### ISSUE TITLE
NuGet exception with TargetFrameworks set in f# proj (fsproj) when using static graph restore

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#10005]
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20454.5

## Repro
```
dotnet new console --language f# --name test1
cd test1
notepad test1.csproj (change `TargetFramework` to `TargetFrameworks`)
dotnet restore /p:RestoreUseStaticGraphEvaluation=true
```

## Error
```
  Determining projects to restore...
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\git\runtime3\.dotnet\test\.dotnet.fsproj. [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateFrameworks(PackageSpec spec, IEnumerable`1 files) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateProjectSpecPackageReference(PackageSpec spec, IEnumerable`1 files) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateProjectSpec(PackageSpec spec) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateDependencySpec(DependencyGraphSpec spec, HashSet`1 projectsToSkip) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.DependencyGraphSpecRequestProvider.GetRequestsFromItems(RestoreArgs restoreContext, DependencyGraphSpec dgFile) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.DependencyGraphSpecRequestProvider.CreateRequests(RestoreArgs restoreContext) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.CreatePreLoadedRequests(RestoreArgs restoreContext) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.GetRequests(RestoreArgs restoreContext) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
C:\git\runtime3\.dotnet\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [C:\git\runtime3\.dotnet\test\.dotnet.fsproj]
```

cc @dsplaisted @nkolev92 

Discovered here: https://github.com/dotnet/runtime/pull/41947/checks?check_run_id=1083056989

**Comment by am11** [comment]
I tried repro steps on macOS and it succeeded:

```sh
$ mkdir ~/.dotnet5
$ curl -sSL https://aka.ms/dotnet/net5/rc1/Sdk/dotnet-sdk-osx-x64.tar.gz | tar xzf - -C ~/.dotnet5
$ ~/.dotnet5/dotnet --version
5.0.100-rc.1.20454.5

$ ~/.dotnet5/dotnet new console --language f# --name test1
$ sed -i '' 's/TargetFramework/TargetFrameworks/g' test1.fsproj 
$ ~/.dotnet5/dotnet restore
$ echo $?
0
```

**Comment by dsplaisted** [comment]
This didn't repro for me with SDK version 5.0.100-rc.1.20453.7 on Windows.

**Comment by dsplaisted** [comment]
@ViktorHofer Try using version 5.0.0-rc.1.20451.14, instead of the latest build out of the branch.  There were some changes that still flowed after the "final" RC1 build which may have broken some things.

**Comment by ViktorHofer** [comment]
@dsplaisted `5.0.0-rc.1.20451.14` doesn't resolve when trying to download it. Is the version string right? Here's the PR: https://github.com/dotnet/runtime/pull/41947/files

**Comment by ViktorHofer** [comment]
> This didn't repro for me with SDK version 5.0.100-rc.1.20453.7 on Windows.

@dsplaisted it does for me at least on OSX: `.dotnet/sdk/5.0.100-rc.1.20453.7/NuGet.RestoreEx.targets(10,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Invalid restore input. Invalid target framework 'unsupported'. Input files: /Users/runner/work/1/s/src/libraries/System.Formats.Cbor/tests/CborDocument/System.Formats.Cbor.Tests.DataModel.fsproj.`

**Comment by am11** [comment]
@ViktorHofer, i think we were not able to the repro you posted in top comment on macOS or Windows. You created the project called `test1` and stacktrace reports `test`. Is it the correct repro?

**Comment by ViktorHofer** [comment]
> There were some changes that still flowed after the "final" RC1 build which may have broken some things.

This was undone with https://github.com/dotnet/installer/commit/53a032d0314ffb281a5ad3ca94eddc421a48b792 which reverted to the "final" RC1 state.

> i think we were not able to the repro you posted in top comment on macOS or Windows.

Just validated it again and found the missing piece. This only happens with static graph restore:

```
dotnet restore /p:RestoreUseStaticGraphEvaluation=true
```

_Updated repro steps and title._

cc @jeffkl

**Comment by jeffkl** [comment]
It might be because you're setting `<TargetFrameworks>` to a single value:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Formats.Cbor/tests/CborDocument/System.Formats.Cbor.Tests.DataModel.fsproj#L4

Can you try just TargetFramework?  NuGet made some major changes around how TargetFramework is read which is causing some breaking changes around how these properties are set in common imports.

**Comment by dsplaisted** [comment]
Static graph build is currently broken, but restore is supposed to work.  So these issues may or may not be related:

https://github.com/dotnet/msbuild/issues/5687
https://github.com/dotnet/sdk/issues/13081

**Comment by jeffkl** [comment]
@dsplaisted static graph is only broken when using `/isolate` I believe.

**Comment by ViktorHofer** [comment]
> It might be because you're setting <TargetFrameworks> to a single value:

My guess was that this is F# related as our 300+ other C# projects don't throw.

> Can you try just TargetFramework?

Yes that works and it unblocks the SDK ingestion in our repo. My remaining concern is if this should be mentioned in release notes / if this should be discussed in Tactics. I doubt this behavior is expected.

**Comment by jeffkl** [comment]
The breaking changes are very subtle, some where because we didn't read a property before and now do which causes restore failures.  I'm not 100% sure what change caused this.  But obviously any notification is better than nothing.

**Comment by ViktorHofer** [comment]
FWIW this happens with multiple tfms as well:

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;netcoreapp3.1</TargetFrameworks>
  </PropertyGroup>
```

**Comment by cartermp** [comment]
Yeah this looks like a major issue, @kevinransom FYI

**Comment by jeffkl** [comment]
@ViktorHofer do you get a different error instead of `Invalid target framework 'unsupported'`?

**Comment by ViktorHofer** [comment]
Still the same error:

```
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1>..\dotnet.exe restore /p:RestoreUseStaticGraphEvaluation=true
  Determining projects to restore...
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error : Invalid restore input. Invalid target framework 'unsupported'. Input files: C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj. [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateFrameworks(PackageSpec spec, IEnumerable`1 files) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateProjectSpecPackageReference(PackageSpec spec, IEnumerable`1 files) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateProjectSpec(PackageSpec spec) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.SpecValidationUtility.ValidateDependencySpec(DependencyGraphSpec spec, HashSet`1 projectsToSkip) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.DependencyGraphSpecRequestProvider.GetRequestsFromItems(RestoreArgs restoreContext, DependencyGraphSpec dgFile) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.DependencyGraphSpecRequestProvider.CreateRequests(RestoreArgs restoreContext) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.CreatePreLoadedRequests(RestoreArgs restoreContext) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.GetRequests(RestoreArgs restoreContext) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\sdk\5.0.100-rc.1.20454.5\NuGet.RestoreEx.targets(10,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [C:\Users\vihofer\Downloads\dotnet-sdk-5.0.100-rc.1.20454.5-win-x64\test1\test1.fsproj]
```

**Comment by am11** [comment]
@jeffkl, I took a diff of c# and f# dumps created with `dotnet5 restore /p:RestoreUseStaticGraphEvaluation=true /v:diag` and these two lines seem to be missing in case of f#:

```diff
-                   InnerBuildProperty = TargetFramework
-                   InnerBuildPropertyValues = TargetFrameworks
```

**Comment by dsplaisted** [comment]
Does F# not import Microsoft.Managed.After.targets?  That seems to be where these properties [are set](https://github.com/dotnet/msbuild/blob/master/src/Tasks/Microsoft.Managed.After.targets#L18-L19).

**Comment by am11** [comment]
I tried adding them like this: https://github.com/am11/fsharp/commit/510c026b2719341a4532f880e171a391606d49f6 in `~/.dotnet5/sdk/5.0.100-rc.1.20454.5/FSharp/Microsoft.FSharp.Targets`, but it has no impact (same error).

**Comment by jeffkl** [comment]
@am11 is correct, the `InnerBuildProperty` and `InnerBuildPropertyValues` aren't set so when Static Graph loads the FSharp projects, so it does not know that the project targets multiple frameworks.

**Comment by jeffkl** [comment]
@am11 For whatever reason, the FSharp targets aren't imported for a cross-targeting build:

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.FSharpTargetsShim.targets#L55-L59

So Microsoft.FSharp.targets isn't imported and your fix isn't enough...

**Comment by am11** [comment]
@jeffkl, right on. This https://github.com/dotnet/sdk/pull/13444, instead, has fixed the issue. 🤣

**Comment by ViktorHofer** [comment]
> @am11 For whatever reason, the FSharp targets aren't imported for a cross-targeting build:

@jeffkl isn't that highly concerning and something that we should look into?

**Comment by jeffkl** [comment]
> isn't that highly concerning and something that we should look into?

Yes we should definitely understand why the targets aren't imported when cross-targeting.  That seems weird to me but I'm sure there's a logical explanation.  I am not familiar at all with the FSharp SDK, who would know more?

**Comment by am11** [comment]
The initial PR which introduced that cross-targeting condition was https://github.com/dotnet/sdk/pull/1172.

**Comment by am11** [comment]
BTW, the same issue happened with IL targets: https://github.com/dotnet/runtime/pull/34124, maybe best place to put these imports would be some common targets in msbuild?

**Comment by nkolev92** [comment]
Just catching up the long discussion. Thanks for the investigation folks!

One thing I wasn't sure if we understand why static graph was failing, but normal restore wasn't. 

The fix to me suggests that both should've been failing. 

@jeffkl @am11 Any ideas?

**Comment by am11** [comment]
@nkolev92, currently (without the fix) `InnerBuildProperty{Values}` are not present with normal (non-static-graph) restore. Perhaps msbuild does not require those in the non-static case (or infer those somehow)?

**Comment by nkolev92** [comment]
@cdmihai to the rescue maybe? :)

**Comment by jeffkl** [comment]
The `InnerBuildProperty` properties are needed for non-static graph restore because NuGet calls targets to determine the target frameworks and subsequent data.  The "static graph" restore is calling the Static Graph API to load projects and their transitive dependencies as well as determine the target frameworks.  Static Graph API does this in a generic way, without having knowledge of target frameworks built in.  Instead, its configured with these properties so it knows how to expand projects' target frameworks.

**Comment by ViktorHofer** [comment]
Fixed by https://github.com/dotnet/sdk/pull/13444
