### ISSUE TITLE
16.10: remove package source 1.0 service. remove obsolete APIs (in nuget.configuration that we added in 16.8)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#10015]
Per @zivkan comment in PR: https://github.com/NuGet/NuGet.Client/pull/3649/files/e70389d28297073fc21d7d03a28c27143c66f290#r485233215

Consider approach for codespaces and these apis:
NuGet.Configuration.IPackageSourceProvider2
NuGet.Configuration.IPackageSourceProvider2.SavePackageSources(System.Collections.Generic.IEnumerable<NuGet.Configuration.PackageSource> sources, NuGet.Configuration.PackageSourceUpdateOptions packageSourceUpdateOptions) -> void
NuGet.Configuration.PackageSourceProvider.SavePackageSources(System.Collections.Generic.IEnumerable<NuGet.Configuration.PackageSource> sources, NuGet.Configuration.PackageSourceUpdateOptions sourceUpdateSettings) -> void
NuGet.Configuration.PackageSourceUpdateOptions
NuGet.Configuration.PackageSourceUpdateOptions.PackageSourceUpdateOptions(bool updateCredentials, bool updateEnabled) -> void
NuGet.Configuration.PackageSourceUpdateOptions.UpdateCredentials.get -> bool
NuGet.Configuration.PackageSourceUpdateOptions.UpdateEnabled.get -> bool
static readonly NuGet.Configuration.PackageSourceUpdateOptions.Default -> NuGet.Configuration.PackageSourceUpdateOptions

**Comment by zivkan** [comment]
I saw and worked on #10098, before discovering this issue, and the other didn't specify a schedule.

Anyway, I've got a branch with the change, ready for a PR: https://github.com/NuGet/NuGet.Client/tree/dev-zivkan-remove-IPackageSourceProvider2
