### ISSUE TITLE
nuget verify ignores NuGet.Config file or trusted-signers list

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10011]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.7.0

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Windows 10 v19041

Worked before? If so, with which NuGet version: No.

## Detailed repro steps so we can see the same problem

1. Generated a self-signed certificate using script found in [docs](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package#create-a-test-certificate)

2. Executed following command to sign the package

`nuget sign "<Package-Path>" -CertificateStoreLocation CurrentUser -CertificateStoreName My -CertificateSubjectName 'NuGet Test Developer' -OutputDirectory "<Output-Path>" -verbosity detailed`

3. Added a [trusted signer](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers) using CLI command to NuGet.Config file (path = `%AppData%\NuGet\NuGet.Config`). `allowUntrustedRoot` is set to `true`.
``` xml
  <trustedSigners>
    <author name="ClassLibrary16">
      <certificate fingerprint="<Removed>" hashAlgorithm="SHA256" allowUntrustedRoot="true" />
    </author>
  </trustedSigners>
```
4. Executed `nuget verify "<Package-Path>" -Signatures -ConfigFile "<Path to Config File>"` and `nuget verify "<Package-Path>" -Signatures` commands which failed to verify the package with the following error message.

```
Signature Hash Algorithm: SHA256
WARNING: NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired.
Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=NuGet Test Developer, OU=Use for testing purposes ONLY
  SHA1 hash: <Removed>
  SHA256 hash: <Removed>
  Issued by: CN=NuGet Test Developer, OU=Use for testing purposes ONLY
  Valid from: <Removed>

NU3018: The author primary signature found a chain building issue: UntrustedRoot: A certificate chain processed but terminated in a root certificate which is not trusted by the trust provider.
The author primary signature's certificate chain validation failed with error(s): UntrustedRoot
Finished with 1 error and 1 warning.
``` 
@heng-liu pointed me to a similar issue reported in [stackoverflow ](https://stackoverflow.com/questions/59179504/cant-verify-signatures-with-nuget)

/cc @dtivel @zkat @aortiz-msft

**Comment by erdembayar** [comment]
Solving as part of https://github.com/NuGet/Home/issues/10774
