### ISSUE TITLE
Project is not eligible for migration. Either Project is not Packages.config based or does't support the package reference Yet.

### ISSUE THREAD

**Issue by Naresh1277** [NuGet/Home#10014]
Attached the screen shot
![Capture](https://user-images.githubusercontent.com/11494691/92627256-1a193880-f299-11ea-87c1-1ef44f911b88.PNG)

**Comment by heng-liu** [comment]
Thanks for reporting this issue.
We have a list of issues when migrating from Packages.config to Package reference.
So closed it as duplicate.
Pls let us know to reopen it if the situation is not in the list https://github.com/NuGet/Home/issues/5877

**Comment by GaTechThomas** [comment]
For others who arrive at this page via search engines, the following 2-minute solution may save you a ton of time:

https://stackoverflow.com/a/65701746/284598
