### ISSUE TITLE
“Installing” instead of “Updates” show in the “Preview Changes” dialog when updating all package in PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10024]
## Details about Problem
NuGet version: NuGet Client dev-feature-OE.PMUI\5.8.0.12792
VS Version: Main\30510.142
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. On a clean VM, launch VS, create an ASP.NET Web Application-Web Forms (.NET Framework 4.8), go to “Updates” tab, check “Select all packages” check-box (uncheck the bootstrap package) and click “Update” button.
2. **(Don’t close the solution/VS)** Click File->New->Project and click the template “ASP.NET Web Application (.NET Framework 4.8)”.
3. Type the project name, click the “Create” button and select “Single Page Application”.
4. Open project PM UI, click “Updates” tab, check “Select all packages” check-box and click “Update” button.
5. Observe the "Preview Changes" dialog.
Note: You can also see this issue 10024 occurs in the latest attached git file of bug [10263](https://github.com/NuGet/Home/issues/10263).
## Expected
There should be “Updates” info in the “Preview Changes” dialog as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/92928352-8a7ab200-f471-11ea-928f-6a261fe9b3b1.png)
## Actual
There is “Installing” info instead of “Updates” in the “Preview Changes” dialog as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/92928484-b8f88d00-f471-11ea-8624-32b5228bd90b.png)
## Notes
1.	It doesn’t repro when updating package one by one.
2.	It doesn’t repro on D16.8\30509.190 with Implicit NuGet Client release-5.8.0-preview.3\5.8.0.6823.
3.     Only repro with the update button in step4. Doesn't repro on other updating way.
4.     It doesn't repro when creating the second project after closing the solution/VS in step2.

**Comment by dtivel** [comment]
@v-luzh, I did not reproduce this bug.  I tested with the same feature branch build and the same repro steps.  I observed the expected results --- 1 package under "Installing" and the remaining packages under "Updates".

(I did not use the same OS or VS build, but I don't believe they are relevant.)

Are you sure that the feature branch VSIX installed successfully?  Can you please reconfirm this bug that this bug reproes with the specified feature branch build and repro steps?

**Comment by v-luzh** [comment]
@dtivel, OK I will have a verify today and let you know the result later.

**Comment by v-luzh** [comment]
@dtivel, yes you are right, it doesn't repro on VS Main\30515.165 + NuGet Client dev-feature-OE.PMUI\5.8.0.12792. That was so weird I saw this bug last Friday as the screenshot above.

**Comment by dtivel** [comment]
Please reactivate with updated repro steps if you can repro it later.

**Comment by v-luzh** [comment]
Hey @dtivel, this bug repro on Main\30801.165 + NuGet Client Dev\5.9.0.6976. The key point to repro are: creating a new project on an opened solution (don't close the solution or VS when creating a new), use the "Update" button after checking “Select all packages” check-box (described in step3). Please have a look, thanks.

**Comment by nkolev92** [comment]
Triage:
Bringing this on top of your notification list.

**Comment by dtivel** [comment]
@v-luzh, can you please update this issue with:
* build information for the most recent VS + NuGet configuration you've verified that this bug reproes on
* complete repro steps
    * start with freshly launched Visual Studio instance with no open solution
    * describe each project added

On VS main/30911.23 I tried creating a C# Console Application (.NET Framework) project with no packages, added an "ASP.NET Web Application (.NET Framework)” project, opened PM UI for only the web project, and tried to update all packages.  I saw "Updates" instead of "Installing"

**Comment by v-luzh** [comment]
Hi @dtivel Update all the info.
## Build Info
NuGet version: NuGet Client dev\5.9.0.7028
VS Version: Main\30912.243
OS: Windows-10-Enterprise-19H2
## Repro Steps
1. On a clean VM, launch VS, create an ASP.NET Web Application-Web Forms (.NET Framework 4.8), go to “Updates” tab, check “Select all packages” check-box (uncheck the bootstrap package) and click “Update” button.
2. **(Don’t close the solution/VS)** Click File->New->Project and click the template “ASP.NET Web Application (.NET Framework 4.8)”.
3. Type the project name, click the “Create” button and select “Single Page Application”.
4. Open project PM UI, click “Updates” tab, check “Select all packages” check-box and click “Update” button.
5. Observe the "Preview Changes" dialog.
Note: You can also see this issue 10024 occurs in the latest attached git file of bug [10263](https://github.com/NuGet/Home/issues/10263).

**Comment by dtivel** [comment]
Hit https://github.com/NuGet/Home/issues/10510 while trying to repro this.

**Comment by dtivel** [comment]
@v-luzh, would you please verify this on the latest dev branch build (>= 5.10.0.7096)?

When I perform your latest repro steps on the latest dev branch, step 1 ends with this error:

![image](https://user-images.githubusercontent.com/12734758/106608775-aca4c780-6519-11eb-9782-9daf3147dfc2.png)

This error repros on older builds (e.g.:  16.8.x and older).

Then, step 5 ends with this Preview Changes dialog:

![image](https://user-images.githubusercontent.com/12734758/106608910-cf36e080-6519-11eb-9797-b22979634410.png)

**Comment by v-luzh** [comment]
Hi @dtivel, I can repro this issue on Main\31002.208 + NuGet Client Dev\5.10.0.7096 **in step5** as below. Please uncheck the "bootstrap" package when you see the incompatible issue, and go on the step2-5 in above steps. (Please refer to above updated steps since the bug 1160376 is fixed). 
![image](https://user-images.githubusercontent.com/20632625/106715879-a0635c00-6638-11eb-8e5c-a37ef5afb28d.png)

**Comment by dtivel** [comment]
Reproes in standalone.

**Comment by v-luzh** [comment]
Hi @dtivel This bug is fixed on Main\31101.164 + NuGet Client Dev\5.10.0.7152. Thanks for your fixing.

**Comment by dtivel** [comment]
Great, @v-luzh.  Thanks for verifying.
