### ISSUE TITLE
NuGet.exe pack generates bad package when TFM has a platform

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#10025]
When packing a project with `nuget.exe`, when the project has a net5.0 platform, the platform is stripped from the destination in `lib` inside the nupkg, and the pack then warns because it thinks `net5.0-<platform>` is just `net5.0`.

A similar but not identical issue happens with dotnet pack: https://github.com/NuGet/Home/issues/10020

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.8.0.7137 (built from latest `main`)

OS version (i.e. win10 v1607 (14393.321)): win10

## Detailed repro steps so we can see the same problem

1. mkdir nuget-repro && cd nuget-repro && dotnet new wpflib
2. nuget pack
3. look in the .nupkg lib directory

### Results
```
❯ ..\nuget\artifacts\NuGet.CommandLine\16.0\bin\Debug\net472\NuGet.exe pack
Attempting to build package from 'bar.csproj'.
MSBuild auto-detection: using msbuild version '16.8.0.45203' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Current\bin'.
Packing files from 'C:\Users\kmarchan\src\bar\bin\Debug\net5.0-windows'.
WARNING: NU5118: File 'C:\Users\kmarchan\src\bar\bin\Debug\net5.0-windows\ref\bar.dll' is not added because the package already contains file 'lib\net5.0\bar.dll'
...
WARNING: NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below:
- Add a dependency group for net5.0 to the nuspec
Successfully created package 'C:\Users\kmarchan\src\bar\bar.1.0.0.nupkg'.
```

**Comment by nkolev92** [comment]
nuget.exe pack with PackageReference projects is sort of broken by design right now, so I wouldn't be concerned about this scenario too much: https://github.com/NuGet/Home/issues/4491

**Comment by zkat** [comment]
Yeah. I'm just gonna close it, then :)
