### ISSUE TITLE
Docs for NuGet.Protocol API 5.7.0 are out-of-date

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#10023]
I'm trying to use NuGet.Protocol 5.7.0 and following this guidance the sample doesn't compile:

https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

Repository.Factory doesn't have a GetCoreV3 method:
![image](https://user-images.githubusercontent.com/679326/92838426-9d1eb980-f393-11ea-9c8a-de2606e4b978.png)

**Comment by nkolev92** [comment]
This should be the type: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Repository.cs

I think the sample might be missing the namespace for the repository. 

Can you try checking the `using` statements?

**Comment by KirillOsenkov** [comment]
Yes, probably missing extension methods. This is not very intuitive.

**Comment by zivkan** [comment]
I agree. I propose the following APIs:

```cs
public class RepositoryFactory
{
  public SourceRepository CreateSourceRepository(string source, FeedType type);
  public SourceRepository CreateSourceRepository(string source);
  public SourceRepository CreateSourceRepository(PackageSource source);
}
```

Justification:
* Changing the namespace of the existing extension methods is an ABI breaking change.
* Copying the extension methods in a new class with the same namespace as the type, such that additional `using` expressions are not needed (and the sample code still works as-is), will likely result in ambiguous method errors in any code that does have the additional `using` expressions.
* `GetV2` and `GetV3` return the same value. It's not the caller's responsibility to determine whether a source uses the V2 or V3 protocol. Let's use a generic name that represents that, plus fits better with a factory naming pattern/convention.

Drawbacks:
* We will need to change the sample, and explain that it only works for NuGet.Protocol version x.y or higher. Also need to consider if we add a comment explaining what to do with older versions of NuGet.Protocol, which we can remove in the future once these new APIs have been shipped in multiple versions of our nupkgs.


Alternatively, we could just add a comment to the sample to say add `using NuGet.Protocol;`.

Comments?

**Comment by nkolev92** [comment]
I think it makes sense to add a comment for now. 

The APIs are not perfect, but I don't think it's worth the hassle of changing namespaces right now.
