### ISSUE TITLE
Log package source in .nupkg.metadata

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#10022]
Suggestion that would greatly improve developer's life everywhere multiple feeds are used:

when NuGet restores a package version into the global package cache, write a file called provenance.txt which logs which package source the package was restored from and at what time.

This will greatly help locate which source a package came from.

**Comment by KirillOsenkov** [comment]
Should use `.nupkg.metadata` which is perfect for this scenario.

Log which source, time of restore and which project/sln/packages.config if available.

**Comment by zkat** [comment]
Related to https://github.com/NuGet/Home/issues/8529

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/3785, Dup of https://github.com/NuGet/Home/issues/10354
