### ISSUE TITLE
Can PackageReference specify source (private gallery)?

### ISSUE THREAD

**Issue by miloush** [NuGet/Home#10031]
Hey, just a question - is there a way for a project file to specify (or add) NuGet source that should be used for resolving PackageReferences?

**Comment by dominoFire** [comment]
You can specifiy a custom NuGet source feed using:

1. A NuGet.Config file at solution level. See https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses
2. `RestoreAdditionalProjectSources` property in your project file or in command line, e.g., `dotnet restore myproject.csproj /p:RestoreAdditionalProjectSources=https://api.nuget.org/v3/index.json;https://myprivatefeed.org`. See https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties
