### ISSUE TITLE
Package Manager Console crashes on loading Visual Studio

### ISSUE THREAD

**Issue by EthanHotz-Reisys** [NuGet/Home#10036]
## Details about Problem

NuGet product used: 
Package Manager Console v5.7.0

VS version (if appropriate): 
VS19, version 16.7.3

OS version:
Windows 10 Pro v1909, OS Build 18363.1082

Worked before? If so, with which NuGet version:
The Package Manager Console seemed to simply break a few days ago, after installing Windows 10 updates, but I'm unable to rollback my system to confirm this.

Error message:
Method not found: 'Void System.Management.Automation.ExecutionContext.MarkObjectAsUntrusted(System.Object)'.

From my testing, it seems as though there is some issue with Powershell within Visual Studio. I'm able to open Powershell outside of VS just fine, but opening the Package Manager Console or Powershell Command Explorer(using Powershell Tools for Visual Studio extension) within VS throws the above error message.

I've attempted a number of reinstalls/upgrades/repairs across VS17 and VS19, but this issue persists across all projects.

**Comment by dominoFire** [comment]
@EthanHotz-Reisys Can you try to repro the issue with a VS instance without custom plugins?

Do you have a [custom profile](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_profiles?view=powershell-7) that could affect PowerShell initialization? For example:

%USERPROFILE%\Documents\WindowsPowerShell\NuGet_profile.ps1
%USERPROFILE%\Documents\WindowsPowerShell\PoshTools_profile.ps1

**Comment by EthanHotz-Reisys** [comment]
@dominoFire I am seeing this issue across fresh VS instances with no extensions installed, both VS17 and VS19.

I don't have any custom profiles for Powershell that I'm aware of.

**Comment by aortiz-msft** [comment]
@v-luzh  - Would you please try to repro on same OS version?

**Comment by v-luzh** [comment]
@aortiz-msft, We cannot repro it on VS 16.7.3 with Windows 10 Pro v1909, OS Build 18363.1082 (same VS and OS version with customer) after installing the Win10 Updates. The Package Manager Console works well and there is no error message, and the PowerShell Tools for Visual Studio works well for me.

**Comment by EthanHotz-Reisys** [comment]
I ended up reinstalling Windows to fix this issue; not sure what the cause might have been, but everything is working now.

**Comment by aortiz-msft** [comment]
Sorry to hear about your experience @EthanHotz-Reisys, but I'm relieved you got unblocked.
