### ISSUE TITLE
DotnetCLiToolReference restores make it difficult to reason about no-op projects count/uptodateprojectscount

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10038]
Take a sample project such as the below: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
</Project>
```

The https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/RestoreTelemetryEvent.cs initially report the following: 

| Restore type | NuGetProjectsCount | NoOpProjectsCount | UpToDateProjectsCount |
|-|-|-|-|
| Implicit | 1 | 0 | 0 | 
| On Build | 1 | 2 | 2 | 

The reason why this happens is that DotnetCLiToolReference is a special restore that generates an assets file, but not nuget.g.* files. Furthermore these assets live in a special location. 

This would make any assumptions based on NoOpProjects count slightly incorrect. 
Good news is that DotNetCliToolReference is not super common, but it is challenging as far as analysis goes. 

cc @aortiz-msft @dominoFire 

This affects all our analysis. We should probably decide what actions/if any we can take sooner rather than later.

**Comment by dominoFire** [comment]
I suspect the problem lies on SolutionUpToDateCheck ; it's the only place in which both counters could have the same value without taking projectsCount as an input.

https://github.com/NuGet/NuGet.Client/blob/5a70626fbcf6d38f0c6c6fc3c96950959ccb70be/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs#L390-L391

**Comment by nkolev92** [comment]
The problem is how we calculate the counters. 
The checker returns the unique names, so we can correlate using that.

**Comment by dominoFire** [comment]
By reviewing SolutionUpToDateChecker code, it only works if the project is PackageReference or ProjectJson, see:

https://github.com/NuGet/NuGet.Client/blob/1dd5351295a5a0d092abcd2bd82ccbd730682dbe/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionUpToDateChecker.cs#L105

For the other hand, when the original dependency graph is calculated, it includes projects and DotNetCliToolReferences as well, see below.

https://github.com/NuGet/NuGet.Client/blob/1dd5351295a5a0d092abcd2bd82ccbd730682dbe/src/NuGet.Clients/NuGet.SolutionRestoreManager/SolutionRestoreJob.cs#L381

Now, when the solution restore dependency graph is calculated in `GetSolutionRestoreSpecAndAdditionalMessages(ISolutionManager, DependencyGraphCacheContext)`, it first calculates the packages 

https://github.com/NuGet/NuGet.Client/blob/1dd5351295a5a0d092abcd2bd82ccbd730682dbe/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/DependencyGraphRestoreUtility.cs#L328

Later, it adds the packages alongside with the project to the graph.

https://github.com/NuGet/NuGet.Client/blob/1dd5351295a5a0d092abcd2bd82ccbd730682dbe/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/DependencyGraphRestoreUtility.cs#L342

Debugging a little bit for a PackageReference project, when the project spec is calculated at [`GetPackageSpecsAndAdditionalMessagesAsync()`](https://github.com/NuGet/NuGet.Client/blob/1dd5351295a5a0d092abcd2bd82ccbd730682dbe/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L153) , it seems that TryGetRestoreInfo() gets a cached dependency graph that already contains the DotNetCliToolReference's as projects.

Quick fix to this counter is just to substract from counter variable projects that are not PackageReference, PackagesConfig or ProjectJson.

Long term fixt would be to remove DotNetCliToolReference from the _project restore graph_ and apply the check only to that graph.

**Comment by dominoFire** [comment]
Note: The checker only returns projects, not DotNetCliToolRestore packages/projects.
