### ISSUE TITLE
Trouble accessing files in Nuget package when using Packagereference

### ISSUE THREAD

**Issue by anishgk80** [NuGet/Home#10033]
We are using Nuget package to share a commonly used Class Library project. The class library uses certain Files (xml) which is accessed in few of the functions in the library. While consuming the package we are using 'packagereference' insted of 'package.config'. Problem is the functions that refer to the files (xml) start failing with error 'path not found'. 

The below was tried to fix the error but with no result
- Copy To Output directory option is set on all the xml files that the program refer to.
- Files section was added with reference to the xml files in "*.nuspec" file 

The xml files are seen in the content section of the nuget package. The file names are also seen in the 'project.assets.json'. But with 'package reference' the required files are not getting copied to the base directory of the application consuming the nuget package, which is causing the program to fail. Is there a way to solve this ?

**Comment by dominoFire** [comment]
@anishgk80 `copyToOutput="true"` in `contentFiles` section makes the asset to be copied by the project.

https://github.com/NuGet/Samples/blob/6343202364bce017f14cc79921adcba7919252b1/ContentFilesExample/ExamplePackage.WithContentFiles-nuspec/ContentFilesExample.nuspec#L17

**Comment by dominoFire** [comment]
I will close the issue since this looks like a question. If you need more help, feel free to reply or open a new issue.
