### ISSUE TITLE
update verify command description 

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10046]
Update `nuget verify` command description because `Verify is meant to do more than just signatures eventually. `

This feedback applies to [`nuget verify`](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-verify) and `dotnet nuget verify` command that will be available soon in `dotnet CLI`.

`Verify` command description for `nuget.exe` is fetched from [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/NuGetCommand.resx#L5388) and for `dotnet.exe` the description is fetched from [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx).

**Comment by aortiz-msft** [comment]
We can update the description whenever we decide to implement further verifications as part of the verify command. Recommendation to close this issue.

**Comment by zivkan** [comment]
Triage: closing as per above comments.
