### ISSUE TITLE
Use [AppliesToProject] on IAttachedCollectionSourceProvider implementations

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#10044]
Visual Studio has recently [added `[AppliesToProject]`](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/271500) support for `IAttachedCollectionSourceProvider` providers, which can be used to prevent unneeded dlls. NuGet should use this for all their implementations to avoid unneeded loads of this dll in projects/solutions where it is not applicable, for example:

``` C#
    [Export(typeof(IAttachedCollectionSourceProvider))]
    [Name(nameof(PackageReferenceAttachedCollectionSourceProvider))]
    [Order(Before = HierarchyItemsProviderNames.Contains)]
    [AppliesToProject("DependenciesTree")] 
```

This is required to fix this [performance gate that was broken](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1136214) that got an exception for 16.7.

**Note:** Similar to UI contexts for commands/packages this only controls whether your implementation is loaded for a given solution. You will still be called back for projects that do not contain these capabilities and you will need to continue to handle this.

**Comment by panopticoncentral** [comment]
@nkolev92 or @aortiz-msft can you add an "Area:SolutionLoad" tag to this issue so we see it in the perf backlog?

**Comment by nkolev92** [comment]
@panopticoncentral done.
