### ISSUE TITLE
SDK side implementation for dotnet nuget verify command

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10050]
`NuGet.Client` side work was completed for `dotnet nuget verify command` and can be tracked [here](https://github.com/NuGet/Home/issues/8051).

This task is created to track SDK side implementation for this new command. https://github.com/dotnet/sdk/issues/13702

**Comment by zkat** [comment]
@kartheekp-ms hey, why was this moved back to New Issues?

**Comment by kartheekp-ms** [comment]
@zkat - Looks like it was by mistake. Thanks for moving this to backlog again.
