### ISSUE TITLE
NuGet Packages Failing to Download in Visual Studio 2015 RTM

### ISSUE THREAD

**Issue by MisterJames** [NuGet/Home#1005]
I haven’t figured out a common theme yet, but certain packages are failing to restore when you attempt to install them from the NuGet primary feed via the project.json file in Visual Studio 2015. Intellisense is also not picking up the package names from the feed.

A couple of things I’ve discovered:
- This seems to be more common for prerelease packages
- It seems to work if the package has a previous release version (not in pre)

Here's a shot of me trying to get AutoFac.Framework.DependencyInjection installed from file->new->project:

![image](https://cloud.githubusercontent.com/assets/1197383/8854064/8eeef880-3123-11e5-9b58-11805a921a44.png)

As a workaround, you can add the packages manually via the dialog in Visual Studio if you allow pre-releases:

![image](https://cloud.githubusercontent.com/assets/1197383/8853991/21a4cafc-3123-11e5-8337-ee7d49c1235e.png)

**Comment by emgarten** [comment]
@MisterJames what is the error message you get when the restore fails on project.json?

Here the UI just writes the name and version into the project.json file for you, are you able to restore this package when ignoring the incorrect intellisense and just writing in the full name AutoFac.Framework.DependencyInjection and version 4.0.0-beta5-90?

It sounds like project.json intellisense might be the only bug here.

**Comment by MisterJames** [comment]
Hrm...I'm actually having trouble verifying that right now. 

I just did the following:
 - removed the package from the project.json
 - saved the file (the restore ran)
 - closed VS2015
 - removed the package from the cache at %LOCALAPPDATA%\NuGet\Cache\
 - reopened the solution in VS

But strangely, I think I'm getting cache hits?

![image](https://cloud.githubusercontent.com/assets/1197383/8865730/1bed8d96-3179-11e5-8ed8-9becc738e646.png)

So, where else does the package hang around?

**Comment by MisterJames** [comment]
@emgarten  One more update.

I disabled the AutoFac package source and then closed/reopened Visual Studio. With the complete package name in there, the package could not be restored, and the build fails.

![image](https://cloud.githubusercontent.com/assets/1197383/8865915/b84cfecc-317b-11e5-8b13-cc937de721c1.png)

And in the output I see this:

     OK https://www.nuget.org/api/v2/FindPackagesById()?id='Autofac.Framework.DependencyInjection' 1333ms
     Unable to locate Autofac.Framework.DependencyInjection >= 4.0.0-beta5-92
     ...
     Errors in C:\[my path]\project.json
     Unable to locate Autofac.Framework.DependencyInjection >= 4.0.0-beta5-92

I'm re-enabling the alternate package source so I can keep working, but

**Comment by emgarten** [comment]
This looks like a DNU issue, please log the bug here: https://github.com/aspnet/Home/issues

DNU uses %USERPROFILE%\.dnx for the cache, it does not share the same NuGet packages cache folder.

The 4.0.0-beta5-92 version of that package is not on nuget.org so the output message you pasted looks correct, however you mention other feeds so it may be possible that DNU is not picking up that feed or finding the package there.

**Comment by MisterJames** [comment]
Ah, good eye on the version, thanks @emgarten.  And thanks for pointing me to the DNU package cache.

I'm closing the issue, but I'm still curious about the IntelliSense...does it not pick up -pre packages?

**Comment by emgarten** [comment]
It picks up prerelease packages, it's possible the server index was behind in indexing this package for the intellisense endpoint. It should also find it in your global packages folder.
