### ISSUE TITLE
Add telemetry for NuGet's VS extensibility API faults

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10062]
NuGet's [VS extensibility APIs](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio) usually should not throw exceptions. Currently, we have no visibility when they do throw, and require customers to report problems to us.

This is particularly an issue for the new [brokered services](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Contracts/NuGetServices.cs), because all exceptions get deserialized as a single exception type, and the stack trace is lost, so customers are unable to report detailed failures to us.

**Comment by nkolev92** [comment]
In the stack trace I see an NPE. Is the NPE expected/side-effect of how we use it?

It's similar to what @erdembayar is looking into at https://github.com/NuGet/Home/issues/10070. 

cc @aortiz-msft

**Comment by zivkan** [comment]
I'm not sure about the NRE, but the empty sequence exception when `GetInstalledPackages` is called when the TFMs listed in the assets file does not match the list of TFMs defined in the csproj. It's a bug from https://github.com/NuGet/NuGet.Client/pull/3539 where it doesn't handle this edge case.
