### ISSUE TITLE
Nuget PMC memory usage - Add new telemetries to track events related to PMC and Powershell usage.

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10069]
Child of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1167790.

Recently decided not to act on [decrease PMC usage](https://github.com/NuGet/Home/issues/9988) issue. We suspect it's highly unlikely problem to happen. To better understand this problem we add this telemetries. This one is for writing the spec.

**Comment by erdembayar** [comment]
I created this [PR#582](https://github.com/NuGet/Client.Engineering/pull/582/files) for spec. 
@nkolev92  Please review.

**Comment by nkolev92** [comment]
In review.

**Comment by nkolev92** [comment]
I imagine this is completed?

Can you make sure all the respective PRs are completed as well. Example: https://github.com/NuGet/Client.Engineering/pull/582

**Comment by erdembayar** [comment]
Yes, this one is completed.
I created this follow [NugetIssue#10499](https://github.com/NuGet/Home/issues/10499) for dashboards.

**Comment by nkolev92** [comment]
That issue belongs to client.engineering. 

I moved it. 

Can you please make sure the home PR doesn't stay open?

**Comment by erdembayar** [comment]
@nkolev92 
Sure. I wasn't sure about telemetry dashboard thing and was waiting for 1:1 to ask. But you caught it up before my 1:1.
