### ISSUE TITLE
Can't use Package Manager Console from VS15

### ISSUE THREAD

**Issue by eestein** [NuGet/Home#1007]
Issue #842 is closed as invalid, but it is not.
Nuget is not working in VS15, checking the reviews at VisualStudio Gallery it seems it IS a general problem. https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d
Are you guys aware of the problem? ETA on a fix? Thanks.

**Comment by emgarten** [comment]
@eestein are you seeing https://github.com/NuGet/Home/issues/974 or is this a different issue? What state is the powershell console in when you open it?

**Comment by eestein** [comment]
@emgarten Hey, thanks for replying. No, I'm getting a CommandException, not PermissionDenied. I'm using the PackageManagerConsole inside Visual Studio 2015 and its state is standard: `PM >` Let me know if there's anything else I can do to help.

**Comment by emgarten** [comment]
Would you paste your output? Are you getting the same exception as 842?

**Comment by eestein** [comment]
The exact same thing, the only difference is the package :)

**Comment by emgarten** [comment]
What package are you trying to install? What are your package sources? Are you able to install any packages with install-package?

**Comment by eestein** [comment]
UpDevs.Framework.Data. Standard, MS and Nuget ones. Now yes, I just ran a Windows Update and it started to work for some packages using the GUI, not the PM though. I don't know if it was something related to my computer or some actual update... anyway, I can use the GUI and it worked for package UpDevs.Framework.Utils, but it's not working for Data. Could it be something on my end? Now that it worked for the first case, I'm thinking that's very likely...

**Comment by emgarten** [comment]
Try adding https://www.nuget.org/api/v2/ as another source, and let me know if that improves anything.

**Comment by eestein** [comment]
Like a charm! Thanks! :)
