### ISSUE TITLE
ContentFiles, PackageReference, support providing custom metadata for individual files 

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [NuGet/Home#10073]
## Details about Problem

NuGet product used VS UI

NuGet version (5.7.0):

VS version (16.7.4):

OS version (WIndows 7 x64 SP1):

## suggested

in nuspec file

```xml
<metadata>
    <contentFiles>
      <files include="cs\any\MyCS.cs" buildAction="Compile" copyToOutput="false"/>
    </contentFiles>
</metadata>
```
This item is generated in memory at Build time:

```xml
<ItemGroup>
    <Compile Include="Program.cs"/>
</ItemGroup>
```

But sometimes we need to attach some Metadatas(like CustomToolNamespace).
For example:
```xml
<ItemGroup>
    <Compile Include="Program.cs">
      <CustomToolNamespace>MMM</CustomToolNamespace>
      </Compile>
</ItemGroup>
```
Can we support specifying the Metadata ourselves? like this:
```xml
<metadata>
    <contentFiles>
      <files include="cs\any\MyCS.cs" buildAction="Compile" copyToOutput="false">                      
               <CustomToolNamespace>MMM</CustomToolNamespace>
               <MyMetadata>This is my MyMetadata</MyMetadata>
      </files>
    </contentFiles>
</metadata>
```

then in memory, create this item:
```xml
<ItemGroup>
    <Compile Include="Program.cs">
      <CustomToolNamespace>MMM</CustomToolNamespace>
      <MyMetadata>This is my MyMetadata</MyMetadata>
    </Compile>
</ItemGroup>
```

What do you think?

**Comment by nkolev92** [comment]
Thanks for this request @mingkuang-Chuyu 

What is a practical example of additional metadata?

For example, content files coming from packages are already tagged with: 

```xml
       <NuGetPackageId>ContentFilesExample</NuGetPackageId>
      <NuGetPackageVersion>1.0.2</NuGetPackageVersion>
```

I am not suggesting this is sufficient ofc, just trying to understand a real world application :)

**Comment by zkat** [comment]
@mingkuang-Chuyu we haven't heard back from you, so we're going to close this now. Please feel free to file a new issue if this is still a priority for you.
