### ISSUE TITLE
VS OE:  propagate exceptions consistently from service to client

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10088]
Client code that was moved behind a VS OE service now has the potential of throwing a `StreamJsonRpc.RemoteInvocationException` where it threw some other exception type before.  In client code we sometimes have [specialized error reporting based on exception type](https://github.com/NuGet/NuGet.Client/blob/ba87e7e45851add0e46a217c14fa2c95973244a9/src/NuGet.Clients/NuGet.PackageManagement.UI/UserInterfaceService/NuGetUI.cs#L358-L405), so we should rethink this when VS OE services are involved.

**Comment by dtivel** [comment]
https://github.com/NuGet/Home/issues/10034 and https://github.com/NuGet/Home/issues/10070 are 2 examples where the unexpected exception type `StreamJsonRpc.RemoteInvocationException` affected our error reporting.

**Comment by rrelyea** [comment]
Moving out of 16.9. We'll maintain and improve 16.8 solution for now. Unsure when we'll move to better overall solution. Current blocked by VS SDK bug.

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
