### ISSUE TITLE
Warning for warning NU5128 when packastool with targetframework alias

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10097]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 9:03:56 PM_

Given
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>targetframeworkAlias</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <OutputType>exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'targetframeworkAlias' ">
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v3.1</TargetFrameworkVersion>
    <TargetFrameworkMoniker>.NETCoreApp,Version=v3.1</TargetFrameworkMoniker>
  </PropertyGroup>

</Project>

```

run dotnet pack. There will be an extra necessary warning:
```
C:\work\sdk3\artifacts\bin\redist\Debug\dotnet\sdk\5.0.100-dev\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [C:\work\temp\nugetalias\nugetalias.csproj]
C:\work\sdk3\artifacts\bin\redist\Debug\dotnet\sdk\5.0.100-dev\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): warning NU5128: - Add lib or ref assemblies for the netcoreapp3.1 target framework [C:\work\temp\nugetalias\nugetalias.csproj]
```

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 9:04:56 PM_

Still have the issue after https://github.com/dotnet/sdk/pull/13924 fix

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 9:10:29 PM_

@nkolev92 I don't think it is a blocking issue. But any idea about the cause?

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @marcpopMSFT.

---

_From @marcpopMSFT on Wednesday, September 30, 2020 9:10:29 PM_

@nkolev92 should this go to NuGet?

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @nkolev92.

---

_From @nkolev92 on Wednesday, September 30, 2020 9:36:20 PM_

@wli3 
Can you post the content of the package when you run it with and without an alias? (nuspec too)

When did this warning start happening?

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 9:43:13 PM_

[nugetalias.1.0.0-with-alias.zip](https://github.com/dotnet/sdk/files/5308396/nugetalias.1.0.0-with-alias.zip)
[nugetalias.1.0.0.without-alias.zip](https://github.com/dotnet/sdk/files/5308398/nugetalias.1.0.0.without-alias.zip)

changed the nupkg suffix to zip since github does not allow me to upload that

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 9:45:03 PM_

![image](https://user-images.githubusercontent.com/6993335/94743003-7f59ca00-032b-11eb-802e-47caf6f4e904.png)

interesting. Everything else is the same

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @nkolev92.

---

_From @nkolev92 on Wednesday, September 30, 2020 9:50:06 PM_

Is `SuppressDependenciesWhenPacking` being set anywhere, or it just NuGet doing something different?

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 10:32:38 PM_

It should be set no matter alias or not. But even when i use `dotnet pack /p:SuppressDependenciesWhenPacking=true` the error still shows

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @nkolev92.

---

_From @nkolev92 on Wednesday, September 30, 2020 10:43:35 PM_

The existence of the dependencies element is what is causing the warning to appear. 

Is the alias the only difference between the projects? 
If that's the case, I think we should mvoe it to NuGet so we can investigate further.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#13928**
- Please respond to @wli3.

---

_From @wli3 on Wednesday, September 30, 2020 10:50:50 PM_

Yes the only difference is `<TargetFramework>targetframeworkAlias</TargetFramework>` vs `<TargetFramework>netcoreapp3.1</TargetFramework>`

Moving to nuget

**Comment by nkolev92** [comment]
There's a bug and SupressDependenciesWhenPacking is not respected in some cases. 
cc @zkat 

Bug probably in https://github.com/NuGet/NuGet.Client/blob/f88ad395c062c98a60ba3084e99f5476106e00d0/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L224-L229
