### ISSUE TITLE
Design and cost Dotnet nuget sign

### ISSUE THREAD

**Issue by aortiz-msft** [NuGet/Home#10090]

**Comment by dtivel** [comment]
@zkat already spec-ced the feature.  See [this](https://github.com/NuGet/Home/pull/9945).

- [ ]  [15 hours]  Add a new dotnet `sign` at src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/Signing/SignCommand.cs.
    *  Note that this new command should perform similar input validation as the existing NuGet.exe `sign` command at src/NuGet.Clients/NuGet.CommandLine/Commands/SignCommand.cs.  For example, some option combinations are invalid/required.
    *  Because the `<package-path>` argument can expand to multiple packages, the new `sign` command must support multiple packages.  (I think the spec has a [typo](https://github.com/NuGet/Home/blob/dev/designs/DotNetSignCommands.md#dotnet-nuget-sign) in that the `sign` usage example should show `<package-path>...*` as the `verify` command does.)  `SignArgs.PackagePath` should be deprecated in favor of a new `IReadOnlyList<string> PackagePaths` property.
- [ ]  [10 hours]  Respect the `--interactive` option.  Note that the option has flipped from NuGet.exe's `-NonInteractive` option.
    *  See all comments in https://github.com/NuGet/NuGet.Client/pull/3069.  
    *  Propagating the `NonInteractive` option from `SignArgs` in `SignCommandRunner` seems like the best option.
    *  If the default behavior must change as a result of this work, please sync with Claire Novotny.
    *  It may be worth adding a test for the non-interactive case.  The test may actually be provided by a later task below.
- [ ]  [5 hours]  Add basic tests for `dotnet sign` that verify on all platforms:
    *  Exit code, output, errors, etc. for argument validation failures.
    *  With valid arguments the command creates a good, signed package.
- [ ]  [10 hours]  Expand `SignCommandRunner` tests to verify different options on all platforms.
    *  When the certificate is a file path.
    *  When the certificate is in a certificate store.
    *  When the certificate is password-protected.
- [ ]  [10 hours]  Add to dotnet autocompletion for the `sign` command. 
- [ ]  [5 hours]  Add/update dotnet documentation for the `sign` command`

Estimate:  55 hours
