### ISSUE TITLE
Assembly versions set by the CI should not overwrite the patch version

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1009]
The 3.0.0 assemblies have a version number of 3.0.60624.657.  This makes it impossible to pass along a patch number. Ex: 3.0.1 

The CI should instead only replace and increment the 4th digit of the assembly version.

**Comment by yishaigalatzer** [comment]
@MeniZalzman was this fixed?

**Comment by MeniZalzman** [comment]
the build/revision version component is now the only thing that change in local build or CI build
