### ISSUE TITLE
PM UI:  verify IVsPackageManagerProvider implementation still works in VS OE environment

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10095]
This is an exploratory task to determine what issues, if any, exist with NuGet's [alternative package manager provider support](https://github.com/NuGet/Home/issues/1444) in a VS OE environment.  `IVsPackageManagerProvider` implementations may not just work in a VS OE environment, as some assumptions may now be invalid.

The only existing `IVsPackageManagerProvider` implementation I'm aware of is for web projects, but it's unclear if it applies to .NET Core (web) projects.

**Comment by nkolev92** [comment]
Is it maye related to this https://github.com/NuGet/Home/issues/6623?

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
