### ISSUE TITLE
Package Manager UI in Visual Studio provides incorrect Report Abuse URL for private feed

### ISSUE THREAD

**Issue by mitchdenny** [NuGet/Home#10103]
Please read the following information before posting the issue.

## Details about Problem

This problem is related to the VS Package Management UI. When viewing the details of a package, the UI provides a fallback Report Abuse URL when the feeds service index doesn't contain a report abuse template URI. If the service index does not contain a URI then it should not fallback to using the NuGet URI since this will be incorrect for packages that are not public.

## Detailed repro steps so we can see the same problem

1. Create a feed in Azure Artifacts (this feed doesn't return a report abuse template URI).

2. Point VS at that feed.

3. Observe that packages in that feed have the incorrect report abuse URI.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6560.
