### ISSUE TITLE
The Path is Not of a Legal Form

### ISSUE THREAD

**Issue by kevswims** [NuGet/Home#1010]
When trying to install Castle.Windsor.3.3.0 or Prism.Unity into a .Net 4.5.2 WPF project it returns with the error: 'The Path is Not of a Legal Form'. This is on a clean install of Windows 8.1 in Visual Studio Community 2015. The Unity failure is on the Unity 3.5.1404 package.

**Comment by ChrisRollason** [comment]
I have been getting the same issue with TweetSharp in a Visual Studio 2015 Community edition Asp.net web application (under Windows 8.1).

**Comment by kevswims** [comment]
I was able to reproduce this with TweetSharp as well.

**Comment by alvipeo** [comment]
I've got the same trying to Install-Package Unity :(

**Comment by ricardopieper** [comment]
I'm having the same problem installing LanguageExt. 
It fails when it tries to install the package System.Collections.Immutable. 

I created a copy of my solution folder and opened it, and opted to NOT add it to the source control.

The package then installed just fine.

**Comment by wmgries** [comment]
This also happens on Visual Studio 2015 Enterprise. We have tried with several different NuGet packages. Seems to be a bug with NuGet/Visual Studio 2015 compatibility.

**Comment by keesschollaart81** [comment]
I Also got this problem (W8.1, VS2015RTM) with NuGet package RestSharp. For me it was solved after updating to NuGet 3.1.60724.766

**Comment by yishaigalatzer** [comment]
Thanks all for reporting it. Could you please update NuGet to the latest in the gallery like @keesschollaart81 did.

If you still see the issue please let us know. We will plan to quickly turn around a fix if it is a thing. 
We plan to verify ourselves as well, the above is just to verify that we don't have something we don't reproduce on our side.

**Comment by kevswims** [comment]
Updating Nuget appears to 3.1 appears to have fixed the issue.

**Comment by alvipeo** [comment]
Same here. The upgraded did it.

**Comment by emgarten** [comment]
@zhili1208 will you verify this is fixed?

**Comment by zhili1208** [comment]
verified nuget 3.1 with vs Enterprise and vs community on windows 10, windows 8.1. Can't repro this issue.

**Comment by kubarom** [comment]
Upgrade to 3.1.1 from here https://github.com/nuget/home/releases worked for me
