### ISSUE TITLE
Pack should validate the case of files referenced by the .nuspec because NuGet.org validation is case sensitive

### ISSUE THREAD

**Issue by mbranscomb** [NuGet/Home#10102]
#### Background
For approx 3 months we had been building a NuGet package daily, hosting on an internal NuGet repository and using within Visual Studio. On the day we planned to release our NuGet packages on NuGet.org, they failed validation due to a missing file, when the file was technically present but the file name case did not match the nuspec. This caused us to scramble to rename the file, replace in multiple NuGet packages and re-sign each package in order to keep on track with our release schedule.

The Pack operation should have failed due to the case issue. 

#### Details
- Actual file name/case inside the NuGet package: `\legal\eula.txt`
- File name/case in the Nuspec reference: `<license type="file">legal/EULA.txt</license>`
- Note NuGet pack did not report any issues in our internal build pipeline
- The package appeared to work OK in Visual Studio when using our internal NuGet server. Or so we thought...
- The package failed NuGet.org validation with the error `The license file 'legal/EULA.txt' does not exist in the package.`

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): NuGet.exe

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): 

Worked before? If so, with which NuGet version:

N/A

## Detailed repro steps so we can see the same problem

1. Take an existing NuGet package
2. Replace a file within the package with a lowercase named version of the same file
3. Attempt to upload to NuGet.org

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Hey @mbranscomb 

This is a dup of https://github.com/NuGet/Home/issues/9817.

**Comment by mbranscomb** [comment]
@nkolev92 Thanks - I've added my 👍 to the other issue.
