### ISSUE TITLE
The task factory "***" could not be found in the assembly "***"

### ISSUE THREAD

**Issue by Denis535** [NuGet/Home#10109]
I am trying to make nuget package with some task. But I ran into a problem:
`The task factory "NuGetLibrary.Tasks.MyTask" could not be found in the assembly "C:\Users\Den\.nuget\packages\nugetlibrary\2.0.0-alpha.637374840513886857\build\netstandard2.1\..\..\lib\netstandard2.1\NuGetLibrary.dll"`.

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.8.0 Preview 3.2
```

NuGetLibrary.nuspec
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>NuGetLibrary</id>
        <version>2.0.0-alpha.$timestamp$</version>
        
        <owners>Den</owners>
        <authors>Den</authors>
        <title>NuGet Library</title>
        <icon>Icon.png</icon>
        <description>Example package</description>
        <tags></tags>
        <projectUrl>https://github.com/</projectUrl>
        <repository type="git" url="https://github.com/" />
        
        <developmentDependency>true</developmentDependency>
        <packageTypes>
            <packageType name="Dependency" />
        </packageTypes>

        <!--<frameworkReferences>
            <group targetFramework=".NETStandard">
            </group>
        </frameworkReferences>-->
        
        <!--<frameworkAssemblies>
        </frameworkAssemblies>-->
        
        <!--<dependencies>
            <group targetFramework=".NETStandard" >
                <dependency id="Microsoft.Build.Utilities.Core" version="16.6.0" />
            </group>
        </dependencies>-->
        
        <!--<references>
            <group targetframework=".netstandard" >
            </group>
        </references>-->
        
        <contentFiles>
            <files include="**/*.*" buildAction="None" copyToOutput="false" flatten="false" />
        </contentFiles>
    </metadata>
    <files>
        <file src="Readme.txt" target="" />
        <file src="Icon.png" target="" />
        <file src="Build/NuGetLibrary.targets" target="build/netstandard2.1/" />
        <file src="bin/$configuration$/netstandard2.1/NuGetLibrary.dll" target="lib/netstandard2.1/" />
        <file src="bin/$configuration$/netstandard2.1/NuGetLibrary.pdb" target="lib/netstandard2.1/" />
        <file src="bin/$configuration$/netstandard2.1/NuGetLibrary.deps.json" target="lib/netstandard2.1/" />
        <file src="Content/Images/Image.jpg" target="contentFiles/any/netstandard2.1/Images/" />
    </files>
</package>
```

NuGetLibrary.targets
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <UsingTask TaskName="MyTask" AssemblyFile = "$(MSBuildThisFileDirectory)..\..\lib\netstandard2.1\NuGetLibrary.dll" TaskFactory="NuGetLibrary.Tasks.MyTask" />
    <Target Name="BeforeBuild_" BeforeTargets="BeforeBuild">
        <Message Text="Hello World !!!" Importance="high" />
        <MyTask />
    </Target>
    <Target Name="AfterBuild_" AfterTargets="AfterBuild">
        <Message Text="Hello World !!!" Importance="high" />
        <MyTask />
    </Target>
</Project>
```

MyTask.cs
```
namespace NuGetLibrary.Tasks {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.Build.Framework;
    using Microsoft.Build.Utilities;

    public class MyTask : Task {

        public override bool Execute() {
            Log.LogWarning( "MyTask !!!" );
            return true;
        }

    }
}
```
And the project itself.
[NuGetLibrary.zip](https://github.com/NuGet/Home/files/5326326/NuGetLibrary.zip)

What am I doing wrong?

**Comment by zivkan** [comment]
It appears this is a MSBuild question, rather than NuGet. Were you able to get the task working with the same `UsingTask` definition, when not doing it as part of the package?

Given the error message says

> The task factory "NuGetLibrary.Tasks.MyTask" could not be found in the assembly

and you used `TaskFactory="NuGetLibrary.Tasks.MyTask"` in your targets file. The [docs for `UsingTask`](https://docs.microsoft.com/en-us/visualstudio/msbuild/usingtask-element-msbuild?view=vs-2019) say

> TaskFactory
> Optional attribute.
> Specifies the class in the assembly that is responsible for generating instances of the specified Task name. The user may also specify a Task as a child element that the task factory receives and uses to generate the task. The contents of the Task are specific to the task factory.

Given that your `MyTask` is a `Task`, and not some kind of factory, I'd guess that you can remove the `TaskFactory` attribute from your targets file, and let MSBuild create instances of your task itself.

It doesn't help me understand task factories any better, but there's also this docs page on [task factories](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-configure-targets-and-tasks?view=vs-2019#task-factories).


On another note, by having your assembly under `lib/` this usually means that this dll will become a compile time reference to the project using your package. It's unlikely that you want your package consumers to call your MSBuild task, so I suggest moving the dll to the `build/` folder, next to your targets file.

**Comment by Denis535** [comment]
I should use 
`<UsingTask AssemblyFile = "..." TaskName="NuGetLibrary.Tasks.MyTask" />` 
instead of 
`<UsingTask AssemblyFile = "..." TaskFactory="NuGetLibrary.Tasks.MyTask" TaskName="MyTask" />`.

What is `TaskFactory`? I thought this is just task class name.

**Comment by Denis535** [comment]
@zivkan 
I didn't notice your answer)))
Yes, problem was in `TaskFactory`. This must be class with interface `ITaskFactory` or `ITaskFactory2`.

> I suggest moving the dll to the build/ folder, next to your targets file.

I think tasks assembly must be placed in "tools" folder.

**Comment by zivkan** [comment]
> I think tasks assembly must be placed in "tools" folder.

There's no requirement where task assemblies are placed, you can use `<UsingTask`'s `AssemblyFile` to point anywhere. I'm just suggesting don't use any of NuGet's "by convention" locations (`lib/`, `ref/`, `runtimes/`, `content/`, `contentFiles/`) that use dll files, to ensure that NuGet never accidentally uses the dll in a way you didn't intend.
