### ISSUE TITLE
Relative links are broken in NuGet.Client debugging guide

### ISSUE THREAD

**Issue by bjorkstromm** [NuGet/Home#10100]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): -

NuGet version (x.x.x.xxx): -

dotnet.exe --version (if appropriate): -

VS version (if appropriate): -

OS version (i.e. win10 v1607 (14393.321)): -

Worked before? If so, with which NuGet version: -

## Detailed repro steps so we can see the same problem

1. Click any link that points to source code in GitHub Web UI
2. Notice that links are broken

## Other suggested things
Ther was also a typo, where RestoreTask was used event though PackTask was meant. I've submitted a PR here: https://github.com/NuGet/NuGet.Client/pull/3696

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment]
@mholo65 thank you for your contribution!
