### ISSUE TITLE
Package signing cross verify spec

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#10110]
Needs to write a spec for Package signing cross verify tests.

**Comment by aortiz-msft** [comment]
@heng-liu - Is there work left for this issue?

**Comment by heng-liu** [comment]
For the spec, I don't think so. But I haven't got any approval on the spec yet.

**Comment by heng-liu** [comment]
Test for bots removing WaitingForClientTeam label.

**Comment by heng-liu** [comment]
Finished testing and remove "waiting for" label.
