### ISSUE TITLE
Making Restore for Older TFMs with TargetPlatformStrings

### ISSUE THREAD

**Issue by Anipik** [NuGet/Home#10113]
Nuget Restore started supporting net5.0-* TargetFrameworks, but it treat all the other older targetframeworks as  if there were without targetPlatform. 
eg restore works perfectly for this project
```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net5.0-Windows</TargetFrameworks>
  </PropertyGroup>
</Project>
```
but the restore on the following project 
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;netcoreapp3.1-Windows</TargetFrameworks> -->
  </PropertyGroup>  
</Project>
```
results in 
```
NuGet.targets(130,5): error : Invalid restore input. Duplicate frameworks found: 'netcoreapp3.1, netcoreapp3.1'
```

##usage

We have using targetPlatforms in the runtime repo for a while now. This will help us in using the latest sdk and nuget feaures.
Currently the restore does not work in the VS for projects, it will help us rectify that as well.

cc @ericstj @ViktorHofer @safern

**Comment by safern** [comment]
I believe this might be because previous to `.net5.0` tfms couldn't have a TargetPlatform. And the TargetPlatform tfms we have in dotnet/runtime are supported via our config system.

**Comment by ViktorHofer** [comment]
@nkolev92 @zivkan what's the reason for NuGet to not support `TargetPlatformMoniker` pre net5.0? It sounds to me that even if we set them manually, they aren't respected.

**Comment by zivkan** [comment]
A TFM represents what APIs are available to the code being compiled. Before .NET 5, there was no concept of platform specific APIs, hence NuGet doesn't consider it a pivot point. For more information: https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md

Ultimately what you appear to be asking for is what we call TargetFramework aliases, which @ViktorHofer has already been part of the conversation for: https://github.com/NuGet/Home/issues/5154

**Comment by ericstj** [comment]
Would it be possible for NuGet to permit platforms on older TFMs?  Perhaps a flag we could turn on?  Like lift that calculation into the targets and let it be passed in as a parameter.
https://github.com/NuGet/NuGet.Client/blob/5a70626fbcf6d38f0c6c6fc3c96950959ccb70be/src/NuGet.Core/NuGet.Frameworks/NuGetFrameworkFactory.cs#L139-L140

**Comment by nkolev92** [comment]
@zkat added it to the weekly meeting agenda with MSBuild, SDK & partners. 
We're supposed to discuss this today (10/26/20)

**Comment by zkat** [comment]
Closing per https://github.com/NuGet/Home/issues/10113#issuecomment-704603125
