### ISSUE TITLE
(MSBuild) Restore does not respect BaseIntermediateOutputPath

### ISSUE THREAD

**Issue by ite-jankl** [NuGet/Home#10119]
When a csproj has the `BaseIntermediateOutputPath` property set (so that instead of `obj` a different folder will be used) the restore target will produce temporary files in `obj` instead of the declared `BaseIntermediateOutputPath`.

This is not a problem for projects using `packages.config`. But it is for those using the `PackageReference` format.

## Details about Problem

NuGet product used: **MSBuild**

NuGet Version: 5.6.0.6591

VS version: 16.7.5

OS version: win10 v2004

## Detailed repro steps so we can see the same problem

1. Clone and check out https://github.com/ite-klass/TestNugetRestoreBaseIntermediatePath
2. Execute `msbuild -t:restore TestNugetRestoreBaseIntermediatePath.sln`

The result is a dirty workspace. VS will also show the obj folder and files.

**Comment by kartheekp-ms** [comment]
I can reproduce this issue. Similar [issue](https://github.com/dotnet/msbuild/issues/1603) reported in `MSBuild` repo. The work-around suggested in the linked issue worked for me. Please try the work around and let us know if you are still experiencing the same behavior.

**Comment by ite-jankl** [comment]
Using a `Directory.Build.props` file to set `BaseIntermediateOutputPath` indeed seems to work. NuGet no longer uses the obj folder but the one defined there for those files.

In my actual project defining `BaseIntermediateOutputPath` and `OutputPath` in `Directory.Build.props` leads to new errors though.

* `Microsoft.NuGet.targets(186,5): error : Your project does not reference ".NETFramework,Version=v4.7.2" framework. Add a reference to ".NETFramework,Version=v4.7.2" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.`
* Unresolvable types
* Metafile dll not found

These errors do not occur when not defining them in a `Directory.Build.props` but in an imported project file.

I tried to resolve it but have to drop it for a while now.

**Comment by kartheekp-ms** [comment]
@ite-klass - Thanks for the udpate. Good to know that `Directory.Build.props` work-around is working.

> In my actual project defining BaseIntermediateOutputPath and OutputPath in Directory.Build.props leads to new errors though.

Can you please upload a sample project for us to repro this issue?

**Comment by ite-jankl** [comment]
I was not able to reproduce it in the small sample project yet. _(Even after making it more similar to the other project (non-sdk project, package references to EF and FxCop analyzers).)_

**Comment by nkolev92** [comment]
Please note that NuGet looks at MSBuildProjectExtensionsPath, not BaseIntermediateOutputPath path. The latter was a bug fixed in https://github.com/NuGet/NuGet.Client/pull/2131, about ~ 2 years ago in 4.7. 

MSBuildProjectExtensionsPath | Output folder, defaulting to BaseIntermediateOutputPath and the obj folder.
-- | --

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties

**Comment by nkolev92** [comment]
Given the above, I'm not sure there's a bug here, `MSBuildProjectExtensionsPath` is what should be used and it should be set *before* the SDK props import.

**Comment by ite-jankl** [comment]
> `MSBuildProjectExtensionsPath` is what should be used and it should be set _before_ the SDK props import.

Should as in the existing logic should already make sure of this?

Or is this not automatically the case? What does this mean for a `<Project Sdk="Microsoft.NET.Sdk">` project? Nothing can be imported before the Sdk attribute handling in the csproj file so it has to be done with a `Directory.Build.props` file which is handled before that (/early enough)?

**Comment by nkolev92** [comment]
Unfortunately the *way* things are declared is a consequences of MSBuild & the SDK. Directory.Build.Props was added  

For example if you do:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <MSBuildProjectExtensionsPath>stuff</MSBuildProjectExtensionsPath>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

</Project>
```
and run dotnet build, you'd get instructions on how to achieve your wanted scenario:

> C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Microsoft.Common.CurrentVersion.targets(803,5): error MSB3540: The value of the property "MSBuildProjectExtensionsPath" was modified after it was used by MSBuild which can lead to unexpected build results.  To set this property, you must do so before Microsoft.Common.props is imported, for example by using Directory.Build.props.  For more information, please visit https://go.microsoft.com/fwlink/?linkid=869650

You can do one of 2 things that come to mind. 
Deconstruct the SDK props/targets imports like https://github.com/NuGet/NuGet.Client/blob/2fdab5155cb0f869556f9901f3ad7122b17daa28/src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.csproj#L8. Given a new project, do something like: 

In particular, you can deconstruct a project such as:

```xml
<Project>
  <PropertyGroup>
    <MSBuildProjectExtensionsPath>stuff</MSBuildProjectExtensionsPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
```

or use Directory.Build.Props. 

Hope this helps.

**Comment by ite-jankl** [comment]
I understand and was able to work around the original issue now. Although my project is not buildable with the workaround I can work without the workaround for now (and ignore the produced obj folders). (I will try to fix that some time in the future, and also try to convert them to sdk projects.)

So the original issue reported here is resolved. From my side this ticket can be closed as such.

**Comment by nkolev92** [comment]
Thanks for following up.
