### ISSUE TITLE
Make PM UI's icon display resilient to errors

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10116]
It appears we have had multiple bugs in the past related to icons in PM UI which caused VS to crash: https://github.com/NuGet/Home/issues/9696, https://github.com/NuGet/Home/issues/10037

PM UI should never crash VS. If there's any kind of problem with displaying an icon, NuGet should display the default icon.

I'm not sure about the first issue, but the second issue is caused because WPF's implementation of resizing and changing the color pallet of images happens on the Dispatcher (UI) thread, and doesn't catch exceptions. Unhandled exceptions on the UI thread crashes the process. Since this is work that WPF is scheduling on the UI thread, NuGet's not on the call stack, and hence we cannot catch/handle the exception. The Dispatcher.UnhandledException handler does get triggered, but I don't see any way to determine if it was NuGet, or something else, that triggered the image load, and even if we assume it was NuGet, I'm not sure how to determine which image load had the problem when we load multiple images in parallel.

Even if dotnet/wpf fixes the issue, that will take effect in .NET 6 at the earliest, but VS 2019 runs in .NET Framework 4.7.2 (or 4.8 if that's installed, I guess). The bar to service the .NET Framework is very, very high, so I have no idea if this issue would be approved. Even if it is, customers who haven't installed the patch would continue to crash. We have to decide what machine install states we want to support.

We should investigating re-designing our icon loading code so that crashing VS just cannot happen, even for bugs we don't currently know about. Think `catch (Exception e)`, rather than catching specific exceptions, which is normally the recommendation. This won't work for this WPF exception on dispatcher thread issue, so we need to do something in addition to handle that scenario.

I have no idea if it will work, but maybe we can copy [WPF's code](https://github.com/dotnet/wpf/blob/b697746306a695af80a756586cad3f84a62e366c/src/Microsoft.DotNet.Wpf/src/PresentationCore/System/Windows/Media/Imaging/BitmapImage.cs#L303), and add more try-catch blocks.

If we can find a fix to the dispatcher thread exception issue, then we should remove the "ignore color pallet" workaround.

**Comment by rrelyea** [comment]
Added in 5.9/16.9 a few changes as part of the async image loading..

1) handle many exception types during Decoding... (just realized the method name was bad..)
PackageItemListViewModel.cs::584
        private static bool IsHandleableBitmapEncodingException(Exception ex)
        {
            return ex is ArgumentException ||
                ex is COMException ||
                ex is FileFormatException ||
                ex is InvalidOperationException ||
                ex is NotSupportedException ||
                ex is OutOfMemoryException ||
                ex is IOException ||
                ex is UnauthorizedAccessException;
        }

also, do the decoding off the UI thread... with a postonfailure:
PackageItemListViewModel.cs::436
                        if (BitmapStatus == IconBitmapStatus.NeedToFetch)
                        {
                            BitmapStatus = IconBitmapStatus.Fetching;
                            NuGetUIThreadHelper.JoinableTaskFactory
                                .RunAsync(FetchThenSetIconBitmapAsync)
                                .PostOnFailure(nameof(PackageItemListViewModel), nameof(IconBitmap));
                        }

So, closing via this PR https://github.com/NuGet/NuGet.Client/pull/3702 (covered by this issue: https://github.com/NuGet/Home/issues/10009)

also, in 16.8 a change was added to the converter...and i've now kept it in the viewmodel refactoring:
            // Workaround for https://github.com/dotnet/wpf/issues/3503
            iconBitmapImage.CreateOptions = BitmapCreateOptions.IgnoreColorProfile;

don't think we have anything left to do here.
