### ISSUE TITLE
Address mutations in cacheContext

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10121]
Maybe it's not urgent now, but  just in case I creating this issue:
Currently we have many `cacheContext`s which used for caching some previous values and calculations.
But they're using mutable normal dictionary which makes very hard for adding parallelization into our code as I experienced in [PR#3605](https://github.com/NuGet/NuGet.Client/pull/3605) and [PR#3646](https://github.com/NuGet/NuGet.Client/pull/3646).
Solution would be change them to `concurrent` type dictionaries or add sync lock. But caveat is `concurrent` types are slower than normal ones because it checks for sync locks. So one hand we're making things little bit faster due to parallelization but other hand making some things slower for other uses, there're 2 sides of coin, hard to evaluate right away.
We can't make it immutable types because most cache are intended for mutation. 
Another issue is almost all `cacheContext`s are part of public API. Not sure how to handle it without breaking. One possible solution is create new ones and deprecate old ones.

**Comment by nkolev92** [comment]
I think this is a very valid concern, it's unfortunate that our public API affects our performance considerations. 
However, given that this is mentioning a `potential` problem where inaction leads to no problems, I'm not sure I see much value in keeping this open.
 
What do you think?
