### ISSUE TITLE
Package Manager Console may take 5 - 15 minutes to initialize.

### ISSUE THREAD

**Issue by konste** [NuGet/Home#1012]
When I try to open Package Manager Console in VS (2013 or 2015) it may take up to 15 minutes for the console prompt to show up. This is not acceptable. What is it doing there for so long and how this delay may be reduced to usable state?

Konstantin

**Comment by emgarten** [comment]
What version of NuGet are you using with Visual Studio 2013? Did you start seeing this after a recent upgrade?

**Comment by konste** [comment]
In VS 2013 I have NuGet 2.8.60610.756

**Comment by emgarten** [comment]
There are no known issues around the load time, but an update will be out later today to resolve this issue: https://github.com/NuGet/Home/issues/974
Since you seeing this on both VS 2013 and 2015 it is likely related to the above bug.

**Comment by yishaigalatzer** [comment]
Can you provide us with more details? This doesn't happen on any machine we have or tested on.

One think I can think of, is that you have packages with an init script that is innefficient

**Comment by konste** [comment]
What kind of details shall I provide? As far as I understand Package Manager Console initialization does not execute any specific package script, it only executes %UserProfile%\Documents\WindowsPowerShell\NuGet_profile.ps1
and in my case it is not present. 
I also tried to use Fiddler to see if may be some network communication is going on, but again it is not the case. So I'm puzzled how to debug it further.

**Comment by yishaigalatzer** [comment]
It actually runs the init.ps1 scripts in the open solution.

Other than that information about the operating system, version of visual studio, etc will be a useful starting point.

@feiling do you have any other suggestions?

**Comment by konste** [comment]
-- It actually runs the init.ps1 scripts in the open solution.

Aha! That helps! I can see three of those:
packages\Costura.Fody.1.3.3.0\Tools\init.ps1 
packages\EntityFramework.6.1.0\tools\init.ps1 
packages\T4Scaffolding.Core.1.0.0\tools\init.ps1 

Will be looking which of them may be a culprit. 
Thank you!

**Comment by yishaigalatzer** [comment]
@konste I'm assuming this is fixed. If not please let us know
