### ISSUE TITLE
The 'Package' Build tab specifies an icon using a property that was deprecated by NuGet

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10120]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/793034/the-package-build-tab-specifies-an-icon-using-a-pr.html)._

---
When building a C# library, in project properties -> Package tab, we specify all the properties for the package. Here we can specify an icon for the package. The only way to specify the icon in this tab is by filling the 'Icon URL' text box. This generates a NuGet package with the 'iconUrl' tag, which was deprecated by NuGet and that gives a warning when uploading to NuGet.

---
#### Feedback Bot on 10/25/2019, 01:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/11/2019, 00:36 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by dominoFire** [comment]
Notes:

- Saw on 16.3
- Change in Properties page made in this PR: https://github.com/dotnet/project-system/pull/5485

**Comment by aortiz-msft** [comment]
@dominoFire should we move to project-system?

**Comment by dominoFire** [comment]
> @dominoFire should we move to project-system?

I think so. I created/transferred the issue to https://github.com/dotnet/project-system/issues/6686
