### ISSUE TITLE
`Unable to resolve dependencies` now shows full stack track in Error List & Output Window

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10128]
Updating the same set of packages in PMUI, I see a difference in behavior in the output window. Did we intentionally append the stack trace to the output window?
/cc @srdjanjovcic & @erdembayar who I believe may have worked in this space.

### VS 16.7.5
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.		
		
### VS 16.9.0 Preview 1
![image](https://user-images.githubusercontent.com/49205731/96209978-eb991800-0f3e-11eb-8b33-2e2d466cf71d.png)
![image](https://user-images.githubusercontent.com/49205731/96210002-f81d7080-0f3e-11eb-8ef8-528a7387e52b.png)

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		StreamJsonRpc.RemoteInvocationException: Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'. ---> System.InvalidOperationException: Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'. ---> NuGet.Resolver.NuGetResolverConstraintException: Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.
>    at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
>    at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__61.MoveNext()
>    --- End of inner exception stack trace ---
>    at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__61.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesAsync>d__56.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<GetUpdateActionsAsync>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Microsoft.ServiceHub.Framework.ServiceJsonRpcDescriptor.LocalProxyGeneration.<ReturnedValueTaskOfTHelper>d__25`1.MoveNext()
>    --- End of inner exception stack trace ---
>    at Microsoft.ServiceHub.Framework.ServiceJsonRpcDescriptor.LocalProxyGeneration.<ReturnedValueTaskOfTHelper>d__25`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.UI.UIActionEngine.<ResolveActionsForUpdateAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass11_0.<<PerformActionImplAsync>b__0>d.MoveNext()
> RPC server exception:
> System.InvalidOperationException: Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.
>  ---> NuGet.Resolver.NuGetResolverConstraintException: Unable to resolve dependencies. 'Cucumber.Messages 13.1.0' is not compatible with 'SpecFlow 3.4.14 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.
>       at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
>       at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__61.MoveNext()
>    --- End of inner exception stack trace ---
>       at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesForClassicAsync>d__61.MoveNext()
>    --- End of stack trace from previous location where exception was thrown ---
>       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>       at NuGet.PackageManagement.NuGetPackageManager.<PreviewUpdatePackagesAsync>d__56.MoveNext()
>    --- End of stack trace from previous location where exception was thrown ---
>       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>       at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>       at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<GetUpdateActionsAsync>d__19.MoveNext()
>    --- End of stack trace from previous location where exception was thrown ---
>       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>       at System.Threading.Tasks.ValueTask`1.get_Result()
>       at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>       at Microsoft.ServiceHub.Framework.ServiceJsonRpcDescriptor.LocalProxyGeneration.<ReturnedValueTaskOfTHelper>d__25`1.MoveNext()

## Repro Steps
1. Create an ASP.NET MVC Framework 4.7.2 app
1. Install SpecFlow (not latest version)
1. Clear NuGet Cache
1. Open PMUI Updates Tab
1. Select All packages
1. Select Update

**Comment by donnie-msft** [comment]
@dtivel any thoughts off-hand if this may be resolved by https://github.com/NuGet/NuGet.Client/pull/3711 ?

**Comment by dtivel** [comment]
@donnie-msft, yes, this issue is resolved by that fix.

**Comment by donnie-msft** [comment]
Closing as Fixed by https://github.com/NuGet/NuGet.Client/pull/3711
