### ISSUE TITLE
Improve multitargeted project support for managing NuGet packages

### ISSUE THREAD

**Issue by Redth** [NuGet/Home#10127]
As Xamarin joins .NET 6, one of the efforts we are focusing on is a single project experience which leans heavily on multitargeting support in SDK style projects.  One of the scenarios we have been looking at is the NuGet package management experience for these projects.  There is opportunity to improve the experience, especially with the visual package manager in the IDE's.

Today in the Xamarin ecosystem, there are many NuGet packages (including those maintained by Xamarin) in the ecosystem which only contain assets for a single, specific target framework (ie: Xamarin.AndroidX.AppCompat only contains assets for `monoandroid90`, others may contain only `xamarin.ios`, etc).

When a user tries to install a NuGet package into a multitargeted project which does not contain assets for every target framework the project is targeting, they are met with an error like this:

```
NU1202	Package Xamarin.AndroidX.AppCompat 1.2.0.4 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Xamarin.AndroidX.AppCompat 1.2.0.4 supports: monoandroid90 (MonoAndroid,Version=v9.0)	ClassLibrary1
```

Today, there are a number of workarounds, all of which I'm aware of require some manual intervention and abandoning the graphical package management experience.  One workaround is to use MSBuild conditions:

```xml
<ItemGroup Condition="$(TargetFramework)' == 'MonoAndroid10.0'">
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.2.0.2" />
</ItemGroup>
```

It's worth mentioning that non-Xamarin multitargeted projects would also benefit from improvements in this scenario.  How can the NuGet package management experience be improved to better support multitargeted projects going forward?

**Comment by jonathanpeppers** [comment]
One comment, is that in multi-targeted .NET 6 projects, pure MSBuild might look like:

```xml
<ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'android'">
    <PackageReference Include="SomeAndroidPackage" Version="1.0.0" />
</ItemGroup>
<ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'ios'">
    <PackageReference Include="SomeiOSPackage" Version="1.0.0" />
</ItemGroup>
```
This will likely cause problems in the IDE; I'll test this when we get there.

If the IDE was to add a dropdown or checkbox for the platform of each NuGet pacakge, it might be easier for some new item metadata to be created:

```xml
<ItemGroup>
    <PackageReference Include="SomeAndroidPackage" Version="1.0.0" TargetPlatform="android" />
    <PackageReference Include="SomeiOSPackage" Version="1.0.0" TargetPlatform="ios" />
</ItemGroup>
```

I don't work on the IDE, though; someone else might know better.

I don't know that we will have an intersection of a package that is iOS or Android, and not Windows. We might?

**Comment by nkolev92** [comment]
Hey @Redth and @jonathanpeppers 

Thanks for creating this issue. This is a dup of https://github.com/NuGet/Home/issues/4681.
