### ISSUE TITLE
[CPVM] Transitive dependency pinning 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#10133]
## Details about Problem

Determine if transitive pinning is a desired scenario for central package version management.

**Comment by cristinamanum** [comment]
Related with https://github.com/NuGet/Home/issues/10115

**Comment by zkat** [comment]
@rconard can you paste your summary on this and close this?

**Comment by rconard** [comment]
https://github.com/NuGet/Home/issues/10115

**Comment by joeltankam** [comment]
Hello, 

Could this be related to #10578 ?

Thanks
