### ISSUE TITLE
Need to "git merge" 3.0-rtm branch into dev branch. Certain commits are missing from the dev branch

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1014]
Need to "git merge" 3.0-rtm branch into dev branch. Certain commits are missing from the dev branch

**Comment by deepakaravindr** [comment]
Assigning to @emgarten who has already cherry-picked those commits. This issue should be fixed

**Comment by emgarten** [comment]
These have been added to the dev branch. They will be in 3.1.2.
