### ISSUE TITLE
Package Manager Output window steals focus from build output

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#10143]
From: https://devdiv.visualstudio.com/DevDiv/_queries/edit/1216649

1. Create new codespace
2. Target https://github.com/dotnet-architecture/eShopOnWeb
2.5 -- open the solution
3. F5 Run app to see things run for the first time
4. Wait 

Result
Build starts
long period of nothing showing up in output window and then package manager window switches the output page from build to package manager

Expected
Output window should stay on the build page throughout a build or an F5

This may seem trivial and even may be current local behavior but this impacts the onboarding experience for net new users watching to see if the basic experience is working end to end. 

We observed all users in onboarding go straight to build an F5 as their first step to see if things were working. Focusing on making sure new customers in GitHub Codespaces get a clean end to end expereince for these customers.

**Comment by dtivel** [comment]
@rrelyea, @sbanni confirmed that this did not repro locally, only with a remote server.  Also, it only reproed once for @sbanni.

@rrelyea, can you please follow up with the CodeSpaces folks to understand:

1. Why would an issue like this would repro remotely and not locally?  (This assumes NuGet code paths are the same for local and remote, but it might be worth verifying this.) 
2.  How do we debug/diagnose an issue which only reproes with a remote server?
3.  Are we really blocked on a new platform API?  Is there something simple we can do like disable Package Manager Output window pane activation in a CodeSpaces-connected client?

CC @sbanni, @aortiz-msft, @chgill-MSFT

**Comment by aortiz-msft** [comment]
Closing per new guidance.
