### ISSUE TITLE
[Nexus] Packages.Config projects don't work in Codespaces yet (C++ and more) - investigate

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#10144]
From: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1192931

From C++ team: Currently and for 16.9 both CMake and vcxproj for console/library applications are supported in Windows Codespaces

**Comment by rrelyea** [comment]
per workaround in associated bug, this is not 16.9 blocker at the moment.

**Comment by donnie-msft** [comment]
Closing CodeSpaces issues.
