### ISSUE TITLE
VS OE:  near-duplicate Error List entries

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10140]
In VS OE scenarios only, near-duplicate Error List entries may display with only file paths differing.  This is not a regression from https://github.com/NuGet/NuGet.Client/commit/1f51ec51421a255c7fb83f362ee23839c0a5f631.

In general (VS OE and non-VS OE) and for a single [`ITableDataSink`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.tablemanager.itabledatasink?view=visualstudiosdk-2019)), when the Error List already contains entries when new entries are added, the Error List overwrites an existing entry with a newer entry if their [`ITableEntry.Identity`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.tablemanager.itableentry.identity?view=visualstudiosdk-2019#remarks) values are equal.  Because [NuGet uses the message text for `ITableEntry.Identity`](https://github.com/NuGet/NuGet.Client/blob/1f51ec51421a255c7fb83f362ee23839c0a5f631/src/NuGet.Clients/NuGet.VisualStudio.Common/ErrorListTableEntry.cs#L21) and because these two entries have the same message, the first NU1101 entry is overwritten with the second NU1101 entry, and the entries are effectively deduplicated.

With the provided repro steps in a standalone (non-VS OE) environment, this deduplication occurs because both entries come from the same `ITableDataSink`.  However, in a VS OE environment, this deduplication does not occur because one entry is written by the service to the Error List and some background LiveShare magic propagates the entry to the Error List but with a it's own client-side `ITableEntrySink`.  The other entry is written by the client to the Error List with the NuGet `ITableEntrySink`. 
 Thus, the "duplicate" entries are not deduplicated.

Repro steps:

1.  Open a .NET Core project in a VS OE environment.
2.  In PM UI attempt to install a package that has a missing dependency.

Expected result:  

Actual result:

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | Package restore failed. Rolling back package   changes for 'NetCore'.
Error | NU1101 | Unable to find package IsMissingDependency. No   packages exist with this id in source(s): Test Packages | NetCore | C:\Users\dtivel\AppData\Local\Temp\4166FF91F1B149FE766E214BA1521E2B4224\2\~~\E$\Trash\VerifyFix\NetCore\NetCore.csproj | 1 |  
Error | NU1101 | Unable   to find package IsMissingDependency. No packages exist with this id in   source(s): Test Packages | NetCore | E:\Trash\VerifyFix\NetCore\NetCore.csproj | 1 |

**Comment by dtivel** [comment]
Possibly addressed by https://github.com/NuGet/Home/issues/10088

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
