### ISSUE TITLE
Pushing multiple packages in CI is causing a file lock, failing 2nd push

### ISSUE THREAD

**Issue by timheuer** [NuGet/Home#10158]
## Details about Problem
When using CI (GitHub Actions and `dotnet nuget push` with *.nupkg, the files are found and a first package is pushed, but then the second fails.

Example: https://github.com/timheuer/strava-net/runs/1243834288#step:7:19

```
Pushing strava-net.1.0.0.symbols.nupkg to '/home/runner/work/strava-net/strava-net/published/'...
Your package was pushed.
Pushing strava-net.1.0.0.nupkg to '/home/runner/work/strava-net/strava-net/published/'...
error: The process cannot access the file '/home/runner/work/strava-net/strava-net/published/strava-net.1.0.0.nupkg' because it is being used by another process.
```

**Comment by donnie-msft** [comment]
@timheuer Thanks for reporting. Please fill out the Issue template here: https://github.com/NuGet/Home/issues/new
This helps in understanding your product versions and scenario.

**Comment by timheuer** [comment]
This looks like #4393 that I think we should bump up.  The dotnet stack here being used is .NET 3.1.402 SDK

**Comment by donnie-msft** [comment]
Closing as duplicate per comment: https://github.com/NuGet/Home/issues/4393
