### ISSUE TITLE
VS OE:  handle service version unavailable gracefully (and maybe try downgrading?)

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10167]
Use `ServiceBrokerExtensions.ReportMissingServiceAsync(...)` to report when a requested service version is unavailable.

This is important to do early so that in the future when service versions are removed, older clients with this feature can know that functionality is reduced.

**Comment by rrelyea** [comment]
@dtivel - we'd like to discuss how we should handle situations when we add something to an existing interface that hasn't shipped publicly like: https://github.com/nuget/client.engineering/issues/682 
Should we inform test team.
Should we add a call to ReportMissingServiceAsync as this bug discussed when a version is not available.
etc...

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
