### ISSUE TITLE
Avoid cache with local sources

### ISSUE THREAD

**Issue by juanan** [NuGet/Home#10160]
Hi,

We have nuget packages from 2 sources: nuget.org and local machine. I have noticed that the command "nuget restore '*.sln' Nocache" continues getting packages from my local source, is it a bug?Its like the parameter "NoCache" doesnt apply for local sources.

I have to run before "nuget locals all -clear" to make it work.

I am running Nuget 5.7.0.

Many thanks.

**Comment by donnie-msft** [comment]
> During restore, NuGet ignores the order of package sources, and uses the package from whichever source is first to respond to requests

See: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#package-restore-overview
