### ISSUE TITLE
Improve install new package performance for large solutions

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10166]
## Details about Problem

We made quite progress on performance improvement for [update/downgrade](https://github.com/NuGet/Home/issues/6010), [uninstall actions](https://github.com/NuGet/Home/issues/9956) for existing package in large solution.
But I see installing new package into OrchardCore (158 projects) taking almost [10 minutes](https://gist.github.com/erdembayar/acb49524d3378c9ba7ddf7638c2fdde2) which is quite long. Since `upgrade/downgrade` actions are already 30-40seconds range `install` action could be improved, because they share much code path. Currently didn't investigate where is the bottleneck for that long 10 min install duration.

OrchardCore (158 projects)
[10 min 17 sec](https://gist.github.com/erdembayar/acb49524d3378c9ba7ddf7638c2fdde2)
Mixed project (42 projects) 
[1 min 17 sec](https://gist.github.com/erdembayar/8b29d2479df64620bbb7ac4187ad0f11)

Since actual bug fix happened in CPS code there is Nuget.Client PR.
You can see 7x perf improvement for large solutions here: 
https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2021/04/installperf.mp4
https://devblogs.microsoft.com/visualstudio/performance-improvements-in-nuget/

**Comment by nkolev92** [comment]
@erdembayar Is this the first installation of that package? Did the download happen? 

Installing a package to 158 projects involves writing to 158 project systems and those project systems might be synchronizing together for whatever reason. 

I'm not denying that 10 mins is too long, but rather that I'm not sure it's specific enough right now.

**Comment by erdembayar** [comment]
@nkolev92  
I don't think download happen. Because it's same version I installed so many times, so it should be already cached on my local.
But 'upgrade/downgrade' technically does almost same thing, still under 1 min.  I believe it could be done similar time frame.

**Comment by nkolev92** [comment]
The upgrade/download scenarios call different project system APIs from the install scenarios.
One edits metadata, the other one adds an item. 

Are those measurements consistent?

**Comment by erdembayar** [comment]
@nkolev92 
Yes, it's consistently slow.

**Comment by mackcoding** [comment]
NuGet is the slowest part of my workday.  My solution is only 2-3 projects if that. Loading the NuGet interface is slow, searching for packages is slow, updating is slow, installing is slow, anything to do with NuGet is slow. It's always been like this. I'm about to lose my mind by constantly waiting for Nuget. 

I uploaded a video demonstrating what I mean: https://www.youtube.com/watch?v=VssoYZXteeU

I have 3 workstations:
Dell Workstation with an i9 CPU
My home workstation with an i7-6800k cpu
My work laptop with an i7 CPU

All systems have 64 GB of ram and run the latest version of Visual Studio & Windows. All of them are slow when it comes to nuget.

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
I found where is cause huge discrepancy between `install new package` vs `upgrade/downgrade` operations.
It's coming from below call.
https://github.com/NuGet/NuGet.Client/blob/222c188279e413f2b78bd3aa8b791dbc05016ddf/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L376-L379
I added timer around it.
```
                var stopWatch = Stopwatch.StartNew();

                // Install the package to all frameworks.
                var configuredProject = await _unconfiguredProject.GetSuggestedConfiguredProjectAsync();

                var result = await configuredProject
                    .Services
                    .PackageReferences
                    .AddAsync(packageId, formattedRange);

                nuGetProjectContext.Log(
                    MessageLevel.Info, "----Duration---------- " +  DatetimeUtility.ToReadableTimeFormat(stopWatch.Elapsed));
```

Upgrade/downgrade existing package operation [log](https://gist.github.com/erdembayar/c1833f14da05944fc4892f70e8cb8296).
` ----Duration---------- 1 ms`

Install new package operation [log](https://gist.github.com/erdembayar/8f93e4ab5960efe2c7066a9a3a45d3d3)

`----Duration---------- 204 ms`

Since this code path is outside Nuget, it's not actionable for us. 

Here is actual implementation which explain why it's slow, it's using write locks and create new reference overhead:
[CpsProject](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=%2Fsrc%2FMicrosoft.VisualStudio.ProjectSystem.Implementation%2FReferences%2FResolvableReferencesProviderBase.cs&version=GBmain&line=345&lineEnd=368&lineStartColumn=1&lineEndColumn=44&lineStyle=plain&_a=contents).

**Comment by nkolev92** [comment]
> Since this code path is outside Nuget, it's not actionable for us.

That's a great catch. We should make sure we talk to the project-system folks to understand if this is known and whether they have any immediate work scheduled here. 

Given that this performance is only noticeable in bulk update, an interesting consideration is a design for an updater service that was considered in the context of CPVM. 

@zivkan Can please provide the context you have from that work? I recall you did some work there. 
I think that service might allow us to be more performant.

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
I'll write brief email to them later today or tomorrow morning about this. Can I just tag them here instead? I can see who contributes to CPS.

**Comment by nkolev92** [comment]
@erdembayar 

Let's wait for Andy to provide some context about the work that he's familiar with first. 
CPS is closed source, and I can provide you some of the context about who the right folks to contact are offline.

**Comment by zivkan** [comment]
I had [design for a new "update package reference" service](https://github.com/NuGet/Home/pull/9182). The project-system team agreed to implement it. A pull request was created (in a closed source part of VS, so I don't want to tag people here, but I'm happy to invite those people to participate in this issue), but it was never completed for some reason. Having said that, when I proposed that NuGet used this new service for all project changes, some people claimed the risk was too high, and was pushing us (NuGet) to only use it for CPVM enabled projects. This perf issue is good justification to use it for all updates, if the service existed.

Anyway, the service was never completed. Let's start the discussion in Teams/email, and then move back here if all participants agree.

**Comment by erdembayar** [comment]
@nkolev92 
Please advise how to proceed? Ping me when you're free on teams.

**Comment by nkolev92** [comment]
I think we should start a discussion detailing this original scenario and then asking them to confirm whether they think this service would the solution to our problem, or whether there are some improvements that can done to AddAsync. 

Focus is that we need their help to determine the best action, if any.

**Comment by erdembayar** [comment]
I sent them email for asking a discussion and I created internal [workitem](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1281052) to keep tab on any future progress.

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 @zivkan 
I tested latest VS Internal preview with CPS team fix. Numbers looks great. 😃 
Now `install` action duration is on par with `upgrade/downgrade/uninstall` actions.
[0 min 38 sec](https://gist.github.com/erdembayar/cbb2d909887816252066961bcbeb2974) for OrchardCore solution with 159 projects.

Also call durations to CPS is down to 20ms range from 200ms range.
`----Duration---------- 21 ms
`

Please note there was no perf improvement old `package.config` type since it doesn't use CPS.

Now I believe time to conclude this perf improvement effort.  From runtime analysis we can't do better than this ( since we still have to evaluate them at least once ~ O(n)) unless change current design. 

Other possible ideas from CPS team were:
```
Can we not wait for msbuild evaluation?
Or can we allow batching so NuGet can batch multiple packages in one call?
```
