### ISSUE TITLE
netcoreapp5.0-windows does not round trip and does not parse platform information

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#10177]
## Details about Problem

NuGet product used: NuGet.Frameworks library
NuGet version: 5.8.0-preview.3.6823
Worked before? Yes, 5.7.0

## Detailed repro steps so we can see the same problem

1. Parse `netcoreapp5.0-windows`
2. Execute `ToString()` or get the short folder name.

### Expected

For 5.8.0-preview.3.6823, I would expect this to parse as "net5.0-windows" with a recognized platform.

### Actual

https://nugettoolsdev.azurewebsites.net/5.8.0-preview.3.6823/parse-framework?framework=netcoreapp5.0-windows

> The input value is **netcoreapp5.0-windows**.
> The short folder name is `net5.0`.
> The .NET framework name is `.NETCoreApp,Version=v5.0,Profile=windows`.
> The framework identifier is `.NETCoreApp`.
> The framework version is `5.0.0.0`.
> The result of `ToString()` is `net5.0`.
> 
> The framework profile is `windows`.
> 
> There is no framework platform.

A profile is parsed and the `ToString()` is `net5.0` indicating the `-windows` part is lost. In other words this does not round trip, a net5.0 framework can theoretically have a profile parsed (wrong. profiles are not a thing for .NET 5), and the platform is not properly detected (wrong).

### Significance

This doesn't seem like a huge, huge deal since `net5.0-windows` is the proper form and should be written as such by all tooling, but it may cause a problem for hand-crafted packages. I don't know the whole landscape but I figured client team should at least know it's a thing.

**Comment by zkat** [comment]
Note to self: this might be working by now, so just need to take a look with the latest and greatest.

**Comment by zkat** [comment]
update: This is, in fact, still broken. I've added some failing tests over at https://github.com/NuGet/NuGet.Client/pull/3756/commits/2dcd56e952a5b3e2991e178173267ff72d8c387b and will work on a fix.
