### ISSUE TITLE
nuget.config packageSources relative paths converted to absolute paths

### ISSUE THREAD

**Issue by tjrobinson** [NuGet/Home#1017]
In our nuget.config file we have a relative path specified for a package source:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="_Packages" />
  </config>
  <disabledPackageSources />
  <packageSources>
    <add key="Working copy" value="_Packages" />
  </packageSources>
</configuration>
```

Using Visual Studio 2015 RTM and "NuGet Package Manager for Visual Studio 2015" 3.0.60624.657 we have noticed that a solution rebuild, with package restore enabled, causes the relative path we had previously specified to be automatically changed in the nuget.config file to an absolute path. It also removes an empty <disabledPackageSources /> element that was there before. 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="_Packages" />
  </config>
  <packageSources>
    <add key="Working copy" value="C:\projects\OurProduct-dev\_Packages" />
  </packageSources>
</configuration>
```

Please see this codeplex work item for the background: https://nuget.codeplex.com/workitem/2810

**Comment by pavelsavara** [comment]
This now happens with VS2015 too as it has same version of NuGet.

**Comment by yishaigalatzer** [comment]
@zhili1208  please verify that the issue of changing the value _should_ have been fixed, because we don't re-save the files since NuGet 3.2. 

Then on top of that we should verify we don't rewrite the path when saving the settings.

**Comment by zhili1208** [comment]
verified issue of changing the value is fixed and we don't rewrite the path when saving the settings
