### ISSUE TITLE
ManagePackageVersionsCentrally default behavior is opposite the spec

### ISSUE THREAD

**Issue by jimmylewis** [NuGet/Home#10183]
## Details about Problem

After creating a Directory.Packages.props file, projects were not opted-in to ManagePackageVersionsCentrally by default.  The [spec](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions) currently reads:
>If a Directory.Packages.props file exists, all projects in that directory tree are automatically opted in to central package version management. 

Adding <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally> to the project file addresses the issue, so this is low-priority (there's a perfectly viable workaround).

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): 
VS/dotnet/msbuild

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):
5.0.100-rc.2.20479.15

VS version (if appropriate):
16.9 Preview 2

OS version (i.e. win10 v1607 (14393.321)):
Win10 20H2

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. dotnet new a project (or create in VS)
2. Add a PackageReference to anything
3. Create a Directory.Packages.props file, add a PackageVersion to it; remove the version from the PackageReference
4. Build/restore

### Expected:
Project should build using the PackageVersion specified in Directory.Packages.props (ManagePackageVersionsCentrally should default to true if Directory.Packages.props exists)

### Actual:
PackageVersion is not used, and PackageReference has no lower bound specified so it uses the oldest package available.

>d:\temp\nuget\nuget.csproj : warning NU1604: Project dependency newtonsoft.json does not contain an inclusive lower b
ound. Include a lower bound in the dependency version to ensure consistent restore results.
  d:\temp\nuget\nuget.csproj : warning NU1701: Package 'Newtonsoft.Json 3.5.8' was restored using '.NETFramework,Versio
n=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version
=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully co
mpatible with your project.

### Sample Project

[Example.zip](https://github.com/NuGet/Home/files/5431751/Example.zip)

**Comment by zivkan** [comment]
@jimmylewis the spec you linked to has a big banner at the top saying "status: reviewing". Additionally, it links to https://github.com/NuGet/Home/issues/6764 which has the Epic label, and the issue is still open.  That is to say, CPVM is a preview feature. That is how CPVM will work when we deem it ready for GA. For now, it's preview, and therefore require customers who are willing to test preview features to opt-in.

I updated the spec to clarify this.
