### ISSUE TITLE
Show transitive dependencies in PMUI for PackageReference projects

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#10184]
Design spec: https://github.com/NuGet/Home/blob/dev/proposed/2020/Transitive-Dependencies.md

This epic covers the PMUI portion of the transitive dependencies spec

**Comment by JonDouglas** [comment]
Related: https://github.com/NuGet/Home/pull/10179

**Comment by nkolev92** [comment]
Live for everyone in Visual Studio 17.6 and later.

**Comment by cremor** [comment]
@nkolev92 @drewgillies Are there any news about the following?

> Q: Can I see transitive dependencies on solution view or only project view?
> A: The scope today is project view first & seeing how complex including this in solution view would be in the engineering costing.

**Comment by nkolev92** [comment]
@cremor Right now, transitive dependencies are only available in the project level PM UI.

**Comment by cremor** [comment]
Yes, but are there any plans to expand this to solution level? Is there a Github issue I can follow?

**Comment by nkolev92** [comment]
No, but feel free to file one. It'll get triaged triaged as per: https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md.
