### ISSUE TITLE
GetDependencyInfoAsync throws NullReferenceException

### ISSUE THREAD

**Issue by punitganshani** [NuGet/Home#1018]
I am trying to get the dependency using following code

```
var repo = Repository.Factory.GetVisualStudio("http://api.nuget.org/v3/index.json");
var findpkgById = await repo.GetResourceAsync<RemoteV3FindPackageByIdResource>();
var depInfo = await findpkgById.GetDependencyInfoAsync("EntityFramework", NuGetVersion.Parse("6.1.3"), CancellationToken.None);

```

The above code throws `System.NullReferenceException`

The NuGet packages version used is 3.1.1

**Comment by emgarten** [comment]
Is findpkgById null? Where is the exception thrown from?

**Comment by punitganshani** [comment]
Yes `findpkgById` is null.  Sorry for not mentioning it earlier.

**Comment by yishaigalatzer** [comment]
@punitganshani note that none of this code is guaranteed to stay the same. These are not public APIs that you can depend on in any extension (without worrying about constantly updating it and making it match across NuGet versions).

Like I asked elsewhere, can you provide the scenario for this?

**Comment by yishaigalatzer** [comment]
@punitganshani looks like you are just not getting the resource. I don't think there is a bug here.
