### ISSUE TITLE
Should nuget DoubleWaitForExit?

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#10189]
So this issue https://github.com/dotnet/runtime/issues/27128 results in "Intermittent: Empty Process stdout" when using WaitForExit in combination with data received events. Looking through the nuget client codebase it would seem this is a likely occurrence. Also given nugets requirement to target msbuild classic (net472) it is unlikle to be (in the short term) resolved by a future fix in the framework. So with this in mind should should nuget be using the workaround proposed in that issue? ie

    static bool DoubleWaitForExit(this Process process)
    {
        var result = process.WaitForExit(500);
        if (result)
        {
            process.WaitForExit();
        }

        return result;
    }

**Comment by kartheekp-ms** [comment]
I agree, noticed a problem when `NuGet.CommandLine` tests were executed in parallel. Found the dotnet/runtime issue linked above extremely helpful. Created a [PR](https://github.com/NuGet/NuGet.Client/pull/3732) to add double wait in test code.

**Comment by rrelyea** [comment]
I've asked on the runtime issue if doing the workaround is recommended. We should consider waiting for official response. (if the impact for our customers and us is large, workarounds until real fixes come are ok most of the time)
