### ISSUE TITLE
Git tags for NuGet 3.0?

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#1019]
I'm struggling to access corresponding sources for the NuGet plugin distributed with VS2015.

Could someone please add GIT tags in relevant repos for NuGet version 3.0.60624.657 that is distributed with VS2015?

**Comment by emgarten** [comment]
NuGet3, NuGet.PackageManagement, and NuGet.VisualStudioExtension contain 3.0-rtm tags.

**Comment by forderud** [comment]
Sorry for being picky, but neither NuGet3 nor NuGet.PackageManagement contains any "3.0-rtm" TAGS.

They do, however, contain branches with the same name, but this is conceptually something else. Branches usually change over time, where as tags are immutable. It's therefore important to use TAGS when pointing to a specific version of the SW.

**Comment by emgarten** [comment]
Ah, you are right those repos are missing the tags. Use the 3.0-rtm branches. That is what matches the release.
