### ISSUE TITLE
[NuGet UI] Search dropdown does not show recent queries in NuGet Packages Manager window

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10200]
Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):  VS UI

NuGet version (x.x.x.xxx): 4.x, 5.x

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Open any solution in VS Int Preview 

2. Open in menu Tools -> NuGet Package Manager -> Manage Nuget Packages for Solution 

3. Input search query to Search field

4. Click on Refresh button/any package/empty space to hide Search dropdown by losing focus from Search 

5. Clear Search field

6. Open Search dropdown

Expected: last searched query appear first in dropdown

Actual: last searched query does not appear in dropdown

Note: query appears after selecting it in dropdown on search

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

[Azdo issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/620319)

**Comment by nkolev92** [comment]
fyi @donnie-msft

**Comment by donnie-msft** [comment]
No repro on Version 16.9.0 Preview 2.0 [30701.28.main]
![image](https://user-images.githubusercontent.com/49205731/97950839-2f28ba00-1d66-11eb-85c7-75a2825d3daa.png)

**Comment by donnie-msft** [comment]
Closing as I can't repro. @nkolev92  if you have a repro, please reopen

**Comment by nkolev92** [comment]
@donnie-msft Did you see the azure devops issue I linked?
I moved it from there, I have not attempted to repro it myself.

**Comment by donnie-msft** [comment]
@nkolev92 Yes I did, it has the exact same repro steps.

**Comment by nkolev92** [comment]
If you read the issue and it's comments, then I have no additional information that I can add.
