### ISSUE TITLE
NU1403: Package content hash validation failed for System.Diagnostics.Debug.4.3.0

### ISSUE THREAD

**Issue by jozefizso** [NuGet/Home#10224]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version: 5.7.0.6726

VS version (if appropriate): 2019 16.7.7

OS version (i.e. win10 v1607 (14393.321)): Windows 10 2004

Worked before? If so, with which NuGet version: Yes, 5.7.0.6726

## Detailed repro steps so we can see the same problem

1. We removed reference to Serilog.Sinks.Logentries package from out project
2. The **packages.lock.json** were regenerated
3. Out build is failing with **NU1403** error.

### Verbose Logs

```
Feeds used:
    https://api.nuget.org/v3/index.json
##[error]The nuget command failed with exit code(1) and error(NU1403: Package content hash validation failed for System.Diagnostics.Debug.4.3.0. The package is different than the last restore.
Package content hash validation failed for System.Runtime.InteropServices.RuntimeInformation.4.3.0. The package is different than the last restore.

NU1403: Package content hash validation failed for System.Diagnostics.Debug.4.3.0. The package is different than the last restore.
Package content hash validation failed for System.Runtime.InteropServices.RuntimeInformation.4.3.0. The package is different than the last restore.
```

### Sample Project

This is a private source code.

**Comment by zkat** [comment]
Note: This error code [really needs documentation](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1998).

We think that NuGet is attempting to use a package from your local fallback folder and the hash is different for the package from what's in the package.lock.json.

**Comment by riQQ** [comment]
See also #10029
