### ISSUE TITLE
VS SDK Improvements

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10221]
Epic tracking improvements to SDK and APIs for VS in general, or the PMUI specifically.
Both internal and external customers are in scope.

**Comment by nkolev92** [comment]
Just cleaning up epics. 
Still needed?

**Comment by donnie-msft** [comment]
> Just cleaning up epics.
> Still needed?

@nkolev92 - I was using this for organizational purposes. However, since ZenHub was deleted, right now the Epic to sub-Issue relationships aren't shown here. I'll have to figure out how to restore those in the new GH Projects, or perhaps just start from scratch assigning them to this Epic.

**Comment by nkolev92** [comment]
Up to you whether you keep this as a new epic or not. 
Do doc has some quick suggestions https://github.com/NuGet/Client.Engineering/blob/main/docs/NuGet.Client-GitHub-Project-How-To.md#how-do-we-use-epics. 

You can just specify the link to an issue and it'll autogenerate things. 

Example: 

```md
- https://github.com/NuGet/Home/issues/10222
- https://github.com/NuGet/Home/issues/10223
```

It'll be autorendered by GH with the name.

**Comment by donnie-msft** [comment]
I understand that's the new process, but this Epic was created under the previous process, so all the sub-Issues for this Epic are lost. In other words, the work is finding all of the relevant sub-issues and manually re-creating the list for the Epic.

**Comment by nkolev92** [comment]
Unlikely we'll get to this at this point. Cleaning up, reducing open issues.
