### ISSUE TITLE
dotnet pack does not include Compile Update Pack="true" when multi-targeting

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#10239]
## Details about Problem

NuGet product used: dotnet.exe
NuGet version (x.x.x.xxx): 5.8.0.6860
dotnet.exe --version: 5.0.100-rc.2.20479.15
OS version: Windows 10
Worked before? Not that I can tell, I tried 1.1.14, 2.1.811, 3.1.302, 3.1.403, 5.0.100-rc.2.20479.15

## Detailed repro steps so we can see the same problem

1. `dotnet new classlib`
1. Attempt to pack one of the source files (`<Compile>`) as a content file
1. Make the project mutli-target with `<TargetFrameworks>`
1. Run `dotnet pack`
1. Inspect the output .nupkg and see if there are `contentFiles`

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard1.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Class1.cs" Pack="true" />
  </ItemGroup>

</Project>
```

**Problem:** does not include the content files at all.

```
_rels/.rels
PackContent.nuspec
lib/netstandard1.0/PackContent.dll
lib/netstandard1.1/PackContent.dll
[Content_Types].xml
package/services/metadata/core-properties/a856c12125244f57bf30839499a16703.psmdcp
```

## Other suggested things

The following workarounds work:

### Don't multi-target

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Class1.cs" Pack="true" />
  </ItemGroup>

</Project>
```

**Problem:** does not multi-target which may be a requirement.

```
_rels/.rels
PackContent.nuspec
lib/netstandard1.0/PackContent.dll
content/Class1.cs
contentFiles/cs/netstandard1.0/Class1.cs
[Content_Types].xml
package/services/metadata/core-properties/4739f3f575954af387728acd57ff525a.psmdcp
```

### Add and remove the item

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard1.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Include="Class1.cs" Pack="true" />
  </ItemGroup>

</Project>
```

**Problem:** works perfectly, but a bit painful to both remove and add the item.

```
_rels/.rels
PackContent.nuspec
lib/netstandard1.0/PackContent.dll
lib/netstandard1.1/PackContent.dll
content/Class1.cs
contentFiles/cs/netstandard1.0/Class1.cs
contentFiles/cs/netstandard1.1/Class1.cs
[Content_Types].xml
package/services/metadata/core-properties/6312600f2bc343e882db96fd6bc3b99f.psmdcp
```

### Pack as content

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;netstandard1.1</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Class1.cs" />
  </ItemGroup>

</Project>
```

**Problem:** does not pack under a C# (`cs`) folder:

```
_rels/.rels
PackContent.nuspec
lib/netstandard1.0/PackContent.dll
lib/netstandard1.1/PackContent.dll
content/Class1.cs
contentFiles/any/netstandard1.0/Class1.cs
contentFiles/any/netstandard1.1/Class1.cs
[Content_Types].xml
package/services/metadata/core-properties/c812a30ee9a64a3c807dce065ce96403.psmdcp
```

### Sample Project

[PackContent.zip](https://github.com/NuGet/Home/files/5505348/PackContent.zip)

**Comment by zkat** [comment]
@joelverhagen let's chat a bit so we can figure out the right priority for this task.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/11467. 

That is newer, but it has more upvotes and a higher priority scenario.
