### ISSUE TITLE
Icon file validation by analyzing file content

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10235]
When working with embedded icon, at pack time, validate that icon file is, in fact, an image.

To doing so, NuGet should verify if those files complies with supported image formats: PNG and JPEG.

We cannot rely on WPF at pack time because NuGet is intended to work cross-platform and currently , WPF only works with Windows.

A possible solution would be to check magic numbers in file headers.

**Comment by nkolev92** [comment]
Low pri.
