### ISSUE TITLE
API to bulk install packages to project.json

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#1023]
When Portable retargets, it uses IVsPackageInstaller to install packages, which has 2 side effects:
1. there's a restore for every package installed
2. If the restore fails, we can fail to install the reference to Microsoft.NETCore which results in errors about missing types, instead of a restore error after the retarget.

We could avoid this if NuGet had an API allowing us to install multiple packages without attempting a restore.
(DevDiv 1202482)

**Comment by yishaigalatzer** [comment]
@joelverhagen where did this end up?

**Comment by nkolev92** [comment]
Redundant now. 
Lots has changed since then. 

Please reopen if you have similar asks.
