### ISSUE TITLE
NuGet.Packaging 5.8.0 is not published on nuget.org

### ISSUE THREAD

**Issue by 0xced** [NuGet/Home#10246]
It seems there was a publishing issue because all NuGet.* **5.8.0** packages (e.g. [NuGet.Common](https://www.nuget.org/packages/NuGet.Common/), [NuGet.Protocol](https://www.nuget.org/packages/NuGet.Protocol/), etc.) have been published 15 hours ago on nuget.org except for [NuGet.Packaging](https://www.nuget.org/packages/NuGet.Packaging/) whose latest published version is **5.8.0-preview.3.6823**.

**Comment by zivkan** [comment]
For transparency here's the story:

* A while ago msbuild pack had an issue where warnings treated as errors would not cause msbuild to report an error via process exit code, so build scripts wouldn't know there was an error. The nupkg was saved to disk, despite the error: https://github.com/NuGet/Home/issues/7404
* This was fixed. The nupkg is deleted on error, but the fix itself appears to have another bug where the exit code still returns a success value if pack is asked to create a symbols package: https://github.com/NuGet/Home/issues/10249
* NuGet.Client's own CI script packs our nupkgs and created a symbols package. Hence once we were using NuGet 5.7 to pack, any packages with warnings elevated to errors would be deleted, but the msbuild process exit code would not show an error, hence our build succeeded.
   * We don't have any validations to ensure that the expected nupkgs exist, so our build completed, and our publish pipeline pushed what it could find, and there was nothing to validate the packages that should exist do. Hence, we pushed packages with a missing dependency.

I regenerated the missing packages (NuGet.Packaging and NuGet.VisualStudio.Contracts) and they're now up on nuget.org. We have multiple learnings and room for improvement here.
