### ISSUE TITLE
Need API functions to find out TargetFrameworks of Package

### ISSUE THREAD

**Issue by punitganshani** [NuGet/Home#1024]
With the new structure of NuGet packages, need some way to find TargetFramework.   

Example: package `PlatformSpecific.Analyzer` supports only `uap` but package `EntityFramework.Commands` supports `.NETCore`, `.NETFramework`, `DNX` and `DNXCore`

```
var repo = Repository.Factory.GetVisualStudio("http://api.nuget.org/v3/index.json");
var metaResource = await repo.GetResourceAsync<UIMetadataResource>();
var versionIdentity = new PackageIdentity("PlatformSpecific.Analyzer", NuGetVersion.Parse("1.0.1"));
var meta = await metaResource.GetMetadata(versionIdentity, CancellationToken.None);
```

I've tried above API but it does not provide any information of TargetFramework

Or, is there any way (using API) to find out compatibility with a particular TargetFramework version?  
Like say, will `EntityFramework.Commands` work on `uap`?

**Comment by punitganshani** [comment]
@yishaigalatzer @emgarten is this possible with API?

**Comment by yishaigalatzer** [comment]
There is no good way to know this, TFMs don't predict that regardless of what an API exposes.

**Comment by yishaigalatzer** [comment]
@punitganshani can you provide some more backstory/scenario of what you are trying to do?

**Comment by yishaigalatzer** [comment]
So you will have to get the package down, and the story for finding out applicability to a target is described in this [gist](https://gist.github.com/yishaigalatzer/f94003b399d4fd28091c)
