### ISSUE TITLE
Create guidelines on changing brokered services

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10248]
Update the [NuGet SDK docs](https://github.com/NuGet/NuGet.Client/blob/dev/docs/nuget-sdk.md), or create new docs so:

1. People (both in the NuGet Client team and other contributors) creating pull requests have a guide for how they can "correctly" modify either of our 2 Contracts assemblies
2. NuGet Client team members reviewing pull requests know what they should look for and can provide meaningful feedback

I know VS's brokered service APIs and recommendations are moving fast, but the NuGet Client team has already had people outside the team contribute changes that needed changes to our RPC contracts, and those of us not working on the VS.OE implementation need guidance on how we can review these changes effectively.

In particular, I'd like guidance on when it's acceptable to modify an existing service version, and when it's necessary to create a new service version. When we create a new service version, how do we implement graceful fallback or functionality degradation. If we're creating a brand new service, what should we do regarding new clients connecting to old servers that don't implement the service. Guidance on when to use long lived proxies, and when to use short lived proxies. Guidance on events/callbacks.

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
