### ISSUE TITLE
Can nuget restore download packages from private repository using only API Key?

### ISSUE THREAD

**Issue by gkalnytskyi** [NuGet/Home#10241]
## Details about Problem
Can `nuget restore` (`dotnet restore`, `msbuild -t:Restore <path to project>`) use API key for the private repository to get packages from it, or Username / Password are required?

Every Nuget documentation page that mentioned API keys is for uploading the package to Nuget repository (which works fine for me), and none of them tells you if you can use API key when restoring packages. The [discussion](https://github.com/NuGet/Home/issues/6233) raises the similar issue, but I could find there a definite answer to this question.
Answer [here](https://github.com/NuGet/Home/issues/3664#issuecomment-354946142) also hints that username/password are required.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version: 5.7.0.6726

dotnet.exe --version (if appropriate): 3.1.403

VS version (if appropriate): 16.7.7

OS version (i.e. win10 v1607 (14393.321)): 10.0.17134 Build 17134

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1. Have a package in a private repo that requires you to provide login/password in order to download a package. (Let's call it RepoP)

2. Have a project and references the package mentioned above.

3. Have valid API key that allows you to upload package to the _RepoP_

4. Set `nuget.config`

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <config />
      <packageRestore>
        
        <add key="enabled" value="True" />
    
        
        <add key="automatic" value="True" />
      </packageRestore>
      <packageSources>
        <clear />
        <add key="nuget" value="https://api.nuget.org/v3/index.json" />
        <add key="RepoP" value="<RepoP Url>" />
      </packageSources>
      <apikeys>
        <add key="<RepoP Url>" value="<Valid Encrypted API Key>" />
      </apikeys>
    </configuration>

5. Use `nuget restore <project path> -ConfigFile .\nuget.config`

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
Cannot provide that, but nuget requests user to enter login/password for the RepoP repository.

**Comment by nkolev92** [comment]
Hey @gkalnytskyi 

This is a dup of https://github.com/NuGet/Home/issues/4049. 

The api key was added for pushing for sources that did not provide their own authentication. 

username/password is the recommended (and implemented in the clients :) ) way for authenticated feeds. 
Additionally https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds and https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin might be an interesting read aobut the auth capabilities NuGet provideds.

**Comment by nkolev92** [comment]
Note that I've created https://github.com/NuGet/docs.microsoft.com-nuget/issues/2205 to add this to our docs.

**Comment by gkalnytskyi** [comment]
Thank you, @nkolev92 !
