### ISSUE TITLE
Add warning to nuget.exe restore suggesting to use msbuild restore instead

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10244]
## Background

Solutions which only use PackageReference never needed to use nuget.exe restore. Solutions that had at least 1 packages.config project HAD to use nuget.exe, until we added `-p:RestorePackagesConfig=true` some time ago.

Since NuGet 5.8 had to introduce a change to the assets file for .NET 5, this has exposed a problem where customers use an old version of nuget.exe to restore their project (create the assets file), but then the version of the build tools they use (msbuild, .NET SDK) expects NuGet's newer "version" of the SDK. This causes the build to fail. It was made worse by an unclear error message that asked the customer to restore, rather than telling them that they were using inconsistent versions of tooling. But it shouldn't be so "difficult" to use consistent versions of tooling.

This is particularly a problem for CI, where the customer's build scripts will have steps like 1. Download/configure NuGet.exe (often specifying a specific version) 2. nuget.exe restore 3. msbuild -t:build. - It's difficult for customers to know they need to keep the versions of nuget.exe in-sync with the version of msbuild, especially when the build script uses whatever version of Visual Studio (msbuild) is installed on the CI agent, often out of their control, but they are responsible for getting nuget.exe, since it doesn't ship with VS. If they have a CI agent pool where different agents have different versions of Visual Studio/MSBuild, the customer's CI script has no chance of getting it "right", although the chance that different agents in a single pool using different versions of tools is very low, since most engineers expect the entire agent pool to be consistent.

## Proposal

NuGet.exe already does msbuild version detection. When we detect MSBuild version X or higher, we should emit an info message or warning telling the customer to use msbuild restore instead, with a link to docs where we explain how. We can detect if the solution uses any packages.config, or is PackageReference only, to give different messages, if needed.

Which version X of MSBuild to warn on is up for debate. We could figure out which version of msbuild we first shipped `-p:RestorePackagesConfig=true` and use that version. Or we could use 16.8, since this is the version starting to cause the current issues.

This will help us educate customers that they no longer need to use nuget.exe to restore.

**Comment by JonDouglas** [comment]
👍 to this suggestion.

My primary question would be about version compatibility. Do we expect MSBuild & NuGet to be an exact version match for maximum compatibility? Is NuGet backwards compatible enough with earlier versions of MSBuild? Should we only omit info / warning message if MSBuild is higher than NuGet?

We should explore the potential paths here and what we want users to be doing. I think we should not be pushing users to newer versions of NuGet if they are on older versions of MSBuild given how tightly coupled NuGet is to MSBuild nowadays. We should generally warn the user that they are using unaligned tooling versions in both directions in my opinion.

For example in the [NuGet Tool Installer](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops#arguments) documentation, users likely set `checkLatest` to true & will run into a plethora of build breaking issues.

> Always check for and download the latest available version of NuGet.exe which satisfies the version spec. Enabling this option could cause unexpected build breaks when a new version of NuGet is released

**Comment by donnie-msft** [comment]
We had a quick discussion and think this should be part of an Epic to deprecate `nuget.exe`. Lowering priority of this specific task until that can be written up.

**Comment by KalleOlaviNiemitalo** [comment]
Does `-p:RestorePackagesConfig=true` support _web site_ projects? (Those can be part of a solution and have a packages.config file, but they do not have a .csproj file, unlike _web application_ projects.) If not, then nuget.exe will still have to be used for them.

**Comment by zivkan** [comment]
@KalleOlaviNiemitalo from a quick test, nuget.exe does not restore the website project's packages.config file, when restoring the project.

My `nuget.exe restore website1.sln` output:

```text
MSBuild auto-detection: using msbuild version '17.0.0.32901' from 'C:\Program Files\Microsoft Visual Studio\2022\IntPreview\MSBuild\Current\bin'.
WARNING: Project file C:\Users\zivkan\source\repos\WebSite1\WebSite1\ cannot be found.
Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.
```

It didn't even find the website project's packages.config project to restore.  So, `git clean -xdf ; nuget.exe restore my.sln ; msbuild my.sln` ends up with a bunch of MSB3030 and MSB4181 warnings because the files in the pacakges folder can't be found. If you have a CI script, I imagine it will need to run `nuget.exe website1\pacakges.config -SoltuionDirectory $(Build.Workspace)` explicitly.

I intended this informational message, about using msbuild to restore, to be displayed only when a solution file is being restored, not when a specific packages.config file is restored. So, from my testing, website projects appear to be out of scope of this issue.

**Comment by nkolev92** [comment]
Team Triage: Closing for now since we're not deprecating NuGet.exe at this point in time. 
If that changes, we'll reopen this issue.
