### ISSUE TITLE
[API] DownloadCount is null

### ISSUE THREAD

**Issue by punitganshani** [NuGet/Home#1025]
`GetMetadata` method in the `UIMetadataResource` always gives DownloadCount as `null` instead of a numeric value

```
var repo = Repository.Factory.GetVisualStudio("http://api.nuget.org/v3/index.json");
var metaResource = await repo.GetResourceAsync<UIMetadataResource>();
var versionIdentity = new PackageIdentity("EntityFramework.Commands", NuGetVersion.Parse("7.0.0-beta5"));
var meta = await metaResource.GetMetadata(versionIdentity, CancellationToken.None);
if (!meta.DownloadCount.HasValue){
          // reaches here
}
```

**Comment by emgarten** [comment]
The download count is only available through the search resource.

**Comment by punitganshani** [comment]
Is there any limitation in providing it in `UIMetadataResource`?  
If its not available in `UIMetadataResource` why not remove the property DownloadCount?

**Comment by yishaigalatzer** [comment]
Download count is an active data, that constantly changes. Providing it on the basic resource means we can't serve data through proper static storage which scales a lot better.
