### ISSUE TITLE
[Performance]: Improve Commit Async for CPVM enabled projects

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#10256]
# NuGet CPVM DgSpec and NuGet.exe

## Summary
NuGet restore under CPVM showed a degradation in performance up to 65.9% (data obtained using CloudBuild branch).
After a set of performance improvements the regression decreased to 28.8.
Data as in the below table

| Run Id | Is CPVM  | Seconds  |  Percent Degradation |
|----------|-------------|-------------|------|
| 5.8.0.6864 | Yes | 73.404 | **65.9** |
| 5.8.0.6864  | No | 44.225 |   |
| 5.9.0.6886  | Yes | 55.950 | **28.8**  |
| 5.9.0.6886  | No | 43.429  |    |

The current document contains a proposal for how NuGet CPVM performance could be improved more. 
The document explains the problem and outline a set of proposals.

## Problem
When NuGet performs a full restore operation there are mainly two steps executed:
1. Restore
    - In this step the noop is evaluated, the dependency graph is created and analyzed, the lock file and conditions are evaluated, the assets and lock file is created in memory.
2. Commit
    - In the commit phase all the data is committed to disk (project.assets.json etc.)

From the two operations the Commit Async shows currently the most negative impact in CPVM / Not CPVM.  
Below are two snapshots with the CommitAsync and ProjectRestore information events(corresponding with the above two operations)

**CommitAsync**

![image](https://user-images.githubusercontent.com/16580006/95640408-81b9d380-0a51-11eb-9f22-e7b27943a1a1.png)

**ProjectRestoreInformation**

![image](https://user-images.githubusercontent.com/16580006/95640531-073d8380-0a52-11eb-80ae-b217187d5117.png)

The reason for having the CommitAsync double as time is because the information is larger in case of CPVM. When CPVM is enabled the central version information is persisted to disk in project.assets.json and in the dgspec files. 
A sample of this data is [here](\\ddfiles\Team\Public\cmanu\CPVM\Docs\Performance\Data_CommitAsync).

There are two reasons for serializing the data to the disk:
1. One of the NuGet principles is as the serialized dgspec data can be deserialized and be input for Restore.  
2. The current NuGet.exe implementation is based on the above principle.
    The main steps executed when a Restore is performed by NuGet.exe are:
    1. MsBuild is invoked with one of the NuGet tasks (WriteRestoreGraphTask) to write the dgspec.
    2. The DGSpec is deserialized, NuGet specific commands are added to the restore operation and the restore is started. 

## Proposals

All the proposals, except the default(not do anything) will mean to avoid serialization of the CPVM information in the assets and dgspec files.

### 1. Support CPVM- NuGet.exe by two writers

To support this it will need to be two dgspec writers one the writes the temp information for NuGet.exe and one that writes the regular assets and dgspec information on restore commit async step.

#### Pros
1. Performance improvements for MsBuild, VS restore and Nuget.exe. 

#### Cons
1. The principle mentioned above will not hold anymore.
2. Two writers will mean larger public surface (probably 2-3 more public APIs)

### 2. Support CPVM- NuGet.exe by redesigning NuGet.exe - MsBuild integration.
As mentioned above nuget.exe first calls MsBuild to generate the dgspec and after that the restore task is executed. 
The proposed solution is to find a way to just invoke MsBuild to execute restore. 
One if the challenges here is the fact that nuget.exe takes more arguments than the MsBuild currently supports. 

#### Pros
1. Performance improvements for MsBuild, NuGet.exe and VS restore CPVM scenarios. 
2. Probably perf improvements for Nuget.exe

#### Cons
1. The principle mentioned above will not hold anymore.
2. NuGet.exe probably will need to drop some functionality

### 3. Do not support NuGet.exe

To support this it will need only to not write the CPVM information. However with this approach NuGet.exe will not support CPVM. 

#### Pros
1. Performance improvements for MsBuild and VS restore CPVM scenarios. 

#### Cons
1. The principle mentioned above will not hold anymore.
2. NuGet.exe will not work for CPVM

#### Pros
1. No work. 

#### Cons
1. More perf degradation for the restore CPVM scenarios. 

## Prototype Stats

Below is data executing the CloudBuuild branch on a NuGet private drop with `Proposal 1`. 
There are two sets of data one for a run before the proposal and for a run after the proposal. 

`Commit Async`

![image](https://user-images.githubusercontent.com/16580006/95786104-d2b50c00-0c8b-11eb-9a9c-6ed415808188.png)

`Restore Task`

This is the overall restore (restore and commit) for the parallel tasks executing the restore.

![image](https://user-images.githubusercontent.com/16580006/95786345-2e7f9500-0c8c-11eb-94a3-33f872f2f102.png)

**Comment by nkolev92** [comment]
Not a priority at this point.
