### ISSUE TITLE
[Bug Bash][Unstable] Error “could not load file or assembly 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform” occurred after updating all the packages in ASP.NET Web Forms Site

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10265]
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.6966
VS Version: Master\30712.41
OS: Windows-10-Enterprise-19H2
## Detailed repro steps
1. Open any solution via VS, (**don’t close the solution/VS-it is easy to repro the bug**) click File->New->Project and click the template “ASP.NET Web Forms Site”.
2. Type the project name and click the “Create” button.
3. Open project PM UI, go to “Updates” tab, check “Select all packages” check-box and click “Update” button.
4. Click “OK” button in the prompt “Preview Changes” window.
5. Click “Yes to All” button in the prompt File Conflict dialog as below.
![image](https://user-images.githubusercontent.com/20632625/99084342-c6f99400-2601-11eb-819a-bf74dabe1471.png)
6. Build/rebuild the solution/project twice.
## Expected
Updating is successful without any error.
## Actual
Error “could not load file or assembly 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform” occurred in Error List window as below. Repro rate: 10%
![image](https://user-images.githubusercontent.com/20632625/99084473-f3151500-2601-11eb-8245-be6a6d156813.png)
## Notes
1.Error Message: Could not load file or assembly 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).
2.We will verify the regression info later.
3.It repro for ASP.NET Web Site (Razor v3).

**Comment by zkat** [comment]
Thanks for finding this! Can you share the regression info once it's available? In particular, whether this broke in 5.8 or 5.9

**Comment by v-luzh** [comment]
@zkat Hi Kat, it start to repro on Dev\6.9.0.6903 for me.

**Comment by zkat** [comment]
@aortiz-msft could you please look into this one and see what changes may have caused it?

**Comment by erdembayar** [comment]
@aortiz-msft @zkat 
Most likely connected to [Issue#10263](https://github.com/NuGet/Home/issues/10263). Asp.net related assembly resolution start having problem around same time.

**Comment by v-luzh** [comment]
This bug is fixed on Main\31101.164 + NuGet Client Dev\5.10.0.7152. Close it now, thanks.
