### ISSUE TITLE
[Bug Bash]Error “failed to add reference to 'Microsoft.Owin.Security.Cookies'” occurred after updating all the packages in ASP.NET Web Application (.NET Framework)-Single Page Application

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10263]
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.6966
VS Version: Master\30712.41
OS: Windows-10-Enterprise-19H2
## Detailed repro steps
1. Create an ASP.NET Web Application-Web Forms (.NET Framework 4.8), **(wait for the number on the right of the “Updates” tab coming out) go to “Updates” tab, check “Select all packages” check-box and click “Update” button**.
2.  **(Don’t close the solution/VS-it is easy to repro the bug)** Click File->New->Project and click the template “ASP.NET Web Application (.NET Framework)”.
3. Type the project name, click the “Create” button and select “Single Page Application”.
4. Open project PM UI, **(wait for the number on the right of the “Updates” tab coming out) click “Updates” tab, check “Select all packages” check-box and click “Update” button**.
5. Click “OK” button in the prompt “Preview Changes” window.
## Expected
Updating is successful without any error.
## Actual
Error “failed to add reference to 'Microsoft.Owin.Security.Cookies'” occurred in Error List window as below. 
![image](https://user-images.githubusercontent.com/20632625/99083973-43d83e00-2601-11eb-9270-cf22bb3bb9f2.png)
## Note
1.Error Message: Failed to add reference to 'Microsoft.Owin.Security.Cookies'.A reference to the component 'Microsoft.Owin.Security.Cookies' already exists in the project.
2.We will verify the regression info later.

**Comment by zkat** [comment]
Thanks for finding this! Can you share the regression info once it's available? In particular, whether this broke in 5.8 or 5.9

**Comment by v-luzh** [comment]
@zkat Hi Kat, It start to repro from Dev\6.9.0.6894 on my VM.

**Comment by zkat** [comment]
@aortiz-msft could you please look into what's new in this build and see if we can track down this regression?

**Comment by erdembayar** [comment]
@aortiz-msft 
I tried on today's latest main and public release and it didn't repro. If it's still problem then I need whole solution to verify again.

**Comment by v-luzh** [comment]
I can repro this issue on Main\30730.159 + NuGet Client Dev\5.9.0.6974 as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/100709675-7f3c8000-33e9-11eb-96bb-bb65a0290430.png)
The key points to repro this bug are the bold lines in the above step1 and step3. Can't upload the solution since it is too big even after making it to zip.

**Comment by erdembayar** [comment]
@v-luzh 
I just tried and still didn't repro. What was 
Maybe your repro steps missing something. Can you create gif animation with screentogif app and share here. I suspect it your initial solution/project before adding "Web application" project matters here.

**Comment by erdembayar** [comment]
@v-luzh @aortiz-msft 
I'm pinging again to remind. Can you help with repro of this bug? I was not able to repro this.

**Comment by v-luzh** [comment]
Hi @erdembayar I got the 100% repro steps after investigating. I created a clean machine (Win10 19H2)->create an ASP.NET Web Application-Web Forms (.NET Framework 4.8)->update all the packages->don't close the solution or VS and new an ASP.NET Web Application (.NET Framework 4.8)-Single Page Application->update all the packages (with the way in step4 and step5), then you would see the bug. Sorry about the previous non-clear steps. Update the steps.

Note: The ScreenToGif is "preparing to save" for a long time since the gif file is big I guess.

**Comment by erdembayar** [comment]
> Hi @erdembayar I got the 100% repro steps after investigating. I created a clean machine (Win10 19H2)->create an ASP.NET Web Application-Web Forms (.NET Framework 4.8)->update all the packages->don't close the solution or VS and new an ASP.NET Web Application (.NET Framework 4.8)-Single Page Application->update all the packages (with the way in step4 and step5), then you would see the bug. Sorry about the previous non-clear steps. Update the steps.
> 
> Note: The ScreenToGif is "preparing to save" for a long time since the gif file is big I guess.

@v-luzh 
I know your pain, because I already experienced it. Screen2Gif's default rendering engine is so bad. So instead use FFmpeg for it from settings, also it let's you easy download FFmpeg engine if it's missing on your machine.

![image](https://user-images.githubusercontent.com/8766776/104350758-5f54ad80-54b9-11eb-8857-c940d5c9d03d.png)

**Comment by erdembayar** [comment]
@v-luzh  @aortiz-msft 
I sent you my recording over email, please check.

**Comment by v-luzh** [comment]
Hi @erdembayar Here is the key point to work around known bug 1160376 and repro the #10263.
Attached the gif file of my repro on VS D16.9\30911.76 + NuGet Client Release-5.9.x-preview.3\5.9.0.7027.
1.	Create an ASP.NET Web Application-Web Forms (.NET Framework 4.8), (wait for the number on the right of the “Updates” tab come out) go to “Updates” tab, check “Select all packages” check-box and click “Update” button.
2.	(Don’t close the solution/VS-it is easy to repro the bug) Click File->New->Project and click the template “ASP.NET Web Application (.NET Framework)”.
3.	Type the project name, click the “Create” button and select “Single Page Application”.
4.	Open project PM UI, (wait for the number on the right of the “Updates” tab come out) click “Updates” tab, check “Select all packages” check-box and click “Update” button.
5.	Click “OK” button in the prompt “Preview Changes” window.
![UpdateError](https://user-images.githubusercontent.com/20632625/104407468-9cde3700-559c-11eb-919c-7940768f2c08.gif)

**Comment by erdembayar** [comment]
@v-luzh @aortiz-msft 

I found where this exception is coming from, it's [VsMSBuildProjectSystem](https://github.com/NuGet/NuGet.Client/blob/a0bccbf2705a1721d5b119c406382033d8160d81/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/ProjectSystems/VsMSBuildProjectSystem.cs#L815-L835) com interface call.

I tried to check in what is in com interface call but found bit challenging due it's being native code.  I wrote internal email for inquiring more information about it.

**Comment by erdembayar** [comment]
@v-luzh

After debugging we found what is wrong and provided that information to that "Webtools" team. Somehow it was resolving another dll as "Microsoft.Owin.Security.Cookies" and failing since they don't match. At this moment nothing we can to until they fix it. 
@aortiz-msft  can you follow up and ask for update later with "Webtools" team?

**Comment by v-luzh** [comment]
@erdembayar OK, thanks for your info. We will verify this bug after their fixing.

**Comment by erdembayar** [comment]
@v-luzh @aortiz-msft 
I created internal [ticket#1267486](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1267486) for external team. Since it's dup of that ticket I'm closing this one.
