### ISSUE TITLE
Missing Nuget.Commandline 5.8.0 package

### ISSUE THREAD

**Issue by dieterv** [NuGet/Home#10267]
## Details about Problem

It looks like all NuGet related packages have had a 5.8.0 release on nuget.org except NuGet.CommandLine which is still on 5.7.0.
This makes our CI builds fail when using .Net SDK 5.0.100 and the Cake build system. Cake references the NuGet.CommandLine package to ensure a nuget.exe file is available. NuGet versions < 5.8 seem to generate assets files without the TargetFrameworkAlias property, which ultimately fails our build with a bunch of NETSDK1005 errors.

Is the NuGet.CommandLine package on a different release schedule?

## Detailed repro steps so we can see the same problem

1. Navigate to https://www.nuget.org/downloads where the latest version is 5.8.0 indicating this is the latest available release

2. Navigate to https://www.nuget.org/packages/NuGet.CommandLine/ where the latest version is still 5.7.0

**Comment by Duracell1989** [comment]
The same is needed when working with Nuke combined with .NET SDK 5.0.100

**Comment by dieterv** [comment]
Looks like the NuGet.CommandLine 5.8.0 package has been made available a couple of days ago. Thanks !
