### ISSUE TITLE
How to create native NuGet packages with VS2015?

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#1027]
I've previously used CoApp (http://coapp.org/) to create native C/C++ NuGet packages. This have worked fine with VS2012 and VS2013, but the CoApp PowerShell tools do not currently support VS2015 (https://github.com/coapp/coapp.powershell/issues/112).

Are there plans for VS2015 support in CoApp, or will there be offered alternative means of creating/packaging native NuGet packages with VS2015?

**Comment by fubar-coder** [comment]
You can always provide your own toolset pivot:

```
configurations {
    Toolset {
        key : "PlatformToolset";
        choices: { v140, v140_xp, v120, v120_xp, v110, v110_xp, v100, v90, v80, v71, v70, v60, gcc };
    };
}
```

**Comment by forderud** [comment]
Thanks for the work-around tip fubar-coder! It did indeed work for me.

Still, one should not have to deal with work-arounds to create native NuGet packaged. The package creation tools offered should work out-of-the-box also for VS2015.

**Comment by fubar-coder** [comment]
It seems that [CoApp](https://github.com/coapp/coapp.powershell) is dead and therefore we're stuck with the current state of the project.

**Comment by yishaigalatzer** [comment]
There was never an official public story for packages to be installed in C++ projects (though that's different than Native packages delivering native payloads for C#/VB and C++ UWP projects, these are totally supported).

It is something we are working with the C++ team on, but we have no schedule yet. For now it remains a community/unofficial effort.

**Comment by rsudev** [comment]
@yishaigalatzer Just a question: Where can I find the 'official' support statement? I searched nuget.org and the FAQ still refers to http://blog.nuget.org/20130426/native-support.html WRT to C++ support.

**Comment by harikmenon** [comment]
Our official [docs ](https://docs.nuget.org/consume/support-for-native-projects) which is essentially derived from the blog you referenced documents defines this,  We support the folder convention as defined in the blog post and the ability to invoke package manager UI on C++ projects. CoApp is a community project and not something that is actively supported by us.
