### ISSUE TITLE
Prototype a Filtering mechanism & prepare for User Study

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10270]
Time-boxed effort to create prototype(s) for filtering packages in various PM UI views. The Epic serves as a guide for customer input.
Prepare these prototype(s) for the next User Study to solicit feedback.

- https://github.com/NuGet/Home/issues/5393

-  https://twitter.com/realDotNetDave/status/1130543286022656001

> @VisualStudio it would be really useful if in the @nuget package manager we could filter on author. For example, just packages by Microsoft. Would make it much easier to find packages that I want.

**Comment by donnie-msft** [comment]
Suggestions made in https://developercommunity.visualstudio.com/t/Nuget-package-updates-are-too-hard/1403616

**Comment by nkolev92** [comment]
Tracks the prototype, but since that's not immediately happening, the work can be part of https://github.com/NuGet/Home/issues/5393
