### ISSUE TITLE
Prototype UI Enhancements & prepare for User Study

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10274]
Time-boxed effort to create prototype(s) for enhancements to various PM UI functions. The Epic serves as a guide for customer input.
Prepare these prototype(s) for the next User Study to solicit feedback.

Some ideas:
- Scope any remaining work for Version Range support https://github.com/nuget/home/issues/6566

- Adding metadata https://github.com/NuGet/Home/issues/7957 & https://github.com/NuGet/Home/issues/8007

- Bonus would be to investigate GitHub commit integration: https://github.com/NuGet/Home/issues/8585

**Comment by nkolev92** [comment]
Given this tracks prototypes to linked issue and that's not hpapening right now, it's probably not very beneficial.
