### ISSUE TITLE
Nuget packages are not restored when switch from a branch to another one

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10279]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Nuget-packages-are-not-restored-when-swi/598462)._

---
Hi,

When I switch switch from a branch to another one with the GUI in VS 2019, the nuget packages are not restored.

Bruno

---
#### Feedback Bot on 6/10/2019, 00:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/7/2019, 06:33 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .
#### Feedback Bot on 3/31/2020, 05:36 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
This was moved from developer community. 

For the OP or anyone else experience this issue. 
We'd appreciate a repro solution, so we can test this out and narrow down what the problem might be.

**Comment by annieIqbal** [comment]
I have faced the same issue on visual studio 19 in mac. I was able to resolve it by following steps :
1- Quit the visual studio instance.
2- Switch to the intended code branch directly from Sourcetree or whatever tool you are using for branch management.
3- Restart the visual studio instance.

The switched branch loads successfully inside vs.

**Comment by nkolev92** [comment]
Hey @annieIqbal 

For Visual Studio for Mac, can you please report the issue in https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019.

**Comment by nkolev92** [comment]
Given that we have no repro for Visual Studio, closing this as no repro.
