### ISSUE TITLE
Can't minimize VS 2019, when Nugat Package Console is active

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10283]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Cant-minimize-VS-2019-when-Nugat-Packa/657195)._

---
When multiple package updates are active and I try to minimize Visual Studio the application get automatically the focus back.
So I'm not able to continue working on other topics, while waiting for the Nuget Package Updates.

---
#### Feedback Bot on 7/23/2019, 02:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/8/2019, 02:22 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/31/2020, 05:37 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by zkat** [comment]
@v-luzh hey, could you try repro this in the latest VS?

**Comment by v-luzh** [comment]
Hey @zkat Sorry, just saw this bug. It doesn't repro on Main\31820.317 + NuGet Client Dev\6.1.0.30.
