### ISSUE TITLE
Unable to download from api.nuget.org

### ISSUE THREAD

**Issue by TomGrube** [NuGet/Home#10287]
For months we've been able to successfully download NuGet packages when building our projects.  Starting on 11/13/2020, we started receiving the errors listed below and are unable to complete a build.  Our network provider said the calls are leaving our network but are getting rejected.  Any help would be appreciated.

Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.openapi/index.json'.
   The SSL connection could not be established, see inner exception.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/google.protobuf/index.json'.
   The SSL connection could not be established, see inner exception.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json'.
   Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/serilog/index.json'.
   The SSL connection could not be established, see inner exception.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/dbup-core/index.json'.
   An error occurred while sending the request.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.commandline/index.json'.
   The SSL connection could not be established, see inner exception.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/google.protobuf/index.json'.
   Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection/index.json'.
   The SSL connection could not be established, see inner exception.
     Unable to read data from the transport connection: Connection reset by peer.
     Connection reset by peer
   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/xunit.runner.visualstudio/index.json'.
   Connection reset by peer

**Comment by zivkan** [comment]
Please follow nuget.org's docs on [NuGet.org not accessible](https://docs.microsoft.com/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible)
