### ISSUE TITLE
Nuget source order not changed after using the options UI to try to effect a change

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10280]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Nuget-source-order-not-changed-after-usi/658557)._

---
If you use the Options UI and change a path or the boolean as to whether a particular nuget source is used, the changes are saved. However, if you reorder the paths using the up/down arrows the new order is not preserved.

BTW, the 'start recording' capture does not appear to be working.

---
#### Feedback Bot on 7/24/2019, 01:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 7/31/2019, 05:04 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/8/2019, 02:22 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
The ordering in the UI doesn't affect the NuGet behavior. 

Dup of https://github.com/NuGet/Home/issues/8315, which tracks the removal of these misleading arrows.
