### ISSUE TITLE
Package available through VS2015 Package Manager Console with v2 src but not with v3 src 

### ISSUE THREAD

**Issue by bentayloruk** [NuGet/Home#1028]
**Summary:**  Unable to `install-package` [FSharp.Core 4.0.0.1](https://www.nuget.org/packages/FSharp.Core/4.0.0.1) using Visual Studio 2015 Package Manager Console, when only the V3 API is configured as a package source.  Package Manager Console Host Version `3.1.1.0`.

When Package Sources is configured for API v3 use only, like this:
![screen shot 2015-07-28 at 10 35 19](https://cloud.githubusercontent.com/assets/189409/8928164/682d42fc-3514-11e5-8064-7bf6ddb2d2d1.png)

The Package Manager Console `-Version` auto-complete list for FSharp.Core looked like this:
![screen shot 2015-07-28 at 10 34 26](https://cloud.githubusercontent.com/assets/189409/8928136/46f38808-3514-11e5-9b6e-4aa0d5cf709f.png)

Specifying version `4.0.0.1` anyway, resulted in:

> Package 'FSharp.Core' is not found

However, when I add back the v2 API source AND disable the v3 source like so:

![screen shot 2015-07-28 at 10 40 24](https://cloud.githubusercontent.com/assets/189409/8928271/1fbe0c26-3515-11e5-87d9-ec9b4708fa0a.png)

...auto-complete contains `4.0.0.1` as expected, like below and package Happy Days are here!

![screen shot 2015-07-28 at 10 39 26](https://cloud.githubusercontent.com/assets/189409/8928248/f241ddc2-3514-11e5-8baa-46aeb30462c9.png)

*As an aside, There is an [unlisted `4.0.0` version](https://www.nuget.org/packages/FSharp.Core/4.0.0), which I see is listed in the v2 feed.  This unlisted version was not listed in the v3 API auto-complete list and was not installed when calling `install-package FSharp.Core`.  Version `3.1.2.5` was installed via this v3 command.  However, the unlisted `4.0.0` was installed via the v3 API when I issued an `update-package`.  I'm not sure if this is an issue, or the intended behaviour.*

**Comment by yishaigalatzer** [comment]
@maartenba @johnataylor @bhuvak @xavierdecoster here is another similar issue with the feeds. This might have been fixed already, please take a look

**Comment by yishaigalatzer** [comment]
@bentayloruk looks like the issue for this specific package is fixed already. We are tracking an issue where some new packages don't show up on the V3 feed. We haven't found the root cause yet, but its our top priority at the moment.

**Comment by bentayloruk** [comment]
Thanks @yishaigalatzer!  Any chance you could link to the issue being tracked?

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGetGallery/issues/2614
