### ISSUE TITLE
Incorrect error message, shows a format string rather than the expanded string

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10281]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Incorrect-error-message-shows-a-format-/645356)._

---
When attempting to build a Xamarin.Forms project for Android, I get the following message. Note the {0} at the end, which is clearly intended for string. Format, but which presumably has just been used as is, rather than being used as a format string. The result is a message that is of little use, as it doesn't tell me what the missing file is.

Set Property: ErrorText=This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.

---
#### Feedback Bot on 7/16/2019, 01:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/8/2019, 02:21 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Feedback Bot on 3/31/2020, 05:45 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by dominoFire** [comment]
Possible issue:

https://github.com/NuGet/NuGet.Client/blob/65abcc61f73ab3d87928495f789ec74011edde7f/src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs#L371

**Comment by dominoFire** [comment]
The `EnsureNuGetPackageBuildImports` is a MSBuild target inserted when NuGet installs a package with .target files in a packages.config project.
The task inserts a Property with a formatted string as follows:

```xml
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    ... Error conditions ...
```

Later, error conditions uses that property to create the error message saying which targets file is missing.

Two code paths add this target:

- [src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs](
https://github.com/NuGet/NuGet.Client/blob/35b6dcdb23642c502065458d91e644fb6fb17ecf/src/NuGet.Clients/NuGet.CommandLine/Common/MSBuildProjectSystem.cs#L348)
- [src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Utility/MicrosoftBuildEvaluationProjectUtility.cs](https://github.com/NuGet/NuGet.Client/blob/65abcc61f73ab3d87928495f789ec74011edde7f/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Utility/MicrosoftBuildEvaluationProjectUtility.cs#L87)

The only way '{0}' could appear in the message is to explicitly set in the MSBuild error conditions.

**Comment by dominoFire** [comment]
Closing for now. Per comment above, it does not seem as a bug, but a by-design behavior.

If anyone experiments this issue, feel free to comment and reopen.
