### ISSUE TITLE
Application.exe.config being overwritten during build

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10282]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Applicationexeconfig-being-overwritten/610276)._

---
During the build of our application, app.config gets copied to &lt;application&gt;.exe.config, this is then overwritten with a binding redirect. 
 This is only happening on two out of four machines, on two it builds as normal, copying the app.config file to &lt;application&gt;.exe.config. On the other two, &lt;application&gt;.exe.config just contains a binding redirect after the application has built.
 We have narrowed it down to the reference of an external dependency, when the use of this dependency is removed, the app.config is copied correctly on build.
 Is this a Visual Studio setting that is trying to put in a binding redirect, as it can't find the correct version of the dependency? (I have tried disabling auto binding redirect, it didn't work)

---
#### Feedback Bot on 6/18/2019, 02:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jin Zhao [MSFT] on 6/19/2019, 01:36 AM: 

<p>Thank you for your feedback! For us to investigate this further, could you provide more details:</p><ol><li>what's the contain in you app.config?</li><li>What external dependence is reference in your project, how it used?</li></ol><p>It will be better if you can provide your repro solution. </p><p>We look forward to hearing from you!</p>

#### Caillin Spain on 6/19/2019, 02:26 AM: 

<ol>
<li>what is contained in your app.config?</li></ol><p>   The app.config contains required dependency versions which are used in checks on application boot. When it is overwritten, it is overwritten with a binding redirect for a dependency which our application uses. </p><p>2.What external dependencies are referenced in your project, how are they used?</p><p>The dependency that the binding redirect is for is Newtonsoft, it is used by our application and also by another third party dependency, which we use in our app.</p><p>Is there a setting in Visual Studio to add auto binding redirects, other than the setting in the csproj, as I have disabled that.</p>

#### Feedback Bot on 6/19/2019, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Jin Zhao [MSFT] on 6/19/2019, 07:25 PM: 

(private comment, text removed)
#### dan.carter on 7/4/2019, 07:46 AM: 

<p>Any update on this? I'm getting exactly the same behaviour in VS2019. On my machine the config file in the bin\Debug\ does not match the app.config file in the project, but this is not happening for my colleages on the same solution.</p>

#### Feedback Bot on 8/7/2019, 06:34 PM: 

We want to let you know that this problem will likely be closed in 60 days. We set priority based on severity, similar reports, and the overall impact on users and scenarios. We've also learned that reports without fresh activity could indicate that the problem isn't a problem anymore. One of our goals is to give you more transparency around these decisions as resolving every problem that gets reported isn't always possible. Your feedback is essential for helping us decide what needs the most attention, so please keep upvoting and commenting if you think that we need to make this a higher priority .
#### Caillin Spain on 9/25/2019, 07:38 AM: 

<p>Update: I am now using a new PC with a fresh install of Visual Studio and have all the settings as before (the same as the rest of my team) and I am still getting this issue, so that's now 3 PC's in our team with this problem. I am unable to run my application without using a nasty work around (post build step to overwrite the exe.config with the app.config contents), other people are reporting this same problem, so please continue to investigate. </p>

#### Feedback Bot on 3/31/2020, 05:35 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Caillin Spain on 8/27/2020, 06:14 AM: 

<p>Any updates? Over a year later and still getting this problem...</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Triage: There's a discussion in the internal issue.

**Comment by nkolev92** [comment]
Re-opening the original issue to listen for feedback.

**Comment by trydalch** [comment]
I'm still seeing this behavior in VS 2022. Not sure why this was closed. I've had to turn off assembly binding auto generation and just put the binding redirects in my app config file. 

But every time I update a package, I have to turn on the binding redirect generation and then copy/paste them into the app config then turn the generation off again. 

Considering putting a post build event in to merge the app settings in with the auto generated assembly bindings so that I can just leave it on, but I shouldn't have to do that.

**Comment by zivkan** [comment]
If the auto-generated binding redirects work for you, why do you have them commit into your repo's app.config? You could remove them and let msbuild auto-generate them on every build.  If the auto-generated ones work, why do you disable auto generation after copying them?

Understanding customer impact and scenarios helps us prioritize efforts.

**Comment by trydalch** [comment]
The binding redirects work, and each time that I generate them I do commit them to my app config. 

The main issue is that when I have auto generation turned on, I can't run/debug the application from visual studio because when the assembly bindings are generated and placed in the app config, it overwrites the contents of my app.config and I lose all my app settings. 

So to debug, I have to turn assembly binding auto generation off.

**Comment by trydalch** [comment]
Am I doing something wrong? I'd expect the build process to just insert the correct assembly bindings into my app.config without overwriting my app settings, nor custom sections.

**Comment by zivkan** [comment]
Here's my test project: [appConfigTest.zip](https://github.com/user-attachments/files/23972991/appConfigTest.zip)

The app.config only has settings, no binding redirects. When you build, it creates `bin\Debug\net48\appConfigTest.exe.config that has the settings from the project's app.config, and also binding redirects. Since it's in the bin\ directory, it's excluded from source control. Running the console app works as expected.
