### ISSUE TITLE
Implement dotnet nuget config command

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#10294]
Implement the equivalent dotnet command of  `nuget config` command

**Comment by erdembayar** [comment]
@heng-liu @zkat @kartheekp-ms @aortiz-msft 
Do you have spec for this one?

**Comment by zkat** [comment]
No. We'll need one and will have to run it by Kathleen, too.

**Comment by nkolev92** [comment]
Closing this in favor of https://github.com/NuGet/Home/issues/7133, which is a community ask with a lot more upvotes
