### ISSUE TITLE
`nuget.exe` and `dotnet.exe nuget` feature parity

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10293]
Both NuGet Command Line Interfaces should have the same functionality but, they can differ in applicability:

nuget.exe: .NET Framework + .NET Core + .NET 5
dotnet.exe: .NET Core + .NET 5

Both CLI's should have the feeling of the same user experience

New developments should favor dotnet.exe; but we should still support nuget.exe; as it's the only NuGet client tool that works on .NET Framework

Ideally, NuGet CLI interfaces should deliver the same experience, regardless of OS-platform and supported .NET version.

**Comment by nkolev92** [comment]
Yet another tracking issue. 

Closing.
