### ISSUE TITLE
Update-Package : “.”(十六进制值 0x00)是无效的字符。 第 22 行，位置 11。

### ISSUE THREAD

**Issue by baiqiaw** [NuGet/Home#10296]
Update-Package : “.”(十六进制值 0x00)是无效的字符。 第 22 行，位置 11。
所在位置 行:1 字符: 1
+ Update-Package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

Microsoft Visual Studio Enterprise 2019
版本 16.8.1
中无法还原、更新、安装Nuget包

**Comment by nkolev92** [comment]
Hey @baiqiaw 

I used a translator, is this something you can reproduce reliably? Can you please attach a repro?

**Comment by zkat** [comment]
Closing this for now--please file a new issue using the issue template if you're able and we'll take a look then.
