### ISSUE TITLE
[nuget.org] 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。

### ISSUE THREAD

**Issue by yzc597425449** [NuGet/Home#10290]
还原 NuGet 程序包时出错: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
[nuget.org] 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。
  基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
  根据验证过程，远程证书无效。

PM> Install-Package Dapper -Version 2.0.35
正在还原 D:\2020.11.16\PDMcontrol\PDMcontrol\PDMcontrol.csproj 的包...
Install-Package : 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
  发送请求时出错。
  基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
  根据验证过程，远程证书无效。
所在位置 行:1 字符: 16
+ Install-Package <<<<  Dapper -Version 2.0.35
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
已用时间: 00:01:24.1254173

**Comment by zivkan** [comment]
I have provided guidance for another customer here: https://developercommunity2.visualstudio.com/t/VS-2019-Publish-issue---Unable-to-load-t/1257366?preview=true#T-N1257595

We'll try to improve guidance and documentation, but ultimately it's up to your computer's configuration.

Closing as a duplicate of https://github.com/NuGet/Home/issues/9961

**Comment by z1y1m1** [comment]
手动下载nuget.org的证书，然后添加到系统的受信任证书就可以了
![Uploading 59516-20220922104344478-1459811668.png…]()

**Comment by strawHatNoLuffy** [comment]
首先需要检查自己是否开启了VPN 并且在访问google过程中是否出现断连，如果有请更换节点，其次的解决办法就是手动下载nuget证书
