### ISSUE TITLE
vs2019, when installing some package with NuGet, get the error "you are trying to install this package into a project that targets 'native,Version=v0.0"

### ISSUE THREAD

**Issue by GitZinger** [NuGet/Home#10298]
Remove the content above here and fill out details below.

## Details about Problem
I create an empty project. also now there is no network choice when creating a new project in vs 2019

Could not install package AWSSDK.Core  
```
You are trying to install this package into a project 
that targets 'native,Version=v0.0', 
but the package does not contain any assembly references 
or content files 
that are compatible 
with that framework. For more information, 
contact the package author.	
```			
but I set the

```
project property -> configuration properties-> c++/cli  properties 
->.net target framework version : v.50
```

please help me here!

I really appreciate it!

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
vs ui NuGet solution
NuGet version (x.x.x.xxx):
unknown
dotnet.exe --version (if appropriate):

VS version (if appropriate):
2019 community
OS version (i.e. win10 v1607 (14393.321)):
win 10
Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. create an empty project

2. install AWSSDK.Core

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Hey @GitZinger 

Is your project a vcxproj? 

Only `vcxproj` should be considered native and pacakges like `AWSSDK.Core` usually cannot be installed because they are managed. 

It'd be helpful if you can attach the project in question. 

Thanks!

**Comment by GitZinger** [comment]
@nkolev92 
Yes. it is an empty c++ project in the visual studio.
and yes, there is a vcxproj file in the folder.
and what do you mean by "managed"?
til now I am not able to install that AWSSDK.Core package from NuGet into my project. What are those for? not for c++?

**Comment by nkolev92** [comment]
AWSSDK.Core packages are not suitable for C++(native).
It contains managed assemblies only, so it supports .NET Framework and .NET Core.

**Comment by GitZinger** [comment]
I see.  it would be better that there is some instruction there saying this SDK is for .NET not for C++.
Thank you.
