### ISSUE TITLE
anyway i can stop getting .net core 5.0 packages in nuget package update for my .net core 3.1 applications

### ISSUE THREAD

**Issue by KamranShahid** [NuGet/Home#10309]
reference to my https://github.com/dotnet/core/issues/5606 can someone help

**Comment by zkat** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/5725

**Comment by KamranShahid** [comment]
How it is related?

**Comment by zkat** [comment]
@KamranShahid we currently don't support filtering by TFM when updating/installing/etc. This means that we just go by version number, even if the new version number happens to be incompatible with the current project's TFM(s). That other issue is for adding that feature.
