### ISSUE TITLE
Create Mock factory for EnvDTE.DTE object

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10306]
There's no way to create a test instance of EnvDTE.DTE object for NuGet testing purposes.

This interface is hard to mock because it represents a large core part of Visual Studio.

Having a minimal, common EnvDTE.DTE  mock object factory would enable NuGet codebase developers to improve testing in VS-NuGet components.

**Comment by nkolev92** [comment]
EE triage: 
I feel tasks like this are best handled on an as needed basis. 
It's difficult to make the argument for this task to ever get assigned in isolation.
