### ISSUE TITLE
nuget.exe -update self can't ... update itself to NuGet v5.8.0

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/Home#10300]
Version 5.8.0 is available for download on https://www.nuget.org/downloads, however nuget 5.7.0 is not able to update itself and download version 5.8.0.

![image](https://user-images.githubusercontent.com/177608/99629817-10395180-2a0f-11eb-8fe6-b6a96a467e28.png)

```
C:\augustoproiete>nuget.exe update -self
Checking for updates from https://api.nuget.org/v3/index.json [https://api.nuget.org/v3/index.json].
  CACHE https://api.nuget.org/v3/registration5-gz-semver2/nuget.commandline/index.json
Currently running NuGet.exe 5.7.0.
NuGet.exe is up to date.
Update successful.
```

![image](https://user-images.githubusercontent.com/177608/99629325-33173600-2a0e-11eb-842a-58b49cb99aa4.png)

## Repro steps

1. Download NuGet v5.7.0
https://dist.nuget.org/win-x86-commandline/v5.7.0/nuget.exe

2. Run `nuget.exe update -self`

## Version info

NuGet version: 5.7.0.7 5.7.0+b804bf4ba62c0b47c77bbf3e22e196b57cd7a556.b804bf4ba62c0b47c77bbf3e22e196b57cd7a556

**Comment by zivkan** [comment]
@zkat FYI as hotseat this week.

**Comment by zkat** [comment]
We are in the process of "blessing" 5.8.0. This should be resolved soon. 👍🏻

**Comment by augustoproiete** [comment]
Perfect. Thanks!

**Comment by zkat** [comment]
This should be all set.
![image](https://user-images.githubusercontent.com/17535/99733801-96d54980-2a76-11eb-89fb-8d1547588fa5.png)
