### ISSUE TITLE
ACLs mess with the reading of  NuGetDefaults 

### ISSUE THREAD

**Issue by Ka0o0** [NuGet/Home#10317]
## Details about Problem

dotnet

NuGet version (x.x.x.xxx): 5.7.0.7

dotnet.exe --version (if appropriate): 3.1.404

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Debian Buster

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Make sure you have a clean installation (e.g. no dotnet restore or smth. similar called)

2. Create a file root owned */etc/opt/NuGet/NuGetDefaults.config* and add content. E.g.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local" value="/var/lib/dotnet/packages" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
</configuration>
```

3. Make sure permissions are readonly for other users:

```
-rw-r--r--. 1 root root 336 Nov 20 07:32 /etc/opt/NuGet/NuGetDefaults.config
``` 

4. Create a new project as root  `dotnet new console` somewhere

5. Login as other user & try to create also a new console app

6. Observe the error

```
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(557,5): error : The type initializer for 'NuGet.Configuration.ConfigurationDefaults' threw an exception. [/tmp/example/client/client.csproj]

/usr/share/dotnet/sdk/3.1.404/NuGet.targets(557,5): error :   Unable to obtain lock file access on '/tmp/NuGetScratch/lock/68c94b3156f40e62c7ce7afc81fc0b62c95ef99f' for operations on '/etc/opt/NuGet/NuGetDefaults.config'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock/68c94b3156f40e62c7ce7afc81fc0b62c95ef99f' will allow NuGet to continue. [/tmp/example/client/client.csproj]
```

I think the expected behavior is that the locks are not applied to a shared "read-only" resource like NuGetDefaults?

### Sample Project

I will add an example docker image asap

**Comment by nkolev92** [comment]
Hey @Ka0o0, 

Can you please try applying the permissions to directory instead of just the file? 

NuGet's cross process locking rely on creating a marker file in the same directory as the file of interest, so I'm guessing that might be the root cause here.

**Comment by Ka0o0** [comment]
Hi again,
as promised, here is a Dockerfile which creates a second user `demo` .  Make sure that you have a NugetDefaults.config inside your Docker build folder.

```
# after compile run with
#     docker run -it 2c8ac84a43d3 su demo -c "cd /tmp/test2 && dotnet new console"

FROM mcr.microsoft.com/dotnet/sdk:3.1

COPY NuGetDefaults.config /etc/opt/NuGet/NuGetDefaults.config

RUN chmod 644 /etc/opt/NuGet/NuGetDefaults.config &&\
    mkdir /tmp/test1 &&\
    cd /tmp/test1 &&\
    /usr/bin/dotnet new console

RUN useradd demo --create-home &&\
    mkdir /tmp/test2 &&\
    chown demo:demo /tmp/test2

```

You can trigger the error by running the container as `docker run -it ENTERHASH su demo -c "cd /tmp/test2 && dotnet new console"`.

Following you suggestions I created another version, where I set the permissions of the folder /etc/opt/NuGet to 644 and it works! 

```
FROM mcr.microsoft.com/dotnet/sdk:3.1

COPY NuGetDefaults.config /etc/opt/NuGet/NuGetDefaults.config

RUN chmod 644 /etc/opt/NuGet &&\
    chmod 644 /etc/opt/NuGet/NuGetDefaults.config &&\
    mkdir /tmp/test1 &&\
    cd /tmp/test1 &&\
    /usr/bin/dotnet new console

RUN useradd demo --create-home &&\
    mkdir /tmp/test2 &&\
    chown demo:demo /tmp/test2
``` 

Please feel free to close this issue, if you think that this works as intended. Thanks.

**Comment by nkolev92** [comment]
Thank you for following up. It is as expected, but we do need better docker guidance to help people not run into this issue.
