### ISSUE TITLE
NuGet.CommandLine: Test(s) on nuget source command are failing

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1031]
NuGet.CommandLine: Test(s) on nuget source command are failing. Currently, they are marked to be skipped so that the CI build successfully

1. SourcesCommandTest_AddWithUserNamePassword_UserDefinedConfigFile

**Comment by zhili1208** [comment]
this is caused by https://github.com/NuGet/Home/issues/998. configFile switch is not working for sources add

**Comment by rrelyea** [comment]
SourcesCommandTest_AddWithUserNamePassword_UserDefinedConfigFile was really broken due to an extra whitespace, it appears. Reenabling test with: NuGet/Home#4126
