### ISSUE TITLE
Parallel restore randomly fails package certificate trust (in container)

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#10322]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.8.0.6930 (via Pipelines `NuGetToolInstaller@0` task)

VS version: 2019 Build Tools v16.8.2

OS version: Server 2019 (1809 build 17763.1577) + Docker hosting mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2019

Worked before? If so, with which NuGet version: New scenario for us

## Description

1. Prepare a Pipelines Docker-based build agent using steps similar to those at https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#windows and using the `--once` agent option.

2. Use the resulting image with Docker Swarm on a 32-core host (so there are a couple of dozen agents running simultaneously).

3. Start multiple builds for solutions containing 100+ projects each with restore steps, using a nuget.config containing `<add key='maxHttpRequestsPerSource' value='4' />`.

What we are seeing is failures validating packages from nuget.org (`PackageSignatureValidity: False`). The failures appear nondeterministic -- the specific packages that succeed or fail look to be different each time, and the number of packages failing during a given run is not consistent either -- but the failure becomes more probable if more than one container's agent is restoring simultaneously.

Adding the `-DisableParallelProcessing` flag seems to make the problem go away, at the cost of a longer time to restore, while lowering `maxHttpRequestsPerSource` seems to have no effect.

Speculation: each container sees itself has having 32 CPUs, so NuGet starts 32 concurrent restore jobs (if parallel processing is left on). The error messages suggest some sort of failure during certificate validation; assuming the certificate doesn't change but the outcome does, perhaps a request rate limit is being hit somewhere?

### Verbose Logs
(Excerpts)

> NU3028: Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> NU3018: Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': The repository primary signature found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> Errors in C:\vsts\_work\1\s\Web\<project_name>.csproj
>     NU3028: Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
>     NU3018: Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': The repository primary signature found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

Later:

> PackageSignatureVerificationLog: PackageIdentity: Microsoft.AspNet.Razor.3.2.3 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: False
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': Timestamp: 12/14/2018 5:55:55 AM
> 
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': Verifying repository primary signature's timestamp with timestamping service certificate: 
>   Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
>   SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
>   SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
>   Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
>   Valid from: 1/2/2017 8:00:00 AM to 4/2/2028 7:59:59 AM
> 
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json':       Subject Name: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
>       SHA1 hash: 6FC9EDB5E00AB64151C1CDFCAC74AD2C7B7E3BE4
>       SHA256 hash: F3516DDCC8AFC808788BD8B0E840BDA2B5E23C6244252CA3000BB6C87170402A
>       Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
>       Valid from: 1/12/2016 8:00:00 AM to 1/12/2031 7:59:59 AM
> 
>             Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
>             SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
>             SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
>             Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
>             Valid from: 4/2/2008 8:00:00 AM to 12/2/2037 7:59:59 AM
> 
> 
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': repository primary signature's timestamp
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': Signature type: Repository
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': nuget-v3-service-index-url: https://api.nuget.org/v3/index.json
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': nuget-package-owners: aspnet, Microsoft
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': Verifying the repository primary signature with certificate: 
>   Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
>   SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
>   SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
>   Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
>   Valid from: 4/10/2018 8:00:00 AM to 4/14/2021 8:00:00 PM
> 
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json':       Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
>       SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
>       SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
>       Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
>       Valid from: 10/22/2013 8:00:00 PM to 10/22/2028 8:00:00 PM
> 
>             Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
>             SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
>             SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
>             Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
>             Valid from: 11/10/2006 8:00:00 AM to 11/10/2031 8:00:00 AM
> 
> 
> Package 'Microsoft.AspNet.Razor 3.2.3' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's certificate chain validation failed with error(s): UntrustedRoot, RevocationStatusUnknown, OfflineRevocation

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/10275. 

Please upvote that issue. Thanks.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/10275, but does not seem to have the same root cause.

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/Home/issues/8726.

**Comment by ghost** [comment]
> Closing as dup of #8726.

I'm afraid the log excerpts I gave may have been too trimmed (parts of our org aren't fans of such sharing). Just double-checking this really is a dup of #8726 in terms of error manifestation; that reports a timeout during download of the nupkg; we aren't seeing any errors with retrieving the nupkg files, only with validating them after download completes successfully.

For the same package as in the sig validation error above:
>   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.razor/3.2.3/microsoft.aspnet.razor.3.2.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.razor/3.2.3/microsoft.aspnet.razor.3.2.3.nupkg 41ms

If the fix for both is the same, then that's fine. :)
