### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by onwuchekwa** [NuGet/Home#10321]
## Details about Problem
I am unable to install Microsoft.EntityFrameworkCore.SqlServer -Version 5.0.0 package. The following error is displayed on the console:
_PM> Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 5.0.0
Restoring packages for C:\Users\osunday\source\repos\ContosoUniversity\ContosoUniversity\ContosoUniversity.csproj...
Install-Package : Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.SqlServer -Version 5.0. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:09.3305969

However, I manage to install version 2.2.0 but was not able to scaffold because the system threw "There was an error running the selected code generator: Unable to load the service index for source https://api.nuget.org/v3/index.json"
 
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Package Manager Console

NuGet version (x.x.x.xxx): 5.8.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2019 v16.8.2

OS version (i.e. win10 v1607 (14393.321)): win10 v1609

Worked before? If so, with which NuGet version: Yes, 5.8.0

**Comment by nkolev92** [comment]
Hey @onwuchekwa, 

Are you still running into this problem? 
Was it only Visual Studio that was running into this problem?
It's possible that you hit an intermittent networking issue.

If you are still running into this, try https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible.

**Comment by onwuchekwa** [comment]
I will get back to you

**Comment by aortiz-msft** [comment]
Closing for now but feel free to add comments if you continue having issues.

**Comment by cw-1988** [comment]
I'm having the same issue with the nuget package manager right now...
