### ISSUE TITLE
How to programming set package management format

### ISSUE THREAD

**Issue by hayletdomybest** [NuGet/Home#10323]
NuGet product used: NuGet.VisualStudio

version: 5.8

OS version: win10

Hi I encounter some problem about using NuGet.VisualStudio to develop Visix programe.

When I use IVsPackageInstaller.InstallPackage(null, project, moq, null, false).

I always get format "0" (not reference format) in installing package.

I realize when source fill with null, Installing process will use user's configured sources, I am sure my configured source management format which select format 1.

Dose any lose step, when i use InstallPackage of IVsPackageInstaller.

I found this commit [#2698](https://github.com/NuGet/NuGet.Client/pull/2698/commits/f089dc92596f8130b3f4fd71ea111bc8849a9fa8)
but it still not resolve my problem.

**Comment by nkolev92** [comment]
Hey @Hsu-Cheng-Wei, 

In projects that support both packages.config and PackageReference, the package management format is controlled by the nuget.config. 

You *might* need to reload VS to ensure the nuget.config is reloaded. 

Would you be able to provide a repro for us?

**Comment by aortiz-msft** [comment]
Closing since we haven't heard back from you. Feel free to add comments if you continue having problems or file a new issue. Thanks!
