### ISSUE TITLE
Add Remove.ps1 hook to run before remove package folder

### ISSUE THREAD

**Issue by lijunle** [NuGet/Home#1032]
My scenario is my `Install.ps1` script will create some files under package installation folder. Nuget needs I to remove those files after the latest uninstall from the solution. But I don't find a hook to do so.

From code aspect. Nuget will [remove the package folder](https://github.com/NuGet/NuGet.PackageManagement/blob/6da43b234eeaf9d1974cb6c5933f72ea311896d7/src/ProjectManagement/Projects/FolderNuGetProject.cs#L203) if the package [is not referenced by any project in the solution any more](https://github.com/NuGet/NuGet.PackageManagement/blob/8ab90543e1b407206c4c56fb03f5a4e7f66f09ec/src/PackageManagement/NuGetPackageManager.cs#L1640). But, such deletion could fails and throws an exception. In such case, the nuget [tells VS to prompt "uninstall fails, restart VS to complete."](https://github.com/NuGet/NuGet.PackageManagement/blob/8ab90543e1b407206c4c56fb03f5a4e7f66f09ec/src/PackageManagement/NuGetPackageManager.cs#L1311). That message is confusing.

It could be great to provide a hook right before [the invoke to delete package action](https://github.com/NuGet/NuGet.PackageManagement/blob/8ab90543e1b407206c4c56fb03f5a4e7f66f09ec/src/PackageManagement/NuGetPackageManager.cs#L1303).

**Comment by yishaigalatzer** [comment]
What is wrong with `uninstall.ps1` ?

**Comment by yishaigalatzer** [comment]
The install.ps1 should not generate any files in the packages folder. That's a design flaw in the package.
