### ISSUE TITLE
project.assets.json file is missing transitive project dependencies when mixing PackageReference and packages.config with v5.8

### ISSUE THREAD

**Issue by sourabhkrishna** [NuGet/Home#10320]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.8

dotnet.exe --version (if appropriate): 

VS version (if appropriate): vs2019 Latest - MSBuild with /r restore option

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: v5.7

## Detailed repro steps so we can see the same problem

1. When building a .net461 project from VS 2019 - performs a successful build and projects.assets.json file has all project references with dependencies listed.

 "XX.Credentials.Domain/1.0.0": {
        "type": "project",
        "dependencies": {
          "XX.Access.DataAccess": "1.0.0",
          "XX.Credentials.Formats": "1.0.0"
        },
        "compile": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        },
        "runtime": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        }
      },

2. When building the same project via Azure Pipelines -> nuget install (v5.8) -> nuget restore -> ms build (v16.8) -> the project.assets.json file misses the project dependencies , hence build failed with assembly missing issues.

 "XX.Credentials.Domain/1.0.0": {
        "type": "project",
        "compile": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        },
        "runtime": {
          "bin/placeholder/XX.Credentials.Domain.dll": {}
        }
      },

**Comment by yuryk53** [comment]
Looks like our team is facing the same issue. The bug reproduces starting from VisualStudio update 16.8.x. What is interesting, build from Visual Studio succeeds, but build using msbuild.exe from console doesn't work - looks like VS has custom restore logic.

In our case, we have  3 projects: A, B and C. "A" depends on "B", and "B" depends on "C" (A -> B -> C). Project "A" uses classes from both "B" and "C". If I build project A with VisualStudio, build succeeds, but if I do `nuget restore A`, and than `msbuild A` -> build fails with [NETSDK 1005](https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1005) error

**Comment by nkolev92** [comment]
Hey folks, 

Apologies for the issues. We have a fix, we're considering patching it down level. 

This looks equivalent to https://github.com/NuGet/Home/issues/10326.

**Comment by nkolev92** [comment]
hey @sourabhkrishna 
If possible, we'd appreciate it you can help us confirm that your issue is addresed by testing out https://dist.nuget.org/win-x86-commandline/v5.9.0-preview.2/nuget.exe
