### ISSUE TITLE
 Restore fails with NU1106 for solution that uses StaticGraph and CPVM

### ISSUE THREAD

**Issue by marcin-krystianc** [NuGet/Home#10327]
## Details about Problem

NuGet product used: `dotnet.exe`

dotnet.exe --version: `5.0.100`

## Detailed repro steps so we can see the same problem

1. Run `dotnet restore --force /p:RestoreUseStaticGraphEvaluation=true`

```
...\CpvmStaticGraphIssue\Project203\Project203.csproj : error NU1106: Unable to satisfy conflicting requests for 'System.Threading.Tasks': 
System.Threading.Tasks (>= 4.0.11) (via package/System.IO 4.1.0), 
System.Threading.Tasks (>= 4.0.11) (via package/System.IO 4.1.0) Framework: (.NETCoreApp,Version=v3.1) 
```

## Other suggested things

`dotnet restore --force /p:RestoreUseStaticGraphEvaluation=false` works fine.

### Sample Project

I've discovered the problem in larger solution, but I was able to reduce it to [CpvmStaticGraphIssue.zip](https://github.com/NuGet/Home/files/5607782/CpvmStaticGraphIssue.zip):
```
              -> Project142 -> log4net
             /
  Project203                -> Project157 -> log4net
             \             /
              -> Project160
                           \
                            -> FSharp.Core
```

`Directory.Packages.props`:
```
<Project>
  <ItemGroup>		
    <PackageVersion Include="FSharp.Core" Version="4.7.0" />
    <PackageVersion Include="log4net" Version="2.0.9" />
  </ItemGroup>
</Project>
```
`Directory.Build.props`:
```
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
```

**Comment by nkolev92** [comment]
I can repro this. Thanks for the detailed steps!

**Comment by Nirmal4G** [comment]
Really need this fixed!
