### ISSUE TITLE
CPVM seems not to take FrameworkReferences into account

### ISSUE THREAD

**Issue by MichaeIDietrich** [NuGet/Home#10331]
## Description

Projects that use central package version management can produce different DLLs in the output if there is a project that uses `PackageReference` for a specific dependency while another uses `FrameworkReference` indirectly for the same dependency.

## Steps to reproduce

1. Clone this repository: https://github.com/MichaeIDietrich/TestCpvmWithFrameworkReferences
   * One project references `Microsoft.Extensions.DependencyInjection.Abstractions` directly using the related NuGet package while the other project references this assembly indirectly by using ASP.NET Core FrameworkReference
2. Open cmd.exe in the repo root folder
3. Run `dotnet publish`

## Actual behavior

If you check the publish folder (_%Project name%\bin\Debug\netcoreapp3.1\win-x64\publish_) of both projects and inspect the details of `Microsoft.Extensions.DependencyInjection.Abstractions.dll`, you will see that the DLLs are different:

### For project _LibraryUsingServiceProvider_

```
InternalName:     Microsoft.Extensions.DependencyInjection.Abstractions.dll
OriginalFilename: Microsoft.Extensions.DependencyInjection.Abstractions.dll
FileVersion:      3.100.920.47302
FileDescription:  Microsoft.Extensions.DependencyInjection.Abstractions
Product:          Microsoft .NET Extensions
ProductVersion:   3.1.9+d8a50ea1cc9892cda13c5237dec402ca10ddeaa1
Size:             36.8 KB
```

### For project _WebProject_

```
InternalName:     Microsoft.Extensions.DependencyInjection.Abstractions.dll
OriginalFilename: Microsoft.Extensions.DependencyInjection.Abstractions.dll
FileVersion:      3.100.920.47302
FileDescription:  Microsoft.Extensions.DependencyInjection.Abstractions
Product:          Microsoft .NET Extensions
ProductVersion:   3.1.9+d8a50ea1cc9892cda13c5237dec402ca10ddeaa1
Size:             70.8 KB
```

_Both have different sizes!_

## Expected behavior

Resulting DLLs for projects that use central NuGet package version management are identical.

## Version info

dotnet SDK version: 5.0.100

Windows version: 20H2 (Build 19042.630)

## Details about the problem

The reason for this might be that the NuGet package uses a .NET Standard 2.0 variant while the ASP.NET Core Framework has a .NET Core 3.1 variant of this DLL.

Is there a way to resolve this mismatch? Currently we have problems with publishing, since we expect all projects to have identical DLLs when building the installer, since all files will end up in the same installation folder. We have found no real way to determine which DLL we should pick, since both have identical version information.

At the moment we work around this issue by adding the ASP.NET Core FrameworkReference as dependency to all top level projects, but I hope there is a better way to resolve this.

Can you please help us with this issue?

**Comment by nkolev92** [comment]
Hey @MichaeIDietrich 

Unfortunately I don't think NuGet is the best to help you here. 
FrameworkReferences are a different way of acquiring the assets. 

Can you please explain why you think CPVM is particularly relevant here? 
I'd expect the same experience with regular restore as well, this is more of a Package vs FrameworkReference thing.

**Comment by MichaeIDietrich** [comment]
Hi @nkolev92,

thank you for your response.

> Unfortunately I don't think NuGet is the best to help you here.
> FrameworkReferences are a different way of acquiring the assets.

If not NuGet is the best to help here, what else is the best, since both files contain identical meta data as far as I can see?
Both, `PackageReference` and `FrameworkReference` are restored using NuGet mechanism, so I would expect that NuGet has some precedence logic for the resulting DLLs.
_Or did you mean the NuGet repo is not the best here for asking for help?_

> Can you please explain why you think CPVM is particularly relevant here?
> I'd expect the same experience with regular restore as well, this is more of a Package vs FrameworkReference thing.

The more I think about it the more I think you are probably right, this seems to be a general resolving issue.

If I reference both in a single project, I get this result:

```
Encountered conflict between 'CopyLocal:C:\Users\dddiet\.nuget\packages\microsoft.aspnetcore.app.runtime.win-x64\3.1.9\runtimes\win-x64\lib\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll' and 'CopyLocal:C:\Users\dddiet\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.1.9\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Choosing 'CopyLocal:C:\Users\dddiet\.nuget\packages\microsoft.aspnetcore.app.runtime.win-x64\3.1.9\runtimes\win-x64\lib\netcoreapp3.1\Microsoft.Extensions.DependencyInjection.Abstractions.dll' arbitrarily as both items are copy-local and have equal file and assembly versions. (TaskId:124)
```

I'm surprised that randomly one DLL wins here, so my initial assumption was wrong that those are always resolved to the `FrameworkReference` DLL without CPVM.

Scanning the log more there seem to be targets that sound like they would be related to this problem: 
`CheckIfPackageReferenceShouldBeFrameworkReference`, `CheckForImplicitPackageReferenceOverrides`. 
Is this problem more related to the dotnet/sdk team? (If so, could you move it to the fitting repo?)

One thing that confuses me a lot here is, why are those DLLs different in size in the first place? Are the Framework DLLs compiled `Ready2Run` or why are here differences? (ILSpy says that they contain unmanaged code)

**Comment by nkolev92** [comment]
> If not NuGet is the best to help here, what else is the best, since both files contain identical meta data as far as I can see?

> Is this problem more related to the dotnet/sdk team? (If so, could you move it to the fitting repo?)

Yep, SDK is a better spot.
