### ISSUE TITLE
Comparer static properties should be idempotent 

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#10339]
We have a pattern for types that implement a comparer interface (e.g.:  `IEqualityComparer<T>`):  implement a static property that returns an instance of the comparer.  That way, comparisons do not require instantiating a new comparer.  Unfortunately, this pattern was incorrectly implemented.

These properties will return a new instance every time the property is accessed:

```C#
public static MyComparer Instance { get { return new MyComparer(); } }
public static MyComparer Instance { get => new MyComparer(); }
```

This will return the same instance every time the property is accessed:

```C#
public static MyComparer Instance { get; } = new MyComparer();
```

**Comment by erdembayar** [comment]
@dtivel 
Is this issue generic for all property type or only for comparer type?

**Comment by dtivel** [comment]
Just comparer types.

**Comment by erdembayar** [comment]
> Just comparer types.

Good to know next time. 👍
