### ISSUE TITLE
Remove call to api/v2/Packages() endpoint during restore

### ISSUE THREAD

**Issue by bhuvak** [NuGet/Home#1033]
During package restore, nuget.exe makes a call to api/v2/Packages(Id='xxx',version='yyy') and then fetches the package @ api/v2/Package/id/version.
The idea of the first call is to validate the existence of the package ( not sure though). 
We need to see if we can fix it for v2 client ( nuget.exe 2.8.x).

With 3.0 this is not the case and we are good here.

**Comment by yishaigalatzer** [comment]
We are not making more changes to nuget 2.x exe

**Comment by deepakaravindr** [comment]
We are making changes to nuget 2.x exe. So, there is nothing to verify here
