### ISSUE TITLE
NuGet Package Manager is not reporting installed packages in Visual Studio 2019

### ISSUE THREAD

**Issue by CLIRResearch** [NuGet/Home#10330]
I would normally report this through Visual Studio 2019.  However, when I try, the website says that there is no instance of Visual Studio that is signed in.  Visual Studio 2019 shows me as being signed in.

The following steps describe my issues with Visual Studio 2019 and NuGet Package Manager:

1.  Go to Tools | NuGet Package Manager | Manage NuGet Packages for Solution...
2.  Click the "Installed" link at the top of the "Manage Packages for Solution".
3.  Click the "EntityFramework by Microsoft" entry.
4.  Note that no projects in the solution show up in the list projects.

When I right-click the solution, and click the "Restore NuGet Packages", I get the response: "All packages are already installed and there is nothing to restore".

If I add a package to a project in the solution, the project entry in the "Manage Packages for Solution" that I added the package shows the correct package version.  The references are correctly shown.

A different project entry that I added the package to last week, shows a blank version.  The references for this project appear correctly.  

This is Visual Studio 2019 Version 16.8.1

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Hey @CLIRResearch 

Thank you for filling this issue. 
Unfortunately I'm not sure how I can repro this. Would you be able to provide a repro projects and some screenshots?

**Comment by aortiz-msft** [comment]
Hey @CLIRResearch

Are you still hitting the same issue? If you are, would you please provide information that would allow us to debug the problem?

Thanks!

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
