### ISSUE TITLE
nuget.exe 'list' command doesn't work for authorized feeds(?)

### ISSUE THREAD

**Issue by ericsampson** [NuGet/Home#10340]
## Details about Problem

NuGet.exe

5.8.0.6930

## Detailed repro steps so we can see the same problem

Right now I can successfully do 'nuget.exe search FOO' against authenticated feeds (GitHub Packages and Azure Artifacts), but trying the same thing using 'nuget.exe list' throws a warning and doesn't return results.

If I was able to have the same control of the search query in 'nuget search' that I can with 'nuget list' (see [here](https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax) ) then I would be OK, but I don't AFAICT.

Thanks!

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/2869.
