### ISSUE TITLE
msbuild restore doesn't import all packages

### ISSUE THREAD

**Issue by benvillalobos** [NuGet/Home#10347]
---
**Issue moved from dotnet/msbuild#5908**
- Please respond to @zdavidsen.

---

_From @zdavidsen on Tuesday, November 24, 2020 4:06:10 PM_

### Issue Description

(Posting on behalf of a coworker, since I'm the designated build script maintainer)

We have a common msbuild script/project that we use in a number of repositories which requires a couple of Nuget packages (an internal package and MSBuild Community Tasks).  Recently, one of my coworkers has started having problems with the project, where it will restore correctly but won't import MSBuild Community tasks (it does import the internal package).  The fun part is that the exact same project will build on any of our other machines and our build server; it only fails on coworker's machine.

Any ideas what could be causing this?

Here's a slightly stripped down copy of the common build script, and the generated .props and .targets files from both my machine and the coworker's.
[MSBuildFiles.zip](https://github.com/dotnet/msbuild/files/5591156/MSBuildFiles.zip)

**Comment by benvillalobos** [comment]
---
**Issue moved from dotnet/msbuild#5908**
- Please respond to @BenVillalobos.

---

_From @BenVillalobos on Wednesday, November 25, 2020 4:48:15 PM_

Team Triage:  Does the file `'$(NuGetPackageRoot)msbuildtasks\1.5.0.235\build\MSBuildTasks.targets`  exist on your coworkers machine?

Does this still happen if your coworker flushes their nuget cache? `nuget locals all -clear`. This will delete _all_ nuget packages on their machine and the restore will redownload them.

**Comment by benvillalobos** [comment]
---
**Issue moved from dotnet/msbuild#5908**
- Please respond to @zdavidsen.

---

_From @zdavidsen on Monday, November 30, 2020 4:34:09 PM_

Yes to both of those questions.  He tried clearing the nuget cache (probably through visual studio), and I know the package exists locally because manually importing the targets file allows the build to proceed.
(`<Import Project="$(PkgMSBuildTasks)\build\MSBuildTasks.targets" />`)

**Comment by benvillalobos** [comment]
---
**Issue moved from dotnet/msbuild#5908**
- Please respond to @BenVillalobos.

---

_From @BenVillalobos on Wednesday, December 2, 2020 4:52:17 PM_

Team Triage: When your coworker imports using `<Import Project="$(PkgMSBuildTasks)\build\MSBuildTasks.targets" />`, what does `PkgMSBuildTasks` expand to? Is it the same on your machine?

**Comment by benvillalobos** [comment]
---
**Issue moved from dotnet/msbuild#5908**
- Please respond to @zdavidsen.

---

_From @zdavidsen on Wednesday, December 2, 2020 5:17:07 PM_

It's expanding to the same path on both computers: `C:\Users\<user>\.nuget\packages\msbuildtasks\1.5.0.235`

**Comment by nkolev92** [comment]
Hey @zdavidsen, 

The files you have uploaded have a different version for one of the packages as well. So seems like restore is different altogether in this case. 

Any way you can provide us a repro? 
If you can't do that, I'd recommend looking at the `project.assets.json` and ensuring that it contains the package you expect to bring the props files. 

If it is there, it'd be helpful to provide us:
* The target framework
* The directory structure of the package in question.

**Comment by zdavidsen** [comment]
Thanks for the follow-up, I believe I have it all figured out now.  I hadn't noticed that the package was a different version, it appears that my coworker had updated the script to pull a more recent package version and I missed it.  That version upgrade switched from a standalone .nuspec to one generated from a .csproj, and in the process the build assets of our package's dependencies started being excluded (the default).  I've updated the csproj and everything seems to be working now.  Thanks for pointing out the package version difference!

**Comment by nkolev92** [comment]
I'm glad you managed to solve your problem :) 

Closing.
