### ISSUE TITLE
FatalProtocolException in PackageSearchResource when deployed to Azure 

### ISSUE THREAD

**Issue by geotinc** [NuGet/Home#10344]
Hello, I have the following problem :

NuGet product used NuGet.Protocol package version 5.8.0 :
![image](https://user-images.githubusercontent.com/20421571/100789444-bf662780-3416-11eb-9709-260342e1b3f5.png)

I have create an Asp.Net core 5 website that list nuget package from my private nuget serveur. It works great when running on my computer but when deployed to Azure, I have the following error

![image](https://user-images.githubusercontent.com/20421571/100789604-f9372e00-3416-11eb-8532-f8b39e0c6340.png)

![image](https://user-images.githubusercontent.com/20421571/100789222-731ae780-3416-11eb-97c5-212f71e97928.png)

Any tips for solving this issues ?

Thanks

**Comment by zkat** [comment]
This is not something we've seen before. I don't know what the best way forward is. Perhaps running in a higher verbosity and debugging the error will give you more clues? I don't understand what file is supposed to be missing here, and that CryptographicException is... much lower level than NuGet itself, which implies some kind of configuration issue? Can you dig into it further and get back to us?

**Comment by geotinc** [comment]
This week I change from Azure Artifact to ProGet, and there is no more authentication for connecting to repository.
No it's work correctly on Azure... Don't know if the problem is the Authentication or the connection with Azure Devops or both...

Thanks for helping

**Comment by zkat** [comment]
Alright. Thanks for filing the issue. I'll close this since this is not something we'll be able to continue looking into. Glad things are working now!
