### ISSUE TITLE
Dotnet add package doesn't record custom source feed was used during restore

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10345]
Hi.
While I was investigating [#5127](https://github.com/NuGet/Home/issues/5127) I realized when user use custom source feed during `add package` then that information[ is not recorded into both asset and dpSpec files](https://github.com/NuGet/Home/issues/5127#issuecomment-736676045). Maybe it could become source of confusion or security hole if we don't know where did this package came from during restore specially when use private feeds.

`>>dotnet add package Domain -s "..\Mypackages" --version 1.0.0`

![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/bc8e25c1-ed8c-41e8-a90d-952865d895ea)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6232.
