### ISSUE TITLE
Restore fails to include PackageReference from Directory.Build.targets on Linux

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#10348]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

dotnet.exe --version (if appropriate): 5.0.100

OS version (i.e. win10 v1607 (14393.321)): ubuntu-20.04

Worked before? If so, with which NuGet version: Works on Windows

## Detailed repro steps so we can see the same problem

1. Have a project with a nested Directory.Build.targets. I use this to bring in test specific packages, then recurse on up.

2. `dotnet restore`

3. Look at the `*.csproj.nuget.g.targets` and it's missing the packages from the nested Directory.Build.targets

This works on Windows, but fails on Linux. The manifest error is the build fails because it can't find the assemblies; after digging around, I found that the packages didn't even appear in the restore.

### Sample Project

Here's the project I saw this in: https://github.com/twsouthwick/wwt-website/tree/nuget-failure-linux-before. I fixed it on the branch `nuget-failure-linux-after` by moving the `<PackageReference>` nodes to a custom targets file.

To repro the error, open the before commit, and run `dotnet build wwt-website-net5.slnf` from Linux (or to see it succeed run it on Windows).

Here's the commit that shows the change to make it work: https://github.com/twsouthwick/wwt-website/commit/733b1df4593f02b1b23a5b58e028e6c146192e77

**Comment by nkolev92** [comment]
Hey @twsouthwick 

The problem is here: https://github.com/twsouthwick/wwt-website/blob/nuget-failure-linux-before/tests/Directory.Build.Targets. 

It should be `targets`, not `Targets`, equivalent to https://github.com/twsouthwick/wwt-website/blob/nuget-failure-linux-before/Directory.Build.targets.
