### ISSUE TITLE
VersionRange cannot parse single-digit ranges

### ISSUE THREAD

**Issue by jpobst** [NuGet/Home#10342]
It would be nice if `NuGet.Versioning.VersionRange.Parse` could parse a single digit (like `NugetVersion.Parse`  can):

```
var a = NuGetVersion.Parse ("1.0");
var b = NuGetVersion.Parse ("1");

Console.WriteLine (a == b);         // true

var c = VersionRange.Parse ("1.0");
var d = VersionRange.Parse ("1");   // System.ArgumentException: ''1' is not a valid version string.'
```

**Comment by nkolev92** [comment]
Bug here: https://github.com/NuGet/NuGet.Client/blob/20f57014932eadd13b4a69e05010fa56d71bdba4/src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs#L104-L117

Given the low impact, we're unlikely to get to this soon, but we'd consider taking a PR.

**Comment by louis-z** [comment]
Thanks to @nkolev92's hint, the fix seems straightforward. I can submit a PR if you want.
