### ISSUE TITLE
Dotnet pack command creates unwanted trash folders on Windows

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10346]
While investigating [issue#5127](https://github.com/NuGet/Home/issues/5127),  I ran `dotnet pack --include-symbols --output '../Nugets'` on my Windows machine. 
Expected bevahior is :
1. create `Nugets` folder on upper level 
2. Or simply fail due to bad formatted path.

Actual bevahior is: It creates a broken folder for windows without any error message. It seems this command format is for MAC/Linux but nothing prevents it from running on Windows and create unwanted trash folder. Since name is not normal ASCII keys we can't easily delete it. I feel this one is polluting production or work environment, so we need to prevent it happening. It shouldn't  create this one or simply fail stating specified path is not valid.

![image](https://user-images.githubusercontent.com/8766776/100803581-4055fc80-33e0-11eb-9078-21ff017f4418.png)

![image](https://user-images.githubusercontent.com/8766776/100678480-1f2ed680-3322-11eb-9033-600a149503ea.png)
![image](https://user-images.githubusercontent.com/8766776/100678531-3e2d6880-3322-11eb-9045-a54887096e46.png)

**Comment by nkolev92** [comment]
I'm not sure it's a NuGet/dotnet problem, it might be shell. 

In particular, I ran the command you provided in powershell and it worked just fine: 

```
C:\Users\Roki2\Source\Repos\10331\10346> dotnet pack --include-symbols --output '../Nugets'
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  10346 -> C:\Users\Roki2\Source\Repos\10331\10346\bin\Debug\net5.0\10346.dll
  Successfully created package 'C:\Users\Roki2\Source\Repos\10331\Nugets\10346.1.0.0.nupkg'.
  Successfully created package 'C:\Users\Roki2\Source\Repos\10331\Nugets\10346.1.0.0.symbols.nupkg'.
```

If the file system accepted it, then I don't NuGet should be concerned with this.
