### ISSUE TITLE
Is there a way to specify NuGet to save the packages in anoter location?

### ISSUE THREAD

**Issue by justin-jalandoni** [NuGet/Home#10359]
In maven, we can specify to save the JARs to a different folder, when we specify it is the `settings.xml` file is there an equivalent in NuGet? I've seen solutions where we need to specify it in a solution. Is there a way to configure this globally?

**Comment by kartheekp-ms** [comment]
Please refer to [How to manage the global packages, cache, temp folders in NuGet](https://docs.microsoft.com/en-us/nuget/Consume-Packages/managing-the-global-packages-and-cache-folders) to learn more about `Managing the global packages, cache, and temp folders`. Hope this helps.
