### ISSUE TITLE
VS Solution manager throws null exception for during debugging

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10352]
I recently noticed there is null exception kept throwing when try to open PMUI/PMC. 
It looks due to recent effort to move from synchronous code to async ones causing this timing issue. It doesn't guarantee `init` is done before code start is using supposedly already initialized things.
Also jebriede [reported it](https://teams.microsoft.com/l/message/19:00d019d741b44e54baadd67ef7aeb41d@thread.skype/1606247461775?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=ad34ac55-6785-4e7c-82c3-7ba405d30c3c&parentMessageId=1606247461775&teamName=NuGet&channelName=Client&createdTime=1606247461775) same problem recently.

![image](https://user-images.githubusercontent.com/8766776/100144755-1898ee80-2e4c-11eb-9fba-c4e64fe331ab.png)

**Comment by zkat** [comment]
@erdembayar can you check if this is actually a regression?
