### ISSUE TITLE
PrivateAssets not considered for ProjectReference node

### ISSUE THREAD

**Issue by gnimor** [NuGet/Home#10366]
I have an "old style" .NET framework project which is used to create a Nuget package. The project itself is using other NuGet packages and project references. For the used NuGet packages the PackageReference format is used. In order to use the msbuild "pack" target a reference to the "NuGet.Build.Tasks.Pack" package was added.

Problem: The package will be created but the project to project references will be treated as Nuget References. Even after adding the "PrivateAssets=all" to the project reference node, they are still handled as NuGet references instead of packaging/including the project references to the package.

**Comment by kartheekp-ms** [comment]
I just created a sample `.NET Framework` project and followed instructions in [doc](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets). I don't see `ProjectReferences` added as dependencies in the nuget package that was generated using `msbuild -t:pack` command.

In the attached project `ClassLibray` has a project dependency to `ProjectDependency` project with `<PrivateAssets>All</PrivateAssets>`. `ClassLibrary` was packed using `msbuild -t:pack` command and the generated `nuget package` does not have any project dependency. Please let me know if I should do anything different to reproduce the behavior you are experiencing.

[NuGetMsBuildPack.zip](https://github.com/NuGet/Home/files/5661592/NuGetMsBuildPack.zip)

**Comment by gnimor** [comment]
@kartheekp-ms Thanks for your update, I checked your project and it seems to work as expected. Therefore I cleaned-up my complete solution and projects (after migrating to PackageReference). Now I can see that with "PrivateAssets" to "all" for the referenced project, the project dependency is gone too, but I want the referenced project to be contained in the package which is not the case. So based on the documentation my expectation would be that the project dependency is gone, but the referenced project is contained in the package - and that is not the case?

**Comment by kartheekp-ms** [comment]
I am having tough time in understanding your question in the above comment. But as per the [doc](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#project-to-project-references), `Project to project references are considered by default as nuget package references` and what is included in the package can be managed by specifying `<IncludeAssets><ExcludeAssets><PrivateAssets>` metadata. Please provide us repro steps if you are experiencing another issue.

**Comment by gnimor** [comment]
OK, perhaps my question was not so clear : -) In my case I want to have the output of the project reference included in the package, therefore the first step would be to avoid the nuget package reference (which seems to work with the `<PrivateAssets>all</PrivateAssets>`). So regarding your sample I am looking for a way to include the ProjectDependency in the ClassLibrary package:

```
    <ProjectReference Include="..\ProjectDependency\ProjectDependency.csproj">
      <Project>{59bf009f-714d-4dea-9e95-569551ae5236}</Project>
      <Name>ProjectDependency</Name>
      <!-- <PrivateAssets>all</PrivateAssets> -->
      <IncludeAssets>?????</IncludeAssets>
    </ProjectReference> 
```

**Comment by kartheekp-ms** [comment]
AFAIK a NuGet package can have a dependency on another NuGet Package but not on another Project. Please refer to https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element to learn more about dependencies.

`msbuild -t:pack` by default includes Project dependency as Package dependency. https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#project-to-project-references
