### ISSUE TITLE
SimpleTestPackageUtility.CreateFolderFeedV3Async doesn't create nupkg file in same location as other OS

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10361]
I saw Linux unit test failing because nupkg file created by `SimpleTestPackageUtility.CreateFolderFeedV3Async()` is not same as other OS.
Other OS it's always located in `PackageName>>Version>>PackageNameVersion.nupkg`
MAC:
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/6f32a44b-b20f-4b08-a74a-7d6caf6551f6)
Windows:
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/2f49d445-81cc-4835-9c01-7b7459b8e1da)

I can't test exactly where is nupkg on Linux because I don't have Linux env now.

**Comment by nkolev92** [comment]
I removed the `Type:Bug` so it's not included in the release notes.

**Comment by nkolev92** [comment]
The simplest way to figure out what's going is to either do a DTL machine or use `printf` debugging, but printing the the directory structure on linux. 

If this is really a problem, it's possible we have some bad coverage.

**Comment by erdembayar** [comment]
@nkolev92 
Sorry my mistake, it happened due to Linux being cases sensitive. Actual created package name is all lower case but my original package name had capital `X` which caused this confusion. 

`/home/eryondon/NugetProj/NuGet.Client/.test/work/449b44d2/5315ce10/MySource/packageX/1.0.0/packageX.1.0.0.nupkg`

![image](https://user-images.githubusercontent.com/8766776/109048189-a377c800-768b-11eb-8bfc-8b103d38f56f.png)

I'll be cautious next time, so I'm closing now.
