### ISSUE TITLE
Remove specific package from cache

### ISSUE THREAD

**Issue by juanan** [NuGet/Home#10377]
Hi,

I know that we can remove from cache all packages or packages by local resource: http-cache, global-packages, temp, plugins-cache.

The question is how can I remove only one specific package from the cache, I don't see the option.

I am using right now nuget 5.4.0.6315.

Thanks a lot.

**Comment by donnie-msft** [comment]
There's no way I know of to use nuget to specify a specific package to remove from cache. You'd need to do that manually after finding whichever cache folder, then removing the file in that folder.

Note that you can also instruct `restore` to use `-NoCache` when restoring a specific package to always ignore cache for a specific package: https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore#options

**Comment by donnie-msft** [comment]
Here's a feature request to add this functionality: https://github.com/NuGet/Home/issues/5713

**Comment by juanan** [comment]
ok, many thanks for your help @donnie-msft

**Comment by gioce90** [comment]
I asked something which somehow relates to this one https://github.com/NuGet/Home/issues/13918 

Well, that's something that would benefit from the feature discussed here. Currently I use a Directory.Build.props where a RemoveDir task removes a package from the global packages folder.

**Comment by gioce90** [comment]
Hi @juanan , as I mentioned earlier, I created a solution to address these problems.
I’ve now decided to make my solution public by releasing a package called NuJet (https://github.com/gioce90/NuJet). It simplifies the development and testing process for NuGet packages, especially in local workflows.

Feel free to check it out—I’d love to hear your feedback!
