### ISSUE TITLE
The description of “Deprecated” disappears after clicking a deprecated package in Browse tab

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10379]
## Details about Problem
VS Version: D16.9\30808.132
NuGet Version: dev-feature-OE.PMUI\5.9.0.13982
OS Version: Windows-10-Enterprise-19H2.
## Installation:
1. Install VS D16.9\30808.132: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4288690&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Client: \\\ddfiles\drops\NuGet\Drops\CI-Private\NuGet.Client\dev-feature-OE.PMUI\5.9.0.13982

## Detailed repro steps 
1. Create a C# Class Library (.Net Framework) project.
2. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json
3. Open PM UI, select the above deprecated package source and search package “afine” in Browse tab.

## Expected
The description of “Deprecated” should show after clicking package “afine” in Browse tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/102194834-bab27080-3ef8-11eb-809c-41c043facad1.png)
## Actual
The description of “Deprecated” disappears after clicking package “afine” in Browse tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/102194886-cc941380-3ef8-11eb-8e1c-5a65e78a4e68.png)
Notes:
1. The issue also reproes on C# Console App (.Net Core) project.
2. The issue does not repro on NuGet Client Dev Branch.

**Comment by donnie-msft** [comment]
@sbanni any chance dev works because you already fixed this?

**Comment by donnie-msft** [comment]
@sbanni any chance dev works because you already fixed this?

**Comment by v-longmin** [comment]
Verify the issue on Main\30912.243 + NuGet Client Dev\5.9.0.7028, it has been fixed, close it, thanks.
