### ISSUE TITLE
Proposal: option to hide dependency APIs if consumers don't reference them too

### ISSUE THREAD

**Issue by Sergio0694** [NuGet/Home#10375]
## Overview

There are cases where library authors need to add a dependency on NuGet packages, but without having consumers of their library (and not the dependency as well) to automatically have access to those APIs **unless explicitly referenced**.

The main idea is: some dependency should only be viewed as **implementation details** for a library.
This is due to a number of reasons:

1. These APIs might not conceptually make sense to be exposed together with a library. As an example, I'm working on [ComputeSharp](https://github.com/Sergio0694/ComputeSharp), which is a high-level, easy to use library to do GPU processing in C#. This library has a dependency on [TerraFX.Interop.Windows](https://github.com/terrafx/terrafx.interop.windows), which provides extremely low-level bindings for Windows APIs. I don't want consumers of my library to also have TerraFX APIs pop up in their IntelliSense. These APIs are just an implementation detail for me, and conceptually they have nothing to do with what ComputeSharp aims to be - a high-level and accessible library.
2. Having these APIs being exposed caused a potentially breaking dependency for consumers. Consider the case for ComputeSharp as before. If one day I wanted to change my backend for whatever reasons, and some consumers were using APIs from TerraFX as well, updating ComputeSharp would be a breaking change, even if I'd only be changing an internal implementation detail, and nothing on my public API surface.

Point 1. is the one I care about in particular. That's the same reason why me and many other library authors take special care in trimming the public API surface as much as possible to keep it clean - having every single indirect API being automatically visible to consumers completely undermines this, especially when these APIs are very different from the design of the library itself.

## Proposed solution

This proposal is to add a new property that can be added to `PackageReference` items (eg. `PubliclyVisible`, defaulting to `true` for backwards compatibility) that when set to `false` would cause the following behavior:

- APIs from these dependencies would not be visible for consumers. As in, trying to use them would fail to build.
- Consumers would need to manually add a dependency to that package in their own project to see/use them.
- These dependencies would still be visible when installing the NuGet package, as is today.

To add more details (quoting from @tannergooding):

> What is wanted is that PackageB depends on PackageA so that the latter is included in the overall version matching, it ends up in the exe output folder, etc.
> However, PackageA should not be passed through to csc and therefore users shouldn't be able to use types from it without directly referencing it themselves.
> Likewise, consumers of B shouldn't need to set any private assets to make this work as intended.

## Alternative solutions (not viable)

- Ask maintainers of these dependencies to provide source-only packages as well. This is clearly not viable in the majority of cases, and would be bad for code size anyway since consumers would end up with duplicated code across different assemblies.
- Keep a local fork of needed packages and use them as private assets. This is not viable either as it would require a lot of work for library authors to keep forks in sync, not to mention this would have the same exact issue with duplicated code.

**Comment by michael-hawker** [comment]
Yeah, this can help library authors (and app developers) as well understand explicitly which packages they depend on.

In the [Windows Community Toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit) we just did an exercise for our upcoming release to understand our full dependency tree.

Since our APIs are layered to build on top of one another, it's easy for them to get included everywhere. But in one of our main packages 'Controls', we basically just had a reference to another package 'Animations', which was then pulling in all the other dependencies (and the kitchen sink). It made it very hard to know at a glance what was really required by the `Controls` package as a dependency.

If we had defaulted to having the internals visible up the chain of our dependencies, it'd make it a lot easier to understand this. Also, consumers would have to explicitly ask for things outside of the package, so they know where their APIs are coming from which makes it easier for future contributors to know where to look for things too.

**Comment by yair100** [comment]
We recently had an issue where our app stopped working after updating a Nuget package that we had been using for a couple of years with no problems. It turned out that the library removed a dependency and it caused us to look all over before we found what we needed to add to our project. Implementing this proposal will make sure that we download the proper Nuget packages in the first place and will prevent these kinds of issues from happening again.

**Comment by sharwell** [comment]
I was directed to this issue by another discussion. We're [currently using `PrivateAssets="compile"`](https://github.com/dotnet/roslyn-sdk/blob/b7df823f6a23d8fb316c8ee2c25237df7c151123/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Microsoft.CodeAnalysis.Analyzer.Testing.csproj#L56-L63) for this purpose, and have not seen any specific difference between the feature requested above and the behavior observed by consumers of this package. Can someone give some examples of specific scenarios where this does not work today?

**Comment by EgorBo** [comment]
In JAVA world it's called "Class Shadowing" https://softwareengineering.stackexchange.com/questions/297276/what-is-a-shaded-java-dependency and https://medium.com/@akhaku/java-class-shadowing-and-shading-9439b0eacb13

Quite a useful feature

**Comment by davidfowl** [comment]
cc @mhutch

**Comment by rickbrew** [comment]
This looks like it's going to affect Paint.NET as well. I just had someone send me a plugin they're working on, and in both their `.deps.json` and their `bin` folder it was pulling in all sorts of DLLs that my app is referencing but their plugin is not: `CommunityToolkit.HighPerformance.dll`, `Crc32.NET.dll`, `Interop.WIA.dll` (wtf), and `Newtonsoft.Json.dll`.

If I add / remove / update / link / trim, this seems like it's going to break all sorts of plugins if they start shipping with their .deps.json files.

**Comment by stijnherreman** [comment]
@sharwell I'm also wondering what the difference is, especially with https://github.com/dotnet/sdk/issues/26286 being pushed.

**Comment by zivkan** [comment]
Does the existing NuGet feature `PrivateAssets="compile"` already cover this request?

https://github.com/dotnet/roslyn-sdk/blob/df51b014fcb8c9e667a0b09a000f2050615f7afb/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/Microsoft.CodeAnalysis.Analyzer.Testing.csproj?q=PrivateAssets%3D%22compile%22#L58-L65

**Comment by michael-hawker** [comment]
> Does the existing NuGet feature `PrivateAssets="compile"` already cover this request?

@zivkan are those build time only dependencies or are they used at runtime as well? (As I would expect that would be the crux of this request over `PrivateAssets` in general.) If this already exists, then it's not well documented as [a scenario in the docs](https://docs.microsoft.com/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) which just talks about misc folder names, but not the practical application/outcomes/use-cases.

**Comment by zivkan** [comment]
Copying my comment from https://github.com/dotnet/sdk/issues/26286#issuecomment-1185729410

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

My summary for only the relevant parts:

metadata|in current project|flow via PackageReference
---|---|---
IncludeAssets| ✔️ | ✔️ 
PrivateAssets|  ✔️ | ❌ 
ExcludeAssets| ❌ | ❌ 

Asset type|description
--|--
compile|`lib/<tfm>/*.dll` or `ref/<tfm>/*.dll` passed to compiler
runtime|`lib/<tfm>/*dll` or `runtimes/<it's complicated>/*.dll` copied to `bin`
(others)|not relevant to this discussion, just want to make it clear this is not a complete list

Therefore:

scenario|what to use
--|--
Prevent NuGet assets being copied into bin folder|`ExcludeAssets="all"` or `ExcludeAssets="runtime"` if you want to keep non-dll assets, and exclude only the dlls
Don't allow consumers of my package to use my dependencies, unless they directly reference those packages themselves|`PrivateAssets="compile"`

I just remembered that I documented this a while ago: https://docs.microsoft.com/en-us/nuget/create-packages/select-assemblies-referenced-by-projects#recommended-one-assembly-per-package

**Comment by nkolev92** [comment]
As covered in zivkan's comment, the ask in this issue is something that's already doable with the current NuGet tooling. 

Does anyone see any scenario where that doesn't work?

**Comment by Sergio0694** [comment]
> "Does anyone see any scenario where that doesn't work?"

I just stumbled upon a scenario where `PrivateAssets="compile"` doesn't work, specifically it seems to leak an internal implementation detail of a public type into consuming assemblies, forcing them to add a NuGet reference they don't need.

Consider this scenario:

**Project A:**
```xml
<ItemGroup>
    <PackageReference Include="TerraFX.Interop.D3D12MemoryAllocator" Version="2.0.0-beta3" PrivateAssets="compile" />
</ItemGroup>
```
```csharp
using TerraFX.Interop.Windows;

public struct ResourceDescriptor
{
    private D3D12_DESCRIPTOR_RANGE_TYPE RangeType;
}
```

**Project B, referencing A:**
```csharp
Span<ResourceDescriptor> span = stackalloc ResourceDescriptor[1];
```

This results in the following errors:
> error CS0012: The type 'D3D12_DESCRIPTOR_RANGE_TYPE' is defined in an assembly that is not referenced. You must add a reference to assembly 'TerraFX.Interop.Windows, Version=10.0.20348.0, Culture=neutral, PublicKeyToken=35b01b53313a6f7e'.
> error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('ResourceDescriptor')

Roslyn needs to be able to see the internal layout of the type to determine whether it's unmanaged (which is required to use the type with `stackalloc`), but it seems that information isn't available with `PrivateAssets="compile"` for some reason. Not sure if this is by design, in which case then `PrivateAssets="compile"` is not a full solution to this issue, or a bug we should report on Roslyn? @sharwell would you know whether this scenario is supposed to work already with `PrivateAssets="compile"`? 🤔

@nkolev92 In general, I would expect that for a feature like this, devs would get help from tooling to enforce that the NuGet packages that they're marking as private don't leak from the public API of their projects. That is, issues like these should never happen, and if one was to leak an API publicly, that should cause a build error with a helpful message. That said, this specific case I mentioned seems more like a bug, given the API from that NuGet package is not publicly exposed.

**Comment by KalleOlaviNiemitalo** [comment]
@Sergio0694, I think this restriction could be removed with a Roslyn change:
- Define IsUnmanagedAttribute applicable to struct types
- Add IsUnmanagedAttribute to struct ResourceDescriptor in project A
- Make Roslyn recognise IsUnmanagedAttribute when it compiles project A, and report an error if ResourceDescriptor is not unmanaged
- Make Roslyn recognise IsUnmanagedAttribute when it compiles project B, and trust that ResourceDescriptor is unmanaged, without needing the definitions of the types of the instance fields

**Comment by sylveon** [comment]
This seems like a workaround for one specific issue, instead of the overall problem. For example, I believe it would not work when trying to use `sizeof`.

It would also probably lead to turning some currently compile-time errors into runtime issues (e.g. a type has IsUnmanagedAttribute but isn't actually unmanaged. Currently Roslyn would fail compiling but with this idea it would only show up as an error at runtime).

**Comment by tannergooding** [comment]
Changing the Compiler/Language, especially for an existing feature, is typically the least viable option.

In this case, it would be a breaking change, would not work with the 20+ years of existing assemblies that define struct types, would lead to fairly massive metadata bloat, etc.

**Comment by KalleOlaviNiemitalo** [comment]
> would lead to fairly massive metadata bloat

No, the attribute would only be required in those unmanaged types that have private dependencies.

**Comment by tannergooding** [comment]
In the scheme of things, that is most interop types. Everything except for the IL primitives is a "user-defined type" and the language generally does not make assumptions about their shape or layout.

That means anything using `Guid`, `Half`, `CLong`, `Int128`, `UInt128`, `Vector*` types, custom fixed sized buffers, 3rd party interop binding libraries, etc all have the possibility of a dependency which is "private".

This is not really a language issue and extends beyond just C# as you must also consider other languages with extensive interop support like F#, C++/CLI, or one of the many non-Microsoft created languages that target .NET. 

I think this is really a tooling/packaging issue and falls into the same category as several of the other areas where NuGet and/or the SDK is "missing" a piece of infra needed by more complex projects. Native dependencies are another area where going off the golden path can be a bit painful.

**Comment by Sergio0694** [comment]
Completely agree with Tanner here. Also wanted to add that my point was not to call out a specific issue to say "we need to fix this to get the feature", but rather just identifying at least _some issue_ to confirm whether or not `PrivateAssets="compile"` was in fact already sufficient to support private dependencies, which as we saw it isn't. So that was mostly just me answering @nkolev92's question there. With that settled, then this is something that'd require planning/tooling to address the overall issue 🙂

**Comment by KalleOlaviNiemitalo** [comment]
I meant the compiler would never generate an IsUnmanagedAttribute. Rather, the developer of project A would know that project A references TerraFX.Interop.D3D12MemoryAllocator as a private dependency and that the unmanagedness of the ResourceDescriptor type depends on that reference, and the developer would then add the attribute to the source code. UInt128 is in the System.Runtime reference assembly; developers are unlikely to reference that as a private dependency and so would not add such an attribute to a type just because it has a UInt128 field.

**Comment by nkolev92** [comment]
@Sergio0694 

I don't think your scenario is equivalent. 
You are referring to a package that *already* exposes other types in it's public APIs. There's no feature that can fix that.

**Comment by Sergio0694** [comment]
> "You are referring to a package that already exposes other types in it's public APIs"

I'm confused... What would be the point of referencing a package with no public APIs...? 🤔
I don't think I've ever seen any such packages in the first place?

The whole point of this proposal was to let authors of packages reference other NuGet packages _whose public APIs they wanted to use internally in their own packages_, without these packages also showing up in consumers of their packages. That is, if I write package A and want to use type `Foo` from library B, I don't want devs referencing my library A to also see `Foo` and all other types and namespaces being available to them _unless they explicitly reference B_.

This is also the same issue that made is so hard for us to untangle our dependencies in the Windows Community Toolkit.

For this feature, I'd expect that:
- The scenario mentioned above was supported
- Roslyn/tooling would be able to properly handle cases such as the one I mentioned here (https://github.com/NuGet/Home/issues/10375#issuecomment-1221292721)
- Roslyn/tooling would give you build errors to prevent you from exposing public APIs referencing any types from your private dependencies (as in, if you declare them as private, then tooling should help you enforce that they're actually private).

**Comment by nkolev92** [comment]
> I'm confused... What would be the point of referencing a package with no public APIs...? 🤔

I'm referring to the package exposing public APIs that are not declared in their own assembly. That's already happened. You can't change a package that already exists. 

> The whole point of this proposal was to let authors of packages reference other NuGet packages whose public APIs they wanted to use internally in their own packages, without these packages also showing up in consumers of their packages

Say you own your own package. When you reference your dependencies, add `compile` to PrivateAssets. Then it's on you to ensure you don't expose any public APIs (at this time). 

I understand that your ask is that the compiler can enforce this as well(maybe we need to open a dedicated issue for that in SDK/roslyn as it'll be a multi component feature,, but for the time being, you are able to do that on your own if you audit your package public API.

**Comment by Sergio0694** [comment]
Ah, I see what you mean. Sure, yeah just having to manually check things on your own would be fine at first, though it seems pretty error prone and something tooling should definitely be helping with. But also, I think the scenario I mentioned earlier should also be supported in this same bucket, which it isn't today. If a type from another assembly is a private member of a public API, that should not cause a build error for consumers. That's also especially tricky for library authors to verify, because at least at first glance, you are not in fact leaking any APIs, it's just that Roslyn needs to inspect internal members eg. in struct types to validate things, and that's falling apart in this scenario. That seems like a relatively easy to hit issue here.

**Comment by nkolev92** [comment]
For all of those concerns, I think it's probably best to file an equivalent issue on Roslyn side. 
NuGet never really looks at the assemblies themselves, so we can't really comment on the feasibility of those ideas. 

From a package authoring perspective, I think that the package metadata supports the scenario.

**Comment by KalleOlaviNiemitalo** [comment]
If .NET SDK passed the private dependencies of project A to the C# compiler when building project B, but also assigned random extern aliases to them in order to prevent project B from using them directly, then would the C# compiler then be able to use those references to check whether the types in project A are unmanaged? (Randomness might interfere with reproducible builds, though.)

**Comment by nkolev92** [comment]
Team Triage: 

As per the above, we believe that the package metadata, PrivateAssets, ExcludeAssets and IncludeAssets already cover the OP scenario. 
https://github.com/NuGet/Home/issues/10375#issuecomment-1185742257

We don't believe there's anything to be done from NuGet side.

**Comment by Sergio0694** [comment]
@nkolev92 I'm... Quite confused.

The thread so far clearly shows an example of a scenario where the current experience is just broken and causes runtime exceptions that are very hard to avoid, and with no tooling support whatsoever. How can this be by design? This is... Not the best developer experience, nor the best consumer experience if you're the one crashing at runtime 🥲

Did you specifically just mean on the NuGet side as in "other tooling might still need work to support this better"?
If so, we should link the tracking issues there here as well for future reference, if there's any already 🙂

**Comment by nkolev92** [comment]
@Sergio0694 

I'd encourage creating issues with details about things that don't work in the roslyn repo. Any redirecting will be handled there.
