### ISSUE TITLE
No-op restore does not work across dotnet.exe and Visual Studio when there is an "sdk" entry in global.json

### ISSUE THREAD

**Issue by caghand** [NuGet/Home#10373]
## Details about Problem

NuGet product used: dotnet.exe and VS UI

NuGet version: 5.8.0.6930

dotnet.exe --version: 3.1.404

VS version: 16.8.3

OS version: win10 v20H2 (19042.630)

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Create a new .NET Core Class Library project in Visual Studio 2019.

2. Add a NuGet package to the project.

3. Save and close the solution.

4. Next to the ".sln" file, add a global.json file with the following content:
```json
{
  "sdk": {
    "version": "3.1.404"
  }
}
```

5. Run `dotnet restore` on the ".sln" file.  If you run it several times, you will see that no-op restore works perfectly.

6. Open the solution in Visual Studio 2019.

7. Run `dotnet restore` on the ".sln" file again.  You will see that no-op restore does not work.

**Comment by caghand** [comment]
Tagging @nkolev92 as the no-op restore expert. :)

**Comment by kartheekp-ms** [comment]
I can reproduce this issue by following the repro steps mentioned in the description.

**Comment by nkolev92** [comment]
Unfortunately this is expected and I'm not sure we can promise fixing the behavior at this point. It is a known technical limitation.

NuGet restore ships as tooling in VS/MSBuild, SDK and NuGet.exe. Taking all the versions that shipped at the same time (16.8, 5.8 & 5.0.100), it is expected that restore no-ops. 

Note that specifying the global.json affects how the build runs, but not restore, restore is VS owned. 

It's not uncommon for different versions of the tooling to cross no-op, sometimes nothing of importance to the build changes, so the same hashes are generated. 

In 16.8/5.8/5.0.100, we had to make some larger changes to support scenarios such as `net5.0-windows`. That breaks the cross-noop between different versions.

It's a complex scenario, and I wish we could promise different behavior, but it's not possible right now. 

What I do have for you is a workaround. 

Running `msbuild /t:restore` should no-op when loaded in VS, even *with* the global.json

**Comment by caghand** [comment]
I understand.  Thanks for the explanation!
Actually, I've noticed that I don't need an "sdk" restriction in my project.  Newer SDKs are backward-compatible with older project types.  So I'll be able to get rid of the "sdk" entry in global.json, and I won't encounter this issue. :)
