### ISSUE TITLE
NuGet.exe restore intermittently interprets content package folders as target framework versions

### ISSUE THREAD

**Issue by ImAMightyPirate** [NuGet/Home#10370]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.7.0.6726

OS version (i.e. win10 v1607 (14393.321)): Windows 10 v1709 (16299.1868)

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. We have a privately hosted NuGet package generated using the following nuspec:-

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="3.3.0">
    ...
    <contentFiles>
      <files include="**" buildAction="None" copyToOutput="false" />
    </contentFiles>
  </metadata>
  <files>
       <file src="_Build\**\*.*" exclude="**\*.pdb;_Build\None\**\*.*;_Build\CustomActions\**\*.*;_Build\UnitTestUtils\**\*.*" target="contentFiles\any\any\CoreBuild" />
  </files>
</package>
```

2. The generated NuGet package has the following folder structure:-

* contentFiles\any\any\CoreBuild\Contracts
* contentFiles\any\any\CoreBuild\Controllers
* contentFiles\any\any\CoreBuild\Dependencies
* contentFiles\any\any\CoreBuild\Modules
* contentFiles\any\any\CoreBuild\Plugins
* contentFiles\any\any\CoreBuild\Resources

3. A NuGet.exe restore performed against our solution using NuGet.exe as part of a job on our build server:-

nuget.exe restore \<Solution Name\>.sln -verbosity detailed

4. The NuGet restore intermittently fails during the job with the following error NU1202:-

00:25:32  NU1202: <Package Name> is not compatible with net472 (.NETFramework,Version=v4.7.2). Package <Package Name> supports:
00:25:32    - contracts (Contracts,Version=v0.0)
00:25:32    - controllers (Controllers,Version=v0.0)
00:25:32    - dependencies (Dependencies,Version=v0.0)
00:25:32    - modules (Modules,Version=v0.0)
00:25:32    - plugins (Plugins,Version=v0.0)
00:25:32    - resources (Resources,Version=v0.0)

5. When the NU1202 error occurs the cached copy of the NuGet package in the C:\Users\\<Username\>\\.nuget\packages\\<PackageName\>\\<Version\>\ has the following folder structure:-

* lib\Contracts
* lib\Controllers
* lib\Dependencies
* lib\Modules
* lib\Plugins
* lib\Resources

6. We then delete the cached copy from C:\Users\\<Username\>\\.nuget\packages\\<PackageName\>\\<Version\>\

7. We then re-run the same build server job as previously executed that runs the  'nuget.exe restore "\<Solution Name\>.sln" -verbosity detailed' command.

8. No error occurs this time, the cached copy of the NuGet package in the C:\Users\\<Username>\.nuget\packages\\<PackageName\>\\<Version\>\ has the following folder structure:-

* contentFiles\any\any\CoreBuild\Contracts
* contentFiles\any\any\CoreBuild\Controllers
* contentFiles\any\any\CoreBuild\Dependencies
* contentFiles\any\any\CoreBuild\Modules
* contentFiles\any\any\CoreBuild\Plugins
* contentFiles\any\any\CoreBuild\Resources

**Note: The NU1202 error only occurs intermittently, in some instances the first restore of the package is unpacked correctly to the cached folder.**

**Comment by kartheekp-ms** [comment]
Thank you for filing this issue. The `nuspec` mentioned in the above comment has `target` attributes in `file` element set to `contentFiles\*` which contradicts with the guidance mentioned in the [doc](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-files-element-for-content-files). Please generate the nuget packge after updating the `nuspec` as per the doc and let us know if that fixes your issue. If it does, we can improve the error message in the `pack` command to avoid error during restore.

**Comment by ImAMightyPirate** [comment]
Hi @kartheekp-ms, we have now updated our nuspec file to the following:-

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="3.3.0">
    ...
    <contentFiles>
      <files include="**" buildAction="None" copyToOutput="false" />
    </contentFiles>
  </metadata>
  <files>
       <file src="_Build\**\*.*" exclude="**\*.pdb;_Build\None\**\*.*;_Build\CustomActions\**\*.*;_Build\UnitTestUtils\**\*.*" target="content\CoreBuild" />
  </files>
</package>
```

We are still seeing the same issue occur intermittently on restore with this change.

**Comment by aortiz-msft** [comment]
Is there a possibility that a package with the lib\* folder structure is being installed on the host intermittently for testing purposes or by a second private NuGet feed? That's our only guess of why the folder structure is different sometimes after clearing the cache and doing a restore.

**Comment by ImAMightyPirate** [comment]
We only have one source for our NuGet packages (a ProGet server) that is automatically populated using a CI build, so I don't think that it is possible for us to have different versions of the same package being restored with different structures.

**Comment by nkolev92** [comment]
@ImAMightyPirate The client doesn't do selective extraction, so not sure how this could happen. 

Is this package generated at an earlier stage of the build?

**Comment by ImAMightyPirate** [comment]
@nkolev92, our process is as follows:-

* We have one nightly CI build that generates the NuGet package and publishes it to the feed hosted by ProGet (steps 1 and 2 above, this is the only source for packages in the NuGet feed)
* We have other nightly CI builds that attempt to restore the latest package published from the NuGet feed (steps 3-5 above)

Step 6 onwards is our manual workaround.

**Comment by nkolev92** [comment]
@ImAMightyPirate 

Any chance you can simplify this down to a repro where you are using a local feed instead of proget?
That'll help us make some progress.

**Comment by ImAMightyPirate** [comment]
@nkolev92 I will see if we can get an alternate feed that does not rely on ProGet set up and report back. 👍

**Comment by ImAMightyPirate** [comment]
OK, so I've now set up the following scenario:-

* Our nightly CI build is now pushing to two feeds - the original one hosted by ProGet and to a shared folder on the network (the local feed)
* I've created a cut-down version of the CI build that restores this package, it runs the following:-

nuget.exe restore \<Solution Name\>.sln  -source \<Path to Local Feed\> -verbosity detailed

(if I have understood correctly -source should take precedence over any sources in the usual config locations - is there any way I can confirm that it is really the local feed being used as the source in the logs?)

* I delete any cached copies of the package from C:\\Users\\\<Username\>\\.nuget\\packages\\\<PackageName\>\\\<Version\> (as this could potentially contain a copy of the package pulled from ProGet as all of these CI builds are running on the same agent)
* I manually run my new CI build

This issue seems to still be reproducible using the above steps, though I cannot be 100% certain it's using the local feed over ProGet (unless there's a way for me to access more logs than can be seen from -verbosity detailed)

**Comment by nkolev92** [comment]
> (if I have understood correctly -source should take precedence over any sources in the usual config locations - is there any way I can confirm that it is really the local feed being used as the source in the logs?)

On the commandline, `-source` overrides the feeds specified in the configuration.

> This issue seems to still be reproducible using the above steps, though I cannot be 100% certain it's using the local feed over ProGet

There are logs added in 5.9, so if you can try it out with the previews, that would do it. 

Note that when you tell NuGet to use 2 feeds, local feeds are preferred over http feeds. https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process

**Comment by ImAMightyPirate** [comment]
Thank you for your support, I think I've identified the root cause and nuget.exe restore is behaving correctly.

Our ProGet server has multiple feeds - one being used as the main feed and the other being used as a symbol server. A malformed package was being pushed to the symbol server feed.

NuGet was on occasion selecting the package from the symbol server feed (which wasn't a real symbols package) and downloading it in place of the correct one.
