### ISSUE TITLE
[nuget.exe] Missing packages are displayed as warnings and not errors

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1038]
1. Remove all sources which would contain the needed packages
2. nuget.exe restore <packages.config>

The resulting messages are in yellow and shown as warnings, instead of as red errors.

Expected (2.8.6 behavior)
Unable to find version '1.0.9.3683' of package 'dotnetrdf'. (RED)

Actual (3.0.0)
WARNING: Unable to find version '1.0.9.3683' of package 'dotnetrdf'.  (YELLOW)

**Comment by emgarten** [comment]
Restoring to an invalid packages folder with -PackagesDirectory is also a warning instead of an error.

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/176916c3f16d3311a42a546a66d0c4fc7816f888

**Comment by emgarten** [comment]
@deepakaravindr when I try this using the latest build I get warnings during the restore, and then errors after. The warnings and redundant and shouldn't be there.

**Comment by emgarten** [comment]
![capture](https://cloud.githubusercontent.com/assets/6381138/9181302/7b03eca6-3f59-11e5-9d79-341368429aee.PNG)
