### ISSUE TITLE
The default version is null after clicking a deprecated package in Browse tab

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10380]
## Details about Problem
VS Version: D16.9\30808.132
NuGet Version: dev-feature-OE.PMUI\5.9.0.13982
OS Version: Windows-10-Enterprise-19H2.
## Installation
1. Install VS D16.9\30808.132: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4288690&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Client: \\\ddfiles\drops\NuGet\Drops\CI-Private\NuGet.Client\dev-feature-OE.PMUI\5.9.0.13982
## Detailed repro steps so we can see the same problem
1. Create a C# Class Library (.Net Framework) project.
2. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json
3. Open PM UI, select the above deprecated package source and search package “test10k” in Browse tab.
## Expected
The default version should show after clicking package “test10k” in Browse tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/102196702-38777b80-3efb-11eb-9d43-dfc091efcc0e.png)
## Actual
The default version is null after clicking package “test10k” in Browse tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/102196834-61980c00-3efb-11eb-9882-c1c1917dfcaa.png)
## Notes:
1. The issue also reproes on C# Console App (.Net Core) project.
2. The issue does not repro on NuGet Client Dev\5.9.0.6981.
3. The issue does not repro on deprecated packages “afine”/”ComplexLicense”/ “ComplexLicenseExpressionWithException”.

**Comment by donnie-msft** [comment]
@sbanni any chance dev works because you already fixed this?

**Comment by rrelyea** [comment]
This is likely an issue in the feature branch...we'll need to fix before or after merging that branch to dev. will work with @aortiz-msft to decide on plan.
Thx

**Comment by aortiz-msft** [comment]
@v-longmin, @v-luzh - Would you please help understand the customer impact of this issue?
