### ISSUE TITLE
Remove "Checking compatibility..." log messages from RestoreTask

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#10383]
Currently RestoreTask logs a lot of messages that start with Checking compatibility:

![image](https://user-images.githubusercontent.com/679326/102312508-b2235f80-3f23-11eb-893c-7b20d05a81e3.png)

The log output is full of these. I'm questioning the value of having these in the logs since they don't provide much useful information and generate a ton of noise.

I suggest that we just stop logging this particular message.

**Comment by KirillOsenkov** [comment]
An average size binlog contains 89193 messages like this:
![image](https://user-images.githubusercontent.com/679326/102312663-f9a9eb80-3f23-11eb-9ef2-666f37770f12.png)

Another medium-size binlog I have has:
![image](https://user-images.githubusercontent.com/679326/102312926-76d56080-3f24-11eb-8360-1e47b23e3f69.png)

It significantly contributes to the bloat in the binlog, makes investigations slower and adds noise (because the search matches for all these assembly names are full of these useless results)

**Comment by KirillOsenkov** [comment]
I guess in general the logging approach in this task follows the philosophy of "What am I currently doing?" instead of answering "Here's what you need to know".

![image](https://user-images.githubusercontent.com/679326/102313981-763dc980-3f26-11eb-8d00-42351e23b299.png)

When reading logs messages like Resolving conflicts for .NETFramework,Version=v4.7.2...
are of questionable value:
1. They don't say which project is being restored, this is inferred from the context
2. Which target framework is a useful piece of information, but it should be printed once at the beginning of restore for the project, and not duplicated over and over again (searching for this string returns too many junk results)
3. The message in and of itself is not helpful. I only need to know if something goes wrong. If this is normal operation, I don't need to know.

**Comment by KirillOsenkov** [comment]
I've highlighted the messages that are worth keeping, because they are useful:
![image](https://user-images.githubusercontent.com/679326/102314226-f2381180-3f26-11eb-99c6-d058ca0c76cd.png)

Note how the rest is pretty much redundant and just slows down the builds and increases log sizes and causes noise when reading and searching through logs.

**Comment by KirillOsenkov** [comment]
Again, highlighted the useful stuff:
![image](https://user-images.githubusercontent.com/679326/102314526-74c0d100-3f27-11eb-9a1a-7faf980d9760.png)

**Comment by zkat** [comment]
@zivkan we've moved this to customer sprint, and it sounds like Arturo is gonna try and take care of it himself :)

**Comment by KirillOsenkov** [comment]
I'd be happy to help or code review if needed.
