### ISSUE TITLE
How to view which unit test fails?

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#10387]
I clone fresh repository and run full build. It produce following error

```
error : Desktop CoreUnitTests tests failed! Results: d:\NuGet.Client\build\TestResults\CoreUnitTests-xunit.xml
```

Steps which I perform. 
1. git clone
2. .\configure.ps1
3. .\build.ps1

I definitely can open XML file and find where tests fails, but how I can do that in more pleasant way?

**Comment by donnie-msft** [comment]
I provided some links to testing docs in your other issue. Basically, you can use VS for a GUI to interact with tests and view results, or you can use the test runner CLI directly to run specific tests. The script isn't the best way to develop, in my opinion, it's more of a final step before creating a PR.
