### ISSUE TITLE
Error when build with automatic packing using cmd

### ISSUE THREAD

**Issue by eddynaka** [NuGet/Home#10382]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate): 5.0.200-preview.20601.7

VS version (if appropriate): VS2019 16.8.3

OS version (i.e. win10 v1607 (14393.321)): win10 19042.685

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. dotnet build csproj throwing error:
```
C:\Program Files\dotnet\sdk\5.0.200-preview.20601.7\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error : The given key 'tfm_raw' was not present in the dictionary. [C:\sarif-pattern-matcher\Src\Plugins\BannedApi\BannedApi.csproj]
    0 Warning(s)
    1 Error(s)
````

If I manually build using VS, it works fine.

Attached you can find a binlog

[msbuild.zip](https://github.com/NuGet/Home/files/5698378/msbuild.zip)

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by sfmskywalker** [comment]
I have the exact same issue: https://ci.appveyor.com/project/sfmskywalker/elsa-1-4-x

**Comment by sfmskywalker** [comment]
For me, this issue happens as of .NET SDK version `5.0.200-preview.20601.7`.
Version `5.0.101` does not appear to have this issue.

**Comment by cpuwzd** [comment]
I'm also having this issue. I'm trying to install Wix 4. I'm running the following command:

D:\Repos\Wix\Tools>dotnet pack -c Release src\WixToolset.Sdk -bl

I've zipped and attached the msbuild.binlog file that was produced:

[msbuild.binlog.zip](https://github.com/NuGet/Home/files/5743517/msbuild.binlog.zip)

If you examine the log using MSBuild Structured Log Viewer, you can see where the error occurred.

If you need more information, I'll do my best to provide it.

I am using .NET SDK version 5.0.200-preview.20601.7, but have not tried backing up to .NET SDK version 5.0.101.

**Comment by aortiz-msft** [comment]
This was fixed by https://github.com/NuGet/NuGet.Client/pull/3730, which will be available in the next preview.
