### ISSUE TITLE
How to run specific unit test?

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#10388]
I have file with failed unit tests, I found list of failed unit tests by running `Select-String -Pattern Result .\build\TestResults\CoreUnitTests-xunit.xml | Select-String -NotMatch -Pattern Pass | Select-String -NotMatch -Pattern Skip`

What's the way how to run single unit test?

**Comment by donnie-msft** [comment]
See if this helps https://docs.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=xunit

**Comment by kant2002** [comment]
@donnie-msft does this worth to put into documentation? Not `dotnet test` command specifically, but as suggestion for first-time user of the repo, that you can run unit tests using dotnet test, or possible even VS (is it supported scenario?)

**Comment by donnie-msft** [comment]
Some think it's out of scope for our docs, but on the other hand, a couple pointers may not be bad to add. I'll make a quick proposal...

**Comment by kant2002** [comment]
My questions is some sort of answers on following questions asked here
https://twitter.com/zkat__/status/1338610968096505856?s=21
