### ISSUE TITLE
Cannot run Nuget.Client library

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#10390]
I clone project and build it. Build without unit tests was without error.

Install extension using `VSIXInstaller.exe NuGet.Tools.vsix`. This is only extension which I have in the `artifacts\VS15` folder.
After trying to launch `Nuget.VisualStudio.Client` project, build tell me that I have same or lower version of `NuGet.72c5d240-f742-48d4-a0f1-7016671e405b` package.

**Comment by donnie-msft** [comment]
My first reaction is to try the following:

1. Try downgrading, see if that succeeds. Then retry installing the new VSIX. 
Downgrade command: `VSIXInstaller.exe /d:NuGet.72c5d240-f742-48d4-a0f1-7016671e405b`
See: https://github.com/NuGet/NuGet.Client/blob/dev/docs/debugging.md#uninstalling-a-custom-version-of-the-nuget-extension-from-visual-studio

2. If no luck there, maybe VS Setup logs will show something interesting. You can get the files with the following steps:

> 1. Download collect.exe from the link https://aka.ms/vscollect 
> 2. You may choose to save the tool for later use, or to run directly.
> 3. The utility creates a compressed cabinet of all the VS and .NET logs to %TEMP%\vslogs.zip.
> 4. Upload your vslogs.zip
> You can get more details about how to get the log files here: https://devblogs.microsoft.com/setup/microsoft-vs-net-log-collection-tool/

**Comment by kant2002** [comment]
It is even more interesting. I manage to figureout that installing Nuget.Tools.vsix was not nescessary, and VS SDK automatically install extension to `/rootSuffix:Exp` instance of VS. I think it is required to make clarification, that installing of dev version for debugging is not needed.

**Comment by donnie-msft** [comment]
> Testing the NuGet Visual Studio functionality is equally as easy as testing NuGet.exe. The start-up project is NuGet.VisualStudio.Client. Starting this will launch the experimental instance of Visual Studio.

If this line clarified it would cause VS to install the VSIX, would that make it clear?

**Comment by kant2002** [comment]
Partially. Specifically it should be clear that installation of package manually can cause debug scenario to break, since VS SDK cannot install extension of same version. 

Maybe 
> Testing the NuGet Visual Studio functionality is equally as easy as testing NuGet.exe. The start-up project is NuGet.VisualStudio.Client. Starting this will launch the experimental instance of Visual Studio and install extension for you.

At least this gives hint what's going on behind the scene.

**Comment by nkolev92** [comment]
Maybe we can add a common pitfalls, Q&A in the debugging docs as well.

Should we make that by product or just general?
