### ISSUE TITLE
During restore NuGet logs "The project does not specify any target frameworks" that you can't get rid of

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#1039]
The code in particular is here:
https://github.com/NuGet/NuGet3/blob/03d8966f7d6760830b832800a2dbaa1bab40bce2/src/NuGet.Commands/RestoreCommand.cs#L150

We're hitting this on the Roslyn (http://github/dotnet/roslyn) repro. Opening that solution and building results in the following being output into the Error List:
```
Error		The project does not specify any target frameworks.			0
```

There's a few problems with it:
1. It's not associated with _any_ project, so unloading ever project in the solution still results in the error being present.
2. Related to 1. It doesn't tell _which_ project is at fault - there's 128 projects in the solution, and I have literally no idea which one is at fault.

**Comment by Burnaster** [comment]
We have the same issue on our solution. The error is also visible in the build-output window, and appears at the very begining of a build:
================================
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
The project does not specify any target frameworks.
================================

**Comment by zhili1208** [comment]
@davkean @Burnaster Please check there are frameworks in project.json file, it looks like this 
 "frameworks": {
      "dnxcore50": {}
  }

**Comment by zhili1208** [comment]
In Roslyn, they already fixed this, please pull latest code

**Comment by zhili1208** [comment]
duplicate issue. https://github.com/NuGet/Home/issues/1047

**Comment by davkean** [comment]
These aren't duplicate issues; one is referring to NuGet restore crashing when the project does not have any target frameworks, the other is referring to that this error message isn't associated with any projects.

**Comment by zhili1208** [comment]
this error message is from RestoreCommand, this command is for restoring package in project.json. it will show this message when It can't find any target framework. So After you add framework to project.json, does this error still repro?

**Comment by davkean** [comment]
No the error doesn't occur, but I didn't open this bug around that. I opened the bug to track that this error isn't associated with *any* project, this makes it extremely difficult to the find the problem project when you have large amounts of projects. It's also hidden by default in the new Error List because it's not associated with any project.

**Comment by zhili1208** [comment]
Sorry for that, we should improve this message, it should show project name and also say that "target framework is missing in project.json". I will file another bug to improve the message.

**Comment by davkean** [comment]
Regardless of whether it shows the project name in the message, it should be *associated* with the project. Those are two different things with different behavior.

This bug is supposed to be tracking improving the error message - so why would file another instead of just opening this one?

**Comment by zhili1208** [comment]
Ok, let's use this bug to track improving the error message issue.
1. the error message should be associated with project in error List.
2. Improve message content, say that  "target framework is missing in project.json".
