### ISSUE TITLE
Introduce a new msbuild property to exclude build output for specific tfms during pack task

### ISSUE THREAD

**Issue by Anipik** [NuGet/Home#10396]
Nuget currently provides a msbuild called IncludeBuildOutput to disable including the build output for all tfms. 
Nuget provides this kind of feature for other targets like ```_GetFrameworksWithSuppressedDependencies``` which run during the pack command.
It will enable the scenario where developer wants to exclude a certain kind of build output for a specific tfm.

cc @ViktorHofer @nkolev92 @ericstj @safern

**Comment by ViktorHofer** [comment]
Or just respect the existing property in inner builds as well?

**Comment by Anipik** [comment]
> Or just respect the existing property in inner builds as well?

yep i thought that as well, just added a new one to just start the discussion. moving the existing property to innerbuilds will be optimal

**Comment by ViktorHofer** [comment]
Agreed, this is a good way to start a discussion. What confused me is that you already opened a PR with a new property name. The problem with a new property is that even if it will be documented (which it should be), it would cause confusion about the differences between the existing and the new one.

**Comment by nkolev92** [comment]
I think reusing the existing property is better than the new one. 
Thinking through it, I don't think there should be any concerns with compat with that either.

**Comment by nkolev92** [comment]
cc @zkat when they're back :)

**Comment by Anipik** [comment]
Updated the pr

**Comment by erdembayar** [comment]
@Anipik 
This PR introduced regression bug [issue#10462](https://github.com/NuGet/Home/issues/10462). So we're reverting the merge.
Can you check what was the problem and rectify it and create new merge PR request?

**Comment by erdembayar** [comment]
It seems false alert here
