### ISSUE TITLE
What's the .NET SDK Equivalent of `nuget init`

### ISSUE THREAD

**Issue by brettrowberry** [NuGet/Home#10398]
## Details about Problem
With Nuget.exe, the command 
`nuget init .\src .\dest\` 
will put hierarchical versions into the `dest` directory based on the `.nupkg` files in the `src` directory.

How can I do this using dotnet.exe?

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe
dotnet.exe

NuGet version (x.x.x.xxx):
5.6.0.6591

dotnet.exe --version (if appropriate):
5.0.100

**Comment by donnie-msft** [comment]
I'm not sure if this is available... @dominoFire ?

**Comment by brettrowberry** [comment]
What I’m trying to accomplish is first, to generate a NuGet package on my machine, and second, consume it in another solution. I’d like to be able to rapidly iterate on the package and do all this with only dotnet.exe (no NuGet.exe).

**Comment by brettrowberry** [comment]
This article explains it well (when not on Windows, nuget.exe requires Mono) https://www.nequalsonelifestyle.com/2019/10/31/local-nuget-dependencies-on-linux/

> It is disappointing to have to install an entire other .NET environment just to do something as simple as doing this package install but sadly that’s the state of things right now.

They ran `nuget add` (`nuget init` does the same thing but for every .nupkg in a directory), but the limitation is the same.

**Comment by zivkan** [comment]
@brettrowberry you can put all the nupkgs in a single directory and use that as a local source. It's not necessary to put them in a hierarchical (v3) folder structure. The v3 folder structure has better perf than a flat directory of nupkgs, but if it only contains the packages that you're testing in an "inner-loop" scenario, the difference in perf will be negligible.

**Comment by brettrowberry** [comment]
That’s good to know! Would your advice be the same if I was creating a package A that depended on two other packages I was making, B and C, and testing A?

**Comment by zivkan** [comment]
I wouldn't expect the perf difference to be noticeable for restore unless you have hundreds of nupkgs in the folder, maybe thousands depending on disk and CPU. Assuming you periodically clear our the folder you're using for testing while developing a package, I wouldn't expect you to have an issue.

It would be more apparent for search (like Visual Studio's package manager). But honestly if perf is an issue when using a file feed, I'd suggest a self-hosted HTTP nuget server. It's overkill for automated tests of packages in a CI build script, but it'll be much better than a network file share for sharing packages with team mates.

A number of people have had this misunderstanding, so it's probably worthwhile me mentioning that if your package contains only your project's dlls, nothing else (no content files, msbuild files, etc), then don't create packages for testing/inner-loop. Just use a project reference instead. For simple class libraries packed into packages, there's no difference between a package and project reference from the compiler/build point of view.
