### ISSUE TITLE
Source parameter is not considered for `dotnet add package` command

### ISSUE THREAD

**Issue by adrianiftode** [NuGet/Home#10407]
## Details about Problem

NuGet product used dotnet.exe

dotnet nuget --version
NuGet Command Line
4.9.4.0

dotnet.exe --version (if appropriate): 
5.0.101

VS version (if appropriate):

OS Version:                10.0.18362 N/A Build 18362

Worked before? If so, with which NuGet version:

Don't know, but other commands work (ie dotnet restore)

## Detailed repro steps so we can see the same problem

1. Execute the following command
`dotnet add package Microsoft.EntityFrameworkCore.Sqlite --source https://api.nuget.org/v3/index.json`

2. Expected to install the package, but getting the following results

```
  Determining projects to restore...
  Writing C:\Users\a.iftode\AppData\Local\Temp\tmpC211.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.Sqlite' into project 'D:\opensource\aspnetcore\IntegrationTestsIssue\IntegrationTestsIssue\IntegrationTestsIssue.csproj'.
info :   GET ... info :   NotFound with following message : Response status code does not indicate success: 404 (Not Found).
error:   Response status code does not indicate success: 404 (Not Found).
````
I removed internal links as these are private

## Other suggested things

In order to install the package, I added
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.1" />
```
in the csproj file

and run
`dotnet restore -s https://api.nuget.org/v3/index.json`
which restores correctly the package

**Comment by erdembayar** [comment]
@adrianiftode
I was able to repro with following local nugetconfig setting to override global nuget.config.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    
  </packageSources>
</configuration>
```

It's technically dup of [#5127](https://github.com/NuGet/Home/issues/5127). I already have [PR#3783](https://github.com/NuGet/NuGet.Client/pull/3783) to fix it.

So, I'm closing it dup.

**Comment by erdembayar** [comment]
Dup of [#5127](https://github.com/NuGet/Home/issues/5127)

**Comment by adrianiftode** [comment]
Indeed, https://api.nuget.org/v3/index.json is removed from my config, this is the reason I'm providing it as a parameter.
