### ISSUE TITLE
Embedded icons showed incorrectly as default nuget packge icon instead of the ones set in nuspec/csproj file

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10409]
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.6996
VS Version: Main\30822.27
OS: Windows-10-Enterprise-19h2
## Detailed repro steps so we can see the same problem
1.Create a Class Library (.NET Framework 4.8) in VS and build the solution. 
2.In the Developer Command Prompt for VS, create a nuspec file by executing command “nuget spec” 
3.Make an image file (size limited to 1 MB with PNG format and 128x128 resolution) and locate in the package. 
4.Add following to nuspec file (both the two kinds of backlash \ and / should be test in the line <icon>images\icon.png</icon>) 
```
<package> 
  <metadata> 
    ... 
    <icon>images\icon.png</icon> 
    ... 
  </metadata> 
  <files> 
    ... 
    <file src="[icon path]\icon.png" target="images\" /> 
    ... 
  </files> 
</package> 
```
5. Pack the package to local path by executing command “nuget pack”. 
6. Create a C# Console App (.NET Framework 4.8) in VS and open the PM UI of the project. 
7. Add the package source as a local feed in Settings->NuGet Package Manager->Package Sources. 
8. Select the new added local feed in the Package source dropdown box in the PM UI and install the package.
## Expected
The embedded icon show correctly on both “Browse”/”Installed”/”Updates”/”Consolidate” tab.
## Actual
Embedded icons showed incorrectly as default nuget packge icon instead of the ones set in nuspec/csproj file as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/102983584-42c2f680-4547-11eb-9276-2f2a1bab2820.png)
## Notes
1.It repro for all valid embedded icons.
2.It start to repro on dev branch after merging NuGet Client dev-feature-OE.PMUI\5.9.0.13982 into Dev.

**Comment by rrelyea** [comment]
will be fixed when https://github.com/nuget/home/issues/10151 is done
