### ISSUE TITLE
_GenerateRestoreProjectPathWalk is too slow.

### ISSUE THREAD

**Issue by BehroozAmoozad** [NuGet/Home#10403]
## Details about Problem

Latest stable dotnet and all previous versions that I know of are affected.
ALL OS
ALL environments
Worked before? No

## Detailed repro steps so we can see the same problem

1. Have a complex solution with dependencies all over the place

2. Execute `dotnet restore /clp:PerformanceSummary SolutionName.sln`

3. 124286 ms  _GenerateRestoreProjectPathWalk          257 calls
 
### Verbose Logs
I can't provide these. 

I believe this abomination is the reason: https://github.com/NuGet/NuGet.Client/blob/b0fef98e6328948e7669297d6869fa792b39e805/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L1050  
I don't know if this sorts the lists, compares sanely, uses keys, hashtables or whatnot properly or not. And I think this repeats some work because I see no way an XML like that is deserialized into an object that understands the context properly. 
Anyway, where I come from it takes at most a millisecond to insert ~250 nodes in a dependency tree. not 124 seconds. And I can't understand how on earth a high profile project could let this be. Wasn't there anyone involved in the project that would say "The dependency resolver is the most interesting part of any build system and I'm gonna science the shit out of it?"

**Comment by erdembayar** [comment]
Hi.
Can you create repro solution and share with us? That'll definitely help us to solve this issue. 
I need more details. For example: Did you install new package or upgrade existing package? Are those sdk style or package.config style projects?

**Comment by BehroozAmoozad** [comment]
@erdembayar 
The bug in question is making problems in my ci builds. The environment is rebuilt before each build. And there are absolutely zero nuget packages used, because I don't trust nuget.

[Behrooz-blank.zip](https://github.com/NuGet/Home/files/5753443/Behrooz-blank.zip)

**Comment by erdembayar** [comment]
@BehroozAmoozad 
Can you give `dotnet --info` output?
It didn't take that much long on my local. Actually whole clean restore  just took about 4 seconds on my local, but somehow `dotnet restore /clp:PerformanceSummary` reports much longer duration. Maybe there is some accuracy issue or difference in how it get interpreted. 

![image](https://user-images.githubusercontent.com/8766776/103392266-de1d1400-4ad1-11eb-9ed1-7edc36aaf10b.png)

Also can you do `Measure-Command { dotnet restore /clp:PerformanceSummary Behrooz.sln }` ?
Mine looks like this: 
![image](https://user-images.githubusercontent.com/8766776/103392390-7ddaa200-4ad2-11eb-8df7-703031ef05b3.png)

**Comment by BehroozAmoozad** [comment]
```
# dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

[restore time.txt](https://github.com/NuGet/Home/files/5756588/restore.time.txt)

```
# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       46 bits physical, 48 bits virtual
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  2
Core(s) per socket:  12
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
Stepping:            2
CPU MHz:             1198.666
CPU max MHz:         3100.0000
CPU min MHz:         1200.0000
BogoMIPS:            4594.76
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            30720K
NUMA node0 CPU(s):   0-23
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d
```
This is not a VM. this is gitlab-ci instance installed on a barebones DL380 gen9 debian machine with nothing else running on it.

**Comment by BehroozAmoozad** [comment]
I realized after posting that I ran the measure command on a slighly different sln. There are still 0 external references because we don't use them. but if it really matters I can rerun them using the blank sln I created.

also, everything benchmarked up until now has been on a tmpfs(ramdisk) to avoid disk/ssd performance interference.

**Comment by erdembayar** [comment]
After looking at your log, actual total duration is about 20-30 seconds, but don't know why it's slower than my 4 seconds range. 
Unfortunately, I don't have `debian` environment development experience. I guess discrepancy might be due to something to do with dotnet implementation on platform or other settings.
By default MSbuild and nuget try to run restore in parallel utilizing multiple CPU cores if available. If MSBuild is doing the work in parallel, the the cumulative total of this parallel work will be greater than the wall-clock time.
So interpretation of `239775 ms  _GenerateRestoreProjectPathWalk` in reports mean many parallel works kicked off in order to shorten overall duration.

**Comment by BehroozAmoozad** [comment]
Reran it on a windows 10 machine (ryzen 3700x) (consumer-grade ssd drive) with warm-up.
`TotalMilliseconds : 7752.1214`
```
Target Performance Summary:
        0 ms  ValidateProjects                           1 calls
        0 ms  ValidateToolsVersions                      1 calls
        2 ms  CollectCentralPackageVersions            255 calls
        2 ms  _GetRestoreSettingsCurrentProject        255 calls
        2 ms  CollectPackageReferences                 255 calls
        2 ms  _GenerateRestoreGraphProjectEntry        255 calls
        3 ms  _GenerateRestoreDependencies             255 calls
        3 ms  _GenerateProjectRestoreGraph             255 calls
        3 ms  _GenerateRestoreProjectPathItemsCurrentProject 255 calls
        3 ms  _GenerateProjectRestoreGraphCurrentProject 255 calls
        4 ms  UpdateAspNetToFrameworkReference           5 calls
        5 ms  CollectFrameworkReferences               255 calls
        6 ms  _CheckForUnsupportedNETCoreVersion       255 calls
        7 ms  _CheckForUnsupportedCppNETCoreVersion    255 calls
        7 ms  CollectPackageDownloads                  255 calls
        7 ms  _CheckForObsoleteDotNetCliToolReferences 255 calls
        7 ms  ValidateSolutionConfiguration              1 calls
        9 ms  _LoadRestoreGraphEntryPoints               1 calls
       11 ms  _CheckForLanguageAndFeatureCombinationSupport 255 calls
       12 ms  ApplyImplicitVersions                      5 calls
       12 ms  _GetProjectJsonPath                      255 calls
       14 ms  _GetRestoreSettingsOverrides             255 calls
       16 ms  _GetRestoreSettingsPerFramework          255 calls
       19 ms  _IsProjectRestoreSupported               255 calls
       25 ms  _GenerateRestoreProjectPathItems         255 calls
       43 ms  _GenerateRestoreSpecs                    255 calls
       62 ms  _GenerateDotnetCliToolReferenceSpecs     255 calls
       69 ms  CheckForImplicitPackageReferenceOverrides 255 calls
       71 ms  _GetRestoreProjectStyle                  255 calls
       95 ms  _GetRestoreTargetFrameworksOutput        255 calls
       96 ms  _GenerateRestoreProjectSpec              255 calls
      119 ms  _GenerateRestoreProjectPathItemsPerFramework 255 calls
      200 ms  _GenerateProjectRestoreGraphPerFramework 255 calls
      436 ms  ProcessFrameworkReferences               255 calls
      564 ms  _GetAllRestoreProjectPathItems             1 calls
      660 ms  Restore                                    1 calls
      805 ms  _GenerateRestoreGraph                      1 calls
     1179 ms  _FilterRestoreGraphProjectInputItems       1 calls
     5322 ms  _GetRestoreSettings                      255 calls
    36663 ms  _GenerateRestoreProjectPathWalk          255 calls

Task Performance Summary:
        1 ms  NuGetMessageTask                           1 calls
        1 ms  WarnForInvalidProjectsTask                 1 calls
        4 ms  CheckIfPackageReferenceShouldBeFrameworkReference  10 calls
        6 ms  GetRestoreSolutionProjectsTask             1 calls
        8 ms  ApplyImplicitVersions                      5 calls
       12 ms  Message                                  512 calls
       21 ms  CheckForDuplicateFrameworkReferences     255 calls
       22 ms  GetRestorePackageDownloadsTask           255 calls
       23 ms  GetRestoreFrameworkReferencesTask        255 calls
       26 ms  CheckForImplicitPackageReferenceOverrides 255 calls
       28 ms  GetRestorePackageReferencesTask          255 calls
       33 ms  GetRestoreDotnetCliToolsTask             255 calls
       37 ms  ConvertToAbsolutePath                    510 calls
       40 ms  GetRestoreProjectStyleTask               255 calls
       43 ms  GetProjectTargetFrameworksTask           255 calls
       55 ms  GetRestoreProjectReferencesTask          255 calls
       56 ms  RemoveDuplicates                         513 calls
      105 ms  ResolveAppHosts                          255 calls
      238 ms  ProcessFrameworkReferences               255 calls
      656 ms  RestoreTask                                1 calls
     5281 ms  GetRestoreSettingsTask                   255 calls
    39037 ms  MSBuild                                  260 calls
```
I do realize that a 3700x might be faster than a 2670 v3. but not by a factor of ~7. Correct? 
How do I bisect the problem further?

**Comment by nkolev92** [comment]
Hey @BehroozAmoozad,

The target in question is how NuGet through msbuild currently reads the project files. 
The performance can be affected by the project type, file count, *log verbosity*, etc. 

Since the original PackageReference implementation the NuGet team has worked with MSBuild team to develop a faster way for reading the project files. 

We currently have an experimental feature for that, that I just documented in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2268 and https://github.com/NuGet/docs.microsoft.com-nuget/issues/1941. 

Please try it out by adding `/p:RestoreUseStaticGraphEvaluation=true` to the end of your command.
