### ISSUE TITLE
Make readonly files by default in NuGet packages

### ISSUE THREAD

**Issue by xoofx** [NuGet/Home#10404]
Hey,

Related closed issue #1729

In the project Scriban, I'm using a mode where I ship with my package also the sources of the project that can be used internally in the consuming projects (these are not contentFiles but custom source files added by the package). See [embedding source](https://github.com/scriban/scriban#source-embedding) in Scriban.

It allows me to release a NuGet package with binaries and sources, and the user can choose which version to use.

One big issue with NuGet today is that files extracted on the disk are not readonly. That means that if a user, by mistake, is starting to change files on the disk, it will change files machine wide (or from where the NuGet package cache is used).

**Comment by erdembayar** [comment]
@JonDouglas 
There was similar request long time ago. But what about now?
https://github.com/NuGet/Home/issues/1729

**Comment by aortiz-msft** [comment]
Hey there. Thanks for your suggestion. Because this change could disrupt tooling from others in the community, particularly across platforms, we will not look at this unless the issue gets upvoted by the community. However, we will keep this in mind shall we rethink our local global package folder solution.

**Comment by nkolev92** [comment]
Starting with 16.8, Visual Studio will open content files from the global packages folder in a `read-only` way. https://github.com/dotnet/project-system/issues/2141

This likely covers one of the common occurrences of `I edited my installed package accidentally`
