### ISSUE TITLE
dotnet add package returns local source not found

### ISSUE THREAD

**Issue by varunmankal** [NuGet/Home#10402]
When I do dotnet nuget list source, it shows the following sources:
* nuget.org
* mysource

However, when I run `dotnet add package <packageID> -s mysource`, it returns local source `mysource` doesn't exist

**Comment by erdembayar** [comment]
Is your source local source or http source?
If it's local then folder structure may have issue. 
Most likely what you're experiencing could be part of [issue#5127](https://github.com/NuGet/Home/issues/5127).

**Comment by aortiz-msft** [comment]
Closing as dupe of https://github.com/NuGet/issue/issues/5127.
