### ISSUE TITLE
[nuget.exe] Restore does not no-op when packages already exist

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1040]
Steps
1. nuget.exe restore .\packages.config -packagesdirectory " <mypath>\Visual Studio 2015\Projects\BugBash\BugBash\test" -Source https://www.nuget.org/api/v2/ -Source https://api.nuget.org/v3/index.json
2. Run the above command again

Expected
The second run should say that all packages have been restored

Actual
Messages are logged saying that packages are being added

**Comment by deepakaravindr** [comment]
@emgarten, Note that if the solution has an UWP project, it will always say that there are packages to be installed. However, if the solution only has legacy projects, and the packages are already installed, you will not see messages that packages are being restored. I have verified. Did you use a solution with UWP projects in them?

**Comment by emgarten** [comment]
@deepakaravindr it had a mix, however that should not cause packages.config projects to restore all packages when they already exist. The messages about adding packages should be skipped.

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/8d98c6fd9fbe219390f4b46ece3ae9b357eaf753
