### ISSUE TITLE
Floating versions not working for pre-release packages with semantic versioning suffix like "-alpha"

### ISSUE THREAD

**Issue by davidliang2008** [NuGet/Home#10408]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.8.0.6930

VS version: Visual Studio Professional 2019 Version 16.8.3

OS version: Windows 10 Pro for Workstations, 64 bits, Version 2004, OS build 19041.685

## Detailed repro steps so we can see the same problem

1. Create and deploy a library as NuGet package. Push it as pre-release: LibA.2.1.1-alpha, for example

2. Create another library, called LibB, that references the first NuGet package. Specify its dependency in its .nuspec using floating versions and push it as pre-release:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <dependencies>
            <group>
                <dependency id="LibA" version="2.1.1-*" />
            </group>
        </dependencies>
    </metadata>
</package>
```

3. Create yet another driver program that references LibB pre-released NuGet package.
4. When you try to install/update LibB NuGet package in the driver program, errors occur:
   - Package restore failed. Rolling back package changes for 'NAME_OF_DRIVER_PROGRAM'.
   - NU1603: LibB depends on LibA (>= 1.2.1-0) but LibA 1.2.1.0 was not found. An approximate best match of LibA 1.2.1-alpha was resolved.

Note, on the Common Scenarios section in the documentation (https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions), it shows that floating versions like `1.2.0-*` will match pre-released versions like `1.2.0-rc.2`.

How come that doesn't work in my case?

**Comment by nkolev92** [comment]
@davidliang2008 

Hey, please refer to https://github.com/NuGet/Home/wiki/Support-pre-release-packages-with-floating-versions#non-goals. 

> Floating versions are only supported as declarations in the project, not in the nuspec. This is not going to change.
