### ISSUE TITLE
SDK projects with bad data not showing restore errors in VS

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#10406]
If you have a project with an error that allows the project to be loaded, but with an error that NuGet can't handle, the assets file is not being written and therefore no error is being reported in Visual Studio.

An example of such an error is a PackageReference with an invalid version string `<PackageReference Include="NuGet.Versioning" Version="broken" />`.

Broken in both VS16.9 previews, and VS16.8, so appears to have regressed from 16.7 at best.

**Comment by donnie-msft** [comment]
Found this problem in https://developercommunity2.visualstudio.com/t/Nuget-integration-is-broken/1291549
