### ISSUE TITLE
"Unable to load the service index for source https://api.nuget.org/v3/index.json" in unbuntu

### ISSUE THREAD

**Issue by agr** [NuGet/Home#10414]
@hieunm22 commented on [Sun Dec 13 2020](https://github.com/NuGet/NuGetGallery/issues/8351)

I'm using **ubuntu 18.04 LTS** and going to build my application using dotnet build
but it pops an error that tells _Unable to load the service index for source https://api.nuget.org/v3/index.json._
I tried to search the same issue and I found this [thread](https://github.com/NuGet/NuGetGallery/issues/7705). but all comments in this thread show how to fix in windows, not in ubuntu.
could some one tell me the solution in my case? 
thanks

---

@agr commented on [Thu Dec 17 2020](https://github.com/NuGet/NuGetGallery/issues/8351#issuecomment-747690955)

Apologies for the delayed response.

Could you please share a full build log with detailed verbosity (`dotnet build --verbosity detailed`)? Feel free to send it to support@nuget.org if you don't want to put it here.

The thread you mention is specifically about addressing an SSL/TLS issues, do you see error messages that mention it?
Are you able to open `www.nuget.org` in a browser on that computer? Does `curl https://api.nuget.org/v3/index.json` succeed?

---

@hieunm22 commented on [Thu Dec 17 2020](https://github.com/NuGet/NuGetGallery/issues/8351#issuecomment-747840418)

Thanks for your response althought late
Here's the full log with the command you provided above
https://controlc.com/1e820605

The URL `www.nuget.org` can be accessed normally in browser, and so can the `curl https://api.nuget.org/v3/index.json`

Some additional informations in my case:
- I created a new project with type = "mvc", type = "console" and the command `dotnet build` runs successfully but some types such as "react", "classlib" doesn't
- The `dotnet build` command in my windows 10 machine runs properly

---

@agr commented on [Mon Dec 21 2020](https://github.com/NuGet/NuGetGallery/issues/8351#issuecomment-749158985)

Which SDK version are you using? Tried updating to the latest one?
I tried setting up an Ubuntu 18.04 VM to try to reproduce the issue and with the latest SDK it worked fine.

I am looking at the log, and I see that it fails but with a different error:

> /usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception.
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   The remote certificate is invalid according to the validation procedure.

You mentioned that it complained about "Unable to load the service index for source https://api.nuget.org/v3/index.json." before. Do you get consistent error messages?

Please, send us the output of `echo | openssl s_client -servername api.nuget.org -connect api.nuget.org:443 2>/dev/null`
The issue might be related to the version of OpenSSL on your system, please try updating to the latest one.

---

@hieunm22 commented on [Tue Dec 22 2020](https://github.com/NuGet/NuGetGallery/issues/8351#issuecomment-749932388)

all dotnet components are up to date to version 3.1 LTS
what's your latest version? latest version is currently 5.0
 
this is the outout for the command above

`https://controlc.com/299441b0`

about the openssl, i updated it to latest version. is it the latest one: 1.1.1g  21 Apr 2020

---

@agr commented on [Wed Dec 23 2020](https://github.com/NuGet/NuGetGallery/issues/8351#issuecomment-750456425)

Yes, I was using 5.0. I also installed 3.1 it works fine, too.

**Comment by erdembayar** [comment]
@hieunm22 
It looks your Ubuntu somehow doesn't trust OpenSSL certificate on it. 
Please open https://api.nuget.org/v3/index.json in your web browser? Do you see SSL lock in your browser url address?
![image](https://user-images.githubusercontent.com/8766776/103254372-e9d5d280-4939-11eb-981d-7d7d6f3b4f47.png)

Please let me know.

**Comment by hieunm22** [comment]
@erdembayar 
I can access that page normally in browser. The SSL icon appears properly

when I open project using VSCode, it pops a popup that said "There are unresolved dependencies. Please execute the restore command to continue"
then here's what the output window shows

https://controlc.com/d883fce2

I don't know what is missing in my machine, but with the same code in windows 10, it runs properly

**Comment by zivkan** [comment]
Which browser? I know that Firefox keeps its own list of trusted certificate authorities, so will behave differently to other applications that use OpenSSL's trusted certificate store to validate certificates.

How about curl or wget? Can they download index.json?

What about a minimal C# program:
```cs
public async Task Main()
{
    var client = new HttpClient();
    var response = await client.GetStringAsync("https://api.nuget.org/v3/index.json");
    Console.WriteLine("Didn't throw exception");
}
```

**Comment by hieunm22** [comment]
- it's Chrome
- about curl and wget, curl can download index.json but either can wget
- about minimal c# program, it throws exception when running this piece of code
https://controlc.com/7d65981b

**Comment by zivkan** [comment]
> about curl and wget, curl can download index.json but either can wget

I'm not sure if this means wget can or can't access api.nuget.org. Since you wrote "but", I'm guessing it can't. Perhaps this means that wget does SSL/TLS negotiation in the same way that .NET does.

Since the test C# program reports the same `The remote certificate is invalid according to the validation procedure` error, it shows that this is not a bug in NuGet, but that .NET itself cannot connect to this host from your machine.

For what it's worth, I created an Ubuntu 18.04 VM on Azure, installed .NET 5 and it was able to download packages from nuget.org just fine. So it appears to me that .NET and NuGet are working fine, and it's an operating system configuration issue.

I'm afraid I'm not an expert on Linux or Ubuntu, so I can't help solve this issue. I found [this issue](https://github.com/dotnet/runtime/issues/27434) that lists locations where dotnet via openssl looks for certificates, but I don't know what you should do with this knowledge. I suggest contacting Ubuntu support. But the evidence is that this is not a bug in NuGet, and since it's not on Windows, it's not related to other Microsoft products.
