### ISSUE TITLE
Must use PackageReference

### ISSUE THREAD

**Issue by cscuser** [NuGet/Home#10410]
packages\Microsoft.Windows.SDK.Contracts.10.0.17763.1000\build\Microsoft.Windows.SDK.Contracts.targets(4,5): error : Must use PackageReference

when i install Microsoft.Identity.Client library using Nuget Manager I got "Must use PackageReference" error in .Net MVC Project.

**Comment by zivkan** [comment]
The error is coming from the package, not from NuGet (see the path to the targets file, as reported by MSBuild).

Looking at the package on nuget.org: https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts/
it says this:

> Requires default package management format set to PackageReference, and NuGet 4.0 or higher.

You can contact the package owner on nuget.org, on the right side under the "Info" block, there's a link "Contact owners".

There's nothing the NuGet team can do about package authors generating errors in their MSBuild files.

**Comment by ronaldbarendse** [comment]
@zivkan This is indeed related to: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2247

**Comment by zkat** [comment]
This is not a NuGet issue, as @zivkan says.
