### ISSUE TITLE
nuget.exe should be renamed to NuGet.exe to have the correct casing and consistent with older releases

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1041]
Now we generated nuget.exe and NuGet-Signed.exe.

Should rename nuget.exe to NuGet.exe

**Comment by deepakaravindr** [comment]
Looks like the nuget.exe published to nuget.org is nuget.exe. However, the exe shipped as part of NuGet.CommandLine package is NuGet.exe

**Comment by deepakaravindr** [comment]
Duplicate of https://github.com/NuGet/Home/issues/873

**Comment by deepakaravindr** [comment]
We will use the same casing for nuget.exe both the exe and NuGet.CommandLine package. It will be simply nuget.exe
