### ISSUE TITLE
NuGet.exe install output is confusing, with target framework specified

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1042]
c:\temp>nuget.exe install fake
Attempting to gather dependencies information for package 'fake.4.0.2' with respect to project 'c:\school', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'fake.4.0.2' with DependencyBehav
ior 'Lowest'
...

These output messages do not apply to nuget.exe install scenarios (how to determine its target framework?) and can be omitted to reduce confusion.

**Comment by emgarten** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/5736
