### ISSUE TITLE
Determine what downloading a specific version of a nuget package

### ISSUE THREAD

**Issue by Ncage1974** [NuGet/Home#10434]
Hi Guys, hopefully its ok to ask this question here. Don't know what else to do since I asked on stackoverflow and all I got was crickets. We are using Whitesource to scan for vulnerable dependencies. Here is one of the vulnerable packages Whitesource reported:
![image](https://user-images.githubusercontent.com/1213549/103939045-c4428900-50f0-11eb-89e3-98552cc9ed3b.png)

As you can see in the image if the issue in the NuGet package cache folder (actually all the issues it found were in the NuGet package cache foler):
/root/.nuget/packages/system.net.http/4.3.3/system.net.http.4.3.3.nupkg

We are not directly referencing `systme.net.http` so it must be a sub dependency of something. I have verified the issue on my machine. I can delete my nuget cache folder and and soon as I do a `dotnet restore`:
![image](https://user-images.githubusercontent.com/1213549/103938869-880f2880-50f0-11eb-8058-dd4cb343ff9b.png)

**So the issue is how to determine what higher level dependency is causing that causing that dependency to be downloaded**  so I can upgrade that package to fix the issue? This is the only thing I could think of to try so far which apparently doesn't work:
![image](https://user-images.githubusercontent.com/1213549/103939379-4df25680-50f1-11eb-9689-2166fc9fbe43.png)

Most of the packages are listed as `4.3.0` which is never downloaded. I found the project in our large solution that is causing it to be downloaded by doing a `dotnet restore` project by project but still haven't been able to find the dependency. Any help would be MUCH appreciated.

**Comment by JonDouglas** [comment]
Nothing quite exists to tell you why directly today. The solution explorer in your last screenshot is one of the better visualization methods, but you may also have success using dotPeak or similar to dive into each assembly.

For example, in your case, Moq > Castle.Core > NETStandard.Library is what is bringing in the dependency.

![image](https://user-images.githubusercontent.com/1288848/104045519-4b046e00-51a4-11eb-8a45-5137d004f70b.png)

https://www.nuget.org/packages/NETStandard.Library/1.6.1

On the NETStandard.Library page, you'd then see that System.Net.Http (>= 4.3.0) is brought in.

There is some work to show transitive dependencies in the VS PM UI that may help this.

https://github.com/NuGet/Home/wiki/Flag-vulnerable-packages#display-vulnerabilities-in-visual-studio-pmui

![image](https://user-images.githubusercontent.com/1288848/104046170-48eedf00-51a5-11eb-9014-27767b719c13.png)

There's also the [dotnet list package](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package) command which supports `--include-transitive` which will list transitive packages for a project or solution.

EX: `dotnet list package --include-transitive`

We're also looking into adding a better "why" functionality to the CLI:

![image](https://user-images.githubusercontent.com/1288848/104046082-265cc600-51a5-11eb-9675-ad6dcbb727c3.png)

or creating a separate `dotnet why` command that will just tell you how the package is being included and showing the tree to the top-level dependency.

**Note:** These items can change at any point and are not subject to the ultimate experience, just sharing some ideas to see if they would be helpful!

Hopefully this answers your question today!

**Comment by Ncage1974** [comment]
Thanks so much @JonDouglas that was super helpful. I definitely does answer my question and thanks so much for your time.

**Comment by cetintozkoparan** [comment]
Hi @Ncage1974. Were you able to prevent showing up this type of critical issues in WhiteSource?
