### ISSUE TITLE
Alias in ProjectReference does not work for framework-included packages

### ISSUE THREAD

**Issue by weltkante** [NuGet/Home#10438]
## Details about Problem

In #4989 alias support for PackageReference was added, but when I try to create an alias to a framework-provided package this does not appear to work.

In particular, in a .NET 5 web application I add
```
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" Aliases="logging" />
```
but `extern alias logging;` does not compile:
```
error CS0430: Der externe Alias "logging" wurde nicht in einer /reference-Option angegeben.
```
If I instead do it in a console application it indeed does work.

Using VS 2019 Update 9 Preview 2

**Comment by JonDouglas** [comment]
Hi @weltkante,

Thanks for the report!

Can you please provide us a sample project or reproducible steps to help us debug this further?

Feel free to refer to our section on [bug reports](https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions#bug-reports) for more information on what we're looking for!

**Comment by weltkante** [comment]
Sure, the reproduction steps are literally just what I said above, adding a `PackageReference` to a framework package and a corresponding `extern alias` statement. I'm adding a full example below, changing the SDK to `Microsoft.NET.Sdk` (i.e. removing the `Web`) makes things compile but obviously I'm then missing a lot of implicit behavior of the Web SDK, both in implicit package references and project system behavior.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" Aliases="logging" />
  </ItemGroup>
</Project>
```

```csharp
extern alias logging;

using System;

namespace PackageAlias
{
    public class Helper
    {
        public void MethodWithLogger(logging::Microsoft.Extensions.Logging.ILogger logger)
        {
        }
    }
}

```

```
Program.cs(1,14,1,21): error CS0430: The extern alias 'logging' was not specified in a /reference option
Program.cs(9,47,9,56): error CS0234: The type or namespace name 'Microsoft' does not exist in the namespace 'logging' (are you missing an assembly reference?)
```

**Comment by JonDouglas** [comment]
@weltkante Thank you kindly! We'll look into this shortly in our next triaging session. Thanks for the clarification on the .csproj items!

**Comment by aortiz-msft** [comment]
This issue was moved to dotnet/sdk#15443
