### ISSUE TITLE
Using 'dotnet nuget push' to local source also push source code

### ISSUE THREAD

**Issue by alexandrejobin** [NuGet/Home#10447]
I have a shared folder on my network where a publish my private packages. I use the command `dotnet nuget push package_name.nupkg --source c:\temp\packages` and it push the `nupkg` file but also all is source code in the `content` folder:

![image](https://user-images.githubusercontent.com/865002/104196248-8cd62400-53f1-11eb-90db-bd55a6a2e1e9.png)

Why does the source code included in the nuget push command? Is it possible to tell the command to only push the nupkg file? The only way I've found to only publish the nupkg is by downloading `nuget.exe` and use the command `nuget.exe add package_name.nupkg -src c:\temp\packages`.

nuget version 5.8.0.6930
dotnet version 5.0.100
OS win10 v1809

**Comment by aortiz-msft** [comment]
Does the nupkg include a content folder? Would you mind adding a screenshot of the contents of the nupkg?

**Comment by alexandrejobin** [comment]
Yes my package have a content folder:
![image](https://user-images.githubusercontent.com/865002/105512256-def33100-5c9e-11eb-8882-20d9c541a5c4.png)

Also, another package have a lib folder that gets deployed on my nuget share folder:
![image](https://user-images.githubusercontent.com/865002/105512089-b0755600-5c9e-11eb-8be0-8c754190bf21.png)

**Comment by nkolev92** [comment]
Hey @alexandrejobin 

When pushing to a local feed(hierarchical), NuGet will *extract* the package that's being pushed. Given that your package has a content folder, it is extracted on disk. 

Everything happening here is by design.

**Comment by alexandrejobin** [comment]
@nkolev92, thank you for the info. Is it possible to know the utility to have the package extracted when pushing it to a local hierarchical feed? Just for my knowledge. I guest I will have to use the nuget.exe to prevent this behavior for now on.
