### ISSUE TITLE
Improve the error message of nuget.exe install, when -version is not found

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1044]
c:\school>NuGet.exe install EntityFramework -version 8.0.0
Attempting to gather dependencies information for package 'EntityFramework.8.0.0
' with respect to project 'c:\school', targeting 'Any,Version=v0.0'
Package 'EntityFramework' is not found

We can improve the error message by mentioning that the version does not exist. Now it seems like EntityFramework id does not exist.

**Comment by RanjiniM** [comment]
Fixed.

**Comment by deepakaravindr** [comment]
I have verified that this bug has been fixed correctly.
