### ISSUE TITLE
Uninstalled NuGet packages remain in the Visual Studio solution explorer

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#10442]
## Details about Problem

Product: Visual Studio

NuGet version: 5.9.0.7005

VS version: 16.9.0 preview 3 (30907.6 main)

Worked before? Yes

Works fine in Visual Studio 16.9.0 preview 2 with NuGet 5.9.0.6967.

## Detailed repro steps so we can see the same problem

1. Install a package to a project through any means (PMC or UI)
2. Uninstall a package to a project through any means (PMC or UI)
3. Check dependencies folder for project in the solution explorer and notice that uninstalled packages haven't been removed there even though they have been successfully removed from the project and assets file.

![image](https://user-images.githubusercontent.com/15097183/104070881-e9f58e00-51d5-11eb-83cb-1ad7c762975a.png)

**Comment by heng-liu** [comment]
I could repro. But if I reopen the solution, the nodes will be removed as expected.
Is this by design, or we should work with project-system team to fix that?

**Comment by chrisraygill** [comment]
I can't imagine it's by design as I don't see any potential customer benefit unless maybe it's a result of some perf optimization. I think we should work with project-system to get a fix 😊

**Comment by aortiz-msft** [comment]
This issue was moved to dotnet/project-system#6853
