### ISSUE TITLE
The deprecated icon overlaps with the version of the deprecated package in Browse tab

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10452]
## Details about Problem
VS Version: Main\30912.243
NuGet Version : Dev\5.9.0.7028
OS Version: Windows-10-Enterprise-19H2
## Installation
1. Install VS Main\30912.243: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4366886&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Dev\5.9.0.7028: \\\ddfiles\drops\NuGet\Drops\CI\NuGet.Client\Dev\5.9.0.7028\artifacts\VS15\NuGet.Tools.vsix
## Repro steps 
1. Create a C# Class Library (.Net Framework) project.
2. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json
3. Open PM UI, select the above deprecated package source and search package “afine” in Browse tab.
## Expected
The deprecated icon should not overlap with the version of the deprecated package as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/104419106-f3ef0680-55b2-11eb-8a9c-2b3b4c28d127.png)
## Actual
The deprecated icon overlaps with the version of the deprecated package in Browse tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/104419141-00735f00-55b3-11eb-956f-46da894fcd7f.png)
## Notes
1. The issue also reproes on C# Console App (.Net Core) project.
2. The issue does not repro after installing the deprecated package.
3. The issue starts from Dev\5.9.0.7028.

**Comment by donnie-msft** [comment]
I found specifically that it's only when no "latest version" is shown on the right that this problem occurs:

![image](https://user-images.githubusercontent.com/49205731/104481034-47e9f300-5593-11eb-8158-54d2e07528d1.png)

**Comment by chrisraygill** [comment]
@donnie-msft 

I played around with it a bit more. The overlap only happens when the package is installed, regardless of if "latest version" is shown on the right side.

![image](https://user-images.githubusercontent.com/15097183/104484797-b2049700-5597-11eb-9104-47c024ecc465.png)
