### ISSUE TITLE
Missing format default on `nuget list source`

### ISSUE THREAD

**Issue by quasarea** [NuGet/Home#10457]
Similar to https://github.com/NuGet/Home/issues/9337, it seems issue reemerged recently.

## Details about Problem
When calling 
```
nuget sources list
```
error is thrown, instead of using detailed as default like it was in previous versions.
```
invalid value for --format: None. Allowed values: 'detailed' or 'short'
```

Product version: 
NuGet Version: 5.8.1 (installed by azdo nuget installer task) - throws 

Worked before? If so, with which NuGet version: 
NuGet Version: 5.7.0.6726 (commandline version) - works as expected

**Comment by erdembayar** [comment]
@quasarea 
Can you give us repro steps? Did you change anything nuget.config file? 
I downloaded nuget.exe (v 5.8.1) and everything seems working fine.

**Comment by zkat** [comment]
@quasarea we've gotten no response on this in 14 days, so I'm gonna go ahead and close this. If you're able to put together a set of repro steps for us in the future, please feel free to file a new issue.
