### ISSUE TITLE
Don't offer upgrade of assemblies to v5 for .Net Core 3 targetted projects

### ISSUE THREAD

**Issue by sonic1981** [NuGet/Home#10455]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 16.8.3

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
```
Nuget offers an upgrade of the package `Microsoft.Extensions.Logging.Abstractions` to version `5.0.0` for the above. If you complete this upgrade you get errors running this project. This can be extremely difficult to diagnose as this assembly could be heavily nested. No build failures occur you only see the issue when the DI runs. 

The error you get is the cryptic:

>Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger

I don't think Nuget should be recommending upgrade of .Net Core 3.x dlls to v5 in none compatible projects?

**Comment by heng-liu** [comment]
Hi, if you download the `Microsoft.Extensions.Logging.Abstractions` package for both v3.1.11 and v5.0.0 and check the lib folder,
you'll find the dlls are in netstand2.0 folder (v5.0.0 has an extra net461 folder, but netcoreapp3.1 project won't use that one as it's not compatible). 
NuGet finds dll for closest compatible TFM, and the [tool](https://nugettoolsdev.azurewebsites.net/5.8.0/get-nearest-framework?project=netcoreapp3.1&package=netstandard2.0) shows the netstandard2.0 dll is compatible with netcoreapp3.1, so the dll under lib/netstandard2.0 will be used no matter the package version is v3.1.11 or 5.0.0.
Please refer to [Matching assembly versions and the target framework in a project](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#matching-assembly-versions-and-the-target-framework-in-a-project) for more details.
So it doesn't look like a compatibility problem. 
You may check if there is any breaking change in this package.
