### ISSUE TITLE
"Unable to find package" error but nupkg exists in in repository and locally

### ISSUE THREAD

**Issue by olivegamestudio** [NuGet/Home#10454]
## Details about Problem

Visual Studio 16.8.4 and the NUGET Package Manager UI

## Repro steps and/or sample project

Select solution and NUGET solution update.
Goto updates and see update for own package listed. e.g. 3.0.7 with an upgrade to 3.0.8 showing.
Checkbox and update.

## Output

Restoring packages for C:\dev\X.csproj...
  GET https://api.nuget.org/v3-flatcontainer/mypackage/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/mypackage/index.json 443ms
**NU1102: Unable to find package mypackage with version (>= 3.0.8)**
  - Found 4 version(s) in local [ Nearest version: 3.0.7 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
  - Found 0 version(s) in nuget.org
Package restore failed. Rolling back package changes for 'Project'.
Time Elapsed: 00:00:00.8883385
========== Finished ==========

But 3.0.8 is present in the c:\nugetlocal folder and being shown in the display.

Looking in the nuget package cache. The cache updates with the right version when update is pressed. The DLL is present in the netXX folder too.

C:\Users\name\.nuget\packages\mypackage\3.0.8\lib\net46

**Comment by dominoFire** [comment]
@olivegamestudio Can you submit your ticket via VS Feedback? We need some info that the VS Feedback tool collect to better diagnose your issue.

![image](https://user-images.githubusercontent.com/1192347/105772049-757d5780-5f16-11eb-9c1f-50515c99a151.png)
