### ISSUE TITLE
Support nuget.exe install project.json

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1045]
we support nuget.exe install packages.config. 

Since now there are project.json files in certain projects, we may need to add support for nuget.exe install project.json

**Comment by deepakaravindr** [comment]
IMO, we should not support this. The only reason we support 'nuget.exe install packages.config' is for legacy reasons and 'nuget.exe restore packages.config' is the right thing to do. If we had a 'nuget.exe install project.json', it would do exactly what 'nuget.exe restore project.json' will do. Not sure why we will have 2 commands for this

**Comment by deepakaravindr** [comment]
We will show a friendly error message

**Comment by yishaigalatzer** [comment]
Agreed that we want a nice error message sending you to call restore

**Comment by nkolev92** [comment]
Redundant now. 
We will not do this, as we want to eventually kill the install command.
