### ISSUE TITLE
Nuget Package does not copy content to output directory

### ISSUE THREAD

**Issue by MansMarius-Intenda** [NuGet/Home#10465]
I'm using a nuspec file to build the package BOS.Shell and reference it from the UI.Warehouse project.

As can be seen, the target is a class library Package Reference project on Framework 4.7.2.

When I build the project I expect the CONTENT FILES to be copied to the output directory, but it does not ?

The binary files works as expected.

NuGet Version: 5.8.0.6930

![image](https://user-images.githubusercontent.com/70512064/105013843-58451680-5a48-11eb-9353-926d56f3b46a.png)

![image](https://user-images.githubusercontent.com/70512064/105005828-7dcd2280-5a3e-11eb-89b1-66c5472349e5.png)

**Comment by dominoFire** [comment]
Have you tried a folder convention-based approach to create BOS.Shell package? That way, you don't need to specify the assemblies as content files. More info at https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

**Comment by MansMarius-Intenda** [comment]
The binary files (dll's) works as expected, it is the other (content) files that is the issue.

So in other words, I need to deploy non binary files in the OUTPUT directory of the target project of my NuGet package, when the target project is a .net FRAMEWORK class library using Package Reference.
Thanks

**Comment by MansMarius-Intenda** [comment]
Ok, got it fixed thanks

https://stackoverflow.com/questions/65803903/nuget-package-does-not-copy-content-to-output-directory?noredirect=1#comment116347149_65803903
