### ISSUE TITLE
Implementation - Add new telemetries to track events related to PMC and Powershell usage follow up.

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10478]
For [issue#10142](https://github.com/NuGet/Home/issues/10142) I received PR reviews right after I merged my [PR#3755](https://github.com/NuGet/NuGet.Client/pull/3755).
Address 2 comments left by @nkolev92 (https://github.com/NuGet/NuGet.Client/pull/3755#discussion_r562995245
https://github.com/NuGet/NuGet.Client/pull/3755#discussion_r562995592)

**Comment by nkolev92** [comment]
This issue did *not* get closed because the template was used incorrectly. 

Note that you need to just paste the link, GH will render everything else 

So it needs to be `Fixes: https://github.com/NuGet/Home/issues/10478` which renders to Fixes https://github.com/NuGet/Home/issues/10478
