### ISSUE TITLE
Problem when pushing via .Net 5 SDK docker image 

### ISSUE THREAD

**Issue by ghominejad** [NuGet/Home#10472]
## Details about Problem
When I push the package locally or via .Net 3.1 SDK docker image, everything woks fine but via  .Net 5 SDK docker image it has source parameter error, while I've set the source parameter.

**Product version:**
 mcr.microsoft.com/dotnet/sdk:5.0-buster-slim

## Repro steps and/or sample project

$ dotnet nuget push **/*.nupkg -k $NugetToken -s https://api.nuget.org/v3/index.json --skip-duplicate -n 1

### Verbose Logs

`
Pulling docker image **mcr.microsoft.com/dotnet/sdk:5.0-buster-slim** ...

$ dotnet pack src/Gita.Infrastructure

Successfully created package '/builds/Infrastructure/bin/Debug/**Infrastructure.5.0.0.nupkg**'

dotnet nuget push **/*.nupkg -k $NugetToken -s https://api.nuget.org/v3/index.json --skip-duplicate -n 1

**error: Source parameter was not specified.**

`

**Comment by dominoFire** [comment]
Reproduced with following steps:

Run a 'terminal' inside the image:

```bash
docker run -it mcr.microsoft.com/dotnet/sdk:5.0-buster-slim /bin/bash
```

Then, run your push command

```bash
dotnet nuget push *.nupkg -k $tok -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
```

If that's the case, then, there's some parameter clashing when you're invoking docker and the nuget push command at the same time.

**Comment by ghominejad** [comment]
I thinks that was Gitlab's fault. I pushed to the master branch and the error has gone!  :/

Do you know the reason of this strange behavior?

**Comment by zkat** [comment]
No idea. But glad it's resolved! :)
