### ISSUE TITLE
NuGet.Client code calls string.Replace and ignores the return value

### ISSUE THREAD

**Issue by omajid** [NuGet/Home#10477]
## Details about Problem

NuGet.Client's `src/NuGet.Core/NuGet.PackageManagement/Utility/PackagesConfigLockFileUtility.cs` calls `string.Replace` and doesn't do anything with the return value.

```csharp
if (Path.DirectorySeparatorChar != '/')
{
    lockFileRelativePath.Replace('/', Path.DirectorySeparatorChar);
}
```

`string.Replace` doesn't modify the instance; it returns a new string. We should either store the returned value somewhere, or not call `string.Replace` at all.

Product version: 

Worked before? Not sure.

## Repro steps and/or sample project

Please see the source code.

### Verbose Logs

**Comment by jebriede** [comment]
Thanks for reporting this issue! This was addressed with the following PR: https://github.com/NuGet/NuGet.Client/pull/4178
