### ISSUE TITLE
NuGet.exe pack does not work for dev14 F# project 

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#1048]
Repro Step:
1. create a F# project in Visual Studio 2015.
2. nuget.exe pack example.fsproj

Expect: pack the project into nupkg.
Actual: Got build error from msbuild.

Looks like pack command always use old msbuild version to build project, msbuild 14 works well for this and msbuild 12 ran into same error.

Error Message: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.

**Comment by feiling** [comment]
Fixed
