### ISSUE TITLE
Why condition is ignored under PackageReference with non-sdk net framework project

### ISSUE THREAD

**Issue by Perry004** [NuGet/Home#10495]
I have  a non-sdk `net framework 4.8` project. And I have installed a nuget package `Newtonsoft.Json` with **PackageReference**.

When I used a custom condition under it like this:

```
<PropertyGroup>
    <Test>13</Test>
 </PropertyGroup>

<PackageReference Include="Newtonsoft.Json" Condition="'$(Test)'=='11'">
    <Version>12.0.3</Version>
</PackageReference>
```

or 

```
<ItemGroup Condition="'$(Test)'=='11'">
    <PackageReference Include="Newtonsoft.Json">
        <Version>12.0.3</Version>
    </PackageReference>
</ItemGroup>

```

Then, I restore under VS IDE, then build the project, the Package is still there and why this happens? I make the condition to `false`.

As a test, I restore,build under MSBuild Command line, then it works well. 

**It seems that VS IDE restore has some errors and cannot recognize the condition.**

Also, I found that the issue only happens on the non-sdk project with **PackageReference** and new-sdk projects do not have it.

I know the `choose, when`  can work, but I do not want to use it. I want to use the traditional item condition.

So please fix the issue. And I am not the only one who faced the issue. And it bothers our work.

**Comment by nkolev92** [comment]
Hey @Perry004 

This is a bug in the project-system that deals with older style projects. 

The bug was tracked here, https://github.com/dotnet/project-system/issues/4175, but unfortunately the project-system team as of this time has determined that the risks are too high to consider fixing right now.
