### ISSUE TITLE
I changed my ReposityPath in nuget.config to point to another folder but still downloads the packages in the .nuget folder.

### ISSUE THREAD

**Issue by justinjalandoniiwest** [NuGet/Home#10490]
Here is my xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositoryPath" value="D:\dotNet\nuget-packages" />
    </config>
</configuration>
```

The nuget packages are still being downloaded to the .nuget folder in my %USERPROFILE%.
How do I fix this? Right now as a workaround I just transfer the packages to the other drive manually.

**Comment by snthomae** [comment]
Are you using PackageReference or package.config?
If you use PackageReference, you should use globalPackagesFolder (see https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)

Also I would add a <clear /> tag before add key to prevent that settings from previous NuGet.Config gets loaded.

**Comment by nkolev92** [comment]
@snthomae is correct. 

If you are using PackageReference, you need to specify the global packages folder.

https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders

**Comment by justin-jalandoni** [comment]
> Also I would add a tag before add key to prevent that settings from previous NuGet.Config gets loaded.

What tag is this?
