### ISSUE TITLE
Update context menu should scroll to first selected item

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10498]
When I select "Update..." on NUnit in solution explorer, I am taken to PMUI to the top of the packages list.

I don't see the package because it's far down in the list...
Let's scroll down to the first item in the selection (eg, NUnit).

![image](https://user-images.githubusercontent.com/49205731/106197873-356ddd00-6181-11eb-9304-c4ae0bc16947.png)

/cc @jebriede thoughts?

**Comment by jebriede** [comment]
@donnie-msft this is a really good catch. I think it can be confusing if there are a lot of packages and the one that's selected isn't in focus in the list. I would propose we also highlight (list item selection) the first package in the list of selected packages (if there's more than one) so the details are populated on the right and then bring the selected item in focus.
