### ISSUE TITLE
dotnet build inside CI container fails with NU3028 and NU3037

### ISSUE THREAD

**Issue by svdHero** [NuGet/Home#10492]
NuGet product used:
dotnet.exe

Product version (as by `dotnet --version`):
5.0.102 inside container [mcr.microsoft.com/dotnet/sdk:5.0](https://hub.docker.com/_/microsoft-dotnet-sdk/)

# Problem description
We have a Jenkins CI server on Ubuntu Server 20.04 LTS which builds our ASP.NET Web API inside a [mcr.microsoft.com/dotnet/sdk:5.0](https://hub.docker.com/_/microsoft-dotnet-sdk/) container. Everything has worked fine until this morning when suddenly the build pipeline fails with hundreds of errors of the kind
```
/MyWorkspace/MyProject/MyProject.csproj : error NU3028: Package 'Microsoft.AspNetCore.Mvc.NewtonsoftJson 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/MyWorkspace/MyProject/MyProject.csproj : error NU3037: Package 'Microsoft.AspNetCore.Mvc.NewtonsoftJson 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
```

What's the problem here? As far as I know we have not changed anything on our CI machine and the build job still pulls the same container image [mcr.microsoft.com/dotnet/sdk:5.0](https://hub.docker.com/_/microsoft-dotnet-sdk/) for building as always.

**Comment by dasMulli** [comment]
Just opened https://github.com/NuGet/Home/issues/10491 for that

**Comment by svdHero** [comment]
@dasMulli Danke schön für den Hinweis. :wink:

**Comment by svdHero** [comment]
Closed as dublicate.
