### ISSUE TITLE
[nuget.exe] Restore fails for project.json based projects when the path contains spaces

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1049]
Steps
1. Create a new solution with a UWP project.json based project
2. Copy the solution to a folder with spaces in the path
3. cd to the solution folder
4. nuget.exe restore

Expected
Everything should be restored

Actual:
MSBuild errors out since the paths is not escaped
Error code: MSB1008

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/3c827106668ff450c872b6c6f1a1bbc35daa6ddc
