### ISSUE TITLE
Why condition is ignored under multi-targetframeworks with new-sdk project

### ISSUE THREAD

**Issue by Perry004** [NuGet/Home#10501]
I have a wpf net core project. And this is my csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" Condition="'$(TargetFramework)' == 'net5.0-windows'" />
		<PackageReference Include="Newtonsoft.Json" Version="11.0.1" />
	</ItemGroup>

</Project>
```

As you saw, I used  `TargetFrameworks` but however I have a condition to distinguish between them. And why `net5.0-windows` still shows `11.0.1`.

![B38d35b3e5da9474d9d43a255d3ffd726637475022232735710_20210129-153021-image](https://user-images.githubusercontent.com/52026687/106245790-066e6e80-6248-11eb-9cb1-4af9122aea17.png)

I know I can use choose,when to make them work but I still want the traditional `item condition`.

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
   <PropertyGroup>
     <OutputType>WinExe</OutputType>
     <TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
     <UseWPF>true</UseWPF>
   </PropertyGroup>
    
     <Choose>
         <When Condition="'$(TargetFramework)' == 'net5.0-windows'">
             <ItemGroup>
                 <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
             </ItemGroup>
         </When>
         <Otherwise>
             <ItemGroup>
                 <PackageReference Include="Newtonsoft.Json" Version="11.0.1" />
             </ItemGroup>
         </Otherwise>
     </Choose>
 </Project>
```

Also, when I used `nuget restore`, `dotnet restore`, `msbuild -t:restore`, all works well and can show the two different features. 

![image](https://user-images.githubusercontent.com/52026687/106245735-ed65bd80-6247-11eb-80d7-14ee91f91d4b.png)

So why VS IDE restore is different , and should not they keep the same?

I think **VS IDE Restore** has some errors.

**Comment by Perry004** [comment]
I want use the first code. And I can also use this to work.

`<PackageReference Include="Newtonsoft.Json" Version="11.0.1" /> <PackageReference Include="Newtonsoft.Json" Version="12.0.3" Condition="'$(TargetFramework)' == 'net5.0-windows'" />`

What I found is that, when I uses **dotnet restore,nuget restore… command line** to restore, the project will only get the first PackageReference include item version and use it:

![29nFi](https://user-images.githubusercontent.com/52026687/106432607-eb029e00-64a9-11eb-8dd5-41d0e0a39d55.png)


But while I used **VS IDE Restore**, it uses the last PackageReference include item version to work.

![image](https://user-images.githubusercontent.com/52026687/106432677-02418b80-64aa-11eb-8255-41059ebfcef3.png)


For **net5.0-windows**, its PackageReference include order: first `11.0.1`, then `12.0.3`.
For **netcoreapp3.1**, its PackageReference inlcude order: `11.0.1`.

Use **VS IDE Restore**, pick the last one: net5.0-windows uses 12.0.3 while netcoreapp3.1 uses `11.0.1`.

Use **Dotnet Restore** Command, pick the first one: net5.0-windows uses 11.0.1 while netcoreapp3.1 uses `11.0.1`.

So I wonder why this is different and why they have a different behavior for each other.

**Comment by nkolev92** [comment]
Hey @Perry004, 

The duplicate handling inconsistency is documented here, https://github.com/NuGet/Home/issues/9864. 

Note that our recommendation would be to include an *item once*!

In the mean time consider one of the following:

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="11.0.1" Condition="'$(TargetFramework)' == 'netcoreapp3.1'"/>
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" Condition="'$(TargetFramework)' == 'net5.0-windows'" />
	</ItemGroup>

</Project>
```

or 

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>netcoreapp3.1;net5.0-windows</TargetFrameworks>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="11.0.1" />
		<PackageReference Update="Newtonsoft.Json" Version="12.0.3" Condition="'$(TargetFramework)' == 'net5.0-windows'" />
	</ItemGroup>

</Project>
```

**Comment by Perry004** [comment]
Your suggestion is actually a copy of `choose, when` which I said before  that I know it and did not want to use. What I am curious is that the different behaviors of the multiple packagereferene include between ide restore, command restore. So I want you could fix it and I do not  want this divergence to grow and affect the rest of the development.
