### ISSUE TITLE
NuGet.CommandLine.Test: MockServer used in functional tests should use unused port

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1050]
NuGet.CommandLine.Test: MockServer used in functional tests should use unused port. Currently, the tests are using non-conflicting ports in order to run in parallel

**Comment by yishaigalatzer** [comment]
Please work with me on this. We built a similar mechanism in Web Stack Runtime - http://aspnetwebstack.codeplex.com/ to assign ports dynamically and coordinate across processes/threads instead of specifying ports manually

**Comment by MeniZalzman** [comment]
Check-in the fix to dev branch
