### ISSUE TITLE
NuGet Restore error - Response status code does not indicate success: 401 (Unauthorized) - Azure DevOps NuGet Feed

### ISSUE THREAD

**Issue by ledjon-behluli** [NuGet/Home#10502]
## Details about Problem

NuGet product used (Visual Studio 2019):

Product version: 16.8.3

## Issue

When trying to build a project in Visual Studio, it fails while trying to restore the packages from our internal Azure Artifacts NuGet store (hosted in Azure DevOps). Directly accessing the Azure Artifacts URL worked without a problem, but when I trying to do this through Visual Studio it fails with the error below.

This usually happens when there is an account credentials change, used to sign into VS.

Re-entering the credentials into visual studio sometimes fixes the issues, sometimes it doesn't (_Couldn't find a pattern_).

### Output Error

```
C:\Program Files\dotnet\sdk\3.1.11\NuGet.targets(123,5): error : Failed to retrieve information about 'MyProject.MyNugetPackage' from remote source 'https://pkgs.dev.azure.com/MyOrganizationName/MyProjectName/_packaging/MyNugetFeedName/nuget/v3/index.json'. [C:\Projects\MyProject\Project.sln]

C:\Program Files\dotnet\sdk\3.1.11\NuGet.targets(123,5): error : Response status code does not indicate success: 401 (Unauthorized). [C:\Projects\MyProject\Project.sln]
```

### Workaround on Windows 10

- Open the search bar in windows and search for Credentials Manager.
- In the Credential Manager go to ‘Windows Credentials’.
- Scroll to the list of Generic Credentials.
  - Click on the 'vscredentials' and click on Remove.
  - Click on the 'azureAccountProviderCredetials|azure TokenCache_azure_public...' and click on Remove.
- Re-enter credentials in VS and now it works again.

### Suggestion

Although this issue doesn't happen all the time, and a simple sign out/in work, sometimes it does happen and I have to apply the above 'hack'. It would be nice if this issue can be resolved only with a sign out/in.

**Comment by nkolev92** [comment]
Hey @ledjon-behluli, 

Given that these are the Visual Studio log-in (NuGet just piggybacks off of that), I'd like to recommend you file the issue on developer community. 

https://developercommunity2.visualstudio.com/report?entry=problem&space=8. 

Unfortunately I don't have the ability to move it from here.

**Comment by ledjon-behluli** [comment]
> Hey @ledjon-behluli,
> 
> Given that these are the Visual Studio log-in (NuGet just piggybacks off of that), I'd like to recommend you file the issue on developer community.
> 
> https://developercommunity2.visualstudio.com/report?entry=problem&space=8.
> 
> Unfortunately I don't have the ability to move it from here.

Created the issue in developer community: 
https://developercommunity.visualstudio.com/content/problem/1331519/nuget-restore-error-response-status-code-does-not.html
