### ISSUE TITLE
`nuget pack` for a nuspec is ignoring some of the `<files>` listed in the nuspec

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#10506]
## Details about Problem

nuget.exe 

Product version: 5.8.0.6930

Worked before? If so, with which NuGet version: 4.9.4. but with a different codebase

## Repro steps and/or sample project
Here is the nuspec...

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>DataService.Client</id>
    <version>0.1.0</version>
    <title>DataService.Client</title>
    <authors>ME</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description><redacted/></description>
    <tags>DataService Client</tags>
    <dependencies>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="Newtonsoft.Json" version="12.0.3" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.1">
        <frameworkReference name="Microsoft.AspNetCore.App" />
      </group>
    </frameworkReferences>
  </metadata>
  <files>
    <file src="bin\Release\netcoreapp3.1\DataService.Client.*" target="lib\netcoreapp3.1" />
    <file src="bin\Release\netcoreapp3.1\DataService.Library.*" target="lib\netcoreapp3.1" />
<!-- trimmed for brevity -->
  </files>
</package>
```
Here are the files...
![image](https://user-images.githubusercontent.com/15381181/106393949-ebc30380-63c7-11eb-8702-fba992e72098.png)

`nuget pack` is being run from the project folder, after I have executed a build of the solution in Release configuration to produce the files.  The package and the verbose logs are missing the `DataServiceLibrary.dll` that is named in the `<files>` element (and others). The file is present in the directory and there is no warning indicating that nuget.exe is unable to locate it, it appears to not even look for it. 

Using and maintaining a nuspec here is not the first choice, but is the one workaround to all of the existing problems with using dotnet auto pack that I have had to use before, but now it is no longer working as well.   I need to be able to pack the files I specify without any overrides or automatic inference or other interference.  How can that be done so that I can be unblocked?

_all of the logs and examples have been redacted, please dont be pedantic about typos related to that_

### Verbose Logs

``` powershell
PS C:\Users\Andrew.Stanton\source\repos\DataService.Client> nuget pack .\DataService.Client.nuspec -version "0.1.$((Get-Date).ToFileTime().ToString().Substring(7,9))" -verbosity detailed
NuGet Version: 5.8.0.6930
Attempting to build package from 'DataService.Client.nuspec'.

Id: DataService.Client
Version: 0.1.954964771
Authors: ME
Description: <redacted>

Tags: DataService, Client
Dependencies: Newtonsoft.Json [12.0.3, )

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'DataService.Client.nuspec'.
Added file 'lib/netcoreapp3.1/DataService.Client.deps.json'.
Added file 'lib/netcoreapp3.1/DataService.Client.dll'.
Added file 'lib/netcoreapp3.1/DataService.Client.xml'.
Added file 'package/services/metadata/core-properties/282f1640516f4eb38e0b4fefe6c2bdca.psmdcp'.
```

**Comment by nkolev92** [comment]
Hey @StingyJack 

There's a typo in the nuspec (or the project that builds the library assembly). 

>     <file src="bin\Release\netcoreapp3.1\DataService.Library.*" target="lib\netcoreapp3.1" />

The globbing is

> DataService.Library.*

while the file in the screenshot is 

> DataServiceLibrary.dll

Can you please double check that?

**Comment by StingyJack** [comment]
Yep, that subtle naming change was one I pulled in after I had started creating the package. Good eye there, thanks!

**Comment by nkolev92** [comment]
Do you still have a problem or can we close this?

**Comment by StingyJack** [comment]
Sorry meant to close it when commenting yesterday
