### ISSUE TITLE
[High-DPI] No border lines on the right and bottom after a DPI change

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#10508]
## Details about Problem

NuGet version: NuGet Client Dev\5.9.0.7088
VS Version: Main\30931.09 
OS Version: Windows-10-Enterprise-20h1

## Repro steps 

1. Open Visual Studio.
2. Turn on DPI awareness feature in VS:
![image](https://user-images.githubusercontent.com/71433406/106445047-818a8b80-64b9-11eb-8054-74e5e38d391c.png)
3. Change the Scale and layout in Settings->Display.
4. Open Tools->Options.

## Expected
There are border lines on the right and bottom.

## Actual
No border lines on the right and bottom.
![image](https://user-images.githubusercontent.com/71433406/106445191-abdc4900-64b9-11eb-972c-f49c41efdfaa.png)

**Comment by aortiz-msft** [comment]
@v-crchang Did you restart the app as per the instructions in the highlighted checkbox above?

**Comment by v-crchang** [comment]
@aortiz-msft Yes, this issue reproes after restarting the VS with the highlighted checkbox above checked.

**Comment by v-crchang** [comment]
I'm closing this issue because it didn't reproduce on main\31008.155.

**Comment by v-crchang** [comment]
I'm closing this issue because it didn't reproduce on main\31008.155.
