### ISSUE TITLE
[High-DPI]The text is normally crisp at 100% is not rendering crisp after a DPI change

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#10507]
## Details about Problem
NuGet version: NuGet Client Dev\5.9.0.7088
VS Version: Main\30931.09 
OS Version: Windows-10-Enterprise-20h1
## Repro steps 
1. Open Visual Studio.
2. Turn on DPI awareness feature in VS:
![image](https://user-images.githubusercontent.com/71433406/106443172-25bf0300-64b7-11eb-837f-7efbf4053ea0.png)
3. Change the Scale and layout of Screen1 to 125% in Settings->Display, do nothing to the Screen2 (100%).
4. Move VS from the Screen1 to Screen2.

## Expected

The text is crisp.

## Actual

The text is not rendering crisp after a DPI change.
![image](https://user-images.githubusercontent.com/71433406/106443360-5acb5580-64b7-11eb-941e-167c119d25d6.png)

**Comment by aortiz-msft** [comment]
@v-crchang Did you restart the app as per the instructions in the highlighted checkbox above?

**Comment by v-crchang** [comment]
@aortiz-msft Yes, this issue reproes after restarting the VS with the highlighted checkbox above checked.

**Comment by donnie-msft** [comment]
I just found fuzzy text in the Find Symbols Results, I also use "optimize rendering" setting.
Seems like possibly a 16.10 VS issue or possibly a Windows bug?
![image](https://user-images.githubusercontent.com/49205731/106660212-b5bf8400-656d-11eb-87fe-45f5df6a02a2.png)

**Comment by v-crchang** [comment]
I'm closing this issue because it didn't reproduce on main\31008.155.
