### ISSUE TITLE
Nuget package settings not loading

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10518]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Nuget-package-settings-not-loading/1323354)._

---
[severity:I'm unable to use this version] [regression]
Nuget Packages are not loading and as a result, code fails in multiple places due to missing dependencies. Screenshot attached
! [Capture.JPG] (https://aka.ms/dc/image?name=B939aaa4f496a497e96df0fde6de916f6637474152987393416_Capture.JPG&tid=939aaa4f496a497e96df0fde6de916f6637474152987393416)
! [Capture2.JPG] (https://aka.ms/dc/image?name=Bb39fb8dbc0a94205959a39622da3d867637474153424590088_Capture2.JPG&tid=b39fb8dbc0a94205959a39622da3d867637474153424590088)
! [Capture3.JPG] (https://aka.ms/dc/image?name=Bd0accdf6fd4a407abb7f6a11c843844f637474154204567869_Capture3.JPG&tid=d0accdf6fd4a407abb7f6a11c843844f637474154204567869)

---
#### Feedback Bot on 1/28/2021, 00:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
The failure occurs when there's a config with an empty password field. 

Example:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="mySource" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <mySource>
        <add key="Username" value="stuff" />
        <add key="Password" value="AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAA/fyAqwdFZ0CjjlL11D4gYwAAAAACAAAAAAAQZgAAAAEAACAAAABv8+MbRSvvPhHS9lbcA9GQcz2ygxibFPdcypIpZIEcowAAAAAOgAAAAAIAACAAAABk1S26gN8T9theEn7//lkDFoc01svjXU3icdlZe2dbyBAAAADms9h6cXntQhc3+HVFaPULQAAAAOtl+2CnbtHXFNFK1sjz6OcWRluD43HZWQOHYSeKyYYlqqsle0FBCnl7KMUvKJyUaZRZNNBkCv6QELCpnKOOe3w=" />
      </mySource>
  </packageSourceCredentials>
</configuration>
```

**Comment by nkolev92** [comment]
Note that while this issue was reported for the VS experience, you will see an exception if you try to restore on the commandline.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/7897
