### ISSUE TITLE
Fine-tuning the output of a dev-dependency nuget package reference

### ISSUE THREAD

**Issue by odalet** [NuGet/Home#10512]
## Details about Problem

* Using: Visual Studio 2019 v16.8.3 Nuget Window.

I've noticed that whenever I add a "dev-only" Nuget package to a project, it is rendered this way in the target csproj (using GitVersion.MsBuild as an example, but seems to be the case for all dev-only packages I'm aware of):

```xml
<PackageReference Include="GitVersion.MsBuild" Version="5.6.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

There are cases where I'd rather have this (notice that 'runtime' is gone from the included assets):

```xml
<PackageReference Include="GitVersion.MsBuild" Version="5.6.4">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

I wonder if there is a means, from the nuget author perspective to obtain the latter result? I'm aware of the `<DevelopmentDependency>`, but how can one fine tune the way the nuget will be referenced in target projects?

**Comment by nkolev92** [comment]
There's currently no way to fine tune the include assets. Currently the consumer is in control of what gets included. 

Can you please provide a more detailed practical example as to why you'd want to exclude runtime assets?
If you package *does not* provide any runtime assets, then the extra metadata wouldn't do much.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
