### ISSUE TITLE
[Nuget.Versioning] NugetVersion.Parse cannot handle branch names which contain /

### ISSUE THREAD

**Issue by dschuermans** [NuGet/Home#10527]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Nuget SDK

Product version: 5.8.1

Worked before? If so, with which NuGet version: Not that i'm aware

## Repro steps and/or sample project

```
var test = NuGetVersion.Parse("1.4.0-alpha.41+Branch.develop.Sha.b9f50da6cb93ddd3008678238c9c3b9ca6709102");

Assert.IsNotNull(test);

// This fails, due to branch name "release/1.4.0". If I remove the release/ part, the parsing works just fine
var test2 = NuGetVersion.Parse("1.4.0-beta.1+0.Branch.release/1.4.0.Sha.663c042fda8ddd6ba71442f0f3ece5cf364a689e");

Assert.IsNotNull(test2);
```

### Verbose Logs

n/a

**Comment by zivkan** [comment]
@dschuermans the [semver2 spec, item 10](https://semver.org/#spec-item-10) specifies:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]

therefore `/` is not a valid character, as per the spec.

**Comment by dschuermans** [comment]
Ah, can't argue with the specs now can we? 😄 

Thanks for the clarification!
