### ISSUE TITLE
Prerelease version ordering is broken for the "Version:" dropdown in the Visual Studio PMUI Browse tab.

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#10532]
## Details about Problem

Prerelease version semantic ordering seems broken for the "Version:" dropdown in the Browse tab of the Visual Studio PMUI. It looks like it's only broken for the Browse tab, but works correctly in the Installed and Updates tabs. Semantic ordering for stable versions works fine in all tabs. The issue seems to arise for ordering based on characters that follow the "-" in a prerelease version.

## Version info

Found bug in Visual Studio 16.10.0 Preview 1.0 [31002.315].

Works in Visual Studio 16.9.0 Preview 2, but not sure what version it broke in.

## Repro steps

1. Enable "Include prerelease"
2. Search for Serilog in the PMUI Browse tab and click on it to open up package details pane
3. Realize that the latest version shown on the right side of the package search result item is different than what's shown as the "Latest prerelease" version in the "Version:" field.
4. Look through more packages with several sequential prerelease versions such as most Serilog.* package, FluentAssertions, and RestSharp.
5. Notice that in general, semantic ordering for prerelease versions is wrong in the package details pane ("Versions:" dropdown)
6. Check the Installed tab, and notice that version ordering is correct in the "Version:" dropdown, so the problem seems limited to the Browse tab.

### Images of bug in Browse tab

![image](https://user-images.githubusercontent.com/15097183/106788384-dc89c300-661e-11eb-8b50-dc52ae00f687.png)

![image](https://user-images.githubusercontent.com/15097183/106788774-66399080-661f-11eb-8e9f-2083a3c85111.png)

![image](https://user-images.githubusercontent.com/15097183/106788964-a39e1e00-661f-11eb-9028-5964a8a5bba7.png)

### Image of correct behavior in Installed tab

![image](https://user-images.githubusercontent.com/15097183/106789674-95043680-6620-11eb-9a35-6ea88c8d4094.png)

**Comment by TysonMN** [comment]
This bug is still present in version 16.9.3 of Visual Studio, which was released on March 30, 2021 (which was 10 days ago).  In which version of Visual Studio should I expect to see this fix incorporated?

**Comment by donnie-msft** [comment]
@TysonMN this will be released in 16.10 Preview 2.
