### ISSUE TITLE
Icon loading behavior is inconsistent in all tabs of the Visual Studio PMUI

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#10534]
## Problem

Icon behavior in the PMUI is inconsistent in the Browse, Installed, and Updates tabs. Sometimes an icon for a package will load in the Browse tab, but not in the Installed or Updates tab. 

In the Browse tab, sometimes icons won't appear properly for the suggested packages but will appear correctly when explicitly searched for in the Browse tab of a different project PMUI as shown by the images below. So far, I haven't found a case where a non-suggested package is missing an icon. _Most_ suggested package do show the correct icon.
![image](https://user-images.githubusercontent.com/15097183/106809422-a7d73500-6639-11eb-9c39-7fb6d60087a0.png)
![image](https://user-images.githubusercontent.com/15097183/106809534-cb9a7b00-6639-11eb-9c27-e70bfab2b08a.png)

In the Installed tab, some packages seem to never show their icon, even if the icon is shown in the Browse tab or if the package is installed to a different project. The image below shows the 16.10 internal preview on the left vs 16.9 public preview on the right.
![image](https://user-images.githubusercontent.com/15097183/106812393-9859eb00-663d-11eb-8055-1ef1608d500d.png)

Broken icon in the Installed tab does not consistently mean a broken icon in the Updates tab, but it sometimes does. Broken icons in the Updates tab are also no consistent across different projects. The images below are from different projects from the same solution in 16.10 internal preview:
![image](https://user-images.githubusercontent.com/15097183/106812883-46fe2b80-663e-11eb-907e-33d160cd3a05.png)
![image](https://user-images.githubusercontent.com/15097183/106812987-701ebc00-663e-11eb-906d-59658747cb82.png)

## Version info

**Found bug in Visual Studio 16.10.0 Preview 1.0 [31002.315].**

Works in Visual Studio 16.9.0 Preview 2, but not sure what version it broke in.

## Repro steps and/or sample project

Difficult to consistently repro, but see examples in the "Problem" section.

**Comment by aortiz-msft** [comment]
@chgill-MSFT @donnie-msft - Does this still repro in 16.10?

**Comment by donnie-msft** [comment]
Neither of us can reproduce this, so I'm closing for now.
Possibly some of rrelyea's or other's VS.OE work already fixed this.
