### ISSUE TITLE
Codespaces - Allow format selection on first package install option in VS

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10538]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 16.10.P1

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

- Connected to a repo using Codespaces
- Navigate to Tools -> Options -> NuGet Package Manager -> General
- Do we need `Allow format selection on first package install option` and `Default package management format` options, if only sdk style projects are supported?
![image](https://user-images.githubusercontent.com/52756182/106956804-fcd38380-66eb-11eb-8760-2e411e478b75.png)

**Comment by rrelyea** [comment]
since codespaces currently only supports sdk style (and no packages.config), this isn't important yet. (assuming it still works in standalone, which we believe it does).

**Comment by nkolev92** [comment]
Note that for SDK based projects you *cannot* do anything but PackageReference, so if you see that in SDK style projects, it's a bug. 
The prompt should only show up for legacy projects.

**Comment by donnie-msft** [comment]
Closing CodeSpaces issues.
