### ISSUE TITLE
NuGet.CommandLine: Platform check on PushCommand_PushToFileSystemSourceUncStyle is incorrect

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1053]
NuGet.CommandLine: Platform check on PushCommand_PushToFileSystemSourceUncStyle is incorrect. Fix this

            // UNC only works in Windows. So skip this test if we're running on Unix,
            if (Path.DirectorySeparatorChar == '/')
            {
                return;
            }

**Comment by yishaigalatzer** [comment]
@alpaix is this already fixed?

@yugangw-msft can you please touch base with @deepakaravindr & @alpaix to decide what needs to be done about this, and does it apply to your new code

**Comment by alpaix** [comment]
Not aware of this one as it's not been in my queue.

**Comment by yugangw-msft** [comment]
I pushed the change to [PR 253](https://github.com/NuGet/NuGet.Client/pull/253)
