### ISSUE TITLE
Downgrading then Updating to the original Package Version fails in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10539]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 16.9 preview 4

Worked before? If so, with which NuGet version: Standalone VS

## Repro steps and/or sample project

Seems like an assets file/timing bug with CodeSpace server...

1. Open PMUI for your .NET Core project.
2. Install a package (I used Castle.Core) to latest.
3. Downgrade the package.
4. Immediately Upgrade the package to latest again.
5. Observe a Restore error claiming the assets file did not change.
Standalone VS does not have this problem.

![image](https://user-images.githubusercontent.com/49205731/106956904-4b414c00-6705-11eb-8db6-84403980ad30.png)

6. After some time (seconds? minutes?), press Update and it works as expected.

**Comment by rrelyea** [comment]
@donnie-msft  - if this repros in standalone, we'll fix in 16.9. If this only repros in codespaces, we'll fix in 16.10. Can you clarify, please?

**Comment by rrelyea** [comment]
confirmed...standalone is ok. 16.10

**Comment by donnie-msft** [comment]
@dtivel I just tried this again and couldn't repro. 
I am realizing now when I found this, I may have not been on the latest VSIX. Possibly we can close this one if nobody else can repro...

**Comment by donnie-msft** [comment]
Logs at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1274931

**Comment by donnie-msft** [comment]
Closing CodeSpaces issues.
