### ISSUE TITLE
Codespaces - PM UI didn't refresh package list upon changing package source

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10537]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio 16.10 P1

Product version: 5.10.0.7102

Worked before? If so, with which NuGet version: I am unable to reproduce this issue in standalone/classic VS

## Repro steps and/or sample project

- Sever and Client instance of Codespace are running locally.
- Cloned this repo https://github.com/nkolev92/NuGet.VS.Oe.TestBed locally
- Connected to above repo using Codespaces
- Navigated to `Manage NuGet Packages` window for `Library2` project
- Removed `nuget.org` from package source

**Actual**
- Packages list didn't refresh

**Expected**
- Packages list to refresh like classic/standalone VS

![pmui-issue](https://user-images.githubusercontent.com/52756182/106949983-9a29ba00-66e2-11eb-80a4-c68ddcf60c41.gif)

**Comment by sbanni** [comment]
Not a regression, tried on 16.7.

**Comment by kartheekp-ms** [comment]
I can't reproduce this issue on standalone/classic VS on 16.10. It may have been fixed recently after 16.7.

**Comment by nkolev92** [comment]
Closing per @kartheekp-ms's comment about the problem being fixed.

**Comment by zkat** [comment]
It still repros in Codespaces. We misread :)

**Comment by aortiz-msft** [comment]
Bulk-closing VS OE issues.
