### ISSUE TITLE
License URL is not loaded when connected to CodeSpace

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10546]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: 16.9p4

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

1. Open a project in a local CodeSpace.
2. Open PMUI
3. Find a package that uses a License URL (eg, Microsoft.Internal.VisualStudio.Shell.Interop.9.0 from apex public feed)
4. In the Details pane, click `View License`. Alternatively, install the package and click `View License` in the prompt.
5. Observe that the license file never loads. In Standalone, the license text is loaded.

![image](https://user-images.githubusercontent.com/49205731/106978899-37104580-672b-11eb-9fbe-48ec6c7ad11d.png)

Expected (Standalone):
![image](https://user-images.githubusercontent.com/49205731/106979171-c3226d00-672b-11eb-92b0-515891fc18ad.png)

**Comment by rrelyea** [comment]
tried latest dev with latest 16.9p4 build.
built 3 packages that all have requireLicense. one embedded. one url. one expression.
used local file source.  all worked.

perhaps it is a problem with http feeds...will find that scenario and test.

**Comment by rrelyea** [comment]
the reported package has licenseUrl of https://aka.ms/pexunj, which redirects to another url

**Comment by donnie-msft** [comment]
> tried latest dev with latest 16.9p4 build.
> built 3 packages that all have requireLicense. one embedded. one url. one expression.
> used local file source. all worked.
> 
> perhaps it is a problem with http feeds...will find that scenario and test.

Are you talking about CodeSpaces working?

**Comment by rrelyea** [comment]
testing/debugging appears to be blocked by: https://github.com/NuGet/Home/issues/10563 (which is against real codespaces server)

**Comment by nkolev92** [comment]
Guidance is that all of these issue are closed.
