### ISSUE TITLE
Package Metadata (details, deprecation) are sometimes not pulled from nuget.org in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10549]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: 16.9p4 with 5.9.0.7097\artifacts\VS15\NuGet.Tools.vsix

Worked before? If so, with which NuGet version: Standalone

## Repro steps and/or sample project

1. Create a solution and connect to a CodeSpace.
2. Open PMUI for a project.
3. On Browse tab, search for some known deprecated packages (I used "nuget.core").
4. Observe that CodeSpaces does not show all deprecated indicators (right). 
 Also metadata is not being pulled from nuget.org for `NuGet.Protocol.Core.Types`, but it is for `NuGet.Core` for some reason.
(Left) shows Standalone with more deprecated indicators.

![image](https://user-images.githubusercontent.com/49205731/107072404-117b4e80-67b4-11eb-8ed8-ff5df1c289cb.png)

"nuget.protocol.core" pulls no metadata:
![image](https://user-images.githubusercontent.com/49205731/107072854-8fd7f080-67b4-11eb-83fc-9679f50f5963.png)

Package Source: nuget.org does not resolve it:
![image](https://user-images.githubusercontent.com/49205731/107072926-aa11ce80-67b4-11eb-9427-eb8b86c96ec8.png)

**Comment by donnie-msft** [comment]
Of course, means Installed tab is missing deprecation indicator:
![image](https://user-images.githubusercontent.com/49205731/107073502-797e6480-67b5-11eb-9fd6-4783e37eba1a.png)

**Comment by rrelyea** [comment]
consider for 16.9 if regression in standalone.

**Comment by donnie-msft** [comment]
> consider for 16.9 if regression in standalone.

@rrelyea as with the others you asked about, this is only "in CodeSpaces". Also every screenshot has the Standalone shown on the left with expected metadata.

**Comment by donnie-msft** [comment]
May be a separate issue, but also on that package, the Uninstall icon is not present when hovering this package. It is for another one in the same list.
![image](https://user-images.githubusercontent.com/49205731/107084822-8d31c700-67c5-11eb-8a24-fab632e6276f.png)

**Comment by donnie-msft** [comment]
@sbanni did your PR also fix this missing uninstall icon? https://github.com/NuGet/Home/issues/10549#issuecomment-774266236

**Comment by sbanni** [comment]
Just tested the uninstall icon, it is fixed with the PR
