### ISSUE TITLE
Unloading project did not close PM UI window in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10543]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: 16.9p4

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

1. Open a project in CodeSpaces
2. Open PMUI
3. Unload the project for which you opened PMUI
4. Observe that the PMUI remains open. It should close as it does in Standalone.

**Comment by rrelyea** [comment]
duplicated of #9935
