### ISSUE TITLE
Manage NuGet Packages should not be shown for Unloaded Projects in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10544]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version:  16.9p4

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

1. Open a solution in CodeSpaces.
2. Unload a project.
3. Right click the project in Solution Explorer
4. Observe "Manage NuGet Packages" is shown. It shouldn't be shown, as it doesn't work, and is not shown in Standalone.

![image](https://user-images.githubusercontent.com/49205731/106965281-631ecd00-6711-11eb-8c61-dd6a46909314.png)

**Comment by rrelyea** [comment]
targeting 16.10, as standalone works fine, which is 16.9 qb mode priority.

**Comment by donnie-msft** [comment]
Closing CodeSpaces issues.
