### ISSUE TITLE
Update to older Package version causes "Object reference not set" error in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10540]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 5.9 preview 4

Worked before? If so, with which NuGet version: ?

## Repro steps and/or sample project

Telemetry, logs, etc: https://developercommunity2.visualstudio.com/t/update-to-older-package-causes-object-reference-no/1330912

1. Repeat steps from https://github.com/NuGet/Home/issues/10539
2. Downgrade `Castle.Core 4.4.1` to `4.2.1`.
3. Observe an error in Error List and PMUI.
![image](https://user-images.githubusercontent.com/49205731/106958528-7e84da80-6707-11eb-95cb-f235d2981880.png)

### Verbose Logs

Telemetry, logs, etc: https://developercommunity2.visualstudio.com/t/update-to-older-package-causes-object-reference-no/1330912

 

>   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<>c__DisplayClass18_0.<GetTransitivePackageReferencesForFramework>b__1(ValueTuple`2 t)
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetTransitivePackageReferencesForFramework(NuGetFramework targetFramework, List`1 installedPackages, List`1 transitivePackages, IList`1 targets)
>    at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<>c__DisplayClass16_0.<GetInstalledAndTransitivePackagesAsync>b__3(TargetFrameworkInformation f)
>    at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
>    at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at System.Linq.GroupedEnumerable`3.GetEnumerator()
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<GetInstalledAndTransitivePackagesAsync>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<GetInstalledPackagesAsync>d__15.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<GetInstalledPackagesAsync>d__10.MoveNext()

**Comment by donnie-msft** [comment]
Added a stack. 
Even after closing PMUI, reopening it immediately fires this error now. Assume restarting VS will resolve.

**Comment by donnie-msft** [comment]
Unload/Load the project resolved the error.

**Comment by rrelyea** [comment]
@donnie-msft  - same question as #10539 -- does this impact standalone scenario too? or just codespaces-connected?

**Comment by rrelyea** [comment]
confirmed...standalone is ok. 16.10

**Comment by nkolev92** [comment]
Closing this issue as it's codespaces only, and not an issue in standalone.
