### ISSUE TITLE
Come up with a list of project types that we might be missing integration tests for

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#10554]
This is one of the corrective actions for https://github.com/NuGet/Client.Engineering/issues/727

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/4094 and https://github.com/NuGet/NuGet.Client/pull/3964. 

This task is equivalent to https://github.com/NuGet/Home/issues/10553 since we kind of just have the tests :)
