### ISSUE TITLE
Updates Tab doesn't show count of available updates in CodeSpaces

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10551]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: 16.9p4

Worked before? If so, with which NuGet version: Standalone

## Repro steps and/or sample project

![image](https://user-images.githubusercontent.com/49205731/107085432-78a1fe80-67c6-11eb-818c-5aad6181d740.png)
1. Open a solution in CodeSpaces.
2. Add packages that have updates available on nuget.org.
3. Navigate to PMUI, with nuget.org selected.
4. Observe that some updates are shown in the packages list, but the Updates tab shows nothing.
5. Tried the following, but made no difference: Refreshed many times, changed tabs, changed Packages Sources (including to All), Reopen PMUI, Install/Uninstall packages, Close VS and reconnect to same CodeSpace.
5. Note: Deprecation is also not shown on Installed, but that's tracked https://github.com/NuGet/Home/issues/10549

**Comment by chrisraygill** [comment]
@donnie-msft can I close this?

**Comment by donnie-msft** [comment]
@chgill-MSFT That sounds like a question for @aortiz-msft
