### ISSUE TITLE
NuGet.VisualStudioExtension: NuGet in Intranet not useable (no Internet connection).

### ISSUE THREAD

**Issue by Torgrimm** [NuGet/Home#1056]
Hello,

we are developing in a LAN without internet access. We have our packet sources in the TFS server. That is the only active packet source.

When opening the NuGet Visual Studio Extension, NuGet starts to query the DNS for each packet in the source (or each visible one) in order to display the package information. The entire Visual Studio nearly freezes. Every click or scrolll repeats the process. That way, the extension is unusable. It can be only exited by killing Visual Studio.
The Package Manager Console is slightly slower then expected, but useable.

The problem exists for every Version of NuGet so far.
Unplugging the network cable "solves" the problem.

**Comment by yishaigalatzer** [comment]
Hey @Torgrimm,

I assume you mean package sources? What do you mean by storing them in the TFS server? Is it on a network share, or an http endpoint? 

Are you experiencing the same behavior with visual studio 2015 and the latest nuget extension as well? Or is this limited to visual studio 2013 and lower?

**Comment by Torgrimm** [comment]
Hello Yishai
Yeah, the Package Source. Wer maintain our Package Source in the TFS Source Control. In the Nu get Settings we choose the Directory of the locally mapped folder as package source. They get installed in a different folder, but still in a TFS maintained folder. 

The behavior is the same in any version I've tested so far. That means some versions for 2013 (2.86 and earlier) and for 2015 version 3.0 and I think for the Windows 10 version as well (3.11?). 

Once I've tried to remove the network access code from the client, but struggled in locating and skipped it due to time constraints. 

Am 7. August 2015 20:12:25 MESZ, schrieb Yishai Galatzer <notifications@github.com>:
>Hey @Torgrimm,
>
>I assume you mean package sources? What do you mean by storing them in
>the TFS server? Is it on a network share, or an http endpoint? 
>
>Are you experiencing the same behavior with visual studio 2015 and the
>latest nuget extension as well? Or is this limited to visual studio
>2013 and lower?
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/NuGet/Home/issues/1056#issuecomment-128785319

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by yishaigalatzer** [comment]
In this case (using network share as in \\share\... ) I'm not sure what DNS server you are trying to hit. Can you please share nuget.config?

In general you probably want to set up a private nuget server. http://docs.nuget.org/create/hosting-your-own-nuget-feeds

**Comment by Torgrimm** [comment]
Oh, I forgot to tell. I'd set up my own NuGet feed in order to try to resolve the issue.
The result was just the same.
It is not the feed, that causes the delay. But beside the feed, NuGet connects the project site of every package. I guess, this is in order to fetch additional informations about the package.

I can post some Wireshark logs and the config next week. The logs showing the issue very clearly. There are a lot of DNS or NetBIOS request to non NuGet servers, when you have the package manager active. 
But the issue is also quite easy to reproduce, even with the default NuGet feed.
1. Be connected to the Internet.
2. Open NuGet Package Manager
-> Everything is nice and fast
3. Unplug your network cable
-> Everything is nice and fast
4. Connect your PC to a switch or another network device, but not the Internet
-> Scrolling or any other usage of NuGet becomes a pain.
(Be fast from step 2 to 4)

This is not exactly my usual scenario, but near enough. The key difference is, at some point, the lost connection is detected

**Comment by yishaigalatzer** [comment]
Very cool if you to point out the issue. I completely missed that this is happening. We know where to look now.

**Comment by Torgrimm** [comment]
Great to hear :)

**Comment by zhili1208** [comment]
@Torgrimm Can you post the network request log for this issue? and you said you maintain your package source under TFS, so this package source is a v2, v3 or folder? thanks

**Comment by MichaelSteinecke** [comment]
@zhili1208 
Hello again
sorry, I forgot to post the log. It's attached as an image as I'm not allowed to post other content. You need to store it locally and rename the file extension from .png to .zip. 

![nuget dns errors zip](https://cloud.githubusercontent.com/assets/6099045/10639861/84f33b58-7812-11e5-805c-22d858af30e9.png)

Hopefully that works.

The package source is a folder within the TFS repository. I attach our nuget.config as well

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositoryPath" value="External\NuGetPackages\Installed" />
    </config>
  <packageSources>
    <add key="TFS" value ="External\NuGetPackages\Packages"/>
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value=""/>
    <add key="Microsoft and .NET" value=""/>
  </disabledPackageSources>
  <activePackageSource>
    <add key="TFS" value ="External\NuGetPackages\Packages"/>
  </activePackageSource>
  <packageRestore>
    <add key="enabled" value="False"/>
    <add key="automatic" value="False"/>    
  </packageRestore>
</configuration>
```

**Comment by zhili1208** [comment]
@Torgrimm have you tried NuGet 3.2? still repro?

**Comment by MichaelSteinecke** [comment]
@zhili1208 I have tried it now. It's still repro. The Wireshark logs looking like same.

**Comment by zhili1208** [comment]
@Torgrimm I think those dns requests are for fetching package icon. I can disable the icon fetching and send you a private build to see if the build can fix your problem. Can you give me your email address? thanks

**Comment by MichaelSteinecke** [comment]
@zhili1208 
You can send it to nugetclient@mailinator.com, but please post here a notification for me as well. Otherwise it may get deleted before i can catch it up. (I don't like to post my mail address in public...)

**Comment by zhili1208** [comment]
@Torgrimm just sent it

**Comment by zhili1208** [comment]
@Torgrimm mailinator mail server returned message oversized error, my email is lzhi@microsoft.com, you can send your email address to me. thanks

**Comment by yishaigalatzer** [comment]
@Torgrimm @zhili1208 can you update on progress here?

**Comment by MichaelSteinecke** [comment]
@yishaigalatzer @zhili1208 
Zhi provided a fixed build for me. So I think we can close the issue

**Comment by zhili1208** [comment]
checked in Rob's fix for this issue. https://github.com/NuGet/NuGet.Client/commit/6d112fb8459899b3dc098b1621e08c56c11fa88f

**Comment by MichaelSteinecke** [comment]
@zhili1208 @yishaigalatzer 
I've tested NuGet VS AddIn 3.4.4 now (and the one shipped with VS2015 SP2). It seems for me as the bug is still present. Is the fix not merged with the trunk, currently? Or is there a new issue resulting in the same behavior?

**Comment by alpaix** [comment]
@Torgrimm I was unable to repro this issue with 3.4.4.1321. 
I tried 2 setups:
- Emulated network delay of 7 sec using Fiddler
- Provisioned isolated VM with no Internet access.

Can you share more details? A screenshot may be helpful as well.

**Comment by Torgrimm** [comment]
Torgrimm

**Comment by MichaelSteinecke** [comment]
@alpaix 
To Setup the Problem, it is important to have a network connection, but being disconnected from the internet. For example a cable to another PC or Switch should be enough.
Now, NuGet tries to connect and retrieve some information for all packets. As soon as you disable the network adapter or unplug the network cable, everything works like a charm.
In the build from @zhili1208, the behavior has been fixed.
[NuGet Captures.zip](https://github.com/NuGet/Home/files/354122/NuGet.Captures.zip)
