### ISSUE TITLE
Add the project type `nfproj` to the list of supportedProjectExtensions for Nuget CLI.

### ISSUE THREAD

**Issue by networkfusion** [NuGet/Home#10562]
## Details about Problem

NuGet product used: NuGet.exe

Product version: latest

Worked before? If so, with which NuGet version: none.

## Repro steps and/or sample project

**Proposal:**
Add the project type `nfproj` to the list of supportedProjectExtensions in `NuGet.Client/src/NuGet.Clients/NuGet.CommandLine/Common/ProjectHelper.cs`
A PR can be raised if required.

**Further explanation:**
.NET nanoFramework (https://dotnetfoundation.org/projects/nanoframework) is an OSS platform that enables the writing of managed code applications for constrained embedded devices. It is supported by the .NET foundation.
.NET nanoFramework uses nuget packages extensively, however, due to a lack of support in VS for extensibility to have sub-projects in a given language (C#), we could not use the standard `csproj` type and have had to differentiate our projects by using a `nfproj` file extension. 
When performing automated dependency updates, currently nuget CLI does not recognise this extension and we have to perform a workaround of scripting the rename of these projects to be the standard `csproj` in order to run tasks like `nuget update`, and then reverse the rename for compatibility with VS.
This is far from ideal, and by adding support for the extension in nuget, it would alleviate a number of complex workarounds.

**Comment by hrumhurum** [comment]
>due to a lack of support in VS for extensibility to have sub-projects in a given language (C#)

Many moons ago Visual Studio allowed to extend common project types like C# with sub-types. Please consider to take a look at `ProjectTypeGuids` MSBuild property. It allows you to instruct the project system to "flavor" a common project type with a custom extension UI/logic. This all applies to VS Extensibility area (VS Extensions etc).

**Comment by josesimoes** [comment]
> > due to a lack of support in VS for extensibility to have sub-projects in a given language (C#)
> 
> Many moons ago Visual Studio allowed to extend common project types like C# with sub-types. Please consider to take a look at `ProjectTypeGuids` MSBuild property. It allows you to instruct the project system to "flavor" a common project type with a custom extension UI/logic. This all applies to VS Extensibility area (VS Extensions etc).

Have tried that (on the scope of the project that @networkfusion mentions) without success. 
Ended up having to use a different extension to accomplish this, which took us here.
To this date, and to the best of my knowledge, this is still not possible. See [here](https://github.com/microsoft/VSProjectSystem/issues/322)

**Comment by zkat** [comment]
@networkfusion PRs welcome, then! Thank you :)

**Comment by josesimoes** [comment]
@zkat awesome! I'll be tackling this.

Now that we are at it, can we also discuss adding a TFM for .NET nanoFramework?
I've started a discussion about this in the .NET repo. Please see [here](https://github.com/dotnet/designs/discussions/180).
