### ISSUE TITLE
nuget restore results in a package integrity check failure on big endian system

### ISSUE THREAD

**Issue by nealef** [NuGet/Home#10567]
## Details about Problem

NuGet product used: NuGet.exe 

Product version: Built from master

Worked before: N/A

## Repro steps and/or sample project

A run of `dotnet build` on a big endian system borks with `The package integrity check failed.` when `msbuild` tries to restore packages

The `VerifySignedPackageIntegrity` method is not endian-aware which results in a verification failure. The attached patch works for both little and big endian systems and may provide insight into creating a _real_ solution to the problem.

[diff-nuget.txt](https://github.com/NuGet/Home/files/5969176/diff-nuget.txt)

**Comment by nealef** [comment]
@zivkan Hi again. This appears to be another endian issue for the client. I'm trying to this on an ubuntu 20.04 x64 system to make sure it doesn't break anything but I can't seem to get the magic formula for building the artifacts using the `./build.sh` command. Note I needed the following to just to get the `restore` to work:
```
diff --git a/build.sh b/build.sh
index 565ef77c4..6c993d5fc 100755
--- a/build.sh
+++ b/build.sh
@@ -19,7 +19,7 @@ curl -o cli/dotnet-install.sh -L https://dot.net/v1/dotnet-install.sh
 chmod +x cli/dotnet-install.sh

 # v1 needed for some test and bootstrapping testing version
-cli/dotnet-install.sh -i cli -c 1.0
+cli/dotnet-install.sh -i cli -c 5.0

 DOTNET="$(pwd)/cli/dotnet"

diff --git a/build/build.proj b/build/build.proj
index b69842da9..11016ee4c 100644
--- a/build/build.proj
+++ b/build/build.proj
@@ -418,8 +418,7 @@
       <CoreInputTestAssemblies>@(TestAssemblyPath->WithMetadataValue("IsCore", "true"))</CoreInputTestAssemblies>
       <CoreInputTestAssembliesSpaced>$(CoreInputTestAssemblies.Replace(';', ' '))</CoreInputTestAssembliesSpaced>

-      <VsTestLogger>--test-adapter-path:$(XunitXmlLoggerDirectory) --logger:"xunit;LogFileName=$(TestResultsFileName)-vsts.$(TestResultOutputFormat)" --logger:"console;verbosity=detailed" --settings:$(MSBuildThisFileDirectory)xunit.runsettings</VsTestLogger>
-      <VSTestCommand>$(DotnetExePath) test $(CoreInputTestAssembliesSpaced) $(VsTestLogger)</VSTestCommand>
+      <VSTestCommand>$(DotnetExePath) test $(CoreInputTestAssembliesSpaced)</VSTestCommand>
     </PropertyGroup>

     <!-- Desktop -->
```

**Comment by kartheekp-ms** [comment]
cc @heng-liu

**Comment by nealef** [comment]
Revised suggested fix.
[diff-nuget-bigendian.txt](https://github.com/NuGet/Home/files/5992960/diff-nuget-bigendian.txt)

**Comment by zivkan** [comment]
@nealef could you create a pull request with these changes?  You might as well be credited in the git history for fixing the bug.

**Comment by nealef** [comment]
Will do. The original author of the fix will generate in the next couple of days.

**Comment by nealef** [comment]
PR located at https://github.com/NuGet/NuGet.Client/pull/3930

**Comment by zivkan** [comment]
@uweigand  thank you for fixing this issue.  It should ship with NuGet 5.10, VS 16.10 (although perhaps this isn't a scenario where the fix will help), and  .NET 5 SDK 5.0.300

**Comment by uweigand** [comment]
Thank you!
