### ISSUE TITLE
Some feeds fail package installation due to metadata fetching

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#10563]
Connect to codespace - https://github.com/rrelyea/repro-nugetauth
use branch: localFeedMetdataRepro
Open terminal - type "dotnet pack" to build 4 packages into src\builtpackages\

Open PM UI for rrelyea.authTestApp
Install one of the packages from the "locally built packages" feed.  I tried "embedded" and a few others.

expected: 
get prompted for license acceptance

actual:
install fails .. "unable to find metadata of " + packageFileName

debugging into routine that throws exception makes it seem like the locally defined source isn't in the list.
also, one of the source urls looks like it is prepended with a path from the client machine... (not sure if related...but likely a problem)

**Comment by rrelyea** [comment]
seems to hit same error with feed of url: https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json

**Comment by sbanni** [comment]
@rrelyea I am not able to repro this, is there something I am missing?

**Comment by sbanni** [comment]
This whole area needs to be using codespace services to get the metadata and sources from the server, right now it is all client based.  @rrelyea is going to take first crack at this.

**Comment by aortiz-msft** [comment]
@sbanni Given what we know today, is this something that we need to complete or can we close?

**Comment by sbanni** [comment]
@aortiz-msft Given what we know today, I would think we are in a place where we can close this item and revisit if there is a problem here in the future.

**Comment by aortiz-msft** [comment]
Great, thanks!
