### ISSUE TITLE
[Question] Why Visual studio copy non windows files (*.so) to output build on Windows

### ISSUE THREAD

**Issue by LiorBanai** [NuGet/Home#10569]
HI,
I'm doing standard build in Visual studio latest on windows.
I have Nuget dependency on gRPC.core.
when I build the program (any cpu) I get additional files (like libgrpc_csharp_ext.x64.so) in the output folder that are not needed on Windows.

Why is that and how to I exclude those files from getting to the output folder.

**Comment by zivkan** [comment]
The Grpc.Core package ships [this MSBuild targets file](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/build/net45/Grpc.Core.targets).

As you can see, it adds all of the native binaries to the build as `Content` items, which instructs the build system to copy the files to the output directory on build.

**Comment by LiorBanai** [comment]
Thanks!
