### ISSUE TITLE
ContentFiles cannot be excluded from dependant projects on VS 16.8.5

### ISSUE THREAD

**Issue by jefflill** [NuGet/Home#10570]
## Details about Problem

NuGet product used: **Visual Studio**

Product version: **16.8.5**

## Repro steps and/or sample project

I have two .NET Standard2.0 projects named **A** and **B** and one .NETCore 3.1 console application named **C**, where:

    A <-- B <-- C

Project **A** includes the **asset.txt** file which is configured to be copied to output as well as published **as content**:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="asset.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="asset.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>true</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
```

Project **B** references project **A** and is configured to include the content files from project **A**, excluding everything else and also configures **ContentFiles** to be **PrivateAssets**:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\A\A.csproj">
      <IncludeAssets>ContentFiles</IncludeAssets>
      <ExcludeAssets>Compile;Runtime;Build;Native;Analyzers</ExcludeAssets>
      <PrivateAssets>ContentFiles</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
```
Project **C** (the console app) references project **B**, excluding **ContentFiles** and **Analyzers** while considering nothing to be private:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B\B.csproj">
      <IncludeAssets>Compile;Runtime;Build;Native</IncludeAssets>
      <ExcludeAssets>ContentFiles;Analyzers</ExcludeAssets>
      <PrivateAssets>None</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
```
With this configuration, I expected the binaries from project **A** to make it into project **B** output but not to project **C**.  This is working correctly.

**The Problem:** I expected the **asset.txt** content file to make it into project **B** output **but not** to project **C**.  The **problem is that asset.txt is also being written to the project C output** which I don't believe should be happening due to the `<PrivateAssets>ContentFiles</PrivateAssets>` in project **B's** .csproj file.

Here's a quick look at the project files with the build output folder displayed below.  As you can see, **assets.txt** is present in the project **C** build output folder and I don't think it should be.

![image](https://user-images.githubusercontent.com/4908431/108018463-af4cf580-6fcc-11eb-94c6-6a3c63e4c29b.png)

Here's the solution that replicates this:

[ReproSolution.zip](https://github.com/NuGet/Home/files/5986071/ReproSolution.zip)

Just for fun, I modified project **C** to try excluding everything from project **B** via:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B\B.csproj">
      <IncludeAssets>None</IncludeAssets>
      <ExcludeAssets>All</ExcludeAssets>
      <PrivateAssets>All</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
```
After cleaning and building, project **C's** output folder still includes the **asset.txt** content file from project **A**.  I must be completely misunderstanding how these asset tags are supposed to work.

**Comment by jefflill** [comment]
This may be a duplicate of #10311 under the covers, but this issue is replicated just doing VS builds without actually building the package.

**Comment by kartheekp-ms** [comment]
IMHO, this issue is a duplicate of https://github.com/dotnet/msbuild/issues/4717 because all the projects have `project reference` not `package reference`. As per [doc](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#projectreference) `The ProjectReference item defines a reference to another project. The referenced project is added as a NuGet package dependency, that is, it's treated the same as a PackageReference.`  Please let us know if the workaround suggested in the link works for you.

When I generated `nuget package` for project `B` from the `ReproSolution`, `A` project content files are not included in `B.1.0.0.nupkg` because the project reference to `A` has `<PrivateAssets>ContentFiles</PrivateAssets>` in `B.csproj`.

**Comment by jefflill** [comment]
I just noticed that when I publish project C, it doesn't include **assets.txt** either, which is the main thing I'm trying to accomplish.  I just assumed that the semantics for project references would be the same as for package references.

I'm going to go ahead and close this.  Thanks for your help.
