### ISSUE TITLE
Remove unreachable code calling EventTrigger.dll

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10584]
## Details about Problem

Worked before? If so, with which NuGet version: NuGet 2.xx

## Repro steps and/or sample project

I found dead code "EventTrigger.dll" from NuGet 2.xx era.
It was introduced [here](https://github.com/anurse/NuGet/commit/9d172f2db54ea6efb807e56693e4bbeaf53942e0).
Now it's time to remove NuGetEventTrigger.cs, TriggerEventMethod.cs which are related to "EventTrigger.dll", because it's taxing on performance.

**Comment by donnie-msft** [comment]
why is this dead code? The PR shows a file.exists check. Are you saying the file always exists?

**Comment by erdembayar** [comment]
@donnie-msft 
No, this file doesn't exist anywhere nowadays. Just search your local HDD for it, you wouldn't find it. That PR is 7-8 years ago thing.
Now question is do I just remove it or mark as Obsolete?

**Comment by donnie-msft** [comment]
You're removing `NuGetEventTrigger.cs`? That wasn't clear from the issue. I don't know, but I can't imagine a reason to mark it Obsolete. I think that's generally for something we continue to support, but retract some functionality.

**Comment by erdembayar** [comment]
@donnie-msft 
2 files are going away: NuGetEventTrigger.cs, TriggerEventMethod.cs
From code it looks like someone who introduced it used as telemetry tool. It records beginning and end of each method then correlate to find out if method successfully run or duration it took.

**Comment by erdembayar** [comment]
@aortiz-msft 
Fix is very straight forward and I created branch for it, but after discussion with @zivkan it's better to wait for V6.00 to for creating PR to merge.
