### ISSUE TITLE
Implement dotnet nuget sign command

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#10581]
According to : https://github.com/NuGet/Home/issues/10090#issuecomment-705086230, and some offline discussion, we changed this issue into an epic, and add more details for each sub-tasks.

**Comment by bruno-garcia** [comment]
In what version of msbuild can expect this to land? Is this a .NET 6 feature?

**Comment by heng-liu** [comment]
Yes, the .NET6 preview5 (and later) should have this command.

**Comment by heng-liu** [comment]
Doc issue:
https://github.com/NuGet/Home/issues/10997
https://github.com/dotnet/docs/issues/25049
