### ISSUE TITLE
PowerShell with .net core 5.0 in Ubuntu 20.4 - Unable to resolve package reference ''.

### ISSUE THREAD

**Issue by JasonJ387** [NuGet/Home#10583]
I'm using PowerShell with .net core 5.0 in Ubuntu 20.4; but I'm having an issue importing nuget libraries using the Install-Package command.

The machine is in a locked down environment with no access to the outside world so nuget pacakages are stored on a fileshare.

This works fine on Windows Devices, but the Ubuntu device is complaining.

The specific command I'm using is:
Install-Package -Source /mnt/share/DotNetCorePackages -Name system.xml.xpath.xmldocument -SkipDependencies

The error message I'm receiving is:
Install-Package: Unable to resolve package reference ''.

**Comment by zivkan** [comment]
From [our docs on `Install-Package`](https://docs.microsoft.com/en-us/nuget/reference/ps-reference/ps-ref-install-package)

> This topic describes the command within the Package Manager Console in Visual Studio on Windows. For the generic PowerShell Install-Package command, see the PowerShell PackageManagement reference.

In short, unfortunately Visual Studio's Package Manager Console uses the same cmdlet name as something built into PowerShell itself, but the two commands have nothing to do with each other (the PowerShell command happens to use NuGet/nupkg as an alternative to creating their own zip file format and implementing their own server protocol, but it has nothing to do with .NET projects).

**Comment by nkolev92** [comment]
Closing per the above comment.
