### ISSUE TITLE
How are fallback paths populated into nuget.g.props for NuGetPackageFolders?  

### ISSUE THREAD

**Issue by breidikl** [NuGet/Home#10580]
We have one user getting an unexpected Xamarian path added to the list of NuGetPackageFolders in his *.nuget.g.props files when running dotnet.exe restore (using version 5.0.102), for which we have not been able to track down the reason.  

Specifically our environment has a nuget.config that clears all earlier setting and only adds very specific enlistment known paths (globalPackagesFolder is set, while RepositoryPath is cleared).  We also sandbox environment variables that are allowed to pass through to the processes being run (so things like NUGET_PACKAGES are not set).  

Most folks just have globalPackagesFolder and a NuGetFallbackFolder under the sdk folder, though the user above has a third folder (before the sdk location) for C:\Microsoft\Xamarin\NuGet\ that we want to remove from that list.  We need to understand how that's getting added as a first step.  

This matters for our team as we use BuildXL to distribute our builds, and the extra path is being read by dotnet.exe causing mismatches to what is statically declared for our BuildXL graph.

**Comment by nkolev92** [comment]
NuGetPackageFolders is a combination of the global packages folder + fallback folders. 
The first in that list will be the global packages folder, while the latter will be fallback folders. 

You can specify a fallback folder through a nuget.config or through RestoreFallbackFolders property in the project file. 

NuGet should print the used configs at the end of the restore (or you can look at the assets file for the configs), so you can just look at the files in quesiton, I'd expect it's set in one of those.

**Comment by breidikl** [comment]
Thanks, that helped us track down the culprit.  

Specifically the user had a Program Files (x86)\NuGet\Config\Xamarin.Offline.config file that was adding an extra key to fallbackPackageFolders.  We're testing some changes to nuget.config in the project sources to clear that value, which we're expecting to resolve the issue.

**Comment by nkolev92** [comment]
That's great. Happy to hear my suggestion helped.
