### ISSUE TITLE
ECCN classification

### ISSUE THREAD

**Issue by JoannaCatts** [NuGet/Home#10582]
Do you know ECCN classification for:
•	NetEsxapades.configuration.Yaml: Read configurations files in yaml or yml format. C# dotnet core does not have a buoild in reader for this type of config files. Our standard config files are in yaml format.
•	NEST: Connect to a elasticsearch database. We are using these kind of database to store or logging

**Comment by zivkan** [comment]
The NuGet team doesn't support individual nuget packages. Please contact the package authors/owners.
