### ISSUE TITLE
 [Request] install command should install with v3 folder layout

### ISSUE THREAD

**Issue by Rand-Random** [NuGet/Home#10593]
As noted here https://github.com/NuGet/Home/discussions/10579 the install command lacks the ability to install the package in the v3 folder layout.

**Expected result:**

Every command nuget CLI has to offer should be ported to the new v3 layout, either by re-defining the "default" behaviour or by giving an additional argument to change the behvaviour.

I would suggest that every command should behave identically regarding the v3 layout, so all commands should default to v3 layout or give an argument, from a consumer point of view currently it seems half-baked where some commands do v3 layout while others don't.

**Actual result:**

The `install` command doesn't "respect" the new folder layout and still uses the "old" layout, while other commands like `add` already do the "new" layout.

I lack the knowledge if the `install` command is the only command which uses the "old" layout.

**Comment by Rand-Random** [comment]
@donnie-msft 
Only just noticed that the issue got tagged with dotnet.exe, just want to point out that I was using nuget.exe.
I don't know if they behave differently in this regard.

**Comment by zkat** [comment]
After some discussion, we decided this is not something we actually want to do. It's a very impactful change on nuget.exe while as a team we've been prioritizing PackageReference and dotnet.exe. As such, I'm closing this. Thanks for your time and the healthy discussions both here and in the other thread!

**Comment by Rand-Random** [comment]
@zkat 
Why not even as an optional argument?

**Comment by zkat** [comment]
It's still work to write, test, and maintain into the future. And the change is too low-priority for us to consider.
