### ISSUE TITLE
Restore fails, if lock is disabled, but lock file exists

### ISSUE THREAD

**Issue by uladz-zubrycki** [NuGet/Home#10597]
#### Description ####
Hi! It's more like a question than an issue actually. 

If I have lock mode disabled, but `packages.lock.json` file exists for a project, restore will fail, why is that?

```
NU1005 Invalid restore input where RestorePackagesWithLockFile property is set to false but a packages lock file exists at {project-path}\packages.lock.json.	
```			

#### Environment ####
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.03752

**Comment by donnie-msft** [comment]
Hi! Given this is a question about using the product, I'm moving it to the Discussions area.
