### ISSUE TITLE
Merge the throttling mechanism used during parallel restore for packages.config and project.json

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1060]
Merge the throttling mechanism used during parallel restore for packages.config and project.json

**Comment by yishaigalatzer** [comment]
The throttling mechanism in project.json restore can theoretically lead to port exhaustion, we should have one mechanism dealing with parallel network access rather than two.

**Comment by yishaigalatzer** [comment]
@emgarten how far are we from a merge?

**Comment by emgarten** [comment]
@yishaigalatzer I would need more context to understand this issue.

**Comment by yishaigalatzer** [comment]
The context is to control the number of http connections/downloading threads the same way across these two options, both when we restore in visual studio in a mixed project or in projects that are just packags.config or project.json (CLI or csproj)
