### ISSUE TITLE
Installed Version is not shown at all, sometimes, when in the 'Upgrade Available' filter

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1061]
Installed Version is not shown at all, sometimes, when in the 'Upgrade Available' filter

![image](https://cloud.githubusercontent.com/assets/2380340/8966739/e0e752d6-35e7-11e5-95bb-072c266dfb28.png)

Repro steps:

1. Switch to 'Upgrade Available' filter in the UI
2. Select an item and look at the details section for the package

Expected:
1. Action is shown, the latest version is shown and the currently installed version is shown

Actual:
1. Action and the latest version are shown. But, the currently installed version is not shown at all

**Comment by Leon99** [comment]
I'm experiencing the same issue even with the "Installed" filter selected
