### ISSUE TITLE
NuGet raises NU1201 compatibility error in projects that reference both a project and a package (transitively) with the same identity for different TFMs

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#10617]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: 5.0.100 / 6.0 Preview 1

Worked before? If so, with which NuGet version:

## Repro steps and/or sample project

A project which references another project with the same identity as a transitive package reference causes NuGet's compatibility check to fail and believe that the supported tfms of the project apply to the package as well. That happens even if the both references are condition on different TargetFrameworks.

In this case we have a parent project called `parent.csproj` which multi-targts for `net5.0` and `netstandard2.0` and references a child project `child1.csproj` on `netstandard2.0` which itself package references `System.Memory` which itself again has a package dependency on `System.Numerics.Vectors`. The `System.Numerics.Vectors` package supports i.e. `netstandard2.0` but not `net5.0`. The parent project also references another project on `net5.0` called `System.Numerics.Vectors` which supports `net5.0`. The same identities cause NuGet to throw a NU1201.

```
parent (project) netstandard2.0 TFM --> child1 (project) --> System.Memory (package) --> System.Numerics.Vectors (package)
                 net5.0 TFM --> System.Numerics.Vectors (project)
```
                      
1. Download and unzip [nugetnodes.zip](https://github.com/NuGet/Home/files/6084583/nugetnodes.zip)
2. `dotnet restore nugetnodes\parent\parent.csproj`

### Verbose Logs

```
C:\temp\nugetnodes\parent>dotnet restore
  Determining projects to restore...
C:\temp\nugetnodes\parent\parent.csproj : error NU1201: Project System.Numerics.Vectors is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project System.Numerics.Vectors supports: net5.0 (.NETCoreApp,Version=v5.0)
  Restored C:\temp\nugetnodes\child1\child1.csproj (in 276 ms).
  Failed to restore C:\temp\nugetnodes\parent\parent.csproj (in 276 ms).
```

cc @nkolev92 @rrelyea @safern @ericstj

**Comment by nkolev92** [comment]
> A project which references another project with the same identity as a transitive package reference

Without digging further, NuGet should select the project if the project & package have the same version. 
Do you see the package getting selected in a graph where both are available?
If not, then this is likely by design.

**Comment by erdembayar** [comment]
I'm closing this one because it's duplicate of https://github.com/NuGet/Home/issues/10368
Please go there and upvote.

**Comment by ViktorHofer** [comment]
> Without digging further, NuGet should select the project if the project & package have the same version.

This issue is about NuGet selecting the project over the package even though the project isn't referenced by a specific TFM when multi-targeting.

**Comment by nkolev92** [comment]
yeah @erdembayar is on hot seat this week so he correctly validated that it's a bug similar to the one we reported in #10368
