### ISSUE TITLE
native assets in subfolders are not respected

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10629]
---
**Issue moved from dotnet/sdk#16211**
- Please respond to @stevenbrix.

---

_From @stevenbrix on Thursday, March 4, 2021 6:39:41 PM_

If you have a NuGet package with native assets in subfolders:

```
runtimes\win10-x86\native\foo.dll
runtimes\win10-x86\native\en-us\foo.dll.mui
```

The .NET SDK copies these to the same location, and you lose the `en-us` locale subfolder.  This happens with both `Build` and `Publish` targets.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#16211**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Thursday, March 4, 2021 6:39:43 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by stevenbrix** [comment]
I know my original issue said this happened with `Build`, but I think this is only an issue for `publish`

Here's a binlog:
[msbuild.zip](https://github.com/NuGet/Home/files/6087995/msbuild.zip)

**Comment by rrelyea** [comment]
@wli3  - if this is publish only, then shouldn't we route to the owner of publish?

**Comment by wli3** [comment]
use https://github.com/dotnet/sdk/issues/16211 back
