### ISSUE TITLE
Changing globalPackagesFolder to a relative path throws a nullref

### ISSUE THREAD

**Issue by jeromelaban** [NuGet/Home#1062]
When creating a nuget.config file next the .sln with this content : 

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <config>
        <add key="globalPackagesFolder" value="..\packages\" />
      </config>
    </configuration>

The VS plugin crashes with this stack when adding a new package:

	System.NullReferenceException: Object reference not set to an instance of an object.
	   at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<EnsureResource>d__13.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	   at NuGet.DependencyResolver.SourceRepositoryDependencyProvider.<FindLibraryAsync>d__8.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at NuGet.DependencyResolver.RemoteDependencyWalker.<>c__DisplayClass14_1.<<FindLibrary>b__0>d.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibrary>d__14.MoveNext()

**Comment by yishaigalatzer** [comment]
Note that this is currently not supported (as in, the packages folder has to be a full path and not a relative path)

**Comment by jeromelaban** [comment]
This breaks the ability for solutions to be self sufficient, particularly when using private repositories. This scenario needs the ability to provide the equivalent of repositoryPath in NuGet 2.x.

**Comment by yishaigalatzer** [comment]
We could consider adding it back in a future release.

Note the downside is that you are creating very large copies of the packages on disk and the private feed can be easily figured out by proper versioning of packages (that you should probably do anyways).

**Comment by jeromelaban** [comment]
Having a large repository is a minor downside I can live with, disk space is cheap. External dependencies (public or private) that will not always be available (temporarily or permanently), making a source tree unbuildable, is a lot bigger downside.

**Comment by yishaigalatzer** [comment]
I don't follow. A global repository works a lot better in this case as long as you don't purge it.

**Comment by jeromelaban** [comment]
Two scenarios come to mind: First, build machines, very frequently changing with new environments, second, shipping source code to a third party that does not have access to the private repositories.

**Comment by yishaigalatzer** [comment]
Please don't take the response below a saying no, we will look into it. However the two scenarios above are easily supported

1. On CI machine you prefer a global folder because it speeds up builds tremendously. Even if you want separation you can set it up with a full path in a folder above the solution (that should work for most but not all cases, depending on how the repository is set up)
2. For sharing projects you can provide a folder with packages to be added to the feed list, which is the right way to do it rather than have the packages be checked in.

**Comment by jeromelaban** [comment]
Thanks! Sure, there are always ways to work around it, I was simply stating how and why that NuGet 2.x feature was conveniently used.

Also, these days, getting the repo is not the most time consuming task anymore... AOT (with Mono or .NET native), static analysis are *way* more time consuming...

**Comment by yishaigalatzer** [comment]
This is a pretty big change from nuget 2. A common package folder offers a much improved way to manage packages on disk.

Either way we will add the support back in the next few weeks. @deepakaravindr is working on the fix today

**Comment by csharpfritz** [comment]
@csharpfritz - Needs doc

**Comment by erikbra** [comment]
This one doesn't by any chance fix #1017 as a byproduct?

**Comment by yishaigalatzer** [comment]
It's an unrelated code path, we will need to take a look at #1017 separately (at least to evaluate if it was actually fixed or not)

**Comment by erikbra** [comment]
OK, thanks. See that it didn't make 3.2 beta. It's really annoying for us... :) Is this i bug in the VS plugin, or in Nuget itself, you think?
