### ISSUE TITLE
Updating nuget packages fails on a solution backed with SVN version control.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10639]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Updating-nuget-packages-fails-on-a-solut/1353545)._

---
[severity:It's more difficult to complete my work]
We have a large solution stored in a SVN repository.
We use VisualSVN extension to provide version control services to VisualStudio.
We have some critical .csproj files for which we've set the "SVN Needs-Lock" property, which means that SVN locks these Files as read only. In order to edit these files we need to use the SVN Get Lock, to get exclusive write access to the file.

Historically, VisualStudio has been able to work well with this feature: whenever you want to edit a locked file, you're prompted with a dialog to asks to try acquire the lock of the file.

But when we try to update the nuget packages of the project with the "Manage nuget packages for solution..." context menu, we select the packages we want to update, and we click on the UPDATE button.... nothing happens. The projects are not updated, and no error is provided.

We've found the reason for this problem is that, as long there's at least one .csproj file that's read only locked, the nuget package update process is stopped.

Expected behaviour: When clicking the UPDATE button, if there's a csproj file for which the write access lock needs to be ackquired, show a dialog to the user, requesting permissing to acquire the SVN lock on all locked files, before proceeding to update the project files, in the same way that when we try to edit a locked file in the main editor.

---
#### Feedback Bot on 3/2/2021, 06:30 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by vpenades** [comment]
For some reason, just today VisualStudio notified me there was an update of VisualSVN extension, [published March 5, 2021](https://www.visualsvn.com/visualsvn/changes/#v7.3.0) , I updated it, and the problem is gone.

When I reported this issue I didn't know whether it was a VisualStudio issue or an VisualSVN extension issue... the change notes don't seem to relate anything to this, but it seems the latest change did the trick.  The timing is weird, though,

I guess this issue can be closed.
