### ISSUE TITLE
Signing: Design dotnet nuget trusted-signers commands

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#10634]
Write up an RFC describing the commands and options and get it reviewed.

Reference: https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-trusted-signers

**Comment by anangaur** [comment]
Is this the Epic for trusted signers work for dotnet.exe? Or is it just for tracking the design work? /cc: @aortiz-msft

**Comment by heng-liu** [comment]
Closed as duplicate of https://github.com/NuGet/Home/issues/8053
