### ISSUE TITLE
NuGet.ContentModel.Infrastructure Parser method need performance improvement

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10644]
## Details about Problem

NuGet product used (Visual Studio):

Product version: 16.8

Worked before? If so, with which NuGet version: N/A

## Repro steps and/or sample project
While analyzing [VSFeedback#1286488](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1286488) I noticed 4 background NuGet threads are blocking for large solution and huge number of packages.
One of was Parser in NuGet.ContentModel.Infrastructure. There are several loop inside loop, we need to improve here. I included bottlenecks locations I identified.

https://github.com/NuGet/NuGet.Client/blob/ac97d923e633f4ee65eec5ec690c4d99d7a922f3/src/NuGet.Core/NuGet.Packaging/ContentModel/Infrastructure/Parser.cs#L192-L215

https://github.com/NuGet/NuGet.Client/blob/ac97d923e633f4ee65eec5ec690c4d99d7a922f3/src/NuGet.Core/NuGet.Packaging/ContentModel/ContentPropertyDefinition.cs#L109

https://github.com/NuGet/NuGet.Client/blob/ac97d923e633f4ee65eec5ec690c4d99d7a922f3/src/NuGet.Core/NuGet.Packaging/ContentModel/ContentPropertyDefinition.cs#L145

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8428. 

I am not confident the time complexity is the problem here, that's necessary, it's the allocations. 

Either way, more investigations will be done in the linked issue.
