### ISSUE TITLE
Authentication Prompts do not indicate the Feed and Retry count & can seem infinite

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10648]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: any

Worked before? If so, with which NuGet version: 

Authentication popups should be more detailed with which feed, and which retry count is being presented.
Showing generic popups 3x per feed can appear to be an infinite and arbitrary

From https://developercommunity.visualstudio.com/t/vs-2019-repeatedly-prompts-to-login-for-private-nu-1/1348029?from=email&viewtype=all#T-ND1364376

> ...with 3 tries, I think it is sane thing to provide more details for the user, after all, user could use 2 completely different repos. I have name and try number in mind. Like “YourRepo, access 1/3”, something like this.

## Repro steps and/or sample project

1. Trigger an Authentication prompt using Package Manager UI in VS.
2. Note that there's no indication of which feed it belongs to.
3. Fail the authentication.
4. Note a retry prompt appears, but doesn't indicate the current or total retries.

**Comment by zivkan** [comment]
related (duplicate?): https://github.com/NuGet/Home/issues/7814 https://github.com/NuGet/Home/issues/8985

**Comment by donnie-msft** [comment]
7814 says "should not automatically prompt" - that's different than making it clear what we're prompting for.
8985 is very generic "improve UX", so I'm sure this could be a step along that path, yes.

**Comment by donnie-msft** [comment]
Related https://developercommunity2.visualstudio.com/t/Version-1684-has-excessive-prompts-for/1332050

**Comment by nkolev92** [comment]
Consolidating this issue into https://github.com/NuGet/Home/issues/8985 as they both have the same motivation. 

I edited the title of the original issue.
