### ISSUE TITLE
Update-Package -Reinstall should not be required to perform a successful restore before reinstalling the package

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10649]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Update-Package--Reinstall-should-not-be-/1360432)._

---
[severity:It's more difficult to complete my work]
I'm getting the error

> Some NuGet packages are missing from the solution. The packages need to be restored in order to build the dependency graph. Restore the packages before performing any operations.

The package thats a problem is `System.Runtime.InteropServices.RuntimeInformation`.    If I try to use the PM UI to remove and reinstall the package, I cant, because the PM UI requires that all packages be restored before any operations take place. I guess thats fine for a UI that has had issues due to complexity.  But if I want to reinstall the package using the PMC there shouldnt be any restore required before any operations. 

``` powershell
PM> update-package -Reinstall -ProjectName MyProject -Id System.Runtime.InteropServices.RuntimeInformation 
update-package : Some NuGet packages are missing from the solution. The packages need to be restored in order to build the dependency graph. Restore the packages before performing any operations.
At line:1 char:1
+ update-package -Reinstall -ProjectName MyProject -Id Syste ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetMissingPackages,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
```
This leaves me only the option of manually removing and reinstalling the package. In this case its package.config based, but that does not matter. There should be no restriction to have a successful restore when using advanced commands like the update package reinstall.

---
#### Feedback Bot on 3/8/2021, 02:24 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### eryondon [MSFT] on 3/9/2021, 02:37 PM: 

<p>Thank you for creating this issue.<br>
You mentioned you’re using package.config.  It looks fixing problems manually in package.config sometime happens. Most likely reason for asking actual restore before reinstall is we need transitive dependencies from other not restored yet packages for full dependency graph evaluation, then decide what kind of changes to make to package.config and packages folder.<br>
Can I ask why are you package.config for your project? Moving to latest packageReference type would be better option because it’s latest and tried to address many problems existed in package.config type. You can find migration guide here <a target='_blank' href="https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#:~:text=%20Migration%20steps%20%201%20Open%20a%20solution,choose%20to%20treat%20a%20NuGet%20package...%20More">https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#:~:text= Migration steps  1 Open a solution,choose to treat a NuGet package... More</a>.</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Andrew Stanton on 3/10/2021, 07:03 AM: 

<p>There are many reasons I can give for not switching to package reference (<a target='_blank' href="https://github.com/NuGet/docs.microsoft.com-nuget/issues?q=%221c782e82-db9a-bf77-05ef-cd49374aee36%22++author%3AStingyJack">these</a> are two of the three issues I logged for the page you cited. The third was maliciously destroyed by someone who is no longer in a position to do something like that anymore), however in this case its an inherited project that I have to add one thing to and that requires a new package.</p>
<p>I cant add that package because nuget is having a wobbly with some other package, and I cant use the provided tool to reinstall that problem package because someone has coded a chicken and egg problem into Update-Package.</p>
<p>Why would I use the <code>-reinstall</code> option to reinstall a package?   Because the package isnt installed correctly or has some problem (like wrong target framework or something).</p>
<p>||: To fix a package installation issue, you run Update-Package -Reinstall for that project and package. Update-Package requires that all packages be restored before executing a reinstall. I cant restore the packages because one isnt installed correctly. I cant reinstall the package with the provided tool because the packages wont all restore properly. :||  &lt;- this whole paragraph repeats (the chicken and egg).</p>
<p>After fussing with it for a few hours, I found that the problem with the other package (System.Runtime.InteropServices.RuntimeInformation) was that it has very long paths inside the package (&gt; 150 chars), and when unzipped by the package manager where my repo is (%USERPROFILE\Source\Repos\Company\repoFolder\path\path\solutionfolder) it creates file paths that are too long and fails to unpack all the files.</p>
<p>That immediate blocking issue has been resolved by myself, but the original ask is still to have Update-Package -Reinstall not require a restore before doing the requested command. Also there is a bug with long file name handling when unpacking nupkgs.</p>

---
### Original Solutions
(no solutions)

**Comment by erdembayar** [comment]
I believe one of your raised issue being addressed here : https://github.com/NuGet/Home/issues/10184
And long path is here: https://github.com/NuGet/Home/issues/3324

**Comment by StingyJack** [comment]
@erdembayar I didnt mention transitivity anywhere. I just dont want to have to have a completely healthy package restore need to occur before running a special utility to fix package install problems. Its like saying you cant write any code until the code you have compiles, and the code has a syntax error.

**Comment by nkolev92** [comment]
The behavior you are experience is a design flaw of `packages.config`. In packages.config the content of packages is burnt *into* the project file, as such the uninstall/update actions needs to know the content of the package to run the uninstallation. 

Reinstall is effectively running uninstall, then install, so it suffers from the same problem. 

This has been reported previous in https://github.com/NuGet/Home/issues/2050#issuecomment-180041822 and https://github.com/NuGet/Home/issues/3077. 

I created a documentation issue to clearly call out this scenario https://github.com/NuGet/docs.microsoft.com-nuget/issues/2348

**Comment by StingyJack** [comment]
I dont mind this being called a dupe except that those two cited examples are talking about uninstall and update, not a repair (idempotent install) operation.  The problem is that -Reinstall is not re-installing, its uninstalling then installing.  The docs issue you logged doesnt make that differentiation either.

**Comment by nkolev92** [comment]
What would expect to be the difference between a reinstall and uninstall then install of the same package ids?

**Comment by StingyJack** [comment]
I would expect that `-reinstall` either performs the actions done to install the package (idempotent install, even if the first one seems to have failed) or does an uninstall then install. Both cases should assume the preconditions are still met as they were when the package was installed originally.  That precondition mostly being the need to have a clean restore of everything.
