### ISSUE TITLE
PMUI Update solution nuget packages: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10650]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Update-solution-nuget-packages:-Collecti/1359900)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.8.6]
After updating nuget packages for a solution, I sometimes see a yellow "Error occurred" message with this in the package manager output window:

**"Collection was modified; enumeration operation may not execute." **

---
#### Jeff Lill on 3/7/2021, 10:26 AM: 

<p>Additional info:</p>
<ul>
<li>This only happens occasionally</li>
<li>The packages seem to have updated correctly even with this warning</li>
<li>I’m pulling from a private feed hosted by <strong>BaGet</strong> container image: <strong>0b46f0ec87216e1dc6839277712ee07c1c2b611a</strong></li>
<li><strong>BaGet</strong> is running on Ubuntu 20.04</li>
<li>I updated solution packages again while watching the Baget logs and saw no messages (errors or otherwise)</li>
<li>I’ve attached the complete package manager log</li>
</ul>

#### Jeff Lill on 3/7/2021, 10:30 AM: 

<p>I attached the full package manager log.</p>

#### Feedback Bot on 3/7/2021, 07:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

[Hash](https://prism.vsdata.io/failure/?query=ch%3Drelease%20sev!%3DDiagnostic&eventType=fault&failureType=hits&failureHash=3b94f40f-06b1-5e46-6885-7e658d5f612f)

**Comment by erdembayar** [comment]
@aortiz-msft 
It's regression related to "NuGet recommender", now trying to pinpoint exact location of problem.

**Comment by erdembayar** [comment]
It's coming from [here](https://github.com/NuGet/NuGet.Client/blob/9dcb02945ce96a5ea8b98e5ff5e83fc67883fc16/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/PackageReferenceProject.cs#L70-L88). But change in [PR#3680](https://github.com/NuGet/NuGet.Client/pull/3680/files) is quite much, can't tell exactly what is wrong here.

**Comment by aortiz-msft** [comment]
@jebriede - Same as other issue related to Pkg Recommender.

**Comment by kartheekp-ms** [comment]
Here is another feedback ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1348442 where the activity log has a bunch of `Collection was modified; enumeration operation may not execute. ` errors.

**Comment by nkolev92** [comment]
And dup in https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1374036, public issue at https://developercommunity.visualstudio.com/t/VS2022-Updating-NuGet-packages-in-Packag/1504618.

**Comment by donnie-msft** [comment]
Duped Feedback ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1420117

**Comment by ToddEvansHome** [comment]
Just to let you know that I have received this same error today.  
I recently installed VS v17.0.0.RC2.  I was updating 6 Nuget packages when the error occurred.  The Updates & Consolidate tabs show incorrect counts.  See screen shot
![VSv17NugetError](https://user-images.githubusercontent.com/43685731/138304786-4a50b221-5caf-490c-9c14-27589642c58d.png)

**Comment by erdembayar** [comment]
@ToddEvansHome 
Could you be able reproduce this consistently? We really need repro steps or repro repo.

**Comment by SimonCropp** [comment]
@erdembayar shouldn't an exception, that bubbles up to a user dialog, be logged somewhere?

**Comment by erdembayar** [comment]
> @erdembayar shouldn't an exception, that bubbles up to a user dialog, be logged somewhere?

Sure, for now biggest hurdle is how to repro this, it happen very rarely.  I have rough idea for where it's coming from in code, but couldn't understand under what input it's happening.

**Comment by SimonCropp** [comment]
can you point to where that log file is? next time it happens to me i can upload the file

**Comment by erdembayar** [comment]
> can you point to where that log file is? next time it happens to me i can upload the file

Start reporting here. https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq
Use recording: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed

![image](https://user-images.githubusercontent.com/8766776/138366234-27fc7cb1-5967-4c23-983d-981d7ef38695.png)

**Comment by SimonCropp** [comment]
but a top level exception should write to a file irrespective of if recording is running.

**Comment by nkolev92** [comment]
The Output window has a Package Manager drop down. 

Any further details should be written there.

**Comment by donnie-msft** [comment]
>  shouldn't an exception, that bubbles up to a user dialog, be logged somewhere?

I'm pretty sure this error should be written to the ActivityLog. You can find it in your VS directory. For more information, see https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log

As erdembayar points out, uploading logs with a VS Feedback ticket will automatically attach this file.

**Comment by ToddEvansHome** [comment]
The ActivityLog needs to be switched on by the  /Log command line switch. So there isn't a log.   Unfortunately the application is a production app and I'm vacation next week so I am not able roll the project back to a previous state and try to reproduce it.

**Comment by nkolev92** [comment]
Report at https://developercommunity.visualstudio.com/t/After-Nuget-Packages-update---Error-occ/1567535

**Comment by erdembayar** [comment]
Reported here too: 
https://developercommunity.visualstudio.com/t/The-VsPackage-package-did-not-load-cor/1669580 and
https://developercommunity.visualstudio.com/t/Updating-nuget:-Collection-was-modified;/1544299

**Comment by erdembayar** [comment]
@jebriede 
If you need load balance thing, I can take this issue, please let me know.

**Comment by erdembayar** [comment]
Most likely related to https://github.com/NuGet/Home/issues/11644

**Comment by flcdrg** [comment]
I was the reporter for one of those developerfeedback tickets. 

I am getting this error almost every time I start Visual Studio 2022 now. Frustratingly, even though I click **No** on the error dialog, it will still show up again the next time I open a specific solution.

![image](https://user-images.githubusercontent.com/384747/157760312-a6f530b0-f243-42c0-abe7-ac0f101d0b1f.png)

This is really annoying. If there's any way of fixing this for 17.1.2 that would be much appreciated!

**Comment by erdembayar** [comment]
> I was the reporter for one of those developerfeedback tickets.
> 
> I am getting this error almost every time I start Visual Studio 2022 now. Frustratingly, even though I click **No** on the error dialog, it will still show up again the next time I open a specific solution.
> 
> ![image](https://user-images.githubusercontent.com/384747/157760312-a6f530b0-f243-42c0-abe7-ac0f101d0b1f.png)
> 
> This is really annoying. If there's any way of fixing this for 17.1.2 that would be much appreciated!

Could be able to create[ separate issue](https://github.com/NuGet/Home/issues) unless it's connected to this issue? I'm not sure if it's NuGet issue, it's too generic error.

**Comment by flcdrg** [comment]
@erdembayar The error I reported in https://developercommunity.visualstudio.com/t/The-VsPackage-package-did-not-load-cor/1669580?from=email (which was closed as a dup of this issue) has what appears to be the same stack trace error that I am still seeing at the end of the ActivityLog.xml, so pretty sure it's the same?

```
SetSite failed for package [VsPackage]Source: 'mscorlib' Description: Collection was modified; enumeration operation may not execute. System.InvalidOperationException: Collection was modified; enumeration operation may not execute. at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetTransitivePackageReferencesForFramework(NuGetFramework targetFramework, List`1 installedPackages, List`1 transitivePackages, IList`1 targets)
at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<>c__DisplayClass16_0.<GetInstalledAndTransitivePackagesAsync>b__3(TargetFrameworkInformation f)
at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at System.Linq.GroupedEnumerable`3.GetEnumerator()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<GetInstalledAndTransitivePackagesAsync>d__16.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.<GetInstalledPackagesAsync>d__15.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass10_0.<<GetInstalledPackages>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
at Microsoft.VisualStudio.DependencyValidation.NuGetHelper.GetInstalledPackages(IServiceProvider serviceProvider, Project project)
at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdater.ComputeDesiredPackages(IEnumerable`1 projects)
at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdater.GetArtifacts(IVsSolution solution, String removedDiagram, ITelemetryScope telemetryScope)
at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.SolutionRequiresUpdates(String removedDiagram)
at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.<OnSolutionApplicablityChanged>b__17_0()
at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.OnSolutionApplicablityChanged(Object sender, Boolean isApplicable)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at Microsoft.VisualStudio.DependencyValidation.VsPackage.<InitializeAsync>d__9.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass20_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
```

**Comment by erdembayar** [comment]
> @erdembayar The error I reported in https://developercommunity.visualstudio.com/t/The-VsPackage-package-did-not-load-cor/1669580?from=email (which was closed as a dup of this issue) has what appears to be the same stack trace error that I am still seeing at the end of the ActivityLog.xml, so pretty sure it's the same?
> 
> ```
> SetSite failed for package [VsPackage]Source: 'mscorlib' Description: Collection was modified; enumeration operation may not execute. System.InvalidOperationException: Collection was modified; enumeration operation may not execute. at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
> ```

Can you do me favor? It looks you can repro this consistently. Please reopen your VS make sure above window pop-up then check `ActivityLog.xml` contains below item with today's date + your current time. 
![image](https://user-images.githubusercontent.com/8766776/157767954-788929fe-60c7-4d2e-b8a0-1029f774b2d8.png)

**Comment by flcdrg** [comment]
Yep.. the timestamp is `2022/03/10 21:46:21.528`, which given I believe it is UTC would correspond to when that happened today

**Comment by erdembayar** [comment]
Could you share your latest ActivityLog.xml? No need sensitive info, only this entry.
Also, could you compile NuGet.Client on your local? If yes, then I already have fix [candidate](https://github.com/NuGet/NuGet.Client/tree/dev-eryondon-10650-CollectionWasModifiedEnumarationMayNotExecute) you can try out and check if it resolved your issue.

**Comment by flcdrg** [comment]
Just this bit?

```xml
  <entry>
    <record>1026</record>
    <time>2022/03/10 21:46:21.528</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;mscorlib&apos; Description: Collection was modified; enumeration operation may not execute.&#x000D;&#x000A;System.InvalidOperationException: Collection was modified; enumeration operation may not execute.&#x000D;&#x000A;   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)&#x000D;&#x000A;   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()&#x000D;&#x000A;   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#x000D;&#x000A;   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetTransitivePackageReferencesForFramework(NuGetFramework targetFramework, List`1 installedPackages, List`1 transitivePackages, IList`1 targets)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.&lt;&gt;c__DisplayClass16_0.&lt;GetInstalledAndTransitivePackagesAsync&gt;b__3(TargetFrameworkInformation f)&#x000D;&#x000A;   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)&#x000D;&#x000A;   at System.Linq.GroupedEnumerable`3.GetEnumerator()&#x000D;&#x000A;   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()&#x000D;&#x000A;   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)&#x000D;&#x000A;   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.&lt;GetInstalledAndTransitivePackagesAsync&gt;d__16.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.&lt;GetInstalledPackagesAsync&gt;d__15.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at NuGet.VisualStudio.VsPackageInstallerServices.&lt;&gt;c__DisplayClass10_0.&lt;&lt;GetInstalledPackages&gt;b__0&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()&#x000D;&#x000A;   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.NuGetHelper.GetInstalledPackages(IServiceProvider serviceProvider, Project project)&#x000D;&#x000A;   at System.Linq.Enumerable.&lt;SelectManyIterator&gt;d__17`2.MoveNext()&#x000D;&#x000A;   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdater.ComputeDesiredPackages(IEnumerable`1 projects)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdater.GetArtifacts(IVsSolution solution, String removedDiagram, ITelemetryScope telemetryScope)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.SolutionRequiresUpdates(String removedDiagram)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.&lt;OnSolutionApplicablityChanged&gt;b__17_0()&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsSolutionUpdaterController.OnSolutionApplicablityChanged(Object sender, Boolean isApplicable)&#x000D;&#x000A;   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.DependencyValidation.VsPackage.&lt;InitializeAsync&gt;d__9.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{7115CACC-895C-4BEA-BE84-706FD8DD69C1}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>
```

I'll take a look at NuGet.Client a bit later today

**Comment by flcdrg** [comment]
@erdembayar I pulled down the repo and switched to your branch. Just not clear what I should do then - build and install the vsix, or is more involved than that?

**Comment by erdembayar** [comment]
> @erdembayar I pulled down the repo and switched to your branch. Just not clear what I should do then - build and install the vsix, or is more involved than that?

Yes, build the repo. Then install the Vsix into your VS, check if it resolves your issue.

**Comment by flcdrg** [comment]
I installed it, but got a similar error dialog when loading the solution.
The ActivityLog.xml contains the following (no stack trace this time)

```xml
  <entry>
    <record>2478</record>
    <time>2022/03/15 06:58:15.028</time>
    <type>Error</type>
    <source>NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstallerServices.GetInstalledPackages</source>
    <description>ProjectNotNominatedException - The operation failed as details for project MyProjectName could not be loaded.</description>
  </entry>
  <entry>
    <record>2479</record>
    <time>2022/03/15 06:58:15.087</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;NuGet.PackageManagement.VisualStudio&apos; Description: The operation failed as details for project MyProjectName could not be loaded.&#x000D;&#x000A;</description>
    <guid>{7115CACC-895C-4BEA-BE84-706FD8DD69C1}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by erdembayar** [comment]
> 

This one is "Nomination error", it's quite different. It's "Project system" issue. Would you like me try to re-open your issue and ask Project system to take a look?

**Comment by flcdrg** [comment]
I might leave it for now - I just rebooted and haven't seen it again, so not sure if it's a one-off or not. If it does happen again I wonder if it's better to open a new issue given it probably has a different underlying cause.

**Comment by erdembayar** [comment]
> I might leave it for now - I just rebooted and haven't seen it again, so not sure if it's a one-off or not. If it does happen again I wonder if it's better to open a new issue given it probably has a different underlying cause.

You can uninstall installed custom built nuget.client with `VSIXInstaller.exe /d:NuGet.72c5d240-f742-48d4-a0f1-7016671e405b` command. Please check if problem resurfaces again.
