### ISSUE TITLE
Nuget update failing when symbol package is also present

### ISSUE THREAD

**Issue by Dynkan** [NuGet/Home#1066]
When a .nupkg and symbols.nupkg exist with the same version number, Nuget update is failing - complains about failing to read package metadata.

**Comment by brettjacobson** [comment]
I've been having the same problem, and stumbled upon the comment at the bottom of this blog that mentioned the same thing: https://britebit.wordpress.com/2013/10/02/troubleshooting-nuget-package-restore-on-a-tfs-build-server-there-are-multiple-root-elements-line-blah-position-blah/

This did not start happening from me until I updated to VS2015, and at the same time I updated my private Nuget server to 2.8.6. from 2.8.1.

**Comment by brettjacobson** [comment]
There doesn't seem to be a repository for Nuget.Server, is there even a good place to report this issue??

**Comment by yishaigalatzer** [comment]
https://github.com/nuget/nugetgallery is the repo for the server issues. However you are not supposed to have these two packages on the same server, and it makes sense for things to break. We can probably take a PR for a fix if you have one, but you should probably separate the nuget server from the symbol server.

We can take a look if we can make a client improvement here, for now the work around is to remove them.

**Comment by brettjacobson** [comment]
I just wanted to add that this had worked fine for 1.5 years on our internal Nuget repository (was server package version 2.8.1) with VS 2013.  It wasn't until I upgraded to VS2015 that this problem became apparent.
I hope this fix makes it into 3.2!

**Comment by MichelZ** [comment]
Same here. Updated to 2015, and now we get this issue

**Comment by yishaigalatzer** [comment]
We are running out of time for 3.2, so unfortunately this issue will not make it in.

The suggested workaround (and correct approach anyways) is not to put symbol packages on the same server.

**Comment by brettjacobson** [comment]
I think its a bit difficult to call it the "correct approach" since it worked fine for 1.5 years.  If you guys want to define it as a "breaking change, just suffer", that at least would be more palatable to me.

but then I would ask the question, why SHOULDN'T you keep symbol packages on the same internal-to-my-company's-LAN Nuget repository?  What is the rationale behind forcing us to have TWO separate nugget repositories?

**Comment by yishaigalatzer** [comment]
We are not saying it is a "breaking change, just suffer" we are saying the exact opposite: "Sorry we broke it, we are going to fix it, we somehow missed this scenario".

When it comes to the correct approach comment, I'm not sure why would you put a symbol package on the NuGet server share? Typically they go to two different servers (symbol servers or nuget servers). I asked a bit around and couldn't find the answer to why they should be on the same server. Can you enlighten me, this must be my ignorance.

**Comment by brettjacobson** [comment]
I'm starting to get the feeling that perhaps I have been "doing it wrong", because of a lack of sufficient documentation from Microsoft regarding hosting symbol packages for Nuget packages.
It appears that for the last 1.5 years I have not been getting the full symbol experience that I thought I was.

Is there anyone that can point out some recent, working, documentation on setting up an internal symbol server for Nuget packages, along side using Nuget.Server 2.8.6?
It doesn't seem that SymbolSource Server Basic can be made to work with latest MVC5 and dependencies, as its latest package is over two years old and built for MVC3.
Are there nothing but commercial, paid options for Symbol Serving?

**Comment by yishaigalatzer** [comment]
We don't have support for an internal symbol server from nuget packages, I'm not sure if you would consider it internal, but I believe myget supports a private symbol server (though hosted on their servers)

**Comment by yishaigalatzer** [comment]
@maartenba can we auto filter symbol packages from nuget.server? Can you please take over?

**Comment by maartenba** [comment]
So favor .nupkg over .symbols.nupkg?

**Comment by yishaigalatzer** [comment]
That's what I'm thinking

**Comment by maartenba** [comment]
Will be tackled with https://github.com/NuGet/NuGetGallery/issues/2824

**Comment by maartenba** [comment]
@Dynkan @brettjacobson @MichelZ Please try https://www.nuget.org/packages/NuGet.Server/2.10.0-master-0006

This functionality has been added as an option.

When `ignoreSymbolsPackages` is set to `true`, the server will never add symbols packages (that is if the file is named `.symbols.nupkg` or there is a `/src` folder in the package).

It is recommended to also set the `allowOverrideExistingPackageOnPush` option to `false` to ensure no packages are overwritten, e.g. when pushing a symbols package to `NuGet.Server`.

Note that symbols packages that already exist in you server should be removed first.

**Comment by yishaigalatzer** [comment]
@maarten should we make this option the default?

**Comment by maartenba** [comment]
Not sure. I know some people tend to only push symbols packages, so that would give them an issue. The current setting is backwards compatible, but I have no strong opinion either way. If defult makes sense, then let's make it default.

**Comment by yishaigalatzer** [comment]
In that case can we dig deeper to see why they are seeing an error? I didn't think people ever intentionally pushed symbol packages

**Comment by maartenba** [comment]
The combination of both being present gave the error here. Right now the server will only contain one version at all times (either non-symbols when ignoreSymbolsPackages is true, either "last one wins" when allowOverrideExisting is true or "first one wins" when allowOverrideExisting is false)

The error should no longer happen with our new bits.

**Comment by yishaigalatzer** [comment]
Sounds good. So here is an idea:

Why don't we set both parameters as follows:
1. Reject symbol packages
2. Reject override (and require a delete)

Then make sure we have a good readable error message with the explanation of what to do if the user really wants them set differently?

**Comment by maartenba** [comment]
Sounds good! Added this to the latest prerelease package.
