### ISSUE TITLE
[Bug Bash] Only the embedded license content of the latest version can be loaded correctly in PM UI when there are multiple versions in the same package from local feeds

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10670]
## Details about Problem
NuGet version: NuGet Client Dev\5.10.0.7170
VS Version: Main\31118.282
OS: Windows-10-Enterprise-20h1
## Repro steps and/or sample project
1.	Create a Class Library (.NET Framework 4.8) in VS and build the solution. 
2.	In the Developer Command Prompt for VS, cd to the project path and create a nuspec file by executing command “nuget spec”. 
3.	Make an image file (size limited to 1 MB with PNG format and 128x128 resolution) and locate in the package. 
4.	Make a License.txt and locate in the package. 
5.	Add following to nuspec file 
```
<package> 
  <metadata> 
    ... 
    <icon>images\icon.png</icon> 
    <license type="file">License.txt</license> 
  </metadata> 
  <files> 
    ... 
    <file src="[ProjectPath]\icon.png" target="images\" /> 
    <file src="[ProjectPath]\License.txt" target="" /> 
  </files> 
</package> 
```
6.	Pack the package to local path by executing command “nuget pack”. 
7.	Pack the same package with another version following step3-step6.
8.	Create a C# Console App (.NET Framework 4.8) in VS and open PM UI of the project/solution. 
9.	Add the package source as a local feed in Settings->NuGet Package Manager->Package Sources. 
10.	Select the new added local feed in the Package source dropdown box in the PM UI and click the package on the left panel.
11.	Choose a package version in the “Version” drop-down box on the right panel and click the “View License” link of every version. 
## Expected 
The embedded license content of every version can be loaded correctly in the PM UI.
## Actual
Only the embedded license content of the latest version can be loaded correctly as below.
![image](https://user-images.githubusercontent.com/20632625/111753067-604af680-88d1-11eb-89e0-9ffa910967f2.png)
## Notes
1.	Repro on both project-level PM UI and solution-level PM UI.
2.	Not a regression since it start to repro from the beginning of the embedded license feature in dev-rrelyea-remotefileservice\5.9.0.14330.

**Comment by donnie-msft** [comment]
maybe related https://github.com/NuGet/Home/issues/10546

**Comment by aortiz-msft** [comment]
@v-luzh - We could not repro with packages hosted in NuGet.org which is the most common scenario.

**Comment by v-luzh** [comment]
@aortiz-msft, OK, Thanks. I changed the pipeline to Icebox.
