### ISSUE TITLE
[Bug Bash] Package recommendor gave a wrong package-installing suggestion to C++ UWP project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10673]
## Details about Problem
NuGet version: NuGet Client Dev\5.10.0.7170
VS Version: Main\31118.282
OS: Windows-10-Enterprise-20h1
## Repro steps and/or sample project
1. Launch VS and click “Create a new project” button in the G2C dialog.
2. Create a Blank App (Universal Windows – C++/CX) template.
3. Open the PM UI of the project and go to “Browse” tab.
4. Try to install the first package “Newtonsoft.Json” suggested by the package recommendor (there is a start icon on the left of the suggested package name).
## Expected
Package recommendor should give a correct package-installing suggestion to C++ UWP project.
## Actual
Package recommendor gave a wrong package-installing suggestion to C++ UWP project as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/111754036-7d33f980-88d2-11eb-9dac-0850f5ec18d6.png)
## Note
It seems not a regression issue since it repro on 16.9 GA (D16.9\31025.194).

**Comment by zkat** [comment]
This is a known limitation in the current package recommender, and part of the roadmap already.
