### ISSUE TITLE
NuGet.CommandLine: nuget config <keyname> shows warning for non-existent keys and not an error

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1067]
NuGet.CommandLine: nuget config <keyname> shows warning for non-existent keys and not an error

Happens on both nuget.exe v2 and v3

Repro steps
1. Run 'nuget.exe config 'a non-existent keyname'

Expected:
An error in RED saying that the key does not exist

Actual:
WARNING: Key '<a non-existent keyname>' not found.

**Comment by RanjiniM** [comment]
Fixed

**Comment by RanjiniM** [comment]
The fix didn't go into 3.3.Commandline. Will check in the fix in 3.4

**Comment by RanjiniM** [comment]
Checked into dev branch (c65b1501f3a8aff024618cc9f46ad2c151bbd9b8)
