### ISSUE TITLE
[Bug Bash] Error “operation canceled by user” show in Error List window when switching between tabs quickly in PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10671]
## Details about Problem
NuGet version: NuGet Client Dev\5.10.0.7170
VS Version: Main\31118.282
OS: Windows-10-Enterprise-20h1
## Repro steps and/or sample project
1. Launch VS and click “Create a new project” button in the G2C dialog.
2. Create an ASP.NET Web Application (.NET Framework 4.8) ->Single Page Application.
3. Open the PM UI of the project and switch between the “Browse”/”Installed”/”Updates” tabs a little quickly.
## Expected
No error show in Error List window and the tab switch correctly.
## Actual
Error “operation canceled by user” show in Error List window as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/111753404-cc2d5f00-88d1-11eb-9e95-fdba7385578d.png)
## Note
Not a regression since it start to repro from the PR: Updating via Checkboxes no longer causes Null Reference Exception NuGet/NuGet.Client#3864

**Comment by donnie-msft** [comment]
The error is expected, but perhaps should be in Output Window or nowhere at all.
The state of packages looks good.
