### ISSUE TITLE
NuGet.CommandLine: Invalid config file for -ConfigFile parameter fails with weird error

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1068]
NuGet.CommandLine: Invalid config file for -ConfigFile parameter fails with weird error

Repro steps:
1. Run 'nuget config -ConfigFile <config file with invalid xml>' (Can use any nuget command that takes in a ConfigFile parameter)

Expected:
Command fails with error that the ConfigFile passed in is invalid or something to that effect

Actual:
Command fails with following error

"SetValue" cannot be called on a NullSettings. This may be caused on account of insufficient permissions to read or write to "%AppData%\NuGet\NuGet.config".

**Comment by zhili1208** [comment]
verified against latest bits, didn't repro.
