### ISSUE TITLE
dotnet pack accepts empty readme file

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10688]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe 
Product version: 5.0.300-preview.21173.7 downloaded from https://github.com/dotnet/installer/blob/main/README.md#installers-and-binaries

Worked before? If so, with which NuGet version: No.

## Repro steps and/or sample project

- Created `.NET Core` class library targeting `net5.0` platform
- Right Click on Project -> Add New Item -> General (Text) File -> Rename the file to "Readme.md" -> Click Ok
- New file added to the project
- Modified `.csproj` as shown below
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="readme.md" Pack="true" PackagePath=""/>
  </ItemGroup>
</Project>

```
- Executed `dotnet pack` command from the `Developer PowerShell` in VS.

### Actual
- Pack command generated package successfully.

### Expected 
- Pack command to throw `The readme file 'readme.md' is empty` error message.

### Few observations
- When VS created a new `readme.md`, the file size is displayed as 1kb even if it empty.
![image](https://user-images.githubusercontent.com/52756182/112383966-0cfaee80-8cab-11eb-8c69-bb7b581957f5.png)
- `Empty readme file` error is thrown if the file size is 0 

https://github.com/NuGet/NuGet.Client/blob/dc2fadacd311646754ce6b062489b403338972aa/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L907-L912

### Verbose Logs

```
> dotnet pack
Microsoft (R) Build Engine version 16.10.0-preview-21173-01+8d34753d2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  ClassLibrary1 -> C:\Users\User\source\repos\ConsoleApp21\ClassLibrary1\bin\Debug\net5.0\ClassLibrary1.dll
  Successfully created package 'C:\Users\User\source\repos\ConsoleApp21\ClassLibrary1\bin\Debug\ClassLibrary1.1.0.0.nupkg'.
```

**Comment by zkat** [comment]
I'm pretty much fine with there being an empty readme :)

**Comment by zivkan** [comment]
@zkat why are you fine with it?

Any scenario where the readme should be shown to the user will look like a bug if the tool effectively says "This package has a readme and the contents are: ` `".

To avoid this, every single implementation (nuget client, nuget.org, every other nuget server with browse functionality, rider, anyone with custom nuget tooling) will have to duplicate effort to treat an empty file the same as no readme.

Doesn't feel like a good end to end customer experience to me.

**Comment by zkat** [comment]
I see it as a corner case that doesn't need extra attention. I don't think it should be treated as a missing file. I think it should be rendered exactly as it is: With no content.
