### ISSUE TITLE
why float version cannot work with pre-release version in this situation

### ISSUE THREAD

**Issue by Perry004** [NuGet/Home#10686]
I have some problems with float version.

In my side,  I have these package version including pre-release version under the local package source.

![image](https://user-images.githubusercontent.com/52026687/112280791-57d33100-8cc0-11eb-9dd2-22afbe82146a.png)

As the picture shows, `modd 1.0.3` nuget package  has three versions, the formal version and the pre-release versions.

In my side, I want to use the pre-release version of `1.0.3`, I then used this xml node:

```
<ItemGroup>
		<PackageReference Include="Modd" Version="1.0.3-*" />
</ItemGroup>
```

But I always get the formal  version of `1.0.3` rather than `1.0.3-beta1`. Why?

I know I can use `1.0.*-*` and `1.*-*` to get it work but that always gets the version `1.0.4.beta1` and I want to use the latest pre-release version of `1.0.3`  in my needs. That get the latest pre-release of a specific `1.0.3` sounds not a difficult thing.

After I research, I found that  when the nuget package source contains the formal version of `1.0.3` version,  the `1.0.3-*` will never work.  When I delete `Modd 1.0.3.nupkg` under the package source,  the `1.0.3-*` works perfectly. So why this happen? Why the formal `1.0.3` version affects the pre-release version with `1.0.3-*`?

**Comment by heng-liu** [comment]
Hi @Perry004 , thanks for asking this question.
My understanding is, 1.0.3 is a stable version, which is already released, so it's greater than any pre-release versions.
From the proposal https://github.com/NuGet/Home/blob/dev/proposed/archive/FloatingStableAndPrerelease.md#scenarios, we can see:
![image](https://user-images.githubusercontent.com/45407901/112381300-aa542380-8ca7-11eb-9163-03a39439856e.png)

You may also try the [tool](https://nugettoolsdev.azurewebsites.net/5.8.0/find-best-version-match?versionRange=1.0.3-*&versions=1.0.3%0D%0A1.0.3-beta1) to check which version will be resolved. Just remember to chose the right version of the tool.

Pls let us know if you have any further questions.
