### ISSUE TITLE
NU3028, NU3037 when trying to restore a project

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10684]
---
**Issue moved from dotnet/sdk#16482**
- Please respond to @IdkGoodName.

---

_From @IdkGoodName on Tuesday, March 23, 2021 5:00:59 PM_

I seem to have issues trying to restore a C# or F# project. I get tons of NuGet signature errors and I don't know what it is caused by. I tried completely reinstalling .NET, but it doesn't seem to work.

# Errors

This is what I get when trying to build C# console project:
```
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3037: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
```
C# library project:
```
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3037: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Channels 4.7.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3037: Package 'System.Threading.Tasks.Extensions 4.5.3' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.3' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3037: Package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.csproj : error NU3028: Package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.2' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.csproj : error NU3037: Package 'System.Threading.Tasks.Extensions 4.5.2' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.csproj : error NU3028: Package 'System.Threading.Tasks.Extensions 4.5.2' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
```

F# console project:
```
/.../ProjectName.fsproj : error NU3028: Package 'FSharp.Core 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
/.../ProjectName.fsproj : error NU3037: Package 'FSharp.Core 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired.
/.../ProjectName.fsproj : error NU3028: Package 'FSharp.Core 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: UntrustedRoot: self signed certificate in certificate chain
```

# Info

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     artix
 OS Version:  20201128
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#16482**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Tuesday, March 23, 2021 5:01:02 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by IdkGoodName** [comment]
Ok, I managed to fix it. I apparently set `MSBuildSDKsPath` to a specific path and that's what caused it to throw bunch of errors.

**Comment by heng-liu** [comment]
Hi @IdkGoodName, may I know how did you fix it? Thanks.
It looks like the packages validation failed during restore. 
So I'm not sure why changing MSBuildSDKsPath works. 
May I know if you specify a SDK version earlier than 5.0 so there is no package validation there?
If so, I'm afraid we still need to look into it if package validation in 5.0.201 doesn't work.

**Comment by IdkGoodName** [comment]
Huh. I am not even sure myself. Deleting .NET fully without any leftovers and removing `MSBuildSDKsPath` worked for me... temporarily... Now it happens again and I have to reinstall it entirely. It's pretty annoying to keep deleting .NET and rebuilding it.

**Comment by IdkGoodName** [comment]
It happens randomly too even if I don't touch .NET in any way.

**Comment by heng-liu** [comment]
Yes, we validate the package before extracting the package into global package folder.
So if the package is not in global package folder yet, any restore using dotnet 5.0 above (or nuge.exe and vs on windows) will do the validation.

Could you run command `dotnet nuget verify <package-path> -v d` and paste the output here? Thanks!

FYI @dtivel @JonDouglas, it might be caused by artix removes root certificate.

**Comment by IdkGoodName** [comment]
`<package-path>` being what? `~/.nuget/packages/<package-name>/...`?

**Comment by dtivel** [comment]
This sounds like https://github.com/NuGet/Announcements/issues/49.  @IdkGoodName, is your OS is also affected?

Try this:
1.  Save this PEM-encoded certificate to file (e.g.:  cert.pem).
```
-----BEGIN CERTIFICATE-----
MIIEuTCCA6GgAwIBAgIQQBrEZCGzEyEDDrvkEhrFHTANBgkqhkiG9w0BAQsFADCB
vTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwOCBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MTgwNgYDVQQDEy9W
ZXJpU2lnbiBVbml2ZXJzYWwgUm9vdCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAe
Fw0wODA0MDIwMDAwMDBaFw0zNzEyMDEyMzU5NTlaMIG9MQswCQYDVQQGEwJVUzEX
MBUGA1UEChMOVmVyaVNpZ24sIEluYy4xHzAdBgNVBAsTFlZlcmlTaWduIFRydXN0
IE5ldHdvcmsxOjA4BgNVBAsTMShjKSAyMDA4IFZlcmlTaWduLCBJbmMuIC0gRm9y
IGF1dGhvcml6ZWQgdXNlIG9ubHkxODA2BgNVBAMTL1ZlcmlTaWduIFVuaXZlcnNh
bCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEAx2E3XrEBNNti1xWb/1hajCMj1mCOkdeQmIN65lgZOIzF
9uVkhbSicfvtvbnazU0AtMgtc6XHaXGVHzk8skQHnOgO+k1KxCHfKWGPMiJhgsWH
H26MfF8WIFFE0XBPV+rjHOPMee5Y2A7Cs0WTwCznmhcrewA3ekEzeOEz4vMQGn+H
LL729fdC4uW/h2KJXwBL38Xd5HVEMkE6HnFuacsLdUYI0crSK5XQz/u5QGtkjFdN
/BMReYTtXlT2NJ8IAfMQJQYXStrxHXpma5hgZqTZ79IugvHw7wnqRMkVauIDbjPT
rJ9VAMf2CGqUuV/c4DPxhGD5WycRtPwW8rtWaoAljQIDAQABo4GyMIGvMA8GA1Ud
EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMG0GCCsGAQUFBwEMBGEwX6FdoFsw
WTBXMFUWCWltYWdlL2dpZjAhMB8wBwYFKw4DAhoEFI/l0xqGrI2Oa8PPgGrUSBgs
exkuMCUWI2h0dHA6Ly9sb2dvLnZlcmlzaWduLmNvbS92c2xvZ28uZ2lmMB0GA1Ud
DgQWBBS2d/ppSEefUxLVwuoHMnYH0ZcHGTANBgkqhkiG9w0BAQsFAAOCAQEASvj4
sAPmLGd75JR3Y8xuTPl9Dg3cyLk1uXBPY/ok+myDjEedO2Pzmvl2MpWRsXe8rJq+
seQxIcaBlVZaDrHC1LGmWazxY8u4TB1ZkErvkBYoH1quEPuBUDgMbMzxPcP1Y+Oz
4yHJJDnp/RVmRvQbEdBNc6N9Rvk97ahfYtTxP/jgdFcrGJ2BtMQo2pSXpXDrrB2+
BxHw1dvd5Yzw1TKwg+ZX4o+/vqGqvz0dtdQ46tewXDpPaj+PwGZsY6rp2aQW9IHR
lRQOfc2VNNnSj3BzgXucfr2YYdhFh5iQxeuGMMY1v/D/w1WIg0vvBZIGcfK4mJO3
7M2CYfE45k+XmCpajQ==
-----END CERTIFICATE-----
```
2. Open a shell prompt and execute:  `openssl verify -verbose cert.pem`

What output do you get?

**Comment by dtivel** [comment]
Also check your ca-certificates.conf file --- at /etc/ca-certificates.conf , I'm guessing --- to see what the status is of
```
mozilla/VeriSign_Universal_Root_Certification_Authority.crt
```
Is that line even present?  Does it have a leading bang (!)?
```
!mozilla/VeriSign_Universal_Root_Certification_Authority.crt
```

**Comment by IdkGoodName** [comment]
> This sounds like [NuGet/Announcements#49](https://github.com/NuGet/Announcements/issues/49). @IdkGoodName, is your OS is also affected?
> 
> Try this:
> 
>     1. Save this PEM-encoded certificate to file (e.g.:  cert.pem).
> 
> 
> ```
> -----BEGIN CERTIFICATE-----
> MIIEuTCCA6GgAwIBAgIQQBrEZCGzEyEDDrvkEhrFHTANBgkqhkiG9w0BAQsFADCB
> vTELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
> ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwOCBWZXJp
> U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MTgwNgYDVQQDEy9W
> ZXJpU2lnbiBVbml2ZXJzYWwgUm9vdCBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTAe
> Fw0wODA0MDIwMDAwMDBaFw0zNzEyMDEyMzU5NTlaMIG9MQswCQYDVQQGEwJVUzEX
> MBUGA1UEChMOVmVyaVNpZ24sIEluYy4xHzAdBgNVBAsTFlZlcmlTaWduIFRydXN0
> IE5ldHdvcmsxOjA4BgNVBAsTMShjKSAyMDA4IFZlcmlTaWduLCBJbmMuIC0gRm9y
> IGF1dGhvcml6ZWQgdXNlIG9ubHkxODA2BgNVBAMTL1ZlcmlTaWduIFVuaXZlcnNh
> bCBSb290IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0BAQEF
> AAOCAQ8AMIIBCgKCAQEAx2E3XrEBNNti1xWb/1hajCMj1mCOkdeQmIN65lgZOIzF
> 9uVkhbSicfvtvbnazU0AtMgtc6XHaXGVHzk8skQHnOgO+k1KxCHfKWGPMiJhgsWH
> H26MfF8WIFFE0XBPV+rjHOPMee5Y2A7Cs0WTwCznmhcrewA3ekEzeOEz4vMQGn+H
> LL729fdC4uW/h2KJXwBL38Xd5HVEMkE6HnFuacsLdUYI0crSK5XQz/u5QGtkjFdN
> /BMReYTtXlT2NJ8IAfMQJQYXStrxHXpma5hgZqTZ79IugvHw7wnqRMkVauIDbjPT
> rJ9VAMf2CGqUuV/c4DPxhGD5WycRtPwW8rtWaoAljQIDAQABo4GyMIGvMA8GA1Ud
> EwEB/wQFMAMBAf8wDgYDVR0PAQH/BAQDAgEGMG0GCCsGAQUFBwEMBGEwX6FdoFsw
> WTBXMFUWCWltYWdlL2dpZjAhMB8wBwYFKw4DAhoEFI/l0xqGrI2Oa8PPgGrUSBgs
> exkuMCUWI2h0dHA6Ly9sb2dvLnZlcmlzaWduLmNvbS92c2xvZ28uZ2lmMB0GA1Ud
> DgQWBBS2d/ppSEefUxLVwuoHMnYH0ZcHGTANBgkqhkiG9w0BAQsFAAOCAQEASvj4
> sAPmLGd75JR3Y8xuTPl9Dg3cyLk1uXBPY/ok+myDjEedO2Pzmvl2MpWRsXe8rJq+
> seQxIcaBlVZaDrHC1LGmWazxY8u4TB1ZkErvkBYoH1quEPuBUDgMbMzxPcP1Y+Oz
> 4yHJJDnp/RVmRvQbEdBNc6N9Rvk97ahfYtTxP/jgdFcrGJ2BtMQo2pSXpXDrrB2+
> BxHw1dvd5Yzw1TKwg+ZX4o+/vqGqvz0dtdQ46tewXDpPaj+PwGZsY6rp2aQW9IHR
> lRQOfc2VNNnSj3BzgXucfr2YYdhFh5iQxeuGMMY1v/D/w1WIg0vvBZIGcfK4mJO3
> 7M2CYfE45k+XmCpajQ==
> -----END CERTIFICATE-----
> ```
> 
>     1. Open a shell prompt and execute:  `openssl verify -verbose cert.pem`
> 
> 
> What output do you get?

```
C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2008 VeriSign, Inc. - For authorized use only", CN = VeriSign Universal Root Certification Authority
error 18 at 0 depth lookup: self signed certificate
error cert.pem: verification failed
```

**Comment by heng-liu** [comment]
So the root cert is not trusted on artix.
Shall we add this into https://github.com/NuGet/Announcements/issues/49 ?

**Comment by kokopi-dev** [comment]
Having same issue on Arch Linux.
linux kernel 5.11.8
dotnet version 5.0.104

**Comment by kokopi-dev** [comment]
I actually fixed this by downgrading ca-certificates-mozilla 3.63-1 to 3.62-1 using AUR's `downgrade`

**Comment by JonDouglas** [comment]
Please note that a .NET 5 release is now available that should resolve this issue. You can find a link to download it on the announcement below:

https://github.com/NuGet/Announcements/issues/56

**Comment by aortiz-msft** [comment]
Closing per last comment. Thank you for your feedback!
