### ISSUE TITLE
Add flag/option to enable or disable mmap in NuGet

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10692]
To better understand mmap effects on NuGet restore, consider adding a flag/option that controls mmap activation in NuGet.

See how NuGet uses mmap at: https://github.com/NuGet/Home/issues/9807

## Design draft

- The flag should work on command line scenarios.
- For SDK-style and Legacy .csproj projects: use a property in the project files: `<DisableMmap>true</DisableMmap>`
- For packages.config, consider adding a flag in `nuget.exe restore`: `-disableMmap`
- VS should use the flag when restoing SDK-style and Legacy PackageReference projects.

**Comment by nkolev92** [comment]
I don't think we should do this. 
We shouldn't subject customers to experiment just to look at performance in the wild. 
Our lab measurements should be enough for this.

**Comment by JonDouglas** [comment]
Unless there is a discrepancy of this flag on other factors like restore success, user experience, etc then we should just leave it on by default / included in the box as a perf win IMO.
