### ISSUE TITLE
GetReferenceNearestTargetFrameworkTask should not log params when LogTaskInputs is set

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#10696]
When MSBuild sets LogTaskInputs, there's no need to specifically log task inputs or outputs as MSBuild will take care of that.

See here:
https://github.com/NuGet/NuGet.Client/blob/58fd22bfc941a6d5cc9404f41a583efb4dfeeaf0/src/NuGet.Core/NuGet.Build.Tasks/GetReferenceNearestTargetFrameworkTask.cs#L64

See https://github.com/dotnet/msbuild/issues/6305 for guidance. Otherwise there's duplication, allocations, log bloat:
![image](https://user-images.githubusercontent.com/679326/112683759-4e1c0b80-8e2f-11eb-8802-27d71ff218bb.png)

**Comment by KirillOsenkov** [comment]
This should also apply to:

1. GetRestoreProjectStyleTask
2. GetRestorePackageReferencesTask
3. GetRestoreSolutionProjectsTask
4. WarnForInvalidProjectsTask
5. GetRestoreSettingsTask
6. GetRestoreDotNetCliToolsTask
7. GetRestoreProjectReferencesTask

and potentially others I'm missing.

**Comment by nkolev92** [comment]
There's no public API available yet.

**Comment by KirillOsenkov** [comment]
This is the public API that we'll want you to use once it's available:
https://github.com/dotnet/msbuild/pull/6803

**Comment by KirillOsenkov** [comment]
I'm looking at a 1 GB binlog and I see hundreds of MB of strings coming from this superfluous logging. The worst part is the strings are concatenated, which means huge allocations and no string deduplication in binlogs. 

It would be nice to revisit this since the API is already available. If log task inputs is set (or maybe check for the MSBUILDBINARYLOGGERENABLED environment variable), just don't log these.

@jeffkl

**Comment by KirillOsenkov** [comment]
See how redundant they are?

![image](https://github.com/NuGet/Home/assets/679326/ee56ccb3-ae5f-4daa-b848-97ac7b176884)

I expect for large builds (>1052 projects in our case here) we'll see very significant space savings and possible less allocations and faster build. If we save 100 MB per binlog, 100 CI builds per day, 1000s of CI builds worldwide, this would be noticeable impact.
