### ISSUE TITLE
Visual Studio Manage Package for Solutions shows error while browsing packages from an internal JFrog NuGet Artifactory

### ISSUE THREAD

**Issue by dnaranjor** [NuGet/Home#10707]
## Details about Problem

NuGet product used: Visual Studio

Product version: Community 2019

Worked before?: No

## Repro steps and/or sample project

In a fresh install of Visual Studio Community 2019, I need to setup as Repository an internal JFrog Artifactory server, Commercial license 7.7.8 rev 70708900.

After opening a brand new Project in Visual Studio, I click on Tools > NuGet Package Manager > Manage Package for Solutions, and in the opened window, select the Gear icon to edit Repositories settings.

In that new window, I select Package Sources > "+" button to add a new source.

Enter the information in required fields:

Name: Arfitactory
Source: https://<my_artifactory_URL>/artifactory/api/nuget/<nuget_virtual_repo_name>/index.json

And finally, click on "Update" button and close the settings window pushing on the "Ok" button.

After this configuration, if I try to browse Artifactory Nuget content, I end up with the following error:

[Artifactory] Unable to load the service index for source https://<my_artifactory_URL>/artifactory/api/nuget/<nuget_virtual_repo_name>/index.json. 
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.

**Comment by donnie-msft** [comment]
If you navigate to your index.json URL, and manually check the Certificate, is it showing as valid?

**Comment by dnaranjor** [comment]
Actually no. In a browser the URL appear as invalid, so I have to manually
instruct the browser to allow it so I can get the content

**Comment by donnie-msft** [comment]
In that case, NuGet is responding as expected. I'd suggest you investigate the problem from both directions:
1. Is JFrog configured correctly? See https://www.jfrog.com/confluence/display/JFROG/Managing+TLS+Certificates.
2. Is your Windows installation trusting the certificates for your package source?

You may find a tool like `certutil` helpful, https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil.
For example, if your Windows installation has an altered Trusted CA list, a command like this may help you restore those: `certutil -verifyCTL authrootwu > roots.txt`

If you still believe there's an issue with NuGet, please let us know.
