### ISSUE TITLE
System.BadImageFormatException after installing my nuget

### ISSUE THREAD

**Issue by althurman** [NuGet/Home#10703]
NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe ):

Product version: 
Visual Studio 2019

Worked before? If so, with which NuGet version: 
Works with nuget that was created on my Win 10 laptop. I get a runtime exception when using the nuget packed on my build machine

I have my own solution that builds a .dll (mytest.dll). I then pack the .dll for referencing into a nuget package using a .nuspec file. When doing this process on my laptop, I can install the nuget into a test app and create objects from the nuget in the code no problem.

Testing on my build machine, which is Windows Server 2012 R2, I do this same process but after installing the nuget and trying to run my test app I get a runtime exception:

System.BadImageFormatException: 'Could not load file or assembly 'mytest.dll' or one of its dependencies. is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)'

Any ideas on what to check on the Windows Server machine? 

Note: 1. Both machines have Visual Studio 2019 used to build 2. I use nuget.exe from the command line to pack the nuget (nuget update --self before packing)

**Comment by dominoFire** [comment]
Are you compiling for .NET Framework, .NET Core or Native?

Did you take a look at this [article](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/0x800700c1-not-valid-win32-application-applocker-hash-rule) ?

Are you directly referencing the .dll assembly? or are you using a local or remote NuGet Feed to use your package in your remote computer?

**Comment by althurman** [comment]
> Are you compiling for .NET Framework, .NET Core or Native?
> 
> Did you take a look at this [article](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/0x800700c1-not-valid-win32-application-applocker-hash-rule) ?
> 
> Are you directly referencing the .dll assembly? or are you using a local or remote NuGet Feed to use your package in your remote computer?

.Net Framework 4.7.1

For the referencing I have actually tested both ways at this point. I have even just run it in debug mode on the server and I get the same thing. SO I think at this point it is not specifically a nuget issue. I'll check out the article as well. Thanks
