### ISSUE TITLE
.nupkg.metadata missing when executing 'nuget add -Expand' from  Azure DevOps MSBuild task

### ISSUE THREAD

**Issue by wouterroos** [NuGet/Home#10701]
## Details about Problem

NuGet product used (NuGet.exe | MSBuild.exe):

Product version: 4.7.1, 5.8.1, 5.9.0

## Repro steps and/or sample project

Hi,

We're using the -Expand option in a MSBuild task to publish newly generated NuGet packages to a local fallback folder (see below).

```
<Target Name="PublishLocalNugetPackage" AfterTargets="Pack;DeleteExistingLocalNuGetPackage">                
  <Exec Command="nuget add $(PackageOutputPath)$(PackageId).$(Version).nupkg -Expand -Source $(LocalNugetFeedPath) -Verbosity detailed"/>
</Target>
```

This works beautifully when invoking MSBuild from the command line. However, when we use the `MSBuild@1` task in our Azure DevOps pipeline, (everything seems to go just fine, no errors or anything) we end up with an expanded package that is missing the `.nupkg.metadata` file (see images below), which seems to cause subsequent steps that use the fallback folder to fail with the following error (package id ommitted):

`Error NU1101: Unable to find package <PACKAGEID>. No packages exist with this id in source(s): Project.Tools, nuget.org` 

_Build agent output_
![image](https://user-images.githubusercontent.com/5137829/112953964-3b127f80-913e-11eb-8dbe-7949e78faa06.png)

_MSBuild command executed manually (same machine)_
![image](https://user-images.githubusercontent.com/5137829/112954000-4796d800-913e-11eb-8922-28deb91192b8.png)

I'd like to get some confirmation that the missing `.nupkg.metadata` file is indeed causing the issue that subsequent steps that rely on the fallback folder are failing and if so, what we can do to solve the issue.

Thanks! 

### Verbose Logs
(package id ommitted)
```
15>PublishLocalNugetPackage:
         NuGet Version: 4.7.1.5393
         Acquiring lock for the installation of <PACKAGEID> 3.0.325
         Acquired lock for the installation of <PACKAGEID> 3.0.325
         Installing <PACKAGEID> 3.0.325.
         Completed installation of <PACKAGEID> 3.0.325
         Successfully added package 'C:\agent\_work\2\s\nuget\nupkg\Release\<PACKAGEID>.3.0.325.nupkg' to feed 'C:\agent\_work\2\s\nuget\project-local\'.
```

**Comment by nkolev92** [comment]
I think when .nupkg.metadata was originally, this behavior was as intendend, https://github.com/NuGet/Home/wiki/Nupkg-Metadata-File#solution. 

However, NuGet doesn't consume this file in non-lock file scenarios, so normally I wouldn't expect you'd get that error as a consequence of the .nupkg.metadata file not being present.

Someone on our team will take a further look. 
cc @dominoFire

**Comment by wouterroos** [comment]
@nkolev92 @dominoFire  Thanks! Do you have an ETA on when you guys will have a look/the issue will be fixed? We are currently blocked by this issue so I would like to plan accordingly.

**Comment by dominoFire** [comment]
I tested with `nuget.exe 5.8.1` and it extracted the nupkg.

```
PS> nuget add .\packageId.1.0.0.nupkg -expand -source C:\nupath1 -Verbosity detailed
NuGet Version: 5.8.1.7021
Acquiring lock for the installation of packageId 1.0.0
Acquired lock for the installation of packageId 1.0.0
Installing packageId 1.0.0.
Completed installation of packageId 1.0.0
Successfully added package '.\packageId.1.0.0.nupkg' to feed 'C:\nupath1'
```

![image](https://user-images.githubusercontent.com/1192347/113558885-4c7fdf80-95b5-11eb-9070-f263719d6a12.png)


On the other hand, using `nuget.exe 4.7.3`, it does _not_ extract the metadata file

```
PS> nuget.4.7.3 add .\packageId.1.0.0.nupkg -expand -source C:\nupath2 -Verbosity detailed
NuGet Version: 4.7.3.5893
Acquiring lock for the installation of packageId 1.0.0
Acquired lock for the installation of packageId 1.0.0
Installing packageId 1.0.0.
Completed installation of packageId 1.0.0
Successfully added package '.\packageId.1.0.0.nupkg' to feed 'C:\nupath2'.
```

![image](https://user-images.githubusercontent.com/1192347/113558911-56a1de00-95b5-11eb-9b4f-dca8d5a80dda.png)

.nupkg metadata file was introduced in NuGet 4.9; see [Release Notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm).

As a workaround, I would use NuGet Tool Installer task to ensure having latest NuGet.exe.

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/nuget?view=azure-devops

**Comment by wouterroos** [comment]
@dominoFire Thanks, that seems to solve the issue.
