### ISSUE TITLE
Implement new precedence for xamarin TFMs when using net6.0+

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#10717]
As part of net6.0, we're implementing [new compatibility rules for xamarin TFMs](https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md#compatibility-rules). This is a tracking issue for implementing the precedence part of it.

Note: This should be feature-flagged for inclusion in 16.10.

**Comment by jonathanpeppers** [comment]
@zkat could this get reopened until we have Android, too? Or is there another issue I could track? Thanks!

**Comment by mattleibow** [comment]
I added my info to a new issue: https://github.com/NuGet/Home/issues/10889

The two worlds are not playing nice at all with the Android stuff. I tried using AssetTargetFallback in some hope to work around it, but still all crazy.
