### ISSUE TITLE
Unable to open NuGet when the solution has TFS source control bindings from 2013

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1071]
The NuGet package fails to load on Visual Studio 2015 when the solution has source control bindings to TFS from Visual Studio 2013.

Details are explained here:
http://samirvaidya.blogspot.com/2015/07/the-nugetpackage-package-did-not-load.html

**Comment by emgarten** [comment]
@zhili1208 can you verify if this is fixed in 3.1.1?

**Comment by zhili1208** [comment]
repro it on RTM 3.0, verified it's fixed in 3.1.60724.766
