### ISSUE TITLE
Clarify and implement the strict mode scenarios 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10729]

**Comment by nkolev92** [comment]
cc @JonDouglas as we progress in the implementation, we will need to clarify and ensure we're happy with the strict mode proposal.

**Comment by nkolev92** [comment]
Unassigning this from myself because of hot seat.

**Comment by kartheekp-ms** [comment]
Child tasks.
- [ ] https://github.com/NuGet/Home/issues/11150

**Comment by nkolev92** [comment]
When defining child tasks can you please use zenhub?

GH's epics are nice, but they don't see estimates cause they are a zenhub feature.

**Comment by kartheekp-ms** [comment]
Unassigned this task due to change in the priorities. Most of the work for this epic is in https://github.com/NuGet/NuGet.Client/tree/dev-kartheekp-ms-pr-namespacesmode branch.

**Comment by nkolev92** [comment]
Closing this. We'll listen to feedback.
