### ISSUE TITLE
build.sh script should build cross-platform binaries

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10726]
Update build.sh script to build binaries for source-build.

source-build 5.0 uses two MSBuild commands to build cross-platform binaries, as shown below.

https://github.com/dotnet/source-build/blob/c13177f2205e4eb8e19e08ac45889b793edc9a2d/repos/nuget-client.proj#L42

**Comment by nkolev92** [comment]
Can you link a general motivation for this issue?
Ideally something on source-build side?

**Comment by dominoFire** [comment]
This issue was for source-build efforts. Fixed in https://github.com/NuGet/NuGet.Client/pull/4105/files
