### ISSUE TITLE
Ensure the namespaces filtering is respected in packages.config package installation/updates in PMUI

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10738]
In PR, restore and package installation are equivalent. 
In PC they are not. 

This task covers ensuring that the namespaces are respected during package installation. 

*Detailed explanation:*

* In https://github.com/NuGet/Home/issues/10823, support for namespaces filtering was added in restore. 
* This issue ensures that commands run through:
    * Package Manager UI, both project level and solution level (I don't expect code differences here, just being explicit)
   
~~Please consider splitting up the work in smaller tasks whenever possible to allow for easier reviewing~~
I created separate issues for:
   * PMC, any commands. https://github.com/NuGet/Home/issues/11001
    * Any IVs installer APIs. https://github.com/NuGet/Home/issues/11002

**Comment by erdembayar** [comment]
@nkolev92 
Can you elaborate on `Any IVs installer APIs`? What could be example of this?

**Comment by zivkan** [comment]
Our [NuGet extensibility in Visual Studio docs](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio) detail our `IVs*` APIs. Also see [the interface definitions](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility), particularly [`IVsPackageInstaller.cs`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility/IVsPackageInstaller.cs) (and `IVsPackageInstaller2`).

Roslyn use it when you have two projects in the solution, one of them use a package, and the other does not. When you write code in the project that does not use the package, Roslyn will give you a lightbulb fix to install the package into the project.

Another way to test it is via our [API testing extension](https://github.com/NuGet/Entropy/tree/main/IVsTestingExtension)

**Comment by nkolev92** [comment]
I'd expect https://github.com/NuGet/Home/issues/10961 to be largely solved by this effort as well.

**Comment by nkolev92** [comment]
Hey @erdembayar 

When breaking down tasks can you please make sure they are all added in the same epic? (You need ZH for that). 

Doing that is necessary for tracking purposes. Ex, now only 10 points are shown as leftover and I don't think that's the case..

**Comment by nkolev92** [comment]
The epic is https://github.com/NuGet/Home/issues/10728.

**Comment by nkolev92** [comment]
Putting back the original estimate of 15
