### ISSUE TITLE
`NuGetProjectManagerService` calls to get installed packages should batch projects

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#10740]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): VS

Product version: all

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

The following methods are called repeatedly for each project, rather than batched:
```
IProjectContextInfoExtensions.GetInstalledPackagesAsync(this IProjectContextInfo projectContextInfo, projectContextInfos,,)
->
NuGetProjectManagerService.GetInstalledPackagesAsync(IReadOnlyCollection<string> projectIds,)
```

Batching these may save significant overhead in common PM UI actions, and reduce the overall load times for any Tab, event, or action that triggers them (eg, loading of any of the 4 tabs, all Package Management buttons, selecting a package, changing sources, external changes to project).

Related to https://github.com/nuget/home/issues/10356.

**Comment by nkolev92** [comment]
Team Triage: A bit stale at this point.
