### ISSUE TITLE
Not Compatible

### ISSUE THREAD

**Issue by christianwinters1989** [NuGet/Home#10741]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 5.0.5 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore 5.0.5 supports: net5.0 (.NETCoreApp,Version=v5.0)	BulkyBook2	C:\Users\christian.winters\Desktop\BulkyBook-master\BulkyBook2\BulkyBook2\BulkyBook2.csproj	1

**Comment by nkolev92** [comment]
Hey @christianwinters1989 

Unfortunately this is not enough information for us to be able to investigate. 

You *likely* need to just upgrade the version of the tooling you are using. 
NuGet.exe 5.8, dotnet SDK 5.0.100 & Visual Studio 16.8 and later have support for the new framework.

**Comment by zkat** [comment]
No response from customer for 14 days, so I'm going to close this.
