### ISSUE TITLE
MsBuild restore task doesn't use packages.config path from RestorePackagesConfigPath

### ISSUE THREAD

**Issue by Nekkiton** [NuGet/Home#10744]
I use the latest MSBuild version to restore NuGet packages from the packages.config file. There are a lot of properties Restore* that I can manage to change needed fields. One of this property is RestorePackagesConfigPath but as it turned out this property doesn't matter at all, since the path to this file is hardcoded as project folder path + "packages.config" constant (see line 477 NuGet.Client/src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs)

Сan we add the use of this property or this is intentional and there is a kinda special reason not to do that?

**Comment by Nekkiton** [comment]
@nkolev92 I see you're responsible for some NuGet restore tasks, could you look at this thread? If we can add support of RestorePackagesConfigPath property, I can prepare PR for that.

**Comment by nkolev92** [comment]
Hey @Nekkiton, 

Unfortunately I don't think we should support the `RestorePackagesConfigPath` property. It is only an intermediate in the msbuild implementation. 

The msbuild version of packages.config restore is supposed to be used as a way to enable the migration to `msbuild /t:restore` for customers that have a mix of projects. 
Adding the support of that property would be adding a new feature to the packages.config restore and at this point we don't want to add that.
