### ISSUE TITLE
Create experimentation metrics to measure engagement of transitive dependencies

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10759]

**Comment by dominoFire** [comment]
Some thoughts:

- Add click through rate on transitive packages list elements in PM UI
- Add Transitive Origins API run-time/execution time
- Monthly Active users on Transitive Dependencies.

**Comment by dominoFire** [comment]
More thoughts:

- Number of installed Packages shown
- Number of Transitive Packages shown

**Comment by dominoFire** [comment]
Created assessment metrics doc: https://github.com/NuGet/Client.Engineering/pull/1489/files

**Comment by dominoFire** [comment]
Created first metric: Error Rate: https://experimentation.visualstudio.com/ExpMetrics/_git/VisualStudioInProc/pullrequest/149476

**Comment by dominoFire** [comment]
Create Experimentation Entry Review Template: https://github.com/microsoft/devdiv-exp-reviews/issues/126

**Comment by dominoFire** [comment]
Added minimal telemetry to determine experiment success. https://github.com/NuGet/Client.Engineering/issues/1497

Other telemetry can de added for detailed data analysis on how customers use the feature.

**Comment by dominoFire** [comment]
Lowering estimate to reflect progress from previous sprint. Still some metrics to implement.

**Comment by martinrrm** [comment]
Completed in Azure DevOps, https://experimentation.visualstudio.com/ExpMetrics/_git/VisualStudioInProc/pullrequest/156881
