### ISSUE TITLE
Make the Installed tab group by dependency type, e.g. "Top-level packages" or "Transitive packages"

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10750]
Make the Installed tab group by dependency type, e.g. "Top-level packages" or "Transitive packages" with transitive dependencies collapsed by default

**Comment by dominoFire** [comment]
Reminder: Add a counter for the number of packages in each group 

From comment: https://github.com/NuGet/NuGet.Client/pull/4465#issuecomment-1054413343
