### ISSUE TITLE
Add caching of the transitive dependencies data pulled from the lockfile (assets file)

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10752]

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/blob/7721feed7c830d5d11f6c43a2205888f36d7e4ab/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProject.cs#L45-L46 and https://github.com/NuGet/NuGet.Client/blob/7721feed7c830d5d11f6c43a2205888f36d7e4ab/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProject.cs#L40-L41 might help.

**Comment by dominoFire** [comment]
Updating issue estimate due to API design review.

**Comment by dominoFire** [comment]
Lowering estimate to zero. No more substantial work is needed to enable caching in Transitive origins.
