### ISSUE TITLE
Read and store the transitive origins of a package while reading installed packages from assets file

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10751]
Add an API to fetch the top-level package that installs a given transitive dependency -- read the dependency tree from the lockfile (assets file)

From design review, we decided to modify an existing API to include transitive origins information.

Modified API: `NuGetProjectManagerService.GetInstalledAndTransitivePackagesAsync()`

**Comment by zivkan** [comment]
Keep in mind there may be multiple top packages that caused a particular package to be a transitive dependency.

**Comment by dominoFire** [comment]
Note: Figure out how to get a list of transitive dependencies for a given project.

**Comment by dominoFire** [comment]
Updating estimate up due to feedback from API design review.
