### ISSUE TITLE
[Push]The package cannot be pushed to specified local source

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10768]
## Details about Problem
VS Version: Main\31213.246
NuGet Version: Dev\5.10.0.7208
OS Version: Windows-10-Enterprise-20H1.
## Installations
1. Install VS Main\31213.246 from:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4650763&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Dev\5.10.0.7208 from: \\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\dev\5.10.0.7208\artifacts\VS15
## Steps to reproduce
1. Create a new C# Class Library (.net Framework) project.
2. Build the solution.
3. Create a .nupkg package through command ‘nuget pack’.
4. Push the package to specified local source (e.g. C:\Users\v-minlon\source\repos) through the command 'nuget push "C:\Users\v-minlon\source\repos\Package1\Package1\Package1.1.0.0.nupkg" -Source C:\Users\v-minlon\source\repos'.
## Expected
The package should be pushed to specified local source successfully.
## Actual
The package had not been pushed to specified local source.
![image](https://user-images.githubusercontent.com/40230425/114838284-235a1d00-9e07-11eb-8e71-61c329cc1366.png)

**Comment by nkolev92** [comment]
@v-luzh 

Not sure I have enough information to repro this.

Can you post the exact commands you ran and the logs for each? 

What was the directory structure of the local source prior to pushing and what was the directory structure after pushing?

**Comment by v-longmin** [comment]
We update the repro steps on the issue, and the command and the log of pushing the package to specified local source as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/114838958-cf036d00-9e07-11eb-8604-c3aef78126bd.png)

**Comment by aortiz-msft** [comment]
@v-longmin - Would you please use a different "NuGet Source" destination for the "source" parameter in:
'nuget push "C:\Users\v-minlon\source\repos\Package1\Package1\Package1.1.0.0.nupkg" -Source **C:\Users\v-minlon\source\repos**'.

**Comment by v-longmin** [comment]
@aortiz-msft We switch the local source to 'C:\PushTest', the package can be pushed successfully.
![image](https://user-images.githubusercontent.com/40230425/115000787-a9dd3000-9ed5-11eb-9100-fd1cd0d6b21a.png)

**Comment by zkat** [comment]
Closing, then.
