### ISSUE TITLE
Can't apply a NuGet package to a blank solution in VS 2015

### ISSUE THREAD

**Issue by Konamiman** [NuGet/Home#1076]
When I try to apply a NuGet package to a blank solution (the package creates a group of related project in the solution) in Visual Studio 2015 I get the following error:

    install-package : Project 'Default' is not found.
    At line:1 char:1
    + install-package (The package name)
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
        + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

This was working fine in Visual Studio 2013.

**Comment by yishaigalatzer** [comment]
Solution level packages are deprecated in Visual Studio 2015. You can apply a package to a project and a simple way to achieve it is to create a project that will include what you used to apply to the solution level.

**Comment by yishaigalatzer** [comment]
http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

**Comment by Konamiman** [comment]
Too bad. Why removing a feature that is useful and doesn't harm? :-(

At my company we often create solutions with a predefined layer structure (interface, domain, infrastructure, tests) and we have a NuGet package that creates one project for each of these layers with the appropriate name and namespace depending on the solution name, plus adds a set of build scripts. With this change we will have to trash this.

**Comment by craig-wagner** [comment]
The problem with this is that you broke the ability to update all packages in a solution. In the old version I could issue a command like:

> Update-Package SomePackage

And it would go through all the projects in the solution and update that package to the latest version. Now when I issue that command I get the same error as the OP, i.e.

> install-package : Project 'Default' is not found.

This is a serious PITA as now I have to go through the 45 projects in which each of five packages is installed and issue 225 `Update-Package` commands.

**Comment by yishaigalatzer** [comment]
Nuget was never intended to be a visual studio scripter. What you could do instead is build a vsix.

**Comment by prakhar241** [comment]
Even applying package at project level not working -

PM> Install-Package xunit.runner.utility -Version 2.1.0
Install-Package : Project 'Default' is not found.
At line:1 char:1

Install-Package xunit.runner.utility -Version 2.1.0

```
CategoryInfo : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
PM>
```

**Comment by yishaigalatzer** [comment]
That looks like an unrelated issue, please open a new bug and provide exact details on how to reproduce the issue. Please make sure you are using the latest nuget extension (3.4.4-rc at the moment)

**Comment by prakhar241** [comment]
I got it fixed now after following 'bitpen' 4 steps listed here - http://stackoverflow.com/questions/10130333/cant-install-packages-with-nuget-500-internal-server-error

**Comment by sindamnataraj** [comment]
Easiest way to fix this is to open a working vs2015 solution(create a new one if you don't have one) and try the Install-Package command again.
