### ISSUE TITLE
How to include files that are not part of the "contentFiles" folder?

### ISSUE THREAD

**Issue by PawcioCNCProfi** [NuGet/Home#10765]
I'm not sure if I understand this part https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files correctly but nuget assumes I have folder named "contentFiles" within my project?

I only have "icon" folder directly in folder of my project.

So, if paths in `include` attribute suppose to be relative to that folder I should be able to write following?

```
<?xml version="1.0" encoding="utf-8"?>
<package>
  <metadata>
    <contentFiles>
      <files include="..\icons\**" buildAction="None" copyToOutput="true" />
    </contentFiles>
  </metadata>
</package>
```

Unfortunately this doesn't work for me :( It does not include anything. How can include my files?
I also don't get what even is this "contentFiles" directory structure for...

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

Product version: 5.6.9

**Comment by nkolev92** [comment]
@PawcioCNCProfi 

There are 2 different `files`  elements. 

The `contentFiles` element is metadata. It's about defining what files in the resulting package do when consumed. 
The `files` element under the `contentFiles` is used for that.

The `<files>` element under `package` is the one that you can use to include files from anywhere.
