### ISSUE TITLE
How to include files that are not children of "contentFiles"

### ISSUE THREAD

**Issue by PawcioCNCProfi** [NuGet/Home#10764]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

Product version: 

Worked before? If so, with which NuGet version:

**Comment by nkolev92** [comment]
Hey @PawcioCNCProfi 

Not sure I understand your question. 

Are you trying to include files in a package?
Is it a consumption time problem?

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/10765, which contains better details
