### ISSUE TITLE
IntelliCode Package Suggestions don't show the verified checkmark or download count

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#10778]
Bug found in VS 16.10 preview 3.

Browse tab package suggestions don't show the verified checkmark for packages that should have it or the download count for any packages: (compare the suggestions to the regular items below it)

![image](https://user-images.githubusercontent.com/15097183/115304679-3a647c00-a133-11eb-8868-da1e43648647.png)

**Comment by aortiz-msft** [comment]
@chgill-MSFT - Did recommendations ever show the Verified Checkmark?

**Comment by chrisraygill** [comment]
@aortiz-msft actually, looking back through old screenshots, I don't think they did. They are also missing the download count.

**Comment by jebriede** [comment]
Closing as duplicate of https://github.com/NuGet/Home/issues/10440
