### ISSUE TITLE
Tools -> Options -> NuGet Package Manager string is truncated

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10779]
Related to: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1151266

Affected Branch:
Affected Build: Version 16.7.0 Preview 4.0 [30301.268.master]
Affected Product Language:

Steps to reproduce:

1. open tools->options->NuGet Package Manager
2. observe the string in the label for "Automatically check for missing packages during build in Visual

**Expected**
the string should either end with "in Visual Basic" or with "during build."

**Observed**
the string appears trunctated, and has extraneous information ("in Visual"). I also question how this string will appear after localization.

![image.png](https://images.zenhubusercontent.com/5fb70598d06a06645c8439d4/e0867be4-577d-401e-8bc2-e3556b98b7d3)

**Comment by donnie-msft** [comment]
Hm, I've never seen this and was unable to reproduce it on 16.10. I tried shrinking the window, increasing font size, different resolution screens, and couldn't get this behavior.
Could you please elaborate on the repro steps? I'd be surprised if it's isolated to 16.7, but let me know if so.
![image](https://user-images.githubusercontent.com/49205731/115317206-f7150800-a148-11eb-8db0-1da1f33612fc.png)

**Comment by jebriede** [comment]
@donnie-msft: It repros on a SurfaceBook 2 with 200% scaling and 3240 x 2160 resolution. On a different monitor with 100% scaling and 2560 x 1440, it did not repro.

**Comment by donnie-msft** [comment]
Those are actually my default settings (200% and 2160) and it doesn't repro for me :\

![image](https://user-images.githubusercontent.com/49205731/115632412-a67ee580-a2d5-11eb-844e-1d3b101ebadd.png)

**Comment by donnie-msft** [comment]
Talked offline. Found that it's a finicky repro, and you have to launch VS on a specific monitor with these settings.
