### ISSUE TITLE
Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion 

### ISSUE THREAD

**Issue by mortenftb** [NuGet/Home#10771]
## Details about Problem

NuGet product used dotnet.exe:
executing  _dotnet add package <somepackage>_
shows the below error and does not include the package in either Directory.Packages.props file or in .csproj

error: NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: HotChocolate.
error: Package 'HotChocolate' is incompatible with 'all' frameworks in project '/Users/<FullFilepathHere>/ConsoleApp1/ConsoleApp1.csproj'.

Product version: 
dotnet cli version 5.0.202

## Repro steps and/or sample project
1) Create new solution
2) Create Directory.Packages.props file at same level as .sln file
3) Add .NET 5 assembly project
4) Opt-in to general package management by adding to to csproj file:
```
 <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
```

5) execute dotnet add package HotChocolate
### Verbose Logs
 Determining projects to restore...
  Writing /var/folders/fd/6ldcftt13p39kcwy4c6qh4zr0000gn/T/tmpFer15V.tmp
info : Adding PackageReference for package 'HotChocolate' into project '/Users/<FullFilePathHere>/CentralPackageManagement/ConsoleApp1/ConsoleApp1.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/index.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/0.1.0/0.7.0-preview.4.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/0.7.0-preview.5/0.8.1.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/0.8.2-preview.1/9.0.0-preview.36.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/9.0.0-preview.37/10.0.0-preview.49.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/10.0.0-preview.50/10.4.0-preview.7.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/10.4.0-preview.10/11.0.0-dev.17.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/11.0.0-preview.1/11.0.0-preview.69.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/11.0.0-preview.70/11.0.0-preview.134.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/11.0.0-preview.135/11.0.6.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/11.0.7-rc.0/11.1.0-preview.59.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/hotchocolate/page/11.1.0-preview.60/12.0.0-preview.1.json
info : The project /Users/<FullFilePathHere>/CentralPackageManagement/ConsoleApp1/ConsoleApp1.csproj is using CentralPackageVersionManagement, a NuGet preview feature.
error: NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: HotChocolate.
error: Package 'HotChocolate' is incompatible with 'all' frameworks in project '/Users/<FullFilePathHere>/CentralPackageManagement/ConsoleApp1/ConsoleApp1.csproj'.

**Comment by nkolev92** [comment]
hey @mortenftb, 

The dotnet CLI commands are not yet implemented for CPVM, https://github.com/NuGet/Home/issues/9014.
