### ISSUE TITLE
dotnet nuget verify command is not using the nuget.config

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10774]
## Details about Problem

NuGet product used (dotnet.exe):

Product version: 5.9

Worked before? If so, with which NuGet version: n/a

## Repro steps and/or sample project

Let we have broken/missing tag in nuget.config file, then `nuget.exe` check it before doing verify but dotnet.exe start doing verify action without checking it. I believe we should check integrity of nuget.config before doing any action since so many logics depend on it.

`nuget59 verify -all ..\TestSigned\TestSigned.1.0.0.nupkg`

NuGet.Config is not valid XML. Path: 'C:\Users\eryondon\source\repos\SigningDemo\nuget.config'.
  The 'trustedSigners' start tag on line 15 position 4 does not match the end tag of 'trustedSigner'. Line 21, position 5.

`dotnet nuget verify ..\TestSigned\TestSigned.1.0.0.nupkg`

error: NU3018: The author primary signature found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
error:
error: Package signature validation failed.

**Comment by nkolev92** [comment]
Related to #10773

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 @kartheekp-ms 
Do I need to address https://github.com/NuGet/Home/issues/10011 issue too here? If no then I cost 1, if yes then I cost 3 just in case.

**Comment by kartheekp-ms** [comment]
> Do I need to address #10011 issue too here? If no then I cost 1, if yes then I cost 3 just in case.

IMHO, I think we should address both because we try to maintain feature parity between `nuget.exe` and `dotnet.exe`.

**Comment by nkolev92** [comment]
I'd try to fix both. 

Given that it's a problem for both, my guess is that the issue is in the shared code anyways.

**Comment by erdembayar** [comment]
I'll try to address too [10111](https://github.com/NuGet/Home/issues/10011). Considering I need to add tests for both `nuget verify` and `dotnet nuget verify`  and need to learn about `verify` code increased costing to 4.
