### ISSUE TITLE
Reference conditionally based on target architecture in .nuspec

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1077]
According to https://docs.nuget.org/create/nuspec-reference it is currently possible to conditionally reference packages depending on the target framework.

``` xml
<references> 
  <group targetFramework="net45"> 
    <reference file="a.dll" />
  </group> 
  <group targetFramework="netcore45"> 
    <reference file="b.dll" /> 
  </group>
  <group>
    <reference file="c.dll" />
  </group>
</references>
```

It would be nice if this would also be possible regarding target architecture. By this I mean something like that:

``` xml
<references> 
  <group targetArchitecture="x64"> 
    <reference file="a_x64.dll" />
  </group> 
  <group targetArchitecture="x86"> 
    <reference file="a_x86.dll" /> 
  </group>
  <group>
    <reference file="b.dll" />
  </group>
</references>
```

This issue might be related with: http://nuget.codeplex.com/workitem/679 (has this issue already been moved to github)

(copied from https://github.com/NuGet/NuGetGallery/issues/2601 - original poster: @sjoerd222888)

**Comment by sjoerd222888** [comment]
Thx. I just realized after posting. You were quicker with moving it here.

**Comment by yishaigalatzer** [comment]
I believe this is supported in NuGet 3.1 in project.json scenarios - http://docs.nuget.org/Create/uwp-create#runtimes

The documentation is still not fully covering this, @csharpfritz will add the docs.

We do not plan to add this support to package.config scenarios.

**Comment by kraigb** [comment]
yishaigalatzer - can you or someone else confirm whether this feature was added? If so, I can update the current docs on https://docs.nuget.org/ndocs/schema/nuspec#reference-groups accordingly.

**Comment by yishaigalatzer** [comment]
I don't think it is supported the way it is described above. You can add runtime implementations per target but not a direct reference.

@karann-msft - can you validate the current state and update accordingly?

**Comment by karann-msft** [comment]
The nuspec only allows pivoting on target framework. A .targets file would be needed to conditionally reference dlls in this way.

**Comment by sjoerd222888** [comment]
Just to understand: This means a feature like this will not be implemented. If I work with C++ dlls I will have to create a separate nuget package, one for 32bit and one for 64bit, in case I want to support both. 

Is this correct?

**Comment by karann-msft** [comment]
I am saying, this feature is currently not available. If you want to achieve this today, you could author a targets file that can conditionally reference dlls based on whatever you'd like to pivot on.

**Comment by sjoerd222888** [comment]
I know this feature is not currently available. I thought of this issue here as a feature request. Closing it seems to me you have decided not to implement this feature. Can you clarify on this?

**Comment by karann-msft** [comment]
That's right. There are no immediate plans of implementing this feature.
