### ISSUE TITLE
Fix overflow in HttpClient 

### ISSUE THREAD

**Issue by xoofx** [NuGet/Home#1078]
FYI, I have opened a pull-request on:
https://github.com/Haacked/NuGet/pull/3 

I can't fork the nuget codeplex correctly. BTW, why is the original repo not available on GitHub while it is still used extensively even in the new NuGet3? Not sure to understand where we should PR to the old repo, sorry!

**Comment by yishaigalatzer** [comment]
Thanks for this PR. We still build from codeplex unfortunately. we have been meaning to take the time and move it over to github (which should take less than a day), but we have been focusing on the 3.0/3.1/3.1.1 back to back releases. We should move it there in the next couple of weeks and then we will gladly take a PR.

**Comment by yishaigalatzer** [comment]
Nuget.Core is now building from https://github.com/nuget/nuget2

**Comment by MeniZalzman** [comment]
:shipit:  @xavierdecoster Please make sure you are merging this PR to 2.10 branch, we ship 2.9

**Comment by yishaigalatzer** [comment]
We _shipped_ 2.9

**Comment by xavierdecoster** [comment]
Merged in 2.10 branch with https://github.com/NuGet/NuGet2/issues/15
