### ISSUE TITLE
Default package management format dropdown box is missing

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#10792]
## Details about Problem

NuGet version: NuGet Client Dev\5.10.0.7222
VS Version: Main\31221.294 
OS Version: Windows-10-Enterprise-20h2

## Repro steps 

1. Create a C# Console App (.net core) project.
2. Click Tools->NuGet Package Manager->Package Manager Settings, go to General tab.
3. Observe the “Default package management format dropdown box”.

## Expected

The “Default package management format” dropdown box should show correctly and can be selected.

## Actual

The “Default package management format” dropdown box is missing and can’t be selected as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/115680033-c7067880-a385-11eb-96ad-6e7e5bbae8e0.png)

## Note

This issue starts from Dev\5.10.0.7222.

**Comment by donnie-msft** [comment]
@jebriede could you please take a look at this one.

**Comment by v-crchang** [comment]
This issue is fixed on Dev\5.10.0.7228.
