### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by dustpan28646** [NuGet/Home#10794]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

Product version: 

Worked before? If so, with which NuGet version:

**Comment by JonDouglas** [comment]
Thanks for the issue! Unfortunately there's not enough information for us to assist. If you'd like to create some more details by following https://github.com/NuGet/Home/wiki/Submitting-Bugs-and-Suggestions#before-submitting-an-issue that would help us!
