### ISSUE TITLE
NuGet.Protocol.Tests.PackageUpdateResourceTests.PackageUpdateResource_SourceAndSymbolNuGetOrgPushingAsync test is flaky

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#10799]
`NuGet.Protocol.Tests.PackageUpdateResourceTests.PackageUpdateResource_SourceAndSymbolNuGetOrgPushingAsync` test has failed in three [1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4687836&view=ms.vss-test-web.build-test-results-tab), [2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4684690&view=ms.vss-test-web.build-test-results-tab), [3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4677592&view=ms.vss-test-web.build-test-results-tab) official builds recently.

One commonality in all the failures is the test is failing for `symbolSource: https://nuget.smbsrc.net/` input.

https://github.com/NuGet/NuGet.Client/blob/d2bb0de35242b04802c1a7856ebb7718f674565c/test/NuGet.Core.Tests/NuGet.Protocol.Tests/Resources/PackageUpdateResourceTests.cs#L226-L231

**Comment by donnie-msft** [comment]
Dupe of https://github.com/NuGet/Home/issues/10706
