### ISSUE TITLE
ResolvePackageAssets task should log package dependency chain on each item

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#10796]
The `ResolvePackageAssets` task takes in PackageReference items and produces `RuntimeCopyLocalItems`. It is not clear why a certain file ends up in RuntimeCopyLocalItems.

A new metadata should be logged on each file that shows the dependency chain from a root package to the package that caused this file inclusion.

This information is available in project.assets.json but is very hard to parse.

Having this metadata would significantly simplify investigations answering questions such as "why is this file being copied to output" and "which NuGet package was the root package that eventually caused this file to be included".

Mockup:
![image](https://user-images.githubusercontent.com/679326/115771623-08d1f780-a363-11eb-8795-19818e36d800.png)

**Comment by KirillOsenkov** [comment]
Need to think about the metadata name, separator (maybe ` -> `?) etc. But the idea is I need to see which package dependency chain led to each resolved asset.

**Comment by nkolev92** [comment]
This task is owned by the SDK team right now, so probably best if this issue is moved there. 

Cc @kartheekp-ms who is hot seat.

**Comment by zkat** [comment]
Closing as dup of https://github.com/dotnet/sdk/issues/17207
