### ISSUE TITLE
[Cross-platform Signing]All expected errors and warnings do not occur after restoring the projects 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10808]
## Details about Problem
VS Version: Main\31227.388
NuGet Version: Dev\5.10.7231
OS Version: Linux Ubuntu Server 18.04/macOS Big Sur 11.0.1
## Installations
1. Install VS Main\31227.388 from:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4698193&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Dev\5.10.0.7231 from: \\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\dev\5.10.0.7231\artifacts\VS15
## Repro steps and/or sample project
1. Create a new Class Library (.Net Core) project and Build Solution.
2. Cd to project path and execute command `“nuget spec”`.
3. File the “Author” and “Description” in “nuspec” file.
4. Execute command '`nuget pack <package>.csproj`'.
5. Execute all [Cross-platform verify signing test cases](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2F%29
).
## Expected
All expected errors and warnings should show after restoring projects.
## Actual
No errors and warnings occur after restoring projects.
## Notes
1. Seems that is affected by commit “Make by default validation disabled on Linux, but enabled by default on Windows" - https://github.com/NuGet/NuGet.Client/pull/3979
2. The issue does not reproes on windows OS.

**Comment by kartheekp-ms** [comment]
@v-longmin - Yes, as short-term solution to https://github.com/NuGet/Announcements/issues/56, signature verification has been disabled on Linux & Mac in https://github.com/NuGet/Home/issues/10713. If users would like to Opt-in to the package signing verification on .NET 5 Linux & Mac then please add an environment variable `DOTNET_NUGET_SIGNATURE_VERIFICATION` set to `TRUE` https://github.com/NuGet/Home/issues/10742

I think in your case feel free add a step in the test cases to add the above said environment variable to perform signature verification on Linux & Mac.

//cc @heng-liu @erdembayar @dtivel

**Comment by nkolev92** [comment]
@kartheekp-ms 

Should this issue remain open? 
I think it might be a good idea to dup this to the re-enabling of verification on linux/mac issue if it all exists.

**Comment by nkolev92** [comment]
🔔 Putting this on top again.

**Comment by kartheekp-ms** [comment]
@v-longmin I am closing this issue since I answered your question. Please feel free to open a new issue if you need more information.
