### ISSUE TITLE
NuGet packages restores fail if the tag Version gets change in a pre-build process

### ISSUE THREAD

**Issue by Rand-Random** [NuGet/Home#10803]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):
Visual Studio
NuGet.exe
vsSolutionBuildEvent - https://marketplace.visualstudio.com/items?itemName=GitHub3F.vsSolutionBuildEvent-11615

Product version: 

Latest
NuGet.exe
![image](https://user-images.githubusercontent.com/9868626/116204387-04c82000-a73d-11eb-88a4-08f87a96a552.png)
Visual Studio
![image](https://user-images.githubusercontent.com/9868626/116204438-10b3e200-a73d-11eb-847a-a30d7df306d1.png)
vsSolutionBuildEvent
![image](https://user-images.githubusercontent.com/9868626/116204525-26c1a280-a73d-11eb-8d4f-e29dd48275bc.png)

## Repro steps and/or sample project

[Ktsw - Kopie.zip](https://github.com/NuGet/Home/files/6382812/Ktsw.-.Kopie.zip)

In this sample project I have added a script for automatic version numbering with the tool vsSolutionBuildEvent.
You may find the script in the vssbe file.

What it does is find the `<Version>` tag in the `Directory.build.props` and replace it with a version including a revsion number.
This change seem to trigger a package restore inside visual studio, but for what ever reason this restore will fail.
The package manager console is only telling me to look inside the error list, but the error list is empty, so I have no clue what is wrong and what I can do to fix it, also I fail to understand why the restore would trigger in the first place.

Directory.Build.props (had to zip it, *.props file aren't supported)
[Directory.Build.zip](https://github.com/NuGet/Home/files/6382857/Directory.Build.zip)

Manually changing the version number in the `Directory.Build.props` and than calling `dotnet restore` doesn't produce an error.
![image](https://user-images.githubusercontent.com/9868626/116207220-f0395700-a73f-11eb-98c2-dfc7397152c7.png)

I have the following question
1. Is there a different more dotnet/nuget/visul studio friendly way to have an automatically incrementing revsion number?
2. What is the actual error and how can I fix it? Or how could I supress the error?

I have noticed if I disable those settings
![image](https://user-images.githubusercontent.com/9868626/116206468-1f02fd80-a73f-11eb-90e5-b0a37c821731.png)
the packages won't get restored, but I would like to continue to use this feature.

### Verbose Logs

NuGet Package Manager Log:
[NuGet Package Manager Log.txt](https://github.com/NuGet/Home/files/6382815/NuGet.Package.Manager.Log.txt)

Visual Studio Build Diagnositc Log: (had to zip it, file limit was exceeded)
[Visual Studio Build Diagnostic Log.zip](https://github.com/NuGet/Home/files/6382821/Visual.Studio.Build.Diagnostic.Log.zip)

**Comment by kartheekp-ms** [comment]
@Rand-Random - Thank you for the detailed report. I agree that the error message is not actionable.  I noticed empty strings `logged` for project names in the package manager output. For example, see below output.

```
Restoring NuGet packages...
Running restore with 6 concurrent jobs.
Reading project file C:\repoCore\trunk\Ktsw - Kopie\Controls\Controls.csproj.
Reading project file C:\repoCore\trunk\Ktsw - Kopie\Core\Core.csproj.
Reading project file C:\repoCore\trunk\Ktsw - Kopie\Common\Common.csproj.
Reading project file C:\repoCore\trunk\Ktsw - Kopie\Rvo\Rvo.csproj.
The restore inputs for 'Ktsw.Controls' have changed. Continuing restore.
---> The restore inputs for '' have changed. Continuing restore. <---
```
> What is the actual error and how can I fix it? Or how could I suppress the error?

Can you please check if there are any error messages logged in the [ActivityLog.xml](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2019#to-examine-the-activity-log)? 

Path - `%AppData%\Microsoft\VisualStudio\<version>\ActivityLog.xml`. Tip: Search for `Error` or `NuGet` words in the activity log.

**Comment by Rand-Random** [comment]
@kartheekp-ms 
As requested here the ActivityLog.xml
[ActivityLog.zip](https://github.com/NuGet/Home/files/6415963/ActivityLog.zip)

The activity log should contain 3 rebuilds each of them fired the exceptions.

**Comment by erdembayar** [comment]
@Rand-Random 
I don't see any actual nuget related error in your `ActivityLog.zip`. There're some MEF error not sure if they're benign or not.
But I see below error in your previous logs:

`The BaseOutputPath/OutputPath property is not set for project 'External.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.`

Do you have `Directory.Packages.props ` in your solution? Then please look for `BaseIntermediateOutputPath` or `OutputPath` in it? Maybe they're not set values or set incorrect default values.
Also this value can be passed to `msbuild.exe` with `/p` option( for example `/p:BaseOutputPath=somepath`).
One of best way to diagnose is do `dotnet restore /bl`, it'll create `msbuild.binlog` file. 
Open `msbuild.binlog` file with [msbuildlogreader](https://www.msbuildlog.com/). Then look for `$error`. 
Edit: You can set msbuild property values in [csproj file too](https://github.com/erdembayar/MSBuildTests/blob/main/NoTargetDemo.csproj).

**Comment by Rand-Random** [comment]
@erdembayar getting 404 for the linked csproj file.

**Comment by erdembayar** [comment]
@Rand-Random 
Here it's:
```
<!-- <Project Sdk="Microsoft.Build.NoTargets/1.0.26"> -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

 <PropertyGroup>
   <SampleProperty>Test</SampleProperty>
 </PropertyGroup>

  <Choose>
  <When Condition="$(SampleProperty)=='Test'">
      <PropertyGroup>
        <SampleProperty>Test2</SampleProperty>
      </PropertyGroup>
  </When>
  <Otherwise>
            <PropertyGroup>
                <DebugSymbols>true</DebugSymbols>
                <Optimize>false</Optimize>
                <OutputPath>.\bin\$(Configuration)\</OutputPath>
                <DefineConstants>DEBUG;TRACE</DefineConstants>
            </PropertyGroup>
  </Otherwise>
  </Choose>

  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="2.1.*" />
  </ItemGroup>
<!-- msbuild /nologo /t:MakePublishDirectory -->
<Target Name="MakePublishDirectory">
    <Message Text="11111111111"/>
    <PropertyGroup>
        <OutputDirectory>\Output2</OutputDirectory>
    </PropertyGroup>
    <Message Text="$(SampleProperty)"/>
    <!-- Importance="High" message show on "dotnet build", but normal without one show on "msbuild" -->
    <Message Importance="High" Text="Creating Publish Directory"/>
    <MakeDir Directories="$(OutputDirectory)"/>
  </Target>

  <!-- <Target Name="Testing123" AfterTargets="Build" DependsOnTargets="GetBuildVersion">
    <Message Importance="High" Text="My!!!!BuildVersion: $(BuildVersion)" />
    <Message Importance="High" Text="My!!!!BuildVersion: $(BuildVersion)" />
  </Target> -->

  <Target Name="Testing123" AfterTargets="Build" DependsOnTargets="MakePublishDirectory">
    <!-- Importance="High" message show on "dotnet build", but normal without one show on "msbuild" -->
    <Message Importance="High" Text="My!!!!BuildVersion: $(BuildVersion)" />
    <Message Importance="High" Text="My!!!!BuildVersion: $(OutputDirectory)" />

    <PropertyGroup>
      <Configuration>Debug</Configuration>
    </PropertyGroup>

    <Message Text="Configuration = $(Configuration)"/>
    <ItemGroup>
      <Reference Include="System.Data"/>
      <!-- <Reference Include="System.Web.*"/> -->
    </ItemGroup>

    <Message Text="References = @(Reference)"/>

    <ItemGroup>
      <Compile Include="$(MSBuildProjectDirectory)\Class1.cs">
        <!-- <DependentUpon>"$(MSBuildProjectDirectory)\Class1.cs"</DependentUpon> -->
        <!-- <SubType>ASPXCodeBehind</SubType> -->
      </Compile>
    </ItemGroup>

    <!-- <Message Text="Element @(Compile) of subtype %(SubType) and depend of %(DependentUpon)"/>     -->
    <Message Text="Element @(Compile)"/>
  </Target>

  <Target Name="CopyFiles" AfterTargets="Build" DependsOnTargets="MakePublishDirectory">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\Class1.cs" 
          DestinationFolder="$(OutputDirectory)">
          <Output TaskParameter="CopiedFiles"
          ItemName="SuccessfullyCopiedFiles"/>
      </Copy> 
     <Message Text="!!!! Copied: $(SuccessfullyCopiedFiles)"/>
   </Target>

<Target Name="sampletarget">
    <PropertyGroup>
        <OutputDirectory>$(MSBuildProjectDirectory)\Output2</OutputDirectory>
    </PropertyGroup>
    <Csc Sources="$(MSBuildProjectDirectory)\Class1.cs"
          TargetType="library"
          Resources="@(CompiledResources)"
          EmitDebugInformation="$(includeDebugInformation)"
          References="@(Reference)"
          DebugType="$(debuggingType)" >
        <Output TaskParameter="$(OutputDirectory)"
                  ItemName="FinalAssemblyName" />
    </Csc>    
    <Csc ContinueOnError="ErrorAndStop">
    </Csc>
    <TaskTwo>
    </TaskTwo>
    <OnError ExecuteTargets="MakePublishDirectory" />    
</Target>

<!-- Always prefer PropertyGroup and ItemGroup  over CreateProperty -->
<!-- https://stackoverflow.com/a/4002500 -->
<Target Name="A">
    <PropertyGroup>
        <DogSound>BarkA</DogSound>
    </PropertyGroup>
    <Message Text="DogSound $(DogSound)"/>
</Target>

<Target Name="B">
    <CreateProperty Value="BarkB">
        <Output TaskParameter="Value" PropertyName="DogSound"/>
    </CreateProperty>
    <Message Text="DogSound $(DogSound)"/>
</Target>

</Project>
```

**Comment by zkat** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue.

Please feel free to comment or open a new issue if needed.
