### ISSUE TITLE
Restore dependencies for projects listed in a solution filter (.slnf) file

### ISSUE THREAD

**Issue by kjanos0502** [NuGet/Home#10809]
NuGet product used: NuGet.exe
Product version: 5.8.1

It would be nice to be able to restore dependencies based on an .slnf file.
Based on the release notes in v5.0 support was added for solution filters, but a restore must be done for the entire solution beforehand.
https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-rtm

As restoring dependencies based on .csproj files is possible, it would be handy if it would work for an .slnf file as well, which basically just lists corresponding csproj files.

As of now the command
`nuget.exe restore "C:\Git\SampleProject\src\Api.slnf" -Verbosity detailed`
produces the following output:

```
NuGet Version: 5.8.1.7021
C:\Users\SampleUser\Downloads\nuget.exe : Invalid input 'Api.slnf'. The file type was not recognized.
At line:1 char:1
+ C:\Users\SampleUser\Downloads\nuget.exe restore "C:\Git\SampleProject\src ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Invalid input '...not recognized.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
System.InvalidOperationException: Invalid input 'Api.slnf'. The file type was not recognized.
   at NuGet.CommandLine.RestoreCommand.GetInputsFromFile(String projectFilePath, PackageRestoreInputs packageRestoreInputs)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by nkolev92** [comment]
@kjanos0502 

Thank you for creating this issue. At this point we're not sure when we will be able to get to this issue, but we'd consider a PR! 

In the mean time consider using `msbuild.exe /t:restore` with a switch to opt into packages.config restore. https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-msbuild

**Comment by kvpt** [comment]
Have the same need.

I went to Nuget source code and the modification seemed trivial to me as Nuget use MsBuild API to retrieve the projects list and MsBuild already handle filters.

@nkolev92 
So as PR are welcome, I tried to make one.
I don't know the project at all so perhaps I have done it wrong at least the test that I added seems to indicate that the change is working.

**Comment by nkolev92** [comment]
Closing as it was accidentally not closed since the issue link was on a different like from the fixes comment.
