### ISSUE TITLE
Support customized packing  on symbol packages 

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#10820]
For now, NuGet has a customized packing on project NuGet.Build.Tasks.Pack.
However, the symbol package of this project could not be customized and packed correctly.
So we skipped packing the symbol package for this project.

Backgroud: https://github.com/NuGet/Home/issues/10463#issuecomment-827174360

When this feature is implemented, we may start to pack the symbol for project NuGet.Build.Tasks.Pack.

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/10860 has the exact same ask with more details.

That one is newer, but it's given the better description, I'm gonna close this issue in favor of that one.
