### ISSUE TITLE
Adding package: too many simultaneous IO requests, freezes USB hard drive and fails due to IO error

### ISSUE THREAD

**Issue by TomArrow** [NuGet/Home#10821]
## Details about Problem

When a project is located on my USB drive (docking station with two drives), installing a new package can freeze the entirety of Visual Studio and ultimately fail due to IO error. During this time, the hard drive is also more or less frozen and incapable of normal operation (very slow reading/getting stuck/taking forever to show folder or drive contents).

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio

Product version: 2019 Community, latest update

Worked before? If so, with which NuGet version: No

## Repro steps and/or sample project

Not sure how well it can be reproduced. I imagine the USB docking station simply doesn't have the bandwidth to deal with a lot of simultaneous IO requests. Nuget is absolutely bombarding it with those though, from what it seems. I tried moving the "packages" folder from the solution to an internal SSD and linking it via junction and the problem disappeared completely. So it's about IO requests within the packages folder, and the problem occurs already at a relatively low count of packages, 12 in my case.

### Verbose Logs

Don't have these because I already got the solution via my SSD and I don't feel like torturing my hard drive any more. But it always ends up failing due to this: "The request could not be performed because of an I/O device error." This happens after the "Adding package to ... /packages" step and there's tens of seconds in between where the GUI and the hard drive freezes. It then ends up rolling back the installation. Strangely enough it does seem to succeed putting the files in the appropriate packages subfolder, but then removes them again after it fails.

**Comment by TomArrow** [comment]
I want to add that this happens even when the dependencies are already added to the project beforehand. However I did not try any special switches to ignore dependencies. I did try installing both through GUI and the package manager CLI though.

**Comment by nkolev92** [comment]
Hey @TomArrow. 

We are sorry you are hitting this issue, unfortunately we are not confident there's anything NuGet could do here. 

1. If you are facing UI freezes in Visual Studio, can you please file a developer community issue and record an etl trace. 
1. If you are getting consistent I/O issue, there might be some issue with your usb connection.

**Comment by TomArrow** [comment]
Hi,

I'm pretty sure it's not a UI issue. This never happens with smaller projects with few dependencies and it happened both with the Package Manager Console and with the normal GUI. Also it affected not just Visual Studio but the entire computer, or more specifically, all software accessing that hard drive at the time. Don't want to recreate the issue because I don't think it's good for my computer. But if it occurs again with another project, how do I record this etl trace?

I have no consistent I/O issues whatsoever. Outside of Nuget, this happened maybe once or twice to me over the course of years, when a great number of programs were simultaneously accessing the hard drive. And it stopped happening completely once I used the internal SSD for the packages folder (while the remaining project remained on the USB drive). In my opinion that makes it pretty obvious that the issue lies with the USB controller having problems with too many simultaneous IO requests. That could likely easily be alleviated by allowing Nuget to limit the amount of simultaneous requests (threads?). 

Cheers

**Comment by TomArrow** [comment]
Happened to me again today. Can you please give me instructions on how to provide a verbose output to you or something? This is intolerable. I don't understand how you can say it's not possible to change the software so that it doesn't saturate my hard drive connection to the point of freezing the hard drive. No other software does this, yet reproducibly NuGet does. 

The one thing this software is supposed to do is install packages and it fails and rolls back all changes. This can't be expected behavior.

**Comment by TomArrow** [comment]
After making my last post, I tried one more time to install a package in the project ... it froze my hard drive and entire computer to the point it remained frozen until now. 7 hours. I don't think it will unfreeze. Can't end processes. Can't access folders. I will likely have to restart my PC and lose all my work and pending writes to that drive. 

"It's a feature, not a bug."

Never happened to me with any other software, but somehow always happens with installing packages, whether in the VS GUI or in a console. Totally my hard drive's fault.

**Comment by TomArrow** [comment]
Yup, had to restart. Completely broke the system...
