### ISSUE TITLE
nuget.exe ignores inheritance for packageSourceCredentials

### ISSUE THREAD

**Issue by jmelosegui** [NuGet/Home#10822]
Is it possible to configure Nuget so the package sources are configured in the nuget.config file in the solution dir, while the credentials for those sources are configured in the nuget.config file located at the user level (`%appdata%\NuGet\NuGet.Config`)?

Reading [how settings are applied](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied) for nuget operations, seems like nuget.config has some sort of inheritance. I was trying to use this inheritance to configure nuget for my team in the following way.

1. Each developer will have a personal set of credentials to the Nuget repository.

2. Each visual studio solution will contain a `Nuget.config` file in the solution directory.

    2.1. The `Nuget.config` file will contain two package sources: nuget.org, and a private credential required source.

3. Each developer will configure the credentials to the private Nuget source within the file located in the user profile (%appdata%\NuGet\NuGet.Config). In this way, those credentials are not committed to source control.

here are some examples of the `Nuget.config` files I am trying to use:

Solution level file
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>  
    <packageSources>
        <add key="nuget.org" value="https://api.nuget.org/api/v3/index.json" />
        <add key="Private" value="url_for_the_private_feed" />
    </packageSources>
    <activePackageSource>
        <add key="All" value="(Aggregate source)" />
    </activePackageSource>  
</configuration>
```

User level file

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />    
  </packageSources>
  <packageSourceCredentials>
    <Private>
      <add key="Username" value="user_name_here" />
      <add key="Password" value="encrypted_password_here" />
    </Private>
  </packageSourceCredentials>
</configuration>
```

**Comment by donnie-msft** [comment]
Hi there! short answer is, yes, what you described should work. 
In fact, `nuget.exe sources add` behaves that way by default (see https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources). When I tried this on NuGet Version: 5.4.0.42325, the credentials were added to the user level config.

Looking at your sample, I see some oddities. Which version of nuget.exe are you using? How was this config generated?

`activePackageSource` was deprecated back in 3.x (see https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#activepackagesource).

**Comment by jmelosegui** [comment]
@donnie-msft, thanks for your answer. 
I finally figured out that if the NuGet command includes the argument `-configFile <path to nuget.config>` then the behavior described in [how settings are applied](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied. ) does not apply, and instead, the NuGet CLI will only consider the configuration file passed as a parameter.

This is not clear in the documentation. For some reason, I thought that I could pass a `nuget.config` file to the NuGet CLI, and it would use that file in conjunction with the user-level configuration and the computer-level configuration.

**Comment by donnie-msft** [comment]
Glad you got it resolved! 

I think that docs page could be more clear and better match what the `nuget <command> -help` shows for `-ConfigFile`.
I wrote up an issue, https://github.com/NuGet/docs.microsoft.com-nuget/issues/2419
Thanks for bringing it up!
