### ISSUE TITLE
Package analysis issues unnecessary warnings

### ISSUE THREAD

**Issue by damyanp** [NuGet/Home#1083]
For example, packages containing winmd/unmanaged dlls will ship DLL files in the runtimes directory.

This triggers a warning about the DLL not being inside the lib folder.

Although -nopackageanalysis can be used to suppress this warning, it shouldn't be necessary to do this.

**Comment by deepakaravindr** [comment]
Do you think that package analysis should be opt-in only?

**Comment by damyanp** [comment]
It would be nice if package analysis understood the runtimes directory and so didn't generate the incorrect warning.

**Comment by emgarten** [comment]
nuget/nuget.client@3f009661481384c5afaeadc23beceed309bc5ad4
