### ISSUE TITLE
Be able to output result a file in json when running dotnet list package

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10837]
---
**Issue moved from dotnet/sdk#17374**
- Please respond to @bschaatsbergen.

---

_From @bschaatsbergen on Monday, May 3, 2021 6:16:32 PM_

When running `dotnet list package` it would be preferable to have a parameter to output the results to a file in order to post process the results.

I would be ok with making a pull request if others are interested in this.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#17374**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Monday, May 3, 2021 6:16:34 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#17374**
- Please respond to @zahycs.

---

_From @zahycs on Tuesday, May 4, 2021 8:34:29 AM_

This can be very handy, especially after introducing packages vulnerability check using  `--vulnerable` argument. it could be very useful in pipelines

**Comment by bschaatsbergen** [comment]
Thanks for moving @wli3

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/7752.
