### ISSUE TITLE
[Wiki] Publishing and Consuming Symbols and Source for Debugging link 404s

### ISSUE THREAD

**Issue by grantborthwick** [NuGet/Home#10832]
The [Publishing and Consuming Symbols and Source for Debugging](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements#solution-) link on [NuGet Package Debugging & Symbols Improvements](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements) has been renamed in the target repo ([dotnet/designs](https://github.com/dotnet/designs/)). Because of this, it 404s.

Current url: https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md
Correct url: https://github.com/dotnet/designs/blob/master/accepted/2020/diagnostics/debugging-with-symbols-and-sources.md

[I have a commit that fixes this on the wiki of my fork of this repo](https://github.com/grantborthwick/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements/_compare/b88505047ba6a3dcefb91c078bd5baeae0034bb4...ee1eec1c86f7b1af88a1c0a1ed05682c53f907fa), however as this is a wiki, I don't believe that I can directly create a PR, so please either update the url with a commit to this repo's wiki, or pull in my commit.

My fork: https://github.com/grantborthwick/Home
My fork's wiki: https://github.com/grantborthwick/Home/wiki (https://github.com/grantborthwick/Home.wiki.git) - commit [ee1eec1c86f7b1af88a1c0a1ed05682c53f907fa](https://github.com/grantborthwick/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements/_compare/b88505047ba6a3dcefb91c078bd5baeae0034bb4...ee1eec1c86f7b1af88a1c0a1ed05682c53f907fa)

**Comment by donnie-msft** [comment]
Thanks for that! Made the edit now :)

**Comment by gato-crypto** [comment]
https://github.com/NuGet/Home.wiki.git
