### ISSUE TITLE
PrivateAssets package reference from metapackage

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#10849]
gRPC on the server requires a bunch of packages:
* Grpc.AspNetCore.Server
* Google.Protobuf
* Grpc.Tools

To make things easier for developers, there is meta-package call [Grpc.AspNetCore](https://www.nuget.org/packages/Grpc.AspNetCore) that references these so the developer only needs to bring in one package.

The issue is Grpc.Tools only needs to be referenced at development time. It is quite large (13MB) and we don't want its content being packaged or deployed with an app.

Ideally, the three packages should be referenced like this:

```xml
<PackageReference Include="Grpc.AspNetCore.Server" Version="2.37.0" />
<PackageReference Include="Google.Protobuf" Version="2.37.0" />
<PackageReference Include="Grpc.Tools" Version="1.37.0" PrivateAssets="All" />
```

Note `PrivateAssets="All"` against `Grpc.Tools`.

Is there a way to make `Grpc.AspNetCore` include a `Grpc.Tools` as a dependency in the developer's app, but only for development time?

Related gRPC issue: https://github.com/grpc/grpc-dotnet/issues/1288

**Comment by nkolev92** [comment]
> Is there a way to make Grpc.AspNetCore include a Grpc.Tools as a dependency in the developer's app, but only for development time?

@jamesnk 

If Grpc.Tools doesn't contain any compile/runtime assets, then it would effectively achieve this goal, wouldn't it?

**Comment by JamesNK** [comment]
What you said makes sense.

I just tested publishing an app that references Grpc.AspNetCore and the large native files weren't copied to the output directory.

Is that because all the content in this package is nested under build and tools?

![image](https://user-images.githubusercontent.com/303201/118558806-4471ad00-b7bb-11eb-9ddb-054254b80a6d.png)

Is using `PrivateAssets="All"` with this package redundant?

**Comment by nkolev92** [comment]
> Is that because all the content in this package is nested under build and tools?

Yes, build is not transitive by default, so unless you explicitly make it flow, it won't consumers of `Grpc.AspNetCore`.

> Is using PrivateAssets="All" with this package redundant?

PrivateAssets is a package build time concern. 
If you mark a dependency with `PrivateAssets="all"`, then it would not even be a part of Grpc.AspNetCore package. 

I think in order to make Grpc.Tools available at build time for consumers of Grpc.AspNetCore, you'd need to include the `build` assets transitively, by tweaking PrivateAssets from the default to one that allows `build` to flow transitively.

**Comment by JamesNK** [comment]
> PrivateAssets is a package build time concern.
> If you mark a dependency with PrivateAssets="all", then it would not even be a part of Grpc.AspNetCore package.

I'm looking at this from the perspective of a developer's app. They need Grpc.Tools at build time but none of its content should be deployed with their app.

**Comment by nkolev92** [comment]
I see. 

Then I think the following is the right answer:

> I think in order to make Grpc.Tools available at build time for consumers of Grpc.AspNetCore, you'd need to include the build assets transitively, by tweaking PrivateAssets from the default to one that allows build to flow transitively.

Then you are relying that your targets are well behaving and the fact that build time assets are by default not transitive.

**Comment by nkolev92** [comment]
@JamesNK 

Is your question answered?

**Comment by JamesNK** [comment]
Yes. Thanks.
