### ISSUE TITLE
NuGet Restore on Windows distro

### ISSUE THREAD

**Issue by georgepharrison** [NuGet/Home#10840]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: 5.0.202

Worked before? If so, with which NuGet version: Unknown

## Repro steps and/or sample project

We're using GitLab and our CI Pipeline was working before and just started to _randomly_ throw the NU3028 and NU3037 errors on nuget.org packages. Here is the dockerfile of the image we are using to build solutions that contain .NET Framework 4.8 and .NET Core 3.1 projects:

```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

RUN powershell -Command \
    #
    # Install Chocolatey 
    Set-ExecutionPolicy Bypass -Scope Process -Force; \
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; \
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')); \
    #
    # Install dotnet 5 sdk
    choco install dotnet-5.0-sdk -y; \
    #
    # Install nuget
    choco install nuget.commandline -y; \
    #
    # Install nodejs
    choco install nodejs -y; \
    #
    # Install git
    choco install git -y; \
    #
    # Refresh env
    refreshenv;
```

### Verbose Logs

```
...
$ dotnet --version
5.0.202
$ dotnet restore --packages ${NUGET_PACKAGES_DIRECTORY}
  Determining projects to restore...
C:\builds\someprojectlocation\someproject.csproj : error NU3028: Package 'runtime.native.System 4.0.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider. [C:\builds\someprojectlocation\somesolution.sln]
...
```

**Comment by erdembayar** [comment]
@Ringo-gph 
It looks your docker image. Can you give us docker image OS details?

**Comment by heng-liu** [comment]
Hi @Ringo-gph , may I know more about "randomly throw the NU3028 and NU3037 errors"?
So does that mean when you run dotnet restore, it either fail on all packages (may I know how many packages should be restored?) for NU3028 and NU3037, or succeed on all packages?
Or fail on certain packages while succeed on other packages? 
You may check if there is any extracted packages in the `${NUGET_PACKAGES_DIRECTORY}`  you specified above, as the extracted packages here should be the packages passed the signature validation. Thanks!

**Comment by georgepharrison** [comment]
It's a windows image: mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

I install dotnet 5.0.202 on it in the dockerfile and confirm through the logs when doing a `dotnet --version`

@heng-liu it sometimes has failures on nuget API packages. I have to keep retrying the job until it successfully does a restore without throwing an error which I find very, very odd. I would expect the restore to always work or to never work, but that's not the case. 

We host our own nuget packages internally and those never have any issue when restoring. 

This is definitely related to the Linux issue that was addressed, but unfortunately this is on Microsoft's windows server core ltsc2019 image (specifically net framework 4.8 sdk.) It's much easier using that image and installing dotnet 5 sdk on it rather than using a dotnet 5 sdk and trying to install net framework sdk on it.

**Comment by erdembayar** [comment]
@Ringo-gph 
I restored your windows docker image 2 times, it didn't repro. It can always restore without issues.

![image](https://user-images.githubusercontent.com/8766776/117496557-10c99400-af2c-11eb-9eae-4fcf347e2c8b.png)

Can you go to your local global nuget cache folder find one of Microsoft package then do `nuget verify -all System.xxxx.nupkg -v d`? We need to see your root CA, something similar to below.
`nuget locals all -l` This one show you all local nuget cache locations.

![image](https://user-images.githubusercontent.com/8766776/117500614-b7fcfa00-af31-11eb-8960-83e2dce12587.png)

**Comment by donnie-msft** [comment]
Just read about a Windows Group Policy issue, where CA's are occasionally identified as untrusted 1-2 times per day or week.

EDIT: I'm not familiar with Windows Docker images, so I think group policy may not apply there. Leaving link here just for reference.
~May be worth quickly checking~
1. Start -> Edit Group Policy
2. **Computer Configuration > Windows Settings > Security Settings > Public Key Policies > Trusted Root Certification Authorities**
3. Does **Trusted Root Certification Authorities** exist here?

See the article here https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/valid-root-ca-certificates-untrusted

**Comment by georgepharrison** [comment]
I will check this out on Monday when back in office and see what it says.

Thank you all for your help!

**Comment by georgepharrison** [comment]
@erdembayar :
![image](https://user-images.githubusercontent.com/3589950/117667396-75723200-b16a-11eb-8b1a-9e656c5c9dca.png)

This is on my local machine. I'll need to remote into the gitlab runner service machine and do a docker run on the image we are using to build with and check on it as well, but I figured I'd share this one as I thought it odd.

**Comment by georgepharrison** [comment]
@erdembayar I remoted into the windows runner server and ran an interactive docker session with the same image, cloned my repo and did a `dotnet restore` and got the following:
![image](https://user-images.githubusercontent.com/3589950/117692084-45cf2400-b182-11eb-9312-3658e9b1d385.png)

I then ran the command you provided against the same package that was the first failure in the dotnet restore (as well as listed the directory for versions brought down) and this is what it says:
![image](https://user-images.githubusercontent.com/3589950/117693311-88453080-b183-11eb-9b72-22d813c4c40b.png)

**Comment by erdembayar** [comment]
> @erdembayar :
> ![image](https://user-images.githubusercontent.com/3589950/117667396-75723200-b16a-11eb-8b1a-9e656c5c9dca.png)
> 
> This is on my local machine. I'll need to remote into the gitlab runner service machine and do a docker run on the image we are using to build with and check on it as well, but I figured I'd share this one as I thought it odd.

This one doesn't make any sense. I suspect your have more than 1 source repo is setup in your `nuget.config`. Maybe some nupkg files are coming from not official nuget.org. Could you be able make binary comparison of  your local `runtime.native.System.4.0.0.nupkg` in screenshot with `https://www.nuget.org/api/v2/package/runtime.native.System/4.0.0`? If you see any difference can you upload your `runtime.native.System.4.0.0.nupkg` somewhere and share with me?

**Comment by erdembayar** [comment]
> @erdembayar I remoted into the windows runner server and ran an interactive docker session with the same image, cloned my repo and did a `dotnet restore` and got the following:
> ![image](https://user-images.githubusercontent.com/3589950/117692084-45cf2400-b182-11eb-9312-3658e9b1d385.png)
> 

Can you retry `dotnet restore` one more time after verify complaining `packageId  +version`  exists in global cache? 
If you can see them then there shouldn't be any issue, because `dotnet/nuget restore` doesn't care about signature if package is already in global cache.

**Comment by georgepharrison** [comment]
@erdembayar I have no idea what changed but none of our solutions (9 of them) are displaying this error anymore. I did recreate the docker image and the dotnet version still shows 5.0.202. I don't know what the nuget.exe version shows (as there's no command to show nuget.exe version in the console app) but maybe it changed or maybe something on the microsoft image changed? Either way, I'm okay as long as I'm not having to mash the retry button on each job! 👍 

I'll close this out. Thank you again!

**Comment by donnie-msft** [comment]
Glad you're not facing this anymore! If you see it again, please let us know. It would be great if we could figure out the root cause.

BTW, to see nuget version in CLI, just enter command `nuget` and the first line of the help text shows the version.

**Comment by erdembayar** [comment]
I can see his nuget version was 5.8.1.7021 on one of screenshots.

**Comment by matt-richardson** [comment]
I also hit this yesterday running msbuild `16.9.0+57a23d249` inside of Windows 20h2 docker container, based on `mcr.microsoft.com/dotnet/framework/sdk:3.5`, which I think has sha sha256:05accdd0b5e8ea58d62a404bff6ce175294493762be674ae2d3222c40d1a2cd1 (I'd go try and find it on docker hub, but it's all hidden behind mcr.microsoft.com). Oddly, re-running worked.
