### ISSUE TITLE
Possible bug in dependency resolver

### ISSUE THREAD

**Issue by thebigb** [NuGet/Home#1085]
I've filed an [issue](https://github.com/aspnet/EntityFramework/issues/2755) with the EF7 repository, of which I can't really tell if this is a bug in NuGet's dependency resolver, or expected behavior for misconfiguration in the nuspec file.

Below is the nuspec of the `System.Collections.Immutable` package. To summarize the issue I linked above, the issue is that with a *.NET 4.5* targeted project, NuGet will attempt to retrieve `System.Runtime` and similar packages while those (if I'm not mistaken) are only meant for *DNX 5.0* projects.

So I'm wondering whether `.NETPlatform5.0` is the proper target framework in the nuspec.

Any thoughts?

P.S. Is there a better way to follow the dependency resolution process? The `-WhatIf` flag gives a nice overview of the result, but doesn't really describe the process.

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/01/nuspec.xsd">
  <metadata minClientVersion="2.8.6">
    <id>System.Collections.Immutable</id>
    <version>1.1.37</version>
    ...
    <dependencies>
      <group targetFramework=".NETPlatform5.0">
        <dependency id="System.Runtime" version="4.0.0" />
        <dependency id="System.Resources.ResourceManager" version="4.0.0" />
        <dependency id="System.Diagnostics.Debug" version="4.0.0" />
        <dependency id="System.Collections" version="4.0.0" />
        <dependency id="System.Linq" version="4.0.0" />
        <dependency id="System.Runtime.Extensions" version="4.0.0" />
        <dependency id="System.Globalization" version="4.0.0" />
        <dependency id="System.Threading" version="4.0.0" />
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by emgarten** [comment]
.NETPlatform 5.0 is compatible with .NET 4.5, the resolver is doing the correct thing here. 

The packages should be ignored after being installed since they are not needed for .NET 4.5. The EF package could avoid these extra dependencies for .NET 4.5 by adding an empty net45 dependency group.

**Comment by thebigb** [comment]
You're absolutely right. I discovered that the `System.Collections.Immutable` package on NuGet was installing fine, but the issue appears to be on the vNext MyGet feed.

```
Could not install package 'System.Runtime 4.0.10-beta-23019'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

I mistook this error message, thinking `System.Runtime` wouldn't be compatible with *.NET 4.5*, but since you mentioned that shouldn't be an issue I discovered the actual issue earlier in the log:

```
Package 'System.Runtime 4.0.10-beta-23019' does not exist in folder 'D:\xxx\packages'
```

So there's probably a reference in the dependency graph to a package that doesn't exist anymore.

But this leads me to the other question I had. Does NuGet have facilities to provide a more detailed dependency report than the `-WhatIf` flag?

Thanks!

**Comment by emgarten** [comment]
There is no flag for showing these dependency graphs yet.

**Comment by thebigb** [comment]
Alright, thanks!
