### ISSUE TITLE
Clarify documentation guideline - do no include empty xml docs

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#10857]

**Comment by donnie-msft** [comment]
Can we make this more explicit? eg, Specify all parameters, at a minimum with their pre- & post-conditions. If nothing of note, should we write a basic descriptions like, "The packageId"?

By not listing a parameter for a method with a parameter, are we not breaking the convention?

**Comment by nkolev92** [comment]
@donnie-msft Can we continue the discussion on the PR?
