### ISSUE TITLE
[Unstable] Error occurs when updating package in PMC for the first time after setting a PackageReference version range in the nuget.config file of SDK project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10859]
## Details about Problem
VS Version: Main\31311.340
NuGet Version: Implicit 6.0.0.15
OS Version: Windows-10-Enterprise-21H1
## Repro steps and/or sample project
1.	Launch VS and create a new .NetCore Console Application (.NET 5.0). 
2.	Select context menu "Edit xxx.csproj" through right-clicking the project. 
3.	Edit the csproj file as below 
```
<Project Sdk="Microsoft.NET.Sdk"> 
  <PropertyGroup> 
    <OutputType>Exe</OutputType> 
    <TargetFramework>net5.0</TargetFramework> 
  </PropertyGroup> 
  <ItemGroup> 
    <PackageReference Include="Newtonsoft.Json" Version="[9.0.1]"/> 
  </ItemGroup> 
</Project> 
```
4. Open PMC from Tools -> Nuget Package Manager->Package Manager Console, then type command "Update-Package". 
## Expected
The package cannot be updated successfully since there is the version range constraints. Below message show in PMC. 
`No package updates are available from the current package source for project 'NetCoreConsole'. `
## Actual
An error show in PMC instead as below for the first updating. Second updating is OK.
![image](https://user-images.githubusercontent.com/20632625/117959609-c478bc80-b34e-11eb-893c-41e92b62db0a.png)
## Error Message:
```
PM> update-package
update-package : The WriteObject and WriteError methods cannot be called from outside the overrides of the 
BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. 
Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
At line:1 char:1
+ update-package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], PSInvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageComma 
   nd
```
## Note:
1. It didn’t repro on VS Main\31221.294 + NuGet Client Dev\5.10.0.7222.
2. It start to repro on VS Main\31311.340 x64 Enterprise with Implicit NuGet 6.0.0.15.

**Comment by erdembayar** [comment]
@v-luzh 
I tried on both my machine and VM so far it didn't repro.
Can you elaborate `with Implicit NuGet 6.0.0.15` part? Maybe I'm missing something here.
First I tried without any change then next I copied content of `6.0.0.15 vsix` to `C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet`  but still no repro.

![image](https://user-images.githubusercontent.com/8766776/118033103-451ec500-b31d-11eb-8161-97cde89d863e.png)

Please let me know if I'm missing something.

**Comment by v-luzh** [comment]
Hi @erdembayar, you didn't miss anything. The part `with Implicit NuGet 6.0.0.15` means using the implicit default NuGet build in VS (no need to install NuGet any more). And no need to copy the content of 6.0.0.15 vsix and overwrite `C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet`. The bug is tricky since it only repro for the first time on clean VM and clean VS.

**Comment by erdembayar** [comment]
@aortiz-msft @v-luzh 
I retried on another clean VM with exact same OS and VS version, still no repro. It looks it's flaky issue and quite challenging to repro, because creating new VM and installing VS takes time.

**Comment by nkolev92** [comment]
Same root cause as https://github.com/NuGet/Home/issues/7891.

**Comment by v-luzh** [comment]
It doesn't repro on VS Main\31326.288 + NuGet Client Release-6.0.x\6.0.0.66. And it can be track by #7891. Close this one now, thanks.
