### ISSUE TITLE
Excessive russian localization in `dotnet nuget list source --help`

### ISSUE THREAD

**Issue by zii-dmg** [NuGet/Home#10862]
NuGet product used: dotnet.exe
Product version: SDK 5.0.203
Command: dotnet nuget list source --help

Should not localize `--format` argument values "Detailed" / "Short" in:
https://github.com/NuGet/NuGet.Build.Localization/blob/2faef2e34504ccaf350912f0cf5ec7a16fcfa7bd/localize/RUS/15/NuGet.CommandLine.XPlat.dll.lcl#L1625

Current:
`<Val><![CDATA[Формат выходных данных команды для получения списка: "Подробный" (по умолчанию) и "Краткий".]]></Val>`

Should be:
`<Val><![CDATA[Формат выходных данных команды для получения списка: "Detailed" (по умолчанию) и "Short".]]></Val>`

**Comment by erdembayar** [comment]
@dominoFire 
Is it something currently you're already addressing?

**Comment by dominoFire** [comment]
Yes, created localization bug.

**Comment by dominoFire** [comment]
Fixed in this PR https://github.com/NuGet/NuGet.Build.Localization/pull/953
