### ISSUE TITLE
Content-only nupkg (eg: source file) doesn't add to project correctly

### ISSUE THREAD

**Issue by bc3tech** [NuGet/Home#1086]
I've got a Windows 10 UWP and I've added the `TinyIOC.WinRT` package to it. This package consists of the core `TinyIOC` package along with the contents of the `TinyIOC.WinRT` one. Both of these packages are **content only**. Previously, one would see the two `.cs` files contained in these packages added to the project so it could use the contents. *Note: they are __not__ assembly references*.
However, with VS 2015 RTM & Nuget 3.0, the package shows as added (is seen under References), but the source code files are never added to the project for use.
This means it doesn't compile.

It's worth noting this was working in VS 2015 RC.

**Comment by yishaigalatzer** [comment]
Content is currently not supported in these scenarios. So this is by design - see http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

We are tracking content support using this issue - https://github.com/NuGet/Home/issues/627
