### ISSUE TITLE
NuGet packages downloaded over 1 billion times show the wrong unit

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10864]
![image](https://user-images.githubusercontent.com/8766776/118065034-1b7f9100-b351-11eb-8018-a237184857d7.png)

_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NuGet-packages-downloaded-over-1-billion/1418778)._

---
[severity:It bothers me. A fix would be nice]
I was just about to download Newtonsoft.Json and noticed that the NuGet package apparently has 1.02G downloads, isn't this supposed to be 1.02B?

---
#### Feedback Bot on 5/11/2021, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by erdembayar** [comment]
@aortiz-msft  @JonDouglas @jebriede 
Do we need to make this change?

**Comment by JonDouglas** [comment]
Can we tag it up for grabs or good first contribution & encourage someone to fix it? we're not in a huge rush and it's a great learning opportunity for someone's first contribution.

Also worthwhile to add the [public code area](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Utility/UIUtility.cs#L54) and maybe a couple steps as to what someone might do to fix? :)

**Comment by zivkan** [comment]
I don't think we can accept a submission that simply changes the `G` to a `B`. The current code uses Standard International notation, and if we deviate from this, we probably need to localize to all of Visual Studio's supported languages.

Therefore, if we change it, we should introduce a new string resource for each suffix, handle the fact that not all languages will use single character abbreviations, and put a suitable comment in the string resource for translators to understand what each of these strings represent.

**Comment by aloisdg** [comment]
As a European (and, caveat, the dude who brings the SI to [Humanizer](https://github.com/Humanizr/Humanizer/blob/7e20c402fa9f1e1bee889bec2f34703743f603c9/src/Humanizer/MetricNumeralExtensions.cs)) please keep it as it. It is clearer for the non imperial world. Keep the k for thousands and the G for billion as per the standard :)

If we really want to translate it, let's add [lakh, crore,  arab, kharab, etc](https://en.wikipedia.org/wiki/Indian_numbering_system) for our Indian friends.

But I really think that we should not deviate from the standard.

**Comment by Amritanshu02** [comment]
Hello! I would like to work on this issue , could you suggest me where to start??

**Comment by erdembayar** [comment]
Please consider https://github.com/NuGet/NuGet.Client/pull/4255#discussion_r706337586 next time.

**Comment by erdembayar** [comment]
@aortiz-msft @chgill-MSFT @dominoFire @donnie-msft 
As part of PR https://github.com/NuGet/NuGet.Client/pull/4255 we 're getting this fix with localization. Now people in USA getting `1B`, but people in other side of world still wants `1G`. Do I need to request localization team to add translation or it happen automatically as part of workflow?

Previous experience on PMUI:
![image](https://user-images.githubusercontent.com/8766776/133136353-90dee8a1-39f7-45ce-9888-3cbcbaa06bd6.png)

New experience on PMUI:
![image](https://user-images.githubusercontent.com/8766776/133136198-6a6ea077-1838-4724-9695-83faeb44bbcb.png)

**Comment by dominoFire** [comment]
@erdembayar  Loc team will pick up loc changes automatically
