### ISSUE TITLE
LinkEmbeddableAssemblies targets in Nuget.VisualStudio and Nuget.SolutionRestoreManager.Interop packages collide, one overwrites the other

### ISSUE THREAD

**Issue by jimmylewis** [NuGet/Home#10868]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): 
msbuild (really, any of the above)

Product version: 
any recent version

Worked before? If so, with which NuGet version: 
Not to my knowledge, I'm cleaning up old workarounds and ran into this.

## Repro steps and/or sample project

1. Have a project which references both the Nuget.VisualStudio and Nuget.SolutionRestoreManager.Interop nuget packages (e.g. I'm building a VS extension that relies on NuGet).
2. Build the project

**Expected:**
Nuget.VisualStudio should be referenced with EmbedInteropTypes set to true, because of https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Clients/NuGet.VisualStudio/NuGet.VisualStudio.targets#L9

**Actual:**
It's not set to embed interop types, because https://github.com/NuGet/NuGet.Client/blob/f24bad0668193ce21a1db8cabd1ce95ba509c7f0/src/NuGet.Clients/NuGet.SolutionRestoreManager.Interop/NuGet.SolutionRestoreManager.Interop.targets#L6 uses the same target name, so when building we can see in the build log:
>Overriding target "LinkEmbeddableAssemblies" in project "C:\Users\jamlew\.nuget\packages\nuget.visualstudio\6.0.0-preview.0.2\build\NuGet.VisualStudio.targets" with target "LinkEmbeddableAssemblies" from project "C:\Users\jamlew\.nuget\packages\nuget.solutionrestoremanager.interop\5.8.0\build\NuGet.SolutionRestoreManager.Interop.targets".

### Digression:
This can have downstream ramification if another project references this.  In the case I'm hitting, the referencing project (I'll call it ProjectB) references the original (ProjectA) and Nuget.VisualStudio only (though Nuget.SRM.Interop is passed transitively, it's build targets are not by default).  This causes ProjectA's generated ProjectA.csproj.nuget.g.targets to contain:
``` 
<Import Project="$(NuGetPackageRoot)nuget.visualstudio\6.0.0-preview.0.2\build\NuGet.VisualStudio.targets" Condition="Exists('$(NuGetPackageRoot)nuget.visualstudio\6.0.0-preview.0.2\build\NuGet.VisualStudio.targets')" />
<Import Project="$(NuGetPackageRoot)nuget.solutionrestoremanager.interop\5.8.0\build\NuGet.SolutionRestoreManager.Interop.targets" Condition="Exists('$(NuGetPackageRoot)nuget.solutionrestoremanager.interop\5.8.0\build\NuGet.SolutionRestoreManager.Interop.targets')" />
```

But ProjectB.csproj.nuget.g.targets only contains:
```
<Import Project="$(NuGetPackageRoot)nuget.visualstudio\6.0.0-preview.0.2\build\NuGet.VisualStudio.targets" Condition="Exists('$(NuGetPackageRoot)nuget.visualstudio\6.0.0-preview.0.2\build\NuGet.VisualStudio.targets')" />
```

Because ProjectA does not to embed types from Nuget.VisualStudio, but ProjectB does, ProjectB can encounter a compilation error: 
>CSC : error CS1762: A reference was created to embedded interop assembly 'nuget.visualstudio, Version=6.0.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because of an indirect reference to that assembly created by assembly 'ProjectA, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Consider changing the 'Embed Interop Types' property on either assembly.

This was historically addressed by the Microsoft.VisualStudio.SDK.EmbedInteropTypes package, but that package is no longer recommended for Dev17, which has exposed this issue.

I have two workarounds:
- Keep maintaining my own workaround target to always embed Nuget.VisualStudio (this works, but kind of sucks for me if Nuget.VS ever decides to stop embedding types in the future, as the rest of the Dev17 VS interop assemblies have already done)
- I can use `<IncludeAssets>all</IncludeAssets>` as described in https://github.com/NuGet/Home/issues/3342#issuecomment-459334177 to make all the build targets transitive, but this will still end up with Nuget.VS not embedding types (because both projects would override the target) even though it's currently expected to be embedded.

### Back on topic:
It seems like the simplest fix is to give these targets unique names ("LinkNugetVisualStudioEmbeddableAssemblies" and "LinkNugetSolutionRestoreManagerInteropEmbeddableAssemblies" maybe?) so they don't have the target name collision anymore.

**Comment by nkolev92** [comment]
Thanks for the detailed analysis @jimmylewis!

> This was historically addressed by the Microsoft.VisualStudio.SDK.EmbedInteropTypes package, but that package is no longer recommended for Dev17, which has exposed this issue.

This would only work if you referenced an interop package that allowed the build assets of the `fix` package to flow, right? 
As in, you would still need to reference a package directly to get it embedded, it wouldn't get embedded transitively by default. It only **worked** because another package brought in a closer reference to the EmbedInteropTypes package which ended up include the build targets. 

Am I missing something? I'm basically considering whether using `buildTransitive` is the right approach here. 

Curious what use do you have for Nuget.SolutionRestoreManager.Interop, as that's something that's normally between the project system and NuGet only.

**Comment by jimmylewis** [comment]
>>This was historically addressed by the Microsoft.VisualStudio.SDK.EmbedInteropTypes package, but that package is no longer recommended for Dev17, which has exposed this issue.
>
>This would only work if you referenced an interop package that allowed the build assets of the fix package to flow, right?
As in, you would still need to reference a package directly to get it embedded, it wouldn't get embedded transitively by default. It only worked because another package brought in a closer reference to the EmbedInteropTypes package which ended up include the build targets.

Correct.

It looks like this issue will become a moot point after your change to remove EmbedInteropTypes is completed.  I'll track change that so I can remove my workarounds for this issue.
