### ISSUE TITLE
Unable to install NuGets with .pp DirectoryNotFoundException thrown + converted to %2B

### ISSUE THREAD

**Issue by jamesmontemagno** [NuGet/Home#1087]
I have a bunch of NuGet packages that are including content with .txt.pp or .cs.pp that get transformed. With VS 2015 when my developers are installing the packages they get the following error:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\rmdne.nuget\packages\Xam.Plugin.Connectivity\1.0.2\content\portable-net45%2Bwp8%2Bwpa81%2Bwin8%2BMonoAndroid10%2BMonoTouch10%2BXamarin.iOS10\PluginsHelp\ConnectivityReadme.txt.pp'.

The file DOES exist on disk in this location, but all of my + are transformed to %2B, which seems to be causing an issue. 

Here is my nuspec: https://github.com/jamesmontemagno/Xamarin.Plugins/blob/master/Connectivity/Connectivity.Plugin.nuspec

Ideas?

**Comment by chrisaswain** [comment]
Is there a work-around for this?

**Comment by jamesmontemagno** [comment]
The work around is to create that file in the project it can't fine. For instance here you need to create a ConnectivityReadme.txt in the PluginHelper folder of your PCL.

**Comment by yishaigalatzer** [comment]
@zhili1208 please take a look, and lets discuss if we are taking it to 3.1.2 or 3.2

@jamesmontemagno note that long term (project.json) we are removing support for transformations and content scaffolding into a project, its a good idea to start considering removing these. Short term we will take a look and provide a fix.

**Comment by chrisaswain** [comment]
@jamesmontemagno I was able to get it working using the work-around you suggested.  Not much effort at all.  Thanks so much!

**Comment by jamesmontemagno** [comment]
@yishaigalatzer that is sad to hear about transforms :( is there going to be a replacement? It is a powerful feature.

**Comment by yishaigalatzer** [comment]
We plan to deprecate project content in general when you opt into project.json scenarios. But we plan on adding scaffolding gestures that could potentially include tranforms.

**Comment by yishaigalatzer** [comment]
We might add transforms back as part of support for scaffolding, this was not discussed in depth yet, but I will bring it up

**Comment by s-doerfler** [comment]
workaround: we just donwloaded the .nupkg file to our local nuget source and installed it from there, as the url doesn't get encoded this way (bypassing the REST service)

**Comment by biste5** [comment]
workaround: update it using Xamarin Studio instead
