### ISSUE TITLE
Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50

### ISSUE THREAD

**Issue by mairaw** [NuGet/Home#10875]
---
**Issue moved from dotnet/core#6262**
- Please respond to @prateekchawla.

---

_From @prateekchawla on Thursday, May 13, 2021 6:54:41 PM_

### Description

Building a .net project on a worker node.  with .net sdk 5 installed &  Azure Functions Core Tools installed 
### Configuration

**Error** 
`error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0`

> E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\ShiftRiskRelayFx\ShiftRiskRelayFx.csproj : error NU1202: Package Microsoft.Azure.Functions.Worker 1.2.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Microsoft.Azure.Functions.Worker 1.2.0 supports: net5.0 (.NETCoreApp,Version=v5.0) [E:\Jenkins\workspace\DotNet\Azure\Builds\azure-fx-shift-build\Shift.sln]
 
 
 **Proj file looks like this**
 
```
 <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.8.3" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.3" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
```

**Comment by mairaw** [comment]
---
**Issue moved from dotnet/core#6262**
- Please respond to @mairaw.

---

_From @mairaw on Thursday, May 13, 2021 9:47:57 PM_

@rrelyea can you help with this issue? Should we move this to NuGet?

**Comment by mairaw** [comment]
---
**Issue moved from dotnet/core#6262**
- Please respond to @GrabYourPitchforks.

---

_From @GrabYourPitchforks on Monday, May 17, 2021 10:31:23 PM_

/cc @rrelyea @nkolev92 - I agree with Maira and think this issue should be transferred to NuGet.

**Comment by mairaw** [comment]
---
**Issue moved from dotnet/core#6262**
- Please respond to @nkolev92.

---

_From @nkolev92 on Monday, May 17, 2021 11:02:20 PM_

You can move this to NuGet. 

Based on the stack trace though, I'm fairly confident it's an old tooling version that's being used. 

.NET 5 is only supported with NuGet.exe 5.8, VS 16.8, .NET 5.0.100 SDK and later.

**Comment by prateekchawla** [comment]
It built fine on other machine while we installed .Net 5.0 SDK using Jenkins plugin instead of installing it via installer(since the issue  was happening on a build machine)
Thanks!

**Comment by nkolev92** [comment]
@prateekchawla 

Is this resolved now?

**Comment by aortiz-msft** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 

Please feel free to comment or open a new issue if needed.
