### ISSUE TITLE
Sdk resolver does not honor --configfile; and fails silently

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#10886]
Issue copied from https://github.com/dotnet/sdk/issues/17319 per request of @erdembayar

## Details about Problem

When performing `dotnet restore` using the --configfile argument, the nuget Sdk resolver does not honor the --configfile setting. 

This results in two problems:
 
1. restore fails to restore the SDKs in question.
2. the restore exist with a success exit code, when it should not.

This issue is tracking the first problem. (second problem tracked by separate issue, https://github.com/dotnet/msbuild/issues/6281)

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

> aaronla@aaronla-rabbit:repro_sdk$ dotnet --version
> 5.0.202

Product version: 

Worked before? If so, with which NuGet version: 

> No

## Repro steps and/or sample project

1. git clone https://github.com/aaronla-ms/bug-repros
2. cd bug-repros/repro_sdk
3. dotnet restore --configfile custom_nuget.config
4. dotnet build --no-restore

```
[git: main]
aaronla@aaronla-rabbit:repro_sdk$ dotnet restore --configfile custom_nuget.config

[git: main]
aaronla@aaronla-rabbit:repro_sdk$ echo %ERRORLEVEL%
0

[git: main]
aaronla@aaronla-rabbit:repro_sdk$ dotnet build --no-restore
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

c:\repos\aaronla-ms\bug-repros\repro_sdk\my.csproj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.

Build FAILED.

c:\repos\aaronla-ms\bug-repros\repro_sdk\my.csproj : error MSB4236: The SDK 'Microsoft.Build.Traversal' specified could not be found.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.12

```

Expected: restore succeeds, and build succeeds

Actual: restore reports success, but did not restore anything. Consequently, build fails.

**Comment by rseanhall** [comment]
This seems to be a duplicate of https://github.com/NuGet/Home/issues/7855.

**Comment by ghost** [comment]
Wow. Very old bug. Agreed, dup of [#7855](https://github.com/NuGet/Home/issues/7855.

I guess what I'm hearing is to not hold my breath for a fix.
