### ISSUE TITLE
Q: Is (or should) the NuGet.org package repository be automatically made available on fast, local storage to the Azure cloud?

### ISSUE THREAD

**Issue by selangley-wa** [NuGet/Home#10881]
My team uses Microsoft-hosted Azure DevOps pipelines for building or .NET projects.

Azure DevOps provides a pipeline Cache task for such things as caching the NuGet packages used by your project in between runs.
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#netnuget

Why is this even beneficial?  

Microsoft owns NuGet.  Why isn't every package on NuGet automatically made available for quick access to Azure DevOps and all of Azure?

**Comment by zkat** [comment]
We don't own this, unfortunately. You'd have to file a feature request against AzDO itself, through Developer Community.

**Comment by selangley-wa** [comment]
OK.

I created such an request for Azure DevOps here:
https://developercommunity.visualstudio.com/t/Make-the-NuGetorg-package-repository-au/1430613
