### ISSUE TITLE
NuGet invocation ends with a non-zero return code when it should not have done

### ISSUE THREAD

**Issue by paul-hammant** [NuGet/Home#10884]
List of nuget adds doesn't complete.

```
nuget add /path/to/package.nupkg -source ~/.nuget
nuget add /path/to/package2.nupkg -source ~/.nuget
nuget add /path/to/package3.nupkg -source ~/.nuget
```

First line completes its job, second line never invokes.

Nuget is v5.9.1.11 on Mac 11.3.1

This works differently for when these three are in a .sh script with `set -e` - they all work, versus when the three are pasted into a terminal - second and third are not executed.  Is nuget sniffing the terminal via [isatty](https://pubs.opengroup.org/onlinepubs/9699919799/functions/isatty.html) or other?

On Windows 10 (Windows Terminal) with the same version of Nuget, the multi-command paste doesn't stop at the first one. Works as intended.

**Comment by aortiz-msft** [comment]
Thank you for the feedback. We just want to make sure you are aware of dotnet nuget add as a natively supported cross-plat CLI.

**Comment by paul-hammant** [comment]
Thanks, I'll look into that.

My wider quest is for a workflow like Maven's -SNAPSHOT suffix for versions. You know, develop a lib on my dev workstation, and in a different clone/checkout try that just-built uncommitted unreleased DLL as a dep.

**Comment by zivkan** [comment]
@aortiz-msft `dotnet nuget add` is used to add package sources to config files, or https client certificate to config files. There is no direct equivalent to `nuget.exe add` (expand nupkgs to a local feed, in v3 folder layout).

push (`nuget.exe push`, or `dotnet nuget push`) can be used to add packages to a local feed. However, `nuget add` will always use the v3 folder layout, whereas push will [use the v2 folder layout if the directory is empty to start with](https://github.com/NuGet/Home/issues/7383). Once a local folder already is in v3 layout, pushing additional packages will keep using the v3 folder layout.

I've never actually tested it, but if you have a nuget.config file with a package source specifying the `protocolVersion="3"` attribute, maybe push will be forced to use the v3 layout, even if the directory is empty. But there's a chance that `protocolVersion` is only used for HTTP feeds.

**Comment by zkat** [comment]
This scenario as described is not supported, so I'm closing this one. If you're interested in a feature like Maven's `-SNAPSHOT`, please go ahead and file a new feature request issue for that. Thanks for your time! :)
