### ISSUE TITLE
[Pack][Doc] The useages of option “--force” and “--no-dependencies” should be deleted from the “dotnet pack” page

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10883]
## Details about Problem
VS Version: Main\31319.342
NuGet Version: Release-6.0.x\6.0.0.46
OS Version: Windows-10-Enterprise-21H1
Dotnet SDK: 6.0.100-preview.4.21255.9
## Repro steps 
1. Launch VS and create a new C# Class Library (.NET 6.0). 
2. Open the Developer Command Prompt and cd to the project path. 
3. Run “dotnet pack --force” or “dotnet pack --no-dependencies”.
4. Check the info on the [dotnet pack](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x) page.
## Expected
The useages of option “--force” and “--no-dependencies” should be deleted from the “dotnet pack” page.
## Actual
The useages of option “--force” and “--no-dependencies” are not deleted from the “dotnet pack” page since they are not support now as below screenshots.
![image](https://user-images.githubusercontent.com/20632625/118958022-9b31df00-b993-11eb-8da9-e3f42ff43038.png)
![image](https://user-images.githubusercontent.com/20632625/118958046-a1c05680-b993-11eb-93c5-81aedc242eb5.png)

**Comment by zkat** [comment]
Woo! Nice catch.

**Comment by aortiz-msft** [comment]
@v-luzh - We weren't able to repro anymore with NET6.0 RC1. Would you please check?

**Comment by v-luzh** [comment]
@aortiz-msft Yes, it is fixed on .NET SDK 6.0.100-rc.1.21458.32. Thanks.
