### ISSUE TITLE
Packages path not joined correctly

### ISSUE THREAD

**Issue by Nezz** [NuGet/Home#1088]
Our build sever receives the following error with NuGet 3.1:

```
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : The package Microsoft.CSharp with version 4.0.0 could not be found in C:\WINDOWS\system32\config\systemprofile.nuget\packages. Run a NuGet package restore to download the package.
```

It seems to me that the path `C:\WINDOWS\system32\config\systemprofile.nuget\packages` is missing a `\` before `.nuget` because the the paths are not joined correctly.

**Comment by tomspilman** [comment]
Follow-up on this issue...  the build server @Nezz mentions was running under the Windows system account.  Once I had it run under its own user account the issue went away.

**Comment by yishaigalatzer** [comment]
@tomspilman thanks for the clarification

**Comment by yishaigalatzer** [comment]
Given that this will not work with the system account anyways, I'm going to close this issue as won't fix.

Feel free to push back if you feel this is a wrong decision
