### ISSUE TITLE
nuget add doesn't sanity-check source path

### ISSUE THREAD

**Issue by paul-hammant** [NuGet/Home#10885]
Nuget does not warn the user they've malformed their `-source` path:

```
nuget add path/to/something.nupkg -source ~/.nuget/packages
nuget add path/to/something.nupkg -source ~/.nuget
```

Both of these work. Only one should. ~/.nuget/packages is where the "local feed" is. The other should be vetoed as a -source path.  Perhaps a `-localfeed` or `-source *LOCAL` or `-source *LOCALFEED` or better would be clearer

For the record, my Nuget is v5.9.1.11 on Mac 11.3.1

**Comment by heng-liu** [comment]
Hi @paul-hammant , thanks for taking time reporting this!
According to the [doc](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-add), there is no checking on the folders to see if it's a "local feed" or not.
```
-src|-Source

Specifies the package source, which is a folder or UNC share, to which the nupkg will be added. Http sources are not supported.
```
So yeah, you have to check the NuGet.Config file to check the path of a local feed and pass it to the nuget add command.
