### ISSUE TITLE
Hard to see the background color of the number on the right of “Updates” and “Consolidate” tabs in the Dark theme

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10896]
## Details about Problem
VS Version: Main\31326.288
NuGet Version: Release-6.0.x\6.0.0.66
OS Version: Windows-10-Enterprise-21H1
## Repro steps and/or sample project
1.	Launch VS and create a solution with multiple projects. 
2.	Open Tools->Options->Environment and select the “Dark” in the “Color Theme” drop-down list.
3.	Open the solution PM UI and install a package (with different versions) into difference projects.
4.	Check the background color of the number on the right of “Updates” and “Consolidate” tabs.
## Expected
The background color of the number on the right of “Updates” and “Consolidate” tabs in the Dark theme is easy to see (like what we did in Blend theme in the Blend for VS as below).
![image](https://user-images.githubusercontent.com/20632625/119794454-20744100-bf0a-11eb-9f8e-da5e87a2ea4b.png)
## Actual
Hard to see the background color of the number on the right of “Updates” and “Consolidate” tabs in the Dark theme as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/119794526-2e29c680-bf0a-11eb-9296-4c6d3219f4ef.png)
## Note
Seems it is caused by Dark theme design changed in VS so I didn't provide the NuGet regression info. But we should update the background color for the new design changes.

**Comment by aortiz-msft** [comment]
@jebriede - Would you please take a look?

**Comment by v-luzh** [comment]
The bug doesn't repro on Main\31409.290 since the VS Dark theme design changed back as below.
![image](https://user-images.githubusercontent.com/20632625/121503913-18d98f80-ca14-11eb-8b87-85b1e53bbedf.png)

**Comment by v-luzh** [comment]
Repro again on Main\31414.215.

**Comment by donnie-msft** [comment]
@aortiz-msft just a reminder to always add product & type labels as well :)

**Comment by donnie-msft** [comment]
I reached out to UX folks and they are actively working on styling, and are aware of this bug.

**Comment by aortiz-msft** [comment]
@donnie-msft @jebriede - What are the next steps for this one?

**Comment by donnie-msft** [comment]
@aortiz-msft I pinged UX team for an update.

**Comment by donnie-msft** [comment]
Self-assigning since I've been talking to UX.
They are supposed to work on this bug this week: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385968?src=WorkItemMention&src-action=artifact_link
