### ISSUE TITLE
dotnet pack produces a package with copyToOutput not applied

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#10906]
---
**Issue moved from dotnet/sdk#17662**
- Please respond to @melanchall.

---

_From @melanchall on Monday, May 17, 2021 12:33:38 PM_

I have a small sample solution: [DualLibClassLibrary.zip](https://github.com/dotnet/sdk/files/6493577/DualLibClassLibrary.zip).

The structure of the solution:

```
├ DualLibClassLibrary
·  ├ native
·  ·  ├ test.dll
·  ·  └ test.dylib
·  ├ Class.cs
·  └ DualLibClassLibrary.csproj
└ DualLibClassLibrary.sln
```

As you can see I have following lines in csproj:

```xml
<ItemGroup>
  <Content Include="native\*">
    <Pack>true</Pack>
    <PackageCopyToOutput>true</PackageCopyToOutput>
    <PackageFlatten>true</PackageFlatten>
    <PackagePath>contentFiles;content</PackagePath>
  </Content>
</ItemGroup>
```

When I run `dotnet pack` I'll get a package with following metadata:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>DualLibClassLibrary</id>
    <version>1.0.0</version>
    <authors>melanchall</authors>
    <owners></owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Dual-lib class library</description>
    <copyright>Copyright © Melanchall 2021</copyright>
    <dependencies>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
    <contentFiles>
      <files include="test.dll" buildAction="Content" copyToOutput="true" flatten="true" />
      <files include="test.dylib" buildAction="Content" copyToOutput="true" flatten="true" />
    </contentFiles>
  </metadata>
</package>
```

So there are `copyToOutput="true"` attributes on the files.

Now we create a small .NET Framework console application: [ConsoleAppFramework.zip](https://github.com/dotnet/sdk/files/6493719/ConsoleAppFramework.zip).

The structure of the solution:

```
├ ConsoleAppFramework
·  ├ Properties
·  ·  └ AssemblyInfo.cs
·  ├ App.config
·  ├ ConsoleAppFramework.csproj
·  └ Program.cs
└ ConsoleAppFramework.sln
```

Now if we install the `DualLibClassLibrary` package into the project, we'll get following project structure:

![image](https://user-images.githubusercontent.com/26361185/118488604-93203800-b724-11eb-8a3e-8c478c13eba8.png)

So we have `test.dll` and `test.dylib` in the solution. Looks good, **BUT** let's take a look at the csproj:

```xml
<ItemGroup>
  <None Include="App.config" />
  <None Include="packages.config" />
  <None Include="test.dylib" />
</ItemGroup>
<ItemGroup>
  <Content Include="test.dll" />
</ItemGroup>
```

Hmm... `test.dylib` added as `None`, `test.dll` added as `Content` and.. no one item has `CopyToOutputDirectory` set. If we build the project, we obviously won't get libraries copied to output directory.

Maybe I do something wrong? Looks strange and absolutely unexpectedly.

I found on the Internet this issue: https://github.com/NuGet/Home/issues/6404. There is a comment there:

> The way content files are copied is that NuGet writes them in the props file and then later the build task picks them up.

But after `dotnet pack` I don't see any `.props` file so it looks like a bug of `dotnet pack`.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#17662**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Monday, May 17, 2021 12:33:41 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#17662**
- Please respond to @melanchall.

---

_From @melanchall on Tuesday, June 1, 2021 3:26:09 PM_

@wli3 Any news?

**Comment by melanchall** [comment]
Any movement on the issue? Looks like a bug.

**Comment by nkolev92** [comment]
Hey @melanchall 

There are 2 concepts for content distribution in NuGet. 

One is of the mutable type, `content` folder, the other one is of the immutable type, `contentFiles`. 


* The `content` folder is supported in packages.config.
* The `contentFiles` folder is supported in PackageReference. 

Please refer to https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files and https://devblogs.microsoft.com/nuget/nuget-contentfiles-demystified/. 

With content in packages.config projects, I don't think you can control the item type it gets added under.

**Comment by melanchall** [comment]
@nkolev92 

> With content in packages.config projects, I don't think you can control the item type it gets added under.

This statement implies (in my opinion) that in .NET Core/.NET apps everything should work (since there is no packages.config there). Well, I've checked with both .NET Core 3.1 and .NET 5 and see the same situation except slightly different text of the exception:

![image](https://user-images.githubusercontent.com/26361185/122534351-1a661180-d02b-11eb-9566-3aac5eb13d22.png)

nupkg I used for tests: [DualLibClassLibrary.1.0.1.nupkg.zip](https://github.com/NuGet/Home/files/6675869/DualLibClassLibrary.1.0.1.nupkg.zip)

The original issue is not with items types. It looks like `copyToOutput` attribute is totally ignored and does nothing, but in [Microsoft docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files) I see:

> **copyToOutput**	A Boolean indicating whether to copy content items to the build (or publish) output folder. The default is false.

So the attribute doesn't do what it must do. Can you please explain how the attribute works (if it really works) and how to achieve copying content files to output directory with it?

Thanks

**Comment by zivkan** [comment]
Please see our [docs on `contentFiles`](https://docs.microsoft.com/en-us/nuget/reference/nuspec#package-folder-structure). It supports adding different content depending on project's target framework and language, and therefore needs files in a specific structure which your package is not currently using.

**Comment by melanchall** [comment]
@zivkan Thanks, now it works!
