### ISSUE TITLE
Android .NET 6 Preview 5 fallbacks not working

### ISSUE THREAD

**Issue by jonathanpeppers** [NuGet/Home#10903]
## Details about Problem

NuGet product used: _dotnet.exe_

Product version: _.NET 6.0.100-preview.6.21276.2 or .NET 6.0.100-preview.5.21278.1_

Worked before? If so, with which NuGet version: _this was testing a new feature in NuGet_

## Repro steps and/or sample project

Context: https://github.com/dotnet/designs/blob/main/accepted/2021/net6.0-tfms/net6.0-tfms.md
Context: https://github.com/NuGet/NuGet.Client/pull/4042
Context: https://github.com/xamarin/xamarin-android/pull/5973

We had some workarounds for NuGet since early in .NET 5 development. This involved setting `$(AssetTargetFallback)` and/or `$(PackageTargetFallback)`.

We got on a build of dotnet/installer that includes: https://github.com/NuGet/Home/issues/10819

So I removed our workarounds, however I hit an error during restore on this sample app:

https://github.com/dotnet/maui-samples/tree/main/HelloAndroid

```
HelloAndroid.csproj : error NU1202: Package Xamarin.AndroidX.Migration 1.0.8 is not compatible with net6.0-android30.0 (.NETCoreApp,Version=v6.0). Package Xamarin.AndroidX.Migration 1.0.8 supports: monoandroid90 (MonoAndroid,Version=v9.0)
```

It seems like this restore should succeed? This package only has `monoandroid90` inside. Thanks!

### Verbose Logs

[msbuild.zip](https://github.com/NuGet/Home/files/6561828/msbuild.zip)

**Comment by jonathanpeppers** [comment]
Actually, perhaps we _don't_ have a new enough dotnet/installer:

https://github.com/dotnet/installer/blob/3ebe0ca9715283842b003a75cf2b3603ca28d964/eng/Version.Details.xml#L124-L127

I'll try using a newer build.

**Comment by heng-liu** [comment]
I think you're right. The PR related to NuGet is inserted into dotnet release/6.0.1xx-preview5 branch not long ago.

**Comment by heng-liu** [comment]
I'll close the issue for now. Please reopen it if the new build still doesn't work. Thanks!
