### ISSUE TITLE
NuGet package not listing dependencies

### ISSUE THREAD

**Issue by dotnetspark** [NuGet/Home#10904]
## Details about Problem

NuGet product used is Visual Studio 2019 Enterprise edition. See below for the .csproj:

![image](https://user-images.githubusercontent.com/63487874/120093648-a69aae00-c0e9-11eb-8d79-b5ebe53769e0.png)

Above are listed the dependencies. When I run the build command, and the package is created. I open it with NuGet Package Explorer and I see the dependencies are listed.

![image](https://user-images.githubusercontent.com/63487874/120093723-0002dd00-c0ea-11eb-88f7-29ca69bd5667.png)

However, after the CI pipeline is done and the package is published to the Artifacts. I go to the project where I need to add the package I just created, and I notice no dependencies are listed in the NuGet Package for the solution.

See pipeline

![image](https://user-images.githubusercontent.com/63487874/120114116-9fa48780-c14b-11eb-9948-33e5c50df8f4.png)

See NuGet Package Manager (no dependencies)

![image](https://user-images.githubusercontent.com/63487874/120093854-ef069b80-c0ea-11eb-91b9-53a0a6b230b5.png)

I ignored that and continued with the installation. However, at runtime it throws an exception about those libraries in the dependencies section are missing.

**Comment by dominoFire** [comment]
Thanks for your report, @ylr-research 

For projects created with `dotnet` CLI, it's preferable to pack using `dotnet pack` 

`nuget.exe` works better with .NET Framework projects.

**Comment by dotnetspark** [comment]
@dominoFire thanks for the quick response. For packing I'm using the Nuget task from Azure DevOps. I just changed to DotNetCLI task. If you have any more details on how to implement this, please let me know

**Comment by dotnetspark** [comment]
@dominoFire it worked. Changing to DotNetCLI task was the thing. There is one thing though, it publishes to the feed my package + dependencies as separate packages. Is there any way to stop that?

**Comment by dominoFire** [comment]
@ylr-research `dotnet nuget push` publishes a given package. If you use a glob (`*`), it will publish all package files that matches the glob.

**Comment by dotnetspark** [comment]
got it now. I was using for push the NuGet task as well instead of DotNetCoreCLI. Thanks
