### ISSUE TITLE
Microsoft.Data.SqlClient should be suggested

### ISSUE THREAD

**Issue by ErikEJ** [NuGet/Home#10909]
Package suggestions: should suggest Microsoft.Data.SqlClient instead of System.Data.SqlClient

**Comment by dominoFire** [comment]
cc @birgithi

**Comment by aortiz-msft** [comment]
Recommendations are based on ML. We cannot do something to address this specifically.

**Comment by ErikEJ** [comment]
This is not Skynet, and you are in charge. This recommendation is plain wrong, and your model needs to be fixed, IMHO.
