### ISSUE TITLE
Azure Functions netcore3.1 adding Assemblies Nuget.Packaging not found exception

### ISSUE THREAD

**Issue by nehio** [NuGet/Home#10915]
Nuget.Protocol 4.8.0.6 | Visual Studio 2019 16.9.5 | dotnet 3.1.15 

Worked before NuGet version: Nuget.Protocol 4.7.3

I don't know if this issue is related to Azure Functions or Nuget itself but i'm trying to add some assemblies to the Azure Functions DLL library (Dependent on framework netcore3.1) :

```
            var assemblyParts = new List<AssemblyPart>();
            var assemblyNames = new[]
            {
                "netstandard",
                "Microsoft.AspNetCore.Html.Abstractions",
                "Microsoft.AspNetCore.Mvc.Abstractions",
                "Microsoft.AspNetCore.Mvc.Razor",
                "Microsoft.AspNetCore.Mvc.TagHelpers",
                "Microsoft.AspNetCore.Mvc.ViewFeatures",
                "Microsoft.AspNetCore.Razor",
                "Microsoft.AspNetCore.Razor.Runtime",
                "Microsoft.CSharp",
                "Microsoft.Extensions.Localization",
                "Microsoft.Extensions.Localization.Abstractions",
                "System.Collections",
                "System.Core",
                "System.Dynamic.Runtime",
                "System.Linq",
                "System.Linq.Expressions",
                "System.Private.CoreLib",
                "System.Runtime",
                "System.Text.Encodings.Web",
            };

            foreach (var assemblyName in assemblyNames)
            {
                var assemblyPart = new AssemblyPart(Assembly.Load(new AssemblyName(assemblyName)));
                assemblyParts.Add(assemblyPart);
            }

            Assembly assemblyViews;
            if (isDevelopment)
                assemblyViews = AssemblyLoadContext.Default.LoadFromAssemblyPath($"{Directory.GetCurrentDirectory()}\\Project.Views.dll");
            else
                assemblyViews = Assembly.Load(new AssemblyName("Project.Views"));
services.AddMvc()
                .ConfigureApplicationPartManager(apm =>
                {
                    // Assemblies System
                    apm.ApplicationParts.AddRange(assemblyParts);

                    // Assemblies
                    apm.ApplicationParts.Add(new AssemblyPart(MyAssembly));

                    var a = new CompiledRazorAssemblyApplicationPartFactory();

                    foreach (var b in a.GetApplicationParts(assemblyViews))
                        apm.ApplicationParts.Add(b);
                })
                .AddMvcLocalization()
                .AddDataAnnotationsLocalization();
```
This code fails with the following error on the services.AddMvc() call when adding everything : 
![image](https://user-images.githubusercontent.com/9347422/120825596-d3bbe600-c559-11eb-90cc-c616921213e1.png)

I've also tried adding the dependency into the project for Nuget.Packaging without any success. Everything before 4.8 works like a charm, everything after crashes with the same error.

Thank you for any help on this and have a good day

**Comment by nkolev92** [comment]
Hey @nehio, 

Unfortunately I'm not sure I have enough context to offer any advice here.

I don't see anything of note that could cause this failure that changed between 4.7 and 4.8 of https://www.fuget.org/packages/NuGet.Protocol/4.8.0/lib/netstandard1.6/diff/4.7.3/. 

Are you loading the assemblies directly yourself? 
I'd recommend enabling fuslogvw and inspecting the logs.

**Comment by zivkan** [comment]
This is happening because of the Azure Functions SDK. See also:
https://github.com/NuGet/Home/issues/10118
https://github.com/Azure/azure-functions-host/issues/6650
https://github.com/Azure/azure-functions-host/issues/5894
