### ISSUE TITLE
Pop-up the an error window: We could not refresh the credentials for the account Non-HTTPS url redirect is not supported in webview

### ISSUE THREAD

**Issue by Vfangma** [NuGet/Home#10912]
**Steps to reproduce:**
1. Tools-> Options-> Environment-> Accounts-> Add and reauthenticate accounts using: Embedded web browser
2. Go to File -> Account settings -> Sign in -> type account and click "Next"
3. Click the "Help&Support" at the bottom of right
4. Check

**Expected result:**
It should enter the document normally

**Actual result:**
It will pop-up the an error window
![Embedded web browser](https://user-images.githubusercontent.com/71419725/120625583-727e0f00-c494-11eb-9b2b-e82b514bf3bf.gif)

**Comment by nkolev92** [comment]
Hey @Vfangma, 

Seems like you are dealing with a more generic VS issue. 

Can you please file at https://developercommunity2.visualstudio.com/home, as we cannot really move this issue there from GitHub.
