### ISSUE TITLE
Add a package field for APIs

### ISSUE THREAD

**Issue by ElectricErger** [NuGet/Home#10911]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Systematic, but Visual Studio I guess

Product version: 3.4

Worked before? If so, with which NuGet version: N/A

## Repro steps and/or sample project
Allow me to paint an example of the UX of selecting a package.
1. Use your favourite tool to search NuGet's listings of packages (ex. Looking for a package to handle "Json" processing).
2. Select a package
3. Use your favourite search engine to find the documentation of the package's API.
4. Test it out, and if you don't like it go back to step 2.

While there are probably other things in there like research forums, check licenses, and other details in there, the big concern I have is step 3. From a users perspective, it makes sense to me, for there to be a way to provide the API as part of the package experience. While it is acknowledged on the [NuGet FAQ](https://docs.microsoft.com/en-us/nuget/resources/nuget-faq) on the Microsoft Docs site that this is dealt with via the "Info" field, it's somewhat limited and "hand wavy".

Proposal: A new (optional) field in packaging details for documentation.

**Comment by ElectricErger** [comment]
Obviously this is more high-level idea stage here, but I could imagine that the documentation field(s) would most likely be something like a reference to a folder where documents are kept (auto-generated or otherwise), which could then be tar-ed up and included as part of the NuGet package file.

I'll also say, if this functionality does exist, I couldn't find it. If it does exist, then maybe the solution is to make it more visible.

**Comment by dominoFire** [comment]
Thanks for your taking time in filling this issue, @ElectricErger 

We have README support on NuGet packages.

https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/

For now, I will close this issue since it not looks like a bug. Any thoughts, please, let us know.

**Comment by ElectricErger** [comment]
Thanks DominoFire. Makes sense, I wasn't 100% sure how to request a feature, but I saw a feature tag here so I took a shot in the dark.
