### ISSUE TITLE
System.Memory referencing old version of System.Runtime.CompilerService.Unsafe

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10922]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemMemory-referencing-old-version-of/1440601)._

---
[severity:It's more difficult to complete my work]
Hi!
I've got a problem with Nuget package System.Memory (v4.5.4) which is referencing an old version of System.Runtime.CompilerService.Unsafe (v4.5.3)
This is creating problems when I am using the newest versions of Roslyns CodeAnalysis Nuget packages (v3.9.0).

The package Microsoft.CodeAnalysis.Common (v3.9.0) is referencing System.Runtime.CompilerService.Unsafe (v5.0.0).
It also references System.Memory (v4.5.4) which in turn is not referencing the same version of System.Runtime.CompilerService.Unsafe (v4.5.3).
Even if I add assembly binding instructions in Web.Config this is still not working since it's searching for the old DLL for System.Runtime.CompilerService.Unsafe anyway.

The only solution I have come up with is to install the old DLL for System.Runtime.CompilerService.Unsafe in the GAC, but this is not really optimal.
Can you please update System.Memory to reference the same version of System.Runtime.CompilerService.Unsafe as Roslyn.CodeAnalysis.Common please?

---
#### Feedback Bot on 6/3/2021, 06:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by dominoFire** [comment]
Redirecting to dotnet/runtime repo: https://github.com/dotnet/runtime/issues/53758
