### ISSUE TITLE
Question: Add dependency depending on target used dotnet-sdk

### ISSUE THREAD

**Issue by cmenzi** [NuGet/Home#10929]
I'm trying to create meta package for our coding guidelines where multiple other analyzers are added as dependencies.

This package also includes .props and .target files to configure the included analyzers with `GlobalAnalyzerConfigFiles`. This basically works very good.

Now, I have the issue that the package SecurityCodeScan analyzers have two releases: `SecurityCodeScan` (deprecated) and `SecurityCodeScan.VS2019` (new).

The problem with `SecurityCodeScan.VS2019` is, that it only works if I'm using `dotnet-sdk-5`. The author of this package also says, that `SecurityCodeScan` should be used in case of `dotnet-core-3.1` or earlier.

Is possible to specify which dependency should be used depending on the used compiler version or sdk version?

I know there are dependency groups where I can specify dependencies depending on the used TFM, but this doesn't help. Because if dotnet-sdk-5 is used and the TFM is netcoreapp3.1, then the analyzer works. So, it really depends on the used SDK or better said the used compiler version.

Thx

**Comment by nkolev92** [comment]
Hey @cmenzi 

There's no way to pivot dependencies in NuGet based on a .NET SDK version, as these concepts pre-date the notion of SDKs. 

Unfortunately I'm not sure I have too many recommendations myself beyond potentially authoring 2 packages which is not ideal. 

The nuspec's minClientVersion provides a way to limit which NuGet tooling versions can install a package, but this won't work with other 3rd party clients and it's not really obvious when all you use is dotnet.
