### ISSUE TITLE
ContentItemCollection uses yield return which is causing over-allocation of Enumerators

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10921]
ContentItemCollection uses yield return in its FindItems code path which is causing over-allocation of Enumerators. What happens with yield return is the compiler creates a type based on the method where the yield is happening, and it derives from Enumerators and at runtime it allocates an Enumerator to handle the foreach iteration. When this is done on a hot code path, as is the case here, it allocates many objects that derive from Enumerator. When restoring with OrchardCore as a solution the following allocations are made:

```
Name                                	Exc %	Exc	Exc Ct	Inc %	           Inc
Type <FindItemGroups>d__7           	     	   	      	  1.9	   170,492,112
Type <FindItemsImplementation>d__10 	     	   	      	  1.3	   119,705,840
```

**Comment by aortiz-msft** [comment]
@jebriede - Any chance we can get this one done in 2021-09?
