### ISSUE TITLE
Remove Obsolete public APIs 

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#10936]
In https://github.com/NuGet/NuGet.Client/pull/4020, we reviewed unused parameters in shipped public APIs.

The goal of this task is to remove public APIs marked as obsolete. The plan is to remove those APIs in the next minor release, saying, 6.1 or later.

**Comment by nkolev92** [comment]
Triage: @zivkan Please sync with @dominoFire for a plan of action here.

@dominoFire Keep in mind we'd only want to remove public APis in major releases.

**Comment by nkolev92** [comment]
Closing since this is a generic issue that doesn't have too much value right now.
