### ISSUE TITLE
Solution packages aren't flagged as `developmentDependency="true"`.

### ISSUE THREAD

**Issue by MicahZoltu** [NuGet/Home#1093]
Packages that are tools only (previously solution packages) should have `developmentDependency="true"` set in the `packages.config` they are added to.

A perfect example of where this makes sense is `NuGet.for.MSBuild`.  It depends on the tools only package `NuGet.CommandLine`.  Upon install into a project, `NuGet.for.MSBuild` has `developmentDependency="true"`set.  Its dependency, `NuGet.CommandLine`, does not.

This will (I believe) result in a NuGet package created from this project including `NuGet.CommandLine` but not `NuGet.for.MSBuild`, which is incorrect.  It is possible that `nuget pack` will never add tools-only packages as a dependency (I haven't tested) but magic behavior like this is undesirable when the tooling could instead just add the more obvious `developmentDependency="true"` to the `packages.config`.

**Comment by nkolev92** [comment]
No work has been done on solution level packages and they are redundant with package reference.
