### ISSUE TITLE
[CPVM] A way to suppress the preview message

### ISSUE THREAD

**Issue by alexrp** [NuGet/Home#10930]
.NET prints a preview message when using a preview SDK. But .NET also provides the `SuppressNETCoreSdkPreviewMessage` MSBuild property to suppress it. It would be nice if NuGet had a similar toggle for the CPVM preview message as it severely clutters build output in large solutions.

**Comment by nkolev92** [comment]
Hey @alexrp 

At this point, we'd want to be as clear as possible that this is a feature in development. 
We don't want to offer a suppress option at this point. 

Thanks for trying out CPVM!
