### ISSUE TITLE
Support sourceUri passed on nuget restore/install and dotnet restore package or other equivalent commands

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10948]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

Product version:  N/A

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

Address Karteek's [comment](https://github.com/NuGet/NuGet.Client/pull/4039/files#r651304501) about there are chances that users might pass -source option to the restore command. 
To support this we may need small changes `SearchTree`, `PackageDownloader.cs` and `PackageNamespacesConfiguration.cs`
files.

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 
It looks, I started working on this issue too early. I created new unit tests but I better to work on this after I complete https://github.com/NuGet/Home/issues/10738

**Comment by nkolev92** [comment]
@erdembayar 

Are you planning to validate both packages.config and PackageReference with this one?

cc @kartheekp-ms

**Comment by erdembayar** [comment]
@nkolev92 
Packages.config is yes, not sure about `PackageReference`, but I'll try to validate both.

**Comment by nkolev92** [comment]
I see `dotnet add package` is in the name, but that only handles PR. 

I'll let you and @kartheekp-ms decide, but consider splitting up the work in 2 issues.

**Comment by nkolev92** [comment]
For complete here are the scenarios of interest PC & PR. 

* nuget.exe restore -source
* dotnet.exe restore -source
* RestoreSources in csproj for PackageReference
* nuget.exe install -source
* dotnet add package -source
* PMC install-package -source
* PMC update-package -source

Note that the last 2 are not relevant in PackageReference. There's a warning message when you try that.

**Comment by erdembayar** [comment]
@nkolev92 
Could you be able to give more context on `RestoreSources in csproj for PackageReference`? How does it work?

**Comment by nkolev92** [comment]
You can do the following and it overrides the package sources specified in the nuget config.

```cs
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RestoreSources>https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="nuget.common" Version="4.9.1"/>
  </ItemGroup>

</Project>
```

**Comment by erdembayar** [comment]
@nkolev92 @kartheekp-ms 
I noticed there's another option `p:RestoreAdditionalProjectSources` besides `p:RestoreSources`.
Do we need to take into account?

**Comment by nkolev92** [comment]
@erdembayar 

Yes, but I'd expect they'd be automatically handled. 
RestoreSources, RestoreAdditionalProjectSources are all merged early on.
If your tests work with `RestoreSources`, I'd expect them to work with `RestoreAdditionalProjectSources ` as well.

**Comment by erdembayar** [comment]
I created follow up issue for `dotnet add package --source` scenario https://github.com/NuGet/Home/issues/11140
