### ISSUE TITLE
Validate Package namespaces for invalid values

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#10941]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe):

Product version: N/A

Worked before? If so, with which NuGet version: 

## Repro steps and/or sample project

Follow up on Karteek's [comment](https://github.com/NuGet/NuGet.Client/pull/4039/files#r650161734). 

`If user defines an invalid namespace such as NuGet.*Common then as per the above logic, we define a namespace on NuGet.* which may be incorrect. I think we should throw an exception because the configuration of NuGet.*Common is currently invalid. One way to do it is check the first index of * in the namespace, if first_index != namespaceId.Length-1 then throw an exception.
`

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/10783
