### ISSUE TITLE
Possible violation of "nearest wins" rule?

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#10949]
## Details about Problem

NuGet product used: NuGet CLI, VS

Product version: NuGet 5.9.1.1, VS 2019 16.9.4

## Repro steps and/or sample project

https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution says that:

> When the package graph for an application contains different versions of the same package, NuGet chooses the package that's closest to the application in the graph and ignores all others

However, I have a solution where this rule does not seem to be being followed. I have a project with 2 dependencies:
* InternalPackage 1.0 (depends on dbup-core >= 4.1.0, dbup-sqlserver >= 4.1.0)
* [dbup](https://www.nuget.org/packages/dbup/4.5.0) 4.5.0 (depends on dbup-sqlserver >= 4.5.0 which in turn depends on dbup-core >= 4.5.0)

Because of nearest wins, **I would expect to resolve dbup-core 4.1.0**, since the ask for that version is nearer to the application than the request for dbup-core 4.5.0 which is 2 levels deep. **However, packages.lock.json shows that we are resolving dbup-core 4.5.0**. Is this unexpected or am I misunderstanding how this rule is supposed to work?

**Comment by nkolev92** [comment]
Hey @madelson 

The documentation is misleading. We have a similar complaint here, https://github.com/NuGet/docs.microsoft.com-nuget/issues/2434, that includes some more details. 

Nearest wins is written in a way that it honors a user's intention, so you'd only get a downgrade if someone explicitly downgrade  in a particular subgraph.

In this case, the 4.50 selection is what I would expect.

**Comment by madelson** [comment]
@nkolev92 very interesting. Is it true that:

> "Nearest wins" rule is applied only on direct dependencies (aka. top level packages)

The documentation has an example under the nearest wins section that would suggest otherwise ("because Package C 2.0 is used, NuGet ignores any branches in the graph that refer to an older version of Package C").
