### ISSUE TITLE
Is it possible to create build/tool only package without NuSpec file creation right from csproj/fsproj

### ISSUE THREAD

**Issue by xperiandri** [NuGet/Home#10943]
NuGet product used (MSBuild.exe | dotnet.exe msbuild):
Product version: 16

I need to create a build package. It is an F# source code geenrator.
So we successfully created MSBuild task that works both for MSBuild and MSBuild Core.
Now I want it to be packaged into a NuGet package.
But can I produce the empty `lib` folder in NuGet package via `pack` command without `NuSpec` file from `fsproj` file only?
Only required dlls must be packaged into `build\$(Configuration)\$(TargetFramework)` folders. I achieved that by custom target according to sample
https://github.com/madskristensen/BundlerMinifier/blob/e66ec7c85ad6c291fcd5bf55e7f426485e2e2d38/src/BundlerMinifier/BundlerMinifier.csproj#L35-L47
Is there a better way?

And now I need to make my `lib` folder empty. How to do that?

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/4254. 

The NuGet pack SDK is tied to MSBuild, there's no way to invoke it without an MSBuild file.
