### ISSUE TITLE
Updated local package is not consumed

### ISSUE THREAD

**Issue by taoyouh** [NuGet/Home#10942]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): dotnet.exe

Product version: 5.0.202

Worked before? If so, with which NuGet version: no

## Repro steps and/or sample project

1. A .NET Standard project generates a nuget package A. It packs some runtime assets like this:
```
  <ItemGroup>
    <Content Include="SomePath/*">
      <PackagePath>runtimes/win-x64/native/%(Filename)%(Extension)</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>
```

2. A .NET 5 project B consumes that nuget package A using a local source:
```
  <PropertyGroup>
    <RestoreSources>../A/bin/$(Configuration);$(RestoreSources)</RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="A" Version="1.0.0" />
  </ItemGroup>
```
    
3. A is changed and the package is re-generated (using `dotnet pack`)
4. Build project B and it does not consume the latest package and keep using the old assets.

As using nuget package seems to be the only way to add rid-specific native runtime assets to a .NET Core project, doing this is required to debug a .NET Core library with native runtimes. However, this behavior makes it necessary to delete the package cache whenever I change the package A, which makes debugging very complicated.

I think there should be an easier way to add rid-specific native runtime assets to .NET Core project or reference a local (volatile) nuget package.

### Verbose Logs

The log of building B:
[log.txt](https://github.com/NuGet/Home/files/6644059/log.txt)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6579. 

Please refer to https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process for the current behavior.

**Comment by gioce90** [comment]
@taoyouh Maybe you can be interested on [NuJet](https://github.com/gioce90/NuJet). It enhance the inner-loop development and testing process for NuGet packages, especially in local.
