### ISSUE TITLE
Unable to restore packages targetting net5.0 using dotnet

### ISSUE THREAD

**Issue by Hejle** [NuGet/Home#10954]
## Details about Problem

I am unable to restore dependencies like "Microsoft.NET.Test.Sdk", "MSTest.TestAdapter", "MSTest.TestFramework", "coverlet.collector", "NUnit", "NUnit3TestAdapter", "Newtonsoft.Json". I have tried to use dotnet version 5.0.202 and 5.0.301, as well as testing on two different PC's.

It seems like I am unable to restore any dependency targeting net5.0.

I am using a mix of vscode and terminal, meaning I do not have visual studio installed
I am running on Windows Pro 19042.1052

NuGet product used dotnet.exe
Product version: 5.0.301 (and 5.0.202)

I have not seen it work on either of my computers. But I can restore other  I have not seen it work

## Repro steps and/or sample project

To replicate I use "dotnet new mstest" which fails its dotnet restore. Running dotnet restore manually afterwards does not change anything.

### Verbose Logs

```
dotnet new mstest -o mytest
Getting ready...
The template "Unit Test Project" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on mytest\mytest.csproj...
  Determining projects to restore...
C:\Users\hejle\Projects\mytest\mytest.csproj : error NU1100: Unable to resolve 'Microsoft.NET.Test.Sdk (>= 16.7.1)' for 'net5.0'.
C:\Users\hejle\Projects\mytest\mytest.csproj : error NU1100: Unable to resolve 'MSTest.TestAdapter (>= 2.1.1)' for 'net5.0'.
C:\Users\hejle\Projects\mytest\mytest.csproj : error NU1100: Unable to resolve 'MSTest.TestFramework (>= 2.1.1)' for 'net5.0'.
C:\Users\hejle\Projects\mytest\mytest.csproj : error NU1100: Unable to resolve 'coverlet.collector (>= 1.3.0)' for 'net5.0'.
  Failed to restore C:\Users\hejle\Projects\mytest\mytest.csproj (in 62 ms).
Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'
```

**Comment by nkolev92** [comment]
Hey @Hejle 

I attempted a repro, and it seems to work on my end. 
Can you please zip up the project created with all the intermediates and attach it here?
Thanks!

**Comment by Hejle** [comment]
Of course! Here it is :)

I have tried on a third computer, where it worked. I think the difference is whether I have Visual Studio installed or not, though I am obviously not sure. :)

[mytest.zip](https://github.com/NuGet/Home/files/6678773/mytest.zip)

**Comment by nkolev92** [comment]
Hmm..seems like there's no sources whatsoever.

And you mentioned a restore doesn't succeed either?

Can you take a look at your config in `%AppData%\NuGet\NuGet.Config` and see if it has anything in it?

**Comment by Hejle** [comment]
This is the content of my NuGet.config file and the config file is the only thing in my nuget folder.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration />
```

(And thats the same case for my second computer)

**Comment by nkolev92** [comment]
@Hejle 

Do you use chocolatey on those machines?

**Comment by Hejle** [comment]
Yes, I do

**Comment by Hejle** [comment]
And it seems like deleting the Nuget.Config and rerunning dotnet restore fixes the problem as a new config-file is generated with the following content.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

**Comment by Hejle** [comment]
It looks like the issue has been fixed here: https://github.com/chocolatey/nuget-chocolatey/issues/23.

Thanks for the help!

**Comment by nkolev92** [comment]
Ah, seems like you're hitting a chocolatey issue where an empty config file is created: https://github.com/chocolatey/choco/issues/2233., https://github.com/chocolatey/nuget-chocolatey/issues/23.

**Comment by nkolev92** [comment]
Ah, you beat me to it :D Glad we figured it out @Hejle

**Comment by Hejle** [comment]
Yep, just barely :D
Again, thanks for the help @nkolev92
