### ISSUE TITLE
[projectname].nuget.targets should use $(UserProfile) instead of hard-coded path

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1095]
I observe that when using project.json for packages that include MSBuild imports, a [projectname].nugget.targets file is created. This file hard-codes the path to my home directory:

    <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
      <NuGetPackageRoot>C:\Users\andrew\.nuget\packages\</NuGetPackageRoot>
    </PropertyGroup>

This makes the project now unshareable with others on the same machine. If instead, NuGet Restore created the file using the `$(UserProfile)` macro:

    <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
      <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    </PropertyGroup>

Then it would work appropriately for all users of the machine.

**Comment by yishaigalatzer** [comment]
The fix should go in this code - https://github.com/NuGet/NuGet3/blob/89b2ffca6ebe2dec5c2db7e0a6b8dc0d94285d2a/src/NuGet.Commands/MSBuildRestoreResult.cs#L128

**Comment by agocke** [comment]
:+1: We would also like this. We're currently not running restore on Linux and Mac for Roslyn due to Mono issues, so if this were user-agnostic we could check this file in and reference it from everywhere.
