### ISSUE TITLE
NuGet Restore fails on Raspberry PI on NativeAOT repo

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#10968]
While I was waiting for ComWrappers in main repo, I decide to build [NativeAOT](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT) on Raspberry hoping that I can found bug or two here.
Unfortunately I see that build stops at very beginning of the build, during "restore projects..." 
```
Target "Restore: (TargetId:38)" in file "/home/pi/runtimelab/.dotnet/sdk/6.0.100-preview.4.21255.9/NuGet.RestoreEx.targets" from project "/home/pi/runtimelab/Build.proj" (entry point):
```

After some time, memory usage on Pi eat whole 1Gb and start swapping.

Here my path trying to understand problem.
Initial task is here.
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/RestoreTaskEx.cs

This in itself seems to be invokes `dotnet NuGet.Build.Tasks.Console.dll CleanupAssetsForUnsupportedProjects=True;Recursive=True XXXX` 

Based on limited analysis this is somewhere in the https://github.com/NuGet/NuGet.Client/blob/702e250d000fd0956688fcd11d3df375a8443f43/src/NuGet.Core/NuGet.Build.Tasks/BuildTasksUtility.cs#L248

I would like to be educated how I can debug this kind of scenario to give more information how I can lessen memory pressure during restore process. Preferably without building Nuget itself, but can do that if needed.

**Comment by zivkan** [comment]
@kant2002 sorry about the slow response.

[`dotnet restore` has an option](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x#options) (see also `dotnet restore --help`) `--disable-parallel`, which will disable restore multiple projects in parallel. This will lessen memory load.

**Comment by kant2002** [comment]
I run `./build.sh -restore /p:RestoreDisableParallel=true` and validate that `RestoreTaskEx` receive `DisableParallel` as `true`, and issue still persists.

**Comment by kant2002** [comment]
I suspect that this is due to fact that `src/libraries` has 235 projects and it require much more memory then available. Assume at least 4Mb per project.

`./build.sh libs -rc Debug -lc Release  /p:RestoreDisableParallel=true` stuck
`./build.sh nativeaot -rc Debug -lc Release  /p:RestoreDisableParallel=true` works

**Comment by zkat** [comment]
Here's the list of officially supported development platforms for net5.0: https://github.com/dotnet/core/blob/main/release-notes/5.0/5.0-supported-os.md

Unfortunately, raspberry pi isn't an officially supported development platform. As such, I'm going to close this. Thanks for taking the time to file it and having a discussion with us!
