### ISSUE TITLE
[Bug Bash] Installing package which has no dependencies into iOS (Xamarin) project will trigger confused warnings

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#10960]
## Details about Problem
VS Version: Main\31421.281
NuGet Version: Dev\6.0.0.124
OS Version: Windows-10-Enterprise-21H1

## Repro steps
1. Launch VS and click “Create a new project” button in the G2C dialog.
2. Search for iOS (Xamarin) template and create a project (e.g. iPad Blank).
3. Open the PM UI of the project and install package “CrossBase.CodeGeneration” (which has no dependencies).
4. Build the solution and observe the warnings in the Error List window.

## Expected
No confused warning showed since the package has no dependences—that means VS didn’t tell people that they need any additional package before installing.

## Actual
There are confused warnings (could not locate the assembly “EnvDTE”/”EnvDTE80”) showing as below.
![image](https://user-images.githubusercontent.com/20632625/122900296-23364a80-d37f-11eb-8a6e-7b78c71c673b.png)

## Note:
It seems not a regression bug since it repro on D16.8\30420.98 with implicit NuGet 5.8.0.6776.

**Comment by nkolev92** [comment]
Hey @v-luzh 

There's nothing out of the ordinary here. 

The warnings are coming because the package itself is referencing, but those are not framework assemblies. 

```xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="EnvDTE" targetFramework="" />
      <frameworkAssembly assemblyName="EnvDTE80" targetFramework="" />
    </frameworkAssemblies>
```
