### ISSUE TITLE
monoandroid fallback logic for net6-android not working

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/Home#10965]
dotnet version: 6.0.100-preview.5.21302.13

Example project:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-android</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
   <PackageReference Include="System.Json" Version="4.7.1" />
  </ItemGroup>

</Project>
```

This should be pulling in `lib/monoandroid10/_._` with the fallback rules, however it's pulling in `lib/netstandard2.0/System.Json.dll`

Here's what I see in project.assets.json, note how the `imports` stops at `monoandroid50` instead of going back to `monoandroid10`
```
    "frameworks": {
      "net6.0-android30.0": {
        "targetAlias": "net6.0-android",
        "dependencies": {
          "System.Json": {
            "target": "Package",
            "version": "[4.7.1, )"
          }
        },
        "imports": [
          "net6.0-android30.0",
          "monoandroid12.0",
          "monoandroid11.0",
          "monoandroid10.0",
          "monoandroid90",
          "monoandroid81",
          "monoandroid80",
          "monoandroid70",
          "monoandroid60",
          "monoandroid50"
        ],
```

/cc @zkat

**Comment by akoeplinger** [comment]
It works for `net6.0-ios`, i.e. it pulls in `ref/xamarinios10/_._` with this `imports` section:

```
    "frameworks": {
      "net6.0-ios13.6": {
        "targetAlias": "net6.0-ios",
        "dependencies": {
          "System.Json": {
            "target": "Package",
            "version": "[4.7.1, )"
          }
        },
        "imports": [
          "net461",
          "net462",
          "net47",
          "net471",
          "net472",
          "net48"
        ],
```

**Comment by zkat** [comment]
this is so strange. Why wouldn't `monoandroid10` be there? I didn't mess with version stuff beyond checking the .net version itself. 🤔💭

**Comment by akoeplinger** [comment]
Ah, this is because Xamarin.Android has some custom workaround code that adds these fallback items: https://github.com/xamarin/xamarin-android/blob/7e9f595f23ebd5b53385b16e3890bc90f95f6fef/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/targets/Microsoft.Android.Sdk.NuGet.targets#L21-L37

If I remove that workaround then it behaves as expected, sorry for the noise!

**Comment by zkat** [comment]
Glad I could be of help! 😂
