### ISSUE TITLE
An error “Could not install package ‘afine 15.1.5’” occurs when installing deprecated package “afine” with Packages.config format into C# Class Library (.Net Framework) project

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#10979]
## Details about Problem
VS Version: Main\31429.199
NuGet Version: Dev\6.0.0.133
OS Version: Windows-10-Enterprise-21H1
## Installations
1. Install VS Main\31429.199 from:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4927364&view=ms.vss-releaseManagement-web.deployments-tab
2. Install NuGet Client Dev\6.0.0.133 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4929063&view=artifacts&pathAsName=false&type=publishedArtifacts
## Repro steps 
1. Create a new C# Class Library (.Net Framework) project and open PM UI.
2. Add a deprecated package source https://apidev.nugettest.org/v3-index/index.json.
3. Search “afine” deprecated package in Browse tab.
4. Install “afine” package with “packages.config” format.
## Expected
The package can be install successfully.
## Actual
An error “Could not install package ‘afine 15.1.5’” occurs when installing the package as below screenshot. 
![image](https://user-images.githubusercontent.com/40230425/123940646-f3fd8a00-d9cb-11eb-8590-c6f3b0fdbb7f.png)
## Notes
1. The issue does not repro on C# Console App (.Net Core) project.
2. The issue does not repro on installing package with “Package Reference” format.
3. The similar Deprecated package ‘’Afine.Symbols” can be install successfully with "Packages.config" format.
4. It is not a regression since it also repros on D16.8\30420.98 with implicit NuGet Client Dev\5.8.0.6776.

**Comment by kartheekp-ms** [comment]
I can reproduce this issue. It looks for packages.config style project the exception is thrown here.

https://github.com/NuGet/NuGet.Client/blob/77e1bdb266093fd1eafff90ef21ad55a2a448889/src/NuGet.Core/NuGet.PackageManagement/Projects/MSBuildNuGetProject.cs#L259-L267 and we have few tests validating this behavior in https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.Tests/NuGet.PackageManagement.Test/ProjectManagement/MSBuildNuGetProjectTests.cs (search for `You are trying to install this package into a project that targets` string in the tests code).

I am unsure if this is by design or a bug in package reference logic.

**Comment by aortiz-msft** [comment]
@nkolev92 - Would you mind taking a look?

**Comment by aortiz-msft** [comment]
@v-longmin, @v-luzh - Does this work on 16.11. If yes, does this work on the implicit NuGet in VS Main?

**Comment by nkolev92** [comment]
I don't believe there's a product issue here, as the failures are a consequence of package authoring.

The package is authored in a way that it's not following any nuget conventions. 

* packages.config enforces a convention where things such as meta packages need more careful crafting. 
* PackageReference is more permissive for packages that *do not follow any convention*, https://github.com/NuGet/NuGet.Client/blob/77e1bdb266093fd1eafff90ef21ad55a2a448889/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L332-L340. This has historically allowed meta packages to be installed in PackageReference projects.
