### ISSUE TITLE
NU3008 Package integrity errors on restore

### ISSUE THREAD

**Issue by skunjachen** [NuGet/Home#10973]
## Details about Problem

NuGet product used (NuGet.exe | Visual Studio | MSBuild.exe | dotnet.exe): Visual Studio 2019 Enterprise, dotnet.exe

Product version:  5.9.1.11

Worked before? If so, with which NuGet version: No, this is a fresh install of Visual Studio on Windows 2016 Datacenter edition

## Repro steps and/or sample project
1. Installed Visual Studio, and just created a blank  xUnit Test project.
2. Unable to build because of restore errors. Unable to restore multiple packages. They are failing with error NU3008 (similar to error below)

> API.Tests.csproj : error NU3008: Package 'System.IO 4.3.0' from source 'https://api.nuget.org/v3/index.json': The package integrity check failed. The package has changed since it was signed. Try clearing the local http-cache and run nuget operation again. [D:\Portal.net.sln]
>   Package 'System.IO 4.3.0' from source 'https://api.nuget.org/v3/index.json':
>   Signature type: Repository
>   Package 'System.IO 4.3.0' from source 'https://api.nuget.org/v3/index.json':   Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
>   Package 'System.IO 4.3.0' from source 'https://api.nuget.org/v3/index.json':   SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
>   Package 'System.IO 4.3.0' from source 'https://api.nuget.org/v3/index.json':   Valid from: 4/9/2018 8:00:00 PM to 4/14/2021 8:00:00 AM

CSProj file content

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```
Nuget.config content:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<config>
    <add key="globalPackagesFolder" value="d:\nuget\packages" />
</config>

  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

### Verbose Logs

[nuget-restore.log](https://github.com/NuGet/Home/files/6718450/nuget-restore.log)

**Comment by zkat** [comment]
@skunjachen did you try to follow the advice in the error message already?

> Try clearing the local http-cache and run nuget operation again.

**Comment by kartheekp-ms** [comment]
I cleared my local cache and followed the repro steps. I am unable to reproduce the issue.

**Comment by skunjachen** [comment]
Yes, I have performed all the steps suggested as suggested in: https://stackoverflow.com/questions/64280574/nuget-returns-package-integrity-checks-on-freshly-downloaded-packages including reinstalling visual studio. The trace attached is after all the steps.

For what its worth, I am doing this on an AWS Workspaces desktop. I suspect that there may be some interference from that system. I have had to specify "ignore ssl" parameters when using git or yarn to bypass a self signed certificate error.

**Comment by kartheekp-ms** [comment]
> I am doing this on an AWS Workspaces desktop. I suspect that there may be some interference from that system.

Interesting part here is bunch of packages were installed successfully and few of them failed with NU3008 error.

```
Installed runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 from https://api.nuget.org/v3/index.json with content hash NS1U+700m4KFRHR5o4vo9DSlTmlCKu/u7dtE5sUHVIPB+xpXxYQvgBgA6wEIeCz6Yfn0Z52/72WYsToCEPJnrw==.

Installed System.Threading.Tasks 4.0.11 from C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\ with content hash k1S4Gc6IGwtHGT8188RSeGaX86Qw/wnrgNLshJvsdNUOPP9etMmo8S07c+UlOAx4K/xLuN9ivA1bD0LVurtIxQ==.
.....
```

In the issue description you have mentioned that `System.IO 4.3.0` package integrity check failed but the `restore log` says `PackageSignatureVerificationLog: PackageIdentity: System.IO.4.3.0 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: True` which means signature validation succeeded. 

Are you experiencing different packages failing integrity checks every time you execute restore?

Please try [`dotnet restore <path to sln file or project>`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore) command and let us know if you are experiencing the same issue.

**Comment by zkat** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue.

Please feel free to comment or open a new issue if needed.
