### ISSUE TITLE
Get vulnerability information from registration API in PMUI

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#10984]

**Comment by dominoFire** [comment]
@jebriede Will I be impacted by https://github.com/NuGet/Home/issues/10865 ?

**Comment by dominoFire** [comment]
IPackageSearchMetadata has some metadata info in it. I think that would work?

https://github.com/NuGet/NuGet.Client/blob/3feb16f44495cfaca4113afea709ee57e4341314/src/NuGet.Core/NuGet.Protocol/Model/IPackageSearchMetadata.cs#L62

**Comment by jebriede** [comment]
@dominoFire https://github.com/NuGet/Home/issues/10865 should not impact this work. That issue is already present and will handled separately.
