### ISSUE TITLE
Package manager wants to check all configured sources on install

### ISSUE THREAD

**Issue by asherber** [NuGet/Home#1099]
Using VS2015 RTM, NuGet 3.1.60724.766. 

In addition to the nuget.org package source, I have another package source configured which lives on my company's LAN and which is only accessible when I am on site or connected via VPN.

Working remotely and not on my VPN, I searched for and located a NuGet package on nuget.org, using the GUI package manager. When I clicked Install, I got the following:

```
Attempting to gather dependencies information for package 'FooBar' with respect to project 'Baz', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'FooBar' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FooBar'
Resolved actions to install package 'FooBar'
An error occurred while loading packages from 'http://my.nuget.server': The remote name could not be resolved: 'my.nuget.server'
========== Finished ==========
```
It appears the the package manager is attempting to contact my NuGet server, even though the package itself has already been located on nuget.org. Since I'm not on the VPN, this fails, causing the install to fail.

The package manager console does not have this problem; running `install-package FooBar` while not on the VPN works as expected.

**Comment by emgarten** [comment]
@asherber which source do you have selected in the power shell console source drop down? 

NuGet should fail when the selected source has errors, but errors from secondary sources will be ignored.

**Comment by asherber** [comment]
I have nuget.org selected. Oddly, this is only happening on one of my two machines, which are configured as similarly as they can be (both Win7, VS2015 installed on the same day, same list of extensions, same VPN setup).

**Comment by asherber** [comment]
Okay, I've located a salient difference and gotten this down to something reproducible. On machine A, where installing from the package manager UI does work, the configured package sources are nuget.org followed by my company's server. On machine B, where installing from the UI does not work, my company's server is listed first, followed by nuget.org. If I switch the order of the servers in preferences, then installing from the UI does work.

Note that the package manager console works on both machines, regardless of the order of the servers in preferences.

Note also that when the error occurs on machine B, the UI has already located the package on nuget.org and has at least downloaded metadata from there. But then for some reason it attempts to download the actual package from the server listed first in preferences, even though nuget.org is selected in the Package Source dropdown.

**Comment by yishaigalatzer** [comment]
@asherber thanks for the report, we will take a stab at fixing it. This doesn't seem to be a major blocking issue so I'm moving to 3.2 (around Update I timeframe) if you disagree, please let me know.

**Comment by asherber** [comment]
Thanks, I agree. I suspect that this won't bite many users, and there are two reasonable workarounds (reorder servers, or use the console).
