### ISSUE TITLE
Prerelease nuget packages not showing in Nuget -> Updates

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#10990]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prerelease-nuget-packages-not-showing-in/1462264)._

---
[severity:It's more difficult to complete my work]
I am using Microsoft Visual Studio Enterprise 2019 Version 16.10.2 on Windows 10.

I notice that pre-release nuget packages show when I Browse them with the Include Prerelease checkbox checked.  They also show as 'Prerelease' (the small text below the icon).

However, when I switch to the Updates tab of the Nuget manager, it shows "No packages found" no matter how many times I uncheck/recheck the Prerelease checkbox or click the little refresh arrow.

I note that updates show correctly when they are NOT pre-release.

The nugets are custom and generated from a .net core 3.1 solution.
The nuget-using code is also a .net core 3.1 solution.

I also note that using Package Manager to run "Update-Package Oscar2SF.Common -IncludePrerelease" does not find anything.

My nuget versions are of the form "1.2.345-dev".
They are hosted in github packages in an enterprise org.  

Like I say, there's no problems getting/installing them.  Just that VS 2019 wont let me update them when they are pre-release.

---
#### Feedback Bot on 6/28/2021, 06:26 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Ian Randell on 7/1/2021, 03:46 AM: 

<p>VS 2019 v16.10.3 is also exhibiting this behavior for me.</p>
<p>HOWEVER, its possible this behavior is down to a proxy caching issue - I am on a corporate network behind proxies.</p>
<p>I’d be grateful if someone who is not could confirm whether this behavior occurs for them.</p>

---
### Original Solutions
(no solutions)

**Comment by kartheekp-ms** [comment]
I moved this issue to GitHub by mistake. I will work with the customer in VS Feedback channel.
