### ISSUE TITLE
Ensure the namespaces filtering is respected in packages.config package installation/updates IVs installer API

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11002]
In PR, restore and package installation are equivalent. 
In PC they are not. 

This task covers ensuring that the namespaces are respected during package installation. 

*Detailed explanation:*

* In https://github.com/NuGet/Home/issues/10823, support for namespaces filtering was added in restore. 
* This issue ensures that commands run through:
    * Any IVs installer APIs.

Below is clarification from @zivkan 

Our [NuGet extensibility in Visual Studio docs](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio) detail our `IVs*` APIs. Also see [the interface definitions](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility), particularly [`IVsPackageInstaller.cs`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility/IVsPackageInstaller.cs) (and `IVsPackageInstaller2`).

Roslyn use it when you have two projects in the solution, one of them use a package, and the other does not. When you write code in the project that does not use the package, Roslyn will give you a lightbulb fix to install the package into the project.

Another way to test it is via our [API testing extension](https://github.com/NuGet/Entropy/tree/main/IVsTestingExtension)

**Comment by nkolev92** [comment]
@erdembayar we don't really use half days in estimates. 

Can you please not adjust the estimates? It messes with the tracking in https://github.com/NuGet/Client.Engineering/issues/1026.
