### ISSUE TITLE
Document which VS extensibility APIs can be called from a background thread

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11021]
We should improve docs so callers know which APIs can be called on a background thread, since general VS/VS-threading guidance is that all non-async APIs must be called on the UI thread.

This change adds XMLDoc that Intellisense will show.

Updating docs.microsoft.com is tracked by this issue: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2513

**Comment by AArnott** [comment]
> since general VS/VS-threading guidance is that all non-async APIs must be called on the UI thread.

I wouldn't say that. I'd say all `IVs` interfaces should be assumed to have thread-affinity if no docs address the question.
A great place to document which APIs have thread-affinity vs. not would probably be [in this file](https://github.com/microsoft/VSSDK-Analyzers/blob/main/src/Microsoft.VisualStudio.SDK.Analyzers.CodeFixes/build/AdditionalFiles/vs-threading.MembersRequiringMainThread.txt) which allows the vs-threading analyzers to call out when users call main thread APIs without switching first.

**Comment by aortiz-msft** [comment]
@zivkan - Would you please address this sprint as part of QW?

**Comment by CyrusNajmabadi** [comment]
@zivkan Can this be worked on soon?  This is currently blocking: https://github.com/dotnet/roslyn/pull/55671

**Comment by zivkan** [comment]
I started this morning, but I'm OOF next week, so I'm not sure when I'll get a PR ready. Hopefully I don't have too many more interruptions today, but I do have at least one meeting.

**Comment by zivkan** [comment]
PR has been created to update the XMLDoc: https://github.com/NuGet/NuGet.Client/pull/4209

I couldn't find any API we provide in VS that clearly must be called on the UI thread, so I won't be adding/updating any vs-threading analyzer additional file.
