### ISSUE TITLE
[Feature]: Address all the package installation rules for package namespaces work in PackageReference and PackageDownload scenarios.

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11035]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### The Elevator Pitch

[The package installation rules](https://github.com/NuGet/Home/blob/dev/proposed/2021/PackageNamespaces.md#package-installation-rules) in the package namespaces spec has rule: `When a package id needs to be downloaded, it is first compared against sources with namespaces. If any match, only those sources are used. If none of the namespaces match, then the sources without namespaces are considered, if any. ` The second half of the requirement i.e. `If none of the namespaces match, then the sources without namespaces are considered` is not addressed in https://github.com/NuGet/NuGet.Client/pull/4149 PR. Hence created this follow-up issue to make sure all the package installation rules are handled as per the spec.

**Comment by nkolev92** [comment]
This one is irrelevant right now, as the default is `FullySpecified`. 

Feel free to reopen if otherwise @kartheekp-ms
