### ISSUE TITLE
[Bug]: Wrong package suggested for SqlConnection/SqlCommand

### ISSUE THREAD

**Issue by ErikEJ** [NuGet/Home#11030]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

5.9

### Impact

It's more difficult to complete my work

### Repro Steps & Context

VS package suggestions: should suggest Microsoft.Data.SqlClient instead of System.Data.SqlClient

**Comment by heng-liu** [comment]
Hi @ErikEJ , I notice you're a contributor of the package. May I know the relationship between the two packages? Is one renamed to another one? Thanks!

**Comment by ErikEJ** [comment]
@heng-liu Both packages are owned by the Microsoft SQL Server team, S.D.S. is part of .NET Core/.NET Framework runtime, and will not receive any new features, M.D.S. ships out of band with .NET, and is the de-facto SqlClient for .NET, and should be used for any new development. So suggesting S.D.S. is wrong.

/cc @cheenamalhotra @vickyharp

**Comment by heng-liu** [comment]
Hi @loic-sharma, do you know if it's related to the work mentioned here? https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28%5BDeprecated%5D%20Specs%20%28in%20progress%5C%29.one%7C910181C5-8695-4A1C-9792-A56DBB86F1C3%2FEngineering%20Design%7CD4F8A54A-BAB4-4F07-A495-E136135CAF48%2F%29
onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/%5bDeprecated%5d%20Specs%20(in%20progress).one#Engineering%20Design&section-id={910181C5-8695-4A1C-9792-A56DBB86F1C3}&page-id={D4F8A54A-BAB4-4F07-A495-E136135CAF48}&object-id={B915BE59-CAC1-0F8E-0790-099D306A17DB}&E8

**Comment by loic-sharma** [comment]
Hello, the work to fix this is tracked by: https://github.com/dotnet/roslyn/issues/53736
