### ISSUE TITLE
Including an empty folder in nupsec

### ISSUE THREAD

**Issue by ellismg** [NuGet/Home#1104]
I would like to author a nuspec which includes a empty ref\dotnet directory (i.e. the produced nupkg has a ref\dotnet folder with the _._ 0 byte file in it).

I have tried a bunch of different ways to do this, for example:

```
<file src="empty\" target="ref\dotnet" exclude="" />
<file src="empty\_._" target="ref\dotnet" exclude="" />
<file src="empty\*" target="ref\dotnet" exclude="" />
<file src="empty\**\*" target="ref\dotnet" exclude="" />
```

If I mention this _._ file name explicitly, then I get an error saying the file does not exist (even though it is present and in the correct location).  Otherwise, the package is built, but the ref\dotnet directory is not present.

This is with NuGet 3.1.0.0

**Comment by yishaigalatzer** [comment]
When you say NuGet 3.1 - Do you mean nuget.exe 3.1?

In NuGet V2 you needed to pass `-ExcludeEmptyDirectories`

We can verify this scenario with NuGet 3.1 command line

**Comment by ellismg** [comment]
I was using http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe.  The problem was I did not realize I needed to pass `-ExcludeEmptyDirectories` since I wanted to have an empty directory!  If I pass that, then things work as expected.

Thanks for the pointer!

**Comment by yishaigalatzer** [comment]
Reopening to investigate why we have to pass `-ExcluseEmptyDirectories` here, it is unexpected and counter intuitive. Lets see if we can come up with a fix for the RTM version.

@ellismg glad you are not blocked.

**Comment by agocke** [comment]
@ellismg What did you do here? This is not working for me either.

**Comment by yishaigalatzer** [comment]
> I was using http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe. The problem was I did not realize I needed to pass  -ExcludeEmptyDirectories  since I wanted to have an empty directory! If I pass that, then things work as expected.

**Comment by agocke** [comment]
@yishaigalatzer Matt describes 4 different mutually exclusive implementations. Which worked?

**Comment by agocke** [comment]
@yishaigalatzer I guess I should also ask -- what _should_ be working here?

**Comment by ellismg** [comment]
IIRC, I did `<file src="empty\_._" target="ref\dotnet" exclude="" />` in the nuspec and passed `-ExcludeEmptyFolders` to nuget.

**Comment by yishaigalatzer** [comment]
the work here is to clearly define how to pack an empty directory (including doc PR and/or bug fix if necessary)

**Comment by emgarten** [comment]
NuGet/NuGet2@23a4429a399183a9dbc5623000098cafbc34d080

Only known folders are allowed to add `_._` at pack time. The fix I've made adds support for the new v3 folders to this list: ref, runtimes, native, contentFiles.

From trying out some of these scenarios I found that just having an empty folder is enough. The folder does not need to have a `_._` file, nuget.exe will add this on it's own. In some cases having a `_._` file or specifying `_._` in the src attribute would cause it to fail. NuGet treats `_._` as an internal implementation detail and it does not expect it to be there already when creating a package.

**Comment by dipsindol** [comment]
I was able to successfully add an empty folder using one piece of documentation on nuget 

![image](https://cloud.githubusercontent.com/assets/975248/16205679/b785e710-36d9-11e6-8b22-c623ef9bd603.png)

Now, the problem is upon install the empty folders are not being added to the project on which I am installing this package.   Any one has thoughts on how I can instruct the Nuget to not ignore empty folders while adding content folders and files to the project on which I am installing the package.

**Comment by ps2goat** [comment]
I thought the clarification needed meant the flag needed to be changed from `-ExcludeEmptyDirectories` to `-IncludeEmptyDirectories`.  Was the ability to have empty directories removed completely?
