### ISSUE TITLE
[Bug]:  Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json

### ISSUE THREAD

**Issue by YGeneral** [NuGet/Home#11056]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

dotnet5

### Worked before?

.net core 3.1

### Impact

I'm unable to use this version

### Repro Steps & Context

PS D:\Project\gitlab\PoJun.SingleSignOn\source> docker-compose build

### Verbose Logs

```shell
`[+] Building 7.9s (32/37)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:5.0                                                  0.4s
 => [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:5.0                                               0.4s
 => [build  1/27] FROM mcr.microsoft.com/dotnet/sdk:5.0@sha256:970a387bcf836c492ed631b3d9c9dbe484f9f32e7a2f9e9428  0.0s
 => [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:5.0@sha256:fef256e9a022b22836ed0e52e31191ea3e5d8d9f88a0d35d71  0.0s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 232.47kB                                                                              0.2s
 => CACHED [base 2/2] WORKDIR /app                                                                                 0.0s
 => CACHED [final 1/2] WORKDIR /app                                                                                0.0s
 => CACHED [build  2/27] WORKDIR /src                                                                              0.0s
 => [build  3/27] COPY [/nuget.config, /]                                                                          0.0s
 => [build  4/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.cspro  0.0s
 => [build  5/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Entity/PoJun.SingleSignOn.Entity.cs  0.1s
 => [build  6/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Enum/PoJun.SingleSignOn.Enum.csproj  0.0s
 => [build  7/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.MongoDBRepository/PoJun.SingleSign  0.1s
 => [build  8/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Exception/PoJun.SingleSignOn.Except  0.1s
 => [build  9/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Code/PoJun.SingleSignOn.Code.csproj  0.1s
 => [build 10/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.IRepository/PoJun.SingleSignOn.Api  0.1s
 => [build 11/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Repository/PoJun.SingleSignOn.Repos  0.1s
 => [build 12/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.Tools/PoJun.SingleSignOn.Tools.cspr  0.1s
 => [build 13/27] COPY [PoJun.SingleSignOn.Shared/PoJun.SingleSignOn.ContractModel/PoJun.SingleSignOn.Co  0.1s
 => [build 14/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.ContractModel/PoJun.SingleSignOn.A  0.1s
 => [build 15/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.SqlServerRepository/PoJun.SingleSi  0.0s
 => [build 16/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.Service/PoJun.SingleSignOn.Api.Ser  0.1s
 => [build 17/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.IService/PoJun.SingleSignOn.Api.IS  0.1s
 => [build 18/27] COPY [PoJun.SingleSignOn.Framework/PoJun.SingleSignOn.IFramework/PoJun.SingleSignOn.IF  0.1s
 => [build 19/27] COPY [PoJun.SingleSignOn.Framework/PoJun.SingleSignOn.BaseFramework/PoJun.SingleSignOn  0.1s
 => [build 20/27] COPY [PoJun.SingleSignOn.Framework/PoJun.SingleSignOn.LogFramework/PoJun.SingleSignOn.  0.1s
 => [build 21/27] COPY [PoJun.SingleSignOn.API/PoJun.SingleSignOn.Api.MySqlRepository/PoJun.SingleSignOn  0.1s
 => [build 22/27] COPY [PoJun.SingleSignOn.Framework/PoJun.SingleSignOn.SMSFramework/PoJun.SingleSignOn.  0.1s
 => [build 23/27] COPY [PoJun.SingleSignOn.Framework/Ashermed.RightFramework/Ashermed.RightFramework.csproj, A  0.1s
 => ERROR [build 24/27] RUN dotnet restore "PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.Singl  6.0s
------
 > [build 24/27] RUN dotnet restore "PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.csproj" --configfile /nuget.config:
#32 0.961   Determining projects to restore...
#32 0.963   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.HospitalFramework/PoJun.HospitalFramework.csproj" because it was not found.
#32 0.963   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.PersonnelFramework/PoJun.PersonnelFramework.csproj" because it was not found.
#32 0.963   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.SingleSignOnFramework/PoJun.SingleSignOnFramework.csproj" because it was not found.
#32 2.003   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.HospitalFramework/PoJun.HospitalFramework.csproj" because it was not found.
#32 2.003   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.PersonnelFramework/PoJun.PersonnelFramework.csproj" because it was not found.
#32 2.003   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.SingleSignOnFramework/PoJun.SingleSignOnFramework.csproj" because it was not found.
#32 2.113   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.HospitalFramework/PoJun.HospitalFramework.csproj" because it was not found.
#32 2.113   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.PersonnelFramework/PoJun.PersonnelFramework.csproj" because it was not found.
#32 2.113   Skipping project "/src/PoJun.SingleSignOn.Framework/PoJun.SingleSignOnFramework/PoJun.SingleSignOnFramework.csproj" because it was not found.
#32 5.903 /usr/share/dotnet/sdk/5.0.302/NuGet.targets(131,5): error : Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json. [/src/PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.csproj]
#32 5.903 /usr/share/dotnet/sdk/5.0.302/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/src/PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.csproj]
#32 5.903 /usr/share/dotnet/sdk/5.0.302/NuGet.targets(131,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [/src/PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.csproj]
------
executor failed running [/bin/sh -c dotnet restore "PoJun.SingleSignOn.API/PoJun.SingleSignOn.WebApi/PoJun.SingleSignOn.WebApi.csproj" --configfile /nuget.config]: exit code: 1
```

**Comment by zivkan** [comment]
@YGeneral the error message says:

> The SSL connection could not be established, see inner exception. 
> Received an unexpected EOF or 0 bytes from the transport stream.

It appears your docker container is having network issues.

**Comment by saber-wang** [comment]
@zivkan  
Connection reset by peer exception occurred
![image](https://user-images.githubusercontent.com/45062099/126579716-e0333909-2e87-4283-8d0d-0291b45f183d.png)

**Comment by xiatiandegaga** [comment]
since 2021-7-20，mcr.microsoft.com/dotnet/sdk:5.0-alpine    can’t get nuget  

Linux coffee-n4 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 Linux
+ dotnet publish IdentityApi.csproj -c release -f net5.0 -r linux-x64 --self-contained false -o ./temPublish
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/usr/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/var/jenkins_home/workspace/ckend_dev-backend-nan-jing-vanke@2/src/Services/IdentityService/IdentityApi/IdentityApi.csproj]
/usr/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. [/var/jenkins_home/workspace/ckend_dev-backend-nan-jing-vanke@2/src/Services/IdentityService/IdentityApi/IdentityApi.csproj]
/usr/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   Unable to read data from the transport connection: Connection reset by peer. [/var/jenkins_home/workspace/ckend_dev-backend-nan-jing-vanke@2/src/Services/IdentityService/IdentityApi/IdentityApi.csproj]
/usr/share/dotnet/sdk/5.0.103/NuGet.targets(131,5): error :   Connection reset by peer [/var/jenkins_home/workspace/ckend_dev-backend-nan-jing-vanke@2/src/Services/IdentityService/IdentityApi/IdentityApi.csproj]
[Pipeline] }


![image](https://user-images.githubusercontent.com/47713355/126582361-2170e27c-0e14-417b-808d-3914a1691f44.png)

**Comment by sunchi570** [comment]
@zivkan 
 Connection reset by peer.
![image](https://user-images.githubusercontent.com/16114632/126589926-a13d4445-4887-4edc-99b3-e3c8bbc44395.png)

**Comment by YGeneral** [comment]
> @YGeneral the error message says:
> 
> > The SSL connection could not be established, see inner exception.
> > Received an unexpected EOF or 0 bytes from the transport stream.
> 
> It appears your docker container is having network issues.

This problem has occurred since yesterday, and it was normal before

**Comment by YGeneral** [comment]
And the server related software has not been updated recently

**Comment by yaoyuansheng** [comment]
i have the same issue.


tep 36/46 : RUN dotnet restore "host/Magic.Api/Magic.Api.csproj"  --configfile "Nuget.config" -nowarn:msb3202,nu1503
 ---> Running in 04f3f26800cd
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.http/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/jetbrains.annotations/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.ddd.application/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.http/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.localization/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.identity.application.contracts/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.tenantmanagement.application.contracts/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.users.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.permissionmanagement.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.security.cryptography.cng/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.identity.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.fileproviders.embedded/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.settingmanagement.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.permissionmanagement.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.tenantmanagement.application.contracts/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.ddd.application/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/volo.abp.users.domain.shared/index.json'.
  The SSL connection could not be established, see inner exception.
    Unable to read data from the transport connection: Connection reset by peer.
    Connection reset by peer
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error : Failed to retrieve information about 'Microsoft.Extensions.Options' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json'. [/src/host/Magic.Api/Magic.Api.csproj]
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [/src/host/Magic.Api/Magic.Api.csproj]
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   Unable to read data from the transport connection: Connection reset by peer. [/src/host/Magic.Api/Magic.Api.csproj]
/usr/share/dotnet/sdk/3.1.404/NuGet.targets(128,5): error :   Connection reset by peer [/src/host/Magic.Api/Magic.Api.csproj]
The command '/bin/sh -c dotnet restore "host/Magic.Api/Magic.Api.csproj"  --configfile "Nuget.config" -nowarn:msb3202,nu1503' returned a non-zero code: 1
Build step 'Execute shell' marked build as failure

**Comment by xiatiandegaga** [comment]
now it's ok ，it seems nuget‘s network

**Comment by YGeneral** [comment]
> now it's ok ，it seems nuget‘s network
Have you made any changes

**Comment by zivkan** [comment]
If you're using docker, please check if api.nuget.org can be reached on the host machine. I have seen customers report connection issues that only happen in their docker container before, I'm not sure how they expect the NuGet team to investigate or fix.

If the problem is also happening on the host machine, or you're not using docker, please [contact the nuget.org team with the information they request in their FAQ](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nuget.org-not-accessible). This provides them with information to pass onto their CDN provider about the local endpoint depending on your specific geographic region. As you can imagine with any globally distributed CDN, problems can be isolated to one region.

Additionally, the nuget.org FAQ already specifies their preferred contact method, but if you're going to create an issue on github, https://github.com/NuGet/Home/issues/new/choose has an entry specific for nuget.org:

![image](https://user-images.githubusercontent.com/5030577/126646124-55fa182c-4ecb-47dd-ac4d-6fb067028343.png)

Creating an issue in the server team's repository will get you an appropriate response more quickly. But for connection issues, I recommend you follow the FAQ, rather than creating a github issue without sufficient information to contact the CDN provider.

@YGeneral as the author of this issue, are your problems resolved as well, or are you still experiencing connection problems?  If you are, only in docker, or also on the host machine?

**Comment by YGeneral** [comment]
> If you're using docker, please check if api.nuget.org can be reached on the host machine. I have seen customers report connection issues that only happen in their docker container before, I'm not sure how they expect the NuGet team to investigate or fix.
> 
> If the problem is also happening on the host machine, or you're not using docker, please [contact the nuget.org team with the information they request in their FAQ](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nuget.org-not-accessible). This provides them with information to pass onto their CDN provider about the local endpoint depending on your specific geographic region. As you can imagine with any globally distributed CDN, problems can be isolated to one region.
> 
> Additionally, the nuget.org FAQ already specifies their preferred contact method, but if you're going to create an issue on github, https://github.com/NuGet/Home/issues/new/choose has an entry specific for nuget.org:
> 
> ![image](https://user-images.githubusercontent.com/5030577/126646124-55fa182c-4ecb-47dd-ac4d-6fb067028343.png)
> 
> Creating an issue in the server team's repository will get you an appropriate response more quickly. But for connection issues, I recommend you follow the FAQ, rather than creating a github issue without sufficient information to contact the CDN provider.
> 
> @YGeneral as the author of this issue, are your problems resolved as well, or are you still experiencing connection problems? If you are, only in docker, or also on the host machine?

Hello, my problem is when I use Jenkins to publish docker

**Comment by YGeneral** [comment]
It hasn't been solved yet

**Comment by YGeneral** [comment]
> If you're using docker, please check if api.nuget.org can be reached on the host machine. I have seen customers report connection issues that only happen in their docker container before, I'm not sure how they expect the NuGet team to investigate or fix.
> 
> If the problem is also happening on the host machine, or you're not using docker, please [contact the nuget.org team with the information they request in their FAQ](https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nuget.org-not-accessible). This provides them with information to pass onto their CDN provider about the local endpoint depending on your specific geographic region. As you can imagine with any globally distributed CDN, problems can be isolated to one region.
> 
> Additionally, the nuget.org FAQ already specifies their preferred contact method, but if you're going to create an issue on github, https://github.com/NuGet/Home/issues/new/choose has an entry specific for nuget.org:
> 
> ![image](https://user-images.githubusercontent.com/5030577/126646124-55fa182c-4ecb-47dd-ac4d-6fb067028343.png)
> 
> Creating an issue in the server team's repository will get you an appropriate response more quickly. But for connection issues, I recommend you follow the FAQ, rather than creating a github issue without sufficient information to contact the CDN provider.
> 
> @YGeneral as the author of this issue, are your problems resolved as well, or are you still experiencing connection problems? If you are, only in docker, or also on the host machine?

The host can access api.nuget.org

**Comment by zivkan** [comment]
> The host can access api.nuget.org

Perhaps you need to talk to docker support then. If your host machine can talk to api.nuget.org, then there isn't a problem with the nuget client, or nuget CDN. The `Received an unexpected EOF or 0 bytes from the transport stream` and `Connection reset by peer` errors happen at a much lower level than NuGet's code, and is out of our control.

**Comment by YGeneral** [comment]
> > The host can access api.nuget.org
> 
> Perhaps you need to talk to docker support then. If your host machine can talk to api.nuget.org, then there isn't a problem with the nuget client, or nuget CDN. The `Received an unexpected EOF or 0 bytes from the transport stream` and `Connection reset by peer` errors happen at a much lower level than NuGet's code, and is out of our control.

Okay thank you

**Comment by zivkan** [comment]
@YGeneral I just chat with someone who maintains Microsoft's dotnet docker images, and his suggestion is you can also try https://github.com/dotnet/dotnet-docker/discussions

**Comment by YGeneral** [comment]
> @YGeneral I just chat with someone who maintains Microsoft's dotnet docker images, and his suggestion is you can also try https://github.com/dotnet/dotnet-docker/discussions

thank you very much！
