### ISSUE TITLE
[Bug Bash][Suggestion] The “installed” package version showed a version installed into other project in solution-level PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11051]
## Details about Problem
VS Version: Main\31519.82
NuGet Version: Dev\6.0.0.155
OS Version: Windows-10-Enterprise-21H1
## Repro steps
1.Create a solution with multiple C# Console App (.NET Framework 4.8) projects in VS.
2.Right-Click the solution in the Solution Explorer and select the “Mange NuGet Packages for Solution”
3.Go to “Browse” tab and select a package (e.g. Newtonsoft.Json) 
4.Check the first project and install a versions into the first project (e.g. install 12.0.1) in the right penal.
5.Uncheck the first project and check the second project in the right penal.
6.Observe the “Installed” text-box.
## Expected
The “installed” package version should show the package version installed into the selected project (not other project) correctly.
## Actual
The “installed” package version showed a version installed into other project in solution-level PM UI as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/126312993-e418b775-95ba-47ce-8359-a893edec7d76.png)
## Notes:
It is not a regression since it did repro on D16.8\30420.98 with implicit NuGet Client Dev\5.8.0.6776.

**Comment by donnie-msft** [comment]
I believe this is expected. The Installed version in Solution PM UI is indicating the version installed across the entire solution, or it indicates "multiple versions installed" when there are multiple versions. The reason for having checkboxes is to allow multi-selection for actions (install/uninstall/update). Selecting a row is for readability purposes, not for refreshing the state or enabling actions.

If you think this is confusing, then we may need a DCR. Can also see if customers have input on that.
The same behavior happens in Dev 15:
![image](https://user-images.githubusercontent.com/49205731/126368625-e48a9218-30ca-4a58-bc2d-687ab20c03b8.png)

@chgill-MSFT, any input on whether we want a DCR to re-envision the selection/dropdown design here? If so, feel free to reopen it.
The question is whether the Installed dropdown should change based on the highlighted/selected project (ie, "<blank>" in this case).
