### ISSUE TITLE
[Bug Bash] There is a typo in the readme.txt files of package “Castle.Core” 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11050]
## Details about Problem
VS Version: Main\31519.82
NuGet Version: Dev\6.0.0.155
OS Version: Windows-10-Enterprise-21H1
## Repro steps
1.Create a C# Console Application (.NET Core) template via VS.
2.Open the PM UI of the project and install the package Castle.Core (version from “3.0.0.2001” to “4.2.1” in the “version” drop-down list).
3.Observe the auto-opened readme.txt file.
## Expected
No typo in the readme.txt files of package Castle.Core (version from “3.0.0.2001” to “4.2.1”).
## Actual
There is a typo in the readme.txt files of package Castle.Core (version from “3.0.0.2001” to “4.2.1”) as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/126312783-905f758b-4345-464d-8744-68cd39b747e7.png)
## Notes:
1.It start to repro from version “3.0.0.2001” to “4.2.1”.
2.It doesn’t repro on the package version<3.0.0.3001 and the package version>4.2.1.

**Comment by donnie-msft** [comment]
Readme files are content of the NuGet packages that authors create.

In 2018, they fixed this typo in their readme: https://github.com/castleproject/Core/commit/21243431f66723a3d553717e61108b6a8c82be6d#diff-7d3c78f4e03444f21be9fd7a45350893e2bac92a0165aab1afefddb9623d1ebdR7

According to https://www.nuget.org/packages/Castle.Core/ the versions you indicate where it repro are dated before they made this fix.
So, no issue on our side, and it's already resolved in newer version.
(...but anyway, good job spotting it! 🦅 👀)
