### ISSUE TITLE
NuGet 2.8.6 fails to pack PCL libraries with replacement tokens in the nuspec file

### ISSUE THREAD

**Issue by hastarin** [NuGet/Home#1106]
Please apply the fix to the 2.8.x branch!   The bug is still there in 2.8.8 on CodePlex.

https://nuget.codeplex.com/SourceControl/network/forks/StephenCleary/Issue4013/changeset/2803f4895ea678d0b0cfbb5a5e2961ec0dec40f7

https://nuget.codeplex.com/workitem/4013

I'd love to help out with a pull request but can't make head/tail of the current project structure.

**Comment by mikecg** [comment]
I have been struggling with this for two work days thinking that I was using the tool wrong, but it is a bug? Please fix this.

**Comment by yishaigalatzer** [comment]
We have moved away from codeplex, we are now building the command line in the github repos and we are working on command line 3.1.1 at the moment.

The new command line is available here - http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe

Last we are no longer tracking bug in codeplex, please don't file bugs there they go unnoticed. We have no way to turn the bug repo off, but we are not looking there.

**Comment by yishaigalatzer** [comment]
@hastarin can you provide a clear repro for this issue so we can easily verify it?

**Comment by hastarin** [comment]
@yishaigalatzer Sure you can use the following:
https://github.com/hastarin/NuGetPCLRepro

**Comment by SuperJMN** [comment]
This bug is shitting on me. I thought it was already fixed :sad:

**Comment by feiling** [comment]
It turns out that this is by design: token replacement is never supported when you run `nuget pack <nuspec file>`.

We'll update our documentation to make this clear.

**Comment by hastarin** [comment]
Ah so the note in the documentation really does need to be made bold and update the section referring to tokens.

> Once your nuspec is ready, you can run:
>
> nuget pack MyProject.csproj
> Note that you need to run 'nuget pack' on the project file, not the nuspec itself. But the nuspec will in fact get picked up.

**Comment by yishaigalatzer** [comment]
@hastarin FYI (and this is not an ask to do so, just letting you know it is there for you to contribute if you'd like to) our docs our open source as well, and we gladly take contributions.

https://github.com/nuget/nugetdocs/pulls

**Comment by MeniZalzman** [comment]
We still need to update the documentation on this command

**Comment by csharpfritz** [comment]
Added statements clarifying the pack action
