### ISSUE TITLE
Use local project instead of referenced package dependency when version does not start from 0.*

### ISSUE THREAD

**Issue by tarastriska** [NuGet/Home#11077]
### Discussed in https://github.com/NuGet/Home/discussions/11076

<div type='discussions-op-text'>

<sup>Originally posted by **tarastriska** July 23, 2021</sup>
I have my own nuget package **PackageA** that depends on my other package **PackageB** (let say with version >=2.0.1)
Then I have solution with
**MyTestProject** that references **MyOtherTestProject** that references **MyProjectB** (this project produces **PackageB**).
**MyTestProject** references **PackageA**
As result I have runtime error when I try running the project because it expects **PackageB** dll from nuget.
I tried as a workaround to set **Version** and **PackageVersion** in **MyProjectB** but it did not help.
There was no issue with **PackageB** version like 0.1.* and it used default generated dll with version 1.0.0.0. But now I need to use higher version and it does not work.
And the idea is that **MyTestProject** is later built in docker with standard dotnet restore, build publish. So it must work both locally and in docker container.

This is the project that is used for testing purposes so I can do workaround. Could you please suggest any?

The only trick I can do is just to push some dummy version of **PackageB** with version starts with 0.* and it will work. But this workaround seems quite stupid so I'd like to hear better suggestions.</div>

**Comment by zkat** [comment]
Unfortunately, this is not something we would actually be able to do. Making this kind of modification to the algorithm is significant and would break a _different_ kind of scenario. As such, I'm going to close this issue. Thank you for your time!
