### ISSUE TITLE
NuGet 3.1 UAP: reference to native winmd failed

### ISSUE THREAD

**Issue by vlechenko** [NuGet/Home#1108]
When we create C++ Windows Runtime Component we have winmd and dll.

No implementation file was provided for the .winmd file 'C:\Users\%username%\.nuget\packages\%packagename%\lib\uap\%name%.winmd'. To generate registration information in the app manifest, specify the 'Implementation' metadata on the .winmd reference item in the project file.

But we can't add 'Implementation' metadata because *.targets and PowerShell is not supported now.

**Comment by emgarten** [comment]
Targets are supported. For UAP use build\uap

**Comment by vlechenko** [comment]
When I move .dll and .winmd to build\uap NuGet say to me that it is not good solution.
When I add *.targets to packages then I can't install package.

**Comment by vlechenko** [comment]
Please see file "build\uap\SQLite.Core.Universal-x86.targets"
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="SQLite.Core">
      <HintPath>$(MSBuildThisFileDirectory)..\..\build\uap\SQLite.Core.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
      <Implementation>$(MSBuildThisFileDirectory)..\..\lib\uap\SQLite.Core.dll</Implementation>
    </Reference>
  </ItemGroup>
</Project>

It does not work. This file was ingored.

**Comment by yishaigalatzer** [comment]
You need to place it in `build/uap/native` to be picked up. See https://www.nuget.org/packages/Win2D.uwp/ for sample

CC @csharpfritz we need the samples in docs asap
