### ISSUE TITLE
Reduce UI thread switching when determining solution folder and if solution is open

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11090]
NuGet's Visual Studio extension has a class named `VsSolutionManager`, which provides some APIs to the rest of our code. Two of these APIs, `SolutionDirectory` and `IsSolutionOpenAsync` switch to the UI thread.

In at least one of the code paths, `IsSolutionOpenAsync` is called from a background thread, therefore switches to the UI thread, and returns it's value. This causes the caller to schedule its continuation on the background thread, but it then immediately calls another API that switches to the UI thread again.  This adds latency to the customer experience. While switching to the UI thread in the caller will remove the bouncing between threads, code running on the UI thread prevents other code from using the UI thread until our code finishes running. Therefore removing the need for the UI thread is preferable.

SolutionDirectory can be obtained once, and cached, eliminating the need to switch to the UI thread every time the directory is needed.

This class already listens to solution events, so IsSolutionOpenAsync can cache the last known state change.

**Comment by zivkan** [comment]
I've spent another day or two on this, and it's just not worth the effort.

Caching `IsSolutionOpen`, `SolutionDirectory` and `SolutionFile` based on events that VS provides, I just can't get it to work the same as polling DTE every time the respective methods are called. Using PerfView to capture a trace, these methods are an insignificant duration, so the cost to benefit ratio just isn't there. Let's focus on more impactful things instead.

**Comment by nkolev92** [comment]
Reopening this. 
The idea isn't so much that this would save a lot of measurable CPU time, but rather the fact that it reduces contention for the UI thread and thus indirectly affects threadpool consumption as we still have places where we try to read this synchronously. 

@adrianvmsft Also provide some links that'd allow us to read all this information in an async way, so fixing this might be an easy win.

**Comment by nkolev92** [comment]
I've unassigned @zivkan from this for now, but you can pick it up if you want it :D

**Comment by nkolev92** [comment]
CPS has a different way of [caching](https://devdiv.visualstudio.com/DevDiv/_git/CPS?path=/src/Microsoft.VisualStudio.ProjectSystem.VS.Implementation/Build/SolutionInformationService.cs&version=GBmain&line=230&lineEnd=230&lineStartColumn=35&lineEndColumn=70&lineStyle=plain&_a=contents). There might be some async code made available soon.

**Comment by Erarndt** [comment]
I'm currently doing work to expose free-threaded methods of requesting that information. We should chat so that we make sure this scenario is covered.
