### ISSUE TITLE
Floating references and NuGet package generation

### ISSUE THREAD

**Issue by RobSwDev** [NuGet/Home#11093]
### Discussed in https://github.com/NuGet/Home/discussions/11088

<div type='discussions-op-text'>

<sup>Originally posted by **RobSwDev** July 26, 2021</sup>
I have 3 .Net projects `A`, `B`, `C` that are built and released (via NuGet ) separately. Project `A` references both `B` and `C`, while `B` references `C` using floating versions in the PackageReference. Each references version `4.1.*`. 

Unfortunately, when the NuGet package for `B` is built, it crystallizes the version of `C` from `4.1.*` to the latest version available: say `4.1.7`. This means that when we make a new release of `C`, we are also forced to make a new release of `B`, otherwise building `A` fails with package downgrade errors.

It says in [the docs](https://docs.microsoft.com/en-au/nuget/reference/nuspec#dependencies-element) that floating versions are not supported. However, a floating version can easily be converted into a range can't it?
I.e. `4.1.*` is equivalent to `[4.1.0, 4.2.0)`

What I want is for the NuGet package dependencies to be generated using an equivalent version range to the floating version specified in the package reference (rather than crystallized at whatever the latest version is when the NuGet package is built). Is there any way of doing this? If not, would it be a reasonable feature request (e.g. as an optional property on the package reference)?

</div>

**Comment by zkat** [comment]
This is best left as a discussion, because it's more about understanding how NuGet actually works, rather than changing anything (we can't really change this).
