### ISSUE TITLE
[Bug]: .NET 5 pack broken if project has both snupkg and embedded README 

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#11092]
### NuGet Product Used

dotnet.exe

### Product Version

5.0.301

### Impact

I'm unable to use this version

### Repro Steps & Context

It looks like NuGet fails to pack a .snupkg if the project has an embedded README. Notice the `.nupkg` file is generated but not the `.snupkg` in the logs below.

HelloWorld.csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
```

README.md:

```
Hello world
```

Class1.cs:

```cs
namespace HelloWorld
{
    public class Class1 { }
}
```

### Verbose Logs

```shell
> dotnet build ; dotnet pack
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\Code\Scratch\4\HelloWorld.csproj (in 62 ms).
  HelloWorld -> D:\Code\Scratch\4\bin\Debug\net5.0\HelloWorld.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.12
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  HelloWorld -> D:\Code\Scratch\4\bin\Debug\net5.0\HelloWorld.dll
  Successfully created package 'D:\Code\Scratch\4\bin\Debug\HelloWorld.1.0.0.nupkg'.
C:\Program Files\dotnet\sdk\5.0.301\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5039: The readme file 'README.md' does not exist in the package. [D:\Code\Scratch\4\HelloWorld.csproj]
```

Exception in binlog:

```
NuGet.Packaging.Core.PackagingException: The readme file 'README.md' does not exist in the package.
   at NuGet.Packaging.PackageBuilder.ValidateReadmeFile(IEnumerable`1 files, String readmePath)
   at NuGet.Packaging.PackageBuilder.Save(Stream stream)
   at NuGet.Commands.PackCommandRunner.BuildPackage(PackageBuilder builder, String outputPath, Boolean symbolsPackage)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage(String path)
   at NuGet.Commands.PackCommandRunner.RunPackageBuild()
   at NuGet.Build.Tasks.Pack.PackTaskLogic.BuildPackage(PackCommandRunner runner)
   at NuGet.Build.Tasks.Pack.PackTask.Execute()
```

**Comment by loic-sharma** [comment]
It looks like the bug is in [`PackageBuilder.ValidateReadmeFile`](https://github.com/NuGet/NuGet.Client/blob/d70adaba77e5754ecdc41984edd21c5cecf8c2a2/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L867) as it checks for a README in symbol packages even though they [cannot contain READMEs](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg#nugetorg-symbol-package-constraints). Other similar methods, like `PackageBuilder.ValidateLicenseFile` or `PackageBuilder.ValidateIconFile`, are skipped on the symbol package type ([here](https://github.com/NuGet/NuGet.Client/blob/d70adaba77e5754ecdc41984edd21c5cecf8c2a2/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L709) and [here)](https://github.com/NuGet/NuGet.Client/blob/d70adaba77e5754ecdc41984edd21c5cecf8c2a2/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L745) before performing the validation. This package type check is missing for the README path.

**Comment by zivkan** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/10791

**Comment by loic-sharma** [comment]
Oops, my searching skills are bad. Closing this one as duplicate
