### ISSUE TITLE
[Bug]: Non open source code in end to end tests

### ISSUE THREAD

**Issue by omajid** [NuGet/Home#11094]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 6.0 Preview 6

### Worked before?

Not sure

### Impact

I'm unable to use this version

### Repro Steps & Context

Here's how I can see the affected file:

```
$ git clone https://github.com/NuGet/NuGet.Client
Cloning into 'NuGet.Client'...
remote: Enumerating objects: 127652, done.
remote: Counting objects: 100% (4262/4262), done.
remote: Compressing objects: 100% (1763/1763), done.
remote: Total 127652 (delta 2764), reused 3676 (delta 2436), pack-reused 123390
Receiving objects: 100% (127652/127652), 52.34 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (99133/99133), done.
$ cd NuGet.Client/
$ git rev-parse HEAD
d70adaba77e5754ecdc41984edd21c5cecf8c2a2
$ grep license test/EndToEnd/ProjectTemplates/NetCoreWebApplication1.0.zip/wwwroot/lib/jquery-validation-unobtrusive/.bower.json
  "license": "http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm",
```

You can also see this online at:
https://github.com/NuGet/NuGet.Client/blob/d70adaba77e5754ecdc41984edd21c5cecf8c2a2/test/EndToEnd/ProjectTemplates/NetCoreWebApplication1.0.zip/wwwroot/lib/jquery-validation-unobtrusive/.bower.json#L26

**Comment by omajid** [comment]
cc @dleeapho @leecow

**Comment by omajid** [comment]
cc @dseefeld @MichaelSimons @crummel

**Comment by aortiz-msft** [comment]
@omajid - Would you please add additional information to the request?

**Comment by omajid** [comment]
@aortiz-msft sure, happy to. Can you tell me what sort of additional information I can provide here?

**Comment by zkat** [comment]
@zivkan would you please help us understand implications and next steps here? I'm told you also brought this up recently.

**Comment by zivkan** [comment]
We're waiting to hear from the source-build team to help us determine priority/impact.

**Comment by zivkan** [comment]
For what it's worth, End to End tests are Visual Studio tests, which don't impact source-build or the .NET SDK in any way. NuGet is just a mono-repo with code that ships in both the .NET SDK and Visual Studio.

**Comment by omajid** [comment]
> For what it's worth, End to End tests are Visual Studio tests, which don't impact source-build or the .NET SDK in any way.

I disagree with the characterization that there's no impact on source-build. Anyone using source-build is using source-build because they care about the sources as well as binaries. The fact that these libraries with non-open source licenses get included into the source compilation (produced by source-build) makes the source compilation unusable by anyone trying to only use open source code. That means users of source-build, just by using these source files (even if they don't build them), are at risk of violating this non-open source license. Companies, organizations and projects that mandate a "open source only" approach will be forced to not use source-build.

In particular, the license at http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm has several clauses that place restrictions on "distributable code". I am not even sure what that is, and the fact that I have to get legal review and approval of this makes this almost a non-starter as an open source project.

**Comment by richlander** [comment]
Ping ... Can we take another run at this for .NET 7? The goal is to have a way to validate NuGet client w/only OSS assets.

**Comment by richlander** [comment]
Thanks!

How's that look @omajid?

**Comment by omajid** [comment]
I have verified the original issue is now fixed for me.

Thanks!
