### ISSUE TITLE
UWP projects are unable to install unlisted packages

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1109]
Unlisted packages cannot be installed from project.json based projects. The find package by id resource uses the versions list from flatcontainer which no longer contains the unlisted versions.

Example 2.1.0 is not in the versions list:
https://az320820.vo.msecnd.net/v3-flatcontainer/microsoft.web.xdt/index.json

This is a server side fix.

**Comment by yishaigalatzer** [comment]
This was already fixed
