### ISSUE TITLE
[Pack][Doc] There is no conflict-tip show in the “dotnet pack” page when using “--version-suffix” and “-p:PackageVersion” meanwhile

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11105]
## Details about Problem
VS Version: Main\31529.265
NuGet Version: Dev\6.0.0.168
OS Version: Windows-10-Enterprise-21H1

## Repro steps
1. Launch VS and create a new C# Class Library (.NET 6.0).
2. Open the Developer Command Prompt and cd to the project path.
3. Run command “dotnet pack -c Release --version-suffix "Jamie" -p:PackageVersion=3.0.0”.
4. Check the info on the dotnet pack page.

## Expected
There is a conflict-tip show in the “dotnet pack” page when using “--version-suffix” and “-p:PackageVersion” meanwhile to tell user that the “--version-suffix” will not be respected.

## Actual
There is no conflict-tip show in the “dotnet pack” page (no warning show while running the command) when using “--version-suffix” and “-p:PackageVersion” meanwhile as below. 
![image](https://user-images.githubusercontent.com/20632625/127632275-866d48d9-17d5-43b6-ab89-8e1eb079f0f1.png)

![image](https://user-images.githubusercontent.com/20632625/127632365-a153438b-5ea4-4f78-863e-f75ed38cbe35.png)
## Note:
1.It doesn’t repro on “nuget pack” command when using “-Suffix” and “-Version” meanwhile since both two options will be respected.
2.It is not a regression.

**Comment by erdembayar** [comment]
I can repro this bug, bug considering this one doesn't even pack on .net sdk 5.0 I wouldn't consider this as regression.

dotnet pack -c Release --version-suffix "Jamie" -p:PackageVersion=3.0.0
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\NuGetProj\IssueRepro\11105\11105.csproj (in 55 ms).
  11105 -> C:\NuGetProj\IssueRepro\11105\bin\Release\net5.0\11105.dll

**Comment by zkat** [comment]
Detecting this conflict would be harder than the value of fixing this particular bug. As such, I'm closing this.
