### ISSUE TITLE
The Alternate Package’s name shows the redundant “packageid:” in the search box in “Browse” tab

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11111]
## Details about Problem
VS Version: Main\31601.14
NuGet Version: Dev\6.0.0.169
OS Version: Windows-10-Enterprise-21H1

## Installation
1. Install VS Main\31601.14 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5044845&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Client Dev\6.0.0.169: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5039908&view=artifacts&pathAsName=false&type=publishedArtifacts

## Steps to reproduce
1. Create a C# Console Application (.NET core) project.
2. Open PM UI, add a deprecated package source https://apidev.nugettest.org/v3-index/index.json and select it.
3. Search the deprecated package (e.g. afine) in “Browse” tab.
4. Click the link of the Alternate package (e.g. plastic=3.0.0).

## Expected
Only the Alternate Package’s name shows in the search box in “Browse” tab.
 
## Actual
The Alternate Package’s name shows the redundant “packageid:” in the search box in “Browse” tab
as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/127850295-7fd5a850-1065-4d94-b3ac-98d87fca147e.png)
## Notes
1. The issue also reproes on “test10k” package.
2. The issue does not repro on “ComplexLicense/ComplexLicenseExpressionWithException” package.
3. The issue starts from Dev\6.0.0.169.

**Comment by donnie-msft** [comment]
I believe this is expected since we want an exact match in this case (docs at https://docs.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax). 

Whether we want to allow "hidden exact match searches" from our own code hasn't been discussed. @dominoFire if know differently, please reopen/comment.

**Comment by dominoFire** [comment]
@donnie-msft @v-crchang Yes, this is expected, per comment https://github.com/NuGet/NuGet.Client/pull/4144#issuecomment-886352539
