### ISSUE TITLE
Establish baseline for vulnerable packages installed

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#11112]

**Comment by nkolev92** [comment]
@jebriede 

Can you link any outcomes from this issue? 

I'm trying to provide an update for the sprint planning: https://microsoft.sharepoint.com/:x:/t/NuGet/EXIow2bgAdpKhIMhMj6xWsUB8KZFWW5I3MFWKuqq0rs3Rw?e=LGgvnP
