### ISSUE TITLE
many nugets are currently showing "This package has not been indexed yet"

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#1112]
even though they were deployed a long time ago

https://www.nuget.org/packages/EntityFramework/5.0.0
https://www.nuget.org/packages/Fody/1.29.0
https://www.nuget.org/packages/Newtonsoft.Json/3.5.8

**Comment by yishaigalatzer** [comment]
@SimonCropp thanks for the report. We are aware and actively looking at
1. Updating our monitoring to catch the issues
2. Fix the individual packages
3. Track the bug causing this

CC @johnataylor @maartenba @xavierdecoster @bhuvak

**Comment by yishaigalatzer** [comment]
This looks like is just a bug in the notification, for packages that are not the latest package. We are looking into a solution. Thanks for reporting

**Comment by SimonCropp** [comment]
BTW a google search for "This package has not been indexed yet" will show u more examples

**Comment by johnataylor** [comment]
I think the “not indexed yet” banner is giving us some false negatives. i.e. its saying that packages are not yet indexed when in fact they are.

The fix is in this code I think: (PackagesController.cs l.304)

            if (_searchService.ContainsAllVersions)
            {
                var isIndexedCacheKey = string.Format("IsIndexed_{0}_{1}", package.PackageRegistration.Id, package.Version);
                var isIndexed = HttpContext.Cache.Get(isIndexedCacheKey) as bool?;
                if (!isIndexed.HasValue)
                {
                    var searchFilter = SearchAdaptor.GetSearchFilter(
                            "id:\"" + package.PackageRegistration.Id + "\" AND version:\"" + package.Version + "\"",
                            1, null, SearchFilter.ODataSearchContext);
                    var results = await _searchService.RawSearch(searchFilter);

That is to say you are building a raw Lucene query and need to say that. This also avoids the filtering logic too I think.

Anyhow, without this many packages (everything but the latest?) are appearing as “not indexed” when in fact they are.

**Comment by maartenba** [comment]
A fix has been deployed.

**Comment by ryanhelms** [comment]
Has this bug be reintroduced? I am getting the "This package has not been indexed yet" banner on many packages, example:
- https://www.nuget.org/packages/NUnit.Runners/3.2.0
- https://www.nuget.org/packages/NUnit.Runners/2.6.4

And after just searching around for a few, I noticed that there are a lot (90% of the non-latest package) being reported "not been indexed yet", example:

 **_(3 randomly selected packages, not latest stable package)**_
- https://www.nuget.org/packages/Microsoft.AspNet.Mvc/5.2.0
- https://www.nuget.org/packages/BuildingBlocks.Mvc.KnockoutMvc/1.0.0.60
- https://www.nuget.org/packages/NExtra.Mvc/2.6.5

**Comment by maartenba** [comment]
Looking into it, thanks!

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#3006

**Comment by ratishphilip** [comment]
@maartenba @yishaigalatzer 
Is this issue back again.
I uploaded my Nuget package [CompositionProToolkit](https://www.nuget.org/packages/CompositionProToolkit/) 3 hours ago but still it is showing "**This package has not been indexed yet**" message.
Earlier it used to take not more than 10-15 mins for the package to be available.

**Comment by yishaigalatzer** [comment]
Thanks, we did have a period today where we had a delay. The issue was fixed, and things should be back to normal.

You can always check status at https://status.nuget.org/

Here is the graph from the time of the event:

![image](https://cloud.githubusercontent.com/assets/1238711/17499786/9048777c-5d84-11e6-9e4f-17fac9e8cbfa.png)

**Comment by ratishphilip** [comment]
@yishaigalatzer Thank you very much.

**Comment by sammosampson** [comment]
This seems to be happening again. https://www.nuget.org/packages/SystemDot.MessageRouteInspector.Server/1.2.1

**Comment by yishaigalatzer** [comment]
The package looks indexed properly. Are you still seeing this?
