### ISSUE TITLE
[Bug]: nuget update -self does not update to latest 5.10

### ISSUE THREAD

**Issue by deadalusai** [NuGet/Home#11123]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet.exe 5.9.1

### Worked before?

NuGet.exe 5.9.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Attempting to update `nuget` from the command line:
```
> nuget update -self
Checking for updates from https://api.nuget.org/v3/index.json [https://api.nuget.org/v3/index.json].
  GET https://api.nuget.org/v3/registration5-gz-semver2/nuget.commandline/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/nuget.commandline/index.json 824ms
Currently running NuGet.exe 5.9.1.
NuGet.exe is up to date.
Update successful.
```

I can only upgrade to 5.10 manually by downloading the `latest` version on nuget.org:
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

This appears to be caused by the package `NuGet.CommandLine` being stuck back on `5.9.1`?
https://www.nuget.org/packages/NuGet.CommandLine/

![image](https://user-images.githubusercontent.com/918952/128102181-c2c46f8c-1df6-477b-9238-ab4a57cfff11.png)

### Verbose Logs

```shell
> nuget update -self
Checking for updates from https://api.nuget.org/v3/index.json [https://api.nuget.org/v3/index.json].
  GET https://api.nuget.org/v3/registration5-gz-semver2/nuget.commandline/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/nuget.commandline/index.json 824ms
Currently running NuGet.exe 5.9.1.
NuGet.exe is up to date.
Update successful.
```

**Comment by kartheekp-ms** [comment]
`NuGet.CommandLine` package version 5.10.0 has been [published to nuget.org](https://www.nuget.org/packages/NuGet.CommandLine/). Please run the `nuget update -self` command again.
