### ISSUE TITLE
[Dotnet List Package] An incorrect dotnet SDK showed when running the command “dotnet-install”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11136]
## Details about Problem
OS Version: Windows-10-Enterprise-21H1. 
Dotnet SDK: 6.0.100-preview.6.21355.2
## Detailed repro steps
1.	Create a Powershell script named "Test.ps1" with below contents.
```
"Getting latest .NET Core CLI" 
if (!(Test-Path .\cli)) { 
   New-Item .\cli\ -ItemType Directory | Out-Null 
} 
if (!(Test-Path .\cli\dotnet-install.ps1)) { 
   Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile .\cli\dotnet-install.ps1 
} 
.\cli\dotnet-install -InstallDir cli -c main
 
"Creating test package projects" 
.\cli\dotnet new classlib -n MyLib 
.\cli\dotnet new classlib -n MyDep 
.\cli\dotnet add MyLib/MyLib.csproj reference MyDep/MyDep.csproj 
.\cli\dotnet new sln -n test 
.\cli\dotnet sln add MyLib/MyLib.csproj 
.\cli\dotnet sln add MyDep/MyDep.csproj 
 
.\cli\dotnet build 
 
"Creating packages" 
.\cli\dotnet msbuild /t:pack /p:version=1.0.1 
.\cli\dotnet msbuild /t:pack /p:version=1.0.2 
.\cli\dotnet msbuild /t:pack /p:version=1.0.3-beta 
.\cli\dotnet msbuild /t:pack /p:version=1.1.0 
.\cli\dotnet msbuild /t:pack /p:version=1.2.0-beta 
.\cli\dotnet msbuild /t:pack /p:version=2.0.0 
.\cli\dotnet msbuild /t:pack /p:version=3.0.0-beta 
 
"Creating nuget.config" 
New-Item .\localSource\ -ItemType Directory | Out-Null 
.\cli\dotnet new nugetconfig 
$xml = [xml](Get-Content .\nuget.config)  
$sources = $xml.SelectSingleNode('/configuration/packageSources') 
$sources.RemoveAll() 
$source = $xml.CreateElement('add') 
$source.SetAttribute('key', 'localSource') | Out-Null 
$source.SetAttribute('value', 'localSource') | Out-Null 
$sources.AppendChild($source) 
$source = $xml.CreateElement('add') 
if (Test-Path .\cli\sdk\NuGetFallbackFolder) { 
       $source.SetAttribute('key', 'dotnetFallbackFolder') | Out-Null 
       $source.SetAttribute('value', 'cli/sdk/NuGetFallbackFolder') | Out-Null 
       $sources.AppendChild($source) 
} 
$config = $xml.CreateElement('config') 
$xml.DocumentElement.AppendChild($config) | Out-Null 
$globalPackagesFolder = $xml.CreateElement('add') 
$globalPackagesFolder.SetAttribute('key', 'globalPackagesFolder') 
$globalPackagesFolder.SetAttribute('value', 'globalPackages') 
$config.AppendChild($globalPackagesFolder) | Out-Null 
$xml.Save((Join-Path (Get-Location) nuget.config)) 
Copy-Item *\bin\Debug\*.nupkg .\localSource\ | Out-Null 
 
"Creating test program" 
.\cli\dotnet new console -n MyProg 
.\cli\dotnet add MyProg\MyProg.csproj package MyLib -v 1.0.0 
.\cli\dotnet restore MyProg\MyProg.csproj 
.\cli\dotnet new console -n deprecationTest 
.\cli\dotnet add .\deprecationTest\deprecationTest.csproj package NuGet.Core -v 2.14.0 

.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive --highest-patch 
"latest version of MyLib and MyDep above should be 1.0.2" 
Pause 
 
.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive --highest-patch --include-prerelease 
"latest version of MyLib and MyDep above should be 1.0.3-beta" 
Pause 
 
.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive --highest-minor 
"latest version of MyLib and MyDep above should be 1.1.0" 
Pause 
 
.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive --highest-minor --include-prerelease 
"latest version of MyLib and MyDep above should be 1.2.0-beta" 
Pause 
 
.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive 
"latest version of MyLib and MyDep above should be 2.0.0" 
Pause 
 
.\cli\dotnet list MyProg\MyProg.csproj package --outdated --include-transitive --include-prerelease 
"latest version of MyLib and MyDep above should be 3.0.0-beta" 
Pause 
 
 
.\cli\dotnet list .\deprecationTest\deprecationTest.csproj package --deprecated 
"the deprecated package version of deprecationTest above should be 2.14.0" 
Pause 
 
"testing complete with the following version of the .NET Core CLI/SDK" 
.\cli\dotnet --version 
 
.\cli\dotnet new classlib -n MultiTargetTest 
$xml=@' 
<Project Sdk="Microsoft.NET.Sdk"> 
 
    <PropertyGroup> 
      <TargetFrameworks>netstandard1.3;netstandard2.0</TargetFrameworks> 
   </PropertyGroup> 
 
   <ItemGroup> 
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1" /> 
   </ItemGroup> 
 
    <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'"> 
      <PackageReference Include="Moq" Version="4.10.0" /> 
     </ItemGroup> 
 
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'"> 
    <PackageReference Include="xunit" Version="2.4.0" /> 
  </ItemGroup> 
 
</Project> 
'@ 
Out-File -FilePath .\MultiTargetTest\MultiTargetTest.csproj -InputObject $xml 
.\cli\dotnet restore MultiTargetTest\MultiTargetTest.csproj 
.\cli\dotnet list MultiTargetTest\MultiTargetTest.csproj package 
"The output above should have two target frameworks, netstandard1.3 and netstandard2.0" 
"Moq should be listed under netstandard1.3, but not netstandard2.0" 
"xunit should be listed under netstandard2.0, but not netstandard1.3" 
"Newtonsoft.Json should be listed under both" 
pause
```
2.	Open Task Manager.
3.	Navigate on the main menu to File | “Run new task”.
4.	In the Open textbox type ‘Powershell -ExecutionPolicy Bypass’.
5.	Enable the option “Create this task with administrative privileges”.
6.	Cd to the path of "Test.ps1" and run the command ‘.\Test.ps1’.
7.	Press Enter for several times and check the result.
## Expected
A correct dotnet SDK version shows in the downloading step when running the command “dotnet-install”. That should be “6.0.100-preview.6.21355.2” in this instance.
## Actual
An incorrect dotnet SDK version shows in the downloading step when running the command “dotnet-install” as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/128466653-b9462ab1-fb51-4620-92fc-e2194c905892.png)
## Notes
1.	It is start to repro from dotnet SDK 6.0.100-preview.6.21355.2.
2.	It did not repro on dotnet SDK 6.0.100-preview.6.21276.12.

**Comment by erdembayar** [comment]
@aortiz-msft 
I can repro this issue.

**Comment by erdembayar** [comment]
~~See https://github.com/NuGet/Home/issues/11137#issuecomment-897345373, they're connected.~~

**Comment by aortiz-msft** [comment]
@erdembayar - could you please make sure the script is doing the right thing?

**Comment by erdembayar** [comment]
@v-luzh @aortiz-msft 
It looks it's bug in script itself, so I'm removing regression label for now, we can add later if it's really a regression.

```
Without global.json it simply show current highest installed sdk version on my machine.
C:\NuGetProj\IssueRepro\11136> .\cli\dotnet --version
6.0.100-preview.7.21379.14

With global.json file I can control sdk version, please note it's coming from my machine sdk not from downloaded sdk from cli  folder as script expect)
C:\NuGetProj\IssueRepro\11136> .\cli\dotnet --version
6.0.100-preview.6.21276.12

Here global.json content:
{"sdk": {"version": "6.0.100-preview.6.21276.12"}}
```

For correcting this one please look at SimpleTestPathContext in our [integration tests ](https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.FuncTests/Dotnet.Integration.Test/DotnetAddPackageTests.cs)  as example.
It looks you need to set env var values to point your downloaded sdk:
![image](https://user-images.githubusercontent.com/8766776/129282784-991fa67e-5832-4094-92b0-6298d41ad63d.png)

**Comment by v-luzh** [comment]
Hi @erdembayar, seems the script is correct. Because the version is consistent as below screenshot now when I verifying the issue without updating anything in the scripts.
![image](https://user-images.githubusercontent.com/20632625/129703650-31692ba5-503a-471a-9eca-eb7e9a52daaf.png)

**Comment by erdembayar** [comment]
> Hi @erdembayar, seems the script is correct. Because the version is consistent as below screenshot now when I verifying the issue without updating anything in the scripts.
> ![image](https://user-images.githubusercontent.com/20632625/129703650-31692ba5-503a-471a-9eca-eb7e9a52daaf.png)

It's correct as long as you didn't install any other higher version. If you have any other higher sdk version already installed then script wouldn't work as expected.

**Comment by v-luzh** [comment]
Hi @erdembayar, I see. Do you mean we should add a env variable point to the downloaded sdk in below table before running the whole script?
![image](https://user-images.githubusercontent.com/20632625/129830455-823d79c2-5e0a-4a4e-b059-bcc58a0fa0f4.png)
But we would not know the exact dotnet SDK which we will test on until running the script. (You can see the top of the script.) The sdk will write to the "...\cli\sdk" folder after running "dotnet-install.ps1". So how can we add the exact sdk path into the env var values in the very beginning?

**Comment by erdembayar** [comment]
@v-luzh 
Your downloaded sdk is relative to your current location. You can get current folder in powershell. Then just add append "\cli\sdk\6.0.100-preview.6.21276.12" into it.
$currentpath = Get-Location | Select-Object -ExpandProperty Path
$sdkPath =Join-Path $currentpath "\cli\sdk\6.0.100-preview.6.21276.12"
You can set env var from powershell without changing your machine state:
$env:MSBuildDSDKsPath = $sdkPath

Here is full code:
```
C:\NuGetProj\IssueRepro\11136> $currentpath = Get-Location | Select-Object -ExpandProperty Path
C:\NuGetProj\IssueRepro\11136> $sdkPath =Join-Path $currentpath "\cli\sdk\6.0.100-preview.6.21276.12"
C:\NuGetProj\IssueRepro\11136> $sdkPath
C:\NuGetProj\IssueRepro\11136\cli\sdk\6.0.100-preview.6.21276.12
C:\NuGetProj\IssueRepro\11136> $env:MSBuildDSDKsPath = $sdkPath
C:\NuGetProj\IssueRepro\11136> .\cli\dotnet --version
6.0.100-preview.6.21276.12
```
Main point of setting env var is we make sure we're running dotnet sdk commands against specific version dotnet sdk we just downloaded. Of course we can improve above manually setting local path part using powershell functions.  `Join-Path $currentpath "\cli\sdk\6.0.100-preview.6.21276.12"`
Please let me know if you have any other question.

**Comment by zivkan** [comment]
> It's correct as long as you didn't install any other higher version. If you have any other higher sdk version already installed then script wouldn't work as expected.

Scripts can use `DOTNET_MULTILEVEL_LOOKUP` to ensure it doesn't find system installed SDKs, even if they're a higher version number: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_multilevel_lookup

However, our test scripts really should be testing the latest nightly build of the .NET SDK, so if it's not the highest version on the system, we need to look at how we're using `dotnet-install.ps1` and fix it to make sure we get the latest nightly build.

**Comment by aortiz-msft** [comment]
@heng-liu  - Would you please take a look this sprint?

**Comment by heng-liu** [comment]
The script in the description is using the latest version of SDK which is downloaded from main branch.
If we would like to test with NuGet bits not yet inserted in the SDK, we'd better patch the SDK with the latest NuGet bits.
Updated the script in test case "Dotnet list packages test" and saved it in "Dotnet list packages test - use patched sdk" page.
Pls refer to https://github.com/NuGet/Client.Engineering/issues/1111.

**Comment by heng-liu** [comment]
I think this issue could be closed as fixed, right? @v-luzh

**Comment by v-luzh** [comment]
Yes, it is fixed after patching the SDK with the latest NuGet bits. Close this bug as "Fixed" now, thanks.
