### ISSUE TITLE
[Bug]: Package name capitalization is inconsistent in NU1605 error message

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#11131]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.0 preview 3

### Worked before?

Not sure - but present in 16.11

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

**Repro**

1. Install Newtonsoft.Json 12.01
2. Try to install Contoso.NuGet.Example 1.2.0, which requires Newtonsoft.Json (>=12.0.3)
3. Notice inconsistent capitalization of Newtonsoft.Json in NU1605 error message in VS Error List

In some places it's entirely lowercase, in others it has the correct capitalization. Unsure if this bug exists for other error messages as well.

![image](https://user-images.githubusercontent.com/15097183/128256344-ce0bf245-1c2f-419c-b095-cf2de36fc3f5.png)

**Expected**

Error message uses correct capitalization (Newtonsoft.Json) in all instances.

**Comment by nkolev92** [comment]
The casing is preserved  and it's the one specified by the dependencies. 

For example: https://www.nuget.org/packages/Contoso.NuGet.Example/ specifies `newtonsoft.json` as a dependency. 

Package names are case insensitive, so it's also possible that a package when created declares different casing for it's name. 
I'm not sure there's always a correct name, or whether it's worth figuring it out.

**Comment by chrisraygill** [comment]
Closing based on Nikolche's feedback. This is a minor issue, so I don't feel the "correct name" is worth figuring out.
