### ISSUE TITLE
Remove temporary Newtonsoft.Json workaround in dotnet integration tests

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11135]
Our dotnet integration tests copy a working .NET SDK folder, then patch the NuGet assemblies, and use this copy/patched .NET SDK to run tests.

We're upgrading to a version of newtonsoft.json higher than what the .NET SDK currently has (we're both upgrading at the same time), but until our CI pipeline start using builds of .NET SDK with a high enough version, we need to copy it ourselves.

Here's what needs to be removed:
https://github.com/NuGet/NuGet.Client/pull/4167/files/0e2f6a70900839b1f8670f8fd471d36bf1974df0#diff-8a81e906729d9dc1d11f635564b6eed54b859ab8aaacb3713fc29b19189f0f3b

**Comment by zivkan** [comment]
This also requires us to use a new .NET 6 SDK for testing (we're still using a .NET 5 SDK) 😞 That work is larger than just removing this workaround.

**Comment by kartheekp-ms** [comment]
@zivkan - I think we can remove this work around because the tests now use .NET SDK 6.
