### ISSUE TITLE
[Bug]: Downloads: 0 appears in Installed tab PM UI inconsistently

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#11130]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

5.11.0.10, 6.0.0.165

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Install Newtonsoft.Json 7.0.1 in the Browse tab
2. Switch to the installed tab
3. Select the 6.0.8 version of Newtonsoft.Json in the version dropdown
4. Switch back to 7.0.1

![zero-dl](https://user-images.githubusercontent.com/94054/128249575-1f931ee2-f68f-4548-bb61-133f633208fc.gif)

**Comment by chrisraygill** [comment]
cc @donnie-msft

**Comment by donnie-msft** [comment]
Dupe of https://github.com/NuGet/Home/issues/11012
