### ISSUE TITLE
For projects with project.json, need a gesture such as a menu, to force Restore Packages

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1113]
For projects with project.json, need a gesture such as a menu, to force Restore Packages.
For example, dnu projects have a project-level menu that can restore packages

![image](https://cloud.githubusercontent.com/assets/2380340/9075165/6197dbd4-3ac6-11e5-8c27-814cbc94a6ca.png)

**Comment by yishaigalatzer** [comment]
We need to coordinate this with @BillHiebert 

CC @davidfowl

**Comment by yishaigalatzer** [comment]
Done in 3.2
