### ISSUE TITLE
Support sourceUri option passed on dotnet add package

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11140]
This is follow up on https://github.com/NuGet/Home/issues/10948.
I addressed most of source Uri pass option scenarios with https://github.com/NuGet/NuGet.Client/pull/4188.
But `dotnet add package -source` is not covered due to https://github.com/NuGet/Home/issues/11035 is completed yet.

**Comment by nkolev92** [comment]
Do you know if this needs any product changes @erdembayar?

Assigning to @kartheekp-ms for now, but it is my understanding that it works as expected.

**Comment by erdembayar** [comment]
> Do you know if this needs any product changes @erdembayar?
> 
> Assigning to @kartheekp-ms for now, but it is my understanding that it works as expected.

Most likely it doesn't need any change, just need to add unit test to assert it works.

**Comment by nkolev92** [comment]
Tests were added in https://github.com/NuGet/NuGet.Client/pull/4225/files. 

@kartheekp-ms Closing for now, but please double check!

Thanks!

**Comment by kartheekp-ms** [comment]
You are correct @nkolev92 tests for `dotnet add package -sourceUri` were already added in the PR you have linked above.

https://github.com/NuGet/NuGet.Client/pull/4225/files#diff-ffa6ee0891a89544eaa7d4279a6b5cfd948aa6e26ba7cc7d0b28319d9473c715R354

https://github.com/NuGet/NuGet.Client/pull/4225/files#diff-ffa6ee0891a89544eaa7d4279a6b5cfd948aa6e26ba7cc7d0b28319d9473c715R420
