### ISSUE TITLE
NuGet config is hierarchical. NuGet Settings dialog does not handle or reflect that

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1114]
NuGet config is hierarchical. NuGet Settings dialog does not handle or reflect that.
Currently, it is unclear where a setting like a package source comes from, local nuget.config or global nuget.config. Settings dialog may be need to enhanced to handle this

**Comment by yishaigalatzer** [comment]
We should consider a rather quick fix, where if the user have nuget.config in multiple places, we send him to edit the files directly.

Building a proper UI for multi level config is not going to be short or simple.

CC @DamianEdwards

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/1820
