### ISSUE TITLE
[Bug]: VS PM UI does not display JPEG icons for packages

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/Home#11144]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 2019 (16.10.4)

### Worked before?

?

### Impact

Other

### Repro Steps & Context

JPEG icons [are supported in the NuGet specification](https://docs.microsoft.com/en-us/nuget/reference/nuspec#icon), and JPEG icons are correctly displayed on nuget.org, but Visual Studio Package Manager UI does not seem to be able to display JPEG icons.

### nuget.org

![Screenshot nuget.org](https://user-images.githubusercontent.com/177608/128745545-bf2b12a9-4587-4f2e-8cc0-b0c86c52d1a2.png)

### Visual Studio Package Manager UI

![Screenshot Visual Studio NuGet Package Manager UI](https://raw.githubusercontent.com/augustoproiete-repros/visual-studio-does-not-display-jpeg-icons-of-nuget-packages/master/asset/nuget-package-jpeg-icon-vs-npm-ui.png)

### Example packages

- [PackageWithJpegIconEmbedded](https://www.nuget.org/packages/PackageWithJpegIconEmbedded/)
- [PackageWithJpegIconUrl](https://www.nuget.org/packages/PackageWithJpegIconUrl/)

### Example packages source

https://github.com/augustoproiete-repros/visual-studio-does-not-display-jpeg-icons-of-nuget-packages

**Comment by erdembayar** [comment]
@aortiz-msft 
I just verified this, jpeg icons default to no icon one. Looks like recent regression, at least it was working on VS 16.6.4.

**Comment by aortiz-msft** [comment]
@dominoFire  - we need to fix this sprint.

**Comment by dominoFire** [comment]
@augustoproiete Thanks for filing this bug. 

By using WICExplorer, it seems the icon was created with paint.net; sometimes, Windows WIC codecs have problems understanding JPEG images if those are created with custom JPEG logic.

Cand you try exporting your image using other image manipulation software?

![image](https://user-images.githubusercontent.com/1192347/130726275-3249d5e6-3674-4f6e-b69f-e316472dd0a1.png)

**Comment by dominoFire** [comment]
Inner stacktrace when loading the icon image in NuGet PM UI:

```
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at NuGet.PackageManagement.UI.PackageItemViewModel.FinalizeBitmapImage(BitmapImage iconBitmapImage) in C:\src\NuGet.Client.PR\src\NuGet.Clients\NuGet.PackageManagement.UI\ViewModels\PackageItemViewModel.cs:line 615
   at NuGet.PackageManagement.UI.PackageItemViewModel.<FetchIconAsync>d__129.MoveNext() in C:\src\NuGet.Client.PR\src\NuGet.Clients\NuGet.PackageManagement.UI\ViewModels\PackageItemViewModel.cs:line 568
```

**Comment by dominoFire** [comment]
HRESULT: 0x88982f61

**Comment by augustoproiete** [comment]
@dominoFire I created a couple of variants of the NuGet packages above using a JPEG icon image exported using Microsoft Paint. It didn't seem to make a difference (i.e. NuGet PM UI also doesn't show the icon):

![image](https://user-images.githubusercontent.com/177608/130820028-308c61a4-cbdf-4ca8-afba-a98c55fc7e4a.png)

- [PackageWithMSPaintJpegIconEmbedded](https://www.nuget.org/packages/PackageWithMSPaintJpegIconEmbedded/)
- [PackageWithMSPaintJpegIconUrl](https://www.nuget.org/packages/PackageWithMSPaintJpegIconUrl/)

---

Here is the source `png` file I used to export as `jpeg` with both Microsoft Paint and Paint.net:

![774688_jpg_document_extension_file_format_icon](https://user-images.githubusercontent.com/177608/130820893-97fb8086-68fd-48e1-8393-e7780603bba4.png)

**Comment by dominoFire** [comment]
@augustoproiete  Thanks for creating those packages. That helped me track down a corner case in package icons in NuGet. A fix is in progress
