### ISSUE TITLE
PosixUMask is called 2 times

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11148]
This is follow up issue for comment https://github.com/NuGet/NuGet.Client/pull/4178#discussion_r688002427

**Comment by zivkan** [comment]
https://github.com/NuGet/NuGet.Client/blob/b58613fbc338b8e142d29b3bdb74e92a83a259fb/src/NuGet.Core/NuGet.Packaging/NuGetExtractionFileIO.cs#L143-L146

**Comment by zkat** [comment]
working as designed.
