### ISSUE TITLE
[Bug]: ContentItemCollection BestItemGroup returning a wrong value for a unsupported rid for a tfm

### ISSUE THREAD

**Issue by Anipik** [NuGet/Home#11146]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

```c#
using NuGet.Client;
using NuGet.ContentModel;
using NuGet.Frameworks;
using NuGet.Packaging.Core;
using NuGet.RuntimeModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ConsoleApp36
{
    class Program
    {
        private static ContentItemCollection _packageAssets = new();
        private static ManagedCodeConventions _conventions;
        static void Main(string[] args)
        {
            string[] filePaths = new[]
            {
                @"lib/net461/TestPackage.dll",
                @"runtimes/unix/lib/netstandard2.0/TestPackage.dll",
            };
            _packageAssets.Load(filePaths);

            _conventions = new ManagedCodeConventions(JsonRuntimeFormat.ReadRuntimeGraph(@"C:\git\sdk\artifacts\bin\redist\Debug\dotnet\sdk\6.0.100-dev\RuntimeIdentifierGraph.json"));
            SelectionCriteria managedCriteria = _conventions.Criteria.ForFrameworkAndRuntime(FrameworkConstants.CommonFrameworks.Net461, "unix");
            var t = _packageAssets.FindBestItemGroup(managedCriteria,
                _conventions.Patterns.RuntimeAssemblies)?.Items.FirstOrDefault();
            Console.WriteLine(t.Path);
        }
    }
}

```

I got the netstandard2.0 itemgroup instead the the returned value should be null.

cc @ericstj @viktorHofer

**Comment by nkolev92** [comment]
net461 is considered compatible with netstandard2.0, https://nugettools.azurewebsites.net/5.10.0-preview.2.7185/framework-compatibility?project=net461&package=netstandard2.0.

**Comment by safern** [comment]
@nkolev92 but is the `unix` runtime supported by `net461`? Note that the ns2.0 asset is under `runtimes/unix/netstandard2.0`

**Comment by nkolev92** [comment]
There's no mapping between frameworks and rids in nuget. 
The SDK/MSBuild would normally validate that.

**Comment by zivkan** [comment]
Also, the code sample in the repro steps above explicitly specified unix: `_conventions.Criteria.ForFrameworkAndRuntime(FrameworkConstants.CommonFrameworks.Net461, "unix");`
