### ISSUE TITLE
[Feature]: Make namespace mode configurable through NuGet.Config file

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11150]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### The Elevator Pitch

Child of https://github.com/NuGet/Home/issues/10729

**Comment by nkolev92** [comment]
Adding a trick label to avoid this issue showing up in release notes.
