### ISSUE TITLE
[Bug]: Indicate Developer PowerShell for Visual Studio in contributing documentation

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#11151]
### NuGet Product Used

NuGet.exe

### Product Version

documentation

### Impact

Other

### Repro Steps & Context

https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md indicates using PowerShell, and would do better to indicate using Developer PowerShell for Visual Studio.

**Comment by zivkan** [comment]
It doesn't need to be Developer PowerShell. If msbuild can't be found on the path it uses vswhere to locate it: https://github.com/NuGet/NuGet.Client/blob/cb290a427545a9214f22d9d6196c9e3c81380611/build/common.ps1#L309
