### ISSUE TITLE
[Bug]: wrong package version is installed

### ISSUE THREAD

**Issue by vadi2** [NuGet/Home#11153]
### NuGet Product Used

dotnet.exe

### Product Version

5.0.400

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I'd like to continuously publish a pre-release version of my package to nuget for easier testing. However, I don't want `#-rc` to litter my package package, so I chose to continuously update `0.0.1-rc` instead. While the package publishes [just fine](https://www.nuget.org/packages/Hammer/0.0.1-rc):

![image](https://user-images.githubusercontent.com/110988/129339054-301f1f59-b289-4d7d-a746-7d3347935b31.png)

Installing using the provided command is not working:

```
$ dotnet tool install --global Hammer --version 0.0.1-rc
warning NU1603: restore depends on Hammer (>= 0.0.1-rc) but Hammer 0.0.1-rc was not found. An approximate best match of Hammer 0.0.2 was resolved.
You can invoke the tool using the following command: hammer
Tool 'hammer' (version '0.0.2') was successfully installed.
```

**Comment by erdembayar** [comment]
Thank you for filing this issue.
This issue didn't repro for me.

![image](https://user-images.githubusercontent.com/8766776/129424929-d2a372d3-bd81-4444-b9d2-46e09adb161a.png)

Could you able to try on another machine or check your setup?

**Comment by vadi2** [comment]
Hm, it did work on another machine. Thank you.
