### ISSUE TITLE
[DCR]: Remove message suggesting Bower for packages that are only compatible with ASP.NET since Bower is deprecated

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#11155]
### NuGet Product(s) Affected

Visual Studio Package Management UI

### Current Behavior

Some packages like JQuery will show a message on the package list item that says it's not compatible with the given project and suggests to user Bower instead.

This happens for any project that is not ASP.NET packages.config. JQuery isn't compatible with any PackageReference project.

### Desired Behavior

Remove the message as Bower is deprecated. ASP.NET Core has been around long enough for users to understand that JQuery isn't compatible with it and have likely adopted alternatives.

**Comment by chrisraygill** [comment]
cc @anangaur @sayedihashimi @donnie-msft @dominoFire

**Comment by donnie-msft** [comment]
Looks like a dupe of https://github.com/NuGet/Home/issues/6623

**Comment by anangaur** [comment]
This one seems specific while the one linked seems more generic and talks about removing the extensibility altogether. For this issue I am not sure though if we have the code to show bower. It might as well be done from another team using the extensibility?

**Comment by chrisraygill** [comment]
@donnie-msft @nkolev92 is there anything else except Bower using the extensibility? If there's not reason we should keep the extensibility, then I'll close this issue in favor of [#6623](https://github.com/NuGet/Home/issues/6623).

**Comment by nkolev92** [comment]
As far as I'm aware only Bower uses this.

**Comment by donnie-msft** [comment]
The Bower message is owned by the Web Tools code, so I've filed https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1371990
