### ISSUE TITLE
[Bug]: Use `$(SolutionDir)` on packages.config paths in project files instead of relative path (`"..\packages"`)

### ISSUE THREAD

**Issue by agtekbuild** [NuGet/Home#11161]
[NuGetTest.zip](https://github.com/NuGet/Home/files/7041608/NuGetTest.zip)
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio Professional 2019 version 16.10.4

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1) Create a C++ WinRT Windows Runtime Component in it's own project and solution.
2) Create a C++ WinRT or C# consumer of the Component created in step 1 as a separate project and solution
        * We want to be able to debug our Windows Runtime Component so it is added as a project to this solution.
        * We will need to Reference the Windows Runtime Component from the project that consumes it.
3) Clean out everything that is generated in both solutions (This is what we push to Git)
4) Now build the solution created in step 2.  You will notice that NuGet attempt to grab the CPPWinRT package for the referenced project and then it grabs it for the project/solution you are building.  Unfortunately when the reference project builds it fails because it can't access the CPPWinRT NuGet package in ../packages or packages.  It is not there since the referenced component project still sits in the directory it was created in and not in the current solution directory.

An update which would solve this problem is to assume that components will be developed and built separately in their own Solutions and projects (Directories).  Since they are consumed at least for debugging at higher levels as projects the "package" location needs to be in the $(SolutionDir), not in "../projects" or "projects".  Relative paths are great but not here.  I have manually updated the .csproj files to add this and it works fine.  Problem is that NuGet messes things up next time it updates packages.

**Comment by nkolev92** [comment]
Hey @agtekbuild 

We really appreciate the time you took to write this issue, but I'm not sure I follow what the problem is. 

Would be able to provide a sample repo/attachment with the minimum setup?

**Comment by agtekbuild** [comment]
Hi, 

I attached a zip file that contains an example.  There is a Readme at the top level that explains how to recreate the issue.  I also added the following repo with the same example:  https://github.com/agtek/NuGetTest.git  

Please let me know if you have any additional questions.

**Comment by nkolev92** [comment]
@kartheekp-ms as hot seat, can you please take a look at this issue.

**Comment by aortiz-msft** [comment]
Thanks for the feedback. This is currently not a supported scenario. Is there a reason why you can't have both projects on the same solution? Alternatively , you could write a script that runs restore with nuget.exe on both projects before trying to build from Visual Studio.

**Comment by agtekbuild** [comment]
Yes there is a reason to have projects shared across multiple solutions.  We have Windows Runtime Components which implement functionality which is shared across solutions.  These components are implemented as stand-alone components and we create a solution which holds the actual component project along with unit tests and example projects.  When an application solution consumes these components projects we add them to the application solution, but they still live in their own directory tree.  We don't copy them into the application solution.  This seems like it would be a typical development style for a team developing larger applications using WinRT Components.  I described what seems to be a pretty simple solution to the, but apparently the thinking is to only support small development efforts out of the box.  Yes I can write scripting, but why should I have to?

**Comment by zivkan** [comment]
> I described what seems to be a pretty simple solution

`$(SolutionDir)` is only defined by MSBuild when restoring a solution file. Some customers restore projects individually (I don't know why), so changing NuGet to use this would break them. So unfortunately the solution to this problem isn't as simple as your proposal, though I wish it was.

**Comment by agtekbuild** [comment]
Would it be possible to supply a user selected item in there?  I am not suggesting changing it as the default.
