### ISSUE TITLE
[Feature]: Ability to reuse the package migrator tool outside of Visual Studio

### ISSUE THREAD

**Issue by KSchlobohm** [NuGet/Home#11175]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

One of the steps that the  `upgrade-assistant` tool performs is to review the NuGet dependencies in my project and then remove my transitive dependencies while converting from .NET Framework to SDK style projects with PackageReference restore.

It would be best if both the Package Migrator tool ([ref](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)) and `upgrade-assistant` behaved the same way when deciding which packages are transitive by using the same code/feature.

### Additional Context and Details

Consistent behavior between the two tools will improve customer's upgrade experience. Improvements in one area should benefit both experiences.

**Comment by nkolev92** [comment]
I just found that we have an ask from Taylor around this topic: https://github.com/NuGet/Home/issues/9514
