### ISSUE TITLE
[Cross-platform Dotnet Nuget Sign] Unexpected warning “NU3018: UntrustedRoot: self signed certificate” shows when signing/verifying with Dotnet Nuget Sign Command on Linux

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11171]
## Details about Problem
NuGet version: NuGet Client Dev\6.0.0.204
VS Version: Main\31617.326
OS: Windows-10-Enterprise-21H1
Linux OS; Ubuntu Server 18.04 LTS
## Detailed repro steps
1.	Git clone https://github.com/NuGet/Entropy.git to Windows VM.
2.	Copy the “SDKPatchTool” folder from https://github.com/NuGet/Entropy.git to the desktop of Linux VM.
3.	Copy the “Nupkgs” folder of the NuGet build to the desktop of Linux VM.
4.	Go to the “SDKPatchTool” folder on Linux, and edit the paths in the “patchOnUnix.ps1”.
5.	Open a bash on Linux, cd to the “SDKPatchTool” folder path and run “patchOnUnix.ps1” script: `./patchOnUnix.ps1`.
6.	On Windows VM, create a C# Class Library (.NET 6.0) project and pack it with command `dotnet pack`.
7.	On Windows VM, cd to <path_to_Entropy>\TestCertGenerator and create a new test certificate:  `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` in powershell.
8.	Copy the “*.nupkg” file (created in step6), “.cer” file and the “.pfx” file from the above Windows machine to Linux machine. 
9.	Change the .cer to .crt format: `openssl x509 -inform DER -in <.cer file path> -out <.crt file path>` on Linux
10.	Add the certificate(.crt) to trusted store on Linux:  
```
      cd /usr/local/share/ca-certificates/ 
      sudo cp <.crt file path>  ./ 
      sudo chmod 644 ./<.crt file name> 
      sudo update-ca-certificates 
```
11.	Run `./dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath>  --certificate-password password -v n` on Linux.
12.	Verify the correct certificate was used with the command `./dotnet nuget verify <PackageFilePath> -v d` on Linux.
## Expected Result
There were no errors or warnings (except for warning NU3002 if you didn't use: "--timestamper").
## Actual Result
Unexpected warning “NU3018: UntrustedRoot: self signed certificate” shows when signing (in step11) /verifying (in step12) as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/130205763-8b619389-05a5-481f-86e4-5b5004417522.png)
## Notes:
1.It is not a regression since it’s a new feature.
2.It only repros on Linux, doesn’t repro on Windows/Mac.
3.It repros on below cases:
   Dotnet nuget sign command:  sign an unsigned package
   Dotnet nuget sign command:  sign an already signed package without overwriting
   Dotnet nuget sign command:  sign when certificate is not valid for code signing
   Dotnet nuget sign command:  sign when certificate is expired
   Dotnet nuget sign command:  sign with non-default output directory

**Comment by heng-liu** [comment]
Hi @v-luzh , when I tried to repro one of the cases "Dotnet nuget sign command: sign an unsigned package" on Linux, I didn't see the warning of “NU3018: UntrustedRoot: self signed certificate”.
![image](https://user-images.githubusercontent.com/45407901/130300206-fa1d2e74-103f-4040-8eb6-ae5e36732310.png)

Could you try again and do the following checking after `step10. Add the certificate(.crt) to trusted store on Linux`? Thanks!
Run` openssl verify -verbose <crt file path>`.
If you see `<crt file path>: OK`, it means the certificate is added successfully to trusted store.
If you see 
```
error 18 at 0 depth lookup: self signed certificate
error <crt file path>: verification failed
```
It means the certificate is not added to trusted store.

BTW, I could see the following after running the last command of step10: `sudo update-ca-certificates`:
```
Importing into legacy system store:
Certificate added: CN=Test certificate for testing NuGet package signing
1 new root certificates were added to your trust store.
Import process completed.

Importing into BTLS system store:
I already trust 131, your new list has 130
Certificate added: CN=Test certificate for testing NuGet package signing
1 new root certificates were added to your trust store.
Import process completed.
Done
done.
```

If none of above works correctly from your side, could you let me know the OS and version of Linux? Thanks!

**Comment by v-luzh** [comment]
Hi @heng-liu, I can repro this bug again. Yes, the certificate is not added to trusted store. Please refer to below logs.
```
jamie@Linux:~/Desktop/PatchedSDK$ openssl x509 -inform DER -in /home/jamie/Desktop/CerFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.cer -out /home/jamie/Desktop/CrtFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.crt
jamie@Linux:~/Desktop/PatchedSDK$ 
jamie@Linux:~/Desktop/PatchedSDK$ cd /usr/local/share/ca-certificates/
jamie@Linux:/usr/local/share/ca-certificates$ sudo cp /home/jamie/Desktop/CrtFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.crt ./
jamie@Linux:/usr/local/share/ca-certificates$ sudo chmod 644 ./FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.crt
jamie@Linux:/usr/local/share/ca-certificates$ sudo update-ca-certificates
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
jamie@Linux:/usr/local/share/ca-certificates$ openssl verify -verbose /home/jamie/Desktop/CrtFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.crt
CN = Test certificate for testing NuGet package signing
error 18 at 0 depth lookup: self signed certificate
error /home/jamie/Desktop/CrtFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.crt: verification failed
jamie@Linux:/usr/local/share/ca-certificates$ cd /home/jamie/Desktop/PatchedSDK/jamie@Linux:~/Desktop/PatchedSDK$ ./dotnet nuget sign /home/jamie/Desktop/Packages/Package014.1.0.0.nupkg --certificate-path /home/jamie/Desktop/PfxFiles/FE14F544C4ADCF32EF42D1C7063F1AB13A14404F.pfx --certificate-password password -v n
warn : NU3002: The '--timestamper' option was not provided. The signed package will not be timestamped. To learn more about this option, please visit https://docs.microsoft.com/dotnet/core/tools

Signing package(s) with certificate:
  Subject Name: CN=Test certificate for testing NuGet package signing
  SHA1 hash: FE14F544C4ADCF32EF42D1C7063F1AB13A14404F
  SHA256 hash: 8EB58F7C1E0EAF820C699E0CD35BF7A435611801BE2292D1C4D54544E3D9EB8A
  Issued by: CN=Test certificate for testing NuGet package signing
  Valid from: 08/23/2021 02:30:06 to 08/24/2021 02:30:06
warn : NU3018: UntrustedRoot: self signed certificate
Package(s) signed successfully.

```
And I could not see the logs as yours after running the last command of step10: sudo update-ca-certificates. Mine is as below.
```
Updating certificates in /etc/ssl/certs...
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```
My Linux OS; Ubuntu Server 18.04 LTS

**Comment by zkat** [comment]
@heng-liu assigning to you for now to make sure how much of a problem this is right now. Feel free to drop to pri2 if you think it's not as big an issue as it seems right now. :)

**Comment by heng-liu** [comment]
I think this is a testing issue.
I could add the certificate to trusted store and run the test successfully.
However, I'm not able to repro the issue (root cause is the certificate is not added to trusted store).
I'll work with @v-luzh offline to solve the issue of adding certificate to trusted store.

**Comment by v-luzh** [comment]
Workaround: add below steps after finishing every test case on Linux 
```
Cd /usr/local/share/ca-certificates/ 
ls 
sudo rm * 
sudo update-ca-certificates 
```

**Comment by heng-liu** [comment]
Great! Thanks @v-luzh !

**Comment by aortiz-msft** [comment]
@v-luzh - Are we okay with closing this issue? Not sure what's the next step here.

**Comment by v-luzh** [comment]
Hey,@aortiz-msft, I'm closing this bug as External.
