### ISSUE TITLE
There is no tooltip for the “install” button on the right of a package in "Browse" tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11189]
## Details about Problem
VS Version: D17.0\31616.261
NuGet Version: Dev\6.0.0.165
OS Version: Windows-10-Enterprise-20H2 with all languages
## Repro steps
1.Create a project [e.g. C# Console App (.NET Framework 4.8)] in VS.
2.Right-Click the project in the Solution Explorer and select the “Mange NuGet Packages…”
3.Go to “Browse” tab and select a package (e.g. Newtonsoft.Json).
4.Hover on the “install” button on the right of the package.
## Expected
There is tooltip for the “install” button.
## Actual
No tooltip for the “install” button as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/131118218-85ac50b6-651c-4e6a-be00-e6378f984980.png)
## Note
1.It is not a regression since it repros on VS 16.11 (D16.11\31605.320).
2.It just repro on "Browse" tab for the “Install” button, doesn’t repro on “Installed”/”Updates” tab.

**Comment by aortiz-msft** [comment]
@donnie-msft - This seems like low hanging fruit that might have been already fixed by one of your change. Would you please take a look?

**Comment by donnie-msft** [comment]
@aortiz-msft no, my change fixed the background color and did not involve the tooltip.

**Comment by donnie-msft** [comment]
I'm fairly certain this bug only happens with the package recommender. I've seen a `null` version while debugging other code, so I think the way it's populated it's not set in time for the tooltip to be created.
