### ISSUE TITLE
Why no CDN for nugetgallery.blob.core.windows.net?

### ISSUE THREAD

**Issue by markrendle** [NuGet/Home#1118]
`dnu install AWSSDK` with the v3 API just took over a minute to download the `nupkg` file directly from Blob Storage.

Can you perhaps point Azure CDN at the container to improve performance, both in terms of network distance and hitting the Azure Storage service limits?

**Comment by xavierdecoster** [comment]
We switched the DNX entry in https://api.nuget.org/v3/index.json to leverage the Azure CDN two days ago.

> {
"@id": "https://az320820.vo.msecnd.net/v3-flatcontainer/",
"@type": "PackageBaseAddress/3.0.0",
"comment": "Base URL of Azure storage where NuGet package registration info for DNX is stored"
}

The issue you are experiencing has to do with DNU client-side caching of the HTTP requests it makes.
See also: https://github.com/aspnet/dnx/issues/2401

Can you please try clearing the dnu cache on disk found at `%localappdata%\dnu\cache`?

**Comment by markrendle** [comment]
Awesome, that worked and it makes a HUGE difference to performance. Thanks :)

**Comment by xavierdecoster** [comment]
You're welcome! :tada:
