### ISSUE TITLE
[Bug]: String comparison approach used for Source and Namespaces is not consistent

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11182]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

VS 2022 P3

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Follow up regarding https://github.com/NuGet/NuGet.Client/pull/4212#discussion_r695943951

package source is using Ordinal comparison https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/Items/SourceItem.cs#L80 whereas namespace Item is using OrdinalIgnoreCase comparison https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/Items/PackageNamespacesSourceItem.cs#L211

there is another implementation for Package Source where keys are compared using `CurrentCultureIgnoreCase` approach. https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSource.cs#L148

**Comment by kartheekp-ms** [comment]
I created a simple `.NET Framework` project with below `nuget.config` file content.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="encyclopaedia" value="https://api.nuget.org/v3/index.json" />
    <add key="Encyclopaedia" value="https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

I executed following command on `nuget.exe v6.0.0-preview.3` version and the result makes me think that `Ordinal` comparison is in effect https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Settings/Items/SourceItem.cs#L80

``` log
nuget.exe  sources list 
Registered Sources:
  1.  encyclopaedia [Enabled]
      https://api.nuget.org/v3/index.json
```

**Comment by aortiz-msft** [comment]
Let's use OrdinalIgnoreCase comparison across the board.

**Comment by nkolev92** [comment]
Added an estimate for planning purposes. 

I think it should be a reasonable one (likely 1, but just in case, I put 2. Feel free to adjust @kartheekp-ms  )

**Comment by kartheekp-ms** [comment]
Load balancing this issue with @erdembayar.
