### ISSUE TITLE
[DCR]: namespace mode cannot be configured in NuGet.Config file

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11184]
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### Current Behavior

As per [spec](https://github.com/NuGet/Home/blob/dev/proposed/2021/PackageNamespaces.md#explanation), Users can configure package namespaces mode in the NuGet.Config file for different source pinning behaviors. There are following modes as per spec.
- `fullySpecified` - Any package id must be in one or more matching namespace declarations
- `singleSource` - No package id may match more than one feed (based on precedence rules)

Sample `NuGet.Config` file with namespace mode added is shown below.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="namespaceMode" value= "singleSourcePerPackage" />
    </config>
</configuration>
```
Users can also use the following `nuget.exe` command to add `namespaceMode` to the `NuGet.Config` file

### Desired Behavior

`namespaceMode` setting is not required any more. Revert commit https://github.com/nuget/home/issues/11150

**Comment by nkolev92** [comment]
Adding the engineering label so it doesn't show up in the release notes.
