### ISSUE TITLE
[Bug]: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" for older projects

### ISSUE THREAD

**Issue by tester346** [NuGet/Home#11180]
### NuGet Product Used

NuGet.exe

### Product Version

5.10.0.7240

### Worked before?

5.4.0.6315

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi,

I have old .NET 4.5 project that breaks at restore

>.\nuget.exe restore "C:\project\MyProject.sln"

	Nuget restore failed.
	Attempt:1
	args:'restore "C:\project\MyProject.sln"'
	MSBuild auto-detection: using msbuild version '4.8.3761.0 built by: NET48REL1' 
	from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.

	error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to ""
	instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\project\MyProject.csproj]

After downloading older version of `nuget.exe`, namely: `5.4.0.6315` it started working again.

That `5.4.0.6315` version I figured out by typing `$host` in Package Manager Console in Visual Studio 2019 16.4.4

	PM> $host
	Name             : Package Manager Host
	Version          : 5.4.0.6292

### Verbose Logs

```shell
.\nuget.exe restore "C:\project\MyProject.sln" -verbosity detailed


NuGet Version: 5.10.0.7240
MSBuild auto-detection: using msbuild version '4.8.3761.0 built by: NET48REL1' from 'C:\Windows\Microsoft.NET\Framework\
v4.0.30319'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000

C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe "C:\Users\User\AppData\Local\Temp\NuGetScratch\o1aobvih.klk.nugetinputs.targets" 

/t:GenerateRestoreGraphFile 
/nologo 
/nr:false 
/v:q 
/p:NuGetRestoreTargets="C:\Users\User\AppData\Local\Temp\NuGetScratch\feh1eall.nex.nugetrestore.targets" 
/p:RestoreUseCustomAfterTargets="True" 
/p:RestoreTaskAssemblyFile="F:\Test\App\nuget.exe" 
/p:RestoreSolutionDirectory="C:\project\\" 
/p:SolutionDir="C:\project\\" 
/p:SolutionName="MyProject" 
/p:RestoreBuildInParallel="False" 
/p:RestoreUseSkipNonexistentTargets="False"
C:\Users\User\AppData\Local\Temp\NuGetScratch\feh1eall.nex.nugetrestore.targets(460,20): 

error MSB4086: A numeric comparison was attempted on "$(MSBuildAssemblyVersion)" that evaluates to "" instead of a number, in condition "'$(MSBuildAssemblyVersion)' < '15.0'". [C:\project\MyProject.csproj]

NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown.
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__63.MoveNext()
```

**Comment by kartheekp-ms** [comment]
As per comment in MSBuild repo https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Tasks/Microsoft.Common.targets#L27-L28, `MSBuildAssemblyVersion is not defined in 4.X MSBuild.` I see from the error message that `4.8.3761.0` version of msbuild was used for restore.

What is the MSBuild version used when restore command was executed with `nuget.exe version 5.4.0.6292`?  Can you please try `msbuid.exe -t:restore` https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-target ? If you have Visual Studio installed on the machine, can you please try executing restore from developer command prompt and see if it succeeds?

 If you are blocked still, please upload a repro so that we can investigate further.

**Comment by tester346** [comment]
Wow, `msbuild.exe "Path" -t:restore` managed to compile and restore my projects.

I had some troubles with getting it to work with `nuget.exe` because when I used nuget.exe `5.4.0.6315` then it couldnt handle `PackageReference`

but apparently I can get rid of nuget.exe and just use `msbuild.exe -t:restore` for everything

Thank you

**Comment by kartheekp-ms** [comment]
Closing this issue as per above comment.
