### ISSUE TITLE
[Localization] The title, tooltip of the warning icon, description and details of vulnerable package have not been localized on PM UI 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11194]
## Details about problem
VS Version: D17.0\31616.261
OS Version: Windows-10-Enterprise-21H1
## Installations
1. Install VS D17.0\31616.261 from:  
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5097037&view=ms.vss-build-web.run-extensions-tab
## Steps to reproduce
1. Create a new C# Console App (.Net Core) project and open PM UI.
2. Search vulnerable package (refer to GitHub Advisory Database) in Browse tab.
3. Select a vulnerable package (e.g. Microsoft.AspNetCore.Authentication.JwtBearer) and observe the information on the right panel.
4. Install the vulnerable package and observe the tooltip of the warning icon in Installed tab.
## Expected
The title, tooltip of the warning icon, description and details of vulnerable package should be localized.
## Actual
The title, tooltip of the warning icon, description and details of vulnerable package have not been localized as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/131304151-8ea2b868-d421-4c70-a95b-f79b2874847e.png)
![image](https://user-images.githubusercontent.com/40230425/131305230-2f7a55dc-d394-490a-bfa5-90db62bed03e.png)
## Notes
1. The issue reproes on all languages.
2. It is not a regression because it is a new feature.

**Comment by donnie-msft** [comment]
After a chat with @dominoFire, he believes there may be a backlog for the localization team. Please follow-up here and reassign as necessary.

**Comment by dominoFire** [comment]
Details pane appears localized:

![image.png](https://images.zenhubusercontent.com/5cac0ec5e63284773bff5eb7/47838973-2c95-44a6-ae94-7609f70421a9)

Tooltip in PM UI tabs appears unlocalized

![image.png](https://images.zenhubusercontent.com/5cac0ec5e63284773bff5eb7/dc21b618-6215-4f6b-9ea2-2ad9ed60d628)

**Comment by dominoFire** [comment]
Corresponding String resource Label_Installed_VulnerableAndDeprecatedWarning is localized:

https://github.com/NuGet/NuGet.Build.Localization/blob/e7189fde81534ca4dc50e96958db082ac313964c/localize/FRA/15/NuGet.PackageManagement.UI.dll.lcl#L1628

It was merged 4 days ago, at the time of this comment.

**Comment by dominoFire** [comment]
A new version was inserted. @v-longmin would you please take another look? Thanks!

**Comment by dominoFire** [comment]
lastes build shows the tooltip localized:
![image](https://user-images.githubusercontent.com/1192347/134077270-8541c75c-cd5b-40be-b404-ffed7e6d0d8c.png)

![image](https://user-images.githubusercontent.com/1192347/134077406-a61dae06-56ed-47f6-a394-a6fc47389019.png)
