### ISSUE TITLE
[Localization] The tooltip of the deprecated package’s warning icon has not been localized on PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11195]
## Details about problem:
VS Version: D17.0\31616.261
OS Version: Windows-10-Enterprise-20h2

## Installation:
Install VS D17.0\31616.261 from:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5097037&view=ms.vss-build-web.run-extensions-tab

## Repro steps:  
1. Create a C# Console App (.net core) project and open PM UI of the project.
2. Select package source: Nuget.org 
3. Search deprecated package "NuGet.Core" in Browse tab. 
4. Hover on the warning icon of the deprecated package “NuGet.Core” and observe the tooltip.
 
## Expected: 
The tooltip of the warning icon should be localized.

## Actual: 
The tooltip of the warning icon has not been localized as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/131308819-48ee04f1-ecc9-452f-8686-f910902c78da.png)

## Notes: 
1. The issue reproes on all languages.
2. It starts to repro from the new feature “Deprecated Package” merged.

**Comment by donnie-msft** [comment]
After a chat with @dominoFire, he believes there may be a backlog for the localization team. Please follow-up here and reassign as necessary.

**Comment by dominoFire** [comment]
It appears localized in spanish in Recent VS build:

![image.png](https://images.zenhubusercontent.com/5cac0ec5e63284773bff5eb7/d6dc38fa-441b-4813-9865-4336605ed33c)

![image.png](https://images.zenhubusercontent.com/5cac0ec5e63284773bff5eb7/8aad02d3-0b15-4593-8b66-34e58a30076c)

**Comment by dominoFire** [comment]
This commit contains all localized strings for tooltip:

https://github.com/NuGet/NuGet.Build.Localization/commit/f904c2ce603a69015081ef2feb0bc24513f37d62#diff-2a68c6ea49bcdf3c33c527be451b06e7efa6e5ce2904bcc3d6d3855a8d3b4e08

**Comment by dominoFire** [comment]
Localized string resource is Label_PackageSelectForInfoToolTip: https://github.com/NuGet/NuGet.Build.Localization/blob/e7189fde81534ca4dc50e96958db082ac313964c/localize/FRA/15/NuGet.PackageManagement.UI.dll.lcl#L1720

I will close the issue since all localized strings are present in all 13 languages.
