### ISSUE TITLE
--interactive switch not displaying device flow in version '6.0.100-preview.7.21379.14'

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#11202]
---
**Issue moved from dotnet/sdk#20332**
- Please respond to @fuocor.

---

_From @fuocor on Wednesday, August 25, 2021 3:23:17 PM_

`dotnet restore --interactive` or `dotnet tool restore --interactive` is not outputting the device flow information for authenticating.

it hangs for the 90 second timeout to elapse.

downgrading the global.json file to '5.0.300' works

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#20332**
- Please respond to @MihaZupan.

---

_From @MihaZupan on Monday, August 30, 2021 3:01:01 PM_

cc: @wli3

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#20332**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Monday, August 30, 2021 6:58:54 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by erdembayar** [comment]
@fuocor
I was not able to repro this issue, for me it restore finished successfully after some waiting. 
Please note if required packages are already in your global packages cache then it may not try to connect authenticated source feed?

First I cleared my local cache:
dotnet nuget locals all -c

![image](https://user-images.githubusercontent.com/8766776/132948293-7ae91b24-65be-4639-a775-59795d6dccdd.png)

Also once your cred provider already cached auth details then it doesn't trigger device flow in next try.
![image](https://user-images.githubusercontent.com/8766776/132948397-73bfbe88-2100-4208-be6d-0a336d9d8025.png)

Could you tell me which cred provider are you using?
Could you be able to provide log from `dotnet restore --interactive  --verbosity detailed`?

**Comment by aortiz-msft** [comment]
We were not able to repro the issue with the Azure Artifacts Credential Provider installed; hence, closing this bug. Please feel free to comment with more information.
