### ISSUE TITLE
Install, Update and Uninstall icons on the right of a package are invisible in PM UI 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11204]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.0.0.222

## Details about problem 

VS Version: Main\31630.363 

NuGet Version: Dev\6.0.0.222 

OS Version: Windows-10-Enterprise-21H1 

## Installations 

1. Install VS Main\31630.363 from:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5151123&view=results 

2. Install NuGet Dev\6.0.0.22 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5152056&view=results
 
## Steps to reproduce 

1. Create a new C# Console App (.Net Core) project and open PM UI. 

2. Go to “Browse” tab and observe the “Install” button on the right of a package. 

3. Install a package (e.g. Newtonsoft.Json) with not latest version and go to “Installed” tab. 

4. Observe the “Update” icon and “Uninstall” icon on the right of the package. 
## Expected 

Install, Update and Uninstall icons on the right of a package are visible. 

 

## Actual 

Install, Update and Uninstall icons on the right of a package are invisible as below screenshot. 
![image](https://user-images.githubusercontent.com/40230425/131468203-9de54ccf-388d-46b5-bce4-f108d3a81b7b.png)
## Note
1. The issue reproes on all themes.

**Comment by v-luzh** [comment]
After investigating, it seems a VS bug, it started to repro from VS Main\31626.357 (Merged PR 347116: Add offscreen property to standard footer).

**Comment by v-longmin** [comment]
We will track the issue on VSO 1390337, close it, thanks.

**Comment by donnie-msft** [comment]
Reopening for tracking.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1390337
