### ISSUE TITLE
[DCR]: Rename packageNamespaces feature to packageSourceMapping

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11205]
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### Current Behavior

Namespaces configuration currently can be configured as follows

``` xml
<packageNamespaces>
    <packageSource key="nuget.org">
      <namespace id="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <namespace id="Contoso.*" />
    </packageSource>
</packageNamespaces>
```

### Desired Behavior

Namespaces configuration should be as follows.

1. Rename `packageNamespaces` to `packageSourceMapping`
2. Rename `namespace` to `package`
3. Rename `id` to `pattern`

```xml
<packageSourceMapping>
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <packageSource key="contoso.com">
      <package pattern="Contoso.*" />
    </packageSource>
</packageSourceMapping>
```

**Comment by loic-sharma** [comment]
Just curious, why did we decide to rename these? Personally I slightly preferred the old names.
