### ISSUE TITLE
Rename types/variables in the product/test code to reflect new name for package namespaces feature

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11216]
As a follow up for https://github.com/NuGet/Home/issues/11205 issue and https://github.com/NuGet/NuGet.Client/pull/4234#pullrequestreview-743329652 comment, we must rename types/variables to reflect package source mapping instead of package namespaces.

**Comment by nkolev92** [comment]
Don't want it to show in the release notes, so marked it as a bug.
