### ISSUE TITLE
[Bug]: Very slow restore when using NoWarn in single project that has lots of dependents

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11222]
### NuGet Product Used

MSBuild.exe

### Product Version

16.11

### Impact

I'm unable to use this version

### Repro Steps & Context

When you have a large project tree with lots of transitive project references and packages, the calculation transitive NoWarn values takes forever.  This code is attempting to search through transitive references:

https://github.com/NuGet/NuGet.Client/blob/5df07c3271aebfbeb86269d59a98d1acc9996670/src/NuGet.Core/NuGet.Commands/RestoreCommand/Logging/TransitiveNoWarnUtils.cs#L163

But in the debugger I found the queue to contain _millions_ of items.  This causing a massive amount of allocations which leads to GC pressure and makes restore very slow.

![image](https://user-images.githubusercontent.com/17556515/132549969-f62a9d4d-45ea-4ca5-a13f-ca188b3f9f27.png)

### Workaround
Currently, the only way to work around the issue is to remove all `NoWarn` definitions in specific projects and instead specify them in a common import like `Directory.Build.props` so that every project has the exact same set of `NoWarn`.  This makes the code not need to walk through recursively to determine `NoWarn`.

**Comment by AAATechGuy** [comment]
likely facing similar issue here. 
```
    <NoWarn>NU1605</NoWarn>
```
After removing NoWarn from csproj, latency reduced from 1.2min to 5sec.
