### ISSUE TITLE
E2E tests that assert web.config binding redirects need to be fixed

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11223]
While testing E2E tests on new infrastrcture, the tests that validate binding redirects in ASP.NET project web.config files are not working. Due to time constraints, these tests are being skipped for now, but need to be fixed.

**Comment by erdembayar** [comment]
https://github.com/NuGet/NuGet.Client/blob/2c6141ab883f14c2dbb847b71c7d89d44a2f4fcb/test/EndToEnd/tests/InstallPackageTest.ps1#L802
