### ISSUE TITLE
[Bug]: Wildcard package reference causes "NU1004: The packages lock file is inconsistent" error in in locked mode

### ISSUE THREAD

**Issue by ilya-git** [NuGet/Home#11238]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet  5.0.401

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create 2 projects in net with these csproj files (one web and a class library that references web):

```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.*" />
    </ItemGroup>

</Project>
```

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>
    

    <ItemGroup>
      <ProjectReference Include="..\WebApplication\WebApplication.csproj" />
    </ItemGroup>

</Project>
```

2. Run `dotnet restore --force-evaluate`
3. Run `dotnet restore --locked-mode`
4. Error happens:

> C:\Source\Test\WebApplication1\ClassLibrary1\ClassLibrary1.csproj : error NU1004: The project references webapplication whose dependencies has changed.The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file. [C:\Source\Test\WebAppl ication1\WebApplication1.sln]

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8465
