### ISSUE TITLE
Add static index.html to dist.nuget.org

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1123]
Add index.html and index.json to dist.nuget.org. Currently, only beta version of nuget.exe has been exposed in dist.nuget.org. In the future, various artifacts will get exposed through dist.nuget.org. By then, we need add index.html and index.json

**Comment by pranavkm** [comment]
:+1:

**Comment by deepakaravindr** [comment]
This has been fixed. A static index.html has been checked into a private repository

**Comment by maartenba** [comment]
@deepakaravindr I have a default document rule working on the staging CDN, let me know when we want that rule on prod as well.

**Comment by yishaigalatzer** [comment]
Done

**Comment by pranavkm** [comment]
FYI - the default document rule isn't working as yet. https://dist.nuget.org/ produces an error from the blob store.

**Comment by yishaigalatzer** [comment]
Yes, I know the rule was not deployed to CDN
