### ISSUE TITLE
NuGet.targets incorrectly performs a url-decode on filesystem paths, resulting in projects not found

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#11247]
---
**Issue moved from dotnet/sdk#20901**
- Please respond to @stewartadam.

---

_From @stewartadam on Friday, September 10, 2021 5:29:50 PM_

### Describe the bug
NuGet.targets (or perhaps something that includes it in the msbuild stack) is incorrectly performing a URL-decode on filesystem paths, causing builds to fail due to projects not being found (because it's trying to access them with `folder name` of `folder%20name` as they exist on the filesystem).

This can happen easily by cloning a Azure DevOps repo whose project has spaces in its name, as DevOps provide the clone URL with %20 characters in it.

### To Reproduce
```sh
mkdir -p ~/git/Backend%20Endpoints
cd ~/git/Backend%20Endpoints
dotnet new console
dotnet build -v d
```

### Exceptions (if any)
```
Microsoft (R) Build Engine version 16.11.0+0538acc04 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/usr/local/share/dotnet/sdk/5.0.400/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file '/Users/stewartadam/git/Backend Endpoints/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/Users/stewartadam/git/Backend%20Endpoints/Backend%20Endpoints.csproj]

Build FAILED.
```

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: N/A

```sh
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.400/

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [/usr/local/share/dotnet/sdk]
  5.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#20901**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Friday, September 10, 2021 5:29:53 PM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by wli3** [comment]
---
**Issue moved from dotnet/sdk#20901**
- Please respond to @tessmichi.

---

_From @tessmichi on Friday, September 10, 2021 5:35:16 PM_

Additionally, when opening the .sln file into visual studio, the nuget packages can't be restored and no files get added to the solution. have not been able to find another workaround other than re-cloning into a folder with no spaces in the path

**Comment by aortiz-msft** [comment]
@kartheekp-ms - Does this issue get resolved by the change you have In Review?

**Comment by kartheekp-ms** [comment]
@aortiz-msft - I think the bug is in SDK or MSBuild logic.

https://github.com/dotnet/sdk/blob/b6bbe16dc12c3bc394ac58b72eefd7d5a7c068c9/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.PackageDependencyResolution.targets#L24

Project assets file path is normalized using MSBuild `NormalizePath` property function which I think is causing this issue.

Here is the repro steps
- Create a folder with name `Backend%20Endpoints`
- Add an MSBuild `.proj` file to the folder with below content
``` xml
<Project>
    <Target Name="TestNormalize">
        <PropertyGroup>
            <Dir1>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)'))</Dir1>
        </PropertyGroup>
        
        <Message Text="$(Dir1)" Importance="High" />
    </Target>
</Project>
```
- Navigate to the new folder in the command prompt
- Run the MSBuild project file
- From the log below, we can observe that `TestNormalize` target printed `C:\repos\Backend Endpoints\` to the console (no `%20` in the path).
``` log
C:\repos\Backend%20Endpoints>msbuild normalizepath.proj
Microsoft (R) Build Engine version 17.0.0-preview-21460-01+8f208e609 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/20/2021 2:11:11 PM.
Project "C:\repos\Backend%20Endpoints\normalizepath.proj" on node 1 (default targets).
TestNormalize:
  C:\repos\Backend Endpoints\

Done Building Project "C:\repos\Backend%20Endpoints\normalizepath.proj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)
```
@nkolev92 - I am new to `NuGet.targets` file code. Please let me know if I missed anything while investigating this issue.

**Comment by nkolev92** [comment]
Analysis seems spot on @kartheekp-ms. 

Closing this and reopening the dotnet/sdk issue.

**Comment by Nirmal4G** [comment]
Seems to be an <https://github.com/dotnet/msbuild> issue! The root of the problem is in Azure DevOps as it should handle the names with spaces without issues but in this case, MSBuild directory functions should not decode file-system paths unless the scheme starts with `file:`.
