### ISSUE TITLE
[Bug]: `dotnet tool restore` does not supply X-NuGet-APIKey header with GET requests

### ISSUE THREAD

**Issue by nathan-alden-hp** [NuGet/Home#11246]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 5.0.400

### Worked before?

No.

### Impact

I'm unable to use this version

### Repro Steps & Context

I have a repo containing a Visual Studio solution with several .NET 5 class libraries. Corporate policy dictates that I use my employer's internal Nexus server as a nuget.org proxy. Recently, I started work on changing my nuget.org source URLs over to our internal Nexus server. Unfortunately, I quickly ran into a showstopper: It appears that some `dotnet` CLI commands do not supply the `X-NuGet-APIKey` header that Nexus requires for authorization in its NuGet APIs.

I had thought that adding the API key to my solution's `nuget.config` file would solve the issue, so I first ran this command:

```
nuget.exe setapikey "redacted-apikey" -Source https://redacted/repository/nuget.org-proxy/ -Verbosity detailed -NonInteractive -ConfigFile nuget.config
```

After running this command I can see that my `nuget.config` file has the requisite API key added:

```
  <apikeys>
    <add key="https://redacted/repository/nuget.org-proxy/" value="redacted-encrypted-apikey" />
  </apikeys>
```

In my case, I am trying to use the `dotnet-sonarscanner` .NET tool. I attempt to restore the .NET tool like this:

```
dotnet tool restore --configfile nuget.config --verbosity detailed
```

Unfortunately, the tool reports a 401 Unauthorized response from the server:

```
       "D:\Users\alden\AppData\Local\Temp\u23lojut.tlj\restore.csproj" (Restore target) (1) ->
       (Restore target) -> 
         C:\Program Files\dotnet\sdk\5.0.400\NuGet.targets(131,5): error : Failed to retrieve information about 'dotnet-sonarscanner' from remote source 'https://redacted/repository/nuget.org-proxy/FindPackagesById()?id='dotnet-sonarscanner'&semVerLevel=2.0.0'. [D:\Users\alden\AppData\Local\Temp\u23lojut.tlj\restore.csproj]
       C:\Program Files\dotnet\sdk\5.0.400\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [D:\Users\alden\AppData\Local\Temp\u23lojut.tlj\restore.csproj]
```

I decided to run Fiddler with HTTPS decryption turned on. Sure enough, there is no `X-NuGet-APIKey` header present when the server is contacted:

![image](https://user-images.githubusercontent.com/40613229/133850252-24c9758c-1657-4ba4-a343-bc92418e038f.png)

If I use Fiddler to rerun the same request with an `X-NuGet-APIKey` header provided, it works as expected.

This is a critical missing capability. API keys are the recommended way for automation to interact with NuGet repositories. Our Nexus installation requires them. I have been unable to find a workaround. I did find [another issue](https://github.com/NuGet/Home/issues/1945) from several years ago that was closed with a snarky response.

There are likely other interactions with NuGet through `dotnet` that do not supply `X-NuGet-APIKey`. I'm requesting that all `dotnet` NuGet requests provide `X-NuGet-APIKey` if a key is specified as shown above.

**Comment by nkolev92** [comment]
API keys are not used for restore, https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-setapikey#usage, https://github.com/NuGet/Home/issues/4049

Follow up docs issue to clarify more scenarios: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2205
