### ISSUE TITLE
All restores fail with NU3037: "The repository countersignature validity period has expired"

### ISSUE THREAD

**Issue by akilhoffer** [NuGet/Home#11240]
I'm unable to perform a restore on any of our .Net projects. I receive NU3037: error that states "The repository countersignature validity period has expired". 

Full error details:

/Users/x/code/xx/Data/xxxx.csproj : warning NU3028: Package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. [/Users/x/code/xx/xxx.sln]
/Users/x/code/xx/Data/xxxx.csproj : error NU3037: Package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired. [/Users/x/code/xx/xxx.sln]

**Comment by aortiz-msft** [comment]
Hi, could you please use one of our issue templates to report the problem? We suspect you are using an older version of NET 5.0 on Linux or Mac and hitting a known issue: https://devblogs.microsoft.com/nuget/net-5-nuget-restore-failures-on-linux-distributions-using-nss-or-ca-certificates/
