### ISSUE TITLE
[Bug]: No indication that the Nuget.config file has a parsing error when opening the Package Sources view

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11248]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.0.0.222

### Impact

It bothers me. A fix would be nice

## Installation
1. Install VS Main\31716.326 from:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5215765&view=results
2. Install NuGet Client Dev\6.0.0.252 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5216452&view=artifacts&pathAsName=false&type=publishedArtifacts 
## Steps to reproduce
1. Create a new C# WPF Application project and close the solution.
2. Create a NuGet.Config file having below parsing errors next to the .sln file
  <?xml version="1.0" encoding="utf-8"?>
                <configuration>
                  <packageSources>
                    <clear />
                    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
                    <add key="NuGetVolatile" value="https://dotnet.myget.org/F/nuget-volatile/api/v3/index.json" />
                    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
                    <add key="dotnet-buildtools" value="https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" />
                    <add key="dotnet-roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
                    <add key="cps" value="https://vside.myget.org/F/devcore/api/v3/index.json" />
                    <add key="dotnet-msbuild" blalblasda="https://dotnet.myget.org/F/msbuild/api/v3/index.json" />
                  </packageSources>
                  <disabledPackageSources>
                    <clear />
                  </disabledPackageSources>
               </configuration>
3. Reload the solution.
4. Open the PM UI and observe the Package Source combo box.
 
## Expected
Available package sources should be appeared on the package sources list.
## Actual
The package sources list is empty as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/133868610-95b2ffe5-4c3f-4241-aa58-0cc6255317c5.png)

**Comment by v-luzh** [comment]
It repro on 16.11. So it seems not a regression issue.

**Comment by nkolev92** [comment]
To my knowledge, this behavior is as expected, as if a config has parsing errors, NuGet can't really reliably detect the sources. 

So the question would be whether NuGet has shown to the user in any way that there is a parsing problem. 

@v-luzh 

Does NuGet log anything in the output window?

**Comment by zivkan** [comment]
Even if the behavior of not listing the sources is expected, I think we should have a yellow bar, or a fake entry, that says "invalid xml file c:\src\repo\nuget.config. Unable to display sources".

Which might be hard to implement as long as this page is WinForms, but I'd expect to be significantly easier if we port it to WPF.

**Comment by nkolev92** [comment]
>  I think we should have a yellow bar, or a fake entry, that says "invalid xml file c:\src\repo\nuget.config. Unable to display sources".

That's what my comment suggests. 

I'm not suggesting a particular implementation, rather whether there's an indication of any issues right now.

**Comment by nkolev92** [comment]
@v-luzh Making sure you see this. 

Thanks!

**Comment by v-luzh** [comment]
Hi @nkolev92, Here is the only info I get from Output window when reloading the solution(verified on Main\31729.143 + NuGet Client Dev\6.0.0.268 with Windows11). So we think NuGet has **not** shown to the user that there is a parsing problem.
`Failed to remove package directories that were marked for deletion on Visual Studio restart: Expected 1 export(s) with contract name "System.IServiceProvider" but found 0 after applying applicable constraints.`

**Comment by nkolev92** [comment]
Thanks @v-luzh 

Pushing back to triage because while the empty is expected, NuGet should indicate to the user that there are problems.

**Comment by zkat** [comment]
@chgill-MSFT hey Chris. Could you help us design the right UX for this particular scenario?

**Comment by chrisraygill** [comment]
Tested this in VS 17.0 int preview 6 and when I reload the solution I get a pretty descriptive error pop up:

![image](https://user-images.githubusercontent.com/15097183/138001445-417aa757-e016-4e54-92b4-67d5d37f0cad.png)

@zkat am I missing something?

**Comment by zkat** [comment]
that looks pretty good to me. @v-luzh ?

**Comment by v-luzh** [comment]
Yes, so this issue is fixed on Main\31820.317 + NuGet Client Dev\6.1.0.30. Close this bug now, thanks.
