### ISSUE TITLE
Update-Package doesnt respect package name

### ISSUE THREAD

**Issue by shahriar-gholami** [NuGet/Home#1124]
Just upgraded to vs2015 and nuget 3.1.1.0
running
```
Update-Package packageName -Reinstall -IgnoreDependencies
```
command in package manager console causes all packages to reinstall

**Comment by yishaigalatzer** [comment]
@zhili1208 please take a look. This is something we regularly test, if its broken indeed please move it to the 3.1.2 milestone to be fixed immediately.

**Comment by zhili1208** [comment]
Duplicate issue. already have it in https://github.com/NuGet/Home/issues/737
