### ISSUE TITLE
Nuget package manager update 3.1.1.0 broken

### ISSUE THREAD

**Issue by shmao** [NuGet/Home#1125]
Quoting from [this Stackoverflow post](http://stackoverflow.com/questions/31770339/nuget-package-manager-update-3-1-1-0-broken/31826795):
> I updated Nuget package manager to version 3.1.1.0. After the update opening any project gives me the error message: copy-item: cannot find path 'c:\users{username}\documents\visual studio 2015\projects{project name}\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\tools\lib\net45' because it does not exist ..... in file init.ps1

> I found $installpath variable given to init.ps1 differs from old nuget to actual in additionally appended \tools subdirectory name, which is obviously wrong and gives the error.

> I double-checked this behaviour also in a fresh installed vm with the same result, VS installed -> ok, update to nuget 3.1.1 -> broken.

> Environment: Windows 10 German, Visual Studio 2015 Community Edition English

**Comment by yishaigalatzer** [comment]
This package needs to move off init.ps1, regardlesss this looks like a valid concern.

**Comment by yishaigalatzer** [comment]
Verified this does **not** repro in Visual Studio 2013

**Comment by zhili1208** [comment]
Verified this does not repro on Visual studio 2013, this bug only happens during Powershell console initialization, so function test can't hit this bug, only UI can hit this. we might can add a test to manual verification

**Comment by deepakaravindr** [comment]
Did the following for verification
1. Created a project and installed Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0 on it.
2. Closed PMC if it was open and closed VS
3. Re-opened VS and opened the solution created in Step-1
4. Deleted files Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll and the xml from <ProjectRoot>\bin if present. Note that init.ps1 from the package in question should add these files to <ProjectRoot>\bin folder after execution
5. Opened Package Manager Console and let it complete initialization
6. Verified that files Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll and the xml are created back in <ProjectRoot>\bin folder indicating that init.ps1 ran successfully
