### ISSUE TITLE
[Bug]: Running dotnet restore on a mac started to fail with NU3037

### ISSUE THREAD

**Issue by akorchev** [NuGet/Home#11255]
### NuGet Product Used

dotnet.exe

### Product Version

5.0.101

### Worked before?

5.0.101

### Impact

I'm unable to use this version

### Repro Steps & Context

Today all my .NET applications started to fail to restore on three different mac machines. Happens for every nuget package. Here is an excerpt:

```
warning NU3028: Package 'Microsoft.AspNetCore.Components.Analyzers 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny.

error NU3037: Package 'Microsoft.AspNetCore.Components.Analyzers 5.0.0' from source 'https://api.nuget.org/v3/index.json': The repository countersignature validity period has expired

```

It started for new packages (packages that were not in the cache). I've made the grave mistake to delete the cache (`rm -r ~/.nuget/`) and now all packages fail to restore.

**Comment by nkolev92** [comment]
Hey @akorchev 

Might be related to https://devblogs.microsoft.com/nuget/net-5-nuget-restore-failures-on-linux-distributions-using-nss-or-ca-certificates/. 

Can you try using a newer version of the 5.0 SDK, maybe v5.0.401?

**Comment by akorchev** [comment]
Hi @nkolev92,

Thank you for your reply! Installed v5.0.401 and this solved the problem. Restoring packages now works again!

**Comment by nkolev92** [comment]
Awesome, glad it fixed your problem!
