### ISSUE TITLE
Scenario: We have two projects ProjectA and ProjectB. ProjectA is dependent on some C++ libraries and is packed as nuget package. ProjectB is a .net5 class library and ProjectA nuget is added in ProjectB.  Then we create ProjectB  nuget package.

### ISSUE THREAD

**Issue by Proxima89** [NuGet/Home#11254]
Scenario: We have two projects ProjectA and ProjectB. ProjectA is dependent on some C++ libraries and is packed as nuget package. ProjectB is a .net5 class library and ProjectA nuget is added in ProjectB.  Then we create ProjectB  nuget package.
Now if we craete a Console application and add ProjectB nuget, the code complies Ok. When we expand the dependencies section we can see ProjectA under ProjectB, everything looks good. When we run the console application, we get Class not registered error.
The application works fine if we explcitly add ProjectA nuget to the solution.  
Please suggest any solution if you ever experienced any similar issue.
Thank you!

_Originally posted by @MonicaJa in https://github.com/NuGet/Home/discussions/11233_

**Comment by nkolev92** [comment]
Closing the issue givent his is a quesiton. 

I'll reply in the discussion itself.

**Comment by Proxima89** [comment]
Thank you @nkolev92 , much appreciate it!
