### ISSUE TITLE
[Bug]: nuget restore fails to resolve dependencies of packages.config items

### ISSUE THREAD

**Issue by andrewcdysart** [NuGet/Home#11269]
### NuGet Product Used

NuGet.exe

### Product Version

5.11.0.10

### Worked before?

N/A

### Impact

I'm unable to use this version

### Repro Steps & Context

We have a somewhat unique workflow which involves generating a packages.config file to be fed into `nuget restore`. Changing our usage, e.g. to use PackageReference, is untenable at the moment. We are attempting a long-overdue upgrade from NuGet 5.4.x (where we used to feed in a project.json) to NuGet 5.11.x. `nuget restore` used to download each package listed in the project.json and evaluate/install that package's dependencies, but unfortunately, `nuget restore`  now seems to *only* download the listed packages without retrieving dependencies. This seems to contradict the [documentation](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-restore#remarks) which claims that for a packages.config file, `nuget restore` will:

> Restore packages listed in the file, resolving and installing dependencies.

**Reproduction steps**:

 1. Create a file `packages.config` with the following contents:
```xml
<packages>
    <package id="xunit" version="2.4.1" />
</packages>
```
 2. Create a "cache" folder anywhere you have write access to (e.g. C:\Users\Andrew\Documents\cache)
 3. Run `nuget.exe restore packages.config -NonInteractive -PackagesDirectory C:\Users\Andrew\Documents\cache -UseLockFile -LockFilePath project.lock.json -PackageSaveMode nuspec;nupkg` and allow the operation to complete.

What I expected: xunit and its dependencies are downloaded to C:\Users\Andrew\Documents\cache

What I got: Only xunit is downloaded. The nuspec file contains references to several other dependencies which are not downloaded.

### Verbose Logs

```shell
NuGet Version: 5.11.0.10
Restoring NuGet package xunit.2.4.1.
Missing C:\Users\*******\.nuget\packages\xunit\2.4.1\xunit.2.4.1.nupkg
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\xunit\2.4.1\xunit.2.4.1.nupkg
  GET https://api.nuget.org/v3-flatcontainer/xunit/2.4.1/xunit.2.4.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/xunit/2.4.1/xunit.2.4.1.nupkg 63ms
Acquiring lock for the installation of xunit 2.4.1
Acquired lock for the installation of xunit 2.4.1
PackageSignatureVerificationLog: PackageIdentity: xunit.2.4.1 Source: https://api.nuget.org/v3/index.json PackageSignatureValidity: True
Installed xunit 2.4.1 from https://api.nuget.org/v3/index.json with content hash XNR3Yz9QTtec16O0aKcO6+baVNpXmOnPUxDkCY97J+8krUYxPvXT1szYYEUdKk4sB8GOI2YbAjRIOm8ZnXRfzQ==.
Adding package 'xunit.2.4.1' to folder 'C:\Users\*******\Documents\cache'
Added package 'xunit.2.4.1' to folder 'C:\Users\*******\Documents\cache'
Added package 'xunit.2.4.1' to folder 'C:\Users\*******\Documents\cache' from source 'https://api.nuget.org/v3/index.json'

NuGet Config files used:
    C:\Users\*******\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\*******\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    1 package(s) to packages.config projects
```

**Comment by nkolev92** [comment]
Hey @andrewcdysart, 

I can totally see how that information can be confusing. 

If you look at the first column, you'll notice: 

> packages.config or project file

I think the description is suggesting that for project file restore, ex. PackageReference, the dependencies will be resolved and install, because in PackageReference, the restore gesture is pretty much the only one. 

Created an issue to clarify that https://github.com/NuGet/docs.microsoft.com-nuget/issues/2536. 

In packages.config PM UI and PMC package installation can resolve dependencies and restore itself will only download the packages listed in that file.

**Comment by andrewcdysart** [comment]
Thanks for your response @nkolev92! That's pretty unfortunate for our use case... am I correct in understanding that there is currently no CLI-only solution for installing NuGet packages with their dependencies given only a packages.config file? You mentioned PMC but as I understand it, that is a built-in Visual Studio utility rather than an external console.

I appreciate the help/clarification either way!

**Comment by nkolev92** [comment]
Yes, there's no packages.config solution for that. 

It's basically one of the many reasons PackageReference was designed, to allow package installation independent of VS.
