### ISSUE TITLE
[Bug]: [Pack] No description for options “--force” and “--no-dependencies” when running the command “dotnet pack –h”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11273]
### NuGet Product Used

dotnet.exe

### Product Version

Dotnet SDK Version: 6.0.100-rc.1.21458.32

### Worked before?

No

### Impact

Other

#### Details about Problem
VS Version: Main\31726.35
NuGet Version: Dev\6.0.0.260
OS Version: co_release_svc_refresh-enterprise_en-us_vl
Dotnet SDK: 6.0.100-rc.1.21458.32
#### Repro Steps
1.	Launch VS and create a new C# Class Library (.NET 6.0).
2.	Open the Developer Command Prompt and cd to the project path.
3.	Run command “dotnet pack -h”.
#### Expected
There is description for options “--force” and “--no-dependencies”.
#### Actual
No description for options “--force” and “--no-dependencies” as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/134878870-cafd5741-678e-49c2-9fed-41ecec26eb05.png)
#### Notes:
1.It is not a regression bug since we never saw the description info for the two options in previous .NET SDK Version.
2.No description for options "-p:PackageVersion", "-p:TargetFrameworks" and "--runtime" either.

**Comment by nkolev92** [comment]
Great catch @v-luzh

Fortunately, this is by design.

`--force` and `--no-dependencies` are commands of implicit commands (pack and restore) and such it is not expected to be in this description. 

Take `build` for example. 

Build runs restore implicitly and one of the options for `restore` is `--force`. 

Running `dotnet build --help`

```
C:\Code\Temp> dotnet build --help
Description:
  .NET Builder

Usage:
  dotnet [options] build [<PROJECT | SOLUTION>...]

Arguments:
  <PROJECT | SOLUTION>  The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  --use-current-runtime                Use current runtime as the target runtime.
  -f, --framework <FRAMEWORK>          The target framework to build for. The target framework must also be specified in the project file.
  -c, --configuration <CONFIGURATION>  The configuration to use for building the project. The default for most projects is 'Debug'.
  -r, --runtime <RUNTIME_IDENTIFIER>   The target runtime to build for.
  --version-suffix <VERSION_SUFFIX>    Set the value of the $(VersionSuffix) property to use when building the project.
  --no-restore                         Do not restore the project before building.
  --interactive                        Allows the command to stop and wait for user input or action (for example to complete authentication).
  -v, --verbosity <LEVEL>              Set the MSBuild verbosity level. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic].
  --debug
  -o, --output <OUTPUT_DIR>            The output directory to place built artifacts in.
  --no-incremental                     Do not use incremental building.
  --no-dependencies                    Do not build project-to-project references and only build the specified project.
  --nologo                             Do not display the startup banner or the copyright message.
  --self-contained                     Publish the .NET runtime with your application so the runtime doesn't need to be installed on the target machine.
                                       The default is 'true' if a runtime identifier is specified.
  --no-self-contained                  Publish your application as a framework dependent application. A compatible .NET runtime must be installed on the target machine to run your application.
  -a, --arch <arch>                    The target architecture.
  --os <os>                            The target operating system.
  -?, -h, --help                       Show command line help.
```

Note that the `--force` description is not available when running help for `dotnet build`.
