### ISSUE TITLE
AutoCompleteResourceV3 does not use the supplied logger

### ISSUE THREAD

**Issue by tintoy** [NuGet/Home#11272]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

NuGet.Client (v4.2.0), tested with .NET Core SDK 5.0.104

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Hi.

I maintain a [VS Code extension[(https://github.com/tintoy/msbuild-project-tools-vscode/) that uses the NuGet autocomplete API, and was having trouble diagnosing the cause of AutoComplete failure for Azure DevOps package sources (it works, and has always worked, for other package sources). I created a console app to perform the AutoComplete request (while capturing any logs created by the NuGet client). I would have expected to see at least _some_ log entries from NuGet which is what made me go looking in the client library source code. As it turns out, the client library ignores the supplied logger and always uses `NullLogger.Instance`.

The code in question:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/AutoCompleteResourceV3.cs#L55

And here's the code I was using where I would have expected it to use the supplied logger:

https://gist.github.com/tintoy/3d9467d59b2547ad227ba5d1560ee838#file-program-cs-L61

I'm happy to open a PR for this if you folks don't have the time to fix it but I thought I'd better talk to you first to see what you think 🙂 

### Verbose Logs

```shell
[Program/INF] Requesting suggestions for package prefix Microsoft.AspNetCore from package source nuget.org ("https://api.nuget.org/v3/index.json")...
[Program/INF] Received 20 suggestions for package prefix Microsoft.AspNetCore from package source nuget.org ("https://api.nuget.org/v3/index.json").
[Program/INF]   Suggested package: Microsoft.AspNetCore
[Program/INF]   Suggested package: Microsoft.AspNetCore.Http.Features
[Program/INF]   Suggested package: Microsoft.AspNetCore.Http.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Hosting.Server.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Hosting.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.WebUtilities
[Program/INF]   Suggested package: Microsoft.AspNetCore.Http.Extensions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Http
[Program/INF]   Suggested package: Microsoft.AspNetCore.Routing
[Program/INF]   Suggested package: Microsoft.AspNetCore.Mvc.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Routing.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Authorization
[Program/INF]   Suggested package: Microsoft.AspNetCore.Mvc.Core
[Program/INF]   Suggested package: Microsoft.AspNetCore.JsonPatch
[Program/INF]   Suggested package: Microsoft.AspNetCore.ResponseCaching.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Authentication.Abstractions
[Program/INF]   Suggested package: Microsoft.AspNetCore.Authentication.Core
[Program/INF]   Suggested package: Microsoft.AspNetCore.Mvc.Formatters.Json
[Program/INF]   Suggested package: Microsoft.AspNetCore.Mvc.DataAnnotations
[Program/INF]   Suggested package: Microsoft.AspNetCore.Authorization.Policy
```
```

**Comment by tintoy** [comment]
For what it's worth, if I hackily override `NullLogger.Instance`, I do get useful log entries:

```csharp
typeof(NuGet.Common.NullLogger)
                .GetField("_instance", BindingFlags.Static | BindingFlags.NonPublic)
                .SetValue(obj: null /* static */, value: myNuGetLogger);
```

**Comment by aortiz-msft** [comment]
Please feel free to send us a PR!

**Comment by tintoy** [comment]
Thanks, will do! 🙂

**Comment by tintoy** [comment]
I'll open a PR shortly; a cursory inspection shows the issue exists in a couple of other resource providers as well but I'm guessing you folks would prefer that a PR addresses a specific issue?

Happy to handle it however you prefer.

**Comment by nkolev92** [comment]
Keeping the PRs scoped down would allow for easier and faster reviews.
