### ISSUE TITLE
Uninstalls are blocked in UWP projects when the project is in a bad state

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1128]
Uninstalls are rolled back when the project is in a bad state, this prevents the user from being able to fix themselves without editting project.json manually.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@08bf877d0b32e89e0652f0cde346a942dc42cb93

**Comment by deepakaravindr** [comment]
Gives the expected result. NuGet.Versioning gets uninstalled
