### ISSUE TITLE
[Bug]: dotnet nuget push "**/*.nupkg" fails to glob for packages to push on Ubuntu.

### ISSUE THREAD

**Issue by AraHaan** [NuGet/Home#11296]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet sdk: 6.0.100-rc.1.21417.19 (on ubuntu github actions runner)

### Worked before?

.NET SDK: 6.0.0-rc.2.21461.1 (on my own macos)

### Impact

I'm unable to use this version

### Repro Steps & Context

When I invoke on my MacOS with:

``dotnet nuget push "**/*.nupkg" --source nuget.org -k {api key}`` the command works and pushes the package.

However if I try the same command on ubuntu from within github actions, the command fails saying that the file ``"**/*.nupkg"`` was not found.

On Windows the command also works. I feel this was some break in the command on linux.

Here is the build log from github actions: https://github.com/Elskom/templates/runs/3818800211

**Comment by tannergooding** [comment]
Fairly certain you need to escape `**` (and possibly `*`) on bash as its used for globbing

**Comment by AraHaan** [comment]
I thought that when I encased them in ``"`` that it would escape them and make nuget from the .NET SDK process the glob like it does on Windows and MacOS.

**Comment by AraHaan** [comment]
Hmm it seems when I switch the runner to ``macos-latest`` it also failed there so the issue might have been in the action will update it then.

**Comment by tannergooding** [comment]
Bash requires single quotes to prevent expansion of variables, not double quotes. I believe globbing is the same.

You can also explicitly escape them as an alternative.

**Comment by zkat** [comment]
For the record, both single and double quotes should be working in bash for this.

This is definitely part of a larger story of how we handle cross-platform stuff, because the way `dotnet nuget push` works is basically by shelling out to nuget.exe, which has... windows-flavored argument handling.

This is worth investigating.

**Comment by AraHaan** [comment]
I guess it *could* special case ``**/*.nupkg`` strings when it goes looking for file names to use to push and then know if it contains ``**/*`` or ``**\*`` as globs and then use the api ``Directory.EnumerateFiles()`` to resolve them to the actual file name strings (full path and everything from it).

Also I think the reason why this did not work as expected in github actions is that it actually seems to skip the shell and just executes the program directly and passes in the arguments and so then the shell does not expand them for you resulting in this issue but I agree it is worth the investigation (and possibly special case it) for those who actually need to run the command this way as well with globs like this.

**Comment by zkat** [comment]
Interesting, although NuGet _should_ be expanding things itself. It has to do that because cmd.exe and pwsh.exe don't support glob-expansion like bash/zsh/etc. I kinda suspect this might be because we're explicitly skipping that code on those platforms. It's really tricky to get this right, imo :)

**Comment by zkat** [comment]
@heng-liu do you mind taking a look at this? I think we have some issue with the way we expand (or not expand) globs on *nix platforms.

**Comment by heng-liu** [comment]
Hi @AraHaan , I tried to repro on both ubuntu and macOS, but it seems the push command work correctly on both of them. 
Here are my repro steps:
On Ubuntu:
```
$ dotnet --version
6.0.101
```

1.Create a packages folder as following:
```
.
└── packages
    ├── folder
    │   └── packageC.1.0.0.nupkg
    ├── packageA.1.0.0.nupkg
    └── packageB.1.0.0.nupkg
```
2.Create another 4 different folders as the sources
```
.
├── packages
│   ├── folder
│   │   └── packageC.1.0.0.nupkg
│   ├── packageA.1.0.0.nupkg
│   └── packageB.1.0.0.nupkg
├── source1
├── source2
├── source3
└── source4
```
3.Go to `packages `folder, run push commands for different scenarios:
3.1 **double quotes and globstar is off**: ` dotnet nuget push "**/*.nupkg" --source ~/test/source1`
   The packages pushed to source1 folder:
```
:~/test/source1$ ls
packageA.1.0.0.nupkg  packageB.1.0.0.nupkg  packageC.1.0.0.nupkg
```
3.2 **single quotes and globstar is off**: `  dotnet nuget push '**/*.nupkg' --source ~/test/source2`
The packages pushed to source2 folder:
```
~/test/source2$ ls
packageA.1.0.0.nupkg  packageB.1.0.0.nupkg  packageC.1.0.0.nupkg
```
3.3 **no quote and globstar is off**: `  dotnet nuget push **/*.nupkg --source ~/test/source3`
The packages pushed to source3 folder:
```
:~/test/source3$ ls
packageC.1.0.0.nupkg
```
3.4 **no quote and globstar is on**: `  dotnet nuget push **/*.nupkg --source ~/test/source4`
```
:~/test/source4$ ls
packageA.1.0.0.nupkg  packageB.1.0.0.nupkg  packageC.1.0.0.nupkg
```
So the repro shows double quotes and single quotes work correctly even if globstar is off. 
And when there is no quote,  the results is depended by the globstar option.

May I know if the issues still exist from your side? If yes, could you let me know if there is anything different in the above repro steps? Thanks!

BTW, for globstar option in bash:
```
#check if globstar is on or off
$shopt 
#turn globstar on
$shopt -s globstar
#turn globstar off
$shopt -u globstar
```

**Comment by AraHaan** [comment]
I have not rechecked it in github actions for some time to see if they fixed it, I could recheck it sometime when I get the time for it.

**Comment by erdembayar** [comment]
@AraHaan 
Do you have any recent update? This issue has been open quite a while.

**Comment by AraHaan** [comment]
I think it randomly started working in github actions as the action randomly started working.

**Comment by erdembayar** [comment]
> I think it randomly started working in github actions as the action randomly started working.

Could we close if there is no recent update?
