### ISSUE TITLE
[Bug]: nuget packages don't download from .targets files when RestoreUseStaticGraphEvaluation is enabled 

### ISSUE THREAD

**Issue by gurpreed** [NuGet/Home#11294]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet --info (Version:   5.0.401)

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Create a targetfilename.targets file:
\<Project>
  \<ItemGroup>
    \<PackageReference Include="any package here" Version="add version here" >
      \<PrivateAssets>all\</PrivateAssets>
    \</PackageReference>
  \</ItemGroup>
\</Project>

In Directory.Build.props, add:
  \<Import Project="\<path>/targetfilename.targets" />

  \<PropertyGroup>
    \<RestoreUseStaticGraphEvaluation Condition=" '$(RestoreUseStaticGraphEvaluation)' == '' ">true </RestoreUseStaticGraphEvaluation>
  \</PropertyGroup>

Run "dotnet restore" and the package will not download. Works with msbuild /restore.

**Comment by erdembayar** [comment]
Thank you for filing the this issue.
It looks you have xml syntax error in your Directory.Build.props, here `RestoreUseStaticGraphEvaluation` tag need closing tag.

I tested below on my local. After running "dotnet restore" command I can see package is downloaded into my Global packages folder.
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="targetfilename.targets" />
    <PropertyGroup>
        <RestoreUseStaticGraphEvaluation Condition=" '$(RestoreUseStaticGraphEvaluation)' == '' ">true</RestoreUseStaticGraphEvaluation>
    </PropertyGroup>    
</Project>
```

Please let me know if it above works for you.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
