### ISSUE TITLE
 401 (Unauthorized)。

### ISSUE THREAD

**Issue by bbhxwl** [NuGet/Home#11302]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

nuget

### Impact

Other

### Repro Steps & Context

I added the GitHub package in vs. the password was entered incorrectly, and then it was 401 (unauthorized). After I deleted it and added it again, I never asked me to enter the password. I changed the password in the windows certificate, but it was useless

**Comment by donnie-msft** [comment]
Hello, I have a few questions.

> I added the GitHub package in vs. the password was entered incorrectly

Which package are you referring to, or do you mean a package source? The specific source (aka feed) you're using is what would prompt for a password. Are you using a private package source?

> After I deleted it and added it again

Do you mean reinstalled the package, or something else?

> I changed the password in the windows certificate, but it was useless

What errors did you get at this point?
Note, we have another issue to improve the prompts, but it sounds like you're reporting the opposite problem (too few prompts).
If it looks relevant, please let us know: https://github.com/NuGet/Home/issues/8985

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by redion-io** [comment]
Go to the Credential Manager in Windows and look for the VSCredentails...github. Delete that. Close and reopen VS 2022 and enter your username and PAT for the password.

**Comment by arla-osman** [comment]
> Go to the Credential Manager in Windows and look for the VSCredentails...github. Delete that. Close and reopen VS 2022 and enter your username and PAT for the password.

Thank you so much! Fixed my issue. I was going crazy because I had my Nuget.Config setup correctly but it seemed like it refused to use those credentials. Turns out, credentials stored in the Credential Manager were used instead (and my pw, not pat was stored there).
