### ISSUE TITLE
[Bug]: LocalV3FindPackageByIdResource.GetAllVersionsAsync does not return any versions when local feed contains the package.

### ISSUE THREAD

**Issue by AraHaan** [NuGet/Home#11303]
### NuGet Product Used

NuGet API nuget packages

### Product Version

I use the latest nuget v3 api packages in my own program (referenced to version `*-*`)

### Worked before?

I know what it worked on Windows with Nuget.Client, but since I need it to work xplat it will not work with the v3 apis.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I would take a look at the code file in action that I encounter the issue at. That is the only file that uses types from the nuget api packages. https://github.com/Elskom/installer/blob/main/src/NuGetHelper.cs

This should hopefully allow to help reproduce this. Basically I want that same code to be anle to process all sources even local ones that they added using `dotnet nuget add source`.

### Verbose Logs

```shell
I am not sure logs are possible in this case, perhaps this is an api bug.
```

**Comment by erdembayar** [comment]
Thank you for filing the this issue.
Could you please check https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#get-package-metadata?
Also if you're using v3 api then please make sure your local feed folder structure is v3 structure, not flat list of nupkgs.
Please check `C:\Users\yourUserName\.nuget\packages` for how v3 structure looks.
Please let me know if it resolves your issue.

**Comment by AraHaan** [comment]
ah they were a flat list of nupkg files. Also I seem to have issues with the ``FindPackageByIdResource`` type as well (when telling it to use the nuget.org v3 url) that is in the docs.microsoft.com url references as well where the GetAllVersionsAsync() for some reason straight up kills the process instead of returning the packages from nuget.org.

**Comment by AraHaan** [comment]
For repro it should be possible to do it with this code (it happens to me where it kills the process now with it before it even can call GetAllVersionsAsync now on Macos and Windows, as for linux I am not sure if it repros there too):

```cs
var providers = new List<Lazy<INuGetProvider>>();
providers.AddRange(Repository.Provider.GetCoreV3());
var cache = new SourceCacheContext();
var repository = new SourceRepository(
    new PackageSource(
        "https://api.nuget.org/v3/index.json",
        "nuget.org",
        true),
    providers,
    FeedType.HttpV3);
// the 2 ways I optain the resource both causes the process to be killed with no stack traces
// at all and even with breakpoints nothing shows inside of Visual Studio debug as well.
var resource = new RemoteV3FindPackageByIdResource(repository, HttpSource.Create(repository));
// var resoure = await repository.GetResourceAsync<RemoteV3FindPackageByIdResource>();
// do stuff with resource, this code never gets reached.
```

As for local feeds it seems to also do the same thing as well.

Could I be calling it wrong? probably, but then again probably not after all I do not know why it fails like this since it's being used in a console application and ``dotnet nuget`` is similarly a console application so there should be no reasons why it should not work.

**Comment by AraHaan** [comment]
After looking into it, it looks like the v5+ packages do it. And it also does it if I do the metadata approach as well.

For more information look at ``NuGetHelper.cs`` in https://github.com/Elskom/installer/ with breakpoints on ``ResolveWildcardPackageVersionAsync``.

**Comment by nkolev92** [comment]
@AraHaan 

You shouldn't request resources with the type, but only the abstract versions and let NuGet determine the feed type based on it's own heuristics (which are pretty rudimentary admittedly, but pretty reliable). 

Refer to: 

https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#list-package-versions

Replacing nuget.org in the example with *any* source should do it. 

Critical part is: 

```cs
SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
FindPackageByIdResource resource = await repository.GetResourceAsync<FindPackageByIdResource>();

IEnumerable<NuGetVersion> versions = await resource.GetAllVersionsAsync(
    "Newtonsoft.Json",
    cache,
    logger,
    cancellationToken);
```

**Comment by nkolev92** [comment]
Hey @AraHaan 

I think the last response provides enough information for your problem. 
Looking at the latest version of your code, looks like you've moved away from it/refactored it. 

Closing this as addressed.
