### ISSUE TITLE
[Bug]: Sporadically get NU3005 for package 'Microsoft.NETCore.Platforms 1.0.1' and 1.1.0

### ISSUE THREAD

**Issue by patspaeth** [NuGet/Home#11304]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet sdk 5.0.401

### Worked before?

sporadic error

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I am running dotnet restore but sporadically it fails because of:
`error NU3005: Package 'Microsoft.NETCore.Platforms 1.0.1' from source 'https://pkgs.dev.azure.com/XXXX/_packaging/XXXX/nuget/v3/index.json': The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).`

The mentioned feed is our private Azure artifacts feed where we upload our used 3rdParty components from nuget.org.
The AzureDevops agents are cloud hosted Azure Pipelines using the VMimage "windows-latest"
No lock file is used!

I'm really upset because it doesn't always fail and don't understand why it fails! Would be great to understand it!

### Verbose Logs

```shell
Determining projects to restore...
D:\a\1\s\Source\MYPROJECT.csproj : error NU3005: Package 'Microsoft.NETCore.Platforms 1.0.1' from source 'https://pkgs.dev.azure.com/XXXX/_packaging/XXXX/nuget/v3/index.json': The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).
  Failed to restore D:\a\1\s\Source\MYPROJECT.csproj (in 3.34 sec).
```

**Comment by donnie-msft** [comment]
Hi, this is a duplicate of https://github.com/NuGet/Home/issues/11226. 
Please follow that issue, and consider giving it a 👍. Thanks!
