### ISSUE TITLE
[Bug]: No warning shows when opening the PackageReference Migrator of an unsupported project

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11300]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.1.0.11

### Worked before?

NuGet Client Dev\6.0.0.265

### Impact

It bothers me. A fix would be nice

## Installation:
1. Install VS Main\31808.228 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5310477&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet Client Dev\6.1.0.11 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5311377&view=results

## Repro steps:  
1. Create a C++ UWP project.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Install a package (e.g. “SampleCPlusPlusDevicePackage”) with “Packages.config” format. 
4. Right-click the “References” node ->Migrate packages.config to PackageReference.

## Expected: 
There should be a warning showing as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/136653847-9a4c2189-54ad-44a6-ba71-12358f1c53e3.png)

## Actual: 
No warning shows.

## Note:
It starts to repro from Dev\6.0.0.266.

**Comment by aortiz-msft** [comment]
@nkolev92 - Build Dev\6.0.0.266 only has this commit: https://github.com/NuGet/NuGet.Client/commit/60b3df443c2d051ac2750920008a3bb048bb918b.

Would you please take a look?

**Comment by nkolev92** [comment]
Fix out in https://github.com/NuGet/NuGet.Client/pull/4304.
