### ISSUE TITLE
[Bug]: Nuget fails if an empty folder not present

### ISSUE THREAD

**Issue by Luk164** [NuGet/Home#11316]
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

6.0.100-rc.2.21505.57

### Worked before?

-

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

After reinstalling VS2019 and opening a solution I worked on before (reinstalled because VS became corrupted as a result of an extension error) I saw that solution had some missing packages, which was to be expected, I tried to build so that they would be re-acquired and got the following errors:

```
The local source 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages' doesn't exist.		

Unable to find fallback package folder 'CProgram Files (x86)Microsoft Visual StudioSharedNuGetPackages'		
```

Creating an empty folder at the specified location worked as a workaround, but now there is an empty folder just hanging there, probably covering a deeper issue, Note: attaching log as a file because of length limits for issues. Log is made by removing the manually created folder and running a verbose dotnet build command
[log.log](https://github.com/NuGet/Home/files/7357518/log.log)

Also my nuget .config file looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="Stride" value="https://packages.stride3d.net/nuget" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by erdembayar** [comment]
Thank you for filing this issue.
If you're not consuming any package from `<add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />` then you may remove that line it from your `nuget.config` file.
Please remove created folder too, then please let me know if it resolves your issue.

**Comment by Luk164** [comment]
@erdembayar It's the other way around. All nuget packages are stored in `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\`. I have no idea where the `C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages` path is defined and I would like to remove it instead.

**Comment by erdembayar** [comment]
Sorry, about that. I believe it's coming from your machine default (%AppData%\NuGet\NuGet.config) or any top level folders. You can add `<clear />` to remove any hieratical configuration impact on your current `nuget.config`. Also adding `disabledPackageSources` part could be best practice too. Please check our [nuget.config](https://github.com/NuGet/NuGet.Client/blob/dev/NuGet.Config) for ideas. Please try below, if it works for you.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" />
    <add key="Stride" value="https://packages.stride3d.net/nuget" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by Luk164** [comment]
Please read the path again. The one that I needed to create is `C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages `, while the path defined in config is `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\`. BTW the defined path is the one working. All packages are downloaded and referenced from there. I really dont know where the other path came from.

**Comment by nkolev92** [comment]
Hey @Luk164, 

At the bottom of the log, there's a message that tells you about the nuget.config files being used: 

```console
 NuGet Config files used: (TaskId:37)
                         C:\Users\lukij\AppData\Roaming\NuGet\NuGet.Config (TaskId:37)
                         C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.FallbackLocation.config (TaskId:37)
                         C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config (TaskId:37)
```

Can you please check those configs?

**Comment by Luk164** [comment]
@nkolev92 That helped, it was in the fallback location. It was also marked as generated and that it could potentially re-appear after I changed it back. Do you know when/why/by what is that file generated?

**Comment by nkolev92** [comment]
I'm not 100% certain, but from digging around, it seems like it's WinUI. 

Do you have that workload installed?

**Comment by Luk164** [comment]
@nkolev92 Yes. Now that I think about it, the timing seems to fit as well. I was trying it out a while before the issue occurred

**Comment by nkolev92** [comment]
Hey @Luk164 

Just closing this thread here. 
NuGet will by design fail if any of the fallback folders or sources are unavailable. 

Does removing the source fix things on your end?

**Comment by Luk164** [comment]
@nkolev92 Yes the fix worked, but I would still like to know why I needed to fix anything in the first place. I am 100% positive that I did not create that path myself. I strongly suspect it was created during an update

**Comment by nkolev92** [comment]
It can be pretty difficult to track what happened. 
NuGet itself does not really create these paths and only reacts to it. 

If you can diagnose what happened, then I'd recommend filing a https://developercommunity.visualstudio.com/ issue.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
