### ISSUE TITLE
[Feature]: Make NuGet credential providers installable via the dotnet cli

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11325]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

Make NuGet credential providers installable via the dotnet cli, to make it easier for customers and alternate nuget sources to discover credential providers and simplify installation steps.

Consider `dotnet tool install -g tool-name`, or `dotnet workload install maui`. These are tools that are shipped as nupkgs and make it easy for customers to install, and `dotnet workload search` makes it easy to discover.

Compare to the [Azure Artifacts credential provider](https://github.com/microsoft/artifacts-credprovider), which gives instructions to use  shell scripting to download some arbitrary URL and execute that download as a shell script.

We could have something like `dotnet nuget credential-provider install Microsoft.Azure.Artifacts.CredentialProvider` which achieves the same end-goal.

Discovery could be solved by using nuspec package types, adding `CredentialProvider` as a new package type, then `dotnet nuget credential-provider list` could use nuget.org's `packageType:CredentialProvider` filtering to list only packages of that package type, display a list of cred providers available on the fee, and similar to `dotnet list package`, it could list which ones are installed and which ones have updates available.

**Comment by nkolev92** [comment]
This is great idea! 

It was considered when plugins were originally added, but tools weren't as mature as they are today, so it's a thing we can totally revisit!

**Comment by KirillOsenkov** [comment]
Just inline the netfx plugin directly into nuget.exe. I want to be able to download nuget.exe and it should all just work.

**Comment by nkolev92** [comment]
@KirillOsenkov 

Not quite what you're suggesting, but the plugin for netfx today ships with VisualStudio/next to NuGet.

Newer(4.8+ NuGet & 15.8) nuget.exe & msbuild.exe automatically discover the plugin there, so you shouldn't need any custom setup if you already have nuget.exe and VS installed.

**Comment by zivkan** [comment]
Duplicate of https://github.com/NuGet/Home/issues/12567. That issue is newer, but has more details, is a partner ask rather than an in-team idea, and already has more upvotes (👍).
