### ISSUE TITLE
[Bug]: Icons don't show for self hosted packages

### ISSUE THREAD

**Issue by woeterman94** [NuGet/Home#11323]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Microsoft Visual Studio Enterprise 2019 Version 16.10.2

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Create your own package with an icon defined in the .nuspec

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>BuildingBlocks</id>
    <version>1.0.0</version>
    <authors>Bridges</authors>
    <icon>images\BuildingBlocks.png</icon>
    <iconUrl>https://i.imgur.com/5CDMwJq.png</iconUrl>
    <description>Package for sharing building blocks for the Adminsuite Projects</description>
    <dependencies>
      <group targetFramework="net5.0">
        <dependency id="AspNetCore.HealthChecks.UI.Client" version="5.0.1" exclude="Build,Analyzers" />
        <dependency id="Microsoft.ApplicationInsights.AspNetCore" version="2.18.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.ApplicationInsights.Kubernetes" version="2.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Bridges</Authors>
    <Product>Admin Suite</Product>
    <PackageIcon>images\BuildingBlocks.png</PackageIcon>
    <PackageIconUrl>https://i.imgur.com/5CDMwJq.png</PackageIconUrl>
    <Description>Package for sharing building blocks for the Adminsuite Projects
</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\BuildingBlocks.png" Pack="true" Visible="false" PackagePath="images\BuildingBlocks.png" />
  </ItemGroup>
```

Icon does not show up in the package manager list in visual studio
![image](https://user-images.githubusercontent.com/5755057/138063653-7b2b1773-1f38-44bc-a78d-d579300b29a9.png)

.nupkg archive contains the icon
![image](https://user-images.githubusercontent.com/5755057/138064001-d1a75ca5-7b5e-43af-a870-1e469231b99c.png)

**Comment by erdembayar** [comment]
Thank you for filing the this issue.
Please note `iconUrl` is [deprecated](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5048).
Following works for me after packing. I placed `5CDMwJq.png` in images folder.

![image](https://user-images.githubusercontent.com/8766776/138385582-38aa3177-a773-4238-94c3-335d7921e781.png)

```
<?xml version="1.0" encoding="utf-8"?>
<package>
  <metadata>
    <id>testPackage</id>
    <version>0.0.1</version>
    <authors>Author1, author2</authors>
    <description>A short sample description</description>
    <icon>5CDMwJq.png</icon>
  </metadata>
  <files>
    <file src="images\5CDMwJq.png" />
  </files>
</package>
```
`nuget pack Package.nuspec`

![image](https://user-images.githubusercontent.com/8766776/138385373-0c2238e4-4baa-43db-b98b-0ff498d3f73f.png)

Please let me know if this resolved your issue.

**Comment by woeterman94** [comment]
I'm using dotnet pack to pack my nuget. Should that make a difference?

**Comment by erdembayar** [comment]
> I'm using dotnet pack to pack my nuget. Should that make a difference?

It looks dotnet pack requires `.csproj` project file besides nuspec.  

`dotnet pack <path to .csproj file> -p:NuspecFile=<path to nuspec file> -p:NuspecProperties=<> -p:NuspecBasePath=<Base path> 
`

Actually you [can move move  most of nuspec details](https://stackoverflow.com/a/42014918) into `.csproj` file then do `dotnet pack ~/projects/app1/project.csproj`

**Comment by woeterman94** [comment]
My csproj file contains both PackageIcon and PackageIconUrl. 

```
<PackageIcon>images\BuildingBlocks.png</PackageIcon>
    <PackageIconUrl>https://i.imgur.com/5CDMwJq.png</PackageIconUrl>
```

**Comment by erdembayar** [comment]
> My csproj file contains both PackageIcon and PackageIconUrl.
> 
> ```
> <PackageIcon>images\BuildingBlocks.png</PackageIcon>
>     <PackageIconUrl>https://i.imgur.com/5CDMwJq.png</PackageIconUrl>
> ```

Please note iconUrl is deprecated, it may work due to backward compatibility. Please use `PackageIcon` only.

**Comment by nkolev92** [comment]
@woeterman94 

Please refer to https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-using-a-nuspec-file 

Your current setup will not work because it's half nuspec/half csproj. 

Please follow the above guidance to correct your setup.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by woeterman94** [comment]
What more info do you need?
Edit: the icon shows when the package is installed, but not in the "gallery view". Please let me know if you need more information, I can send you the project file as well if you want but I can't post it publicly on github

**Comment by CDTR-MattConroy** [comment]
I am seeing a similar issue where I did not see any icon in GitHub Packages or Visual Studio 
After adding PackageIconUrl as a backup as recommended [here](https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packageicon), the icon shows in Visual Studio, but not GitHub.

It looks like that the Installed package in Visual Studio is showing the Icon specified by `PackageIconUrl` / `IconUrl` (which is now deprecated). Whereas GitHub Packages only shows the icon specified by `PackageIcon` / `Icon`.

**Comment by sdudnic** [comment]
don't see the icon.png in Visual Studio list, VS 2022, gitlab 16.9, didn't specify the URL
