### ISSUE TITLE
[Bug]: Some CLI commands don't respect DOTNET_CLI_UI_LANGUAGE

### ISSUE THREAD

**Issue by aortiz-msft** [NuGet/Home#11326]
### NuGet Product Used

dotnet.exe

### Product Version

5.0.302

### Worked before?

Not sure

### Impact

It bothers me. A fix would be nice

### Describe the bug
I've set the `DOTNET_CLI_UI_LANGUAGE` env variable to `en-us`, and `dotnet --info` is displaying in English. However, some commands like `dotnet restore` still "speak" Chinese, which is the language of my local machine.

### To Reproduce

1. Create an class library using `dotnet new classlib -n Infrastructure`
2. View the output:
```sh
> dotnet new classlib -n Infrastructure
The template "Class library" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on Infrastructure\Infrastructure.csproj...
  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
Restore succeeded.
```

### Exceptions (if any)

The info should all be in English.

### Further technical details
- Include the output of `dotnet --info`

```sh
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]     
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

VS Code 1.60.1

**Remarks**:
I have a global.json to pin the dotnet version used.

```json
{
  "sdk": {
    "version": "5.0.302"
  }
}
```

**Comment by aortiz-msft** [comment]
Transferred manually from: https://github.com/dotnet/sdk/issues/21159

**Comment by erdembayar** [comment]
@HymanZHAN
~~I was not able to repro this issue on Chinese Windows OS~~. I used version 5.0.402 since it's latest secure version for 5xx.
![image](https://user-images.githubusercontent.com/8766776/138528052-62b0f728-730d-4e54-82b8-21e6e2f3454a.png)

I was able to repro is after using `--force` option.
![image](https://user-images.githubusercontent.com/8766776/138528552-8b56cd58-70cf-4616-984c-20d4fb758420.png)

![image](https://user-images.githubusercontent.com/8766776/138528652-fde4c447-891a-4713-b36f-b2ac4939e2f5.png)

**Comment by nkolev92** [comment]
restore runs through msbuild, I wonder if this an issue with MSBuild only or all nuget commands.

Worth testing the 2 classes of commands: 

dotnet restore, dotnet pack 

vs

dotnet nuget sign, dotnet add package, dotnet nuget sources

**Comment by erdembayar** [comment]
```
dotnet build .\Infrastructure\Infrastructure.csproj
用于 .NET 的 Microsoft (R) 生成引擎版本 16.11.1+3e40a09f8
版权所有(C) Microsoft Corporation。保留所有权利。

  正在确定要还原的项目…
  所有项目均是最新的，无法还原。
  Infrastructure -> C:\Users\eryondon\Desktop\222\Infrastructure\bin\Debug\net5.0\Infrastructure.dll

已成功生成。
    0 个警告
    0 个错误

已用时间 00:00:12.52
```

```
 dotnet restore
MSBUILD : error MSB1003: 请指定项目或解决方案文件。当前工作目录中未包含项目或解决方案文件。
```

```
dotnet nuget list
NuGet Command Line 5.11.1.5

Usage: dotnet nuget list [options] [command]

Options:
  -h|--help  Show help information

Commands:
  client-cert  列出配置中的所有客户端证书。
  source       列出所有配置的 NuGet 源。
```

```
 dotnet add package nuget.protocol
  正在确定要还原的项目…
  Writing C:\Users\eryondon\AppData\Local\Temp\tmpC753.tmp
info : 正在将包“nuget.protocol”的 PackageReference 添加到项目“C:\Users\eryondon\Desktop\222\Infrastructure\Infrastructure.csproj”。
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/nuget.protocol/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/nuget.protocol/index.json 85 毫秒
info : 正在还原 C:\Users\eryondon\Desktop\222\Infrastructure\Infrastructure.csproj 的包...
```

**Comment by zkat** [comment]
We can't fix restore/pack. Those are msbuild things: https://github.com/dotnet/msbuild/issues/1596

But for other things, we should make sure we're following the docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-environment-variables#dotnet_cli_ui_language

**Comment by Balkoth** [comment]
`dotnet list package` has the same problem. It does not respect `DOTNET_CLI_UI_LANGUAGE` and uses the installed os language instead.

**Comment by dominoFire** [comment]
We need [UILanguageOverride](https://cs.github.com/dotnet/sdk/blob/49d9b4148c4f65fd3f691186a4533375c3a83c97/src/Cli/dotnet/UILanguageOverride.cs#L9) class in NuGet.CommandLine.XPlat, since our nuget commands in dotnet.exe create a new process _outside_ dotnet.exe
