### ISSUE TITLE
The file .nuget\packages.config is checked out from TFS when restore solution level packages

### ISSUE THREAD

**Issue by wrongite** [NuGet/Home#1132]
In Visual Studio 2012 with `NuGet Package Manager - Version: 2.8.60318.667`,
I enable the NuGet to automatically check and restore for missing packages during build.

If there is any missing solution level package, the NuGet will restore the missing packages and check out the file `.nuget\packages.config` for editing but it doesn't change the file content.

Why does the NuGet check this file out? The NuGet doesn't check out the project level `packages.config` file when restoring the project level packages.

NuGet should not check out the file `.nuget\packages.config` if it doesn't make any change.

**Comment by rohit21agrawal** [comment]
@wrongite  I tried this using Nuget 2.8.60318.667 and VS 2012 , but was unable to get this to repro. Could you provide more details as to the kind of project you were using? It would be even better if you could attach a small repro project for us to investigate.

Also, when you say .nuget\packages.config, do you actually mean the packages.config in the project directory?

**Comment by wrongite** [comment]
@rohit21agrawal Today, I was unable to get this repro either. I guess the issue was fixed by VS 2012 Upddate 5. The Visual Studio seems to check the file out and undo check out automatically. So we cannot see the problem now but we are still noticed, the packages.config has been automatically checked out for editing.

![image](https://cloud.githubusercontent.com/assets/570322/15268954/133e6258-1a1a-11e6-919f-90ab423dfccd.png)

Steps to reproduce the issue:
1. Create a C# Console project
2. Use NuGet  to install the NuGet package "DisableSourceControlIntegration-TFS" or any solution level package.
3. Save and add all files to TFS, including the file $(SolutionDir).nuget\packages.config
4. Build solution
5. Delete all files and folder in $(SolutionDir)\packages
6. Build solution. At here, the package will be restored and the file $(SolutionDir).nuget\packages.config will be checked out. Please take a look the attached photo.

**Comment by rohit21agrawal** [comment]
@wrongite  Yes I can repro this now. However, since the check-out is undone automatically, is this still an issue for you?

**Comment by wrongite** [comment]
@rohit21agrawal No, this is not an issue for me now. Thanks.

**Comment by rohit21agrawal** [comment]
@wrongite  Thanks for your quick response! Closing this now!
