### ISSUE TITLE
[Bug]: An unknown build error occurs when installing package “Expression.Blend.Sdk.WPF” with "packages.config" format into a C# WPF App (.NET Framework) project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11333]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.1.0.35

### Impact

It bothers me. A fix would be nice

### Details about Problem
VS Version: Main\31825.306
NuGet Version: Dev\6.1.0.35
OS Version: Windows-11-Enterprise-21H1

### Repro steps
1. Create a C# WPF App (.NET Framework) project in VS and open the PM UI of the project.
2. Install package “Expression.Blend.Sdk.WPF” with packages.config format into the project.
3. Build the project.

### Expected
No error occurs.

### Actual
An unknown build error occurs as below.
![image](https://user-images.githubusercontent.com/20632625/138851924-993ad886-325d-41ef-b9ea-c378954fff5e.png)

### Notes
1. It doesn’t repro when installing the same package with "PackageReference" format.
2. It repro on both VS and Blend for VS for C# WPF App (.NET Framework) project.
3. Seems it is not a regression since it reproes on 16.10 Preview1 D16.10\31025.218.

### Verbose Logs

```shell
**Error Log:**
Unknown build error, 'Cannot resolve dependency to assembly 'Microsoft.Windows.Design.Extensibility, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.'
```

**Comment by nkolev92** [comment]
Hey @v-luzh 

The package in question might be a problem in this scenario. 

Differences between PackageReference and packages.config are sometimes expected, and unless we get a specific package author complaint about how this package works, we don't think this is something that NuGet should be investigating. 

I imagine this was found during exploratory testing?
Please use a different package. 

Closing as not a bug.
