### ISSUE TITLE
[Engineering]:  Use IAsyncServiceProvider extension methods instead of type casting ourselves

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#11339]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.x

### Worked before?

N/A

### Repro Steps & Context

Use [`IAsyncServiceProvider` extension methods](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.iasyncserviceprovider?view=visualstudiosdk-2019#extension-methods) instead of type casting ourselves.

See https://github.com/NuGet/NuGet.Client/pull/4324/files#r737866598

**Comment by nkolev92** [comment]
I've been meaning to ban this API for a while, and now that banned apis are options , https://github.com/NuGet/NuGet.Client/blob/dev/build/BannedSymbols.txt we can do it. 

I made the changes for the product in https://github.com/NuGet/NuGet.Client/compare/dev-nkolev92-banIAsyncProviderGetServiceAsync?expand=1
