### ISSUE TITLE
The repository primary signature validity period has expired for runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl package

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#11332]
@RussellLMiller commented on [Thu Oct 21 2021](https://github.com/NuGet/NuGetGallery/issues/8855)

### Impact

It's more difficult to complete my work

### Describe the bug

When running dotnet restore on our project we are getting the following error intermittantly. This issue occurs about 30%-40% of our build runs.

error NU3037: Package 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
error NU3028: Package 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider.

Nuget Version Installed: 5.11.0.10
Dotnet Version Installed: 5.0.402

### Repro Steps

1. Create a project that has the following target frameworks (<TargetFrameworks>net452;net5.0</TargetFrameworks>)
2. Add a package reference to the project for System.Net.Http 4.3.4
3. Create a nuget package for that project
4. Create a .Net5.0 project and reference the nuget package for the previous project
5. Run the dotnet restore on the .Net5.0 project 

### Expected Behavior

The package should restore without issues

### Additional Context and logs

I have reached out to Microsoft as they are the package owners 

Have found some NuGet blog posts around certificates expiring and we have updated our nuget.config to include the following configuration. Even with these changes 
```
  <trustedSigners>
  <repository name="nuget.org" serviceIndex="https://api.nuget.org/v3/index.json">
    <certificate fingerprint="0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
    <certificate fingerprint="5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
  </repository>
  <author name="Microsoft">
    <certificate fingerprint="3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
    <certificate fingerprint="AA12DA22A49BCE7D5C1AE64CC1F3D892F150DA76140F210ABD2CBFFCA2C18A27" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
  </author>
</trustedSigners>
```

---

@loic-sharma commented on [Thu Oct 21 2021](https://github.com/NuGet/NuGetGallery/issues/8855#issuecomment-948880711)

Hello, thank you for opening this bug. How do you restore your packages? Are you on Windows? Are you sure you're using the latest version of the .NET SDK and `dotnet` CLI when restoring? Could you capture the errors with maximum verbosity by adding the `--verbosity diagnostic` option? 

Also, can you reproduce this issue by downloading [runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0](https://www.nuget.org/api/v2/package/runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl/4.3.0) and running this command:

```
dotnet nuget verify --all .\runtime.debian.8-x64.runtime.native.system.security.cryptography.openssl.4.3.0.nupkg -v diag
```

If yes, could you share the output of those logs?

---

@loic-sharma commented on [Thu Oct 21 2021](https://github.com/NuGet/NuGetGallery/issues/8855#issuecomment-948911253)

Hello, @heng-liu mentioned that you may be impacted by this problem: https://github.com/NuGet/Home/issues/11099#issuecomment-897046587

The [.NET SDK 6.0.100-rc.2](https://dotnet.microsoft.com/download/dotnet/6.0) allows you to retry on these kinds of intermittent issues by setting the `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY` environment variable. For example:

```
set NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY=3,1000
```

... would try up to 4 times (initial try + 3 retries) with 1 second (1,000 ms) between each try. Please let us know if that solution fixes your issue!

---

@RussellLMiller commented on [Fri Oct 22 2021](https://github.com/NuGet/NuGetGallery/issues/8855#issuecomment-949872007)

This issue occurs when running on a Windows server. We use the DotNetCoreCLI@2 task through Azure DevOps to run the dotnet restore command. Based on the logs it looks like it is using the version of dotnet that we install on the server 5.0.402.

I have attempted to run the following a couple times throughout the day today and haven't seen any failures.

`nuget install runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl -Version 4.3.0
      dotnet nuget verify --all .\runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0\runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl.4.3.0.nupkg -v diag `

I will continue to run this for the next couple of days to see if I can manage to catch a failure. 

When it comes to the .NET SDK version 6.0 option, I'm still working on getting an isolated server to test on for that.

---

@RussellLMiller commented on [Mon Oct 25 2021](https://github.com/NuGet/NuGetGallery/issues/8855#issuecomment-951136557)

@loic-sharma Are there any plans to fix this issue on the .NET SDK 5?

**Comment by loic-sharma** [comment]
@RussellLMiller Thanks for providing additional information! From my understanding, the `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY` workaround is only available in .NET 6. The .NET 6 SDK should be able to build your .NET 5 projects without any changes. 

@dtivel and @heng-liu please correct me if anything I've stated is incorrect! 😊

**Comment by heng-liu** [comment]
Yes, I think you're right.
If using any .NET SDK version after .NET 6 RC2 to restore (or any other command including implicit restore, like build), the `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY` workaround is available. If the project is an SDK-style project, the TFM it targets doesn't matter.

**Comment by heng-liu** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/11099
The workaround is added in PR https://github.com/NuGet/NuGet.Client/pull/4259 ( It is available in .NET 6 RC2 and later)
Pls refer to the description in the above PR for the workaround:

> To opt in, set an environment variable named NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY with a value consisting of 2 comma-delimited positive integers representing retry count and sleep interval in milliseconds, respectively. There are no default values; you'll need to pick retry values that are sensible for you.
> 
> For example:
> 
> set NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY=3,1000
> ...would try up to 4 times (initial try + 3 retries) with 1 second (1,000 ms) between each try.
