### ISSUE TITLE
[DCR]: Adjust compatibility rules for Apple TFMs in .NET 

### ISSUE THREAD

**Issue by rolfbjarne** [NuGet/Home#11338]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe

### Current Behavior

Current behavior is for the following TFMs to be compatible:

| TFM | Compatible With |
|--------------------|------------------------------------------|
 | net6.0-ios         | xamarin.ios                              |
 | net6.0-macos       | xamarin.mac                              |
 | net6.0-maccatalyst | xamarin.ios                              |
 | net6.0-tvos        | xamarin.tvos                             |

### Desired Behavior

We've decided that the xamarin.* TFMs should not be compatible with the corresponding net6.0-* TFM (for the Apple platforms).

Note that there's *no change* for net6.0-android / monoandroid.

### Additional Context

This is a design change that was approved here: https://github.com/dotnet/designs/pull/252

Note that this is technically not a breaking change (yet), since the net6.0-* TFMs aren't considered stable (stable release is Q2 2022).

**Comment by JonDouglas** [comment]
Thank you kindly for filing an issue @rolfbjarne. We'll direct our attention towards it shortly.

**Comment by nkolev92** [comment]
@rolfbjarne 

What's the timeline for this?
What SDK version do you need this change in?

**Comment by rolfbjarne** [comment]
@nkolev92 as soon as possible really. The absolute latest is for the GA MAUI release in Q2 2022, but the sooner the better (6.0.200?), since this will likely hit a lot of people and the earlier it happens the more prepared they'll be by GA.

**Comment by nkolev92** [comment]
PR out: https://github.com/NuGet/NuGet.Client/pull/4361

We'd need to decide whether we want this in 6.0.200 preview 3 (feature stabilization). 

Normally I'd say let's wait, but this shouldn't be something that's exercised at all.
