### ISSUE TITLE
Search in UI of VS 2015 is broken

### ISSUE THREAD

**Issue by DerAlbertCom** [NuGet/Home#1133]
Try to search for xunit.core package

you wont see it, you get the xunit package and the xunit.extensibility.core package. but the package i like to get, xunit.core is not visible. have to go to console to install it.

http://nuget.org will find the right package, VS 2013 will also find it. So it seems to be a v3 feed problem.

**Comment by yishaigalatzer** [comment]
Yes, I see the same issue. If you flip the feed to `https://www.nuget.org/api/v2` it works as expected.

CC @johnataylor @maartenba @bhuvak @xavierdecoster

**Comment by bhuvak** [comment]
@DerAlbertCom , the issue is resolved now and you should see "xunit.core" as the first result when you search for "xunit.core" in VS 2015. Let us know if you hit any further issues.
