### ISSUE TITLE
unable to create a nupkg with framework .NETPortable v5.0

### ISSUE THREAD

**Issue by jorisdebock** [NuGet/Home#1134]
I am unable to create a nupkg with framework .NETPortable v5.0, due the following error:
```
Value cannot be null or an empty string.
Parameter name: profileValue
```

This is in a PCL which targets .net framework 4.6 and windows universal 10.0

Also there appears to be no profiles for this version, when i checked the folder C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v5.0 causing the value to be empty

**Comment by yishaigalatzer** [comment]
Can you please share your nuspec and the exact commands, and version of nuget.exe you are using? You should be able to do that.

**Comment by jorisdebock** [comment]
I tried it with nuget.exe version 2.8.6 and with the beta 3.1.0
without a nuspec file and just the solution file using the following command: 
"nuget.exe pack C:\...\...\example.sln" (with an existing path of course)

Inside this solution i have a couple of project and only the PCL project fails to create a nupkg.
Inside the .csproj file, this variable <TargetFrameworkProfile> </TargetFrameworkProfile> is empty which i guess the error is from.

**Comment by yishaigalatzer** [comment]
Are you able to upload a sample repro solution? We will take it from there

**Comment by yishaigalatzer** [comment]
@jorisdebock if you provide a sample we can look deeper, and perhaps provide a better error message for the failure if it is not fixable

**Comment by yishaigalatzer** [comment]
@jorisdebock haven't heard back from you for about 2 weeks now. Please re-open if you have a repro.

In general at this point we would probably guide you to build for specific TFMs rather than dotnet (so build UAP10, DNX etc.)

**Comment by jorisdebock** [comment]
sorry for late response, wasnt at home last weeks. I made an example repo https://github.com/jorisdebock/PCLNugetExample

Using the nuget.exe beta 3.1.0 with the following command 
`nuget.exe pack PCLNugetExample\PCLNugetExample.csproj` (just saw the command I posted before wasn't correct)

result:

```
WARNING: Unable to extract metadata from 'PCLNugetExample.dll'.
Value cannot be null or an empty string.
Parameter name: profileValue
```

@yishaigalatzer can't re-open myself
