### ISSUE TITLE
Publish SourceMapper tool

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11348]
Once Sourcemapper tool is ready then publish as dotnet global tool on nuget.org

**Comment by nkolev92** [comment]
Should this live here or Client.Engineering?

Removed the `RestoreTool`, as that refers to the RestoreTool feature and this issue is not about that.

**Comment by erdembayar** [comment]
> Should this live here or Client.Engineering?
> 
> Removed the `RestoreTool`, as that refers to the RestoreTool feature and this issue is not about that.

Usually publish nuget.exe/nuget packages issues reside on Client.Engineering, so I guess this one can reside here too.

**Comment by erdembayar** [comment]
Issue moved to [NuGet/Client.Engineering #1343](https://github.com/NuGet/Client.Engineering/issues/1343) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nkolev92** [comment]
Moving issues with the same org should/can be done through Transfer Issue

**Comment by erdembayar** [comment]
@nkolev92 
Sure, I'll do next time. May I ask why? I'm just trying to understand what difference in end result would be.

**Comment by nkolev92** [comment]
It won't close the issue, it'll just add a redirect. 
So every link to the previous issue will still work automatically. 

I'll also completely "hide" the issue, which means that if something was public, it's now private.

**Comment by nkolev92** [comment]
In particular, you'd do https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository instead of the zenhub thing.
