### ISSUE TITLE
Remove repeated/redundant reading of v3-index.json file

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11341]
From https://github.com/NuGet/Home/issues/11341 issue I noticed this. Currently `dotnet restore` command trigger about 16x reading of v3-index.json file in http cache, for dotnet `build` about 80x according to ETL trace. Even though file is small, we better to read only once, because it's on hot path and IO operations are quite expensive.

**Comment by erdembayar** [comment]
@nkolev92 @NuGet/nuget-client 
This one need more investigation, it looks 30 min cache file is quite erratic,  works differently depending on machine, on beefy machine it use cache less but more on slower machine.  Is there any spec/doc regarding 30 min cache policy? I believe we have bug, but need to confirm.

**Comment by donnie-msft** [comment]
@erdembayar yes, we have a cache policy noted here: https://docs.microsoft.com/en-us/nuget/Consume-Packages/managing-the-global-packages-and-cache-folders#viewing-folder-locations

**Comment by nkolev92** [comment]
I would be surprised if the cache itself worked differently on different machines. 

The one thing that could be causing it to look different is the machines have different perf characteristics, which is perfectly understanble.

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 
I was not able to repro again, I can see some duplicate read data with perfview logging and but actual code doesn't read repeatedly. 
I'm closing for now. I'll revisit later if necessary.
