### ISSUE TITLE
Implement "consuming pdbs from packages in PackageReference"

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#11352]
This is one of the sub task of https://github.com/NuGet/Home/issues/5926
When spec is reviewed and merged, investigation on the existing extensions besides assemblies is done, we will start working on the implementation.

**Comment by AraHaan** [comment]
Because of this I made my pdbs embedded so that way if there ever is an issue they can easily diagnose the issue and report it to me (plus they have source link)
