### ISSUE TITLE
Unskip FSharp tests

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#11358]
Tests skipped to resolve: https://github.com/NuGet/Home/issues/11357

**Comment by erdembayar** [comment]
From email thread:
Short term solution for this was to set _NetCoreSdkIsPreview=true when building, which would cause it to fall back to a version available within dotnet-tools.
It’s an msbuild property, passed to the build command line. It’s only necessary when the package is not available on nuget.org
