### ISSUE TITLE
NuGet.exe 2.8.60717.93 and VS extension 2.8.60723.765 NullReferenceException if package ID and Title are not the same

### ISSUE THREAD

**Issue by claq2** [NuGet/Home#1136]
It looks like this version of NuGet.exe creates the nupkg file in Nuget\Cache with the Title value and then looks for it with the ID value. This may be limited to interactions with Artifactory 4.0.0.

Recreation steps (or how I ran into this problem):
1. Install https://www.nuget.org/packages/System.Management.Automation/6.1.7601.17515 in a C# project.
2. Upload the cached nupkg into an Artifactory 4.0.0 instance (System.Management.Automation.6.1.7601.17515.nupkg)
3. Delete the cached nupkg file.
4. Delete the solution's packages\System.Management.Automation.6.1.7601.17515 folder.
5. Build->Clean Solution.
6. Enable package restore.
7. Edit the solution's .nuget\Nuget.targets file to only use your Artifactory source. I.e. uncomment one of the PackageSource lines and change it to your Artifactory Nuget base URL.
8. Build the project.
9. VS will report that Nuget exited with code 1 and an "Object reference not set to an instance of an object" error.
10. Try building the solution with MsBuild.exe.
11. Nuget.exe will report the same error.

In that package's nuspec file the ID is System.Management.Automation and the Title is System.Management.Automation.dll. I tried editing the package's properties in Artifactory, but I gather that NuGet doesn't use those values for creating the cached package.

I got around this bug by:
1. unzipping the nupkg file
2. changing the Title to match the ID in the nuspec file
3. re-packing it
4. replacing the package in Artifactory

**Comment by yishaigalatzer** [comment]
Can you provide a link to this artifcatory server for the specific package?

**Comment by claq2** [comment]
I'm afraid not. It's inside our company.

**Comment by yishaigalatzer** [comment]
Can you share the fiddler trace? I'm suspecting this is a bug in artifactory since the package installs fine from nuget.org

**Comment by claq2** [comment]
Yeah, it works for me from Nuget.org too. I'll have to recreate the full conversation Monday, but I do have some responses:

From Artifactory:
<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns="http://www.w3.org/2005/Atom" xml:base="http://evaultrepo.corp.ssv.com:8080/artifactory/api/nuget/nuget-local/">
    <id>http://evaultrepo.corp.ssv.com:8080/artifactory/api/nuget/nuget-local/Packages(Id='System.Management.Automation',Version='6.1.7601.17515')</id>
    <title type="text">System.Management.Automation.dll</title>
    <summary type="text">System.Management.Automation.dll</summary>
    <updated>2015-08-06T10:56:28Z</updated>
    <author>
        <name>Microsoft</name>
    </author>
    <link title="V2FeedPackage" href="Packages(Id='System.Management.Automation',Version='6.1.7601.17515')" rel="edit"/>
    <category scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" term="NuGetGallery.V2FeedPackage"/>
    <content type="application/zip" src="http://evaultrepo.corp.ssv.com:8080/artifactory/api/nuget/nuget-local/Download/System.Management.Automation/6.1.7601.17515"/>
    <m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">
        <d:lastUpdated>2015-08-06T10:56:28</d:lastUpdated>
        <d:Version>6.1.7601.17515</d:Version>
        <d:Copyright>Microsoft Corporation</d:Copyright>
        <d:Created m:type="Edm.DateTime">2015-08-06T10:56:32</d:Created>
        <d:Dependencies/>
        <d:Description>System.Management.Automation.dll</d:Description>
        <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
        <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
        <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
        <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
        <d:Language m:null="true"/>
        <d:Published m:type="Edm.DateTime">2015-08-06T10:56:32</d:Published>
        <d:PackageHash>vYGypqQE0x3RPhZsC6RsHnU/SAiPGFzpaj2CMRtgRZubXvpF+1zBHxnhCPa3puvO19QdYFxq76LpcevIYNYi2w==</d:PackageHash>
        <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
        <d:PackageSize m:type="Edm.Int64">2028689</d:PackageSize>
        <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
        <d:Title>System.Management.Automation.dll</d:Title>
        <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
        <d:Authors>Microsoft</d:Authors>
        <d:MinClientVersion m:null="true"/>
    </m:properties>
</entry>

Same response from Nuget.org:
<?xml version="1.0" encoding="UTF-8"?>
<entry xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns="http://www.w3.org/2005/Atom" xml:base="https://www.nuget.org/api/v2/">
    <id>https://www.nuget.org/api/v2/Packages(Id='System.Management.Automation',Version='6.1.7601.17515')</id>
    <category scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" term="NuGetGallery.V2FeedPackage"/>
    <link title="V2FeedPackage" href="Packages(Id='System.Management.Automation',Version='6.1.7601.17515')" rel="edit"/>
    <title type="text">System.Management.Automation</title>
    <summary type="text"/>
    <updated>2015-04-27T23:27:44Z</updated>
    <author>
        <name>Microsoft</name>
    </author>
    <link title="V2FeedPackage" href="Packages(Id='System.Management.Automation',Version='6.1.7601.17515')/$value" rel="edit-media"/>
    <content type="application/zip" src="https://www.nuget.org/api/v2/package/System.Management.Automation/6.1.7601.17515"/>
    <m:properties>
        <d:Version>6.1.7601.17515</d:Version>
        <d:NormalizedVersion>6.1.7601.17515</d:NormalizedVersion>
        <d:Copyright>Microsoft Corporation</d:Copyright>
        <d:Created m:type="Edm.DateTime">2013-03-29T17:16:45.727</d:Created>
        <d:Dependencies/>
        <d:Description>System.Management.Automation.dll</d:Description>
        <d:DownloadCount m:type="Edm.Int32">28760</d:DownloadCount>
        <d:GalleryDetailsUrl>https://www.nuget.org/packages/System.Management.Automation/6.1.7601.17515</d:GalleryDetailsUrl>
        <d:IconUrl m:null="true"/>
        <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
        <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
        <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
        <d:Language m:null="true"/>
        <d:Published m:type="Edm.DateTime">2013-03-29T17:16:45.757</d:Published>
        <d:PackageHash>vYGypqQE0x3RPhZsC6RsHnU/SAiPGFzpaj2CMRtgRZubXvpF+1zBHxnhCPa3puvO19QdYFxq76LpcevIYNYi2w==</d:PackageHash>
        <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
        <d:PackageSize m:type="Edm.Int64">2028689</d:PackageSize>
        <d:ProjectUrl m:null="true"/>
        <d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/System.Management.Automation/6.1.7601.17515</d:ReportAbuseUrl>
        <d:ReleaseNotes m:null="true"/>
        <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
        <d:Summary m:null="true"/>
        <d:Tags m:null="true"/>
        <d:Title>System.Management.Automation.dll</d:Title>
        <d:VersionDownloadCount m:type="Edm.Int32">28684</d:VersionDownloadCount>
        <d:MinClientVersion m:null="true"/>
        <d:LastEdited m:type="Edm.DateTime" m:null="true"/>
        <d:LicenseUrl m:null="true"/>
        <d:LicenseNames m:null="true"/>
        <d:LicenseReportUrl m:null="true"/>
    </m:properties>
</entry>

**Comment by claq2** [comment]
Here is the Fiddler trace of the Nuget VS plugin trying to restore the package:

    GET http://evaultrepo:8080/artifactory/api/nuget/nuget-local HTTP/1.0
    User-Agent: NuGet/2.8.60717.93 (Microsoft Windows NT 6.1.7601 Service Pack 1)
    Host: evaultrepo:8080


    HTTP/1.1 200 OK
    Server: Artifactory/3.8.0
    X-Artifactory-Id: 62f3dd8c028aa30b:-3b2d8e13:14eff26817e:-8000
    DataServiceVersion: 1.0
    Artifactory-UI-messages: []
    Content-Type: application/xml;charset=utf-8
    Date: Mon, 10 Aug 2015 12:22:11 GMT
    Connection: close

    <?xml version="1.0" encoding="utf-8" standalone="yes" ?><service xmlns="http://www.w3.org/2007/app" xml:base="http://evaultrepo:8080/artifactory/api/nuget/nuget-local/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:app="http://www.w3.org/2007/app"><workspace><atom:title>Default</atom:title><collection href="Packages"><atom:title>Packages</atom:title></collection></workspace></service>

------------------------------------------------------------------

    GET http://evaultrepo:8080/artifactory/api/nuget/nuget-local/Packages(Id='System.Management.Automation',Version='6.1.7601.17515') HTTP/1.1
    DataServiceVersion: 1.0;NetFx
    MaxDataServiceVersion: 2.0;NetFx
    User-Agent: NuGet Command Line/2.8.60717.93 (Microsoft Windows NT 6.1.7601 Service Pack 1)
    Accept: application/atom+xml,application/xml
    Accept-Charset: UTF-8
    Host: evaultrepo:8080
    Accept-Encoding: gzip, deflate


    HTTP/1.1 200 OK
    Server: Artifactory/3.8.0
    X-Artifactory-Id: 62f3dd8c028aa30b:-3b2d8e13:14eff26817e:-8000
    DataServiceVersion: 2.0
    Artifactory-UI-messages: []
    Content-Type: application/atom+xml;charset=utf-8
    Transfer-Encoding: chunked
    Date: Mon, 10 Aug 2015 12:22:11 GMT

    <?xml version='1.0' encoding='UTF-8'?>
    <entry xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xml:base="http://evaultrepo:8080/artifactory/api/nuget/nuget-local/">
      <id>http://evaultrepo:8080/artifactory/api/nuget/nuget-local/Packages(Id='System.Management.Automation',Version='6.1.7601.17515')</id>
      <title type="text">System.Management.Automation.dll</title>
      <summary type="text">System.Management.Automation.dll</summary>
      <updated>2015-08-10T08:19:31Z</updated>
      <author>
        <name>Microsoft</name>
      </author>
      <link rel="edit" title="V2FeedPackage" href="Packages(Id='System.Management.Automation',Version='6.1.7601.17515')"/>
      <category term="NuGetGallery.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
      <content type="application/zip" src="http://evaultrepo:8080/artifactory/api/nuget/nuget-local/Download/System.Management.Automation/6.1.7601.17515"/>
      <m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">
        <d:lastUpdated>2015-08-10T08:19:31</d:lastUpdated>
        <d:Version>6.1.7601.17515</d:Version>
        <d:Copyright>Microsoft Corporation</d:Copyright>
        <d:Created m:type="Edm.DateTime">2015-08-10T08:19:35</d:Created>
        <d:Dependencies></d:Dependencies>
        <d:Description>System.Management.Automation.dll</d:Description>
        <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
        <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
        <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
        <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
        <d:Language m:null="true"/>
        <d:Published m:type="Edm.DateTime">2015-08-10T08:19:35</d:Published>
        <d:PackageHash>vYGypqQE0x3RPhZsC6RsHnU/SAiPGFzpaj2CMRtgRZubXvpF+1zBHxnhCPa3puvO19QdYFxq76LpcevIYNYi2w==</d:PackageHash>
        <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
        <d:PackageSize m:type="Edm.Int64">2028689</d:PackageSize>
        <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
        <d:Title>System.Management.Automation.dll</d:Title>
        <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
        <d:Authors>Microsoft</d:Authors>
        <d:MinClientVersion m:null="true"/>
      </m:properties>
    </entry>



------------------------------------------------------------------

    GET http://evaultrepo:8080/artifactory/api/nuget/nuget-local/Download/System.Management.Automation/6.1.7601.17515 HTTP/1.0
    NuGet-Operation: Restore-Dependency
    NuGet-DependentPackage: System.Management.Automation
    NuGet-DependentPackageVersion: 6.1.7601.17515
    User-Agent: NuGet Command Line/2.8.60717.93 (Microsoft Windows NT 6.1.7601 Service Pack 1)
    Host: evaultrepo:8080


    HTTP/1.1 200 OK
    Server: Artifactory/3.8.0
    X-Artifactory-Id: 62f3dd8c028aa30b:-3b2d8e13:14eff26817e:-8000
    Last-Modified: Mon, 10 Aug 2015 12:19:31 GMT
    ETag: 96161d4089cd7ba3c4ea5d1903b91ee6224ce3a1
    X-Checksum-Sha1: 96161d4089cd7ba3c4ea5d1903b91ee6224ce3a1
    Accept-Ranges: bytes
    X-Checksum-Md5: 2e8a04154a60e9d173b878a6e5aaeea2
    X-Artifactory-Filename: System.Management.Automation.6.1.7601.17515.nupkg
    Content-Disposition: attachment; filename="System.Management.Automation.6.1.7601.17515.nupkg"; filename*=UTF-8''System.Management.Automation.6.1.7601.17515.nupkg
    Content-Type: application/x-nupkg
    Content-Length: 2028689
    Date: Mon, 10 Aug 2015 12:22:11 GMT
    Connection: close

    <binary response containing nupkg file>

**Comment by yishaigalatzer** [comment]
@MeniZalzman please investigate this report. I'm suspecting Artifactory 4.0 is sending data we don't expect. It is worth validating in the NuGet 3.1.1 as well as Command Line 3.1.1.

In general we want to deal with misbehaving servers in a nice way and not nullref

**Comment by rohit21agrawal** [comment]
@claq2 Did you notice that at that time that nuget.org was sending a different title value than the artifactory server?

However, it seems like Artifactory has fixed this on their end (verified using  version 4.7.1) and they now send the right value in title.

Closing this issue for now - if you still see this issue, or upgrading to a newer artifactory version is not an option for you, please feel free to reactive this bug.
