### ISSUE TITLE
Package Source Mapping UI - Allow a source to be pinned as default (ie. set `*`) in the NuGet Options -> Package Sources view.

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#11364]
Refer to https://github.com/nuget/home/issues/11361 and https://github.com/NuGet/Home/blob/dev/implemented/2021/PackageSourceMapping.md

**Comment by donnie-msft** [comment]
Note: There's a long discussion about why we shouldn't implement the topic of this issue.
See: https://github.com/NuGet/Home/pull/11865#discussion_r899650092

**Comment by donnie-msft** [comment]
Closing based on comment https://github.com/NuGet/Home/issues/11364#issuecomment-1158434597
