### ISSUE TITLE
Package Source Mapping UI - Allow the Creation/Removal of package source mappings in the NuGet Options UI

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#11363]
Blocked on https://github.com/NuGet/Home/issues/11362

Refer to https://github.com/nuget/home/issues/11361 and https://github.com/NuGet/Home/blob/dev/implemented/2021/PackageSourceMapping.md

**Comment by donnie-msft** [comment]
Rough estimate is you can look for the introduction of this feature in 17.5 Preview 1
