### ISSUE TITLE
[Feature]: Settings for nuget cache behaviour

### ISSUE THREAD

**Issue by WhiteBlackGoose** [NuGet/Home#11369]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

It would be nice to be able to
1. Change the location of the folder with cache
2. Limit the maximum size of the cache storage or completely disable cache

The reason is simply because nuget cache takes insane amount of space on the user folder. I "purged" it recently, and it already takes 10Gb. That's simply way too much, and in my case it makes it much harder to manage space, if some package manager can consume everything.

Let me know if I need to move it to sdk repo or somewhere else.

**Comment by heng-liu** [comment]
Hi @WhiteBlackGoose , thanks for taking time raising this issue!
I'm not sure if you are talking about [global package folder](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders).
If yes, you could override using the NUGET_PACKAGES environment variable.
By the way, you could use [command ](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#clearing-local-folders) to clear the global package folder. 
The next time when you run restore or build(with explicit restore), the needed packages will be in global package folder again.

**Comment by heng-liu** [comment]
By the way, global package folder is not a cache. As for package reference, all packages are consumed from the global packages folder. So there is no way to disable cache, if you mean global package folder.

And there is an issue https://github.com/NuGet/Home/issues/4980 discussing about the clean up policy of global package folder.

**Comment by WhiteBlackGoose** [comment]
Ohhh, thanks a lot!

**Comment by zivkan** [comment]
There's also a nuget.config setting, `globalPackagesFolder`, which can be set (for example in your user profile nuget.config, so that it applies to all solutions you open on the computer): https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file
