### ISSUE TITLE
Intellisense in package manager console in visual studio 2015 is broken

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1137]
At least on my machine, Visual Studio 2015 + Win 10 tools 1.0 + nuget 3.1.1 there is not intellisense in the PowerShell console

**Comment by deepakaravindr** [comment]
We haven't heard any user feedback on this for now, moving out from 3.3, as the priority seems low

**Comment by zodrog** [comment]
Indeed it is...
My configuration: vs2015 Enterprise v14.0.24720.00 Update 1, Windows 10, Package Manager Console Host Version 3.3.0.167

**Comment by workabyte** [comment]
been having this issue for a long time myself
[edit] not sure how my comment unassigned @deepakaravindr .....

**Comment by TecProTools** [comment]
Intellisense not displaying in the package manager console window on my machine: VS Community 2015 Update 3.3, Windows 10Pro, Package Manager Console Host Version 3.5.0.1484

**Comment by nkolev92** [comment]
At this point we are not doing any work to support VS 2015.
This issue does not reproduce in VS 2017.
