### ISSUE TITLE
[Bug]: Visual Studio 2019 16.11.5 Enterprise advices me to update nuget package to version that is incompatible with my project TFM

### ISSUE THREAD

**Issue by bairog** [NuGet/Home#11372]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

dotnet sdk version: 6.0.100, msbuild version: 4.8.3752.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have an ASP Core project that targets **.net5.0** TFM. I reference several **EntityFramework** nuget packages (**Microsoft.EntityFrameworkCore.*** and **Microsoft.AspNetCore.***) that are currently at version **5.0.12**. It is the latest version that is compatible with **.net5.0** TFM. But Visual Studio 2019 16.11.5 Enterprise advices me to update nuget packages to version **6.0.0** that is incompatible with my project TFM (it is compatible only with **.net6.0** TFM).
![image](https://user-images.githubusercontent.com/44995181/141057099-504bb466-6d0e-4d4a-9552-369bdecf0f42.png)

P. S. I also have Visual Studio 2022 17.0.0 Communuty Current istalled side-by-side.

**Comment by Sfairait** [comment]
Same issue for me

**Comment by heng-liu** [comment]
Thanks @bairog for taking time filing this issue!
We currently don't support filtering by TFM when updating/installing/etc. This means that we just go by version number, even if the new version number happens to be incompatible with the current project's TFM(s). 
We have an issue about adding this feature at https://github.com/NuGet/Home/issues/5725.
So this issue will be closed as duplicate.
