### ISSUE TITLE
[Bug]: Nuspec file with wildcard and  / instead of \ skipped in 6.0.0 but works in 5.1.1 

### ISSUE THREAD

**Issue by jhoneill** [NuGet/Home#11389]
### NuGet Product Used

NuGet.exe

### Product Version

6.0.0

### Worked before?

5.1.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I had a single line in the files section of a one nuspec file
```
 <file src="./PowerShellScripts/*"  target="/PowerShellScripts" />
```
In 5.1.1 this worked. Azure devops updated to 6.0 and the pipeline where nuget.exe runs reported
```
Error NU5017: Cannot create a package that has no dependencies nor content.
```
I was able to repro this at the command line by downloading 6.0
A second nuspec file was _not_ reporting the error 
```
<file src="./PowerShellScripts/Enable-Https*"     target="/PowerShellScripts" />
<file src="./PowerShellScripts/Helper.ps1"   target="/PowerShellScripts" />
```
The first line is **skipped silently** and only helper.ps1 goes into the package.  This is more of a problem because the command **appears to complete successfully, but produces a faulty package.** 

If I replace **/** with **\\**  everything works as it should. 

I'll apologize for my ignorance, but I don't know which of the following is the case: 
*  / as a path separator should _never_ have worked,  and this breakage was intentional, but I'm looking in the wrong place for  documentation of that (but shouldn't non-wildcards break too ?) 
*  / as a path separator wasn't intended to work,  but this breakage was unintentional, and a bug
* / as a path separator should work,  and this is a bug

**Comment by dominoFire** [comment]
Related [11234](https://github.com/NuGet/Home/issues/11234)

**Comment by nkolev92** [comment]
Closing as dup of #11234
