### ISSUE TITLE
[Bug]: PackageSourceMapping inconsistencies should be reported

### ISSUE THREAD

**Issue by lanfeust69** [NuGet/Home#11385]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

When there is a no source matching the source name of a `<packageSourceMapping>` (typically a typo, or maybe after a git merge), a restore can fail with a very generic error
```
error NU1100: Unable to resolve '<package>' for '<framework>'
```

### Desired Behavior

There should be a more helpful message.

Maybe a warning at the beginning if there is no source corresponding to a `<packageSourceMapping>` entry.

**Comment by kartheekp-ms** [comment]
Once this issue has been fixed, we may have to update the docs to address https://github.com/NuGet/docs.microsoft.com-nuget/issues/2571

**Comment by nkolev92** [comment]
Reviewing NU1102 and the likes also makes sense for these scenarios.
