### ISSUE TITLE
"nuget sources add" does not support setting NuGet API version

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#11396]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/nuget-sources-add-does-not-support-set/1585758)._

---
[severity:It's more difficult to complete my work]
When running "nuget sources add" command, it does not support setting NuGet API version.  There should be an option to set the "protocolVersion" parameter in the NuGet.Config file that is written.  The only workaround is to manually edit the config file, but is shared build servers and hard to automate.

---
#### Feedback Bot on 11/17/2021, 01:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/9170
