### ISSUE TITLE
The fallback for secondary search endpoint doesn't work 

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#11400]
@loic-sharma mentioned:  NuGet client will try the "primary" search endpoint, and if that fails, fallback to the "secondary" search endpoint does not happen

@zivkan helped finding the fallback at: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs#L113
But it doesn't seem to retry:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs#L174
Haven't investigated more. Just create this in case we forget about it.

**Comment by nkolev92** [comment]
The retry is happening in a different layer. 
Through: https://github.com/NuGet/NuGet.Client/blob/a8b6b1fb3a1bccd207a83612cd0f5e1f4ff1d0b8/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs#L102,  which goes to https://github.com/NuGet/NuGet.Client/blob/a8b6b1fb3a1bccd207a83612cd0f5e1f4ff1d0b8/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs#L226, which goes to https://github.com/NuGet/NuGet.Client/blob/a8b6b1fb3a1bccd207a83612cd0f5e1f4ff1d0b8/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSource.cs#L202 which goes to https://github.com/NuGet/NuGet.Client/blob/a8b6b1fb3a1bccd207a83612cd0f5e1f4ff1d0b8/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSource.cs#L339. 
HttpRetryHandler handles the retrying in https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRetryHandler.cs

**Comment by zivkan** [comment]
The issue is about fallback to secondary search servers defined in the service index, not retrying the same URL.

**Comment by loic-sharma** [comment]
Do y'all have telemetry on how often a customer's search request fails?

**Comment by aortiz-msft** [comment]
Should this be moved to Icebox?

**Comment by loic-sharma** [comment]
It looks like the fallback does work. I broke nuget.org's primary search (by making azuresearch-usnc.nuget.org point to 127.0.0.1 in my host file, kudos to Joel for this trick) and Visual Studio's search still worked:

![image](https://user-images.githubusercontent.com/737941/152230931-2419c3ab-95fb-48de-b5bb-c37fd89d74a7.png)

I think we can close this, but will wait for @heng-liu or @zivkan to confirm.

**Comment by zivkan** [comment]
Triage:  We trust Loic 😄
