### ISSUE TITLE
[DCR]: improve HTTP authentication flow for package sources

### ISSUE THREAD

**Issue by chucker** [NuGet/Home#11402]
### NuGet Product(s) Affected

Visual Studio Package Management UI

### Current Behavior

VS doesn't appear to have a well-defined UI for prompting for NuGet package source credentials. For some (not all?) users, there was a message in **Output** that simply asked the user to use interactive mode for authentication. This is cumbersome, because an IDE _is_ already the interactive mode, and it isn't clear for a user how to proceed.

Instead, the answer appears to be: ignore the IDE and instead use the CLI tooling to edit the source and enter credentials there.

### Desired Behavior

Ideally, Tools | Options | NuGet | Sources would have additional UI, such as a `[x] This source requires credentials` checkbox. Either, ticking it reveals further `Login` / `Password` fields, or, they come up as a dialog the first time you try to access that source.

### Additional Context

We recently moved a NuGet server that used to be behind a VPN to a public machine, but behind HTTP authentication.

**Comment by chucker** [comment]
(Last tested several months ago, with VS 2019, but I was asked to file this nonetheless.)

**Comment by nkolev92** [comment]
Hey @chucker, 

There's definitely some work that needs to be done here, in particular https://github.com/NuGet/Home/issues/7814 and many other issues related to Azure DevOps feeds in particular.

> For some (not all?) users, there was a message in Output that simply asked the user to use interactive mode for authentication.

The authentication experience in NuGet is driven through Extensibility, which means it is on the package source owners to provide the proper mechanics, https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#visual-studio. 

What kind of sources do you get the interactive prompts for?

Can you please provide info about the exact message (it'd great to understand where it's coming from). 
Is it in the output window? Somewhere else?

> Instead, the answer appears to be: ignore the IDE and instead use the CLI tooling to edit the source and enter credentials there.

We try to provide extensibility that helps customers avoid having to add credentials in their configs.
In the end, we can also do as much as the package source owners are willing to go.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
