### ISSUE TITLE
Reduce heap allocations in ResolverUtility.FindLibraryByVersionAsync

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11409]
@kartheekp-ms commented on [Tue Nov 23 2021](https://github.com/NuGet/Client.Engineering/issues/1314)

While working on https://github.com/nuget/client.engineering/issues/1057 issue, I noticed that `ResolverUtility.FindLibraryByVersionAsync` method https://github.com/NuGet/NuGet.Client/blob/a8b6b1fb3a1bccd207a83612cd0f5e1f4ff1d0b8/src/NuGet.Core/NuGet.DependencyResolver.Core/ResolverUtility.cs#L363 has following warnings reported by the `PerformanceSensitive` analyzers.

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Warning | HAA0302 | The compiler will emit a class that will hold this as a field to allow   capturing of this closure | NuGet.DependencyResolver.Core (net472) | ~\NuGet.Client-W1\src\NuGet.Core\NuGet.DependencyResolver.Core\ResolverUtility.cs | 365 | Active
Warning | HAA0301 | Heap allocation of closure Captures:   libraryRange,framework,cacheContext,logger,token | NuGet.DependencyResolver.Core (net472) | ~\NuGet.Client-W1\src\NuGet.Core\NuGet.DependencyResolver.Core\ResolverUtility.cs | 373 | Active
Warning | HAA0302 | The compiler will emit a class that will hold this as a field to allow   capturing of this closure | NuGet.DependencyResolver.Core (net472) | ~\NuGet.Client-W1\src\NuGet.Core\NuGet.DependencyResolver.Core\ResolverUtility.cs | 423 | Active

This method has ~880 MB allocations during solution restore for OrchardCore solution https://github.com/OrchardCMS/OrchardCore/tree/75923732c36d2785cb869affb805f0ff19d1847c

![image](https://user-images.githubusercontent.com/52756182/143098452-39101c02-b521-4410-89a1-e4c76b4eeed3.png)

**Comment by aortiz-msft** [comment]
@kartheekp-ms - Would you please get us memory allocations before and after this change?

**Comment by kartheekp-ms** [comment]
@aortiz-msft - The heap allocations have reduced by **200 MB** after the fix for OrchardCore solution restore scenario. I added more details to the PR description. https://github.com/NuGet/NuGet.Client/pull/4348
