### ISSUE TITLE
PackageSearchMetadata allocates PackageIdentity on every access to the identity property. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#11401]
https://github.com/NuGet/NuGet.Client/blame/dev/src/NuGet.Core/NuGet.Protocol/Model/PackageSearchMetadata.cs#L47
![image](https://user-images.githubusercontent.com/8766776/142551366-e449fe70-5a26-454d-85ae-514e5cffba8d.png)

**Comment by nkolev92** [comment]
cc @davkean @zivkan @donnie-msft

**Comment by kartheekp-ms** [comment]
@erdembayar @aortiz-msft - I added `PerfWins` label to this issue because the improvements are great.
