### ISSUE TITLE
Ability to add the same version of an installed package from 1 project to another

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1140]
Ability to add the same version of an installed package from 1 project to another

From a customer:
<i> It happens very often that you DO NOT want to update the package to the latest available because you can mess all the tests. Therefore when adding a new project to an existing solution, we used to "manage the package for the solution" and simply add the checkbox for this new project. This ensured that we could have the exact same version of the package. </i>

**Comment by raffaeler** [comment]
Thank you Deepak for filing it

**Comment by yishaigalatzer** [comment]
Please verify this as part of manage packages for solution

**Comment by yishaigalatzer** [comment]
This is doable now from solution level package management (3.3)

Note we plan to keep enhancing the usability of that dialog, but it is now easily doable.
