### ISSUE TITLE
[Bug]: weird NU5128 error for a runtime-only package

### ISSUE THREAD

**Issue by bitbonk** [NuGet/Home#11415]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 3.1.415

### Worked before?

.NET SDK 3.1.116

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We have a `MyProject.RuntimeOnlyDeps.nuspec` file inside a `MyProject.RuntimeOnlyDeps` folder with a `MyProject.RuntimeOnlyDeps.csproj` that targets  `netcoreapp3.1` and that is needed to deploy some assemblies to the build output that need to be loaded by the app but should never be added as reference to the consumer of our nuget packages.

`MyProject.RuntimeOnlyDeps.nuspec` has the following content.

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>MyProject.RuntimeOnlyDeps.nuspec</id>
    <version>1.2.3456</version>
    ...
  </metadata>
  <files>
    <file src="_._" target="ref\netcoreapp3.1" />
    <file src="bin\Release\netcoreapp3.1\Contoso*.dll" target="lib\netcoreapp3.1"/>
  </files>
</package>
```

When we pack using `dotnet pack MyProject.RuntimeOnlyDeps.csproj` with SDK 3.1.116 or SDK 3.1.415 (no difference here) we get the following errors:

> error NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: 
> error NU5128: - Add a dependency group for .NETCoreApp3.1 to the nuspec [c:\build\_work\342\s\src\MyProject.RuntimeOnlyDeps\MyProject.RuntimeOnlyDeps.csproj]

Can this error be solved? If so, how?  I don't see how I could "add a dependency group for .NETCoreApp3.1 to the nuspec" in this case.

Furthermore, on the Azure Devops Server build pipeline we have `WarningsAsErros` enabled. There with SDK 3.1.116 the build did not break despite the aforementioned errors. with SDK 3.1.415 however, the build suddenly breaks. Why this change in behavior?  Was it just a bug in SDK 3.1.116 ?

**Comment by erdembayar** [comment]
~~I was not able to repro the issue, it looks we may actual repro for this.~~
I can repro this issue.

```
dotnet pack MyProject.RuntimeOnlyDeps.csproj -p:NuspecFile=MyProject.RuntimeOnlyDeps.nuspec
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp1 -> C:\NuGetProj\IssueRepro\11415\ConsoleApp1\bin\Debug\netcoreapp3.1\ConsoleApp1.dll
  MyProject.RuntimeOnlyDeps -> C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\net5.0-windows\MyProject.RuntimeOnlyDeps.dll
  MyProject.RuntimeOnlyDeps -> C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\netcoreapp3.1\MyProject.RuntimeOnlyDeps.dll
C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: Some target frameworks declared in the dependencies group of the nuspec and the lib/ref folder do not have exact matches in the other location. Consult the list of actions below: [C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\MyProject.RuntimeOnlyDeps.csproj]
C:\Program Files\dotnet\sdk\6.0.100\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): warning NU5128: - Add lib or ref assemblies for the net5.0-windows7.0 target framework [C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\MyProject.RuntimeOnlyDeps.csproj]
  Successfully created package 'C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\MyProject.RuntimeOnlyDeps.nuspec.1.2.3456.nupkg'.
```

**Comment by erdembayar** [comment]
@bitbonk 
`dotnet pack MyProject.RuntimeOnlyDeps.csproj -p:NuspecFile=MyProject.RuntimeOnlyDeps.nuspec`
I added `dependencies` section into nuspec file then NU5128 warnings disappeared.

```
<?xml version="1.0" encoding="utf-8"?>
<package >
  <metadata>
    <id>MyProject.RuntimeOnlyDeps.nuspec</id>
    <version>1.2.3456</version>
    <title>MyProject.RuntimeOnlyDeps</title>
    <authors>Me, You</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <description>ggg</description>
    <copyright>MIT</copyright>
    <tags>my project best</tags>
    <dependencies>
      <group targetFramework=".NETCoreApp3.1">
        <dependency id="ConsoleApp1" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="AutoMapper" version="10.1.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkReferences>
      <group targetFramework=".NETCoreApp3.1">
      </group>
    </frameworkReferences>
  </metadata>
  <files>
    <!-- <file src="_._" target="ref\netcoreapp3.1" /> -->
    <file src="bin\Debug\netcoreapp3.1\ConsoleApp*.dll" target="lib\netcoreapp3.1"/>
  </files>
</package>
```
```
dotnet pack MyProject.RuntimeOnlyDeps.csproj -p:NuspecFile=MyProject.RuntimeOnlyDeps.nuspec
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  ConsoleApp1 -> C:\NuGetProj\IssueRepro\11415\ConsoleApp1\bin\Debug\netcoreapp3.1\ConsoleApp1.dll
  MyProject.RuntimeOnlyDeps -> C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\net5.0-windows\MyProject.RuntimeOnlyDeps.dll
  MyProject.RuntimeOnlyDeps -> C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\netcoreapp3.1\MyProject.RuntimeOnlyDeps.dll
  Successfully created package 'C:\NuGetProj\IssueRepro\11415\MyProject.RuntimeOnlyDeps\bin\Debug\MyProject.RuntimeOnlyDeps.nuspec.1.2.3456.nupkg'.

```

Please add `dependencies` section for your dependency packages, let me know if fixes your issue.

**Comment by bitbonk** [comment]
The error indeed go away if I add an (empty)  `<dependencies>`  element like this:

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>MyProject.RuntimeOnlyDeps.nuspec</id>
    <version>1.2.3456</version>
    ...
    <dependencies>
        <group targetFramework=".NETCoreApp3.1" />
    </dependencies>
  </metadata>
  <files>
    <file src="_._" target="ref\netcoreapp3.1" />
    <file src="bin\Release\netcoreapp3.1\Contoso*.dll" target="lib\netcoreapp3.1"/>
  </files>
</package>
```

I still don't understand why this should be necessary though. Is this any better than disabling the NU5128 error altogether for this project?

**Comment by zivkan** [comment]
NuGet treats it as a warning. If you're seeing it as an error, it means your project has opt into treating warnings as errors.  Like other warnings you can `<NoWarn>$(NoWarn);NU5128</NoWarn>` if you wish, or stop treating warnings as errors.

The reason the warning exists is because currently neither Visual Studio's package manager UI, nor nuget.org, provide you with any feedback for what target frameworks a package actually supports. However, both show you dependency groups, even if they're empty. Therefore, by encouraging package authors to create empty dependency groups for their packages, package consumers can see about what target frameworks the package probably supports (even if it's technically not 100% accurate). When we, the NuGet team, run surveys, one of the common requests we get is to help developers understand whether or not a package is compatible with their project, and while this pack warning is not a 100% solution to that problem, it helps improve the situation a little bit.

Also, for what it's worth, when I do a web search for NU5128, the first hit I see is for our official docs: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5128.  that might have been a quicker way to find a solution.

**Comment by bitbonk** [comment]
Thanks, that makes sense. I am pretty sure I have stumbled across the NU5128 error docs you mentioned but somehow I did not come to the right conclusion. 😊
