### ISSUE TITLE
[Bug]: Should "nuget update --self" update to version 6.0?

### ISSUE THREAD

**Issue by Rand-Random** [NuGet/Home#11426]
The command "nuget update --self" only updated to the latest minor version 5.11.x.
Not sure if that behaviour is desired or not.

**Comment by erdembayar** [comment]
It'll be rectified soon. It's in process, we wait for 2-3 weeks before make it default to prevent from any regression.

**Comment by nkolev92** [comment]
6.0 has been published, https://www.nuget.org/packages/NuGet.CommandLine/6.0.0. 

Update -Self should now work.
