### ISSUE TITLE
[Bug]: The status of installed package with “PackagesReference” format is incorrect in “Installed”/“Updates” Tab

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11425]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.1.0.66

### Worked before?

Dev\6.1.0.64

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Create a C# Console App (.NET Framework) project.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Install a package (e.g. “Newtonsoft.Json”), not the latest one (e.g. “11.0.1”) with “PackagesReference” format. 
4. Click the “Installed”/“Updates” Tab.

## Expected: 
The status of installed package with “PackagesReference” format is correct in “Installed”/“Updates” Tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/144213716-96f5c80b-6f89-4534-b2a9-948a22221b07.png)

## Actual: 
The status of installed package with “PackagesReference” format is incorrect in “Installed”/“Updates” Tab as below screenshot.
 
![image](https://user-images.githubusercontent.com/71433406/144213745-9da8b0a1-8e8b-45da-9ce1-4d1125f9288d.png)

## Notes:
1. The issue doesn't repro on NuGet Client Dev\6.1.0.64.
2. The issue doesn’t repro with the Packages.Config format.

**Comment by donnie-msft** [comment]
@v-crchang Hello, thanks for finding this one. What is your Package Source dropdown at the time of this error (in your Actual section screenshots)?
Does it automatically change to something different? For example, "Visual Studio Offline Packages"?

**Comment by v-crchang** [comment]
@donnie-msft I am using the "nuget.org" Package Source, it will not automatically change to something different.

**Comment by donnie-msft** [comment]
@v-crchang Thanks for confirming. Today, could you try this repro again, and if you repro, submit to us a VS Feedback ticket with a screen recording? We will also get a trace that way we can analyze.
Thank you!

**Comment by v-crchang** [comment]
@donnie-msft I can still repro this issue on Dev\6.1.0.68. I submit a VS Feedback ticket [1601679](https://developercommunity.visualstudio.com/t/the-status-of-installed-package-with-packagesrefer/1601679?from=email). You can trace the issue with the Feedback ticket.
