### ISSUE TITLE
unable to restore packages in vs 2015 and NuGet v3

### ISSUE THREAD

**Issue by wanghaolu** [NuGet/Home#1143]
unable to restore packages in vs2015 and nuget V3..
the alert me " unable to find version '*****' of package '*******' "
![default](https://cloud.githubusercontent.com/assets/9586655/9150282/ad6a0c2c-3e03-11e5-88b7-f06dcbe3f939.PNG)

**Comment by bhuvak** [comment]
@wanghaolu , I am not able to repro the scenario and I can install both versions of enterpriselibrary.common package. 
Can you try installing it via powershell console and provide us the output traces ( from "Output window"). Also can you capture the fiddler traffic and attach us the log ? Make sure to turn on https decryption ( tools --> fiddler options --> https).
Any further details around narrowing it down would help : Do you get this error only for this specific package, does it work if you chose v2 source ( https://nuget.org/api/v2) ?

**Comment by wanghaolu** [comment]
@bhuvak  this error for all packages. but when I use the commandline to restore those packages are all success.
following picture is the screen shout for fiddler. You can download the fiddler log file from http://pan.baidu.com/s/1pJkmcHX
![default](https://cloud.githubusercontent.com/assets/9586655/9199954/fb9a6de4-4077-11e5-9145-a8868806e7de.PNG)

**Comment by bhuvak** [comment]
@wanghaolu , thanks for sharing the logs. I am looking in to it. Meanwhile, can you confirm in which version of command line you tried it out ?

**Comment by bhuvak** [comment]
@wanghaolu , also what project template are you using ?

**Comment by wanghaolu** [comment]
@bhuvak , project template is asp.net mvc 5.0 and class library, using .net framework 4.5.2.
the version of command line is 2.8.6

**Comment by bhuvak** [comment]
@wanghaolu , are you able to access the url via browser
https://api.nuget.org/packages/nhibernate.4.0.3.4000.nupkg
https://api.nuget.org/packages/fluentvalidation.5.6.2.nupkg

**Comment by wanghaolu** [comment]
@bhuvak , yes, can access via browser.

**Comment by bhuvak** [comment]
Do you have any resharper tools installed ? We noticed a similar issue without another user last week and it turned out to be an issue with resharper dotpeek. So want to quickly cross check.

**Comment by wanghaolu** [comment]
@bhuvak ,yes, i have been installed resharper 9.

**Comment by bhuvak** [comment]
@wanghaolu , thanks for confirming. Can you try uninstalling the resharper tools or better yet try on a clean image and see how it goes ?

**Comment by wanghaolu** [comment]
@bhuvak , I'm tried it. It's also alert me unable to find pakcage.

**Comment by yishaigalatzer** [comment]
@wanghaolu can you try again today, and tell us what packages are failing right now?

**Comment by jackywang615** [comment]
@yishaigalatzer , I upload the fiddler log file into http://pan.baidu.com/s/1c09B8fY, you can download it.

**Comment by yishaigalatzer** [comment]
@wanghaolu can you please update to 3.3, and tell us if this is still an issue?

CC @joyhui

**Comment by jackywang615** [comment]
@yishaigalatzer issue is solved. thank you.

**Comment by dotnetchris** [comment]
Solution was created in VS2013 with Nuget.org v2

Colleague setup a new machine with VS2015, out of box it uses Nuget.org v3

Colleague could not get packages to restore. 

Work around was to modify the solution level nuget.config to add `<add key="Nuget.org v2" value="https://www.nuget.org/api/v2/" />` as an explicit package source.

I really don't understand why this had to be done. https://www.nuget.org/packages/DapperExtensions/ was the exact package it refused to restore without that explicit entry (latest version 1.4.4)

**Comment by yishaigalatzer** [comment]
I just tried your scenario with NuGet 3.3 and Visual Studio Update I and I don't see anything going on.

So I would suggest a few things:
1. Update to NuGet 3.3
2. There was an outage in the CDN a couple of days ago, does this happen right now?

As your report does not seem to be directly related to this I would appreciate that if you are still seeing issue, would you be able to open a separate bug and share your nuget.config and a sample project that reproduces this issue?

I'm going to go ahead and close this specific issue for now. I'll obviously keep monitoring your comments here.

**Comment by dotnetchris** [comment]
My colleague already had the latest version of Nuget, this happened within minutes of when i posted today so not during the CDN outage you mentioned.

**Comment by yishaigalatzer** [comment]
If you can still reproduce this, please open a new bug like I suggested and add a fiddler trace from your machine if possible
