### ISSUE TITLE
[Bug]: [Pack] No restore info shows in the CLI when running command “dotnet pack --no-dependencies”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11430]
### NuGet Product Used

dotnet.exe

### Product Version

Dotnet SDK Version: 6.0.200-preview.21573.3

### Worked before?

Worked on Dotnet SDK Version: 5.0.200-preview.21077.7

### Impact

It bothers me. A fix would be nice

#### Details about the problem
VS Version: Main\32002.62
NuGet Version: Dev\6.1.0.68
OS Version: Windows-11-Enterprise-21H2

#### Repro steps
1. Create a solution with two C# ClassLibrary (.NET 6.0) projects.
2. Make the project1 reference project2.
3. Open CLI and go to the path of above solution. 
4. Run the command “dotnet pack --no-dependencies”.

#### Expected
There should be only one restore info for the project1 (like “Restored …\project1.csproj”) in the CLI as the [dotnet pack doc](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x) said as below.
![image](https://user-images.githubusercontent.com/20632625/144576288-05eaf5af-6a0c-45d0-8589-cee8ca699ebd.png)
Worked on Dotnet SDK Version: 5.0.200-preview.21077.7 as below.
![image](https://user-images.githubusercontent.com/20632625/144578096-dee6cfd5-8e08-41e5-a096-39896ef99dbf.png)

#### Actual
No restore info shows in the CLI as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/144576551-8f50c3a2-6e0f-41b5-99ed-ad1b69e14b6e.png)

**Comment by erdembayar** [comment]
I was not able to repro `expected` part, I used "5.0.209" version

```
 dotnet pack --no-dependencies
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\NuGetProj\IssueRepro\11430\11430b\Class1\Class1.csproj (in 69 ms).
  Class2 -> C:\NuGetProj\IssueRepro\11430\11430b\Class2\bin\Debug\net5.0\Class2.dll
  Class1 -> C:\NuGetProj\IssueRepro\11430\11430b\Class1\bin\Debug\net5.0\Class1.dll
  Successfully created package 'C:\NuGetProj\IssueRepro\11430\11430b\Class1\bin\Debug\Class1.1.0.0.nupkg'.
C:\NuGetProj\IssueRepro\11430\11430b> dotnet --version
5.0.209
```

Also, I don't get why both csprojs are packed same time. It looks I'm missing another context  here.

**Comment by v-luzh** [comment]
Hi @erdembayar, just want to make sure if you had the step2: project1->project2 (project1 reference project2).

**Comment by erdembayar** [comment]
> Hi @erdembayar, just want to make sure if you had the step2: project1->project2 (project1 reference project2).

Yes, I did it. There's tiny bit difference in logging, most likely due to no-op restore. In general packing wouldn't even start without successful restore, you can see restore did happen.

![image](https://user-images.githubusercontent.com/8766776/144875401-f4b1b3b9-aecd-47d6-b612-33fd755f1af5.png)

**Comment by v-luzh** [comment]
Hi, @erdembayar, I think your repro is expected result (only the first project should be restored) for this bug, You can see there is no restored info in my actual result (that's the issue) above. Can you repro my actual result in latest VS main build with .NET SDK 6.0?

And as you said  **"Also, I don't get why both csprojs are packed same time. It looks I'm missing another context here"**, do you mean it is another bug (only the first project should  be packed)?

**Comment by kartheekp-ms** [comment]
@v-luzh - I followed the repro steps except that I added `Newtonsoft.Json` package to `project1` and then executed `dotnet pack --no-dependencies` which produced the following excepted output.

![image](https://user-images.githubusercontent.com/52756182/145662460-bd79187f-9d8b-4b88-8057-be6bb4b0600c.png)

The behavior seems to be working as expected. What do you think?

**Comment by v-luzh** [comment]
@kartheekp-ms Yes, I got the same output as yours after I added `Newtonsoft.Json` package to project1 and then executed `dotnet pack --no-dependencies`. But I got the wrong result (as below) after I added `Newtonsoft.Json` package to project1 & `Castle.Core` package to project2.
![image](https://user-images.githubusercontent.com/20632625/147226953-fdfde165-d9ca-405c-b03c-e1e29ffdf081.png)

**Comment by zivkan** [comment]
@v-luzh when `dotnet pack` is run, are you running it in the directory that contains the solution file, or are you running it from the directory containing "project1" only?

All MSBuild commands, including pack, restore, and build, when run on a solution file, will run the target on all projects in the solution.

This means that `dotnet pack --no-dependencies whatever.sln` is equivalent to running pack on both `project1` and `project2`. So, even if `project1` is packed/restored with `--no-dependencies`, `project2` is going to be included anyway because it's in the solution.

Therefore, this is only a bug if you cd to `project1`'s directory and run the command, however, looking at your screenshot, your current directory is where I would expect the solution file to be, not one of the project files.

**Comment by v-luzh** [comment]
@zivkan Got it. Yes, it would only restore the project1 after I cd to project1's directory and run the command. So, the expected pre-step of running the `dotnet pack --no-dependencies` is going to the project1's directory, correct?

**Comment by zivkan** [comment]
Yes. 

For what it's worth, `--no-dependencies` is only used by restore. It's just that the .NET CLI implicitly restores projects unless `--no-restore` is passed (or in the case of pack, test, or publish, if `--no-build` is passed). Therefore, this issue actually has nothing to do with pack, and would work the same with `dotnet restore --no-dependencies`.
