### ISSUE TITLE
dotnet list package outdated doesn't suggest stable version

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11439]
Create simple console app then add Serilog  2.10.0-dev-01245.
When you do `dotnet list package outdated`, it should suggest "2.10" stable according to VS.

```
   [netcoreapp3.1]:
   Top-level Package         Requested             Resolved              Latest
   > Serilog                 2.10.0-dev-01245      2.10.0-dev-01245      2.11.0-dev-01377
```
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/f683c112-174e-4c65-b7ad-3e11d344a561)

Output for `dotnet list package outdated --include-prerelease` is fine.

```
   [netcoreapp3.1]:
   Top-level Package         Requested             Resolved              Latest
   > Serilog                 2.10.0-dev-01245      2.10.0-dev-01245      2.11.0-dev-01377
```

**Comment by nkolev92** [comment]
There might be a thing where if the current verison is prerelease, the command may return prerelease results as well.
