### ISSUE TITLE
[Bug]: No fallback mechanism for projects without IVsRestoreInfoSource implementation blocks package restore, build, IntelliSense for supported projects

### ISSUE THREAD

**Issue by madkat** [NuGet/Home#11440]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console, Other/NA

### Product Version

NuGet.VisualStudio.dll 6.0.0.275-6.0.1.1 (Visual Studio 2022)

### Worked before?

Worked in Visual Studio 2019 and earlier.

### Impact

I'm unable to use this version

### Repro Steps & Context

There is no fallback mechanism in place for project systems that do not implement IVsRestoreInfoSource. As a result, IsAllProjectsNominatedAsync() will never return true and the NuGet restore for the solution will never complete. This blocks IntelliSense for supported project systems pending the restore, as well as all Visual Studio Build processes.

In order to reproduce, you must have a LegacyPackageReferenceProject project system that does not implement IVsProjectRestoreInfoSource. My project system for Synergy/DE is one such sample. I am happy to provide product installers for triage.

Steps:
Create a solution with both the legacy project and a C# project.
Close and re-open the solution.
NuGet restore never completes for the C# project.
Attempting to build the solution hangs indefinitely.

**Comment by madkat** [comment]
I was able to get IVsProjectRestoreInfoSource implemented for my project system and get project nomination functional. This should prevent my language from blocking C# users. There are a number of non-CPS project systems out there that will likely not have implementation for IVsProjectRestoreInfoSource. Mixed project users are unlikely to understand why their C# projects are not working in that situation.

**Comment by nkolev92** [comment]
We'll take a look.

**Comment by madkat** [comment]
We are continuing to run into problems with the bulk restore mechanism. Is there a way to disable the "nugetbulkrestorecoordination" feature? I don't seem to have access to setting values in the Experimentation Service, and the environment variable only enables the feature, not disables.

**Comment by nkolev92** [comment]
@madkat 

I tried to best understand your scenario, and I don't think it's the new feature that's causing a problem. The timeout has changed, which is probably what you're seeing, from 20s to 300s, so something that might've been an issue but you didn't notice it until now.

LegacyPackageReferenceProject isn't required implement IVsProjectRestoreInfoSource, in fact they cannot cause they don't nominate. 

IsAllProjectsNominatedAsync does a few things. 
It waits for all CPS projects to nominate. - Callers are https://github.com/NuGet/NuGet.Client/blob/54e041fed028866a8695709f202dc1e5ee35cdc8/src/NuGet.Clients/NuGet.VisualStudio/SolutionRestoreManager/IVsSolutionRestoreService3.cs#L48 and https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/SolutionRestoreManager/IVsSolutionRestoreService.cs#L47
It waits for Legacy projects that call nominate at solution load. - https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/SolutionRestoreManager/IVsSolutionRestoreService2.cs#L30

I think you are likely in the 2nd scenario. 

Only legacy PR projects that explicitly opt into NuGet waiting for them will block. The way that's determined is by checking the `PackageReferences` project system capability. 

https://github.com/NuGet/NuGet.Client/blob/54e041fed028866a8695709f202dc1e5ee35cdc8/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProjectProvider.cs#L106

Does your project system set the PackageReferences capability?

**Comment by madkat** [comment]
Yes, my project system sets the PackageReferences capability. We added support for PackageReference items in a project system based on Managed Package Framework, so we are a Legacy project that supports PackageReferences.

**Comment by nkolev92** [comment]
Setting that capability implies that a project will call nominate. 

Can you try removing that and testing? 

It's likely that your projects took 20s longer to load before becaue of that.

**Comment by nkolev92** [comment]
> It's likely that your projects took 20s longer to load before becaue of that.

Well 20s longer for the intellisense stage to load, not necessarily the project itself.

**Comment by nkolev92** [comment]
A supported legacy project system can advertise PackageReference support by implementing VSProject4. 

https://github.com/NuGet/NuGet.Client/blob/54e041fed028866a8695709f202dc1e5ee35cdc8/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/LegacyPackageReferenceProjectProvider.cs#L103-L104 contains details about when a project is PR (because by default, those project styles are considered packages.config).

**Comment by madkat** [comment]
That makes sense. I previously did not have implementation for VSProject4 until I was troubleshooting this issue. Removing the capability and keeping the IVsProject4 implementation looks like the right path forward.

I can confirm that after removing the capability I get a consistent, functional experience.

**Comment by nkolev92** [comment]
phew. 

Glad that solved it, and we're not regressing anything with the bulk restore coordination, as that change is critical for making branch switching functional in VS. 

I created an issue about documenting PR support: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2620. 

Anything you would've liked to see differently?
Beyond having documentation on how to do this successfully ofc.

**Comment by madkat** [comment]
I am generally really happy to see the unified package restore approach working. It's a pain point for my .NET Core/.NET 6 users whenever a restore fails to occur, and it looks like this may have cleaned up some rough edges. Documentation will be a big win for any remaining MPFproj developers that have not yet updated to support PackageRef.

Thank you for getting back to me today! Your timing could not have been better.

**Comment by nkolev92** [comment]
Sounds good. 

Closing this for now.
