### ISSUE TITLE
newest nuget not showing in VS2015

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#1145]
the current is 1.0.10

![missing nuget](https://cloud.githubusercontent.com/assets/122666/9154475/81f1ba0c-3ed2-11e5-9577-0c23a78ee554.png)

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue. The package indeed does not show up. We are going to look into it today.

Note that if you switch to the V2 feed `https://www.nuget.org/api/v2` it is showing up. This looks like a V3 feed issue.

**Comment by bhuvak** [comment]
@SimonCropp : The packages are not returned by the search results though they are actually present in the V3 feed – that’s the reason it’s not shown in the drop down. While we fix the issue, you can install the latest version of packages via “Install-Package” powershell command let and try specifying recent versions. I tried "Install-Package Fielder.Fody" without any version and it installs 1.0.10 properly. Will get back to you ASAP (in a few hours) once we fix the issue with packages not shown in drop down.

**Comment by bhuvak** [comment]
@SimonCropp, the issue is resolved now and you should be able to see all version of the package from nuget 3 UI. Let us know if you still hit any issues.

**Comment by SimonCropp** [comment]
I can confirm this is now fixed. thanks
