### ISSUE TITLE
[Bug]: The “version” drop-down box shows the installed version instead of latest version in Browse tab before refreshing

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11461]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.1.0.83

### Worked before?

No

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\32016.83
NuGet Version: Dev\6.1.0.83
OS Version: Windows-11-Enterprise-21H2
#### Repro steps
1. Create a C# Console App (.NET 6.0) project.
2. Open the PM UI for the project and go to Browse tab.
3. Install a package – not the latest version (e.g. Newtonsoft.Json) from Browse tab.
4. Observe the “version” drop-down box on the right panel after installing.
#### Expected
The “version” drop-down box should show the latest version of this package in Browse tab.
#### Actual
The “version” drop-down box shows the installed version instead of latest version in Browse tab as below.
![image](https://user-images.githubusercontent.com/20632625/146527400-7a9c373f-fb08-4bb7-b630-e21b42e669e4.png)
#### Notes
1. The “version” drop-down box will show the latest version of this package correctly after refreshing/reopening the PM UI/switching the tab back as below.
![image](https://user-images.githubusercontent.com/20632625/146528463-57ffa97d-63b0-438d-ba8c-cad6e2e05dc6.png)
2. It is not a regression issue since it reproes on D16.10 31025.218.

**Comment by nkolev92** [comment]
I don't think this is a bug. 

This was an explicit change in https://github.com/NuGet/NuGet.Client/commit/fef7522ee0e7c5d8be656770a95c8262313f09cb, https://github.com/NuGet/NuGet.Client/pull/3050

**Comment by donnie-msft** [comment]
After installing, I believe it's reasonable to leave the "just installed" as the selected version. 
Let me know if you or anyone feels there should be a design change here.

Refreshing or leaving and returning to this tab, you'll then see the latest, as expected.
