### ISSUE TITLE
[Feature]: dotnet list package --include-transitive --vulnerable shoud return nopn-zero status code when issues are found

### ISSUE THREAD

**Issue by majkel89** [NuGet/Home#11463]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

`dotnet list package --vulnerable` shoud return non-zero status code when issues are found.

The the CI could break build when problems are found.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/11315

Please upvote the linked issue.
