### ISSUE TITLE
[Bug Bash] The package recommended from IntelliCode should have the recommend icon on the left of the package in Browse Tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11474]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

 NuGet Client Dev\6.1.0.86

### Worked before?

No

### Impact

It bothers me. A fix would be nice

### Details about Problem
NuGet version: NuGet Client Dev\6.1.0.86
VS Version: Main\32030.25
OS: Windows-11-Enterprise-21H2
### Detailed repro steps
1. Launch VS and click “Create a new project” button in the G2C dialog.
2. Type “ASP.NET Web” in the search box, select the “ASP.NET Web Application (.NET Framework)” template in the list and click “Next” button.
3. Type a project name and click “Create” button.
4. Select “Single Page Application” and click “Create” button.
5. Open the PM UI of the project and go to Browse tab.
### Expected
The package recommended from IntelliCode should have the recommend icon (the start icon) on the left of the package in Browse Tab.
### Actual
The package recommended from IntelliCode doesn’t have the recommend icon (the start icon) on the left of the package in Browse Tab as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/147820066-ae747e55-25b3-4a85-9cdd-765b8977ccf8.png)
### Note
It’s not a regression.

**Comment by nkolev92** [comment]
When there's a search term, there are no recommendations provided. 

In the above screenshot, there's a search term. 

Am I missing anything?

**Comment by birgithi** [comment]
IntelliCode does not make NuGet package recommendations when the user types in a search string. The packages listed in this case are the default (non-recommender) packages filtered by the search string, and do not include results from the recommender. We've considered integrating search and recommendation results in the future, but at this point, this is working as expected.

**Comment by nkolev92** [comment]
The gold bar is unrelated to the NuGet Package Recommender logic.

**Comment by donnie-msft** [comment]
@chgill-MSFT - could you please comment on whether we would consider having the gold bar data as input to the recommender?

**Comment by v-luzh** [comment]
VS will not show the golden bar in step5 on VS Main\35222.175 with implicit NuGet Client Dev\6.12.0.82.

**Comment by nkolev92** [comment]
When there's a search term, the package recommender doesn't really provide recommendations. 

The yellow bar is not something that's connected to the NuGet Package Recommender. 

At this point, I'm not sure it's worth the effort to synchronize the experiences, since the yellow bar is really meant to help people get to a building project. 

Closing as won't fix.
