### ISSUE TITLE
nuget.exe restore not creating projectname.nuget.targets

### ISSUE THREAD

**Issue by mikegfink** [NuGet/Home#1148]
Building a C# solution on command line after running nuget.exe restore when a local repository dependency is present fails because no project.nuget.targets file is created.

Steps to reproduce:
- Create a C# solution with nuget dependencies from a package in a local repository
- Specify local repository source in nuget.config
- On command line, run nuget.exe restore solution.sln
- Run msbuild.exe solution.sln (with whatever options you like)
- Build ought to fail because references to local package cannot be found
- View source folder and note presence of project.csproj.nuget.targets but no project.nuget.targets file (project.nuget.targets is automatically picked up by msbuild but project.csproj.nuget.targets is not)

Compare:
- Build same solution in Visual Studio (2015)
- Build completes successfully
- Note that project.nuget.targets has been created.

We worked around this by creating a process that automatically finds and copies project.\*proj.nuget.targets files into the same directory and removes the ".*proj" string. 

Msbuild can then successfully build the project from the command line after the restore.

**Comment by emgarten** [comment]
@mikegfink thanks for reporting this, I've made a fix for the issue.

**Comment by emgarten** [comment]
NuGet/NuGet.PackageManagement@9df5185f8a75d22333945582210cc91b30029ff5

**Comment by vlechenko** [comment]
Now NuGet does not creating anything *.nuget.targets.

**Comment by emgarten** [comment]
@vlechenko what are your command line parameters? and what is your working directory and structure of your project when you run the restore command?

**Comment by vlechenko** [comment]
I run it with single "restore" paramenters at dictionary with .sln file. It working for previous version but incorrectly.

**Comment by emgarten** [comment]
@vlechenko I created a new solution with a UWP project, deleted out the targets and lock file, then ran nuget.exe restore in the directory with the solution folder. The targets file was created with the correct name.

**Comment by vlechenko** [comment]
Ok. Maybe I build nuget.exe incorrectly. I will wait it to download and test in my solution.
