### ISSUE TITLE
Prototype reading Vulnerability and Deprecation information from the Search service

### ISSUE THREAD

**Issue by aortiz-msft** [NuGet/Home#11483]

**Comment by nkolev92** [comment]
I'm not 100% confident, but this should be mostly code removal! :)

**Comment by donnie-msft** [comment]
@nkolev92 Some UI level code can likely be removed (secondary querying), but actually the metadata classes are shared from both registration & search, so not much to change there. That's my cursory understanding.

**Comment by donnie-msft** [comment]
Related: https://github.com/nuget/home/issues/11127
Related: https://github.com/nuget/home/issues/11129

**Comment by donnie-msft** [comment]
Prototyping using static JSON had impact on benchmarks, so we consider the Prototype to be complete.
