### ISSUE TITLE
[Bug]: ContentItemCollections.FindItems should not be obsolete as its implementation no longer uses yield returns

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#11487]
### NuGet Product Used

Other/NA

### Product Version

6.0.0.163

### Worked before?

N/A

### Impact

Other

### Repro Steps & Context

This PR addresses overallocation of enumerators through the FindItemsImplementation: https://github.com/NuGet/NuGet.Client/pull/4099

Since FindItemsImplementation was fixed to no longer use yield returns, and the FindItems public method delegates to this method does not need to be obsolete and the obsolete attribute should be removed.

**Comment by donnie-msft** [comment]
@jebriede - please add relevant labels, thanks!
