### ISSUE TITLE
Feature request: Local package "groups"

### ISSUE THREAD

**Issue by moswald** [NuGet/Home#1149]
I just added another unit-testing project to my solution. This is the fourth one, and it's going to get all the same NuGet packages the other three get: xunit, nsubstitute, fluentassertions, etc. It would be nice if I could point at a previous project and say "give this project the same configuration" -- or even better, "this project gets this custom group of packages I've got defined in my solution called 'unit test packages'".

**Comment by yishaigalatzer** [comment]
You can do it two ways today - 

1. Copy packages.config from project A to project B, and run Update-Package -reinstall from the console for projectB
2. You can author a simple package in a local feed that depends on these (aka meta package) and install it

**Comment by nkolev92** [comment]
Thank for creating this. 
At this point we have other priorities, and we are not going to do any work in this direction. 

NuGet Package References are integrated with MSBuild now, so it's super easy to do this with a props import
