### ISSUE TITLE
NuGet bloating disk space

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#1151]
Using Nuget to just install a single package like *gulp* increases my projects' sizes from just 19 KB to incredible 50 MB, including almost ten thousand files!!!

You can't be serious about this, can you?

**Comment by emgarten** [comment]
Are the files coming from gulp? Is this an issue with the contents of the gulp package, or are you seeing issues like this with NuGet on other packages also?

**Comment by yishaigalatzer** [comment]
The gulp package brings down node, which is indeed large. This is not a nuget issue.

You can either install npm globally, deal with the size, or tall to the package owner.

Either way we do not own the package.
