### ISSUE TITLE
[Feature]: Allow overriding a centrally defined package version

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11516]
### NuGet Product(s) Involved

NuGet.exe, MSBuild.exe, dotnet.exe

### The Elevator Pitch

Central Package Management (CPM) allows users to specify versions for their packages in one place.  However, there are edge cases where a project might want to use a different version.  For example, a prototype project could need a newer version than a repo is using so it would opt into newer versions.

There is an existing implementation, Microsoft.Build.CentralPackageVersions, which uses a `VersionOverride` attribute to indicate that a `<PackageReference />` should use a different version than is centrally defined.

This design has a few advantages:
1. Makes it obvious when a project is using its own package version(s)
2. Ideally, an entire repo would use the same package version which is why users would define it in one place.  Users who want to use a different version would need to fully understand the ramifications of specifying the `VersionOverride` attribute.
3. Migration from Microsoft.Build.CentralPackageVersions would be easier.

Other options for users that would still be possible are:
1. Specify a `<PackageVersion />` in a project
2. Define an MSBuild property that represents the package version and set it in a project

Since MSBuild essentially lets users do anything they want, the built-in mechanism for overriding a package version should be simple and well documented.  

# Design

A user would specify package versions in `Directory.Packages.props`:
```xml
<Project>
  <ItemGroup>
    <PackageVersion Include="PackageA" Version="1.0.0" />
    <PackageVersion Include="PackageB" Version="2.0.0" />
  </ItemGroup>
<Project>
```

A project would override the version with the `VersionOverride` metadata on a `<PackageReference />` item:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PackageA" VersionOverride="3.0.0" />
  </ItemGroup>
<Project>
```

In this case, the project's restore graph would resolve `PackageA` to version `3.0.0`.  Any project that references it would also get that version and a user would be responsible for handling an unresolved conflicts.

Finally, a repo owner should be able to disable the ability for developers to override package version.  This would be used for instance if someone wanted to ensure that all package versions are unified.  This would be possible by setting the MSBuild property `EnablePackageVersionOverride` to `false` in a project or import like Directory.Build.props:

```xml
<Project>
  <PropertyGroup>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>
<Project>
```

When this is disabled, specifying a `VersionOverride` on a `<PackageReference />` would result in a restore error indicating that he feature is disabled.

**Comment by zivkan** [comment]
What happens if a customer uses `EnablePackageVersionOverride` or `VersionOverride` on a project that is not opt into CPM?  Should we warn/error, to help them detect possible configuration errors?

(I missed this "spec" because it's an issue, not a pull request)

**Comment by jeffkl** [comment]
> What happens if a customer uses EnablePackageVersionOverride or VersionOverride on a project that is not opt into CPM? Should we warn/error, to help them detect possible configuration errors?

If you don't specify a `Version`, you'll get an error.  If you specify both `Version` and `VersionOverride`, the `VersionOverride` is ignored.  I'm not sure if we need to warn a user in this case, maybe its something we add later if enough users complain?

**Comment by zivkan** [comment]
Becoming more restrictive in a higher version of tooling is a breaking change (a customer's commit which builds without error on a lower version of tooling fails on the higher version, despite no code changes). Becoming more permissive in a future version is not a breaking change.

**Comment by kzu** [comment]
I would expect a `<PackageReference Version="..." />` to always override a central package version. I fail to see when/why you'd need a differently named attribute (`VersionOverride`) for that. MSBuild is quite flexible in how it exposes all this and editing item metadata via targets is quite trivial. 

Trying to understand the design decision behind this. Seems weird to introduce new attributes for something that can be subsumed in a prior attribute (unless I'm missing some key scenario). 

 The only potential benefit I see is 

> Users who want to use a different version would need to fully understand the ramifications of specifying the VersionOverride attribute.

But that can be most certainly be addressed with a warning (when both central version *and* project-level version is specified), which developers can trivially turn into an error or ignore via the built-in NoWarn and WarningsAsErrors as they see fit.

**Comment by xoofx** [comment]
> But that can be most certainly be addressed with a warning (when both central version _and_ project-level version is specified), which developers can trivially turn into an error or ignore via the built-in NoWarn and WarningsAsErrors as they see fit.

Agreed, that could be done with e.g `OverrideVersion=true` for example

**Comment by kzu** [comment]
Indeed. Anything but having an unnecessary fork in how you add package references in *every reference* instead of a top-level property (either that `OverrideVersion` or just a `NoWarn`) via `Directory.Build.props`.

**Comment by jeffkl** [comment]
> I would expect a <PackageReference Version="..." /> to always override a central package version. I fail to see when/why you'd need a differently named attribute (VersionOverride) for that.

The reason is for enforcement.  Large repositories don't want extra versions of packages creeping into their projects so they want no versions at all allowed in a project.  To detect this, NuGet looks at the `Version` metadata and can provide an error telling the user that a version must be specified in the central location instead.  However, in some edge cases, users need to override the version centrally.  Since using the `Version` metadata is essentially banned and reusing it would make it impossible to enforce the error about not specifying versions in projects, we need to use a different attribute.  This ability to override versions can also be disabled entirely so a repo administrator can make sure that no versions are specified anywhere else.

That said, you can still use custom MSBuild implementations to do whatever you want.

**Comment by kzu** [comment]
> To detect this, NuGet looks at the Version metadata and can provide an error telling the user that a version must be specified in the central location instead. 

A (say) `$(OverrideVersion) = false` would trivially cover that. Can be added per project or per-repo via a `Directory.Build.props`. 

> However, in some edge cases, users need to override the version centrally.

I'm missing what makes this scenario not possible with a property that specifies what overriding behavior you want.

**Comment by xoofx** [comment]
FYI, I had to fix an issue with Central package mgt in dotnet-releaser and the fix is in the following commit https://github.com/xoofx/dotnet-releaser/commit/0aea1e59b45517ff72117a558cc90c6fb245c4dc showing in practice the trouble that we were discussing here. 

I had to duplicate entirely the entry because in one case I have to use `VersionOverride` and in the other `Version`

```xml
  <Choose>
    <When Condition="'$(ManagePackageVersionsCentrally)' == 'true' AND '$(CentralPackageVersionsFileImported)' == 'true'">
      <ItemGroup>
        <PackageReference Include="Packaging.Targets" VersionOverride="0.1.220">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>compile;build</IncludeAssets>
          <ExcludeAssets>runtime;contentFiles;native</ExcludeAssets>
        </PackageReference>
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="Packaging.Targets" Version="0.1.220">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>compile;build</IncludeAssets>
          <ExcludeAssets>runtime;contentFiles;native</ExcludeAssets>
        </PackageReference>
      </ItemGroup>
    </Otherwise>
  </Choose>
```

Injecting package reference in projects is now quite more complicated instead of something like this:

```xml
      <ItemGroup>
        <PackageReference Include="Packaging.Targets" Version="0.1.220" OverrideVersion="$(ManagePackageVersionsCentrally)">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>compile;build</IncludeAssets>
          <ExcludeAssets>runtime;contentFiles;native</ExcludeAssets>
        </PackageReference>
      </ItemGroup>
```

**Comment by delanym** [comment]
I set `EnablePackageVersionOverride` to false in my solution's `Directory.Packages.props` file and in a project. I'm expecting the project build to fail, but it succeeds with
`<PackageReference Include="Core.System.Configuration.Install" VersionOverride="1.1.0"/>` or `<PackageReference Include="Core.System.Configuration.Install" Version="1.1.0"/>`

**Comment by jeffkl** [comment]
@delanym that seems like something is misconfigured since including a `Version` should definitely produce an error.  Are you able to reproduce the problem with a simple project that you can ZIP up and attach?  Or specify `/binarylogger` to your build command-line and attach the `msbuild.binlog`?
