### ISSUE TITLE
PackageDownload: support GeneratePathProperty

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#11510]
If my understand is correct, `PackageDownload` items currently don't support `GeneratePathProperty`. This loses a lot of potential value prop because in the scenarios where you use `PackageDownload` you're highly likely to want to know a deterministic path to the package contents where it was laid out on disk.

Right now the only way we can see is rely on `$(NuGetPackageRoot)` which is problematic because I've seen users remap it to say E:\NuGet (without the trailing slash), wreaking all sorts of havoc.

**Comment by KirillOsenkov** [comment]
@nkolev92 @sandyarmstrong

**Comment by sandyarmstrong** [comment]
Even with $(NuGetPackageRoot) you have to repeat a lot of information to get the full nupkg path. It would be nice to have `GenerateNupkgPathProperty` or something too. :-)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8476.
