### ISSUE TITLE
[Bug]: Race Condition Creating Plugin Log Files

### ISSUE THREAD

**Issue by reynoldsbd** [NuGet/Home#11517]
### NuGet Product Used

Other/NA

### Product Version

.NET 5.0.404

### Worked before?

Don't have specific versions, but we have been observing the bug for nearly 6 months.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Original issue: dotnet/sdk#21320

NuGet credential provider fails to initialize if two .NET projects are being built concurrently.

Appears to be caused by a race condition where both concurrent MSBuild instances attempt to open the same log file for plugin logs. The winner of the race successfully opens the file and starts the plugin; the loser fails to start the plugin, and the overall build fails because NuGet packages cannot be restored.

So far my team has only observed this happening within Azure DevOps Pipelines builds, and only over the past 6 months or so. I'm confident that nothing in our build has changed; we have been building .NET projects concurrently for years.

# Repro Steps

Definitely not easy to repro. You have to get "lucky" and start two separate .NET builds within a short time of each other. Haven't been able to reproduce locally, but this happens in our CI builds dozens of times per day.

# Proposed Fix

@nkolev92 suggested adding process ID or some other random string as part of the log file name.

https://github.com/dotnet/sdk/issues/21320#issuecomment-1017855276

### Verbose Logs

```shell
Full output from running `dotnet publish`:


  Determining projects to restore...
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Problem starting the plugin 'C:\Users\cloudtest\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Problem starting the plugin 'C:\Users\cloudtest\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error :   The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Temp\pluginlog\NuGet_PluginLogFor_dotnet_8d97ea679be4f9c.log' because it is being used by another process. [C:\a\_work\1\s\Path\To\MyProj.csproj]
  Retrying 'FindPackagesByIdAsync' for source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
  Retrying 'FindPackagesByIdAsync' for source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'.
  Response status code does not indicate success: 401 (Unauthorized).
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error : Failed to retrieve information about '<PACKAGE>' from remote source 'https://microsoft.pkgs.visualstudio.com/<GUID>/_packaging/<GUID>/nuget/v3/flat2/<PACKAGE>/index.json'. [C:\a\_work\1\s\Path\To\MyProj.csproj]
C:\a\_work\_tool\dotnet\sdk\5.0.401\NuGet.targets(131,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\a\_work\1\s\Path\To\MyProj.csproj]
```
```

**Comment by reynoldsbd** [comment]
Hey @nkolev92, I'm happy to submit a PR to fix this. What do you think would be the best solution?

Using process ID could work, but what if the same process tries to run two plugin instances in parallel? Is this even possible?

Another option would be to use `new Random().NextInt64()` instead of `DateTime.UtcNow.Ticks`. Would this work?

Maybe some combination of the above?

**Comment by nkolev92** [comment]
> Hey @nkolev92, I'm happy to submit a PR to fix this.

That sounds great, thanks!

> Using process ID could work, but what if the same process tries to run two plugin instances in parallel

That shouldn't be possible. 

> Another option would be to use new Random().NextInt64() instead of DateTime.UtcNow.Ticks

I think we still need to keep the time element as it helps having multiple logs in the same folder. 

I don't think there's  too big of a difference in what the extra qualifier is as long as it's short. Possible someone else has a better idea when the PR gets reviewed.
