### ISSUE TITLE
NuGet Package Manager in Visual Studio 2013 does not remove references marked "could not be found" when uninstalling packages

### ISSUE THREAD

**Issue by brendanzagaeski** [NuGet/Home#1152]
When uninstalling packages in Visual Studio 2013 the NuGet Package Manager does not remove references that are currently marked "could not be found". This issue does _not_ affect NuGet Package Manager 3.0.0 in VS 2015.

I suspect this might be an old known issue that has an acceptably low impact to be left as-is, but I searched for the associated warning message in both the GitHub issues and the old CodePlex issues, and I didn't notice a previous report. So if nothing else, this report can serve as some small documentation.

## Regression status: probably not a regression

Certainly not an immediate regression: 2.8.60610.756 and 2.8.60723.765 have the same behavior

## Steps to reproduce

1. Download and unzip the [test case](https://gist.github.com/brendanzagaeski/6f86fa66463e8420caf9/archive/4d59cd4368eab79559949bb164306edfdd41b051.zip), and then open the `.sln` file in Visual Studio 2013.

2. Open "Tools -> NuGet Package Manager -> Manage NuGet Package for Solution".

3. Click the "Restore" button at the top right of the package manager window.

4. If the "Updates" heading is already selected, click the "Installed Packages" heading on the left of the package manager window.

5. Click the "Updates -> Microsoft and .NET" heading.

6. Click the "Update" button on the right side of the "Json.NET" NuGet package.

(Note: to make the test case I started with a new "Visual C# -> Class Library (Portable)" solution, ran "Install-Package Newtonsoft.Json -Version 6.0.8", and then intentionally deleted the `packages` folder.)

## Results

After step 6, `PortableClassLibrary1.csproj` contains an incorrect `Version=` specifier for the "Newtonsoft.Json" assembly:

```
<Reference Include="Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
  <HintPath>..\packages\Newtonsoft.Json.7.0.1\lib\portable-net45+wp80+win8+wpa81+dnxcore50\Newtonsoft.Json.dll</HintPath>
  <Private>True</Private>
</Reference>
```

The primary problem seems to be that when the NuGet Package Manager uninstalls the 6.0.8 version of "Newtonsoft.Json", it does not remove the original reference to "Newtonsoft.Json.dll". The package manager apparently skips over this reference because Visual Studio reports that it cannot be found:

> Warning	1	The referenced component 'Newtonsoft.Json' could not be found.

If you attempt to build the project after step 6, you will see a similar, more verbose warning:

> Warning	1	Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

(Note: this issue is not specific to the "Newtonsoft.Json" package.) 

## Workaround

After restoring the package at step 3, select the "PortableClassLibrary1" project in the Solution Explorer and then click the "Refresh" button at the top of the Solution Explorer. Visual Studio will now see the "Newtonsoft.Json" assembly correctly, the "could not be found" warning will disappear from the Error List, and the package update at step 6 will produce the correct `Version=` specifier.

## Possible improvements

a. Maybe the NuGet Package Manager could "imitate" the manual workaround and tell Visual Studio to refresh the status of the assembly references after the "Restore" process at step 3?

or

b. Maybe the package manager could ignore the fact that the `.dll` is marked as "could not be found" when uninstalling the package. In fact based on my quick tests, it appears that NuGet Package Manager 3.0.0 in VS 2015 does ignore the "found" status, so this issue does not affect VS 2015 RTM. That said, there might be an intentional reason that the 2.x package manager behaves differently and refuses to remove the `Reference` element if `.dll` is currently marked "could not be found".

## Additional version information

Windows 8.1 (64-bit) in VMWare Fusion 6.0.6

Microsoft Visual Studio Professional 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.6.00081

NuGet Package Manager   2.8.60723.765

**Comment by yishaigalatzer** [comment]
Yes, the issue is known and we decided to fix it for Visual Studio 2015 only, by following exactly the suggestion you made. Namely we force a restore, so uninstall can take place.

**Comment by brendanzagaeski** [comment]
Sounds good to me. Thanks for the follow-up!
