### ISSUE TITLE
after upgrade, cannot reach internal feed

### ISSUE THREAD

**Issue by RipCurrent** [NuGet/Home#1153]
hi,
re-posting this on correct forum. can anyone give me guidance on this issue:

installed vs2015 & got latest nuget 3.1(?). Also upgraded command line to nuget v2.8.60717.93

In both VS and on commandline:
I can reach external nuget feeds and localhost nuget feed.
I can no longer reach internal corporate nuget feeds. 404 error.

I downloaded source code from codeplex and ran command line tool in debug mode.
With fiddler, I can see the v3 api call to internal server "{url}\intercept.json " which returns 404 (also see iis log entry)
After the 404, it then tries the request using v2 and just "{url}" and errors out
Nothing in fiddler for this or in IIS log, as if it never tried it.

other users who upgraded to VS2015 are ok (they don't have command line). 
I can reach internal server using browser and HTTP Get in powershell

can ideas on how I might get going again here?
:)
thanks!

**Comment by yishaigalatzer** [comment]
Can you share your `nuget.config` (or all of them)? And the fiddler trace?

And I'm not sure what is an internal server with a v3 feed? What product is it?
For command line support V3 server you want to use the beta - http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe

**Comment by RipCurrent** [comment]
![nugetconfig](https://cloud.githubusercontent.com/assets/8657359/9223745/b8fd8df4-40f4-11e5-9619-6e79b8f6144d.PNG)
![fiddler](https://cloud.githubusercontent.com/assets/8657359/9223752/c46f460a-40f4-11e5-98e5-6375d814c55f.PNG)
![v2](https://cloud.githubusercontent.com/assets/8657359/9223750/c468a552-40f4-11e5-94f9-fbdc3c9d2eaa.PNG)
![v3](https://cloud.githubusercontent.com/assets/8657359/9223751/c46a8110-40f4-11e5-9909-d68a123757fb.PNG)



Hi,
Thanks for response. I've attached:
1 - relevant section of nuget.config. The url resolves to corporate nuget feed
2 - fiddles capture showing its making the v3 call. however its not making the v2 call
3 - v3 code using HttpClient which works is so much that it makes the web request to the non existant v3 file
4- the v2 code using older WebResponse/HttpWebRequest technology

Code is from Nuget.v2 on github

Using cookies based security here and maybe this is not handled. Whats killing me is this used to work before I upgraded. But maybe its some internal proxy changes etc. Just posting here in case there was any recent change that might have caused something like this.

**Comment by yishaigalatzer** [comment]
Thanks for all the details, very useful.

Cookie based security might have worked inadvertently.

V2 not being called is by design v3 deduplicates to allow for v2 and v3 side by side on the same machine (2.8.6 and above recognizes protocol version).

We will take a look at cookie authentication and figure out what is going on. Basic auth is what is properly supportedm

**Comment by emgarten** [comment]
@RipCurrent the shim code you are debugging from codeplex is not in Visual Studio 2015 RTM or NuGet 3.1.0.

Try the code in github https://github.com/NuGet/NuGet3

**Comment by RipCurrent** [comment]
@emgarten @yishaigalatzer thanks for replies. After more testing etc conclude it must be some issue with proxy settings etc on my machine as downloaded older versions of nuget command line and still getting 404's from "nuget list -s TEST" where Test is corporate server.
