### ISSUE TITLE
[Bug]: Versions dropdown default selection should be LatestStable on Updates tab in PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11537]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.2.0.29

### Worked before?

Dev\6.2.0.28

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Create a C# Console App (.NET Core) project.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Install a package (e.g. “Newtonsoft.Json”), not the latest one (e.g. “11.0.1”).
4. Click the “Updates” Tab.

## Expected:
The Latest Stable version should show in the "Version" dropdown box as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/151691090-06362ca4-a956-468d-849c-56fecea85188.png)

## Actual:
The version shows in the "Version" dropdown box as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/151691096-d816ab5f-d075-4a9b-8972-aa7daf820e30.png)

## Notes:
1. The issue also reproes on C# Console App (.NET Framework) project with the Packages.Config format.
2. The issue starts to repro from NuGet Client Dev\6.2.0.29, it doesn't repro on NuGet Client Dev\6.2.0.28.
3. The issue still repro after pressing the "Refresh" button.

**Comment by nkolev92** [comment]
@v-longmin 

Please don't remove the automatically configured labels. 
We rely on that to tell us which issues we're supposed to look at.
