### ISSUE TITLE
[Bug]: [Bug Bash] The “PackageReference” package icon colors in Solution Explorer window are inconsistent between .NET SDK based project and .NET Framework project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11531]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.2.0.26

### Impact

It bothers me. A fix would be nice

### Details about Problem
NuGet version: NuGet Client Dev\6.2.0.26
VS Version: Main\32127.271
OS: Windows-11-Enterprise-21H2
### Detailed repro steps
1. Launch VS and click “Create a new project” button in the G2C dialog.
2. Create a C# ASP.NET Core Web App (.NET Core 6.0) project and a C# Console Application (.NET Framework 4.8) project separately in two VS instances.
3. Open the PM UI of every project and go to “Browse” tab.
4. Select a package and install it into each project with “PackageReference” format.
5. Go to the Solution Explorer window and observe the installed package icon.
### Expected
The “PackageReference” package icon color in Solution Explorer window should be consistent.
### Actual
The “PackageReference” package icon colors in Solution Explorer window are inconsistent as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/151561512-7d1b9d35-69aa-45ee-be44-12cdb3997402.png)
### Notes
It’s not a regression.

**Comment by dominoFire** [comment]
@drewnoakes Do you think this is expected?

**Comment by drewnoakes** [comment]
Yes this is expected. In old projects these were mixed under the same heading and colours helped differentiate. In the new tree we aim to keep all colour out of the tree, so that we can use colour to highlight error status etc. I have reached out to the design team about removing colour from the Analyzers node.

**Comment by nkolev92** [comment]
As mentioned by @drewnoakes this is as expected right now. As such we'll close this. 

@drewnoakes Do you have a link for issue tracking the legacy project system change?

**Comment by drewnoakes** [comment]
We would be unlikely to change the legacy project system here. In that project system, two different kinds of reference are shown as siblings, and the colouration helps distinguish them.
