### ISSUE TITLE
[Bug]: Package unusable after pack

### ISSUE THREAD

**Issue by atrauzzi** [NuGet/Home#11536]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.100

### Worked before?

N/A

### Impact

I'm unable to use this version

### Repro Steps & Context

I'm in the process of configuring builds for an open source project which can be found here: https://github.com/atrauzzi/protoculture-dotnet-postgres

Part of how this project works is that it **embeds** various versions of postgres as static dependencies.  Those dependencies are to be included in the package and copied to the build output folder of any consuming projects.

If you look at [my `.csproj` file](https://github.com/atrauzzi/protoculture-dotnet-postgres/blob/main/Protoculture.Postgres.Embedded/Protoculture.Postgres.Embedded.csproj#L27-L34), you can see that I'm telling it to recursively grab a directory and eventually include it in the nuget package.

You can see in [the build](https://github.com/atrauzzi/protoculture-dotnet-postgres/runs/4994959039), packaging seems to succeed, but when I go to upload to the GitHub package repository as a test, I get the error:

```
warn : nupkg malformed - failed to extract metadata from upload. Are you sure this is a nupkg file?
```

Not helpful, but I tried out some nupkg validators and I end up getting the following:

```
Could not load file or assembly '/tmp/Protoculture.Postgres.Embedded.0.1.1-pre/contentFiles/postgres/windows/x86_64/lib/_int.dll'. The module was expected to contain an assembly manifest.
```

I definitely am copying `dll` files to that path in the package, but they are dependencies of the applications I'm embedding.  They do not in any way participate directly with my own application code.

As best as I can tell -- and the documentation for this kind of stuff is really spotty -- I can't seem to find a way to tell nuget/nupkg to not try to do anything with those files.  Thus it's preventing the package from working anywhere.

### Verbose Logs

You can see all configuration and attempted builds over at the project.

---

Feel free to also check out [my twitter thread](https://twitter.com/alextrauzzi/status/1487828270779224064) as I start asking around about this issue.

**Comment by nkolev92** [comment]
@atrauzzi 
Looks like you've narrowed it down to a GPR problem, is that correct?

**Comment by atrauzzi** [comment]
@nkolev92 - At least for the moment, yes.

It can be a bit difficult at times to track down a canonical and _complete_ reference for nupkg.  Much of the knowledge is fragmented at the gaps between various tools that have been involved in its evolution (visual studio, nuget, msbuild, dotnet).

It would be useful to help them with troubleshooting though if I can arm myself with as much information as possible.  I've attached a copy of a failing package to this ticket.  If you or anyone in-the-know :tm: can spot something wrong with it, please feel free to let me know.

:pray:

[Protoculture.Postgres.Embedded.0.1.14-pre.nupkg.zip](https://github.com/NuGet/Home/files/7975242/Protoculture.Postgres.Embedded.0.1.14-pre.nupkg.zip)
 
(Obviously remove the `.zip` at the end, this is just so that github will let me upload it.)

The build for this file can be seen here, if at all interested: https://github.com/atrauzzi/protoculture-dotnet-postgres/actions/runs/1775821068

I should note, I will be trying to upload this to nuget once I can get a few remaining concerns stabalized.

**Comment by nkolev92** [comment]
@atrauzzi 

We strive for the tooling to *not* allow invalid packages to be created. 
I don't see anything about the package that suggests it should be invalid here. 

The usage for package is usually more permissive than uploads, but a good rule of thumb can be applied there as well. 
In a large majority of the cases, if a package can be consumed/installed, then it's likely ok. 

For now, i'll close this issue as external, but happy to help if you run into any other issues.

**Comment by atrauzzi** [comment]
That's wonderful to know!  Thank you so much for the insights and I'll continue to liase with your sister group over at GitHub :slightly_smiling_face:
