### ISSUE TITLE
[Bug]: Disabling package source in VS throws null reference exception

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11534]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

17.1

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

```text
dotnet new nugetconfig
dotnet nuget add source https://whatever
dotnet new sln
start *.sln
```

Then go into VS options, NuGet Package Manger, Package Sources.

Uncheck the checkbox for the whatever source, and click ok.

The problem is here: https://github.com/NuGet/NuGet.Client/blob/0ca13dff1ebdd33c2f20a66aa059628200a16af9/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L448

PackageSourceProvider's constructor takes in an `ISettings`, which VSSettings implements. However, the line tries to cast to a `NuGet.Configuration.Settings` class, which VSSettings does not extend.  The cast is done using the `as` keyword, not a "direct" typecast, preventing a more useful typecast exception from being reported.

However, the more serious design bug is allowing the class constructor to take in anything that implements the interface `ISettings`, but then expecting the class to be a specific implementation `Settings`.

**Comment by nkolev92** [comment]
Triage: Let's close this as there's no immediate functional impact and no customer reports.
