### ISSUE TITLE
[Bug]: Enhanced HTTP retry does not respect cancellation

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11544]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

Latest

### Repro Steps & Context

The implementation of enhancing our HTTP retries in https://github.com/NuGet/NuGet.Client/pull/4220 unfortunately does not respect cancellation since the tokens aren't passed to the `Task.Delay()` calls.  When enabling this by default, some unit tests caught this problem.

**Comment by zivkan** [comment]
Fixed in 6.2: https://github.com/NuGet/NuGet.Client/pull/4436
