### ISSUE TITLE
Hierarchical view in packages

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#1155]
Many suites of packages have dependencies and it is not obvious understanding which is the "root" which will include all the dependent packages. Example of these suites are "webapi", "rx extensions" or "roslyn" / "CodeAnalysis".
The scenario is when the user looks at an existent project and wants to create a new one with a hierarchy of packages (but not necessarily all the packages of the other project).

If a root package exists and can be evidenced in nuget client, it would be nice if the packages would be organized in a tree instead of a flat list.
In this case, one package could appear more than once, but it can be marked as an "placeholder" so that if the user updates it, the others are obiously too.

**Comment by nkolev92** [comment]
With package reference, this has been changed to where the user does not see the transitive dependencies anymore.
