### ISSUE TITLE
Readme node in .nuspec xml unable to compile

### ISSUE THREAD

**Issue by zehavibarak** [NuGet/Home#11568]
We are using .nuspec & nuget pack cli. I tried to set a 
```xml
<readme>file.md</readme>
```
in project .nuspec. But the `nuget pack .` throws an exception that _readme_ in not found in http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd.

**Comment by zivkan** [comment]
@zehavibarak  readme support was added into NuGet 5.10: https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/

This suggests to me that you're using a version of nuget.exe that is older than version 5.10.  You can download a newer version from https://www.nuget.org/downloads.

If this does not help, please try to provide us with a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) so we can better understand the steps to get the error.

**Comment by zehavibarak** [comment]
Updating the .exe solved it. thanks
