### ISSUE TITLE
Download counts are different in Visual Studio between V3 and V2 sources

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1156]
nuget.org points to api.nuget.org/v3/index.json
V2 points to www.nuget.org/api/v2

![image](https://cloud.githubusercontent.com/assets/1238711/9207293/841675c0-4021-11e5-8c2f-f1c891a4839f.png)

nuget.org points to api.nuget.org/v3/index.json

![image](https://cloud.githubusercontent.com/assets/1238711/9207311/a131cbe6-4021-11e5-8a22-dbb460cb8247.png)

**Comment by xavierdecoster** [comment]
Fixed.

## V3 pointing to api.nuget.org/v3/index.json

![v3](https://cloud.githubusercontent.com/assets/880728/10096823/061c6608-6375-11e5-886f-70e547f1d3ed.png)

## V2 pointing to nuget.org/api/v2

![v2](https://cloud.githubusercontent.com/assets/880728/10096825/0ac230ca-6375-11e5-8128-58f064a85eca.png)
