### ISSUE TITLE
NuGet.exe list doesn't search from local folders using local path on Linux/Ubuntu

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11579]
Currently `nuget list` [command tests ](https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetListCommandTest.cs)are not running under Linux/Ubuntu CI pipeline, it's running under Windows CI and MAC CI.

```
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nugetmain" value="https://api.nuget.org/v3/index.json" />
    <add key="nuget1" value="C:\packageFolder" />
  </packageSources>

```
When I try to run it manually try it only accept source name nuget.config
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/4579303c-42f5-4fb9-8e5e-b07680c1005e)

But Windows and MAC allow to use local path, there's divergent experience:
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/ab3b4f04-c2b6-48a4-9636-72cd4ea483e9)
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/f25efca5-9c12-47c3-a1ad-aff952776d8e)

**Comment by erdembayar** [comment]
@heng-liu 
Is it known bug?

**Comment by nkolev92** [comment]
Is the bug specific to LocalSearchResource? 
List is just one one usage of it, so the impact could be great than just the list command.

**Comment by zivkan** [comment]
Triage:  local file feed code is in NuGet.Protocol, which could possible affect restore. Validate if restore is affected, and if it is not, we can lower the priority.

**Comment by zivkan** [comment]
@erdembayar nuget.exe is a .NET Framework assembly, and therefore on Linux it needs to run under mono (just like on Mac), but your screenshot shows that you invoked nuget.exe directly.  This suggests to me that you ran this under WSL on Windows, not on a Linux VM, where WSL detects the Windows exe being called and silently runs it in Windows, despite running it from the Linux prompt.  Therefore, it's the same as running `nuget.exe list /mnt/c/...` on Windows, which probably really does not exist on your `c:\`.

Please [install mono](https://www.mono-project.com/download/stable/#download-lin) if you wish to try again, and run nuget.exe with that on Linux.

**Comment by erdembayar** [comment]
Added myself as well, I'll retry when I spin Ubuntu VM.

**Comment by erdembayar** [comment]
@zivkan 
I tested on Ubuntu VM, it looks it doesn't repro. As you mentioned it was running WSL on Windows issue.
![image](https://user-images.githubusercontent.com/8766776/179145983-b2a5fa19-2c0a-46ff-b968-737e93b3f2eb.png)

I believe you can close this one.
