### ISSUE TITLE
Canceling project.json restore leaves the packages folder in a bad state

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1157]
Steps
1. Create a new UWP project
2. Save and close the solution
3. Delete the global .nuget\packages folder
4. Reopen and build the solution
5. Click cancel on the progress dialog while packages are downloading
6. Build again to perform a 2nd restore

Expected:
The second restore should complete successfully

Actual:
The first restore did not leave the packages folder in a good state. Some packages have only a nupkg and the second restore fails.

**Comment by yishaigalatzer** [comment]
Also - https://github.com/NuGet/NuGet3/commit/1b2bbafa99f6382375810f8b934922efe34d1126
