### ISSUE TITLE
[Bug]: Infinite Scrolling is broken after a package source error

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#11575]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

d17.2

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Create a package source that doesn't exist (eg, http://localhost:5000)
2. Open PMUI to the Browse tab
3. Wait for the error to indicate the package source could not be reached.
4. Scroll down to the bottom of the list. 

Actual: Nothing happens
Expected: More packages are loaded

The LoadingStatus state is set to `ErrorOccurred`, and this never changes until a refresh/etc. `ScrollViewer_ScrollChanged` only triggers for the Ready state.

I would expect clicking "Dismiss" or a similar action would return the behavior to normal. Otherwise, I'd expect a message at the bottom to say the list is locked due to the error.
![image](https://user-images.githubusercontent.com/49205731/153046485-a0762fca-6b7c-4254-80bc-01b5990f3e32.png)

**Comment by nkolev92** [comment]
Likely a dup of https://github.com/NuGet/Home/issues/2496.
