### ISSUE TITLE
[DCR]: Make enhanced HTTP retry the default, deprecate older retry logic

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11578]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

Enhanced HTTP retry [was added](https://github.com/NuGet/NuGet.Client/pull/4220) as an opt-in feature and will be turned on by default in https://github.com/NuGet/NuGet.Client/pull/4403.  Once released, we should get rid of the legacy retry logic that is superseded by it and clean up the code.  We'll also need to remove references to the environment variable to disable it here: 

https://github.com/NuGet/docs.microsoft.com-nuget/pull/2664

We should leave the env var that configures the retry count and delay.

### Desired Behavior

Enhanced HTTP retry becomes the default and the escape hatch to turn it off is removed along with the legacy code.

**Comment by zivkan** [comment]
It's been default since 6.2: https://github.com/NuGet/NuGet.Client/pull/4403

**Comment by jeffkl** [comment]
Enabling enhanced retry by default might have regressed https://github.com/NuGet/Home/issues/12195 and https://github.com/NuGet/Home/issues/12215
