### ISSUE TITLE
Package source mapping should check for duplicate node keys

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11573]
If you follow  `bad config`setup then you'll get `dotnet` source not considered for `Microsoft.Somepackage` error during restore,
problem is there 2 nodes with same `dotnet` key so last one overwrites the first one. We need to detect this and warn customer about it before try to restore.

Bad config:
```
  <packageSourceMapping>
    <packageSource key="dotnet">
      <package pattern="Microsoft.*" />
    </packageSource>     
    <packageSource key="dotnet">
      <package pattern="System.Securiry*" />
    </packageSource>
  </packageSourceMapping>
```

Good config, 2 patterns for same source should be under same node key:
```
  <packageSourceMapping>
    <packageSource key="dotnet">
      <package pattern="Microsoft.*" />
      <package pattern="System.Securiry*" />
    </packageSource>
  </packageSourceMapping>
```

**Comment by nkolev92** [comment]
We should validate this on a configuration level. 

If this is a behavior that's source mapping specific, we should address it. 
If this is a behavior that's configuration specific, then I'm not as worried.

**Comment by erdembayar** [comment]
>  If this is a behavior that's configuration specific, then I'm not as worried.

If it's the case maybe we need to call this out in doc.

**Comment by nkolev92** [comment]
I want to make sure we don't focus too much on singular feedback and increase the size of documentation unnecessarily. 

imo, I don't see customers doing the above too often.

**Comment by martinrrm** [comment]
The XML parser uses a map and cannot handle duplicate keys, to enable this we will need to do a custom parser for XML
