### ISSUE TITLE
[Bug]: Nuget.exe breaks in Azure DevOps agent container (Linux)

### ISSUE THREAD

**Issue by roycornelissen** [NuGet/Home#11574]
### NuGet Product Used

NuGet.exe

### Product Version

6.0.0

### Worked before?

No

### Impact

I'm unable to use this version

### Repro Steps & Context

We are using a Azure DevOps build agent, installed as a Linux Docker container, as documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#use-azure-kubernetes-service-cluster). In addition, it has the latest Mono framework installed.

Running `mono nuget install` (or even just `mono nuget`) fails with the following error message:

```
Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000e3] in <9bc69d145f5a4dbcbd11cfa298c5ba4f>:0 
```
According to https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux, we should be able to run `nuget.exe`, but we can't get it to work.

We tried with versions 4.x, 5.x and 6.x but none of them work.

What could be the reason?

### Verbose Logs

```shell
We ran it with `-Verbosity detailed` and the output is still only:


Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000d3] in <628ad472b621437fba78dcacbf4e1cd2>:0
```
```

**Comment by zivkan** [comment]
What version/build of Mono are you using?

I'm not motivated to spend 15 minutes searching right now, but we've had problems in the past with the Debian build of mono in the past. If you follow mono-project's instructions: https://www.mono-project.com/download/stable/#download-lin
and use their official & supported build of mono, things seem to work better. Also, mono-project's official feeds have a `nuget` or `nuget.exe` package, so you don't need to download nuget.exe yourself. The version that ships in the mono project's feed is tested by them to work.

**Comment by zivkan** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by msdkool** [comment]
@zivkan suggestion worked for me. All I did was to follow the link provided and install mono all over again.

**Comment by cbersch** [comment]
@roycornelissen Works for me with Ubuntu if I install the `mono-devel` package

**Comment by don-rumata** [comment]
More compact list than `mono-devel` (for Ubuntu 20.04): `libmono-system-componentmodel-composition4.0-cil libmono-microsoft-build-utilities-v4.0-4.0-cil libmono-windowsbase4.0-cil libmono-system-net4.0-cil libmono-system-net-http-formatting4.0-cil libmono-system-net-http-webrequest4.0-cil libmono-system-net-http4.0-cil libmono-system-io-compression4.0-cil libmono-system-data-services-client4.0-cil libmono-system-servicemodel4.0a-cil mono-mcs`
