### ISSUE TITLE
Referring to #1151: NuGet bloating disk space

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#1159]
I believe (and I strongly suggest) NuGet should globally install every part of a package by default which is not related to a project to be deployed. Or it should provide an option to do so.

Dissecting each and every package detail for being eligible to be globally installed can not be the responsibility of a package consumer. There are too many packages around for keeping up with each of their implementation details. Today it's *Node* and *NPM*, tomorrow it's some other tool that's unnecessarily wasting disk space.

A package consumer is not supposed to be interested in the implementation details of any package. A consumer is neither implementing those packages nor maintaining them, but just consuming them. Packages are supposed to be treated as a black box. A consumer is only supposed to be interested in the source of the project he/she's working on.

So I strongly believe the package provider and the package distributor - **NuGet** in this case - are responsible for providing options to gracefully deal with installing packages.

Hence, **NuGet** should provide an option for having every part of a package installed globally that's eligible for doing so.

![folder distribution analysis 1](https://cloud.githubusercontent.com/assets/9283914/9215012/4127d9e6-40a5-11e5-8353-c5c37f6cb7e7.png)

**Comment by yishaigalatzer** [comment]
With the `project.json` model that's the case. We currently require it for UWP and PCL apps, and plan to add more project to be supported this way.
Similarly ASP.NET 5 follows exactly the same pattern (and will shortly the same global folder).

We do not plan to make a change for package.config scenario for this.
