### ISSUE TITLE
[Responsiveness] Package Management UI can consume large number of threads all searching the disk (up to 316 threads), use cancellation token at subroutines

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11599]
Tracking issue for: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1424937
I added `Around The World` tag here since internal issue has one.
Currently passed cancellation token to [LocalPackageSearchResource.SearchAsync](https://github.com/NuGet/NuGet.Client/blob/ac2cb86d726e1f0089fc6f5a63357a37940ca8aa/src/NuGet.Core/NuGet.Protocol/LocalRepositories/LocalPackageSearchResource.cs#L30) is not checked frequently also getting list of directories once then do processing, resulting fire off very slow thread which is not cancelled even calling method already requested cancellation, instead we could check cancellation token more frequently while processing directories one by one.

Sample look:
![LockingThreads](https://user-images.githubusercontent.com/8766776/154781668-e1fad1b5-9ff3-4956-9683-275e5ba5e0f8.png)

**Comment by nkolev92** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1424937 has a duplicate already linked: https://github.com/NuGet/Home/issues/11570

Are they the same issue?

**Comment by erdembayar** [comment]
> https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1424937 has a duplicate already linked: #11570
> 
> Are they the same issue?

Yes, they're same. But I'm creating 2 PRs. There're 2 sub-issues need to be addressed. I large PR is hard to review.

**Comment by nkolev92** [comment]
I see. Worth using better names instead of part 1/part 2 :)

**Comment by erdembayar** [comment]
> I see. Worth using better names instead of part 1/part 2 :)

Sure, I'll rename them when I create PR.
