### ISSUE TITLE
PackageSourceMapping public constructor

### ISSUE THREAD

**Issue by lbargaoanu** [NuGet/Home#11609]
### NuGet Product(s) Involved

NuGet SDK

### The Elevator Pitch

We want to set the package source mapping dynamically on restore, not read them from a configuration file.
### Additional Context and Details

We don't have a static pattern for the package ids and we don't have the feeds in the configuration file, but we can set those when restoring. Making the existing constructor public would work.

**Comment by erdembayar** [comment]
@lbargaoanu 
Could you be able to elaborate more? We want to understand your use case. How are you going to invoke constructor?

**Comment by lbargaoanu** [comment]
When calling restore, I need to create an instance and pass it to  `RestoreRequest`'s constructor.

**Comment by erdembayar** [comment]
> Reference in new is

How are you going to call RestoreRequest's constructor? I'm trying to understand your use case.

**Comment by lbargaoanu** [comment]
The same as nuget.exe does it? :) Perhaps I'm missing your point. There is only one constructor and we need to pass all those parameters, including the source mapping. And the source mapping can only be constructed from `ISettings`. But we cannot store the mapping in a nuget configuration file, hence the need for that constructor.

**Comment by lbargaoanu** [comment]
Is there smth I can do here?

**Comment by nkolev92** [comment]
Hey @lbargaoanu 

Just trying to clarify your scenario. 

You call restore programmatically yourself. 
Do you have a separate tool? Or are you using it for your build?

> We don't have a static pattern for the package ids and we don't have the feeds in the configuration file, but we can set those when restoring.

Can you elaborate on this? In particular, not sure I understand what you mean by a static pattern for package ids.

**Comment by lbargaoanu** [comment]
Yes, we have tools like VS and nuget.exe. Used at dev time, but also at runtime.
At runtime, we call restore and we want to make sure that some packages come from a certain source. The package names and the sources are read from a central database. We get what we want by calling the constructor with reflection.
But I guess my main point is that the source mapping doesn't have to come from a nuget config file.

**Comment by lbargaoanu** [comment]
Would you accept a PR to make the existing constructor public? Because _that_ I can do :) I'm not sure about smth more involved, but I could try.

**Comment by JonDouglas** [comment]
I see no concern with it. Seems like a good contribution to enable more scenarios.
