### ISSUE TITLE
[Feature]: Download packages via torrent

### ISSUE THREAD

**Issue by lostmsu** [NuGet/Home#11603]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

This is a potential solution to [NuGet.org package size limits](https://github.com/NuGet/Home/issues/890)

Instead of hosting the package itself, NuGet.org can give an option to host a torrent file and/or a magnet link. The client can then use a torrent library such as [MonoTorrent](https://github.com/alanmcgovern/monotorrent) to download the package.

**Comment by kartheekp-ms** [comment]
Related - https://github.com/NuGet/NuGetGallery/issues/8042

**Comment by nkolev92** [comment]
Team Triage: This is not something we'd be interested in doing at this point.
