### ISSUE TITLE
[Bug]: Unexpected error “NU3034: This package is signed but not by a trusted signer” shows when verifying with Dotnet Nuget verify Command

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11605]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet Client Dev\6.20.75

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1.  Git clone https://github.com/NuGet/Entropy.git to Windows VM.
2.	Copy the “SDKPatchTool” folder from https://github.com/NuGet/Entropy.git to the desktop of Mac machine.
3.	Copy the “Nupkgs” folder of the NuGet build to the desktop of Mac machine.
4.	Go to the “SDKPatchTool” folder on Mac, and edit the paths in the “patchOnUnix.ps1”.
5.	Open a bash on Mac, cd to the “SDKPatchTool” folder path and run “patchOnUnix.ps1” script: ./patchOnUnix.ps1.
6.	On Windows VM, create a C# Class Library (.NET 6.0) project and pack it with command dotnet pack.
7.	On Windows VM, cd to <path_to_Entropy>\TestCertGenerator and create a new test certificate: `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` in powershell.
8.	Go to the PatchSDK path.
9.  Copy the .cer file(should be generated under the same path with .pfx file) and the .pfx file from the above Windows machine to Mac machine.
10. Add the certificate to trusted store:  
`sudo security import <pfxFilePath> -k /Library/Keychains/System.keychain`
`sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <cerFilePath>`
11.	Run`./dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath> --certificate-password password -v n` on Mac.
12.	Verify the correct certificate was used with the command `./dotnet nuget verify <PackageFilePath> -v d `on Mac.
## Expected
There were no other errors except for expected errors/warnings.

## Actual
Unexpected error “NU3034: This package is signed but not by a trusted signer” shows when verifying (in step10) as below screenshot.
 
![image](https://user-images.githubusercontent.com/40230425/154656297-32f16bd6-6965-493a-a83d-364dc920fb8a.png)

## Note
1. The issue does not repro on Windows.
2. The issue also repro on Linux.

**Comment by kartheekp-ms** [comment]
@v-longmin - We recently added a new option [--configfile for dotnet nuget verify](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-verify#options) command. `The NuGet configuration file (nuget.config) to use. If specified, only the settings from this file will be used. If not specified, the hierarchy of configuration files from the current directory will be used. For more information, see` https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied

Given this information, is there any configuration file from the current directory to the root that has `trustedsigner` section defined?

Looking at the code path that raises this error, it looks like `trustedsigners` are defined somewhere in the hierarchy.

https://github.com/NuGet/NuGet.Client/blob/ac2cb86d726e1f0089fc6f5a63357a37940ca8aa/src/NuGet.Core/NuGet.Packaging/Signing/Verification/AllowListVerificationProvider.cs#L49-L57

The easiest way to check if there are any trusted signer section defined is to execute, [`dotnet nuget trust list`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-trust#list) from the directory where `dotnet nuget verify` command was invoked. If the output of `dotnet nuget trust list` command has one or more trusted signers then that explains the reason why `verify` command throws `NU3034: This package is signed but not by a trusted signer` error.

**Comment by v-luzh** [comment]
Hi @kartheekp-ms , thanks for your detailed info. Yes, we can see a trust signer after running the command dotnet nuget trust list on Mac/Linux. Is that because we added the certificate into trust store on Mac/Linux (as step 10 above) and it would write a trust signer into the nuget.config file?

**Comment by kartheekp-ms** [comment]
> Is that because we added the certificate into trust store on Mac/Linux (as step 10 above) and it would write a trust signer into the nuget.config file?

@v-luzh - step 10 `(sudo security)` is not a nuget command and hence I don't think it modifies NuGet.Config file. Maybe you are executing another manual test with `<trustedsigner>` section configured causing this failure? In other words, what happens if we delete the config file that has `<trustedsigner>` section and then execute `dotnet nuget verify` command on the signed package? I would expect it to pass verification unless there is some other configuration in the hierarchy which has another different setting.

**Comment by v-luzh** [comment]
@kartheekp-ms Yes, you are correct. The error NU3034 gone after removing the <trustedsigner> section in nuget.config. Please give it a resolution label and closing, thanks.
