### ISSUE TITLE
[Bug]: Cannot find convention based plugins

### ISSUE THREAD

**Issue by rsking** [NuGet/Home#11612]
### NuGet Product Used

NuGet SDK

### Product Version

6.2.0, or previous

### Worked before?

not tested

### Impact

I'm unable to use this version

### Repro Steps & Context

Convention based plugin discovery is not possible

1. Copy plugin to convention based path (i.e. `$(UserProfile)\.nuget\plugins\netcore\myplugin`)
2. Do not set `NUGET_PLUGIN_PATHS`

Plugin is not found

This appears to be because plugin discovery is only enabled when the source is `http`, and `_rawPluginPaths` is not null or empty

https://github.com/NuGet/NuGet.Client/blob/2ffefa687ba980fd0a70e13615875c69bde9393c/src/NuGet.Core/NuGet.Protocol/Plugins/PluginManager.cs#L122

If `_rawPluginPaths` is not set, then plugin discovery is disabled, but when it is set, then convention based discovery is disabled.

This seems to be the case for all versions.

**Comment by erdembayar** [comment]
Thank you for filing this issue.
Can you help us with repro steps? Can you remove sensitive data/classes/info and share with us bare minimum project/solution for your plugin? Without it it’s hard to repro for us.
If you’re making zip or git repo please don’t exclude packages folder and bin/obj folders.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
