### ISSUE TITLE
[Bug]: NuGet Verify failing in windows Docker containers - Unable to disable Verify

### ISSUE THREAD

**Issue by msherms2** [NuGet/Home#11611]
### NuGet Product Used

NuGet.exe

### Product Version

All nuget.exe versions (5.7 and latest), also present in dotnet restore.

### Worked before?

No verification failures

### Impact

I'm unable to use this version

### Repro Steps & Context

When we build in our azure devops pipelines using docker containers, in the last two months we have encountered intermittent verify failures that we are unable to track down. I've tried moving to the latest nuget.exe, dotnet restore, and nothing has worked, most importantly and relevantly nuget verify disabling. From everything i can find on the history of verify, it was supposed to be opt in - so i should be able to at least temporarily disable verification altogether and not encounter issues. However, all documentation to disable it fails - I still get intermittent trusted root certification errors.

Note: I am not able to change my package versions, .net FW version, or visual studio version due to customer requirements.

I am expecting there is an ability to skip nuget verification on packages that are failing verification improperly. I honestly don't know what the reasoning is - every case I've found was solved with more up to date docker base images, but that has not worked for us.

The error:

##[error]NU3018: Package 'Microsoft.CodeAnalysis.VersionCheckAnalyzer 2.9.4' from source 'C:\__w\81\s\Packages': The author primary signature found a chain building issue: UntrustedRoot: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

And yes, all the packages are microsoft packages, and yes, it isn't just that one package, and yes, sometimes my builds pass.

**Comment by donnie-msft** [comment]
I've seen issues in the past with Group Policy causing intermittent “untrusted” errors 1-2x daily/weekly. If you can easily check, it may be good to know whether it may potentially apply to your case.  
My suggested quick steps:
1.	Start -> Edit Group Policy on an affected VM.
2.	Navigate to Computer Configuration > Windows Settings > Security Settings > Public Key Policies > Trusted Root Certification Authorities
3.	Does Trusted Root Certification Authorities exist here?

More detailed workarounds are described in the article, https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/valid-root-ca-certificates-untrusted

**Comment by msherms2** [comment]
@donnie-msft,

Thank you for your response. I'm unaware that policy configurations affect docker containers as they are UI-less containers. It also would mean microsoft's base images would have certification issues.

Are you saying that nuget verify is no longer opt in and there is no way to turn it off?

**Comment by donnie-msft** [comment]
Have you tried detailed verbosity when analyzing this?: Eg, `dotnet nuget verify -v d`

Machine state and other external factors can be in play here. Recently, we enabled a switch to retry signing. You may want to experiment with this to see if your CI can succeed with a retry policy: `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY`
For more information on that, see:
**Issue**: https://github.com/NuGet/Home/issues/11099
**PR**: https://github.com/NuGet/NuGet.Client/pull/4259
**Docs**: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#retry-untrusted-root-failures

Disabling verification is not recommended, as documented in https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode. The `NUGET_CERT_REVOCATION_MODE` switch is described there.

**Comment by msherms2** [comment]
@donnie-msft This was a great help. We had as a last ditch effort attempted to call nuget restore 5 times in a row to try to get by it, but this solution is MUCH better. I absolutely did not want to disable nuget verification but if the choice was between always failing 50% of builds or that, it was an easy choice. Thankfully I don't have to now!

Are you able to update documentation on nuget.exe or basically anywhere about this? I googled for days and none of the results ever had anything detailing that as a viable option - it would be very helpful for others in the future that see this to know it exists.

thank you!

**Comment by donnie-msft** [comment]
@msherms2 Thanks for the feedback and discovering this was missing. I totally agree and I've filed your suggestion https://github.com/NuGet/docs.microsoft.com-nuget/issues/2676.

Glad you're unblocked... Happy Coding!
