### ISSUE TITLE
[Bug]: Private NuGet Feed errors with `dotnet new --update-check`

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#11618]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.101

### Worked before?

no

### Repro Steps & Context

Feedback ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460341

Similar to https://github.com/NuGet/Home/issues/11169...
>  For some reason nuget makes multiple calls to the credprovider and every next call starting from 2nd passes IsRetry: true as request argument, which invalidates cached token. 

To reproduce:
1. Clear nuget cache (dotnet nuget locals all -c) and credprovider cache ([clear this folder](https://github.com/microsoft/artifacts-credprovider/blob/master/README.md#session-token-cache-locations))
2. Set nuget.config to use exclusively private feed in ADO
3. dotnet new --uninstall Microsoft.DotNet.Web.Spa.ProjectTemplates (remove template for repro if it's already installed) 
4. Run `dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates --interactive`
5. Observe multiple sequential interactive prompts

**Comment by erdembayar** [comment]
I'm trying to understand actual scenario. 
I asked questions in internal feedback ticket also pinged in teams. I'll update here if there is new update.

**Comment by erdembayar** [comment]
Everytime, I try to repro I'm getting different kind of errors. Something is broken here.

1. Sometime Cred provider won't ever trigger.
2.
![image](https://user-images.githubusercontent.com/8766776/156685295-4295ce85-7ca8-4a9b-9a68-d96706591956.png)

2. Another time: 
![image](https://user-images.githubusercontent.com/8766776/156686358-70352230-e4ec-47d3-aaab-026ed5ea75ba.png)

Looks like some race condition is happening here.

**Comment by SimonCropp** [comment]
same thing occurs for the `list` command

**Comment by kartheekp-ms** [comment]
> same thing occurs for the `list` command

This should be fixed in https://github.com/NuGet/NuGet.Client/pull/4794

**Comment by kartheekp-ms** [comment]
@vlada-shubina - Is this somehow related to https://github.com/dotnet/templating/issues/4278 that is fixed in https://github.com/dotnet/templating/pull/4764 ?

**Comment by vlada-shubina** [comment]
> @vlada-shubina - Is this somehow related to [dotnet/templating#4278](https://github.com/dotnet/templating/issues/4278) that is fixed in [dotnet/templating#4764](https://github.com/dotnet/templating/pull/4764) ?

yes, it seems the same issue. It was already fixed.

**Comment by kartheekp-ms** [comment]
Looking at https://github.com/dotnet/templating/commit/c5b2e2f9638946e9e31e66eb6e123b1d085eacb3 commit, it looks like this fix released in https://dotnet.microsoft.com/en-us/download/dotnet/7.0.

@donnie-msft - I propose to close this issue as external.
