### ISSUE TITLE
[DCR]: Show transitive origins in `dotnet list package --include-transitive`

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#11625]
### NuGet Product(s) Affected

dotnet.exe

#### Command

```
> dotnet list package --include-transitive
```

#### Output

```
Project 'projectA' has the following package references
   [net6.0]:
   Transitive Package                        Resolved
   > Microsoft.TestPlatform.ObjectModel      17.0.0
   > Microsoft.TestPlatform.TestHost         17.0.0
   > Newtonsoft.Json                         12.0.1
   > Newtonsoft.Json.Bson                    1.0.2
   > NuGet.Frameworks                        5.0.0
   > PeterO.Cbor                             4.5.2
   > PeterO.Numbers                          1.8.2
   > PeterO.URIUtility                       1.0.0
   > projectB                                1.0.0
   > System.Reflection.Metadata              1.6.0

Project 'projectB' has the following package references
   [net6.0]:
   Top-level Package                      Requested   Resolved
   > Microsoft.TestPlatform.TestHost      17.0.0      17.0.0
   > Newtonsoft.Json.Bson                 1.0.2       1.0.2
   > PeterO.Cbor                          4.5.2       4.5.2

   Transitive Package                        Resolved
   > Microsoft.TestPlatform.ObjectModel      17.0.0
   > Newtonsoft.Json                         12.0.1
   > NuGet.Frameworks                        5.0.0
   > PeterO.Numbers                          1.8.2
   > PeterO.URIUtility                       1.0.0
   > System.Reflection.Metadata              1.6.0
```

### Desired Behavior

Add an additional column that indicates which package/project brought a given transitive package. Example:

#### Command

```
> dotnet list package --include-transitive
```

#### Output

```
Project 'projectA' has the following package references
   [net6.0]:
   Transitive Package                        Resolved    Origin(s)
   > Microsoft.TestPlatform.ObjectModel      17.0.0      projectB
   > Microsoft.TestPlatform.TestHost         17.0.0      projectB
   > Newtonsoft.Json                         12.0.1      projectB
   > Newtonsoft.Json.Bson                    1.0.2       projectB
   > NuGet.Frameworks                        5.0.0       projectB
   > PeterO.Cbor                             4.5.2       projectB
   > PeterO.Numbers                          1.8.2       projectB
   > PeterO.URIUtility                       1.0.0       projectB
   > projectB                                1.0.0       projectB
   > System.Reflection.Metadata              1.6.0       projectB

Project 'projectB' has the following package references
   [net6.0]:
   Top-level Package                      Requested   Resolved
   > Microsoft.TestPlatform.TestHost      17.0.0      17.0.0
   > Newtonsoft.Json.Bson                 1.0.2       1.0.2
   > PeterO.Cbor                          4.5.2       4.5.2

   Transitive Package                        Resolved   Origin(s)
   > Microsoft.TestPlatform.ObjectModel      17.0.0     Microsoft.TestPlatform.TestHost/17.0.0
   > Newtonsoft.Json                         12.0.1     Newtonsoft.Json.Bson/1.0.2;Microsoft.TestPlatform.TestHost/17.0.0
   > NuGet.Frameworks                        5.0.0      Microsoft.TestPlatform.TestHost/17.0.0
   > PeterO.Numbers                          1.8.2      PeterO.Cbor/4.5.2
   > PeterO.URIUtility                       1.0.0      PeterO.Cbor/4.5.2
   > System.Reflection.Metadata              1.6.0      Microsoft.TestPlatform.TestHost/17.0.0
```

### Additional Context

See proposal https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-why-proposal.md
Issue filed from PR comment https://github.com/NuGet/NuGet.Client/pull/4465#discussion_r809593140

**Comment by emz00** [comment]
Per 11695, it would be even better to include the full path to each package, rather than just the origin (first step in the path). This is particularly useful with `--vulnerable`. Say I reference package A, which reference B, which reference C, which is vulnerable. I'd like to see the A -> B -> C chain. Maybe I can't upgrade A, but instead of explicitly referencing C I choose to reference a newer version of B, which upgrades C.

**Comment by gustavnyberg** [comment]
Hi,

This seems really neat and looks really nice!

It is even further and better described in https://github.com/NuGet/Home/issues/11625 and would be a very big and time-saving improvement, especially when working with securing dependencies in projects very you aren't familiar with the dependencies and their dependency chains.

I am looking forward to having this implemented and will follow this closely. Any time plan on when this could be brought into active development and get deployed? Please let me know if there is anything I can do to help or contribute to this.

Regards,
Gustav

**Comment by gustavnyberg** [comment]
Is it the right way to solve the issue, that @loop-evgeny mentions: "maybe I can't upgrade A, but instead of explicitly referencing C I choose to reference a newer version of B, which upgrades C", by explicitly referencing a later version further down in the dependency chain?

Should you update as far up or as far down in the chain as possible?

Will this actually make the project use the latest version in all it is dependencies or does this just make it pass validation and hide the errors?

Thanks in advance!

Regards,
Gustav

**Comment by JonDouglas** [comment]
For what it is worth, this has been considered as an addition to this command but also as another command itself. See the following spec for more details:

https://github.com/NuGet/Home/blob/dev/proposed/2022/dotnet-nuget-why-proposal.md#rationale-and-alternatives

**Comment by jonnekleijer** [comment]
FYI - Proposal link moved:
https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-why-proposal.md

**Comment by donnie-msft** [comment]
> FYI - Proposal link moved: https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-why-proposal.md

Nice catch, thanks! I added that to this issue's description as well.

**Comment by zhangzw218** [comment]
Is there a solution to this problem, or is it still under discussion?
What I'm doing now is I'm adding a lower version, and I'm triggering the error, and I'm seeing the call chain.
But it's a hassle, and I wonder if there's a better way, 'dotnet nuget why'

**Comment by nkolev92** [comment]
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-why is now shipped and should be the solution to this problem.

**Comment by nkolev92** [comment]
Closing this per the above comment. 
dotnet nuget why is the recommended way.

**Comment by lvde0** [comment]
`dotnet why` is cool, but it doesn't change the fact the output of `dotnet list package --include-transitive` is next to useless without information about the origin.
