### ISSUE TITLE
[DCR]: Align Release Label comparison to other package managers

### ISSUE THREAD

**Issue by woernsn** [NuGet/Home#11621]
### NuGet Product(s) Affected

NuGet.exe

### Current Behavior

Currently, Release Labels are compared case insensitive:
https://github.com/NuGet/NuGet.Client/blob/7a5b0aafd767d105014c995378a1dbb71a5d86bd/src/NuGet.Core/NuGet.Versioning/VersionComparer.cs#L330:L331

When using for example `gitversion` to version commits and therefore NuGet packages, following scenario can appear:
* 1.0.0-alpha.1
* 1.0.0-beta.2
* 1.0.0-PullRequest.4

GitVersion creates the `PullRequest` Release Label uppercase, so that it will always be lower than `alpha` or `beta`, as following is true for most package managers: `0 < ... < 9 < A < ... < Z < a < ... < z`.
Therefore, `PullRequest` builds will correctly be considered lower than `alpha` packages.

By using `StringComparer.OrdinalIgnoreCase.Compare(version1, version2)` this advantage is taken away as `PullRequest` will be considered higher than `alpha` when compared with `OrdinalIgnoreCase.Compare`.

### Desired Behavior

NuGet should do the comparison of Release Labels the same way as other package managers are doing it:
`0 < ... < 9 < A < ... < Z < a < ... < z`.
By using [`StringComparer.Ordinal`](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinal?view=net-6.0) the behavior would be aligned.

### Additional Context

Other tools used in development:
* [GitVersion](https://gitversion.net)
* Conan

**Comment by erdembayar** [comment]
@woernsn 
Does this [GitVersion](https://gitversion.net/) is similar to https://github.com/dotnet/Nerdbank.GitVersioning?

**Comment by woernsn** [comment]
> @woernsn Does this [GitVersion](https://gitversion.net/) is similar to https://github.com/dotnet/Nerdbank.GitVersioning?

I didn't know `Nerdbank.GitVersioning` until now.
It seems to follow somehow the same idea. `GitVersion.net` seems to be more universal in usage to me.
It's a single `.exe` file that can be called in any git repository at any time and provides different kinds of versions (NuGet formatted, build time, commit hash, ...).

**Comment by erdembayar** [comment]
> > @woernsn Does this [GitVersion](https://gitversion.net/) is similar to https://github.com/dotnet/Nerdbank.GitVersioning?
> 
> I didn't know `Nerdbank.GitVersioning` until now. It seems to follow somehow the same idea. `GitVersion.net` seems to be more universal in usage to me. It's a single `.exe` file that can be called in any git repository at any time and provides different kinds of versions (NuGet formatted, build time, commit hash, ...).

Actually [Nerdbank.GitVersioning](https://www.nuget.org/packages/Nerdbank.GitVersioning/3.5.85-alpha ) is quite popular, currently 4.3 downloads.  We need to take account how other existing solutions like `Nerdbank.GitVersioning` works, this change might break them.

**Comment by nkolev92** [comment]
Team Triage: Thank you so much creating this issue. This would be a breaking change that could negatively impact the community, which is why we will not consider it at this point.
