### ISSUE TITLE
Nuget package manager is missing from Visual Studio Extension Gallery

### ISSUE THREAD

**Issue by westdavidr** [NuGet/Home#1162]
Getting this message in the Visual Studio Extension Gallery
>**This item is not yet published**
>If you are the owner of this project, please sign in with the appropriate account.

**Comment by yishaigalatzer** [comment]
Fixed the blog to point to the right way to get the extension, and we will fix the gallery as well

**Comment by westdavidr** [comment]
@yishaigalatzer Can you give me a link to the blog that you are referring to? 

Thanks!

**Comment by yishaigalatzer** [comment]
Blog.nuget.org

**Comment by yishaigalatzer** [comment]
This was fixed (the gallery blocked the extension for some reason).

**Comment by RanjiniM** [comment]
Not an issue anymore
