### ISSUE TITLE
[Feature]: Show transitive dependencies from project references in PM UI Installed Tab

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#11624]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

In PM UI, show transitive dependencies from referenced projects.

That way, users can see transitive dependencies that indirectly affect their current project.

### Additional Context and Details

Issue filed from PR comment https://github.com/NuGet/NuGet.Client/pull/4465#discussion_r809593140

**Comment by nkolev92** [comment]
Team Triage: Can you please drive the discussion on this.

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/13060 is newer but has more details. 
Dup of https://github.com/NuGet/Home/issues/13060.
