### ISSUE TITLE
[Bug]:Version combo box is not editable in C# Console Application (.NET Framework) – PackageReference project

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11620]
### NuGet Product Used

PM UI

### Product Version

NuGet Client dev-martinrrm-fix-versions-combobox\6.2.0.452

## Repro steps
1. Create a new C# Console Application (.net framework) project.
2. Right-click the project and select ‘Manage NuGet Packages…’ menu item in Solution Explorer.
3. Click settings button, check ‘Allow format selection on first package install’ in General tab, select 'PackageReference' in the ‘Default package management format’ combo box and click OK.
4. Go to ‘Browse’ tab, click some packages (e.g.Newtonsoft.Json) and start typing a version in the version list.

## Expected
Version combo box is editable in C# Console Application (.NET Framework) – PackageReference project.

## Actual
Version combo box is not editable in C# Console Application (.NET Framework) – PackageReference project as below screenshot.
![Record](https://user-images.githubusercontent.com/40230425/155710346-21813537-bb48-4376-88c6-79cd2e52b5b7.gif)
## Note
1. The issue does not repro on C# Console App (.NET Core) project.
2. It is a regression bug, start to repro from dev-martinrrm-fix-versions-combobox\6.2.0.452.

**Comment by erdembayar** [comment]
@v-longmin 
Hi. I tried with latest `Main\32227.60 + Dev\6.2.0.85`. So far, I was not able to repro this.
Please verify again and let me know.

**Comment by v-longmin** [comment]
Hi @erdembayar, the issue **still reproes** on Main\32228.143 + Dev\6.2.0.86, and we created C# Console Application(.NET Framework)- PackageReference project, **not** C# Console App(.NET Core) project.

**Comment by erdembayar** [comment]
@v-longmin @martinrrm 
I just synced with Martin, this binary not released yet to customers so it shouldn't be P1 issue.

**Comment by martinrrm** [comment]
@v-longmin C# Console Application (.NET Framework) creates a .config style project, I'm closing this issue and going to update the doc to be more clear
