### ISSUE TITLE
[Bug]: Automatic credential plugin discovery is broken when 64 bit msbuild.exe is used by nuget.exe

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#11623]
### NuGet Product Used

NuGet.exe

### Product Version

6.1

### Worked before?

Yes, with VS 2019 msbuild 

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Configure a project with an azure artifacts feed. 
2. Restore

Expected:
NuGet.exe automatically discovers the plugin shipped with msbuild.

Actual:
NuGet.exe does not automatically discover the plugin shipped with VS. 
The problem is that 64 bit msbuild is used by default and it changes the relative path so pluigin discovery fails.

**Comment by WebDancer69** [comment]
The buggy function is PluginDiscoveryUtility.GetInternalPluginRelativeToMSBuildDirectory() which needs to consider the extra "amd64\" in the path for 64-bit msbuild.

**Comment by nkolev92** [comment]
Workaround: Point to the plugin in the VS installation, 
`set NUGET_PLUGIN_PATHS=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\Plugins\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe`

or install the plugin separately. https://github.com/microsoft/artifacts-credprovider.

**Comment by WebDancer69** [comment]
Another workaround is to set NUGET_PLUGIN_PATHS:

$env:NUGET_PLUGIN_PATHS="$($env:DevEnvDir)CommonExtensions\Microsoft\NuGet\Plugins\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe"

**Comment by nkolev92** [comment]
P1 issue raised in https://developercommunity.visualstudio.com/t/Nuget-does-not-load-custom-credential-pr/10015436.
