### ISSUE TITLE
[Bug]: The deleted packages.lock.json file still shows as before in the Solution Explorer window when “RestorePackagesWithLockFile” is not enabled

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11635]
### NuGet Product Used

Other/NA

### Product Version

Release-5.11.x\5.11.1.17

### Impact

It bothers me. A fix would be nice

### Details about Problem
VS Version: D16.11\32228.343
NuGet Version: Release-5.11.x\5.11.1.17
OS Version: Windows-11-Enterprise-21H2

### Repro steps
1. Create a project [e.g. Class Library (.NET Framework)] and generate a lock file “packages.lock.json” alongside the csproj file. 
2. Install a PackageReference package into the project (to generate some content into the lock file). 
3. Run restore and close the solution/VS. 
4. Delete the lock file (which you generated in step1) and run restore again. 
5. Check the lock file should not be regenerate.
6. Reopen this solution and go to Solution Explorer window to see if the lock file is deleted (or looks like it is deleted as expected screenshot showing) in the window too. 

### Expected
The deleted packages.lock.json file should show as a deleted file or removed (that's what we do for .NET Core projects) in the Solution Explorer window. Below is what we show on 17.2 Preview 2 (Main\32228.143).
![image](https://user-images.githubusercontent.com/20632625/156330129-ad2a9715-2cc2-4e85-9898-5ec8c4f0110e.png)

### Actual
The deleted packages.lock.json file still shows as before in the Solution Explorer window as below.
![image](https://user-images.githubusercontent.com/20632625/156330313-bcd9ef97-06ac-4d0f-955e-2980b74aecf0.png)

### Notes:
1.It is not a regression. We just think it should be fix on VS 16.11.
2.It doesn't repro on 17.2 Preview 2 (Main\32228.143).

**Comment by erdembayar** [comment]
I didn't test with 16.11+5.11.1.17, but I did test with latest VS17.2 Int Preview and I can repro similar issue, but experience is bit different. 
Above-described issue repro for netcore project, but not for `packages.config` projects.
After I delete `packages.lock.json` files from each project then restore again then same file regenerates for `netcore` but not for `packages.config`

![image](https://user-images.githubusercontent.com/8766776/156433701-31e31372-2643-4bcd-aa1b-2e88c977cca3.png)

Could you please retest this with VS17?

**Comment by nkolev92** [comment]
@erdembayar 
I think the scenario is legacy package reference. 
So create a .NET Framework project, and when you install a package, select PackageReference.

**Comment by erdembayar** [comment]
> @erdembayar I think the scenario is legacy package reference. So create a .NET Framework project, and when you install a package, select PackageReference.

`PackageReference` is package name?

**Comment by nkolev92** [comment]
PackageReference is the project restore style. 

.NET Core projects are PackageReference, but CPS based PackageReference, so different project system.
Legacy PackageReference are old style projects, not SDK based, not CPS based, but the long project files that normally support packages.config by default.

**Comment by v-luzh** [comment]
Hi @erdembayar, It doesn't repro on 17.2 Preview 2 (Main\32228.143). The behavior on VS 17.2 is reasonable as the screenshot I uploaded in Expected section above.

**Comment by erdembayar** [comment]
I tried to repro with actual version (D16.11\32228.343 5.11.1.17) in description. I can see `packages.lock.json` in FileExplorer, but not in VS.

![image](https://user-images.githubusercontent.com/8766776/156482321-ee9452cc-204f-4e5f-9567-9e0ac8126ccb.png)

Am I missing something?

**Comment by aortiz-msft** [comment]
@v-luzh does this issue repo on the latest version of 16.11?

**Comment by nkolev92** [comment]
> Delete the lock file and run restore again.

Worth calling out how the file is being deleted. 

In VS? Through File Explorer? 
The legacy project system doesn't support globbing, or automatic refreshing so it might be a red herring.

**Comment by v-luzh** [comment]
Hi @aortiz-msft Yes, it repro on the latest version of 16.11 (that's D16.11\32228.343 which we filed this bug on). 
Hi @nkolev92, we deleted the file on disc (in File Explorer) which you created manually in step 1. But 17.2 support automatic refreshing for the legacy project system as what I mentioned in Expected section above. 
Hi @erdembayar, we used C# Class Library (.NET Framework) project, not the C# Class Library (.NET Core).

**Comment by erdembayar** [comment]
> Hi @aortiz-msft Yes, it repro on the latest version of 16.11 (that's D16.11\32228.343 which we filed this bug on). Hi @nkolev92, we deleted the file on disc (in File Explorer) which you created manually in step 1. But 17.2 support automatic refreshing for the legacy project system as what I mentioned in Expected section above. Hi @erdembayar, we used C# Class Library (.NET Framework) project, not the C# Class Library (.NET Core).

 I used C# Class Library (.NET Framework) project in last one.

**Comment by erdembayar** [comment]
> Hi @aortiz-msft Yes, it repro on the latest version of 16.11 (that's D16.11\32228.343 which we filed this bug on). Hi @nkolev92, we deleted the file on disc (in File Explorer) which you created manually in step 1. But 17.2 support automatic refreshing for the legacy project system as what I mentioned in Expected section above. Hi @erdembayar, we used C# Class Library (.NET Framework) project, not the C# Class Library (.NET Core).

Yes, I'm using `Library (.NET Framework) project`. But still couldn't repro, could you create gif animation please? Maybe there is something I'm missing. 
![image](https://user-images.githubusercontent.com/8766776/156803246-a6beaf1f-cc8a-4ec1-a9ae-aac89eea0b51.png)

**Comment by nkolev92** [comment]
If this is only about the file, there's nothing NuGet can/should do about it, only project system.

I imagine the same thing could apply if the files was any random text file.

**Comment by v-luzh** [comment]
Hi @erdembayar , please refer to below gif animation.
![DeletedStillExist](https://user-images.githubusercontent.com/20632625/157020692-106897aa-8254-4518-91a5-b869ed16fbba.gif)

**Comment by erdembayar** [comment]
2 things in question. 
1. Why did you create empty `packages.lock.file` manually? 
2. VS creates it for you when you open solution since it does implicit restore, right?

**Comment by zivkan** [comment]
@erdembayar https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#enabling-the-lock-file

> Once a project has packages.lock.json file in its root directory, the lock file is always used with restore even if the property RestorePackagesWithLockFile is not set. So another way to opt-in to this feature is to create a dummy blank packages.lock.json file in the project's root directory.

If there is no lock file on disk, and the project has not set the MSBuild property `RestorePackagesWithLockFile` (this test scenario, from the title of this github issue) then no, VS/NuGet will not re-create the lock file.

**Comment by v-luzh** [comment]
Hi @erdembayar, 
1. That's one test case of Repeatable Restore Test. The purpose is to verify restoring will not regenerate the deleted lock file when “RestorePackagesWithLockFile” is not enabled. 
2. VS will not create it for you if you didn't set “RestorePackagesWithLockFile”.

This is not a regression since it reproes on 16.10.0 Preview 1.0 [31025.218.d16.10]. Why it is OK on VS 17.2 Preview3 latest? I guess that's because VS improved the experience on how to show deleted file in Solution Explorer window on VS 17.2 Preview3. But we think it should be fix on 16.11 since the behavior in VS 17.2 Preview3 is more reasonable than before.

**Comment by nkolev92** [comment]
This sounds like something we should move to project team and let them decide how to handle it. 

You can probably replace packages.lock.json with *any* non compile file and it's likely to repro. It doesn't seem like it has anything to do with lock files in particular.

**Comment by v-luzh** [comment]
Hi @nkolev92, I agree with you. Could you please help to confirm which area path should we move this bug to? I will move it later.

**Comment by nkolev92** [comment]
The path should be `DevDiv\NET Tools\Project`

**Comment by v-luzh** [comment]
@nkolev92 Thanks. Created a VS bug 1499811 to track this issue. I'm closing this one.
