### ISSUE TITLE
[Bug]: CPVM - NuGet.exe doesn't include central transitive dependencies in the nuspec of the created package

### ISSUE THREAD

**Issue by marcin-krystianc** [NuGet/Home#11647]
### NuGet Product Used

NuGet.exe

### Product Version

dev branch

### Worked before?

no

### Impact

Other

### Repro Steps & Context

- `dotnet pack` adds transitive dependencies (when [transitive dependency pinning is enabled](https://github.com/NuGet/NuGet.Client/pull/4025)) to the dependency groups in the nuspec of the created package (see https://github.com/NuGet/NuGet.Client/blob/b76bf48337114102098d31c80271589feb0d28eb/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L922-L932).
- `nuget.exe pack` doesn't add transitive dependencies thus as a result packages created with `dotnet pack` and `nuget.exe pack` are inconsistent.

Not providing detailed repro steps as the https://github.com/NuGet/NuGet.Client/pull/4025 has not been merged yet. It seems that when transitive dependency pinning was implemented originally, support for `centralTransitiveDependencyGroups` was added to `PackTask/dotnet/msbuild` but NuGet.exe was missed.

**Comment by erdembayar** [comment]
See description **_Not providing detailed repro steps as the https://github.com/NuGet/NuGet.Client/pull/4025 has not been merged yet_**

**Comment by marcin-krystianc** [comment]
> See description **_Not providing detailed repro steps as the [NuGet/NuGet.Client#4025](https://github.com/NuGet/NuGet.Client/pull/4025) has not been merged yet_**

HI @erdembayar, https://github.com/NuGet/NuGet.Client/pull/4025 is just implementing option to enable a feature called "transitive dependency pinning". But the feature itself was in fact implemented in the past and then was disabled with this PR: https://github.com/NuGet/NuGet.Client/pull/3719. 
So it is true that the issue with nuget.exe that I'm reporting here is not yet reproducible, but it will be as soon as https://github.com/NuGet/NuGet.Client/pull/4025 is merged.

**Comment by marcin-krystianc** [comment]
I think this issue can be closed. I've just found out, that according to documentation `nuget.exe` is not supposed to support SDK-style projects, so there is also no reason to expect that it is going to support central transitive dependencies (See https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package):

> - For non-SDK-style projects, typically .NET Framework projects, follow the steps described in this article to create a package. For step-by-step instructions using Visual Studio and the nuget.exe CLI, see [Create and publish a .NET Framework package (https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework).
 > - For .NET Core and .NET Standard projects that use the [SDK-style format](https://docs.microsoft.com/en-us/nuget/resources/check-project-format), and any other SDK-style projects, see [Create a NuGet package using the dotnet CLI](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli).

**Comment by erdembayar** [comment]
As per request above, closing this.
