### ISSUE TITLE
[Bug]: The searched package does not appear at the top of package list in “Browse” Tab 

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11646]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.2.0.89

### Impact

It bothers me. A fix would be nice

## Repro steps
1. Create a project (e.g. “C# Console App (.NET Core)”).
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Search a package (e.g. “Newtonsoft.Json”) in the filter of “Browse” Tab. 
4. Observe the package list.

## Expected
The searched package should appear at the top of package list in “Browse” Tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/156742300-6d96a213-c3d4-4bd1-80f2-dc7e6bf18bc2.png)

## Actual
The searched package does not appear at the top of package list in “Browse” Tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/156742145-a105384e-1448-471f-9c79-48ab6de58b28.png)

## Notes
1. The issue starts to repro on NuGet Client Dev\6.2.0.89.
2. The recommended packages did not appear at the top of default package list of “Browse” Tab.

**Comment by donnie-msft** [comment]
@v-crchang it would be helpful if we could see which Package Sources are selected in both instances. Could you verify that nuget.org is enabled in the "Actual" repro?

**Comment by v-crchang** [comment]
@donnie-msft We have selected "NuGet.org" package source in both instances, it is enabled in the "Actual" repro. And we can find "Newtonsoft.Json" package through the "NuGet.org" package source, it's only not show at the top of the package list as above mentioned in "Actual" screenshot.

**Comment by jebriede** [comment]
This is a regression introduced by this change: [NuGet.Client/src/NuGet.Clients/NuGet.PackageManagement.UI/PackageItemLoader.cs at 82dc2b64ff69ef03d9ab7b7b4b015748777e7e44 · NuGet/NuGet.Client (github.com)](https://github.com/NuGet/NuGet.Client/blame/82dc2b64ff69ef03d9ab7b7b4b015748777e7e44/src/NuGet.Clients/NuGet.PackageManagement.UI/PackageItemLoader.cs#L304)
