### ISSUE TITLE
System.TypeInitializationException in NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#11655]
NuGet.Client tracking issue for https://devdiv.visualstudio.com/DevDiv/_queries/edit/1365236/?triage=true
I added Around The World tag here since internal issue has one.
It's new exception started to appeared in VS17.00

**Comment by nkolev92** [comment]
@erdembayar I had the same question for one my issues, and after a brief chat with Arturo he suggested we don't duplicate the Around The World labels to make the progress easier to figure out.

**Comment by erdembayar** [comment]
@aortiz-msft
I added my investigation finding into [Azdo workitem](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1365236/?triage=true). Looks like it's OOM issue, but not sure what is the root cause of OOM. Most likely nothing is actionable from NuGet.

**Comment by erdembayar** [comment]
@aortiz-msft  @nkolev92 
We resolved internal bug as "External". Basically. it's some OOM, but nothing is actionable from NuGet.Client at this moment.
