### ISSUE TITLE
Are there any programmable interfaces that can get all top-level dependencies when migrating packages.config to packagereference?

### ISSUE THREAD

**Issue by Smartisa** [NuGet/Home#11657]
### Discussed in https://github.com/NuGet/Home/discussions/11656

<div type='discussions-op-text'>

<sup>Originally posted by **Smartisa** March  8, 2022</sup>
For example:
![image](https://user-images.githubusercontent.com/47079990/157184221-a5723f26-e0f1-406f-863e-3ba17f6261ca.png)
How can I automatically obtain top-level dependencies?</div>

**Comment by nkolev92** [comment]
Closing this as a question. We can answer in the discussion.
