### ISSUE TITLE
Drop NuGet.ISettings from NuGet.Core

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1166]
Drop NuGet.ISettings from NuGet.Core

**Comment by yishaigalatzer** [comment]
This is to start dismantling NuGet.Core and merging the functionality into nuget3

**Comment by yishaigalatzer** [comment]
We are not going to do that. We will just get rid of the dependency in V3

**Comment by deepakaravindr** [comment]
@yishaigalatzer, 

Actually, I meant to write 'Drop use of NuGet.ISettings, which is from NuGet.Core, in NuGet v3'. In an attempt to write short titles, I changed the meaning altogether :)
