### ISSUE TITLE
[Feature]: Add support for a dedicated environment variable providing the NuGetScratch path.

### ISSUE THREAD

**Issue by MarkKharitonov** [NuGet/Home#11671]
### NuGet Product(s) Involved

MSBuild.exe

### The Elevator Pitch

It would allow us to run multiple builds on the same CI server where:

1. Each build has its own TEMP directory pointing at the build staging directory
2. All the builds would be able to share the same NuGetScratch directory.

This way all the garbage files created by the unit tests in the temp directory are automatically deleted before the next build and all the concurrently running nuget processes can still synchronize between themselves.

### Additional Context and Details

https://github.com/NuGet/Home/issues/11670

**Comment by nkolev92** [comment]
The fix should be trivial: https://github.com/NuGet/NuGet.Client/blob/60f920f2227d417311c71b6651822c5c40917b17/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L81

Example, the env var could be NUGET_TEMP and it can be TEMP or it can be NuGetScratch depending on prior art with other NuGet env var.

**Comment by MarkKharitonov** [comment]
@nkolev92 - does it make sense for me to try and contribute a fix?

**Comment by nkolev92** [comment]
Sure, we'd be happy to review that.

**Comment by MarkKharitonov** [comment]
Here you go - https://github.com/NuGet/NuGet.Client/pull/4511

**Comment by erdembayar** [comment]
@nkolev92 
What is the actual use of NuGetScratch? Never encountered before.

**Comment by nkolev92** [comment]
I don't have a list of all scenarios, but as I mentioned in the previous issue it's used for cross process locking. 
You can look up a reference for NuGetFolderPath.Temp and infer usages from there.
