### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by greengumby** [NuGet/Home#11673]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 6.0.0.280

### Impact

I'm unable to use this version

### Repro Steps & Context

Running the following;

nuget pack .\project.csproj -IncludeReferencedProjects -Verbosity detailed

causes the following error

    nuget : Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its 
    dependencies. The system cannot find the file specified.
    At line:1 char:1
    + nuget pack .\project.csproj -IncludeReferencedProjects ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (Could not load ...file specified.:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, 
    PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
    File name: 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
       at Microsoft.CodeAnalysis.Collections.SegmentedArray.Copy[T](SegmentedArray`1 sourceArray, SegmentedArray`1 destinationArray, Int32 
    length)

I have reviewed all referenced projects and transitive dependencies and the only version of System.Memory being pulled into the output is 4.6.2

Is there a chance something has caused this going from nuget 5.8 to 6.0?

**Comment by jeffkl** [comment]
@greengumby can you please attach a sample project that reproduces this error?

**Comment by greengumby** [comment]
Found the issue. Upgrading the csproj to sdk format seemed to fix it.

**Comment by jamers99** [comment]
@greengumby fixed it for me too! Thanks!
