### ISSUE TITLE
How can I programmatically obtain the dependency structure in "packages. config" mode?

### ISSUE THREAD

**Issue by Smartisa** [NuGet/Home#11688]
### Discussed in https://github.com/NuGet/Home/discussions/11687

<div type='discussions-op-text'>

<sup>Originally posted by **Smartisa** March 23, 2022</sup>
Because the "packages. config" file contains all dependencies (direct and indirect), I  want to know the whole dependency structure in this mode. Is there a way that I can get it through programming?</div>

**Comment by nkolev92** [comment]
Closing as question.
