### ISSUE TITLE
CS0006 Could not found \bin\Debug\net472\***.dll

### ISSUE THREAD

**Issue by Smartisa** [NuGet/Home#11683]
### Discussed in https://github.com/NuGet/Home/discussions/11682

<div type='discussions-op-text'>

<sup>Originally posted by **Smartisa** March 19, 2022</sup>
I git clone "NuGet". When I run the test file: "PackageGraphAnalysisUtilitiesTests.cs", there are many code problems in CS0006. How can I rebuild the project to eliminate such errors?
Thanks!!!!!
![image](https://user-images.githubusercontent.com/47079990/159103963-65acfeb7-b895-4da5-ab54-0cb6e5c1521a.png)
</div>

**Comment by nkolev92** [comment]
Closing the issue in favor of the discussion as this is a quesiton.
