### ISSUE TITLE
nuget.exe does not unwrap msbuild exceptions fully

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1168]
MSBuild errors are not displayed correctly.

For scenarios where msbuild throws the error: The project file "App\App.Shared\App.Shared.vcxitems" is in the ".vcproj" file format, which MSBuild no longer supports. Please convert the project by opening it in the Visual Studio IDE or running the conversion tool, or use MSBuild 3.5 or earlier to build it.

The only error message displayed to the user is: Exception has been thrown by the target of an invocation.

**Comment by zhili1208** [comment]
verified latest code, it's already fixed
