### ISSUE TITLE
[Bug Bash] The installed package from local path disappears in the auto-restore/NuGet restore/dotnet restore when reopening the solution

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11694]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.2.0.127

### Impact

It's more difficult to complete my work

### Details about Problem
VS Version: Main\32324.52
NuGet Version: Dev\6.2.0.127
OS Version: Windows-11-Enterprise-21H2
### Repro steps:
1.Only enable one package source which point to local path (have some packages) in the Options->NuGet Package Manager->Package Sources.
2.Create a C# Console App (.NET Core 6.0) project in VS.
3.Right-Click the project in the Solution Explorer window, select ‘Manage NuGet Packages…’ and select the package source (which I set in step1) in the Package source drop-down box.
4.Click “Browse” tab and install a package from the local path.
5.Save the solution and close VS.
6.Delect the package cache from “C:\Users\UserName\.nuget\packages” and reopen the solution.
7.Run “dotnet restore” in PMC or select “Restore NuGet Packages” from the solution context menu.
### Expected:
The installed package should not disappear.
### Actual:
The installed package from local path disappears as below.
![image](https://user-images.githubusercontent.com/20632625/160149052-164554e4-03b7-4bde-b915-b6992731ab88.png)
### Notes:
1.It is found in the simulative offline environment.
2.It doesn’t repro if the package is installed from online sources like “nuget.org”.
3.It doesn’t repro on VS 16.11.12 Preview 1.0 [32311.313.d16.11].

**Comment by martinrrm** [comment]
Hi @v-luzh I wasnt able to reproduce this, is it possible that you can attach a video?

**Comment by v-luzh** [comment]
Hi @martinrrm, I attached the video for your investigation. It is recorded on VS Main\32329.175 + NuGet Client Dev\6.2.0.127. And the issue seems unstable. Repro rate is 60%. Please have more try if you can't repro it at the first time.
![LocalPackageLost](https://user-images.githubusercontent.com/20632625/160830564-efd3790a-0b8d-4517-a69e-2644b595c692.gif)
.

**Comment by SueSu01** [comment]
Verified this issue on VS Main\34809.69 + NuGet Client Dev\6.11.0.9, it's fixed, so closed it, thanks!
