### ISSUE TITLE
PRI error on building NuGet package

### ISSUE THREAD

**Issue by saravanan-2112** [NuGet/Home#11693]
### Impact

Other

### Describe the bug

Facing PRI error when building the NuGet package. It is because changes in the dependent library#1 will not be updated into library#2.

Project structure

App1

- library#1
- library#2 (using library#1)

I'm referring to the latest library package whenever I'm opening App1. Here I'm facing an error in the below scenario.

<html>
<body>

Scenario | library#1 | library#2(Depends on library#1) | Comments
-- | -- | -- | --
Changes in library#1 cs file | library#1– version2 | library#2– version1library#1 – version1 | Working fine
Changes in library#1 XAML file | library#1 – version2 | library#2– version1library#1 – version1 | It shows PRI error
Changes in library#1 XAML file with the same version | library#1 – version1 | library#2– version1library#1 – version1 | Working fine but changes are not reflected
No changes in library#1 but changes in version | library#1 – version2 | library#2– version1library#1 – version1 | Working fine

</body>
</html>

We have the scenario "If there is one change in library#1, then we need to repack multiple libraries like library#2. Otherwise it shows PRI error". Is that any other way to resolve this issue?

**Sample and package:** [pri error.zip](https://github.com/NuGet/NuGetGallery/files/8347630/pri.error.zip)

### Repro Steps

1. Open the provided sample
2. Install the package provided
3. Build the sample then it shows PRI error 

### Expected Behavior

- It should not show a PRI error.
- For changes in one library, we should not repack multiple libraries.

**Comment by saravanan-2112** [comment]
Hi @joelverhagen,

Please find the error details in the attached screenshot.

<img width="919" alt="image" src="https://user-images.githubusercontent.com/92977521/160326233-abe8dc08-5ddc-44f7-a9ec-bf3c6ff9dc1b.png">

**Comment by saravanan-2112** [comment]
Hi Team,

Do we have any solution for this issue?

**Comment by dominoFire** [comment]
I just tried attached project and NuGet restores the project successfully.

Analyzing packages with NuGet package Explorer shows this error:

![image](https://user-images.githubusercontent.com/1192347/162589390-c30e7e0c-00b7-49c6-aad3-be3c57a5970d.png)

It seems you are experimenting this issue: https://docs.microsoft.com/en-us/answers/questions/39120/pri-errors-when-compiling-uwp-app.html

Some samples that may be useful: https://github.com/microsoft/WindowsAppSDK-Samples

Closing this issue as it seems it's not NuGet related.

For any NuGet questions, please feel free to create another issue.
