### ISSUE TITLE
[Bug]: `<GeneratePackageOnBuild>true` causes `dotnet pack` to fail when bin folder is missing

### ISSUE THREAD

**Issue by snebjorn** [NuGet/Home#11691]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK (reflecting any global.json):  Version:   6.0.200  Commit:    4c30de7899  Runtime Environment:  OS Name:     Windows  OS Version:  10.0.19041  OS Platform: Windows  RID:         win10-x64  Base Path:   C:\Program Files\dotnet\sdk\6.0.200\  Host (useful for support):   Version: 6.0.2   Commit:  839cdfb0ec  .NET SDKs installed:   2.2.401 [C:\Program Files\dotnet\sdk]   3.1.404 [C:\Program Files\dotnet\sdk]   5.0.101 [C:\Program Files\dotnet\sdk]   6.0.200 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:   Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]   Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

- Given this dotnet project (no other files are needed)
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
```
- Delete the `bin` folder if it exists.
- Run `dotnet pack`
- Observe this error:
> C:\Program Files\dotnet\sdk\6.0.200\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file 'project_folder\bin\Debug\net6.0\Test.dll' to be packed was not found on disk. [project_folder\Test.csproj]

### Verbose Logs

```shell
https://gist.github.com/snebjorn/232c6890e809ad632b5ac295330f9239
```

Original issue from https://github.com/dotnet/sdk/issues/24318

**Comment by heng-liu** [comment]
Hi @snebjorn , thanks for taking time filing this issue!
According to the [doc](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli#automatically-generate-package-on-build), my understanding is, 
setting `GeneratePackageOnBuild` to true is to automatically run dotnet pack when you run dotnet build, but not the opposite: automatically run dotnet build when you run dotnet pack.

I tried to create the same project and run `dotnet build`. The pack ran after build and the package is created. So I guess this is as expected?
Hi @snebjorn , may I know if you could run `dotnet build` to create the package?

**Comment by snebjorn** [comment]
Hi @heng-liu, I'm sorry I didn't check the documentation. I just ran the command and observed how it worked.
Running `dotnet pack` does build the project. That might be an undocumented feature.

Your bug report form didn't have a section for a description so I didn't provide one here. However I did write one where I [first reported the issue](https://github.com/dotnet/sdk/issues/24318). Here it is:

> ### Describe the bug
> `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` causes `dotnet pack` to fail if the `bin` folder is missing.
If it's set to `false` then `dotnet pack` works as expected but no package is benig generated on build - obviously.
It also works if the project already have been built. So running `dotnet build` then `dotnet pack` works.

So the issue is that  `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` breaks stuff that was previously working.

Running `dotnet pack` on this clean, unbuilt project works.
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

However running `dotnet pack` on this clean, unbuilt project throws an error.
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
```

**Comment by heng-liu** [comment]
Hi @snebjorn , thanks for your reply! 
You're right, the dotnet pack implicitly run dotnet build when `GeneratePackageOnBuild` is false or not set.
When `GeneratePackageOnBuild` is set to true, the dotnet pack won't implicitly run dotnet build,  to avoid running build twice.
So this is kind of by design. 
I think it might be good if we clarify this in our documentation. So I created a doc issue at https://github.com/NuGet/docs.microsoft.com-nuget/issues/2706

**Comment by snebjorn** [comment]
I would prefer that `dotnet pack` just worked. But don't know how much work that would take.

And documenting the issue so everyone is aware of it is a good first step :)
