### ISSUE TITLE
[Feature]: `dotnet list package --vulnerable --include-transitive` should return dependency path to vulnerable package

### ISSUE THREAD

**Issue by emz00** [NuGet/Home#11695]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

When `dotnet list package --vulnerable --include-transitive` reports packages that are indirect (transitive) dependencies it's very tedious to manually track down which direct dependency causes the vulnerable package to be included. NuGet already knows this - it just needs to show it to the user.

### Additional Context and Details

Current output:

```
Project `MyProject` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > SharpCompress                       0.23.0     Moderate   https://github.com/advisories/GHSA-jp7f-grcv-6mjf
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

I then have to look for "SharpCompress" in obj/project.assets.json to find that it's a dependency of "MongoDB.Driver.Core". I then search for that string in the same file to find it's a dependency of "MongoDB.Driver", which my project directly includes. This has to be done for every listed package.

The output I'd like to see:

```
Project `MyProject` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > SharpCompress                       0.23.0     Moderate   https://github.com/advisories/GHSA-jp7f-grcv-6mjf
     via MongoDB.Driver -> MongoDB.Driver.Core
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
     via MongoDB.Driver -> MongoDB.Bson -> NETStandard.Library
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
     via MongoDB.Driver -> MongoDB.Bson -> NETStandard.Library
```

**Comment by heng-liu** [comment]
Hi @loop-evgeny , this is a duplicate of  https://github.com/NuGet/Home/issues/11625.
