### ISSUE TITLE
[Bug]: A prompt error “cannot access disposed object” prevents solution saving after installing a package from local path

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11703]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.2.0.132

### Worked before?

Dev\6.2.0.131

### Impact

It's more difficult to complete my work

### Details about Problem
VS Version: Main\32329.175
NuGet Version: Dev\6.2.0.132
OS Version: Windows-11-Enterprise-21H2

### Repro steps:
1.Only enable one package source which point to local path (have some packages) in the Options->NuGet Package Manager->Package Sources.
2.Create a C# Console App (.NET Core 6.0) project in VS.
3.Right-Click the project in the Solution Explorer window, select ‘Manage NuGet Packages…’ and select the package source (which I set in step1) in the Package source drop-down box.
4.Click “Browse” tab and install a package from the local path.
5.Save the solution and close VS.

### Expected:
The solution can be saved and closed successfully.

### Actual:
A prompt error “cannot access disposed object” prevents solution saving after installing a package from local path as below.
![image](https://user-images.githubusercontent.com/20632625/160847414-e8cc9efa-e410-4a29-9a87-9b672aa87f38.png)
### Notes:
1.It reproes on .NET SDK style projects, does not repro on .NET Framework projects.
2.It just repro on local path packages, dose not repro on online package source (e.g. nuget.org).
3.It start to repro from Dev\6.2.0.132, doesn't repro on Dev\6.2.0.131.

**Comment by heng-liu** [comment]
I tried the following steps but failed to repro: ( on VS 17.2 preview2.0)
1.Install VS 17.2 preview2.0
2.Download vsix from build 6.2.0.132, install it the VS installed in step1
3.Open VS (install vsix in step2), create a new Console app, targeting net6.0
4.Create a local folder with two packages
5.Change the settings to make the local folder is the only source in config file
6.Run "dotnet nuget locals all --clear" to clean all caches and global package folder
7.Right-Click the project in the Solution Explorer window, select ‘Manage NuGet Packages…’ and select the local feed as the package source in the Package source drop-down box.
8.Click “Browse” tab and install a package from the local folder.
9.Click "Save all" to save solution and close VS. (Also  tried with close directly and click "Save" in the prompt)
The installation and saving both succeeded. No error prompt is shown.

**Comment by heng-liu** [comment]
I didn't repro on with the exact same version either:
VS Version: Main\32329.175
NuGet Version: Dev\6.2.0.132
Hi @v-luzh , may I know if there is anything different in my repro compared with your repro steps?
And did you repro constantly? Or there is a chance we could not repro it every time? Thanks!

**Comment by kartheekp-ms** [comment]
May be [activity log](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2022#to-examine-the-activity-log) has more details about the exception. Any exception logged in the output or error list window?

**Comment by dominoFire** [comment]
It seems no NuGet-related assembly is associated with the exception message is shown in Message box.

**Comment by v-luzh** [comment]
@heng-liu @kartheekp-ms, after showing-up the issue and Fernando's investigation, it seems not a NuGet issue. I have created an internal bug 1511563 to track. I'm closing this one now. Thanks.
