### ISSUE TITLE
_CleanPackageFiles target fails sporadically when (re)building

### ISSUE THREAD

**Issue by benvillalobos** [NuGet/Home#11710]
---
**Issue moved from dotnet/msbuild#7465**
- Please respond to @wouterroos.

---

_From @wouterroos on Monday, March 14, 2022 12:28:54 PM_

### Issue Description

When rebuilding our 80+ project solutions we sporadically get the following error on the `_CleanPackageFiles` target:

`MSB3061 Unable to delete file "C:\Projects\MyProject\src\MyProject\obj\MyPlatform\Debug\MyProject.MyPlatform.3.0.0-debug.nuspec". Access to the path 'C:\Projects\MyProject\src\MyProject\obj\MyPlatform\Debug\MyProject.MyPlatform.3.0.0-debug.nuspec' is denied.`

This issue happens for seemingly random projects in our solution.

### Steps to Reproduce

Execute the following MSBuild command until the issue presents itself (Build runs with `Configuration` set to `Debug` and `Platform` set to `any cpu` by default):

`msbuild MySolution.MyPlatform.sln /bl -t:Rebuild -m --restore`

The impacted projects have `IsPackable` and `GeneratePackageOnBuild` set to true and `PackageOutputPath` set to `$(RepositoryRootDirectory)nuget\nupkg\$(Configuration)\`. Furthermore, the projects have `TargetFrameworks` set to `net48;netcoreapp3.1;net6.0`.

The issue can also be reproduced by opening the solution in Visual Studio and rebuilding the solution. This yields more consistent results.

Additional information:

We have multiple solutions targeting the same projects but for a different platform so we use a `Directory.Build.props` file that modifies the following MSBuild variables to allow for everything to compile to a separate output folder (`BuildForPlatform` is set per project or in a nested Directory.Build.props file based on requirements and `MySolutionPlatform` is determined by the solution name):

```
<!-- BEGIN Sets project output paths for platform-specific projects -->
  <PropertyGroup Condition="'$(BuildForPlatform)'=='true'">
    <MSBuildProjectExtensionsPath>obj\$(MySolutionPlatform)</MSBuildProjectExtensionsPath>
    <BaseIntermediateOutputPath>obj\$(MySolutionPlatform)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(MySolutionPlatform)</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**</DefaultItemExcludes>
    <PackageId>$(MSBuildProjectName).$(MySolutionPlatform)</PackageId>
  </PropertyGroup>
  <!-- END -->
```

We build our solutions in parallel using the `-m` MSBuild switch or by setting `maximum number of parallel project builds` in Visual Studio.

### Expected Behavior

As happens sometimes, the solution will be rebuilt and all NuGet packages are generated as expected.

### Actual Behavior

Rebuilding one of the projects fails with the error mentioned above, causing a cascading failure for all projects depending on the project causing the issue. We've verified this behavior using both Visual Studio and the MSBuild command line. The issue happens more often when building using Visual Studio but we've also seen occurrences when using MSBuild, especially when building on our build server. 

### Analysis

I generated a `.binlog` file and did some analysis and the issue might be caused by the `_CleanPackageFiles` target running for each target framework during the inner build, which are built in parallel. This seems weird as the `Pack` is only executed once (after all inner builds are completed, which makes sense). I've submitted the binlog as a Visual Studio issue (see: https://developercommunity.visualstudio.com/t/Binlog-for-https:githubcomdotnetmsb/1691529?entry=myfeedback)

### Versions & Configurations

MSBuild version: `17.1.0.7609`
OS: `Windows 10 Enterprise 21H2`

**Comment by benvillalobos** [comment]
---
**Issue moved from dotnet/msbuild#7465**
- Please respond to @BenVillalobos.

---

_From @BenVillalobos on Thursday, March 31, 2022 4:32:03 PM_

MSBuild Team Triage: We believe this is an issue with NuGet. Your inner builds of Copper.Discovery.Interface are all trying to delete the nupkg and nuspec files.

The first one deletes the files
The second one gives the error
The third one doesn't see the files because they got deleted.

To the NuGet team: It sounds like these targets should clean these files in the outer build. That, or setting `TreatErrorsAsWarnings` to true when calling the delete task for this clean up operation.

**Comment by wouterroos** [comment]
@BenVillalobos Thanks, I'll start monitoring this issue. I hope to hear from your colleagues soon!

**Comment by dominoFire** [comment]
@wouterroos Could you be able to provide a minimal project repo example?

**Comment by wouterroos** [comment]
@dominoFire That’s a though one, as the issue doesn’t seem to happen all the time and, if it happens, it happens at a seemingly random project in the solution. What I can say it that it only happens for projects with multiple target frameworks (3 in our case) that have set `IsPackable` and `PackOnBuild` to `true`. Calling the `Rebuild` target increases the chance of it happening but still not a really reliable repro case. In theory a solution with a single project that matches this configuration would be a repro case, but the chance that the issue occurs would be minimal as it seems to be some kind of race condition. Then again, the binlog clearly shows the `_CleanPackageFiles` target being ran for each target framework which conceptually doesn’t make sense to me as packaging is done once per project and not per target framework. I could show you the issue in our solution if you’re willing to have a call. Let me know if I can do anything else to help solve this issue.

**Comment by nkolev92** [comment]
`_CleanPackageFiles` is set up to run with AfterTargets=Clean

I don't think `_CleanPackageFiles` was meant to run in the inner build on purpose. 
It's possible that the it wasn't done purpose, and before the `Clean` target. 

For example, the `_PackAsBuildAfterTarget` has an inner build check. 

I think `_CleanPackageFiles` can have one as well.

So something like the following probably does it: 

```xml
  <Target Name="_CleanPackageFiles"
          DependsOnTargets="_GetOutputItemsFromPack"
          AfterTargets="Clean"
          Condition="'$(GeneratePackageOnBuild)' == 'true' AND '$(IsInnerBuild)' != 'true'">
    <ItemGroup>
      <_PackageFilesToDelete Include="@(_OutputPackItems)"/>
    </ItemGroup>
    <Delete Files="@(_PackageFilesToDelete)"/>
  </Target>
```

**Comment by wouterroos** [comment]
@nkolev92 @dominoFire Any update on this? Is there some way we can test @nkolev92's suggestion? I tried adding the target to our Directory.Build.targets file but it gets overwritten with the one from the SDK.

**Comment by nkolev92** [comment]
@wouterroos 

This issue is not high on our priority list right as indicated by the priority label, https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md. 

> I tried adding the target to our Directory.Build.targets file but it gets overwritten with the one from the SDK.

That's interesting, not what I would've expected :(. 
Consider deconstructing the SDK imports and adding the other version of the target in the project file itself then.

**Comment by egraff** [comment]
This has been a recurring issue in my company's CI, causing a significant number builds to fail intermittently. So I'm really hoping it will get fixed 🙂

> > I tried adding the target to our Directory.Build.targets file but it gets overwritten with the one from the SDK.
> 
> That's interesting, not what I would've expected :(. Consider deconstructing the SDK imports and adding the other version of the target in the project file itself then.

I've spent a bit of time looking into this issue. This happens because `Directory.Build.targets` files are imported by `Microsoft.Common.targets`, and `$(MSBuildSdksPath)\Microsoft.NET.Sdk\Sdk\Sdk.targets` imports `Microsoft.Common.targets` (either directly or via e.g. `Microsoft.CSharp.targets`) _before_ importing `NuGet.Build.Tasks.Pack.targets` (where the `_CleanPackageFiles` target is defined), in case that part wasn't clear.

**Comment by nkolev92** [comment]
hey all, 

At this point, this isn't high on our priority list (Priority:3 label) due to the lack of repros and low upvote count. 

If someone wants to investigate and submit a fix, we'd be happy to consider it.

**Comment by egraff** [comment]
@nkolev92 FYI, I'm currently trying out a modification equivalent to [your suggested fix](https://github.com/NuGet/Home/issues/11710#issuecomment-1098519667) on our CI 🙂 I'll come back with an update once we've collected more data, but so far it looks promising. IMHO, your reasoning around that fix sounds sane, and the fix seems correct.

**Comment by kkirkfield** [comment]
@nkolev92 I can confirm that your fix is working for my projects. I had to modify my project files similar to below to override the _CleanPackageFiles target.

```
<Project>

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <!-- Other project configuration goes here. -->

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

  <Target Name="_CleanPackageFiles"
          DependsOnTargets="_GetOutputItemsFromPack"
          AfterTargets="Clean"
          Condition="'$(GeneratePackageOnBuild)' == 'true' AND '$(IsInnerBuild)' != 'true'">
    <ItemGroup>
      <_PackageFilesToDelete Include="@(_OutputPackItems)"/>
    </ItemGroup>
    <Delete Files="@(_PackageFilesToDelete)"/>
  </Target>

</Project>

```

**Comment by nkolev92** [comment]
That's great to hear @kkirkfield 

We'd be happy to accept a PR for this if anyone is interested. 

If submitted within the next month, this would make it in time for .NET SDK version 7.0.100.

**Comment by egraff** [comment]
@nkolev92 I can also confirm; we haven't had a single reoccurrence of the problem in over a month on our CI, after I put in the beforementioned modification.

The fix is exactly the one-liner change that you suggested, @nkolev92 (adding `AND '$(IsInnerBuild)' != 'true'` to the condition). Would you still like someone else to create that PR?

Will the fix also be included in an update to .NET SDK 6?

**Comment by kkirkfield** [comment]
I should be able to work on a PR later today unless someone else gets to it first. As you said, it is a simple 1 line change.

**Comment by egraff** [comment]
@kkirkfield brilliant! In case you haven't located it already in git (and it might save you some time), it's this file and line: https://github.com/NuGet/NuGet.Client/blob/1ad750307b4c227b78d3666fc68f8c71894b2f43/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L171 🙂

**Comment by nkolev92** [comment]
> Will the fix also be included in an update to .NET SDK 6?

At this point it's too late for the code change to flow into .NET SDK 6.0.400.

**Comment by egraff** [comment]
> > Will the fix also be included in an update to .NET SDK 6?
> 
> At this point it's too late for the code change to flow into .NET SDK 6.0.400.

@nkolev92 Would the fix be included in a later .NET SDK version, though? E.g. 6.0.401, or 6.0.500, or similar?

**Comment by nkolev92** [comment]
6.0.401 would be a patch version with only security fixes. 

The next feature SDK release will be 7.0.100
