### ISSUE TITLE
The package integrity check failed for almost all Microsoft packages I have tried to install

### ISSUE THREAD

**Issue by joero4** [NuGet/Home#11712]
This all started about 4 hours ago when I tried to update the Microsoft.Data.SqlClient from 3.0.1 to 4.1.0.  I got the "The package integrity check failed" error, and I began looking for solutions.  Microsoft recommends running the following command "dotnet nuget locals http-cache --clear" from here (https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3008).  I did that, and tried again, same error.  I then found the option in my Visual Studio to clear my NuGet cache.  I did that.  That was a mistake.  I then had to re-install all my packages.  Fine, did that, but many started to fail with integrity error.  I don't remember them all now, but I ended up having to copy them from another machine so I could get back up and running.  

Now I'm back to square one.  I want to upgrade Microsoft.Data.SqlClient.  Here is the error...

GET https://api.nuget.org/v3-flatcontainer/microsoft.data.sqlclient/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.data.sqlclient/index.json 197ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.data.sqlclient/4.1.0/microsoft.data.sqlclient.4.1.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.data.sqlclient/4.1.0/microsoft.data.sqlclient.4.1.0.nupkg 32ms
Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': Timestamp: 1/31/2022 5:36:44 PM

Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 7:00:00 PM to 3/22/2029 7:59:59 PM

Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': Signature type: Author
Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': Verifying the author primary signature with certificate: 
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: A6E18D21B507879FC7F9C392A5CE355936E3AD2C
  SHA256 hash: AA12DA22A49BCE7D5C1AE64CC1F3D892F150DA76140F210ABD2CBFFCA2C18A27
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 9/29/2020 8:00:00 PM to 10/5/2023 8:00:00 AM

NU3008: Package 'Microsoft.Data.SqlClient 4.1.0' from source 'https://api.nuget.org/v3/index.json': The package integrity check failed.

I'm not sure where to go from here.  Any ideas would be great.  Thanks!

**Comment by joero4** [comment]
Found the cause of my issue.  It was my corporate proxy that was causing this issue.  I disabled my corporate VPN and things worked fine.  I think I need to set the http_proxy settings somewhere.  I'll have to look into that.

**Comment by mt3sliv** [comment]
> Found the cause of my issue. It was my corporate proxy that was causing this issue. I disabled my corporate VPN and things worked fine. I think I need to set the http_proxy settings somewhere. I'll have to look into that.

Hey Joe, did you ever figure out the http_proxy setting? I think I may be running into a similar issue, and can't find much else online about NU3008 and vpn conflicts. I was able to restore my packages once I was not on the vpn as well.

**Comment by cah-jonathan-cachat01** [comment]
@joero4 & @mt3sliv - any solutions here regarding http_proxy settings?
