### ISSUE TITLE
[Bug]: Two packages with different names with the same assembly name - error when install

### ISSUE THREAD

**Issue by hrlourenco** [NuGet/Home#11711]
### NuGet Product Used

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

VS2019, Nuget 5.x

### Worked before?

Don't know, new behavior

### Impact

I'm unable to use this version

### Repro Steps & Context

Hello everyone,

*Scenario:*

_a) Create a project A with netstandard 2.0, create 2 packages:_
- A.1.0.0.nupkg (based on project A, assembly name A)
- A.singleassembly.1.0.0.nupkg (based on project A, assembly name A, just change package name, add .singleassembly)

_b) Create a project B with NET4.7.2:_
- Reference to A.singleassembly.1.0.0
- Create a package for project B, B.1.0.0.nupkg

_c) Create a project C with NET 4.7.2:_
- Reference to B.1.0.0

**Error:**
- When you reference package B, it gives an error that cannot be installed because it's not compatible with NET472
- When you install this package, it takes all other "external" packages except dependency to "A"

**Expected:**
- Should allow the installation of C, bringing dependency to A

_Workaround:_
- Create a new version of A, A.singleassembly.1.1.0.nupkg
- Remove from feed A.1.1.0.nupkg, allowing only A.1.1.0
- Repeat the steps b) and c) below and it will works

It seems that, when you install a package with dependencies, it tries to match \ understand the assembly name and not only the package name to resolve the dependency. It seems that, besides the fact that feed as 2 different packages, it looks to assembly name to resolve dependencies for "3rd party"

This is an internal request, package A as 2 different packages for the same project because the solution where we have project A, as a postbuild behavior to transform all in one single assembly (ILRepack), and we need to publish this singleassembly, but we need to publish also all individual projects.

Thank you!

**Comment by dominoFire** [comment]
@hrlourenco can you try with VS 2022 or nuget.exe 6.x ?

**Comment by hrlourenco** [comment]
> @hrlourenco can you try with VS 2022 or nuget.exe 6.x ?

This is related to "update", "restore" works fine.

We cannot use VS 2022 in this solution, related to a dependency with microsoft.visualstudio... that have a breake change.

We made a change in ".psmdcp" file, changing "identifier" name. With that change, we need to install manually package "A" in project "C" and then we can install package "B" in project "C".

**Comment by dominoFire** [comment]
> Should allow the installation of C, bringing dependency to A

Where do you install package  C ?

I just reproduced steps with instructions above and I can generate all three packages.

Am I missing something?

[issue11711.zip](https://github.com/NuGet/Home/files/8457755/issue11711.zip)

**Comment by hrlourenco** [comment]
Not exactly, the scenario is:

Using VS 2017:
1 - Create Package A with netstandard:   **A.nupkg**
2 - Copy A.nupkg and inside of this package rename <ID> at nuspec to a A.RENAME
3 - Create **A.RENAME.nupkg**
4 - Create project B.csproj with net 472
5 - Install A.RENAME.nupkg at B.csproj
6 - Create package of B: B.nupkg
7 - Create project C.csproj with net 472
8 - Install B.nupkg

Project C should install and should have installed packages A.RENAME and B.

**Comment by nkolev92** [comment]
@hrlourenco 

NuGet doesn't really use the assembly name for installation and restore. It's not really an input, that's usualyl more of a build time concern. 

I created a repro per your instructions and as there's no issues. 

[11711.zip](https://github.com/NuGet/Home/files/8477233/11711.zip)


Can you please provide a zip with your repro? 
It'd be great if you can post the logs of the error you are running into as well.

**Comment by hrlourenco** [comment]
Hi @nkolev92, could you try to use packages.config instead of packagereference on net472 projects?

How did you pack the project B? Nuget CLI? What version? Could you please paste here the exact command?

We use nuspec and Nuget CLI

**Comment by nkolev92** [comment]
@hrlourenco 

I am using dotnet pack. You can view the script inside my repro. 

Note that nuget.exe pack won't automatically figure out the dependencies for packages.config projects. That's not a thing for those projects. You're expected to specify a nuspec with all that information.

We're hoping you can provide us a repro, as there's definitely something specific about your scenario.

**Comment by hrlourenco** [comment]
We use nuget cli with nuspec in Project B, Project A we use dotnet pack.

The error: You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework...
![image](https://user-images.githubusercontent.com/6207067/164257957-bc34a77b-c642-47f0-9f94-947d2340b12c.png)


Note that project A target is netstandard2.0, this is nuspec for project B:
![image](https://user-images.githubusercontent.com/6207067/164258112-68792c63-eef3-4135-837c-b7dea4069ca8.png)



C Target framework is the same as B, 4.7.2

The print of the error:
![image](https://user-images.githubusercontent.com/6207067/164260307-04d74503-f9ae-40a9-bdb1-5e5b9a12d0ae.png)

The package in this erros is the package "A"

**Comment by nkolev92** [comment]
In the original post you mentioned, the error is package B, which is different from the latest comment here. 

Can you please try to zip up dummy packages (the file content doesn't matter unless you build) that look exactly the same as the generated ones?

**Comment by hrlourenco** [comment]
Thanks nkolev, follows attached.
The error happens installing packaging B in project C, taking into consideration A is installed in project B, A is netstandard and B net472.
[prj.zip](https://github.com/NuGet/Home/files/8526246/prj.zip)

**Comment by nkolev92** [comment]
Hey @hrlourenco 

The lib/net472 folder of B is empty.

**Comment by hrlourenco** [comment]
[prj_final.zip](https://github.com/NuGet/Home/files/8529741/prj_final.zip)

Hey nkolev92, Follow the scenario. Thank you

**Comment by erdembayar** [comment]
> [prj_final.zip](https://github.com/NuGet/Home/files/8529741/prj_final.zip)
> 
> Hey nkolev92, Follow the scenario. Thank you

Thank you for sharing repro files, I tried to repro your issue by installing "Primavera.Core.ApplicationServices.12.6.0-alpha0491.nupkg" into my newly created `C.csproj` but it looks there're other missing packages too. Probably error is coming from those other dependency packages. Could be test your repro on your local by removing local cache (for packages.config project remove `packages` folder, for packages reference projects `dotnet nuget locals all -c`)?

![image](https://user-images.githubusercontent.com/8766776/165159455-a33858bc-1775-4749-97fa-c85754266138.png)

**Comment by hrlourenco** [comment]
Hi @nkolev92 ,

Seem something here. I have another example, one solution works and another dows not work....

![image](https://user-images.githubusercontent.com/6207067/166970833-9c1b9f0e-a52e-4b27-adcd-85692aa1e770.png)

**Comment by hrlourenco** [comment]
> > [prj_final.zip](https://github.com/NuGet/Home/files/8529741/prj_final.zip)
> > Hey nkolev92, Follow the scenario. Thank you
> 
> Thank you for sharing repro files, I tried to repro your issue by installing "Primavera.Core.ApplicationServices.12.6.0-alpha0491.nupkg" into my newly created `C.csproj` but it looks there're other missing packages too. Probably error is coming from those other dependency packages. Could be test your repro on your local by removing local cache (for packages.config project remove `packages` folder, for packages reference projects `dotnet nuget locals all -c`)?
> 
> ![image](https://user-images.githubusercontent.com/8766776/165159455-a33858bc-1775-4749-97fa-c85754266138.png)



@nkolev92  @dominoFire 
Hi,

Have here a reproduced scenario where this happens, i.e., package netstandard does not install in multi-project solution with net 471.

folder _localpackages: I add the package without DLL
folder _original: I add the package with DLL

[example.zip](https://github.com/NuGet/Home/files/8636136/example.zip)

![debug](https://user-images.githubusercontent.com/6207067/167028494-d455ef7e-5f0c-4216-b8ac-2e33e7006498.gif)

**Comment by nkolev92** [comment]
@hrlourenco 

Someone else will look in detail, but from looking at your gif, the package in the _localPackages does not have a dll, so it has nothing compatible with that project to install. That package is correct in not installing. 

Did I miss anything?

**Comment by hrlourenco** [comment]
> @hrlourenco
> 
> Someone else will look in detail, but from looking at your gif, the package in the _localPackages does not have a dll, so it has nothing compatible with that project to install. That package is correct in not installing.
> 
> Did I miss anything?

@nkolev92 thank you in advance

It's the opposite scenario. `_localpackages` has no dll and install, `_original` has dll and not install. It was just to show the installation is working with the metadata of this package (related to the rename that we did).

The failed instalation, `_original` folder, is the reported scenario, i.e., netstandard does not install in fw471 (should be compatible), and this folder has netstandard dll

**Comment by nkolev92** [comment]
This one threw me for a loop :D 

The problem is that the path separator in the package in the `_original` folder is incorrect. 

The path separator has to be `/` and it is in the `_localpackages` folder, but it's not in the `_original` folder.

the package in `_localpackages` folder seems to install because of the resource assemblies.

**Comment by hrlourenco** [comment]
wow! XD

What path, could you please explain exactly (example)? :)

 and about the message "... You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does ...."?


nuget.config?

**Comment by nkolev92** [comment]
In the zip package that separator for `lib\netstandard2.0` is wrong. 

It fails installing because it sees no files, so it can't be project level compatible, it has no dependencies and it has no tools.

**Comment by hrlourenco** [comment]
sorry...i'm not getting you :)

If I extract `example.zip` I have this path (after extract nupkg): `example\_original\Primavera.Lithium.TaxAuthority.Portugal.Client.Rest.SingleAssembly.5.0.3\lib\netstandard2.0`

Where are you seeing the error? What are the correct path and where?

**Comment by nkolev92** [comment]
Zip tooling will usually convert the paths, so it's be hard to see. 
As does nuget when you pack content into a package. 

Try loading the package using ZipArchive.

**Comment by hrlourenco** [comment]
OMG....

this is when we repack, powershell it's changing the slah!!! 🤣 

Thanks for the support, if possible try to make some fix there :)

Uploading images for someone that could have the same issue.

| original pack | renamed pack with powershell zip tool |
|-|-|
| ![image](https://user-images.githubusercontent.com/6207067/167043012-86f3d1f8-c9fd-44ee-a475-2576b90aba8b.png) | ![image](https://user-images.githubusercontent.com/6207067/167043044-1a833c0a-040e-49f9-865a-7da02fcdf197.png) |
