### ISSUE TITLE
[DCR]: Print sources in NU1507

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#11715]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

As part of https://github.com/NuGet/Home/issues/11505, we emit a warning that only displays the number of sources in use.  

### Desired Behavior

We should just print the sources themselves in the warning because the sources can come from lots of places and at the moment its hard to determine what sources are in use and from where.

**Comment by nkolev92** [comment]
Hey folks, for issues that obvious bugs and that are known as something that needs to be done, or being actively worked on, to fully self triage:

https://github.com/NuGet/Client.Engineering/blob/main/docs/creating-github-issues.md
