### ISSUE TITLE
[Bug]: Significant delay in UI state change following package operations

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#11726]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.3 Preview 1

### Worked before?

Unsure

### Repro Steps & Context

1. Open browse tab in solution or project level PMUI
2. Keep output window open so you can see when package operations complete
3. Install any package through the PMUI
4. Notice that the installation completes quickly, but the Install/Uninstall buttons in the details pane of the PMUI takes much longer to reflect the operation completion. Anywhere from 1-10s delay, usually about 2.5s on my machine.

Note: It isn't 100% consistent. You may have to uninstall/reinstall a package or try a few different packages to see the most dramatic delays.

![PMUI Delay Bug](https://user-images.githubusercontent.com/15097183/162281328-9bf10a0a-b119-45ee-a106-7c1be522aa52.gif)

**Comment by nkolev92** [comment]
Hey @v-luzh 
We are seeing this occasionally, would you be able to try reproing it a few times and with different versions of Visual studio (17.1, 16.11 and latest)

**Comment by dominoFire** [comment]
Note: Delay is more visible in PM UI Details Tab

**Comment by chrisraygill** [comment]
Repro'd in 17.1 and 16.11 to a smaller extent (2-3s delay). I haven't ran into the 10s+ delays I can see in VS 17.2. It could be possible that we always had a 2-3s delay, but 17.2 introduced some condition causing periodic 10s+ delays.

**Comment by v-luzh** [comment]
@nkolev92 It repro on 17.3 latest: Main\32415.346 with implicit NuGet Client Dev\6.3.0.24 and 17.1 GA D17.1\32210.238, it delays 5s in average and ran into 20+ seconds occasionally (Rate: 20%). It doesn't repro on 16.11.12 Preview1 D16.11\32311.313 (2-3s delay).

**Comment by nkolev92** [comment]
Team Triage: 

@jebriede has familiarity with the codepaths, assigning to him for initial investigation. 

Please note the Priority label :)

**Comment by jebriede** [comment]
We have identified and fixed an issue that was contributing to the slownless here: https://github.com/NuGet/NuGet.Client/pull/4739. There are still additional contributors for which we have planned longer-term solutions on our road-map that we will track and address separately.
