### ISSUE TITLE
Can't install MvvmCross into Xamarin project in VS2015

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#1172]
This problem was first reported in a forum (registration required): http://forums.somethingawful.com/showthread.php?threadid=3644791&pagenumber=92#post448918549

*"It's now impossible to install the package MvvmCross into a Xamarin.iOS or Xamarin.Android app. I have to open up VS2013 and use NuGet there to get things working."*

Repro: 1. Install VS2015 with Xamarin support. 2. File>New>C#>Android>BlankApp. 3. ManageNugetReference > install "MvvmCross".
 
What I get: an error message which says it can’t install MvvmCross.PortableSupport.3.5.1 into a project that targets ‘monoandroid5’. Note that the package itself has only one directory, lib\portable-win+net45+wp8+win8+wpa81, and this directory only contains `_._`
 
This looks like a regression. In VS 2013 Update 4 + Xamarin, I can install MvvmCross into a Xamarin Android app.

Note that Mono was treated specially in NuGet v2 – it might have regressed.

**Comment by yishaigalatzer** [comment]
@zhili1208 please investigate

**Comment by emgarten** [comment]
@zhili1208 for NuGet to automatically determine Xamarin support it needs to recognize that the folder is a known profile. It's possible that having win in the folder name twice is causing this to fail. Debugging what TxMs the package reader shows for this package might be a good place start.

**Comment by RanjiniM** [comment]
Verified as working
