### ISSUE TITLE
Error	NU3008	Package 'SQLitePCLRaw.lib.e_sqlite3 2.0.2' from source 'https://api.nuget.org/v3/index.json': The package integrity check failed. The package has changed since it was signed.[Bug]: 

### ISSUE THREAD

**Issue by ZainebLM** [NuGet/Home#11729]
### NuGet Product Used

NuGet.exe

### Product Version

visual studio 2019

### Repro Steps & Context

while cloning git repository . my packages are not installed properly.i i am getting this error.please provide solution

### Verbose Logs

```shell
Nuget issue
```

**Comment by dominoFire** [comment]
Can you provide a sample project/solution and all build/restore messages that shows the restore failure?

Also, take a look at NU3008 page with possible solutions. https://docs.microsoft.com/nuget/reference/errors-and-warnings/nu3008

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
