### ISSUE TITLE
Package restore should fail if a package with runtime-specific assets doesn't provide an asset

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1173]
Consider a package that provides runtime assets for different platforms/architectures. If you specify a different runtime than the package provides, package restore will succeed and silently not provide any runtime-specific assets. We should make that be a failure so the user doesn't get downstream failures.

**Comment by yishaigalatzer** [comment]
I think this is a valid scenario if for example the runtime assets are expected to be in the GAC for say NET45.

Do you have a specific scenario where this failure was hit?

**Comment by yishaigalatzer** [comment]
CC @anurse @davidfowl @emgarten

**Comment by yishaigalatzer** [comment]
Please reachout to @jasonmalinowski for more info, and schedule a design discussion before fixing this.

**Comment by yishaigalatzer** [comment]
@davidfowl this needs a design, do you have any thoughts on the matter?

**Comment by davidfowl** [comment]
Hmmm tricky one. What if a package provides a portable implementation for everyone but optimized implementations for specific RIDs? We need to be able to tell the difference.

**Comment by nkolev92** [comment]
There hasn't been any traction here in a while. No customer reports?
Closing this for now. We can open a new issue if we consider it important.
