### ISSUE TITLE
Large number of allocations while processing package references

### ISSUE THREAD

**Issue by Erarndt** [NuGet/Home#11733]
When calling `GetPackageReferenceUtility.GetInstalledVersion()` and `GetPackageReferenceUtility.GetTransitivePackagesForLibrary()` large amounts of memory are allocated to execute LINQ queries; primarily due to capture classes, delegates, and enumerators. In the case of OrchardCore, this totals to ~22MB. By unrolling these LINQ queries, we can eliminate these allocations and get a small reduction in CPU usage too.

**Comment by dominoFire** [comment]
@Erarndt Did you create this issue using 'blank issue' feature in GitHub? I'm asking because our bot should have labeled this issue automatically.

@heng-liu Does bot should also tag issues created from blank template?

**Comment by Erarndt** [comment]
@dominoFire I created a blank issue.

**Comment by nkolev92** [comment]
@dominoFire The Triage:Untriaged label is set by the issue templates, not a bot.
