### ISSUE TITLE
[Bug]: PM UI version list only shows a single latest version

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#11734]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.2.0 Preview 3.0 [32407.349.d17.2] 

### Worked before?

Yes, works in 17.1.1 and 17.3.0 preview 1.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Open PM UI for a .net project
1. Switch to Browse tab
1. Ensure NuGet.org is the selected source
1. Search for `azure.resourcemanager`
1. Observe the version list menu

![image](https://user-images.githubusercontent.com/94054/162587120-48259e2f-33a6-46fa-95eb-473e7556afc9.png)

It should show many versions, not just one.

I was unable to use "Report an issue" in VS because that option made VS lock up. I'm not sure how to report that.

**Comment by dominoFire** [comment]
We are tracking this on https://github.com/NuGet/Client.Engineering/issues/1487

There is a PR available with bugfix: https://github.com/NuGet/NuGet.Client/pull/4509

**Comment by dominoFire** [comment]
My bad, this is the fix: https://github.com/NuGet/NuGet.Client/pull/4478

**Comment by dominoFire** [comment]
Workaround is to delete content in version textbox/drop down list and PM UI will show you available versions.

**Comment by martinrrm** [comment]
@dominoFire I think this bug is different from https://github.com/NuGet/NuGet.Client/pull/4478, I can see this error without Floating Versions feature. 

Version 17.2.0 Preview 3.0 [32320.37.main]

![image](https://user-images.githubusercontent.com/43253759/162800309-23940d4d-886a-4f5a-98e3-9f154b1e0145.png)

**Comment by martinrrm** [comment]
Wait, it works, is just that there is only one version that is not prerelease, my bad. 

It looks like the first time you open the combobox the filter is wrong. It looks like an error when you have the prerelease checkbox, I think this is a new bug, I'll investigate about it

**Comment by nkolev92** [comment]
Hey folks, for issues that obvious bugs and that are known as something that needs to be done, or being actively worked on, to fully self triage: 

https://github.com/NuGet/Client.Engineering/blob/main/docs/creating-github-issues.md
