### ISSUE TITLE
API for xproj tooling to run Init.ps1 in Package Manager Console

### ISSUE THREAD

**Issue by rowanmiller** [NuGet/Home#1174]
In order to enable Init.ps1 to register commands in Package Manager Console for xproj based projects we concluded that we need an API in NuGet that xproj tooling can call as part of it's package restore process.

The main driving force behind this is the EF migration commands which use PMC in all other project types but in xproj you need to drop out to a cmd line which is pretty jarring for visual developers.

**Comment by yishaigalatzer** [comment]
Moving tentatively to this milestone, needs discussion and planning to see if it fits

**Comment by yishaigalatzer** [comment]
Closing as we decided this will be part of the tooling merge
