### ISSUE TITLE
[Bug]: There is no black arrow install button on the right of custom feed package when hovering on the package in “Browse” tab of PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11757]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.24

### Worked before?

Dev\6.3.0.12

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. File->New Project->Visual F#, create a Console Application project. 
2. Open Package Manager Settings dialog (Tools->NuGet Package Manager->Package Manager Settings). 
3. Add a custom feed source, type in the name is 'Myget' and the source is https://www.myget.org/F/andy-nuget-project/api/v2. 
4. Start NuGet Package Manager dialog and select the ‘Myget’ package source. 
5. Go to “Browse” tab and hover on the package 'knockoutjs'.

## Expected
There is a black download arrow on the right of package list in “Browse” Tab when hovering on the package as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/163995283-6912e272-5c15-4f2a-8c76-c78dac2462b0.png)

## Actual
There is no black arrow install button on the right of custom feed package when hovering on the package as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/163995344-9660c421-f5f3-4f8d-8df5-f33b70eedba9.png)

## Notes
1. This issue does not repro on NuGet Client Dev\6.3.0.12.
2. This issue does not repro on NuGet public feed.

**Comment by nkolev92** [comment]
Possible that https://github.com/NuGet/NuGet.Client/commit/74ec8baeb1577f68d77320223c7c6285b8f9c779 is the problem. 

Assigning to @martinrrm for the initial investigation.
