### ISSUE TITLE
[Feature]: Retain Command History After Closing and Opening Visual Studio

### ISSUE THREAD

**Issue by kellielellie1** [NuGet/Home#11759]
### NuGet Product(s) Involved

Visual Studio Package Manager Console

### The Elevator Pitch

Package Manager Console does retain command history in a temporary manner but in between closing and opening of Visual Studio that history is gone. 

Please can the command history be retained after closing and opening of Visual Studio.

**Comment by kartheekp-ms** [comment]
@kellielellie1 - AFAIK this looks like a feature of PowerShell in general. I created a sample project and then installed a package using PMC and then followed the example in https://docs.microsoft.com/powershell/module/microsoft.powershell.core/add-history?view=powershell-7.2#example-1-add-commands-to-the-history-of-a-different-session to share the commands across different sessions.
- Open VS and execute `Install-Package NuGet.Common` in NuGet Package Manager Console.
- Execute `Get-History | Export-Csv c:\testing\history.csv` in first session.
- Close VS
- Open VS and select a project
- Execute `Import-Csv c:\testing\history.csv | Add-History` command to import the commands from the first session.
- Execute `Get-History` and I can see `Install-Package NuGet.Common` (step 1) in the commands list.

Hope it helps.

**Comment by nkolev92** [comment]
Team Triage; Closing per the above comment. 

The history is PMC is a general powershell feature.
