### ISSUE TITLE
Missing Visual Studio 2015 - NuGet Package Manager menu missing - not in gallery also

### ISSUE THREAD

**Issue by Billj111** [NuGet/Home#1175]
How do I get this to show up?
I thought it was built into the visual studio 2015 - I also do not see it in the online gallery in extensions and updates

**Comment by yishaigalatzer** [comment]
We have noticed the extension doesn't show up on the gallery earlier today, and we are working with the gallery owners on this. 

The extension should be available in Visual Studio by default.

Can you try installing it from here - https://github.com/nuget/home/releases

**Comment by yishaigalatzer** [comment]
This is now addressed, please re-open if you can't get it.

**Comment by Billj111** [comment]
Works now. Thanks.
