### ISSUE TITLE
Package manager UI should be only updated only when there is an important state change

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#11750]
Track https://github.com/NuGet/NuGet.Client/pull/4535#discussion_r848924794. Package manager UI should be only updated only when there is an important state change.

Also https://github.com/NuGet/NuGet.Client/pull/4535#discussion_r848675522 and https://github.com/NuGet/NuGet.Client/pull/4535#discussion_r848675567

**Comment by nkolev92** [comment]
Closing as the fix was reverted.
