### ISSUE TITLE
[Bug]: NU1604	Project dependency Newtonsoft.Json does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

### ISSUE THREAD

**Issue by Varorbc** [NuGet/Home#11768]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.2.0 Preview 4.0

### Repro Steps & Context

```
Directory.Packages.props

<Project>
	
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>
	
</Project>

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  	<PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
	
</Project>


```

**Comment by jeffkl** [comment]
@Varorbc Sorry I just realized our documentation does not call out that central package management (CPM) is off by default and you must enable it with the `ManagePackageVersionsCentrally` property:

```xml
  <PropertyGroup>
    <!-- Enable central package management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
```
I recommend you place that property in `Directory.Packages.props`

Here is an example of CPM and some of the features: https://github.com/NuGet/Samples/tree/main/CentralPackageManagementExample

I'll get the docs updated.

**Comment by Varorbc** [comment]
Thank you very much for your reply. I have another question. how to update the central package version by Visual Studio package management UI?

**Comment by jeffkl** [comment]
@Varorbc We are actively working with folks in Visual Studio to support updating PackageVersion items in Visual Studio.  At this time, you must manage the XML manually.

**Comment by jeffkl** [comment]
I've updated the docs: https://github.com/NuGet/docs.microsoft.com-nuget/pull/2732

@Varorbc thanks for reporting the issue, please close the if you feel that it has been addressed.

**Comment by japj** [comment]
I also just ran into this issue with 17.2.0 Preview 4.0 (so very glad to get the solution here ;) )

I also noticed when enabling (and having multiple package sources) there might be a string formatting issue in one of the error messages (notice the {0} in the actual message):

`error NU1507: There are {0} package sources defined in your configuration. When using central package management, please map your package sources with package source mapping (https://aka.ms/nuget-package-source-mapping) or specify a single package source.`

**Comment by jeffkl** [comment]
The warning message missing the number has been fixed and should be available soon

https://github.com/NuGet/Home/issues/11709
