### ISSUE TITLE
[Bug]: Upgrading a package across a large solution is downgraded when it should not have been

### ISSUE THREAD

**Issue by kabua** [NuGet/Home#11777]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

vs 16.11.5

### Worked before?

Not really

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We have 187 projects in our master solution and we publish several internal frameworks as nuget packages, which these projects require. Also, there are several project dependencies between the various projects. Therefore, we need to upgrade everything all at once.

However, instead of having a clean upgrade process, we keep getting `Detected package downgrade` errors, regardless of which "Install and **Update** Options" we pick. And the note: 
```These options are not applicable to projects managing their dependencies through project.json or PackageReference```

This makes no sense since all of our projects use PackageReferences. So, when do these options apply then? 

Example of the error message, and thus the bug:
```
NU1605: Detected package downgrade: F from 9.5.4-b001-Debug to 9.5.4-a015-Debug. 
Reference the package directly from the project to select a different version. 
 A -> B -> C -> D -> E 9.5.4-b001-Debug -> F (>= 9.5.4-b001-Debug) 
 A -> B -> F (>= 9.5.4-a015-Debug)
```

First issue: the message "Reference the package directly from the **project** to select a different version." 

Which project? We have 187 of them. Therefore, this message should be changed to specify which project.

Main Issue:
1. The upgrade rules clearly state that `B` can use any version of `F` that is greater than or equal to `9.5.4-a015-Debug`
2. According to [semver 2.0](https://semver.org/#spec-item-11) sections 11.4.2 & 11.4.4, (assuming we have read the spec correctly) state that the version number `9.5.4-b*` is greater than `9.5.4-a*`.
3. Therefore, `F 9.5.4-b001-Debug` is greater than `F 9.5.4-a015-Debug` which satisfies the upgrade rule (see item 1 above.)

Thus this package should **not** be downgraded. Because of these bogus errors, it is very challenging to upgrade our projects.

This behavior also suggests that the Nuget Manager is not following the solution's build dependencies, otherwise `B` would have been upgraded before `A` and this issue would not have existed in the first place.

**Comment by erdembayar** [comment]
@kabua 
Sorry hear about this. Did you try solutions from [MS NU1605 doc](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605)? Here nearest win logic resolving F (>= 9.5.4-a015-Debug), instead you can install  `F (>= 9.5.4-b001-Debug)` directly to top project `A` to make more near than `A -> B -> F (>= 9.5.4-a015-Debug)`.
There're 2-3 different approaches for this issue in the NU1605 doc.

@nkolev92 
> First issue: the message "Reference the package directly from the project to select a different version."

> Which project? We have 187 of them. Therefore, this message should be changed to specify which project.

Do we have tracking issue surfacing error message better, inform which specific projects have issue?

**Comment by erdembayar** [comment]
@kabua 
Please take a look at latest [Central Package Management](https://devblogs.microsoft.com/nuget/introducing-central-package-management/#:~:text=To%20get%20started%20with%20central%20package%20management%2C%20you,elements%20that%20define%20the%20package%20ID%20and%20version.) feature. It's designed for addressing same problems you're facing now.
Not only it lets you set version for top level package dependency it lets you set versions for transitive dependencies in 1 place, still lets you override it case by case. 
Currently we don't have Package Management UI in VS to work with Central Package Management, so you need to edit it manually. 
If you have any feedback about this new feature please let us know.

**Comment by nkolev92** [comment]
Hey @kabua 

You mentioned `Which project? We have 187 of them. Therefore, this message should be changed to specify which project.` 

Can you paste the full log. 

For example when I try to repro I see the path in front. 
The first project in the path will be one where you can add the package. 

Example

> NU1605: Detected package downgrade: F from 9.5.4-b001-Debug to 9.5.4-a015-Debug. 
Reference the package directly from the project to select a different version. 
 A -> B -> C -> D -> E 9.5.4-b001-Debug -> F (>= 9.5.4-b001-Debug) 
 A -> B -> F (>= 9.5.4-a015-Debug)
 
 It's likely recommending to reference the package directly from the A project.

**Comment by nkolev92** [comment]
Re-reading your post, I have a few more clarifications :) 

> The upgrade rules clearly state that B can use any version of F that is greater than or equal to 9.5.4-a015-Debug

That's fair, but NuGet respects the user intent. If someone explicitly wants a lower version, like in your case, B explicitly wants a lower version of than it's dependencies are trying to bring. 
It's not a really semver thing.

**Comment by erdembayar** [comment]
@kabua 
> First issue: the message "Reference the package directly from the project to select a different version."

> Which project? We have 187 of them. Therefore, this message should be changed to specify which project.

Soon new feature which surfaces all transitive dependencies so you can view which project is bringing which dependencies more clarity. You can see brief details here: https://github.com/NuGet/NuGet.Client/pull/4465

**Comment by nkolev92** [comment]
You can always use the solution explorer to view the transitive dependencies.

![image](https://user-images.githubusercontent.com/2878341/166291246-afa0a6b2-26fa-49be-9cb3-ba99b6944960.png)

**Comment by nkolev92** [comment]
Thank you for your feedback, at this point we cannot confirm that there's an issue with the downgrade warnings. 

Consider trying out CPM as @erdembayar suggested in https://github.com/NuGet/Home/issues/11777#issuecomment-1113436780, which is an experimental feature designed to help scenarios like yours.
