### ISSUE TITLE
[Bug]: RestoreLockedMode fails when overriding reference from Directory.Builds.prop

### ISSUE THREAD

**Issue by MisinformedDNA** [NuGet/Home#11776]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.202

### Impact

It's more difficult to complete my work.

### Repro Steps & Context

1. Run `dotnet new console`
2. Replace the project file contents with the following

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RestoreLockedMode>true</RestoreLockedMode>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>

</Project>
```

3. Run `dotnet restore`
4. Note that `packages.lock.json` specifies version `6.0.0` of `Microsoft.Extensions.DependencyInjection`
5. Create `Directory.Build.props` with the following contents

```xml
<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
  </ItemGroup>
</Project>
```

6. Run `dotnet restore`

EXPECTED: 

Operation completes successfully. `packages.lock.json` continues to use version of `6.0.0` of `Microsoft.Extensions.DependencyInjection`

ACTUAL:

Receive error message: 

> C:\temp\RestoreIssue\RestoreIssue.csproj : error NU1004: The package reference Microsoft.Extensions.DependencyInjection version has changed from [6.0.0, ) to [5.0.0, ).The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.

### Verbose Logs

[log.txt](https://github.com/NuGet/Home/files/8565927/log.txt)

**Comment by erdembayar** [comment]
I can repro this issue in both sdk5 and sdk6.

**Comment by nkolev92** [comment]
Latest NuGet will raise a warning for duplicate PackageReference, https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1504. 

Duplicate PackageReference cause ambiguity among the different toolings and as such should be avoided.

**Comment by MisinformedDNA** [comment]
The warning makes sense for duplicate PackageReferences within a single project file. But should that be the case when the "duplicate" is coming from another file (i.e. `Build.Directory.props`)? Or should it override it?

**Comment by nkolev92** [comment]
For MSBuild purposes, project file vs any other file doesn't really matter. It's still part of the project.

**Comment by zivkan** [comment]
If you want to override a version in the csproj, for a package referenced in Directory.Build.props, you can use MSBuild's Update (rather than Include):  `<PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />`.  This way MSBuild doesn't see two items with the same id, and therefore there are no risks of which one gets chosen when deduplicated (first wins vs last wins vs random).

**Comment by erdembayar** [comment]
I tested your scenario on my local.
In this case override in `Build.Directory.props` didn't work, but placing into `Build.Directory.targets` worked for me.
It looks like settings in props is seen by msbuild 1st but csproj is overriding it, but targets is executed later than csproj.
```
<Project>
  <ItemGroup>
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/8766776/165871886-6772e732-c2a5-404d-aaad-c1a7ad872c9f.png)

Please let me know if works for you.

**Comment by MisinformedDNA** [comment]
Yes, this works, but in my case, I replaced `Include` with `Update` in my CSPROJ file to override the PROPS file.

**Comment by erdembayar** [comment]
Sure, yesterday I didn't test correctly.

CSProj file file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <RestoreLockedMode>true</RestoreLockedMode>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  </ItemGroup>

</Project>
```

Build.Directory.props:

```
<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.0" />
  </ItemGroup>
</Project>
```

packages.lock.json:
![image](https://user-images.githubusercontent.com/8766776/165971077-d1f73d7e-a312-46ea-a90f-84aa5c12fd28.png)
