### ISSUE TITLE
after upgrade, cannot reach internal nuget server

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1178]
_From @RipCurrent on August 6, 2015 14:49_

hi,
can anyone give me guidance on this issue:

installed vs2015 & got latest nuget 3.1(?). Also upgraded command line to nuget v2.8.60717.93

I can reach external nuget feeds and localhost nuget feed.
I can no longer reach internal corporate nuget feeds. 404 error

I downloaded source code from codeplex and ran command line tool in debug mode.
With fiddler, I can see the v3 api call to internal server "{url}\intercept.json " which returns 404 (also see iis log entry)
After the 404, it then tries the request using v2 and just "{url}" and errors out
Nothing in fiddler for this or in IIS log, as if it never tried it.

other users who upgraded to VS2015 ok (they don't have command line). can ideas on how I might get going again here?
:)
thanks!

_Copied from original issue: NuGet/NuGetGallery#2608_

**Comment by yishaigalatzer** [comment]
Command line 2.8.6 still doesn't support the V3 API, you need to try the http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe

I suggest you look into how your nuget.config differs from other people on your team.

**Comment by yishaigalatzer** [comment]
@ripcurrent can you provide more details or update on your issue?

Can you share the url for your server, and some more details about it?

**Comment by yishaigalatzer** [comment]
@ripcurrent we haven't heard anything on this for over a month now. 

I'm closing this, but feel free to resurrect the thread.

Note that we since release NuGet 3.2 (both command line and a vsix)

See - https://dist.nuget.org/index.html
