### ISSUE TITLE
nuget integrity check DocumentFormat.OpenXml 2.16.0

### ISSUE THREAD

**Issue by patrick-m-kendall** [NuGet/Home#11799]
I am getting an integrity check on the DocumentFormat.OpenXml 2.16.0 package. I have tried both the Package Manager Console and the NuGet Package Manager.

thanks

**Comment by zivkan** [comment]
team triage meeting:
1. You can try deleting the package from your global packages folder, and run `dotnet nuget locals http-cache --clear` and try again.
2. We don't support individual packages, so you can go to https://www.nuget.org/packages/DocumentFormat.OpenXml/ and use the [contact owners](https://www.nuget.org/packages/DocumentFormat.OpenXml/2.16.0/ContactOwners) link to contact the package author for help.
3. If you have problems with multiple packages, please use our bug issue template
