### ISSUE TITLE
Package Newtonsoft.json install fails with NU3008

### ISSUE THREAD

**Issue by cfairchi** [NuGet/Home#11791]
GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 202ms
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.1/newtonsoft.json.13.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/index.json 215ms
  GET https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/4.8.3/system.data.sqlclient.4.8.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.1/newtonsoft.json.13.0.1.nupkg 46ms
  OK https://api.nuget.org/v3-flatcontainer/system.data.sqlclient/4.8.3/system.data.sqlclient.4.8.3.nupkg 99ms
Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json': Verifying the author primary signature with certificate: 

Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json':   SHA1 hash: 4CFB89FAA49539A58968D81960B3C1258E8F6A34
Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json':   Issued by: CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json': Timestamp: 3/17/2021 4:03:36 PM

Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json': Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=DigiCert Timestamp 2021, O="DigiCert, Inc.", C=US
  SHA1 hash: E1D782A8E191BEEF6BCA1691B5AAB494A6249BF3
  SHA256 hash: B3109006BC0AD98307915729E04403415C83E3292B614F26964C8D3571ECF5A9
  Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 12/31/2020 7:00:00 PM to 1/5/2031 7:00:00 PM

NU3008: Package 'Newtonsoft.Json 13.0.1' from source 'https://api.nuget.org/v3/index.json': The package integrity check failed. The package has changed since it was signed. Try clearing the local http-cache and run nuget operation again.
Package restore failed. Rolling back package changes for 'GoldenTeeDataService'.

**Comment by martinrrm** [comment]
Thanks for filing the issue, but please open a new bug following the template so we can understand your issue better.
