### ISSUE TITLE
[Bug]: Visual Studio restore sometimes sets originalTargetFrameworks incorrectly in project.assets.json

### ISSUE THREAD

**Issue by tg73** [NuGet/Home#11795]
### NuGet Product Used

Other/NA

### Product Version

VS 2019 16.11.7, VS 2022 17.1.6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The issue is seen in `project.assets.json` at `project/restore/originalTargetFrameworks`. The issue is present only for some values of `$(TargetFramework)`. I see the issue when `$(TargetFramework)` is `net6.0-windows`, but not when using, for example, `net6.0`. Examples below are when `$(TargetFramework)` is `net6.0-windows`:

Relevant portion of `project.assets.json` after MSBuild command line restore:
```json
      "originalTargetFrameworks": [
        "net6.0-windows"
      ],
      "frameworks": {
        "net6.0-windows7.0": {
          "targetAlias": "net6.0-windows",
          "projectReferences": {}
        }
      },
```

Relevant portion of `project.assets.json` after Visual Studio restore:
```json
      "originalTargetFrameworks": [
        "net6.0-windows7.0"
      ],
      "frameworks": {
        "net6.0-windows7.0": {
          "targetAlias": "net6.0-windows",
          "projectReferences": {}
        }
      },
```

The documentation for `NuGet.ProjectModel.ProjectRestoreMetadata.OriginalTargetFrameworks` states:
```
Original target frameworks strings. These are used to match msbuild conditionals to $(TargetFramework)
```
Therefore I would suggest that MSBuild command line is behaving correctly, and Visual Studio is behaving incorrectly. This difference in behaviour has broken one of our build customizations. It will also create churn when mixing VS and command line builds, causing unnecessary rebuilds.

Repro project/solution: [ClassLibrary1.zip](https://github.com/NuGet/Home/files/8639413/ClassLibrary1.zip)

**Comment by nkolev92** [comment]
Great catch @tg73. Thanks for the analysis.

The fix should be in https://github.com/NuGet/NuGet.Client/compare/dev-nkolev92-fixOriginalTargetFrameworks?expand=1
I'll add some tests soon.
