### ISSUE TITLE
[Feature]: dotnet list package report with definable column widths

### ISSUE THREAD

**Issue by williamdenton** [NuGet/Home#11790]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

an option to specify the minimum width of the package name column in the list packages report

### Additional Context and Details

I would like to use the dotnet package list command to inspect all the packages in a project and compare the packages referenced between builds. I use this to monitor the changes to packages, especially transitive ones between builds. It would be very convenient if the column with was configurable so the layout didn't change depending on the length of the package names, then i wouldn't need to do any post processing on the file

originally posted here https://github.com/dotnet/sdk/issues/25159

**Comment by zivkan** [comment]
@williamdenton would you still want this feature if `dotnet list package` had a `--format json` feature? https://github.com/NuGet/Home/issues/7752

**Comment by williamdenton** [comment]
json format would be excellent

**Comment by zivkan** [comment]
In that case I'll close this feature request as it might not be needed once json output is implemented.  If you haven't already, please consider adding a 👍 reaction to the original/top comment in that issue, as we use upvotes as one input in our prioritization process.
