### ISSUE TITLE
[Bug]: `SecurePluginCredentialProvider.GetAsync` calls `GetAuthenticationCredentialsRequest` wrong

### ISSUE THREAD

**Issue by DavidKarlas** [NuGet/Home#11801]
### NuGet Product Used

NuGet SDK

### Product Version

Any version

### Worked before?

No

### Impact

I'm unable to use this version

### Repro Steps & Context

I wrote at length about this issue in https://github.com/NuGet/docs.microsoft.com-nuget/issues/2715

At time I was asking about documentation mismatch between caller and callee. It was answered I should look at https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-plugins for documentation which states:
> If present, indicates that this attempt is a retry of a previously failed attempt. Providers typically use this flag to ensure that they bypass any existing cache and prompt for new credentials if possible.

Hence I'm opening issue that `SecurePluginCredentialProvider.GetAsync` is setting wrong value for `isRetry` parameter on `GetAuthenticationCredentialsRequest`.

Until this is fixed, multiple calls to authenticated feed is/will be broken.

**Comment by dominoFire** [comment]
@DavidKarlas Thanks for filing this issue. We are open to accept a pull request if you feel confident about setting a new value

**Comment by zivkan** [comment]
team triage meeting:  Looks like a duplicate of https://github.com/NuGet/Home/issues/11210

please add a 👍 reaction to upvote that issue.
