### ISSUE TITLE
[Feature]: Allow for viewing readme when package not hosted on nuget.org

### ISSUE THREAD

**Issue by mahgo** [NuGet/Home#11800]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

I have a nuget package hosted in a private repository (Aerion Devops Artifacts). It would be good to be able to view the readme file in Visual Studio that is embedded in my nuget package.

**Comment by zivkan** [comment]
The private feeds need to implement the Nuget API to provide Visual Studio with the information/links to display.

Unfortunately for embedded readmes, the documentation appears to be lacking, so I've filed this docs bug as a first step: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2752
