### ISSUE TITLE
2013 Release: 2.8.60610.756 (NuGet check for updates broken) vsix download required?

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1180]
_From @tombrown571 on July 24, 2015 7:33_

After installing 2.8.60610.756 (on top of VS 2013 Update 5) I get an error loading package manager in NuGetVSEventsPackage

This appears to prevent NuGet from checking for updates.

Its very similar to this issue http://nuwanlanka.com/?p=85#comment-163 
From this blog, the fix appears to be to re-run the vsix package from outside visual studio - only as you are in the process of moving to GitHub, I can't find a download link for the correct vsix package (and I'm not sure it will fix the issue until I try it)

From the Activity Log
1090 ERROR CreateInstance failed for package [NuGetVSEventsPackage] {98BF0691-D23C-4897-A241-9CF5BEFDCC4A} 80070002 VisualStudio 2015/07/23 13:11:27.910 
1091 ERROR End package load [NuGetVSEventsPackage] {98BF0691-D23C-4897-A241-9CF5BEFDCC4A} 80004005 - E_FAIL VisualStudio 2015/07/23 13:11:27.910 

_Copied from original issue: NuGet/NuGetGallery#2594_

**Comment by yishaigalatzer** [comment]
This got fixed here - https://github.com/NuGet/Home/issues/1105

@feiling can you provide a workaround if possible, and the link to download?

**Comment by yishaigalatzer** [comment]
@feiling this looks like a dup of the one you opened today #1353

**Comment by rohit21agrawal** [comment]
This seems to have been fixed. Verified using VS 2013 Update 5 and NuGet 2.8.60723.765
