### ISSUE TITLE
[Bug]: NOTICE.TXT includes Lucene references

### ISSUE THREAD

**Issue by mirespace** [NuGet/Home#11804]
### NuGet Product Used

Other/NA

### Product Version

dotnet --info .NET SDK (reflecting any global.json):  Version:   6.0.104  Commit:    915d644e45

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Hi,

I'm writing here as I'm packaging dotnet suite for Ubuntu from source build, and we are finding some 3rd party software issues, one of them related to the Nuget.client as you can read here https://github.com/dotnet/source-build/issues/2147#issuecomment-1121310464.

The file https://github.com/NuGet/NuGet.Client/blob/0471d9e44848c4d00e37f2f7d4e9a1b69eb0b213/src/NuGet.Clients/NuGet.VisualStudio.Client/NOTICES.txt is propagated to the dotnet suite tarball source (it was built using MSBuild) through the processes carried out by the installer and the source build repos (it creates a /src/nuget-client.* folder), but looking at the software build and also the source code, the references to Lucene are no longer present (src/Lucene.Net/\*) ... could it be not up-to-date? Could you check it, please?

Thanks in advance. Kind regards,

Miriam

**Comment by zivkan** [comment]
The NuGet.Client repo contains the source not only for NuGet's components that ship in the .NET SDK, but also NuGet's Visual Studio extension.  As the folder name for the NOTICES.txt file suggests, the file is related to our Visual Studio extension, not the .NET SDK. We don't ship Lucene.NET in the .NET SDK, only in Visual Studio.

Additionally, we don't build Lucene.NET ourselves, or copy the source in our repo, we consume the pre-built binaries as a NuGet package. The NOTICES.txt file is not a notice of the source code in the repo, it's a notice of the binaries that are installed in the `$(VS install directory)\Common7\IDE\CommonExtensions\Microsoft\NuGet` directory. For example, it also lists Newtonsoft.Json, but we don't have Newtonsoft.Json's source in our repo either.

**Comment by zivkan** [comment]
Closing as there has not been any reply in 2 weeks.
