### ISSUE TITLE
[Bug]: [Bug Bash] The “Version” dropdown box is blank in “Consolidate” tab of solution-level PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11806]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.51

### Impact

It's more difficult to complete my work

### Details about Problem
VS Version: Main\32509.107
NuGet Version: Dev\6.3.0.51
OS Version: Windows-11-Enterprise-21H2

### Repro steps:
1.Create a solution with two C# Console App (.NET Framework 4.8) projects in VS.
2.Right-Click the solution in the Solution Explorer and select the “Mange NuGet Packages for Solution”.
3.Go to “Browse” tab, select a package (e.g. Newtonsoft.Json) and install different versions (with PackageReference format) into the different projects. (e.g. install 12.0.1 into the first project, install 12.0.2 into the second project)
4.Click the “Consolidate” tab, click the package “Newtonsoft.Json” in the list and observe the “Version” dropdown box.

### Expected:
The “Version” dropdown box is showing the latest installed version (12.0.2 in this instance), the version in the drowdown list can be reselected and the "Install" button is available.

### Actual:
The “Version” dropdown box is blank, the version in the drowdown list cannot be reselected and the "Install" button is not available as below.
![image](https://user-images.githubusercontent.com/20632625/167605435-14c7b265-c080-4976-bea9-a5117312a08a.png)

### Notes:
1. This issue starts to repro on Dev\6.3.0.10, does not repro on Dev\6.3.0.9.
2. It does not repro on .NET SDK style solution.
3. It does not repro when the package is installed with “packages.config” format in step3.

**Comment by dominoFire** [comment]
@martinrrm Could you please take a look?

**Comment by v-luzh** [comment]
Hi @martinrrm, it still repro on Main\32601.383 with implicit NuGet Dev\6.3.0.75 as below. I am reopening it now.
![image](https://user-images.githubusercontent.com/20632625/171601405-f2c696e0-f745-4dec-99a2-e7bf7ef740c2.png)

**Comment by v-luzh** [comment]
Close it as fixed on Main\32606.79+Dev\6.3.0.77. Thanks for fixing.
