### ISSUE TITLE
[Bug]: Regression in 6.0.300 'dotnet restore' for custom SDKs with version in global.json

### ISSUE THREAD

**Issue by dorssel** [NuGet/Home#11809]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet SDK 6.0.300

### Worked before?

dotnet SDK 6.0.202

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Was working before (6.0.202):

.csproj with:
```
<Project Sdk="Microsoft.Build.NoTargets">
```

global.json with:
```
...
 "msbuild-sdks": {
    "Microsoft.Build.NoTargets": "3.4.0"
  }
...
```

With 6.0.300, `dotnet restore` fails, and the project won't load in VS 2022 version 17.2.

To fix, I need to provide the SDK version in the project file:
```
<Project Sdk="Microsoft.Build.NoTargets/3.4.0">
```

Possibly related, the '/' syntax for the version must be used. The following syntax will *not* work:
```
<Project Sdk="Microsoft.Build.NoTargets" Version="3.4.0">
```
even though this syntax is allowed per the documentation.

See also: https://github.com/dorssel/usbipd-win/commit/bb16b3583eda4de4fa66b99fa2eee90b334ba4a9

### Verbose Logs

```shell
> dotnet restore

C:\Users\Frans\Source\Repos\usbipd-win\InstallerDependencies\InstallerDependencies.csproj : warning NU1503: Skipping restore for project 'C:\Users\Frans\Source\Repos\usbipd-win\InstallerDependencies\InstallerDependencies.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\Frans\Source\Repos\usbipd-win\usbipd-win.sln]
```

**Comment by jeffkl** [comment]
Duplicate of https://github.com/NuGet/Home/issues/11784

@dorssel sorry you're hitting the regression in the NuGet-based MSBuild project SDK resolver's global.json parser.  We've merged a fix and working on releasing it.

**Comment by dorssel** [comment]
Agreed, this is a side-effect of #11784.
