### ISSUE TITLE
[Bug]: Special case packages that use ``-dev`` suffixes as always being the latest version of the package.

### ISSUE THREAD

**Issue by AraHaan** [NuGet/Home#11803]
### NuGet Product Used

dotnet.exe, MSBuild.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

.NET SDK: 7.0.100-preview.5.22229.2, MSBuild (From Visual Studio and .NET SDK), Visual Studio: 17.2 Preview 6

### Worked before?

Nope

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

This thing annoys me that nuget always considers ``-dev`` as an downgrade for ``-preview.*``, or ``-beta.*`` packages when they are not (because they are local builds).

Consider the following:
- Project A references EFCore.SqlServer and an local build of Microsoft.Data.SqlClient (5.0.0-dev)
  - EFCore.SqlServer references Microsoft.Data.SqlClient (5.0.0-preview.2)

In this case it warns (or errors) even though technically my local build is newer than what 5.0.0-preview.2 provides.

### Verbose Logs

```shell
It should be easy to reproduce my creating an new library project (A) that then adds an package reference to EFCore.SqlServer, and then to an local build of Microsoft.Data.SqlClient.
```

**Comment by nkolev92** [comment]
The priority is based on the semver guidelines. 

In particular: https://semver.org/spec/v2.0.0.html#spec-item-11, part 4. 

Example here: https://nugettools.azurewebsites.net/6.0.0/sort-versions?versions=1.0.0-dev%0D%0A1.0.0-preview.1%0D%0A1.0.0-beta.1%0D%0A

This'd be a breaking change.
