### ISSUE TITLE
[Bug]: [Bug Bash] “Updates” tab will not show available-to-update packages in the solution-level PM UI when the solution having more than one project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11805]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.51

### Impact

It's more difficult to complete my work

### Details about Problem
VS Version: Main\32509.107
NuGet Version: Dev\6.3.0.51
OS Version: Windows-11-Enterprise-21H2

### Repro steps:
1.Create a solution with two C# Console App (.NET Framework 4.8) projects in VS.
2.Right-Click the solution in the Solution Explorer and select the “Mange NuGet Packages for Solution”.
3.Go to “Browse” tab, select a package (e.g. Newtonsoft.Json) and install different versions (with PackageReference format) into the different projects. (e.g. install 12.0.1 into the first project, install 12.0.2 into the second project)
4.Install package “Moq” (not latest version, e.g. 4.16.1) with PackageReference format into the second project.
5.Observe the “Updates” tab and click the “Updates” tab.

### Expected:
Correct number (should be 2 in this instance) is showing on the right of “Updates” tab and available-to-update packages (“Newtonsoft.Json” and “Moq” in this instance) should show in the list.

### Actual:
No number is showing on the right of “Updates” tab and no available-to-update packages are showing in the list as below.
![image](https://user-images.githubusercontent.com/20632625/167604752-d49b838c-fbdd-4aeb-8bb9-3f048ce3d14b.png)

### Notes:
1. This issue starts to repro on Dev\6.3.0.10, does not repro on Dev\6.3.0.9.
2. It does not repro when the solution just having one project.
3. It does not repro on .NET SDK style solution.
4. It does not repro when the package is installed with “packages.config” format in step3.

**Comment by nkolev92** [comment]
Started by https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5985668&view=results.

**Comment by v-luzh** [comment]
It is fixed on Dev\6.3.0.77.
