### ISSUE TITLE
[Bug]: The Latest Stable version does not show in the "Version" dropdown box after installing a package with not the latest version in “Updates” tab

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11802]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.51

### Worked before?

Dev\6.3.0.15

### Impact

It bothers me. A fix would be nice

## Repro steps:  
1. Create a C# Console App (.NET core) project via VS.
2. Open PM UI of the project by right clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Install a package (e.g. Newtonsoft.json) into the project with not the latest version in “Browse” tab.
4. Switch to the “Update” tab and observe the “version” dropdown box.
## Expected:
The Latest Stable version should show in the "Version" dropdown box in “Updates” tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/167382210-fb22f501-d939-4b55-b829-c0cef045cc9a.png)
## Actual: 
The installed version shows in the "Version" dropdown box in “Updates” tab as below screenshot. 
![image](https://user-images.githubusercontent.com/71433406/167382264-80ea98ca-f41e-42c0-85bb-51aa1724324a.png)
## Note:
1. This issue starts to repro on Dev\6.3.0.17.

**Comment by dominoFire** [comment]
@martinrrm Could you please take a look? Thanks! This seems related https://github.com/NuGet/Home/issues/11806
