### ISSUE TITLE
[Bug]: Can't build anymore with temporarily failing nuget source

### ISSUE THREAD

**Issue by marnilss** [NuGet/Home#11811]
### NuGet Product Used

dotnet.exe

### Product Version

Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET / mcr.microsoft.com/dotnet/sdk:6.0.300

### Worked before?

Microsoft (R) Build Engine version 17.1.1+a02f73656 for .NET / mcr.microsoft.com/dotnet/sdk:6.0.202

### Impact

I'm unable to use this version

### Repro Steps & Context

In a nuget.config file we have the following line:
```
<add key="localFileSource" value="%TEMP%\nugetfeed.local" />
```
Which means that we have a local folder-based Nuget feed, in a subfolder of the local TEMP-folder.

While building on a machine, where that folder exists - no problems.

If that folder is missing, e.g. when building in a docker-environment, that build fails.
> Line in Dockerfile: `RUN dotnet build "ST.DRT.Booking.API.csproj" -c Release -o /app/build`

BUT if we added msbuild property _RestoreIgnoreFailedSources_ in .csproj:
`<RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>`
Build now worked, but generated alot of warnings

A lot of warnings was reported as an issue in #9765 , and while fixing that probably something fundamentally broke.
**Now, with latest version, I can not find a way to get build to complete when that folder is missing (in Docker environment) - it always fails!**

With _RestoreIgnoreFailedSources_ set to _true_ (which worked before): build now throws:
> /src/ST.DRT.Booking.API/ST.DRT.Booking.API.csproj : error NU1801: The local source '/src/%TEMP%\nugetfeed.local' doesn't exist.

With _RestoreIgnoreFailedSources_ missing or set to _false_ (which used to generate NU1801 errors): build now throws
> /src/ST.DRT.Booking.API/ST.DRT.Booking.API.csproj : error NU1301: The local source '/src/%TEMP%\nugetfeed.local' doesn't exist.

And note, they are both errors, not warnings, so they can not be suppressed.
I'm guessing that while trying to fix the issue above, something got terribly broken, because with latest version build always fails!

**Comment by marnilss** [comment]
Commandline: 
===============================
docker build -t drt-booking . -f src\ST.DRT.Booking.API\Dockerfile --no-cache --progress=plain > builder.log 2>&1

Dockerfile: 
===============================
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY "src/" "/src"
WORKDIR "/src/ST.DRT.Booking.API"
RUN dotnet build "ST.DRT.Booking.API.csproj" -c Release -o /app/build --verbosity n

[builder.log](https://github.com/NuGet/Home/files/8671117/builder.log)

**Comment by dominoFire** [comment]
@marnilss Could you please provide a sample project that shows your issues? Thanks!

**Comment by marnilss** [comment]
> @marnilss Could you please provide a sample project that shows your issues? Thanks!

Yes, finally managed to reproduce the problem. Vital for the reproduction is to use the following MSBuild properties (in addition to folder based feed in nuget.config file):
```
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
```
NOTE: I'm specifying these MSBuild properties in Directory.Build.props file, instead of the csproj file. But that has no impact of the issue, but is how I usually structure things for similarity between all csproj files in a solution.

Attached a zip-file with two batch-files (and two folders):
- Working sample: how it worked with previous version - Dockerfile specifies "mcr.microsoft.com/dotnet/sdk:6.0.202"
- Failing sample: Dockerfile specifies "mcr.microsoft.com/dotnet/sdk:6.0" and uses the same properties as above. Also tries to suppress warnings with `<WarningsNotAsErrors>1801;NU1801</WarningsNotAsErrors>` but with no success.

Otherwise the contents of the two folders are exactly the same.
[Nuget-issue-repro.zip](https://github.com/NuGet/Home/files/8682803/Nuget-issue-repro.zip)

**Comment by nkolev92** [comment]
@marnilss 

NU1801 is a warning, which is getting elevated to an error. 

Prior to the change in the latest version, we were not respecting NoWarn or TreatWarningsAsErrors for NU1801, but now we do. 
Can you try suppressing the warning?

**Comment by marnilss** [comment]
> @marnilss
> 
> NU1801 is a warning, which is getting elevated to an error.
> 
> Prior to the change in the latest version, we were not respecting NoWarn or TreatWarningsAsErrors for NU1801, but now we do. Can you try suppressing the warning?

**Breakthrough! (but now I think documentation is wrong)**

In the supplied failing sample I tried to suppress the warning/error, but failed, with this line:
`<WarningsNotAsErrors>1801;NU1801</WarningsNotAsErrors>`

BUT if I instead use the following line:
`<NoWarn>@(NoWarn);NU1801</NoWarn>`
It now works and my build completes!

So for anyone wanting to know the working recipe of properties to use:
```
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Ignore our localfeedsource (%TEMP%\nugetfeed.local) when building in pipeline  -->
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <NoWarn>@(NoWarn);NU1801</NoWarn>
```

BUT: I then think the documentation on https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1301 is wrong!
NU1301 isn't a warning - it is an error since you can't suppress it with `<NoWarn>@(NoWarn);NU1301</NoWarn>`
It it truly was a warning, we would not need the property `RestoreIgnoreFailedSources` anymore, and the following would suffice (but it doesn't - it fails with compile error NU1301)
```
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>@(NoWarn);NU1301</NoWarn>
```

**Comment by nkolev92** [comment]
`WarningsNotAsErrors` is not supported in NuGet, https://github.com/NuGet/Home/issues/5375, only NoWarn is. 

> BUT: I then think the documentation on https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1301 is wrong!

The title is wrong there. I'll get that fixed. 

For reference, in restore, anything ending with 0-499 is an error, anything ending with 500-999 is a warning :) 

> It it truly was a warning, we would not need the property RestoreIgnoreFailedSources anymore, and the following would suffice (but it doesn't - it fails with compile error NU1301)

Yep. 

The logic is: 

Source Fails -> RestoreIgnoreFailedSources == true ? NU1801 : NU1301

Trick is NU1801 can still be elevated to an error! 
Because of how we've arrived at this state, there's really no better way of doing it.

**Comment by nkolev92** [comment]
I created a fix for NU1301. https://github.com/NuGet/docs.microsoft.com-nuget/pull/2754

**Comment by nkolev92** [comment]
@marnilss 

I think this is resolved. I'm closing this issue now. Please let us know if you disagree.
