### ISSUE TITLE
[Feature]: Support for specific suffix after wildcard version using floating notation

### ISSUE THREAD

**Issue by a98c14** [NuGet/Home#11819]
### NuGet Product(s) Involved

MSBuild.exe, dotnet.exe

### The Elevator Pitch

Currently, NuGet package versions support floating notation, e.g `1.5.*-*`, `*-*`. However, it does not support a specific version suffix after a floating version like `1.5.*-beta`. I want to be able to always use the beta version despite whatever version number I am on for my package.

### Additional Context and Details

Here is the error message you get when you try to use the `1.8.*-beta` notation.

```
 error : '1.8.*-beta' is not a valid version string.
```

**Comment by nkolev92** [comment]
@a98c14 

Would `1.5.*-beta*` work for you? 

[Example](https://nugettools.azurewebsites.net/6.0.0/parse-version-range?versionRange=1.5.*-beta*)

**Comment by a98c14** [comment]
I actually didn't try it like that at all, my bad. It works perfectly for us. Thanks a lot 👍

Also, very nice tool, I didn't know that existed either.

**Comment by a98c14** [comment]
~~Just a quick question regarding `1.5.*-beta*`. Let's say I have `1.5.3-charlie` and `1.5.3-beta` available, it wouldn't match `charlie` if I have `1.5.*-beta*` in my version, right?~~

Nevermind, tested with best version tool and it doesn't match charlie if I have beta. Thank you for your help again

[Example](https://nugettools.azurewebsites.net/6.0.0/find-best-version-match?versionRange=1.5.*-beta*&versions=1.5.3-beta%0D%0A1.5.4-beta%0D%0A1.5.5-alpha%0D%0A1.5.6-charlie%0D%0A1.5.7%0D%0A1.5.8-beta)

**Comment by nkolev92** [comment]
Glad you found the tool helpful. 

Consider upvoting https://github.com/NuGet/NuGetGallery/issues/7828, which covers adding this tool to the nuget.org website directly.
