### ISSUE TITLE
[Bug]: NuGet should show in the Task Status Center instead of the status bar

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#11814]
### NuGet Product Used

Other/NA

### Product Version

Visual Studio 2022 Version 17.3.0 Preview 2.0 [32509.446.main]

### Worked before?

No

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Open a solution in Visual Studio.

Expected result:

NuGet restore progress shows in the Task Status Center.

Actual result:

NuGet restore progress does not show.
NuGet logs verbose messages to the status bar, which is not intended for showing the progress of background operations.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/9396. 

We attempted this change a while back, but on build restore tends to be super quick and the task status center would often display a popup even though restore has completed by the time the popup is shown. 

Maybe we need to consider different behavior for on build vs solution load restore? 
After all, is on build a background task in the same style that solution load tasks are?

**Comment by sharwell** [comment]
> Maybe we need to consider different behavior for on build vs solution load restore?

Yes. Restore on Build shows in the build output window, so it doesn't need to show in the task status center or status bar. Only restore operations _not_ tied to a build need to show separately.

**Comment by nkolev92** [comment]
Closing as dup. 

I'll leave a comment in the other issue.
