### ISSUE TITLE
Can't upgrade packages on a per-solution basis

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#1182]
I will never want to use different version of the same package in the same solution.
For this reason, I expect nuget allows me to upgrade the packages starting from the "Manage NuGet Packages for Solution..." screen as it was possible with VS2013 client.

Currently, when I open the packages for the solution, there is no way to upgrade the packages:
![image](https://cloud.githubusercontent.com/assets/5183152/9273886/f766df9e-4290-11e5-81d2-c0c510206887.png)

**Comment by yishaigalatzer** [comment]
Change the Action to Update

**Comment by raffaeler** [comment]
There is no 'Update' option available as you can see from this new screenshot:
![image](https://cloud.githubusercontent.com/assets/5183152/9275491/b6a95eac-429d-11e5-8ffc-895e57944290.png)

Please note that I didn't any package change from days but now one of the projects has the checkbox marked while the previous screenshot of this morning has not.

**Comment by yishaigalatzer** [comment]
@raffaeler - Thanks for the update, I want to look into it and see if this is something that can be done in the immediate milestone, or requires bigger changes than we can fit.

@feiling please take a look and lets discuss today.

**Comment by feiling** [comment]
@raffaeler from the screenshot, I can see you're using an older version of nuget. Please install the latest version. Then you can see action "Consolidate", which is exactly what you need.

![image](https://cloud.githubusercontent.com/assets/2679220/9367922/3e9d1d32-4675-11e5-9edf-ef159aad681d.png)

**Comment by RanjiniM** [comment]
Verified that Consolidate is working now

**Comment by raffaeler** [comment]
@feiling @RanjiniM The version of the screenshot and that I am still using is 3.1.60724.766.
I regularly receive extension updates, but this is the latest proposed by VS2015.
What should I do? Should I upgrade the extension manually? How?
