### ISSUE TITLE
Incompatible change to NuGet package resolution

### ISSUE THREAD

**Issue by Zastai** [NuGet/Home#11823]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

6.0.300 / 17.2

### Worked before?

6.0.20x / 17.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We have a company nuget server (using Nexus), which hosts not only our own packages, but also any versions of third-party packages that have been allowlisted (so no nuget.org access).

We only target version 4.7.2 (or very occasionally 4.8) of the .NET framework, and our builds are set up to reference `microsoft.netframework.referenceassemblies` 1.0.0 to ensure that works everywhere.

Previous NuGet resolution only pulled in `microsoft.netframework.referenceassemblies` itself, plus `microsoft.netframework.referenceassemblies.net472` and/or `microsoft.netframework.referenceassemblies.net48`, matching what we target.

However, the same projects now fail to restore with the 6.0.300 SDK that comes with VS2022 17.2:

```
error NU1101: Unable to find package Microsoft.NETFramework.ReferenceAssemblies.net461. No packages exist with this id in source(s): <company feed>
```

(And the project in question does NOT target `net461`.)
This feels like a pretty significant regression.

### To Reproduce
- set up a feed containing only `microsoft.netframework.referenceassemblies` and its `net472` and `net48` sub-packages
- create a project targeting `net472` or `net48` (plus optionally something else, like `netstandard2.1`)
- add a package reference to `microsoft.netframework.referenceassemblies`
- run `dotnet restore`

**Comment by nkolev92** [comment]
Hey @Zastai,

What you are seeing is a change in 6.2, https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.2#summary-whats-new-in-62, best described in https://github.com/NuGet/Samples/tree/main/AssetTargetFallbackTransitiveDependencies. 

The tldr is when `AssetTargetFallback` was being used before, the dependencies weren't being downloaded. 

Because you have `microsoft.netframework.referenceassemblies` as a dependency in a `.NET Standard` project you were effectively installed microsoft.netframework.referenceassemblies and because the fallback was incorrectly not considered you were never getting the dependencies that were going to be seen as incompatible. 

The solution here for you is to conditionally include the PackageReference microsoft.netframework.referenceassemblies and not include it for .NET Standard. 

Let me know if that works for you.

**Comment by Zastai** [comment]
I wish there was more care taken with introducing breaking changes in point releases...

Now I'll need to add a conditional, one something that has no "nice" variable to test, because AFAIK there is no property set to the "class" of target specified by `$(TargetFramework)` (something with a value like "netfx", "netstandard", "netcore").

I'll have to hope that something like `$(TargetFramework.StartsWith('net4'))` is going to be sufficient and futureproof (well, until we hit NET 40.0 in 2055 anyway). That does resolve the issue for now though (but then, so would refreshing our nuget server using a nuget client that has this behaviour).

**Comment by nkolev92** [comment]
Consider using the MSBuild property functions instead: 

https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-targetframework-and-targetplatform-functions

You might be able to condition on the TargetFrameworkIdentifier as well. 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFrameworkIdentifier)' == '.NETFramework' ">
    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup Condition=" $([MSBuild]::IsTargetFrameworkCompatible('netstandard2.0', '$(TargetFramework)'))">
    <PackageReference Include="NuGet.Common" Version="5.8.0" />
  </ItemGroup>

</Project>
```

here's the dotnet list package of the above project:

```
C:\Code\Temp\Conditional [master +0 ~1 -0 !]> dotnet list package
Project 'Conditional' has the following package references
   [net472]:
   Top-level Package      Requested   Resolved
   > Newtonsoft.Json      9.0.1       9.0.1

   [netstandard2.0]:
   Top-level Package             Requested   Resolved
   > NETStandard.Library   (A)   [2.0.3, )   2.0.3
   > NuGet.Common                5.8.0       5.8.0

(A) : Auto-referenced package.
```
