### ISSUE TITLE
[Bug]: PackageReader.CanVerifySignedPackages(SignedPackageVerifierSettings) result  is always true in the maui.android

### ISSUE THREAD

**Issue by yiszza** [NuGet/Home#11839]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Protocol-v6.2.0

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Maybe the problem in the `RuntimeEnvironmentHelper.IsMono`, `RuntimeEnvironmentHelper.IsMono` should return true, but in the Maui.android, `RuntimeEnvironmentHelper.IsMono` return false

**Comment by heng-liu** [comment]
Hi @yiszza , thanks for taking time filing this issue.
May I know your os and platform?
And how about `RuntimeEnvironmentHelper.IsWindows`, `RuntimeEnvironmentHelper.IsMacOSX` and `RuntimeEnvironmentHelper.IsLinux`? 
BTW, may I know what are you going to use this API CanVerifySignedPackages for? Thanks!

**Comment by yiszza** [comment]
> Hi @yiszza , thanks for taking time filing this issue.
> May I know your os and platform?
> And how about `RuntimeEnvironmentHelper.IsWindows`, `RuntimeEnvironmentHelper.IsMacOSX` and `RuntimeEnvironmentHelper.IsLinux`? 
> BTW, may I know what are you going to use this API CanVerifySignedPackages for? Thanks! 

net6-android31.0

**Comment by zivkan** [comment]
Team triage meeting:  Our team's focus is on nuget.exe, dotnet cli and VS, but we're happy to take contributions for NuGet SDK improvements.

**Comment by NaattyD** [comment]
> ### NuGet Product Used
> 
> NuGet SDK
> ### Product Version
> 
> NuGet.Protocol-v6.2.0
> ### Worked before?
> 
> _No response_
> ### Impact
> 
> It bothers me. A fix would be nice
> ### Repro Steps & Context
> 
> Maybe the problem in the `RuntimeEnvironmentHelper.IsMono`, `RuntimeEnvironmentHelper.IsMono` should return true, but in the Maui.android, `RuntimeEnvironmentHelper.IsMono` return false
> ### Verbose Logs
> 
> _No response_
