### ISSUE TITLE
[Feature]: Allow specifying a package source for a PackageReference in the csproj

### ISSUE THREAD

**Issue by GNUGradyn** [NuGet/Home#11837]
### NuGet Product(s) Involved

MSBuild.exe, dotnet.exe

### The Elevator Pitch

Say your company has a nuget package on their private nuget repository called `VeryGood.Package`, and an unrelated package also exists by the same name on nuget.org. This is not a problem when working on the project locally in visual studio, because the Nuget Package Manager tab will show both when you search and you can just click the one provided by your company.

However, when building the project via the dotnet CLI, this creates a problem. If the csproj contains the following package reference
```yml
<PackageReference Include="VeryGood.Package" Version="1.1.0" />
```
this is ambiguous between the one on nuget.org and the private repository. This is problematic for automated builds in Azure Devops for an example.

I propose a `Source` option be added to `PackageReference` to determine where the package should come from.

Example PackageReference:
```yml
<PackageReference Include="VeryGood.Package" Version="1.1.0" Source="PrivateNuget"/>
```

Example nuget.config:
```yml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="PrivateNuget" value="https://pkgs.dev.azure.com/TheVeryGoodCompany/_packaging/TheVeryGoodCompanyNuget/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

**Comment by heng-liu** [comment]
Hi @GNUGradyn , we implemented package source mapping feature last year. 
Do you think that solve this problem? Thanks!

The doc is https://github.com/NuGet/Home/blob/dev/implemented/2021/PackageSourceMapping.md
and https://devblogs.microsoft.com/nuget/introducing-package-source-mapping/

**Comment by GNUGradyn** [comment]
Yes, this is perfect. thank you

**Comment by heng-liu** [comment]
Close as fixed.
