### ISSUE TITLE
How to create a NuGet package for a tool built in .net, to be used in a native C++ project

### ISSUE THREAD

**Issue by asklar** [NuGet/Home#11843]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

.net 5

### Impact

I'm unable to use this version

### Repro Steps & Context

I am writing a tool in .net and need to create a nuget package from it. This tool / nupkg is to be used from native C++ projects.
So the target framework for the tool itself is something like net5.0, whereas I need the nupkg to package the tool into tools/native.
I haven't found a way to do this; I am using `<PackAsTool>true</PackAsTool>` to get the system to pack it under tools, but that uses the TFM of the tool itself as if it is the TFM of the project that will reference the tool nuget. 
So I would need something like `<PackageTargetFramework>native</PackageTargetFramework>` but that doesn't exist, it would seem.

**Comment by jeffkl** [comment]
@asklar The folder that .NET tools is packaged under is necessary for them to work correctly.  When the tool is installed, its placed under a folder that matches its runtime and that version is used when the tool is executed.  `native` is not a valid runtime for .NET so I don't think this will work.  If you want to build a package that can be referenced by a project then placing the stuff under `native` would be fine.  Can you clarify if you're trying to create a .NET tool package or a normal NuGet package that you want to reference from a project?

**Comment by asklar** [comment]
hi @jeffkl !
The idea is to ship a nuget package that will be referenced by C++ apps. The nuget package will contain a tool, which happens to be written in .net 5. The nuget package has props/targets that add some Target that runs this tool during the app's project's build.

I'm therefore looking for guidance for the best way to produce such a nuget package from a .net 5+ C# project. Setting the PackAsTool prop will produce "almost the right thing", in that it puts the tool inside a tools\ folder, but the package is still marked as only consumable by .net 5 projects, and in my case only C++ projects will consume it.
Any ideas on what the best way to do this is? I could write my own nuspec, but a) that's cumbersome, and b) it's kind of tricky to get all the right files, since the .net tool will copy a bunch of DLLs to my tool's output that are dotnet core DLLs from the framework itself, etc.

**Comment by jeffkl** [comment]
Okay thanks for clarifying.  Support for native tooling in NuGet is limited as its really designed for packaging up dependencies for managed projects.

You can accomplish this manually with the following logic:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);GetCustomPackageFiles</TargetsForTfmSpecificContentInPackage>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>
  <Target Name="GetCustomPackageFiles">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(TargetDir)*"
                              Exclude="$(TargetDir)*.pdb"
                              Pack="true"
                              PackagePath="tools/native" />
    </ItemGroup>
  </Target>
</Project>
```

1. The `IncludeBuildOutput` property set to `false` disables the built-in packing of the project's outputs
2. The `TargetsForTfmSpecificContentInPackage` property can be used to inject a target that runs to add items to the package
3. The `GetCustomPackageFiles` target is then adding every file in the output directory to the `TfmSpecificPackageFile` item group with the package path of `tools/native`.
4. The `SuppressDependenciesWhenPacking` property suppresses dependencies so that the package will work with any framework.

![image](https://user-images.githubusercontent.com/17556515/171279380-0e4d3def-34b3-4d8a-89be-aa696b873471.png)

**Comment by asklar** [comment]
awesome I'll give this a try later today/tomorrow :) thanks for your help!

**Comment by asklar** [comment]
confirming that this worked great :) Thanks for the help @jeffkl, I wouldn't have figured it out alone :)

**Comment by jeffkl** [comment]
Great, glad to help!
