### ISSUE TITLE
How to include nuget lib's dll.config into my project's output binary folder?

### ISSUE THREAD

**Issue by zhangyazhong** [NuGet/Home#11841]
I have an SDK style C# project "HelloWorld" whose .csproj is like below
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ABCLibrary" Version="1.0.0" />
  </ItemGroup>
</Project>
```
The `ABCLibrary` files in my local nuget cache are under
`C:\Users\MyUsername\.nuget\packages\abclibrary.retail-amd64\1.0.0\lib\net472` and have such files:
- ABCLibrary.dll
- ABCLibrary.dll.config

When I build my project "HelloWorld", the output binary folder only has `ABCLibrary.dll` but no `ABCLibrary.dll.config`. But the dll depends on some settings in the config so I get exceptions.

An optional solution is to add the following in my "HelloWorld.csproj":

```
<ItemGroup>
  <None Include="$(NuGetPackageRoot)\abclibrary.retail-amd64\1.0.0\lib\$(TargetFramework)\ABCLibrary.dll.config">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </None>
</ItemGroup>
```

But it's too ugly and troublesome. Is there a better way to include `ABCLibrary.dll.config` into the binary folder?

**Comment by jeffkl** [comment]
Please do the following to add an App.config to your package for a class library:
1. Add an `App.config` to your project by right clicking the project and selecting File -> Add -> New Item...
![image](https://user-images.githubusercontent.com/17556515/171916846-35602191-d8b5-4d2f-949b-db66f0b5a587.png)
1. Tell the .NET SDK that you want the `App.config` to be [included in the build output](https://github.com/dotnet/msbuild/blob/a2df02e6af1ed33882f36932ac2111cc98591dff/src/Tasks/Microsoft.Common.CurrentVersion.targets#L6086) for a class library (its only on by default for EXEs)
    ```xml
    <PropertyGroup>
        <AddAppConfigToBuildOutputs>true</AddAppConfigToBuildOutputs>
    </PropertyGroup>
    ```

3.  Tell NuGet that you want `.config` files from the build output to be included in the package:
    ```xml
    <PropertyGroup>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.config</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>
    ```

Full example:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AddAppConfigToBuildOutputs>true</AddAppConfigToBuildOutputs>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.config</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/17556515/171916570-b1e18d5f-becf-4756-a520-58e97be393a8.png)

Feel free to re-open if that doesn't work for you.
