### ISSUE TITLE
[DOCS] Need to document setting up a nuget gallery vs. nuget.server

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1184]
_from @johncmckim_ #456 

As a follow up to the Nuget Gallery comment, if that's what we are supposed to be using, why is there no mention of it in the nuget documentation http://docs.nuget.org/create/hosting-your-own-nuget-feeds. I assume that many many people wanting to host their own feeds are following that guide and using the Nuget.Server package. I would be happy to use the Gallery project instead if it supports an Authentication system that I can hook into my LDAP server, but there's no mention of it in the docs as an option at all.

_My feedback_
@johncmckim I'm missing one bit of feedback.

The report from @martinsuchan talks about project.json scenarios. It is understood and we are tracking a fix.

I manage to connect to the feed and download the packages through VS2015 UI (though they are not applicable to NET452 projects they download fine).

So I still don't know if there is any other scenario broken here other than the one tracked at - #1158

@martinsuchan - Yes I wasn't aware it was (sorry relatively new to the team, I checked last night and yet it is supposed to work).

@johncmckim - Here is the difference between NuGet Gallery and nuget.server. Both support authentication, the former is more complicated to install, but provides a lot more features.

_NuGet.Server_
Works off the list of files on disk, becomes very inefficient to startup and find packages when the number of packages grows (above a few hundreds its going to start crawling)

Intended for small projects with a few packages. Mostly allows decoupling from using a fileshare, locking files and access over Http where fileshare access is not available.

_NuGet Gallery_

More of a mirror of the nuget.org V2 site, with a database behind the scenes and a lot more available features.

Here is one of the blogs I found on how to set it up with authentication. This might not be the most up to date one.
http://blogs.msmvps.com/p3net/2013/01/06/setting-up-a-private-nuget-repository/

You are right that the docs do not point to the nuget gallery solution, or go into the details above. I'll make sure that happens.

**Comment by maartenba** [comment]
So the idea is to document setting up NuGetGallery in docs?

**Comment by yishaigalatzer** [comment]
Yeah, and how to set up authentication. I did make a basic change to the docs to point to the gallery wiki.

Walk through the new doc, if you think its enough close the issue, otherwise add/update

**Comment by maartenba** [comment]
Looks good to me. The ecosystem page contains a few OSS entries as well where all sorts of auth are possible.
