### ISSUE TITLE
List -AllVersions displays packages too many times

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1185]
AllVersions outputs the package, and then all versions of the package (for each version of a package)

Below, c:\testpak has the packages testpackage0.1.0.0, testpackage0.1.0.1, and testpackage1.1.0.0

nuget list -Source "c:\testpak" -AllVersions
testpackage0 1.0.0
testpackage0 1.0.0
testpackage0 1.0.1
testpackage0 1.0.1
testpackage0 1.0.0
testpackage0 1.0.1
testpackage1 1.0.0
testpackage1 1.0.0

**Comment by deepakaravindr** [comment]
Fixed with NuGet/NuGet3@334a1cd and https://github.com/NuGet/NuGet.PackageManagement/commit/7d76fca64714e02b935c76592419afbb68dd8f45
