### ISSUE TITLE
[Feature]: nuget.exe uninstall command

### ISSUE THREAD

**Issue by MsdnUsrSince1994** [NuGet/Home#11850]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

nuget.exe has an install command but no uninstall command.  This is an obvious oversight and quite annoying when needed.
This is especially important when nuget.exe has been run outside any project, thus making the installed packages unavailable to commands that can only be run in a project context.

### Additional Context and Details

Running "nuget.exe install packagename" outside any project installs the package under the current directory where the user happens to run the command.  Such packages don't appear in the output of PowerShell Get-Package, and there is no easily found information on how to list or remove packages installed that way.

If this installation method is unintended and removed in a future nuget.exe version, users will still need a tool to uninstall those things.

**Comment by zivkan** [comment]
@MsdnUsrSince1994 `nuget.exe install` just downloads and unzips the package, but it doesn't make any other modifications (for example, the `tools/install.ps1` is not run outside of VS). Therefore, "uninstall" is just deleting the package folder, which you can do with your shell.
