### ISSUE TITLE
NuGet restore exits with code 0 errorlevel when packages not found

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1186]
**Failing to restore a package incorrectly returns 0:**
C:\Users\zarenner>nuget restore -PackagesDirectory %temp%
Restoring NuGet package SomePackageThatDoesntExist.100.0.0.
WARNING: Unable to find version '100.0.0' of package 'SomePackageThatDoesntExist'.
Unable to find version '100.0.0' of package 'SomePackageThatDoesntExist'.

C:\Users\zarenner>echo %errorlevel%
0

**Other failures correctly return 1:**
C:\Users\zarenner>nuget restore sdfdsf
Could not find a part of the path 'C:\Users\zarenner\sdfdsf'.

C:\Users\zarenner>echo %errorlevel%
1

**Comment by yishaigalatzer** [comment]
@zarenner what version of nuget.exe are you reporting this?

**Comment by zarenner** [comment]
@yishaigalatzer Repros in latest dev.
