### ISSUE TITLE
[Bug]: nuget.exe doesn't support signatures compressed with deflate method

### ISSUE THREAD

**Issue by Inok** [NuGet/Home#11861]
### NuGet Product Used

NuGet.exe

### Product Version

6.2.0

### Repro Steps & Context

We have a local NuGet feed (ProGet) to both store our private packages and move public libraries from nuget.org to our feed.

Somehow, we are getting packages in our internal feed with signature files compressed using the "deflate" method. When we copy .nupkg files from nuget.org to our feed, they are valid. However, for some reason, after some time we are starting to get errors like the following when we are restoring packages from our feed:
```
C:\Nuget\nuget.exe verify -All .\Microsoft.AspNetCore.Http.Features.2.1.1.nupkg

Verifying Microsoft.AspNetCore.Http.Features.2.1.1
...\Microsoft.AspNetCore.Http.Features.2.1.1.nupkg

Finished with 1 errors and 0 warnings.
NU3005: The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).
```

It turns out that in a valid .nupkg file, the signature file is not compressed. And in an invalid package, the signature file is compressed using Deflate method.
![valid-invalid](https://user-images.githubusercontent.com/7262311/172415815-338320bc-5116-4e38-9c67-eaa5ae22b53f.png)

Both signatures, if extracted (unzipped) from the package, are binary equal (you can also see the same CRC on the screenshot). So the problem is that for some reason NuGet does not support signatures compressed with deflate method.

We don't realize yet how it is possible that our package feed "repackages" packages and compresses their signatures, but it seems that nuget.exe should support such signatures since they have a perfectly valid compression method in terms of ZIP file format.

Example of a "broken" package:
[Microsoft.AspNetCore.Http.Features.2.1.1.nupkg.zip](https://github.com/NuGet/Home/files/8854398/Microsoft.AspNetCore.Http.Features.2.1.1.nupkg.zip)

**Comment by nkolev92** [comment]
Hey @Inok 

According to the spec: https://github.com/NuGet/Home/wiki/Package-Signatures-Technical-Details#-the-package-signature-file, the signature file most not be compressed.

NuGet is asserting that the compression method needs to be 0, so the file is expected to not be compressed. Code reference: https://github.com/NuGet/NuGet.Client/blob/9c469e4dbfa8ba6085f0cd47d58207de90304a5a/src/NuGet.Core/NuGet.Packaging/Signing/Archive/SignedPackageArchiveIOUtility.cs#L461

Can you please reach out to ProGet to understand how/why the package is getting repackaged.

**Comment by Inok** [comment]
So this is by design... Ok, got it!
Now I'm curious why the signature needs to be not compressed... May I ask what's the reason behind that?

Also, I've already reported the issue to ProGet, and it seems that it's also not the one to blame.

So now I'm closing the issue, and I will reopen it if it turns out that "NuGet" itself is somehow related to the issue.
Thank you!

**Comment by nkolev92** [comment]
I wasn't part of the design team at that time so I can't really tell you why it was left as uncompressed.
