### ISSUE TITLE
[Bug]: Double loading status indicators sometimes shown in PMUI

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#11864]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.3.0 Preview 3.0 [32609.364.main]

### Worked before?

Yes, unknown

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Create a new C# Class Library project.
2. Open PMUI for Solution.
3. On the Installed tab (opened by default, which may be important to repro), there are 2 indicators for "no packages found".
![image](https://user-images.githubusercontent.com/49205731/173136214-08404aea-17e8-4375-b14c-f3462cae0786.png)

Note that the visual tree shows multiple loading indicators:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/49205731/173136349-37b701d3-c578-43b0-a4fe-4fc8957be63f.png)

One suspected cause is that recent changes to async loading logic and/or for grouping of the packages list could be allowing 2 additions of the `LoadingStatusIndicator` to the packages list.

**Comment by nkolev92** [comment]
Adding a regression during current release as it's almost certainly related to the changes for showing transitive dependency.

**Comment by jeffkl** [comment]
Team Triage: Closing as stale, if anyone reproduces the issue we can re-open it
