### ISSUE TITLE
Using JsonTextWriter manually in LockFileFormat

### ISSUE THREAD

**Issue by mjolka** [NuGet/Home#11870]
The current implementation of `LockFileFormat.Write` creates a `JObject` that is then written to a `JsonTextWriter`.

Replacing this implementation with one that uses [`JsonTextWriter` manually](https://www.newtonsoft.com/json/help/html/Performance.htm#ManuallySerialize) shows a good improvement in object allocations.

### OrchardCore

  | Objects (M) | Total Size (GB) | Objects % | Total Size %
-- | -- | -- | -- | --
Before (cd24c74) | 24.35 | 1.31 |  N/A |  N/A
After | 21.72 | 1.12 | 89.20% | 85.50%

### SanitisedNet471

  | Objects (M) | Total Size (GB) | Objects % | Total Size %
-- | -- | -- | -- | --
Before (cd24c74) | 53.32 | 2.72 | N/A  | N/A
After | 48.62 | 2.38 | 91.19% | 87.50% 

Is this a change you would be interested in taking?

`LockFileFormat.Read` could similarly be replaced with a manual use of `JsonTextReader`, but I wanted to see if there was any interest in this type of change before going too far down this path.

**Comment by zivkan** [comment]
@mjolka yes, that would be fantastic.  With so much work, doing this ourselves had just never been prioritized.

We eventually should get rid of all `JObject` thoughout our codebase, although I believe that will cause some public API breaking changes in NuGet.Protocol.  However, for the assets file and packages lock file, it should be fine, and will benefit scenarios where no network calls are made, but no-op restore fails.

Note that for `LockFileFormat.Read`, I believe that [NuGet.BuildTasks](https://github.com/dotnet/NuGet.BuildTasks) for non-SDK style project, and the .NET SDK for SDK style projects, they both use `LockFIleFormat.Read`, so improvements will also benefit builds with no-op restores.
