### ISSUE TITLE
Nuget does not find the latest listed version of a package on VS2015

### ISSUE THREAD

**Issue by kdelmonte** [NuGet/Home#1188]

**Comment by emgarten** [comment]
Would you provide some repro steps for this? What package are you seeing this issue with?

**Comment by kdelmonte** [comment]
The package is called DataFile and it is my own package. When I push a new version and wait until the site says it is available to download, the Visual Studio package manager console does not find the new version. If I install the package using the command line utility, it finds it right away.

**Comment by yishaigalatzer** [comment]
Look like it does. 0.0.9 is the latest listed, 1.0.0 - through 1.1.3 are not

![image](https://cloud.githubusercontent.com/assets/1238711/9343749/aa66e7f4-45b8-11e5-847c-af201c999d5e.png)

**Comment by yishaigalatzer** [comment]
Please reopen if you still see this issue after your packages are listed.
