### ISSUE TITLE
[Bug]: The error “An error occurred while retrieving package metadata for ‘microsoft.entityframeworkcore.design’ from source ‘http://api.nuget.org/v3/registration5-gz-semver2/’” occurred when switching to “Browse” tab in PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11880]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.87

### Worked before?

Dev\6.3.0.81

### Impact

It bothers me. A fix would be nice

## Steps to reproduce:
1. Create a C# Console App (.Net Core) project.
2. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open PM UI.
3. Click “Browse” tab and observe. 

## Expected:
No error occurred and the packages showed in the package list correctly.
 
## Actual: 
The error “An error occurred while retrieving package metadata for ‘microsoft.entityframeworkcore.design’ from source ‘http://api.nuget.org/v3/registration5-gz-semver2/’” occurred as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/173547059-a62d64c2-e289-4b82-9224-c55daa98db18.png)

## Note:
1. This issue not repro on Dev\6.3.0.81.

**Comment by joelverhagen** [comment]
Hello, thanks you for taking the time to report this. This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/9140. We'll use that one issue to track the NuGet.org availability issue that users experienced last night.
