### ISSUE TITLE
[Bug]: NuGet Server API reterns right link only for lowercase packages  

### ISSUE THREAD

**Issue by Nataliia5722** [NuGet/Home#11897]
### NuGet Product Used

Other/NA

### Product Version

NuGet V3 API

### Repro Steps & Context

If the package name is **18.3.4-f-DTE-23727-0002** then the link will be formed like https://artifactory.***.***.com/artifactory/api/nuget/v3/***/registration/***/page/18.3.4-f-dte-23727-0002/18.3.4-f-dte-24705-in-0001.json
And as result, the link will not work as it's looking for package **18.3.4-f-dte-23727-0002**, not for **18.3.4-f-DTE-23727-0002** and response will be 
```
{
"count": 0,
"lower": "18.3.4-f-dte-23727-0002",
"parent": "https://artifactory.***.***.com/artifactory/api/nuget/v3/***/registration/***/index.json",
"upper": "18.3.4-f-dte-24705-in-0001",
"items": [],
"@id": "https://artifactory.dev.intapp.com/artifactory/api/nuget/v3/***/registration/***/page/18.3.4-f-dte-23727-0002/18.3.4-f-dte-24705-in-0001.json"
}
```
but must return result something like this: 
```
{
"count": 9,
"lower": "18.3.4-f-DTE-23727-0002",
"parent": "https://artifactory.***.***.com/artifactory/api/nuget/v3/***/registration/***/index.json",
"upper": "18.3.4-f-dte-24705-in-0001",
"items": [<9_ITEMS_HERE_TRUNCATED>],
"@id": "https://artifactory.***.***/artifactory/api/nuget/v3/***/registration/***/page/18.3.4-f-DTE-23727-0002/18.3.4-f-dte-24705-in-0001.json"
}
```
It does not work only if **lower** element has an upper case letter, for **upper** element it works anyway

**Comment by nkolev92** [comment]
For the V3 protocol, the links are supposed to be lowercase: https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#request-parameters
