### ISSUE TITLE
GlobalJsonReader breaking change

### ISSUE THREAD

**Issue by deryaza** [NuGet/Home#11893]
Now it looks from solutionpath property, which is breaking. Before it would look down from project dir.

https://github.com/NuGet/NuGet.Client/blob/e9637ed865687c2153da78c6c6385f010277329c/src/NuGet.Core/Microsoft.Build.NuGetSdkResolver/GlobalJsonReader.cs#L44

**Comment by jeffkl** [comment]
Duplicate of https://github.com/NuGet/Home/issues/11747

The change was made intentionally to make the NuGet-based MSBuild project SDK resolver have the same behavior as the .NET SDK resolver.  More details here: https://github.com/NuGet/Home/issues/11747#issuecomment-1099315888
