### ISSUE TITLE
[Bug]: [Client policy]There is an error NU3034 “Package 'Microsoft.AspNet.Razor 3.2.9' from source 'https://api.nuget.org/v3/index.json': This package is signed but not by a trusted signer.” occurs when installing “Microsoft.AspNet.Mvc” package in PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11891]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.3.0.90

### Impact

It bothers me. A fix would be nice

## Repro steps:  
1. Create a Console App (.Net Framework) project and close VS. 
2. Add required mode in nuget.config file with trusted signers list and repository:
```
<config>
     <add key="signatureValidationMode" value="require" />
  </config>
  <trustedSigners>
      <repository name="nuget.org" serviceIndex="https://api.nuget.org/v3/index.json">
          <certificate fingerprint="0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
          <owners>Microsoft;aspnet</owners>
      </repository >
     <author name="Microsoft">
          <certificate fingerprint="0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```

3. Reload the solution, right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI.
4. Click settings button (top-right of right panel), check “Allow format selection on first package install” in General tab and click OK.
5. Go to “Browse” tab, search “Microsoft.AspNet.Mvc” package and click install button, check “Packages.config” and click OK.

## Expected: 
There is no error and the “Microsoft.AspNet.Mvc” package is installed successfully. 

## Actual: 
There is an error NU3034 “Package 'Microsoft.AspNet.Razor 3.2.9' from source 'https://api.nuget.org/v3/index.json': This package is signed but not by a trusted signer.” occurs as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/174045495-b7bab7ff-1065-4014-976a-40619b451afc.png)

**Comment by kartheekp-ms** [comment]
@v-crchang - I am able to reproduce this issue. However, the SHA256 hashes that are mentioned in the issue description are incorrect.

I downloaded the package and executed `dotnet nuget verify` from a different folder
```
C:\Users\source\repos>dotnet nuget verify ""C:\Users\Downloads\microsoft.aspnet.razor.3.2.9.nupkg""

Verifying Microsoft.AspNet.Razor.3.2.9

Signature type: Author
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA256 hash: AA12DA22A49BCE7D5C1AE64CC1F3D892F150DA76140F210ABD2CBFFCA2C18A27
  Valid from: 9/29/2020 5:00:00 PM to 10/5/2023 5:00:00 AM

Signature type: Repository
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Valid from: 2/15/2021 4:00:00 PM to 5/15/2024 4:59:59 PM

```
Executing `dotnet nuget verify` command from another folder that has the `nuget.config` mentioned in the issue description failed with `NU3034` error.

```
C:\Users\source\repos\Repro11891>dotnet nuget verify "C:\Users\Downloads\microsoft.aspnet.razor.3.2.9.nupkg"

Verifying Microsoft.AspNet.Razor.3.2.9

Signature type: Author
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA256 hash: AA12DA22A49BCE7D5C1AE64CC1F3D892F150DA76140F210ABD2CBFFCA2C18A27
  Valid from: 9/29/2020 5:00:00 PM to 10/5/2023 5:00:00 AM

Signature type: Repository
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Valid from: 2/15/2021 4:00:00 PM to 5/15/2024 4:59:59 PM

error: NU3034: This package is signed but not by a trusted signer.

Package signature validation failed.
```
After fixing the fingerprint hashes in the config file, I reloaded solution in the VS and then installed the package successfully.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <config>
     <add key="signatureValidationMode" value="require" />
  </config>
  <trustedSigners>
      <repository name="nuget.org" serviceIndex="https://api.nuget.org/v3/index.json">
          <certificate fingerprint="5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
          <owners>Microsoft;aspnet</owners>
      </repository >
     <author name="Microsoft">
          <certificate fingerprint="5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
</configuration>

```

<img width="1896" alt="image" src="https://user-images.githubusercontent.com/52756182/175432473-49d6c2bb-70cb-4447-a157-0165c6aa26f0.png">

**Comment by zivkan** [comment]
For more background information: https://devblogs.microsoft.com/nuget/the-nuget-org-repository-signing-certificate-will-be-updated-as-soon-as-march-15th-2021/

Certificates have a limited lifetime, and the one nuget.org uses will change every time it expires. Old packages won't be re-signed, so the list of certificates that need to be trusted, to trust all versions of packages, will keep growing forever

**Comment by v-crchang** [comment]
@kartheekp-ms Got it, thanks.
