### ISSUE TITLE
[Bug]: dotnet pack on a net6.0-windows (or net6.0-windows7.0) TargetFramework generates a package targetting net6.0

### ISSUE THREAD

**Issue by thatnerdyguy** [NuGet/Home#11894]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 6.0.203

### Worked before?

Unsure

### Impact

It's more difficult to complete my work

### Repro Steps & Context

(I could just be fundamentally misunderstanding something about nuget packaging here, but...)

Example csproj: [WinFormsControlLibrary1.zip](https://github.com/NuGet/Home/files/8930962/WinFormsControlLibrary1.zip)

1. In a new WinForms control library csproj, set TargetFramework to net6.0-windows7.0
2. dotnet pack
3. Take a look inside the nupkg created, and in it's nuspec see the targetFramework is set to net6.0, not anything indicating it requires windows/winforms

**Comment by zivkan** [comment]
Thank you for providing the sample. I see it's using [NuGetizer](https://www.nuget.org/packages/NuGetizer), which as you can see on nuget.org, is not owned by Microsoft or the NuGet team. The NuGetizer package metadata says that the project website is https://github.com/devlooped/nugetizer.

If I comment out the `PackageReference` to NuGetizer and try pack again, I see then that the package now contains files under `lib/net6.0-windows7.0/` and contains a dependency group for the same TFM.
