### ISSUE TITLE
[Bug]: The “Update” button is still clickable after installing a package-the latest version with “Packages.config” format in PM UI 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11907]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.3.0.104

### Repro Steps & Context

Repro steps: 
1. Create a new Console App (.Net Framework) project.
2. Right-click the project and open Manage NuGet Packages in Solution Explorer.
3. Install a package-the latest version (e.g. Newtonsoft.Json 13.0.1) with “Packages.config” format into the project.
4. Observe the information of the package in the right panel.

Expected:
The “Update” button is non-clickable.

Actual:
The “Update” button is still clickable after installing a package-the latest version with “Packages.config” format in PM UI as below screenshot.
 
![image](https://user-images.githubusercontent.com/40230425/174979792-1d85128e-1585-45d6-b837-dd060fbd6770.png)

Note:
1. The issue does not repro on installing package-the latest version with “Package Reference” format.
2. The issue does not repro on .Net Core template project.
3. The issue starts from Dev\6.3.0.96.

**Comment by nkolev92** [comment]
@v-longmin 

Please don't add the priority label. Triage usually handles that.

**Comment by v-longmin** [comment]
OK, got it, thanks.
