### ISSUE TITLE
Provide solution for NuGet Error NU1012 - the pack error does not call out the problem files

### ISSUE THREAD

**Issue by RussKie** [NuGet/Home#11905]
![image](https://user-images.githubusercontent.com/4403806/174542009-4b643688-0a31-4642-92b2-1ff04d8c8e0c.png)

How do you specify the platform?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a877e2f5-e92f-3db9-77de-ae6c958b3736
* Version Independent ID: a877e2f5-e92f-3db9-77de-ae6c958b3736
* Content: [NuGet Error NU1012](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1012)
* Content Source: [docs/reference/errors-and-warnings/NU1012.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1012.md)
* Product: **nuget**
* GitHub Login: @nkolev92
* Microsoft Alias: **nikolev**

**Comment by nkolev92** [comment]
You need to specify the platform version. It all depends on what your exact scenario is. 

Normally the SDK handles it by setting the correct `TargetPlatformMoniker` that's usually inferred from the `TargetFramework` value.

**Comment by RussKie** [comment]
It'd be great to have some examples.

I'm porting https://github.com/dotnet/winforms-datavisualization to .NET 6 and getting NU1012 running `.\build.cmd -pack`, and I have no idea what's wrong:
```
C:\Program Files\dotnet\sdk\6.0.301\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU1012: Some included files are included under TFMs which are missing a platform version: net6.0-windows
```



Here's a binlog: [Build.binlog.zip](https://github.com/NuGet/docs.microsoft.com-nuget/files/8946190/Build.binlog.zip)

**Comment by nkolev92** [comment]
Honestly that seems like a product bug. 

The pack error message should point out the files, not just the framework.

**Comment by danjagnow** [comment]
Looks like the relevant code is in the [ValidateFileFrameworks](https://github.com/NuGet/NuGet.Client/blob/ee9ef1f0e1a256a6d215669256576320a02fb0ac/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L804-L861) method of `PackageBuilder`.  The last bit of that method throws the NU1012 error:

```cs
if (frameworksMissingPlatformVersion.Any())
{
    throw new PackagingException(NuGetLogCode.NU1012, string.Format(CultureInfo.CurrentCulture, Strings.MissingTargetPlatformVersionsFromIncludedFiles, string.Join(", ", frameworksMissingPlatformVersion.OrderBy(str => str))));
}
```

There are some unit tests for the class in [PackageBuilderTest](https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.Tests/NuGet.Packaging.Test/PackageBuilderTest.cs).

**Comment by kirsan31** [comment]
Sorry for bumping it, but any one know how to deal with original error?
I have a packege (like this https://github.com/kirsan31/winforms-datavisualization/blob/DesignerTest/src/System.Windows.Forms.DataVisualization.Package/DataVisualization.Package.csproj) and it works with .net6, but when I change target framework to .net6-windows, I see this error:

> Error NU1012 Some included files are included under TFMs which are missing a platform version: net6.0-windows

**Comment by jzabroski** [comment]
It's unclear from this original issue if the problem was triggered via `dotnet pack` or `nuget.exe pack`. I am getting this with `nuget.exe 6.14` while trying to pack a legacy "Tools" nupkg directory to pack the content into (although it seems very likely to me this issue has been around for a very long time). It seems like NU1012 should not report an error if there is no output items to copy into lib.
