### ISSUE TITLE
[Feature]: optional local package sources

### ISSUE THREAD

**Issue by Rabadash8820** [NuGet/Home#11909]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

Allow optional package sources, i.e., sources that don't cause restore errors when missing. This would greatly improve local library development.

### Additional Context and Details

I regularly find myself working with multiple .NET libraries that reference each other as NuGet packages. When one of those libraries is in development, I often want to test it out in a dependent project on the same machine. Rather than updating the package references in the dependent project, I can just add a `NuGet.Config` to it with a `packageSource` for the local, work-in-progress library. That way, when I build the library, it generates a new .nupkg locally, which my dependent projects pick up with their custom package source.

Unfortunately, if somebody clones the dependent project repo and _not_ the library project, this causes NuGet restore to fail. The error is typically `Index was outside the bounds of the array` after displaying the config files in use, or  `error NU1301: The local source '...' doesn't exist.` This occurs whether I use `packageSources` or `fallbackFolderPackages` sections in my NuGet.Configs, and occurs for all NuGet clients (hence my selection above). It would be great to have some way of telling NuGet "use the package from this local source; if the source isn't there, just get it from the next source".

**Comment by kartheekp-ms** [comment]
How about using [`dotnet restore --ignore-failed-sources`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore#options)?

**Comment by Rabadash8820** [comment]
Wow, yep, definitely was not aware of that option. Setting it [as an MSBuild property](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restore-properties) is even better. Thanks for the suggestion!

**Comment by chipplyman** [comment]
I would sure love to have some sources that are required where restore will fail if they are missing, and some sources that are optional where restore will not fail if they are missing.

**Comment by Rabadash8820** [comment]
@chipplyman I like that suggestion, but you'll probably have more luck just opening a new Issue
