### ISSUE TITLE
[Bug]: Timestamps of files of unpacked package are shifted by the timezone (reopen/related issue 7395?)

### ISSUE THREAD

**Issue by valentinmarkus** [NuGet/Home#11904]
### NuGet Product Used

NuGet.exe

### Product Version

Nuget 6.2

### Worked before?

5.10 (fixed in 5.10, but again existing in 6.2)

### Impact

It's more difficult to complete my work

### Repro Steps & Context

This bug was already fixed in [Nuget 5.10](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.10) [(Bug 7395)](https://github.com/NuGet/Home/issues/7395), but is still/again existing in 6.2 and maybe other 6.x Versions.

Repro:
- Install Nuget-Package to a VisualStudio .net-Framework Test-Project, e.g. install this: [Microsoft.SqlServer.Compact](https://www.nuget.org/packages/Microsoft.SqlServer.Compact/4.0.8876.1) 
- Download same Nuget-Package from Nuget.org, [Microsoft.SqlServer.Compact](https://www.nuget.org/packages/Microsoft.SqlServer.Compact/4.0.8876.1) and unpack it in file-explorer
- Compare timestamps of containing Dlls -> **Timeshift** (in my case 2h, because I'm located in Germany, which is UTC+2)
![Capture](https://user-images.githubusercontent.com/48953170/174782361-f13848cf-ce01-47a5-84bd-8b999248e538.PNG)

This is especially annoying if you build nuget packages yourself from newly created dlls (deployed on a private nuget-source). Because when you install such a package, the dlls are in my case 2h younger than the last build. This causes the project for which the package was installed (and all dependent projects) to be rebuilt each time. This increases the development time enormously!

Note: 
The timestamp within the nupkg (unzipped in file-explorer) is correct
The timestamp of the installed nupkg (installed using vs 2022.2.4) is wrong/shifted

**Comment by kartheekp-ms** [comment]
I guess you are experiencing this issue because the package was already published before the issue was fixed in 5.10. 
https://github.com/NuGet/Home/issues/7395#issuecomment-770073687

The package version linked in the issue description https://www.nuget.org/packages/Microsoft.SqlServer.Compact/4.0.8876.1 was published in 2012.

**Comment by valentinmarkus** [comment]
Hi,

no, this issue is not only present for packages published before the issue was fixed in 5.10 (below is another example, with a newer package). As I wrote in my initial post, this problem also exists with newly (self-)created packages. Actually, this bug is mainly a problem with recently (self-)created packages because (as stated in my initial post): 

> Because when you install such a package, the dlls are in my case 2h younger than the last build. This causes the project for which the package was installed (and all dependent projects) to be rebuilt each time. This increases the development time enormously!

Here is another example with a fairly new package: [System.Memory 4.5.5](https://www.nuget.org/packages/System.Memory/4.5.5), published in 2022, May.

The package then shows up like this:
![Capture](https://user-images.githubusercontent.com/48953170/175869864-d49c9c71-f822-4ef4-9fc4-8f41aa6fa3a9.PNG)

**Comment by zivkan** [comment]
@valentinmarkus In [a comment in issue 7395](https://github.com/NuGet/Home/issues/7395#issuecomment-763852659), that you linked to, I explained that the zip file format doesn't provide room for timezone. Hence both the app creating zip files and extraction zip files need to make decisions about which timezone to use. The intention is that NuGet converts the local file timestamp to UTC when creating the nupkg, and then convert from the nupkg's UTC time to the machine local time when extracting.

Following the fix of #7395, are you sure the difference isn't just that NuGet is treating the zip timestamp as UTC and converting to local, whereas the non-NuGet way you extract the zip file assumes the time is local?

To me, the most important question is if someone uses NuGet to pack a nupkg, and then extract, will the time stay the same (considering timezones), even when the machine it was packed on has a different timezone than the machine it was extracted on. Some deployment tools (such as msdeploy) use file timestamp as the condition to determine whether or not the file needs to be replaced.

Also, we have [another duplicate](https://github.com/NuGet/Home/issues/5240) of this issue, so as per our [triage policy](https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md), if you (and others) upvote (👍) that issue, it will help us prioritize the issue sooner.

**Comment by valentinmarkus** [comment]
Thank you very much for your comment, it makes me understand the overall context much better than before.

The fact, or rather my realization, that Nuget.exe converts the timestamps from local-time to UTC when packing and from UTC back to local-time when unpacking was extremely helpful in further analyzing the problem.

And the result of further analysis is the following:
For unpacking/installing nuget packages on development machines, we use VS2022 (nuget 6.2). For packing nuget packages (the packages are packed in various CI-chains on other machines), we also use nuget 6.2, but unfortunately there seem to be a few exceptions. At least in one CI-chain we use an outdated nuget version (older than 5.10).
This outdated version obviously does not change the timestamp from local-time to UTC when packing. When unpacking/installing such a package with nuget 6.2, the "wrong" (local-time) timestamp is interpreted as UTC and converted to local-time. With the result that the timestamp is "in the future".

So all in all it can be said:
**It is NOT a bug in nuget 6.2**, but unfortunately in some cases we use outdated nuget versions to pack nuget packages. It is obviously a self-made problem.

**I apologize for the false alarm.**

> To me, the most important question is if someone uses NuGet to pack a nupkg, and then extract, will the time stay the same (considering timezones), even when the machine it was packed on has a different timezone than the machine it was extracted on. Some deployment tools (such as msdeploy) use file timestamp as the condition to determine whether or not the file needs to be replaced.

Unfortunately, I can't answer this question, or rather, I can't recreate the scenario described, since I don't have access to a machine in a different time zone.
