### ISSUE TITLE
Files aren't added to VS if they exist before installing a package

### ISSUE THREAD

**Issue by dandriscoll** [NuGet/Home#1190]
If you install a package and one of its files already exists on disk, NuGet does not add the file to VS. This can easily happen if you reset your source code after installing a package.

Example repro for mustache.js:
1) Install mustache.js
2) Reset all source code for your project (leaving Scripts\mustache.js on disk)
3) Reopen solution
4) Install mustache.js
5) Notice that Scripts\mustache.js is on disk but not added to your project

**Comment by nkolev92** [comment]
Thank you filing this issue. 
At this point we are prioritizing other issues, so we will not be addressing this.
