### ISSUE TITLE
[DCR]: Make error NU5104 more informative

### ISSUE THREAD

**Issue by IanKemp** [NuGet/Home#11911]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

When attempting to create a package from a project that depends on a prerelease version of another package, error NU5104 is thrown with the following message:

> A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Upstream.Dependency [1.0.0-pre, )" or update the version field in the nuspec.

### Desired Behavior

The error message should be updated to explain how to override it:

> A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Upstream.Dependency [1.0.0-pre, )", update the version field in the nuspec<b>, or specify the -AllowPrereleaseDependencies option.</b>

**Comment by kartheekp-ms** [comment]
@IanKemp - https://docs.microsoft.com/nuget/create-packages/prerelease-packages doc has more information about building pre-release packages. https://docs.microsoft.com/nuget/create-packages/package-authoring-best-practices has more information about Package authoring best practices.

I don't see `AllowPrereleaseDependencies` as an option for [NuGet.exe pack](https://docs.microsoft.com/nuget/reference/cli-reference/cli-ref-pack) and [dotnet.exe pack](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack). Are you proposing to add `AllowPrereleaseDependencies` option for pack command?

**Comment by erdembayar** [comment]
@IanKemp 
You can override the warning for pre-release dependency if you want pre-release dependency. Please use last stable sdk, [support added](https://github.com/NuGet/NuGet.Client/pull/4369) in Jan 2022.
```
  <ItemGroup>
    <PackageReference Include="Upstream.Dependency" Version="[1.0.0-pre, )" NoWarn="NU5104" />
  </ItemGroup>
```
