### ISSUE TITLE
[DCR]: Allow disabling preview feature log

### ISSUE THREAD

**Issue by aelij** [NuGet/Home#11921]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

The log `The project {0} is using CentralPackageVersionManagement, a NuGet preview feature.` always appears and it's written for every restored project, creating a lot of noise in large solutions.

### Desired Behavior

Either:
- Allow disabling this log, e.g. by adding a flag to disable preview notices
- Set the log level to `Normal` instead of `Mininal`

**Comment by aelij** [comment]
Incidentally the [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/central-package-management) doesn't mention anything about this being a preview, probably should fix that too.

**Comment by jeffkl** [comment]
Duplicate of https://github.com/NuGet/Home/issues/11724.  We will be removing this message.
