### ISSUE TITLE
[Feature]: Make migrating from `packages.config` to `PackageReference` scriptable

### ISSUE THREAD

**Issue by astrohart** [NuGet/Home#11924]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console

### The Elevator Pitch

Make the process of migrating projects from `packages.config` to `PackageReference` easily scriptable.   Perhaps, add a `nuget CLI`, `dotnet CLI`, and/or **Package Manager Console** cmdlet (or perhaps all three) in order to enable this.

### Additional Context and Details

I am using primarily .NET Framework 4.8 in my projects, per customer requirements.  They requested me to not upgrade to .NET Core yet, until their product is at a certain stage of development.  Currently, all my projects rely on `packages.config`.  I've been approved to migrate them all to `PackageReference` but, it seems rather impractical at the moment.

Currently, migration is a manual process, wherein one needs to right-click a context menu item, `Migrate packages.config to PackageReference...`, [per this doc](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference) on the specific project to be migrated).  

My solutions typically have 100+ projects, and I have about 25-50 solutions on my dev machine.  

Doing this as a manual process for each project, by hand, one at a time, by right-clicking a context menu for each would, in my mind, be quite an undertaking.

Having a `nuget CLI command` or `dotnet CLI command` or a cmdlet in the **Package Manager Console** window of Visual Studio would give me a way to script this process -- iterate over all my project files and ... brrrrpp! ... migration is done!

**Comment by erdembayar** [comment]
Fyi: I have seen community created tool, but I didn't test it, we're not affiliated with it. https://github.com/MarkKharitonov/NuGetPCToPRMigrator

**Comment by nkolev92** [comment]
Team triage: 
Both nuget.exe and dotnet.exe do not have sufficient information to successfully migrate the projects to PackageReference (ex. scripts, assembly adds to the project).

Bulk migration using Visual Studio is covered in  https://github.com/NuGet/Home/issues/5879. 
Please upvote that issue.

**Comment by astrohart** [comment]
> Team triage: Both nuget.exe and dotnet.exe do not have sufficient information to successfully migrate the projects to PackageReference (ex. scripts, assembly adds to the project).

How so?  I mean, what is the blocker per se?  Can't you use System.IO and other file-access APIs to just straight up, iterate the project tree, read the files for the correct info, and then implement the changes to `dotnet.exe` and `nuget.exe`?  

For those of us with 200+ projects in our solutions, using a script with the CLI activity would, in my mind, greatly improve my productivity as a developer.

**Comment by jeffkl** [comment]
@astrohart unfortunately it is a lot more complicated than one might think.  You can try a tool I wrote a while back: https://github.com/jeffkl/PackagesConfigConverter

**Comment by astrohart** [comment]
@jeffkl Thanks I will check it out

that being said, the preference would be to rely on standard, Microsoft-maintained tooling for my NuGet needs :-)
