### ISSUE TITLE
[Bug]: Visual Studio Package Manager Console EFCore Tools not working

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11932]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

17.2.5

### Repro Steps & Context

https://developercommunity.visualstudio.com/t/Visual-Studio-Package-Manager-Console-EF/10079780

**Comment by donnie-msft** [comment]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1559710

**Comment by aortiz-msft** [comment]
Closing as dupe of https://github.com/dotnet/efcore/issues/28407
