### ISSUE TITLE
How can I  programmatically obtain the NU errors

### ISSUE THREAD

**Issue by Smartisa** [NuGet/Home#11939]
### Discussed in https://github.com/NuGet/Home/discussions/11938

<div type='discussions-op-text'>

<sup>Originally posted by **Smartisa** July  3, 2022</sup>
I can check the "project assets. json" file to get the log, but how can I  programmatically obtain the NU errors?
![image](https://user-images.githubusercontent.com/47079990/177030593-99a9fde4-ff16-49ca-a80a-0a988613df04.png)
</div>

**Comment by nkolev92** [comment]
What's the context in which you're trying to obtain these errors?

Build scripts? MSBuild tasks? Visual Studio extension?

**Comment by Smartisa** [comment]
> What's the context in which you're trying to obtain these errors?
> 
> Build scripts? MSBuild tasks? Visual Studio extension?

Visual Studio extension，How can I obtain the NU errors programmatically instead of parsing the "project.assets.json" file?

**Comment by nkolev92** [comment]
That's not really possible today. 

NuGet in Visual Studio has a limited surface area. 

The only APIs available for extensions to use are the ones in NuGet.VisualStudio and NuGet.VisualStudio.Contracts and are documented here: https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio. 

The assets file is a build intermediary that is probably best not relied on as it's something that changes as NuGet and the SDK see fit for build purposes. 

If you don't mind me asking, what would you be using the warning/error codes for?
