### ISSUE TITLE
Please delete nuget from codeplex

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#1194]
search engines still resolve doco there as the top result. You are doing your consumers a disservice by leaving out of date information live.

**Comment by SimonCropp** [comment]
or better yet apply the appropriate redirects to all the urls on codeplex

**Comment by yishaigalatzer** [comment]
@SimonCropp we discussed this in the team for quite some time, unfortunately there is rich history there that we don't want to shutdown completely.

There is no good way to lock the site down, codeplex just doesn't support it but every single page in the site including the title says that we moved and where to go.

We might eventually be able to do that in the future, or when the codeplex team enables some sort of a lockdown feature.

Unfortunately I'm going to close this for now, be assured that we keep in touch with the codeplex team, and once we can do more to lock things down we will.

**Comment by SimonCropp** [comment]
how about instead of a lock down you add a robots.txt noindex feature. that would at least fix the search engine problem

**Comment by yishaigalatzer** [comment]
Do you know if this can be done on codeplex? Couldn't find a way to control it. I did forward this thread to the codeplex team, I will do the same with this suggestion.

**Comment by SimonCropp** [comment]
no i dont believe it is possible. i was just hoping since nuget is run by MS and codeplex is run by MS.... :)
