### ISSUE TITLE
[Bug]: [Cross-platform Sign Verify] The expected error “NU3018: The author primary signature found a chain building issue: UntrustedRoot” disappeared after restoring the project with untrusted signing certificate on Linux

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11941]
### NuGet Product Used

NuGet.exe

### Product Version

Dev\6.3.0.120

### Impact

It bothers me. A fix would be nice

## Repro steps: 
1. Git clone https://github.com/NuGet/Entropy.git
2. Set the following parameters in “pathOnUnix.ps1” file:
a. The SDK channel must be: 6.0.4xx
b. The SDK version should be: latest
c. Add a -Quality/--quality argument with a value of: signed
3. Cd /home/jamie/Desktop/SDKPatchTool/ and type in command './patchOnUnix.ps1'
4. Create a new test certificate: `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile`
5. Sign a package: `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>`.
6. Launch Microsoft Management Console (mmc.exe)  
7. In Microsoft Management Console, navigate on the main menu to File|"Add/Romove Snap-in…"  
8. In the subsequent "Add or Remove Snap-ins" dialog, select Certificates in the left-hand list.  
9. Click the Add button.  
10. In the subsequent "Certificates snap-in" dialog, select "My user account."  
11. Click the Finish button.  
12. Click the OK button.  
13. In the left-hand tree pane navigate to "Console Root" | "Certificates - Current User" | "Trusted Root Certification Authorities" | Certificates.  
14. In the right-hand list pane, find the certificate that was created in step 4. The certificate "Issued To" will be "Test certificate for testing NuGet package signing" and the thumbprint will match.  
15. Right-click on the certificate and select Delete.  
16. Copy the signed package from the above Windows machine to Linux machine.
17. Create a project, add package reference in the .csproj file
```
<ItemGroup>
<PackageReference Include="<packageName>" Version="<packageVersion>" />
</ItemGroup>
```
18. Add the feed (path contains the signed package), set required mode in nuget.config file with trusted signers list:
```
<packageSources>
<add key="<anyname>" value="<signed package parent folder>" />
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
</packageSources>
<config>
<add key="signatureValidationMode" value="require" />
</config>
<trustedSigners>
<author name="JamieZhang">
<certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
</author>
</trustedSigners>
```
19. Clear the cache: `<patchedSDKPath>./dotnet nuget locals all –clear`.
20. Delete the <projectPath>/obj folder if there is any.
21. Go inside the project folder, verify the package by running restore: `<patchedSDKPath>./dotnet restore <projectpath>/<projectname>.csproj`

## Expected:
The expected error “NU3018: The author primary signature found a chain building issue: UntrustedRoot “ should show after restoring the project.

## Actual:
The expected error “NU3018: The author primary signature found a chain building issue: UntrustedRoot”  disappeared after restoring the project.
![image](https://user-images.githubusercontent.com/71433406/177311444-e98b76d7-201c-4a28-b371-a49c746340f6.png)

## Note
This is not a regression issue, because it is a new feature.

**Comment by dtivel** [comment]
This bug is confusing because in step 4 you create a certificate and in step 5 you sign a package with that certificate.  However, in step 17a you create a _new_ certificate and trust that certificate in steps 17f-h.  If I understand the test correctly --- wanting to verify a package signed with an untrusted certificate --- then you should skip step 17 in its entirety.  Step 17 trusts the certificate.

If you skip step 17 and leave the certificate untrusted on Linux, then the test will produce the error:  `error: NU3018: The author primary signature's signing certificate is not trusted by the trust provider.`

**Comment by v-crchang** [comment]
@dtivel Sorry for the confusing about the test steps. Yes, you are correct, the expected result NU3018 shows after skipping trusting the certificate. I updated the steps and closed this bug as "Not Repro".
