### ISSUE TITLE
release notes and blogs do not equate to documentation

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#1195]
Ok this has been going on for a long time and i think it needs to be called out as bad practice. 

Too often changes occur in nuget (often breaking changes) and while it is publicized in release notes and/or blogs the documentation is updated much later or never at all

Some recent examples

So this talks about dependencyversion
https://docs.nuget.org/release-notes/nuget-2.8#dependencyversion-attribute
But not this 
https://docs.nuget.org/consume/nuget-config-settings

This http://blog.nuget.org/20150729/Introducing-nuget-uwp.html
-talks about install.ps1/uninstall.ps1 being deprecated but this still says it is a supported feature http://docs.nuget.org/create/Creating-and-Publishing-a-Package
-talks about content delivery being deprecated but this still says it is a supported feature http://docs.nuget.org/Create/Enforced-Package-Conventions

Your definition of done should first favor updating the doco and then doing the marketing

**Comment by yishaigalatzer** [comment]
@SimonCropp very fair comment.

Also note that this is an open source project and you are more than welcome to PR.

**Comment by yishaigalatzer** [comment]
@csharpfritz ping, this is stuck in the 3.2 release and still haven't been addressed

**Comment by csharpfritz** [comment]
Updated in v3.3 docs

**Comment by SimonCropp** [comment]
@csharpfritz thanks

**Comment by SimonCropp** [comment]
I notice u olny linked one commit. Can u please also link the other commits that fix the several other examples i mentioned

**Comment by csharpfritz** [comment]
The other item about DependencyVersion was addressed in commit
NuGet/NuGetDocs#372

Jeff
