### ISSUE TITLE
[Bug]: Nuget Package Manager - source path with accentuated character messes with .NET Interactive #r directive

### ISSUE THREAD

**Issue by JDiLenarda** [NuGet/Home#11955]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

Visual studio 2019 (16.11.6) - Nuget Package Manager 5.11.0 - VSCode 1.69.0 - .NET Interactive notebooks v1.0.3314011 - F# Interactive version 11.4.2.0 pour F# 5.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

In the Visual Studio (2019 or 2022) Nuget package manager, add 2 sources :

C:\nuget\rihanna
C:\nuget\beyoncé

Create the underlying directories as well.

In Visual Studio Code :
- create a .NET Interactive Notebooks
- add a C# or F# code cell
- type #r "nuget: Newtonsoft.Json" and execute
You will get : `stdin(1,1): error FS3217: The source directory 'C:\Nuget\beyonc%EF%BF%BD' not found`

Notes :
- the package that is tried to be loaded is not supposed to be in any local source directory.
- you get the error even if the faulty source is unticked in the package manager. The only workaround is to remove it.

The problem also occurs in F# Interactive as I reported a few months back: https://github.com/dotnet/fsharp/issues/12401. I only realized yesterday it occurs in .NET Interactive.

**Comment by erdembayar** [comment]
@JDiLenarda 
Thank you for filing this issue. Could you elaborate more?
Which extension did you install for Visual Studio Code .NET Interactive Notebooks? How did you create it?

**Comment by JDiLenarda** [comment]
@erdembayar : current version is .NET Interactive Notebooks for VS Code v1.0.3357010 (it's been updated this week end but the problem stands still)

**Comment by erdembayar** [comment]
> @erdembayar : current version is .NET Interactive Notebooks for VS Code v1.0.3357010 (it's been updated this week end but the problem stands still)

I'm not sure if `.NET Interactive Notebooks for VS Code` uses nuget.client component, probably it's not. Did you try to create issues in their repo first?

**Comment by JDiLenarda** [comment]
At least, there is a weird side effect between the Visual Studio Nuget Package manager and the #r directive from both F# Interactive and .NET Interactive.

As I said, I filed an issue on the F# repo a few months back. Discovering it also occurs in the same way in .NET Interactive made me think Nuget Package Manager is the suspect.

I will nevertheless report this to .NET Interactive.

**Comment by zivkan** [comment]
Team triage meeting:  @JDiLenarda if you create a sub directory under `C:\nuget\beyoncé` and run `dotnet new console`, does `dotnet restore` fail?

**Comment by JDiLenarda** [comment]
> Team triage meeting: @JDiLenarda if you create a sub directory under `C:\nuget\beyoncé` and run `dotnet new console`, does `dotnet restore` fail?

Currently on holiday far from my office PC, I will only be able to test this next Wednesday. Thank you.

**Comment by JDiLenarda** [comment]
> Team triage meeting: @JDiLenarda if you create a sub directory under `C:\nuget\beyoncé` and run `dotnet new console`, does `dotnet restore` fail?

I've just tried this, `dotnet restore` does not fail.

**Comment by zivkan** [comment]
Thank you for letting us know. Since NuGet itself supports directories with non-ASCII characters, I suggest that it appears that whatever product you're using is passing bad data into NuGet. You've already mentioned that you would report this to that product, so I'm going to close this as there is nothing actionable for the NuGet team at this time.
