### ISSUE TITLE
[Bug]: [Cross-platform Dotnet Nuget Sign] Unexpected errors/warnings show after verifying the package on Linux & Mac 

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#11969]
### NuGet Product Used

NuGet.exe

### Product Version

Release-6.3.x\6.3.0.128

### Impact

It bothers me. A fix would be nice

## Repro steps: 
1. Git clone https://github.com/NuGet/Entropy.git and download nupkgs-NonRTM from [Pipelines - Run 6.3.0.128 artifacts (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D6406259%26view%3Dartifacts%26pathAsName%3Dfalse%26type%3DpublishedArtifacts&data=05%7C01%7Cv-crchang%40microsoft.com%7C8617a23fa1734bdda39508da658564c0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637933920882569737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jCIj8DCuL2Fwm5SPvhOPEZ15o0vzlGLBBtGXDJZVXj0%3D&reserved=0) on Windows.
2. Set the following parameters in “pathOnUnix.ps1” file:
    a. The SDK channel must be: 6.0.4xx
    b. The SDK version should be:  latest
    c. Add a -Quality/--quality argument with a value of: signed
    d. $patchSDKFolder = "/home/jamie/Desktop/PatchedSDK" 
    e. $nupkgsPath = "/home/jamie/Desktop/Nupkgs" 
3. Cd /home/nuget/Desktop/SDKPatchTool/ (under Entropy folder in step1) and run command './patchOnUnix.ps1'
4. Go to ...\Entropy\TestCertGenerator and create a new test certificate: `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` 
5. Copy the .pfx file (Generated in step4) from the above Windows machine to Linux machine.
6. Trusted Certificate:
    a. Open a Terminal window and execute:
        `openssl pkcs12 -in <PfxFilePath> -out <PemFilePath> -nokeys`
        When prompted, enter the PFX password.
    b. Open the PEM file created in step a.
    c. Copy the entire block labelled with BEGIN CERTIFICATE/END CERTIFICATE:
-----BEGIN CERTIFICATE-----
…
-----END CERTIFICATE-----

    d. In the versioned directory of your patched .NET SDK open ./trustedroots/codesignctl.pem.
    e. At the end of the file on a new blank line, paste the copied certificate in PEM format.
    f. Save the file.
7. Go to the patchedSDK folder and run `./dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath>  --certificate-password password -v n`
8. Verify the correct certificate was used and no errors or warnings (except for warning NU3002 if you didn't use: "--timestamper").
9. Verify the package was signed: ` ./dotnet nuget verify <PackageFilePath> -v d `

## Expected:
No error/warning shows after verifying the package since signature verification is disabled by default.

## Actual:
Unexpected errors/warnings show after verifying the package as below.

PS /home/jamie/Desktop/patchSDK>  ./dotnet nuget verify /home/jamie/Desktop/SignPackage/Package1.1.0.0.nupkg -v d
X.509 certificate chain validation will use the fallback certificate bundle at '/home/jamie/Desktop/patchSDK/sdk/6.0.400-preview.22330.6/trustedroots/codesignctl.pem'.

Verifying Package1.1.0.0
/home/jamie/Desktop/SignPackage/Package1.1.0.0.nupkg
Signature Hash Algorithm: SHA256

Signature type: Author
Verifying the author primary signature with certificate: 
  Subject Name: CN=Test certificate for testing NuGet package signing
  SHA1 hash: B6437C3ED42AC5DA5E235E7B8212445EB7A0E8D2
  SHA256 hash: E60BC3B63F655FA5B7B0586533F787D887FD03B7E3777FF6BB136024E4DC0A22
  Issued by: CN=Test certificate for testing NuGet package signing
  Valid from: 07/14/2022 06:31:00 to 07/15/2022 06:31:00

Finished with 0 errors and 1 warnings.
warn : NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired.

Package signature validation failed.
PS /home/jamie/Desktop/patchSDK>

## Notes:
1. This issue also reproes on MacOS.
2. The error/warning (expected on Windows only) in every test case of Cross-platform Dotnet NuGet Sign Test reproes.
3. This is not a regression issue, because it is a new feature change.

**Comment by dtivel** [comment]
Hmm, this does not repro for me.  I overwrote the signature on NuGet.Common 5.0.0, and it verified successfully.

```text
dtivel@dtiveldebian11:~/Desktop$ ./patchSDK/dotnet nuget verify ./nuget.common.5.0.0.nupkg -v d
X.509 certificate chain validation will use the fallback certificate bundle at '/home/dtivel/Desktop/patchSDK/sdk/6.0.400-preview.22330.6/trustedroots/codesignctl.pem'.

Verifying NuGet.Common.6.2.1
/home/dtivel/Desktop/./nuget.common.5.0.0.nupkg
Signature Hash Algorithm: SHA256

Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=Test certificate for testing NuGet package signing
  SHA1 hash: 63ABB78AC11D3754ADB5C777E5569EF28D6A3D0A
  SHA256 hash: 4B529214A66CB2255AB50DEE97143C92DA4B4D6ECA341B73FEE57D3D326BD33C
  Issued by: CN=Test certificate for testing NuGet package signing
  Valid from: 07/14/2022 12:43:39 to 07/15/2022 12:43:39

Finished with 0 errors and 1 warnings.
warn : NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired.

Successfully verified package 'NuGet.Common.6.2.1'.
```

@v-crchang, can you please send me your package that fails to verify successfully?

**Comment by v-crchang** [comment]
@dtivel The package I'm using that fails to verify is: [Package1.1.0.0.nupkg.zip](https://github.com/NuGet/Home/files/9117219/Package1.1.0.0.nupkg.zip)

**Comment by dtivel** [comment]
@v-crchang, I tried verifying your package but it fails because the signature is now expired.  So, I created a new test certificate, re-signed the package and verified.  It succeeded with the same warning (NU3027).

Can you please meticulously repeat the test and update the repro steps with every detail?  Include every command you run, the operating system and version, and output of each of the following commands:

* `dotnet --info`
* `uname --all`
* `export`

**Comment by v-crchang** [comment]
@dtivel  I updated the repro steps above. 
And the dotnet --info:
![image](https://user-images.githubusercontent.com/71433406/179484766-9b7a888c-5896-4f90-97b5-c52d646dadf7.png)
uname --all:
Linux Linux 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
export:
![image](https://user-images.githubusercontent.com/71433406/179484577-c0020a10-bfff-466e-a1d6-fbc13bfeca2c.png)

**Comment by nkolev92** [comment]
Team triage:

@v-crchang 

Closing as by design for now, please reactivate if there's anything else you need from us.
