### ISSUE TITLE
[Bug]: [Cross-platform sign Verify] Unexpected error/warning show after restoring the project on Mac

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#11966]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Release-6.3.x\6.3.0.128

## Repro steps: 
1. Git clone[ https://github.com/NuGet/Entropy.git]( https://github.com/NuGet/Entropy.git)
2. Set the following parameters in “pathOnUnix.ps1” file:
    a. The SDK channel must be: 6.0.4xx
    b. The SDK version should be:  latest
    c. Add a -Quality/--quality argument with a value of: signed
3. Cd /home/nuget/Desktop/SDKPatchTool/ and type in command './patchOnUnix.ps1'
4. Create a new test certificate: `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority  -Password password -NotAfter "<30 minutes in the future from current local time>"  -GenerateCerFile  `
5. Sign a package: `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>` .
6. Copy the .pfx file and signed package from the above Windows machine to Mac machine.
7. Trusted Certificate:
    a. Open a Terminal window and execute:
      `  openssl pkcs12 -in <PfxFilePath> -out <PemFilePath> -nokeys`
        When prompted, enter the PFX password.
    b. Open the PEM file created in step 3.
c. Copy the entire block labelled with BEGIN CERTIFICATE/END CERTIFICATE:
-----BEGIN CERTIFICATE-----
…
-----END CERTIFICATE-----

d. In the versioned directory of your patched .NET SDK open ./trustedroots/codesignctl.pem.
    e. At the end of the file on a new blank line, paste the copied certificate in PEM format.
    f. Save the file.
8. Create a project, add package reference in the .csproj file
  ```
<ItemGroup>
    <PackageReference Include="<packageName>" Version="<packageVersion>" />
  </ItemGroup>
```
9. Add the feed (path contains the signed package), set required mode in nuget.config file with trusted signers list:
```
<packageSources>
      <add key="<anyname>" value="<signed package parent folder>" />
     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
   </packageSources>
   <config>
    <add key="signatureValidationMode" value="require" />
   </config>
  <trustedSigners>
     <author name="JamieZhang">       
         <certificate fingerprint="71E8D51A3B8725197292D8CBEC76AD998A8F13F461BE778D646494FBABD974C5D050" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```
10. Clear the cache: <patchedSDKPath>`./dotnet nuget locals all –clear`.
11. Delete the <projectPath>/obj folder if there is any.
12. Go inside the project folder, verify the package by running restore: `<patchedSDKPath>./dotnet restore <projectpath>/<projectname>.csproj
`
## Expected:
No error/warning shows after restoring the project since signature verification is disabled by default.

## Actual:
Unexpected error/warning show after restoring the project as below screenshot.
 
![image](https://user-images.githubusercontent.com/40230425/178719423-c302e1ba-f708-4e02-8242-c0ef4d894cab.png)

## Note:
We didn’t set the environment: 
export DOTNET_NUGET_SIGNATURE_VERIFICATION=true as below screenshot:
![image](https://user-images.githubusercontent.com/40230425/178719386-d2291bad-e62e-4231-8379-7fe7b87932d4.png)

**Comment by dtivel** [comment]
@v-longmin, I followed your steps and this bug did not repro.  Here's the output of the `verify` command on the package:

```text
Damons-MacBook-Pro:test dtivel$ ../patchSDK/dotnet nuget verify --all ../MyPeachPackage/bin/Debug/MyPeachPackage.1.0.0.nupkg 

Verifying MyPeachPackage.1.0.0

Signature type: Author
  Subject Name: CN=Test certificate for testing NuGet package signing
  SHA256 hash: A98A536A699E9B95E71A61B2608F408BB60D9C453E2F11BF9664052276B0FA3C
  Valid from: 7/13/2022 7:30:33 AM to 7/13/2022 7:40:00 AM

error: NU3018: The author primary signature's signing certificate is not trusted by the trust provider.
error: NU3037: The author primary signature validity period has expired.
warn : NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired.

Package signature validation failed.
```
Here is restore output:
```text
Damons-MacBook-Pro:test dtivel$ ../patchSDK/dotnet restore ./test.csproj 
  Determining projects to restore...
  Restored /Users/dtivel/Desktop/test/test.csproj (in 555 ms).
```

Can you please post your `<PatchedSDK>/dotnet --info` output?  Also, was your patching successful?

**Comment by dtivel** [comment]
@v-longmin, is it possible that you had the environment variable `DOTNET_NUGET_SIGNATURE_VERIFICATION` set to `true` before performing restore in your PowerShell session?

In a new Terminal window try this:

```text
pwsh
```

Then, in the PowerShell session, execute:

```PowerShell
$Env:DOTNET_NUGET_SIGNATURE_VERIFICATION='true'
Get-ChildItem Env:DOTNET_NUGET_SIGNATURE_VERIFICATION | Format-Table -AutoSize
```

I see that the environment variable is set as expected:

```PowerShell
Name                                Value
----                                ----
DOTNET_NUGET_SIGNATURE_VERIFICATION true
```

Now exit PowerShell:

```PowerShell
exit
```

Now you're back in a plain Bash shell.  Now execute:

```text
export
```

You'll see that the `DOTNET_NUGET_SIGNATURE_VERIFICATION` environment variable is no longer defined.  Environment variables defined in a PowerShell session are not propagated back to the outer Bash shell.

Looking at your 2 screenshots, I see that NuGet restore failed in a PowerShell session, but you listed environment variables after exiting the PowerShell session.  This only tells me that the `DOTNET_NUGET_SIGNATURE_VERIFICATION` environment variable wasn't defined _before_ starting the PowerShell session.  It leaves the possibility that the `DOTNET_NUGET_SIGNATURE_VERIFICATION` environment variable was defined _during_ the PowerShell session before you performed restore.  That would explain the restore failure.

**Comment by v-longmin** [comment]
Hi @dtivel, I patched SDK successfully, the dotnet info as below:
![image](https://user-images.githubusercontent.com/40230425/178916611-6592241b-3657-4230-bef4-013beedff03e.png)
After setting DOTNET_NUGET_SIGNATURE_VERIFICATION = false, unexpected error or warning was not repro as below screenshot:
![image](https://user-images.githubusercontent.com/40230425/178917497-5e0571f6-a359-4689-83be-b1fa09748626.png)

**Comment by dtivel** [comment]
Thanks for confirming, @v-longmin.

After patching, you should be still in a PowerShell session.  If you simply `exit` the PowerShell session, you'll return to your Bash session, and the `DOTNET_NUGET_SIGNATURE_VERIFICATION` environment variable should be unset.  The test should then pass without explicitly setting `DOTNET_NUGET_SIGNATURE_VERIFICATION` to anything.  The default is `false`.
