### ISSUE TITLE
DependencyVersion Highest is broken

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#1196]
Re this https://docs.nuget.org/release-notes/nuget-2.8#dependencyversion-attribute

If that setting worked it would mitigate it. Unfortunately i have never gotten that to work
My config  `C:\Users\simon\AppData\Roaming\NuGet\NuGet.Config`

has had this  for ages

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="DependencyVersion" value="Highest" />
  </config>
```

and from my nuget "dialog"

![2015-08-17 15_36_59-photos](https://cloud.githubusercontent.com/assets/122666/9298655/dfe1ee4c-44f5-11e5-9434-1cd5a06533b0.png)

so clearly this is not true

>  This value will also be respected by the NuGet Package Manager Dialog for any install package operations.

Also can this setting please be documented and not "just in the release notes"

**Comment by zhili1208** [comment]
checked this, the behavior respect the config setting but Nuget doesn't show the setting value on UI.
