### ISSUE TITLE
[Bug]: An error “unable to load the service index for source” occurs after making DevOps feed https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json enabled on Windows ARM64

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11965]
### Impact

It's more difficult to complete my work

### Describe the bug

An error “unable to load the service index for source” occurs after making DevOps feed https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json enable in PM UI

#### Details about Problem
VS Version: D17.3\32714.290
NuGet Version: Dev\6.3.0.123
System type: ARM-based 64bit processor
OS: Windows11 Pro 21H2

### Detailed repro steps
1. Create a C# Console App (.NET 6.0)/(.NET 7.0) in VS and open the PM UI of the solution. 
2. Add the DevOps feed (https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json) into the Settings->NuGet Package Manager->Package Sources. 
3. Select the new added DevOps feed in the Package source dropdown box in the PM UI. 

### Actual Result
An error “unable to load the service index for source” occurs after making DevOps feed https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json enable as below.

### Expected Behavior
There is no error after making DevOps feed https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json enable.

### Screenshots

![image](https://user-images.githubusercontent.com/20632625/178227294-3a1a7295-dec8-4bb6-8f19-47291a5b451b.png)

#### The error log
Unable to load the service index for source https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json.
  Response status code does not indicate success: 401 (Unauthorized).

**Comment by v-luzh** [comment]
We filed the bug on NuGetGallery since we thought it's a server issue. Please help to reroute if the area path is incorrect, thanks.

**Comment by dominoFire** [comment]
@v-luzh  I just checked the associated Azure DevOps feed. All vendor testing teams should have access.

Please let me know if you can access this page: https://dev.azure.com/farhub/repros/_artifacts/feed/farhub/connect/nuget.exe

![image](https://user-images.githubusercontent.com/1192347/178599958-1aefb8aa-5266-4c31-abd6-ce3c56b7b819.png)

**Comment by joelverhagen** [comment]
Moved to NuGet/Home for @dominoFire to interact with @v-luzh. Feel free to close if this is better off handled over email/Teams.

This issue is not related to NuGet.org availability. Azure DevOps feeds are outside of the scope of NuGet/NuGetGallery.

**Comment by v-luzh** [comment]
It doesn't repro on Main\32712.105 + NuGet Client Dev\6.4.0.10. I'm closing it now.

**Comment by v-luzh** [comment]
Repro on ARM64 VS D17.3\32714.290 with Surface Pro X. I am reopening it for tracking.

**Comment by nkolev92** [comment]
Team Triage:
Assigning to @zivkan for investigation.

**Comment by kartheekp-ms** [comment]
@zivkan - I am guessing if this issue is a duplicate of [another internal issue](https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1956144) assigned to the partner team.

**Comment by zivkan** [comment]
Emailed internally. This issue is no longer reproducing in internal builds.

Also note that NuGet gets Azure DevOps credentials from another service within VS, so it's worthwhile creating these credential failure issues in Azure DevOps, so we can reassign to the Credential Provider and VS Identity teams.
