### ISSUE TITLE
Apex tests should use timeout

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#11988]
A recent build had this in the log, until the job timed out:

> ##[warning]RunMessage : [xUnit.net 02:21:05.36] NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.IVsServicesTestCase.SimpleInstallFromIVsInstaller', Elapsed: 02:15:06

The test should not be allowed to run for 2 hours.

**Comment by nkolev92** [comment]
Are all of the Apex tests missing a timeout?

**Comment by zivkan** [comment]
I don't know.

I *think* some of the tests watch the Package Manage Output Window buffer for magic strings, and fail the test if the magic string is not found after a certain time. But maybe that's E2E tests.

Ideally all tests would have a timeout, yes, but the only evidence I have right now is that this API test is at risk of "deadlocking".

**Comment by zivkan** [comment]
We had another test with the same issue:

> [xUnit.net 02:06:06.20] NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.NuGetConsoleTestCase.DowngradePackageFromPMCForPCAsync', Elapsed: 02:00:22

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/5428, commit https://github.com/NuGet/NuGet.Client/commit/6a096d0504851db695bef483801a992d65262c64

Feel free to reopen if I'm wrong.
