### ISSUE TITLE
Installed version of a package is never displayed

### ISSUE THREAD

**Issue by ygoe** [NuGet/Home#1198]
This affects all packages, installed and upgradable. I never know what is currently installed and how large the jump for an upgrade is.

![nuget-installed-version-missing](https://cloud.githubusercontent.com/assets/868315/9303795/bfd55684-44e1-11e5-9419-3e0fecce5929.png)

**Comment by emgarten** [comment]
@dg9ngf please paste the contents of your packages.config file for this project

**Comment by yishaigalatzer** [comment]
Thanks for reporting, this was already fixed - The duplicate bug is https://github.com/NuGet/Home/issues/1061

**Comment by ygoe** [comment]
When will this fix be available in a release? I couldn't figure out how releases are done here. It looks broken even from the user end with missing release tags and release notes in the gallery and all that.

**Comment by yishaigalatzer** [comment]
The release is not out yet. It will be available here and in visual studio directly. We are still tweaking the release date but hopefully early Sep.

Releases are only drafted after the final commit is made, for now you can look at the milestone - https://github.com/NuGet/Home/milestones/3.2
