### ISSUE TITLE
Signing:  macOS removed CRL support

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#11985]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 5 SDK and later

### Impact

Other

### Repro Steps & Context

In March 2022, I confirmed with Apple developer technical support that Apple removed CRL support from macOS starting with 10.15 (Catalina).  See https://github.com/dtivel/x509-revocation-check-macos for repro steps.

NuGet packages that are author- or repository-signed with certificates without OCSP support will have permanently unavailable revocation status on macOS 10.15+.

Microsoft's current author-signing certificate and NuGet.org's current repository-signing certificate are both DigiCert certificates.  Publicly trusted, commercial code signing certificates typically have both CRL and OCSP support, so as long as OCSP checks continue to work, the lack of CRL support on macOS is a non-issue.

**Comment by nkolev92** [comment]
@dtivel Is there a proposal for an action that we're going to take on this?

**Comment by dtivel** [comment]
@nkolev92, no, not at this time.

**Comment by nkolev92** [comment]
Team Triage: Closing this for now. 
@dtivel please feel free to reopen if needed.
