### ISSUE TITLE
[Bug]: PackageReference is auto-discover an unlisted version.

### ISSUE THREAD

**Issue by ricaun** [NuGet/Home#11989]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 2022

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

In the `csproj` when using `PackageReference` usually set the version with `"*"` to use the latest version of the package.

Something like this:
```xml
<PackageReference Include="PropertyChanged.Fody" Version="*"/>
```

Works fine until I noticed the version is `4.0.0`, and the last release is `3.4.1`.

This means the package has an unlisted version `4.0.0`, confirmed by: https://www.nuget.org/packages/PropertyChanged.Fody/4.0.0

I'm not sure if this is the right behavior, should the `Version="*"` select unlisted/deprecated versions?

https://github.com/Fody/PropertyChanged/issues/867

**Comment by nkolev92** [comment]
That's expected behavior. https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#floating-version-resolutions.

**Comment by ricaun** [comment]
`Floating version resolution does not take into account whether or not a package is listed. Floating version resolution will be resolved locally if the conditions can be satisfied with packages in the Global Package Folder.`
It's a feature indeed.

**Comment by ltrzesniewski** [comment]
@nkolev92 what's the rationale behind this? Because resolving to a version which *should explicitly not be used* seems very wrong (or even dangerous) to me.

**Comment by nkolev92** [comment]
Package listedness affects discoverability in search. 

In PackageReference, packages are installed into a global packages folder where the concept of listedness is not relevant (after all a package may exist in multiple sources). 
By allowing already 'seen' versions to be used, it is likely to improve nbuild stability (ie package removal from consideration won't affect my build that already used this available package).

**Comment by ltrzesniewski** [comment]
I see. That's unfortunate. 😕

But will it also resolve to an unlisted/deprecated version if the package hasn't been seen yet? (I'm sorry, I'm currently AFK and can't test this myself).

I suppose it may be the case since you probably want the same version to be resolved on different machines. 🙁 

@ricaun you may try to remove PropertyChanged.Fody v4.0.0 from the global packages folder if you'd like to test this.

**Comment by ricaun** [comment]
> @ricaun you may try to remove PropertyChanged.Fody v4.0.0 from the global packages folder if you'd like to test this.

I tried to remove the version 4.0.0 from the global packages folder and my project finds and download again the v4.0.0.

The best solution at the moment is use `Version="3.*"` until PropertyChanged.Fody is below version 4.0.0

**Comment by kartheekp-ms** [comment]
developer community report for the same issue https://developercommunity.visualstudio.com/t/NuGet-PackageReferences-wildcard-selects/10188536
