### ISSUE TITLE
[Bug]: [Bug Bash] Second-opening the “Version” drop-down list will show the bottom instead of the top after selecting a version in the custom version drop-down box

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#11991]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.4.0.22

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\32726.62
NuGet Version: Dev\6.4.0.22
OS Version: Windows-11-Enterprise-21H2 ENU

#### Detailed repro steps
1. Create a C# Console App (.NET 7.0) in VS and open the PM UI of the project. 
2. Click the “Browse” tab and click a package (e.g. “Microsoft.EntityFrameworkCore”) in the list. 
3. Click the down-arrow button of the “Version” drop-down box and select a package version (not the latest version) in the “Version” drop-down list. 
4. Click the down-arrow button of the “Version” drop-down box again to reopen the version list.
#### Expected
It will show the top of the version list.

#### Actual
It shows the bottom instead of the top as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/181232477-7d0b5a25-013c-4d0f-915c-9b2c02cda5f9.png)
#### Notes:
1.	It does not repro for the non-sdk style project [e.g. C# Console App (.NET Framework)] with the same steps.
2.     It reproes on NuGet 6.2.0.131.

**Comment by donnie-msft** [comment]
The version# shown in the main textbox shouldn't be offscreen when reopening the dropdown.
Better to scroll-to the value shown when reopening.

**Comment by martinrrm** [comment]
Closing, this is a bug in the combobox, I created a bug here https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1599649.

**Comment by donnie-msft** [comment]
@martinrrm we will have to update our VS Platform assembly in order to obtain this fix. I'd recommend marking it Blocked by External and leaving it open.
