### ISSUE TITLE
How are Roslyn analyzers supported with project.json?

### ISSUE THREAD

**Issue by hmemcpy** [NuGet/Home#1199]
The Roslyn SDK currently ships with a project template that creates a nuget package together with PowerShell installation files to add the analyzers to the solution.

With `project.json`, it is my understanding, PowerShell scripts are going away.

How will Roslyn analyzers continued to be supported in the new scenario?

(n.b. same question applies for .targets/.props)

**Comment by yishaigalatzer** [comment]
As far as I recall Roslyn looks at a top level folder in the package for these scenarios, and uses an install.ps1 for others. I'll track a sample and spec.

@jmarolf owns the design for this - Can you please submit a PR to docs.nuget.org and expand here?

**Comment by yishaigalatzer** [comment]
@hmemcpy - here is a sample https://www.nuget.org/packages/Microsoft.NETNative.Analyzer/1.0.0

**Comment by yishaigalatzer** [comment]
@hmemcpy the PR is updated, and it has all the technical details, now just cleaning up the verbiage. Let me know if you have more questions before we close this issue

**Comment by yishaigalatzer** [comment]
This is now public. @hmemcpy thanks for pushing on this.

**Comment by hmemcpy** [comment]
Awesome! Thanks so much for making it available!
