### ISSUE TITLE
[Feature]: Make NuGet.ProjectModel (and friends) usable within a Visual Studio extension.

### ISSUE THREAD

**Issue by kfertitta** [NuGet/Home#12001]
### NuGet Product(s) Involved

NuGet SDK

### The Elevator Pitch

Our company builds Visual Studio extensions, and we have a need to perform the very same tasks within our VS extension that NuGet.ProjectModel performs -- reading nuspec files, assets files, querying HTTP sources, etc.  Although these APIs are, themselves, available via NuGet packages, they cannot be used directly within a Visual Studio extension because of the lack of binding redirects within `devenv.exe.config`.

### Additional Context and Details

For us, the functionality exposed by these APIs is nearly as fundamental as a package like `Newtonsoft.Json`, which does, of course, have binding redirects in `devenv.exe.config`.  When we build our VS extension against a particular version of NuGet.ProjectModel, for instance, and then the end user updates VS to a version with a different in-box version of NuGet.ProjectModel, our extension breaks.  Obviously redist'ing these assemblies would break VS and I'm sure is not an intended scenario.  It would seem our only viable option is to clone the entire repo, build locally, and redist under a different set of assembly names.  That feels pretty drastic.

**Comment by drewnoakes** [comment]
The .NET Project System would also benefit from having a version of NuGet's project model available for use within VS. It'd allow us to move a bunch of code from NuGet.Client to the project-system repo.

**Comment by nkolev92** [comment]
We have a duplicate in https://github.com/NuGet/Home/issues/9611, which was probably something prompted when the original discussions about the NuGet nodes in the solution explorer (what @drewnoakes is probably referring to). 

Unfortunately I think the only way we could fix this would be to create a completely new assembly and limit the public API carefully. 
Maintaining both the library and tooling (NuGet ships in both VS & .NET SDK) with the same assemblies is a big challenge we deal with on the regular, and at this point we're not likely to want to add more assemblies to that public API surface area. 

cc @zivkan

**Comment by kfertitta** [comment]
Thanks @nkolev92 for the references to #9611.  I had, indeed, considered the VS interfaces, but I was wary of feature-diffs relative to `NuGet.ProjectModel`.  For context, ours is a full-on project system which, among other things, extends the DependencyTree via @drewnoakes excellent `IRelation`-based extensibility model.

Currently, we do have things working by building the entire set of assemblies under a different assembly name and dist'ing with our VSIX.  That was an option I saw you mention in #9611.  I hadn't seen any updates to that issue, so what is the current prescriptive guidance for extension devs such as us?  Should we really try to find a way to restrict our usage to the VS services (may or may not be possible over time), or should we continue for now with our redist'ed clone of `NuGet.ProjectModel` ?

Thanks very much in advance.

**Comment by nkolev92** [comment]
>  I hadn't seen any updates to that issue, so what is the current prescriptive guidance for extension devs such as us? Should we really try to find a way to restrict our usage to the VS services (may or may not be possible over time), or should we continue for now with our redist'ed clone of NuGet.ProjectModel ?

We don't really have an approach we can recommend at this point mostly because it depends on the amount of coupling a component already has with NuGet. 

Out of curiosity, are you trying to recreate the solution explorer integration, https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer?

**Comment by kfertitta** [comment]
@nkolev92 Thanks for the reply.  Indeed, we have been spending a lot of time studying how NuGet extended the Dependencies Tree and one of our use cases for parsing the assets file is to render additional details (specific to our project system) beneath the NuGet package nodes drawn by the NuGet client.  We setup TPL dataflows to monitor the assets file and use the LockFile parser in the very same way as the SE integration code in NuGet.

We'll take a fresh look at the API surface area we're actually using and see if we can, indeed, live with the `IVsXXX` interfaces for now.  Perhaps there will be a better solution than cloning a big hunk of the repo by the time our needs grow beyond what the shell APIs offer.

**Comment by kfertitta** [comment]
@nkolev92 One thing I see off the bat that we need that doesn't seem to be in the shell interfaces is an API to query a source for available packages.  Any advice there?  

This is the canonical example from `NuGet.Protocol` that exemplifies the kind of queries we need to perform:

```
ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceCacheContext cache = new SourceCacheContext();
SourceRepository repository = Repository.Factory.GetCoreV3("https://api.nuget.org/v3/index.json");
FindPackageByIdResource resource = await repository.GetResourceAsync<FindPackageByIdResource>();

IEnumerable<NuGetVersion> versions = await resource.GetAllVersionsAsync(
    "Newtonsoft.Json",
    cache,
    logger,
    cancellationToken);

foreach (NuGetVersion version in versions)
{
    Console.WriteLine($"Found version {version}");
}
```

**Comment by nkolev92** [comment]
Yep, we don't really have any public APIs that allow extensions to do that today. 

I don't really have any specific advice here as it really depends on your exact scenario (which I understand you may or may not be able to share much details about)
Are you querying the source in order to make a decision about whether to install a certain package? How is auth handled today.

**Comment by kfertitta** [comment]
@nkolev92 Yes, that, and querying about specific packages to determine the latest available version.  I've got a simple solution in place that just uses `HttpClient` against the V3 service endpoint and parses the JSON directly.  Just a few lines of code, really, for this particular scenario.  At present, we're only looking at a small bit of the response and it's a non-fatal error if something goes wrong connecting or parsing.

Given that, I feel we're in a much better place using the shell APIs and the `HttpClient` directly in place of building all of `NuGet.ProjectModel` and re-dist'ing.  I do, however, expect our needs to grow, so I feel the larger issue represented here is still kinda "open".  Thoughts?  Should we Close and connect to #9611?

**Comment by nkolev92** [comment]
> so I feel the larger issue represented here is still kinda "open"

Yes, agreed. 

> Should we Close and connect to https://github.com/NuGet/Home/issues/9611?

I'll do that. 

Would running an install in the project at question work instead? Are you updating or just installing a new package?

**Comment by kfertitta** [comment]
> Would running an install in the project at question work instead? Are you updating or just installing a new package?

Not in this particular case.  We're actually "converting" some domain-specific non-SDK-style projects to SDK style within our extension.  That involves a lot of direct manipulation of the project file XML and translating older item types to `PackageReference`'s where we'd need to use the latest version published on nuget.org.
