### ISSUE TITLE
[Bug]: A typo in NuGet.Client LockFileFormat.cs

### ISSUE THREAD

**Issue by sify21** [NuGet/Home#12018]
### NuGet Product Used

Other/NA

### Product Version

NuGet.Client repo dev branch

### Repro Steps & Context

It's a typo in source code. I just found it when reading the code. `ServicableProperty` missing a letter `e`

**Comment by nkolev92** [comment]
Hey @sify21. 

Thank you so much for the issue and the code contribution. 
It is unfortunate that we have this typo in our formatter code. 
Unfortunately we cannot take this change because the assets file is used for some performance optimizations, and this would be a breaking change.
