### ISSUE TITLE
RestoreUseStaticGraphEvaluation is reporting changes

### ISSUE THREAD

**Issue by belav** [NuGet/Home#12019]
I ran the following on a large solution
```
msbuild.exe -t:restore -p:RestoreUseStaticGraphEvaluation=true
msbuild.exe -t:restore
```

The second command shows that 1 project needed to be updated
```
  Writing assets file to disk. Path: C:\projects\insite-commerce\Src\Backend\Modules\JobQuote\Insite.JobQuote.Tests\obj
  \project.assets.json
  Restored C:\projects\insite-commerce\Src\Backend\Modules\JobQuote\Insite.JobQuote.Tests\Insite.JobQuote.Tests.csproj
  (in 645 ms).
```

I diffed the whole `obj` after the first command to after the second command, and there is just a single line change in `project.assets.json` and `Insite.JobQuote.Tests.csproj.nuget.dgspec.json`
```diff
      "warningProperties": {
+       "allWarningsAsErrors": true,
        "noWarn": [
          "NU1608"
        ],
        "warnAsError": [
          "NU1605"
        ]
      }
```

Digging through the other project `obj` folders, none of them include `"allWarningsAsErrors": true,` and we have this in a `Directory.Build.props`
```
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
```

I don't believe this would prevent us from using RestoreUseStaticGraphEvaluation, but I am not really sure what to make of it. It almost seems like p:RestoreUseStaticGraphEvaluation is correct and the regular restore shouldn't be including that line.

**Comment by jeffkl** [comment]
@belav thanks for reporting the issue and including all the details!  Just to clarify, does static graph restore add the `allWarningsAsErrors` line or does the non-static graph restore do that?

**Comment by belav** [comment]
@jeffkl It is the non-static graph restore that is adding the `allWarningsAsErrors` line.

I'm also on MSBuild version 17.3.0+f67e3d35e, one potentially important detail that I forgot.

**Comment by martinrrm** [comment]
@belav Hi! I have been trying to reproduce this behavior and couldn't do it. `"allWarningsAsErrors": true,` is added in both restores. Can you try again this in the latest VS version? If is still present, can you please share a repro? Thanks!

**Comment by belav** [comment]
@martinrrm I am unable to reproduce this anymore on MSBuild version 17.8.3+195e7f5a3 so it may have been resolved.
Thanks!
