### ISSUE TITLE
Dotnet list package restore automatically if there is missing asset file

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#12012]
### NuGet Product Used

dotnet.exe

### Product Version

n/a

### Worked before?

n/a

### Repro Steps & Context

Feedback follow up for https://github.com/NuGet/Home/pull/11983. 
If `asset file missing` then instead of just error out better do restore on the spot could be better customer experience. `dotnet build` already does same thing.

**Comment by jebriede** [comment]
@aortiz-msft do we want to put this on our backlog?

**Comment by nkolev92** [comment]
Team Triage: `dotnet list package` is offline by default. When adding vulnerable and deprecated we explicitly tried to keep it that way. restore itself is not offline, so this'd be breaking change/we'd be breaking the offline promise of the command.
