### ISSUE TITLE
[Bug]: After Migration from package.config to PackageReference implementation, Build works, but Rebuild fails

### ISSUE THREAD

**Issue by JosephNguyenDev** [NuGet/Home#12023]
### NuGet Product Used

MSBuild.exe, NuGet.exe

### Product Version

.NET Framework 4.6.2

### Impact

I'm unable to use this version

### Repro Steps & Context

I was on a project using .NET Framework 4.6.2 and was still using package.config. I used the migration tool to migrate the project to us ProjectReference instead. The project build correctly, but when I attempt to rebuild, the rebuild fails and my none of my nuget packages aren recognized. In my console output, I get errors stating "CS0006: Metadata file '.dll/exe' could not be found" for each of my projects in my solution

**Comment by nkolev92** [comment]
Hey @JosephNguyenDev, 

Thanks for trying out the migrator to PackageReference. 

Did the migrator raise any warnings? Any chance we get some sort of a repro so that we can determine whether NuGet did the expected? 

For context PackageReference would normally work well if you have packages that without install scripts or the likes, but there are some cases in which it might need some more manual work to get it working, but it is more project specific.

**Comment by JosephNguyenDev** [comment]
Hi @nkolev92, thanks for getting back to me. The migrator didn't raise any warnings on rebuild other than the metadata for the dlls and exe's were missing. As far as reproducing, I don't think I have the capacity to. I'm working on proprietary code, and am very new to the codebase and csharp development. I thought we could just migrate to using PackageReference, but my team ended up making the decision to switch back to using packages.config instead and are going to defer migration to a later date.  I have tried creating a new project using .net framework 4.6.2 and packages.config and attempted to migrate over, which succeeded. Then I realize that doesn't really help me identify what is keeping my main project from rebuilding.

**Comment by nkolev92** [comment]
I understand. 

At this point, I don't think we have enough to continue investigating. 
We can leave this issue open for some time. If you do have more information please share with us and we'd be happy to take a look.
