### ISSUE TITLE
Regression, .400 msbuild reports error on duplicate PackageVersions

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#12022]
### NuGet Product Used

MSBuild.exe

### Product Version

6.0.400

### Worked before?

yes

### Impact

I'm unable to use this version

### Repro Steps & Context

After upgrading to 6.0.400 version of SDK, dotnet restore fails on all our project. We had (benign) duplicate entries. This worked fine on 6.0.302, but now on 6.0.400 this results in build failures.

### Steps to Reproduce

https://github.com/erinlah-ms/bug-repros/tree/main/repro-packageversiondup

1. install just 6.0.302 sdk
2. clone folder linked above
3. cd original
4. dotnet restore. Note no errors
5. install 6.0.400 sdk (don't uninstall .302)
6. dotnet restore. 
7. cd workaround
8. dotnet restore
9. open visual studio 17.3.0 (latest VS 2022 Enterprise)
10. build/restore the workaround.csproj from visual studio

### Expected Behavior

Error at step 6, building original.csproj, no errors at step 8 or 10 building workaround.csproj

### Actual Behavior

Step 10 fails to restore/build in visual studio, despite workaround.

### Analysis

It appears that release .400 introduced a new warning for duplicate PackageVersion entries. This broke our repo.

Normally we would just workaround the issue until such time as we could fix it. However, Visual Studio does not permit the user to downgrade to an older release of msbuild. Building the 'workaround.csproj' folder under visual studio still fails.

Visual Studio lacks an option to honor the msbuild/sdk version selected in the repo. It partially ignores global.json by using the version/build of msbuild that is shipped in box in visual studio, including using the targets/tasks defined in that version of msbuild.

### Versions & Configurations

Dotnetsdk 6.0.302 / dotnet msbuild 17.2.0+41abc5629
dotnetsdk 6.0.400 / dotnet msbuild  17.3.0+92e077650
Visual Studio 2022 Enterprise 17.3.0

**Comment by jaredpar** [comment]
Copied from https://github.com/dotnet/msbuild/issues/7886

This bug is causing developers to revert updates to Visual Studio.

**Comment by nkolev92** [comment]
Starting with 6.3 of NuGet, 17.3 of VS and .NET SDK 6.0.400, NuGet warns when duplicate PackageReference, PackageDownload and PackageVersion items are detected. This behavior was added to ensure consistency and predictability for NuGet restores.

https://docs.microsoft.com/en-us/nuget/release-notes/nuget-6.3#summary-whats-new-in-63

You may choose to:
- Address the warnings removing the duplicate items
- NoWarn the warnings that you are getting.
- Set `DisableCheckingDuplicateNuGetItems` to `true`

**Comment by ghost** [comment]
Thanks for the update @nkolev92 . Any tips on the larger point (that sdk updates occasionally bring breaking changes, so how to use Visual Studio with dotnetsdk in presence of such breaks?). Unlike dotnetsdk, visual studio does _NOT_ appear to support side by side installation (e.g. 17.2.7 parallel with 17.3.0), preventing me and my team from using the VS version that matches our dotnetsdk.

**Comment by nkolev92** [comment]
> Any tips on the larger point (that sdk updates occasionally bring breaking changes, so how to use Visual Studio with dotnetsdk in presence of such breaks?)

Unfortunately I don't have any suggestions at this point. 
NuGet has this  particular challenge as well because it ships in both .NET SDK and VS and they have different versioning schemes.

We are considering change waves for future diagnostics introduced but that won't fully address the problem, rather reduce its frequency.

**Comment by nkolev92** [comment]
Team Triage: 

Closing as by design.
