### ISSUE TITLE
[Bug]: [Cross-Platform Sign Verify]Failed to add a package reference to the test package on Linux

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12037]
### NuGet Product Used

dotnet.exe

### Product Version

.Net SDK 7.0 latest

### Impact

It's more difficult to complete my work

## Repro Steps
1. Execute the [Pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29).
2. Where <CertificateFilePath> is the file path to the long-lived .cer or .pem file and <VersionedSdkDirectoryPath> is the directory path for the versioned .NET SDK directory, add trust for the certificate: 
`./dotnet/dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> -vsd <VersionedSdkDirectoryPath>`
3. Where <PackageId> is the test package ID and <PfxFilePath> is the file path to the .pfx file, sign the test package:  `./dotnet/dotnet nuget sign ./<PackageId>/bin/Debug/<PackageId>.1.0.0.nupkg --overwrite --certificate-path <PfxFilePath>`
4. Create a test project: 
 `mkdir ./test && pushd ./test && ../dotnet/dotnet new console && cp ../NuGet.config.template ./NuGet.config`
5. Clear local NuGet resources and previous restore results:
`rm -r -f ./obj && ../dotnet/dotnet nuget locals --clear all`
6.Where <PackageId> is the test package ID, add a package reference to the test package:
`../dotnet/dotnet add package <PackageId> --version 1.0.0`
## Expected 
Adding a package reference to the test package should be successful.
## Actual
Failed to add a package reference to the test package.
![image](https://user-images.githubusercontent.com/40230425/185345832-6ca438ed-77ff-4d85-b0e6-0217e4a4ffb9.png)
![image](https://user-images.githubusercontent.com/40230425/185345868-f440f7b6-a8a6-4a05-863d-6362e00f7f89.png)
## Note
The issue only reproes on Linux OS.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8543.

I think this is unrelated to signing
