### ISSUE TITLE
[Bug]: Nuget restores Windows assembly on some Linux distros (SqlClient)

### ISSUE THREAD

**Issue by alex-jitbit** [NuGet/Home#12031]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK (reflecting any global.json):  Version:   6.0.105

### Worked before?

Worked on NET5

### Impact

I'm unable to use this version

### Repro Steps & Context

The SqlClient team has directed me here, this is related to the bug: https://github.com/dotnet/SqlClient/issues/1643

For a NET6 app that uses SqlClient (both `System.Data.SqlClient` and `Microsoft.Data.SqlClient` packages) Nuget restores the windows versions instead of linux one, which results in error `System.Data.SqlClient is not supported on this platform`

Steps to repro:

1. Create a trivial .net6 app that references SqlClient nuget and calls `var x = new SqlConnection()`.
2. Install the app on AlmaLinux 8 (available form from Windows store for WSL), run the app via `dotnet MyProject.dll`
3. The app tries to use Windows assemblies, not the linux one.

The MS team was able to repro this. See https://github.com/dotnet/SqlClient/issues/1643 for more details and STR.

P.S. The same error is thrown in Red Hat Linux at one of our client's

**Comment by nkolev92** [comment]
Hey @alex-jitbit 

I noticed that when you publish you don't specify the RuntimeIdentifier, have you tried specifying the runtime identifier and seeing if the app works?

Can you help me understand which assembly is the one with the issues?
I don't think it's NuGet choosing the windows one explicitly, NuGet will use the lib one if there's no runtimeidentifer specific, so NuGet is just using what's provided there.

**Comment by alex-jitbit** [comment]
Yes, the app is "portable" so people can download it from our website and use with whichever OS they prefer. That's why we don't specify runtime when building

The assembly with the issue is `System.Data.SqlClient` (ironically, a MS's lib) if that's what you're asking. And according to [this comment](https://github.com/dotnet/SqlClient/issues/1643#issuecomment-1193844940) "the nuget restore process isn't identifying your distro as Linux"

**Comment by MarkpageBxl** [comment]
It seems the problem isn't necessarily on the NuGet side of things. When publishing a project depending on `System.Data.SqlClient` on Linux with .NET 6.0.108, we seem to end up with the stub `System.Data.SqlClient.dll` (which always throws the platform exception) and platform-specific artifacts in the `runtimes` directory.

When then running the application using the .NET 6.0.8 runtime, for some reason, the stub `System.Data.SqlClient.dll` is loaded at execution, whereas using .NET 6.0.0 loads `runtimes/unix/lib/netcoreapp2.1/System.Data.SqlClient.dll`. As such, it seems the problem is downstream, not at the NuGet level.

**Comment by nkolev92** [comment]
Thanks for contributing @mhlindstr! 

The assemblies from the `runtimes` folder will only be selected, when publish is called with a runtime identifier. 

@alex-jitbit I'm not sure your app can be portable given the sql package has platform specific implementations. You have to publish with a RID to get the correct implementation of the SQL package assets.

**Comment by alex-jitbit** [comment]
@nkolev92 My app has to be portable b/c it's cross-platform. Also, it works fine on Ubuntu and some other distos, just SOME distors throw this error.

Also it worked perfectly fine in .NET5

**Comment by nkolev92** [comment]
Hey @alex-jitbit, 

Can you try publishing for unix instead? 

Given that I don't think there's anything incorrect that NuGet is doing, I'd recommend continuing the discussion on the sqlclient issue.

**Comment by AraHaan** [comment]
@alex-jitbit did you try ``dotnet publish -r linux-x64`` or ``dotnet publish -r linux-arm`` or ``dotnet publish -r linux-arm64``?

**Comment by morvoso** [comment]
I'm getting this issue with PopOS 22 ( which is based on ubuntu I believe ).  I specify the RID and it still appears.  All my other code works fine except for this SqlClient package.

**Comment by jinek** [comment]
Same on Pop_Os.
Same with dotnet 7. ( after few different approaches to install dotnet 7, it started to work somehow. Im not sure why and if that is preserved)
Am I right that simple workaround is to fallback to dotnet 5?

**Comment by morvoso** [comment]
Not sure who's issue this is, but wouldn't adding the popos name to the
list of accepted distro fix this issue? For some reason I remember seeing a
file with all the distro in it...

**Comment by butrov** [comment]
I received an error that SqlClient could not execute the SqlConnection command:
```
Exception has occurred: CLR/System.PlatformNotSupportedException
An exception of type 'System.PlatformNotSupportedException' occurred 
 in Microsoft.Data.SqlClient.dll but was not handled 
 in user code: 'Microsoft.Data.SqlClient is not supported on this platform.'
```

We are checking the version of dotnet.
# dotnet --info
Runtime:
 OS Name:     redos
 OS Version:  7.3.2
 OS Platform: Linux
 RID:         fedora.34-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.105/
 
 dotnet sdk 6.0 was installed from the repository http://repo.red-soft.ru/redos/7.3/x86_64/os/
 
# Workaround.
https://github.com/dotnet/SqlClient/issues/1643#issuecomment-1445039402
  
After that, the 'System.PlatformNotSupportedException' error has stopped appearing. Now everything is working normally.
