### ISSUE TITLE
System.Data.HashFunction.**** is giving Nuget Warning: NU3005

### ISSUE THREAD

**Issue by AnilReddyKandula** [NuGet/Home#12046]
Whenever we try to import the following nugets, it was resulting in nuget warning. 
Error: ##[error]The nuget command failed with exit code(1) and error(NU3005: Package 'System.Data.HashFunction.Interfaces 2.0.0' from source '---: The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).

Nugets: 
<PackageReference Include="System.Data.HashFunction.Core" Version="$(SystemDataHashFunction)" NoWarn="NU3005" />
<PackageReference Include="System.Data.HashFunction.xxHash" Version="$(SystemDataHashFunction)" NoWarn="NU3005" />
<PackageReference Include="System.Data.HashFunction.Interfaces" Version="$(SystemDataHashFunction)" NoWarn="NU3005" />

So these nuget warnings had to be suppressed manually.

**Comment by nkolev92** [comment]
Hey @AnilReddyKandula 

Looks like you are trying to install a package that appears to have been tampered with.

What's the version of the tooling you are using?
What's the source you are trying to install the package from? 
If you download the package manually and If you run `nuget.exe verify` or `dotnet nuget verify` on it, what's the output you get?
