### ISSUE TITLE
Possible race condition when packing

### ISSUE THREAD

**Issue by mausch** [NuGet/Home#1204]
I have an assembly named DocumentConversion.dll that's referenced in 4 projects in a solution of 54 projects total.
16 of these projects are exported as NuGet packages. Since "nuget pack" is pretty slow, I'm running this concurrently (using rake's multitask, but that doesn't matter).
Every now and then, one of the "nuget pack"s fails with the output:

```
DocumentConversion.dll
Cannot access a closed stream
```

or:

```
DocumentConversion.dll
Object reference not set to an instance of an object
```

without any stack trace.

This happens randomly, i.e. maybe 10% of the time, and it doesn't happen at all if I disable concurrency, which makes me think it's some kind of race condition or some other concurrency bug.

Also this only happens with this particular library reference. The only unusual thing I see about this DLL is that it's pretty big (16MB).

**Comment by yishaigalatzer** [comment]
Looks like a dup of #1282 we are going to look at both these reports this week.
