### ISSUE TITLE
[Bug]: Console wont open and it turns purple and VSMac crashes

### ISSUE THREAD

**Issue by Edrisym** [NuGet/Home#12077]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

17.3.3

### Worked before?

before 17.3.3

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi 

I am using a MacBook Pro M1 2020 and 2022 visual studio 

I used to use the package manager console for adding migration for my application
and after I upgraded VS and the extension I wasn't able to open the Nuget Package manager console 
somehow when I click, it turns purple, and VS crashes 
I'm desperate please help me solve this I don't know what is wrong with it

![Screen Shot 2022-08-15 at 16 41 49](https://user-images.githubusercontent.com/101327489/188302781-ba86bf70-13b9-4f4c-8335-d6d6c3073a06.png)

and this error comes up 

![Screen Shot 2022-08-15 at 16 14 27](https://user-images.githubusercontent.com/101327489/188302710-50838e0c-f9da-4024-8dfb-b2c98249c84c.png)

### Verbose Logs

```shell
Nuget Package Manager Console
```

**Comment by donnie-msft** [comment]
Hello @Edrisym , I've reached out to the VSMac team for guidance. I'll let you know once I know more.

Meantime, I see your Project dropdown is empty in the console window. Are you able to build your project(s)? Any other errors shown in VSMac outside of the package manager console?

**Comment by mrward** [comment]
@Edrisym would be able to you look for errors in the IDE log? Help - Open Visual Studio Log. Do not share the full IDE Log (just the errors which should be near the end of the file).

Also which version of the NuGet Extensions do you have installed? You should be able to find that from the about dialog's Show Details page (at the end there is a `Enabled user installed extensions` section).

Thanks.

**Comment by renanelias** [comment]
Same error here. It's been a common problem between the latest updates... How to solve this?

![image](https://user-images.githubusercontent.com/452862/191790762-e010d738-b616-438b-bb52-bcbda2be6256.png)

**Comment by mrward** [comment]
@renanelias Which version do you have installed and which version of VS Mac are you using? And can you provide the error in the IDE log? Thanks.

All the releases for the different versions are available here - https://github.com/mrward/monodevelop-nuget-extensions/releases

**Comment by renanelias** [comment]
> @renanelias Which version do you have installed and which version of VS Mac are you using? And can you provide the error in the IDE log? Thanks.
> 
> All the releases for the different versions are available here - https://github.com/mrward/monodevelop-nuget-extensions/releases

VS 17.3.5 (Mac OS), NuGet Package Manager 0.31

I didn't find many information about the error, but this json was displayed on the error screen before VS crash:

https://paladins.com.br/error.txt

I removed the hidden ".vs" folder from the solution folder and I cleared the bin and obj folders from the projects. After that, the plugin starts to work again, like expect.

**Comment by mrward** [comment]
@renanelias There may be more info in the IDE Logs folder `~/Library/Logs/VisualStudio/17.0` - in that directory there will be the ide log and probably a vsmonitor log (which may have crash information).

Also do not post the entire IDE Log file here (since it may contain some personal data). Probably better if you zip up the entire directly and email the logs to me. mawa at microsoft.com

**Comment by renanelias** [comment]
> @renanelias There may be more info in the IDE Logs folder `~/Library/Logs/VisualStudio/17.0` - in that directory there will be the ide log and probably a vsmonitor log (which may have crash information).
> 
> Also do not post the entire IDE Log file here (since it may contain some personal data). Probably better if you zip up the entire directly and email the logs to me. mawa at microsoft.com



Sent! I hope it helps to fix the problem.

**Comment by mrward** [comment]
The crash should be fixed in a later VS Mac 17.4 release, preview 3.

For VS Mac 17.3 there is a new build of the NuGet extensions addin that may fix the problem: 

https://github.com/mrward/monodevelop-addins/blob/gh-pages-vsmac-17.3/17.3/MonoDevelop.PackageManagement.Extensions.0.31.1.mpack

I believe the underlying problem is that lazy loading of dependencies has changed in VS Mac 17.x so assemblies are not loaded causing an error. The above NuGet extensions indicates all its assemblies need to be loaded when the addin loads which should hopefully fix the problem, but I cannot repro it myself.

**Comment by renanelias** [comment]
> The crash should be fixed in a later VS Mac 17.4 release, preview 3.
> 
> For VS Mac 17.3 there is a new build of the NuGet extensions addin that may fix the problem:
> 
> https://github.com/mrward/monodevelop-addins/blob/gh-pages-vsmac-17.3/17.3/MonoDevelop.PackageManagement.Extensions.0.31.1.mpack
> 
> I believe the underlying problem is that lazy loading of dependencies has changed in VS Mac 17.x so assemblies are not loaded causing an error. The above NuGet extensions indicates all its assemblies need to be loaded when the addin loads which should hopefully fix the problem, but I cannot repro it myself.

I've been using this version since you sent it to me and the problem hasn't happened anymore. I believe it has been resolved. Thanks.

**Comment by donnie-msft** [comment]
Closing based on the fix mentioned, and reports of it resolving the issue. If anyone still experiences the issue, give us a ping!

**Comment by zivkan** [comment]
> If anyone still experiences the issue, give us a ping!

I know it's not obvious to customers, but NuGet in VS for Mac isn't maintained by the same people who work in github.com/nuget, so it would be better to report the problem though VS for Mac's feedback system. If it's reported here, we can certainly pass on the message, but customers might get better, and more direct, support though VS for Mac's official suport channel.

**Comment by Edrisym** [comment]
> Hello @Edrisym , I've reached out to the VSMac team for guidance. I'll let you know once I know more.
> 
> Meantime, I see your Project dropdown is empty in the console window. Are you able to build your project(s)? Any other errors shown in VSMac outside of the package manager console?

HI @mrward I really appreciated it and I am absolutely thankful for reaching out
sorry if I was late to answer (I live in Iran and internet was blocked)
yes I can build my project and I have tested everything I could 
still no clue

**Comment by Edrisym** [comment]
> 

@mrward  thanks for letting me know about the IDE log 
it has some errors and warnings 
and I have NuGet Package Explorer 0.10 V
NuGet Package Management Extensions  0.31 V
Installed

**Comment by Edrisym** [comment]
> Same error here. It's been a common problem between the latest updates... How to solve this?
> 
> ![image](https://user-images.githubusercontent.com/452862/191790762-e010d738-b616-438b-bb52-bcbda2be6256.png)

@renanelias Hey I see you have the same issue like me and its been 3 months Im using external terminal directing the folder of my project and it is working but it is really bothering in total 
if you could find any solutions PLZ I'd be really happy if you let me know 
Thanks

**Comment by renanelias** [comment]
> > Same error here. It's been a common problem between the latest updates... How to solve this?
> > ![image](https://user-images.githubusercontent.com/452862/191790762-e010d738-b616-438b-bb52-bcbda2be6256.png)
> 
> @renanelias Hey I see you have the same issue like me and its been 3 months Im using external terminal directing the folder of my project and it is working but it is really bothering in total if you could find any solutions PLZ I'd be really happy if you let me know Thanks

Hey! I installed the latest version (0.31) and removed the .vs folder located in the project root folder. After that, the plugin started working again.

**Comment by Edrisym** [comment]
> > > Same error here. It's been a common problem between the latest updates... How to solve this?
> > > ![image](https://user-images.githubusercontent.com/452862/191790762-e010d738-b616-438b-bb52-bcbda2be6256.png)
> > 
> > 
> > @renanelias Hey I see you have the same issue like me and its been 3 months Im using external terminal directing the folder of my project and it is working but it is really bothering in total if you could find any solutions PLZ I'd be really happy if you let me know Thanks
> 
> Hey! I installed the latest version (0.31) and removed the .vs folder located in the project root folder. After that, the plugin started working again.

that is amazing, thank you so much
I did install it it is working and the background turned white 
I'm worried. hahah
I think it's bcz of the version, isn't it?
and also I couldn't find the .vs folder 
could you tell me the director
thanks a lot

**Comment by mrward** [comment]
@Edrisym Try version 0.31.1 of the NuGet extensions addin - https://github.com/mrward/monodevelop-addins/blob/gh-pages/17.3/MonoDevelop.PackageManagement.Extensions.0.31.1.mpack

**Comment by Edrisym** [comment]
@mrward  Thank you so much man 
it is working finally
