### ISSUE TITLE
After saving a solution, 'Restore' button does not show up on Package Manager Console

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1207]
After saving a solution, 'Restore' button does not show up on Package Manager Console

Repro steps
1. Create a C# Console App. Save the solution
2. Install Newtonsoft.Json
3. Close the solution
4. Delete packages folder and the solution file
5. Open VS and open package manager console
6. Open the .csproj from Step (1). 
7. Save the solution in the same directory as .csproj file

Expected:
Package restore button shows up since packages are missing from the solution and the solution is saved

Actual:
Package restore button does not show up. One needs to restart PackageManagerConsole to see the button

**Comment by nkolev92** [comment]
Redundant.
