### ISSUE TITLE
[Bug]: Broken link in msftbot

### ISSUE THREAD

**Issue by Eli-Black-Work** [NuGet/Home#12080]
### NuGet Product Used

Other/NA

### Product Version

N/a

### Repro Steps & Context

`msftbot` just posted a message at https://github.com/NuGet/Home/issues/9803#issuecomment-1235816557 that says this:

> Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)

The "Type label" link 404's.

**Comment by donnie-msft** [comment]
Hello, this is not a public URL but points to an internal team document. It's an action for the team to apply labels.

**Comment by Eli-Black-Work** [comment]
Ah, got it, thanks.
