### ISSUE TITLE
Slow installation of msbuild task delivered by nuget

### ISSUE THREAD

**Issue by msedi** [NuGet/Home#12081]
### Discussed in https://github.com/NuGet/Home/discussions/12079

<div type='discussions-op-text'>

<sup>Originally posted by **msedi** September  4, 2022</sup>
I'm creating an msbuild task which we deliver as a nuget package. Everything works fine so far, the task does what it should but a problem is the installation of the nuget package. It takes around 5 minutes to install the nuget package and there is not real log to identify the source of the lag.

During development I simply increase the version number to show a new package version. Afterwards I go to a demo project that contains the nuget package. I then simply update the nuget package in my demo project to the latest version, and this is what I get:

```
Restoring NuGet packages...
Running restore with 32 concurrent jobs.
Reading project file D:\GIT\IPIPE\Libraries\Managed\siemens.CUDA\siemens.CUDA.csproj.
The restore inputs for 'siemens.CUDA' have changed. Continuing restore.
Restoring packages for D:\GIT\IPIPE\Libraries\Managed\siemens.CUDA\siemens.CUDA.csproj...
Restoring packages for .NETCoreApp,Version=v6.0...
Resolving conflicts for net6.0...
Scanning packages for runtime.json files...
Restoring packages for net6.0/win-x64...
Resolving conflicts for net6.0/win-x64...
```

After around 5 minutes I get this output

```
Feeds used:
    https://api.nuget.org/v3/index.jsonC:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    D:\GIT\IPIPE\_Build\Release\Assemblies\ipipe.Cuda.Design
    Restored D:\GIT\IPIPE\Libraries\Managed\siemens.CUDA\siemens.CUDA.csproj (in 4,54 min).
NuGet package restore finished.
Time Elapsed: 00:04:32.6545900
```

The problem is that I do not see who is wasting time. Is there anything I can do to get more logging?

</div>

**Comment by nkolev92** [comment]
Hey @msedi, 

Thanks for creating this issue. 

We'd need some extra information to determine what's going on here: 

- Can you please provide a verbose output. It will have information about all the http calls made by NuGet. 
- Can you upload the assets file (note it can contain proprietary information). 
  The assets file can tell us how many packages were used, and whether we are dealing with a really large project graph.
- What's the size of the package in question?

**Comment by nkolev92** [comment]
Closing https://github.com/NuGet/Home/issues/12083 as it has more details.
