### ISSUE TITLE
[Bug]: [Bug Bash][Suggestion] Suggest to show a tooltip “Show existed version” when hovering on the arrow-down button of Version drop-down box on the right panel of the PM UI

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#12093]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.4.0.85

### Impact

It bothers me. A fix would be nice

## Repro steps:  
1. Launch VS and create a solution [e.g. C# Console App (.NET Framework 4.8.1)].
2. Open the PM UI.
3. Hover-on the arrow-down button of Version drop-down box on the right panel of PM UI.

## Expected:
There should be a tooltip like “Show existed version” when hovering on the arrow-down button of Version drop-down box on the right panel of the PM UI as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/190375072-e15342d1-fce1-46a0-8dd7-3e26730b66ad.png)
## Actual: 
No tooltip shows when hovering on the arrow-down button of Version drop-down box on the right panel of the PM UI as below screenshot. 
![image](https://user-images.githubusercontent.com/71433406/190375183-a7e77f3d-abcf-44c1-919e-b9c702af4cd4.png)
## Notes:
1. It is just a suggestion.
2. It is not a regression.

**Comment by donnie-msft** [comment]
I understand why this was suggested; however, I believe the tooltip is not necessary, so I'm closing it for now. Please let me know if you have a counterargument, and we can reconsider.

The VS Search Control is a different control than the "Versions" drop-down box. Tooltips on dropdowns are not standard, even though you do find them on these VS controls in toolbars, etc. If we did need this change, we'd likely have to work with Platform team to modify the control template.
