### ISSUE TITLE
[Bug]: User needs to login multiple times while executing dotnet list package from private feeds

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12090]
### NuGet Product Used

dotnet.exe

### Product Version

 .NET Core 3.1 SDK and later versions

### Worked before?

No

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The steps to reproduce this issue are explained clearly in https://github.com/microsoft/artifacts-credprovider/issues/329

Related issues: 
- https://developercommunity.visualstudio.com/t/Azure-Artifacts-Credential-Provider-dele/10110841
- https://github.com/microsoft/artifacts-credprovider/issues/343

@sliekens reported these issues and I guess the root cause appears to be NuGet creating new `SourceRepository` to interact with resources (ServiceIndexResource, PackageMetadataResource) while executing list package command.

### Verbose Logs

```shell
Verbose logs can be found in the developer community issue linked in the issue description.
```

**Comment by ransagy** [comment]
Do we have any idea when this will pop up in nuget.exe/dotnet.exe etc assuming this is the sole source of this issue?

Every other nuget operation (list, restore, etc) fails for me with a 401 and removal of the cached token since these recent chain of updates and im no closer myself to understanding the source of it.

It made trying to use our private feed a living hell in anything.

**Comment by kartheekp-ms** [comment]
> Do we have any idea when this will pop up in nuget.exe/dotnet.exe etc assuming this is the sole source of this issue?

This fix was released in .NET 7 SDK RC2 https://dotnet.microsoft.com/en-us/download/dotnet/7.0 and it applies only to `dotnet list package` command. 

> Every other nuget operation (list, restore, etc) fails for me with a 401 and removal of the cached token since this recent chain of updates and im no closer myself to understanding the source of it.
> It made trying to use our private feed a living hell in anything.

Are you experiencing similar issue for other NuGet operations such as restore? If yes, can you please create a new issue with some logs & repro steps.
