### ISSUE TITLE
[DCR]: Change PackageReference restore algorithm to prevent redundant packages from being downloaded

### ISSUE THREAD

**Issue by stephenjust** [NuGet/Home#12109]
### NuGet Product(s) Affected

NuGet.exe, MSBuild.exe, dotnet.exe

### Current Behavior

Currently when doing a package restore, Nuget will download packages that are eclipsed by newer versions if that newer version is not a direct dependency of a parent.

![image](https://user-images.githubusercontent.com/3144757/192067489-4fcf50a0-43c6-4a5c-b720-6b49e8173f7c.png)

In the example above, both LibC 1.0.0 and LibC 1.0.2 will be downloaded (but only 1.0.2 installed). However, LibB 1.0.0 will neither be downloaded nor installed since a newer version is a direct dependency of a parent node.

If you use a nuget Lock file, the restore is smarter and only downloads the packages that will be installed.

### Desired Behavior

Nuget should only download packages that will be installed, even without the presence of a lock file.

This may require changes to package servers to provide additional metadata about dependencies or to optionally do the dependency resolution entirely server-side (verified by the client).

### Additional Context

Component scanning tools can detect packages downloaded by nuget, even if not installed. This can make it difficult to remove components from a build.

**Comment by nkolev92** [comment]
Hey @stephenjust, 

NuGet downloading the packages that may be rejected, often serves as an optimization for subsequent restores, as it'd allow NuGet to fully analyze the graph without having to download packages that may latter be rejected by the algorithm. 

Changing the algorithm to do comparisons between separate subgraphs is likely to add a lot of overhead to an already complex algorithm. 

> Component scanning tools can detect packages downloaded by nuget, even if not installed. This can make it difficult to remove components from a build.

Thank you for providing the context! 

If you're able to provide this information, can you let us which services you are using? 
We've noticed this with some component governance tools and we're working with some of them to focus on the `project.assets.json` to learn about the exact packages being used.

**Comment by stephenjust** [comment]
Specifically we use Microsoft's internal Azure DevOps step. It does read project.assets.json to add some metadata but also reports on any nuspec files that it finds (which are present in the package download location)

**Comment by nkolev92** [comment]
Good news is that we're working with that team to not raise false positive alerts about such packages. 

Beyond that, we don't think we'd want to be any changes NuGet side at this point. 

For context, the issue that sparked our discussion with the MS team is https://github.com/NuGet/Home/issues/11782. 

Closing this per these comments. 
For now, we can only recommend suppressing these warnings as "unused" 

Anything that doesn't show up in `dotnet list package --include-transitive` can be suppressed with the same reasoning.
