### ISSUE TITLE
Use latest version as dependency

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1210]
_From @remster85 on August 4, 2015 10:24_

Here is my setup.

I have a project that contains the wcf configuration (endpoints mostly) about a service. Let’s call it config package.

I have a service project that references the config dependency via nuget.

My problem is everytime the config is updated, I need to open the service project and manage my nuget dependency and request an update. It’s time consuming!

Is there any way to tell the service to reference the latest version available if any ?
I would only need to rerun the service project build instead.

I found this article https://docs.nuget.org/create/versioning.

They mention using empty version in order to get the latest but visual studio is not able to understand :
=> Unable to parse version value ” from ‘packages.config’.

Any clue how to do it ?

Thanks

_Copied from original issue: NuGet/NuGetGallery#2605_

**Comment by yishaigalatzer** [comment]
Unfortunately that is not supported, we should probably remove the empty dependency from the docs, as you are right it is wrong and does not work.

Automatically updating a project is something we do not support, and don't intend to. You should probably move the configuration away from a nuget package.

Down the road with project.json based projects (and you can experiment with that, though its not official supported for WCF projects), you can use a \* notation. Unfortunately there is not yet built in content support (planned for next release though) for this model.

Keep a track of this issue - https://github.com/nuget/home/issues/627 for when it happens.

**Comment by ghost** [comment]
Remi.desreumaux@sgcib.com

**Comment by raygerrard** [comment]
I have also wasted time trying to figure out why using empty as the docs state does not work. The docs should be updated.
