### ISSUE TITLE
[Bug]: [Bug Bash][Localization] The translation of string “NuGet storage cleared at (current time)” in Options window is incorrect

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12108]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.4.0.97

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\32922.386 (installed “Chinese (Simplified)” language pack)
NuGet Version: Dev\6.4.0.97
OS Version: Windows-11-Enterprise-21H2 ENU

#### Detailed repro steps
1. Open VS, click menu Tools->Options->Environment->International Settings and select “中文(简体)” in the “Language” dropdown list and restart VS.
2. Create a “C# Console App (.NET 7.0)” project in VS.
3. Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
4. Click the “Browse” tab and install some packages into this project.
5. Click the settings button on the top-right of PM UI to open the Options window.
6. Go to NuGet Package Manager->General tab and click the “Clear All NuGet Storage” button.

#### Expected
The translation should be “在9/23/2022 2:09:53 AM已清除NuGet存储”.

#### Actual 
The translation is incorrect as “已清除 9/23/2022 2:09:53 AM 处的 NuGet 存储” since the “9/23/2022 2:09:53 AM” is a time not a place.
![image](https://user-images.githubusercontent.com/20632625/191941090-07ec2661-c05d-40fb-ac5e-f7234287c440.png)
#### Notes:
It doesn’t repro on D16.11\32802.440.

**Comment by donnie-msft** [comment]
@dominoFire do you know if this is a problem with the loc process, or something we did wrong with the string?

**Comment by dominoFire** [comment]
I don't think there's a problem with the loc process. Also, I don't think we did something wrong. The string has comments. The string is localized. By looking at localization repo, you can see the translation update

https://github.com/NuGet/NuGet.Build.Localization/commit/be781393a4610a04f9f7ce8326f3b6bd548f50c0#diff-c28633847de6545b1c8088f7454dfa89d693afcfe97dd30d4969c3c8d840e257R2214

**Comment by dominoFire** [comment]
Filed ticked with localization team to investigate.

**Comment by dominoFire** [comment]
This was fixed by loc vendors. Here's the commit: https://github.com/NuGet/NuGet.Build.Localization/pull/977/files

Here's the PR https://github.com/NuGet/NuGet.Build.Localization/pull/977
