### ISSUE TITLE
[Bug]: The transitive package doesn’t show in “Installed” tab until reopening the solution

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12102]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.4.0.92

### Impact

It bothers me. A fix would be nice

## Repro steps: 
1.  Set the environment Variable NUGET_TRANSITIVE_DEPENDENCIES_IN_PMUI=1.
2. Create a new C# Console App (.Net Core) project.
3. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open PM UI. 
 4. Click “Browse” tab, search a package (e.g. “Microsoft.EntityFrameworkCore”) that has dependencies, select a package version [6.0.4] in the "Version" drop-down list in the right panel and click the “Install” button on the right.
5. Switch to “Installed” tab.

## Expected:
The transitive package should show in “Installed” tab.

## Actual:
The transitive package doesn’t show in “Installed” tab as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/191237740-12394cc1-993a-4a62-b872-9c40c42ff462.png)

## Notes: 
1. The transitive package can be show in “Installed” tab after closing solution/VS and reopening the same solution.
2. The issue starts from NuGet Client Dev\6.4.0.90.

**Comment by donnie-msft** [comment]
@v-longmin do you get the desired behavior if you choose `File -> Save All` after the Install completes, but before opening the Installed tab?

@jebriede may be able to speak to the caching strategy used for this feature. I would guess that what's happening is the assets file isn't being re-generated, and the UI is reading/showing stale data from the previous restore.

**Comment by dominoFire** [comment]
I can repro the bug on latest VS with NuGet 6.4.0.90; investigating.

**Comment by dominoFire** [comment]
When a package is installed, this should invalidate inner cache in `PackageReferenceProject` and, then, repopulate them.

**Comment by dominoFire** [comment]
There seems to be a race condition when we re-read the assets file and when the assets file is restored with updated info.

**Comment by dominoFire** [comment]
A pull request is on the way: https://github.com/NuGet/NuGet.Client/compare/dev-dominofire-fixcache?expand=1

**Comment by v-longmin** [comment]
@dominoFire It doesn't work after choosing file -> save all after the install completes.
