### ISSUE TITLE
[Bug]: [Cross-platform Sign Verify]An error ” error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version(= 6.0.10)” occurred when creating the long-lived test code signing certificate

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12111]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet Client Dev\6.4.0.97

## Repro steps: 
1. Open a Command prompt.
3. Create a test pass directory and path into it: mkdir .\testpass && pushd .\testpass:.
4. Download the latest .NET install script: `curl -sSL https://dot.net/v1/dotnet-install.ps1 -o .\dotnet-install.ps1`
5. Install the .NET SDK using script: `powershell.exe .\dotnet-install.ps1 -InstallDir .\dotnet -Channel 7.0 -Version latest -Quality daily -NoPath.`
6. Clone the NuGet Entropy repository:  `git clone https://github.com/NuGet/Entropy.git.`
7. Create a long-lived test code signing certificate: `dotnet.exe run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net7.0 -- -vp 10`

## Expected:
Create the long-lived test code signing certificate successfully.

## Actual:
An error ” error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version(= 6.0.10)” occurred when creating the long-lived test code signing certificate as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/192229563-f0b31e1b-a7a1-45f5-8d39-f5dbad0ddd6d.png)
## Notes:
1. The issue also repro on Linux & MacOS as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/192229982-61389474-d3f8-489a-9949-bbef98f0c45c.png)
![image](https://user-images.githubusercontent.com/40230425/192230007-c10f976c-7131-4fcf-9fec-1fd3cb6e487f.png)
2. Workaround: The issue doesn’t repro after deleting TargetFramework net6.0 in MakeTestCert.csproj file.

**Comment by erdembayar** [comment]
I can repro this.

```
C:\NuGetProj\Entropy\TestCertGenerator\testpass\dotnet\dotnet.exe run --project .\MakeTestCert\MakeTestCert.csproj --framework net7.0 -- -vp 10 -v n

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.100-rtm.22480.6

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.11)
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102:   - Found 54 version(s) in nuget [ Nearest version: 7.0.0-preview.1.22076.8 ]
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 6.0.11)
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102:   - Found 50 version(s) in nuget [ Nearest version: 7.0.0-preview.1.22077.5 ]
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 6.0.11)
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102:   - Found 55 version(s) in nuget [ Nearest version: 7.0.0-preview.1.22109.13 ]
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 6.0.11)
C:\NuGetProj\Entropy\MakeTestCert\MakeTestCert.csproj : error NU1102:   - Found 100 version(s) in nuget [ Nearest version: 7.0.0-preview.1.22076.8 ]

The build failed. Fix the build errors and run again.
```

**Comment by erdembayar** [comment]
Fyi @dtivel

**Comment by nkolev92** [comment]
The problem is that the packages needed are not yet published on the sources specified. 
Once these packages are published on nuget.org, this should work. 

We'll continue this discussion via e-mail.
