### ISSUE TITLE
VS Extension: slow packages list updates\listing

### ISSUE THREAD

**Issue by centur** [NuGet/Home#1211]
VS Extension is very chatty on the network and doesn't perform proper response caching, which results in very low overall performance when listing all packages or updates:
- For each package in the solution it'll lookup for index.json file which is a separate network call.
- The data that downloaded with each call to index.json doesn't seems to be cached on a client side, thus results in consequent calls to get exactly the same data.
- Each action like Upgrade single package or install existing package into another project, flushes entire state and triggers all packages to be updated again - thus same call to index.json
- Network responses (index.json) are not gzipped which causes even more traffic, slower experience

Overall, upgrading packages in a solution with 70 packages ( not the biggest one :) ever) can result in 4Mb of internet traffic per each package upgrade
Here is [a link to fiddler capture](https://dl.dropboxusercontent.com/u/4735273/Chatty%20Nuget%20v3.saz)  with calls that were triggered after single package upgrade.

Potential fixes: 
1. Enable gzip compression on server-side. As you're using Azure block blob - it might be needed to upload compressed BlockBlobs and set Content-Encoding metadata manually there
2. Enable caching header on the server side and respect it on a client side - server side seems easy as it's just a metadata on a blob, client probably needs to be updated.

Even 5-10 minutes cache can improve overall experience - I'm not sure that real-time information about package versions is needed. But it'll avoid long refreshes and excessive traffic when managing nuget packages in Visual Studio.

Test environment:
Nuget Extension ver: 3.1.60724.766
Microsoft Visual Studio Community 2015 Version 14.0.23107.0 D14REL
Microsoft .NET Framework Version 4.6.00079

**Comment by yishaigalatzer** [comment]
Moved to the gallery.
