### ISSUE TITLE
[Bug]: [Cross-platform Sign Verify] An error NU1101 occurred after adding package to the test project and restoring the project on MacBook

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12118]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 7.0.100-rtm.22476.1

### Impact

It bothers me. A fix would be nice

#### Detailed repro steps
1.	Execute the [pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29).
2.	Create a test code signing certificate. 
On macOS:`  ./dotnet/dotnet run --project ./Entropy/MakeTestCert/MakeTestCert.csproj --framework net7.0 `
This will create a test code signing certificate. 
Keep the output of this tool.  You will refer to it in later steps. 
3.	Where <PackageId> is the test package ID and <PfxFilePath> is the file path to the .pfx file, sign the test package: 
        On macOS:`  ./dotnet/dotnet nuget sign ./<PackageId>/bin/Debug/<PackageId>.1.0.0.nupkg --overwrite --certificate-path <PfxFilePath> `
4.	Verify that the previous step succeeded with the following warnings. 
a.	warn : NU3002: The '--timestamper' option was not provided. The signed package will not be timestamped. To learn more about this option, please visit https://docs.microsoft.com/dotnet/core/tools 
b.	warn : NU3018: UntrustedRoot: self-signed certificate 
5.	Create a test project: 
       On macOS:  `mkdir ./test && pushd ./test && ../dotnet/dotnet new console && cp ../NuGet.config.template ./NuGet.config `
6.	Update NuGet.config to reference the SHA-256 fingerprint of the certificate created in step 2. 
7.	Clear local NuGet resources and previous restore results: 
       On macOS: ` rm -r -f ./obj && ../dotnet/dotnet nuget locals --clear all `
8.	Where <PackageId> is the test package ID, add a package reference to the test package: 
       On macOS: ` ../dotnet/dotnet add package <PackageId> --version 1.0.0 `
9.	Verify the results of the previous step. 
       On macOS, the operation succeeded with no warnings or errors. 
info : X.509 certificate chain validation will use the fallback certificate bundle at '/home/dtivel/testpass/dotnet/sdk/7.0.100-preview.7.22376.5/trustedroots/codesignctl.pem'. 
10.	Repeat step 7. 
11.	Where <PackageId> is the test package ID, edit test.csproj to include the following element directly inside the root <configuration> element: 
```
<ItemGroup> 
<PackageReference Include="<PackageId>" Version="1.0.0" /> 
</ItemGroup> 
```
12.	Restore: 
        On macOS: ` ../dotnet/dotnet restore -v detailed.`

#### Expected
There is no error NU1101 shows in step8 and step12.

#### Actual
There is error NU1101 shows in step8 and step12 as below.
![image](https://user-images.githubusercontent.com/20632625/192535655-46255f0f-63e0-4b43-8006-076439de2d6c.png)

![image](https://user-images.githubusercontent.com/20632625/192535698-b80ef2d5-3ae7-4787-97d2-153d3ae93fa7.png)

#### Note:
1.It is not a regression.
2.Only repro on MacOS.

**Comment by erdembayar** [comment]
@NuGet/nuget-client 
Same as https://github.com/NuGet/Home/issues/12123#issuecomment-1266300918
This one requires MAC, so hard to repro for me. Based on screenshot I believe it's a valid issue. Could we just accept as `bug` so someone investigate?

**Comment by heng-liu** [comment]
Hi @v-luzh , could you check if there is a local source in the NuGet.Config file, by running "dotnet nuget list source" command?
In the [pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29), step 10, there is a local source `<add key="local" value="../<PackageId>/bin/Debug" />` in the config file. Please check if this line is there. If yes, then pls check if this path is correct (has the testing package).

**Comment by v-luzh** [comment]
Hi @heng-liu, yes, I remember I checked that there was local source in the NuGet.config file and the path of the package was correct.  But we cleared the "testpass" folder after testing on that machine. We will re-verify it during the monthly test this week.

**Comment by v-luzh** [comment]
Hi @heng-liu, This bug doesn't repro during today's testing on .NET SDK 7.0.100-rtm.22511.20. I am closing this bug as not-repro. We will reopen it if repro later.
