### ISSUE TITLE
nuget.exe unit test failure: NuGetPackCommandTest.PackCommand _ReferencedProjectWithDifferentTarget

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1212]
...\NuGet.PackageManagement\test\NuGet.CommandLine.Test\NuGetPackCommandTest.cs(738): error : NuGet.CommandLine.Test.NuGetPackCommandTest.PackCommand
_ReferencedProjectWithDifferentTarget: Attempting to build package from 'proj1.csproj'.\r\nBuilding project 'C:\Users<username hidden>\AppData\Local\Temp\1e230a5a
-652d-4f5e-8f5d-92b9c7ccf74b\proj1\proj1.csproj' for target framework '.NETFramework,Version=v4.0'.\r\n__________________________________________________\
r\nProject "C:\Users<username hidden>\AppData\Local\Temp\1e230a5a-652d-4f5e-8f5d-92b9c7ccf74b\proj1\proj1.csproj" (default targets):\r\n\r\n______________________
____________________________\r\nProject "C:\Users<username hidden>\AppData\Local\Temp\1e230a5a-652d-4f5e-8f5d-92b9c7ccf74b\proj1\proj1.csproj" is building "C:\Use
rs<username hidden>\AppData\Local\Temp\1e230a5a-652d-4f5e-8f5d-92b9c7ccf74b\proj2\proj2.csproj" (default targets):\r\n\r\nC:\Program Files (x86)\MSBuild\14.0\bin\
Microsoft.Common.CurrentVersion.targets(1097,5): error MSB3645: .NET Framework v3.5 Service Pack 1 was not found. In order to target ".NETFramework,Versio
n=v3.0", .NET Framework v3.5 Service Pack 1 or later must be installed.\r\nC:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets
(1097,5): warning MSB3644: The reference assemblies for framework ".NETFramework,Version=v3.0" were not found. To resolve this, install the SDK or Targeti
ng Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note
 that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not
be correctly targeted for the framework you intend.\r\nDone building project "proj2.csproj" -- FAILED.\r\n Failed to build 'proj1.csproj'.\r\n\r\nExpected
: True\r\nActual:   False [C:\nuget\NuGet.PackageManagement\test\NuGet.CommandLine.Test\NuGet.CommandLine.Test.csproj]
C:\nuget\NuGet.PackageManagement\test\NuGet.CommandLine.Test\NuGetPackCommandTest.cs(738): error :    at NuGet.CommandLine.Test.NuGetPackCommandTest.PackC
ommand_ReferencedProjectWithDifferentTarget() in C:\nuget\NuGet.PackageManagement\test\NuGet.CommandLine.Test\NuGetPackCommandTest.cs:line 738 [C:\nuget\N
uGet.PackageManagement\test\NuGet.CommandLine.Test\NuGet.CommandLine.Test.csproj]

**Comment by yishaigalatzer** [comment]
The test fails when 3.5 is not installed on the machine. We don't have to fix it right away

CC @feiling

**Comment by toddm** [comment]
Fixed with the project.json changes.
