### ISSUE TITLE
[Bug]: [Cross-platform Dotnet NuGet Sign] The message “Package(s) signed successfully” lost after signing a package successfully with “dotnet nuget sign” command

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12123]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 7.0.100-rc.1.22431.12

### Worked before?

Worked well on .NET SDK 6.0.400

### Impact

It bothers me. A fix would be nice

#### Repro Steps
1. Execute the [Dotnet nuget sign pre-step](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FDotnet%20nuget%20sign%20pre-step%7C708e56b6-a296-493e-a615-e0e18c55f96f%2F%29&wdorigin=703).
2. On Windows: Create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` (in the powershell "Developer Command Prompt"). 
3. On macOS: Copy the .cer file and the .pfx file from the above Windows machine to macOS machine. 
4. Where <CertificateFilePath> is the file path to the long-lived .cer or .pem file and <VersionedSdkDirectoryPath> is the directory path for the patched versioned .NET SDK directory (e.g.:  ./patchedSDK/sdk/7.0.100), add trust for the certificate: 
    On macOS: ` ./dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> -vsd <VersionedSdkDirectoryPath> `
5. Use the patched "dotnet.exe" to sign a package. Where <PackageFilePath> is the test package path and <PfxFilePath> is the file path to the .pfx file, sign the test package: 
On macOS: ` ./patchedSDK ./dotnet nuget sign <PackageFilePath> --overwrite --certificate-path <PfxFilePath> --certificate-password password -v n`

#### Expected 
There is a message “Package(s) signed successfully” after signing a package successfully.

#### Actual
The message “Package(s) signed successfully” lost after signing a package successfully with “dotnet nuget sign” command on MacBook as below.
![image](https://user-images.githubusercontent.com/20632625/192995784-b870257b-643a-47e1-b7ee-d80863a67ba3.png)
#### Note
1. It is not a regression.

**Comment by erdembayar** [comment]
@NuGet/nuget-client 
This one requires MAC, so hard to repro for me. Based on screenshot I believe it's a valid issue.  Could we just accept as `bug` so someone investigate?

Fyi @dtivel

**Comment by v-luzh** [comment]
It also reproes on Windows/Linux as below screenshot. Users should have message that the package is signed successfully.
![image](https://user-images.githubusercontent.com/20632625/221107463-161dbfce-2276-4feb-b5e2-79a71f179566.png)

**Comment by dtivel** [comment]
The message "Package(s) signed successfully" is logged as an informational message.

NuGet.exe's default verbosity is normal, so you will see this message by default.  You won't see this message if you decrease verbosity (e.g.:  `-Verbosity quiet`).

dotnet.exe's default verbosity is minimal, so you won't see this message by default.  You will see this message if you increase verbosity (e.g.:  `--verbosity normal`).

**Comment by aortiz-msft** [comment]
@v-luzh  - Please see above comment.
