### ISSUE TITLE
[CPM]: Transitive pinning feature should allow for pinning a minimum version

### ISSUE THREAD

**Issue by DJackman123** [NuGet/Home#12125]
### NuGet Product(s) Involved

NuGet.exe, MSBuild.exe

### The Elevator Pitch

Instead of pinning only a specific version of a transitive dependency, we would like to pin a minimum version (or version range) for the package.  That way if a particular dependency tree used a higher version that the pinned version no error would occur, making it easier to maintain the pinned version.

### Additional Context and Details

One of the uses for transitive pinning in Central Package Management will be for avoiding vulnerable versions of packages.  For example, we recently had to update dependencies for Newtonsoft.Json because versions prior to 13.0.1 had a vulnerability.  Using transitive pinning to pin version 13.0.1 for all projects is a great way to make sure none of them pick up a vulnerable version in their respective dependency trees.
However, in the future, when one of our dependencies uses version 13.0.2, the project with that dependency will now get a package downgrade error (NU1109).  Now I have to maintain the pinned version along with my direct dependencies even though none of my projects directly depend on it.  I would prefer to have a way to pin a minimum version (or version range) instead of a specific version of a transitive package.  In other words, a way to tell CPM that Newtonsoft.Json needs to be >= 13.0.1 instead of strictly equal to 13.0.1.

**Comment by erdembayar** [comment]
Fyi @jeffkl

**Comment by jeffkl** [comment]
@DJackman123 I think the reason this is not available today is because what if someone pushes a new version of a "pinned" dependency which causes breaking issues but now your build is automatically upgrading since you have specified that you want any version greater than 13.0.1.

In my opinion, a system like dependabot is a better solution.  When a newer version of a package comes out, you get an automated pull request which runs build validation.  If it passes, you commit the change and that build is now deterministic.  If something ends up breaking at runtime, you can easily revert the change and get back to an older version of the package.  Having NuGet manage the version using a range seems very error prone to me.  What do you think about using automated systems to keep you on the latest versions of packages?

**Comment by DJackman123** [comment]
I think there are couple of different scenarios for transitive pinning and it makes sense to understand the differences between the two.
The first scenario is when I have a package (say CoolLogger) that some of my projects use and some of my dependencies also use.  Transitive pinning makes it easy to have all of my projects be in alignment on the version to use, even if a particular project doesn't use CoolLogger directly.  This could be because a particular version is vulnerable or just to make the projects more consistent when used together.  
What you are describing for maintaining dependency versions makes total sense for this scenario.  However, this is NOT the kind of scenario I am talking about with this feature request.

The second scenario is when there is some other package (say LousyLogger) that _none_ of my projects use but some of my dependencies use.  I find out that a particular version of LousyLogger has a vulnerability and that is the version that my dependencies currently use.  So, I use transitive pinning to force my build to use a later version of the package that doesn't have the vulnerability.  I don't want to maintain a dependency on LousyLogger, because I don't really have a dependency on LousyLogger.  (Extending that idea by bringing in #12128, I also don't want my own packages to have dependencies on LousyLogger--I just want the service that I deploy from my projects to not use the lower, vulnerable version.)
Right now for this scenario the experience is a bit klunky because when I update my actual dependencies and they use a newer version of LousyLogger I get a build failure and the solution to the failure is to remove the PackageVersion for LousyLogger.  

Here is a variation of this scenario: say LousyLogger version 1.0 is the vulnerable version, which was fixed in version 1.1, and now there is also a version 2.0 that has breaking changes (so can't be used by code that was compiled for version 1.x).  One of my projects uses a package that has a dependency on LousyLogger 1.0 and another project uses a package that has a dependency on LousyLogger 2.0.  In this scenario, there isn't a way to use transitive pinning to make the first project bump up the version of LousyLogger to 1.1 while letting the second project move forward with LousyLogger 2.0 without getting package downgrade errors.  I would like for transitive pinning to let me express my true intent here: that version 1.1 is the minimum version that any dependency tree should use, and any higher version is okay.  At the same time, I _don't_ want it to use the latest version available when I run restore (the non-deterministic build).

I think the problem comes from needing to describe transitive pinning concepts using the construct provided for direct dependency version management, and in this scenario transitive pinning needs something different (a means of expression that won't work for direct dependencies).  I have some ideas for how this could be achieved, but I'll wait on that part of the discussion until we're in agreement on the fact that this second scenario exists and should be addressed.

**Comment by erdembayar** [comment]
@jeffkl 
Is it under your radar?

**Comment by jeffkl** [comment]
Yes we're leaving this open to collect upvotes

**Comment by brandon-hurler** [comment]
I think this is an important feature to have. Without it, you are forced into a juggling game with transitive dependencies. I am currently working through the exact same issue with the affected Newtonsoft assembly.

**Comment by jeffkl** [comment]
At this time the design of NuGet is to make restores repeatable and deterministic.  To have a setting in Central Package Management (CPM) to allow for a minimum version means that a package push would alter your restore graph.  If that package had a breaking change, your restore/build could be broken even though you made no changes in your repository.  We don't feel that is a good scenario and would rather push people to use automated systems like Dependabot to keep their package versions updated.  Since these automated systems push a commit, if something goes wrong all you need to do is a revert.  Automatically consuming a new package seems handy but there's no good way to get back into a good state, even if you delete a bad package from a feed.  I'm closing this for now since this idea goes against a fundamental design of NuGet.

**Comment by DJackman123** [comment]
I already pointed out how your last response shows a misunderstanding of what I'm asking for.  The feature as you describe it is not at good idea and goes against a fundamental design of NuGet (so I agree with you on that).  However, the feature that I'm asking for is NOT the feature you are describing in your last response.  Your response shows that you don't yet have a firm grasp on the problem I'm talking about and how NuGet could make life better for its real-world customers.

**Comment by brandon-hurler** [comment]
The original request as I interpreted it is to allow a range, minimum AND maximum that you specify work with your application. This gives you wiggle room for allowing the dependency to "auto update" within the range if an additional dependency enters the project with a higher version than the currently pinned one, but lower than the maximum that will work without breaking changes.

**Comment by jeffkl** [comment]
@DJackman123 I'm going off the original concept in the issue:

> Instead of pinning only a specific version of a transitive dependency, we would like to pin a minimum version (or version range) for the package. That way if a particular dependency tree used a higher version that the pinned version no error would occur, making it easier to maintain the pinned version.

Can you reframe your ask so I understand better?  It sounds like you want NuGet to pin to version 1.1, but then when 1.2 comes out, you want to use that instead?

**Comment by brandon-hurler** [comment]
> @DJackman123 I'm going off the original concept in the issue:
> 
> > Instead of pinning only a specific version of a transitive dependency, we would like to pin a minimum version (or version range) for the package. That way if a particular dependency tree used a higher version that the pinned version no error would occur, making it easier to maintain the pinned version.
> 
> Can you reframe your ask so I understand better? It sounds like you want NuGet to pin to version 1.1, but then when 1.2 comes out, you want to use that instead?

Let's say you have a package A, it has a transitive dependency version 1.1. You have a package B that has the same dependency but version 1.2. 

Version 1.2 gets loaded because you know that your application will work for all 1.x versions up to 2.0 without breaking changes. 

What is being asked for is to be able to pin the allowed range for the transitive dependency to be 1.x-2.0. 

You don't care what specific version it is. As long as the breaking changes are contained between versions, you can take the highest patched version that is compatible.

Edit: adding a missing comma.

**Comment by jeffkl** [comment]
What about moments in time?  So its January 1st, and you want to reference PackageA and PackageB.  Transtively, they pull in DependencyX version 1.0 and 1.1 repectively.

On February 1st, DependencyX 1.0 and 1.1 are found to have a vulnerability, so DependencyX version 1.2 is pushed with a fix.  But PackageA and PackageB aren't updated.  So you commit a change to your repository to pin DependencyX to 1.2, bypassing the transitive dependencies.

On March 1st, a new version of DependencyX is pushed, version 1.3.  At the same time, a new PackageA is pushed which consumes DependencyX 1.3.  You update your repository with a commit to get a new version of PackageA, but DependencyX 1.2 is pinned, so you're still consuming that.

It sounds like you're asking NuGet to pin a version, unless you specify an allowable range, like 1.x-2.0.  So when you update PackageA on March 1st, you'll be getting a newer version of DependencyX.  You could just unpin DependencyX when you update PackageA, or some automated system that keeps your packages up-to-date could do that.  There's also no good way to know that 1.3 doesn't have a new vulnerability.  To me, pinning is a way of you conveying to NuGet that you don't trust the transitive graph.  You still need a commit that brings in newer transitive versions so you might as well unpin when you do that. 
 A range like 1.x-2.0 doesn't help when I updated to 3.0 and forget to unpin.  Some of these packages are never even updated so you don't always get the update anyway.  

I still believe an automated system that sends pull requests which run a validation build is a better solution to keeping your packages up to date.  You have commits in your code base that record the versions used at restore time.  Version ranges introduce non-determinism in your restore that not always obvious.  If convenience is a priority, automation seems like the much better answer in my opinion.

**Comment by brandon-hurler** [comment]
> What about moments in time? So its January 1st, and you want to reference PackageA and PackageB. Transtively, they pull in DependencyX version 1.0 and 1.1 repectively.
> 
> On February 1st, DependencyX 1.0 and 1.1 are found to have a vulnerability, so DependencyX version 1.2 is pushed with a fix. But PackageA and PackageB aren't updated. So you commit a change to your repository to pin DependencyX to 1.2, bypassing the transitive dependencies.
> 
> On March 1st, a new version of DependencyX is pushed, version 1.3. At the same time, a new PackageA is pushed which consumes DependencyX 1.3. You update your repository with a commit to get a new version of PackageA, but DependencyX 1.2 is pinned, so you're still consuming that.
> 
> It sounds like you're asking NuGet to pin a version, unless you specify an allowable range, like 1.x-2.0. So when you update PackageA on March 1st, you'll be getting a newer version of DependencyX. You could just unpin DependencyX when you update PackageA, or some automated system that keeps your packages up-to-date could do that. There's also no good way to know that 1.3 doesn't have a new vulnerability. To me, pinning is a way of you conveying to NuGet that you don't trust the transitive graph. You still need a commit that brings in newer transitive versions so you might as well unpin when you do that. A range like 1.x-2.0 doesn't help when I updated to 3.0 and forget to unpin. Some of these packages are never even updated so you don't always get the update anyway.
> 
> I still believe an automated system that sends pull requests which run a validation build is a better solution to keeping your packages up to date. You have commits in your code base that record the versions used at restore time. Version ranges introduce non-determinism in your restore that not always obvious. If convenience is a priority, automation seems like the much better answer in my opinion.

While this is a valid point, it doesn't address the security issue itself that the post is about. The current implementation will allow security flaws to exist without having a process to regularly audit all dependencies. Furthermore, if one exists, you have to specify that version to be used explicitly rather than allowing transitive pinning.

Is there a better alternative solution than either of the two options being discussed? It may need a third idea.

**Comment by DJackman123** [comment]
90% of the time when I would use the transitive pinning feature I would be doing it to prevent using a known vulnerable version of a package.  The feature as it is implemented now will work, but could work better to support this scenario.  It does what it needs to in the moment, but makes the future more cumbersome.

Think of it this way: on February 1st, when I learn that DependencyX version 1.0 and 1.1 have vulnerabilities but PackageA isn't updated yet, I don't really want to tell NuGet to use version 1.2 instead.  What I _really_ want to say is don't use version 1.0 or 1.1.  The easiest way to say this would be to "pin" version 1.2 (the known fixed version) or anything higher than that.  (Hence, my original request: allow for pinning a minimum version.)  I would never use a range like 1.x-2.0.  I am not managing which versions of DependencyX that PackageA can use--that's PackageA's problem.  I just want to prevent known vulnerable versions from being used.

The current implementation works fine until March 1st, and at the moment I update my project to use the new PackageA that wants DependencyX version 1.3, I get build failures because I had to pin version 1.2.  The solution to this is to remove the pin at that point.  I know this, but unfortunately the hundreds of developers in my product group don't know this and they send frantic messages at all hours asking me to help them fix their project because it just stopped building.  If I could tell transitive pinning that 1.0 and 1.1 are bad, but 1.2 and 1.3 (and everything higher) is good, then the build failure would never happen.  Sure, it wouldn't be necessary after March 1, but it wouldn't cause any problems if it stayed there for a few more days (or years, for that matter).

That is what I'm asking for.  This is the scenario that comes up 90% of the time.  Make transitive pinning work better for this scenario so it can be a great solution for this scenario (fix it now and never worry again) instead of just an okay solution (fix it now, pay for it later).

**Comment by doxxx** [comment]
Perhaps transitive pinning has its place, but I agree that there is need for a way in CPM to specify that package X should be at least this version or higher while still being subject to the version constraints as determined by the dependency graph. This isn't pinning -- it's an _additional_ minimal constraint.

**Comment by voroninp** [comment]
@doxxx, I think this [issue](https://github.com/NuGet/Home/issues/5553) is what we actually need.

**Comment by doxxx** [comment]
@voroninp Over a year later, I'm struggling to remember the context for my comment, but as I understand it the issue you link is more about being able to choose whether a minimal or maximal version selection strategy is used. I still want a minimal version selection strategy but I want to specify an _additional_ minimum version constraint on a transitive package without needing to declare a direct dependency. For me, this would mainly be useful for fixing package vulnerability warnings where the vulnerable package is not a direct dependency.

**Comment by voroninp** [comment]
@doxxx , but won't we get this with transitive pinning, range constraints, and resolve highest available?

`Version="[MinimalMajor.Minor.Patch, MinimalMajor+1)" ResolutionStrategy="HighestVersion" />`

**Comment by doxxx** [comment]
@voroninp Ah, yeah, sure that would do it. I missed that when scanning the issue.
