### ISSUE TITLE
[Bug]: Global.json is not  picked up by `NuGetSdkResolver` when using Microsoft.Build API

### ISSUE THREAD

**Issue by hknielsen** [NuGet/Home#12139]
### NuGet Product Used

Other/NA

### Product Version

Microsoft.Build nuget package

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Using MsBuild on a `sln` file having a `Global.json` file, specifying the `msbuild-sdks` tag is picked up as expected.

Using `Microsoft.Build` nuget package to build does not.

The reason is that MsBuild.exe internal generates a .proj file, instead of the sln file. This is how the ProjectPath to the NuGetSdkResolver is invoked, and by that the `Global.json` is picked up.

We need a way to specify the location of `Global.json`. ie. GlobalProperty, or an environment variable.

Repro steps:
Using MSBuildLocator
`MSBuildLocator.RegisterDefaults();`

Parsing a Solution file `SolutionFile.Parse`
And traversiong the ProjectsInSolution, to create Projects.
Of the creating of 
`var Project = new Project(projectPath, globalProperties, projectCollection.DefaultToolsVersion, projectCollection);`
Will go over the SDKResolvers, and try resolving with `NuGetSdkResolver`, this then does not have the path to the sln, but the project in the sln.

**Comment by jeffkl** [comment]
The NuGet-based MSBuild project SDK resolver looks next to the solution file first and the project path second.  Are the projects in the same directory structure as the solution file? 

This should work if:
* There is no solution file and `global.json` is next to or in a directory above
* The project is in a directory below the solution file and `global.json` is next to or above the solution file

When MSBuild builds a solution file, it sets global properties for the projects so other tooling knows where the solution file is, are you setting them?

https://github.com/dotnet/msbuild/blob/20ce296d6b3f4e63a511321c7e1a2f69a4ee63ef/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L65

**Comment by hknielsen** [comment]
> When MSBuild builds a solution file, it sets global properties for the projects so other tooling knows where the solution file is, are you setting them?
> 
> https://github.com/dotnet/msbuild/blob/20ce296d6b3f4e63a511321c7e1a2f69a4ee63ef/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L65

I was setting `SolutionDir` but that was not enough I see now :) Setting `SolutionPath` and `BuildingSolutionFile` specifically fixed it!

I see that it is indeed using the global properties 😅 
```
        internal static string GetStartingPath(SdkResolverContext context)
        {
            if (context == null)
            {
                return null;
            }

            if (!string.IsNullOrWhiteSpace(context.SolutionFilePath))
            {
                return context.SolutionFilePath;
            }

            if (!string.IsNullOrWhiteSpace(context.ProjectFilePath))
            {
                return context.ProjectFilePath;
            }

            return null;
        }
```

Thank you!!
