### ISSUE TITLE
Install-Package : Dependency loop detected for package 'Microsoft.Data.SqlClient'.

### ISSUE THREAD

**Issue by SqlBenjamin** [NuGet/Home#12133]
I continue to get the error "Install-Package : Dependency loop detected for package 'Microsoft.Data.SqlClient'." when trying to install the package Microsoft.Data.SqlClient in PowerShell. I've seen a couple issues that reference this but they're closed and yet I'm still not able to install the package successfully.

**Comment by nkolev92** [comment]
Hey @SqlBenjamin, 

We need some more info to the able to investigate here. 
Loops are usually a consequence of a package graph. 

Are you using the NuGet Package Manager Console in Visual Studio or something else? 
I imagine this is in the project context? What kind of projects are using? Do you have any other packages?
Most dependency loop we see tend to be true positives, so we'd need a repro to make progress. 

Thanks!
