### ISSUE TITLE
getting https://api.nuget.org/v3/index.json instead of the package

### ISSUE THREAD

**Issue by shayhatsor** [NuGet/Home#1213]
when i try to download some packages, i get https://api.nuget.org/v3/index.json instead of the package.
some examples:
https://www.nuget.org/packages/ZooKeeperNetEx/
https://www.nuget.org/packages/ZooKeeperNet/
https://www.nuget.org/packages/Microsoft.Experimental.Azure.ZooKeeper/0.4.0-alpha

**Comment by maartenba** [comment]
This has been resolved. We recommend clearing NuGet cache (%LOCALAPPDATA%\NuGet\Cache).
