### ISSUE TITLE
[Bug]: dotnet list vulnerable include transitive fails to report System.Text.Encodings.Web v4.7.1 as vulnerable

### ISSUE THREAD

**Issue by snakefoot** [NuGet/Home#12132]
### NuGet Product Used

dotnet.exe

### Product Version

6.0.400

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Clone repo to local machine: https://github.com/JDetmar/NLog.Extensions.AzureStorage
2. Open Command Prompt and run this command:
```
dotnet list ./src package --vulnerable --include-transitive
```
3. Fails to report solution depends on [System.Text.Encodings.Web v4.7.1](https://www.nuget.org/packages/System.Text.Encodings.Web/4.7.1) marked as vulnerable.

P.S. Also tried changing `NLog.Extensions.AzureBlobStorage.Tests` to have targetframework=net48, but still no report of it being vulnerable..

### Verbose Logs

```shell
Project `NLog.Extensions.AzureBlobStorage` has the following vulnerable packages
   [netstandard2.0]:
   Transitive Package                    Resolved   Severity   Advisory URL
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj

The given project `NLog.Extensions.AzureBlobStorage.Tests` has no vulnerable packages given the current sources.
Project `NLog.Extensions.AzureQueueStorage.Tests` has the following vulnerable packages
   [netcoreapp3.1]:
   Transitive Package                    Resolved   Severity   Advisory URL
   > Newtonsoft.Json                     9.0.1      High       https://github.com/advisories/GHSA-5crp-9r3c-p9vr
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
```

Would expect with `--include-transitive` that it would report that [System.Text.Json v4.7.2](https://www.nuget.org/packages/System.Text.Json/4.7.2#dependencies-body-tab) depends on vulnerable version [System.Text.Encodings.Web v4.7.1](https://www.nuget.org/packages/System.Text.Encodings.Web/4.7.1):

> NLog.Extensions.AzureBlobStorage@3.1.1 › Azure.Storage.Blobs@12.13.0 › System.Text.Json@4.7.2 › System.Text.Encodings.Web@4.7.1
```

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 
Looks actual issue. Considering I'm already working on this code path I assigned to myself. What is the priority of this issue?

**Comment by nkolev92** [comment]
Please double check against `dotnet list package --include-transitive`. 

Ensure that System.Text.Encodings.Web 4.7.1 is what actually gets resolved

**Comment by erdembayar** [comment]
> Please double check against `dotnet list package --include-transitive`.
> 
> Ensure that System.Text.Encodings.Web 4.7.1 is what actually gets resolved

Yes, it gets resolved in transitive dependencies but not shown in vulnerable list. Maybe I can quickly check what is cause the this when I resume working on `Machine readable output` work.

**Comment by snakefoot** [comment]
Sorry about this. Can see there are 2 dependency chains:

> NLog.Extensions.AzureBlobStorage@3.1.1 › Azure.Storage.Blobs@12.13.0 › System.Text.Json@4.7.2 › System.Text.Encodings.Web@4.7.1

But there is also this dependency-chain:

> NLog.Extensions.AzureBlobStorage@3.1.1 › Azure.Storage.Blobs@12.13.0 › Azure.Storage.Common@12.12.0 › Azure.Core@1.25.0 > System.Text.Encodings.Web@4.7.2

Closing the issue as user-error.
