### ISSUE TITLE
[Bug]: The “NuGetRecommender” still shows in the “Installed” tab of “Manage Extensions” after being uninstall and it can be uninstalled successfully for multiple times

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12145]
### NuGet Product Used

Other/NA

### Product Version

Release-6.2.x\6.2.1.25

### Repro Steps & Context

1.	Open VS, click menu File->New Project, create a Console App (.Net Core) project.
2.	Click the menu: Extensions ->Manage Extensions ->Installed.
3.	Uninstall “NuGetRecommender”.
4.	Restart VS and reopen “Manage Extensions” dialog.

#### Expected
The “NuGetRecommender” will not show in the “Installed” tab of “Manage Extensions” after being uninstall.

#### Actual
The “NuGetRecommender” still shows in the “Installed” tab of “Manage Extensions” after being uninstall and it can be uninstalled successfully for multiple times.
![image](https://user-images.githubusercontent.com/20632625/194752980-8bcb1809-0f8b-472a-9ac2-d26141ffcc26.png)
#### Note
1.	It seems not a regression since it’s a new PR change.
2.	This issue reproes on D16.11\33005.80 + NuGet Client Release-5.11.x\5.11.2.23, D17.0\33005.84 + NuGet Client Release-6.0.x\6.0.2.26 and D17.2\33005.85 + NuGet Client Release-6.2.x\6.2.1.25.

**Comment by nkolev92** [comment]
This is something that should be fixed in latest VS, https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1586335. 

The extension does not appear in latest VS version. 

Closing now, please reopen if you see anything in 17.5, and I'll reach out the recommender component team.
