### ISSUE TITLE
[Bug]: Starred packages still show in the “Browse” tab after disabling the NuGetRecommender

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12144]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Release-6.2.x\6.2.1.25

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	Open VS, click menu File->New Project, create a Console App (.Net Core) project.
2.	Open Manager Extensions (Extensions ->Manage Extensions ->Installed).
3.	Click the “Disable” button on the right of “NuGetRecommender” when hovering on.
4.	Restart the previous project and open NuGet Package Manager UI.
#### Expected:
There is no starred package showing in the “Browse” tab since the feature is disabled.
#### Actual:
There are still starred packages showing in the “Browse” tab as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/194752211-3379d667-9210-4f99-8c1a-252818137195.png)
#### Note:
1. It seems not a regression since it's a new PR change.
2. This issue reproes on D16.11\33005.80 + NuGet Client Release-5.11.x\5.11.2.23, D17.0\33005.84 + NuGet Client Release-6.0.x\6.0.2.26 and D17.2\33005.85 + NuGet Client Release-6.2.x\6.2.1.25.

**Comment by nkolev92** [comment]
We don't want to invest into this. 
The disable feature is going to disabled in the latest version of the extension.
