### ISSUE TITLE
[Bug]: Starred packages still show in the “Browse” tab after uninstalling the NuGetRecommender

### ISSUE THREAD

**Issue by v-crchang** [NuGet/Home#12143]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Release-6.0.x\6.0.2.26

### Impact

It bothers me. A fix would be nice

## Repro steps:  
1. Open VS, click menu File->New Project, create a Console App (.Net Core) project. 
2. Open Manager Extensions (Extensions ->Manage Extensions ->Installed). 
3. Uninstall “NuGetRecommender”. 
4. Restart the previous project, open NuGet Package Manager UI.

## Expected: 
There is no starred package showing in the “Browse” tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/194750382-ed4c3935-9a42-4a83-aa3c-67c3b60df0a1.png)
## Actual: 
There are still starred packages showing in the “Browse” tab as below screenshot.
![image](https://user-images.githubusercontent.com/71433406/194750405-341eeb6c-977f-43b9-8df9-024bdc29282e.png)

## Notes:
1. This issue reproes on D17.0\33005.84 + NuGet Client Release-6.0.x\6.0.2.26 and D17.2\33005.85 + NuGet Client Release-6.2.x\6.2.1.25.
2. It does not reproes on D16.11\33005.80 + NuGet Client Release-5.11.x\5.11.2.23.

**Comment by nkolev92** [comment]
At this point, we're choosing not to address these. 

The uninstall option for the extension has been disabled in latest VS.
