### ISSUE TITLE
Too many automatic redirections were attempted - NuGet Package restore failed?

### ISSUE THREAD

**Issue by drmcclelland** [NuGet/Home#1214]
I have pulled code from GitHub (https://github.com/ilich/MvcReportViewer), which contains a C# project which I would like to reference in my application.  I've added it to my solution in VS2013, and notice this message at the top of the "Manage NuGet Packages" dialog:

![image](https://cloud.githubusercontent.com/assets/6124858/9355130/c477443a-463b-11e5-8879-a5aed84fe19f.png)

So, I happily click the "Restore" button, and the dialog displays "Downloading missing packages..." for about 5 seconds, then I get this cryptic error message:

```
An error occurred while trying to restore packages:  Too many automatic redirections were attempted.
```

I am trying to figure out how to diagnose this error message - is this a network issue, or a problem with the way the packages are being referenced in the source code itself?

I am running Visual Studio 2013 Ultimate with Update 5, and NuGet version 2.8.60723.765.

**Comment by maartenba** [comment]
This has been resolved. We recommend clearing NuGet cache (%LOCALAPPDATA%\NuGet\Cache).
