### ISSUE TITLE
[Bug]: SettingsLoadingContext throws exceptions when a different settings file causes an exception

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12154]
### NuGet Product Used

MSBuild.exe

### Product Version

All

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The `SettingsLoadingContext` class adds a `Lazy<T>` to a list and then returns the value.  If reading that file causes an exception, subsequent calls to `SettingsLoadingContext` also cause an exception for a different file since the list is enumerated for each call.

https://github.com/NuGet/NuGet.Client/blob/493d6b38484377e8c4d713d960097b97ce3ba4e9/src/NuGet.Core/NuGet.Configuration/Settings/SettingsLoadingContext.cs#L41-L47

This line throws for a different file because `_settingsFiles[i].Value` is accessed:
```c#
if (PathUtility.GetStringComparerBasedOnOS().Equals(_settingsFiles[i].Value.ConfigFilePath, filePath))
```

**Comment by zivkan** [comment]
Out of curiosity, what's a customer scenario where this is impacted?

**Comment by jeffkl** [comment]
> Out of curiosity, what's a customer scenario where this is impacted?

I think if you have bad XML in one NuGet.config and are doing a restore with multiple configs in the mix, you'll get an error about the bad NuGet.config during a different project which is confusing.  I only caught this in a unit test when fixing https://github.com/NuGet/Home/issues/12152
