### ISSUE TITLE
nuget package list is always scrolled one item down

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#12160]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-Search-results-on-Nuget/10163787)._

Another, [Closed as duplicate on Developer Community](https://developercommunity.visualstudio.com/t/nuget-package-list-is-always-scrolled-on/10170793)

---
When searching for a nuget package (or just browsing) the list is always scrolled 1 item down (see the screenshot) hiding the top result, which is very confusing.

![image.png](https://aka.ms/dc/image?name=B0fcf14b32c7845a18e58ba4fd5099e08638011791712462035_20221012-164609-image.png&tid=0fcf14b32c7845a18e58ba4fd5099e08638011791712462035)

---
#### Feedback Bot on 12/10/2022, 07:21 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dominoFire** [comment]
Reproduced in VS 17.3.6 Release, see section in red.

![image](https://user-images.githubusercontent.com/1192347/195745262-b43eb1db-8416-4d7c-b03d-087f2bf8d9e2.png)

**Comment by nkolev92** [comment]
We need to understand if this is a regression.

**Comment by dominoFire** [comment]
Not a regression. The scroll bar bug is also visible in Visual Studio 2019 16.11.20


![scroll-visual-studio-2019](https://user-images.githubusercontent.com/1192347/196290168-3044a868-6889-4573-adff-ca2cc8ca5899.png)

**Comment by nkolev92** [comment]
dev com issue: https://developercommunity.visualstudio.com/t/VS2022-Search-results-on-Nuget/10163787

**Comment by alex-jitbit** [comment]
another report on deves community: https://developercommunity.visualstudio.com/t/nuget-package-list-is-always-scrolled-on/10170793

**Comment by erdembayar** [comment]
Another dup https://developercommunity.visualstudio.com/t/Nuget-Package-Manager-not-starting-out-s/10205297

**Comment by nkolev92** [comment]
Matching the AzDO priority.

**Comment by joelverhagen** [comment]
This has been encountered by another user on Twitter: https://mobile.twitter.com/rickvdbosch/status/1597890237946269696

**Comment by rickvdbosch** [comment]
Just like @joelverhagen [mentioned above](https://github.com/NuGet/Home/issues/12160#issuecomment-1332102480), I have this issue too. I can see it in these two versions:

* Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview, Version 17.5.0 Preview 1.0
* ~Microsoft Visual Studio Enterprise 2022 (64-bit) - Current, Version 17.4.1~
* Microsoft Visual Studio Enterprise 2022 (64-bit) - Current, Version 17.4.2

It happens when searching for packages where the resulting list is larger than the available screen size. Besides that, the search term doesn't matter.

**Comment by donnie-msft** [comment]
**Status update**: I was able to repro this problem at least back to 16.11 (~1 year old problem, at least) on Browse & Updates tab, and I think Installed tab as well. Unfortunately, I didn't figure out exactly what's causing that behavior, yet. My current guess is that WPF is measuring the `ListBox` before we add items on background threads, which then moves the `ScrollBar`.

Unless I missed something obvious (👀 always welcome!), doesn't seem there's any quick fix. Will spend more time on it in the coming days and hopefully get at least some improvement out soon.

**Comment by donnie-msft** [comment]
After reaching out to the WPF team, it seems this is a known issue introduced into an update to WPF. The fix will come in a Windows update soon, but in the meantime you can workaround the problem by adding the switch below to your `devenv.exe.config` (eg, `C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\devenv.exe.config`). Tip: don't forget Admin privileges will be needed to save this file (ie, make sure it really saves). Restart VS and the problem should be gone.

> This issue originates in WPF and is a known regression. We have made the appropriate changes to fix this issue and will be rolled out in future .NET Framework releases. Meanwhile, there is a workaround available for this :
> 
> Setting the following flag in the application config will resolve the issue :
> 
```
 <runtime>
 <AppContextSwitchOverrides value=“Switch.System.Windows.Controls.VirtualizingStackPanel.OptOutOfCollectionChangeFix=true”/>
 </runtime>
```

You may not encounter this issue if you don't have the Windows update installed which caused this regression ( KB5017856, KB5017857 and so on ).
