### ISSUE TITLE
[Bug]: Method not found exception while nuget pack

### ISSUE THREAD

**Issue by PiterGoCompany** [NuGet/Home#12165]
### NuGet Product Used

NuGet.exe

### Product Version

msbuild version '17.3.1.41501'
nuget CLI version 6.3.1.1

### Worked before?

works on vs 2019 and msbuild  version 16.11.2.50704

### Impact

I'm unable to use this version

### Repro Steps & Context

When running command 'nuget pack' with default msbuild 17.3 I always get method not found exception 'System.ReadOnlySpan`1<Char> Microsoft.IO.Path.GetFileName(System.ReadOnlySpan`1<Char>)'.

**Comment by jeffkl** [comment]
Possibly related to https://github.com/NuGet/Home/issues/12137

**Comment by nkolev92** [comment]
I'm unable to reproduce this with 6.3.1 and latest VS 17.3. 

I wonder if there's something else we're missing.

Can you repro this on any other machines @PiterGoCompany? 

I'm guessing it's the same root cause as #12137 too.

**Comment by PiterGoCompany** [comment]
@nkolev92 today I'm out of office, so I'll try on Thursday.

**Comment by PiterGoCompany** [comment]
@nkolev92 does your command nuget pack really pick msbuild 17.3 version or 16.11? On my machine msbuild command is pointing to VS2022 folder. One of my coworkers also has VS 2019 and VS 2022 installed next to each other, but on his machine msbuild is pointing to VS2019 folder.

**Comment by zivkan** [comment]
This seems related: https://github.com/dotnet/msbuild/issues/7873

**Comment by nkolev92** [comment]
@PiterGoCompany Yep, I used `-MSBuildVersion` to achieve that. 

Given the multiple reports, I'm sure we'll be able to investigate this further.

**Comment by nkolev92** [comment]
Team Triage: 
The suggestion in the MSBuild issue to update the version of MSBuild NuGet references. 
Updating that version is likely to have new versions of NuGet.exe fail to work with older (dev16?, dev17.2?) versions of MSBuild. 
However, not fixing the issue means that new versions of NuGet.exe do not work with newer versions of MSBuild.exe (17.3+).

**Comment by jeffkl** [comment]
I can't reproduce this anymore after https://github.com/NuGet/NuGet.Client/pull/4975, if anyone still experiences this issue, please let me know how and I'll reopen this issue.

**Comment by backlash1897** [comment]
I have the issue with NuGet Version 6.4.0.123 & MSBuild 17.5.1.16304

**Comment by nkolev92** [comment]
@backlash1897 

The milestone for the fix is 6.5, and you're still using 6.4 version of NuGet.

**Comment by backlash1897** [comment]
@nkolev92 I missed that, but after upgrade to version 6.5.0.154 same problem.
I am trying to pack .csproj with target .NET Framework 4.8
