### ISSUE TITLE
Packages.config restore does not retry on 5xx status codes from V2 sources

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1217]
Restoring a packages.config project from V2 will fail if a 503 status code is returned by the server during a call to FindPackagesById or the package download endpoint.

NuGet.Core should retry in these scenarios.

RestoreRetry_PackagesConfigRetryOnFailingV2Source should be re-enabled after fixing this.

**Comment by emgarten** [comment]
This is fixed now that all V2 http requests are made through HttpSource and the retry handler.

**Comment by joelverhagen** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249)
