### ISSUE TITLE
[DCR]: Producing Multiple Related NuGet Packages from a Single Git Repo

### ISSUE THREAD

**Issue by jcoburn** [NuGet/Home#12179]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

using data from
Producing Multiple Related NuGet Packages from a Single Git Repo
https://markheath.net/post/multiple-nuget-single-repo

md MultiPackageLibrary
cd MultiPackageLibrary
dotnet new classlib -o LibraryA
dotnet new classlib -o LibraryB
dotnet new solution
dotnet sln add LibraryA
dotnet sln add LibraryB
dotnet add LibraryA reference LibraryB

Let's create an interface in LibraryB...
namespace LibraryB
{
    public class IMyInterface
    {
    }
}

.and a concrete implementation of it in LibraryA:

using LibraryB;
namespace LibraryA
{
    public class MyClass : IMyInterface
    {
    }
}
dotnet pack -c Release
This will create LibraryA.1.0.0.nupkg and LibraryB.1.0.0.nupkg.

checking the dependencies from the nuspec file from the nupkg, we get

dependency id="libraryB" version="1.0.0" exclude="Build,Analyzers" 

### Desired Behavior

need a way to be able to generate a dependency range.
i.e.
dotnet pack -c Release ???

so that dependency becomes
dependency id="libraryB" version="[1.0.0, 2.0.0)" exclude="Build,Analyzers"

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/5556. 

There are some workarounds available.
