### ISSUE TITLE
[Bug]: Static graph-based restore fails with a NullReferenceException during SetPlatform negotiation

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12177]
### NuGet Product Used

MSBuild.exe

### Product Version

17.3

### Worked before?

17.2

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Have a set of projects that use SetPlatform which is a new feature of MSBuild 17.3
2. Run restore with static graph enabled (`RestoreUseStaticGraphEvaluation`)
3. `NuGet.Build.Tasks.Console.exe` encounters an unhandled `NullReferenceException`

This is caused by a [new code path](https://github.com/dotnet/msbuild/commit/73d331a1b9758315978432f21de46cfcc8e948c3#diff-9b91245ea02bf3f1b2f41dab3457efc0960ebf27fbf4b6a331cedd87d45f7583R115) in MSBuild for SetPlatform negotiation.

https://github.com/dotnet/msbuild/blob/3ed9e807c5c6dfc86d54ca4b5c068758583b8f6c/src/Build/Graph/ProjectInterpretation.cs#L115

NuGet's static graph restore does not expect the global properties collection to be `null`

https://github.com/NuGet/NuGet.Client/blob/10ce64e63bb15f5fed2f39aa129f70fb370d106a/src/NuGet.Core/NuGet.Build.Tasks.Console/MSBuildStaticGraphRestore.cs#L940

![image](https://user-images.githubusercontent.com/17556515/197020437-db023d10-6ea5-430a-bb6c-150d97c6939e.png)

**Comment by AArnott** [comment]
@jeffkl when should we expect to see this fixed in dogfooding? I still see this fail regularly in IntPreview builds when using the .NET 7 SDK.

**Comment by jeffkl** [comment]
It looks like it went into the SDK here: https://github.com/dotnet/installer/commit/a9388a7704dac5cfb81ff889253ec26e4f2896a9

I would expect to start seeing .NET SDK 7.0.2xx soon in IntPreview builds?
