### ISSUE TITLE
[Bug]: Versions_SelectionChanged throws NullReferenceException when changing selected package

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#12184]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.5 Preview 1.0 33023.41.main

### Impact

Other

### Repro Steps & Context

I don't see any direct customer impact from this, but when changing selected version, the debugger shows exceptions being thrown from `Versions_SelectionChanged` due to `null` value in the AddedItem[0] element (see https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/ProjectView.xaml.cs#L279)

1. Attach a debugger.
2. Launch Project PM UI.
3. Change selected packages.
4. Observe the NRE.

![image](https://user-images.githubusercontent.com/49205731/197612110-6c4fde03-4c62-403c-8c38-7a88bd20efc9.png)

**Comment by dominoFire** [comment]
Dupe of https://github.com/NuGet/Client.Engineering/issues/1912

**Comment by jebriede** [comment]
In addition to handling the null value for the element at AddedItems[0], we should use AddedItems.Any() instead of AddedItems.Count > 0;

**Comment by zivkan** [comment]
@jebriede I disagree. `AddedItems.Count > 0` is zero allocation, where as `AddedItems.Any()` is LINQ and therefore creates an enumerator which is non-zero allocation (although due to `System.Collections.Generic.List<T>`'s implementation it's a stack allocation, not a heap allocation. But that's only one data type)

**Comment by martinrrm** [comment]
Assigning it to myself since I'll be working in Version combobox this Quality week

**Comment by jebriede** [comment]
@zivkan, you're right, thanks for catching that. I made my comment thinking of a different scenario. In this case, it's referencing the property Count which is indeed more efficient than using Any().

**Comment by jebriede** [comment]
The fix in https://github.com/NuGet/NuGet.Client/pull/4935 still attempts to dereference `AddedItems[0]` by calling `.Equals` on it, resulting in an NRE. Reopening the bug to address the issue and prevent the NRE.
