### ISSUE TITLE
Powershell Install-Package: Dependency loop detected for package 'MailKit'.

### ISSUE THREAD

**Issue by irm-phoudek** [NuGet/Home#12183]
### NuGet Product Used

I don't know. NuGet via PowerShell "Install-Package" function

### Product Version

PowerShell 7.1.3

### Impact

I'm unable to use this version

### Repro Steps & Context

When I try to install "MailKit" Package in Powershell via:
`Install-Package -Name MailKit -Force -Source "https://www.nuget.org/api/v2"`
I receivce this error:
```
Install-Package : Dependency loop detected for package 'MailKit'.
In Zeile:28 Zeichen:1
+ Install-Package -Name Mailkit -Force -Source "https://www.nuget.org/a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (MailKit:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

Seems like this error is caused by a false loops with .NETStandard 1.0:
1. NETStandard.Library ->  System.Security.Cryptography.X509Certificates -> System.Security.Cryptography.Cng ->  System.Formats.Asn1 - > System.Memory ->  System.Numerics.Vectors -> (back to start)
2. NETStandard.Library -> System.Security.Cryptography.X509Certificates -> System.Security.Cryptography.Cng ->  System.Formats.Asn1 - >  System.ValueTuple -> (back to start)
3. NETStandard.Library -> System.Net.Http -> System.Security.Cryptography.X509Certificates -> (see 1./2.)
4. NETStandard.Library -> System.Net.Http -> System.Diagnostics.DiagnosticSource -> System.Memory -> (see 1.)
5. NETStandard.Library -> System.Net.Http -> System.Security.Cryptography.OpenSsl -> System.Formats.Asn1 -> (see 1./2.)

How can I solve this problem? I tried different PowerShell-Versions and also tried manuall install the required packages:
# the dependency packages without a loop first:
```
Install-Package -Name Portable.BouncyCastle -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Data.DataSetExtensions -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Security.Cryptography.Algorithms -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Threading.Tasks.Extensions -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Buffers -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Runtime.CompilerServices.Unsafe -Force -Source "https://www.nuget.org/api/v2"
Install-Package -Name System.Runtime.Handles -Force -Source "https://www.nuget.org/api/v2"
```

# the dependency packages with loop issue one by one:
```
Install-Package -Name System.Numerics.Vectors -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.Memory -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.ValueTuple -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.Formats.Asn1 -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.Text.Encoding.CodePages -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.Security.Cryptography.Cng -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name System.Security.Cryptography.Pkcs -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name MimeKit -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
Install-Package -Name MailKit -Force -Source "https://www.nuget.org/api/v2" -SkipDependencies
```

But seams like something is missing.

**Comment by kartheekp-ms** [comment]
As mentioned in [NuGet ](https://learn.microsoft.com/en-us/nuget/reference/powershell-reference), `The commands listed here are specific to the Package Manager Console in Visual Studio, and differ from the Package Management module commands that are available in a general PowerShell environment`.

I am not able to reproduce the issue in Visual Studio -> NuGet Package Manager Console. A similar issue was reported to the package author in https://github.com/jstedfast/MimeKit/issues/826, please refer to that issue for further instructions. If that doesn't help to solve your problem, please create an issue in https://github.com/PowerShell/PowerShell/issues/new/choose repo.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/52756182/200090318-3e155844-fdd9-48ea-a935-20a608ea00f7.png">
