### ISSUE TITLE
[Bug]: The scroll bar is not located at the top of package list in “Browse” and “Updates” tab of PM UI by default

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12182]
### NuGet Product Used

PM UI

### Product Version

NuGet Client Dev\6.5.0.35

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Create a C# Console App (.Net core) project.   
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.   
3. Go to "Browse" tab and observe the scroll bar.
#### Expected:
The scroll bar should be at the top in “Browse” tab.
#### Actual:
The first package cannot be seen before scrolling up the scroll bar as below screenshot.
 
![image](https://user-images.githubusercontent.com/40230425/197484491-1f4c6f98-176c-4156-976c-307f019849e3.png)

#### Notes: 
1.The issue starts from Dev\6.5.0.14.
2.It also reproes in “Updates” tab.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/12160
