### ISSUE TITLE
nuget.exe list -AllVersions does not list all the versions

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1219]
nuget.exe list -AllVersions does not list all the versions
1. Run nuget.exe list Newtonsoft.Json -Source https://www.nuget.org/api/v2 -AllVersions

Expected:
All versions of Newtonsoft.Json are listed in the result

Actual:
Only the latest version of Newtonsoft.Json is listed in the result

**Comment by eatdrinksleepcode** [comment]
Is anyone working on this? It's a little mind-boggling that this hasn't worked for at least 9 months and (apparently) no progress has been made.

**Comment by scovetta** [comment]
This is also broken in 4.0.0.2283.

**Comment by jairbubbles** [comment]
There is a duplicate issue here which seems to get more activity: https://github.com/NuGet/Home/issues/4537

**Comment by nkolev92** [comment]
Closing this in favor of https://github.com/NuGet/Home/issues/4537
The codepath that was being hit here is not hit in the post-4.0 versions anymore. 

In addition nuget.org allversions in particular has a server-side bug as well.
https://github.com/NuGet/NuGetGallery/issues/3274
