### ISSUE TITLE
[Bug]: Can not recognize Password start with symbol @

### ISSUE THREAD

**Issue by chucklu** [NuGet/Home#12196]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet Version: 5.10.0.7240

### Impact

I'm unable to use this version

### Repro Steps & Context

https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources

update the nuget source with user name and password 
1.add it successfully
nuget sources add -name foo.bar -source C:\NuGet\local -username foo -password bar
2.update it successfully
nuget sources update -name foo.bar -source C:\NuGet\local -username foo -password bar
3.failed with password start with @
nuget sources update -name foo.bar -source C:\NuGet\local -username foo -password @bar

> Missing option value for: '-password'
> NuGet.Commands.CommandException: Missing option value for: '-password'
>    at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
>    at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

4.failed evenif I quote password
 nuget sources update -name foo.bar -source C:\NuGet\local -username foo -password "@bar"

> Unhandled Exception: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
>    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.Format(String format, Object[] args)
>    at NuGet.Common.CommandLineResponseFile.ParseArgsResponseFiles(String[] args, Int32 parseArgsResponseFileRecursionDepth)
>    at NuGet.CommandLine.Program.Main(String[] args)

**Comment by chucklu** [comment]
I also tried add back slash,

> nuget sources update -name foo.bar -source C:\NuGet\local -username foo -password \@bar

but the response status code does not indicate success: 401 (Unauthorized).

Is there any way I can check the verbose log?

**Comment by Azizxon** [comment]
@chucklu Did you try verbosity?
` -Verbosity [normal|quiet|detailed]`

reference: https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-update

**Comment by erdembayar** [comment]
Looks like dup of https://github.com/NuGet/Home/issues/7707. Please upvote the https://github.com/NuGet/Home/issues/7707 issue for visibility.

**Comment by jebriede** [comment]
Closing as duplicate as reported here: https://github.com/NuGet/Home/issues/12196#issuecomment-1293881553

**Comment by chucklu** [comment]
reported here https://github.com/NuGet/Home/issues/7707

**Comment by chucklu** [comment]
[brann0n](https://github.com/brann0n) try to fix this here, and did not pass the code review
https://github.com/NuGet/NuGet.Client/pull/3822#issuecomment-827411060

> Hi, thanks for the ping.
> I resigned from the company where fixing this issue would have improved daily tasks.
> With my new job i no longer have the time to work on this, although this issue still seems important to fix.
> 
> Maybe in the future someone else can pick it up were i left it.
> 
> Kind Regards!
