### ISSUE TITLE
Nuget package console fails to install packages for projects in the same directory

### ISSUE THREAD

**Issue by gh-andre** [NuGet/Home#12203]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

Visual Studio 2022 x64

### Worked before?

don't know

### Impact

I'm unable to use this version

### Repro Steps & Context

Use the provided sample solution that has two .vcxproj files in the same directory as the solution - `proj-A.vcxproj` and `proj-B.vcxproj`. Install a Nuget package into `proj-A` via Nuget package console:
```
Install-Package StoneSteps.zLib.Static -ProjectName proj-A
```
It will install the package and `proj-A` will be able to use zLib from the package.

Attempt to install the same package for `proj`-B`:
```
Install-Package StoneSteps.zLib.Static -ProjectName proj-B
```
Nuget refuses to do so with this message:
```
Package 'StoneSteps.zLib.Static.1.2.12.1' already exists in project 'proj-B'
```
However, because `proj-B.vcxproj` wasn't modified to add `.props` and `.targets` from the package, it won't build. Moving projects into their own directories seems to make it work, but project file location shouldn't be dictated by a bug in the packager.

This is the sample solution. It requires C++ installed to build the solution, but the bug probably can be reproduced without it.

[bug-nuget-two-projects.zip](https://github.com/NuGet/Home/files/9956152/bug-nuget-two-projects.zip)

**Comment by kartheekp-ms** [comment]
Thank you for attaching the sample solution. I am able to reproduce the issue.

> Moving projects into their own directories seems to make it work, but project file location shouldn't be dictated by a bug in the packager.

I am glad you found a work around for this issue.

**Comment by nkolev92** [comment]
When using 2 projects in the same folder, you are likely to hit issues with various build components. 

In packages.config, a packages.config is normally associated with a specific project. Given that you have 2 projects in the same folder, NuGet would try to associate the same packages.config file with both projects. 

Having multiple projects in the same folder is not recommended practice.

**Comment by gh-andre** [comment]
> When using 2 projects in the same folder, you are likely to hit issues with various build components.


VS provides all the tools for this to work just fine if it is set up correctly. This is also commonly used by CMake's VS generators. My sample project is not the best example because I focused on package installation and not project being fully working. I will update the sample with intermediate directories set by project name to fix those errors. 

I will also note that `packages.config` may be named as `packages.<project-name>.config` to maintain a set of Nuget packages per project. It is not well documented on in Nuget docs, but works really well and keeps projects well organized.

> In packages.config, a packages.config is normally associated with a specific project.

That's fine, but then it should work for both projects if it reports that both projects have the package installed. If you go as far as to say it's not supported, then VS should report an error instead of misreporting that one of the projects is good to go. This would be unfortunate, but would better reflect what it actually does.

The only way to get it working today is to unload some projects, install packages and then keep unloading/loading. That's a very laborious process.

> Having multiple projects in the same folder is not recommended practice.

I wouldn't know why because this is a good way to set up projects without scattering them over a bunch of folders. I will also add that I'm hoping that the packaging system would try to accommodate ways people actually use projects instead of forcing people to use it the way that works out for the packaging system.

**Comment by nkolev92** [comment]
> VS provides all the tools for this to work just fine if it is set up correctly

The challenge with sharing any sharing of directories among projects is the ambiguity that tools have to deal with due to not knowing *when* the files/folders are shared.

Just because it works, ie, your project build and runs, it doesn't mean it always does what it's actually supposed to do in that scenario. 

> I will also note that packages.config may be named as packages.<project-name>.config to maintain a set of Nuget packages per project. It is not well documented on in Nuget docs, but works really well and keeps projects well organized.

Yes, that'd work, but that's not what was being used here :) 

> but then it should work for both projects if it reports that both projects have the package installed. If you go as far as to say it's not supported, then VS should report an error instead of misreporting that one of the projects is good to go. This would be unfortunate, but would better reflect what it actually does.

That's why we're leaving the issue open. NuGet could do a best effort to detect issues, but that's not always going to work correctly. It'd require you to have both projects restoring/building in the same context. 

> I wouldn't know why because this is a good way to set up projects without scattering them over a bunch of folders. I will also add that I'm hoping that the packaging system would try to accommodate ways people actually use projects instead of forcing people to use it the way that works out for the packaging system.

It's not really a packaging system limitation, but there's bits and pieces everywhere. 
It is not uncommon that we see people accidentally naming multiple projects the same, or having the dependencies from 1 project override the dependencies from another project when sharing an intermediate directory. 

The best approach would be to use the defaults, use separate output directories and express dependencies through the ProjectReference. If and when it's needed, a project's dependencies would then be copied to the output folder.

**Comment by gh-andre** [comment]
> The challenge with sharing any sharing of directories among projects is the ambiguity that tools have to deal with due to not knowing when the files/folders are shared.

Perhaps I didn't express this well. Sharing any intermediaries and output is bad indeed, which is distinctly different from having projects at the same level. They just need to be set up to keep intermediate files and output in their own directories. VS does it well and it works for Windows and Linux projects, keeping all files strictly per project.

> The best approach would be to use the defaults, use separate output directories and express dependencies through the ProjectReference. If and when it's needed, a project's dependencies would then be copied to the output folder.

`ProjectReference` is not something C++ projects can use, so not sure what's the relevance here.

Anyway, all I'm saying is that VS is supposed to inject `.prop` and .`targets` from the package into affected projects and that's the part of the package installation process that isn't working here. Seeing how this issue is open, I'm hopeful this will get resolved one day.

Thanks for your insights.

**Comment by nkolev92** [comment]
> Anyway, all I'm saying is that VS is supposed to inject .prop and .targets from the package into affected projects and that's the part of the package installation process that isn't working here

Yep, basically none of the installation happens for a project because it uses the same packages.config for both projects. 

> Seeing how this issue is open, I'm hopeful this will get resolved one day.

Just setting expectations, we wait for upvotes on bugs such as this. You can read about our policy in  https://github.com/NuGet/Home/blob/dev/Issue-Triage-Policy.md.

**Comment by gh-andre** [comment]
> Just setting expectations, we wait for upvotes on bugs such as this.

Oh, I see. Never mind then. We both know how those work out.
