### ISSUE TITLE
nuget.exe restore returns an incorrect error message for unknown file inputs

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1220]
When an unknown file is passed into nuget.exe restore it is treated as a solution file and the error message is unhelpful.

Repro
1. create a new empty file: file.xaml
2. run nuget.exe restore file.xaml

Expected:
An error saying the input is invalid

Actual:
"Could not find a part of the path 'c:\mypath\file.xaml'"

**Comment by RanjiniM** [comment]
Fixed
