### ISSUE TITLE
Can we have dependency graph feature ? (Showing Parent & Child relationship of different dependencies)

### ISSUE THREAD

**Issue by rohitcoder** [NuGet/Home#12218]
### NuGet Product(s) Involved

dotnet.exe, NuGet SDK, Other/NA

### The Elevator Pitch

We need a JSON output of the parent & child dependencies list, right now we're using  ``dotnet list /tmp/project package --include-transitive`` but this doesn't show a relationship and this is not in JSON format, since we already have a PR 
 https://github.com/NuGet/NuGet.Client/pull/4855 related to JSON output of dependencies, now it's time to work on Making these dependency graphs.

**Comment by nkolev92** [comment]
Duplicate in https://github.com/NuGet/Home/issues/6339.

**Comment by harshsikhwal** [comment]
I have implemented my own version of dependency generator: 
[NuGet-Visualizer](https://github.com/harshsikhwal/nuget-visualizer)

An interactive python script which helps users to generate dependencies for both NuGet and .NET Solution.

Graph for Microsoft.CodeAnalysis.CSharp:
![codeanalysis graph](https://user-images.githubusercontent.com/52648233/200638325-1929fa83-0713-4202-98e7-38efa650433b.png)

Hope this helps!

**Comment by pombredanne** [comment]
@rohitcoder you wrote:

> We need a JSON output of the parent & child dependencies list, right now we're using dotnet list /tmp/project package --include-transitive but this doesn't show a relationship and this is not in JSON format, since we already have a PR
NuGet/NuGet.Client#4855 related to JSON output of dependencies, now it's time to work on Making these dependency graphs.

Try this new, work-in-progress (standalone) tool at https://github.com/nexB/nuget-inspector

From a proj or sln file, it outputs a resolved dependency tree in JSON. It honors both legacy and current manifests and lockfiles (project.lock.json lockfile, project.json, packages.config) and (proj projectreferences and project.assets.json lockfile)... and calls the nuget libraries to resolve dependencies live as needed. It is designed to run as a self-contained, standalone CLI utility on Linux/Windows/macOS no donet installation needed.
feedback mucho welcomed!
