### ISSUE TITLE
VS 2022 - Unable to load the service index for source feed

### ISSUE THREAD

**Issue by matusqo** [NuGet/Home#12217]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.3.6

### Worked before?

Same version but stopped working on Friday afternoon

### Impact

I'm unable to use this version

### Repro Steps & Context

![image](https://user-images.githubusercontent.com/50449453/200262810-e7f92265-0008-4027-bd09-45c27e79fbb0.png)
I can't restore my VS solution at all. Workaround for me is to use VS 2019 only.

### Verbose Logs

```shell
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Dispatchers.PositionsSnapshot\FlowBank.DataHub.Dispatchers.PositionsSnapshot.csproj (in 58,61 sec).
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
NU1301: Unable to load the service index for source https://pkgs.dev.azure.com/FlowBank/_packaging/FlowBank/nuget/v3/index.json.
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.Common.UnitTests\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Injectors.RealtimeRisk.Trades\FlowBank.DataHub.Injectors.RealtimeRisk.Trades.csproj (in 18 ms).
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.Common.UnitTests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.Common.UnitTests.csproj (in 58,62 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Extractors.BocoreClient.UnitTests\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Extractors.BocoreClient.UnitTests\FlowBank.DataHub.Tests.Extractors.BocoreClient.UnitTests.csproj (in 58,63 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Dispatchers.Exante.PositionsSnapshots.UnitTests\obj\project.assets.json
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Extractors.BocoreClient\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Dispatchers.Exante.PositionsSnapshots.UnitTests\FlowBank.DataHub.Tests.Dispatchers.Exante.PositionsSnapshots.UnitTests.csproj (in 58,64 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.ClientPositionsSnapshots.UnitTests\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Extractors.BocoreClient\FlowBank.DataHub.Extractors.BocoreClient.csproj (in 48 ms).
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Tests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.ClientPositionsSnapshots.UnitTests\FlowBank.DataHub.Tests.Injectors.RealtimeRisk.ClientPositionsSnapshots.UnitTests.csproj (in 58,65 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Injectors.RealtimeRisk.ClientPositionsSnapshots\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Injectors.RealtimeRisk.ClientPositionsSnapshots\FlowBank.DataHub.Injectors.RealtimeRisk.ClientPositionsSnapshots.csproj (in 51,44 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Extractors.SymbolDb\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\Services\FlowBank.DataHub.Extractors.SymbolDb\FlowBank.DataHub.Extractors.SymbolDb.csproj (in 40,23 sec).
Writing assets file to disk. Path: C:\Users\mkopac\source\repos\DataHub Services\Product\_AppHosts\WindowsService\FlowBank.DataHub.Services.Host\obj\project.assets.json
Failed to restore C:\Users\mkopac\source\repos\DataHub Services\Product\_AppHosts\WindowsService\FlowBank.DataHub.Services.Host\FlowBank.DataHub.Services.Host.csproj (in 1,17 min).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
Time Elapsed: 00:01:10.1743589
========== Finished ==========
```

**Comment by donnie-msft** [comment]
Hi @matusqo,
How are you triggering this restore? Is it from auto-restore, or manually restoring, interacting with the Package Manager UI, etc? Also, you say that VS 2019 works for you. Is that for the same package source(s) and `nuget.config`? If you're using the PM UI, are the same package sources enabled in the upper-right in both 2019 and 2022?

**Comment by kartheekp-ms** [comment]
@matusqo - Can you please take a look at the https://github.com/NuGet/Home/wiki/Azure-DevOps-Artifacts-authentication-issues wiki page and check if any of the workarounds unblock you?

**Comment by matusqo** [comment]
Hi guys, I do restore of solution by context menu "Restore NuGet Packages". VS 2022 also does it automatically at solution load. Yes I have same set of NuGet sources configured in both VS. I open exactly the same .sln file on my disk in both VS.
Yesterday I had to migrate to a new laptop because of other reasons and the issue is not there anymore in VS2022. Thank you for the link @kartheekp-ms I will keep it for the future in case it happens again.

**Comment by matusqo** [comment]
Happens again on the new laptop. Even with "dotnet restore" command executed in the folder where the .sln file is located. I will check the link provided

**Comment by matusqo** [comment]
Ok I found that VS doesn't prompt for credentials to access Azure Artifacts automatically, I had to go to the accounts screen in VS and Re-enter credentials for the account which I use to access Azure DevOps. Restore then worked immediately.

**Comment by donnie-msft** [comment]
Glad you're unblocked. It seems this issue is the same one that was recently fixed in https://github.com/NuGet/Home/issues/12062. The credential provider fix is available in 17.4.
Happy coding!

**Comment by olakusibe** [comment]
>If you go through the guide https://github.com/NuGet/Home/wiki/Azure-DevOps-Artifacts-authentication-issues and still have issues, how I solved mine was Manage Connections via Team Explorer by re entering the credential and doing a refresh.

**Comment by ankitbuti** [comment]
I removed all cache and temporary files. And then did a fresh, clean install of .NET8.0.100 SDK & Visual Studio for Mac 2022 (17.6.7 (build 417)). 

On CLI:
curl https://api.nuget.org/v3/index.json works.
nuget restore works.
msbuild /t restore works.

But,
CLI - dotnet restore
error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
Also, dotnet workload install fails with same error.

I am unable to install wasm-tools,maui etc even with the Visual Studio setup due to these errors. I did. dev cert trust etc and that's working fine.

**Comment by jjzhang12** [comment]
Error occurred while restoring NuGet packages: Unable to load the service index for source https://api.nuget.org/v3/index.json.
Value cannot be null.
Parameter name: versionRange

Visual Studio 17.8 with .net 8 SDK on Windows.

**Comment by bdgit** [comment]
Index and 401 issues happened for me using an existing script during 2 of 3 steps; which I run via Developer Powershell.
Part 1 > dotnet pack
Part 2 > dotnet nuget push [to Local Feed Directory]
Part 3 > dotnet tool update
My solutions nuget.config includes Local Feed, Private Feed, and Nuget.

Starting setup including NET 8.0.1 (via Visual Studio) with credential provider some time ago.  Part 1 and 3 failed with 401 accessing the index on my private feed.

Re-auth was required in Visual Studio.  That alone was not enough.  Rebuild Solution was run twice (first run gives error).
At this point the error during Part 1 is gone.

Updated Visual Studio to 17.9.1 w/ NET 8.0.2 and re-trusted the DevCert.  This did not fix Part 3.

Instead of installing NET 8.0.201, I decided to run the credential provider install script (used iex method w/ netfx) again.  This worked.  All parts of my script are running.

**Comment by enavarro65** [comment]
I ran into the same issue until I disabled McAfee's firewall on my Mac.  Then all of the sudden the restoring was completed with no issues.

**Comment by larenztate** [comment]
They closed suddenly without notice while there's balance of 800,000 dollars ! Now they don't allow trading or more than that, asking me to open a new account !! What about my money !!! I am currently working with  ''wikihelpdesks at gmail dot com '' for assistance to help me get my fund back from them.
