### ISSUE TITLE
nuget still can't find msbuild.exe on MacOS?

### ISSUE THREAD

**Issue by jchowgithub** [NuGet/Home#12219]
### NuGet Product Used

NuGet.exe

### Product Version

5.9.0.7134

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi, I'm running nuget.exe 5.9.0.7134 as part of mono 6.12.0.122 on MacOs but when I use the restore command it still gives me this error:
`NuGet.Commands.CommandException: MsBuild.exe does not exist`
I know I have **msbuild** but not **msbuild.exe** (being a Mac) and that there has been a thread about this from 2016 but it was closed without any resolution. Is there another work around for this pls? Thanks in advance!

### Verbose Logs

```shell
09:22:20  + /Library/Frameworks/Mono.framework/Commands/nuget restore -Verbosity detailed /Users/ec2-user/agent/perforce/trunk/m3/Unity/MYPROJECT/MYPROJECT.sln
09:22:22  NuGet Version: 5.9.0.7134
09:22:22  MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
09:22:23  MSBuild P2P timeout [ms]: 120000
09:22:23  NuGet.Commands.CommandException: MsBuild.exe does not exist at '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'.
09:22:23    at NuGet.CommandLine.MsBuildUtility.GetProjectReferencesAsync (NuGet.CommandLine.MsBuildToolset msbuildToolset, System.String[] projectPaths, System.Int32 timeOut, NuGet.CommandLine.IConsole console, System.Boolean recursive, System.String solutionDirectory, System.String solutionName, System.String restoreConfigFile, System.String[] sources, System.String packagesDirectory, NuGet.ProjectModel.RestoreLockProperties restoreLockProperties) [0x00044] in <9181e88e7bb14ceabfcb2a891b5308f9>:0 
09:22:23    at NuGet.CommandLine.RestoreCommand.GetDependencyGraphSpecAsync (System.String[] projectsWithPotentialP2PReferences, System.String solutionDirectory, System.String solutionName, System.String configFile) [0x0012b] in <9181e88e7bb14ceabfcb2a891b5308f9>:0 
09:22:23    at NuGet.CommandLine.RestoreCommand.DetermineInputsFromMSBuildAsync (NuGet.CommandLine.RestoreCommand+PackageRestoreInputs packageRestoreInputs) [0x000e5] in <9181e88e7bb14ceabfcb2a891b5308f9>:0 
09:22:23  WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
09:22:23  All packages listed in packages.config are already installed.
```

**Comment by donnie-msft** [comment]
Hi @jchowgithub  - I touched base with the Mono team, and their first suggestion was that you try updating Mono. Version `6.12.0.122` is 18 months old and there have been many bug fixes since then. They tried a to repro this issue and were not seeing the error you see.

Secondly, nuget.exe 5.9 is quite old as well. I'd suggest updating as well (6.3.1 is latest recommended on nuget.org).
Let us know if the issue resolves and which versions you are using after update. Thanks!

**Comment by jchowgithub** [comment]
Thank you, it'll take some time to update our build machines but I'll let you know, thanks!
