### ISSUE TITLE
Credential provider skips all authentication methods if NET 7 RC SDK is installed

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12215]
### NuGet Product Used

dotnet.exe

### Product Version

.NET 7 SDK

### Worked before?

.NET 6 SDK

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

NuGet side issue for https://github.com/microsoft/artifacts-credprovider/issues/347 especially https://github.com/microsoft/artifacts-credprovider/issues/347#issuecomment-1304395965.

**Comment by kartheekp-ms** [comment]
May be related to https://github.com/NuGet/Home/issues/12195#issuecomment-1302595922 cc @jeffkl

**Comment by kartheekp-ms** [comment]
Andy explained the current credential provider workflow with the help of a diagram in https://github.com/NuGet/Home/issues/11210#issuecomment-1132240645 cc @dominoFire

**Comment by dominoFire** [comment]
Discussed offline with Kartheek. The goal is to investigate:

- Whether or not this can be fixed in NuGet side?
- Where do retries are happening?

**Comment by dominoFire** [comment]
Assigning back to Kartheek to load balance.

**Comment by kartheekp-ms** [comment]
Customers have mentioned that they were unable to reproduce the issue on .NET 7 GA SDK. https://github.com/microsoft/artifacts-credprovider/issues/347#issuecomment-1308351905 and https://github.com/microsoft/artifacts-credprovider/issues/347#issuecomment-1309075757 cc @ransagy @arknu.

Unfortunately, I can't reproduce the issue on my end. I searched for any race conditions in the code that that could be causing NuGet to pass `IsRetry=true` for credential providers but nothing seems obvious. At this point, I am leaning towards closing this issue and reopen it if customers were able to reproduce this issue again.

**Comment by ransagy** [comment]
The only thing im worried about is that we aren't aware that there was anything to change/fix the scenario between 7 RC2 and GA, which is suspicious. Otherwise, yes, haven't come across the issues again since 7 GA was installed.

**Comment by kartheekp-ms** [comment]
> The only thing im worried about is that we aren't aware that there was anything to change/fix the scenario between 7 RC2 and GA, which is suspicious. 

I totally agree with you. Looking at the commit history https://github.com/NuGet/NuGet.Client/commits/release-6.4.x the only difference is .NET 7 GA has one commit extra when compared to .NET 7 RC2. AFAIK https://github.com/NuGet/NuGet.Client/commit/125f673fd1cdb3cc012f62aa3ce764d2460b89eb commit related to package signature verification but not related to credential provider issue.

![image](https://user-images.githubusercontent.com/52756182/203395714-544221f0-df89-4d3a-8d76-b3664625a8d7.png)

@ransagy - Would it be possible to pin your repository to .NET 7 RC2 SDK using global.json file (`dotnet new globaljson --sdk-version 7.0.100-rc.2.22477.23`) and see if you can reproduce this issue again? If I understand https://github.com/microsoft/artifacts-credprovider/issues/347#issuecomment-1275241768 correctly, `IsNonInteractive` is not an issue anymore but sometimes you were able to reproduce `IsRetry` is set to `true` even though it should not be correct?

**Comment by kartheekp-ms** [comment]
I think I found the root cause of this issue. For some reason when I execute `dotnet restore` on `.NET 7 RC2` SDK the task manager still has `dotnet.exe` process hanging around. 

![image](https://user-images.githubusercontent.com/52756182/203430396-77b6c9a3-cdce-4062-8b19-dee2f96f63de.png)

When I execute my sample project on .NET 7 GA there is no `dotnet.exe` process hanging around after restore command executed successfully.

![image](https://user-images.githubusercontent.com/52756182/203431046-ccc90d05-4a13-4905-b4ac-ef3a37466aca.png)

NuGet stores CredentialService cache in a static variable. https://github.com/NuGet/NuGet.Client/blob/1dbec1c3e8323b8be902b83d4a10c5d8e4cf5887/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpHandlerResourceV3.cs#L40
What this means is that if earlier `dotnet.exe` process has authenticated against the private feed with `IsRetry= false`. Given that `.NET host` process didn't exit, next time when we execute `dotnet restore` and if the command is executed on the existing .NET Host then `IsRetry` will be true even for the first attempt,

Given that this is issue not reproducible on .NET 7 GA, I am leaning towards closing this issue.

**Comment by ransagy** [comment]
Good call on the hanged processes, didn't even think looking at that. Let me know if you want me to try and confirm it on my end as well. Otherwise, i agree, seems to have been more a general issue.

**Comment by kartheekp-ms** [comment]
> Let me know if you want me to try and confirm it on my end as well. 

That would be great. Thank you. I am closing this issue now. If you observe a different behavior, please add a comment so that I ca reopen it.
