### ISSUE TITLE
Json output localization

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#12210]
### NuGet Product Used
dotnet.exe

### Repro Steps & Context

Follow up on [comment](https://github.com/NuGet/NuGet.Client/pull/4855#discussion_r1009977670
).   It's more important for problems>>security section. 
If it's localized, then json processing should be aware of localization. Let's say we filter for `Error` or `Critical` then if it's in different languages may not notice there was an `error`/`vulnerability`.
Please note it's not localized for console output yet. 

https://github.com/NuGet/NuGet.Client/blob/ee9ef1f0e1a256a6d215669256576320a02fb0ac/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/ProjectPackagesPrintUtility.cs#L213-L216

Fyi @dominoFire

**Comment by dominoFire** [comment]
If this is a category name or value, we can leave it unlocalized and "treat it as an enumeration".

**Comment by nkolev92** [comment]
> If this is a category name or value, we can leave it unlocalized and "treat it as an enumeration".

I agree. For categories in fact we should leave it unlocalized. 
An example of that is the item `PackageReference`.  You shouldn't need a different parser depending on your culture.

**Comment by nkolev92** [comment]
Not localization is preferred. 
Closing this.
