### ISSUE TITLE
NuGet 3.1 not reading from our internal v2 source

### ISSUE THREAD

**Issue by bencyoung** [NuGet/Home#1222]
I get the error below whenever it tries to restore a package

Response status code does not indicate success: 401 (Unauthorized).
 GET http://adpbuildsrv:81/nuget/Internal/FindPackagesById()?id=...
 System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

Interestingly the package manager view works fine in VS 2015, as does NuGet 2.8 in VS 2013

**Comment by yishaigalatzer** [comment]
@bencyoung can you provide some more details on how you are trying to restore the package? What product are you using (VS 2015? What version of NuGet? nuget.exe ?)

**Comment by yishaigalatzer** [comment]
@bencyoung ping

**Comment by yishaigalatzer** [comment]
Haven't hear back
