### ISSUE TITLE
Target Segment in . targets file in buildTransitive not work

### ISSUE THREAD

**Issue by Y-Theta** [NuGet/Home#12223]
### NuGet Product Used

NuGet.exe

### Product Version

 nuget.exe 6.3.0.131

### Impact

It's more difficult to complete my work

### Repro Steps & Context

create a package with struct like  
mctech.lib.desktopcapture
   -1.4.2
        -buildTransitive
             -net47
                   -McTech.Lib.DesktopCapture.targets

and in the targets 
have a <target> 
```
   <Target Name="T2"
        AfterTargets="Build">
        <Message Text="copy capture tool complate to '$(OutputPath)tools\capture'"
            Importance="high" />
    </Target>
```
create a classlibrary project using netframework 4.7 named A
create a winform project using netframework 4.7 named B
in Project B make a project reference to A 
in Project A make a PackageReference to the package

when rebuild Project B 
only project A output has the message

**Comment by Y-Theta** [comment]
output like this 

已启动重新生成…
1>------ 已启动全部重新生成: 项目: ClassLibrary1, 配置: Debug Any CPU ------
已还原 D:\Program\MyProj\C#\Cli\WindowsFormsApp1\WindowsFormsApp1.csproj (用时 8 ms)。
已还原 D:\Program\MyProj\C#\Cli\ClassLibrary1\ClassLibrary1.csproj (用时 39 ms)。
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): warning MSB3270: 所生成项目的处理器架构“MSIL”与引用“C:\Users\mc_yangjieming\.nuget\packages\mctech.lib.growingio\1.0.0\lib\net47\manualtrackCliDll.dll”的处理器架构“AMD64”不匹配。这种不匹配可能会导致运行时失败。请考虑通过配置管理器更改您的项目的目标处理器架构，以使您的项目与引用间的处理器架构保持一致，或者为引用关联一个与您的项目的目标处理器架构相符的处理器架构。
1>  ClassLibrary1 -> D:\Program\MyProj\C#\Cli\ClassLibrary1\bin\Debug\ClassLibrary1.dll
1>  copy ssssss
1>  copy capture tool complate to 'bin\Debug\tools\capture'
2>------ 已启动全部重新生成: 项目: WindowsFormsApp2, 配置: Debug Any CPU ------
2>  WindowsFormsApp2 -> D:\Program\MyProj\C#\Cli\WindowsFormsApp2\bin\Debug\WindowsFormsApp2.exe
========== 全部重新生成: 成功 2 个，失败 0 个，跳过 0 个 ==========

**Comment by donnie-msft** [comment]
Hello,
I found a similar report against MSBuild here: https://github.com/dotnet/msbuild/issues/5797
Take a look at that thread and see if it looks similar to you.

MSBuild also made some changes recently. The default was changed with VS 2022 (17.0) (https://github.com/dotnet/msbuild/pull/6622). It looks you're using VS 2019, so the default is still set to `false` with your setup.

> It is now possible to opt into reasonable behavior: set the property MSBuildCopyContentTransitively to true in a Directory.Build.props file (or in individual projects--but you probably want this for your whole repo).
(see more details at https://github.com/dotnet/msbuild/issues/1054#issuecomment-847959047)

Please take a look and let us know if you're able to resolve your issue.

**Comment by Y-Theta** [comment]
but my vs2022 has the same action ;
is that because I'm not using the sdk-style project

**Comment by Y-Theta** [comment]
> ### NuGet Product Used
> NuGet.exe
> 
> ### Product Version
> nuget.exe 6.3.0.131
> 
> ### Worked before?
> _No response_
> 
> ### Impact
> It's more difficult to complete my work
> 
> ### Repro Steps & Context
> create a package with struct like mctech.lib.desktopcapture -1.4.2 -buildTransitive -net47 -McTech.Lib.DesktopCapture.targets
> 
> and in the targets have a
> 
> ```
>    <Target Name="T2"
>         AfterTargets="Build">
>         <Message Text="copy capture tool complate to '$(OutputPath)tools\capture'"
>             Importance="high" />
>     </Target>
> ```
> 
> create a classlibrary project using netframework 4.7 named A create a winform project using netframework 4.7 named B in Project B make a project reference to A in Project A make a PackageReference to the package
> 
> when rebuild Project B only project A output has the message
> 
> ### Verbose Logs
> _No response_

When I change Porject A and Project B to sdk-style project it works

**Comment by zivkan** [comment]
@Y-Theta Please see https://learn.microsoft.com/nuget/consume-packages/package-references-in-project-files#using-packagereference-for-a-project-with-no-package-dependencies

SDK styles default to PackageReference, as they don't support packages.config. But as the docs say, for non-SDK style projects, a project either needs a PackageReference, or to define the RestoreProjectStyle.
