### ISSUE TITLE
[Push] The duplicated package was pushed again to the specific source using command “dotnet nuget push "*. nupkg" --skip-duplicate” 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12233]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet Client Dev\6.5.0.75

### Impact

It bothers me. A fix would be nice

#### Repro steps:  

1. Open VS and create a C# Class Library (.Net Framework) project. 

2. Type project name as “[Package01]” in “Project name” text box and click “Next” button. 

3. Build solution and make sure compilation succeeds.  

4. Open “Developer Command Prompt”, cd to Package01 project path and execute execute “nuget spec”. 

5.  Execute “dotnet nuget pack Package01.csproj –include-symbols”. 

6.  Cd to “C:\Users\v-minlon\source\repos\Package01\Package01\bin\Debug”   

7. Execute command “dotnet nuget push "*. nupkg" --skip-duplicate -s \\ddfiles\Drops\NuGet\PushTest\Aimee” 

#### Expected: 

The duplicated package “Package01.1.0.0. nupkg” should be skipped under the specified source as the doc said as below. 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/84695155/201295232-81d4badc-6fab-4354-9fed-5c96f7b70c81.png)

#### Actual: 

There is a warning that said the option is not currently supported and the duplicated package “Package01.1.0.0. nupkg” was pushed successfully as below screenshot. 
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/84695155/201295339-288783f7-e998-4d54-a593-0454827dce78.png)

#### Note: it is not a regression.

**Comment by donnie-msft** [comment]
As the warning indicates, SkipDuplicates does not apply when pushing to a local source. 

https://github.com/NuGet/NuGet.Client/blob/a8a8a34d9679041fb0d0fa1f2385667860658afb/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L640

**Comment by donnie-msft** [comment]
Filed https://github.com/NuGet/docs.microsoft.com-nuget/issues/2943
