### ISSUE TITLE
[Bug Bash] “Prerelease” tag under package icon in the “Browse” tab and “Installed” tab will not show in real time after checking “Include prerelease” checkbox

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12234]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.5.0.75

### Impact

It bothers me. A fix would be nice

#### Details about Problem
VS Version: Main\33110.265
NuGet Version: Dev\6.5.0.75
OS Version: Windows-11-Enterprise-22H2 ENU

#### Repro Steps:
1.	Open VS, click menu File->New Project, create a Console App (.Net Core) project.
2.	Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3.	Click the “Browse” tab and check the “Include prerelease” checkbox.
4.	Install a package (which has prerelease version) into the project and click the “Installed” tab.
#### Expected:
“Prerelease” tag under package icon in the “Browse” tab (step3) and “Installed” tab (step4) will show in real time after checking “Include prerelease” checkbox. Same with the showing in the “Updates” tab as below.
![image](https://user-images.githubusercontent.com/20632625/201308421-d7233a91-9864-4bbe-9e56-0e3966b5e646.png)
#### Actual:
“Prerelease” tag under package icon in the “Browse” tab (step3) and “Installed” tab (step4) will not show in real time after checking “Include prerelease” checkbox.
![image](https://user-images.githubusercontent.com/20632625/201308496-d50a7b37-2061-47f1-ae1a-504631b49d02.png) 
#### Note: It is not a regression since it reproes on VS D16.11\33027.164.

**Comment by SueSu01** [comment]
Verified this issue on VS Main\34809.69 + NuGet Client Dev\6.11.0.9, it's fixed, so closed it, thanks!
![image](https://github.com/NuGet/Home/assets/149561645/1b1ef5d8-72c4-4905-832d-454e7cc4f2ce)
