### ISSUE TITLE
Installation is rolledback instantly

### ISSUE THREAD

**Issue by CobraCalle** [NuGet/Home#1224]
Hello,

with VS2015 I cannot update packages from our own store. The with VS2013 everything works fine. When I want to update a package it is installed and is shown in the source control explorer for a second. The it is rolled back, but I cannot see why this happens... here the output:

Attempting to gather dependencies information for package 'Diomex.Framework.Release.2.1.15229.1' with respect to project 'Diomex XcalibuR\Misc\Cogito\Cogito.Retail', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Diomex.Framework.Release.2.1.15229.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Diomex.Framework.Release.2.1.15229.1'
Resolved actions to install package 'Diomex.Framework.Release.2.1.15229.1'
For adding package 'Diomex.Framework.Release.2.1.15229.1' to project 'Cogito.Retail' that targets 'net452'.
For adding package 'Diomex.Framework.Release.2.1.15229.1' to project 'Cogito.Retail' that targets 'net452'.
Adding package 'Diomex.Framework.Release.2.1.15229.1' to folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages'
Added package 'Diomex.Framework.Release.2.1.15229.1' to folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages'
Install failed. Rolling back...
Package 'Diomex.Framework.Release 2.1.15229.1' does not exist in project 'Cogito.Retail'
Removing package 'Diomex.Framework.Release 2.1.15229.1' from folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages'
Removed file 'Diomex.Framework.Release.2.1.15229.1.nupkg' from folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages\Diomex.Framework.Release.2.1.15229.1'.
Removed folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages\Diomex.Framework.Release.2.1.15229.1'.
Removed package 'Diomex.Framework.Release 2.1.15229.1' from folder 'S:\Diomex\XcalibuR\Main\Sourcen\packages'
Failed to add reference to 'Diomex.Framework'.
========== Finished ==========

Is there any detailed log or something like that?

Is it possible to use the old plugin von VS2013 in VS2015? The new version is so buggy, that it is (at least for us) nearly impossible to work with...

Thanks for any help

**Comment by emgarten** [comment]
It looks like the error is

> Failed to add reference to 'Diomex.Framework'.

This could occur if the assembly reference cannot be added to the project. Since I don't see the package on nuget.org I can't try it myself, but you could verify that adding a reference to Diomex.Framework.dll works as expected outside of NuGet.

You can also try using the powershell management console to get more info on the error by running the install there:
_install-package Diomex.Framework.Release -version 2.1.15229.1_

**Comment by CobraCalle** [comment]
Thank you for the info... I'll try the powershell command when we update the Diomex.Framework-Package next time. But in general some more information in the default log would make live easy.

But at the end, I don't think that the problem is related to that package, because updating the package with package manager in VS2013 work just fine. Or are there any things I have to change in my package to be installed by the new package manager?

**Comment by emgarten** [comment]
VS2013 and VS2015 should be installing the same items from the package.

**Comment by yishaigalatzer** [comment]
@CobraCalle any updates on the matter? Do you mind updating to the latest NuGet available (either 3.2 from the gallery or to 3.2.1-rc from http://dist.nuget.org/index.html

**Comment by yishaigalatzer** [comment]
ping, we haven't heard back yet. We would have to close this issue down if we can't get any more information.
