### ISSUE TITLE
Publish NuGet Package seems broken for multiple-TargetFrameworks setting, at least for publish to a Folder. Package not not copied to destination.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#12247]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Publish-NuGet-Package-seems-broken-for-m/10202072)._

---
\[regression\] \[worked-in:17.3.6\]  
Hi! See the subject.

I am using Visual Studio 17.4. And therefore I also have the .NET 7.0 SDK installed.

Today I tried multiple combinations of settings and multiple combinations of TargetFrameworks.  
It does not make a difference whether I try .NET 7.0 (net7.0), .NET 6.0 (net6.0) or .NET Framework 4.8 (net48).

In all cases the publish only finishes correctly with  enabled, but _not_ when using  (the plural version of this XML tag).

Important:  
Today I noticed the same problem 2 machines at work with the paid Visual Studio Professional 2022 product, but at home, with Visual Studio Community 2022 on my own private machine: same issue.

I don’t know whether the root cause of the issue is in the new .NET SDK or in Visual Studio. But I am using Visual Studio’s way of working with a created FolderProfile.pubxml publish profile file.

Right now I can work around the issue by manually copying the .nupkg file from the bin\\Release folder, but the idea behind publishing is that you don’t need to do that by hand.

Second thing I noticed: not only the package is copied to the destination, but also the rest of the build products. I am not sure whether this is by design or not, but it’s different from my earlier experience, where just the package was copied when I enabled the GeneratePackageOnBuild property in my csproj file.

---

I can repro this issue.
I created binlog files with `dotnet publish  --framework net6.0 /bl` and compared it.
If it's just `TargetFramework` then as you can see `PackAsBuildAfterTarget` target triggered as expected.
![image](https://user-images.githubusercontent.com/8766776/202304888-566a72df-b0e0-48e2-a255-dbfaafee6b20.png)

But if it's `TargetFrameworks` then as you can see `PackAsBuildAfterTarget` target is not triggererd.

![image](https://user-images.githubusercontent.com/8766776/202305604-74a8e046-ee36-466e-b499-fa7234894ee2.png)

Code pointer for above target is  here:
https://github.com/NuGet/NuGet.Client/blob/20be995d651808feb5cd48f30cb97197e497377c/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L162

Code calling above is here:
https://github.com/microsoft/MSBuildSdks/blob/252b32490bba60105bed8828a8ea7c18d69e5701/src/Artifacts/buildMultiTargeting/Microsoft.Build.Artifacts.targets#L17

**Comment by erdembayar** [comment]
I redirected the VsFeedback issue to sdk team, it looks like they need to stop setting true to `GeneratePackageOnBuild` anymore for single targetframework, they already stopped creating [nupkg for multitarget framework](https://developercommunity.visualstudio.com/t/Visual-Studio-174-no-longer-produces-nu/10194715#T-N10197489). Please note pack vs publish is 2 different scenarios.

**Comment by zivkan** [comment]
also duplicate of/related to: https://github.com/NuGet/Home/issues/4638
