### ISSUE TITLE
getting error while build .net application in jenkins

### ISSUE THREAD

**Issue by steephan-s1** [NuGet/Home#12241]
VERBOSE: Building InsightWeb Project with Version number : 2021.07.0.0
MSBuild version 17.3.0+92e077650 for .NET
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.devexpress.com/CnraCdegL3Nrpe5TGyiFPMwksP9mua7zFXAe5hGwiGWI3AYetM/api/FindPackagesById()?id='Antlr4'&semVerLevel=2.0.0'.
  The SSL connection could not be established, see inner exception.
    Authentication failed, see inner exception.
    The client and server cannot communicate, because they do not possess a common algorithm.
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.devexpress.com/CnraCdegL3Nrpe5TGyiFPMwksP9mua7zFXAe5hGwiGWI3AYetM/api/FindPackagesById()?id='BuildBundlerMinifier'&semVerLevel=2.0.0'.
  The SSL connection could not be established, see inner exception.
    Authentication failed, see inner exception.
    The client and server cannot communicate, because they do not possess a common algorithm.
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.devexpress.com/CnraCdegL3Nrpe5TGyiFPMwksP9mua7zFXAe5hGwiGWI3AYetM/api/FindPackagesById()?id='Microsoft.AspNetCore.Identity'&semVerLevel=2.0.0'.
  The SSL connection could not be established, see inner exception.
    Authentication failed, see inner exception.
    The client and server cannot communicate, because they do not possess a common algorithm.
  Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.devexpress.com/CnraCdegL3Nrpe5TGyiFPMwksP9mua7zFXAe5hGwiGWI3AYetM/api/FindPackagesById()?id='BuildWebCompiler2022'&semVerLevel=2.0.0'.

**Comment by erdembayar** [comment]
@steephan-s1 
Could you please run tool here https://github.com/microsoft/azure-devops-tls12 to test if your jenkins machine has latest TLS enabled? 
It could be TLS connection issue, but since it's 3rd party artifact server server so hard to say. Above `TLS1.2` is enabled for nuget.org Azure artifacts. 
Also, you could you try to restore/build simple dotnet application with 1 package from nuget.org on your jenkins machine?

**Comment by steephan-s1** [comment]
Hi @erdembayar,
I tried to build in local using CMD even though its throwing same error:

 
[errorlog.pdf](https://github.com/NuGet/Home/files/10073267/errorlog.pdf)

**Comment by jeffkl** [comment]
@steephan-s1 I think you'll need to follow-up with DevExpress on how their feeds are hosted and what security transport layer is in use.  I see a handful of KB articles related to this: https://supportcenter.devexpress.com/ticket/list?searchString=TLS&sorting=Relevance
