### ISSUE TITLE
A normal nuget package cannot reference a prerelease package

### ISSUE THREAD

**Issue by tonyqus** [NuGet/Home#12259]
### NuGet Product Used

NuGet.exe, Visual Studio Package Manager Console

### Product Version

6.3.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Since NPOI 2.6.0 starts using SixLabors.Fonts 1.0.0-beta18 (a prerelease package), a few users report the following issue in .NET framework 4.7.2:

**Repo Steps**
Create a new console and install NPOI 2.6.0 package (latest one)
1. Open VS 2022
2. Create new C# console app for .net framework 4.7.2
3. Open NuGet console
4. PM> Install-Package npoi

And another popular package ClosedXML has [the same problem](https://github.com/ClosedXML/ClosedXML/blob/35a2fca7852a9a941287f6d5f828b10de0fd93ce/docs/installation.rst)

According to my own investigation, this issue may mainly due to VS template for .NET framework 4.7.2 in VS2022. The root cause is that this template is still using legacy package.config instead of PackageReference. 

And it's weird that we have another release called NPOI 2.6.0-rc-3 (a prerelease package), which also reference SixLabors.Fonts 1.0.0-beta18. I can install package in any case no matter if the VS project is in package.config mode. In other words, a prerelease package can support referencing another prerelease package in any case.

### Verbose Logs

```shell
Attempting to gather dependency information for package 'npoi.2.6.0' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 1.28 sec
Attempting to resolve dependencies for package 'npoi.2.6.0' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependency 'SixLabors.Fonts'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.
At line:1 char:1
+ Install-Package npoi
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by jeffkl** [comment]
Team Triage: This is expected behavior since with `packages.config` a stable package was not allowed to depend on a prerelease package.   WIth `PackageReference` this is now allowed.  Are you able to migrate the project to `PackageReference`?

**Comment by tonyqus** [comment]
I can except that this is expected behavior (I know Microsoft style very well).

However, is it possible to update the project template for .NET framework 4.7.2 in VS2022? You should directly use PackageReference in the new template so that developers can get rid of legacy packages.config if the project is newly created.

**Comment by jeffkl** [comment]
> However, is it possible to update the project template for .NET framework 4.7.2 in VS2022?

Yes that could probably be done.  The NuGet team does not own these templates though so I think your best bet would be to use the Visual Studio Feedback tool to file this request.

**Comment by tonyqus** [comment]
Ok. I understand this is not your team's scope. 

But frankly speaking, I give up.  Microsoft is too huge and it's very hard to reach the correct team and deliver the feedback even if the feedback is valid. It takes days or months just to reach the correct developer and get it fixed. I don't have so much time.
