### ISSUE TITLE
Feature Request: Allow hard copy of  ContentFiles without the need for a separate target to copy the files.

### ISSUE THREAD

**Issue by moh-hassan** [NuGet/Home#12252]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

I created a package that contain files either using nuspec files as described in [nuget home samples](https://github.com/NuGet/Samples/blob/main/ContentFilesExample/authoring/ContentFilesExample.nuspec) or from csproj file using `<content ... or None`
```
 <ItemGroup>
    <Content Include="contentfiles\mytool.exe">
      <Pack>true</Pack>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackageFlatten>true</PackageFlatten>
      <PackagePath>tools\any\any;content\any\any\tools;;contentFiles\any\any\tools</PackagePath>           
    </Content>
  </ItemGroup>
```
When I use this  package from a consumer project (net6 and net472), all files appear in visual studio as a link.
In VS code it's invisible at all and can not be reached although I use `PackageCopyToOutput`

Some of these contents are tools that I want to run from within the project using MsBuild  'Exec`` command.
These files are not physically copied and I can not call these linked tool (they are not symbolic link files). 

For example, run `dir' in the Console tool, don't list these files.
I know that i can use a target to copy these files as described in this [thread](https://github.com/NuGet/Home/issues/6743#issuecomment-473425762)

It's nice if there an attribute used to insure this physical copy of files (text, exe,...) without the extra effort in creating a target.

**Comment by erdembayar** [comment]
I believe we have dup issue, couldn't find in quick search.

**Comment by nkolev92** [comment]
Hey @moh-hassan 

Based on your description, we don't believe you need to copy the tools file into the output directory. 
You should never need to copy the tool into the output folder just to run it at build time. 

A few options:

* The package containing the tool could include a targets file that makes it easy to call the tool at build time. A community blog that's mostly up to date can be found here: https://natemcmaster.com/blog/2017/11/11/build-tools-in-nuget/.
* As a package consumer of a package without a targets file, you can use the automatically generated path property, https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty, for example: PkgSome_Package.

**Comment by moh-hassan** [comment]
@nkolev92 
Your solution is what I need 👍 . I'll try using them and feedback.

**Comment by moh-hassan** [comment]
@nkolev92, Thanks for help and support.
The [GeneratePathProperty](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty) is the black horse solution for tools, the next is an excerpt from  the docs:

>The package identity needs to be changed to an MSBuild friendly name, prefixed by the word **Pkg**. To verify the exact name of the property generated, look at the generated **nuget.g.props** file.
>Example:
```xml
<ItemGroup>
      <PackageReference Include="Package.With.Tools" Version="1.0.0" />
  </ItemGroup>

  <Target Name="TakeAction" AfterTargets="Build">
    <Exec Command="$(PkgPackage_With_Tools)\tools\tool.exe" />
  </Target>
```
It's nice if  there a demo for this scenario at [Nuget/samples](https://github.com/NuGet/Samples) 
My issue is resolved, thanks again.
