### ISSUE TITLE
NU5104 false positive when using the workaround from #6434

### ISSUE THREAD

**Issue by shuebner** [NuGet/Home#12265]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

17.4.0+18d5aef85

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Add a `PackageReference` with the pre-release exclusion workaround from #6434 (an issue that is now even linked to in [the official documentation](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges) like this:

```csproj
<PackageVersion Include="Abc" Version="[2.0.0, 3.0.0-0)" />
```

When executing `dotnet pack`, NU5104 will be triggered although the specified version range cannot be satisfied by a pre-release version.
This is an edge case of course, but it is precisely the workaround for pinning the major version to which the documentation links,  so at least this specific case with `<N>.#.#, <N+1>.0.0-0)` should be supported and not trigger NU5104.

The workaround `NoWarn="NU5104"` is cumbersome when using central package management.

**Comment by jeffkl** [comment]
@shuebner can you clarify more what exactly you're asking for?  It sounds like there is a suggested solution but that didn't work for you so I want to understand more.  If you have a package set and projects that exhibit the behavior that would also be helpful in understanding the ask.  Thanks!

**Comment by shuebner** [comment]
I am asking that NU5104 not be triggered when using the workaround from #6434.

> this specific case with <N>.#.#, <N+1>.0.0-0) should be supported and not trigger NU5104

This is reasonable because NU5104 in this case is a false positive anyway.

Example:
If you create a csproj like this, that uses the workaround:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
      
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[6.0.0, 7.0.0-0)" />
  </ItemGroup>

</Project>
```

and then call `dotnet pack` on it, you will get NU5104..
This is a false positive because `7.0.0-0` is the smallest pre-release version with a major version of `7` and thus no pre-release version can fulfil the range constraint.

If it were not for #6434, no-one would even care much about this edge case.
But, since we have to use the `-0)` technique for pinning the major version of a package reference, the NU5104 false positive is annoying.
Especially since we cannot suppress it globally on a `PackageVersion` element when using central package management.

**Comment by jeffkl** [comment]
Great, thanks for the clarification.

**Comment by shuebner** [comment]
It seems my reasoning was based on a wrong assumption as pointed out in #12424 https://github.com/NuGet/Home/issues/12424#issuecomment-1430538002

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/12424 is a dup, but it contains more details about the reasoning.

**Comment by jeffkl** [comment]
Here's the output for reference:

```
MSBuild version 17.8.0-preview-23367-03+0ff2a83e9 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  Test1 -> C:\Users\jeffkl\Desktop\Test1\bin\Release\net6.0\Test1.dll
C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): warn
ing NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Mi
crosoft.Extensions.Logging.Abstractions [6.0.0, 7.0.0-0)" or update the version field in the nuspec. [C:\Users\jeffkl\Desktop\Test1
\Test1.csproj]
  The package Test1.1.0.0 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package read
  mes are important.
  Successfully created package 'C:\Users\jeffkl\Desktop\Test1\bin\Release\Test1.1.0.0.nupkg'.
```

**Comment by nkolev92** [comment]
I'll work on improving the docs for these scenarios.

**Comment by nkolev92** [comment]
I have a PR out: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3281.
