### ISSUE TITLE
NuGet.Client repo introduced Microsoft.Web.XDT prebuilts during .NET 7.0.200 source-build

### ISSUE THREAD

**Issue by lbussell** [NuGet/Home#12261]
### NuGet Product Used

Other/NA

### Product Version

nuget.client commit 20be995d651808feb5cd48f30cb97197e497377c

### Worked before?

c0de924b0cfc8089f4ce1f35360cb9cddcd81138

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Build failure: https://github.com/dotnet/installer/pull/15018

Context: NuGet.Client is included in the .NET SDK. When building the SDK from source for Linux, we cannot download packages from the internet that we don't produce during our build. Microsoft.Web.XDT is consumed by NuGet.Client and also produced during a .NET build from source. We rely on using the property `MicrosoftWebXdtPackageVersion` to override the version used in this repo with the one we need at build-time. The change https://github.com/NuGet/NuGet.Client/commit/20be995d651808feb5cd48f30cb97197e497377c resulted in using a hardcoded version of 3.0.0. Instead, we should use the version `MicrosoftWebXdtPackageVersion` if it exists, otherwise use version 3.0.0 (or whatever other version this repo might need).

We can work around this right now using a patch, but this will need to be fixed as it is a regression ever since NuGet.Client adopted central package version management.

### Verbose Logs

```shell
/tarball/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1103: Unable to find a stable package Microsoft.Web.Xdt with version (>= 3.0.0) [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1103:   - Found 1 version(s) in source-built [ Nearest version: 7.0.0-preview.22423.2 ] [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1103:   - Found 1 version(s) in previously-source-built [ Nearest version: 7.0.0-preview.22423.2 ] [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1103:   - Found 0 version(s) in prebuilt [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.PackageManagement/NuGet.PackageManagement.csproj : error NU1103:   - Found 0 version(s) in reference-packages [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1103: Unable to find a stable package Microsoft.Web.Xdt with version (>= 3.0.0) [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1103:   - Found 1 version(s) in source-built [ Nearest version: 7.0.0-preview.22423.2 ] [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1103:   - Found 1 version(s) in previously-source-built [ Nearest version: 7.0.0-preview.22423.2 ] [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1103:   - Found 0 version(s) in prebuilt [/tarball/src/nuget-client/build/restorehelper.targets]
  /tarball/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks/NuGet.Build.Tasks.csproj : error NU1103:   - Found 0 version(s) in reference-packages [/tarball/src/nuget-client/build/restorehelper.targets]
```

**Comment by jeffkl** [comment]
Thanks for reporting, I’ll get this fixed right away

**Comment by jeffkl** [comment]
@lbussell I had searched for usages of properties in our repo but obviously I didn't realize they're used by others.  Do you know if this is the only property that we need back?  I see a few that we used to have:

https://github.com/NuGet/NuGet.Client/commit/20be995d651808feb5cd48f30cb97197e497377c#diff-02cd2ab756594450a21c2af84fa7c20ce24ed49788806320e553680f1ac48826L3-L14

Is there a definitive list of package properties that a repo must have that I can cross check or can you just spot check those and see if `MicrosoftWebXdtPackageVersion` is the only one we need back?

**Comment by lbussell** [comment]
> @jeffkl: Is there a definitive list of package properties that a repo must have?

Unfortunately, I don't have an exhaustive list for you. Any version properties introduced by @crummel should probably stay. I'm not seeing any more failures to restore after making the following change: https://github.com/dotnet/installer/pull/15018/commits/d238d9b6b6ffbc73ab200413d82656824edf5571.

NuGet.Client still fails to build after that change with the following error though:
```
    ...
    NuGet.PackageManagement -> /data/tb/15018/src/nuget-client/artifacts/NuGet.PackageManagement/bin/net7.0/NuGet.PackageManagement.dll
    NuGet.Packaging.Core -> /data/tb/15018/src/nuget-client/artifacts/NuGet.Packaging.Core/bin/net472/NuGet.Packaging.Core.dll
    NuGet.Packaging.Core -> /data/tb/15018/src/nuget-client/artifacts/NuGet.Packaging.Core/bin/netstandard2.0/NuGet.Packaging.Core.dll
    NuGet.Packaging.Core -> /data/tb/15018/src/nuget-client/artifacts/NuGet.Packaging.Core/bin/net7.0/NuGet.Packaging.Core.dll
  /data/tb/15018/src/nuget-client/build/build.proj(176,5): error MSB4181: The "MSBuild" task returned false but did not log an error.

  Build FAILED.

  CSC : error CS9057: The analyzer assembly '/data/tb/15018/packages/restored/system.text.json/7.0.0/analyzers/dotnet/roslyn4.4/cs/System.Text.Json.SourceGeneration.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [/data/tb/15018/src/nuget-client/src/NuGet.Core/NuGet.Build.Tasks.Console/NuGet.Build.Tasks.Console.csproj::TargetFramework=net7.0]
  CSC : error CS9057: The analyzer assembly '/data/tb/15018/packages/restored/system.text.json/7.0.0/analyzers/dotnet/roslyn4.4/cs/System.Text.Json.SourceGeneration.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [/data/tb/15018/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj::TargetFramework=net7.0]
  /data/tb/15018/src/nuget-client/build/build.proj(176,5): error MSB4181: The "MSBuild" task returned false but did not log an error.
      0 Warning(s)
      3 Error(s)
```

Do you think this could be package version related? It does look like you also touched the `Microsoft.Net.Compilers` version. Trying to figure out if there was a property for that. I'll try out a fix for that tomorrow morning.

**Comment by jeffkl** [comment]
It looks like the package is System.Text.Json right?  The NuGet.Client repo uses versions 6.0.0 version of that.  But yeah if we need another property let me know!
