### ISSUE TITLE
Unable to use UI to uninstall when another dependency isn't available for a target platform.

### ISSUE THREAD

**Issue by brettfo** [NuGet/Home#1226]
**REPRO:**
1.  Using VS2015, create a new portable class library targeting ".NET Framework 4.6", "Windows Universal 10.0", and "ASP.NET Core 5.0".
2.  Manually edit `project.json` and add two dependencies that don't support one of the target platforms.  E.g., add a dependency to "Serilog 1.5.9" and "IxMilia.Dxf 0.2.0", neither of which support ASP.NET Core 5.0.
3.  Open "Manage NuGet Packages" UI and filter to all installed packages.
4.  Try to uninstall any package.

**RESULT:**
`Package restore failed.  Rolling back package changes for '<library-name>'.`

**WORKAROUND:**
Manually edit `project.json`.

**Comment by emgarten** [comment]
This will be fixed in the next release. For uninstall scenarios the rollback has been removed.
NuGet/NuGet.packagemanagement@08bf877d0b32e89e0652f0cde346a942dc42cb93

**Comment by emgarten** [comment]
https://github.com/NuGet/Home/issues/1128
