### ISSUE TITLE
Package Manager Console Host Version 6.4.0.111 Garbled characters

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#12260]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/程序包管理器控制台主机版本-640111-乱码/10203703)._

---
程序包管理器控制台主机版本 6.4.0.111 乱码

dotnet publish 命令乱码

![2022-11-16 22 08 50.png](https://aka.ms/dc/image?name=Bd157fd5af3e24cdd90128823fb39370c638042046055504960_2022-11-16_22_08_50.png&tid=d157fd5af3e24cdd90128823fb39370c638042046055504960)

---
#### Feedback Bot on 11/16/2022, 06:37 PM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2022, 00:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by dominoFire** [comment]
Closing this NuGet issue in favor of dotnet/sdk issue https://github.com/dotnet/sdk/issues/29151
