### ISSUE TITLE
How to use nuget API to judge that these dependencies have build errors?

### ISSUE THREAD

**Issue by Smartisa** [NuGet/Home#12264]
### Discussed in https://github.com/NuGet/Home/discussions/12263

<div type='discussions-op-text'>

<sup>Originally posted by **Smartisa** November 22, 2022</sup>
For example, enter:
` <PackageReference Include="Flips" Version="2.4.3" />
    <PackageReference Include="CenterSpace.NMath.Standard.Windows.X64" Version="7.4.0.16" />`

NuGet API can return:
`NU1107 ERROR`</div>

**Comment by nkolev92** [comment]
Hey @Smartisa, 

The only way to determine whether a package will successfully install in a project is to attempt to install the package in that project.

What's the scenario in which you're attempting this?

Are you a user trying to change a package?
Do you have an extension that's trying to do some automated work?
