### ISSUE TITLE
VS 17.4.1 => Get-Project –All | Add-BindingRedirect => Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DarthSonic** [NuGet/Home#12273]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

17.4.1

### Worked before?

unknown

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Open Package Manager Console
2. Run "Get-Project –All | Add-BindingRedirect"
3. Result is:

```
Get-Project : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-Project –All | Add-BindingRedirect
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Project], NullReferenceException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.GetProjectCommand
```

**Comment by jeffkl** [comment]
@DarthSonic I'm unable to reproduce this issue, can you please supply a project I can load in Visual Studio that will cause this error to happen?

**Comment by DarthSonic** [comment]
Unfortunately, I am not allowed to share any code. Sorry.

**Comment by jeffkl** [comment]
> Unfortunately, I am not allowed to share any code. Sorry.

Totally get it.  Are you able to create a new project that exhibits this error that I could try out?  I'm wondering if its only related to a particular project type like web versus console app.

**Comment by DarthSonic** [comment]
> > Unfortunately, I am not allowed to share any code. Sorry.
> 
> Totally get it. Are you able to create a new project that exhibits this error that I could try out? I'm wondering if its only related to a particular project type like web versus console app.

I am not able to reproduce with newly create ASP.NET C# MVC project.

**Comment by erdembayar** [comment]
Does it still repro with your existing solution?
Without repro steps it's hard for us to investigate the issue.

**Comment by DarthSonic** [comment]
Cannot reproduce the exception anymore. Works now in VS 17.4.3.

**Comment by erdembayar** [comment]
Thank you reporting this issue. Considering this issue doesn't repro anymore I feel it's safe to close.
At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
