### ISSUE TITLE
PM UI versions drop-down should show vulnerability information

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#12279]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

When choosing which version to install in PM UI, it would be helpful if the drop down (on Search, Install, Update tabs), will show if a package is vulnerable, for example by adding a warning icon next to the version.

![image](https://user-images.githubusercontent.com/16807822/204671655-a70f3635-9f54-4b87-82d1-94bcd9fa171e.png)

Potentially aligning with the nuget.org view:
![image](https://user-images.githubusercontent.com/16807822/204671765-c2d60543-a951-4a85-ab01-a130a62b8205.png)
 

### Additional Context and Details

As we focus on showing vulnerability information in different parts of the VS UI, IMO this would help in making the experience consistent across the board.

**Comment by JonDouglas** [comment]
Duplicate of #11127
