### ISSUE TITLE
Return different exit codes for dotnet list package report command in case vulnerable/outdated/deprecated package detected

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#12286]
### NuGet Product Used

dotnet.exe

### Product Version

n/a

### Repro Steps & Context

Currently `dotnet list package --format json` command only returns 0 or 1. Here 1 means `successfully generated report` or 1 means [some issue with generating the report](https://github.com/NuGet/Home/blob/04b3ebec7868c09054f800af8996148e4e3b15c8/proposed/2022/DotnetListPackageMachineReadableJsonOutput.md).
Still customer have to parse json output to check if my report has any vulnerability/outdated/deprecated package.
Instead, we could use return [different application exit code ](https://tldp.org/LDP/abs/html/exitcodes.html) to signal customer if there is any vulnerability issue or not, it would save them time.
Related issue: https://github.com/NuGet/Home/issues/7752

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/11315 probably?

**Comment by erdembayar** [comment]
You're right.
