### ISSUE TITLE
CPM opt in detection in VS and commandline is different

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#12285]
1. dotnet new classlib
1. Change the project file to
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagePackageVersionsCentrally >true</ManagePackageVersionsCentrally>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" Version="6.4.0" />
  </ItemGroup>
</Project>
```

1. Restore on the commandline (succeed)
1. Load in VS.
![image](https://user-images.githubusercontent.com/2878341/204876611-ad4c60bd-f9d7-47c8-9474-5a2a01bcfc21.png)

The checks in VS and commandline are different. The reason is that the commandline implementation checks for the existence of the directory.packages.props file, but the VS one does not. 

These should be the same. 

2 ideas: 

- Do not require the directory.packages.props file to exist. This would be the project would fail on the commandline as well.
- set the ManagePackageVersionsCentrally property to true if and only if, the prop value is true and the file was imported. This would allow nomination to just work.

**Comment by jeffkl** [comment]
Team Triage: Simplify this: https://github.com/NuGet/NuGet.Client/blob/95d72977b8ed9f26a897fe1b048ac810495211c0/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#LL63C6-L63C36

**Comment by jeffkl** [comment]
I believe this will be addressed by https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CPS/pullrequest/453924?_a=overview which now will look at the `ManagePackageVersionsCentrally` property and the existence of a `Directory.Packages.props`.
