### ISSUE TITLE
NuGet.Client uses the wrong compiler when building in a source-build tarball.

### ISSUE THREAD

**Issue by lbussell** [NuGet/Home#12280]
### NuGet Product Used

Other/NA

### Product Version

.NET 6.0, 7.0, 8.0 source-build only

### Worked before?

This seems to have been an issue since nuget-client was added to .NET source-build.

### Impact

Other

### Repro Steps & Context

This applies to all versions of .NET 6.0, 7.0, and probably 8.0 as well.

When building in an end-to-end source-build tarball context, NuGet Client is using the "bootstrap" version of the compiler, instead of the version that was built earlier in the source-bulid from the Roslyn repo. This causes new CS9057 errors whenever the compiler version is different between our bootstrap SDK and the version we build in source-build. We can no-warn CS9057 but this should be addressed.

This is likely an issue with the way we try to use arcade in NuGet Client, since it isn't fully onboarded like other projects in the `dotnet` org.

cc @crummel who worked on the NuGet Client arcade infrastructure before.

**Comment by nkolev92** [comment]
Root issue is closed
