### ISSUE TITLE
[Bug Bash] [Suggestion] Suggest making version “0.0.0” an invalid instead of valid package version and not showing an invalid version in PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12283]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.5.0.108

### Impact

Other

#### Details about Problem
VS Version: Main\33129.147
NuGet Version: Dev\6.5.0.108
OS Version: Windows-11-Enterprise-22H2 ENU

#### Repro Steps:
1. Create a C# Console App (.NET Core 7.0) project in VS.
2. Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’ and select “nuget.org” in the source selection.
3. Click “Browse” tab and search package “afine” in the filter.
4. Select “afine” in the package list and click the “Version” drop-down list to observe.

#### Expected:
Suggest making version “0.0.0” an invalid instead of valid package version and not showing an invalid version in PM UI.

#### Actual:
There is a version “0.0.0” as below. 
![image](https://user-images.githubusercontent.com/20632625/204797610-0589707f-aa69-40c9-bc95-73b6297340e6.png)

#### Notes:
**1.This version “0.0.0” seems invalid in some national culture, like Chinese culture. So we suggest make it an invalid instead of a valid version.**
2.It’s not a regression, just a suggestion.

**Comment by jeffkl** [comment]
Team triage: The SemVer standard states that `0.0.0` is a valid version so we must support it.
