### ISSUE TITLE
PluginCredentialProvider not calling plugin correctly

### ISSUE THREAD

**Issue by hemisphera** [NuGet/Home#12287]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Credentials 6.4.0, CredentialProvider.Microsoft 1.0.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I am trying to integrate the NuGet SDK into a project of mine. I am not using `nuget.exe` or `dotnet.exe` for that matter, just the SDK (NuGet.Protocol and NuGet.Credentials). Because I need to access a NuGet feed that is hosted on Azure Artifacts, I am also using https://github.com/microsoft/artifacts-credprovider to provide me with credentials for accessing them.

I am however unable to make it to work. It appears that the PluginCredentialProvider class is calling the external provider .exe using the wrong arguments. Specifically: it does not pass `-F JSON` and therefore the credential response (even though working fine and returning the actual token) is returned in human readable format and not in `JSON`. PluginCredentialProvider therefore is unable to parse the response and thus fails.

Also: there is a specific switch for running that external .exe in `plugin` mode and not in `standalone` mode. But that switch is never passed anywhere. Is that correct?

Also: the argument `-C` for enabling an interactive UI login is never passed, and therefore DeviceCode flow is used, should credentials not be cached/available already.

I was able to make it work using the following argument injection trick:
````
var provider = new PluginCredentialProvider(GetLogger(), GetCredentialProviderPluginPath(), 20, "minimal -f JSON");
````
As you can see, I inject `-F JSON` as part of the `verbosity` parameter. Doing so passes it on to the credential provider which then returns the response in JSON and my token gets returned correctly.

I don't really understand why this does not work because apparently this .exe is used in VisualStudio and elsewhere. Is this PluginCredentialProvider also used by NuGet.exe itself? Does it work?

**Comment by nkolev92** [comment]
The matching code for working with the artifacts-credprovider plugin is https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Credentials/SecurePluginCredentialProvider.cs. 

It's used in all tooling, but in different preference order.

For example, in VS we prefer the MEF cred providers https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds
