### ISSUE TITLE
log.txt

### ISSUE THREAD

**Issue by NaattyD** [NuGet/Home#12294]
![log.txt](https://github.com/NuGet/Home/files/10150219/log.txt)

**Comment by NaattyD** [comment]
> ![log.txt](https://github.com/NuGet/Home/files/10150219/log.txt)

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
