### ISSUE TITLE
Spec for locals command: deleting an specific package from Global Packages Folder

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#12298]
Goal: Get this spec merged: https://github.com/NuGet/Home/pull/10427

**Comment by dominoFire** [comment]
Offline discussion: we need evaluate our options and workaround to delete a specific package from the global packages folder.

**Comment by CZEMacLeod** [comment]
Would be really useful to also delete the information for a specific package from the http-cache too (without deleting the global package folder).

**Comment by nkolev92** [comment]
Closing as https://github.com/NuGet/Home/issues/5713 will be enough for tracking purposes.
