### ISSUE TITLE
NuGet.Client repo has source-build prebuilts - Microsoft.Extensions.FileSystemGlobbing, Microsoft.Extensions.FileProviders.Abstractions

### ISSUE THREAD

**Issue by MichaelSimons** [NuGet/Home#12317]
The [latest dependency flow](https://github.com/dotnet/installer/pull/15115) of NuGet.Client into .NET broke source-build because it introduces a couple prebuilts:

Microsoft.Extensions.FileSystemGlobbing - 6.0.0
Microsoft.Extensions.FileProviders.Abstraction - 6.0.0

The best solution for this is to utilize a version property that source-build can override.  This pattern is demonstrated in [this PR](https://github.com/NuGet/NuGet.Client/pull/4941).

cc @jeffkl - can you help the source-build team on this?  TIA

**Comment by jeffkl** [comment]
Yes is there a definitive list of MSBuild package version properties so I can make sure we use them?  Or at least the properties we need to get this fixed?

**Comment by MichaelSimons** [comment]
[Here](https://github.com/dotnet/installer/pull/15115/files#diff-fccc902e8993c5790224a642410dbdaff7e26322bf1dbc17c3a510622f9a143f) is the change I think is needed - I am testing now in source-build to verify.

**Comment by jeffkl** [comment]
We do a validation of source build in our PR builds but it doesn't catch stuff like this.  I'd love a definitive list of properties and I could add something to our build that breaks if someone adds a package without a property.
