### ISSUE TITLE
The command "dotnet restore" failed to run with error “MSB4062 NuGet.Build.Tasks.GetRestoreSolutionProjectsTask task could not be loaded” after patching .NET SDK 3.1.4xx with NuGet Client release-5.7.x \5.7.4.4. 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12314]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet Client release-5.7.x\5.7.4.4 

### Impact

It's more difficult to complete my work

##### **Repro Steps:** 

1.Execute the [Patch dotnet SDK](onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/Manual%20tests/Test%20Cases/Package%20Signing%20Manual%20Test.one#Patch%20dotnet%20SDK&section-id={0344A15B-01B1-4828-AF4C-63FE53687F8A}&page-id={FD0E3C41-E7A8-4DE8-B83A-1A09FDB56271}&end)  ([Web view](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fteams%2FNuGet%2F_layouts%2FOneNote.aspx%3Fid%3D%252Fteams%252FNuGet%252FTeam%252FManual%2520tests%252FTest%2520Cases%26wd%3Dtarget%2528Package%2520Signing%2520Manual%2520Test.one%257C0344A15B-01B1-4828-AF4C-63FE53687F8A%252FPatch%2520dotnet%2520SDK%257CFD0E3C41-E7A8-4DE8-B83A-1A09FDB56271%252F%2529&data=05%7C01%7Cv-cicili%40microsoft.com%7C151b0f7ea8794d8dc5d208dad8c3f52e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638060633514410876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O3UkJs5pE19Of3HUIlAMBmd3nr17HeLff2Nr2ZnPgqo%3D&reserved=0))  

2.Clone [microsoft/MSBuildSdks: MSBuild project SDKs (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FMSBuildSdks&data=05%7C01%7Cv-cicili%40microsoft.com%7C151b0f7ea8794d8dc5d208dad8c3f52e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638060633514410876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LFAAABQt61i6mA%2F6igJo%2FSTNe5cGAmluu4JiSDFjqms%3D&reserved=0) 

3.Execute "dotnet restore" command on the patched SDK 

##### **Expected:** 

No error occurs and “Build succeeded” appears. 

##### **Actual:** 

The command "dotnet restore" failed to run with error ‘MSB4062 "NuGet.Build.Tasks.GetRestoreSolutionProjectsTask" task could not be loaded’ as below.
![image](https://user-images.githubusercontent.com/84695155/206414964-7b1c8669-a5db-430f-b11a-c59842459aab.png)

#### **Note:**
It is not a regression, it only repro on patching .NET SDK 3.1.4xx with NuGet Client release-5.7.x\5.7.4.4.

**Comment by v-luzh** [comment]
Notes: 
1. We updated the $SDKChannel to "3.1" in the script of SDKPatchTool before patching.
2. It reproes on all the 3 platforms: Windows\Linux\MacOS.

**Comment by heng-liu** [comment]
Thanks @CiciLi1 and @v-luzh filing this issue!
I could repro when patching sdk 3.1.x
But when using the sdk patched by dotnet.integration.test, the issue doesn't repro. 
So it should be an issue in patching script. 

After checking the patching script, it uses NuGet bits from netcoreapp5.0 folder instead of netstandard2.0, which is incorrect when patching sdk 3.1.x. 
So I fix the patching script by https://github.com/NuGet/Entropy/pull/103
Then I patched sdk 3.1 by using the updated script, and the restore worked and there is no issue.

Hi @CiciLi1 and @v-luzh, could you help check if it works? Thanks!

**Comment by CiciLi1** [comment]
> Thanks @CiciLi1 and @v-luzh filing this issue! I could repro when patching sdk 3.1.x But when using the sdk patched by dotnet.integration.test, the issue doesn't repro. So it should be an issue in patching script.
> 
> After checking the patching script, it uses NuGet bits from netcoreapp5.0 folder instead of netstandard2.0, which is incorrect when patching sdk 3.1.x. So I fix the patching script by [NuGet/Entropy#103](https://github.com/NuGet/Entropy/pull/103) Then I patched sdk 3.1 by using the updated script, and the restore worked and there is no issue.
> 
> Hi @CiciLi1 and @v-luzh, could you help check if it works? Thanks!

It works well now, thanks for the fix!

**Comment by heng-liu** [comment]
Thanks for the confirmation! @CiciLi1 
Closed as fixed.
