### ISSUE TITLE
Avoid passing TargetFramework as a global property when packing for projects that aren't multi-targeted

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#12323]
In https://github.com/dotnet/designs/pull/281, we are proposing that the TargetFramework will be included in the output path if it was set as a global property or if the project was multi-targeted.  Otherwise, it will not be part of the output path.

This causes an issue when doing a NuGet pack command, as the `_WalkEachTargetPerFramework` target runs the `_GetBuildOutputFilesWithTfm` target for each `TargetFramework`.  This means in this inner build the `TargetFramework` will be a global property, even if there is only one.

To fix this, the NuGet pack logic would need to change so that if there is only one target framework, it does not pass the `TargetFramework` global property in this case.

**Comment by aortiz-msft** [comment]
@dsplaisted - Could you please add us to the discussion for the design referenced above?

**Comment by dsplaisted** [comment]
@aortiz-msft I think your team has been part of the discussion.  This was the topic in two partner sync meetings so far, and I believe @nkolev92 was in and contributed to both.

EDIT: Note that this specific change to NuGet wasn't discussed in those meetings, I discovered the issue afterwards when working on the implementation.

**Comment by jeffkl** [comment]
Team Triage: Per offline discussion, this change might not be needed.  Feel free to re-activate if you feel otherwise.
