### ISSUE TITLE
Static graph restore failure when referencing unrestorable project

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#12322]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

.NET SDK 7.0.100; VS 17.5 internal preview

### Worked before?

Not a regression

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Given a project that has a `ProjectReference` to a project that doesn't import `NuGet.targets`, like `Something\Something.csproj` referencing the empty project `asdf.proj` in [GraphRestoreFailsOnUnrestorableReference.zip](https://github.com/NuGet/Home/files/10239519/GraphRestoreFailsOnUnrestorableReference.zip), graph-based restore can fail when non-graph-based restore succeeds.

```sh-session
❯ dotnet restore  -p:RestoreUseStaticGraphEvaluation=true .\Something\
  Determining projects to restore...
S:\play\alkestj\Something\Something.csproj : error NU1105: Unable to find project information for 'S:\play\alkestj\asdf.proj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing 
targets required for restore.
  Failed to restore S:\play\alkestj\Something\Something.csproj (in 54 ms).
```

Looking at the dgspec, non-graph restore elides the `projectReferences` entry for the reference to the non-restorable project, while graph restore includes it.

```diff
diff --git "a/.\\Something\\obj\\nongraph_Something.csproj.nuget.dgspec.json" "b/.\\Something\\obj\\Something.csproj.nuget.dgspec.json"
index 3468b15..e9b26cf 100644
--- "a/.\\Something\\obj\\nongraph_Something.csproj.nuget.dgspec.json"
+++ "b/.\\Something\\obj\\Something.csproj.nuget.dgspec.json"
@@ -32,7 +32,11 @@
         "frameworks": {
           "net7.0": {
             "targetAlias": "net7.0",
-            "projectReferences": {}
+            "projectReferences": {
+              "S:\\play\\alkestj\\asdf.proj": {
+                "projectPath": "S:\\play\\alkestj\\asdf.proj"
+              }
+            }
           }
         },
         "warningProperties": {
```

Since there is in fact no info for that project, this leads to a failure later.

**Comment by rainersigwald** [comment]
@jeffkl looked at this and identified that there's no equivalent of

https://github.com/NuGet/NuGet.Client/blob/d3639a5faaad1901fbf1dbb90f89585876ef0111/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/MSBuildRestoreUtility.cs#L109-L110

in graph restore.

**Comment by erdembayar** [comment]
I can repro this.
![image](https://user-images.githubusercontent.com/8766776/208518781-67328bf9-23e5-462d-8e71-1dc881834cb4.png)
