### ISSUE TITLE
Add the possibility to filter package where consolidation is required

### ISSUE THREAD

**Issue by FranckSix** [NuGet/Home#1232]
Add the possibility in the filter combobox to select all package in solution where a consolidation is required. When a package is selected chose by default the Action Consolidate.

This feature can help considerably in case when have some Assembly conflict.

**Comment by emgarten** [comment]
Which version of NuGet and Visual Studio are you using today?

**Comment by yishaigalatzer** [comment]
Is this about making a package match the same version across the whole solution?

**Comment by FranckSix** [comment]
VS 2015 with the built in nuget version. This version has alreaady the possibility to consolidate but I want a feature to spot package with version conflicts. This will permit rapidly to spot which assemblys does not match the same version across the whole solution.

**Comment by drphrozen** [comment]
:+1: 
![image](https://cloud.githubusercontent.com/assets/309670/9730849/82321e90-5619-11e5-9053-758768e8b459.png)

**Comment by drphrozen** [comment]
Maybe the title should be where consolidate is possible?

**Comment by mortenholmgaard** [comment]
:+1:

**Comment by RagingRudolf** [comment]
:thumbsup:

**Comment by dgg** [comment]
:+1:

**Comment by Machabeli** [comment]
:+1:

**Comment by rosrosros** [comment]
:+1:

**Comment by csharpfritz** [comment]
I like this discussion, and think this would add value.  Lets add it to the user interface discussion:  #1236

**Comment by dustinchilson** [comment]
:+1:

**Comment by yishaigalatzer** [comment]
Done! Thanks for the feedback.

![image](https://cloud.githubusercontent.com/assets/1238711/11195932/9c0a6152-8c69-11e5-89a7-4a5d098a138c.png)
