### ISSUE TITLE
NU5012: nuget pack is unable to find output exe on linux/mono

### ISSUE THREAD

**Issue by AqlaSolutions** [NuGet/Home#12334]
### NuGet Product Used

NuGet.exe

### Product Version

6.4.0

### Impact

I'm unable to use this version

### Repro Steps & Context

I have a .NET 6 sdk-style project with output type set to EXE. I build it with dotnet build on linux and then run `nuget pack`. It expects to see exe files in the output folder but on linux they don't have ".exe" extension which causes the error.

I can't use dotnet command to pack because I need the flag `IncludeReferencedProjects`, therefore `nuget` on mono is my only option.

### Logs

Error NU5012: Unable to find '/source/redacted/bin/Release/net6.0/redacted.exe'. Make sure the project has been built.

**Comment by zivkan** [comment]
@AqlaSolutions In https://github.com/NuGet/Home/issues/3891, multiple community members have posted ways to achieve the desired outcome, sometimes with using 3rd party tools, sometimes by using NuGet's extensibility within the MSBuild scripting language (which you can add to the csproj, or to a `Directory.Build.targets`, etc).

Unfortunately, NuGet.exe was created for, and designed for, .NET Framework (non-SDK style) projects, and packages.config. Even .NET Framework (a non-SDK style csproj) with PackageReferences will not have dependencies calculated correctly with `nuget.exe pack`. But the .NET SDK has many features that .NET Framework projects never had (for example, multi-targeting). As a consequence, nuget.exe pack for SDk style projects (or other PackageReference projects) isn't a supported scenario. Our position is that MSBuild pack is the officially supported pack for PackageReference projects (including all SDK style projects), and that MSBuild scripting can be used to extend most functionality not built-in.

**Comment by AqlaSolutions** [comment]
@zivkan , did you read the bug report? The issue is about ".exe" extension, not about `IncludeReferencedProjects`.

**Comment by zivkan** [comment]
You wrote:

> I can't use dotnet command to pack because I need the flag IncludeReferencedProjects, therefore nuget on mono is my only option.

With .NET Framework projects, all `<OutputType>exe` projects have extension `.exe` when compiled. It's only .NET Core target frameworks that don't have .exe extension for exe output types. .NET Core target frameworks are only supported with SDK style projects, not the "non-sdk" (some call it "legacy") project file types.
