### ISSUE TITLE
[Cross-platform Dotnet NuGet Sign] Duplicated “X.509 certificate chain validation” info showed after running command “dotnet nuget sign” and “dotnet nuget verify” on Windows

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12339]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 7.0.101

### Impact

It bothers me. A fix would be nice

#### Repro Steps:

1. Execute the [dotnet nuget sign pre-step](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FDotnet%20nuget%20sign%20pre-step%7C708e56b6-a296-493e-a615-e0e18c55f96f%2F%29&wdorigin=703&xsdata=MDV8MDF8fGJiMGU2NDY4NzA2ZDQ0ZWQzOWRmMDhkYWU5ODBiMDBifDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgwNzkwMzYxNDQ5NTc5MTl8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVFkzTWpNd05qZ3hNekkzTkRzeE5qY3lNekEyT0RFek1qYzBPekU1T2prellqVTBNbUZpTFdZeU1XTXRORFJqTWkwNE16aGhMVGN3WXpneVlUYzFNelk0Wmw5bU5EWTNZall6WWkwd05XSTRMVFF4Wm1VdE9EVmxNaTB5TkRGaFl6STRPVEZsWmpOQWRXNXhMbWRpYkM1emNHRmpaWE09fGFiYTExMjc3ZDRlZTRkMGUzOWRmMDhkYWU5ODBiMDBifDJlM2U5MGIyYjI2YTQyZWVhZDJmZThjZWIzMThiNDcw&sdata=YUwxQmlxODc0WGxNT2gzbEd0bGxMMnMyQkJScU1wUVd4eXVRUXppRFkxVT0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Cv-cicili%40microsoft.com).

2. On Windows: Create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile `(in the powershell "Developer Command Prompt").

3. Use the patched "dotnet.exe" to sign a package. Where <PackageFilePath> is the test package path and <PfxFilePath> is the file path to the .pfx file, sign the test package: 

On Windows: ` .\patchedSDK .\dotnet.exe nuget sign <PackageFilePath> --overwrite --certificate-path <PfxFilePath> --certificate-password password --timestamper http://timestamp.digicert.com/ -v n`

4. Verify that the package is signed successfully in the output, with no warnings and no errors

Package(s) signed successfully.

5. Use the patched "dotnet.exe" to verify a package. 

On Windows: ` .\patchedSDK .\dotnet.exe nuget verify <PackageFilePath> -v d` 

#### Expected: 

There is only one “X.509 certificate chain validation” info after step3 and step5.

#### Actual: 

Duplicated “X.509 certificate chain validation” info showed after step5 and step7 as below screenshot.
![image](https://user-images.githubusercontent.com/84695155/209935806-dbd393e7-fc87-441e-8ea2-c74a51b84238.png)

#### Note:
1. It only reproes on Windows, on Linux/MacBook the “X.509 certificate chain validation” info is:
```
X.509 certificate chain validation will use the fallback certificate bundle at '/home/jamie/Desktop/patchSDK/sdk/7.0.101/trustedroots/codesignctl.pem'.
X.509 certificate chain validation will use the fallback certificate bundle at '/home/jamie/Desktop/patchSDK/sdk/7.0.101/trustedroots/timestampctl.pem'.
```
2. It doesn't repro on .NET SDK 6.0.

**Comment by aortiz-msft** [comment]
@dtivel - Could this be related to recent changes in the area?

**Comment by v-luzh** [comment]
It also reproes on Cross-Platform Verify Test.

**Comment by nkolev92** [comment]
This was in an older sprint, so i moved it to the march one for now.
