### ISSUE TITLE
The feature “Transitive Package” doesn’t work in the “Installed” tab until reopening the .NET SDK style project  

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12333]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.5.0.135

### Impact

It bothers me. A fix would be nice

##### Repro Steps:  

1. Set the NUGET_TRANSITIVE_DEPENDENCIES_IN_PMUI environment variable to 1. 

2. Create a .NET Core Console App project via VS.  
3. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open PM UI.  
 4. Click “Browse” tab, search a package (e.g. “Microsoft.EntityFrameworkCore”) that has dependencies, select a package version “6.0.4” in the "Version" drop-down list in the right panel and click the “Install” button on the right.  
 5. Click “OK” button in the “Preview Changes” dialog and click “I Accept” button in the “License Acceptance” dialog.  
 6. Click “Installed” tab. 

##### Expected:  

The feature “Transitive Package” works in the “Installed” tab. “Transitive packages” label is expanded by default and all the transitive packages showed in the “Transitive packages” list (under the “Top-level packages” list). 

##### Actual:  

The feature “Transitive Package” doesn’t work in the “Installed” tab until reopening the .NET SDK style project as below. 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/84695155/209311969-03dce789-008c-415d-a22b-6c2a14559400.png)

##### Note: 

1. The feature “Transitive Package” will work in the “Installed” tab after reopening the .NET SDK style project and PM UI. 
2. Started to repro from Dev\6.5.0.117.

**Comment by kartheekp-ms** [comment]
I am able to reproduce the issue following the steps mentioned in the issue description. Please note I didn't set `NUGET_TRANSITIVE_DEPENDENCIES_IN_PMUI` environment variable to `1` because transitive packages feature is turned on by default.

**Comment by jebriede** [comment]
Regression introduced by https://github.com/NuGet/NuGet.Client/commit/e7ea3a13d3fc4738c375f2a48306d0cc46207e36. Investigating a fix.
