### ISSUE TITLE
WebSite projects opened from IIS fail to install packages

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12337]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

VS 17.4

### Worked before?

17.3

### Impact

I'm unable to use this version

### Repro Steps & Context

1. In IIS Manager, create a virtual directory as an application.
2. In VS, use "open website", select "local IIS", and then select the directory
3. Try to install a package that has `lib/<tfm>/*.dll` files.

An obscure error message is reported: 

> Failed to add reference to ‘Newtonsoft.Json’.
> 
> Invalid URI: The Authority/Host could not be parsed.

**Comment by aortiz-msft** [comment]
Triage: Let's revert the performance improvement as a first step, then explore how to bring the perf improvement back without breaking this scenario.
