### ISSUE TITLE
ManagePackageVersionsCentrally works in VS but not with dotnet CLI

### ISSUE THREAD

**Issue by jbe2277** [NuGet/Home#12347]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet: 7.0.101

### Impact

I'm unable to use this version

### Repro Steps & Context

I have enabled the ManagePackageVersionsCentrally with following commit:
https://github.com/jbe2277/waf/commit/3cc45a30193a758c674bfb8a83e886027876e35c

In Visual Studio 17.4.3 the restore works correct.

But with `dotnet CLI` I get following warnings which show that the version could not be read:

```
dotnet build ./src/System.Waf/System.Waf.sln -c Release

...
D:\a\waf\waf\src\System.Waf\Samples\InformationManager\AddressBook.Modules.Domain\AddressBook.Modules.Domain.csproj : warning NU1604: Project dependency NLog does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [D:\a\waf\waf\src\System.Waf\System.Waf.sln]
D:\a\waf\waf\src\System.Waf\Samples\InformationManager\AddressBook.Modules.Domain\AddressBook.Modules.Domain.csproj : warning NU1701: Package 'NLog 1.0.0.505' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'. This package may not be fully compatible with your project. [D:\a\waf\waf\src\System.Waf\System.Waf.sln]
  Restored D:\a\waf\waf\src\System.Waf\Samples\InformationManager\AddressBook.Modules.Domain\AddressBook.Modules.Domain.csproj (in 1.23 sec).
D:\a\waf\waf\src\System.Waf\Samples\InformationManager\AddressBook.Modules.Presentation\AddressBook.Modules.Presentation.csproj : warning NU1602: Waf.InformationManager.AddressBook.Modules.Domain does not provide an inclusive lower bound for dependency NLog. An approximate best match of NLog 1.0.0.505 was resolved. [D:\a\waf\waf\src\System.Waf\System.Waf.sln]
...
```

The build fails because the wrong (oldest found) version was restored for all Package Reference elements. This GitHub Action shows the Log (however, it might not exist for too long): https://github.com/jbe2277/waf/actions/runs/3858407691/jobs/6576907498

**Comment by kartheekp-ms** [comment]
Reading from https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#get-started doc, I guess you may have to rename `src/Directory.Build.props` to `src/Directory.Packages.props`. https://github.com/jbe2277/waf/commit/3cc45a30193a758c674bfb8a83e886027876e35c#diff-5c1900dca99df01c3ddc3a884282164b04deee76e79b176e2d34cfa47f3b8907

As per the docs linked above, `<PackageVersion />` items should be declared in your `Directory.Packages.props`.

**Comment by jbe2277** [comment]
@kartheekp-ms: Thanks for the solution. This solved my issue: https://github.com/jbe2277/waf/commit/3852bd20aac793da6b415070cf1c1a9e7b4b531d

However, it is strange that Visual Studio behaves different than the dotnet CLI. This makes it more difficult to find out what is wrong when it works correct within Visual Studio. Maybe related to this: 
- https://github.com/NuGet/Home/issues/12285
