### ISSUE TITLE
nuget.exe does not prompt for credentials under powershell

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1235]
1. Create a packages.config file with projects
2. Do not have have any credentials in nuget.config
3. _nuget.exe restore packages.config -Source https://www.myget.org/F/nuget-private-test/api/v2 -SolutionDirectory ._

Expected:
nuget.exe should prompt and wait for the credentials for be entered

Actual:
nuget.exe does not wait for input and a command line exception is thrown

Restoring NuGet package jQuery.1.10.0.
Restoring NuGet package dotNetRDF.1.0.8.3533.
Please provide credentials for: https://www.myget.org/F/nuget-private-test/api/v2
UserName: Please provide credentials for: https://www.myget.org/F/nuget-private-test/api/v2
UserName: WARNING: Unable to find version '1.10.0' of package 'jQuery'.
WARNING: Unable to find version '1.0.8.3533' of package 'dotNetRDF'.
Unable to find version '1.10.0' of package 'jQuery'.
Unable to find version '1.0.8.3533' of package 'dotNetRDF'.
Exception of type 'NuGet.CommandLineException' was thrown.

**Comment by emgarten** [comment]
After looking at this further it appears that this happens in both nuget.exe 3.0.0 and 2.8.6 when running in powershell. nuget.exe seems to treat powershell environments as non-interactive?

One difference I see is that 2.8.6 prints out a warning about non-interactive mode where as 3.0.0 does not mention this.

**Comment by yishaigalatzer** [comment]
@feiling is this issue resolved already?

**Comment by yishaigalatzer** [comment]
@feiling ping

**Comment by feiling** [comment]
This no longer repros. This user is prompted to input user name and password.
