### ISSUE TITLE
CPM:  VS for Mac's Test Explorer fails to load tests for CPM-managed test project 

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#12350]
### NuGet Product Used

Other/NA

### Product Version

6.3.1.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Extract the contents of [repro.zip](https://github.com/NuGet/Home/files/10368875/repro.zip).
2. In VS for Mac open WithCpm/WithCpm.sln.
3. On the main menu, navigate to View | Tests to open the Tests tool window.

Expected result:  The unit test will display.

Actual result:  The unit test does not display.

Observations:

1. If you open the test file (WithCpm/WithCpm/UnitTest1.cs), right-click in the method body of `Test1`, and select "Run Test(s)", the "Test Results" tool window will report `Unit test 'WithCpm.UnitTest1.Test1' could not be loaded.`
1. Opening a Terminal window, pathing to the WithCpm solution directory, and executing `dotnet test` successfully discovers and executes the test.
1. For comparison, repeat the repro steps on WithoutCpm/WithoutCpm.sln and the test will be discovered and execute as expected.

Not sure where the problem is (CPM, VS for Mac, or something else), but we'll start here.

CC @jeffkl

### Verbose Logs

```shell
Visual Studio Community 2022 for Mac
Version 17.4.2 (build 17)
Installation UUID: 70a4ce63-6d55-4c84-a017-063b14eab799
 
Runtime
.NET 6.0.12 (64-bit)
Architecture: Arm64
 
Roslyn (Language Service)
4.4.0-6.22578.12+3c6ab8e1715e5b080fb7bb77070810ab71e09387
 
NuGet
Version: 6.3.1.1
 
.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.101/Sdks
SDK Versions:
                7.0.101
                7.0.100-rc.1.22431.12
                6.0.404
MSBuild SDKs: Not installed
 
.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
                7.0.1
                7.0.0-rc.1.22426.10
                6.0.12
 
Xamarin.Profiler
'/Applications/Xamarin Profiler.app' not found
 
Updater
Version: 11
 
Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-12-13 00:02:45 UTC
 
Apple Developer Tools
Xcode 14.2 (21534)
Build 14C18
 
Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.
 
Xamarin.iOS
Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.
 
Xamarin.Android
Not Installed
 
Microsoft Build of OpenJDK
Java SDK: Not Found
 
Eclipse Temurin JDK
Java SDK: Not Found
 
Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-12-13 00:02:50 UTC
 
Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-12-13 00:02:50 UTC
 
Build Information
Release ID: 1704020017
Git revision: 7ef5413f2eec3351ce648085f619fc29fd8cb647
Build date: 2022-12-13 00:00:15+00
Build branch: release-17.4
Build lane: release-17.4
 
Operating System
Mac OS X 13.1.0
Darwin 22.2.0 Darwin Kernel Version 22.2.0
    Fri Nov 11 02:03:51 PST 2022
    root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64
 
Enabled user installed extensions
Log Monitor 0.7
```

**Comment by jeffkl** [comment]
VS for Mac is [being retired](https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/) so I'm going to close this for now.
