### ISSUE TITLE
Package Source Mapping with '*' not at the end matches wrong packages

### ISSUE THREAD

**Issue by cremor** [NuGet/Home#12367]
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI

### Product Version

.NET SDK 7.0.102, VS 17.4.4

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Use Package Source Mapping similar to the config shown [here](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#enabling-package-source-mapping).
2. Use a custom package in the project that only exists in the custom feed, but don't configure it in the Package Source Mapping.
3. Make sure that the custom package is not already in the global packages folder.
4. Try `dotnet restore` or building in Visual Studio.
5. Note that it shows an error because it can't find the custom package -> OK, as expected.
6. Add the line `<package pattern="*.something" />` to the custom package source mapping.
7. Try `dotnet restore` or building in Visual Studio.
8. Note that the restore/build works now -> Why? That dummy pattern doesn't match the package id! (The custom package does **not** end in `.something`!)

The [documentation](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping#package-pattern-syntax) mentions that the pattern needs to **end** with a `*`. But it seems like this is not enforced and leads to unexpected results when done differently.

**Comment by martinrrm** [comment]
I can repro this, when you have a leading `*` as a Pattern using PackageSourceMapping it will consider the pattern just as it was as a `*`

**Comment by aortiz-msft** [comment]
Triage: Hi there. Thanks for your feedback. Using a leading * is not a supported scenario. We have an existing issue to add validations to the pattern passed for Source Mapping here: https://github.com/NuGet/Home/issues/10783. Please feel free to upvote that issue.
