### ISSUE TITLE
[Cross-platform Dotnet NuGet Sign] An error occurred when adding the trust for certificate on Mac

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12369]
### NuGet Product Used

dotnet.exe

### Product Version

.Net SDK 7.0.102

### Impact

It's more difficult to complete my work

#### Repro Steps:
1. [Patched dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703).
2. Create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile `(in the powershell "Developer Command Prompt") on Windows.
3. Copy the .cer file(should be generated under the same path with .pfx file) and the .pfx file from the above Windows machine to macOS machine.
4. Add the trust for certificate: `./dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> -vsd <VersionedSdkDirectoryPath>`  on Mac.

#### Expected:
Adding the trust for certificate is successful.

#### Actual:
An error occurred when adding the trust for certificate as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/213104277-5cf743dc-3db0-4a5b-b948-4adf77bba291.png)
#### Notes:
1. The issue doesn’t repro on Windows & Linux.
2. The issue doesn’t repro on .NET SDK Version: 7.0.101 patched with Dev\6.5.0.136.

**Comment by aortiz-msft** [comment]
@heng-liu - Would you please take a quick look to see if this is a test issue?

**Comment by heng-liu** [comment]
The exception is thrown in a testing tool at https://github.com/NuGet/Entropy/blob/main/TrustTestCert/Program.cs#L68.
So I suppose this is a test issue.

But I haven't figured out why the X509Certificate2 constructer failed at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/UnixPkcs12Reader.cs#L270. 
I'll try to repro on a Mac machine and investigate.

**Comment by v-longmin** [comment]
Verify the issue on Dotnet SDK 7.0.200 with NuGet client dev\6.5.0.32, it's not repro, so close it, thanks.
