### ISSUE TITLE
The count of the transitive packages never changes in the “Installed” tab after installing transitive packages 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12360]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.5.0.140

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Create a .NET Core Console App project via VS.  
2. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open PM UI.  
3. Click “Browse” tab, search a package (e.g. “Microsoft.EntityFrameworkCore”) that has dependencies, select a package version (e.g. 6.0.4) in the "Version" drop-down list in the right panel and click the “Install” button on the right.  
4. Click “OK” button in the “Preview Changes” dialog and click “I Accept” button in the “License Acceptance” dialog.
5. Switch to the “Installed” tab, and Install a transitive package “Microsoft.Extensions.Logging” in the package list.

#### Expected:
The count of the transitive packages should show correctly (it should be 12 for this example).

#### Actual:
The count of the transitive packages never changes in the “Installed” tab (it showed 13 for this example) as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/212027396-429aece4-6814-4720-88ed-286ec8df147d.png)
#### Notes:
1. The count never changes no matter how many transitive packages are installed.
2. It started from Dev\6.5.0.129.

**Comment by jebriede** [comment]
Regression introduced by https://github.com/NuGet/NuGet.Client/commit/e7ea3a13d3fc4738c375f2a48306d0cc46207e36. Investigating a fix.
