### ISSUE TITLE
GlobalPackageReference is not working for legacy-style csproj projects

### ISSUE THREAD

**Issue by cremor** [NuGet/Home#12368]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 17.4.4

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create a solution with both a SDK-style csproj file and a legacy-style csproj file (e.g. .NET Framework project).
2. Add a NuGet package to both.
3. Enable Central Package Management per [documentation](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#).
4. Note that Central Package Management works fine for both project types.
5. Add a Global Package Reference (per [documentation](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#global-package-references)) to the `Directory.Packages.props` file, e.g. [PolySharp](https://www.nuget.org/packages/PolySharp/).
6. Note that the global package reference works in the SDK-style project but is **not** working in the legacy-style project.

`<PackageReference>` and the base feature of Central Package Management both work with legacy-style csproj files, so why doesn't `<GlobalPackageReference>` work too?

**Comment by jeffkl** [comment]
Thanks for reporting this issue.  I'll work on getting this fixed but it will take a while to be generally available.  To make GlobalPackageReference work for legacy CSPROJ projects for now, you'll need to specify this instead in your Directory.Packages.props:

```xml
<ItemGroup>
  <PackageReference Include="Some.Global.Package" IncludeAssets="Runtime;Build;Native;contentFiles;Analyzers" PrivateAssets="All" />
  <PackageVersion Include="Some.Global.Package" Version="1.0.0" />
</ItemGroup>
```

**Comment by jeffkl** [comment]
https://github.com/NuGet/NuGet.Client/pull/5064 didn't fix it after all, so re-opening until https://github.com/NuGet/NuGet.Client/pull/5092 is in.
