### ISSUE TITLE
After using the DeleteWorksheet method of SpreadsheetLight to delete the excel sheet, error will be prompted when opening the file

### ISSUE THREAD

**Issue by wangminh** [NuGet/Home#12366]
### NuGet Product Used

Other/NA

### Product Version

SpreadsheetLight  3.4.11

### Impact

None

### Repro Steps & Context

error: 削除された機能: /xl/workbook.xml パーツ内の名前付き範囲 (ブック)
If move the sheet of the deleted object to the last position in the template, it seems that no error will occur。
Maybe the order in the source code is reversed。
wbp.DeletePart(sRelId);
slwb.Sheets.RemoveAt(i);

**Comment by martinrrm** [comment]
We don't support individual packages, so you can go to https://www.nuget.org/packages/SpreadsheetLight and use the [contact owners](https://www.nuget.org/packages/SpreadsheetLight/3.5.0/ContactOwners) link to contact the package author for help.
