### ISSUE TITLE
Central Package Management warning NU1507

### ISSUE THREAD

**Issue by Tibe31** [NuGet/Home#12371]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 7

### Impact

None

### Repro Steps & Context

I'm trying out the new [Central Package Management](https://devblogs.microsoft.com/nuget/introducing-central-package-management/) feature in NuGet.

As stated in the documentation, if you use multiple NuGet sources (which I use), it is now required to configure the Package Source Mapping in a nuget.config file, otherwise you should get a NU1507 warning.

My simplified file tree is this:

- **MySolution.sln**
- **Proj1.csproj**
- **MyLibrary\\** (this is an external repository with all my shared projects)
         - **Directory.Packages.props**
         - **nuget.config**
         -  **Proj2\\** (an example library project)
         - **Proj2\\Proj2.csproj**

Here is the **Proj1.csproj** content:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <PropertyGroup>
        <DefaultItemExcludes>$(DefaultItemExcludes);MyLibrary\**\*</DefaultItemExcludes>
    </PropertyGroup>
</Project>
```

Here is **Directory.Packages.props**:

```
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="JetBrains.Annotations" Version="2022.1.0" />
    </ItemGroup>
</Project>
```

Here is **nuget.config**:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <clear/>
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json"/>
        <add key="Custom NuGet" value="https://nuget.mydomain.net/"/>
    </packageSources>

    <packageSourceMapping>
        <packageSource key="nuget.org">
            <package pattern="*"/>
        </packageSource>
        <packageSource key="Custom NuGet">
            <package pattern="MyNamespace.*"/>
        </packageSource>
    </packageSourceMapping>
</configuration>
```

and **Proj2.csproj**:

```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
</Project>
```

In the [official documentation](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied) the **MyLibrary\nuget.config** should be used when restoring the packages because it is in the parent directory of **Proj2.csproj**, and actually it works when I build the solution via dotnet build, but when I build it in Visual Studio I still get the NU1507 warning.

I know that I could work around the issue by copying the nuget.config file in the same directory as the solution file (the warning goes away), but I have hundreds of projects that include the MyLibrary directory and I'd like to keep all the configuration centralized.

Moreover it works as expected when it's built from the command line, so what am I doing wrong?

**Comment by martinrrm** [comment]
Hi! Thanks for filling the issue, can you check which version of VS are you using? Can you add a screenshot of the Error and the tree view of your solution? Can you add a <clear/> in packageSourceMapping?

**Comment by Tibe31** [comment]
Hi! Thank you for your answer, i'm using VS 17.4.4 but i have the same problem also with Rider so it seems independent from IDE.
Below the screenshots of the NU1507 warning and the tree view of my solution:

![image](https://user-images.githubusercontent.com/117848094/214784867-8f0a4012-acd5-4412-8109-2992fb1c45a5.png)

![image](https://user-images.githubusercontent.com/117848094/214787661-6fbe94d1-03bb-4c93-81d2-c65681aea6d6.png)

**Comment by jeffkl** [comment]
@Tibe31 I set up a solution with two projects, one using CPM and the other not.  Everything works in Visual Studio.  Here's what how I set it up:
[solution.zip](https://github.com/NuGet/Home/files/10559552/solution.zip)
```
│   nuget.config
│   Solution.sln
│
├───ClassLibrary1
│       Class1.cs
│       ClassLibrary1.csproj
│
└───ClassLibrary2
        Class1.cs
        ClassLibrary2.csproj
        Directory.Packages.props
        nuget.config
```
If you can repro it with a simple solution, please attach it so I can investigate.

**Comment by Tibe31** [comment]
@jeffkl Thank you for your answer! Your set up is a bit different from mine, as you can see in my first question at the top of the page, this is my tree structure:

MySolution.sln
Proj1.csproj
MyLibrary\ (this is an external repository with all my shared projects)
- Directory.Packages.props
- nuget.config
- Proj2\ (an example library project)
- Proj2\Proj2.csproj

Here is the zip with my solution:
[test-nuget-config.zip](https://github.com/NuGet/Home/files/10567120/test-nuget-config.zip)

**Comment by zivkan** [comment]
@Tibe31 from our docs: https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

> Note that if a config file is placed in a project folder, it has no effect on that project.

In VS, we only load config files starting from the solution directory. While I'm confident that restoring a single project on the command line will load configs from the project directory, I think that even restoring the sln file on the command line will also not load the config in the subdirectory.

Therefore, nuget.config files in submodules are not supported. On linux/mac I'd suggest making a nuget.config symlink pointing to the submodule nuget.config, but symlinks are not commonly used on Windows and I don't know if they behave in the same way. Otherwise, your best option is to copy the nuget.config into the repo using the submodule.

**Comment by zivkan** [comment]
I created this PR to updae the docs to make it more clear. https://github.com/NuGet/docs.microsoft.com-nuget/pull/2990

**Comment by zivkan** [comment]
I just merged the docs PR, thanks for bringing it to our attention. The docs repo still needs the main branch merged into the live branch (in the past someone in the team would do it about once a month), but hopefully the new docs are more clear about the scenario.

**Comment by Tibe31** [comment]
@zivkan Thanks a lot for your reply and clarification!
