### ISSUE TITLE
Restoring sln file restores project with improper configuration/platform pairs

### ISSUE THREAD

**Issue by mathieubourgeois** [NuGet/Home#12375]
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild version "17.4.1+9a89d02ff"

### Worked before?

Unsure

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I am trying to port a solution to .Net 6. In the process, I've noticed a weird issue with the restore. In VS, everything works fine. However, when building from MSBuild, I am getting extra assemblies copied to my output folder which shouldn't be there based on the configuration.

After analysis of the binlog, I've narrowed it down to the combination of NuGet and a project with a conditional `ProjectReference`. Under some `Configuration` values, I have a reference to the project or not. However, when building with the `Configuration` that shouldn't have this project referred, it still gets copied (along with its dependencies) to the output. The reason seems to be from the fact that I am restoring a solution file. More specifically, I have :

- Sln file
  - Solution Configuration|Platform pairs : `Debug|x64` and `Release|x64`
- Multiple csproj, each with their own set of Configuration|Platform pair, which don't necessarily match

When looking at the evaluation of the restore project in the binlog, it becomes pretty clear what the source of the problem is : when doing the restoring evaluation in the csproj, `Configuration` and `Platform` end up being those of the solution, and not those of the actual project being restored. This is why the unreferenced project ends up copied, because NuGet evaluated it in a Configuration|Platform pair where the `ProjectReference` is actually used.

I narrowed down the actual source of the issue, which is the `_LoadRestoreGraphEntryPoints`, more specifically, the `GetRestoreSolutionProjectsTask` task inside the target. The `RestoreGraphProjectInputItems` items generated are of the following fashion :

```
<RestoreGraphProjectInputItems Include="Path/to/the/file.csproj" >
  <AdditionalProperties>Configuration=Release; Platform=x64</AdditionalProperties>
  <Platform>AnyCPU</Platform>
  <Configuration>RedactedProjectConfiguration</Configuration>
  <ToolsVersion>Current</ToolsVersion>
  <SkipNonexistentProjects>Build</SkipNonexistentProjects>
</RestoreGraphProjectInputItems>
```

And that's where the problem becomes (relatively) clear. The `AdditionalProperties` are passed straight to the restore MSBuild tasks, and they contain the solution configuration/platform pairs, which override the whole thing and cause the issue. The reason why I'm suggesting this is a problem coming from `GetRestoreSolutionProjectsTask` is because this task takes into input `ProjectReference` from the solution, which, in this case, can be of the `.metaproj` variety. This task then removes the .metaproj and considers it as a valid restore input. Which is fair, except for the fact that the csproj and its metaproj file are actually different : specifically, a metaproj file seems to be a wrapper on top of the csproj, and works based on Solution-level logic (i.e. Solution-level configuration and platform), while the csproj is actually based on that csproj' configuration and platform. When going from a metaproj back to a csproj, we are forgetting to go back from the solution configuration/platform to the csproj configuration/platform.

I have a solution to circumvent the issue, though it is not exactly long-term proof : we can add the following `after.$(SolutionName).sln.targets` file next to the solution, with the following content :

```
<Project>
  <Target Name="_PatchNugetSolutionProjectReferences" DependsOnTargets="_LoadRestoreGraphEntryPoints" BeforeTargets="_FilterRestoreGraphProjectInputItems" Returns="@(RestoreGraphProjectInputItems)">
    <ItemGroup>
      <RestoreGraphProjectInputItems Update="$(RestoreGraphProjectInput)">
        <AdditionalProperties>Configuration=%(RestoreGraphProjectInputItems.Configuration); Platform=%(RestoreGraphProjectInputItems.Platform)</AdditionalProperties>
      </RestoreGraphProjectInputItems>
    </ItemGroup>
  </Target>
</Project>
```

With this, I'm doing (essentially) what I'm saying is missing, i.e. regenerate the `AdditionalProperties` for the projects based on the actual `Configuration`/`Platform` pair that's provided and that the csproj will run on normally. It's not exactly perfect (this relies on the fact that `AdditionalProperties` only contains Configuration and Platform, and that the `Configuration` and `Platform` metadata attributes are indeed the csproj-level Configuration and Platform.

This solution seems to be sufficient on my end to circumvent the issue, but I think a proper fix would make more sense. I'm willing to give it a try if that can help, however I am unsure if what I'm proposing, even if cleaned up, is sufficient. A cleaner version of what I did would be to parse and rewrite the `AdditionalProperties` in `GetRestoreSolutionProjectsTask` to only modify `Configuration` and `Platform`. However, we'd still rely on the (maybe correct, but I'm not sure) assumption that the `Configuration` and `Platform` metadata are the actual csproj-level properties.

**Comment by jeffkl** [comment]
It is not currently supported to have NuGet restore pivot on any property other than `TargetFramework`.  The main input to restore is a project/solution and optionally a target framework.  For the most part, restore is supposed to be agnostic to the configuration, platform, or any other property.  This is because the restore can be re-used for multiple builds and the result should be the same.  Consider this:

* `msbuild /Target:Restore /Property:Something=Value`
* `msbuild /Property:Something=AnotherValue`

The build can be affected by these properties and have different outputs, but the restore should be generic and be the same.  Otherwise you cannot re-use restore and would have to restore before every build in order to have things work as expected.  It's also a bit of a support burden that users can set custom properties that alter their restore outputs and then have failing builds where the errors do not necessarily correlate to restore.  So the design at the moment is to have restore be agnostic to any other inputs.  

Of course this is all just MSBuild which allows you to do pretty much anything you want, which you've shown a workaround for.  But at this time we have no plans to make restore take into consideration custom inputs.
