### ISSUE TITLE
Automatically detect and include readme/license/icon file when packing

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#12385]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe, NuGet SDK

### The Elevator Pitch

Understand desired experience (auto include or not)
Understand readme/license/icon file convention (path, naming etc.)
Automatically detect and include readme/license/icon file if the file exists.

**Comment by heng-liu** [comment]
Updates: meeting with Azure SDK team and Entity Framework team and send out summaries and follow-up emails.

**Comment by jebriede** [comment]
Team Triage: This feature would have the potential negative side-effect of bringing in readme and icon files that are not intended to be included in the nupkg.
