### ISSUE TITLE
Nuget.exe CLI not getting correct versions when running in -ExcludeVersion mode

### ISSUE THREAD

**Issue by Pxtl** [NuGet/Home#12384]
### NuGet Product Used

NuGet.exe

### Product Version

Nuget 6.4.0.123

### Worked before?

unknown

### Impact

I'm unable to use this version

#### Context

When using Install -ExcludeVersion mode and changing the desired version in packages.config, Nuget.exe does not actually replace the package with the desired version.  Note that this issue only occurs when the packages are already cached -- if the cache is freshly cleared using `nuget locals all -clear`, this does not occur.  `-nocache` does not help.

#### Repro Steps

In powershell, in a fresh folder, execute the following:

    if(Test-path packages) {rm packages -r}

    '<?xml version="1.0" encoding="utf-16"?>
    <packages>
      <package id="SqlServer" version="21.0.17099" />
    </packages>' > packages.config

    '<?xml version="1.0" encoding="utf-16"?>
    <configuration>
      <packageSources>
        <clear />
        <add key="PSGallery" value="https://www.powershellgallery.com/api/v2/" />
      </packageSources>
      <config>
        <add key="repositoryPath" value=".\packages" />
      </config>
    </configuration>' > nuget.config

    Write-Output "* INSTALLING OLD VERSION *"

    nuget install packages.config -excludeversion -verbosity detailed

    Write-Output "* DOWNLOADED VERSION: $((Import-PowershellDataFile "./packages/SqlServer/SqlServer.psd1").ModuleVersion) *"

    '<?xml version="1.0" encoding="utf-16"?>
    <packages>
      <package id="SqlServer" version="21.1.18245" />
    </packages>' > packages.config

    Write-Output "* INSTALLING NEW VERSION *"

    nuget install packages.config -excludeversion -verbosity detailed

    Write-Output "* DOWNLOADED VERSION: $((Import-PowershellDataFile "./packages/SqlServer/SqlServer.psd1").ModuleVersion) *"

See in the logs below, the DOWNLOADED VERSION remains unchanged after the second `nuget install` command.

### Verbose Logs

```shell
* INSTALLING OLD VERSION *
NuGet Version: 6.4.0.123
Feeds used:
  C:\Users\zaratem\.nuget\packages\
  https://www.powershellgallery.com/api/v2/

Restoring NuGet package SqlServer.21.0.17099.
Adding package 'SqlServer.21.0.17099' to folder 'C:\temp\NugetBugDemo\packages'
Added package 'SqlServer.21.0.17099' to folder 'C:\temp\NugetBugDemo\packages'
Added package 'SqlServer.21.0.17099' to folder 'C:\temp\NugetBugDemo\packages' from source 'C:\Users\zaratem\.nuget\packages\'
* DOWNLOADED VERSION: 21.0.17099 *
* INSTALLING NEW VERSION *
NuGet Version: 6.4.0.123
Feeds used:
  C:\Users\zaratem\.nuget\packages\
  https://www.powershellgallery.com/api/v2/

Restoring NuGet package SqlServer.21.1.18245.
Adding package 'SqlServer.21.1.18245' to folder 'C:\temp\NugetBugDemo\packages'
Added package 'SqlServer.21.1.18245' to folder 'C:\temp\NugetBugDemo\packages'
Added package 'SqlServer.21.1.18245' to folder 'C:\temp\NugetBugDemo\packages' from source 'C:\Users\zaratem\.nuget\packages\'
* DOWNLOADED VERSION: 21.0.17099 *
```

**Comment by martinrrm** [comment]
I was able to repro this, this only happens with the flag -ExccludeVersion, this will create a folder with the package name only, doing a second install does not update the previous package files.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/11016.
