### ISSUE TITLE
Package not found while restoring causes ArgumentNullException

### ISSUE THREAD

**Issue by bhaeussermann** [NuGet/Home#12381]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Commands 6.4.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

See the following code used for restoring a NuGet package:

```
public async Task RestoreAsync()
{
    var packageToRestore = new PackageIdentity("FluentAssertions", NuGetVersion.Parse("6.8.0"));

    var progressCallback = new Action<string, TraceLevel>((message, traceLevel) => Console.WriteLine(message));
    var machineWideSettings = new MachineWideSettings();
    var settings = Settings.LoadDefaultSettings(null, null, machineWideSettings);

    using var sourceCacheContext = new SourceCacheContext();
    var restoreArgs = new RestoreArgs
    {
        AllowNoOp = true,
        CacheContext = sourceCacheContext,
        CachingSourceProvider = new CachingSourceProvider(new PackageSourceProvider(settings)),
        ConfigFile = null,
        DisableParallel = false,
        Runtimes = new HashSet<string>(),
        FallbackRuntimes = new HashSet<string>(),
        RequestProviders = new List<IRestoreRequestProvider>(),
        Sources = new List<string>(),
        GlobalPackagesFolder = null,
        HideWarningsAndErrors = false,
        Inputs = new List<string>(),
        IsLowercaseGlobalPackagesFolder = false,
        LockFileVersion = null,
        ValidateRuntimeAssets = null,
        Log = Logger.Create(progressCallback),
        MachineWideSettings = machineWideSettings,
        PackageSaveMode = PackageSaveMode.Defaultv3
    };
    restoreArgs.PreLoadedRequestProviders.Add(
        new DependencyGraphSpecRequestProvider(
            new RestoreCommandProvidersCache(),
            GetDependencyGraph(packageToRestore)));

    await RestoreRunner.RunAsync(restoreArgs);
}

private DependencyGraphSpec GetDependencyGraph(PackageIdentity package)
{
    var frameworkName = new FrameworkName(".NETCoreApp,Version=v6.0");

    var packageSpec = ToolRestoreUtility.GetSpec(
        Path.Combine(Path.GetTempPath(), $"{package.Id}{package.Version}.csproj"),
        package.Id,
        new VersionRange(package.Version),
        new NuGetFramework(frameworkName.Identifier, frameworkName.Version, ".NETCoreApp", new Version("6.0")),
        Path.Combine(Path.GetTempPath(), "TestNuGet"),
        new List<string>(),
        new List<PackageSource> { new PackageSource(@"https://api.nuget.org/v3/index.json") },
        new WarningProperties());

    var dependencyGraphSpec = new DependencyGraphSpec();
    dependencyGraphSpec.AddProject(packageSpec);
    dependencyGraphSpec.AddRestore(packageSpec.Name);
    return dependencyGraphSpec;
}
```

Running the code unchanged works. However, if I either:
- change the ID of the `PackageIdentity` to a package that does not exist, eg. "NonExistent", or
- change the version to one that doesn't exist, eg. "99.0.0"

I get the exception `System.ArgumentNullException : Value cannot be null. (Parameter 'path')`
I would expect a more informative exception.

The same exception also occurs when restoring while the package source cannot be reached (eg. internet connection down).
To reproduce:
- Debug the code and set a breakpoint on the first line of the method
- Clear the _%temp%\TestNuGet_ folder
- Clear the NuGet cache
- Disable all network adaptors that connect to the internet
- Continue debugging

The exact same `ArgumentNullException` is thrown.

**Comment by jeffkl** [comment]
Your custom code is calling `ToolRestoreUtility.GetSpec()` which probably isn't the best way to do this.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/ToolRestoreUtility.cs#L22

I would recommend you create the `PackageSpec` yourself so that you have more control over the output.  Some of the NuGet Client public API surface isn't maintained anymore and `ToolRestoreUtility` isn't something we're currently looking at improving.

Here are more examples of how to create a `PackageSpec` object: https://github.com/search?q=repo%3ANuGet%2FNuGet.Client+%22new+PackageSpec%22&type=code
