### ISSUE TITLE
Show an infobar in Solution Explorer for any detected security vulnerabilities in a project or solution

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#12398]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

When a project or solution are loaded and NuGet restore detects any security vulnerability, Visual Studio should provide an embedded infobar mentioning one or more vulnerabilities has been detected and a link to go to the package manager UI to address them.

![image](https://user-images.githubusercontent.com/1288848/215889142-30b86882-e1f6-4248-be44-d7e13a5e40ea.png)

**Comment by JonDouglas** [comment]
@martinrrm can we close as done?

**Comment by martinrrm** [comment]
@JonDouglas the PR is in review still
