### ISSUE TITLE
Show a Visual Studio notification when a vulnerability is detected

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#12399]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

In addition to #12398, a notification should appear in Visual Studio's notification center with a link to the package manager UI to address issues.

The notification will let the user know what package in what project/solution is vulnerable or its plural equivalent. i.e. `Known security vulnerabilities have been detected in your project(s)/solution`.

![image](https://user-images.githubusercontent.com/1288848/215889414-0cf1c648-0149-4958-a223-5c25a575020e.png)

**Comment by JonDouglas** [comment]
@martinrrm can we close this as done or dupe of the solution explorer infobar?

**Comment by martinrrm** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/12398, we will continue exploring other ways to show notifications using VS mechanisms.

**Comment by nkolev92** [comment]
Reopening to change the closing status as not planned
