### ISSUE TITLE
Plan for NuGet in 2023

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#12407]
Today we are excited to share with you the plan for NuGet and NuGet.org. This issue contains summary of the plan for the year and acts as a place for you to leave feedback.

This plan is a collection of input from many stakeholders and outlines where we intend to invest our time in NuGet and NuGet.org.

> **IMPORTANT**
> This plan is not a commitment; it will evolve as we continue to learn throughout the release. Some things that are not currently planned for NuGet may get pulled in. Some things currently planned may even be pushed out.

# General information

NuGet has a major release following [NuGet 6.4](https://docs.microsoft.com/nuget/release-notes/nuget-6.4) and is currently scheduled for release in November 2023 at the same time as .NET 8.

NuGet will align with the [.NET support policy](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) and will therefore be a long-term support (LTS) release.

NuGet.org does not currently follow any specific schedule and releases features & bug fixes regularly throughout the year.

### Breaking changes

NuGet may contain a small number of breaking changes as we continue to evolve NuGet with the .NET platform. Our goal is to minimize breaking changes as much as possible to keep you productive when upgrading. You'll be able to find them at the [.NET 8 Breaking Changes](https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0).

## Themes

The large investments in NuGet are the following themes:

### Highly Requested Features

As always, a major input into our planning process comes from [votes (👍) for features on GitHub](https://github.com/NuGet/Home/blob/dev/CONTRIBUTING.md#before-submitting-an-issue).

These features are areas we are actively engaged in with regards to designing, implementing, and polishing the respective experiences for.

#### Security

- https://github.com/NuGet/Home/issues/8087
- https://github.com/NuGet/Home/issues/1851
- https://github.com/NuGet/Home/issues/11262
- https://github.com/NuGet/Home/issues/10730
- https://github.com/NuGet/Home/issues/12015
- https://github.com/NuGet/Home/issues/4387
- https://github.com/NuGet/Home/issues/12497

#### Tooling

- https://github.com/NuGet/Home/issues/9015

#### Season of Giving

- https://github.com/NuGet/Home/issues/7752
- https://github.com/NuGet/Home/issues/8476
- https://github.com/NuGet/Home/issues/8420
- https://github.com/NuGet/Home/issues/7912
- https://github.com/NuGet/Home/issues/6938
- https://github.com/NuGet/Home/issues/6437
- https://github.com/NuGet/Home/issues/6279
- https://github.com/NuGet/Home/issues/6060
- https://github.com/NuGet/Home/issues/5713
- https://github.com/NuGet/Home/issues/5556
- https://github.com/NuGet/Home/issues/5138
- https://github.com/NuGet/Home/issues/4879
- https://github.com/NuGet/Home/issues/4855
- https://github.com/NuGet/Home/issues/4254
- https://github.com/NuGet/Home/issues/4103

#### NuGet Gallery

- https://github.com/NuGet/NuGetGallery/issues/3098
- https://github.com/NuGet/NuGetGallery/issues/8773
- https://github.com/NuGet/NuGetGallery/issues/8964
- https://github.com/NuGet/NuGetGallery/issues/9339
- https://github.com/NuGet/NuGetGallery/issues/7297

### .NET Platforms and Ecosystem

Much of the work planned for NuGet involves improving the package management experience for .NET across different platforms and ecosystem. This involves work in NuGet to ensure a great experience across .NET technologies.

- https://github.com/NuGet/Home/issues/10430
- https://github.com/NuGet/Home/issues/10872
- https://github.com/NuGet/Home/issues/5154

### Migrating to .NET

NuGet has always [supported many scenarios for package management](https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference). In our continued efforts to help you migrate to the latest version of .NET, we will be working on improvements to the [Upgrade Assistant](https://github.com/dotnet/upgrade-assistant) and core package management experiences to help you migrate your project to use the latest version of NuGet.

## Performance

With each [new release of NuGet & Visual Studio comes a plethora of performance improvements](https://devblogs.microsoft.com/visualstudio/performance-improvements-in-nuget/) when restoring NuGet packages, managing project dependencies, and browsing for the next great package to include in your solution. We will continue to invest time to improve your experiences every .NET & Visual Studio release.

# Feedback

Your feedback is important to us. The best way to indicate the importance of an issue is to vote (👍) for that [issue on GitHub](https://github.com/NuGet/Home/issues) and [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We use this data to help us with our regular planning so we can work on the things that matter most to you.

Please **comment on this issue** if you believe we are missing something that is critical for NuGet, or are focusing on the wrong areas. Give us a little bit of context as to why you believe so and feel free to upvote each other's comments to help us make changes to our future plans.

Huge thanks to @ajcvickers and the Entity Framework Core team for a wonderful format and forum to discuss product plans in OSS. 🎉

Last year's plan can be found in https://github.com/NuGet/Home/issues/11571

**Comment by marco-carvalho** [comment]
@JonDouglas any chance of https://github.com/NuGet/Home/issues/4387 being prioritized?

**Comment by JonDouglas** [comment]
@marco-carvalho I believe that one and #12015 are related. Can you check if that's the case? Will add them both until we de-dupe.

**Comment by Varorbc** [comment]
Could you please include #12473 in the plan?

**Comment by JonDouglas** [comment]
@Varorbc we will triage this issue, but right now it is too new to include in the plan although it is an excellent suggestion.

**Comment by zlsmith86** [comment]
Can https://github.com/dotnet/sdk/issues/9500 be included as well?

**Comment by baronfel** [comment]
@zlsmith86 dotnet/sdk#9500 (and dotnet tools generally) is owned by the SDK team, not the NuGet team, and so isn't in scope for NuGet's 2023 plan. We (the SDK team) are actively working on it though - see the linked PR from that issue.

**Comment by smarts** [comment]
Can #1851 and #6437 be handled together? Seems like the problems are fairly similar, no?

It's not clear to me why 6437 is not categorized under **Security**, and why it's not prioritized higher. It's got more 👍🏼 votes than nearly all of the items in that category.

**Comment by zivkan** [comment]
@smarts I think that https://github.com/NuGet/Home/issues/12539 is a better solution than #6437, at least for CI scenarios. It should also be much easier to implement. Unfortunately I have too many other higher priority things to have worked on it myself yet, but I think it might be simple enough for someone else to contribute, if someone wants to try before I, or someone else in the team, finds time to do it ourselves.

**Comment by smarts** [comment]
Got it, thank you! 🙂

**Comment by JonDouglas** [comment]
Hi friends,

In preparation for the next year, I'm going to close this plan. We made significant progress on many fronts. Not everything is documented but here is a taste of what was done besides what was closed in various issues above. There are some issues that still need closing as their functionality has shipped or will be shipped soon.

Releases:

- https://devblogs.microsoft.com/nuget/announcing-nuget-6-8-maintaining-security-with-ease/
- https://devblogs.microsoft.com/nuget/announcing-nuget-6-7-keeping-you-secure/
- https://devblogs.microsoft.com/nuget/announcing-nuget-6-5-the-sweetest-way-to-manage-your-packages/

Feature Blogs:

- https://devblogs.microsoft.com/nuget/introducing-search-by-target-framework-on-nuget-org/
- https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/
- https://devblogs.microsoft.com/nuget/https-everywhere-update/
- https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-4/#nuget-auditing-package-dependencies-for-security-vulnerabilities

NuGet Tooling:
- [2023 Features](https://github.com/NuGet/Home/issues?q=is%3Aissue+label%3AType%3AFeature+is%3Aclosed+closed%3A2023-01-01..2023-12-31)

NuGet Gallery:
- [2023 Features](https://github.com/NuGet/NuGetGallery/issues?q=is%3Aissue+label%3Afeature-request+is%3Aclosed+closed%3A2023-01-01..2023-12-31)

Epics:

- https://github.com/NuGet/Home/issues/8087
- https://github.com/NuGet/Home/issues/12301
- https://github.com/NuGet/Home/issues/12413

New/Closed Proposals:
- [Created Proposals](https://github.com/NuGet/Home/pulls?q=is%3Apr+created%3A2023-01-01..2023-12-31+is%3Aopen)
- [Merged/Closed Proposals](https://github.com/NuGet/Home/pulls?q=is%3Apr+closed%3A2023-01-01..2023-12-31+is%3Aclosed)

To help us for next year, please go through our issues/prs on all our https://github.com/NuGet/Home#repos-and-projects and please upvote, comment, and contribute where you think is appropriate!

Thank you for all your help in making this year great.

**Comment by Frulfump** [comment]
Where's the plan for 2024 and 2025? The 2023 issue was closed by linking to this issue would have been nice if that trend continued.
