### ISSUE TITLE
Package not found while restoring causes ArgumentNullException

### ISSUE THREAD

**Issue by bhaeussermann** [NuGet/Home#12402]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Commands 6.4.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Reopened from #12381 after fixing the repro code.

See the following code used for restoring a NuGet package:

```
public async Task RestoreAsync()
{
    var packageToRestore = new PackageIdentity("FluentAssertions", NuGetVersion.Parse("6.8.0"));

    var progressCallback = new Action<string, TraceLevel>((message, traceLevel) => Console.WriteLine(message));
    var machineWideSettings = new MachineWideSettings();
    var settings = Settings.LoadDefaultSettings(null, null, machineWideSettings);

    using var sourceCacheContext = new SourceCacheContext();
    var restoreArgs = new RestoreArgs
    {
        AllowNoOp = true,
        CacheContext = sourceCacheContext,
        CachingSourceProvider = new CachingSourceProvider(new PackageSourceProvider(settings)),
        ConfigFile = null,
        DisableParallel = false,
        Runtimes = new HashSet<string>(),
        FallbackRuntimes = new HashSet<string>(),
        RequestProviders = new List<IRestoreRequestProvider>(),
        Sources = new List<string>(),
        GlobalPackagesFolder = null,
        HideWarningsAndErrors = false,
        Inputs = new List<string>(),
        IsLowercaseGlobalPackagesFolder = false,
        LockFileVersion = null,
        ValidateRuntimeAssets = null,
        Log = Logger.Create(progressCallback),
        MachineWideSettings = machineWideSettings,
        PackageSaveMode = PackageSaveMode.Defaultv3
    };
    restoreArgs.PreLoadedRequestProviders.Add(
        new DependencyGraphSpecRequestProvider(
            new RestoreCommandProvidersCache(),
            GetDependencyGraph(packageToRestore)));

    await RestoreRunner.RunAsync(restoreArgs);
}

private DependencyGraphSpec GetDependencyGraph(PackageIdentity package)
{
    var frameworkName = new FrameworkName(".NETCoreApp,Version=v6.0");
    var nugetFramework = new NuGetFramework(frameworkName.Identifier, frameworkName.Version, ".NETCoreApp", new Version("6.0"));
    var versionRange = new VersionRange(package.Version);
    string packageName = $"{package.Id}-{nugetFramework}-{versionRange.ToNormalizedString()}".ToLowerInvariant();
    string projectFilePath = Path.Combine(Path.GetTempPath(), $"{package.Id}{package.Version}.csproj");

    var packageSpec = new PackageSpec
    {
        Name = packageName,
        FilePath = projectFilePath,
        Dependencies = { },
        TargetFrameworks =
        {
            new TargetFrameworkInformation
            {
                TargetAlias = nugetFramework.GetShortFolderName(),
                FrameworkName = nugetFramework,
                Dependencies =
                {
                    new LibraryDependency
                    {
                        LibraryRange = new(package.Id, versionRange, LibraryDependencyTarget.Package)
                    }
                }
            }
        },
        RestoreMetadata = new()
        {
            ProjectStyle = ProjectStyle.DotnetCliTool,
            ProjectName = packageName,
            ProjectUniqueName = packageName,
            ProjectPath = projectFilePath,
            PackagesPath = Path.Combine(Path.GetTempPath(), "TestNuGet"),
            FallbackFolders = { },
            Sources = { new PackageSource(@"https://api.nuget.org/v3/index.json") },
            OriginalTargetFrameworks = { nugetFramework.GetShortFolderName() },
            TargetFrameworks =
            {
                new ProjectRestoreMetadataFrameworkInfo
                {
                    TargetAlias = nugetFramework.GetShortFolderName(),
                    FrameworkName = nugetFramework,
                    ProjectReferences = { }
                }
            },
            ProjectWideWarningProperties = new WarningProperties()
        }
    };

    var dependencyGraphSpec = new DependencyGraphSpec();
    dependencyGraphSpec.AddProject(packageSpec);
    dependencyGraphSpec.AddRestore(packageSpec.Name);
    return dependencyGraphSpec;
}
```

Running the code unchanged works. However, if I either:
- change the ID of the `PackageIdentity` to a package that does not exist, eg. "NonExistent", or
- change the version to one that doesn't exist, eg. "99.0.0"

I get the exception `System.ArgumentNullException : Value cannot be null. (Parameter 'path')`
I would expect a more informative exception.

The same exception also occurs when restoring while the package source cannot be reached (eg. internet connection down).
To reproduce that scenario:
- Debug the code and set a breakpoint on the first line of the method
- Clear the %temp%\TestNuGet folder
- Clear the NuGet cache
- Disable all network adaptors that connect to the internet
- Continue debugging

The exact same `ArgumentNullException` is thrown.

**Comment by jeffkl** [comment]
@bhaeussermann where is this exception being thrown exactly?

**Comment by bhaeussermann** [comment]
@jeffkl Here is the stack trace that I get:
```
   at System.IO.Path.GetFullPath(String path)
   at NuGet.Commands.RestoreCommand.GetAssetsFilePath(LockFile lockFile)
   at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__45.MoveNext()
   at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
   at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
   at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__9.MoveNext()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
   at NuGet.Commands.RestoreRunner.<RunAsync>d__1.MoveNext()
   at TestNuGet.Tests.<Test>d__0.MoveNext() in C:\Projects\AdHoc\TestNuGet\UnitTest1.cs:line 55
```

**Comment by jeffkl** [comment]
@bhaeussermann what values are used in `GetAssetsFilePath()`?  I would imagine under the debugger you could figure out what part of the code is trying to pass `null` to `Path.GetFullPath()`.

**Comment by bhaeussermann** [comment]
@jeffkl I can't step into the code as the debugging symbols aren't there. However, the issue description above contains the complete code so it should be easy to reproduce.

**Comment by heng-liu** [comment]
Hi @bhaeussermann , just want to make sure if you unchecked "Enable Just My Code" in VS(Debug->Options ->Debugging) before debugging.
![image](https://user-images.githubusercontent.com/45407901/218209210-44197071-af7e-4e80-a791-83a2df6e4ba4.png)
 Please let us know if you still could not debug into it after unchecking "Enable Just My Code". Thanks!

**Comment by bhaeussermann** [comment]
Here's a screenshot of the code that is throwing the exception, as well as some key values. The path through which the `text` variable ends up being null can be easily traced.

Once again, the code I've provided above should enable you to reproduce the error. Let me know if you need anything else to reproduce it.

![2023-02-13_07h23_05](https://user-images.githubusercontent.com/7482216/218377510-5f31095a-d33a-42fa-83fd-21b4f057c482.png)

**Comment by nkolev92** [comment]
@bhaeussermann 

You're still using the ProjectStyle.DotnetCliTool, which is the equivalent of what was being done with ToolRestoreSpec. 

That's a special implementation that's no longer in use, and that's an implementation that wrote the assets file in the packages location. 

You're basically entering [here ](https://github.com/NuGet/NuGet.Client/blob/b84ca7373557c5725836697f81786ed22e20ead5/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L735-L747)and it's all null cause the package doesn't exist.

I'd recommend switching to PackageReference style and populating things like OutputPath to get it working.

**Comment by bhaeussermann** [comment]
@nkolev92 Thanks! Using `ProjectStyle.PackageReference` yields the expected outcome when the package is not found.
