### ISSUE TITLE
Unable to Update Nuget packages that run powershell scripts

### ISSUE THREAD

**Issue by princeo911** [NuGet/Home#1240]
When I try to update some packages that run powershell scripts, I get an a warning about running the script which stops the update from continuing. The warnings appear in the package manager console, the only way to come out of it is to terminate visual studo.
I will attach the images in the next comment. I think there is a link of these issues and Visual Studio Update 5.

**Comment by princeo911** [comment]
![updating json](https://cloud.githubusercontent.com/assets/13858033/9428926/c60710f4-49b6-11e5-9843-1b007351b532.png)
![updating json2](https://cloud.githubusercontent.com/assets/13858033/9428929/c988d816-49b6-11e5-8be2-fc03c7f0175e.png)

**Comment by eriawan** [comment]
@princeo911 
Have you tried to run Visual Studio as administrator? Please run Visual Studio as administrator. 
I have used this workaround before. Please let me know if it's working or not.

**Comment by yishaigalatzer** [comment]
Are you seeing this specifically with json.NET 7.0.1 or other packages as well?

**Comment by emgarten** [comment]
@princeo911 is P:\ mapped to a UNC shared?

**Comment by princeo911** [comment]
@yishaigalatzer I am seeing this with any package that runs powershell script.I will create a new demo solution and see if this happens with it. I have 6 projects and they all seem to have the same problem

**Comment by princeo911** [comment]
@emgarten  No its a partition off my SSD, I Think if there was a way for me to answer the prompts when the script is running or ability to suppress the prompts, this problem will go away.

**Comment by princeo911** [comment]
@eriawan I always run visual studio as administrator, and I do have UAC control on so anything doing admin stuff pops up. That is not the issue here.

**Comment by emgarten** [comment]
There was a powershell bug in NuGet 2.8.6 which comes with Update 5. Update to the latest 2.8.7 version from the extension gallery and see if you still get this prompt.

**Comment by princeo911** [comment]
Sorry I have been trying to get 2.8.7, and I cant seem to find it anywhere. Been looking in the updates folder but no luck, please help

**Comment by princeo911** [comment]
Sorry I found the visx file in releases tab on nuget/home.
The issue has gone away. the version on my machine is 2.8.60723.765

I have manged to update some packages.

Thank you for your help.

**Comment by emgarten** [comment]
@princeo911 glad to hear it fixed your issue, thanks for the update on the issue!
