### ISSUE TITLE
install.ps1 on Nuget 3.1

### ISSUE THREAD

**Issue by iskiselev** [NuGet/Home#1241]
According to NuGet 3.1 release notes, it is not clear, if install.ps1/uninstall.ps1 was deprecated at all or only for projects that use project.json.
So should it be run if I install some old package to common Net 4.5 (4.6) console application?
Currently it doesn't work, that breaks expected behavior for some packages. Even worse, it doesn't warn end user, that some features was disabled and may not work correct.
See nunit/nunit-vs-adapter#77 as example of such problem (there install.ps1 marked all added references with CopyLocal=false)

**Comment by yishaigalatzer** [comment]
I'll update the content shortly.

Install.ps1 is running, so my guess is that there is an issue with the scripts in nunit. I've suggested some things to verify for the nunit folks, and we can take another look once these have been done.

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/1245

**Comment by yishaigalatzer** [comment]
Also the text is quite clear IMHO (perhaps we should add a big bold note below)

> Starting with NuGet 3.1 when using project.json, we are deprecating support for executing the install.ps1/uninstall.ps1 scripts and delivering elements in the /content folder of packages. Installing packages that have these elements will not execute the install.ps1 file and will not copy content to your project. There are several reasons for these decisions:

**Comment by yishaigalatzer** [comment]
Blog updated
