### ISSUE TITLE
NU5104 (stable package should not use prerelease) should not warn when upper version uses -0

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12424]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

all

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

NU5104 basically says that SemVer stable versions of packages should not take dependencies on prelreease versions of packages. According to https://github.com/NuGet/Home/issues/6434#issuecomment-1323572424 this warning triggers when the version range `[1.0.0, 2.0.0-0)` is specified.

However, and upper exclusive range of `2.0.0-0` explicitly means that no pre-release version of 2.0.0 will match since `-0` is the lowest possible prerelease version, and exclusive bound means that it won't allow the exact match. Therefore, the `-0` and the NU5104 are trying to achieve the exact same thing, so it shouldn't be warning.

**Comment by nkolev92** [comment]
When a range is specified with either a lower or upper boundary of prerelease it *opts* in the package into prerelease versions, so I'm not certain it's the right behavior. By specifying a stable range only, you'll only get prerelease versions if another component in the graph asks for a prerelease version of the package.

**Comment by zivkan** [comment]
> When a range is specified with either a lower or upper boundary of prerelease it opts in the package into prerelease versions

I'm trying to understand what this actually means. There is no project property "allow prerelease versions", so I'm unfamiliar what "opts into prerelease versions" changes. And as you've described in other issues, the upper bound pre-release won't be used unless another package's dependency tries to use it as the lower bound.

Say a feed has versions `1.2.0-beta.1` and `1.2.0`. If I specify `Version="[1.0.0, 2.0.0]"` on my PackageReference, are you saying that I'll get version `1.2.0`, whereas if I request version `[1.0.0, 2.0.0-0)`, I'll get the `1.2.0-beta.1` version?  That's not what the docs on [pre-release versions](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#pre-release-versions) says.

**Comment by nkolev92** [comment]
> Say a feed has versions 1.2.0-beta.1 and 1.2.0. If I specify Version="[1.0.0, 2.0.0]" on my PackageReference, are you saying that I'll get version 1.2.0,

You get 1.2.0. 

> whereas if I request version [1.0.0, 2.0.0-0), I'll get the 1.2.0-beta.1 version?

You get 1.2.0-beta.1

I can see how the docs are confusing in this case. This is a missing version scenario and the lowest version in the range is resolved when the lower version is missed.

**Comment by shuebner** [comment]
Duplicate of #12265.
However, the opt-in argument is new to me and invalidates my reasoning.

**Comment by nkolev92** [comment]
Closing this is as duplicate of https://github.com/NuGet/Home/issues/12265.
