### ISSUE TITLE
[Bug Bash] The transitive packages will not disappear in the “Installed” tab after uninstalling the top-level package

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12428]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.6.0.19

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Create a C# Console App (.NET Core 7.0) project in VS.
2. Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3. Click “Browse” tab, search a package (e.g. “Microsoft.EntityFrameworkCore”) that has dependencies and click the “Install” button (↓) on the right.
4. Click “OK” button in the “Preview Changes” dialog and click “I Accept” button in the “License Acceptance” dialog.
5. Click “Installed” tab and observe the package list.
6. Uninstall the top-level package (e.g. “Microsoft.EntityFrameworkCore”) and observe the package list in “Installed” tab.

#### Expected:
The transitive packages would disappear in the “Installed” tab.

#### Actual:
The transitive packages will not disappear in the “Installed” tab as below.
![image](https://user-images.githubusercontent.com/20632625/218050492-74e607bb-ba31-4472-a479-1384ade7c6ba.png)

#### Notes:
It doesn't repro on Dev\6.5.0.107, repro on Dev\6.5.0.127.

**Comment by nkolev92** [comment]
Team Triage; @jebriede Can you please check if this is related to the current transitive deps bug you are looking at?

**Comment by jebriede** [comment]
> Team Triage; @jebriede Can you please check if this is related to the current transitive deps bug you are looking at?

Yes! This is highly related and caused by the same regression affecting: https://github.com/NuGet/Home/issues/12333 and https://github.com/NuGet/Home/issues/12360
