### ISSUE TITLE
Icon is not shown for self hosted package

### ISSUE THREAD

**Issue by VSorokoumov** [NuGet/Home#12425]
### NuGet Product Used

MSBuild.exe

### Product Version

17.4.1+9a89d02ff 

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Create your own package with an icon defined in the MyLib.csproj

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <PropertyGroup>
      ...
      <PackageIcon>icon.png</PackageIcon>
      ...
   </PropertyGroup>

   <ItemGroup>
      ...
      <None Include="icon.png" Pack="true" Visible="false" PackagePath="" />
      ...
   </ItemGroup>
</Project>
```

2. Restore all project dependencies using NuGet v6.4.0

`nuget restore .\MyLib.csproj -PackagesDirectory .\packages`

3. Use MSBuild for packaging
`MSBuild .\MyLib.csproj -t:Pack -p:Configuration=Release`

4. Publish the package to JFrog Artifactory using JFrog CLI

```
cd bin/Release
jf rt u "*.nupkg" myrepo-nuget/MyLib/
jf rt u "*.snupkg" myrepo-nuget/MyLib/
```

5. Icon does not show up neither in JFrog Artifactory nor in the package list in JetBrains Rider.

6. icon.png file is included into the .nupkg archive

7. The resulting MyLib.nuspec includes  <icon>icon.png</icon> in the metadata section, and is missing any files or contentFiles sections.

**Comment by heng-liu** [comment]
Hi @VSorokoumov , I could not repro. Did you try to browse the package in VS?
I tried the following steps:
1. Use the same steps(above 1-3) to pack a test package. 
2. Confirmed the .nuspec file in the package contains `<icon>icon.png</icon>`.
3. Create a test project in VS, add a local package source which contains the package created in step1. 
4. Open Package Manager UI in VS, specified the above package source and go to the "Browse" tab
5. Check the icon of the package, it's displayed correctly.
If you can do the same, it might be some issue in JFrog Artifactory or JetBrains Rider.
