### ISSUE TITLE
Error message on installing package into C++ project could be more helpful

### ISSUE THREAD

**Issue by mlinehan17** [NuGet/Home#1242]
I was authoring a package and importing it into a C++ project.

I got this error:

“Could not install package '<package name>'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.”

The issue was that the name of the .targets file had not exactly matched the package name. I know that this is documented, but it would be good if the error message could mention this as one of the possible problems.

**Comment by yishaigalatzer** [comment]
Thanks for the suggestion. Sounds like something we could easily do (or would take a pull request for if you want to speed it up).

**Comment by nkolev92** [comment]
Thanks for reporting this issue. 
At this point, we have a lot of fixed in this issue and improved our error messaging. 

If you have similar problems, please file a new issue. 

Thank you.
