### ISSUE TITLE
I could run VS Code attached to a container using F5, but now I can't

### ISSUE THREAD

**Issue by Nefcanto** [NuGet/Home#12432]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe

### Current Behavior

This is what we do:

- We run a container that is customized from `mcr.microsoft.com/vscode/devcontainers/dotnet:7.0-bullseye-slim` and has once ran `dotnet restore` to cache all of the dependencies.
- Then we attach to it using `ms-vscode-remote.remote-containers`
- Then we hit <kbd>F5</kbd> to run it in debug mode
- Then we see that it actually tries to restore everything, and in the end, it gives us this error:

```
error : Unable to obtain lock file access on '/tmp/NuGetScratch/lock' for operations on '/home/user/test/NuGet.Config'. This may mean that a different user or administrator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file '/tmp/NuGetScratch/lock' will allow NuGet to continue.
```

### Desired Behavior

I don't know what is changed. NuGet? VS Code? Dev Containers? I have no idea. But before recent changes this was our procedure:

- We would run a container (that has ran `dotnet restore` once)
- We could attach to it
- We would hit <kbd>F5</kbd> and withing 500ms it would restore and run our code in debug mode

### Additional Context

Something stupid is changed here. I know that I should be polite. But you cause us so much pain that I should tell you how much I hate your decisions. Let us run everything as root.

I don't care if it's dangerous or not. I still choose it. I take the risks. But you don't let us do that.

Once inside the container, I want everything to be root.

We do all of these steps:

- setting `NUGET_SCRATCH=/Temp/NuGet`
- setting `NUGET_ConcurrencyUtils_DeleteOnClose=1`
- `sudo rm -rf obj`
- `sudo rm -rf bin`
- `sudo chown -R vscode:vscode /Temp/NuGet`
- `sudo chmod -R 777 /Temp/NuGet`

But when we hit <kbd>F5</kbd> we still see that it tries to restore everything and sometimes it works and sometimes it complains about that lock error.

Please, let us choose to run everything in the highest privilege everywhere. Give us options to run everything as root. Let us configure NuGet and dotnet and VS Code and every f***king thing to run as root.

**Comment by nkolev92** [comment]
Hey @Nefcanto, 

Which .NET SDK version is being used in your containers? 
Which was the version that worked previously?

**Comment by Nefcanto** [comment]
This is the `dotnet --info` from inside the container:

```
.root ➜ /Project/AdminApi $ dotnet --info
.NET SDK:
 Version:   7.0.103
 Commit:    276c71d299

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.103/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.103 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

I don't know which version was working. We constantly update our Docker images and our containers.

**Comment by JonDouglas** [comment]
Hi @Nefcanto,

Please edit your issue to be in-line with our [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct). While we understand your frustrations, it can be communicated in a respectful way. Otherwise we will close this issue.

**Comment by Nefcanto** [comment]
@JonDouglas, thank you for reminding me of that. The point is, your decision has made our team completely paralyzed for a month now. We had to literally change the way we code and remove containers from our API workflow, simply because NuGet team, or maybe VS Code team, or other teams in Microsoft had a breaking change that we could not figure out after days of frustration and tens of hours of man-hours.

That's cruelty towards small companies.

While I understand your point and I read your code of conduct, I won't change the issue's tone.

Please feel free to close this issue if you don't intend to address it. As we have decided to leave more and more Microsoft technologies. SQL Server to MariaDB, Windows to Linux, ASP.NET Razor Pages to React, and now .NET to Python.

That's it. Wherever we go to submit our feedback and frustration, instead of getting responses for changes that take us to the limit of technical failure, we get advice after almost a month of inactivity.

I hope that someday you learn the value of community back in Microsoft. If you want respect, you need to show respect first. And showing respect is not just about words. It's about caring about the pain the community has to suffer because of your decisions too.

Thank you again, have a good day.

**Comment by JonDouglas** [comment]
We are closing this issue due to a violation in our [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct) and refusal of remediation to the profanity and abusive language. This will serve as a warning for the future which can lead to a temporary ban.

All we ask is that you treat our repos, our people, and the issues you are communicating about with respect. While we can understand your frustrations with the situation, we do not tolerate inappropriate/abusive language.
