### ISSUE TITLE
project.assets.json should not contain username in it

### ISSUE THREAD

**Issue by erickulcyk** [NuGet/Home#12434]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

Currently, dotnet restore --locked generates project.assets.json, which contains the username of whomever ran the command.  This causes issues because every build in our CI loop there is new username (using a GUID), and so the hash of project.assets.json changes and downstream items rebuild.

### Desired Behavior

Username should be removed from project.assets.json.

### Additional Context

In some cases were are able to overwrite the username after nuget restore runs with a common value, but it becomes more tricky which the call to nuget restore is nested (like the build calls npm, which runs some javascript that then calls dotnet restore).

**Comment by nkolev92** [comment]
Hey @erickulcyk, 

The assets file is not designed to be roamable. 
It will always contain references to certain directories, and it does not explicitly burn in the username, but more often than not, the username is part of the paths where certain files are stored.
