### ISSUE TITLE
Setting EnablePackageVersionOverride to false does not cause an error when VersionOverride is used

### ISSUE THREAD

**Issue by sonnemaf** [NuGet/Home#12445]
### NuGet Product Used

MSBuild.exe

### Product Version

VS2022 Preview

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have set the `EnablePackageVersionOverride` property to `false`. It doesn't generate an error on the `VersionOverride` 

See this image below. 
![image](https://user-images.githubusercontent.com/9335559/220094085-bdb38892-d6c5-4ffb-8516-308c7557cfcb.png)

The [docs](https://devblogs.microsoft.com/nuget/introducing-central-package-management/#overriding-package-versions) mention that an error should be generated. This is not the case
![image](https://user-images.githubusercontent.com/9335559/220094670-f4316af0-638c-4845-8f75-c61e1f455776.png)

# Directory.Packages.props
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnablePackageVersionOverride>false</EnablePackageVersionOverride>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>
</Project>
```

# ConsoleApp1.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" VersionOverride="13.0.2" />
	</ItemGroup>

</Project>
```

**Comment by jeffkl** [comment]
@sonnemaf thank you for bringing this to our attention.  The documentation is wrong so I've updated the blog post and am working on getting the docs fixed (https://github.com/NuGet/docs.microsoft.com-nuget/pull/3011).  

The correct property name is `CentralPackageVersionOverrideEnabled`.

**Comment by kant2002** [comment]
@jeffkl I still see outdated page on the docs. Is this expected? Usually I seen changes applied almost immidiately on other docs.microsoft.websites.

**Comment by jeffkl** [comment]
Documentation changes first go into a `main` branch and then later on someone does a big merge from `main` to `live`.  That should be happening soon I believe.

**Comment by kant2002** [comment]
Thank you! I discover this issue when looking at the one Nuget bug which we discover in CPM and outdated docs a bit confuse us.
