### ISSUE TITLE
After migrating from package.config to package reference, properties are not shown on right click of referred nuget package.

### ISSUE THREAD

**Issue by anujk633** [NuGet/Home#12447]
### NuGet Product Used

Other/NA

### Product Version

Visual studio 2019

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Right click on a projects package.config file and you get an option to migrate from package.config to package reference, click it.

![image](https://user-images.githubusercontent.com/41225827/220343263-8ea14d93-b6ec-4a6b-8ece-05fd4f7a6918.png)

Once migration is done, go to any rereferred nuget package in References and try to see its properties, you will find everything as black i.e. no properties shown.

![image](https://user-images.githubusercontent.com/41225827/220343668-21e29bee-fadd-4c88-8d29-323aeeb80f8d.png)

I am not able to see any properties that I was able to see when package.config way of rereferring nuget package was used.
Can somebody help me out on this?

**Comment by zivkan** [comment]
@anujk633 can you please explain what it is you'd like to do? If properties were shown, how would you use it?

With PackageReference, if you want to do anything more advanced than install a package and use NuGet's default behaviour, you need to edit the project file and modify the PackageReference with the relevant MSBuild metadata as documented here: https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
For example, if you have two packages that define the same type name in the same namespace, so you need assembly aliases, here are the docs: https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-aliases
Note that with ".NET Framework" projects (non-SDK style), you need to unload the project to edit the project file. If you can migrate to SDK style projects (that can still target .NET Framework), you can right click the project and edit the csproj while the project is still loaded.

When using packages.config, the references node would show you all assemblies referenced by the project. When a package only contains a single assembly, and the assembly name matches the package name, it looks like it's listing the package in the References node, but it's not. When the package contains multiple assemblies, or none of the assemblies match the package name, then it's more obvious that it's showing something different.

The assemblies are known by IntelliSense, so unless something is wrong, you can add the appropriate `using` statements and access types from the package. 

Also note that PackageReference changes the way a small number of things work, so there are some incompatible packages: https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#package-compatibility-issues

Finally, if you're able to migrate your project to the new "SDK style" projects (they can still target .NET Framework, it's not only for .NET Standard and .NET Core/5+), then it will use a different project system in VS that will allow you to see more details like this:
![image](https://user-images.githubusercontent.com/5030577/222442674-2b657f76-e79f-4930-b969-0d9d48cf3a98.png)
