### ISSUE TITLE
License Acceptance Dialog - Missing keyboard accelerators

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1244]
From Visual Studio Feedback [428713]:

License acceptance dialog in NuGet doesn't support keyboard accelerators for "I Accept" and "I Reject" buttons.

**Comment by zhili1208** [comment]
@csharpfritz what's the keyboard accelerators for "I Accept" and "I Reject" buttons user want to support? like "Y" for "I Accept", "N" for "I Reject"?

**Comment by csharpfritz** [comment]
From other dialogs with License Acceptance, the terms are typically "I
Accept" and "I Decline".  In this case, make the A in Accept and the D in
Decline the accelerators.

See this example screenshot from the WebPI:
http://i.msdn.microsoft.com/dynimg/IC629169.png

Jeff
