### ISSUE TITLE
[Cross-platform Sign Verify] The “PackageSignatureVerificationLog” line lost after restoring the project with an expired certificate but timestamped package added on Windows

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12454]
### NuGet Product Used

dotnet.exe

### Product Version

 .NET SDK 7.0.104

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	Execute the [Pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FManual%20tests%2FTest%20Cases&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344A15B-01B1-4828-AF4C-63FE53687F8A%2FPre-testing%20steps%7C6E4370C3-C593-4B99-ABD8-908D0F9E002B%2F%29).
2.	Where <NotBefore> and <NotAfter> are datetime values that mark a 10-minute period starting now, create a short-lived test code signing certificate that will expire 10 minutes from now. 
              On Windows: ` .\dotnet\dotnet.exe run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net7.0 -- -nb "<NotBefore>" -na "<NotAfter>"  `
3.	Where <CertificateFilePath> is the file path to the .cer or .pem file in step 1 and <VersionedSdkDirectoryPath> is the directory path for the versioned .NET SDK directory (e.g.:  ./dotnet/dotnet/sdk/7.0.100), add trust for the certificate: 
              On Windows: ` .\dotnet\dotnet.exe run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath> `
4.	Where <PackageId> is the test package ID and <PfxFilePath> is the file path to the .pfx file, sign the test package: 
              On Windows:  `.\dotnet\dotnet.exe nuget sign .\<PackageId>\bin\Debug\<PackageId>.1.0.0.nupkg --overwrite --certificate-path <PfxFilePath> --timestamper http://timestamp.digicert.com/`
5.	Verify that the previous step succeeded with no warnings or errors. 
6.	Create a test project: 
              On Windows:  `mkdir .\test && pushd .\test && ..\dotnet\dotnet.exe new console && copy ..\NuGet.config.template .\NuGet.config  `
7.	Update NuGet.config to reference the SHA-256 fingerprint of the short-lived certificate created in step 2. 
8.	Clear local NuGet resources and previous restore results: 
               On Windows:  `rd /s /q .\obj && ..\dotnet\dotnet.exe nuget locals --clear all  `
9.	Where <PackageId> is the test package ID, add a package reference to the test package when the time is expired: 
               On Windows: ` ..\dotnet\dotnet.exe add package <PackageId> --version 1.0.0 `
10.	Verify that the previous step succeeded with the following message. 
              On Windows, the operation failed with the following messages: 
              info : X.509 certificate chain validation will use the default trust store selected by .NET. 
11.	Repeat step 8. 
12.	Restore: 
              On Windows:  `..\dotnet\dotnet.exe restore -v detailed`

#### Expected:
Where <PackageId> is the test package ID, verify that the previous step succeeded with following messages in the restore output. 
       On Windows: 
a.	X.509 certificate chain validation will use the default trust store selected by .NET. 
b.	PackageSignatureVerificationLog: PackageIdentity: <PackageId>.1.0.0 Source: E:\testpass\<PackageId>\bin\Debug PackageSignatureValidity: True 
c.	Build succeeded. 
    0 Warning(s) 
    0 Error(s) 

#### Actual:
The “PackageSignatureVerificationLog” line lost as the attached restore log.
[NoPackageSignatureVerificationLog.txt](https://github.com/NuGet/Home/files/10823448/NoPackageSignatureVerificationLog.txt)

#### Notes:
1.	It just repro on Windows platform.

**Comment by donnie-msft** [comment]
@dtivel could you look at the Expected section here and confirm you'd expect the same output? Thanks

**Comment by dtivel** [comment]
@v-luzh, I'm a bit confused.  There is no cross-verify test that has your steps 4 and 5.  Step 4 signs with a timestamp.  Step 5 verifies that you got a warning because you didn't timestamp.  It seems you're mixing up steps from different tests.  Can you please review repro steps and correct as necessary?

Also, I couldn't install 7.0.104, but 7.0.103 or 7.0.2xx.  This fails:
```
dotnet-install.ps1 -InstallDir .\dotnet7.0 -Version 7.0.104
```

If you are patching .NET SDK with NuGet assemblies, please send me precise repro steps. 

Also, step 10 is confusing.  Should I expect success or failure?  The step says both.

When I try to repro this as best as I can (with above issues), I consistently get `PackageSignatureVerificationLog`

**Comment by v-luzh** [comment]
Hi @dtivel, sorry about the step4 and step5, I have updated the steps. 

**For the installation,** we followed the [pre-testing steps](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPre-testing%20steps%7C6e4370c3-c593-4b99-abd8-908d0f9e002b%2F%29&wdorigin=703) and got the '7.0.104' in the path: "...\dotnet\sdk" on Feb.24th.

**For the step10,** it should be succeed as the case said below.
![image](https://user-images.githubusercontent.com/20632625/226289054-00fd3f62-4c43-4b9b-b8c2-24d6b0bd0f5c.png)

**Note:** The bug is saying that: we will not get the line: "b. PackageSignatureVerificationLog..." after restoring (step12), instead of step 10.

**Comment by erdembayar** [comment]
@dtivel 
Is this issue under your radar?

**Comment by dtivel** [comment]
Yes, it's low priority for me.  This looks like an occasional inconsistency under detailed logging for a particular log message with no significant user impact.

**Comment by v-luzh** [comment]
Still repro on .NET SDK Version:  7.0.107.

**Comment by nkolev92** [comment]
Team Triage: Given the low user impact, assigning this to P3.

**Comment by CiciLi1** [comment]
This issue is fixed on .NET SDK 8.0.400-rtm.24367.3. I will close this bug soon.
