### ISSUE TITLE
The icons of installed package version shows incorrectly in the “Installed” tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12453]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.6.0.27

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Create a C# Console App (.NET Framework 4.8.1) project in VS.
2. Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3. Click “Browse” tab, search a package (e.g. “Newtonsoft.Json”), select a vulnerable package version (e.g. 12.01) in the “Version” drop-down list and click the “Install” button on the right.
4. Click “OK” button in the “Preview Changes” dialog and click “I Accept” button in the “License Acceptance” dialog.
5. Click “Installed” tab and observe the package list.

#### Expected:
The icons of installed vulnerable package version show correctly in the “Installed” tab.

#### Actual:
The icons of installed vulnerable package version show incorrectly in the “Installed” tab as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/220890355-ad4404d5-53e5-4b53-970a-70af91c023e7.png)

#### Notes:
1.	It doesn’t repro on non-vulnerable package version for the same installed package.
2.	It doesn’t happen in “Browse” tab/”Updates” tab.
3.	It doesn't repro on VS Main\33419.19 + NuGet Client Dev\6.6.0.24.
4.     It still reproes after clicking "Refresh" button.

**Comment by nkolev92** [comment]
Team Triage:

The behavior doesn't seem related to vulnerable packages. We were able to repro it without vulnerable packages. 
Sometimes it happens on the scroll list, other times in happens in the details tab.

**Comment by v-luzh** [comment]
Hi @nkolev92, the package icon issue seems another known unstable bug: https://github.com/NuGet/Home/issues/10781. And we saw this issure for the first time while it happens on the scroll list of "Installed" tab.

**Comment by nkolev92** [comment]
@v-luzh I'm not really what the issue is here in that case.

Can you point what on the screenshot is incorrect/missing?

**Comment by v-luzh** [comment]
Hi @nkolev92, sorry, I didn't describe clearly. The bug 10781 is saying that the icons in the detailed info (the right panel) showed incorrectly, while this bug 12453 is saying that the icons in the installed package list showed incorrectly. 

Anyway, this current bug doesn't repro on NuGet Client Dev\6.6.0.32.

**Comment by nkolev92** [comment]
Thanks for the clarification. 

This is a flaky bug. I was able to repro it on latest but it's very inconsistent.

**Comment by CiciLi1** [comment]
This issue is fixed on VS Main\35222.175 + NuGet Client Dev\6.12.0.82. I will close this bug soon.
