### ISSUE TITLE
dotnet nuget hangs when ran as non-root user

### ISSUE THREAD

**Issue by lhalleyvzc** [NuGet/Home#12457]
### NuGet Product Used

NuGet SDK

### Product Version

dotnet sdk 6.0.405

### Worked before?

dotnet sdk 3.1.426

### Impact

I'm unable to use this version

### Repro Steps & Context

Running Amazon Linux 2

### Working
As a root user:
```
> whoami
root
```
![image](https://user-images.githubusercontent.com/119940912/221855129-86d76848-7bc4-4bdd-a590-ccf27f58bd16.png)

Check if dotnet is available, which works:
```
> dotnet --version
6.0.405
```

![image](https://user-images.githubusercontent.com/119940912/221855217-339c2e99-9c51-4d46-a569-ec8bbfde6adc.png)

Simply run dotnet nuget to check if its available, which it does 
```
> dotnet nuget
NuGet Command Line 6.3.1.1

Usage: dotnet nuget [options] [command]

Options:
  -h|--help  Show help information
  --version  Show version information

Commands:
  add      Add a NuGet source.
  delete   Deletes a package from the server.
  disable  Disable a NuGet source.
  enable   Enable a NuGet source.
  list     List configured NuGet sources.
  locals   Clears or lists local NuGet resources such as http requests cache, packages folder, plugin operations cache  or machine-wide global packages folder.
  push     Pushes a package to the server and publishes it.
  remove   Remove a NuGet source.
  sign     Signs NuGet package(s) at <package-paths> with the specified certificate.
  trust    Manage the trusted signers.
  update   Update a NuGet source.
  verify   Verifies a signed NuGet package.

Use "dotnet nuget [command] --help" for more information about a command.
```

![image](https://user-images.githubusercontent.com/119940912/221855314-1c7da2de-c60d-4020-8b56-b7216fb198f2.png)

### Not Working:
As a non-root user -Check if dotnet is available, which works:
```
> dotnet --version
6.0.405
```
As a non-root user - dotnet nuget, and it will hang indefinitely 
```
> dotnet nuget
```
![image](https://user-images.githubusercontent.com/119940912/221852545-df038a2f-37e3-46de-882c-9e860e9a9559.png)

If ran as a background task, it will max the CPU out at 100%
![image](https://user-images.githubusercontent.com/119940912/221853038-742a6710-e2a1-4860-b533-ed447a9bc5ab.png)

The non-root user, has ownership of the /usr/share/dotnet/ folder and all files within it, user name blurred out but it is the users name and group.
![image](https://user-images.githubusercontent.com/119940912/221853591-2fa8995c-1ea1-4ee8-9fe3-8b22908a7383.png)

### Conclusion
After we added dotnet 6 to our servers, any dotnet nuget commands are hanging, we have the following versions installed:
```
2.1.818 [/usr/share/dotnet/sdk]
3.1.426 [/usr/share/dotnet/sdk]
6.0.405 [/usr/share/dotnet/sdk]
```

Note: I tested the following commands and they are NOT hanging for both and non-root users:
- [dotnet build](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build)
- [dotnet build-server](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build-server)
- [dotnet clean](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-clean)
- [dotnet dev-certs](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-dev-certs)
- [dotnet format](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format)
- [dotnet help](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-help)
- [dotnet migrate](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-migrate)
- [dotnet msbuild](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-msbuild)
- [dotnet pack](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack)
- [dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
- [dotnet restore](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore)
- [dotnet run](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-run)
- [dotnet sdk check](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sdk-check)
- [dotnet sln](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-sln)
- [dotnet store](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-store)
- [dotnet test](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test)
- [dotnet vstest](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest)
- [dotnet watch](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch)
- [dotnet tool](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install)

From what I can see this looks like a permission issue but all relevant directory and files are owned by the non-root user so I am not sure what else to do.

**Comment by kartheekp-ms** [comment]
the bug report looks similar to https://github.com/NuGet/Home/issues/12365#issuecomment-1387319370. Can you please check if the presence of forward slash at the end of $HOME environment variable causing this issue?

**Comment by lhalleyvzc** [comment]
Thank you @kartheekp-ms - this is already looking better on my side.

It was indeed the presence of forward slash at the end of $HOME environment variable causing this issue.

For reference I used this command **as root** to fix:

`echo "export HOME=\$(echo \$HOME | sed 's/\/$//')" | sudo tee -a {INSERT_USER_BASH_PROFILE}`

Which will remove any trailing forward slashes from the $HOME var if they are present.

Will close when fully validated.
