### ISSUE TITLE
Confusing error message for -MSBuildPath argument in the English resource file of the Nuget.CommandLine client.

### ISSUE THREAD

**Issue by atamagaii** [NuGet/Home#12461]
### NuGet Product Used

NuGet.exe

### Product Version

nuget.exe v.6.4.0.123

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Description:
When the -MsBuildPath doesn't exist the command line returns an error saying that the directory "doesn't not exist". Which is confusing since the error stems from a Directory.Exists() == false check. 

Reproduce:
1. Execute the restore command and specify an non-existent path in the -MSBuildPath argument

Expected:
A well formed sentence explaining that the path does not exists

Actual:
The sentence returned contains the double negative "doesn't not exist"

### Verbose Logs

```shell
nuget.exe restore testProject.sln -MsBuildPath 'c:\some_non_existent_path'
Using Msbuild from 'c:\some_non_existent_path'
MSBuildPath : c:\some_non_existent_path doesn't not exist.
```

**Comment by kartheekp-ms** [comment]
I think you would like to change the error message displayed from `MSBuildPath : c:\some_non_existent_path doesn't not exist.` to `MSBuild path c:\some_non_existent_path does not exists`. Correct?

Here is the resource file where the string `MSBuildPath : {0} doesn't not exist` is coming from.

https://github.com/NuGet/NuGet.Client/blob/c911884c370d24a46ae73b49a9857784dccc534a/src/NuGet.Clients/NuGet.CommandLine/NuGetResources.resx#L640

Feel free to submit a pull request :) We will be happy to review the PR, provide feedback and accept the contribution.

**Comment by atamagaii** [comment]
That's correct.

I would update the error message as follows...

  <data name="MsbuildPathNotExist" xml:space="preserve">
    <value>MSBuildPath : {0} does not exist.</value>
  </data>
