### ISSUE TITLE
Need to check our usage of HttpResponseMessage.EnsureSuccessStatusCode()

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1246]
By design, EnsureSuccessStatusCode() is called when an unrecoverable error is encountered. The exception it throws does not contain the http status code. However, in many places where it is used in our code, the top level code should in fact perform different actions based on the underlying error condition. E.g. if it's authentication failure, nuget needs to get prompt users for credentials and retry the  request.

We need to go through our code base and verify that EnsureSuccessStatusCode() is correctly used, and change our code when it is not appropriate.

**Comment by yishaigalatzer** [comment]
To be a bit more blunt, we should not rely on `EnsureSuccessStatusCode` or catching the respective exception anywhere.

**Comment by nkolev92** [comment]
Redundant now.
