### ISSUE TITLE
dotnet list return code changed

### ISSUE THREAD

**Issue by groogiam** [NuGet/Home#12479]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

It appears the return codes for dotnet list have been changed to return 1 instead of 0 if there is a failure to list packages for an project in a solution. Previously this was not the case. The behavior change is breaking and has implications for build automation using dotnet list.

`src/MySln.sln package --vulnerable --include-transitive`

### Desired Behavior

Previously the command would return a 0 exit node. It would print something like The project DockerCompose\docker-compose.dcproj uses package.config for NuGet packages, while the command works only with package reference projects. for any projects it could not list. Recently it has been changed to return a non zero exit code which is breaking existing build automation logic.

### Additional Context

Originally Reported Here https://github.com/dotnet/sdk/issues/30975

**Comment by erdembayar** [comment]
Thank you for filing this issue, returning `non-zero` value was expected change to inform there is possible security vulnerability or deprecated package, other problem in your dependencies, you can check spec [here](https://github.com/NuGet/Home/blob/04b3ebec7868c09054f800af8996148e4e3b15c8/proposed/2022/DotnetListPackageMachineReadableJsonOutput.md). If it's returning `1` then, please kindly check your console log for actual problem. 
You can either update the packages or change your return code handling in your CI script.
We have follow up issue for improving the return exit code for more clarity, please go to https://github.com/NuGet/Home/issues/11315 and upvote or comment. We prioritize investigations based on community engagement such as comments and up-votes.
