### ISSUE TITLE
ResourceProvider.TryCreate() should not blindly cache negative result

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1247]
In the TryCreate() method in several ResourceProviders, when the resource cannot be created, then null value is cached. But whether null should be cached really depends on the underlying error: If it's 404, then probably it's OK to add null to the cache. But if the error is authentication failure, probably we shouldn't cache null in this case.

**Comment by yishaigalatzer** [comment]
@feiling I thought we fixed this issue already. If not can you please take another look?

**Comment by yishaigalatzer** [comment]
@feiling ping

**Comment by feiling** [comment]
This has been fixed. Most resource providers do not cache the result at all. Only two providers use cache. For ServiceIndexResourceV3Provider, null is cached, but with an expiration time. For PackageRepositoryResourceV2Provider, null is not cached.
