### ISSUE TITLE
[Feature]: add command dotnet config set

### ISSUE THREAD

**Issue by dainizzz** [NuGet/Home#12476]
### NuGet Product(s) Involved

NuGet.exe, dotnet.exe

### The Elevator Pitch

Feature for #12469  
This command will set the value of a specified NuGet configuration setting, following [this spec](https://github.com/NuGet/Home/blob/dev/proposed/2022/dotnet-nuget-config-spec.md#set).

**Comment by dainizzz** [comment]
This has been merged into the feature branch

**Comment by kartheekp-ms** [comment]
This feature was actually released in NuGet 6.9, but we missed mentioning it in the [release notes](https://learn.microsoft.com/nuget/release-notes/nuget-6.9). It will be included in the upcoming 6.10 release notes.

https://github.com/NuGet/Home/issues/12469#issuecomment-2113059734
