### ISSUE TITLE
Add central package management option for package management

### ISSUE THREAD

**Issue by Varorbc** [NuGet/Home#12473]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

![image](https://user-images.githubusercontent.com/5714438/223906721-f366e960-d57e-4f2b-a5a0-a3c50fd6b64b.png)

**Comment by jeffkl** [comment]
Thank you for your interested in Central Package Management (CPM).

CPM is really just an extension of PackageReference.  We don't believe it would make sense for CPM to show up in this particular UI.  We are looking into ways of onboarding repositories to CPM through tooling but I'm not sure if one will ever exist in Visual Studio.  CPM is meant to be enabled for an entire repository and Visual Studio solution files don't always represent the entire set of projects in a repository.  We will continue to evaluate our options and come up with a good onboarding experience for CPM.
