### ISSUE TITLE
Push command doesn't resolve credentials from config

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1248]
The PushCommand method ResolveSource resolves the push source specified, but then returns the source as a string, instead of an object with the credentials.

This results in the push command failing (at least against a V3 authenticated endpoint with a v2 PackagePublish service in the service index).

@deepakaravindr

**Comment by zarenner** [comment]
Note: May be similar to the auth issues with list in #1229.

**Comment by yishaigalatzer** [comment]
@zarenner a work around for now (if we can't fit it in to 3.2) is to publish the V2 push end point on your server directly.

**Comment by zarenner** [comment]
Thanks @yishaigalatzer, that's what I've been doing and it works.

**Comment by zarenner** [comment]
I'd really like to get this into 3.2.  Let me know if I can help in any way.

**Comment by yishaigalatzer** [comment]
@feiling is supposed to check it in today. You can party on the PR and test the build once its out

**Comment by feiling** [comment]
With Deepaks's fixes and my fix of https://github.com/NuGet/Home/issues/1216, pushing to authenticated v3 feed is now supported.
