### ISSUE TITLE
[release-6.3.x]  Port X509ChainHolderTests.cs from dev

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#12493]
https://github.com/NuGet/NuGet.Client/pull/4971 contained a [change](https://github.com/NuGet/NuGet.Client/pull/4971/commits/2d1743082dd15bc587bab49c020038425275ca90) which improved verification in X509ChainHolderTests to be more robust.

We need to port this change to the release-6.3.x branch.

CC @heng-liu

**Comment by ghost** [comment]
@dtivel Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)

**Comment by nkolev92** [comment]
Closing as fixed by https://github.com/NuGet/NuGet.Client/pull/5100. 
PRs that target non-main branches won't auto close issues.
