### ISSUE TITLE
Cannot create a package that has no dependencies nor content.

### ISSUE THREAD

**Issue by goreshmusalay** [NuGet/Home#12499]
### Discussed in https://github.com/NuGet/Home/discussions/12498

<div type='discussions-op-text'>

<sup>Originally posted by **goreshmusalay** March 21, 2023</sup>
I am trying to generate NuGet package by using cPack,
I am new to cmake and cpack stuff, so bare with me if the questions and doubt i have are stupid  ones

I am hitting the following error on issuing cpack --build . --package

1. Cannot create a package that has no dependencies nor content.
I have added following NUGET params to the CMakeList.txt file.

1. CPACK_NUGET_PACKAGE_VERSION
2. CPACK_NUGET_PACKAGE_DEPENDENCIES
3. CPACK_NUGET_PACKAGE_DEBUG
4. CPACK_NUGET_PACKAGE_DESCRIPTION
5. CPACK_GENERATOR as NuGet
6. CPACK_NUGET_PACKAGE_NAME

The cpack geneartes the nuget spec file but it has no <files> tag inside it
In build Dir I see folder created with the cmake install (FILES, ....) options that was added.

Can you help in what must i have done wrong here?
</div>

**Comment by jeffkl** [comment]
Closing this in favor of the discussion
