### ISSUE TITLE
NuGet 3.2 takes ~two seconds to verify restore and ~one minute to restore

### ISSUE THREAD

**Issue by agocke** [NuGet/Home#1249]
Note that this is just verifying that all packages have been restored completely -- it's after running a successful restore once.

Repro: run `nuget.exe restore Roslyn.sln` on the Roslyn branch at https://github.com/dotnet/roslyn/tree/CoreClr

**Comment by jaredpar** [comment]
Wanted to point out that during restore the UI in VS is hung.  So this bug effectively hangs VS for over a minute whenever we invoke a build solution or build project operation (even if they are a nop).  The only way we can move to NuGet v3 and keep VS in usable state is to completely disable package restore.

**Comment by emgarten** [comment]
@jaredpar are you using the CoreClr branch also?

**Comment by yishaigalatzer** [comment]
@jaredpar that would be my suggestion for now (turn off package restore and use the command line). We are trying to add a restore context menu to NuGet 3.2 to give you more control on when to restore.

I would also look into the solution, it might be that restore is not fully successfully which forces the retries on every build. We should make the errors for that more visible.

I'm keeping this bug open to improve restore speed, and investigate exact reasons for why build is happening again on every build.

**Comment by jaredpar** [comment]
@emgarten yes

**Comment by emgarten** [comment]
After the first build I am no longer seeing the restore dialog for Roslyn.sln. 

I'm not able to try nuget.exe restore Roslyn.sln due to missing packages. Which feed has Microsoft.DotNet.BuildTools 1.0.25-prerelease-00063?

**Comment by agocke** [comment]
It looks like installing the latest update has helped significantly. It still seems to hang the UI for a couple seconds after I hit build (VS freezes and the OS whites-out the app as unresponsive), but it no longer seems to be doing the full restore.

**Comment by emgarten** [comment]
Given the latest feedback this is still an issue but it can be moved to 3.3

**Comment by yishaigalatzer** [comment]
@emgarten this is related to the fix you attempted today. Looks valueable to try and get it in on Monday if we can

**Comment by yishaigalatzer** [comment]
We are done with perf improvements for nuget.exe for 3.3, we will consider more perf work post 3.3, this bug should be closed based on the improvments we made so far
