### ISSUE TITLE
[Bug Bash] The alternative package “ErikEJ.EntityFramework.SqlServerCompact” cannot be found through clicking the link in deprecated package info  

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12492]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.6.0.52

### Impact

It bothers me. A fix would be nice

#### Repro Steps:     

1. Create a C# Class Library (.NET Framework) project.   

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.   

3. Select the package source: “nuget.org” near the gear button and go to "Browse" tab. 

4. Search for a deprecated package “EntityFramework.SqlServerCompact.PrivateDeployment” in "Browse" tab.  

5. Click the link “ErikEJ.EntityFramework.SqlServerCompact” in the description of the package in the searched package list or the link “ErikEJ.EntityFramework.SqlServerCompact” on the right panel.  

#### Expected:     

The alternative package “ErikEJ.EntityFramework.SqlServerCompact” is showing in the searched package list.  

#### Actual:     

The alternative package “ErikEJ.EntityFramework.SqlServerCompact” cannot be found as below screenshot. 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/84695155/225867519-81b8dad0-af5a-43f1-925c-59de55953556.png)

  

#### Notes:  

1.The repro rate is 100%.  
2.It is not a regression since it doesn't repro on VS Main\33005.16 + NuGet Client Dev\6.4.0.107.

**Comment by nkolev92** [comment]
@CiciLi1 

If you look at nuget.org, https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServerCompact/6.4.0-beta2, you'll see that the package in question only has prerelease versions available. 

Can you please try with the prerelease checkbox selected?

**Comment by CiciLi1** [comment]
Hi @nkolev92, thanks for the update, I tried to select the checkbox for pre-release and this package "ErikEJ.EntityFramework.SqlServerCompact" can be found.

**Comment by nkolev92** [comment]
I'm assuming there's no bug here then?
Closing, please reopen if you disagree.
