### ISSUE TITLE
Set CentralPackageVersionOverrideEnabled=false in project with CPM broke project restore

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#12500]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.0-preview.2.23128.3

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create project with CPM enabled. 
2. Add `<CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>` to project file.
3. Run `dotnet restore`

The restore fails but does not log an error.  This is because of bad logic here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L478

**Comment by jwfx** [comment]
@nkolev92 

This issue still appears on SDK 6.0.417. (dotnet nuget --version => 6.3.3.3)

On 7.x it seems to be fixed, at least on the version 7.0.311 that I tested with.

**Comment by nkolev92** [comment]
The fix is in the 7.0.3xx. The release notes contain exact versions since NuGet is available in various tools. https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.6
