### ISSUE TITLE
Web.Config and App.config transformation not working on uploaded package

### ISSUE THREAD

**Issue by n3wt0n** [NuGet/Home#1250]
Hello. I have a uploaded a package (DBTek.BugGuardian) and I'm experiencing a strange issue with config transformations in non-transient restore.

The package contains transformation files for both app and web.config files, cause it targets both platforms.

The package was build following the new folder structure guidelines.

If I pick the package from a local folder, the trasformations work fine (tested on Console application, MVC5 webapp and WinForm app).
Though, if I use the uploaded package (same version) they don't work.

I'm on VS2015 with NuGet Package Manager v.3.1.60724.766
To build the package I used the NuGet CLI v 3.1.0.0

**Comment by yishaigalatzer** [comment]
@zhili1208 please take a first crack at investigating this issue, so we can see if it needs to go into the 3.2 release.

**Comment by zhili1208** [comment]
@n3wt0n Can you provide the repro step? and what's the strange issue? thanks

**Comment by yishaigalatzer** [comment]
@zhili1208 I think the repro steps are
1. Download the package to a local folder, and set it up as package source
2. Install the package to an MVC app and a console app
3. Check the app.config / web.config

Repeat the process with the normal nuget.org

Compare app.config from step1 and step2, they should be the same.

**Comment by n3wt0n** [comment]
I didn't try with the uploaded package downloaded in the local folder (I'll do it as soon as I arrive in office), but I have the original package and with it the config files changes, while using the uploaded one they don't.

If you want I can send you the original package.

Sent from my Windows Phone

-----Original Message-----

**Comment by yishaigalatzer** [comment]
:) are you sure you uploaded the same package? Can you binary compare them?

**Comment by n3wt0n** [comment]
Yes, I'm sure 😊

When I arrive in the office I will also do binary comparison.

Sent from my Windows Phone

**Comment by n3wt0n** [comment]
So, I did the binary compare between the original package version 1.1.0 and the downloaded one and… they are different!

I’m very sure I uploaded just that package, because it was the only one I generated for that version…

Now I’ve tried to upload the same package just changing the version to 1.1.1… and now it works. Also the binary comparison shows they are equals…

Do you processes someway the packages server side?

DAVIDE BENVEGNU'
Microsoft MVP Visual Studio ALM

 http://www.davidebenvegnu.com/ http://www.davidebenvegnu.com

 http://blog.dbtek.it/ http://blog.dbtek.it

From: Davide Benvegnu [mailto:davide.benvegnu@outlook.com] 
Sent: Wednesday, 26 August 2015 9:29 AM
To: NuGet/Home reply@reply.github.com; NuGet/Home Home@noreply.github.com
Subject: RE: [Home] Web.Config and App.config transformation not working on uploaded package (#1250)

Yes, I'm sure 😊

When I arrive in the office I will also do binary comparison.

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
Only if you change the metadata. But it will only change the nuspec.

Can you compare the contents?

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
Closing since there is nothing further to investigate here. Feel free to comment and resurrect the thread with more details.
