### ISSUE TITLE
NuGet Configuration Defaults should be storable in solution directory

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#1252]
Currently NuGetDefaults.config must be located under %ProgramData%\NuGet.

Documentation says "While not required, we expect many companies to use Group Policy to deploy NuGetDefaults.config files to developers' machines."
This would involve IT in development tasks and is impossible to manage in larger companies.

A better approach would be to allow the .config to be in any parent folder of the project, usually the solution folder or SCM root folder. This would enable to easily deploy the .config with SCM, and make it even instantly available on a build server.

**Comment by yishaigalatzer** [comment]
nuget.config is deployable to any folder. It covers the scenarios you have in mind.

For example: You can use a clear tag to remove all sources and redefine them.
Similarly you can control enabling and disabling sources.

**Comment by tom-englert** [comment]
If that works it's fine, I will try it - but then the documentation is wrong!
@yishaigalatzer shall I create an issue to fix the documentation instead?

**Comment by tom-englert** [comment]
P.S. 
https://docs.nuget.org/consume/nuget-config-file looks good, but when searching you will land here: https://docs.nuget.org/consume/nuget-config-defaults - and this does not link to the config description, so one thinks that's all you can do.

**Comment by yishaigalatzer** [comment]
Makes sense. We can either fix the docs or if you'd like to send a pr in the nugetdocs repo with your suggestion (since you found it, would be nice to give you to opportunity for the cookie points :) ).

**Comment by tom-englert** [comment]
#367 :smirk:
