### ISSUE TITLE
References Drawn through NuGet do not respect the `required` keyword

### ISSUE THREAD

**Issue by MikeKenyon** [NuGet/Home#12526]
### NuGet Product Used

dotnet.exe, Visual Studio Package Management UI

### Product Version

dotnet 7.0.100, VS 2022

### Worked before?

New feature

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I'm unsure this is the correct place, but it's the best I've been able to come up with.

Create a library that provides data types that use the new `required` keyword.

If you directly reference that package, the compiler generates errors/warnings indicating that you are not setting properties so marked.

If you reference the same DLL via a Nuget Package, no errors are created.

**Comment by jeffkl** [comment]
Team Triage: Can you please provide a simple repro of the problem so we can investigate?  Create a project, package, and zip it up so we can see what's going on.  Thanks!

**Comment by MikeKenyon** [comment]
Issue on our side.  Apologies for the efforts  spent,.
