### ISSUE TITLE
Packages.lock.json different when built from msbuild versus visual studio

### ISSUE THREAD

**Issue by robertson-bauercontrols** [NuGet/Home#12527]
### NuGet Product Used

MSBuild.exe, NuGet.exe

### Product Version

msbuild 17.5.1.16304

### Worked before?

never

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Given a solution (such as the one mentioned in this same issue, which was marked as released https://github.com/NuGet/Home/issues/8272).  Use central package management.

If you do a msbuild via command line, the packages.lock.json use DLL names for dependancies on a nuget restore.  If you open visual studio and do a build, it uses the Project names, as well as adds more to the packages.lock.json.  

In the screenshot below, the left is msbuild, the right is visual studio.

![image](https://user-images.githubusercontent.com/55808281/229877656-ef8f8fa8-66e6-4c07-8666-456c992f0cd9.png)

This issue has been mentioned elsewhere on github, but they're all marked as fixed or closed.  It is definately still an issue for me (VS2022 17.5.3, winforms).  Since these files are checked into source control, we're gettign files modified when a developer builds from visual studio VS command line.  For this to work with continuous integration, I need these files to be the same no matter the build context.

There's a chance I'm misunderstanding how to use these lock files.

**Comment by martinrrm** [comment]
@robertson-bauercontrols I wasn't able to repro this with the project from previous bug, can you add a more detailed repro steps for you issue? Thanks!

**Comment by robertson-bauercontrols** [comment]
In an effort to stop this from going stale, I'm still working on reproducing. I'm having trouble getting my  problem reproducing on a small scale, will keep at it!

**Comment by robertson-bauercontrols** [comment]
Here's an example of a diff.  The left is command line, the right is visual studio.  This is from our enterprise product, and not a simple reproducible application

![image](https://user-images.githubusercontent.com/55808281/234661595-1166afe0-d005-4976-9cb5-dcc47d072f18.png)

**Comment by zivkan** [comment]
@robertson-bauercontrols in the project's `obj/` directory is a file named `project.assets.json`.  Could you please also get a diff of that file after a restore in VS & the CLI?

The diff you show suggests that a different global packages folder, and/or fallback folder is being used, and the contents of the package are different in those two locations.  Packages being globally unique and immutable is a core assumption by NuGet (and at least some other package managers from other ecosystems). So, a package changing contents breaks deterministic results. If lock files are used with "locked mode", this will cause restore to fail. In this case, the `rtdd.core` package changing dependency between `rtdd.interop` and `rtddinterop` is what's changing.

The assets file lists all the nuget.config files, the global packages folder, any fallback folders, and other information, so it will give us a better hint about what's different between the VS and CLI restores.

**Comment by tomaszras-intive** [comment]
~~I am also hitting the same issue. In my case I have a couple of **vcxproj** in my solution. These C++ project don't use any nuget packages. When, I run nuget restore from command line using nuget.exe lock file are being also created for these C++ projects, but when i run restore from Visual Studio, lock files are not being created.  This issue complicates things when we try to cache packages in Azure DevOps as we get key mismatch.~~

EDIT: I tourend out that I had some leftover packages.config files in these vcxrpoj dirs, removing it fixed the problem for me.

**Comment by shueybubbles** [comment]
@zivkan I can reproduce this with two different msbuild commands - one using dirs.proj to build everything, and one building just a specific .csproj file in the tree.
The lock file generated for the same .csproj differs when it gets brought in via dirs.proj vs being built directly.

There are several apparent factors at play:
1. The dependencies whose names differ in the 2 lock files are coming from `<ProjectReference>`, not `<PackageReference>`
2. The dependency projects have a `.proj` extension and build using the `NoTargets` SDK
3. Our `Directory.Build.Targets` file sets `<PackageId>` to include the value of `$(Configuration)` so we can build different nuget packages from the same sources.
4. The affected dependencies differ in the lock.json files by the omission of `$(Configuration)` when built from dirs.proj
5. My VS2022 just upgraded to 17.9.5 when this started happening. It was fine in older versions
