### ISSUE TITLE
Don't fall thru when v3 feed failed

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1253]
In ServiceIndexResourceV3Provider.TryCreate(), when there are errors connecting to a v3 feed, the method returns (false, null). This allows fall thru and cause the feed to be treated as V2. We should stop the fall thru instead.

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/NuGet3/commit/11a75e076278146679ebd9cc76e8165896fcaae0
