### ISSUE TITLE
NuGet client proxy settings are not behaving as expected

### ISSUE THREAD

**Issue by muhtarmamatov** [NuGet/Home#12534]
### Impact

Other

### Describe the bug

Dear NuGet.org team,
We have a problem regarding the use of proxies when using nuget in the Teamcity CI system. If you add the proxy server data to the nuget.config configuration file via the terminal or command line, downloading dependencies will come through the proxy server. But using the same configuration file inside the Teamcity CI system downloading dependencies does not happen through a proxy but directly. Used configuration is below:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <config>
    <add key="http_proxy" value="<http://ip_address_of_proxy:port_number>" />
    <add key="https_proxy" value="<http://ip_address_of_proxy:port_number>" />
  </config>
</configuration>

### Repro Steps

1. Set up proxy server on TeamCity ci agent 
teamcity.http.proxyHost=ip_address_of_proxy
teamcity.http.proxyPort=port_number

teamcity.https.proxyHost=ip_address_of_proxy
teamcity.https.proxyPort=port_number

teamcity.http.nonProxyHosts=localhost|<teamcity_server_ip>
teamcity.https.nonProxyHosts=localhost|<teamcity_server_ip>

2. Set up proxy server for nuget 
*) > nuget.exe config -set http_proxy=http://ip_address_of_proxy:port_number
*) > nuget.exe config -set https_proxy=http://ip_address_of_proxy:port_number

3. Run Build 

### Expected Behavior

Downloading all the project dependencies should go through proxy server.

**Comment by joelverhagen** [comment]
This appears to be a question about NuGet client software (NuGet config for proxies). I'm moving this issue to NuGet/Home since that is where we track NuGet client issues. NuGet/NuGetGallery is for issues related NuGet.org.

**Comment by kartheekp-ms** [comment]
> But using the same configuration file inside the Teamcity CI system downloading dependencies does not happen through a proxy but directly.

According to https://github.com/NuGet/Home/issues/747, it appears that NuGet disregards proxy settings unless they are specified in the user-level configuration file. Could you verify whether the NuGet.Config file has been copied to the user-level or repository-level? If it has been copied to the repository-level, please attempt relocating the file to the user-level and try again. For more information about NuGet.Config locations please refer to https://learn.microsoft.com/nuget/consume-packages/configuring-nuget-behavior.

If the suggested work around doesn't work, could you please try setting the below recommended environment variable to determine if it resolves the issue?

Variable | Description | Remarks
-- | -- | --
http_proxy | Http proxy used for NuGet HTTP operations. | This would be specified as `http://<username>:<password>@proxy.com`.

**Comment by muhtarmamatov** [comment]
NuGet.Config file has been copied to the user-level not repository-level

**Comment by muhtarmamatov** [comment]
Tried below recomendation there is no affect, not using proxy connecting directly to the internet. 

> Variable	Description	Remarks
> http_proxy	Http proxy used for NuGet HTTP operations.	This would be specified as `http://<username>:<password>@proxy.com`.

**Comment by erdembayar** [comment]
Have you tried to reach out to Teamcity support?
We're not familar with 3rd party hosting services like Teamcity. It could be bug on their product, if it's not then we need repro steps to diagnose this.

**Comment by muhtarmamatov** [comment]
We have not tried to reach Teamcity support. I will write issue report to Teamcity support. if there is no any issue with Teamcity I will be back to thread.

**Comment by erdembayar** [comment]
Sure, meantime I'll close this issue. You can reopen or file a new one.
Please note we need repro steps or repro code independent from Teamcity infrastructure, because we don't have a Teamcity pipeline available for testing.
