### ISSUE TITLE
CPM - NU1009 should be suppressable

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#12543]
Example: Your net7.0 application references xunit.assert which only offers a netstandard1.1 asset. Because of that, your application receives the transitive NETStandard.Library/1.6.1 package dependency which itself brings in a ton other framework dependencies and some of these might even have a known vulnerability (i.e. System.Runtime/4.3.0).

To minimize the dependency graph and not bring these out-of-support and vulnerable dependencies into the closure, we define a PackageReference to NETStandard.Library/2.0.3 which results in it being preferred over the transitive NETStandard.Library/1.6.1 package and a trimmed dependency graph (NETStandard.Library/2.0.3 has a single dependency only).

This is achieved via the following: https://github.com/dotnet/runtime/blob/ba0d5f41c25357e375927bab28ce268262bf22ca/eng/testing/xunit/xunit.targets#L3-L6

Now with CPM enabled, implicitly referenced packages can't be bumped anymore as the unsuppressable `NU1009` error is raised. The alternative of disabling CPM is not possible as that affects every project that has a (transitive or direct) package dependency on NETStandard.Library/1.6.1. These days such projects are mostly test projects in our stack which use xunit or Shouldly but those are hundreds in runtime and still a lot in msbuild.

CPM should warn about such cases but not error or offer a way to suppress it. As an alternative, to provide a work around for similar issues that might arise in the future, it might help to allow specifying the `VersionOverride` attribute on the PackageReference item without a corresponding `PackageVersion` item.

cc @jeffkl

**Comment by jeffkl** [comment]
@ViktorHofer the `IsImplicitlyDefined` attribute is designed so that parts of the .NET ecosystem can differentiate between package references added by SDKs and package references added by users.  Whatever is adding an implicit reference to NETStandard.Library would need to be updated.  Alternatively, you can remove that attribute:

```xml
<PackageReference Update="NETStandard.Library" IsImplicitlyDefined="" />
```

The current design is that with CPM, you can't set versions for implicitly defined packages and if things are out of date then the SDK owners should update their references.  Is the above workaround viable?

**Comment by ViktorHofer** [comment]
Yes, clearing IsImplicitlyDefined attribute on the PackageReference worked. Thanks for the workaround.

**Comment by inikulshin** [comment]
@ViktorHofer I saw you've already managed, but I still wanted to share another workaround that worked for us:
```
    <PackageVersion Include="NETStandard.Library" Version="2.0.3"
        Condition="'$(DisableImplicitFrameworkReferences)'=='true' or '$(TargetFrameworkIdentifier)'!='.NETStandard' or '$(_TargetFrameworkVersionWithoutV)'>='2.1'" />
```

It's `PackageVersion` with negated condition of `PackageReference` with `IsImplicitlyDefined` from [Microsoft.NET.Sdk.DefaultItems.props](https://github.com/dotnet/sdk/blob/0667d47630d1f082baeb5a6672c6aa15256db5cf/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.props#L54-L55):
```
  <ItemGroup Condition=" '$(DisableImplicitFrameworkReferences)' != 'true' and '$(TargetFrameworkIdentifier)' == '.NETStandard' And '$(_TargetFrameworkVersionWithoutV)' &lt; '2.1'">
    <PackageReference Include="NETStandard.Library" Version="$(NETStandardImplicitPackageVersion)" IsImplicitlyDefined="true" />
```

@jeffkl FYI
