### ISSUE TITLE
Fix docs.nuget.org for nuget.exe restore <project.json> scenarios

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1255]
Fix docs.nuget.org for nuget.exe restore <project.json> scenarios

**Comment by yishaigalatzer** [comment]
@deepakaravindr more details please?

**Comment by deepakaravindr** [comment]
Usage and Help information at http://docs.nuget.org/consume/command-line-reference#restore-command is outdated.
For instance, Usage should be 
nuget restore [< solution > | < packages.config file > | < project.json > | < Microsoft Build project >] [options]

But, it still reads 
nuget restore [< solution >|< packages.config file >] [options]

**Comment by yishaigalatzer** [comment]
By the time you wrote this, you could have submitted a PR and closed this issue :)
