### ISSUE TITLE
[Cross-platform Dotnet NuGet Sign] A redundant warning NU3018 shows after signing an already signed package with another trusted certificate on Linux

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12559]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 7.0.203

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

**Note:** It is an extended scenario instead of original test case

#### Repro Steps:
1. [Patched dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703).
2. On Windows: Create a new test **certificate1**:  `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` (in the powershell "Developer Command Prompt"). 
    On Linux: Copy the .cer file (should be generated under the same path with .pfx file) and the .pfx file from the above Windows machine to Linux machine.
3. On Windows: Create another test **certificate2**:  `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password -GenerateCerFile` (in the powershell "Developer Command Prompt"). 
    On Linux: Copy the .cer file (should be generated under the same path with .pfx file) and the .pfx file from the above Windows machine to Linux machine.
4. Where <CertificateFilePath> is the file path to the created two certificates (in step2 & step3) .cer or .pem file and <VersionedSdkDirectoryPath> is the directory path for the patched versioned .NET SDK directory (e.g.:  ./patchedSDK/sdk/7.0.100), add trust for **the two certificates:** 
    On Linux:  `./dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFile1Path> -vsd <VersionedSdkDirectoryPath> `
    On Linux: ` ./dotnet run --project ./Entropy/TrustTestCert/TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFile2Path> -vsd <VersionedSdkDirectoryPath> `
5. Use the patched "dotnet.exe" to sign a package for the first time. Where <PackageFilePath> is the test package path and <PfxFilePath> is the file path to the .pfx file of the **first** trusted certificate, sign the test package: 
    On Linux: ` ./patchedSDK ./dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath> --certificate-password password --timestamper http://timestamp.digicert.com/ -v n `
6. Verify that the package is signed successfully in the output, with no warnings and no errors.
   Package(s) signed successfully. 
7. Use the patched "dotnet.exe" to sign the package for the second time. Where <PackageFilePath> is the test package path and <PfxFilePath> is the file path to the .pfx file of the **second** trustedccertificate, sign the test package: 
    On Linux:  `./patchedSDK./dotnet nuget sign <PackageFilePath> --certificate-path <PfxFilePath> --certificate-password password --timestamper http://timestamp.digicert.com/ -v n `

#### Expected:
Verify that the second signing failed for 1 error in the output: 
Error: NU3001: The package already contains a signature. Please remove the existing signature before adding a new signature. 

#### Actual:
A redundant warning NU3018 shows as below screenshot. The warning doesn't make sense because the second certificate has been trusted.
![image](https://user-images.githubusercontent.com/20632625/234220912-3395caff-c073-4c32-a082-4e4390da1579.png)

#### Notes:
1.It only reproes on Linux platform, doesn’t repro on Mac & Windows.
2.It is not a regression since the scenario is extended case instead of original case.
3.It doesn’t repro in the original test case: [Dotnet nuget sign command:  sign an already signed package without overwriting](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FDotnet%20nuget%20sign%20command%20%20sign%20an%20already%20signed%20package%20%7Cee4f9421-a04f-4e96-a23b-49039e069cd3%2F%29&wdorigin=703) (sign two times with the same trusted certificate)

**Comment by jeffkl** [comment]
Team Triage: @dtivel does this seem like it is a result of changes in .NET 7 for Linux?

**Comment by dtivel** [comment]
The issue is https://github.com/dotnet/runtime/issues/85830.  This reproes independently of NuGet.

@v-luzh, you can work around this by having different subjects for each test certificate (e.g.:  `CN=NuGet Testing 0` and `CN=NuGet Testing 1`).

Also, your steps 2-3 are needlessly complicated.  You can simply run Entropy/MakeTestCert/MakeTestCert.csproj on Linux directly to create the certificates.  This tool lets you customize the subject.

This issue also reproes without a patched SDK.

(Simpler repro steps are always better.)

**Comment by dtivel** [comment]
@v-luzh, I just updated MakeTestCert (per feedback in that .NET bug) so that you don't need to specify unique subjects.

https://github.com/NuGet/Entropy/commit/b6d21037985c92b6b86bb66fccce42f60ac543cb

**Comment by v-luzh** [comment]
Hi @dtivel, thanks for your reminder. We will have a verification in the Cross-platform Dotnet NuGet Sign Test.
