### ISSUE TITLE
nuget restore fails for solution filters not in same directory as the solution it references.

### ISSUE THREAD

**Issue by jerhon** [NuGet/Home#12562]
### NuGet Product Used

NuGet.exe

### Product Version

nuget 6.5

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The new solution filters feature added in 6.5 with nuget restore does not use the correct pathing if the solution filter is kept in a different directory than the solution file.

If I place a solution filter in a directory outside of where the solution file is kept, it will not restore properly.
It evaluates the paths for the projects in the solution filter relative to where the solution filter is rather than relative to where the solution file is.

If I use the same solution filter and run it with "dotnet restore" instead, it restores file.

I have created a minimal reproducible example in a git repository here: https://github.com/jerhon/nuget-slnf-bug

It has two GitHub actions to show this, one with `dotnet restore` restoring the nuget packages and one with `nuget restore` restoring the nuget packages.  Both restore against the same solution filter.  The dotnet restore command restores the nuget packages.  The nuget restore command succeeds but doesn't restore the nuget packages so the build step fails.

**Comment by jerhon** [comment]
Was digging through the code, and the problem looks pretty straightforward.  Was experimenting with a fix, but the solution doesn't seem to build according to the contribution guidelines.  I tucked away an idea for a fix in a branch on fork if you are interested.  Can't test it or try it out since the project won't build.  So, IDK if it works.

https://github.com/jerhon/NuGet.Client/tree/jerhon-SlnfRelativePathFix

**Comment by zivkan** [comment]
>  but the solution doesn't seem to build according to the contribution guidelines

@jerhon can you share what error you're getting?  Running the configure and build scripts should still work, and works for me after a `git clean -xdf`

**Comment by jerhon** [comment]
I was able to build. Not sure what went wrong the first time.  I updated visual studio, pulled latest, cleaned, and it seems to be building fine now.  Thanks.

**Comment by jerhon** [comment]
@jeffkl @zivkan I have a simple fix with test to cover the scenario I'd like to propose in a PR.  However, I'm working with my current employer to make sure there are no issue with the .NET submission agreement before I open it.

**Comment by jerhon** [comment]
Anything I need to do to move forward on the fix in the PR?  I see some tests failed, any way I can resolve those?
