### ISSUE TITLE
The deprecated package "NuGet.Core" version 2.14.0 has no detailed information in the right panel of PM UI 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12563]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.7.0.20

### Impact

It bothers me. A fix would be nice

#### Repro Steps:      

1. Create a C# Class Library (.NET Framework) project.    

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.    

3. Select the package source: “nuget.org” near the gear button and go to "Browse" tab.  

4. Search for a deprecated package “NuGet.Core” with version 2.14.0 in "Browse" tab.   

5. Click the package in the package list and observe the right panel 

#### Expected:      

The deprecated package "NuGet.Core" version 2.14.0 should have detailed information in the right panel of PM UI as below: 
![Untitled1](https://user-images.githubusercontent.com/84695155/234510927-67e71ba1-6c5c-482a-8a16-18f7b054b261.png)
#### Actual:      

The deprecated package "NuGet.Core" version 2.14.0 has no detailed information in the right panel of the package as below screenshot.  
![Untitled](https://user-images.githubusercontent.com/84695155/234511020-993df4e4-e634-4ec3-b356-1588dbd531b9.png)
#### Notes:   
1.The repro rate is 100%.   
2. It is a regression bug since it doesn’t repro on VS Main\33621.438 + NuGet Client Dev\6.7.0.18. 
3. It just repro on version 2.14.0, doesn’t repro on the "NuGet.Core" package with other versions.

**Comment by donnie-msft** [comment]
I repro'd this and it appears to be due to a null `VersionRange` on deprecation's alternate package metadata. 
Used Version 17.7.0 Preview 1.0 [33623.95.main]


```
This exception was originally thrown at this call stack:
    NuGet.Versioning.VersionRangeFormatter.Format(string, object, System.IFormatProvider) in VersionRangeFormatter.cs
    NuGet.PackageManagement.UI.DetailControlModel.GetPackageDeprecationAlternatePackageText(NuGet.VisualStudio.Internal.Contracts.AlternatePackageMetadataContextInfo) in DetailControlModel.cs
    NuGet.PackageManagement.UI.DetailControlModel.PackageMetadata.set(NuGet.PackageManagement.UI.DetailedPackageMetadata) in DetailControlModel.cs
    NuGet.PackageManagement.UI.DetailControlModel.SetCurrentPackageAsync(NuGet.PackageManagement.UI.PackageItemViewModel, NuGet.PackageManagement.UI.ItemFilter, System.Func<NuGet.PackageManagement.UI.PackageItemViewModel>) in DetailControlModel.cs
    NuGet.PackageManagement.UI.PackageDetailControlModel.SetCurrentPackageAsync(NuGet.PackageManagement.UI.PackageItemViewModel, NuGet.PackageManagement.UI.ItemFilter, System.Func<NuGet.PackageManagement.UI.PackageItemViewModel>) in PackageDetailControlModel.cs
    NuGet.PackageManagement.UI.PackageManagerControl.UpdateDetailPaneAsync(System.Threading.CancellationToken) in PackageManagerControl.xaml.cs

```

**Comment by donnie-msft** [comment]
Closing based on the issue being resolved in my own testing and @CiciLi1 's retesting. Thanks again for reporting this!
