### ISSUE TITLE
NuGetAudit should be on by default with the .NET 8 SDK

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12568]
### NuGet Product(s) Affected

dotnet.exe

### Current Behavior

NuGetAudit was recently merged into NuGet. In order to use the feature, it's necessary for customers to opt in with an MSBuild property `<NuGetAudit>true</NuGetAudit>`.

### Desired Behavior

The default should be the same (opt-in) for customers using the .NET 7 SDK and earlier. But for early .NET 8 preview SDKs, we'd like to try making NuGetAudit opt-out, so on by default. Depending on feedback, we can revert it to opt-in before .NET 8 gets to RC1, but we think opt-out will give us great feedback during .NET 8's previews.

### Additional Context

Feature spec: https://github.com/NuGet/Home/blob/dev/proposed/2022/vulnerabilities-in-restore.md

NuGetAudit will check for packages with known vulnerabilities during restore.

**Comment by JonDouglas** [comment]
🚢🐿️ great plan!
