### ISSUE TITLE
License Type

### ISSUE THREAD

**Issue by dhyaman** [NuGet/Home#12560]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

Why does NuGet only display the license URL in package details, unlike other package managers? Wouldn't it be easier to find out the license of a package through APIs or similar means?

**Comment by zivkan** [comment]
This was implemented in 2018: https://github.com/NuGet/Home/issues/4628

In order not to break 7 years worth of existing packages, license URLs still work. As a consequence, package authors who either use old versions of nuget, or who ignore pack warnings, can still create packages with license URLs.
