### ISSUE TITLE
To dist.nuget.org, Add index.json and index.html that is based on index.json

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1257]
To dist.nuget.org, Add index.json and index.html that is based on index.json. Currently, there is only a static index.html with artifacts for win-x86-commandline

**Comment by csharpfritz** [comment]
Can we make this a static HTML file with knockout or angular bindings to
the content of index.json?

**Comment by maartenba** [comment]
Will the json be manually edited or does this come from a CI?

**Comment by deepakaravindr** [comment]
- It is preferable that dist.nuget.org is deployed in a way similar to v3's index.json
- In addition, the root index.html on dist.nuget.org should be based on the json file once it is available

**Comment by maartenba** [comment]
@deepakaravindr @csharpfritz @yishaigalatzer 

Please review:
- Commit https://github.com/NuGet/NuGet.Services.Index/commit/569477cb327795b55b0f6492bd74b211bfc5495a
- Example of the page - https://nugetdist.blob.core.windows.net/test2/index.html
- Example of the JSON (which incidentally @xavierdecoster could also use to track downloads and map "latest" by date of download) - https://nugetdist.blob.core.windows.net/test2/index.json

**Comment by xavierdecoster** [comment]
JSON looks good to me :+1:

**Comment by xavierdecoster** [comment]
Would it be meaningful to make this https://dist.nuget.org/index.json discoverable in https://api.nuget.org/v3/index.json?

**Comment by yishaigalatzer** [comment]
Can we use a date only format? Since we don't have a mechanism to populated the json file, and we (for now) will do it by hand, it will be much nicer if we could make the date just a string.

**Comment by yishaigalatzer** [comment]
I don't think the dist/index should be discoverable through the api. Mostly because it feels like we are making a service quality promise on it.

**Comment by maartenba** [comment]
Would the time set to zeroes work? This one parses nicely to a proper date object as-is in both JS and .NET?

**Comment by xavierdecoster** [comment]
If the cdn stats parser is to use this index.json to recognize /latest versions as their effective versions, dropping time from the release date means the stats parser will incorrectly consider /latest downloads as a different version than it actually was at the time of download (although, there may not be a 100% accurate way of doing this). However, having the hour of day would potentially improve accuracy by a factor 24 :)

Are we OK with such inaccuracy? Or should the cdn stats importer look for an alternative means to recognize /latest version downloads?

**Comment by maartenba** [comment]
How about dates in this format? `2015-09-16T00:00:00.000Z` - lets us be specific if we feel like being specific. And otherwise only date has to be populated with all the rest zeroes.

**Comment by yishaigalatzer** [comment]
I’m fine with the original stuff once we have deployment validation

**Comment by deepakaravindr** [comment]
I wonder if we should have a top-level property name which is fixed like "artifacts" similar to "resources" in https://api.nuget.org/v3/index.json. Currently, the property value "win-x86-commandline" is being used like a property name. 

Perhaps, something like the following, where there is a JSON array of artifacts and each artifact has a name and a displayname. This means that all the property names in the JSON is from a fixed set, "artifacts", "name", "displayname", "versions"

{
"artifacts" : [
        {
        "name": "win-x86-commandline",
        "displayname": "Windows x86 Commandline",
        "versions": [
            { "name": "nuget.exe - latest", "version": "3.2.0", "url": "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe", "releasedate": "2015-09-16T11:58:00.000Z" },

...
...

**Comment by deepakaravindr** [comment]
Rest looks good to me :shipit:

**Comment by maartenba** [comment]
- Updated JSON format a bit according to @deepakaravindr comments
- Added a JSON schema
- Updated TeamCity build configuration to run JSON schema validation

https://github.com/NuGet/NuGet.Services.Index/pull/19 (deploy via https://nugetbuild.cloudapp.net/viewType.html?buildTypeId=Gallery_NuGetServicesIndex_DeployDistNugetOrgIndexHtml)
