### ISSUE TITLE
Enable to set version of transitive dependency without adding it explicitly

### ISSUE THREAD

**Issue by orirabi** [NuGet/Home#12579]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

Say we have the following dependencies:

A requires B (v 1.0)
B requires C (v 4.0)

Say that there has been a vulnerability detected on C 4.0 and it is patched in 4.1 - how can I set that without upgrading my B version (either because there is no new version out, or for any other reason).

Today, as far as I know, this requires us to add C as a direct dependency and specify the version to 4.1, but this has some downsides (for example, if at any time B will stop requiring C this will cause us to add a useless dependency).

Gradle has a feature explicitly for that: https://docs.gradle.org/current/userguide/dependency_constraints.html

Question on StackOverflow for this: https://stackoverflow.com/q/73526370/2924784

**Comment by erdembayar** [comment]
@orirabi 
Thank you for filing this issue. Actually, you can do it now if onboard to CPM transitive pinning. https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#transitive-pinning

Please check it and let me know if fixes your problem.

**Comment by orirabi** [comment]
@erdembayar 
This actually looks great, than you!
