### ISSUE TITLE
"This project cannot be packaged because packaging has been disabled" nag when IsPackable is false

### ISSUE THREAD

**Issue by QuantumToasted** [NuGet/Home#12577]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

MSBuild version 17.4.1+9a89d02ff for .NET

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

When running `dotnet pack -c Release` with my project, [Elefess](https://github.com/QuantumToasted/Elefess), the following warning is emitted:
```
C:\Program Files\dotnet\sdk\7.0.102\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(203,6): warning :
This project cannot be packaged because packaging has been disabled. Add <IsPackable>true</IsPackable> to the project f
ile to enable producing a package from this project. [D:\Code\Elefess\Elefess.TestHost.AspNetCore\Elefess.TestHost.AspN
etCore.csproj]
```
I am unsure why this is the case - not only have I explicitly specified `<IsPackable>false</IsPackable>` in the .csproj, the project it depends on is just an xUnit project, which also has `<IsPackable>false</IsPackable>`, and does not give this warning.

### Verbose Logs

```shell
Ran with `dotnet pack -c Release --verbosity diag`:

(Apologies for the third-party link - the output is past GitHub's 25MB limit, and I wasn't sure of a reputable long-lasting source to just dump that amount of text)
https://cdn.discordapp.com/attachments/416139786961813514/1105263621023469638/output.txt
```

**Comment by erdembayar** [comment]
@QuantumToasted 
I see `<IsPackable>false</IsPackable>` in your code [here](https://github.com/QuantumToasted/Elefess/blob/62563fbb59820a9c9093213409767cee8a3350d7/Elefess.Test/Elefess.Test.csproj#L7) for test project and another project.

It looks like warning coming from here: https://github.com/NuGet/NuGet.Client/blob/886d4675d7d7c2c2100fb0fe99a62a0543c2431e/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#LL203C79-L203C110

I see 2 solutions. 
1. https://github.com/dotnet/sdk/issues/10511#issuecomment-543241183
2. Or you can set no warn property for excluded projects.
![image](https://github.com/NuGet/Home/assets/8766776/23def1a0-ba96-41cb-809b-22dccbecef19)

Please let me know if it resolves your problem.

**Comment by QuantumToasted** [comment]
Setting `WarnOnPackingNonPackableProject` to `false` did resolve the issue, or at least the warning when packing the solution.
I believe xUnit projects by default automatically add `<IsPackable>false</IsPackable>` - I just found it strange that the Test project did not emit a warning either. I'm not sure what specifically is resulting in an *attempt* to pack this project at all.

In either case, it is just a warning and doesn't indicate any problems on my end, so if this is working as intended somehow, then feel free to close this.
