### ISSUE TITLE
Transitive packages don’t show in the “Installed” tab until setting the “NUGET_TRANSITIVE_DEPENDENCIES_IN_PMUI” environment variable 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12582]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.7.0.38

### Impact

It bothers me. A fix would be nice

#### Repro Steps:   
1. Create a .NET Core Console App project via VS.   
2. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open PM UI.   
3. Click “Browse” tab, search a package (e.g. “Microsoft.EntityFrameworkCore”) that has dependencies, select a package version “6.0.4” in the "Version" drop-down list in the right panel and click the “Install” button on the right.   
4. Click “OK” button in the “Preview Changes” dialog and click “I Accept” button in the “License Acceptance” dialog.   
5. Go to “Installed” tab.  

#### Expected:   
Transitive packages should show in the “Installed” tab. “Transitive packages” label is expanded by default and all the transitive packages showed in the “Transitive packages” list (under the “Top-level packages” list).  

#### Actual:   
Transitive packages don’t show in the “Installed” tab as below screenshot.  
![image](https://github.com/NuGet/Home/assets/84695155/716abd8c-870a-4ddb-aa28-77cb5f76b186)
#### Notes:  

1. The repro rate is 80%.   
2. The issue will not repro after setting the “NUGET_TRANSITIVE_DEPENDENCIES_IN_PMUI” environment variable to 1 and reopen the same solution. 
3. it also repro on VS Main\33710.149 + NuGet Client Dev\6.7.0.36.

**Comment by erdembayar** [comment]
Fyi @jebriede

**Comment by jeffkl** [comment]
This feature is currently gated behind a feature experiment and the only way to guarantee that feature is enabled is to set the environment variable.  When testing this functionality, you'll need to set it.
