### ISSUE TITLE
Update-Package with -IgnoreDependencies doesn't work in a certain scenario

### ISSUE THREAD

**Issue by SeanFeldman** [NuGet/Home#1258]
According to [documentation](https://docs.nuget.org/consume/package-manager-console-powershell-reference) it should be possible to update a package to a newer version ignoring dependencies that would normally fail the update using `IgnoreDependencies` switch. This is failing in the following scenario.

Steps to reproduce:
VS2013 (Update4/Update5 and NuGet v2.8.50926.663 /  v2.8.60723.765)
1. Create a new console project
2. run Install-Package NServiceBus.Azure
3. run Update-Package Microsoft.WindowsAzure.ConfigurationManager -IgnoreDependencies 

fails

When doing the same in VS2015 Nuget v3.1.0.0 it works.

**Comment by SeanFeldman** [comment]
Have reproduced this on another machine. Is documentation wrong or this is a bug?

**Comment by emgarten** [comment]
This has been fixed in NuGet 3.0.0.
