### ISSUE TITLE
Wrong product version values in nuget.exe 6.6

### ISSUE THREAD

**Issue by MindaugasBaltakis** [NuGet/Home#12597]
### NuGet Product Used

NuGet.exe

### Product Version

6.6.0

### Worked before?

6.5

### Impact

I'm unable to use this version

### Repro Steps & Context

Inside nuget.exe 6.6 from https://dist.nuget.org/win-x86-commandline/v6.6.0/nuget.exe version.txt file contains:

`PRODUCTVERSION 0,0,0,0` and `VALUE "ProductVersion",    "6.6.0-preview.3+0fa557836fa35aee7d60776ef0c88176dbcd22ac.0fa557836fa35aee7d60776ef0c88176dbcd22ac"`

I think they cause issues in azure pipelines using NuGetCommand@2. 

Sorry for creating issue if release is not finished yet.

**Comment by magleaso** [comment]
Correct, this is what caused issues in NuGetCommand@2. That task is getting patched to be resilient if this happens again.

**Comment by donnie-msft** [comment]
Hello @MindaugasBaltakis, I deployed `6.6.0.61` by mistake which has the `preview.3` release label. I've now deployed `6.6.0.62` which is labelled as `6.6.0`. Please let me know if this still doesn't look how you expect.

**Comment by donnie-msft** [comment]
Duplicate of https://github.com/NuGet/Home/issues/12595

**Comment by MindaugasBaltakis** [comment]
@donnie-msft it works. Thank you very much for speedy fix.
