### ISSUE TITLE
NuGet 3.1 command-line returns 0 exit code on restore errors

### ISSUE THREAD

**Issue by FeodorFitsner** [NuGet/Home#1259]
When some packages cannot be restored you see "Unable to find version X of package Y" in the log, but at the same time exit code returned by nuget.exe is always `0` and you can't basically handle these errors in build script.

NuGet 2.8.5 treats errors correctly and returns exit code `1`.

**Comment by emgarten** [comment]
This looks like the same issue as: https://github.com/NuGet/Home/issues/1186

**Comment by FeodorFitsner** [comment]
Absolutely! So, it's fixed in 3.2?

**Comment by emgarten** [comment]
It's fixed, the next nuget.exe release will be coming soon. :smile:

**Comment by FeodorFitsner** [comment]
Thank you! :)
