### ISSUE TITLE
nuget pack is ignoring dependencies when using PackageReference instead of packages.config - and cannot use MSBuild /t:pack

### ISSUE THREAD

**Issue by s-t-e-v-e-c** [NuGet/Home#12593]
### NuGet Product Used

NuGet.exe

### Product Version

.NET 7.0

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Similar to issue 5979 except the proposed solution of running MSBuild /t:pack is not an option since the assembly is obfuscated after compilation, and then a nuget package is created.  MSBuild /t:pack attempts to do this as part of building which prevents the intermediate step of obfuscation.

**Comment by erdembayar** [comment]
Thank you for reporting this issue. Could you please provide more information about how your obfuscator works? Does it change file names or assembly names? If you know the exact resulting files, you can specify them in your `nuspec` file and use that to pack the package with `nuget.exe` pack or `msbuild /t:pack`. 

Happy coding! 🧑‍💻
