### ISSUE TITLE
nuget.exe wrongly complaining about missing readme

### ISSUE THREAD

**Issue by josesimoes** [NuGet/Home#12596]
### NuGet Product Used

NuGet.exe

### Product Version

6.6.0.61

### Worked before?

any before that

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Using this nuspec from .NET nanoFramework project:
https://github.com/nanoframework/nanoFramework.Logging/blob/main/nanoFramework.Logging.nuspec

It complains that the package should have a readme. It does have a readme (see line 12).
When executing the `pack` command it shows:

```text
E:\GitHub\nf-nanoFramework.Logging>nuget pack nanoFramework.Logging.nuspec -Version 1.1.75 -Symbols -SymbolPackageFormat snupkg -properties nativeVersion="1.0.0.0";commit="70724b742a2b6ae86eee87abbcbe41cf2da8a7ad";checksum="0x00000000"
Attempting to build package from 'nanoFramework.Logging.nuspec'.
WARNING: NU5101: The assembly 'lib\nanoFramework.Logging.dll' is placed directly under 'lib' folder. It is recommended that assemblies be placed inside a framework-specific folder. Move it into a framework-specific folder.
Successfully created package 'E:\GitHub\nf-nanoFramework.Logging\nanoFramework.Logging.1.1.75.nupkg'.
The package nanoFramework.Logging.1.1.75 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
Successfully created package 'E:\GitHub\nf-nanoFramework.Logging\nanoFramework.Logging.1.1.75.snupkg'.
```

Both nuspec file and the pack command used haven't changed for quite a while and the same pattern is being used on all other class libraries under the same org.

**Comment by martinrrm** [comment]
@josesimoes Hi! Looking at your nuspec and your project, you added `<readme>docs\README.md</readme>` and `<file src="README.md" target="docs\" />` but you don't have your README.md in a docs directory, you don't have a docs directory in your project, can you try to fix the path and try again? Thanks!

**Comment by josesimoes** [comment]
hey @martinrrm thank you for looking into this! 😃 
I was under the impression that the `<file>...` grabbed an existing file and, when packaging the nuget, would place it under the specified directory. In this case the repo README.md file is placed inside a docs folder in the package.

The above is what I see when openning the package in:
![image](https://github.com/NuGet/Home/assets/1881520/8a4f62ec-b6d3-4e9d-8308-a4113ddd9114)

And I can see a readme showing in the listing of this nuget package:
https://www.nuget.org/packages/nanoFramework.Logging/

The above leads me to think that the readme is there and is being properly packaged.

Question: your suggestion is for me to create a docs folder and copy the readme file there? I don't understand the part of the docs directory in the project... are you suggesting to create a "dummy" docs folder in the project, is that it?

Thanks!

**Comment by martinrrm** [comment]
Yess you are right, this should be working, I created a similar project structure and couldn't reproduce it.  I'm using nuget.exe 6.6.0.62
![image](https://github.com/NuGet/Home/assets/43253759/314e94d2-3140-4f35-bca3-3b829dbb624c)

It looks like it is actually adding the README and at the correct place, right?

**Comment by josesimoes** [comment]
@martinrrm I've run this with 6.6.0.62 and the warning isn't there anymore. 
Recall that the original issue was reported about 6.6.0.61. Whathever was causing it must have been fixed between those two versions.

I'm closing this now. Thank you for your time!
