### ISSUE TITLE
Signing:  enable `X509Chain.Build(...)` retry behavior by default

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#12592]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe

### Current Behavior

As of NuGet 6.0, NuGet has an environment variable which can be used to opt-in to `X509Chain.Build(...)` retry behavior on Windows only when the only failure is that the root certificate is untrusted.  See https://github.com/NuGet/NuGet.Client/pull/4259 for more context.

### Desired Behavior

We should enable this retry behavior by default with reasonable values and the same restrictions (i.e.:  untrusted status on Windows) while still allowing users to override or opt-out of the default.

For example, if we choose `3,1000` as the default, a user could override by setting the environment variable with different values:

```
set NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY=10,3000
```

A user could also opt out (meaning, no retry at all) with a different value (TBD, but possibly just `0`):

```
set NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY=0
```

A [GitHub search](https://github.com/search?q=NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY&type=code) reveals `3,1000` as the most common value, with `9,2000` being next most common.

### Additional Context

The root problem is that a particular API call isn't retried, and it should be.  Whether or not Windows adds a retry, retrying is the only mitigation.  We can broadly mitigate this issue for NuGet users by retrying by default.

CC @joelverhagen

**Comment by jebriede** [comment]
Team Triage: @dtivel Looks good. Assigned this to you and put it in next sprint. Thanks!
