### ISSUE TITLE
New prebuilt package in .NET source-build: ilmerge.3.0.21.nupkg

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [NuGet/Home#12604]
New prebuilt package was introduced by `nuget/nuget.client`  repo, in latest flow to `installer`: https://github.com/dotnet/installer/pull/16391

```
ilmerge.3.0.21.nupkg
```

This needs to be fixed asap.

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
