### ISSUE TITLE
Visual Studio 2015 IVsPackageInstaller InstallPackage

### ISSUE THREAD

**Issue by xAaeEx** [NuGet/Home#1260]
Hello,

I updated the NuGet.Core and NuGet.VisualStudio assemblies on my VS 2015 extension and I when I use the IVsPackageInstaller InstallPackage Method I get the following exception:

Implementation:

```
NuGetPackageInstaller = _serviceHost.GetService<IVsPackageInstaller>();
…
this.NuGetPackageInstaller.InstallPackage(onlineRepo, project, packageId, chosenVersion, true, false);
```

Exception:

```
Specified method is not supported.
at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(IPackageRepository repository, Project project, String packageId, String version, Boolean ignoreDependencies, Boolean skipAssemblyReferences)
```

Did I do something wrong? If this is the wrong method to install a NuGet package to a Visual Studio project, which implementation is the correct one?

Thanks

**Comment by emgarten** [comment]
Use any of the other IVsPackageInstaller.InstallPackage methods.  

IPackageRepository is not part of the IVs interfaces and it is easy to hit issues when the version of NuGet.Core in your extension becomes out of sync with the version of NuGet in Visual Studio.

**Comment by xAaeEx** [comment]
Now it seems to be working as expected. Thanks a lot!
