### ISSUE TITLE
NU1100 is used for both TFM incompatibility and for an unresolved PackageSourceMapping

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#12606]
### NuGet Product(s) Affected

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe, NuGet SDK

### Current Behavior

When an install fails, the message I get is this: "Error    NU1100    Unable to resolve 'Swashbuckle.Core (>= 5.6.0)' for '.NETFramework,Version=v4.7.2/win-x86'. PackageSourceMapping is enabled, the following source(s) were not considered: nuget, nuget-build. "

I don't know if the failure is because of TFM incompatibility, or because I forgot to add source mapping

![image](https://github.com/NuGet/Home/assets/49205731/ddfe8a46-cf89-4f60-aeca-ba499e9981bd)

### Desired Behavior

Specific messages for either scenario. 
Specify whether the TFM not compatible, or is the PackageSourceMapping not configured?

**Comment by nkolev92** [comment]
NU11**  errors are always package unavailable. 

NU12** are compat errors.

**Comment by donnie-msft** [comment]
@nkolev92 - Considering that I'm already creating an NU code in https://github.com/NuGet/Home/issues/12953 
... What if I create another NU111X and move the Package Source Mapping scenario to it?
https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100#scenario-2

This would sort of make NU111X prefix space a place for 10 source mapping specific error codes.
More importantly, this issue could be closed since it would help the concern of NU1100 representing multiple scenarios.

**Comment by nkolev92** [comment]
This is not really a bug. 
Let's have an offline discussion, the error here says that the package can't be found, nothing to do with compat.

**Comment by nkolev92** [comment]
I removed this from the NuGet.Client project. By adding it to the project, triage never saw this issue.

**Comment by jeffkl** [comment]
Team Review: Closing as not a bug.  The docs for NU1100 state that if you're using package source mapping and the package isn't found but exists on your feeds you need to add a mapping.

https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1100
