### ISSUE TITLE
Escaped filename characters causing package installation failures

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1261]
_From @ProductionReady on August 26, 2015 2:45_

I am trying to install either package https://www.nuget.org/packages/Harvest.Chosen/ or https://www.nuget.org/packages/chosen/ however I am receiving errors with Visual Studio 2015. Both packages contain a file "chosen-sprite@2x.png" but when installing, the package installation errors out and says it cannot file "c:.....nuget\packages\chosen\1.2.0\content\chosen-sprite%402x.png". I can manually create a file in the package directory with the name shown in the error and the package moves on, however this is not a valid strategy for deploying these packages with mine. Can you take a look?

_Copied from original issue: NuGet/NuGetGallery#2641_

**Comment by ProductionReady** [comment]
Sorry for putting defect in the wrong project... Just adding a comment so I can get notified when the solution is fixed. Thanks!

**Comment by yishaigalatzer** [comment]
@ProductionReady we believe we fixed a lot of these issues in 3.2-RC, didn't verify your scenario though.

Here is how to get the newer bits http://blog.nuget.org/20150902/nuget-3.2RC.html

@zhili1208 can you please verify this was fixed or needs more work?

**Comment by yishaigalatzer** [comment]
Sorry @zhili1208 it was so easy to test, so I just did. This works fine now
