### ISSUE TITLE
NuGetAudit should warn when no vulnerability data available

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12610]
### NuGet Product(s) Involved

NuGet.exe, MSBuild.exe, dotnet.exe

### The Elevator Pitch

With the newly available NuGetAudit feature, it gets package vulnerability data from package sources. However, if none of the package sources contain vulnerability information (for example, a package source that upstreams to nuget.org, but doesn't yet know about the brand new vulnerability info server resource), then the initial implementation of the feature will succeed without any warnings. This is indistinguishable from none of the packages having known vulnerabilities, and therefore gives a false sense of security.

In this scenario, restore should raise a warning that no package sources provide vulnerability data.

**Comment by nkolev92** [comment]
Adding a by design since we decided to cut this.

We might need/want a more appropriate label but I'm ok with by design for now.
