### ISSUE TITLE
NuGet.Client needs to target net8.0 for source-build

### ISSUE THREAD

**Issue by MichaelSimons** [NuGet/Home#12620]
NuGet.Client needs to target net8.0 for source-build in order to eliminate all probuilts.  Source-build must build the complete dependency graph with no external dependencies.  We don't allow targeting net7 or (n-1) as is would require building all of .NET 7.0 from source which would snowball.

**Comment by MichaelSimons** [comment]
@NikolaMilosavljevic is this something you could help with?

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
