### ISSUE TITLE
[Pack] Warning NU5100 “the assembly 'Package1.1.0.0.nupkg\lib\net481\Package1.dll' is not inside the 'lib' folder” shows incorrectly while the dll file is already inside the 'lib' folder

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12624]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.7.0.51

### Impact

It bothers me. A fix would be nice

#### Steps:
1. Open VS and create a C# Class Library (.Net Framework 4.8.1) project. 
2. Build the solution and make sure compilation succeeds. 
3. Open “Developer Command Prompt”, cd to Package1 project path and execute `nuget spec`.
4. Execute command `nuget pack Package001.csproj `and make sure the “Package1.1.0.0.nupkg” is packed successfully.
5. Change the “Package1.1.0.0.nupkg” file extension to “Package1.1.0.0.nupkg.zip” and click “Extract All” context menu.
6. Execute command `nuget pack Package001.nuspec -OutputDirectory C:\Users\v-luzh\Desktop\OtherPath -version 3.0.0`.
#### Expected:
The lase warning NU5100 “the assembly 'Package1.1.0.0.nupkg\lib\net481\Package1.dll' is not inside the 'lib' folder” should not show.
#### Actual:
Warning NU5100 “the assembly 'Package1.1.0.0.nupkg\lib\net481\Package1.dll' is not inside the 'lib' folder” shows incorrectly while the dll file is inside the 'lib' folder as below.
![image](https://github.com/NuGet/Home/assets/20632625/588feec5-2111-4447-ba99-6da134d4455e)
#### Note:
1.The warning still repro after placing the Package1.dll file inside a framework-specific folder under a lib folder as the “solution” said in the [Doc](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5100) file as below.
![image](https://github.com/NuGet/Home/assets/20632625/5f235f10-e242-4a18-8c81-eb3bb3d3ac42)
2.It is not a regreasion since it reproes from the beginning.

**Comment by jeffkl** [comment]
The warning is correct, the assembly path is not rooted in the `lib` folder but instead is rooted in the `Package1.1.0.0.nupkg` folder.

**Comment by v-luzh** [comment]
But the same warning appears when I put all the assembly path in a lib folder under the package folder.

**Comment by zivkan** [comment]
@v-luzh when you pack a nuspec that does not have a `<files>` section in the XML, it packs all files in the current directory. I don't understand what **exactly** you mean by "when I put all the assembly path in a lib folder", but if the same warning appears, that means you didn't rename or move the `Package1.1.0.0.nupkg` directory. If you open the nupkg in a zip program, or NuGet Package Explorer, you will see that the package contains a directory named `Package1.1.0.0.nupkg`, and underneath it there is the lib directory.

Whereas, when you pack the csproj, it tries to automatically determine which files to include in the package from the project file, and automatically put files in the correct directories depending on their conventions.

So, I don't understand what user-scenario this test is trying to validate.  What would a developer being trying to achieve by exacting a package in a sub-directory, and then packing the nuspec, causing the original package's contents to be a sub-directory within the second package?

If the user-scenario is trying to test re-packing an existing package, then it's an error in the test steps. The second `nuget pack package1.nuspec` (step 6 in the original issue) needs to be done inside the extracted directory, not the parent directory where the package was extracted to (in this case, where the csproj is)

**Comment by v-luzh** [comment]
Hi @zivkan, thanks for your info. I meant when we run into this warning, under the package folder (C:\Users\v-luzh\source\repo\Package1\Package1) we created a folder called "lib", created another folder "net481" in the folder "lib" and copied all the dll files into the folder "net481" to see if this resolution (as the doc above said) should make the warning gone. But it doesn't work. The purpose of this test scenario in this bug is testing if the solution works.

So, do you mean above operation of the resolution is invalid? And customer usually use "nuget pack package1.csproj"?

**Comment by nkolev92** [comment]
@v-luzh 

*After* you see get the warning again, can you please open the newly creating nupkg and post the directory structure inside? You can always *upload* the new package here and it'll be the easiest way to confirm the behavior.

**Comment by v-luzh** [comment]
@nkolev92 The warning still shows after I put the dll into the lib\net481 folder as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/60953253-c059-466f-b73a-f8365efff161)
Upload the newly created nupkg for your investigation. Thanks a lot.

[Package02.3.0.0.nupkg.zip](https://github.com/NuGet/Home/files/11798307/Package02.3.0.0.nupkg.zip)

**Comment by zivkan** [comment]
@v-luzh the nupkg you attached does indeed have a `obj/Debug/Package02.dll` file, so the warning is working as designed.

Whoever created the test probably intended for you to extract the nupkg into an empty directory. Windows's zip extractor by default puts the extracted files in a subdirectory with the same of the zip file (minus .zip), it does not by default put the extracted files in the same direct as the zip file.

Since you extracted the files in the same directory as the project, the second nupkg contains the csproj, the nupkg.zip file, the obj/ and lib/ subdirectories, etc.

**Comment by v-luzh** [comment]
@zivkan Thanks for your description. I will close it as by-design.
