### ISSUE TITLE
NuGet UI at Solution Level for large solutions is very slow

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1262]
From vs-feedback - https://vs-feedback/comment/428156

In a very large solution (155 projects), when opening the 2015 NuGet user interface for the solution it takes 5-10 minutes to load the interface and paint the list of packages.  Previous versions of the extension in earlier versions of Visual Studio would take 2-3 minutes to load the interface.

The total time for NuGet workflow in a solution this size approaches an hour.

**Comment by yishaigalatzer** [comment]
@emgarten @feiling @johnataylor 

I'm suspecting we have a mix of issues here (UI making too many network calls, and underlying implementation being pretty inefficient).

Lets start by creating a repro and see where we can take it from here.

**Comment by yishaigalatzer** [comment]
@feiling can you please look at this first thing on Monday?

**Comment by philipbjorge** [comment]
This is extremely slow for me with a 10 project solution and ~60 packages.

**Comment by yishaigalatzer** [comment]
@philipbjorge can you share more info about your project? This shouldn't take this long.

What sources are you using? What version of NuGet and visual studio?

**Comment by philipbjorge** [comment]
@yishaigalatzer -- 

Visual Studio Professional 2015
Version 14.0.24720.00 Update 1

Nuget Package Manager for Visual Studio 2015
3.3.0.167

1 Solution
13 Projects
All projects have < 15 packages defined in packages.config with the exception of one which has 60 packages defined

On my machine, I have the following package sources defined:
- https://www.nuget.org/api/v2/
- MyGet V3 Private Repo
- C:\LocalNuget

Let me know if there is anything else that would be helpful.

---

From Manage Packages for Solution UI:
It takes a few seconds for the Installed tab to load (reasonable). A major source of slowness is simply scrolling the list of installed packages. It appears as if the whole UI is blocking while downloading thumbnails.

It takes about 10 seconds to load the updates tab. Scrolling up and down causes the whole UI to block on what appears to be thumbnails.

Is there a fix for this that's unreleased? When can we expect a release addressing this issue?
It appears as if a number of users are being affected by this: https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d

**Comment by philipbjorge** [comment]
@yishaigalatzer -- Is the source code available for the Visual Studio extension?
The performance is terrible enough here I'd like to fix it locally for my team.

**Comment by yishaigalatzer** [comment]
@philipbjorge the source code is definitely available on https://github.com/NuGet/nuget.client/ if you think you can fix performance problems, we would love to take pull requests. We do have a develop planned to work on this for the coming 3.4 release CC @johnataylor 

Can you share how many packages you have in your C:\LocalNuget folder?

One major change in NuGet 3.X is that we are talking to all source simultaneously to get possible updates, if one of the sources is extremely slow it will impact the overall speed, but will provide the more correct answer.

We have a bug in our backlog to detect slow sources and report them to the user (so he can disable them or work around them).

**Comment by philipbjorge** [comment]
At the time I had 15 packages in C:\LocalNuget.
I've since emptied it and while everything is still slow I don't have the UI freezing up on me anymore.

Thanks for the link to the source. I'll see if I can investigate if its a slow package source or if something more heinous is going on :wink: and I'll report back.

**Comment by yishaigalatzer** [comment]
Awesome! Note that you can use fiddler to look at speed before diving into source. Also given your other feedback, are you running nuget 3.3?

**Comment by philipbjorge** [comment]
@yishaigalatzer -- The version of my Nuget Extension is 3.3.0.167. 
Does this mean it will use the corresponding 3.\* version of nuget.exe?

**Comment by yishaigalatzer** [comment]
no, you need to pick that. At the moment running nuget.exe -Update Self will get you 3.3 (the build for nuget.exe is 212)

**Comment by yishaigalatzer** [comment]
@philipbjorge are you able to give our private RTM bits a test run for your scenarios? I'm not confident it fixes your cases because I don't have a repro (and would love to declare success/fail for you before we ship).

Shoot me an email y i g a l a t z @ msft.com

**Comment by yishaigalatzer** [comment]
ping - We are going to lock things down shortly.

**Comment by yishaigalatzer** [comment]
We haven't heard back for over two weeks now, so I'm going to move this out to the next release, hopefully it is fixed for you, and if not we would love a repro project.

**Comment by nkolev92** [comment]
A lot of things have changed/have been improved since this issue have been created.

Closing this for now.
