### ISSUE TITLE
C++\Cli PackageReference .NET 6+ doesn't restore when executed from command line

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#12636]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

dotnet 7.0.302, msbuild 17.6.3.22601, nuget 6.6.0.62

### Worked before?

no / I don't know

### Impact

I'm unable to use this version

### Repro Steps & Context

Visual Studio 17.6.2

Create new CLR Class library

Visual Studio automatically restore vcxproj creating file obj\project.assets.json

Compile inside Visual Studio -> SUCCESS

Close Visual Studio

Open Developer Command Prompt for VS 2022

CD vcxproj folder

Delete obj folder

run "msbuild t:/restore" or "nuget restore" or "dotnet restore" (same issue)

file obj\project.assets.json was not recreated

run "msbuild" -> Error "NETSDK1004: Assets file 'C:\Users\fmontanari\source\repos\ClassLibraryCli\ClassLibraryCli\obj\project.assets.json' not found."

I'm unable to use C++/CLI vcxproj with PackageReference inside a continuous integration scenario

![msbuild restore](https://github.com/NuGet/Home/assets/32999837/86270cb4-de19-4ec4-aa05-3f407591619c)
![msbuild error](https://github.com/NuGet/Home/assets/32999837/da324bcc-c7e6-4555-8a58-1bf03d0d68e1)

**Comment by nkolev92** [comment]
Hey @qubicaamf, 

can you upload a repro project by any chance?

**Comment by ghost** [comment]
Here is the repo you asked for
[ClassLibraryCli.zip](https://github.com/NuGet/Home/files/11756495/ClassLibraryCli.zip)

**Comment by ghost** [comment]
I found a workaround,
If I add at least one package the command line restore works fine as inside Visual Studio.

**Comment by nkolev92** [comment]
Hey @qubicaamf, 

Another workaround is to specify `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`. 
Have you filled this issue in developer community by any chance? It seems to be an issue with the project template?

**Comment by ghost** [comment]
thanks, your workaround works fine as well.
I'm going to open an issue in the visual studio developer community

**Comment by nkolev92** [comment]
Hey @qubicaamf 
There's a fix that's been merged on the project template side for this. 
It should be released in 17.7 Preview 3 of Visual Studio.
