### ISSUE TITLE
Updating a package removes developmentDependency attribute from packages.config

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#1263]
It seems to reason that if a package is a development dependency before updating, it should remain one after a package update. Steps to reproduce:
- Create a new console project
- Run `Install-Package boostrap -version 3.3.4` from the Package Manager Console
- Open `packages.config` and add `developmentDependency="true"` for both the `bootstrap` package and `jQuery` package (which is installed as a dependency of `boostrap`)
- Open the Package Management GUI for the project
- Update the `bootstrap` package to 3.3.5 using default behavior
- Go back to `packages.config` and notice that `developmentDependency="true"` is no longer on the `bootstrap` package (though it's still on the `jQuery` package, probably because it wasn't updated)

**Comment by emgarten** [comment]
This is related to https://github.com/NuGet/Home/issues/1130

**Comment by emgarten** [comment]
Visual Studio 2013 persisted the developmentDependency property, I've fixed NuGet 3.2.0 to persist this also.

NuGet/Nuget3@945d8b6a59f58e9c5ae42e7f88f254ad6658456c
