### ISSUE TITLE
NuGetAudit: Show package graph path

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12635]
### NuGet Product(s) Involved

MSBuild.exe, dotnet.exe

### The Elevator Pitch

When NuGetAudit checks transitive packages, and a package with a known vulnerability is found, it's hard to determine why the package has been included. When the transitive package is included because a top level package isn't on the latest version, it's sometimes (often?) preferable to update the direct package reference, rather than introduce the transitive package as a direct reference, especially when the project isn't already using Central Package Management.

**Comment by zivkan** [comment]
Consider `dotnet nuget why` instead:

* https://github.com/NuGet/Home/issues/11943

**Comment by zivkan** [comment]
`dotnet nuget why` has been implemented, and we think is sufficient, maybe even better, than trying to report the package path in restore.

**Comment by TheXenocide** [comment]
Will this work for projects that target .NET Framework?
