### ISSUE TITLE
Avoid repeated Enum.ToString() in PackageSpecWriter.SetDependencies

### ISSUE THREAD

**Issue by Erarndt** [NuGet/Home#12638]
PackageSpecWriter.SetDependencies calls Enum.ToString() on two enum types and multiple fields:

LibraryDependencyTarget
LibraryIncludeFlags

This causes unavoidable stringbuilder allocations to produce the various combinations. Normally this never shows up, however, in NuGut this code path is called a lot and hence it needs to work around this.

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)

**Comment by nkolev92** [comment]
Completed in https://github.com/NuGet/NuGet.Client/pull/5215
