### ISSUE TITLE
Nuget Package Visualizer is missing in Visual Studio 2015 Enterprise

### ISSUE THREAD

**Issue by phillipc** [NuGet/Home#1264]
The package visualizer isn't available in the nuget menu "Tools -> Library Package Manager -> Package Visualizer"

Nuget-Version: 3.1.60724.766
VS-Version: Visual Studio Enterprise 2015 - Version 14.0.23107.0

**Comment by yishaigalatzer** [comment]
We did not port it over from 2.8.6, currently this is a lower priority item comparing to the rest of the NuGet issues we have in flight. We can get to it later or take a pull request.

**Comment by amccool** [comment]
+1

**Comment by yishaigalatzer** [comment]
We where just discussing this. This seems like something that should be a straighforward port from NuGet2, we just don't seem to free up enough to get to this, so I'm marking as up for grabs for now.

**Comment by chillitom** [comment]
Could someone familiar with the code base leave a short description of what would be required to port this over?

**Comment by yozepi** [comment]
I really, really miss this feature!

**Comment by biliktamas79** [comment]
Yeah. I miss it too.

**Comment by Zimmergren** [comment]
I'd love to hear about any progress on this issue too, as it's a pretty vital tool for the toolbasket.

**Comment by yishaigalatzer** [comment]
It's currently not on our roadmap due to other high priority items. However as the label `UpForGrabs` indicate, we will gladly take a pull request to bring it back. 

We are not sure about the complexity and cost of the work when it comes to transitive restore scenarios, so this might go a bit beyond porting the old code from the nuget2 repo over to the new code base.

**Comment by 0xced** [comment]
Brent Krueger created a [Nuget Package Visualizer Extension for VS2015](https://www.kruegerwebdesign.com/blog/nuget-package-visualizer-extension-vs2015).

**Comment by nkolev92** [comment]
Thanks for this feedback. 

At this point in time, we are not planning on servicing the VS 2015 release. 

I will close this issue, and open a new one tracking the implementation for package reference based projects as well. 

https://github.com/NuGet/Home/issues/6339

Similarly as this issue, that task is up for grabs as well, so we will be happy to help.
