### ISSUE TITLE
PackageSpec.Clone and LibraryDependency.Clone overwrite collections created by their constructors.

### ISSUE THREAD

**Issue by Erarndt** [NuGet/Home#12642]
Both `Clone` methods create a new default object that has collections that get implicitly assigned in the constructors. The `Clone` method then proceeds to overwrite the collections that were just created. We can avoid this to reduce allocations.

This code is used in restore, so will benefit restore in Visual Studio, msbuild, dotnet, and nuget.exe.

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
