### ISSUE TITLE
Order dependent packageSource bug 

### ISSUE THREAD

**Issue by TheKnarf** [NuGet/Home#12658]
### NuGet Product Used

dotnet.exe

### Product Version

```
dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/Cellar/dotnet/7.0.100/libexec/sdk/7.0.100/

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [/usr/local/Cellar/dotnet/7.0.100/libexec/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/Cellar/dotnet/7.0.100/libexec/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/Cellar/dotnet/7.0.100/libexec]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Impact

It's more difficult to complete my work

### Repro Steps & Context

So this does not work:

```
<configuration>
	<config>
		<add key="maxHttpRequestsPerSource" value="4" />
	</config>
	<packageSources>
		<clear />
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
		<add key="DevExpress" value="https://nuget.devexpress.com/secretkey/api" />
	</packageSources>
</configuration>
```

This didn't work just getting timeouts. Finally found @andersstorhaug comment in [this bug repport](https://github.com/NuGet/Home/issues/7413) and changed up the order of `nuget` and `DevExpress` and suddenly everything works flawlessly:

```
<configuration>
	<config>
		<add key="maxHttpRequestsPerSource" value="4" />
	</config>
	<packageSources>
		<clear />
		<add key="DevExpress" value="https://nuget.devexpress.com/secretkey/api" />
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
	</packageSources>
</configuration>
```

### Verbose Logs

```shell
$ dotnet restore
  Determining projects to restore...
  Restored /Users/knarf/projects/tds/TDSPortal/TDSPortal.Enums/TDSPortal.Enums.csproj (in 2.61 sec).
  Restored /Users/knarf/projects/tds/TDSPortal/TDSPortal.Tests/TDSPortal.Tests.csproj (in 17.85 sec).
  Failed to download package 'DevExpress.Blazor.22.2.4' from 'https://nuget.devexpress.com/secretkey/api/package/DevExpress.Blazor/22.2.4'.
  The HTTP request to 'GET https://nuget.devexpress.com/secretkey/api/package/DevExpress.Blazor/22.2.4' has timed out after 100000ms.
```

**Comment by TheKnarf** [comment]
**Update**

It no longer works locally, but did work in my CI pipeline in Azure DevOps. So I no longer have any clue if this is a `dotnet nuget`-cli issue or if the DevExpress server is just really flaky / having issues (and just as I wrote this it worked again).

Maybe someone else can double check in a repeatable manner if its actually order dependent?

**Comment by nkolev92** [comment]
Hey @TheKnarf, 

Apologies for the long delay. 

The order the sources are declared should not be affecting timeouts. https://learn.microsoft.com/en-us/nuget/concepts/package-installation-process

If the timeouts are coming from a specific source, you should consider reaching out to the service as they'll be able to diagnose it better.

**Comment by iqapps** [comment]
This problem STILL exist in 2024, was reported first in 2018.

All tools in my toolchain are updated tolatest versions.

If one specify a folder source first and a https source second, then the https source is formatted internally by dotnet, as if it is another local source with an absolute path.

Running **dotnet restore** command specifying multiple sources in specific order:

dotnet restore --source "C:\Code\Packages" --source https://api.nuget.org/v3/index.json

Throws Error:

SomeProject.csproj : error NU1301: The local source 'C:\Code\https://api.nuget.org/v3/index.json' doesn't exist. [SomeSoultion.sln]

This is clearly very wrong.
