### ISSUE TITLE
Reduce allocations in ContentItemCollection

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#12657]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, NuGet SDK

### Product Version

All versions

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I created this issue to track https://github.com/NuGet/NuGet.Client/pull/5200#discussion_r1227141863 code review feedback.

**Comment by nkolev92** [comment]
It's been done now: https://github.com/NuGet/NuGet.Client/blob/9331d0c10918602da91ac0bc5207ce143851427c/src/NuGet.Core/NuGet.Packaging/ContentModel/ContentItemCollection.cs#L107.
