### ISSUE TITLE
Latest patch has breaking change on Linux

### ISSUE THREAD

**Issue by Inok** [NuGet/Home#12655]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet 6.3.3.3

### Worked before?

6.3.2.9

### Impact

I'm unable to use this version

### Repro Steps & Context

That change in the latest version broke our builds. The problem is that the well-known (and documented [here](https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)) folder `/tmp/NuGetScratch` now depends on the username on Linux.

Here is the change that broke it: https://github.com/NuGet/NuGet.Client/commit/5e444458a8c4a2dac9806fc1d387b7f157669540#diff-bd5079461f77fe4398660802d5b56e2139e99865e480d89b12cd42b244f64715R41

After that change, we get `/tmp/NuGetScratch/username` instead of `/tmp/NuGetScratch` on the Linux platform.

It broke our builds because we share `/tmp/NuGetScratch` (and other folders) between different docker containers which restore packages concurrently, and now that path has changed.

Instead, the path probably should be like `/tmp/NuGetScratch/username` (subfolder for every user inside NuGetScratch):
```
RuntimeEnvironmentHelper.IsLinux ? Path.Join("NuGetScratch", Environment.UserName) : "NuGetScratch"
```

### Verbose Logs

```shell
## 6.0.408
❯ docker run --rm -it mcr.microsoft.com/dotnet/sdk:6.0.408-bullseye-slim
root@0686b672d9aa:/# dotnet nuget locals all -l
http-cache: /root/.local/share/NuGet/http-cache
global-packages: /root/.nuget/packages/
temp: /tmp/NuGetScratch
plugins-cache: /root/.local/share/NuGet/plugin-cache

## 6.0.410
❯ docker run --rm -it mcr.microsoft.com/dotnet/sdk:6.0.410-bullseye-slim
root@c06c837b2957:/# dotnet nuget locals all -l
http-cache: /root/.local/share/NuGet/http-cache
global-packages: /root/.nuget/packages/
temp: /tmp/NuGetScratchroot
plugins-cache: /root/.local/share/NuGet/plugin-cache
```

**Comment by nkolev92** [comment]
cc @heng-liu @kartheekp-ms

**Comment by kartheekp-ms** [comment]
@Inok - I understand the bug report and the suggested solution. Could you kindly consider adding the `NUGET_SCRATCH` environment variable pointing to a shared location, as a potential workaround?

Suppose we follow your suggestion and modify the directory path to something like `/tmp/NuGetScratch/userA`. Assuming that the `/tmp/NuGetScratch/` directory is world writable but only `userA` can access the files within the `/tmp/NuGetScratch/userA` directory. I'm uncertain how other users can benefit from this solution since each user will have their individual folder within `/tmp/NuGetScratch`. Please inform me if I have misunderstood anything.

**Comment by Inok** [comment]
@kartheekp-ms, thanks for the workaround! It fixes the issue. However, that variable isn't documented [here in the docs](https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders) (variables for other locations are documented). Is it safe to use it in the long term?

I don't think someone cares if it's separate directories in `/tmp` for each user or if it's a single directory `/tmp/NuGetScratch` with all the per-user stuff inside it. So the change, in its essence, is great. 

My point is that the documented behavior has changed in a minor version, which led us to non-obvious failures in CI/CD after the upgrade. So, for backward compatibility, it would be safer to keep the path to the temp directory the same (`/tmp/NuGetScratch/`) and make all the per-user changes inside of it.

But since it's already released now, IMO there is no point to roll it back anyway. But it would be great if you change the docs and consider mentioning such changes in release notes.

**Comment by heng-liu** [comment]
Thanks @Inok for your suggestion!
We updated the doc to address this change in [doc](https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders).
Unfortunately we need to make this change, despite it's a breaking change in a minor version. Thanks for your understanding! 
We will mention this breaking change in the release notes to remind people about it.

**Comment by Inok** [comment]
Thanks!
