### ISSUE TITLE
No license shows when clicking the “view license” link of the package “FSharp.Net.Http” in the right penal of PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12660]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.7.0.83

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Open VS and create a F# Console Application (.Net Framework 4.8.1) project. 
2. Right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI. 
3. Click “Browse” tab and select the “nuget.org” from Package source drop-down list.
4. Search the package “FSharp.Net.Http” in the filter and click the package in the package list.
5. Click the “view license” link of the package “FSharp.Net.Http” in the right penal of PM UI.

#### Expected:
The license shows correctly.

#### Actual:
Nothing shows for the license info as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/d38177b4-010b-444b-85fe-fb63f24c256e)
#### Notes:
1.Repro rate: 100%.
2.It is not a regression bug since it reproes on 17.5.4 Preview 1.0 [33530.505.d17.5]+ Dev\6.5.0.154.

**Comment by agr** [comment]
Sounds like a package authoring issue: invalid license URL is specified in the package metadata. It should be brought up to the package author.

**Comment by nkolev92** [comment]
@martinrrm Seems like it be related to https://github.com/NuGet/Home/issues/12060?

When you work on that can you please confirm if that's the case? 
If it is *not*, please let us know so we can retriage.

**Comment by martinrrm** [comment]
@nkolev92 This is a package issue, the License link points to https://github.com/frank-fs/frank/raw/master/LICENSE.txt which is not valid, maybe Github did a breaking change to raw files url since other packages with GH url have a different url format

**Comment by nkolev92** [comment]
Feel free to close. I totally missed @agr's original comment.

**Comment by martinrrm** [comment]
Closing since its a package issue, consider opening a bug in the package repo.
