### ISSUE TITLE
unable to create a nupkg with framework .NETPortable v5.0

### ISSUE THREAD

**Issue by jorisdebock** [NuGet/Home#1267]
@yishaigalatzer had to create a new issue since i couldnt reopen #1134 myself.

I am unable to create a nupkg with framework .NETPortable v5.0.

 I made an example repo https://github.com/jorisdebock/PCLNugetExample
This is in a PCL which targets .net framework 4.6 and windows universal 10.0

Using the nuget.exe beta 3.1.0 with the following command 
`nuget.exe pack PCLNugetExample\PCLNugetExample.csproj`

result:

```
WARNING: Unable to extract metadata from 'PCLNugetExample.dll'.
Value cannot be null or an empty string.
Parameter name: profileValue
```

Not sure if i am missing something or?

**Comment by emgarten** [comment]
nuget.exe pack does not support project.json projects. You will need to pack using a nuspec.

**Comment by yishaigalatzer** [comment]
@emgarten is this feature tracked already?

**Comment by emgarten** [comment]
@yishaigalatzer not yet

**Comment by jorisdebock** [comment]
Even with a nuspec file added, almost same result:

```
WARNING: Unable to extract metadata from 'PCLNugetExample.dll'.
Using 'PCLNugetExample.nuspec' for metadata.
Value cannot be null or an empty string.
Parameter name: profileValue
```

What is this "profileValue" ? Is this in the nuspec file or?

@emgarten  Also i thought 3.1.0 does support project.json files, that is what the blog says at least

**Comment by yishaigalatzer** [comment]
Can you share the nuspec and the exact command you are using?

Project.json is supported for restore, we did not build support for pack yet.

**Comment by emgarten** [comment]
I think it's complaining about this line in the csproj:

``` xml
<TargetFrameworkProfile></TargetFrameworkProfile>
```

**Comment by yishaigalatzer** [comment]
@emgarten are we able to improve this error message?

**Comment by jorisdebock** [comment]
@yishaigalatzer nuspec is in the repo
@emgarten ye i think so too, when using .netportable v5.0 that one is empty

**Comment by yishaigalatzer** [comment]
@jorisdebock The suggestion is to use a fully fleshed out nuspec, and pack from the nuspec and not from the csproj.

We are working on documentation samples that should be up in a few days for these scenarios.

CC // @ericstj

**Comment by ericstj** [comment]
Here's my doc in progress: https://github.com/ericstj/NuGetDocs/blob/ericstj/nuget3samples/NuGet.Docs/Create/nuget3-packages-walkthrough.md

**Comment by jorisdebock** [comment]
@yishaigalatzer  @ericstj  ok thanks, going to try it out.

**Comment by jorisdebock** [comment]
@ericstj ok followed the doc and now successfully created a package
