### ISSUE TITLE
Polly 7.2.4 nuget package - invalid package signature or a signature that cannot be verified on Windows.

### ISSUE THREAD

**Issue by elina-zh** [NuGet/Home#12682]
### NuGet Product Used

dotnet.exe

### Product Version

6

### Worked before?

no

### Impact

I'm unable to use this version

### Repro Steps & Context

 Repro Steps:
 Perform dotnet restore on Polly 7.2.4 nuget package on Windows
 The action is fails with the following error:
 Package 'Polly 7.2.4' from source '[https://api.nuget.org/v3/index.json']: The package signature is invalid or cannot be verified on this platform.
 
The failure is happening on Windows, where on Linux it is working.

**Comment by nkolev92** [comment]
Hey @elina-zh 
Which exact version of the .NET SDK are you using?

**Comment by elina-zh** [comment]
We are using the latest - 6.0.410.

**Comment by zivkan** [comment]
@elina-zh are you getting this consistently, or does the package sometimes restore successfully?

If this is only happening sometimes (so you only see it on CI machines, but if you create a lot of virtual machines for testing, you might see it in manual testing as well), then you can try setting the `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY` environment variable, similar to this PR: https://github.com/NuGet/NuGet.Client/pull/5212/files

We haven't yet had enough feedback about whether setting this environment variable helps, or makes things worse (longer delays before failing with the same error), which is why it's still experimental and needs to be opt-in.

**Comment by elina-zh** [comment]
It's consistently, on the CI machines. We will check the parameter.

**Comment by elina-zh** [comment]
We tried to set NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY  environment variable
```
variables:
    NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
```
However it doesn't look like it is used and the package restore still fails with the same error.

**Comment by zivkan** [comment]
You can download the package with powershell: `Invoke-WebRequest https://www.nuget.org/api/v2/package/Polly/7.2.4 -OutFile polly.nupkg`

Then, please run `dotnet nuget verify polly.nupkg -v d` (on the CI machine), and show us the output. It will be interesting to find out if the package hash is different, or if a certificate chain is not trusted.

**Comment by elina-zh** [comment]
See the requested information (output):

`X.509 certificate chain validation will use the default trust store selected by .NET.
X.509 certificate chain validation will use the default trust store selected by .NET.

Verifying Polly.7.2.4
C:\test-nuget\.\polly.nupkg
Signature Hash Algorithm: SHA256

Signature type: Author
Verifying the author primary signature with certificate: 
  Subject Name: CN=Polly (.NET Foundation), O=Polly (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Washington, OID.1.3.6.1.4.1.311.60.2.1.3=US
  SHA1 hash: E9412D9B7B363AEA92EF18195D2519A94E4AE343
  SHA256 hash: B9752340121AB41446EEAB7484B7A8F176B54F3357CD601A4BE3DC7B1D08D11D
  Issued by: CN=.NET Foundation Projects Code Signing CA2, O=.NET Foundation, C=US
  Valid from: 6/2/2023 3:00:00 AM to 6/2/2026 2:59:59 AM
trace:       Subject Name: CN=.NET Foundation Projects Code Signing CA2, O=.NET Foundation, C=US
trace:       SHA1 hash: 9170E881F14FC075B8CF999402FE3D12282555AF
trace:       SHA256 hash: D60D2D02F83920E89C0063AECA7C4630642C80EB824FFE43D9A11C250E5F51B9
trace:       Issued by: CN=DigiCert CS RSA4096 Root G5, O="DigiCert, Inc.", C=US
trace:       Valid from: 7/15/2021 3:00:00 AM to 7/15/2031 2:59:59 AM
trace:             Subject Name: CN=DigiCert CS RSA4096 Root G5, O="DigiCert, Inc.", C=US
trace:             SHA1 hash: 5EEED86FA37C675230642F55C84DDBF67CD33C80
trace:             SHA256 hash: 7353B6D6C2D6DA4247773F3F07D075DECB5134212BEAD0928EF1F46115260941
trace:             Issued by: CN=DigiCert CS RSA4096 Root G5, O="DigiCert, Inc.", C=US
trace:             Valid from: 1/15/2021 2:00:00 AM to 1/15/2046 1:59:59 AM
Timestamp: 6/13/2023 4:46:19 PM
Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=Microsoft Public RSA Time Stamping Authority, OU=Thales TSS ESN:4E89-9666-FFE7, OU=Microsoft Ireland Operations Limited, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: 401993261D46909A59A1BC7D6A486D01ABFC089E
  SHA256 hash: EFF65E903F6EB1DC9FE4A0A756F57ED90A0979A9A96840E7792A729809004A56
  Issued by: CN=Microsoft Public RSA Timestamping CA 2020, O=Microsoft Corporation, C=US
  Valid from: 7/28/2022 9:16:41 PM to 7/28/2023 9:16:41 PM
trace:       Subject Name: CN=Microsoft Public RSA Timestamping CA 2020, O=Microsoft Corporation, C=US
trace:       SHA1 hash: 27F0ABAC2877BA255F62B389B43FF539A0FB598E
trace:       SHA256 hash: 36E731CFA9BFD69DAFB643809F6DEC500902F7197DAEAAD86EA0159A2268A2B8
trace:       Issued by: CN=Microsoft Identity Verification Root Certificate Authority 2020, O=Microsoft Corporation, C=US
trace:       Valid from: 11/19/2020 10:32:31 PM to 11/19/2035 10:42:31 PM
trace:             Subject Name: CN=Microsoft Identity Verification Root Certificate Authority 2020, O=Microsoft Corporation, C=US
trace:             SHA1 hash: F40042E2E5F7E8EF8189FED15519AECE42C3BFA2
trace:             SHA256 hash: 5367F20C7ADE0E2BCA790915056D086B720C33C1FA2A2661ACF787E3292E1270
trace:             Issued by: CN=Microsoft Identity Verification Root Certificate Authority 2020, O=Microsoft Corporation, C=US
trace:             Valid from: 4/16/2020 9:36:16 PM to 4/16/2045 9:44:40 PM

Signature type: Repository
Service index: https://api.nuget.org/v3/index.json
Owners: dylanreisenberger, joelhulen, Polly
Verifying the repository countersignature with certificate: 
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 68FC37CCC293766A607DBC26A26DF371B0249328
  SHA256 hash: 5A2901D6ADA3D18260B9C6DFE2133C95D74B9EEF6AE0E5DC334C8454D1477DF4
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 2/16/2021 2:00:00 AM to 5/16/2024 2:59:59 AM
trace:       Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
trace:       SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
trace:       Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       Valid from: 10/22/2013 3:00:00 PM to 10/22/2028 3:00:00 PM
trace:             Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
trace:             SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
trace:             Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             Valid from: 11/10/2006 2:00:00 AM to 11/10/2031 2:00:00 AM
Timestamp: 6/14/2023 4:24:57 AM
Verifying repository countersignature's timestamp with timestamping service certificate: 
  Subject Name: CN=DigiCert Timestamp 2022 - 2, O=DigiCert, C=US
  SHA1 hash: F387224D8633829235A994BCBD8F96E9FE1C7C73
  SHA256 hash: C7F4E1BE32288920ABE2263ABE1AC4FC4FE6781C2D64D04C807557A023B5B6FA
  Issued by: CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O="DigiCert, Inc.", C=US
  Valid from: 9/21/2022 3:00:00 AM to 11/22/2033 1:59:59 AM
trace:       Subject Name: CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O="DigiCert, Inc.", C=US
trace:       SHA1 hash: B6C8AF834D4E53B673C76872AA8C950C7C54DF5F
trace:       SHA256 hash: 281734D4592D1291D27190709CB510B07E22C405D5E0D6119B70E73589F98ACF
trace:       Issued by: CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:       Valid from: 3/23/2022 2:00:00 AM to 3/23/2037 1:59:59 AM
trace:             Subject Name: CN=DigiCert Trusted Root G4, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             SHA1 hash: A99D5B79E9F1CDA59CDAB6373169D5353F5874C6
trace:             SHA256 hash: 33846B545A49C9BE4903C60E01713C1BD4E4EF31EA65CD95D69E62794F30B941
trace:             Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:             Valid from: 8/1/2022 3:00:00 AM to 11/10/2031 1:59:59 AM
trace:                   Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:                   SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
trace:                   SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
trace:                   Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
trace:                   Valid from: 11/10/2006 2:00:00 AM to 11/10/2031 2:00:00 AM

Successfully verified package 'Polly.7.2.4'.
`

**Comment by zivkan** [comment]
@elina-zh the end of the output says "Successfully verified package 'Polly.7.2.4'"

Did restore fail on the same pipeline, but then `dotnet nuget verify` was successful?

In that case, I would expect `NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY` to fix the issue on restore, but perhaps you need to change the numbers to increase the number of retries and/or the delay between retries.

**Comment by elina-zh** [comment]
Yes, restore fails on the same pipeline.
Downloading the package and verifying it separately is successful.

**Comment by JonDouglas** [comment]
Please provide the full dotnet information using --help or --info. 6 is not enough to understand. 6.0.4xx for example would be helpful.

@dtivel may be related to trust

**Comment by elina-zh** [comment]
We are using 6.0.410.

**Comment by JonDouglas** [comment]
This might be related to https://github.com/dotnet/sdk/issues/33928

Does this reproduce on 6.0.411 or higher?

https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by dtivel** [comment]
6.0.410 should not have the problem.  In fact, 6.0.410 should already have the fix.  @elina-zh, are you sure you are using .NET 6.0.410 SDK?

Here's the PowerShell script I used to verify:

```PowerShell
[string] $sdkVersion = '6.0.410'
[string] $packageId = 'Polly'
[string] $packageVersion = '7.2.4'

If (-Not (Test-Path '.\dotnet-install.ps1'))
{
    curl -LO https://dot.net/v1/dotnet-install.ps1
}

If (-Not (Test-Path .\$sdkVersion))
{
    .\dotnet-install.ps1 -Version $sdkVersion -InstallDir .\$sdkVersion -NoPath
}

Function New-Subdirectory([string] $name)
{
    $subdirectory = [System.IO.DirectoryInfo]::new([System.IO.Path]::Combine($PSScriptRoot, $name))

    If ($subdirectory.Exists)
    {
        $subdirectory.Delete($True) # recursively
    }
    
    $subdirectory.Create()

    Return $subdirectory
}

$Env:DOTNET_MULTILEVEL_LOOKUP=0
$Env:DOTNET_ROOT="$PSScriptRoot\$sdkVersion"

[string] $dotnet = [System.IO.Path]::Combine($Env:DOTNET_ROOT, 'dotnet.exe')
[System.IO.DirectoryInfo] $packagesDirectory = New-Subdirectory('packages')
[System.IO.DirectoryInfo] $testDirectory = New-Subdirectory('test')

$Env:NUGET_PACKAGES="$($packagesDirectory.FullName)"

Write-Host "Using $dotnet" -ForegroundColor Green
Write-Host "Test directory:  $($testDirectory.FullName)" -ForegroundColor Green
Write-Host "Packages directory:  $($Env:NUGET_PACKAGES)" -ForegroundColor Green

Push-Location "$($testDirectory.FullName)"

& "$dotnet" new console

Try
{
    [string] $output = & "$dotnet" add package $packageId --version $packageVersion | Out-String
}
Finally
{
    Pop-Location
}

Write-Host $output

If ($LASTEXITCODE -eq 0)
{
    Write-Host 'Restore succeeded.' -ForegroundColor Green
}
Else
{
    Write-Host "Restore failed.  Exit code:  $LASTEXITCODE" -ForegroundColor Red
}

If ($output.Contains('NU3003'))
{
    Write-Host 'NU3003 found.' -ForegroundColor Red
}
Else
{
    Write-Host 'NU3003 not found.' -ForegroundColor Green
}
```

<details><summary>output</summary>

```
Using F:\dotnet\6.0.410\dotnet.exe
Test directory:  F:\dotnet\test
Packages directory:  F:\dotnet\packages
The template "Console App" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on F:\dotnet\test\test.csproj...
  Determining projects to restore...
  Restored F:\dotnet\test\test.csproj (in 112 ms).
Restore succeeded.


  Determining projects to restore...
  Writing C:\Users\dtivel\AppData\Local\Temp\tmp7833.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'Polly' into project 'F:\dotnet\test\test.csproj'.
info : Restoring packages for F:\dotnet\test\test.csproj...
info :   CACHE https://api.nuget.org/v3-flatcontainer/polly/index.json
info :   CACHE https://api.nuget.org/v3-flatcontainer/polly/7.2.4/polly.7.2.4.nupkg
info : Installed Polly 7.2.4 from https://api.nuget.org/v3/index.json with content hash bw00Ck5sh6ekduDE3mnCo1ohzuad946uslCDEENu3091+6UKnBuKLo4e+yaNcCzXxOZCXWY2gV4a35+K1d4LDA==.
info : Package 'Polly' is compatible with all the specified frameworks in project 'F:\dotnet\test\test.csproj'.
info : PackageReference for package 'Polly' version '7.2.4' added to file 'F:\dotnet\test\test.csproj'.
info : Writing assets file to disk. Path: F:\dotnet\test\obj\project.assets.json
log  : Restored F:\dotnet\test\test.csproj (in 735 ms).

Restore succeeded.
NU3003 not found.
```

</details>

**Comment by dtivel** [comment]
@elina-zh, by default [`NU3003`](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3003) is a warning.  It can be elevated to an error (e.g.:  [`TreatWarningsAsErrors`](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022)).  Are you seeing a warning or an error?

If it's an error, adding a `NoWarn` for `NU3003` should enable you to ignore this issue until a fix is available.  The simplest way to do this is to add (or edit) [Directory.Build.props](https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022) in your solution's root directory:

```XML
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <NoWarn>$(NoWarn);NU3003</NoWarn>
    </PropertyGroup>
</Project>
```

**Comment by elina-zh** [comment]
> This might be related to [dotnet/sdk#33928](https://github.com/dotnet/sdk/issues/33928)
> 
> Does this reproduce on 6.0.411 or higher?
> 
> https://dotnet.microsoft.com/en-us/download/dotnet/6.0

No
