### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by nanderto** [NuGet/Home#1269]
I have set up a private feed for nuget on our TFS server, using the nuget server, package. This has been successfully running for some time, but now I need to move it to a new server. (TFS Consolidation)

On the new server I can use the settings to point to the new server. I can get the packages to show up in the UI, and in a list if I run nuget list -source <and provide source> but when I attempt to install a package I get an error 

Unable to connect to the remote server

from the command line I get:

Install-Package : Unable to connect to the remote serverAt line:1 char:1
- INstall-package BrXXXXXXXs.GlobalConstants -source  http://tfs.brXXXXXXXs.c ...
- ```
  ```
  - CategoryInfo          : NotSpecified: (:) [Install-Package], WebException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
  
  I have compared the 2 end points and I do not see what is different. I can access both thru a browser.

**Comment by yishaigalatzer** [comment]
It seems like you have a setup issue either in visual studio or the server.

I would start by comparing a fiddler trace between trying to connect to the old and the new server, and figure out what changed.

**Comment by yishaigalatzer** [comment]
ping, please give us more info, if we don't hear back we are going to close this as no-repro.

**Comment by yishaigalatzer** [comment]
Closing as we haven't heard back for over a month now
