### ISSUE TITLE
NuGet.PackageManagement: resolver should return correct resolution for updating Dependent package

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#127]
Repro step:
1. Install-Package jquery.validation -Version 1.8
2. Update-package jquery -version 2.0.3

Expected: jquery.validation was updated to 1.8.0.1

Actual: it was downgraded to 1.6.0. 

When resolving packages, resolver should also consider what's already installed on the projects, and the update directions (upgrade or downgrade).

**Comment by danliu** [comment]
From yesterday's run results using 3.0-rc VSIX, this issue still reproes.

**Comment by danliu** [comment]
with today's (4/1) build:

PM> Update-package jquery -version 2.0.3
Attempting to gather dependencies information for package 'jQuery.2.0.3' with respect to project targeting '.NETFramework, Version=v4.5'
Attempting to resolve dependencies for package 'jQuery.2.0.3' with DependencyBehavior 'Lowest'
Unable to satisfy package dependency constraints.

**Comment by emgarten** [comment]
Fixed with b51a225ae175fea1657d35fec753f80074226185
