### ISSUE TITLE
"dotnet list" fail on old csproj style when the project has zero package

### ISSUE THREAD

**Issue by vernou** [NuGet/Home#12702]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK : 7.0.304

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I want check the vulnerability from a project with the old csproj style that don't have package dependencies.

To reproduce :

1. Create a new project with Visual Studio with the template "**Console App (.NET Framework)**"
2. Build the project
3. Execute the command : 
```cmd
>dotnet list package --vulnerable --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json
   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

The project `C:\Projets\Vrac\ConsoleApp\ConsoleApp.csproj` uses package.config for NuGet packages, while the command works only with package reference projects.
```

---

Next, if we add and remove a package :

```PowerShell
Install-Package Newtonsoft.Json
Uninstall-Package Newtonsoft.Json
```

Then the command work :

```cmd
>dotnet list package --vulnerable --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json
   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

The given project `ConsoleApp44` has no vulnerable packages given the current sources.
```

Sound like the `Install-Package` generate `obj\project.assets.json` need by `dotnet list`.

**Comment by nkolev92** [comment]
dotnet.exe cannot resolve old style csproj.
Similar to https://github.com/NuGet/Home/issues/9747, this is by design.
