### ISSUE TITLE
Stop using JObject in assets file reading to reduce allocations

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#12715]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1817651

**Comment by nkolev92** [comment]
@kartheekp-ms did you mean to assign this to @heng-liu

**Comment by zivkan** [comment]
Whoever works on this, I **STRONGLY** recommend using System.Text.Json, not Newtonsoft.Json's JsonReader or JsonConverter. See the vulnerability file benchmarks: https://github.com/NuGet/Home/issues/12855

It'll have much bigger impact on reducing memory allocations, plus it's a little bit faster to run.  The amount of effort is similar regardless which is used, so it's better to go straight to the better solution, rather than require a second migration in the future.

**Comment by kartheekp-ms** [comment]
> @kartheekp-ms did you mean to assign this to @heng-liu

Sorry for the confusion, no I didn't mean to assign this to Heng.

**Comment by mungojam** [comment]
I'm not clear if this is related but I've been trying to write a NuGet plugin and found that the dependencies on Newtonsoft.Json when using types from `NuGet.Protocol.Plugins` namespaces was surprising and causing me extra work. It uses JObject for the message payload and it's not possible to deserialize messages into the Message type provided using System.Text.Json directly

**Comment by nkolev92** [comment]
@mungojam NuGet.Protocol.Plugins is one part of our SDK that could be moved to System.Text.Json when the time is right for it. 

I dug a little bit and I wasn't able to find which API you were referring to. 
Can you give us a code pointer? https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/Logging/PluginLogMessage.cs is internal, so if we moved to System.Text.Json the migration should be seamless.

**Comment by mungojam** [comment]
> @mungojam NuGet.Protocol.Plugins is one part of our SDK that could be moved to System.Text.Json when the time is right for it.
> 
> I dug a little bit and I wasn't able to find which API you were referring to. Can you give us a code pointer? https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/Logging/PluginLogMessage.cs is internal, so if we moved to System.Text.Json the migration should be seamless.

This was the one I hit first:

https://github.com/NuGet/NuGet.Client/blob/741f7d55477ebd3e2201a5d9e6a030daa25ec5f2/src/NuGet.Core/NuGet.Protocol/Plugins/Messages/Message.cs#L34-L37

**Comment by nkolev92** [comment]
Thanks. 
awww, that's unfortunate :(

**Comment by mungojam** [comment]
> Thanks. awww, that's unfortunate :(

If there was a (documented) higher level API I could use for creating the plugin, then I wouldn't need a direct dependency on Message. Something where we could just pass in handlers for different types of message or something and it would handle console.out etc. It might even be there in the library already, but just not documented

**Comment by nkolev92** [comment]
I think Message is widely used in the infrastructure. My initial instinct is that only the infra uses it and you shouldn't need to reference it directly, but I haven't looked into that in a while. 
https://github.com/microsoft/artifacts-credprovider is an example of plugin, so you check whether they do anything different.

On the other hand, we'd still be able to eventually move from NJ to STJ if we need to, it'd just need be a breaking change in the SDK. 
However, I don't think that'll cause issues for plugins. 
The plugins communicates to NuGet via STDIN/STDOUT and serialized json payload, so how whether the serialization happens with STJ or NJ, it shouldn't matter as long it's equivalent. 
I think an updated NuGet that serializes with STJ will work.

**Comment by mungojam** [comment]
> https://github.com/microsoft/artifacts-credprovider is an example of plugin, so you check whether they do anything different.

I have been referring to that a bit, but it's quite a complex beast, with lots of abstraction that makes it hard to decipher the basics from it. I did however see that it was using Message which is where I got the idea to use it. So it's using the same basic approach as I was trying and it will also have a JSON.net dependency in it.

Very off topic now but the docs for nuget plugin creation are so vague I have found. They would benefit from explicit protocol examples and a basic code example that did things in a rudimentary way. Even with working serialisation using the Message type I haven't yet managed to complete a handshake and get a second request from nuget. I'll keep trying but may end up having to reverse engineer that azure credential library or the nuget plugin protocol library some more to figure out where I'm going wrong.

**Comment by mungojam** [comment]
I've now discovered `PluginFactory.CreateFromCurrentProcessAsync` in the NuGet.Protocol package, which is exactly the high level API I was looking for. It's the one that the AWS Code Artifact helper uses and it looks very simple and hides the Json.net aspect so I'm happy with that for my uses.

**Comment by zivkan** [comment]
If you make your cred provider public, please consider posting a link in https://github.com/NuGet/Home/issues/12567, so that when we eventually implement that feature request, we can contact you to let you know how to update it to be installable via the new way (and/or consider subscribing to the issue, to get notifications when it updates)
