### ISSUE TITLE
NuGet extension in VS cannot find dotnet PCL libraries on MyGet

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#1271]
I have a few dotnet PCL libraries I push to MyGet. When I use them in a local directory, the package manager finds them and things work great. However, it cannot find them when I point it to MyGet. Is this an issue with NuGet or MyGet?

**Comment by yishaigalatzer** [comment]
If the packages work locally, it is probably an issue with myget or your setup, I would talk to @maartenba 

Closing for now. If @maartenba tracks it to nuget, we can revisit.

**Comment by maartenba** [comment]
This may be because of [target framework filtering](http://blog.nuget.org/20141001/targetframeworkfiltering.html). Can you contact support at myget org and provide us with the package + describe the consuming project type?
