### ISSUE TITLE
Nuget restore / Nuget list configured with client-cert keeps prompts for credentials in Mac and Linux Platform

### ISSUE THREAD

**Issue by OMPRAKKASH** [NuGet/Home#12726]
### NuGet Product Used

NuGet.exe

### Product Version

6.6.1.2

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Nuget configured with a client certificate for the private repository, it repeatedly prompts for credentials when nuget restore / nuget list command is executed from Mac or Linux platforms and returns '`401 Missing client certificate!`'  when `-NonInteractive` flag is used / manual user credentials are provided. On the Windows platform, it works fine with the same endpoint, credentials, and configuration.

**Commands used to configure Nuget:**

```
nuget client-certs Add -PackageSource artifactory -Path ClientCertificate.pfx -Password CertPwd -StorePasswordInClearText -ForceEnglishOutput

nuget sources Add -Name artifactory -Source https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote -username ArtifactoryUsername -password ArtifactoryPassword -StorePasswordInClearText -ForceEnglishOutput -NonInteractive -ValidAuthenticationTypes basic

nuget list JSONTranslator -Source artifactory -Verbosity detailed 
```

We receive the following credential prompts, and if no user input is provided within a certain timeout period, it fails.

```
NuGet Version: 6.6.1.2
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Using credentials from config. UserName: ***
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote
UserName: Unable to load the service index for source https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote.
  The HTTP request to 'GET https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote' has timed out after 100000ms.
```

If valid user credentials are provided for all attempts it still return 401 error : 

`Mob-OSX-Builder-04:~ mobosxbuilder$ nuget list JSONTranslator -Source EEC-artifactory -Verbosity detailed
NuGet Version: 6.6.1.2
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Using credentials from config. UserName: damo-artif-svc
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Unable to load the service index for source https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote.
  Response status code does not indicate success: 401 (Missing client certificate!).
`

With same config when nuget is configured with `-NonInteractive` flag it results in same "`401 Missing client certificate!'.`"

```
NuGet Version: 6.6.1.2
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Using credentials from config. UserName: ***
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/$metadata
  Unauthorized https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/$metadata 64ms
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
  Unauthorized https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 63ms
The V2 feed at 'https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0' returned an unexpected status code '401 Missing client certificate!'.
NuGet.Protocol.Core.Types.FatalProtocolException: The V2 feed at 'https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0' returned an unexpected status code '401 Missing client certificate!'.

```
Expected Solution :

It is expected to work the same way as on the Windows platform, ensuring that the client certificate, client certificate path, username, and password are all the same.

```
NuGet Version: 6.6.1.2
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/$metadata
  OK https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/$metadata 76ms
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
  OK https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='JSONTranslator'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 595ms
JSONTranslator
 3.0.0.1
 This is a .Net Core 2 console application that accepts a JSON file, calls the Microsoft Text Translator API in Azure and writes translated files to disk.
 License url: https://github.com/swernimo/translator/blob/master/LICENSE
```

**Comment by OMPRAKKASH** [comment]
Additional Info:

The output below shows the results of `nuget source` and `nuget client-certs` before executing `nuget restore/nuget client`

```
Registered Sources:
  1.  nuget.org [Disabled]
      https://api.nuget.org/v3/index.json
  2.  artifactory [Enabled]
      https://artifactory-mtls.xyz.com/artifactory/api/nuget/nuget-remote
Registered client certificates:

 1.   artifactory [fileCert]
      File path: /home/vsts/work/1/s/ClientCertificate.pfx
      Password: ****
      Certificate: C301234XYZXYZXYZC079
```
For the same source server endpoint and with the same credentials, without a client certificate (mTLS), it works as expected in all platforms (Linux, Mac, and Windows). Therefore, I believe there is likely a bug specific to certain behavior that is being handled differently in Mac and Linux.

**Comment by donnie-msft** [comment]
Where is the source defined you're using here:  `-Source EEC-artifactory` ?
It doesn't match the source name here: `nuget client-certs Add -PackageSource artifactory `

**Comment by OMPRAKKASH** [comment]
That output was generated from different custom source names (only name) on different client machines. Even if we provide the same source name and ensure that it picks up the pre-configured configuration, the issue remains the same.

```
Mob-OSX-Builder-04:~ mobosxbuilder$ nuget list JSONTranslator -Source artifactory -Verbosity detailed
NuGet Version: 6.6.1.2
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Please provide credentials for: https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote
UserName: damo-artif-svc
Password: *************************************************************************
Unable to load the service index for source https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote.
  Response status code does not indicate success: 401 (Missing client certificate!).
NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://artifactory-mtls.xyz.com/artifactory/api/nuget/v3/nuget-remote. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Missing client certificate!).
```

**Comment by erdembayar** [comment]
Thank you for filing this issue.
Unfortunately, this feature is not documented, here is tracking issue https://github.com/NuGet/Home/issues/13485

Could you tell me if you installed `mono runtime` for Mac/Linux? Because nuget.exe relies on mono runtime for those OSs.

Alternative could be `dotnet nuget add client-cert`, again unfortunately it's also not documented too, at least you can see description of options.
![image](https://github.com/NuGet/Home/assets/8766776/228bf075-fd87-48f8-8318-430896120939)

Please let me know if you above helps.

**Comment by OMPRAKKASH** [comment]
Yes, `mono runtime` is already installed, but issue still exist. 

![image](https://github.com/NuGet/Home/assets/20636655/a9c2aac1-addf-401d-82e3-0fc6b4e4fa55)

**Comment by erdembayar** [comment]
> Yes, `mono runtime` is already installed, but issue still exist.
> 
> ![image](https://user-images.githubusercontent.com/20636655/252502621-a9c2aac1-addf-401d-82e3-0fc6b4e4fa55.png)

Have you tried this yet? `dotnet nuget add client-cert`

**Comment by OMPRAKKASH** [comment]
Yes, I used `dotnet nuget add client-cert` and used the dotnet config file to execute the command `nuget list JSONTranslator -Source artifactory -Verbosity detailed -config ..\dotnet\Nuget.config` but still same results

**Comment by zivkan** [comment]
@OMPRAKKASH I just noticed it seems you're using pfx certificates.

Even though OpenSSL knows how to convert `pfx` certs to `pem` format, for some reason these pfx certificates can't be loaded on Mac or Linux through .NET's APIs (I don't know if it's possible to from its original C API, I guess so since it's possible to convert the file).

I'm surprised reading the certificate doesn't throw an exception if the file format isn't supported: https://github.com/NuGet/NuGet.Client/blob/4187eab2d176d6fccb6f0cfc45fc71fd2e750708/src/NuGet.Core/NuGet.Configuration/Settings/Items/FileClientCertItem.cs#L163

Someone would need to debug to see if NuGet can even detect that the certificate instance isn't going to work, rather than `HttpClient` silently ignoring the certificate.

Anyway, you should be able to resolve the problem by converting the pfx certificate to something that works on Linux & Mac. a quick search for "openssl convert pfx" finds plenty of examples.

**Comment by OMPRAKKASH** [comment]
@zivkan  Unfortunately, even after converting the PFX into PEM and importing it into NuGet, the same issue still persists.

![image](https://github.com/NuGet/Home/assets/20636655/dd1dcf4c-0fa6-4e5a-82cc-ddf3711158ef)

**Comment by zivkan** [comment]
Could you try a simple console app using HttpClient, to help understand if it's a NuGet issue, or a .NET HttpClient issue?  Setting up a web server that accepts client certificates is non-trivial, so if you already have one to test with, it can save a lot of time.

Typing from memory, so it probably needs fixes:

```csharp
string certificatePath = args[0];
string certPassword = Environment.GetEnvironmentVariable("CERT_PASSWORD");
var certificate =
  string.IsNullOrEmpty(certPassword)
  ? new X509Certificate(certifictePath)
  : new X509Certificate(certificatePath, certPassword);

// in case server needs HTTP Basic auth in addition to the client cert
string basicUsername= Encironment.GetEnvironmentVariable("BASIC_USERNAME");
string basicPassword = Environemtn.GetEnvironmentVariable("BASIC_PASSWORD");
NetworkCredential? credential =
  string.IsNullOrEmpty(basicUsername) && string.IsNullOrEmpty(basicPassword);

HttpClientHandler handler = new();
handler.ClientCertificates.Add(certificate);
handler.Credentials = credential;

using var client = new HttpClient(handler);

for (int i = 0; i < 5; i++)
{
  if (i != 0)
  {
    await Task.Delay(TimeSpan.FromSeconds(5));
  }
  using var response = await client.GetAsync(arg[1]);
  Console.WriteLine($"Request {i} response code: {response.StatusCode}");
}
```

**Comment by OMPRAKKASH** [comment]
@zivkan  We have the client certificate and the test Artifactory to reproduce this scenario. Please let me know how you would like to receive the credentials and certificate details.

**Comment by erdembayar** [comment]
> @zivkan We have the client certificate and the test Artifactory to reproduce this scenario. Please let me know how you would like to receive the credentials and certificate details.

Do you have the pfx file for the certificate ready? If so, pass it as arg[0] to the console app. This file should come with its own `CERT_PASSWORD` password, so set it as the value for the `CERT_PASSWORD` environment variable.

For `BASIC_USERNAME` and `BASIC_USERNAME`, make sure you manually create user on the server and then set them as environment variables on your local machine. 

Does that answer your question?

**Comment by OMPRAKKASH** [comment]
@erdembayar  and @zivkan  Yes, I used the console script below that utilizes HttpClient to validate the scenario. The authentication process returned a successful response.

```using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

namespace HttpClientAuthenticationTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            if (args.Length < 4)
            {
                Console.WriteLine("Usage: HttpClientAuthenticationTest <username> <password> <certificatePath> <certificatePassword>");
                return;
            }

            string username = args[0];
            string password = args[1];
            string certificatePath = args[2];
            string certificatePassword = args[3];

            string targetUrl = "https://artifactory-mtls.digitalaviationservices.com";

            HttpClientHandler handler = new HttpClientHandler();

            X509Certificate2 certificate = new X509Certificate2(certificatePath, certificatePassword);
            handler.ClientCertificates.Add(certificate);
            handler.Credentials = new System.Net.NetworkCredential(username, password);

            using (HttpClient client = new HttpClient(handler))
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                try
                {
                    HttpResponseMessage response = await client.GetAsync(targetUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        string responseContent = await response.Content.ReadAsStringAsync();
                        Console.WriteLine("Authentication successful!");
                        Console.WriteLine("Response content:");
                        Console.WriteLine(responseContent);
                    }
                    else
                    {
                        Console.WriteLine("Authentication failed. Status code: " + response.StatusCode);
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("An error occurred: " + ex.ToString());
                }
            }

            Console.WriteLine("Press any key to exit.");
            Console.ReadKey();
        }
    }
}
```

Response :

![image](https://github.com/NuGet/Home/assets/20636655/c8b99866-50e8-49d3-96a3-009257eb6001)

**Comment by OMPRAKKASH** [comment]
Based on previous results, I could confirm it is issue specific to Nuget in Mac / Linux platform. Can anyone please provide any further background of this issue ?

**Comment by zivkan** [comment]
Background?  I don't remember any work on the feature since it was contributed by a community member, so conveniently, we can look at a single commit to easily see all the related code: https://github.com/NuGet/NuGet.Client/commit/788bc01a1b063a37841cdd6d035feb320e90e475

Reading a certificate from a file: https://github.com/NuGet/NuGet.Client/commit/788bc01a1b063a37841cdd6d035feb320e90e475#diff-478b97ebb510a8436d9653d627db4c6a69f911b0c7183463283811cb5d6125e7R153-R160

also: https://github.com/NuGet/NuGet.Client/commit/788bc01a1b063a37841cdd6d035feb320e90e475#diff-93482a8631efd30f5df833baa903bcf342fb99a2e93cf9a3dea6a672b44d3a61R193-R197

setting the certificate(s) on the `HttpClientHandler`: https://github.com/NuGet/NuGet.Client/commit/788bc01a1b063a37841cdd6d035feb320e90e475#diff-4e1193a4ff524ae74ffa1582bc80ed615cb7e0cc38dcd1cf74288ebadd7723f6R52-R54

Only now it occurs to me that maybe you're running nuget.exe on Mac/Linux, which would mean you'd be using Mono.  Did you run the test app on Mono as well, or did you use the `dotnet` CLI?  Please make sure you're using the same runtime.

Otherwise, I can't guess why NuGet would behave differently to the test app. If the path to the certificate file was wrong, `X509Certificate`'s constructor would throw an exception. If the nuget.config settings were wrong (for example a type in one of the XML element names), NuGet will silently ignore the unknown settings, but you said it works on Windows. Therefore, looking at the code, I'm confident that the client certificate is being passed to the `HttpClientHandler`, at which point it's the runtime's responsibility.
