### ISSUE TITLE
The version doesn’t display the “(Deprecated)” or “(Vulnerable)” label in version box when typing a deprecated or vulnerable package version in the “version” drop-down box 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12725]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Private Dev\6.8.0.14

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Create a C# Console App (.Net core) project.    
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.                                         
3. Go to "Browse" tab and click a package (for example “NuGet.Core” or "Newtonsoft.Json").   
4. Click the "Version" drop-down box in the right panel.  
5. Type a version (for example “2.14.0” for package “NuGet.Core” or "12.0.1" for package "Newtonsoft.Json") which already exists in the list and press the "Enter key". 

#### Expected:     

The version will display “(Deprecated)” or “(Vulnerable)” label in version box. 

#### Actual:     

The version doesn’t display the “(Deprecated)” or “(Vulnerable)” label as below： 
![screenshot2](https://github.com/NuGet/Home/assets/84695155/a94e8e45-1228-4724-9eaa-1dfef32a3a89)

#### Note:    
1. The repro rate is 100%.     
2. This is not a regression since it is a new feature change.

**Comment by donnie-msft** [comment]
@martinrrm could you help me triage this one? Thank you
