### ISSUE TITLE
Are you sure you are running the latest version of code-server?

### ISSUE THREAD

**Issue by KnighOfR** [NuGet/Home#12720]
Are you sure you are running the latest version of code-server? 
The latest version (4.14.0) packages Code 1.79.2, not 1.66.2.  You 
can run `code-server --version` or use Help > About from the menu 
to check.

_Originally posted by @code-asher in https://github.com/coder/code-server/issues/6279- - [ ] #issuecomment-1601319953

**Comment by kartheekp-ms** [comment]
I believe this issue has been created in the incorrect GitHub repository, so I am closing it. Based on the comments in the linked issue, it appears to be unrelated to the NuGet Client. If my understanding is incorrect, please provide clear reproducible steps that demonstrate how it is connected to the NuGet Client functionality in Visual Studio, dotnet.exe, NuGet.exe, or msbuild.exe. This will allow us to investigate further.
