### ISSUE TITLE
NuGetAuditMode all warns about package versions that were upgraded (rejected)

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12730]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

6.7

### Worked before?

no, new feature

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Consider the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Packaging" Version="5.11.5" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="5.0.1" />
  </ItemGroup>

</Project>
```

This results in two warnings about two different versions of Newtonsoft.Json:

> D:\src\test\vulnBug\vulnBug.csproj : warning NU1902: Package 'Newtonsoft.Json' 9.0.1 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr
> D:\src\test\vulnBug\vulnBug.csproj : warning NU1902: Package 'Newtonsoft.Json' 12.0.2 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr

The package `NuGet.Packaging` has a dependency on `Newtonsoft.Json` 9.0.1, whereas `Microsoft.AspNetCore.JsonPatch` has a dependency on version `12.0.2`. If you upgrade either package to a newer version, that has a dependency on a no longer vulnerable version of `Newtonsoft.Json`, NU1902 will still since there's a part of the restore graph that rejected the lower version of Newtonsoft.Json.

**Comment by cremor** [comment]
@zivkan Which version will include the fix for this issue?

I ask because I have a problem with `<NuGetAuditMode>all</NuGetAuditMode>` that might be the same as this issue. My .NET SDK version is 7.0.400 and `dotnet nuget --version` prints 6.7.0.111.

**Comment by zivkan** [comment]
@cremor it's fixed in .NET 8 previews. Unfortunately NuGetAudit had some dumb bugs in 7.0.400 that I didn't catch in time to fix, so we're considering NuGetAudit broken in 7.0.400 (the feature was disabled in VS 17.7. I don't know why we didn't remove it from 7.0.400 as well)

**Comment by cremor** [comment]
I see, thanks for the quick response!

Will those bugs be fixed in a future .NET 7 SDK or only in .NET 8?

**Comment by cremor** [comment]
Also, do you consider the whole NuGetAudit broken in .NET 7, or just `<NuGetAuditMode>all</NuGetAuditMode>`? So would it be fine to use `<NuGetAuditMode>direct</NuGetAuditMode>`?

**Comment by zivkan** [comment]
The whole NuGetAudit is considered broken in .NET 7. 😭 Two major bugs (this is one), where the fixes had too many code changes to get approved to fix in 7.0.4xx.

Actually, [we did insert into the .NET SDK's 7.0.4xx branch](https://github.com/dotnet/sdk/blob/95c088db4433ef5b6b4083ee376d2c6ce8d7c795/eng/Versions.props#L68) ([nuget build 6.7.0.127](https://github.com/NuGet/NuGet.Client/commits/6.7.0.127) disables NuGetAudit completly), but we did so too late to make 7.0.400, so NugetAudit will stop working as soon as 7.0.401 ships.

NuGetAudit will work again in 8.0.100, and without this bug (hopefully without any other major bugs either!)

**Comment by Corniel** [comment]
Is it also broken for .NET 6?

**Comment by zivkan** [comment]
It's a brand new feature, so it never existed in the .NET 6 SDK.

In case you're talking about projects targeting .NET 6, the .NET SDK (compiler and build tools) can target any runtime version equal to, or lower, than the runtime version. So, you can use the .NET 7 or .NET 8 SDK to build your project that targets `net6.0`. NuGetAudit (checking packages for known vulnerabilities) only exists in the .NET 8 SDK (and above), regardless of which TargetFramework your project uses.
