### ISSUE TITLE
RemoteDependencyWalker allocates a lot due to the fact that it's called recursively

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#12748]
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1825512

**Comment by jeffkl** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/12748

**Comment by zivkan** [comment]
@jeffkl this issue is closed in favour of itself? 🤣

**Comment by jeffkl** [comment]
Closing instead as "fixed" buy several pull requests and https://github.com/NuGet/Home/issues/13222
