### ISSUE TITLE
[Bug Bash] No warning info shows when adding a package pattern with a long string which is more than maximum length characters in the “Add New Package Source Mapping” dialog

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12742]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.8.0.22

### Impact

None

### Repro Steps & Context

VS Version: Main\33912.166
NuGet Version: Dev\6.8.0.22
OS Version: Windows-11-Enterprise-22H2 ENU
#### Repro Steps:
1.	Open VS, click menu File->New Project, create a Console App (.Net Core) project.
2.	Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3.	Click the “settings” button on the right panel and click “Package Source Mapping” tab.
4.	Click “Add” button and type a long string which is more than maximum length characters.
#### Expected:
There should be a warning info to tell user the maximum length of the string.
#### Actual:
No warning info shows as below.
![image](https://github.com/NuGet/Home/assets/20632625/dfe330c0-b50d-489f-a799-27578ffc3343)
#### Notes:
It is not a regression since it is a new feature.

**Comment by erdembayar** [comment]
I can repro this issue, it doesn't accept any text more than 100 chars, it just cut off at 100. It doesn't inform about limit already reached when someone try to paster string more than 100 chars or type after 100 chars.

**Comment by donnie-msft** [comment]
@erdembayar you say you can repro but then you say it cuts off at 100. The expectation is it should cut off at 100. What do you mean by repro? Are you able to enter more than 100 characters by any means, and if so, can you describe how?

I tried a few ways to type and paste from clipboard, and I couldn't get more than 100 characters into the textbox. For me, it is no repro.

**Comment by jebriede** [comment]
Team triage: We were able to verify that the character limit of 100 characters is working for the textbox. Any additional characters added after 100 are not added to the text, as expected. We have other textboxes in VS, especially in the Tools -> Options dialog that work the same way. For example, the Tools -> Options -> NuGet Package Manager -> Package Sources page has a Name textbox that has a limit of approximately 37k characters, but once the end is reached, there is no warning that appears so the package source mapping options page is consistent with that design.

/cc: @donnie-msft as FYI
