### ISSUE TITLE
NUGET_PACKAGES, NUGET_HTTP_CACHE_PATH, NUGET_SCRATCH and NUGET_PLUGINS_CACHE_PATH not working

### ISSUE THREAD

**Issue by israelvaldez** [NuGet/Home#12756]
### NuGet Product Used

Other/NA

### Product Version

17.3.1

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Install the nuget package Microsoft.Build version 17.3.1
Load a csproj using an instance of Microsoft.Build.Evaluation.Project
Run the method Build of the instance
We get the following exception:
```
Project "C:\EpicorData\Users\epicor\UD\Source\Shared\Contracts\UD\CPQOrderDtl_c\Erp.Contracts.UD.CPQOrderDtl_c.csproj" (default targets):

C:\Program Files\dotnet\sdk\6.0.405\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file 'C:\EpicorData\Users\epicor\UD\Source\Shared\Contracts\UD\CPQOrderDtl_c\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
Done building project "Erp.Contracts.UD.CPQOrderDtl_c.csproj" -- FAILED.
```
This runs on an IIS App pool that runs using the user Network Service, that runs in a Windows container running with the security context of a gMSA.
If we change the IIS App pool to run using the System user, we're able to build the project.
We're also able to build the project if we give the Network Service user access to the app data directory of the System user which is c:\windows\system32\config\systemprofile

We're trying to get away from giving the Network service access to the system user app data directory and instead rely on the NUGET_* environment variables in order to redirect temporary files into a folder that we already gave the Network service user access to.
What we did to give the Network service user visibility over the NUGET_* environment variables was to set the environment variables of the Network Service SID via a registry change.
```
New-PSDrive HKU Registry HKEY_USERS
New-ItemProperty -Path "HKU:\S-1-5-20\Environment" -Name "NUGET_PACKAGES" -Value "C:/storage/nuget-packages" -PropertyType String -Force
New-ItemProperty -Path "HKU:\S-1-5-20\Environment" -Name "NUGET_HTTP_CACHE_PATH" -Value "C:/storage/nuget-http-cache" -PropertyType String -Force
New-ItemProperty -Path "HKU:\S-1-5-20\Environment" -Name "NUGET_SCRATCH" -Value "C:/storage/nuget-scratch" -PropertyType String -Force
New-ItemProperty -Path "HKU:\S-1-5-20\Environment" -Name "NUGET_PLUGINS_CACHE_PATH" -Value "C:/storage/nuget-plugins-cache" -PropertyType String -Force
```

**Comment by zivkan** [comment]
@israelvaldez last year another customer found they had to configure their app to enable environment variables: https://github.com/NuGet/Home/issues/11762#issuecomment-1114540340

Have you done that?

**Comment by israelvaldez** [comment]
@zivkan haven't really tried that, I'll report back what I find. Thanks for your quick response.

**Comment by israelvaldez** [comment]
@zivkan that did the trick. After I set those two settings up (loadUserProfile and setProfileEnvironment) the IIS App Pool can write into the Network Service appdata directories (C:\windows\ServiceProfiles\NetworkService\AppData).

I used the below scripts to set the IIS settings programatically, hopefully they'll be useful for somebody later.
```
	Start-Process -FilePath "$($env:windir)\system32\inetsrv\appcmd.exe" `
        -ArgumentList @(
            "set AppPool Server",
            "-processModel.loadUserProfile:true"
        ) -Wait
		
	Start-Process -FilePath "$($env:windir)\system32\inetsrv\appcmd.exe" `
        -ArgumentList @(
            "set AppPool Server",
            "-processModel.setProfileEnvironment:true"
        ) -Wait
```
