### ISSUE TITLE
NuGet doesn't restore RID-specific assets for Microsoft.DotNet.ILCompiler

### ISSUE THREAD

**Issue by sbomer** [NuGet/Home#12757]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.100-preview.7.23361.25

### Worked before?

8.0.100-preview.7.23361.20

### Impact

I'm unable to use this version

### Repro Steps & Context

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Dotnet.ILCompiler"
                      Version="8.0.0-preview.6.23316.3" />
  </ItemGroup>

</Project>
```

Run a RID-specific restore operation, for example `dotnet restore -r linux-x64`. Observe that `project.assets.json` doesn't contain an entry for `runtime.linux-x64.microsoft.dotnet.ilcompiler`. This was working previously.

I tracked this down to the following SDK update: https://github.com/dotnet/sdk/pull/33913, and narrowed it down a bit more to the nuget commit range https://github.com/nuget/nuget.client/compare/13f2b6af6e...ba16cb02 by building SDK with different nuget package versions.

This is blocking AOT compilation for .NET (see https://github.com/dotnet/runtime/issues/89040).

**Comment by sbomer** [comment]
@drewnoakes would you be able to take a look? I had trouble building .nupkgs for NuGet.Client locally so I couldn't narrow it down to a more specific change.

**Comment by drewnoakes** [comment]
Thanks for the analysis @sbomer. I'm not intimate with building the NuGet repo for external consumption. My recent PRs in this repo have been targeted performance changes as part of a cross-org perfathon in June.

I asked @zivkan about building packages and he suggests that, on Windows, `.\build.ps1 -fast -SkipUnitTest` will build NuGet and the nupkgs. Are you set up to be able to bisect the commits in range https://github.com/NuGet/NuGet.Client/compare/13f2b6af6e...ba16cb02 to help narrow down to a specific commit? If we can blame a specific PR it'll help considerably.

**Comment by sbomer** [comment]
Thanks @drewnoakes for the help. I was able to bisect it down to https://github.com/NuGet/NuGet.Client/pull/5248. Specifically, the problem is that the change introduced case sensitivity here: https://github.com/NuGet/NuGet.Client/pull/5248#discussion_r1268550523.

**Comment by drewnoakes** [comment]
Thanks very much Sven. I'll get a fix in today.

**Comment by drewnoakes** [comment]
FYI @davkean who is tracking regressions from the Perfathon.

**Comment by drewnoakes** [comment]
A fix is available in https://github.com/NuGet/NuGet.Client/pull/5321.
