### ISSUE TITLE
Nuget restore fails  with Error NU3003: The package signature is invalid or cannot be verified on this platform.

### ISSUE THREAD

**Issue by MaddyDev** [NuGet/Home#12760]
### NuGet Product Used

dotnet.exe

### Product Version

MSBuild version = "17.2.0+41abc5629"

### Worked before?

worked with xunit 2.4.2

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Updated the xunit package from 2.4.2 to the latest 2.5.0 (https://www.nuget.org/packages/xunit.core/2.5.0)
2. Queued a new build on our pipeline and nuget restore fails with the below error on windows only, restore is successful on mac and linux: error NU3003: Package 'xunit.runner.visualstudio 2.5.0' from source 'https://api.nuget.org/v3/index.json': The package signature is invalid or cannot be verified on this platform.
3. Below id the ado results with verbose logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206872&view=logs&j=b2ceb7fa-76eb-5e2f-7afb-5c7fcf0ef065&t=e83f30b7-a2bb-5f3b-7eb9-2f82380d0d78

### Verbose Logs

```shell
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206872&view=logs&j=b2ceb7fa-76eb-5e2f-7afb-5c7fcf0ef065&t=e83f30b7-a2bb-5f3b-7eb9-2f82380d0d78&l=5
```

**Comment by JonDouglas** [comment]
@MaddyDev Can you include the dotnet version here? Such as `dotnet --info` or similar? Does this reproduce on 6.0.411+?

**Comment by JonDouglas** [comment]
Looks related to https://github.com/dotnet/sdk/issues/33928

**Comment by MaddyDev** [comment]
> @MaddyDev Can you include the dotnet version here? Such as `dotnet --info` or similar? Does this reproduce on 6.0.411+?

We are using: SDK Version: 6.0.300 and .Net 2.221

**Comment by jebriede** [comment]
@MaddyDev have you had a chance to confirm that this doesn't repro with the SDK version 6.0.411 or later? Thanks!

**Comment by MaddyDev** [comment]
> @MaddyDev have you had a chance to confirm that this doesn't repro with the SDK version 6.0.411 or later? Thanks!

Cannot repro it with 6.0.411 version.

**Comment by donnie-msft** [comment]
HI @MaddyDev, 
Please take a look at this workaround and follow this issue for any future guidance: https://github.com/dotnet/sdk/issues/33928#issuecomment-1644507852
Thank you!
