### ISSUE TITLE
Disabling nuget.org in VS options creates a second nuget.org in nuget.config

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12776]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.8 preview 1

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

From an internal email:

1.	Launch VS 17.8 preview 1 and Simulate offline in VM by uncheck all the package sources and click “OK” in VS.
 
    ![image](https://github.com/NuGet/Home/assets/5030577/a713f81b-86d4-4056-9262-da3d1aaee358)

2.	After step1,  extra feed will be added in NuGet.Config file.

    ![image](https://github.com/NuGet/Home/assets/5030577/3a79ef98-30e7-4c45-8552-f94bdae8aa1c)

**Comment by jebriede** [comment]
Team triage: Increasing priority to P1 since the behavior of adding a second entry after saving in the Tools -> Options dialog seems to be a regression in this version. This does not repro in 17.6 and 17.7.
