### ISSUE TITLE
GatewaysOperationsExtensions.GetDatasourceUsersAsync Method  always returns DatasourceUserAccessRight.Read 

### ISSUE THREAD

**Issue by VladPetrov-Quest** [NuGet/Home#12773]
### NuGet Product Used

NuGet SDK

### Product Version

Microsoft.PowerBI.Api 4.15.0 

### Worked before?

i dont know

### Impact

It's more difficult to complete my work

### Repro Steps & Context

GatewaysOperationsExtensions.GetDatasourceUsersAsync Method  always returns DatasourceUserAccessRight.Read, no matter what access right is configured on UI. 

1. Configure "Owner" access right for Gateway Connection: 
![image](https://github.com/NuGet/Home/assets/140498067/1bb75ad0-2e6f-4caf-a187-77b8512482c3)

2. Fetch users using GetDatasourceUsersAsync method
3. DatasourceUserAccessRight is returned as "Read"

**Expected:** 
DatasourceUserAccessRight.ReadOverrideEffectiveIdentity should be returned 

Similar problem I observed with writing method, it only add users with "Read" role, no matter of the input.

**Comment by martinrrm** [comment]
Thanks for filling this issue! Unfortunately, this doesn't look like a NuGet related bug, I suggest opening a bug to the package owner of Microsoft.PowerBI.Api.
