### ISSUE TITLE
nuget versioning is three part but $version$ replacement token applies four part

### ISSUE THREAD

**Issue by myusrn** [NuGet/Home#1277]
The nuget versioning story [ http://docs.nuget.org/Create/Versioning ] uses three part major.minor.patch approach and when you set nuspec <version>$version$</version> setting to leverage a .net framework project's Properties\AssemblyInfo.cs | [assembly: AssemblyVersion("1.0.0.0")] attribute setting it applies a four part major.minor.build.revision story to package output.

Shouldn't processing of the $version$ replacement token automatically drop the fourth part from that .net framework assembly version setting or provide some alternate version of that replacement token that supports doing that, e.g. $version2semver$ ?

**Comment by emgarten** [comment]
Use AssemblyInformationalVersion with your semantic version.

**Comment by myusrn** [comment]
Thanks for pointer that addressed the issue.  

I see now in http://docs.nuget.org/Create/Nuspec-Reference the $version$ info stating "The assembly version as specified in the assembly’s AssemblyVersionAttribute. If the assembly’s AssemblyInformationalVersionAttribute is specified, that one is used instead." vs the old http://blog.davidebbo.com/2011/04/easy-way-to-publish-nuget-packages-with.html article i'd been following suggesting it was driven only by AssemblyVersionAttribute setting.
