### ISSUE TITLE
Opt-out of "HTTPs everywhere" : add an allowInsecureConnections property in NuGet.Config

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#12786]
We need to add an `allowInsecureConnections` property into `packageSources` section in NuGet.Config files, as below:
```
<!-- Allows insecure connections on a specific http source -->
<packageSources>
    <add key="Contoso" value="http://contoso.com/packages/" allowInsecureConnections="true" />
</packageSources>
```
Spec: https://github.com/NuGet/Home/blob/dev/proposed/2023/InsecureConnectionsDisableCertificateValidation.md#package-source-nuget-config

**Comment by 0xced** [comment]
Along with this change I think a new `--allowInsecureConnections` option should be added to the `dotnet nuget add source` command.

```sh
dotnet nuget add source http://contoso.com/packages/ --name Contoso --allowInsecureConnections
```

should add the following source in the NuGet.config file:

```xml
<add key="Contoso" value="http://contoso.com/packages/" allowInsecureConnections="true" />
```

**Comment by kaatula** [comment]
> Along with this change I think a new `--allowInsecureConnections` option should be added to the `dotnet nuget add source` command.
> 
> ```shell
> dotnet nuget add source http://contoso.com/packages/ --name Contoso --allowInsecureConnections
> ```

Has the team considered this suggestion?

I need this command-line argument for my docker build pipeline.

**Comment by yadickson** [comment]
Hello

Maybe also add this options for the next command line:

`nuget setapikey xxx -source http://yyy/repository --allowInsecureConnections`

Best regards

**Comment by dca00** [comment]
Even after I add 

`allowInsecureConnections="true"`

to the source, I still get

> You are running the 'push' operation with an 'HTTP' source: http://192.68.1.1/nuget/api/v2/package.
> NuGet requires HTTPS sources. To use an HTTP source, you must explicitly set 'allowInsecureConnections'
> to true in your NuGet.Config file. Refer to https://aka.ms/nuget-https-everywhere for more information.

You likely have many different Nuget.config locations, and we have no way of knowing from which you load the config at run time.

So you are not only control freaks, you are also incompetent as developers. Someone should put an end to your bizarre circus and keep you in line. Learn to test your software for a change.

**Comment by flier268** [comment]
```bash
dotnet nuget add source http://yyy/repository --allow-insecure-connections
```

**Comment by alexsajno** [comment]
We maintain a large number of projects with CI pipelines across our organization, and manually adding allowInsecureConnections to each nuget.config file is not so simple, as we have hundreds of them.

It would be very helpful if the .NET SDK provided a command-line flag (for example, --allow-insecure-connections) for dotnet build and dotnet publish, or alternatively a machine-level configuration option to control this behavior globally. This would simplify CI/CD configuration and make adoption much smoother in enterprise environments.

It is important for us to have backward compatibility for old projects compiled with previous .NET versions using the new .NET 10 SDK.

@heng-liu

**Comment by jeffkl** [comment]
@alexsajno this can be done programmatically with the `dotnet nuget update source` command

If all of your nuget.configs refer to a feed with the same name, you can place this in your CI:

```
dotnet nuget update source <NAME> --allow-insecure-connections
```

If you wanted them all to allow insecure connections, you'd have to run `dotnet nuget list source`, parse the output, and run the command for each one.

If you really want a machine-wide environment variable that allows all connections to be insecure, please open a new feature request at https://github.com/NuGet/Home/issues/new?template=FEATURE.yml

**Comment by alexsajno** [comment]
@jeffkl We run dotnet build with parameters that specify the nuget.config file path, so the SDK automatically performs dotnet restore before compilation. At which stage am I expected to retrieve the list of sources, parse them, and apply the updates?

We’re not using dotnet nuget add source because we run many jobs in parallel, and this command modifies the user-level configuration on the Windows machine, which can cause conflicts. Your approach works well in Docker, since each build runs in a clean, isolated environment.

I opened a feature request:
https://github.com/NuGet/Home/issues/14643

**Comment by iSeiryu** [comment]
https://github.com/NuGet/Home/issues/14643#issuecomment-3832039882
