### ISSUE TITLE
`dotnet nuget add source` with credentials adds source to local nuget.config but credentials to user level

### ISSUE THREAD

**Issue by McDoit** [NuGet/Home#12797]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet sdk 7.0.306

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Adding a nuget source with login to a local Nuget.config using `dotnet nuget add source` adds source to local nuget.config but credentials to user level NuGet.config

Can be solved by using the --configfile parameter but just strange to have this behavior

Repro:
Check user level config

`mkdir C:/nugetsourcebug`

`cd C:/nugetsourcebug`

`dotnet new nugetconfig`

`dotnet nuget add source "https://feed/v3/index.json" -n "source" --username "user" --password "pass"`

Check local nuget.config and user level config, source is added to local and credentials is added to the user level

**Comment by zivkan** [comment]
@McDoit why do you think this is a bug?

If I have a nuget.config in my repo, I don't want my credentials being saved into the repo nuget.config and accidentally being commit.

To me, saving credentials in my home directory seems like a good security feature.
