### ISSUE TITLE
The nuget.info site is broken, blocked by CORS policy

### ISSUE THREAD

**Issue by chucklu** [NuGet/Home#12796]
### NuGet Product Used

Other/NA

### Product Version

1.0.0

### Worked before?

not sure 

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Did you update the policy on nuget.info site? Now when I try to access the package info of nuget package, such as https://nuget.info/packages/Microsoft.AspNetCore.Identity.UI/7.0.9.
The link is dead, and got console error as:

Access to fetch at 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.identity.ui/7.0.9/microsoft.aspnetcore.identity.ui.7.0.9.nupkg' from origin 'https://nuget.info' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by chucklu** [comment]
Did you fix this? It works again, the package info could be loaded now.

**Comment by zivkan** [comment]
@chucklu NuGet Package Explorer isn't owned by or run by Microsoft's NuGet team. nuget.org just has a link to it, because it's a useful and commonly used tool.  You can direct your questions to their official repo: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

**Comment by chucklu** [comment]
@zivkan  Thanks for the tip, next time I will know report issue to the package explorer
