### ISSUE TITLE
Symbols package is missing some content when custom nuspec file is used

### ISSUE THREAD

**Issue by WenningQiu** [NuGet/Home#12798]
### NuGet Product Used

MSBuild.exe

### Product Version

VS2022, 17.6.5

### Worked before?

N/A

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I opened https://github.com/dotnet/project-system/issues/9188, but was advised to raise the issue here instead.

## Visual Studio Version

Version 17.6.5

## Summary

I am using a custom nuspec file to build NuGet package for my application. When "IncludeSymbols" is set to true, one file listed in nuspec file is missing in the symbols package that is produced; the other package is fine.

## Steps to Reproduce

The nuspec file:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>$Id$</id>
    <version>$Version$</version>
    <authors>$Authors$</authors>
    <description>CommandControl command line tools.</description>
  </metadata>
  <files>
    <file src="$OutputPath$\net48\CSG.Framework.CommandController.exe" target="tools" />
    <file src="$ProjectDirectory$\..\..\..\Scripts\ServiceControl.ps1" target="tools" />
  </files>
</package>
```

SDK csproj file snippet that sets package building properties:

```
    <NoWarn>NU5111</NoWarn>
    <DebugType>embedded</DebugType>

    <IsPackable>true</IsPackable>
    <NuspecFile>$(MSBuildProjectName).nuspec</NuspecFile>
    <NuspecBasePath>$(MSBuildProjectDirectory)</NuspecBasePath>
    <NuspecProperties>Id=$(AssemblyName);Version=$(Version);Authors=$(Authors);ProjectDirectory=$(MSBuildProjectDirectory);OutputPath=$(OutputPath)</NuspecProperties>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
```

## Expected Behavior

NuGet package's tools folder contains two files.

## Actual Behavior

ServiceControl.ps1 is missing from the tools folder of the symbols package:
```
Listing archive: CSG.Framework.CommandController.23.3.0.symbols.nupkg

--
Path = CSG.Framework.CommandController.23.3.0.symbols.nupkg
Type = zip
Physical Size = 682463

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-07-26 15:59:52 .....          525          291  _rels\.rels
2023-07-26 15:59:52 .....          409          255  CSG.Framework.CommandController.nuspec
2023-07-26 20:59:52 .....      1883648       680504  tools\CSG.Framework.CommandController.exe
2023-07-26 15:59:52 .....          465          206  [Content_Types].xml
2023-07-26 15:59:52 .....          717          425  package\services\metadata\core-properties\51518f895ddb457ab0cc0aedc65a7ba6.psmdcp
------------------- ----- ------------ ------------  ------------------------
2023-07-26 20:59:52            1885764       681681  5 files
```

The non-symbols package has the correct content:
```
Listing archive: CSG.Framework.CommandController.23.3.0.nupkg

--
Path = CSG.Framework.CommandController.23.3.0.nupkg
Type = zip
Physical Size = 683522

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-07-26 15:59:52 .....          525          292  _rels\.rels
2023-07-26 15:59:52 .....          409          255  CSG.Framework.CommandController.nuspec
2023-07-26 20:59:52 .....      1883648       680504  tools\CSG.Framework.CommandController.exe
2017-11-07 13:39:06 .....         3922          929  tools\ServiceControl.ps1
2023-07-26 15:59:52 .....          528          211  [Content_Types].xml
2023-07-26 15:59:52 .....          717          425  package\services\metadata\core-properties\823d253a9625412ab9f984f4a3efd42c.psmdcp
------------------- ----- ------------ ------------  ------------------------
2023-07-26 20:59:52            1889749       682616  6 files
```

## User Impact

The symbols package has incorrect content.

**Comment by jeffkl** [comment]
I'm not able to reproduce this.  I've attached a .zip with a project and the symbols package has the correct contents.  Did I do something different?

```
msbuild ClassLibrary1.csproj /restore /bl
```

[nuspec-symbols.zip](https://github.com/NuGet/Home/files/12263986/nuspec-symbols.zip)

![image](https://github.com/NuGet/Home/assets/17556515/fa6f5d22-23ab-4b24-994f-0f1ca44a5e84) 
![image](https://github.com/NuGet/Home/assets/17556515/700479c5-d896-4692-b061-39935534c70f)

**Comment by WenningQiu** [comment]
@jeffkl You were using tools/Something.txt. Can you try tools/Something.ps1? The issue appears to be related to how PS1 files are handled.

**Comment by jeffkl** [comment]
I don't see a difference when using `.ps1`

```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>$Id$</id>
    <version>$Version$</version>
    <authors>$Authors$</authors>
    <description>CommandControl command line tools.</description>
  </metadata>
  <files>
    <file src="$OutputPath$ClassLibrary1.dll" target="tools" />
    <file src="$ProjectDirectory$\..\Something.ps1" target="tools" />
  </files>
</package>
```
![image](https://github.com/NuGet/Home/assets/17556515/ee16b2e8-1128-4240-9ed7-fe0787b043e7)

**Comment by WenningQiu** [comment]
@jeffkl I noticed that you were examining the content of ClassLibrary1.1.0.0.nupkg. Can you check the content of ClassLibrary1.1.0.0.symbols.nupkg instead?

**Comment by jeffkl** [comment]
Okay sorry, looks like this is currently by design:

https://github.com/NuGet/NuGet.Client/blob/3297d73a377a597e5d5cd0a92dc6c03cbcf39d20/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L49-L54

@nkolev92 is the intent of that code to exclude init.ps1, install.ps1, and uninstall.ps1?  If so, should we make that list more precise or do we want to exclude all PowerShell scripts from the tools folder of any symbol package?

**Comment by nkolev92** [comment]
It seems like it's all scripts. 
symbols packages are a lot slimmer than regular nupkgs.

**Comment by zivkan** [comment]
I don't understand why symbols packages ever used an exclude list, rather than an include list. The ["symbol server scenario"](https://github.com/NuGet/NuGet.Client/blob/3297d73a377a597e5d5cd0a92dc6c03cbcf39d20/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L49) is that the symbols package (whether it's `.symbols.nupkg` or `.snupkg`) is a container for the files that a [symbols server](https://en.wikipedia.org/wiki/Microsoft_Symbol_Server) hosts. Which I think is only `*.pdb` (maybe also source?  I'm not sure). It would have been so much less "fragile" (fewer unintended files being included) if it only ever used an allow list.

@WenningQiu can you explain how your "symbols packages" are being consumed, and therefore why anything under `tools/*` is important?  I don't believe this is in line with the original design goals of symbols packages. Understanding can help us prioritize if it's a useful & "supported" scenario.

**Comment by WenningQiu** [comment]
@zivkan 

**Why/how we use symbols packages:** Our applications require PDB files to be present in order to extract code location information (method name, source file name and source line number etc.) to be included in log messages. So we use ```IncludeSymbols>true</IncludeSymbols>``` to build symbols packages that have PDB included.

**Why we pack PS1 scripts in NuGet packages:** We are migrating away from wixlib; so files that used to be distributed in wixlib need a new mechanism to be distributed to the consuming applications. I expected that the content of symbols package and non-symbols package to be the same execept for the PDB file. Since tools folder appears to be treated in some special way, I have since moved PS1 files to contentFiles folder as a workaround.

**Comment by nkolev92** [comment]
Team Triage: At this point, we're unlikely to make changes to the allow list for symbols packages.
