### ISSUE TITLE
update-package : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AndiRudi** [NuGet/Home#1279]
In VS2015 I issued a update-package -reinstall in the package manager console. After a long long time the following error occured:
...
Package 'Google.Apis 1.9.2' already exists in folder 'C:\repository\coursika\Stories\1972-MembershipPay\packages'
Added package 'Google.Apis 1.9.2' to 'packages.config'
update-package : Object reference not set to an instance of an object.
At line:1 char:1
- update-package -reinstall
- ~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

**Comment by yishaigalatzer** [comment]
What version of NuGet are you using? Did you update to the latest available?
We are going to push a release of 3.2 in a couple of days. Would you be able to verify if it resolves your scenario?

**Comment by AndiRudi** [comment]
I have 3.1.60724.766. I will retry with next version.

**Comment by yishaigalatzer** [comment]
I don't think we have a repro for this nullref? Would you mind sharing a full repro?

**Comment by yishaigalatzer** [comment]
@AndiRudi we have 3.2 out, but we still don't have a repro for your scenario? Would you mind sharing a small project that will reproduce this issue (or a bigger one if you can't)?

**Comment by AndiRudi** [comment]
Today i retested with 3.2 and everything worked! Issue can be closed
