### ISSUE TITLE
Can't add New Scaffold Identity

### ISSUE THREAD

**Issue by nguyentuananh921** [NuGet/Home#12806]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

C:\Users\Nguyen Tuan Anh>dotnet --info .NET SDK:  Version:   8.0.100-preview.7.23376.3  Commit:    daebeea8ea  Runtime Environment:  OS Name:     Windows  OS Version:  10.0.19045  OS Platform: Windows  RID:         win10-x64  Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\  .NET workloads installed: There are no installed workloads to display.  Host:   Version:      8.0.0-preview.7.23375.6   Architecture: x64   Commit:       65b696cf5e   RID:          win-x64  .NET SDKs installed:   7.0.305 [C:\Program Files\dotnet\sdk]   8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]   8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Other architectures found:   x86   [C:\Program Files (x86)\dotnet]     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]  Environment variables:   Not set  global.json file:   Not found  Learn more:   https://aka.ms/dotnet/info  Download .NET:   https://aka.ms/dotnet/download  C:\Users\Nguyen Tuan Anh>

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have try to create new WebApp MVC.
Then I Add Scaffold Item-> Add Identity.
But I failed.

I Have try:
- Add Package Microsoft.VisualStudio.Web.CodeGeneration.Design on Manage Nuget Package 
And I found
Microsoft.VisualStudio.Web.CodeGeneration.Design Version 8.0.0-preview.6.23360.4 
But Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.0-preview.7.23375.9
And I see the Error:
![image](https://github.com/NuGet/Home/assets/18616693/4398613f-c8bc-46b9-b105-c3d35b542f26)

**Comment by donnie-msft** [comment]
We don't support individual packages. I see you've already contacted the package owner, and they've issued a response about a missing transitive dependency. Please follow-up there, and if once the dependencies are made available you still experience issues with NuGet, reactivate or file a new bug.

https://github.com/dotnet/Scaffolding/issues/2493#issuecomment-1675468078
