### ISSUE TITLE
Nuget Version string is translated when called from the command line on some locales

### ISSUE THREAD

**Issue by leezer3** [NuGet/Home#12818]
### NuGet Product Used

NuGet.exe

### Product Version

6.6.1.2

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

https://github.com/leezer3/OpenBVE/issues/929

I have a command-line script (makefile, but that's not really important here) which is used to build on non-windows platforms.
In order to do this, we need a minimum nuget version.

So-far, so good.
The Microsoft documentation suggests that the correct way to do this is to run the **nuget help** command, and to appropriately parse the output.
https://learn.microsoft.com/en-us/nuget/resources/nuget-faq#how-do-i-get-the-latest-version-of-nuget-command-line-tool-
```
How do I get the latest version of NuGet command line tool?

See the [Install guide](https://learn.microsoft.com/en-us/nuget/install-nuget-client-tools). To check the current installed version of the tool, use nuget help.
```

On Debian **en_US.UTF-8** this produces the following version string output (trimmed to remove the help text):
```
NuGet Version: 6.3.1.1
```

Similarly, on Debian **de_DE.UTF-8** this produces the following:
```
NuGet Version: 6.3.1.1
```

However, on a Korean locale Mac, the string version is translated:
```
NuGet 버전: 6.6.1.2
```

---

Essentially, what I'd suggest is *not* translating the string _Version_ in any case. This would provide a consistant way to get the version string, but I'm also not entirely clear why it's not being translated in the German case, seeing as most of the other command-line output is.
A 'better' solution to the problem would be something like the following:
`nuget version` to return simply the version number, but I don't know why the original design choice was made.

**Comment by martinrrm** [comment]
@leezer3 Verion is being translated in the German case, but in this scenario the word is the same.

![image](https://github.com/NuGet/Home/assets/43253759/9d8331f5-3720-4a69-87c1-5389d4d1713f)

**Comment by leezer3** [comment]
Good point, although as a non native speaker, I'd not thought to run through translate. Assumptions are the mother of all...... :)

This isn't necessarily the end of the world whatever you decide, it just seems to me to be an issue. I need to check what Mono / .Net return under these cases too.
Someone else must have thought of this :/

**Comment by leezer3** [comment]
As a note, an easy fix would be to *remove* Version entirely from that string.
It's superfluous, and I presume should be dead simple.

Could probably look into a PR if you think it appropriate in that case.

**Comment by nkolev92** [comment]
Team Triage: This is by design. You can consider parsing everything after `:`.
