### ISSUE TITLE
Test:  use product resource string instead of hard-coded en-US string

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#12820]
It should be easy to clone the repo, build and test, irrespective of the current user's locale.  There's at least [one report](https://github.com/NuGet/NuGet.Client/pull/5002#issuecomment-1679707317) that this workflow was not possible without first changing the locale to en-US.  While the report lacks detail, I suspect that the problem is that some tests use hard-coded en-US strings ([example](https://github.com/NuGet/NuGet.Client/blob/4d815bf71aa1ce5fe8d9d9da6573303d7093c2f1/test/NuGet.Clients.FuncTests/NuGet.CommandLine.FuncTest/Commands/InstallCommandTests.cs#L32)) instead of using the product's resource string.

**Comment by dotnokato** [comment]
One way to solve that could be to add `-ForceEnglishOutput` as one of the arguments passed to `CommandRunner.Run`.
Happy to submit a PR if this is an acceptable solution.

**Comment by nkolev92** [comment]
Team Triage: Tests should use resource strings *when possible* to allow them to be runnable on machines with different locales.

**Comment by dotnokato** [comment]
To give more context: My machine is setup with non-English language (Polish) and non-us regional format.
When I run `build.ps1`, I get quite a high number of tests failing -> as of writing this comment, running on `dev` branch, resulted in 118 tests failing. I'll include list of those tests in a separate comment below.

To get those tests run successfully without any code changes I need to:
- set system language to `English`
- set regional format to `English (United States)`

Interestingly enough, setting environment variable `DOTNET_CLI_UI_LANGUAGE` to `en-us` shaves the number of tests failing by ~1/3rd, to around 70.

**Comment by dotnokato** [comment]
| Test name                                                                                                                                                                                 | Error                                                                                                 |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------- |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsList_WithSupportedTypes_ReturnsStringArrFaileday                                                                   | Assert.Collection() Failure                                                                           |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19.   1 9")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1     1.1.1.1")                                                                               | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.3.-4")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1. .1")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNullOrEmpty                                                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.Protocol.Tests.PackageUpdateResourceTests.PackageUpdateResource_SymbolSourceOnlyPushingAsync                                                                                        | System.Net.Http.HttpRequestException : Kod stanu odpowiedzi nie wskazuje powodzenia: 403 (Forbidden). |  |
| NuGet.Common.Test.CryptoHashProviderTest.CryptoHashProviderThrowsIfHashAlgorithmIsNotSHA512orSHA256(hashAlgorithm: "md5")                                                                 | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2..")                                                                                       | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.3.4This version is full of awesomeness!!")                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.2147483648")                                                                            | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.-1.1.1")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "So.is.this")                                                                                  | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1beta")                                                                                       | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2147483648")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Configuration.Test.SettingsTests.ResolvePathFromOrigin_WhenPathIsInvalidRelativeFileSystemPath_Throws                                                                               | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenCopyrightValueIsConvertibleToString_ReturnsCopyright(value: "3.14", expectedValue: "3.14")                          | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1 .")                                                                                       | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1 .")                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.3.Beta")                                                                                  | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.2147483648")                                                                              | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.-2.3.4")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.-1")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "         ")                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringOrArrayOfStringsAsReadOnlyList_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14") | Assert.Collection() Failure                                                                           |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "19   .1 9   ")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19.   19.   19.   1 9")                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.DependencyResolver.Core.Tests.GraphNodeTests.GraphNode_WithDifferentHasEmptyInnerNodes_CreateInnerNodesCorrectly(hasInnerNodes: False, innerNodesHasNode: False)                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "-1.2.3.4")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7+*")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.")                                                                                          | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenAuthorsValueElementIsConvertibleToString_ReturnsAuthor(value: "3.14", expectedValue: "3.14")                        | Assert.Collection() Failure                                                                           |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1     1.1.1")                                                                               | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenContentFilesValueElementIsConvertibleToString_ReturnsContentFile(value: "3.14", expectedValue: "3.14")              | Assert.Collection() Failure                                                                           |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7-AA.01^")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Common.Test.CryptoHashProviderTest.CryptoHashProviderThrowsIfHashAlgorithmIsNotSHA512orSHA256(hashAlgorithm: "SHA2561")                                                             | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenFrameworksDependenciesDependencyValueIsArray_Throws(propertyName: "include")                                        | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19.   19.   1 9")                                                                          | Assert.Contains() Failure                                                                             |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.10000000000000000000")                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadNextTokenAsString_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14")                    | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1. ")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.34.2Release Candidate")                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1.")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   1 9")                                                                                      | Assert.Contains() Failure                                                                             |
| NuGet.Configuration.Test.SearchTreeTest.SearchTree_InvalidSearchInput_Throws(packagePatterns: "nuget.org,nuget", term: "")                                                                | Assert.Equal() Failure                                                                                |
| NuGet.Configuration.Test.SearchTreeTest.SearchTree_InvalidSearchInput_Throws(packagePatterns: " nuget.org , nuget", term: " ")                                                            | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1 .")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "..1")                                                                                         | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1..2")                                                                                        | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.-1.1")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Packaging.Test.ManifestTest.RejectsInvalidPackageTypeWhenValidatingSchema                                                                                                           | Assert.Equal() Failure                                                                                |
| NuGet.Common.Test.CryptoHashProviderTest.CryptoHashProviderThrowsIfHashAlgorithmIsNotSHA512orSHA256(hashAlgorithm: "MD5")                                                                 | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "..1.2")                                                                                       | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2147483648.3.4")                                                                            | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "10000000000000000000")                                                                        | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenFrameworksDependenciesDependencyValueIsArray_Throws(propertyName: "suppressParent")                                 | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.-3.4")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.10000000000000000000")                                                                      | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "19   .19   .19   .1 9   ")                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Configuration.Test.SearchTreeTest.SearchTree_InvalidSearchInput_Throws(packagePatterns: "nuget.org,nuget", term: null)                                                              | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenBuildOptionsValueOutputNameIsConvertibleToString_ReturnsOutputName(outputName: "3.14", expectedValue: "3.14")       | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "2147483648.2.3.4")                                                                            | Assert.Contains() Failure                                                                             |
| NuGet.DependencyResolver.Core.Tests.GraphNodeTests.GraphNode_WithDifferentHasEmptyParentNodes_CreateParentNodesCorrectly(hasParentNodes: False, parentNodesHasNode: False)                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1. .1.1")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "....")                                                                                        | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1 .")                                                                                         | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19   .   1 9   ")                                                                          | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19   .   19   .   19   .   1 9   ")                                                        | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1.2147483648")                                                                          | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   1 9   ")                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1 9   ")                                                                                      | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1     1.1")                                                                               | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.34.2Alpha")                                                                                 | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.3.2147483648")                                                                            | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "19   .19   .1 9   ")                                                                          | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.2147483648.4")                                                                            | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "-1.1.1.1")                                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7-*")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: " .1.1.1")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7-AA.0A^")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7-")                                                                                      | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7+AA.01^")                                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "   19   .   19   .   1 9   ")                                                                 | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2.3.4.5")                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.Protocol.Tests.PackageUpdateResourceTests.PackageUpdateResource_GetErrorFromCreateKeyPushingAsync                                                                                   | Assert.True() Failure                                                                                 |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.")                                                                                      | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsReadOnlyListFromArrayStart_WhenValuesAreConvertibleToString_ReturnsReadOnlyList                                    | Assert.Collection() Failure                                                                           |
| NuGet.Configuration.Test.SearchTreeTest.SearchTree_InvalidSearchInput_Throws(packagePatterns: "nuget.org,nuget", term: " ")                                                               | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenFrameworksDependenciesDependencyValueIsArray_Throws(propertyName: "exclude")                                        | Assert.Equal() Failure                                                                                |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.4.7-A^A")                                                                                   | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1.10000000000000000000")                                                                | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.")                                                                                        | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.2Av^c")                                                                                     | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1     1")                                                                               | Assert.Contains() Failure                                                                             |
| NuGet.Versioning.Test.NuGetVersionTest.ParseThrowsIfStringIsNotAValidSemVer(versionString: "1.1.1.1.1.")                                                                                  | Assert.Contains() Failure                                                                             |
| NuGet.Common.Test.CryptoHashProviderTest.CryptoHashProviderThrowsIfHashAlgorithmIsNotSHA512orSHA256(hashAlgorithm: "SHA1")                                                                | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenCopyrightValueIsConvertibleToString_ReturnsCopyright(value: "3.14", expectedValue: "3.14")                          | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringOrArrayOfStringsAsReadOnlyList_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14") | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadNextTokenAsString_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14")                    | Assert.Equal() Failure                                                                                |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadNextTokenAsString_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14")                    | Assert.Equal() Failure                                                                                |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsList_WithSupportedTypes_ReturnsStringArray                                                                         | Assert.Collection() Failure                                                                           |
| NuGet.Common.Test.DateTimeUtilityTests.ToReadableTimeFormat_Localized_AssumesEnglishLocale_ContainsTimeNumber_Succeeds                                                                    | Assert.Contains() Failure                                                                             |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenContentFilesValueElementIsConvertibleToString_ReturnsContentFile(value: "3.14", expectedValue: "3.14")              | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsReadOnlyListFromArrayStart_WhenValuesAreConvertibleToString_ReturnsReadOnlyList                                    | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenCopyrightValueIsConvertibleToString_ReturnsCopyright(value: "3.14", expectedValue: "3.14")                          | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenAuthorsValueElementIsConvertibleToString_ReturnsAuthor(value: "3.14", expectedValue: "3.14")                        | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenBuildOptionsValueOutputNameIsConvertibleToString_ReturnsOutputName(outputName: "3.14", expectedValue: "3.14")       | Assert.Equal() Failure                                                                                |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenAuthorsValueElementIsConvertibleToString_ReturnsAuthor(value: "3.14", expectedValue: "3.14")                        | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsList_WithSupportedTypes_ReturnsStringArray                                                                         | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringOrArrayOfStringsAsReadOnlyList_WhenValueIsConvertibleToString_ReturnsValueAsString(value: "3.14", expectedResult: "3.14") | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonTextReaderExtensionsTests.ReadStringArrayAsReadOnlyListFromArrayStart_WhenValuesAreConvertibleToString_ReturnsReadOnlyList                                    | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenContentFilesValueElementIsConvertibleToString_ReturnsContentFile(value: "3.14", expectedValue: "3.14")              | Assert.Collection() Failure                                                                           |
| NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WhenBuildOptionsValueOutputNameIsConvertibleToString_ReturnsOutputName(outputName: "3.14", expectedValue: "3.14")       | Assert.Equal() Failure                                                                                |

**Comment by dotnokato** [comment]
I've submitted https://github.com/NuGet/NuGet.Client/pull/5442 and https://github.com/NuGet/NuGet.Client/pull/5441 fixing all but one tests that have been failing on my machine.

The last test failing is [PackageUpdateResource_SymbolSourceOnlyPushingAsync](https://github.com/NuGet/NuGet.Client/blob/b4115e8b4fa35c418086cedecd946c696dd4c7b1/test/NuGet.Core.Tests/NuGet.Protocol.Tests/Resources/PackageUpdateResourceTests.cs#L383) which fails due to method under test [expecting exception message in English](https://github.com/NuGet/NuGet.Client/blob/b4115e8b4fa35c418086cedecd946c696dd4c7b1/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L923C30-L923C30).

In this case not sure if the test itself or rather method under test should be updated.
