### ISSUE TITLE
[Bug Bash] The vulnerability InfoBar of the second project will not show after closing the one for the first project

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12823]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.8.0.68

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1. Create a C# Console App (.Net Core) **-- .NET 8.0** project (the first project). 
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.   
3. Install a vulnerable package version (e.g. Newtonsoft.json 12.0.1) into this project and restore the solution. 
4. Close the vulnerability InfoBar on top of the Solution Explorer window. 
5. **Don’t close VS** and click the menu “File->New->Project” to create a C# Class Library (.Net Core) **-- .NET 8.0** project (the second project). 
6. Install a vulnerable package version (e.g. Newtonsoft.json 12.0.3) into this project and restore the solution. 
#### Expected:
The vulnerability InfoBar of the second project should show after closing the one for the first project. 
![image](https://github.com/NuGet/Home/assets/40230425/7728e7f5-a6dc-4d9f-89f1-127d4a68882b)
#### Actual: 
The vulnerability InfoBar of the second project will not show after closing the one for the first project.
![image](https://github.com/NuGet/Home/assets/40230425/bb8772ce-964f-4e58-b071-d3905e82537c)
#### Note:
1. The issue doesn’t repro if creates the second project after closing VS in step5.
2. It’s not a regression since this is a new feature.

**Comment by kartheekp-ms** [comment]
I am able to reproduce this issue following the steps mentioned in the issue description.

**Comment by nkolev92** [comment]
Team Triage: We believe this is by design. 
The info bar will notify the user at most once during a solution session. 

The info bar will show again if the solution is reloaded or Visual Studio is restarted.
