### ISSUE TITLE
Support clearing package source mappings for repo-local NuGet.config files

### ISSUE THREAD

**Issue by mitchdenny** [NuGet/Home#12836]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, dotnet.exe

### The Elevator Pitch

Often you will add package sources and package source mappings to your global ```NuGet.config``` file. But sometimes you work with a repository that has its own package sources which require a different set of mappings. The idea behind this feature request is to allow me to ```<clear />``` the package source mappings in a repo-local ```NuGet.config``` file so that I can override my global defaults.

### Additional Context and Details

I ran into this issue because I was working on a project outside my usual repo and I was testing some new project templates. The project template and the dependencies for the code in the templates were in a different private feed. It worked well when I set up my source mappings in my global ```NuGet.config``` file but when I went back to my usual repo I didn't anticipate that those package source mappings would apply to the repo local version especially since there isn't a ```<clear />``` gesture you can make for package source mappings.

**Comment by kartheekp-ms** [comment]
> since there isn't a <clear /> gesture you can make for package source mappings.

Adding `<clear />` tag to `packageSourceMapping` element in nuget.config file is supported. For e.g., please refer to https://github.com/NuGet/NuGet.Client/blob/dev/NuGet.Config#L12
