### ISSUE TITLE
VS Options add/remove package source icons aren't using VS2022 styling

### ISSUE THREAD

**Issue by timheuer** [NuGet/Home#12840]
I've been spending a lot of time lately in the NuGet Package source feed location and the icons are not current UX for VS2022.
![55f95066-71e1-4c34-8318-b73ff766583e](https://github.com/NuGet/Home/assets/4821/0837f93f-7b8e-47c3-8ec0-65b23cf66ab2)

These should be updated using the add/cancel (and I see the image list uses moveUp/Down as well but don't know where those are used) using the known monikers from VS2022.  In doing so it will result in:
![image](https://github.com/NuGet/Home/assets/4821/9d4bcca5-007d-4688-9cb7-4cceb819ed40)

It is a small change but makes the UI up to standard images used if still going to use images in this dialog.

The Up/Down are also updated:
![image](https://github.com/NuGet/Home/assets/4821/51c0259a-7294-4885-8953-bc46bcdde7b0)

**Comment by donnie-msft** [comment]
@timheuer thanks again for the contribution. Can you elaborate on this part?

> The Up/Down are also updated:

We haven't had up/down arrows in a while, so I want to make sure I'm not missing part of your PR.

**Comment by timheuer** [comment]
Yeah @donnie-msft I agree I couldn't find them anywhere, but in the spirit of ensuring no breaking and needing to keep the `imageList` index the same, there are 4 images in the base64-encoded imageList(s) -- in order: up/down/cancel/add in a specific index order.  I also could not find any code that references the up/down images anymore but they are still present in the imageList (and thus the base64 value).  In order to preserve the index, I made sure to retain the up/down/cancel/add ordering in the base64 value and ensure those images are still there...but also updated them with the KnownMonikers versions in VS.  If you look at the images in `imageList` control on `PackageSourcesOptionsControl.cs` you will see them there (in Windows Forms designer so it helps decode the value ;-))

See: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Options/PackageSourcesOptionsControl.Designer.cs#L98-L101 (and also repeated in `images32px`/`images64px`.  So the update was just to keep this code consistent.
