### ISSUE TITLE
NuGet Source Transformation (.pp) not working as expected

### ISSUE THREAD

**Issue by AR-May** [NuGet/Home#12857]
---
**Issue moved from dotnet/msbuild#8322**
- Please respond to @Aragas.

---

_From @Aragas on Thursday, January 19, 2023 4:33:16 PM_

### Issue Description
As I understand, MSBuild 17.5 might have broken the transformation.
The `obj` folder that should contain the transformed source code (`.cs.pp`) of a nuget package is empty - it doesn't contain the final `.cs` files where things like `$rootnamespace$` are resolved.
As an example, I have a NuGet Source Package (`BUTR.DependencyInjection` version 2.0.0.43) that stopped working.
The workarounds I saw while browsing source codes were basically "get rid of the .pp ending", since `.pp` was just used to hide the additional files. But how to fix it when it was used for the actual transformations?

## Steps to Reproduce
1. Create an empty C# project
2. Add `BUTR.DependencyInjection` version 2.0.0.43

## Expected Behavior
`.pp` files should be correctly transformed into `.cs` files

## Actual Behavior
`.pp` files are not correctly transformed into `.cs` files

### Versions & Configurations
VS2022
MSBuild version 17.4.1+9a89d02ff for .NET Framework
17.4.1.60106

VS2022 Preview
MSBuild version 17.5.0-preview-23053-01+ac0911a00 for .NET Framework
17.5.0.5301

VS2019
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Happens in VS2019/VS2022/VS2022 Preview.
Happens on Rider too when MSBuild is used.

The computer I'm using is a fresh install. It does work still on my older one, ~~but it's I guess because I didn't upgrade yet, it's version is 17.4+9a89d02ff~~

EDIT:
The version of MSBuild seems to be the same for the working one and the broken one when using VS2022, the MSBuild versions of VS2019 is 16.
After verifying this, I have no idea what is causing this.
Also, to add to the confusion, when Rider is switched to use MSBuild, the same issue happens there too.

**Comment by zivkan** [comment]
@AR-May sorry about the delay in responding to this. I had a very busy week on support 😞 

Anyway, I just tried myself, but I can't reproduce the problem. Here's what I did:

```pwsh
dotnet new console
dotnet add package butr.dependencyinjection --version 2.0.43
echo "_ = typeof(BUTR.DependencyInjection.GenericServiceProvider);" > Program.cs
dotnet build
Remove-Item -r -force obj\
Remove-Item -r -force bin\
msbuild -restore -t:Build -v:m
```

I didn't get any errors.

When I look at `obj\project.assets.json`, I can see all the `.pp` files listed, each of which has a `ppOutputPath` property to a file with extension `.cs`, and when I do the MSBuild without `-v:m`, I can see all the `.cs` files passed to `csc.exe`.

I'm using a .NET 8 preview SDK, and MSBuild 17.8 preview.


If you're still having these problems, can you check the `project.assets.json` file and make sure they're listed?

If you run `msbuild -restore -bl`, this will create a file in the current directory called `msbuild.binlog`, which can be viewed using https://msbuildlog.com (there's a WIndows app to download, or view in the browser). Can you attach that? It might give us hints as to what's going on.

**Comment by zivkan** [comment]
Sorry, this should have been addressed to @Aragas

I'm not familiar with this `.pp` transformation feature, so it was breaking my brain.

**Comment by zivkan** [comment]
note to anyone else who might investigate, looks like what happens is NuGet puts all these `.pp` files in the assets file, then a task named `ProduceContentAssets`, coming from `Microsoft.NET.Build.Tasks.dll`, writes all the transformed files. Therefore, depending on what the customer's binlog says, we might need to transfer the issue to dotnet/sdk.

Actually, maybe the project isn't an SDK style project, so we need to test non-SDK style project as well.  @aragas, what kind of project are you using the package in?
