### ISSUE TITLE
Wrong markdown for usage examples

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1285]
@skazantsev

The help command generates a blockquote only for the first usage example. It looks like a bug.
The version of NuGet I use is 2.8.60717.93

_Command:_

```
NuGet.exe help -All -Markdown
```

_Output:_
....
### Examples

```
nuget install elmah
```

nuget install packages.config

nuget install ninject -o c:\foo

....

**Comment by yishaigalatzer** [comment]
I'm moving this out beyond 3.3, because in all honesty it is not meeting the bar as other more critical bugs. We will gladly take a pull request for this though.
