### ISSUE TITLE
Remove the NuGetOperationType from NuGet.PackageManagement, use NuGetProjectActionType instead

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#12866]
While working conditional PR updating, I noticed myself doing a lot of duplicated work. See more details for motivation: https://github.com/NuGet/NuGet.Client/compare/dev-nkolev92-conditionalPackageReferenceUpdating?expand=1

For example, I had to do lots of conversions with NuGetProjectActionType and NuGetOperationType.
This is redundant, and makes our code more complicated.

I looked at the references and the only place where the NuGetOperationType is explicitly used is as an API is ActionTelemetryEvent, which is not used a lot.

Consolidating these types simplifies the NuGet code and makes future updates simpler.

**Comment by ghost** [comment]
@nkolev92 Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/5394
