### ISSUE TITLE
PackageReadmeFile outside csproj (in props file) doesn't work

### ISSUE THREAD

**Issue by michael-hawker** [NuGet/Home#12872]
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild version 17.7.2+d6990bcfa for .NET Framework

### Impact

It's more difficult to complete my work

### Repro Steps & Context

The docs and most examples seem to indicate you should do something like this directly in the csproj file:

```xml
    <PackageReadmeFile>ReadMe.md</PackageReadmeFile>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="ReadMe.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
```

However, we have a bunch of projects which all share a props file and similar structure, so we wanted to abstract this to just detect if there was a `ReadMe.md` file in the source's project directory next to our `csproj` file, so I did this:

```xml
     <PackageReadmeFile Condition="Exists('$(MSBuildProjectDirectory)\ReadMe.md')">ReadMe.md</PackageReadmeFile>
  </PropertyGroup>
  
    <ItemGroup>
      <None Include="$(MSBuildProjectDirectory)\ReadMe.md" Pack="true" PackagePath="\" Condition="Exists('$(MSBuildProjectDirectory)\ReadMe.md')"/>
    </ItemGroup>
```

Which should be equivalent if a `ReadMe.md` file exists in the same folder as the `csproj` file (which they did).

The former works, but the latter produces this error upon pack:

> Error: C:\Users\runneradmin\.nuget\packages\nuget.build.tasks.pack\6.7.0\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5039: The readme file 'ReadMe.md' does not exist in the package. [C:\a\Windows\Windows\components\Triggers\src\CommunityToolkit.WinUI.Triggers.csproj]

**Comment by heng-liu** [comment]
Hi @michael-hawker , I tried the following but was unable to repro.
Could you try the same steps and let me know if it works for you? And could you provide the repro steps if the following is not the same with yours? Thanks!
1.Create a Classlibrary1 project
2.Add a non-empty ReadMe.md file in solution folder
3.Create a common.props file in solution folder, with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0">
 <PropertyGroup>
     <PackageReadmeFile Condition="Exists('$(MSBuildProjectDirectory)\ReadMe.md')">ReadMe.md</PackageReadmeFile>
  </PropertyGroup>
  
    <ItemGroup>
      <None Include="$(MSBuildProjectDirectory)\ReadMe.md" Pack="true" PackagePath="\" Condition="Exists('$(MSBuildProjectDirectory)\ReadMe.md')"/>
    </ItemGroup>
</Project>
```
4.Add `<Import Project="common.props"/>` into Classlibrary1.csproj file, so it's:
```
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="common.props"/>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```
5. Run dotnet pack, the package contains the Readme.md file as expected.

**Comment by heng-liu** [comment]
BTW, we're considering a feature to automatically include a readme file if it satisfied a certain path. Do you think that would be helpful? 
You may share your thoughts in https://github.com/NuGet/Home/issues/12385, thanks!

**Comment by michael-hawker** [comment]
Thanks for clarifying @heng-liu, I realized after that I forgot to specify directly about the import step in the repro steps.

Main differences in the repro you laid out from what we're doing is our imported props file is in a different directory (not a parent one, e.g. `..\..\tooling\common.props`) and imported at the end of our project file (if location matters).

We're also using `msbuild` over `dotnet` in our process.

**Comment by heng-liu** [comment]
Hi @michael-hawker , thanks for your reply! Using msbuild and dotnet to pack should be the same.
From the msbuild [doc](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2022#define-and-reference-properties-in-a-project-file): `Properties are evaluated in the order in which they appear in the project file.`
You may generate a msbuild binlog to check if the properties are evaluated as expected. https://learn.microsoft.com/en-us/shows/visual-studio-toolbox/msbuild-structured-log-viewer
