### ISSUE TITLE
2.8.6 doesn't work on .NET 4.0

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1287]
@zapov

> ..\NuGet.exe Pack Project.nuspec
> Checking for updates from https://www.nuget.org/api/v2/.
> Currently running NuGet.exe 2.8.5.
> Updating NuGet.exe to 2.8.6.
> Update successful.
> Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from as
> sembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e
> 089'.

**Comment by yishaigalatzer** [comment]
We need to decide if we require .NET 4.5 on the user machine to run or not.

CC @csharpfritz

**Comment by Antiohne** [comment]
I also ran into this problem within my company. When I upgraded one of our solutions to use NuGet 2.8.6 and build that particular project I get the following error message:  

> "Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'." 

I don't understand why there is a .NET framework change (4.0 > 4.5) introduced in a patch level version of NuGet 2. This is a breaking change for us because we can't upgrade our BizTalk 2010 solutions to the .NET 4.5 level. This framework version is not supported by BizTalk 2010.

According to the semantic versioning rules this change only should be introduced in a major version of NuGet. A dependency change on the .NET framework is for me an incompatible API change.

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 1.MAJOR version when you make incompatible API changes,
> 2.MINOR version when you add functionality in a backwards-compatible manner, and
> 3.PATCH version when you make backwards-compatible bug fixes.

**Comment by richardschneider** [comment]
I'm just running .Net 4.0 and get the above error.  Here's some background info I found [Stackoverflow](http://stackoverflow.com/questions/13748055/could-not-load-type-system-runtime-compilerservices-extensionattribute-from-as?lq=1).

**Comment by yishaigalatzer** [comment]
At this point we realize this was a breaking change, but we are not going to go back and fix 2.8.6, you can use 2.8.5 or update to 3.2.1 (or newer) and move to .NET 4.5.

We will eventually produce a version of NuGet.exe that runs on core clr, and that would be independent from the .NET installed on the user's machine.

For now I'm closing this as Won't fix, with the plan to produce an .net independent nuget

**Comment by 4nd3250n** [comment]
How to downgrade to 2.8.5 ?
Info on this would be most welcome.

**Comment by yishaigalatzer** [comment]
Download the nuget package nuget.commandline version 2.8.5 from nuget.org

Sent from my Windows Phone

**Comment by 4nd3250n** [comment]
Will this fix iz or must something else be done also? Because in my case it did not. Still no build.

**Comment by feiling** [comment]
We just uploaded NuGet.CommandLine package 2.9 (which works on .net 4.0). You can get it from https://www.nuget.org/api/v2/package/NuGet.CommandLine/2.9.0. After you download the file, unzip it, and you'll find nuget.exe under directory `tools\`

**Comment by feiling** [comment]
Please try nuget 2.9. You can get it from https://www.myget.org/F/nuget-volatile/api/v2/package/NuGet.CommandLine/2.9.0. After you get the file, unzip it, and you'll find nuget.exe under directory `tools`.

**Comment by 4nd3250n** [comment]
Hi. I have tried it with mixed results.
MSBuild command line now build my project without nuget related errors.
Visual studio does not build nor individual projects nor complete solution. To make worse it does not report any error.

Thank you for 2.9 notification.

**Comment by yishaigalatzer** [comment]
What version of visual studio are you using? And what do you mean by doesn't build?

We recommend that you avoid using msbuild to restore your packages, please read on package restore here: http://docs.nuget.org/consume/package-restore

Sent from my Windows Phone

**Comment by 4nd3250n** [comment]
Visual Studio 2010
And by doesn't build I mean I get this message in output window:

> ------ Rebuild All started: Project: MyProject, Configuration: Debug Any CPU ------
> ========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

And no other error or warning. i have set output options to detail

I will clarify a bit, although this is somewhat out of place here.
It all started when I got some error, can't remember what it was exactly something like 0x800...
Upon all following builds I got the fail message above.
Therefore I tried command line MSBuild to build my project just to get some output. And I did. It was as above:

> "Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly >'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'." 

Your NuGet 2.9 suugestion helped in a sense that MSBuild now builds my project. From command line of course which is impractical.
If I try build/rebuild/clean from visual studio in gives just this "1 failed" message with no further info. It also completes very quickly so I guess the build doesn't even start.
I think this is not related to NuGet anymore. I just wrote this as a brief explanation and to clarify it for you.

**Comment by yishaigalatzer** [comment]
You probably have a version of nuget in your .nuget solution folder that fails to load. Try dir /s nuget.exe from the solution level on the commandline

Sent from my Windows Phone

**Comment by 4nd3250n** [comment]
The dir /s nuget.exe result is

```
Directory of D:\Visual Studio\Projects\MySolution\.nuget
11.09.2015  12:49         1.697.280 NuGet.exe
           1 File(s)      1.697.280 bytes
Directory of D:\Visual Studio\Projects\MySolution\packages\NuGet.CommandLine.2.9.0\tools
07.11.2015  14:29         1.697.280 NuGet.exe
           1 File(s)      1.697.280 bytes

 Total Files Listed:
           2 File(s)      3.394.560 bytes
           0 Dir(s)   7.377.006.592 bytes free
```

**Comment by yishaigalatzer** [comment]
Try following the link I sent before

**Comment by 4nd3250n** [comment]
I am not sure what you are getting at. But i have disabled those two options

>  Visual Studio is configured to 'Allow NuGet to download missing packages'
>     Visual Studio is configured to 'Automatically check for missing packages during build in Visual Studio'

Same result. Build failed.
As I said I dont think this is related anymore to

> Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from as
> sembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e
> 089'.

As much as I would love to have my problem fix I also don't like the idea to clutter this issue with something that may not be related anymore.
