### ISSUE TITLE
NuGet.Build.Tasks.Pack.targets: Could not find a part of path

### ISSUE THREAD

**Issue by msedi** [NuGet/Home#12878]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

dotnet 7.0.100

### Worked before?

I don't know, I havent' tried it before.

### Impact

I'm unable to use this version

### Repro Steps & Context

I'm having several projects, some of them are .NET7, .NET Framework 4.8, .NET Standard 2.0.
It seems on all projects dotnet pack works, but not on .NET standard projects. It stops with the error: ```Could not find a part of the path ```.

The reason seems to be due to a change in the output path:

```
<Project DefaultTargets="Build">
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

	<PropertyGroup>
		<OutputPath>$(BuildRoot)\_Build\$(Configuration)\Apps\$(MSBuildProjectName)</OutputPath>
		<OutDir>$(OutputPath)</OutDir>
	</PropertyGroup>
</Project>
```

and the output for all project is exactly dropped into the given folders:

`_Build\Debug\Assemblies\ipipe.DataCollections.SourceGeneration\ipipe.DataCollections.SourceGeneration.dll`

but the packing tries to locate the output in

`_Build\Debug\Assemblies\ipipe.DataCollections.SourceGeneration\netstandard2.0\win-x64`

It doesn't matter if I call `dotnet pack` or if I use the `Pack` method directly from Visual Studio.

Is this a known behavior?

**Comment by zivkan** [comment]
"could not find part of path" is unfortunately the most common error that Windows provides for long path issues. So, my question is if the full path of the file is it over 260 characters?

However, if you enable Windows' long path support, then the dotnet cli should work with long paths. If you're still getting the error, it's likely (well, it has to be) something else.

**Comment by zivkan** [comment]
Oh, but Visual Studio (devenv.exe) doesn't support long paths, so even if you enable it in the OS, it still might not work. But `dotnet pack` on the command line will work, if it's a long path issue.

**Comment by msedi** [comment]
@zivkan. I think the problem is not the path length, since there is a small prefix at the beginning:

The problem is that obviously the NET Standard pack does not consider that there is no framework and runtime path attached, as you can see in the normal build

`D:\GIT\_Build\Debug\Assemblies\ipipe.DataCollections.SourceGeneration\ipipe.DataCollections.SourceGeneration.dll`

but obviously in NET Standard it looks for it in a different path (below is the message from the pack command):

`D:\GIT\_Build\Debug\Assemblies\ipipe.DataCollections.SourceGeneration\netstandard2.0\win-x64`

**Comment by zivkan** [comment]
If you're reasonably familiar with MSBuild, you can try getting binlogs (`dotnet pack -bl` will create a file named `msbuild.binlog` in the current directory), which you can view with https://msbuildlog.com (there's a Windows app that can be downloaded, or view in the web app).

Otherwise, I'll let whoever is on our rotating support roster investigate.

If you're able to create a sample project/solution that repros the bug and attach the zip, it will reduce the risk that we're unable to reproduce the error when we try to create our own sample. For example, there might be more going on that the one `Directory.Build.props` you put in the original issue. It does import another `Directory.Build.props` after all.

To be honest, I'm expecting it's a bug with your own build custimisation. NuGet.Client itself redirects the `obj/` and `bin/` directories to non-standard locations, and our `dotnet pack` works. My guess is that you have a target somewhere that modifies some properties, and this target only runs as part of build, but not pack. Hence why pack is looking for the assembly on a different path to where build put it. The binlog should be able to confirm this guess.

**Comment by msedi** [comment]
@zivkan. You may be right, that this is causes somewhere in my solution, the only problem I have is that I have two projects in the same folder structure (they are on the same level, herefore with the same access to all resources).

1. ipipe.Memory (NET7.0, regular project)
2. ipipe.DataCollection.SourceGeneration (NET-Standard, source generator library)

1.) works, but 2.) doesn't.

BUT, While testing I had a similar project that worked. It is also a source generator. 
In the source generator that doesn't work, I had the following line:

<ItemGroup>
  <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
</ItemGroup>

which is what is required to distribute the library as a source generator, the other (working) library didn't have it. So this line above causes the problem, which means something modifies the $(OutputPath) in the nuget build target?

Because this is what I set in the Directory.Build.props

```
<Project DefaultTargets="Build">
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))" />

	<PropertyGroup>
		<OutputPath>$(BuildRoot)\_Build\$(Configuration)\Assemblies\$(MSBuildProjectName)</OutputPath>
		<OutDir>$(OutputPath)</OutDir>
	</PropertyGroup>
</Project>
```

The MSBuild shows a heterogenous OutputPath, so the question is if there is something different with a .NET Standard project.

![image](https://github.com/NuGet/Home/assets/8020659/a22c2f41-4af4-4756-b7b3-46aec9c0e817)

**Comment by jeffkl** [comment]
@msedi I'm not able to reproduce your issue with a simple project.  Can try creating a simple repro and attaching a ZIP with the project that exhibits the behavior?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>$(MSBuildThisFileDirectory)\out\$(Configuration)\</OutputPath>
  </PropertyGroup>
</Project>

```

```
D:\Repros\pack-outputpath>dotnet pack
MSBuild version 17.8.0-preview-23418-03+0125fc9fb for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  pack-outputpath -> D:\Repros\pack-outputpath\out\Release\net8.0\pack-outputpath.dll
  The package pack-outputpath.1.0.0 is missing a readme. Go to https://aka.ms/nuget/authoring-best-practices/readme to learn why package readmes are important.
  Successfully created package 'D:\Repros\pack-outputpath\\out\Release\pack-outputpath.1.0.0.nupkg'.
```

**Comment by msedi** [comment]
@jeffkl. I have provided an example in the attached ZIP. It has exatcly the same structure as in my large solution only with two selected files where one works, the other one doesn't. As shown above if you call

`dotnet pack ipipe.DataCollections.SourceGeneration.csproj`

it shows the error

```
C:\Program Files\dotnet\sdk\8.0.100-rc.1.23455.8\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5
): error : Could not find a part of the path 'E:\_Build\Release\Assemblies\ipipe.DataCollections.SourceGeneration\netst
andard2.0\win-x64'. [E:\TFS\NugetProblem\Libraries\Core\DataCollectionMathGenerator\ipipe.DataCollections.SourceGenerat
ion.csproj]
```

whereas when calling `dotnet pack ipipe.Memory.csproj` it runs as expected.

[NugetProblem.zip](https://github.com/NuGet/Home/files/12668710/NugetProblem.zip)

**Comment by jeffkl** [comment]
@msedi The .NET SDK is appending the target framework and runtime identifier to your output path.  You'll need to set the following properties to disable the functionality:

```xml
<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

```

https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props#appendtargetframeworktooutputpath

**Comment by msedi** [comment]
@jeffkl. Thanks for looking into this. I'm aware of these two settings. I know both switches. The question is nevertheless, why does it behave differently in .NET7 vs .NET-Standard? Both projects are Sdk projects: `<Project Sdk="Microsoft.NET.Sdk">` the output is also not stored in some netstandard\Release (Framework\Runtime) folder. I couldn't find any specifics if there is a difference in the behavior of NET-Standard vs. NET7.

This obviously only happens for netstandard projects but seems to be a problem only for nuget. Publishing also works as expected for both projects.

By the way, I made a mistake in my demo project and you shouldn't have been able to compile it the right way. I have fixed it in the attached example. If you compile the indiviual projects you can see that both projects are compiled without the framework/runtime appendices. There is also no difference in Debug/Release mode.

[NugetProblem.zip](https://github.com/NuGet/Home/files/12675663/NugetProblem.zip)
