### ISSUE TITLE
Why is "Uninstalling" missing in Preview Window ?

### ISSUE THREAD

**Issue by Danielovich** [NuGet/Home#12887]
Nuget 6.7.0
VS Version 17.7.4

Two different devs experience to different things when trying to update the same packages. No clue why. 

One dev is experiencing some packages uninstalls (1), other dev is not (2). 

I have no idea how to debug this :/

1.
![image](https://github.com/NuGet/Home/assets/273661/fa82e1d3-9009-4bcf-931a-3312c2dc5be0)

2.
![image](https://github.com/NuGet/Home/assets/273661/189b1219-463b-4b59-9101-eb250b940046)

**Comment by jewi-dhi** [comment]
Can you try for Cleaning the solution/project. and probably better to delete bin and obj folder on those project folder.
And how about cleaning your nuget cache also.

**Comment by Danielovich** [comment]
Ended up deleting C:\Users\{userid}\AppData\Roaming\NuGet\nuget.config

And deleted all from C:\Users\{userid}\.nuget\packages

Works again.
