### ISSUE TITLE
Project.json restore removes the targets file

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1288]
1. file->new UWP class library
2. Add NuSpec.ReferenceGenerator 1.2.0 to the project.json
3. Build/rebuild.

On the second rebuild the projectName.nuget.targets file is deleted. The only way to get it back is to delete the project.lock.json file.

**Comment by yishaigalatzer** [comment]
CC // @onovotny

**Comment by emgarten** [comment]
NuGet/Nuget.packagemanagement@5584e2548e97d075e71049a382a80d2342b3d78d
nuget/nuget3@0b3ca109e8c5e63ac29cd8ed8b12d75199175d96
