### ISSUE TITLE
[Accessibility] The Vulnerabilities InfoBar link “Manage NuGet Packages” have two right-borders when focused on by Tab 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12892]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.8.0.115

### Impact

It bothers me. A fix would be nice

#### Repro Steps:     

1. Create a C# Console App (.Net core) project.     
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.   

3. Select the package source: “nuget.org” near the gear button.   

4. Go to the "Browse" tab and search for a vulnerable package (e.g. "Newtonsoft.Json").  

5. Select a vulnerable package version (e.g. 12.0.1) and click the “Install” button. 

6. Focus on the “Manage NuGet Packages” link by tab. 

   

#### Expected:   

The Vulnerabilities InfoBar link “Manage NuGet Packages” only has one right-border.   

#### Actual:      

The Vulnerabilities InfoBar link “Manage NuGet Packages” have two right-borders as below: 

![Screenshot 2023-09-21 024347](https://github.com/NuGet/Home/assets/84695155/79272f1a-794c-4063-976f-88be1ab0fe9c)

#### Note:  

1. The repro rate is 100%.      

2. This is not a regression, since it is a new feature change.

**Comment by nkolev92** [comment]
Team Triage: This seems to be an issue with the infobar, rather than NuGet's specific implementation. 

@v-luzh Can you please create the issue in AzureDevOps instead, so we can forward correctly.

**Comment by nkolev92** [comment]
This issue was moved to NuGet/Client.Engineering#2489
