### ISSUE TITLE
Push with a fully-qualified path on POSIX fails.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1289]
@dmccaffrey

When executing NuGet pack command using a fully-qualified path to the nupkg (such as Linux or Mac), NuGet is incorrectly assuming that the specified path is relative to the current directory.

For instance:

If pwd = /Volumes/Storage/Users/test/repos/nuget

dnx nuget.exe push "/Volumes/Storage/users/test/repos/nuget/packages/test.pkg" -Source "/Volumes/Storage/Users/test/.config/NuGet/packages"

fails with error message:

Directory '/Volumes/Storage/Users/test/repos/nuget/Volumes/Storage/Users/test/repos/nuget/packages' not found.

This issue has been moved from https://github.com/NuGet/NuGet.CommandLine/issues/11

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/886
