### ISSUE TITLE
[Question | Bug?] Restore fails to GeneratePathProperty or copy content to output directory if obj folder is missing

### ISSUE THREAD

**Issue by LostTime76** [NuGet/Home#12902]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

dotnet 8.1 RC

### Worked before?

Never tried

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

My project uses the dotnet CLI directly instead of using a standard C# project structure with the root project having a solution. Instead I have a parent msbuild project file that invokes child msbuild projects. Some of those child projects are C# projects and some are just generic build files not attached to a standard msbuild project type like C#. I happen to be using VSCode for development to invoke the command line.

Suffice it to say, the child C# projects are not committed to source control with their obj or bin folders and they contain package references. When somebody checks out the project, the intent is for the build to restore everything including the package references.

The C# project files are setup to perform a pre build nuget restore, which ends up generating the obj folder and the nuget packages are successfully restored globally. The issue I am having is that if the obj and bin folders are missing the first time a user does a build (or the user does a clean, because I have the clean target delete obj & bin), then the nuget restore only restores the packages and the obj folder for the project. If the package contains content that needs to be copied to the output directory on package restore, nuget does not perform the copy. If a second build is performed with the obj folder present from the previous restore, the package content is copied successfully to the output folder. This behavior seems to be the same for the GeneratePathProperty. The package reference path is only generated if the obj folder is already present on restore.

After some testing and digging, it just seems like nuget needs to take the extra step of completing its work if the obj folder is absent. If the obj folder is absent and a restore is performed, it is generating the obj folder, restoring the packages to the global .nuget folder but is stopping there. It should lastly perform the content copy. I think the .g.props file that is generated within the obj folder is controlling that content copy as it contains all the paths to the content to copy, it's just not being invoked when nuget has to firstly generate the file.

When the automatic copy on fresh restore failed, I tried using the GeneratePathProperty to manually execute an msbuild copy task to copy what I needed.. only to find out that it seems like the property is not generated unless obj (an .g.props) exists first. I need a way for the restore to work fully if the obj folder is absent on a fresh restore. If this comes from the built in copy or from me manually writing a copy task using GeneratePathProperty, it doesn't matter, I just need one or both to work.

The overall issue is that it is a bad omen to tell users of my project that they need to restore / build the project twice whenever they firstly clone the project or do a full clean. I think this has been mentioned elsewhere in the forum, but nuget restore should work fully from a fresh restore (no obj or bin folders). Saying that the built in msbuild clean target never touches the obj folder or the obj folder is restored by VSCode / Visual Studio with "normal" solution project structures, is not very valid. A clean should wipe out everything (the entire cache which includes the obj folder) and start from a fresh slate.

**Comment by nkolev92** [comment]
Hey @LostTime76, 

Thanks for filing this issue. 
This is the nature of the beast with NuGet. Restore cannot affect restore. 

The properties generated via GeneratePathProperty are only available *after* restore has happened, as they are dependent on restore. It is impossible for them to be available any earlier.
