### ISSUE TITLE
PackageBuilder does not seem to ever write the <files> tag. Intended?

### ISSUE THREAD

**Issue by hemisphera** [NuGet/Home#12904]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Protocol 6.7.0

### Worked before?

Cant' say

### Impact

Other

### Repro Steps & Context

When using the `NuGet.Packaging.PackageBuilder` class to construct a package, the **files** tag never seems to be written to the manifest.

I looked into the source code and the place where the manifest is written in `WriteManifest` uses the `NuGet.Packaging.Manifest.Create` method to create the manifest. That static method is calling the constructor of the class without passing the parameter `files`. Therefore, the manifest never gets any files passed and PackageBuilder never writes them to the manifest.
Is this intended?

**Comment by nkolev92** [comment]
That is expected. The resulting nuspec inside the package does not contain the files element. The files element is only used to "author" the package, it's not part of the final nuspec.
