### ISSUE TITLE
Help Us Improve Our Open Source Repositories!

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#12917]
We'd love to hear from those of you who participate often in our open source project and let us know how we're doing as maintainers.

Whether you've been involved for a while now or you're relatively new to open source, please let us know about your experience by [taking a survey that will take a couple minutes](https://www.surveymonkey.com/r/BMMSK9F).

Thank you kindly!

**Comment by danmoseley** [comment]
Hey, only a couple responses so far -- the survey will be open for a while longer. The mean time to complete the survey is less than one minute. you can do it without typing anything!

In case anyone's interested, here's results for some other repos who did the same survey.

https://github.com/dotnet/wpf/issues/8243#issuecomment-1744737592
https://github.com/dotnet/runtime/issues/92378#issuecomment-1743592545
https://github.com/dotnet/aspnetcore/issues/50850#issuecomment-1743899131
results for maui should be up soon.
