### ISSUE TITLE
Unexpected increase of Updates() when installing prelease packages.

### ISSUE THREAD

**Issue by meokullu** [NuGet/Home#12911]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

6.7.0.127

### Worked before?

No

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. install a prelease package..
2. look for updates() tab.

**Comment by nkolev92** [comment]
Hey @meokullu 

Can you please provide more information. 
What do you see on the updates tab vs what you expect to see?
Screenshots would be great.

**Comment by meokullu** [comment]
Hey @nkolev92

When installing prelease packages with certain name like "EasySaver", Updates tab is also searching for updates of packages with prelease option. When you tap on Updates tab, there might be no result, since "EasySaver" is using to search but, Updates tab badge count is searching without any specified name. That would be better to  remove package name when you change tab, so people can see what are the updates or Update tab "prelease check" shouldn't be sharing a value with Browse or Installed tabs.

![NuGet](https://github.com/NuGet/Home/assets/4971757/4449a0af-e1a0-418a-9055-2d4e1f50bc0e)
![Screenshot 2023-09-29 200243](https://github.com/NuGet/Home/assets/4971757/d77e1840-7fc4-4b60-a47a-4ee10da92eb7)

I couldn't find source code of this certain section to take a look. I wanted to look for the code and suggest to change/fix it if it is neccessary.
Take care.

**Comment by nkolev92** [comment]
Just confirming I understood the feedback. 

- Updates tab # is independent of what's been searched. 
  - I think this is by design. It's calculating how many overall updates there are. I don't think we're likely to change that since we haven't gotten a lot of feedback.
- Make the search term not sticky. 

Is that correct? Did I miss anything else?

**Comment by meokullu** [comment]
Sorry for delay.

If it is working like that as a design, it is all right. I just thought it could create a confusion, since number shows search result and while there is already no result, showing numbers could be misleading.

I am sorry for delay again, take care.

**Comment by nkolev92** [comment]
thanks for the response @meokullu
