### ISSUE TITLE
Feedback for package source mapping: multiple package source elements with same key but different patterns

### ISSUE THREAD

**Issue by WhitWaldo** [NuGet/Home#12913]
### NuGet Product(s) Affected

NuGet.exe

### Current Behavior

I was just setting up the package source mapping, having learned about it in a random survey VS invited me to the other day. I read from the blog post that precedence rules would be applied for specific values down to wildcards so I thought hey, that's neat. I can specify NuGet as a catch-all and then specify some more specific patterns that also apply to NuGet.  That way if I ever want to change the source, the block is already there and just needs a key change.

I had tried doing this:
```xml
<packageSourceMapping>
  <packageSource key="nuget">
    <package pattern="**"/>
  </packageSource>
  <packageSource key="nuget">
    <package pattern="Microsoft.*"/>
  </packageSource>
</packageSourceMapping>
```

I saved the file and immediately Visual Studio locked up with the following error:
> NuGet operation failed
> PackageSourceMapping is enabled and there are multiple package sources associated with the same key(s) (and then a path to the file)

### Desired Behavior

A gold error bar should show up in Visual Studio calling out the issue, but it absolutely shouldn't require one to crash VS and re-open it due to it being perpetually non-responsive from that moment on. In the alternative, just show a red squiggly in the XML document as though I had a syntax error. Either way, it shouldn't break VS.

Further, I think it should allow such an entry. In keeping with the precedence rules indicated, it would simply find a pattern match for the package as before and the key should serve as a reference back to the specific package source, not as a unique identifier for that element.

### Additional Context

Today, it's legal to simply have:

```xml
<packageSource key="nuget">
  <package pattern="*" />
  <package pattern="Microsoft.*"/>
</packageSource>
```

I'm simply proposing that this should be legal as well to represent the same thing.

```xml
<packageSource key="nuget">
  <package pattern="*" />
</packageSource>
<packageSource key="nuget">
  <package pattern="Microsoft.*"/>
</packageSource>
```

Thank you for the consideration!

**Comment by nkolev92** [comment]
Related: https://github.com/NuGet/Home/issues/12245 The invalid config behavior is not specific to source mapping related issues, it's the same for every config issue.

**Comment by nkolev92** [comment]
Team Triage: The validation for duplicate keys was added intentionally, https://github.com/NuGet/Home/issues/11573. 
We believe that the mappings should be self-contained within 1 file.

Regarding the Visual Studio handling of config issues, please upvote https://github.com/NuGet/Home/issues/12245.
