### ISSUE TITLE
Update documentation for NU1011 error indicating how to allow floating versions with central package management

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#12919]
As part of https://github.com/NuGet/NuGet.Client/pull/5440 we'll be allowing users to enable floating versions with central package management (CPM).  We'll need to update the documentation for the NU1011 error to explain how to enable the functionality since it will remain off by default.  

https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1011.md

Proposed wording:

### Solution
NuGet recommends not using floating versions with central package management and instead encourages users change the floating versions to a [non floating version range](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/concepts/Package-Versioning.md#version-ranges).

If changing to non floating versions is not possible, users can enable the functionality by setting the MSBuild property `CentralPackageFloatingVersionsEnabled` to `true` in an individual project or a common import like [Directory.Build.props](https://learn.microsoft.com/visualstudio/msbuild/customize-by-directory#directorybuildprops-and-directorybuildtargets):

```xml
<PropertyGroup>
  <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
</PropertyGroup>
```

***NOTE: The use of floating versions can introduce non-deterministic NuGet restores as described above and is not recommended.***

**Comment by boylec** [comment]
Yeah this is important, I just wasted many hours due to being misled by the doc here.

**Comment by voroninp** [comment]
Btw, is this recommendation still relevant if `packages.lock.json` file is enabled with:
```
<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
```
