### ISSUE TITLE
Nothing is working correctly anymore and I made no changes. 

### ISSUE THREAD

**Issue by EdLichtman** [NuGet/Home#12923]
### NuGet Product Used

dotnet.exe, Other/NA

### Product Version

.NET SDK:  Version:   7.0.400  Commit:    73bf45718d  Runtime Environment:  OS Name:     Windows  OS Version:  10.0.17763  OS Platform: Windows  RID:         win10-x64  Base Path:   C:\Program Files\dotnet\sdk\7.0.400\  Host:   Version:      7.0.10   Architecture: x64   Commit:       a6dbb800a4  .NET SDKs installed:   1.1.14 [C:\Program Files\dotnet\sdk]   6.0.408 [C:\Program Files\dotnet\sdk]   7.0.400 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]   Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]   Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]   Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Other architectures found:   x86   [C:\Program Files (x86)\dotnet]     registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]  Environment variables:   Not set  global.json file:   Not found  Learn more:   https://aka.ms/dotnet/info  Download .NET:   https://aka.ms/dotnet/download

### Worked before?

Yes it worked before. I have no idea what changed. I didn't seem to download a version, so I wonder if my machine was automatically patched?

### Impact

It's astronomically more difficult to complete my work, everything that packaged up nicely with a bow just stopped working.

### Repro Steps & Context

Context:
It was working fine and dandy before, and all of a sudden, today I ran into an Error, which was thrown because I TreatWarningsAsErrors. So as far as I know, I didn't do any upgrades, or anything. 

Here's what I'm doing:
I'm building a convention and uniform library solution, in which I have "Assembly Annotations" that help dictate things.

Some examples of what the convention and configuration does:
* if a package has the "MyAssemblyType" of "PackageAssembly", then msbuild will create a new Attribute called "PackageAssemblyIntroAttribute" that includes "Id" and "Version".
* if it's a PackageAssembly, then the Author is me.
* Includes custom targets

So what happened:
* I'm now getting warnings and errors out the wazoo which is incredibly breaking for my workflow, since I need to either turn off TreatWarningsAsErrors, or individually address each one. Most of which I've seen so far don't even make any sense.

For example, the base Assembly Annotations library, it has been stable and untouched for the last month. I ran into an issue today and decided to run "dotnet pack" against it, and get the following:

```
C:\Program Files\dotnet\sdk\7.0.400\Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277: Found conflicts between different versions of "System.Collections.Immutable" that could not be resolved. [C:\Source\core-nuget-host\AssemblyAnn
otations\src\My.AssemblyAnnotations.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.400\Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277: There was a conflict between "System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Collecti
ons.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". [C:\Source\core-nuget-host\AssemblyAnnotations\src\My.AssemblyAnnotations.csproj::TargetFramework=netstandard2.0]
C:\Program Files\dotnet\sdk\7.0.400\Microsoft.Common.CurrentVersion.targets(2364,5): warning MSB3277:     "System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System
.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not. [C:\Source\core-nuget-host\AssemblyAnnotations\src\My.AssemblyAnnotations.csproj::TargetFramework=netstandard2.0]
```
So I tried to create one single library, with one project, and one props file:

```
props/My.Microservice.Builder.Analyzers.props
My.Microservice.Builder.Analyzers.csproj
```
The Props File is empty (<Project></Project>)
Inside the Csproj I have this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  
    <TargetFramework>net6.0</TargetFramework>
    <Description>asdfsdf</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency -->
    <!-- For NU5128 (Since net6.0 is the Framework, but there is no lib/ref directory -->
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <NoPackageAnalysis>true</NoPackageAnalysis>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>



  <ItemGroup>
    <None Include="**\My.Microservice.Builder.Analyzers.props" Pack="true" PackagePath="/build/" Visible="true"/>
  </ItemGroup>
</Project>

```

And when I run dotnet pack, I get this error:

C:\Program Files\dotnet\sdk\7.0.400\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(221,5): error NU50
17: Cannot create a package that has no dependencies nor content. [C:\Source\sandbox\testnamepackagelength\src\My.Micro
service.Builder.Analyzers.csproj]

The thing about it is, the combination of 
```    
   <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
```
has historically suppressed NU5017.

In addition, under a random condition that I can't put my finger on that same project will tell me that "it found a "props" file, but the props file didn't match the "My.Microservice.Builder.Analyzers.props" required name

**Comment by EdLichtman** [comment]
Well, I figured out through another library that part of it has to do with a bug where if you have one props in a build folder, and another props in a buildTransitive, and the one in the buildTransitive doesn't match the name, then you have a problem...

**Comment by donnie-msft** [comment]
Hello,
Glad you found the issue. The naming must match and it's documented here: https://learn.microsoft.com/en-us/nuget/concepts/msbuild-props-and-targets. If the names are matching and you still see a problem, let us know. Thanks!
