### ISSUE TITLE
Central Package Management causes Downgrade errors (NU1109) in non-SDK projects

### ISSUE THREAD

**Issue by gliljas** [NuGet/Home#12920]
### NuGet Product Used

Other/NA

### Product Version

Visual Studio 17.7

### Impact

It's more difficult to complete my work

### Repro Steps & Context

When changing versions in Directory.Packages.props, non-SDK projects often end up giving NU1109 errors, even though they of course should use the package version just specified. It seems they maintain the previous version used in some kind of cache, and the only way to get around it is to restart VS.

A solution or guidance would be much appreciated.

**Comment by Nigusu-Allehu** [comment]
Thank you for bringing this to our attention. I have tried to reproduce the bug by the following steps.
- New solution
- add a non-SDK project to the solution
- create `Directory.Packages.props` at the root of the repo
- I used the PMUI to install a package to the non-SDK project
- And added the package version to the `Directory.Packages.props` file. 
- Following this I changed the version specified. 
However, this did not produce the error you specified. I was wondering if you could please provide with a detailed set of repro steps. Thank you!

**Comment by gliljas** [comment]
Thanks you for your quick response. I'm trying to create a small reproducing solution, but it seems tricky. Yet, in our real solution, it's completely reproducable. Will keep trying.

**Comment by woutervanranst** [comment]
![Image](https://github.com/user-attachments/assets/b20eb6af-f371-4d52-bac2-61470b7280a9)
