### ISSUE TITLE
automatic package restore to run init.ps1 scripts after restoring

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1292]
@MarkusWild

Hi,

I have seen this issue already on codeplex but it seems to be lost or abandoned. Are there any activities around running init.ps1on Package restore?

Are there reasons not to do it?

Markus

This issue has been moved from https://github.com/NuGet/NuGet.CommandLine/issues/19

**Comment by yishaigalatzer** [comment]
This is not related to the command line. It is now being done for project.json scenarios.

@deepakaravindr please verify the current state.

**Comment by yishaigalatzer** [comment]
Scenario:

Open a solution with EF but no packages are restored
Open PS console - Verify no EF commands are available
Restore
Should EF commands be available? This bug suggests that they should.

**Comment by natemcmaster** [comment]
@rrelyea @yishaigalatzer can we have someone look into this, especially for .NET Core projects? We're seeing behavior in 3.4.4 and.NET Core RC2 projects that is inconsistent with NuGet 2/package.config.

Possibly related: we're also seeing that this behavior is buggy if a package in "tools" only.

**Comment by yishaigalatzer** [comment]
Nate please open a new bug with repro steps and details

**Comment by sancho2412** [comment]
Are there some updates when this bug will be fixed? It's the only showstopper to use NuGet in our company :(

**Comment by yishaigalatzer** [comment]
@sancho2412 can you do a couple of things
1. Try 3.5-RC and see if it resolves your issues?
2. Describe exactly what is broken for you. Can you list the exact steps that leave your broken?

**Comment by joelverhagen** [comment]
Spoke to @rrelyea during stand-up, this is an invasive change with some risk. Moving to 3.6 beta2.

**Comment by mcmellawatt** [comment]
Any updates on this?  We have logic that needs to be executed on package restore as well, and it is not intuitively obvious that the workaround is to close/reopen the solution so init.ps1 gets called.  I'd even be happy if there was a separate restore.ps1 that I can duplicate the logic in, if it is less invasive.  Right now we are just struggling to use these NuGet package lifecycle scripts in any reliable way.

**Comment by nkolev92** [comment]
@mcmellawatt 

init.ps1 scripts are executed when installing a package and when launching VS. 

Allowing the user to act during restore caused major performance and reproduciblity issues for consumers. 
Currently there are no plans to support such a scenario. 

We don't believe there are enough scenarios where a package needs to do something at restore time to allow add a feature like this. 

In our experience most of the time, packages need to affect build and authors can already do it by using targets. 
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package

Please look into these and do let us know if you need more help with your scenario.
