### ISSUE TITLE
[Localization][JPN] The string "Readme” is not localized on the package details panel  

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#12928]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.8.0.122

### Impact

It bothers me. A fix would be nice

#### Installation:
1.Create a clean VM with loc OS: Windows-11-Enterprise-22H2-JA-JP.
2.Install VS D17.8\34205.153 from: [Pipelines - Run rel.d17.8-34205.153 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D8497505%26view%3Dresults&data=05%7C01%7Cv-luzh%40microsoft.com%7C9ee80318e2ae49f7d77208dbc6057aa9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321499433963834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X2sM0FoniQiuAfH%2FKHWyidhtRMGQMnQQ%2BtJ6s3xxFPU%3D&reserved=0) with loc language pack JPN.
 
#### Repro Steps:
1.Create a C# Console App (.NET Core 8.0) in VS after setting a loc language JPN through menu “Tools->Options->Environment->International Settings->Language”.
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.  
3. Search a package (such as “Newtonsoft.json”) on “Browse” tab.
4. Observe the “Readme” in the package description on the package details panel.

#### Expected: 
The string “Readme” should be localized.

#### Actual: 
The string "Readme” is not localized as below screenshot.
![image](https://github.com/NuGet/Home/assets/40230425/89216bd4-b2cd-4256-8031-e494e4770491)
#### Note:
1. The issue is only repro on JAP language, it doesn’t repro on other loc languages.
2. It is not a regression issue since it reproes on 17.6 (D17.6\33712.159).

**Comment by donnie-msft** [comment]
@v-longmin I see this also repros on 17.8 preview 2. If it's only for one language, I wonder if the English word is typically used. Can we ask the localization vendor team about this? If you're not familiar with contacting the loc team, then I can do that, just let me know.

**Comment by v-longmin** [comment]
@donnie-msft  Yes, the string "Readme" is not localized only repro on JAP language, we will try to file feedback to localization team, if we encounter problem，we will let you know via email or comments. Thanks a lot!

**Comment by v-luzh** [comment]
Link this issue to internal feedback [914514](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/914514).

**Comment by v-luzh** [comment]
This bug is tracked by another feedback: [925749](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/925749?src=WorkItemMention&src-action=artifact_link) which is just fixed on NuGet Dev\6.9.0.39. I will close this issue as resolution:fixed.
