### ISSUE TITLE
[Localization] The filter “show only vulnerable” on “Installed” tab is not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12927]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.8.0.122

### Impact

It bothers me. A fix would be nice

#### Installation:
1.Create a clean VM with loc OS (such as Windows-11-Enterprise-22H2-FR-FR)
2.Install VS D17.8\34205.153 from: [Pipelines - Run rel.d17.8-34205.153 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D8497505%26view%3Dresults&data=05%7C01%7Cv-luzh%40microsoft.com%7C9ee80318e2ae49f7d77208dbc6057aa9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321499433963834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X2sM0FoniQiuAfH%2FKHWyidhtRMGQMnQQ%2BtJ6s3xxFPU%3D&reserved=0) with loc language pack (such as FRA)

#### Repro Steps:
1.Create a C# Console App (.NET Core 8.0) in VS after setting a loc language (such as FRA) through menu “Tools->Options->Environment->International Settings->Language”.
2.Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3.Click the “Installed” tab and observe the filter “show only vulnerable”.

#### Expected:
The filter “show only vulnerable” on “Installed” tab should be localized correctly in all local languages.
#### Actual:
The filter “show only vulnerable” on “Installed” tab is not localized as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/7af036ee-da82-4462-bffa-f305b080ba8e)

#### Notes:
1.It also repro on solution-level PM UI.
2.It reproes on all local languages: CSY, CHS, CHT, DEU, ESN, FRA, RUS, KOR, ITA, JPN, TRK, PTB, PLK.
3.It’s not a regression since it is a new feature.

**Comment by donnie-msft** [comment]
@v-luzh I see a localized string here for JPN language in Version 17.9.0 Preview 1.0 [34208.28.main].
Could you check again and let me know if it persists?
![image](https://github.com/NuGet/Home/assets/49205731/f81c7eb2-a6f5-403b-a6e4-a833304a5c1a)

**Comment by v-luzh** [comment]
Hi @donnie-msft, thanks for your confirmation. Yes, you are right. This issue doesn't repro on Main\34209.49. I will close this bug.
