### ISSUE TITLE
[Localization][CHS] The string “skip applying binding redirects” on Options window is localized incorrectly

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#12929]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.8.0.122

### Impact

It bothers me. A fix would be nice

#### Installation:
1.Create a clean VM with loc OS: Windows-11-Enterprise-22H2-ZH-CN
2.Install VS D17.8\34205.153 from: [Pipelines - Run rel.d17.8-34205.153 (visualstudio.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevdiv.visualstudio.com%2FDevDiv%2F_build%2Fresults%3FbuildId%3D8497505%26view%3Dresults&data=05%7C01%7Cv-luzh%40microsoft.com%7C9ee80318e2ae49f7d77208dbc6057aa9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638321499433963834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X2sM0FoniQiuAfH%2FKHWyidhtRMGQMnQQ%2BtJ6s3xxFPU%3D&reserved=0) with loc language pack CHS

#### Repro Steps:
1.Create a C# Console App (.NET Core 8.0) in VS after setting a loc language CHS through menu “Tools->Options->Environment->International Settings->Language”.
2.Right-Click the project in the Solution Explorer window and select ‘Manage NuGet Packages…’.
3.Click the settings (gear) button and observe the string “skip applying binding redirects” on Options->NuGet Package Manager->General dialog.

#### Expected:
The string “skip applying binding redirects” should be localized as “跳过应用绑定重定向”.
#### Actual:
The string “skip applying binding redirects” on Options window is localized incorrectly into “跳过应用和绑定重定向” as below.
![image](https://github.com/NuGet/Home/assets/20632625/ca3a782c-b87b-4ff7-8cb9-6ca25f1bf236)
#### Notes:
1.It only reproes on CHS.
2.It's not a regression issue since it also reproes on 17.6 (D17.6\33712.159).

**Comment by donnie-msft** [comment]
@v-luzh it's awesome that you're helping find loc bugs! The NuGet team isn't responsible for translation, so we would need to file a bug with the localization team. If you can do that, please let me know, and if not, I'll file the bug and use this one as a tracking issue. Thanks!

**Comment by v-luzh** [comment]
Hi @donnie-msft, thanks for your reminder. Linked this issue to the feedback [914519](https://dev.azure.com/ceapex/CEINTL/_workitems/edit/914519).

**Comment by jeffkl** [comment]
Team Review: @v-luzh please watch the internal tracking issue and close this issue once you've verified the fix.

**Comment by v-luzh** [comment]
Hi @jeffkl, this bug is fixed on VS Main\34216.159. Close this issue with resolution: fixed.
