### ISSUE TITLE
Unable to update all packages only from given source

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#1293]
Calling the following command:

```
Update-Packages -Source MyGet
```

Causes an error:

```
Update-Package : Package 'AutoMapper' is not found
At line:1 char:1
+ Update-Package -Source MyGet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

What is expected since this a nuget.org package, not from the private feed.

**Comment by johnataylor** [comment]
#1181

**Comment by yishaigalatzer** [comment]
We would like to control Update operation from the UI with two controls
1. What version to update the selected packages to
2. How to treat dependencies.

This needs another UI discussion.

We also think that the right pane should drop some of the controls when multiple packages are selected for update (many of the controls are irrelevant)

We also want to add back the release notes field

cc @csharpfritz
