### ISSUE TITLE
Ability to pull a NuGet package and all of its dependencies into a single directory using the command-line

### ISSUE THREAD

**Issue by Pxtl** [NuGet/Home#12938]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

Nuget does a great job of pulling down packages and all their dependencies.  But the form it brings them down leaves actually putting them together into a usable directory as an out-of-scope problem.  If you're working on C# source-code, this is fine.  But if you're trying to handle an .exe that lives in a nuget package, or if you're trying to access a nuget package in Powershell or CSX script, you can't actually load it because its dependencies are outside of the module search path.  These are the cases when I *want* to use `nuget.exe` - if I just wanted the raw packages folders, I'd use normal `csproj` stuff where the compiler would handle putting together my bin folder for me.  If I'm using `nuget.exe`, I'm already trying to get stuff from nuget so I can *hack* with it.

So, a proposal, call it "nuget deploy".  As in 

```ps
nuget deploy mypackagename -OutputDirectory ./packages -DeployDirectory ./bin -Framework netcore

Add-Type -path './bin/myPackageName.dll'
[MyPackageClass]::StaticHelloWorld()
```

This is a pretty straightforward use of Nuget.exe, and yet the amount of code it requires is very very non-trivial.  See the Tolstoy at https://stackoverflow.com/questions/39257572/loading-assemblies-from-nuget-packages

### Additional Context and Details

Detailed example.

Currently, if I do this:

```ps
nuget install Microsoft.Data.Tools.Msbuild -o ./packages
```

I get MsBuild and all its dependencies in `./packages`.  Which is great!  But if I try to use the copy of `SqlPackage.exe` that lives in there, I get the following:

```
> .\packages\Microsoft.Data.Tools.Msbuild.16.0.62004.28040\lib\net46\SqlPackage.exe

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.Tools.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.Main(String[] args)
```

which is sad.  I have the file, I have the dependencies, it's just I have to put them together myself.

```
mkdir bin -Force
cp packages/*/lib/net46/* bin -Force

```

and then try it:

```
> .\bin\SqlPackage.exe | select-object -First 3 # we don't want the whole help doc
SqlPackage: Command-line tool for creating and deploying SQL Server databases and DACPAC packages.
Copyright (c) 2016 Microsoft Corporation.  All rights reserved.

```

So it works if you're willing to deploy the files out of the packages folder yourself.  Nuget being able to help with this would be fantastic.

dotnet.exe offers a similar service in `dotnet tool install` but it only allows things that are flagged as *tools*, and is very netcore oriented and so doesn't really work well with old framework things like nuget.exe does.

```
> dotnet tool install Microsoft.Data.Tools.Msbuild --tool-path ./bin

C:\Users\zaratem\AppData\Local\Temp\fc86e76c-4d47-498e-8a10-e120aaaa7ea3\restore.csproj : error NU1212: Invalid project-package combination for Microsoft.Data.Tools.Msbuild 16.0.62004.28040. DotnetToolReference project style
 can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'microsoft.data.tools.msbuild' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

but for anything else, `dotnet tool install` does what we'd expect - it dumps the files I want to play with in the `bin` folder with all their dependencies where it needs them for when it's loaded into memory.

**Comment by nkolev92** [comment]
@Pxtl It's worth noting that for `dotnet tool install`, *all* of the assemblies are part of that package, there's no stitching for dependencies anywhere, it's the responsibility of the package author.

**Comment by nkolev92** [comment]
Team Triage: 

As a package manager, NuGet's responsibility is primarily around resolving the graph for a particular project and together with the build, if you have a runnable project, they'd help bring in the compatible dependencies in a publish directory. 

Running exes from packages is beyond that scope. 

It's worth noting that for `dotnet tool install`, *all* of the assemblies are part of that package, there's no stitching for dependencies anywhere, it's the responsibility of the package author. 

As such we don't think this fits within the scope of NuGet's responsibilities.
