### ISSUE TITLE
VS restores incorrect packages when project.json in same directory as csproj

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#1294]
I have this directory structure:

-/Src
--App.Net45.sln
--App.Net40.sln
--/App
---App.Net45.csproj
---App.Net40.csproj
---project.json
--/App.Tests
---App.Tests.Net45.csproj
---App.Tests.Net40.csproj
---project.json

The project.json file has a .NET Core framework designed so I can test that environment.

When I have App.Net45.sln open and I build, VS + NuGet sees project.json and restores for it. Because of that I added framework targets for net45 and net40 to project.json with correct dependencies. The problem is VS + NuGet for some reason also restores the .NET Core framework when building .NET 4.5 and that throws up a modal message box that takes 10 seconds to disappear for EVERY build. This is super annoying. Please stop being annoying.

If VS + NuGet is going to use the project.json file in this directory, it should only restore packages for the building application's framework.

![image](https://cloud.githubusercontent.com/assets/303201/9565266/088bf8ec-4f19-11e5-8709-f733fa38499f.png)

**Comment by JamesNK** [comment]
I think there are two bugs here.

First is that DNXCore packages are being restored
The second is it happens every single time

**Comment by yishaigalatzer** [comment]
There is no good story to mix project.json for multiple projects. We have a fix that will enable creating `{projectName}.project.json` per project so you can separate the concerns properly.

This should be released at some point in September.

Similarly restoring everytime was enhanced in the 3.2 release, and should not happen on every build (but yes on every rebuild).

**Comment by JamesNK** [comment]
So csproj projects will look for {projectName}.project.json **instead of** project.json?

What happens if I still have a project.json in the directory? (for dnx) Will it now be ignored or will I need to create a {projectName}.project.json to get NuGet to use that instead?

**Comment by JamesNK** [comment]
A user has also reported this error caused by the csproj project using project.json - https://github.com/JamesNK/Newtonsoft.Json/issues/639

**Comment by yishaigalatzer** [comment]
I don't think you will be able to mix dnx and csproj and packages.config together but you can do two of the three.

Cc @davidfowl

**Comment by JamesNK** [comment]
I'm happy with ditching packages.config and moving to {projectName}.project.json, I just need a way for the csproj to stop picking up project.json in VS and creating problems like the ones above.

Do you understand what I'm getting at?

**Comment by JamesNK** [comment]
-/Src
--App.Net45.sln
--App.Net40.sln
--/App
---App.Net45.csproj
---App.Net45.project.json
---App.Net40.csproj
---App.Net40.project.json
---project.json
--/App.Tests
---App.Tests.Net45.csproj
---App.Tests.Net45.project.json
---App.Tests.Net40.csproj
---App.Tests.Net40.project.json
---project.json

So with this file structure, when App.Net45.sln is open, will VS completely ignore the two project.json's and use the {projectName}.project.json's instead?

**Comment by yishaigalatzer** [comment]
yes it should do that, I didn't see the final piece of code from @pilchie that makes msbuild pick up the right things. We can probably put privates in your hands to verify it before we ship.

**Comment by JamesNK** [comment]
Ok!

You can also test yourself by cloning Newtonsoft.Json, adding a Newtonsoft.Json.project.json and Newtonsoft.Json.Tests.project.json and seeing what happens when you build Newtonsoft.Json.sln and use the NuGet UI inside VS2015.

**Comment by yishaigalatzer** [comment]
We tested as you suggested, and it works :). The bits from managed languages will go live in Sep. You can reach out to @pilchie to see if you can get preview bits. (I'll do the same)

**Comment by dmitriyse** [comment]
Possible solution for this problem https://github.com/NuGet/Home/issues/3207
