### ISSUE TITLE
RestoreTask: Control whether to embed files in the binlog

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#12957]
### NuGet Product(s) Involved

NuGet.exe, MSBuild.exe, dotnet.exe

### The Elevator Pitch

Need some properties on RestoreTask to control whether to embed files in the binlog, and possibly filter out .dgspec.json files.

We've found that the embedded .nuget.dgspec.json files are huge, and our binlog is 1 GB in size. .dgspec.json files total 3.5 GB for us uncompressed. Would be nice to be able to control whether to include .dgspec files here:

https://github.com/NuGet/NuGet.Client/blob/5ce332fb834feea1f6c974d17456c8c9d5504e09/src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs#L216

Not sure how fine grained to make it. Just one property on the task to embed dgspec files, default to true? (No effect if no binlog present). Or 4 properties to control each of the four types of files? Or a main property to control all files?

Embedding files is useful and a good default, but for large builds embedding dgspec file specifically renders the binlog almost unusable.

**Comment by KirillOsenkov** [comment]
@jeffkl

**Comment by KirillOsenkov** [comment]
I tried a workaround like this:

```msbuild
  <Target Name="ExcludeDGSpecFromBinlog" AfterTargets="Restore">
    <ItemGroup>
      <EmbedInBinlog Remove="@(EmbedInBinlog)" Condition="$([System.String]::new('%(Filename)').EndsWith('.nuget.dgspec'))"/>
    </ItemGroup>
  </Target>
```

but it didn't work, because BinaryLogger observes EmbedInBinlog items as soon as they're logged, so removing them after the RestoreTask is done is too late.

**Comment by kartheekp-ms** [comment]
I am certainly not an expert in MSBuild binary log functionality. However, upon examining the [implementation](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs#L202-L205), it appears that if the `MSBUILDBINARYLOGGERENABLED` environment variable is set to false, then no files will be embedded in the MSBuild binary log. Does that work for your scenario?

**Comment by KirillOsenkov** [comment]
No, because I still need the environment variable for other scenarios (not just NuGet). Also, I do want to see most of the NuGet files embedded. I want to be able to turn off the dgspec ones.

**Comment by KirillOsenkov** [comment]
If we build with `/bl:ProjectImports=ZipFile` turns out 2/3 of it is dgspec files:

<img width="686" alt="image" src="https://github.com/NuGet/Home/assets/679326/4e62474a-8057-4c88-ac6e-081ec72ed80d">

**Comment by jeffkl** [comment]
@KirillOsenkov I'm thinking of a few options here:

1. Add a property that users can set to opt out of any files being embedded by NuGet
2. Add the items to an initial item group that then runs another target that the user can use to filter out items before they're logged
3. A special property with values specifying which items NuGet should embed with something like `AssetsFile;DGSpec;PropsAndTargets` where the user would sort of be able to tweak which ones are embedded

From the NuGet team's perspective, having the DG spec is very useful.  But if users don't need it, I think its reasonable to have a way to turn it off.  What are your thoughts?

**Comment by KirillOsenkov** [comment]
I'm thinking 3 is best, a special property seems simple enough and also extensible.

Make an enum and allow setting the property on the task to one of the enum values (and TryParse it maybe or something).

Default it to `All` (current behavior), but also allow `None` (embed nothing), and also turn individual parts off (`NoDGSpec`, `NoAssetsFile`, `NoPropsAndTargets` etc). I anticipate that All, None and NoDGSpec will really be the only usages, and very infrequent at that. It's better to have options to turn one thing off, instead of turning all-but-one things on (because we might want to add more stuff in the future).

Or we could have two properties, `IncludeFilesInBinlog` and `ExcludeFilesFromBinlog`, and if we want to turn DGSpec off, we set ExcludeFilesFromBinlog to `DGSpec`. If we want to only include Assets file, we set `IncludeFilesInBinlog` to `AssetsFile`. If we want to include Assets and propsandtargets, we set `IncludeFilesInBinlog` to `AssetsFile;PropsAndTargets`. If neither are set, default to All and include all. Set `ExcludeFilesFromBinlog` to `All` to exclude all.

We'd love to have DG specs too, but for us it increases the binlog from 350 MB to 900 MB. If we need it, we can turn it back on for specific project(s) that we care about, or trigger a one-off build with this property set. This is where a simple property would shine, because we could just `msbuild /bl /p:ExcludeFilesFromBinlog=DGSpec` or something.

And of course if the binlog environment variable not set, don't embed any files and ignore the property.

**Comment by jeffkl** [comment]
Okay I'll try to get to this in the coming weeks.

**Comment by KirillOsenkov** [comment]
I thought about the design some more and I think we should just add 5 more properties on the RestoreTask and RestoreTaskEx.

BinlogEmbedPackagesConfig
BinlogEmbedProjectAssetsJson
BinlogEmbedDGSpec
BinlogEmbedProps
BinlogEmbedTargets

Have one or two properties with custom syntax would be confusing I think. And with this design I could just set BinlogEmbedDGSpec to false and be done. They'd all default to true.

A bit worried about adding 5 properties, feels like it might clutter?

Maybe just add BinlogEmbedDGSpec or EmbedDGSpecInBinlog for now? We could still add the others later if needed.

**Comment by KirillOsenkov** [comment]
Yeah, maybe just add `EmbedDGSpecInBinlog` for now, default it to true. 

Would unblock me and the rest can be added later if needed. Props and Targets are kinda small, and if we want to turn off project.assets.json, might as well turn the whole thing off.

Oh, maybe we do need to also have `EmbedAllFilesInBinlog` too, to be able to turn everything off.

**Comment by KirillOsenkov** [comment]
Here's what I'm thinking:
https://github.com/NuGet/NuGet.Client/pull/5494

**Comment by KirillOsenkov** [comment]
@jeffkl @nkolev92 FYI draft PR above ^^^

**Comment by KirillOsenkov** [comment]
Would be super nice to prioritize _some_ fix for this.
