### ISSUE TITLE
NuGet.Core - Version 2.8.8 not available

### ISSUE THREAD

**Issue by punitganshani** [NuGet/Home#1295]
In the NuGet build repository, the package `NuGet.Protocol.VisualStudio` version `3.2.0` depends on `Nuget.Core` version `2.8.8` but its not available in repo

```
Error       Unable to find a version of 'NuGet.Core' that is compatible with 'NuGet.Protocol.Core.v2 3.2.0 constraint: NuGet.Core (≥ 2.8.8)'.
```

The last version of `NuGet.Core` that is available is `2.8.6`

Please help.

**Comment by yishaigalatzer** [comment]
To unblock you - NuGet 2.8.8 is built from nuget2. 

We need to push it to NuGetBuild feed as well

**Comment by emgarten** [comment]
NuGet.Config in the PackageManagement repo contains the source which has NuGet.Core 2.8.8
https://github.com/NuGet/NuGet.PackageManagement/blob/dev/NuGet.Config#L5

Make sure you haven't disabled this source at the machine wide level.

**Comment by punitganshani** [comment]
@emgarten I was using `https://www.myget.org/F/nugetbuild/api/v2` until now to get the API packages. Did that change to `https://www.myget.org/F/nuget-volatile/api/v2/` or this is a staging feed before it goes to build feed?

**Comment by emgarten** [comment]
Use both feeds. nuget-volatile contains the inputs for nugetbuild.

**Comment by punitganshani** [comment]
Thanks @emgarten :)
