### ISSUE TITLE
Polly 7.4.2 Invalid Signature when dotnet restore run via MSBuild

### ISSUE THREAD

**Issue by mckinley-melton** [NuGet/Home#12958]
### NuGet Product Used

MSBuild.exe

### Product Version

msbuild -version 17.2.0+41abc5629

### Worked before?

Yes. Polly 7.2.3.1

### Impact

I'm unable to use this version

### Repro Steps & Context

I updated the package Polly 7.2.3.1 to version 7.2.4.

I then tried to run this change through an MS build pipeline which includes a dotnet restore step. This is now failing the dotnet restore error "The package signature is invalid or cannot be verified on this platform."

Per [this documentation](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3003), it said to report the issue here.

### Verbose Logs

```shell
error NU3003: Package 'Polly 7.2.4' from source: The package signature is invalid or cannot be verified on this platform.
```

**Comment by kartheekp-ms** [comment]
I believe this issue is related to https://github.com/NuGet/Home/issues/12760. Could you please review the suggested workaround at https://github.com/dotnet/sdk/issues/33928#issuecomment-1644507852 to see if it provides a temporary resolution to your problem?
