### ISSUE TITLE
Package Manager Console freezes Visual Studio 2015

### ISSUE THREAD

**Issue by mmoore99** [NuGet/Home#1296]
This is a follow-up to issue #1016 (Package Manager Console freezes Visual Studio 2015 with custom profile).  In my case, any attempt to access the Package Manager Console freezes Visual Studio and requires VS to be killed by Task Manager.  In this case, there is no custom profile.

**Comment by yishaigalatzer** [comment]
@mmoore99 we need more details
1. What version of the NuGet extension are you using (can you update to the latest from the gallery)?
2. If updating doesn't resolve your issue, is there a way to get more information about your setup and can you provide a dump?

**Comment by mmoore99** [comment]
Upon further review I have determined that my issue is, in fact, a
duplicate of issue #917.  My issue can be closed.
