### ISSUE TITLE
HTTP 401 after some time in VS

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#12961]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet 6.8

### Worked before?

NuGet 6.6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Use a package source that needs credentials, and use a credential manager to provide those credentials. If VS is open for long enough (longer than token validity that the cred provider gave to NuGet), then all HTTP requests will result in HTTP 401, because HttpClient will keep using the old credential, and never refresh to the newer token that the cred provider gave.

The root cause is that NuGet started using `HttpClientHandler.PreAuthenticate`, but there's a bug in the .NET runtime:

* https://github.com/dotnet/runtime/issues/93340

Note, that the Azure Artifacts cred provider currently gives a token with a long valid duration, so it's unlikely most customers will experience this, with Azure DevOps. However, if customers are using other credential providers, that return short lived tokens, the probability of encountering this problem is greatly increased.

**Comment by umerkle** [comment]
Is it possible that my problem, i posted on [stackoverflow](https://stackoverflow.com/questions/77335731/getting-401-when-trying-to-access-nuget-sources), may be related to this?
I'm not aware if i use any credential manager.
