### ISSUE TITLE
Folder Name mangling

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1297]
_From @Grauenwolf on August 30, 2015 3:2_

I have a folder named "lib\portable-win81+wp81", but when I package my library the folder is renamed "lib\portable-win81%2Bwp81". 

Is this normal? I ask because my Win 8.1 projects can't load the package.

_Copied from original issue: NuGet/NuGetGallery#2651_

**Comment by Grauenwolf** [comment]
The root problem is that there isn't any good documentation on what the framework version strings should look like. For example, in this case the name mangling was a red herring. The string should have ended with "wpa81", not "wp81".

**Comment by yishaigalatzer** [comment]
Fair enough, we are already tracking a bug to fix the docs in this area. So closing as a dup. Completely agree we should improve this as soon as possible.

#358 

CC // @csharpfritz
