### ISSUE TITLE
Vulnerabilities filter shows incorrectly on “Brower” tab when the default tab was “Browse” instead of “Installed” for the previous opening of solution PM UI  

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#12974]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.9.0.22

### Impact

It bothers me. A fix would be nice

#### Repro Steps:       

1. Create a C# Class Library (.NET Core 8.0) project.   
2. Right-click the solution in Solution Explorer and select "Manage NuGet Packages for Solution…" menu.   
3. Click the "Browse" tab and close the solution-level PM UI.  
4. Right-click the solution in Solution Explorer and select "Manage NuGet Packages for Solution…" menu to open the solution-level PM UI again.   

#### Expected:        

Vulnerabilities filter should not show on “Brower” tab. 

#### Actual:        

Vulnerabilities filter shows incorrectly on “Brower” tab as below: 
![Unbenannt](https://github.com/NuGet/Home/assets/84695155/3d5fa777-a9cd-4cf3-a076-8ee4895ee35d)

#### Note:    

1.The repro rate is 100%.  
2.This is not a regression since it is a new feature— Vulnerabilities filter.

**Comment by nkolev92** [comment]
I think this wasn't a consideration when the feature was implemented, so I'm torn between a bug and a DCR for this. 

I'll leave for now and discuss during triage. 

cc @martinrrm, @NuGet/nuget-pm thoughts here?

**Comment by nkolev92** [comment]
Team Triage: Let's make sure the vulnerabilities filter is not there for the browse tab.
