### ISSUE TITLE
Add `--format`, `--verbosity` , `configfile` options to `dotnet package search`

### ISSUE THREAD

**Issue by Nigusu-Allehu** [NuGet/Home#12978]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

Tracking issue for adding a `--format`, `--verbosity` , `configfile` option to `dotnet package search`

### Additional Context and Details

Main feature: https://github.com/NuGet/Home/issues/6060

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/5580. 

cc @Nigusu-Allehu
