### ISSUE TITLE
`dotnet nuget restore` does not unpack `ref/*/.xml` files in the package cache on Linux, but works on macOS

### ISSUE THREAD

**Issue by radical** [NuGet/Home#12989]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.0-alpha.1.23523.13

### Worked before?

8.0.100-rtm.23506.1 on macOS

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. `dotnet new console`
2. Add `<PackageReference Include="Microsoft.Internal.Runtime.AspNetCore.Transport" Version="9.0.0-alpha.1.23552.1" />`
3. `dotnet new nugetconfig`
4. Add a local source for the above package

5. Restore with `NUGET_PACKAGES=/tmp/nuget-test dotnet restore`
6. `find /tmp/nuget-test/microsoft.internal.runtime.aspnetcore.transport/9.0.0-alpha.1.23552.1 -name '*xml'`

On linux there are no `.xml` files there even though they exist in the nuget.
On macos:
```
/tmp/nuget-test/microsoft.internal.runtime.aspnetcore.transport/9.0.0-alpha.1.23552.1/ref/net9.0/Microsoft.Extensions.DependencyInjection.Abstractio
ns.xml
/tmp/nuget-test/microsoft.internal.runtime.aspnetcore.transport/9.0.0-alpha.1.23552.1/ref/net9.0/Microsoft.Extensions.FileProviders.Physical.xml
/tmp/nuget-test/microsoft.internal.runtime.aspnetcore.transport/9.0.0-alpha.1.23552.1/ref/net9.0/Microsoft.Extensions.Diagnostics.xml
...
```

Specifically this was hit when building `dotnet/dotnet`, and hit in `aspnetcore` build.
[microsoft.internal.runtime.aspnetcore.transport.9.0.0-alpha.1.23552.1.nupkg.zip](https://github.com/NuGet/Home/files/13273223/microsoft.internal.runtime.aspnetcore.transport.9.0.0-alpha.1.23552.1.nupkg.zip)

Renamed the .nupkg to .
[restore.binlog.zip](https://github.com/NuGet/Home/files/13273233/restore.binlog.zip)
nupkg.zip .

**Comment by radical** [comment]
cc @steveisok @lewing

**Comment by radical** [comment]
This is on `Ubuntu 22.04.2` in github codespaces.

**Comment by nkolev92** [comment]
Here's a self contained repro. [12989.zip](https://github.com/NuGet/Home/files/13313292/12989.zip)

Download the zip, extract it and run dotnet restore.

**Comment by nkolev92** [comment]
Any chance the `NUGET_XMLDOC_MODE` environment variable is set?

**Comment by jebriede** [comment]
I tried repro'ing the issue on an Ubuntu system version 22.04.2 and upon running a dotnet restore, it expanded the files, including the xml files which I was able to verify with the same `find` command provided in the repro steps. Can you please check if the `NUGET_XMLDOC_MODE` environment variable is set to Skip or any other value? Thanks!

**Comment by radical** [comment]
No, the environment variable is not set anywhere. The attached binlog shows all the environment variables when restoring.

**Comment by radical** [comment]
> No, the environment variable is not set anywhere. The attached binlog shows all the environment variables when restoring.

scratch that! It is set in the environment, but does not show up in the binlog for some reason.

**Comment by nkolev92** [comment]
I think the binlog only shows env vars that are being used as properties.

**Comment by nkolev92** [comment]
Sounds like that's the answer then correct?
Are we safe to close this issue?

**Comment by baronfel** [comment]
> I think the binlog only shows env vars that are being used as properties.

Correct, though there is an environment variable (MSBUILDLOGALLENVIRONMENTVARIABLES) that can be set to opt into the older, more verbose behavior.

**Comment by radical** [comment]
> > I think the binlog only shows env vars that are being used as properties.

It cannot know the properties that will be used till evaluation is done which happens after the initial logging of environment variables. Instead, msbuild logs "well known" environment variables that get used as properties.

https://github.com/dotnet/msbuild/blob/3b59113aa9333f52efc4ab6bf96d713d05d604d1/src/Build/Logging/SerialConsoleLogger.cs#L107-L114

https://github.com/dotnet/msbuild/blob/3b59113aa9333f52efc4ab6bf96d713d05d604d1/src/Shared/EnvironmentUtilities.cs#L16-L21

> Correct, though there is an environment variable (MSBUILDLOGALLENVIRONMENTVARIABLES) that can be set to opt into the older, more verbose behavior.

yeah

**Comment by radical** [comment]
> Sounds like that's the answer then correct? Are we safe to close this issue?

Yes. I still don't know how I'm getting the variable though. And I cannot override it, so it is being treated like a "special variable"? I think it might be something docker related. I'll keep digging.
Thanks for all the help!
