### ISSUE TITLE
Restore operations randomly failing due to "repository primary signature validity period has expired"

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#12987]
---
**Issue moved from dotnet/core#8884**
- Please respond to @arp-mbender.

---

_From @arp-mbender on Friday, November 3, 2023 3:12:45 PM_

### Description

Our CI/CD pipelines seem to randomly fail when restoring Nuget packages, and I can't seem to pinpoint the cause.

The logs from such failed attempts seem to indicate a certificate issue with Nuget.org.

```
"C:\Program Files\dotnet\dotnet.exe" restore C:\azp\agent\_work\1\s\<Project>\<Project>.sln --configfile C:\azp\agent\_work\1\Nuget\tempNuGet_46182.config --verbosity Minimal --ignore-failed-sources
  Determining projects to restore...
C:\azp\agent\_work\1\s\<Project>\src\<Project>.Web.Core\<Project>.Web.Core.csproj : error NU3028: Package 'System.Diagnostics.DiagnosticSource 4.0.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamping certificate is not trusted by the trust provider. [C:\azp\agent\_work\1\s\<Project>\<Project>.sln]
  Package 'System.Buffers 4.0.0' from source 'https://api.nuget.org/v3/index.json': 
  Signature type: Repository
  Package 'System.Buffers 4.0.0' from source 'https://api.nuget.org/v3/index.json':   Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  Package 'System.Buffers 4.0.0' from source 'https://api.nuget.org/v3/index.json':   SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Package 'System.Buffers 4.0.0' from source 'https://api.nuget.org/v3/index.json':   Valid from: 4/10/2018 2:00:00 AM to 4/14/2021 2:00:00 PM
C:\azp\agent\_work\1\s\<Project>\src\<Project>.Web.Core\<Project>.Web.Core.csproj : error NU3037: Package 'System.Buffers 4.0.0' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired. [C:\azp\agent\_work\1\s\<Project>\<Project>.sln]
```

As far as I know the `dotnet` version we're using is 7.0.403. The logs seem to suggest that **nugget.org** is using a certificate that expired in 2021, which I find highly unlikely. 

Since this is failing randomly I've no idea how to proceed with debugging this. Is it possible it's some random CDN server that's lacking updates / is out of sync and we randomly seem to be routed to it?

**Comment by jebriede** [comment]
---
**Issue moved from dotnet/core#8884**
- Please respond to @michaelgsharp.

---

_From @michaelgsharp on Monday, November 6, 2023 5:10:18 PM_

@rrelyea are you the right person to tag for this?

**Comment by jebriede** [comment]
---
**Issue moved from dotnet/core#8884**
- Please respond to @rrelyea.

---

_From @rrelyea on Monday, November 6, 2023 5:24:30 PM_

Sorry, not anymore. @aortiz-msft or @dtivel most likely.

**Comment by jebriede** [comment]
---
**Issue moved from dotnet/core#8884**
- Please respond to @dtivel.

---

_From @dtivel on Monday, November 6, 2023 6:00:10 PM_

See https://learn.microsoft.com/nuget/reference/errors-and-warnings/nu3037 and https://learn.microsoft.com/nuget/reference/signed-package-verification-options#retry-untrusted-root-failures

**Comment by jebriede** [comment]
@arp-mbender it looks like the issue you are experiencing may be the one described [here](https://learn.microsoft.com/en-us/nuget/reference/signed-package-verification-options#retry-untrusted-root-failures). That link also contains a solution for enabling a retry mechanism by setting an environment variable with values that indicate how many retries and how often to retry.

The values provided in the documentation are a suggestion and what works best in your situation may be different. You may need to try a few different values before finding a retry count and interval that works best. Please try using the retry mechanism and setting various values and let us know if that fixes the problem.

**Comment by arp-mbender** [comment]
@jebriede Yes, already followed that from the last response. I've already implemented that environmental variable in our docker images. Alas, I cannot immediately confirm if this resolves the issues we've been having since, well, they've been rather random.

**Comment by jebriede** [comment]
> @jebriede Yes, already followed that from the last response. I've already implemented that environmental variable in our docker images. Alas, I cannot immediately confirm if this resolves the issues we've been having since, well, they've been rather random.

Great! Thanks for your reply. Please keep us posted over time as you observe if the retry mechanism seems to resolve the issue.

**Comment by zahirtezcan-bugs** [comment]
For certificate errors about a nuget package, one may use `dotnet nuget verify -v detailed path-to-package` command to check whether there actually is an error in the certification chain. In my case, the computer in an offline network did not have the up-to-date root certificates.
