### ISSUE TITLE
Bad data in `nupkg.metadata` should include package id or path in error message

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#12997]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe, Visual Studio Package Management UI, Visual Studio Package Manager Console, NuGet SDK

### Product Version

N/A

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

When performing a restore, the Global Packages Folder (GPF) is commonly used to find packages and read their included `nupkg.metadata` file. When doing so, if that file is empty or contains invalid metadata, this will cause restore to fail.

The output from restore does not indicate which package it found with invalid metadata. 
A message states: `Found invalid data while decoding.`
Enabling `SHOW_STACK_TRACE` shows the origination is from reading `nupkg.metadata`, but not which file caused it.
Detailed/Diagnostic verbosity does not help either.

![image](https://github.com/NuGet/Home/assets/49205731/14c5c2e9-cd16-4b60-9c43-46b70a872aa6)

**Comment by nkolev92** [comment]
Customer reported in https://github.com/NuGet/Home/issues/13763.
