### ISSUE TITLE
Embed the right versions of Restore-related files into binlog at the right time

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#12994]
Currently we have a problem that if Restore is running after .g.props and g.targets files are already on disk, the old versions of these files will be embedded in the binlog instead of the ones produced by the Restore task.

However if the Restore task doesn't run, we still want to embed whatever version of g.props and g.targets was on disk at the time they were imported.

Same for project.assets.json, it's hard to embed the right version of it at the right time. Currently it's being done by this logic:
https://github.com/dotnet/sdk/pull/16840/files

The way embedding into binlog is done is every time an item is added (either via ItemGroup, or as an output item of a task, or as target output), if the file path exists on disk, the current contents of the file is embedded immediately and eagerly. Subsequent requests to embed the same file path are ignored (the first request wins, and the version is stored as of the time of the first request). However if the requested file doesn't exist on disk, nothing happens, so the next request to embed the file will succeed if the file is first found on disk.

@jeffkl

**Comment by nkolev92** [comment]
@KirillOsenkov Don't we want both files embedded, since they are potentially different?
Does the binlog support embedding 2 versions of the same file?

**Comment by KirillOsenkov** [comment]
That's the problem, we only support one blob per file path, and whoever logs first, wins. We could change that but we'd have to hash the file contents each time to avoid duplication, because hundreds of projects are requesting to embed the same files over and over (e.g. Directory.Build.props, or Common.targets). I doubt we can practically store multiple snapshots of a file, at least not in the near future.

Much easier to figure out a solution for this issue.

For example I've been thinking: if the file path ends with .g.props or .g.targets, and the file was not imported, do not embed it. This would deal with one case.

The project.assets.json is a harder problem. Mostly because if Restore doesn't run during a build, we just want to embed whatever project.assets.json is on disk, and that's currently done via https://github.com/dotnet/sdk/pull/16840/files. But if Restore does run, we want to embed the version that was output by the Restore task. Fortunately that currently works fine because Restore runs earlier than that logic (I think??)

**Comment by KirillOsenkov** [comment]
@jeffkl and I came up with a solution. Alongsize MSBuildRestoreSessionId we should set three other properties (Jeff remembers which ones)

**Comment by jeffkl** [comment]
I'm going to close this in favor of https://github.com/dotnet/msbuild/issues/9512
