### ISSUE TITLE
NuGet Pack: Invalid evaluation of the <files> entries for dependency .nuspec files

### ISSUE THREAD

**Issue by ulrichb** [NuGet/Home#1299]
We're using `nuget pack` to pack .csprojs with dependencies. There is one common `TemplateShared​.nuspec` (added as a project item link in all .csprojs) + we use the trick with the empty .nuspec files next to the dependency .csproj files (which is necessary that `nuget pack` accepts these projects as dependencies).

When calling `nuget pack` with `-IncludeReferencedProjects` we get the following output.

<pre>
Attempting to build package from 'NuGetPackDependencyFilesIncludeIssue.Lib.csproj'.
Packing files from 'C:\[...]\NuGetPackDependencyFilesIncludeIssue\
NuGetPackDependencyFilesIncludeIssue.Lib\bin\Debug'.
Using 'TemplateShared.nuspec' for metadata.
Error occurred when processing file 'C:\[...]\NuGetPackDependencyFilesIncludeIssue\
NuGetPackDependencyFilesIncludeIssue.
Dependency\NuGetPackDependencyFilesIncludeIssue.​Dependency.csproj': <b>Could not 
find a part of the path</b> 'C:\[...]\NuGetPackDependencyFilesIncludeIssue\<b>Shared\bin\Debug</b>'.
</pre>

The problem is that `nuget pack` tries to resolve the `<files>` specification of the _dependency's_ .nuspec, containing `<file src="bin\$configuration$\$id$.pdb" />`. This file include is evaluated relative to the `TemplateShared.nuspec`. (=> A functioning workaround is to create a dummy shadow file structure  next to `TemplateShared.nuspec`.)

Why is the `<files>` specification evaluated for the dependency .nuspec files at all?

For a complete repro sample, see [NuGetPackDependencyFilesIncludeIssue.zip](https://github.com/ulrichb/IssueAttachments/raw/master/NuGetPackDependencyFilesIncludeIssue.zip). Executing `pack.cmd` produces the error shown above, and renaming "Shared/rename to bin for the workaround" to "Shared/bin" as workaround allows to create the .nupkg.

**Comment by nkolev92** [comment]
Thanks for filing this issue. 
We believe that the guidance posted [here](https://github.com/NuGet/Home/issues/6265#issuecomment-349841982) would help you author to your nuspec.
Please let us know if you're still having issues.
