### ISSUE TITLE
V3 install/restore only uses credentials for index.json

### ISSUE THREAD

**Issue by jmyersmsft** [NuGet/Home#1300]
We're still having problems with auth against v3 endpoints. Using: 
- nuget.exe built from current dev branch or CI build 10477
- an authenticated v3 source containing the package 'SuperHelloLib'
- credentials stored in nuget.config,

running:

```
nuget install SuperHelloLib
```

gives the following behavior:
1. GET (index.json) (without credentials) -> 401 with auth challenge
2. GET (index.json) (with Basic credentials) -> 200
3. GET (Registration URL for SuperHelloLib) (**without** credentials) -> 401 with auth challenge
4. NuGet.exe gives up with the message "Failed to retrieve metadata from source: '_[query URL]_'.". No further HTTP requests are issued.

The same behavior is seen with restore using a packages.config

**Comment by yishaigalatzer** [comment]
This should be verified both for command line, and visual studio extension
