### ISSUE TITLE
NuGetAuditMode doesn't work for SDK style projects in VS 17.8

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13003]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 17.8

### Worked before?

It's a new feature

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The way that NuGet & the .NET SDK works in Visual Studio is that https://github.com/dotnet/project-system sends NuGet project information (via an API called `NominateProjectAsync`, so we typically call it a "nomination"), which NuGet then uses in order to perform the restore.  Unfortunately I forgot to add `NuGetAuditMode` to the list of properties sent to NuGet, so NuGet has no way of knowing this property value in VS 17.8:

* https://github.com/dotnet/project-system/pull/9320

**Comment by nkolev92** [comment]
This was fixed in 6.9, correct?

**Comment by zivkan** [comment]
Yes, yes it was: https://github.com/dotnet/project-system/pull/9320

thanks for noticing and cleaning up.
