### ISSUE TITLE
Update-Package for project.json does not rollback changes if the install fails

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1301]
Steps:
1. Create a new UWP project
2. install-package nuget.versioning -version 1.0.5
3. update-package nuget.versioning -version 9.0.0

Expected:
The update should rollback to 1.0.7

Actual:
An error message is displayed but there is no rollback

Use the above steps but instead of #3 run:
install-package nuget.versioning -version 9.0.0
This will rollback

**Comment by yishaigalatzer** [comment]
@emgarten do you mean it should roll back to 1.0.5 ?
