### ISSUE TITLE
Add support for ECDSA certificates

### ISSUE THREAD

**Issue by baughj** [NuGet/Home#13016]
### NuGet Product(s) Involved

NuGet SDK

### The Elevator Pitch

In May 2021, the minimum RSA key size for code signing and EV code signing was increased to 3072 bits as a result of the adoption of new CA/B standards. In addition, the private keys for those certificates are required to be stored securely (eg you cannot generate a CSR yourself and store the key locally). Many code signing certificate vendors have been using Yubikey FIPS tokens as a compliant way of meeting the storage requirements (private key storage must be on an HSM _or token_ that is FIPS 140-2/CC EAL4+ or equivalent). They do this by attestation using PIV - however, the PIV standard does not support RSA keys greater than 2048 bits, so, neither does the Yubikey. 

As older 2048 bit certificates expire, or are rekeyed / regenerated, this poses a problem: Nuget does not support ECDSA, and Yubikeys do not support RSA > 2048. Many vendors are simply migrating users to ECDSA (as a for instance, mine did) to get around the Yubikey issue, because many other tools (including signtool) work just fine with ECDSA. If you order a new certificate from a vendor and order a token - you are almost assuredly receiving ECDSA on a FIPS Yubikey.

As far as I can tell (and I would be happy to be wrong) this leaves no path for many smaller organizations or users that does not involve either:

* expensive HSMs (even a "low end" Yubikey HSM is $950 for a FIPS-certified version, and this cannot be used with my vendor, as an example, without undergoing an expensive (multiple $K) auditing process)
* generally terrible third party tooling (such as a cloud signing service).

I feel fairly strongly that:

1. I should not have to use a third party tool written in Java to sign my nuget packages (what my vendor suggested)
2. I should not need to spend thousands of dollars to sign Nuget packages

I would suspect I am not alone in this regard. 

### Additional Context and Details

I see that this was discussed previously in https://github.com/NuGet/Home/issues/11232 and I am hoping that two years later there will be a different response or a little bit more discussion.

Thank you for your time reading this and your efforts on Nuget. I appreciate both.

**Comment by nkolev92** [comment]
cc @dtivel

**Comment by wangkanai** [comment]
I agree with @baughj on this matter, I currently have no way to sign my nuget package using code signing certifcate from ssl.com with new enforce of ECS certifcate that Microsoft also voted yes on the matter [Ballot CSC-13 – Update to Subscriber Key Protection Requirements
](https://cabforum.org/2022/04/06/ballot-csc-13-update-to-subscriber-key-protection-requirements/)

I have not been able to publish any new nuget packages bugs fixes or update of any kind right now.

https://www.nuget.org/profiles/wangkanai

```log
Signing package(s) with certificate:
  Subject Name: CN=Sarin Na Wangkanai, O=Sarin Na Wangkanai, S=Bangkok, C=TH
  SHA1 hash: F031558C2440575FBBE764E7D807E01A79F2E10E
  SHA256 hash: 9D54719E5C3A65185F2352C15B71C97AC12DCD43E63789FC5E4E52ADB9444214
  Issued by: CN=SSL.com Code Signing Intermediate CA ECC R2, O=SSL Corp, L=Houston, S=Texas, C=US
  Valid from: 12/25/2023 12:54:48 PM to 12/24/2026 12:54:48 PM
Timestamping package(s) with:
http://ts.ssl.com
Signed package(s) output path:
.\signed
error: NU3013: The signing certificate has an unsupported signature algorithm.
```

I have been find alternative ways to get around this limitation.

**Comment by baughj** [comment]
@wangkanai I see we use the same vendor! The only way you can sign packages with ssl.com certificates at the moment is by using their cloud code signing service. I worked with their support to get this working - the latest version of their CLI tool (1.3.0) supports signing nuget packages (see https://www.ssl.com/how-to/code-signing-nuget-packages-with-esigner-codesigntool/#ftoc-heading-5), however - caveat is it obviously does not work with ECDSA keys. 

You can get their support to reissue as 3072 bit RSA, however, and then you can use their tool to do it, but then you are forced to use that tool for all signing operations (because PIV attestation will no longer be available).

**Comment by baughj** [comment]
@jeffkl @dtivel any thoughts on this? Above is a perfect example of a terrible workflow that is now required due to lack of ECDSA support.

**Comment by jonas-pdx** [comment]
I also agree with @baughj’s excellent write up. This would be so appreciated.

**Comment by wangkanai** [comment]
@baughj That is the problem, I don't want to be locked into a cloud subscription for something that I have paid for 10 years in advance and need another $20 usb/month with limited of how many signings I get from their HSM cloud e-signer service.

**Comment by nkolev92** [comment]
Team Triage: 
Referring to https://github.com/NuGet/Home/issues/11232#issuecomment-1683059868. 
At this point we're not planning on adding support for ECDSA certificates.

**Comment by XomegaNet** [comment]
It's a shame, as we ended up having to publish our packages to NuGet unsigned.
This is really a step backwards for security. I hope you'll reconsider in the near future and will add support for ECDSA certs.
