### ISSUE TITLE
Missing nuget packages a constant pain, no way to restore 

### ISSUE THREAD

**Issue by asdf23** [NuGet/Home#13010]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

Visual Stuidios All

### Worked before?

Never

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Constantly missing packages no way to restore. Delete files, uninstall through GUI reinstall through GUI.

**Comment by jeffkl** [comment]
@asdf23 can you please provide more context on your issue?  Simple steps to reproduce the problem or attaching a ZIP with a solution/projects that we can use to reproduce the issue will help us investigate further.  Are you seeing error messages that you can share here?  If you're having specific trouble in Visual Studio, you can use the Send Feedback functionality to send Microsoft more information about the issue you're experiencing.



![Image](https://github.com/NuGet/Home/assets/17556515/39b6acb1-078d-4a97-8084-868d0b4c6982)
