### ISSUE TITLE
Nuget requires Paketsource assignment on almost every package

### ISSUE THREAD

**Issue by josua-kaden** [NuGet/Home#13020]
### NuGet Product(s) Affected

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Current Behavior

I'm not sure when it started but my Nuget packge manager in Visual Studio now doesn't recognize packages until I manually given it their Sourcename. This is very annoying and other users i asked personally do not even have the option to change their package source tight from the installtion tool.

My window looks like this right now: 
![Screenshot_nuget](https://github.com/NuGet/Home/assets/125959666/3866f86e-c14b-42d0-bfba-791b256e0dc7)

just to clarify, because the picture is in german, the part behind the red x is my problem it says: Requires Packagesource assignment.

### Desired Behavior

This wasn't the case like 3 months ago, but since then more and more packages required that and the package source required is just the name of the package e.g. 'System.Drawing.Common' or something. So i hope there is a way to just download the packages without this requirement. 

### Additional Context

I already tried to reinstall my Visual Studio, this didn´t work.

So Probably there is some residual userdata file with saves my config of VS, but before a start scraping my whole filesystem I wanted to try it here.

Thank you in advance

**Comment by jeffkl** [comment]
@josua-kaden it sounds like [Package Source Mapping](https://learn.microsoft.com/nuget/consume-packages/package-source-mapping) might have been enabled.  Do you see any `<packageSourceMapping>` elements in a `NuGet.config` file next to the project or any folder above it?  You also can check these user-wide and machine-wide configs:

```
%AppData%\NuGet\NuGet.Config
%ProgramFiles%\NuGet\Config\*.config
%ProgramFiles(x86)%\NuGet\Config\*.config
```

**Comment by josua-kaden** [comment]
Hi Jeff,

thanks for the answer. Yes i do have the `<packageSourceMapping>` -tags. For now i tried just to commented them out, is this the way to go ? because Visual Studio, now at least realises that the sourcemapping is deactivated. Or is there another switch that i can use to turn it off ?

**Comment by jeffkl** [comment]
@josua-kaden if you enable Package Source Mapping, NuGet will require you to map every package you consume.  If your NuGet.config only contains one feed, Package Source Mapping is not really a requirement since you know all of your packages are coming from that one source.

Package Source Mapping is useful when you are consuming packages from multiple feeds but want to be sure that certain packages come from specific feeds.  But again, once enabled, you will need to provide a mapping for each package or use a pattern like `Microsoft.*`.
