### ISSUE TITLE
nuget.exe should show a helpful message when nuget.config is corrupt

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1302]
An invalid nuget.config will cause a generic exception and error message.

Steps
1. Create a new UWP app
2. Copy .vs\config\applicationhost.config to nuget.config or create a corrupted nuget.config file
3. From the solution folder run: _nuget.exe restore -configfile nuget.config -packagesdirectory packages_

**Expected:**
An error message referring to nuget.config

**Actual:**

```
Restoring packages for <mypath>\Projects\App13\App13\project.json...
Unable to resolve Microsoft.NETCore.UniversalWindowsPlatform (≥ 5.0.0) for UAP,Version=v10.0.
Exception of type 'NuGet.CommandLineException' was thrown.
```

**Comment by csharpfritz** [comment]
Similarly, ensure that a friendly and detailed error message is shown for corruption of 
project.json files as well.

**Comment by emgarten** [comment]
@deepakaravindr was this fixed in your change?

**Comment by deepakaravindr** [comment]
Yes, this will get fixed by the PR: https://github.com/NuGet/NuGet.Client/pull/103 as well

**Comment by yishaigalatzer** [comment]
The message should show what file is introducing the bad xml.

Duplicate bug: #834

**Comment by yishaigalatzer** [comment]
Summary: Any invalid config file that should be picked up, but fails to load should be turned into an error message that shows both in the UI and commandline. The error should be meaningful and point to the filename/file path and location in the file

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/1567
