### ISSUE TITLE
Migrate NuGet.CommandLine.XPlat package search to use System.CommandLine

### ISSUE THREAD

**Issue by Nigusu-Allehu** [NuGet/Home#13031]
Tracking issue for migrating NuGet.CommandLine.XPlat package search to use System.CommandLine

**Comment by ghost** [comment]
@Nigusu-Allehu Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
