### ISSUE TITLE
Microsoft.EntityFrameworkCore.Sqlite how to prevent all the runtime binaries from being emitted? 

### ISSUE THREAD

**Issue by catmanjan** [NuGet/Home#13039]
### NuGet Product Used

NuGet.exe

### Product Version

7.0.402

### Worked before?

Unsure

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I've logged this here https://github.com/dotnet/efcore/issues/32382

We have a project which only runs on windows x64 and uses Microsoft.EntityFrameworkCore.Sqlite

I notice in the bin folder there are sqlite dependencies for just about every computer on earth... How can we prevent these from being emitted?

and was asked to follow up with nuget team

We use efcore in our project however we only target win-x64 environments, can nuget do something to allow efcore to only emit the architecture files needed for supported architectures.

**Comment by zivkan** [comment]
Unfortunately .NET's build process is complex, and made of many components from different teams, which live in different repos. But I'm going to have to redirect you to https://github.com/dotnet/sdk.  NuGet restores packages, creating an assets file, telling the .NET SDK what assets the package contains. It's then up to the .NET SDK to do something meaningful with that information, but working on NuGet, I only understand NuGet's side of this contract. I don't know if it's possible to give the .NET SDK a list of RIDs to include, so others get excluded from the "no rid" build.

However, if you're only in one specific RID, `win-x64`, you can use `dotnet publish -r win-x64`, and the publish output will only contain the files for that single rid.
