### ISSUE TITLE
How should I get the latest package version using `NuGet.Client`

### ISSUE THREAD

**Issue by WeihanLi** [NuGet/Home#13042]
Hi there, I'm trying to get the latest package version of a package

```c#
Task<NuGetVersion?> GetLatestPackageVersion(string packageId, 
    bool includePrerelease = false, CancellationToken cancellationToken = default)
```

Is there an API for this?

Found some ways as follows:

- `PackageMetadataResource.GetPackageMetadataAsync`
- `FindPackageByIdResource.GetAllVersionsAsync`

Are there more ways for it I missed? And which is recommended? Thanks very much.

**Comment by nkolev92** [comment]
Those are the 2 ways, and the bottom line is depending on what information you want.

Those 2 methods return different data, one returns a list of versions, the other one includes metadata such as whether a package is listed, whether a package is vulnerable etc, so it really depends on your scenario.
