### ISSUE TITLE
[Bug Bash] An error “Type universe cannot resolve assembly: System.Runtime” occurs when uninstalling the top-level package “Microsoft.NETCore.UniversalWindowsPlatform” whose transitive package should not be uninstalled

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13040]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.9.0.45

### Worked before?

It also reproes on 17.6 (D17.6\34302.98) & 16.11 (D16.11\34301.259)

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	Create a C# UWP project in VS and open the PM UI of the project.
2.	Right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI.
3.	Go to “Installed” tab and uninstall the top-level package: “Microsoft.NETCore.UniversalWindowsPlatform” whose transitive package should not be uninstalled.
4.	Build the project.

#### Expected:
In step3 NuGet should remind user that the top-level package should not be uninstalled since its transitive package: “NETStandard.Library” (which depends on package “System.Runtime”) should not be uninstalled. [At least warn people the uninstallation would bring error and how to resolve it].

#### Actual:
No warning is provided in step3 and there is an error “Type universe cannot resolve assembly: System.Runtime” in the Error List window after step4 as below. And the error message doesn’t tell people how to resolve it.
![image](https://github.com/NuGet/Home/assets/20632625/3973cdef-679a-4f5e-b765-fb807392b173)

**Comment by nkolev92** [comment]
Thanks for creating this suggestion @v-luzh. 

However, I'm not really sure that's detectable by NuGet. We cannot really know the impact of a package getting removed. 
NuGet's responbility is downloading packages, selecting the compatible assets, whether the packages work in the project because of missing dependencies is beyond NuGet's ability.

**Comment by v-luzh** [comment]
Hi @nkolev92, OK, got you. Thanks for your triaging and description. We updated the resolution to External since this error is still there although it is beyond NuGet's ability. Please feel free to loop this issue to other team, thanks.
