### ISSUE TITLE
Unable to find a version of package "System.Globalization' that is compatible with version constraint [4.0.0, )

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1304]
I have a simple package that takes a dependency on a few framework packages.

I reference it and another package (one that is included by default in ASP.NET v5 projects) and nuget fails to restore the project.  The error message doesn't make any sense because it is inconsistent with what is on the feed (System.Globalization does indeed exist with version 4.0.0).

To repro use the following project.json

```
{
  "dependencies": {
    "System.Banana.1.1.dll.dotnet": "1.0.0",
    "Microsoft.AspNet.Server.IIS": "1.0.0-beta6"
  },
  "frameworks": {
    "dnxcore50": { }
  }
}
```

With sources:

```
https://www.myget.org/F/ericstj-issue-repros/api/v2
https://www.nuget.org/api/v2
```

A simple repro is

```
NuGet.exe restore -source https://www.myget.org/F/ericstj-issue-repros/api/v2 -source https://www.nuget.org/api/v2 project.json
```

You'll see

```
Restoring packages for Z:\test\uwp\project.json...
Restoring packages for DNXCore,Version=v5.0...
Unable to find a version of package 'System.Globalization' that is compatible with version constraint '[4.0.0, )'.
```

I've experimented with v2 vs v3 nuget feed and it doesn't seem to be caused by this.  

If I promote the references that are complained about to the project.json I can play whack-a-mole until the error goes away, but that was a lucky guess.  

Interestingly this bug does **not repro with dnu** so the issue seems to be unique to nuget's version of the graph walking code.

/cc @davidfowl @anurse @yishaigalatzer

**Comment by ericstj** [comment]
I found that when I use the latest pre-release nuget.exe that I extracted from http://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.2-beta-10482 I get more information:

```
Version conflict detected for System.Globalization.
 uwp (≥ 1.0.0) -> Microsoft.AspNet.Server.IIS (≥ 1.0.0-beta6) -> Microsoft.AspNet.Loader.IIS (≥ 1.0.0-beta6) -> Microsoft.AspNet.Hosting (≥ 1.0.0-beta6) -> Microsoft.AspNet.Http.Extensions (≥ 1.0.0-beta6) -> Microsoft.Net.Http.Headers (≥ 1.0.0-beta6) -> System.Globalization (≥ 4.0.10-beta-23109)
 uwp (≥ 1.0.0) -> System.Banana.1.1.dll.dotnet (≥ 1.0.0) -> System.Resources.ResourceManager (≥ 4.0.0) -> System.Globalization (≥ 4.0.0).
...
```

Can you explain why nuget thinks System.Globalization (≥ 4.0.10-beta-23109) and System.Globalization (≥ 4.0.0) are a conflict?

Seems to me nuget should choose 4.0.10-beta-23109 and it'd satisfy both constraints.

**Comment by rowanmiller** [comment]
FYI this also affects installing the Entity Framework 7 Beta 7 packages on a UWP project (installs successfully on Full .NET and ASP.NET 5 projects).

**Comment by emgarten** [comment]
This was caused by stable dependency version ranges (Ex: >= 4.0.0) not allowing prerelease packages during conflict resolution.

NuGet/NuGet3@f35805cdd7b494890de99037a70adadbe8ff344a
