### ISSUE TITLE
NuGet restore cache check is no longer using file existence cache

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#13058]
### NuGet Product Used

Other/NA

### Product Version

Visual Studio 17.9

### Worked before?

not sure

### Impact

Other

### Repro Steps & Context

Check Visual Studio solution loading trace when cache is available,  or performance DDRITs can be used here. During NuGet restore runner time, NuGet took out many thread pool threads, and most of them will be blocked to check whether sha256 files exist (or basically, whether the version of NuGet package is still in the NuGet cache folder).  Because package references are added to the closure of project references, each file is often checked in multiple projects. With often hundreds of files per project, in a large solution, it introduces heavy amounts of system calls/IOs.

Here is the thread time of one trace:

<img width="1697" alt="image" src="https://github.com/NuGet/Home/assets/11638466/29b35148-5f15-4323-bf93-ac06dfc9942d">

**Comment by lifengl** [comment]
+ @nkolev92

**Comment by lifengl** [comment]
@nkolev92 : can we address this problem as it is a regression & showing in our perf test traces. It may expose other problems and help us to know how much further work we need do in this area?

+ @davkean

**Comment by nkolev92** [comment]
Yeah, we can schedule it. It should be a simple change, but not sure it'll make it in 17.9 since it's basically the last week for changes.

**Comment by nkolev92** [comment]
I started a change, https://github.com/NuGet/NuGet.Client/tree/dev-nkolev92-useFileCacheForNoOp

**Comment by lifengl** [comment]
nice, thanks a lot to take care of it.
