### ISSUE TITLE
Validate --source for "dotnet restore --source"

### ISSUE THREAD

**Issue by TheOnlyWei** [NuGet/Home#13056]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe

### Current Behavior

Currently, there is an easy developer pitfall due to caching of NuGet package sources. Once I run something like the following code:
```
dotnet restore --source 'https://api./nuget.org/v3/index.json'
```
This will cache the source's packages on my computer. Therefore, if I run a restore command again in the same project like the following:
```
dotnet restore --source 'asdasdfasfasfsgdfhgrsdtyhrtuhrthjfghj'
```
The command will work because the source doesn't actually matter after the packages are cached. The developer will only run into issues if `dotnet restore --source 'asdasdfasfasfsgdfhgrsdtyhrtuhrthjfghj'` is run before `dotnet restore --source 'https://api./nuget.org/v3/index.json'`.

### Desired Behavior

If a developer specifies `--source` flag, it means they want to use that source, not the cached source. So, a command like the following should fail even if packages required by the current project are cached because the NuGet source is obviously invalid:
```
dotnet restore --source 'asdasdfasfasfsgdfhgrsdtyhrtuhrthjfghj'
```

**Comment by nkolev92** [comment]
The offline behavior whenever appropriate is something our customers frequently want, so I'm not sure if it's beneficial to the majority of the customers to access sources when all packages are already on disk.

**Comment by TheOnlyWei** [comment]
> The offline behavior whenever appropriate is something our customers frequently want, so I'm not sure if it's beneficial to the majority of the customers to access sources when all packages are already on disk.

How does NuGet know the sources are already on the disk if the source is `asdsafsdgdfgeryhrtyufhfghfghdfh`? What is the point of the parameter `--source` if it doesn't matter what it is? On top of that, it's strange that if a registered NuGet source is unavailable, NuGet commands all fail even if the code doesn't use the unavailable source (see https://github.com/NuGet/Home/issues/6373), but here when `--source` is specified literally by the user, it doesn't even attempt to validate the source and should "just work". Seems like there are some contradictions in the user-experience design.

**Comment by nkolev92** [comment]
@TheOnlyWei It's the project that specifies which packages need restored. If those packages are on disk, NuGet will not try to access any sources. 

https://learn.microsoft.com/en-us/nuget/concepts/package-installation-process

A new package installation is different from a restore that might've run before.

**Comment by TheOnlyWei** [comment]
@nkolev92 Isn't the `--source` parameter supposed to override registered or already configured sources? So, what I am hearing is that it won't override anything if the package was already cached, is that the expected behavior?

**Comment by nkolev92** [comment]
If the packages are installed on disk (what you're referring to as cached), there won't be any download. 
We describe that in https://learn.microsoft.com/en-us/nuget/concepts/package-installation-process.

**Comment by TheOnlyWei** [comment]
@nkolev92 I understand that, as I pointed out, `--source` says it overrides the registered sources as documented here:
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

> Specifies the URI of the NuGet package source to use during the restore operation. **This setting overrides all of the sources specified in the nuget.config files.** Multiple sources can be provided by specifying this option multiple times.

The caching behavior makes it so that the `--source` parameter is not even validated. If `--source` was never validated, how does it know the cached version is correct? What if there is a package name conflict? I wouldn't call this current behavior "overriding".

**Comment by nkolev92** [comment]
The sources are overwritten, but they're not used since everything is on disk.

Once a package is downloaded and installed on the machine, it will be used until it's removed.
There's no overwriting packages today. 
If you want to use packages from that source only you can use the dotnet nuget locals command.

**Comment by nkolev92** [comment]
Team Triage: This is by design.
