### ISSUE TITLE
Vulnerability InfoBar remains visible in the Solution Explorer after closing solution

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13055]
When closing a solution when the vulnerability infobar was shown, I noticed that the infobar remains visible. When solutions are closed, this infobar should be removed since the context is no longer present in VS.

![image](https://github.com/NuGet/Home/assets/49205731/06527807-1b3b-4b1f-aa45-f2cdaf9adaf0)

**Comment by nkolev92** [comment]
cc @martinrrm

**Comment by nkolev92** [comment]
The SolutionManager has a SolutionOpening and SolutionClosing events. Listening to those should be an easy fix.

**Comment by nkolev92** [comment]
Team Triage: We should try to address this in 17.9 given that it's affecting a new feature.
