### ISSUE TITLE
VS2015 NuGet UI shows "Upgrade available" packages even when not applicable to current solution.

### ISSUE THREAD

**Issue by RichardJFoster** [NuGet/Home#1305]
This problem is somewhat self-inflicted due to some legacy choices associated with version control repositories and solution structure... however the result is still potentially undesirable due to the confusion it may cause.

In the scenario where there are multiple solutions in a single folder structure, the NuGet UI may erroneously indicate that there are updates available for a package within a solution even though the update is only applicable to an assembly that is not part of the currently loaded solution.

Example:

Assuming the current version of package X is 1.1

Solution 1 contains
- Shared assembly with dependency on package X, V 1.1
- Solution specific assembly with dependency on package X, V 1.1

Solution 2 contains
- Shared assembly with dependency on package X, V 1.1
- Solution specific assembly with dependency on package X, V 1.0

Both sln files are placed in the same folder.

The erroneous operation is that if Solution 1 is loaded, then showing the solution-wide NuGet UI with "Update available" selected indicates that there is an update for package X, even though package X is fully up-to-date within Solution 1.

A better operation would be that package X is not shown as having updates available within the context of Solution 1, but that it would be shown in the context of Solution 2.

This operation was observed in Visual Studio 2015 with NuGet package manager V 3.1.60724.766 installed.

**Comment by yishaigalatzer** [comment]
That sounds odd, since the code doesn't have any knowledge about solution 2. Can you try deleting solution 2 completely, and see if you still get an update available notification?

I'm suspecting that this might be an unrelated issue to the one described here. Of course if I'm wrong would you be able to share your solution or a small repro?

**Comment by abatishchev** [comment]
Doesn't it show an available update because nuget doesn't scan packages.config but packages folder instead.
For instance, you have a package of version A in packages folder but don't have it installed in any project. Once version A+1 is available it will be shown. But no projects can update it since don't have it installed.

**Comment by yishaigalatzer** [comment]
@abatishchev that's not the case.

@RichardJFoster I've tried to reproduce this issue, and I don't seem to get it, unless you have the project but its unloaded. Is this the case you are hitting? If no can you please post a repro?

**Comment by RichardJFoster** [comment]
Hmmm.... I may have jumped the gun with my initial problem description. While the problem I describe is definitely occurring with current code (which I do not have permission, nor am I likely to get permission to share) I am not able to reproduce in a "fresh" folder using the mechanism I described. I shall continue investigating. It may also be associated with the fact that there are a also a couple of NuGet.config files in play (one to ensure that for most solutions within the same code tree the NuGet packages are placed in a common folder, a second to ensure that for the SDK we distribute that its NuGet packages end up in the expected place relative to the solution folder). I'll let you know when/if I can nail down the problem more completely (ideally with a repro).

**Comment by emgarten** [comment]
@RichardJFoster were you able to get a repro?

**Comment by RichardJFoster** [comment]
No. Unfortunately not. We are still seeing it, but have not been able to nail down exactly what the root cause is. I'm going to close this case and I will open a new one when/if I am finally able to reproduce the problem consistently.
