### ISSUE TITLE
PackageReference to native code does not error when it's absent

### ISSUE THREAD

**Issue by Forgind** [NuGet/Home#13054]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.0-alpha.1.23577.7

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Copy the contents of [this folder](https://github.com/dotnet/sdk/tree/bd786cf2963e46fe866e80d1803b717d79806b1b/src/Assets/TestProjects/DesktopMinusRid).
Build it with `dotnet build /p:RuntimeIdentifier=win-x86`

That csproj has `<PackageReference Include="Libuv" Version="1.9.1" />`. Libuv version 1.9.1 doesn't have a win-x86 version, so it fails to copy Libuv to the output directory. When you run the exe, it fails.

dotnet build, however, succeeds with no errors. This led me to hours of head-scratching.

**Comment by nkolev92** [comment]
@Forgind, the package is added with  a condition `<ItemGroup Condition="'$(UseNativeCode)' == 'true'">`

Is that property set to true?

**Comment by Forgind** [comment]
Sorry—yes. This came out of running the relevant unit test, and it adds `<UseNativeCode>true</UseNativeCode>` to the PropertyGroup at the top.

**Comment by Forgind** [comment]
Looking at the unit test now, you shouldn't have to make any other modifications.

**Comment by Forgind** [comment]
Related:
I tried something similar with SQLite 3.13.0, which, like libuv 1.9.1, doesn't have win-x* versions, and it came up with this:
```
C:\GitHub\sdk\artifacts\bin\redist\Debug\dotnet\sdk\9.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.target
s(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win7-x64, win7-x86
. Affected libraries: SQLite. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime ide
ntifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

That message would have been very helpful with libuv; not sure what the difference is between libuv 1.9.1 and sqlite 3.13.0 in this case. Any thoughts @nkolev92?

**Comment by nkolev92** [comment]
SQLite has a lib folder, maybe that's the difference. 

Also that warning is coming from the SDK and not NuGet, so I'm not sure there's an action for NuGet here.

**Comment by Forgind** [comment]
Is the SDK what is supposed to do the copying? I honestly hadn't noticed that it was an SDK error, but this whole scenario feels like a NuGet scenario to me—asking for a package that we (transitively) need then not getting it? Though if NuGet is just supposed to download the package, and the SDK is supposed to oversee copying it, then it might just be an SDK issue after all...

**Comment by nkolev92** [comment]
> asking for a package that we (transitively) need then not getting it?

I'm not sure I get this part, the package is there, it's just authored in a way where nothing is compatible. 

> and the SDK is supposed to oversee copying it, then it might just be an SDK issue after all

NuGet downloads and does compat checks (TFM ones) and then the SDK uses it.

**Comment by Forgind** [comment]
I did see that the package was downloaded, just that no part was copied to the output directory. So it's NuGet's job to download it, and the SDK's job to copy it to the output directory or error if the requested rid-specific assembly isn't there?

**Comment by zivkan** [comment]
NuGet does asset selection and writes information about the relevant assets, per TargetFramework, into the assets file. The .NET SDK then reads the assets file and creates MSBuild items relevant so that assemblies get passed to the compiler, content gets copied to the bin folder after build, etc: https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs
