### ISSUE TITLE
`LockFileTargetLibrary` doesn't expose `msbuildProject` when `type` is `project`

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#13061]
When my project.assets.json contains this project as a library:

```
    "MSBuild.StructuredLogger/1.0.0": {
      "type": "project",
      "path": "../StructuredLogger/StructuredLogger.csproj",
      "msbuildProject": "../StructuredLogger/StructuredLogger.csproj"
    },
```

and I get the `LockFileTargetLibrary` object for it via the API, I don't see a way to get at the `path` or `msbuildProject` via the API.

Do I need to read the raw Json to obtain it?

**Comment by nkolev92** [comment]
That looks to be LockFileLibrary instead. 
Is it the libraries section? 

libraries = LockFileLibrary.
targets = LockFileTargetLibrary

**Comment by KirillOsenkov** [comment]
Oh, you were right, I had a `LockFileTargetLibrary`. I was able to look up `LockFile.GetLibrary()` and the `LockFileLibrary` does have the `MSBuildProject`.
