### ISSUE TITLE
PM UI Scrolling no longer loads additional packages.

### ISSUE THREAD

**Issue by jgonz120** [NuGet/Home#13063]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.8.34309.116

### Worked before?

17.7.7

### Impact

It’s more difficult to complete my work

### Repro Steps & Context

Reported from [DevCom Feedback](https://developercommunity.visualstudio.com/t/Problem-with-NuGet-Package-Manager-UI-af/10530864)
1. Open the PM UI. 
2. Scroll down to the bottom of the list.

Expected: More packages are loaded
Actual: The end of the list is reached and no new items are loaded. Sometimes the list will load one additional page and then stop loading more.

**Comment by nkolev92** [comment]
Comment from related issue: 

Body from the feedback ticket: There is a problem with the NuGet Package Manager UI in 17.8.0.  When trying to browse for packages it only returns the first 25 and won’t refresh when scrolling down to the bottom of the page.  I have rolled back to 17.7.7 and confirmed that it is working correctly in that version.  I then updated to 17.8.0 and confirmed that it is working as described of only getting the first 25 and not getting more.

[Developer Community Issue](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1924207?src=WorkItemMention&src-action=artifact_link), [Developer Community bug](https://developercommunity.visualstudio.com/t/Problem-with-NuGet-Package-Manager-UI-af/10530864).
