### ISSUE TITLE
Setting NUGET_HTTP_CACHE_PATH is not working

### ISSUE THREAD

**Issue by halcwb** [NuGet/Home#13066]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK:  Version:           8.0.100  Commit:            57efcf1350  Workload version:  8.0.100-manifests.71b9f198  Runtime Environment:  OS Name:     Mac OS X  OS Version:  14.1  OS Platform: Darwin  RID:         osx-arm64  Base Path:   /usr/local/share/dotnet/sdk/8.0.100/  .NET workloads installed:  Workload version: 8.0.100-manifests.71b9f198 There are no installed workloads to display.  Host:   Version:      8.0.0   Architecture: arm64   Commit:       5535e31a71  .NET SDKs installed:   6.0.415 [/usr/local/share/dotnet/sdk]   7.0.402 [/usr/local/share/dotnet/sdk]   8.0.100 [/usr/local/share/dotnet/sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.NETCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]   Microsoft.NETCore.App

### Worked before?

?

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I keep getting the error that the path to the .local/share/Nuget/http-cache etc.. is denied when I want to restore a project. Deleting the folder and setting the read and write for the user account doesn't work. So, I wanted to change the folder location, however, that doesn't work either. 

I have put this as en environmental variable: export NUGET_HTTP_CACHE_PATH=User/user1/.nuget-http-cache
But stil when running `dotnet restore`, nuget looks at the cache folder in the .local/share/nuget/http-cache.

### Verbose Logs

To make matters more confusing:

`dotnet restore`
  Determining projects to restore...
/Users/user1/Development/user1/apps/GenPRES/src/Informedica.ZIndex.Lib/Informedica.ZIndex.Lib.fsproj : warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/user1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new' is denied. [/Users/user1/Development/user1/apps/GenPRES/GenPres.sln]
/Users/user1/Development/user1/apps/GenPRES/src/Informedica.GenSolver.Lib/Informedica.GenSolver.Lib.fsproj : warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/iser1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new' is denied. [/Users/user1/Development/user1/apps/GenPRES/GenPres.sln]
  All projects are up-to-date for restore.

But when `dotnet nuget locals all --list`

dotnet nuget locals all --list
http-cache: /Users/user1/.nuget-http-cache
global-packages: /Users/user1/.nuget/packages/
temp: /var/folders/j5/xhmmjddj01vbgx6s11kdnwfc0000gn/T/NuGetScratch
plugins-cache: /Users/user1/.local/share/NuGet/plugin-cache

**Comment by halcwb** [comment]
Made a typo in the path definition.

**Comment by halcwb** [comment]
Reopened because after fixing the typo, nuget still looks at the wrong folder and can't access the path:

printenv
NUGET_HTTP_CACHE_PATH=/Users/user1/.nuget-http-cache

dotnet restore
  Determining projects to restore...
/Users/user1/Development/user1/apps/GenPRES/src/Informedica.GenSolver.Lib/Informedica.GenSolver.Lib.fsproj : warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/user1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new' is denied. [/Users/user1/Development/user1/apps/GenPRES/GenPres.sln]
/Users/user1/Development/user1/apps/GenPRES/src/Informedica.ZIndex.Lib/Informedica.ZIndex.Lib.fsproj : warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/user1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new' is denied. [/Users/user1/Development/user1/apps/GenPRES/GenPres.sln]
  All projects are up-to-date for restore.

**Comment by zivkan** [comment]
FWIW, I can't repro this in Linux using WSL2.  I'll ask any team mates with a mac to see if they can reproduce.

**Comment by JonDouglas** [comment]
I can reproduce:

```
/Users/jondouglas/Desktop/TestVul/TestVul.csproj : warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/user1' is denied. [/Users/jondouglas/Desktop/TestVul/TestVul.sln]
```

But the question to me is... does `user1` even exist on your machine? It doesn't on mine and therefore if I switch to my user, everything works as expected.

**Comment by zivkan** [comment]
My understanding of the problem being reported is that the environment variable is set to:

> /Users/user1/.nuget-http-cache

But when `dotnet restore` is run, it writes to:

> /Users/user1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new

In other words, the environment variable was being ignored, and `dotnet restore` kept using NuGet's default http-cache directory location.

@JonDouglas the fact that your restore message using using the `/Users/user1` path means that restore is using the environment variable, and therefore you couldn't reproduce (what I believe) @halcwb was reporting.
