### ISSUE TITLE
Path access denied to http-cache

### ISSUE THREAD

**Issue by halcwb** [NuGet/Home#13071]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK:  Version:           8.0.100  Commit:            57efcf1350  Workload version:  8.0.100-manifests.71b9f198  Runtime Environment:  OS Name:     Mac OS X  OS Version:  14.1  OS Platform: Darwin  RID:         osx-arm64  Base Path:   /usr/local/share/dotnet/sdk/8.0.100/  .NET workloads installed:  Workload version: 8.0.100-manifests.71b9f198 There are no installed workloads to display.  Host:   Version:      8.0.0   Architecture: arm64   Commit:       5535e31a71  .NET SDKs installed:   6.0.415 [/usr/local/share/dotnet/sdk]   7.0.402 [/usr/local/share/dotnet/sdk]   8.0.100 [/usr/local/share/dotnet/sdk]  .NET runtimes installed:   Microsoft.AspNetCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]   Microsoft.NETCore.App 6.0.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]   Microsoft.NETCore.App

### Worked before?

dotnet sdk 6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

``dotnet restore``, gives:

warning NU1900: Error occurred while getting package vulnerability data: Access to the path '/Users/user1/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new' is denied.

This is related to issue: https://github.com/NuGet/Home/issues/12162#issuecomment-1838523872. The issue is active since 2022. I tried all the proposed solutions:
- Removing the http-cache folder
- Making sure that all user rights on the folder were set
- Try to run using `sudo`, also gives the same error
- Using the --no-http-cache- option, doesn't work: https://github.com/NuGet/Home/issues/13065#issue-2024394037
- Using an environmental variable, doesn't work: https://github.com/NuGet/Home/issues/13066#issue-2024417844

So, whatever I try, I can't get rid of this problem

### Verbose Logs

[log.txt](https://github.com/NuGet/Home/files/13578073/log.txt)

**Comment by zivkan** [comment]
In https://github.com/NuGet/Home/issues/12162#issuecomment-1838523872, you shows that the `http-cache` directory had user and group ownership `myName:staff`, and the error message reported listed `/Users/MY_USER_NAME/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new`.

`MyName` and `MY_USER_NAME` are not the same. Is this just an editing "error", or are the two really different?

Can you also check the ownership of the `670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json` directory, and any `vuln_index.dat*` files if they exist?  I would expect them all to match the account that you're logged in with (`whoami` or `id -un`)

**Comment by halcwb** [comment]
> In [#12162 (comment)](https://github.com/NuGet/Home/issues/12162#issuecomment-1838523872), you shows that the `http-cache` directory had user and group ownership `myName:staff`, and the error message reported listed `/Users/MY_USER_NAME/.local/share/NuGet/http-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/vuln_index.dat-new`.
> 
> `MyName` and `MY_USER_NAME` are not the same. Is this just an editing "error", or are the two really different?
> 
> Can you also check the ownership of the `670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json` directory, and any `vuln_index.dat*` files if they exist? I would expect them all to match the account that you're logged in with (`whoami` or `id -un`)

@zivkan : Indeed that is an editing error. I can confirm that all directories are listed under my user name, they have the proper authorization settings:

ls -al ~/.local/share/NuGet/http-cache/
total 0
drwxr-xr-x   3 halcwb  staff    96 Dec  4 13:00 .
drwxr-xr-x   5 halcwb  staff   160 Dec  4 19:33 ..
drwxr-xr-x  87 halcwb  staff  2784 Dec  4 13:43 670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json

Als the files in the directories look Ok (to me):

...
-rw-r--r--   1 halcwb  staff   279710 Dec  4 13:43 vuln_data_base.dat
-rw-r--r--   1 halcwb  staff        2 Dec  4 13:43 vuln_data_update.dat
-rw-r--r--   1 halcwb  staff      519 Dec  4 13:43 vuln_index.dat

**Comment by zivkan** [comment]
It sure would be nice if Apple allowed OSX virtual machines, so I could create one in the cloud to do some testing 😞

NuGet uses standard .NET APIs to create/write/read files, so I'm afraid I just don't have any other ideas. Although, I'd like to confirm you're getting these errors when running `dotnet restore` directly in a shell?  This isn't about restore running in an IDE like VSCode, VS for mac, Rider, or something else? (which might, for some reason be running `dotnet restore` as a different user id, despite still using your account's home directory)

Your `dotnet --info` output says `RID: osx-arm64`, but it's not clear to me if that means you installed the ARM64 .NET SDK, or the x64 .NET SDK. Does OSX on ARM do anything "weird" (permission wise) when running x64 emulation?

https://dotnet.microsoft.com/en-us/download/dotnet/8.0 has binary downloads for both the arm64 and x64 builds of the .NET SDK. Can you download the "other" one, unzip it to some temporary directory, then run `dotnet restore` using that directory's .NET SDK (not the one on the system PATH), and see if there are any differences?

On Linux, `strace dotnet restore` will output all the syscalls. From a quick web search, it's unclear to me if you need to use `dtruss` on OSX, or if strace can be used (installed via homebrew?). Anyway, if you find the appropriate tool, are you able to see anything unusual when NuGet is creating/reading/writing/renaming `vuln_index.dat-new`?

The `vuln_*` files are related to NuGetAudit, which you can turn off by setting it to `false` in a `Directory.Build.props`, or as an environment variable. But there's no reason why NuGetAudit's files are special, so I'd expect that you'll get the same error when NuGet needs to download a package.

It seems very unusual that you say your arm mac has this problem, but the intel mac does not.  Are they both running the same version of OSX, and the .NET SDK, so the "only" difference is CPU architecture?

**Comment by halcwb** [comment]
> It sure would be nice if Apple allowed OSX virtual machines, so I could create one in the cloud to do some testing 😞
> 
Acualy, if you look at: https://github.com/halcwb/GenPres2/actions, you can see that my projects run just fine on a MacOS machine, just not on my M2 notebook.

> NuGet uses standard .NET APIs to create/write/read files, so I'm afraid I just don't have any other ideas. Although, I'd like to confirm you're getting these errors when running `dotnet restore` directly in a shell? This isn't about restore running in an IDE like VSCode, VS for mac, Rider, or something else? (which might, for some reason be running `dotnet restore` as a different user id, despite still using your account's home directory)
> 
I always do my restore, building, testing, etc.. directly from command line. So that is were I see the problem happening.

> Your `dotnet --info` output says `RID: osx-arm64`, but it's not clear to me if that means you installed the ARM64 .NET SDK, or the x64 .NET SDK. Does OSX on ARM do anything "weird" (permission wise) when running x64 emulation?
> 
I don't think I can even run an x64 SDK on an M2??

> https://dotnet.microsoft.com/en-us/download/dotnet/8.0 has binary downloads for both the arm64 and x64 builds of the .NET SDK. Can you download the "other" one, unzip it to some temporary directory, then run `dotnet restore` using that directory's .NET SDK (not the one on the system PATH), and see if there are any differences?
> 
See above, I think this wouldn't work. For example, I cannot run a docker image build for a x64 on my M2 and vice versa.

> On Linux, `strace dotnet restore` will output all the syscalls. From a quick web search, it's unclear to me if you need to use `dtruss` on OSX, or if strace can be used (installed via homebrew?). Anyway, if you find the appropriate tool, are you able to see anything unusual when NuGet is creating/reading/writing/renaming `vuln_index.dat-new`?
> 
hmm, that is not trivial, have to look into that. There is a dtrace, but you need to be in recovery mode to even be able to run that.

> The `vuln_*` files are related to NuGetAudit, which you can turn off by setting it to `false` in a `Directory.Build.props`, or as an environment variable. But there's no reason why NuGetAudit's files are special, so I'd expect that you'll get the same error when NuGet needs to download a package.
> 
What env should I set to disable the audit?, because it only happens with the audit. Nuget can do all the rest.

> It seems very unusual that you say your arm mac has this problem, but the intel mac does not. Are they both running the same version of OSX, and the .NET SDK, so the "only" difference is CPU architecture?
I use both on the same project, so yes.

Thanks for looking into this.

**Comment by zivkan** [comment]
> I don't think I can even run an x64 SDK on an M2??

My understanding is that Apple silicon has some proprietary extensions to the ARM instruction set, in order to provide x86-64 compat (possibly needing [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2)). So, I think it could work, it just won't be native. 🤷   To be clear, my suggestion/question is only for troubleshooting (problem isolation), not a long term suggestion.

> See above, I think this wouldn't work. For example, I cannot run a docker image build for a x64 on my M2 and vice versa.

https://stackoverflow.com/questions/67458621/how-to-run-amd64-docker-images-on-arm64-host-platform

This is the first time you mentioned docker in this issue. Is it just a coincidence because the conversation has gone off-topic from the NuGet issue, or are you having a problem only inside the docker images?  I was under the assumption that everything reported so far is happening on the host machine.

> What env should I set to disable the audit?, because it only happens with the audit. Nuget can do all the rest.

This only happening with the vulnerability files makes me wonder if it's docker related, because I've seen other customers report issues when files copied into a container are read only, and so they get these permission errors, it's because of docker. What I don't know, and what I'm wondering if could be a possible cause of failure, when docker is creating a multi-stage image, if a previous stage creates the `vuln_index.dat` file, when a "child image" tries to overwrite the file, is it also read only? Or is the child image allowed to overwrite a file from a parent image? However, if you're experiencing this issue on the host machine, not in a docker image, then this isn't relevant to this issue.

Anyway, [MSBuild imports environment variables as properties](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2022), so you'd use an environment variable with the same name of the MSBuild property name you want to use, in this case `NuGetAudit`.

**Comment by halcwb** [comment]
> > I don't think I can even run an x64 SDK on an M2??
> 
> My understanding is that Apple silicon has some proprietary extensions to the ARM instruction set, in order to provide x86-64 compat (possibly needing [Rosetta 2](https://en.wikipedia.org/wiki/Rosetta_(software)#Rosetta_2)). So, I think it could work, it just won't be native. 🤷 To be clear, my suggestion/question is only for troubleshooting (problem isolation), not a long term suggestion.
> 
> > See above, I think this wouldn't work. For example, I cannot run a docker image build for a x64 on my M2 and vice versa.
> 
> https://stackoverflow.com/questions/67458621/how-to-run-amd64-docker-images-on-arm64-host-platform
> 
> This is the first time you mentioned docker in this issue. Is it just a coincidence because the conversation has gone off-topic from the NuGet issue, or are you having a problem only inside the docker images? I was under the assumption that everything reported so far is happening on the host machine.
> 
I am sorry for the confusion. The problem is not docker related but is seen directly on my M2 notebook.

> > What env should I set to disable the audit?, because it only happens with the audit. Nuget can do all the rest.
> 
> This only happening with the vulnerability files makes me wonder if it's docker related, because I've seen other customers report issues when files copied into a container are read only, and so they get these permission errors, it's because of docker. What I don't know, and what I'm wondering if could be a possible cause of failure, when docker is creating a multi-stage image, if a previous stage creates the `vuln_index.dat` file, when a "child image" tries to overwrite the file, is it also read only? Or is the child image allowed to overwrite a file from a parent image? However, if you're experiencing this issue on the host machine, not in a docker image, then this isn't relevant to this issue.
> 
> Anyway, [MSBuild imports environment variables as properties](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2022), so you'd use an environment variable with the same name of the MSBuild property name you want to use, in this case `NuGetAudit`.


I'll try that, thanks.

**Comment by nkolev92** [comment]
This is a bit of a long thread. 

@halcwb Any progress here, did turning off NuGet audit help?
I'm guessing it just postpones a problem rather than potentially solving anything.
