### ISSUE TITLE
README.txt does not open for project.json scenarios

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1307]
Although #607 covered opening readme.txt, it only works for packages.config scenarios and not for project.json scenarios.

Need to fix, and also work with DNX folks to fix it in their system

CC @davidfowl

**Comment by yishaigalatzer** [comment]
The fix here, is that when we install from the UI or power shell, we detect new package versions or new packages that got added and open a the readme files.

Preferably we should show the yellow bar with a message showing: "New packages with readme.txt have been installed, click here to open"

**Comment by RanjiniM** [comment]
First part of the fix - open readme files in project.json scenarios is done - https://github.com/nuget/nuget.client/pull/77
