### ISSUE TITLE
Support for GitHub commit tags

### ISSUE THREAD

**Issue by PWagner1** [NuGet/Home#13081]
### NuGet Product(s) Involved

Other/NA

### The Elevator Pitch

It would be great to see support for GitHub commit tags. Say I publish multiple packages over days/weeks/months etc, and I discover a bug in my product months down the line. I go back over the past packages, and discover the version where the bug is introduced. Currently, the only way to track down the issue is by trawling through pull request histories, and trying to match up the PR date with the package publish date, which takes time. By using GitHub commit tags in the NuGet information data, it would save time tracking the bug down.

**Comment by zivkan** [comment]
@Wagnerp The NuGet package manifest (`.nuspec` file) already has support for repository metadata: https://learn.microsoft.com/en-us/nuget/reference/nuspec#repository

If you use the appropriate [SourceLink package](https://www.nuget.org/packages?q=Microsoft.SourceLink&prerel=true&sortby=relevance), and pack via `dotnet pack` or `msbuild -t:Pack`, then the package repository information will be filled out automatically.

Does this meet your needs?

**Comment by PWagner1** [comment]
@zivkan Is this supported in SDK style projects via a tag?

**Comment by nkolev92** [comment]
@Wagnerp Yep, all of those are documented in https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target.
