### ISSUE TITLE
[Pack] The packed package is not in tool folder after executing "nuget pack -tool" command

### ISSUE THREAD

**Issue by SueSu01** [NuGet/Home#13087]
### NuGet Product Used

NuGet.exe

### Product Version

Dev\6.9.0.59

### Worked before?

It reproes on NuGet Client 6.6.0.48

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

**Repro Steps:**

1. Create a C# Class Library (.NET Framework) project named package1 in VS.
2. Build solution.
3. Open “Developer Command Prompt” , cd to the project path.
4. Execute “nuget spec”
5. Execute "nuget pack package1.csproj -tool"
6. Check the output files of the project should be in the tool folder.

**Expected:**

The package file of the project should be in the tool folder.

**Actual:**

The packed package is not in tool folder as below screenshot.
![image](https://github.com/NuGet/Home/assets/149561645/ee1ff747-9825-4b18-9d8e-f4f05c1744ae)

**Note:**

1.Repro rate: 100%.

**Comment by nkolev92** [comment]
I think the folder being referred to is from within the package. 

![image](https://github.com/NuGet/Home/assets/2878341/f74f4643-cb64-48f6-884f-4cf5f8f4cfad)

The doc itself does have a small bug though, which I'll fix: https://learn.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-pack.
