### ISSUE TITLE
In UI for solution, projects checkbox goes from checked to partial selection state automatically

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1308]
In UI for solution, projects checkbox goes from checked to partial selection state automatically

Repro steps:
1. Create a solution with 2 console applications
2. Install Newtonsoft.Json to the first console app
3. Open Manage NuGet Packages for solution with nuget.org as the package source and note that EntityFramework is selected by default.
   ![image](https://cloud.githubusercontent.com/assets/2380340/9613271/3b39dc6e-509f-11e5-8681-4daebdfda5f7.png)
4. Select Newtonsoft.Json which is already installed. Note that on the details section, only ConsoleApplication2 shows up. This is expected.
5. Now, select EntityFramework package

Expected:
It looks like the following with the check box in checked state
![image](https://cloud.githubusercontent.com/assets/2380340/9613276/3eca3de2-509f-11e5-9081-966cf6e67848.png)

Actual:
It looks like the following with the check box in partial selection state
![image](https://cloud.githubusercontent.com/assets/2380340/9613252/178fb914-509f-11e5-97b6-9b254bde8b11.png)

**Comment by feiling** [comment]
Not a problem anymore. The check box status is now kept when a different package is selected.
