### ISSUE TITLE
NuGet visual studio not showing logs when the Build output windows is not opened

### ISSUE THREAD

**Issue by MeniZalzman** [NuGet/Home#1309]
When packages are restored and the build Output windows is not initiated, we are not showing any action logs.

**Comment by yishaigalatzer** [comment]
@MeniZalzman - What is the suggestion here? What happens if you open the build output window after the fact?

**Comment by MeniZalzman** [comment]
All the log entries that we logged will not show up anywhere and the user will not have anything to work with, we need to init the output window or use something that always exist

**Comment by nkolev92** [comment]
NuGet has it's own output pane for non-build operations, and on build we write to the output window.

This has been true for a while now. Closing this.
