### ISSUE TITLE
All user to add comments on a installed nuget package

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#13096]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/All-user-to-add-comments-on-a-installed-/10363496)._

---
It would be helpful to us if you were to have the ability to add a user comment on installed nuget packages.  We have many instances that we cannot update a package because of some bug or other issue.  If we had the ability to comment and also put an icon on the package that was installed, we would not run into issues of installing package updates that may give us an issue.

---
#### Feedback Bot on 5/15/2023, 11:05 PM: 

(private comment, text removed)

**Comment by nkolev92** [comment]
Team Triage: You can add an XML comment in the csproj itself, which could be caught during code review.
