### ISSUE TITLE
Symbol loading from external server

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#13094]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Symbol-loading-from-external-server/1553736)._

---
Hello,

I would like to ask for feature which allows moving the process of loading symbols from external service like Azure DevOps, Microsoft Symbols and Nuget.org Symbols to the background. It prevents developer if he is interested into debugging fast only some part of code that does not use external sources at first.

The origin of the problem is when you use project with many dependencies that does not have published symbols.
As there is a cache for already found symbols that speed up symbol loading and downloading process, there is no process while loading symbols that speeds up determining that some symbols will be not available at all. Thought, each time starting the debug session, the symbol loading will try to find not published symbols on remote servers, if you use more than 1 remote location that will take extra time too. You can of course add manually the name of libraries that does not publish symbols to options in Visual Studio, but it is very time consuming process when you need to as 25-50 libraries like so.
More over each and every developer will have to do this, as those settings are local to the IDE installation.

Therefore one of the proposals I suggest is to put loading into background, so developer can already work with locally available symbols which should be loaded first. And the experience will be better each time the VS finds more symbols on remote server.

Second option that I would suggest is a some button or dialog that summaries not found symbols in external servers, and be able to add them to exclusions so VS does not try to find them again. The problem with solution as so, is that VS will not try to get symbols once those will become available and will require manual action.

Best regards,
Maciej Klemarczyk

---
#### Feedback Bot on 10/14/2021, 03:00 AM: 

(private comment, text removed)

**Comment by zivkan** [comment]
Isn't this a VS debugger request, not a NuGet request?

**Comment by nkolev92** [comment]
Closing as this is a debugger request. 

The original suggestion ticket is open.
