### ISSUE TITLE
CPM doesn't work with non-SDK style projects and static graph restore

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13108]
### NuGet Product Used

MSBuild.exe

### Product Version

internal preview

### Worked before?

public preview

### Impact

I'm unable to use this version

### Repro Steps & Context

Have a non-SDK style project that uses CPM and restore static graph evaluation. Restore behaves as if CPM is disabled.

This regressed in https://github.com/NuGet/NuGet.Client/pull/5528

**Comment by kartheekp-ms** [comment]
Changed the milestone to 6.10 because of https://github.com/NuGet/NuGet.Client/pull/5583#issuecomment-1884007153 comment.
