### ISSUE TITLE
nuget.exe packages config restore throws a commandlineexception on unresolved packages

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1311]
Steps
- Create a packages config file with a missing package:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="madeuppackage2000" version="1.0.7" targetFramework="net452" />
</packages>
```
- _nuget.exe restore packages.config -packagesdirectory packages_

![image](https://cloud.githubusercontent.com/assets/6381138/9618146/5418d770-50b9-11e5-81f2-5eeac6bd5510.png)

The warning and 1st error are expected. The final error is not expected.

**Comment by deepakaravindr** [comment]
Validated with NuGet.exe 3.3.0.9356, that this has been fixed already and does not repro
