### ISSUE TITLE
[Client policy] An error NU3018 “The author primary signature's signing certificate is not trusted by the trust provider” occurs when Install package with trusted signers and package with untrusted root 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13114]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.9.0.67

### Worked before?

It worked in nuget client Dev\6.8.0.101 since we used the "CreateTestCertificate.ps1" file to create certificate but we use "MakeTestCert.csproj" this time. 

### Impact

It's more difficult to complete my work

#### Repro Steps:     

1.Patch dotnet SDK: [Patch dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7B8a3c6685-1661-47f4-8807-b765ca62aea1%7D&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703) 
2.Add NuGet.exe path into System variables and create a package with command "nuget pack .csproj" for testing.   

3.Go to the patchedSDK folder and create a new test certificate:  

`.\dotnet run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net7.0  `

4.Sign a package:  `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath> `

5.Create a project in VS and add required mode in nuget.config file with trusted signers list: (the SHA256 fingerprint is the one in step3) 
```
   <config> 
     <add key="signatureValidationMode" value="require" /> 
   </config> 
   <trustedSigners> 
     <author name="JamieZhang">        
         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="true" /> 
     </author> 
    </trustedSigners> 
```
		
6. Reload the solution in VS, update the package source to the signed package path above (in step4) and install the package into the project in PM UI.
#### Expected:     

The signed package was successfully installed into the project without any error. 

#### Actual:        

The package failed to install with error NU3018 “The author primary signature's signing certificate is not trusted by the trust provider” as below: 
![MicrosoftTeams-image (1)](https://github.com/NuGet/Home/assets/84695155/faa58f4a-05ef-424a-a1ee-221d3d99a669)
#### Notes:    

1.The repro rate is 100%.  
2.It also reproes VS 17.8 (D17.8\34309.116 with implicit NuGet 6.8.0.131).

**Comment by martinrrm** [comment]
I wasn't able to reproduce this in my local machine, VS version Version 17.9.0 Preview 1.0 and I didn't patched SDK, using **8.0.200-preview.23624.5**

**Comment by CiciLi1** [comment]
Hi @martinrrm,I verified this issue with the unpatched SDK using **8.0.200-preview.23620.12**, this issue can also be reproduced as below:
![image](https://github.com/NuGet/Home/assets/84695155/e16c3289-6e6c-40c5-bf55-b5c850dbd191)

**Comment by nkolev92** [comment]
Team Triage: Hey @dtivel, would you mind taking a look at this issue, and help us understand whether there's a test setup issue or a product issue. 

Thanks!

**Comment by dtivel** [comment]
@CiciLi1, you said that previously this test passed when you used CreateTestCertificate.ps1.  Can you please provide the exact statement you used for CreateTestCertificate.ps1 --- all arguments.  In particular, did you use `-AddAsTrustedRootAuthority`?

**Comment by CiciLi1** [comment]
> @CiciLi1, you said that previously this test passed when you used CreateTestCertificate.ps1. Can you please provide the exact statement you used for CreateTestCertificate.ps1 --- all arguments. In particular, did you use `-AddAsTrustedRootAuthority`?

Hi @dtivel, we previously used the exact statement in the nuget client Dev\6.8.0.101 with the statement `. \CreateTestCertificate.ps1" and did not use "-AddAsTrustedRootAuthority".

**Comment by dtivel** [comment]
@CiciLi1, I'm going to guess that you're copying the SHA-256 fingerprint output by MakeTestCert into your nuget.config file and it fails.  However, if you upper-case the fingerprint in nuget.config, it should succeed.

Please confirm.

**Comment by dtivel** [comment]
@CiciLi1, if it helps, Visual Studio has a command which can take the selected text and make it upper case.

![image](https://github.com/NuGet/Home/assets/12734758/0857fae0-7591-4e15-bb99-35fd9b26330c)

**Comment by CiciLi1** [comment]
> @CiciLi1, I'm going to guess that you're copying the SHA-256 fingerprint output by MakeTestCert into your nuget.config file and it fails. However, if you upper-case the fingerprint in nuget.config, it should succeed.
> 
> Please confirm.

Hi @dtivel, the case work well when the fingerprint is upper-case in the nuget.config file, I will close this issue. Thanks for your help.
