### ISSUE TITLE
[Signing] Verifying a signed package failed with an error "NU3034: This package is signed but not by a trusted signer" when signing without using CertificatePassword 

### ISSUE THREAD

**Issue by SueSu01** [NuGet/Home#13113]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.9.0.67

### Worked before?

It worked in nuget client Dev\6.8.0.101 since we used the " CreateTestCertificate.ps1 " file to create certificate but we use " MakeTestCert.csproj" this time.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

**Repro steps:**

1.Patch dotnet SDK: [Patch dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7B8a3c6685-1661-47f4-8807-b765ca62aea1%7D&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703)
2.Add NuGet.exe path into System variables and create a package with command "nuget pack .csproj" for testing.
3. Go to the patchedSDK folder and create a new test certificate:
`.\dotnet run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net7.0 --Password password`
4. Where CertificateFilePath is the file path to the created certificate (in step3) .cer or .pem file, add trust for the certificate:
`.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net7.0 -- add -c <CertificateFilePath>` 
5. In another "Developer Command Prompt", cd to the path of "NuGet.exe" and sign a package:
`NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>`
6. Enter the password: password.
7. Verify the correct certificate was used and no errors or warnings (except for warning NU3002 if you didn't use: "-Timestamper").
8. Verify the package was signed:  `NuGet.exe verify -signatures <PackageFilePath>`

**Expected:**
Verify the package was signed successfully.

**Actual:**
Verifying a signed package failed with an error "NU3034: This package is signed but not by a trusted signer" as below screenshot. 
![image](https://github.com/NuGet/Home/assets/149561645/f3d5b7e7-4535-4a59-8409-a213c3774d66)

**Note:**   
  The repro rate is 100%.

**Comment by martinrrm** [comment]
I wasn't able to reproduce this in my local machine, VS version Version 17.9.0 Preview 1.0 and I didn't patched SDK, using **8.0.200-preview.23624.5**

**Comment by SueSu01** [comment]
> I wasn't able to reproduce this in my local machine, VS version Version 17.9.0 Preview 1.0 and I didn't patched SDK, using **8.0.200-preview.23624.5**

@martinrrm I verified this issue with the unpatched SDK using **8.0.200-preview.23620.12**, it can also be reproduced as below:
![image](https://github.com/NuGet/Home/assets/149561645/0426cbc0-a9c4-4e77-aa47-4f9db5f7b931)

**Comment by nkolev92** [comment]
Likely related to https://github.com/NuGet/Home/issues/13114. We're just monitoring that thread in order to avoid fragmenting the conversation.

**Comment by nkolev92** [comment]
@SueSu01 Is this still reproing after the casing fixes for the fingerpint.

**Comment by SueSu01** [comment]
> @SueSu01 Is this still reproing after the casing fixes for the fingerpint.

@nkolev92 This issue does not repro, so I close it, thanks.
