### ISSUE TITLE
[Signing] Package signing failed with an error: "NU3001: No certificates were found that meet all the given criteria." after nuget signing a package with certificate comes from LocalMachine certificate store

### ISSUE THREAD

**Issue by SueSu01** [NuGet/Home#13112]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Client Dev\6.9.0.67

### Worked before?

It worked in nuget client Dev\6.8.0.101 since we used the "CreateTestCertificate.ps1" file to create certificate but we use "MakeTestCert.csproj" this time.

### Impact

It's more difficult to complete my work

### Repro Steps & Context

**Repro steps:**

1.Patch dotnet SDK: [Patch dotnet SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7B8a3c6685-1661-47f4-8807-b765ca62aea1%7D&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703)
2.Add NuGet.exe path into System variables and create a package with command "nuget pack .csproj" for testing.
3. Go to the patchedSDK folder and create a new test certificate:
`.\dotnet run --project .\Entropy\MakeTestCert\MakeTestCert.csproj --framework net8.0 -UseLocalMachineStore`
4. Where _CertificateFilePath_ is the file path to the created certificate (in step3) .cer or .pem file, add trust for the certificate:
`.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net8.0 -- add -c <CertificateFilePath> -UseLocalMachineStore`
5. In another "Developer Command Prompt", cd to the path of "NuGet.exe" and sign a package, where _Fingerprint_ is the Fingerprint (SHA-1) from step 3:
`NuGet.exe sign <PackageFilePath> -CertificateStoreLocation LocalMachine -CertificateStoreName Root -CertificateFingerprint <Fingerprint>`
6. Verify the correct certificate was used and no errors or warnings (except for warning NU3002 if you didn't use: "-Timestamper").

**Expected:**
Package signing is successful and no error or warnings (except for warning NU3002 if you didn't use: "-Timestamper").

**Actual:**
Package signing failed with an error: "NU3001: No certificates were found that meet all the given criteria." after nuget signing a package with certificate comes from LocalMachine certificate store as below screenshot.
![image](https://github.com/NuGet/Home/assets/149561645/c0eb8abf-7089-4941-9ebc-91ea7cfb0a80)

**Note:**   
The repro rate is 100%.

**Comment by martinrrm** [comment]
I can reproduce this behavior in my local machine

**Comment by nkolev92** [comment]
Likely related to https://github.com/NuGet/Home/issues/13114. We're just monitoring that thread in order to avoid fragmenting the conversation.

**Comment by SueSu01** [comment]
> Likely related to #13114. We're just monitoring that thread in order to avoid fragmenting the conversation.

Hi @nkolev92 As mentioned in https://github.com/NuGet/Home/issues/13114, the test case still fails when we using the fingerprint in upper-case in [Dotnet nuget sign command: sign when certificate comes from LocalMachine certificate store](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target(Package+Signing+Manual+Test.one%7c0344a15b-01b1-4828-af4c-63fe53687f8a%2fDotnet+nuget+sign+command++sign+when+certificate+comes+from+%7ca26b8930-8704-44df-8814-b484ece0a298%2f)&wdorigin=703&xsdata=MDV8MDJ8di1jaWNpbGlAbWljcm9zb2Z0LmNvbXxiMThjYzU1OTkxMzY0ZGQzN2NmODA4ZGMwYjM2OGZmYnw3MmY5ODhiZjg2ZjE0MWFmOTFhYjJkN2NkMDExZGI0N3wxfDB8NjM4Mzk3NTc2MjM5NjE0NzQwfFVua25vd258VFdGcGJHWnNiM2Q4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazFoYVd3aUxDSlhWQ0k2TW4wPXwzMDAwfHx8&sdata=TjBsZzBaYVd0TlYxWng4d244R1p0NnNmc3BKNlFDdTVtbldqWjRJVldLZz0%3d) in Cross-Platform Dotnet NuGet Sign Test.

**Comment by nkolev92** [comment]
@dtivel 

It seems the casing fix in the fingerprint is not addressing this problem. 
Can you help us understand whether this is a setup problem or a real bug?

**Comment by dtivel** [comment]
@SueSu01, looking at your provided repro steps, I see that you used TrustTestCert tool with one of the following syntaxes:

![image](https://github.com/NuGet/Home/assets/12734758/21898753-ff20-459f-b171-c09d3db5937e)

As explained [here](https://github.com/NuGet/Entropy/tree/main/TrustTestCert#windows), you'll want to pass the .cer file to TrustTestCert if you are signing using a .pfx file.  However, you'll want to pass the .pfx file to TrustTestCert if you are signing using a certificate in a Windows certificate store.

That said, note that TrustTestCert's `add` command adds the certificate to the _current user's_ root store, not the local machine's root store.  However, you told NuGet.exe to look in the local machine's root store with `-CertificateStoreLocation LocalMachine`.  Try using `-CertificateStoreLocation CurrentUser` instead.

**Comment by SueSu01** [comment]
> @SueSu01, looking at your provided repro steps, I see that you used TrustTestCert tool with one of the following syntaxes:
> 
> ![image](https://private-user-images.githubusercontent.com/12734758/305213861-21898753-ff20-459f-b171-c09d3db5937e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE3NjQsIm5iZiI6MTcwODMxMTQ2NCwicGF0aCI6Ii8xMjczNDc1OC8zMDUyMTM4NjEtMjE4OTg3NTMtZmYyMC00NTlmLWIxNzEtYzA5ZDNkYjU5MzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNWFkMjI3NWNlMjcyNzZjYmYyMDkyMzIzYjk5Y2E3OThkOWMxZGI1YzA4YzU0N2RjZjZjYWJlNzU5NjE4MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vOCJNXFRDb333T_0wxo47uq8kPoz9dDvO6OLpMYgoeE)
> 
> As explained [here](https://github.com/NuGet/Entropy/tree/main/TrustTestCert#windows), you'll want to pass the .cer file to TrustTestCert if you are signing using a .pfx file. However, you'll want to pass the .pfx file to TrustTestCert if you are signing using a certificate in a Windows certificate store.
> 
> That said, note that TrustTestCert's `add` command adds the certificate to the _current user's_ root store, not the local machine's root store. However, you told NuGet.exe to look in the local machine's root store with `-CertificateStoreLocation LocalMachine`. Try using `-CertificateStoreLocation CurrentUser` instead.

@dtivel The case works fine when using `-CertificateStoreLocation CurrentUser` , I will close this issue, thanks for your help.

**Comment by v-luzh** [comment]
Hi @dtivel, the associated test case of this bug is: "[536708 sign command: sign when certificate comes from LocalMachine certificate store](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2F536708%20sign%20command%20%20sign%20when%20certificate%20comes%20from%20LocalMachine%20%7C1ffb2699-5840-4a9d-90a4-dcbc6d4207da%2F%29&wdorigin=703)". If we use `-CertificateStoreLocation CurrentUser`, that will be the previous test case: "[536707 sign command:  sign when certificate comes from CurrentUser certificate store](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2F536707%20sign%20command%20%20sign%20when%20certificate%20comes%20from%20CurrentUser%20%7Cf004fa2f-1787-47d8-a113-67077d3c880e%2F%29&wdorigin=703)". So we used the` -CertificateStoreLocation LocalMachine` when signing in step5 because we use "-UseLocalMachineStore" when making certificate in step3. 

And we just tried `.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net8.0 -- add -c <CertificateFilePath> -UseLocalMachineStore` in step4 and "`NuGet.exe sign <PackageFilePath> -CertificateStoreLocation LocalMachine -CertificateStoreName Root -CertificateFingerprint <Fingerprint>(with upper-case)`", but it still failed as the original actual result above. 

Could you help to confirm if the "LocalMachine certificate store" is not supported in the new "MakeTestCert.csproj" now? If yes, do we need to delete this outdated test case? I will reopen this bug for tracking this issue.

**Comment by dtivel** [comment]
`-UseLocalMachineStore` is not an option for the TrustTestCert tool.  You can see all available options by running any of the following:

* `.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net8.0 -- -?`
* `.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net8.0 -- -h`
* `.\dotnet run --project .\Entropy\TrustTestCert\TrustTestCert.csproj --framework net8.0 -- --help`

> Could you help to confirm if the "LocalMachine certificate store" is not supported in the new "MakeTestCert.csproj" now?

The old PowerShell script did 2 operations:  1) create a test certificate and 2) optionally add trust.  I've split these operations into 2 separate tools:  MakeTestCert and TrustTestCert, respectively.  MakeTestCert does not support any stores.  Use TrustTestCert to add/remove certificates to/from certificate stores.

I [updated](https://github.com/NuGet/Entropy/pull/111) the TrustTestCert tool to accept a new option, excerpted below:

```
  Option                              Description
  ----------------------------------- -------------------------------------------
  --certificate-store-location, -csl  The certificate store location, either
                                      CurrentUser or LocalMachine.
                                      On Windows, the default is CurrentUser,
                                      and LocalMachine requires elevation.
                                      On Linux/macOS, this option is never used.
```

The full readme is [here](https://github.com/NuGet/Entropy/tree/main/TrustTestCert#readme).

On Windows, without this option, TrustTestCert still adds/removes certificates to/from the current user's certificate root store.  With this option set to `LocalMachine`, TrustTestCert still adds/removes certificates to/from the local machine's certificate root store.  Examples:

```
    TrustTestCert.exe add -c .\test.cer -csl LocalMachine
      Adds the certificate to the local machine's root store.

    TrustTestCert.exe add -c .\test.pfx -csl LocalMachine
      Adds the certificate and its private key to the local machine's root store.

    TrustTestCert.exe remove -c .\test.cer -csl LocalMachine
      Removes the certificate from the local machine's root store.
```

Note that this new option is only available on Windows.  Also note that adding/removing certificates to/from the local machine root store requires an elevated prompt.

**Comment by v-luzh** [comment]
Hi @dtivel Thanks for your quick fixing and detailed description. We have updated the test cases.
