### ISSUE TITLE
NuGet not respecting local cache

### ISSUE THREAD

**Issue by Nefcanto** [NuGet/Home#13118]
### NuGet Product(s) Affected

MSBuild.exe, dotnet.exe

### Current Behavior

NuGet does not honor the locale cache. We have restored a project with many packages in a docker image to cache images so that we can run an app without an internet connection, but we get this error:

```
ApiContainer | MSBuild version 17.8.3+195e7f5a3 for .NET
ApiContainer |   Determining projects to restore...
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Project/AdminApi/Api.csproj]
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   Resource temporarily unavailable (api.nuget.org:443) [/Project/AdminApi/Api.csproj]
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   Resource temporarily unavailable [/Project/AdminApi/Api.csproj]
ApiContainer | 
ApiContainer | Build FAILED.
ApiContainer | 
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/Project/AdminApi/Api.csproj]
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   Resource temporarily unavailable (api.nuget.org:443) [/Project/AdminApi/Api.csproj]
ApiContainer | /usr/share/dotnet/sdk/8.0.100/NuGet.targets(156,5): error :   Resource temporarily unavailable [/Project/AdminApi/Api.csproj]

```

### Desired Behavior

When packages are cached once, NuGet should use them if the internet connection is not available. Preferably it should use them and not connect to the internet at all, even if it's available. Because packages are already there on the disk.

### Additional Context

This is our `Dockerfile`:

```
# https://mcr.microsoft.com/v2/vscode/devcontainers/dotnet/tags/list
# https://mcr.microsoft.com/v2/devcontainers/dotnet/tags/list
# https://github.com/devcontainers/images/blob/main/src/dotnet/.devcontainer/Dockerfile
# https://hub.docker.com/_/microsoft-dotnet-sdk
ARG VARIANT="8.0-bookworm-slim"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:${VARIANT}

ENV PATH="${PATH}:/HolismHolding/Commands/ApiContainer:/HolismHolding/Commands"

ENV Nuget=/root/.local/share/NuGet/http-cache/

COPY . /HolismApi/Infra

RUN mkdir /Temp \
    && cd /Temp \
    && dotnet new console \
    && echo '<Project Sdk="Microsoft.NET.Sdk.Web"><Import Project="/HolismApi/Infra/DotNet.targets" /></Project>' > /Temp/Temp.csproj \
    && echo 'System.Console.WriteLine("hello");' > /Temp/Program.cs \
    && dotnet restore \
    && dotnet build \
    && cd / \
    && rm -rf /Temp

RUN apt update -qq \
    && mkdir -p /Temp/ImageResizingAndCompression \
    && chmod 777 --preserve-root /Temp/ImageResizingAndCompression \
    && mkdir -p /Temp/VideoConversion \
    && chmod 777 --preserve-root /Temp/VideoConversion \
    && apt install bc -qq -y \
    && apt install procps -qq -y \
    && apt install file -qq -y \
    && apt install gettext-base -qq -y \
    && apt install apt-utils -qq -y \
    && apt install libgdiplus -qq -y \
    && apt install inotify-tools -qq -y \
    && apt install libc6-dev -qq -y \
    && apt install webp -qq -y \
    && apt install telnet -qq -y \
    && apt install dnsutils -qq -y \
    && apt install imagemagick -qq -y \
    && apt install ffmpeg -qq -y \
    && cd /usr/local/bin \
    && curl https://getmic.ro | bash
```

As you can see we create a `Temp.csproj` that has a `Import`. This is what it imports:

```
<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>.\bin</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <Import Project="/HolismApi/Infra/Nuget.targets" />

  <ItemGroup>
    <None Include="./Settings.json" Condition="Exists('./Settings.json')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="./SettingsOverride.json" Condition="Exists('./SettingsOverride.json')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="./LocalSecrets.json" Condition="Exists('./LocalSecrets.json')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="./ConnectionStrings.json" Condition="Exists('./ConnectionStrings.json')" >
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

And this is our `Nuget.targets`:

```
<Project>

  <ItemGroup>

    <PackageReference Include="AngleSharp" Version="1.0.7" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.19.1" />
    <PackageReference Include="Bogus" Version="35.2.0" />
    <PackageReference Include="ClosedXML" Version="0.102.1" />
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="Humanizer.Core" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.ar" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.fa" Version="2.14.1" />
    <PackageReference Include="Humanizer.Core.ru" Version="2.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.0.3" />
    <PackageReference Include="morelinq" Version="4.1.0" />
    <PackageReference Include="MySqlConnector" Version="2.3.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.NetTopologySuite" Version="7.0.0" />
    <PackageReference Include="SocketIOClient" Version="3.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.3.7" />
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
    <!-- <PackageReference Include="AngouriMath" Version="1.3.0" /> -->

  </ItemGroup>

</Project>

```

And then we do `dotnet restore` and `dotnet build` to make sure that our dependencies are cached once and our project can be built.

Then we use this image in an environment without internet access. When we upgraded to dotnet 8, it broke.

**Comment by martinrrm** [comment]
Hi! I believe that since you have `https://api.nuget.org/v3/index.json` as a source and it's not configured with Package Source Mapping it will try to find the package.  https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping

What you can do is add a source that points to your folder with the cached packages. For example, this is my configuration for offline packages. You can access this window in VS.

![image](https://github.com/NuGet/Home/assets/43253759/4fc0c277-e282-45c6-af91-229ad581f10f)

**Comment by Nefcanto** [comment]
@martinrrm, I read the link you provided. Thank you for answering and helping.

From the link you sent, I think we should create a `nuget.config` at the root of our project, and add two items to the `packageSource` element, and the first one should be the physical path of the NuGet. However, where should I find the NuGet cache?

The point is we don't use VS, we use VS Code and we don't run code on our machine. We run code inside docker containers. We develop them on our machine, and they are mapped inside a container in which .NET and other required stuff are installed.

**Comment by donnie-msft** [comment]
I don't have much docker experience with NuGet, so please tell me where I'm wrong:

- Your code above has this line `ENV Nuget=/root/.local/share/NuGet/http-cache/`
- What I'm wondering is if that's actually picked up by NuGet? I don't think "Nuget" is an envvar we look for.

- In this doc, these snippets look as if they may be relevant to you:

> Mac/Linux: ~/.local/share/NuGet/v3-cache
> Override using the NUGET_HTTP_CACHE_PATH environment variable.

https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders
    I'd try to use the Mac/Linux path if possible, but if not, try using the override env var.

**Comment by Nefcanto** [comment]
@donnie-msft, that `ENV Nuget=...` is just our internal variable. We used to debug some stuff by going into the Nuget cache directory and searching for things. We didn't want to write that long path again and again. Thus we created an environment variable for it. So that has nothing to do with Nuget. It's a simple internal thing.

I'll read the link you provided to see if it's helpful or not. Thank you.

**Comment by Nefcanto** [comment]
I ran `dotnet nuget locals all --list` and this is the response:

```
http-cache: /root/.local/share/NuGet/http-cache
global-packages: /root/.nuget/packages/
temp: /Temp/NuGet
plugins-cache: /root/.local/share/NuGet/plugin-cache
```

The `/Temp/NuGet` is set using this line in our `docker-compose.yml` file:

```
      - NUGET_SCRATCH=/Temp/NuGet
```

But other paths are not modified. And when I look into the `/root/.nuget/packages/` I see more than 300 MBs of packages being listed. Yet we still see that NuGet tries to connect to the internet to restore the packages.

Could it be because of the root user? Because I remember that Microsoft is very restrictive about using the root user, while we prefer to run with the root user.

I used this script to get some stats for each directory:

```
dotnet nuget locals all --list |
cut -d":" -f2 |
while read dir;
do
    Count=$(find $dir -maxdepth 1 -mindepth 1 2>/dev/null | wc -l)
    Size=$(du $dir -h -cksh 2>/dev/null | grep total | cut -d"t" -f 1)
    echo "$dir-$Count-$Size"
done
```

And this is the result:

```
/root/.local/share/NuGet/http-cache-1-144M	
/root/.nuget/packages/-147-372M	
/Temp/NuGet-1-8.0K	
/root/.local/share/NuGet/plugin-cache-0-0
```

As you can see I have a large cache in `global-package` and `http-cache`. Yet NuGet still goes for the internet.

**Comment by donnie-msft** [comment]
Thanks for sending that. I agree that the configuration appears good.

Next thought is NuGet Audit. This will attempt to reach out to nuget.org in order to pull vulnerability data. You can try disabling this to see if that's what's reaching out to nuget.org and causing your error. For more information, see https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages#disabling-security-auditing

Beyond that, there are other scenarios that Restore would need to reach out to sources and not just rely on what's in your GPF folders. 
Some food-for-thought questions:
1. Are any packages being downloaded (if so, where are they defined)? 
1. None of your PackageReferences are floating versions.

**Comment by Nefcanto** [comment]
@donnie-msft, that was the culprit right there. I added:

```
<NuGetAudit>false</NuGetAudit>
```

And now it works without an internet connection. Such a frustrating experience. Took us many weeks after upgrading to .NET 8.
Thank you so much for your help and time. You saved us.
