### ISSUE TITLE
Nuget.exe not installing latest package

### ISSUE THREAD

**Issue by FerdinandStapenhorst** [NuGet/Home#13139]
### NuGet Product Used

NuGet.exe

### Product Version

6.8.0.131

### Worked before?

no

### Impact

I'm unable to use this version

### Repro Steps & Context

See screen shot:
- I update to latest nuget.exe
- I deleted all local package versions from .nuget folder
- I list the latest package which is 10.1.20
- I run install and only the previous version is found

<img width="1207" alt="Screenshot 2024-01-08 at 19 02 09" src="https://github.com/NuGet/Home/assets/118904606/b8286c6c-ee8e-435d-8d6d-367280af80cb">

### Verbose Logs

```shell
C:\WINDOWS\system32>nuget list DrivveDmXmlServer.Distribution -source https://172.20.0.7:8443/repository/nuget-hosted/ -Verbosity detailed
NuGet Version: 6.8.0.131
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://172.20.0.7:8443/repository/nuget-hosted/$metadata
  OK https://172.20.0.7:8443/repository/nuget-hosted/$metadata 421ms
Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
  GET https://172.20.0.7:8443/repository/nuget-hosted/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='DrivveDmXmlServer.Distribution'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
  OK https://172.20.0.7:8443/repository/nuget-hosted/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='DrivveDmXmlServer.Distribution'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 705ms
DrivveDmXmlServer.Distribution
 10.1.20
 DrivveDmXmlServer Distribution


C:\WINDOWS\system32>nuget install DrivveDmXmlServer.Distribution -source https://172.20.0.7:8443/repository/nuget-hosted/ -Verbosity detailed
NuGet Version: 6.8.0.131
Feeds used:
  https://172.20.0.7:8443/repository/nuget-hosted/

Installing package 'DrivveDmXmlServer.Distribution' to 'C:\WINDOWS\system32'.
  CACHE https://172.20.0.7:8443/repository/nuget-hosted/FindPackagesById()?id='DrivveDmXmlServer.Distribution'&semVerLevel=2.0.0


Attempting to gather dependency information for package 'DrivveDmXmlServer.Distribution.10.1.19' with respect to project 'C:\WINDOWS\system32', targeting 'Any,Version=v0.0'
Package DrivveDmXmlServer.Distribution from source Drivve Intern gathered from cache.
Total number of results gathered : 1
Gathering dependency information took 31 ms
Summary of time taken to gather dependencies per source :
Attempting to resolve dependencies for package 'DrivveDmXmlServer.Distribution.10.1.19' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'DrivveDmXmlServer.Distribution.10.1.19'
Resolved actions to install package 'DrivveDmXmlServer.Distribution.10.1.19'
Retrieving package 'DrivveDmXmlServer.Distribution 10.1.19' from 'Drivve Intern'.
  GET https://172.20.0.7:8443/repository/nuget-hosted/DrivveDmXmlServer.Distribution/10.1.19
  OK https://172.20.0.7:8443/repository/nuget-hosted/DrivveDmXmlServer.Distribution/10.1.19 2170ms
Acquiring lock for the installation of DrivveDmXmlServer.Distribution 10.1.19
Acquired lock for the installation of DrivveDmXmlServer.Distribution 10.1.19
```

**Comment by jebriede** [comment]
@FerdinandStapenhorst it sounds like this may be an issue related to the http-cache not reflecting the package source. You can see where the http cache is located with the following command:
`dotnet nuget locals http-cache --list`

and then clear it with:
`dotnet nuget locals http-cache --clear`

After you've cleared the http-cache, please try installing the package again and let us know if that worked. For reference on clearing the NuGet caches, please see: https://learn.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders#clearing-local-folders.

**Comment by FerdinandStapenhorst** [comment]
Hello,

thank you for your reply. Clearing the cache helped and the package was installed.
I assume it has to do with the fact that the time between pushing a new package and then installing it using the *-notation is too close.

Is there a way to generally disable the http-cache? Because this behaviour might come up again?
Thanks.

**Comment by jeffkl** [comment]
@FerdinandStapenhorst `nuget install` has a `-NoCache` command-line argument to disable the HTTP cache during that invocation.
