### ISSUE TITLE
Package restore fails during docker builds

### ISSUE THREAD

**Issue by Ben305** [NuGet/Home#13148]
### NuGet Product Used

Other/NA

### Product Version

mcr.microsoft.com/dotnet/sdk:7.0

### Impact

I'm unable to use this version

### Repro Steps & Context

Since today we cannot build docker images in GitLab CI any longer, because the packages cannot be restored. Other calls to webservices during the docker build can be completed successfully, so there is no network error.

```
$ (cd src/WebApi && dotnet publish "WebApi.csproj" -c Release -o publish)
MSBuild version 17.7.4+3ebbd7c49 for .NET
  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/grpc.tools/index.json'.
  Response status code does not indicate success: 502 (Bad Gateway).
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.mvc.core/index.json'.
  Response status code does not indicate success: 502 (Bad Gateway).
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/firebaseadmin/index.json'.
  Response status code does not indicate success: 502 (Bad Gateway).
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.entityframeworkcore.design/index.json'.
```

**Comment by Balkoth** [comment]
Seeing this too, in my case its not even the same package i will get the error on.

**Comment by DamianBorndorff** [comment]
We're also facing similar issues while trying to restore in Azure Devops Pipelines:

>  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.linux-x64/index.json'.
         Response status code does not indicate success: 502 (Bad Gateway).
         Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
           GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/index.json
           BadGateway https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/index.json 1ms
         Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/index.json'.
         Response status code does not indicate success: 502 (Bad Gateway).
         Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.
           GatewayTimeout https://api.nuget.org/v3-flatcontainer/testing.vstsexecutor/index.json 4006ms

[...]

edit: yesterday everything worked fine

**Comment by Ben305** [comment]
Can confirm, yesterday the pipelines could be executed sucessfully.

**Comment by Keartland** [comment]
Also getting this in my pipelines today, yesterday they ran fine


dotnet:8

**Comment by jdunnink** [comment]
+1

**Comment by ianbeemsterboerr** [comment]
Same here

**Comment by emre6943** [comment]
😿

**Comment by tibuprophen** [comment]
Same here. I guess there are some kind of server-infrastructure issues

**Comment by Keartland** [comment]
seems to be fixed for me now

**Comment by Balkoth** [comment]
Not here...

**Comment by DamianBorndorff** [comment]
nope for me neither..

it seems to work sometimes and sometimes not tbh, when it works then after a lot of retries

**Comment by Keartland** [comment]
ah yeah had a lucky run i guess, had another failing pipeline

**Comment by OllowainT** [comment]
Currently, we are lucky that we are using a nuget cache in our company. Cached packages are still buildable, but packages, not cached yet, cannot be downloaded from nuget. We saw different behaviours and failed request within same nuget.org IPs. It worked for a while, then it started again to fail.

**Comment by ryanbowden** [comment]
https://status.dev.azure.com/_event/457938891  Worth watching the ADO status page around this issue.

**Comment by jszwab** [comment]
We observe this error when trying to connect to the nuget API from eu-central-1. From us-east-1 it works fine

**Comment by ZeroMD** [comment]
> https://status.dev.azure.com/_event/457938891 Worth watching the ADO status page around this issue.

This issue is closed, a new one is reported:
https://status.dev.azure.com/_event/457957898

**Comment by ryanbowden** [comment]
Seems all our pipelines working now. for now :D

**Comment by Balkoth** [comment]
Still failing here:

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass15_0`1.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync[T](String filePath, Func`2 action, CancellationToken token)
   at NuGet.Protocol.HttpSource.GetAsync[T](HttpSourceCachedRequest request, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.LoadRegistrationIndexAsync(HttpSource httpSource, Uri registrationUri, String packageId, SourceCacheContext cacheContext, Func`2 processAsync, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, VersionRange range, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
   at NuGet.Protocol.PackageMetadataResourceV3.GetMetadataAsync(String packageId, Boolean includePrerelease, Boolean includeUnlisted, SourceCacheContext sourceCacheContext, ILogger log, CancellationToken token)
```

**Comment by tibuprophen** [comment]
Still failing here too

**Comment by ZeroMD** [comment]
here three

**Comment by Wibble199** [comment]
> > https://status.dev.azure.com/_event/457938891 Worth watching the ADO status page around this issue.
> 
> This issue is closed, a new one is reported: https://status.dev.azure.com/_event/457957898

Seems that issue has been deleted? It leads to a 404 page. https://status.dev.azure.com/ is reporting that everything is fine.

**Comment by DamianBorndorff** [comment]
> > https://status.dev.azure.com/_event/457938891 Worth watching the ADO status page around this issue.
> 
> This issue is closed, a new one is reported: https://status.dev.azure.com/_event/457957898

also closed

**Comment by mindekm** [comment]
Still seeing intermittent failures when running restore from eu-central-1

**Comment by oshicollins** [comment]
same here, problems with eu-central-1 region

**Comment by Ben305** [comment]
Still not working from AWS

**Comment by Michriko** [comment]
Still having the issue when restoring my projects. Doesn't matter if local, local container or container build within CI.
Location: Germany

Curl / Browser Requests to api.nuget.org also occasionally fail.

**Comment by KamilChlodek** [comment]
Same here. AWS, Oracle Cloud (Germany).

**Comment by Pabzt** [comment]
Same here.

**Comment by anthonybouton** [comment]
My codebuild builds in eu-central-1 are looking good again, no more 502 ( for now )

**Comment by Keartland** [comment]
still the same error occasionally

**Comment by chrisbrook83** [comment]
This is definitely an issue with the UK / European Nuget cluster. We redirected api.nuget.org to a north American IP address and the problems have gone

**Comment by clarazuto** [comment]
Going through some similar issues. (UK) 
It failed interminably yesterday but we managed to deploy. This morning its been impossible, it keeps failing
Curl / Browser Requests to api.nuget.org work fine for us

ERRORS
Failed to retrieve information about 'Amazon.Lambda.APIGatewayEvents' from remote source 'https://api.nuget.org/v3-flatcontainer/amazon.lambda.apigatewayevents/index.json'
Failed to retrieve information about 'System.ObjectModel' from remote source 'https://api.nuget.org/v3-flatcontainer/system.objectmodel/index.json'.

**Comment by jszwab** [comment]
@chrisbrook83 good trick. Thx

**Comment by brkzr** [comment]
`dotnet restore` gives 502 but pipeline run successfully with `--disable-parallel` command. fyi

`dotnet restore --disable-parallel`

**Comment by Onik97** [comment]
Seems like its happening more in the UK
502 & 504 errors
I was hoping they update this page 
https://status.nuget.org/

**Comment by kapelan** [comment]
The same here in UK South region

**Comment by dulcisclade** [comment]
still the same for eu-west-2

**Comment by aliokn** [comment]
We were also getting this error in UK, we ran  `systemd-resolve --flush-caches` `resolvectl flush-caches` commands to our system, containers working fine right now.

**Comment by SalihKARAHAN** [comment]
> We were also getting this error in UK, we ran `systemd-resolve --flush-caches` `resolvectl flush-caches` commands to our system, containers working fine right now.

I agree with him

**Comment by ZeroMD** [comment]
It's working again in AWS germany

**Comment by jfreeland** [comment]
Can https://status.nuget.org/ provide an RSS feed?  I'd like to be able to subscribe to the feed in my feed Slack channel.

And can status.nuget.org be updated when these issues happen?  I also bumped into this yesterday.

It looks like https://github.com/NuGet/NuGetGallery/issues/9775#issuecomment-1887433227 suggests this was a known issue but the status page wasn't updated?  cc: @zhhyu

**Comment by jeffkl** [comment]
We believe that this is resolved, please let us know if anyone is still experiencing the issue.

**Comment by zhhyu** [comment]
> Can https://status.nuget.org/ provide an RSS feed? I'd like to be able to subscribe to the feed in my feed Slack channel.
> 
> And can status.nuget.org be updated when these issues happen? I also bumped into this yesterday.
> 
> It looks like [NuGet/NuGetGallery#9775 (comment)](https://github.com/NuGet/NuGetGallery/issues/9775#issuecomment-1887433227) suggests this was a known issue but the status page wasn't updated? cc: @zhhyu

Hi! My sincere apologies for this outage! There was a monitoring gap, and the regression was not caught in time. Otherwise, the failover should have been executed and the status page should be updated, when the outage of our dependency just started happening.

I created an issue for the RSS feed at https://status.nuget.org/: https://github.com/NuGet/NuGetGallery/issues/9779. Please thumb up so the team can prioritize this feature. Thanks!

**Comment by zhhyu** [comment]
Our sincere apologies for this inconvenience! The primary CDN provider of NuGet.org had an outage around the time when you reported this issue. We switched the traffic to the other CDN to mitigate this outage. We are working with our CDN provider to take further investigation and resolve any potential issues that caused this incident.

On NuGet.org side, we plan to improve the monitoring coverage and enhance the automatic failover as next steps. This will provide a faster turnaround window, and defend against any regression from our primary CDN provider in the future.

For client resilience, we suggest you consider the latest versions of NuGet clients, and also use environment variables of NuGet clients to enhance the retry policy on CI machines:
https://learn.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#why-can-t-i-restore-packages-from-nuget-org

Please let us know if you have any concerns or suggestions!

**Comment by kapelan** [comment]
Apologies accepted :)

**Comment by Jeff-Tian** [comment]
Met the issue, too. From yesterday there were many errors:

```
pi.nuget.org/v3-flatcontainer/system.reflection.primitives/4.0.1/system.reflection.primitives.4.0.1.nupkg'.
#13 104.2   Response status code does not indicate success: 403 (Forbidden).
#13 105.8   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 105.8   Response status code does not indicate success: 429 (Too Many Requests).
#13 105.9   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 105.9   Response status code does not indicate success: 429 (Too Many Requests).
#13 106.0   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 106.0   Response status code does not indicate success: 429 (Too Many Requests).
#13 106.2   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 106.2   Response status code does not indicate success: 429 (Too Many Requests).
#13 106.3   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 106.3   Response status code does not indicate success: 429 (Too Many Requests).
#13 106.4   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/index.json'.
#13 106.4   Response status code does not indicate success: 429 (Too Many Requests).
#13 106.5   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.primitives/index.json'.
#13 106.5   Response status code does not indicate success: 429 (Too Many Requests).
#13 107.3   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 107.3   Response status code does not indicate success: 403 (Forbidden).
#13 107.6   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 107.6   Response status code does not indicate success: 403 (Forbidden).
#13 107.6   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.diagnostics.healthchecks/index.json'.
#13 107.6   Response status code does not indicate success: 403 (Forbidden).
#13 109.4   Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/system.reflection.typeextensions/index.json'.
#13 109.4   Response status code does not indicate success: 403 (Forbidden).
#13 109.4   Failed to download package 'Microsoft.Extensions.Logging.Abstractions.9.0.0-preview.5.24306.7' from 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.abstractions/9.0.0-preview.5.24306.7/microsoft.extensions.logging.abstractions.9.0.0-preview.5.24306.7.nupkg'.
#13 109.4   Response status code does not indicate success: 429 (Too Many Requests).
#13 113.9 /src/xxx/yyy.csproj : error NU1301: Failed to retrieve information about 'Microsoft.Extensions.Options' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.extensions.options/index.json'. 
```

Still error today.

Our server is in China, seems it redirects all the restore requests to https://nuget.cdn.azure.cn/, and that CDN refused our requests.

**Comment by jinzaz** [comment]
I have also encountered the same problem these past few days
