### ISSUE TITLE
[Dotnet Package Search] When the local source path in quotes ends with a backslash, warning is shown instead of "No results found"

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13159]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 9.0.100-alpha.1.24062.11

### Worked before?

It’s not a regression issue since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:  
1.Patch the latest .NET SDK version ([9.0.100-alpha.1.24062.11](https://github.com/dotnet/installer?tab=readme-ov-file#use-dotnet---help-to-see-available-commands-or-visit-httpsakamsdotnet-cli)) with NuGet Client [Pipelines - Run 6.9.0.86 artifacts (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8897544&view=artifacts&pathAsName=false&type=publishedArtifacts). 
   1.1 Download the [Entropy](https://github.com/NuGet/Entropy.git) to the desktop of test machine.
   1.2 Download and extract the NuGet Client build “[6.9.0.86](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8897544&view=artifacts&pathAsName=false&type=publishedArtifacts)->nupkgs - NonRTM” (named to “nupkgs”) to the desktop of test machine.
   1.3 Update the $SDKChannel = "LTS" and $SDKVersion = "9.0.100-alpha.1.24062.11" in the “patchOnWindows.ps1” file of the downloaded “Entropy\SDKPatchTool”.
   1.4 Modify the $patchSDKFolder = "C:\Users\[UserName]\Desktop\PatchedSDK" and $nupkgsPath = "C:\Users\v-luzh\Desktop\nupkgs" (the path of downloaded nupkgs in step 1.2) in the “patchOnWindows.ps1” file of the downloaded “Entropy\SDKPatchTool”.
2. After patching finished, go to the patchedSDK folder and execute the command` .\dotnet package search CSharp --format table --source "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" `in powershell.

#### Expected Results:  
The result should be “No results found.” (as the result of similar command` .\dotnet package search CSharp --exact-match --format table --source "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"` below).
![image](https://github.com/NuGet/Home/assets/20632625/a4c3f6a5-8ac1-4fa2-81db-8ae84efde114)

#### Actual Results:
The result is “warn: the path for the selected source could not be resolved” instead as below.
![image](https://github.com/NuGet/Home/assets/20632625/9aad1580-c25a-42bd-ba05-c0415d2f6c21)

#### Note:
Repro rate: 100%

**Comment by Nigusu-Allehu** [comment]
This seems to be an issue that occurs if a local file path is specified in quotes as "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\" and ends with a back slash. In addition, it looks like nuget.exe search also produces a warning if a source value is specified similarly. If you look closely in the error message it says `The path 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"'`. Which is not the path you were trying to specify. It looks like the back slash escaped one of the quotes. To prove that was the case, I tested it using a forward slash and that resulted in no warnings.

**Comment by Nigusu-Allehu** [comment]
It looks like this is caused by how System.commandline parses arguments. Created an issue here : https://github.com/dotnet/command-line-api/issues/2334#issue-2149850994

**Comment by elgonzo** [comment]
> It looks like this is caused by how System.commandline parses arguments

No. It's not caused by how System.CommandLine parses arguments. This is how the CLI arguments are passed to the `args` array of the Main method way before System.CommandLine touches any of the strings in the `args` array.

**Comment by zivkan** [comment]
it's not command-line-api, it's how PowerShell/cmd.exe work. `\"` means "put a `"` character in the args sent to the app", but these shells don't force you to close a quoted string. Once it reaches the end of line, it auto closes the string literal.

The exact syntax depends shell to shell (so, it might be different between powershell and cmd.exe, and probably is different for bash, zsh, and other shells), but using `--arg "c:\path\to\directory\\"` might work. In other words, it's up the person writing the command line to write the correct syntax. Apps can't guess what was intended.

**Comment by zivkan** [comment]
Also see https://github.com/dotnet/sdk/issues/29770
