### ISSUE TITLE
[Dotnet Package Search] The search result of the package should be “version” instead of “latestVersion” when executing command “dotnet package search <Package Name> --exact-match --format json”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13158]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 9.0.100-alpha.1.24062.11

### Worked before?

It’s not a regression issue since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:  
1.Patch the latest .NET SDK version ([9.0.100-alpha.1.24062.11](https://github.com/dotnet/installer?tab=readme-ov-file#use-dotnet---help-to-see-available-commands-or-visit-httpsakamsdotnet-cli)) with NuGet Client [Pipelines - Run 6.9.0.86 artifacts (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8897544&view=artifacts&pathAsName=false&type=publishedArtifacts). 
   1.1 Download the [Entropy](https://github.com/NuGet/Entropy.git) to the desktop of test machine.
   1.2 Download and extract the NuGet Client build “[6.9.0.86](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8897544&view=artifacts&pathAsName=false&type=publishedArtifacts)->nupkgs - NonRTM” (named to “nupkgs”) to the desktop of test machine.
   1.3 Update the $SDKChannel = "LTS" and $SDKVersion = "9.0.100-alpha.1.24062.11" in the “patchOnWindows.ps1” file of the downloaded “Entropy\SDKPatchTool”.
   1.4 Modify the $patchSDKFolder = "C:\Users\[UserName]\Desktop\PatchedSDK" and $nupkgsPath = "C:\Users\v-luzh\Desktop\nupkgs" (the path of downloaded nupkgs in step 1.2) in the “patchOnWindows.ps1” file of the downloaded “Entropy\SDKPatchTool”.
2. After patching finished, go to the patchedSDK folder and execute the command `.\dotnet package search NUnit --exact-match --format json` in powershell.

#### Expected Results:  
The search result of the package should be “version” instead of “latestVersion” since one package only has one latest version. Like the result of the searching the same package with “--format table” by default as below.
![image](https://github.com/NuGet/Home/assets/20632625/dd4211bb-ffc6-4b55-9111-8caaf9d1086b)

#### Actual Results:
The search result of the package shows a lot of “latestVersion” which does not make sense as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/913aea90-1fdc-4063-88b7-cc8d48b36cf9)

#### Note:
Repro rate: 100%

**Comment by skofman1** [comment]
@Nigusu-Allehu - an additional question regarding the behavior of --exact-match: are we able to show downloads / owners per version? If we don't have the data in the protocol, let's hide it. If we have downloads per version / know the name of the owners, let's display it. Showing null doesn't seem like the best customer experience.
