### ISSUE TITLE
Wrong order of arguments in logs for centralized package version (string `Info_AddPkgCPM`)

### ISSUE THREAD

**Issue by ztl8702** [NuGet/Home#13155]
### NuGet Product Used

dotnet.exe, NuGet.exe

### Product Version

NuGet Command Line 6.8.0.122 (via dotnet CLI)

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

The string template `Info_AddPkgCPM` in https://github.com/dotnet/dotnet/blob/002d01eeae9f40bc6d021971cac07501928de3fc/src/nuget-client/src/NuGet.Core/NuGet.CommandLine.XPlat/Strings.resx#L764-L767

Renders to:
```
info : PackageReference for package 'NAudio' added to '/some-project/src/Directory.Packages.props' and PackageVersion added to central package management file '/some-project/src/Web/UiComponents/Zezo.UiComponents.csproj'.
```

shouldn't it instead be:

```
info : PackageReference for package 'NAudio' added to '/some-project/src/Web/UiComponents/Zezo.UiComponents.csproj'  and PackageVersion added to central package management file '/some-project/src/Directory.Packages.props'.
```

The arguments `{1}` and `{2}` should be swapped.

**Comment by jeffkl** [comment]
Thank you for reporting this!
