### ISSUE TITLE
Shipped APIs tool is not doing the work to copy APIs from unshipped to shipped

### ISSUE THREAD

**Issue by jebriede** [NuGet/Home#13153]
Repro:
From root of enlistment NuGet.Client enlistment, run: "dotnet run --project tools-local\ship-public-apis\ship-public-apis.csproj"

Expected:
Tool runs and generates output to the command line.

Actual:
Tool runs but does not produce any output.

Notes: The tool was regressed by this commit: [ff7695dfeafa05fcf1af15e7f880c7bf8507304d ](https://github.com/NuGet/NuGet.Client/commit/ff7695dfeafa05fcf1af15e7f880c7bf8507304d) which introduced a boolean check that prevents the tool from calling into MainAsync and doing its work.

**Comment by nkolev92** [comment]
This was never ported to main.
