### ISSUE TITLE
`dotnet package search` does not work for private feeds

### ISSUE THREAD

**Issue by Nigusu-Allehu** [NuGet/Home#13160]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet 8.0.2xx

### Impact

I'm unable to use this version

### Repro Steps & Context

dotnet package search --source <private feed>
![image](https://github.com/NuGet/Home/assets/59111203/7f391dea-1248-4579-87f7-2015d5fbb47d)
The anticipated behavior was that the `--interactive` option would prompt for authentication and enable searching. However, there is no prompt for authentication, and we end up with an error as shown in the image above

**Comment by jebriede** [comment]
@Nigusu-Allehu can you please add details to the description of this bug of what the expected behavior is and what the actual behavior is? Thanks!

**Comment by nkolev92** [comment]
I can't repro this consistently anymore.

I'm getting a prompt now.

**Comment by Nigusu-Allehu** [comment]
I can't repro this anymore. It was previously caused by lack of credential provider on computer.

**Comment by Nigusu-Allehu** [comment]
Can not be reproduced.
