### ISSUE TITLE
NuGet Package can't find "latest" version of Azure.AI.OpenAI

### ISSUE THREAD

**Issue by jaz2038** [NuGet/Home#13171]
### NuGet Product Used

dotnet.exe

### Product Version

.net SDK 7.0.* and .net SDK 8.0.*

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Since 1.0.0-beta.12 is the latest version of Azure.AI.OpenAI, I would expect nothing to come back from :

dotnet list package --outdated

for this package.

Actual behavior:

Project `xxx` has the following updates to its packages
   [net7.0]: 
   Top-level Package      Requested      Resolved       Latest                  
   > Azure.AI.OpenAI      1.0.0-beta.12   1.0.0-beta.12   Not found at the sources

Reproduction Steps:

on macOS (I'm running 14.2.1) create a sample project with the Azure.AI.OpenAI project reference above:

and then run:

dotnet list package --outdated

Environment

all MacOS command line, tried with 7.x .net sdk's, most recently tried with latest 8.x .net sdk:

dotnet --info
.NET SDK:
Version: 8.0.100-rc.2.23502.2
Commit: 0abacfc2b6

Runtime Environment:
OS Name: Mac OS X
OS Version: 14.1
OS Platform: Darwin
RID: osx-arm64
Base Path: /usr/local/share/dotnet/sdk/8.0.100-rc.2.23502.2/

.NET workloads installed:
There are no installed workloads to display.

Host:
Version: 8.0.0-rc.2.23479.6
Architecture: arm64
Commit: 0b25e38ad3

.NET SDKs installed:
7.0.100-rc.2.22477.23 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]
7.0.101 [/usr/local/share/dotnet/sdk]
7.0.102 [/usr/local/share/dotnet/sdk]
7.0.200 [/usr/local/share/dotnet/sdk]
7.0.201 [/usr/local/share/dotnet/sdk]
7.0.202 [/usr/local/share/dotnet/sdk]
7.0.203 [/usr/local/share/dotnet/sdk]
7.0.302 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]
7.0.305 [/usr/local/share/dotnet/sdk]
7.0.306 [/usr/local/share/dotnet/sdk]
7.0.400 [/usr/local/share/dotnet/sdk]
7.0.401 [/usr/local/share/dotnet/sdk]
7.0.402 [/usr/local/share/dotnet/sdk]
7.0.403 [/usr/local/share/dotnet/sdk]
8.0.100-rc.2.23502.2 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
x64 [/usr/local/share/dotnet/x64]
registered at [/etc/dotnet/install_location_x64]

Environment variables:
Not set

global.json file:
Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download

NOTE: dotnet team punted the issue from their repo and determined it was a nuget issue - seems macOS specific: https://github.com/dotnet/sdk/issues/36637

**Comment by jeffkl** [comment]
By default, `dotnet list package` will not list pre-release packages.  You'll need to specify the `--include-prerelease` command-line argument to get the latest pre-release.

```
dotnet list package --outdated --include-prerelease

The following sources were used:
   https://api.nuget.org/v3/index.json
   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Project `openai_resolve` has the following updates to its packages
   [net8.0]:
   Top-level Package      Requested      Resolved       Latest
   > Azure.AI.OpenAI      1.0.0-beta.8   1.0.0-beta.8   1.0.0-beta.12
```

**Comment by baronfel** [comment]
@jeffkl should 'list package' consider if the dependency is _already_ a pre release and include those packages in the search? The user has (to me) clearly indicated their desires by explicitly specifying a prerelease in the project file.

**Comment by jeffkl** [comment]
@baronfel I guess it depends on the user's intent.  They might be checking if a stable version is available or they might want the latest pre-release.  At the moment, the `--include-prerelease` command-line argument is how that is conveyed.  Possibly we need a new mode like

1. `--include-prerelease` which implies `--include-prerelease always` and always gives you latest pre-release even if a PackageReference isn't already specify a pre-release version
2. `--include-prerelease existing` only gives you latest pre-release if the package is already specifying a pre-release version

**Comment by jaz2038** [comment]
to @baronfel 's point, specifying a prerelease package already in a project to me implies that "list package" should find new prerelease updates automatically w/o specifying --include-prelease, otherwise @jeffkl your suggestion for #2 makes sense as well.

**Comment by baronfel** [comment]
> to @baronfel 's point, specifying a prerelease package already in a project to me implies that "list package" should find new prerelease updates automatically w/o specifying --include-prelease, otherwise @jeffkl your suggestion for #2 makes sense as well. 

+1 to this, the suggestions do make sense to me.

I wanted to clarify my position a bit - the user specifying a pre release PackageVersion should only opt _that package_ into prerelease version availability checks (in the absence of other CLI flags allowing prereleases).

**Comment by jeffkl** [comment]
Please file a new issue so it can be triaged accordingly.  Thanks for taking the time to make a suggestion.
