### ISSUE TITLE
nuget.exe does not have a default feed

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1317]
On a machine without a default nuget.config, nuget install does not work without specifying a source

**Comment by deepakaravindr** [comment]
Same issue happens with restore too. However, running 'nuget.exe help' or 'nuget.exe sources' creates the default nuget.config

**Comment by yishaigalatzer** [comment]
Can you compare the behavior to nuget.exe 2.8.6?

**Comment by deepakaravindr** [comment]
This is a regression in comparison to NuGet.2.8.6
