### ISSUE TITLE
Update-Package pkgid (without specifying version) fails when package source uses "dnu packages add" layout

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1318]
Software:
NuGet Package Manager for Visual Studio version: 3.1.60717.741
Visual Studio 14.0.23231.00 Update 1 CTP (lab/vsuvscore)

Repro steps:

```
git clone https://mseng.visualstudio.com/DefaultCollection/VSIDEProj/_git/VSIDEProj.slnx slnx
cd slnx
git checkout b8eafb9ae
src\Microsoft.VisualStudio.SLNX.sln
```

Then open the Package Manager console and enter this command:

```
update-package Microsoft.VisualStudio.SDK.VsixSuppression -pre
```

The output is:

```
PM> update-package Microsoft.VisualStudio.SDK.VsixSuppression -pre
Attempting to gather dependencies information for multiple packages with respect to project 'Microsoft.VisualStudio.SourceExplorer', targeting '.NETFramework,Version=v4.6'
update-package : An error occurred while retrieving package metadata for 
'Microsoft.VisualStudio.SDK.VsixSuppression' from source '\\cpvsbuild\drops\vsideproj\Packages'.
At line:1 char:1
+ update-package Microsoft.VisualStudio.SDK.VsixSuppression -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePacka 
   geCommand
```

But if you change the package source from: `\\cpvsbuild\drops\vsideproj\Packages` to `\\cpvsbuild\drops\vsideproj\Packages.old`, it works. The difference between these two paths is that the former one uses the nuget package source layout set up by "dnu packages add"

**Comment by johnataylor** [comment]
The fix here is to make nuget.core a little more resilient to bad data. Specifically if the folder contains a  nuspec that does not appear to be XML or it fails to open the nuspec file for some reason then that package is skipped.

The fact that the bad package has been seen is recorded in the nuget.core Logger. However the user will not currently receive this feedback because the Logger is not correctly wired up.

**Comment by johnataylor** [comment]
Refer to #1343 for missing Logger wire-up.
