### ISSUE TITLE
Unable to use GlobalPackageReference with Directory.Packages.Props and CPM disabled

### ISSUE THREAD

**Issue by ashafique2** [NuGet/Home#13181]
### NuGet Product Used

NuGet.exe, Visual Studio Package Management UI, NuGet SDK

### Product Version

NuGet Version: 5.8.1.7021, .NET SDK (8.0.101)

### Impact

I'm unable to use this version

### Repro Steps & Context

Subject: Issue with Central Package Management and Transitive Pinning in Mono Repo Migration

### Description

We are currently in the process of migrating our solutions within a mono repo to utilize Central Package Management (CPM) along with Transitive Pinning. The current setup involves a mono repo structure with a common `Packages.props` file and multiple solutions within the "Solutions" directory. The solutions rely on a `GlobalPackageReference` defined in the common `Packages.props` file.

The migration plan involves moving solutions one by one and updating the package management configuration. For instance, when migrating "Solution1," the new structure would be as follows:

```
Repository
|-- Solutions
|   |-- Directory.Packages.Props    (Common Central Package Management configuration with transitive pinned packages (PackageVersion and GlobalPackageReference)
|   |-- Solution1
|       |-- Directory.Packages.Props (Solution-specific configuration:<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>, <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>,<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)..\'))" />)
|   |-- Solution2 (to be migrated later)
|       |-- Directory.Packages.Props (Solution-specific configuration: <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>, <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)..\'))" />)
|   |-- Solution3 (to be migrated later)
|       |-- Directory.Packages.Props (Solution-specific configuration: <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>, <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Packages.props', '$(MSBuildThisFileDirectory)..\'))" />)
```

The issue arises when attempting to use the same `Directory.Packages.Props` file for both CPM-enabled and CPM-disabled solutions. Solutions with `ManagePackageVersionsCentrally` set as true can successfully retrieve the `GlobalPackageReference` from the parent `Directory.Packages.Props` file. However, solutions with `ManagePackageVersionsCentrally` set as false are unable to access these packages from the parent file.

**Previously, we had a `Packages.props` file in the root of our repository, but eve after adding `Directory.Packages.props` to the service, it would read the `PropertyGroup` tag from `Directory.Packages.props` inside the solution, but read the `ItemGroup` tag from `Properties.props` which is the most weird behavior** 
### Expected Behavior

Ideally, we would like to have a single `Directory.Packages.Props` file that accommodates both CPM-enabled and CPM-disabled solutions, ensuring that all solutions can access the necessary packages.

### Steps to Reproduce

1. Migrate a solution to use Central Package Management with Transitive Pinning.
2. Ensure that the `Directory.Packages.Props` file for the migrated solution includes `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` and `<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>`.
3. Migrate another solution, but set `ManagePackageVersionsCentrally` to false for this solution.
4. Observe that Solution2 is unable to retrieve the necessary packages from the parent Directory.Packages.Props file.

If there is a workaround or solution to enable the use of the same file for both CPM-enabled and CPM-disabled solutions, please provide guidance.

Thank you for your assistance in resolving this issue.

**Comment by jeffkl** [comment]
At this time, the concept of `GlobalPackageReference` is only available with Central Package Management (CPM).  Projects that are not using CPM will not get this functionality.  You can however enable it yourself with this in a `Directory.Build.targets`:
```xml
<!-- Manually add GlobalPackageReference items for projects where CPM is not enabled -->
<ItemGroup Condition="'$(ManagePackageVersionsCentrally)' != 'true' And '$(RestoreEnableGlobalPackageReference)' != 'false'">
  <PackageReference Include="@(GlobalPackageReference)"
                    Version=""
                    IncludeAssets="Runtime;Build;Native;contentFiles;Analyzers"
                    PrivateAssets="All" />
  <PackageVersion Include="@(GlobalPackageReference)"
                  Version="%(Version)" />
</ItemGroup>
```

You'll want to remove that hack once all of the projects are migrated.
