### ISSUE TITLE
.nupkg of the v3.x nuget.exe

### ISSUE THREAD

**Issue by MikeEsteves** [NuGet/Home#1319]
Team City builds are failing because ''System.Net.Http 4.0.0' package requires NuGet client version '3.0''. Team City uses the command line version of nuget which it fetches from https://www.nuget.org/packages/NuGet.CommandLine (as far as I can tell)

Is v3 going to be published to nuget.org? Or is there a .nupkg of the nuget.exe which I can upload to Team City? (It allows you to upload a nuget version you want to use but it has to be a .nupkg)

Thanks

**Comment by yishaigalatzer** [comment]
Thanks for reaching out.

You can get the nupkg from http://myget.org/gallery/nugetbuild

We plan to ship it on nuget.org once we get to RTM.
