### ISSUE TITLE
Exception when debugging Nuget.CommandLine

### ISSUE THREAD

**Issue by tcartwright** [NuGet/Home#13199]
### NuGet Product Used

NuGet.exe

### Product Version

Microsoft Visual Studio Professional 2022 Version 17.8.5+34511.84

### Impact

I'm unable to use this version

### Repro Steps & Context

I pulled the latest dev branch from https://github.com/nuget/nuget.client, and have been trying to debug the Nuget.CommandLine with a restore. However, each time I run I get this exception:

> error MSB4062: The "NuGet.Build.Tasks.WarnForInvalidProjectsTask" task could not be loaded from the assembly C:\src\NuGet.Client\artifacts\NuGet.CommandLine\bin\Debug\net472\NuGet.Build.Tasks.dll. Could not load file or assembly 'NuGet.Build.Tasks, Version=6.10.0.32767, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

I have tried several things to try to be able to run, but nothing has worked.

**Comment by tcartwright** [comment]
I am trying to debug this issue: https://stackoverflow.com/questions/77881667/error-nu1202-package-is-not-compatible-framework-when-it-actually-is

**Comment by kartheekp-ms** [comment]
@tcartwright - Please take a look at [debugging.md](https://github.com/NuGet/NuGet.Client/blob/dev/docs/debugging.md#debugging-and-testing-nugetexe-nugetcommandline) and [contributing.md](https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md#build) docs and let us know if that resolves your issue.

**Comment by tcartwright** [comment]
@kartheekp-ms  No it does not, I am not trying to debug the extension. Just run the command line.  This pops up immediately. 

![image](https://github.com/NuGet/Home/assets/1036177/0b995bda-b74e-42c1-8ca1-e5519d5dab68)

I can independently build the Nuget.Build.Tasks project, however that is it. Whenever I try to run the command line I get the above error.

**Comment by tcartwright** [comment]
I am sorry, I retraced the steps again in contributing, and it worked this time. I think the first time I was connected to my VPN, and it blocked some of the requests without me noticing.

Edit: now I just have to figure out why this issues is happening: https://stackoverflow.com/questions/77881667/error-nu1202-package-is-not-compatible-framework-when-it-actually-is
