### ISSUE TITLE
Csproj to Xproj references design meeting discussion

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1320]

**Comment by yufeih** [comment]
Hi,

What is the status of this feature? Is there a timeline of when will this be released? Having to publish a new package to update csproj is real pain at the moment.

**Comment by emgarten** [comment]
@yufeih this will go into Visual Studio 2015 Update 2 / NuGet 3.4.0

**Comment by tmbalun17** [comment]
@emgarten I have downloaded Visual Studio 2015 Update 2 RC, so should this feature be working for me, as currently it does not work for me locally, or I have to wait till the full release of Visual Studio 2015 update 2.

**Comment by yufeih** [comment]
@emgarten I installed VS2015 Update 2, created a console app and an xproj library, then reference  xproj from csproj, it gave me the following error:

![image](https://cloud.githubusercontent.com/assets/511355/14306897/dfe2fa7a-fbfd-11e5-81b5-caccafea6d91.png)

Is there a working sample where I can learn how to do the trick? Thanks!

**Comment by xaviergxf** [comment]
I have the same problem as yufeih. I have a project called Deployment which should contain the reference to all other projects and create a bin folder with all outputs. How can i achieve this with the current vs 2015?

Thanks!

**Comment by emgarten** [comment]
@xaviergxf @yufeih there are a few issues with csproj to xproj references, but the fixes are in progress and we're trying to get an update out as soon as possible.

**Comment by rrelyea** [comment]
Was implemented in NuGet 3.5.0 or ASPNET core rc2.
We'll be moving it all towards msbuild.

**Comment by iskiselev** [comment]
With NuGet 3.5.0 from  .NET Core for Visual Studio, I'm still unable to build csproj that reference xproj. It is able to add project reference now, it even show correct dll pah in properties, but it doesn't pass this dll to c# compiler in csproj build.
