### ISSUE TITLE
[Feature] Enable Transitive Dependencies for Solution-level in Visual Studio

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13216]
### NuGet Product(s) Involved

Visual Studio Package Management UI

### The Elevator Pitch

People love using the new transitive dependencies feature in Visual Studio for their projects! 

https://devblogs.microsoft.com/nuget/introducing-transitive-dependencies-in-visual-studio/

One common follow-up is that people would love to see this experience in the solution-level within Visual Studio.

As we know from survey data, people use projects / solution levels just about equally and we originally went with projects to experiment with this feature as it has not been done before in Visual Studio.

This issue tracks bringing this experience to the solution-level in Visual Studio.

Please 👍 or 👎 this comment to help us with the direction of this feature & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

Thank You 🎉

**Comment by Rand-Random** [comment]
Yes, please.

Escpecially with the vulnerable check, if "only" a transitive package is vulnerable you get no feedback.
You actually have to click through all project, manage each project's nugetpackages to see the vulnerable packages.

Project ClassLibrar0:
![image](https://github.com/NuGet/Home/assets/9868626/698dab6a-550c-4beb-b6a3-4c23b247f7f1)

Solution nothing:
![image](https://github.com/NuGet/Home/assets/9868626/5e2bd67d-9135-4244-8438-b6a0163c93a3)

**Comment by ka4ep** [comment]
Not sure if my use-case is correct. Say, I add a few 3rd-party libraries, I have my (~100) transient dependencies shown. When I manually add these dependencies as top-level ones, I can finally update them to the latest versions if applicable. It is very often a good half of transient libraries are well behind. The thing is, the process of bringing transients to top-level is somewhat tedious and time consuming. I wish there was a button or a checkbox for that.

A typical .NET 8 project transient:
![image](https://github.com/user-attachments/assets/b02ed5b1-293f-45df-8cfc-e69d3fbace10)

**Comment by JonDouglas** [comment]
WIP 🏗️👀

![image](https://github.com/user-attachments/assets/6a9ffe4f-29d4-41eb-af40-1b676ef1d4d4)

**Comment by JonDouglas** [comment]
> Not sure if my use-case is correct. Say, I add a few 3rd-party libraries, I have my (~100) transient dependencies shown. When I manually add these dependencies as top-level ones, I can finally update them to the latest versions if applicable. It is very often a good half of transient libraries are well behind. The thing is, the process of bringing transients to top-level is somewhat tedious and time consuming. I wish there was a button or a checkbox for that.
> 
> A typical .NET 8 project transient: ![image](https://private-user-images.githubusercontent.com/5640372/357713907-b02ed5b1-293f-45df-8cfc-e69d3fbace10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MTc1MTMsIm5iZiI6MTcyNDQxNzIxMywicGF0aCI6Ii81NjQwMzcyLzM1NzcxMzkwNy1iMDJlZDViMS0yOTNmLTQ1ZGYtOGNmYy1lNjlkM2ZiYWNlMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMTI0NjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdhYmZlZGJkYjNlYWUxNWU5YTNlNTVmYWE5ZGUxNTlhODFiNWU3YTZhOWZhMjEzMDEyNTlmZjhlMzM0MDlhNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3Yc9WgdMey4inNnqEWYpSsoq4zRX_MDARU-PA74bbCs)

Ideally you shouldn't have to pin or promote transitive packages to top-level. Rather, the package owner would ship a clean dependency graph until a new security vulnerability is disclosed.

Due to the relative newness of these features, it will take the ecosystem some time to make those shifts appropriately. Here is a document on what to do in these situations:

https://learn.microsoft.com/en-us/nuget/concepts/auditing-packages#actions-when-packages-with-known-vulnerabilities-are-reported

There are certain cases where promoting a transitive dependency makes sense to remove the risk. We also provide other tools like suppressing advisories.
