### ISSUE TITLE
nuget.exe: Code to construct SourceRepositoryProvider object is repeated several times

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1321]
nuget.exe: Code to construct SourceRepositoryProvider object is repeated several times. This should be fixed to avoid bugs

**Comment by emgarten** [comment]
NuGet/NuGet.PackageManagement@f4165c27f32c809cbeb6c6f8ec5c17b0feda443b
NuGet/NuGet3@35d6d170c8cfee244f36fd84d9a87c23b6a54956

**Comment by deepakaravindr** [comment]
I have verified this fix.
