### ISSUE TITLE
ProjectModel.HashObjectWriter.OnFlush is using a SHA512 hash versus a cheaper hash which seems like overkill

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#13214]
### NuGet Product(s) Affected

MSBuild.exe, dotnet.exe

### Current Behavior

Originally filed by the VS Perf team.  The `ProjectModel.HashObjectWriter` currently uses a SHA512 hash algorithm and we're wondering if a faster hash algorithm would still work and speed things up.

### Desired Behavior

A faster hashing algorithm that still yields the same outcome.

### Additional Context

Originally reported at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1987168

**Comment by rainersigwald** [comment]
This is a case one where we'd benefit locally from being able to use `System.IO.Hashing` in VS, which has historically been rejected by the VS perf team because it's another DLL load which may be overall negative to system performance.

(MSBuild wants this too; cc @jankrivanek)

**Comment by JanKrivanek** [comment]
What is the exact scenario of usage? - are collisions acceptable? And is MSBuild on execution path? If yes and yes - we can possibly help you :-)


Noncryptographic hash can definitely be orders of magnitude faster, but it cannot be used where hash collisions would lead to correctness issues. With 64 bit hashes the 50% collision odd starts around 4 billion hashed strings (by the "birthday paradox"), but cannot be disregarded.

If MSBuild task or property function would be usable - then you might benefit from FNV string hashing (32bit and 64bit) that we plan to add and expose very soon.

**Comment by JanKrivanek** [comment]
Oh I see it's here: https://github.com/NuGet/NuGet.Client/blob/f45ff31d06d8254f7a5df017f1a4c54ce706b575/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L302-L303 - so PropFunction/Task is out of question.
But you seem to be referencing Microsoft.NET.StringTools - so once/if following PR goes in, you might simply leverage FNV from StringTools: https://github.com/dotnet/msbuild/pull/9721/files#diff-ed2e36ca70a3a73e4379cf4470aa8f4f492b961eabfaa15127b21efcff6706f1R12
