### ISSUE TITLE
[Bug Bash] Unmatched detailed info is showing on the right panel when typing an invalid package version in the “Version” drop-down box 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13224]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.10.0.28

### Worked before?

It reproes on D17.8\34601.278 but it doesn't repro on D16.11\34601.136 and D17.0\33829.163 since the feature "custom version" was not merged into 16.11 and 17.0.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Create a C# Console App (.NET core) project.   
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open the PM UI.   

3. Go to the "Browse" tab and select a package (for example "Newtonsoft.Json").  

4. Click the "Version" drop-down box in the right panel and type an invalid version (e.g. “121”) in it. 

#### Expected:      

No detailed info is shown on the right panel. 

#### Actual: 

Unmatched detailed info is showing on the right panel as below: 
![MicrosoftTeams-image (5)](https://github.com/NuGet/Home/assets/84695155/9adb4696-8485-437b-9872-ca235208cf9e)
#### Note:     

The repro rate is 70%.

**Comment by Nigusu-Allehu** [comment]
I was not able to repro this.

**Comment by nkolev92** [comment]
Team Triage: 
We're not concerned that the details tab does not get cleared.
