### ISSUE TITLE
[Bug]: PackageReference with Content fails to build rather than warn with NU1701

### ISSUE THREAD

**Issue by AR-May** [NuGet/Home#13221]
---
**Issue moved from dotnet/msbuild#9702**
- Please respond to @edmfgh.

---

_From @edmfgh on Thursday, February 1, 2024 7:02:24 PM_

### Issue Description

Given a consumer project, ProjectConsumer (with TargetFramework netstandard2.0) that PackageReferences a project with Content, ProjectWithContent, (with TargetFrameworks net48;net6.0) and another project without Content, ProjectWithoutContent, (also with TargetFrameworks net48;net6.0), ProjectConsumer fails to compile with "error CS0246: The type or namespace name 'ProjectWithContent' could not be found (are you missing a using directive or an assembly." On the other hand, ProjectWithoutContent compiles with warning NU1701.

Note that if ProjectWithContent and ProjectWithoutContent are ProjectReferenced rather than PackageReferenced, ProjectConsumer builds with warning. This leads me to suspect the issue could involve NuGet.

If there is a fundamental issue why a project with content cannot be PackageReferenced this way, it would be nice to have a more descriptive error message.

Thanks!

### Steps to Reproduce

Sample project to reproduce issue: https://github.com/edmfgh/PackageReferenceBug/tree/main

1. "dotnet pack" both ProjectWithContent and ProjectWithoutContent, e.g., "dotnet pack .\ProjectWithContent.csproj" -o <output folder>
2. Add <output folder> as a NuGet source
3. Ensure ProjectConsumer references ProjectWithContent and ProjectWithoutContent via PackageReference
4. Build ProjectConsumer

### Expected Behavior

ProjectConsumer builds with warnings that ProjectWithContent and ProjectWithoutContent may not fully be compatible with your project, ProjectConsumer.

### Actual Behavior

ProjectConsumer fails to compile with "error CS0246: The type or namespace name 'ProjectWithContent' could not be found (are you missing a using directive or an assembly reference?)"

### Versions & Configurations

SDK 8.0.101
MSBuild version 17.8.3+195e7f5a3 for .NET, 17.8.3.51904
IDE Agnostic

**Comment by edmfgh** [comment]
"Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)"

The link appears to be 404. Does someone have a working link I could use to add labels? Thanks

**Comment by nkolev92** [comment]
> "Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)"
>
> The link appears to be 404. Does someone have a working link I could use to add labels? Thanks

@edmfgh That's because a template was not used.  I've taken care of that.

The behavior is as expected: 

PackageWIthoutContent uses ATF to restore, but the PackageWithContent has content files which are compatible with every framework: 

```json
 "ProjectWithContent/1.0.0": {
        "type": "package",
        "contentFiles": {
          "contentFiles/any/any/MyContent/MyFile.txt": {
            "buildAction": "Content",
            "codeLanguage": "any",
            "copyToOutput": true,
            "outputPath": "MyContent/MyFile.txt"
          }
        }
      },
```

That means, no asset target fallback, no assemblies getting included. 

As to why ProjectReference works and PakcageReference doesn't, it's because content files are not supported by ProjectReference.

**Comment by edmfgh** [comment]
Hi, @nkolev92, could you clarify on 

> "That's because a template was not used."

Could you provide an example of what should be added to the csproj so "codeLanguage": "any" appears in the nuspec?
        
```
<Content Include="..\MyFile.txt">
            <Link>MyContent\MyFile.txt</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <PackagePath>contentFiles/any/any/MyContent</PackagePath>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <Pack>true</Pack>
</Content>
```

Also, when you say 

> "I've taken care of that."

Do you mean that you've fixed the issue in the past? If yes, which versions/release of msbuild was it fixed in?
Thanks

**Comment by nkolev92** [comment]
> Hi, @nkolev92, could you clarify on

That first line was referring to your Type questions. 
I've fixed my original response with a quote.

> Could you provide an example of what should be added to the csproj so "codeLanguage": "any" appears in the nuspec?

Your sample does exactly that. 
That thing I pasted was following your repro, and that's what was written in the assets file.


There's nothing to be fixed here btw, the behavior is as expected. Hopefully these explanations clarify that.

**Comment by edmfgh** [comment]
> PackageWIthoutContent uses ATF to restore

sorry, could you explain what ATF is and the difference between ATF and the mechanism used to restore PackageWithContent?

> PackageWithContent has content files which are compatible with every framework... That means, no asset target fallback, no assemblies getting included.

What governs the asset target fallback, e.g., if content files are not compatible with at least one framework?

Thanks

**Comment by nkolev92** [comment]
Here's the AssetTargetFallback documentation: https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#assettargetfallback. 

Hope that helps.
