### ISSUE TITLE
Getting HTTP response status 403 when browsing Artifactory package source in Visual Studio Package manager

### ISSUE THREAD

**Issue by kosa-gyula-77** [NuGet/Home#13228]
### To reproduce

Browse packages in Visual Studio Package manager by selecting an Artifactory nuget package source that requires authentication.
`packageSourceCredentials` is set in `NuGet.config` with the personal Identity Token generated by Artifactory as password.

### Details

Visual Studio Package manager does not respond to challenge `WWW-Authenticate: Basic` according to Fiddler. Only one round trip occurs with Artifactory package source in that the request is responded with `403` HTTP status and `WWW-Authenticate: Basic` header set.
No subsequent requests are made by Visual Studio.

### Further technical details

- Microsoft Visual Studio Professional 2022 (64-bit) Version 17.8.6
- NuGet Package Manager 6.8.0
- Artifactory EnterpriseX license 7.71.8 rev 77108900
- It may be related to https://github.com/NuGet/Home/issues/13227

**Comment by nkolev92** [comment]
@kosa-gyula-77 

Please use the templates for future issues. 

403 suggests to me that the credentials were actually sent, but they were invalid. 

Can you try generating new credentials?
