### ISSUE TITLE
NuGet.PackageManagement.dll should not use NuGet.Core and NuGet.Protocol.Core.v2

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1323]
NuGet.PackageManagement.dll should not depend on NuGet.Core and NuGet.Protocol.Core.v2.

Currently, NuGet.PackageManagement.dll references NuGet.Protocol.Core.v2 package.

https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/project.json#L4

Also, 
https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/Utility/UriHelper.cs uses PackageSourceProvider from NuGet.Core instead of NuGet.Configuration.dll, which is a
totally unnecessary dependency

**Comment by nkolev92** [comment]
this is done.
