### ISSUE TITLE
`dotnet list {SolutionName}.sln package` error

### ISSUE THREAD

**Issue by asalletmaier** [NuGet/Home#13236]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.101

### Impact

I'm unable to use this version

### Context
When running the command `dotnet list {SolutionName}.sln package` in the command line, I receive the following error:
'The imported project "{PathToFile}{NameOfPropsFile}.props" was not found. Confirm that the expression in the Import declaration "{NameOfPropsFile}.props" is correct, and that the file exists on disk.'

In VS2022, the solution can be built without failure. The error only occurs when using the command.

### Repro Steps
This concrete example of the error message, which is a consequence of following the steps for reproduction below, seems to use a faulty path:
'The imported project "{LocalPath}\DotNetListError\DotNetListError\Default.CPP.Project.props" was not found. Confirm that the expression in the Import declaration "Default.CPP.Project.props" is correct, and that the file exists on disk.'
**However, the actual path to the `.props` file is "{LocalPath}\DotNetListError\Default.CPP.Project.props"!**

1. Create a new solution with an empty C++ project.
2. Add a `.props` file in the same directory as the `.sln` file.
3. Reference the file in the `.vcxproj` file of the project using `$(SolutionDir)`.
4. Build the solution; it should be successful.
5. Try to run the `dotnet list {SolutionName}.sln package` command.

See this minimal example for reference: https://github.com/asalletmaier/dotnet-list-error

### Further technical details
The IDE I am using is `Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.8.6`.

**Comment by nkolev92** [comment]
@asalletmaier 

`dotnet list package` and all `dotnet SDK` commands support .NET SDK projects only. 
They do not support C++ projects.
