### ISSUE TITLE
Analyzer of included assets vs exposed types.

### ISSUE THREAD

**Issue by voroninp** [NuGet/Home#13246]
### NuGet Product(s) Involved

MSBuild.exe, dotnet.exe

### The Elevator Pitch

If I reference package and declare `compile` as private assets, but expose types from referenced package in api of my package, I'd like to get a warning.

```xml
<PackageReference Include="Dependency" Private assets="compile" Version="x.y.z" />
```
```CSarp
public Interface My interface
{
    void SomeMethod(Dependency.SomeType value);
}
```

**Comment by nkolev92** [comment]
[Hey @voroninp, 

Thanks for creating this issue.
While is this is somewhat of a NuGet scenario, from a technical perspective, NuGet *does* not read or understand assemblies. 

Are you familiar with (https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/package-validation/overview)

Can you check if it captures your scenario?

If it does not, we'll need to file this issue in the dotnet/sdk repo https://github.com/dotnet/sdk/issues/new
