### ISSUE TITLE
nuget command line should display http requests it's making to v3 feed when Verbosity is set to detailed

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1324]
When nuget talks to a v2 feed, it displays http requests when Verbosity is set to true. But it does not show the requests when it connects to a v3 feed.

**Comment by xavierdecoster** [comment]
@feiling `-verbosity` needs to have one of these values: `quiet, normal, detailed`. I'm assuming by _verbosity is set to true_ you are referring to `-verbosity detailed`, right?
