### ISSUE TITLE
[Bug Bash] There is a duplicated “version” column in the right panel of solution-level PM UI for SDK based projects

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13257]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.10.0.42

### Worked before?

It’s not a regression since it repro on D16.11\34601.136 and D17.9\34601.282.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1.	Create a solution with multiple project types – 1 C# Console App (.NET 8.0) project, 1 C# Class Library (.NET 8.0) and 1 C# Console App (.NET Framework 4.8.1) in VS. 
2.	Right-click the solution node in Solution Explorer window and click “Manage NuGet Packages for Solution…”. 
3.	Install a package into every project and go to “Installed” tab.

#### Expected Result: 
There should be no need to show a duplicated “version” column in the right panel of solution-level PM UI for SDK based projects.

#### Actual Result:
There is a duplicated “version” column (dup to “Installed” version) in the right panel of solution-level PM UI for SDK based projects as below screenshot.
![image](https://github.com/NuGet/Home/assets/20632625/33bedb2e-0d78-4ade-ab7f-994846821fc8)
#### Notes:
1.Repro rate: 100%.
2.It also reproes on “Browse”/”Updates”/”Consolidate” tab of solution-level PM UI.
3.It should be fixed since we don’t have this behavior for Non-SDK style project (take the project “NetFwConsole” above for example).

**Comment by martinrrm** [comment]
"Version" column refers to the requested version, so it can be a range, a floating version or a version that was not resolved. I believe that the name is not the best one but that's the one we decided to long time ago. @nkolev92 do you think we need to do something here?

**Comment by nkolev92** [comment]
We'll run it through triage to see if there's a better name. 

What's the behavior for non .NET SDK PackageReference projects? Does it match the .NET SDK one?

**Comment by nkolev92** [comment]
Team Triage: 

* PackageReference projects (both .NET SDK and non .NET SDK based), have 2 versions, the specified one, and the resolved one. 
* packages.config projects will only ever show 1 column.

This is by design.
