### ISSUE TITLE
NullReferenceException when updating package with different casing than project file

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13259]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

6.9

### Worked before?

6.8

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Have a project with a package reference that uses a different case than what the package's own metadata claims. For example `<PackageReference Include="nuget.versioning" Version="6.6.0" />`.  Then either try to upgrade the package in PM UI, or try to upgrade the package in PMC using a different case, for example `Update-Package NUGET.VERSIONING -Version 6.7.0`.

### Extra Context

See https://developercommunity.visualstudio.com/t/Update-nuget-package-causes-NullReferenc/10584808

**Comment by WernerMairl** [comment]
Hi,

Updated VisualStudio... "dotnet nuget --version" shows: 6.9.1.3

but the issue remains...
Is this the correct version ?

**Comment by zivkan** [comment]
No, the Developer Community feedback is still "pending release": https://developercommunity.visualstudio.com/t/Update-nuget-package-causes-NullReferenc/10584808
