### ISSUE TITLE
the package does not contain any assembly references or content files that are compatible with that framework

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1325]
_From @NVentimiglia on September 2, 2015 22:35_

I am trying to install a nuget package and failing. Both the nuget package and the importing project are of the same type (PCL target 259). When I try to import the project, I get this error.

Could not install package 'WebSocket.Portable.Core 1.2.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

After emailing myself the issue, I tried to republishing the nuget package using the manager tool (vs 1.2.3) and that did not work. Here is my nuget package explorer.

![nugetmad](https://cloud.githubusercontent.com/assets/125889/9646406/22462534-5188-11e5-8611-d410065d700a.png)

Using VS 2015 and NuGet 3.1.6

_Copied from original issue: NuGet/NuGetGallery#2654_

**Comment by ericstj** [comment]
Yep, this package won't apply.  Profile24 is equivalent to net45+sl5, but the package doesn't support SL5 at all.  It'd be nice if nuget didn't just throw up profile numbers in the error messages, that'd make this a bit easier to understand.  Perhaps something like "You are trying to install this package into a project that targets a portable profile supporting .NET Framework 4.5 and Silverlight 5 but the package doesn't contain any..."

**Comment by NVentimiglia** [comment]
@ericstj  So the solution would be to add a Silverlight5 lib target to my package ?

**Comment by NVentimiglia** [comment]
I added Silverlight5 target. This did not help.

Could not install package 'WebSocket.Portable.Core 1.2.4'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by yishaigalatzer** [comment]
Is the package available anywhere, along with the project you are trying to install it into?

**Comment by NVentimiglia** [comment]
@yishaigalatzer The githup / nuget package is available at 

https://github.com/NVentimiglia/WebSocket.Portable

I am importing this package into a new PCL library (fresh from visual studio).

**Comment by yishaigalatzer** [comment]
Thanks for getting back. What exact flavor of pcl?

**Comment by NVentimiglia** [comment]
A new one. I tried a number of combinations including one that targeted the same platforms as the websocket library and another that targeted a smaller subset. Xamarin iOS, Xamarin Droid, and .net 4.5 were my minimal.

**Comment by yishaigalatzer** [comment]
Would you mind sharing your project, to make sure we are verifying the exact same thing you are using.

**Comment by NVentimiglia** [comment]
https://drive.google.com/file/d/0B_kXglJqPnm_M1NrRUVYUlNIZGM/view?usp=sharing

**Comment by yishaigalatzer** [comment]
@ericstj do you have any more suggetions on this?

@NVentimiglia please update to NuGet 3.2 for the continuation of this discussion

**Comment by ericstj** [comment]
Sorry for the delay, have been out of town.

> @ericstj So the solution would be to add a Silverlight5 lib target to my package ?
> No you need to expand the portable profile folder to include SL5.

Consider that PCL requires a dll to compile against.  It needs one that supports all the targets.

So the project you are installing into is targeting .NETPortable,Version=v4.0,Profile=Profile24. Nuget translates this to  portable-net45+sl5.  If you check the PCL targeting dialog in the project properties of the project you'd see something similar.
![pcl-net45 sl5](https://cloud.githubusercontent.com/assets/8918108/10050949/bfe609ac-61d3-11e5-8a5f-47ca1e2f0996.PNG)

Now consider if any of the folders support **both** net45 and sl5.
MonoAndroid -> nope
MonoTouch -> nope
portable-net45+wp8+win8 -> nope, doesn't support SL5
sl5 -> nope doesn't support net45

From the [latest in GitHub](https://github.com/NVentimiglia/WebSocket.Portable/blob/master/.nuget/WebSocket.Portable.Core.1.2.nuspec)
portable-net45+win+wpa81+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10 -> nope, doesn't support SL5.

So, if you wanted to use this package in a PCL that includes SL5 support you need to build the PCL (either a single DLL, or a separate DLL) to a PCL profile that includes SL5.
So you'd change [this project](https://github.com/NVentimiglia/WebSocket.Portable/blob/58b51ff9ef1eebe3c017e1b7e9aaccfb1fbb3dde/WebSocket.Portable/WebSocket.Portable/WebSocket.Portable.csproj#L16) from targeting net45+win8+wpa81+wp8 to include SL5 as well.  That'd be Profile344 I believe.  This all assumes you can actually do that and still have the surface area you need to implement WebSocket.Portable.

After doing this you'd have a folder in your package like the following:
portable-net45+win+wpa81+wp80+SL5+Xamarin.iOS10+MonoAndroid10+MonoTouch10 -> YES supports both net45 and SL5.

**Comment by NVentimiglia** [comment]
@ericstj That worked. I manually adjusted my nupkg file with a target for portable-net45+win+wpa81+wp80+SL5+Xamarin.iOS10+MonoAndroid10+MonoTouch10
