### ISSUE TITLE
Items with Pack=True are not included in package when cross-targeting with GeneratePackageOnBuild=True

### ISSUE THREAD

**Issue by miitors-tbm** [NuGet/Home#13254]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

dotnet SDK 8.0.200, MSBuild version 17.9.5+33de0b227, VS2022 17.9.1

### Impact

I'm unable to use this version

### Repro Steps & Context

When using `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>`, project items such as the package icon or readme file with `<Pack>True</Pack>` are not discovered/included when generating the NuGet package for projects with cross-targeting enabled. This causes the build to fail when these files are specified in e.g. `<PackageIcon>` or `<PackageReadmeFile>`.

To reproduce, perform the following steps in Visual Studio:
1. Create new, empty class library project.
2. Add an image to the project to use as package icon.
3. In the project properties, enable "Produce a package file during build operations." and select the image as the package icon.
4. Build the project and verify that a NuGet package is generated as expected.
5. Now, change the `<TargetFramework>` property to `<TargetFrameworks>` to enable cross-targeting. It does not matter if one or multiple target frameworks are specified.
6. Build again.
7. Build fails with `C:\Program Files\dotnet\sdk\8.0.200\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(221,5): error NU5046: The icon file 'icon.png' does not exist in the package.`

Example project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <PackageIcon>icon.png</PackageIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
```

### Verbose Logs

[dotnet build -v diag](https://github.com/NuGet/Home/files/14374845/dotnet.diag.log.txt)

**Comment by nkolev92** [comment]
Duplicate of https://github.com/NuGet/Home/issues/6792 & https://github.com/NuGet/Home/issues/11467.

**Comment by stonstad** [comment]
@nkolev92  In which ticket was this issue resolved?  I see closure for duplicates but no resolution. I'm seeing this behavior in VS 17.8.x and 17.9x when multitargeting is enabled.

**Comment by nkolev92** [comment]
It is not resolved, the 2 linked issues are still open.

**Comment by miitors-tbm** [comment]
The workaround of changing `Update=` to `Include=` mentioned in [this comment](https://github.com/NuGet/Home/issues/11292#issuecomment-1317357876) worked for me, as well, so I'm just repeating it here for anyone else who might stumble upon this issue.
