### ISSUE TITLE
NuGet 3.2-RC - Incorrect error message when no framework defined

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#1326]
I got the error message below when I tried to modify a project's packages with a file named Newtonsoft.Json.Tests.Net20.project.json instead of project.json:

```
Restoring packages for 'Newtonsoft.Json.Tests.Net20'.
The project 'Newtonsoft.Json.Tests.Net20' does not specify any target frameworks in project.json.
Package restore failed for 'Newtonsoft.Json.Tests.Net20'.
Generating MSBuild file Newtonsoft.Json.Tests.Net20.nuget.targets.
Successfully uninstalled 'NUnit 2.6.4' from Newtonsoft.Json.Tests.Net20
========== Finished ==========
```

The error message should say `Newtonsoft.Json.Tests.Net20.project.json` instead of `project.json`. Should check any other error messages to replace project.json with the correct file name.

**Comment by JamesNK** [comment]
Also once I fixed the issue by including the framework in json file, the csproj's references don't appear to be modified when I add and remove NuGet packages, only the json file.

**Comment by yishaigalatzer** [comment]
Nice catch.

**Comment by RanjiniM** [comment]
The error message shows projectname.project.json now
