### ISSUE TITLE
[FEATURE] Support deprecation warnings at restore time

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13266]
### NuGet Product(s) Involved

NuGet.exe, MSBuild.exe, dotnet.exe

### The Elevator Pitch

TL;DR - Support deprecated metadata similar to what we did with security vulnerability auditing in .NET 8 timeframe.

https://github.com/NuGet/Home/blob/dev/accepted/2022/vulnerabilities-in-restore.md#surfacing-deprecation-information

Please 👍 or 👎 this comment to help us with the direction of this feature & leave as much feedback/questions/concerns as you'd like on this issue itself and we will get back to you shortly.

Thank You 🎉

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/12244.
