### ISSUE TITLE
NuGet 3.2-RC - Adding and removing packages doesn't update the csproj references

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#1327]
I have a project Newtonsoft.Json.Tests.Net20.csproj which has a json NuGet file Newtonsoft.Json.Tests.Net20.project.json.

Adding and removing NuGet packages updates the json file but it doesn't update the csproj with the new references.

**Comment by emgarten** [comment]
References are added to Newtonsoft.Json.Tests.Net20.project.lock.json, the csproj file will not have the references.

**Comment by JamesNK** [comment]
Well Visual Studio doesn't appear to know about those references and I can't build my project.

**Comment by emgarten** [comment]
You need a version of MSBuild that supports {ProjectName}.project.json.

**Comment by JamesNK** [comment]
And I can get that where...?

**Comment by emgarten** [comment]
It hasn't been released to the public yet.

**Comment by JamesNK** [comment]
Terrific. That would have been some useful intel... https://github.com/NuGet/Home/issues/1294

**Comment by JamesNK** [comment]
So is the new msbuild that you are referring to what is talked about here?  http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

That blog post says "you now use this file in your Universal Windows projects and modern portable class libraries (that target DNX, UWP, and .NET 4.6) to define your package references".

I want to confirm it can be used with ALL csprojs. If I have a csproj that targets PCL net45+win8+wpa81 or net20, will it work? Have you tested the new msbuild with projects like that?

**Comment by yishaigalatzer** [comment]
@JamesNK this seems to be repeated across multiple bugs.

In #1294 I was saying that we need a piece of code from @pilchie 's team, which is not the NuGet team. Sorry this wasn't clear enough. These bits will be released later (or as I suggested elsewhere, we might be able to put them in your hands earlier). And yes we did test with your project.

**Comment by JamesNK** [comment]
I saw NuGet 3.2 has been released. When will the new msbuild be released?

Reminder: I'm not using UWP or Windows 10. All I want is NuGet to start working again with my csprojs like it use to.

**Comment by Pilchie** [comment]
The new Win10tools release today includes a patch to the msbuild targets to support this. 

Unfortunately for now you need to install the win10 tools to get it. This will change with VS Update 1, which will also include all of these changes.

**Comment by JamesNK** [comment]
Any idea when that will be?

What I don't understand is why is NuGet using the project.json file for non-UWP projects? It's done nothing but cause me trouble. I just want NuGet to use packages.config like it use to! I'm sick of everything being broken.

**Comment by Pilchie** [comment]
I know when update 1 is planned, but can't post publicly in case someone takes it as a commitment :frowning:

Project.json is used in PCL right now as well as UWP, and works (though we aren't pushing it yet) in all project types. For example in http://Roslyn.io, we just moved all of our projects over to it.

Eventually I think it will be the default.

What's broken about it?

**Comment by Pilchie** [comment]
Note: I mean what's wrong with _project.json_ and its transitive refs, not what's wrong with "dotnet" "dnxcore50", etc.

**Comment by yishaigalatzer** [comment]
@JamesNK for now you need to use Win10 tools 1.1 for using project.json (outside of DNX), its unfortunate, but it doesn't have a ship vehicle until U1 like @Pilchie says.

**Comment by JamesNK** [comment]
The thing is I never even wanted to use project.json from csprojs, NuGet uses it as soon as it is present https://github.com/NuGet/Home/issues/797 I just happen to have a project.json for CoreCLR in the same directory as csproj files :(

@pilchie Can you be vague? Will it be out in weeks or months?

**Comment by JamesNK** [comment]
Maybe I just just go back to checking in DLLs and not using NuGet. This entire thing has been extremely frustrating.

**Comment by yishaigalatzer** [comment]
Ah, I see that's an ask from DNX, perhaps they can support {projectName}.project.json. Just chatting about it with @lodejard here, we can kick the idea around with them.

For now I guess you will have to move the location (sucks I get it)

Schedule is not weeks (is that clue enough?)

**Comment by yishaigalatzer** [comment]
@JamesNK another suggestion is to use {projectName}.project.json for your csproj projects. This just got introduced in this release, I get that it requires the extra windows tooling, but think about it like installing Update 1-1/2

**Comment by JamesNK** [comment]
That's what I'm doing! Look at the original issue:

> I have a project Newtonsoft.Json.Tests.Net20.csproj which has a json NuGet file Newtonsoft.Json.Tests.Net20.project.json.
> 
> Adding and removing NuGet packages updates the json file but it doesn't update the csproj with the new references.

I'm trying to find a way to make this work but every direction I run into another issue. Why didn't you just keep using packages.config over project.json until it did work?

**Comment by JamesNK** [comment]
Look, I don't want to lose the forest for the trees. I really don't care about using project.json or {project}.project.json from a csproj at all. I'm just trying to find a way to make project.json and ye olde NuGet projects co-exist.

See all the recent issues from #797 onwards I've opened trying to get around this problem: https://github.com/NuGet/Home/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3AJamesNK+

**Comment by yishaigalatzer** [comment]
I get it. The solution is to install win 10 tools 1.1, it requires the project system and build task changes in that release

**Comment by JamesNK** [comment]
I'd love to but I don't have Win10 and I don't see an option to install them.

**Comment by Pilchie** [comment]
You can install the tools on older OS's.  If you go to
Modify VS in Add and Remove programs, there should be an option to add it. Otherwise running the installer at https://dev.windows.com/downloads should install it.

**Comment by davidfowl** [comment]
Seems like we just need to ship the msbuild target outside of a uwp release

**Comment by JamesNK** [comment]
That would be a good idea. The Win10 tools are 7gigs. Also what about build servers without Visual Studio. What do they do?

---

So I installed the Win10 tools on my computer and it works, sort of. About half the time the NuGet packages never show up under References, VS doesn't know anything about them and there is a lot of red code. When I build it says it succeeds though. To fix VS not knowing about the NuGet packages I have to close and reopen VS2015 until they show up.

My other issue is building from the command line with msbuild doesn't appear to work: Type and namespace could not be found, etc. What do I need to do to get calling msbuild directly working?

**Comment by JamesNK** [comment]
Any ideas about why building from the command line with msbuild doesn't work? Or could you point me in the direction of where to go to ask? I'm not familiar with the UWP scene.

**Comment by Pilchie** [comment]
You need to have done a nuget restore first so that there is a project.lock.json, but once that's done it should work. What errors are you getting?

**Comment by JamesNK** [comment]
Member not found, type not found, etc.

The PS function below is the bit from my build script that is doing the compilation. I'm doing a restore with NuGet on the sln immediately prior to msbuild.

Will `NuGet.exe update -self` update nuget.exe to 3.2? Could that be it?
Or do I need to do the restore with the {project}.project.json as the argument instead of the sln?

```
function MSBuildBuild($build)
{
  $name = $build.Name
  $finalDir = $build.FinalDir

  Write-Host
  Write-Host "Restoring $workingSourceDir\$name.sln"
  [Environment]::SetEnvironmentVariable("EnableNuGetPackageRestore", "true", "Process")
  exec { .\Tools\NuGet\NuGet.exe update -self }
  exec { .\Tools\NuGet\NuGet.exe restore "$workingSourceDir\$name.sln" -verbosity detailed | Out-Default } "Error restoring $name"

  $constants = GetConstants $build.Constants $signAssemblies

  Write-Host
  Write-Host "Building"
  exec { msbuild "/t:Clean;Rebuild" /p:Configuration=Release "/p:Platform=Any CPU" /p:OutputPath=bin\Release\$finalDir\ /p:AssemblyOriginatorKeyFile=$signKeyPath "/p:SignAssembly=$signAssemblies" "/p:TreatWarningsAsErrors=$treatWarningsAsErrors" "/p:VisualStudioVersion=14.0" /p:DefineConstants=`"$constants`" "$workingSourceDir\$name.sln" | Out-Default } "Error building $name"
}
```

**Comment by Pilchie** [comment]
1. Will `nuget.exe update -self` update to 3.2?  Not sure.  @yishaigalatzer?
2. No, restore on the .sln should be fine.

After the restore, do you have project.lock.json files for the projects that don't build?  If not, look at and/or share the output from the restore command?  If so, can you share them and an msbuild diagnostic build log with us (kevinpi@microsoft.com is fine)?

**Comment by JamesNK** [comment]
1. It doesn't. I just looked at the logs and it was saying that 2.8.6 was up to date
2. Ok

I will download the nuget.exe 3.2 and see how I go. Is that what we're suppose to check into source control now? I'm just curious because the old bootstrapper nuget.exe was 18kb and the new file is 3.6 megs.

**Comment by JamesNK** [comment]
Edit: Thought I found a bug. False alarm.

**Comment by yishaigalatzer** [comment]
It will eventually do that after we push the commandline package. We are holding off a bit on this to look at incoming bugs first before we “break” the world.

**Comment by JamesNK** [comment]
@Pilchie Random csproj + project.json question for you: How do I copy NuGet DLLs to the output directory when I build. I need them to run unit tests and by default msbuild doesn't write DLLs from NuGet packages to disk. I'm guessing there is an argument I can give to msbuild to tell it to write them to disk.

**Comment by JamesNK** [comment]
Nevermind. Found /p:CopyNuGetImplementations=true

**Comment by Pilchie** [comment]
Yep, that's the one. We are planning on making it the default for desktop projects too.

**Comment by JamesNK** [comment]
@Pilchie When do you expect the change to make writing NuGet DLLs to the output directory to be the default will be released?

Unit test runners like ReSharper expect DLLs to be in the output directory on build and currently nothing from NuGet gets copied. Hard to run nunit tests with no nunit dll!

**Comment by Pilchie** [comment]
With the next VS Update. In the meantime you can set <CopyNuGetImplementations>true</> in your project file instead of just using /p on the command line.

**Comment by bchavez** [comment]
The struggle is real. I have the same problem here: https://github.com/Microsoft/msbuild/issues/394

I do not want any kind of **package.json** running or looked at when I have a classic **.csproj** open. @JamesNK is absolutely right here. It's just **_common sense**_ not to enable this **project.json** stuff slapjacked on top of classic projects.
