### ISSUE TITLE
Transitive dependency resolution ignores CPM unless explicitly referenced

### ISSUE THREAD

**Issue by capomandamento** [NuGet/Home#13287]
### NuGet Product Used

MSBuild.exe

### Product Version

17.3.1.41501

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Central Package Management does not pick version from Directory.Packages.props for transitive dependency unless it's explicitly added as PackageReference.

Example:
Directory.Packages.props:
```
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Diagnostics.Runtime" Version="3.1.512801" />
    <PackageVersion Include="System.Collections.Immutable" Version="7.0.0" />
  </ItemGroup>
</Project>
```
.csproj (net472):
```
...
  <ItemGroup>
    <PackageReference Include="Microsoft.Diagnostics.Runtime" />
  </ItemGroup>
...
```
output folder has System.Collections.Immutable of version 6 (Microsoft.Diagnostics.Runtime depends on 6.0.0+)
adding `<PackageReference Include="System.Collections.Immutable" />` to csproj changes output dll to be of version 7.0.0.

The expectation is to have of version 7 even without explicitly referencing it like described here https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions#will-a-central-defined-package-version-influence-transitive-dependency-resolution

**Comment by ransagy** [comment]
I was trying to do similar things; i think this depends on https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#transitive-pinning and the linked page is old/outdated as noted at the top.

**Comment by nkolev92** [comment]
You need to enable transitive pinning to get restore to select versions for transitive dependencies from Directory.Packages.props. 

https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management#transitive-pinning
