### ISSUE TITLE
NuGet 3.2-RC - Packages aren't restored

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#1328]
I have a project Newtonsoft.Json.Tests.Net20.csproj which has a json NuGet file Newtonsoft.Json.Tests.Net20.project.json.

Building the solution doesn't restore the project's NuGet packages and the build fails.

**Comment by emgarten** [comment]
Are you getting any restore errors? Can you share the project?

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/commit/f017a1a7c57582d029fff1c6e91109d379ac887a

**Comment by yishaigalatzer** [comment]
@JamesNK Sorry this wasn't clear enough in the blog. This feature requires an update in the managed languages side of the code. It ships in Visual Studio not in the NuGet extension.

We did actually verify your solution yesterday with the Visual Studio bits.

CC // @pilchie
