### ISSUE TITLE
`dotnet package search` crashes on .NET 9 preview 2 nightly

### ISSUE THREAD

**Issue by baronfel** [NuGet/Home#13286]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.100-preview.2.24129.7

### Worked before?

unknown

### Impact

I'm unable to use this version

### Repro Steps & Context

Using the .NET 9 preview 2 release candidate build, `dotnet package search` crashes on activation:

```terminal
> dotnet package search
Unhandled exception. System.MissingMethodException: Method not found: 'Void System.CommandLine.CliCommand.Add(System.CommandLine.CliSymbol)'.
   at NuGet.CommandLine.XPlat.ConfigCommand.RegisterOptionsForCommandConfigPaths(CliCommand cmd, Func`1 getLogger)
   at NuGet.CommandLine.XPlat.ConfigCommand.Register(CliCommand app, Func`1 getLogger)
   at NuGet.CommandLine.XPlat.Program.MainInternal(String[] args, CommandOutputLogger log)
   at NuGet.CommandLine.XPlat.Program.Main(String[] args)
```
My best guess is a System.CommandLine version mismatch, but it would need some investigation to verify.

**Comment by Nigusu-Allehu** [comment]
It looks like the `ConfigCommand`  which is not `dotnet package search` is trying to use the `CliCommand.Add()` method which has two different contracts in different versions of System.CommandLine
In versions that are built after this PR https://github.com/dotnet/command-line-api/pull/2205, the contract is `Void System.CommandLine.CliCommand.Add(System.CommandLine.CliOption)` || `Void System.CommandLine.CliCommand.Add(System.CommandLine.CliArgument)`.
However, in versions that are built before the PR, the contract is `Void System.CommandLine.CliCommand.Add(System.CommandLine.CliSymbol)`.
Dotnet SDK uses the version 2.0.0-beta4.24126.1 which is the latest according to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-libraries/NuGet/System.CommandLine/versions/2.0.0-beta4.23307.1
However according to the error it looks like the NuGet build was compiled with the old contract which does not exist anymore.

**Comment by martinrrm** [comment]
Something must have changed recently, we have two packages that use `System.CommandLine` package, and we are not consistent on how we add an `Option` and `Arguments` to a `CliCommand` in package search we do [`CliCommand.Options.Add(CliOption)`](https://github.com/NuGet/NuGet.Client/blob/0d9fe5cc3d353321d323d110fdcc4aa383d7c1ce/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageSearch/PackageSearchCommand.cs#L92)  and in config we do[ `CliCommand.Add(CliOption)`](https://github.com/NuGet/NuGet.Client/blob/0d9fe5cc3d353321d323d110fdcc4aa383d7c1ce/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/ConfigCommands/ConfigCommand.cs#L163).

I believe that we are using the same source of `System.CommandLine` in SDK and NuGet but that could have changed, we need to verify that. Also, if this is happening just in Preview 2, it could also mean that the package changed it's API's but I don't see it in their commits.

SDK also has a source that contains System.CommandLine package https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public/NuGet/System.CommandLine/versions/2.0.0-beta4.22272.1, not sure if it's taking this source instead

**Comment by nkolev92** [comment]
@Nigusu-Allehu can you please add the behavior for each version of the interest. 
8.0.2xx?
8.0.3xx
.NET 9, P1
.NET 9, P2

**Comment by martinrrm** [comment]
@Nigusu-Allehu @nkolev92 8.0.2xx and 8.0.3xx is working, .NET 9 is not working at all. I just created a PR https://github.com/NuGet/NuGet.Client/pull/5668

**Comment by martinrrm** [comment]
8.0.2xx doesn't contain the `dotnet nuget config` command, 8.0.3xx does, I'm still not sure why is failing just for .NET 9
