### ISSUE TITLE
Project.assets.json inconsistency between VS 17.9.2 and dotnet 8.0.200 cmd line

### ISSUE THREAD

**Issue by dedale** [NuGet/Home#13292]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

VS Pro 17.9.2, dotnet 8.0.200

### Worked before?

Can't say, we just migrated GUI projects to net6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

# Context
- 1500 projects, only ~10 loaded
- All loaded projects target net48 & net6.0-windows with UseWindowsForm=true property.
- All GUI projects depend (directly or not) to a unique project, let's call it Gui.Core.
- Other unloaded referenced projects are not GUI related, they target net48 & net6.0-windows or only netstandard2.0. Could be exe or libs.
- `global.json`: `8.0.100 latestFeature`
- `dotnet --version 8.0.200` in the repo.

# Expected behavior

> This is what happens with the command line.

- In GUI.Core project.assets.json: ... > frameworks > net6.0-windows7.0 > frameworkReferences > Microsoft.WindowsDesktop.App.WindowsForms
- In project.assets.json of other projects: ... > Gui.Core/VERSION > frameworkReferences > Microsoft.WindowsDesktop.App.WindowsForms

# Actual behavior

> In VisualStudio Professional 17.9.2

- In GUI.Core project.assets.json: ... > frameworks > net6.0-windows7.0 > frameworkReferences > Microsoft.WindowsDesktop.App (WindowsForms has been remove as-if project also had UseWPF=true which is not the case)
- In project.assets.json of other projects: ... > Gui.Core/VERSION > frameworkReferences > Microsoft.WindowsDesktop.App (WindowsForms also removed)
- Similar differences in *.dgspec.json files

# Analysis

- Adding UseWPF=false (which is the default!) in Gui.Core.csproj fixes the problem (but it should not be needed).

# Side notes
- No problem with VS 17.8.x but GUI projects were not targeting net6 yet.
- I cannot provide a small repro.
- Being able to get diagnostic NuGet logs while restoring in VS would be nice, but I do not know how to proceed. An alternative would be to be able to restore in command line using VS binaries & context (how to proceed?)
- Only one project in the repo with UseWPF=true, a GUI test project not in the dependency graph of the loaded projects.

**Comment by nkolev92** [comment]
It sounds like UseWPF might be set to true in some cases, potentially by the new SDK.

Can you help us understand what is setting it to true?

**Comment by dedale** [comment]
> It sounds like UseWPF might be set to true in some cases, potentially by the new SDK.

This is also my understanding

> Can you help us understand what is setting it to true?

I'd be glad to help but I don't know how to proceed. I tried restoring with MSBuild diagnostics but NuGet is not verbose...

**Comment by nkolev92** [comment]
If you can get us a binlog, we can look into it.

The root cause is the authoring in the SDK, NuGet is simply interpreting what's specified.

**Comment by dedale** [comment]
> If you can get us a binlog, we can look into it.
> 
> The root cause is the authoring in the SDK, NuGet is simply interpreting what's specified.

How to get a binlog in VisualStudio context?

Might be very hard to share it for compliance reasons. But if you can tell me what to look for and/or compare with a binlog generated with the command line, it would be great.

**Comment by nkolev92** [comment]
https://learn.microsoft.com/en-us/visualstudio/ide/msbuild-logs?view=vs-2022#provide-msbuild-binary-logs-for-investigation

I'd then search for the UseWPF value.

**Comment by dedale** [comment]
I confirm I can find `UseWpf=true` in the first CentralNode_devenv*.binlog file only once when executing the target `GenerateSupportTargetFrameworkAlias` for the base GUI project.
I have more occurrences in other binlogs for the same project.

But I don't understand yet from where this value comes from.

**Comment by nkolev92** [comment]
@dedale 

Given that this is an issue in the project targets probably, can you please create an issue at https://github.com/dotnet/wpf?
Unfortunately GH won't allow moving issues across orgs, and I think it's best if the issue comes from you.

**Comment by dedale** [comment]
@nkolev92 

> Given that this is an issue in the project targets probably, can you please create an issue at https://github.com/dotnet/wpf?

OK will do. thanks
