### ISSUE TITLE
prop/target files in packages are not added correctly for C++/CLI projects.

### ISSUE THREAD

**Issue by wunianqing** [NuGet/Home#13296]
### NuGet Product Used

MSBuild.exe

### Product Version

visual studio 2022 17.9

### Worked before?

I think it worked before when another project was targeting to the net462

### Impact

It's more difficult to complete my work

### Repro Steps & Context

1. Create a C++/CLI project. Target to .net 6.
2. Add packages that include target and prop files.
3. Compile and make sure the project works.
4. Upload source code to git. Download in a different place to make sure it is the first time to restore the packages.
5. use `msbuild -t:restore -p:RestorePackagesConfig=true your_project` to restore the project. And you will find the nuget.g.prop file does not include the prop files in packages.
6. delete the obj folder and use the same command to restore again. The file generates correctly.

**Comment by jeffkl** [comment]
Only projects that support PackageReference will automatically generate a `.nuget.g.props` to the MSBuildProjectExtensions path to be imported during a build.  For projects that use `packages.config`, the imports are added to the project's XML when installing the packages for the first time in Visual Studio.  Manually adding packages to `packages.config` will not add the imports to the project's XML, only if you use Visual Studio to install the packages.

Can you confirm that the project you're experiencing the issue with is using PackageReference?  If it's using `packages.config`, you must install packages with Visual Studio for the project XML to be updated.

**Comment by wunianqing** [comment]
Yes, I am sure that the package info is contained in the vcxproj file.

**Comment by nkolev92** [comment]
> Yes, I am sure that the package info is contained in the vcxproj file.

I'm not sure I follow, are you using PackageReference or packages.config?
Any chance you can provide a repro?

**Comment by wunianqing** [comment]
The project was created with the template CLR Class Library(.NET). It uses PackageReference. I am using .NET 6.
I used two packages like this. 
[nugetpackage.zip](https://github.com/NuGet/Home/files/14784348/test_lib.1.0.1.zip)
The strange thing is, I had problem with the second one. And if I switch the order of the two packages, every package gets restored successfully.
