### ISSUE TITLE
[Dotnet Package Search] The search result is hard to read when searching with detailed verbosity

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13299]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 8.0.300-preview.24154.12

### Worked before?

It’s not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. [Patch](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Dotnet%20Package%20Search%20Test.one%7Cf765a470-67cc-4d36-839c-01ce4dda10d0%2FPre-testing%20Steps%7Cc0dfdc5e-b3f9-4451-8fa6-b461f70965aa%2F%29&wdorigin=703) the latest .NET SDK 8.0.3xx version with NuGet Client Dev latest [6.10.0.72](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9193043&view=artifacts&pathAsName=false&type=publishedArtifacts) nupkgs. 
2. Open the PowerShell command prompt and go to the “PatchedSDK” folder.
3. Enter the command `dotnet package search <search argument> --verbosity detailed `(for example: .`\dotnet package search log4net --verbosity detailed`) and press Enter.
4. Open the NuGet package manager UI in VS and search for the same search argument.
5. Compare the generated output with the result by performing the same search using NuGet PM UI on Visual Studio. 
#### Expected Result: 
-The output will be highly detailed, and it should be easy to read. For each package, it will display the following metadata:
  Package ID
  Latest Version
  Owners
  Total Downloads
  Vulnerable
  Deprecation
  Project URL
  Description
- The generated output should be same as that of a search in NuGet PM UI-Browse tab on Visual Studio.
#### Actual Result:
The search result is hard to read as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/2c95557d-3eda-414d-b652-b581d9a4c5aa)
#### Notes:
1.Repro rate: 100%.
2.It’s not a regression since it is a new feature.

**Comment by Nigusu-Allehu** [comment]
duplicate of : https://github.com/NuGet/Home/issues/13162

**Comment by v-luzh** [comment]
Hi @Nigusu-Allehu, OK thanks for your verification. Dotnet-policy-service said it missed a type, so I add it as a Bug and resolve it as Duplication. Please feel free to let us know if you think the tags are incorrect.
