### ISSUE TITLE
[Dotnet Package Search] The column “Owners” should not be empty when running the command “dotnet package search <Package Name> --exact-match”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13298]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 8.0.300-preview.24154.12

### Worked before?

It’s not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. [Patch](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Dotnet%20Package%20Search%20Test.one%7Cf765a470-67cc-4d36-839c-01ce4dda10d0%2FPre-testing%20Steps%7Cc0dfdc5e-b3f9-4451-8fa6-b461f70965aa%2F%29&wdorigin=703) the latest .NET SDK 8.0.3xx version with NuGet Client Dev latest [6.10.0.72](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9193043&view=artifacts&pathAsName=false&type=publishedArtifacts) nupkgs. 
2. Open the PowerShell command prompt and go to the “PatchedSDK” folder.
3. Enter the command `dotnet package search <Package Name> --exact-match` (for example: `.\dotnet package search Newtonsoft.Json --exact-match`) and press Enter.
4. Open the NuGet package manager UI in VS and search for the same package name.
5. Compare the generated output with the result by performing the same search using NuGet PM UI on Visual Studio. 
#### Expected Result: 
- All versions of the specified package should be listed as a table without empty columns.
- The generated output should be same as that of a search in NuGet PM UI-Browse tab on Visual Studio. 
#### Actual Result:
The column “Owners” is empty as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/15fb31c3-ffb4-4ecb-a141-bd9bd5401f33)
#### Notes:
1.Repro rate: 100%.
2.It’s not a regression since it is a new feature.

**Comment by Nigusu-Allehu** [comment]
This is because the API(https://learn.microsoft.com/en-us/nuget/api/registration-base-url-resource) used for listing versions of a package does not currently provide with owner metadata.

**Comment by v-luzh** [comment]
Hi @Nigusu-Allehu, OK thanks for your verification. Dotnet-policy-service said it missed a type, so I add it as a Bug and resolve it as External. Please feel free to let us know if you think the tags are incorrect.
