### ISSUE TITLE
Plugin issue while using any of the nuget command

### ISSUE THREAD

**Issue by ShBansal22** [NuGet/Home#13302]
When I am using nuget commands like nuget restore or nuget update -self
, I am getting below issue:

A plugin was not found at path 'C:\Users\sbansal\.nuget\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe'.

Even dotnet restore is throwing same type of error:

C:\Program Files\dotnet\sdk\8.0.200\NuGet.targets(169,5): error : A plugin was not found at path 'C:\Users\sbansal\.nuget\plugins\netfx\CredentialProvider.Microsoft\CredentialProvider.Microsoft.exe'.

![Capture](https://github.com/NuGet/Home/assets/49473335/d23cc83d-cf46-4a5a-80f3-f46823b28465)

**Comment by martinrrm** [comment]
Hi! @ShBansal22 looks like the error comes from the Credential Provider, I'm not sure how that plugin works, is it this one https://github.com/microsoft/artifacts-credprovider? Have you configured it?
