### ISSUE TITLE
[Dotnet Package Search] Search result doesn’t ignore empty property “owners” in JSON format output for offline package source “C:\Program Files (x86)\Microsoft SDKs\NuGetPackages”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13315]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 8.0.300-preview.24161.12

### Worked before?

It’s not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. [Patch](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc=%7b8a3c6685-1661-47f4-8807-b765ca62aea1%7d&action=edit&wd=target%28Dotnet%20Package%20Search%20Test.one%7Cf765a470-67cc-4d36-839c-01ce4dda10d0%2FPre-testing%20Steps%7Cc0dfdc5e-b3f9-4451-8fa6-b461f70965aa%2F%29&wdorigin=703) the latest .NET SDK 8.0.3xx version with NuGet Client Dev latest [6.10.0.78](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9216388&view=artifacts&pathAsName=false&type=publishedArtifacts) nupkgs. 
2. Open the PowerShell command prompt and go to the “PatchedSDK” folder.
3. Input the command `dotnet package search Newtonsoft.Json --source “C:\Program Files (x86)\Microsoft SDKs\NuGetPackages”  --format json --exact-match` and press Enter.
#### Expected Result: 
Search result should ignore empty property “owners” in JSON format output for all the sources.
#### Actual Result:
Search result doesn’t ignore empty property “owners” in JSON format output for offline package source as the screenshot below. [It ignore null property “owners” for the public source “nuget.org” successfully as the green line below.]
![image](https://github.com/NuGet/Home/assets/20632625/964ebdbf-b91e-4ee1-a43c-d6b9eb3b788d)
#### Notes:
1.Repro rate: 100%.
2.It’s not a regression since it is a new feature.
3.It reproes with or without `--exact-match`.

**Comment by martinrrm** [comment]
@Nigusu-Allehu Can you help me confirm what is the expected behavior? Looks like when we get the package info from offline source `Owners` will be an empty string instead of a null, we do handle nulls from nuget.org. We will need to verify what is expected for empty values in JSON formats, maybe is the other way around and should add owners even when null.

**Comment by Nigusu-Allehu** [comment]
Null and empty properties should be ignored in the Json format. The owners property is not null but is empty string. It should have been ignored. This issue has been addressed here : https://github.com/NuGet/NuGet.Client/pull/5672/files

**Comment by martinrrm** [comment]
@Nigusu-Allehu Make sure you close this one with the PR too
