### ISSUE TITLE
DynamicDataTemplatesCS install failed

### ISSUE THREAD

**Issue by uuuus** [NuGet/Home#1331]
In VS 2015 Enterprise can not install DynamicDataTemplatesCS - error: The path is not of a legal form.

**Comment by emgarten** [comment]
What type of project are you installing into? Can you provide some more repro steps along with the version of NuGet that you are using?

**Comment by uuuus** [comment]
Hi Justin,

I am trying to install it into ASP.NET Web Forms project template. Version
of NuGet is 1.0.1.
Platform: Visual Studio Enterprise 2015 (Version 14.0.23107.0 D14REL)
.NET Framework Version 4.6.00081

Repro steps:
1. Create ASP.NET Web Forms project (.net framework 4.6)
2. Install DynamicDataTemplatesCS 1.0.1

You'll get error: The path is not of a legal form.

Thanks,
Slawomir

2015-09-09 8:21 GMT+02:00 Justin Emgarten notifications@github.com:

**Comment by emgarten** [comment]
I'm not sure what version 1.0.1 of NuGet would be. Would you try using 3.2.0 RC and let me know if it still repros? 
http://blog.nuget.org/20150902/nuget-3.2RC.html

**Comment by uuuus** [comment]
Problem gone.

Thanks!
Slawomir

2015-09-09 9:29 GMT+02:00 Justin Emgarten notifications@github.com:

**Comment by emgarten** [comment]
@uuuus great!
