### ISSUE TITLE
[Bug Bash] The vulnerability warning NU1901-NU1904 in Error List window lost the link for a .NET SDK based project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13320]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.10.0.80

### Worked before?

It’s didn't repro on 17.9.0 Preview 6.0 [D17.9\34601.282] with implicit NuGet Client 6.9.1.3.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. Create a C# Console App (.NET 8.0) project.
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.
3. Select the package source: “nuget.org” near the gear button.
4. Go to the "Browse" tab and search for a package (e.g. "Newtonsoft.Json").
5. Select a vulnerable package version (e.g. 12.0.1) and install the package.
6. Hover on the warning NU1903 in the Error List window.
#### Expected Result: 
There is a link when hovering on the vulnerability warning NU1901-NU1904 in the Error List window.
#### Actual Result:
There is no link when hovering on the vulnerability warning NU1901-NU1904 in the Error List window as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/af4b0076-576e-4ffd-9b7c-d44600e45495)
#### Notes:
1.Repro rate: 100%.
2.It doesn’t repro for non-SDK based project.
3.It didn't repro on VS 17.9.4 Preview 1.0 [34714.143.d17.9].

**Comment by nkolev92** [comment]
@zivkan Any idea why this wouldn't work?

**Comment by zivkan** [comment]
The code that adds items into the error list has to provide a `HelpLink`, [like we do for packages.config](https://github.com/NuGet/NuGet.Client/blob/6917e6c883d45f45672e20d4b1c45758dad2fa84/src/NuGet.Clients/NuGet.VisualStudio.Common/ErrorListTableEntry.cs#L67-L75)

@drewnoakes do you know how this is supposed to work for SDK style projects?

**Comment by nkolev92** [comment]
fwiw, I thought this worked for SDK style projects.

**Comment by v-luzh** [comment]
It’s didn't repro on VS 17.9.0 Preview 6.0 [D17.9\34601.282] with implicit NuGet Client 6.9.1.3, VS 17.9.4 Preview 1.0 [D17.9\34714.143] with implicit NuGet Client 6.9.2.1 & VS 17.8.8 with implicit NuGet Client 6.8.1.2.

**Comment by drewnoakes** [comment]
I believe the code for this lives in the CPS repo. You might like to file an internal bug and route it to them.

**Comment by drewnoakes** [comment]
The CPS code for this looks fine to me though. It seems to correctly handle the `HelpLink` property.

**Comment by zivkan** [comment]
If this is no longer reproducing, I propose we close it.

**Comment by v-luzh** [comment]
It still repro on Main\34731.15+NuGet Client Dev\6.11.0.3 as the screenshot below. So, I will reopen the bug to track this issue.
![image](https://github.com/NuGet/Home/assets/20632625/70fa2f3d-51af-4125-8765-551b1139b594)

**Comment by nkolev92** [comment]
@v-luzh Can you please file an internal issue that we can route to CPS.

**Comment by v-luzh** [comment]
Hi @nkolev92, I have filed an internal issue [2015676](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2015676) and route it to CPS. Please feel free to correct the "Area" if it is incorrect. I will close this bug later.
