### ISSUE TITLE
NuGet.exe does not pass credentials provided in command line to GET requests in list command

### ISSUE THREAD

**Issue by milanajdinovic** [NuGet/Home#13322]
### NuGet Product Used

NuGet.exe

### Product Version

6.9.1.3

### Worked before?

No

### Impact

I'm unable to use this version

### Repro Steps & Context

I have private NuGet repository hosted on JFrog Artifactory and I have setup my source with credentials in NuGet.Config file:
`nuget sources Add -Name Artifactory -Source https://address.com/artifactory/api/nuget/v3/repository/index.json -username user -password PAT.`
With this setup I can push packages to my repository:
nuget push package.nupkg -Source Artifactory 
This works fine and I can se using Fiddler that credential are passed in header:
```
PUT https://address.com/artifactory/api/repository// HTTP/1.1
X-NuGet-ApiKey: user:PAT
```
With the same configuration when I wont to list the packages with command: `nuget list -Source Artifactory` I get prompt to enter UserName and Password several times and finally command fails::
```
Using credentials from config. UserName: user
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The V2 feed at 'https://address.com/artifactory/api/nuget/repository/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0' returned an unexpected status code '403 '.
```
In Fiddler I can se that first GET request to: `https://address.com/artifactory/api/nuget/repository` passes 200 OK
and subsecvent GET request for `https://address.com/artifactory/api/nuget/repository/$metadata` fails with 403 as no credentials are passed.
Subsequent calls for $metadata where I enter username and password in command line also fails with 403
And finally: `https://address.com/artifactory/api/nuget/repository/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0` fails with 403 for the same reason. 

When I run this HTTP request with credentials provides from external tool such as Postman with credentials provided everything works as expected (no mater weather I use basic auth, bearer token or X-NuGet-ApiKey).

### Verbose Logs

```shell
Using credentials from config. UserName: user
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The remote server indicated that the previous request was forbidden. Please provide credentials for: https://address.com/artifactory/api/nuget/v3/repository/index.json
UserName: user
Password: ****************************************************************
The V2 feed at 'https://address.com/artifactory/api/nuget/repository/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0' returned an unexpected status code '403 '.
```

**Comment by milanajdinovic** [comment]
This affects Visual Studio NuGet extension as well.
As I can see in NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSourceAuthenticationHandler.cs
In method:
`protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)`
After the credentials are obtained they are not set into request (added to request header) for subsequent attempts.

**Comment by zivkan** [comment]
@milanajdinovic NuGet sets the credentials in `HttpClientHandler.Credentials`. From my prior experience, `HttpClient` will only send these credentials when the server responds with a `WWW-Authenticate` header, telling HttpClient if it should use BASIC auth, or Kerberos/Digest, or NTLM, etc.

Also, the general convention for server authentication & authorization responses are that 401 should be used to signal that credentials were not provided, or were invalid. 403 should mean that the credentials were authenticated correctly (the username and password is valid), but the account does not have access to the resource
* https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

Therefore, it seems unusual that 403 is being returned if the request doesn't provide an `Authorization` header. I'd double check if the requests getting 403 really don't have authenticate headers, and if that's true, check with JFrog if your Artifactory is configured correctly. We occasionally get requests from other customers using Artifactory, so I'm confident that many customers are successfully using NuGet with Artifactory, so it seems there might be something different going on with your setup compared to theirs.

You can mimic NuGet's behaviour with a simple console app. This is untested pseudocode, so you might need to adapt it, but something like:

```csharp
var handler = new HttpClientHandler();
handler.Credentials = new NetworkCredentials("username", "PAT");
var client = new HttpClient(handler);

using var response = await client.GetAsync("https://address.com/artifactory/api/repository//");
Console.WriteLine("Got response " + response.ResponseCode);
```

If this doesn't work, then NuGet's not going to either.

**Comment by milanajdinovic** [comment]
It does not matter what server responds because logic in SendAsync checks bot 403 and 401 and in either case it will not add credentials to request header for subsequent attempt:
`                if (response.StatusCode == HttpStatusCode.Unauthorized ||
                    (configuration.PromptOn403 && response.StatusCode == HttpStatusCode.Forbidden))
                {
`

Seems to me this logic is broken.

**Comment by nkolev92** [comment]
The credentials are attached to the client handler in https://github.com/NuGet/NuGet.Client/blob/8c972cdff5b1194d7c37384fca5816a33ffbe0c4/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceAuthenticationHandler.cs#L57-L63

**Comment by milanajdinovic** [comment]
Well I have debugged this part of code and even on first request no credentials are provided in request.
Also, even if initial credentials are set wrong there is functionality of prompting for credentials and multiple attempts in while loop but this code have no sense as prompted credentials are not set for subsequent calls.

**Comment by zivkan** [comment]
HttpClient will NEVER send credentials on the first request, when using `HttpClientHandler.Credentials`. As I previously stated, HttpClient expects the server to respond with an error status code `WWW-Authenticate` header.

**Comment by milanajdinovic** [comment]
What is the point of the multiple attempts while loop in SendAsync? This code then serves no purpose. 
By debugging the code and watching what happens in Fiddler I can not make sense of what are you saying.
First request to server happens from SendAsync method, this method does check both 403 and 401 and goes to acquire credentials and do nothing with them in subsequent calls.

**Comment by zivkan** [comment]
Use https://nuget.pkg.github.com/milanajdinovic/index.json as the URL, rather than your Artifactory URL, and look at Fiddler again. It doesn't matter if your provide an incorrect PAT, because the point of the exercise is to validate that Nuget/HttpClient sends an `Authorization` header after the first request fails. 

You can try this with the simple console app I provided earlier to see that the "retry" happens within `HttpClient` and not the app code.

**Comment by milanajdinovic** [comment]
Ok, so the code is misleading and as I stated serves no purpose. So the problem is that Artifactory server does not send 401 and retry within HttpClient will not happen. 
By HttpClient do you mean System.Net.Http.DelegatingHandler which is base class of HttpSourceAuthenticationHandler?

**Comment by nkolev92** [comment]
The code you are referring to is relevant in the presence of a credential provider such as https://learn.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin and https://learn.microsoft.com/en-us/nuget/reference/extensibility/nuget-credential-providers-for-visual-studio

The AcquireCredentials step assigns the credentials: https://github.com/NuGet/NuGet.Client/blob/8c972cdff5b1194d7c37384fca5816a33ffbe0c4/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSourceAuthenticationHandler.cs#L229

**Comment by milanajdinovic** [comment]
It seems that this is just some weird setup of JFrog Artifactory server.
They even have solution for this:
```
You can then check the “force authentication” option in the remote repositories basic tab (Admin -> Repository -> Remote Repo).  
You can check this box if anonymous access is enabled.  
When anonymous access is enabled at the system, and the anonymous user doesn’t have permissions to the repository, we need to enable the "force authentication" option in order for Artifactory to challenge the client and ask for credentials.
```
[link](https://jfrog.com/help/r/why-is-artifactory-not-able-to-find-my-nuget-packages/why-is-artifactory-not-able-to-find-my-nuget-packages)

So after contacting team that manages our JFrog Artifactory server they manages to set up this correctly and everything works now.
