### ISSUE TITLE
`dotnet new console` hangs because it tries to connect via IPv6 when I do not have a public IPv6 address, and will not fall back to IPv4.

### ISSUE THREAD

**Issue by IoIxD** [NuGet/Home#13329]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.102

### Worked before?

First time using .NET

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Get Fedora Linux 39, Kernel version 6.6.7 (or 6.7.9)
2. Install `dotnet` via `dnf`. Install `nuget` through there too.
3. Run `dotnet new console` or `dotnet restore`
4. It hangs while "determining projects to restore".

I have confirmed I can reach the nuget api via `curl https://api.nuget.org/v3/index.json`. Also, my $HOME variable does not have a slash after it. I'm also not using a Docker container.

This is a duplicate of #12467 but that one ended in the author saying it "fixed itself". This, of course, does not apply to me. 
Somebody in that thread said they "couldn't easily test arch linux", do know that [Fedora is avaliable under WSL just like Arch](https://apps.microsoft.com/detail/9npcp8drchsn?hl=en-US&gl=US). However, it might also help to try and reproduce this under a VM, in case WSL introduces some extra stuff that makes the issue unreproducable.

### Verbose Logs

```shell
➜  onedrive98 dotnet new console           

Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.102

----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /home/gavin/Projects/onedrive98/onedrive98.csproj:
  Determining projects to restore...
```

**Comment by IoIxD** [comment]
Upgrading kernel to 6.7.9 does not change anything.

**Comment by IoIxD** [comment]
Realized that it is timing out trying to get the API, even though I can access it just fine via curl.

```
➜  onedrive98 dotnet new console --force
The template "Console App" was created successfully.

Processing post-creation actions...
Restoring /home/gavin/Projects/onedrive98/onedrive98.csproj:
  Determining projects to restore...
^[OC^R
^[OC/usr/lib64/dotnet/sdk/8.0.102/NuGet.targets(156,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/home/gavin/Projects/onedrive98/onedrive98.csproj]
/usr/lib64/dotnet/sdk/8.0.102/NuGet.targets(156,5): error :   The HTTP request to 'GET https://api.nuget.org/v3/index.json' has timed out after 100000ms. [/home/gavin/Projects/onedrive98/onedrive98.csproj]
Restore failed.
Post action failed.
Manual instructions: Run 'dotnet restore'


➜  onedrive98 curl https://api.nuget.org/v3/index.json
{
  "version": "3.0.0",
  "resources": [
    {
```

Incidentally, pinging api.nuget.org also fails, although traceroute works just fine

```
➜  onedrive98 ping api.nuget.org
PING api.nuget.org(2620:1ec:46::71) 56 data bytes
^C    
--- api.nuget.org ping statistics ---
72 packets transmitted, 0 received, 100% packet loss, time 72725ms

➜  onedrive98 sudo traceroute -T api.nuget.org
[sudo] password for gavin: 
traceroute to api.nuget.org (13.107.213.71), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  1.964 ms  2.326 ms  2.691 ms
 2  10.51.0.1 (10.51.0.1)  10.482 ms  11.424 ms *
 3  100.127.74.24 (100.127.74.24)  15.776 ms * *
 4  68.1.0.187 (68.1.0.187)  15.905 ms * *
 5  * * *
 6  * * ae23-0.rwa03.phx10.ntwk.msn.net (104.44.42.148)  27.092 ms
 7  be-104-0.ibr01.phx10.ntwk.msn.net (104.44.22.25)  36.892 ms * *
 8  be-9-0.ibr01.lax30.ntwk.msn.net (104.44.7.43)  24.248 ms * *
 9  ae21-0.ear03.lax30.ntwk.msn.net (104.44.33.170)  21.423 ms ae23-0.ear03.lax30.ntwk.msn.net (104.44.33.172)  21.398 ms ae25-0.ear04.lax30.ntwk.msn.net (104.44.33.180)  24.251 ms
10  * ae29-0.ier02.lax.ntwk.msn.net (104.44.55.80)  19.476 ms *
11  * * *
12  13.104.186.36 (13.104.186.36)  23.526 ms  19.938 ms  20.518 ms
13  * * *
14  * * *
15  * * *
16  * 13.107.213.71 (13.107.213.71)  25.281 ms *
➜  onedrive98 
```

**Comment by IoIxD** [comment]
Somebody pointed out to me that ping tries to access the IPv6, while traceroute tries IPv4. Further investigation reveals 
I do not have a public IPv6 address assigned to me.

This is, as far as I know, impossible for me to solve.

Disabling IPv6 works. I am leaving the issue open because I still think this is a bug in the program that needs to be solved.
As much as I wish that IPv6 could become the standard, this is simply out of my control (as well as many others control). My ISP is COX Communications and given my other numerous problems with them this adds up (and sadly, I can't just switch, they pretty much have a monopoly in my city, and have screwed over the only other ISP that exists here, preventing them from being good)

**Comment by IoIxD** [comment]
Disabling IPv6 works. I am leaving the issue open because I still think this is a bug in the program that needs to be solved.
As much as I wish that IPv6 could become the standard, this is simply out of my control (as well as many others control)

**Comment by jeffkl** [comment]
NuGet uses standard .NET libraries for TCP/IP connectivity and does not have any knowledge of what version of IP address is in use, or if that IP address is considered public.  If any functionality like this were to exist, I would expect it to be in https://github.com/dotnet/runtime/ instead.
