### ISSUE TITLE
[Bug Bash] Clicking the vulnerability warning NU1901-NU1904 link for "packages.config" project in Error List window goes to an incorrect page (404-page not found)

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13321]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.10.0.80

### Worked before?

It’s not a regression since it is a feature change.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. Create a C# Console App (.NET Framework 4.8.1) project.
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.
3. Select the package source: “nuget.org” near the gear button.
4. Click the “settings” button (top-right of right panel), check "Allow format selection on first package install" in “General” tab and click OK button.
5. Go to the "Browse" tab and search for a package (e.g. "Newtonsoft.Json").
6. Select a vulnerable package version (e.g. 12.0.1) and install the package with “packages.config” format.
7. Hover on the warning NU1903 and click the link in the Error List window.
#### Expected Result: 
Clicking the link should goes to [correct page](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1901-nu1904).
#### Actual Result:
Clicking the link goes to the [incorrect page](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/NU1903) as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/04a3e23b-144e-4430-a2ab-5b4dd4b6e79a)
#### Notes:
1.Repro rate: 100%.
2.It’s not a regression since it is a feature change.
3.It doesn’t repro for .NET SDK based project.

**Comment by zivkan** [comment]
This will be fixed once the docs repo merged the `main` branch into the `live` branch.
