### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by tomap** [NuGet/Home#13324]
### NuGet Product Used

Other/NA

### Product Version

wiki

### Impact

None

### Repro Steps & Context

https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior#problem

=> And it will hard for Project A to understand the root cause.

should be

=> And it will **be** hard for Project A to understand the root cause.

**Comment by zivkan** [comment]
@tomap thanks for letting us know!
