### ISSUE TITLE
`dotnet package search` returns "warn: Failed to retrieve metadata from source" when searching packages from Github NuGet registry

### ISSUE THREAD

**Issue by julealgon** [NuGet/Home#13331]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.202

### Impact

I'm unable to use this version

### Repro Steps & Context

Running `dotnet package search OurCompany` results in the following error:

> Source: GithubFeed (https://nuget.pkg.github.com/our-company/index.json)
warn : Failed to retrieve metadata from source 'https://nuget.pkg.github.com/our-company/query?q=OurCompany&skip=0&take=20&prerelease=false&semVerLevel=2.0.0'.

I'm running the command in a folder where we have the feed setup like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<clear />
		<add key="GithubFeed" value="https://nuget.pkg.github.com/our-company/index.json" />
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
	</packageSources>
	<packageSourceCredentials>
		<GithubFeed>
			<add key="Username" value="%GITHUB_PACKAGE_USER_NAME%" />
			<add key="ClearTextPassword" value="%GITHUB_PACKAGE_TOKEN%" />
		</GithubFeed>
	</packageSourceCredentials>
	<packageSourceMapping>
		<packageSource key="GithubFeed">
			<package pattern="OurCompany.*" />
		</packageSource>
		<packageSource key="nuget.org">
			<package pattern="*" />
		</packageSource>
	</packageSourceMapping>
</configuration>
``` 

Both of the environment variables are defined for my user and point to a valid PAT token from github with `read:packages` permissions that is authorized for our organization:

![image](https://github.com/NuGet/Home/assets/461579/12e7084d-e4cb-43ad-a8ec-7c2c0227e52d)

![image](https://github.com/NuGet/Home/assets/461579/e13aa023-1d77-4341-917d-41d35ba97760)

I've tried just hardcoding the username and password values in `nuget.config` as well just for testing and it still fails with the exact same error. I`ve tried restarting the system, opening/closing the cmdprompt, to no avail. Lastly, I also tried explicitly passing the `nuget.config` using `--configfile` parameter, but again, same results.

This exact setup works perfectly from Visual Studio when restoring packages.

### Verbose Logs

```shell
dotnet package search {789456123} --verbosity detailed
****************************************
Source: GithubFeed (https://nuget.pkg.github.com/our-company/index.json)
warn : Failed to retrieve metadata from source 'https://nuget.pkg.github.com/our-company/query?q={789456123}&skip=0&take=20&prerelease=false&semVerLevel=2.0.0'.
****************************************
Source: nuget.org (https://api.nuget.org/v3/index.json)
No results found.
```

**Comment by jeffkl** [comment]
I am not able to reproduce the problem.  I created a Personal Access Token (classic) and pasted it into a `NuGet.config` and was able to authenticate.

NuGet.config
```xml
<configuration>
  <packageSources>
    <clear />
    <add key="github" value="https://nuget.pkg.github.com/jeffkl/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <github>
      <add key="Username" value="jeffkl" />
      <add key="ClearTextPassword" value="PAT_REDACTED" />
    </github>
  </packageSourceCredentials>
</configuration>
```

Output without a PAT:
```
>dotnet package search new
****************************************
Source: github (https://nuget.pkg.github.com/jeffkl/index.json)
error: Failed to retrieve metadata from source 'https://nuget.pkg.github.com/jeffkl/query?q=new&skip=0&take=20&prerelease=false&semVerLevel=2.0.0'.
```

Output with PAT:
```
>dotnet package search new
****************************************
Source: github (https://nuget.pkg.github.com/jeffkl/index.json)
No results found.
```

I just followed the steps at https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry#authenticating-to-github-packages

Can you verify that your PAT was correctly acquired?

**Comment by julealgon** [comment]
I'm sorry... you are correct @jeffkl , it works as expected. I don't understand what happened with my previous token value but for whatever reason, deleting it and creating another one worked.

I did quite a few tests with Postman making a direct request to the search URL, and interestingly enough, with the token from before, I get a `404 Not Found` (_not_ an unauthorized....), and with the new token I get a 200.

This is the 404 body:
```json
{
    "error": "The expected resource was not found."
}
```

If I change the token to something invalid, the response changes to `401 Unauthorized`.

If I create a brand new token, but don't authorize it, I _also_ get a `401 Unauthorized`.

Clearly something very weird was going on with my token, and I have no idea why (it also makes zero sense to me that it would return a 404 when using it... looks like a bug in the Github implementation to me to be honest).

I'm closing this as "cannot reproduce". I'll open a related issue for the fact that the tool doesn't expose the underlying error even in `verbose` mode though.
