### ISSUE TITLE
Target nuget.exe to .Net Core

### ISSUE THREAD

**Issue by konjac** [NuGet/Home#13330]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

The current nuget.exe is targeting .Net framework. Users on Linux are using Mono as a workaround. 

But Mono is on the deprecation path. It will be more friendly if nuget.exe could be executed on Linux through .Net Core.

**Comment by jeffkl** [comment]
A lot of the functionality of `nuget.exe` has been ported to `dotnet nuget` which is cross-platform.  Does `dotnet nuget` contain the features you need?

https://learn.microsoft.com/nuget/reference/dotnet-commands

**Comment by konjac** [comment]
@jeffkl I am expecting `nuget install`.  Some tools are distributed as nupkg. With `nuget install`, we can easily download and extract them without initializing a project.

Or could you consider porting `nuget install` to `dotnet nuget install`?

**Comment by jeffkl** [comment]
In that case, I'm closing this as a duplicate of https://github.com/NuGet/Home/issues/12513.  Please add a 👍 reaction to upvote that issue.
