### ISSUE TITLE
VS2015 installs win8 dll for UWP 10

### ISSUE THREAD

**Issue by pemari-msft** [NuGet/Home#1334]
WindowsAzure.Storage nuget package does not support UWP 10, and I believe that the target moniker for this would be win81 at minimum, correct? Currently it only supports win8. It installs correctly. Is this expected?

**Comment by pemari-msft** [comment]
(Downloaded via nuget package manager; I can provide any other details as needed).

**Comment by emgarten** [comment]
UWP is compatible with win8 (netcore45), wpa81, and PCLs that support either of those.

**Comment by pemari-msft** [comment]
Just to clarify, getting back to this, there is indeed a difference of behavior that causes a blocking bug between the win8 and UWP project types ;) So I wouldn't really say it's compatible. I'll let you know what the root cause is when I find it.
