### ISSUE TITLE
A source code nuget package defining a .cs.pp file fails to resolve the namespace if <RootNamespace> is not set in the project

### ISSUE THREAD

**Issue by vpenades** [NuGet/Home#13346]
### NuGet Product Used

dotnet.exe, MSBuild.exe

### Product Version

Msbuild 17.8.5.5502 DotNet 8.0.101

### Worked before?

no

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

Create a source code package including a .cs.pp template file that uses `namespace $rootnamespace$` ... or consume an existing source code nuget like [CodeSugar.Sys.IO.Sources](https://www.nuget.org/packages/CodeSugar.Sys.IO.Sources/) into a new project.

The test project referencing the nuget package does NOT have a `<RootNamespace>` property defined, so theoretically, the default assembly namespace should be used for `$rootnamespace$`

And what happens is this:

-At edition time, the files seem to be correctly evaluated with the correct namespace, and the files and classes are correctly found by intellisense within visual studio.
-At build time, it fails and gives errors saying that the templated files are missing due to (I guess) incorrectly resolving `$rootnamespace$`

If then, I add the `<RootNamespace>` to the test project, even if the namespace is the same as the default, then the project builds correctly.

So clearly, there's a problem at build time, the compiler is unable to resolve the root namespace if it's not explicitly defined using the `<RootNamespace>` property.

**Comment by nkolev92** [comment]
Hey @vpenades 

pp files are handled in the SDK. 

Can you please create an issue in the dotnet/sdk repo?

If you'd prefer, I can move it, but it's be under my name.

**Comment by vpenades** [comment]
Okey, I'll close it here and reopen in the dotnet/sdk
