### ISSUE TITLE
Promote from warning to error in `delete` operations

### ISSUE THREAD

**Issue by Nigusu-Allehu** [NuGet/Home#13341]
### NuGet Product(s) Affected

NuGet.exe

### Current Behavior

`nuget delete` using an http shows a warning. 

### Desired Behavior

show an error message instead.

**Comment by nkolev92** [comment]
Team Triage:
@Nigusu-Allehu please make sure issues we're working on actively are correctly labeled and part of the GH project. 
Normally that'd mean having a P2 label.

Ignore this if you couldn't add it because of the issue limit :)
