### ISSUE TITLE
Crash in CopyNupkgToStreamAsync

### ISSUE THREAD

**Issue by fbrunetgirard** [NuGet/Home#13352]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Protocol 6.9.1

### Impact

I'm unable to use this version

### Repro Steps & Context

Using proget as nuget feed , some packages cannot be downloaded
Im able to list the problematic package but download crash  at CopyNupkgToStreamAsync
```
using NuGet.Common;
using NuGet.Configuration;
using NuGet.Packaging;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;
using NuGet.Versioning;


string url = "https://myprogetfeed";
string username = "password";
string password = "";	
ILogger logger = NullLogger.Instance;
CancellationToken cancellationToken = CancellationToken.None;

SourceCacheContext cache = new SourceCacheContext();

PackageSource packageSource = new PackageSource(url);
packageSource.Credentials = new PackageSourceCredential(url,username, password, true, null);

SourceRepository repository = Repository.Factory.GetCoreV3(packageSource);
FindPackageByIdResource resource = await repository.GetResourceAsync<FindPackageByIdResource>();

string packageId = "jQuery.vsdoc";
NuGetVersion packageVersion = new NuGetVersion("1.6");

IEnumerable<NuGetVersion> versions = await resource.GetAllVersionsAsync(
		packageId,
		cache,
		logger,
		cancellationToken);

foreach (NuGetVersion version in versions)
{
	Console.WriteLine($"Found version {version}");
}

using MemoryStream packageStream = new MemoryStream();

await resource.CopyNupkgToStreamAsync(
		packageId,
		packageVersion,
		packageStream,
		cache,
		logger,
		cancellationToken);


Console.WriteLine($"Downloaded package {packageId} {packageVersion}");

using PackageArchiveReader packageReader = new PackageArchiveReader(packageStream);
NuspecReader nuspecReader = await packageReader.GetNuspecReaderAsync(cancellationToken);
```

### Verbose Logs

```shell
System.IO.InvalidDataException: 'Central Directory corrupt.'

[Exception] System.IO.Compression.dll!System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() Line 383
	at System.IO.Compression\ZipArchive.cs(383)
[Exception] System.IO.Compression.dll!System.IO.Compression.ZipArchive.ZipArchive(System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, bool leaveOpen, System.Text.Encoding entryNameEncoding) Line 179
	at System.IO.Compression\ZipArchive.cs(179)
[Exception] System.IO.Compression.dll!System.IO.Compression.ZipArchive.ZipArchive(System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, bool leaveOpen) Line 105
	at System.IO.Compression\ZipArchive.cs(105)
[Exception] NuGet.Packaging.dll!NuGet.Packaging.PackageArchiveReader.PackageArchiveReader(System.IO.Stream stream, bool leaveStreamOpen, NuGet.Frameworks.IFrameworkNameProvider frameworkProvider, NuGet.Frameworks.IFrameworkCompatibilityProvider compatibilityProvider)
[Exception] NuGet.Packaging.dll!NuGet.Packaging.PackageArchiveReader.PackageArchiveReader(System.IO.Stream stream)
[Exception] ConsoleApp1.dll!Program.<Main>$(string[] args) Line 50
	at C:\Users\fbrunetgirard\source\repos\ConsoleApp1\ConsoleApp1\Program.cs(50)
System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() Line 53
	at /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs(53)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) Line 154
	at /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs(154)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task, System.Threading.Tasks.ConfigureAwaitOptions options) Line 118
	at /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs(118)
[Waiting on Async Operation, double-click or press enter to view Async Call Stacks]
ConsoleApp1.dll!Program.<Main>(string[] args)
```

**Comment by nkolev92** [comment]
@fbrunetgirard 

That suggests that the package is invalid. 

Did you notice the issue using the NuGet tool first, or just with the SDK?

**Comment by fbrunetgirard** [comment]
> @fbrunetgirard
> 
> That suggests that the package is invalid.
> 
> Did you notice the issue using the NuGet tool first, or just with the SDK?

With more investigation i found out that using nuget restore etc is okay (the file are good on disk) because it fetch from many sources (nuget.org + my private proget feed)

But using the SDK with only proget source it seem some packages like this crash and are not available (not sure why the version appear in the list if it cannot be downloaded or found)

In receiving :
package jquery.vsdoc 1.6 on Feed (ID=1) was not found at http://myfeed/nuget/MSNUGET/v3/flatcontainer/jquery.vsdoc/1.6/jquery.vsdoc.1.6.nupk

It might be a bug in proget or with the connector im using with nuget, it's a little bit deep
Is there another method to be sure that the package is available for download in the SDK?

**Comment by nkolev92** [comment]
> Is there another method to be sure that the package is available for download in the SDK?

Your code seems pretty straightforward. It's what NuGet pretty much uses. 

Unfortunately I don't have any other suggestions.

**Comment by fbrunetgirard** [comment]
It seem that is because of Proget with what they call Quirky versions
https://docs.inedo.com/docs/proget-feeds-nuget-semver2-and-legacy-versioning
It seem that the SDK is not doing the version dancing with multiple requests as the nuget client?

**Comment by nkolev92** [comment]
I don't think that should be related. That's more about discoverability than downloading.

**Comment by zivkan** [comment]
Putting it another way, the exception message "Central Directory corrupt" suggests that some package file was successfully downloaded, but the zip file's central directory is corrupt.

Can you open the nupkg in any other zip program?

When downloading the nupkg, the logger will get the package's URL. You can copy the URL into your browser and download it there. Is the file contents different to when NuGet downloads the nupkg?

**Comment by fbrunetgirard** [comment]
> Putting it another way, the exception message "Central Directory corrupt" suggests that some package file was successfully downloaded, but the zip file's central directory is corrupt.
> 
> Can you open the nupkg in any other zip program?
> 
> When downloading the nupkg, the logger will get the package's URL. You can copy the URL into your browser and download it there. Is the file contents different to when NuGet downloads the nupkg?

My problem is that the version is shown as available but the file cannot be downloaded, there's a missmatch somewhere
Why GetAllVersionsAsync return it if it's not available?

The file is not found on the feed so an invalid zip of 0 bytes is fetch and this is why the exception is throw

**Comment by nkolev92** [comment]
> My problem is that the version is shown as available but the file cannot be downloaded, there's a missmatch somewhere
Why GetAllVersionsAsync return it if it's not available?

If a package were reported as missing, you'd be getting a 404, not a central directory corrupt. The package exists.

Even if that were true, that wouldn't be a NuGet Client SDK problem, but a server problem. The API is documented in https://learn.microsoft.com/en-us/nuget/api/overview.
