### ISSUE TITLE
[Bug Bash] The vulnerable warning flashed and disappeared in the Error List window when reloading the solution which had installed vulnerable package

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13384]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.11.0.9

### Worked before?

It’s not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. Create a C# Console App (.NET Core 8.0) project.
2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI.
3. Select the package source: “nuget.org” near the gear button.
4. Go to the "Browse" tab and search for a package (e.g. "Newtonsoft.Json").
5. Select a vulnerable package version (e.g. 12.0.1) and install the package.
6. Close VS with the solution saved and reload that solution again.
#### Expected Result: 
The vulnerable warning should be showing in the Error List window.
#### Actual Result:
The vulnerable warning flashed and disappeared immediately in the Error List window as below.
![image](https://github.com/NuGet/Home/assets/20632625/6213ef92-8d8e-4326-8425-6a4bc04240d8)
#### Notes:
1.Repro rate: 100%.
2.It is not a regression since it is a new feature.
3.Building the solution will get the warning back.

**Comment by Nigusu-Allehu** [comment]
I was not able to reproduce the issue. I closed VS and opened the solution again, however, I was still able to see the vulnerability warning without having to build the project.
![image](https://github.com/NuGet/Home/assets/59111203/1d96942d-da03-491a-92f9-9757ae122fc5)
However, I have noticed deleting the `obj` and `bin` folders of the project makes the warning disappear. Visual studio restores automatically, and these folders are created again. However, the warning does not appear again. Rebuilding brings the warning back again.

**Comment by v-luzh** [comment]
The warning didn't show (no flashed) when reloading the solution (as the screenshot I provided above) on Main\34810.77+NuGet Client Dev\6.11.0.17. I didn't delete any folder during the bug reproing.

**Comment by Nigusu-Allehu** [comment]
I have tried it again on VS Version 17.11.0 [34810.77.main] and I followed these steps
1. Install VS Version 17.11.0 [34810.77.main]
2. Create a Console App
3. Install Newtonsoft,Json 12.0.1 from the PMUI
4. Save the project.
5. Close VS
6. Open VS again an open the solution back again

As expected, I was able to see the vulnerability warning. Please let me know if I missed a step. Otherwise, it would be great if you would be able to provide us with a recording of the issue occurring to help us identify the issue. Thank you!

**Comment by v-luzh** [comment]
@Nigusu-Allehu, did you install latest NuGet Client from Dev branch on top of VS 34810.77.main? Your repro steps are correct, the only difference in our side is installing  NuGet Client from Dev branch on top of VS in your step1. I attached the video for your investigation. 

Note: the operation become very slowly when I use the recorder. So, I start to record from my step6 to make sure the video smaller enough to upload.
![NoWarningWhenReloading](https://github.com/NuGet/Home/assets/20632625/f6d8838c-dbcb-4af4-ad19-d38baf0f1a11)

**Comment by nkolev92** [comment]
Might be related to <https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/543238>

There's a chance that this won't repro with newer builds (Thursday and later). 

Can you try reproing with the latest build.

**Comment by v-luzh** [comment]
Hi @nkolev92, we can repro it on the latest build (VS Main\34816.200+NuGet Client Dev\6.11.0.26). Nothing shows in the Error List window when reloading the solution as the screenshot below.

Note: When you reloading the solution, please stare at the Error List window. When you do the first reloading after installing a vulnerable package, the vulnerability warning will flash for a second, then disappear automatically. When you do the second reloading, the vulnerability warning will not flash, it will disappear directly.
![image](https://github.com/NuGet/Home/assets/20632625/12475393-9610-4470-b6f8-df1fbe4deaa0)

**Comment by jebriede** [comment]
I'm not able to repro this. I followed the repro steps on VS Version 17.11.0 Preview 1.0 [34816.266.main] and using the latest NuGet.Client from the dev branch:
- Installed Newtonsoft,Json 12.0.1 from nuget.org using the PMUI in VS
- Note: At this step, I see the warning in the Error List. It does not disappear. It stays there.
- Save the project.
- Close VS
- Open VS and load the solution.
- After a bit of a delay, once the solution is fully loaded and the restore finishes, I see the warning in the Error list and it does not go away. Here's a screenshot:
![image](https://github.com/NuGet/Home/assets/10777837/6a62ea91-3519-4e1d-8d3e-e869bf906524)

One thing worth noting is that the Info Bar in the solution explorer shows up before the warning shows up in the Error List. In my repro, the delay was significant, about 10+ seconds later that the warning showed up. But once it showed up, it did not disappear.

I also tried closing the solution (without closing VS) and loading the solution again and the warning showed up immediately in the Error List and did not disappear. I tried repro'ing with a new project first and then tried with an existing console app project. In both cases, the warning shows up in the error list and does not disappear.

Can you help me identify if I did anything differently than you did? Maybe you can point us at a machine with a repro offline or any additional details about the setup?

**Comment by v-luzh** [comment]
Hi @jebriede, we can repro it on Main\34917.97 installed NuGet Client Dev\6.11.0.27. The steps are same with you mentioned:

- Installed Newtonsoft,Json 12.0.1 from nuget.org using the PMUI in VS.
- Note: At this step, I see the warning in the Error List. It does not disappear. It stays there.
- Save the project.
- Close VS.
- Open VS and load the solution.
- After a bit of a delay, once the solution is fully loaded and the restore finishes, **the warning showed for less than half a second and go away.** 

My repro machine: 172.16.195.27. Note: I have added the access control of the machine for you.

**Comment by jgonz120** [comment]
I followed those instructions and was unable to get it to reproduce. I'm on VS 17.11.0 Preview 1.0 [34822.286.main]. 
![image](https://github.com/NuGet/Home/assets/5552792/1b1316e1-d6df-4129-b0cb-76c02b17f842)

**Comment by v-luzh** [comment]
Hi @jebriede @jgonz120 @Nigusu-Allehu, we can still repro it in VS Main\34823.189 installing NuGet Client Dev\6.11.0.28 (on a VM). But it didn't repro in VS Main\34823.184 with implicit NuGet Client Dev\6.11.0.27 (on physical machine). Did you not repro on physical machine?

**Comment by jgonz120** [comment]
I tried it on my DevBox Vm, I just updated to the latest version of VS and am still unable to reproduce.

**Comment by v-luzh** [comment]
Hi @jgonz120, our test VMs are created in [DTL](https://ms.portal.azure.com/)->NuGetDTL/DevDiv-Test-Labs-05. Could you please try to repro on a DTL VM? Thanks.

**Comment by nkolev92** [comment]
Team Triage: 

* @v-luzh Is that a VM you're referring or something else? We don't see any VM with that name in the DTL. 
* We don't really see the flash of the warning in the repro video.
* How long did you wait before closing VS? @jebriede mentioned in https://github.com/NuGet/Home/issues/13384#issuecomment-2067491281 that it may take some time to appear. 

Technical:

NuGet does not really show the warnings, likely if there is any problem here, it'd be on the project-system side, but we need to confirm a repro before we continue.

**Comment by zivkan** [comment]
In addition to what Nikolche said, if you get into a situation where there's a yellow bar on Solution Explorer saying there's a vulnerability, but there is no warning in the Error List window, then please click on a file in the project, in Solution Explorer's menu select "show all files", then open `obj/project.assets.json`. At the end of the file there might be a section named "errors" or "messages".  We should check if there's any NU1901, NU1902, NU1903, or NU1904 messages in the assets file, to better understand where the fault is.

**Comment by v-luzh** [comment]
Hi @nkolev92, 

- The VM (172.16.195.27) is what I created on [DTL](https://ms.portal.azure.com/)->DevDiv-Test-Labs-05, I have add the control for you, so you can login it. 
- We can see the flashing for 2 seconds after reopening the solution.
- We can see the warning after step5, then we will close the VS immediately. I guess you are asking how long do we wait after reopening the solution. We will wait for 10 seconds and the warning shows up for 2 seconds and then disappear automatically forever.

Hi @zivkan, we cannot see the 'project.assets.json' file showing in Solution Explorer after clicking "show all files" button as below. 
![image](https://github.com/NuGet/Home/assets/20632625/f68d2c09-b083-4bac-81eb-2fc33211e150)

So I manually opened the 'obj/project.assets.json' in the project's path, and the log is showing like:

```
  "logs": [
    {
      "code": "NU1903",
      "level": "Warning",
      "warningLevel": 1,
      "message": "Package 'Newtonsoft.Json' 12.0.1 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr",
      "libraryId": "Newtonsoft.Json",
      "targetGraphs": [
        "net8.0"
      ]
    }
  ]
```

**Comment by jebriede** [comment]
[Team triage] @v-luzh Thank you for including the error message you are seeing in the project.assets.json file. That helps us understand that NuGet is fulfilling its part of the contract to write the error to the assets file which then is supposed to get picked up by the project system and shown in the error list and it should not be disappearing. Can I ask you to please file this issue in AzDO so we can reassign the issue to the project system to investigate why the error message is then disappearing? Thank you!

**Comment by zivkan** [comment]
> we cannot see the 'project.assets.json' file showing in Solution Explorer after clicking "show all files" button as below.

@v-luzh the screenshot shows that the solution root node in solution explorer is selected. You need to either click the project, or any node underneath the project, before clicking "show all files". By default both the obj and bin directories are under the project directory, but I think the project system now also adds a "Imports" node when "show all files" is enabled. I don't see any of these in the screenshot, which tells me that Show All Files was not correctly enabled for the project.

**Comment by v-luzh** [comment]
Hi @jebriede, I have created the internal bug [2064548](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2064548) for this issue in the area path 'DevDiv\VS Core\Project\CPS'. Please help to reassign to the correct team if that's not expected. I will close this one as External.
Hi @zivkan, yes I can see the obj and bin directories followed your instructions. Thanks all.
