### ISSUE TITLE
Regression in target frameworks for source build

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/Home#13390]
After https://github.com/NuGet/NuGet.Client/pull/5735 we're seeing a different target framework for the projects when building nuget.client from source.

It is now only building for netstandard2.0 instead of net9.0+netstandard2.0. This breaks the sdk update PR in https://github.com/dotnet/installer/pull/19412

**Before:**
<img width="1218" alt="image" src="https://github.com/NuGet/Home/assets/1376924/36e231a3-3fc9-45f2-a3e8-6b757cb46e5b">

**After:**
<img width="437" alt="image" src="https://github.com/NuGet/Home/assets/1376924/a2502286-8a7d-43b1-a37e-e30fd4ef4dfe">

/cc @jeffkl @nkolev92

**Comment by nkolev92** [comment]
@jeffkl There's a regression with the frameworks, can you please take a look?

https://github.com/NuGet/NuGet.Client/blob/dev/docs/updating-target-frameworks.md has a call out to the helper targets.

**Comment by nkolev92** [comment]
I see @mmitche has a PR in https://github.com/NuGet/Home/issues/13390, which is related, but might not fix everything.

**Comment by jeffkl** [comment]
Dang sorry about that, I always assume if the source build leg of our build pipeline is green then we're good to go.

**Comment by mmitche** [comment]
> Dang sorry about that, I always assume if the source build leg of our build pipeline is green then we're good to go.

For big updates like this, opening a PR in dotnet/dotnet to see what falls out is a good strategy.

Anyways, reading the previous code, it looks like the DotNetBuildFromSource conditional should be removed here:

https://github.com/nuget/nuget.client/compare/fb50d1a45e...d3804abb2a#diff-f347074219e3ccedc963e7527a9494778633a9106034d29ebf1365b369d64b6fR26

And this line should also have a version for DotNetBuildFromSource:

https://github.com/nuget/nuget.client/compare/fb50d1a45e...d3804abb2a#diff-f347074219e3ccedc963e7527a9494778633a9106034d29ebf1365b369d64b6fR18

**Comment by jeffkl** [comment]
@mmitche do you think it will be okay if we _only_ target .NET 9.0 for source build?  I'm not sure why we'd need to build for .NET Standard 2.0 and .NET 9.0.  My fix locally yields this for source build at the moment:

![image](https://github.com/NuGet/Home/assets/17556515/7b0542b1-1630-40fc-8fd5-1113e9c6c88f)

**Comment by mmitche** [comment]
There's probably netstandard use somewhere within the product. I don't think it is sufficient to target only the newest framework.

**Comment by jeffkl** [comment]
Okay pull request sent: https://github.com/NuGet/NuGet.Client/pull/5753
