### ISSUE TITLE
Different TypeScript versions in the package

### ISSUE THREAD

**Issue by NN---** [NuGet/Home#1339]
NuGet supports packaging for different platform versions such as .NET .
TypeScript releases sometimes have a breaking changes and make old code illegal.
It means that at some point we need a package which is suitable for several TypeScript versions.

Is there a possibility to make a package working for TypeScript 1.0 and 1.6 in the same package ?

**Comment by yishaigalatzer** [comment]
Going forward we are deprecating content packages, but plan to add support for languages. This is a good idea to include a minimal language version in the spec for shared sources.

CC @davidfowl

**Comment by NN---** [comment]
@yishaigalatzer What is the replacement for content packages ?
All ![DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) packages are content packages.

**Comment by yishaigalatzer** [comment]
There is no deprecation for existing scenarios. So if you use packages.config it will work the same as today.

When it comes to project.json we at building a new feature for shared sources. We discussed language version support and have provisions for it but that's not going to be available in the first version supporting it.

Cc @pilchie @emgarten

**Comment by 304NotModified** [comment]
Maybe this issue is broader, we like to have one package for Asp.net and asp.net core

**Comment by nkolev92** [comment]
The direction that NuGet has pivoted in right now is that every packages need to have specific compatible assets. 

Closing this issue as redundant for now. 
Please re-open this issue if facing similar issues.
