### ISSUE TITLE
Error during updating a version after renaming a package with uppercase.

### ISSUE THREAD

**Issue by meokullu** [NuGet/Home#13404]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

9.0.100-preview.1.24101.2, 6.10.0.18

### Worked before?

No.

### Impact

I'm unable to use this version

### Repro Steps & Context

1. Download Prefill https://www.nuget.org/packages/Prefill/2.1.0
2. Update it to PreFill v2.2.0 https://www.nuget.org/packages/PreFill/2.2.0

During update, it returns an error.

![Screenshot 2024-04-22 002053](https://github.com/NuGet/Home/assets/4971757/7b47bb4d-b5da-494d-aa9f-1e642eda17b5)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/13259 and https://developercommunity.visualstudio.com/t/Update-nuget-package-causes-NullReferenc/10584808. 

Can you update to the latest Visual Studio version?

**Comment by meokullu** [comment]
The problem is resolved after updating Visual Studio. Thanks.
