### ISSUE TITLE
Missing Installation details in Nuget page for Mvc 6.0.0-beta7

### ISSUE THREAD

**Issue by NeelBhatt** [NuGet/Home#1340]
I have recently found that there is missing details for installation of beta7 from Nuget.

which should be

`PM> Install-Package Microsoft.AspNet.Mvc -Version 6.0.0-beta7 -Pre`

instead of

`PM> Install-Package Microsoft.AspNet.Mvc -Pre`

Nuget Link:
https://www.nuget.org/packages/Microsoft.AspNet.Mvc/6.0.0-beta7

Or may be i am missing something then let me know i will close immediately.

**Comment by yishaigalatzer** [comment]
`
PM> Install-Package Microsoft.AspNet.Mvc -Pre
`

is correct. It will install that version of package into your project (if its applicable)

**Comment by NeelBhatt** [comment]
ok thanks
