### ISSUE TITLE
Unable to upload package via .NET CLI (403 Error)

### ISSUE THREAD

**Issue by Center-Deal** [NuGet/Home#13403]
### NuGet Product Used

dotnet.exe, Other/NA

### Product Version

latest

### Worked before?

No

### Impact

I'm unable to use this version

### Repro Steps & Context

Follow the steps [here](https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli) to upload a package.

On the section labeled "Publish with the .NET CLI or NuGet CLI", copy the code snippet:
'''dotnet nuget push Contoso.08.28.22.001.Test.1.0.0.nupkg --api-key qz2jga8pl3dvn2akksyquwcs9ygggg4exypy3bhxy6w6x6 --source https://api.nuget.org/v3/index.json'''. This is the .NET CLI snippet. Replace the values as indicated (ID, API key, etc).

Console outputs: "error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)."/

For context, yes I verified the API key is correct, and yes I ensured that my package ID was globally unique. I triple checked, repackaged, and retried several times at different times of day, just in case.

Upload via the CLI did not work. 

I tried uploading through the web interface. Worked on first try, as expected.

**Comment by jgonz120** [comment]
Hello, I was unable to reproduce this issue following these [steps](https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli). I know you've checked a bunch of things already, but can you verify that the API Key has the GLOB pattern set to ```*``` or to something that would have access to your package?
