### ISSUE TITLE
NuGet Package Restore incompatible with custom ‘packages’ folder location and authentication

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#1341]
NuGet Pacakge Manager 2.8.60723.765 for VS2013.

Automatic restore is enabled in Tools/Options/NuGet Package Manager/
  -Allow NuGet to download missing package - YES
  -Automatically check for missing packages during build in Visual Studio - YES

It's enabled in `.nuget\nuget.config` file (the `.nuget` folder is on the same level as sln file):  

```
<configuration>
    <packageRestore>
        <add key="enabled" value="true" />
    </packageRestore>
    <config>
    <add key="repositoryPath" value="$\..\..\..\packages" />
</config>
    <solution>
        <add key="disableSourceControlIntegration" value="true" />
    </solution>
  <packageSources>
    <add key="rnd" value="https://artifacts.croc.ru/api/nuget/rnd-nuget-dev" />
  </packageSources>
</configuration>
```

When I run Rebuild NuGet doesn't try to restore missing packages and msbuild reports errors.

**Comment by evil-shrike** [comment]
More details. As you can see I have [repositoryPath](https://docs.nuget.org/Release-Notes/NuGet-2.1#Specify-packages-Folder-Location) option (my several solutions share the same packages folder). 
If I remove the `repositoryPath` option (and restart VS), then NuGet seems to behave more correctly - it shows me a warning of missing packages.
When I run Rebuild NuGet tries to download packages. BUT, It fails with 401 error - my repository requires authentication.

So I can see several bugs here:  
- Auto-Restore feature of NuGet Package Manager doesn't work if `repositoryPath` is used  
- Auto-Restore feature of NuGet Package Manager doesn't support authentication, when in all other places it does support authentication - if I click "Restore" in the mentioned warning on missing packages ("Some NuGet packages are missing from this solution. Click to restore from your online package sources") then NuGet will ask me for credentials.

**Comment by yishaigalatzer** [comment]
1. Try using forward slashes and no $.
2. Include credentials in nuget.config, then it will not need to ask you. At build time I would not expect popups to come up.

Please confirm this solves (or not) your issue, and close if it does.

**Comment by evil-shrike** [comment]
1. I changed "$\..\..\..\packages"  to "../../../packages".
2. Removed one package in the `packages` folder
3. Opened VS
4. Nothing. No "missing packages" warning in Package console/manager, no package restore (i.e. build fails)

Then I removed _all_ `packages` folder and opened VS.
Hurray! These's the expected warning in Package console/manager. I clicked "Restore" and it restored my packages.

Then I removed the `packages' folder again and reopened VS.
It showed the warning but I didn't click "Restore". Instead I run a build. I got the error 401 for each my project:

```
NuGet Package restore failed for project WebServer.Interop: The remote server returned an error: (401) Unauthorized..
NuGet package restore failed.
```

I do have credentials specified for my sources in nuget.config in my user's profile. I have a source in project's nuget.config pointing to a source for which there're credentials in global nuget.config (in user's profile). That source works as "restore" in Package console works fine - when I click "Restore" in warning on missing packages nuget restores packages normally without 401s or asking for credentials. But not during "package restore" which is triggered by a build.

So "package restore" incorrectly works with `repositoryPath` in the following aspects:
- Nuget can't determine a missing package if a folder specified in `repositoryPath` option exists (if it doesn't exist then it correctly determines missing packages and suggests restore)
- Nuget doesn't support sources with authentication when does "package restore" triggered by a build (or it incorrectly choose a source for restore)

**Comment by yishaigalatzer** [comment]
How do you restore during build? Is it with a target and nuget.exe?

We can look at fixing this in 3.3 (for visual studio 2015) if it still repros.

@zhili1208 can you please take a look?

**Comment by evil-shrike** [comment]
@yishaigalatzer 

> How do you restore during build? Is it with a target and nuget.exe?

Right click on solution and click "Build".

> We can look at fixing this in 3.3 (for visual studio 2015)

that's nice, but it's failing in VS2013 which we're widely using

**Comment by yishaigalatzer** [comment]
@evil-shrike 

I'm asking if your project file is using restore in an msbuild target or not, I don't get the answer.

I know its not the message you want to hear, and I truly apologize. However when it comes to fixing this level of bugs VS 2013, this is a lower priority goal at this point. We are focused on the visual studio 2015 extension, and I don't see us getting to fixing 2013 for this kind of bug.

We will however gladly take a pull request if you are interested in contributing it. Or we can get back to it when our list of high priority issues dwindles.

**Comment by evil-shrike** [comment]
@yishaigalatzer 
I'm talking about the new "package restore" feature (since nuget 2.7) - http://docs.nuget.org/consume/package-restore not old one which was implemented via msbuild target.

**Comment by evil-shrike** [comment]
Well it seems I understand what's going on. 

First of all, NuGet does correctly install missing packages. I was just wrongly renaming a package's folder with some prefix ("~~") hoping that it should be looking as missing for Nuget. But it didn't, as Nuget actually found it even in a wrong folder. My fault. I apology.

As for getting 401 during restore. It's a bit trickier. If I have a source with authz (which will be default source) then Nuget will fail with 401 during restore. BUT if before running a build I open "Package Manager Console" window (and it's initialized) then Nuget will use cached credentials (or ask from them). And restore will succeed.

**Comment by yishaigalatzer** [comment]
Sounds like this is not so bad after all. You are saying the only remaining issue is that cached credentials are dependent on the PowerShell console being opened?

**Comment by evil-shrike** [comment]
@yishaigalatzer exactly! I've created a separate issue #1368, and closing this one. Thanks for your help.

**Comment by manojsagoi** [comment]
Hi , 
i want my packages dll to be download here 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls

but even after using <add key="repositoryPath" value="..\..\..\packages" />

its downling 2 level back ,
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\
please suggest some input on this.

**Comment by manojsagoi** [comment]
Hi , 
i want my packages dll to be download here 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls
but even after using <add key="repositoryPath" value="..\..\..\packages" />
its downloding 2 level back ,
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\
please suggest some input on this.

**Comment by manojsagoi** [comment]
Hi , 
i want my packages dll to be download here 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls
but even after using 
add key="repositoryPath" value="......\packages" in nuget.config
its downloading 2 level back ,in this location
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\
please suggest some input on this.

**Comment by zhili1208** [comment]
Where's your nuget.config? repositoryPath is relative to nuget.config

**Comment by manojsagoi** [comment]
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController.nuget\nuget.config
is it fine ?

**Comment by zhili1208** [comment]
So the nuget.config is at C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController.nuget\

And you want your packages to be download here: 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls

then the repositoryPath value should be "..\XsmController\XsmDll\dlls"

**Comment by manojsagoi** [comment]
ahhh tried your suggestion but don't know why its taking this path
'C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\packages'

instead of 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls

**Comment by zhili1208** [comment]
Did you reopen the solution after change?

**Comment by manojsagoi** [comment]
yeahh i guess you solved my issue :) thanks a lot ..
but one thing i am seeing its creating one more folder by name  XsmController  , let me check it

**Comment by manojsagoi** [comment]
Hi one more question .
when i am executing install-package XSMDB -version 5.21.35 my all dlls getting downloaded to 
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls

that's fine .

but i am getting more folders which are getting downloaded .
C:\TFS\XGS-SDI\XOS\Integrations\Development\XisImprovement\XsmController\XsmDll\dlls\XSMDB.5.21.39.0\lib\net40

i don't want additional   XSMDB.5.21.39.0\lib\net40     folder can you please check ?

**Comment by zhili1208** [comment]
So you mean you just want to download the nupkg but don't want to expand the package, is that right?
what's your issue with the folder? because you don't want the folder be added to TFS or something else?

**Comment by manojsagoi** [comment]
I want to download DLLs only without there default folder structure. I don't want to check-in folders in TFS.

**Comment by yishaigalatzer** [comment]
That's not supported and not a recommended practice.

**Comment by manojsagoi** [comment]
Oops than can someone help me on this: 
1: I want to automate the nuget configuration process in vs2015.
2: in my project we are using only 24 DLLs but install nuget downloading all 60 DLLs , how to filter only 24 DLLs

**Comment by yishaigalatzer** [comment]
Feel free to email support@nuget.org with a concrete example and we can try to help
