### ISSUE TITLE
There is an error showing that a dll file path cannot be found when patching .NET SDK 9.0.1xx with NuGet Dev latest build

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13412]
### NuGet Product Used

NuGet SDK

### Product Version

Dev\6.11.0.30

### Worked before?

It’s not a regression since the patch tool was updated recently.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1. Open a "Developer Command Prompt" and run `Git clone https://github.com/NuGet/Entropy.git` to get the latest “Entropy”.
2. Open a Powershell from Task Manager with the “powershell -ExecutionPolicy Bypass” set & “Create this task with administrative privileges” checked.
3. Download the “nupkgs – NonRTM” folder from NuGet Client Dev latest build’s Artifacts to the desktop of your test machine and named "nupkgs".
4. Go to the SDKPatchTool folder: "…\Entropy\SDKPatchTool" in the PS prompt in step2 and run the “SDKPatch.ps1” script with the commands:
`.\SDKPatch.ps1 -SDKPath C:\Users\v-luzh.FAREAST\Desktop\PatchedSDK -NupkgsPath C:\Users\v-luzh.FAREAST\Desktop\nupkgs -SDKChannel 9.0.1xx -Quality daily`
#### Expected Result: 
The patching is successful.
#### Actual Result:
There is an error saying “Cannot find path 'C:\Users\v-luzh.FAREAST\Desktop\PatchedSDK\sdk\9.0.100-preview.5.24224.9\NuGet.Packaging.Core.dll' because it does not exist” as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/cf015ef2-2c65-407d-9a4f-0be58fb70332)
#### Notes:
1.The repro rate is 100%.
2.It doesn’t repro with “-SDKChannel 8.0.3xx” in the step4.
3.I verified the reported path, it exists but don’t know why it said does not exist.

**Comment by nkolev92** [comment]
Pushed a fix.
