### ISSUE TITLE
There is an error when patching .NET SDK with NuGet Dev latest build

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13419]
### NuGet Product Used

Other/NA

### Product Version

Entropy

### Worked before?

It’s not a regression since the patch tool was updated recently.

### Impact

It's more difficult to complete my work

#### Repro Steps: 
1. Open a "Developer Command Prompt" and run Git clone https://github.com/NuGet/Entropy.git to get the latest “Entropy”.
2. Open a Powershell from Task Manager with the “powershell -ExecutionPolicy Bypass” set & “Create this task with administrative privileges” checked.
3. Download the “nupkgs – NonRTM” folder from NuGet Client Dev latest build’s Artifacts to the desktop of your test machine and named "nupkgs".
4. Go to the SDKPatchTool folder: "…\Entropy\SDKPatchTool" in the PS prompt in step2 and run the “SDKPatch.ps1” script with the commands:
     .\SDKPatch.ps1 -SDKPath C:\Users\v-luzh.FAREAST\Desktop\PatchedSDK -NupkgsPath C:\Users\v-luzh.FAREAST\Desktop\nupkgs -SDKChannel 8.0.3xx -Quality daily
#### Expected Result: 
The patching is successful with no error.
#### Actual Result:
There is an error saying “A parameter cannot be found that matches parameter name ‘or’” as the screenshot below.
![image](https://github.com/NuGet/Home/assets/20632625/ee9e1a69-a371-4d18-b528-61f5e503633a)
#### Notes:
1.The repro rate is 100%.
2.It also repro with “-SDKChannel 9.0.1xx” in the step4.But the error is different as below.
![image](https://github.com/NuGet/Home/assets/20632625/ca67cb9c-79dc-4c72-8ced-0a0c12bda8c3)
3.It blocked all the test cases which try to run the command ‘dotnet.exe’ in the PatchedSDK folder with the error as below.
![image](https://github.com/NuGet/Home/assets/20632625/ed5cec48-780b-46b4-9080-70ee56656389)

**Comment by nkolev92** [comment]
Fixed now. 

8.0.xx should work. 

9.0.x The .NET installation is not a failure of this script, but something must have gone wrong with the .NET SDK publishing. Let's wait for a few builds. 
If it's still failing, please file an issue at: https://github.com/dotnet/installer/

Final thing, @v-luzh Please refer to https://github.com/NuGet/Entropy/blob/main/SDKPatchTool/ReadMe.md#picking-a-channel. 
At this point 8.0.4xx exists, https://github.com/dotnet/sdk/tree/release/8.0.4xx. 

And as per the doc I linked: 

> Every single time a NuGet minor version changes, the SDK channel has to be incremented

6.10 matched 8.0.3xx, 6.11 should be tested against 8.0.4xx

**Comment by v-luzh** [comment]
Thanks @nkolev92, it is fixed after verifying with 8.0.4xx. 9.0.1xx still doesn't work. We will wait for a few builds and check again.
Note: I tagged the bug with P1 since it blocked two testing. Please correct the priority if you think it is incorrect.
