### ISSUE TITLE
[Bug Bash] An error occurs when deleting the package and building solution at the second time after checking the “Automatically check for missing packages during build in Visual Studio” in Options dialog for UWP project

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13411]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.11.0.30

### Worked before?

It is not a regression since it reproes on both D16.11\34601.136 with implicit NuGet Client 5.11.6.4 and D17.9\34601.282 with implicit NuGet Client 6.9.1.3. 

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Create a C# Blank App (Universal Windows) project in VS and open the PM UI or PMC window. 

2. Install a package (e.g. log4net) through PM UI. 

3. Click the settings button (gear button) on PM UI or PMC window. 

4. Click the NuGet Package Manager->General in the opened “Options” window. 

5. Check the “Automatically check for missing packages during build in Visual Studio” and click OK button. 

6. Go to the path “C:\Users\[username]\.nuget\packages” and delete the installed package “log4net”. 

7. Go back to VS and build the solution. 

8. Verify the package will be restored successfully to the path in step6 and there will be no error and warning in the Error List window in step7. 

9. Re-delete package “log4net” and build the solution. 

#### Expected:    

The package “log4net” is restored successfully again to the path “C:\Users\[username]\.nuget\packages” and there will be no error or warning in the Error List window. 

#### Actual: 

The following error occurs, and the package has not been restored back.   
![image](https://github.com/NuGet/Home/assets/84695155/fc9021bb-ee8b-451e-986c-ce1b5d5d169f)
#### Notes:     

1. The repro rate is 100%.     

2. It doesn’t repro for non-SDK based projects. 

3. The error will disappear, and the package will be restored back after rebuilding solution. 

4. The error doesn’t disappear and the package doesn’t restored back according to error tips to run restore package.

**Comment by jgonz120** [comment]
I was able to repro. If you run nuget restore from the CLI it downloads the package again, the restore from the context menu in VS does not.

**Comment by nkolev92** [comment]
This is a known caveat of the partial restore optimization in Visual Studio. 
Documented here: https://github.com/NuGet/Home/blob/dev/accepted/archive/VisualStudio-PartialRestoreOptimization.md#caveats. 

We basically assume packages out of the packages folder won't get deleted in a single Visual Studio session. 

Runing a clean/build or a rebuild will redownload.

**Comment by v-luzh** [comment]
Thanks, @nkolev92. We marked this as P2, please feel free to correct it if you think it is other priority.

**Comment by nkolev92** [comment]
Hey @v-luzh this is closed as by design, so it can't be more than P3.

We don't really set priority for issues we won't change.
