### ISSUE TITLE
`PackageSourceProvider.UpdatePackageSource` doesn't respect a value from `AllowInsecureConnection` field

### ISSUE THREAD

**Issue by seclerp** [NuGet/Home#13418]
### NuGet Product Used

NuGet SDK

### Product Version

6.9.1

### Worked before?

No, this is not a regression

### Impact

I'm unable to use this version

### Repro Steps & Context

Hi folks, a `PackageSourceProvider.UpdatePackageSource` method from the `NuGet.Configuration` package doesn't respect the `PackageSource.AllowInsecureConnections` property value.

This is due to a missing expression in the `if` statement here:
https://github.com/NuGet/NuGet.Client/blob/3ebcf80e47ce6aaca1d017acd8750e27c8208822/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L616-L617

To reproduce the issue you could use a simple code snippet:

```csharp
using NuGet.Configuration;

var configContents = """
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <packageSources>
            <add key="default-http" value="http://api.nuget.org/v3/index.json" />
        </packageSources>
    </configuration>
    """;

File.WriteAllText(Path.Combine(Environment.CurrentDirectory, "NuGet.Config"), configContents);

var settings = new Settings(Environment.CurrentDirectory);
var packageSourceProvider = new PackageSourceProvider(settings);

var source = packageSourceProvider.GetPackageSourceByName("default-http")!;
source.AllowInsecureConnections = true;
packageSourceProvider.UpdatePackageSource(source, false, false);

// Loading brand new Settings instance to ensure we are not checking for cached value
settings = new Settings(Environment.CurrentDirectory);
packageSourceProvider = new PackageSourceProvider(settings);
source = packageSourceProvider.GetPackageSourceByName("default-http")!;

var value = source.AllowInsecureConnections; // false, should be true
```

**Comment by nkolev92** [comment]
Team Triage: Assigning to @Nigusu-Allehu as the SME here. 

There's a PR out for this already
