### ISSUE TITLE
[Feature]: Identify and report the package(s) with a transitive dependency upon a vulnerable package

### ISSUE THREAD

**Issue by jhennessey** [NuGet/Home#13422]
### NuGet Product(s) Involved

dotnet.exe

### The Elevator Pitch

When running `dotnet list <project> package --vulnerable --include-transitive` the generated report will include transitive dependencies with detected vulnerabilities. However, the report (text or JSON format) does not include which top-level package(s) depend upon the transitive dependency. Therefore, when automating vulnerability scans, it becomes difficult to know which packages should be reviewed for updates. Including this information in the generated report file would greatly ease the effort required to determine what packages require updates.

**Comment by kartheekp-ms** [comment]
I am able to reproduce the issue.

1. Created a Console application targetting net7.0 target framework.
2. Installed `Microsoft.Build` package 16.8.0 version.
3. Executed `dotnet list package --vulnerable --include-transitive --format json`

```json
{
  "version": 1,
  "parameters": "--vulnerable --include-transitive",
  "sources": [
    "https://api.nuget.org/v3/index.json"
  ],
  "projects": [
    {
      "path": "[REDACTED]/ConsoleApp1.csproj",
      "frameworks": [
        {
          "framework": "net7.0",
          "transitivePackages": [
            {
              "id": "System.Drawing.Common",
              "resolvedVersion": "4.7.0",
              "vulnerabilities": [
                {
                  "severity": "Critical",
                  "advisoryurl": "https://github.com/advisories/GHSA-rxg9-xrhp-64gj"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
As you can see from the output there is no top-level package id that resulted in the installation of the vulnerable package.

FWIW, the top-level package that resulted in the installation of the vulnerable dependency package even with out using `--format` option.

```
dotnet list package --vulnerable --include-transitive

The following sources were used:
   https://api.nuget.org/v3/index.json

Project `ConsoleApp1` has the following vulnerable packages
   [net7.0]:
   Transitive Package           Resolved   Severity   Advisory URL
   > System.Drawing.Common      4.7.0      Critical   https://github.com/advisories/GHSA-rxg9-xrhp-64gj
```

That being said, @jhennessey we are working on adding [`dotnet nuget why`](https://github.com/NuGet/NuGet.Client/pull/5761) command to print the graph or entire package path that led to installation of any transitive package. May be the new command would be helpful as a work around until this issue has been resolved.

**Comment by jhennessey** [comment]
@kartheekp-ms Thanks for pointing out the `dotnet nuget why` command issue, that will definitely be useful. I also found #11625 asks for the same thing here. I'll go ahead and close this issue.
