### ISSUE TITLE
Flaky test PackCommandTests.PackCommand_PackTargetHook_ExecutesBeforePack

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13428]
This test is looking for .NET 7.0 packages which do not exist.

Dotnet.Integration.Test.PackCommandTests.PackCommand_PackTargetHook_ExecutesBeforePack(tfmProperty: "TargetFrameworks", tfmValue: "netstandard1.4;net7.0")

> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Found 0 version(s) in dotnet-eng
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Found 0 version(s) in dotnet-eng [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Found 0 version(s) in myget-legacy@Local
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Found 0 version(s) in myget-legacy@Local [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from dotnet-libraries were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from dotnet-libraries were not considered [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from nuget-build were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from nuget-build were not considered [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from vside were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from vside were not considered [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.20)
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.20) [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Found 288 version(s) in myget-legacy@Local [ Nearest version: 3.0.0-preview6-19253-01 ]
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Found 288 version(s) in myget-legacy@Local [ Nearest version: 3.0.0-preview6-19253-01 ] [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Found 110 version(s) in dotnet-public [ Nearest version: 8.0.0-preview.1.23112.2 ]
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Found 110 version(s) in dotnet-public [ Nearest version: 8.0.0-preview.1.23112.2 ] [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Found 0 version(s) in dotnet-eng
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Found 0 version(s) in dotnet-eng [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from dotnet-libraries were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from dotnet-libraries were not considered [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from nuget-build were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from nuget-build were not considered [D:\a\_work\1\s\build\build.proj]
> ##[error]D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj(0,0): Error NU1102: - Versions from vside were not considered
> D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj : error NU1102: - Versions from vside were not considered [D:\a\_work\1\s\build\build.proj]
>     Failed to restore D:\a\_work\1\s\.test\work\f54e592d\3dea106d\ClassLibrary1\ClassLibrary1.csproj (in 469 ms).
>   
>   , but found 1 (difference of 1).
>     Stack Trace:
>        at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
>      at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
>      at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
>      at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
>      at Dotnet.Integration.Test.DotnetIntegrationTestFixture.RunDotnet(String workingDirectory, String args, Boolean expectSuccess, IReadOnlyDictionary`2 environmentVariables) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\DotnetIntegrationTestFixture.cs:line 227
>      at Dotnet.Integration.Test.DotnetIntegrationTestFixture.RestoreProjectExpectSuccess(String workingDirectory, String projectName, String args) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\DotnetIntegrationTestFixture.cs:line 196
>      at Dotnet.Integration.Test.PackCommandTests.PackCommand_PackTargetHook_ExecutesBeforePack(String tfmProperty, String tfmValue) in D:\a\_work\1\s\test\NuGet.Core.FuncTests\Dotnet.Integration.Test\PackCommandTests.cs:line 3411
>      at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>      at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
>

**Comment by jeffkl** [comment]
I'll work on a fix for this
