### ISSUE TITLE
Reference not working after migrating to PackageReference

### ISSUE THREAD

**Issue by JustinPechstein** [NuGet/Home#13427]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

.NET SDK Version 8.0.204

### Worked before?

Unknown

### Impact

I'm unable to use this version

### Repro Steps & Context

Hello, 
yesterday I restructured my files and projects a bit and since I did this I have this new errormessage " Must use PackageReference".

![image](https://github.com/NuGet/Home/assets/139776864/dba9adc6-1c98-4250-bfbf-521c0c6b19f7)

I quickly found out that I have to migrate the packages.config to PackageReferences to solve this problem. 

![image](https://github.com/NuGet/Home/assets/139776864/8cd20f39-b214-4543-950d-ec5c0c4d3b8c)

So I did the migration as shown (once with every transitive dependencies checked and once with only the Top-level dependencies).

This worked completely fine for all the projects, instead of "Microsoft.Office.Interop.Excel". After the migration the reference is bugged and the "new" behavior is hard to explain. In general the reference exists:

![image](https://github.com/NuGet/Home/assets/139776864/559c231d-0b98-4853-9de4-0089961d27b1)

and I can use it in the using section without any problems:

![image](https://github.com/NuGet/Home/assets/139776864/e460708a-360f-4820-b69c-8c3a951d6279)

But, without doing anything I have tons of errors because of whatever reason...

![image](https://github.com/NuGet/Home/assets/139776864/4fcc65cd-a5b5-44be-be85-743e84c8f604)

There are several datatypes that can be resolved but the properties for "Rows" and "Cells" are not being found.

![image](https://github.com/NuGet/Home/assets/139776864/006ede65-d197-460f-8f52-950207d6957f)

I am very curious about this, did I miss something, did the migration miss something? Or might this be a problem with that package?

I am thankful for every helpful response because I cannot carry on right now...

**Comment by donnie-msft** [comment]
I repro'd this and what's happening is when packages.config is used, the Interop assembly is loaded from your machine's GAC. Package Reference doesn't do this for reasons described below.
Let me know if you have any questions about this.

**Workaround** is in this comment: https://github.com/dotnet/sdk/issues/987#issuecomment-286307697
**Explanation** in this comment: https://github.com/dotnet/sdk/issues/987#issuecomment-286307943

**Comment by JustinPechstein** [comment]
I will definitely try this out. Thank you very much!

**Comment by JustinPechstein** [comment]
Unfortunately I have to reopen this issue, in fact it did not fix my issue. I added 
<PropertyGroup>
  <AssemblySearchPaths>$(AssemblySearchPaths);{GAC}</AssemblySearchPaths>
</PropertyGroup>
to the specific .csproj and I also tried this: https://github.com/dotnet/sdk/issues/987#issuecomment-318172879 but the problem remains...

**Comment by zivkan** [comment]
@JustinPechstein are you trying to build with `dotnet` or `msbuild`?  As per https://github.com/dotnet/sdk/issues/987#issuecomment-318172879, only msbuild has access to the GAC. The dotnet CLI does not.
