### ISSUE TITLE
Logger is not fully wired up in NuGet.Core

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#1343]
The design in the NuGet.Core code is to write warnings and errors to a Logger object. The results are then displayed to the user in different ways each appropriate to the scenario.

However the Logger is not universally wired-up. Specifically it is not wired up in the ExpandedPackageRepository which means errors in reading the packages unzipped on the file system are not shown to the user. (Because errors are written to the default NullLogger instance.)

The Logger needs to be passed through the various layers of implementation. One implementation to consider would be to make it a member of the base class PackageRepositoryBase. Currently the Logger is a member of the file-system abstractions, although it is not always initailized correctly.

**Comment by yishaigalatzer** [comment]
This should be verified for both the extension(s) 2.8.9 and 3.3, as well as command line
