### ISSUE TITLE
PetaPoco 对postgres 数据支持有bug 

### ISSUE THREAD

**Issue by kchanghui** [NuGet/Home#13435]
### NuGet Product Used

NuGet.exe

### Product Version

6.0.677

### Worked before?

6.0.677

### Impact

It's more difficult to complete my work

### Repro Steps & Context

PetaPoco 对postgres 数据支持有bug , 当插入数据表 表名 会有引号“myTable”, Npgsql.PostgresException:“42P01: 关系 "myTable" 不存在”, 实际表是存在的

### Verbose Logs

```shell
PetaPoco 对postgres 数据支持有bug , 当插入数据表 表名 会有引号“myTable”, Npgsql.PostgresException:“42P01: 关系 "myTable" 不存在”, 实际表是存在的
```

**Comment by jeffkl** [comment]
Sorry you're experiencing this issue.  The error message indicates that there is something wrong with Postgres, I suggest you seek support at https://www.postgresql.org/support/
