### ISSUE TITLE
Adding nuget package does not add a packagereference

### ISSUE THREAD

**Issue by C-Wal** [NuGet/Home#13433]
### NuGet Product Used

MSBuild.exe, Visual Studio Package Management UI

### Product Version

MSBuild version 17.9.8+b34f75857 for .NET Framework 17.9.8.16306

### Worked before?

Don't know

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I have a simple class library in .Net Framework 4.8.  It has a packages.config containing Nuget.Build.Tasks.Pack and Newtonsoft.Json.  I right-click to migrate to PackageReference and the report and output look good.  In VS I can see little blue nuget icons for Newtonsoft.Json and Nuget.Build.Tasks.Pack in my references.  However, no PackageReference entries have been added to my csproj, and if I delete the projects obj folder then the references dissapear and I can't build the project.

What's going on?  Even adding a random package like BoDi does nothing to my ,csproj.  Do I now need to check in the contents of my /obj folder to source control to get PackageReference to work in my builds???

**Comment by C-Wal** [comment]
This seems broken even in the most trivial use case.

Steps:
In VS 2022, create a new class library project targeting .Net Framework 4.8.
Add a nuget package reference to Newtonsoft.Json.
Add a using statement for Newtonsoft.Json to Class1.cs
Right-click on packages.config and choose to convert to PackageReference.
Follow wizard, no errors shown.
Check the .csproj, no PackageReference for Newtonsoft.Json is added.
Delete /bin and /obj and build the project and it fails: 'Type or namespace name Newtonsoft cannot be found'.

Note, inspecting the project references will show NewtonsoftJson as a nuget reference but it's not really there and doesn't work and going to 'Manage NuGet packages' in VS shows there are no packages installed in the project.

I am using VS 2022 (version 17.9.6).

**Comment by C-Wal** [comment]
I have figured out the issue.  You absolutely MUST do a BUILD after the migration step or the tooling does not add the PackageReference entries to the .csproj at all.  Very brittle process but hopefully this helps anyone else who has this problem.

**Comment by drguildo** [comment]
@C-Wal Please re-open this. A workaround isn't a fix.

**Comment by C-Wal** [comment]
> [@C-Wal](https://github.com/C-Wal) Please re-open this. A workaround isn't a fix.

I'm not sure it's really a 'workaround' as such.  Just make sure you do a build after you run the migration tool and it should be fine.

**Comment by drguildo** [comment]
Don't you think it would delightful if people didn't have to encounter the same issue, spend time trying to diagnose the cause, then spend time searching the web to find this GitHub issue?

Come with me and imagine a world in which the process that claims to convert a project to PackageReference format actually added the PackageReferences without extra, undocumented steps.

Not that I think this will ever get fixed, but we can dream, can't we?

**Comment by drguildo** [comment]
Also, your workaround of doing an immediate build after conversion doesn't work. I've had a few projects where I did a conversion, immediately built afterwards, and the build failed because the PackageReferences hadn't been added.

**Comment by C-Wal** [comment]
It worked for me when I did it, but I've not had to do it since.  I suggest you create your own issue/bug as the version numbers will now be different and you can provide more feedback than me to anyone investigating it.
