### ISSUE TITLE
Project that does not use external NuGet packages will not run because of missing packages

### ISSUE THREAD

**Issue by SHOOSH12SR** [NuGet/Home#13440]
### NuGet Product Used

dotnet.exe, NuGet.exe, Visual Studio Package Management UI

### Product Version

dotnet Version 8.0.205, could not find NuGet version or msbuild version

### Worked before?

same dotnet version

### Impact

I'm unable to use this version

### Repro Steps & Context

I was working on a Blazor wasm project but then transitioned to a console project that uses a NuGet package (Raylibcs installed through VS2022 NuGet menu). when I went to work on the Blazor project it wouldn't run because it couldn't find the Raylib package.
all dotnet projects were working fine before installing Raylib, now they don't run because they can't find the dependency.

### Verbose Logs

```shell
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]
C:\Users\ssrou\source\repos\calc\calc\Server\calc.Server.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist.
C:\Users\ssrou\source\repos\calc\calc\Server\calc.Server.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist.
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]
C:\Users\ssrou\source\repos\calc\calc\Server\calc.Server.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist.
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]
C:\Users\ssrou\source\repos\calc\calc\Client\calc.Client.csproj : error NU1301: The local source 'C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs' doesn't exist. [C:\Users\ssrou\source\repos\ca
lc\calc\Server\calc.Server.csproj]

The build failed. Fix the build errors and run again.
```

**Comment by jeffkl** [comment]
@SHOOSH12SR it looks like you've configured a local feed pointing to a folder at `C:\Users\ssrou\AppData\Roaming\NuGet\raylibcs`.  I would suggest removing that feed from your configuration to get unblocked.  Information about where NuGet finds configuration files is at https://learn.microsoft.com/nuget/consume-packages/configuring-nuget-behavior

**Comment by SHOOSH12SR** [comment]
I've created nuget config files for each solution and it works but all other projects (including new ones) need a `nuget.config` file to run. is there a way to reset the machine-wide config or something along those lines?

**Comment by jeffkl** [comment]
Yes you'll need to open your machine-wide and user-wide configuration and see what's configured that feed.

`%AppData%\NuGet\NuGet.Config` and `%ProgramFiles(x86)%\NuGet\Config\*.config`

**Comment by SHOOSH12SR** [comment]
it works, thank you so much!
