### ISSUE TITLE
[Bug]: dotnet restore throws error NU1202 with dotnet sdk 8.0.300 for some centrally managed packages

### ISSUE THREAD

**Issue by AR-May** [NuGet/Home#13453]
---
**Issue moved from dotnet/msbuild#10157**
- Please respond to @tomasfabian.

---

_From @tomasfabian on Monday, May 20, 2024 9:56:59 AM_

### Issue Description

After upgrading to the latest .NET SDK 8.0.300, the build process fails when using **ManagePackageVersionsCentrally** in case of some packages such as `FluentAssertions`.

### Steps to Reproduce

Running the `dotnet restore` Demo.sln command with the configuration below fails to restore packages:

UnitTest.csproj:
```xml
<Project Sdk="MSTest.Sdk/3.3.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>

</Project>
```
Directory.Packages.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
</Project>
```

This works as expected:
```xml
<Project Sdk="MSTest.Sdk/3.3.1">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <IsPackable>false</IsPackable>
  </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="6.12.0" />
    </ItemGroup>
</Project>
```

### Expected Behavior

Running `dotnet restore` with .NET SDK 8.0.300 should work the same way as it does with .NET SDK 8.0.205.

### Actual Behavior

A much older version of the package is being used/reported instead of the referenced one:
_C:\UnitTests.csproj : error NU1202: Package FluentAssertions 1.3.0.1 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package FluentAssertions 1.3.0.1 supports: [C:\Demo.sln]_

**Comment by AR-May** [comment]
---
**Issue moved from dotnet/msbuild#10157**
- Please respond to @AR-May.

---

_From @AR-May on Tuesday, May 21, 2024 2:05:08 PM_

Team triage: it seems like it is a NuGet issue, moving it to NuGet repository.

**Comment by nkolev92** [comment]
@AR-May 

There's some breaking changes for CPM opt-in in 8.0.3xx, namely: https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.10#breaking-changes. 

In particular, you shouldn't need ManagePackageVersionsCentrally anymore. 

Now, I'm not sure I see how that breaking change could lead to the behavior you're seeing. 

I'm not able to repro it with: https://github.com/nkolev92/13453

```log
E:\NuGet\temp\13453 [main ≡]> dotnet restore
  Determining projects to restore...
  Restored E:\NuGet\temp\13453\13453.csproj (in 212 ms).
E:\NuGet\temp\13453 [main ≡]> dotnet --version
8.0.300
E:\NuGet\temp\13453 [main ≡]>
```

Can you help me understand how my repro is different from yours?

**Comment by brettfo** [comment]
@nkolev92 I was able to repro this.  I created a repo at https://github.com/brettfo/13453 with all of the relevant information in the README, but the short version is that a `Directory.Build.props` further up the tree sets the `ManagePackageVersionsCentrally` property to `false` and in the `/src` directory, `Directory.Packages.props` used to be able to override this property in the 205 SDK, but it doesn't in the 300 SDK.  It's a regression between the versions, but it's certainly possible that it only "worked" in 205 on accident.

**Comment by nkolev92** [comment]
I think only Directory.Packages.props is supposed to be imported. 
Very likely that it was accidentally working.

cc @jeffkl

**Comment by tomasfabian** [comment]
In my case, I disabled `ManagePackageVersionsCentrally` in the root **Directory.Build.Props** file for the entire solution. This detail wasn't included in my original issue that was transferred here:
```xml
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    </PropertyGroup>
</Project>
```
and enabled it only for individual test projects:
```xml
<Project Sdk="MSTest.Sdk/3.3.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" />
    </ItemGroup>

</Project>
```

If it is no longer possible to configure `ManagePackageVersionsCentrally` in the Directory.Build.Props file in the root folder, I can move the Directory.Packages.Props file to the UnitTests subfolder.

**Comment by jeffkl** [comment]
It seems that this has to do with MSBuild import order.  Any `Directory.Build.props` next to the project or any parent folder is imported first.  A little after that, the `Directory.Packages.props` is imported but only if `ManagePackageVersionsCentrally` is set to `true`.  Since you're disabling central package management (CPM) in `Directory.Build.props`, its too late to enable it in a project since the `Directory.Packages.props` was already not imported.

Its rather usual to use central package management but only for a select set of projects.  Like you suggested, you could move `Directory.Packages.props` to a sub-directory with only those projects in it.  Alternatively, you can create a `Directory.Build.props` next to each project that wants to use CPM with `ManagePackageVersionsCentrally=true`:

Project-level `Directory.Build.props`:
```xml
<Project>
  <PropertyGroup>
        <!-- Enable CPM for the project in this directory -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Import parent Directory.Build.props which respects the ManagePackageVersionsCentrally property already being set  -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
</Project>
```
Root `Directory.Build.props`:
```xml
<Project>
  <PropertyGroup>
    <!-- Disable CPM by default unless something already enabled it -->
    <ManagePackageVersionsCentrally Condition="'$(ManagePackageVersionsCentrally)' != 'true'">false</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
```

I'm closing this issue as "by design" for now since with `Directory.Build.props` its not possible to disable CPM globally but then enable it per-project.
