### ISSUE TITLE
Azure DevOps credentials "expired" after a couple of days

### ISSUE THREAD

**Issue by RichardD2** [NuGet/Home#13468]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet nuget push

### Worked before?

6.9

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I use the command-line to publish private NuGet packages to our Azure DevOps artifacts feed, following the connection instructions on the feed.

None of my PATs expire before August.

Since the "upgrade" to v6.10, I am now told every 3-5 days that _"The plugin credential provider could not acquire credentials"_. I then have to re-run the command with the `--interactive` flag, and obtain _another_ PAT in order to publish.

### Verbose Logs

> Pushing (Package).nupkg to 'https://(org).pkgs.visualstudio.com/_packaging/(Guid)/nuget/v2/'...
>   PUT https://(org).pkgs.visualstudio.com/_packaging/(Guid)/nuget/v2/
> warn : The plugin credential provider could not acquire credentials. Authentication may require manual action. Consider re-running the command with --interactive for `dotnet`, /p:NuGetInteractive="true" for MSBuild or removing the -NonInteractive switch for `NuGet`
>   Unauthorized https://(org).pkgs.visualstudio.com/_packaging/(Guid)nuget/v2/ 1756ms
> error: Response status code does not indicate success: 401 (Unauthorized).
> 
> 
> Usage: dotnet nuget push [arguments] [options]
> ...

**Comment by martinrrm** [comment]
I'm not able to repro this in my local machine, looks like tokens are expiring. Could this be a duplicate issue https://github.com/NuGet/Home/issues/12516?

**Comment by RichardD2** [comment]
The PAT doesn't expire until August. 

This wasn't an issue prior to 6.10; with 6.9 I never saw a 401 response before the PAT expired.

**Comment by RichardD2** [comment]
I think I've found the problem. Even though I already had the Azure Artifacts Credential Provider installed, and the install script told me there was nothing to do, it was obviously out of date. I've just manually downloaded and installed [v1.1.1](https://github.com/microsoft/artifacts-credprovider/releases/tag/v1.1.1), and the operation now works, with a slightly different log:

> [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'MSAL Silent'  
> [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.  
> ...  
> Your package was pushed.
