### ISSUE TITLE
[Bug Bash] Clicking the author info link on the right of the package name in PM UI goes to an incorrect page

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13472]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.11.0.72

### Worked before?

This is not a regression since it is a new feature.   

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Open VS and create a project through menu File->New->Project->select the “Project Type” as “C#”->search "C# ASP.NET Web Application (.NET Framework)". 

2. Click “C# ASP.NET Web Application (.NET Framework)” in the list and click “Next” button. 

3. Type project name in “Project name” text box, select “.NET Framework 4.8.1” in the “Framework” dropdown box and click “Create” button. 

4. 4. Select “MVC” on the left, choose “Windows” in the “Authentication” dropdown list, check “MVC” & “Web API” under “Add folders & core References” and click “Create” button. 

5. Right-click the project in Solution Explorer and select “Manage NuGet Packages…” menu item to open PM UI. 

6. Click “Installed” tab and select the package “Antlr”. 

7. Click the author info “Terence Parr” link on the right of the package name. 
#### Expected:    

Clicking the author info link should go to the correct page which is about the author’s info. 

#### Actual: 

The link goes to a “Error 404 – Page Not Found” page as below: 
![image](https://github.com/NuGet/Home/assets/84695155/541be03e-02b8-4fd3-a250-47079afd63e1)
#### Notes:     

1. The repro rate is 100%. 
2. The issue doesn’t repro on the "Browse" tab of PM UI and the author info link of the "Browse" tab and the "Installed" tab is different for the same package as below:
![Unbenannt1](https://github.com/NuGet/Home/assets/84695155/7b18d99e-818c-4e4f-b5af-67bc48478110)

**Comment by martinrrm** [comment]
@donnie-msft looks like the author account doesn't exist, I had the impression that if the account no longer exists it would be null. https://api.nuget.org/v3/registration5-semver1/antlr/index.json.

**Comment by donnie-msft** [comment]
Installed tab doesn't load Owner. So, I need to make sure it doesn't try to hyperlink author names.
There is pending work to support Installed tab, but it keeps getting pushed out for other work. I should be able to disable the links entirely on Installed tab even when the source supports owner.

**Comment by nkolev92** [comment]
Team Triage: We agree with @donnie-msft that we shouldn't have a link since the author value is not validated.
