### ISSUE TITLE
"nuget.exe restore [solutiondir]" doesn't restore solution-level packages

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1347]
Very similar to the configuration described in #1281, I have a solutiondir.nuget\packages.config file. 

Nuget.exe version  3.2.0.10488 does not restore packages from that file when supplied with the path to the solution folder. This is a breaking change from nuget.exe 2.8. 

Is this intentional? Can it be corrected?

**Comment by yishaigalatzer** [comment]
Solution level packages have been deprecated in visual studio 2015, but we should probably support it in nuget.exe
