### ISSUE TITLE
Absolute repositoryPath turns into relative reference HintPath

### ISSUE THREAD

**Issue by MortenHelgesen** [NuGet/Home#1348]
In NuGet.Config we have

  `<config>`
`<add key="repositoryPath" value="c:\Lib\packages" />`
`</config>`

When installing a package to a project using either the Package Manager or the Package Manager Console from within Visual Studio the resulting HintPath in the project's reference section (from a .csproj) becomes

`<HintPath>..\..\..\..\..\..\Lib\packages\WpfResourcesLib.1.0.0.16\lib\net46\WpfResourcesLib.dll</HintPath>`

Not being able to use an absolute path as a repositoryPath without it being converted to  a relative path is a problem for us since not all developers have the same source code mappings. We also run into issues during branching.

What we want is the possibility of using an absolute path as repositoryPath and for NuGet to use this absolute path when generating the reference HintPath in the the .csproj, i.e.

`<HintPath>c:\Lib\packages\WpfResourcesLib.1.0.0.16\lib\net46\WpfResourcesLib.dll</HintPath>`

for the example above instead of the relative path.

If we have the repositoryPath point to a folder on another disk (e.g. d:\Lib\packages) the HintPath becomes absolute.

Is this a bug? Is there a way we can force NuGet to use absolute paths in the project's HintPath?

**Comment by yishaigalatzer** [comment]
There is no good way to do that, since NuGet doesn't actually add the hint path, it is visual studio add reference that does it.

You should use relative paths in your nuget.config if you want to use projects across machines/users.

**Comment by yishaigalatzer** [comment]
I'm closing, since there is not much we can do about this, but feel free to continue the discussion on this thread, we might be able to find a better workaround.

One of the reasons we introduced `project.json` is to avoid stamping hintpaths into the users project, and that should work for you going forward as project.json support is added for more project types.

**Comment by MortenHelgesen** [comment]
Thanks for you reply!

When can we expect project.json support for C++, C# and C++/CLI projects?

With Regards
Morten Helgesen
Research and development
Kongsberg Maritime
Horten

Direct tel  +47 33 03 42 93
Office        +47 33 03 40 00
Fax            +47 33 04 44 24

http://www.km.kongsberg.com

**Comment by yishaigalatzer** [comment]
We don't have a firm schedule for project.json support in C++, but we are discussing it with the C++ team. Will announce once we have a schedule.

For C# projects, you can basically try to use it today, it is not officially supported but it does work in most scenarios (that's how we build nuget itself and Roslyn is getting built this way as well (see https://github.com/dotnet/roslyn/tree/master/src/EditorFeatures/CSharp)

**Comment by Halofreak1990** [comment]
What about changing HintPath to be based off $(PackagesDir) ?
