### ISSUE TITLE
There is no doc for NU1702

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#13487]
There is for `NU1701` and there is for `NU1703`.

But not for `NU1702` which reads as following:

```
Warning
NU1702
ProjectReference 'MyProject.csproj' was resolved using '.NETFramework,Version=v4.6.2' instead of the project target framework '.NETCoreApp,Version=v3.1'. This project may not be fully compatible with your project.	
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Warning NU1701](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by abatishchev** [comment]
@nkolev92 do you know who can help and triage the issue?

**Comment by nkolev92** [comment]
Triaged, thanks for the tag.

**Comment by abatishchev** [comment]
@nkolev92 I see last time a P1 issues was addressed in February and another is still open. Do you know if I expect this one to be addressed any time soon, or it went nowhere?

**Comment by nkolev92** [comment]
Hey @abatishchev, 

I can't provide an ETA right now, but we're trying to improve our cadence on solving issues such as this. cc @JonDouglas
