### ISSUE TITLE
Updating multiple projects in solution needs to use same repository

### ISSUE THREAD

**Issue by stavnskov** [NuGet/Home#1349]
Updating a package in multiple projects of a solution works differently in Nuget 3 than the version 2. In v3 It is not possible to update a package to a new version if the old versions is not present in the same repository. Even though the original source is available in the drop down. On the same solution this is possible in v2.

We use a structured approach to Nuget repos, so sometimes we update a package to a new version from a local feed (e.g. an alpha version) that was previously from a networked feed (e.g. a more stable version).

What you can do to workaround the issue is to update one project at a time or uninstall the old package from the projects and then reinstall the new projects.

**Comment by yishaigalatzer** [comment]
The requirement is to have the package available, so uninstall operations can happen. 

I believe all you need to do is restore the packages first, and it _should_ work, unless I'm not understanding the scenario.

Could you please verify?

**Comment by stavnskov** [comment]
Let me try to clarify.

The old package IS available in one of the enabled feeds, though not in the selected feed where the new version is.

The new version is available when filtering for upgrades on the left. But on the right I cannot select Update action.

**Comment by yishaigalatzer** [comment]
We should fix it.

But can you clarify the scenario further is the current version of the package restore?

Possible workaround: Use update-package command from powershell

**Comment by stavnskov** [comment]
Yes I know the workaround thank you. It also works if I copy the old version into the selected feed where the new version is.

Is there a specific version for package restore? In Extensions and Updates it says 3.1.60724.766 in Help About it reads 3.0.0

**Comment by yishaigalatzer** [comment]
We are updating to 3.2 shortly - 3.2RC is out (and it will show 3.2 both in extensions and updates and everywhere else). Here is the link to 3.2 RC. http://nugetdist.blob.core.windows.net/artifacts/win-x86-commandline/v3.2.0-rc/nuget.exe

**Comment by LeroyK** [comment]
This may be the same issue as #1370. Does the scenario I have described there match yours?

**Comment by stavnskov** [comment]
It sounds like the same issue as #1370, which seems to be more precisely described

**Comment by yishaigalatzer** [comment]
Closing as duplicate, but we will verify as part of fixing #1370. Also note that we are planning on enabling all sources again in 3.3
