### ISSUE TITLE
Dependencies not being respected

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#1350]
Using VS 2015 / NuGet Package Explorer 3.1.60724.766

I am installed Catel.Core to a .NET 4.5 project like this:

MyProject (NET45) => MyPackage (NET45) => Catel.Core (NET45, but has lots of other packages as well). Here is the nuspec for Catel.Core:

```
    <dependencies>
      <group targetFramework=".NETFramework4.0">
        <dependency id="Microsoft.Bcl" version="1.1.10" />
        <dependency id="Microsoft.Bcl.Async" version="1.0.168" />
        <dependency id="Microsoft.Bcl.Build" version="1.0.21" />
      </group>
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework="Silverlight5.0">
        <dependency id="Microsoft.Bcl" version="1.1.10" />
        <dependency id="Microsoft.Bcl.Async" version="1.0.168" />
        <dependency id="Microsoft.Bcl.Build" version="1.0.21" />
      </group>
    </dependencies>
```

Here is the nuspec for the intermediate package:

```
    <dependencies>
      <dependency id="Catel.Core" version="4.2.0" />
    </dependencies>
```

Then when installing to the final project, it says I need to install Microsft.Bcl as well (what normally only should happen to NET 4.0 projects).

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik is this an msbuild error you see (only guessing here) ?

Can you please verify if the dlls and packages you expected are installed in the project and the only issue is the warning?

**Comment by GeertvanHorrik** [comment]
It's something that NuGet package manager shows when installing the intermediate package (in the confirm dialog). They are all installed, even the Microsoft.Bcl stuff, but I don't expect it to be installed.

**Comment by emgarten** [comment]
@GeertvanHorrik does this happen when you install Catel.Core directly? What type of project is this and can you provide repro steps for this using packages currently on nuget.org?

**Comment by GeertvanHorrik** [comment]
No, it does not happen when I install Catel directly. One example is Orchestra.Core (all open source).

**Comment by emgarten** [comment]
I'm not reproing this using a net45 console app. Installing Orchestra.Core gives me:

![image](https://cloud.githubusercontent.com/assets/6381138/9755948/1f856ea6-568b-11e5-947d-4cf757c9becb.png)

Would you try the 3.2.0-RC VSIX and see if it resolves the issue? http://blog.nuget.org/20150902/nuget-3.2RC.html

**Comment by GeertvanHorrik** [comment]
I can't reproduce it there either. Let me try on the original sln, will get back to you.

**Comment by GeertvanHorrik** [comment]
Pfew, can reproduce it. Thought I was going crazy, but it looks like it's related to MyGet (v3 feed).

![image](https://cloud.githubusercontent.com/assets/1246444/9756725/a267b0da-56dc-11e5-909b-7bc4284c1edd.png)

Will contact the MyGet team.

**Comment by maartenba** [comment]
We've received @GeertvanHorrik's request, and we've inspected the registration for `Catel.Core`. We have identified a bug in our dependency parser, which has been fixed and eployed.

@GeertvanHorrik can you confirm this now works as expected?

**Comment by GeertvanHorrik** [comment]
Fix works. Thanks!
