### ISSUE TITLE
Building with `net8.0-ios` is picking `net8.0` from NuGet package instead of `net8.0-ios17.0`

### ISSUE THREAD

**Issue by Youssef1313** [NuGet/Home#13510]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK 8.0.300

### Impact

It's more difficult to complete my work

### Repro Steps & Context

[themes-build-ios-winui.zip](https://github.com/user-attachments/files/15551150/themes-build-ios-winui.zip)

See target `ResolvePackageAssets` for the build of `Uno.Themes.WinUI.Samples.Mobile.csproj`. Specifically, the output item `RuntimeCopyLocalItems` and more specifically the Uno.UI.dll path. It's `/Users/runner/.nuget/packages/uno.winui/5.3.0-dev.1669/lib/net8.0/Uno.UI.dll`.

This version of the Uno package has `net8.0-ios17.0`. But `net8.0` was favored over `net8.0-ios17.0`, which doesn't feel correct.

**Comment by jeffkl** [comment]
Team Triage: @Nigusu-Allehu can you please attempt to reproduce the problem and add details you find.

**Comment by nkolev92** [comment]
If you look at the assets file, the IOS platform set is 15.4, net8.0-ios15.4. 

PlatformItemGroups.props seems to set it 15.4. 
net8.0-ios15.4 can't consume net8.0-ios17.0.

The default SDK provided version would normally be 17.2, if I'm reading it correctly. 

```xml
_DefaultTargetPlatformVersion>17.2</_DefaultTargetPlatformVersion
```

All that being said, I think this is expected and not a bug. 

lmk if you have any questions @Youssef1313
