### ISSUE TITLE
'why' and 'config' command does not show up in 'dotnet nuget --help' output

### ISSUE THREAD

**Issue by advay26** [NuGet/Home#13517]
### NuGet Product Used

dotnet.exe, NuGet SDK

### Product Version

.NET 9.0.100 Preview 6

### Worked before?

No

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

1. Run 'dotnet nuget -h'
2. See commands listed in help output: the 'why' command is missing

We are in the process of migrating our CLI commands from '_Microsoft.Extensions.CommandLineUtils.CommandLineApplication_' to '_System.Commandline.CliCommand_', and this has meant that we have a split in our command parsing here (migrated commands): https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs#L83-L85, and here (pre-migration commands): https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Program.cs#L257-L276.

All commands registered with the old code path (pre-migration) show up correctly in the help output, but migrated `_dotnet nuget *_' commands (_why_/_config_) are not being registered correctly. They still run correctly. They just do not show up in 'dotnet nuget --help' output.

### Verbose Logs

```shell
> dotnet nuget -h
```

See also: https://github.com/dotnet/sdk/issues/42084

**Comment by donnie-msft** [comment]
I also can't find docs for `dotnet nuget config`, am I just not finding them?

**Comment by kartheekp-ms** [comment]
> I also can't find docs for `dotnet nuget config`, am I just not finding them?

There are docs for all [config commands](https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-config-spec.md) but they are not part of dotnet nuget commands tree.
https://learn.microsoft.com/dotnet/core/tools/dotnet-nuget-config-get
https://learn.microsoft.com/dotnet/core/tools/dotnet-nuget-config-set
https://learn.microsoft.com/dotnet/core/tools/dotnet-nuget-config-paths

**Comment by donnie-msft** [comment]
> There are docs for all [config commands](https://github.com/NuGet/Home/blob/dev/accepted/2022/dotnet-nuget-config-spec.md) but they are not part of dotnet nuget commands tree.

This seems wrong to me. Is there a reason they shouldn't be in the tree?

**Comment by martinrrm** [comment]
Looks like they were added incorrectly to the TOC https://github.com/dotnet/docs/pull/41604/files, I'll fix this

**Comment by advay26** [comment]
@martinrrm The config commands should also probably be added to the `index.md` file: https://github.com/dotnet/docs/blob/main/docs/core/tools/index.md#nuget-commands
