### ISSUE TITLE
Version conflict with Nuget client 3.2-rc

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#1352]
I'm playing around with 3.2 rc version of nuget.exe and trying to run the following restore command.

`.\nuget.exe restore project.json -source https://myget.org/F/dotnet-core`

project.json contains the following

```
{
  "dependencies": {
    "Microsoft.NETCore.Console": "1.0.0-beta-*",
  },
  "frameworks": {
    "dnxcore": {},
  }
}
```

I get a ton of similar version conflicts but I will only include on here to see if someone can help me understand it.

```
Version conflict detected for System.Runtime.
 nugetv3.2 (>= 1.0.0) -> Microsoft.NETCore.Console (>= 1.0.0-beta-) -> Microsoft.NETCore (>= 5.0.1-beta-23308) -> System.Runtime (>= 4.0.21-beta-23308)
 nugetv3.2 (>= 1.0.0) -> Microsoft.NETCore.Console (>= 1.0.0-beta-) -> System.Security.Cryptography.Encoding (>= 4.0.0-beta-23308) -> System.Runtime (>= 4.0.20).
```

Can someone help me understand why (>=4.0.20.0) and (>=4.0.21-beta-23308) are not compatible? Is it because of the prerelease and if so what can I do in my project.json or the restore command to make  it consider prerelease?

**Comment by yishaigalatzer** [comment]
Pre-release has to match the same version that was asked for. In fact we are going to tighten it further. You can override it by making the required package a top level package in project.json

**Comment by weshaggard** [comment]
Interesting so that seems to imply that we don't have any good support for prerelease meta-packages like "Microsoft.NETCore.Console" or "Microsoft.NETCore.UniversalWindowsPlatform" unless we only have direct dependencies in the meta-package. Is that your understanding as well? If so that seems to put a big constraint on the meta-packages.

**Comment by yishaigalatzer** [comment]
Not sure I follow. The constraint is to not bump to pre-releases. That should never happen anyways unless you delete packages from the feed.

Sent from my Windows Phone

**Comment by weshaggard** [comment]
The issue I'm hitting right now is I'm working on a prerelease of "Microsoft.NetCore.Console" meta-package which contains a nesting of other meta-packages and some direct references to packages. A large set of these packages are prerelease but not all of them and some of them also have dependencies on prerelease packages. In this scenario I would like to have the prerelease version of the package be the chosen one without needing to directly reference them in my project.json file which defeats the purpose of a meta-package. 

It seems as though we are in a position that everything referenced in my meta-package closure must refer to the exact same prerelease package versions or only depend on stable versions. That seems like it will be trouble for us.

**Comment by emgarten** [comment]
The fix for this didn't make it into the 3.2.0 RC build, but it is fixed for RTM. 

It looks like the same issue as: https://github.com/NuGet/Home/issues/1304

**Comment by yishaigalatzer** [comment]
Wes - can you try your scenario with the latest build?

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
We believe this is indeed a dup of #1304, we can re-open if we get other feedback.

**Comment by weshaggard** [comment]
Yes the latest nuget seems to allow my restore to succeed. I plan to follow-up later to ensure that all the correct packages are restored.
