### ISSUE TITLE
[Bug Bash] The searching mode “packageid:[PackageName]” should also be supported in the filter of ‘Installed’/’Updates’/’Consolidate’ tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13543]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Dev\6.11.0.96

### Worked before?

It’s not a regression since it reproes on D16.11\34601.136 with implicit NuGet Client 5.11.6.4.

### Impact

It bothers me. A fix would be nice

#### Repro Steps: 
1.	Create a solution with two C# Console App (.NET 8.0) projects (called Project1 and Project2), right-click the solution in the Solution Explorer window and select the menu item “Manage NuGet Packages for Solution…”..
2.	Go to ‘Browse’ tab, install the package **‘jQuery 3.5.0’** into **Project1** and install the package **‘jQuery 3.6.0’** into **Project2**.
3.	In the right panel, select the ‘3.5.0’ in the drop-down list of ‘Version’ box and click the alternate package link ‘jQuery>=3.5.0.1’.
4.	**Don’t delete the searching string “packageid:[PackageName]”** in the filter and click the ‘Installed’/’Updates’/’Consolidate’ tab.

#### Expected Results:
The searching mode “packageid:[PackageName]” should also be supported in the filter of ‘Installed’/’Updates’/’Consolidate’ tab. There should be the package ‘jQuery’ listed in ‘Installed’/’Updates’/’Consolidate’ tab in this instance.

#### Actual Result:
The searching mode “packageid:[PackageName]” is not supported in the filter of ‘Installed’/’Updates’/’Consolidate’ tab as below screenshot. It doesn’t make sense because the searching mode “packageid:[PackageName]” is supported in ‘Browse’ tab.
![image](https://github.com/NuGet/Home/assets/20632625/0c41df51-5659-4755-b41b-dc223ba2a2ec)

#### Notes:
Repro Rate: 100%

**Comment by donnie-msft** [comment]
Worth considering this DCR as part of https://github.com/NuGet/Home/pull/12704

**Comment by jeffkl** [comment]
Team Triage:  Unfortunately making this work is very involved.  Only certain endpoints support such filtering and so the feature would need to be enabled only if the feed supported it.
