### ISSUE TITLE
Option to ignore unsupported project types in command-line nuget and azure pipelines nuget

### ISSUE THREAD

**Issue by Pxtl** [NuGet/Home#13549]
### NuGet Product(s) Involved

NuGet.exe

### The Elevator Pitch

Edit: I just realized that while I discovered the issue on the azure pipelines server, it's much more severe there and is pretty mild on nuget.exe (which I was using to debug the problem, which is why I focused on nuget.exe).

A solution file may contain project types that are not supported by nuget.exe.  For example, I'm facing this with a .modelproj - nuget chokes on this file within the solution.

If I attempt to nuget restore with msbuild.exe, it properly recognizes that it can't work with that .modelproj and moves on.

This same issue exists in Azure Pipelines nuget restore as well, since I think that uses nuget.exe under the hood.

### Additional Context and Details

Edit-Followup:

Nuget.exe *does* continue undaunted with the modelproj, it just throws ugly red text and error messages.  It looks like it finishes the restore and sets an exit code of 0.

The real problem is in the azure pipelines task, where we get a full stracktrace:

```
Error parsing solution file at C:\AgentPools\Default\Agent2\_work\271\s\<solutionfilename>.sln: Exception has been thrown by the target of an invocation.
NuGet Version: 4.1.0.2450
   at NuGet.CommandLine.MsBuildUtility.GetAllProjectFileNamesWithMsBuild(String solutionFile, String msbuildPath)
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__30.MoveNext()

```

This is mostly a convenience thing.  It'd be nice to be able to just do `nuget restore <solutionfile>` and not have to worry about which containing projects it can handle.

Nuget.exe beahviors:

This is the error I get:

```
Jun14 14:44:10 C:\tfs\<SolutionDir> [main ≡]
> nuget restore .\<SolutionFile>
MSBuild auto-detection: using msbuild version '17.10.4.21802' from 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin'.
C:\tfs\<SolutionDir>\<ProjectName>\<ProjectName>.modelproj(27,11): error MSB4226: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VisualStudio\v17.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets" was not found. Also, tried to find "ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v17.0" . These search paths are defined in "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\msbuild.exe.Config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.

WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
All packages listed in packages.config are already installed.
  CACHE https://api.nuget.org/v3/vulnerabilities/index.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.06.14.05.22.49/vulnerability.base.json
  CACHE https://api.nuget.org/v3-vulnerabilities/2024.06.14.05.22.49/2024.06.14.05.22.49/vulnerability.update.json
```

When using msbuild, this is what I get:

```
& 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe' -t:restore .\<SolutionFile>
MSBuild version 17.10.4+10fbfbf2e for .NET Framework
Build started 2024-06-14 2:39:54 PM.

Project "C:\tfs\<SolutionDirectory>\<SolutionFile>" on node 1 (Restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Mixed Platforms".
C:\tfs\<SolutionDirectory>\<ProjectDirectory>\<ProjectFile>.modelproj : warning NU1503: Skipping restore for project 'C:\tfs\<SolutionDirectory>\<ProjectDirectory>
ing\<ProjectFile>.modelproj'. The project file may be invalid or missing targets required for restore. [C:\tfs\<SolutionDirectory>\<SolutionFile>]
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Restore:
  X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
  X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
  Nothing to do. None of the projects specified contain packages to restore.
Done Building Project "C:\tfs\<SolutionDirectory>\<SolutionFile>" (Restore target(s)).


Build succeeded.

"C:\tfs\<SolutionDirectory>\<SolutionFile>" (Restore target) (1) ->
(_FilterRestoreGraphProjectInputItems target) ->
  C:\tfs\<SolutionDirectory>\<ProjectDirectory>\<ProjectFile>.modelproj : warning NU1503: Skipping restore for project 'C:\tfs\<SolutionDirectory>\<ProjectDirectory>\<ProjectFile>.modelproj'. The project file may be invalid or missing targets required for restore. [C:\tfs\<SolutionDirectory>\<SolutionFile>]

    1 Warning(s)
    0 Error(s)
```

**Comment by nkolev92** [comment]
@Pxtl 

We've been moving towards tooling that contains both restore and build functionality, so nowadays, we'd recommend restoring via msbuild -t:restore and dotnet restore: https://learn.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-by-using-msbuild. 

That being said, you're using a really old version of NuGet.exe, 4.1 shipped around 2017. 
Can you try the latest version? Note that NuGet 6.* is expected to be using with Visual Studio 2022.

**Comment by baronfel** [comment]
Note that if you want to do any other MSBuild you should use `msbuild /restore` instead of `msbuild /t:restore` - if you invoke the Restore target directly along with other targets (for example `msbuild /t:restore /t:build` any props/targets from your NuGet packages will not be loaded for the `Build` target, whereas with `msbuild /restore /t:build` they will be.

**Comment by Pxtl** [comment]
@nkolev92

Oh wow, somehow AzDO pipeline build-agent server is running an old version of nuget.exe even though I have 6.10.0.107 installed on it.  Thanks!  I'll investigate that.  I installed `nuget.exe` via Chocolatey, which doesn't put it in `program files` but rather installs it in %programdata% and then creates a bunch of shim binders to the exes, maybe that's confusing the AzDO Pipeline agent to ignore the new version and hard-binding to the old one.

Anyhow, the server isn't calling nuget.exe manually, it's using `NuGetCommand@2`.  

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-command-v2?view=azure-pipelines

We're running Azure Devops Server 2022.0.1 and the build-agent is running agent version v3.225.0 which is from last year... but the server was upgraded from an older version of AzDO server/agent.... either the build-agent bundles this old version of Nuget.exe, or the upgrade process is failing to update its private install of nuget.exe.

But that does mean we can workaround it by replacing the `NuGetCommand@2` with a simple script/powershell task.  But it's still disappointing that Azure Pipelines Agent's Nuget is that old out-of-the-box.

edit: I'd accidentally grabbed the version # of chocolatey itself first, not the version of nuget.exe installed by chocolatey

edit2: looks like AzDO Pipelines has a "NugetToolInstaller@0" command I'm supposed to use to tell it to automatically update its preferred nuget.exe version.  I'll try that and see if it fixes my problem.

**Comment by nkolev92** [comment]
Sounds good. 

Let us know how it goes.

**Comment by Pxtl** [comment]
Good (ish) news:

It succeeds!

But while logging some ugly complaints.  

```
WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
```

It logs error-text, has a stack-trace of a "NuGet.CommandLine.ExitCodeException" exception, complains it can't find "MSBuild\Microsoft\VisualStudio\v17.0\ArchitectureTools\Microsoft.VisualStudio.TeamArchitect.ModelingProject.targets"

but still moves on and nuget restores everything else sucessfully, without so much as logging a warning in Azure DevOps - the complaints are just text in the raw stdout log output.

We can probably just turn off `verbosity: detailed` and politely ignore the situation.

**Comment by nkolev92** [comment]
Glad that worked. 

If possible, I'd recommend using `msbuild -t:restore`. 
You already need it for building, so no need to add an extra binary there :)
