### ISSUE TITLE
Updating packages in VS with TFS, doesn't correctly mark the old package folder for deletion

### ISSUE THREAD

**Issue by mostergaard** [NuGet/Home#1354]
I am using the latest VS2015 and the latest NuGet extensions for VS. I have a project in TFS (classic TFVC not Git) where packages are checked in (including binaries). When I update NuGet packages the  old package files are deleted from the packages folder, but the folder itself isn't marked for deletion in Team Explorer. This leaves an empty folder in version control under packages. It is, however, deleted from the file system, but the extension has failed to add this change to "pending changes".

In previous versions there used be horrible problems with NuGet updates in the above scenario - especially for projects with only one NuGet package installed. This is much better now, but it does suggest that the testing focus is on Git-based projects and the packages folder NOT included in source control. We are moving towards that as well, but please include these scenarios in your tests - and make sure to also include a project with only one NuGet package ;-) I'm sure we're not the only one's doing it this way.

**Comment by yishaigalatzer** [comment]
Hey @mostergaard, thanks for the report. We should probably add this scenario to our test matrix.

One tiny comment - It will be super helpful to include the actual version of the NuGet extension, the latest keeps changing and we currently have both 3.1.1 RTM and 3.2-RC out there.

**Comment by mostergaard** [comment]
Hey @yishaigalatzer. Thanks for the reponse. The NuGet extension I've seen the bug with is 3.1.60724.766. I will remember to include that in future reports :-)

**Comment by yishaigalatzer** [comment]
Awesome. Just as FYI we did release a 3.2-RC that addresses a few TFS issues (yes we care :) )

http://blog.nuget.org/20150902/nuget-3.2RC.html

**Comment by zhili1208** [comment]
just verified this issue with latest 3.2, it's fixed there. close this bug.

**Comment by mostergaard** [comment]
Great - thanks. Will look out for the release then :-)

**Comment by mostergaard** [comment]
This issue seems to have resurfaced with the latest VS and NuGet. I'm running VS 14.0.24720 and NuGet package manager extension version 3.3.0.167.

**Comment by yishaigalatzer** [comment]
Thanks @mostergaard will take a look

**Comment by mostergaard** [comment]
Maybe I should write this in a different issue, but I see now that the old bug, that seems to keep re-appearing once in a while, with projects with only one NuGet package, has come back. The problem is with projects that only have ONE NuGet package on it. If you then update this, the packages.config file get's marked for deletion by the TFVC integration eventhough the file is still on disk.

We use NuGet a lot internally for sharing common utility assemblies, and for us it is not uncommon to have projects that only point to one NuGet package. And if you don't notice that the package.config get's marked for deletion when checking in to TFVC, the build will fail. This has been fixed a number of times, but seem to keep coming back. So I would suggest that you add this scenario to your tests.

**Comment by zhili1208** [comment]
verified this with 3.3. it repros with powershell and UI

**Comment by zhili1208** [comment]
Looks like this issue is always there, we never really fixed it.  we tested it by checking pending changes, but if you don't check in the project, everything looks right in pending changes.
