### ISSUE TITLE
PERF: GetPackageInfo allocates by unnecessarily calling GetNupkgMetadataPath

### ISSUE THREAD

**Issue by ToddGrun** [NuGet/Home#13556]
### NuGet Product Used

Other/NA

### Product Version

VS17

### Worked before?

N/A

### Impact

Other

### Repro Steps & Context

See https://github.com/NuGet/NuGet.Client/pull/5859 for more details

Repro:

Open VS
Wait for things to calm down
Start profiling
Open Roslyn.sln, open a file it none opened
Wait for things to calm down
Stop profiling
Allocations during FallbackPackagePathResolver.GetPackageInfo:

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/5859. 

It didn't autoclose cause it wasn't on the same line as the fixes statement.
