### ISSUE TITLE
Package v3 downloads time out at 1:40min due to DataClient/HttpClient default setting

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1355]
Large downloads currently time out at 1 minute 40 seconds, since DataClient uses the default HttpClient timeout.

**Comment by zarenner** [comment]
See NuGet/NuGet3#128 and NuGet/NuGet.PackageManagement#98 for proposed changes to allow configurable timeouts.

**Comment by emgarten** [comment]
Thanks for reporting this. This will need to be fixed at a lower level so that it works for the VSIX also.

**Comment by yishaigalatzer** [comment]
Zach - Are you saying you want a longer timeout?

The best way to deal with it is to pass the flag that says don't buffer the response ResponseHeadersRead - https://msdn.microsoft.com/en-us/library/system.net.http.httpcompletionoption(v=VS.118).aspx

At that point you can make the default timeout a lot shorter, at that point you need to manage your own timeouts, and flag the cancellationtoken. This should be verified on 4.5 -> 4.5.1.

In 4.5 this mind needs some more thought on how to abandon the task if the server stops responding

**Comment by zarenner** [comment]
An update on this:
1. There is no bug in packages.config based restore, as far as I can tell in latest dev.  It uses DownloadResourceV3, which uses GetStreamAsync, which uses HttpCompletionOptions.ResponseHeadersRead.  Some confusion here on my side was that fiddler was buffering my responses and therefore never returning headers.
2. In older versions of nuget.exe when the max degree of parallelism was unbounded, this was causing requests to time out (with packages of any size), since the timeout starts when SendAsync is called, not (later) when the request actually starts (which is limited by ServicePoint.DefaultConnectionLimit).  This has been fixed for a while I believe.
3. **There IS still a bug in project.json based restore**, which doesn't use DownloadResourceV3, and its client doesn't use HttpCompletionOptions.ResponseHeadersRead.  It appears to time out at 100 seconds and try a total of 3 times with a message similar to below:
   Failed to download package from '[package download url]'.
   A task was canceled.
   Failed to download package from '[package download url]'.
   A task was canceled.
   Failed to download package from '[package download url]'.
   A task was canceled.
   Value cannot be null.
   Parameter name: stream

**Comment by yishaigalatzer** [comment]
@zarenner do you see similar issues with DNU?

CC // @davidfowl

**Comment by zarenner** [comment]
@yishaigalatzer I don't use DNU so I'm not sure, sorry.

**Comment by yishaigalatzer** [comment]
@zarenner what is the status of this?

**Comment by zarenner** [comment]
I haven't checked to see if any recent changes may have fixed this (#3 above), but I assume it's still active.  Unfortunately I don't think I have any bandwidth right now to look into this further.

**Comment by emgarten** [comment]
This has been fixed, project.json restore will now use HttpCompletionOptions.ResponseHeadersRead

NuGet/NuGet.Client@36fb77d875bb8249d6dba70105fea353318a03da

**Comment by emgarten** [comment]
The change is available in 3.2.1-rc nuget.exe
