### ISSUE TITLE
"Static graph-based restore failed with exit code 1 but did not log an error." failure in dotnet/runtime repo

### ISSUE THREAD

**Issue by jkotas** [NuGet/Home#13551]
### NuGet Product Used

NuGet.exe

### Product Version

.NET SDK 9.0.100-preview.5.24307.3

### Impact

It's more difficult to complete my work

### Repro Steps & Context

This is intermittent build error encountered by dotnet/runtime repo build. https://github.com/dotnet/runtime/issues/103526 is going to have statics on how often it occurs.

### Verbose Logs

```shell
Log https://dev.azure.com/dnceng-public/public/_build/results?buildId=709057&view=logs&j=bdec34cc-8c67-558e-657b-d36a4105119f&t=a678ac1d-afa2-555a-c9f2-128b541774a9&l=605:

...
Restored D:\a\_work\1\s\src\libraries\shims\stubs\System.IO.Packaging.csproj (in 0.8 ms).
Failed to restore D:\a\_work\1\s\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable.csproj (in 271 ms).
Restored D:\a\_work\1\s\src\libraries\shims\stubs\System.Diagnostics.PerformanceCounter.csproj (in 0.8 ms).
...
Restored D:\a\_work\1\s\src\libraries\sfx-gen.proj (in 0.6 ms).
2D:\a\_work\1\s\.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets(19,5): error : Static graph-based restore failed with exit code '1' but did not log an error. Please file an issue at https://github.com/NuGet/Home. [D:\a\_work\1\s\Build.proj]
```
```

**Comment by ViktorHofer** [comment]
This is probably similar or the same as https://github.com/NuGet/Home/issues/13545 but just with normal (non-static graph based) restore.

**Comment by nkolev92** [comment]
Consolidating to a single investigation: https://github.com/NuGet/Home/issues/13545. 

The root cause is the same.
