### ISSUE TITLE
VS 17.10 - Error building projects with CPM explicitly enabled if ManagePackageVersionsCentrally is set to false in Directory.Build.props

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#13560]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-1710---Cant-enable-CPM-on-individua/10683768)._

---
\[severity:It’s more difficult to complete my work\] \[regression\] \[worked-in:17.9\]  
If CPM is disabled globally via `<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>` in the `Directory.Build.props` file, a “Failed to restore” error is thrown when building a project which has CPM explicitly enabled by setting `ManagePackageVersionsCentrally` to `true` in the .csproj.

I’m guessing this may have been introduced with the change to enable CPM whenever there is a `Directory.Packages.props` file present in the root directory ([https://github.com/NuGet/Home/issues/11834](https://github.com/NuGet/Home/issues/11834)).

### To reproduce:

Pre-req: You have both `Directory.Build.props` and `Directory.Packages.props` files in the root directory of the repository.

1.  Inside of `Directory.Build.props` set `<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>` to disable CPM by default for all projects.
2.  Inside a .csproj file within your repository, set `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` to enable CPM for that individual project.

**Expected:**
CPM enabled for projects which have `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` explicitly set. 

**Actual:**
“Failed to restore” errors when building projects which have `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` explicitly set. 
e.g.

```  
Failed to restore C:\TestCpm\WithCpm\WithCpm.csproj (in 6 ms).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.<GetProjectFileDependencySet>g__IndexOfWhiteSpace|6_1(String s)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.LockFileExtensions.GetProjectFileDependencySet(LockFile lockFile, String frameworkAlias)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<WritePackageDependenciesDesignTime>g__GetPackageDependencies|59_0()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WritePackageDependenciesDesignTime()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroup(Action writeItems)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroups()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.Write()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
  
```

Have also seen a slightly different stack trace:

```  
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ProjectContext.<>c__DisplayClass31_0.<GetTopLevelDependencies>b__3(String projectFileDependency)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.ComputePackageExclusions()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
  
```

---
#### Feedback Bot on 6/16/2024, 11:48 PM: 

(private comment, text removed)
#### Jason Brooks on 6/17/2024, 07:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Here's the repro indicated: [CPM.zip](https://github.com/user-attachments/files/15892620/CPM.zip)

Note that the reverse works. 

ie, disabling selectively. (Just putting ManagePackageVersionsCentrally to false in the projects you don't want).

**Comment by thomaskilgus** [comment]
This is very important for us for our migration phase. This used to work in VS 17.09 (and early) via both `Directory.Packages.Props` and `Directory.Build.Props`. Furthermore, there is misleading error message if your `Directory.Packages.Props` does not include an entry for a package being used. In VS 17.09 the message was (similar to) "does not include an inclusive lower bound for package X" which is much nicer than this new thing

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	MSB4018	The "ResolvePackageAssets" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.LockFileExtensions.<GetProjectFileDependencySet>g__IndexOfWhiteSpace|6_1(String s)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetProjectFileDependencySet(LockFile lockFile, String frameworkAlias)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<WritePackageDependenciesDesignTime>g__GetPackageDependencies|59_0()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WritePackageDependenciesDesignTime()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroup(Action writeItems)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.Write()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	ConsoleApp3	C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266	
```	

A fix would be highly appreciated. Also: The docs don't say anything that you cannot disable CPM globally via `Directory.Packages.Props`. If that is truly the case now, the docs should be updated to include this as it used to work in VS 17.09.

**Comment by nkolev92** [comment]
We're tracking a docs improvement in https://github.com/NuGet/Home/issues/13477. 

> The docs don't say anything that you cannot disable CPM globally via Directory.Packages.Props

The disabling actually works through Directory.Packages.props. 

What seems broken is enabling CPM for a project in the csproj, which is a consequence of ordering.

**Comment by jeffkl** [comment]
I've determined this is an unintentional breaking change in CPM behavior.  When enable CPM automatically if `Directory.Packages.props` existed, we also opted to not import `Directory.Packages.props` if CPM was disabled. This makes it impossible for projects to enable it since `Directory.Packages.props` is imported before the project gets to declare properties.  I'm fixing this in https://github.com/NuGet/NuGet.Client/pull/5866

**Comment by thomaskilgus** [comment]
That is great news. Will this be part of any next VS patch coming soon or do we have to wait?

**Comment by jeffkl** [comment]
> That is great news. Will this be part of any next VS patch coming soon or do we have to wait?

I'm not sure yet if we'll get permission to service older releases.  Stay tuned...

**Comment by Sentri** [comment]
@jeffkl Is there a mitigation until we have a fix? My work is currently blocked unable to build. Can I revert something to an earlier version to get unblocked?

**Comment by thomaskilgus** [comment]
@jeffkl we are unable to update VS on our systems. That's kind of a blocker for us as well. I know that my company has Gold Partner Support status with Microsoft somewhere. I couldn't find the person managing that, yet. Would that help if you received such a request?

@Sentri You could downgrade to VS 17.09 or older couldn't you?

**Comment by jeffkl** [comment]
@thomaskilgus I think it depends on the pattern you're using.  If you are globally disabling CPM and then only enabling it for individual projects, it should work if you either don't set `ManagePackageVersionsCentrally` in `Directrory.Build.props` or set `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` and set `<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>` in `Directory.Packages.props`.  Then CPM is disabled unless a project enables it.

The current behavior is that CPM is enabled if `Directory.Packages.props` exists and you haven't already disabled it in `Directory.Build.props`.  So disabling it in `Directory.Packages.props` instead should work.

**Comment by thomaskilgus** [comment]
@jeffkl I tried to reproduce your suggestion(s). Here are the results for Commandline and VS restore

Config / Restore | VS restore | CLI | Correct for both? 
-------- | -------- | -------- | --------
CPM deactivated in Build.props, nothing in Packages.Props  | ❌ | ❌ | ❌
CPM activated in Build.props, nothing in Packages.Props | ✅ | ✅ | ✅
CPM deactivated in Build.props, deactivated in Packages.Props | ❌ | ❌ | ❌
CPM deactivated in Build.props, activated in Packages.Props | ❌ | ❌| ❌
CPM activated in Build.props, deactivated in Packages.Props | ✅ | ❌| ❌
CPM activated in Build.props, activated in Packages.Props | ✅ | ✅ | ✅
CPM nothing in Build.props, activated in Packages.Props | ✅ | ✅ | ✅
CPM nothing in Build.props, deactivated in Packages.Props | ✅ | ❌| ❌

Notes: 
* Everything is in VS Version 17.10.3
* CPM is always enabled in the .csproj
* CLI: `msbuild /t:restore` in Developer Command Prompt
* VS restore: right click in VS on solution -> NuGet restore
* I omitted "Directory." for both central config files
* X: some kind of error or warning. Most of the time CPM doesn't work and you receive a lower bound warning. Other times you can a null reference exception
* I restarted VS each time and executed "Clean Solution"  to ensure nothing is cached anywhere

@jeffkl so as you can see we don't have any workaround for both cases. Only global activation works. Global deactivation always breaks CLI restore. Or do you have any suggestion how to change `msbuild /t:restore` so that it works with globally deactivated CPM?

**Comment by thomaskilgus** [comment]
@jeffkl I tried your suggestion to set `<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>` in Build.Props and set `<ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>` in Packages.Props as well with `dotnet restore` and `nuget.exe restore`. They both result in a lower bound warning and disabled CPM even though it is activated in the .csproj.

**Comment by jeffkl** [comment]
Sorry I just realized that another property isn't set if you disable CPM, `CentralPackageVersionsFileImported`.  This works:

Directory.Build.props (CPM is enabled globally):
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
</Project>
```

Directory.Packages.props (CPM is disabled globally):
```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <CentralPackageVersionsFileImported>true</CentralPackageVersionsFileImported>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EnvironmentAbstractions" Version="4.0.0" />
  </ItemGroup>
</Project>
```

ClassLibrary1.csproj (CPM is enabled):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EnvironmentAbstractions" />
  </ItemGroup>
</Project>
```

ClassLibrary2 (CPM is disabled):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EnvironmentAbstractions" Version="3.0.2" />
  </ItemGroup>
</Project>
```

[Solution.zip](https://github.com/user-attachments/files/15974084/Solution.zip)

**Comment by thomaskilgus** [comment]
@jeffkl thanks! That works. We don't even need a `Directory.Build.Props`, do we? At least it works on my machine with just the `Directory.Packges.Props`

```xml
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <CentralPackageVersionsFileImported>true</CentralPackageVersionsFileImported>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="EnvironmentAbstractions" Version="4.0.0" />
  </ItemGroup>
</Project>
```

**Comment by jeffkl** [comment]
@thomaskilgus yes, `Directory.Build.props` isn't required, just make sure that its not set to `false` there otherwise `Directory.Build.props` will not be imported.
