### ISSUE TITLE
[Bug Bash] The package installation with ‘packages.config’ format is blocked after adding a non-existed feed to package source list for non-SDK project 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13565]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.11.0.108

### Worked before?

It can be repro on D16.11\34601.136 and D17.10\34902.84.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Create a C# Console App (.NET Framework) project. 

2. Open Tools->Options->NuGet Package Manager->Package Sources and add a non-existed feed (for example: https://packagesource). 

3. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI. 

4. Click the settings button (gear) on the top-right of PM UI and check the checkbox: “All format selection on first package install”. 

5. Click “Browse” tab and select the “nuget.org” from Package source drop-down list. 

6. Search "Newtonsoft.Json" package in the filter of “Browse” tab, select the package in the package list and click the ‘Install’ button. 

7. Select “packages.config” radio-box and click “OK” button in the prompt “Choose NuGet Package Manager Format” dialog. 

#### Expected:    

The package will be installed successfully. 

#### Actual: 

The package installs fails with the follow error: 
![image](https://github.com/NuGet/Home/assets/84695155/06798409-d2d1-469d-b22b-1477d735d8ed)
#### Notes:     

1. The repro rate is 100%. 

2. It doesn’t repro on SDK project and non-SDK project that install package with “PackageReference” format. 

3. This error shouldn't block the installation of the package because the selected package source is ‘nuget.org’.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6373.
