### ISSUE TITLE
TFS issue: when install package into an solution first, bind the solution to TFS later, VS doesn't check in packages folder to TFS

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#1356]
NuGet version: 3.2.60904.105.08 
Repro Step: 
1. create consoleApplication project.
2. install EF 6.1.3 to the project
3. bind the solution to TFS.
4. Check in the pending changes.

Expect: all files in the solution are checked in to TFS.
actual: packages folder is not checked in to TFS.

this is an regression. 2.8.6 works well on VS 2013 for this case.

**Comment by deepakaravindr** [comment]
More context:
1. This issue is only applicable if the user has not disabled checking-in of packages folder. This is the default behavior.
2. Also, once the solution is bound to TFS, things seem to be fine

**Comment by yishaigalatzer** [comment]
> Also, once the solution is bound to TFS, things seem to be fine

@deepakaravindr I don't understand what this means. Can you be more specific?

@zhili1208 is this a regression from 3.1.1 ?

**Comment by deepakaravindr** [comment]
Once the solution has been bound to TFS, all the NuGet operations perform necessary source control oeprations as well. For example, if you installed a package to a TFS bound project, packages folder is marked for check-in as expected.
