### ISSUE TITLE
[Bug Bash] The “Advisory (high severity)” link for installed vulnerable package is truncated in the right panel of PM UI when shrinking the VS window  

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13579]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.11.0.113

### Worked before?

It can be repro on D17.10\34902.84, but it doesn’t repro on D16.11\34601.136 since the feature 'vulnerable package' was not merged into VS 16.11.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Create a C# Console App (.NET Framework) project. 

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI. 

3. Go to "Browse" tab, search for a vulnerable package (e.g. "Newtonsoft.Json") and choose a vulnerable version (e.g. "12.0.1"). 

4. Shrink the VS window to make sure it is not the maximum. 

5. Resize the PM UI window to the left to make it not wide enough to display all controls. 

#### Expected:    

The “Advisory (high severity)” link isn’t truncated in right panel. 

#### Actual: 

The “Advisory (high severity)” link is truncated as below: 
![image](https://github.com/NuGet/Home/assets/84695155/9effde0a-2c4d-4ed0-84b4-2cb82dff1fa5)

#### Notes:     
1. The repro rate is 100%. 
2. When shrinking the VS window and resizing the PM UI window to the left, we can see the horizontal bar at the bottom of the PM UI window, however dragging it to the right side would not resolve this issue.

**Comment by donnie-msft** [comment]
Thanks for finding this. I believe it's a duplicate of https://github.com/NuGet/Home/issues/12580.
/cc @jebriede for visibility since I believe you own this feature
