### ISSUE TITLE
https://github.com/NuGet/docs.microsoft.com-nuget/issues/3237 - Unsorted list in nuget package manager GUI within VS

### ISSUE THREAD

**Issue by dangavNZ** [NuGet/Home#13585]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

All

### Worked before?

never

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Open Nuget UI.  Search for Newtonsoft.

You won't get the base package first, and what you do get is a randomly sorted list!

### Verbose Logs

```shell
.
```

**Comment by jgonz120** [comment]
Hello, can you share what your results look like and what your expectation is? When I try this, I see them in the same order as nuget.org, and the first result is the base Newtonsoft.Json package. 

![image](https://github.com/NuGet/Home/assets/5552792/b70fb18f-ff94-4e28-be19-d1ccb74db6e4)

**Comment by dangavNZ** [comment]
Hi

Sorry didn't see the earlier notification.

I actually get the same although for some reason the UI scrolls down one entry so I don't see newtonsoft.json at the top of the list, so that's misleading... 

That being said, this list is in not in any logical order that I can easily determine.  There's no ranking score or indicator etc.

Thanks,
Daniel

**Comment by zivkan** [comment]
It's up to the server to determine the ranking/order. [The protocol that client-server uses for search](https://learn.microsoft.com/en-us/nuget/api/search-query-service-resource) doesn't have a way for the server to tell the client what the search score is.
