### ISSUE TITLE
DependencyVersion is not defaulted in Vs2015 UI from NuGet.config

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1361]
According to the v2.8 release notes, the DependencyVersion from nuget.config should be honored in the user interface and defaulted from nuget.config:
http://docs.nuget.org/release-notes/nuget-2.8#dependencyversion-attribute

This appears to work properly in Vs2013

**Comment by emgarten** [comment]
This looks like a dupe of: https://github.com/NuGet/Home/issues/1196

**Comment by csharpfritz** [comment]
Closing dupe
