### ISSUE TITLE
ManagePackageVersionsCentrally preventing restore with UsingTask from package

### ISSUE THREAD

**Issue by brinko99** [NuGet/Home#13613]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

.NET  8.0.302, VS 17.10.3

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Using `ManagePackageVersionsCentrally` with a package that includes a build task (i.e. `UsingTask`) that is referenced via `GeneratePathProperty` prevents the package from restoring with an `"ResolvePackageAssets" task failed unexpectedly` error.

The attached repo project includes the package `MSBuild.Microsoft.VisualStudio.Web.targets`, which defines a `TransformXml` task. When this task is used in an `AfterTargets="BeforeCompile"` target, the mentioned errors occur (see logs).

```
<ItemGroup>
  <PackageReference Include="MSBuild.Microsoft.VisualStudio.Web.targets" GeneratePathProperty="true" />
</ItemGroup>

<UsingTask TaskName="TransformXml"
           AssemblyFile="$(PkgMSBuild_Microsoft_VisualStudio_Web_targets)\tools\VSToolsPath\Web\Microsoft.Web.Publishing.Tasks.dll"/>

<Target Name="PerformTransform" AfterTargets="BeforeCompile">
  <TransformXml Source="TestFile.xml" Destination="TestFile.xml" Transform="TestFile.xml" />
</Target>
```

The only workaround we've found is to apply a condition on every target that uses the task. e.g. `Condition="'$(PkgMSBuild_Microsoft_VisualStudio_Web_targets)' != ''"`

This issue does not occur when not using centrally managed packages.

[CentralPackagesRepo.zip](https://github.com/user-attachments/files/16152071/CentralPackagesRepo.zip)

### Verbose Logs

```shell
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Error (active)	MSB4018	The "ResolvePackageAssets" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.NET.Build.Tasks.LockFileExtensions.<GetProjectFileDependencySet>g__IndexOfWhiteSpace|6_1(String s)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetProjectFileDependencySet(LockFile lockFile, String frameworkAlias)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.<WritePackageDependenciesDesignTime>g__GetPackageDependencies|59_0()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WritePackageDependenciesDesignTime()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroup(Action writeItems)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.Write()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.WriteToCacheFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	CentralPackagesRepo	c:\program files\dotnet\sdk\8.0.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	266
```

**Comment by nkolev92** [comment]
Duplicate reported in https://developercommunity.visualstudio.com/t/The-ResolvePackageAssets-task-failed-une/10648043.

**Comment by jnm2** [comment]
Is this likely the same bug or should I report separately? Also using central package management.

> MSB4018 The "ResolvePackageAssets" task failed unexpectedly.
> System.NullReferenceException: Object reference not set to an instance of an object.
> ```
>    at Microsoft.NET.Build.Tasks.ProjectContext.<>c__DisplayClass31_0.<GetTopLevelDependencies>b__3(String projectFileDependency)
>    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter.ComputePackageExclusions()
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
>    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
>    at Microsoft.NET.Build.Tasks.TaskBase.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> ```
> C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets

**Comment by jnm2** [comment]
In my case, it seemed the Directory.Packages.props file was not updated the first time I installed the new package, so I reverted the .csproj and tried again and this time both files updated, and this error came back briefly but I tried building a couple of times and then the restore succeeded.

**Comment by jeffkl** [comment]
Adding the condition `Condition="'$(PkgMSBuild_Microsoft_VisualStudio_Web_targets)' != ''"` is required for restore to succeed since without it MSBuild will fail to evaluate the project.  The `NullReferenceException` is coming from the [ResolveNuGetPackageAssets](https://github.com/dotnet/NuGet.BuildTasks/blob/main/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs) class which is in another repo.  But that task should only run during build and not restore?

**Comment by jeffkl** [comment]
I'm closing this in favor of https://github.com/dotnet/project-system/issues/8318

What's happening is the target is being injected into the project system's design-time build which fails since the task can't run because the package hasn't been restored yet.  

So this scenario requires:
1. The `UsingTask` must have a condition to ensure it's only created if restore has completed
2. The target injected must have a condition to not run during a design-time build

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSBuild.Microsoft.VisualStudio.Web.targets"
                      GeneratePathProperty="true" />
  </ItemGroup>
  <UsingTask TaskName="TransformXml"
             AssemblyFile="$(PkgMSBuild_Microsoft_VisualStudio_Web_targets)\tools\VSToolsPath\Web\Microsoft.Web.Publishing.Tasks.dll"
             Condition="'$(PkgMSBuild_Microsoft_VisualStudio_Web_targets)' != ''" />

  <Target Name="PerformTransform"
          AfterTargets="BeforeCompile"
          Condition="'$(DesignTimeBuild)' != 'true' Or '$(BuildingProject)' == 'true'">
    <Message Text="Transformaing file" Importance="High" />
    <TransformXml Source="TestFile.xml" Destination="TestFile.xml" Transform="TestFile.xml" />
  </Target>
</Project>

```
