### ISSUE TITLE
Syntax to specify latest pre-release in nuget 3.2rc

### ISSUE THREAD

**Issue by paulvanbrenk** [NuGet/Home#1362]
Probably similar to #1360 

Is there a way to configure my project.json file to always download the latest pre-release version of the Roslyn Nightly pacakages.

``` javascript
{
  "dependencies": {
    "Microsoft.CodeAnalysis.Common": "1.1.0-beta"
  },
  "frameworks": {
    "net452": {}
  }
}
```

This gets me the following version: 

`WARNING: Dependency specified was Microsoft.CodeAnalysis.Common (≥ 1.1.0-beta) but ended up with Microsoft.CodeAnalysis.Common 1.1.0-beta1-20150812-01.`

This is not the newest, which is advertised as:

`v1.1.0-beta1-20150906-01`

Any suggestions on the correct syntax in the project.json to always get the latest even if it's pre-release? Or is this a bug.

(Source for Roslyn nightly is: https://www.myget.org/gallery/roslyn-nightly)

**Comment by yishaigalatzer** [comment]
use `1.1.0-*`
