### ISSUE TITLE
When offline or bad package source, build of UWP shows confusing error when packages are missing

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1363]
When offline or bad package source, build of UWP shows confusing error when packages are missing

Repro steps
1. Put the machine offline
2. Create a new UWP application
3. Delete (or backup) 1 or 2 packages from global packages folder
4. Perform build or hit 'Restore Packages' Menu at solution level

Expected:
1. Build is fails with a meaningful error on why package restore failed

Actual:
1. Build fails with the following error

![image](https://cloud.githubusercontent.com/assets/2380340/9776995/6976be60-5713-11e5-86d9-9a0c14ffbda0.png)

Snapshot of clean Fiddler trace when performing the build as follows

![image](https://cloud.githubusercontent.com/assets/2380340/9777180/a55aeea4-5715-11e5-9f77-adecac1feed8.png)

**Comment by nkolev92** [comment]
Redundant.
