### ISSUE TITLE
dotnet add package stops checking sources on the first failure http code

### ISSUE THREAD

**Issue by xparadoxical** [NuGet/Home#13642]
### NuGet Product Used

dotnet.exe

### Product Version

NuGet Command Line 6.10.0.97; .NET SDK:  Version:           8.0.300  Commit:            326f6e68b2  Workload version:  8.0.300-manifests.5273bb1c  MSBuild version:   17.10.4+10fbfbf2e

### Impact

It's more difficult to complete my work

### Repro Steps & Context

dotnet/sdk#42245
In short, have a source that 503's and it'll prevent you from using `dotnet add package <name>` without `--source` or disabling the failing source.

### Verbose Logs

Can't get them because the dotnet-tools source (`https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json`) doesn't respond with 503 anymore and `--verbosity diag` seems to be undocumented (I looked yesterday specifically for any verbosity option in the `dotnet` docs and didn't see anything).

**Comment by jgonz120** [comment]
I was able to reproduce this by using https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json as a source.

**Comment by nkolev92** [comment]
That's a known restore requirement for PackageReference, documented in https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-and-sources. 

Dup of https://github.com/NuGet/Home/issues/6373:
