### ISSUE TITLE
'Clean Solution' does not clear NuGet Package Restore errors

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1366]
'Clean Solution' does not clear NuGet Package Restore errors.
This is a regression from NuGet 3.1

Repro steps:
1. Create a console application and install Newtonsoft.Json
2. Open packages.config and create a entry for non-existent package. Example xml snippet at the end
3. Perform Build. This should create an error. Look at snapshot at the end
4. Perform 'Clean Solution'

Expected:
1. Package restore errors are cleaned up

Actual:
1. Package restore errors are not cleaned up. See below

``` xml
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net452" />
      <package id="Newtonsoft.Json.BlahBlah" version="7.0.1" targetFramework="net452" />
    </packages>
```

![image](https://cloud.githubusercontent.com/assets/2380340/9777379/8996c8c0-5718-11e5-854b-f8fa22ec72b0.png)

**Comment by yishaigalatzer** [comment]
When you build again, the error does go away?

**Comment by deepakaravindr** [comment]
Once the package restore error has been resolved by the user, building it again clears the error, yes.

**Comment by yishaigalatzer** [comment]
This behavior seems reasonable. Closing
