### ISSUE TITLE
[Feature] Automatically remediate known vulnerabilities in dependencies by upgrading them.

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13665]
### NuGet Product(s) Involved

NuGet.exe, Visual Studio Package Management UI, MSBuild.exe, dotnet.exe, NuGet SDK

### The Elevator Pitch

The CLI and VS tooling should be able to automatically remediate known vulnerabilities in dependencies by upgrading them. This issue tracks the PR design of https://github.com/NuGet/Home/pull/11549 which would provide this functionality through a new `dotnet audit` and `dotnet audit fix` command.

**Comment by nkolev92** [comment]
Dup in https://github.com/NuGet/Home/issues/13372. 

I see you're tracking this in another place, can you dup them out @JonDouglas? 
Feel free to ping me if needed.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/13372.
