### ISSUE TITLE
Is There any way to list the dependency tree of some dotnet project/solution ?

### ISSUE THREAD

**Issue by athinboy** [NuGet/Home#13669]
### NuGet Product(s) Involved

Visual Studio Package Management UI, Visual Studio Package Manager Console, NuGet SDK

### The Elevator Pitch

when build a project ,there are some unexpected  **.dll files . I hope a convenient  way  to show the dependency tree of dotnet project/solution ,UI is better ,Console is ok .
corresponding to Mavin In Java. 
Sorry for my bad english .

**Comment by martinrrm** [comment]
Hi! We recently added the command `dotnet nuget why` available in 8.0.4xx https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-why

There is also a helpful tool from a NuGet team member that could help you visualize the dependency tree
https://github.com/nkolev92/DependencyVisualizer

**Comment by martinrrm** [comment]
I'm closing the issue since this is not an actual bug/feature, but feel free to continue the conversation here, hopefully the previous tasks help you

**Comment by athinboy** [comment]
@martinrrm  thanks.
but,why not add a list-dependency command to list whole dependency  recursively ?
