### ISSUE TITLE
Fail to run the ‘filebackedserver’ project by running command ‘dotnet run --project’ with patched .NET SDK 9.0.1xx

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13662]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet SDK 9.0.100-rc.1.24380.5

### Worked before?

It’s not a regression since this is a new feature.

### Impact

I'm unable to use this version

#### Repro Steps:
1.	[Patch dotnet  SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703) (patch 9.0.1xx with Nupkgs from Dev latest). 
2.	Open a command prompt (called prompt1), go to the PatchedSDK folder and create a .NET SDK project with command `dotnet new console  -n NetCoreConsole `
3.	In the solution folder, create a file named nuget.config with the following content: 
```
<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
  <packageSources> 
    <clear /> 
    <add key="mySource" value="https://127.0.0.1:44444/v3/index.json"/> 
  </packageSources> 
</configuration>
```
4.	Open the .csproj file for your project and insert the following package reference within an ItemGroup: 
```
<ItemGroup> 
  <PackageReference Include="abcdefghijkl" Version="1.0.0" /> 
</ItemGroup> 
```
5.	Open a second command prompt (called prompt2), go to the PatchedSDK folder and build the server by running:  
`dotnet build   …Entropy\filebackedserver\filebackedserver.csproj `
6.	Start the local server by executing: 
`dotnet run --project  ….Entropy\filebackedserver\filebackedserver.csproj `

#### Expected Result:
Succeed to run the ‘filebackedserver’ project by running command ‘dotnet run --project’ with patched .NET SDK 9.0.1xx.

#### Actual Result:
Fail to run the ‘filebackedserver’ project by running command ‘dotnet run --project’ with patched .NET SDK 9.0.1xx.
![image](https://github.com/user-attachments/assets/b231ecdb-9fa9-4fbc-80b4-13488cb285f5)
#### Note:
1.The repro rate: 100%.
2.It should be fixed since NuGet Dev latest matches .NET SDK 9.0 now and the failure would block the following step of the test case 'TLSCertificateValidation'.

**Comment by martinrrm** [comment]
@v-luzh Hi! The screenshot doesn't contain any error, I see that is complaining that NET 8.0 is missing, does the error comes right after that?


@nkolev92 Sorry I don't have a lot of knowledge about this scripts, do we need to update the version something like this change https://github.com/NuGet/Entropy/commit/a5838640ef2a51b31bea400b1231da08dc63f6fa?

**Comment by v-luzh** [comment]
Hi @martinrrm, no, there was any error coming out after that, but the expected log should be shown as the screenshot below.
![image](https://github.com/user-attachments/assets/0bea0da6-2692-45f8-a21a-a905ce0d3df7)
And you can see there is a line "https://aka.ms/dotnet/app-launch-failed" in the screenshot of the Active Result part, is that means launching the project failed?

**Comment by zivkan** [comment]
@v-luzh the error says "you must install or update .NET to run this application", it then goes on to explain the app that was found, and it says "Framework: Microsoft.NETCore.App, Version 8.0.0", followed by ".NET location: ...\patchedSDK" and finally it says "the following frameworks were found" and only lists 9.0.0, not 8.0.0.

If you did a restore & build in a different command to the run, it might be easier to see the difference between the runtime error and the build warnings.

Note, apps can be configured to "roll forward" and try to run on newer runtimes, when target runtime is not found. I don't remember how to do it, but I suspect a quick web search will find out what you need to put in the csproj to enable it. In theory if there are breaking changes between .NET versions, the app might break when it's running on a different version than it was compiled for, but there's generally low risk of that.

**Comment by v-luzh** [comment]
Hi @zivkan, thanks for your description. We tried to update the <TargetFramework> to 'net9.0' and the testing can be continued. I will close this bug soon, thanks again.
