### ISSUE TITLE
NuGet cache clearing fails after clicking the button “Clear All NuGet Storage” in “Options->NuGet Package Manager ->General” window for SDK project 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13660]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.12.0.36

### Worked before?

It’s a regression since it doesn’t repro before .NET MAUI (.NET 9 Preview) is involved to the VS Workloads.

### Impact

It's more difficult to complete my work

#### Repro Steps:    

1. Create a C# Console App (.NET 8.0) project in VS and open the PM UI or PMC window. 

2. Install several packages (e.g. Newtonsoft.Json and log4net) through PM UI. 

3. Click the settings button (gear button) on PM UI or PMC window. 

4. Click the “NuGet Package Manager->General” in the opened “Options” window. 

5. Click the button “Clear All NuGet Storage” and check the message. 

#### Expected:    

The message should show correctly like “NuGet storage cleared at [Time]” 

#### Actual: 

NuGet cache clearing fails as below: 
![Unbenannt_0730](https://github.com/user-attachments/assets/c1308af7-b037-4c25-a488-36673300c8d6)
#### Notes:     

1. The repro rate is 100%. 
2. It blocked installing all packages after clicking the “Clear All NuGet Storage” button. 
3. It only reproes after installing the “.NET MAUI (.NET 9 Preview)” workload from .NET Multi-platform App UI development in VS installer, doesn’t repro if you didn’t install that workload.

**Comment by nkolev92** [comment]
What does Can you run dotnet nuget locals --clear do? If it fails, can you try with high verbosity?

Do we know if it's a permissions problem or something else?

**Comment by CiciLi1** [comment]
> What does Can you run dotnet nuget locals --clear do? If it fails, can you try with high verbosity?
> 
> Do we know if it's a permissions problem or something else?


Hi @nkolev92, the command `dotnet nuget locals all --clear` fails to execute when VS is open, but succeeds when VS is closed, as shown below:
![Unbenannt0806](https://github.com/user-attachments/assets/acf8cb92-eecd-4a2d-93ec-69f1ed108a3b)

We also tried using the --verbosity detailed option, but it was not recognized in the Developer Command as below:
![image](https://github.com/user-attachments/assets/3bec452a-7db0-4648-9bcc-8fe9d8aefdd7)

**Comment by CiciLi1** [comment]
Verified this issue on VS Main\35213.193 + NuGet Client Dev\6.12.0.67, it's fixed, so closed it, thanks!
