### ISSUE TITLE
VS restore won't respect project prefix in the lock file

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#13663]
Internal ticket: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2172224

This is a weird bug, when you are using lock files and have a `ProjectA` referencing `ProjectB` **and add a prefix in the `Directory.Build.props`** with a `PackageReference` to Nugetizer, the lock file is going to produce different outputs depending on where restore was made.

VS will output something like this:

```json
{
  "version": 1,
  "dependencies": {
    "net8.0": {
      "referencedproject": {
        "type": "Project"
      }
    }
  }
}
```

While doing a `dotnet restore` it will result in:
```json
{
  "version": 1,
  "dependencies": {
    "net8.0": {
      "A.Prefix.ReferencedProject": {
        "type": "Project"
      }
    }
  }
}
```

Example Directory.Build.props:

```xaml
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <AssemblyPreffix Condition="$(AssemblyPreffix) == ''">A.Prefix</AssemblyPreffix>
    <AssemblyName Condition="$(AssemblyName) == ''">$(MSBuildProjectName)</AssemblyName>
    <AssemblyName Condition="!$(AssemblyName.StartsWith(AssemblyPreffix))">$(AssemblyPreffix).$(AssemblyName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup Condition="!$(MSBuildProjectName.Contains('ReferencedProject'))">
    <ProjectReference Include="..\ReferencedProject\ReferencedProject.csproj" />
  </ItemGroup>
</Project>
```

Example ReferencedProject.csproj:

```xaml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by nkolev92** [comment]
Assigning to hotseat for investigation

**Comment by jebriede** [comment]
Team Triage: Assigning to current hotseat for investigation

**Comment by kartheekp-ms** [comment]
I am able to reproduce this issue in VS 2022 versions 17.11.2, 17.12 public preview, and internal preview.

I noticed an odd behavior, but I haven't identified the root cause yet.

- Cloned the repo https://github.com/voroninp/BadRestore locally
- The project name in https://github.com/voroninp/BadRestore/blob/17c6cef9243543d6c854418d23913bfe2b29ea80/BadRestore/packages.lock.json#L5 is still `referencedproject`
- Opened `BadRestore.sln` in Visual Studio 2022
- I observed that the project name was `A.Prefix.Referencedproject` for a fraction of a second before it changed to `referencedproject`. I didn't execute `dotnet restore` in separate process.

![vs-restore-nugetizer](https://github.com/user-attachments/assets/9f049b2d-be23-453f-82f3-984800871acd)

**Comment by jeffkl** [comment]
@voroninp I believe the repro has bad MSBuild syntax which I've fixed at https://github.com/voroninp/BadRestore/pull/1 and now the lock file is properly regenerated in VS for me.

**Comment by voroninp** [comment]
@jeffkl , hi, I'll be able to check in a week. Thanks.

**Comment by voroninp** [comment]
@jeffkl , hello once again. I added a commit which contains your changes (I hope I did not miss anything), but I still can reproduce the issue.

**Comment by jeffkl** [comment]
@voroninp I suspect you still have something wrong with your MSBuild logic.  Previously you had 
```diff
- <AssemblyName Condition="!$(AssemblyName.StartsWith(AssemblyPreffix))">$(AssemblyPreffix).$(AssemblyName)</AssemblyName>
+ <AssemblyName Condition="!$(AssemblyName.StartsWith($(AssemblyPreffix)))">$(AssemblyPreffix).$(AssemblyName)</AssemblyName>
```

Where the Condition was missing some MSBuild syntax for properties, specifically the `$()`.  I do not believe there is a bug in NuGet and instead that the custom logic you are using has an issue.  With the change at https://github.com/voroninp/BadRestore/pull/1, I was not able to reproduce the issue.

**Comment by voroninp** [comment]
But I did change it in last commit:
![image](https://github.com/user-attachments/assets/0d854e09-c10f-48c3-a9b9-d5c8216868db)

```
<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <AssemblyPrefix Condition="$(AssemblyPrefix) == ''">A.Prefix</AssemblyPrefix>
    <AddPrefixToRootNamespace Condition="$(AddPrefixToRootNamespace) == ''">false</AddPrefixToRootNamespace>
    <AssemblyName Condition="$(AssemblyName) == ''">$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>$(AssemblyName.Replace(" ", "_"))</RootNamespace>
    <AssemblyName Condition="!$(AssemblyName.StartsWith($(AssemblyPrefix)))">$(AssemblyPrefix).$(AssemblyName)</AssemblyName>
    <RootNamespace Condition="'$(AddPrefixToRootNamespace)' == 'true'">$(AssemblyName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>


  <ItemGroup Condition="!$(MSBuildProjectName.Contains('ReferencedProject'))">
    <ProjectReference Include="..\ReferencedProject\ReferencedProject.csproj" />
  </ItemGroup>

</Project>
```

Also, if it's a bad MsBuild syntax, why does behavior of VS and dotnet cli differ?

**Comment by jeffkl** [comment]
Those changes look different than the ones I proposed in the pull request.  With the changes in my pull request, I tested things out in Visual Studio and from the command-line and got the same results.

When you add a lot of proprietary custom logic to your MSBuild, its hard for us to support every possible thing you're trying to accomplish.  I'm not sure why your changes above are causing issues but I suspect that if you use my original pull request then it will work.

**Comment by voroninp** [comment]
I just did reset and merged your changes. The issue is still there.

**Comment by voroninp** [comment]
![BadRestore](https://github.com/user-attachments/assets/5415d0cd-9ba3-4302-b626-4c527db78c72)

**Comment by jgonz120** [comment]
I can't explain what the difference is between VS and the command line. If you run `msbuild /t:restore` from the developer command prompt, it generates the expected package.lock. 

From what I can tell, when msbuild is running without `MSBuildIsRestoring` being true, it allows for project extensions which allows for nugetizer add itself and override the NuGet build options. 

That said, by default `IsPackable` is set to false by default for NuGetizer, https://github.com/devlooped/nugetizer/issues/26. If you add `<IsPackable>true</IsPackable>` to ReferencedProject.csproj you should get the build to work as expected in the IDE.

**Comment by voroninp** [comment]
@jgonz120 , it works indeed. But I have no clue why this property affects assembly name =)

**Comment by jgonz120** [comment]
NuGetizer includes it's own set of MSBuild properties. 
If you look at https://github.com/devlooped/nugetizer/blob/cfefd208d635b68d6b3b9b3acd40feac54f92acd/src/NuGetizer.Tasks/NuGetizer.Shared.targets#L58 you'll see that the PackageId is set to the Assembly name only when IsPackable is set to true.

**Comment by voroninp** [comment]
@jgonz120 , got it, thanks.

But if project is not packable, why is it captured in `packages.lock.json`?

**Comment by jgonz120** [comment]
package.lock is keeping track of all the dependencies, not just NuGet package dependencies.

**Comment by voroninp** [comment]
Ok, but then if it's a regular dependency which is not a package why it uses package id and not just an assembly name?

Also, if it's the fault of Nugetizer which weirdly sets MsBuild properties why this behavior has no effect for `dotnet restore`?

**Comment by jgonz120** [comment]
> Ok, but then if it's a regular dependency which is not a package why it uses package id and not just an assembly name?

If you look at [NuGet.Build.Tasks.Pack.targets](https://github.com/NuGet/NuGet.Client/blob/3603dca86e416b7f013accf93a4cec0ece231d87/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L29), NuGet always sets the `Package Id` to the `Assembly Name`, unless it's overwritten somewhere. The code is using this as the [project name](https://github.com/NuGet/NuGet.Client/blob/c36ca8ffc76879296441df65ab90adbcdfddfae1/src/NuGet.Clients/NuGet.SolutionRestoreManager/VsSolutionRestoreService.cs#L355), so without a `Package Id` it uses the [project file name](https://github.com/NuGet/NuGet.Client/blob/3603dca86e416b7f013accf93a4cec0ece231d87/src/NuGet.Clients/NuGet.SolutionRestoreManager/VSNominationUtilities.cs#L194). 

> Olso, if it I the fault of Nugetizer which weirdly sets MsBuild properties why this behavior has no effect for `dotnet restore`?

This part I'm still unsure about. Looking at the binlogs there's a difference between running `msbuild /t:restore` and `msbuild /t:rebuild`. Given the behavior I believe that VS doesn't run msbuild with restore, so NuGetizer is getting injected in the IDE and then those results are passed directly to NuGet restore, creating the incorrect package.lock.json. I haven't been able to confirm this yet.

**Comment by voroninp** [comment]
@jgonz120 , I am trying to summarize:

Case one:
- Value for `IsPackable` is not defined.
- NuGetizer [sets](https://github.com/devlooped/nugetizer/blob/cfefd208d635b68d6b3b9b3acd40feac54f92acd/src/NuGetizer.Tasks/NuGetizer.Shared.targets#L58 ) `IsPackable` to `false` and does not set `PackageId`.
- NuGet [sets](https://github.com/NuGet/NuGet.Client/blob/3603dca86e416b7f013accf93a4cec0ece231d87/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L29) not-initialized `PackageId` to assembly name.
- Assembly name should contain prefix, defined in `props` file.


Case two:
- `IsPackable` is set to `true`.
- NuGetizer sets `PackageId` to `AssebmlyName`.
- NuGet reuses that `PackageId` value.

In the latter case `AssemblyName` contains prefix.  But prefix should be added anyway as `props` file is evaluated first.

And your comment:
> NuGet **always sets** the Package Id to the Assembly Name, unless it's overwritten somewhere. ... **without** a Package Id it uses the project file name.

**How come there can be no package id, if NuGet always sets it?**

By the way, if I explicitly set in proj file:
```
<IsPackable>false</IsPackable>
<PackageId>X</PackageId>
<AssemblyName>Y</AssemblyName>
```
`packages.lock.json` contains `X`.

If I do not set `PackageId`, `packages.lock.json` contains project name.

**Comment by jgonz120** [comment]
When NuGetizer is enabled, it replaces NuGet.Build.Tasks.Pack.targets. So NuGet does not get the opportunity to set the PackageId.

**Comment by jeffkl** [comment]
Closing this since it appears to not be a bug
