### ISSUE TITLE
NullReferenceException in AddPackageAsync

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#1367]
Hi,

it seems that I get a `NullReferenceException` in `AddPackageAsync` when adding the NuGet package `FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01` to a .NET 4.6 WPF project.

```
Aktionen zum Installieren des Pakets "FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01" wurden aufgelöst.
Installationsfehler. Ein Rollback wird ausgeführt...
Das Paket "FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01" ist im Projekt "****" nicht vorhanden.
Das Paket "FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01" ist im Ordner "C:\Users\****\Documents\GitHubVisualStudio\****\packages" nicht vorhanden.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Abgeschlossen ==========
```

**Comment by deepakaravindr** [comment]
I tried the latest bits found at http://blog.nuget.org/20150902/nuget-3.2RC.html. It seems to work. Could you please try and let us know the behavior?

```
PM> Install-Package FubarCoder.RestSharp.Portable.OAuth2 -Version 3.0.0-beta01
Attempting to gather dependencies information for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with respect to project 'WpfApplication1', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Resolved actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Adding package 'Newtonsoft.Json.7.0.1' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to 'packages.config'
Executing script file 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages\Newtonsoft.Json.7.0.1\tools\install.ps1'
Successfully installed 'Newtonsoft.Json 7.0.1' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' to folder 'c:\users\daravind\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.OAuth2 3.0.0-beta01' to WpfApplication1
PM> 
```

**Comment by fubar-coder** [comment]
Not working for me:

```
PM> Install-Package FubarCoder.RestSharp.Portable.OAuth2 -Version 3.0.0-beta01
Attempting to gather dependencies information for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with respect to project 'WpfApplication1', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Resolved actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Adding package 'Newtonsoft.Json.7.0.1' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to 'packages.config'
Executing script file 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages\Newtonsoft.Json.7.0.1\tools\install.ps1'
Successfully installed 'Newtonsoft.Json 7.0.1' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' to WpfApplication1
Install failed. Rolling back...
Package 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' does not exist in project 'WpfApplication1'
Removed package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from 'packages.config'
Removed package 'Newtonsoft.Json 7.0.1' from 'packages.config'
Package 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' does not exist in folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removing package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removed package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removing package 'Newtonsoft.Json 7.0.1' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removed package 'Newtonsoft.Json 7.0.1' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Install-Package : Error while copying content to a stream.
At line:1 char:1
+ Install-Package FubarCoder.RestSharp.Portable.OAuth2 -Version 3.0.0-b ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Here's the exception from the Package Manager output:

```
Attempting to gather dependencies information for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with respect to project 'WpfApplication1', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Resolved actions to install package 'FubarCoder.RestSharp.Portable.OAuth2.3.0.0-beta01'
Adding package 'Newtonsoft.Json.7.0.1' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Newtonsoft.Json.7.0.1' to 'packages.config'
Executing script file 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages\Newtonsoft.Json.7.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 7.0.1' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.Core.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' to WpfApplication1
Adding package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'FubarCoder.RestSharp.Portable.OAuth.3.0.0-beta01' to 'packages.config'
Successfully installed 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' to WpfApplication1
Install failed. Rolling back...
Package 'FubarCoder.RestSharp.Portable.OAuth2 3.0.0-beta01' does not exist in project 'WpfApplication1'
Removed package 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' from 'packages.config'
Removed package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from 'packages.config'
Removed package 'Newtonsoft.Json 7.0.1' from 'packages.config'
Package 'FubarCoder.RestSharp.Portable.OAuth2 3.0.0-beta01' does not exist in folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removing package 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removed package 'FubarCoder.RestSharp.Portable.OAuth 3.0.0-beta01' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removing package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removed package 'FubarCoder.RestSharp.Portable.Core 3.0.0-beta01' from folder 'C:\Users\****
\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removing package 'Newtonsoft.Json 7.0.1' from folder 'C:\Users\***\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Removed package 'Newtonsoft.Json 7.0.1' from folder 'C:\Users\****\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
```

This is a screenshot from my VS' info window:
![vs-2015-info](https://cloud.githubusercontent.com/assets/4739844/9837431/f75b826e-5a3e-11e5-93b2-904eebe9bc87.png)

**Comment by yishaigalatzer** [comment]
@fubar-coder and @deepakaravindr with plan to release 3.2 RTM shortly, lets verify if this is still an issue after that, and if so try to narrow down the steps to reproduce the problem. If it still reproducible after 3.2 RTM, we should definitely fix it.

@fubar-coder would you be able to provide (after the release, where we will push symbol packages to symbolsource.org) an accurate call stack with the line where this happens?

**Comment by deepakaravindr** [comment]
@fubar-coder, Could you please provide more information?
1. Do you have %USERPROFILE% set on your machine? Also, what does the following code return on your machine?
   `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);`
2. Do you have 'nuget.org' as your package source? And, is the URl https://api.nuget.org/v3/index.json?
3. Is it a consistent repro?

**Comment by fubar-coder** [comment]
@yishaigalatzer I'll try to provide an accurate call stack, but it'd be nice if you could provide instructions how to do it.

@deepakaravindr I cannot definitely answer your questions 1+2, because I'm not at home until thursday evening.
1. %USERPROFILE% is most likely set and `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` should return the same value
2. Most likely yes, as I can download all other packages
3. Yes

**Comment by yishaigalatzer** [comment]
You will need a few things.
0. Wait until we release 3.2 today and install it
1. Add symbolsource.org as a symbol source
2. Attach a second instance of visual studio to your visual studio (do it as late as possible as it is going to slow things down)
3. In debug setting turn on exception catching for handled exception and only check nullref
4. Repeat the action above

Cc // @MeniZalzman - need to make sure all symbols are up today on symbolsource or alternatively all pdbs are available (including the ones from the visual studio extension)

**Comment by fubar-coder** [comment]
@yishaigalatzer I tried to follow the steps above, buit it says that it cannot find the `NuGet.Protocol.Core3.v3.pdb` under the following paths:
- Microsoft Symbol Servers
- http://referencesource.microsoft.com/symbols
- http://srv.symbolsource.org/pdb/Public
- http://srv.symbolsource.org/pdb/MyGet
- http://msdl.microsoft.com/download/symbols

Did I miss a symbol source?

**Comment by yishaigalatzer** [comment]
Just talked to @MeniZalzman who is working on the pushing the symbols, they are not live yet, and should be later this week.

@MeniZalzman please update this thread once things are live.

I also assume you updated to 3.2 RTM and you still get the nullref?

**Comment by fubar-coder** [comment]
Yes, that is correct.

**Comment by ghost** [comment]
Same Mistake.

Attempting to gather dependencies information for package 'AutoMapper.4.0.4' with respect to project 'Amaggi.Opus.Web.Api', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'AutoMapper.4.0.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'AutoMapper.4.0.4'
Resolved actions to install package 'AutoMapper.4.0.4'
Removed package 'AutoMapper.4.0.3' from 'packages.config'
Successfully uninstalled 'AutoMapper.4.0.3' from Amaggi.Opus.Web.Api
Install failed. Rolling back...
Package 'AutoMapper 4.0.4' does not exist in project 'Amaggi.Opus.Web.Api'
Package 'AutoMapper.4.0.3' already exists in folder 'C:\BitBucket\Opus-Credito\OpusCredito\packages'
Added package 'AutoMapper.4.0.3' to 'packages.config'
Package 'AutoMapper 4.0.4' does not exist in folder 'C:\BitBucket\Opus-Credito\OpusCredito\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
![2015-09-25_15-08-08](https://cloud.githubusercontent.com/assets/10385588/10109819/644cd060-6397-11e5-9632-29a325817e77.png)

**Comment by yishaigalatzer** [comment]
Can any of you share a project (and if that doesn't work) an azure VM where we can try and reproduce this issue? We aren't able to reproduce it in our "lab"

**Comment by fubar-coder** [comment]
I'm currently unable to provide an Azure VM (due to limited resources), but I'm willing to test it again when the PDB files are available.
@MeniZalzman Any time frame when the PDB files are uploaded?

**Comment by yishaigalatzer** [comment]
Symbols are available in symbolsource.org

**Comment by yishaigalatzer** [comment]
@fubar-coder please contact me directly on my microsoft email, and I can hook you up with a VM for this purpose (y i g a l a t z @ ...)

**Comment by fubar-coder** [comment]
@yishaigalatzer It's still unable to download the symbols from symbolsource.org. Maybe it's a configuration problem on my side? However, I'm not sure if a VM really works as it doesn't happen on every PC I have access to.

**Comment by deepakaravindr** [comment]
@fubar-coder, Can you please send an email to me at daravind@microsoft.com?
I can help you resolve this issue. Thanks!

**Comment by idg10** [comment]
I'm seeing exactly this same issue, but with a different package:

Attempting to gather dependencies information for package 'xunit.extensibility.execution.2.1.0' with respect to project '@Tests\Valhalla.Services.Core.Tests', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'xunit.extensibility.execution.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.extensibility.execution.2.1.0'
Resolved actions to install package 'xunit.extensibility.execution.2.1.0'
Install failed. Rolling back...
Package 'xunit.extensibility.execution 2.1.0' does not exist in project 'Valhalla.Services.Core.Tests'
Package 'xunit.extensibility.execution 2.1.0' does not exist in folder 'C:\dev\valhalla\Finsbury\src\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

**Comment by yishaigalatzer** [comment]
Ian, what version of NuGet are you using?

**Comment by deepakaravindr** [comment]
@fubar-coder, I have sent you an email. Not sure if you got a chance to read it. Please check it out.

**Comment by idg10** [comment]
@yishaigalatzer, VS2015 reports NuGet 3.2.0. And if I open the Package Manager Console pane I see:

```
Package Manager Console Host Version 3.2.0.10516
```

Interestingly, if I run Install-Package and point it at the v2 NuGet feed, it works ok.

**Comment by yishaigalatzer** [comment]
@idg10 

At least on 3.3 I don't see it:

```
PM> install-package xunit.extensibility.execution
Attempting to gather dependencies information for package 'xunit.extensibility.execution.2.1.0' with respect to project 'ClassLibrary5', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'xunit.extensibility.execution.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'xunit.extensibility.execution.2.1.0'
Resolved actions to install package 'xunit.extensibility.execution.2.1.0'
Adding package 'xunit.abstractions.2.0.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.abstractions.2.0.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.abstractions.2.0.0' to 'packages.config'
Successfully installed 'xunit.abstractions 2.0.0' to ClassLibrary5
Adding package 'xunit.extensibility.core.2.1.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.extensibility.core.2.1.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.extensibility.core.2.1.0' to 'packages.config'
Successfully installed 'xunit.extensibility.core 2.1.0' to ClassLibrary5
Adding package 'xunit.extensibility.execution.2.1.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.extensibility.execution.2.1.0' to folder 'c:\users\yigalatz\documents\visual studio 2015\Projects\ClassLibrary5\packages'
Added package 'xunit.extensibility.execution.2.1.0' to 'packages.config'
Successfully installed 'xunit.extensibility.execution 2.1.0' to ClassLibrary5
PM> 
```

Source is - api.nuget.org/v3/index.json

So I'd suggest first upgrading to 3.2.1-RC (or shoot me an email, and I'll try to get you private bits for 3.3), if it still repros we will need to get a more detailed case (like a sample project that fails with exact steps)

Edit: You can find 3.2.1-rc on https://dist.nuget.org/index.html

**Comment by yishaigalatzer** [comment]
Closing as I don't see any reports that this repros on 3.3, and we cannot repro it either.
