### ISSUE TITLE
[Bug Bash] The showing behaviors of transitive vulnerable package are inconsistent between project-level PM UI and solution-level PM UI 

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13687]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.12.0.60

### Worked before?

It’s not a regression since the vulnerability InfoBar does not display in the Solution Explorer window when the transitive package is a vulnerable package in .NET SDK 8.0.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:    

1. Open VS and create a C# Console App (.NET 9.0) project. 

2. Right-click the project in Solution Explorer and select ‘Manage NuGet Packages…’ menu item to open the project-level PM UI.  

3. Click “Browse” tab, search for the package ‘FSharp.Net.Http’ that has dependencies of vulnerable package and click the “Install” button on the right. 

4. Observe the Solution Explorer window, a golden InfoBar and a link “Manage NuGet Packages” will show on the top of the Solution Explorer window. 

5. Click the link “Manage NuGet Packages” on the golden InfoBar. 

#### Expected:    

The showing behaviors of transitive vulnerable package should be consistent between project-level PM UI and solution-level PM UI. 

#### Actual: 

The showing behaviors of transitive vulnerable package are inconsistent between project-level PM UI and solution-level PM UI as below. (The warning icon and vulnerable info are showing on project-level PM UI, but not showing on solution-level PM UI.) 
![Unbenannt](https://github.com/user-attachments/assets/c0a6baf2-3be0-4004-a3b1-2bac62b2752c)
#### Note:     

1. The repro rate is 100%. 
2. The transitive vulnerable package info/warning-icon should be involved into solution-level PM UI because of the “The solution contains package with vulnerabilities” message at the top of the Solution Explorer window.

**Comment by Nigusu-Allehu** [comment]
This is by design and will eventually be enabled following https://github.com/NuGet/Home/issues/13216

**Comment by v-luzh** [comment]
This issue is fixed on VS Main\35325.243 + NuGet Client Dev\6.12.0.118.
