### ISSUE TITLE
'dotnet list package --vulnerable' checks packages in all sources even when package source mapping is enabled

### ISSUE THREAD

**Issue by mikolajpiecuch** [NuGet/Home#13689]
### Discussed in https://github.com/NuGet/Home/discussions/13688

<div type='discussions-op-text'>

<sup>Originally posted by **mikolajpiecuch** August  8, 2024</sup>
Hi, I observe some strange behaviour as follows. I've configured a package source mapping for my repo (defined in Nuget.config in repo root). I use nuget.org with a pattern of "\*" and my private repo with a pattern of "MyName.\*". While restoring, nugets are fetched correctly from these two sources. Unfortunately, when I call 'dotnet list package', it seems to call all my sources for all packages - e.g. GET request for Microsoft.* packages is sent to my private nuget registry. Why doesn't 'dotnet list package --vulnerable' take Nuget.config into account?</div>

Because of that I see a lot of requests on my private server that could be limited only to my packages

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/12766.
