### ISSUE TITLE
NuGet Package Manager can't restore packages on build from sources with authentication till Package Manager Console is opened

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#1368]
Steps to reproduce:
- add a source with authentication into project's .nuget\nuget.config
- install a package 
- close VS
- delete the package's folder (in 'packages' dir)
- open VS
- build project

NuGet will report 401 error during 'package restore' step. 

Then open Package Manager Console window (do nothing, just wait it's initialized) and build again.
Now NuGet successfully downloads the package from source. It asks for credentials if they weren't cached or just uses the cached ones.

**Comment by zhili1208** [comment]
this issue doesn't repro in 3.2, it's 2.8.6 issue

**Comment by yishaigalatzer** [comment]
We don't plan to fix this for 2.X, but will gladly take a pull request.
