### ISSUE TITLE
TFS keeps adding packages to Source Control

### ISSUE THREAD

**Issue by DdeMoel** [NuGet/Home#1369]
Whenever I start a project and install a NuGet package the package gets added to TFS. There is also not a .nugget folder being created, and creating one manually doesn't work either. Also I don't have the "Enable Automatic Package Restore" setting in my package manager settings as explained here: http://docs.nuget.org/consume/package-restore so I can't try to toggle that setting.

I am using Visual Studio 20013 Update 5 with NuGet version 2.8.60723.765 but the issue also happens in Visual Studio 2015.

**Comment by yishaigalatzer** [comment]
Create the nuget.config at the root of your project (or at the global .nuget folder), here is a  sample https://docs.nuget.org/consume/package-restore/msbuild-integrated

``` xml
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```

In visual studio 2015, this was broken until the 3.2 release scheduled for this month to go RTM, but available today as RC
