### ISSUE TITLE
Update-Package fails when using prerelease versions and multiple sources

### ISSUE THREAD

**Issue by LeroyK** [NuGet/Home#1370]
Update-Package fails under the following conditions:
- VS2015 with NuGet 3.1/3.2-RC.
- Multiple package sources (nuget.org v3, private NuGet server).
- PackageX 0.1.0-pre is hosted on a private NuGet server.
- PackageX 0.1.0-pre has only prerelease versions.
- PackageX 0.1.0-pre depends on a public non-prerelease package (say WindowsAzure.Storage 5.0.0, hosted on nuget.org).
- All packages in the solution are restored.

The following message appears when trying to update WindowsAzure.Storage:

```
PM> Update-Package WindowsAzure.Storage
Attempting to gather dependencies information for multiple packages with respect to project 'MyProject', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for multiple packages
Update-Package : Unable to find package 'PackageX'. Existing packages must be restored before performing an install or update.
At line:1 char:1
+ Update-Package WindowsAzure.Storage
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

**Comment by ashmind** [comment]
Something like this works for me as a workaround:

```
Update-Package WindowsAzure.Storage -Version (version you want) -Pre
```

If `-Pre` is specified, NuGet is able to find that my pre-release package is actually installed. However it obviously affects the version chosen for the package you are updating, so you might want to specify an explicit version.

**Comment by yishaigalatzer** [comment]
Please also verify https://github.com/NuGet/Home/issues/1349 when resolving this issue

**Comment by johnataylor** [comment]
This should be fixed on branch updateBug1370
