### ISSUE TITLE
<vulnerabilityDataSource> in Nuget.config not working if Nuget.org is added as a disabled package source

### ISSUE THREAD

**Issue by gautam-singh2** [NuGet/Home#13716]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.100-preview.7.24407.12

### Impact

I'm unable to use this version

### Repro Steps & Context

I want to use Nuget.org just as a vulnerability source, not as a package source. So, my existing Nuget.config had these lines added in it:

```
<disabledPackageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Microsoft Azure Service Fabric" value="true" />
    <add key="Microsoft and .NET" value="true" />
</disabledPackageSources>
```

According to this comment: https://github.com/NuGet/Home/issues/12698#issuecomment-1606988777, adding this should have allowed me to use Nuget.org as a  vulnerability source but I have been unable to get it to work.

```
<vulnerabilityDataSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  <vulnerabilityDataSource>
```

I have tried this with .NET SDK 8.0.300, 8.0.400 and 9.0.100-preview.7.24407.12, didn't work with any of these. Infact, I observed that adding `<vulnerabilityDataSource>` in my Nuget.config didnt make any difference at all.

Steps to reproduce:

1) Run `cd C:\MyTest`.
2) Run `dotnet new classlib --framework "netstandard2.0" -o MyTest`.
3) Open the .csproj in Visual Studio and add a package reference to System.Formats.Asn1 6.0.0 which has a known high security vulnerability.
After this my .csproj looks like this:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Asn1" Version="6.0.0" />
  </ItemGroup>

</Project>
```
4) Create a global.json file in C:\MyTest to make use of .NET SDK 9.0.100-preview.7.24407.12 (or .NET SDK 8.0.300 or .NET SDK 8.0.401) with these contents:

```
{
  "sdk": {
    "version": "9.0.100-preview.7.24407.12",
    "rollForward": "latestFeature"
  }
}
```
5) Create a NuGet.config in C:\MyTest with these contents:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
	  <add key="RETRACTED 1" value="A VALID V2 URL" />
	  <add key="RETRACTED 2" value="ANOTHER VALID V2 URL" />
  </packageSources>
  <vulnerabilityDataSource>
    <add key="NuGet Vulnerability DB" value="https://api.nuget.org/v3/index.json" />
  </vulnerabilityDataSource>
  <disabledPackageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Microsoft Azure Service Fabric" value="true" />
    <add key="Microsoft and .NET" value="true" />
</disabledPackageSources>
  <activePackageSource>
	  <add key="RETRACTED 1" value="A VALID V2 URL" />
	  <add key="RETRACTED 2" value="ANOTHER VALID V2 URL" />
  </activePackageSource>
</configuration>

```

6) Run `dotnet nuget config get ALL` to get the combined Nuget.config created form all Nuget.config, this is the output I get:

```
C:\MyTest\MyTest>dotnet nuget config get ALL
packageSources:
        add key="RETRACTED 1" value="A VALID V2 URL"
        add key="RETRACTED 2" value="ANOTHER V2 URL"
        add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3"
        add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"

fallbackPackageFolders:
        add key="Microsoft Visual Studio Fallback Folder" value="C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages"

packageRestore:
        add key="enabled" value="True"
        add key="automatic" value="True"

vulnerabilityDataSource:
        add key="nuget.org" value="https://api.nuget.org/v3/index.json"

disabledPackageSources:
        add key="nuget.org" value="https://api.nuget.org/v3/index.json"
        add key="Microsoft Azure Service Fabric" value="true"
        add key="Microsoft and .NET" value="true"

activePackageSource:
        add key="RETRACTED 1" value="A VALID V2 URL"
        add key="RETRACTED 2" value="ANOTHER VALID V2 URL"
```

7) Run this command `dotnet restore MyTest\MyTest.csproj`, the build logs dont report the warnings about the security flaw:

```
C:\MyTest\MyTest>dotnet restore
  Determining projects to restore...
  Restored C:\MyTest\MyTest\MyTest.csproj (in 414 ms).
```

To make this work, I have to remove nuget.org as a disabled package source. This is the output I get after removing nuget.org as a disabled package source from C:\MyTest\NuGet.config:

```
C:\MyTest\MyTest>dotnet restore
  Determining projects to restore...
C:\MyTest\MyTest\MyTest.csproj : **warning NU1903**: Package 'System.Formats.Asn1' 6.0.0 has a known high severity vulnerab
ility, https://github.com/advisories/GHSA-447r-wph3-92pm [C:\MyTest\MyTest\MyTest.sln]
  Restored C:\MyTest\MyTest\MyTest.csproj (in 521 ms).
```

Even if I remove 

```
<vulnerabilityDataSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </vulnerabilityDataSource>
``` 
completely from my NuGet,config, I still get the build warning about security flaw as long as I don't have nuget.org in the list of disabled package sources.

**Comment by gautam-singh2** [comment]
On further digging, I realized that the comment I was referring to was https://github.com/NuGet/Home/issues/12698#issuecomment-1606988777, was more than an year old and later a new spec was created https://github.com/NuGet/Home/blob/dev/accepted/2023/NuGetAudit-without-nuget.org-as-packageSource.md where `<auditSources>` was chosen over `vulnerabilityDataSource`. The spec has already been implemented https://github.com/NuGet/NuGet.Client/pull/5708 and should be available in .NET SDK 8.0.400? Can someone please confirm?

**Comment by gautam-singh2** [comment]
I modified C:\MyTest\NuGet.config used in Step 5) to have these contents (used `auditSources` instead of `vulnerabilityDataSource`):

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
	  <add key="RETRACTED 1" value="A VALID V2 URL" />
	  <add key="RETRACTED 2" value="ANOTHER V2 URL" />
  </packageSources>
  <auditSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </auditSources>
  <disabledPackageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Microsoft Azure Service Fabric" value="true" />
    <add key="Microsoft and .NET" value="true" />
</disabledPackageSources>
  <activePackageSource>
	  <add key="RETRACTED 1" value="A VALID V2 URL" />
	  <add key="RETRACTED 2" value="ANOTHER V2 URL" />
  </activePackageSource>
</configuration>
```

Tried with .NET SDK 8.0.400 and .NET SDK 9.0.100-preview.7.24407.12, it still didnt show the warning about security flaw unless I removed nuget.org from the disabled package sources list.

**Comment by gautam-singh2** [comment]
I finally got it to work when I changed the key name in `auditSources` to be different from the key name in `disabledPackageSources`. It didnt work with .NET SDK 8.0.400 though, only with .NET SDK 9.0.100-preview.7.24407.12. This might be expected though since the change https://github.com/NuGet/NuGet.Client/pull/5708 might not be released as part of .NET SDK 8.0.400?

**Comment by zivkan** [comment]
@gautam-singh2 the feature was not implemented early enough to make it into the .NET 8 SDK (not even 8.0.400).  But you can use the .NET 9 SDK to build projects targeting .NET 8, and therefore benefit from the stability of .NET 8's LTS status for your apps, while still using the latest build tools

I always recommend looking at our official docs before looking at github issues, or design specs that are written before the feature is implemented. I can't control where search engines will point you to, but hopefully over time the official docs will get better search rankings than github issues.

* [audit sources docs](https://learn.microsoft.com/nuget/concepts/auditing-packages#audit-sources)
* [nuget.config reference](https://learn.microsoft.com/nuget/reference/nuget-config-file#auditsources)
   * Looks like I forgot to mention which version of NuGet auditSources are available in, so I created a pull request: https://github.com/NuGet/docs.microsoft.com-nuget/pull/3334
