### ISSUE TITLE
When using latest nuget gui in vs2015 we see "net4" as target version

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1371]
_From @wallymathieu on September 10, 2015 7:23_

Should target framework match the documentation:

https://docs.nuget.org/create/enforced-package-conventions#common-framework-and-profile-targeting-examples

Or

https://docs.nuget.org/create/nuspec-reference

where net40 is mentioned, but in the packages.config:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AutoFixture" version="3.21.0" targetFramework="net4" userInstalled="true" />
  <package id="AutoFixture.Xunit" version="3.21.0" targetFramework="net4" userInstalled="true" />
  <package id="xunit" version="1.8.0.1549" targetFramework="net4" userInstalled="true" />
  <package id="xunit.extensions" version="1.8.0.1549" targetFramework="net4" userInstalled="true" />
</packages>
```

_Copied from original issue: NuGet/NuGetGallery#2668_

**Comment by yishaigalatzer** [comment]
This is by design, because we don't have hardcoding for the TFMs and they are normalized.

Yes there is a difference, but it is expected and it will work with Visual Studio 2013.
