### ISSUE TITLE
IVsPackageInstaller.InstallPackage should include pre-release packages

### ISSUE THREAD

**Issue by urasandesu** [NuGet/Home#1372]
In NuGet3, `IVsPackageInstaller.InstallPackage` has become the behavior that excludes any pre-release packages. This API can't be specified the flag whether including pre-release packages, so I guess that current behavior is unintended.

The differences between NuGet2 and NuGet3 are in the following:
- NuGet2
  https://github.com/NuGet/NuGet2/blob/dev/src/VisualStudio/Extensibility/VsPackageInstaller.cs#L161
- NuGet3
  https://github.com/NuGet/NuGet.VisualStudioExtension/blob/dev/src/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstaller.cs#L360

**Comment by emgarten** [comment]
That flag is equivalent to the include prerelease check box in the UI. If no version is given the API will install the highest stable version. Prerelease packages can be installed by passing in the prerelease version to the API.

**Comment by urasandesu** [comment]
OK. I understood that this behavior is a breaking change from NuGet2. 
However, how do I get the newest pre-release package programmatically? I think that there are no such features in [Extensibility](https://github.com/NuGet/NuGet.VisualStudioExtension/tree/dev/src/NuGet.VisualStudio.Implementation/Extensibility)...

**Comment by emgarten** [comment]
What is the scenario where this is needed? Is this part of an extension?

**Comment by urasandesu** [comment]
Yes. As you pointed out, I'm using this API in my [Visual Studio Extension](https://github.com/urasandesu/Prig/blob/a7da3d4ae962fbf54fdab4c967bdd0ca7d2cd9d2/Urasandesu.Prig.VSPackage/PrigPackageController.cs#L274). It resolves some dependecies in background at the first time of use.

**Comment by emgarten** [comment]
It's generally a bad idea to have an extension depend on the latest version of an online package. This usually leads to unexpected behavior when the package updates and the user is using an older version of the extension that isn't expecting the change.

**Comment by urasandesu** [comment]
That's is exactly right, but it is unneeded in my case. Because the dependencies are all mine. 
You said, 

> Prerelease packages can be installed by passing in the prerelease version to the API.

but it makes cost to manage the version of such packages doubly. That is really tiresome :tired_face:

**Comment by urasandesu** [comment]
I reviewed my build process and succeeded to minimize the above cost. So the API behavior  is no longer needed to revert. I am sorry for making noise :disappointed:
