### ISSUE TITLE
Directoy.packages.props not being loaded when building on Linux

### ISSUE THREAD

**Issue by davidKolar175** [NuGet/Home#13728]
## Description
Hello, I have a repository where I newly added `Directory.packages.props` file to have a centralized package management. The problem is that build on my Linux machine is not working while Windows and Mac build with no issue. I do believe that I am using appropriate versions of dotnet sdk. At the end of the build I'm getting error:

```
/home/kolard/Desktop/TEAF/Server2/Src/TescoSW.Server2.MinimalAPIDemo/TescoSW.Server2.MinimalAPIDemo.csproj : error NU1107: Version conflict detected for Microsoft.OData.Edm. Install/reference Microsoft.OData.Edm 7.6.0 directly to project TescoSW.Server2.MinimalAPIDemo to resolve this issue.  [/home/kolard/Desktop/TEAF/Server2/Src/TescoSW.Server2.sln]
```

This is caused by by the msbuild not knowing, what version of referenced packages it should use. And as I said, the same repository build on any other platforms is build without issue.

### NuGet Product Used
dotnet.exe

### Product Version
OS: AlmaLinux 9.4 and also Ubuntu 20.04.6 LTS

.NET SDKs installed:
  6.0.425 [/home/kolard/dotnet/sdk]
  8.0.401 [/home/kolard/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [/home/kolard/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [/home/kolard/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [/home/kolard/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [/home/kolard/dotnet/shared/Microsoft.NETCore.App]

### Impact
I'm unable to use this version

### Repro Steps & Context
Just create new Console app, add Direcory.packages.props and use any nuget package. Then build the solution and you will most definitelly have warning in the console about incorrect version of dotnet.

```
/home/kolard/Desktop/ConsoleTest/ConsoleTest.csproj : warning NU1604: Project dependency Moq does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [/home/kolard/Desktop/ConsoleTest/ConsoleTest.generated.sln]
```

## Ms

**Comment by zivkan** [comment]
@davidKolar175 try renaming the file to `Directory.Packages.props`.  Linux filesystems are usually case sensitive, so the little `p` is probably the problem:

https://github.com/NuGet/NuGet.Client/blob/15991039d603b8da5d2603315fc9c5c2cfb91a07/src/NuGet.Core/NuGet.Build.Tasks/NuGet.props#L30

**Comment by davidKolar175** [comment]
Oh my god... what a silly mistake. Thank you very much! You saved me from headache. <3
