### ISSUE TITLE
[Bug Bash] Expected error disappear and restore will be successful after the TLS certificate validation is re-enabled

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#13733]
### NuGet Product Used

dotnet.exe

### Product Version

.NET SDK Version: 9.0.100-rc.2.24420.21

### Worked before?

It is not a regression since it is a new feature.

### Impact

It bothers me. A fix would be nice

#### Repro Steps:
1.	[Patch  dotnet  SDK](https://microsoft.sharepoint.com/teams/NuGet/_layouts/15/Doc.aspx?sourcedoc={8a3c6685-1661-47f4-8807-b765ca62aea1}&action=edit&wd=target%28Package%20Signing%20Manual%20Test.one%7C0344a15b-01b1-4828-af4c-63fe53687f8a%2FPatch%20dotnet%20SDK%7Cfd0e3c41-e7a8-4de8-b83a-1a09fdb56271%2F%29&wdorigin=703) (patch 9.0.1xx with Nupkgs of the NuGet build you are testing). 
2.	Open a command prompt (called prompt1), go to the PatchedSDK folder and create a .NET SDK project with command `dotnet new console  -n NetCoreConsole `
3.	In the solution folder, create a file named nuget.config with the following content: 
```
<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
  <packageSources> 
    <clear /> 
    <add key="mySource" value="https://127.0.0.1:44444/v3/index.json"/> 
  </packageSources> 
</configuration> 
```
4.	Open the .csproj file for your project and insert the following package reference within an ItemGroup: 
```
<ItemGroup> 
  <PackageReference Include="abcdefghijkl" Version="1.0.0" /> 
</ItemGroup> 
```
5.	Open the "...\Entropy\filebackedserver\filebackedserver\filebackedserver.csproj" and update the <TargetFramework> property to 'net9.0'. 
6.	Open a second command prompt (called prompt2), go to the PatchedSDK folder and build the server by running:  
`dotnet build   ...\Entropy\filebackedserver\filebackedserver\filebackedserver.csproj `
7.	Start the local server by executing: 
`dotnet run --project  ...\Entropy\filebackedserver\filebackedserver\filebackedserver.csproj `
8.	Switch back to the first terminal where your original project is located (prompt1) and run 
`dotnet restore …\NetCoreConsole.csproj `
9.	Modify the nuget.config file to disable TLS certificate validation as follows: 
```
<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
  <packageSources> 
    <clear /> 
    <add key="mySource" value="https://127.0.0.1:44444/v3/index.json" disableTLSCertificateValidation="true"/> 
  </packageSources> 
</configuration> 
```
10.	 Run dotnet restore again: `dotnet restore …\NetCoreConsole.csproj`
11.	Modify the nuget.config file to re-enable the TLS certificate validation as follows: 
```
<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
  <packageSources> 
    <clear /> 
    <add key="mySource" value="https://127.0.0.1:44444/v3/index.json" /> 
  </packageSources> 
</configuration> 
```
12.	Run dotnet restore again: `dotnet restore …\NetCoreConsole.csproj`
#### Expected Result:
This should result in a "TLS validation failed" error or "Unable to load the service index" error in step12 as the screenshot below.
![image](https://github.com/user-attachments/assets/81d2ef03-362b-4741-9c29-b7ce1fff6396)
#### Actual Result:
No error shows and restoring is successful in step12.
![image](https://github.com/user-attachments/assets/ef0c3229-9caa-40f4-a5c0-3d87380bd00b)

#### Notes:
1.Repro rate: 100%
2.The feature works well in step8 (the expected error shows). if you re-enable the TLS certificate validation, it will fail. This doesn't make sense.

**Comment by nkolev92** [comment]
Is `abcdefghijkl` ever created? Does it exist?

**Comment by v-luzh** [comment]
Hi @nkolev92, yes it created after doing step10. But before doing step11, I deleted the package, after doing the step12, we got the same result as the screenshot above in "Actual Result" part.

And we also tried deleting all the "PatchedSDK"/"Entropy" folder and redo the testing from step1. We got the same result as "Actual Result", even after step8. In other words, the VM will be abandon if it has already run the “TLS certificate validation” test case.

**Comment by jeffkl** [comment]
@v-luzh can you please run the restore/repro steps again with the binary logger (`-bl`) and attach the `msbuild.binlog`?  I wonder if no-op restore is running.

**Comment by v-luzh** [comment]
Hi @jeffkl, the [msbuild.binlog](\\mlangfs1\Public\NuGet\Jamie\Bug13733) file is attached.

**Comment by jeffkl** [comment]
[msbuild.zip](https://github.com/user-attachments/files/17193608/msbuild.zip)
Attaching the binlog here.  It shows a no-op restore so I guess NuGet is not taking into account the value of `disableTLSCertificateValidation` in the NuGet.config, most likely its just looking at feeds.  I'll mark this appropriately for team triage.

**Comment by nkolev92** [comment]
Team Triage: 

Currently, changing disableTLSCertificateValidation in the nuget.config file does not defeat no-op.
We think that's acceptable. 

If you attempt to install a package in step 12 or delete the obj folder before running restore, you should get the expected error. 
We can talk offline if you still have questions.

**Comment by v-luzh** [comment]
@nkolev92, OK, got you. Make sense for me and no more questions, thanks for the info.
