### ISSUE TITLE
VS Package Manager adds version to legacy project files using CPM

### ISSUE THREAD

**Issue by FXZFun** [NuGet/Home#13730]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

Visual Studio 17.11.1, NuGet 6.11.0.119

### Impact

It's more difficult to complete my work

## Description
When updating dependencies in solutions using central package management, projects that still use the legacy project file format with `PackageReference` do not update properly using the Visual Studio Package Manager UI. 

- **SDK-style projects**: Update correctly, with only the `Directory.Packages.props` file changing.
- **Legacy-style projects**: Reintroduce the `Version` element into the project file during the update, causing `NU1008` errors.

These errors must be manually corrected by opening the project file, removing the version, and then reloading the project.

## Steps to Reproduce
1. Open a solution with both SDK-style and legacy-style projects. ([Sample Project](https://github.com/user-attachments/files/16714096/CPMUpdateBug.zip))
2. Use central package management to update dependencies.
3. Observe the changes:
   - SDK-style projects: Only `Directory.Packages.props` file is updated.
   - Legacy-style projects: `Version` element is added back into the project file.

### Expected Behavior
- Both SDK-style and legacy-style projects should update dependencies correctly without reintroducing the `Version` element.

### Actual Behavior
- Legacy-style projects reintroduce the `Version` element, causing `NU1008` errors.

### Workaround
- Manually open the project file, remove the `Version` element, and reload the project.

## Attachments
- Screenshot illustrating the issue:
![image](https://github.com/user-attachments/assets/42f28660-975c-4e5a-9c57-4e9d27bc973e)
 - Sample Repro Project: [CPMUpdateBug.zip](https://github.com/user-attachments/files/16714096/CPMUpdateBug.zip)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/9521.

Known limitation for legacy projects at this point.
