### ISSUE TITLE
Package Manger output and VS status bar restore updates are not available on solution load

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13756]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS 17.12

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

When opening a solution on VS load, if you open a solution where restore takes a long time (say there are many packages that need to be downloaded), then VS's background tasks shows that IntelliSense is taking "forever" to finish (because it's waiting for restore to finish), but restore doesn't show the usual messages on the status bar.

Similarly, if you open the Output window, "Package Manager" is not an option in the dropdown, until AFTER the first restore is complete.

If you try to build the solution while VS is seemingly doing nothing, the VS status bar will go to 50%, but then not mode. The Build output window doesn't show any build output, making it look like VS is frozen.

**Comment by nkolev92** [comment]
What are the usual messages on the status bar that are missing, in other words, what you have liked to see?

Has this changed?

**Comment by nkolev92** [comment]
I tried 5-6 times on our solution forcing to download all the packages. 

I'm not really getting a repro. It could be that it's been fixed or it could be that it's just that intermittent.

**Comment by nkolev92** [comment]
We can't repro this for now. 

We can reopen if it happens again.
