### ISSUE TITLE
As of Windows 10 build 10540 init.ps1 fails to execute

### ISSUE THREAD

**Issue by JerryNixon** [NuGet/Home#1376]
It is important to note that my ps1 only has a comment in it, and no commands. It was working last night, and with the upgrade this morning, this is the resulting behavior.

Here's what I am getting.

Successfully installed 'Template10 1.0.3-preview-15091108' to App15
For adding package 'Template10.1.0.3-preview-15091108 : Newtonsoft.Json [7.0.1, )' to project 'App15' that targets 'uap10.0'.
Executing script file 'C:\Users\jerry.nuget\packages\Template10\1.0.3-preview-15091108\tools\Init.ps1'...
& : File C:\Users\jerry.nuget\packages\Template10\1.0.3-preview-15091108\tools\Init.ps1 cannot be loaded because 
running scripts is disabled on this system. For more information, see about_Execution_Policies at 
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:45
- ... rgs+=$_}; & 'C:\Users\jerry.nuget\packages\Template10\1.0.3-preview- ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : SecurityError: (:) [], PSSecurityException
  - FullyQualifiedErrorId : UnauthorizedAccess
    ========== Finished ==========

**Comment by emgarten** [comment]
What is your powershell script execution policy? 
Upgrading Windows 10 caused this change? Or upgrading NuGet caused it?

**Comment by yishaigalatzer** [comment]
@JerryNixon if this is a change in windows, we probably want to flag in their database as well.

**Comment by JerryNixon** [comment]
Before this morning I didn't know there was a ps execution policy.
I certainly did not change it.

**Comment by yishaigalatzer** [comment]
The question is what changed on your box? Did your windows version update, did your nuget extension update? Both?

Sent from my Windows Phone

**Comment by JerryNixon** [comment]
Not sure of the NuGet extension update. If you mean the packet manager extension, I am running 3.1.60724.766 which was installed 8/26/2015. It appears not to have updated. 

That being said, I resolved this manually by executing (as admin):

``` ps
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
```

**Comment by yishaigalatzer** [comment]
I'm closing this issue, but will loop it in with the Windows folks to see why this started all of the sudden.
