### ISSUE TITLE
[Behavior Change] Raise a missing README warning to <NuGetRequireReadMe> is true

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#13765]
### NuGet Product(s) Affected

NuGet SDK

### Current Behavior

When packing a NuGet project, we warn if a README is missing.

### Desired Behavior

When packing a NuGet project and a project specifies <NuGetRequireReadMe>, we should upgrade to an error if a README is missing.

### Additional Context

https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5039

**Comment by zivkan** [comment]
I think it would be better if we made pack warnings understand `.editorconfig` files, and allow customers to customize pack messages in the same way they can roslyn analyzer messages.

**Comment by baronfel** [comment]
> I think it would be better if we made pack warnings understand .editorconfig files, and allow customers to customize pack messages in the same way they can roslyn analyzer messages.

Good news! This is something you get for free if you implement the pack warnings as MSBuild BuildChecks! Editorconfig-based configuration is a core aspect of the BuildCheck model.

**Comment by nkolev92** [comment]
Which warning are we referring to here?
NU5039 is an error that's only raised when the readme is attempted to be packed, but not succesfully. 

The other part is not a warning, but an info message.

**Comment by zivkan** [comment]
@nkolev92 the title of this issue is to change the info message to a warning.

Adding a `NuGetRequireReadMe` property is not necessary, because once it's a warning, and has an NU code, customers can `<WarningsAsError>` the code, or if we go down the editorconfig route (or MSBuild BuildChecks), then set it in their editorconfig file.

**Comment by nkolev92** [comment]
> @nkolev92 the title of this issue is to change the info message to a warning.

It's not, which is why I asked for a clarification, it's referring to a current warning, but It's also linking NU5039, which if it's about upgrading the message to a warning, NU5039 is not really relevant.

**Comment by JonDouglas** [comment]
> Which warning are we referring to here? NU5039 is an error that's only raised when the readme is attempted to be packed, but not succesfully.
> 
> The other part is not a warning, but an info message.

We need a warning code for missing README. I thought this we did this but I guess we didn't? https://github.com/NuGet/Home/issues/12070

**Comment by nkolev92** [comment]
Thanks for the clarifications. Fixed the title, this is ready for the next triage.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/13633.

**Comment by JonDouglas** [comment]
The request for the standalone property was because we don't have this coded either approach should work.

**Comment by nkolev92** [comment]
> The request for the standalone property was because we don't have this coded either approach should work.

Yes, it's  just consolidating the asks. 
The ideal solution would be one that scales as @zivkan and @baronfel were discussing.
