### ISSUE TITLE
Do not force .NET SDK 8.0.400 to increase minimum version number

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13775]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.400

### Worked before?

8.0.300

### Impact

None

### Repro Steps & Context

https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules

.NET documents 8.0.400 as having a minimum VS version of 17.8. However, because NuGet compiles against a higher version of MSBuild, it doesn't work. (note, [there's a pull request to update the docs](https://github.com/dotnet/docs/pull/42393), which might change it given NuGet broke earlier VS)

NuGet that ships in the 8.0.400 SDK needs to respect the .NET SDK's minimum VS version number.

**Comment by nkolev92** [comment]
Fixed in 6.11.
