### ISSUE TITLE
NuGet Restore is inconsistent about raising NU1201

### ISSUE THREAD

**Issue by namerril** [NuGet/Home#13777]
### NuGet Product Used

MSBuild.exe

### Product Version

MSBuild 17.10.4.21802

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Justification: I'm attempting to build a package that depends on several different tools packages.  These tools packages are built in the same repo and produce a package that is target framework independent.  They are *not* dotnet tools.

For simplicity, I have the following projects:

Parent.csproj:
```<Project Sdk="Microsoft.Build.NoTargets">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageId>Parent.Package</PackageId>
    <NoWarn>NU5128</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Child1\Child1.csproj" ReferenceOutputAssembly="true" />
    <ProjectReference Include="..\Child2\Child2.csproj" ReferenceOutputAssembly="true" />
  </ItemGroup>
</Project>
```

Both Child.csproj projects look like the following:

```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Child1</AssemblyName>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>NU5128</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="$(OutputPath)\$(AssemblyName).exe" PackagePath="tools" Pack="true" />
  </ItemGroup>
</Project>
```

EXCEPT Child2.csproj targets net6.0 instead of net472.

The net6.0 target framework causes the following error: `error NU1201: Project Child2 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Project Child2 supports: net6.0 (.NETCoreApp,Version=v6.0)`.  If I remove the dependency to Child2, I get a package with the dependency to Child1 in the netstandard2.0 target framework, as expected.

This is confusing to me.  Netstandard2.0 is not compatible with BOTH net6.0 and net472.  However, only net6.0 throws the error?

My real goal is to add the project references as a dependency to the NuGet, ignoring the target framework being used to build the tools DLL.  Is this possible?

**Comment by jeffkl** [comment]
I believe that .NET Framework is compatible with .NET Standard due to [.NET Framework compatibility mode](https://learn.microsoft.com/en-us/dotnet/core/porting/third-party-deps#net-framework-compatibility-mode).  I also found this in the documentation indicating why .NET 6.0 would not be:

https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#net-5-and-net-standard
