### ISSUE TITLE
Saving PackageManagementFormat throws Nullable object must have a value.

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13773]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

any

### Worked before?

no

### Impact

Other

### Repro Steps & Context

When calling `ApplyChanges` on `PackageManagementFormat` settings , if the nullable property `_showDialogValue` is not set, the attempt to save settings to disk will fail.

1. Create a PackageManagementFormat
2. Do not call a `get` method for `Enabled` property
3. Call `ApplyChanges` and observe the InvalidOperationException

**Comment by kartheekp-ms** [comment]
I think [PackageManagementFormat.ApplyChanges()](https://github.com/NuGet/NuGet.Client/blob/5d08fbd496ee2ce63b50dfe0803edbd9701e1b35/src/NuGet.Clients/NuGet.VisualStudio.Common/PackageManagementFormat.cs#L103-L110) method is referred in the issue description.
