### ISSUE TITLE
Internal Error when requesting ProductDimensionPerformanceReportRequest

### ISSUE THREAD

**Issue by yuuzhan** [NuGet/Home#1377]
I am able to request all of the reports except ProductDimensionPerformanceReportRequest, where I get an internal error.

Is there a way to export the SOAP Header from the C# Nuget?

Contacting Bing Support, they need a SOAP Header to help further.  I can provide a sample console application to help debug the issue.

Code snippet:

System.Threading.Tasks.Task<SubmitGenerateReportResponse> reportSubmitResponseAsync = serviceClientRequest.CallAsync((s, r) => s.SubmitGenerateReportAsync(r), reportRequest);
reportSubmitResponseAsync.Wait();

From Bing Support:
I apologize for the confusion. After thoroughly checking the website, it appears that there is another team on our end who can further assist you in running the SOAP request in your NuGet application.

You can proceed to file an Issue tracker by clicking here so that one of our experts for this tool will be able to get back with you with the instruction for getting the SOAP request for this application. Otherwise, you can also check with them the cause of the error that Ward's getting when he tried to run the "ProductDimensionPerformanceReportRequest" using this application so that they could check for any workaround that they can provide with it.

**Comment by emgarten** [comment]
This doesn't sound like a NuGet issue. Are you having problems with a NuGet package that uses SOAP?

**Comment by yuuzhan** [comment]
No, I think you are correct, it is the Bing Nuget that is causing the issue, not the NuGet system totally.  I just assumed the Bing Support team sent me to the right spot, it would seem I was mistaken!
