### ISSUE TITLE
Clash between development and production config files

### ISSUE THREAD

**Issue by lonix1** [NuGet/Home#13787]
### Discussed in https://github.com/NuGet/Home/discussions/12824

<div type='discussions-op-text'>

<sup>Originally posted by **lonix1** August 18, 2023</sup>
Originally posted on [StackOverflow](https://stackoverflow.com/q/76928790/9971404) without success. Any help would be appreciated.

---

My .net project is built locally by me during development, and remotely by my ci/cd server.

The project has **project-level config** in `myproject/nuget.config`. It is used by my ci/cd server, which provides some environment variables:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>

  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="custom" value="https://example.com/api/nuget/index.json" />
  </packageSources>

  <packageSourceCredentials>
    <custom>
      <!-- env vars provided by pipeline -->
      <add key="Username" value="%USERNAME%" />
      <add key="ClearTextPassword" value="%API_KEY%" />
    </custom>
  </packageSourceCredentials>

  <packageSourceMapping>
    <!-- get other packages from nuget server -->
    <packageSource key="nuget.org">
      <package pattern="*" />
    </packageSource>
    <!-- get own packages from private server -->
    <packageSource key="custom">
      <package pattern="MyOrg.*" />
    </packageSource>
  </packageSourceMapping>

</configuration>
```

My local machine has **user-level config** in `~/.nuget/Nuget/Nuget.Config`, which is the same, except for different credentials:
```xml
  <packageSourceCredentials>
    <custom>
      <add key="Username" value="my_username" />
      <add key="ClearTextPassword" value="my_personal_api_key" />
    </custom>
  </packageSourceCredentials>
```

That works in the ci/cd server, i.e. in production.

But locally (i.e. in development), I get 401/Unauthorized errors when running `dotnet restore` (etc.) - because *the project-level config (which requires extra env vars) overwrites the user-level config*. (I have many other repos with the same issue, so I don't want to export env vars or add stuff to my .bashrc: it's messy, I don't want to do that.)

This seems to be the opposite to how it's typically done, where there is some "default" checked into source control, and it can be customised during development (with overriding config files) and production (with config files or env vars).

How do I do this?</div>

**Comment by jeffkl** [comment]
@lonix1 The project-level config always wins at the moment by design.  There are a few ways to handle this:

1. Don't store credentials in the project-level config and in your CI, add credentials on-the-fly
   `nuget.exe sources -Name custom -Username USERNAME -Password PASSWORD -StorePasswordInClearText`
2. If you're using Azure DevOps, use [NuGetAuthenticate](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/nuget-authenticate-v1?view=azure-pipelines)
3. On your local machine, set the same environment variables that CI uses, `USERNAME` and `API_KEY`

**Comment by zivkan** [comment]
@jeffkl  a better way on CI is to use the convention based environment variables: https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#credentials-in-environment-variables

I don't think we should recommend your suggestions 1 or 3 any longer.
