### ISSUE TITLE
BuildOutputInPackage in combination with TargetPath doesn't work for wildcards

### ISSUE THREAD

**Issue by CoenraadS** [NuGet/Home#13806]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.303

### Worked before?

No

### Impact

It's more difficult to complete my work

### Repro Steps & Context

I am trying to copy a folder into a nuget package, on a multi-targeted project.

My input folder is `Example`, and I want it's content copied into a folder `Example` in the nuget package (for each lib version)

I am following the docs for BuildOutputInPackage: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#advanced-extension-points-to-create-customized-package

I have a .csproj with the following:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48</TargetFrameworks>
  </PropertyGroup>

 <PropertyGroup>
   <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);Example</TargetsForTfmSpecificBuildOutput>
 </PropertyGroup>

 <Target Name="Example">
   <ItemGroup>
     <BuildOutputInPackage Include="$(ProjectDir)Example\**\*.*">
       <TargetPath>Example</TargetPath> // Also tried appending a folder separater character, it has no influence
     </BuildOutputInPackage>
   </ItemGroup>
 </Target>
</Project>
```

Given I have 
- Example/1.txt
- Example/2.txt

Only the first file gets copied when `TargetPath` is present, and msbuild emits a warning: `{File} not added because the package already contains file {TargetPath}`

However if I remove `TargetPath`, all files are copied, but to the root directory.

Workaround:

```
  <Target Name="Example">
    <ItemGroup>
      <Files Include="$(ProjectDir)Example\**\*.*" />
      <BuildOutputInPackage Include="%(Files.Identity)">
        <TargetPath>Example/%(Files.Filename)%(Files.Extension)</TargetPath>
      </BuildOutputInPackage>
    </ItemGroup>
  </Target>
```

**Comment by jeffkl** [comment]
This is currently by design, the `TargetPath` metadata is the fully qualified file path of the destination file and should be unique for each file, otherwise duplicates result in a warning.  

The workaround you listed is the correct option but you'll also need to use %(RecursiveDir) when using `**\*` so that the sub-directory paths are appended.

```xml
<Target Name="Example">
  <ItemGroup>
    <Files Include="$(ProjectDir)Example\**\*.*" />
    <BuildOutputInPackage Include="%(Files.Identity)">
      <TargetPath>Example/%(Files.RecursiveDir)%(Files.Filename)%(Files.Extension)</TargetPath>
    </BuildOutputInPackage>
  </ItemGroup>
</Target>
```

Relevant code: https://github.com/NuGet/NuGet.Client/blob/1e0115a608073be2ad615201be30b93dd628300d/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L450-L507
