### ISSUE TITLE
Transitive analyzers/source generators flow through by default?!

### ISSUE THREAD

**Issue by aradalvand** [NuGet/Home#13813]
### NuGet Product Used

dotnet.exe

### Product Version

8.0.100

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

It's mentioned in the official documentation that the default value of `PrivateAssets` for a `<PackageReference>` is `contentfiles;analyzers;build` — see [this](https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets:~:text=contentfiles%3Banalyzers%3Bbuild); which, as far as I understand, is supposed to mean that if:

1. Project `A` references package `B`
2. Package `B` references package `C` containing analyzers/source generators
Then the analyzers/source generators from `C` would not flow through to `A`.

This, however, doesn't seem to be the case, which I find perplexing. Here's a minimal reproduction: https://github.com/aradalvand/nuget-transitive-analyzer-test

Steps to reproduce:
1. `git clone https://github.com/aradalvand/nuget-transitive-analyzer-test`
2. `dotnet build`

Here is the `ThePackage`'s `.nuspec` contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ThePackage</id>
    <version>1.0.0</version>
    <authors>ThePackage</authors>
    <description>Package Description</description>
    <repository type="git" />
    <dependencies>
      <group targetFramework="net8.0">
        <dependency id="Riok.Mapperly" version="3.6.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```
Notice `exclude="Build,Analyzers"`.

However, when you run `dotnet build` on the repro linked above, to build the `ConsumingThePackage` project, you'll see that Mapperly's source generators (which was referenced in `ThePackage`) are actually run in `ConsumingThePackage`. This is precisely against what `exclude="Build,Analyzers"` suggests.

What am I missing?! This is extremely surprising, given what the docs say.

**Comment by zivkan** [comment]
Duplicate of https://github.com/NuGet/Home/issues/6279

From the first comment: https://github.com/NuGet/Home/issues/6279#issuecomment-350838039

> Analyzers were added without work being done on the NuGet side originally.

Since analyzer discovery was implemented without NuGet, it doesn't know about exclude assets.

I have no idea why NuGet defaults to excluding analyzers by default, when it doesn't even do analyzer asset selection.  I imagine it's going to make implementing it very difficult, while also maintaining backwards compatibility. That choice was made years before I joined the team.

**Comment by aradalvand** [comment]
> Since analyzer discovery was implemented without NuGet, it doesn't know about exclude assets.

@zivkan Wow, that's shocking to hear given that there is a **documented** "analyzers" options for `PrivateAssets` and `exclude`.
This is a failure of communication at best; I think the fact that NuGet basically has no control over analyzers (at least until #6279 is implemented) should definitely be made clear in the docs.

> it's going to make implementing it very difficult, while also maintaining backwards compatibility

It's a mess, but the sanest route would be to make the breaking change and not let analyzers flow through by default (similar to what seems to have been intended from the beginning — albeit left unimplemented — according to the documentation); while also communicating said breaking change clearly to users.
The more this is postponed the more tricky the situation gets.
