### ISSUE TITLE
NuGet fails to decompress NuGet packages, which are created with a newer ZIP version

### ISSUE THREAD

**Issue by magicmonty** [NuGet/Home#1381]
## Background

I use [Paket](https://github.com/fsprojects/Paket) to create my packages. Paket uses the `System.IO.Compression.ZipArchive` class to create NuGet packages. This works fine under Windows. But if I create my package under Mono, I get a (valid) Archive with a "Version needed to extract" (Bytes 5 and 6) of `0x003F` (Zip Version 6.3) instead of `0x0014` (Zip Version 6.3), which is created by the Windows version. This is because the implementation in Mono is newer and writes this Version hard coded into the header.
## The Problem

NuGet uses the fairly old `System.IO.Packaging` namespace to decompress the nuget package:
(see ~~https://github.com/NuGet/NuGet2/blob/dev/src/Core/Packages/ZipPackage.cs#L142~~
https://github.com/NuGet/NuGet2/blob/dev/src/Core/Packages/OptimizedZipPackage.cs#L193)
With a nuget package, created under Mono this line throws a NotSupportedException, because the `System.IO.Packaging.Package` or the `MS.Internal.IO.Zip.ZipArchive` cannot handle the Version 0x3F (only up to Version 4.5 or 0x002D). This is a problem, when the package is created with a build server like Travis-CI.

StackTrace (sorry, in German):

```
   bei MS.Internal.IO.Zip.ZipArchive.VerifyVersionNeededToExtract(UInt16 version)
   bei MS.Internal.IO.Zip.ZipIOLocalFileHeader.Validate()
   bei MS.Internal.IO.Zip.ZipIOLocalFileHeader.ParseRecord(BinaryReader reader, Encoding encoding)
   bei MS.Internal.IO.Zip.ZipIOLocalFileBlock.ParseRecord(BinaryReader reader, String fileName, Int64 position, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
   bei MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
   bei MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
   bei MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
   bei MS.Internal.IO.Zip.ZipArchive.GetFiles()
   bei System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   bei System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   bei System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   bei System.IO.Packaging.Package.Open(Stream stream)
   bei NuGet.OptimizedZipPackage.EnsureManifest() in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Packages\OptimizedZipPackage.cs:Zeile 195.
   bei NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Packages\OptimizedZipPackage.cs:Zeile 87.
   bei NuGet.LocalPackageRepository.OpenPackage(String path) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\LocalPackageRepository.cs:Zeile 350.
   bei NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\LocalPackageRepository.cs:Zeile 297.
   bei NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext() in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\LocalPackageRepository.cs:Zeile 254.
   bei NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1 items) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Extensions\CollectionExtensions.cs:Zeile 11.
   bei NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\LocalPackageRepository.cs:Zeile 230.
   bei NuGet.LocalPackageRepository.FindPackagesById(String packageId) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\LocalPackageRepository.cs:Zeile 158.
   bei NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository, String packageId) in C:\Users\martingondermann\Desktop\test\NuGet2\src\Core\Repositories\PackageRepositoryExtensions.cs:Zeile 179.
   bei NuGet.Commands.InstallCommand.GetLastestPackageVersion(IPackageRepository repo, String id, Boolean allowPrereleaseVersions) in C:\Users\martingondermann\Desktop\test\NuGet2\src\CommandLine\Commands\InstallCommand.cs:Zeile 346.
   bei NuGet.Commands.InstallCommand.<>c__DisplayClass38_0.<GetLatestVersionPackageByIdFromAggregateRepository>b__1(Object state) in C:\Users\martingondermann\Desktop\test\NuGet2\src\CommandLine\Commands\InstallCommand.cs:Zeile 369.
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
```

**Comment by yishaigalatzer** [comment]
A few questions
1. What version of NuGet are you using? In NuGet 3.X we have moved most of the code (didn't check if all of it) to use Zip Archive
2. Why do you think this is a NuGet fix? There are many clients out there, and even if NuGet fixes this, you still created a package only compatible with newer clients, which seems like a severe limitation and you will theoretically have to provide a minclientversion header, except that wouldn't actually work. So again I'd think you want the fix in paket (or Mono) on the packing side rather then just NuGet the client. thoughts? CC // @forki
3. This is something we want to consider when we build the NuGet xplat pack, to make sure we build compatible packages with all clients. CC // @emgarten 

Moving to backlog for now, and we will gladly take a PR.

**Comment by yishaigalatzer** [comment]
Talking to @pranavkm here, this _should_ work already in NuGet 3.2, could you please verify with your package? seems there is nothing to do on NuGet side once you validate, because we can't go back in time and fix clients out there :)

**Comment by yishaigalatzer** [comment]
Closing, but open to more discussion.

**Comment by pranavkm** [comment]
@yishaigalatzer, I think this problem will persist for OData based feeds - it uses NuGet.Core which uses System.IO.Packaging APIs.

**Comment by yishaigalatzer** [comment]
ah ok, but at that point you won't be able to upload it to the server either...

So keeping this issue around, to move off System.IO.Packaging when reading from a V2 server

**Comment by nkolev92** [comment]
Please open another bug if this is still an issue. 
Thank you.
