### ISSUE TITLE
Only nupkg-files gets included as pending changes

### ISSUE THREAD

**Issue by paululvinius** [NuGet/Home#1383]
When adding new packages with VS2015 and Nuget 3.1, files are missing in pending changes. Only nupkg-files are included:
![capture](https://cloud.githubusercontent.com/assets/854330/9850045/519beb04-5af0-11e5-942c-6819bb9f77c8.JPG)

With VS2013 and Nuget 2.8, all the files are included:
![capture2](https://cloud.githubusercontent.com/assets/854330/9850057/68a3f5b2-5af0-11e5-8909-6ed01d179378.JPG)

We don't have the automatic package restoring feature enabled, so we're depending on the dlls being checked in. The missing dlls are easily missed by developers checking in, and this causes our builds to fail. Can this behavior be changed in VS2015 so that files aren't missing when checking in new packages?

Thanks!

/Paul

**Comment by emgarten** [comment]
There have been some TFS fixes in nuget 3.2.0, will you try the latest RC and see if it resolves your issue?
http://blog.nuget.org/20150902/nuget-3.2RC.html

**Comment by paululvinius** [comment]
Nice, now it works. I guess Nuget 3.2 RC did the trick. Thanks! :)
/Paul
