### ISSUE TITLE
I cannot run Windows PowerShell as an administrator.

### ISSUE THREAD

**Issue by DocCoCauBai-00** [NuGet/Home#13831]
### NuGet Product Used

Other/NA

### Product Version

windows powershell v1

### Worked before?

v1

### Impact

Other

### Repro Steps & Context

Windows PowerShell terminated with the following error:
 The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

[process exited with code 4294901760 (0xffff0000)]
You can now close this terminal with Ctrl+D, or press Enter to restart.

### Verbose Logs

```shell
Windows PowerShell terminated with the following error:
 The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

[process exited with code 4294901760 (0xffff0000)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by martinrrm** [comment]
Hi! This looks like a PowerShell error; I would suggest opening an issue ticket in their repo. https://github.com/PowerShell/PowerShell
