### ISSUE TITLE
Advice on the preferred method for fixing vulnerable package references

### ISSUE THREAD

**Issue by aetos382** [NuGet/Home#13839]
### NuGet Product(s) Involved

Visual Studio Package Management UI, dotnet.exe

### The Elevator Pitch

There are some feature suggestions for how to fix vulnerabilities of a referenced package in dotnet CLI and Visual Studio.

For example, let's say my project has following dependencies.
`My App -> Package A -> Package B`

The version 1.0 of Package B is vulnerable, and this vulnerability has been fixed in the version 1.1.
The version 1.0 of Package A references the version 1.0 of Package B.
And when the new version 1.1 of Package A is released, it will reference the version 1.1 of Package B.

Even if the version 1.0 of Package A itself is not vulnerable, it is indirectly vulnerable because it references vulnerable Package B.
However, nuget.org does not always report that the version 1.0 of Package A is vulnerable.

For example, [the version 5.15 of the Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.1.5) is not marked as vulnerable, but [the version 1.10.3 of Azure.Identity package ](https://www.nuget.org/packages/Azure.Identity/1.10.3)it references is vulnerable.
Even if a newer, non-vulnerable version of `Azure.Identity` package will be install, if minimum requirements specify a vulnerable version, it should still be displayed as having an indirect vulnerability.

In this case, I can choose from two options.

1. Update the version of Package A to 1.1, which indirectly references version 1.1 of Package B.
2. While referencing version 1.0 of Package A, directly reference version 1.1 of Package B.

In this case, I would first like to choose option 1 (if vulnerabilities is still not resolved, I will reluctantly choose option 2).

However, current dotnet CLI and Visual Studio only indicate that Package B is vulnerable, and do not indicate that updating only Package A will resolve issues.
If I follow tool's advice and directly reference the version 1.1 of package B, and then decide to reference the version 1.1 of package A for reasons other than fixing vulnerabilities, I no longer need to directly reference package B, but the reference is not deleted automatically.

There are several suggestions to resolve this situation.

* nuget.org should reliably report that if a dependency package is vulnerable, then higher-level packages that reference it are also vulnerable.
* The `dotnet list package` command should provide `-–tree` option to display dependency tree, to help identify which higher-level packages reference vulnerable packages (the `––include-transitive` option is automatically enabled when the `––tree` option is used). If the `--vulnerable` option is also specified, this command will display reference paths from application to vulnerable packages.
* I want to be able to set a policy for fixing vulnerabilities of indirectly dependent packages, either by directly referencing them or by trying to update packages that are closer to application first, in csproj or NuGet.config.

**Comment by nkolev92** [comment]
Hey @aetos382, please refer to https://devblogs.microsoft.com/nuget/nugetaudit-2-0-elevating-security-and-trust-in-package-management/#recommended-way-to-resolve-warnings for details. 

We're always working on improving audit capabilities, so you should follow https://github.com/NuGet/Home/issues/13372.
