### ISSUE TITLE
[Bug Bash] There is a message “not available in this source” and incorrect package icon for the recommended package “RestSharp” in “Brower” tab of the non-SDK project-level PM UI

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13863]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.13.0.26

### Worked before?

It is a regression since it doesn't repro on D16.11\34601.136 with implicit NuGet Client 5.11.6.4 and D17.11.5\35327.3 with implicit NuGet Client 6.11.1.2. 

### Impact

None

#### Notes:   

1. The repro rate is 100%.  
2. This issue doesn’t repro when searching the package in the search box as below: 
![1017-1](https://github.com/user-attachments/assets/e2e0433c-fa9f-477c-b65f-f9f2117a6aff)
#### Repro Steps:    

1. Create a C# Console App (.NET framework) project.    

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open PM UI and select “nuget.org” in the “Package source” dropdown list.    

3. Switch to “Brower” tab and observe the recommended package “RestSharp” in packages list. 
#### Expected:    

There is no message “not available in this source” under the recommended package “RestSharp” and the package icon should be correct. 

#### Actual:    

There is a message “not available in this source” under the recommended package “RestSharp” and the package icon is incorrect as below screenshot:  
![1017](https://github.com/user-attachments/assets/1f5f8f3f-87b7-4075-a3e2-5ca26aad3132)

**Comment by jeffkl** [comment]
@CiciLi1 I think this might be intermittent, I'm not able to reproduce the problem.  Can you try it a few more times and tell me if it only happens some of the time?

**Comment by CiciLi1** [comment]
> @CiciLi1 I think this might be intermittent, I'm not able to reproduce the problem. Can you try it a few more times and tell me if it only happens some of the time?

Hi @jeffkl, I verified this issue ten times today on VS Main\35417.73 with implicit NuGet Client Dev\6.13.0.34, the repro rate is 100%.

**Comment by jeffkl** [comment]
6.13.0.34 potentially made some changes to our VSIX, does not not repro with 6.13.0.33?

**Comment by CiciLi1** [comment]
> 6.13.0.34 potentially made some changes to our VSIX, does not not repro with 6.13.0.33?

Hi @jeffkl, it reproduced on Dev\6.13.0.33 as well.
![image](https://github.com/user-attachments/assets/21cb4090-a258-45f1-b74e-f81a90cd110d)

**Comment by jeffkl** [comment]
@nkolev92 maybe you can take a look? I was not able to reproduce the problem on my machine.

**Comment by nkolev92** [comment]
I can repro this. It's a casing issue, I'll submit a fix.

**Comment by CiciLi1** [comment]
Hi @nkolev92, thanks for the fix, the package "swashbuckle" also repro this issue for "C# ASP.NET Web Application (.NET Framework)--MVC" project on Dev\6.13.0.38. could you please help to have look? Thanks.
![image](https://github.com/user-attachments/assets/2ed7b167-437d-4970-9171-6642847d93b8)

**Comment by nkolev92** [comment]
Hey @CiciLi1, I haven't submitted a fix yet. I'm assuming it's the same issue though.
