### ISSUE TITLE
Packages containing nupkgs with the same name fail to extract during UWP restore

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1386]
Packages containing a nupkg with the same name fail to extract since the downloaded nupkg is extracted to same folder.
1. Create a new UWP blank app
2. install-package Revalee.Client -version 2.1.2

The above steps will throw a file in use exception since Revalee.Client.2.1.2.nupkg contains a file Revalee.Client.2.1.2.nupkg. The original nupkg is in use since it is extracting files, while at the same time the extraction is attempting to overwrite the source.

Other packages with the same issue:
- AzureBuildVerifier 1.0.0
- Yammer.Oss.Api 0.1.0.3
- T4Test 1.0.0
- SQLitePortable 2.0.0
- pgn.net 1.1.1.1
- ApiLogFilter.dll 1.0.0

**Comment by yishaigalatzer** [comment]
Suggestion - Make this a warning, and ignore the nupkg file

basically 

``` C#
if (File.Exists(fileNameToExtract))
{
   Log.Warning(...);
}
else
{
   Extract(...);
}
```

**Comment by yishaigalatzer** [comment]
Fixed with https://github.com/NuGet/NuGet3/commit/00053876b86fd29b46bfdaccb76dfd5ceba7701b

@emgarten please close when the 2 commits are ported over to NuGet.Client
