### ISSUE TITLE
The focus border on the Details Pane Tab content is being truncated

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#13879]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

17.13 Preview 1

### Impact

Other

### Repro Steps & Context

With the new tabs introduced to the Details Pane as part of the README work, the focus border on the Details Pane Tab content is being truncated (on the left side in my testing).

![image](https://github.com/user-attachments/assets/44978ab7-d392-4639-ab67-5bb35846aedf)

**Comment by nkolev92** [comment]
@jgonz120 Assigning a couple of bugs related to the Readme work.
