### ISSUE TITLE
NuGet.Versioning.NuGetVersion can incorrectly report `IsSemVer2 == true` when version includes build metadata

### ISSUE THREAD

**Issue by cyungmann** [NuGet/Home#13872]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Versioning 6.11.1

### Impact

It bothers me. A fix would be nice

### Repro Steps & Context

I am attempting to use the `NuGet.Versioning` package to report the version of our code to end-users. However, I am noticing some weirdness with printing version strings:

```csharp
NuGetVersion.Parse("1.2.3.0+abcd").ToString(); // returns 1.2.3
NuGetVersion.Parse("1.2.3.0").ToString(); // returns 1.2.3.0
```

I believe this is a result of the following:

```csharp
NuGetVersion.Parse("1.2.3.4").IsSemVer2; // returns false
NuGetVersion.Parse("1.2.3.4+abcd").IsSemVer2; // returns true, but I would expect false
SemanticVersion.TryParse("1.2.3.4+abcd", out var semVer); // returns false
```

**Is this expected behavior, or should `IsSemVer2` take into account whether it is a four-part version?** Currently, `IsSemVer2` returns `true` whenever the version has build metadata attached to it. This probably used to not matter as much, but with the .NET 8 SDK the `AssemblyInformationalVersionAttribute` now appends commit information by default (see [here](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/source-link)).

**Comment by nkolev92** [comment]
I think this is expected. 

The semver2 is primarily related to metadata. 
Due to the fact that we're building on top of System.Version NuGet accept 4 part versions. 
Semver 1 doesn't support 4 part versions either, so I think the "safe" approach was not try to limit 4 part versions there.
