### ISSUE TITLE
Azure.Core 1.44.1 with bug on Dependency System.Memory.Data 6.0.0 for instruction BinaryData.Empty.ToString()

### ISSUE THREAD

**Issue by Riccardonewall1985** [NuGet/Home#13870]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

.NET 8

### Worked before?

Azure.Core 1.43.0

### Impact

I'm unable to use this version

### Repro Steps & Context

Create console app with .NET 8
Install NuGet package Azure.Core 1.44.1 (with Dependency System.Memory.Data 6.0.0)
Write this code line: string data = BinaryData.Empty.ToString();
Run...
You get: System.ArgumentNullException: 'Value cannot be null. (Parameter 'bytes')'

**Comment by jeffkl** [comment]
Closing this as external, please open a new issue at https://github.com/Azure/azure-sdk-for-net/issues/new for support with that specific package.
