### ISSUE TITLE
Duplicate .nupkg files are added to package folder when adding Nuget packages

### ISSUE THREAD

**Issue by martinsuchan** [NuGet/Home#1387]
I think this is a bug, there should be no reason for two identical .nupkg files in a package folder.
Using NuGet v3.2.60902.10488 in VS2015.

**Repro steps**
Create a Console Application
Install-Package MvvmLightLibs.5.2.0.0
Inspect the packages folder for MvvmLightLibs

**Expected:**
There should be only one MvvmLightLibs nupkg file and one CommonServiceLocator nupkg file in the CommonServiceLocator.1.3 folder.

**Actual:**
There is MvvmLightLibs.5.2.0.nupkg + identical MvvmLightLibs.5.2.0.0.nupkg file in the MvvmLightLibs.5.2.0.0 folder and CommonServiceLocator.1.3.0.nupkg + identical CommonServiceLocator.1.3.nupkg in the CommonServiceLocator.1.3 folder.

**Comment by emgarten** [comment]
I'm not able to repro this. I end up with only MvvmLightLibs.5.2.0.0.nupkg. Are there any other steps needed here? What are your sources?

**Comment by martinsuchan** [comment]
I have just tested it on another machine and reproduced it on first try - have you used the [NuGet Package Manager 3.2 RC](http://blog.nuget.org/20150902/nuget-3.2RC.html)? 

![capture](https://cloud.githubusercontent.com/assets/3041397/9887159/925d20c8-5bee-11e5-9403-5a4dc0c1148e.PNG)

**Comment by emgarten** [comment]
What source is the package coming from?

**Comment by yishaigalatzer** [comment]
@martinsuchan I have a repro using the v3 server `https://api.nuget.org/v3/index.json`

I'm assuming you are not seeing any other issues other than another file dropped on disk?

**Comment by martinsuchan** [comment]
Yes, but it looks like this other file is dropped only when the package version ends with two zeroes, like 5.2.**0.0**. It works fine when the package has three non-zero numbers. Not tested yet when the package has three zeroes.
