### ISSUE TITLE
Trusted signers gets ignored on macOs

### ISSUE THREAD

**Issue by tom171296** [NuGet/Home#13881]
### NuGet Product Used

dotnet.exe

### Product Version

9.0.100-rc.2.24474.11

### Worked before?

-

### Impact

Other

### Repro Steps & Context

- Create a new .net project on a macOs device.
- Add the nuget.config file with trusted signers
- Add a package to the csproj without adding a section to the trusted signers section
- Run `dotnet restore`, this will succeed when I expect the restore action to fail.

**Comment by nkolev92** [comment]
Duplicate of https://github.com/NuGet/Home/issues/11986
