### ISSUE TITLE
Issue during package creation in 'content' folder

### ISSUE THREAD

**Issue by zelex74** [NuGet/Home#1388]
I am trying to create a package of the ASP.NET MVC project (Visual Studio 2013) without .nuspec by command "nuget pack Hive.UI.Web.Shell.csproj".
Сreated package has the following structure
![image](https://cloud.githubusercontent.com/assets/14290419/9872410/b1780fe0-5bb2-11e5-89a6-26cae680885a.png)
I expect to see in the folder 'content' the following composition: Content, Scripts, Views, Web.config.transform. But as you can see 'content' is file, it contains the text of one of css file from 'Content' folder. Why did this happen?
Below is the structure of Hive.UI.Web.Shell.csproj. Red flagged the css file from which the contents fall into the 'content'
![image](https://cloud.githubusercontent.com/assets/14290419/9873041/ab80f06c-5bb6-11e5-96d7-75908c3c6a4b.png)
On another project, such problems do not occur.

**Comment by zelex74** [comment]
Using NuGet v2.8.50126.400

**Comment by zelex74** [comment]
Probably the reason is in the SlowSheetah package. My .csproj file contains the following:
![image](https://cloud.githubusercontent.com/assets/14290419/9903682/b340ad8e-5c91-11e5-87bd-b9107e3db7f0.png)
After the removal of the last line, packaging is done properly.
A similar problem, but the solution did not help me: http://gregorsuttie.com/2015/01/10/issue-i-ran-into-when-using-nugetslowcheetah/

**Comment by zelex74** [comment]
Setting SlowCheetah_EnableImportFromNuGet = false solved my problem.
nuget pack Hive.UI.Web.Shell.csproj -Properties SlowCheetah_EnableImportFromNuGet=false

**Comment by nkolev92** [comment]
Thanks for filing this issue. Apologies for the overdue response. 

At this point, pack has been completely rewritten. 

Please create another issue if you're still running into problems.
