### ISSUE TITLE
Project and package in the same graph with the same name but different dependencies may lead to incorrect versions of the dependencies of that id 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#13888]
Take the following setup:

```
        // Project1 -> (project) ProjectAndPackage 1.0.0 -> Project3 -> Project4 -> PackageB 2.0.0
        //                -> packageA 1.0.0 -> PackageB 1.0.0
        //                                              -> ProjectAndPackage 2.0.0
```

The old algorithm would choose packageB 2.0.0, but the new one chose PackageB 1.0.0.

**Comment by stijnherreman** [comment]
Maybe this should be released as a patch for 6.12 instead? It can break builds, for example when using the 'NuGet tool installer' task in Azure Pipelines with Version set to `6`. (I know that is a risk when specifying only a major version.)
