### ISSUE TITLE
Creating a package for non sdk project with IncludeReferencedProject gives System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by DmitryLukyanov** [NuGet/Home#13899]
### NuGet Product Used

NuGet.exe

### Product Version

NuGet Version: 6.9.1.3

### Worked before?

yes, few months ago

### Impact

I'm unable to use this version

### Repro Steps & Context

Command that I run:

>nuget pack "project.csproj"  -SolutionDirectory "Solution" -PackagesDirectory "Solution/packages"  -IncludeReferencedProjects -OutputDirectory artifacts -Verbosity detailed -Properties Configuration=Debug

the project has references on other nugets as well as on the projects. In some cases I see the output like:

>Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

This command worked few months ago. Also it works if I remove the option `IncludeReferencedProjects`. Any ideas how can it be fixed?

### Verbose Logs

```shell
NuGet Version: 6.9.1.3
Attempting to build package from 'project.csproj'.
MSBuild auto-detection: using msbuild version '17.11.9.46202' from 'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'Solution\Project\bin\Debug'.
Add file 'Solution\Project\bin\Debug\Project.dll' to package as 'lib\net452\Project.dll'
WARNING: NU5118: File 'Solution\DependencyProject\Images\loaderbar.gif' is not added because the package already contains file 'content\Images\loaderbar.gif'
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
Found packages.config. Using packages listed as dependencies
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

**Comment by DmitryLukyanov** [comment]
I'm trying to investigate it via debugging source code, but have issues with running the project described here https://github.com/NuGet/Home/discussions/13900

**Comment by DmitryLukyanov** [comment]
I didn't make many tests, but as I can see the issue is the following. Let's say we have a nuget package called "NugetPackage". Then we have 2 other projects: `Project1` and `Project2`.  Then steps to reproduce is the following:

1. Consume an initial package via `Install-Package` in `Nuget Package Manager` in VS, but with name like `Nugetpackage` (case is different). Result will be successful.
2. Create a nuget package (with `IncludeReferencedProject`) based on `Project1`, let's say `Project1Package`. The nuspec file will have the incorrect case in the NugetPackage dependency definition (Nugetpackage).
3. Then consume `Project1Package` in the `Project2` and then try to create a package `Project2Package`.
This step will fail because going down to dependencies chain he will find the `Nugetpackage` and `NugetPackage` keys which in turns will force this logic fail: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L958. 

Maybe somehow it's my fault that this issue appear, but in any case the thrown error looks fully unsafe. I would at least change the error message here. Ideally, like "we didn't find X, but maybe you meant x?" or anything like this.

>System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

this error is definitely should not happen in this place and it's useless from troubleshooting point of view

**Comment by donnie-msft** [comment]
I'm able to reproduce getting incorrect casing into a PackageReference project, but not a packages.config project. That seems to match what you're describing as well. Were both your consuming and dependent projects packages.config, or was one of them PackageReference?

Using PMC to install this package with random casing, it is reflected here in the Dependencies node in VS:
![image](https://github.com/user-attachments/assets/d1bde27c-2cc3-44d7-b5b5-d3f157f18ceb)


The packages.config file ended up with corrected casing:
![image](https://github.com/user-attachments/assets/aefec5e7-262b-4f7e-8767-0410ebaa79d8)

So, your analysis makes sense to me. I believe there could be a bug with comparing and case-sensitivity. I'm not sure it's a regression since the only changes to the dictionary lookup were https://github.com/NuGet/NuGet.Client/commit/008151dc9bbdb00bbd197744b2531fbf39c1da68#diff-6480a4669dc5a548ef6cecbffee381fbb0ad34a0cac09fbd47e0611a6cb090feR297 and I don't think that lookup behavior has changed. 

Perhaps your scenario changed in recent months? Can you share more about why you mention this worked a few months ago?

**Comment by DmitryLukyanov** [comment]
Thanks @donnie-msft ,

> I'm not sure it's a regression

>Can you share more about why you mention this worked a few months ago?

it's regression on my side, you can ignore this part.

>but not a packages.config project

I had this only for package.config projects (not SDK project type), but I feel like it can appear in both (and I didn't try to reproduce it on SDK projects).

**Comment by nkolev92** [comment]
Duplicate of https://github.com/NuGet/Home/issues/12617.
