### ISSUE TITLE
nuget pack can't handle double backslashes in paths

### ISSUE THREAD

**Issue by martingalvan-volue** [NuGet/Home#13909]
### NuGet Product Used

NuGet.exe

### Product Version

5.9.1.11

### Impact

It's more difficult to complete my work

### Repro Steps & Context

Hi, I'm trying to run nuget pack and see that it will fail to find any files whose paths are specified in a way that contains double backslashes, e.g.:

    C:\Users\martin\build\Release\\my_lib.dll

This is very surprising behavior, since a user would assume nuget pack is able to solve such path specifications correctly as any other tool does.

**Comment by donnie-msft** [comment]
Reproduces for me.

> Error NU5019: File not found: `bin\Debug\\BackgroundPrototype.pdb`.
> NuGet.Packaging.Core.PackagingException: File not found: `bin\Debug\\BackgroundPrototype.pdb`.
>    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
>    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
>    at NuGet.CommandLine.ProjectFactory.ProcessNuspec(PackageBuilder builder, String basePath)
>    at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
>    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
>    at NuGet.CommandLine.PackCommand.ExecuteCommand()
>    at NuGet.CommandLine.Command.ExecuteCommandAsync()
>    at NuGet.CommandLine.Command.Execute()
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/12628.

**Comment by martingalvan-volue** [comment]
@nkolev92 @donnie-msft @jeffkl issue #12628 is only about a specific case where `OutputPath` ends up with a double slash, thus triggering this bug. The real root cause of that issue is this bug; therefore IMHO this one should be open instead of #12628

**Comment by nkolev92** [comment]
@martingalvan-volue 
When we de-duplicate issues we usually use the older issue. 
I have added an additional comment on that issue so that when someone investigates the bug they'll have all the details.
