### ISSUE TITLE
3.2 RC 1 - packages getting added to TFS source control

### ISSUE THREAD

**Issue by thnk2wn** [NuGet/Home#1390]
Tried installing http://blog.nuget.org/20150902/nuget-3.2RC.html to see if it would fix this but did not.

Regardless of .tfignore, any time I install a new package or upgrade an existing package, it gets added to TFS (2013) source control.

Using the automatic (non MS build package restore) and Visual Studio 2015 Enterprise.

It seemed more sporadic with nuget.org packages but definitely seeing it consistently with other package sources (from our TeamCity nuget server). Maybe there's just something I need to setup?

![packgesaddedtosourcecontrol](https://cloud.githubusercontent.com/assets/120529/9918006/6aa649a2-5c79-11e5-8ab1-ba42925308a7.png)

**Comment by emgarten** [comment]
Do you have disableSourceControlIntegration set to true in your nuget.config file?

**Comment by thnk2wn** [comment]
@emgarten I thought that was only for MS build package restore. We've switched over to the automatic package restore. What/where nuget.config for that?

**Comment by emgarten** [comment]
Follow the directions for setting disableSourceControlIntegration  here: https://docs.nuget.org/consume/package-restore

**Comment by thnk2wn** [comment]
@emgarten Thanks. I thought the entire .nuget folder could go away with automatic package restore. That fixed it although it's annoying having to create a .nuget folder, a Nuget.config file and .tfignore file for each app just to prevent packages from being added to source control. I thought part of the new way was "it just works" and this doesn't feel that way.

**Comment by emgarten** [comment]
@thnk2wn the setting can be added to any nuget.config file, it doesn't have to be in the .nuget folder. You could put it in your solution root directory, in a directory above that, or in your machine wide nuget.config file under _%AppData%\Roaming\NuGet_.

NuGet doesn't read .tfignore, if you leave that file out does it still work correctly?

**Comment by thnk2wn** [comment]
Thanks for the info. It seems to require both.

Nuget.config at a higher level may be handy but machine wide requires each team member to do that so it's not so portable. At a higher root level than app may not work in many cases where someone just pulls one app down or just opens the solution without getting a much larger root tree.

Ideally I'd expect this to just default to true (not adding packages into source control which is half the point of Nuget) and if that needs to be changed maybe something at the project file properties or requiring the config then.
