### ISSUE TITLE
[Feature Request] Disable caching for Local Feed

### ISSUE THREAD

**Issue by gioce90** [NuGet/Home#13918]
### NuGet Product(s) Involved

NuGet.exe, NuGet SDK

### The Elevator Pitch

I'm asking the same feature in #8251 , in light of new clearer reasons of which is the common scenario that the feature will resolve.

For local development purposes this feature is a must-have: I exhaustive described [here](https://github.com/NuGet/Home/issues/8251#issuecomment-2468435652) a common scenario, but - shortly - the idea is to give to developers the freedom to works on their local machines using [Local Feeds](https://learn.microsoft.com/en-us/nuget/hosting-packages/local-feeds) without facing cache issues.

This is especially needed when we work on 2 or more local projects, where one is a package project and the other is a project who consumes the package. When a developer make some changes on a package, before to push these changes he wants to test the changes using (in local) other project(s) which consumes the edited package. All of this happens in local and doesn't involve yet the CI/CD pipelines. This is a really common scenario in companies with large codebase and numerous package projects. 
Note that the purpose here is not to skip the CI/CD, but just speed-up the local development.

So the request is: _only and exclusively for packages on the local machine, that the cache should be disabled._

It could be by default or, as suggested [here](https://github.com/NuGet/Home/issues/8251#issuecomment-1260930006), with this configuration:
```
nuget.config

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
     <add key="Local packages for Windows" value="%userprofile%\.nuget\packages\localPackages"  disableCache="True" />
     <add key="Local packages for MacOS" value="~/.nuget/packages/localPackages"  disableCache="True" />
  </packageSources>
</configuration>
```
Of course `disableCache="True"`  should works only for local feeds.

Another solution it can be to operate on the <PackageReference> in the .csproj in this way:
```
<Project Sdk="Microsoft.NET.Sdk">
         ...
	<ItemGroup>
		<PackageReference Include="MyPackage" Version="8.0.0-Local" disableCache="true" />
	</ItemGroup>
</Project>
```

Any other ideas on how to disable cache for packages on the local machine are welcome.

### Additional Context and Details

In local I use to produce a package using this convention: MyPackage.x.y.z-Local ... now, we all knows that increment the version is really important when we are shipping the package, but in local it should not be a serious thing, because is just distracting and a waste of time and focus.
But using just the "-Local" suffix without increment the version means facing cache issues: this should due to _global packages folder_ that keep the old package (I don't think that _http-cache_ is involved).

Note:
- In NuGet there are already several ways to skip cache, but not via .config or .csproj
- Being forced to continuously increment the version number on both the package project and the project that references it, when we are still working locally, is non-sense [IMHO].
- Typically a pre-release version of a package is built via CI/CD related to a feature branch: but being forced to push changes to start this pipeline, only to debug and test locally something a developer isn't entirely sure about, is a waste of time, resources (pipeline agents), and an unnecessary mess of git history. And have to wait the pipeline execution just to take the new pre-release version that then will however tested in local by the other project... is a waste of time and focus.
- Avoiding this cache problem with the use of CLI commands, custom Powershell scripts, Directory.Builds.props (which is my case), clean all the cache manually every time... all of this is a burden that the feature proposed resolves.
- Note that substitute the `<PackageReference>` tag with the more directly `<Reference>` tag in the .csproj of the project who uses the package expose to easy mistakes and compromises other things. 
- A fallback Package Folders doesn't resolve the problem (as initially pointed out in the closed issue).

**Comment by CEbbinghaus** [comment]
> Of course disableCache="True" should works only for local feeds.

I have a problem with this as it needlessly constrains the usage of this feature. Additionally, it conflicts with your proposed "package" syntax `<PackageReference Include="MyPackage" Version="8.0.0-Local" disableCache="true" />`. What if that package was only available from a remote feed? 

Instead, a more general solution that allows disabling caching on either feeds or packages would be preferred. So, a remote feed could have its caching disabled or a singular package within the feed could. This would benefit most for local feeds but there is no reason to limit the design to only it.

**Comment by jeffkl** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/6579

**Comment by gioce90** [comment]
@CEbbinghaus ,  you’re absolutely right — this wasn’t my first choice either.

In my opinion, the best approach would be to place `disableCache="true"` not in the `<PackageReference>` tag, but in an entry under `<packageSources>` in the nuget.config.

I suggested applying it only to Local Feeds because disabling the cache for a remote feed feels a bit unusual to me — after all, there’s a reason the cache exists. That said, it might make sense in specific cases for individual packages?
However, there are already other feature requests open, like #8745  and #5713 .

------

The NuGet team decided to close this feature request in favor of a more generic (and older) issue, which has been open since 2018... In the meantime, I’m working on a solution myself. Once it’s ready, I’ll share it and post it here.

**Comment by gioce90** [comment]
Hi @CEbbinghaus  , I worked on a solution by myself, as I mentioned here and also [here](https://github.com/NuGet/Home/issues/6579#issuecomment-2476832378). 

I’ve now decided to make my solution public by releasing a package called NuJet (https://github.com/gioce90/NuJet). It enhances the inner-loop development and testing process for NuGet packages, especially in local workflows. 

Feel free to check it out—I’d love to hear your feedback!
