### ISSUE TITLE
Add dotnet generation mappings for Xamarin frameworks

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1391]
Currently Xamarin frameworks are allowed to install all dotnet generations. This should be reviewed and the correct dotnet generation mappings should be added to NuGet.Frameworks.

**Comment by yishaigalatzer** [comment]
CC // @lodejard @davidfowl @anurse

**Comment by emgarten** [comment]
I believe this has been solved and nuget will continue mapping dotnet/netstandard to the highest versions of xamarin frameworks.

**Comment by joelverhagen** [comment]
Emailed @ericstj about this who got confirmation from Xamarin on this (mapping highest .NETStandard to Xamarin platforms). Closed.
