### ISSUE TITLE
NuGet package manager does not respect selected "FrameworkVersion" on Update in Package manager UI

### ISSUE THREAD

**Issue by ibe-SAG** [NuGet/Home#13926]
### NuGet Product Used

Visual Studio Package Management UI, dotnet CLI

### Product Version

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current Version 17.12.0

### Worked before?

NO

### Impact

I'm unable to use this version

### Repro Steps & Context

After Release of new .NET Version for example .NET 9.0, it is not possible to Upgrade packages correctly any more.

Example in Directory.Build.props we have following line

`<TargetFramework>net8.0</TargetFramework>`, which is explicitly specify that we want to use only LTS 8.0 version of .NET

If I start update packages to the latest version, there are components offered which support  only .NET 9.0, but not .NET 8.0
Microsoft.AspNetCore.Mvc.NewtonsoftJson version 9.0.0 is only available for .NET 9.0.

This breaks the whole procedure and lead to errors!

Please fix it

### Verbose Logs

```shell
Error message:
Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 9.0.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package Microsoft.AspNetCore.Mvc.NewtonsoftJson 9.0.0 supports: net9.0 (.NETCoreApp,Version=v9.0)
```
The same happens if I run command such as:
` dotnet list .\Example.csproj package --include-transitive --framework=net8.0 --outdated`

Result look like 
```
Project `Example` has the following updates to its packages
   [net8.0]:
   Top-level Package                                           Requested   Resolved   Latest
   Azure.Identity                                            1.12.0      1.12.0     1.13.1
   LigerShark.WebOptimizer.Core                              3.0.422     3.0.422    3.0.426
   Microsoft.AspNetCore.Authentication.JwtBearer             8.0.11      8.0.11     9.0.0
   Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore      8.0.7       8.0.7      9.0.0
   Microsoft.AspNetCore.Identity.EntityFrameworkCore         8.0.7       8.0.7      9.0.0
   Microsoft.AspNetCore.Identity.UI                          8.0.7       8.0.7      9.0.0
   Microsoft.AspNetCore.Mvc.NewtonsoftJson                   8.0.7       8.0.7      9.0.0 <= version 9.0. has no support for net8.0
```

**Comment by JorisVanEijden** [comment]
Duplicate of: https://github.com/NuGet/Home/issues/5725

**Comment by nkolev92** [comment]
@JorisVanEijden is right, duplicate of https://github.com/NuGet/Home/issues/5725
