### ISSUE TITLE
In nuget.exe 3.2 automatic msbuild detection works different from nuget 3.1.beta.exe

### ISSUE THREAD

**Issue by yura-yaroshevich** [NuGet/Home#1392]
When `nuget.exe restore` run without `-MSBuildVersion` parameter automatic `MSBuild` version detection works wrong. According to docs it should select highest available msbuild version (on my machine 14), but it chooses 12 version. It worked correctly on version 3.1.beta http://dist.nuget.org/win-x86-commandline/v3.1.0-beta/nuget.exe, but was broken in 3.2

`MSBuild auto-detection: using msbuild version '12.0' from 'H:\Program Files (x86)\MSBuild\12.0\bin'.`

**Comment by emgarten** [comment]
Does msbuild 14.0 exist under H:\Program Files (x86)\MSBuild\14.0\bin? Do you have Visual Studio 2015 on the machine or was msbuild 14.0 installed separately?

**Comment by mstyura** [comment]
@emgarten yes, it is exists. It was installed as part of VS2015 Pro installation along with Windows UWP SDK. So it is definitely exists on my machine.
UPD: Oops, posted answer from my different account. :|

**Comment by emgarten** [comment]
@yura-yaroshevich would you try running msbuild from the same command line to see which version you get? NuGet uses the highest version on the path.

**Comment by yura-yaroshevich** [comment]
@emgarten on path the higher version of MSBuild is 12. How nuget will work if there is no MSBuild in PATH at all? Is it possible not to be restricted by PATH?

**Comment by yishaigalatzer** [comment]
If you want to control it, you have to use the parameter. In most cases the command line used to call msbuild, is used to call nuget and hence they should be the same.

If you want to opt out, you can use the flag, or control the path environment variable.

We though about doing -msbuildversion Latest, but it is not very useful because of breaking changes between versions of msbuild

**Comment by bunkerdives** [comment]
Just make sure whichever msbuild version you're looking to use has its parent dir listed in your system (not user) path environment var.
