### ISSUE TITLE
[Bug Bash] The “README” tab doesn’t show in the right panel of the PM UI after installing package

### ISSUE THREAD

**Issue by CiciLi1** [NuGet/Home#13924]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

NuGet Client Dev\6.13.0.63

### Worked before?

It’s not a regression since it is a new feature. 

### Impact

It bothers me. A fix would be nice

#### Notes:   

1. The repro rate is 70%.  

2. This issue easily reproes when installing the package for first time. 

3. Clicking the refresh button doesn’t work. 

4. It’s not a regression since it is a new feature. 

#### Repro Steps:    

1. Create a “C# Console App (.NET 9.0)” project.    

2. Right-click the project in Solution Explorer and select "Manage NuGet Packages…" menu item to open the PM UI.    

3. Click “Browse” tab and select the source “nuget.org” from Package source drop-down list. 

4. Install a package (e.g. RestSharp) and switch to “Installed" tab. 

5. Observe the details panel on the right panel of PM UI.  

#### Expected:    

The “README” tab should show in the right panel as below. 
![1114](https://github.com/user-attachments/assets/a20c196e-d38c-42ea-b7f9-d332f46a59e8)
#### Actual:    

The “README” tab doesn’t show in the right panel of the PM UI after installing package as below screenshot:  
![image](https://github.com/user-attachments/assets/a1a4f1e5-0d5f-48b5-98ce-721038486ee2)

**Comment by martinrrm** [comment]
@jgonz120 FYI not sure if you are aware of this bug

**Comment by jgonz120** [comment]
I thought I responded to this. Do you see this issue happen consistently? I wasn't able to replicate.

**Comment by CiciLi1** [comment]
Verified this issue on VS Main\35602.64 + NuGet Client Dev\6.13.0.83, it was fixed, so I will close this issue, thanks.
