### ISSUE TITLE
dotnet restore on a solution file only restores one project

### ISSUE THREAD

**Issue by Pollyfun** [NuGet/Home#13931]
### NuGet Product Used

dotnet.exe

### Product Version

dotnet

### Impact

It's more difficult to complete my work

### Repro Steps & Context

This command fails to restore all the nugets to C:\Users<user>.nuget\packages.

dotnet restore MySolution.sln

Using NET 8.0.400.

This behaviour doesn't occur in all situations, so I've added a solution where it's easily reproducable.

Restoring nugets for the solution (in Visual Studio, or on the command line with dotnet restore) will seemingly randomly restore the nugets from one of the projects, but not for the other. Illustration added.

[Packages.zip](https://github.com/user-attachments/files/17778438/Packages.zip)

![image](https://github.com/user-attachments/assets/cc870987-acda-4d4c-bf43-4f53aea97101)

**Comment by jeffkl** [comment]
When restoring projects, the default location that the restore assets are stored is in a folder next to the project named `obj`.  It is highly recommended that a folder only contains a single project.  If all projects are contained in a unique folder, then their restore outputs will not be shared and restore will work as expected.

If you need projects to share the same folder, you can set the `MSBuildProjectExtensionsPath` (https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-by-directory?view=vs-2022#example)  However, be aware that those two projects will also share compile-time assets among other things.
