### ISSUE TITLE
I'd like NuGet to give me a cue for different available updates.

### ISSUE THREAD

**Issue by voroninp** [NuGet/Home#13948]
### NuGet Product(s) Involved

Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### The Elevator Pitch

If a newer package version targets the next version of .NET runtime, I cannot update the package without switching the runtime. This is fundamentally different from the case "There is a new version for **the same** .NET runtime you project targets". 

_I want to see this difference in the output of NuGet be it CLI or UI in VS._

Also, I'd like to have a dry run option for installing packages to see whether I'd be able to install a new version of the package without any issue like version conflict or version downgrade without actually installing the package. 
Seeing problematic packages in UI would be a nice addition to the DX.

### Additional Context and Details

It's very annoying to try to update packages and end up with rollbacks. There should be a hint in UI.

**Comment by voroninp** [comment]
Somewhat related [issue](https://github.com/NuGet/Home/issues/13940)

**Comment by nkolev92** [comment]
The frameworks part is covered by https://github.com/NuGet/Home/issues/5725. 

A package installation is really a restore, and if you have the `Show preview window` checkbox enabled, it'll effectively do that. 
https://github.com/NuGet/Home/issues/5725 may consider more than just frameworks in general though. Any graph inconsistencies are only knowable at restore time.

**Comment by voroninp** [comment]
@nkolev92,

> and if you have the `Show preview window` checkbox enabled, it'll effectively do that.

Well...
![image](https://github.com/user-attachments/assets/d522f2ef-17be-4d34-a966-951ef3b3808e)

![image](https://github.com/user-attachments/assets/6850d200-e7fc-4a10-acee-1efd0e7c7f16)

This is not what I should se but rather the warning that I won't be able to install.
