### ISSUE TITLE
Support separate caches support per build & feed for http & package caches

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1394]
For a CI machine running restore in parallel for multiple projects we want a mechanism that avoids using an http cache, to avoid contention.

An alternative is to provide an environment variable `NUGET_HTTP_CACHE` (or the v2 cache folder) similar to `NUGET_PACKAGES` to create a temporary cache per solution level restore

CC @davidfowl

**Comment by yishaigalatzer** [comment]
To clarify: The idea is to be able to create a complete separation between two different restores.

The end goal is to be able to run a build machine (or unit tests, or local builds) that each use its own set of sources where package ids might collide, but without cross restore effects that happen today.

CC // @zjrunner

**Comment by emgarten** [comment]
``NUGET_HTTP_CACHE_PATH`` is supported now
