### ISSUE TITLE
Revert changes to NuGetAuditMode defaults

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#13945]
### NuGet Product(s) Affected

Visual Studio Package Management UI, Visual Studio Package Manager Console, MSBuild.exe, dotnet.exe

### Current Behavior

In .NET 9 preview 6, and VS 17.12 preview 1, we changed NuGetAuditMode to `all`, so it will report both transitive and direct packages with known vulnerabilities.

### Desired Behavior

Restore .NET 8 SDK & VS 17.11's default to only report known vulnerabilities in directly referenced packages.

**Comment by WeihanLi** [comment]
Is it because it caused too many breaks?
