### ISSUE TITLE
.NET Designer and NuGet packages for UI: Problems with IncludeAssets/ExcludeAssets/PrivateAssets

### ISSUE THREAD

**Issue by kuskitkd** [NuGet/Home#13953]
### NuGet Product Used

Visual Studio Package Management UI

### Product Version

VS2022 17.12.178.10385

### Impact

I'm unable to use this version

### Repro Steps & Context

I am switching the support of our UI libraries/apps from using NETFramework 4.7.2 + NET 8 Windows to using only NET 8 Windows as part of the migration process to the latest .NET.  

The UI uses third party libraries (DevExpress WinForms). To prevent copying of the DevExpress dlls to the output folder, those packages were originally configured as ExcludeAssets=runtime. This was done because the dlls end up being pulled into a different folder in the output tree through another project and this library is enhancing that one. The whole application is published later on via ClickOnce, so there cannot be duplicates anywhere on the folder published.

When having both frameworks, the designer run as for Framework and everything was OK. When having only NET 8 Windows, the designer seems to need to consume the content of the lib folder for all DevExpress packages or the in-place designer in VisualStudio does not work. So ExcludeAssets=runtime does not work anymore. After removing that, the designer works but dlls start appearing in folders where they should not be (and causing ClickOnce issues). 

I tested several combinations of asset configurations, just in case the tag or the asset was being used wrong, but there does not seem to be a way to have the contents in the lib folder used for the designer but not copy them out to the output folder.

Combinations tested:
IncludeAssets: (default); PrivateAssets: (default), ExcludeAssets: (default) -> Dlls copied, Designer works
IncludeAssets: (default); PrivateAssets: (default), ExcludeAssets: runtime -> Dlls not copied, Designer does not works
IncludeAssets: (default); PrivateAssets: runtime, ExcludeAssets: (default) -> Dlls copied, Designer works
IncludeAssets: (default); PrivateAssets: all, ExcludeAssets: (default) -> Dlls copied, Designer works
IncludeAssets: compile; PrivateAssets: all, ExcludeAssets: (default) -> Dlls not copied, Designer doesn't work
IncludeAssets: compile;runtime; PrivateAssets: all, ExcludeAssets: (default) -> Dlls copied, Designer works
IncludeAssets: compile;runtime; PrivateAssets: all, ExcludeAssets: runtime -> Dlls not copied, Designer doesn't work

For reference, the nupkg for the  NuGet packages referenced looks as follows:
![image](https://github.com/user-attachments/assets/3dfcf3d5-a941-4e05-81cf-f0f86763f010)

And the DesignToolsError
![image](https://github.com/user-attachments/assets/6cfaabe7-3e04-4fcc-b99f-aca4a41cfe32)

Opening the report here, as it's not clear if the issue is the NuGet package assets configuration or if it's how VS and the .NET designer use them.

**Comment by jeffkl** [comment]
The `IncludeAssets` and `ExcludeAssets` attribute control what assets of a particular package your project should consume.  By setting `ExcludeAssets="runtime"`, NuGet is being told to not have the DLLs of that package copied to the output directory.  NuGet does not know what functionality of any particular package is needed so it would not be able to tell you when an incompatible `IncludeAssets/ExcludeAssets` is set.  If anything, the DevExpress SDK could detect if a user has set that metadata on a `PackageReference` since its the only component aware of the requirements.

**Comment by kuskitkd** [comment]
Hi @jeffkl, just to confirm, having ExcludeAssets=runtime sounds like the correct approach for not having the packages going to the output folder but still have the project use everything correctly at runtime/compilation, right?

As originally stated, I wasn't sure if it was a problem on my understanding of what indicating runtime meant when used in Include/Exclude/PrivateAssets (some additional information/example in the documentation would be nice). 

If the usage of the asset tags makes, I'll raise the topic on the WinForms side instead, as it might be an issue on the new .NET WinForms designer in VS and how it deals with nuget.s

**Comment by jeffkl** [comment]
> Hi @jeffkl, just to confirm, having ExcludeAssets=runtime sounds like the correct approach for not having the packages going to the output folder but still have the project use everything correctly at runtime/compilation, right?

Yes, you can read more about controlling consumption of package assets at https://learn.microsoft.com/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
