### ISSUE TITLE
Targeting Net8.0 (Isolated) and using Durable Functions Orchestration within an Azure Functions project causes NuGet to restore old vulnerable packages

### ISSUE THREAD

**Issue by mikejohnstonPremierinc** [NuGet/Home#13952]
### NuGet Product Used

Visual Studio Package Management UI, Visual Studio Package Manager Console

### Product Version

Visual Studio 17.12

### Worked before?

No. Version 17.11.6 did not work either

### Impact

I'm unable to use this version

### Repro Steps & Context

**Steps to Reproduce**  

1. Open Visual Studio, choose to create a new project
2. Search for `Azure Functions`, choose it and click Next
3. In the Additional Information window, choose `.NET 8.0 Isolated (Long Term Support)` and `Durable Functions Orchestration`
![Snag_9787fe](https://github.com/user-attachments/assets/d120aabc-f375-4f81-8542-2cfffa43b376)
4. Click Create
5. Double-click the csproj file and see that nuget restore adds a few packages 
![Snag_9c68d5](https://github.com/user-attachments/assets/8fae7d38-710d-46ee-b649-8e0151968e5b)
6. Within File Explorer in  Windows, look inside your .nuget packages newtonsoft folder. i.e.  `C:\Users\username\.nuget\packages\newtonsoft.json`. You will notice that NuGet downloaded version `13.0.1`
7. Build your project and then look at File Explorer and notice NuGet downloads versions `9.0.1`, `10.0.1`, `10.0.2`, `11.0.2`
8. Delete ALL versions/folders from `C:\Users\username\.nuget\packages\newtonsoft.json`. The folder should now be empty.
9. Add this XML to your .csproj: `<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />`
10. Adding the XML above should force NuGet to download ONLY 13.0.3, for any and all transitive dependencies. 
11. Rebuild the project and notice that it does not download only 13.0.3. It incorrectly downloads all prior versions again.

_**Workarounds**_  
There are no known workarounds

**Comment by jeffkl** [comment]
Duplicate of https://github.com/NuGet/Home/issues/13943

**Comment by mikejohnstonPremierinc** [comment]
@jeffkl I do not consider this as duplicate of 13943, because 13943 was introduced in VS version 17.12. If I revert back to VS version 17.11.6, then 13943 is no longer reproducible. 

This bug, 13952, has been reproduced in lower versions, including 17.11.6.

**Comment by jeffkl** [comment]
Let me see if I can reproduce it..

**Comment by mikejohnstonPremierinc** [comment]
The steps to reproduce / cause of this bug are primarily and only due to creating/using an Azure Function app, with Durable Functions Orchestration, and targeting `Isolated` Net8.0. As shown in the OP's Steps to Reproduce

**Comment by jeffkl** [comment]
Okay I made this trivial project:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.2.0" />
  </ItemGroup>
</Project>
```

Since `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` transitively depends on `Newtonsoft.Json` version 13.0.1, that gets downloaded and installed to the global packages folder.  If you then add a direct dependency on Newtonsoft.Json and clear the global packages folder:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
```
NuGet should only install Newtonsoft.Json version 13.0.3.  However, with the new dependency resolver, it downloads both versions.  If I disable to new resolver as described in https://github.com/NuGet/Home/issues/13943, the legacy resolver only installs 13.0.3.

```
msbuild /t:restore /p:RestoreUseLegacyDependencyResolver=true
```

That makes me think its just the new resolver?  I don't have Visual Studio 17.11 installed at the moment to verify older versions.

**Comment by mikejohnstonPremierinc** [comment]
I assume the trivial project you created above is not an Azure Functions project (Choosing `.NET 8.0 Isolated (Long Term Support)` and `Durable Functions Orchestration` in the Additional Information window). 
![Snag_97d737](https://github.com/user-attachments/assets/18c9eec6-c0ab-4103-95d5-f43a8efef0b6)

Choosing exactly those settings is explained in the original post. 

I assume you did not choose those settings because your result was not the same as mine. Meaning you only experienced NuGet downloading `Newtonsoft.Json 13.0.1`. I experienced NuGet downloading many more versions (`9.0.1`, `10.0.1`, `10.0.2`, `11.0.2`).

Can you please follow my exact steps in the original post and then tell me if disabling the new resolver prevents ALL older versions of `Newtonsoft.Json` from getting downloaded? 

Also, can you provide exact steps on how to disable the resolver. I saw the workaround you posted stating `setting an MSBuild property in their Directory.Build.props or an environment variable`. I thought I properly disabled the resolver, but that did not resolve the issue. Meaning the old packages still get downloaded. After performing your workaround, is there any explicit way to verify that the new resolver is actually disabled?

The steps I performed to disable the resolver:

1. Right click on Solution and select Add>New Item
2. Name the new item `Directory.Build.props`
3. Inside `Directory.Build.props`, add:
```XML
<Project>
  <PropertyGroup>
    <RestoreUseLegacyDependencyResolver>true</RestoreUseLegacyDependencyResolver>
  </PropertyGroup>
</Project>
```
Finally, after you follow my exact steps in the original post, if you reproduce the issue, can you please mark this issue as Open? Because I do not believe it is a duplicate of [13943](https://github.com/NuGet/Home/issues/13943), as explained in my prior comment. It occurs BEFORE Visual Studio 17.12, and it is only reproducible by those specific steps in the original post

**Comment by mikejohnstonPremierinc** [comment]
@jeffkl Please provide an update on my prior reply.

**Comment by jeffkl** [comment]
Sorry, you're right.  What's happening in Azure Functions apps is that the SDK is generating a `.csproj` on the fly in the obj folder:


```xml

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Configuration>Release</Configuration>
        <AssemblyName>Microsoft.Azure.Functions.Worker.Extensions</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETCore.Targets" Version="3.0.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.3.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.13.1" />
    </ItemGroup>

    <Target Name="_VerifyTargetFramework" BeforeTargets="Build">
        <!-- It is possible to override our TFM via global properties. This can lead to successful builds, but runtime errors due to incompatible dependencies being brought in. -->
        <Error Condition="'$(TargetFramework)' != 'net6.0'" Text="The target framework '$(TargetFramework)' must be 'net6.0'. Verify if target framework has been overridden by a global property." />
    </Target>
</Project>
```

Its then restoring the project itself:

![image](https://github.com/user-attachments/assets/f78c98da-f5b0-4928-89be-caf26b3718d9)

This generated project contains a transitive reference to a different Newtonsoft.Json which is why NuGet is installing it.

I'm not sure exactly how this SDK works but you can see if there's an existing issue or file a new one at https://github.com/Azure/azure-functions-dotnet-worker/issues

**Comment by mikejohnstonPremierinc** [comment]
@jeffkl Thanks. I will post an issue within https://github.com/Azure/azure-functions-dotnet-worker/issues.
