### ISSUE TITLE
Http Caching in Client doesn't Actually Happen

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#1395]
Despite some code kicking around in the HttpMessageHandler resource to initialize the HttpClient correctly this doesn't actually happen because the custom CredentialPromptWebRequestHandler stamps on that behavior.

The fix is to make sure that that handler actually sets its base class CachePolicy to the RequestCachePolicy Default level. The Default level has the correct behavior with the client following the Cache headers appropriately.

Somewhat independent of this is the fact that the client stack attempts to contact the network too many times in the course of performing some action. For example, executing install from the comment line does attempt to load the registration blobs 3 times. Caching would have actually masked this to a large degree but fundamentally the client is doing more work than it has too - even if caching was actually working.

**Comment by yishaigalatzer** [comment]
Related PR - https://github.com/NuGet/NuGet3/pull/131

**Comment by emgarten** [comment]
NuGet/NuGet.Client@1974574a8b3b4df9b1690c2718ba7010b5f8f64e
