### ISSUE TITLE
NU3018  The trust provider does not trust the signature certificate signed by the repository master The package "xxxxx"

### ISSUE THREAD

**Issue by JavaScript-zt** [NuGet/Home#13958]
### NuGet Product Used

Visual Studio Package Manager Console

### Product Version

dotnet NET6

### Impact

It's more difficult to complete my work

### Repro Steps & Context

NU3018 comes from the source“ https://api.nuget.org/v3/index.json: The trust provider does not trust the signature certificate signed by the repository master The package "JavaScript Engine Switcher. ChakraCore 3.26.0"
NU3018 comes from the source“ https://api.nuget.org/v3/index.json: The trust provider does not trust the signature certificate signed by the repository master The package "xxxxx"
NU3018 comes from the source“ https://api.nuget.org/v3/index.json: The trust provider does not trust the signature certificate signed by the repository master The package "xxxxx"
NU3018 comes from the source“ https://api.nuget.org/v3/index.json: The trust provider does not trust the signature certificate signed by the repository master The package "xxxxx"
NU3018 comes from the source“ https://api.nuget.org/v3/index.json: The trust provider does not trust the signature certificate signed by the repository master The package "xxxxx"

**Comment by jeffkl** [comment]
Can you provide a project we can use to reproduce the behavior?  I'm not sure what packages and versions of those packages you're using exactly.  Adding a `PackageReference` to `JavaScriptEngineSwitcher.ChakraCore 3.26.0` worked for me and [downloading the package](https://www.nuget.org/packages/JavaScriptEngineSwitcher.ChakraCore/3.26.0)

Are you able to reproduce the problem on multiple machines? I wonder if this machine's certificate trust chain is misconfigured?
