### ISSUE TITLE
Idea: Make nuget.config configuration options available as env vars

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1396]
All [nuget.config configuration](http://docs.nuget.org/consume/NuGet-Config-Settings) options should be overrideable with environment variables.

Suggestion: use the same configuration parameter name prefixed with "NUGET_" for the environment variable to maintain consistent feature naming across configuration options.

Discussion: Does a nuget.config file in the same folder as a project take precendence over the environment variable, or is the environment variable the highest priority?

**Comment by nkolev92** [comment]
This has already been done partially, with env variables taking the highest preference. 
Currently, there's no requests suggesting that we should fully move to env variables.
