### ISSUE TITLE
Installing KendoUICore package (lots of small JS files) extremely slow.

### ISSUE THREAD

**Issue by jwynia** [NuGet/Home#1397]
Given VS2015 Enterprise, web application project in .NET 4.5.2, standard MVC project wizard output.
When I install the KendoUICore package
Then it takes 20+ minutes to install

I've noticed that this particular JS library causes problems with VS when added manually as well, which leads me to suspect that it's the "add file to VS project" portion of the package install that's bogging things down. But, with all of the translation, etc. files, more and more JS libraries have tons of JS/CSS/img files to add, so it's not going to get better on its own.

**Comment by burkeholland** [comment]
I've got VS 2015 Community edition running and I'm getting the exact same issue. However, I'm getting it with all packages that I add, and even creating or adding a single new file to the project takes between 5 and 10 seconds sometimes. I wish I could provide more input here. I'm not often in Visual Studio so I'm not sure where to look to help, but I'll go get log files or stack traces or whatever you need.

**Comment by emgarten** [comment]
@burkeholland are the projects under source control? Are you able to manually add a file to the project in a normal amount of time, or are you only seeing this issue when nuget adds the files?

**Comment by yishaigalatzer** [comment]
What version of the NuGet extension are you using? There are some improvements in this area in NuGet 3.2.

Are you using TFS as the source control system for this?

**Comment by csharpfritz** [comment]
Tested with 3.2 and install runs very quickly in 2015.  We will investigate the Update and Uninstall actions with packages of this size

**Comment by yishaigalatzer** [comment]
I've made a change that improves performance here by x3/x4, I still see install being about x3/x4 faster than uninstall, but all the time is spent in the csproj.dll.

Reaching out to @pilchie and @jasonmal to see if we can do something better about this.
