### ISSUE TITLE
Add indicator for deprecated and vulnerable packages to Package Details tab header.

### ISSUE THREAD

**Issue by jgonz120** [NuGet/Home#13974]
The vulnerability and deprecated warnings were moved to inside the package details tab. We want to make sure users are aware of the any issues with the packages they have selected so we want to add a warning icon similar to the one on the "Installed" tab in the PM UI.

**Comment by aortiz-msft** [comment]
Would it be possible to add a screenshot of the new UI as part of the PR description?
