### ISSUE TITLE
Package install error?

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1398]
_From @HaukiDog on September 17, 2015 15:40_

I am trying to install a package with zero dependencies. Specifically https://www.nuget.org/packages/x-editable

I am installing in to a .net 4.5.2 MVC site, and I am getting the following error:

Error       Could not install package 'x-editable 1.5.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.           0

It seems like a nuget of vs bug as there are no .net dependencies in the project.

_Copied from original issue: NuGet/NuGetGallery#2686_

**Comment by emgarten** [comment]
The nuget error message is correct, the x-editable 1.5.1 package is authored incorrectly and doesn't contain any folders for nuget. The readme file mentions installing the package with bower. Either this package is installed using another tool on top of nuget, or it has never worked at all.
