### ISSUE TITLE
Version conflict with Nuget.Frameworks.dll in .Net SDK 9.0.101

### ISSUE THREAD

**Issue by Gambero81** [NuGet/Home#13987]
### NuGet Product Used

NuGet SDK

### Product Version

NuGet.Framework.dll 9.0.101

### Worked before?

sdk 8.0.307

### Impact

I'm unable to use this version

### Repro Steps & Context

i use roslyn libraries to analyze my project.
after update my project to net9, roslyn code has stopped working.

some code to reproduce the issue:

```
var solutionFilePath = "c:\myPath\mySolution.sln";
var projectName = "MyProject";

using (var workspace = MSBuildWorkspace.Create())
{
   var solution = await workspace.OpenSolutionAsync(solutionFilePath);
   var project = solution.Projects.FirstOrDefault(p => p.Name.Equals(projectName));
   if (project == null)
   {
       HandleError($"Progetto {projectName} non trovato nella solution!");
       return null;
   }
   var compilation = await project.GetCompilationAsync();

  //after call to project.GetCompilationAsync if i watch workspace.Diagnostics 
  //it give me a lot of errors relative to assembly NuGet.Frameworks (see verbose log section)
}
```

errors are like 'Could not load file or assembly 'NuGet.Frameworks, Version=6.12.2.1'

NOTE: the references version of NuGet.Frameworks library is 6.12.1.1

the version it not found because simply DOES NOT EXIST (6.12.1.1 is the last one available on nuget)

these errors cause all the code analysis to fail...

a similar issue is this one: https://github.com/NuGet/Home/issues/13746 who is closed but NOT RESOLVED: the workaround suggested (using the old framework version) does NOT WORK with a project compiled in NET9.

any help?

Thanks

### Verbose Logs

```shell
[Error] Msbuild failed when processing the file 'C:\ARTInvoiceManager\ARTInvoiceManager.Server\ARTInvoiceManager.Server.csproj' with message: C:\Program Files\dotnet\sdk\9.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets: (90, 5): errore imprevisto dell'attività "ProcessFrameworkReferences".
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Frameworks, Version=6.12.2.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'NuGet.Frameworks, Version=6.12.2.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: Could not load file or assembly 'C:\Program Files\dotnet\sdk\9.0.101\NuGet.Frameworks.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'C:\Program Files\dotnet\sdk\9.0.101\NuGet.Frameworks.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.<>c.<AddPacksForFrameworkReferences>b__233_0(ITaskItem item)
   at System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
   at System.Linq.Enumerable.IEnumerableWhereIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.AddPacksForFrameworkReferences(List`1 packagesToDownload, List`1 runtimeFrameworks, List`1 targetingPacks, List`1 runtimePacks, List`1 unavailableRuntimePacks, List`1& knownRuntimePacksForTargetFramework)
   at Microsoft.NET.Build.Tasks.ProcessFrameworkReferences.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by jasonmalinowski** [comment]
@Gambero81 What version of Microsoft.CodeAnalysis.Workspaces.MSBuild are you using?

**Comment by zivkan** [comment]
I've reached out to the Roslyn team for advice.

From my point of view, the runtime's assembly loader isn't working as expected. It should allow loading any assembly whose version is greater than or equal to the compile time assembly version. Here's the code: https://github.com/dotnet/runtime/blob/99814311b0af050b5a90d53c563d1baaf674745a/src/coreclr/binder/assemblybindercommon.cpp#L49-L51

One way to test it:

```sh
dotnet new classlib -n ClassLib1
dotnet new console -n ConsoleApp1
dotnet add ClassLib1 package NuGet.Frameworks -v 6.11.0
dotnet add ConsoleApp1 package NuGet.Frameworks -v 6.12.0
dotnet add ConsoleApp1 reference ClassLib1
```

Then edit ClassLib1 to NuGet.Frameworks, and edit ConsoleApp1 to use both ClassLib1. Here's a sample where I also added output about the compiled reference version and the loaded assembly version:
[gh13987.zip](https://github.com/user-attachments/files/18014900/gh13987.zip)

```console
Is net9.0 compatible with netstandard2.0? True

ClassLib1.dll compiled against NuGet.Frameworks, Version=6.11.0.119, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Loaded NuGet.Frameworks version 6.12.0.127
```

This is just like your scenario, the dll was compiled against a lower version of the assembly that exists on disk. My sample app works, so I don't understand why your analyzer doesn't.   I don't mean to blameshift, but I feel like NuGet isn't technically doing anything wrong here. Whatever is causing these assembly load failures probably shouldn't be. 😕

**Comment by zivkan** [comment]
@Gambero81 Does your analyzer package (I assume you're using your analyzer via a package) contain NuGet.Frameworks.dll within it?  If so, I'm even more confused, but if not, I suspect that you can mitigate the issue by shipping your dependency with your analyzer.

edit: it was pointed out to me that the original issue isn't a roslyn analyzer that runs as part of a dotnet build (csc.exe /analyzer arugment), so my question doesn't make much sense.

**Comment by zivkan** [comment]
I copied the code snippet from the original post, and edited it until I got something that compiles and runs: 
[gh13987-2.zip](https://github.com/user-attachments/files/18015242/gh13987-2.zip)

But I can't reproduce the error

@Gambero81 please provide us with a reproduction

**Comment by Gambero81** [comment]
hi, in attachment a zip with 2 projects:
`AspNetControllerWrapper`: command line application for analyze other .net app (i trim the code only for reply the issue)
`ConsoleApp30`: a new console application analyzed by `AspNetControllerWrapper`

`AspNetControllerWrapper` take 2 input parameters:
Solution file path (for example "C:\ConsoleApp30\ConsoleApp30.sln")
ProjectName (for example "ConsoleApp30")

running `AspNetControllerWrapper` in debug, if you break on variable `diagnosticsLog` (file `ARTCodeAnalysis.cs`) you can reply the issue.

Thanks

[NugetFrameworkError.zip](https://github.com/user-attachments/files/18019985/NugetFrameworkError.zip)

**Comment by Gambero81** [comment]
seem i found the issue:

i have referenced 4.8.0 versions on these libraries:  

```
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.8.0" />
```

updating to 4.12.0 seem solve the issue.

But now project build create 2 additional folders "BuildHost-net472" and "BuildHost-netcore" who seem needed to deploy the application, with the previous version i deploy only the binaries on the bin folder.

What is the correct deploy method? (my analysis application is a command line application used for asp.net core apps)

Thanks

**Comment by jasonmalinowski** [comment]
You will now need to deploy the folders it creates along with your application.

To explain a bit what the problem is here: for us to load .csproj projects, we have to run parts of MSBuild to analyze them and resolve references, NuGet packages, etc. Prior to the 4.9 version of the MSBuild packages, we ran that MSBuild in your application. This creates problems like you saw: if MSBuild or the SDK moves to a higher version of a package that you are also deploying yourself (even in directly if some other package used it), you can have load issues because .NET will prefer the assembly shipping in your applications' folder over what is in the SDK/MSBuild directory.

To solve problems like this (and address some other issues like a .NET Core app needing to analyze a .NET Framework project, which some folks need to support) we generally went to a model where we no longer load MSBuild in your process, and we instead launch a separate application to do that, where we can control exactly what's loaded to avoid surprises. So that's what's in those separate folders -- something to ensure you don't have version mismatches.

**Comment by Gambero81** [comment]
> To solve problems like this (and address some other issues like a .NET Core app needing to analyze a .NET Framework project, which some folks need to support) we generally went to a model where we no longer load MSBuild in your process, and we instead launch a separate application to do that, where we can control exactly what's loaded to avoid surprises. So that's what's in those separate folders -- something to ensure you don't have version mismatches.

Thanks @jasonmalinowski
