### ISSUE TITLE
New dependency resolver does not handle floating versions correctly in some situations

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#13992]
### NuGet Product Used

dotnet.exe, MSBuild.exe, NuGet.exe

### Product Version

6.12

### Worked before?

Yes, 6.11

### Impact

None

### Repro Steps & Context

Originally reported in https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2302642

Projects that use floating versions with the new dependency resolver can have issues with resolved packages.  Sometimes a version conflict is incorrectly reported.

Project1:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.*" />
  </ItemGroup>
</Project>
```

Project2:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.*" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project1\Project1.csproj" />
  </ItemGroup>
</Project>
```

### Verbose Logs

```shell
Version conflict detected for Microsoft.Extensions.Logging. Install/reference Microsoft.Extensions.Logging 6.0.0 directly to project NugetTestDemo to resolve this issue.
  Project2 -> NLog.Extensions.Logging 5.3.15 -> Microsoft.Extensions.Logging (>= 6.0.0)
  Project2 -> Microsoft.EntityFrameworkCore 6.0.36 -> Microsoft.Extensions.Logging (>= 6.0.1)
```

### Workaround

Users can workaround the issue by setting an MSBuild property in their `Directory.Build.props` or an environment variable:
```xml
<Project>
  <PropertyGroup>
    <RestoreUseLegacyDependencyResolver>true</RestoreUseLegacyDependencyResolver>
  </PropertyGroup>
</Project>
```

**Comment by 304NotModified** [comment]
When is this fix gonna be released? 

And this is NU1107, isn't?

**Comment by jeffkl** [comment]
> When is this fix gonna be released?
> 
> And this is NU1107, isn't?

This will be in the next version of Visual Studio, 17.13, and the .NET SDK 9.0.200.  Yes, the error code logged is `NU1107`.
