### ISSUE TITLE
[Wiki] Docs for msbuild equivalent property for --force-evaluate not correct

### ISSUE THREAD

**Issue by Charles-Gagnon** [NuGet/Home#13995]
### NuGet Product Used

Other/NA

### Product Version

N/A

### Impact

None

### Repro Steps & Context

The wiki says that there isn't an msbuild equivalent property for --force-evaluate, but per https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#lock-file-extensibility `RestoreForceEvaluate` does just that.

https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#restore-command-line-options

**Comment by nkolev92** [comment]
@Charles-Gagnon 

The Wiki was used for Designs at one point, the docs at https://learn.microsoft.com/nuget are real source of truth.

**Comment by Charles-Gagnon** [comment]
Can you at least update the wiki to point to the docs then? Or just delete them if they aren't being maintained...I came across that by doing a web search, so having stale/outdated information out there is just going to cause confusion.

**Comment by nkolev92** [comment]
We have ~100s of pages, many of which are specs. 

I have edited this particular doc, but unfortunately it's laborious to have them point to the exact docs and it's not something we've heard a lot of feedback on. 

I have updated this particular file with the following line:

> *Note* This is a spec and only has historical value. If implemented, documentation is available at https://learn.microsoft.com/nuget/ and it may be different from this document.
