### ISSUE TITLE
Provide a way for NuGet to work in environments that force Powershell to AllSigned

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#1399]
I'm not even sure it's possible, just logging my frustrations - package installs fail in all kinds of interesting way when AllSigned is enforced via Group Policy or similar.

**Comment by emgarten** [comment]
Try changing your execution policy for the local machine scope:

```
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
```

**Comment by ghost** [comment]
That's overridden in our environment

**Comment by emgarten** [comment]
NuGet respects the group policy. There are ways to run global powershell profile scripts that would apply to the NuGet console, you could try changing the settings there to allow for a bypass, but this would need to be done locally by you.
