### ISSUE TITLE
NugetVersion acceptes a postfix of +15, but silently drops it off. 

### ISSUE THREAD

**Issue by ChaosYoda** [NuGet/Home#14026]
### NuGet Product(s) Affected

NuGet.exe, dotnet.exe, NuGet SDK

### Current Behavior

Currently with the changes to gitversion v6, a fullsemver is produced like 9.0.8-141871-git-version.1+15, nugetversion will accept the value but will drop off the +15. In giversion v5, there was the following:
`"NuGetVersionV2": "9.0.7-141167-dex-param0008",
  "NuGetVersion": "9.0.7-141167-dex-param0008",
  "NuGetPreReleaseTagV2": "141167-dex-param0008",
  "NuGetPreReleaseTag": "141167-dex-param0008",`
  Variables, but these are not available anymore. 

### Desired Behavior

Would it be possible to adjust gitversion to convert the +15 to 0015, so that continuous versioning won't break. 

### Additional Context

This is after the breaking changes in gitversion v5 to v6, which is following [Semantic Versioning & auto-incremented NuGet package versions](https://www.xavierdecoster.com/post/2013/04/29/semantic-versioning-auto-incremented-nuget-package-versions.html)

**Comment by zivkan** [comment]
According to the [semver spec](https://semver.org/#spec-item-10)

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Build metadata MUST be ignored when determining version precedence.** Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85, 1.0.0+21AF26D3----117B344092BD.

emphasis mine.

When I do a `dotnet pack -p:Version=1.2.3+abc123`, and then look at the generated nuspec file, it has `<version>1.2.3+abc123</version>`. So, I'm confident that the metadata is getting passed around, it's just that from package consumers point of view, the metadata doesn't matter, so NuGet typically doesn't show the metadata for example on nuget.org or the package manager UI.

> Would it be possible to adjust gitversion to convert the +15 to 0015, so that continuous versioning won't break.

I don't know what product "gitversion" is, but it's not a NuGet feature. If you're referring to the package NerdBack.GitVersioning, the NuGet team doesn't support individual nuget packages, you should contact that package owner. If you're talking about some other gitversion product/feature, you should report it to the appropriate owner. NuGet is using the version provided to it.
