### ISSUE TITLE
Distribution site fails to load (too many redirections)

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#1403]
I tried to go to https://dist.nuget.org/index.html to get the newest nuget.exe (3.2), but it fails to open in Chrome as well as failing to download from commandline via Invoke-WebRequest in PowerShell:

``` powershell
Invoke-Webrequest : Too many automatic redirections were attempted.
```

**Comment by yishaigalatzer** [comment]
Thanks we are aware, this happens because of a CDN rule that got propagated to Prod after testing on int, but fails for some reason on Prod.

We are working with out CDN provider to revert and propagate the change, should be a few more minutes to get it back up.

**Comment by twsouthwick** [comment]
Looks like it's back up! Thanks
