### ISSUE TITLE
VCXPROJ not understood by NuGet.exe

### ISSUE THREAD

**Issue by DzonnyDZ** [NuGet/Home#1409]
I tried this with latest version of NuGet.exe (3.2)

```
nuget.exe" pack Tools.Hardcore.vcxproj
```

and I'm getting following error message
"Please specify a nuspec or project file to use."

**Comment by yishaigalatzer** [comment]
This is not supported by NuGet, you will need to create a nuspec and pack directly.

There is currently no standard way to pack a C++ project. It might be something we look into in the future when C++ gets a first class support

**Comment by DzonnyDZ** [comment]
My C++ project is actual C++/CLI project (pure managed library). It's just for some reasons written in C++/CLI. I just expected this to work since csxproj is MSBuild format.

**Comment by yishaigalatzer** [comment]
I see the why you would have expected that.

C++/CLI projects where always somewhat of a fringe thing and thus never supported for this path.

**Comment by dersteve** [comment]
Will there ever be support @yishaigalatzer for C++/CLI projects? Is something in the pipe? I ask, because I have the same challenge at the moment to pack such a project

**Comment by magol** [comment]
I'm using coApp to create nuget packades for c++. The project is deadline,  but it works

**Comment by dersteve** [comment]
@mago i also saw this just now. what do you mean with deadline? Like dead? Is it working for you?

**Comment by magol** [comment]
Upps,  auto correct on my smart phone. 
It should be  "dead" 

CoApp works for me 😊
