### ISSUE TITLE
VS2015 extension does not follow redirect to package icon URL

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#1410]
Example package: http://www.nuget.org/packages/Microsoft.Azure.Devices/1.0.0-preview-001-000-001

In VS2013, the package icon shows correctly.
In VS2015, the default package icon is shown instead.

The icon url in the below package points to http://go.microsoft.com/fwlink/?LinkID=288890.
This looks like a redirect to http://www.gravatar.com/avatar/425be63bdaaeeffd26d0172ed2030198.png.

**Comment by emgarten** [comment]
@feiling can you find out how many packages this affects to determine if we should take this for 3.3?

**Comment by RanjiniM** [comment]
Xavier, both VS 2013 and VS 2015 show the Microsoft icon now? Is that what is expected? If yes, then this issue is fixed. Can you please confirm and close? Thanks!

Please reassign to me if I have misunderstood the issue.

**Comment by xavierdecoster** [comment]
@RanjiniM looks fixed indeed!
