### ISSUE TITLE
Consider adding a warning for users of nuget.targets

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1411]
Some users are still in the nuget.targets world, and they have no indication (other than searching) that they should move off it. This become more important in Visual Studio 2015.

We need to see if there is a way to
1. Reliably warn people (so no false alerts)
2. Reliably suppress the warning for people that know what they are doing.

**Comment by emgarten** [comment]
This is normally a solution level package. Once that is fixed and this package shows up again we will take a look at detecting deprecated packages.
