### ISSUE TITLE
Add LicenseUrl again to the Package object returned by Get-Package

### ISSUE THREAD

**Issue by raphaelschnaitl** [NuGet/Home#1416]
There is a script which used to download all Licenses of all packages which does not work any more in VS 2015.

http://stackoverflow.com/questions/32638653/licenseurl-showing-up-empty-when-using-get-package-in-the-vs-package-manager-con/32647036#32647036

**Comment by yishaigalatzer** [comment]
The package object in Visual Studio 2013, was an OData object that basically exposed the world. In Visual Studio 2015 where we don't support OData directly many of the properties where dropped.

So it makes complete sense to add necessary objects back. This seems like a lower priority issue compared with other work scheduled for Update I. But will gladly take a pull request for this.

As of this point in time we are consolidating our Repositories for all V3 code to move into the nuget.client repo (from nuget3, nuget.packagemanagement and nuget.visualstudioextension). We are planning for the repo to be ready to take new PRs by 9/25

**Comment by gutierlf** [comment]
Here's a vote for returning this object so that the license download will work again.

**Comment by mikebrengartner** [comment]
Also voting for this to return!

**Comment by yishaigalatzer** [comment]
@zhili1208 this should be something you have done before many times, can you take a quick look?

**Comment by vunvulear** [comment]
One vote from me also!

**Comment by defaultbob** [comment]
+1

**Comment by konste** [comment]
+1
Any idea when approximately it is going to be available? We need it badly.

**Comment by zhili1208** [comment]
@konste I will try to fix this soon, maybe next week

**Comment by konste** [comment]
Great! Thanks a lot @zhili1208 ! I would rather not wait for the official 3.4 RTM, but pick up the build with this fix as soon as it is available. Going through 250 packages to extract licenses manually does not look like fun to me :-(

**Comment by konste** [comment]
Hoorray! Now, unless 3.4 is real close, how do I get the bits with the fix? Is there a way shorter than rebuilding everything locally?

**Comment by yishaigalatzer** [comment]
This will go live with VS Update II, shoot me a personal email for access to bit - y i g a l a t z @msft.com
