### ISSUE TITLE
Automatic Restore in Visual Studio does not restore the content from the nuget pack

### ISSUE THREAD

**Issue by donnib** [NuGet/Home#1417]
Hi,
I have removed all packs from my solution then i opened my solution and did a rebuild, VS restores all nuget packs but forgets about the contents of the contents folder within the nuget pack, actually it creates the folders but does not copy the files to the projects.

Anyone experiencing this ? Is there a work around ?

/donnib

**Comment by csharpfritz** [comment]
We need some more details to troubleshoot:

What project type are you working with?  
What version of NuGet and Visual Studio are you using?

**Comment by yishaigalatzer** [comment]
Restore is not going to add content to your project, content is added at install time.

Note: Content is not supported for project using project.json to define packages.

**Comment by yishaigalatzer** [comment]
You can run update-package -reinstall to add stuff back

**Comment by donnib** [comment]
@yishaigalatzer Ok, i am not sure i understand why they don't get restored. I thought that was the point with nuget packs that one could open a project and everything got restored as it was. As mentioned it's funny that the folders inside content does get created but the files are not copied. Is there a way to reinstall as you mention automatically when package restore takes place in the post-build step ? Usually people put images or other things in content which the application might rely on so it is equal important as lib files are restored, isn't it just a copy call that is missing ?

**Comment by donnib** [comment]
@yishaigalatzer no idea on above ? What is the meaning with Content ? Maybe i am using it wrongly ?

**Comment by yishaigalatzer** [comment]
There is a misunderstanding here.

NuGet restores job is to download the packages into the packages folder and that is it.

Content is added to a users project at install time and the user is expected to include it in source control, and it is not expected that it gets added back on restore.
