### ISSUE TITLE
Nuget is using runtime.json from old package despite using assets from latest package

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1418]
Use the following project.json

```
{
  "dependencies": {
    "Microsoft.NETCore.Console": "1.0.0-beta-*"
  },
  "runtimes": {
    "win7-x86": { },
    "win7-x64": { }
  },
  "frameworks": {
    "dnxcore50": { }
  }
}
```

With the following nuget sources

```
https://api.nuget.org/v3/index.json
https://www.myget.org/F/dotnet-core/api/v3/index.json
```

Restore will fail with 

```
System.IO.Compression 4.0.1-beta-23321 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86.
```

This is happening because nuget has selected System.IO.Compression 4.0.1-beta-23321 which no longer contains the implementation assembly for System.IO.Compression.dll, we've moved it out into a runtime specific package.  The runtime specific package isn't getting merged in however because for some reason nuget is merging the runtime.json from both System.IO.Compression 4.0.0 and 4.0.1-beta-23321.  The older version defines a more specific runtime association for System.IO.Compression (<os>-<arch> instead of just <os>) so nuget is preferring this.

```
Merging in runtimes defined in Package/System.IO.Compression 4.0.1-beta-23321.
...
Merging in runtimes defined in Package/System.IO.Compression 4.0.0.
```

This is incorrect, if you check the project.lock.json, all targets have chosen the later version of System.IO.Compression, the runtime.json from 4.0.0 should not be used.

/cc @yishaigalatzer @anurse  @lodejard

**Comment by yishaigalatzer** [comment]
We should only use runtime.json from one package, since we don't actually allow multiple versions of the same package in the compile time graph.

**Comment by ericstj** [comment]
Over the past week a lot of folks have moved from using DNX to NuGet in the dotnet CLI and this issue has come up a lot.  @yishaigalatzer can you please prioritize a fix?

**Comment by emgarten** [comment]
nuget/nuget.client@cc6ddc6928a59fd1ee9bd8c5870600706efa035d

Packages rejected during resolution were being merged in as part of the runtime.json walk. This fix checks the node disposition and skips over the rejected nodes.
