### ISSUE TITLE
nuget.exe network request optimizations

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1426]
nuget.exe restore and install makes multiple requests for index.json and the same registration blob data.

**Comment by emgarten** [comment]
NuGet/NuGet3@652c55ffd59f99c2175b958017a1e1ef3e96fd40
NuGet/NuGet.PackageManagement@a12484c3e03818878f294ce233216d85d481021d
NuGet/NuGet.PackageManagement@f4165c27f32c809cbeb6c6f8ec5c17b0feda443b

**Comment by zhili1208** [comment]
verified restore command, it's fixed and @deepakaravindr verified install.
