### ISSUE TITLE
nuget.exe install on Mono fails intermittently with 'Invalid Chunked Data'

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1429]
nuget.exe install on Mono fails intermittently with 'Invalid Chunked Data'

nuget.exe v3.2.0 against a nuget v3 feed

Repro steps:
1. nuget.exe install <packageId>

Expected:
Installation is successful

Actual:
Fails intermittently with the following error:
'Invalid Chunked Data'

Reported by @NTaylorMullen

**Comment by emgarten** [comment]
@ntaylormullen do you know what version of Mono travis-ci is running?

**Comment by NTaylorMullen** [comment]
https://travis-ci.org/aspnet/Razor/jobs/81499303#L968

We're using their alpha feed. Attempting to reproduce on their beta and stable feed now.

**Comment by NTaylorMullen** [comment]
This turned out to be an issue with the current mono on their alpha feed.

Work arounds: 
- Use beta feed mono
- Use v2 NuGet feeds so v3 client doesn't use `HttpClient`.
