### ISSUE TITLE
Problems with Packages.Config

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1441]
_From @kabua on September 22, 2015 21:30_

Nuget states: `"Found packages.config. Using packages listed as dependencies"` However, the dependencies are missing from the corresponding nupkg file.

We have a framework that consists of 1 solution and it contains 4 projects. All of the projects contains direct and indirect dependencies. E.g. Some dependencies are required by the project and others are required when **using** the framework. To ensure that **everything** is included in the package we are using the -NoPackageAnalysis like so: 

In our build batch file we have following local variable defined

```
set packageArgs=-Properties Configuration=Release -NoPackageAnalysis -IncludeReferencedProjects -MinClientVersion 2.5 -verbosity %verbosityLevel%
```

and being used like so

```
..\..\_Solutions\BuildTools\nuget pack Test1\Test1.csproj -OutputDirectory Test1\bin\Release %packageArgs%
..\..\_Solutions\BuildTools\nuget pack Test2\Test2.csproj -OutputDirectory Test2\bin\Release %packageArgs%
etc...
```

For each project, the output states `"Found packages.config. Using packages listed as dependencies"`.

However, when we inspect our nupkg files, we find that some packages contains all of our direct and indirect dependencies and other packages do not. If we rebuild, the packages that were built correctly are still correct and the broken packages are still broken but we can't figure out why some build correctly and the others do not.

IOWs, how do we tell nuget to include **all** the packages that are referenced by the project, regardless if they are being used or not? We thought that the -NoPackageAnalysis flag was suppose to do that but that doesn't seem to work in all cases.

_Copied from original issue: NuGet/NuGetGallery#2693_

**Comment by yishaigalatzer** [comment]
-NoPackageAnalysis is just an analysis of the built package, not something participating in the actual packaging process. It will for example tell you that you accidentally dropped dlls in the wrong folder, but it will not affect the actual content of the package.

The dependencies are only the dependencies coming from packages.config, not indirect dependencies that are not defined.

It will be helpful if you can share an actual sample of a broken project.

**Comment by yishaigalatzer** [comment]
ping

**Comment by yishaigalatzer** [comment]
Heard no response, and we don't have a repro. Feel free to comment with more information here, for re-opening or helping you out
