### ISSUE TITLE
Select multiple packages for update at once in "NuGet Package Manager"

### ISSUE THREAD

**Issue by Tasteful** [NuGet/Home#1442]
Often when I is updating packages to newer versions I need to update multiple packages and it should be good if multiple packages can be updated at once instead of updating them one-by-one.

**Comment by emgarten** [comment]
Use the Update-Package command in the powershell console to do this.

**Comment by Tasteful** [comment]
`Update-Package`will update all packages. I wan't to update selected packages and as I remember the `Update-Package` will not take a list of packages to update.

**Comment by yishaigalatzer** [comment]
This is coming in 3.3 - See https://github.com/NuGet/Home/issues/1504
