### ISSUE TITLE
Add refresh button in the package list.

### ISSUE THREAD

**Issue by petterek** [NuGet/Home#1443]
Just a button that trigger a re-read of the content in the current source.

**Comment by yishaigalatzer** [comment]
That's a cool idea, we will consider adding it after 3.3.

**Comment by csharpfritz** [comment]
I have heard this comment from other customers in the past week after sharing the UI update blog post.  It sounds like this will be very helpful for those using private repositories that are updated frequently

**Comment by rrelyea** [comment]
Fixed in 3.4
