### ISSUE TITLE
disableSourceControlIntegration not honoured in VS 2013

### ISSUE THREAD

**Issue by ObsidianPhoenix** [NuGet/Home#1449]
When running a build in VS2013, nuget restores the missing packages, and then adds the directories to source control automatically, despite the config dictating that this not be the case.

I'm using version 2.8.60723.765 of the nuget extension, and have the following in a nuget.config file at the solution root.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositorypath" value="..\packages" />
        <add key="disableSourceControlIntegration" value="true" />
        <solution>
            <add key="disableSourceControlIntegration" value="true" />
        </solution>
    </config>
</configuration>
```

I've tried setting the value (as you can see) in the config root, _and_ under the solution node. I have also attempted to put this config in a /.nuget folder under the solution root too, but this had no impact.

I actually think this has always been the case for me, and is also the case for other developers in the company too.

This setting works fine in VS2015, but I need to get it working in 2013 too.

What am I missing? Is this actually a bug?

**Comment by yishaigalatzer** [comment]
This could be an issue with how the relative path is defined. Try to use an absolute path or avoid defining all together.

We are currently spending most of our efforts in Visual Studio 2015 3.3, so I'm going to move this to the next release of Visual Studio 2013, which is currently unfortunately not scheduled.

**Comment by rohit21agrawal** [comment]
@rrelyea @yishaigalatzer 
Investigated this and found out that if a .tfignore file is present in the TFS project, disableSourceControlIntegration is not honored, and everything under the packages folder is added to the TFS Source Control.
If the tfignore file is not present, then the repositories.config file is added (if it is created) to source control.

@ObsidianPhoenix - Could you verify this finding at your end, if possible? Also, use the following XML file (note the forward slashes), and you need to put this in the ($SolutionDir).nuget directory:

`<?xml version="1.0" encoding="utf-8"?>
   <configuration>
    <config>
        <add key="repositorypath" value="../packages" />
    </config>        
    <solution>
            <add key="disableSourceControlIntegration" value="true" />
    </solution>
    </configuration>`

**Comment by rohit21agrawal** [comment]
@rrelyea @yishaigalatzer 
My above observation was based on the assumption that disableSourceControlntegration was enabled by default. This assumption was due to the following line in the NuGet docs : https://docs.nuget.org/consume/nuget-config-settings

> section: solution
> key: disableSourceControlIntegration
> 
> Allows you to disable source control integration for the "Packages" folder. This key works at the solution level and hence need to be added to the NuGet.config file present in the $(SolutionDir).nuget directory. Enabling package restore from VS would add the .nuget\nuget.config file automatically. More details here.
> 
> **The default value for this key is true.**

However, since this is not the case, I am not able to repro the bug, if there is any at all.

**Comment by rohit21agrawal** [comment]
Closing this bug. Please feel free to reactivate if this is still an issue for anyone.
