### ISSUE TITLE
Runtime-agnostic native folders are not supported

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#1454]
1. Create a NuGet package with some files in a native folder at the root level.
2. Reference the NuGet package from project.json in a .csproj where CopyNuGetImplementations will be true (either by setting the MSBuild property manually in the .csproj, or because the output type is an exe or AppX).
3. Restore
4. Build

**EXPECTED:** Files from the native folder in the package are deployed to the output folder
**ACTUAL:** Files from the native folder in the package are not deployed to the output folder

This is happening because when running the restore command, the files in a runtime-agnostic native folder are not included in the runtime-specific targets section of project.lock.json.  The ResolveNuGetPackageAssets MSBuild task only considers native folders when a RuntimeIdentifier is specified, so this means that the files in the native folder will never be used.

Sample NuGet package:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package>
  <metadata minClientVersion="2.8.1">
    <id>xunit.console.netcore</id>
    <version>1.0.2-prerelease</version>
    <title>xUnit.net [Runners - .NET Core]</title>
    <authors>James Newkirk, Brad Wilson (.NET Core package by Matt Cohn)</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <licenseUrl>http://go.microsoft.com/fwlink/?LinkId=329770</licenseUrl>
    <projectUrl>http://go.microsoft.com/fwlink/?LinkId=518631</projectUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <summary>.NET Core Framework Test Host</summary>
    <description>
      Console runner for the xUnit.net framework.
      Supported platforms: .NET Core.
      Based on xunit.runners - https://github.com/xunit/xunit
    </description>
    <copyright>Copyright © Microsoft Corporation</copyright>
    <dependencies>
      <dependency id="System.Collections" version="4.0.10" />
      <dependency id="System.Collections.Concurrent" version="4.0.10" />
      <dependency id="System.Console" version="4.0.0-beta-23213" />
      <dependency id="System.Diagnostics.Debug" version="4.0.10" />
      <dependency id="System.Globalization" version="4.0.10" />
      <dependency id="System.IO" version="4.0.10" />
      <dependency id="System.IO.FileSystem" version="4.0.0" />
      <dependency id="System.IO.FileSystem.Primitives" version="4.0.0" />
      <dependency id="System.Linq" version="4.0.0" />
      <dependency id="System.Runtime" version="4.0.20" />
      <dependency id="System.Runtime.Extensions" version="4.0.10" />
      <dependency id="System.Text.RegularExpressions" version="4.0.10" />
      <dependency id="System.Threading" version="4.0.10" />
      <dependency id="System.Threading.Tasks" version="4.0.10" />
      <dependency id="System.Xml.XDocument" version="4.0.10" />
      <dependency id="xunit.runner.utility" version="2.1.0-rc1-build3168" />
    </dependencies>
  </metadata>
  <files>
    <file src="xunit.console.netcore\xunit.console.netcore.exe" target="native" />
  </files>

</package>
```

Sample project.json:

``` json
{
  "runtimes": {
    "win7-x86": { }
  },
  "dependencies": {

  },
  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "xunit.console.netcore": "1.0.2-prerelease-00092"
      },
      "imports": "portable-net451+win81"
    }
  }
}
```

I will send a PR to fix this shortly.

**Comment by yishaigalatzer** [comment]
Can you share the folder structure?

**Comment by davidfowl** [comment]
What is a runtime agnostic native folder?

**Comment by yishaigalatzer** [comment]
I have no idea ☺

**Comment by dsplaisted** [comment]
> What is a runtime agnostic native folder?

@yishaigalatzer @davidfowl It's a native folder that should apply to any runtime.  We'd like to use it to deploy the xunit runner (which is a managed .exe) without having to use .props files. See dotnet/buildtools#276.

The ManagedCodeConventions [seem to indicate](https://github.com/NuGet/NuGet3/blob/1eee015512f0ee7f2685f31102f31613ad09146a/src/NuGet.Client/ManagedCodeConventions.cs#L304) that a native folder in the root of the NuGet folder is a supported pattern:

```
                NativeLibraries = new PatternSet(
                    conventions.Properties,
                    groupPatterns: new PatternDefinition[]
                        {
                            "runtimes/{rid}/native/{any?}",
                            "native/{any?}",
                        },
                    pathPatterns: new PatternDefinition[]
                    {
                        "runtimes/{rid}/native/{any}",
                        "native/{any}",
                    });
```

**Comment by yishaigalatzer** [comment]
A managed exe doesn't work everywhere, this seems wrong

Sent from my Windows Phone

**Comment by dsplaisted** [comment]
> A managed exe doesn't work everywhere, this seems wrong

@yishaigalatzer It should work everywhere that the package's dependencies work, just like something in lib/dotnet.

**Comment by yishaigalatzer** [comment]
@dsplaisted I believe this was resolved already, with another approach. Please correct me if I'm wrong (and i'll re-open)
