### ISSUE TITLE
NuGet.Xplat - init and add commands

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1455]
nuget.exe add and nuget.exe init - Concurrency compatible with CoreCLR

**Comment by emgarten** [comment]
@deepakaravindr would you provide more details on this? This should extract under the existing locking which works xplat.

**Comment by yishaigalatzer** [comment]
@emgarten can you please review if this still needs to stick around?

**Comment by yishaigalatzer** [comment]
Repurposing for creating the xplat commands for init and add, and make sure the lock mechanisms are the same between desktop and .net core

**Comment by nkolev92** [comment]
Redundant now.
