### ISSUE TITLE
Nuget chooses wrong RID asset when no matching RID is present

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1457]
I suspect something gone afoul in your routing logic, perhaps you aren't ensuring that the lib/{tfm} pattern is rooted?

Package has the following content:

```
        "ref/dotnet/System.Threading.dll",
        "runtimes/win8-aot/lib/netcore50/System.Threading.dll",
```

When resolving for `.NETCore,Version=v5.0` it selects this runtime specific dll, despite no runtime being part of graph walk.  When resolving for `.NETCore,Version=v5.0/win7-x86` it also selects this runtime specific DLL despite win8-aot not being part of the runtime graph for win7-x86.

To repro you can restore the following project.json:

```
{
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-beta-23324",
    "System.Runtime": "4.0.21-beta-23324",
    "System.Threading": "4.0.11-beta-23324"
  },
  "frameworks": {
    "netcore50": {}
  },
  "runtimes": {
    "win7-x86": {}
  }
}
```

Against this source: https://www.myget.org/F/dotnet-core/api/v3/index.json

I found that the same bug exists in DNU, let me know if you'd like me to file it there.

/cc @yishaigalatzer @lodejard @davidfowl

**Comment by yishaigalatzer** [comment]
We are not clear on why this package is trying to mix the runtime.json and the runtime folder. 

Are you seeing the error we are seeing:

![image](https://cloud.githubusercontent.com/assets/1238711/10233176/dd012444-6841-11e5-9f59-22181cc28a42.png)

[project.lock.json.txt](https://github.com/NuGet/Home/files/6369/project.lock.json.txt)

**Comment by yishaigalatzer** [comment]
We think we do have a bug on our side, but we also think the package shouldn't be factored this way. Put all the runtimes in the runtime package

**Comment by ericstj** [comment]
Yeah, that was a bug in System.Threading that was fixed in the latest version.  http://www.myget.org/F/dotnet-core/api/v2/package/System.Threading/4.0.11-beta-23401

I fixed the bug when I saw this, but the behavior from nuget was clearly wrong so I filed this bug.

We never saw this before because I never had a package that only had an AOT asset without having a non-AOT asset.

**Comment by ericstj** [comment]
I reordered the assets in a package and actually hit this on a completely valid package, so it wasn't happening due to no matching RID.

The bug is here: https://github.com/NuGet/NuGet3/blob/007e3477862665eb3d9dcc3a03aa29133bde511c/src/NuGet.ContentModel/ContentItemCollection.cs#L98

When evaluating groups against criteria this algorithm doesn't account for the case when a group is "overly qualified"; that is it has a RID and a TFM when the criteriaEntry was only looking for a TFM.  As a result both lib/netcore50/foo.dll and runtimes/aot/lib/netcore50/foo.dll appear valid for the criteria TFM == ".NETCore,Version=v5.0"

Here's the package content that is enough to reproduce the problem.  The runtimes entry must appear first.  When this happens the first will be considered a match and the second won't be any better (since they use the same TFM) and nuget will return the RID-qualified asset incorrectly.

```
runtimes/aot/lib/netcore50/System.Reflection.Emit.dll
lib/netcore50/System.Reflection.Emit.dll
```

Stepping through in the debugger I see this algorithm consider `runtimes/aot/lib/netcore50/System.Reflection.Emit.dll` as a match for the criteria that only includes TFM.  I think the fix here would be to somehow make TFM-only criteria specify that the RID must not be present.

I believe this would be to add `[PropertyNames.RuntimeIdentifier, null]` here https://github.com/NuGet/NuGet3/blob/a5bc907d36ddaa8d4fa6c499e50d7ebf8993ed39/src/NuGet.Client/ManagedCodeConventions.cs#L201

/cc @anurse @emgarten

**Comment by yishaigalatzer** [comment]
@ericstj we are now building out of https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Client/ManagedCodeConventions.cs

**Comment by ericstj** [comment]
Then that fix would go here: https://github.com/NuGet/NuGet.Client/blob/3a9e61a52f0e9bc47380031bcddc0a73ff3883ea/src/NuGet.Core/NuGet.Client/ManagedCodeConventions.cs#L201

**Comment by ericstj** [comment]
Ping, this bug still exists.  Fix is a simple one liner.  Want me to submit a PR?

**Comment by yishaigalatzer** [comment]
Sure

Sent from my Windows Phone

**Comment by ericstj** [comment]
Do you have updated steps?  I first tried to follow these http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment, but they didn't bring down the Nuget.Client repo you pointed me at before.  I tried to just clone and build Nuget.Client and that failed with something that looked like it didn't have the right feeds configured.

**Comment by emgarten** [comment]
Clone https://github.com/NuGet/nuget.client
Everything is in one repository now, for you change you can use the nuget.core.sln

**Comment by emgarten** [comment]
I was able to repro this and made the fix described. The criteria should filter to runtime=null when falling back to runtime agnostic items as @ericstj said.
