### ISSUE TITLE
Improve error message when uninstall encounters locked files

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1458]
![image](https://cloud.githubusercontent.com/assets/1238711/10092059/2ffb2f5a-62f7-11e5-8fd5-42c6b14fcc5a.png)

Users mistake this for a fatal error, where it is actually pretty innocuous.

Can't come up with a better message at this point. But its worth a discussion

**Comment by phil-scott-78** [comment]
This is where I get antsy when I see this error - what exactly failed to uninstall? Did we fail to remove entries from the packages.config? Csproj file? Really it comes down to this - if they do a commit and push before restarting visual studio will that leave the project in an invalid state?

I suspect what's happening is the csproj and packages.config actually do get updated properly and what failed to uninstall were the contents of the package that have a file lock from IIS or something else. In that case a scary message might not be needed. It'd be ideal to queue up this removal when it can be done safely and don't even alert the user about this. If it MUST be removed at that moment then I'd much rather VS must be restarted than a little message I have to constantly worry about myself or others on my team catching before they do commits

**Comment by yishaigalatzer** [comment]
It is typically dlls in the packages folders. If you check them in then a restart is required.

I disagree with forcing a restart, that's just too  intrusive, but perhaps a nicer message like: Several files are locked and we recommend a restart to finish uninstalling the packages. With a tool tip showing what files are locked and if they are under source control.

The message is not small today, it is very obvious and prominent.

Sent from my Windows Phone

**Comment by csharpfritz** [comment]
Can we output a detailed list of the locked files in the package manager
log window?

**Comment by phil-scott-78** [comment]
I do at least get the error message which contains the file which got me started on my debugging

```
Access to the path 'C:\Projects\my_app\packages\MediatR.1.0.0.0\lib\portable-net45+win+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10' is denied.
```

This is actually pretty easy for me to reproduce. I get it about 50% of the time when doing any upgrades to a nuget package. So I ran some procmon. Nothing stood out that much besides one cultprit - it looks like nCrunch was reading from these folders around the same time. I disabled nCrunch and I was able to update around 15 nuget packages in my solution without a problem.

@hmemcpy - I suspect you are running ncrunch too - right? My assumption is that in 2013 they relied on the modal window of the package manage to let those actions perform front and center. With it no longer being a model ncrunch is continuing to execute (which in my case involves not just compiling but copying files up to a remove server for processing) while the package manager is doing it's thing.

**Comment by remcomulder** [comment]
It's definitely possible that NCrunch could be responsible for short-term file locks during large updates from NuGet.

Best practice is that you should always disable NCrunch when updating NuGet packages.

There is an active feature request for NCrunch to suppress all activity while NuGet is updating packages - https://ncrunch.uservoice.com/forums/245203-feature-requests/suggestions/5719302-pause-while-nuget-is-installing-or-updating-packag

.. To date this hasn't yet been implemented, as I haven't found a reliable way for NCrunch to be notified of when NuGet starts and finishes its updating process.  If anyone can advise me of a way to do this, I would be eternally grateful!

**Comment by yishaigalatzer** [comment]
@remcomulder there is an API for eventing when installing/uninstalling packages - http://docs.nuget.org/Create/Extensibility-APIs

**Comment by remcomulder** [comment]
Excellent thank you!!! :)

**Comment by phil-scott-78** [comment]
@remcomulder let me know if you need any help with testing this. I can reproduce pretty consistently.

**Comment by nkolev92** [comment]
At this point we are not going to do any non-critical servicing for packages.config style projects.
