### ISSUE TITLE
20 character limit for prerelease version strings

### ISSUE THREAD

**Issue by jmezach** [NuGet/Home#1459]
I've just hit a limitation when creating NuGet packages when the prerelease version part is longer than 20 characters, for instance: 1.0.0-alpha20150925093600-FeatureX. I was able to find an issue [3426](https://nuget.codeplex.com/workitem/3426) on the CodePlex site that describes this behavior, but wasn't able to find one here.

I can sort of understand why this limitation exists when you push packages to NuGet.org, but I'm perfectly able to upload a package with such a version (by manually modifying it) to our internal feed (hosted on a ProGet server). Wouldn't it be better if this was treated as a warning (much like the existing validations already performed by nuget.exe), rather than an error so that it doesn't block folks who don't upload their packages to NuGet.org anyway?

**Comment by yishaigalatzer** [comment]
The issue with long names is that they eventually leads to pathtoolong exceptions when laying out the packages. So we don't plan to remove this limitation, it is entirely within reason.

Also please hold off on Pull Request until the issue is discussed, it will save the frustration of rejected PRs.

**Comment by yishaigalatzer** [comment]
To be honest, we should revisit this once dotnet fixes the pathtolong issue on windows (and I'm hearing they just might).

Until then this will just create more pain than value.

**Comment by silver-xu-webjet** [comment]
Windows is pathetic in terms of pathtoolong issue and will lead more UI developers moving towards macs.

**Comment by moerwald** [comment]
Has there been any progress on this topic? 

We're creating NuGet packages on feature/bugfix branches. Since we're using this schema "bugfix/QPSTEGW-7387"|"feature/QPSTEGW-7387" the 20 characters limit is reached very fast. Where "QPSTEGW-7387" is the JIRA project and ticket number.
