### ISSUE TITLE
Different install behavior when specifying version

### ISSUE THREAD

**Issue by vtbassmatt** [NuGet/Home#1460]
This is nuget.exe 3.2.0.10516.

I have three private feeds configured in addition to nuget.org. `nuget install <id>` works for a package that is only in the NuGet Gallery, but fails if I specify the version number.

```
C:\temp>nuget install Newtonsoft.Json -version 7.0.1
Attempting to gather dependencies information for package 'Newtonsoft.Json.7.0.1' with respect to project 'C:\temp', targeting 'Any,Version=v0.0'
Using credentials from config. UserName: *redacted*
Please provide credentials for: https://*redacted*/nuget/index.json
Using credentials from config. UserName: *redacted*
UserName:
Password:
Please provide credentials for: https://*redacted*/nuget/index.json
UserName:
Password:
Please provide credentials for: https://*redacted*/nuget/index.json
UserName:
Password:^C
```

```
C:\temp>nuget install Newtonsoft.JSON
Attempting to gather dependencies information for package 'Newtonsoft.JSON.7.0.1' with respect to project 'C:\temp', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Newtonsoft.JSON.7.0.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Newtonsoft.JSON.7.0.1'
Resolved actions to install package 'Newtonsoft.JSON.7.0.1'
Adding package 'Newtonsoft.Json.7.0.1' to folder 'C:\temp'
Added package 'Newtonsoft.Json.7.0.1' to folder 'C:\temp'
Successfully installed 'Newtonsoft.Json 7.0.1' to C:\temp
```

This is intermittent: Sometimes it can correctly pull from the NuGet Gallery even with a version specified.

**Comment by yishaigalatzer** [comment]
Based on this input, I'm going to guess the following: If you do provide your username and password things do work.

This is why: NuGet can't guess where the package comes from and accesses all sources in parallel, this is a safe race (unless you ^C it and abort the whole thing).

**Comment by vtbassmatt** [comment]
I'm having a hard time reproing today, so I can't verify what you said. I'll assume you're right, but that leaves me with two questions:
1) Are you saying I need to enter my credentials before NuGet will proceed, or is the race happening in the background and it will eventually complete correctly?
2) I have credentials for all the private feeds saved in my machine nuget.config. When I give an explicit -Source, nuget.exe uses them. Is the behavior difference intentional when leaving -Source unspecified?

**Comment by yishaigalatzer** [comment]
1. You need to enter your credentials in this case.
2. Can you check that all of your sources are accessible, this could happen if your password doesn't match. We don't expect prompting if the password are in your nuget.config and are valid. If we do that's a bug. I believe we have a test covering this scenario, going to look into it.
3. If you never want to get prompted (which is what you would do on a CI build, use the NonInteractive flag http://docs.nuget.org/consume/Command-Line-Reference)

**Comment by vtbassmatt** [comment]
I confirmed that I can access all of the sources without being prompted for
a password if I specify -source. Seems like there may be a bug here.

**Comment by deepakaravindr** [comment]
@vtbassmatt, I just tried and it seems to work for me without the -Source switch.
- When you say it works with the -Source switch, Do you use the URL or the package source name?
- Can you tell us how your nuget.config looks like? Mine looks like the following. And, note that I added the private feed source 'test', to my nuget.config, using nuget.exe sources command. (https://docs.nuget.org/consume/command-line-reference#sources-command)

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="test" value="https://www.myget.org/F/< privatetestfeedname >/api/v2" />
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
  </disabledPackageSources>
  <packageSourceCredentials>
    <test>
      <add key="Username" value="< username >" />
      <add key="Password" value="< encryptedPassword >" />
    </test>
  </packageSourceCredentials>
</configuration>
```

**Comment by vtbassmatt** [comment]
I use the URL as the argument to -Source. All of my sources were added by `nuget sources add`. Here's my nuget config, with sensitive portions of URLs and username/password removed:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="MyGreatFeed" value="https://< account > .pkgs.visualstudio.com/DefaultCollection/_apis/packaging/MyGreatFeed/nuget/index.json" />
    <add key="Wotd.Lib.CI" value="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/Wotd.Lib.CI/nuget/index.json" />
    <add key="Wotd.Release" value="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/Wotd.Release/nuget/index.json" />
    <add key="Wotd.Gui.CI" value="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/Wotd.Gui.CI/nuget/index.json" />
    <add key="ThisFeedFull" value="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/This_feed_is_full/nuget/index.json" />
  </packageSources>
  <disabledPackageSources />
  <apikeys>
    <add key="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/MyGreatFeed/nuget/index.json" value="< key >" />
    <add key="https://www.nuget.org" value="< key >" />
    <add key="http://nuget.gw.symbolsource.org/Public/NuGet" value="< key >" />
  </apikeys>
  <activePackageSource>
    <add key="Wotd.Release" value="https://< account >.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/Wotd.Release/nuget/index.json" />
  </activePackageSource>
  <packageSourceCredentials>
    <MyGreatFeed>
      <add key="Username" value="< user >" />
      <add key="Password" value="< pass >" />
    </MyGreatFeed>
    <Wotd.Lib.CI>
      <add key="Username" value="< user >" />
      <add key="Password" value="< pass >" />
    </Wotd.Lib.CI>
    <Wotd.Release>
      <add key="Username" value="< user >" />
      <add key="Password" value="< pass >" />
    </Wotd.Release>
    <Wotd.Gui.CI>
      <add key="Username" value="< user >" />
      <add key="Password" value="< pass >" />
    </Wotd.Gui.CI>
    <ThisFeedFull>
      <add key="Username" value="< user >" />
      <add key="Password" value="< pass >" />
    </ThisFeedFull>
  </packageSourceCredentials>
</configuration>
```

**Comment by yishaigalatzer** [comment]
These look like VSO feeds, is that correct?

**Comment by vtbassmatt** [comment]
Correct.

**Comment by yishaigalatzer** [comment]
I'm not sure how these are supposed to work, I'm following up with the VSO team (they seem to be gone for the day, so perhaps will hear tomorrow what is going on)

**Comment by vtbassmatt** [comment]
I'm on the VSO code sharing team :) We have some folks out of office today.

We just tried the exact same scenario on a coworker's machine and it worked
for him. Maybe there's something wacky in my nuget.config?

**Comment by yishaigalatzer** [comment]
That's why I asked about the passwords not being applicable. Lets get Zache Renner involved tomorrow, he was looking into this area before

**Comment by vtbassmatt** [comment]
I'm not sure how the service is involved, though. When I specify a -source,
it correctly reads my credentials from nuget.config and works. When I
don't, I'm sometimes prompted for credentials (although it's intermittent).

**Comment by vtbassmatt** [comment]
I can't repro consistently. I will reactivate if I get a consistent repro. Probably garbage in my nuget.config.
