### ISSUE TITLE
UWP restore adds all target files when the build folder mixes TFM folders and root level targets

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1461]
After converting a project.json-based class library to be a portable library, nuget restore no longer puts *.nuget.props and *.nuget.targets files in my project directory.

[Repro project](https://github.com/aarnott/nugetissue1461)

**Comment by AArnott** [comment]
When I modify the package I'm depending on to have a build folder with various TxF folders in it, the imports are added, but _all_ the .props and .targets files, from _all_ the folders are imported to the project instead of just the one from the most appropriate TxF folder.

**Comment by AArnott** [comment]
The bug where _all_ targets and props files are imported instead of just one TxF folder's being imported is `doubleImports` branch of the repo linked in the original repro steps. 
Should I file a separate bug for the multiple imports problem or should we repurpose (and retitle) this bug to track that? I think you already have another issue tracking the possible DCR of making project.json import files in all the same scenarios that packages.config did (#965).

**Comment by emgarten** [comment]
I've updated the title.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@26a6fa6cfc92f577e132d073e4a90ac3425cc8da

**Comment by AArnott** [comment]
Thanks, @emgarten. Can you briefly summarize the design of the fix? If my package has this structure:

```
build\PackageName.props
build\net451\PackageName.props
build\wp8\PackageName.props
```

When will each one be used? Are the TxM folders preferred when applicable?

**Comment by emgarten** [comment]
It will follow the same rules as packages.config scenarios for the build folder now. The root level folder will be used as a fallback if there are no compatible TxM folders.

Example:
Project framework -> props 
uap10.0 -> build\PackageName.props
net46 -> build\net451\PackageName.props
wp8 -> build\wp8\PackageName.props

**Comment by AArnott** [comment]
Great! thanks.
