### ISSUE TITLE
Commandline and UI give different results when installing a package.

### ISSUE THREAD

**Issue by nanderto** [NuGet/Home#1462]
have set up a private feed for nuget on our TFS server, using the nuget server, nuget package. This has been succesfuly running but now I need to move it to a new server.

On the new server I can use the settings to point to the new server. I can get the packages to show up in the UI, but when I attempt to download I get an error 

Unable to connect to the remote server

from the command line I get:

Install-Package : Unable to connect to the remote serverAt line:1 char:1
- INstall-package BrXXXXXXXs.GlobalConstants -source  http://tfs.brXXXXXXXs.c ...
- ```
  ```
  - CategoryInfo          : NotSpecified: (:) [Install-Package], WebException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
  
  I have compared the 2 end points and I do not see what is different. I can access both thru a browser.

---

Thanks Noel

**Comment by yishaigalatzer** [comment]
Sorry, but there is not enough information to help you with this request. Perhaps look at a fiddler trace between the two and compare.

**Comment by yishaigalatzer** [comment]
ping, is this still an issue?

**Comment by nanderto** [comment]
yes its still an issue, fiddler did not help. Still trying to fix this.

**Comment by yishaigalatzer** [comment]
@maartenba can you point @nanderto to the new nuget.server package you just produced?

**Comment by maartenba** [comment]
The new package (prerelease!) can be installed / updated from the `https://www.myget.org/F/nugetbuild/api/v3/index.json` package source.

Basically run an update of the existing NuGet.Server package you have and should be fine.
Note that the very first start of the server may be a bit slower because it restructures the packages folder.

**Comment by nanderto** [comment]
Thanks for the help, and the speedy reply. I will try this out when I return to work in new year, and provide update then. Thanks

**Comment by rrelyea** [comment]
@nanderto - going through old bugs. Any update?

**Comment by nanderto** [comment]
I abandoned trying to fix this, we just manually copied the nuget packages to the directory. Going to move onto using the built in Package Management in TFS
