### ISSUE TITLE
Unable to find package 'PowerThreading'

### ISSUE THREAD

**Issue by veleek** [NuGet/Home#1464]
I'm trying to install the [PowerThreading package on Nuget.org](https://www.nuget.org/packages/PowerThreading/) but Install-Package always throws an error saying it can't find the package. 

Even more interesting, when I specify a version, it seems to be aware that version exists but fails after gathering dependencies.  Output from the Package Manager Console, running the latest version of NuGet in Visual Studio 2015.

```
PM> Find-Package PowerThreading -ExactMatch

Id                                  Versions                                 Description                                          
--                                  --------                                 -----------                                          
PowerThreading                      {20120420.0.0}                           Wintellect's own Jeffrey Richter has produced the ...


PM> Find-Package PowerThreading -ExactMatch | Install-Package
Install-Package : Unable to find package 'PowerThreading'
At line:1 char:43
+ Find-Package PowerThreading -ExactMatch | Install-Package
+                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

PM> Install-Package PowerThreading -Version 20120420.0.0
Attempting to gather dependencies information for package 'PowerThreading.20120420.0.0' with respect to project 'Microsoft.XboxLive.Borg.Common', targeting '.NETFramework,Version=v4.5'
Install-Package : Package 'PowerThreading' is not found
At line:1 char:1
+ Install-Package PowerThreading -Version 20120420.0.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand 
```

**Comment by emgarten** [comment]
Which nuget.org source are you using v2 or v3?

**Comment by veleek** [comment]
I have V3 configured.

**Comment by emgarten** [comment]
@bhuvak it looks like this package is missing from the registrations.

@veleek you can work around this by using https://www.nuget.org/api/v2/  instead of the v3 source.

**Comment by veleek** [comment]
I'll give it a shot but it may be a bit more complicated because all the other team members are going to need to re-configure their machines and we'll have to get these settings propagated to our build team as well.

**Comment by veleek** [comment]
This appears to be working with v2 instead of v3.  What is the process of getting a package properly registered with v3?

**Comment by yishaigalatzer** [comment]
@maartenba can you please take care of this issue?

CC @joyhui

**Comment by maartenba** [comment]
@veleek can you try again on API v3? I have re-generated the registration for the package.
