### ISSUE TITLE
NuGet reports Windows 8 packages as "Windows 0.0"

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#1465]
I've run into a bug under the new ASP.NET 5 `project.json` format where the package version will be listed as **Windows 0.0** ([example](https://www.nuget.org/packages/Enu/)) when uploaded to the website. Steps to reproduce:

**1.**

``` bash
cd ~
git clone -b nuget-snapshot https://github.com/jamesqo/enu.git
```

**2.** Change the `project.json` package ID to a different name
**3.** Open the solution in Visual Studio and build
**4.** Upload it to [nuget.org](https://www.nuget.org/) and the supported versions will be:
- DotNET 5.0
- .NETFramework 4.5
- Windows 0.0

**Comment by yishaigalatzer** [comment]
Moved to gallery https://github.com/NuGet/NuGetGallery/issues/2719
