### ISSUE TITLE
error message updating packages when there is at least one pre-release package.

### ISSUE THREAD

**Issue by jimmymain** [NuGet/Home#1466]
Hi,

I have a pre-release package installed (stylecop.analyzers)
If I type `update-package`, I get the error below.

This means I have to supply the `-pre` parameter, and now every single package in the solution will be updated to the latest pre-release. This is **not** intuitive.

The default behaviour should be to ignore the updates to packages that are pre-release, instead of complaining that they don't exist (they surely do).

```
update-package

Attempting to gather dependencies information for multiple packages with respect to project 'Utility\Palantir.Utility', 
targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages

update-package : Unable to find package 'StyleCop.Analyzers'. 
Existing packages must be restored before performing an install or update.
```

**Comment by yishaigalatzer** [comment]
You can call Update-Packate with packageId, instead of calling Update-Package.

The error should definitely be improved.

**Comment by johnataylor** [comment]
This does appear to be a problem. It appears that we don't automatically allow packages that are already prerelease in the project when you run update all.

This is probably a fix around NuGetPackageManager.cs l.571 PrunePrereleaseForStableTargets should probably always be give the current list of packages so packages that are currently prerelease can automatically remain prerelease.
