### ISSUE TITLE
NuGet.PackageManagement package is missing dependencies

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1469]
The 3.2.0 PackageManagement package does not define any dependencies.
https://www.nuget.org/packages/NuGet.PackageManagement/

The dependencies are now defined in the project.json file and these are not being picked up at pack time.

**Comment by MeniZalzman** [comment]
We resolve this issue with the move to the new repository

**Comment by feiling** [comment]
verified that this is fixed in NuGet.PackageManagement 3.3.0
