### ISSUE TITLE
Support for runtime light-up dependencies

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#1471]
We need to add a reference to System.Runtime.Loader FX library to one of our projects. The project targets portable-net452 like so:

"frameworks": {"dotnet": { "imports": "portable-net452" } }

It is supposed to be used on both CoreCLR and Desktop FX. At runtime we detect what CLR we run on and either use the Desktop FX assembly resolver or the Core CLR AssemblyLoadContext implemented in System.Runtime.Loader.

However adding a NuGet reference “System.Runtime.Loader": “4.0.0-beta-23321” to project.json results in an error:

“System.Runtime.Loader 4.0.0-beta-23321 provides a compile-time reference assembly for System.Runtime.Loader on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-anycpu.
Some packages are not compatible with .NETFramework,Version=v4.6 (win-anycpu).”

We would like to tell NuGet to not worry about the runtime assembly, since we are actually not going to use the reference unless running on CoreCLR.

**Comment by yishaigalatzer** [comment]
@emgarten can you take a look and make a recommendation?

**Comment by nkolev92** [comment]
Closing this as redundant in the post project.json world. 

@tmat Please reopen if you still have similar issues.
