### ISSUE TITLE
nuget install -ExcludeVersion not working with packages.config

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1473]
_From @vonlipwigmoist on September 28, 2015 9:44_

with nuget version  3.2.0.10516 the following command does not work as expected:
nuget install packages.config -ExcludeVersion
The destination directory still contains the version number while the documentation states that it shouldn't.
If a packageId is given instead of a packages.config file it works as expected. 

_Copied from original issue: NuGet/NuGetGallery#2704_

**Comment by RichiCoder1** [comment]
_bump_

**Comment by RanjiniM** [comment]
This is a regression from 2.8.6. We will fix it in 3.3 commandline

**Comment by RanjiniM** [comment]
Fixed in 3.3 commandline

**Comment by feiling** [comment]
verified with nuget.exe 3.3.0.208
