### ISSUE TITLE
NullReferenceException : Cannot install Aspose.Email into VS2015 Console App.

### ISSUE THREAD

**Issue by nambrose** [NuGet/Home#1476]
Version of Nuget is 3.2.60914.10516

Make a blank C#/Console app

Install Aspose.Email

Attempting to gather dependencies information for package 'Aspose.Email.5.7.0' with respect to project 'DVS', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Aspose.Email.5.7.0' with DependencyBehavior 'Highest'
Resolving actions to install package 'Aspose.Email.5.7.0'
Resolved actions to install package 'Aspose.Email.5.7.0'
Install failed. Rolling back...
Package 'Aspose.Email 5.7.0' does not exist in project 'DVS'
Package 'Aspose.Email 5.7.0' does not exist in folder 'C:\Source\Prototypes\NicholasA\DVS\packages'
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========

VS2015 info:

Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Professional

Visual Basic 2015   00325-60002-30968-AA575
Microsoft Visual Basic 2015

Visual C# 2015   00325-60002-30968-AA575
Microsoft Visual C# 2015

Visual C++ 2015   00325-60002-30968-AA575
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20711.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

BitTitan Build Ide Package   1.0
VS IDE Package to help facilitate BitTitan build.

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure HDInsight HQL Service   2.0.2200.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2200.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30728.1602

Microsoft Team Foundation Server 2015 Power Tools   14.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

Paket.VisualStudio   1.0
Manage your Paket dependencies from Visual Studio!

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

Visual Studio Tools for Universal Windows Apps   14.0.23121.00 D14OOB
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Windows Installer XML Toolset   3.10.0.2103
Windows Installer XML Toolset version 3.10.0.2103
Copyright (c) Outercurve Foundation. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

**Comment by yishaigalatzer** [comment]
Just tried it, and the package installs without a hitch (Console App 4.5.2, api.nuget.org/v3/index.json).

Is there anything else special about the project/solution?

**Comment by nambrose** [comment]
Hmmm, it was just a brand new Console app. Just a blank Program.cs
I will try to see if there is anything special. I may have another machine I can try to see if it also happens there.

**Comment by yishaigalatzer** [comment]
I tried again this time with dependency version highest, still works fine. Would help if we can get more specific repro steps or an accurate callstack to see if we can pinpoint things.

Can you share your nuget.config (s)?

**Comment by nambrose** [comment]
Repro was literally
- Make C# Console app with no specific nuget.config
- Try to add the package

is there a way to get a better call stack than the one I provided ?

**Comment by yishaigalatzer** [comment]
I get it, but it doesn't repro for me with exact same steps.

Its tricky to get a callstack, but if you are willing to help that would be great!

You need to attach another instance of visual studio, and turn on catching thrown exception (handled). Then look for a nullref, they are rare so that's going to make it easier.

You can find symbols and sources on symbolsource.org

**Comment by emgarten** [comment]
It looks like the package is failing to download from a v3 source.
- Do any packages installs work? 
- Is it only Aspose.Email that fails for you? 
- Does this work: _Install-Package Aspose.Email -Source https://www.nuget.org/api/v2/_

If you are able to get it in the debugger as @yishaigalatzer mentioned and see why the download is failing that would very helpful also.

**Comment by nambrose** [comment]
Other package installs are working OK. 

Install-Package Aspose.Email -Source https://www.nuget.org/api/v2/ - This worked

**Comment by nambrose** [comment]
I can trap the exception but even when I add the symbols server into my debugger, I only get an assembly dump. Anything special I have to do to force it to load symbols for NuGet ?

EDIT: Synbolsource.org appears to be down for me...

**Comment by emgarten** [comment]
There may be an issue with the Aspose.Email package on v3 based on what you are seeing.

**Comment by maartenba** [comment]
Not able to reproduce this issue either. @nambrose can you run the following requests using curl or Fiddler and see if they return data?
- `https://api.nuget.org/v3/registration1/aspose.email/index.json` should return a JSON document. The last entry of this document should have `packageContent: "https://api.nuget.org/packages/aspose.email.5.7.0.nupkg"` in it
- `https://api.nuget.org/packages/aspose.email.5.7.0.nupkg` should return the NuGet package. Can you try unzipping it?

Server-side looks good from my side, but then again it may be based on CDN location.

**Comment by nambrose** [comment]
Yes,I  can download via that link and successfully unzip

and my JSON seems OK too ?
JSONLint validates it ...

**Comment by yishaigalatzer** [comment]
@nambrose can you share the fiddler trace?

**Comment by yishaigalatzer** [comment]
One more set of thoughts on this:
1. Can you share the content of c:\users{userName}.nuget\packages\Apose.Email
2. Can you share your nuget.config

Would be interesting to delete c:\users{username}\packages and see if the issue goes away. But please take a copy first so we can see the root cause of the nullref.

It would be interesting to attach a debugger and try to get the call stack for the nullref, we might be able to learn more.

@MeniZalzman - Can you help with directions?

**Comment by nambrose** [comment]
Hi, I did attach the debugger but had trouble getting the symbols loaded so all I got was an assembly dump.
I'll try to get ahold of that package directory but for now I went ahead and installed the 2.0 sources as I needed to get stuff done.

**Comment by yishaigalatzer** [comment]
We are working on creating a debug build that we can share for you to be able to debugger better. Please shoot me an email y i g a l a t z @ msft.com

**Comment by nambrose** [comment]
Done

**Comment by nambrose** [comment]
Debugged a little with Yishai and Aspose.Email 5.8.0 installs fine (my original version was 5.7.0 which still fails)

EDIT:
I installed 5.7.0 with the prod version and it failed again.
Then I went to the debug bits to install 5.7.0 and trap the failure ... and now 5.7.0 works for both the debug and production bits.

i guess I will close this out and keep an eye on any re-occurences ?

Pretty irritating that it went away like that
