### ISSUE TITLE
Project that find themselves at varying nesting depths cannot find `packages/`

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#1477]
I do not know if this is a right venue for questions, but I cannot find a mailing list or a google group where I can communicate with other users. If there is one, please point me to one and close this.

We have some projects that can be pulled as Git submodules into different solutions. The projects sometimes end up at a different depth from the solution directory. Since NuGet always inserts a single relative reference to the downloaded unpacked libraries, it works only if the project is at the same depth as where the reference to a NuGet package was added (e. g., `../../packages/ .... /mylibrary.dll`).

So far I have to manually edit each project that is used this way to add a property (this is only for MsBuild, since VS provides this same property pointing to the solution folder)

``` xml
  <PropertyGroup>
    <SolutionDir Condition="$(SolutionDir) == '' And Exists('..\..\..\*.sln')">..\..\..\</SolutionDir>
    <SolutionDir Condition="$(SolutionDir) == '' And Exists('..\..\*.sln')">..\..\</SolutionDir>
    <SolutionDir Condition="$(SolutionDir) == '' And Exists('..\*.sln')">..\</SolutionDir>
  </PropertyGroup>
```

Then I modify references added by NuGet as

``` xml
  <ItemGroup>
    <Reference Include="FParsec">
      <HintPath>$(SolutionDir)packages\FParsec.1.0.1\lib\net40-client\FParsec.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
```

replacing some string of double-dot references, like `../..` with `$(SolutionDir)`.

Then I need to maintain the change in case of a package upgrade, by re-editing the project file manually.

Can something be done about that? I thought about creating a package that contains a special target that transforms the Reference item collection, but the catch 22 is that the transformer package suffers from the same problem in locating its `.props` and `.targets` files...

Maintaining working link to a NuGet package becomes a living horror, and we seem to be getting more of such projects. Help!!!

**Comment by yishaigalatzer** [comment]
This is not a discussion group in general, stackoverflow is a good place for this kind of question.

In general the solution long term for this is to move to project.json based projects. It is currently a bit limited (no content support) and it is not fully tested on all project types, but it avoid using hard links in the project (for similar reasons to what you are experiencing).

A simple suggestion would be to embed the projects at the right level (I know that sounds pretty bad, but its a simple rule to follow).

**Comment by kkm000** [comment]
@yishaigalatzer: Thanks for the response. Moving to a different project system is hardly an option, given our sheer codebase size, as is reorganizing it to a single level. Unfortunately, we are talking an old, large, quirky codebase complicated with additional tools and services putting additional limitations on the code structure.

I am wondering though, why does not NuGet even try to use `$(SolutionDir)`? The variable is readily supplied by the Visual Studio, and can be technically provided with MsBuild on command line. What was the downside of this variable's use that the decision was made not to use it in NuGet?

**Comment by yishaigalatzer** [comment]
1. NuGet doesn't know anything about msbuild when it adds references, it merely calls the DTE.AddReference and each project system is responsible to do whatever it needs to do. So you end up with hint paths etc.
2. Packages folder is configurable at the solution level (or to a global folder) by changing nuget.config at any level above the solution. So solution dir is just a good default, but not the right thing every time.

Which is why we are moving away from all of this to use project.json to define the package dependencies, and at that point the package folder is global across the machine (of course you can configure it differently), and nothing is touching the project anymore. It is still the responsibility of the project system/msbuild to add the references dynamically.

**Comment by kkm000** [comment]
I see, that's a clear explanation, thanks!
