### ISSUE TITLE
Visual Studio 2015 with Nuget 3.2 + PCL targetting Windows Universal 8.1 throws NullReferenceException

### ISSUE THREAD

**Issue by martingem** [NuGet/Home#1478]
I am trying to make PCLs for my Windows Universal 8.1 application. It seems in VS 2015 that Nuget doesn’t like targeting anything lower than 4.6 and I can’t do anything. Everything in a WindowsPhone/WinRT project with Shared works, but when it comes to PCL that targets both, Nuget 2015 3.2 handles very badly the fact that I want my PCL to target both of Universal 8.1 (and up).

Repro steps:
1-      Make a Windows Runtime Library (for 8.1). 
2-      Try to add Crittercism via UI or Install-Package Crittercism
3-      Notice v4.6 Profile=XYZ couldn’t find any package.

So I try to:
1-      Change Framework to 4.5.1. The .csproj shows 4.5
2-      Try again from 2 above
3-      Notice the same happens.

When I downgrade to 4.5 (fully from 4.6 -> 4.5), I get "object is not an instance of an object" when I try to open the Manage Nuget and I can’t select my project in the dropdown

Finally, I added the v2’s nuget.org api, Nothing different, it fails.

**Comment by emgarten** [comment]
Crittercism does not contain any PCL compatible libraries:

![image](https://cloud.githubusercontent.com/assets/6381138/10150379/ff1565c2-65f3-11e5-8d56-e21c2037f311.png)

Installing that package should give you an error message saying that there are no compatible items for your target framework, is that what you saw?

The crash looks interesting, can you find the stack from this in your visual studio ActivityLog.xml file?

If you create a new library with 4.5 instead of retargetting does it work? Did you have any packages installed before the retarget from 4.6 to 4.5?

**Comment by martingem** [comment]
_Crittercism does not contain any PCL compatible libraries_
I can't deny that for Crittercism at least.

_Installing that package should give you an error message saying that there are no compatible items for your target framework, is that what you saw?_
I cannot get to that. For Crittercism it was what you said and I was unaware that it didn't support PCL. But for others, it works under 2013.

For instance, Splat (by paulbetts) works in a project targetting _v4.5 + WinPhone 8.1 + Windows 8.1_ (what I want as a minimum) under Visual Studio 2013, and throws an exception in vs 2015, like so:
![capture](https://cloud.githubusercontent.com/assets/2473921/10150908/72fc91ec-6610-11e5-9acf-84f903f00df7.PNG)
(VS 2015 on Left, 2013 on Right)
(On VS2015: Right Click > Manage NugetPackage > Throws exception)

You can find the ActivityLog.xml [here](https://onedrive.live.com/redir?resid=5D18D0287E371AC!345514&authkey=!APMbMyv5wvaI1Hs&ithint=file%2czip).

**Comment by emgarten** [comment]
Doesn't look like the error made it into the activity log here. What are your steps for reproing the crash? Create a PCL targeting .NET 4.6 and then change it to .NET 4.5, then open NuGet?

In your original repro steps above you said install-package could not find the package, that is where the compatibility error should have been displayed.

**Comment by martingem** [comment]
Repro steps:
1- Make a Windows Runtime Library (for 8.1) -> _It automatically targets v4.6 in VS2015._
2- Change target framework to v4.5 + WinPhone 8.1 + Windows 8.1
3- try right-click -> Manage Nuget Package
3.1- Object reference not set to an instance of an object.
3.2- Check the Nuget Package Console, the project is not there.

**Comment by emgarten** [comment]
There are two issues here.
1) Before re-targeting, does the correct compatibility message show when installing Crittercism into the PCL.
2) Crashing when opening the NuGet UI after re-targeting to net45+wpa81+win81

Are you seeing #1?

I am unable to repro #2. What version of windows 10 tools are you using? I don't have a "Windows Runtime Library (for 8.1)" template, and the Windows Runtime projects I tried do not have a project.json file like your screen shot.

**Comment by martingem** [comment]
1) I cannot install Crittecism into a PCL targetting multiple platforms (e.q. in this case Windows Phone 8.1 and Windows 8.1)
2- It is right after, yes. Everything closed from scratch, in a sentence: New Project -> Windows Runtime Library (autotargets v4.6) -> net45+wpa81+win81 -> Manage NugetGet Packages -> throws exception

**Comment by yishaigalatzer** [comment]
@emgarten please investigate further to figure out what is going on.

**Comment by yishaigalatzer** [comment]
Tried to repro again today
1. I don't see a nullref, I do see the error emgarten expected for Crittercism
2. Splat installs fine

![image](https://cloud.githubusercontent.com/assets/1238711/13720186/f419dbc2-e7b6-11e5-9928-de0c680a41d7.png)

![image](https://cloud.githubusercontent.com/assets/1238711/13720183/dddbfc64-e7b6-11e5-8c29-8af89c38ecc6.png)

**Comment by yishaigalatzer** [comment]
This is with 3.4 + Visual Studio 2015 Update I
