### ISSUE TITLE
"nuget.exe restore project.json" creates *.nuget.props and *.nuget.targets files with incorrect name after project rename

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1479]
Package restore within VS and at command line based on solution works fine. 
Package restore directed at a particular project's project.json file incorrectly produces *.nuget.targets files named after the original name of the project instead of its new name. As demonstrated by the following repro steps:
## Prebaked steps

```
git clone https://github.com/AArnott/NuGetIssue1479
cd NuGetIssue1479\ClassLibrary12
nuget restore project.json
msbuild
```

Build fails with error that the import was not found.
## Manual steps
1. Create a new C# portable library (uap+dnxcore+net46)
2. Add any package dependency to project.json that will result in adding imports to the project (e.g. `Nerdbank.GitVersioning` version `1.1.47-rc-g58708fcf8c` from package source `https://ci.appveyor.com/nuget/nerdbank-gitversioning-oejyfd1q8igm`)
3. Build project in VS. Verify that *.nuget.targets was added on disk and matches project name.
4. Rename project in VS.
5. Delete *.nuget.targets file(s) from project directory.
6. Build project in VS. Verify that *.nuget.targets was added on disk and matches project name.
7. Delete *.nuget.targets file(s) from project directory.
8. Run "nuget.exe restore" from the command line in solution directory
9. Verify that *.nuget.targets was added on disk and matches project name.
10. Delete *.nuget.targets file(s) from project directory.
11. Run "nuget.exe restore project.json" from the command line in _project_ directory
12. Observe from the output and directory listing that the generated _.nuget.targets file is using the *wrong_ name (the old project name).

**Comment by AArnott** [comment]
This is probably because in the execution path for project.json, the .props and .targets file names are based on the `AssemblyName` property of the project rather than the `$(MSBuildProjectName)`. Since the automatic imports are actually based on the `$(MSBuildProjectName)`  however, this leads to a malfunction in the build as the files are not imported as required.

**Comment by emgarten** [comment]
Restore when passing the project.json file as the input is very limited. It will be treated as a standalone file, and msbuild will not be used. No project to project references will be taken into consideration and the targets will be generated using the directory name.

When restoring the solution file nuget uses the project file name as the name, this may need to be updated to use the same property as msbuild for the name.

**Comment by nkolev92** [comment]
This is now redudant. 
We are not doing any servicing in the project.json world.
