### ISSUE TITLE
Packages are missing when selected pre-release option!

### ISSUE THREAD

**Issue by hmemcpy** [NuGet/Home#1480]
We have a custom feed on MyGet for our pre-release packages.
When I select this feed, and search for the package, when I select "include prerelease", it disappears from the search results.

See gif:
![](http://i.imgur.com/sDo38dk.gif)

Tried with both NuGet 3.2.609... build, and 3.1.607....
Colleague reports this works fine for him with 3.1.607

What should I be looking for?

**Comment by hmemcpy** [comment]
Gah! It became obvious after I tried installing it from the console:

> Install-Package : Could not install package 'NServiceBus 6.0.0-unstable0909'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the 
> package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My project was .NET 4.5, but the new version requires 4.5.1 at least. There's no way to know this, of course, but the UI doesn't give any hint whatsoever!!
Just disappearing the incompatible packages is bad UX.

**Comment by csharpfritz** [comment]
The package does not meet your filter, and you want it displayed regardless?

**Comment by hmemcpy** [comment]
@csharpfritz well, I didn't know that they didn't meet my filter, so I thought that was a bug. So yes, I would expect them to appear, maybe become grayed out (with a message stating the reason for incompatibility).

The best thing would be for NuGet to offer to upgrade my target framework, but that's another story.

**Comment by nkolev92** [comment]
I am not able to reproduce this issue. If you are still able to reproduce this problem, please file a new issue.
