### ISSUE TITLE
Nuget Pack doesn't include resource files (single localized package approach)

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1482]
_From @richieeeeeeee on September 29, 2015 12:10_

Hi,
I try to pack an NugGet package that contains all my localized resource files as described here:
https://docs.nuget.org/create/creating-localized-packages

Unfortunately, the resource DLLs are not included in the packed file. Whats wrong? Here is my nuspec (I removed some attributes like license):

``` xml
<?xml version="1.0"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>$description$</description>
    <releaseNotes>See Redmine/SVN</releaseNotes>
  </metadata>
</package>
```

My output folder of VS 2013 bin\Debug:

```
en
   MyAssembly.resource.dll
es
   MyAssembly.resource.dll
MyAssembly.dll
```

However, the final package after calling "nuget pack MyAssembly.csproj" contains only the MyAssebly.dll, not the resource files.

What's wrong?

Thanks!

_Copied from original issue: NuGet/NuGetGallery#2708_

**Comment by emgarten** [comment]
What version of nuget.exe are you using? Running nuget.exe with no parameters will show you.

**Comment by richieeeeeeee** [comment]
Nuget Version 2.8.60717.93

**Comment by richieeeeeeee** [comment]
Any update? Its a fundamental feature, wondering if others have the same problem?

**Comment by yishaigalatzer** [comment]
@zhili1208  please take a look

**Comment by zhili1208** [comment]
@richieeeeeeee I think we don't support automatically pack resource dll, but you can do it by specifying the dll you want to pack. For example, you can add this to spec for .net 4.0 project under "package" section. http://docs.nuget.org/create/nuspec-reference

``` xml
<files>
    <file src="bin\Debug\en\MyAssembly.resource.dll" target="lib\net40\en\MyAssembly.resource.dll" />
    <file src="bin\Debug\es\MyAssembly.resource.dll" target="lib\net40\es\MyAssembly.resource.dll" />
</files>
```

it should work, if there is any problem, feel free to ask. thanks

**Comment by yishaigalatzer** [comment]
So in conclusion, this seems to be a feature we could support in the future, but this never did work. @zhili1208 please update the documentation to clarify that this is the case.

I'm moving this to be a feature ask, that we might address in one of the future releases. This could also be something we will happilly take a pull request for,.

**Comment by nkolev92** [comment]
Current recommendation is here: 
https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages

Currently we don't have plans to do more work in this space. 

If this is still an important scenario for you that cannot be satisfied by the above guidance, please create another issue.

**Comment by sebastianslutzky** [comment]
I know this ticket is closed, but the current recommendation doesn't address this problem. Is this problem (i.e. resource.dll files not added to the project on nuget install) an ongoing issue?

**Comment by JereckNET** [comment]
How can we include localized assemblies in the .nupkg file ? The workaround proposed by @richieeeeeeee is not maintainable as it requires many manual changes to the .nuspec file (fetching from debug or release, changing assembly name, targeting the correct version, etc. ...)

> @richieeeeeeee I think we don't support automatically pack resource dll, but you can do it by specifying the dll you want to pack. For example, you can add this to spec for .net 4.0 project under "package" section. http://docs.nuget.org/create/nuspec-reference
> 
> ```
> <files>
>     <file src="bin\Debug\en\MyAssembly.resource.dll" target="lib\net40\en\MyAssembly.resource.dll" />
>     <file src="bin\Debug\es\MyAssembly.resource.dll" target="lib\net40\es\MyAssembly.resource.dll" />
> </files>
> ```
>
