### ISSUE TITLE
Installing a package with a .Nupkg extension fails. Works for .nupkg extension

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1488]
Installing a package with a .Nupkg extension fails. Works for .nupkg extension

Repro steps:
1. Create a folder containing a package, say, A.1.0.
2. Make sure that package A's file name is A.1.0.Nupkg.
3. Create a Console Application in VS.
4. Open Powershell Console in VS.
5. Install-Package A

Expected:
Package A gets installed into the Console application.

Actual:
![image](https://cloud.githubusercontent.com/assets/2380340/10203081/eedbe4e4-6768-11e5-93b0-24c3270362c2.png)
- If you renamed the file from A.1.0.Nupkg to A.1.0.nupkg, it works fine
- Note that the repro from the UI will be different. Open the UI in VS after renaming the package file and  not before. And, then, you will notice that the differently named package (version) does not show up on the UI

**Comment by yishaigalatzer** [comment]
Fixed with: https://github.com/NuGet/NuGet2/commit/ad10dae82820f3e9e36316a1addf0a07feacff0e
