### ISSUE TITLE
nuget.exe update with no updates available does not show proper message

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1489]
nuget.exe update with no updates available does not show proper message.

Repro steps:
1. Create a Console Application
2. Create a package source <folderOfNupkgs> with a package, say, A.1.0.nupkg
3. Install-Package A -Source <folderOfNupkgs> from Powershell console
4. Go to cmd. Run 'nuget.exe update <projectFilePath>'

Expected:

Shows a message saying that 'There are no available updates.'

Actual:

It looks like the following and does not show any proper message. Message ends abruptly.

<b>c:\nuget></b>nuget.exe update < projectFilePath > -Source <folderOfNupkgs>
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Scanning for projects...
Found 1 project with a packages.config file. (ConsoleApplication4.csproj)
Attempting to gather dependencies information for multiple packages with respect to project '< projectFilePath >', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
<b>c:\nuget></b>

**Comment by RanjiniM** [comment]
Fixed

**Comment by RanjiniM** [comment]
This didn't go into 3.3.Commandline. Will check in the fix for 3.4

**Comment by RanjiniM** [comment]
Checked into dev branch (c65b1501f3a8aff024618cc9f46ad2c151bbd9b8)
