### ISSUE TITLE
UI update: improve "Installed" tab performance

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1492]

**Comment by yishaigalatzer** [comment]
This is now done. Installed tab goes to local sources first, shows up immediately and trickle updates the data. Potentially when https://github.com/NuGet/Home/issues/1493 is fixed we can use a similar API to get metadata for a set of packages in one go

**Comment by yishaigalatzer** [comment]
This is now done. Installed tab goes to local sources first, shows up immediately and trickle updates the data.
