### ISSUE TITLE
No information was given when calling nuget.exe update *.csproj while the project does not have a packages.config

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1496]
c:\school>nuget.exe update "C:\Users\danliu\Documents\Visual Studio 2015\Project
s\UAPApp\UAPApp.csproj" -repositorypath c:\school
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.

There is no packages.config in UAP app. The call above should have emitted a message saying "No packages.config was found".

**Comment by danliu** [comment]
In 2.8.6, it says "Cannot find the packages folder, please use -RepositoryPath switch to specify it". Then I added that switch, still got the same message back.

So the behavior was different in 2.8.6, though not a proper behavior either.

**Comment by feiling** [comment]
with nuget.exe 3.3.0.208, no messages are displayed. My opinion is that we don't need to display anything if there is no packages.config/project.json etc. Move it to 3.4

**Comment by yishaigalatzer** [comment]
@TimBarham assigned to you, but please hold off from checking in to dev until we open the branch again

**Comment by rrelyea** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249) by @zhili1208
