### ISSUE TITLE
NuGet.exe update should complete package resolution before updating

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1497]
Sometimes it will go ahead with the update, and then roll back after discovering that the target framework is not compatible.

c:\school>nuget.exe update "C:\Users\danliu\Documents\Visual Studio 2015\Project
s\WpfApplication1\WpfApplication1\packages.config" -pre
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.
Attempting to gather dependencies information for multiple packages with respect
 to project 'C:\Users\danliu\Documents\Visual Studio 2015\Projects\WpfApplicatio
n1\WpfApplication1\WpfApplication1.csproj', targeting '.NETFramework,Version=v4.
5.2'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'Unity 3.5.1405-prerelease' from 'packages.config'
Successfully uninstalled 'Unity 3.5.1405-prerelease' from WpfApplication1.csproj

Removed package 'LanguageExt 1.0.0' from 'packages.config'
Successfully uninstalled 'LanguageExt 1.0.0' from WpfApplication1.csproj
Removed package 'System.Collections.Immutable 1.1.36' from 'packages.config'
Successfully uninstalled 'System.Collections.Immutable 1.1.36' from WpfApplicati
on1.csproj
Removed package 'RestSharp 105.1.0' from 'packages.config'
Successfully uninstalled 'RestSharp 105.1.0' from WpfApplication1.csproj
Removed package 'Castle.Core 3.3.0' from 'packages.config'
Successfully uninstalled 'Castle.Core 3.3.0' from WpfApplication1.csproj
For adding package 'Castle.Core.3.3.3' to project 'WpfApplication1.csproj' that
targets 'net452'.
For adding package 'Castle.Core.3.3.3' to project 'WpfApplication1.csproj' that
targets 'net452'.
Package 'Castle.Core.3.3.3' already exists in folder 'C:\Users\danliu\Documents\
Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Castle.Core.3.3.3' to 'packages.config'
Successfully installed 'Castle.Core 3.3.3' to WpfApplication1.csproj
For adding package 'RestSharp.105.2.3' to project 'WpfApplication1.csproj' that
targets 'net452'.
For adding package 'RestSharp.105.2.3' to project 'WpfApplication1.csproj' that
targets 'net452'.
Package 'RestSharp.105.2.3' already exists in folder 'C:\Users\danliu\Documents\
Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'RestSharp.105.2.3' to 'packages.config'
Successfully installed 'RestSharp 105.2.3' to WpfApplication1.csproj
For adding package 'Rx-Interfaces.2.3.0-beta2' to project 'WpfApplication1.cspro
j' that targets 'net452'.
For adding package 'Rx-Interfaces.2.3.0-beta2' to project 'WpfApplication1.cspro
j' that targets 'net452'.
Package 'Rx-Interfaces.2.3.0-beta2' already exists in folder 'C:\Users\danliu\Do
cuments\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Rx-Interfaces.2.3.0-beta2' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.3.0-beta2' to WpfApplication1.csproj
For adding package 'Rx-Core.2.3.0-beta2' to project 'WpfApplication1.csproj' tha
t targets 'net452'.
For adding package 'Rx-Core.2.3.0-beta2' to project 'WpfApplication1.csproj' tha
t targets 'net452'.
Package 'Rx-Core.2.3.0-beta2' already exists in folder 'C:\Users\danliu\Document
s\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Rx-Core.2.3.0-beta2' to 'packages.config'
Successfully installed 'Rx-Core 2.3.0-beta2' to WpfApplication1.csproj
For adding package 'Rx-Linq.2.3.0-beta2' to project 'WpfApplication1.csproj' tha
t targets 'net452'.
For adding package 'Rx-Linq.2.3.0-beta2' to project 'WpfApplication1.csproj' tha
t targets 'net452'.
Package 'Rx-Linq.2.3.0-beta2' already exists in folder 'C:\Users\danliu\Document
s\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Rx-Linq.2.3.0-beta2' to 'packages.config'
Successfully installed 'Rx-Linq 2.3.0-beta2' to WpfApplication1.csproj
For adding package 'Rx-PlatformServices.2.3.0-beta2' to project 'WpfApplication1
.csproj' that targets 'net452'.
For adding package 'Rx-PlatformServices.2.3.0-beta2' to project 'WpfApplication1
.csproj' that targets 'net452'.
Package 'Rx-PlatformServices.2.3.0-beta2' already exists in folder 'C:\Users\dan
liu\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Rx-PlatformServices.2.3.0-beta2' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.3.0-beta2' to WpfApplication1.cspr
oj
Adding package 'Rx-Main.2.3.0-beta2', which only has dependencies, to project 'W
pfApplication1.csproj'.
Package 'Rx-Main.2.3.0-beta2' already exists in folder 'C:\Users\danliu\Document
s\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Rx-Main.2.3.0-beta2' to 'packages.config'
Successfully installed 'Rx-Main 2.3.0-beta2' to WpfApplication1.csproj
For adding package 'System.Linq.4.0.1-beta-23225' to project 'WpfApplication1.cs
proj' that targets 'net452'.
For adding package 'System.Linq.4.0.1-beta-23225' to project 'WpfApplication1.cs
proj' that targets 'net452'.
Package 'System.Linq.4.0.1-beta-23225' already exists in folder 'C:\Users\danliu
\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'System.Linq.4.0.1-beta-23225' to 'packages.config'
Successfully installed 'System.Linq 4.0.1-beta-23225' to WpfApplication1.csproj
For adding package 'System.Resources.ResourceManager.4.0.1-beta-23225' to projec
t 'WpfApplication1.csproj' that targets 'net452'.
For adding package 'System.Resources.ResourceManager.4.0.1-beta-23225' to projec
t 'WpfApplication1.csproj' that targets 'net452'.
Package 'System.Resources.ResourceManager.4.0.1-beta-23225' already exists in fo
lder 'C:\Users\danliu\Documents\Visual Studio 2015\Projects\WpfApplication1\pack
ages'
Added package 'System.Resources.ResourceManager.4.0.1-beta-23225' to 'packages.c
onfig'
Successfully installed 'System.Resources.ResourceManager 4.0.1-beta-23225' to Wp
fApplication1.csproj
For adding package 'System.Runtime.4.0.21-beta-23225' to project 'WpfApplication
1.csproj' that targets 'net452'.
WARNING: Install failed. Rolling back...
WARNING: Package 'System.Runtime 4.0.21-beta-23225' does not exist in project 'W
pfApplication1.csproj'
Removed package 'System.Resources.ResourceManager 4.0.1-beta-23225' from 'packag
es.config'
Removed package 'System.Linq 4.0.1-beta-23225' from 'packages.config'
Removed package 'Rx-Main 2.3.0-beta2' from 'packages.config'
Removed package 'Rx-PlatformServices 2.3.0-beta2' from 'packages.config'
Removed package 'Rx-Linq 2.3.0-beta2' from 'packages.config'
Removed package 'Rx-Core 2.3.0-beta2' from 'packages.config'
Removed package 'Rx-Interfaces 2.3.0-beta2' from 'packages.config'
Removed package 'RestSharp 105.2.3' from 'packages.config'
Removed package 'Castle.Core 3.3.3' from 'packages.config'
For adding package 'Castle.Core 3.3.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
For adding package 'Castle.Core 3.3.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
Package 'Castle.Core 3.3.0' already exists in folder 'C:\Users\danliu\Documents\
Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Castle.Core 3.3.0' to 'packages.config'
For adding package 'RestSharp 105.1.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
For adding package 'RestSharp 105.1.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
Package 'RestSharp 105.1.0' already exists in folder 'C:\Users\danliu\Documents\
Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'RestSharp 105.1.0' to 'packages.config'
For adding package 'System.Collections.Immutable 1.1.36' to project 'WpfApplicat
ion1.csproj' that targets 'net452'.
For adding package 'System.Collections.Immutable 1.1.36' to project 'WpfApplicat
ion1.csproj' that targets 'net452'.
Package 'System.Collections.Immutable 1.1.36' already exists in folder 'C:\Users
\danliu\Documents\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'System.Collections.Immutable 1.1.36' to 'packages.config'
For adding package 'LanguageExt 1.0.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
For adding package 'LanguageExt 1.0.0' to project 'WpfApplication1.csproj' that
targets 'net452'.
Package 'LanguageExt 1.0.0' already exists in folder 'C:\Users\danliu\Documents\
Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'LanguageExt 1.0.0' to 'packages.config'
For adding package 'Unity 3.5.1405-prerelease' to project 'WpfApplication1.cspro
j' that targets 'net452'.
For adding package 'Unity 3.5.1405-prerelease' to project 'WpfApplication1.cspro
j' that targets 'net452'.
Package 'Unity 3.5.1405-prerelease' already exists in folder 'C:\Users\danliu\Do
cuments\Visual Studio 2015\Projects\WpfApplication1\packages'
Added package 'Unity 3.5.1405-prerelease' to 'packages.config'
Could not install package 'System.Runtime 4.0.21-beta-23225'. You are trying to
install this package into a project that targets '.NETFramework,Version=v4.5.2',
 but the package does not contain any assembly references or content files that
are compatible with that framework. For more information, contact the package au
thor.

**Comment by danliu** [comment]
This is a regression.

With 2.8.6, nuget.exe was able to complete. 

```
   <packages>
     <package id="Castle.Core" version="3.3.3" targetFramework="net45" />
     <package id="LanguageExt" version="1.5.0" targetFramework="net45" />
     <package id="RestSharp" version="105.2.3" targetFramework="net45" />
     <package id="Rx-Core" version="2.2.5" targetFramework="net45" />
     <package id="Rx-Interfaces" version="2.2.5" targetFramework="net45" />
     <package id="Rx-Linq" version="2.2.5" targetFramework="net45" />
     <package id="Rx-Main" version="2.2.5" targetFramework="net45" />
     <package id="Rx-PlatformServices" version="2.2.5" targetFramework="net45" />
     <package id="System.Collections.Immutable" version="1.1.38-beta-23225" targetFramework="net45" />
     <package id="Unity" version="3.5.1406" targetFramework="net45" />
</packages>
```

**Comment by danliu** [comment]
To repro, create a new WPF application and install the following:

Restsharp -version 105.1.10
LanguageExt -version 1.0.0
Castle.core -version 3.3.0
Unity -version 3.5.1405-prerelease -pre

then call nuget.exe update -pre

**Comment by MeniZalzman** [comment]
using the latest the command line 3.3 with the repro steps and everything is working. (No repro)

**Comment by feiling** [comment]
verified with nuget.exe 3.3.0.208
