### ISSUE TITLE
NuGet Package Manager in VS 2015 not adding reference to assemblies whose name ends in .Resources

### ISSUE THREAD

**Issue by wabirch** [NuGet/Home#1499]
When using the NuGet package manager to install a package containing an assembly whose name ends in .Resources, the package installs correctly but a reference to that assembly is not added to the project.

Tools: -
- Visual Studio Enterprise 2015 v4.6.00081
- NuGet Package Manager for Visual Studio 2015 v3.2.60914.10516

.nuspec file:

```
<?xml version="1.0"?>
<package >
  <metadata>
    <id>ClassLibrary.TestPackage</id>
    <version>1.0.0.0</version>
    <title>ClassLibrary.TestPackage</title>
    <authors>Me</authors>
    <owners>Me</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
    <tags></tags>
  </metadata>
</package>
```

.nupkg contents: -

> - lib
>   - net46 (.NETFramework,Version=4.6)
>   - ClassLibrary.Resource.dll
>   - ClassLibrary.Resources.dll
>   - ClassLibrary.Resourcex.dll
>   - ClassLibrary.ResourcesWhatever.dll
>   - ClassLibrary.Whatever.dll
>   - ClassLibrary.WhateverResources.dll

All 6 of the assemblies are empty class libraries targetting .Net 4.6.

When installing the nuget package, references are added for all assemblies except: -

> - ClassLibrary.Resources.dll

It would seem specifically that assemblies whose name ends in .Resources is causing the problem.

The problem continues further when upgrading such an assembly - the reference remains pointing to the previous version and indeed the package itself remains in the packages folder.

A workaround, of course, is to simply add a reference manually but this is proving to be repetitive and tiresome for a regularly changing library used in mutliple projects.

**Comment by yishaigalatzer** [comment]
This appears to be by design: assemblies ending with .resources are considered localization assemblies, and hence are not added as references.

http://docs.nuget.org/create/creating-localized-packages

``` C#
private static bool IsReferenceAssembly(string path)
        {
            var result = false;

            var extension = Path.GetExtension(path);

            if (StringComparer.OrdinalIgnoreCase.Equals(extension, ".dll"))
            {
                if (!path.EndsWith(".resources.dll", StringComparison.OrdinalIgnoreCase))
                {
                    result = true;
                }
            }
            else if (StringComparer.OrdinalIgnoreCase.Equals(extension, ".winmd"))
            {
                result = true;
            }
            else if (StringComparer.OrdinalIgnoreCase.Equals(extension, ".exe"))
            {
                result = true;
            }

            return result;
        }
```

**Comment by yishaigalatzer** [comment]
Still looking at NuGet 2.X to see if the behavior is the same or this is a change in behavior

**Comment by yishaigalatzer** [comment]
Looks like it - Here is the code from the V2 code base

https://github.com/NuGet/NuGet.Client/blob/3a9e61a52f0e9bc47380031bcddc0a73ff3883ea/src/NuGet.Core/NuGet.ProjectManagement/Projects/MSBuildNuGetProject.cs#L533

```
        internal protected static bool IsAssemblyReference(string filePath)
        {           
            // assembly reference must be under lib/
            if (!filePath.StartsWith(Constants.LibDirectory + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            var fileName = Path.GetFileName(filePath);

            // if it's an empty folder, yes
            if (fileName == Constants.PackageEmptyFileName)
            {
                return true;
            }

            // Assembly reference must have a .dll|.exe|.winmd extension and is not a resource assembly;
            return !filePath.EndsWith(ResourceAssemblyExtension, StringComparison.OrdinalIgnoreCase) &&
                Constants.AssemblyReferencesExtensions.Contains(Path.GetExtension(filePath), StringComparer.OrdinalIgnoreCase);
        }
```

**Comment by jcoder76** [comment]
I know this is a closed issue, but is there a workaround for this so I don't have to change the name and still get NuGet to add a reference to specific DLL files ending in .Resources.dll?

**Comment by yishaigalatzer** [comment]
Let me ask around. But I think the easiest way to achieve it is to use a target file.

**Comment by laurencee** [comment]
I just ran into this same issue and my solution is the same as mentioned, I am also just copying the dll to where i need it instead of having it referenced. 

Wasted a bunch of time figuring out what was going on with this...

**Comment by gaganpa2020** [comment]
What is the workaround for same issue?

**Comment by yishaigalatzer** [comment]
Rename the assembly or put it in a target file as a reference

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by bojingo** [comment]
What is meant by "put it in a target file as a reference"? Would really appreciate some guidance (links to references, etc.) on that so I don't have to rename the assembly.

**Comment by rrelyea** [comment]
Defining and important an MSBuild targets are documented here: https://msdn.microsoft.com/en-us/library/ms171464.aspx

@yishaigalatzer  was recommending to create a targets file with the following content:

MyReference.targets:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
       <Reference Include="..\..\somepath\Foo.Resources.dll" />
    </ItemGroup>
</Project>

```
And then import that target from your project file with: 
`<Import Project="MyReference.targets" />`
