### ISSUE TITLE
Push doesn't use apiKey for service index when talking to PackagePublish/2.0.0 service

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1502]
The apiKey must currently be set using the URL for the PackagePublish/2.0.0 service, rather than the service index.  The service index url should (also) work, but does not.

This means that a user has to first try to push, see the message:

"WARNING: No API Key was provided and no API Key could be found for 'https://<v2_push_service>'. To save an API Key for a source use the 'setApiKey' command."
and then run "nuget setApiKey -Source <v2_push_service> <api_key>".

The location of the PackagePublish/2.0.0 service is an implementation detail from the users perspective, and users should not have to know it.

Note: Using "nuget push -ApiKey" appears to work fine.

**Comment by yishaigalatzer** [comment]
@zarenner good catch. Pushing this out post 3.3 unless you want to PR, in that case we will bring it back.

**Comment by g0t4** [comment]
A new package is ready for ASP.NET Core, enjoy! https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.MongoDB/

**Comment by emgarten** [comment]
Closing. Would accept a PR for this.
