### ISSUE TITLE
Nuget is dropping packages from the TFM/RID on first restore

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1503]
I'm seeing that on first restore some packages are present in the TFM target but absent from the TFM/RID target.  This only seems to happen if the packages haven't already been downloaded, so make sure to do this on a fresh packages folder with no project.lock.json.

Repro project.json

```
{
  "dependencies": {
    "Microsoft.NETCore": "5.0.1-beta-*",
    "System.Security.Cryptography.X509Certificates": "4.0.0-beta-*",
    "Microsoft.Win32.Primitives": "4.0.1-beta-*"
  },
  "frameworks": {
    "dnxcore50": {}
  },
  "runtimes": {
    "win7-x64": {},
    "win7-x86": {}
  }
}
```

Restore using the command:

```
NuGet.exe restore project.json -Source "https://www.myget.org/F/dotnet-core/api/v3/index.json" -Source "https://api.nuget.org/v3/index.json" -Verbosity detailed -PackagesDirectory .\packages
```

This runs successfully and produces a lock file.  Examine the TFM target in the lock file and you'll see that it has System.Reflection.Emit, System.Reflection.Emit.ILGeneration, and System.Net.NetworkInformation.  Examine the TFM/RID targets and you'll see the packages are missing.

Now if I rerun the exact same command with no changes, the restore will run again and correctly add these packages to the TFM/RID graphs.

I couldn't reproduce this using DNU, but it could be that I couldn't get the exact same scenario set up.

/cc @yishaigalatzer @anurse @loudej

**Comment by yishaigalatzer** [comment]
We believe this is fixed now, Justin will verify and close

**Comment by emgarten** [comment]
This is fixed in 3.3.0, I double checked that the example in this bug no longer repros the issue.

NuGet/NuGet.Client@42cbee2a8aca0f448d09734a753245a60dedaa2f

**Comment by ericstj** [comment]
Cool, thanks!

**Comment by feiling** [comment]
verified with nuget.exe 3.3.0.208
