### ISSUE TITLE
Too aggressive caching of TFM might have side effects

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1509]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectManagement/Projects/BuildIntegratedNuGetProject.cs#L56

As I was fixing a bug in this code, I noticed that the TFM from project.json is grabbed once, and never updated when project.json changes (couldn't find any trigger that will change this).

I'm not sure where the data is being used, and what side effects it might had.

We should either
1. Understand the potential issue and fix it.
2. Document that the data doesn't play an important role (comment), but in that case should we just get rid of it?

@emgarten please take a quick look and provide more info (and adjust the priority if needed)

**Comment by emgarten** [comment]
This shouldn't be an issue beyond logging and potentially search. The project.json file is re-read for each restore and the TFM is taken directly from there. Removing this property could cause issues since other parts of the code require the project to have a TFM.
