### ISSUE TITLE
Dependency range lower bound incorrect in VS

### ISSUE THREAD

**Issue by vtbassmatt** [NuGet/Home#1511]
[Per the docs](http://docs.nuget.org/Create/versioning#Specifying-Version-Ranges-in-.nuspec-Files), a dependency range `<dependency id="StrictlyGreaterThan" version="(1.0,)" />` means 1.0 < x, which is mathematically equivalent to x > 1.0. But the IDE shows: `StrictlyGreaterThan (≥ 1.0.0)`. See screenshot. This is VS 2015 with VSIX 3.2.60914.10516.

![image](https://cloud.githubusercontent.com/assets/714283/10254168/d3d63214-68f6-11e5-8e5e-2975cb6cfcd1.png)

**Comment by yishaigalatzer** [comment]
@vtbassmatt thanks for reporting this issue. I agree we should fix it, I'm just putting the priority lower than the immediate next release.

Feel free to provide more feedback if you disagree.

**Comment by vtbassmatt** [comment]
Fine by me :)

Sent from Outlook for iPhone

On Mon, Oct 5, 2015 at 9:07 AM -0700, "Yishai Galatzer" notifications@github.com wrote:

@vtbassmatt thanks for reporting this issue. I agree we should fix it, I'm just putting the priority lower than the immediate next release.

Feel free to provide more feedback if you disagree.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
