### ISSUE TITLE
Need a nuget.exe command to clear and list local caches and global packages folder

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1516]
With the plethora of caches NuGet support, it is pretty hard to clear them out.

Perhaps the option name needs to become a bit better, since I would expect it to also wipe the global pacakges folder.

CC @davidfowl

**Comment by xavierdecoster** [comment]
Should this `nuget.exe clearcache` command wipe the global packages folder by default or only the machine default cache located at `%localappdata\nuget\cache`?

Maybe there could be an optional switch to also wipe the global cache (if that makes any sense)? 
E.g. `nuget.exe clearcache -g`

**Comment by yishaigalatzer** [comment]
The command should be

`nuget.exe -clearcache -clearGlobalPackages`

Clear cache should clear all caches (http caches, global cache etc.)

CC @davidfowl @emgarten

**Comment by xavierdecoster** [comment]
So `nuget.exe clearcache` is the command. This clears all caches (http, global, etc).

What's the purpose of the `-clearGlobalPackages` command option? To only clear the global packages cache?

**Comment by yishaigalatzer** [comment]
-clearGlobalPackages is to clear more than just the caches

**Comment by xavierdecoster** [comment]
I see. So, `nuget.exe clearcache` clears all caches. `-clearGlobalPackages` cleans "more than just the caches"? Can you please define "more"? Confused :)

**Comment by xavierdecoster** [comment]
Here's my understanding of the requirements:
- `nuget.exe clearcache` will clear `%localappdata%\NuGet\cache` and `%localappdata%\NuGet\v3-cache`
- `nuget.exe clearcache -clearGlobalPackages` will clear the above, and also clear the global packages folder as defined using the `NUGET_PACKAGES` environment variable, or if not defined, the default location `%userprofile%\.nuget\packages`

**Comment by yishaigalatzer** [comment]
Exactly.

**Comment by xavierdecoster** [comment]
As a result of exchanging ideas, here's the suggested syntax and usage:

| Command | Description |
| --- | --- |
| `nuget.exe locals` | Show help for the `nuget.exe locals` command |
| `nuget.exe locals -clear` | Shows usage help for the `nuget.exe locals -clear` command |
| `nuget.exe locals -clear all` | Clears all local resources, including package cache, http cache and local machine-wide packages folder |
| `nuget.exe locals -clear http-cache` | Clears the local http cache |
| `nuget.exe locals -clear packages-cache` | Clears the local packages cache |
| `nuget.exe locals -clear global-packages` | Clears the local machine-wide packages folder |
| `nuget.exe locals -list` | Shows usage help for the `nuget.exe locals -list` command |
| `nuget.exe locals -list all` | Prints the location on disk for all local resource folders, including package cache, http cache and local machine-wide packages folder |
| `nuget.exe locals -list http-cache` | Prints the location on disk for the local http cache folder |
| `nuget.exe locals -list packages-cache` | Prints the location on disk for the local packages cache folder |
| `nuget.exe locals -list global-packages` | Prints the location on disk for the local machine-wide packages folder |

**Comment by xavierdecoster** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/3b5a7fc2dc221161a7a7caf8415ec25a3a4189fc

**Comment by feiling** [comment]
verified with nuget.exe 3.3.0.208
