### ISSUE TITLE
Alt+S in VS Tools->Options->NuGet Package Manager->"Package Sources" jumps to wrong text box

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1518]
VS
Tools->Options->NuGet Package Manager -> Package Sources
Press Alt+S
Focus should be set to the Source text box. Instead, it focuses on the Name textbox.

![image](https://cloud.githubusercontent.com/assets/3548/10287939/dbbae258-6b4a-11e5-96f0-be3b41967eac.png)

**Comment by rrelyea** [comment]
This appears fixed. Tried it in 16.5 latest daily build.
Also looked at docs for labels in winforms...and the tabindexs are set as they say to, in order to have this work. https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/how-to-create-access-keys-with-windows-forms-label-controls
