### ISSUE TITLE
Gallery: some packages are missing on api.nuget.org

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#152]
one package missing is http://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers/1.0.0-rc1, which is not available on api.nuget.org.

**Comment by deepakaravindr** [comment]
xunit.core.2.0.0 is missing too. This is the latest stable version of a very popular unit test package. This was uploaded on March 16 2015, and has been downloaded 7000 times in the first 2 weeks

**Comment by deepakaravindr** [comment]
@RanjiniM 
One more, package Microsoft.LightSwitch.Client.JavaScript.Runtime, used by the LightSwitch project template is not present on V3, but present on V2

**Comment by RanjiniM** [comment]
@deepakaravindr , Which version is missing? What is the client version you are using?

**Comment by deepakaravindr** [comment]
It is present. My bad

**Comment by RanjiniM** [comment]
Catalog has been repaired to have all the packages now.

**Comment by yishaigalatzer** [comment]
@RanjiniM should this issue remain open for some reason?

**Comment by RanjiniM** [comment]
Closing the issue as we have all packages in the catalog and blobs now.
