### ISSUE TITLE
Remerge settings origin for package sources

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1522]
https://github.com/NuGet/NuGet3/commit/2ae84e2d251be26217bcc552501de6bad2e9eb7d

CC @anurse @emgarten

**Comment by emgarten** [comment]
This is ready in emgarten/321merge  https://github.com/NuGet/NuGet.Client/commit/b1b3f2a2a1b6bb7e1e553721e1a96159883e0679

**Comment by emgarten** [comment]
Merged
