### ISSUE TITLE
Disable symbol package upload

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#1524]
It would be nice to disable symbol package upload (even though a symbol package is created) with a command line option for a `nuget push`, because `symbolsource.org` is often so extremely slow and unreliable, that a simple switch to disable the symbol package upload would make my life much easier.

This would allow a two-step package upload from a build server, where I first upload the normal packages, and then I upload the symbols separately. The second upload step could be configured, that an error uploading the symbols wouldn't mark the build as failed.

Another possible solution would be ignoring a failed symbol package upload (`nuget.exe` returning exit code 0).

**Comment by yishaigalatzer** [comment]
Sounds like a good idea, priority wise moving to vNext and would love a pull request if you want it faster.

NuGet.Client is the repo where things are happening now for command line

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Announcements/issues/13
