### ISSUE TITLE
nuget 3.2 freeze Visual Studio 2015 on install/update/remove package

### ISSUE THREAD

**Issue by Viacheslav01** [NuGet/Home#1526]
Since the update to Windows 10 and Visual Studio 2015 each manipulation with packages by the Nuget console either the Package manager dialog, the Visual Studio is frozen and crushed in 10 seconds.

**Comment by yishaigalatzer** [comment]
@Viacheslav01 we would love to help you, but we will need some more information.
1. Did you update the NuGet extension to 3.2? Tools->Extensions and Updates->Updates->Visual Studio Gallery?
2. If you did and you still see issues, please provide us with some details on your setup, project and what packages are you trying to install.

**Comment by Viacheslav01** [comment]
My English is not good, but I'll try to describe.

I have tried the next actions:

1) Update nuget to the latest version -> it doesn't resolve the issue
2) Remove nuget + reboot + install nuget -> the issue stay here

**Comment by Viacheslav01** [comment]
My solution contains 20 projects including:
1) Win 8.1 + WP 8.1 PCL
2) WP 8.0
3) Universal App 8.1
4) WinRT Components C++

**Comment by Viacheslav01** [comment]
The first time when I see the issue it was update Newtonsoft.Json from 6.0.8 to 7.0.1.
Visual Studio froze and reboot on each updated project.

The result was:
1) pacages.config is updated to a new version of package
2) *.csprj is not updated and links to an old version of the package

Now I try to add package Newtonsoft.Json to a C# PCL project.
I have tried to add the other project especially Autofac, result is the same.

**Comment by Viacheslav01** [comment]
[Auto] Package restore is working correct.

**Comment by yishaigalatzer** [comment]
Is it possible to get access to your project? This is a very common scenario that we think should work fine, it will really help if we can get a sample and run through it to figure out what is going wrong with your project.

**Comment by Viacheslav01** [comment]
Unfortunately, this is a company project I can't share the sources. I'll try to create a sample solution with the same configuration.

**Comment by kjeremy** [comment]
I just saw this on a Xamarin project trying to install Xamarin.Android.Support.Design.  It took over 20 minutes to install the nuget packages into my bare-bones project.

**Comment by yishaigalatzer** [comment]
@kjeremy can you share more details? What version of NuGet are you using? What version of Xamarin.Android.Support.Design did you try to install? What exact bare bone project are you using?

In general we find that NuGet 3.2 is installing packages quicker than NuGet 2.8.X, so we ask you for exact details to help us pinpoint the issue you are referring to

**Comment by yishaigalatzer** [comment]
@kjeremy one other thought is that this could come from your package sources. Do you have a very slow server or a large file share as a source?

**Comment by kjeremy** [comment]
The latest stable of all of the above.  Package source is the default that
comes with VS2015.  It occurs to me that I have resharper 9 installed and
I'm thinking that may be part of the problem.

**Comment by yishaigalatzer** [comment]
Sounds like a good path. The packages are very simple nothing that should take that long.

Can you let us know what is up once you removed resharper?

Sent from my Windows Phone

**Comment by Viacheslav01** [comment]
I have removed Resharper unfortunately it doesn't solve the issue.

**Comment by yishaigalatzer** [comment]
Do you have any other tool running tests in the background or locking files? Can you share a sample project (so we do exactly the same thing, and I'll try on my side with a vanilla visual studio)

**Comment by yishaigalatzer** [comment]
ping. We also released nuget 3.3 in between with a lot of bug fixes, I'm wondering if your scenario has improved and if not can we get a repro project?

**Comment by kjeremy** [comment]
It looks like it works now.

**Comment by yishaigalatzer** [comment]
Thanks!

**Comment by Viacheslav01** [comment]
I have tested nuget 3.3 it works correct now. Thanks!
