### ISSUE TITLE
Respect existing web.config formatting and whitespace.

### ISSUE THREAD

**Issue by kogir** [NuGet/Home#1527]
I format my XML with attributes on their own lines, and use two spaces instead of 4. Whenever I perform a NuGet operation that edits web.config, it reformats the whole file with different settings.

If the Visual Studio NuGet extension respected my Visual Studio editor configuration settings, it would get the formatting completely right. If this is too much work, please minimize changes to only lines modified/added/removed, not the entire file.

I know this is a small issue, and semantically the XML is the same, but it makes me sad each time I go to commit and see all of web.config has changed.

**Comment by yishaigalatzer** [comment]
XDT transforms are performed by the `Microsoft.Web.Xdt` package, we can reach out to the owner of the package. Or perform the editor edit like you suggest (or perhaps even simpler, perform an auto format operation when we are done - though this might open a bunch of unexpected side effects).

This issue doesn't seem to meet the bar for an immediate release, I'm moving it to vNext and we will prioritize it when we get free-d up from the pressing issue of fixing up 3.2 performance and behavior.

We would gladly take a pull request for this issue.

**Comment by mishra14** [comment]
Closing due to lack of traction.
