### ISSUE TITLE
Cache package metadata locally for duration of session.

### ISSUE THREAD

**Issue by kogir** [NuGet/Home#1528]
I primarily use NuGet through the Visual Studio plugin. It's infuriatingly slow.

When I "Manage NuGet Packages for [Solution|Project]", any retrieved package metadata should be cached. Already cached metadata should be used when possible.

When online, viewing installed packaged for my solution takes 15 seconds on my 100/20Mbps connection. The same operation while offline takes < 1 second. Installed packages are installed and cached. Just use the metadata on disk.

When updating packages in my solution, it takes 15-20 seconds to check for updates. Bummer, but ok. Say there are 5 updates. I update one package, and then have to wait 15-20 seconds again before I can update the next. Instead of going back to the server again, it should use the same data as last time for subsequent package updates.

**Comment by yishaigalatzer** [comment]
Fair feedback. This is already on our plan for 3.3

There are a few strategies that may help you speed up your scenario
1. If you use many sources, consider removing unnecessary sources. NuGet goes in parallel to all of them to find the latest versions.
2. If you use www.nuget.org/api/v2, as a package source, consider using api.nuget.org/v3/index.json instead.

We plan to both do more caching of update results, and also enable to update multiple packages in parallel.

CC @feiling

**Comment by yishaigalatzer** [comment]
Closing, because there is no extra action on this issue, but feel free to continue the discussion on this thread.

Related issues #1493 #1492 #1494 #1504

**Comment by kogir** [comment]
Great news, thanks!

api.nuget.org/v3/index.json was and is currently my only source.
