### ISSUE TITLE
Can I have NuGet install packages to custom directory?

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#1532]
NuGet always seems to install JavaScript libraries, like AngularJS or jQuery, into the `/Scripts/` root directory.

I want to manually choose a different target directory when installing these packages so they won't conflict with other NuGet packages.

How can I do this?

**Comment by yishaigalatzer** [comment]
That is not supported, which is why the ASP.NET team is recommending to use Bower.

We are working on a new feature for content, that might eventually support determining the root location see - https://github.com/NuGet/Home/wiki/Bringing-back-content-support,-September-24th,-2015
