### ISSUE TITLE
COM Errors while installing EntityFramework in Vs2013

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1533]
From @Fransbouma on Twitter:

Installing EntityFramework package throws COM error:
PM> install-package entityframework
Installing 'EntityFramework 6.1.3'.
You are downloading EntityFramework from Microsoft, the license agreement to which is available at http://go.microsoft.com/fwlink/?LinkID=320539. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'EntityFramework 6.1.3'.
Adding 'EntityFramework 6.1.3' to Northwind.Adapter.Persistence.
Successfully added 'EntityFramework 6.1.3' to Northwind.Adapter.Persistence.
Uninstalling 'EntityFramework 6.1.3'.
Successfully uninstalled 'EntityFramework 6.1.3'.
Install failed. Rolling back...
install-package : Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.
At line:1 char:1
- install-package entityframework
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidCastException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Retrying successfully installs the package.

Original content on gist at:  https://gist.github.com/FransBouma/edf4935e27501f63c84d

**Comment by FransBouma** [comment]
What I have discovered:
- When having saved the solution and making _no change_ whatsoever, it is often avoided
- When having saved the solution and then making some change, it is likely going to fail with the errors mentioned above. 
- It happens with most packages, including my own which contain no script at all. 

If I have to look at logs somewhere, let me know.

**Comment by FransBouma** [comment]
Additionally, it's also very slow (as in: it hangs for half a minute to a minute, vs.net is unresponsive) right before it crashes with the error reported in some cases. Mind you that the errors are also sometimes different, as shown in the gist: 

```
PM> install-package entityframework
'EntityFramework 6.1.3' already installed.
Adding 'EntityFramework 6.1.3' to Tests.
install-package : Failed to add reference to 'System.ComponentModel.DataAnnotations'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ install-package entityframework
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

PM> 
```

Repeatedly retrying to install the package gives different errors after an error like the one above, mostly ending with the comobject error. 

It happens both from the console and also in the UI so there's no difference in that.

**Comment by FransBouma** [comment]
Another log, this time with different packages, and a different issue. I quote the complete log so you can see that when retrying things go OK. 

My suspicion is that the following happens:
- a certain error occurs/exception occurs
- the error ends up in a piece of code which has the cast exception or runs into another issue and _that_ issue what's reported back to the user. 

> Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.
> 
> Package Manager Console Host Version 2.8.60723.765
> 
> Type 'get-help NuGet' to see all available NuGet commands.
> 
> PM> install-package entityframework
> 'EntityFramework 6.1.3' already installed.
> Adding 'EntityFramework 6.1.3' to NWDocDB.Persistence.
> Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.
> install-package : Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.
> At line:1 char:1
> - install-package entityframework
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidCastException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package entityframework
> 'EntityFramework 6.1.3' already installed.
> Adding 'EntityFramework 6.1.3' to NWDocDB.Persistence.
> Successfully added 'EntityFramework 6.1.3' to NWDocDB.Persistence.
> 
> Type 'get-help EntityFramework' to see all available Entity Framework commands.
> 
> PM> install-package nunit
> 'NUnit 2.6.4' already installed.
> Adding 'NUnit 2.6.4' to TesterDocumentDatabase.
> Successfully added 'NUnit 2.6.4' to TesterDocumentDatabase.
> install-package : Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.
> At line:1 char:1
> - install-package nunit
> - ~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidCastException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package nunit
> 'NUnit 2.6.4' already installed.
> TesterDocumentDatabase already has a reference to 'NUnit 2.6.4'.
> 
> PM> install-package entityframework
> 'EntityFramework 6.1.3' already installed.
> Adding 'EntityFramework 6.1.3' to TesterDocumentDatabase.
> Successfully added 'EntityFramework 6.1.3' to TesterDocumentDatabase.
> 
> Type 'get-help EntityFramework' to see all available Entity Framework commands.
> 
> PM> install-package ravendb.client
> Installing 'RavenDB.Client 3.0.3800'.
> You are downloading RavenDB.Client from Hibernating Rhinos, the license agreement to which is available at http://www.ravendb.net/licensing. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
> Successfully installed 'RavenDB.Client 3.0.3800'.
> Adding 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Uninstalling 'RavenDB.Client 3.0.3800'.
> Successfully uninstalled 'RavenDB.Client 3.0.3800'.
> Install failed. Rolling back...
> install-package : Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.
> At line:1 char:1
> - install-package ravendb.client
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidCastException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package ravendb.client
> Installing 'RavenDB.Client 3.0.3800'.
> You are downloading RavenDB.Client from Hibernating Rhinos, the license agreement to which is available at http://www.ravendb.net/licensing. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
> Successfully installed 'RavenDB.Client 3.0.3800'.
> Adding 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Uninstalling 'RavenDB.Client 3.0.3800'.
> Successfully uninstalled 'RavenDB.Client 3.0.3800'.
> Install failed. Rolling back...
> install-package : Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
> At line:1 char:1
> - install-package ravendb.client
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], COMException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package ravendb.client
> Installing 'RavenDB.Client 3.0.3800'.
> You are downloading RavenDB.Client from Hibernating Rhinos, the license agreement to which is available at http://www.ravendb.net/licensing. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
> Successfully installed 'RavenDB.Client 3.0.3800'.
> Adding 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Uninstalling 'RavenDB.Client 3.0.3800'.
> Successfully uninstalled 'RavenDB.Client 3.0.3800'.
> Install failed. Rolling back...
> install-package : Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
> At line:1 char:1
> - install-package ravendb.client
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], COMException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package ravendb.client
> Installing 'RavenDB.Client 3.0.3800'.
> You are downloading RavenDB.Client from Hibernating Rhinos, the license agreement to which is available at http://www.ravendb.net/licensing. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
> Successfully installed 'RavenDB.Client 3.0.3800'.
> Adding 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Uninstalling 'RavenDB.Client 3.0.3800'.
> Successfully uninstalled 'RavenDB.Client 3.0.3800'.
> Install failed. Rolling back...
> install-package : Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))
> At line:1 char:1
> - install-package ravendb.client
> - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : NotSpecified: (:) [Install-Package], COMException
>   - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
> 
> PM> install-package ravendb.client
> Installing 'RavenDB.Client 3.0.3800'.
> You are downloading RavenDB.Client from Hibernating Rhinos, the license agreement to which is available at http://www.ravendb.net/licensing. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
> Successfully installed 'RavenDB.Client 3.0.3800'.
> Adding 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Successfully added 'RavenDB.Client 3.0.3800' to TesterDocumentDatabase.
> Failed to generate binding redirects for 'TesterDocumentDatabase'. Unable to cast object of type 'System.__ComObject' to type 'EnvDTE.Project'.

I tried to save the solution before re-trying, but this one keeps quiting. the errors tend to mutate as well ;)

**Comment by FransBouma** [comment]
A different one this morning:

> Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.
> 
> Package Manager Console Host Version 2.8.60723.765
> 
> Type 'get-help NuGet' to see all available NuGet commands.
> 
> PM> install-package nunit
> 'NUnit 2.6.4' already installed.
> Adding 'NUnit 2.6.4' to DocDBTests.
> Successfully added 'NUnit 2.6.4' to DocDBTests.
> Failed to generate binding redirects for 'DocDBTests'. Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED))

the lib _is_ registered as a normal project reference. I also don't understand why it wants to generate binding redirects as the vs.net project is .net 4.5, and nunit.framework supports that.

**Comment by FransBouma** [comment]
Is there _anyone_ even interested in solving this? I have to wade through this mess every damn day. I can now not install a package at all, retrying doesn't work. When I open the solution 2015, it works. Before you say 'so that solves it then', it doesn't, I prefer 2013 over 2015 as 2015 has some issues e.g. with debugger visualizers so I can't use 2015.

**Comment by rohit21agrawal** [comment]
@FransBouma Can't repro this with NuGet 2.8.60723.765 + VS 2013 Update 5 on Windows 10. Can you share the specifics of the project in which this repros? Or attach a small project with which this happens and list the exact steps so we can easily identify the issue?

**Comment by FransBouma** [comment]
Sorry, I don't use 2013 anymore, with 2015 I haven't seen it (and nuget 3.3+). I must say, if you had replied sooner I might have been able to get you a repro

**Comment by rohit21agrawal** [comment]
Closing this issue since cannot get a repro anymore.

Please feel free to reactivate if you hit this issue again.
