### ISSUE TITLE
"VS 11 Common Tools not found" error after installing Gulp/Grunt/NPM

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#1534]
In Visual Studio 2015, after installing Gulp/Grunt/NPM, whenever building a web application, the above error `VS 11 Common Tools not found` is logged to the output window.

Perhaps an update of the corresponding packages is required to correctly support Visual Studio 2015?

**Comment by yishaigalatzer** [comment]
Moved to https://github.com/aspnet/Tooling/issues/212
