### ISSUE TITLE
Can't install portable-net451-* package into .NET 4.5.1 class library

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1535]
VS: 14.0.23107.0 D14Rel
NuGet Package Manager for VS 3.2.60914.10516

Repro steps:
1. Create a new C# class library that targets .NET 4.5.1 (_not_ a portable library)
1. In the Package Manager Console: `install-package nerdbank.fullduplexstream -pre -version 0.1.15-beta`

Expected:
package installs successfully because it has a `lib\portable-net451%2Bwin81%2Bwpa81` folder, which obviously suggests compatibility with .NET 4.5.1 class libraries.

Actual: 
Package installation fails with this log in VS:

```
PM> install-package nerdbank.fullduplexstream -pre
Attempting to gather dependencies information for package 'nerdbank.fullduplexstream.0.1.15-beta' with respect to project 'ClassLibrary17', targeting '.NETFramework,Version=v4.5.1'
Attempting to resolve dependencies for package 'nerdbank.fullduplexstream.0.1.15-beta' with DependencyBehavior 'Lowest'
Resolving actions to install package 'nerdbank.fullduplexstream.0.1.15-beta'
Resolved actions to install package 'nerdbank.fullduplexstream.0.1.15-beta'
Adding package 'System.Diagnostics.Tools.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Diagnostics.Tools.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Diagnostics.Tools.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Tools 4.0.0' to ClassLibrary17
Adding package 'System.Globalization.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Globalization.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Globalization.4.0.0' to 'packages.config'
Successfully installed 'System.Globalization 4.0.0' to ClassLibrary17
Adding package 'System.Linq.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Linq.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Linq.4.0.0' to 'packages.config'
Successfully installed 'System.Linq 4.0.0' to ClassLibrary17
Adding package 'System.Reflection.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Reflection.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Reflection.4.0.0' to 'packages.config'
Successfully installed 'System.Reflection 4.0.0' to ClassLibrary17
Adding package 'System.Resources.ResourceManager.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Resources.ResourceManager.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Added package 'System.Resources.ResourceManager.4.0.0' to 'packages.config'
Successfully installed 'System.Resources.ResourceManager 4.0.0' to ClassLibrary17
Install failed. Rolling back...
Package 'System.Runtime 4.0.20' does not exist in project 'ClassLibrary17'
Removed package 'System.Resources.ResourceManager 4.0.0' from 'packages.config'
Removed package 'System.Reflection 4.0.0' from 'packages.config'
Removed package 'System.Linq 4.0.0' from 'packages.config'
Removed package 'System.Globalization 4.0.0' from 'packages.config'
Removed package 'System.Diagnostics.Tools 4.0.0' from 'packages.config'
Package 'System.Runtime 4.0.20' does not exist in folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removing package 'System.Resources.ResourceManager 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removed package 'System.Resources.ResourceManager 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removing package 'System.Reflection 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removed package 'System.Reflection 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removing package 'System.Linq 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removed package 'System.Linq 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removing package 'System.Globalization 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removed package 'System.Globalization 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removing package 'System.Diagnostics.Tools 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
Removed package 'System.Diagnostics.Tools 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary17\packages'
install-package : Could not install package 'System.Runtime 4.0.20'. You are trying to install this package 
into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the 
package author.
At line:1 char:1
+ install-package nerdbank.fullduplexstream -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Install 
   PackageCommand

PM> 
```

**Comment by AArnott** [comment]
Perhaps a dupe, but a very similar bug is this:
1. Create a .NET 4.5 class library (not 4.5.1)
2. `install-package Validation -Version 2.2.4`

**Expected**
Successful install. This particular version of the package includes a Profile259 library folder and the only dependency is Validation.2.2.4.

**Actual**
Install fails with this log:

```
Attempting to gather dependencies information for package 'validation.2.2.4' with respect to project 'ClassLibrary18', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'validation.2.2.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'validation.2.2.4'
Resolved actions to install package 'validation.2.2.4'
Adding package 'System.Diagnostics.Debug.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Diagnostics.Debug.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Diagnostics.Debug.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Debug 4.0.0' to ClassLibrary18
Adding package 'System.Diagnostics.Tools.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Diagnostics.Tools.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Diagnostics.Tools.4.0.0' to 'packages.config'
Successfully installed 'System.Diagnostics.Tools 4.0.0' to ClassLibrary18
Adding package 'System.Globalization.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Globalization.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Globalization.4.0.0' to 'packages.config'
Successfully installed 'System.Globalization 4.0.0' to ClassLibrary18
Adding package 'System.Linq.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Linq.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Linq.4.0.0' to 'packages.config'
Successfully installed 'System.Linq 4.0.0' to ClassLibrary18
Adding package 'System.Reflection.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Reflection.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Reflection.4.0.0' to 'packages.config'
Successfully installed 'System.Reflection 4.0.0' to ClassLibrary18
Adding package 'System.Resources.ResourceManager.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Resources.ResourceManager.4.0.0' to folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Added package 'System.Resources.ResourceManager.4.0.0' to 'packages.config'
Successfully installed 'System.Resources.ResourceManager 4.0.0' to ClassLibrary18
Install failed. Rolling back...
Package 'System.Runtime 4.0.10' does not exist in project 'ClassLibrary18'
Removed package 'System.Resources.ResourceManager 4.0.0' from 'packages.config'
Removed package 'System.Reflection 4.0.0' from 'packages.config'
Removed package 'System.Linq 4.0.0' from 'packages.config'
Removed package 'System.Globalization 4.0.0' from 'packages.config'
Removed package 'System.Diagnostics.Tools 4.0.0' from 'packages.config'
Removed package 'System.Diagnostics.Debug 4.0.0' from 'packages.config'
Package 'System.Runtime 4.0.10' does not exist in folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Resources.ResourceManager 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Resources.ResourceManager 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Reflection 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Reflection 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Linq 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Linq 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Globalization 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Globalization 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Diagnostics.Tools 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Diagnostics.Tools 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removing package 'System.Diagnostics.Debug 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
Removed package 'System.Diagnostics.Debug 4.0.0' from folder 'c:\users\andarno\documents\visual studio 2015\Projects\ClassLibrary18\packages'
install-package : Could not install package 'System.Runtime 4.0.10'. You are trying to install this package 
into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the 
package author.
At line:1 char:1
+ install-package validation -version 2.2.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Install 
   PackageCommand

PM> 
```

**Comment by yishaigalatzer** [comment]
The issue here is that the package declares a dotnet folder. dotnet takes precedence over the portable profiles, and fails to install.

This is a known limitation, you need to pick either using dotnet or portable, both can't work together.

We are working on an alternative mechanism, your solution will be to either ditch the dotnet folder, or to create a net451 folder.

CC @ericstj

**Comment by ericstj** [comment]
_aside:_ Originally `dotnet` was supposed to be lower than `portable-` since that matches the semantics of `lib\` or `lib\any` however folks wanted `dotnet` to be special, as you'll see with the upcoming generation work.

Looking at the dependencies:

```
<dependency id="System.Collections" version="4.0.10" />
<dependency id="System.Diagnostics.Debug" version="4.0.10" />
<dependency id="System.IO" version="4.0.10" />
<dependency id="System.Runtime" version="4.0.20" />
<dependency id="System.Runtime.Extensions" version="4.0.10" />
<dependency id="System.Threading" version="4.0.10" />
<dependency id="System.Threading.Tasks" version="4.0.10" />
```

All of these require at least .NET 4.6.

@AArnott , if you don't actually need the newer surface area I'd recommend to build a single PCL that targets net451+win81+wpa81.  You can put that same dll in the `portable-` folder and the `dotnet` folder.  The `portable-` folder is really only for old PCL projects.  Your dependencies in the dotnet folder can be the older versions that match what's used by that profile.  Oren's tool can help you harvest those.  If you want to reduce the noise on older platforms you can null out the dependency sections as I discuss here: https://github.com/ericstj/NuGetDocs/blob/ericstj/nuget3samples/NuGet.Docs/Create/nuget3-packages-walkthrough.md

**Comment by yishaigalatzer** [comment]
@ericstj it is probably simpler to avoid dotnet all together

**Comment by ericstj** [comment]
Yeah if you don't care about running on DNXCore and you don't need to use any contracts that were added post-net451 that'd be simpler.

**Comment by ericstj** [comment]
The package will be pretty simple once nuget3 goes everywhere:

```
      <group targetFramework=".NETPlatform5.0">
        <dependency id="System.Collections" version="4.0.0" />
        <dependency id="System.Diagnostics.Debug" version="4.0.0" />
        <dependency id="System.IO" version="4.0.0" />
        <dependency id="System.Resources.ResourceManager" version="4.0.0" />
        <dependency id="System.Runtime" version="4.0.10" />
        <dependency id="System.Runtime.Extensions" version="4.0.0" />
        <dependency id="System.Threading" version="4.0.0" />
        <dependency id="System.Threading.Tasks" version="4.0.0" />
        <dependency id="Validation" version="2.2.4" />
      </group>
lib/dotnet/Nerdbank.FullDuplexStream.dll
lib/portable-net451+win81+wpa81/Nerdbank.FullDuplexStream.dll
```

The only reason why you need to add the second `portable-` copy is to support profile-based PCL projects since NuGet decided not to map `dotnet` to portable profile projects.

The only reason why I was suggesting empty dependency groups was to avoid noise in old packages.config projects (empty packages that just validate the platform supports the contract).  That goes away with project.json since NuGet won't show you the indirect dependencies.

**Comment by AArnott** [comment]
@ericstj What you prescribe as just the one `<group>` tag and the two lib folder sis exactly what I had. But nuget 3 evidently tries to install all the dependencies in my net45 or net451 targeting class library anyway and fails in the process. It was only by adding a bunch of empty groups that target each platform (net, wpa, wp, etc.) that I was able to get the package to install. It doesn't just suppress noise in packages.config -- it allows it to work at all. So is this a bug in nuget v3?

The nuget docs guidance I've read suggest I should use `portable-` to work with downlevel PCLs and use `dotnet` to ensure I work with newer PCLs. My NuGet package is designed to work with a very broad set of targets (net40+..., net451+wpa81+win81, and the newer dotnet). So far, it _seems_ like it works as long as I have lib folders for each, and explicitly specify groups for all individual target platforms, leaving them all empty except for the dotnet (.NETPlatform5.0) one.

**Comment by AArnott** [comment]
One example in particular for guidance I've read that suggests creating a package with a lib\dotnet folder as well as other lib\portable- folders is [Lucian's blog post](http://blogs.msdn.com/b/lucian/archive/2015/09/15/writing-a-nuget-package-for-vs2015-rtm-repost.aspx) (see step 2)

**Comment by AArnott** [comment]
Also from [nuget's own blog](http://blog.nuget.org/20150729/Introducing-nuget-uwp.html):

> This doesn’t mean that you can simply build a portable class library (PCL), bundle it up with dotnet dependencies declared and be done. If you want to be able to support projects using older versions of Visual Studio and NuGet clients that are building with traditional portable class libraries, you should still create and place a reference to the full PCL target framework moniker.

**Comment by ericstj** [comment]
Thanks, for sharing those docs.  I think you'll find that we're all saying the same thing if you read through them and compare to the doc I linked.   My statement about `portable-` was calling out the fact that there isn't any technical problem with associating `dotnet` with the correct `portable-` combinations, it was just something that NuGet decided not to do.  If you think it's important and makes your life easier, file feature request against NuGet to support `dotnet` on legacy portable profiles.  The logic we initially proposed was that if all targets supported by the legacy portable profile also map to `dotnet`, then consider the `dotnet` moniker for that portable profile, after considering any `portable-` folder.

> net45 or net451 targeting class library anyway and fails in the process

It was failing because your dependencies were on versions higher than those supported by net45 and Net451, as I mentioned before.  If you build a single dll against a portable profile that supports all your targets and package it as dotnet, listing the dependencies at the version you compile against it will work everywhere without the empty dependency groups.

Give the sample I just shared with you a try.  I'd expect it to install successfully on all the targets.  Keep in mind that this assumes `lib/dotnet/Nerdbank.FullDuplexStream.dll` and `lib/portable-net451+win81+wpa81/Nerdbank.FullDuplexStream.dll` are the same DLLs, compiled against `.NETPortable,Version=v4.6,Profile=Profile151`.  If you want net45 as well the profile would be different as well as the version of dependencies.

The empty dependency groups are only there to tell nuget that you know that all those dependent packages are inbox on that platform.  As I mentioned they aren't really needed in project.json based projects since the indirect dependencies are hidden.  Once project.json goes everywhere we can get rid of that annoying piece of the authoring.

**Comment by AArnott** [comment]
>  I think you'll find that we're all saying the same thing if you read through them and compare to the doc I linked.

@ericstj: one concern I have is that I've spent a very considerable amount of time (at least 24 real hours) studying docs, blogs, emailing, and experimenting to try to find out what works for my nuget packages. And I still didn't get what you're proposing that I should understand if I read and understood it all. I think if we improve our nuget docs and edit the blog posts as necessary, we can reduce the time NuGet customers have to invest to be successful with your tooling. That is something I'm sure we all want. IMO, reading a single doc should be enough to help folks who were quite familiar with the old system understand what they need to get their packages to play well in the new system _without abandoning support for all their existing users on the old system_. 

Of course I can't ditch the portable- and platform projects in my packages. Most/all of my users are on those projects today. But I want newer projects to be able to depend on my packages as well. What I'm hearing is that NuGet doesn't allow me any supported way to do this with my package. If that's correct, then yes, I think we need to file a feature request to fix that. If you can make 'dotnet' just work everywhere, that fantastic. But working by simply allowing users to add dotnet folders to their existing packages that already have several other folders seems like it might be simpler for nuget to support and allow package authors to easily add support without breaking support for downlevel nuget clients.
Support for downlevel nuget clients is very important since (AFAIK) nuget v3 isn't available on VS2013 at all.

**Comment by yishaigalatzer** [comment]
Andrew we completely agree, and we are already working on this issue, no need to file a new one.

Same answer for docs.

CC @csharpfritz

**Comment by AArnott** [comment]
@ericstj Have you taken a look at Validation 2.2.4? It follows the folder structure you suggested, with just one addition: it adds a portable-net40+\* profile as well:

```
lib
    dotnet (Profile151)
    portable-net451+win81+wpa81 (Profile151, same DLL as dotnet)
    portable-net40-*  (Profile328)
```

The 2.2.4 nuspec has no empty dependency groups. It just has the 'dotnet' one. If I understand your comments correctly, you suggest this should work, albeit with some 'noise' in the packages.config file for extra dependencies that aren't needed because net40 and net45 projects already have the types (in mscorlib) necessary for my assembly in the portable-net40-\* folder. However, the package install fails as I describe in the first comment in this bug.

I was able to workaround the installation failure in version 2.2.5 of my package, and the [_only_ difference between them](https://github.com/AArnott/Validation/compare/v2.2.4...v2.2.5) is that 2.2.5 has explicit, empty dependency groups for all the platforms except the dotnet one, suggesting it's not just noise reduction -- it prevents NuGet's dependency analyzer from deciding the package is incompatible with net40 and net45.

I don't mean to belabor the point if indeed this issue is being tracked elsewhere. But I'm not sure yet that all the issues are being tracked:
1. "Making 'dotnet' support the older profiles will fix this". But only if customers have the latest version of the NuGet client and VS2015.
2. "Using project.json instead of packages.config will fix this". But only if the dependency analyzer is also fixed, since even hidden dependencies have to be satisfied and NuGet seems to think they aren't. Also, almost all projects out there don't use project.json so this doesn't really help the downlevel target audience that I'm struggling with to begin with.
3. Since 2.2.5 "works", despite your comments saying this isn't supported, I want to know why and what I need to do to get into a supported state. Is there something in my 2.2.5 version that's broken that I haven't discovered yet?

**Comment by ericstj** [comment]
Validation would fail in a net45 project since it references `id="System.Runtime" version="4.0.10"` which is only supported on net451.  If you wanted the dotnet implementation to work everywhere you'd need to build this against a PCL profile including net45 which would result in a 4.0.0.0 System.Runtime reference.
1. Making `dotnet` applicable for profile based PCLs would eliminate the need for separate portable- folders.  You're already using separate portable- folders so this isn't going to save you much.  Also since net40 is not compatible with dotnet, you'd still need a separate folder for that.  If nuget did decide to do this it would have to go to nuget 2 as well.
2. Project.json instead of packages.config just reduces noise.  You still need to reference package versions that are supported by your target platforms.  If you still care about downlevel and you care about reducing reduce noise then I think you'll need to keep using empty dependency groups.
3. 2.2.5 would fail when running on .Net 4.5 if you depended on any API that was added in 4.0.10.0 of System.Runtime.  The binder will automatically unify 4.0.10.0 down to 4.0.0.0 and happily let it run on a 4.5 machine until it encounters the missing type or member.

The diff between System.Runtime 4.0.0.0 and 4.0.10.0 is the following:

```
System.Runtime.GCLargeObjectHeapCompactionMode 
System.Runtime.GCSettings.LargeObjectHeapCompactionMode 
System.String added IEnumerable<char>
```

**Comment by AArnott** [comment]
> Validation would fail in a net45 project since it references id="System.Runtime" version="4.0.10" which is only supported on net451. 

No it doesn't. A net45 project would use the portable-net40+\* folder, and the assembly in that folder does not reference System.Runtime, but references mscorlib instead:

![image](https://cloud.githubusercontent.com/assets/3548/10377445/302ca640-6db8-11e5-8536-005c382be08b.png)

> You still need to reference package versions that are supported by your target platforms.

But a net45 project doesn't need to reference all these extra .NET packages that NuGet v3 is trying to bring in. That's my whole point. It doesn't need System.Runtime. My assembly doesn't reference it as shown above, and my nuspec file doesn't specify it as a package dependency except when targeting .NETPlatform,5.0.

> 2.2.5 would fail when running on .Net 4.5 if you depended on any API that was added in 4.0.10.0 of System.Runtime

It shouldn't fail because as I state above, my .NET 4.5 compatible assembly doesn't reference System.Runtime at all.

**Comment by ericstj** [comment]
> net45 project would use the portable-net40+\* folder

Nope, it uses the dotnet folder.  As Yishai mentioned, NuGet prefers `dotnet` over `portable-a+b+c`.  If you install Validation 2.2.5 in a net45 project you get a reference to `Validation.2.2.5\lib\dotnet\Validation.dll`.  That library has a reference to System.Runtime 4.0.10.0 which, as mentioned before, is invalid for net45.

> a net45 project doesn't need to reference all these extra .NET packages that NuGet v3 is trying to bring in

The point of dotnet is to be an open ended qualifier.  You represent all your dependencies to the package manager and it will decide where you can run.  It means you don't need to tie your package down to a fixed set of TFMs.  Now if you choose to "fast-path" TFMs by saying you know that all your dependencies are satisfied by the framework itself, so don't bother installing packages, you can.  That's what we have been talking about by "reducing noise".

**Comment by AArnott** [comment]
I see. It was the 'dotnet always wins' that I had forgotten. Suppose I remove that folder. How can I keep the package working for all the new platforms and PCL types (at least those that exist today)? Is it enough that I have a `portable-net46+win81+wpa81` folder, or do I need to explicitly call out everything out in that folder name such as `portable-net46+win81+wpa81+dnxcore+xamarinios+...`?

**Comment by AArnott** [comment]
@ericstj I just manually tested a nuget package with a dotnet folder as well as portable-net45+... by installing it into a net45 packages.config project. The project references the lib\net45 assembly. This seems to contradict you're assertion that dotnet always wins, and again suggests that my approach works. What am I missing?

**Comment by ericstj** [comment]
Lib\net45 wins over lib\dotnet wins over lib\portable-net45+a+b+c.

**Comment by AArnott** [comment]
I don't have a lib\net45 folder. So I'm seeing lib\portable-net45+... win over lib\dotnet

**Comment by AArnott** [comment]
But in an Android project, the reference goes to the lib\dotnet folder. Gah! 
I'm just going to write it off as "dotnet in nuget is just too buggy to use at this point" and switch to legacy lib folders exclusively.

**Comment by ericstj** [comment]
Same rule applies on android, did you have a lib/android folder?  DotNET will win over potable, only thing that beats DotNET is a TFM-specific folder.

**Comment by AArnott** [comment]
As described above, my package doesn't have a TFM-specific folder. All it has is:

```
lib
    dotnet (Profile151)
    portable-net451+win81+wpa81 (Profile151, same DLL as dotnet)
    portable-net40-*  (Profile328)
```

And my observation is that when I install this package into a net45 class library it references the assembly from the portable-net40-\* folder. And when I reference it from an C# Android project, it references the assembly from the dotnet folder.

I do appreciate all the time you've put into this thread, @ericstj. But I do feel we're not really getting anywhere. You keep asserting that a certain behavior occurs and I keep seeing different behavior. And I'm jumping all over the place in various lib folder paths and nuspec dependency groups and seeing varying behaviors but I haven't landed on a single one that does _everything_ correctly at once. So I'm thinking the best way is to go back to the better understood and older pattern of  no lib\dotnet folder at all, and specifying all the platforms manually. This has the disadvantage (as I understand it anyway) of not working on future platforms that aren't named explicitly in my portable-\* folders, but as those platforms don't yet exist, and I have a package to ship today, I'll just go for what works. 
Hopefully, I can land on some folder names that gets it to work on every kind of platform and PCL available today.

**Comment by AArnott** [comment]
@ericstj In my attempt to remove the dotnet folder and still get my Validation package to work in an Android package, I've run into another nuget error that doesn't make sense to me:

> update-package : Unable to resolve dependencies. 'System.Diagnostics.Debug 4.0.0' is not compatible with 'Validation 2.2.8-g0ae750d6a5 constraint: System.Diagnostics.Debug (≥ 4.0.0)'.

This seems like a contradiction. Of course the version it's testing (4.0.0) complies with a >=4.0.0 constraint. Why is it complaining?

**Comment by AArnott** [comment]
Interesting. _That_ error somehow is generated because no active package source allowed NuGet to find the System.Diagnostics.Debug package. Once I activated the appropriate package source, that error went away. I can think of some more helpful error messages than the one I saw there...

Next one is that apparently Xamarin.Android doesn't work with System.Resources.ResourceManager 4.0.0:

> update-package : Could not install package 'System.Resources.ResourceManager 4.0.0'. You are trying to 
> install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain 
> any assembly references or content files that are compatible with that framework. For more information, 
> contact the package author.

How can I tell what packages are available for a given target platform? I have this dependency in my PCL that indicates it can target Xamarin.Android. So how is it that it references an assembly that isn't available on that platform?

**Comment by ericstj** [comment]
If you'd like I can sit down with you tomorrow and walk through scenarios and determine if you are hitting bugs or if you need updates to your package.

**Comment by AArnott** [comment]
I'd very much appreciate that, @ericstj. Thanks. I'm willing to change my package in any way in order to meet the requirements of working on my target platforms. Tomorrow afternoon looks good for me. I'll send an S+ in a spot I can find open on your calendar. For my own notes, I'll keep this list updated with those requirements:
- net40
- SL5
- wp80
- win80
- wpa81
- monoandroid
- monotouch
- xamarinios
- dnxcore
- net40+SL+monotouch+monoandroid+...
- net451+win81+wpa81
- net46+uap10.0+dnxcore50

For each of these, verify that the package installs, the assembly reference path is appropriate for the platform, and that a call to `Requires.NotNull` does not cause a compile-time or runtime failure due to missing assemblies or references.

**Comment by emgarten** [comment]
@AArnott I'm not able to repro this:

> And my observation is that when I install this package into a net45 class library it references the assembly from the portable-net40-\* folder. 

In a new net45 console app: _install-package Validation -Version 2.2.5_ adds a reference to lib/dotnet for me. Are you by chance using Visual Studio 2013 or retargeting your project as part of your steps when you see lib/portable-net40\* show up after the install?

**Comment by AArnott** [comment]
No. I don't even have VS2013 installed on this box. But just now, I'm seeing the same thing you are (although I saw what I claimed to several times yesterday....i think)

**Comment by AArnott** [comment]
@ericstj was able to resolve the issue for me. Here was the magic combination of settings that makes it all work (from what I've tested so far):
- dependency groups in nuspec explicitly called out for every target platform that are _empty_
- a dependency group for 'dotnet' that accurately express all contract package dependencies.
- of my two PCL projects, the contract-based one should target net40+win8+wp80+wpa81 instead of net451+win81+wpa81. 
- I _should_ have a lib\dotnet folder, as well as two other portable-\* folders in my nupkg file.

I think that was it. After that, everything worked like clockwork. :)

Thanks for your time, @ericstj 

I'll probably write a blog post on the right combination of things. But only after I review more docs so I'm not just throwing out inaccurate or redundant information. I'd love for the primary source of all this to come from the .NET and NuGet teams' doc sites.

**Comment by yishaigalatzer** [comment]
Andrew the point is that we are changing all of this to be reasonable. So not sure spending the effort is that valuable, particularly since it will be obsolete and confusing by update 1

Sent from my Windows Phone

**Comment by AArnott** [comment]
I'd love to save my effort where its value would be obsolete quickly, @yishaigalatzer. What part(s) of it is obsoleted by update 1 and where can I read about the newer design?

(and _my_ point is that I have to get something working with the software available today, so that why I'm happy Eric unblocked me)
