### ISSUE TITLE
NuGet Slow, becuase of UI refresh

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1536]
_From @reader-man on October 7, 2015 21:39_

When you use nuget at the solution level to add/remove a package to multiple Projects, it takes a long time for a trivial functionality, i think one of the reasons is because its trying to show the changes in the Solution Explorer and maybe other UI controls, instead of using the new VS 2015 mechanism of having a watch on nodes and metadata instead of a sharing model, to disconnect the UI from the Model.

_Copied from original issue: NuGet/NuGetGallery#2722_

**Comment by yishaigalatzer** [comment]
NuGet is using DTE to add/remove items from a project, it doesn't attempt to understand the project. We don't plan to and can't really change that.

There is one known slowness that has to do with batching operations when uninstalling packages. Tracked here - https://github.com/NuGet/Home/issues/1397.

We are investing in project.json based approach that makes nuget completely disengage from the project system, UWP apps already support that, and we plan to slowly bring this support over to other project systems. (You can experiment with that today, but note that these are not officially supported scenarios).
