### ISSUE TITLE
Reload Visual Studio package sources when nuget.config is modified manually

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1538]
Visual Studio should reload nuget.config settings after the config files have been manually modified outside of Visual Studio. Today sources are only reloaded when the Tools > Options dialog is used.

This could be achieved by re-initializing settings before package restores and before package operations. Note: SourceRepositories should be kept between reloads to avoid losing cached data such as index.json.

**Comment by yishaigalatzer** [comment]
Another alternative is to have a file watcher on all folders to indicate a change to nuget.config (need to track add/remove/move/change)

**Comment by davidfowl** [comment]
Yes please :smile:

**Comment by natemcmaster** [comment]
FWIW, in WTE, NuGet.config changes will trigger a restore on .NET Core projects, but PMC and NuGet GUI still don't update to include latest sources.

**Comment by anangaur** [comment]
We should fix this IMO.

**Comment by davidfowl** [comment]
Yes please 😄

**Comment by richlander** [comment]
Please, please!

**Comment by NickCraver** [comment]
This bit me recently several times as well, AFAIK it's not documented anywhere and it's hella confusing. "Just restart Visual Studio" is unfortunately becoming a more and more common answer from me in resolving problems. While this is far from the only issue, things like this contribute to the whole picture a user experiences.

**Comment by taori** [comment]
I sure hope priority 1 makes this happen seeing how this issue is rather old considering how relevant it is

**Comment by jainaashish** [comment]
This should not just be restricted with package sources, I'll be fine with an explicit option to reload all applicable nuget.config files but at least some option instead of reload the solution itself.

**Comment by anangaur** [comment]
Or maybe reload just happens (gets triggered) on any edit of package sources?

**Comment by AArnott** [comment]
This is hitting me a lot. .NET Core projects are _not_ immune. Even if those projects do re-run a restore when nuget.config changes, they do so with the old content of nuget.config. Package restore fails if the changes to nuget.config added a package source that restore then needs. 

I hit this on branch switch, pull, or manually modifying the file. I have to reload the solution in VS before package restore will work again.

**Comment by launchpadbs** [comment]
4 years later and still getting the same issue, is there a fix for this yet?

**Comment by anangaur** [comment]
> I hit this on branch switch, pull, or manually modifying the file. I have to reload the solution in VS before package restore will work again.

☝️  is one of the main scenarios for auto-loading the `nuget.config` file. At the minimum NuGet should not require a solution reload. IMO, the reload button should be overloaded to refresh the `nuget.config`s as well. We may need to also work on the positioning of the button to imply this overload.
![image](https://user-images.githubusercontent.com/14800916/59943615-8b13cc80-9417-11e9-92e7-fb952fb11faf.png)

**Comment by rrelyea** [comment]
Discussed possible solutions as a team today...

Scenarios missing:
* Branch Switch
* Git Pull

Possible solutions:
* listen to "branch switch" or "pull" type events in VS
* File watcher (existing nuget.config)
* watch for new files created in right directories
* Manual refresh in UI somewhere
* Overload in build/rebuild
* etc...

No slam dunk solution, but we are thinking about it.

**Comment by AArnott** [comment]
Please make sure you're watching the file for changes independently of a git HEAD change. If having the file is valid, changing the file is valid too. :)

**Comment by nkolev92** [comment]
A note for the implementer that the *IVSPathContextProviderX* API should be considered when making this change.

**Comment by drdamour** [comment]
how about just a reload action somewhere in the gui so i don't have to close and reopen VS?

**Comment by Thomas-p2-Elliott** [comment]
> how about just a reload action somewhere in the gui so i don't have to close and reopen VS?

If not this, then at least give us a command to punch into a console.

**Comment by AArnott** [comment]
I just run `dotnet restore` from the console to workaround this. Once the packages have been restored once, the content of nuget.config is of no consequence, so VS gets along fine without having to restart VS.

**Comment by richlander** [comment]
Perhaps it makes sense only to auto update if sources are declared via msbuild? It occurs to me that CPVM is all specified by msbuild and those settings will be important to honor due to branch (and other) changes.

**Comment by AArnott** [comment]
> It occurs to me that CPVM is all specified by msbuild

@richlander Is this because nuget.config gets translated into msbuild items during the restore target? CPVM certainly doesn't altogether ignore the nuget.config file.

**Comment by richlander** [comment]
That isn't what I mean. I meant that you can declare sources via msbuild. Maybe the first class reload scenario is via that since we already need it for this other NuGet feature that is not nuget.config related.
