### ISSUE TITLE
Package restore adds binding redirects to Views\web.config instead of project-level web.config

### ISSUE THREAD

**Issue by rcarduner** [NuGet/Home#1539]
NuGet PM 3.2.0; VS 2015.

Upgraded packages in several ASP.NET/MVC web projects in a single solution and binding redirects were added to Web.config in Views subfolder; the web.config at the project level was left untouched.  Pretty sure this is not correct.

**Comment by emgarten** [comment]
Would you provide the structure of your project and include the paths to all web.config files in the project? What were you steps for installing the package when you saw this behavior?

**Comment by rcarduner** [comment]
Hi Justin,

Thanks, I will try to get some essential details for you presently.  I did
undo those changes and also just upgraded PM for VS from 3.2.60902.10488 to
3.2.60914.10516.  But I have some more packages to clean up so if I can
reproduce that I can get you the exact steps.

Thanks,

Robin

**Comment by emgarten** [comment]
@rcarduner that should fix the issue. There were some known problems in this area in 3.2 RC. Let me know if you see it again with 3.2.60914.10516

**Comment by rcarduner** [comment]
I think that may have indeed fixed the issue.  I rolled back all my source
code to before the package updates and tried updating everything again with
the latest version, and did not see the issue again.  I was just looking to
see if I could find the previous version of package manager, but hadn't
yet. I didn't realise that it was only an RC version.  If you believe that
it was one of the issues fixed in the final release, since I can't repro it
again, that's good enough for me.

Thanks,

Robin
