### ISSUE TITLE
Could not install package in VS 2015

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1542]
_From @mikasoukhov on October 8, 2015 18:4_

Could not install package 'StockSharp 4.3.7'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain 
any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Works ok in VS 2013. In VS 2015 the package https://www.nuget.org/packages/StockSharp cannot be installed.

_Copied from original issue: NuGet/NuGetGallery#2727_

**Comment by MeniZalzman** [comment]
this package seems to be not following the NuGet package authoring guidelines, please ref to the following document to fix the package
http://docs.nuget.org/Create/Creating-and-Publishing-a-Package

**Comment by mikasoukhov** [comment]
I've created it using Nuget API v2.8.60717.93

Does the API still workable?

**Comment by yishaigalatzer** [comment]
The package is violating many basic tenants of what a NuGet package should look like
1. The dlls should be in the lib folder, under a target framework
2. You are including many dlls your package should reference as a dependency or as a Framework assembly

Without the first step, your package just cannot work, no references would be added. The second step makes the package bloated and it will conflict with many other packages

Last, the package includes licenses 3rd party components like ActiPro that you have no permission to distribute, we have been asked to delete packages with that content by ActiPro owner and will remove such packages (including this one) upon request from the owner.

Please unlist the package, and work out these issues with your dependencies.

**Comment by mikasoukhov** [comment]
So in VS 2015 behavior for Nuget packages was changed?

**Comment by davidfowl** [comment]
Very strange that it ever worked really. The package doesn't even have a lib folder. 

@mikasoukhov Are you the owner of this package?

**Comment by mikasoukhov** [comment]
Yes, owner.

**Comment by mikasoukhov** [comment]
Is the any option to set folder's name in creating package? I mean via API.

**Comment by yishaigalatzer** [comment]
Can you be more specific? What are you trying to do? What APIs are you referring to?

**Comment by mikasoukhov** [comment]
Trying to do packet via API.

Now I'm using the followed code:

var builder = new PackageBuilder();
builder.PopulateFiles(filesDir, new[] { new ManifestFile { Source = "**" } });
builder.Populate(manifest);

But files adds into the root folder. How I can set subfolder's name (net40 for example).?

**Comment by osya** [comment]
So to fix the problem and to make only one NuGet package for VS 2013 & 2015 the files hierarchy in the package should be changed. All dlls should be in the folder lib/net45 (I suppose all dlls in StockSharp package use .NET 4.5. If not other dlls should be placed in another special folder). To do so programmatically there are no any specific features in NuGet.Core. I suppose for this task Isolated Storage (https://msdn.microsoft.com/en-us/library/3ak841sy%28v=vs.110%29.aspx) should be used. I.e. in Isolated Storage lib/net45 directory structure should be created. And all files for package should be placed in appropriate folders in this directory structure in Isolated Storage. Then you could use your existing code for creating NuGet package. Naturally, as directory structure in the package will be changed all projects that use this StockSharp package will be broken. All these package should change paths to dlls to thir new location.
Workaround for users that need StockSharp NuGet package in VS 2015: Create console application in VS 2013 and install StockSharp NuGet package in this application. Then copy package folder from project in VS 2013 to your project in VS 2015. And you need to copy content of file .nuget/packages.config from VS 2013 project into the file <project_name>/packages.config in VS 2015 project.

**Comment by emanov** [comment]
You could use
npe.codeplex.com
to create nugget package with GUI

**Comment by sanjeev8800** [comment]
Severity    Code    Description Project File    Line    Suppression State
Error       Package 'StockSharp,4.3.17' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available (OR) package id, version are specified correctly.           0   

Please anybody idea why this error occured.

thanks
san

**Comment by skofman1** [comment]
@sanjeev8800 , I wasn't able to repro the issue you are describing. Installation of 'StockSharp,4.3.17' succeeded for me using VS 2015 Update 3. Are you still experiencing the issue?

**Comment by shishirx34** [comment]
@sanjeev8800 - I have created a separate issue to track the problem https://github.com/NuGet/NuGetGallery/issues/3321. Investigating.
