### ISSUE TITLE
Nuget 3.2.0.10516 command line client cannot restore packages under mono

### ISSUE THREAD

**Issue by delcypher** [NuGet/Home#1543]
The latest build of the nuget command line client does not seem to be able to run under Mono (4.0.4).

```
$ mono nuget.exe restore
MSBuild auto-detection: using msbuild version '4.0' from '/usr/lib/mono/4.5'.
Error parsing solution file at /home/dsl11/dev/thing/src/Thing.sln: Could not load type 'Microsoft.Build.Construction.SolutionParser'.
```

The old nuget client `2.8.60717.93` worked fine.

For context I'm running Arch Linux (kernel 4.1.6).

**Comment by delcypher** [comment]
I can't seem to find `Microsoft.Build.Construction.SolutionParser` as a documented type under https://msdn.microsoft.com/en-us/library/microsoft.build.construction.aspx

Where does it come from?

**Comment by yishaigalatzer** [comment]
For now you have to restore packages.config only.

There is remaining work to bring back support for xbuild.

**Comment by wpostma** [comment]
So for example, I can not build monodevelop on linux right now, with nuget 3.2?

**Comment by yishaigalatzer** [comment]
You can restore project by project but not a solution

**Comment by feiling** [comment]
Fixed. Tested with Mono 4.0.5.1 on Ubuntu 14.04.

**Comment by feiling** [comment]
Verified with nuget.exe 3.3.0.208, Mono 4.0.5.1, Ubuntu 14.04.
