### ISSUE TITLE
Package present in https://www.nuget.org/api/v2 but missing from https://api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [NuGet/Home#1544]
Severity    Code    Description Project File    Line
Error       NuGet Package restore failed for project BigQuery: Unable to find version '1.9.3' of package 'Google.Apis'..            0

Did we make a mistake while publishing the Google.Apis package?  How do we fix it?  We tried publishing again, but it failed:
$ nuget push google.apis.1.9.3.nupkg  ...
Pushing Google.Apis 1.9.3 to the NuGet gallery (https://www.nuget.org)...
Failed to process request. 'A package with id 'Google.Apis' and version '1.9.3'
already exists and cannot be modified.'.
The remote server returned an error: (409) Conflict..

**Comment by SurferJeffAtGoogle** [comment]
FYI confirmed that the NuGet v3 API does not list 1.9.3:
https://api-v3search-0.nuget.org/query?q=Id:Google.Apis

But the v2 API does:
https://www.nuget.org/api/v2/Packages?$filter=Id%20eq%20%27Google.Apis%27

Also note that other 1.9.3 Google.Apis.\* packages released on 8/12 do show up in the new API, eg. Google.Apis.Core and Google.Apis.Auth.

**Comment by maartenba** [comment]
Can you give it another go?

**Comment by SurferJeffAtGoogle** [comment]
I rebuilt, and it worked!  Thanks for your help!

Any tips for avoiding this issue with future releases?

**Comment by maartenba** [comment]
None, seems our indexing process missed this guy, I just gave it a punch. We'll be looking into why it wasn't included in the first place.
