### ISSUE TITLE
NuGet client adds reference to inappropriate target platform assembly

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1548]
1. Create a PCL targeting Profile7 (net45+dnxcore50+win8+monoandroid+monotouch+xamarianios)
2. Configure a NuGet Package Source for this URL: `https://ci.appveyor.com/nuget/validation-qrkoqeildw84`
3. Install-Package Validation -Version 2.2.18-g0904725fe0
4. Inspect the reference to Validation.dll that was added to the project. In particular, look at its HintPath metadata.

**Expected**
The assembly reference should be to the `lib\portable-net45%2Bdnxcore50%2Bwin%2Bwpa81%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10\Validation.dll` assembly.

**Actual**
The assembly reference is to `lib\portable-net40%2Bsl50%2Bwin%2Bwpa81%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10\Validation.dll` 

The expected is correct where the actual is incorrect because in fact the project targets dnxcore50 which is only mentioned in the expected path. Also, net45 is mentioned in the expected path and is therefore better than the net40 match.

**Repro machine configuration**
Windows 10 Tools 1.1 is installed.
The folder `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.5\Profile\Profile7\SupportedFrameworks` has these contents:

.NET Framework 4.5.xml
ASP.NET Core 5.0.xml
Windows 8.xml
Xamarin.Android.xml
Xamarin.iOS.Unified.xml
Xamarin.iOS.xml

**Comment by AArnott** [comment]
This found in the process of working with @ericstj on #1535

**Comment by yishaigalatzer** [comment]
@emgarten can you provide a quick opinion on the matter?

**Comment by MeniZalzman** [comment]
Profile 7 does not include dnxcore50, try removing that from your folder path

**Comment by ericstj** [comment]
@MeniZalzman I believe it does as of the latest VS update.  /cc @rchande

**Comment by emgarten** [comment]
Was this added to the .NET framework or to Visual Studio for projects of this type?

**Comment by ericstj** [comment]
It was a change to the portable targeting pack afaik. Kevin or Ravi should be able to give more details. @pilchie

**Comment by Pilchie** [comment]
Yes, we opted dnxcore50 into the existing contract based profiles.

**Comment by Pilchie** [comment]
Tagging @rchande too.

**Comment by yishaigalatzer** [comment]
dnxcore50 was removed from PCL7 this should be resolved now
