### ISSUE TITLE
NuGet v3.2 does not negotiate Kerberos, but only for restore and only for project.json references

### ISSUE THREAD

**Issue by mababey** [NuGet/Home#1551]
I was catching up with this thread: https://github.com/NuGet/Home/issues/456, but the discussion revolved around basic auth.  I’m seeing issues with Windows Integrated Auth.

We have a UWP app we’re trying to migrate from VS2015 RC to RTM.  For the RC, using packages.config and NuGet v3.0, there’s no problem installing packages from our intranet server for third-party components, let's call it http://internal/nuget/.  This works on the MSBuild hooks whether running in the IDE, or invoking MSBuild directly on the command line.  http://internal is joined to an internal AD domain, has NTLM and ASP.NET impersonation enabled, and anonymous access disabled.

For RTM, we have to move to project.json, which means we also have to invoke restore “manually” for command line builds, which means we need NuGet client v3.2.  I see two things:
• In the IDE, I get spammed with auth prompts by the VSIX.  (If I enter credentials, the build succeeds, otherwise packages are not downloaded.)
• On the command-line, it just gives up with a bunch of errors, “Please provide credentials for: http://internal/nuget/” and “Cannot prompt for input in non-interactive mode.”

But this is the same server for which we never had to enter credentials, resolving many of the same packages.

What’s even more bizarre, is that if, everything else being identical, I run two consecutive “nuget restore” operations, where one targets a solution that has all packages.config based projects, and the other solution has a mix of packages.config/project.json, the pure packages.config approach works.

In the working pattern, the first request is anonymous and results in a 401 status, and is followed by a request with a Kerberos ticket in the authorization header which results in a 200 status.  In the failing pattern, after the 401 it just quits.

So it seems to boil down to the new code added to handle project.json references not negotiating NTLM.

This is all running on the latest Visual Studio 2015, with the .NET 1.1 tools update, and the latest NuGet extension in the IDE, and the latest NuGet.exe downloaded from nuget.org. The machine is joined to the same domain as http://internal/nuget, and I'm logged in with a domain user account.

**Comment by feiling** [comment]
Fixed. https://github.com/NuGet/NuGet.Client/commit/1e93f0241bca4ebc44f09d94f1396e71d9373c05
