### ISSUE TITLE
nuget.exe install generates a lot of (parallel) network requests compared to UI or nuget.exe.2.*

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1552]
nuget.exe install generates a lot of (parallel) network requests compared to UI or nuget.exe.2.*.
This happens, because, nuget.exe has to install under "Any" target framework, and with the new dependency resolution mechanism, it seems necessary that those requests are made.

Repro steps:
1. nuget.exe install t4mvc

Expected:
Number of requests generated is comparable to the UI or nuget.exe.2.8

Actual:
Number of requests generated is much higher 177 for nuget.exe.3.\* vs 6 for the nuget.exe.2.*

**Comment by MeniZalzman** [comment]
this bug is about doing multi phase gather when resolving the dependency tree

**Comment by emgarten** [comment]
This can be fixed by walking the dependencies for the target packages and optimistically taking the best match, then passing all of the ideal options to the current resolver to solve any conflicts.

**Comment by emgarten** [comment]
@johnataylor this bug tracks the optimistic resolver. The work is partially done and on a branch in nuget.client.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
