### ISSUE TITLE
nuget.exe install does not say 'All the packages are already installed', when they are.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1553]
nuget.exe install does not say 'All the packages are already installed', when they are.
[Regression from nuget.exe 2.8.*]

Repro steps:
1. Create a net45 Console Application and install WindowsAzure.Storage
2. Confirm that the packages are restored
3. Run nuget.exe install on the packages.config from Step 1

Expected:
Message saying 'All the packages are already installed'.

Actual:
There is no message of any kind. exe just exits.

**Comment by RanjiniM** [comment]
Fixed
