### ISSUE TITLE
nuget.exe install throws if one of the sources is bad on the -Source switch.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1555]
nuget.exe install throws if one of the sources is bad on the -Source switch.
[Regression from nuget.exe 2.*]

Repro steps:
1. nuget.exe install EntityFramework  -Source "https://nuget.doesnotexist.org;https://www.nuget.org/api/v2"

Expected:
Package gets installed with a warning that a source does not exist.
WARNING: The remote name could not be resolved: 'nuget.doesnotexist.org'
Installing 'EntityFramework 6.1.3'.
Successfully installed 'EntityFramework 6.1.3'.

Actual:
The remote name could not be resolved: 'nuget.doesnotexist.org'. And, the package is not installed.

**Comment by MeniZalzman** [comment]
We get that this issue is a regression but we consider this behavior incorrect. we will consider reopening based on customer feedback
