### ISSUE TITLE
nuget.exe install does not honor '-DisableParallelProcessing' switch

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1556]
nuget.exe install does not honor '-DisableParallelProcessing' switch

Repro steps:
1. nuget.exe install t4mvc -DisableParallelProcessing

Expected:
Necessary package(s) are installed serially and parallel requests are not made

Actual:
Used Fiddler to verify that parallel requests are made and the switch '-DisableParallelProcessing' is not honored

**Comment by emgarten** [comment]
This appears to be fixed in 4.4.0.  Watching the fiddler trace I see calls running sync with disable parallel, and in parallel without it.
