### ISSUE TITLE
Nuspec dependency w/o version specified installs earliest 

### ISSUE THREAD

**Issue by kimjohnson** [NuGet/Home#1557]
In prior NuGet versions a version-agnostic dependency, such as 
     dependency id="NuGetPowerTools" 
would install the latest version.  Now with NuGet 3 the earliest version is installed.

**Comment by yishaigalatzer** [comment]
You have worlds here:

In packages.config you can control the dependency behavior through a dropdown in the UI or through a parameter in the powershell console

In project.json it is by design.

**Comment by kimjohnson** [comment]
Thanks.  It is a breaking change, but it's good to know the workaround is easy.
