### ISSUE TITLE
nuget.exe scripted package update issues

### ISSUE THREAD

**Issue by pmcgrath** [NuGet/Home#1559]
Hi all,
I am currently working in a system that has lots of micro-services where I sometimes want to update a package across a number of services which are in their own repositories. That is I do not want to necessarily want to update all the services. 
I have looked into scripting updating these updates with nuget.exe but have observed that its behavior is different to the nuget package manager within VS. I can see that it does not appear to support assembly binding redirect updates to config files for example.

I know the VS package manager version has access to the project source object model and has a bit more context to work with, but wanted to know if there are any plans to support this type of scripting ?

See this link for someone in the same situation
http://stackoverflow.com/questions/31385224/auto-update-nuget-packages-assembly-redirects-are-not-added

Thanks in advance
Pat

**Comment by yishaigalatzer** [comment]
Hey Pat,

We do not plan to support these scenario from commandline and packages.config.

Projects using project.json will be able to do most of that, because they do not modify your projects. You might still have to do binding redirects manually.
