### ISSUE TITLE
PackageManagement.VisualStudio: targetframework retargeting error is not shown in VS

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#156]
Repro steps:
1.	Create a new project target .net 4.5 
2.	Install package TestPackage.retargetNET using the below command in "package manager console"  
Install-Package TestPackage.retargetNET -version 1.0.0
3.	Now change the target framework of the project to .net40  
4.	The below build error should be shown. On a successive builds, the build error should go away and a build warning should be shown. Packages.config file should have "requireReinstallation" set to true for TestPackage.retargetNET package. 

![retarget](https://cloud.githubusercontent.com/assets/1087852/6447498/c13cfaac-c0c7-11e4-8efc-2931da90fdc5.jpg)

**Comment by deepakaravindr** [comment]
@danliu will take care of this

**Comment by danliu** [comment]
Fixed via https://github.com/NuGet/NuGet.VisualStudioExtension/commit/675c5d8e28493eaa2576e9b6d609f691d346af27
