### ISSUE TITLE
NuGet should respect specific version dependency even if higher version package exists locally

### ISSUE THREAD

**Issue by codepic** [NuGet/Home#1561]
Here's my NuGet.config in the solution folder

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="_packages" />
    <add key="dependencyVersion" value="Highest" />
  </config>
  <packageSources>
    <!-- Do not consider any other previously defined package sources -->
    <clear/>
    <!-- Only use our private feed and what can be found in there -->
    <add key="Lojaali" value="http://www.myget.org/F/lojaali/auth/{api-key}/api/v3/index.json" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <activePackageSource>
    <add key="Lojaali" value="http://www.myget.org/F/lojaali/auth/{api-key}/api/v3/index.json" />
  </activePackageSource>
</configuration>
```

In the `Lojaali` feed, we have a package that has specific version dependency to package id `Facebook`.

``` nuspec
  <dependencies>
    <dependency id="Facebook" version="[5.4.1]"/>
  </dependencies>
```

In the feed `Lojaali` there is only that specific version `5.4.1` of `Facebook` available. The private feed also has an upstream source to `NuGet.org` but that feed is filtered to exclude prerelease versions.

In my local packages folder however, I got `Facebook.7.0.10-beta` which isn't available in the feed, nor it is specified by any package as a dependency version.

Now, just because I have that package locally and I try to install my own package (sourced from the custom feed) which has a specific version dependency to `Facebook.5.4.1` and I use `-DependencyVersion Highest` NuGet grabs that locally stored beta-package and completely ignores my package's specific version dependency.

While it is very handy in development perspective to have local packages picked over the ones sourced from the feed, it's highly annoying in production use when you want to use a central location for packages but to lock certain path in source control to using only one specific feed and NuGet starts picking up packages which aren't even available in the feed. Not to mention going ahead and disregarding specific version dependencies.

I do understand that I am practically saying `-DependencyVersion Highest` but as a package consumer one would expect it to mean `highest supported` by the package. Not highest available anywhere even if no package would love to use it.

I have also verified it with `LINQPad` and `Fiddler` and ensured the `Facebook -Version 5.4.1` is not available from the feed and also during `Install-Package`, there's no query to the feed that would even check for the package.

But as soon as I delete the package locally, everything reverts to being fine.

Here's a picture of the feed, the package I select, the options I take, the package explorer with specific version dependency and of course the rogue package stored locally on my disk.

![nuget_issue](https://cloud.githubusercontent.com/assets/3933589/10461964/9f55ccec-71e4-11e5-872d-8519f844aa60.PNG)

**Comment by emgarten** [comment]
That is very strange that it is ignoring the dependency constraint in your scenario. What version of the NuGet vsix do you have installed?

**Comment by codepic** [comment]
NuGet Package Manager for Visual Studio 2015 Version `3.2.60914.10516`

Same version as available in [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d)

**Comment by emgarten** [comment]
Are you able to repro this issue when using the v2 source for your MyGet feed? The resolution phase does not read the nupkgs, only the package metadata as given by the feed, so if we can rule that out it would narrow this issue down.

You could also try copying the packages to a local folder, adding it as a source, and installing from that.

**Comment by codepic** [comment]
I'll check. Just a moment.

**Comment by codepic** [comment]
@emgarten I just checked multiple times switching between v3 and v2 sources while closing and reopening the solution in beween the tests. Every time the result was consistent. While it does replicate in v3, it does not replicate with v2 source.

**Comment by emgarten** [comment]
Thank you for checking that, I haven't seen this issue come up anywhere else so this could be a MyGet  v3 issue.

@maartenba @xavierdecoster is the strict version range syntax making it into the MyGet v3 feed in the same way it does on nuget.org?

**Comment by codepic** [comment]
Not sure if it helps but here's the difference of the preview window in visual studio when I switch the feeds in order to repro the situation. Note, there's no single specific version reported by the v3 feed.

![ngbg](https://cloud.githubusercontent.com/assets/3933589/10473806/325d83f6-7238-11e5-9679-5faf8ae29d38.png)

And here's the nuspec for the package I'm installing. For if it helps.

``` nuspec
<?xml version="1.0"?>
<package >
  <metadata>
    <id>Lojaali.Mvc.Common</id>
    <version>$version$</version>
    <title>Common libraries for MVC Platform</title>
    <authors>Lojaali Development</authors>
    <owners>Jani Hyytiäinen,Michael Parr</owners>
    <licenseUrl>http://lojaaligroup.com/</licenseUrl>
    <projectUrl>http://lojaaligroup.com/</projectUrl>
    <iconUrl>https://lojaalicampaigns.blob.core.windows.net/devportal/img/lojaali.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Common libraries for MVC Platform</description>
    <summary>Common libraries for MVC Platform</summary>
    <releaseNotes>Common libraries for MVC Platform</releaseNotes>
    <copyright>Copyright 2015</copyright>
    <tags>Lojaali MVC Areas</tags>
    <dependencies>

      <!--Our own dependencies-->
      <dependency id="Lojaali.Core.Platform" version="[$version$]" />
      <dependency id="Lojaali.Core.Services" version="[$version$]" />
      <dependency id="Lojaali.Js.App" />

      <!--While migrating to Microsoft.Owin.Security.Facebook-->
      <dependency id="Facebook" version="[5.4.1]"/>
      <dependency id="FacebookWeb" version="[5.4.1]"/>

      <!--Uhh, for Mvc :)-->
      <dependency id="Microsoft.AspNet.Mvc" version="[5.2.3]"/>

      <!--Bundling and Minification-->
      <dependency id="Microsoft.AspNet.Web.Optimization" version="[1.1.3]" />

      <!--Owin & Identity-->
      <dependency id="Microsoft.Owin.Security.OpenIdConnect" version="[3.0.1]" />
      <dependency id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2" />
      <dependency id="Microsoft.Owin.Security.Cookies" version="[3.0.1]" />
      <dependency id="Microsoft.AspNet.Identity.Owin" version="[2.2.1]" />

      <!--For collecting data from within the software-->
      <dependency id="Microsoft.ApplicationInsights.Web" version="1.0.0" />
      <dependency id="Microsoft.ApplicationInsights.DependencyCollector" version="[1.2.1]" />
      <dependency id="Microsoft.ApplicationInsights.PerfCounterCollector" version="[1.2.1]" />

      <!--Well, better linq queries-->
      <dependency id="Morelinq" version="[1.3.0]" />

      <!--Needed for client-side localization-->
      <dependency id="Microsoft.AspNet.SignalR" version="[2.2.0]" />

      <!--Needed for Storage-->
      <dependency id="WindowsAzure.Storage" version="[6.0.0]" />
    </dependencies>
    <references>
      <reference file="Lojaali.Web.Mvc.dll" />
      <reference file="DeusPak.Areas.Account.dll" />
      <reference file="DeusPak.Areas.CMS.dll" />
      <reference file="DeusPak.Areas.Profile.dll" />
      <reference file="DeusPak.Areas.Support.dll" />
    </references>
    <frameworkAssemblies>

      <!--Needed for example for RegularExpressions-->
      <frameworkAssembly assemblyName="System" targetFramework="net452" />
      <!--Still needed for MVC5-->
      <frameworkAssembly assemblyName="System.Web" targetFramework="net452" />
      <!--Needed for Linq to Objects-->
      <frameworkAssembly assemblyName="System.Data.Linq" targetFramework="net452" />
      <!--Needed to be able to render images-->
      <frameworkAssembly assemblyName="System.Drawing" targetFramework="net452" />
      <!--Advanced C# Stuff such as Reactive Extensions-->
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="net452" />

    </frameworkAssemblies>
  </metadata>
  <files>
    <file src="**\Lojaali*Web*.dll" target="lib\net452" exclude="*Code*;*Cs*;*Trivia*;*Rewards*" />
    <file src="**\Lojaali*Web*.pdb" target="lib\net452" exclude="*Code*;*Cs*;*Trivia*;*Rewards*" />
    <file src="**\DeusPak*Areas*.dll" target="lib\net452" exclude="*Code*;*Cs*;*Trivia*;*Rewards*" />
    <file src="**\DeusPak*Areas*.pdb" target="lib\net452" exclude="*Code*;*Cs*;*Trivia*;*Rewards*" />
  </files>
</package>
´´´
```

**Comment by emgarten** [comment]
@codepic that shows the problem clearly. The nuspec looks correct to me. The V3 feed must be dropping the []'s when writing the ranges into the registration files.

**Comment by maartenba** [comment]
@codepic we deployed an update to MyGet which should fix this, can you verify?

**Comment by codepic** [comment]
@maartenba  Unfortunately I cannot repro it anymore. But that's a good thing... right?

So, to recap:
1. Had a beta nupkg on local folder
2. Used v3 feed
3. DependencyBehavior Highest
4. IncludePrerelease on
5. Prereleases filtered from upstream
6. Try to install a package that depends on the beta-package but a specific version dependency to lower stable release version

NuGet **used to** offer local beta packages overriding my source but **not anymore**. Also Package Manager Preview -window now shows correct version information.

So, on my end **it looks like fixed**. Thanks. And I think we noticed when you deployed the update to MyGet. Things got a little sluggish for a while ;)

**Comment by maartenba** [comment]
Thanks @codepic !
