### ISSUE TITLE
NuGetFramework.GetShortFolderName is a little odd

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1568]
`DNXCore,Version=v5.0` => `dnxcore5`? It should be `dnxcore50`... Same for `net4`, etc.

/cc @davidfowl @yishaigalatzer

**Comment by emgarten** [comment]
This could easily be fixed, but we would more or less need to define the expected format for every TxM due to how random the format is today.

Example: win80, wp80 look odd also.

**Comment by analogrelay** [comment]
I'd rather just normalize to at least two digits than try to emulate exactly the format used by older versions. As @yishaigalatzer and I discussed, it's not likely to break anything since everywhere that reads them does full parsing to understand them, so it's just for aesthetics. I think the two digit values are clearer, even for `win80` (especially with `win81` in existence)

**Comment by emgarten** [comment]
NuGet/NuGet.Client@05c53d7e7630503607f79068f2dfafd1ea88b3c0
