### ISSUE TITLE
Follow up to #1397

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1569]
Made a pretty large fix, but looks like we have more room for improvement

From @jwynia 

> Given VS2015 Enterprise, web application project in .NET 4.5.2, standard MVC project wizard output.
> When I install the KendoUICore package
> Then it takes 20+ minutes to install
> 
> I've noticed that this particular JS library causes problems with VS when added manually as well, which leads me to suspect that it's the "add file to VS project" portion of the package install that's bogging things down. But, with all of the translation, etc. files, more and more JS libraries have tons of JS/CSS/img files to add, so it's not going to get better on its own.

Currently - Most of the time is spent in projectItem.Delete() which is a DTE call.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
