### ISSUE TITLE
Improve extension load error message

### ISSUE THREAD

**Issue by ericsciple** [NuGet/Home#1570]
Consider improving the extension load error message. The error printed from nuget.exe to the console is:

_Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information._

Something like the following might be more helpful:

_Failed to load extension <FULL PATH TO EXTENSION DLL>. If you are using the environment variable NUGET_EXTENSIONS_PATH to load extensions, verify all DLL dependencies are resolvable as well. Inner exception: The assembly with display name 'nuget' failed to load in the 'LoadFrom' binding context of the AppDomain with ID 1. The cause of the failure was: System.IO.FileNotFoundException: Could not load file or assembly 'nuget, Version=3.2.0.10516, Culture=neutral, PublicKeyToken=31bf3856ad364e35'  or one of its dependencies. The system cannot find the file specified._

**Comment by yishaigalatzer** [comment]
@ericsciple can you please share with us the extension you had that failed and the exact setup that leads to it?

**Comment by yishaigalatzer** [comment]
Another commit: https://github.com/NuGet/NuGet.Client/commit/8bc54adc3ce0e4c1756fb0ccf2fbde2202c50bfe
