### ISSUE TITLE
Bring powershell cmdlets outside visual studio

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#1573]
We are trying to automate the update package proces of in-house packages through a powershell script. The commands we need (e.g. update to a specific version) are not exposed in nuget.exe, only by the powershell cmdlets in visual studio. Why isn't it possible to bring those cmdlets outside visual studio?

**Comment by yishaigalatzer** [comment]
Because these commandlets depend on visual studio environment to run. We don't plan to bring them out of visual studio.

If there is a specific feature you are missing in nuget.exe we will gladly add it. Going forward with project.json we are obsoleting many of the reasons for these cmdlets.

**Comment by tomkuijsten** [comment]
I understand your point of view. I'll add another issue as question about my situation.
