### ISSUE TITLE
NuGet 2 mirror command does not replace missing packages

### ISSUE THREAD

**Issue by jc1001** [NuGet/Home#1574]
Hi there,

I've found an issue while using the "mirror" command (NuGet.ServerExtensions.dll) in NuGet 2 to mirror from several remote repositories to a local path.

The problem occurred in the following scenario:
- Package A has a dependency on package B. 
- Using the mirror command on package A (with the default DependenciesMode option), mirror pulls both package A and B as expected.
- I then went and deleted package B from the local path and ran the command again. 
- According to the command-line output B is already present on the local path and it wasn't pulled again.
- If I delete A and B and run the command again, everything works as expected (both packages are pulled again).

The problem seems to be related to the following lines of code in "PackageMirrorer.cs" (from line 99):
https://github.com/NuGet/NuGet2/blob/dev/src/CommandLine.ServerExtensions/PackageMirrorer.cs

``` C#
foreach (var p in packagesToMirror)
{
  if (TargetRepository.Exists(package))
  ...
```

Shouldn't this be:

``` C#
foreach (var p in packagesToMirror)
{
  if (TargetRepository.Exists(p))
  ...
```

**Comment by yishaigalatzer** [comment]
Thanks for the report, we will not be fixing this any time soon (as it falls well below our other issues we are prioritizing at the moment), but we would love to take a PR if you want to give it a try.
