### ISSUE TITLE
NuGet.exe does not restore packages from project.json correctly when using one authenticated feed

### ISSUE THREAD

**Issue by emanuelquintero** [NuGet/Home#1575]
## Problem

I try restoring the packages in project.json. 
1. It tries to get index.json from AuthenticatedFeed
2. Gets 401 (3 times)
3. Gets 200 (with auth headers)
4. Tries to get PackageInNuGetOrg from AuthenticatedFeed
5. Gets 401 
6. Gets 404 (with auth headers)
7. Retries to get the same package from the same feed so steps 5 and 6 are repeated
8. NuGet.exe hangs waiting for credentials to be inputted into the command line

If my project.json only contains either package it works, but when both are there it fails to restore.
### Command line

NuGet.exe restore project.json -ConfigFile nuget.config
### project.json

``` json
{
    "dependencies": {
        "PackageInNuGetOrg": "4.0.0",
        "PackageInAuthenticatedFeed": "1.0.0"
    },
    "frameworks": {
        "dotnet": { }
    }
}
```
### nuget.config

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="AuthenticatedFeed" value="AuthenticatedFeed" />
  </packageSources>
  <packageSourceCredentials>
    <AuthenticatedFeed>
      <add key="Username" value="UserName" />
      <add key="Password" value="Password" />
    </AuthenticatedFeed>
  </packageSourceCredentials>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>
```

**Comment by yishaigalatzer** [comment]
Can you tell us some more about your scenario. 

What version of nuget.exe are you using? (Please use https://dist.nuget.org/index.html to get 3.2.1)
What type of authentication is used on your server (basic auth? Windows Auth?)

What server are you hitting that has a V3 feed other than nuget.org ?

**Comment by emanuelquintero** [comment]
NuGet version: 3.2.1
The server is the VisualStudioOnline.

The problem is that I was using https://www.nuget.org/api/v2/ instead of https://api.nuget.org/v3/index.json

Still, the client should've just thrown an exception saying that it couldn't restore all the packages instead of misleading with auth problems.

What throws me off is that if I restore only the PackageInNuGetOrg OR the PackageInAuthenticatedFeed it works, but the hybrid of V2 and V3 endpoints/packages doesn't work.

**Comment by emanuelquintero** [comment]
Cannot repro anymore.
