### ISSUE TITLE
Extensions are no longer loaded from the directory where nuget.exe lives

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1576]
Extensions were previously loaded from the same directory as nuget.exe, in addition to NUGET_EXTENSIONS_PATH and %LOCALAPPDATA%\NuGet\Commands.
It looks like this code got dropped when NuGet.CommandLine moved repos.

This feature is useful in that NUGET_EXTENSIONS_PATH is used by multiple versions of nuget.exe 2.X and 3.X, while extensions are very likely only compatible with specific versions of nuget.exe.

**Comment by zarenner** [comment]
https://github.com/NuGet/NuGet.PackageManagement/pull/110

**Comment by yishaigalatzer** [comment]
@zarenner please move the pr over to nuget.client

**Comment by zarenner** [comment]
I've moved this over to NuGet.Client, but I don't know where to add a functional test.  The EndToEnd tests look like they're for the Package Manager Console, not for nuget.exe.

**Comment by yishaigalatzer** [comment]
Thank you. @deepakaravindr will add a pointer shortly

**Comment by deepakaravindr** [comment]
@zarenner , For adding functional tests to nuget.exe, Please check out 

https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/NuGetRestoreCommandTest.cs

 and other files under https://github.com/NuGet/NuGet.Client/tree/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test

They are all functional tests that use https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/CommandRunner.cs

to launch a nuget.exe process and verifies the exit code, output stream and error stream as needed.

Please let me know if you have any issues

**Comment by zarenner** [comment]
Perfect, thanks.

**Comment by deepakaravindr** [comment]
Verified locally that the changes are good and works as desired

![image](https://cloud.githubusercontent.com/assets/2380340/10746643/3423d5c4-7c0a-11e5-8dd4-603503e7f22a.png)
