### ISSUE TITLE
How do I update multiple solutions at once

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#1578]
We use nuget packages for enterprise components. Some components are used by many others and when we release a new version, we now manually open each solution and update through the nuget package manager. Is there any way to automate this (preferabel powershell)?

**Comment by emgarten** [comment]
Visual Studio can be updated using DTE. It is possible for an external process to find Visual Studio through the running object table and pass commands to the NuGet powershell window through DTE.

Within NuGet project.json is designed to solve this problem, it allows floating versions which are determined at restore/build time.

**Comment by tomkuijsten** [comment]
Project.json is not an option for it only supports UWP/PCL/ASP projects and not the "regular" .NET applications (WPF/Console/Assembly).

Do you have some sample code for executing powershell in Visual Studio from another application?

**Comment by yishaigalatzer** [comment]
project.json does work for other apps, but it has the same limitations as UWP (and is not yet officially supported). We do use it to build nuget.exe and nuget itself. But as it is experimental for these other project types, I completely understand not opting to using it.

We have a piece of sample code (not production hardened) that will show you how to do that. @deepakaravindr  is going to push it to the entropy repo and share here.

**Comment by yishaigalatzer** [comment]
Back to provide sample code:
1. Launcher
   https://github.com/NuGet/Entropy/tree/master/NuGetFunctionalTestsLauncher
2. Out functional tests that do run powershell scripts in visual studio
   https://github.com/NuGet/NuGet.Client/tree/dev/test/EndToEnd

**Comment by tomkuijsten** [comment]
Wauw cool, thanks a million for the sample code!
