### ISSUE TITLE
Prevent installing multiple versions of a package in the solution

### ISSUE THREAD

**Issue by plaurin** [NuGet/Home#1579]
I would like to see a way to prevent multiple versions of the same NuGet packages to be installed in my solution. What happens is that developers usually add packages at the project level and usually the latest stable version at that point in time. Over time if we are not careful we end up with different versions of the package in the solution. This is a problem as my experience with this is hard to diagnose run-time errors or weird behaviours unless with set up binding redirects properly.

A better solution would be to help us prevent such things to happen. At our company we actually ban developers to use the manage NuGet package at the project level for that reason.

The other thing is that currently the UI doesn't help us see rapidly if we have this problem. For example if I have 3 projects with 3 versions of Json.Net I need to click on the version combo box to see if multiple versions of that package is present in my solution. And I need to this for all packages of my solution (sometime I have more than 40 packages in a solution) which is time consuming.

My current work-around is keeping a close watch on every changes to packages.config files in code reviews and a custom tool I created that scan all the packages.config files of my solution and report packages with more than one version.

**Comment by yishaigalatzer** [comment]
We are going to have a consolidate view in solution level package manager, so that issue should resolve the UI help.

We could have a feature to warn/enforce it in one of the next releases. This needs some more thought to how exactly we will materialize it.

**Comment by emgarten** [comment]
Closing as fixed based on the comment above. Consolidate view is available in the UI.
