### ISSUE TITLE
nuget fails to install/update/remove when there is a reference with an Alias

### ISSUE THREAD

**Issue by timgaunt** [NuGet/Home#1580]
We recently came across a situation where we needed to alias a reference and ever since then, nuget won't install erroring in the Add-BindingRedirect call with “same key has already been added.”

There's a full stack trace/further information here: http://stackoverflow.com/questions/33110295/nuget-fails-to-install-update-or-remove-packages-same-key-has-already-been-add

To replicate, add two references to similar DLLs and alias one of them e.g.:

```
<Reference Include="Lucene303">
    <HintPath>..\_External Dependencies\Lucene303.dll</HintPath>
    <Aliases>UcommerceLucene</Aliases>
</Reference>
```

**Comment by yishaigalatzer** [comment]
What version of NuGet are you seeing this in? From you SO post, I assume it is 3.2? FYI we do have a 3.2.1-RC out on https://dist.nuget.org/index.html

What do you mean by similar dlls? Same name? Same version etc.

**Comment by yishaigalatzer** [comment]
@timgaunt I've been trying to get a repro, but couldn't quite get it. This is a real edge case where I don't want to spend half a day trying to get a repro, but would love to get a quick win if I have one.

Could you please share a project with a repro, and exact repro steps?

**Comment by yishaigalatzer** [comment]
ping, looks like we will have to move this out of 3.3.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
