### ISSUE TITLE
Error in Package Manager when packages folder gets out of sync

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#1581]
Here's the scenario:
- I have a multiple-project solution
- I installed some packages and some updates to one of the projects but not the others
- Stuff wasn't working
- I backed it out by resetting my entire repository to the last commit (which worked fine before)
- This (probably) left stale packages in my packages folder (since that's excluded from the repo)
- Opening the NuGet Package Manager dialog gave me this:

![2015-10-15_11h04_30](https://cloud.githubusercontent.com/assets/1020407/10518333/e82236d6-732e-11e5-8e5d-7bfcdc975a2e.png)

The error persisted until I totally deleted the packages folder from the solution and had NuGet refresh all the packages from scratch. Perhaps this behavior is by design? If so, I would suggest a better error message. If not, it should be possible to recover from a corrupted or invalid packages folder.

**Comment by yishaigalatzer** [comment]
@daveaglick I completely agree with you, we probably need a better repro, to figure out what was the core of the issue here.

Do you have a copy of the offending packages folder by any chance?

What version of NuGet did you use?

**Comment by daveaglick** [comment]
Happy to help any way I can. I'm on the latest 3.2.1-RC version of the Visual Studio extension. The solution this happened in is pretty complex with lots of projects. I've been trying to reproduce, but unfortunately I can't seem to get the right sequence of adding and removing packages to make it happen again. FWIW, I do know that I was playing around with the Roslyn Microsoft.CodeAnalysis.\* packages.

**Comment by yishaigalatzer** [comment]
Hey Dave. I'm keeping this open (but not assigned), will see if we can get a good repro next time you hit it.

We are working on a few issues we found with the roslyn solution, they might be related (but it is hard o tell).

I did fix a major bug where restore failures created corrupted packages, that could be the issue here. So the scenario is restore from command line and break, or something throws in the middle of expanding a package. The fix is in 3.3, but if the packages folder is corrupted, cleaning it is the way to go.

**Comment by daveaglick** [comment]
Great, thanks a lot. It may very well be related to the other things you've found with the Roslyn packages - I've noticed other seemingly random oddness (best way to describe it) while working with them. In any case, I'll pay close attention and grab the packages config file and folder if it happens again.

**Comment by yishaigalatzer** [comment]
Like I said we are fixing a bunch of issues that the Roslyn solution revealed. We should do a lot better in 3.3.

Closing for now, you can search our bug database as new things come up. Mostly we get detailed bugs from @davkean and @danliu on this matter (thanks to David!)
