### ISSUE TITLE
Update SymbolSource auto push URL

### ISSUE THREAD

**Issue by TripleEmcoder** [NuGet/Home#1583]
We've made the new SymbolSource engine live - see http://tripleemcoder.com/2015/10/04/moving-to-the-new-symbolsource-engine/ for more info.

Now would be a good time to update nuget.exe to push to https://nuget.smbsrc.net instead of the old URL. The old service redirects packages automatically, but that incurs a performance penalty that we'd all want to avoid.

I'd be happy to create a pull request, but I am not familiar with NuGet's branching to find the right place to start.

I've already crated a PR for docs with the same small change.

**Comment by yishaigalatzer** [comment]
Please don't create a PR for this, as we can't take new ones for a while (as we are locking down for 3.3 release), we can make it happen.

**Comment by TripleEmcoder** [comment]
Ok, great. Are there any 2.x maintenance releases planned that could also receive this?
