### ISSUE TITLE
Merge dnu restore features into NuGet's project.json restore

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#1588]
[Updated by @emgarten 2016-03-04]

We need to unify the logic in `dnu restore` and nuget's project.json restore so that they can be used interchangeably without issues. This issue is the uber issue to track that work:

We need this in nuget.exe for full .NET and nuget.exe xplat
## P0 (Dec 11)
- [X] - Make nuget xplat restore command work on xplat on coreclr - @davidfowl 
- [x] - Run a set of tests on the Linux/Mac CI - @emgarten 
- [x] - Packaging for the CLI (Create a nupkg and consume in the CLI project) - @anurse (in progress)
- [X] - Add `--no-cache` option to skip HTTP cache (at a minimum) - @emgarten (?)
- [x] - Consider changing `--verbosity` from a top-level switch to a common per-command switch `--quiet` to mirror dnu. Either way, switches before the command name are confusing to users and break the integration with `dotnet` (even though `dotnet` does actually have one of these... :P `--verbose`) - **I believe this was cut** (@emgarten)
- [x] - Libraries have to reference Microsoft.NETCore.Platforms. This seems wrong. We need to work that out - @yishaigalatzer @davidfowl @emgarten @anurse (?) **RIDs were not hard coded, adding the package is the correct way.** (@emgarten)
## P1
- [X] - Compute P2P for all csproj -> xproj (critical) - On Desktop with desktop msbuild - @pranavkm + @davidfowl  (Dec 11)
- [X] - Upgrade lock file format to version 2 (critical) - @emgarten (Dec 11)
- [X] - Put projects in `project.lock.json` (critical) - @emgarten 
- [X] - Change the restore command (in command line) to stop skipping DNX projects - @emgarten
- [X] - MsBuild API integration to xplat restore
- [X] - Support `{ target: "project/package" }` in `project.json` - @emgarten 
## P2
- [x] - Support passing multiple projects to restore (critical)
- [ ] - Run pre and post restore scripts in `project.json` if defined (critical)
- [x] - Print out dependency diagnostics after restore (we have a bunch of diagnostics that come out of a restore in the right format) *\* ( @yigalatz already tracked elsewhere ) **
- [X] - Resolve Solution level restore differences (different nuget.config per project)

/cc @anurse @yishaigalatzer

**Comment by analogrelay** [comment]
I've updated some of these, based on my info. Are any of the others done yet @emgarten @pranavkm @davidfowl @yishaigalatzer ?

**Comment by cesarblum** [comment]
> Run pre and post restore scripts in project.json if defined (critical)

Not having this at the moment prevents a proper migration of the Kestrel build to dotnet (see https://github.com/aspnet/KestrelHttpServer/blob/b4b5f07a080162ac905c944fe06346bd72342537/src/Microsoft.AspNet.Server.Kestrel/project.json#L59).

For I've put those scripts in `precompile`, but that's not ideal.

**Comment by dougbu** [comment]
Something has recently regressed w.r.t. `--quiet` support. With the current .NET CLI, our builds look like:

```
info: Exec
info:   program: dotnet
info:   commandline: restore --quiet
info:   workingdir: C:\dd\dnx\Universe\Antiforgery
log  : Restoring packages for C:\dd\dnx\Universe\Antiforgery\samples\AntiforgerySample\project.json...
log  : Restoring packages for C:\dd\dnx\Universe\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.Test\project.json...
log  : Restoring packages for C:\dd\dnx\Universe\Antiforgery\src\Microsoft.AspNetCore.Antiforgery\project.json...
log  : Restoring packages for C:\dd\dnx\Universe\Antiforgery\test\Microsoft.AspNetCore.Antiforgery.FunctionalTests\project.json...
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json.
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json 394ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json 415ms
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.dataprotection/index.json 424ms
info :   OK https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json 1018ms
info :   OK https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json 1044ms
info :   OK https://www.myget.org/F/aspnetcidev/api/v3/flatcontainer/microsoft.aspnetcore.dataprotection/index.json 1060ms
```

Not positive this is NuGet-specific since other `dotnet` commands look rather messy e.g.

```
info: Exec
info:   program: dotnet
info:   commandline: pack  src\Microsoft.AspNetCore.Antiforgery --configuration Debug
info:   workingdir: C:\dd\dnx\Universe\Antiforgery
Compiling ←[33mMicrosoft.AspNetCore.Antiforgery←[39m for ←[33m.NETPlatform,Version=v5.4←[39m

←[32mCompilation succeeded.←[39m
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.4819716


Compiling ←[33mMicrosoft.AspNetCore.Antiforgery←[39m for ←[33m.NETFramework,Version=v4.5.1←[39m

←[32mCompilation succeeded.←[39m
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:04.7295652
```

(At least the `dotnet restore` output was colourized correctly.)

**Comment by dougbu** [comment]
FYI I filed dotnet/cli#1274 about the other `dotnet` command output.

**Comment by dougbu** [comment]
Decided the `dotnet restore` regression described above is a separate issue. Filed #2069.

**Comment by yishaigalatzer** [comment]
@davidfowl can we break out what is left in this bug and still required. We are locking down 3.4 beta, and I want this one closed with whatever we have done already

**Comment by emgarten** [comment]
> Print out dependency diagnostics after restore (we have a bunch of diagnostics that come out of a restore in the right format)

@davidfowl what is needed for this? And does NuGet still need to run pre/post restore scripts?
