### ISSUE TITLE
Package Manager Console and nuget.exe UPDATE function are inconsistent

### ISSUE THREAD

**Issue by wilson0x4d** [NuGet/Home#1591]
When performing "Package-Update -Source FEEDB" from Package Manager Console we see that packages from sources _other than the specified source_ are pulled.

This is **undesirable behavior**.

When performing "nuget.exe update" from the command-line we see that packages from sources other than the specified source **are NOT pulled.**

This is **desired** behavior.

I realize backward compatibility is a concern, but I view this as a mistake and I'm surprised no Product Owner, Manager, nor any Engineers (Software/QA) noticed this inconsistency, and if they had, I'm surprised that the deviation between tools was allowed to occur. Thus, I'm concerned that, one day, someone will get The Wrong Idea(tm) and update nuget.exe (CLI tool) to behave as Package Manager Console behaves (such a change would break CI for a number of companies where I've seen nuget integrated into their process.)

Consider for a moment that when we are performing a package update from a private feed (we specified a -Source option for a private nuget server) and a dependency exists for a package from a feed OTHER THAN the one specified (such as a nuget.org or myget feed) it should result in an error when either..
1. The package is not already present in the packages folder (e.g. do not auto-restore/update), or..
2. The package version specified on the dependency is newer than the version present in the packages folder (e.g. do not auto-update).

However, if a package is available from the specified source(s) and the package does not demand a newer version of another package than what is already available on disk then the update should succeed (you could warn the user of anon-updated package b/c from other sources perhaps), and the update should not perform updates from unspecified sources in any event.

This is how the command-line tool behaves. It's how the Package Manager Console should behave but does not for some reason.

If you reference Issue #1181 you will see a report where users could not update at all because of packages outside of the specified source, and it helped highlight the fact that Package Manager Console and Command-Line NuGet.exe behave differently.

Does this make sense or do I need to clarify something?

Thanks.

**Comment by yishaigalatzer** [comment]
This makes sense, but there is a reason behind the current behavior in the powershell console, and in fact this is desired by many users. Perhaps the right answer is to have two different flags to control the behavior.

Example:
I have a private package depending on a public package. Specifying update-package from that source will try to pull in a new version of the package, but will fail because it requires a new public package version to work. Forcing the user to create a copy of the public package in the private feed is wrong.

So the design is pull top level packages only from the primary sources, but allow dependencies to come from other defined sources.

It is probably reasonable to add more control here to control secondary sources behavior.

CC @johnataylor

**Comment by wilson0x4d** [comment]
It would be desirable to be warned that a package from 'other source' was not updated, because it's from 'other source' (only when a compatible version is already available on disk.) Or, when not already on disk (e.g. requires a fetch) result in an error that a required package/dependency could not be satisfied.

If the end-user really wanted to update from all sources, he could specify the additional source, or alternatively your team could consider adding an additional parameter that would allow required dependencies to be pulled (again, when not already on disk and when semver is not already satisfied.) 

The basic premise for specifying -Source is to constrain the package updates to only those available from the specified sources.

This is how the command-line tool behaves, which unfortunately lacks the capability we require for Project Item and Reference (hintpath) management (which can only be achieved with PM Console presently, as it appropriately relies on EnvDTE.)

**Comment by wilson0x4d** [comment]
I will reiterate that nuget.exe (latest, 2.8.6) does not fetch from sources which were not specified by -Source parameter. It also does not error so long as dependencies are already satisfied.

**Comment by wilson0x4d** [comment]
I should also note that VS2013 Package Manager (not the console) exposes an "Update All" button that behaves in the way I've described (see Issue #1592 -- which describes a regression of behavior in VS2015 v. VS2013)

**Comment by johnataylor** [comment]
The behavior is that the package you are targeting is pulled from the source specified but the other enabled sources are considered for dependencies. We would want to keep this as the default behavior however we could consider some flags to control this.

We've recently fixed a couple of bugs around update-package when you have prerelease packages in the mix. This was a regression from 2013. See #1370. It would be good to know you are not hitting issues around that.

**Comment by yishaigalatzer** [comment]
We decided that we agree with the general problem statement, and believe we want to come up with a way to control the behavior. We are not convinced we want to change the existing behavior, but we definitely want to come up with something better.

Since this is not going to fit in 3.3, we are putting aside the decision on what the behavior will be and the detailed design for this until we get to execute on it.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
