### ISSUE TITLE
VS2015 Package Manager does not have "Restore All" function as seen in VS2013 or prior

### ISSUE THREAD

**Issue by wilson0x4d** [NuGet/Home#1592]
In VS2013 it is possible to use the Package Manager (not the Console, the full UI) to perform an update of all packages from a specific source, and ONLY from that source.

This was accomplished by selecting the target Source on the left-side of the package manager in the "Update" group. Once the UI finished updating package states an "Update All" button would appear. Clicking the button updated all packages for the selected source.

VS2015's version of Package Manager does not provide this functionality.

Combined with the bug identified in Issue #1181 there's no good way to perform such an update (as Package Manager Console attempts to interrogate sources OTHER THAN sources specified in the -Source parameter, when/if provided.)

The standing work-around is to retain a VS2013 license so that we can perform this function. We would like to perform this function from within VS2015, since swapping to VS2013 is an interruption (and with our own VSIX production, is not an option, as the project conversions are one-way. As are likely several other specialized project types.)

I've verified in 3.2.0.10516 (latest available at this time).

**Comment by yishaigalatzer** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/1504. We are actually going not only to bring back the behavior but improve it (so you can multi select packages and update a subset)
