### ISSUE TITLE
VersionRange.Parse ends up with weird Minor version string

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#1598]
![image](https://cloud.githubusercontent.com/assets/95136/10559099/a6548f3c-749c-11e5-8f2b-ab4da0f4040a.png)

``` C#
var range = VersionRange.Parse("1.0.0-*");
var formatted = range.MinVersion.ToString();
```

formatted prints "1.0.0---"

/cc @emgarten

**Comment by emgarten** [comment]
That's the lowest possible inclusive 1.0.0 pre-release version since an empty release label would mean it is stable. Alternatively the highest exclusive min version is 0.MaxInt.MaxInt.

**Comment by davidfowl** [comment]
Nah this is wrong. If you look at the break down this is what it looks like:

Major = 1
Minor = 0
Patch = 0
Release = "-"

Why is the relese portion "-", it's supposed to be empty

**Comment by emgarten** [comment]
If release were empty it would be 1.0.0 (stable). Of the characters allowed in a semantic version release label hyphen is the lowest, so this is the lowest possible release label that can be inclusive for the range >= 1.0.0-*

**Comment by emgarten** [comment]
Also, an empty release label would be an invalid semantic version. We could take a look at allowing it to solve this problem however.

**Comment by emgarten** [comment]
From SemVer.org:

> Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty.

**Comment by davidfowl** [comment]
Ok I'm still convinced this is broken

**Comment by davidfowl** [comment]
@emgarten Remember I'm just talking about the min version part of the overall version. The min version part is `1.0.0`, the overall version is `1.0.0-*`

**Comment by emgarten** [comment]
1.0.0-beta would not satisfy  >= 1.0.0, the range needs the actual minimum possible pre-release version for 1.0.0.

**Comment by emgarten** [comment]
We can make VersionRange understand this and return a min version of 1.0.0, the MinVersion property just couldn't be used by itself as the actual minimum.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@1cd4679a
