### ISSUE TITLE
NuGet.PackageManagement: install package stopped at resolved actions and not proceeding

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#161]
1. create a new web application
2. install mvcscaffolding package

Expected: works fine

Actual: previewInstallAsyc call did not return any project actions to execute, so install package stopped prematurely.

**Comment by yishaigalatzer** [comment]
This package does not work on VS14, please use the -2013 version of the package. Or use another package altogether.

**Comment by danliu** [comment]
Looks like it's the package issue itself. The package needs to be updated to work on VS14.
