### ISSUE TITLE
Can't upgrade or uninstall Microsoft.Net.Compilers

### ISSUE THREAD

**Issue by mike-barnett** [NuGet/Home#1610]
We had found a bug in the Roslyn compiler and so once there was a fix, we added a NuGet reference to Microsoft.Net.Compilers using https://www.myget.org/F/roslyn-nightly/ as the package source. This worked, but now a few weeks later I went to build my solution and got errors on the NuGet package restore. I was unable to update or even uninstall the package because apparently it had been deleted from the package source. I've had to go into the .csproj file and manually edit them to replace the version numbers. Maybe this is because it adds the package references in a special way from the other NuGet references in the .csproj file? Here are the lines that I have to update in the .csproj file:

```
  <Import Project="..\..\packages\Microsoft.Net.Compilers.1.1.0-beta1-20150916-08\build\Microsoft.Net.Compilers.props" Condition="Exists('..\..\packages\Microsoft.Net.Compilers.1.1.0-beta1-20150916-08\build\Microsoft.Net.Compilers.props')" />
```

And:

```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
<PropertyGroup>
  <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
</PropertyGroup>
<Error Condition="!Exists('..\..\packages\Microsoft.Net.Compilers.1.1.0-beta1-20150916-08\build\Microsoft.Net.Compilers.props')" Text="$([System.String]::Format('$(ErrorText)', '..\..\packages\Microsoft.Net.Compilers.1.1.0-beta1-20150916-08\build\Microsoft.Net.Compilers.props'))" />
```

  </Target>

**Comment by yishaigalatzer** [comment]
This is by design, there is no way to know what references to remove or targets to remove without the package being around. So although you can force the uninstall, you will have to manually remove the package.

**Comment by yishaigalatzer** [comment]
By the way with project.json based projects, this is not an issue anymore because nuget doesn't touch your project.

**Comment by mike-barnett** [comment]
As far as I know, the package was still there on my disk. I mean, I can see the folder in the packages directory. How should I convert an existing project to be "project.json based" (whatever that means)?

**Comment by yishaigalatzer** [comment]
Can you validate that? If the package was there on disk update and uninstall should work just fine. Do you have the latest version of nuget (3.2 is the RTM, 3.2.1 is the RC)?

**Comment by mike-barnett** [comment]
Yes, the package is still on my disk. How can I tell which version of nuget I have?

**Comment by yishaigalatzer** [comment]
Worked with @mike-barnett in person. Looks like he was using NuGet 3.0, we update to 3.2 and will keep an eye if this issue re-appears.
