### ISSUE TITLE
RemoteV2FindPackageByIdResource ignores unlisted packages

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1612]
RemoteV2FindPackageByIdResource ignores unlisted packages.
Test TestPacManBuildIntegratedInstallPackageWithInitPS1 fails due to this issue and must be re-enabled

Repro steps:
1. Clean the global packages folder and the v3-cache.
2. Install NuGet.Core -version 2.8.3 to project.json from https://www.nuget.org/api/v2
3. Check the project.lock.json file

Expected:
project.lock.json contains an entry for Microsoft.Web.Xdt.2.1.0, since NuGet.Core.2.8.3 depends on Microsoft.Web.Xdt, version >= 2.1.0.

Actual:
project.lock.json contains an entry for Microsoft.Web.Xdt.2.1.1

**Comment by emgarten** [comment]
The V3 resource uses flat container which does not filter out unlisted packages, V2 should return everything also.

**Comment by deepakaravindr** [comment]
Priority?
