### ISSUE TITLE
Automatically update package references when project location has been changed

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1613]
_From @frodegil on October 20, 2015 6:52_

I have a folder structure for my solution where I group related projects in sub-folers located in the folder where my solution file is.
I recently added a new project and forgot to place it in the correct sub-folder. Instead the project folder became a new sub-folder under my solution-file folder. Packages were already added from NuGet.
I removed the project from the solution, moved the project-folder to the correct project-sub-folder and added the project back to my solution. NuGet reported that packages were installed correctly, but the references showed a yellow warning. I opened the project-file and found that my NuGet packages were missing "..\" in the path to the packages folder for the actual project.
Is it possible, somehow, for NuGet to detect that project-folders has moved up/down the solution-folder tree and auto-correct the relative path to the packages folder? It would be nice.

_Copied from original issue: NuGet/NuGetGallery#2738_

**Comment by emgarten** [comment]
We are unable to detect this, but it can be fixed with Update-Package <id> -reinstall

**Comment by frodegil** [comment]
I wasn't aware of Update-Package -reinstall. Thanks!
I promise I'll start to read the manual :)
