### ISSUE TITLE
Transforming files (.pp) depending on project type. 

### ISSUE THREAD

**Issue by petterek** [NuGet/Home#1614]
Using the .pp extension source code is transformed and inserted into the project. 

But i can't find a way to insert different 'templates' according to the current project type. 

So if i want to offer my package to both c# and vb projects I have to provide both .vb.pp and .cs.pp files.
But only one of them should be imported to the project.

**Comment by emgarten** [comment]
There is no way to do this currently, but we're working on this feature along with support for it in msbuild!
Check out https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json
