### ISSUE TITLE
Bad update in VS2013  broke all VS instances of NuGet

### ISSUE THREAD

**Issue by shepard1166** [NuGet/Home#1615]
Attempted to update NuGet from VS 2013 Extension&Update UI... Update failed... unable to uninstall NuGet, Unable to re-install visx. Broken in all instances of VS (2013 Ultimate, 2015 Enterprise). See attached files. 
![nuget_unavailable](https://cloud.githubusercontent.com/assets/1486129/10612899/7998ed8e-7718-11e5-8872-3fab7954e450.PNG)

![vsixinstallfail](https://cloud.githubusercontent.com/assets/1486129/10612900/799a00c0-7718-11e5-8176-333297b78d79.PNG)

![logimage](https://cloud.githubusercontent.com/assets/1486129/10612988/d921e292-7718-11e5-8dfe-63c3822fb6ed.PNG)

**Comment by emgarten** [comment]
From the log it looks the files are in use. Try closing everything, then download the NuGet vsix from dist.nuget.org/index.html and double click it to install the vsix with Visual Studio closed.

**Comment by shepard1166** [comment]
It is installed, but it is not functioning properly... i attempted to repair both instances of VS and to re-install NuGet through boxstarter... which seems to have fixed it partially (the nuget options now appear in the VS menu). . However, when I select the NuGet options from the VS menus (i.e. Manage NuGet Packages etc...) nothing happens. 

Your solution gets the same results...
![image](https://cloud.githubusercontent.com/assets/1486129/10635458/8bfaf8d6-77be-11e5-9bf3-a0193a1913c6.png)

![image](https://cloud.githubusercontent.com/assets/1486129/10635501/d12fa3f2-77be-11e5-8b91-5d7d95d00450.png)

**Comment by yishaigalatzer** [comment]
Can you try install nuget 2.9 from https://dist.nuget.org/index.html

**Comment by yishaigalatzer** [comment]
ping

**Comment by shepard1166** [comment]
Apologies....reinstall v2.9 with boxstarter seems to have done the trick

**Comment by yishaigalatzer** [comment]
Thanks for getting back to us!
