### ISSUE TITLE
Investigate 3 functional test failures for project K

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#1616]
ProjectKUpdateAllPackages

ProjectKUpdatePackage

ProjectKUpdatePackageNoUpdateAvailable

There are timing issues with the tests, which could be either product or test issues.

**Comment by danliu** [comment]
One more test is ProjectKInstallDNXCore

**Comment by danliu** [comment]
Since the tests works fine locally, there are timing issues with checking the project.json references on the test machine. Please work with Anton to see if there is a solution for this.

**Comment by emgarten** [comment]
ProjectK is gone.
