### ISSUE TITLE
Package Manager Console cannot determine startup project when a solution has multiple startup projects.

### ISSUE THREAD

**Issue by RoarkeRandall** [NuGet/Home#1618]
Steps to reproduce bug:
1. Open a solution with 2 or more valid startup projects.
2. Right click the solution and select properties.
3. Select the "Multiple startup projects" radio button, and set at least 2 of the valid startup projects to "Start".
4. Run a command in the Package Manager Console, like "Add-Migration".

Outcome: 
Package Manager Console will print "Cannot determine a valid start-up project. Using project 'DefaultProjectName' instead. Your configuration file and working directory may not be set as expected. Use the -StartUpProjectName parameter to set one explicitly. Use the -Verbose switch for more information." 

Expected Outcome: 
Package Manager Console should choose one of the projects that is set as startup project, rather than choosing the "Default project". 

I know that there is the -StartUpProjectName parameter, but this solution seems intuitive and easy to implement.

**Comment by emgarten** [comment]
What version of Visual Studio and NuGet are you using?

**Comment by RoarkeRandall** [comment]
Sorry, Visual studio 2015 Update 5, Nuget version 2.8.60610.756

**Comment by emgarten** [comment]
This doesn't appear to be a NuGet issue, the start up project name parameter comes from EntityFramework.psm1 for Add-Migration

See: http://entityframework.codeplex.com/SourceControl/latest#src/NuGet/EntityFramework/tools/EntityFramework.psm1 

//cc @rowanmiller

**Comment by rowanmiller** [comment]
I don't think would arbitrarily choose one of the projects. If we did do something we would probably just error out and instruct you to use the startupProject parameter to identify which project to use.
