### ISSUE TITLE
Command line restore spits a wrong message about enabling restore in visual studio

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1619]
run nuget.exe restore or nuget.exe install

Expected 
Messages are relevant to command line

Actual
A message about enabling package restore in visual studio shows up

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
