### ISSUE TITLE
NuGet.PackageManagement.UI: The action dropdown text should be Upgrade instead of Update

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#162]
![update](https://cloud.githubusercontent.com/assets/1087852/6490135/ea990dfe-c258-11e4-8374-8a4b5858139f.png)

Select "Upgrade available" filter, click the dropdown for Action

It should be Uninstall and Upgrade, not update

**Comment by yishaigalatzer** [comment]
@feiling was is upgrade not always true?

**Comment by RanjiniM** [comment]
New UI doesn't need this.
