### ISSUE TITLE
NuGet.Client build fails at finding NuGet.MsBuild.Integration

### ISSUE THREAD

**Issue by logankp** [NuGet/Home#1621]
When building the NuGet.Client repo, build.ps1 fails at finding packages\NuGet.MsBuildIntegration because the package downloads as NuGet.MsBuild.Integration.3.1.0-beta-001. build\common.targets should be changed to use NuGet.MsBuild.Integration.3.1.0-beta-001. I can submit a PR for this if necessary.

**Comment by yishaigalatzer** [comment]
That sounds weird, because I regularly build with a cleancache, and clean packages folder and I don't see this issue?

Can you try Build.ps1 -CleanCache?

Do you have all the pre-requisites installed?

ASP.NET Beta7 (must be Beta7, we don't work with Beta8 yet)
Win 10 tools
Vs SDK

**Comment by logankp** [comment]
I have all of the above installed. Building with -CleanCache does seem to resolve this error, but now I'm getting the following:  `The type or namespace name 'Shell' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?` and a warning `Could not r
esolve this reference. Could not locate the assembly "Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0`. I have the VS SDK installed, and I've verified that the Microsoft.VisaulStudio.Shell assembly exists.

Thanks for your help!

**Comment by yishaigalatzer** [comment]
Can you build the nuget.clients.sln in visual studio and tell us what project is broken?

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
Oh wait. I have vs2013 on my box as well. That could be the difference?

Sent from my Windows Phone

**Comment by logankp** [comment]
It looks like the VIsualStudio14 project isn't building because the Microsoft.VisualStudio.Shell.14.0, Microsoft.VisualStudio.Shell.Interop, and Microsoft.VisualStudio.Threading references aren't in the .csproj (although they are in the project.json file).

The VisualStudio.Interop project has the same problem with the MS.VS.OLE.Interop and MS.VS.Shell references.

I'm also getting warnings about PackageManagement.PowerShellCmdlets because multiple versions of the VS SDk assemblies are being references in the .csproj.

**Comment by yishaigalatzer** [comment]
Looks like you are missing the windows 10 tools

Sent from my Windows Phone

**Comment by logankp** [comment]
Ah-ha, I see. I misunderstood that and installed the Windows 10 SDK. Now I see there's the Windows Universal tools in VS that I need to install. I'll see if that works tomorrow!

**Comment by logankp** [comment]
Alright, that fixed it. Thanks for your patience and help!
