### ISSUE TITLE
Nuget sometimes installs a package but does not properly place it in the output folder

### ISSUE THREAD

**Issue by zjrunner** [NuGet/Home#1622]
v3.2.1
using fileshares as a packagesource
Sometimes we get a folder with only [Content_Types].xml in it -- no other package contents.  I know there is a separate issue to stop dropping this one file at all, but it isn't clear why other files aren't expanded.

In earlier nuget releases we would see nothing show up in folders, a success return code from nuget, and in the logs a Task Cancelled Exception (or aborted, or similar).  We hadn't seen this since going to 3.2.1 until now and this looks very similar to that old problem but without any log messages.

We are pulling two versions of newtonsoft but both claimed to be successful:
[Inf] 2015/10/14:01:09:53.031 : Restoring NuGet package Newtonsoft.Json.6.0.8.
[Inf] 2015/10/14:01:09:53.203 : Adding package 'Newtonsoft.Json.6.0.8' to folder 'd:\dbs\CxCache'
[Inf] 2015/10/14:01:09:53.375 : Added package 'Newtonsoft.Json.6.0.8' to folder 'd:\dbs\CxCache'
[Inf] 2015/10/14:01:09:53.516 : Restoring NuGet package Newtonsoft.Json.6.0.1.
[Inf] 2015/10/14:01:09:53.672 : Adding package 'Newtonsoft.Json.6.0.1' to folder 'd:\dbs\CxCache'
[Inf] 2015/10/14:01:09:54.578 : Added package 'Newtonsoft.Json.6.0.1' to folder 'd:\dbs\CxCache'

Newtonsoft.json.6.0.1 is complete.  In case there could be a race contention in the \tmp folder, it is worth noting the timestamp on [Content Types].xml is 1s earlier for 6.0.8

(nuget 3.2.1)
nuget.exe restore d:\dbs\el\clbd.corext\gen\packages.config -PackagesDirectory d:\dbs\CxCache -PackageSaveMode nupkg -Verbosity detailed <8 sources, 6 of them shares>

In this case, some of the shares are old format (flat list of nupkg files) and the share with the newtonsoft packages was new format (\newtonsoft.json\version{nupkg,sha512,nuspec}).  Tried a few manual runs and couldn't get it to happen again locally.

**Comment by yishaigalatzer** [comment]
Can you share the packages.config file?

**Comment by yishaigalatzer** [comment]
Note that starting with 3.2.1, we will consider these failed restores, and another restore will overwrite them (because the SHA file is dropped last). 

You can always move up to 3.3 bits available on myget / nugetbuild feed in the nuget.commandline  package to get our latest bits from the CI.

**Comment by zjrunner** [comment]
sorry, it is difficult to get at the packages.config because we autogenerate and then delete it.  I can get you the log to see the scope of what we installed, but it was probably 20-30 packages, some of them pretty large.

Overwriting with future restores is good, but the active build post-restore might be hard to read.  It might be good to do that validation check post restore and to fail there and not just pre-restore to re-populate.  I'd also love to see a more verbose option from nuget -- a Diagnostic level maybe -- where you can just spew out all the logging you might have available and we can do better forensics and open better workitems next time.

**Comment by MeniZalzman** [comment]
Following our conversion we are closing the issue for now until we will get a clear repro steps or detailed log, also Zack trying to collect the hit count of this issue
