### ISSUE TITLE
Need to move guardrails out of restore

### ISSUE THREAD

**Issue by Petermarcu** [NuGet/Home#1623]
@davidfowl has the context but in general, we want to let the install happen and let the compile fail with a good error in the command line case and enable good checks and experiences in VS around understanding the tradeoffs for platforms support you are making when you use an API.

**Comment by yishaigalatzer** [comment]
@Petermarcu yes, we discussed it yesterday. But we need to synchoronize. Is this fix from your side going into Update I or later?

**Comment by Petermarcu** [comment]
I'm assuming later. We definitely need to coordinate how to land this together.

**Comment by emgarten** [comment]
Guardrails are off by default for PackageReference projects since 4.0.0.
