### ISSUE TITLE
NuGet.exe restore (solution) fails with MSBuild protection level error

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1631]
nuget Version: 3.2.0.10488

```
> nuget restore <solutiondir>
```

> Error parsing solution file at C:\git\microbuild\src\MicroBuild.sln: 'Microsoft.Build.Construction.ProjectInSolution.ProjectType' is inaccessible due to its protection level

**Comment by AArnott** [comment]
This repro'd on both solutions that I tried on. Since the two solutions are completely unrelated, I suspect this build of nuget.exe may simply be broken.

**Comment by yishaigalatzer** [comment]
That's not a recent build or a public one. Closing

**Comment by AArnott** [comment]
Sorry. I didn't realize I had any non-public builds on my machine.

**Comment by mrchief** [comment]
@yishaigalatzer  I'm having the same issue with v3.3.0

```
Target RestorePackages:
    "D:\Workspace\master\20151201025221\tools\NuGet\NuGet.exe" update -self
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 2.8.6.
    Updating NuGet.exe to 3.3.0.
    Update successful.
    "D:\Workspace\master\20151201025221\tools\NuGet\NuGet.exe" restore "D:\Workspace\master\20151201025221\src\All.sln"
    MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
    Error parsing solution file at D:\Workspace\master\20151201025221\src\All.sln: 'Microsoft.Build.Construction.ProjectInSolution.ProjectType' is inaccessible due to its protection level
    D:\Workspace\master\20151201025221\build.proj(68,3): error MSB3073: The command ""D:\Workspace\master\20151201025221\tools\NuGet\NuGet.exe" restore "D:\Workspace\master\20151201025221\src\All.sln"" exited with code 1.
```

**Comment by yishaigalatzer** [comment]
@mrchief would you mind sharing a repro?

@feiling

**Comment by mrchief** [comment]
Not sure how to go about it - its a private project for a client. Let me see if I can upload a redacted version.

 Do you think just the solution file will be good enough or do you need the whole setup?

**Comment by yishaigalatzer** [comment]
@mrchief if that repros the problem, go ahead and share it

**Comment by feiling** [comment]
The problem doesn't seem to have anything to do with the particular sln file. @mrchief Can you run msbuild to get the msbuild version number you're using?

**Comment by mrchief** [comment]
I'm not using the command line tool rather `Microsoft.Build.dll` and related assemblies to fire off the build. The DLL version is 14.0.22310.1

**Comment by feiling** [comment]
This is an older version of msbuild (probably Microsoft Build Tools 2015 RC). Could you update it? We verified that nuget.exe works correctly with msbuild 14.0.24720.0.

**Comment by mrchief** [comment]
Using latest DLLs and targets works! :+1:

**Comment by yishaigalatzer** [comment]
Thanks!

**Comment by Eneuman** [comment]
I am still getting this error when doing VSO Builds.
Is it because the Tools on the Hosted Build Agents are outdated ?

**Comment by JakeGinnivan** [comment]
I just had this issue, I fixed it by removing a solution platform (had Any CPU and x86)

**Comment by JakeGinnivan** [comment]
Actually, it wasn't this exact error. It was a AggregateException not a decent error message

**Comment by yishaigalatzer** [comment]
Can you share the call stack?
