### ISSUE TITLE
Shopping Cart/Ability to pin packages in search, and install them in one go

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1632]
This is a preliminary idea allowing installation of packages from the UI as a batch, potentially saving time and conflicts.

The flow is
Search
Find a package
Pin it

It show up either on the top of the search list as pinned, or in a cart. You can then install, update, or delete it in one go.

**Comment by yishaigalatzer** [comment]
CC // @ljw1004

**Comment by emgarten** [comment]
I don't believe this applies to PackageReference, installs should be much faster and do not hang the UI like packages.config did.
