### ISSUE TITLE
Running nuget.exe update -Verbosity Quiet does not display user prompts but expects an answer anyway

### ISSUE THREAD

**Issue by dee-see** [NuGet/Home#1639]
I'm using the NuGet 3.2.1-rc command-line tool.

When there is a file conflict during a package update, we are normally prompted with

```
File 'X' already exists in project 'Y'. Do you want to overwrite it?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All ?
```

When using the `-Verbosity Quiet` switch, the text above is not shown, but the update process freezes until the user inputs an answer to the hidden question.

I'd like the prompt to be shown even in `Quiet` mode, or maybe assume `-NonInteractive`...

**Comment by yishaigalatzer** [comment]
Thanks for this report, we should show the prompt regardless of verbosity (although quiet is really pushing it).

We should not assume NotInteracive

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
