### ISSUE TITLE
NuGet.PackageManagement: Functional test failure. UninstallPackageHonorPackageReferencesAccordingToProjectFramework

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#164]
NuGet.PackageManagement: Functional test failure. UninstallPackageHonorPackageReferencesAccordingToProjectFramework

More information

The test verifies that, when 2 packages have references of the same name, and they are both installed on a project; uninstalling the second package does not remove the reference. In NuGet V2 client, this test passed. In NuGet V3 client, this test fails, and so, the test has been commented out

Note that the first package has "lib\net40\one.dll" and second package has "lib\one.dll"

**Comment by rrelyea** [comment]
This is still commented out in:
nuget.client\test\EndToEnd\tests\uninstall.ps1

**Comment by jainaashish** [comment]
I couldn't find this test in latest source code. So assuming this test has already been moved.
