### ISSUE TITLE
Add support for including/excluding package folders to nuspec defined dependencies

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1644]
Add an additional property to nuspec dependencies to allow packages to define which folders are included from a nupkg.

**Comment by yishaigalatzer** [comment]
We also want to be able to include all content, and include/exclude at a package level.

Please post the spec here and in the design document

**Comment by emgarten** [comment]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets
