### ISSUE TITLE
-ConfigFile is not setting custom config on install command

### ISSUE THREAD

**Issue by ronybarbosa** [NuGet/Home#1646]
Hi Guys,

I have a project located on my D: Driver. I am trying to set up a custom NuGet.config for my develop enviroment.

My project is located on "D:\company\project\Service". I am placing my nuget config in this folder and naming it as "Nuget.local.config" containing the following configuration:

```
<?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
      <clear />
        <add key="NugetLocalRepository" value="D:\company\project\NugetLocalRepository" />
        <add key="nuget.org" value="https://nuget.org/api/v2/" />
      </packageSources>
     <disabledPackageSources>
        <add key="nuget.org" value="true" />
      </disabledPackageSources>
      <activePackageSource>
        <add key="All" value="(Aggregate source)" />
      </activePackageSource>
    </configuration>
```

and I try to install my packages running the follow command:

```
nuget install "D:\company\project\Service\packages.config"  -ConfigFile D:\company\project\Service\NuGet.local.config -NonInteractive -RequireConsent -solutionDir "D:\company\project\Service" 
```

But it didn work.

It only works when I rename NuGet.local.config file to  "NuGet.config"

p.s: When I run the install command using "NuGet.local.config", nuget is always creating a default NuGet.config file on %appdata%/Roaming/Nuget

What I want is set up different configurations for different build profiles.

I am using NuGet 2.8.6 (I am having the same problem with the latest version)

**Comment by yishaigalatzer** [comment]
As a workaround, can you place the nuget.config in a subfolder that represents your configuration

e.g.

```
Build1\nuget.config
Build2\nuget.config
...

```

And then call 

```
nuget install "D:\company\project\Service\packages.config"  -ConfigFile D:\company\project\Service\Build1\NuGet.config -NonInteractive -RequireConsent -solutionDir "D:\company\project\Service" 
```

**Comment by ronybarbosa** [comment]
It also didn't work .

I suppose these folders don't follow the folder hierarchy. That one described on the documentation.

**Comment by emgarten** [comment]
I am not able to repro this in nuget.exe 4.3.0. Please let me know if you are still seeing this issue.
