### ISSUE TITLE
NullReferenceException in NuGet.PackageManagement.VisualStudio.AssemblyBinding.Parse

### ISSUE THREAD

**Issue by oocx** [NuGet/Home#1649]
I accidentially deleted the "version" attribute of a  codeBase Element in one of the app.config files in my solution. This caused install-package (invoked in the package manager console) to fail for all projects in my solution without giving me a meaningful error message. I had to attach a debugger to Visual Studio to find the cause of the problem.

Expected behavior:
NuGet should not crash when parsing incomplete application configurations (missing elements, missing attributes, ...). Instead, it should provide me with a meaningful error message that I can act upon (example: "The element 'codeBase' is missing the required attribute 'version' in 'path-to\my\app.config', line 42")

I'm using NuGet 3.2.0.10516 with Visual Studio 2015.

**Comment by yishaigalatzer** [comment]
@oocx I just fixed a very similar bug.

Going forward (3.3+)
1. We are not going to fail if binding redirect failed, and we are just going to write a warning (this is configurable)
2. We are going to spit out an error telling you what file didn't follow the scheme.
3. Binding redirects are now optional

I don't think we have a meaningful error message for this particular case, so this is still worth verifying an fixing.

Given that we are locking down 3.3, this will probably make it into a future release.

**Comment by yishaigalatzer** [comment]
@oocx we will also gladly take a pull request if you already spent the time digging into the code

**Comment by oocx** [comment]
Thanks for the fast response!

**Comment by yishaigalatzer** [comment]
It irked me enough to fix it before going to sleep :)
