### ISSUE TITLE
Nuget restore needs to support batch restoring for larger projects

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#1653]
Today for the corefx repo we do a batch restore of all the project.json files in the entire repo (>800) up front to try and reduce the build time costs of doing that for every individual project. We need to support this type of scenario with nuget restore.

See https://github.com/aspnet/dnx/issues/2771 and https://github.com/aspnet/dnx/commit/0dda8bf86863364cc20421f1af7494f1b2a3256f#commit for some discussion about the current support in dnu and how it impacts larger projects.

**Comment by davkean** [comment]
Roslyn is bigger that CoreFX right now, and we have one giant Roslyn solution pulling in every project. With this change here: https://github.com/NuGet/Home/issues/1586, this works pretty decently.

**Comment by yishaigalatzer** [comment]
Clarification: This issue tracks the ask from nuget.exe to support this. NuGet.xplat.commandline already supports traversing a root folder

**Comment by emgarten** [comment]
Restore performance has been improved in 4.4.0.
