### ISSUE TITLE
UI: Better UserSettings saving and loading

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1654]
UserSettings are saved and loaded into .suo using BinaryFormatter. This means if there's any change to the user settings, and existing existing won't get read. We need a better way to load & save settings such that 
- old settings can be read by new code.
- new settings can be read by old code: a setting that cannot be recognized is ignored by will not be overwritten when saving.

**Comment by mishra14** [comment]
Closing due to lack of customer traction.
