### ISSUE TITLE
VS command "Enable NuGet Package Restore" reverts to pre-2.7 approach (NuGet.targets, etc.)

### ISSUE THREAD

**Issue by bobmeyers5** [NuGet/Home#1658]
I just manually migrated a solution and its packages to the new 2.7+ approach to package restore, referred to as Automatic Package Restore. This was working great, but then as I was testing things out, I clicked this menu item on the Solution context menu, and it undid just about everything I had done.

Not cool...

**Comment by yishaigalatzer** [comment]
What version of visual studio are you using? This was fixed in NuGet 3+ as far as I know

**Comment by bobmeyers5** [comment]
Microsoft Visual Studio Ultimate 2013Version 12.0.40629.00 Update 5
NuGet Package Manager   2.8.60723.765

Date: Wed, 28 Oct 2015 20:19:41 -0700

**Comment by yishaigalatzer** [comment]
@bmeyers43 we completely agree, and we removed this option in Visual Studio 2015 - NuGet 3.X
