### ISSUE TITLE
NuGet package source installation

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1659]
_From @dajuric on October 28, 2015 23:39_

The provided package I created (I cannot upload the nupkg file here):
http://expirebox.com/download/059a5d4acd4c0f92ada91212c2f7b1f1.html

installs fine when used in .NET 4.x.
However, when added to DotNet5 project, it is added as an dependency, the source file is not copied and the readme file is not shown. 

![project](https://cloud.githubusercontent.com/assets/4395047/10806424/75c11ba0-7dd5-11e5-8e3f-2f76cf0b5296.jpg)

_Copied from original issue: NuGet/NuGetGallery#2756_

**Comment by dajuric** [comment]
Can I have some explanation on what has been done regarding the issue ??

**Comment by yishaigalatzer** [comment]
That is by design currently. ASP.NET 5 does not support either of these actions.

In NuGet 3.3 we plan to re-introduce a new immutable content model. And readme.txt will show up again for none asp.NET 5 projects (that's an explicit choice that project system made).

**Comment by dajuric** [comment]
Thank you.
And then will it be possible to install package as source file(s) ?
When NuGet 3.3 is going to become active ?
