### ISSUE TITLE
Shared dependency group ignored

### ISSUE THREAD

**Issue by MoonStorm** [NuGet/Home#1661]
Please have a look at https://www.nuget.org/packages/Dapper.FastCrud/2.1.0 

As you can see it's got a dependency for all the frameworks to `Dapper`, with some special treatment for .NET 4.5.

It properly reflects the definition of the dependencies in the nuspec file.

```
    <dependencies>
      <group>
        <dependency id="Dapper" version="1.38" />
      </group>
      <group targetFramework="net45">
        <dependency id="StringInterpolationBridge" version="0.9.1"/>
      </group>
      <group targetFramework="net46">
      </group>
    </dependencies>
```

However, when you try to install it in VS2015 when the project is targeting .NET 4.5 for example, the shared `Dapper` dependency is not getting picked up.

**Comment by emgarten** [comment]
NuGet selects the nearest group and uses it. It only picks one. You shoud add Dapper to both the net45 and net46 groups and remove the empty framework group.

**Comment by MoonStorm** [comment]
@emgarten That doesn't make any sense. 

I've also seen this example in the docs:

https://docs.nuget.org/create/nuspec-reference#specifying-dependencies-in-version-2.0-and-above

```
<dependencies> 
   <group>
      <dependency id="RouteMagic" version="1.1.0" />
   </group>

   <group targetFramework="net40">
      <dependency id="jQuery" />
      <dependency id="WebActivator" />
   </group>

   <group targetFramework="sl30">
   </group>
</dependencies>
```

When is RouteMagic gonna get installed? Don't say ONLY in versions below .NET 4.0 or Silverlight 3.0 because it makes no sense. That section is the common dependency section. The Dapper dependency in my case is even listed under "All Frameworks" on [nuget.org](https://www.nuget.org/packages/Dapper.FastCrud/2.1.0). 
This is clearly a bug.

**Comment by emgarten** [comment]
RouteMagic will not be installed for sl30 since that has a group. RouteMagic would be installed for native, win8, net35, and all other frameworks since it is in the fallback group.

From the doc: 

> All dependencies **inside a group** are installed together if the target framework is compatible with the project's framework profile.

**Comment by MoonStorm** [comment]
I get the reasoning behind this decision. In any case, can someone please update the docs to avoid the confusion, by adding the fact that the group with no target is actually considered to be a "fallback group". 

Also, someone has to change the report for the packages that use that group in nuget.org, because it's wrongfully saying that those dependencies are for " **all frameworks**". 

Thanks Justin.

**Comment by yishaigalatzer** [comment]
Logged an issue for nuget.org

The doc actually says exactly that - 

| Attribute | Description |
| --- | --- |
| targetFramework | **Optional**. The target framework of the group. If not set, the group acts as a **fallback** group, which behaves exactly as before version 2.0 |

**Comment by MoonStorm** [comment]
Silly me. I missed that in the docs sorry.
