### ISSUE TITLE
Show infobar with links to open readme files when installing packages

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/Home#1662]
https://github.com/NuGet/Home/issues/1307 - relevant bug.

Currently we open the readme file, if one exists, after installing the package. Instead look into showing an infobar that gives user the control whether to open the readme file or not.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
