### ISSUE TITLE
Empty dropdown for 'Update' is shown in Package Manager Dialog and leads to NullReferenceException 

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/Home#1664]
1. Configure an UNC with one version of a package as Package Source. For example my share has only elmah, 1.2.2
2. Install the package into a project
3. Now an empty dropdown with 'Update' button enabled is shown
4. Click on 'Update'

Nullreference exception is thrown

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet.Client/pull/85

**Comment by feiling** [comment]
Fix checked in.
