### ISSUE TITLE
Proposal: Visual Studio Extension should allow for upgrading all project/solution packages in one shot

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#1665]
For the NuGet Package Manager interface, it would be nice to have an **"Upgrade all"** button to immediately update all of a project/solution's updatable packages in one shot and to have an additional **filter drop down list**, similar to the following sketch, for easily getting an overview on whether updates for installed packages are available:

```
---------------------------------
|▼| Show installed packages with:
      no upgrade available
      upgrade available
      all
---------------------------------
```

That would ease upgrading a fresh project template to the latest version in one single shot and ease getting an educated overview on the installed packages.

**Comment by csharpfritz** [comment]
Already addressed with upcoming UI changes in v3.3  Please read our blogpost at: http://blog.nuget.org/20151014/nuget-userinterface.html for details of the coming UI changes including the Installed / Update Available tabs as well as the Update All feature.
