### ISSUE TITLE
Prerelease Setting Should be Set Per Package Source

### ISSUE THREAD

**Issue by johnkoerner** [NuGet/Home#1666]
Currently the "Include Prerelease" setting in the package manager UI affects all packages sources.  I work in an environment where I use multiple package sources and would like some sources to default to prerelease, while others to default to stable.

We have internal nuget repositories where I want to be on the bleeding edge to get all latest updates, but from the official nuget.org package source, I want stable releases. When I switch between package sources, the prerelease setting sticks. In the past I have unknowingly installed prerelease packages from nuget.org, which caused downstream problems.

**Comment by yishaigalatzer** [comment]
That's a cool idea. We have some ideas around building a proxy with policy, and that would enable building a lot more elaborate control around that kind of scenario.

For example you want to take certain packages only from a private feed (though they exist on nuget.org you might have hijaacked them, or there might be a name collision between two feeds).

Making the change in the resolver/nuget proper is a lot more complicated than this type of proxy (that could be in the box with VS).

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
