### ISSUE TITLE
NuGet.VisualStudioExtension VS 2015 - Show installed projects when select a package

### ISSUE THREAD

**Issue by toannguyen83** [NuGet/Home#1668]
https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d  <- refering to nuget visual studio 2015 extension.

In the old nuget visual studio extenstion vs 2013, when you select an installed package, you get a nice little text at the bottom right panel telling you which projects having the package installed.
![image](https://cloud.githubusercontent.com/assets/2815878/10866425/5c78f1a8-7ffc-11e5-8528-0cde90fe6ec7.png)

In the new nuget visual studio extension vs 2015, it's no longer showing that text when you select an installed package. In order for me to see that list, I have to select the package, then select "Uninstall" action so that it can list the projects I have installed in order to uninstall. My intention though was not to uninstall, just for at a glance to see what projects out there having the selected package installed.

Is there anyway to add it back? It's just some text but very useful for us when managing 20+ projects in a solution.

**Comment by yishaigalatzer** [comment]
This is supported in 3.3

![image](https://cloud.githubusercontent.com/assets/1238711/10892796/3f82e996-815a-11e5-9cfa-4612d11989eb.png)
