### ISSUE TITLE
On a UAP project, installing by typing wrong casing for package id fails from a folder based package source

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1672]
On a UAP project, installing by typing wrong casing for package id fails from a folder based package source

Repro steps:
1. Create a C# UAP application
2. Create a folder with say a package, called, jQueryShared
3. Add the folder created above as a source
4. Install-Package <b>jqueryShared</b> (from the source added in Step-3)

Expected:
It installs successfully even the

Actual:
It fails with the following error. Notice how, in the same snapshot, using the correct id casing and trying again installed the package fine.

![image](https://cloud.githubusercontent.com/assets/2380340/10893677/f1851b88-815e-11e5-95bf-88a3dab11c77.png)

**Comment by yishaigalatzer** [comment]
Verified this works now - NuGet 3.3

**Comment by yishaigalatzer** [comment]
This repros when you clear the cache. The command also ignores that -source parameter, and grabs packages from other sources/cache as well.

**Comment by matthid** [comment]
A similar thing happens when you create a filesystem based package source from windows (-> lower case names are used) and later try to restore on linux.

I noticed this when adding alpha packages directly to the repository and later try to restore and build on linux (a dotnetcore application).

**Comment by yishaigalatzer** [comment]
The feature to handle path casing across the board is being worked on and will be available in 3.6
