### ISSUE TITLE
Install NuGet package programatically

### ISSUE THREAD

**Issue by MtMovo** [NuGet/Home#1675]
Wondering if such scenario would be possible:
I have an app which would let user to install plugins during runtime. Those plugins are NuGet packages. So i would need to:
1) Display a list of available packages
2) Download selected packages and resolve dependencies

Is there an API for this kind of operations in NuGet 3.x?

**Comment by daveaglick** [comment]
I'm using the following libraries to programmatically consume the 2.x feed:
NuGet.Core
NuGet.Frameworks
NuGet.Versioning
NuGet.Packaging

Not sure about the 3.0 feed (they might work, I just haven't tested personally).

Unfortunately, there isn't much documentation for these libraries. Here's an old blog post: http://blog.nuget.org/20130520/Play-with-packages.html. I've also got code here that programatically consumes packages (may not be the same as your situation, but something to go on): https://github.com/Wyamio/Wyam/tree/develop/Wyam.Core/NuGet

**Comment by MtMovo** [comment]
Thanks @daveaglick.
Will investigate more and if nothing comes up use Your approach.

**Comment by rrelyea** [comment]
appears closable
