### ISSUE TITLE
NuGet chooses first asset that matches TFM, even if a more specific RID is available

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1676]
If I have a package with

```
runtimes/any/lib/netcore50/System.Xml.XmlSerializer.dll
runtimes/aot/lib/netcore50/_._
```

And resolve for `.NETCore,Version=v5.0/win10-x64-aot` NuGet is selecting the `any` asset, even though `aot` is a more specific RID.

If I debug the code it seems that the bug is here:
https://github.com/NuGet/NuGet3/blob/a5bc907d36ddaa8d4fa6c499e50d7ebf8993ed39/src/NuGet.Client/ManagedCodeConventions.cs#L158

If all three framework names are the same this should return 0, instead it returns -1.

This should be changed as follows:

```
                bool criteriaEqual = criteriaFrameworkName.Equals(nearest);
                bool availableEqual = availableFrameworkName.Equals(nearest);

                if (criteriaEqual && availableEqual)
                {
                    return 0;
                }

                if (criteriaEqual)
                {
                    return -1;
                }

                if (availableEqual)
                {
                    return 1;
                }
```

/cc @davidfowl @anurse @emgarten @yishaigalatzer

**Comment by emgarten** [comment]
@ericstj have you verified that fix solves the issue?

**Comment by ericstj** [comment]
Only in the debugger.  I am trying to contribute and test case the fix but having issues building Nuget.Client repo.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@321a906d57e64b21f818d62ab50b1635c5d795f5
