### ISSUE TITLE
Erroneous warning with analyzers in package

### ISSUE THREAD

**Issue by rockfordlhotka** [NuGet/Home#1677]
I have a package that includes (among other things) a VS analyzer. When I build the package NuGet gives me a warning about the analyzer, even though it is actually valid and works great.

<img width="1068" alt="snip_20151103142958" src="https://cloud.githubusercontent.com/assets/2333134/10923753/895acda8-8237-11e5-8cac-f09f6bc26d76.png">

This comes from this NuSpec file:
https://github.com/MarimerLLC/csla/blob/master/NuGet/Definition/Core.NuSpec

This is on Windows 10 RTM with NuGet 3.2.0.10516.

**Comment by emgarten** [comment]
NuGet/NuGet2@0226d4469c12076affd56431e69dfdeff1557744

**Comment by emgarten** [comment]
NuGet/NuGet.Client@94061d2408b6c0add1f92ae26cfea88c42f23e15
