### ISSUE TITLE
Request: integrated into VS "Add Reference" dialog

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#1679]
Currently, I use RightClick > AddReference to add many kinds of reference (framework DLLs, extension SDKs, P2P, shared projects, COM type libraries, WinRT platforms, raw DLL files).

But to add a NuGet reference I have to do it via RightClick > ManageNuGetPackages.

Please consider putting the "NuGet reference" page _inside_ the AddReference dialog.

(Incidentally, when my brain wants to add a new nuget package, my brain's first instinct is to look for the word "add" -- not the word "manage"...)

**Comment by yishaigalatzer** [comment]
We should consider this once we merge the asp.net 5 tooling

CC @pilchie @davidfowl

**Comment by davidfowl** [comment]
We looked at this a while ago and it just doesn't fit. There are too many other facets to nuget packages and the add reference ui is too simplistic. The most we would do is make it another entry point

**Comment by emgarten** [comment]
Marking as won't fix based on the comments above.
