### ISSUE TITLE
NuGet doesn't re-restore after adding or modifying the runtimes section in project.json

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1680]
1. Create a new UWP project, and build the project.
2. Open your project.json, and delete the line for the active RID (probably win10-x86).
3. Hit build.

_Expected:_ the build fails, since I removed the RID. 
_Actual:_ it succeeds. If you keep pressing regular build the restore doesn't run. Once you do a rebuild, the restore is forced and then the build fails.

This is on an internal VSIX build of 3.3.0.145.

**Comment by emgarten** [comment]
NuGet checks the project.json file last modified timestamp now, this will catch any changes such as removing RIDs.

NuGet/NuGet.Client@f48718971aec219393268901a4d863f9b855c757
