### ISSUE TITLE
UI: we should use the same text for the install/update button

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1683]
Currently, the text on the button is 
- In project package manager, if the package is already installed, it's "Update". If it's not installed, it's "Install".
- In solution package manager, the text is always "Install". 

It's better to be consistent and always use the same text on the button. My preference is to use "Install".

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
