### ISSUE TITLE
Surface NuGet package updates in Solution Explorer

### ISSUE THREAD

**Issue by robrich** [NuGet/Home#1684]
It's hard to discover NuGet package updates in Visual Studio. I must open the Manage Nuget Packages dialog to see the updates. Consider surfacing when NuGet package updates are available in the Solution Explorer, prompting me to open the NuGet window.

**Comment by augustoproiete** [comment]
+1

**Comment by yishaigalatzer** [comment]
We should do this when we merge asp.net 5 tooling into nuget.

CC @davidfowl @pilchie

**Comment by anangaur** [comment]
VS Mac has it. We need a similar functionality:
![image](https://user-images.githubusercontent.com/14800916/64999680-8ab39200-d89d-11e9-8930-3170c8873ad7.png)

**Comment by nkolev92** [comment]
Duping to https://github.com/NuGet/Home/issues/3292 since it has a significant account more upvotes
