### ISSUE TITLE
Issues with error messages when 'contentFiles' section of nuspec is invalid

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1686]
Issues with error messages when 'contentFiles' section of nuspec is invalid are as follows
1. If copyToOutput or flatten attribute is invalid, we get the following error message: <i>Index (zero based) must be greater than or equal to zero and less than the size of the argument list.</i>
2. When 'include' attribute is not present, we get the following message. It would be better to say that 'include' attribute is mandatory and is missing : <i>The nuspec contains an invalid entry '<files buildAction="EmbeddedResource" xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd" />' in package 'b.1.0.0' .</i>

**Comment by toddm** [comment]
These were both fixed when I tested them.  They throw InvalidOperationExceptions with nice messages explaining that the copyToOutput attribute is invalid or that the required attribute include is missing, as appropriate.

**Comment by emgarten** [comment]
Verified in 3.5.0-beta
