### ISSUE TITLE
On UAP project, Installing from a folder package source without the version fails

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1687]
On UAP project, Installing from a folder package source without the version fails

Repro steps:
1. Create a folder with packages.Say, there is a package A.1.0.0.nupkg in the folder, then
2. Install-Package A

Expected:
NuGet picks up the latest version of A, which is A.1.0.0.nupkg. If the exact version is specified, it works properly

Actual:
<i> An error occurred while retrieving package metadata for 'A' from source 'C:\temp\content-packages'.</i>

**Comment by yishaigalatzer** [comment]
This does not repro.
