### ISSUE TITLE
Pack support for csproj + project.json

### ISSUE THREAD

**Issue by mteper** [NuGet/Home#1689]
I am having no luck building a NuGet package for IntacctClient (see https://github.com/el-loco/IntacctClient)

Here's build output:

```
nuget pack "C:\projects\intacctclient\IntacctClient.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -OutputDirectory "C:\Users\appveyor\AppData\Local\Temp\1\v0q0xxfwxi"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from 'IntacctClient.csproj'.
Packing files from 'C:\projects\intacctclient\bin\Release'.
WARNING: Unable to extract metadata from 'IntacctClient.dll'.
Using 'IntacctClient.nuspec' for metadata.
Value cannot be null or an empty string.
Parameter name: profileValue
Command exited with code 1
```

**Comment by mteper** [comment]
This appears similar to #1267.

**Comment by emgarten** [comment]
It is the same as 1267, nuget.exe pack does not support project.json projects. You will need to pack using a nuspec.

**Comment by mteper** [comment]
OK, that worked. Is there an issue I can follow for adding support for building from .csproj?

**Comment by yishaigalatzer** [comment]
This will be the feature tracking it (renaming)

**Comment by gregjhogan** [comment]
When I have project.json and MyProject.nuspec, I expected the dependencies to be picked up out of the project.json file.  That does not seem to be the case.

I am running
`nuget pack MyProject.csproj -Properties Configuration=release -IncludeReferencedProjects`

Example with no `<dependencies></dependencies>` specified

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
    <releaseNotes>$releaseNotes$</releaseNotes>
  </metadata>
</package>
```

Before I had a project.json this magically picked up all my nuget package dependencies (I guess out of packages.config)

**Comment by emgarten** [comment]
@gregjhogan project.json is not being used at all by pack today. Project.json can contain all of the same metadata as the nuspec file so there may not be a nuspec + project.json pack scenario in the future.

**Comment by gregjhogan** [comment]
@emgarten when you said 

> there may not be a nuspec + project.json pack scenario in the future

did you really mean csproj + project.json?

**Comment by toddm** [comment]
Pushed to Dev
