### ISSUE TITLE
GetProjectsReferencingProjectJsonFiles.target does not support ProjectName.project.json

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1690]
nuget.exe does not support projectname.project.json

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/GetProjectsReferencingProjectJsonFiles.target#L9

The target here should only find the list of child projects, everything else should be done in the nuget.exe code.

**Comment by yishaigalatzer** [comment]
CC @pranavkm

**Comment by feiling** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/107
