### ISSUE TITLE
Support new TFMs for the .NET Platform Standard

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#1691]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

dotnet5.1 -> netstandard1.0
dotnet5.2 -> netstandard1.1
dotnet5.3 -> netstandard1.2
dotnet5.4 -> netstandard1.3
dotnet5.5 -> netstandard1.4

Long Name:

.NET Standard

**Comment by ericstj** [comment]
we also have:
dotnet5.6 -> netstandard1.5
as of https://github.com/NuGet/NuGet.Client/commit/a15e8ff0c6de85eb8da995672ce4bb1751fc141d

**Comment by joelverhagen** [comment]
Complete with NuGet/NuGet.Client#189.
