### ISSUE TITLE
Update-Package -Safe -IncludePrerelease updates to a package with different minor

### ISSUE THREAD

**Issue by endrih** [NuGet/Home#1693]
From the Package Manager Console of Visual Studio 2013 Update 5, if you run the command 
Update-Package -Safe -IncludePrerelease
And one of your projects has a dependency on a pre-release package, then it might get updated to a prerelease package of the next minor version.
For example 1.0.0-CI123 will get updated to 1.1.0-CI234. 

Temporary fix: Restrict with allowedVersions in the packages.config [1.0.0-CI, 1.1.0-a)

**Comment by endrih** [comment]
I forgot to mention that the same thing happens with Nuget.exe 2.8.60717.93 .
The command I ran is:
nuget.exe update my.sln -safe -pre

**Comment by yishaigalatzer** [comment]
We plan to deal with it in Visual Studio 2015, but don't plan to update 2013 to fix this. We plan an overhaul cleanup for Update-Package in NuGet 3.4
