### ISSUE TITLE
When packing a nuget package, folders starting with dot are ignored

### ISSUE THREAD

**Issue by endrih** [NuGet/Home#1694]
When trying to put a folder that starts with a dot '.' in the folder name, the folder does not get picked up by nuget.exe and no error or warning messages are displayed. 
For example 

```
<file src="Contracts\.NETFramework\v4.0*." target="tools\Contracts\.NETFramework\v4.0\" /> 
```

This line does not put anything in the tools\Contracts folder inside the package. Neither does 

```
<file src="Contracts\*.*" target="tools\Contracts\" /> 
```

Workaround: 
Apparently it works if you do it like this: 

```
<file src="Contracts\*NETFramework\v4.0*.*" target="tools\Contracts\.NETFramework\v4.0\" /> 
```

So instead of the dot at the beginning of the file name, put a star '*'.

Nuget version is: 2.8.60717.93

**Comment by yishaigalatzer** [comment]
folders starting with . are ignored by default.

However your samples don't show anything that look like a folder starting with a dot, would you mind clarifying and provide the actual files on disk?

**Comment by endrih** [comment]
I am sorry. It must have been a typo in the original submission.
I modified it now. There was a "\" before between Contracts and .NetFramework, which I had to re-add. So the contents of what I am trying to add to the package is: Contracts\.NETFramework\v4.0*

**Comment by yishaigalatzer** [comment]
This is by design - See https://github.com/NuGet/Home/issues/1338
And documented here: https://github.com/NuGet/NuGetDocs/blob/master/NuGet.Docs/Create/Creating-and-Publishing-a-Package.md
