### ISSUE TITLE
Version interpretation problem with nuget

### ISSUE THREAD

**Issue by williambernardet** [NuGet/Home#1695]
Pack let you create packages where the version could be interpreted equally during restore operation:

> nuget pack component.nuspec -Version 1700.0000
> will generate component.1700.0000.nupkg
> 
> nuget pack component.nuspec -Version 1700.000
> will generate component.1700.000.nupkg
> ...
> nuget pack component.nuspec -Version 1700.0
> will generate component.1700.0.nupkg

When you want to retrieve 1700.0000 with the following project.json:
{"dependencies":{"component":"1700.0000"},"frameworks":{"any":{}}}
You end up extracting 1700.0. And in my package directory I can see it as 1700.0.0 (yet an another inconsistency).

I understand that both version are interpreted as 1700.0.0. So to avoid any ambiguity pack command should either prevent you you to create such package (input version is not matching the interpreted one), or generate the package using the interpreted version (component.1700.0.0.nupkg).

**Comment by emgarten** [comment]
For project.json the version folder name is normalized according to [SemVer](http://semver.org) to make it predictable.

Changing the output from pack would break backwards compatibility for scripts expecting the non-normalized file name. The best thing to do here is to always pass in a normalized version when creating a nupkg.
