### ISSUE TITLE
NullReferenceException when launching NuGet on PCL

### ISSUE THREAD

**Issue by AmadeusW** [NuGet/Home#1697]
To reproduce, get a PCL project that targets
- .NET Framework 4.0
- Silverlight 5
- Windows 8
- Windows Phone 8.1
- Windows Phone Silverlight 8

For example, [OpenWeatherMap](https://github.com/joancaron/OpenWeatherMap-Api-Net)

And turn it into "modern" PCL:
Remove **packages.config** (required by changing targets)
Change project's targets to
- .NET Framework 4.5
- ASP.NET Core 5.0
- Windows 8

Attempt to launch NuGet for this project. A NullReferenceException occurs.
It persists after closing and restarting Visual Studio and reverting changes (packages.config now exists). Happens only in that solution. I will restart the computer and update

![img](https://i.gyazo.com/0adc41a07058c238e71ebb61abb742c8.gif)

**Comment by davidfowl** [comment]
Is your nuget up to date?

**Comment by AmadeusW** [comment]
I think so, it's v3.2.60914.10516

**Comment by emgarten** [comment]
There have been a lot of fixes in this area. Try the 3.2.1-rc version of VSIX from http://dist.nuget.org/index.html and let us know if that resolves the issue for you.

**Comment by AmadeusW** [comment]
Thanks, the 3.2.1-rc version of VSIX fixed NuGet in this solution: Now NuGet window opens for other projects, and opens for the target project when I revert the changes.

After converting the project to "modern" PCL, however, I keep getting the same exception. Here are the exact changes that cause NuGet to fail:
1. Remove **packages.config** (NuGet still works, and correctly shows that there are no packages installed for this project)
2. Convert the project to "modern" PCL
   - This creates empty **project.json**
   - [Diff of the **.csproj** file](https://gist.github.com/AmadeusW/4e943a0052a397eb0918)

Removing project.json doesn't fix the issue or saving all.

However, after I restarted, **project.json** was populated and the [.csproj file changed again](https://gist.github.com/AmadeusW/aa22d21e776afb2f27c8). This time NuGet works. I will keep exploring this.

It looks like there is a temporary (until Visual Studio exits?) issue where the .csproj file is invalid and breaks NuGet

**Comment by emgarten** [comment]
It sounds like NuGet may not be reloading the project fully after the change from packages.config -> project.json if restarting Visual Studio helps. You could also close and re-open the solution to have the same effect.

**Comment by yishaigalatzer** [comment]
Yes - We do not support reloading the projects on such changes. We should fix it at some point, but this is not a high pri scenario.

However converting the project should not create an empty project.json, can you explain the exact steps of what converting means?

CC @pilchie

**Comment by yishaigalatzer** [comment]
We tracked the generation of empty project.json to the pcl project system and that team will fix it (note that code is not oss). In 3.3 we will detect the issue and provide you with a proper error message pointing to the bad project.json
