### ISSUE TITLE
Improve p2p resolution for project.json restore 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1700]
NuGet needs to handle both DNX style folder based resolution and CSProj references. Today the implementation does not contain a switch which puts the project resolver into one mode or the other which can lead to msbuild based projects resolving a package using a folder via global.json when it shouldn't.

Since DNU and NuGet will merge both styles need to be supported.

**Comment by yishaigalatzer** [comment]
CC @davidfowl

**Comment by emgarten** [comment]
NuGet/NuGet.Client@f5a4c758a7d0fe28ef576236f4de36c342e6603b
