### ISSUE TITLE
Improve library type handling

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1701]
There have been a lot of bugs around how different types of libraries are compared during restore. For example if a framework reference has the same name as a package the two can end up being compared even though they are not the same type.

To fully solve these issues beyond day to day fixes the code base should be reviewed to find places where this is a problem and the handling improved.

Examples a few examples of library types:
External project
Solution project
Package
Framework reference

**Comment by yishaigalatzer** [comment]
@davidfowl is this something you can take over as part of the merge?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@f5a4c758a7d0fe28ef576236f4de36c342e6603b
