### ISSUE TITLE
When NuGet UI re-opens Visual Studio, it opens incorrect solution

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1702]
From vs-feedback (492831):

When nuget has to restart visual studio (using IVsShell4.Restart) it sometimes opens a different solution than the one I was actually using.

Reproduction steps

1: Open a solution (solution 1) in Visual Studio

2: Open another solution (solution 2) in another Visual Studio instance

3: Close the second instance (or keep it open, I don't think it makes a difference)

4: Update packages via nuget in a manner that requires a restart (packages under source control seems to to trigger it).

5: Click restart

6: Visual Studio opens solution 2.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
