### ISSUE TITLE
Add clearcache support for visual studio UI

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1704]
Ala Visual Studio 2013 (perhaps without the browse button), also show the list of all cache folders somehow

![image](https://cloud.githubusercontent.com/assets/1238711/11048474/f28b4bcc-86ec-11e5-97c9-4682a257dca6.png)

**Comment by csharpfritz** [comment]
It might make sense to add this, along with the previously requested
'Refresh' button to the top right side of the UI near the sources
combobox.  In this way, the user will be able to quickly see the changes to
the packages list.

This also leads to the side thought: we could show in the package detail
pane when that data was last loaded, which should also be the write date of
the package content in the cache.

**Comment by yishaigalatzer** [comment]
Note: the `Refresh` button was added in 3.4.0

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/3289
