### ISSUE TITLE
packages.config Package restore should detect some basic corruption scenarios

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1705]
Packages folder that only have the .nupkg file in it (can happen from a botched TFS checkin), skip restoring the package and leads to failures customer have a hard time recovering from.

We should consider this basic scenario, and force restore on top of the nupkg.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
