### ISSUE TITLE
No warning is logged when the directory with the packages.config contains more than 1 project file

### ISSUE THREAD

**Issue by samholder** [NuGet/Home#1706]
this is an issue in nuget 2.*, I'm not sure if its an issue in nuget3 as we are not using it. I couldn't see where to log the issue in the nuget2 repo, so apologies if this is not the right place. Please point me in the right direction if its not right.

I'm logging this in the hope of being able to submit a PR to fix it soon.

Anyway, in the function:

``` c#
        private static IMSBuildProjectSystem GetMSBuildProjectSystem(string packageReferenceFilePath)
        {
            // Try to locate the project file associated with this packages.config file
            var directory = Path.GetDirectoryName(packageReferenceFilePath);
            var projectFiles = ProjectHelper.GetProjectFiles(directory).Take(2).ToArray();

            if (projectFiles.Length == 0)
            {
                throw new CommandLineException(LocalizedResourceManager.GetString("UnableToLocateProjectFile"), packageReferenceFilePath);
            }

            if (projectFiles.Length > 1)
            {
                throw new CommandLineException(LocalizedResourceManager.GetString("MultipleProjectFilesFound"), packageReferenceFilePath);
            }

            return new MSBuildProjectSystem(projectFiles[0]);
        }
```

in the [UpdateCommand](https://github.com/NuGet/NuGet2/blob/861741bd780225a542c73a1d0904dd33b33a7a3d/src/CommandLine/Commands/UpdateCommand.cs)

nothing is logged if anything other than 1 project file is found in the same directory as the packages.config file. An exception is thrown but this is just caught and supressed by the calling function which means that the system just ignores that packages.config file for updates and the user is left wondering why the project was not returned in the list of projects in the solution.

When detailed logging is enabled I think that something should be logged so that users can more easily debug this issue.

**Comment by yishaigalatzer** [comment]
We don't plan to reship versions of nuget 2.*.

versions of 3.\* are available on dist.nuget.org/index.html, if this still repros we should fix it, and will gladly take a PR.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
