### ISSUE TITLE
Valid Nuget Packages Fail to Install on Visual Studio 2015

### ISSUE THREAD

**Issue by Xamtastic** [NuGet/Home#1707]
It would seem that this bug (now closed) has reared it's head again: https://github.com/NuGet/Home/issues/1172

The problem is concerning Nuget Packages being rejected by Visual Studio 2015, and yet installing  properly on Visual Studio 2013.

The bug was first reported, and then clarified, on the Xamarin forum as follows: https://forums.xamarin.com/discussion/55518/valid-nuget-packages-fail-to-install-on-visual-studio-2015?new=1

In particular, there are two images there showing the same bug before upgrading to the latest version of the Package Manager, and afterwards.

The bug is also easily reproducible, with the process at the bottom of this report.

The salient error detail is as follows (post upgrade), which considering it installs in Visual Studio 2013, and yet not on Visual Studio 2015, would seem to be erroneous:

Install-Package : Could not install package 'Microsoft.AspNet.WebApi.Client 5.2.3'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package Donky.Core
- ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Install 
    PackageCommand

I belong to the company which is the Package Author, and as a test I built a separate Nuget Package that instead of installing version 5.2.3 of Microsoft.AspNet.WebApi.Client, required that version 5.1.0 was installed instead: this installed on Visual Studio 2015!

i.e. I changed the following line in the nuspec file:
&lt;dependency id="Microsoft.AspNet.WebApi.Client" version="5.2.3" /&gt;
to
&lt;dependency id="Microsoft.AspNet.WebApi.Client" version="[5.1.0,5.1.1)" /&gt;

We don't, however, want to publicly reissue the Nuget Package with a version 5.1.0 dependency instead of a version 5.2.3 dependency, as the problem is not a Nuget package problem, but a tooling problem.

The bug itself is easily reproducible, just create a new Xamarin Forms PCL solution on both of Visual Studio 2013 and 2015 and run the following command in the Package Manager console, against the Android project:

PM> Install-Package Donky.Core

The Visual Studio 2013 one should successfully install, and the Visual Studio 2015 will not successfully install.

We ran this test on two different MacBook workstations with Visual Studio 2013 and 2015 installed in different VM mechanisms, both in Windows 10, but with the same result.

Every assistance will be appreciated!

Kind regards.

**Comment by emgarten** [comment]
This is similar to 1172 in that the TxM _wp_ exists twice, but unlike 1172 it is not the same version.

Microsoft.AspNet.WebApi.Client 5.2.3 contains `lib\net45+win8+wpa81+wp8+wp81` 

`lib\net45+win8+wpa81+wp8` is equivalent to Profile 259 which is supported by Xamarin.

NuGet could de-duplicate the profile down to this by recognizing that wp81 is irrelevant here since wp8 exists. Or the package could author this folder name correctly.

**Comment by Xamtastic** [comment]
Thanks emgarten, that adds some definition to the problem.

Presumably when Universal Windows Apps (Windows 10) get more traction, some of these profiles with windows duplicity will start to become rarer - before which this bug needs to be fixed simply because this behaviour shouldn't happen.

**Comment by JohnMcAvinue** [comment]
Any ideas when this will be fixed?

**Comment by Yortw** [comment]
Hi,

I think I am having this exact problem, but with different packages. I cannot install Microsoft.Bcl.Async in a Xamarin Android or iOS project using VS2015 and the version of nuget that ships with that, however it works perfectly from VS2013. This also true when trying to install other packages that use Microsoft.Bcl.Aync as a dependency (i.e my own package, RSSDP, fails to install because bcl.async won't install)... but again, only in VS2015, in VS2013 it works fine.

The error is "You are trying to install this package into a project that targets 'MonoAndroid,Version=vx.x', but the package does not contain any assembly references or content files that are compatible with that framework" but that seems incorrect since VS2013 will install the same package into an Android project targeting the same Android version.

**Comment by emgarten** [comment]
> VS2015 and the version of nuget that ships with that

@Yortw get the latest version of NuGet from the extension gallery or by installing Visual Studio Update 1, and then see if you are still hitting the issue.

**Comment by Yortw** [comment]
Already have update 1 (and did a repair of it last week for a different reason), and VS extensions and updates doesn't show any updates for nuget. I'll try a manual dowload from the gallery and see if that helps, thanks.

**Comment by Yortw** [comment]
Tried downloading from https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d but the installer says "This extension is already installed to all applicable products".

**Comment by emgarten** [comment]
@Yortw what version of BCL and what kind of project are you installing into?

**Comment by Yortw** [comment]
Hmm, might be my fault. Just realised it's trying to install and old copy of Microsoft.Bcl.Build (1.0.14 instead of 1.0.21 which I _think_ works). My package doesn't directly list that as a dependency (maybe it should?) but it does list the Microsoft HTTP libraries as a dependency, and that seems to list 1.0.14 as the minimum version required. I guess I should update my package to explicitly list .21.

Is only a problem for Xamarin.iOS and Xamarin.Android projects as far as I can tell, works for everything else I'd tried.

**Comment by Yortw** [comment]
@emgarten Seems it works fine if I manually declare the later version as a direct dependency of my package, so I'll do that. Thanks for your help.

**Comment by emgarten** [comment]
@Yortw looks like they fixed the BCL package then, thanks for reporting back.

**Comment by mrward** [comment]
With NuGet 3.4.2 the error still occurs trying to install Microsoft.AspNet.WebApi.Client into an Xamarin Android project. Should the duplicate target frameworks be handled in NuGet 3.4.2 or does the NuGet package need to updated?

```
Package Manager Console Host Version 3.4.2.830

Type 'get-help NuGet' to see all available NuGet commands.

PM> install-package Microsoft.AspNet.WebApi.Client
Attempting to gather dependency information for package 'Microsoft.AspNet.WebApi.Client.5.2.3' with respect to project 'AndroidTest', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'Microsoft.AspNet.WebApi.Client.5.2.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.AspNet.WebApi.Client.5.2.3'
Resolved actions to install package 'Microsoft.AspNet.WebApi.Client.5.2.3'
  GET https://www.nuget.org/api/v2/package/Microsoft.AspNet.WebApi.Client/5.2.3
  OK https://www.nuget.org/api/v2/package/Microsoft.AspNet.WebApi.Client/5.2.3 1985ms
Installing Microsoft.AspNet.WebApi.Client 5.2.3.
Install failed. Rolling back...
Package 'Microsoft.AspNet.WebApi.Client.5.2.3' does not exist in project 'AndroidTest'
Package 'Microsoft.AspNet.WebApi.Client.5.2.3' does not exist in folder 'C:\Projects\Tests\AndroidTest\packages'
install-package : Could not install package 'Microsoft.AspNet.WebApi.Client 5.2.3'. You are trying to install this package into a 
project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that 
are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package Microsoft.AspNet.WebApi.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by yishaigalatzer** [comment]
We are saying that this is a package issue, there was no fix for this. I'll forward to the MVC team to update the package

**Comment by TimHaydnJones** [comment]
I have the same issue with Renci SSH.NET and have reported it on https://sshnet.codeplex.com (waiting to hear back)
Any suggestions from this side?

For adding package 'SSH.NET.2013.4.7' to project 'TaskyAndroid' that targets 'monoandroid6'.
Install failed. Rolling back...
Package 'SSH.NET 2013.4.7' does not exist in project 'TaskyAndroid'
Package 'SSH.NET 2013.4.7' does not exist in folder 'C:\Users\Tim\Downloads\Tasky\packages'
Could not install package 'SSH.NET 2013.4.7'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
========== Finished ==========

**Comment by EugeneChua91** [comment]
till of today, there isn't any solution / fix on this yet? i understand this issue is been exist for more than half a year to be exact, perhaps there're other solutions / workarounds that anyone would like to share / recommend? in dire need for a solution here =(

**Comment by TimHaydnJones** [comment]
EugeneChua91 

Take a look at this
https://blog.xamarin.com/net-standard-library-support-for-xamarin/

I managed to get SSH.NET to install OK by including a Portable Class Library in my Xamarin Android Project. It seems to act as a conduit to installing the Nuget package properly.

**Comment by EugeneChua91** [comment]
TimHaydnJones,

Thanks for fast response, but i'm actually referring to "microsoft.aspnet.webapi.client", which i actually installed that NuGet without any issue, but the moment i ran the code (using PostAsJsonAsync), i got "System.Web Exeption", which i supposed is due to WepAPI Client 2.2's issue. Sigh =(

**Comment by yishaigalatzer** [comment]
On individual package support you should reach out to the respective owners (link is on the package page in nuget.org)

**Comment by EugeneChua91** [comment]
yisha,

Thanks for that, I already left a message to the owner on such issue already.

**Comment by ismailsameer12** [comment]
Hi All,
i have tried to install  system.net.mail from nuget package but could not be installed in my vs2015.
whats problem?
