### ISSUE TITLE
Content delivered by nupkg should not get picked up by Roslyn Analyzers

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1708]
Discussion from MVP Summit:  Source files or content transformed that was delivered by a package will get picked up by Roslyn Analyzers and will increase the noise in a project.
- @BillWagner

**Comment by emgarten** [comment]
The analysis happens on the project system side. Today analyzers are picked up directly from the nupkg folder and aren't even going through the lock file or nuget yet.

On the nuget side we could potentially add a feature that allowed for an analyzer ignore list to be written into the lock file.

**Comment by yishaigalatzer** [comment]
Filed a related bug on https://github.com/dotnet/roslyn/issues/6736
