### ISSUE TITLE
packages.config Package restore/update should detect some basic corruption scenarios, part 2

### ISSUE THREAD

**Issue by OsirisTerje** [NuGet/Home#1712]
If a developer adds a direct file reference to a packaged reference, but adds it from the output folder - something which is very easy to do, if you don't know the file is part of a package, the nuget update doesn't manage to either warn or correct package.config nor the reference.

Given an update of a beta package (1.0.3-beta4) to a stable version (1.0.3), using the package manager console :  update-package  MasterFlt   

  The package has 2 dependencies.
According to the log, all is being updated correctly:
Package 'Geometry.1.0.7' already exists in folder 'C:\tfskb\Nemo\Baseline\DeploymentTool.nuget....\packages'
Added package 'Geometry.1.0.7' to 'packages.config'
Successfully installed 'Geometry 1.0.7' to CommonTestFiles
Package 'morelinq.1.4.0' already exists in folder 'C:\tfskb\Nemo\Baseline\DeploymentTool.nuget....\packages'
Added package 'morelinq.1.4.0' to 'packages.config'
Successfully installed 'morelinq 1.4.0' to CommonTestFiles
Package 'MasterFlt.1.0.3' already exists in folder 'C:\tfskb\Nemo\Baseline\DeploymentTool.nuget....\packages'
Added package 'MasterFlt.1.0.3' to 'packages.config'
Successfully installed 'MasterFlt 1.0.3' to CommonTestFiles

But in the package config file, only the dependencies are updated, not the package itself
  <package id="Geometry" version="1.0.7" targetFramework="net452" />
  <package id="MasterFlt" version="1.0.3-beta4" targetFramework="net452" />
  <package id="morelinq" version="1.4.0" targetFramework="net452" />

If I check the references, the MasterFlt file itself has been correctly updated, but not the other files in the same package.  

I have seen similar issue now with VS 2015 and Nuget 3.2.61008.10581, also using the Manage Pacakges in solution dialog.  It says it has updated all packages, but it really hasn't, and  I believe the cause is the same - manually changed references disturbs the nuget updater.

**Comment by yishaigalatzer** [comment]
@OsirisTerje can you provide a repro project here? There are many moving pieces and it will be a lot easier to start with a project that is broken.

Also please provide exact versions of nuget and visual studio you are using?

**Comment by OsirisTerje** [comment]
Ok, will do, upload it somewhere tomorrow (night time here now).  VS 2015 Update 1 RC, with Nuget 3.2.61008.10581

**Comment by yishaigalatzer** [comment]
@OsirisTerje going back through old bugs. Do you have a repro project for this?

**Comment by rrelyea** [comment]
@OsirisTerje - we'd like to investigate if you can help us understand how to reproduce the problem. please try to help us repro with 3.5.0-rc1 (or later) and we'll dig in.

**Comment by OsirisTerje** [comment]
This was an old one that drowned in time - I'll create a repro, amd check if it still there, and if so, then upload to github.

**Comment by rrelyea** [comment]
Doesn't appear to have enough users affected to make important enough to consider.
