### ISSUE TITLE
NuGet (version 3.2): command "nuget install" doesn't fail if can't find specific package version

### ISSUE THREAD

**Issue by burnasheva** [NuGet/Home#1714]
In previous NuGet versions (e.g. 2.8) "nuget install" command fails if can't find package (can't find specidied version or the feed is unavailable). The command return code 1, my build script failed at this step and I clearly saw the cause of the problem.

Now, in the version 3.2 nuget install command doesn't fail, just show warning message:
`Restoring NuGet package CalcProject.0.120.0.`
`WARNING: Unable to find version '0.120.0' of package 'CalcProject'.`
The build failed only on the compilation step.

**Comment by yishaigalatzer** [comment]
@burnasheva thanks for your report. This was fixed in 3.3 already.

```
C:\temp\test>nuget33-beta.exe restore packages.config -PackagesDirectory FooP
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
)\MSBuild\14.0\bin'.
Restoring NuGet package AutofacX.3.5.2.
WARNING: Unable to find version '3.5.2' of package 'AutofacX'.
Unable to find version '3.5.2' of package 'AutofacX'.

C:\temp\test>echo %errorlevel%
1

C:\temp\test>
```

The latest nuget.exe is available from our nightly build source on http://myget.org/gallery/nugetbuild in the nuget.commandline package
