### ISSUE TITLE
Package Cache folder ACL file permissions

### ISSUE THREAD

**Issue by japplequ** [NuGet/Home#1715]
We are having a big permissions issue with NuGet packages being pulled from the local machine cache folder under a user's profile folder/NuGet.  Since that is the default directory for cache, user profile directories are of course restricted to the current user and admins, and system.

During an msbuild, msbuild is pulling the cached file to the builds bin directory and of course maintaining file permissions.  In a web project, certain users need access to read dlls.  Since the file came across with limited permissions, the web project fails to open in a browser.  Once permissions on the web folder are RESET using icacls to their default inherited permissions, all is well.

The crux of the problem is that a cache should not behave this way.  I realize there is probably a setting to change the cache location to a non-user profile folder, but we still feel this is out of the norm.

Can you tell me if this is a known issue that I could not find in the issue list?  Is this a bug in how the caching works?

Thank you for your help.

**Comment by yishaigalatzer** [comment]
@japplequ can you provide more details, and exact scenario you are addressing?

What version of nuget and visual studio are you using? What is the project type you are building? What version of asp.net

etc.

**Comment by japplequ** [comment]
NuGet 2.8.6x, on VS 2012 update 5.  Asp.net 5 I believe.  We are NOT publishing, just building.  The solution we have is extremely large.  We starting noticing this when we found that an incorrect version of a nuget file from one package ended up in the package folder for another version, meaning a 5.0 version of system.net.http.formatting in a 5.0 package folder got overwritten with a 4.0 version, which later led to the permission discovery.  That's a huge issue but I have not filed it yet because I don't have much to provide.

I have understood that the package restore only uses the cached copy as a FALLBACK, which in our case would be extremely rare for the nuget server.

So when it uses it locally, we get the file permissions of the file how it existed in the user profile directory.  We have reproduced this on several machines.

**Comment by yishaigalatzer** [comment]
So you are saying that you build with one user, and another user works directly on the build result, without any deployment step?

**Comment by japplequ** [comment]
well, i mean, each developer builds locally, and the web directory is actually the bin directory of the web  site.  So we dont have to publish, it's already there.  we are aware of an msbuild target that will change permissions but that is only on a publish, and we dont have that anyway.

**Comment by yishaigalatzer** [comment]
I think the answer is that if you want the project to work for different users, you have to either publish it or to add the msbuild task that changes permissions.

That sounds like the right place to fix this, I don't know that nuget could/should do anything here.

**Comment by japplequ** [comment]
You may be right.  But consider this.  I want the project to work for me too.  So i can't run the project on my machine because of my own permissions were copied from the NuGet cache folder to the bin directory.  The point is that the NuGet cache folder is by default placed in a restricted directory which rears its head for IIS projects that suddenly by default no longer have read permissions to a dll.

I appreciate your input.

**Comment by yishaigalatzer** [comment]
You can either re-set the ACLs as part of build, or run IIS as your user instead of the network user. This is unfortunately a known problem with full IIS, where you need to do a proper deployment.

We can look at fixing this at some point in the future. But the scenario seems very low priority, given that you have a workaround.

As always we are open to taking a pull request with a fix, if you want to accelerate it.
