### ISSUE TITLE
C#: creating Windows Universal project shows 'Progress in this operation is taking a long time...' message

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1718]
Copied from TFS

Occasionally, when creating a C# Windows Universal project,  'Progress in this operation is taking a long time...' message dialog is shown (See snapshot at the end)

This is an intermittent issue. But, following is why it could happen

When an operation under ThreadHelper.JoinableTaskFactory.Run is not marked as 'LongRunning', it could end up showing the 'Progress in this operation is taking a long time...' message.

Note that OnBuildPackageRestorer does this correctly at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/VsExtension/VsEvents/OnBuildPackageRestorer.cs#L239

During project creation also packages are restored, and VSPackageInstaller is used in the process. In that scenario as well, we need to marked the JTF as long running.

![image](https://cloud.githubusercontent.com/assets/2380340/11107715/45936080-8895-11e5-8059-524abf3b8115.png)

**Comment by emgarten** [comment]
Fixed with background restore.
