### ISSUE TITLE
Package Manager For Visual Studio overwrites solution nuget.config if any changes are made

### ISSUE THREAD

**Issue by jacku-abide** [NuGet/Home#1719]
I have customised my nuget.config file inside the .nuget folder of my solution.

If I then go into the Nuget Package Manager options screen and make any changes (either in General or Packages sources) the nuget.config file in my solution gets overwritten with a near-empty template file.

Surely changing the VS Package Manager settings should only modify the %AppData%\Nuget\nuget.config file, not the settings for my solution?

I'm using VS2013 with:
Nuget Package Manager For Visual Studio
Nuget 2.8.60723.765

**Comment by yishaigalatzer** [comment]
This is a known issue, and we plan to address it in one the next releases of nuget 3.

The assumption for this dialog was that it tries to update the nearest possible settings, which is obviously sometimes correct, and many times not.

The plan to is to provide a hierarchical settings dialog that resolves this issue.

We do not plan to update nuget 2.X for visual studio 2013 and earlier with this change.

https://github.com/NuGet/Home/issues/1114
