### ISSUE TITLE
NuGet is missing latest schema change from DNX

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1723]
DNX has been writing Version: 2 in the lock file as of this commit: https://github.com/aspnet/dnx/commit/ed8b37a7 (thanks @DaGood for tracking this down).  NuGet doesn't have this change.  The result is that NuGet will always try to regenerate lock files that were generated by DNX.

/cc @emgarten  @yishaigalatzer

**Comment by yishaigalatzer** [comment]
We are hoping that in the next release DNU is going to be gone. So that shouldn't be an real issue real soon

**Comment by emgarten** [comment]
Right now nuget.exe and dnu are not expected to be interchangeable, and neither are the lock files they create. Rewriting the file is expected here.

As @yishaigalatzer mentioned they **will** merge soon and this problem will finally be solved :smile:

**Comment by ericstj** [comment]
Ok, but you have been flowing most of the code from DNX.  My impression was that DNX would eventually move to using shared nuget libraries.  Do you need to flow this change from DNX > NuGet or is it not required?

**Comment by emgarten** [comment]
It will get brought over in the merge. We had been flowing bug fixes but not all features between the two. I think the confusion here is that NuGet and DNU had differences between their Version 1 formats. If that wasn't the case then it would be just porting this change to NuGet to get Version 2 support.

**Comment by emgarten** [comment]
NuGet now writes v2 lock files
