### ISSUE TITLE
API to do TFM -> Generation mapping

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#1725]
Given a set of target TFMs, the VS PCL tooling needs to be able to compute the highest compatible generation so it can write it into project.json. That API should probably be exposed through the NuGet VS service, the way the package installation APIs are.

**Comment by yishaigalatzer** [comment]
CC @davidfowl

**Comment by yishaigalatzer** [comment]
@rchande as far as I know you guys don't need it, so I'm closing as won't fix for now

CC @Pilchie
