### ISSUE TITLE
Doc bug: Information on requireReinstallation should go to https://docs.nuget.org/consume/reinstalling-packages

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1726]
Doc bug: Information on requireReinstallation should go to https://docs.nuget.org/consume/reinstalling-packages. Currently, the information is only found on https://docs.nuget.org/release-notes/nuget-2.7

**Comment by SimonCropp** [comment]
thanks

**Comment by kraigb** [comment]
Fixed with NuGet/NuGetDocs#694
