### ISSUE TITLE
Make extracted /Content read-only

### ISSUE THREAD

**Issue by drauch** [NuGet/Home#1729]
Extracted content from the /Content folder could be made read-only by default, such that people know when they try to overwrite a file that is probably updated when updating NuGet packages in the future. Read-only flags can be easily enough circumvented if it is really necessary to overwrite such files, but protect us from accidental changes in NuGet-related files.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
