### ISSUE TITLE
NuGet should format whitespace in project.json per VS behavior

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1731]
When VS formats my project.json document, I have this:

``` json
{
  "dependencies": {
    "Nerdbank.GitVersioning": "1.1.47-rc-g58708fcf8c",
    "PInvoke.BCrypt": "0.1.122-beta",
    "StyleCop.Analyzers": "1.0.0-beta014",
    "Validation": "2.2.8"
  },
  "frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile32": { }
  },
  "supports": { }
}
```

After NuGet updates a package dependency, I'm left with this:

``` json
{
  "dependencies": {
    "Nerdbank.GitVersioning": "1.1.47-rc-g58708fcf8c",
    "PInvoke.BCrypt": "0.1.122-beta",
    "StyleCop.Analyzers": "1.0.0-beta014",
    "Validation": "2.2.8"
  },
  "frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile32": {}
  },
  "supports": {}
}
```

Notice that the single space between `{ }` is removed to `{}`. This introduces noise in SCC diffs/code reviews. And potentially introduces merge conflicts where none needed to exist.

Can the NuGet VS extension be modified to format project.json in the same way VS does?

**Comment by yishaigalatzer** [comment]
#1527

**Comment by emgarten** [comment]
Closing since we are moving from project.json to PackageReference. If not this would be a great idea.
