### ISSUE TITLE
VS2013 2.9RC: Clearing search box causes "Retrieving information" forever

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#1732]
Build 2.9.0.780

Repro steps:
1. Open the package manager
2. In the "search online" box, enter a search term and hit enter.  The search results show up.
3. Clear the "search online" box, and hit enter.
4. The HTTP request to Search() completes successfully, but the spinner is stuck on "Retrieving information" forever.
5. Hitting cancel causes results to show up, but only the first page.

**Comment by yishaigalatzer** [comment]
We no longer maintain fix level of issues in older versions of the client
