### ISSUE TITLE
Locked lock files are not rewritten when out of date

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#1733]
When a locked `project.lock.json` is out of date (e.g. after changing a dependency in `project.json`), nuget restore says:

> The lock file is out-of-date relative to the project file. Regenerating the lock file and re-locking.

The correct packages are restored, but no change is made to the lock file.

@ericstj tracked this down to the `RestoreResult` constructor not saving the value of `relockFile` into its `RelockFile` property: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreResult.cs#L54

**Comment by yishaigalatzer** [comment]
locked lock files have been deprecated, they no longer exist.
