### ISSUE TITLE
Error updating package for project file via CMD (nuget.exe)

### ISSUE THREAD

**Issue by Kamarey** [NuGet/Home#1735]
I'm trying to update a package via nuget.exe in CMD from our company's local package repository:

nuget.exe update C:\ProjectPath\Project.vbproj -Source MySourceName -Id PackageId

I get this error:

"The project file could not be loaded. Access to the path 'C:\ProjectPath' is denied.  C:\ProjectPath"
- File .vbproj and related packages.config are NOT readonly.
- I run CMD as administrator so permission is not an issue here. Also when using the ProcessMonitor I see all SUCCESS results when nuget.exe access the above files.
- If instead .vbproj file I provide packages.config - the package updated successfully (only in packages.config file)

NuGet Version: 3.2.0.10516

**Comment by paiden** [comment]
Same issue here. My nuget version also is 3.2.0.10516. 

My command is 
`NuGet.exe update Folder\ProjFolder\Proj.csproj -configFile .nuget\NuGet.config -id PackageId -RepositoryPath packages`

As soon as I switch back to nuget version 2.8.50506.491 the build works as expected.

**Comment by yishaigalatzer** [comment]
Just verified this works with NuGet 3.3, would you mind verifying it in your projects?

You can find it in: http://myget.org/gallery/nugetbuild

Download the nuget.commandline package, extract it (you can rename to .zip), and try nuget.exe from there.

Please let me know if this still repros.

**Comment by Kamarey** [comment]
Yep, looks it works. When the 3.3 will be released? Is it safe to use this version if I don't use new features?

**Comment by yishaigalatzer** [comment]
@Kamarey thanks for verifying!

It is going to be released in a few weeks. It is pretty stable, we are making a few perf/reliability fixes and error scenarios improvements before shipping. It is definitely better/more stable than 3.2.1-RC
