### ISSUE TITLE
nuget.exe: Fix the strings for add and init commands once the docs PR is signed-off

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1736]
nuget.exe: Fix the strings for add and init commands once the docs PR is signed-off

https://github.com/NuGet/NuGetDocs/pull/387

**Comment by csharpfritz** [comment]
Docs PR: NuGet/NuGetDocs#387

**Comment by yishaigalatzer** [comment]
@deepakaravindr details or a PR should be attached to this bug

**Comment by deepakaravindr** [comment]
@yishaigalatzer 

Done. Do you have any comments on this PR? https://github.com/NuGet/NuGetDocs/pull/387

**Comment by RanjiniM** [comment]
Verified the strings
