### ISSUE TITLE
nuget.exe add and init commands ignore invalid packages on the destination. Should it overwrite?

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1738]
nuget.exe add and init commands ignore corrupt packages. Should it overwrite? It is nice that there is no automatic overwrite happening. But, at least it would be nice to be able to force an overwrite

Repro steps:
1. Run nuget.exe add c:\packages\A.1.0.0.nupkg -Source c:\of-4
2. Addition will succeed. Delete the hash file for package A from c:\of-4\a\1.0.0
3. Run nuget.exe add c:\packages\A.1.0.0.nupkg -Source c:\of-4

Expected:
Actual is the current expected behavior. Should the expected behavior be changed to replace an invalid package?

Actual:

![image](https://cloud.githubusercontent.com/assets/2380340/11198737/4b0389ba-8c7c-11e5-93bb-949f5baf9e0c.png)

With init, there is a warning for invalid packages and they are skipped. Should init overwrite? Or, should there be a switch to force the overwrite

![image](https://cloud.githubusercontent.com/assets/2380340/11198840/0aa84756-8c7d-11e5-83c5-62d42175c29b.png)

**Comment by yishaigalatzer** [comment]
The current behavior is not bad, but a Force switch will be nice. We should always warn about overwritten corrupt packages.

Also validate that exit code here is not zero

**Comment by emgarten** [comment]
closing due to lack of feedback in this area.
