### ISSUE TITLE
Nuget Package Manager - Unable to view currently installed version description

### ISSUE THREAD

**Issue by jwidmer** [NuGet/Home#1740]
In the Nuget Package Manager, when looking at the Installed tab the description is always linked to the version drop down and so you cannot get the latest version info to show up in the description panel.  This is also an issue when on the Browse tab and you have that package installed.  Not a problem if you do not have the package installed.

![image](https://cloud.githubusercontent.com/assets/1501203/11225043/0d56d08e-8d46-11e5-97b7-227ff20a8679.png)

![image](https://cloud.githubusercontent.com/assets/1501203/11225016/e44a65ca-8d45-11e5-8d10-6875d5f0c888.png)

**Comment by yishaigalatzer** [comment]
@feiling we need to discuss a design that will enable it.

Putting this tentatively in 3.4, to see if we can come up with something.

Practically speaking the description rarely every changes from version to version, but when we add releases notes here, it will become a more prominent issue

**Comment by yishaigalatzer** [comment]
@rrelyea lets work with the UI designer to see if we can come up with something? Perhaps enable the installed version in the dropdown, but then disable the buttons?
