### ISSUE TITLE
allow nuget validation rules to be disabled (-disablerules)

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#1741]
old pull request
https://nuget.codeplex.com/SourceControl/network/forks/vdbg/rules/contribution/7654

stripped thread for context.

From: Yishai 
Sent: Tuesday, November 17, 2015 3:41 PM
Subject: RE: issues with nuget 3.2.0

File a bug for now on https://github.com/nuget/home/issues and we can take it from there

From: Josh 
Sent: Tuesday, November 17, 2015 3:47 PM
Subject: RE: issues with nuget 3.2.0

This can wait for the next release.  I have no idea how to create a new pull request.  Is this something you guys can handle on your end or do you need me to do it.

From: Yishai 
Sent: Tuesday, November 17, 2015 3:41 PM
Subject: RE: issues with nuget 3.2.0

Looks like this was abandoned, we should probably spin up a new PR. 
Yishai

From: Josh 
Sent: Tuesday, November 17, 2015 3:15 PM
Subject: RE: issues with nuget 3.2.0

A while ago Gregory worked with Fei to add the -disablerules feature to nuget.exe.  

See attached for source review.
The pull request is here.
https://nuget.codeplex.com/SourceControl/network/forks/vdbg/rules/contribution/7654
It was accepted on Nov 05, 2014.

**Comment by yishaigalatzer** [comment]
We would love to reconsider this suggestion, it will need to be rebuilt against nuget.client repo (against the new command line project, and perhaps the xplat one as well).

It will also require a doc PR to nugetdocs repo
