### ISSUE TITLE
"dnu restore" does not honor locked property in project.lock.json

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1744]
I have a set of DNX projects where I've checked in project.lock.json files with the locked property set to `true`. But `dnu restore` rewrites them anyway.

`dnu restore -?` documentation still documents the locked property as if it's still supported:

>   --lock                      Creates dependencies file with locked property set to true. Overwrites file if it exists.
>   --unlock                    Creates dependencies file with locked property set to false. Overwrites file if it exists.

The locked property is still [documented as supported online](http://docs.nuget.org/consume/projectjson-format) as well.

If the locked property is truly unsupported at this point (as @yishaigalatzer suggested by email), then this issue should track removal of all documentation of it or notation that newer versions of nuget/dnu don't support it any more. But if it should work, please consider that this issue tracks correcting the behavior of `dnu restore` to respect the property.

Repro case: 
commit 08713cc1b of MSFT internal devcore repository.

See related #1036

**Comment by yishaigalatzer** [comment]
dnu is not tracked here, you might want to file a DNX issue (though I won't expect anything to happen there as we are going to start merging the two shortly)

**Comment by yishaigalatzer** [comment]
Fixed
