### ISSUE TITLE
Extract to wrong folder - other version

### ISSUE THREAD

**Issue by japplequ** [NuGet/Home#1745]
We are experiencing strange behavior in a very large C# solution.  Our solution contains multiple versions of NuGet packages such as Thinktecture and NewtonSoft.Json.  

Either MSBuild or NuGet are the most likely causes of the issues after weeks of research.  What happens is that say a Thinktecture version 3.5.0.0 package finds its way into the Thinktecture 3.6.0.0 folder, under the net45 folder.  So a build error occurs because it wants the 3.6 version but find the 3.5 version.

Diagnostic logging has not produced any hints as to what is going on.  It is very very hard to reproduce, but when it happens a few times per week, it's mind boggling.  I wish I had better terminology to describe the issue, but what it feels like is that nuget is trying to restore a package, somehow the extracts are crossing paths, literally.  On some occasion, if we are lucky, we can purge the packages folder and rebuild, and it might be a few hours until the issue rears its head.

We do use parallel builds, 4 in fact, on this solution via msbuild.  It would be great to point to various facts, but most of them do not seem to make sense.

We believe that since the only dlls that have this issue are dlls that come from NuGet packages, and none of the other project based dlls, that this is most likely a NuGet issue during extraction and possibly parallel builds.

**Comment by yishaigalatzer** [comment]
@japplequ can you provide more details, what version of nuget.exe are you using? What kind of project is this etc.?

**Comment by japplequ** [comment]
This is nuget 2.8.6.  It is a gigantic visual studio solution with web projects, mvc, and some windows services.  It has everything.

**Comment by yishaigalatzer** [comment]
Thanks. Would you mind updating to NuGet 3.2.1-rc from dist.nuget.org or better yes nuget 3.3 from nugetbuild feed on myget?

(After the update) Can you reproduce this by just running nuget.exe restore on your packages.config and finding the wrong dll in the wrong folder

**Comment by japplequ** [comment]
It is so hard to reproduce, as I've spent weeks on it.  If I had some insight into how this might be happening, if at all, something specific in my older version, that would be a comfort to know it wasn't all in vain!  I would love to update but want to get to the root of this before I ask the release manager to do this.  If I am the first to bring something like this up, then it is likely not a NuGet issue, but I have to rule it out.  

Thank you for your time.

**Comment by yishaigalatzer** [comment]
Suggestion on trying to repro

Run a loop a round nuget.exe restore your solution
// Run some code to verify that something leaked (in your case it was always thinkechture I guess
// Break if it happens
Cleanup

**Comment by japplequ** [comment]
Ok, I will do that probably Monday.  Thanks for the idea.

**Comment by yishaigalatzer** [comment]
Closing as I haven't heard anything here. I assume you are in a good place. Let us know if this is not the case
