### ISSUE TITLE
Relative file path for "DefaultPushSource"

### ISSUE THREAD

**Issue by LarterStyles** [NuGet/Home#1746]
As far as I can tell, the "DefaultPushSource" configuration key doesn't allow you to specify a relative file path.

This works:

```
<add key="DefaultPushSource" value="C\Source\Project\CustomFeed" />
```

This doesn't:

```
<add key="DefaultPushSource" value="CustomFeed" />
```

This causes issues when executing builds + generating packages from a build server which may not even have a C:\

**Comment by yishaigalatzer** [comment]
You can always define the settings on the build server proper, so that should give you a workaround. Or better yet push explicitly to a known folder in the command itself

**Comment by spadapet** [comment]
Also need to make relative paths work as normal sources:
    nuget push foo.nupkg -Source packages
    nuget push foo.nupkg -Source ..\packages
    nuget push foo.nupkg -Source .\packages

**Comment by spadapet** [comment]
I'll open a new issue for "push -Source foo" being relative. I don't want the change for that to be mixed up with the change for this fix.
