### ISSUE TITLE
NuGet.PackageManagement.Cmdlets: value cannot be null error for user's wrong input

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#175]
PM> install-package knockoutjs version 3.2.0
install-package : Value cannot be null.
Parameter name: nuGetProject
At line:1 char:1
- install-package knockoutjs version 3.2.0
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

when "-" is missing before Version, get the above error. should make error more friendly.

**Comment by vdevappa** [comment]
I get this issue.

![image](https://user-images.githubusercontent.com/22800346/27097396-1db2d3b8-5042-11e7-9625-2f53490e4911.png)
