### ISSUE TITLE
NuGet has not been working all day from VS 2015

### ISSUE THREAD

**Issue by erickbp** [NuGet/Home#1750]
It happens with any package I try. See image
![image](https://cloud.githubusercontent.com/assets/10678433/11307420/097c8174-8f86-11e5-848e-d03c8aca7b35.png)

**Comment by yishaigalatzer** [comment]
@joyhui can you do a first pass investigation?

**Comment by erickbp** [comment]
sure, let me know what I need to do.

**Comment by joyhui** [comment]
I tried in VS2015 for both
v3: https://api.nuget.org/v3/index.json
v2: https://www.nuget.org/api/v2

They are all working:
![capture](https://cloud.githubusercontent.com/assets/4565352/11312621/35c67b62-8f8c-11e5-863b-682dc8f2b9a4.png)

There may be network issue in your side. Can you put fiddler to confirm the http request?

**Comment by erickbp** [comment]
@joyhui I have just tried with Fiddler running. I didn't get any response from http://api.nuget.org:443
[2_Request.txt](https://github.com/NuGet/Home/files/40573/2_Request.txt)
[2_Response.txt](https://github.com/NuGet/Home/files/40574/2_Response.txt)

**Comment by erickbp** [comment]
@joyhui  Here is another interesting thing. I'm not experimenting any internet issue and yet ping to api.nuget.org is that bad ( see image )

![image](https://cloud.githubusercontent.com/assets/10678433/11312849/cb455e96-8fa6-11e5-9ddc-650b5a7ad53e.png)

**Comment by joyhui** [comment]
Our CDN services may be experiencing problem. let me check and get back to you.

**Comment by yishaigalatzer** [comment]
Try to ping `api.nuget.org/v3/index.json`

**Comment by erickbp** [comment]
![image](https://cloud.githubusercontent.com/assets/10678433/11313677/c2d27f54-8fac-11e5-93e2-68255736fb25.png)

**Comment by erickbp** [comment]
here is ping api.nuget.org
![image](https://cloud.githubusercontent.com/assets/10678433/11313701/ed6dabda-8fac-11e5-9b75-b81b581a2bed.png)

**Comment by yishaigalatzer** [comment]
curl https://api.nuget.org/v3/index.json

**Comment by erickbp** [comment]
![image](https://cloud.githubusercontent.com/assets/10678433/11314011/9dc20484-8faf-11e5-9277-d8211400ae3f.png)

**Comment by erickbp** [comment]
![image](https://cloud.githubusercontent.com/assets/10678433/11314033/d4fbd1f0-8faf-11e5-9f97-e8a4899f7497.png)

**Comment by joyhui** [comment]
http://api.nuget.org/v3/index.json , not API in between.

**Comment by joyhui** [comment]
Here is more you have to in order to identify problem: (sorry)
1. http://winmtr.net/how-to/
   Use MTR tool to api.nuget.org, wait for sent >=100, copy text to clipboard
   ![capture](https://cloud.githubusercontent.com/assets/4565352/11314269/dc10d560-8f98-11e5-9729-cf7cea0f18a4.png)
2. Please let me know your geographical area.. where are you.

Thanks,

**Comment by erickbp** [comment]
http://api.nuget.org/v3/index.json works fine

![image](https://cloud.githubusercontent.com/assets/10678433/11314309/648467f4-8fb2-11e5-88bc-7b227320471a.png)

**Comment by yishaigalatzer** [comment]
Can you share your nuget sources? They show up in the UI and in nuget.config

**Comment by erickbp** [comment]
@joyhui  I'm in West Palm Beach, FL, USA

|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                                10.0.0.1 -    0 |  128 |  128 |    1 |    5 |   76 |    6 |
|                             96.120.36.9 -    0 |  128 |  128 |   10 |   16 |   91 |   17 |
|xe-10-3-3-0-sur02.northpoint.fl.pompano.comcast.net -    0 |  128 |  128 |    9 |   17 |   81 |   16 |
|xe-2-0-8-0-ar02.stuart.fl.pompano.comcast.net -    0 |  128 |  128 |   12 |   23 |  118 |   48 |
|he-0-17-0-0-ar01.northdade.fl.pompano.comcast.net -    0 |  128 |  128 |   16 |   25 |  132 |   20 |
|be-20214-cr01.miami.fl.ibone.comcast.net -    0 |  128 |  128 |   18 |   29 |  140 |   32 |
|he-0-12-0-0-pe03.nota.fl.ibone.comcast.net -    0 |  128 |  128 |   17 |   27 |  120 |   27 |
|                           50.248.119.98 -    0 |  128 |  128 |   17 |   27 |  118 |   21 |
|                          93.184.215.200 -    0 |  128 |  128 |   16 |   27 |  139 |   33 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider

![image](https://cloud.githubusercontent.com/assets/10678433/11314350/cbf30d1e-8fb2-11e5-8181-bed0b42e1569.png)

**Comment by erickbp** [comment]
@yishaigalatzer This keeps saying "loading" and I get nothing
![image](https://cloud.githubusercontent.com/assets/10678433/11314382/151bf0fa-8fb3-11e5-8a71-1eae6691f9f6.png)

**Comment by yishaigalatzer** [comment]
Click the gear icon on the top right

**Comment by erickbp** [comment]
@yishaigalatzer 
![image](https://cloud.githubusercontent.com/assets/10678433/11314429/7baa5d34-8fb3-11e5-9a19-c596cfde8ffc.png)

**Comment by joyhui** [comment]
Can you use fiddler to check the requests?
http://www.telerik.com/download/fiddler

It will help us to know which request really block you. Here is the example requests when I execute the same command:
![capture](https://cloud.githubusercontent.com/assets/4565352/11314500/e6e21da8-8f9a-11e5-8b3f-951ec67c302f.png)

**Comment by joyhui** [comment]
Can I know your public IP?

**Comment by erickbp** [comment]
@joyhui we can do share screen/remote control if you want. 
![image](https://cloud.githubusercontent.com/assets/10678433/11314596/034f1b20-8fb5-11e5-953f-d4812b56872c.png)

**Comment by erickbp** [comment]
2601:587:101:c0fa::7c9c

**Comment by joyhui** [comment]
Can you try again for install package? The MTR result seems clean, no packet lost.

**Comment by erickbp** [comment]
I tried to install a package from VS and it is still not working.
![image](https://cloud.githubusercontent.com/assets/10678433/11314747/80a7a852-8fb6-11e5-89c9-e83d06db554c.png)

![image](https://cloud.githubusercontent.com/assets/10678433/11314737/67339ff2-8fb6-11e5-982b-10a8cea03a58.png)

**Comment by joyhui** [comment]
Can you clean up local cache manually if it exists and try again?

Nuget HTTP cache: C:\Users\hujiang\AppData\Local\NuGet\v3-cache
NuGet cache: C:\Users\hujiang\AppData\Local\NuGet\Cache
NuGet global packages cache: C:\Users\hujiang.nuget\packages\

How can we share screen/remote control? Skype?

**Comment by joyhui** [comment]
In fiddler, please decrypt HTTPs traffic:
Tools > Fiddler Options > HTTPS > Decrypt HTTPS traffic option.

Do you get same result with and without running Fiddler?

**Comment by erickbp** [comment]
I had it configured to decrypt HTTPS.
It seems to be working now, very slow though but working. Thank you

**Comment by joyhui** [comment]
Try to download this file.. this is the first step of resolving dependency.
https://api.nuget.org/v3/registration1/microsoft.owin.security.openidconnect/index.json

**Comment by erickbp** [comment]
that file downloads fine, less than a sec. what do I do with it?
I tried Update-Package and I got this:
![image](https://cloud.githubusercontent.com/assets/10678433/11314990/55a85b9e-8fb9-11e5-98fb-6c0b16f0247d.png)

**Comment by joyhui** [comment]
I tried in my machine too.. it is working. Hum...

![capture](https://cloud.githubusercontent.com/assets/4565352/11315023/af0f7d98-8fa0-11e5-8532-608d22e4dfdc.png)

Are you behind a company proxy server?

**Comment by erickbp** [comment]
no, I'm at home, Comcast, 90Mbs

**Comment by joyhui** [comment]
This is the list of files downloaded when execute: Update-Package:

# Result  Protocol    Host    URL Body    Caching Content-Type    Process Comments    Custom

18  200 HTTPS   api.nuget.org   /v3/registration1/microsoft.owin.security/index.json    38,419  no-store    application/json    devenv:5144  
19  200 HTTPS   api.nuget.org   /v3/registration1/owin/index.json   9,625   no-store    application/json    devenv:5144  
20  200 HTTPS   api.nuget.org   /v3/registration1/system.identitymodel.tokens.jwt/index.json    74,672  no-store    application/json    devenv:5144  
21  200 HTTPS   api.nuget.org   /v3/registration1/microsoft.identitymodel.protocol.extensions/index.json    68,253  no-store    application/json    devenv:5144  
22  200 HTTPS   api.nuget.org   /v3/registration1/microsoft.owin/index.json 32,100  no-store    application/json    devenv:5144  
23  200 HTTPS   api.nuget.org   /v3/registration1/microsoft.owin.security.openidconnect/index.json  28,103  no-store    application/json    devenv:5144  
25  200 HTTPS   api.nuget.org   /v3/registration1/system.identitymodel.tokens/index.json    86,589  no-store    application/json    devenv:5144  
27  200 HTTPS   api.nuget.org   /v3/registration1/newtonsoft.json/index.json    64,399  no-store    application/json    devenv:5144  
28  200 HTTPS   api.nuget.org   /v3/registration1/microsoft.identitymodel.logging/index.json    24,379  no-store    application/json    devenv:5144 

Can you also give a try on Fiddler directly? If there are working well, it is not the server problem then. We can focus on the VS + Nuget client.

**Comment by erickbp** [comment]
![image](https://cloud.githubusercontent.com/assets/10678433/11315161/988033cc-8fbb-11e5-80b8-6939701a5183.png)

**Comment by erickbp** [comment]
I can see the upgrade available but I cannot use the command to upgrade
![image](https://cloud.githubusercontent.com/assets/10678433/11315178/dd061a34-8fbb-11e5-8af0-45839633aa71.png)

**Comment by joyhui** [comment]
The fiddler shows all download succeeded. Nice.

Can you click "Upgrade" button to upgrade? Please monitor fiddler to find the requests.

**Comment by erickbp** [comment]
I tired 3 times. it didn't work. Second time almost works but it failed. see the error in VS and Fiddler
![image](https://cloud.githubusercontent.com/assets/10678433/11315308/c92ea16e-8fbd-11e5-94c3-1cb7612a953a.png)

**Comment by joyhui** [comment]
In fiddler, can you add Overall_Elapsed column?
Right click on column head -> Customize Columns ... -> In popup dialog, choose "Session Timers" in collection, "Overall_Elapsed" in Timer Name.

Then make those these call, and check the overall elapsed time. I suspect the latency may cause timeout in nuGet client.
https://api.nuget.org/v3/registration1/microsoft.owin.security/index.json
https://api.nuget.org/v3/registration1/owin/index.json
https://api.nuget.org/v3/registration1/microsoft.owin.security.openidconnect/index.json
https://v3/registration1/microsoft.identitymodel.logging/index.json

**Comment by joyhui** [comment]
It may be a nuget client bug. Can you have your email?

**Comment by erickbp** [comment]
three links came fine but it still doesn't work in VS 2015
![image](https://cloud.githubusercontent.com/assets/10678433/11315642/845bd97a-8fc3-11e5-8060-ad23032f3d2e.png)

**Comment by erickbp** [comment]
my GitHub username at gmail.com

**Comment by joyhui** [comment]
Most probably it is a client bug. Check your email box.. and give a try.

**Comment by erickbp** [comment]
I tried 2 times, second one worked. Thank you so much!

**Comment by joyhui** [comment]
Glad to help you solve the problem.
