### ISSUE TITLE
Command line backslash \ and double quote interaction

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#1752]
It looks like the path separator `\` character quotes the double quote `"` character in the command line and needs to be doubled before the quote, but not when seen by itself. Not sure if it's by design, but leads to a surprising error and a weird workaround:

```
C:\>nuget pack Nnn.csproj  -out "bin\"
Illegal characters in path.
C:\>nuget pack Nnn.csproj  -out "bin\."
Successfully created package 'bin\Nnn.1.0.1.0.nupkg'.
C:\>nuget pack Nnn.csproj  -out "bin\\"
Successfully created package 'bin\Nnn.1.0.1.0.nupkg'.
```

In my case the part represented as `bin\` here came from an MSBuild variable, so doubling the backslash at the end is not trivial. Currently I have weird construction like `-out "$(OutputFolder)."` in my build script--the dot `.` at the end looks hard to understand, to say the least.

**Comment by yishaigalatzer** [comment]
You might just want to trim the trailing slashes for now?

**Comment by yishaigalatzer** [comment]
Marking to be fixed post Update II, but will gladly take a PR with tests if someone wants to jump on this

**Comment by kkm000** [comment]
@yishaigalatzer: 

> You might just want to trim the trailing slashes for now?

Thanks, I have a workaround already, the dot at the end.Trimming/doubling backslashes is not easy in an msbuild script.

**Comment by yishaigalatzer** [comment]
I'm actually suspecting the bug is not in nuget.exe, but an expected behavior of the command line. I'll build a test app to verify

**Comment by yishaigalatzer** [comment]
Appears to be this way:

When I run the following code:

``` c#
using System;

namespace ConsoleApplication17
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < args.Length; i++)
            {
                Console.WriteLine(i + " : " + args[i]);
            }
        }
    }
}
```

With: `-pack "hello\"`

I get

```
0 : -pack
1 : hello"
```

and with `-pack "hello."

I get

```
0 : -pack
1 : hello\.
```

Which I guess explains the issue, I wouldn't want to hack auto trimming of `"` from msbuild, and looks like your workaround makes sense (unfortunately)

**Comment by kkm000** [comment]
@yishaigalatzer: I am sorry, maybe I should not even persist on this question, but the argumentation seems a bit odd to me. If you said "this does not work, and we are to fix it," I'd understand that. If you said "It works the way we designed it to work," I would understand that too. But the argument "It works the way some library we are using to parse command line works, therefore this is it" seems, if you follow me, somewhat strange, even when that library is the default command line parser in .NET. There is over 9000 command line parsers around, and nobody took away `Environment.CommandLine` from us, so the .NET bug that your test demonstrates is not impossible to work around. What are your thoughts?

**Comment by yishaigalatzer** [comment]
I'm saying that it is expected. That's not how all .net programs work, it is how windows command line work.

**Comment by yishaigalatzer** [comment]
I'm saying this is how windows command line work, not a command line parser in .NET. http://blogs.msdn.com/b/oldnewthing/archive/2010/09/17/10063629.aspx
