### ISSUE TITLE
-Tool packaging rules not propagated to referenced packages

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#1753]
I have a solution with 2 C# DLL projects, one referencing the other (say `Tasks.csproj` references `Base.csproj`). The `Base` project does not have a nuspec file, and `Tasks` does. When I package the `Tasks` package with `nuget pack -Tool -IncludeReferencedProjects Tasks.csproj`, the `Tasks.dll` ends up, as expected, in the package's `tools/` folder. But its dependency `Base.dll` is packaged as a normal library, under `lib/net40`. I would rather expect it packaged to the `tools/` folder as well.

I cannot think of any use case where that would be expected behavior. Should not the `-Tool` packaging rules be recursively applied to the packaged referenced projects as well?

**Comment by yishaigalatzer** [comment]
These are all pretty unexplored territories, I suspect you are right at least for your scenario and the current answer for these cases is to use a nuspec to pack rather than relying on this -Tool + .csproj packing.

Will gladly take a pull request for a fix.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by kkm000** [comment]
Sure, thanks, this should be really not a very common scenario anyway, and a workaround is very easy (an explicit .nuspec). 

🐑🐑🐑 I do not even remember what I was packaging...
