### ISSUE TITLE
Implicit assembly references through package depedencies 

### ISSUE THREAD

**Issue by theo-albers** [NuGet/Home#1757]
It's pretty painful how a C# project handles assembly references: each and every assembly needs to be referenced in the project References section before it will be recognized. The NuGet package provides dependency information, but still this information is copied into the C# project file for every dependency. This makes upgrading packages more painful, since an upgrade means an implicit uninstall and install. This process sometimes breaks when two packages depend on another package. 
It would be nicer if the C# project only references the NuGet packages which it has a direct dependency upon. All NuGet packages that are indirect dependencies should be resolved at build time and should not update the c# project file. I guess that's easier said than done, since NuGet packages can update config files. But I think the biggest pain today is the cascading effect of referencing a package in a project. 
Example: I create a NuGet package Foo which has a dependency towards Entity Framework 6. I expect to only see a reference to dependency Foo in my project file. I expect intellisense/compiler to dynamically pick up the Entity Framework libraries. This way I can upgrade my Foo package to depend on a newer EF package and the upgrade of my consuming project would be much smoother.

**Comment by emgarten** [comment]
The points you've outline are a great summary of how packages.config can be painful. In Visual Studio 2015 the new UWP projects use project.json instead of packages.config, it contains only the top level dependencies. We're taking a look at moving everything towards project.json to make NuGet easier to use.

**Comment by theo-albers** [comment]
The vague part for me today is that it seems like the new project layout is tied to ASP.NET 6, which is still in RC. It would be a step forward if one could use the new C# project structure for assembly projects. 
Keep up the good work, since the current assembly references are a pain.

**Comment by yishaigalatzer** [comment]
This is mostly supported for everything but the asp.net 4 projects (there is no asp.net 6 yet, you probably mean MVC6/ASPNET5).

Take a look at the [nuget.client](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Clients/NuGet.CommandLine) repo where we use this structure already. Although it is officially supported only for UWP and portable class libraries, you can opt into using it for class libraries, console apps and other project types.

We plan to expand the officially supported scenarios going forward. 

Note that you will need Visual Studio 2015 Update I, or windows sdk on top of visual studio 2015 to make it work.
