### ISSUE TITLE
Update intellisense for json editor - for include/exclude feature

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1758]
We introduced include/exclude feature but didn't update the editor schema to support it.

This can be done out of band, because the file is on line

**Comment by yishaigalatzer** [comment]
@emgarten please work with @danliu today or tomorrow on grabbing the how-to details

**Comment by joelverhagen** [comment]
`suppressParent` should also be added.

**Comment by joelverhagen** [comment]
Closed with https://github.com/SchemaStore/schemastore/pull/124.
