### ISSUE TITLE
Filter for Installed shows all packages and not just from selected packages source.

### ISSUE THREAD

**Issue by wolfpackt99** [NuGet/Home#1761]
I want to choose Source and Installed and see just those installed from a particular source. Currently if i set source.  It shows packages from that source. Then set filter, it will show all installed packages and not just those installed from selected source.

Gui: v3.2.60914.10516

**Comment by yishaigalatzer** [comment]
Package source is not going to be a filter, in the new UI we moved it away to signify that it is not a filter. I think that it will cause a disjointed experience where installed packages dissapear and the common user have no idea why they don't show up. Perhaps we should include some indication for available on the feed and a way to sort by availability.

So to summarize the source is used to control where packages are going to be installed from, or to get updates available, but not to filter the installed packages.

![image](https://cloud.githubusercontent.com/assets/1238711/11381070/bcde3c0a-92ae-11e5-84b3-da8b49c13de5.png)

I do see a bug however when we select a secondary source that doesn't include the packages
1. It is slow to load the list
2. It is missing information that is already available

Tracking with https://github.com/NuGet/Home/issues/1762

![image](https://cloud.githubusercontent.com/assets/1238711/11381185/7cdaa408-92af-11e5-9535-648d45843754.png)

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
