### ISSUE TITLE
Installed packages are missing information based on source selected

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1762]
We should include the description for the package in the installed and update available (because it is already available on disk if the package has been restored).

![image](https://cloud.githubusercontent.com/assets/1238711/11381105/ffd4c916-92ae-11e5-81f7-d84f79cdc4e0.png)

**Comment by yishaigalatzer** [comment]
we think this was fixed by @johnataylor as a side effect of the last few UI perf fixes.

**Comment by yishaigalatzer** [comment]
Still busted in 3.4, only works if you first get data from the online source

![image](https://cloud.githubusercontent.com/assets/1238711/13720563/4fa920ce-e7c1-11e5-824a-90ccd564dda4.png)

**Comment by johnataylor** [comment]
This is fixed by first reading all the installed package metadata from the physically installed packages. We then lazily go on-line to flesh out details such as available versions.

**Comment by johnataylor** [comment]
Sorry prematurely closed this. What we fixed was all the details necessary for the left hand pane - so description, icon, author. We didn't do anything to make the right hand pane appear although we do have some of those details. We are obviously missing downloads, published date, alternative versions  but we could do better and partially populate those fields.

**Comment by johnataylor** [comment]
changing priority and assignment according to @yishaigalatzer
