### ISSUE TITLE
Port fixes from DNX for httpsource.cs

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1763]
https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/NuGet/HttpSource.cs

Things I noticed so far
1. http_proxy environment variable - This is tracked by a separate bug https://github.com/NuGet/Home/issues/1671, and the change should be made across the board
2. Consider supporting 204 - Where we check for not found - https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/NuGet/HttpSource.cs#L131
3. Validate content is expected  so we don't cache faulty results https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/NuGet/HttpSource.cs#L144

**Comment by emgarten** [comment]
@joelverhagen @yishaigalatzer what work needs to happen here still?

**Comment by emgarten** [comment]
The final part of this is fixed in https://github.com/NuGet/NuGet.Client/pull/289
