### ISSUE TITLE
Feature: Better management of multiple configuration files

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1771]
The current user interface has no indication of which nuget.config settings come from that are applied to a project, nor is there control over which settings are persisted to which nuget.config file.

Idea: indicators of where the nuget.config file is located that settings are applied from
Idea: Control over which nuget.config file settings are persisted to

**Comment by yishaigalatzer** [comment]
Duo

**Comment by yishaigalatzer** [comment]
Meant dup
