### ISSUE TITLE
Feature: Simplify Repository Sources UI

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1773]
The Update -> OK steps to manage a repository location in the NuGet sources UI is confusing to some.  It could be simplified to a single "OK" button

**Comment by abatishchev** [comment]
Yes, please. Forgetting to click Update causes all changes to be discarded.
With adoption of custom vso feeds, this happens every other day.

**Comment by yishaigalatzer** [comment]
We should do it as part of the new settings UI we plan for 3.4

**Comment by yishaigalatzer** [comment]
Duplicate of #1114
