### ISSUE TITLE
Visual Studio Nuget Package Manager Reset local Nuget.config files

### ISSUE THREAD

**Issue by dai-le** [NuGet/Home#1775]
Every time I make an addition or deletion to my package source in the visual studio nuget package manager console, my local nuget.config file in the .nuget directory gets reset and I lose all the package sources that was added to this local file.

Nuget Package Manager version 2.8.60723.765 for Visual Studio 2013

**Comment by dai-le** [comment]
It's actually replacing my local package sources with

  < activePackageSource >
    < add key="All" value="(Aggregate source)" />
  < /activePackageSource >

**Comment by yishaigalatzer** [comment]
We are planning to fix this in NuGet 3.4 - https://github.com/NuGet/Home/issues/1114
