### ISSUE TITLE
nuget.exe update drops the assembly strong name and Private attribute.

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1778]
nuget.exe update drops the assembly strong name and `<Private>` attribute.

This is **not** a regression from 2.8.6.

Steps
1. Create a new C# console app
2. Install-Package newtonsoft.json -version 6.0.4
3. Save and close the solution
4. nuget.3.3.0.exe update .\packages.config -Safe

From VS:

``` xml
    <Reference Include="Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\packages\Newtonsoft.Json.6.0.4\lib\net45\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

From nuget.exe:

``` xml
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\packages\newtonsoft.json.6.0.8\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
```

**Comment by jainaashish** [comment]
https://github.com/NuGet/NuGet.Client/pull/600

**Comment by mdkf** [comment]
Just tested 3.5.0-RC1 command line client, instead of dropping the private tag it changed it from False to True.

**Comment by ferdaarikan** [comment]
Is the commit always adding the fully qualified name? The bug report was complaining about the strong name being removed. Seems like fix is always adding the strong name. We have some use cases that strong name is intentionally excluded from the reference entry. It seems like this fix is breaking the functionality.
