### ISSUE TITLE
nuget pack -NoPackageAnalysis appears to perform analysis

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#1784]
Specifying a completely invalid version field, for example, "lala" is illegal, however, even if you specify -NoPackageAnalysis this blunder is still picked up on. This is unexpected behavior.

Conversely, if you specify a 4 digit version (i.e. one that is not correctly Semantic Version) then that is allowed through even if you don't specify -NoPackageAnalysis

**Comment by yishaigalatzer** [comment]
@emgarten do you have an opinion on this?

**Comment by emgarten** [comment]
The package analysis done by pack is really more about warnings, ex: if a .dll file is in an unknown folder. The invalid version in the example here is a fatal error. Ignoring it will create an invalid package that cannot be read by any client.
