### ISSUE TITLE
NuGet restore runs msbuild and times out on machines with pegged CPU

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1785]
This issue is tracking bumping up the timeout from 1 minutes to 5 minutes (not yet configurable). Will follow up with configurable timeout, and msbuild diagnostics support

**Comment by pranavkm** [comment]
Addressed as part of https://github.com/NuGet/NuGet.Client/pull/140 \ https://github.com/NuGet/NuGet.Client/commit/377b0298f2aa76e7cd30cedf932962b2231d5316
