### ISSUE TITLE
Add diagnostics to nuget restore failures when msbuild fails to resolve P2P

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1786]
Related to:
https://github.com/NuGet/Home/issues/1785 

On roslyn builds (pegged CPU machines) we see the following 

16:06:52 Restoring: Toolsets (this may take some time)
16:07:10 Restoring: Roslyn.sln (this may take some time)

> 16:08:12 Process must exit before requested information can be determined.
> 16:08:12 Restoring: Open\src\Samples\Samples.sln (this may take some time)
> 16:08:12  d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\src\Scripting\CSharp\CSharpScripting.csproj : error MSB4057: The target "_NuGet_GetProjectsReferencingProjectJsonInternal" does not exist in the project.
#1785 address the first error, this issue should help in diagnosing the calls to msbuild resolving P2P

**Comment by emgarten** [comment]
Closing due to lack of feedback in this area.
