### ISSUE TITLE
nuget restore always restores for ARM not x86,x64

### ISSUE THREAD

**Issue by sriniketana** [NuGet/Home#1788]
I have a nupkg with the following structure 

```
runtimes\win10-arm\lib\uap10.0\MyDLL.dll
runtimes\win10-x86\lib\uap10.0\MyDLL.dll
runtimes\win10-x64\lib\uap10.0\MyDLL.dll
```

When I add this nupkg to a UWP project, only ARM build succeeds, x86 and x64 builds fail with the error 

> There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users....\runtimes\win10-arm\lib\uap10.0\MyDLL.dll", "ARM". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Upon looking around, I notice that the project.lock.json has the following structure 

```
"targets": {
    "UAP,Version=v10.0": {
      ...
        "compile": {
          "runtimes/win10-arm/lib/uap10.0/MyDLL.dll": {}
        },
        "runtime": {
          "runtimes/win10-arm/lib/uap10.0/MyDLL.dll": {}
        }
      },
...
```

Although there are other targets for x86, ARM and x64, the generic target always points to win10-arm.  After changing it manually, nuget restore again puts it back to arm. This is probably preventing successful builds of x86 and x64

**Comment by yishaigalatzer** [comment]
Would you mind updating to Visual Studio Update I and NuGet 3.3, and tell us if this still repros for you?

They both should be out (and if not available where you are, they should be shortly)

**Comment by emgarten** [comment]
This should be fixed in 3.3.0.

**Comment by sriniketana** [comment]
Tried with Visual Studio 2015 Update 1 and NuGet 3.3.0. The behaviour is now different. 
The generic target doesn't have the DLL listed anymore. The ARM, x86 and x64 targets have the DLL listed under `compile` and `runtime`

```
    "UAP,Version=v10.0/win10-arm": {
        ...
        "compile": {
          "runtimes/win10-arm/lib/uap10.0/MyDLL.dll": {},
        },
        "runtime": {
          "runtimes/win10-arm/lib/uap10.0/MyDLL.dll": {},
        },
```

However, in the project, I am not able to import any packages from MyDLL.dll. 
The VS project does not pick up anything under the win10-arm, win10-x86, win10-x64 targets.

**Comment by yishaigalatzer** [comment]
Can you share the full structure of your package?

**Comment by sriniketana** [comment]
Well, here is the full .nuspec file for a sample DLL created using NuGet 3.3 and tested on VS 2015 Udpate 1 and NuGet 3.3 

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>MyDLL</id>
        <version>8.0.0.0</version>
        <authors>Me</authors>
        <description>DLL that changes the world</description>   

    </metadata>
    <files>

        <!-- Windows 10 UWP -->         
        <file src="..\bin\x86\Debug\MyDLL.dll" target="runtimes\win10-x86\lib\uap10.0" />
        <file src="..\bin\ARM\Debug\MyDLL.dll" target="runtimes\win10-ARM\lib\uap10.0" />
        <file src="..\bin\x64\Debug\MyDLL.dll" target="runtimes\win10-x64\lib\uap10.0" />   

    </files>
</package>
```

Note that this package works fine on VS 2015 (without Update 1).

**Comment by emgarten** [comment]
The lock file and package structure look correct for a runtime package. Runtime specific assemblies should not show up under the generic target graph.

To fix the problem you are seeing now I believe you need to add a `ref` or `lib` item for the generic graph. This assembly will be used at design time, and then at compile time the actual runtime assembly will be used instead.

The nuget uwp docs provide some help on this: https://docs.nuget.org/create/uwp-create
You can also take a look at the .NET system packages.
