### ISSUE TITLE
[Test] NuGet.PackageManagement.Cmdlets: Add functional tests for new PMC features in 3.0 Beta

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#179]
Now only 4 simple tests are added.

Should make the tests covering more cases.

The features are:

- Install-Package "path To packages.config or .nupkg"

- Find-Package

- Sync-Package

- Update-Package -DependencyVersion -Version

- Get-Package -PageSize (added paging support to Get-Package)

**Comment by johnataylor** [comment]
we should also include addition functional tests for -reinstall that specifies a specific package id

**Comment by johnataylor** [comment]
additional tests for Update-Package and new tests for Sync-Package
