### ISSUE TITLE
Nuget does not build 

### ISSUE THREAD

**Issue by Jonne** [NuGet/Home#1790]
When I follow the https://docs.nuget.org/contribute/Setting-up-the-NuGet-Development-Environment 
guide, I get the following error when I build it:

```
D:\repos\NuGet3\src\NuGet.Common\ConcurrencyUtilities.cs(29,39): DNXCore,Version=v5.0 error     CS0246: The type or namespace name 'ThreadStart' could not be found (are you missing a using directive or an assembly reference?)
D:\repos\NuGet3\src\NuGet.Common\ConcurrencyUtilities.cs(31,34): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'Thread' could not be found (are you missing a using directive or an assembly reference?)
```

Its using 4.0.0-beta-23109. I haven't done anything with dnx before, so I might be doing something wrong? Any help is appreciated

**Comment by yishaigalatzer** [comment]
I have seen this issue on my machine as well before. You want to make sure you have Beta7 (for the next few days at least) of DNX installed, and you want visual studio not to have the core project open (because it might run a different version of DNX that will interfere with restore).

**Comment by yishaigalatzer** [comment]
Hey @jonne I'm assuming things work for you now. But just to let you know we just updated to DNX RC1 so you will need to move up to that version of DNX

**Comment by alpaix** [comment]
Fixed with nuget/nuget.client@fa21082c74d22e14c2b04701b52dedfa8716e087.
