### ISSUE TITLE
One parameter is missing for format string FailToWritePackagesConfig

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#1791]
In file PackagesConfigWriter.cs, there is code snippet

```
throw new PackagesConfigWriterException(string.Format(CultureInfo.CurrentCulture, 
                    Strings.FailToWritePackagesConfig, ex.Message), ex);
```

The problem is that format string FailToWritePackagesConfig requires two parameters, but there is only one provided. This should be fixed.

**Comment by zhili1208** [comment]
verified this, it's already fixed. close this bug
