### ISSUE TITLE
-Source has no effect

### ISSUE THREAD

**Issue by vvavrychuk** [NuGet/Home#1793]
I have rebuilt a NuGet package `MathNet.Numerics` with some temporary local modifications for debug purposes. I would like to temporary install it in my project to check something.

```
Update-Package MathNet.Numerics -ProjectName Sinc.Rest.Owin -Reinstall -Source C:\kom\oss\mathnet-numerics\out\packages\NuGet
```

Problem is that the above command does not installs `MathNet.Numerics.3.9.0.nupkg` from my specified folder. I see this by files sizes.

**Comment by yishaigalatzer** [comment]
It is probably picking it up from the cache. This is an expected behavior (nuget assumes Id and version translates to the same package)

You can try using nuget.exe 3.3 and use the nuget.exe locals -Clear command.

You can get 3.3 from - http://dist.nuget.org/index.html

**Comment by vvavrychuk** [comment]
Suggested command cleared cached packages but still it did not help me.

**Comment by vvavrychuk** [comment]
I did some play and found what worked for me
1. Remove the package from `SolutionFolder\packages`.
2. Run `cd Sinc.Rest.Owin && nuget restore Sinc.Rest.Owin.csproj -SolutionDirectory .. -Source C:\kom\oss\mathnet-numerics\out\packages\NuGet`

During use of the `nuget.exe` I did not found
1. If `nuget install` can install package into a specific `csproj` like `Install-Package` does.
2. If there is an option to reinstall a package.

**Comment by yishaigalatzer** [comment]
> If  nuget install  can install package into a specific  csproj  like  Install-Package  does.

No it cannot, and would not be able to do it reliably outside of visual studio.

>  If there is an option to reinstall a package.

Same answer as the first, if it can't install, it can't upgrade. Update does try to do some of the work, but again it is not 100% reliable (for example adding references behaves differently, and it doesn't run install/uninstall scripts).

I believe we can close this issue now?

**Comment by vvavrychuk** [comment]
> I believe we can close this issue now?

Not yet since visual studio extension is not working as expected as I described originally even after cache clear. Maybe there is some conflict between "Package source" specified in combo box GUI of "Package Management Console" and `-Source` parameter.

**Comment by yishaigalatzer** [comment]
Sorry I think I confused you, the idea of update-package -reinstall is not to allow redownloading of the same package id, it is design to reinstall the package in the project, when for example the .net framework has changed.

So if you did
1. Change the package version and update-package -reinstall it, it will work
2. Uninstall the package, then install it from the source it will work.

So unfortunately this is expected. Note that nuget treats a package with the same id and version as the same, so if the package exists in your packages folder it stays there.

If we enabled what you are asking it will have some pretty undesired side effects, like the fact that the update will now apply to other projects that share the same packages folder.

Unfortunately I don't think we are going to fix it, I see why you (and me) got confused.

The best approach by the way is to just create a different version on the package and install it into the project, probably with some pre-release moniker on it. NuGet will let you do it, even if it is a dependency of something else.

**Comment by vvavrychuk** [comment]
Sorry for being annoying, but I would like to clean up one thing.

If I remove the package from `packages` folder and do

```
Update-Package MathNet.Numerics -ProjectName Sinc.Rest.Owin -Reinstall -Source C:\kom\oss\mathnet-numerics\out\packages\NuGet
```

extension will do

```
Restoring NuGet package MathNet.Numerics.3.9.0.
Adding package 'MathNet.Numerics.3.9.0' to folder 'C:\kom\sincsharp\packages'
...
```

but not from the source I specified.

**Comment by yishaigalatzer** [comment]
Not annoying at all, you are again not doing the right thing.

Update-Package for this scenario will just not work, you need to either uninstall the package then install it from the source you specified, or change the version and install it.

Here is what is happening for you:
1. You removed the package from the packages folder
2. In order for update to work, it needs to actually read the content of the package, so the first step we run before update even starts is restore (as you can see from the log). Restore obviously uses all sources available, so you get back the package you are trying to remove before update operation even starts
3. You are back to step 1, where you are with the package already there, and it just reinstalls itself in the csproj file.

**Comment by vvavrychuk** [comment]
Thanks for help!
