### ISSUE TITLE
AssemblyInformationalVersion not taken into account

### ISSUE THREAD

**Issue by FabienDehopre** [NuGet/Home#1794]
I tried what is explained here https://docs.nuget.org/create/versioning#user-content-creating-prerelease-packages but the nuget program still use the AssemblyVersionAttribute instead of the AssemblyInformationalVersionAttribute to version my nuget package.

**Comment by yishaigalatzer** [comment]
What version of nuget.exe are you using?

**Comment by FabienDehopre** [comment]
I'm using the version 3.3.0.212

**Comment by FabienDehopre** [comment]
My bad... I was using an unsupported build number with dot notation.
So I suppose that nuget switch back to using the AssemblyVersionAttribute instead of AssemblyInfermationalVersionAttribute.
Nevertheless, I think this should not be silent and at least a warning should be emitted.

**Comment by yishaigalatzer** [comment]
Openning as up for grabs, seems like a reasonable fix to take, just at a low priority.

If someone is interested in working on this issue, I would wait until we pull pack out of nuget.core

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
