### ISSUE TITLE
Packages no longer sorted by name Package Manager 3.3

### ISSUE THREAD

**Issue by kimbirkelund** [NuGet/Home#1797]

**Comment by yishaigalatzer** [comment]
Can you provide details? What command are you running, what are you comparing this to?

**Comment by kimbirkelund** [comment]
My bad, it's the Package Manager dialog, not the console.

And it appears I was totally wrong; they were sorted in the 3.2 version either.

**Comment by yishaigalatzer** [comment]
Yup, they are supposed to show up by search relevancy as determined by the server, we are tracking an ask to add sorting capabilities
