### ISSUE TITLE
Updating solution removes references

### ISSUE THREAD

**Issue by raulramaya** [NuGet/Home#1799]
Initial State:

1 solution containing 2 projects.
Both projects have package.config containing 5 references
3 of the references have updated nuget packages
2 of the references have no updated nuget packages
Using file based nuget feed
Using version 2.8.5 of nuget

Steps:

Ran restore and verified all packages existed in packages folder and were set to version specified in package.config
Ran update using:  [nuget update x.sln -Source "path to file based feed"]

Result:

Each project's package.config now contains only 2 references.
Both references are updated to latest version

Expected:

All five references to be updated if newer version exists.  If newer version does not exist, original version is maintained.

**Comment by yishaigalatzer** [comment]
This should work with NuGet 3.3 - run nuget.exe /updateself to overwrite the existing nuget 2.8.5 (although there is a minor bug in update for *.sln, that is fixed here - http://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.4.0)

Generally new version of nuget.exe are available in https://dist.nuget.org/index.html or in the nuget.commandline package on nuget.org.
