### ISSUE TITLE
Leading 0 in Package Revision Number Fails to Restore in VSTS

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1800]
_From @joshlrogers on December 1, 2015 15:27_

Starting today (12/1/2015) we are unable to restore packages during a build in VSTS that have a leading 0 in the revision number of the version.  Currently our private Nuget Packages are packaged and deployed in VSTS and have versions like 1.0.151201.01.  Starting today, we're assuming due to the recent release of the VS Update 1, it is stripping off the leading 0 of the revision number when trying to restore and thus not finding a package that maps. So for the example given it is trying to restore a package with the version 1.0.151201.1 rather than .01 and since this version doesn't exist it is failing the builds.

Our packages.config file do have the .01 in the version attribute
&lt;package id="mhd.ExternalMessaging.Contract" version="1.0.15334.05" targetFramework="net45" /&gt;

_Copied from original issue: NuGet/NuGetGallery#2797_

**Comment by emgarten** [comment]
What version does the nuspec contain?

**Comment by yishaigalatzer** [comment]
What do you mean by `deployed in VSTS` what exactly is your package server?

**Comment by joshlrogers** [comment]
@emgarten the nuspecs do contain the leading 0 so for instance .01

@yishaigalatzer VSTS does the packaging and deployment of our Nuget packages to an Azure Web App that hosts the NuGet server and packages.

**Comment by yishaigalatzer** [comment]
What kind of a server is running on that web app? We would like to figure out a repro for this...

Timing wise - I don't know that we can offer a quick fix, but I was wondering why are you using such version numbers, and can you quickly work around it, but using simple 0.1 instead?

**Comment by yishaigalatzer** [comment]
ping

**Comment by rrelyea** [comment]
@joshlrogers - I don't think you were listening to this issue. still an important issue for you? any repro help?

**Comment by emgarten** [comment]
Closing due to lack of response.
