### ISSUE TITLE
Update link for VSIX

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#1804]
![nuget-extension-info](https://cloud.githubusercontent.com/assets/4739844/11526553/8148cbc8-98db-11e5-8056-a09f847ea3e0.png)

**Comment by yishaigalatzer** [comment]
@csharpfritz can you track where this is coming from? I don't see this link in the English version at all, and we don't have any links to codeplex in the code as far as I can tell.

**Comment by csharpfritz** [comment]
I think this comes from the information submitted to the Visual Studio
extensions gallery.  I'll check into it when I get back to my office.

Jeff

**Comment by csharpfritz** [comment]
This looks like it comes from the MoreInfo element in the
source.extension.vsixmanifest file.  Is there an entry being added during
the translation process?

Jeff

**Comment by yishaigalatzer** [comment]
Apparently this comes from our localization source which is not open sourced yet (not even sure why). 
Can we update: $/DevDiv/Offcycle/WPT/NuGetVisualStudio/Main/ReferenceAssemblies/NuGet/extension.vsixlangpack

**Comment by mishra14** [comment]
Fixed in dev14: 

![capture](https://cloud.githubusercontent.com/assets/10507120/22994053/2757cfec-f37a-11e6-8987-1f539be54b02.PNG)


Not applicable in dev15 as we are a system component.
