### ISSUE TITLE
Package source is neglected when installing package?

### ISSUE THREAD

**Issue by tomkerkhove** [NuGet/Home#1805]
Hi,

I'm currently using a local NuGet repo internally that we only use. This week I've updated to the latest version and saw that I have strange behavior when installing a package.

Although I've selected my own package source it still tries to connect to the default NuGet one.
However, because I'm not connected to the internet it fails.
![Nuget Package Console](https://cloud.githubusercontent.com/assets/4345663/11529680/fa40a13c-98ee-11e5-9aec-3da02773a686.png)

When I disable the source in the settings it works.
![Nuget Package Sources](https://cloud.githubusercontent.com/assets/4345663/11529681/fa41224c-98ee-11e5-84bc-f4d739d7659c.png)

Is it possible that he ignores the selected source or something?

**Comment by yishaigalatzer** [comment]
Can you share what version of NuGet you are using? I'm guessing it is connecting to the sources to find dependencies. And in that case you should disable the source. The flag just points to where to get the top level dependency from.

We did fix a few bugs in this area, so you might want to update to 3.3 first (Can't tell if you did or didn't from the screenshots)

**Comment by tomkerkhove** [comment]
I'm currently using version 3.3 but when I specify another feed it shouldn't go to the other one, right?
Doesn't really make sense to me to be honest...

**Comment by yishaigalatzer** [comment]
The flag is a bit confusing but there is a good reason for this. Most of the time you want to update a package and it pulls newer dependencies that many a times are not on the same source.

**Comment by tomkerkhove** [comment]
I might not be following but what's the point of the `Package Source` then?

![screenshot_1](https://cloud.githubusercontent.com/assets/4345663/11555372/13103c98-99a0-11e5-8df3-3316cb598870.png)

**Comment by yishaigalatzer** [comment]
The point is that it picks the source where the primary packages you work with are being restored from. Dependencies can come from other places.

I agree it is not super clear, but considering the alternative, where it will truly restrict the operations to this one source most actions where dependencies exist will fail. The classic example is company private packages (that are typically also get updated the most)

So in that scenario companypackage is being updated from internal source, but for example it requires a new version of a dependency (say MVC), the update will fail.

Given that we believe this scenario is more common we think this is the "best" behavior in this case, and we consider adding a flag to the command restricting sources further OR you can use what you did which is disabling sources that cannot be accessed.

I'm the first to agree that this command doesn't have a very easy to understand behavior, but if you look at the range of scenarios it is used in, it is the best way (we found so far) for it to behave.

**Comment by samneirinck** [comment]
Would it be possible to check the dependencies _first_ on the selected package source, before looking for it on the other package sources?

I think that would prevent the problem.

**Comment by yishaigalatzer** [comment]
The problem is pretty complex in this case, since a dependency may exist on another source as well and we will move the problem from an error you can easily fix (and we are tracking a better experience to tell you to shutdown unreachable sources) to inconsistent behavior.

The problem space here is deceptively complex unfortunately

**Comment by yishaigalatzer** [comment]
I believe this can be now closed. Please let me know if there is anything else we want to follow up on?
