### ISSUE TITLE
Feature: Add dependencyVersion switch to command-line

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1806]
The dependencyVersion switch is available in NuGet.config, the Visual Studio UI, and Powershell experiences but is not available on the command-line for the install, update, or restore commands.

**Comment by jberezanski** [comment]
In addition to gaining a command-line argument, nuget.exe should also respect the value from NuGet.config (currently it does not).

**Comment by jacqueskang** [comment]
We are surprised to find out nuget.exe v3.5.0-beta2 doesn't take into account "dependencyVersion" specified in nuget.config, when restoring NuGet packages from project.json. Does anyone know a walk-around for this ? How can I have nuget.exe install "highestMinor" version for indirect dependencies?

**Comment by harikmenon** [comment]
@jacqueskang this is not supported in project.json. Our dependency resolution behavior is documented here https://docs.nuget.org/consume/projectjson-dependency

**Comment by jacqueskang** [comment]
@harikmenon Thanks for your rely. But in our case we want to restore latest minor version of all packages in the entire dependency graph. The floating version works perfectly for direct dependencies but since nupkg doesn't support floating version, it restores minimum version for indirect dependencies. Our project is huge and we build it by parts, and thus we are getting conflicts in the end. Do you have any suggestion please?

**Comment by harikmenon** [comment]
Adding @joelverhagen @emgarten . Do you guys have any ideas?

**Comment by joelverhagen** [comment]
Hey @jacqueskang, as @harikmenon said, this feature is not supported today on project.json.

I have created an issue to track this idea. Feel free to check this issue in the future for status: https://github.com/NuGet/Home/issues/3159.

This would definitely require a significant amount of careful design and implementation and is currently not scheduled for the next two NuGet releases.

**Comment by jacqueskang** [comment]
Thanks @joelverhagen for the clarification. I see manually lifting dependencies up to project.json is the only option for this time being. Allowing to have a similar behavior like npm would be nice in the future +1:

**Comment by billboyletrintech** [comment]
This became an issue for us while trying to use nuget for the deploy step in a CI environment where we would want nuget cli to grab the highest version of all dependencies.  I added the switch for the install command, hope thats ok.

**Comment by erick-thompson** [comment]
Is there any movement on this? We also have a process that requires that nuget.exe install the latest version of matching dependencies.

**Comment by emgarten** [comment]
Thanks @billboyletrintech and @WardenGnaw for fixing this issue! 🥇 

Merged with https://github.com/NuGet/NuGet.Client/commit/6f8d529312187fa1b6734da8d4ed9dc3442b916c

**Comment by Indomitable** [comment]
Hi, I see that this fix is only done for the Install command but in the Update command it is still hard coded to use Highest version. 
https://github.com/NuGet/Home/issues/2746
I think we should reopen this issue.

**Comment by emgarten** [comment]
@Indomitable open a new issue and PR if you would like. At this point the recommended way to run nuget operations from the command line is to move to PackageReference. 

The only complete way to update packages for a packages.config project is through Visual Studio. nuget.exe update is very limited in what it can do. Install is a bit different in that it doesn't install to the project at all.
