### ISSUE TITLE
when using UNC share package source, client cannot find package in folders that indicate package version revision is 0

### ISSUE THREAD

**Issue by mschaad** [NuGet/Home#1807]
# Description

When using the new nuget 3 file share-based package source directory layout, the client cannot find/use packages stored in directories that indicate a package revision number of 0.

e.g. if you have a package named like so: `$myPackageSource\Foo\1.0.2.0\Foo.1.0.2.0.nupkg` then the nuget client will not be able to find it or install it for you.
# Repro
## Setup
- Create an solution in VS with a C# class library.  Call both the solution and the project Foo.  
- Add a _nuget.config_ file setting up a package source called "mysource" that points to a directory we'll call _$myPackageSource_

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="mysource" value="$myPackageSource" />
  </packageSources>
</configuration>
```
- Using any method you like (perhaps using `nuget pack`), create a nuget package `Foo.nupkg` from the Foo project whose version is `1.0.2.0` (notice the trailing 0).  
- open a powershell instance and CD to the directory with the nupkg in it.
- Use the [Publish-Package cmdlet](https://gist.github.com/AArnott/45d884642684046c81cb) (NuGetPackageSources.ps1) to publish  the package.  Assuming your NuGetPackageSources.ps1 file and Foo.nupkg are in your current directory:

```
Import-Module NuGetPackageSources.ps1
Publish-Package -Path Foo.nupkg -PackageSource $myPackageSource
```
- Verify these files exist:
  - _$myPackageSource_\Foo\1.0.2.0\Foo.1.0.2.0.nupkg
  - _$myPackageSource_\Foo\1.0.2.0\Foo.nuspec 
  -  _$myPackageSource_\Foo\1.0.2.0\Foo.1.0.2.0.nupkg.sha512
- in VS, try to install the package from the PMC:

```
install-package Foo -source mysource
```
## Expected Result

The client finds the nuget package when I try to install it from the Package Manager Console and installs it into your project.
## Actual Result

In thise case, the client _will successfully discover_ the directory $myPackageSource\Foo\1.0.2.0, but then build the expected hash file name using a truncated version number like so: `$myPackageSource\ Foo\1.0.2\Foo.1.0.2.nupkg.sha512`

So package installation fails.
# Workarounds
- Rename the package folder, the nupkg file and the sha512, removing the trailing ".0" from the version part of their names, so the folder contents look like this:
  - _$myPackageSource_\Foo\1.0.2\Foo.nuspec
  - _$myPackageSource_\Foo\1.0.2\Foo.1.0.2.nupkg
  - _$myPackageSource_\Foo\1.0.2\Foo.1.0.2.nupkg.sha512
- Increment the package number to, say, `1.0.2.1` so that the nuget client can find it
- perhaps change the package number to `1.0.2` (without the trailing .0)
- fix the `Publish-Package` script so that it lops off the trailing ".0" from the package Version when constructing the folders and file names

**Comment by emgarten** [comment]
The versions used **must** be normalized according to [SemVer](http://semver.org). NuGet.exe can handle this for you with the _add_ and _init_ commands added in 3.3.0.

When using normalized versions NuGet is able to predict the exact path of the nupkg. Without this NuGet has to list the files on the share to find the package which takes much longer.

**Comment by yishaigalatzer** [comment]
I agree with Justin looks like the cmdlet is buggy, and you can use nuget.exe init or nuget.exe add instead. I'll chat with @aarnott about it, to see if we want to remove it from the blog or he can update the cmdlet

**Comment by AArnott** [comment]
For the immediate timeframe I've added a comment on my gist to suggest using nuget.exe 3.3 instead of the script. But I think we should update the blog to refer to nuget v3.3 instead of the PS script.

**Comment by mschaad** [comment]
Perhaps it's better for most folks if you recommend they use the nuget v3.3
method instead, but the PS script is still useful for TFS builds, so don't
take it down!  (Or is there an easy way to invoke _nuget add_ from a TFS
Build task that I'm missing?)

As for myself, I just modified the script to normalize the directory and
file names when copying them to the PackageSource directory, and that
solved my problem.

But, in any case, better documentation on how the nuget client actually
discovers packages would have saved me a ton of time and frustration
yesterday.  I'll happily describe the pitfalls I found if you guys can tell
me where I should send this kind of feedback.

--Matt Schaad

**Comment by yishaigalatzer** [comment]
You can definitely run nuget.exe as part of your msbuild task (even on VSO), they are going to update to 3.3 hopefully soon.

**Comment by yishaigalatzer** [comment]
And you can always submit a pull request to our documentation, it is in the nugetdocs repo

**Comment by mschaad** [comment]
Justin,
  Thanks for responding so quickly!  It's really helpful to know that nuget
expects strict adherence to SemVer.  I think it would have been helpful to
point out that fact on the blog
http://blog.nuget.org/20150922/Accelerate-Package-Source.html and in the
documentation too.
  As for the performance issue: if one doesn't supply a version number
(which is my typical use case), nuget _still *has to scan the directory.
What's puzzling about the scanning behavior to me is that nuget *notices *the
version directory, correctly *parses *the version indicated by the name of
the folder it just found (even when in the form a_.b.c.0*), but then *doesn't
actually look in *that directory for nuspec files.
  But it does work fine when the package version is of the form a.b.c.d
(where d != 0), even though semver doesn't seem to allow that.
  It was difficult to figure all that out.

--Matt

**Comment by yishaigalatzer** [comment]
I just updated the blog. Note that you can't mix the folder types, it is either the structured one with versions or the flat one. Don't try to mix them, there is no reason to do it.

The version on the name is not guaranteed to be the right one, so we have to look inside the nuspec.

**Comment by mschaad** [comment]
I discovered the hard way that you can't mix-and-match.  I was trying to
give the new convention a spin with a single package without migrating the
whole repository and disrupting my whole team.

Once I realized that trying to mix conventions actually disabled the new
convention, I put my test package in its own repo and now it works fine.

But I had to discover that through trial and error (and procmon). :-/

**Comment by yishaigalatzer** [comment]
@csharpfritz can this issue be closed, or do you plan to add more to the docs?

**Comment by csharpfritz** [comment]
Docs updated
