### ISSUE TITLE
Manager not preselecting packages

### ISSUE THREAD

**Issue by wgtmpeters** [NuGet/Home#1808]
This is about the manage solution UI.
Screenshot added in comment below.

Using the new VSIX 3.3.0 version i am having a hard time managing my packages.
In earlier version (believe i used 3.2.0 before) it would preselect packages when i for example select the Update action and a version.
This worked for all actions and versions. In the new manager 
it seems to not do any of these preselections.
It simply remember which selection you made previously, even when moving to other packages, the same projects are selected as targets for installation.

Which is pretty annoying when you want to update or downgrade a package to a certain version.
- Please preselect packages when selecting any Version, just pre select the packages that have a version installed.
- Please move the Installed and version dropdown lists with its button to the top of the UI, why do i need to scroll down every time. As the list of projects the package could be installed in could be pretty large, usually you need to scroll to make your selection.
- Scrolling in the list of projects is not working correctly, it only scrolls when the mouse is on the scroller itself.
- To me it looks like the font size is really large, for most of my packages i cannot see its full name and version in for example the browse tab.
- It also seems to be quit a bit slower then 3.2.0, takes a long time to finally show the updates and consolidate tabs (x ) .

Basicly missing this functionality makes 3.3.0 unusable at the moment. Even though it has some fun new features like the update all button.

**Comment by csharpfritz** [comment]
Can you share a screenshot of your NuGet UI so that we can see what you are looking at?  Its not clear to me what problems you are having

**Comment by wgtmpeters** [comment]
![vsix_solution_manage](https://cloud.githubusercontent.com/assets/5174293/11563443/35ead8d4-99d4-11e5-8143-769cdc0c5a0d.png)

**Comment by yishaigalatzer** [comment]
We got similar feedback offline - Adding some of my thoughts below (and customer images)

> - Please preselect packages when selecting any Version, just pre select the packages that have a version installed.
>   This seems to be repeating feedback, the current design was to enable users to work on a consistent set of projects and install and update packages into them. We probably have to rethink and see how we support both scenarios.
> - Please move the Installed and version dropdown lists with its button to the top of the UI, why do i need to scroll down every time. As the list of projects the package could be installed in could be pretty large, usually you need to scroll to make your selection.

We already planned to limit the size of the list instead, so the location is always the same. We can take a look at your suggestion as well, when we prototype the next iteration and see which one works better (and consistent with the rest of the UI).

> - Scrolling in the list of projects is not working correctly, it only scrolls when the mouse is on the scroller itself.

Yes

> - To me it looks like the font size is really large, for most of my packages i cannot see its full name and version in for example the browse tab.

We can take a look at the font size, the current size seemed appropriate, perhaps you changed the default environment font?

> - It also seems to be quit a bit slower then 3.2.0, takes a long time to finally show the updates and consolidate tabs (x ) .

It is now running in the background, it is a bit faster than 3.2 actually, we do plan to speed it up further in 3.4.

> Basically missing this functionality makes 3.3.0 unusable at the moment. Even though it has some fun new features like the update all button.

You can sort by version, so it makes it easier to select the packages you need and you don't have to spend a lot of time scrolling. At the same time we see your point and we plan to work on it before the next release.

Additional feedback:
We want to be able to multi select multiple projects after sorting

![image](https://cloud.githubusercontent.com/assets/1238711/11641813/39f66128-9cef-11e5-9e76-f0c66144fd5e.png)

**Comment by feiling** [comment]
Nuget now auto selects projects when user is in the "Consolidated" tab or the "Updates Available" tab.
