### ISSUE TITLE
Protocol documentation for NuGet v3 is missing

### ISSUE THREAD

**Issue by niklaslundberg** [NuGet/Home#1809]
I cannot find any documentation anywhere for the NuGet v3 protocol. I want to learn about endpoints that are known by both the server and the client, their purpose, their paths, HTTP methods, HTTP headers, query string parameters and so on. I can read the source code of course but then it's an implementation rather than a specification.

**Comment by yishaigalatzer** [comment]
Moved to the gallery repo https://github.com/NuGet/NuGetGallery/issues/2801
