### ISSUE TITLE
Network request failure failed restore when all packages were present

### ISSUE THREAD

**Issue by pawchen** [NuGet/Home#1810]
From [roslyn/#7176](https://github.com/dotnet/roslyn/pull/7176#issuecomment-161506061), when I tried to build roslyn locally and I was sure all packages were present(did it once before). So I cut the network(metered), walked away and did something else, only to find build failed because nuget failed to talk to network when I was back.

cc @jasonmalinowski

**Comment by yishaigalatzer** [comment]
Even if you have all the packages, there are scenarios where we still need to talk to the network. You really want to override the pacakge sources in this scenario and go straight to a local feed instead (use the nuget init command to set an efficient one up).

As this seems like a relatively low priority fix, we could look at improving this scenario, but it will be a pretty big help if you can share a repro scenario (what packages do you have locally, the specific commit hash of roslyn, and the feed setup)

**Comment by jasonmalinowski** [comment]
Which scenarios are those? We aren't doing floating versions in Roslyn, so that's not @diryboy's problem.

**Comment by yishaigalatzer** [comment]
One thing I can think of is if a package dependency available is not an exact match

Example:

Graph:
PackageA -> PackageB 1.0

Feed:
PackageA 1.0
packageB 1.1

Restore will find 1.1, but will keep looking for 1.0 on subsequent restores.

**Comment by pawchen** [comment]
This is the hash I was building atop https://github.com/dotnet/roslyn/commit/4f165b43f7c43287aa1a2ab69132d1f97d965552
1. Download the zip drop from https://dotnetci.blob.core.windows.net/roslyn/nuget.35.zip and extracted to %userprofile%
2. Run `nuget restore Roslyn.sln`
3. Cut network
4. Run `cibuild /restore`

**Comment by yishaigalatzer** [comment]
I don't understand step 2 + step 4. If you already run restore in step 2, why do you run it again in step 4?

**Comment by pawchen** [comment]
This is an existing script provided in the repo, lazy to write another then mask local changes in git when commit, at the time I used it, I did not expect it to use network again.

**Comment by yishaigalatzer** [comment]
The real answer here is that you can't 100% rely on restore to work based on the fact that you have the packages in the folder. The restore process might require additional packages that are not actually referenced at the end (known as intermediate packages).

The realistic answer to solve this problem is to add a local feed (and remove remote feeds) when restoring offline. We are thinking about ideas to improve this scenario (Where we can automatically create such a feed/feeds during restore for you)

So something like `restore x.sln -outputFeedRoot c:\newtempfeed`

**Comment by pawchen** [comment]
Could I achieve this without modifying upstream script/config?

**Comment by yishaigalatzer** [comment]
I don't think you can reliably do it unless you run the build steps without restore

**Comment by pawchen** [comment]
Thanks @yishaigalatzer.

@jasonmalinowski Looks like we still want to add a /norestore switch.

**Comment by yishaigalatzer** [comment]
@diryboy coming back very late to the discussion. You can restore with a -configfile parameter and provide the packages folders as the only source or with --ignore-failed-sources

**Comment by pawchen** [comment]
Thanks for the idea @yishaigalatzer. This issue is not that significant for me now than it was. It's up to you to decide whether this issue can be closed.
