### ISSUE TITLE
Add ability to "-Reinstall" a package from the NuGet Package Manage UI

### ISSUE THREAD

**Issue by johnegbert** [NuGet/Home#1812]
There are times when a projects references get messed up and are pointing to a dll in the bin instead of the same dll under the /packages/... folder. Or for other reasons the project/packages/file get into a dirty state and the easiest way to fix it is ReInstalling the package

Update-Package PackageName -Reinstall

Can you please add a way to select one or more installed nuget packages and "-Reinstall" them.
Thanks
John

**Comment by yishaigalatzer** [comment]
The concern I have with this is that moving it to the UI makes it too visible and it is not a very common operation. Hence my knee jerk reaction to this ask, is to not add it, and let the power shell console be the way to keep doing it (you can also uninstall and then reinstall the package from the UI, which is very similar).

But before making any determination, I'd like to hear some more of why you think it should surface that high?

**Comment by yishaigalatzer** [comment]
I'm moving this to the discussions milestone, I'd like to gather more feedback before determining what do to about it

**Comment by Jonathan34** [comment]
Or at least provide a way to do this from a prebuild step in visual studio?

**Comment by yishaigalatzer** [comment]
@jonathan34 can you elaborate why you want this in a build step?

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
