### ISSUE TITLE
MSBuild outputs unnecesary message about BeforeGenerateProjectPriFile tagert

### ISSUE THREAD

**Issue by jozefizso** [NuGet/Home#1814]
After upgrading to Visual Studio 2015 Update 1, out build servers started to output this message during builds of our solutions. We have C# and C++ projects in our solutions.

```
The target "BeforeGenerateProjectPriFile" listed in a BeforeTargets attribute at "C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets (186,61)" does not exist in the project, and will be ignored.
```

This message appears in the output several times. We use automatic package restore and does not reference `Microsoft.NuGet.targets` directly.
We build solution with the `msbuild.exe Solution.sln /t:Build` command and this message is echoed as normal level message.

**Comment by yishaigalatzer** [comment]
@jozefizso looking into it. Thanks for bringing it up

**Comment by jasonmalinowski** [comment]
This is just our build conditions mentioning something that's not always there. I admit this is annoying, but it's at least harmless.

**Comment by cspeirs** [comment]
The messages appear to be less than harmless actually.

Projects build with treat warnings as error.  Projects compile just fine using the VS 2015 environment.  Now building via MSBuild, all projects that have the message above are marked as Failed.

**Comment by jasonmalinowski** [comment]
Which warning as error flag? I wouldn't expect that MSBuild would consider this to be a warning. If it is, that's a second bug.
