### ISSUE TITLE
C++ project getting 'Solution is not saved. Please save your solution before managing NuGet package'

### ISSUE THREAD

**Issue by Eilon** [NuGet/Home#1815]
I'm getting an error in the Error List in VS: `Solution is not saved. Please save your solution before managing NuGet package`.

My project is a VCXPROJ (C++) and I opened the project directly, and not via the solution (that is, there's no solution file at all).

I'm using the latest public NuGet in VS2015: 3.3.0.167 (I was previously using 3.2.x and had the same error).

I can share a repro project internally but not publicly because it's a non-public project.

**Comment by Eilon** [comment]
@yishaigalatzer I internally sent you the repro project.

**Comment by zhili1208** [comment]
@yishaigalatzer I repro this, the problem is there is no solution file there, we always do solution check before open nuget.
I think we don't support no solution scenario, nuget always use solution folder as root, if there is no solution file, where nuget should put packages folder?

**Comment by yishaigalatzer** [comment]
The error happens when opening the project, right? Why would we error then?

**Comment by zhili1208** [comment]
I didn't get error during opening the project, got the error during opening nuget UI.

**Comment by yishaigalatzer** [comment]
Like we have seen, we get the error during build, this error should go away. @Eilon did you see something else?

**Comment by Eilon** [comment]
I don't recall if I saw it right when opening the project, or when attempting to build. But either way the error is wrong.

**Comment by chucklu** [comment]
I encounter this problem in C# project
I tried to use NuGet,using NuGet Package Explorer
then I get this file .nupkg

but now, I do not want to use NuGet,
and I have deleted the .nupkg file
when I try to build the project

I get this wrong info "Solution is not saved. Please save your solution before managing NuGet package."
actually,I think this project have nothing to do with NuGet

**Comment by yishaigalatzer** [comment]
Don't forget to delete the packages.config and remove the references

Sent from my Windows Phone

**Comment by chucklu** [comment]
@yishaigalatzer there is no packages.config under my project
I have a class library,I try to publish this dll to local
and I can not make it,so I do not want to use NuGet

Is there something to do to remove the warning info

**Comment by yishaigalatzer** [comment]
Can you try closing the solution and verifying you are on nuget 3.3 and that there is no packages.config and your solution is saved?

**Comment by chucklu** [comment]
I uninstalled the NuGet,then the warning disappeared

what's  the difference between NuGet Package Explorer and NuGet in VS2015(Extension and Updates)

**Comment by chucklu** [comment]
try to reinstall the NuGet in VS2015，Under Tools-->Extension and Updates
rebuild the project again,
I still get the same warning info

why?I just want to build my own project,

**Comment by yishaigalatzer** [comment]
Can you share the file list under your solution?

**Comment by chucklu** [comment]
$ ls -al
total 13
drwxr-xr-x   13 Administ Administ     4096 Jan 27 11:04 .
drwxr-xr-x   17 Administ Administ     4096 Jan 27 10:32 ..
-rw-r--r--    1 Administ Administ       36 Jan 26 16:03 .gitignore
drwxr-xr-x    3 Administ Administ        0 Jan 27 10:33 .vs
-rw-r--r--    1 Administ Administ     2454 Jan 26 16:54 ExceptionLog.cs
-rw-r--r--    1 Administ Administ     3121 Jan 26 16:54 FileLog.cs
-rw-r--r--    1 Administ Administ     2134 Jan 27 09:14 Log.cs
-rw-r--r--    1 Administ Administ     2448 Jan 27 10:59 Log.csproj
-rw-r--r--    1 Administ Administ      165 Jan 26 16:54 LogType.cs
-rw-r--r--    1 Administ Administ     1432 Jan 27 09:14 OperationLog.cs
drwxr-xr-x    3 Administ Administ        0 Jan 27 10:33 Properties
drwxr-xr-x    3 Administ Administ        0 Jan 27 10:33 bin
drwxr-xr-x    3 Administ Administ        0 Jan 27 10:33 obj

**Comment by yishaigalatzer** [comment]
That doesn't look like windows, c++ or a solution level file list can you elaborate?

**Comment by chucklu** [comment]
it's C# project，there is no solution
just a single project

**Comment by yishaigalatzer** [comment]
I believe this bug was fixed in the next release. For now save a solution file to work around the issue

**Comment by chucklu** [comment]
ok,thank you

**Comment by Trafalgar-D-Law** [comment]
I also met this question, and I has solved this question.
Here are what I did.
1.Open the project in VS;
2.Press F5 to run it;
3.Close the VS, and it will ask you if save solution, select yes;
4.reopen the project（*.sln）, and the question is solved.

**Comment by artunltd** [comment]
@Trafalgar-D-Law, thank you)
