### ISSUE TITLE
NuGet 3.3.0 update fails with 'An additional constraint ... defined in packages.config prevents this operation.'

### ISSUE THREAD

**Issue by paiden** [NuGet/Home#1816]
I tried to switch from NuGet 2.8.60717.93 to 3.3.0.212. 

As soon as I do this my build starts to fail with the following error message:
`Attempting to gather dependencies information for multiple packages with respect to project 'ProjectName'. Unable to resolve 'PackageName'. An additional constraint '(≥ 5.4.0 && < 5.4.5)' defined in packages.config prevents this operation.`

The command that causes the error message is:
`NuGet.exe update Project.csproj -configFile .nuget\NuGet.config -id PackageId -RepositoryPath packages`

The feed in use definitely contains a package version that satisfies the constraint. 

I just need to switch back to the old NuGet version and everything works as expected.

**Comment by emgarten** [comment]
What version of the package is installed and what versions are available on the feed?
Does the feed show up in the list when running _nuget.exe sources_ ?

**Comment by paiden** [comment]
> What version of the package is installed and what versions are available on the feed?

The installed version is 5.4.3.26485 (which is the highest available version within the constraint)
This is an internal package on a internal feed and there are about 25 package versions that satisfy the constraint.

> Does the feed show up in the list when running nuget.exe sources ?

When I run `nuget sources -configFile '.nuget\NuGet.config'` the feed shows up and is enabled.

**Comment by emgarten** [comment]
Sounds like a bug. With 2.8.6 the same command results in no operations being performed, correct?

**Comment by yishaigalatzer** [comment]
Are you able to provide a small repro project for this issue?

**Comment by paiden** [comment]
> With 2.8.6 the same command results in no operations being performed, correct?

Only on my local system no operations are performed. E.g. on the build server, the package always gets updated (from 0.0.0.0; please don't ask why we do such things ;-) ) correctly (as the build folder is always cleaned).

> Are you able to provide a small repro project for this issue?

I will try to try to create a small repro project. As I'm quite busy at the moment and I don't know how easy it is to repro it with a small example (the project where the issue happens has 100+ projects with many NuGet packages served via multiple feeds) it may take some time.

**Comment by paiden** [comment]
I finally found the time to investigate the issue. It seems the problematic code is in NuGetPackageManager.cs around line 709.

``` C#
prunedAvailablePackages = PrunePackageTree.PruneByUpdateConstraints(prunedAvailablePackages, projectInstalledPackageReferences, resolutionContext.VersionConstraints);

// Remove all but the highest packages that are of the same Id as a specified packageId
if (packageId != null)
{
    prunedAvailablePackages = PrunePackageTree.PruneAllButHighest(prunedAvailablePackages, packageId);

    // And then verify that the installed package is not already of a higher version - this check here ensures the user get's the right error message
    GatherExceptionHelpers.ThrowIfNewerVersionAlreadyReferenced(packageId, projectInstalledPackageReferences, prunedAvailablePackages);
}
```

The line 

``` C#
prunedAvailablePackages = PrunePackageTree.PruneAllButHighest(prunedAvailablePackages, packageId);
```

removes the valid packages from the list. Only a newer package that doesn't satisfy the constraint in my case 6.X.X.X is left and therefore causes the error.

So it seems 'PruneByUpdateConstraints' returns packages that don't satisfy the constraint, even if it shouldn't (as far as I can tell).

A small project to repro the issue can be found at: http://1drv.ms/1OKt3OX

**Comment by yishaigalatzer** [comment]
We are running out of time for 3.4, John can you please start looking at the Update issues for 3.5?
