### ISSUE TITLE
Support space in paths

### ISSUE THREAD

**Issue by Liero** [NuGet/Home#1818]
Please, make sure this test case works:

```
"C:\My Projects\nuget.exe" pack "C:\My Projects\package.nuspec" -OutputDirectory "C:\My Projects\Output\" -prop "RootDir=C:\My Projects\"
```

package.nuspec:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
<metadata>
    <id>Package</id>
    <version>1.0.0</version>
    <authors>daniel.turan</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>RootDir=$RootDir$</description>
</metadata>
<files>
    <file src="$RootDir$package.nuspec" target="ContentFile.txt" />
</files>
</package>
```

I'm aware of two issues when paths contains space:
1. -OutputDirectory cannot end with `\`. This makes it difficult to use with msbuild, where path variables usually ends with `\`.
   
   e.g this works: `-OutputDirectory "C:\My Projects\Output"` but this doesn't  `-OutputDirectory "C:\My Projects\Output\"`
2. if there is just one property (replacementtoken) defined by -prop and it contains space, it does not work when `;` is missing at the end.
   
   e.g this works: `-prop "RootDir=C:\My Projects\;"` but this doesn't `-prop "RootDir=C:\My Projects\"`

**Comment by yishaigalatzer** [comment]
Thanks this is good feedback, a great sample and sound analysis.

Since I don't see us jumping on this right away (given the current open items), I'm moving this to the next milestone (which I expect to be sometime mid next year). 

We would love to take a pull request if this is a blocking issue for you (or anyone else) to accelerate fixing this issue.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by OliverRC** [comment]
?? This is kinda mad that Nuget does not support file paths with spaces!

**Comment by Liero** [comment]
@OliverRC: it does work, but there are some gotchas, see points 1. and 2. in my original comment
