### ISSUE TITLE
Error installing packages with NuGet 2.8 for VS 2013

### ISSUE THREAD

**Issue by vrsanthosh83** [NuGet/Home#1819]
Getting below are error

---

12/9/2015 11:23:33 AM - Microsoft VSIX Installer
12/9/2015 11:23:33 AM - -------------------------------------------
12/9/2015 11:23:33 AM - Initializing Install...
12/9/2015 11:23:33 AM - Extension Details...
12/9/2015 11:23:33 AM -     Identifier      : NuGet.67e54e40-0ae3-42c5-a949-fddf5739e6a5
12/9/2015 11:23:33 AM -     Name            : NuGet Package Manager for Visual Studio 2013
12/9/2015 11:23:33 AM -     Author          : Microsoft Corporation
12/9/2015 11:23:33 AM -     Version         : 2.8.60723.765
12/9/2015 11:23:33 AM -     Description     : A collection of tools to automate the process of downloading, installing, upgrading, configuring, and removing packages from a VS Project.
12/9/2015 11:23:33 AM -     Locale          : en-US
12/9/2015 11:23:33 AM -     MoreInfoURL     : http://docs.nuget.org/
12/9/2015 11:23:33 AM -     InstalledByMSI  : False
12/9/2015 11:23:33 AM -     SupportedFrameworkVersionRange : [4.0,4.5]
12/9/2015 11:23:33 AM - 
12/9/2015 11:23:34 AM -     SignedBy        : Microsoft Corporation
12/9/2015 11:23:34 AM -     Certificate Info : [Subject]
  CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Issuer]
  CN=Microsoft Code Signing PCA, O=Microsoft Corporation, L=Redmond, S=Washington, C=US

[Serial Number]
  33000000FEEB02CCACAAEB9F780001000000FE

[Not Before]
  5/20/2015 1:30:50 PM

[Not After]
  8/20/2016 1:30:50 PM

[Thumbprint]
  3FF2B5272DA04778A97B10E39F2AE1774ABF0E25

12/9/2015 11:23:34 AM -     Supported Products : 
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.Pro
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.IntegratedShell
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.VWDExpress
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.VPDExpress
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.VSWinExpress
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM -         Microsoft.VisualStudio.VSWinDesktopExpress
12/9/2015 11:23:34 AM -             Version : [12.0]
12/9/2015 11:23:34 AM - 
12/9/2015 11:23:34 AM -     References      : 
12/9/2015 11:23:34 AM - 
12/9/2015 11:23:35 AM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.exe: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
12/9/2015 11:23:35 AM - System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.GetScopePaths(String applicationPath, String suffixOrName, String vsVersion, Boolean isLogged, Boolean isForIsolatedApplication)
   at Microsoft.VisualStudio.Settings.ExternalSettingsManager.CreateForApplication(String applicationPath)
   at VSIXInstaller.App.GetExtensionManager(SupportedVSSKU sku)
   at VSIXInstaller.App.GetExtensionManagerForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by yishaigalatzer** [comment]
> Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.exe: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

Looks like you are trying to install nuget for SSMS and not visual studio 2013, I don't believe we support this scenario
