### ISSUE TITLE
NuGet.Configuration: Active package source on local nuget.config file is not get honored

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#182]
Repro steps:
1. create a new project
2. place a local nuget.config file near the solution with the content below:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
     <packageRestore>
      <add key="enabled" value="True" />
        <add key="automatic" value="True" />
      </packageRestore>
      <packageSources>
        <add key="remote" value="c:\packages" />
      </packageSources>
      <disabledPackageSources />
       <activePackageSource>
        <add key="remote" value="c:\packages" />
      </activePackageSource>
      <config>
        <add key="repositorypath" value="C:\Temp" />
      </config>
    </configuration>

3. start package manager UI or powershell console

Expected: active package source is remote or c:\packages

Actual: active package source is still using the one from machine-level NuGet.Config under %appdata%

**Comment by zhili1208** [comment]
active package source on local nuget.config is get honored, the issue is it's not updated to UI or powershell, same issue as https://github.com/NuGet/Home/issues/303
