### ISSUE TITLE
NuGet.config settings UI to represent hierarchy of config files -- Design Discussion

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#1820]
https://github.com/NuGet/Home/wiki/Ideas-about-NuGet-Hierarchical-Setting

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/5321 needs to be considered when this is being done as well.

**Comment by nkolev92** [comment]
This one is older, but https://github.com/NuGet/Home/issues/7973 has more details.
