### ISSUE TITLE
Visual Studio hangs when opening a solution

### ISSUE THREAD

**Issue by jmezach** [NuGet/Home#1824]
We just ran into an issue that occurs when we open a solution in Visual Studio that contains NuGet packages that have PowerShell scripts. If one of the Init scripts writes something to the Package Manager Console (for instance a warning about unapproved verbs), Visual Studio will hang when the solution is being opened.

We can consistently reproduce the issue with a particular solution, although other solutions open just fine even though they have the same packages installed, so it doesn't seem to happen all the time. Also, closing the Package Manager Console window in Visual Studio seems to avoid the issue.

**Comment by yishaigalatzer** [comment]
Can you share what version of visual studio this happens in, and a sample where the hang occurs?

In general the nature of these scripts is that they can hang visual studio or even crash it, because they run in the context of the host application. I'm not sure what going on here, so please treat it as a general statement, we would appreciate a repro solution first is possible

**Comment by yishaigalatzer** [comment]
Also can you update NuGet to 3.3, we did fix a hanging issue in the powershell console (when writing with colors) so it _might_ be related

**Comment by jmezach** [comment]
I think it started with Visual Studio 2015 Update 1. As far as I know it worked without problems without Update 1. Color output might be related though since the warning I know was being raised was written in yellow. We worked around it by removing the warning for now.

I believe VS 2015 Update 1 already includes NuGet 3.3 right? I'll have a look at a repro, though I'm a bit short on time at the moment.

**Comment by rrelyea** [comment]
@jmezach - would love to know if this still repros with 3.4.4 and VS Update 2.

**Comment by rrelyea** [comment]
Community - let us know if you hit this issue. latest nuget version for VS 2015 is 3.5.0 -- available from http://nuget.org/downloads
