### ISSUE TITLE
ContentFiles feature is not extensible

### ISSUE THREAD

**Issue by drieseng** [NuGet/Home#1825]
The ContentFiles feature only provides specific support for adding content to c# and vb projects (with fallback to the "any" folder for other language projects).

Why wasn't value of the (MSBuild) **Language** property used to determine the folder name from which to add files ?
This way any language project could be supported.
The folder names would then just have to match the value of that property.
For example:
- **C#** for C# projects
- **VB** for VB.NET projects
- **F#** for F# projects
  ...

**Comment by yishaigalatzer** [comment]
The feature is actually extensible, because that portion is done outside of NuGet by the msbuild task. and the intent it support more than just language (e.g. support specific language versions like CS6 if that need ever arises).

I think your suggestion makes sense, and I'm adding the owner of the msbuild task, to see if we can update it.

Since F# is not yet officially supported (but it will) this is a very good point to consider.

CC @pilchie @jasonmalinowski

**Comment by Pilchie** [comment]
Looking at the code, it already does use the msbuild `Language` property, it just maps C# to `cs` and F# to `fs`.

@jasonmalinowski would have to comment on why the rename happens, but my expectation is around concerns with path escaping.

**Comment by jasonmalinowski** [comment]
@emgarten was the one who gave me the spec, so he'll know why we chose the names. I assume that's because we probably don't want # in the file names though...strange stuff might happen.

**Comment by emgarten** [comment]
I believe we were going by the file extensions when deciding on the package folder paths. It could have gone either way. To keep things consistent we've been using: cs, fs, vb

**Comment by drieseng** [comment]
I'm not sure but I don't think having a # in file or folder names would be a problem.

Using the file extension of the source files for a given project language as the folder name, in which you have to put files that you want to add to such projects, is perhaps not the most intuitive. Personally I would surely prefer **C#** over **cs**, as the former makes me think of C# as a language while the latter for me only refers to the C# source files.

That said, I mostly care about whether or not the MSBuild task would have to be modified to support a given project language. If the value of the **Language** property is used, then this would definitely not be necessary.

Can anyone point me to the class where the mapping between a given project language and the expected (contentFiles) folder name is done ? Thx

**Comment by Pilchie** [comment]
Sadly, not yet, because the code isn't OSS yet, but we are working on it. It does fall back to Language for all languages except C# and F#.

**Comment by jasonmalinowski** [comment]
The code's available now, so the mapping is defined [here in the build task](https://github.com/NuGet/NuGet.BuildTasks/blob/6d5532276ed05781421e33572bc7602d4c7b7f2d/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L524).

**Comment by jasonmalinowski** [comment]
@drieseng: let us know if you need anything else here; the code is now open so you can see how the mapping is done.

**Comment by drieseng** [comment]
I would've expected at least feedback on PR #437.
But I still have hope that one will be accepted :p

**Comment by jasonmalinowski** [comment]
@drieseng: I believe that was the wrong number?

**Comment by drieseng** [comment]
It's the right number, but GitHub links it to an issue instead of a PR.
This is the PR (also see above):
https://github.com/NuGet/NuGetDocs/pull/437

**Comment by yishaigalatzer** [comment]
thanks! merged the PR
