### ISSUE TITLE
Is there an API into the NuGet.org datawarehouse?

### ISSUE THREAD

**Issue by dkackman** [NuGet/Home#1829]
I am trying to get at the data from the NuGet gallery that would show package usage statistics. (Downloads over time, NuGet action per download etc.)

There is the NuGet data warehouse project but I do not see any API to access the nugget.org instance, so I'm assuming that it is purely to drive what is shown on the gallery website.

Is there an API other than https://api-v3search-0.nuget.org/query or the older https://nuget.org/api/v2 OData feed that can be used to get at NuGet.org package stats?

**Comment by yishaigalatzer** [comment]
moved to https://github.com/NuGet/NuGetGallery/issues/2810
