### ISSUE TITLE
Update-Package command removes dependency details

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1832]
Given a project.json file with this dependency:

``` json
{
  "dependencies": {
    "ReadOnlySourceTree": {
      "version": "0.1.17-beta-gf0bddac335",
      "suppressParent": "none"
    }
  }
}
```

When I run the `Update-Package ReadOnlySourceTree -Pre` command, the json file becomes this:

``` json
{
  "dependencies": {
    "ReadOnlySourceTree": "0.1.21-beta"
  }
}
```

Note how the `suppressParent` field is removed. This is a significant change, and reverts what I had explicitly placed there without warning.

**Comment by emgarten** [comment]
This has been fixed with PackageReference.
