### ISSUE TITLE
'nuget pack' ignores .nuspec's <file> elements sourced from $(UserProfile)\.nuget\packages

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#1833]
It seems nuget pack quietly drops (without warning or error) all files from being packaged if they're src'd from `$(UserProfile)\.nuget\packages\...` This took me a couple hours to figure out, and now I have to invent some temporary location to have my build copy files to just to keep it from ignoring them.

I'm building a package with a tools folder, so obviously all runtime components required during the build have to be directly embedded (since NuGet has no means for one package depending on another package for purposes of a build "runtime" time dependency). 

It would sure be nice if "nuget pack" emitted a warning to the effect to make this more discoverable, or (better yet, IMO) didn't ignore these files.

**Comment by emgarten** [comment]
It looks like this is due to the dot at the beginning of the folder name. Pack excludes these by default. To allow them use `-NoDefaultExcludes`

See: https://docs.nuget.org/consume/command-line-reference

**Comment by AArnott** [comment]
Thanks, @Emgarten. That's a much easier workaround than copying the files around to other directories.
