### ISSUE TITLE
Dependent packages not showing in References and project.json in UWP. Is it a new behaviour?

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1834]
_From @mathikp on September 9, 2015 7:9_

In UWP projects, when we installing a NuGet, the dependency packages of the NuGet is not showing in References node in Solution Explorer and also there is no entry in project.json file. Whether it is an issue or not?

_Copied from original issue: NuGet/NuGetGallery#2667_

**Comment by maartenba** [comment]
_From @emgarten on September 9, 2015 7:30_

Would you provide some repro steps for this? 

Is the install failing and rolling back?

**Comment by maartenba** [comment]
_From @mathikp on September 9, 2015 10:59_

I have add dependencies properly. List of dependencies are showing correctly in VS2015's NuGet Package Manager. And after installed its successfully restored to the .nuget/packages folder. But the issue is, the dependency NuGet packages are not showing in the References node in Solution Explorer and entry is not adding in project.json file after installed. Its not showing any error in installation log.

**Comment by maartenba** [comment]
_From @emgarten on September 9, 2015 19:4_

Please provide steps that can be used to reproduce this issue.
Example: project type, package installed, steps used to install the package.

**Comment by maartenba** [comment]
_From @mathikp on September 10, 2015 4:59_

1.Created 2 packages with "lib/netcore46" folder named A and B. In A's nuspec file I had added B as a dependency. I have configured the NuGet in Visual Studio 2015. 
2.Created Universal Windows blank app. Opened Tools->NuGet Pakckage Manager->Manage packages for this solution. 
3.Selected my package source and selected package A.
4.B is showed as dependency in the right pane of NuGet Package Manager.
5.Installed A. Its installed successfully. 
6.A is added to project.json and under References node in Solution Explorer. But B is not showing in Solution Explorer and not added in project.json.

But A and B are available in .nuget/packages location. Why?

**Comment by maartenba** [comment]
_From @emgarten on September 10, 2015 5:39_

Dependencies are not added to project.json, only the top level package. In solution explorer you can find B by expanding A.

Btw, it doesn't affect your scenario but netcore46 is not a valid target framework. If you are trying to target UWP use uap10.0.

**Comment by maartenba** [comment]
_From @ratishphilip on December 9, 2015 15:23_

I am facing a similar issue.
I have created a Class Library for Universal Windows App and want to publish it as a NuGet package.

My library has a dependency on Microsoft.Xaml.Behaviors.Uwp.Managed.

I created the spec file for the project using NuGet and mentioned the dependency as follows
&lt;dependencies&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;dependency id="Microsoft.Xaml.Behaviors.Uwp.Managed" version="1.0.3" /&gt;
&lt;/dependencies&gt;

Then I used the nuget pack command to create the .nupkg file.

When I am adding this .nupkg  file to another Universal app (using the Nuget Package manager), it correctly lists its dependency on Microsoft.Xaml.Behaviors.Uwp.Managed.

But when I install the .nupkg, the dependency (Microsoft.Xaml.Behaviors.Uwp.Managed) is not installed (it does not show in the References in the Solution Explorer) which creates a build issue.

How to resolve this issue and make nuget install the dependencies automatically.

I am using Visual Studio 2015 Update 1.

**Comment by maartenba** [comment]
_From @davidfowl on December 9, 2015 16:52_

@ratishphilip The solution explorer only shows top level dependencies in uwp projects. That doesn't have any effect on the build.

**Comment by maartenba** [comment]
_From @ratishphilip on December 9, 2015 17:58_

@davidfowl Thanks for the reply. I found out what the issue was. While creating the nuget package, the default configuration was set to **Release|AnyCPU**. I think _Microsoft.Xaml.Behaviors.Uwp.Managed_ does not work with **AnyCPU** configuration. Setting the default configuration to **Release|x64** solved the issue. Now while installing the package, it shows that _Microsoft.Xaml.Behaviors.Uwp.Managed_ is also being installed.

![nuget_dep](https://cloud.githubusercontent.com/assets/7021835/11693693/2c0634b8-9e5b-11e5-9294-abb44f3cc618.png)

However, it does not show up in the Project References in the Solution Explorer. It builds successfully though.
![nuget_dep2](https://cloud.githubusercontent.com/assets/7021835/11693744/6cfb83d8-9e5b-11e5-8355-e7c3ca1ce460.png)

**Comment by yishaigalatzer** [comment]
@jasonmalinowski this seems to fall in your area.

@ratishphilip can you point to your package?

**Comment by ratishphilip** [comment]
@yishaigalatzer @jasonmalinowski  My package is not available in NuGet. I just made a sample package locally(SampleBehaviorLib which has a reference to **Microsoft.Xaml.Behaviors.Uwp.Managed**) and tried to add that package to another project (SampleBehaviorClient)

**Comment by yishaigalatzer** [comment]
Would you mind pushing it to myget or make it available for us to debug it?

**Comment by ratishphilip** [comment]
[NugetSample.txt](https://github.com/NuGet/Home/files/61885/NugetSample.txt)
Please rename the file to **NugetSample.zip**
I have included the nuget package and the source code for the SampleBehaviorLib and SampleBehaviorClient

**Comment by yishaigalatzer** [comment]
CC @pilchie

**Comment by Pilchie** [comment]
Yes, it is expected that only top level decencies are shown when you have a .csproj using project.json. We hope to unify the presentation with ASP.NET v5 at some point in the future.

**Comment by ratishphilip** [comment]
Thank you all for your clarification.
I have another question (related to NuGet packaging but not related to this issue). Is there any documentation on how to create a NuGet package for UWP applications which contains x86, x64 and ARM binaries and loads the appropriate binary based on the build configuration of the client using this NuGet package.
I tried following the instructions specified in http://dontcodetired.com/blog/post/Creating-a-Windows-Store-App-NuGet-Package-for-ARM-x86-and-x64.aspx
but I get the following error in the client (when I build for any target except x86 which is the default target in the **/lib** folder)
_1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1151,5): error APPX1101:_**Payload contains two or more files with the same destination path 'SampleBehaviorLib.dll'**_. Source files: 
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1151,5): error APPX1101: C:\Users\Guest01.nuget\packages\SampleBehaviorLib\1.0.8\lib\uap10.0\SampleBehaviorLib.dll
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1151,5): error APPX1101: C:\Users\Guest01.nuget\packages\SampleBehaviorLib\1.0.8\build\uap10.0\x64\SampleBehaviorLib.dll_

 I am using the same source projects (SampleBehaviorLib and SampleBehaviorClient) which I uploaded earlier.

**Comment by yishaigalatzer** [comment]
Follow this guide instead - https://docs.nuget.org/create/uwp-create

**Comment by ratishphilip** [comment]
Yes, I went through this guide to and added the uap10.0 TxM to the package. But it still is not working and giving me the same error.

[SampleBehaviorLib.targets.txt](https://github.com/NuGet/Home/files/61914/SampleBehaviorLib.targets.txt)
The above file (**_rename to SampleBehaviorLib.targets.zip**_) contains the SampleBehaviorLib.targets file which I am using to add reference to the appropriate binary. 
I am still not able to pinpoint why there are two dlls being referenced instead of one.

**Comment by Pilchie** [comment]
Tag @ericstj too

**Comment by yishaigalatzer** [comment]
@ratishphilip your package should contain a ref and runtimes folder, and shouldn't include any targets. I'm closing the bug, because there is no issue here. But we can keep discussing your package issue on this thread

**Comment by ratishphilip** [comment]
Ok. Let me try that.
But I do have some doubts.
I am targeting a single TxM uap10.0 because my library should only be used by UAP apps on Windows 10.
So in the Ref folder, how will I differentiate between x86, x64 and ARM libraries?
Also in the Runtimes folder, what is the runtime ID for windows 10?

**Comment by emgarten** [comment]
The ref folder is runtime agnostic. You can create a ref assembly using: https://www.nuget.org/packages/Microsoft.DotNet.BuildTools.GenAPI/1.0.0-beta-00081

Microsoft.NETCore.Platforms\1.0.0\runtime.json contains these runtimes for windows 10: win10-x86, win10-x64, win10-arm

**Comment by ratishphilip** [comment]
Hi,
@emgarten @yishaigalatzer @Pilchie  @jasonmalinowski 
 I have a question.
**Reference Assembly Source Generator** emits a **.cs** file. How do I generate a dll out of it?

**Comment by ericstj** [comment]
You can create a project with similar characteristics as your implementation dll and include the source.  We didn't try to create a dll since everyone has a different build system with respect to versioning, signing, etc so we just emit a CS that you can plug into your own project.  Here's a sample: https://github.com/ericstj/Samples/tree/ericstj/nuget3/NuGet3/1.5.dll.runtimes/src/System.Banana.Ref

**Comment by ratishphilip** [comment]
@ericstj  Thank you very much.
