### ISSUE TITLE
nuget.targets is included in .csproj file with incorrect casing

### ISSUE THREAD

**Issue by perlun** [NuGet/Home#1837]
Unfortunately, I couldn't locate the file in the NuGet2 repo, so no PR in this case. The incorrect line is this:

```
  <Import Project="$(SolutionDir)\.nuget\nuget.targets" />
```

The problem here is that the file is in fact called `NuGet.targets`. If you have your Windows projects checked out on a case-sensitive file system (like I do), this means that the file cannot be loaded. We should be writing the file name in the correct case, i.e. `NuGet.targets` in this case.

If you point me to the right file, I can submit a trivial PR for this code, where this line gets added to the `.csproj` file.

**Comment by perlun** [comment]
The same goes for the `NuGet.settings.target` file btw - it contains references to `nuget.exe` instead of the canonical `NuGet.exe`.

(then of course, one could argue as to _why_ anyone would want to name an executable with CamelCase but... that's an altogether different discussion. :wink:)

**Comment by emgarten** [comment]
The repo is at: https://github.com/NuGet/NuGet2

Note that this method of package restore has been deprecated. The current best practice is to just call nuget.exe restore in your build script before running msbuild.

**Comment by yishaigalatzer** [comment]
@perlun like @emgarten is suggesting, perhaps the best approach is to get rid of the targets alltogether.

**Comment by perlun** [comment]
Thanks for the suggestions. Doesn't that mean that all people cloning my repo would need to manually do `nuget restore` before being able to build the project in Visual Studio also? That would feel a bit awkward, but OTOH if that's the recommended practice I'll be willing to accept it.

**Comment by emgarten** [comment]
Visual Studio will automatically detect missing packages before the build starts and restore them. This is subject to the automatic package restore options in Visual Studio, but by default it is enabled.

**Comment by perlun** [comment]
OK, cool, so then the `.target` file can be dropped altogether. Do you remember what VS version this is supported from? 2012 and newer?

**Comment by emgarten** [comment]
It looks like NuGet 2.7 was the first: https://docs.nuget.org/consume/package-restore

The vast majority of users have a higher version already, you can see the client stats here: https://www.nuget.org/stats

**Comment by yishaigalatzer** [comment]
@perlun please let us know if you plan to submit a PR, which we would gladly take. Otherwise I'm going to close this as won't fix.

**Comment by yishaigalatzer** [comment]
Leaving it around until the 1st of the year, assuming you are enjoying the holidays for now.

**Comment by perlun** [comment]
@yishaigalatzer - I don't think I'll do a PR, I'll remove the stuff from the `.csproj` files instead and rely on the new, recommended approach. Thanks!
