### ISSUE TITLE
NuGet code is checking for char.IsDigit() instead for checking decimal '0'-'9'

### ISSUE THREAD

**Issue by Eilon** [NuGet/Home#1838]
The `char.IsDigit` API checks for any character in this class: http://www.fileformat.info/info/unicode/category/Nd/list.htm

And that's unlikely to be what's expected here. All the code here almost certainly is expecting ASCII chars `0` - `9`.

Offending code is here:
- https://github.com/NuGet/NuGet.Services.Dashboard/blob/8a3a1f751a8ba5b3812c59e959a593631d3c4cf3/NuGet.Services.Dashboard.Operations/Tasks/DashBoardTasks/IssLogCleanUptask.cs#L47
- https://github.com/NuGet/NuGetDocs/blob/18b512cce181147404e5d8100e2b5d096586b8a1/NuGet.Docs.MarkdownPages/MarkdownWebPage.cs#L121
- https://github.com/NuGet/NuGetDocs/blob/18b512cce181147404e5d8100e2b5d096586b8a1/NuGet.Docs.MarkdownPages/MarkdownWebPage.cs#L199
- https://github.com/NuGet/NuGet2/blob/861741bd780225a542c73a1d0904dd33b33a7a3d/WebMatrixExtension/NuGetExtension/Requirements/Requirement.cs#L469
- https://github.com/NuGet/NuGet.PackageIndex/blob/1d9e504f626f680844a584135136074a9b11568b/src/Nuget.PackageIndex/NugetHelpers/DnxVersionUtility.cs#L174

**Comment by mishra14** [comment]
Closing this as none of the repos are active anymore.
