### ISSUE TITLE
Dependencies hidden once package installed in VS

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1840]
_From @LeeCheneler on December 16, 2015 13:33_

The dependencies for a package are hidden in the right hand pane in VS once you have installed the package. It is useful to be able to see the dependencies even after a package has been installed.

_Copied from original issue: NuGet/NuGetGallery#2819_

**Comment by yishaigalatzer** [comment]
@LeeCheneler can you provide more feedback? What kind of project are you using, what right pane are you referring to? What version of visual studio and NuGet? Can you share a screenshot?

**Comment by LeeCheneler** [comment]
Sorry it would appear that the installed package wasn't available in the set packages source and so its details were not pulled. When the source is set correctly it does pull the dependencies and display them.

**Comment by yishaigalatzer** [comment]
Thanks!
