### ISSUE TITLE
ResolveNuGetPackageAssets.ReferencedPackages returns the wrong result when dependencies are listed under framework

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1843]
Sample project:

```
{
  "dependencies": {
    "System.Runtime": "4.0.0",
    "System.Dynamic.Runtime": "4.0.0",
    "System.Linq.Expressions": "4.0.0"
  },
  "frameworks": {
    "dotnet5.1": {
      "dependencies": {
        "System.IO": "4.0.0"
      }
    }
  }
}
```

When building this I would expect the build task to return System.IO in the list of ReferencedPackages.  It does not.

Potentially hacky fix: https://github.com/dotnet/buildtools/pull/368

**Comment by ericstj** [comment]
Just hit this again, I suspect this will be more important as we bring project's which cross-compile to msbuild.

**Comment by ericstj** [comment]
Ping.  Just hit this again.  I suspect this will be more important now that we're moving cross-compile to msbuild-based projects.

**Comment by nkolev92** [comment]
Manually moved to https://github.com/dotnet/NuGet.BuildTasks/issues/76.
