### ISSUE TITLE
tools directory not on the path for vcxproj builds

### ISSUE THREAD

**Issue by dp-github** [NuGet/Home#1844]
I've created a NuGet package with some executable commands in the tools directory, and I invoke those tools during my build process.  As per [this page](https://docs.nuget.org/create/creating-and-publishing-a-package), the tools directory should be added to the environment path.

I find that my csproj builds work perfectly, but my .vcxproj builds fail, complaining that the executables cannot be found on the path.  I am using Visual Studio 2013 Update 5.

**Comment by yishaigalatzer** [comment]
The page says that the path is added for the powershell console, not generically for your build. Can you explain what are you trying to do? 

In general when you want to use packages as part of the build you will add target/props files in the package and use them as part of the build.

Also note that we don't plan on fixing issues of this grade in NuGet 2.X (which is what shipped with Visual Studio 2013), we can look at it in NuGet 3.x (which ships with Visual Studio 2015 and on)

**Comment by zhili1208** [comment]
verified 3.4.2, tools folder path is added to environment path. Close this bug.
