### ISSUE TITLE
Visual Studio UI: Project List steals mouse scroll

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1847]
From vs-feedback #519724: 

In the VS2015 Update 1 NuGet "Manage Packages for Solution" UI, the box containing the list of projects steals scroll wheel focus from the pane containing it, which breaks scrolling the packages pane.

**Comment by yishaigalatzer** [comment]
The list is now a scrollable list of projects within a bigger tab which is scrollable.

You still can't scroll the two with the mouse, but it is much clearer. There is also a drag bar that lets you separate the two areas.

![image](https://cloud.githubusercontent.com/assets/1238711/13308203/350c6e80-db26-11e5-8c41-ad1d4a23a7b7.png)
