### ISSUE TITLE
Incomplete nuget version in package manager UI.

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1848]
From vs-feedback # 518862:

NuGet applies a 20 character limit to the prerelease version of a nuget package. However, the Manage Packages UI only shows up to 10 of them. This is rather troublesome, seeing as our build number mostly differs at the 11th character.

This issue occurs on the Updates and Consolidate tabs. When viewing the details of the package (on the right) the full version number is shown. But that it would be preferable to see it in the list, as we normally update multiple packages at once.

**Comment by feiling** [comment]
Fixed.
