### ISSUE TITLE
Project list needs scrollbar

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1849]
From vs-feedback 513151:

My primary solution has a large number of projects in it (86).  When I go to the updates tab in the nuget package manager window to see which projects need a package update, the list runs off the bottom of the window, rather than constraining itself to the window boundary and presenting a scroll bar.

**Comment by feiling** [comment]
Fixed by change https://github.com/NuGet/NuGet.Client/commit/f2da9be0d0d3fa3920d240cef8ea7aee65221616
