### ISSUE TITLE
Support Windows environment variables in NuGet.config files

### ISSUE THREAD

**Issue by mikeyq6** [NuGet/Home#1852]
It would be immensely helpful to be able to have something like this in the NuGet.config file:
`<add key="repositoryPath" value="%APPDATA%\NuGetPackages" />`

That way you wouldn't have  to hard-code a directory in a shared environment.

**Comment by yishaigalatzer** [comment]
Definitely something we can look into at some point. Will also be open to taking a pull request here.

Noting the cases to consider
1. Should we expand just values or also keys (probably just values)
2. Should expand the whole doc in one go (probably no, if yes we should consider the 32K limit)
3. Should this work on coreclr & Linux/Mac - Yes
