### ISSUE TITLE
include License.txt file in package but don't copy into solution

### ISSUE THREAD

**Issue by myusrn** [NuGet/Home#1853]
in my $(ProjectName).nuspec i want to include the following files entry so that anyone looking at the contents of the nupkg, when it gets referenced and expanded into a $(SolutionDir)packages folder, can see a local hardcopy of the license but i don't want this file actually copied into the projects that reference this nuget package.   Is there an oob way to accomplish that?

<file src=".\License.txt" target="" />

**Comment by yishaigalatzer** [comment]
You can put files outside of the content folder, and then they don't get copied. There is no official support for this, but pretty much any folder outside of content and lib will work.

**Comment by myusrn** [comment]
thanks for clarification of expected results.   When i set target="" it places them in <package>\content folder and so only way i could find to get it to place file in root of <package> contents was to have a source="..<some file name>" at which point target="" places the file in root of <package> folder hierarchy.  I tried target=".." to enable the same result for source=".<some file name>" references and that didn't change outcome, i.e. still got placed in "contents" folder.   Might there be a special case target= setting that routes file to root of <package> folder hierarchy so it is not included when package is consumed by a project?
