### ISSUE TITLE
Debug Experience -- telling installer to use .symbols package when both exist

### ISSUE THREAD

**Issue by myusrn** [NuGet/Home#1854]
if i have a local disk nuget feed defined and it contains both <packagename>.<version>.nupkg and <packagename>.<version>.symbols.nupkg versions of package is there a way to get <project> | manage nuget packages | <select nuget package from this feed> to use the symbols one so i have f11 step into debug support for this dependency?

**Comment by yishaigalatzer** [comment]
Not possible at the moment, symbol packages are something you need to publish to a symbol server. This could be enabled if we build a symbol server on top (or next to) nuget.server package.

CC @maartenba - lets chat and see if we want to take it into the nuget.server project (tracked on nuget gallery), also consider filtering out symbol packages by default from nuget.server (perhaps with some config)

**Comment by myusrn** [comment]
Yes using visual studio team services [ vsts ] and/or symbolsource.org i can create feeds of packages intended to enable f11 step into debugging of package provided binaries.   What i'm trying to enable with the local %temp%\packages feed is a story where i'm doing work in both the project that produces the package and the project that consumes it.   

Having it automatically output changes in package sources to %temp%\packages feed, with a symbols.nupkg drop, and the project that consumes it automatically pulling from there is in an effort to enable the experience you'd typically expect when a project reference dependency is used instead of a nuget package reference.   I'm finding teams still use lots of project reference dependency setups in lieu of nuget packages so they can get this immediate turn around on ability to consume changes/fixes made in dependency project [ / package ].

**Comment by yishaigalatzer** [comment]
yes, that makes sense. The question is mostly when/how/who

**Comment by yishaigalatzer** [comment]
ASP.NET 5 resolves it by making the package/project be an alternating thing. If you can use that build model you are better off. Also if you want to go to this mode, I suggest using project.json + csproj (because packages from other projects are a pain to update otherwise).

**Comment by myusrn** [comment]
thanks for highlighting the different asp.net 5 project behavior, i'll test switching to the environment and see if it gives a better workflow for package dependencies, vs project references, where i need to do work on both package and project that depends on package output.

**Comment by SERWare** [comment]
Yes, if .nupkg exits, package manager doesn't show .symbols.nupkg. As a turnaround to select normal or symbols packages on local folders, create one folder to feed normal packages and other for the symbolic ones. Add both feeds with "package manager settings" in VS or modify nuget config file, and then select packages from the normal or symbolic feed.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
