### ISSUE TITLE
Microsoft.Extensions.Logging does not install in .NET 4.5.1 project

### ISSUE THREAD

**Issue by muratg** [NuGet/Home#1855]
_From @xavierdecoster on December 7, 2015 18:20_

It fails with the below error message, caused by a failure to add a framework reference to System.Collections.Concurrent, as defined here:
https://github.com/aspnet/Logging/blob/dev/src/Microsoft.Extensions.Logging/project.json#L22

>  Attempting to gather dependencies information for package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' with respect to project 'WebApplication1', targeting '.NETFramework,Version=v4.5.1'
> Attempting to resolve dependencies for package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Microsoft.Extensions.Logging.1.0.0-rc1-final'
> Resolved actions to install package 'Microsoft.Extensions.Logging.1.0.0-rc1-final'
> Adding package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to 'packages.config'
> Successfully installed 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-final' to WebApplication1
> Adding package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to 'packages.config'
> Successfully installed 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-final' to WebApplication1
> Adding package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Added package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' to folder 'C:\src\WebApplication1\packages'
> Install failed. Rolling back...
> Package 'Microsoft.Extensions.Logging.1.0.0-rc1-final : Microsoft.Extensions.DependencyInjection.Abstractions [1.0.0-rc1-final, ), Microsoft.Extensions.Logging.Abstractions [1.0.0-rc1-final, )' does not exist in project 'WebApplication1'
> Removed package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final : ' from 'packages.config'
> Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final : ' from 'packages.config'
> Removing package 'Microsoft.Extensions.Logging.1.0.0-rc1-final : Microsoft.Extensions.DependencyInjection.Abstractions [1.0.0-rc1-final, ), Microsoft.Extensions.Logging.Abstractions [1.0.0-rc1-final, )' from folder 'C:\src\WebApplication1\packages'
> Removed package 'Microsoft.Extensions.Logging.1.0.0-rc1-final : Microsoft.Extensions.DependencyInjection.Abstractions [1.0.0-rc1-final, ), Microsoft.Extensions.Logging.Abstractions [1.0.0-rc1-final, )' from folder 'C:\src\WebApplication1\packages'
> Removing package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final : ' from folder 'C:\src\WebApplication1\packages'
> Removed package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final : ' from folder 'C:\src\WebApplication1\packages'
> Removing package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final : ' from folder 'C:\src\WebApplication1\packages'
> Removed package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final : ' from folder 'C:\src\WebApplication1\packages'
> **Failed to add reference to 'System.Collections.Concurrent'.** Please make sure that it is in the Global Assembly Cache.
> ========== Finished ==========

_Copied from original issue: aspnet/Logging#313_

**Comment by muratg** [comment]
Thanks for the report.  Could you share a basic repro project? 

Also, what does your nuget.config look like?  Are you only using nuget.org?

**Comment by muratg** [comment]
_From @xavierdecoster on December 10, 2015 9:44_

Hi @muratg!

Here's what I did to run into the issue:
1. clone searchcloud branch of NuGet.Services.Metadata repository, open up the solution, set NuGet.Services.BasicSearch as startup project.
2. upgrade this project from NET45 to NET452
3. Using NuGet UI, targeting this project, try installing `Microsoft.Extensions.Logging` v1.0.0-rc1-final, default dependency options (Lowest)
4. check output, looks like above

![image](https://cloud.githubusercontent.com/assets/880728/11712022/c1903360-9f2a-11e5-868c-47d386947fa3.png)

![image](https://cloud.githubusercontent.com/assets/880728/11712049/e520475c-9f2a-11e5-994f-3b71cd26fd3f.png)

The repo contains the following nuget.config, however, I'm simply targeting nuget.org (https://api.nuget.org/v3/index.json) in the NuGet UI:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nugetbuild" value="https://www.myget.org/F/nugetbuild/" />
    <add key="nuget" value="https://nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)"  />
  </activePackageSource>
</configuration>
```

**Comment by muratg** [comment]
Can you paste your project.json?  I assume this is an ASP.NET 5 project targeting Desktop CLR...  (I'm not sure what `NuGet.Services.Metadata` exactly is)

**Comment by muratg** [comment]
_From @xavierdecoster on December 10, 2015 16:58_

No project.json, no ASPNET5. Just a web project being upgraded from net45 to net452. Code in NuGet/NuGet.Services.Metadata repo on GitHub, cloudsearch branch, NuGet.Services.BasicSearch project
https://github.com/NuGet/NuGet.Services.Metadata/tree/searchcloud/src/NuGet.Services.BasicSearch

**Comment by muratg** [comment]
Got it. I don't think we ever tested our packages with csproj based projects, and I'm not sure how they would work. 

Is your goal just upgrading from net45 to net452?  Or do you intend to port it to DNX as well?

**Comment by muratg** [comment]
_From @xavierdecoster on December 10, 2015 17:17_

Actually, the goal is to use these logging packages as an abstraction between our components and the actual logger, e.g. Serilog. We can't take the dependency to the logger (e.g. Serilog) in NuGet service components, but we can rely on Microsoft.Extensions.Logging.Abstractions. See searchcloud-serilog branch how I hacked it in manually (and it works). Only, the Microsoft.Extensions.Logging package doesn't install without manually editing the csproj and adding a (unresolved) reference to System.Collections.Concurrent 😊 

DNX port? Maybe one day, not now, need logging first.

**Comment by muratg** [comment]
Hey @davidfowl, is this a project system bug?  Our package has a dependency in `net451` on `System.Collections.Concurrent`, and this actually exists on disk.  DNU is able to restore this properly, while nuget seems to have a problem.

**Comment by muratg** [comment]
_From @moorandrew on December 13, 2015 1:6_

Any update on this?

**Comment by muratg** [comment]
_From @davidfowl on December 13, 2015 1:10_

It's a csproj bug that nuget is going to work around. I'm not 100% on removing our dependencies just yet.

**Comment by muratg** [comment]
FYI guys: @yishaigalatzer @emgarten

**Comment by yishaigalatzer** [comment]
@xavierdecoster this should probably be fixed downlevel as well in NuGet2

CC @davidfowl

**Comment by avanderhoorn** [comment]
I just ran into this same issue when trying to add logging to a csproj based project... I also got a similar `System.IO` one for `Microsoft.AspNet.StaticFiles`

**Comment by mmisztal1980** [comment]
I'm struggling with this, as it prevents me from trying out EF7 in a .NET 4.5.1 project, any news on the progress or a fix? Is there a workaround?

**Comment by yishaigalatzer** [comment]
You have to manually install the framework references. It is something we will look into after the first of the year.

**Comment by yishaigalatzer** [comment]
The current consensus is that these packages are invalid, and should change. The fix will go in the CLI to auto add these references.

**Comment by dcarr42** [comment]
So just to be sure is the workaround a manual edit of the csproj file?

**Comment by yishaigalatzer** [comment]
Yes or you can add the dll manually.

**Comment by budajeff** [comment]
Is this statement still true today?

"The current consensus is that these packages are invalid, and should change. The fix will go in the CLI to auto add these references."

By "packages" do you mean Microsoft.Extensions.Logging? And if so, why haven't the maintainers of that package fixed the issue yet?

**Comment by gabbsmo** [comment]
I cannot install the package in a .NET 4.6 project. Is it the same issue?

```
Install-Package : Could not install package 'Microsoft.Extensions.Logging 2.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Microsoft.Extensions.Logging -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
