### ISSUE TITLE
ResolveNuGetPackageAssets will throw NullReferenceException when ProjectLanguage is not set

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1856]
See https://github.com/dotnet/buildtools/pull/341.  There should be a friendly error when ProjectLanguage is not set.

**Comment by yishaigalatzer** [comment]
@jasonmalinowski is this going to you?

**Comment by jasonmalinowski** [comment]
Yep!

**Comment by yishaigalatzer** [comment]
We need a label for the build task, how about Area: Build Task ?

**Comment by nkolev92** [comment]
Copied to https://github.com/dotnet/NuGet.BuildTasks/issues/77
