### ISSUE TITLE
Discussion item for Converting-a-csproj-from-package.config-to-project.json

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1857]
https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

**Comment by rohit21agrawal** [comment]
@yishaigalatzer @rrelyea  Are pack scenarios supported for projects which have converted from packages.config to project.json ?

**Comment by yishaigalatzer** [comment]
Implemented as a prototype, we will address the change to go to <packagereference>
