### ISSUE TITLE
Restore WebProxy in CoreCLR

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1858]
WebProxy is ifdefed out for CoreCLR builds, we need it back by implementing IWebProxy ourselves

**Comment by yishaigalatzer** [comment]
We need to look at getting rid of WebProxy on coreCLR, and potentially all over the place.

CC // @SidharthNabar

**Comment by SidharthNabar** [comment]
Yes - `WebProxy` was a convenience class that was part of the .NET Framework managed HTTP stack. .NET Core uses a different HTTP implementation and `WebProxy` type is no longer part of this. Consider using the following instead:
1. Create a custom type that implements `IWebProxy` interface. All .NET Core HTTP APIs related to proxies accept any type that implements `IWebProxy`.
2. Use `WinHttpHandler.ProxyUsePolicy` property to select the appropriate default for your scenario. If you want to use the same proxy that the user has configured in Internet Explorer settings, use `WinHttpHandler.ProxyUsePolicy = WindowsProxyUsePolicy.UseWinInetProxy`
3. To use a custom proxy, set `WinHttpHandler.ProxyUsePolicy = WindowsProxyUsePolicy.UseCustomProxy` and `WinHttpHandler.Proxy` to an instance of your custom proxy type.
4. If you are writing a service and want to set a specific proxy for all services on the system, you can set it for WinHTTP stack via a script (https://technet.microsoft.com/en-us/library/cc731131(v=ws.10).aspx) and then set `WinHttpHandler.ProxyUsePolicy = WindowsProxyUsePolicy.UseWinHttpProxy` (Note: This is different from setting the Internet Explorer proxy)
5. For getting or setting proxy credentials, use `WinHttpHandler.DefaultProxyCredentials` or for custom proxies, set the credentials property on an instance of your custom proxy type.

@DavidSh might have more recommendations/suggestions.

Thanks,
Sid

**Comment by davidsh** [comment]
There are simpler ways to replace `WebProxy`.  You don't need to start changing all of your code to rip out calls to `WebProxy`.

You should first just create your own `System.Net.WebProxy` class (i.e. a shim) and implement the `IWebProxy` interface on it. How exactly you implement this class depends on how you are using `WebProxy`.

I could assist more if I knew exactly how you are using the `WebProxy` class.  What parameters are you passing the constructor?  What properties are you setting?  Why use this class at all if you can simply use the "default system" proxy?  Are you using `HttpWebRequest` or `HttpClient`?

If you can describe in detail how/why you are using this class, I will be able to help more.

**Comment by emgarten** [comment]
@davidsh nuget uses `HttpClient`

**Comment by alpaix** [comment]
@davidsh NuGet uses WebProxy instances to populate [ProxyCache](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Proxy/ProxyCache.cs). 

First, it attempts to read proxy settings from a config file or from an environment variable. Proxy settings can be set as a triplet of host, user name, and password values. Optional bypass list can be added too.

Next, it validates whether system proxy is set by testing combination of values `WebRequest.GetSystemWebProxy()` and `WebRequest.DefaultWebProxy`.

Thus acquired IWebProxy objects are consumed by initializing `HttpClientHandler.Proxy` attribute of our custom [CredentialPromptWebRequestHandler](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/HttpSource/HttpHandlerResourceV3Provider.cs#L86) => WebRequestHandler => HttpClientHandler.
