### ISSUE TITLE
MSBuild targets should condition on project.json's existence, not project.lock.json's existence

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1859]
1. Create a csproj project with a project.json to resolve packages.
2. Delete the project.lock.json written out by restore
3. Build the project.

_Expected:_ you get an error telling you to run restore again
_Actual:_ it marches along, hopefully failing in some other way

**Comment by yishaigalatzer** [comment]
You also need to consider projectname.project.json in this case

**Comment by konard** [comment]
Any news on that?

**Comment by rrelyea** [comment]
Unsure of when this should be scheduled for.

**Comment by nkolev92** [comment]
Redundant now.
