### ISSUE TITLE
GetProjectsReferencingProjectJson has wrong "ProjectJson" metadata for projectname.project.json

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1863]
The code today:

```
<ItemGroup Condition="'$(ResolveNuGetPackages)' == 'true'">
  <_ProjectReferencingProjectJsonFile Include="$(MSBuildProjectFullPath)">
    <ProjectReferences>@(ProjectReference)</ProjectReferences>
    <ProjectJson>$(MSBuildProjectDirectory)\project.json</ProjectJson>
  </_ProjectReferencingProjectJsonFile>
</ItemGroup>
```

The ProjectJson is hard-coded to project.json, but it might have been [projectname].project.json in reality.

(Mentioned internally in bug 149651 and also by @onovotny.)

**Comment by jasonmalinowski** [comment]
@yishaigalatzer, @emgarten: Is NuGet actually using this property? When @Pilchie and I saw this internally a month or so ago we weren't sure.

**Comment by yishaigalatzer** [comment]
I don't believe we do, as we generate our own target file in nuget.exe. @onovotny Did you actually hit an issue?

**Comment by clairernovotny** [comment]
I did not hit any issues related to this. I just noticed it when trying to see what and how the TFM's were used in the targets file and thought it was suspicious.

**Comment by nkolev92** [comment]
Moved to https://github.com/dotnet/NuGet.BuildTasks/issues/79
