### ISSUE TITLE
Post-build events cannot depend on NuGet DLLs

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#1864]
As of today, NuGet redist DLLs are copied to $(OutDir) _after_ execution of post-build events. This is problematic for C++ use-cases where one want to run a unit-test automatically as post-build event, since any NuGet DLLs required by the test framework are not yet available.

Suggestion:
- Change the NuGet "AfterBuild" targets to run _before_ execution of post-build events.

**Comment by forderud** [comment]
Problem reproduced with Visual C++ 2015 (update 1) and NuGet 3.3.0.167.

**Comment by yishaigalatzer** [comment]
I'm not super familiar with this use case, can you share more information? What test framework are you using, and what is msbuild target are you trying to rely on?

**Comment by forderud** [comment]
I'm using Boost test (http://www.boost.org/doc/libs/release/libs/test/), but the same principle applies to any C++ unit-test framework that generates an executable intended to be run as a post-build event.

There is nothing fancy about my setup. Just a simple C++ project with a custom "post build event" to automatically start the generated executable that runs the test suite.
![image](https://cloud.githubusercontent.com/assets/2671400/11967628/ae8a39ee-a904-11e5-8b59-39b9d14049ac.png)

I don't know how post build events are integrated with msbuild.

**Comment by yishaigalatzer** [comment]
I don't know what is the build script you refer to and what binaries is boost depending on.

**Comment by forderud** [comment]
There is not build script, just a simple C++ project that starts the generated executable as a post-build event.

My generated executable depends a Boost DLLs that is packaged in the "redist" version of the Boost NuGet package I'm using ("boost_unit_test_framework-vc110-mt-gd-1_59.dll" in my case). However, these are unimportant details for you, since this is a generic problem affecting all C++ projects. All you need to check to verify this problem is that the NuGet "AfterBuild" targets are invoked after "post build events" configured through the Visual Studio IDE.

**Comment by yishaigalatzer** [comment]
I'm still not following. I'm guessing you are referring to the targets the package adds, in that case  this is a package issue. I might be able to find time to take a look if you could  provide the package id and version.

**Comment by forderud** [comment]
Ok. I understand.

I'll get back to you within a week with a minimal reproducer.

**Comment by forderud** [comment]
Minimal C++ project to reproduce the issue: [NuGetPostBuild.zip](https://github.com/NuGet/Home/files/72280/NuGetPostBuild.zip)

It appears like the problem might be related to the CoApp (http://coapp.org/) authoring tool used to generate native C++ NuGet packages.

**Comment by yishaigalatzer** [comment]
Note that co-app is an abandoned project and I believe the c++ folks are working in a replacement.

Thanks for the repro, will be back after the first of the year to look at it.

**Comment by forderud** [comment]
I know that CoApp is abandoned. However, it's the only authoring tool for native packages currently available, so the C++ community is kind of stuck with it for the time being.

Please let me know when a better replacement is available, and I'll promise to switch ASAP.

**Comment by yishaigalatzer** [comment]
Sure, I'll ping some folks to get in touch with you

**Comment by yishaigalatzer** [comment]
@forderud I talked to folks from the C++ team, they are supposed to get in touch with you first week of January. If that doesn't happen and you still need help, please ping me here.

Closing for now.

**Comment by forderud** [comment]
@yishaigalatzer did you say that there was some Microsoft NuGet activity related to C++ that I can test out?

**Comment by yishaigalatzer** [comment]
pinged them again just now

**Comment by yishaigalatzer** [comment]
@forderud have you been contacted?

**Comment by forderud** [comment]
No, not yet...

**Comment by ericmitt** [comment]
Hi Frederik, 
I'm PM in VC++ Team, can we discuss offline about this?  
my email: ericmitt@microsoft.com
Talk to you soon
Eric
