### ISSUE TITLE
NuGet.exe 3.3.0 update command on solution installs package in all projects

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#1865]
_From @BeeWarloc on December 22, 2015 10:35_

Given SomeSolution.sln with ProjectA and ProjectB, where ProjectA references a Package 1.0.0.

The old nuget.exe (v2) would upgrade Package to the latest version in ProjectA, and leave ProjectB alone, as expected.

The new nuget.exe (v3) upgrades Package to latest version in ProjectA, but also installs the Package in ProjectB. For this to occur ProjectB has to contain a packages.config file.

Is this change in behaviour intended?

_Copied from original issue: NuGet/NuGetGallery#2828_

**Comment by maartenba** [comment]
_From @BeeWarloc on December 22, 2015 10:38_

This might be the wrong place to report this issue, my apologies if that's the case.

**Comment by yishaigalatzer** [comment]
Known and fixed. You can pick nuget 3.4 from the nuget build feed in myget
