### ISSUE TITLE
Resolve Conflics

### ISSUE THREAD

**Issue by sadjadbp** [NuGet/Home#1868]
Every time I update a package like bootstrap from NuGet in VS 2015, it won't delete the old folder and adds that .deleteme file, then also when I check-in (into VS online) then I have to go to "Resolve Conflicts" section and select all then click that "copy to local ..." and then go ahead in the packages folder and delete that folder again! it has been like this from v3 and it really bugs me. Thanks.

**Comment by yishaigalatzer** [comment]
You are supposed to restart visual studio, this happens because something is holding on to the file. We are tracking a separate bug to not put the deleteme file in TFS. I will fix that one shortly https://github.com/NuGet/Home/issues/1720

**Comment by sadjadbp** [comment]
The first part of the bug is about that .deleteme file. by the way, closing and reopening, even in "run as admin" mode does not help. It never deletes package folder and the deleteme file.

Also, that Resolve Conflict part is my main issue. So please don't close this one yet.

**Comment by yishaigalatzer** [comment]
I just pushed a PR to remove these files from source contro - https://github.com/NuGet/NuGet.Client/pull/163 

Could you try re-running your scenario without being attached to source control? Also can you please verify you have both Update I and NuGet 3.3 installed?

**Comment by yishaigalatzer** [comment]
Just pushed a fix, shoot me an email to my microsoft account: y i g a l a t z

I’ll share a private build so you can verify it
