### ISSUE TITLE
NuGet Package Manager crashes in VS 2013/2015 on Windows 10

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#1872]
I have VS2013 (w/Update 5) and VS2015 on Windows 10. It was clear installation.

On opening VS2015 tells me: "The 'NuGetPacakge' package did not laod correctly". 
In ActivityLog.xml in userprofile:

```
  <entry>
    <record>462</record>
    <time>2015/12/24 12:46:37.758</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
    <hr>80131500</hr>
    <errorinfo>An exception was thrown while initializing part "NuGet.PackageManagement.VisualStudio.VSPackageRestoreManager".</errorinfo>
  </entry>
  <entry>
    <record>463</record>
    <time>2015/12/24 12:46:37.761</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [NuGetPackage]</description>
    <guid>{5FCC8577-4FEB-4D04-AD72-D6C629B083CC}</guid>
    <hr>80131500</hr>
    <errorinfo>An exception was thrown while initializing part "NuGet.PackageManagement.VisualStudio.VSPackageRestoreManager".</errorinfo>
  </entry>
```

On opening VS2013 nothing bad happens but trying open Nuget Package Manager for a project/solution fails with error:
"Value cannot be null. 
Parameter name: source".
I can open NuGet Settings but if I add a repository and save VS crashes. 
NuGet Settings contains no any repository at the same time there're a lot of them in nuget.config in my profile ("C:\Users\Sergei Dorogin\AppData\Roaming\NuGet\NuGet.Config")

I run VSs under admin account.
I've tried to reinstall NuGet package itself. No luck.
I've tried to install NuGet.Tools.vsix under Admin manually. No luck.
I've tried to remove folders "AppData\Roaming\Microsoft\VisualStudio". No luck.

It's not the first machine on Win10 I work on. It fails only on this one. The only unusual thing I can see is my user profile folder - it contains space: 
"C:\Users\Sergei Dorogin\" 

What to do?

p.s.: Needless to say that renaming user's folder is simple impossible in Windows (it'll break too many things).

p.p.s: Nuget CLI can see the config in my profile. I did successfully create/update my sources via CLI.

**Comment by evil-shrike** [comment]
Any ideas?

**Comment by yishaigalatzer** [comment]
Thanks for the hint with the space in the user name folder. We can give it a spin.

What version of NuGet do you have installed with Visual Studio 2015?

**Comment by evil-shrike** [comment]
NuGet in VS 2013 - 2.8.60723.765
NuGet in VS 2015 - 3.3.0.167

**Comment by yishaigalatzer** [comment]
Can you please update to 3.3 on 2015 and let us know if it still crashes?

Sent from my Windows Phone

**Comment by evil-shrike** [comment]
@yishaigalatzer I'm on 3.3 already, I mistakenly wrote 3.0 at the first time, sorry

**Comment by yishaigalatzer** [comment]
Ok. Will take a look after the first of the year. Need to set up a vm and user for this. I guess you know the work around for now

**Comment by yishaigalatzer** [comment]
@evil-shrike I tried it today with a username with a space in it. I don't see any issue. Can you try and get activitylog from Visual Studio 2015 with Update I. In Update I the activity log is supposed to include mode details that might give us a clue.

**Comment by evil-shrike** [comment]
I've installed VS 2015 Update 1, rebooted and NuGet Manager started working! So it seems it's not a bug but some bizarre glitch on my PC. sorry to trouble you
Closing.
