### ISSUE TITLE
NuGet.CommandLine nuspec should specify developmentDependency

### ISSUE THREAD

**Issue by commonsensesoftware** [NuGet/Home#1873]
The nuspec file for the **NuGet.CommandLine** package should declare **developmentDependency="true"** in the metadata.  Without this present, other tools that want to depend on the package cannot exclude it as a forward dependency (e.g. nuget.exe will see "NuGet.CommandLine" as a dependency when using _pack_ against a project).

The side effects of not have this declared results in one or more of the following tool author behaviors:
1. Embed a copy of nuget.exe in their own package
2. Ask the package consumer to manually update the their configuration (packages.config/json.config) with developmentDependency="true"
3. Add an Install.ps1 that automatically updates the developmentDependency="true", which only works for packages.config

Even though solution packages are no longer supported, this is similar to the ask proposed in issue #1093.

**Comment by yishaigalatzer** [comment]
We should verify this is also a part of nuget.xplat package, also note that nuget.commandline is attempting to include the pdb, but it gets stripped out

**Comment by emgarten** [comment]
NuGet/NuGet.Client@26d4fe8d737193fec341da83b3c53099e62c8b39

**Comment by emgarten** [comment]
Verified fix in the package created by the CI
