### ISSUE TITLE
It is difficult to troubleshoot connection issues

### ISSUE THREAD

**Issue by Blackbaud-SeanLong** [NuGet/Home#1878]
As a developer using NuGet in isolated test environments that we manage, I often have to troubleshoot connectivity problems between our servers trying to use NuGet during a build process, and various remote NuGet sources. This could be internal NuGet package servers or external.

Because of this, I often encounter the error "Unable to connect to remote server". Unfortunately since we use multiple sources, this error message is vague and it takes me awhile to figure out what remote server is unable to be connected to.

A couple of ideas to make this particular error easier to work through:

1) Put the Source that is not able to be reached into the error message
2) Make connection logging easier to find (I can't actually find it)
3) If you're catching a connection exception anyway, maybe suggest useful troubleshooting steps (Powershell's Test-NetConnection for instance)

**Comment by csharpfritz** [comment]
I like this type of usability improvement for the clients to help identify the source of an issue.  It reduces frustration on the developer's part because they get some diagnostic information about the error and helpful information pointing them in the direction of a possible solution.

This does not look like a functionality change, more of an error reporting / in-app documentation enhancement.

**Comment by yishaigalatzer** [comment]
Thanks for the feedback, can you a be more specific to where you are seeing this error and in what scenarios (so to help direct the effort), for example when I use a non-reachable (because of a wrong address I get the following useful error IMHO)

![image](https://cloud.githubusercontent.com/assets/1238711/12054559/8175176e-aed9-11e5-9d2a-962453b60450.png)

**Comment by Blackbaud-SeanLong** [comment]
This may be something that was changed in a recent version. Currently I’m running Visual Studio 2013 on all machines I’m setting up due to dependencies we have on that version.

Currently I’m seeing this particular vague error in a number of places:

·        If I run nuget.exe install <packageconfig> -source <unreachable host> -RequireConsent –solutionDir <solution>

·        If I open the solution I’m working in and Manage NuGet Packages and attempt to pull a NuGet package on a server I cannot reach

[cid:image001.png@01D14300.56FB0F10]

The error message you shared would have saved me probably 3 hours of troubleshooting over the past couple days, and more in the past. So if that’s what I could expect to see in VS2015 I’d be happy with that.

**Comment by yishaigalatzer** [comment]
We are no longer planning to make such changes in Visual Studio 2013, only critical bug fixes will go there.

Please try using nuget.exe 3.3 (available from https://dist.nuget.org/index.html) and Visual Studio 2015 + NuGet 3.3

**Comment by Blackbaud-SeanLong** [comment]
Unfortunately this isn’t a piece I can update in isolation, as it’s part of a complex build/test infrastructure and it would require planned downtime to update to Visual Studio 2015 (there are test agents and controllers that would have to be updated at the same time).

However, this does help me build a better case for updating this infrastructure and starting that planning process.

Thanks!

**Comment by yishaigalatzer** [comment]
Closing for now, we would love to get specific feedback on not so useful logging, in general we completely agree with the statement, it is just a matter of pointing out areas we missed and we are still producing vague error messages.

If you have specific ones please open a new issue with a repro step and details.

**Comment by Blackbaud-SeanLong** [comment]
Sure thing, thanks for taking the time to investigate this. I completely agree with the notion, sorry I couldn’t find us more specific steps to nail another down!
