### ISSUE TITLE
NuGetDocs style inconsistent

### ISSUE THREAD

**Issue by TravisTheTechie** [NuGet/Home#1879]
The writing style of the NuGetDocs content is inconsistent. Some examples...
- The use of serial commas
- Capitalization of headings (e.g. http://docs.nuget.org/Consume/ProjectJson-Intro Transitive Package Restore vs. How does msbuild task know what to pick up?) 
- Clearly identified what items are proper nouns (e.g. Project.Json sometimes, other times Project.json or project.json)
- Handling of filenames (e.g. sometimes `.nuget\NuGet.targets` or **.nuget\NuGet.targets** vs just plain  .nuget\NuGet.targets)

I would propose a style guide to be included in [Contributing to NuGet Documentation](http://docs.nuget.org/contribute/contributing-to-nuget-documentation) that highlights these things. Then as need content is added or existing content is edited, it can be brought inline with the guidance. 

A few paragraphs can go a long way, but there are plenty of examples of content style guides on the web that could be used to make a more extensive style guide or referenced and just used as is.

**Comment by csharpfritz** [comment]
I'll look into this

**Comment by kraigb** [comment]
I've finished doing a full revision pass of the docs which should address most of the inconsistencies. I'll be making another full pass to pick up stragglers. Let me know if you see specific ones while this issue is open. I'll also add contribution notes as part of that second pass.

**Comment by kraigb** [comment]
@TravisTheTechie I've done another consistency pass on the docset (https://docs.microsoft.com/nuget), and updated the readme.md on https://github.com/NuGet/docs.microsoft.com-nuget with conventions.

I believe these are sufficient to close this issue.
