### ISSUE TITLE
Framework references to System.* removes reference to System

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#1880]
1. Create a project.json that has a framework reference to something like System.Linq or System.Xml.
2. Add an explicit reference to System in your .csproj
3. Try building.

_Expected:_ your System reference is still there
_Actual:_ it gets removed

The bug is here:

```
  <!-- Remove simple name references if we're directly providing a reference assembly to the compiler. For example,
       consider a project with an Reference Include="System", and some NuGet package is providing System.dll -->
  <Reference Remove="%(_ReferencesFromNuGetPackages.FileName)" /> 
```

The FileName metadata is dropping the second namespace. The easiest fix is probably to just add a condition to verify the extension is actually of the type that line expects. The more complicated fix might be to revisit some of this entirely.

**Comment by clairernovotny** [comment]
Documenting the temporary workaround as per @jasonmalinowski:

Add `<IncludeFrameworkReferencesFromNuGet>false</IncludeFrameworkReferencesFromNuGet>` to the csproj.
