### ISSUE TITLE
Docs update - Package Manager Dialog usage docs need to be updated for VS 2015

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1884]
The Package Manager Dialog page needs an updated version that demonstrates the new Visual Studio 2015 user interface:

http://docs.nuget.org/consume/package-manager-dialog

**Comment by kraigb** [comment]
http://docs.nuget.org/ndocs/tools/package-manager-ui has screenshots that are current for VS 2015 as well as VS 2017 RC.
