### ISSUE TITLE
"nuget.exe update" installs packages to projects that don't have the specified package in packages.config

### ISSUE THREAD

**Issue by alecor191** [NuGet/Home#1885]
Scenario: Assume we have a solution with 2 projects. A test project T that uses package "nunit" and a console app project C that doesn't use "nunit". Now I want to update package "nunit" to the latest version using "nuget.exe":

`
nuget.exe update <path_to_solution_file> -id nunit -repositorypath <path_to_packages_folder>
`

The result is:
- "nunit" package is properly updated to the latest version in project T. 
- **"nunit" also gets _added_ to project C.** This is unexpected/not desired.

Note that this is inconsistent with the behavior of the PS command Update-Package which will only update "nunit" package in project T and leave C as-is (i.e. don't install "nunit"). This is the desired behavior.

Is this something that can be addressed in nuget.exe? 

Some more context: We have hundreds of projects and dozens of solution files. So we're looking for ways to simplify package updates across solutions.
- E.g. update "nunit" to latest version in all test projects across all solutions. 
- Or update "Microsoft.ApplicationInsights.Web" package in all web projects across all solutions.
  We have both .csproj (packages.config) as well as .xproj (project.json) projects.

Any suggestions how to address the scenarios above using "nuget.exe update" or using another approach?

**Comment by yishaigalatzer** [comment]
This is a bug that was already fixed, you can pick up a pre-release version on the nugetbuild feed on myget - http://myget.org/gallery/nugetbuild, grab the nuget.commandline package.

Here is the duplicate bug: https://github.com/NuGet/Home/issues/1312

**Comment by yishaigalatzer** [comment]
If this doesn't resolve your issue, please re-ping this thread.

**Comment by alecor191** [comment]
Thanks @yishaigalatzer. The pre-release version works fine.

**Comment by Semax** [comment]
I'm having this very issue with NuGet 3.3.0.212. I thought it had been fixed in 3.3.

**Comment by yishaigalatzer** [comment]
Would you mind giving 3.4 a try?

Sent from Outlook Mobilehttps://aka.ms/xp9y6l

On Wed, Mar 16, 2016 at 12:30 AM -0700, "Semax" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm having this very issue with NuGet 3.3.0.212. I thought it had been fixed in 3.3.

##

**Comment by Semax** [comment]
Thanks, 3.4 seems to work fine in this respect. Though it started to give multiple warnings with one of external private package sources we use: An error occurred while retrieving package metadata for "X" from source "Y".
