### ISSUE TITLE
Feature Request: Add support for Management Pack projects (mpproj)

### ISSUE THREAD

**Issue by mfaulkinbury** [NuGet/Home#1888]
[System Center Visual Studio Authoring Extensions](https://www.microsoft.com/en-us/download/details.aspx?id=30169) adds support for developing Management Packs using Visual Studio.

As a Management Pack author, I would like to leverage NuGet to manage Management Pack (MP) and Management Pack Bundle (MPB) references.

As a Management Pack author, I would like to leverage NuGet to manage shared content in the form of template snippets, so that template snippets can effectively be shared across projects.

![nuget4scom](https://cloud.githubusercontent.com/assets/9920907/12152282/5e2c829c-b479-11e5-9450-d9250d6eb7dc.PNG)

I've cloned the repository and experimented with the implementation for this request.  I would appreciate feedback so I know whether this feature request should be:
1. handled by your team,
2. submitted as a pull request, or
3. does not belong in NuGet and should be supported using an alternate extension.

Best,
Mike

**Comment by yishaigalatzer** [comment]
First thanks a lot for a well formed issue request!

When it comes to options, I'm guessing this is not something we would like to handle (at least not in the near future), we could consider it as a pull request, but we could look at it first as a design level dicsussion, and then move on to code, I think that will be the best.

I'm parking it for now in the discussions milestone, so we can keep talking and once a PR is ready we can move it to a milestone.

A few things to keep in mind.
1. We are going to remove the dependency on nuget.core.dll in this release (living in nuget2 repo), so we would like to avoid new code depending on it in any way.
2. Tests - This will require functional tests, and a solid way to run them regularly so we can make this doesn't break.
3. If this is just about snippets, rather than other shared content - I would suggest this is not the right mechanism, and I would look at scaffolding as a mechanism to do that.

**Comment by mfaulkinbury** [comment]
@yishaigalatzer  Thanks for your thoughtful response!  

I've looked into this a little further and _I think_ it might be much easier than I originally anticipated.  

If I add the MP Project Kind as a supported project, handle supplying a TargetFrameworkMoniker for it, then let the Project System Factory return the default project system (VSMSBuildNuGetProjectSystem), I am able to access all of the NuGet-ey goodness that I've come to appreciate in my other projects.

I'd be happy to issue a pull request (and work through any resulting feedback) in order to facilitate this discussion (I find it easier to look at code than read the above paragraph).

To address your points above:
1. I don't believe I am creating any new dependencies and I've been able to find existing "patterns" to accomplish this requested change.
2. I'd be happy to create any required tests.  I'm still trying to understand the test organization at the moment.  It seems that I could leverage existing tests by just adding an additional MP project artifact. 
3. This is not just about snippets; I just used snippets as an example of content.  A Management Pack project leverages content in the form of Management Pack fragments (XML), but also includes snippets and template groups that have respective code (XML) generators.

Obviously if the MP authoring community embraces the use of NuGet, we can add more functionality later.  However, with the changes noted above, I am able to leverage the existing Build folder and Lib folder capabilities to accomplish the required Management Pack references and everything else is covered by the existing Content folder capabilities.

Best,
Mike

**Comment by mfaulkinbury** [comment]
@yishaigalatzer 

[PR](https://github.com/NuGet/NuGet.Client/pull/187) added.

I look forward to continuing this discussion.

Best,
Mike

**Comment by mfaulkinbury** [comment]
@yishaigalatzer Above, you mention that, "...once a PR is ready we can move it to a milestone."

I've submitted a PR.  Can you provide guidance on what I can do to move this forward?

Best,
Mike

**Comment by yishaigalatzer** [comment]
@mfaulkinbury sorry about not being super responsive. We are under pretty heavy load at the moment. We could take this for 3.4 if this is all the change required, and you can verify it in your scenarios (pending PR review)

**Comment by mfaulkinbury** [comment]
@yishaigalatzer  Getting it into 3.4 would be great.  Thanks!

**Comment by mfaulkinbury** [comment]
@yishaigalatzer 

I see that the PR has been reviewed and is marked "ship it", but shows as OPEN rather than PROPOSED in the Pulse view.

Is there an action that I've failed to take, or will you guys move it through the process from here?

Thanks!

**Comment by yishaigalatzer** [comment]
We will take it from here. I have no idea what it takes to change it to Proposed, we just merge and close :)

**Comment by yishaigalatzer** [comment]
I am waiting for your feedback on actually having tested this change

**Comment by mfaulkinbury** [comment]
@yishaigalatzer   yes, I have been using the new version for about a week and it does what I need it to do (to start).

I'd be happy to provide more formal test support, but I'd need a little guidance as to where and what is needed.

**Comment by rrelyea** [comment]
from the commit, looks like this is addressed in 3.4.3 or 3.4.4
