### ISSUE TITLE
Build tasks should be installable

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1889]
#### End goal

We would like to be able to rev the build tasks, without having users taking a dependency of new releases of visual studio. Thus enabling OSS projects to take new NuGet features, and ship the build tasks as part of the project.
#### Mid goal

Once we have csproj to xproj reference support, we would like to depend on that build task and merge nuget.core and nuget.client solutions **before** Update II ships while allowing end users to contribute to the NuGet project without needing pre-release bits.
#### This particular issue

Create an "installable" version of the build task we can consume in the nuget github project.

**Comment by emgarten** [comment]
This is no longer needed now that changes to the build task have slowed.
