### ISSUE TITLE
NuGet should persist runtime dependencies from runtime.json in the lock file

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#1890]
Today there is nothing in the lock file when one package causes another runtime-specific package to be added to the lock file.

For example:

```
{
    "dependencies": {
        "System.IO.FileSystem": "4.0.1-beta-23516",
        "Microsoft.NETCore.Platforms": "1.0.1-beta-23516"
    },
    "frameworks": {
        "dnxcore50": { }
    },
    "runtimes": {
        "win7-x64": { }
    }
}
```

The `runtime.win7.System.IO.FileSystem` package will appear as if it is rooted in the runtime graph, yet it doesn't appear in the project dependencies a root reference.  Instead I would have expected some way to associated that the `runtime.win7.System.IO.FileSystem` package was brought in by a runtime association with System.IO.FileSystem for RID win7.

This is necessary in order to provide build time tooling that reconstructs the package graph without cracking open the runtime.json files.

**Comment by emgarten** [comment]
Merged with NuGet/NuGet.Client@6f8f8e783fc2f314c5b27498225d9e4db006c0da
