### ISSUE TITLE
Improve RE-RELEASE/SNAPSHOT functionality

### ISSUE THREAD

**Issue by andreasfrey** [NuGet/Home#1891]
Is there any way to achieve some sort of SNAPSHOT functionality in NuGet?

We are currently developing a new project A in which we use another project B currently under development.

Whenever there are changes in project B, we have to release a new (pre-release) version and update the dependency in project A manually.

I would like to have some maven (java) like SNAPSHOT behavior. Example:
I am working on project B. It is currently in Snapshot (pre-release) mode. E.g. 1.0-SNAPSHOT. Every time i deploy a new version (of a SNAPSHOT/PRERELEASE) to the repository, the old package gets overwritten and the version number does not change. Project A requires Project B 1.0-SNAPSHOT. Whenever I rebuild the project A, it automatically downloads the newest version of the dependent SNAPSHOT versions (Project B 1.0-SNAPSHOT) and ignores the local cache. Overwriting of versions is only possible for SNAPSHOT/Pre-Release versions. SNAPSHOT versions and Release version also can live in different repositories.

This would improve the daily development work for larger (distributed teams) a lot.

I hope you understand the benefit for this, feel free to ask and I will clarify.

I found no similar issue in the new github repo, but an older / unresolved issue on codeplex (Source: https://nuget.codeplex.com/discussions/238169).

**Comment by yishaigalatzer** [comment]
We do have a feature for that and infact the NuGet project itself is relying on it. It is not exactly the same as you describe, but the goal is very similar.

You do need to switch your project from using packages.config to project.json (you can still rely on csproj files etc.) and then specify the dependecy with a star notation: e.g. 3.4.*

Here is an example used in building nuget.exe - https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/project.json.
At this point we do not intend to implement a feature like this in packages.config world, and at the moment it is not officially supported (i.e. there are no project.json templates, or file->new project doesn't yet generate it), but we (and so does Roslyn and other prominent projects) rely on this new mechanism with classic class libraries, console apps, UWP apps and other types of apps.

I'm going to move this item to the discussions milestone, where we can keep talking about it.

**Comment by rrelyea** [comment]
Our solution is to use project.json and rotate build numbers with *.
We do not want to enable building a new package with the same identity as a previous package.
