### ISSUE TITLE
ArgumentException stemming from PowerShellCmdlets.UpdatePackageCommand

### ISSUE THREAD

**Issue by lukepuplett** [NuGet/Home#1892]
Hello, had this exception 3 times today.

NuGet 3.3 with VS2015 update 1, I think. I'll check and come back: Yep, 3.3.0.167 

Original command line:

`Update-Package -Reinstall -ProjectName CompanyName.WebAPI.AppName`

And here's the error, tail end of PS console:

<code>
...
'Areas\RouteDebugger\Components\DictionaryExtensions.cs' already exists. Skipping...
'Areas\RouteDebugger\Components\ActionSelectSimulator.cs' already exists. Skipping...
Added package 'WebApiRouteDebugger 1.0.0' to 'packages.config'
Update-Package : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.At line:1 char:1
- Update-Package -Reinstall -ProjectName CompanyName.WebAPI.AppName
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

PM> 
</code>

Smells buggy in that CmdLet. For info, this update has needed user input on keyboard to confirm/reject file overwrites.

Luke

P.S. Couldn't get a trace, even though the error is in the `$errors` PS collection the exception instance is seemingly empty.

**Comment by lukepuplett** [comment]
The error seemingly occurs always for the WebApiRouteDebugger.

And it doesn't invoke a rollback.

Err, nope it also just happened for Microsoft.AspNet.Web.Optimization 1.1.3

**Comment by yishaigalatzer** [comment]
I believe I fixed this bug over the holidays. It happens when you have another local folder where you have the packages as well as online.

Please email me directly, and I'll get you access to private bits to verify the fix. yigalatz @ msft.com

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet.Client/commit/0713e107b5cbf0e3fc213915f8c928ee73dcead7
https://github.com/NuGet/Home/issues/1877
