### ISSUE TITLE
Redirecting nuget.exe output to file causes infinite loop

### ISSUE THREAD

**Issue by mrkane27** [NuGet/Home#1893]
When trying to print justified text, NuGet uses `Console.WindowWidth`, which is `0` if the output was redirected to a file, and then it loops forever printing newlines and not consuming any text.

This issue existed before in codeplex as [3408](https://nuget.codeplex.com/workitem/3408), and was [fixed](https://github.com/NuGet/NuGet2/commit/98d15b3b5d18a3100136d8b9a5aaf857d7b8b5b4) in the NuGet2 repo a couple of years ago, but it never made its way to NuGet.Client.

**Comment by mrkane27** [comment]
https://github.com/NuGet/NuGet.Client/pull/184

**Comment by yishaigalatzer** [comment]
@mrkane27 thanks for the fix, could you please add a test to the fix?
