### ISSUE TITLE
Unable to find packages when ignoring dependencies using vs2015 and Nuget Api V2 using JFrog Artifactory

### ISSUE THREAD

**Issue by StefanoGermani** [NuGet/Home#1894]
Hi,

When I try to install a package ignoring the depedencies using Nuget Package Manager 3.3.0.167 on VS2015 from Nuget Api v2, Nuget Package Manager fails to find the package.

If I try to install the same package with Lowest dependency behaviour then everything works fine.

**Comment by yishaigalatzer** [comment]
@StefanoGermani can you please provide more specific feedback. What package, what project and as much examples as you can provide to reproduce this issue?

**Comment by StefanoGermani** [comment]
We are using an internal nuget api (JFrog Artifactory) and it happens with any package present only in it. Installing or updating any package ignoring the depedencies fails with

```
Unable to find version 'xxx' of package 'xxx'
```

I have tried to replicate the issue using the nuget.org api v2 (by setting it in Package Sources in the NuGet Package Manager settings) but everything works fine. 

If I use Nuget Package Manager 2.x with VS2013 I can install packages with ignore dependencies without any problem. That is why I have assumed that the problem is with the new version of Nuget Package Manager.

**Comment by yishaigalatzer** [comment]
Can you share a fiddler trace? My assumption here is that the jfrog server is not fully compliant with the protocol and perhaps v3 is using a different piece of the protocol in this case.

**Comment by StefanoGermani** [comment]
This is the relevant request that is failing

```
GET http://xxxx/artifactory/api/nuget/nuget-internal-master/Packages(Id='xxxx',Version='21.4')/Id HTTP/1.1
DataServiceVersion: 1.0;NetFx
MaxDataServiceVersion: 2.0;NetFx
User-Agent: NuGet Client V3/3.3.0.0 (Microsoft Windows NT 10.0.10240.0, VS Professional/14.0)
Accept: application/atom+xml,application/xml
Accept-Charset: UTF-8
Host: xxxxx
Accept-Encoding: gzip, deflate


HTTP/1.1 405 Method Not Allowed
Server: nginx/1.8.0
Date: Mon, 11 Jan 2016 12:07:12 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Artifactory-Id: 92b2893cc137d63c:-2ac551e5:151cfa78079:-8000
Allow: DELETE,OPTIONS,PUT

53
{
  "errors" : [ {
    "status" : 405,
    "message" : "Method Not Allowed"
  } ]
}
0
```

it looks like the problem is the /id at the end of the requested url, this request instead succeeded and I managed to install the same package successfully:

```
GET http://xxxx/artifactory/api/nuget/nuget-internal-master/Packages(Id='xxxxx',Version='21.4.0') HTTP/1.1
DataServiceVersion: 1.0;NetFx
MaxDataServiceVersion: 2.0;NetFx
User-Agent: NuGet/2.10.0.755 (Microsoft Windows NT 10.0.10240.0)
Accept: application/atom+xml,application/xml
Accept-Charset: UTF-8
Host: xxxx
Accept-Encoding: gzip, deflate


HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Mon, 11 Jan 2016 12:18:30 GMT
Content-Type: application/atom+xml;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Artifactory-Id: 92b2893cc137d63c:-2ac551e5:151cfa78079:-8000
DataServiceVersion: 2.0
Content-Encoding: gzip
```

**Comment by yishaigalatzer** [comment]
Looks like artifactory is not supporting the full protocol. I'll call their support. Particularly simmering is getting confused about the http method.

**Comment by StefanoGermani** [comment]
Thanks for the help! I'll raise it with the JFrog support too.

**Comment by santee** [comment]
@StefanoGermani @yishaigalatzer 
Did you guys get any answer from JFrog? Have the same issue.

**Comment by StefanoGermani** [comment]
Sorry for the late reply. This is the Artifactory ticket tracking the issue:

https://www.jfrog.com/jira/browse/RTFACT-9287

**Comment by santee** [comment]
Thank you!

**Comment by rrelyea** [comment]
Issue still seems open in JFrog
