### ISSUE TITLE
Korean translation in v3.3 does not appear correctly

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#1895]
From vs-feedback 515796:

_Looks like the Korean encoding has been changed?_

Screenshot is attached to the vs-feedback item.

**Comment by yishaigalatzer** [comment]
@csharpfritz can you add a link to the image?

**Comment by DarylRoberts** [comment]
Gotta Watch those Koreans , Espeacialy the Northern Ones

**Comment by csharpfritz** [comment]
Here is the screenshot shared with us:

<img width="379" alt="snip_20160108161358" src="https://cloud.githubusercontent.com/assets/78577/12209701/e27ff2ea-b622-11e5-8a7c-48ee7ec3d555.png">

**Comment by yishaigalatzer** [comment]
That looks like a .NET issue, not NuGet. We do no localize the http exceptions. @RanjiniM can you look deeper into this?

**Comment by zhili1208** [comment]
Tested NuGet 3.4.0.715 on VS 2015 Update2, it's fixed.
![test](https://cloud.githubusercontent.com/assets/7131513/13653580/6584e89e-e607-11e5-8ca3-1a25a1b45cbd.PNG)
