### ISSUE TITLE
Installing Nuget gives "URI formats are not supported"

### ISSUE THREAD

**Issue by validian** [NuGet/Home#1898]
I have Visual Studio 2015 Update 1 with Nuget version 3.3.0.167. I have tried installing numerous Nuget Packages for a Universal Windows project type and get the error "URI formats are not supported" no matter what package I try to install. A couple of the packages I have tried to install:
NewtonSoft.Json
Microsoft.IoT.Devices

**Comment by yishaigalatzer** [comment]
Can you share your nuget.config/package sources. My guess is that you have more than one, and one of them is invalid. In this case we should provide an error message that will point you to the right place and how to fix it.

**Comment by validian** [comment]
The new UWP project template doesn't seem to have a nuget config file anymore. 
![image](https://cloud.githubusercontent.com/assets/4553904/12204565/c01f5a76-b5e9-11e5-9558-d06cc645c015.png)

**Comment by yishaigalatzer** [comment]
This will be your nuget.config on your machine. you can also just share the nuget sources that you see by clicking the gear button in the nuget UI.

**Comment by validian** [comment]
These are my nuget sources. They work on all project types other than the UWP.
![image](https://cloud.githubusercontent.com/assets/4553904/12205911/dafa0504-b5f2-11e5-8b8e-c4ac6c55dddd.png)

**Comment by yishaigalatzer** [comment]
Looks like you work in Microsoft, please contact me directly at - yigalatz. I can see some potential issues with your setup (particularly the fact that your are using ms-nuget server)

**Comment by yishaigalatzer** [comment]
Looks like the core issue is from the 3rd entry file://..../$e/....

The error we produce isn't good enough and send the user on a wild goose chase. We should explicitly say that the feed is bad, and provide the name + url for it.

**Comment by yishaigalatzer** [comment]
![image](https://cloud.githubusercontent.com/assets/1238711/12210400/82d618f6-b60e-11e5-8255-421dee30b291.png)

**Comment by yishaigalatzer** [comment]
@validian we believe this should fixed now, would you be able to contact me again to grab a build and validate?

**Comment by zhili1208** [comment]
verified this, we only fixed v2 and v3 source, if the source is local path or UNC share, it will go to old nuget.core, we didn't fix that yet, when we move local repository to NuGet.Client solution, it will be fixed automatically.
