### ISSUE TITLE
Enable machine wide configuration on OS X and Linux

### ISSUE THREAD

**Issue by glennc** [NuGet/Home#1899]
We want the ability to pre-install a feed on a machine and have restore pick that up and use it instead of hitting the internet.

I was thinking of locations like this:

**Linux:** /etc/opt/nuget

From LHS about `/etc/opt`: Host-specific configuration files for add-on application software packages must be installed within the directory /etc/opt/, where is the name of the subtree in /opt where the static data from that package is stored.

**OS X:** /Library/Application Support/NuGet/nuget

From AppleDocs on `/Library/Application Support`: Use this directory to store all app data files except those associated with the user’s documents. For example, you might use this directory to store app-created data files, configuration files, templates, or other fixed or modifiable resources that are managed by the app.

**Comment by yishaigalatzer** [comment]
@zhili1208 this is something to look at as soon as you are done with the current test fixes for Linux/Mac.

CC @emgarten

**Comment by ellismg** [comment]
For Red Hat specifically, their "software collections" feature uses a different system layout (basically they have some intermediate folders under /opt).  Do you imagine that the location of this machine wide configuration would itself be configurable?  If so, is that a build time thing or could it be controlled via environment variables?

**Comment by yishaigalatzer** [comment]
@ellismg can you share specific details about where would you place the nuget.config files on redhat, and then we can see how to control it (environment variables seem right)

**Comment by ellismg** [comment]
@yishaigalatzer I can dig into it as I read more of their packaging guidelines.  My high level understanding is that they provide a tool to select what version of a "software collection" you are using and then do stuff behind the scenes (setting environment vars) to make sure things run on the selected version.  It sounded like something like RVM or how DNVM used to work (by putting stuff on the PATH) but I'll follow up here once I have a deeper understanding of their packing requirements.
