### ISSUE TITLE
Nuget add makes some folders and files all lowercase

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#1900]
For example in our build script we run `Nuget add Blah.Blah -source <folder> -expand` and we get <folder>/blah.blah

**Comment by BrennanConroy** [comment]
Talked in person, by design

**Comment by roberthusak** [comment]
Hi, do you know the reason of this decision? It actually causes trouble on case sensitive file systems (or at least on Linux under Mono), because `dotnet restore` can't recognize a package added this way and installs it again. Thanks.
