### ISSUE TITLE
Clean-up: Make sure that PackageExtractionContext in non-null in INuGetProjectContext

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#1901]
Clean-up: Make sure that PackageExtractionContext in non-null in INuGetProjectContext

One option is to have an abstract class NuGetProjectContext which implements INuGetProjectContext to enforce the default value for all its implementors

**Comment by yishaigalatzer** [comment]
This doesn't seem like an important enough to track given the limited scope of the issue. We can revisit if this if we find issues or bugs stemming from this.
