### ISSUE TITLE
Public CI server?

### ISSUE THREAD

**Issue by kevinkuszyk** [NuGet/Home#1904]
I've been having some trouble building the [NuGet.Client](https://github.com/NuGet/NuGet.Client) solution (see #1768).

How about adding a public CI server on AppVeyor, so that potential contributors can see if the solution currently builds and if there are any broken tests?  Everyone would also get the benefit of verifying PRs build in public too.

I appreciate that you must have your own private CI server at the moment.  Perhaps you can run the two in parallel for a while, and fully transition over to the public one at some time in future?

**Comment by yishaigalatzer** [comment]
Thanks, this has been on our todo list for a while. We plan for our CI to be side by side, and not rely on appveyor to run our actual builds, mostly because we have to do internal only activities (like signing with Microsoft keys, etc.).

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
