### ISSUE TITLE
Restore with Project Dependencies put incorrect version in project.lock.json

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#1911]
project dependencies give 1.0.0-- (i.e. DNX proj reference Microsoft.Dnx.Runtime)

@emgarten (I pinged you about this, just logging a bug for tracking)

**Comment by emgarten** [comment]
Related to https://github.com/NuGet/Home/issues/1598

**Comment by emgarten** [comment]
NuGet/NuGet.Client@1cd4679aeaad43a2fe2edb023f0be22e2ee36984
