### ISSUE TITLE
Avoid "overfloat" in v3 Restore

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1912]
Right now, `*` is a little extra dangerous because we can end up "overfloating" it (i.e. floating a package too high, so that it's dependencies cannot be resolved properly against your sources).

This occurs because the restore process puts the package installation location (i.e. `~/.nuget/packages`) in as a source during restore. When you have a `*`, we check all registered sources for versions and the local package location may have a version that is **higher** than is present on the sources registered in `NuGet.Config` because another project may have installed one there. Instead, we should ensure that a `*` is resolved to a version number using the registered feeds only and only go to the local cache once it has been resolved (to see if we need to fetch it).

/cc @BrennanConroy @emgarten

**Comment by yishaigalatzer** [comment]
Needs verification and discussion with @davidfowl about the use of the global packages folder as a feed

**Comment by emgarten** [comment]
This has been fixed in the latest version of NuGet.
