### ISSUE TITLE
Determine project.json dependency name to use for msbuild projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1914]
MSBuild projects can be referenced in project.json as dependencies to add additional metadata such as include/exclude. The problem is that Visual Studio allows duplicate project names, to solve this NuGet creates unique names by adding the solution folders to the name.

Example: If a project `MyProject` is under a solution folder `src` it will be given the name `src\\MyProject` 

This name isn't obvious to the users. 

The name is also displayed in the lock file.

One possible solution is to use the project name until a conflict is hit, then all conflicts will be forced to use the full unique name.

NuGet could also support understanding both the unique and short name.

**Comment by emgarten** [comment]
Assembly name could be used for this.

**Comment by yishaigalatzer** [comment]
This doesn't block xplat, but it blocks vs scenarios after we implement p2p required for xplat

**Comment by emgarten** [comment]
Moving this to 3.6.0 RC since it affects consumers of the assets file. The current plan is to use `PackageId` and fallback to `AssemblyName`. This matches how Pack will find the id, so converting a project to a package will keep the same id.

**Comment by emgarten** [comment]
This is easier with .NETCore projects where Include/Exclude flags are set on the ProjectReference.

Additional project naming clean up has been added in NuGet/NuGet.Client@f9c92a0f12631f91418e8ea3a6705a1e8dd01dcf
