### ISSUE TITLE
Handling failing sources

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1916]
DNU by default fails when a source is not found. NuGet ignores these failing sources during restores.

We need to discuss this and decide on what behavior NuGet should have.

**Comment by yishaigalatzer** [comment]
CC @davidfowl, lets discuss the design here today and make a call.

**Comment by yishaigalatzer** [comment]
e.g. Should we have a --offline mode?

**Comment by csharpfritz** [comment]
I think there is enough customer feedback for NuGet to indicate that we
should not fail when a package source is unreachable, and we should report
it in the output as a warning.

I like the idea of a command-line switch or configuration option that
indicates that NuGet should fail if it cannot reach a package source, the
opposite of an --offline switch.

**Comment by yishaigalatzer** [comment]
@csharpfritz in project.json restore, the results would vary based on feeds availability so although I get the feedback, the default should guarantee that the results are accurate.

There is an existing flag on DNU called ignorefailedsources, it is a bit different than -offline and we should probably go with that

**Comment by csharpfritz** [comment]
Agreed that results delivered could vary based on feed availability, but we
currently have no mechanism that records which feed a package is delivered
by.  It would be great to be able to say, "Package A was not updated
because Source Z was inaccessible" because just reporting "Package A was
restored" when it was updated from Source Y would be a bad thing.

This would be a behavior change for NuGet, and we would need to make it
clear when the NuGet tools are updated.

Jeff

**Comment by yishaigalatzer** [comment]
The work here, is to add a flag called -ignoreFailedSources. The default behavior should be failure.

For specific scenarios we might be able to allow failed sources regardless
1. Restore to an exact version in packages.config
2. Restore to an exact version in project.json

There are more edge cases that might still work correctly (like install with a known version, dependency behavior lowest and exact match of all dependencies found). However this would be too confusing, and i prefer we fail for now.

**Comment by yishaigalatzer** [comment]
Was replacing https://github.com/NuGet/Home/issues/2125, make sure you read #2034 before executing

**Comment by Roemer** [comment]
What happened to the flag `--ignore-failed-sources`? Is there now any way to prevent nuget from aborting if a source is not reachable?
