### ISSUE TITLE
Cannot install any packages - VS2015

### ISSUE THREAD

**Issue by JLR-UK** [NuGet/Home#1923]
I cannot install any packages in VS2015 using either pm console or gui.

In an attempt to fix this issue before shouting for help, I have un-installed VS2013 & VS2015 from my machine and re-installed VS2015.

No matter what project type I use or which package I try to install, installation fails with the message

"Exception has been thrown by the target of an invocation"

Also tried using elevated permissions and also removed and re-installed nuget via developer command prompt (ie outside of the IDE)

Any suggestions/help appreciated.

**Comment by emgarten** [comment]
Are you able to get the full stack trace for this from your Visual Studio ActivityLog.xml log file?

What steps did you use to install nuget from the command prompt?

**Comment by JLR-UK** [comment]
Unfortunately, as this was holding back my work I've re-installed everything from the OS up.  Sorry I can't provide any further info/logs.
