### ISSUE TITLE
OptimizedZipPackage unpacks packages to TEMP but don't delete them

### ISSUE THREAD

**Issue by jechtom** [NuGet/Home#1924]
Version: 2.8.3

When using Nuget.Server package, every time App starts, it will unpack all packages to TEMP folder (class OptimizedZipPackage created in ServerPackageRepository.OpenPackage private method). 

It will unpack all packages every time app is recycled and used. After while it will eventually fill disk. Because folder names are generated randomly so for same packages each time app is started new folder is created. Those cached unpacked packages are never deleted.

**Comment by jechtom** [comment]
Created for wrong project.

**Comment by maartenba** [comment]
@jechtom Try our latest bits - http://blog.nuget.org/20160113/Accelerate-your-NuGet.Server.html

**Comment by yishaigalatzer** [comment]
Please update to the latest version

**Comment by jechtom** [comment]
Great work guys!

**Comment by maartenba** [comment]
Thanks @jechtom !
