### ISSUE TITLE
Local Packages having remote dependencies - Unable to resolve dependencies

### ISSUE THREAD

**Issue by last-Programmer** [NuGet/Home#1926]
When we have a local package depending on remote dependencies and upgrading the local package gives error unable to resolve dependencies for remote packages.

**Comment by yishaigalatzer** [comment]
You need to provide more details, this definitely works in all the scenarios we are aware of.
1. Version of NuGet you are using
2. Sources configuration
3. Dependnecies
4. The exact way you run the command

**Comment by yishaigalatzer** [comment]
Closing because there is no feedback here. I hope you managed to resolve the issue
