### ISSUE TITLE
NuGet 3 seems to reference the project itself

### ISSUE THREAD

**Issue by Alovchin91** [NuGet/Home#1929]
I'm building the NuGet packages for my company's private NuGet feed. I then use these NuGet packages in projects on the same computer. In this case, I get the CS0436 warning when I rebuild the NuGet package. I also get unwanted .targets file execution from this NuGet package.

Let's say I have a project called MyLib. I have a .nuspec defining this project, and I have a .targets file that xcopies the Debug version of MyLib in target project's Debug configuration.

I build the NuGet package and upload it to the private feed. I then create another project, say, TheApp. TheApp references MyLib from the NuGet feed. When I build TheApp, NuGet places MyLib into the user's package cache. Also, when I build TheApp in Debug configuration, the .targets file from MyLib package xcopies its Debug version to TheApp's output dir.

I then go back to MyLib project and rebuild it. In this case, I get a bunch of following warnings:

```
1>...\MyLib\SomeClass.cs(22,25,22,41): warning CS0436: The type 'SomeClass' in '...\MyLib\SomeClass.cs' conflicts with the imported type 'SomeClass' in 'MyLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '...\MyLib\SomeClass.cs'.
```

Also, when I build MyLib in Debug configuration, I can see the diagnostic output from the .targets file, and actually the .targets file executes, which means that it xcopies Debug versions of the NuGet packaged MyLib over the newly built MyLib.

If I remove the MyLib folder from the package cache, the problem no longer occurs.

I believe there is a bug in NuGet 3 which for some weird reason references the NuGet package from the cache when it finds the project with the same name. Please do some investigation.

**Comment by yishaigalatzer** [comment]
Please share some more information, what version of visual studio and nuget are you using, what project type are you building, can you share a repro?

I believe we do have such a known issue, but to look into your issue I suggest you look into your projects or share them, because you have to reference the nuget package in the project for this to kick in.

This can also be an issue with your targets, in short this is extremely hard to figure out without a full repro.

**Comment by yishaigalatzer** [comment]
CC @emgarten

**Comment by Alovchin91** [comment]
@yishaigalatzer Visual Studio 2015 Update 1, Nuget Package Manager 3.3.0.167. The project type is Universal Class Library (DLL, .NETCore5). I'll try to make a repro as soon as possible.

**Comment by Alovchin91** [comment]
@yishaigalatzer @emgarten Here is the test project: https://github.com/Alovchin91/nuget-issue-test-project
Building the project in Release configuration will trigger the .targets file that will create a .nupkg file. I'm taking the .symbols.nupkg file usually, but I believe there will be no difference without symbols.
Create a new Blank Universal App project. Install the package into this project.
Come back to the test MyLib project and try to rebuild it. You will see the error message that there is an ambiguous call between MyExtensions.MyShowAsync in the source file and in the unpacked .dll from the package. But there is no nuget reference in the MyLib project!

**Comment by yishaigalatzer** [comment]
>  .symbols.nupkg file usually

I don't follow, you are not supposed to install these to a project or place them on your feed. These are meant to be sent to the symbol server

**Comment by Alovchin91** [comment]
@yishaigalatzer No problem, I believe there is no actual difference between the two for this issue.

**Comment by yishaigalatzer** [comment]
I would tend to agree. Briefly looking into your project, this looks like something @emgarten is working on fixing right at this moment. @emgarten can you please verify this project as well with your fixes (and if we need to make changes to the project.json in his project lets do that as well)

**Comment by Alovchin91** [comment]
@yishaigalatzer Just checked with the non-symbols package, on an almost clean VS install (other than the one I use daily), and the problem reproduced.

```
1>D:\VSProjects\Git\nuget-issue-test-project\MyLib\MyClass.cs(11,70,11,81): error CS0121: The call is ambiguous between the following methods or properties: 'MyLib.MyExtensions.MyShowAsync(Windows.UI.Popups.MessageDialog)' and 'MyLib.MyExtensions.MyShowAsync(Windows.UI.Popups.MessageDialog)'
```

**Comment by emgarten** [comment]
I'm not clear on the scenario. Adding a custom build target to reference a dll somewhere on disk causes the dll from a non-referenced nuget package to be loaded?

Does project.lock.json list the incorrect reference you are seeing?

**Comment by Alovchin91** [comment]
@emgarten If you mean the custom build target in a NuGet package that I meant in the initial post, forget it - the bug is reproducible without it. Just take the test project, build it in Release mode, reference the produced .nupkg in some other Universal project (so that it is put into local user cache), and then try to rebuild the test project. You will get the error.

The project.lock.json does list the reference, though it should not (I never added this reference):

``` xml
"MyLib/1.0.0": {
  "compile": {
    "lib/.NETCore50/MyLib.dll": {}
  },
  "runtime": {
    "lib/.NETCore50/MyLib.dll": {}
  }
}
```

**Comment by emgarten** [comment]
Rebuilding MyLib (the project) fails due to having another MyLib in the packages folder?

**Comment by Alovchin91** [comment]
@emgarten Yes. Could you please just run the test project?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@f5a4c758a7d0fe28ef576236f4de36c342e6603b
