### ISSUE TITLE
The call to MetadataResource.Exists is too expensive

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1931]
The call in the V3 resource - https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/MetadataResourceV3.cs#L72

Although rarely used is loading all the registrations instead of simply making a head request to the registration index.json

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
