### ISSUE TITLE
The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.

### ISSUE THREAD

**Issue by TehWardy** [NuGet/Home#1932]
I get this error intermittently when doing the following ...
1. Open VS
2. Load solution (any)
3. Open Package Manager Console

I can repeat the process with the same solution and it work fine after this error has occurred.
When this error is shown it fails to initialise the powershell console within VS and the window is unusable. 

I believe I am using the latest version of VS 2015 fully patched / service packed, and the latest version of nuget ... 
VS reports its verison as: Enterprise 2015 - 14.0.24720.00 Update 1
Nuget version is 3.3.0

...
In case this is important, my solution is entirely built against .Net 4.6.01038

**Comment by emgarten** [comment]
This looks like a dupe of https://github.com/NuGet/Home/issues/1638

**Comment by TehWardy** [comment]
I think you're right looking at what others are saying is happening, i've had pretty much the same behaviour. 
Apologies I couldn't find #1638 when I was logging this.

**Comment by Sn3akyP3t3** [comment]
I realize this is closed and so is the duplicate, but I was able to cause this error by experimenting with environment variables, particularly PATH, TEMP, and TMP environment variables where a script accidentally used SETX with incorrect values and triggered this error in PowerShell.  This is purely to document this behavior to assist someone in pinpointing another location to review for this.
