### ISSUE TITLE
RepositoryPath not working

### ISSUE THREAD

**Issue by krismy93** [NuGet/Home#1934]
Specifying repositoryPath in NuGet.config does not change the packages directory.
Packages still go to: C:\Windows\SysWOW64\config\systemprofile.nuget\packages

`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositoryPath" value="D:\NuGetPackages" />
  </config>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
      ...
  </packageSources>
</configuration>`

We are running as Local System User Account.  We only seem to be able to get the packages directory to change if we specify the directory through the command line. We are using Nuget v3.3.0

**Comment by emgarten** [comment]
Set the environment variable **NUGET_PACKAGES** to your global folder path. Both NuGet and MSBuild will use this.

_repositoryPath_ is only for packages.config. There is a _globalPackagesFolder_ setting for the project.json packages folder but MSBuild does not yet read it.

**Comment by krismy93** [comment]
Thank you that fixed my issue!
