### ISSUE TITLE
Fail to add xunit.runner.msbuild nuget package if project.json is used

### ISSUE THREAD

**Issue by jmelosegui** [NuGet/Home#1936]
Having the following solution

![image](https://cloud.githubusercontent.com/assets/450246/12333093/32314824-bac0-11e5-8a15-e819bab66a2f.png)

and the following project.json configuration:

``` json
{
  "supports": { },
  "dependencies": {
    "xunit.runner.msbuild": "2.1.0"
  },
  "frameworks": {
    ".NETFramework,Version=v4.6.1": { }
  },
  "runtimes": {
    "win": { } 
  }
}
```

When restoring nuget packages I get this error:

```
xunit.runner.msbuild 2.1.0 is not compatible with .NETFramework,Version=v4.6.1.
```

As soon as I replace the `project.json` file by `packages.config` with the following configuration

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="xunit.runner.msbuild" version="2.1.0" targetFramework="net461" />
</packages>
```

Restoring nuget packages runs without any problem.

**Visual Studio version 14.0.24720.00 Update 1**

**Comment by emgarten** [comment]
Try:

``` json
{
  "supports": { },
  "dependencies": {
    "xunit.runner.msbuild": "2.1.0"
  },
  "frameworks": {
    "net461": { }
  },
  "runtimes": {
    "win": { } 
  }
}
```

Frameworks use short names.

**Comment by jmelosegui** [comment]
@emgarten thanks for your answer. I changed the `project.json` (according to your suggestion) and still getting the exact same error though.

**Comment by yishaigalatzer** [comment]
@jmelosegui I assume you are using a csproj file and not an asp.net5 class library. Right?

**Comment by jmelosegui** [comment]
Correct. I am using a csproj as you can see from the project icon in the image.

**Comment by yishaigalatzer** [comment]
We think there is a bug in the package, and that packages.config is being a bit too forgiving here. We are verifying a package fix as we speak and will circle back when we know more.

**Comment by jmelosegui** [comment]
Thanks!!!!!

**Comment by ttrevorr** [comment]
any update on this?  I have the exact same issue.

**Comment by emgarten** [comment]
XUnit 2.1.0 contains a file `lib\portable-net45%2Bwin8%2Bwp8%2Bwpa81\_` instead of the expected `lib\portable-net45%2Bwin8%2Bwp8%2Bwpa81\_._` 

`_._` signals to NuGet that the package is compatible with that framework, without this compatibility errors will occur.

**Comment by dagood** [comment]
I'm hitting this package/issue now while trying to upgrade coreclr to xplat nuget restore. What's the status on this? Are we waiting for a fix from xunit?

/cc @ericstj

**Comment by bradwilson** [comment]
This will be fixed in 2.2 Beta 2, which will ship shortly after .NET Core / ASP.NET Core RC 2 ships.

**Comment by bradwilson** [comment]
> XUnit 2.1.0 contains a file lib\portable-net45%2Bwin8%2Bwp8%2Bwpa81_ instead of the expected lib\portable-net45%2Bwin8%2Bwp8%2Bwpa81_._

FWIW, this "expectation" is a new requirement, as the single underscore file works just fine with `packages.config` based projects.

**Comment by emgarten** [comment]
@bradwilson interesting, it may have been that case that the packages.config compat check was happy with any file at all in the directory. Project.json is stricter in how it checks for files to make sure that the project is actually going to use the package.

**Comment by yishaigalatzer** [comment]
@bradwilson & @emgarten we could theoretically add the _ as a valid entry. But we would need to justify it by scanning from the existing packages in nuget.org to see how prevalent that is.

Given that we want to move more folks over to project.json in the coming year, that is probably not a bad investment.
