### ISSUE TITLE
 SemVer-compatible build number with dot notation

### ISSUE THREAD

**Issue by DannyvanderKraan** [NuGet/Home#1938]
Although it is documentated very well that the dot notation for prereleases is not allowed (http://docs.nuget.org/create/versioning paragraph "Really brief introduction to SemVer") I would still humbly and kindly like to try to get this 'issue' on the backlog. 

I personally find it strange that visual studio 2015 adheres to semver and therefor this is the notation for prereleases: [assembly: AssemblyInformationalVersion("1.0.1-alpha.1")] to find out that in NuGet this is actually not allowed and it has to be:  [assembly: AssemblyInformationalVersion("1.0.1-alpha1")].

It's a minor thing, nothing major. But would still like to thank you for considering it.

**Comment by emgarten** [comment]
This is related to https://github.com/NuGet/Home/issues/1359

**Comment by yishaigalatzer** [comment]
Hey @DannyvanderKraan unfortunately fixing this seemingly minor issue, is a pretty large breaking change to all previous clients, because they first look at version and id before proceeding with any operation. Hence I don't see us taking this one small fix on it's own.

Visual Studio doesn't strictly adhere or follow semver, the assembly informational version is just an opaque string. So I see where this might look confusing, but it is unrelated.

The way forward with this is laid out in #1359, where we plan to add support to SemVer 2.0 in the client (but not necessarily in nuget.org right at the same time).

**Comment by yishaigalatzer** [comment]
Marking as duplicate because resolving #1359 should resolve this issue as well.

**Comment by DannyvanderKraan** [comment]
Ok, thank you for responding and clarifying. Good luck with resolving #1359 and other issues.

**Comment by tugberkugurlu** [comment]
> The way forward with this is laid out in #1359, where we plan to add support to SemVer 2.0 in the client (but not necessarily in nuget.org right at the same time).

This is going to confuse people and I am potentially hitting this on #2543. Everything would be so much simpler (especially the communication) if SemVer 2.0 was what NuGet supported.

**Comment by yishaigalatzer** [comment]
3.4.2 blocks semver2 until we get it all sorted out. But the nuget gallery will not allow it because that will break old clients with no recourse.

Also please don't push CI builds to nuget.org

**Comment by tugberkugurlu** [comment]
@yishaigalatzer 

>  But the nuget gallery will not allow it because that will break old clients with no recourse

Fair enough but at least the error message should indicate clearly why.

> Also please don't push CI builds to nuget.org

I am not pushing CI builds to NuGet.org, this is a pre-release https://www.nuget.org/packages/AspNetCore.Identity.MongoDB/1.0.0-rc1-1

If the intention is not to allow pre-release packages on NuGet.org, then it should be disabled there.

**Comment by yishaigalatzer** [comment]
Agree to both. We do absolutely support pre-release. Typically when you have the build number on the package you indicate a CI build vs a real pre-release that doesn't have it. But that is just a convention

@maartenba

**Comment by tugberkugurlu** [comment]
Do you know if MyGet supports this?

**Comment by maartenba** [comment]
Yup. For NuGet we'll improve the error message.

**Comment by maartenba** [comment]
Improved the error message on NuGet (to be deployed). https://github.com/NuGet/NuGetGallery/commit/4d91074f79325fbc4d18ee17d63fc9f90c3178b3
