### ISSUE TITLE
Cache Directory created in different directory

### ISSUE THREAD

**Issue by krismy93** [NuGet/Home#1940]
When running a nuget restore. Our NuGet cache is auto created at `C:\Windows\SysWOW64\config\systemprofile\AppData\Local\Temp\NuGetTempCache`

When we run `nuget locals all -clear` it removes the NuGet Cache at: `C:\Windows\system32\config\systemprofile\AppData\Local\NuGet\Cache`

Since these two directories do not match up and the NuGetTempCache directory continues to get very large.

Is there a way to specify where the cache directory is created, like specifying an environment variable?

**Comment by emgarten** [comment]
> Since these two directories do not match up and the NuGetTempCache directory continues to get very large.

How are you setting that location? Is clear not using NUGET_PACKAGES?

**Comment by yishaigalatzer** [comment]
@krismy93 thanks for the feedback. Looks like there are two issues here:
1. You are running nuget with a system account, which leads to your cache folder being created in the systems folder. I would make sure you run under a proper user profile, and then the cache location will be created and something like `c:\users{username}\appdata\local
2. You can just clear you %temp% folder regularly, the files on the top are extra temp files, not cache's, we seem to be not clearing them well enough, but I don't see reference to "NuGetTempCache" no more in nuget.client 

CC @xavierdecoster

**Comment by xavierdecoster** [comment]
When running `nuget.exe locals all -clear`, we are clearing the global packages folder using `SettingsUtility.GetGlobalPackagesFolder(ISettings)` ([here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/LocalsCommand.cs#L145)), which also checks for the `NUGET_PACKAGES` environment variable ([here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L134)).

In addition, we also clear the local packages cache folder, which is typically found at `%localappdata%\NuGet\Cache`. I could not find any reference to _NuGetTempCache_ either. However, the code path references `MachineCache.Default` from the old **NuGet.Core** package ([here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/LocalsCommand.cs#L162)), which under the hood also checks for a `NuGetCachePath` environment variable (and when none found, sticks to the default `%localappdata%\NuGet\Cache` location).

Two questions here:
- @krismy93 do you by any chance have a `NuGetCachePath` environment variable defined?
- @emgarten do we have replacement code in the new NuGet.Core bits to avoid the usage of `MachineCache.Default` from the old NuGet.Core?

**Comment by krismy93** [comment]
@xavierdecoster @yishaigalatzer I do not seem to have a `NuGetCachePath` environment variable defined.

I tried to set the environment variable to `NuGetCachePath` but it seems to still be creating the cache directory at `%localappdata%\Temp\NuGetCache`. The only difference is that when i set the environment variable, the `nuget.exe locals all -clear` recognized that I had changed the cache directory.

The cache seems to be created at `%localappdata%\Temp\NuGetCache` regardless of if I use the System Account or a user account.

Is there any other place that I could accidentally be setting the cache directory to be created elsewhere? I

**Comment by yishaigalatzer** [comment]
I think we are looking at a completely different folder than the cache.  To verify can you grab 3.4 bits from nugetbuild feed on myget

What are we changing in 3.4:

Unify ask temp folder usage to a sub folder named nugetscratch.
Adding that folder to the clear command.

Step 1 done
Step 2 in progress

**Comment by yishaigalatzer** [comment]
@krismy93 can you pick up nuget 3.4 from the myget nugetbuild feed, and confirm your scenario is now handled?
