### ISSUE TITLE
RID inferral + guardrails = some sadness

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1941]
Because we infer `[osname]-x86` and `[osname]-x64` as RIDs, we will often attempt to restore `dnxcore50/osx.10.10-x86` (for example). This fails guardrails because it is not supported (there are no 32-bit packages for OSX). We need to change this behavior to only infer the `-x64` RID (at least for now).

I've worked around this in `dotnet-restore` for now.

**Comment by analogrelay** [comment]
It should be as simple as removing this line: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/Utility/RequestRuntimeUtility.cs#L48

That would cause applications running on Mono, on a 32-bit platform, using a NuGet package which includes native components to have to manually specify that RID when restoring, but I think that's OK

**Comment by emgarten** [comment]
@anurse do we want to remove it always, or just for osx?

**Comment by analogrelay** [comment]
Just for non-windows. Since the primary use case for RIDs is CoreCLR and there is no 32-bit CoreCLR on non-Windows OSes

**Comment by emgarten** [comment]
nuget/nuget.client@ac28dabff6e514e3ac094c289718b9252521f045
