### ISSUE TITLE
Feature request: automate signing of assemblies in NuGet packages lacking strong names

### ISSUE THREAD

**Issue by maitre-matt** [NuGet/Home#1942]
Installing NuGet packages into projects using strong-name signing is like playing Russian roulette: there is a good chance it won't build because assemblies are not signed. It would be great if NuGet automated signing assemblies, either at packaging time or at installation time using tools along the line of
https://github.com/brutaldev/StrongNameSigner

**Comment by yishaigalatzer** [comment]
NuGet is not going to get in the middle of this process. Strong name signing is a package owner concern. NuGet is not in a position or desire to alter package content.

The decision on utilizing strong name signing comes from the .net team, their repo is at https://github.com/dotnet/corefx.

**Comment by davidfowl** [comment]
This is something that should be done at build tie if anything, not package install time. There's actually an msbuild task called StrongNamer that does what you want
