### ISSUE TITLE
NuGet.exe doesn't include ApiKey header in all messages in a push command

### ISSUE THREAD

**Issue by juliank** [NuGet/Home#1945]
We're trying to push packages from our build server to a NuGet server that is located behind a different corporate firewall. This firewall normally requires two-factor authentication, but for our build server we've set up a rule to allow traffic from that specific IP if the http header `x-nuget-apikey` is present. This doesn't seem to work as intented, and from the firewall's logs it appears that only some requests have the `x-nuget-apikey` header set.

We've been trying to trace exactly what messages are being sent from the build server by using WireShark, but this has been a bit difficult since the communication is over SSL using a private key we don't have access to. By comparing the communication against an internal NuGet server without SSL though, I think we've managed to figure out the following message flow:
1. Run `NuGet.exe push package.nupkg -ApiKey API-XXX -Source http://nugetserver.com/nuget/packages -Verbosity detailed` on the build server (from console, to debug)
2. Build server sends GET message to NuGet server: `GET /nuget/packages HTTP/1.0`
3. NuGet server responds with `HTTP/1.1 405 Method Not Allowed`, also stating that the allowed response is `PUT`
4. Build server sends PUT message to NuGet server. Console output: `PUT http://nugetserver.com/nuget/packages/` (followed by success message `Your package was pushed.)`
5. Package is successfully uploaded to the NuGet server

Why NuGet sends the GET message before the actual PUT to upload the package we don't know. Perhaps to verify the existence of the server? This at least seems to be the root of our problems when trying to push packages to the secure NuGet server behind the firewall (the `-Source` is then `https://securenugetserver.com/nuget/packages`):

From what we can tell, the `x-nuget-apikey` http header is not included in the GET request (step 2). Because of the rules in the firewall, the response from the server (step 3, which is actually a response from the firewall, since we never get through to the NuGet server) is a `200 OK` containing the two-factor authentication login page with the URL `https://securenugetserver.com/my.policy/`. This again leads to in step 4 an attempted push to this URL: `PUT https://securenugetserver.com/my.policy/`, which naturally results in an exception, since there is no NuGet server listening to that URL.

And to further indicate that the missing http header _is_ the issue, we can reproduce the response from the NuGet server/firewall by invoking the GET message from PowerShell on the build server:
- `Invoke-WebRequest -Method GET -Uri "https://securenugetserver.com/nuget/packages" -Headers @{ "X-Nuget-ApiKey" = "API-XXX" }` results in the expected `405 Method Not Allowed`
- `Invoke-WebRequest -Method GET -Uri "https://securenugetserver.com/nuget/packages"` results in a `200 OK` containing the login page of the firewall

Are we doing something obviously wrong here, or is there an actual bug in the way NuGet.exe handles/includes the ApiKey when pushing?

**Comment by yishaigalatzer** [comment]
I don't think we should send the API key on any get request. I suggest you find a different way to configure your firewall to allow for all these requests to go through.

**Comment by juliank** [comment]
But what is the reason behind the GET request in the first place (if my understanding of the message flow is correct)? When you issue a nuget push, shouldn't it be sufficient with the one PUT request?

**Comment by yishaigalatzer** [comment]
This is a fair question, I didn't dig into this. But given that this has been the behavior for quite a few years now, I'm not inclined to jump on this right away and try to fix it, because I'm not sure about all the side effects.
