### ISSUE TITLE
Remove nuget.core v2 dependency

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1947]
Remove the legacy v2 nuget.core.dll dependency from the Visual Studio extension and nuget.exe.
- [x] Port and update pack
- [x] Unzipped repository support
- [x] OData feed reader for v2 sources
- [x] Flat folder repository support
- [x] Version folder repository support
- [x] List command  (Now covered by #3177)
- [ ] NuGet.Credentials (Now covered by #3178)

**Comment by yishaigalatzer** [comment]
Oh well, moving to 3.5

**Comment by alpaix** [comment]
Updated milestone due to validation requirements.
@emgarten Does it make sense to split the issue to two, one per version?
-or- we could start an epic :smiley_cat:

**Comment by rrelyea** [comment]
Yes, let's split into granular issues. I'm doing now.
