### ISSUE TITLE
Remove Logger.Instance

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#1951]
Logger.Instance static should be removed from the codebase, it leads to scenarios where logging doesn't work or potentially crosses the paths.

**Comment by xavierdecoster** [comment]
The static `Logger.Instance` got recently introduced as part of the _least impacting_ change to add http request logging, see https://github.com/NuGet/NuGet.Client/pull/138

Removing the static means traversing many layers of code, passing along an ILogger to have the it available in the protocol's resource classes, which is _very intrusive_. What scenarios are not working?

**Comment by yishaigalatzer** [comment]
Yes, that's what needs to happen. 
1. We don't want static variables floating around
2. This does not work in visual studio, and blocks the ability to set a logger for testing purposes

**Comment by xavierdecoster** [comment]
@yishaigalatzer there's no single ILogger interface that works for both Visual Studio, commandline and PowerShell console host, making it impossible (in its current state) to require a logger instance in the protocol's resources that works for all. I think we need to unify/consolidate the different loggers first before we can force the requirement in the down-level APIs.

Currently, there's at least the following variety of different loggers: 
- NuGet.ILogger in NuGet.Logging.dll
- NuGet.PackageManagement.UI.INuGetUILogger in NuGet.PackageManagement.UI
- NuGet.PackageManagement.PowerShellCmdlets.NuGetPowerShellBaseCommand

In addition, there's a:
- NuGet.ProjectManagement.MessageLevel in NuGet.ProjectManagement
- NuGet.CommandLine.CommandOutputLogger.LogLevel in NuGet.CommandLine
- VerbosityLevel enum in OnBuildPackageRestorer (which in turn implements NuGet.Logging.ILogger)

**Comment by xavierdecoster** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/e146e57c29a464032ddb3a9404428633d16531a0
