### ISSUE TITLE
Break compatibility between netstandard and dotnet

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1963]
We should break compatibility between `netstandard` and `dotnet`. `dotnet` is going to be phased out, so let's not perpetuate the legacy :). Until packages update, `netstandard`-based projects can always use `imports` to add support (made easier after #1962 as well).

Similarly, `netstandardapp` will support `netstandard` (as before) and will therefore also lose access to `dotnet`. Mappings of v2 PCL profiles will remain tied to `netstandard` and be unaffected.

/cc @yishaigalatzer @ericstj @lodejard @davidfowl @joelverhagen @emgarten

**Comment by joelverhagen** [comment]
Closed with NuGet/NuGet.Client#209.
