### ISSUE TITLE
GetInstalledPackages() doesn't support C++

### ISSUE THREAD

**Issue by h2rashee** [NuGet/Home#1965]
IVsPackageInstallerServices throws an ArgumentException when GetInstalledPackages() is called on C++ projects.

**Comment by emgarten** [comment]
what version of nuget?
what version of Visual Studio?

**Comment by arturl** [comment]
VS 2015 Update 1. NuGet.VisualStudio version 2.8.6

**Comment by yishaigalatzer** [comment]
@arturl NuGet.VisualStudio in 2015 should be 3.3, can you validate?

Can you help us with understanding the priority of this item?

**Comment by emgarten** [comment]
Closing due to lack response.
