### ISSUE TITLE
CopyLocal set twice when using install.ps1 

### ISSUE THREAD

**Issue by jmecosta** [NuGet/Home#1967]
Hi guys,

hope you can help with this, vs 2015 update 1. package manager 3.3.0.167. powershell 5.0

we have a instal.ps1 where we do this:

```
            if ($gacRefences -contains $reference.Name + ".dll")
            { 
                $reference.CopyLocal = $false;
                Write-Host "Disable Copy Local for GAC Reference: " $reference.Name
            }
```

For some reason, in this visual studio version i get duplicated entries in project file like this

```
      <Private>True</Private>
      <Private>False</Private>
```

I have vs 2013 and 2.8.60723 and this does not happen. i would be ok with this however some users using vs 2013 and 2.8.60723 still get the duplicated entries.

their powershell is 3.0, and they will be updating it to 5 to see if it works in vs 2015.

Have you heard about reports about this before.

thanks in advance

jorge costa

**Comment by yishaigalatzer** [comment]
Hey @jmecosta we haven't heard reports of this.

To be honest this is one of the reasons we are deprecating install.ps1 in the next evolution of nuget, it exposes a very rough surface area, and one that we cannot support. We see packages being broken regularly across releases of visual studio and sometimes even across updates. So our goal is to provide a more uniform experience and add first class features to NuGet proper to control this kind of scenario.

Sorry I couldn't be of more help. Feel free to continue the discussion, or if you feel this was closed erroneously please let me know.
