### ISSUE TITLE
This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them

### ISSUE THREAD

**Issue by ktsjackson** [NuGet/Home#1968]
VS 2013 using MsBuild definition with TFS 2013.

I have gone through that old thread (http://nuget.codeplex.com/workitem/1879) and have been trying to resolve this issue. From the steps below, when I get to "right-click a project in the solution and "Manage nuget packages". Then you will finally get a bar across the top of this UI with a message" There is never a crossbar. A new window opens for xxx.sln - Manage NuGet Packages. No idea what I am supposed to do after that. Looks similar to the 'Extensions and Updates' window.

What worked finally was to 
check Tools|Options|package manager|Package restore
right-click the solution and "enable package restore"
right-click a project in the solution and "Manage nuget packages".
Then you will finally get a bar across the top of this UI with a message that some packages are missing, click to get them. Clicking this button gets the packages.

**Comment by yishaigalatzer** [comment]
This feature was deprecated, and we do not recommend using it going forward. It causes many issues with packages that carry targets and props.

I would recommend (of course if you can), moving to Visual Studio 2015 and removing the nuget targets from the project

**Comment by pabrams** [comment]
How do I "remove nuget targets from the project"
