### ISSUE TITLE
Build task needs a way to specify ".NETStandard.*"

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#1970]
The PCL targets currently hardcode ".NETPlatform, Version=v5.0" for their NuGetTargetMoniker. This needs to change in order to support ".NETStandard", but currently portable needs to include the specific netstandard version in the project file so the targets can pick it up. To avoid this (and enable users to retarget by only editing their project.json), the build task should have a way to indicate that the netstandard version is floating and it should choose the best available one from the lock file.

**Comment by rchande** [comment]
cc @jasonmalinowski

**Comment by ericstj** [comment]
What happens when folks have multiple versions in the project.json?  Warn/error?

**Comment by jasonmalinowski** [comment]
Probably error and require it to be forced in that place. is there an actual user scenario there for doing that...?

**Comment by ericstj** [comment]
Project.json usage in CLI commonly uses this.  In CoreFx we have projects that look like portable projects and have multiple configurations for cross-compilation that result in a different value for NuGetTargetMoniker.  I'm not suggesting first class support for that in PCL, but given the syntax is supported in project.json it'd be good to not just silently select one of many based on what we think is best.

For folks that really want to have many framework sections in the PJ, make them specify NuGetTargetMoniker.

**Comment by jasonmalinowski** [comment]
Well, I think our plan would be that the build task would just accept a NuGetTargetMoniker of ".NETStandard,Version=v*" (or something, syntax TBD) which would mean to do this, and that's what the PCL targets would specify. If you want to have multiple targets in your project.json and pick them by overriding the property set by the PCL targets, go right ahead. I guess the onus is on @rchande and I to test that to make sure we respect whatever setting you might have.

We won't do magic without the property saying do magic; magic will just be the default.

**Comment by rrelyea** [comment]
Not sure the right milestone for you guys to schedule this in.

**Comment by emgarten** [comment]
@rchande is this still needed?

**Comment by rchande** [comment]
Not sure. I think this experience no longer exists (PCL net standard). @Pilchie to confirm.

**Comment by Pilchie** [comment]
Correct - we don't need this anymore, there is no .NET Standard experience with project.json.
