### ISSUE TITLE
Convert NuGet.* libraries to use netstandard instead of dnxcore50

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1971]
The NuGet.\* libraries should use a `netstandard` TFM instead of `dnxcore50` since they are portable libraries.

**Comment by borgdylan** [comment]
Please also leave support for the desktop framework. Those bits allow me to build the mono version of the dotnet cli for Ubuntu x86.

**Comment by analogrelay** [comment]
`netstandard` does support desktop framework and Mono/Xamarin explicitly, it's the modern replacement for portable. Having said that, if necessary, we can cross-compile. Desktop support is definitely not going away.

**Comment by borgdylan** [comment]
The current dotnet5.6 supports .net core only. Will that include desktop in the future?

**Comment by analogrelay** [comment]
You are correct about `dotnet5.6`/`netstandard1.5`. NuGet should try to avoid that if possible and use an earlier version that does support Desktop. I don't know the specific plans, but in general Desktop will continue to catch up (at it's usual, somewhat slower, pace ;)). It's up to Mono to figure out which versions they want to target. Last I heard, they just wanted us to map them to the highest version at all times.

See https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md#mapping-the-net-platform-standard-to-platforms (note, `netstandardX.Y` is the same as `dotnet(X+4).(Y+1)`, and `netstandard1.5` is new, not on that list, and only supports Core right now).

In general, Libraries should target the **lowest** `netstandard` version they can based on desired API surface. Lower versions give broader compatibility.

**Comment by borgdylan** [comment]
This tip should be given to the corefxlab people since other projects like the dotnet cli use their stuff.

**Comment by emgarten** [comment]
NuGet packages now target netstandard.library 1.5.0 in nuget 3.5.0.
