### ISSUE TITLE
nuget.exe should only load MSBuild when needed

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1972]
Today nuget.exe loads msbuild at the start even if the user is restoring a project.json or packages.config file. These operations do not use MSBuild and block xplat scenarios.

**Comment by yishaigalatzer** [comment]
This is important for xplat builds used by the dotnet team and others, because it slows things down a lot because it needs to find, load and jit msbuild.

**Comment by emgarten** [comment]
This has been fixed. Restore, Update, and Pack will now load msbuild lazily.

NuGet/NuGet.Client@5f4f39f2b5c67192294e4c3b7c5931196404a9c8
