### ISSUE TITLE
Clean up NuGet3 XPlat Restore console output

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1973]
There are a few small tidy-up changes that should be made to the XPlat restore:
- [x] Don't return negative exit codes, they are bad on Unix (POSIX exit codes are expected unsigned integers between 0 and 255)
- [x] Catch exceptions at the Program.Main so they don't crash the process :)
- [x] Move most `info` spew down to `trace` level, so a "quieter" `info` level can be used as the default trace
- [x] Show a summary view like DNU did, including a message indicating if all restores completed/failed (right now we just show a completed/failed for each individual restore so when you do a bulk restore of multiple projects and the last one succeeds, it looks like they all do; the exit code is correctly non-zero, but the message is weird)

**Comment by davidfowl** [comment]
Adding to this, only showing NotFound in the http request output is totally useless. It should match DNU with GET, and CACHE and the response times for each request. All of the important information is currently missing from the restore output.

**Comment by analogrelay** [comment]
Ah, that makes sense... I was thinking "Wow... if it didn't find anything, how is the restore working?"

**Comment by emgarten** [comment]
NuGet/NuGet.Client@6fbfa2294cf277abfa0f2b659956ec6f6119da2f

**Comment by joelverhagen** [comment]
Addressed the third item about too much default noise (see https://github.com/NuGet/NuGet.Client/pull/229). In particular:

> Move the following sorts of messages from information level to verbose.
> 1. `Running restore with 16 concurrent jobs.`
>    - The level of restore parallelism.
> 2. `NotFound https://api.nuget.org/v3-flatcontainer/netstandard.platform/index.json 247ms`
>    - Any request or response status when fetching a package over HTTP.
> 3. `All packages are compatible with DNXCore,Version=v5.0 (win7-x64).`

**Comment by borgdylan** [comment]
Also, would it be possible to exit cleanly (no negative exit code) if no runtime bits were found for the current runtime id? Such errors are thrown out on mono/x86 due to no coreclr support. These errors however are beningn since the lock file is still made correctly.

**Comment by analogrelay** [comment]
We've had a lot of discussions about that (/cc @ericstj @davidfowl). In general, we'd rather fix the issues that cause these runtime compatibility check failures. We removed the automatic inference of x86 runtimes because of the CoreCLR issues, as a temporary change, but there does need to be a way to restore it for Mono targets, since they do fully support x86.

**Comment by borgdylan** [comment]
Indeed with a host of other cpu architectures. I think that for mono errors like that can be ignored.

**Comment by joelverhagen** [comment]
Finished item 4 in the checklist with https://github.com/NuGet/NuGet.Client/pull/246. Since this is the last open item, I will close this issue.
