### ISSUE TITLE
version list is not populated when the installed package version not available from source 

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#1974]
The version list is not populated when the installed package version is not available from the particular source.

Scenario:
Local Source: A.1.0.0, A.2.0.0, A 3.0.0. A 4.0.0.
nuget.org/api/v2: A.1.0.0, A.2.0.0, A 3.0.0

Installed: A 4.0.0.

select source nuget.org/api/v2

Select the Installed tab.

Expected: version list shows A.1.0.0, A.2.0.0, A 3.0.0
Actual: version list is empty.

Examining the network traffic with fiddler and we see the FindPackageById returning the correct data - i.e. the list of versions 1 through 3. So this looks like a bug in the UI layer.

**Comment by emgarten** [comment]
closing due to a lack of feedback on this.
