### ISSUE TITLE
How to avoid having win81 references and .targets pulled to UAP on Nuget Client

### ISSUE THREAD

**Issue by rmarinho** [NuGet/Home#1975]
I m having troubles with this "feature", can i avoid it?

https://github.com/NuGet/NuGet.Client/blob/59b1a03d557f4f89a48ddd401704a6c60ed99dc8/src/NuGet.Core/NuGet.Frameworks/DefaultFrameworkMappings.cs#L299

IF i have specific assemblies and for example .targets and .props in \build\win81\x86 folder .. When i install the package on a Universal Windows project it references the stuff in win81, for example my .props file for win81 adds Bing.Maps.SDK and i don't want that in UAP.

Is there a way to avoid this? 

Thanks

**Comment by emgarten** [comment]
Targets can be excluded on a per package basis. See: https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

It would look similar to this:

``` json
  "dependencies": {
    "Bing.Maps.SDK": {
      "version": "1.0.0",
      "exclude": "build"
    }
  }
```

Note: this feature is only available in NuGet 3.3.0 (Visual Studio 2015 Update 1)

**Comment by emgarten** [comment]
@rmarinho did this solve your issue?

**Comment by rmarinho** [comment]
hey @emgarten i worked around the issue by making sure (add an extra condition) that the contents of my .props and .targets file only executed when in the proper platform win81 .. something like this:
 `('$(TargetPlatformIdentifier)' == 'Windows')`

```
<Target Name="PlatformCheck" BeforeTargets="InjectReference"  Condition=" (('$(TargetPlatformIdentifier)' == 'Windows') AND ('$(Platform)' != 'x86') AND ('$(Platform)' != 'ARM') AND  ('$(Platform)' != 'x64') )">
 <Error  Text="$(MSBuildThisFileName) does not work correctly on '$(Platform)' platform. You need to specify platform (x86 / x64 or ARM)." />
</Target>
```
