### ISSUE TITLE
Investigate impact of .exe files in lib 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1976]
Determine how many packages include .exe files in the lib folder to see if it will impact UAP.

see: https://github.com/NuGet/NuGet.Client/pull/220

**Comment by analogrelay** [comment]
For the record, NuGet 2 actually already considered `.exe` as a valid reference when in `lib`. So this is really just bringing NuGet 3 in line with existing NuGet 2 behavior /cc @yishaigalatzer 

https://github.com/NuGet/NuGet2/blob/2.11/src/Core/Packages/Constants.cs#L75

https://github.com/NuGet/NuGet2/blob/2.11/src/Core/Packages/LocalPackage.cs#L251

**Comment by emgarten** [comment]
NuGet 3 supports it also for packages.config scenarios. It's just project.json where .exe was excluded.

**Comment by analogrelay** [comment]
Sounds like this was a bug that needed fixing anyway then :)
