### ISSUE TITLE
v3 Restore on Mac creating lots of NuGet.Configs

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#1977]
Every time I run `dotnet restore`, I get a `Library/Application Support/NuGet/NuGet` folder created under the project directory for each project in the restore. This is obviously not ideal :). It should probably live somewhere under `~/`

/cc @yishaigalatzer @emgarten @davidfowl

**Comment by yishaigalatzer** [comment]
@zhili

**Comment by analogrelay** [comment]
Brain dump ahead :)

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/NuGetEnvironment.cs#L71 needs some review.

### What they mean
- `ProgramFiles`/`ProgramFiles(x86)` - The location programs are installed to
- `UserProfile` - The root of the user's profile directory
- `CommonApplicationData` - **Machine-global** application data (`C:\ProgramData` on Windows). This is an appropriate place for machine-level config and caches.
- `ApplicationData` - **User-global** application data (on Windows, this folder is also "roamed" across machines in a domain, but that **is not the case** on other platforms). This is an appropriate place for user configuration files.
- `LocalApplicationData` - **User- and Machine-global** application data, i.e. data that is specific to **both** the User and the Machine. Windows is the only platform that makes the distinction between "User-global" (Roaming) and "User- and Machine-global" (Local). This is an appropriate place for user-level caches, for example.
- The above all mirror the values from the [Desktop CLR type](https://msdn.microsoft.com/en-us/library/system.environment.specialfolder%28v=vs.110%29.aspx), but I think it might be valuable to add a few NuGet-specific items, like `MachineCache` and `UserCache`

I would avoid trying too hard to abstract everything behind the `System.Environment` type. Instead, if we need to have a central `NuGetPaths` helper with more NuGet-specific choices, that would be clearer. For example, on Windows the User-level NuGet caches can be in `LocalApplicationData`, but on Mac OS X, there is actually a Caches directory(`/Library/Caches` and `~/Library/Caches`), so we should probably use those and avoid trying to make `LocalApplicationData` abstract over all of that. In general, I believe it's more important for NuGet to fit well into each OS than to have a rigid abstraction.

Below are some suggestions per OS

### Mac OS X
- `ProgramFiles`/`ProgramFiles(x86)` - Return empty string or throw, this directory is invalid
- `UserProfile` - Return value of `HOME` env var (this is correct already)
- `CommonApplicationData` - `/Library/Application Support` (the `NuGet` name is not required here since this method is expected to return the **root** of the app data folder, not the product-specific folder underneath it, this is why the path above has two `NuGet`'s) - The code is currently **incorrect** here
- `ApplicationData` - `$HOME/.nuget` - The code is currently **incorrect** here. We could use `Library` (as the current code does) but honestly I think for this data having a `.` folder in HOME is a little preferable. That keeps it in sync with Linux.
- `LocalApplicationData` - `$HOME/.nuget` - Mac OS X does not have a distinction between Local and Roaming application data. The code is currently **incorrect** here
- Have a separate helper/or enum value or something to ensure that on Mac OS X, the caches go to `/Library/Caches/NuGet` (for Machine-wide) and `$HOME/Library/Caches/NuGet` (for User-wide)

### Other Unixes (Linux, FreeBSD, etc.)
- `ProgramFiles`/`ProgramFiles(x86)` - Return empty string or throw, this directory is invalid
- `UserProfile` - Return value of `HOME` env var (this is correct already)
- `CommonApplicationData` - `/etc` - That's where machine-level config goes in Unix. So the machine-wide NuGet.Config should be `/etc/nuget/nuget.config` (or whatever casing makes sense). The code is currently **incorrect** here
- `ApplicationData` - `$HOME/.nuget` - 
- `LocalApplicationData` - `$HOME/.nuget` - Mac OS X does not have a distinction between Local and Roaming application data. The code is currently **incorrect** here
- Have a separate helper/or enum value or something to ensure that on Linux, the caches go somewhere under `/var` (for Machine-wide) and `~/.nuget` (for User-wide).

**Comment by yishaigalatzer** [comment]
I believe this is duplicating what glen already spec'd and zhi implemented (which is what I suspect introduced this bug). Can we go back to the original bug and did the requirements?

**Comment by yishaigalatzer** [comment]
Also the "paths" class exists in nuget.common package

**Comment by analogrelay** [comment]
Cool, I was just noticing this in the late rush to get NuGet integrated and wanted to capture it somewhere. Feel free to dup this over some other bug if you've got one. The P0 change needed (preferably early next week) is to stop spewing the NuGet.Config files everywhere (specifically https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/NuGetEnvironment.cs#L99 needs to ensure the path is prefixed with the value of `HOME` because `Library/Application Support/NuGet` ends up pointing to a relative path under the current directory)

**Comment by yishaigalatzer** [comment]
Yup. I believe that's the bug introduced here. We just need to agree on the locations. I hear redhat might have them not 100% the same

**Comment by analogrelay** [comment]
Using `/etc` for machine-wide and `~/.nuget` for user-wide should be pretty standard across all non-Mac Unixes. Redhat might have other places you _could_ put the files, but I'd err on the side of the [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) over individual distro patterns

**Comment by davidfowl** [comment]
This issue is pretty bad and needs to be fixed ASAP.
