### ISSUE TITLE
contentFiles BuildActionList missing Android and iOS for whitelist

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#1978]
Android projects need special Build actions that are not on the whitelist:

https://github.com/NuGet/NuGet.Client/blob/3f009661481384c5afaeadc23beceed309bc5ad4/src/NuGet.Core/NuGet.Commands/ContentFiles/ContentFileUtils.cs#L56-L69

At a minimum they need:
- `AndroidAsset`
- `AndroidResource`

iOS apps also need:
- `BundleResource`

The fact that contentFiles uses a whitelist approach means that Android and iOS Xamarin projects cannot correctly specify resources to include using this mechanism.

**Comment by clairernovotny** [comment]
Would be great to get this into 3.4 as this change alone should be very minor and fits the x-plat theme.

**Comment by clairernovotny** [comment]
PR for this here: https://github.com/NuGet/NuGet.Client/pull/225

**Comment by yishaigalatzer** [comment]
Does the xamarin project system support project.json ?

**Comment by clairernovotny** [comment]
It does in VS. I successfully use MonoAndroid,v6.0 and MonoTouch,v1.0 and  Xamarin.iOS,v1.0 here:

https://github.com/xunit/devices.xunit/tree/master/src

Look at the Xamarin projects, they're all project.json based.

Xamarin Studio does not support it yet but I know they're working on it now that the targets/tasks are public.

**Comment by yishaigalatzer** [comment]
I think this requires a bit more thought. At this point we are allowing arbitrary actions and we need to figure out how we communicate to the users what is being picked up what is not and how to suppress warnings

**Comment by clairernovotny** [comment]
What is this whitelist for then? I just stumbled across it and thought that the Xamarin stuff could be added. I haven't tried it, but you're saying that I can already do this?

**Comment by yishaigalatzer** [comment]
No I'm not saying that. I'm saying that if your add more stuff to the list it becomes arbitrary and hence it needs more thought.

When it comes to submitting a pull request, we really expect you to test the scenario end to end and cover it with a functional test if possible.

**Comment by clairernovotny** [comment]
How should this be tested? It's not exactly easy to build this stuff locally :) This is basic use of buildAction, nothing fancy. These item types do not even require metadata (unlike Page and ApplicationDefinition, which are causing issues in the other thread).

The Xamarin targets simply need these resource types this way to "do their thing." 

What is the reasoning for putting a whitelist to begin with? Why not allow any build action type? I certainly see a case for fixing any case-sensitivity of a few well-known item types, but I'm not seeing a reason to block any arbitrary type.

**Comment by yishaigalatzer** [comment]
First: It is extremely easy to build locally. Type build.ps1 - done.

Test - f5

Second - the white list was put for things we tested or things we thought make sense. Looking at it or seems too open. I'm concerned with package owners and users producing/consuming packages that don't work without any warnings or way to diagnose. Project.json is supporting a narrow set of targets at the moment and expansion is fine but needs to be thought through.

**Comment by clairernovotny** [comment]
I can buy the argument that this needs to be thought through on a general level, but at the very least three specific item types I mentioned initially fit the theme and original intent. They enable resources that are part of a NuPkg to be used in an immutable read-only fashion by the system.

It's just that Android and iOS require something other than `EmbeddedResource` to work. 

Without these, it's a blocker on Xamarin projects using `project.json`. Given the small scope of the change, I'm really hoping these three can hit 3.4.

**Comment by yishaigalatzer** [comment]
In general Xamarin projects are not tested, nor supported by anyone, and taking in things that make it look like it is, is really concerning to me. I see your point though, so I'd like to think more about the design.

But first I would start with testing it, then we can talk further.

**Comment by clairernovotny** [comment]
I tested this as you can see here:
https://gist.github.com/onovotny/5d007fd323a8393412b9

It worked _prima facie_, but it uncovered another issue in that additional changes are required in the Android tasks for determining the correct output directory. That said, not blocking it is a necessary first step before the other build tasks can be fixed. 

As far as NuGet should be concerned, it did add additional Items with the correct type that the other build tasks could see. That should be all NuGet needs to do. The rest is on third parties.

**Comment by yishaigalatzer** [comment]
Merged https://github.com/NuGet/NuGet.Client/pull/225
