### ISSUE TITLE
Need way to specify item metadata on contentFiles

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#1979]
Right now for contentFiles you can specify a buildAction and copyToOutput. Some content types require additional metadata to be set on the items.

For example, Page and ApplicationDefinition XAML items need the `Generator` metadata set to `MSBuild:Compile`. Xamarin Form's XAML pages need to be set as `EmbeddedResource` with their `Generator` set to `MSBuild:UpdateDesignTimeXaml`.

Many content types also may have a build action of `None` but need to specify a custom metadata to operate correctly -- think of a `.tt` file. It needs to have the metadata to specify the right generator type.

There currently does not seem to be a way of using those kinds of content with contentFiles.

Ideally there should be a way of specifying multiple arbitrary metadata/value pairs for an item.

**Comment by davidfowl** [comment]
I don't see the benefit of supporting msbuild item metadata like this. Why not just use a .props file? The value of the `contentFiles` section is that other project systems (like the CLI) can consume things like this. If we support putting all of the msbuild metadata in there, it might as well be a props files.

**Comment by clairernovotny** [comment]
One of the main reasons is that NuGet 3.x took away the ability to have content files in a nuget package. This broke many existing scenarios for package authors. `contentFiles` was supposed to restore that but it still leaves things broken, like the inability to put XAML content in a package and have it work correctly.

**Comment by davidfowl** [comment]
> contentFiles was supposed to restore that but it still leaves things broken, like the inability to put XAML content in a package and have it work correctly.

It's not a direct replacement for content. Why not use msbuild props?

**Comment by clairernovotny** [comment]
A props file alone isn't enough. We need the pp translation to have namespaces correct, something that a props file cannot do. I also need to ensure that they don't accidently change the source file as it'd be shared amongst all packages in the new nuget model. the contentFiles approach does this by applying the transform and putting a copy in the obj\NuGet dir.

**Comment by yishaigalatzer** [comment]
Sounds like something we can discuss a design for. `ContentFiles` is not intended to solve every single scenario, but we could look at what extra feature we want to light up.

The key here is that contentfiles is not a way to define msbuild properties, but a generic way to define build actions so things can compile in different build systems.

In general this is something I think the build task can do and even better specific build tasks for specific projects can do.

For now I'm pushing this ask and discussion out of the 3.4 release.

**Comment by 304NotModified** [comment]
+1

**Comment by yishaigalatzer** [comment]
@304notmodified for now you can use msbuild props for this, its a little more painful butbitb fully addresses the scenario

**Comment by rrelyea** [comment]
@emgarten - please check this scenario out...as you are doing contentfiles work now.

**Comment by emgarten** [comment]
ContentFiles are now written out to .props files. Additional metadata can be added through msbuild targets/props.
