### ISSUE TITLE
[NuGet.Services.Search] Search auto complete service should not be case-sensitive

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#198]
Found that using the autocomplete search endpoint, the service is case-sensitive.

For example: autocompletion for 
microsoft.aspnet vs. Microsoft.AspNet
testpackage vs. TestPackage

returns different results.

Talked to Scott and this is related to the tokenization of the query string and the search indexes. 

We should probably improve the logic by adding lower-cased tokens to the existing search indexes to allow better match.

**Comment by yishaigalatzer** [comment]
Also consider performance improvement by allowing a single call to retrieve data for all active frameworks.
