### ISSUE TITLE
Global packages folder path is incorrect on kudu

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1981]
NuGetEnvironment uses _Environment.SpecialFolder.UserProfile_ which does not have a value on Kudu Consoles. This was previously fixed in SettingsUtility.

This fix (no longer exists):
https://github.com/NuGet/NuGet.Client/commit/381b6128d74cd51df82544b936533331452123a1#diff-f83497230965c941a0bf5e2d2ed13deeR151

Should be applied here:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/NuGetEnvironment.cs#L36

**Comment by emgarten** [comment]
//cc @glennc who reported the issue

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/issues/232.
