### ISSUE TITLE
Are breaking changes allowed in prerelease package versions?

### ISSUE THREAD

**Issue by tihomir-kit** [NuGet/Home#1982]
If you version your NuGet as a prerelease version (for example 0.9.9-alpha), are you then allowed to make breaking changes to the public API without having to bump up the Major version number?

According to the [documentation](https://docs.nuget.org/create/versioning), the Major version number is for breaking changes, but there is no info about how the prerelease behaves. I guess it's just a semantic change.

I know that when I made a breaking change to a NuGet and published it to nuget.org and I only bumped the minor version (for example from 1.2.1 to 1.3.0), when I pulled the NuGet update (to 1.3.0) from inside a different project that uses the NuGet, the visible version number would be ok (1.3.0), but the code for that NuGet version was from the previous version (1.2.1).

Do the prerelease versions behave in the same way?

Btw., I'm not even completely sure that nuget.org does this check (perhaps it idnexes the public API stuff, it does make a lot of sense) or if I did something wrong (I did re-publish a few different times with the same result and only after bumping the major version did everything work as expected)

Thanks

**Comment by yishaigalatzer** [comment]
This seems like a good question for somewhere like stackoverflow. The discussion is of course theoretical, but in general you should be able to break between pre-releases to your hearts content. Pre-releases are all about: I haven't made up my mind 100% and I'm not ready to commit to anything.

Now at the same time, this is where you carefully choose Alfa, Beta, RC, etc tags to indicate the maturity of your changes. The closer you are to a release quality your customers expect things to be more stable, but up until you released an RTM release go ahead an break it if you got it wrong.

**Comment by tihomir-kit** [comment]
I know it's for stackoverflow, sorry. But I asked there and didn't receive an answer.. Thanks.
