### ISSUE TITLE
nuspec version range should override -IncludeReferencedProjects version

### ISSUE THREAD

**Issue by sliekens** [NuGet/Home#1983]
The `ÌncludeReferencedProjects` option ignores version range restrictions in nuspec files.

I have a solution that contains two projects that need to be packaged: a master project and a referenced slave project.

![solution explorer](http://i.imgur.com/6nri2Xs.png)

The master project has a nuspec file that configures a dependency with a version restriction on the slave project.

<pre>
&lt;package &gt;
  &lt;metadata&gt;
    &lt;id&gt;<b>Master</b>&lt;/id&gt;
    &lt;version&gt;<b>1.0.0</b>&lt;/version&gt;
    &lt;title&gt;Master&lt;/title&gt;
    &lt;authors&gt;Steven&lt;/authors&gt;
    &lt;description&gt;Master&lt;/description&gt;
    &lt;dependencies&gt;
      &lt;dependency id=&quot;<b>Slave</b>&quot; version=&quot;<b>[1,2)</b>&quot; /&gt;
    &lt;/dependencies&gt;
  &lt;/metadata&gt;
&lt;/package&gt;
</pre>

The slave project has a nuspec file too, for integration with the `IncludeReferencedProjects` option.

<pre>
&lt;package &gt;
  &lt;metadata&gt;
    &lt;id&gt;<b>Slave</b>&lt;/id&gt;
    &lt;version&gt;<b>1.0.0</b>&lt;/version&gt;
    &lt;title&gt;Slave&lt;/title&gt;
    &lt;authors&gt;Steven&lt;/authors&gt;
    &lt;description&gt;Slave&lt;/description&gt;
  &lt;/metadata&gt;
&lt;/package&gt;
</pre>

When I execute `nuget pack -IncludeReferencedProjects Master.csproj`, the package is created without a version range restriction.

**Expected result**

![expected result](https://i.imgur.com/MxTZSew.png)

**Actual result**

![actual result](https://i.imgur.com/TMtdciK.png)

**Comment by yishaigalatzer** [comment]
Good catch, I don't see us jumping on this right away, so moving to vNext and marking as up for grabs

**Comment by sliekens** [comment]
I edited my post to make the important bits stand out more. If nobody wants to grab this then I'll have a go at it when time permits it.

**Comment by toddm** [comment]
https://github.com/NuGet/NuGet.Client/commit/80a8f7d13d7ca8228b212649902eefb5cb2bee98
