### ISSUE TITLE
Pack command for xplat

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#1989]
Port the existing pack command along with the DNU code for creating OPC files to nuget xplat.

**Comment by borgdylan** [comment]
Please make sure the cross platform way for ZIP file internal paths i.e. with `/` instead of `\` that works only on Windows. Therefore `/` needs to be explicitly set instead of using `Path.DirectorySeparatorChar`.

**Comment by yishaigalatzer** [comment]
@toddm this is the main item for pack. Your key partner is @ericstj please keep me involved in the design discussions, and lets get one setup this week.

CC @petermarcu
