### ISSUE TITLE
Strange error description when updating package

### ISSUE THREAD

**Issue by McMlok** [NuGet/Home#1996]
Hello,

My situation: Project with two nugget. NugetA and NugetB. NugetA have dependency to NugetB. In my project is installed version 1 of these nugets. But on nugget server are version 2. But when I try to update with option Dependency behavior set to Ignore Dependencies I get error with only text "available" but when I set dependency to Highest update succeeded. Problem is only in text of error because available is not too much descriptive.

Thanks

**Comment by yishaigalatzer** [comment]
Can you please share more specific details on what packages, your nuget.config and the exact command you are running.

Also are you running on nuget 3.3?

**Comment by McMlok** [comment]
OK,

I'm using VS 2015 Update 1, Nuget Manager 3.3.0.167.

It don't depend on specified nugget because I try Microsoft.Data.OData 5.7.0 from nugget.org and our Nuget from our shared folder. 

Package manager output
Attempting to gather dependencies information for multiple packages with respect to project 'MyProjectX', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
available
========== Finished ==========

**Comment by yishaigalatzer** [comment]
Can you share your initial dependencies or your packages.config so we can try to reproduce

**Comment by McMlok** [comment]
I did sample [project](https://github.com/McMlok/NugetManagerUpdateTest)

**Comment by johnataylor** [comment]
This looks like more than just a bug in the message text.

When I try this from the UI - selecting a specific package and then IgnoreDependencies from the drop down it does the update but when I use the PowerShell prompt it gives the error "available."

The behavior is inconsistent. However, if we do decide to keep the existing command prompt behavior we should at least improve this error message.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
