### ISSUE TITLE
"nuget pack" ignores files in dot-prefixed directories when listed in nuspec

### ISSUE THREAD

**Issue by urbas** [NuGet/Home#1997]
Version of NuGet affected: `3.3.0.212`

Here's what goes wrong:

``` bash
# See below for the content of the "Foo.nuspec" file
$ nuget pack Foo.nuspec -OutputDirectory FooOutputPath -BasePath FooInputPath

MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Attempting to build package from 'Bud.nuspec'.
Cannot create a package that has no dependencies nor content.
```

`Foo.nuspec` content:

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Foo</id>
    <version>0.0.1</version>
    <authors>Chuck</authors>
    <description>Foo</description>
    <dependencies></dependencies>
  </metadata>
  <files>
    <file src=".Foo/Foo.dll" target="lib/net45/Foo.dll" />
  </files>
</package>
```

Explanation: the `.Foo/Foo.dll` file is ignored and nuget thinks the package is empty.

Expected result: a valid nupkg should have been created with `Foo.dll` being in the package.

**Comment by yishaigalatzer** [comment]
This is by design, it is clearly documented as well. https://docs.nuget.org/create/creating-and-publishing-a-package#from-a-project

**Comment by jhenyffer** [comment]
Hello, but then how can I manage folders named like this? I mean, how can I include those folders in the nuget package? Because like this guy, I have a database that have folders named like this and I can not exclude the "." in front of the folder's name.
Thank you!
