### ISSUE TITLE
NuGet packages not updated during scripted build

### ISSUE THREAD

**Issue by dbeukers** [NuGet/Home#1999]
I am working on a VisualStudio 2013 project that uses several NuGet packages. If I check out this project and build from the GUI, the packages are restored. If I try to script the build (same command line, but adding a "/build Release" argument), the restore does not happen. Is this a problem with the NuGet extension, VisualStudio itself, or what?

**Comment by yishaigalatzer** [comment]
You need to run nuget.exe restore {solution}.sln before running msbuild
