### ISSUE TITLE
Improve error message when incorrect feed URL used in NuGet.Config

### ISSUE THREAD

**Issue by danroth27** [NuGet/Home#2000]
If you try a restore with a bad feed URL the `dotnet restore` command tells you there was a 404, but it doesn't tell you which URL the request was made to.

NuGet.Config:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <!--To inherit the global NuGet package sources remove the <clear/> line below -->
    <clear />
    <add key="dotnet-core" value="https://www.myget.org/F/dotnet-core/api/v3/index.json" />
    <!-- This is the bad feed URL -->
    <add key="aspnetcidev" value="https://www.myget.org/F/aspnetcidev/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

project.json:

``` json
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "NETStandard.Library": "1.0.0-rc2-23704",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-*"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

Output:

```
C:\Users\daroth\Documents\projects>dotnet --version
.NET Command Line Tools (1.0.0)
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

C:\Users\daroth\Documents\projects>dotnet restore
info : Running restore with 16 concurrent jobs.
info : Restoring packages for C:\Users\daroth\Documents\projects\project.json...
error: Response status code does not indicate success: 404 (Not Found).
```

**Comment by yishaigalatzer** [comment]
@joelverhagen was this fixed already?

**Comment by joelverhagen** [comment]
New output:

<pre>
log  : Restoring packages for C:\Users\jver\Desktop\Test\i\project.json...
info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.aspnetcore.diagnostics/index.json
info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.aspnetcore.diagnostics/index.json 114ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.diagnostics/index.json
<b>error: Unable to load the service index for source https://www.myget.org/F/aspnetcidev/v3/index.json.
error:   Response status code does not indicate success: 404 (Not Found).</b>
</pre>

This now indicates the source that caused the problem.
