### ISSUE TITLE
A way to have automatic notifications of package updates

### ISSUE THREAD

**Issue by epicbugs** [NuGet/Home#2002]
As a member of a team that develops some tools using Nuget packages from Microsoft, I have a requirement to not only keep the installed packages on bleeding edge but also to have some advance notice to new releases (by being aware of release candidates as they roll out). Unfortunately the only way to accomplish that in Visual Studio is to manually open Package Manager every once and a while. Not only is that cumbersome, it requires to go back and forth between solutions that one is not even working on at that moment.

A problem we had earlier this week today prompted me to think of an easier and a more reliable method. At first, I hoped the public website has version history **`RSS`** feeds but at the moment it doesn't. It seemed the only viable course of action to have the automatic notification feature was to propose or contribute new features either to the Gallery or to the Extension. Luckily there were some Google results indicating that your **`v2`** web **`API`** returns results in **`OData/Atom`** (which an ordinary **`RSS`** reader can consume). One such example is https://www.nuget.org/api/v2/Search().

Unfortunately I still don't know as to how the $filter parameter works or if that one is even the correct parameter to use in this case. Can anyone here please guide me in the right direction?

**What kind of a query string should I write over there in order to get a list of `<entry>`-s where each `<entry>` is a separate version of the same package, ordered chronologically? Or should I use a different API service altogether?**

Knowing this would solve our initial problem.

**Comment by yishaigalatzer** [comment]
This does belong in the gallery. We are planning to support notifications long term (through a push notification). 

To give you a way to get all versions of a package (or latest) you can use this sample (from the V3 API, you get by installing nuget.protocol.v3 package)

``` c#
        public async Task<string> CheckForUpdate(string packageId, string versionNumber)
        {
            //Check to see if we can find a newer/greater version number on Nuget.org
            //Decide if lazy & do as GET with QS or do as proper POST
            var repo = Repository.Factory.GetCoreV3(NuGetConstants.V3FeedUrl);

            var otherResource = await repo.GetResourceAsync<FindPackageByIdResource>();
            otherResource.CacheContext = new SourceCacheContext();
            otherResource.Logger = NullLogger.Instance;

            var items = await otherResource.GetAllVersionsAsync(packageId, CancellationToken.None);
            var resource = await repo.GetResourceAsync<MetadataResource>();
            var lastestFormsVersion = await resource.GetLatestVersion(packageId,
                false,
                false,
                CancellationToken.None);

            //Parse the current version so we can compare easier
            var currentVersion = NuGetVersion.Parse(versionNumber);

            if (lastestFormsVersion > currentVersion)
            {
                return lastestFormsVersion.ToString();
            }

            return currentVersion.ToString();
        }
```

**Comment by karann-msft** [comment]
@epicbugs - I found this thread when I was searching for something very similar to what you have, and wanted to tell you that packages now do have RSS feeds. Have you built something around that do send you notifications for updates to packages you are interested in?

**Comment by epicbugs** [comment]
@karann-msft - Wow :) What a nice trip down the memory lane! But no, I haven't built anything around it. At the time (with no RSS available) it was decided as too much work for the convenience of our team only. Thanks for the heads-up though! For the DIY folks, adding a simple Outlook RSS rule to alert/action on appearance of hyphen in version name is (provably) quite doable now. It's certainly less elegant than a "Follow/Unfollow pre-releases" button in github.com/nuget.org would be but it does the job :slightly_smiling_face: :+1:

**Comment by epicbugs** [comment]
@karann-msft - Wow :) What a nice trip down the memory lane! But no, I haven't built anything around it. At the time (with no RSS available) it was decided as too much work for the convenience of our team only. Thanks for the heads-up though! I tried it out and managed to get notifications from plain RSS by creating an Outlook rule that looks for a hyphen in the item title. Works 👍
