### ISSUE TITLE
NuGet Package Manager is very slow offline

### ISSUE THREAD

**Issue by Heinzelemente** [NuGet/Home#2006]
Hello Nuget Team,
I am working ALWAYS offline and the NuGet-Paket-Manager is so slow with Visual Studio 2015 V14.0.23107.0.
It takes 10 - 20 seconds everytime I click on a package (offline folder). 
How can I find out what the problem is? It is unusable.
Best regard,
Alex

**Comment by yishaigalatzer** [comment]
Hey Alex,

There could be a few underlying issues, its hard to tell from your report.
1. We are tracking an issue where when you are truly offline, the image links in the icons might be hitting the network and blocking. (You can validate that by using fiddler)
2. If your offline folder is relatively large you might want to consider following the guidance on one of the two blogs we shared (one for file based feed, and one for http based feed)

http://blog.nuget.org/20150922/Accelerate-Package-Source.html
http://blog.nuget.org/20160113/Accelerate-your-NuGet.Server.html

Can you please ping us back after you give it a try?

**Comment by yishaigalatzer** [comment]
CC @zhili1208

**Comment by Heinzelemente** [comment]
Hey Yishai,

My offline folder is very very small (only 5 – 10 packages), so I assume that the issue is more related to option one. 
The vm is definitely offline. I can try to monitor the network traffic with wireshark, but I do not know where to look at.

I will install the VS 2015 Update 1 in advanced. 

Best regards,
Alex

**Comment by Heinzelemente** [comment]
Hey,
I now updated the VS, but the problem is still pending. 
Meanwhile I could find out that everytime I paste in a new nuget package. The NuGet Package Manager is in "Loading...." for 30 seconds. 
If I click on one entry. It hangs for 30 - 40 seconds.
That is very annoying. 
Any ideas?

Best regards

**Comment by zhili1208** [comment]
@Heinzelemente  can you share your network traffic log with wireshark and what are those packages in your folder? thanks

**Comment by yishaigalatzer** [comment]
@zhili1208 can we please share with him the build we had that fixes the icon loading ?

**Comment by zhili1208** [comment]
@Heinzelemente can you send your email address to me? I can share a private build with you, it might fix your issue, my email is lzhi@microsoft.com. Thanks

**Comment by Heinzelemente** [comment]
@zhili1208 I sent you an email. You can send me the private build via this contact.
Thanks

**Comment by zhili1208** [comment]
@Heinzelemente I sent you an email with the private build two weeks ago, did you try it? we just checked in a fix about this, we can share the latest build with you, it might solve your issue. thanks

**Comment by Heinzelemente** [comment]
@zhili1208 first of all: thanks for the build. Yes I tested the build now for a week and the initial load is now a little faster (~30 seconds). The browsing is still slow, but only during scrolling. I can select the packages without any delay. But to be honest: it improved a lot already.

**Comment by yishaigalatzer** [comment]
We have another improvement, would you mind trying the build from yesterday?

**Comment by Heinzelemente** [comment]
@yishaigalatzer yes of course. Every improvement is welcome. My department (31 developer) will be happy about it.

**Comment by yishaigalatzer** [comment]
Another question, do you have source that are not accessible on your list? For example is nuget.org enabled?

**Comment by Heinzelemente** [comment]
@yishaigalatzer No the options set like that: 
![2016-03-09 10_29_18](https://cloud.githubusercontent.com/assets/12995603/13630869/e11fb856-e5e1-11e5-9c20-5a1e8d93fefc.png)

**Comment by Heinzelemente** [comment]
I installed the new vix and the issue is is definitely solved now. I can browse and select the packages without any delay. Only the initial start of the manager needs some seconds ("Browse"-Tab), but that is in my eyes absolutely OK. The second start of the manager is fast and fluent. 
Well done.

**Comment by yishaigalatzer** [comment]
Very cool. I have a couple of suggestions/notes
1. Instead of just dropping files in the download folder use nuget.exe add or init command and you will see faster performance out of this folder.
2. The tab performance is going to be improved further in rtm
