### ISSUE TITLE
Don't allow floating versions to consider the shared packages location

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2007]
Right now, if I remember correctly, NuGet3 restore uses the shared packages location (`~/.nuget/packages`) as a feed. This is good for perf, but bad behavior in general because it means you have a package source that is variable based on other projects. There is a long-standing issue with `*` where if another project restores a higher version from a **different** feed to the packages location, your project (which points at a feed containing **lower** versions) will still get it because the local packages directory is a source and the `*` forces the version up to the highest value.

Ideally, the shared packages location should only be used to resolve a specific package version and never used to determine the version a `*` refers to. Instead, a `*` should force the restore process to go to the feeds listed in `NuGet.Config` **only**, identify a version, and **then** consider the local packages directory to determine if the package is already present. This will avoid issues with multiple projects using different feeds and dependencies like `1.0.0-*`.

/cc @yishaigalatzer @davidfowl @emgarten

**Comment by analogrelay** [comment]
Side note: This would mean `*` would actually behave the way users expect it to behave...

**Comment by davidfowl** [comment]
This change was only in dnu and never ported to nuget, proof:
- https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs#L456
-  https://github.com/aspnet/dnx/blob/dev/src/Microsoft.Dnx.Tooling/Restore/RestoreOperations.cs#L201
