### ISSUE TITLE
Specifying Configuration (Debug/Release) not possible with Nuget Update

### ISSUE THREAD

**Issue by raulramaya** [NuGet/Home#2008]
Applies to version 2.8.5

When Nuget Update is run, it will place the updated reference outside of any configuration block which means that all configurations will take the update by default.

Example:  

Before running Nuget Update`

```
<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">

  <Reference Include="X">
  <HintPath>path\1.2.2\X.dll</HintPath>

</ItemGroup>

<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'ProjRef|AnyCPU' ">

  <ProjectReference Include="X.vbproj">
  <Name>X</Name>
  </ProjectReference>

</ItemGroup>
```

After running Nuget Update

```
<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">

 <Reference Include="X">
  <HintPath>path\1.2.2\X.dll</HintPath>

</ItemGroup>

<ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'ProjRef|AnyCPU' ">

  <ProjectReference Include="X.vbproj">
  <Name>X</Name>
  </ProjectReference>

</ItemGroup>

<ItemGroup>

  <Reference Include="X">
  <HintPath>path\1.2.3\X.dll</HintPath>

</ItemGroup>

```

The result, in example above, is both the `ProjRef`and `Release` configs pick up the reference placed by Nuget Update.

I would expect the ability to specify a build type/config to use.

**Comment by yishaigalatzer** [comment]
Consider moving your projects to a project.json model, where nuget.exe update might no longer be required for CI scenarios.

This is however good feedback, and we should find the time too look into it. I'm opening this up for folks that might want to submit a pull request.

**Comment by raulramaya** [comment]
Thanks - I am unfortunately in that class of folks who can't move to 3.x just yet.   Otherwise it looks like the project.json would solve the issue.

**Comment by rrelyea** [comment]
We are working on PackageReference model for VS2017 and hope to migrate most Packages.Config and Project.json users there. We are unlikely to go back and address this in Packages.Config.

Good news is that PackageReference is msbuild based, so will give much increased flexibility for many scenarios.
