### ISSUE TITLE
Build task should copy PDBs from both packages and xproj projects

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#2009]
The build task, when computing assets, should include PDBs along with the implementations. This is necessary for a few scenarios:
1. .NET Native, where you want the PDBs so you can debug the resulting ahead-of-time compiled application.
2. csproj -> xproj, where you would expect the PDB to get copied along like a regular csproj -> csproj reference would do.

(This is a copy of an internal bug originally filed on behalf of @onovotny.)

**Comment by clairernovotny** [comment]
Not sure if this is the correct/best approach, but this did the trick for csproj/UWP:
https://github.com/xunit/devices.xunit/blob/36f9c4eea05fbcb611f36289c0430999c503445f/test/test.xunit.runner.uwp/test.xunit.runner.uwp.csproj#L192-L200

Question is where that belongs in the nuget targets.

**Comment by jasonmalinowski** [comment]
@onovotny, I think we need it in the build task since there's multiple places that would otherwise need to duplicate that code. But thank you for the pointer, we'll make sure whoever fixes this syncs xunit and removes that to see if everything still works.

**Comment by clairernovotny** [comment]
Yeah, figured that it belonged deeper than that but wanted to provide something that seemed to work.
