### ISSUE TITLE
When authentication fails, it's difficult to diagnose and fix

### ISSUE THREAD

**Issue by vtbassmatt** [NuGet/Home#2010]
When using NuGet against Team Services-hosted private feeds, if the identity is valid but not authorized to use the feed (either to restore or push), the client reports "unable to prompt for input". It would help with troubleshooting if the client reported that the action was denied, or even surfaced the HTTP status code, in addition to the "unable to prompt" message.

**Comment by vtbassmatt** [comment]
We were not passing -NonInteractive in the build task, and since the build machine has no stdin, NuGet was crashing. We've addressed that, but the auth failure is still not diagnosable. Updating the title and initial report to reflect the actual issue.

**Comment by yishaigalatzer** [comment]
This seems like a VSO authentication related issue, @pspill built the original feature. CC-ing him

**Comment by pspill** [comment]
I'll take a look.

**Comment by yishaigalatzer** [comment]
ping

**Comment by pspill** [comment]
This issue no longer repros in Nuget 3.4.  The error message is now "Unable to load the service index for source https://somesource/DefaultCollection/_packaging/NoAccessForPeter/nuget/v3/index.json.  Response status code does not indicate success: 401 (Unauthorized).", which is an actionable message.

**Comment by zhili1208** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249)
