### ISSUE TITLE
Provide a Better Error Message When Unable to Write to Nuget.Config

### ISSUE THREAD

**Issue by johnkoerner** [NuGet/Home#2012]
When using a version control system that makes files readonly, if you modify the nuget settings in the Visual Studio options dialog with the file marked readonly, you receive the following error: 

![image](https://cloud.githubusercontent.com/assets/3915000/12665879/2a2aa95a-c609-11e5-814a-2f92da68783c.png)

This error message does not indicate the path of the Nuget.Config file that causing the exception.  

It would be beneficial to know the full path of the file causing the exception to allow a user to more easily know which file to check out from the VCS.

**Comment by yishaigalatzer** [comment]
@zhili1208 this is part of the things you are working on now. Can you take it as part of your changes?
