### ISSUE TITLE
nuget.exe update -Id not working when project has not restored packages ?

### ISSUE THREAD

**Issue by christopheblin** [NuGet/Home#2013]
Try to do the following in a not compiled solution, replacing xxx with one of your packages :

```
nuget.Exe update -Id xxx 
```

You will always have the result : 

```
WARNING: can not find xxx. Make sure they are specified in packages.config.
```

Obviously, I use that command with a package that is specified in my packages.config.

I look at the source code and find a strange thing in UpdateCommand.cs

```
    private IEnumerable<IPackage> GetPackages(IPackageRepository repository)
    {
        var packages = repository.GetPackages();
        if (Id.Any())
        {
            var packageIdSet = new HashSet<string>(packages.Select(r => r.Id), StringComparer.OrdinalIgnoreCase);
            var idSet = new HashSet<string>(Id, StringComparer.OrdinalIgnoreCase);
            var invalid = Id.Where(id => !packageIdSet.Contains(id));

            if (invalid.Any())
            {
                throw new CommandLineException(LocalizedResourceManager.GetString("UnableToFindPackages"), String.Join(", ", invalid));
            }

            packages = packages.Where(r => idSet.Contains(r.Id));
        }
        var packageSorter = new PackageSorter(targetFramework: null);
        return packageSorter.GetPackagesByDependencyOrder(new ReadOnlyPackageRepository(packages)).Reverse();
    }
```

The problem here is that the packages variable does not contain "xxx" (whereas my packages.config DOES contain it).

If I build the project and relaucnh the command it does not throw this error anymore.

Is this a bug or a known limitation/quirck/.... ?

**Comment by christopheblin** [comment]
Please note that this is true for nuget 2.8.6 but not for 3.3.0

**Comment by yishaigalatzer** [comment]
The issue here is that we don't want to update packages when the original package is not on disk, because update uses data from the old package (in vs it runs the uninstall script, and it may remove content files, check if they where modified etc.).

So the behavior is expected, but the error is misleading.

**Comment by yishaigalatzer** [comment]
In general consider moving your projects to the project.json model where you have a much nicer model of updating packages (by just changing project.json file or using the \* notation). The nuget.client repo is a good example for this pattern

**Comment by christopheblin** [comment]
Thx for answering . I will look at json model when I am sure that our tfs build server correctly handle that.

**Comment by rrelyea** [comment]
Updating the advice. We've now evolved past project.json towards PackageReference in csproj. Please evaluate making the jump there.
