### ISSUE TITLE
Packages built with Linux dnu pack cause problems

### ISSUE THREAD

**Issue by petr-k** [NuGet/Home#2015]
When I build and publish a package via `dnu pack` on Linux (.NET Core RC1), some NuGet clients have problems reading it. I believe it has something to do with the zip format.

I even got errors about invalid archive structure in VS2015 with the latest NuGet (3.3.0), which seem to be somewhat random and I cannot reproduce them at the moment.

It this addressed in NuGet or the new dotnet CLI? I believe the right solution would be to pack in a ZIP format that is easily readable "everywhere".

**Comment by csharpfritz** [comment]
Yes, these two utilities are not currently compatible across Linux/Windows
boundaries.  dnu packages should be compatible with dnu only at this point.

This is exactly what the team is working on right now:  unifying dnu and
NuGet as part of the dotnet CLI so that every package is accessible
everywhere.

Jeff

**Comment by petr-k** [comment]
Many thanks for the quick explanation!

**Comment by petr-k** [comment]
Just to be absolutely certain - does that mean that Windows NuGet 2.8 clients will be able to read packages produced by the new dotnet CLI?

**Comment by csharpfritz** [comment]
That's our goal: maintain that compatibility

Jeff

**Comment by davidfowl** [comment]
Did you pack using mono or the new cli?

**Comment by petr-k** [comment]
I used `dnu pack` in the official `microsoft/aspnet:1.0.0-rc1-update1` docker image, so I guess that means mono..

**Comment by yishaigalatzer** [comment]
@petr-k can you please share your package and project?

**Comment by petr-k** [comment]
https://github.com/avast/sms-connector-client

If you check out `.travis.yml` and follow the link to Travis, you can see how the package is being built and published.

**Comment by yishaigalatzer** [comment]
We are replacing dnu pack with nuget pack, and we will validate this as part of our change

**Comment by rrelyea** [comment]
fixed in ~Feb 2017 -- VS 2017 15.0, DotNet 1.1, and NuGet 4.0 eras.
