### ISSUE TITLE
nuget client doesn't understand gzip content-encoding

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2016]
The nuget client doesn't understand gzip content-encoding. For example, placing gzip content in storage, setting the headers all correctly and the the UI will not show details. (Of course the UI should never have been fetching this blob in the first place but it does and that's where we are at.)

Experimenting with this in a console app suggests the client code needs to set the AutomaticDecompression on the HttpClientHandler. (It should also set the Accept-Encoding header to gzip but in my test case that was being ignored because I was always sending gzip whatever the client asked for.) Code looks something like this (we actually have a custom client handler so it would be a little more complex but this represents the idea.)

```
        var handler = new HttpClientHandler();
        handler.AutomaticDecompression = DecompressionMethods.GZip;
        var client = new HttpClient(handler);
```

**Comment by emgarten** [comment]
WebRequestHandler (the custom handler) takes this flag also.

Should it be: `DecompressionMethods.GZip | DecompressionMethods.Deflate` or just Gzip?

**Comment by emgarten** [comment]
It looks like NuGet.Core was supporting this also. Is it still turned on for the OData feed?

https://github.com/NuGet/NuGet2/blob/2.11/src/Core/Http/HttpClient.cs#L133

**Comment by johnataylor** [comment]
and we should add deflate (though this is probably not much used!)

handler.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;

**Comment by emgarten** [comment]
NuGet/NuGet.Client@7f6f9861660fe4a99c8c3589aee9c7b3963fb629

**Comment by yishaigalatzer** [comment]
This change is going to make the download size of metadata improve by a factor of x5 to x10, affecting search results, updates from the V3 sources
