### ISSUE TITLE
nuget.commandline 3.3.0 -Source not adhering to source

### ISSUE THREAD

**Issue by wolfpackt99** [NuGet/Home#2018]
I upgrade to nuget.commandline from chocolately.  When i ran nuget update <SLN> -Source MySourceName it started updated ALL packages from all sources in my solution.  When i downgraded back to 2.8.6 it only updated packages from specified source.

**Comment by yishaigalatzer** [comment]
@johnataylor I believe this is a duplicate. Can you take a look?.

**Comment by rrelyea** [comment]
Closing this very old bug. Please file a new one if current NuGet.exe (4.4.0) from http://nuget.org/downloads has problematic behavior.
