### ISSUE TITLE
Create a command similar to nuget.exe mirror for V3 feeds based on the catalog

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2021]

**Comment by fabsenet** [comment]
is there any intent or workaround in place?

i have a local package folder. it was created via

`nuget.exe init`

and i can add to it via 

`nuget.exe add *full*qualified*package*file*name -source ...`

but it is not convenient. I would rather want to say latest and/or -pre! `nuget.exe install` can do this, but it does not respect the local folder structure of .\package-id\version\*.nupkg

What should I do?

**Comment by rrelyea** [comment]
See https://www.nuget.org/packages/NuGetMirror/ for a package that helps do that from @emgarten
