### ISSUE TITLE
Search: Prefer exact name matches

### ISSUE THREAD

**Issue by NickCraver** [NuGet/Home#2023]
I was quite surprised when adding a reference to [Jil](https://www.nuget.org/packages/Jil/) (our JSON (de)serializer) just now. Despite having an exact name match and orders of magnitude more downloads, it was ranked below 5 other packages in "relevance" in both the Visual Studio UI and [on the website](https://www.nuget.org/packages?q=Jil):
![2016-02-01 11_17_10-stackexchange geo - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/454813/12723271/b972c712-c8d6-11e5-9dc2-d7cd766bab08.png)
![2016-02-01 11_19_31-nuget gallery _ packages matching jil](https://cloud.githubusercontent.com/assets/454813/12723269/b8268506-c8d6-11e5-81b3-fc2dba320e01.png)

Why isn't an exact name match preferred above all else in all situations? We're talking about 1 spot at the top here for a lot of net good. Can we please change the relevance algorithm to do this?

**Comment by herecydev** [comment]
:+1: Looks like having the tag `Jil` increased the relevance. Downloads feel like the most important criteria to me, at least should be used as a tie breaker within multiple results with the same name.

**Comment by keichinger** [comment]
@herecydev how can there be multiple results with the same name? NuGet package names are meant to be unique, aren't they?

**Comment by NickCraver** [comment]
Yep, they're unique - the URLs wouldn't work otherwise :) That's why an exact match should be up top, IMO. It's the canonical.

**Comment by yishaigalatzer** [comment]
This bug belongs in the nugetgallery. However we already have an improvement in flight - http://nuget-prod-0-v2v3search.azurewebsites.net/query?q=jil

This new search server is in the process of being deployed to production.

**Comment by yishaigalatzer** [comment]
CC @johnataylor @maartenba @joyhui @joelverhagen

**Comment by herecydev** [comment]
@cH40z-Lord Sorry I meant where the package name contains the same search term, in this case `Jil`

**Comment by yishaigalatzer** [comment]
@herecydev yes, that's what we have done.

**Comment by JamesNK** [comment]
When searching for json, should the top result be the package with the id JSON?

http://nuget-prod-0-v2v3search.azurewebsites.net/query?q=json

**Comment by NickCraver** [comment]
@JamesNK yep, I think it should - and JSON.Net should definitely be 2nd because of name and downloads. Since installing "json" form the console will get you _that_ package, it should match up as the first result as well. 

I believe this should be the case even if the package had 12 downloads. If a user is searching for a specific package regardless of something larger having millions more downloads, they knew what they wanted. Let's argue they didn't though: in such a case we've only occupied 1 spot with this exact-match behavior and caused very little downside (as in your case, where JSON.Net is ranked 2nd). Big packages shouldn't make finding less-downloaded ones very difficult, which is what special behavior there would cause across the board.

**Comment by yishaigalatzer** [comment]
In general the thought is that if you are in the top 3, call it good. However it is debatable if the id="json" package should win or be second. IMHO it should be second, because it is probably not as relevant, and 2nd is good enough. We will take a look

**Comment by JamesNK** [comment]
@NickCraver In this case (JSON) the user probably isn't searching for a specific package, they're searching for a technology.

**Comment by NickCraver** [comment]
@JamesNK agreed _on this case_, but this has to be an automated decision overall and I don't see how to really handle that case better for all searches. IMO, JSON.Net showing up very readily as spot 2 is acceptable.
