### ISSUE TITLE
(Question) Is it possible to specify the license/project URL without creating a .nuspec file?

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#2024]
Hi! Sorry to trouble you guys, but SO's not helping (and you guys are probably experts anyway :wink:)

I'm wondering if it's possible (during `nuget pack`) to specify the project/license URL without creating a .nuspec file. I know you can specify the author in `AssemblyInfo` via `AssemblyCompany`, and the description via `AssemblyDescription`. How do I do the other things specific to NuGet, like tags/license/project URL?

For reference, here's my current AssemblyInfo file: https://github.com/jamesqo/observable-vector/blob/master/src/ObservableVector/Properties/AssemblyInfo.cs

Thanks for helping!

**Comment by yishaigalatzer** [comment]
No there isn't a way as far as we know with the current pack system.

With project.json based project (.NET CLI) that would be a possibility, but you wouldn't have a csproj file at that point.
