### ISSUE TITLE
Add useragent to the ILogger context

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2028]
Today the UserAgent for http calls is set on a static property. With recent changes in the protocol an ILogger is now passed everywhere that http calls are made, this could allow the UserAgent string to be passed along with the logger. 

The logger today should know the context, for example PS, nuget.exe, and the VSIX each provide different loggers and also have different user agents.

**Comment by yishaigalatzer** [comment]
@emgarten that sounds weird, the logger shouldn't carry around extra properties. Perhaps this is just a naming change from ILogger context to an operation context that will carry the logger with it.

**Comment by rrelyea** [comment]
Marking won't fix for now.
