### ISSUE TITLE
NuGet.VisualStudioExtension: Package Listing Operation Blocks UserInterface

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#203]
As reported by Phil Haack:

Listing installed packages is really slow. It basically doesn't even work if you don't have an internet connection. We often want to just see what packages we have installed and it always takes a while.

I think I understand why. In the past, NuGet didn't show updates available for installed packages unless you switched to the Updates tab. But now it seems you query for that before you show installed packages. Going back to the list of tasks people want to accomplish, it seems to me you could do one of two things:

1. Don't show updates when people want to view installed packages.
2. Check for updates asynchronously for the currently selected installed package. Never hold up showing the list of installed packages while retrieving that information. You can only see one package at a time anyways. You can check for updates at that time.

**Comment by feiling** [comment]
Fixed by Yishai. Now we're doing approach number 2: the version lists are now fetched in the background. 

See https://github.com/NuGet/NuGet.PackageManagement/commit/1dcd25c4a7e66aae2a8d601e017f1dd6f4be89f4
