### ISSUE TITLE
Package manager checkbox not working with Dark VS theme

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#2032]
The package manager has a "Show preview window" checkbox documented here:

http://docs.nuget.org/consume/package-manager-ui#install-options

However when I click this it remains unchecked (no check mark appears) a similar problem exists with the "Remove dependencies" and "Force uninstall..." checkboxes.

This seems to be specific to the "Dark" theme, checkboxes appear fine with other themes.

**Comment by yishaigalatzer** [comment]
Thanks fort reporting this issue will take a look

**Comment by rrelyea** [comment]
First try...Not able to repro on VS 2015 Update 1 with the dark theme.

**Comment by rrelyea** [comment]
Related "connect bug" - https://connect.microsoft.com/VisualStudio/feedback/details/1651653/vs-2015-dark-theme-check-box-issue

**Comment by rrelyea** [comment]
Although I wasn't able to repro, it appears, from the connect bug, that it happens elsewhere in VS.
Working the VS theming folks for them to address. The connect bug link is above, for you to follow along.
