### ISSUE TITLE
Replace INuGetProjectContext logging with ILogger

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2037]
NuGet contains two logging abstractions: ILogger and INuGetProjectContext. These should be consolidated. 

Potentially ways to fix this:
- INuGetProjectContext could extend ILogger
- INuGetProjectContext could add an ILogger property.

**Comment by yishaigalatzer** [comment]
Closing as @alpaix filed a more detailed bug in this area

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/2286
