### ISSUE TITLE
Make nuget client smarter about which package source to hit first for a given package

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#2038]
As the NuGet client knows where a package is installed from, it may consider storing/caching that information somewhere on the client so that it knows which package source to hit first when trying to update/restore that package in a later request.

Currently, the client seems to be reaching out to all package sources configured (N), which generates N-1 requests that will result in a 404 for just a single valid request being handled by one of these package sources.

That's not very friendly behavior from the server point of view. In fact, this client behavior could be abused.

Perhaps the http cache could keep track of a hint to the package's origin, or some kind of lock file could keep track of it.

**Comment by rrelyea** [comment]
Closing this issue, as we aren't planning on doing this at this point.
