### ISSUE TITLE
Nuget 3.3 inconsistent in version numbers.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2039]
Example given a nuget package of:
Microsoft.StashClient.DPG 1601.04.0942
Nuget list will return 1601.04.0942
Nuget pack will create a package of 1601.04.0942
Nuget install will create a folder of 1601.04.0942
Nuget install will output that it actually installed 1601.4.942

**Comment by yishaigalatzer** [comment]
Microsoft.StashClient.DPG 1601.04.0942

> Nuget list will return 1601.04.0942
> can be fixed to return a normalized version
>  Nuget pack will create a package of 1601.04.0942
> Can be fixed to normalize the version but will change the nuspec created by the user
>  Nuget install will create a folder of 1601.04.0942
> Has to stay, otherwise it is a breaking change to existing projects
>  Nuget install will output that it actually installed 1601.4.942
> That is correct

**Comment by yishaigalatzer** [comment]
Suggestion for fix: Pack should normalize the version, and so should list.

NuGet Install should stay as is for backcompat, but NuGet install should also start getting a deprecated warning message with suggestion for alternatives

**Comment by toddm** [comment]
As of this morning, pack normalizes the version.

**Comment by toddm** [comment]
This is fixed in 3.5 beta.

**Comment by StingyJack** [comment]
> As of this morning, pack normalizes the version.

By "Normalizing", do you mean this will happen...
>Nuget install will output that it actually installed 1601.04.942  

...and not this...  

> Nuget install will output that it actually installed 1601.4.942
