### ISSUE TITLE
NuGet.VisualStudioExtension: Uninstall with dependencies

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#204]
Reported by Phil Haack:  

There's no way to uninstall with dependencies, so have to go and search for every dependency of a package and uninstall one by one until I can uninstall the one I want, even though installing has an option for installing dependencies as well.

**Comment by yishaigalatzer** [comment]
This will get fixed with project.json support. We don't plan to add support for this for `packages.config`

**Comment by ladylo50bear** [comment]
Delete
