### ISSUE TITLE
Add positive tests for CommandLine XPlat

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#2040]
Currently the CommandLine.XPlat unit tests don't actually do a restore to test the code.  Instead, the tests only do a few negative tests, and make sure the exit code is 0 for --help and empty args.

When NuGet moves to dotnet cli, we should be able to write real tests for CommandLine.XPlat restore.

See https://github.com/NuGet/NuGet.Client/pull/252/files#r51634203

**Comment by rrelyea** [comment]
believe that our msbuild based testing of restore covers this well enough for now.
