### ISSUE TITLE
Localize strings in NuGet.Core.sln

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2041]
Strings in the code ported from DNU in NuGet.Core.sln need to be localized.

**Comment by emgarten** [comment]
@rrelyea should this go in 4.0.1?

**Comment by mishra14** [comment]
@emgarten : can you please update the issue with the list of these strings?

**Comment by emgarten** [comment]
@mishra14 doing a find across the solution for all uses of ILogger would be a great way to get started on this 🍰

**Comment by rrelyea** [comment]
Please investigate customer impact.

**Comment by mishra14** [comment]
Searched the core solution. The only non-localized strings seem to be debug logs. Closing this for now. We can reopen this if needed.
