### ISSUE TITLE
High Priority: NuGet.Server

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#2042]
I want to submit an issue pertaining to NuGet.Server, that repo has no issue list so I'm posting the issue here.

The issue may be the same as this one:

https://github.com/NuGet/Home/issues/1066

That issue is listed as Open with no information about a fix or workaround.

Basically we cannot install certain packages and we're trying to work and deliver a system in a dynamic, rapidly evolving development environment.

Does anyone at least have any recommendations or specific guidance that will let us get moving?

I understand that a bug is a bug, but this seems to be a serious bug in a server component, it has large impact on multiple developers/testers and is exacerbated by being rather cryptic, the error message gives no hint that there's an issue with symbol packages.

Surely these facts justify this bug being given a high priority?

Thanks

**Comment by maartenba** [comment]
@Korporal What is the error you are seeing?

**Comment by yishaigalatzer** [comment]
The workaround is quite clear, don't include symbol packages in the same folder. That was never a scenario for nuget.server, it might have worked but accident.

**Comment by The-Futurist** [comment]
@yishaigalatzer @maartenba 

First how do I know for sure that the error I see "Install-Package : There are multiple root elements. Line 43, position 2" is definitely due to the symbol package problem?

Where exactly is the documentation that describes what we can or cannot do with symbol packages?

If users are assuming something that's not actually supported then any restrictions should really be made crystal clear, there's a bug somewhere - either never allow it to work or always allow it work, this limbo state is a huge risk - we're hitting a problem here that isn't trivial.

Thanks

**Comment by yishaigalatzer** [comment]
It is not crystal clear, but why won't you start by removing the symbol packages? These where never supported on a nuget server and are intended for symbol servers.

If it doesn't work for you, we can help investigate further

**Comment by The-Futurist** [comment]
@yishaigalatzer - OK I'll investigate but I'm new to NuGet servers, never set one up or anything and I'm just trying to understand the error message I see in Visual Studio. If this capability isn't supported then at least improve the error message we see, surely this would improve things?

Thanks

**Comment by yishaigalatzer** [comment]
Yes, we completely agree. We are making an effort on improving error messages in general, I can't guarantee this will be happening right away, but this is something we definitely want to attack.

One of the hard thing about improving error messages is the ability to get a good repro, and understand the source of the error. Many of these kind of errors come from exception being thrown by .NET or lower layers that are not obvious. So it will be super helpful if you can nail down the repro for this for us and we would be easily able to go back and fix the error (or perhaps even be able to work around it)

**Comment by maartenba** [comment]
Will be tackled with https://github.com/NuGet/NuGetGallery/issues/2824

**Comment by maartenba** [comment]
@Korporal Please try https://www.nuget.org/packages/NuGet.Server/2.10.0-master-0006

This functionality has been added as an option.

When `ignoreSymbolsPackages` is set to `true`, the server will never add symbols packages (that is if the file is named `.symbols.nupkg` or there is a `/src` folder in the package).

It is recommended to also set the `allowOverrideExistingPackageOnPush` option to `false` to ensure no packages are overwritten, e.g. when pushing a symbols package to `NuGet.Server`.

Note that symbols packages that already exist in you server should be removed first.
