### ISSUE TITLE
httpclient UserAgent does not set an OS version for xplat

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2044]
XPlat and other DNXCore50 libraries skip setting the OS as part of the user agent string. For xplat scenarios this info would be helpful.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.Types/UserAgent.cs#L141-L150

**Comment by emgarten** [comment]
The Version is also skipped

**Comment by xavierdecoster** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/4c58607a8b344e26d9ce19dd18da2b1e277d73b2
