### ISSUE TITLE
Invalid URI error when downloading nuget.packaging.core

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#2045]
Using the V3 apis, I'm downloading the latest nuget packages from https://www.myget.org/F/nugetbuild/api/v3/index.json, and I've hit an exception when trying to download the `nuget.packaging.core` package:

```
Invalid URI: The format of the URI could not be determined.
```

It appears the 'iconUrl' of this package is set to: `/Content/images/packageDefaultIcon_nuget.png`, and passing that string into `new Uri(str)` is throwing an exception, which goes unhandled here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/SearchLatestResourceV3.cs#L65.

Here's the snippet of code that can reproduce this:

``` C#

PackageSource packageSource = new PackageSource("https://www.myget.org/F/nugetbuild/api/v3/index.json");
SourceRepository repo = new SourceRepository(packageSource, Repository.Provider.GetCoreV3());

var searchLatest = await repo.GetResourceAsync<SearchLatestResource>();
IEnumerable<ServerPackageMetadata> packagesPage = await searchLatest.Search("", new SearchFilter(Enumerable.Empty<string>(), includePrerelease: true, includeDelisted: false), skip: 0, take: 500, cancellationToken: CancellationToken.None);


```

**Comment by eerhardt** [comment]
cc @yishaigalatzer @emgarten

**Comment by emgarten** [comment]
Interesting! I'm not sure that the SearchLatestResource is used anywhere in NuGet, but it is handy for v2 parity scenarios.

Looks like the nuspec for the nuget packages should be fixed also.

**Comment by eerhardt** [comment]
We are using this code in a tool that grabs all the packages from a certain set of feeds, and then mirrors those packages in our own feed.  We are using SearchLatestResource to read all the latest versions of the packages in the feed.  Is there any other way to get all the packages in a feed?

**Comment by emgarten** [comment]
You can use https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.Types/Resources/MetadataResource.cs#L54

And then the DownloadResource to get it.

**Comment by eerhardt** [comment]
Thanks for the pointer to MetadataResource - but the issue is: I don't know ALL of the package ids in the feed. That's why I was using the Search with an empty string.

Is there a way to get all the package ids in the feed?

**Comment by yishaigalatzer** [comment]
You can use the catalog, but it depends on what server you are working on. Not sure if myget supports it. @xavierdecoster might know.

@emgarten if we don't use this resource, we should remove it. Building an API for mirroring is on our todo list, this shouldn't be it.

**Comment by xavierdecoster** [comment]
@eerhardt running that snippet of code against https://api.nuget.org/api/v3/index.json throws a 404, indicating this is not a supported resource in NuGet v3. If support for this resource is going to be removed in the NuGet client bits, chances are support for this resource type will be removed from MyGet as well.

A fix for the icon url issue you are seeing is going to be deployed to MyGet later today.

**Comment by yishaigalatzer** [comment]
We are going to get rid of this resource in the code since it is dead code

**Comment by xavierdecoster** [comment]
@eerhardt the icon url fix has been deployed yesterday, the same code should now no longer throw.

**Comment by emgarten** [comment]
@xavierdecoster I was wondering where that URL was coming from!

I've removed the SearchLatestResource from NuGet.Protocol to avoid any confusion on this in the future.

**Comment by xavierdecoster** [comment]
:+1:
