### ISSUE TITLE
VS2013 crashes when opening Package Sources options

### ISSUE THREAD

**Issue by ch-hristov** [NuGet/Home#2046]
Probably related in some way to #564 . I had VS 2015 community, had modified the%appdata%\NuGet\NuGet.Config file then I removed VS 2015 Community and installed VS 2013 Community.I clicked Tools -> Options -> Nuget Package manager -> Package sources this is followed by a crash. Happens every time. Then I removed Community and installed VS2013 Ultimate. Still crashing.

**Comment by csharpfritz** [comment]
What is in your nuget.config file?  It sounds like it could be malformed

**Comment by ch-hristov** [comment]
I copied some text from an email and pasted it in the config file. It is probably the formatting that affects the text so it made it the file invalid for VS to read. In any case, there should be a mechanism that notifies the user for an invalid .config.

**Comment by yishaigalatzer** [comment]
Hey @interdrift thanks a lot for reporting this issue. In general this is a class of bugs we are investing in fixing for visual studio 2015, however don't plan on further fixing bugs at this level for 2013. 

If you have a file that works on 2015 and not on the latest version of NuGet on 2013, we will be interested in fixing it, I'm assuming it is not the case and closing this issue.

If I got it wrong please re-open.
