### ISSUE TITLE
HttpSource should require a user agent

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2047]
Currently UserAgent.UserAgentString can be empty. SetUserAgent should throw if the string is null or empty. 

All unit tests will need to be updated to support this.

**Comment by emgarten** [comment]
@xavierdecoster since you are looking at the other user agent bug would you see if this could be done in a simple way?

**Comment by xavierdecoster** [comment]
@emgarten is this still an unresolved issue?

**Comment by emgarten** [comment]
I don't think this is needed anymore.
