### ISSUE TITLE
NuGet package manager Visual Studio 2015 tooling

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#2049]
If we create a folder with packages (.nupkg files) and create a new source for it in VS and that folder contains other folders named similarly as NuGet packages, the VS tooling fails to load packages from that folder for Install/Update/Consolidate actions.

For instance, this folder structure

```
/packages
/packages/MyPackage1.versionnumber.nupkg
/packages/MyPackage2.versionnumber.nupkg
/packages/MyPackage1 (contains source)
/packages/MyPackage2 (contains source)
```

results in NuGet for Visual Studio tooling to not be able to find any packages. In fact, it produces error as shown in the attached screenshot.

Moving the .nupkgs under `/packages/nuget` solves and updating the package source specification in VS solves this issue,

The error did send me on a goose chase wasting hours trying to figure out what was wrong with .nupkg's until I discovered was the actual issue was.

![nuget-vs-tooling1](https://cloud.githubusercontent.com/assets/193816/12811736/afba6f4a-cb2e-11e5-993e-e55cb1bf3310.png)

**Comment by emgarten** [comment]
This should be fixed in NuGet 3.5.0, please let me know if you are still hitting this.
