### ISSUE TITLE
NuGet.VisualStudioExtension: Packages by version is tedious

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#205]
Reported by Phil Haack:

There's no way to list all packages regardless of version, so if there's multiple projects with the same package but different versions, I have to manually check versions. uninstall filters by the version that's selected, so that's not very helpful

**Comment by yishaigalatzer** [comment]
@csharpfritz not sure why this was assigned to you

**Comment by csharpfritz** [comment]
It's part of a general UI usability review


-----Original Message-----

**Comment by johnataylor** [comment]
Can you add more details. Its not clear exactly what UI / scenario you are describing.

**Comment by yishaigalatzer** [comment]
We now have support for that in solution level package manager and a consolidate tab.

We will take further feedback for the UI after the release.
