### ISSUE TITLE
Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by mak1453** [NuGet/Home#2051]
Hi,

I am using CoApp Developer Tools to package C++ libraries. Power Shell 3 is already installed on the system. When I run :
**_Write-NuGetPackage .\cpptest.autopkg_
**
The error I am getting : **_Invalid URI: The format of the URI could not be determined._**

Can some one please help me with this? I have been trying tackle down this problem but no luck so far. I tried it with different versions of Nuget (2.5, 2.8, 3.3, etc). Here is the content of the .autopkg file:

```
nuget {
    nuspec {
        id = cppTestLIB;
        version : 1.0.0.0;
        title: C++ TEST LIB;
        authors: {Some body};
        owners: {Some body;
        licenseUrl: "None";
        projectUrl: "https://casablanca.codeplex.com/";
        iconUrl: "https://download-codeplex.sec.s-msft.com/Download?ProjectName=casablanca&DownloadId=630102&Build=20425";
        requireLicenseAcceptance:false;
        summary: This is a test project ;
        releaseNotes: "Release of C++ libraries.";
        copyright: Copyright 2016;
        tags: { TEST, native, CoApp };
    }
    files {

        [x64,v120,release] {
            bin: { Release\*.dll };
        }

    }

}
```

**Comment by emgarten** [comment]
@mak1453 CoApp is a package and not part of NuGet itself. You may contact the owner of the CoApp package using nuget.org to ask for support.

**Comment by mak1453** [comment]
@emgarten , thank you for the recommendation. I have already contacted them as well. I just thought that someone could have done some work with CoApp here in this group and tried my luck.
