### ISSUE TITLE
Save solution after package upgrade

### ISSUE THREAD

**Issue by CraigSelbert** [NuGet/Home#2052]
After upgrading various packages it would be of great if the solution could be saved. Multiple times I have upgraded packages, committed them to source control only to find out that I did not save the solution not persisting the changes to the solution.

**Comment by emgarten** [comment]
This is a general Visual Studio problem. NuGet does not force Visual Studio to write all changes to disk after every operation for performance reasons.

**Comment by CraigSelbert** [comment]
Makes sense, I just thought I would see what you guys would say. Thanks for a quick response.

**Comment by yishaigalatzer** [comment]
We could consider this as an option. I to have been burned by this, we could potentially do the save all only after all the operations have been completed.

**Comment by CraigSelbert** [comment]
@yishaigalatzer That would work for my scenario's, I guess it does matter if the command was executed by command line vs UI, not sure how the UI actually knows when it is completed but I do know the UI does a auto refresh when it is complete.

**Comment by yishaigalatzer** [comment]
This will only be relevant for the UI. The command line only works on files on disk.

**Comment by rohit21agrawal** [comment]
@yishaigalatzer @harikm86 

This sounds like dupe of https://github.com/NuGet/Home/issues/2214 . Correct me if I am wrong.

**Comment by yishaigalatzer** [comment]
Yes, please close

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/commit/c022ca256a74340a05e25b11f3d8b3d0e90214ca
