### ISSUE TITLE
Feature Discussion: Add --interactive flag to command-line

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2055]
As suggested in tweet, https://twitter.com/jeremydmiller/status/695362614742790144

Lets investigate adding --interactive capabilities to the NuGet CLI.

This issue is for discussion and leading to design publication on Wiki

**Comment by rrelyea** [comment]
This old issue has very little info in it.
I think it was a request to support something like this: https://fsprojects.github.io/Paket/reference-from-repl.html

I'd say that "dotnet add package", etc... is the direction that the dotnet CLI is going...and we should enhance that model as needed.
