### ISSUE TITLE
In xplat nuget restore, basic auth from NuGet.Config not used when source specified by argument

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2056]
When I specify a username/password in a nuget.config like this:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="A" value="https://a" />
  </packageSources>
  <packageSourceCredentials>
    <A>
      <add key="Username" value="dagood" />
      <add key="Password" value="*************" />
    </A>
  </packageSourceCredentials>
</configuration>
```

Then try to use the source in a restore command:

`NuGet.CommandLine.XPlat.exe restore` with the NuGet.Config around (or specified with `--configfile`) succeeds.

`NuGet.CommandLine.XPlat.exe restore -s A` fails to resolve packages, and it looks like no http requests are made.

`NuGet.CommandLine.XPlat.exe restore -s https://a` returns:
`error: Response status code does not indicate success: 401 (Unauthorized).`

I worked around this in a fork a while ago like this: https://github.com/dagood/NuGet.Client/commit/ee90f38845a9392c33afd60654d8a14887fcfa6f

**Comment by yishaigalatzer** [comment]
@dagood is this blocking the xplat RC release? 

IMHO this is a low pri bug, but I'd like to hear more

**Comment by dagood** [comment]
To recap an offline discussion, this is probably low priority because there are some alternatives:
1. Don't use `--source`/`-s`, and use a custom NuGet.Config with `--configfile` which should ignore the environment.
2. Use `<clear />` tags. (Not useful for my scenario, but an option for the issue.)
3. Pass username and password on the command line. (Might not be implemented in xplat nuget.)
4. Use a lightweight fork with a quick fix.

At the moment I'm validating 1 and checking on 3, and if those don't work I'll go with 4 and make a pull request.

**Comment by dagood** [comment]
Update after building latest dev:

1: The `--configfile` parameter does not ignore the environment, only adding to it. Specifically, the NuGet.Config files in the ancestor directories of the restored project.json are used. This results in unwanted sources being included, and if any of those NuGet.Config files have `<clear />` the contents of the `--configfile` are entirely void. (This is true in my case.)

3: Didn't find any new references to this in xplat Program.cs or `PackageSource`.

Continuing with 4 for now.

**Comment by yishaigalatzer** [comment]
Can you open a separate bug for that nuget.config and --configfile issue

**Comment by dagood** [comment]
Sure, opened https://github.com/NuGet/Home/issues/2087.

**Comment by emgarten** [comment]
@dagood are you still hitting this issue with the latest CLI?

**Comment by dagood** [comment]
Looks like it works! With or without `--configfile`, `--source https://...` will use the auth associated with the URL I give.

Passing `--source A` makes CLI say it's trying to use `{current dir}/A` rather than the url of `A` from the nuget.config, but I don't need to be able to specify a feed by name.

I'm using SDK 1.0.0-rc4-004823.

Closing, thanks. :smile:
