### ISSUE TITLE
Have a more consistent approach for handling HTTP failures

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2057]
The failures that should be investigated are:
1. Errors while fetching response
   - [x] Timeout (#2017)
   - [x] DNS failure (https://github.com/NuGet/NuGet.Client/pull/277)
   - [x] Could not connect (e.g. closed port) (https://github.com/NuGet/NuGet.Client/pull/271)
   - [x] Non-success status code
     - [x] 500+ (#2017)
     - [x] 400-499 (#2017)
   - [x] Protocol problem (TCP) (https://github.com/NuGet/NuGet.Client/pull/271)
2. Errors while downloading the stream
   - [x] Protocol problem (TCP)

The high level goals are:
- [x] Determine whether the failure is retriable.
- [x] Implement retry, if necessary.
- [x] Throw a good error message.

More work can be done here, see https://github.com/NuGet/Home/issues/2269.

**Comment by yishaigalatzer** [comment]
This issue will be partially fixed in RC2, when we go past the RC2 cutline, lets open a new issue with the unresolved items

**Comment by joelverhagen** [comment]
Closed but to be continued with https://github.com/NuGet/Home/issues/2269.
