### ISSUE TITLE
Possibility to exclude transitive dependency

### ISSUE THREAD

**Issue by williambernardet** [NuGet/Home#2061]
In our project we need to replace a package fetched transitively by a package having a different name but providing same functionality. Like in Maven would it be possible to have something like this under project.json:
{
  "dependencies": {
    "packageA": {
      "version": "1.0.0",
      "include": "runtime",
      **"excludeDependency": ["packageB"]**
    }
    "packageBOverride": {
      "version": "1.1.0",
      "include": "runtime"
    }
  }
} 

excludeDependency would tell the resolution engine to prune packageB from packageA and avoid having packageB conflicting with packageBOverride.

**Comment by emgarten** [comment]
Does it work to reference packageB with exclude: all? It would still bring in the package, but it would remove all assembly references from it.

**Comment by emgarten** [comment]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

**Comment by emgarten** [comment]
Closing this issue for now, but we can continue the discussion in here until work items come up.

**Comment by williambernardet** [comment]
It works thanks.
But one comment about the granularity, in this case packageB will be completely discarded of the resolution, accross all dependencies. By experience maven for example allows to exclude a transitive dependencies from a dependency level.
