### ISSUE TITLE
Add a xUnit trait(s) to indicate platform specific unit-tests

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2065]
Introduce a platform xUnit trait to indicate platform specific tests like this

``` C#
[Fact]
[Trait("Platform", "WindowsOnly")]
public void PushCommand_PushToFileSystemSourceUncStyle()
{
...
}
```

Having the trait one can invoke xunit runner with `-ExcludeTraits "Platform=WindowsOnly"`

Opened as a follow up on:
https://github.com/NuGet/Home/issues/1053
https://github.com/NuGet/NuGet.Client/pull/253

**Comment by emgarten** [comment]
There is a similar attribute in the nuget.exe tests: 
https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/LocalResourceUtilsTest.cs#L63-L73

**Comment by yugangw-msft** [comment]
I can do either way, @alpaix @emgarten , how about you 2 discussed and let me know the log term suggestion I should adopt. The attribute, in a nushell, is a if logic still, and it is different from the Trait
