### ISSUE TITLE
IVsPackageRestorer API does not support UWP projects

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2066]
Reported by @drewgil.

For UWP projects, calling `IVsPackageRestorer.RestorePackages` does nothing. This seems to be due to an explicit skip in our code.
https://github.com/NuGet/NuGet.Client/blob/3a9e61a52f0e9bc47380031bcddc0a73ff3883ea/src/NuGet.Core/NuGet.PackageManagement/IDE/PackageRestoreManager.cs#L156-L160

This should be provided to give a consistent experience across project types.

**Comment by yishaigalatzer** [comment]
We should also include the .NET Core scenarios, when we get a new API from Bill Heibert that lets us call through to their restore

**Comment by rrelyea** [comment]
Until we have a customer ask in this area, we'll leave this unimplemented for Transitive PackageFormats.
