### ISSUE TITLE
Disabling package restore on build in VS not honored

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2067]
Machine configuration:
- Visual Studio 2015 Update 2 CTP 1 
- NuGet Package Manager 3.4.0

As shown in screenshot below, I try to disable package restore, and click OK. No error is shown. But build still executes a package restore. When I go back to this dialog, I see the checkbox is checked again. In fact if I clear the checkbox, click OK, and then immediately reopen the dialog, the checkbox is checked again. It seems this regressed with the Update 2 install I made yesterday.

![image](https://cloud.githubusercontent.com/assets/3548/12867583/ff73f812-cca5-11e5-926e-908c7927571c.png)

**Comment by emgarten** [comment]
Do you have this setting enabled in the solution level NuGet.Config or a NuGet.Config in any parent directories?

I hit a similar issue yesterday where the setting was being modified by Visual Studio in the machine wide config, but another config was overriding it. That behavior is expected as far as I know, and the plan is to improve the settings UI to allow more control over hierarchical configs.

**Comment by AArnott** [comment]
Yes, I have a nuget.config file with this content:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="repositorypath" value="packages" />
  </config>
  <packageRestore>
    <!-- Allow NuGet to download missing packages -->
    <add key="enabled" value="True" />

    <!-- Automatically check for missing packages during build in Visual Studio -->
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="PInvoke CI" value="https://ci.appveyor.com/nuget/pinvoke" />
    <add key="xunit.devices CI" value="https://www.myget.org/F/xunit-xamarin/api/v2" />
  </packageSources>
</configuration>
```

Is the `<add key="enabled" value="True" />` tag what's giving me grief? I can just remove that. It's been there since back when NuGet 1.0 was a new thing. :)
