### ISSUE TITLE
`dotnet restore` ignores `locked: true` in `project.lock.json` files

### ISSUE THREAD

**Issue by dougbu** [NuGet/Home#2068]
Though `dnu restore --lock` remains an important part of many developers' workflow, `dotnet restore` unconditionally floats the package versions. This results in a number of problems:
- Offline builds using the current aspnet tooling are impossible.
- Builds are significantly slower, even when all packages are already the latest.
- .NET CLI packages are often inconsistent with the source developers have on disk. That is, developers should be able to limit acquiring new packages to when they also `git pull --rebase` or similar.
- Not possible to reliably repeat builds, a frequent customer request. (We've heard of customers purposefully checking `dnu`'s `project.lock.json` files into source control for exactly this purpose.)

Currently `dotnet restore` seems to completely ignore `locked: true`, check all sources for new packages, and overwrite `project.lock.json`. This occurs whether or not all packages are already available on disk.

**Comment by dougbu** [comment]
Of course it would be even better if `dotnet restore` supported `dnu restore`'s `--lock` and `--unlock` options.

**Comment by borgdylan** [comment]
:+1: I agree that being able to lock the project file is very important short of messing with NuGet.config to prevent updates.

**Comment by yishaigalatzer** [comment]
This feature was removed by design of @lodejard and @davidfowl long time ago

**Comment by lodejard** [comment]
Indeed - at the time there was a spec of a different "lock" and "unlock" that doesn't have all the problems that lock: true causes. But that takes time...

**Comment by choikwa** [comment]
I know this is closed by design, but is there a replacement for locking down which version of packages are currently in use instead of manually having to edit project.json? This is important for keeping identical state across different environments. It would be nice to generate something like 'project.lock.json' but for current configuration which can be reused as 'project.json'.
