### ISSUE TITLE
"dotnet restore" is using versions that were not specified in project.json

### ISSUE THREAD

**Issue by forki** [NuGet/Home#2071]
I have the following project.json:

```
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "frameworks": {
        "dnxcore50": { }
    },

    "dependencies": {
        "System.Threading.Timer": "4.0.1-rc3-23805",
        "System.Threading.Tasks": "4.0.11-rc3-23805",
        "System.Threading": "4.0.11-rc3-23805",
        "System.Text.RegularExpressions": "4.0.12-rc3-23805",
        "System.Text.Encoding.Extensions": "4.0.11-rc3-23805",
        "System.Text.Encoding": "4.0.11-rc3-23805",
        "System.Runtime.Numerics": "4.0.1-rc3-23805",
        "System.Runtime.InteropServices.RuntimeInformation": "4.0.0-rc3-23805",
        "System.Runtime.InteropServices.PInvoke": "4.0.0-rc3-23805",
        "System.Runtime.InteropServices": "4.1.0-rc3-23805",
        "System.Runtime.Handles": "4.0.1-rc3-23805",
        "System.Runtime.Extensions": "4.1.0-rc3-23805",
        "System.Runtime": "4.1.0-rc3-23805",
        "System.Resources.ResourceManager": "4.0.0",
        "System.Reflection.TypeExtensions": "4.1.0-rc3-23805",
        "System.Reflection.Primitives": "4.0.1-rc3-23805",
        "System.Reflection.Extensions": "4.0.1-rc3-23805",
        "System.Reflection": "4.1.0-rc3-23805",
        "System.Net.Sockets": "4.1.0-rc3-23805",
        "System.Net.Primitives": "4.0.11-rc3-23805",
        "System.Linq": "4.0.2-rc3-23805",
        "System.IO.FileSystem.Primitives": "4.0.1-rc3-23805",
        "System.IO.FileSystem": "4.0.1-rc3-23805",
        "System.IO": "4.1.0-rc3-23805",
        "System.Globalization.Calendars": "4.0.1-rc3-23805",
        "System.Globalization": "4.0.11-rc3-23805",
        "System.Diagnostics.Tracing": "4.1.0-rc3-23805",
        "System.Diagnostics.Tools": "4.0.1-rc3-23805",
        "System.Diagnostics.Debug": "4.0.11-rc3-23805",
        "System.Console": "4.0.0-rc3-23805",
        "System.Collections.Concurrent": "4.0.12-rc3-23805",
        "System.Collections": "4.0.11-rc3-23805",
        "System.AppContext": "4.1.0-rc3-23805",
        "NETStandard.Platform": "1.0.0-rc3-23805",
        "NETStandard.Library": "1.0.0-rc3-23805",
        "Microsoft.Win32.Primitives": "4.0.1-rc3-23805",
        "Microsoft.NETCore.Windows.ApiSets": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Targets.UniversalWindowsPlatform": "5.0.1-rc3-23805",
        "Microsoft.NETCore.Targets.NETFramework": "4.6.1-rc3-23805",
        "Microsoft.NETCore.Targets.DNXCore": "5.0.0-rc3-23805",
        "Microsoft.NETCore.Targets": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime.Native": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime.CoreCLR": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Platforms": "1.0.1-rc3-23805",
        "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001"
    }
}
```

when I run "dotnet restore" I get:

![image](https://cloud.githubusercontent.com/assets/57396/12872226/564c30b2-cd9d-11e5-8c1b-13cc75bf176d.png)

Why is it not using the versions that I have specified?

**Comment by forki** [comment]
Ok I tried `[4.0.0]` and get

![image](https://cloud.githubusercontent.com/assets/57396/12872371/f42a89f6-cda1-11e5-9602-c8107305ac7e.png)

**Comment by davidfowl** [comment]
Using `[4.0.0]` shouldn't float, however, the naked `4.0.0` is a minimum (just like it is with packages in general) 

/cc @emgarten

**Comment by isaacabraham** [comment]
@davidfowl should it get RC versions as well by default? Also - and I'm a bit out of date with project.json / restore behaviour here so apologies - I thought the default behaviour was lowest first rather than highest?

**Comment by forki** [comment]
Tbh I don't want to question syntax here. I will take whatever works, but I really hope there is a way to make nuget restore the version I specified.

**Comment by davidfowl** [comment]
> @davidfowl should it get RC versions as well by default? Also - and I'm a bit out of date with project.json / restore behaviour here so apologies - I thought the default behaviour was lowest first rather than highest?

It is lowest. I actually don't know what's happening to your packages. Maybe a simple repro with a single package would be better? You might even be asking for packages that don't exist on any feed (those packages on myget get cleaned up pretty often).

**Comment by forki** [comment]
It's there. I manually downloaded it.

**Comment by forki** [comment]
And if it's not there I think nuget should throw and error and never come
up with something else.

**Comment by emgarten** [comment]
It looks like the version is being bumped up in the runtime graph. Here is what I see in the lock file:

| Target | Package |
| --- | --- |
| DNXCore,Version=v5.0 | System.Resources.ResourceManager/4.0.0 |
| DNXCore,Version=v5.0/win7-x64 | System.Resources.ResourceManager/4.0.1-rc3-23805 |
| DNXCore,Version=v5.0/win7-x86 | System.Resources.ResourceManager/4.0.1-rc3-23805 |

**Comment by isaacabraham** [comment]
@emgarten sorry. what is the "runtime graph"?

**Comment by davidfowl** [comment]
Looks correct then.

@isaacabraham @forki There's tons of vodoo going on that's way too hard to explain over this github issue.

**Comment by davidfowl** [comment]
Lets just say that the BCL packages aren't like any other packages that exist today on NuGet.org.

**Comment by forki** [comment]
Overriding users explicit settings? Is that a good idea?

**Comment by isaacabraham** [comment]
@davidfowl ok :-) Is there anywhere I can read up on this voodoo? When I see things like this with special cases for BCL packages and the like, it'd be good to understand why that's necessary.

**Comment by yishaigalatzer** [comment]
Packages may bring in dependencies through the runtime graph, which is a way to bring in native dependencies for your runtime environment. Sometimes these dependencies are not just implementation details of the package but extra dependencies. In this case the extra dependency is bumping up the top level dependency.

This is something we are trying to figure out how to avoid, and we are in a discussion with the .NET team to figure out how to avoid. Not sure how far we will get though, at this point we haven't reached a conclusion

**Comment by forki** [comment]
I guess my point is: the tool should never override the user. I mean it can
suggest other options or fail when things are unsound, but never override
the users decision.

**Comment by davidfowl** [comment]
It doesn't like I said, it's a topic for a blog post or documentation or white paper. It's a whole feature within itself designed for shipping something like the bcl as nuget packages. The packages are not special cased but are using a new mechanic invented for nuget packages to bring in runtime dependencies.

**Comment by forki** [comment]
@emgarten 

I just looked into the project.json.lock and saw all relevant packages define:

```
    "dependencies": {
      ...
      "System.Resources.ResourceManager": "4.0.0",
      ...
     }
```

So it seems there is nothing that would make the resolution unsound if NuGet would pick 4.0.0.
And I define it as direct dependency with specific version requirement in project.json.

So yes the "version is being bumped up in the runtime graph", but why?

**Comment by yishaigalatzer** [comment]
So what is happening is that one of the framework  dependencies

``` json
        "Microsoft.NETCore.Targets.NETFramework": "4.6.1-rc3-23805",
        "Microsoft.NETCore.Targets.DNXCore": "5.0.0-rc3-23805",
        "Microsoft.NETCore.Targets": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime.Native": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime.CoreCLR": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Runtime": "1.0.1-rc3-23805",
        "Microsoft.NETCore.Platforms": "1.0.1-rc3-23805",
        "Microsoft.DotNet.CoreHost": "0.0.1-beta-00001"
```

is depending on resource manager of a newer version, because it ships the specific implementation for the platform. The restore as it is today, acts as a binding redirect and lifts it up.

We think this shouldn't be the case and instead we should warn you that you forced a downgrade, you will need to update your top level dependency (or risk being broken in edge case/random scenarios you will have a hard time foretelling, but it will be the users choice)

CC @ericstj @emgarten @davidfowl - Please object or accept the above statement, and we will make this change before the CLI RC

**Comment by forki** [comment]
thanks @yishaigalatzer I now found the conflicting requirement. I only looked into project.lock.json before and I didn't found it there.

**Comment by yishaigalatzer** [comment]
@emgarten lets move this up, so we can find any issues with existing packages faster.

**Comment by ericstj** [comment]
We are intentionally lifting up this dependency, what do you think you're going to achieve by downgrading our lineup?

**Comment by yishaigalatzer** [comment]
The intent is that the user has the decision at the top level of what dependencies to install. In this mode there is no way to override a package lifting up dependencies. This was never an intended feature.

So after the change the user is back in full control, however he will get a downgrade warning, and can fix it. Once he uses a top level lineup he should be good and never have to specify individual packages from the .NET core packages, which is a busted experience anyways since no one can keep track of which one to install.

**Comment by isaacabraham** [comment]
@ericstj If the user _explicitly_ specifies a specific version of a dependency, the package manager should never silently replace it with something else - even if it's the "wrong" thing insofar as runtime dependencies etc.

It should simply do the best it can with the users requirements and (as @yishaigalatzer says) offer a warning that it is missing a recommended version of a runtime dependency.

**Comment by ericstj** [comment]
I'm trying to understand if you have a real problem you were trying to solve by doing this or if it is purely hypothetical.  I don't disagree with the hypothetical concern, though in the runtime case it's never going to be a good idea to downgrade.

**Comment by yishaigalatzer** [comment]
A typical problem would be a package that is too aggressive about upgrading and leading to a bug. You have no way to downgrade a dependent package that introduces the bug or "changed behavior"

Sent from Outlook Mobilehttp://aka.ms/xp9y6l

On Thu, Feb 25, 2016 at 7:22 AM -0800, "Eric StJohn" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm trying to understand if you have a real problem you were trying to solve by doing this or if it is purely hypothetical. I don't disagree with the hypothetical concern, though in the runtime case it's never going to be a good idea to downgrade.

##

**Comment by ericstj** [comment]
I understand the theoretical concern.  I'm trying to understand if folks are hitting such a problem today.

**Comment by yishaigalatzer** [comment]
Practically people shouldn't be hitting the problem which is why we shouldn't need to lift and if we protected the way I'm suggesting all packages will be authored without warnings (assuming authors address warnings)

**Comment by isaacabraham** [comment]
In terms of practicalities NuGet doesn't currently do this as far as I'm aware?

I think a part of this is about trusting the package manager - I can also see people raising bug reports about this behavior in future because it (as David said earlier) looks like voodoo.

The second reason is simply that for whatever reason one might need an older version of a given dependency - there can be all sorts of reasons e.g. Bug with a new version or incompatibility between another transient dependency.

**Comment by yishaigalatzer** [comment]
FYI - We haven't forgotten about this issue. It is not going to happen in 3.4 (because 3.4 closes before the CLI releases). We will continue discussing the alternatives and report here if we come up with a better alternative

**Comment by rrelyea** [comment]
Not clear on the right thing to do here now.
Not planning for 3.5.0

**Comment by yishaigalatzer** [comment]
I believe that the .net team was supposed to clean this up before rtm. Runtime graph is only supported in the core bcl packages.

So we should verify this doesn't repro, rather than moving the issue out of 3.5. it's a very legitimate concern that we should address rather than postponing

**Comment by rrelyea** [comment]
@ericstj  - has this been cleaned up in the corefx?
would like to close, if appropriate.

**Comment by ericstj** [comment]
I believe NuGet actually fixed this.  Specifying versions in the app will win out over anything brought in by runtime.json because of nearest wins and how the runtime.json dependencies are stitched in: they'll always be lower than app.

You can close this.
