### ISSUE TITLE
<contentFiles> doesn't work for standard .csproj project

### ISSUE THREAD

**Issue by wldevries** [NuGet/Home#2075]
I'm struggling getting contentFiles to work in a standard csproj project. The file below generates a nupkg that contains all the files in /contentFiles that it should. However when I consume the nuget package in a standard csproj project nothing is copied to the output folder. I checked the .csproj file expecting a postbuild task, but nothing was added.

The [example project](https://github.com/NuGet/Samples/tree/master/ContentFilesExample/consuming/MyUWPApp) is a project.json project. The generated .csproj doesn't contain any copy tasks nor the embedded png resource. Is contentFiles a feature only enabled for project.json projects?

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ChickenGame</id>
    <version>1.0.10</version>
    <authors>SF</authors>
    <description>Sample exists only to show a sample .nuspec file.</description>
    <contentFiles>
      <files include="**/*" buildAction="None" copyToOutput="true" flatten="true"/>
    </contentFiles>
  </metadata>
  <files>
    <file src="..\bin\release\product\games\chickengame\**\*.*"
          target="contentFiles\any\any\games\chickengame"/>
    <file src="..\bin\release\product\games\chickengame\ChickenGame.Interfaces.dll"
          target="lib\net45\ChickenGame.Interfaces.dll"/>
  </files>
</package>
```

**Comment by wldevries** [comment]
Okay sorry, I read over the part where it mentions that this feature is project.json only. A shame..

**Comment by wldevries** [comment]
I didn't read over it, it isn't mentioned in the [official documentation](https://docs.nuget.org/create/nuspec-reference#contentfiles-with-visual-studio-2015-update-1-and-later). I read it in a [blog post](http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html).

**Comment by csharpfritz** [comment]
Added reference to project.json only in the docs.

**Comment by roy-t** [comment]
Can we make this bug into a feature request? Or is there already a feature request for supporting contentFiles in csproj?

**Comment by marcussonestedtbarium** [comment]
@roy-t I'm looking for this too. Any progress the last 3.5 years? 🙄 😜
