### ISSUE TITLE
"-Verbosity detailed" should display HTTP(S) requests on console to help troubleshooting

### ISSUE THREAD

**Issue by nodakai** [NuGet/Home#2076]
My NuGet is experiencing a network problem probably due to a corporate firewall and I'm struggling to diagnose what exactly has gone wrong because it says nothing other than

```
WARNING: Unable to find version '2.0.3' of package 'FsCheck'
```

NuGet should support displaying raw HTTP(S) requests/responses like "curl -v" and "-Verbosity detailed" should turn it on.

**Comment by yishaigalatzer** [comment]
Yup, we completely agree, and it is already fixed :) Please grab the latest bits from myget - http://myget.org/gallery/nugetbuild by downloading the nuget.commandline package
