### ISSUE TITLE
Uninstall of NuGet VS extension fails

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2077]
VS 2015 14.0.25005.0 Update 2 CTP
NuGet Package Manager for VS: 3.4.0.531

In the dialog shown below, I click Uninstall on the NuGet Package Manager for Visual Studio. I am presented with a UAC dialog and approve. Then the gray UAC screen lingers for perhaps 20 seconds, and I am returned to the dialog below with no apparent removal having occurred. No errors are shown.

![image](https://cloud.githubusercontent.com/assets/3548/12892531/8103fb88-ce41-11e5-9fe6-ed11efd6fb02.png)

By the way, I am trying to remove it as an experiment to see if it's causing a regression that I'm seeing in VS2015 Update 2

**Comment by yishaigalatzer** [comment]
We don't own uninstall for the the extension, so this bug doesn't belong here, I communicated with the vs extensions team, to follow-up this.
