### ISSUE TITLE
project.json and workspace scoped packages

### ISSUE THREAD

**Issue by theo-albers** [NuGet/Home#2078]
As described in this issue https://github.com/NuGet/Home/issues/1934, repositoryPath in .nuget.config is no longer working for C# projects that switched from packages.config to project.json. The alternative approach is to use an environment variable. 
Today we can't migrate our CSPROJ files to project.json, since we have internal NuGet packages as part of our Git repository in a local folder, see https://github.com/NuGet/Home/issues/782#issuecomment-159189537. Making life easier from a dependency perspective is great with the new project.json approach, see https://github.com/NuGet/Home/issues/1757. 
Our issue: we don't version NuGet packages we produce in our Git workspace as shared code, since that's cumbersome with the old packages.config setup. We can't switch to project.json since packages are cached in the USER-folder. A simple fix would be to allow using a workspace local package cache, just like the feature we had with .nugget.config repositoryPath. Setting environment variables is not a practical solution when switching Git branches. It's also impractical when using Visual Studio Online builds. Our future goal is to use NuGet feeds in VSO for our internal packages, but that's further down the line. 

Summary of the request: support repository cache path in global.json of the solution, comparable to .nuget.config. Alternatively respect repositoryPath from .nuget.config for backwards compatibility. Packages are great, but it can be cumbersome to retrofit in an existing solution, hence the request.

**Comment by yishaigalatzer** [comment]
@theo-albers can you explain why setting NUGET_PACKAGES as part of the build script is a problem?

I think what you are hitting is actually a versioning problem of the nuget packages, if your packages where versioned independently, then things would just work.

Another alternative (which is how we build our own stuff is to blow away the cache if you flip branches around as part of your build). We introduced a command (for now on desktop only, but we plan to port it to .net cli soon - nuget locals -clear all).

Waiting to hear more of your thoughts on the matter.

**Comment by yishaigalatzer** [comment]
Btw we think that moving the packages folder long term is not a bad idea, but it does require a change in the msbuild task that finds the common packages folder, it is pretty tricky to get it released safely, so we are not addressing it just yet.

I'd still like to understand if you are blocked on this and find a way to unblock you

**Comment by theo-albers** [comment]
Hi Yishai, of course it all starts with a versioning problem. On the other hand: if versioning would be zero hassle, we would have implemented it. Let me explain our workspace:
- at some point we started sharing code via NuGet packages (in 2015 with DNX in mind)
- we moved from TFVC to VSO with Git, so our repo is not split into smaller repo's
- the easiest way to work with NuGet in traditional csproj files was to publish packages to a local folder, relative to the workspace.
- the bonus of working with our own NuGet packages: we could enforce minimum version dependencies towards external package like Entity Framework, ServiceBus, Application Insights, etc.

So our workspace consists of:
- common folder with a solution that produces multiple packages. There are dependencies between some of these packages
- an output folder where we place our NuGet packages. This folder is under source control to allow building the other solutions without having to build the common solution.
- several top level folders and each folder has a solution, consuming NuGet packages.
- each solution had a packages folder where NuGet placed downloaded packages. That was messy, so we moved from a per-solution packages folder to a top level artefact folder. Simply deleting this folder would force the build process to get our NuGet packages freshly from the output folder.

Upgrading a package in a solution can be cumbersome: 
- there can be a dependency, making the upgrade a forced uninstall, etc.
- some package (re)installs tweak app.config / web.config, sometimes blowing away packages.config
  So if we could prevent having to upgrade our internal NuGet packages, that was a bonus. Moving to project.json would solve this problem (partially), since no project files would need to be updated anymore.

For some reason VSO build couldn't locate our internal nuget packages after switching to project.json. It was able to resolve the NuGet packages:

2016-02-08T11:07:21.6609671Z All packages are compatible with .NETFramework,Version=v4.6.
2016-02-08T11:07:21.6609671Z All packages are compatible with .NETFramework,Version=v4.6 (win-anycpu).
2016-02-08T11:07:21.6609671Z All packages are compatible with .NETFramework,Version=v4.6 (win).

But the build was not able to find the packages. This could be an issue on the build agent not having the latest NuGet installed. It would be more transparent and easier to fix if the repository folder could be set transparently. 

You say: why is setting NUGET_PACKAGES a problem? We have our own MsBuild scripts, but we would like to keep things standard in the VSO environment. Setting environment variables I find nasty, since it's at a process level. It would be more straightforward to specify it in .nuget.config, since the other settings like feeds are picked up from that file as well.

One improvement we considered was to no longer check in the NuGet packages we produce. Rather the developer / build server would need to build our common solution first, which still produces the NuGet packages in the output folder. Advantage: always the code matching the package. 

So if you have a better setup, I'm happy to implement it and give it a try!

**Comment by yishaigalatzer** [comment]
I see where youbare coming from, this is a very common requirement and we are using a very similar approach.

Our strategy for this is using a common folder per user, and a local folder with packages generated as an intermediate step. We don't use msbuild to orchestrate, instead we have a powershell script that orchestrate the multiple solutions (you can choose your own of course).

The packages generated are always versions and then version is always incremented, these go to an intermediate folder which is not in source control (so we require building everything once), however you can push the packages to a shared folder or server instead to get the same effect, except you will need to switch between local and remote builds. You can achieve it by using pre-release tags for local builds that are always later than the ones in the server.

Last you can always wipe the caches using the nuget locals command (we always do it on the ci) and git clean -xdf for the local nupkgs folder.

Back to the original question:
 Setting environment variables is a very common thing at a build machine.

The packages folder needs to be knowns by the msbuild task that doesn't know how to read nuget.config yet. Similarly by the dnx or .net CLI project system. In fact nuget already supports what you just suggested, however we don't document it because the build system can't pick it up(yet), once it does this will start working.

Cc @Jasonmal

You do need at least an equivalent of vs 2015 update I on the build machine to pick up the lock file generated by nuget for things to work on the ci. 
For now you should put the disdain to environment variables away

**Comment by theo-albers** [comment]
I just upgraded the build machines to VS2015 Update 1. That way I can try again. 
About the environment variable: it's not just the build machine, it's more the developer machines. If we set the environment variable globally, the problem will be the same as not setting the variable: switching branches, like between release branches and master, we would all point to the same packages. I will investigate "nuget locals -clear all". I guess I could add a Tools menu item in our VS environments to ease clearing the cache.

**Comment by theo-albers** [comment]
In your description there is a lot of build customization. I think a lot of developers would appreciate backwards compatibility when supporting repositoryPath in .nuget.config. Breaking the behaviour with a global package folder makes life more difficult when using multiple workspaces locally in my opinion. There is no clear benefit other than reduced disk space + network IO. It would be nice to opt in when leaving out the repositoryPath setting instead of breaking the behaviour. I'm pretty sure there are good reasons from an implementation perspective. It seems to me that .nuget.config is already resolved for the feeds, so it might as well read the other config settings. The documentation suggests that repositoryPath is still supported, https://docs.nuget.org/consume/nuget-config-file. It is of course when using packages.config.

**Comment by yishaigalatzer** [comment]
Repeating what I said above:

Nuget does read it, the project systems don't yet do it.
The disk space is a huge thing, it makes the process to restore a lot faster, hence that is the default. You can always opt out and once project systems pickup reading the settings, things will be resolved for folks like you that want a folder relative to the solution.

**Comment by theo-albers** [comment]
Thanks for explaining once again. 
About disk usage: that's a real problem! It's the build process itself that is the biggest problem here. Our workspace:
- just a couple of MB of source code
- 13GB after debug build, due to copying DLL's around
- 415 MB of package cache (central repositoryPath across solutions)
  So the amount of files that are copied around during a build is enormous.

**Comment by kjbartel** [comment]
> Nuget does read it, the project systems don't yet do it.
> The disk space is a huge thing, it makes the process to restore a lot faster, hence that is the default. You can always opt out and once project systems pickup reading the settings, things will be resolved for folks like you that want a folder relative to the solution.

@yishaigalatzer From this am I to understand that having a "packages" folder relative to the solution will be supported in the future? I asked a [question on SO](http://stackoverflow.com/q/35307155/1730559) about this but the response was that it's not (going to be) supported with NuGet 3+ using project.json.

It should be noted that VSO build vNext [searches for a "packages" folder for nuget based unit test adapters](https://github.com/Microsoft/vso-agent-tasks/issues/311).

**Comment by jnm2** [comment]
Yes, what's the story on nuget based test adapters now that we are moving to project.json?

**Comment by yishaigalatzer** [comment]
1. We plan to bring back solution level packages, we have been swamped and did not get to it. We plan at a minimum to support restoring them in the next release (so if they got added manually in the packages.config file, or through 2013, we will restore them).
2. For project.json + xproj the story is different, and a good place to follow up on it is - https://github.com/dotnet/cli

**Comment by jnm2** [comment]
My case is specifically project.json + csproj in production with .NET 4.5.2, where xproj and Core are not in the picture. 

We switched from packages.config to project.json because @onovotny [recommended it](https://github.com/Humanizr/Humanizer#known-installation-issues-and-workarounds) to use Humanizer. He has a nice guide on [how to convert all your projects](https://oren.codes/2016/02/08/project-json-all-the-things/).

The v3 experience is better than v2 by light years, but it would be good to be able to put nuget based test adapters in a solution directory for vNext TFS builds while keeping all other packages in the normal v3 cache. What's the best way to get this working in v3?

**Comment by yishaigalatzer** [comment]
I agree, what folks have been doing for now is create the packages.config in the solution directory manually, and run nuget.exe restore on the file as part of the build through a build task or a script.
