### ISSUE TITLE
FSharp package references contain unnecessarily long paths

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2079]
Installing packages into FSharp libraries with packges.config leads to very long paths.

Steps
1. File > New Project > FSharp Library
2. install-package nuget.versioning
3. View the project file xml

Actual (from fsproj)

``` xml
<Reference Include="NuGet.Versioning">
      <HintPath>..\..\..\..\..\..\..\Users\username\documents\visual studio 2015\Projects\Library1\packages\NuGet.Versioning.3.3.0\lib\net45\NuGet.Versioning.dll</HintPath>
      <Private>True</Private>
</Reference>
```

Expected (from a csproj):

``` xml
 <Reference Include="NuGet.Versioning, Version=3.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\NuGet.Versioning.3.3.0\lib\net45\NuGet.Versioning.dll</HintPath>
      <Private>True</Private>
</Reference>
```

I'm only seeing this on FSharp, C# works fine.

**Comment by emgarten** [comment]
The strong name is missing in F# also

**Comment by yishaigalatzer** [comment]
Looks like this is not even going to work cross computers. Did this use to work in NuGet 2.X?

**Comment by emgarten** [comment]
@yishaigalatzer we should verify if this is fixed by the project system and consider making a change for 3.4 RTM.
