### ISSUE TITLE
Allow to specify runtime dependencies in project.json

### ISSUE THREAD

**Issue by forki** [NuGet/Home#2082]
Is it possible to specify runtime dependencies in project.json?

https://github.com/NuGet/Home/issues/2071 shows that it would be useful to give users a way to override resolver decisions when needed.
Also in some cases we need to add additional runtime dependencies that are not expressed in compile time dependencies.

**Comment by yishaigalatzer** [comment]
@ericstj can you help track the bug that is the duplicate of this issue?

**Comment by ericstj** [comment]
That'd be this one:
https://github.com/nuget/home/issues/1660
Spec is here:
https://github.com/dotnet/cli/issues/465
