### ISSUE TITLE
Xplat nuget restore --configfile is affected by NuGet.Config files in ancestor directories

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2087]
Sources found in a NuGet.Config specified with the `--configfile` argument can be affected by NuGet.Config files in ancestor dirs of the restored root.

For example:

If a NuGet.Config pointed to with `--configfile` specifies source A, and a NuGet.Config sitting in the path of `project.json` defines source B, both A and B are used to restore.

If the `--configfile` NuGet.Config specifies source A, and the path NuGet.Config contains a `<clear />` element and source B, only source B is used to restore. (The `--configfile`'s contents are cleared.)

In both cases, only source A should be used.

**Comment by dagood** [comment]
I think the current behavior of `--configfile` is that it acts as a replacement for the `%AppData%\NuGet\NuGet.Config` (or equivalent per-platform). Maybe I misinterpreted what @yishaigalatzer was saying about `--configfile`--the current behavior could make sense as the intent of the design.

The expected behavior I described would be more useful for my scenario though. :smile:

**Comment by yishaigalatzer** [comment]
I expect it to replace all of the nuget.configs and serve as is
