### ISSUE TITLE
Determine a shared v2 and v3 MachineCache location

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2088]
NuGet v2 and v3 downloads should be stored in the same machine cache. 
- Where should these be placed?
- Is hash checking needed?
- Should feed information be stored as part of this?

Today NuGet.Core.dll uses local app data to store nupkgs while v3 uses the global folder.

**Comment by yishaigalatzer** [comment]
Lets put it all in the global packages folder for now. Long term we want a new cache structure all up.

**Comment by rrelyea** [comment]
Packages.Config and transitive systems all download things to the user package folder.
While there were thoughts that having a per-feed storage may be useful, it is nowhere near top of mind at this point. Closing.
