### ISSUE TITLE
UI make unnecessary second HTTP call for top result in Installed tab

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2089]
Repro steps in "NuGet Package Manager" UI:
1) create project with a single package
2) click to Browse tab
3) open and clear fiddler
4) click to Installed tab
5) observe two identical HTTP calls made for same data

what is basically happening here is that the client is making an HTTP call for every result (left hand pane) and then a final one for the "top" result (right hand pane)

**Comment by yishaigalatzer** [comment]
Lets optimize the hang this scenario creates (like we discussed, it is not exactly what is described here)

**Comment by johnataylor** [comment]
Perhaps the bigger issue is that it actually makes network calls at all when you move between tabs.

For example, if you have the packages locally there is no need to gather the metadata just to show the list. Certainly you need to make calls to gather the details of all the versions - but that could wait.

**Comment by emgarten** [comment]
I think the goal should be:
Open NuGet UI, install tab loads - ZERO http calls are made
Click on Browse tab -> ONE http call is made

**Comment by johnataylor** [comment]
It seems now whenever you select a package in the Browse window you get a double HTTP call for the details of that particular package.
