### ISSUE TITLE
Investigate the usage of Managed C++ projects

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#2090]
Investigate the usage of Managed C++ projects. Currently, they are treated the same as native C++ projects. See https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/ProjectSystems/MSBuildNuGetProjectSystemFactory.cs#L53Need to understand if they should be treated differently. 

The following piece of code will be useful when fixing the issue and the IsNativeProject method at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/Utility/EnvDTEProjectUtility.cs#L1234

```
    private static readonly string ManagedCplusplusProjectCapability = "managed";

    /// <summary>
    /// Checks if a native project type really is a managed project, by checking project capability
    /// </summary>
    internal static bool IsClr(EnvDTEProject envDTEProject)
    {
        ThreadHelper.ThrowIfNotOnUIThread();

        var vcProject = envDTEProject?.Object as VCProject;
        var isClr = vcProject?.IsCapabilityPresent(ManagedCplusplusProjectCapability) ?? false;

        return isClr;
    }
```

**Comment by rrelyea** [comment]
will work with C++ team to drive C++ related backlog. For now, won't fix.
