### ISSUE TITLE
NuGet.Server should not reset files on update

### ISSUE THREAD

**Issue by niklaslundberg** [NuGet/Home#2092]
When installing an updated version of the NuGet.Server package, it replaces most of web.config and adds default files not needed. A suggestion is to separate the package into multiple where the core parts can be installed without all configuration updates and sample files. This can be reproduced when upgrading from NuGet.Server 2.10.0-master-0002 to NuGet.Server 2.10.0-master-0004. Elmah has solved this exact issue with elmah.corelibrary and elmah packages.

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2881
