### ISSUE TITLE
Nuget Client > 3.0 required for PCL libaries on Visual Studio 2013

### ISSUE THREAD

**Issue by NicoJuicy** [NuGet/Home#2093]
When i want to install the Nuget library for TypeExtensions ( https://www.nuget.org/packages/System.Reflection.TypeExtensions/ ) i need Nuget 3.0

I'm currently in the scenario of updating a DLL library to a PCL library, but i need some "currently unsupported" methods.

Because of the outdated version of the Nuget Client on https://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca ( Nuget Client 2013 package Manager is v. 2.8 ), i can't use this.

I also see a RC for Nuget 2.9 on https://dist.nuget.org/index.html for Visual Studio 2013, but i'd appreciate a Nuget > 3.0 version.

Could this extension be updated to support nuget.exe (v3.2.0) or can i just install the .exe on top of my previous one?

**Comment by yishaigalatzer** [comment]
We are not planning to update NuGet 3.0 on Visual Studio 2013 and below. The work to do that is much larger than it would seem and the support cost is not something we can take.

The packages themselves however do not have to declare the limitation and require nuget 3.0, they can work fine on 2.8 if the owner chose to do so.

We do plan to ship at some point 2.11, that will understand the new .NETStandard TFM, that will probably happen after Update II for Visual Studio 2015 releases.

Adding the package owner, and closing this issue.

CC @ericstj
