### ISSUE TITLE
Port reserver does not work on Linux and Mac

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2096]
The current port reserver implementation depends on:
1. System-wide mutexes (which can be replaced with file-based locking à la `ConcurrencyUtilities`)
2. Listing ports in use via `IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpListeners()`.

This fix will allow better integration testing on localhost.

Ideas:
- For the system-wide mutexes, just use the existing pattern of opening a file without sharing.
- Instead of listing active ports, just try to listen on the port and handle the exception.

**Comment by yishaigalatzer** [comment]
@joelverhagen do we still need to be fixed?

**Comment by joelverhagen** [comment]
Yes, this will allow some good functional tests to run on Mac in Linux. I think this is important since the HTTP stack in .NET Core is different from Windows.

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/411.
