### ISSUE TITLE
credential prompt is shown when you enter invalid URL for source

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2097]
This looks like a regression in 3.4.

For example, try the source:

http://http://lala/index.json

Ending in index.json causes us to recognize this as a v3 source and in this case the server registered at cname "http" actually returned some HTML. However the Visual Studio client appears to misinterpret this as an authentication challenge.

**Comment by joelverhagen** [comment]
I did a fiddler on this and it seems this is due to the fact that Redmond corpnet has an HTTP server listening to `http://http:80`. It turns out that this website returns `301 Moved Permanently` to another Redmond domain name, which throws up an NTLM auth challenge.
