### ISSUE TITLE
NuGet.CommanLine.Xplat doesn't load machineWide setting

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2099]

**Comment by shirhatti** [comment]
@zhili1208 Do you have any update on this?

**Comment by zhili1208** [comment]
@shirhatti I'm trying to fix it this week.

**Comment by zhili1208** [comment]
checked in the fix,  For mac the machine wide default path is /Library/Application Support/nuget/Config,
for Linux , it's /etc/opt/nuget/Config
