### ISSUE TITLE
ProgressAvailable not being raised

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#2101]
We have written our own UI around NuGet to use it as an extension manager for our apps. So far, this all works great, but now we wanted to add download progress updates (in case of slow internet / larger packages). We use this code (it's ugly, but it's because NuGet doesn't expose any of this). We have overridden the _NuGet.PackageManager_ and subscribe to the right events.

```
        public void NotifyOperationStarting(string installPath, PackageOperationType operationType, IPackageDetails packageDetails)
        {
            Argument.IsNotNull(() => packageDetails);

            SubscribeToDownloadProgress(packageDetails);

            OperationStarting.SafeInvoke(this, new PackageOperationEventArgs(packageDetails, installPath, operationType));
        }

        private object GetPackageDownloaderInstance(IPackageDetails packageDetails)
        {
            var innerPackagePropertyInfo = packageDetails.GetType().GetPropertyEx("Package");
            if (innerPackagePropertyInfo == null)
            {
                return null;
            }

            var innerPackage = innerPackagePropertyInfo.GetValue(packageDetails, null);
            if (innerPackage == null)
            {
                return null;
            }

            var downloaderPropertyInfo = innerPackage.GetType().GetPropertyEx("Downloader");
            if (downloaderPropertyInfo == null)
            {
                return null;
            }

            var downloader = downloaderPropertyInfo.GetValue(innerPackage, null);
            if (downloader == null)
            {
                return null;
            }

            return downloader;
        }

        private void OnPackageDownloadProgress(object sender, ProgressEventArgs e)
        {
            Log.Debug("Progress of operation '{0}': {1} %", e.Operation, e.PercentComplete);
        }
```

We are able to subscribe to the event, but the _OnPackageDownloadProgress_ event is never raised (so it seems). Is this functionality implemented in NuGet or was it intended but never finished? And of course, if we are doing something wrong, I am happy to hear that as well :-)

For the full code, see this open source library:

https://github.com/WildGums/Orc.NuGetExplorer/blob/develop/src/Orc.NuGetExplorer/Orc.NuGetExplorer.Shared/NuGet/PackageManager.cs

**Comment by yishaigalatzer** [comment]
To be honest I'm not sure, and as we don't plan to support nuget.core going forward, not sure I'm inclined to dive into this to figure it out. Sorry I really don't mean to push you off, just not familiar enough and focused elsewhere at the moment.

I'm moving to the discussions milestone, the nuget2 code is of course available on github.com/nuget/nuget2 for your convenience.

**Comment by GeertvanHorrik** [comment]
Ok, what is the right package to use in the future for our extensibility if NuGet.Core is being marked obsolete?

**Comment by yishaigalatzer** [comment]
It is a set of packages, depending what you want to do. I would follow the code from nuget.commandline project as a sample

**Comment by rrelyea** [comment]
Marking won't fix as this isn't anywhere near the top of our backlog.
