### ISSUE TITLE
Xplat restore race condition/error when dependencies are the same with different casing

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2102]
When doing a recursive restore on projects that contain the same package with multiple casings, restore tries to install them at the same time, causing errors like: 

```
The process cannot access the file '...p\Microsoft.TargetingPack.NetFramework.v4.5\1.0.1\Microsoft.TargetingPack.NetFramework.v4.5.nuspec' because it is being used by another process.
```

To repro, do a recursive restore on a directory with:
- `a\project.json` with dependency `"Microsoft.TargetingPack.NETFramework.v4.5": "1.0.1"`
- `b\project.json` with dependency `"Microsoft.TargetingPack.NetFramework.v4.5": "1.0.1"`

Here's a zip with this set up, plus a batch file so you can see the sources I'm using: [parallel-repro-tree.zip](https://github.com/NuGet/Home/files/126848/parallel-repro-tree.zip).

I'm using `NuGet.CommandLine.XPlat.exe` created using `dotnet publish -r win7-x86 -f dnx451` in the NuGet.CommandLine.XPlat directory.

---

A workaround is to use `--disable-parallel`. A fix is to make sure that case-insensitivity is handled well by [`ConcurrencyUtilities.ExecuteWithFileLockedAsync`](https://github.com/NuGet/NuGet.Client/blob/08aaf9c78892f53a997ae429b13ee551aa54e418/src/NuGet.Core/NuGet.Common/ConcurrencyUtilities.cs#L17) or its callers.

Adding `filePath = filePath.ToLowerInvariant();` to the beginning of that method makes the error go away, but that probably isn't a good fix. If that method is used in a case-sensitive context there would be unnecessary waiting.

/cc @ericstj

**Comment by ericstj** [comment]
Seems to me like the right fix here would be to first have nuget normalize the path with the _actual_ casing it has determined for the package ID from the server.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@16a7798c143ab8bb6707464ca3a49ba5e21fb8c1
