### ISSUE TITLE
Misleading error message for failed dependency

### ISSUE THREAD

**Issue by dazinator** [NuGet/Home#2103]
I have:

`Package A` Depends On `Package B`
`Package A` Depends On `Package C`
`Package B` Depends On `Package C`

`Package C` is `Microsoft.AspNet.Mvc`

I am using an Aggregate repository, where Package A and B is on a local folder feed, and Package C is already installed into the target project (packages.config).

When I attempt to install `Package A` with the NuGetPackageManager I get this exception:

![image](https://cloud.githubusercontent.com/assets/3176632/12987142/ab4c5daa-d0f2-11e5-8f35-77c73e3302b8.png)

I have obfuscated the names of packages A and B in that image.

This looks like it's telling me that it can't find a compatible `Package C` - but `Package C` is already installed, and `Package C` satisfies the dependency constraints of packages A and B perfectly.

I did a bit more digging, and found that the issue was actually that `Package A` and `Package B` both also had a dependency on `Package D` and `Package D` wasn' available anywhere, on any of the feeds.

When I added `Package D` to one of the feeds, the error cleared, and I was able to install `Package C` just fine..

**Comment by emgarten** [comment]
NuGetPackageManager (NuGet.PackageManagement.dll) does not support Aggregate repositories (nuget.core.dll)

Are you able to repro this using NuGet through visual studio, or this is with your own API calls?

**Comment by dazinator** [comment]
Its with my own API calls but it was based upon your own code that used an aggregate repository. I know you guys are splitting stuff out at present but it seems nuget.core (v2) is still leveraged in some places or perhaps i am confused. In any case I am using v3 right now with an aggregate repo and all seems to be working ok except the misleading error message. Happy to close this if its premature!

**Comment by emgarten** [comment]
nuget.core (v2) will be going away soon

**Comment by yishaigalatzer** [comment]
We are not supporting nuget.core anymore, it is going away and we are just chipping away at it. We definitely do not use it for resolving dependencies or reporting errors and we don't plan to make any changes in that area of the code base. 

If you see similar issues with the new code base we'd love to know and fix.

**Comment by dazinator** [comment]
Cool. May I ask if there is / will be an alternative to aggregaterepository in v3? Will NuGet.PackageManagemet support this in future? I rely on this ability to resolve dependencies from multiple sources at package install time.

**Comment by yishaigalatzer** [comment]
You can pass multiple sources to restore. Follow the code in restore command in nuget.exe
