### ISSUE TITLE
Restore with project references doesn't do framework checks

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#2104]
Example:
Project1 -> project.json:

```
{
  "dependencies": { },
  "frameworks": {
    "dnxcore50": { }
  }
}
```

Project2 -> project.json:

```
{
  "dependencies": {
    "Project1": "1.0.0-*"
  },
  "frameworks": {
    "dnx451":{}
  }
}
```

Notice how Project1 builds only for `dnxcore50` and Project2 builds only for `dnx451`
Restore will succeed without any failures, but build will fail because it can't find the Project1 dependency on `dnx451`

**Comment by yishaigalatzer** [comment]
What did DNU do in this case?

**Comment by davidfowl** [comment]
Same behavior as if a package had a missing framework

**Comment by yishaigalatzer** [comment]
Thanks

**Comment by emgarten** [comment]
Packages are currently checked for compatible assets by guard rails. Should NuGet still do this or should this be done by the guard rails replacement?

**Comment by emgarten** [comment]
Projects will now be checked as part of the TFM compatibility check.

NuGet/NuGet.Client@a06a5906ab294fee6e442cbedfb39cdeaeafff6a
