### ISSUE TITLE
Remove dev14 only references from the VSIX

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2105]
The Dev15 vsix contains references to Dev14 only assemblies and fails to load on Dev15.

Example: 
"Microsoft.VisualStudio.Services.Client": "14.83.2"

**Comment by emgarten** [comment]
This dependency appears to have been added as part of the VSO credential provider.

**Comment by yishaigalatzer** [comment]
This should be handled by a redesign from the VSO team of their bits in NuGet
