### ISSUE TITLE
NuGet silently ignores invalid config file

### ISSUE THREAD

**Issue by victorhurdugaci** [NuGet/Home#2108]
Try to restore with this and you'll see that there's no error:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="AspNetVNext" value="\\aspnetci\Drops\latest-packages\dev" />
        <add key="NuGet" value="https://api.nuget.org/v3/index.json"; />
        <add key="KoreBuild" value="\\aspnetci\Drops\Universe\dev\latest\build" />
        <add key="External" value="\\aspnetci\Drops\latest-packages\external\dev" />
    </packageSources>
</configuration>
```

The invalid char is the `;` after `value="https://api.nuget.org/v3/index.json"`

**Comment by yishaigalatzer** [comment]
@victorhurdugaci we already track invalid config files. But I assume that you have a config file somewhere else that provides feeds? If so please close, we are already handling this. If not please provide more details

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/1567
