### ISSUE TITLE
NuGet XPlat output should identify concurrent streams

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#2109]
Consider the following [invented] output:

log: restoring dependencies for foo/project.json
log: restoring dependencies for bar/project.json
warn : Detected package downgrade:...

which project was affected? This would be much easier to diagnose if each parallel restore operation were assigned an ID that was persisted. Let's say that that ID is an int, then the output could look like this:

log(1): restoring dependencies for foo/project.json
log(2): restoring dependencies for bar/project.json
warn(1): Detected package downgrade:...

Now I know that the downgrade was detected during the restore of foo/project.json

**Comment by yishaigalatzer** [comment]
I believe the solution for this was to summarize the errors on the bottom of the restore output, we should also summarize errors

**Comment by yishaigalatzer** [comment]
@joelverhagen this should also address all restore scenario in nuget.exe
1. Restore .NET 4 app with packages.config
2. Restore .NET 4 app with project.json
3. Restore .NET Core app with project.json

Now mix all of these is a solution, and restore at the solution level

**Comment by emgarten** [comment]
This has been fixed by the summary mentioned above.
