### ISSUE TITLE
Group errors and warnings by graph in the output

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2110]
``` JSON
{
    "version": "1.0.0-*",
    "compilationOptions": {
        "emitEntryPoint": true
    },

    "dependencies": {
        "System.Runtime": "4.0.20",
        "NETStandard.Library": "1.0.0-rc2-23728"
    },

    "frameworks": {
        "dnxcore50": { }
    }
}
```

I'm downgrading System.Runtime to 4.0.20. The compilation graph is downgraded by the runtime graph has been lifted by `runtime.json`. Check the output:

```
Davids-MacBook-Pro:foo dfowler$ dotnet restore
log  : Restoring packages for /Users/dfowler/dev/foo/project.json...
warn : Dependency specified was System.Runtime (>= 4.0.20) but ended up with System.Runtime 4.0.21-rc2-23728.
warn : Detected package downgrade: System.Runtime from 4.0.21-rc2-23728 to 4.0.20
 foo (>= 1.0.0) -> NETStandard.Library (>= 1.0.0-rc2-23728) -> NETStandard.Platform (>= 1.0.0-rc2-23728) -> System.Runtime (>= 4.0.21-rc2-23728)
 foo (>= 1.0.0) -> System.Runtime (>= 4.0.20)
log  : Committing restore...
log  : Restore completed in 1094ms.
NuGet Config files used:
    /Users/dfowler/dev/foo/NuGet.Config
    /Users/dfowler/.nuget/NuGet/NuGet.Config
Feeds used:
    https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
    https://api.nuget.org/v3/index.json
```

@yishaigalatzer wanted to apply the same rules to apply to the runtime graph but I don't know what side effects there are if we start doing that (like completely breaking everything :smile:) 

/cc @ericstj

**Comment by yishaigalatzer** [comment]
The output doesn't tell you what ever in the graph (and the path to it) made that violation. I'd like to see that somewhere otherwise debugging sucks.

We also wanted top level to always win (I assume this is what you refer to)

**Comment by davidfowl** [comment]
> The output doesn't tell you what ever in the graph (and the path to it) made that violation. I'd like to see that somewhere otherwise debugging sucks.

Yes! That's what this bug is about, so we agree here.

> We also wanted top level to always win (I assume this is what you refer to)

That's what we spoke about on the other thread but it would actually break `runtime.json` completely for the BCL packages. I don't want to pollute this bug though so we should focus on the output formatting.

**Comment by TimBarham** [comment]
@yishaigalatzer and/or @davidfowl - could you guys clarify for me exactly what it is you want to see in the output (an example output based on the example `project.json` above would help)? Thanks!

**Comment by harikmenon** [comment]
@glennc had a pretty sweet looking prototype around showing errors and issues with resolutions in the CLI, is this design or approach something we can leverage?

**Comment by glennc** [comment]
I have no problem using what I have as a basis for some of this if it helps. Do you have a project.json that I can restore? I can put some screenshots in here showing what it does already and we can go from there

**Comment by TimBarham** [comment]
I was just working with @davidfowl's `project.json` above (which forces downgrade of `System.Runtime`)
