### ISSUE TITLE
Inconsistent Behavior in Packages View in Package Manager UI

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2111]
The search term stays constant across different tab views ("Browse" "Installed" "Updates") in the Package Manager UI and the search term is applied to filter each view. However, it is not applied consistently and this leads to an odd user experience. For example: if you search for "owin system web" in the Browse tab you will find a bunch of reasonably matching packages. Now switch the tab to "Installed" even if you have just install Microsoft.Owin.Host.SystemWeb you won't see it in this view. You would however see it if you simplified the search term to "owin" so the behavior is very inconsistent and dependent on the particular contents of the search box.

This is happening because the code is using completely different technologies to produce each view and the Lucene based multi-term search that creates the Browse view is a different semantic to the more simplistic pattern match used to create the "Installed" view.

The "Installed" view should use the same code (or at least the same algorithm) as the "Browse" view.

**Comment by rrelyea** [comment]
yes, search needs help. have major items in backlog to improve via server and client.
