### ISSUE TITLE
Duplicate project ASSERT when building NuGet.Clients.sln

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#2112]
Steps to reproduce:
- Clone NuGet.Client & switch to latest commit on "dev" branch (f585e42e357158ac8d7f2478223355e32d15fa09 as of 2016-02-13).
- Open NuGet.Clients.sln in VS2015 community, Update 1.
- Build solution from IDE.

![image](https://cloud.githubusercontent.com/assets/2671400/13036606/0fbf3976-d36c-11e5-9166-afae576dafbf.png)

Building with the `build.ps1` script succeeds, so the problem is limited to building through the VS2015  IDE. Still, this issue makes it hard to debug NuGet problems & to contribute back to the NuGet project.

**Comment by emgarten** [comment]
@forderud do you have a debug version of NuGet installed that you built yourself? The repro steps given are not enough to cause an assert like this.

**Comment by forderud** [comment]
You're of course right @emgarten. I had a locally built NuGet 3.4 "alpha version" plugin installed. Dowgrading to the official 3.3.0 release fixed my issue.

Thanks a lot for your assistance!
