### ISSUE TITLE
Badges API

### ISSUE THREAD

**Issue by bchavez** [NuGet/Home#2113]
Currently using GitHub badges for my projects: https://github.com/bchavez/RethinkDb.Driver

The service I'm using to render badges is http://shields.io/. The problem is shields.io constantly offline or inaccessible. I've had so many problems getting NuGet metadata for the project.

![screen603](https://cloud.githubusercontent.com/assets/478118/13060478/a5020502-d3e6-11e5-90a8-c944d208ae10.png)

Would be nice if NuGet provided an API to render badges directly:
- Total Downloads.
- Download Count of current version.
- Last published date.

Thanks,
Brian

**Comment by glen35** [comment]
Thank you.

**Comment by yishaigalatzer** [comment]
Moved to gallery
