### ISSUE TITLE
Remove RID inference

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2114]
It's causing a bunch of problems:
- When you need to actually specify a RID, there's a usability cliff you fall off. You have to know what the inferred RIDs were in the first place.
- Class libraries that target concrete TFMs need `Microsoft.NETCore.Platforms` because they look like applications. 
- Since we skip compile time only TFMs, we're skipping RID restore if they are specified (this is just a bug though)

We should just drop the inference altogether.

/cc @anurse @ericstj @emgarten @yishaigalatzer

**Comment by yishaigalatzer** [comment]
@davidfowl can you provide more data. I thought we had this discussion when we decided to do RID inference, and we wanted the basic scenario to be simple, how is this going to be simple for anyone? Should rids be defined in project.json, in the command line parameters or both?

**Comment by davidfowl** [comment]
What data we you looking for specifically? There might be other ways to achieve the simplicity without baking defaults like this into to the tool. Right now it's causing friction (in the cases outlined above) and the special casing of compile time only tfms is a hack

**Comment by emgarten** [comment]
Once this change is made how will the CLI repo build, will RIDs be added to the project.json files or will it be passed on the command line? Is there going to be a suggested way to provide the RIDs?

What is a scenario where a compile time txm such as netstandard needs a runtime?

**Comment by davidfowl** [comment]
@emgarten the CLI will add the RIDs to `project.json`. Suggested way is putting it in the `project.json`.

> What is a scenario where a compile time txm such as netstandard needs a runtime?

We don't want to denote TFMs as compile only anymore, that was a hack. We're going to instead change the NetStandard.Library packages so that they are split into reference only and runtime packages.

We want to make it so that applications can be fully portable. This means that it should be possible to pick netstandard + runtime to go standalone, but without a runtime, it would be portable. We don't want NuGet to do _any_ inference based on TFM in this case.

**Comment by emgarten** [comment]
Makes sense, I'll remove the RID inference in xplat.

**Comment by davidfowl** [comment]
@emgarten it was never in NuGet before and shouldn't exist in any form. Just clarifying that it only exists in xplat.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@3bb16d3467f5680eefa61365fa5acc401e70ab6c

**Comment by analogrelay** [comment]
@ericstj had some concerns this might cause some issues in corefx. /cc @dagood

If corefx is using the `runtimes` section everywhere though, nothing should have to change.

**Comment by dagood** [comment]
I'll have to look into that... I haven't seen if/how the inferred+restored runtime packages are used in the corefx build. There aren't `runtimes` sections on most corefx project.jsons (some were added as workarounds for inferred RID issues--excited to take those out!) but I think they're present where runtime packages are actually needed. Thanks!

**Comment by ericstj** [comment]
@dagood We'll require a runtime section wherever we are resolving for a concrete target framework in order to satisfy the gaurdrails check.  I think we just need to be careful about picking up this new build of the CLI and add the right RIDs to our projects to continue to satisfy gaurdrails.

If you can give us a build of this up front to test before it goes into the CLI that should help us avoid a firedrill.

**Comment by analogrelay** [comment]
Reopening this. We jumped the gun slightly and dotnet-cli and ASP.NET Core really need RID inference to stick around for a little bit longer. We'll ping this when the necessary publishing changes have been made to allow us to re-remove this.

**Comment by analogrelay** [comment]
See NuGet/NuGet.Client#316

**Comment by yishaigalatzer** [comment]
@anurse since you are on top, and took it out, can you take care of putting it back in when you are done?

**Comment by analogrelay** [comment]
https://github.com/NuGet/NuGet.Client/pull/391 removes inference by default, but keeps it available temporarily as a command line switch. We'll still want to remove the switch before any RTM version of NuGet goes out, so I'm going to leave this bug open. Once https://github.com/NuGet/NuGet.Client/pull/391 goes in, we will work with CoreFX, .NET CLI and ASP.NET to ensure everyone is ready to remove inference for good.

**Comment by yishaigalatzer** [comment]
This is now done

**Comment by emgarten** [comment]
Verified on 3.5.0-beta
