### ISSUE TITLE
Put the project and dependencies in the lock file

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2115]
This will make it so that consumers don't always need to read both the `project.json` file and the `project.lock.json` file. We just need add an entry for the project so that framework assemblies and dependencies show up in the lock file.

/cc @emgarten

**Comment by emgarten** [comment]
Would this be in the targets graphs or in a new section of the lock file?

**Comment by glen35** [comment]
Is that right

**Comment by glen35** [comment]
From 67c0afc1da354d8571f51b6f0af8f2794117fd10 Mon Sep 17 00:00:00 2001
From: The Octocat <octocat@nowhere.com>
Date: Sun, 27 Apr 2014 15:36:39 +0530
Subject: [PATCH] updated index for better welcome message

**Comment by davidfowl** [comment]
targets

**Comment by yishaigalatzer** [comment]
@emgarten status? Do we need this for RC2?

**Comment by davidfowl** [comment]
Can be RTM
