### ISSUE TITLE
Dependency version resolution appears broken

### ISSUE THREAD

**Issue by isobel-cullen** [NuGet/Home#2118]
Attempting to upgrade an internal project `bwf-knockout-kendo` gives the following error:

> Unable to find a version of 'jQuery' that is compatible with 'bootstrap 3.3.1 constraint: jQuery (≥ 1.9.0)', 'Bootstrap.Multiselect 0.9.13 constraint: jQuery (≥ 1.10.0)', 'bwf-knockout-kendo 2016.1.0.6 constraint: jQuery (= 2.0.3)', 'Sammy.js 0.7.4 constraint: jQuery (≥ 1.4.1)'

`bwf-knockout-kendo` depends on three projects: `jQuery`, `KnockoutJS`, and an internal repacking of KendoUI (which has no dependencies, just content).

The project already has `jQuery 2.0.3`, `bootstrap 3.3.1`, `Sammy 0.7.4`, and `Bootstrap.Multiselect 0.9.13` installed.

The internal nuget source is an installation of the `NugetGallery` software (built within from the master branch within the last month).

Any ideas?

**Comment by maartenba** [comment]
Can you define "within the last month"? (if this was within the last 7 days then please grab a new one from master)

**Comment by isobel-cullen** [comment]
Built from https://github.com/NuGet/NuGetGallery/commit/3f2b1429c669af1a2a6c6143e0a1e9dc86e675eb

**Comment by maartenba** [comment]
That should be good. Let's wait until someone can comment on the client bits.

**Comment by yishaigalatzer** [comment]
What version of nuget are you using? Is it in visual studio or nuget.exe?

This seems like something that should work, so if you are still seeing this on the latest (nuget 3.3), can you please share a small repro project?

**Comment by isobel-cullen** [comment]
Latest visual studio nuget (VS2015 u1).

Will see if I can get a reproduction project tomorrow. Hopefully the issue doesn't just manifest when the dependant package is from a different source to one being upgraded.

**Comment by isobel-cullen** [comment]
Annoyingly, installing the same packages in a fresh project works. There must be something else going on here.

Log of attempting to use nuget.exe directly https://gist.github.com/ProfessionalNihilist/c227077b8a4be5b2d14e

**Comment by yishaigalatzer** [comment]
I can't see the log, also are you able to share a repro project?

**Comment by rrelyea** [comment]
Doesn't seem to be an actionable issue. Closing.
