### ISSUE TITLE
NuGet 3 dependency resolution model breaks the ability to use Debug builds

### ISSUE THREAD

**Issue by Alovchin91** [NuGet/Home#2120]
We are using private NuGet server in our company for our internal SDKs and Core libraries. We need to deploy Debug versions of our libs to out private NuGet server as well.

When we've been using NuGet 2, we used a very simple trick: we put Debug versions into \build\ folder inside a NuGet package, and also used a simple .targets file that added a reference to these Debug libs into our projects. Everything worked fine.

Now, with NuGet 3 and UWP, this doesn't work anymore. We now have to use CopyFiles task to simply copy the Debug references over what NuGet 3 resolves. But this doesn't let us use these Debug libraries in appx packages, for example, deployed to the phones.

Is there any possibility to resolve this? Maybe I could copy the Debug references over what is being put inside AppX before the AppX is being deployed. How could I achieve the good old behavior? Thanks.

**Comment by yishaigalatzer** [comment]
You still should be able to use targets, the feature was not removed, what is exactly broken? CC @jasonmalinowski 

Alternatively you can ship packages in debug and release feeds, you need to wipe the caches between builds if you want to get debug bits.

I'm keeping this open for now, so we can figure out if you are completely unblocked. We do want to discuss a top level debug support

CC @davidfowl

**Comment by Alovchin91** [comment]
@yishaigalatzer I still do use targets, but now instead of invoking the reference into the project, I have to simply copy the Debug files over those copied by NuGet 3 when building the project. This leads to inability to get Debug files in the AppX.

**Comment by yishaigalatzer** [comment]
I see, I agree we should do something better here. Butbfor now why not place the dlls only in the targets?

**Comment by Alovchin91** [comment]
@yishaigalatzer I'm sorry, I don't get what do you suggest by placing the dlls only in the targets?

**Comment by yishaigalatzer** [comment]
Create a target file with your dlls referenced, don't put them in the lib and pivot in the msbuild target.

Alternatively push the packages to two feeds and if you want debug builds clear the cache swap the feeds and restore
