### ISSUE TITLE
VS Package Manager Dialog hides details of packages when installed and only 1 version published

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2124]
Visual Studio Package Manager Dialog doesn't always appear to show the details of packages when using v3.

This appears to be a regression possibly coupled to the source fallback logic checked in on Friday.

**Comment by yishaigalatzer** [comment]
@johnataylor can you update on this?

**Comment by johnataylor** [comment]
This is a problem with owin/1.0.
The detail pane is not displayed. The versions appear to be there but there are some semver problems on this one.

**Comment by johnataylor** [comment]
OK this turns out to having nothing to do with semver or broken metadata. All the code is working correctly and this behavior is not a regression.

But this is clearly a UI design bug.

Specifically the version list is only populated by package version you _don't_ have install. So if there is only one version of a package and you have that one version installed then you will always see nothing in the detail pane. This happens in both the Installed and Browse tab. Clearly this is non-sense.

As discussed moving this to 3.5. Assigning to @yishaigalatzer to drive decision on UI Design.
