### ISSUE TITLE
Visual Studio Package Manager Dialog Bad Clipping in UI in Right Hand Pane

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2126]
In the Visual Studio Package Manager Dialog, select the Browse tab, move the central vertical splitter to the right to reduce the size of the right hand side "details view" pane. Now the Installed and Version drop down boxes are badly clipped to their right hand side.

**Comment by rrelyea** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/de49245d1f71daa69cdfa9a2bd6dc1a1cad1e91c
