### ISSUE TITLE
NuGet.Client - Restore with WinRT C++ fails

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#213]
Issue copied from [Codeplex](https://nuget.codeplex.com/workitem/4401):

I have solution with WinRT C# app and Universal C++/CX project(s) Shared, Windows and Windows Phone. 
 When I try to run Restore command from CMD, I get strange error that .vcxitems is not supported anymore with msbuild. 

https://ci.appveyor.com/project/AleksandarDev/sparkiy-client/build/0.1.33

**Comment by emgarten** [comment]
This issue is fixed in the 3.0.0 command line. All packages were restored without errors on a solution that hits this error using nuget.exe 2.8.6.

**Comment by emgarten** [comment]
This error is reproing again, possibly due to changing the version of MSBuild used by nuget.exe

**Comment by emgarten** [comment]
@feiling an msbuild exception is thrown when calling: new Solution(path)  in nuget.exe. It looks like msbuild immediately parses the entire solution and all project files and throws on .vcxitems.  This was broken in 2.8.6 but worked briefly in 3.0.0. It may be due to the version of msbuild used.
