### ISSUE TITLE
missing text in negative error message

### ISSUE THREAD

**Issue by michaelcfanning** [NuGet/Home#2130]
In VS, for the 'add pacakge referernece' feature, we show an install failure message returned by Nuget that doesn't scan well:

Package install failed: No latest version found for the 'Newton.Json' for the given source repositories and resolution context.

We should either add 'package' after the package name or emit the 'the' that precedes the package name.

**Comment by rohit21agrawal** [comment]
@michaelcfanning  Can you list the exact steps to repro this?

**Comment by michaelcfanning** [comment]
I cannot. I see the relevant string here.

src\NuGet.Core\NuGet.PackageManagement\Strings.resx
 <value>No latest version found for '{0}' for the given source repositories and resolution context</value>

It doesn't show the issue. Checking history, it appears Cyrus fixed this.
https://github.com/NuGet/NuGet.Client/commit/d91d4b95696d25c90f4b3810cfecf007ebaedf95

**Comment by rohit21agrawal** [comment]
Closing as fixed.
