### ISSUE TITLE
csproj w/ project.json project reference treated as external package reference

### ISSUE THREAD

**Issue by gregjhogan** [NuGet/Home#2131]
For a .NET 4.6 project (csproj file using VS 2015) using a project.json, a project reference seems to be treated as if it is a external package.  They show up in the "Manage NuGet Packages..." screen and TFS builds attempt to restore the packages.

Here is how I specified the project dependency

``` json
"dependencies": {
    "MyProject": "1.0.0-*",
}
```

Here is the error I get from our TFS builds
`Unable to resolve MyProject (≥ 1.0.0--) for .NETFramework,Version=v4.6.`

The same project.json in a DNX (xproj file using VS 2015) project does not seem to have this issues.

**Comment by emgarten** [comment]
XProj and CSProj resolve project references differently. CSProj project references must come from the csproj file. The project.json file contains only package references.

**Comment by yishaigalatzer** [comment]
We are adding a type support to clearly specify

``` json
"dependencies": {
    "MyProject": {
       "target": "project",
     }
}
```

Note that this still will not be supported in project.json on csproj, but it will help disambiguate for xproj

**Comment by gregjhogan** [comment]
@emgarten @yishaigalatzer will I eventually be able to do the following and have it pick up project dependencies from the csproj file and package dependencies from the project.json file?

```
nuget pack MyProject.csproj -IncludeReferencedProjects
```

**Comment by yishaigalatzer** [comment]
We haven't decided if that is a pattern we want to encourage going forward or not. Still a good discussion to have:

Should dependent projects be separate packages by default, or should we enable the scenario you mentioned where sub projects gets packed into the same package. 

The main issue with this is that it gets pretty tricky to define which P2P references go out as packages and which gets bundled, which leads to lots of confusion and bugs. 

So something to keep thinking about until we get to a good design, I don't want us to repeat the pack story with packages.config that was only really going so far and then hitting a cliff

**Comment by gregjhogan** [comment]
@yishaigalatzer there may be another scenario to consider, too.  I currently use `-IncludeReferencedProjects` for dependent projects that have their own nuspec file, and it adds those projects as a package dependency when packing.  So I have a solution that builds multiple packages which depend on each other.  My experience has been that this works great with nuspec files, and was hoping you would support this for package.json + csproj meaning I can switch to using package.json before switching to using xproj projects.  Thanks!
