### ISSUE TITLE
Nuget automatically removes dependencies from packages.config

### ISSUE THREAD

**Issue by Dashue** [NuGet/Home#2132]
To set the scene: I have a solution with a bunch of projects. There is issues with the packages.config of one project, let's call it 'Project X'.

Whenever I install or update a nuget that is in another project than 'Project X', some packages from the packages.config of 'Project X' gets removed.
I then manually have to install those packages into 'Project X' again.

I'm using a shared path for nuget packages, through a nuget.config at the root of my solution.

```
<configuration>
  <config>
    <add key="repositoryPath" value="./Packages" />
  </config>
</configuration>
```

Worth mentioning is that 'Project X' is referenced by multiple different solutions.
The hintpaths of the references appears to be correct, pointing to the shared packages folder.

I do not understand why this is happening or what is causing it.

Please help me with this weird situation

Edit: It actually happens by just rebuilding the solution
NuGet Version: 3.3.0.212
Visual studio 2013

**Comment by yishaigalatzer** [comment]
I don't have enough information from the report to make a determination so I'll try to start you up on two paths:
1.  We do no support sharing packages folders across multiple solutions. I'm guessing what you are seeing is that one solution is removing the packages from another solution rather from two projects in the same solution.
2. There is also a potential mix up in the versions you are reporting

NuGet version 3.3.0.212 is a nuget.exe version that matches visual studio 2015. So how exactly are you updating the packages? Is it in nuget.exe or in visual studio.

FYI - We do have a known issue in nuget.exe that looks like the same issue you are reporting it was fixed in 3.4 which you can find in myget.org on the nugetbuild feed.

**Comment by Dashue** [comment]
Hey, thanks for your input.

Do you possibly know the ticket number for that issue?

The update is done through "Package Manager Console", I've possibly run "nuget update -self" there, could that explain the version? I do also have vs2015 installed.

I don't think it's caused by your 1)

As if I install a package into project X, then clean and build, it would have removed it again from packages.config

Appreciate your time, apologies for taking a while to get back.
Thanks!

**Comment by yishaigalatzer** [comment]
Hey @Dashue can you please clarify your situation, I'm a bit confused because you discuss nuget.exe and Package Manager Console in Visual studio. Which of them are you using?

Second question: Is the package removed from the packages.config file or from the packages folder?

**Comment by Dashue** [comment]
Using package manager console.
Removed from packages.config, not from folder

Cheers

**Comment by johnataylor** [comment]
@dashue it would be great if you could construct a solution with multiple projects that exhibits the behavior you describe and send it to us (or alternatively describe the steps exactly) can you do that?

**Comment by yishaigalatzer** [comment]
@Dashue, any chance you can share a solution with a repro? This is something we haven't seen before.

Please also specify exactly what version of visual studio you are doing this in (there is still confusion if it is 2013 or 2015, and note we only support bug fixes of this kind in 2015)

**Comment by Dashue** [comment]
Hey, I'll try. As far as I can tell it's just two different solutions, sharing the same project that is using nuget. Visual studio 2013. A simple build will manipulate the packages.config in my case remove entries.

I can't share the code that currently is experiencing this issue but I'll try to reproduce as I find time.
I'll basically try to create two different solutions containing the same project, hoping it will trigger the effect.

**Comment by yishaigalatzer** [comment]
How can a build update your packages.config? There is nothing in nuget that touches that file during build?

Also please see if this repros in 2015 or not. We mostly spent our time and bug fixes in Visual Studio 2015 I and beyond (nuget 3.3 or you can try nuget 3.4 RC from nuget.org)

**Comment by Dashue** [comment]
I haven't been able to reproduce in a isolated solution. I configured the build output level to Diagnostics, but nothing stands out as being the cause. I think it's happening when restoring packages, however it says "already installed, skipping". 

Happening in 2015 as well. Building one solution properly puts the right content in the packages.config, building another removes some of those, building the first one puts it back again. And back and forth.

3.4 RC does not solve it.

I will try to strip down the code exhibiting the issue, perhaps I can remove everything to make it shareable.

Thanks for your time

**Comment by Dashue** [comment]
Some further testing shows that it's happening withing the same solution as well by switching between different build configurations i.e debug and release. Does that give any hint as to what might be causing it?

**Comment by yishaigalatzer** [comment]
Unfortunately it doesn't, we haven't seen this anywhere else. My only guess is that you might have a call to nuget.exe as part of your build targets (and that is no longer supported)

**Comment by Dashue** [comment]
Nevermind, yet again the problem was of the human sort :)

We're using a modular approach with with a core website and customized websites being copied into the core website upon build. Guess which file wasn't being excluded in the copy, it was just bad luck that the customized dependencies listed in packages was a subset of the core packages.config.
Had there just been one very different package it would have been obvious what was happening.

I thank you again for your time and help, and do apologize for wasting it.

**Comment by yishaigalatzer** [comment]
Thanks a ton for keeping engaged, these things happen regularly in complex systems, so due diligence is the only way to resolve them.

Much appreciated!
