### ISSUE TITLE
Corrupt cache file causes dotnet restore to crash

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#2133]
During `dotnet restore` on our CI agents, the restore operation fails:

```
[09:41:07] warn : The file 'C:\Users\ciagent\AppData\Local\NuGet\v3-cache\a3f7996bd74fb18cce048733dd07221a97fca25d$spnetcidev_api_v3_flatcontainer_\nupkg_System.Collections.4.0.11-rc2-23805.dat' is corrupt.
[09:41:07] error: End of Central Directory record could not be found.
```

Using dotnet 1.0.0.001290

Deleting the cache folder manually solves the crash. But it would be better if NuGet automatically discarded corrupt cache files.

**Comment by yishaigalatzer** [comment]
@joelverhagen we have a fixed a ton of bugs in this area. The mode should be that we first write down a file only when it is completed (by writing to a temp extension, then renaming/moving).

We should also recover if the file is corrupt and clear it automatically like @natemcmaster is suggesting.

@natemcmaster how did you get a corrupt file? Is it by interrupting a download?

**Comment by natemcmaster** [comment]
@yishaigalatzer not sure how the file got corrupted. This was on a CI agent. The build log doesn't have anything that indicates download interruption.

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/289.
