### ISSUE TITLE
Nuget backend returns incorrect number of packages

### ISSUE THREAD

**Issue by jianyunt** [NuGet/Home#2134]
Recently, when we use nuget API v2 and ODATA syntax to query the server, we get back the wrong number of packages. Specifically, the URL
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework=''&includePrerelease=false&$skip=320&$top=40 returns 39 packages instead of 40. This used to work before but now it is broken (we are not sure when this happened). Is this a known issue?

**Comment by yishaigalatzer** [comment]
Move to gallery - https://github.com/NuGet/NuGetGallery/issues/2895
