### ISSUE TITLE
Remove V2 machine cache 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2140]
The V2 machine cache is no longer used by nuget. It should be removed where ever it still exists.

Known locations:
- Default source in nuget.exe
- Clear command

**Comment by mishra14** [comment]
Yet to have a design discussion for https://github.com/NuGet/Home/issues/3591. The result will impact this as well.

**Comment by emgarten** [comment]
@mishra14 is this complete?

**Comment by mishra14** [comment]
Locals does not clear V2 cache any more as per:  https://github.com/NuGet/NuGet.Client/commit/6f3ae2d59140f5ea97eb7573535de1c286d6d336

@emgarten: I am not sure about the default source.
