### ISSUE TITLE
Could not load file or assembly 'EntityFramework.MappingAPI, Version=6.0.0.7

### ISSUE THREAD

**Issue by netizenk** [NuGet/Home#2141]
After executing Install-Package EntityFramework.BulkInsert-ef6 it also pulled   EntityFramework.MappingAPI 6.1.0.9  and added bindingRedirect oldVersion="0.0.0.0-6.1.0.9" newVersion="6.1.0.9" to the assembly config file but when BulkInsert() method is executed this Exception is thrown: Could not load file or assembly 'EntityFramework.MappingAPI, Version=6.0.0.7
Why is it still looking for the older version even though the bindingRedirect is in the config file and how do I resolve this issue?

**Comment by yishaigalatzer** [comment]
This seems like a package specific question. Can you please move it to the package owner?
