### ISSUE TITLE
Restore errors don't show resolved dependency, they only show requested dependency

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2142]
First, there was a dependency that was requested but it didn't exist, so an upgrade happened:

**project.json**

``` JSON
{
    "version": "1.0.0-*",

    "dependencies": {
        "Microsoft.Extensions.Logging": "1.0.0-rc1-final-update1",
        "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final"
    },

    "frameworks": {
        "dnx451": { }
    }
}
```

```
warn : Dependency specified was Microsoft.Extensions.Logging (>= 1.0.0-rc1-final-update1) but ended up with Microsoft.Extensions.Logging 1.0.0-rc2-16040.
warn : Dependency specified was Microsoft.Extensions.Logging (>= 1.0.0-rc1-final-update1) but ended up with Microsoft.Extensions.Logging 1.0.0-rc2-16040.
```

Next there was a downgrade detected but the output shows that `Microsoft.Extensions.Logging (>= 1.0.0-rc1-final-update1)` depends on `Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc2-15992)` when infact it's the resolved version from the previous warning  `Microsoft.Extensions.Logging 1.0.0-rc2-16040`

```
warn : Detected package downgrade: Microsoft.Extensions.DependencyInjection.Abstractions from 1.0.0-rc2-15992 to 1.0.0-rc1-final
warn :  foo-lib (>= 1.0.0) -> Microsoft.Extensions.Logging (>= 1.0.0-rc1-final-update1) -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc2-15992)
warn :  foo-lib (>= 1.0.0) -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc1-final)
warn : Detected package downgrade: Microsoft.Extensions.DependencyInjection.Abstractions from 1.0.0-rc2-15992 to 1.0.0-rc1-final
warn :  foo-lib (>= 1.0.0) -> Microsoft.Extensions.Logging (>= 1.0.0-rc1-final-update1) -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc2-15992)
warn :  foo-lib (>= 1.0.0) -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 1.0.0-rc1-final)
```

**Comment by yishaigalatzer** [comment]
@GuardRex : https://github.com/dotnet/cli/issues/1646

A dependency conflict currently displays this information ...

```
<PATH>\project.json(42,30): warning NU1012: Dependency conflict. 
NETStandard.Platform 1.0.0-rc3-23901 expected System.AppContext >= 4.1.0-rc3-23901 but got 
4.1.0-rc3-23829
```

Could this information also state which package (or packages) requested the lower version?

btw- Nit ... "but got" ... perhaps "but received" would be better.

**Comment by davidfowl** [comment]
This is actually a pretty simple fix https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs#L143. We need to decide if we want to show both versions or only resolved versions. 

node.Key - Requested
node.Item.Key - Resolved version (may be null of unresolved)

**Comment by joelverhagen** [comment]
Added a permalink to the commit @davidfowl was talking about:
https://github.com/NuGet/NuGet.Client/blob/fa622dccaa09bfa3a8c94a2c4a0c19032e48aa84/src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs#L143

Restoring the "fooproject" project in this .zip should reproduce this issue.
[restore-warnings.zip](https://github.com/NuGet/Home/files/437724/restore-warnings.zip)
