### ISSUE TITLE
Packages not restoring, but it says restored.

### ISSUE THREAD

**Issue by christophedemey** [NuGet/Home#2143]
Ive created a vsix with a multi project template.
One of these templates has a reference to newtonsoft.json.
When i create the template the nuget console says "Restore packages" in a yellow bar at the top of the command prompt.
When i click it, it loads a bit (progress bar) then just dissapears without errors.
Console does not show output, but my reference is still dead.

Can you please have a look ?
My vsix is downloadable here : http://www.cdmapplications.be/VSIXProject4.zip

The template is located at c# -> MultiWaffle -> MultiProject Waffle project.
Thanks.

**Comment by yishaigalatzer** [comment]
@christophedemey I would start by making sure my projects are all saved, and so is the solution. 
Next to help us be able to quickly figure things out without having to install unknown vsix on our computers, I would appreciate if you can push the created projects into a github repo. This will both save time and be a lot crisper about responsibilities between NuGet and your vsix.

**Comment by yishaigalatzer** [comment]
Also forgot to mention, make sure you are using nuget 3.3 and visual studio Update I

**Comment by yishaigalatzer** [comment]
@christophedemey ping

**Comment by rrelyea** [comment]
CLosing due to lack of response.
