### ISSUE TITLE
UI Client fails to show any error or warning when search is ahead of registration blobs

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2149]
If the search is ahead of the registration blobs (specifically if there are versions of a package in the search results that arn't in the registration blobs) the search UI fails to show an details.

Technically the problem here is that the feed is slightly out of sync. This shouldn't ever happen on nuget.org prod. However, if it did or some other package source did get out of sync the client _should show a warning somewhere_.

Often a slightly older version of the package will unblock what the user is trying to do. And the problem on a server will often just be temporary.

**Comment by rrelyea** [comment]
Closing this old issue, until we see significant customer impact.
