### ISSUE TITLE
NuGet credentials for multiple package sources: always using credentials of first accessed feed

### ISSUE THREAD

**Issue by ygeelen-tb** [NuGet/Home#2151]
See http://stackoverflow.com/questions/35560057/nuget-credentials-for-multiple-package-sources-always-using-credentials-of-firs

Is this a bug in the latest nuget.exe client?

**Comment by yishaigalatzer** [comment]
Can you be specific about what version of the client you are using?

**Comment by ygeelen-tb** [comment]
The VS extension says "NuGet 3.3 for Visual Studio 2015 RTM" and I tested with nuget.exe 3.3.0

**Comment by ygeelen-tb** [comment]
When I specify the package source on the command-line, it seems to work properly:
nuget list -Source http://mycompany.com/nuget/feed1
"Using credentials from config. UserName: Feed1Developer"
nuget list -Source http://mycompany.com/nuget/feed2
"Using credentials from config. UserName: Feed2Developer"

So it seems to be a bug in the Visual Studio extension then?

**Comment by yishaigalatzer** [comment]
I'm guessing it looks like the http client is picking the credentials based on the host name rather than the root feed url in your case.

@emgarten when you work on porting the proxy/auth to XPLAT, can you also verify this scenario?

**Comment by ygeelen-tb** [comment]
I'm experiencing the problem when switching from feed1 to feed2 at the right when browsing for packages (up-to-date Visual Studio 2015):
![image](https://cloud.githubusercontent.com/assets/12393883/13234793/bfcec4e0-d9ba-11e5-94e3-e78e3d35b96a.png)

To be more precise: I'm checking the current user in an HttpModule on my NuGet Server (ASP.NET) using HttpContext.Current.User.Identity.Name in the PostAuthenticateRequest event and it's always the same.

**Comment by ygeelen-tb** [comment]
I have the same problem when checking the Authorization header (Basic HTTP Authentication), it keeps sending the same username in the header. I think this is what nuget.exe uses internally?

**Comment by ygeelen-tb** [comment]
Can you confirm whether it's an issue in the NuGet.exe client?

I will still need to wait until a VS nuget package manager extension update gets published that ships with the patched NuGet.exe version in that case I guess?

**Comment by yishaigalatzer** [comment]
This is a bug in http client

**Comment by ygeelen-tb** [comment]
Ok, which is a dependency of NuGet.exe?
