### ISSUE TITLE
Project to Project references with native libraries stopped working

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#2153]
This project: https://github.com/aspnet/KestrelHttpServer/blob/dev/test/Microsoft.AspNetCore.Server.Kestrel.FunctionalTests/project.json
References this project:
https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Microsoft.AspNetCore.Server.Kestrel/project.json
Which has native libraries inside of it

This used to work but now restore doesn't resolve these native libraries if its a project to project reference. Making it reference a nupkg instead works.

**Comment by yishaigalatzer** [comment]
@BrennanConroy - more info please.

What does not work mean? What version of nuget are you using

**Comment by BrennanConroy** [comment]
CLI version 1496
Native libraries used to show up in the lock file, now they no longer appear
Before, we used CLI version 1290

**Comment by yishaigalatzer** [comment]
@emgarten can you please followup here?

**Comment by emgarten** [comment]
This was working due to a type: build dependency flowing to a parent project, which is not the correct behavior. I'm closing this as by design.
