### ISSUE TITLE
Weird dependency format in project.lock.json file

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2155]
Here's the nuspec

``` XML
<group targetFramework=".NETPlatform5.0">
        <dependency id="Microsoft.Build.Framework" />
        <dependency id="Microsoft.Build" />
        <dependency id="Microsoft.Build.Utilities.Core" />
        <dependency id="Microsoft.Build.Tasks.Core" />
        <dependency id="MSBuild" />
      </group>
```

Here's the lock file.

```
"dependencies": {
          "MSBuild": "(, )",
          "Microsoft.Build": "(, )",
          "Microsoft.Build.Framework": "(, )",
          "Microsoft.Build.Tasks.Core": "(, )",
          "Microsoft.Build.Utilities.Core": "(, )"
        },
```

/cc @emgarten

**Comment by yishaigalatzer** [comment]
The nuspec is not valid, so we should do something about it, but it doesn't seem like a top priority because it doesn't happen in the wild.

I'm pushing this out to the next release

**Comment by emgarten** [comment]
That is the correct format, NuGet writes out the range for all possible versions as `(, )` No min, no max.  The alternative would be to use an empty string or null, but that seems dangerous.

**Comment by davidfowl** [comment]
> That is the correct format, NuGet writes out the range for all possible versions as (, ) No min, no max. The alternative would be to use an empty string or null, but that seems dangerous.

:\
