### ISSUE TITLE
Nuget.exe ExitCode on Warnings

### ISSUE THREAD

**Issue by WernerMairl** [NuGet/Home#2156]
Hi
I'm using a nuget.exe (v.3.3.0) with the following arguments:

INSTALL <packages.config> -source <folder> -NoCache -OutputDirectory <directory>

Basically everything works like expected. 
But one case with remaining questions:
If the specified -source does not contains one of the requested packages i get a warning that the package is not installed - OK

BUT: there is ANY way to get this information (not installed) by using the process exitcode ?
every try on my side ends with a exitcode 0 - not really helpful.

I'm also not be able to find any documentation about Exit/returncodes on the docu
What I'm doing wrong ?

regards
Werner

**Comment by yishaigalatzer** [comment]
Hey Werner,

Thanks for reporting this issue.

Warnings do not affect exit codes, if you want to check for them, you have to splunk the log.

The rule for exit code is non zero when there is an error, there is no more information available through error codes.

One could argue that this should be an error and not a warning.

**Comment by yishaigalatzer** [comment]
@WernerMairl we decided to prefix warnings, so they can easily be found through logs. But warnings will not return a non 0 exit code.

**Comment by yishaigalatzer** [comment]
@joelverhagen can you please look into it, I agree that this should be an error and not a warning

**Comment by WernerMairl** [comment]
Thank you for the quick response!

for long terms, what about one of the following (backward compatible) ideas

a) add a commandline option "-xml" (like subversion) that returns structured information about the warnings/output (severity, source, etc)

b) add a commandline option "-extendedReturncodes" that allows a new/imrpoved exitcode-handling without impacting the old and known behavior

**Comment by yishaigalatzer** [comment]
That sounds like a good idea. I'm not sure we can/will get there in the short term, but definitely something that can be added.

The second one should be fairly easy in a simpler form. E.g. -warnings as errors mode

**Comment by rrelyea** [comment]
In VS 2017 version 15.3 and NuGet 4.3 we added support for Warnings as Errors.
Please see https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings
