### ISSUE TITLE
White installation error

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2159]
_From @d054702741 on February 23, 2016 16:30_

Attempt to install White by the PM, with the following line: "PM> Install-Package TestStack.White"
I've got the following error:

Install-Package : Could not install package 'TestStack.White 0.13.3'. You are trying to install this package into a projec
t that targets '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files tha
t are compatible with that framework. For more information, contact the package author.
At line:1 char:16
- Install-Package <<<<  TestStack.White
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Please advise the way to resolve this problem.

Thanks
Daniel Maor
danielmaor@gmail.com

_Copied from original issue: NuGet/NuGetGallery#2900_

**Comment by yishaigalatzer** [comment]
The packages does not work in 3.5, the error spells it out. You can contact the package owner or upgrade your project to 4.0 +
