### ISSUE TITLE
Dev15 Preview Install EntityFramework 6.1.3, got "The domain manager specified by the host could not be instantiated" during running script.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2162]
Step:
1. Dev15 Preview + NuGet 3.4.0.653
2. Open NuGet UI and install entityframework 6.1.3

Expected: installed well.

Actual:
Executing script file 'c:\Users\lzhi\Documents\Visual Studio vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\install.ps1'...
Exception calling "CreateDomain" with "3" argument(s): "The domain manager specified by the host could not be 
instantiated."
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:743 char:5
-     $domain = [AppDomain]::CreateDomain('EFConfig', $null, $info)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : TypeLoadException

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:744 char:5
-     $domain.SetData('project', $Project)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:747 char:5
-     $domain.SetData('efDispatcher', $dispatcher)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Unload" with "1" argument(s): "Value cannot be null.
Parameter name: domain"
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:795 char:5
-     [AppDomain]::Unload($runner.Domain)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
-     $domain.CreateInstanceFrom(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "CreateDomain" with "3" argument(s): "The domain manager specified by the host could not be 
instantiated."
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:743 char:5
-     $domain = [AppDomain]::CreateDomain('EFConfig', $null, $info)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : TypeLoadException

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:744 char:5
-     $domain.SetData('project', $Project)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:747 char:5
-     $domain.SetData('efDispatcher', $dispatcher)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Exception calling "Unload" with "1" argument(s): "Value cannot be null.
Parameter name: domain"
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:795 char:5
-     [AppDomain]::Unload($runner.Domain)
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentNullException

You cannot call a method on a null-valued expression.
At C:\Users\lzhi\Documents\Visual Studio 
vNext\Projects\ConsoleApplication1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
-     $domain.CreateInstanceFrom(
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully installed 'EntityFramework 6.1.3' to ConsoleApplication1
========== Finished ==========

**Comment by yishaigalatzer** [comment]
@divega - Closing the NuGet issue, please keep tracking with the VS folks, and update here when it is working agin

CC @bricelam
