### ISSUE TITLE
Allow configuration of machine wide location for nuget configuration.

### ISSUE THREAD

**Issue by ellismg** [NuGet/Home#2164]
As I mentioned in #1899, different vendors want to control where NuGet configuration data is loaded from, as the `/etc/opt` may not always be correct.

A concrete example is Red Hat, which wants to package the CLI (and hence nuget) in something they call a Software Collection.  One of the goals of Software Collections is that there's isolation between the packages from the software collection and the rest of the file system.  So ideally, packages in software collections are configured to not configured to read and write from hard coded locations (e.g `/etc/opt`) and instead there's some way of configuring these paths (e.g. a file or environment variable).

https://github.com/NuGet/NuGet.Client/pull/297 is a look at what adding such a feature to NuGet would look like.  I'm not wed to the specific implementation, I'd just like to understand how we can get some flexibility here.

@yishaigalatzer

**Comment by yishaigalatzer** [comment]
@emgarten this is to review and PR from @ellismg

**Comment by emgarten** [comment]
Fixed by @ellismg's PR
NuGet/NuGet.Client@96317b44d96c7213fd475a23b47cade40b2282eb
