### ISSUE TITLE
nuget.exe push needs different URL to nuget.exe list (with Nuget.Server)

### ISSUE THREAD

**Issue by piers7** [NuGet/Home#2165]
When running an internal Nuget.Server, the [docs](https://docs.nuget.org/create/hosting-your-own-nuget-feeds#step-5:-deploy-and-run-your-brand-new-package-feed!) and start page tell you to put a URL in this form into Visual Studio package manager:

> http://yourserver/nuget

This works fine in Visual Studio (2013), and in the command line nuget.exe (3.3.0.212 - ie latest) if you **list** packages:

> nuget.exe list -source http://yourserver/**nuget**

When you come to **push** packages, however, you need to drop the /nuget off the end:

> nuget.exe list -source http://yourserver/

...otherwise you get either 405 Method Not Allowed or 413 Request Entity Too Large (see http://stackoverflow.com/questions/11264902/private-nuget-server-request-entity-too-large/17813278#17813278 and http://stackoverflow.com/a/16453216/26167 )

This means that the nuget server aliases defined in nuget.config can't be used during push operations, which is a pain.

Is this a client bug, or is it actually a Nuget.Server issue?

**Comment by yishaigalatzer** [comment]
This is definitely not a NuGet client issue. @maartenba can you see what it means to change it in the new nuget.server? (basically it would need to allow both URLs as push end point)

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2903
