### ISSUE TITLE
Error message when missing version range does not say which package is missing a package dependency

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2166]
This makes it hard to figure out what to fix.

```
error: Package dependencies must specify a version range.
```

Full log:

https://gist.githubusercontent.com/colemickens/258b15db0fc8ffa41ef2/raw/7d92c6c6d2dc853b5f58f34db02599090ba64a66/gistfile1.txt

**Comment by emgarten** [comment]
This is fixed in the latest build. NuGet/NuGet.Client@0db56afa511667ea8ba1add3309e432a3ed5cf34
