### ISSUE TITLE
Absolute Package paths break nuget push on mono

### ISSUE THREAD

**Issue by andycmaj** [NuGet/Home#2167]
## Problem

Apparently, this is a problem when running nuget on mono (tested with both 2.8.5 and 3.X.X).
Seems to break when passing absolute package paths as arguments.
### :-1: Running Nuget With Absolute Package Path

``` bash
$ mono .tools/nuget.exe push "/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug/ImsHealth.Automation.1.1.2.nupkg"
Directory '/Workspaces/appature/git/ImsHealth.Automation/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug' not found.
```

Notice how it tries to append the absolute path it's given to the current working directory:

> '**/Workspaces/appature/git/ImsHealth.Automation/**Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug' not found.
### :+1: Running Nuget With Relative Package Path

``` bash
$ mono .tools/nuget.exe push "./.artifacts/Debug/ImsHealth.Automation.1.1.2.nupkg"
Pushing ImsHealth.Automation 1.1.2 to the NuGet gallery (https://www.nuget.org)...
```

Great success!
## Environment

``` bash
$ mono -V
Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug
    LLVM:          yes(3.6.0svn-mono-(detached/a173357)
    GC:            sgen
```

``` bash
$ mono .tools/nuget.exe
NuGet Version: 3.3.0.212
```

**Comment by yishaigalatzer** [comment]
@andycmaj we just updated nuget 3.4 push code to work xplat. Can you give it a try?

It is a available on my http://myget.org/gallery/nugetbuild

**Comment by andycmaj** [comment]
I'd be happy to... can you provide quick instructions on which package/executable i should use on osx?

**Comment by andycmaj** [comment]
ah i guess it's NuGet.CommandLine.3.4.0-beta-659.nupkg with nuget.exe

**Comment by andycmaj** [comment]
yeah looks like 3.4 is working great! feel free to close with the 3.4 label or whatever your process

**Comment by andycmaj** [comment]
so question... does nuget 3.4 automatically try to publish any `symbols.nupkg` files it finds to a hard-coded symbol server?
i'm seeing this now:

``` bash
$ tree .artifacts
.artifacts
└── Debug
    ├── ImsHealth.Automation.1.1.5.nupkg
    ├── ImsHealth.Automation.1.1.5.symbols.nupkg
    └── net451
        ├── ImsHealth.Automation.dll
        └── ImsHealth.Automation.xml
```

``` bash
$ mono .tools/nuget.exe push "/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug/ImsHealth.Automation.1.1.5.nupkg" -Source https://imshealth.myget.org/F/internal/api/v2/package
Pushing ImsHealth.Automation.1.1.5.nupkg to 'https://imshealth.myget.org/F/internal/api/v2/package'...
Your package was pushed.
Pushing ImsHealth.Automation.1.1.5.symbols.nupkg to the symbol server (https://nuget.smbsrc.net/)...
400 (Bad Request)
```

**Comment by yishaigalatzer** [comment]
Yes it does and we will eventually change it

**Comment by andycmaj** [comment]
ok is there an existing issue for this?

**Comment by yishaigalatzer** [comment]
Go ahead and open one

**Comment by andycmaj** [comment]
created https://github.com/NuGet/Home/issues/2204. feel free to close this one when 3.4 is released
