### ISSUE TITLE
Write "subtargets" to RID-less graph in Cross-Plat Restore

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2171]
As discussed earlier in person with @emgarten and @yishaigalatzer, in order to support shared-framework apps, we need to encode some additional data into the lock file describing the RID-specific assets within a package. This does not need to affect restore algorithms, just how we build the lock file.

Given a package with the following structure (just a contrived example, not necessarily accurate):

```
System.Data.SqlClient.4.0.0.nupkg/
  ref/
    netstandard1.5/
      System.Data.SqlClient.dll
  runtimes/
    unix/
      lib/
        netstandard1.5/
          System.Data.SqlClient.dll
    win7-x64/
      native/
        sni.dll
      lib/
        netstandard1.5/
          System.Data.SqlClient.dll
    win7-x86/
      native/
        sni.dll
      lib/
        netstandard1.5/
          System.Data.SqlClient.dll
```

The entry within the `targets.[tfm]` property of the `project.lock.json` file should now look as follows:

``` json
{
  "targets": {
    ".NETStandardApp,Version=v1.5": {
      "System.Data.SqlClient/4.0.0": {
        "compile": {
          "ref/netstandard1.5/System.Data.SqlClient.dll": {}
        },
        "subtargets": {
          "runtime": {
            "runtimes/unix/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "unix" },
            "runtimes/win7-x64/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x86" }
          },
          "native": {
            "runtimes/win7-x64/native/sni.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/native/sni.dll": { "rid": "win7-x86" }
          }
        }
      }
    }
  }
}
```

/cc @davidfowl @pakrym @emgarten

@yishaigalatzer This is part of the work we discussed earlier this week, please triage as appropriate.

**Comment by analogrelay** [comment]
My prototype code is in a branch on NuGet.Client. This is the starting point for the changes: https://github.com/NuGet/NuGet.Client/blob/anurse/phat-apps/src/NuGet.Core/NuGet.Commands/LockFileUtils.cs#L176

**Comment by emgarten** [comment]
NuGet/NuGet.Client@81f9ca85119b38b3c5dd21cbde63a561a60b5774
