### ISSUE TITLE
Add RID-fallback data to the lock file

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2172]
For shared framework apps, we need to encode some additional data about the RID-fallback logic into the lock file for RID-less targets. First, we capture concrete RIDs by allowing the use of the `#concrete` value in `runtime.json`. This is an optional property that defaults to `false` and is simply tracked in the runtime graph data model. For example:

``` json
{
    "runtimes": {
        "win7-x64": {
            "#imports": [ "win7", "win-x64" ],
            "#concrete": true
        }
    }
}
```

When generating the lock file, first track all unique RIDs used by "subtargets" (https://github.com/NuGet/Home/issues/2171) in packages in the `usedRids` set. Then, capture all concrete RIDs in the entire Runtime Graph in the `concreteRids` set.

For each `concreteRid` in `concreteRids`, expand the RID into it's full ordered list of possible fallbacks (`ExpandRuntime` in the `RuntimeGraph` class). Remove any RIDs from the list that are not in `usedRids`. Finally, write all pairs of `concreteRid` and expanded, filtered, RIDs to the lock file. **Include empty entries as empty JSON arrays to indicate a RID that is supported by the app but has no fallbacks**.

As an example, see the below potential lock file. Given the expected set of "concrete RIDs" (exact set TBD, but basically it's all RIDs that are distro, os version and arch-specific, i.e. "leaf"(ish) nodes), and the packages and subtargets listed in the lock file, the `runtimes` section at the end of the lock file should be generated. The child nodes of `runtimes` should match all RID-less entries in `targets` and provides the runtime fallback list for **that target only**.

``` json
{
  "targets": {
    ".NETStandardApp,Version=v1.5": {
      "Microsoft.AspNetCore.Server.Kestrel/1.0.0-rc2-12345": {
        "runtime": { "lib/Microsoft.AspNetCore.Server.Kestrel.dll": {} },
        "subtargets": {
          "native": {
            "runtimes/osx/native/libuv.dylib": { "rid": "osx" },
            "runtimes/linux-x64/native/libuv.so": { "rid": "linux-x64" },
            "runtimes/win7-x64/native/libuv.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/native/libuv.dll": { "rid": "win7-x86" }
          }
        }
      },
      "System.Data.SqlClient/4.0.0": {
        "subtargets": {
          "runtime": {
            "runtimes/unix/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "unix" },
            "runtimes/win7-x64/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/lib/netstandard1.5/System.Data.SqlClient.dll": { "rid": "win7-x86" }
          },
          "native": {
            "runtimes/win7-x64/native/sni.dll": { "rid": "win7-x64" },
            "runtimes/win7-x86/native/sni.dll": { "rid": "win7-x86" }
          }
        }
      },
      "Newtonsoft.Json/6.0.2": {
        "runtime": { "lib/netstandard1.5/Newtonsoft.Json.dll": {} }
      }
    }
  },
  "runtimes": {
    ".NETStandardApp,Version=v1.5": {
      "win7-x64": [ ],
      "win7-x86": [ ],
      "win8-x64": [ "win7-x64" ],
      "win8-x86": [ "win7-x86" ],
      "win81-x64": [ "win7-x64" ],
      "win81-x86": [ "win7-x86" ],
      "win10-x64": [ "win7-x64" ],
      "win10-x86": [ "win7-x86" ],
      "osx.10.10-x64": [ "osx", "unix" ],
      "osx.10.11-x64": [ "osx", "unix" ],
      "rhel.7-x64": [ "linux-x64", "unix" ],
      "rhel.7.1-x64": [ "linux-x64", "unix" ],
      "rhel.7.2-x64": [ "linux-x64", "unix" ],
      "rhel.7.3-x64": [ "linux-x64", "unix" ],
      "centos.7-x64": [ "linux-x64", "unix" ],
      "centos.7.1-x64": [ "linux-x64", "unix" ],
      "debian.8-x64": [ "linux-x64", "unix" ],
      "ubuntu.14.04-x64": [ "linux-x64", "unix" ],
      "ubuntu.14.10-x64": [ "linux-x64", "unix" ],
      "ubuntu.15.04-x64": [ "linux-x64", "unix" ],
      "linuxmint.17-x64": [ "linux-x64", "unix" ],
      "linuxmint.17.1-x64": [ "linux-x64", "unix" ],
      "linuxmint.17.2-x64": [ "linux-x64", "unix" ],
      "linuxmint.17.3-x64": [ "linux-x64", "unix" ]
    }
  }
}
```

Note that the RID fallbacks have been drastically reduced from their complete set because we can exclude RIDs for which there is no runtime-specific asset. For example, `win7-x64` should import `win`, `win-x64`, `any` and `base` RIDs but there is no asset in the `.NETStandardApp,Version=v1.5` target for those RIDs so that data is unnecessary. It **is** necessary to ensure order is preserved during this optimization, since RID fallbacks are always ordered.

/cc @davidfowl @pakrym @emgarten 

@yishaigalatzer This is part of the work we discussed earlier this week, please triage as appropriate.

**Comment by emgarten** [comment]
RIDs will not longer be added to the lock file according to the latest plan. //cc @glennc

**Comment by davidfowl** [comment]
@emgarten That's wrong. This is still needed.

**Comment by davidfowl** [comment]
oops, I thought it was the subtargets section. That's still needed
