### ISSUE TITLE
Error message when build my project

### ISSUE THREAD

**Issue by d054702741** [NuGet/Home#2173]
I'm trying to build my project and I've got the following error:

Error   1   Cannot implicitly convert type 'TestStack.White.UIItems.WindowItems.Window' to 'System.Windows.Window'  c:\users\daniel.cbt\documents\visual studio 2013\Projects\I2K-White\I2K-White\MainWindow.xaml.cs    37  33  I2K-White

My program:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.Windows.Automation;
//using NUnit.Framework;

using TestStack.White;
using TestStack.White.Configuration;
using TestStack.White.UIItems;
using TestStack.White.UIItems.Finders;

namespace I2K_White
{
    /// <summary>

    /// Interaction logic for MainWindow.xaml
    /// </summary>

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            TestStack.White.Application app = TestStack.White.Application.Launch("c:\Integris-2000\I2K-GUI.exe");

```
        Window mainWindow = app.GetWindow(TestStack.White.UIItems.Finders.SearchCriteria.ByText("2000 Remote Radio Installation Tester"),
                                          TestStack.White.Factory.InitializeOption.WithCache);
```

Thanks
Daniel Maor

**Comment by yishaigalatzer** [comment]
Hey Daniel,

I think we have a bit of a confusion here. This repo tracks the work to build the NuGet clients rather than the place to discuss individual packages.

Please contact the package owner directly on his page https://www.nuget.org/packages/TestStack.White/ContactOwners , or post a stackoverflow question.
