### ISSUE TITLE
E2E Test InstallPackageMissingPackage fails if 'Microsoft and .NET' curated feed is enabled

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#2174]
E2E Test InstallPackageMissingPackage fails if 'Microsoft Dot Net' curated feed is selected

Repro steps:
1. Enable the machine wide package source 'Microsoft and .NET'
2. Open VS. Open PMC. Import-Module $gitRoot\NuGet.Client\test\EndEnd\NuGet.Tests.psm1
3. Run-Test InstallPackageMissingPackage

(Before doing (1), you could  Open Admin Powershell and Run $gitRoot\NuGet.Client\scripts\e2etests\SetupFunctionalTests.ps1. In which case, you don't need (2)).

Expected:
Test passes.

Actual:

 Failed: Test-InstallPackageMissingPackage. Exception message: Error downloading 'Castle.Core.1.2.0' from 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
A task was canceled.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/298.
