### ISSUE TITLE
VS2015 freezes on startup loading Nuget Packages

### ISSUE THREAD

**Issue by maxcelcat** [NuGet/Home#2175]
Visual Studio 2015 Enterprise is freezing for me when I load a solution with six projects and a fair number of packages. See the attached screenshot of the state VS is stuck in. Eventually I have to kill it from the task manager.

The only work around I have is If I delete the entire contents of the "packages" directory, the solution loads correctly.

I did a debug dump of VS2015 itself while it was hanging, which lead me to believe it was NuGet playing up, and lead me to the work-around of deleting the packages.

Other things to note:
- This same problem afflicts one of my colleagues when he opens the same project in VS2015
- The same project opens just fine in VS2013 every time.
- The project deliberately contains some older versions of some packages. Our code is dependant on specific versions
- I have the latest NuGet installed - 3.3.0.167
- We have our own local NuGet Repository we use as well as Nuget.org
- The project is built against .NET 4.0, because of the limitations of the live environment
- The project has two versions of the same package installed (Microsoft.Owin.Host.SystemWeb.1.0.1 and 3.0.0) for reasons I'm trying to determine.

Any ideas?

[AgendaInstalledPackages.txt](https://github.com/NuGet/Home/files/145942/AgendaInstalledPackages.txt)

![visualstudiofreezeonload](https://cloud.githubusercontent.com/assets/5043277/13309476/3c91732a-dbd1-11e5-804e-d25caaa31e6c.png)

**Comment by yishaigalatzer** [comment]
The interesting thing is that NuGet is not loaded into memory when a solution is loaded and doesn't participate in the process at all. So I would be very interested to find why you think NuGet is part of the issue (of course packages are part of the game because the projects load dlls from them).

One of few things that might load NuGet is if you have the powershell console open, does this repeat if it is closed? If you attach a debugger is nuget.packagemanagement dll loaded in memory?

**Comment by yishaigalatzer** [comment]
@maxcelcat can we get more feedback? 

Also Is there a misbehaving init.ps1 in one of the packages? These run powershell commands that we don't control and can indeed hang visual studio (because they just run arbitrary code)

**Comment by maxcelcat** [comment]
It's possibly NuGet is not at fault, but given the problem occurs when the nuget packages are being loaded, it was my best guess as to the cause. I'll look at the init scripts this week!

**Comment by renagade1** [comment]
I experienced the samme issue, and it looks like nuget tries to invoke init.ps1 on some of the packages. The workaround I have found so far is to delete the .vs folder and restart visual studio. It only happens in VS2015. VS2013 works fine.

**Comment by yishaigalatzer** [comment]
Thomas - what version of the nuget extension are you using?

**Comment by renagade1** [comment]
We are using 3.3.0.167

**Comment by yishaigalatzer** [comment]
Can you identify the package and what is the init.ps1 doing?/

**Comment by renagade1** [comment]
Last time I checked. It was trying to run NServiceBus init.ps1. The script only checks the registry to see if the package has been installed before and if not it displays the welcome to nservicebus in visual studio.

**Comment by renagade1** [comment]
I think I have a dumpfile if your interested

**Comment by maxcelcat** [comment]
I can confirm that deleting the init.ps1 files from all the packages directories fixes the problem. We're using the latest NuGet with a fully patched version of VS2015.

**Comment by yishaigalatzer** [comment]
We would appreciate both the dump file and the specific version of nservicebus you are using.

We need to investigate and see if it is a nuget fault (in how we set up the powershell console) or a change between the 2013 object model to 2015, that causes the hangs.

Thinking out loud, perhaps it is time for adding hang detection for init.ps1 and a feature to turn it off from running (or choosing explicitly which init.ps1 to run/ignore).

**Comment by renagade1** [comment]
Imo: Hang detection wouldn't be a bad thing regardless if its nuget fault or not.
Do you have any contact information where I can send the dump file?

**Comment by GlennJohnson** [comment]
I'm having the same problem.  If I delete the .vs folder, I can load the solution and in Package Manager Console, I see:
Set-DefaultScaffolder : Cannot get an instance of EnvDTE.DTEAt C:\TFS\wtfsapp01
p\HRSupplyChain\Merit\Dev\packages\T4Scaffolding.Core.1.0.0\tools\init.ps1:50 
char:9
-         Set-DefaultScaffolder -Name CustomTemplate -Scaffolder 
  T4Scaffolding.Cus ...

If I exit VS2015, the .vs folder gets recreated, so if I try to reload the solution, it hangs again until I delete the .vs folder.

**Comment by yishaigalatzer** [comment]
I suggest you contact the package owner, the hang is in the package and until we add hang detection you can either remove it, or ask the owner for a fix

**Comment by rrelyea** [comment]
Closing this old issue. If this still repros with VS2017 version 15.4 or later, please let us know.
