### ISSUE TITLE
Consider writing errors to the error stream

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2176]
Ported from: https://github.com/dotnet/cli/issues/1331

We've set up our CI to read any output written to the error stream and format it so that errors get highlighted in the CI's summary and build failure emails. This worked well with `dnu build` \ `dnu pack` \ `dnu restore` since errors generated by these tools were written to standard error.
Unfortunately this is not the case with `dotnet` tools. The `build` and `compile` commands write errors to standard out and color codes them.

![image](https://cloud.githubusercontent.com/assets/174281/12933782/cb5f3b68-cf3e-11e5-9186-7faa8f6c2e22.png)

 `dotnet restore` on the other hand writes errors to standard out but prefixes them with the log level:

```
info :   NotFound https://api.nuget.org/v3-flatcontainer/sfkldsjfkljdklf/index.json 309ms
info :   NotFound https://dotnet.myget.org/F/dotnet-core/api/v3/flatcontainer/sfkldsjfkljdklf/index.json 452ms
error: Unable to resolve sfkldsjfkljdklf (>= 3.3.0-beta) for DNXCore,Version=v5.0.
```

It'd be great if we could get errors written to the error stream. This would mean we wouldn't need any special string parsing to digest these messages.

**Comment by yishaigalatzer** [comment]
We are going to keep the info label, but we should write errors to the error stream.

**Comment by joelverhagen** [comment]
The current plan is to write errors in real-time to stdout and, at the end of execution, write a summary of errors to stderr. The high level plan is detailed here:
https://github.com/NuGet/Home/wiki/Logging-Guidance

**Comment by pranavkm** [comment]
This sounds great.

**Comment by joelverhagen** [comment]
Hey @pranavkm, this change is in the latest dotnet CLI build. Could you take a look and let me know if your needs are met?

**Comment by pranavkm** [comment]
We're on build `1.0.0-beta-002202`. Would this have the change?

**Comment by joelverhagen** [comment]
Yes, it should. `1.0.0-beta-002202` has NuGet build `3.5.0-beta-1123`. Any build greater than or equal to `3.5.0-beta-1086` has the fix.
