### ISSUE TITLE
NuGet restore occasionally outputs "A task was cancelled" during restore of Roslyn.sln

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#2180]
We do ~100s of NuGet restores a day, every couple of days, restores fails our pull request & rolling builds with the following:

`A task was cancelled`
https://github.com/dotnet/roslyn/issues/9159

We've hit this with 3.4.0.645, but have also hit it with other 3.4.0.N builds that we've used in the past.

We've just started using restore even more on every Windows build, which will triple the number of times we will hit this.

Have you seen this before?

**Comment by yishaigalatzer** [comment]
Dup of #2174, doesn't quite look like it, but the root cause is the same. We have a fix in flight

**Comment by davkean** [comment]
Can we reopen this? I've upgraded to the latest build with the fix this was dup'd against and we're still running into this: https://github.com/dotnet/roslyn/issues/9262

//cc @joelverhagen

**Comment by davkean** [comment]
Ah, nevermind - the build was against a branch that doesn't have the new version. My bad.
