### ISSUE TITLE
NuGet.Common uses very old CoreFx packages

### ISSUE THREAD

**Issue by bartonjs** [NuGet/Home#2181]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/project.json

```
            "dependencies": {
                "System.Runtime.InteropServices.RuntimeInformation": "4.0.0-beta-23225",
                "System.Collections": "4.0.0-beta-23109",
                "System.IO.Compression": "4.0.0-beta-23109",
                "System.IO.FileSystem": "4.0.0-beta-23109",
                "System.IO.FileSystem.Primitives": "4.0.0-beta-23109",
                "System.Runtime.Extensions": "4.0.10-beta-23109",
                "System.Threading": "4.0.10-beta-23109",
                "System.Threading.Thread": "4.0.0-beta-23109",
              "System.Security.Cryptography.Cng": "4.0.0-beta-23516",
              "System.Diagnostics.Process": "4.0.0-beta-23109"
            }
```

The 23109 packages were built more than 7 months ago at this point.  In particular, these references lead to inconsistent type graphs for users because they are pulling in packages that have been deleted and/or refactored.

```
NuGet.Common -->
System.Diagnostics.Process 4.0.0-beta-23109 -->
System.Security.SecureString 4.0.0-beta-23109 (was deleted after 23409) -->
System.Security.Cryptography.Encryption 4.0.0-beta-23109 (was deleted after 23225)
```

Everything in System.Security.Cryptography.Encryption was moved to System.Security.Cryptography.Primitives in 23225, so the NuGet.Common project itself is bringing down two competing definitions of `System.Security.Cryptography.ICryptoTransform` (S.S.C.Encryption via old System.Diagnostics.Process; S.S.C.Primitives via less-old S.S.C.Cng).

**Comment by yishaigalatzer** [comment]
Duplicate, we are working on moving to .NetStandard and it should move up this week or early next week.

CC @emgarten
