### ISSUE TITLE
PackageUpdateResource Push should allow for a Stream input

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#2182]
PackageUpdateResource.Push currently takes in a "packagePath" parameter. It should also have an overload for a stream for the cases where consumers have the package already in memory.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/Resources/PackageUpdateResource.cs#L39

My current scenario is that I am downloading a package from one feed and pushing it to another. I have a `DownloadResourceResult` that has a PackageStream property. I should be able to just pass in PackageStream to Push, instead of having to write it out to a file.

**Comment by yishaigalatzer** [comment]
Really sorry, but we are not making NuGet3 a general purpose library. You can save it to disk and read it from disk.
