### ISSUE TITLE
Suppress downgrade warnings for project references

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2186]
Projects are allowed to omit the version property, but when using this a warning is displayed.

```
WARNING: Detected package downgrade: NuGet.Versioning from 0.0.0 to 3.4.0--
 NuGet.Commands.FuncTest (>= 3.4.0) -> NuGet.Commands (>= 3.4.0) -> NuGet.Client (>= 3.4.0) -> NuGet.Packaging (>= 3.4.0
) -> NuGet.Packaging.Core (>= 3.4.0) -> NuGet.Packaging.Core.Types  -> NuGet.Frameworks  -> NuGet.Versioning
 NuGet.Commands.FuncTest (>= 3.4.0) -> NuGet.Commands (>= 3.4.0) -> NuGet.Client (>= 3.4.0) -> NuGet.Versioning (>= 3.4.
0)
```

**Comment by emgarten** [comment]
NuGet/NuGet.Client@805f0769b0dd01d6dc40d21f0558d72d7ff978d0

**Comment by f0rt** [comment]
I'm not sure if this is already resolved but I'm still getting the warnings on version 3.4.4.1321. I'm using "*" for package versions and I get these warnings.

**Comment by emgarten** [comment]
@f0rt reference your projects using target instead of version. Take a look at the nuget repo for an example: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/project.json#L29-L31
