### ISSUE TITLE
Docs inconsistent on resolving multiple config files

### ISSUE THREAD

**Issue by piers7** [NuGet/Home#2188]
I'm pretty confused about how the multiple-configuration file resolution happens, and the docs don't seem to help.

Within the [Nuget Configuration File](https://docs.nuget.org/consume/nuget-config-file) page there appear to be two different, conflicting accounts of how this work.

The '[chaining multiple configuration files](https://docs.nuget.org/consume/nuget-config-file#chaining-multiple-configuration-files)' section describes a scenario where nuget.config files are loaded from **furthest-away-to-closest**, and (without being particularly explicit about it) implies that configs are merged using a last-in-best-dressed approach. The example bears this out (though it's not very easy to follow).

> NuGet first loads NuGet.config from the default location, then loads any file named NuGet.config starting from the root of the current drive and ending in the current directory.

This is immediately followed by the '[Nuget Config Extensibility Point](https://docs.nuget.org/consume/nuget-config-file#nuget-config-extensibility-point)' section, which describes exactly the opposite order for loading files - from **closest to furthest away**. If one reads this assuming last-in-best-dressed, this implies exactly the opposite from the section above. That being said, there's nothing actually in that section that describes precedence, so it could actually mean anything.

> NuGet config files are read in the following order, assuming the solution directory is c:\a\b\c:
> c:\a\b\c.nuget\nuget.config
> c:\a\b\c\nuget.config
> c:\a\b\nuget.config
> ...

Both of these sections make the mistake of talking about the _order that files are loaded_ (implementation) rather than the _precedence with which they are applied_, which is the bit anyone actually cares about. It'd be useful to mention the intent as well.

I assume what's actually happening is:
- The intent is to allow hierarchical configuration of nuget settings, allowing widely-targeted settings to always be overridden on a project by project basis as required
- Multiple nuget configuration files are applied to the runtime configuration in order of least-specific to most-specific (furthest away to closest)
- Configurations that are applied later augment (or in some cases replace) what came before

... but I feel I've had to infer that from the docs + behavior + thinking about what makes sense, rather than it just being clearly spelt out.

**Comment by yishaigalatzer** [comment]
Thanks for the feedback, I made changes to make it clearer. As FYI - you can always just submit a pull request to any document you have a comment above, there is a link on the bottom of each page to the github repo/markdown file the document is in
