### ISSUE TITLE
Flags in project.json dependency edge should support JSON arrays

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2190]
Right now you can add flags to dependency edges to manipulate the inclusion or exclusion of specific package assets:

``` JSON
"dependencies": {
        "Microsoft.NetCoreApp": {
            "version": "1.0.0",
            "exclude": "runtime, native"
        }
    }
```

However, JSON arrays don't work:

``` JSON
"dependencies": {
        "Microsoft.NetCoreApp": {
            "version": "1.0.0",
            "exclude": ["runtime", "native"]
        }
    },
```

They should.

/cc @emgarten

**Comment by emgarten** [comment]
I believe the type property was using commas so this was done to match. Allowing arrays also would be great :+1:
