### ISSUE TITLE
Update dependencies of nuget.packaging and nuget.configuration

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#2191]
While looking at the dependencies of dotnet cli I noticed we have some references to System.Security.Cryptography.Hashing and Hashing.Algorithms, which no longer exist in the latest dev builds. 

https://github.com/NuGet/NuGet.Client/blob/b63fcac8388496f9ec88cb49bb747dab097653a4/src/NuGet.Core/NuGet.Packaging/project.json#L40
https://github.com/NuGet/NuGet.Client/blob/b63fcac8388496f9ec88cb49bb747dab097653a4/src/NuGet.Core/NuGet.Configuration/project.json#L50

We need to update these dependencies to use System.Security.Cryptography.Algorithms before we ship RC2 of dotnet cli.

**Comment by weshaggard** [comment]
@yishaigalatzer Is this something you guys will be taking care of in upcoming dependency update for CLI?

**Comment by yishaigalatzer** [comment]
I guess we will find out soon enough. Can you explain the changes?

**Comment by weshaggard** [comment]
cc @bartonjs 

We essentially changed the factoring of the Crypto libraries since you guys took that dependency. The primary one to depend on now is System.Security.Cryptography.Algorithms. Which should get you the hashing if that is all you guys are using.

**Comment by bartonjs** [comment]
The full data is available in the commit description of https://github.com/dotnet/corefx/commit/ce0506baea623efdb74707aee0e4aa169d6f468c.

Highlights:

```
System.Security.Cryptography.Encryption            => System.Security.Cryptography.Primitives
System.Security.Cryptography.Hashing               => System.Security.Cryptography.Primitives

System.Security.Cryptography.RandomNumberGenerator => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Encryption.Aes        => System.Security.Cryptography.Algorithms
System.Security.Cryptography.Hashing.Algorithms    => System.Security.Cryptography.Algorithms
System.Security.Cryptography.DeriveBytes           => System.Security.Cryptography.Algorithms

The only partitioned library was System.Security.Cryptography.RSA:
  The RSA base class and supporting types                            => System.Security.Cryptography.Algorithms
  The RSACryptoServiceProvider class and additional supporting types => System.Security.Cryptography.Csp
  The internal RSAOpenSsl type was made public                       => System.Security.Cryptography.OpenSsl
  RSACng was copied from desktop                                     => System.Security.Cryptography.Cng
```

**Comment by yishaigalatzer** [comment]
Thanks

**Comment by emgarten** [comment]
These have been updated

NuGet/NuGet.Client@883764388f7e11f4ad4e4c87b3392d61ed141b9d
NuGet/NuGet.Client@6e99ad12d0bf14a9e52111c784c5718aedca497d

**Comment by eerhardt** [comment]
I don't think this is fully fixed.  I still see a reference to Hashing.Algorithms here:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/project.json#L44
