### ISSUE TITLE
Authentication issues in ASP.NET 5 projects

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2194]
_From @vvatkov on February 26, 2016 14:53_

Hi guys,

We have hosted the NuGetGallery V2 with basic authentication in a public feed. Our authentication however does not work in ASP.NET 5 projects. It seems that we receive some requests with UserAgent "Microsoft_.NET_Development_Utility/1.0.0-rc1-16202(Windows6.3)" without Authorization header even though we response with WWW-Authenticate header. Is this a known issue?

Regards,
Veselin Ivanov
Telerik Team

_Copied from original issue: NuGet/NuGetGallery#2907_

**Comment by yishaigalatzer** [comment]
RC1 bits are not owned by NuGet, I'm not sure who generates it.

Moving forward we have a common codebase for authentication with NuGet, so this shouldn't be an issue in NuGet going forward in RC2,

**Comment by yishaigalatzer** [comment]
Shared internally with folks that own DNU, to see if it is known or not. Either way it will not get fixed there.
