### ISSUE TITLE
Add a way to control the user agent on nuget.exe

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2200]
We want systems that run internally and run tests against nuget.org to send a test user-agent header

**Comment by yishaigalatzer** [comment]
We want to enable folks like .NET team that run heavy internal tests and CIs not to affect download counts in NuGet.org, we have made a change like that in our tests, but this is about being able to do it as a consumer.

@xavierdecoster since you did it before can you come up with a design for this? In short
1. I'd like this to not be a very prominent feature
2. I'd like to be able to do it per build and not per machine

CC @petermarcu

**Comment by xavierdecoster** [comment]
We already have support in nuget.exe that allows running in _test mode_. This will internally set the nuget.exe user agent string to the hardcoded value: _NuGet Test Client_. 
Simply set the env var `NuGetTestModeEnabled=true` to enable this behavior. This can easily be constrained to a script-scoped environment variable.

Related PR that introduced the above support: https://github.com/NuGet/NuGet.Client/pull/135

Reason for this approach: each additional new user agent string we need to support or ignore requires an update to the cdn stats parsing jobs and stored procedures in the stats db. The _NuGet Test Client_ is ignored in stats.

Wouldn't that already help you reach the goal of _not counting towards stats_? It's also a not very prominent feature :)

**Comment by yishaigalatzer** [comment]
Yes! Perfect
