### ISSUE TITLE
Recent NuGet.exe builds can't push to VSTS feeds

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2202]
When I try to push to an (authed) VSTS feed using NuGet.exe 3.4.0.665, the server returns a 400 error with a message:

> Expected a single 'application/octet-stream' part named 'package'.

In earlier NuGet.exe versions (334, 531) the form data sent was:

> Content-Disposition: form-data; name="package"; filename="package"
> Content-Type: application/octet-stream

Now (665) it's:

> Content-Type: application/octet-stream
> Content-Disposition: form-data; name=package; filename=package.nupkg; filename*=utf-8''package.nupkg

I was able to modify a NuGet 655 PUT in Fiddler to match the earlier request and it went through. It seems that:
- The name and filename need to be in quotes.
- The filename must be "package", not "package.nupkg".
- The utf-8 section cannot be present (or I don't know how to quote it right).

Here's where the value is set: https://github.com/NuGet/NuGet.Client/blob/d899f4b258b60/src/NuGet.Core/NuGet.Protocol.Core.v3/Resources/PackageUpdateResource.cs#L272

If these changes were needed to make some other feed work, maybe VSTS needs to fix this on the feed side. (I can't use the earlier versions as a workaround because they aren't compatible with the specific packages I'm pushing.)

Thanks for the help tracking this down, @emgarten!

/cc @weshaggard

**Comment by weshaggard** [comment]
@emgarten @yishaigalatzer can you guys confirm if this is a nuget bug or is this something we need to push on the VSTS folks on?

**Comment by emgarten** [comment]
@weshaggard it's a nuget issue, the push format should not have changed.

**Comment by emgarten** [comment]
@yugangw-msft any ideas on this?

**Comment by yishaigalatzer** [comment]
Actually I think that VSTS should be able to work with this, it looks like a valid change to me. It works both on myget.org and NuGet, and we are now using the standard way to create a multi-part request.

**Comment by yishaigalatzer** [comment]
We decided that VSTS is going to fix their server, rather than NuGet changing back.
