### ISSUE TITLE
Allowed versions attribute is incorrectly working when Dependency behavior is 'Ignore dependencies'

### ISSUE THREAD

**Issue by sponkrashin** [NuGet/Home#2206]
Visual Studio 2015 is used. I update package with allowedVersions="[1.0,1.1)" attribute from NuGet Package Manager. Current version of package is 1.0.72, available versions are 1.0.73 and 1.1.1.

Firstly, I can see that version "1.1.1" is available for update, which is not satisfy condition. But moreover, if I use Dependency behavior: "Ignore dependencies", nuget will update package to this version despite of constraint without any message.

**Comment by yishaigalatzer** [comment]
Duplicate of https://github.com/NuGet/Home/issues/1094.
