### ISSUE TITLE
Enable preview or file count/list on Nuget installation

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2207]
Steps to reproduce:
1. Create new basic web site
2. right click project and select Manage nugget packages
3. Search for AngularJS
4. Install the most obvious result: AngularJS
5. Wait while hundreds of files are downloaded and added to your project

**Suggestion:**

Give a file count or list or potentially a preview of what it will do to your project

This is only an example some ASP.NET packages have a bunch of dependencies, download way more things and take longer. with dependencies, its even harder to "undo".

**Comment by rrelyea** [comment]
Closing as we've not heard much demand for this kind of thing.
