### ISSUE TITLE
Localization Context Needed

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2209]
In the sentence below there is no comment about the placeholder. Without this info, translation will be more difficult. Can you please add comment to this string about possible values of {0} and {1}? 

https://github.com/NuGet/NuGet.Client/blob/960426fa423e9ba09d24758d109ae21bc9d2c168/src/NuGet.Core/NuGet.Packaging/Strings.resx#L135 

https://github.com/NuGet/NuGet.Client/blob/fd39c40935a40e332b4895bff975ff6965ed3638/src/NuGet.Core/NuGet.Commands/Strings.resx#L132

**Comment by csharpfritz** [comment]
Please also verify:  

https://github.com/NuGet/NuGet.Client/blob/0eecd479f51f5fb5a90e44fef424d7efc1e7fc64/src/NuGet.Clients/VsExtension/Resources.resx#L132

**Comment by csharpfritz** [comment]
Another to update:  https://github.com/NuGet/NuGet.Client/blob/d899f4b258b609f947bab6d5de5b38c530abbcfd/src/NuGet.Core/NuGet.PackageManagement/Strings.resx  for 

Rule Message No contexts exist in comments for placeholders, match: {0};{1}; 
LSPKG Filename 14_ploc_nuget.packagemanagement.resources.dll.lcg 
Resource File nuget.packagemanagement.resources.dll.lcg 
Resource ID 0; "Warning_ErrorFindingRepository"

**Comment by rrelyea** [comment]
@mishra14  - not critical, but likely goodness to improve our comments on these kind of things...and suggest to team how to best do it. backlog p2.
