### ISSUE TITLE
UI Needs "Upgrade NuGet" button when client version does not meet requirements

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2212]
If the package has a minClientVersion set that the current NuGet extension in use does not satisfy, then an "Upgrade NuGet" button should be displayed that will trigger a download of the latest extension version

**Comment by yishaigalatzer** [comment]
Going forward NuGet is no longer an extension, and all of visual studio needs to update. I don't think it is quite appropriate for NuGet to send you there.

However we should come up with an update to this UI in VS15, so things make sense when the message comes up

**Comment by yishaigalatzer** [comment]
CC @harikmenon

**Comment by harikmenon** [comment]
@karann-msft

**Comment by karann-msft** [comment]
Assigning to @rrelyea for triage.

cc: @anangaur

**Comment by anangaur** [comment]
@karann-msft,
 NuGet vsix no longer needs update separately. VS upgrade is the only way. I.e. VS 2017 onwards. So I am guessing this should be won't fix for VS 2015.

**Comment by rrelyea** [comment]
agreed. Won't fix, due to shifting update strategies.
