### ISSUE TITLE
Improvements for uninstall in scenarios where restore doesn't work

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2213]
Here is a scenario - A package that is installed in a project is no longer available on the server or locally. A user still want to uninstall it (or any other package):
### How to repro locally
1. Edit your packages.config to a non-existent version of a package 
2. Try to update it or uninstall it from the GUI or PS console - should fail 
3. Try to install another package from the GUI or PS - should fail 
### What could we do
1. If you pass a -Force flag to uninstall, allow for removing the package from package.config
2. Explain that the package has to be removed from packages.config and anything it changed in the project has to be removed manually.
### What other scenarios
1. If we are in the project.json world, you can totally uninstall a package without restoring, so we should relax our requirement to restore there.

**Comment by rrelyea** [comment]
This already works well in PackageReference. 
We aren't planning to fix this in Packages.Config world.
The answer is to move the ecosystem to PackageReference, which we are actively investing in.
