### ISSUE TITLE
Updating packages deletes packages.config in TFS (VS2015)

### ISSUE THREAD

**Issue by ddrinka** [NuGet/Home#2215]
This issue corresponds to Issue #491 which is VS2013-sepcific but has re-emerged in VS2015 Update 1.

I have a solution with many projects dependent on a single NuGet package.  If I run an update on that NuGet package from the Visual Studio GUI, the update succeeds, but for any projects that included only that NuGet package, the packages.config is marked as deleted in the changeset.

I am running VS2015 Enterprise 14.0.24720.00 (Update 1), with NuGet 3.3.0 installed.

We are utilizing visualstudio.com for our TFS server.

I have SSD disks on a brand new install of Windows 10.

I did not have this issue with the same solution on the same TFS tree before upgrading.  My previous (working) configuration was VS2015 RTM, Windows Server 2012R2.

**Comment by ddrinka** [comment]
@zhili1208 See this issue, as requested by @yishaigalatzer in Issue #491.

**Comment by yishaigalatzer** [comment]
@zhili1208 can you please validate if this issue was fixed in 3.4 RTM? If not please move to 3.5

**Comment by ddrinka** [comment]
This issue was blocking development for our team.  For any others watching, our workaround was to move to project.json package configuration.  This move brought many additional wins, and I would recommend it to anyone having trouble with the legacy packages.config style.

**Comment by skofman1** [comment]
Verified the fix on 3.4 RTM. Works great.

**Comment by stgit123** [comment]
This is happening to us consistently and often. 
VS2015 Update 3 14.0.25422.01
Package Manager Console Host Version 3.4.4.1321
