### ISSUE TITLE
Nuget 3.4.0.675 PackageSaveMode doesn’t save nuspec when specified

### ISSUE THREAD

**Issue by stvfks** [NuGet/Home#2218]
Repro:

```
1.  MD %TEMP%\Nuget34 and populate with the following

    Package.Config
    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="EntityFramework" version="6.1.2" targetFramework="net45" />
    </packages>

    Nuget.Config (V3)
    <?xml version="1.0" encoding="utf-8"?>
    <configuration >
      <packageSources>
        <clear />
         <add key="NugetOrg" value="https://api.nuget.org/v3/index.json" /> 
       </packageSources>
    </configuration>

    Nuget 3.4.0.675

1.  CD %TEMP%\Nuget34
2.  Execute: NuGet.exe install packages.config -OutputDirectory %TEMP%\NugetPackages34 -PackageSaveMode nuspec;nupkg

3.  Result
    Dir %TEMP%\NugetPackages34\EntityFramework.6.1.2 /b
        content
        EntityFramework.6.1.2.nupkg
        lib
        tools

    Missing: EntityFramework.6.1.2.nuspec
```

Possibly related change: Related change: https://github.com/NuGet/NuGet.Client/pull/179

**Comment by yishaigalatzer** [comment]
@stvfks if you want everything, just run the normal install operation.

**Comment by deepakaravindr** [comment]
@stvfks @yishaigalatzer 

I found that PackageSaveMode setting does not work for `nuget.exe install <packages.config>` either.
However, it  works properly for  `nuget.exe install <packageId>`

Based on looking at the code, it looks the PackageSaveMode setting is not passed down at
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L190

It should be similar or better yet code should be refactored a little bit to use
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/InstallCommand.cs#L263

**Comment by yishaigalatzer** [comment]
Deepak - does restore works correctly?

**Comment by deepakaravindr** [comment]
@yishaigalatzer, Yes, it does.. Same scenario, if the user used executed
`NuGet.exe restore packages.config -OutputDirectory %TEMP%\NugetPackages34 -PackageSaveMode nuspec;nupkg`, things are fine.

Only `nuget.exe install <packages.config>` does not work with PackageSaveMode

**Comment by yishaigalatzer** [comment]
@stvfks does this unblock you?

**Comment by stvfks** [comment]
I'll give the restore option a try

**Comment by stvfks** [comment]
Reopening accidently closed

**Comment by rrelyea** [comment]
Not going to invest in nuget.exe install for this scenario as our backlog is way too large, and we need to make appropriate choices.
