### ISSUE TITLE
When uninstalling NuGet without selecting "Remove dependencies" no errors will show up in error window

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2219]
The Error List Window shows 0 errors out of 1. 

Output window has an actual error:

Attempting to gather dependencies information for package 'Microsoft.ApplicationInsights.1.0.0' with respect to project 'CurrentSprint', targeting 'WindowsPhone,Version=v8.0'

Resolving actions to uninstall package 'Microsoft.ApplicationInsights.1.0.0'

Unable to uninstall 'Microsoft.ApplicationInsights.1.0.0' because 'Microsoft.ApplicationInsights.PersistenceChannel.1.0.0, Microsoft.ApplicationInsights.WindowsApps.1.0.0' depend on it.

========== Finished ==========

**Comment by rrelyea** [comment]
Not enough actionable detail. Closing as won't fix.
