### ISSUE TITLE
"NuGet.exe list" doesn't use basic auth from configfile

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2220]
Using NuGet.exe 3.4.0.677 with an authed VSTS feed, this is the command and output:

```
nuget list -s VSTSSource -configfile C:\...\NuGet.Config -noninteractive
```

> The remote server returned an error: (401) Unauthorized.

The NuGet.Config is like the following:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="VSTSSource" value="https://.../DotNet-Cache/nuget/v3/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <VSTSSource>
      <add key="Username" value="dagood" />
      <add key="Password" value="..." />
    </VSTSSource>
  </packageSourceCredentials>
</configuration>
```

This config works for pushing but not `list`. Interestingly the list command uses a v2 url:

```
https://.../...f991bb99e4f5/nuget/v2/
```

The last NuGet.exe version that I've tried that supports listing from VSTS is 3.4.0.531. For now, my workaround is to use that version for listing.

/cc @weshaggard @ericstj (Another auto-publishing to VSTS issue, but this one has an easy workaround.)

**Comment by dagood** [comment]
/cc @emgarten 

The workaround appears to be working stably but it would be good not to have to worry about being blocked by this in the future.

**Comment by emgarten** [comment]
NuGet needs a way to _list_ from a v3 feed. Going to v2 for v3 to find all packages is a work around itself.

**Comment by dagood** [comment]
True. It would be good if the v2 workaround still worked until that is implemented though.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/2869. 

That one is newer but it has more customer engagement.
