### ISSUE TITLE
All-sources feature implementation doesn't follow code conventions

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2221]
As mentioned in comments to [the original PR](https://github.com/NuGet/NuGet.Client/pull/264):
- All async methods should accept cancellation token as parameter.
- Pass ILogger everywhere.
- Each class in its own file.
- Use existing exception utilities for flattening aggregated exceptions

**Comment by rrelyea** [comment]
Let this be a reminder...we never get back to things. Block the PR until code is acceptable.
