### ISSUE TITLE
problem upgrading js packages in an asp.net application

### ISSUE THREAD

**Issue by lucamorelli** [NuGet/Home#2224]
Hi,
 I've just started working to the application of a customer of mine and I would like to add a few angular packages, like angular Ui bootstrap, but I'm having a few issues. When I try to updated jquery from 2.1.4 to 2.2.1 or add Angular UI Bootstrap inside Visual Studio I receive errors like this:

```
Attempting to gather dependencies information for package 'Angular.UI.Bootstrap.1.1.2' with respect to project 'Portale', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'Angular.UI.Bootstrap.1.1.2' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Microsoft.AspNet.Razor 2.0.20710' is not compatible with 'Microsoft.AspNet.Mvc 4.0.40804 constraint: Microsoft.AspNet.Razor (≥ 2.0.20710)', 'Microsoft.AspNet.Razor.it 3.2.3 constraint: Microsoft.AspNet.Razor (= 3.2.3)', 'Microsoft.AspNet.WebPages 2.0.30506 constraint: Microsoft.AspNet.Razor (≥ 2.0.20710)'.

```

I know that the mvc runtime packages are a bit out of date, but actually when can't update them since this implies to update several installations.

This time I solved Ignoring the dependencies and forcing installation, but I would like to solve this problem since I don't understand why nuget prevents me from installing a package that is not dependent from the server packages

**Comment by yishaigalatzer** [comment]
@lucamorelli can it be that your project is inconsistent at the moment (rather than out of date?)

The error hints that you might have mismatched dependencies installed like razor 2 & razor 3 loc packages together.

Also can you share the version of NuGet you are using?

**Comment by lucamorelli** [comment]
vs nuget tooling is the latest, the nuget.exe version inside the solution is 2.1.0

**Comment by rrelyea** [comment]
if this is still an issue with the latest NuGet.exe (4.4.1) and or VS 2017 (15.4) -- and it is majorly impacting you, please give us updated data.
