### ISSUE TITLE
When you have no enabled sources Browse tab should be always clear.

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2227]
When you have no enabled sources Browse tab should be always clear.

Using 3.4. If you click on "Installed" tab. Disable all your sources. The screen refreshes and you loose things like the version list. But now tab back to the "Browse" and you see the packages you have installed. The client should have cleared the content of the view.

**Comment by rrelyea** [comment]
closing. If we have customer reports of this issue, we'll consider.
