### ISSUE TITLE
Nuget auto-restore should fix up broken references in project file

### ISSUE THREAD

**Issue by ryanackley** [NuGet/Home#2230]
A very common situation is when you have a nuget managed reference like this in your project file.

```
<Reference Include="ACHeck21.Cloud.Common, Version=1.0.0.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\..\..\Downloads\BatchFileParsers\BatchFileParsers\packages\ACHeck21.Cloud.Common.1.0.0-CI00021\lib\net452\ACHeck21.Cloud.Common.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

If for some reason, this hintpath is broken, you currently have to fix it by hand. It seems like auto-restore should do this.

**Comment by yishaigalatzer** [comment]
Restore is not a step that will ever touch the project, it is designed to just download the packages and NEVER touch the project files.

We have built a whole new experience in NuGet 3 using project.json (+csproj) that eliminated the need for HintPaths, or for that matter any changes to your project. Consider moving your project over to this model going forward.

Practically if you can do it by calling update-package -reinstall in visual studio.

**Comment by ryanackley** [comment]
Fair enough but I really don't understand  what makes the project file holy ground considering Nuget is the thing that put those references in there in the first place. I can't find any way to make it fix these broken references even via command line. 

Am I mistaken that Nuget is a dependency manager? Or is it really just a tool to assist you in finding libraries to add to your project?

It's frustrating to come from Java/Javascript land where you have maven and npm managing dependencies consistently and transparently.

**Comment by yishaigalatzer** [comment]
1. The project file is not holy ground, but nuget really adds stuff to it through the project system API (add reference) and steps back, it doesn't truly understand the project format, which is how things work in multiple project types. So it can't attempt to fix stuff it doesn't understand, and restore is not the right time for it.
2. The suggestion is to use project.json model, which does exactly what you expect it to do. It never touches your project, it instead writes down a lock file that then the project system picks up. So if you move stuff around things work beautifully. 
3. The command update-package -reinstall is the step to update your project when things have dramatically changed. What it does it remove all the references from the project (by calling the API to uninstall), and then adds them again. 

Are you on Visual Studio 2015? Is so take a look at how we build nuget here: https://github.com/nuget/nuget.client where we embrace this model. Will be glad to help with more guidance to get you on the right path

Here is an intro http://docs.nuget.org/consume/ProjectJson-Intro
