### ISSUE TITLE
Remove `--runtime` option from cross-plat restore

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2231]
We are removing the ability to restore and publish for arbitrary RIDs. For RTM, we want to remove the `--runtime` switch from `dotnet restore` in order to ensure that the runtimes a project supports must always be provided in the project.json file.

Please note: We do not want to do this right away, we want to co-ordinate this with getting the portable app publishing working. The reason is: We don't currently specify `runtimes` in dotnet-cli and ASP.NET Core, but since we don't have portable app deployment working fully yet, we need to continue deploying these the old way (standalone). Until we have everything transitioned, we are using explicit `--runtime` switches to ensure we get the same behavior as RID inference gave us, so removing them right away would mess things up :).

Once dotnet/cli#1561, dotnet/cli#1562 and the matching host changes are in, we can make this change.

/cc @blackdwarf @yishaigalatzer @emgarten @davidfowl

**Comment by emgarten** [comment]
NuGet/NuGet.Client@6bcdbc51aa07f4984b127286c778288fb59a9bb0
