### ISSUE TITLE
E2E test SimpleBindingRedirectsNonWeb fails on VS 2015 Update 2 RC

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#2235]
E2E test SimpleBindingRedirectsNonWeb fails on 
VS 2015 Update 2 RC 25025.00 and NuGet 3.4.0.682.

This is a new failure upon upgrading to new VS. It was run thrice from the CI on 2 different agents. And, once manually on the agent. Failed all 4 times. Seems consistent.

Repro steps:
1. Build NuGet.Client solution on your machine
2. Open VS. Open PMC. Import-Module $gitRoot\NuGet.Client\test\EndEnd\NuGet.Tests.psm1
3. Run-Test SimpleBindingRedirectsNonWeb

(Before doing (1), you could Open Admin Powershell and Run $gitRoot\NuGet.Client\scripts\e2etests\SetupFunctionalTests.ps1. In which case, you don't need (2)).

Expected:
Test passes.

Actual:
 Failed: Test-SimpleBindingRedirectsNonWeb. Exception message: Value is null. At install.ps1: line 768

**Comment by yishaigalatzer** [comment]
Can you please investigate?

**Comment by deepakaravindr** [comment]
Upon investigation, I found that this is a regression in References3 interface w.r.t WPF application. 

For WPF application only, At https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/Utility/EnvDTEProjectUtility.cs#L1059, we check for reference3.Resolved and reference3.CopyLocal properties.

In VS 2015 Update 1, the aforementioned properties return true and binding redirects could be determined and added for WPF applications.

In VS 2015 Update 2, the aforementioned properties return false and binding redirects could not be determined and could not be added for WPF applications.

Just for reference, since Aug 2015, the aforementioned properties have been in use:
https://github.com/NuGet/NuGet.Client/commit/98acbf4ae5856ea7fdec5078ae2cef9070a01016

**Comment by deepakaravindr** [comment]
@drewgil 

I am not able to repro this issue when running the scenario manually. I have tried the scenario multiple times on WPF application manually. However, it happens consistently when running the E2E test.

Note that our E2E test tries to create a net45-client profile based WPF application. I don't think it is possible to create a project like that using Create->NewProject dialog in VS 2013 or VS 2015.
I may be wrong.

It would be useful to understand why this, arguably unusual target framework, worked in Update 1 and does not work in Update 2 RC.

**Comment by drewgillies** [comment]
The interesting thing is that our WPF template sets the target profile to Client if the .NET framework target version is >=4.0 (https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/ProjectTemplates/WPFApplication.zip/WPFApplication.csproj#L14), which makes no sense--client profiles ceased after 4.0. In the case of this test, we're creating a WPF project targeting 4.5. So, I'll change it to only set the profile to Client when the version == 4.0. That fixes the test. I expect that the new break is because DTE project reference resolution has changed under the hood to now return false for frameworks that don't exist.

**Comment by yishaigalatzer** [comment]
Lets take the test fix in the dev branch only, and close

**Comment by drewgillies** [comment]
Fix #369 merged.
