### ISSUE TITLE
Could a dependency conflict provide a little more detail?

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2238]
@GuardRex : https://github.com/dotnet/cli/issues/1646

A dependency conflict currently displays this information ...

```
<PATH>\project.json(42,30): warning NU1012: Dependency conflict. 
NETStandard.Platform 1.0.0-rc3-23901 expected System.AppContext >= 4.1.0-rc3-23901 but got 
4.1.0-rc3-23829
```

Could this information also state which package (or packages) requested the lower version?

btw- Nit ... "but got" ... perhaps "but received" would be better.

**Comment by yishaigalatzer** [comment]
This is a duplicate

**Comment by akoeplinger** [comment]
@yishaigalatzer which one is the real issue number?

**Comment by yishaigalatzer** [comment]
Searching as we speak :+1:

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/2142
