### ISSUE TITLE
Compile only package references should not verify compatible runtime assemblies

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2242]
Package references that are only using compile references should skip the guard rails check for runtime assemblies.

``` json
{ 
  "dependencies": {
    "packageA": {
      "version": "1.0.0",
      "include": "compile"
     }
  }
}
```

**Comment by emgarten** [comment]
This is related to: https://github.com/dotnet/cli/issues/1043 where runtime assemblies do not exist for the platform, and currently there is no way to skip the guard rails check.

**Comment by andyleejordan** [comment]
Will this transparently include said dependencies when the runtime implementation is available?

Also, can this make it into a 1.0.0 build?

Thanks Justin.

**Comment by andyleejordan** [comment]
> Will this transparently include said dependencies when the runtime implementation is available?

The sad answer is no, they will not. :frowning:

**Comment by emgarten** [comment]
NuGet/NuGet.Client@d795f5eeb4cd9462294c7f8cf78aae0b05436402

@andschwa yes this doesn't sound like it will fix your issue since you aren't just referencing the assemblies for compile. Guard rails is behaving as expect and throwing when runtime assets are referenced but not resolved.
