### ISSUE TITLE
Guard rails should include framework assemblies as runtime assets

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2246]
Guard rails verifies that all compile assets have runtime assets with the same assembly name. In the case of net45 these assets are framework references and not present in the lock file under a runtime asset node.

The fix for this is to include framework references when verifying compile assets in `CompatibilityChecker.Check`

**Comment by yishaigalatzer** [comment]
Still debating if we are completely removing guardrails

**Comment by rrelyea** [comment]
In PackageReference, guard rails is off by default.
In Project.json, guard rails exists.
We're won't fixing for this, unless it rears its ugly head in an important scenario later.
