### ISSUE TITLE
Guard rails does not include all file types

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2247]
Compile assets can be `.dll`, `.winmd`, or `.exe`, guard rails should check all of these types instead of just `.dll` when looking for runtime assets.

Also, when running the `CompatibilityChecker.IsCompatible` the check does not verify file type when looking at the ref and lib folder. This causes issues for packages such as xunit which have a file named `_` under lib.

**Comment by yishaigalatzer** [comment]
I think the plan is to turn off guardrails at some point?

CC @davidfowl @anurse @ericstj can you guys comment?

**Comment by davidfowl** [comment]
Yes, we need to remove them and find a new place for them to run later in the pipeline with the option to turn them off.

**Comment by yishaigalatzer** [comment]
OK, so we need a signal on when to remove it, and if it is going to be removed for UWP as well or just .NET Core

**Comment by rrelyea** [comment]
In PackageReference, guard rails is off by default.
In Project.json, guard rails exists.
We're won't fixing for this, unless it rears its ugly head in an important scenario later.
