### ISSUE TITLE
NuGet.PackageManagement: Solution folder corresponding to 'Scripts' folder of jQuery.2.1.3 alone does not get removed, on an uninstall

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#225]
NuGet.PackageManagement: Solution folder corresponding to 'Scripts' folder of jQuery.2.1.3 alone does not get removed, on an uninstall

**Comment by AndriySvyryd** [comment]
Scripts\jquery-2.1.3.intellisense.js file is removed by uninstall.ps1 and thus the removal of the Scripts folder should be handled there as well
