### ISSUE TITLE
RDP from a laptop which is 1600 resolution to machine at 150%, Package Manager hangs

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#2251]
From vs-feedback-532340

Have a 4K display with 150% size. Works fine on it. If I RDP from a laptop which is 1600 resolution, package manager console hangs when I try to open it.

 Before I tried opening it I was trying to NuGet update a package automatically and it errored out saying power shell could not be initialized. That is when I tried to open the package manager console from RDP.

**Comment by csharpfritz** [comment]
Also tracked internally with dump file on VSTS#180038

**Comment by rrelyea** [comment]
we'll consider dealing with if we get more feedback on this.
