### ISSUE TITLE
Potential blocking thread calls in PackageManagerControl

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#2252]
This is regarding review with @yishaigalatzer and @alpaix 

Some of the code switches to the main thread in order to update the UI however it appears to do so early and ends out making awaited calls on the thread. This could cause the UI to hang.

It is possible that the particular cases where we've seen this avoid the problem with _current_ lower level behavior however even in this case the maybe a future refactoring at a lower layer will cause unforeseen trouble at this layer.

See for example: PackageManagerControl.RefreshAvailableUpdatesCount

Regarding triage: we should get this area closely re-reviewed and if necessary fixed for 3.4.

**Comment by rrelyea** [comment]
Did this get fixed as part of Rohit's recent work?

**Comment by rrelyea** [comment]
we've gone through many JoinableTaskFactory related fixes throughout our codebase. closing as won't fix.
