### ISSUE TITLE
NuGet.exe does not support TLSv1.1 or TLSv1.2

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2253]
Additionally, SSLv3.0 is supported, which is a broken protocol. I think we should disable SSLv3.0.

Support as it stands today:

| _ | Xplat | nuget.exe | nuget.exe |
| --- | --- | --- | --- |
| **Protocol** | **Supported by default** | **Supported by default** | **Maximum support** |
| SSL 2.0 | :x: | :x: | :x: |
| SSL 3.0 | :x: | :white_check_mark: | :white_check_mark: |
| TLS 1.0 | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| TLS 1.1 | :white_check_mark: | :x: | :white_check_mark: |
| TLS 1.2 | :white_check_mark: | :x: | :white_check_mark: |

Xplat seems fine but nuget.exe needs work. The difference between the two is that nuget.exe is running on desktop .NET Framework and Xplat is running on .NET Core.

**Comment by joelverhagen** [comment]
Related: https://github.com/NuGet/Home/issues/390

**Comment by joelverhagen** [comment]
@matt-richardson, I am working on a fix for this. Thanks for the report!

**Comment by joelverhagen** [comment]
It seems that .NET Core functionality differs from platform to platform. See https://github.com/dotnet/corefx/issues/6668. Due to this issue, my fix will disable my new test that asserts that SSLv3.0 is not supported.

**Comment by yishaigalatzer** [comment]
Although the change is in the desktop commandline, it is heavily used by folks building .net core.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/330.
