### ISSUE TITLE
Align scroll bar position with the topmost edge of package list

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2254]
After the search status bar was added the package list in search control keeps blank placeholder above all items. Consider stretching vertical scroll bar up to the topmost list edge.

![image](https://cloud.githubusercontent.com/assets/8239356/13537054/e2aa8fa4-e1f7-11e5-9fe2-af96a7101369.png)

**Comment by rrelyea** [comment]
Fixed with: https://github.com/NuGet/NuGet.Client/commit/9f9b846d7fad262ca7e0a4cce9d2c1822c12892e
