### ISSUE TITLE
VS2015 Update 2 CTP ignores machine-wide package sources

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#2256]
Before Update 2 NuGet extension respected machine-wide sources, in our case installed on every developer's machine by dropping a file `%ProgramData%\NuGet\Config\SmartAction.nuget.config`. This worked in VS2015 Update 1, but the Update 2 CTP fails to restore packages from the private source defined in that file. The command line client, however, both lists and restores the packages reported by the VS plugin as missing at source.

In Visual Studio:

```
NuGet Package restore failed for project Data: Unable to find version '7.0.0' of package 'SmartAction.Xxxxxx'.
E:\NuPackages: Package stream for 'SmartAction.Xxxxxx.7.0.0' cannot be found at 'E:\NuPackages'.
https://api.nuget.org/v3/index.json: Response status code does not indicate success: 404 (Not Found).
.
```

In command prompt:

```
C:\projects\xxx>nuget list SmartAction
SmartAction.Xxxx 1.0.0.0
. . . . .
C:\projects\xxx>nuget restore
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Feeds used:
  C:\Users\kkm\AppData\Local\NuGet\Cache
  C:\Users\kkm\.nuget\packages\
  https://api.nuget.org/v3/index.json
  E:\NuPackages
  https://nuget:4488/nuget   <-- AHA! Here's the local source!

Restoring NuGet package SmartAction.Xxxxxx.7.0.0.
Adding package 'SmartAction.Xxxxxx.7.0.0' to folder 'C:\projects\xxx\packages'
Added package 'SmartAction.Xxxxxx.7.0.0' to folder 'C:\projects\xxx\packages'
```

Also, before CTP Update2, NuGet options box in Visual Studio looked like that on the picture in [this commant](https://github.com/NuGet/Home/issues/1298#issuecomment-143016221). In CTP2, the bottom part with machine-wide sources is no longer there:

![untitled picture](https://cloud.githubusercontent.com/assets/8228229/13538433/5d0d7660-e1ff-11e5-861f-57197d950a28.png)

Nuget extension version 3.4.0.531.

**Comment by yishaigalatzer** [comment]
@zhili1208 can you please investigate as top priority. @kkm000 can you send your personal email to me, so we can get you access to fixed bits to verify your scenario? y i g a l a t z @msft.com

**Comment by kkm000** [comment]
Done. I'll be happy to test the fix!

**Comment by yishaigalatzer** [comment]
Would you mind trying the RC release? It was out 2 days ago http://dist.nuget.org/index.html

**Comment by kkm000** [comment]
@yishaigalatzer: Yes, 3.4-RC fixes the problem, thank you! Extension version 3.4.0.653.
