### ISSUE TITLE
Restore for solution in subdirectory creates empty project.lock.json

### ISSUE THREAD

**Issue by ArvidJB** [NuGet/Home#2257]
We have a directory structure where a project is part of a solution which lives under a different folder (see attached zip file):
A\A.sln
A\A.Util\A.Util.csproj
B\B.csproj
where B.csproj depends on A.Util.csproj and should therefore inherit its NuGet dependencies.

Restoring the NuGet packages for A.sln does not include the NuGet references from A.csproj's project.json. After running
nuget.exe restore A\A.sln
you can inspect B\project.lock.json which contains no libraries, which seems incorrect.

This is in contrast to a restore on a top-level solution S.sln which also includes A.Util.csproj and B.csproj:
nuget.exe restore S.sln
which populates B\project.lock.json with the expected libraries.

This problem should be reproducible with the NuGet command line tool, Version: 3.3.0.212.

Also note that a NuGet restore from Visual Studio 2015U1 of A.sln does work correctly.

[S.zip](https://github.com/NuGet/Home/files/159335/S.zip)

**Comment by yishaigalatzer** [comment]
One quick comment - Your project.json is invalid in the sample - 

```
{
  "frameworks": {
    ".NETFramework,Version=v4.6": {}
  },
  "runtimes": {
    "win": {},
    "win-x64": {},
    "win-x86": {},
    "win-anycpu": {}
  },
  "dependencies": {
    "Newtonsoft.Json": "6.0.8",
  }
}
```

You can't have a trailing comma after the version number in 6.0.8

**Comment by ArvidJB** [comment]
@yishaigalatzer thanks, that's due to cutting down a much larger solution to a minimal repro. Apparently the NuGet JSON parser can handle the trailing comma, though. The same problem still exists after removing it.

**Comment by yishaigalatzer** [comment]
Yup, I can repro it. Trying to figure it out

**Comment by yishaigalatzer** [comment]
We are guessing there might be an issue with the msbuild task that find the Project to Project references in this case. 

How blocking is this to you, I wanted to understand this in the scope of other things we are working on at the moment.

**Comment by ArvidJB** [comment]
It is blocking us from converting an existing large codebase over to project.json. We would like to do that since it allows us to clean up our existing references. If it's not easy to fix or work around we will stick with our current packages.config approach for a while longer.

**Comment by emgarten** [comment]
NuGet.exe 3.4.0 gives the following error: `Invalid input 'C:\projects\S\A\..\B\B.csproj'. The file type was not recognized.`

B is likely being skipped all together during restore. This looks like an issue in `MSBuildUtility.GetAllProjectFileNames`

**Comment by ArvidJB** [comment]
Looks like the problem is that the msbuild.exe process returns "normalized" paths for the projects in the solution, while the call to MsBuildUtility.GetAllProjectFileNames in RestoreCommand.ProcessSolutionFile does not normalize the path to the project. I think this can be fixed by adding a Path.GetFullPath:

`-            var projectFiles = MsBuildUtility.GetAllProjectFileNames(solutionFileFullPath, _msbuildDirectory.Value);`
`+            var projectFiles = MsBuildUtility.GetAllProjectFileNames(solutionFileFullPath, _msbuildDirectory.Value).Select(Path.GetFullPath); // normalize path`

**Comment by emgarten** [comment]
Fixed by a PR from @ArvidJB 

NuGet/NuGet.Client@7b2e8a5260ecbeab6e1889018e562f71800e55f8
