### ISSUE TITLE
NuGet hangs when lock file can not be written

### ISSUE THREAD

**Issue by pspill** [NuGet/Home#2258]
NuGet Version: 3.4.0.710
"nuget.exe list -source https://api.nuget.org/v3/index.json"
result: command hangs, no network traffic.

Looking in the debugger, I see this stack:

>   mscorlib.dll!System.IO.__Error.WinIOError(int errorCode, string maybeFullPath)  Unknown
>     mscorlib.dll!System.IO.FileStream.Init(string path, System.IO.FileMode mode, System.IO.FileAccess access, int rights, bool useRights, System.IO.FileShare share, int bufferSize, System.IO.FileOptions options, Microsoft.Win32.Win32Native.SECURITY_ATTRIBUTES secAttrs, string msgPath, bool bFromProxy, bool useLongPath, bool checkHost)    Unknown
>     mscorlib.dll!System.IO.FileStream.FileStream(string path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, int bufferSize, System.IO.FileOptions options)   Unknown
>     NuGet.exe!NuGet.Common.ConcurrencyUtilities.ExecuteWithFileLockedAsync<NuGet.Protocol.HttpSourceResult>(string filePath, System.Func<System.Threading.CancellationToken, System.Threading.Tasks.Task<NuGet.Protocol.HttpSourceResult>> action, System.Threading.CancellationToken token)    Unknown

The IO Exception is:  +     $exception  {"Access to the path 'C:\Users\pspill\AppData\Local\Temp\NuGetScratch\lock\7e2c433b47ec107cf9a287a75947095cbf33c844' is denied."}   System.UnauthorizedAccessException

Once we get in to this state, ExecuteWithFileLockedAsync will try forever, since there is an infinite loop on IOException.  See \NuGet.Core\NuGet.Common\ConcurrencyUtilities.cs

This repros 100% on one machine that has an issue with this lock file. On another machine I don't ever hit this.

**Comment by yishaigalatzer** [comment]
@emgarten ping

**Comment by emgarten** [comment]
NuGet/NuGet.Client@d0fdec9eea230cbb4fbacbf1d83adc099daf57c2
