### ISSUE TITLE
Add support for pre/post restore scripts 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2260]
DNU supported pre and post restore scripts. NuGet should also handle this and call scripts listed in the project.json file.

**Comment by ah-** [comment]
I'm just porting a project over from dnx to dotnet cli and this would help me a lot. I built a very hacky prototype based on how the other dotnet cli scripts are implemented: https://github.com/ah-/NuGet.Client/commit/52976572b84b0d3cbb112147cdc1846a0e5a90d1

Mainly needs more correct escaping of the single script string into executable and arguments and forwarding of script output to the correct logger.

See https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L114 and from there on https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/Command.cs and https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.Cli.Utils/StreamForwarder.cs for the dotnet cli implementation.

**Comment by emgarten** [comment]
This should be possible now just by using MSBuild, right?

**Comment by rrelyea** [comment]
yes, msbuild should be good. closing.
