### ISSUE TITLE
Consider deprecating SSLv3.0 in nuget.exe.

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2261]
SSLv3.0 is broken and insecure. .NET Core does not support SSLv3.0 at all (once https://github.com/dotnet/corefx/issues/6668 is fixed). The only case where we support SSLv3.0 is nuget.exe.

Open questions:
1. Does running inside VS (with our VSIX) support SSLv3.0. If so, do we care?

**Comment by yishaigalatzer** [comment]
CC @blowdart - Can you share your opinion here?

**Comment by blowdart** [comment]
Kill ssl 2 & 3 with fire

**Comment by yishaigalatzer** [comment]
@joelverhagen you know what to do.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/339.
