### ISSUE TITLE
Suffix paramter adding 0 to SymVer

### ISSUE THREAD

**Issue by tomasz-soltysik** [NuGet/Home#2264]
With AssemblyInformationalVersion set to 1.0.1 pack command creates package with version 1.0.1
If I use Suffix parameter with eg. Dev, pack command creates package with version 1.0.1**.0**-Dev which is not right.

**Comment by tomasz-soltysik** [comment]
`public NuGetVersion(Version version, string releaseLabel = null, string metadata = null)`
is probably invoked somewhere. First parameter in [SemanticVersion ctor](https://github.com/NuGet/NuGet.Client/blob/afc65ae26b6f79b85f7a8deddab18c2cc3182b70/src/NuGet.Clients/NuGet.CommandLine/Commands/PackCommand.cs#L160) should be changed

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue, we will take a look in the next release as we are locking down for 3.4.

**Comment by toddm** [comment]
This looks like it might have been fixed on March 3 with [113f7d3](https://github.com/NuGet/NuGet.Client/commit/113f7d3697bb89c9b2ad077941391f9cba5f7d2f).  Please take a look at the latest version from here http://myget.org/gallery/nugetbuild to see if it fixes the problem.

**Comment by tomasz-soltysik** [comment]
Checked with 3.5 beta. Issue is almost fixed. Manifest contains good version number, but filename contains .0 before suffix. This is small issue, as filename is not used for anything.

**Comment by yishaigalatzer** [comment]
@lion92pl thanks! reactivated

**Comment by toddm** [comment]
This is now fixed in Dev, which will show up in myget.
