### ISSUE TITLE
NuGet cross-plat cli no longer reads NuGet.Config from project directory

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2265]
We're seeing issues when there is a `NuGet.Config` immediately adjacent to a `project.json`. NuGet used to honor that config file, but it no longer does. It looks like the problem is here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs#L63

We used to use the project directory itself as the search root, now we use the immediate parent. We use this frequently in dotnet/cli test projects so we can't easily update to the latest NuGet until this behavior is restored.

/cc @piotrpMSFT @davidfowl @yishaigalatzer @emgarten

**Comment by yishaigalatzer** [comment]
@emgarten please decide if you want to fix or reassign to @TimBarham

**Comment by TimBarham** [comment]
Hey @anurse - any chance you have a simple project that repro's this problem?

**Comment by TimBarham** [comment]
Never mind, I realize now it's a trivial repro (just a basic project created by `dotnet new` will do it).

**Comment by TimBarham** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/7537ffad4136f1e22f2aaf0b671f67d29ec4a022

**Comment by dhnnjy** [comment]
what is xplat cli, is it different than corecli?

**Comment by yishaigalatzer** [comment]
Nuget commandline.xplat is the standalone tool package that gets integrated into the dotnet CLI to provide restore capability and more capabilities are coming
