### ISSUE TITLE
NuGet UI installed tab loading forever for UWP app

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2266]
repro step:
1.  File -> new -> project-> visual c# -> blank app(universal windows) , or class library (portable) 
2.  Right click project , open  manage nuget  package 
3.  on installed tab.

expected : show installed packages

actual: loading forever

**Comment by johnataylor** [comment]
This does appear to be a problem - just tested bld 724 and get the behavior described.

**Comment by alpaix** [comment]
Filed new issue only for eternal loading bug. Returning the master one to @johnataylor.

**Comment by johnataylor** [comment]
fixed
