### ISSUE TITLE
Finish up IVS APIs to facilitate package indexing

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2268]
Most of the needs were addressed by https://github.com/NuGet/Home/issues/2148, however two needed more design or required changes that were too large for 3.4. The remaining work is:
### Opening the NuGet UI
- [ ] Open the NuGet UI for a specific project, tab (Browse/Installed/Updates), package source, and source term.
  - It would also make sense to allow the “Include prerelease” checkbox as a parameter.
### Package Installation
- [ ] A new install method that causes us  to pop up the license agreement UI.

Both of these APIs have the same key difference from current IVS APIs that make them "big changes": IVS APIs currently have no connection to our Visual Studio UI code.

**Comment by rrelyea** [comment]
As we've not heard any customer or partner requests for this, in the past 18 months. Killing it.
