### ISSUE TITLE
Uninstall force fails on Microsoft.ApplicationInsights

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#227]
Steps
1. Install-Package Microsoft.ApplicationInsights.WindowsStore -Pre
2. Get-Package | Uninstall-Package -force

[Also, test functional test UninstallPackageUseTargetFxPersistedInPackagesConfigToInvokeUninstallScript]

Output:
PM> Get-Package | Uninstall-Package -force
Attempting to gather dependencies information for package 'Microsoft.ApplicationInsights.0.13.3-build03939' with respect to project targeting 'Windows, Version=v8.1'
Resolving actions to uninstall package 'Microsoft.ApplicationInsights.0.13.3-build03939'
Resolved actions to uninstall package 'Microsoft.ApplicationInsights.0.13.3-build03939'
Removed package 'Microsoft.ApplicationInsights.0.13.3-build03939' from 'packages.config'
Install failed. Rolling back...
Package 'Microsoft.ApplicationInsights.0.13.3-build03939' already exists in folder 'c:\Users\juste\documents\visual studio 2015\Projects\App7\packages'
Added package 'Microsoft.ApplicationInsights.0.13.3-build03939' to 'packages.config'
Uninstall-Package : Sequence contains more than one element
At line:1 char:15
+ Get-Package | Uninstall-Package -force
+               ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UninstallPackageCommand
 
This appears to be due to GetNearest being unable to narrow down the target frameworks during uninstall time.

**Comment by emgarten** [comment]
Fixed

**Comment by danliu** [comment]
verified using latest vsix and uninstall was all successful
