### ISSUE TITLE
Move UAP/NETCore50 down to NETStandard1.4 (dotnet5.5)

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2273]
Due to shared library and the inability for the NETNative toolchain to support side-by-side we have to fix the generation of UAP/NETCore50 to a version less than latest.  We need to do this before NuGet 3.4 ships so that we aren't moving backward in the generation mapping.

This is required so that we can expose more API for NETCore than is currently supported by UWP (EG: more complete reflection).

/cc @yishaigalatzer @emgarten @weshaggard

**Comment by joelverhagen** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/342.
