### ISSUE TITLE
NuGet Delete does not work against a V3 endpoint

### ISSUE THREAD

**Issue by kkdawkins** [NuGet/Home#2274]
NuGet delete only works when given a V2 endpoint. When given a V3 endpoint, it incorrectly constructs the URL. 

For example, the following command:

`nuget delete angle.collar 43.1.78 -Source https://mseng.pkgs.visualstudio.com/DefaultCollection/_packaging/KevinDaw/nuget/v3/index.json -ApiKey VSTS`

Produces the following REST request:

`DELETE https://mseng.visualstudio.com/DefaultCollection/_packaging/KevinDaw/nuget/v3/index.json/angle.collar/43.1.78`

**Comment by yishaigalatzer** [comment]
@kkdawkins is this with 3.4?

**Comment by kkdawkins** [comment]
@yishaigalatzer It appears to be any NuGet 3.x client. I can repro on 3.2.1.10575

**Comment by yishaigalatzer** [comment]
Thanks, it must be a 3.X client of course because the 2.X doesn't recognize V3 feeds :)

**Comment by spadapet** [comment]
@drewgil

**Comment by drewgillies** [comment]
This is fixed in 3.4.0. @kkdawkins  -- please retry repro with the 3.4 RC.

**Comment by drewgillies** [comment]
You may also want to test the latest build from the MyGet feed: https://www.myget.org/feed/nugetbuild/package/nuget/NuGet.CommandLine/3.4.0-rtm-768

NuGet 3.4 RC: https://dist.nuget.org/win-x86-commandline/v3.4.0-rc/nuget.exe

**Comment by kkdawkins** [comment]
@drewgil Confirmed! Thank you for looking into it!

**Comment by drewgillies** [comment]
You're welcome :)
