### ISSUE TITLE
Nuget packages will not add references with "resources" in name.

### ISSUE THREAD

**Issue by willemtoerien** [NuGet/Home#2275]
When a package has "Resources" in it's dll name, the dll will not be added to the references. Please see [http://stackoverflow.com/questions/35886540/nuget-is-not-adding-references/35887234](url) for more information.

Once I alter the name "Resources" to something else, it works fine.

Kind Regards,
Willem Toerien.

**Comment by yishaigalatzer** [comment]
Yes, this is a by design convention, because of localized packages - https://docs.nuget.org/create/creating-localized-packages
