### ISSUE TITLE
NuGet and P4VS integration

### ISSUE THREAD

**Issue by maxpavlov** [NuGet/Home#2276]
We use perforce as our source control system. P4VS is the name of the Visual Studio plugin provided by Perforce. 

There is a huge problem with the plugin - every time we NuGet something in or update the package's version, we need to manually checkout the packages.config in the project for it's changes to be noticed by SC. This adds errors that are only detected during CI.

The reason for the changes to packages.config not being detected is described in the following perforce thread:

http://forums.perforce.com/index.php?/topic/2821-p4vs-and-nuget-advice-seeked/page__hl__packages.config

Perforce employee states:

 It seems as though NuGet is editing that file outside of the IDE.

Is this true? Is NuGet interacting with packages.config somehow different, so that IDE and P4VS can't detect it? Could this be fixed? 

Thanks.

**Comment by yishaigalatzer** [comment]
This issue was fixed in visual studio 2015, we do not plan to address it in downlevel versions of visual studio. So the answer is to update, and let us know if you still see an issue.

My 2c and please don't take it as a copout, we totally still support centralized source control systems like perforce and TFS:

Take a look at GIT, I used perforce and loved it back in 2007. but the fact that you still have to checkout files in 2016 is behind the times.

I'm closing because I don't think there is more action here, but if you still see specific issues in Visual Studio 2015 (3.3 at least 3.4RC better) let us know.

**Comment by maxpavlov** [comment]
Hello. Thanks for a prompt response. I seem to be using the latest version of VS 2015 (Update 1) and still confirm the issues is there, no changes. Here is my about window for VS:
![VS About](https://i.gyazo.com/43f5ddf9bc781a56f15af284859af53e.png)

There are no outstanding updates shown for VS except for some Azure stuff. 
NuGet version is 3.3.0.167

@yishaigalatzer, could you please re-open the issue? Thanks.

**Comment by maxpavlov** [comment]
@yishaigalatzer Could you please re-open this issue for someone in the team to take a look? Thanks.

**Comment by yishaigalatzer** [comment]
Sure, can you try one more thing before we do? Can you please try 3.4 (available on the download tabs of nuget.org)

Here is my guess: we call the vs apis for checking out files before doing anything with packages.config (in fact we have bugs about being too aggressive about it). Perhaps the perfoce plugin is not listening to them. 

We should be able to take a look.

**Comment by yishaigalatzer** [comment]
Reopening for investigation in 3.4 CC @skofman1

**Comment by skofman1** [comment]
There is indeed an integration problem. NuGet 3.4 uses DTE.SourceControl in order to checkout packages.config. This interface is not implemented by P4VS. 
The options here are obvious:
1. Either NuGet tries to hit an API P4VS implements
2. P4VS implement DTE.SourceControl 

@yishaigalatzer ?

**Comment by yishaigalatzer** [comment]
What does p4vs implement?

**Comment by yishaigalatzer** [comment]
@maxpavlov from the surface it looks like the perforce extension doesn't implement the required APIs required by NuGet to interact with it, see above.

We will take another look, and see if they can implement it or there is some technical limitation that blocks them from doing so. If it is implementable I think we are going to close this and redirect the work over to P4VS, either way I'm moving this out of this milestone

**Comment by maxpavlov** [comment]
Ok, thank you very much. I will let P4VS know that they can arrive at the solution (since I think this is their interest) via their support forums as well. But if you have a contact with them over your channels, please still use it. I assume MS contacting Perforce will be way more effective. Thanks for taking a look at this.

**Comment by wbaffy** [comment]
P4VS implements DTE.SourceControl in 2018.4
`        #1717269 (Bug #66552, 59357)
            P4VS now implements some of EnvDTE.SourceControl. Other
            Visual Studio tools can now call IsItemUnderSCC,
            IsItemCheckedOut, and CheckOutItem. This will enable files
            like packages.config to be checked out when they are being
            edited by NuGet package manager.`
