### ISSUE TITLE
CLI "delete" is actually "unlist"

### ISSUE THREAD

**Issue by vtbassmatt** [NuGet/Home#2277]
The CLI verb "delete" is actually "unlist", at least against NuGet.org and VS Team Services (not sure what other implementations have decided). It would cause less confusion if there were two separate verbs.

NuGet.org would deny "delete" but allow "unlist". Presumably for fileshares, "delist" would be denied but "delete" would work. Team Services would allow both verbs but apply potentially different permissions checks.

**Comment by yishaigalatzer** [comment]
This feedback is valid, I suggest that on vsts you make delete == delete and not unlist.

On NuGet.org we can eventually change the behavior like you are suggesting, but for now we could just add an unlist verb. 

Lets discuss priority offline

**Comment by vtbassmatt** [comment]
@zjrunner @jmyersmsft @alexmullans thoughts on making our `nuget delete` == delete and putting delist in the UX? Makes sense to me if NuGet cmd line will be adding an unlist verb.

**Comment by zjrunner** [comment]
I worry about changing expectations across versions of the client -- I'd create new verbs or switches, not change the meaning of 'delete' (where every doc and StackOverflow thread needs to get specific about version ranges of the client being used).  You could go for a -soft and -hard delete if you want to be git-y, or go for an 'unlist' and 'remove' command so you could always doc that delete/unlist are equivalent for nuget and users will only have one or the other to reduce confusion.

**Comment by vtbassmatt** [comment]
@yishaigalatzer can you expand on your preference for us to differ from nuget.org? Where we can, we imitate your semantics to avoid fragmenting advice on StackOverflow as @zjrunner alluded to.

**Comment by rrelyea** [comment]
closing this issue, as our backlog is too large...and it hasn't come up in the last 18months.
