### ISSUE TITLE
Corrupt cache file causes dotnet restore to crash

### ISSUE THREAD

**Issue by kichalla** [NuGet/Home#2278]
I am able to repro this with the following latest version of dotnet CLI. I couldn't re-open the issue https://github.com/NuGet/Home/issues/2133, so creating a new one here.

This issue has been causing lot of pain because to fix it I have to delete the individual corrupt packages and run the restore again and again (as each time its a random package) until the restore succeeds.

**Repro**
- Delete `%localappdata%\Nuget\v3-cache` folder
- Delete `%userprofile%\.nuget\packages` folder
- Clone MVC repo
- With the following latest CLI, do a `dotnet restore`. You should notice the following kind of errors. _Please try few times as this issue seems random and on random package_

**Errors**

```
warn : The file 'C:\Users\kichalla\AppData\Local\NuGet\v3-cache\8f4358f45e87338232123d05bea76a3f13464d9a$_F_aspnetcidev_api_v3_index.json\nupkg_System.Runtime.4.1.0-rc2-23819.dat' is corrupt.
warn : The file 'C:\Users\kichalla\AppData\Local\NuGet\v3-cache\8f4358f45e87338232123d05bea76a3f13464d9a$_F_aspnetcidev_api_v3_index.json\nupkg_System.Runtime.4.1.0-rc2-23819.dat' is corrupt.
error: End of Central Directory record could not be found.

```

**Version Info:**

```
.NET Command Line Tools (1.0.0-dev-001606)

Product Information:                      
 Version:     1.0.0-dev-001606            
 Commit Sha:  399b3ee470                  

Runtime Environment:                      
 OS Name:     Windows                     
 OS Version:  10.0.10586                  
 OS Platform: Windows                     
 Runtime Id:  win10-x64                   
```

@yishaigalatzer  @dougbu

**Comment by yishaigalatzer** [comment]
The fix didn't make it into the CLI yet, should happen today.

**Comment by yishaigalatzer** [comment]
@kichalla use nuget.exe locals -clear all to alleviate your pain

**Comment by kichalla** [comment]
@yishaigalatzer Actually I did try clearing the caches but that still didn't resolve the issue. Didn't know that it was not part of the new CLI yet. Will try it out once available. Thanks
