### ISSUE TITLE
Update Tab - time to load

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2279]
Repro:
1. Install NuGet 3.4
2. Create a new MVC 5 web application
3. Open the nuget package manager ui for the project and immediately click on the update tab
4. Wait ~10-20 seconds

Expected:
1. The data should show up a lot faster (within a couple of seconds)

**Comment by johnataylor** [comment]
As we discussed lets just consolidate discussion about update perf #561

**Comment by zhili1208** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249)
