### ISSUE TITLE
Normalize use of loggers in UI

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2286]
Follow-up on https://github.com/NuGet/NuGet.Client/pull/353.

**The problem:**
UI layer employs many different loggers across different components, e.g. `INuGetUILogger`, `Logging.ILogger`, `ActivityLogger`, `ProgressWindow`, etc. This leads to inconsistent user experience where different actions send output in many ways: inline in notification bar, in activity log file, in output window, or in a command window. Worse, some of the actions report errors to `NullLogger`.

**The solution:**
Come up with unified UI logging component for consistent user experience.

**Comment by yishaigalatzer** [comment]
Also note from @emgarten 

NuGet contains two logging abstractions: ILogger and INuGetProjectContext. These should be consolidated.

Potentially ways to fix this:

INuGetProjectContext could extend ILogger
INuGetProjectContext could add an ILogger property.

**Comment by rrelyea** [comment]
nice to do, but not very imminent. So closing.
