### ISSUE TITLE
Add web caching for UI and gather scenarios

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2287]
Today the disk cache (v3-cache) is used only for project.json restore. Now that `HttpSource` is used across the product registration blobs and v2 xml should also be cached to disk to allow scenarios such as independent package updates and finding if updates are available in the UI.

project.json restores use `SourceCacheContext` to control cache expiration, this could also be passed through on other scenarios.

**Comment by emgarten** [comment]
//cc @joelverhagen

**Comment by rrelyea** [comment]
@jainaashish just did work like this..enabling httpcache for packages.config codepaths (UI & Gather) with v2 or v3 feeds.
