### ISSUE TITLE
Latest nuget package is not showing in https://api.nuget.org/v3/index.json feed

### ISSUE THREAD

**Issue by drgraduss** [NuGet/Home#2289]
I'm experiencing issue similar to https://github.com/NuGet/Home/issues/1145 and https://github.com/NuGet/Home/issues/1544 with `Neo4jClient` package.

Latest version 1.1.0.29 is not showing up in the VS2015 for nuget v3 feed.
Nuget v2 feed returns the latest version though.

Trying to install latest version from PackageManagerConsole gives me 1.1.0.28. Plus Teamcity nuget restore failing to find 1.1.0.29 version as well (uses Nuget v.3.3.0).

I can confirm that I can download package from https://api.nuget.org/packages/neo4jclient.1.1.0.29.nupkg

**Comment by skofman1** [comment]
Was moved to the Gallery: https://github.com/NuGet/NuGetGallery/issues/2927
