### ISSUE TITLE
When specifying references in nuspec, pack fails with "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2290]
Config used:

```
 <references>   
       <reference file="DepDepLib.dll"></reference>
    </references>
```

Output: Object reference not set to an instance of an object.

**Comment by emgarten** [comment]
@skofman1 would you run this with `-verbosity detailed` and paste the stack trace?

**Comment by skofman1** [comment]
Attempting to build package from 'PackTestClassLibrary.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\PackTestClassLibrary\PackTestClassLibrary.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Packing files from 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\PackTestClassLibrary\bin\Debug'.
Using 'PackTestClassLibrary.nuspec' for metadata.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DependencyLib\DependencyLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DepDepLib\DepDepLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DependencyLib\DependencyLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DepDepLib\DepDepLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
File from dependency is not changed. File 'Content\bootstrap-theme.css' is not added.
File from dependency is not changed. File 'Content\bootstrap-theme.min.css' is not added.
File from dependency is not changed. File 'Content\bootstrap.css' is not added.
File from dependency is not changed. File 'Content\bootstrap.min.css' is not added.
File from dependency is not changed. File 'fonts\glyphicons-halflings-regular.svg' is not added.
File from dependency is not changed. File 'Scripts\bootstrap.js' is not added.
File from dependency is not changed. File 'Scripts\bootstrap.min.js' is not added.
File from dependency is not changed. File 'Scripts\jquery-1.9.1.js' is not added.
File from dependency is not changed. File 'Scripts\jquery-1.9.1.min.js' is not added.
Found packages.config. Using packages listed as dependencies
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DependencyLib\DependencyLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Building project 'C:\Users\skofman\Documents\Visual Studio 2015\Projects\PackTest\DepDepLib\DepDepLib.csproj' for target framework '.NETFramework,Version=v4.5.2'.
Found packages.config. Using packages listed as dependencies
Object reference not set to an instance of an object.

**Comment by toddm** [comment]
This has been fixed by my recent changes.
