### ISSUE TITLE
NuGet restore issuing error about NuGetScratch folder

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#2292]
Lately a lot of restores on my team are producing the following error message:

```
C:\Users\jaredpar\AppData\Local\Temp\NuGetScratch\lock\1de659d695c5816ecbb48e1ce81ee816ee502e67'
```

At first I thought it was an artifact from a previous NuGet I'd killed and force deleted the directory.  Yet this still pops up with high regularity when restore our [Samples.sln](https://github.com/dotnet/roslyn/blob/master/src/Samples/Samples.sln) solution.  The repro should work on any machine: 
- clone roslyn (https://github.com/dotnet/roslyn)
- run: `.\nuget.exe restore .\src\Samples\Samples.sln -configfile .\NuGet.Config`

Is this a known issue? 

The version of NuGet we are using is 3.4.0.665

**Comment by yishaigalatzer** [comment]
@jaredpar I can't see an error message. 

I would

a. pick the latest build 742 - We did fix bugs in this area
b. Make sure you don't run restore from admin and non admin, we create lock files that can't be locked after an admin might have created them

**Comment by yishaigalatzer** [comment]
Closing, please re-open if it repros after addressing both feedback items.

**Comment by jaredpar** [comment]
@yishaigalatzer  

When you tried to reproduce this did you use the `nuget.exe` checked into the Roslyn repo?  I'm surprised it didn't repro for you.  Right now it's failing for every Roslyn developer we've ran this scenario on.  

I can't speak for other devs but I haven't restored with a mix of admin / non-admin.  Even if I had I'm unsure how that problem would persist after fully blowing away the directory listed by the error message.  

> pick the latest build 742 - We did fix bugs in this area

Can you point me to these bugs?  Upgrading NuGet.exe can be done but it's work and potentially destabilizing to our repo.  Doing this to fix a bug goes over better if we have a bug to reference.

**Comment by jaredpar** [comment]
@yishaigalatzer and I spoke off line and eventually we narrowed down the problem to the Virus Checker on our dev machine.  It's racing with NuGet's restore process and exposing a latent issue which is fixed in recent builds.  Change in behavior is likely a result of changes in how the virus checker processes these directories.
