### ISSUE TITLE
Split the nuget extension build into two for dev14 & dev15

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2293]
We want to remove dependencies on shell14 in nuget going to dev15, to reduce memory payload by 5MB or so.

**Comment by yishaigalatzer** [comment]
Internal tracking issue - https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems?_a=edit&id=180207

**Comment by deepakaravindr** [comment]
This is related to https://github.com/NuGet/Home/issues/2386, and depended on #2392
#2369

**Comment by yishaigalatzer** [comment]
@rrelyea can you please add a comment/commit to clarify the state of this work?
