### ISSUE TITLE
Using TFM as a search filter

### ISSUE THREAD

**Issue by poimis** [NuGet/Home#2295]
Is it possible to search for packages that target given TFM?

Reading through Nuget.Services.Seach.QueryMiddleware gives me impression it's possible but I can't find any client that implements it, neither the search on nuget.org seems not to support that.

**Comment by yishaigalatzer** [comment]
It is not possible at the moment on the V3 server, it is somewhat possible on the V2 server, but it is not complete and doesn't understand the new package formats.

Something to consider for the future

**Comment by yishaigalatzer** [comment]
@xavierdecoster can you please track down the duplicate item and close it?

**Comment by poimis** [comment]
@yishaigalatzer Thanks for the info. We really need this functionality somehow. Either exposing targeted frameworks in the package metadata (so clients can filter) or provide a search api (so one could search on the web). Especially now when people start searching for packages that work for .NET Core.

**Comment by yishaigalatzer** [comment]
@poimis I don't disagree with the need, but this is not in our immediate horizon. I moved the bug to the server for now - https://github.com/NuGet/NuGetGallery/issues/2936

**Comment by xavierdecoster** [comment]
@yishaigalatzer Is this the dupe you refer to? https://github.com/NuGet/Home/issues/318
