### ISSUE TITLE
Optimize settings load during restore

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2297]
CLI projects can contain NuGet.Config files in the project directory, to read these NuGet reloads all settings for each project. This should be optimized so that configs from higher level directories can be cached.

Related to: https://github.com/NuGet/Home/issues/2265

//cc @TimBarham

**Comment by TimBarham** [comment]
Caching settings didn't prove to be a significant benefit, but got some improvements by:
- Caching remote dependency providers (https://github.com/NuGet/NuGet.Client/commit/59519fc2)
- Avoiding writing out project.lock.json unnecessarily (https://github.com/NuGet/NuGet.Client/commit/8903878a).
