### ISSUE TITLE
Create netcoreapp1.0 TFM and map it to netstandard1.5

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#2299]
As part of our dotnet cli work we will be needing a new TFM called "netcoreapp" currently with only one version "netcoreapp1.0" which maps to netstandard1.5.

cc @ericstj @richlander

**Comment by weshaggard** [comment]
cc @yishaigalatzer @joelverhagen

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/361.

**Comment by bricelam** [comment]
Where can we learn more about this new TFM and how it differentiates from `netstandardapp1.5`?

**Comment by weshaggard** [comment]
@richlander When do we plan to publish the spec for this?

**Comment by NickCraver** [comment]
+1 on @bricelam's request. But to add - if the API levels match, why wouldn't it be `netcoreapp1.5`? Can't we simplify the naming/versioning here to only use one level?

**Comment by richlander** [comment]
Still working on these docs.

There is a mapping of TFM to metapackage.
- netstandard -> NETStandard.Library (this is expected to work on all .NET 
- netstandardapp -> NETStandard.App (same as NETStandard.Library + app hosts)
- netcoreapp -> Microsoft.NETCore.App (this is the .NET Core base install)

You can explore the packages here: https://dotnet.myget.org/gallery/dotnet-core
