### ISSUE TITLE
Pack should fail on unrecognized frameworks

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2301]
Pack converts unknown frameworks to `Unsupported0.0` in the nuspec for unknown group target frameworks. This often goes unnoticed by package authors and results in a broken package when an older version of NuGet.exe is used by mistake to pack.

Pack should instead fail and error out without creating the nupkg. This should contain a message letting the user know which framework is not recognized and suggesting that they fix their nuspec or update nuget.exe.

**Comment by davidfowl** [comment]
Omg yes

**Comment by nkolev92** [comment]
File based frameworks are covered in https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5103. 

Nuspec stuff covered with an error.
```
Attempting to build package from 'Test.nuspec'.
Unsupported targetFramework value '.MyBadFramework1.2'.
```
