### ISSUE TITLE
Add project.json dependency type "platform"

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2303]
``` json
{
    "dependencies": {
        "MyPlatformTargettingPackThingy": {
            "version": "1.0.0",
            "type": "platform"
        }
    }
}
```

This `type` flag implies the following behavior:
- Suppress all `runtime` and `native` assets for the package and it's dependencies (my sources say this is basically already possible via a different flag)

Nothing else is implied by this flag in NuGet. Other tools (i.e. `dotnet publish`) will use it, but NuGet does not need to handle that part. This is needed to indicate which package defines the shared framework.

/cc @davidfowl @DamianEdwards (did I get the implications right?)
/cc @yishaigalatzer Triaging (I should be able to handle this and send a PR)
/cc @emgarten FYI

**Comment by yishaigalatzer** [comment]
@anurse please proceed, I'm fine with this after our discussion. This also needs to get documented in nugetdocs and perhaps on the CLI. Who is taking care of that?

**Comment by davidfowl** [comment]
There's one tricky part here that we need to discuss. We need this flag to win if another package brings in the same version of dependencies in the platform.

**Comment by analogrelay** [comment]
Do we need that for CLI RC2? As far as I can tell, the worst outcome of that is that we'll unnecessarily publish managed code bits. I totally agree that's bad, but I think we could live with it for RC2 given the tight schedule.

I'll take a look at trying to make the flag always win, but I've got quite a bit on my plate already and I just want to get this in as quickly as possible :)

**Comment by emgarten** [comment]
Include/exclude flags defined at the top level override all other flags.

For example:

```
Project -(platform only)-> A
Project -(all)-> B -(all)-> A
```

A will be treated as a platform type.

**Comment by yishaigalatzer** [comment]
Platform only applies to the netcore package and only one of these flags can exist (or more correctly only one package can have it specified).

We want this for rc

**Comment by davidfowl** [comment]
@emgarten The thing you're missing is the fact that A is a meta package that has a bunch of dependencies we want to omit during publish. Consider:

```
Project -(platform only)-> Meta -> B -> C
Project -(all)-> A -(all)-> B -> C
```

If the resolved B and C are the same version that comes from the platform only edge, then those flags should win, otherwise keep the default logic.

**Comment by analogrelay** [comment]
It sounds like getting this in fairly soon would be good. I don't have cycles to work on this directly right this moment, I'm working on other high-pri CLI integration stuff. /cc @piotrpMSFT @davidfowl @yishaigalatzer @emgarten

**Comment by emgarten** [comment]
@davidfowl in that case, yes it would pull in everything since it isn't top level. Also, flags are checked against the flattened graph currently where versions do not matter. The check here seems a little different than other flags.
