### ISSUE TITLE
NuGet xplat failing during tools restore

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#2304]
Repro:
on Windows
- git clone https://github.com/dotnet/cli.git
- cd cli
- git fetch origin
- git checkout -b emgarten/nuget0752 origin/emgarten/nuget0752
- git merge rel/1.0.0
- build.ps1

Expected:
build finishes successfully

Actual:
12:05:02 error: The process cannot access the file 'C:\Users\dotnet-bot.nuget\packages.tools\dotnet-hello\2.0.0\netstandardapp1.5\project.lock.json' because it is being used by another process.

**Comment by yishaigalatzer** [comment]
This should not go into RTM

**Comment by brthor** [comment]
An idea about what's happening here. 

Two project.jsons referencing the same tool version restored in parallel.
The tool restores get kicked off async and race on the project.lock.json file write access.

Perhaps some way to merge tool restores across projects would fix this? Is that feasible?

**Comment by yishaigalatzer** [comment]
We need to lock, we have a locking mechanism already forcross process

**Comment by emgarten** [comment]
This fix was reverted and it is currently blocked by the Update 2 release.

**Comment by TheRealPiotrP** [comment]
https://github.com/NuGet/NuGet.Client/pull/366 Seems merged. What is blocked? How soon does it get unblocked?

We need a working build Monday to facilitate Shared Framework standup.

**Comment by yishaigalatzer** [comment]
It is blocked because of branching. It will be unblocked on Monday or you can grab the build that had the fix.

**Comment by TheRealPiotrP** [comment]
What was that build number?

Sent using OWA for iPhone

**Comment by emgarten** [comment]
763 contains the fix, it is not on the nugetbuild feed. 764 has the reverted change and will not work.

**Comment by TheRealPiotrP** [comment]
Can we somehow consume 763?

Sent using OWA for iPhone

**Comment by yishaigalatzer** [comment]
Yes you sure can.

Sent from Outlook Mobilehttps://aka.ms/xp9y6l

On Sun, Mar 13, 2016 at 1:49 PM -0700, "Piotr Puszkiewicz" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can we somehow consume 763?

Sent using OWA for iPhone

**Comment by joelverhagen** [comment]
The fix is now in `dev`. For real this time. :roller_coaster:
