### ISSUE TITLE
NuGet xplat failing to restore packages in CLI latest version

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#2305]
Repro:
- Install latest
- mkdir hwapp && cd hwapp
- dotnet new
- dotnet restore

Expected result: restore completes

Actual result: error that netstandardlib cannot be restored for the framework in project.json. 

Tried on Ubuntu 14.04, Win8, Win7 SP1. Same results on all. Tried dnxcore50, netstandardapp1.5 same results.

**Comment by yishaigalatzer** [comment]
@blackdwarf I think this had to do with a CDN outage, things are working fine now.

In the future please include:
1. Version of nuget.xplat and CLI you are using
2. Log
