### ISSUE TITLE
dotnet restore failed when "Project.json" file name is captialized

### ISSUE THREAD

**Issue by troydai** [NuGet/Home#2306]
## Steps to reproduce
1. `dotnet new`
2. Rename `project.json` to `Project.json`
3. `dotnet restore`
## Expected  behavior

Restore successfully
## Actual behavior

```
$ dotnet restore
log  : Restoring packages for D:\dev\repo\np\Project.json...
info : Committing restore...
log  : D:\dev\repo\np\Project.json
log  : Restore completed in 24604ms.

NuGet Config files used:
    C:\Users\troyd\AppData\Roaming\NuGet\NuGet.Config
Could not find a part of the path 'D:\dev\repo\np\Project.json\project.json'.
```
## Environment data

`dotnet --version` output:

1.0.0-beta-001709
sha: b7392e65b6

**Comment by emgarten** [comment]
I'm not able to repro this in the latest dev channel, is beta older?

**Comment by troydai** [comment]
It's on beta channel. `1.0.0-beta-001709`

**Comment by yishaigalatzer** [comment]
This seems like a super low pri item, can you please validate on the latest, and if it repros push to CLI 1.1

**Comment by rrelyea** [comment]
project.json in net core doesn't matter any more. closing.
