### ISSUE TITLE
Nuget restore and install fails to install packages with versions that are not normalized

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2307]
I apologize if this is a dupe of a pre-reported issue.  I saw a similar issue reported but I am not sure the issue is exactly the same.

d:\tfs\IS\ES\M\CBT\NuGet>nuget
NuGet Version: 3.4.0.738

d:\tfs\IS\ES\M\CBT\NuGet>nuget list SourceDepotClient
SourceDepotClient 2.8.0.0

d:\tfs\IS\ES\M\CBT\NuGet>nuget install SourceDepotClient -version 2.8.0.0
Feeds used:
  C:\Users\joshking\AppData\Local\NuGet\Cache
  C:\Users\joshking.nuget\packages\
  https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json
  http://sqlisnuget/ds-shared/nuget

Attempting to gather dependency information for package 'SourceDepotClient.2.8.0' with respect to project 'd:\NuGetPackages', targeting 'Any,Version=v0.0'
Package 'SourceDepotClient,2.8.0.0' is not found in the following primary source(s): 'C:\Users\joshking\AppData\Local\NuGet\Cache,C:\Users\joshking.nuget\packages\,https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json,https://msdata.pkgs.visualstudio.com/Def
aultCollection/_packaging/SQL_Toolset/nuget/v3/index.json,https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json,http://sqlisnuget/ds-shared/nuget'. Please verify all your online package sources are available (OR) package id, version are specified correctly.

d:\tfs\IS\ES\M\CBT\NuGet>type packages.config
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="SourceDepotClient" version="2.8.0.0" />
</packages>

d:\tfs\IS\ES\M\CBT\NuGet>nuget install packages.config
Feeds used:
  C:\Users\joshking\AppData\Local\NuGet\Cache
  C:\Users\joshking.nuget\packages\
  https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json
  http://sqlisnuget/ds-shared/nuget

Restoring NuGet package SourceDepotClient.2.8.0.
  GET https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/4fb3f7f7-46a4-48be-852e-5aba811259c2/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET http://sqlisnuget/ds-shared/nuget/Packages(Id='SourceDepotClient',Version='2.8.0')
  NotFound http://sqlisnuget/ds-shared/nuget/Packages(Id='SourceDepotClient',Version='2.8.0') 64ms
  GET http://sqlisnuget/ds-shared/nuget/FindPackagesById()?Id='SourceDepotClient'
  OK http://sqlisnuget/ds-shared/nuget/FindPackagesById()?Id='SourceDepotClient' 28ms
  Unauthorized https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg 276ms
  Unauthorized https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg 278ms
  NotFound https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/4fb3f7f7-46a4-48be-852e-5aba811259c2/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg 665ms
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  NotFound https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg 171ms
  NotFound https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg 628ms
WARNING: Unable to find version '2.8.0' of package 'SourceDepotClient'.
  C:\Users\joshking.nuget\packages: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
  C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
  http://sqlisnuget/ds-shared/nuget: Package 'SourceDepotClient.2.8.0' is not found on source 'http://sqlisnuget/ds-shared/nuget'.
  https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json'.
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json'.
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json'.

d:\tfs\IS\ES\M\CBT\NuGet>nuget restore packages.config
Restoring NuGet package SourceDepotClient.2.8.0.
  GET https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/4fb3f7f7-46a4-48be-852e-5aba811259c2/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET http://sqlisnuget/ds-shared/nuget/Packages(Id='SourceDepotClient',Version='2.8.0')
  NotFound http://sqlisnuget/ds-shared/nuget/Packages(Id='SourceDepotClient',Version='2.8.0') 157ms
  GET http://sqlisnuget/ds-shared/nuget/FindPackagesById()?Id='SourceDepotClient'
  OK http://sqlisnuget/ds-shared/nuget/FindPackagesById()?Id='SourceDepotClient' 31ms
  Unauthorized https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.
  Unauthorized https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.
  NotFound https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/4fb3f7f7-46a4-48be-852e-5aba811259c2/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nup
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  GET https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupkg
  NotFound https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/0da5341a-70c3-4663-8a76-3f6f65bc400b/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupk
  NotFound https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/cfbab30e-3c62-4dd8-ba8a-6a354a64ee81/nuget/v3/flat2/sourcedepotclient/2.8.0/sourcedepotclient.2.8.0.nupk
WARNING: Unable to find version '2.8.0' of package 'SourceDepotClient'.
  C:\Users\joshking.nuget\packages: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
  C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
  http://sqlisnuget/ds-shared/nuget: Package 'SourceDepotClient.2.8.0' is not found on source 'http://sqlisnuget/ds-shared/nuget'.
  https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://ossmsft.pkgs.visu
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkgs.vi
  https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkgs.visu

Errors in packages.config projects
    Unable to find version '2.8.0' of package 'SourceDepotClient'.
      C:\Users\joshking.nuget\packages: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
      C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'SourceDepotClient.2.8.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
      http://sqlisnuget/ds-shared/nuget: Package 'SourceDepotClient.2.8.0' is not found on source 'http://sqlisnuget/ds-shared/nuget'.
      https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://ossmsft.pkgs.
      https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkg
      https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json: Package 'SourceDepotClient.2.8.0' is not found on source 'https://msdata.pkgs.

NuGet Config files used:
    d:\tfs\IS\ES\M\NuGet.Config
    C:\Users\joshking\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    C:\Users\joshking\AppData\Local\NuGet\Cache
    C:\Users\joshking.nuget\packages\
    https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_packaging/OSS_ALL/nuget/v3/index.json
    https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Toolset/nuget/v3/index.json
    https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLIS_ISS/nuget/v3/index.json
    http://sqlisnuget/ds-shared/nuget

**Comment by yishaigalatzer** [comment]
What servers are you using? Is one of them ProGet by any chance?

We have a known issue around pacakges that are not following semver and use superflous versions. At the moment we know that ProGet is not tolerant to these, and we are discussing a fix with ProGet.

If this is not the case please let us know

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/2298

**Comment by kingerja** [comment]
This has nothing to do with proget as the sample shows it is pulling from a v3 VSO feed.  It is simply if you have a nuget package that doesn't have a have a normailzed version such as having an 4 part version number with the last digit being 0.
