### ISSUE TITLE
dotnet restore doesn't use NuGet.config at current directory

### ISSUE THREAD

**Issue by troydai** [NuGet/Home#2309]
### Steps
1. `dotnet new`
2. `dotnet restore`
### Expectation

The `NuGet.config` file created during `dotnet new` should be used by the `dotnet restore`
### Actual

It uses the `NuGet.config` at the `%LocalAppData%` only. 

```
$ dotnet restore
log  : Restoring packages for D:\dev\tools\repo\project.json...
info : Committing restore...
log  : D:\dev\tools\repo\project.json
log  : Restore completed in 1154ms.

NuGet Config files used:
    C:\Users\troyd\AppData\Roaming\NuGet\NuGet.Config
```

It is fixed when the `project.json` is moved to a folder. However the default behavior is misleading especially when it is used with `dotnet new` together.

**Comment by yishaigalatzer** [comment]
Dup

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/2265
https://github.com/NuGet/Home/issues/2297

**Comment by troydai** [comment]
:beers:
