### ISSUE TITLE
NuGet restore when two projects have the same name

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2310]
from @rajivharris

https://github.com/NuGet/NuGetGallery/issues/2935

Nuget restore is failing if they are two projects with same names but different directory in the same solution.

Restore failed
The project name 'Service' is ambiguous between the following projects:
G:\microservices\src\Service
G:\microservices\test\Service

**Comment by yishaigalatzer** [comment]
Can you please provide more details on your scenario
1. Version of NuGet
2. Do you run this in visual studio/nuget.exe/dotnet restore
3. What type of projects are these (this is expected if this is a dotnet project at least for now)

**Comment by yishaigalatzer** [comment]
CC @emgarten

**Comment by emgarten** [comment]
This is a DNU error message.

**Comment by yishaigalatzer** [comment]
So @emgarten do you allow it now?

**Comment by rajivharris** [comment]
Yes this happens in the new xproj, but pointing to the full .net framework not the .core.

```
"frameworks": {
    "dnx451": { }
  }
```

Nuget Version : 3.3.0.167
Visual Studio 2015

**Comment by emgarten** [comment]
NuGet does allow this, it has an order of precedence:
1. MSBuild external projects
2. Sibling directories
3. Search paths from global.json using the order they are listed in within the global.json file

Disallowing any duplicates would be safer, but it would be difficult for the user to solve in some scenarios.

**Comment by rajivharris** [comment]
Currently I dont have much in my global.json 

global.json
`{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-update1"
  }
}
`

**Comment by rrelyea** [comment]
This issue appears to be from before the move from Project.json to msbuild PackageReference. If something is still painful, please open a new issue with details.
