### ISSUE TITLE
NuGet install command doesn't go to compressed blobs

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2311]
## Run

nuget version: 3.4.0.653
nuget.exe install microsoft.aspnet.webapi.client
## Expected
1. Request headers have gzip/deflate
2. Response is compressed
## Actual
1. Request headers have gzip/deflate (good)
2. Response is not compressed see headers below:

```
HTTP/1.1 200 OK
Cache-Control: no-store
Content-MD5: LW2zPla/gZs/Mj3iwBN9sA==
Content-Type: application/json
Date: Sun, 13 Mar 2016 02:56:30 GMT
Etag: 0x8D23AD938EF4481
Last-Modified: Wed, 01 Apr 2015 21:23:25 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-CDN-Rewrite: Lowercase blobs in v3-flatcontainer
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 77ac6a4e-0001-002a-61d3-7cfce1000000
x-ms-version: 2009-09-19
Content-Length: 75222
```
## Expected encoding is missing from result

```
Content-Encoding: gzip
```

CC @maartenba @johnataylor @emgarten

**Comment by yishaigalatzer** [comment]
Justin assigning to you to start investigating, this could be server issue or a client issue.

**Comment by emgarten** [comment]
I investigated this earlier in the week. Gzip is only available through the 3.4.0 endpoint which has not yet been added to `https://api.nuget.org/v3/index.json`.  @johnataylor has a test account containing an updated service index which enables this.

**Comment by johnataylor** [comment]
Marrten's [pull request](https://github.com/NuGet/NuGet.Services.Index/pull/24) fixes this

**Comment by maartenba** [comment]
It has just been deployed. Take into account that the blob is cached for a few minutes, you should be able to test drive in a bit.

**Comment by yishaigalatzer** [comment]
Reassigned to you, please validate and close

**Comment by maartenba** [comment]
Verified and working. Latest `dev` version.

## Run

nuget.exe install microsoft.aspnet.webapi.client

## Expected
1. Request headers have gzip/deflate
2. Response is compressed

## Actual
1. Request headers have gzip/deflate
2. Response is compressed (served from `https://api.nuget.org/v3/registration1-gz/microsoft.aspnet.webapi.client/index.json`) and has the `Content-Encoding: gzip` header

```
HTTP/1.1 200 OK
Content-Encoding: gzip
Cache-Control: no-store
Content-MD5: qFjPBmq+BX68WttCIB/3QA==
Content-Type: application/json
Date: Tue, 15 Mar 2016 15:18:30 GMT
Etag: 0x8D34BF90C19EA0E
Last-Modified: Mon, 14 Mar 2016 11:09:01 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-CDN-Rewrite: Lowercase blobs in v3-flatcontainer
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: bf23ecac-0001-0058-74cd-7e8ddf000000
x-ms-version: 2009-09-19
Content-Length: 3129
```
