### ISSUE TITLE
nuget.exe on linux: This method must be implemented in derived classes

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#2312]
Using the latest nuget.exe from the download page, I can't install anything. Getting a 'This method must be implemented in derived classes' (see below).

Ubuntu 14.04, Linux sunra 3.19.0-51-generic #58~14.04.1-Ubuntu SMP Fri Feb 26 22:02:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

gmc@sunra:~/bin/nuget$ mono --version
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
gmc@sunra:~/bin/nuget$ mono nuget.exe 
NuGet Version: 3.3.0.212
usage: NuGet <command> [args] [options] 
Type 'NuGet help <command>' for help on a specific command.

Available commands:

 add         Adds the given package to a hierarchical source. http sources are not supported. For more info, goto https://docs.nuget.org/consume/command-line-reference#add-command.

 config      Gets or sets NuGet config values.

 delete      Deletes a package from the server.

 help (?)    Displays general help information and help information about other commands.

 init        Adds all the packages from the <srcPackageSourcePath> to the hierarchical <destPackageSourcePath>. http feeds are not supported. For more info, goto https://docs.nuget.org/consume/command-line-refer
             ence#init-command.

 install     Installs a package using the specified sources. If no sources are specified, all sources defined in the NuGet configuration file are used. If the configuration file specifies no sources, uses the de
             fault NuGet feed.

 list        Displays a list of packages from a given source. If no sources are specified, all sources defined in %AppData%\NuGet\NuGet.config are used. If NuGet.config specifies no sources, uses the default NuG
             et feed.

 locals      Clears or lists local NuGet resources such as http requests cache, packages cache or machine-wide global packages folder.

 pack        Creates a NuGet package based on the specified nuspec or project file.

 push        Pushes a package to the server and publishes it.
             NuGet's default configuration is obtained by loading %AppData%\NuGet\NuGet.config, then loading any nuget.config or .nuget\nuget.config starting from root of drive and ending in current directory.

 restore     Restores NuGet packages.

 setApiKey   Saves an API key for a given server URL. When no URL is provided API key is saved for the NuGet gallery.

 sources     Provides the ability to manage list of sources located in %AppData%\NuGet\NuGet.config

 spec        Generates a nuspec for a new package. If this command is run in the same folder as a project file (.csproj, .vbproj, .fsproj), it will create a tokenized nuspec file.

 update      Update packages to latest available versions. This command also updates NuGet.exe itself.

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference
gmc@sunra:~/bin/nuget$ mono nuget.exe install xunit.runners
Feeds used:
  https://api.nuget.org/v3/index.json

This method must be implemented in derived classes
gmc@sunra:~/bin/nuget$

**Comment by davidfowl** [comment]
Update to a newer mono

**Comment by ghost** [comment]
Ok, works fine with mono 4.2.2. Thanks.
