### ISSUE TITLE
Nuget api v3 failed to get meta data of my package

### ISSUE THREAD

**Issue by thang2410199** [NuGet/Home#2313]
In visual studio package manager, my package [Suto Navigation](https://www.nuget.org/packages/SutoNavigation/) display outdated version. In website and api v2 it display the package correctly.

If I install the package by using package console, it pulls the latest version, but without any meta data. "Not available at this source" message appear below my package name in "Installed" tab of the package manager.

If I switch to package source api v2, everything works.

**Comment by aloisdeniel** [comment]
Same problem here with [PdfRasterizer](https://www.nuget.org/packages/Xam.Plugin.PdfRasterizer/). It works with `v2` but not `v3`.

**Comment by yishaigalatzer** [comment]
Yes this was a known issue - see the status reports on the bottom of http://status.nuget.org/, should be resolved now
