### ISSUE TITLE
Dependencies targeting .NET 3.5 are installed to .NET 4.x projects

### ISSUE THREAD

**Issue by alextercete** [NuGet/Home#2315]
I'm trying to create a NuGet package that has different dependencies based on the target framework. Following [the documentation ](https://docs.nuget.org/create/nuspec-reference#specifying-dependencies-in-version-2.0-and-above), I declared the dependencies on my _.nuspec_ file like this:

```
<dependencies>
  <group>
    <dependency id="A" version="1.0.0" />
    <dependency id="B" version="1.0.0" />
    <dependency id="C" version="1.0.0" />
  </group>
  <group targetFramework="net35">
    <dependency id="D" version="1.0.0" />
  </group>
</dependencies>
```

The problem is that package `D` keeps being installed to .NET 4.x projects, no matter what!

I managed to "fix" the problem by specifying an empty group targeting `net40` (I got the idea from some open source projects that seem to be doing the same):

```
<dependencies>
  <group>
    <dependency id="A" version="1.0.0" />
    <dependency id="B" version="1.0.0" />
    <dependency id="C" version="1.0.0" />
  </group>
  <group targetFramework="net35">
    <dependency id="D" version="1.0.0" />
  </group>
  <group targetFramework="net40" />
</dependencies>
```

Now `D` is only installed to .NET 3.5 projects, as expected.

Am I seeing the expected behavior here? Is there a documentation I'm missing?

**Comment by davidfowl** [comment]
That's by design. net35 means >= net35, which means a net40 project can consume it. It's best practice to isolate your dependency groups and generally avoid targetFramework less dependency groups.

**Comment by alextercete** [comment]
That explains the behavior I was experiencing -- which, by the way, I **didn't** fix by introducing an empty dependency group targeting `net40`, as I just realised the common dependencies weren't being installed.

Just to confirm, is the following how it's supposed to look like?

```
<dependencies>
  <group targetFramework="net40">
    <dependency id="A" version="1.0.0" />
    <dependency id="B" version="1.0.0" />
    <dependency id="C" version="1.0.0" />
  </group>
  <group targetFramework="net35">
    <dependency id="A" version="1.0.0" />
    <dependency id="B" version="1.0.0" />
    <dependency id="C" version="1.0.0" />
    <dependency id="D" version="1.0.0" />
  </group>
</dependencies>
```

I was using the `targetFramework`less group in the hope of preventing duplication of the common dependencies.

**Comment by davidfowl** [comment]
Yes. That's how it should be done. The duplication is a bit unfortunate but it drastically simplifies the selection logic

**Comment by alextercete** [comment]
Fair enough. Thanks!
