### ISSUE TITLE
Create a Mono TFM

### ISSUE THREAD

**Issue by kevinchalet** [NuGet/Home#2320]
_Copied from https://github.com/aspnet/dnx/issues/2118:_

_We want to create a TFM for DNX on Mono: dnxmono. It should probably be tied to Mono version. It should also inherit from a dnx (desktop CLR) TFM._

_We'll want to get this in to NuGet as well._

---

Having a Mono-specific TFM would help fix this kind of issues: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/179#issuecomment-155884377.

**Comment by yishaigalatzer** [comment]
There would be no more DNX TFMs going forward, everything is going to be .NETStandard based. 

So I don't follow what is the exact ask here, can some take the time write up an exact spec/ask?

**Comment by kevinchalet** [comment]
There are actually many types that Mono doesn't have (like `ECDsa`, as discussed in the thread I mentioned), which prevents a project using them from compiling or running correctly (a `TypeLoadException` is thrown at runtime). Having a Mono TFM would make conditional compilation (`#ifdef mono`) possible.

**Comment by yishaigalatzer** [comment]
But how is that related to DNX? Is the scenario that you want to use the xproj project system to build for mono runtime scenarios? 

As far as I know we don't plan to support mono as a .net cli runtime environment, so the only conclusion I have is that this to support cross compilation?

What exactly is the expected hierarchy of TFMs? It cannot depend on dnxXXX because these are obsolete and gone. So what is it going to follow exactly?

We need the mono platform owners to jump in and work on a design here.

**Comment by kevinchalet** [comment]
I simply copied the thread as-is, but of course, it would need to be adapted to the new CLI environment since DNX is dead. I changed the title to make that clearer.

> As far as I know we don't plan to support mono as a .net cli runtime environment

That's the whole point of this thread.

> So the only conclusion I have is that this to support cross compilation?

Not only cross compilation, since it would only solve half of the problem: we'd still see `TypeLoadException`s at runtime.

**Comment by kevinchalet** [comment]
> So what is it going to follow exactly?

I'd say the corresponding .NET Desktop TFM: e.g mono44 -> net461.

**Comment by csharpfritz** [comment]
Isn't dnx on Mono just a runtime?  Shouldn't this run the same as dnx on Core or dnx on dotnet framework

**Comment by tim-cools** [comment]
:+1: This would makes things more clear as **mono** misses some important security features.

**Comment by nkolev92** [comment]
With netstandard and more recently NET5, the frameworks in .NET have taken a different direction so this issue is unnecessary. 
Closing
