### ISSUE TITLE
Nuget pack gives Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2323]
NuGet Version: 3.4.0.738

From microsoft corp network if you try to pack the package located here.
\joshking-main\dump\nugetpackissues\SourceDepotClient.2.8.0.0

d:\NuGetPackages\SourceDepotClient.2.8.0.0>d:\tfs\IS\ES\M\cbt\nuget\nuget.exe pack SourceDepotClient.nuspec
Attempting to build package from 'SourceDepotClient.nuspec'.
Object reference not set to an instance of an object.

This package is just an existing nuget package I installed and then with out change I tried to repack it.
It may be the nuspec is incorrect but if so I would expect some warning or error not an exception.

**Comment by toddm** [comment]
Thanks for reporting the issue.  It has been fixed in Dev and 3.4 RTM.
