### ISSUE TITLE
NuGet config documentation is not up to date

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2326]
Page: https://docs.nuget.org/consume/nuget-config-settings
Section: Source control integration

disableSourceControlIntegration setting is not true by default, and enabling auto restore of packages doesn't create .nuget folder

**Comment by kraigb** [comment]
This is fixed on https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file#solution-section. Thanks for pointing it out!

**Comment by kraigb** [comment]
@skofman1 can you verify the changes and close this issue? Thanks.
