### ISSUE TITLE
The ‘Select All’ checkbox on the Updates tab is hidden

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2336]
The ‘Select All’ checkbox on the Updates tab is hidden:

 ![3](https://cloud.githubusercontent.com/assets/8239356/13822607/883889ac-eb63-11e5-92c1-9f046b829f4a.jpg)

Until I select a package:

![4](https://cloud.githubusercontent.com/assets/8239356/13822613/9056ea20-eb63-11e5-9844-be9b9d9359b5.jpg)

**Comment by rrelyea** [comment]
merged fix into dev and release-3.4.0
