### ISSUE TITLE
PackageDependency set with targetFramework==null throws

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2337]
I noticed this when updating from my fork of NuGet pack code to the official bits.  I found that I could pass NuGetFramework.Any to get the behavior I wanted, but it seems like null should work.

/cc @toddm @emgarten

**Comment by yishaigalatzer** [comment]
@ericstj is this an API bug or a behavior bug for restore? (I assume API bug), I think null shouldn't be an input, but lets debate

**Comment by ericstj** [comment]
API bug. I don't mind since I'm not blocked here but it was something I noticed as "breaking" between previous code that was generating a nuspec and latest.  I had to do a bit of searching in the source to discover I could pass any.

**Comment by emgarten** [comment]
NuGet.Core.dll used null or string.empty to mean 'any' target framework. In NuGet v3 we've moved away from this and use an actual NuGetFramework to pass around 'any'.

For this API we could convert null into NuGetFramework.Any to keep compatibility with the old behavior.

**Comment by yishaigalatzer** [comment]
I wouldn't, instead just document the expected values in an XML doc, and make it easy to understand. Also make it throw right at the callsite an argument exception (if it doesn't already)

**Comment by toddm** [comment]
Updated the XML doc.
