### ISSUE TITLE
[Nuget.ProjectModel] Bug in XprojUtility line 65: wrong dependencies collection is used

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#2341]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/XProjUtility.cs#L65 
It loops through spec.Dependencies (which are only top level), but not over a combined dependency collection it created above (containing dependencies form top and target frameworks)

**Comment by yishaigalatzer** [comment]
@emgarten we need this fix, this week and prerrably ASAP to unblock @abpiskunov

**Comment by emgarten** [comment]
NuGet/NuGet.Client@c9e301849983c83ef109308e8146d63f4cbe815b
