### ISSUE TITLE
VS2015 extension ignores <title> and always shows <id>

### ISSUE THREAD

**Issue by dakrer** [NuGet/Home#2343]
The VS2013 extension correctly shows the title in the "Manage NuGet Packages for Solution..." dialog, but the VS2015 extension completely hides the title and only shows the id

This happens both in 3.3 and 3.4-rc.

**Comment by yishaigalatzer** [comment]
This is by design, the id correctly represents the package, where the title can be spoofed. We heard strong feedback from the community about this confusion and made the change.
