### ISSUE TITLE
NuGet prompts to enter credentials when there is a private feed even when installing from NuGet.org

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2346]
Scenario:
I have a private feed that required credentials, and also NuGet.org in the feed list (both enabled).
When searching in NuGet.org using package manager, and trying to install a package, there is a prompt to enter credentials even though the package public.
If I fail to enter credentials, package install fails, and so do following install attempts.

**Comment by yishaigalatzer** [comment]
CC @pspill

**Comment by alpaix** [comment]
Fixed with previous changes. Closing...
