### ISSUE TITLE
Push - It should be possible to override the symbol server when pushing from the command line

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2348]
Related: https://github.com/NuGet/Home/issues/2204

The code currently wants to auto-push symbols to https://nuget.smbsrc.net/. There is no way to override it. The only thing that can be done is to delete the *.symbols.nupkg before pushing the *.nupkg.

There should be a way to specify an override for the symbol server, something like:
nuget.exe push foo.nupkg /Source foo /SymbolSource bar /SymbolApiKey xxx

**Comment by spadapet** [comment]
I added new switches for the push command: -SymbolsSource and -SymbolsApiKey

**Comment by harikmenon** [comment]
Can you open a PR on the docs with the change, we will merge it in when appropriate

**Comment by spadapet** [comment]
NuGetDocs PR: https://github.com/NuGet/NuGetDocs/pull/480
Fix that up as necessary, I don't know all the places the docs need to be updated
