### ISSUE TITLE
NuGet internationalization: switch-off required

### ISSUE THREAD

**Issue by jochenwezel** [NuGet/Home#2352]
To support tools based on NuGet, it's required to analyse the output messages of NuGet by these tools (e.g. the CreateNewNuGetPackage). 

The problem is on non-English systems that NuGet automatically logs every message in the supported language - making it very difficult to analyse NuGet output messages (required lot of internationalization work on those depending projects).

For simplifying development for those tools depending on NuGet output messages, an additional command line parameter/switch would be great to disable internationalization of output messages and to just output everything with messages in English language.

Example:
NuGet.exe pack niceApp.csproj -ForceEnglishUI

**Comment by deadlydog** [comment]
Yes, yes, yes please! Great idea :+1:

**Comment by yishaigalatzer** [comment]
@joelverhagen - I think this will take some reflection magic, but I think it is doable by iterating all the loaded assemblies finding the resource managers (flaky I know) and forcing the `resourceCulture` variable to English

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/451.

Per the original request...

> NuGet.exe pack niceApp.csproj -ForceEnglishUI

We chose to make the option name `-ForceEnglishOutput`.

**Comment by jochenwezel** [comment]
absolutely great! :+1: 

One additional question because most depending tools are developed to support older Visual Studio versions, too.

> NuGet feed v2 (VS 2013 and earlier / NuGet 2.x)

If I understand it correctly, NUget 3.5 will be available only for VS2015 or higher because earlier VS versions depend on NuGet 2.x.
Are these changes also visible to VS <= 2013 ?

**Comment by yishaigalatzer** [comment]
These changes are only for nuget.exe, not inside visual studio. We are unable to make these in visual studio proper without a deeper discussion and approvals from the visual studio team.

We are not planning on further investments in 2013 other than critical bug fixes or major blocking issues like new target frameworks.

**Comment by jochenwezel** [comment]
@yishaigalatzer Thank you for this information. I hoped a different result, but I understand your decision, too :-)

**Comment by alpaix** [comment]
Re-opening due to a bug reported by a customer in NuGet/NuGet.Client#451

**Comment by joelverhagen** [comment]
Closed because additional work is tracked here https://github.com/NuGet/Home/issues/3191.
