### ISSUE TITLE
Incorrect default tab selection behavior in Manage NuGet Packages dialog

### ISSUE THREAD

**Issue by scottaddie** [NuGet/Home#2353]
The version of NuGet Package Manager being used is 3.3.0. Refer to the following screen capture for context around this issue:

![nuget_browse_tab](https://cloud.githubusercontent.com/assets/10702007/13857071/3829dc20-ec46-11e5-8868-574ccc906e90.gif)

The package manager dialog seems to display the tab last selected when it opens. I'm proposing that this behavior change, such that the **Browse** tab is selected by default when opening the dialog from the context menu of a project which has no NuGet packages installed.

In the screen capture above, I would have expected the **Browse** tab to be selected by default when opening the dialog for the _ClassLibrary1_ project. Instead, the **Installed** tab was selected, which doesn't make sense since no _packages.config_ file is present in that project.

**Comment by yishaigalatzer** [comment]
We got the opposite feedback, and hence this selection. Typically when you click manage you want to update packages, or the like.

I can see this as an option in the nuget settings (default tab -> Last, Browse, Updates, Installed)

**Comment by scottaddie** [comment]
@yishaigalatzer I agree that it would be really nice to have a setting for this within Tools --> NuGet Package Manager --> Package Manager Settings.

**Comment by emgarten** [comment]
Closing due to lack of feedback to support this change.
