### ISSUE TITLE
Reexamine `type: platform`

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2355]
We either need to change include/exclude flags OR just have `type: platform` not set these flags and do the publish suppression in `dotnet-cli`.

The problem is when you have a graph like this:

```
    A
  /   \
 B     C
  \   /
    D
```

If B->D is marked as `exclude: runtime`, but C->D has no include/exclude flags, it is interpreted as including all and that overrides the B->D metadata

**Comment by emgarten** [comment]
This is no longer needed.
