### ISSUE TITLE
nuget.exe pack (and pack tests in NuGetPackCommandTest) fail to build projects when Dev15 is installed.

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2356]
**Repro:**
1. Install latest Dev15 preview build on your dev machine (side-by-side with existing Dev14)
   \dogfoodvs\DOGFOOD\Dev15\InstallScriptsV2\InstallDev15.lnk
2. Run a full nuget.client build: .\build.ps1

**Result:**

![capture](https://cloud.githubusercontent.com/assets/2523431/13860874/be254c6e-ec47-11e5-9e22-d7f8708ce4b4.PNG)

NuGetPackCommandTest.cs(867,0): at NuGet.CommandLine.Test.NuGetPackCommandTest.PackCommand_NuspecFileWithTokens()
G:\nuget.client\test\NuGet.Clients.Tests\NuGet.CommandLine.Test\NuGetPackCommandTest.cs(919): error : NuGet.CommandLine
.Test.NuGetPackCommandTest.PackCommand_OutputDirectorySuffixes(suffix: "") [FAIL] [G:\nuget.client\test\NuGet.Clients.T
ests\NuGet.CommandLine.Test\NuGet.CommandLine.Test.csproj]
        Attempting to build package from 'proj1.csproj'.
        MSBuild auto-detection: using msbuild version '15.0' from 'C:\Program Files (x86)\MSBuild\15.0\bin'.
        Building project 'C:\Users\peterspa\AppData\Local\Temp\NuGetTestFolder\857a2553-5090-48b7-8e0e-fbc5ecfadd11\pro
  j1\proj1.csproj' for target framework '.NETFramework,Version=v4.0'.
        __________________________________________________
        Project "C:\Users\peterspa\AppData\Local\Temp\NuGetTestFolder\857a2553-5090-48b7-8e0e-fbc5ecfadd11\proj1\proj1.
  csproj" (default targets):

C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB4127: The "Csc" task could not be instantiated from the assembly "C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.Build.Tasks.CodeAnalysis.dll". Please verify the task assembly has been built using the same version of the Microsoft.Build.Framework assembly as the one installed on your computer and that your host application is not missing a binding redirect for Microsoft.Build.Framework. Unable to cast object of type Microsoft.CodeAnalysis.BuildTasks.Csc to type Microsoft.Build.Framework.ITask.
**C:\Program Files (x86)\MSBuild\15.0\bin\Microsoft.CSharp.Core.targets(67,5): error MSB4060: The "Csc" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name.**
Done building project "proj1.csproj" -- FAILED.

Failed to build 'proj1.csproj'.

**Comment by toddm** [comment]
This is not limited to Pack.  It seems to be a test issue but I'm still trying to prove that definitively.

**Comment by toddm** [comment]
I got it to repro using a Dev15 dev cmd prompt.  Still investigating what the cause is.

**Comment by toddm** [comment]
This happens when doing a -build during pack when the command-line will use MSBuild 15.

**Comment by rrelyea** [comment]
Do we understand the fix?

**Comment by toddm** [comment]
Not really, no.  I do know that using MSBuild 14 instead of 15 is a reasonable workaround.
We might need to build NuGet.exe referencing/using MSBuild 15 but that's not a simple thing to do and it might not be backward compatible with 14 if we do.
