### ISSUE TITLE
All sources "browse" can hit a null ref, and continually retry

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2363]
My configuration is two Klondike servers, one accessed via localhost and the other via remote request to a VM.
Both of them have ~5 different packages, with a few versions in common, etc...

Browse via All sources...and you'll see an error with Null Ref in output for package manager.

@alpaix is investigating.

**Comment by rrelyea** [comment]
:shipit: (after a bit more testing of other scenarios to ensure no regression)

**Comment by jslew** [comment]
I don't know if this is related, but trying to browse  a remote Klondike (v1.6.2) server using VS2015 Update 2, I get the following error:
[MyRepository] The V2 feed at 'http://nuget.myrepo.com/api/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=false&$skip=0&$top=26' returned an unexpected status code '404 Not Found'.

Updating to 3.4.1 did not help.

**Comment by alpaix** [comment]
@jslew Does the Package Manager enter infinite retry loop in your scenario? Can you please elaborate and/or share a printscreen?

**Comment by jslew** [comment]
I created a different issue to track what I am seeing, it turned out to be unrelated.
https://github.com/NuGet/Home/issues/2435
