### ISSUE TITLE
Prevent package push to public repository

### ISSUE THREAD

**Issue by jozefizso** [NuGet/Home#2367]
Does NuGet client and Nuspec have ability to prevent pushing packages to public repositories? We use corporate NuGet server and we would like to have our internal packages marked as private, or be able to set only allowed push sources (servers).

**Comment by yishaigalatzer** [comment]
We are planning to deprecate nuget.exe push without a source, so packages do not get pushed accidentally to nuget.org. Is this a sufficient solution?

(This is already the case in NuGet 3.4)

**Comment by jozefizso** [comment]
I have found the [`DefaultPushSource` config value](https://docs.nuget.org/consume/nuget-config-defaults#default-nuget.exe-push-source). A well placed `NuGet.config` file will prevent our internal packages to be pushed to public nuget.org service.

I would love to be able to define the source directly in `nuspec` file but I think this config value will be sufficient.
