### ISSUE TITLE
"All" is the default package source when multiple package sources are enabled

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#2370]
"All" is the default package source when multiple package sources are enabled. This is true even without user opting for "All" package sources.

**Comment by rrelyea** [comment]
I think PackageManagerControl.xaml.cs line 494 should change from PackageSources.FirstOrDefault();
to:
                // use the first enabled source as the active source by default, but do not choose "All sources"!
                SelectedSource = PackageSources.Where<PackageSourceMoniker>(psm => psm.SourceName != UI.Resources.AggregateSourceName).FirstOrDefault();

**Comment by rrelyea** [comment]
Fixed in dev. (will likely ship in 3.4.1)

**Comment by rrelyea** [comment]
Marking as 3.4.1 milestone...this fix shipped there.
