### ISSUE TITLE
Size also to be displayed in Package Description Window in Visual Studio

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#2375]
It would be good if size is also to be displayed in Package Description Window in Visual Studio.
![](https://cloud.githubusercontent.com/assets/16834561/13944572/2d2e59ba-f02c-11e5-9c31-86b3f44f2f27.png)

**Comment by yishaigalatzer** [comment]
That's a neat idea!

We spent some time looking into it and we currently don't have that information available in the metadata shared by the servers, so it is not guaranteed to be able to show it on all servers, and will require a protocol change to show up (for V3 servers, it is currently available for V2).

CC @maartenba - Lets track adding the data over to the registration blobs.

**Comment by maartenba** [comment]
Created tracking issue: https://github.com/NuGet/NuGetGallery/issues/2957

**Comment by emgarten** [comment]
Closing due to lack of feedback on this.

**Comment by clairernovotny** [comment]
Please re-open this.... we do want size in the v3 feed, there's people following https://github.com/NuGet/NuGetGallery/issues/2957 for it.
