### ISSUE TITLE
Incorrect import fallback behavior

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2377]
Import should be used as an "ultimate" fallback.  That is, it should only ever be considered after the targeted TFM and all compatible TFMs have been considered.

I'm seeing that this is not the case.

Consider the following project.

```
{
    "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-23922"
   },

    "frameworks": {
        "netstandard1.3": {
        }
    }
}
```

The project restores correctly.  Now if I add `"imports": [ "dnxcore50" ]` and restore I get a different result.

The diff can be seen here: https://gist.github.com/ericstj/b8f283c1c65011d53c09/revisions

The particularly concerning lines are things like https://gist.github.com/ericstj/b8f283c1c65011d53c09/revisions#diff-c1e5585bccc57e553af12dd3b1ef45f8L460

Where NuGet previously selected an exact-match asset for the _targeted framework_ and is now selecting an asset for TFM derived from the _imported framework_.

I know that this particular case is nonsense (portable TFM importing non-portable TFM) but it highlighted what looks like a serious issue in how import fallbacks are evaluated.

/cc @eerhardt @yishaigalatzer @davidfowl

**Comment by davidfowl** [comment]
That's hella broken.

**Comment by emgarten** [comment]
I'll take a look, this seems like a bug. Fallback should not occur if the target framework has any compatible assets for the group.

**Comment by emgarten** [comment]
I've checked in a fixed for this issue. ContentModel was not falling back properly when the imported framework was a higher version than the project framework. The whole scenario of falling back to a higher version is somewhat strange, but NuGet should handle it it correctly now.

NuGet/NuGet.Client@642bf92b8547b7bd62ac78ef4e9a87c0f8f24a47

**Comment by ericstj** [comment]
I'm still seeing this issue with the following project.json

```
{
    "dependencies": {
        "System.Collections.Immutable": "1.2.0-rc2-23922"
   },
    "frameworks": {
        "netstandard1.3": {
            "imports": [ "portable-net45+win8" ]
        }
    }
}
```

With the import I see the following in the lock file.

```
        "compile": {
          "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll": {}
        },
        "runtime": {
          "lib/portable-net45+win8+wp8+wpa81/System.Collections.Immutable.dll": {}
        }
```

Without the import I see

```
        "compile": {
          "lib/netstandard1.0/System.Collections.Immutable.dll": {}
        },
        "runtime": {
          "lib/netstandard1.0/System.Collections.Immutable.dll": {}
        }
```
