### ISSUE TITLE
dotnet CLI OS X CI builds failed

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2378]
This is the issue we saw before that blocked the Jenkins OS X CI for dotnet CLI. Two problems were observed:
1. Corrupt .nupkg (even after validating the file in the HTTP cache).
2. HTTP cache file not found.

We worked around the problem with `--disable-parallel` but the root cause still needs to be reproduced and investigated.

**Comment by emgarten** [comment]
@joelverhagen this fix is in right?

**Comment by joelverhagen** [comment]
I started a build this afternoon to test the latest bits and it looks like the problem still repro'd.
https://github.com/dotnet/cli/pull/2181
(notice the OS X build failed).

I ran my paralellism test against `HttpSource` (not the locking code itself) and still repro'd the issue.
Here's a PR applying the fixes we talked about offline:
https://github.com/NuGet/NuGet.Client/pull/444
