### ISSUE TITLE
Remove the locked property from the lock file

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2379]
project.lock.json has a locked property, that is not being consumed by anything. We should remove the property from the default writer.

CC @davidfowl

**Comment by glen35** [comment]
Where is that at please

**Comment by yishaigalatzer** [comment]
@glen35 don't understand the question

**Comment by emgarten** [comment]
NuGet/NuGet.Client@097349c2fd29cca768049451dd50b4d71f26cfb6
