### ISSUE TITLE
NuGet.VisualStudioExtension: Search results on a net45 project shows Microsoft.AspNet.Mvc.6.0.0-beta3

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#238]
NuGet.VisualStudioExtension: Search results on a net45 project shows Microsoft.AspNet.Mvc.6.0.0-beta3 which is not compatible with net45 project. This happens on nuget.org

**Comment by feiling** [comment]
This fix needs to happen on the server.

**Comment by yishaigalatzer** [comment]
We are not adding filtering support (at least not for now until more discussion happens)
