### ISSUE TITLE
Update-Package is failing on VS2015 

### ISSUE THREAD

**Issue by repl-shenoy-sukumaran** [NuGet/Home#2380]
I am getting below command to update-package to new version its fails with below error, If i use with Install-Package command everything is success. How do i get the full exception detail, its looks trimmed from Package manager console.

PM> Update-Package Replicon.Darkwater.Services.Contracts -Version 1.50.21.0 -IgnoreDependencies -Source Replicon -Project Replicon.Darkwater.UI
Attempting to gather dependencies information for multiple packages with respect to project 'Production\Replicon.Darkwater.UI', targeting '.NETFramework,Version=v4.0'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Update-Package : available
At line:1 char:1
- Update-Package Replicon.Darkwater.Services.Contracts -Version 1.50.21 ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

**Comment by repl-shenoy-sukumaran** [comment]
Not sure this is the right place to create this defect, or we should create in Package Manager console

**Comment by emgarten** [comment]
I am unable to repro this. please create a new issue if this still happens in vs 2017
