### ISSUE TITLE
Publish xml documentation in NuGet.Core package

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#2381]
Hi. The  [NuGet.Core package](https://www.nuget.org/packages/NuGet.Core/) is missing the xml documentation file `NuGet.Core.xml` that's needed by Visual Studio to show documentation in Intellisense. Please add it, even if it's incomplete, it would be helpful.

**Comment by hickford** [comment]
Follow http://stackoverflow.com/q/5205738/284795

**Comment by emgarten** [comment]
nuget.core is deprecated at this point.
