### ISSUE TITLE
Packages added via nuget.exe add cannot be restored on Linux \ OSX

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2383]
Repro steps:
- Build a package and publish it using `nuget.exe add -source $TESTDIR`
- Attempt to restore the package using `dotnet restore` (version  1.0.0-beta-001718)

Package will fail to restore. Using `dnu restore` to publish the package works in this instance. The issue is likely the path normalization that is done during `add`. The v3 local package repo has to account for this (https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Repositories/NuGetv3LocalRepository.cs#L54).

**Comment by emgarten** [comment]
NuGet needs to normalize on install also, this is still an issue there.

**Comment by emgarten** [comment]
Flat folders also have this issue.

**Comment by emgarten** [comment]
This should be fixed. Please yell if you are still hitting this.
