### ISSUE TITLE
Consider shipping a new version of 3.3 vsix that only supports vs2015

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2385]
Currently, VS vNext users can choose to install 3.3 vsix, as it has a different identity than 3.4 vsix for vNext. VS isn't happy with 2 versions of NuGet installed. 

We should consider updating 3.3 vsix to say it works on [14.0-15.0), like the 3.4 vsix for vNext now does.

**Comment by emgarten** [comment]
After discussing this in triage we decided not to go this route.
