### ISSUE TITLE
PackageRestoreTest.ps1 E2E tests have disabled since Dev12. Re-enable or Delete them

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#2387]
PackageRestoreTest.ps1 E2E tests have disabled since Dev12. Re-enable them or Delete them

Currently, they were disabled for Dev12 and Dev14. Will disable it for Dev15 as well.
Investigate and fix them all when this issue is fixed.

Code to remove is at https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/NuGet.Tests.psm1#L108

**Comment by emgarten** [comment]
@deepakaravindr is this fixed?

**Comment by heng-liu** [comment]
It's not enabled nor deleted. so reopen it.

**Comment by nkolev92** [comment]
Running as of https://github.com/NuGet/NuGet.Client/blame/b9657fd4665055429d15285c2c22ec081e4600b4/eng/pipelines/templates/pipeline.yml#L221.

**Comment by nkolev92** [comment]
nvm, the link is bad.
