### ISSUE TITLE
NuGet doesn't honor MinClientVersion

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2390]
We've seen lots of cases where folks are trying to install NETStandard packages with old clients and get errors like the package isn't supported for the platform (rather than the package needs a new NuGet client version).  Seems to me NuGet isn't doing minClientVersion check in Package Manager nor in Restore.  I'd expect it to happen in both places.

**Comment by emgarten** [comment]
nuget/nuget.client@0836ef72d6b89d033f11ff21703dd693aea32515

**Comment by niemyjski** [comment]
Is there a way to specify minClientVersion in project.json? I'm not finding it and we want to set it to 2.12 so it works on VS2012/VS2013
