### ISSUE TITLE
Incorrect nuget update behaviour for nuget CLI 3.3

### ISSUE THREAD

**Issue by melcloud** [NuGet/Home#2394]
When updating a single nuget package by id in 2.8.6 with command `nuget update -id myPackage MySolution.sln`, nuget will escape projects which **myPackage** is not installed:

```
Scanning for projects...
Found 10 projects with a packages.config file.
Looking for installed packages in 'packages'.
Updating 'blah.csproj'...
WARNING: Unable to find 'myPackage'. Make sure they are specified in packages.config.
```

However, in the latest version of nuget (3.3.0.212), the same command will **install** the nuget package!!!

```
Attempting to gather dependencies information for multiple packages with respect
 to project 'blah.csproj', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
For adding package 'MyPackage.version' to project 'blah.csproj' that t
argets 'net45'.
For adding package 'MyPackage.version' to project 'blah.csproj' that t
argets 'net45'.

Added package 'MyPackage.version' to 'packages.config'
Successfully installed 'MyPackage.version' to blah.csproj
```

Is there anyway to not do this by default?

**Comment by emgarten** [comment]
Update installs the package into all projects?

Would you try the latest nightly build of nuget.exe from: https://dist.nuget.org/index.html and see if this still repros for you?

**Comment by melcloud** [comment]
Hi emgarten,

Yes. that is correct. I tried the v3.4.0-rc which fixed this problem. However, when it updates package contains build target in build folder, it doesn't remove the old error condition. You can see from the below example, I updated package inin from _15.2.0.361_ to _15.2.0.362_. Nuget 3.4 and 3.5 nightly build correctly change the `Import Project` but didn't delete the old `<Error Condition="!Exists('..\packages\InIn.15.2.0.361\build\InIn.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\InIn.15.2.0.361\build\InIn.targets'))" />`

``` xml
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\InIn.15.2.0.361\build\InIn.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\InIn.15.2.0.361\build\InIn.targets'))" />
    <Error Condition="!Exists('..\packages\InIn.15.2.0.362\build\InIn.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\InIn.15.2.0.362\build\InIn.targets'))" />
  </Target>
  <Import Project="..\packages\InIn.15.2.0.362\build\InIn.targets" Condition="Exists('..\packages\InIn.15.2.0.362\build\InIn.targets')" />
```

**Comment by emgarten** [comment]
@melcloud thanks for verifying it is fixed in the latest build. The left behind errors is a known issue, you'll have to remove those manually until that is fixed.

**Comment by melcloud** [comment]
Great! I am going to use 2.xx for now as it works.
