### ISSUE TITLE
Add ability to mark nuget warnings as errors

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2395]
Today we warn for a couple of things:
- Minimum version getting bumped because it can't be found on a feed
- Downgrades
- Other stuff

It would be great if we could force a restore errors instead of a warnings for these things.

/cc @yishaigalatzer @emgarten

**Comment by rrelyea** [comment]
Needs design. Does it need to support individual warnings, etc...

**Comment by davidfowl** [comment]
@rrelyea We did this right?

**Comment by emgarten** [comment]
> We did this right?

This is complete and in CLI 2.0.0
