### ISSUE TITLE
.targets files installed are imported using relative path

### ISSUE THREAD

**Issue by damnlogin** [NuGet/Home#2398]
Hello

If NuGet package contains **build** directory inside - the .targets files present there are referenced in project using relative path when package gets installed. The issue is when we build that project on a build agent that has NuGet.config in the root of drive containing sources to redirect package location to some fixed place to avoid multiple copies of the package all over the drive.
If msbuild property **$(NuGetPackagesDirectory)** would be used instead - I would be able to override it prior build. But with current approach the only thing I can do is remove NuGet.config and accept multiple copies of packages for every solution built.

Looks like the way references are added to the project makes package location setting key in NuGet.config almost useless when it comes to practice.

For assembly references that have relative hint paths we created an MSBuild target that on the fly replaces them, but for project imports that is impossible.

**Comment by davidfowl** [comment]
A bunch of these problems are solved with `project.json` + csproj. Hopefully we'll move more projects over to this new model soon.

**Comment by damnlogin** [comment]
Thanks - but as far as I got from documentation - I can switch already referenced projects to json format right now - correct? Will the VS2015 package manager respect new settings when upgrading packages?
