### ISSUE TITLE
Simple project not compiling when using project.json

### ISSUE THREAD

**Issue by damnlogin** [NuGet/Home#2400]
Hello

I know this is not yet supported, but I will really appreciate if someone can check why the attached very simple project doesn't compile when using project.json. It does work fine though when using packages.config.

Looks like Fluent.Assertions package conflicts with System.dll although I do not see anything strange about the package.

**_Unfortunately I was not able to upload a zip - so I changed extension to .txt - please rename it to .zip._**

System Info:
_Visual Studio Enterprise 2015 Version 14.0.24720.00 Update 1
Microsoft .NET Framework Version 4.6.01055
NuGet Package Manager   3.3.0
Visual Studio Tools for Universal Windows Apps   14.0.24720.00_

Thanks in advance.

[Sample.txt](https://github.com/NuGet/Home/files/189587/Sample.txt)

**Comment by emgarten** [comment]
@damnlogin please paste your output log.

**Comment by damnlogin** [comment]
Hello, I figured out the reason: Microsoft.NuGet.targets ResolveNuGetPackageAssets target was removing duplicate references and that code contained an error - the reference was removed by its filename and System.Xml being a dependency in package caused System assembly to be removed from project dependencies instead as MSBuild treated .Xml as an extension. I fixed that replacing 

`<Reference Remove="%(_ReferencesFromNuGetPackages.FileName)" />`

with

`<Reference Remove="%(_ReferencesFromNuGetPackages.FileName)" Condition=" '%(_ReferencesFromNuGetPackages.Extension)' == '.dll' or '%(_ReferencesFromNuGetPackages.Extension)' == '.exe' " />`

**Comment by D3-LucaPiombino** [comment]
I know this is closed, 
but i wanted to share this, since i finally solved this (today) after wrestling with it for some time. 
This is related to #1880.

If you add the `IncludeFrameworkReferencesFromNuGet` element and set the value to `false` into the csproj, the problem goes away:

``` xml

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" ... >
  <PropertyGroup>
     [...]
      <IncludeFrameworkReferencesFromNuGet>false</IncludeFrameworkReferencesFromNuGet>
     [...]
```

**Comment by damnlogin** [comment]
Thanks, I agree - both solutions are about fixing system references coming from package.

**Comment by emgarten** [comment]
@jasonmalinowski would you take a look at where the problem is here?

**Comment by emgarten** [comment]
@damnlogin @D3-LucaPiombino Visual Studio 2015 Update 2 was released today with an updated build task, does the issue still repro there for you?

**Comment by damnlogin** [comment]
@emgarten, with new VS 2015 Update 2 issue is permanently gone. Should I close this one or you will? And thanks everyone for your help and time!

**Comment by jasonmalinowski** [comment]
Yep, this was bug #1880 and the fix went out in Update 2 yesterday. Good to know everything's working @damnlogin, sorry for the trouble!
