### ISSUE TITLE
Add an API to get the path to the global packages folder

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2403]
This is an ask by the dotnet CLI team so that they can depend on our code to find the global packages folder (rather that duplicating our logic which is prone to break in the future). This should be exposed in one of our existing `NuGet.*` packages.

Considerations:
1. The global packages folder can be relative. If it is, it is relative to the solution directory (not the location of the NuGet.config).
2. The value can come from a couple different places. The precedence is:
   1. The `NUGET_PACKAGES` environment variable.
   2. The `globalPackagesFolder` key in the settings.
   3. An OS-dependent machine-wide value (e.g. `%USERPROFILE%\.nuget\packages` for Windows)
3. The directory separators (`\` vs. `/`) be fixed up based on OS so that the caller does not have to do the fix up.

**Comment by emgarten** [comment]
Related to: https://github.com/NuGet/Home/issues/2296

**Comment by yishaigalatzer** [comment]
We also need this API for the build task to pick up

**Comment by emgarten** [comment]
The `NuGetPathContext` API handles this now.

NuGet/NuGet.Client@b5972d87fe8044843e4d4beb41d66807332ef226

**Comment by qbikez** [comment]
Why the requirement that `globalPackagesFolder` should be relative to the solution directory? This seems counter-intuitive to me and differs from `repositoryPath` behavior. When running `restore` from commandline, the global packages folder will be different depending on current working directory.

**Comment by emgarten** [comment]
@qbikez I agree and this behavior has been fixed for 3.5.0 RTM. `globalPackagesFolder` will be relative to the nuget.config file where it is defined now, the same as `repositoryPath`.
