### ISSUE TITLE
nuget pack -symbols: Missing source files

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#2407]
"nuget pack -symbols" only includes source files that are part of the project. However a .pdb file might contain extra files that are generated, (e.g. XAML, VB projects) or cross-linked from other projects.

If these files are missing, the debugging experience is impaired since the debugger can't locate the source files.

There are ready made solutions available (e.g. https://github.com/NuGet/NuGet2/pull/23, https://nuget.codeplex.com/SourceControl/network/forks/tomenglert/private/contribution/8243) that were never integrated. Instead all related issues (#304, #529) were closed as "won't fix".

However if it does no longer crash but still does not work is not a valid reason to close issues!

**Comment by yishaigalatzer** [comment]
@tom-englert no need to re-open copies of closed bugs. Feel free to comment on close bugs, we see the comments and discuss. In this case I reopened #304.

As a reminder your contribution was not meeting the requirements so it could to go into the product, and we spent weeks on it to bring it up to snuff. We did build most a solution, it was way too complex for what it does, and it was my judgement that after symbol source fixed the issue when a file is missing, the priority went way down.

I don't know that anyone is really debugging .g.cs files, but I'm open to continuing the discussion on https://github.com/NuGet/Home/issues/304
