### ISSUE TITLE
Incorrect resolution for System.AppContext

### ISSUE THREAD

**Issue by borgdylan** [NuGet/Home#2408]
When compiling something that depends on System.AppContext against net461, I am getting errors due to the fact NuGet prefers the reference assembly for netstandard1.3 rather than the net46 PCL facade. These facades are shipped by the framework itself as well as the corefx nuget packages. There I recomedn to prefer all net4*\* TFMs before trying teh netstandard1.\* TFMs. Failing to do so there would be two definitions of System.AppContext from mscorlib and the System.AppContext reference assembly for netstandard1.3.

**Comment by davidfowl** [comment]
Can you provide a repro project?

**Comment by borgdylan** [comment]
This was happening with NuGet 3.40. I have since then managed to build my mono variant of the .NET CLI successfully which self-hosts OK with NuGet 3.5
