### ISSUE TITLE
NuGet CLI Update only updates projects with every package Id specified

### ISSUE THREAD

**Issue by makhdumi** [NuGet/Home#2412]
If I run
`nuget.exe update <MySolution.sln> -Source <MyCustomSource> -Id <Package1> -Id <Package2> -Id <Package3> -Id <Package4> -Verbosity detailed`

Then nuget will only update projects that have all Package1, Package2, Package3, and Package4 installed,  instead of updating the packages wherever it finds them.

e.g. if ProjectA has Package1 and Package2 installed, it will be skipped
only ProjectB, which has Package1, Package2, Package3, and Package4 all installed will be updated.

It doesn't make sense that every project in a solution would have the same packages installed.

**Comment by emgarten** [comment]
What version of nuget.exe are you using?

You can get the latest nightly build here: https://dist.nuget.org/index.html

**Comment by makhdumi** [comment]
I'm using version 2.8 of nuget.exe.

I can't upgrade because of https://github.com/NuGet/Home/issues/2225

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
