### ISSUE TITLE
Visual Studio occasionally disregards disabled NuGet restore

### ISSUE THREAD

**Issue by joshfree** [NuGet/Home#2414]
Moving https://github.com/dotnet/corefx/issues/7130 here on behalf of @clockwork-muse

> > > > I haven't been able to completely repro this one, but VisualStudio is occasionally disregarding the unchecked "Allow NuGet to download missing packages" option.  IOW, the option is unchecked, but the build process still attempts to dial out to the server.
> > > > 
> > > > This happens consistently when I'm away from "home" (when I have no internet connection), but never when I'm at "home" and try to repro (via things like disconnecting from the wireless internet).  I _thought_ I had managed to with the following steps on my Windows 10 machine, but haven't gotten it to do it a second time:
> > > > 1. Make sure both options under "package restore" are checked.
> > > > 2. Build the project.  (Should dial out)
> > > > 3. Exit VisualStudio
> > > > 4. Set the computer to Sleep
> > > > 5. Wake computer
> > > > 6. Start VisualStudio
> > > > 7. Uncheck "Allow NuGet...."
> > > > 8. Attempt to build project.
> > > > 
> > > > When I'm "away" it still attempts to dial out, which of course results in a failed build (because it can't contact the server).  This is a little bizarre, because in trying to repro this I attempted to do things like give it permission to dial out and turn of my network... and it completed fine.  So no clue what I'm running into here.  My best guess is it may be something in the timing between steps 4 and 5 (ie, travel time).
> > > > It's also a little strange, because I can build okay via command line by disabling restore there, but VisualStudio will still refuse to honor the unchecked option (which means I have a terrible time in-editor).
> > > 
> > > ...Just hit it again, but still can't repro.  Stuff I've done in VS before first offline build when this happens:
> > > - _nothing_ (just build/rebuild)
> > > - Change project file (ie, new test file)
> > > - Change method signature/attributes/declared variables.
> > > 
> > > So yeah, still mystified
> > 
> > @Clockwork-Muse  what is your project type? Also what is exact VS and Update version?
> 
> @abpiskunov - This has happened to both PLINQ and Threading.Tasks (so regular .csproj), so I'm assuming it would affect all of the corefx projects.
> VS is 10.0.24720.00 Update 1
> 
> It can also occur if I build the project, don't shut down VS, sleep the computer, then wake and try to build again.  Trying to rebuild via command line (with `/p:RestorePackages=false`) was complaining about not finding the correct version of System.Runtime.InteropServices.RuntimeInformation (I think - it's behaving now)

**Comment by yishaigalatzer** [comment]
@clockwork-muse can you point me to what projects you are restoring? Do they have nuget.exe in the build script?

**Comment by Clockwork-Muse** [comment]
@yishaigalatzer - I've been working on the System.Linq.Parallel and System.Threading.Tasks subprojects for [dotnet-corefx](https://github.com/dotnet/corefx).  NuGet.exe is in the build script(s), although it may be imported by [dotnet-buildtools](https://github.com/dotnet/buildtools).

**Comment by yishaigalatzer** [comment]
I'm guessing that's because the build process might be calling nuget.exe. The values are for blocking visual studio UI from downloading packages directly.

When you get it again can you capture a fiddler trace, and look at the user-agent header for the request? It will indicate if it comes from nuget.exe (expected) or visual studio (not expected)

**Comment by Clockwork-Muse** [comment]
...I'll see what I can do to get set up for that, but it might be a while.

**Comment by Clockwork-Muse** [comment]
@yishaigalatzer - I get no user-agent.
It's dying during DNS lookup, since I don't have any connection.

I suspect you're probably right, though.

**Comment by yishaigalatzer** [comment]
I'll wait for further feedback or you can try some other tool that will tell you what exe initiated the call

**Comment by Clockwork-Muse** [comment]
Looks like it's blaming dotnet.exe, from the dotnetcli.  So yeah, using an external command, not the hosted one.

**Comment by emgarten** [comment]
I am unable to repro this in the latest bits.
