### ISSUE TITLE
Nuget fails when connecting to SSL private repo with a lot of packages

### ISSUE THREAD

**Issue by taschmidt** [NuGet/Home#2417]
We have a private repo that's locked down to HTTPS only.  When clicking on a specific package inside VS 2015 and monitoring requests in Fiddler, the first request appears to be successful and it gets back ~80 package versions (there are 146 total).  The request to fetch more then switches to HTTP for some reason and fails causing weird results in VS.  See the attached screenshot.

![image](https://cloud.githubusercontent.com/assets/228736/14149625/aa167b94-f66a-11e5-947f-c818e805a5e2.png)

I should also mention that I have v3.3.0.167 (currently the latest) of the Nuget Package Manager extension.

**Comment by yishaigalatzer** [comment]
@taschmidt - Looks like Artifactory itself is redirecting you to an http feed in the link it sends back, but there is no redirection on the server to accommodate for that

**Comment by taschmidt** [comment]
Holy crap, you're right... I totally missed that!

**Comment by taschmidt** [comment]
Oddly enough, doing a `nuget list` from the CLI seems to work since it doesn't appear to rely on a "next" link from the server!

**Comment by yishaigalatzer** [comment]
Yeah, list is a completely different implementation from nuget2, we have yet to consolidate it.
