### ISSUE TITLE
Update command might be a bit more verbose if i ask it to be so...

### ISSUE THREAD

**Issue by Piet-van-Bruggen** [NuGet/Home#2418]
A simple problem has cost me quite some headaches.. I used the NuGet commandline update command and supplied a solution to it... for some reason it seemed to work, but it didn't. 

If found out that there was a message like:

Scanning for projects...
Found N projects with a packages.config file.

And I found out that my solution had N+1 projects so that was my starting point... But what I tried to specify (Verbose, Verbosity) nothing showing me why it didn't update that one other project...

So I fetched the sources and searched a bit, then found this piece of code on line 162 of the file src\NuGet.Clients\NuGet.CommandLine\Commands\UpdateCommand.cs

```
    private MSBuildProjectSystem GetProject(string path, INuGetProjectContext projectContext)
    {
        try
        {
            return GetMSBuildProject(path, projectContext);
        }
        catch (CommandLineException)
        {

        }

        return null;
    }
```

The root cause of my problem is that for some unknown reason there was a second csproj file in the path of the project that was skipped. I'm not going to argue whether or not this should have been supported (the second project file was not in my solution), but at least a writeline of the exception to the console (maybe even only when in Verbose) would be nice ;)

**Comment by yishaigalatzer** [comment]
Yes, we completely agree with you.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/605.
