### ISSUE TITLE
NuGet xplat should pick up build 23930.0 of net core as new baseline

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2421]

**Comment by emgarten** [comment]
NuGet/NuGet.Client@438cb3699a8aa091e9d1b0cc154414634fd21bce

**Comment by joelverhagen** [comment]
This change is superceded by https://github.com/NuGet/NuGet.Client/commit/3b436f6f6b02f3dd116c9f9f2480bbd169551831, which has been verified.
