### ISSUE TITLE
Crash when browsing sources with invalid icon URL with NuGet 3.4.1.807

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#2423]
NuGet package browsing causes a crash in VS2015 U2 after upgrading the NuGet plugin to 3.4.1.807. Downgrading to Nuget 3.3.0.167 fixes the problem.

Steps to reproduce:
- Right click on a project, select "manage nuget packages".
- Click on the "browse" tab. Observe that browsing the 1st (default) remote works fine.
- Switch to a 2nd remote. Observe that Visual Studio crashes.

Crash message:

```
An unhandled exception of type 'System.Windows.Markup.XamlParseException' occurred in PresentationFramework.dll

Additional information: The URI prefix is not recognized.
```

System information:
- Windows 7 SP1 (x64) - fully patched
- VS2015 U2
- NuGet V2 source hosted on Artifactory Pro Power Pack 3.9.2 (rev. 30204) within corporate network.
- Proxy configured through "automatic configuration script" (internet explorer setting). HTTP_PROXY is not set.

**Comment by forderud** [comment]
My gut feeling is that this is authentication related. Unfortunately, I'm unable to debug the issue myself due to https://github.com/NuGet/Home/issues/2419.

**Comment by rrelyea** [comment]
This might be related to the Image URI for a package. We did some work to make the ScrollingList deal with images more efficiently. (this checkin: https://github.com/NuGet/NuGet.Client/commit/dfab17961845b05fdf597a621b6580d55e1efdbb) 

If that is the case, if we could determine the package that causes this problem...we can likely adapt the code to deal with that case.

Perhaps you could remove this change from your private build, build retail...and see if this repros?

**Comment by yishaigalatzer** [comment]
@forderud can you try and get all the packages from the second feed, and put them in a local file folder. See if that crashes as well. If so can you get us the package that triggers the crash?

You can also just extract all the nuspec files and find the package that perhaps has a non standard image url

**Comment by forderud** [comment]
Thanks for very helpful suggestions @rrelyea and @yishaigalatzer. The crash was indeed caused by a package with invalid icon URL. The icon url was `ttp://www.ge.com/sites/all/themes/ge_2012/favicon.ico`, where `h` was missing from `http`.

Would it be possible for you to somehow harden the code in question to more gracefully deal with icon loading failures?

**Comment by forderud** [comment]
@alpaix thanks a lot for fixing this issue. I really appreciate it.
