### ISSUE TITLE
Write and publish documentation for NuGet.Core.dll

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#2425]
Hi. I couldn't find any documentation for [NuGet.Core](https://www.nuget.org/packages/NuGet.Core/) "1,530,729 downloads" beyond [one blog post](http://blog.nuget.org/20130520/Play-with-packages.html from 2013). Is there any more comprehensive documentation? If I've missed it, please could you link it from the package page? Otherwise, think about writing some.

See also http://docs.writethedocs.org/writing/beginners-guide-to-docs/#why-write-docs

> You have written a piece of code, and released it into the world. You have done this because you think that others might find it useful. However, people need to understand why your code might be useful for them, before they decide to use it. Documentation tells people that this project is for them.
> - If people don’t know why your project exists, they won’t use it.
> - If people can’t figure out how to install your code, they won’t use it.
> - If people can’t figure out how to use your code, they won’t use it.
> 
> There are a small number of people who will source dive and use any code out there. That is a vanishingly small number of people, compared to people who will use your code when properly documented. If you really love your project, document it, and let other people use it.

**Comment by yishaigalatzer** [comment]
We don't plan to do any more work on nuget.core, it is pretty much as is, nor do we plan to document it further.

We do plan to work on document the new nuget set of packages, the work is not starting immediately but is tracked here: https://github.com/NuGet/Home/issues/2243

**Comment by hickford** [comment]
Which are the 'new set' of packages? Does one of them replace NuGet.Core?

**Comment by hickford** [comment]
Would you at least add NuGet.Core.xml to the package so Intellisense shows some documentation? https://github.com/NuGet/Home/issues/2381

**Comment by yishaigalatzer** [comment]
We stopped investing in nuget.core, but adding an XML might work.

There is no direct replacement to nuget.core, depending on what you are trying to do we might be able to suggest a path
