### ISSUE TITLE
Installing nuget package with two part version number from old 2.x nuget server fails

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2431]
Using 3.5.0.1106 nuget.exe
http://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.5.0-beta-1106

repo share: \joshking-main\dump\nugetissue\x

**Nuget.exe list AjaxControlToolkit -source https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Curated/nuget/v3/index.json**
AjaxControlToolkit 7.1213

**Nuget.exe list AjaxControlToolkit -source http://SQLISNuGet/DPG-Curated/nuget**
AjaxControlToolkit 7.1213

**nuget.exe restore packages.config -source https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Curated/nuget/v3/index.json -PackagesDirectory %cd%\temp**
Restoring NuGet package AjaxControlToolkit.7.1213.0.
Adding package 'AjaxControlToolkit.7.1213.0' to folder 'd:\dump\nugetissue\x\temp'
Added package 'AjaxControlToolkit.7.1213.0' to folder 'd:\dump\nugetissue\x\temp'

NuGet Config files used:
    C:\Users\joshking\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    C:\Users\joshking\AppData\Local\NuGet\Cache
    C:\Users\joshking.nuget\packages\
    https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQL_Curated/nuget/v3/index.json

Installed:
    1 package(s) to packages.config projects

**nuget.exe restore packages.config -source http://SQLISNuGet/DPG-Curated/nuget -PackagesDirectory %cd%\temp**
Restoring NuGet package AjaxControlToolkit.7.1213.0.
Please provide credentials for: http://SQLISNuGet/DPG-Curated/nuget
UserName: WARNING: Unable to find version '7.1213.0' of package 'AjaxControlToolkit'.
  C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
  C:\Users\joshking.nuget\packages: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
  http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.

Errors in packages.config projects
    Unable to find version '7.1213.0' of package 'AjaxControlToolkit'.
      C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
      C:\Users\joshking.nuget\packages: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
      http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.

NuGet Config files used:
    C:\Users\joshking\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    C:\Users\joshking\AppData\Local\NuGet\Cache
    C:\Users\joshking.nuget\packages\
    http://SQLISNuGet/DPG-Curated/nuget

**Comment by kingerja** [comment]
Breaks on 4 part versions. as well.  I am guessing the new version of nuget.exe is not intended to be compatible with the old 2.x nuget servers if the packages do not conform to the semver rules.

d:\dump\temp\nuget\x>nuget.exe restore packages.config -source http://SQLISNuGet/DPG-Curated/nuget -PackagesDirectory %cd%\temp
Restoring NuGet package AjaxControlToolkit.7.1213.0.
Restoring NuGet package AjaxMin.5.14.5506.26202.
Please provide credentials for: http://SQLISNuGet/DPG-Curated/nuget
UserName: WARNING: Unable to find version '5.14.5506.26202' of package 'AjaxMin'.
  C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxMin.5.14.5506.26202' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
  C:\Users\joshking.nuget\packages: Package 'AjaxMin.5.14.5506.26202' is not found on source 'C:\Users\joshking.nuget\packages\'.
  http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.

Please provide credentials for: http://SQLISNuGet/DPG-Curated/nuget
UserName: WARNING: Unable to find version '7.1213.0' of package 'AjaxControlToolkit'.
  C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
  C:\Users\joshking.nuget\packages: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
  http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.

Errors in packages.config projects
    Unable to find version '5.14.5506.26202' of package 'AjaxMin'.
      C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxMin.5.14.5506.26202' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
      C:\Users\joshking.nuget\packages: Package 'AjaxMin.5.14.5506.26202' is not found on source 'C:\Users\joshking.nuget\packages\'.
      http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.
    Unable to find version '7.1213.0' of package 'AjaxControlToolkit'.
      C:\Users\joshking\AppData\Local\NuGet\Cache: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking\AppData\Local\NuGet\Cache'.
      C:\Users\joshking.nuget\packages: Package 'AjaxControlToolkit.7.1213.0' is not found on source 'C:\Users\joshking.nuget\packages\'.
      http://SQLISNuGet/DPG-Curated/nuget: Cannot prompt for input in non-interactive mode.

NuGet Config files used:
    C:\Users\joshking\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    C:\Users\joshking\AppData\Local\NuGet\Cache
    C:\Users\joshking.nuget\packages\
    http://SQLISNuGet/DPG-Curated/nuget

**Comment by yishaigalatzer** [comment]
1. Can you share the packages.config file?
2. What version of nuget.server are you using?

**Comment by kingerja** [comment]
everything I used for the repo is located below. (the packages.config is located at that share as well.)  You can access it from Microsoft corp net.
\\joshking-main\dump\nugetissue\2431

The exact nuget commands I used are bolded above.  If you need any repo access to test this out let me know.

**Comment by kingerja** [comment]
A very old version this is before the 3.0 redo so it is closer to the 2.x codebase.

NuGet.Server.3.0.0-ctp3
--a-- W32i   DLL   -   3.0.51211.706 shp     51,888 12-17-2014 nuget.server.dll

**Comment by emgarten** [comment]
I don't recognize NuGet.Server 3.0.0-ctp3 as a release. Would you try the latest version (2.11) from nuget.org and see if you can repro this there?

The 3.5.0 client should request the normalized package version first, then if no results are turned it will fall back to FindPackagesById and get the matching package version itself from the list.

**Comment by yishaigalatzer** [comment]
@kingerja ping

**Comment by kingerja** [comment]
Sorry for the delay I got caught up in other things.

I tried updating to 2.10.3 (the latest nuget.server I could find on nuget.org)
It did not repro so it appears this issue is fixed in later 2.x builds.

Thanks
