### ISSUE TITLE
Nuget.CommandLine package is out of date -- current 3.3.0 version causes "NuGet.exe pack" to overwrite targetFramework with "unsupported0.0"

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#2433]
I create a .nuspec file with

```
    <dependencies>
      <group targetFramework=".NETStandard1.5">
        <dependency id="Microsoft.NETCore.App" version="[1.0.0-rc2-23930, )" />
            <dependency id="Microsoft.CodeAnalysis" version="[2.0.0-beta1, )" />
      </group>
    </dependencies>
```

and then I compile it with `nuget.exe pack` (using the nuget.exe that comes from the latest version 3.3.0 of the NuGet.CommandLine nuget package).
## What I expect:

This should produce a .nupkg which contains a .nuspec which has the same targetFramework
## What I get:

Actually, if you look inside the resulting .nupkg, it has replaced my targetFramework with

```
<group targetFramework="Unsupported0.0">
```

which makes it unusable by dotnet-cli. I don't know why it replaced it in this way, and I don't know how to fix it.

**Comment by ljw1004** [comment]
(if the underlying issue is that I'm using an out-of-date version of NuGet.exe, then please upload a new NuGet.CommandLine package which contains an appropriate newer version of it!)

**Comment by yishaigalatzer** [comment]
Yes, you are using an out of date package, we will upload a new one today or tomorrow. In the meantime go to our dist.nuget.org/index.html and grab the nightly build.

**Comment by ljw1004** [comment]
Hey, maybe we could re-open this issue and use it to track the workitem to update the NuGet package? (or is there a different tracking item?)
