### ISSUE TITLE
Support runtimeTargets in msbuild task that resolves nuget package assets

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#2436]
NuGet now supports exposing runtime assets from packages that don't have runtime specific dependencies. That is, packages with RID specific assets are now exploded into the lock file. We need to decide what the msbuild task does with these assets. Does it copy all of them to the output like .NET CLI? If you specify a RID, should it pick the right ones and flatten it in the output?

/cc @emgarten @jasonmalinowski @anurse

**Comment by jasonmalinowski** [comment]
> That is, packages with RID specific assets are now exploded into the lock file.

I feel like I'm back in my college math classes where the clarification didn't clarify anything. Can you clarify further? (Sorry, it's Friday and the weather outside is beautiful.)

The behavior of the task today is:

1) If you specify an RID, we copy that RID's assets. You must have that runtime in your restore.
2) If you don't specify an RID, we don't copy anything. Tough luck.

The challenge with "copy all" would be there's no real well-defined pattern for doing that in the output path for traditional projects. Obviously the .NET CLI tooling can, because it can invent new things. But we have existing things already doing that.

**Comment by emgarten** [comment]
Copy all would need to add sub folders for the top level RIDs that are automatically selected right? If everything is just copied into the same folder there would be conflicts.

**Comment by jasonmalinowski** [comment]
Yes, it'd have to be subfolders. But nothing about the rest of the entire MSBuild pipeline would know about those subfolders. The MSBuild design is very much "you are building for a specific platform", and if you want two platforms, you build twice.

**Comment by davidfowl** [comment]
I don't think there needs to be a copy all FWIW, the CLI has this but its ok if the msbuild task doesn't support it right now. What would be nice is if you specified a RID and the lock file does not have a RID specific target, but the RIDless target has rid specific assets, they should still get copied. 

To illustrate:

**System.Globalization.Extensions**

```
ref/netstandard1.3/System.Globalization.Extensions.dll
ref/netstandard1.3/System.Globalization.Extensions.xml
runtimes/unix/lib/netstandard1.3/System.Globalization.Extensions.dll
runtimes/win7/lib/netstandard1.3/System.Globalization.Extensions.dll
```

**System.Globalization.Extensions** will have a runtimeTargets section in the RIDless target, that specifies all of the RID specific assets:

``` JSON
"System.Globalization.Extensions/4.0.1-rc2-23931": {
  "type": "package",
  "dependencies": {
    "System.Globalization": "4.0.11-rc2-23931",
    "System.Resources.ResourceManager": "4.0.1-rc2-23931",
    "System.Runtime": "4.1.0-rc2-23931",
    "System.Runtime.Extensions": "4.1.0-rc2-23931",
    "System.Runtime.InteropServices": "4.1.0-rc2-23931"
  },
  "compile": {
    "ref/netstandard1.3/System.Globalization.Extensions.dll": {}
  },
  "runtimeTargets": {
    "runtimes/unix/lib/netstandard1.3/System.Globalization.Extensions.dll": {
      "assetType": "runtime",
      "rid": "unix"
    },
    "runtimes/win7/lib/netstandard1.3/System.Globalization.Extensions.dll": {
      "assetType": "runtime",
      "rid": "win7"
    }
  }
}
```

Specifying win7 should copy the win7 specific asset to the output folder.

**Comment by jasonmalinowski** [comment]
Maybe the real question I have is "what's the difference between this and just targeting the runtime with a runtime target", as it applies to the project types we see in the MSBuild world? What's the benefit for the newer/different model? What does it mean to be targeting a RID that you didn't list?

(I'm not fighting back on implementing this; I just don't understand what this changes to have any clue what I'm enabling or unblocking.)

**Comment by davidfowl** [comment]
> Maybe the real question I have is "what's the difference between this and just targeting the runtime with a runtime target", as it applies to the project types we see in the MSBuild world?

The idea would be that msbuild would be able to use the single target + an inferred or specified RID to get all of the assets. In the case of the inferred RID, you would do this if the user didn't specify anything. Users wouldn't need to understand RIDs up front.

> What's the benefit for the newer/different model? What does it mean to be targeting a RID that you didn't list?

This is where build time/publish time RID inference comes in. The basic idea is to avoid having to specify RIDs where possible. We've implemented this in the CLI for .NET Framework apps and for .NET Core apps, we do a "publish all" Any CPU style deployment. In this model, the Core CLR host picks the most appropriate RID at runtime.

/cc @pakrym @anurse
