### ISSUE TITLE
Package source missing after upgrade to 3.4.1.807

### ISSUE THREAD

**Issue by ndouthit** [NuGet/Home#2437]
The nuget.org package source is removed after upgrading to 3.4.1.807. I had to manually add it in order for the package manager to start working again. I can downgrade to 3.3.0.167 and the package source is no longer missing.

I'm using VS 2015 Community.

**Comment by emgarten** [comment]
thanks @ndouthit 
This has been added to the known issues list: http://docs.nuget.org/release-notes/known-issues
