### ISSUE TITLE
Package add wrong reference when a library item with the same name exists in the project

### ISSUE THREAD

**Issue by HugoLemieux** [NuGet/Home#2438]
If you have a library item in a project with the same name as the referenced library added by a package, the package successfully install but the reference is targeting the library item in the project rather than the library inside the package.

**Comment by emgarten** [comment]
@HugoLemieux would you give an example and some repro steps?

**Comment by HugoLemieux** [comment]
In Visual Studio:
1. Create a new library project named with the same name as a known added library by a known package (ex.: NuGet.Core)
2. Build it
3. Create another library project
4. Add the first compiled library as an existing item in the second project
5. Add the known package (ex.: NuGet.Core) to the second project

The reference of the second project added by the known package is targeting the existing library item inside the second project.

**Comment by emgarten** [comment]
This behavior is correct. Projects and packages are treated the same by NuGet, and they must have unique names.

In your example you have: (Project) B -> (Package) B 
If you then pack project B into a nupkg or consume that project from another project you will have: (Project) A -> B -> B

**Comment by HugoLemieux** [comment]
I understand that projects and packages are treated the same by NuGet and that they must have unique names.

I do not understand why the reference added by a package is targeting the wrong library.

From the example your are giving me with the project B, I am not sure I was clear enough to make my point. 

I have made a Visual Studio solution to illustrate the problem but I am not able to send it even in a ZIP file type.

In a Visual Studio project, I am able to add as an item as many libraries with the same name I want as long as they are not in the same project folder. Since I am also able to add one reference with the same name of any items within the project, I expect to be able to add one package adding one reference having the same name of any items within the project.

Can you confirm me that this behavior is correct even if the collision name occurs between the reference added by the package and the existing items inside the project?
