### ISSUE TITLE
FindPackagesById casing changes in 3.4.1 breaks Artifactory integration

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#2439]
Prior to NuGet 3.4, NuGet used a `FindPackagesById()?id='<name>'` query to search for package versions. With NuGet 3.4.1 this changed to `FindPackagesById()?Id='<name>'`. The subtle change in casing have utterly broken NuGet support in Artifactory (https://www.jfrog.com/jira/browse/RTFACT-9741) and possibly other case-sensitive servers.

To restore compatibility, could it be possible to change the `Id` field casing back to `id`?

**Comment by zhili1208** [comment]
Yes,  We just found this issue, I already change it back to id in one PR, it will be fixed after merge

**Comment by Kanimozhi12** [comment]
When the fix will be available. Whether it will be a Hot fix or update?

**Comment by zhili1208** [comment]
it will be released by the end of this week

**Comment by Kanimozhi12** [comment]
Hi ,

Now the installtion is working fine. But am unable to update NuGet packages from custom feed.Am getting the below error please look into this and provide solution ASAP.

**The V2 feed at 'http://{custom feed link}/FindPackagesById()?id='Microsoft.Owin.Security.Facebook'' returned an unexpected status code '403 Forbidden'.**

**Comment by zhili1208** [comment]
@Kanimozhi12 Hey, I tried this package on my test artifactory server but didn't repro this issue. is this working in 3.3?

**Comment by forderud** [comment]
This bug was introduced in NuGet 3.4.0 and later fixed in NuGet 3.4.2. It does therefore not affect NuGet 3.3.

**Comment by Kanimozhi12** [comment]
When am trying to update using 3.3 it asks to check the private feed link whether its proper or not. but the installation works well with the same feed.
