### ISSUE TITLE
Path to project package - why it is relative?

### ISSUE THREAD

**Issue by kreuzerkrieg** [NuGet/Home#2441]
This issue was already risen on codeplex, however I didnt find this issue here. 
The original link https://nuget.codeplex.com/workitem/8337
Since I dont see it is addressed one way or another I repost it here:
Looks like the path to package's props and targets used in project's file is pointing to the solution folder. Example: 
<Import Project="..\Solutions\packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props" Condition="Exists('..\Solutions\packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props')" /> 
Now, lets say this import is in my infrastructure project which resides in infra solution and, what a surprise, its gonna be used in numerous application solutions. These application solutions are not going to stick to the same folder structure as infra solution did. So at the moment I include my infra project in application solution the path "..\Solutions\packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props" is no more relevant. 
From my experience staring at nuget imports in various project files it always means $(SolutionDir)\packages...\ so it looks wrong to try and use relative path instead of using macros. Meanwhile I manually search and replace relative paths to mocro'ed one, like: <Import Project="$(SolutionDir)packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props" Condition="Exists('$(SolutionDir)packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props')" />. It solves the problem described above but gives me hard times when I try to update packages. The project file ends with multiple imports since nuget cant get it right. Example: 
<Import Project="..\Solutions\packages\cpprestsdk.2.4.0.1\build\native\cpprestsdk.props" Condition="Exists('..\Solutions\packages\cpprestsdk.2.4.0.1\build\native\cpprestsdk.props')" /> 
<Import Project="$(SolutionDir)packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props" Condition="Exists('$(SolutionDir)packages\cpprestsdk.2.4.0\build\native\cpprestsdk.props')" /> 

So, can we get our imports pointing to the right place using macros instead of relative paths? sounds this is the right thing to do in any case.

**Comment by emgarten** [comment]
The best answer for this is to change to project.json which has a global packages folder. You can see help for this here: https://oren.codes/2016/02/08/project-json-all-the-things/

SolutionDir may not work in all cases such as with a standalone csproj.

**Comment by kreuzerkrieg** [comment]
As I understand it doesnt work with native projects. checked it a minute ago with VS2015 Update 2, none of described in the link you've provided happened, so I guess the project.json works with managed project only.

**Comment by kreuzerkrieg** [comment]
@emgarten could you please reopen?

**Comment by kreuzerkrieg** [comment]
Thanks

**Comment by seangwright** [comment]
We have solved this issue (with non-.net Core projects) on our team by having everyone on the team set their `~\AppData\Roaming\NuGet\NuGet.Config` to have this same `<config>` block with a defined `repositoryPath` value.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositoryPath" value="c:\dev\projects\packages" />
    </config>
        ...
</configuration>
```

It doesn't matter what the path is as long as it is defined. Then all of our projects are cloned from Git to a directory with the same relative path to the `repositoryPath` defined in `NuGet.Config`.

Our solution files are at the top level of every project repository so we can use the macro mentioned above (`$(SolutionDir)`) to have our `HintPath` in our `.csproj` references point to the same packages location for all projects in all solutions.

This works but... it's a wacky and restrictive solution.

I know in the [Nuget 3 Explanation](http://blog.nuget.org/20151008/NuGet-3-What-and-Why.html) blog post it was mentioned that there would be a Global Packages folder (I imagine like `npm`) but it seems this is for `project.json` (and whatever `project.json` might turn into in the future) supporting projects. 

This means .net Core only, right?

Will our full .net framework .sln/.csproj projects ever be able to use Nuget in a 'add a package and forget it' manner or will the hoops described above remain tricks of the trade for all who are not (or cannot) move to .net Core?

Thanks for all the work btw, I love what Nuget has done for the .net community.

**Comment by emgarten** [comment]
At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by seangwright** [comment]
@emgarten One step ahead of you - I've been migrating my company's projects over the past month to either the new VS2017 project system or at least to `PackageReference` if they are a project type not supported by the new VS2017 project system (ex: full framework ASP.Net apps).

I've run into a few issues but so far they've all been resolvable. Of course there is a non-trivial set of packages out there that do not work correctly using `PackageReference` (https://github.com/aspnet/EntityFramework6/issues/189)

**Comment by emgarten** [comment]
@sgwatgit glad to hear it! EntityFramework is probably the most common blocker, but we are working on improving this and making it easier to migrate. If you hit any other blockers feel free to open an issue on it.
