### ISSUE TITLE
'Error occurred' when browsing for PCL or Xamarin (Mono) packages

### ISSUE THREAD

**Issue by artkat** [NuGet/Home#2442]
Browsing for PCL [https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='portable45-net45+win8+wp8+wpa81'&includePrerelease=false&$skip=0&$top=26'](https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search%28%29?$filter=IsLatestVersion&searchTerm=''&targetFramework='portable45-net45+win8+wp8+wpa81'&includePrerelease=false&$skip=0&$top=26')
or Mono (Xamarin) packages [https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='monoandroid60'&includePrerelease=false&$skip=0&$top=26'](https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search%28%29?$filter=IsLatestVersion&searchTerm=''&targetFramework='monoandroid60'&includePrerelease=false&$skip=0&$top=26') results in "The request is invalid".
![image](https://cloud.githubusercontent.com/assets/3071447/14231957/e072397e-f9c8-11e5-8daf-abae346854f6.png)

**Comment by artkat** [comment]
Reverted back to Package manager v3.3.0.167: No issues. Confirming the issue is with v3.4.1.807

**Comment by gannonlawlor** [comment]
Same issue here

**Comment by maartenba** [comment]
@artkat Can you see the URL that is requested in v3.3.0.167?

**Comment by emgarten** [comment]
It looks like ``&targetFramework`` is being added inside the search query string, instead of to the url.

**Comment by artkat** [comment]
Used Fiddler to monitor the NuGet Package manager requests and results:
There are clearly differences in the request.
This time, only one time I got the 'Error Occurred' message, but the results are very different between v3.3 and v3.4.1

NuGet 3.4.1 Searching for 'mvvmcross' with target Android
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search()?$filter=IsLatestVersion&searchTerm='mvvmcross'&targetFramework='monoandroid60'&includePrerelease=false&$skip=0&$top=26 
Results: None

NuGet 3.3 Searching for 'mvvmcross' with target Android
https://api-v2v3search-0.nuget.org/query?q=mvvmcross&skip=0&take=26&prerelease=false&supportedFramework=MonoAndroid,Version=v6.0 
Results: Many

NuGet 3.4.1 Searching for 'json' with target Android
https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Search()?$filter=IsLatestVersion&searchTerm='json'&targetFramework='monoandroid60'&includePrerelease=false&$skip=0&$top=26
Results: first time 'Error'
2nd time: 2 results

NuGet 3.3 Searching for 'json' with target Android
https://api-v2v3search-0.nuget.org/query?q=json&skip=0&take=26&prerelease=false&supportedFramework=MonoAndroid,Version=v6.0 
Results: Many (over 30)

**Comment by emgarten** [comment]
@artkat thanks for the traces. It looks like your feeds have changed. Instead of searching nuget.org you are now searching the .NET curated feed (a subset of nuget).

Try this: close all instances of Visual Studio, then delete `%AppData%\NuGet\NuGet.Config` 
Next re-open Visual Studio and try your search again.

More info can be found on: http://docs.nuget.org/release-notes/known-issues

**Comment by artkat** [comment]
@emgarten: That seems to do the trick ;-)
Not sure why v3.4.1 would change the feed to the .NET curated feed.
