### ISSUE TITLE
Nuget is popping up the ErrorList at beginning of every build...

### ISSUE THREAD

**Issue by clovett** [NuGet/Home#2450]
VS is supposed to show the Output window at the beginning of a build, but nuget is overriding this behavior which is not what users want.  This is happening here:

> ```
>            Microsoft.VisualStudio.ErrorListPkg.dll!Microsoft.VisualStudio.ErrorListPkg.Shims.ErrorList.Microsoft.VisualStudio.Shell.Interop.IVsErrorList.BringToFront() Line 147                C#
>            Microsoft.VisualStudio.Shell.14.0.dll!Microsoft.VisualStudio.Shell.ErrorListProvider.BringToFront() Line 816                C#
>             NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.MessageHelper.ShowError(Microsoft.VisualStudio.Shell.ErrorListProvider errorListProvider, Microsoft.VisualStudio.Shell.TaskErrorCategory errorCategory, Microsoft.VisualStudio.Shell.TaskPriority priority, string errorText, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy hierarchyItem)  Unknown
>             NuGet.Tools.dll!NuGetVSExtension.ProjectRetargetingHandler.ShowRetargetingErrorTask(System.Collections.Generic.IEnumerable<string> packagesToBeReinstalled, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy projectHierarchy, Microsoft.VisualStudio.Shell.TaskErrorCategory errorCategory, Microsoft.VisualStudio.Shell.TaskPriority priority)                Unknown
>             NuGet.Tools.dll!NuGetVSExtension.ProjectRetargetingHandler.ShowWarningsForPackageReinstallation(EnvDTE.Solution solution)              Unknown
>             NuGet.Tools.dll!NuGetVSExtension.ProjectRetargetingHandler.BuildEvents_OnBuildBegin.AnonymousMethod__0()                Unknown
>             mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<NuGetVSExtension.ProjectRetargetingHandler.(ref 
> ```

**Comment by emgarten** [comment]
Are there restore errors? Or are you seeing an empty error list?
