### ISSUE TITLE
For security reasons DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/Home#2454]
I am getting the issue like below image when using my private NuGet.

![image](https://cloud.githubusercontent.com/assets/17586319/14276657/4a594d12-fb3d-11e5-9602-20d8ad9be775.png)

How to ged rid of this

**Comment by yishaigalatzer** [comment]
Can you give us some more details? What is the server you are using? What version of the nuget client? Can you share a fiddler trace?

**Comment by yishaigalatzer** [comment]
ping, we want to wrap up a 3.4.2 release today and your feedback will be really helpful to nail this issue down.

**Comment by Kanimozhi12** [comment]
I have upgraded to latest version 4.1 issue is resolved . Now i have some other issues in using private feed url. Waiting for 4.2 release..let me know once released.

**Comment by yishaigalatzer** [comment]
Please let me know more details of your issue and feel free to email me for an early preview of 3.4.2 yigalatz@microsoft

**Comment by Kanimozhi12** [comment]
It has been discussed here https://github.com/NuGet/Home/issues/2439

**Comment by yishaigalatzer** [comment]
Sounds good, closing this issue
