### ISSUE TITLE
Push to symbol server often generates a 500 error

### ISSUE THREAD

**Issue by xoofx** [NuGet/Home#2455]
Hi there!

When trying to push NuGet symbols packages to https://nuget.smbsrc.net/, I often get a 500 error (like [here](https://ci.appveyor.com/project/xoofx/sharpscss/build/1.0.7) at the bottom). For the past years I have been using symbol source and I have often encountered this kind of issue. It is very annoying...

A couple of questions:
- Who is in charge of this service? 
- Is there any known issues about this?
- What could be done to improve the service?

Thanks!

**Comment by yishaigalatzer** [comment]
The service is not owned by NuGet, @tripleemcoder is the owner, please reach out to him directly.

**Comment by xoofx** [comment]
> The service is not owned by NuGet, @tripleemcoder is the owner, please reach out to him directly.

@yishaigalatzer thanks, well, that's the problem I would like to talk then :sweat_smile: 

NuGet.exe generates this symbol package (typically by default when using `project.json`) and when we push it NuGet.exe automatically push to `https://nuget.smbsrc.net/` so whenever there is a problem with this service, everybody using NuGet is impacted because almost everybody is pushing their symbols to this service.

So from a user point of view, this service is not really "external". Couldn't Microsoft take the responsibility of it, in partnership with @TripleEmcoder?

**Comment by yishaigalatzer** [comment]
The service is external, and we don't plan to take ownership for it.We might at some point build our own, but it is not on the immediate horizon.

We are adding a feature to push to avoid pushing symbol packages to smbsrc if you'd like not to push them or push them somewhere else.

**Comment by spadapet** [comment]
Look at this work item that adds a -NoSymbols option for push:
https://github.com/NuGet/Home/issues/2204

Here's the commit:
https://github.com/NuGet/NuGet.Client/commit/06312c8c0c59ef92c587779af443bb966ffaa83c

With that, you can choose to stop pushing symbols to that default server. You can push the symbol package somewhere else.

**Comment by xoofx** [comment]
Actually, I don't want to disable source-debugging-step-in, but ok, I assume that as SymbolSource/smbsrc.net is not supported, solutions like [GitLink](https://github.com/GitTools/GitLink) are the way to go now.

**Comment by FeodorFitsner** [comment]
You can also host symbol packages on MyGet: http://docs.myget.org/docs/reference/symbols

**Comment by yishaigalatzer** [comment]
Yes to what @FeodorFitsner said. The myget team added a symbol server support.

We are contemplating dropping the default symbol server support, but it is still useful even with the potential 500s coming from smbrc, so for now we decided not to drop the support.

@xoofx - GitLink is a pretty awesome way to got at it.

**Comment by xoofx** [comment]
> @xoofx - GitLink is a pretty awesome way to got at it. 

Yep, until they [support for project.json](https://github.com/GitTools/GitLink/issues/83) :sweat_smile:

**Comment by yishaigalatzer** [comment]
@xoofx love that you are using all the new stuff :)

xproj is not yet RTM, so lets give them some props for the great work they have done so far. Also side note, project.json is a bit misleading statement because there are two varieties (one with csproj and one that is either standalone or with xproj)

**Comment by TripleEmcoder** [comment]
Hi everyone, I'd like to chime in as the owner (or part of the owner duo to be precise).

We have had major issues before with SymbolSource, but smbsrc.net is running on code written from scratch, which should be quite reliable. What failed this particular time was the monitoring system, which did not alert us about upstream failure. I did some tuning to make sure this doesn't happen again.

I know there are other symbol solutions, and you are more than welcome to use them. Apart from those mentioned I also believe that ProGet is an option. What I believe is SymbolSource's strength is that it mirrors nuget.org packages, so when you need symbols for NHibernate, Autofac or any other mainstream project, you know where to look. This was our main goal from the beginning, and I believe it would be a setback for the community if we truly failed to deliver on that.

Having said that, we are of course open to discussion about help and support, as the project is run by us only part-time.

**Comment by niemyjski** [comment]
@TripleEmcoder it seems to be down again :(. @nuget team it would be great to throw some resources at @TripleEmcoder  and maybe join services... there is no way to not generate symbols with `dotnet pack` and with that said ci servers like appveyor automatically push all nuget packages (including symbols) his way... Also, you guys also push to him by default..

**Comment by TripleEmcoder** [comment]
@niemyjski I do deserve you jumping into conclusions... But the server seems healthy. 

I suspect this error is coming from your submission?

`08/06/2016, 16:02:23 - EXCEPTION
'Exceptionless' already has a dependency defined for 'Microsoft.CSharp'.
Exception type: System.InvalidOperationExceptionFailed method: NuGet.Manifest.ValidateDependencySetsProblem Id: System.InvalidOperationException at NuGet.Manifest.ValidateDependencySets`

Could you send me the package that is failing?

**Comment by niemyjski** [comment]
Your status page is also throwing an error :(, here is a link to all the artifacts: https://ci.appveyor.com/project/Exceptionless/exceptionless-net/build/artifacts

```
Publishing Exceptionless.4.0.1851-pre.symbols.nupkg to https://nuget.smbsrc.net/api/v2/package... 
Error publishing package. NuGet server returned 400: Bad Request
```

https://www.symbolsource.org/Public/Status (takes a really long time to come up and then has):
![screen shot 2016-06-08 at 10 13 14 am](https://cloud.githubusercontent.com/assets/1020579/15899529/a1f3f88c-2d61-11e6-8d3f-688fa17a82f3.png)

It's worth noting that these were all packaged via `dotnet pack` : https://github.com/exceptionless/Exceptionless.Net/blob/master/tools/Package.ps1#L19

**Comment by yishaigalatzer** [comment]
Can you guys take the discussion off the nuget client issue? :)

Get Outlook for Androidhttps://aka.ms/ghei36

On Wed, Jun 8, 2016 at 8:13 AM -0700, "Blake Niemyjski" <notifications@github.com<mailto:notifications@github.com>> wrote:

Your status page is also throwing an error :(, here is a link to all the artifacts: https://ci.appveyor.com/project/Exceptionless/exceptionless-net/build/artifactshttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fci.appveyor.com%2fproject%2fExceptionless%2fexceptionless-net%2fbuild%2fartifacts&data=01%7c01%7cyigalatz%40microsoft.com%7ca92d548ab09444358d4308d38faf7ad1%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=YbRe98SzO9Co29uqdKvCfA6fm9ICmllbo3zyTsHgyJg%3d

Publishing Exceptionless.4.0.1851-pre.symbols.nupkg to https://nuget.smbsrc.net/api/v2/package...
Error publishing package. NuGet server returned 400: Bad Request

https://www.symbolsource.org/Public/Statushttps://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fwww.symbolsource.org%2fPublic%2fStatus&data=01%7c01%7cyigalatz%40microsoft.com%7ca92d548ab09444358d4308d38faf7ad1%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=SpShvuqqtPUGb9nAKYDBxObfLw8bAOn9kvwSD5kCkv0%3d (takes a really long time to come up and then has):
[screen shot 2016-06-08 at 10 13 14 am]https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fcloud.githubusercontent.com%2fassets%2f1020579%2f15899529%2fa1f3f88c-2d61-11e6-8d3f-688fa17a82f3.png&data=01%7c01%7cyigalatz%40microsoft.com%7ca92d548ab09444358d4308d38faf7ad1%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=1I44gtrASnH0l66Yv0Xtrd4c3Fn106%2fONqfMi5%2fCZLI%3d

##
