### ISSUE TITLE
Auto add framework assemblies to nuget spec -a assy.dll

### ISSUE THREAD

**Issue by patrickgreenwell** [NuGet/Home#2457]
When building a NugetSpec from Assembly using `nuget spec -a MyAssembly.dll`

The generated .nuspec File should use reflection to List the referenced assemblies and add them to the frameworkAssemblies node in metadata.  

This will help solve any issues that would arise from missing dependencies needed by the assembly.

**Comment by yishaigalatzer** [comment]
Thanks for a cool idea.

We need to see if this is something that can be done reliably. We should probably limit it with a flag, so we don't enforce a breaking change to users.

Given our current backlog, this item doesn't fit high on the list, but we would gladly take a pull request if you want it promoted.

**Comment by emgarten** [comment]
Closing due to lack of takers on this up for grabs issue.
