### ISSUE TITLE
Port support for Klondike 2.0 server via uri redirection (odata)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2460]
Not sure which of these 2 we need:
- https://github.com/NuGet/NuGet.Client/commit/ea16486372d708c7d84a09af98ad7fd9c8804bc1
- https://github.com/NuGet/NuGet.Client/commit/7f8b4c1cdd4cff49dd7f8d302d0e56a525fee57c

**Comment by emgarten** [comment]
Merged to release-3.4.2 with NuGet/NuGet.Client@1e4eaede0ce4f9a5148d01aef64c55d93c1b63f8
