### ISSUE TITLE
NuGet cmd 3.5 beta packs whole project directory, wrong version

### ISSUE THREAD

**Issue by tomasz-soltysik** [NuGet/Home#2461]
NuGet Command Line 3.5.0-beta-1133 packs whole project directory and sets version to 1.0.0
for UWP library.
Tested with and without nuspec. Probably connected with project.json handling.

**Comment by emgarten** [comment]
@lion92pl does your project.json file contain a version property? Normally UWP projects do not, we are still designing how pack should work for both UWP and CLI projects which have slightly different project.json formats.

**Comment by tomasz-soltysik** [comment]
@emgarten No, my project.json contains only: dependencies, frameworks, runtimes.
Setting version in project.json fixes version part, but I think version from AssemblyInfo should be respected like in previous versions of NuGet cmd tool.
But what's more important, pack command still adds all files to package instead of only dll (like in previous versions).

**Comment by tomasz-soltysik** [comment]
Version is set in nuspec to `<version>$version$</version>`.
Also description is set in nuspec to `<description>$description$</description>` and it's also ignored. nuspec in packed nuget has description set to "Description" (during packing there is warning about it)

Warnings connected to packing whole directory:

```
WARNING: Issue: Assembly outside lib folder.
WARNING: Description: The assembly 'obj\Debug\something.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
WARNING: Solution: Move it into the 'lib' folder if it should be referenced.
```

**Comment by toddm** [comment]
Support for project.json just went in this week.  As you found, there is a bug that it ends up with default values for properties like version when it reads the json file and those were overriding the values from the project file.  I'm fixing that now.
Note that it now packs using the project file + project.json if it's there. We don't support project + json + nuspec so your nuspec file will be ignored if there is a project.json file.  You should be able to put all nuspec properties into the project.json file.
Please let me know if you see other bugs.  This hasn't had much testing on real projects yet.

**Comment by tomasz-soltysik** [comment]
I'm wondering what's the status of referenced pull request.  
Nothing happened to it for 7 last days.

**Comment by toddm** [comment]
I was out on vacation last week.  I'll try to finish this up today.

**Comment by toddm** [comment]
The Dev branch is frozen right now while we ship 3.4.3.  I'll be able to push this change when that lifts.

**Comment by toddm** [comment]
https://github.com/NuGet/NuGet.Client/commit/0021c1fde2fe47ae25de89ebde116f65ecbc2eb7
