### ISSUE TITLE
v3.4.1.807 of Nuget Pkg Mgr for VS2015 does not work with Artifactory

### ISSUE THREAD

**Issue by mgunter6** [NuGet/Home#2463]
I just installed v3.4.1.807 of Nuget Package Manager for VS 2015 which was released 3/30/2016. After doing so, Nuget Package Manager no longer works with packages exposed from my company's Artifactory server.

We run an in-house Artifactory Server which is set up to mirror all packages from the official nuget feed (I am not sure what technique is used to mirror these packages). I have VS2013 and VS2015 installed. I have no issues installing packages into my projects on VS2013 (running Nuget PM v2.8.60723.765).

In VS2015 (running Nuget PM v3.4.1.807), I can see all the packages from our Artifactory server in the Browse Tab. However, when I select a package, the Version dropdown is never populated, and hence, I cannot install these packages. Note that I did not change the nuget configuration between testing on VS2013 and VS2015.

Here is the issue shown in VS2015:
![vs2015-1](https://cloud.githubusercontent.com/assets/8250347/14301684/d4d337b2-fb67-11e5-9616-d0888c1200a9.png)

Here is the same package working fine in VS2013:
![vs2013-1](https://cloud.githubusercontent.com/assets/8250347/14301679/ce332368-fb67-11e5-907a-543d7bbaa9dd.png)
![vs2013-2](https://cloud.githubusercontent.com/assets/8250347/14301683/d144b6ca-fb67-11e5-9536-490ad8b21685.png)

Here is the nuget config (server names removed):
[NuGet.Config.txt](https://github.com/NuGet/Home/files/205562/NuGet.Config.txt)

**Comment by emgarten** [comment]
Dupe of https://github.com/NuGet/Home/issues/2439

**Comment by mgunter6** [comment]
Aha! Thank you, @emgarten.
