### ISSUE TITLE
Package add wrong reference when a library item with the same name exists in the project(#2438)

### ISSUE THREAD

**Issue by HugoLemieux** [NuGet/Home#2466]
I am opening a new issue for the #2438 which is now closed.

I understand that projects and packages are treated the same by NuGet and that they must have unique names.

I do not understand why the reference added by a package is targeting the wrong library.

From the example your are giving me with the project B, I am not sure I was clear enough to make my point.

I have made a Visual Studio solution to illustrate the problem but I am not able to send it even in a ZIP file type.

In a Visual Studio project, I am able to add as an item as many libraries with the same name I want as long as they are not in the same project folder. Since I am also able to add one reference with the same name of any items within the project, I expect to be able to add one package adding one reference having the same name of any items within the project.

Can you confirm me that this behavior is correct even if the collision name occurs between the reference added by the package and the existing items inside the project?

**Comment by yishaigalatzer** [comment]
Please share the project, so we can understand better.

**Comment by yishaigalatzer** [comment]
Also note that you can always ping us on a bug, and we will reopen, there is typically no need to create duplicates. We sometime close the bug because we think it is resolved (our bad), but we always listen to further comments/pings and reopen if necessary

**Comment by HugoLemieux** [comment]
I would be glad to be to share the project but I am not able to attach it.

When I select or drag and drop a ZIP file, I received this error message : Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

Is there any other way to share it?

**Comment by HugoLemieux** [comment]
I am sending you the screenshot of my VS solution showing that the reference added by the package NuGet.Core (this name is used as an example) is trageting the project item NuGet.Core.dll that was present in the project before but not as a reference.

Do not hesitate to ask me to show you any additional element not present in the screenshot.

![image](https://cloud.githubusercontent.com/assets/12341715/14350671/bedc141a-fc98-11e5-93d4-83a3f31fb1af.png)

**Comment by yishaigalatzer** [comment]
Thanks for coming back with more info,  unfortunately I still don't understand what exactly you are trying to do? Can you describe step by step what are you doing to get yourself in that state?

As for sharing you can share a zip file on dropbox.

**Comment by HugoLemieux** [comment]
I am trying to add or update a package that will add or update a reference targeting a library having the same name as an existing project item.

Here are the steps I have sended in the #2438 issue :
{
In Visual Studio:
1. Create a new library project named with the same name as a known added library by a known package (ex.: NuGet.Core)
2. Build it
3. Create another library project
4. Add the first compiled library as an existing item in the second project
5. Add the known package (ex.: NuGet.Core) to the second project
}

I have shared the zip file on dropbox at https://www.dropbox.com/s/4tuef8htttx1bfh/Test.zip?dl=0

**Comment by yishaigalatzer** [comment]
Thanks for the project and the repro steps!

This doesn't look like a NuGet issue but a core visual studio behavior. CC @AArnott 

Here are my repro steps:
1. Take your sample and remove the references and packages.config file
2. Right click on the references node and click Add Reference
3. Browse to packages\nuget.core and add nuget.core.dll
4. Expected: That dll gets added
5. Actually: The nuget.core.dll that is in the project gets added.

I'll follow up with folks in VS to see if this is an intended behavior or a bug.
