### ISSUE TITLE
During long running task if I close the Package Manager console window - I cannot open again.

### ISSUE THREAD

**Issue by onlyutkarsh** [NuGet/Home#2467]
In VS Package Manager Console, if you are running a long running task (or a task which is hung) and I close the package manager console (without stopping the task), I can no longer open "Package Manager console" via the menu. The menu item is greyed out.

![image](https://cloud.githubusercontent.com/assets/2685029/14322846/2c9de92a-fc16-11e5-825c-803767cb1bc4.png)

I also cannot open this window from "Command Window". I get 
"Command View.PackageManagerConsole is not available"

Restarting VS helps but I think VS should allow us to open "Package Manager Console" again so that we can stop the task.

**Comment by yishaigalatzer** [comment]
The thought here is to just close the window, but not to get rid of anything else. So showing up the window will just be a simple visual thing rather than killing it off completely.
