### ISSUE TITLE
Tools as a project reference

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#2469]
Currently, tools extensions can only be added as a package reference. This makes local development of tools and end to end testing cumbersome.
## Example scenario

Be able to reference a dotnet tool from a project in the same solution.

```
src/
     dotnet-ef
test/
     testProject/
          project.json <-- references dotnet-ef as a tool
```

``` json
{
    "tools": {
         "dotnet-ef": { "target": "project" }
    }
}
```
## Workaround

In the meantime, the inner dev cycle is to pack and restore the tool into the test project.

**Comment by yishaigalatzer** [comment]
@natemcmaster please write proper issues, I can't parse this

**Comment by natemcmaster** [comment]
@yishaigalatzer  not sure what you mean. Also, did you delete the content of my issue?

**Comment by yishaigalatzer** [comment]
Of course I didn't :) That's the point why I'm asking for more data

**Comment by natemcmaster** [comment]
Oh, weird. I typed out an explanation of the issue when I submitted. Must have been a weird networking error. I'll edit comment and re-write.

**Comment by natemcmaster** [comment]
@yishaigalatzer re-added content. Apologies for empty issue cc @githubstatus

**Comment by yishaigalatzer** [comment]
Thanks, the ask makes sense, I'm not sure how this will actually work because these tools are global so we might end up in contention here.

I'll start a design discussion

**Comment by NTaylorMullen** [comment]
Any update on this guy? I'm in the midst of building Razor tooling functional tests and I have to jump through a few hoops to work around this issue.

**Comment by jdom** [comment]
I'm also interested about this, since we'd like to use it in Orleans https://github.com/dotnet/orleans/issues/368

**Comment by rrelyea** [comment]
@piotrpMSFT after talking with @natemcmaster yesterday, we think this should be tracked as a CLI issue.
Make sense?

1) provide docs on best practices today to do development of a tool and debug, etc...
  (nate passes 3 params into dotnet.exe to run after building his tool, but skipping the need to pack, and restore the target prop)
2) consider doing better than what is possible today.

**Comment by TheRealPiotrP** [comment]
@brthor as well

This issue has been bouncing around for a while and it doesn't cleanly land in CLI or NuGet.

The NuGet ask here is that we need to enable restore to find P2P references for tools. Today, it is only able to restore tools if there is a nupkg available. Certainly there are many workarounds available to us but none of them are acceptable, at least of those which I've been exposed to.

**Comment by fearthecowboy** [comment]
I kinda needed this, so I hacked a not-completely terrible solution together for this.

I made a .proj file that gets included by the appropriate consuming projects that has an `InitialTargets` that points to a target that
- has a condition that only happens during `dotnet restore` and the tool isn't installed  `Condition="$(RestoreRecursive) AND !Exists('$(USERPROFILE)/.nuget/packages/.tools/dotnet-razor')` 
- If it's not, it ensures the tools project gets built and installed before the dotnet restore continues

see https://github.com/fearthecowboy/autorest/blob/coreclr/src/common/compile-cshtml.proj

**Comment by BrainCrumbz** [comment]
@fearthecowboy excuse me, link seems broken

**Comment by natemcmaster** [comment]
Closing. My request isn't relevant anymore now that MSBuild has replaced project.json.

**Comment by GiuseppePiscopo** [comment]
@natemcmaster is there a similar request for MSBuild-based projects, or such feature is already available in that scenario? Thanks

**Comment by natemcmaster** [comment]
There isn't such a request. I closed because in MSBuild we now use the `Exec` task to to invoke console tools as project references. Example: https://github.com/aspnet/KestrelHttpServer/blob/c83f606b220714fa7b1b6a6a91b16d78cee6005f/build/repo.targets#L2-L4 I don't think there is anything actionable here for NuGet.
