### ISSUE TITLE
Incorrect package version is used under NUGET_PACKAGES

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2471]
Nuget version used:
3.5.0.1139 shp  4,020,952 04-06-2016 nuget.exe

repro steps:
set NUGET_PACKAGES=d:_t
nuget install CommonServiceLocator -source https://api.nuget.org/v3/index.json
dir D:_t\CommonServiceLocator

Note the folder is 1.3.0
Note the package name is CommonServiceLocator.1.3.0.nupkg
Note the package version in the nuspec is 1.3

Also note the console output of that command is completely wrong stating 1.3.0.  Which is not the package version.
However at least it is installed correctly under the repositorypath to 1.3.

**Comment by emgarten** [comment]
This is by design. Versions are normalized to at least three digits, and four if the fourth digit is non-zero. This allows NuGet to determine exactly what the folder path will be without searching for all folders or trying to guess every form of the version with and without leading and trailing zeros.

Packages.config/repositoryPath is unable to change since those paths already exist as references in project files.

**Comment by emgarten** [comment]
Not also that NUGET_PACKAGES refers to the location of the global packages folder which is used as a packages cache for nuget.exe install. It is not expected to be the output path for nuget.exe install.

**Comment by daveaglick** [comment]
> Not also that NUGET_PACKAGES refers to the location of the global packages folder **which is used as a packages cache** for nuget.exe install. It is not expected to be the output path for nuget.exe install.

@emgarten Can you elaborate on this? It seems to contradict the discussion [here](https://github.com/NuGet/Home/issues/1406#issuecomment-141569881):

> %localappdata%\NuGet\Cache **Is a cache** - Means you can get packages from there instead of downloading them again. It is off in NuGet3, and we might want to bring it back, we didn't make that determination yet.
> %userprofile%.nuget\packages **is an install target** (or restore target depending who you ask), this is where packages are expanded to, so they get consumed by the projects.

**Comment by emgarten** [comment]
@daveaglick %localappdata%\NuGet\Cache is no longer used, packages are download first to %userprofile%.nuget\packages and then copied to their final destination. If the package already exists in %userprofile%.nuget\packages it will not be downloaded.

**Comment by daveaglick** [comment]
@emgarten Ah, okay. So am I correct that no matter what settings are used, packages will _always_ be copied to the project's local package path for use and a reference is added from that final destination? To put it another way, would NuGet ever add a project reference to an assembly that lives in %userprofile%.nuget\packages?

**Comment by emgarten** [comment]
@daveaglick that's correct. Project.json based projects use the dlls directly from %userprofile%.nuget\packages, packages.config projects will reference the solution level packages folder.

**Comment by daveaglick** [comment]
@emgarten That was super-helpful, thanks!
