### ISSUE TITLE
Install nuget.exe with an install of visual studio

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2473]
Customers would like to see nuget.exe installed as part of installing visual studio and having it in the path (or perhaps as part of the visual studio command line).
## Considerations
1. NuGet is not an msi installer, and is updating constantly, we need to figure out how we can safely bring nuget.exe without jeoperdizing out install pattern.
2. We need to figure out how to update it
3. Nuget.exe ships out of band to the vsix. We need to be in a mode where they can ship exactly at the same time, so they ship inside visual studio.
4. Similar to 3 - we need to figure out the update story for nuget.exe

**Comment by ghost** [comment]
:+1: on having one command line interface with just self-update option tapped into VS update notification center. Easy to maintain and less confusing when two different set of commands available doing the same thing: `nuget install <package>` (shell) <-> `install-package <package>` (visual-studio package-manager-console).
