### ISSUE TITLE
V2 requests don't encode URLs correctly

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2475]
Request in 3.4 (broken and not getting results):
`http://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm=''&targetFramework='portable45-net45+win8+wp8'&includePrerelease=false&$skip=0&$top=26`

Request in 3.3:
`https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&searchTerm=''&targetFramework='portable-net45%2Bwin%2Bwp80'&includePrerelease=false`

Needs encoding in the `targetFramework` parameter (`+` should be `%2B`)

(regression of http://nuget.codeplex.com/workitem/2886)

**Comment by rrelyea** [comment]
in release-3.4.2 and release-3.4.2-dev15. about to verify.
