### ISSUE TITLE
Need better --help doc on `dotnet restore --fallbacksource`

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#2477]
I had a lot of trouble trying to figure out the difference between:

`dotnet restore --source`
and
`dotnet restore --fallbacksource`

Looking at the `dotnet restore --help` didn't really help me learn what these two options do:

```
-s|--source <source>            Specifies a NuGet package source to use during the restore.
-f|--fallbacksource <FEED>      A list of packages sources to use as a fallback.
```

In reality, what I learned by talking to other developers is that:
1. --source will use only your specified source, and override any sources in your NuGet.config
2. --fallbacksource will append your specified source with what is in NuGet.config

The biggest trouble for me was the word `fallback`.  To me fallback seems to mean "only use this source if the other sources don't work". Or "use as a last resort".  But what it really means is "make this source just like any other source".

I think we should better explain these two options on `--help`, as I think that will go a long way in avoiding confusion in the future.

**Comment by yishaigalatzer** [comment]
Lets make sure this gets updated both for the xplat and the commandline

**Comment by emgarten** [comment]
This option is no longer part of dotnet.exe
