### ISSUE TITLE
Unable to install packages from own Artifactory

### ISSUE THREAD

**Issue by granak** [NuGet/Home#2478]
Hello,

I have problem with installation own (company) packages from our own artifactory after update VSIX to 3.4.1 (current latest 807) version. I am able to see list of packages, but I can't see version of particular packages. Also I'm not able to install package from console (error "Can't find metadata for {package-name}").
After downgrade to 3.3.0 version everything works fine.

Something was changed? Any ideas?

**Comment by yishaigalatzer** [comment]
I'm guessing this is a duplicate of - https://github.com/NuGet/Home/issues/2439 (it exposes a bug in Artifactory case sensitivity, but we decided to fix in NuGet client to avoid breaking behaviors with old servers.

Here is a link to a build (not the final release, and not localized) that should fix this issue. https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.2.821.vsix   

Please let us know if your issue got resolved

**Comment by granak** [comment]
@yishaigalatzer Thank you. The issue got resolved in this build.

**Comment by yishaigalatzer** [comment]
Wonderful! Thanks for validating.

**Comment by codekaizen** [comment]
+1 new build works for Artifactory again.
