### ISSUE TITLE
Can't install packages via Package Manager

### ISSUE THREAD

**Issue by klemmchr** [NuGet/Home#2479]
Hey guys,

currently I can't install some specific packages via the package manager interface. Some of these packages are:
- MVVM Light
- MahApps.Metro

What I already did:
- Restarting VS
- Restarting PC
- Changing the package source (like shown in the workaround)
- Creating a new Project/Solution

When I try to install the mentioned packages via Packet Manager Console it works fine so this issue only applies to the interface. 

Starting the interface it looks as usual:
![3dcf8152434dc5ea1c2159c7dc9bdad7](https://cloud.githubusercontent.com/assets/6552521/14352267/eddc0898-fcd3-11e5-8ed0-a4072e2756e4.png)

Searching for a package which is in the list of the recommended packages works fine:
![fad87f7d3a16efc6aa4d3c16471c2468](https://cloud.githubusercontent.com/assets/6552521/14352300/1c3df192-fcd4-11e5-9c57-586e8c7f2933.png)

Searching for a package which is not in the list doesn't works:
![19257878d087a3f81e6df631ef7379e8](https://cloud.githubusercontent.com/assets/6552521/14352333/454e714c-fcd4-11e5-9119-6c67279d5b02.png)

Installing the same package via the console works fine:
![20ff4dd0e412037bbd1c3409b6407fb2](https://cloud.githubusercontent.com/assets/6552521/14352444/e57bd63c-fcd4-11e5-8d15-368846d87154.png)

`
PM> Install-Package MahApps.Metro
Attempting to gather dependency information for package 'MahApps.Metro.1.2.4' with respect to project 'WpfApplication1', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'MahApps.Metro.1.2.4' with DependencyBehavior 'Lowest'
Resolving actions to install package 'MahApps.Metro.1.2.4'
Resolved actions to install package 'MahApps.Metro.1.2.4'
Adding package 'MahApps.Metro.1.2.4' to folder 'd:\onedrive\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'MahApps.Metro.1.2.4' to folder 'd:\onedrive\documents\visual studio 2015\Projects\WpfApplication1\packages'
Added package 'MahApps.Metro.1.2.4' to 'packages.config'
Executing script file 'd:\onedrive\documents\visual studio 2015\Projects\WpfApplication1\packages\MahApps.Metro.1.2.4.0\tools\install.ps1'
Successfully installed 'MahApps.Metro 1.2.4' to WpfApplication1
`

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue. We plan to address with a fix shortly.

You are using the curated feed instead of the main nuget.org. The curated feed filters out a lot of packages.

Possibly this is because you are hitting https://github.com/NuGet/Home/issues/2445. After adding the feed, you should switch to the nuget.org source and everything would be good again.
