### ISSUE TITLE
Intellisense error: Could not find a part of the path "[file path]" during uninstall nuget.server in MVC project

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2481]
Create MVC or WebForm project, open NuGet UI, uninstall NuGet.Server package meet error
1  file -> new project -> c# -> web asp .net web application -> mvc .
2  Right click project , open  manage nuget  package 
3  install package nuget.server, then uninstall it. Show the error.

it's not an regression.

**Comment by maartenba** [comment]
@zhili1208 is this caused by the package itself?

**Comment by zhili1208** [comment]
maybe, but looks like only happens for nuget.server

**Comment by maartenba** [comment]
Relates to https://github.com/NuGet/Home/issues/2962 - seems to also happen for e.g. "BugSense.Xamarin.iOS"

**Comment by maartenba** [comment]
Relates to https://github.com/dotnet/roslyn/issues/8850 (at least the showing errors portion)

Seems related to content file being removed, an event being triggered with IntelliSense, and then IntelliSense no longerfinding the content file (which was rightfully removed).

(wondering if https://github.com/NuGet/NuGet.Client/pull/739 could fix this?)
