### ISSUE TITLE
Print stack traces based on an env var or setting

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2482]
For CI scenarios users often run with verbosity set to minimal or quiet. This makes it hard to track down inconsistent crashes. 

To fix this NuGet should optionally print the full stack trace on exceptions/crashes when an environment variable or nuget.config setting is enabled.

Note that stack traces cannot be displayed all of the time since many expected errors come through as exceptions, when users see the stack trace they ignore the error message. For this reason this should be opt in.

**Comment by pranavkm** [comment]
Yeah, this would be great. We saw logs with
`error: Enumeration cannot continue because the collection was modified` without knowing what the underlying cause was. 

Turning on verbosity to detailed, bloats the build logs. It'd be great if we had this flag so we could get detailed logs for things we could report.

**Comment by joelverhagen** [comment]
Any particular reason that this should be an environment variable or NuGet config value instead of a simple command line argument, e.g. `--show-stack` for Xplat and `-ShowStack` on nuget.exe?

**Comment by emgarten** [comment]
Users can already get this with `--verbosity verbose`

Printing the stack under quiet would only be for unusual situations such as dogfooding a prerelease build on your CI machine while also limiting the output verbosity.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/eaf372a46362a2d2d295e3bde5abec598acaac3e.
