### ISSUE TITLE
Restore from a directory with inaccessible subdirectories fails

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2485]
Drop a project.json in a folder [somePath]
run `md foo`
run `icacls foo /deny Everyone:(F)`
run `nuget restore`

Expect: successful restore
Actual: fail with **Access to the path '[somePath]\foo' is denied.**

**Comment by yishaigalatzer** [comment]
Will address if we get user feedback on this issue

**Comment by manu-st** [comment]
I had this problem for a while but reported in the wrong forum (see https://github.com/dotnet/cli/issues/822). It has been blocking for me and anyone who might have tried to do cross compilation for arm on Linux.

Any hope to have this fix soon?

Thanks,
Manu

**Comment by emgarten** [comment]
Closing due to lack of feedback in this area.
