### ISSUE TITLE
Hide dependency options when using project.json

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2486]
Install and Update options and uninstall options are not supported in project.json, we should hide them in these scenarios (xproj, csproj + project.json)

![image](https://cloud.githubusercontent.com/assets/1238711/14370015/c920e1b2-fcde-11e5-885c-507308b64ee4.png)

**Comment by rohit21agrawal** [comment]
@rrelyea @yishaigalatzer 

What should be the behavior here if the Package Manager is opened via the Solution? 

Should we show the dependency options if there is atleast one project in the solution which is not the scenario stated above?

**Comment by yishaigalatzer** [comment]
Lets discuss with @harikm86 it probably needs a string of some kind telling the user that this doesn't impact xproj

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/commit/72d791a34317645b7411deac6f992c4966880a35

**Comment by harikmenon** [comment]
Sorry, was pretty late to the party. Have we decided how to handle this case when we do this from the Manage Packages in Solution command? Or are we going to track this separately in a different issue?

**Comment by rohit21agrawal** [comment]
@harikm86  We should track it in a separate issue.

**Comment by harikmenon** [comment]
Did you open one or do you want me to?

**Comment by rohit21agrawal** [comment]
@harikm86 you can open one and add in the details of the string we should display to indicate that those options are not valid for project.json scenarios.

**Comment by harikmenon** [comment]
Thanks. I will take this offline with you and Rob and open an issue once I have a solid understanding of the scenario
