### ISSUE TITLE
dotnet restore puts packages in an unexpected location

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2488]
From @lodejard 

have a solution with two projects:
./src/ClassLibrary1/project.json
./src/ClassLibrary2/project.json

in the root of the solution I run: 
$ dotnet restore --packages foo

Expected: the folder foo is created in the current directory, and it contains the packages
./foo/*\*  <-- packages here 
./src/ClassLibrary1/project.json
./src/ClassLibrary2/project.json

Actual: the folder foo is created in each project’s directory
./src/ClassLibrary1/project.json
./src/ClassLibrary1/foo/*\*  <-- packages here
./src/ClassLibrary2/project.json
./src/ClassLibrary2/foo/*\*  <-- packages here

Workaround: you can run dotnet restore --packages %CD%/foo to trick restore into providing the correct behavior.

**Comment by emgarten** [comment]
This should be fixed in 4.x
