### ISSUE TITLE
Installing nuget package with embedded .nupkg files from vso feed fails to lay down .nupkg file

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2491]
I tried the following commands.

nuget.exe install WASDK-v2.6.Quarantine -version 1.0.1 -source https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLDS_Shared/nuget/v3/index.json -outputdirectory %cd%\installedpackages

nuget.exe restore packages.config -source https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLDS_Shared/nuget/v3/index.json -outputdirectory %cd%\installedpackages

I expect to see nupkg files under the %cd%\installedpackages\WASDK-v2.6.Quarantine.1.0.1\bin\packages

If I point to an old onprem nuget server or a folder as a source then the install works.  It just appears to not work from vso feeds.  I can use the package that was downloaded from the vso feed place it in a folder and point to it as the source and it will install the embedded .nupkg files.

I am using 
3.5.0.1150 shp  4,021,464 04-07-2016 nuget.exe

please note:
if you require access to my vso feed then please let me know.

**Comment by yishaigalatzer** [comment]
Looks like a duplicate of https://github.com/NuGet/NuGet.Client/pull/466 or https://github.com/NuGet/Home/issues/2354

**Comment by yishaigalatzer** [comment]
In general we do not recommend including nupkg inside NuGet that's a major hack we don't want to support. We will take pull requests to address issues, but we will not actively invest in this area.
