### ISSUE TITLE
Using properties such as $(SolutionDir), $(ProjectDir), or $(CustomDefinedProperties)

### ISSUE THREAD

**Issue by guoliang** [NuGet/Home#2492]
I don't know if the feature is there already.

But is it possible in nuget.config use MSBuild properties?
E.g. I want the following to be possible

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="LocalNuget" value="$(SolutionDir)\LocalNuget" />
  </packageSources>
</configuration>
```

More specifically I want to be able to use $(CustomDefinedProperties)

**Comment by yishaigalatzer** [comment]
nuget.config is not tied to msbuild (nor it will ever be), nuget runs before msbuild, and works for other build systems that are not msbuild based. So you can't use msbuild properties in it. You could use relative paths and drop it in the right spot to resolve the SolutionDir issue.

**Comment by yishaigalatzer** [comment]
Closing because we do not intend to fix at the moment. But feel free to continue the discussion here
