### ISSUE TITLE
3.4 VS2015 and private nuget feed 

### ISSUE THREAD

**Issue by MademoiselleH** [NuGet/Home#2493]
Hello

I've just start using VS2015, previously I used 2013 with my organization private nuget feed.
When I try to change the source from nuget package manager parameters, my choice isn't taken into account. Whatever I try, I can get my own feed.

I had to uninstall the manager and get the 3.3 one.

Is it a problem already known ? Will it be fixed ?

**Comment by yishaigalatzer** [comment]
We think it is fixed, can you please try:

https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.2.821.vsix

**Comment by MademoiselleH** [comment]
Hello,

Thanks you for your quick answer :)
I've tried and it works.
My question is why this fix isn't embedded in VS 2015 enterprise setup ?

**Comment by yishaigalatzer** [comment]
You can now update from the gallery. The fix was released after visual studio was and will auto update your visual studio instance

**Comment by MademoiselleH** [comment]
I've seen this update.
Ok since I'm testing VS2015 for a future migration I just want to be sure
what to tell to developpers and weither it's better to use professional or
enterprise version.
Indeed, my co-worker tried professional version, and it had an older non
buggy version of nuget package manager.
He was asked to update, and then he upgraded to 3.4.0.798 whereas for
enterprise version nuget version update is 3.4.2.830.

I can't find anywhere why there's such a gap between the both.

**Comment by yishaigalatzer** [comment]
If you go to extensions and updates you will see 3.4.2 version of nuget available. Not sure why one will update and the other will not. Will circle back with the owners of extensibility

**Comment by yishaigalatzer** [comment]
Well, both have to have update 2 for auto update to work. Can you confirm that's the case?

**Comment by MademoiselleH** [comment]
It seems that my coworker didn't select Update 2 when he installed VS2015 pro.
When he did, the nuget package version worked without any patch, but the manager version was still different than mine. (VS2015 enterprise).
