### ISSUE TITLE
Improve performance when counting packages that need updates in VS UI

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2495]
Right now, we load the registration index and all pages. This is done pretty frequently, including:
- Every time the UI is opened.
- Every time the little search refresh button is clicked.
- More... I am not an expert in the area so it's hard to pin down for me.

We should think about the following improvements:
1. Add some kind of short-term caching. Right now, we never cache registration blobs.
2. Add throttling so if many packages have many registration blobs, we don't flood the user's network.
3. Improve the algorithm so that not all registration blobs are downloaded.
4. Add a new endpoint that is optimized for getting updates.

**Comment by emgarten** [comment]
Some of this has been fixed. Registration blobs are cached now. We should still look into reading only a subset of the reg pages.

**Comment by donnie-msft** [comment]
Closing after reviewing outstanding items offline with @joelverhagen

**Comment by loic-sharma** [comment]
@donnie-msft, was this piece done?

> Improve the algorithm so that not all registration blobs are downloaded.

**Comment by donnie-msft** [comment]
Your existing issue https://github.com/NuGet/Home/issues/8058 seems to cover that.

**Comment by loic-sharma** [comment]
Yep I asked because https://github.com/NuGet/Home/issues/8058 had been closed, thanks for reopening it.
