### ISSUE TITLE
"nuget sources remove -name sourceName" leaves behind credentials in local config

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2501]
nuget sources remove will remove a source from both the main nuget.config and a local config.
However, it appeared to leave behind credential information in the local config.
Next time the config was changed, the credential information was dropped, since there was no matching source name.

[found as part of 3.4.2 test pass]

**Comment by spotlesscoder** [comment]
Pleas fix this

**Comment by zhili1208** [comment]
checked nuget 4.4, it's fixed
