### ISSUE TITLE
Packing symbols of a csproj with a reference to a VS2015 shared project does not include the sources of the shared project.

### ISSUE THREAD

**Issue by stecydube** [NuGet/Home#2502]
Issued the following

> nuget pack myclasslibrary.csproj -symbols

Package was created with source files from myclasslibrary but missing source files from referenced shared project (.shproj).
The output issued warnings to the effect that it can't find the files (they are in a separate folder along with the .shproj file).

> WARNING: '$(MSBuildThisFileDirectory)Properties\CommonAssemblyInfo.cs' was included in the project but the path could not be resolved. Skipping...

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue, we will take a look.

This is not going to be a high priority item, so if it is blocking you, consider submitting a pull request.

**Comment by yishaigalatzer** [comment]
CC @toddm

**Comment by Thraka** [comment]
Ack, I just found out about symbol stuff and ran into this too. All my projects are created this way 😢
If I want to modify the nuget package, do I just copy all of the files in the shared project folder directly into nuget/src folder? Some guidance for this scenario would be great to have here: https://docs.nuget.org/create/creating-and-publishing-a-symbol-package

**Comment by yishaigalatzer** [comment]
I don't know the answer here or if it will even work. The way the paths work, I don't see how the symbol server will pick up sources from other folders.

**Comment by zhili1208** [comment]
Please try latest version of nuget: https://www.nuget.org/downloads, if it still repro, feel free to reopen it
