### ISSUE TITLE
nuget.exe push timeout needs a better error message

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2503]
```
nuget.exe push NuGetTestPackage.1.0.0.nupkg -ApiKey ... -Timeout 1
Pushing NuGetTestPackage.1.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package
A task was canceled.
```

"A task was canceled." should probably be "Push timeout expired." or similar.

**Comment by spadapet** [comment]
Dupe of: https://github.com/NuGet/Home/issues/2199
Here's the committed pull request: https://github.com/NuGet/NuGet.Client/pull/442
