### ISSUE TITLE
Nuget.Server why is cachesize not configurable? 

### ISSUE THREAD

**Issue by captelias** [NuGet/Home#2505]
in the packages.svc.cs code, the cache size is fixed at 100.  
Why is that limited and not configurable? 
that is causing several packages in my folder to drop out of the server, even though it is in the packages folder

**Comment by maartenba** [comment]
This is not a cache size, it's the page size. It serves an OData feed (www.odata.org) and provides paging - at the end of the page's XML source you will find a URL to the next page, which shows the next 100 pages and so on.

The NuGet client knows how to handle this protocol.

**Comment by captelias** [comment]
I don't understand. 
We are unable to download all the packages in our large feed. If I address the package folder directly it works
it seems to not serve packages on the "second page"

**Comment by maartenba** [comment]
How are you downloading the packages?

**Comment by captelias** [comment]
I have my nuget package manager using the webserver address. ( http://mynugetserver/nuget )
web server has the packages line in the web.config pointing to our existing v3 style repository

 <add key="packagesPath" value="\\fileserver\devopsfolders\Packagesv3" />

if I have the packagemanager use "\fileserver\devopsfolders\Packagesv3" it works

**Comment by captelias** [comment]
this is what we are getting
( http://istfs.pc.factset.com:8060/nuget/Packages(Id='BuildConfigs',Version='1.1') 

but the folder exists in the repo
Core-PackagesFast\BuildConfigs\1.1

**Comment by maartenba** [comment]
What exactly are you getting?

**Comment by captelias** [comment]
its not visible in the nuget browse 
and the request above returns a 404

**Comment by captelias** [comment]
other packages work fine if they are on the first page

**Comment by maartenba** [comment]
Which version of NuGet.Server is this?

**Comment by captelias** [comment]
I just got the latest

**Comment by captelias** [comment]
v2.10.2

**Comment by maartenba** [comment]
Okay, and what is the full log output in VS / nuget.exe? (not just single line, need more details)

**Comment by captelias** [comment]
I will have to pick this up on Monday. have a good weekend

**Comment by maartenba** [comment]
Likewise! Would love to get a repro of this so we can fix it. Enjoy your weekend!

**Comment by captelias** [comment]
Severity    Code    Description Project File    Line    Suppression State
Error       NuGet Package restore failed for project API: NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '1.1.0' of package 'BuildConfigs'.
  http://istfs.pc.factset.com:8060/nuget: Package 'BuildConfigs.1.1.0' is not found on source 'http://istfs.pc.factset.com:8060/nuget'.
  https://api.nuget.org/v3/index.json: Package 'BuildConfigs.1.1.0' is not found on source 'https://api.nuget.org/v3/index.json'.
  https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/: Package 'BuildConfigs.1.1.0' is not found on source 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/'.
  http://istfs.pc.factset.com:8060/private/HRPrivatepackages/nuget: The V2 feed at 'http://istfs.pc.factset.com:8060/private/HRPrivatepackages/nuget/Packages(Id='BuildConfigs',Version='1.1.0')' returned an unexpected status code '500 Internal Server Error'.
  http://istfs.pc.factset.com:8060/private/ISCorePrivatepackages/nuget: The V2 feed at 'http://istfs.pc.factset.com:8060/private/ISCorePrivatepackages/nuget/Packages(Id='BuildConfigs',Version='1.1.0')' returned an unexpected status code '500 Internal Server Error'.

   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<RestorePackageAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageRestoreManager.<RestorePackageAsync>d__39.MoveNext().          0   

the package is in the first of the repos 'http://istfs.pc.factset.com:8060/nuget'.(or should be)

**Comment by maartenba** [comment]
Seems there are a few servers in place? I see:
- http://istfs.pc.factset.com:8060/nuget
- http://istfs.pc.factset.com:8060/private/HRPrivatepackages/nuget
- https://api.nuget.org/v3/index.json
- https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/

Are all these four configured in your VS?

Also, just as a test, could you upgrade to the latest client from https://dist.nuget.org/index.html?

**Comment by captelias** [comment]
#3.4.1?

**Comment by maartenba** [comment]
That's the one

**Comment by captelias** [comment]
I am using this one
https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d?SRC=VSIDE

**Comment by captelias** [comment]
these are all configured sources.

**Comment by maartenba** [comment]
Any chance you can contact us by email and share (part of) the repository you have on disk so we can try and reproduce the issue? support at nuget . org

**Comment by captelias** [comment]
I'll have to approach that Monday

**Comment by captelias** [comment]
OK I went back to the beginning and redeployed everything 
I found the issue, it was a problem in the nuget init, that was not run for all packages, just publish so it wasn't really there
It just worked out that the packages on page 2 were not inited properly  

Sorry to waste your time.

**Comment by maartenba** [comment]
No worries, glad this is resolved. Enjoy your weekend!

**Comment by captelias** [comment]
I will now!
thanks again
