### ISSUE TITLE
nuget.exe delete is broken for V2 feed

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2509]
`NuGet.exe delete mysecrettestassembly 2.0.0 -Source https://www.nuget.org/api/v2`

generates the wrong package uri: 

```
DELETE https://www.nuget.org/api/v2/mysecrettestassembly/2.0.0
NotFound https://www.nuget.org/api/v2/mysecrettestassembly/2.0.0 478ms
```

**Comment by spadapet** [comment]
I don't think this is a bug. The behavior is exactly the same if you use nuget.exe v2.8 and v3.3.
Also, this works if you use https://www.nuget.org as the source.

Here are screenshots of the output when using v2.8, v3.3, and v3.4.2 to try and delete from both https://www.nuget.org/api/v2 and https://www.nuget.org.

![image](https://cloud.githubusercontent.com/assets/2523431/14399828/8b0f2b00-fda5-11e5-8ec6-4361f6fb9e31.png)

![image](https://cloud.githubusercontent.com/assets/2523431/14399830/8ecc85b2-fda5-11e5-956d-f15eefd6b347.png)

**Comment by maartenba** [comment]
I believe for delete (and push) you need to specify the full package endpoint `https://www.nuget.org/api/v2/package`

**Comment by spadapet** [comment]
Yep that works. Since the behavior hasn't changed, I don't think a fix needs to be made.

**Comment by rrelyea** [comment]
Could consider better command line help/docs -- as people new to this would have no clue.

**Comment by harikmenon** [comment]
Done.

**Comment by harikmenon** [comment]
http://docs.nuget.org/consume/Command-Line-Reference
