### ISSUE TITLE
When using the UI to search a V2 source, FindPackagesById is called twice for each ID

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2517]
Steps:
1. Open 3.4.0+ VS package management UI on a project (or solution, doesn't matter).
2. Select a V2 source.
3. Open Fiddler (with HTTPS decrypted, given that the V2 source is HTTPS).
4. Make some search, e.g. `TorSharp`.
5. Click on a result in the search result list.

You will notice individual calls made to `FindPackageById`. One made during search, and one made when you clicked the package.

The root of the problem is that we make the first call to get the version list of a package and the second call to get all of the metadata for each version. We can save the results in memory from the first call so the second call is not necessary.

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/484.

**Comment by rrelyea** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249)
