### ISSUE TITLE
NuGet packages should target netcoreapp and not netstandardapp

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#2524]
The NuGet packages are currently targeting `netstandardapp1.5`:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/project.json#L36

But this TFM is no longer valid. This should be targeting `netcoreapp1.0`.  That way CLI, who is referencing the NuGet packages, don't need to import `netstandardapp1.5`.

**Comment by emgarten** [comment]
This was blocked by https://github.com/dotnet/cli/issues/2406  
I'll get the updated packages out once I have a CLI build with the fix.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@e137a4d73154f55f43ab6a6f802103744f93f201
