### ISSUE TITLE
Project reference fails from csproj to xproj (with netstandard target reference)

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#2525]
Ported from dotnet/roslyn#10481 from @jinujoseph:

Repro steps 
- Create a .Net Core Class Library (xProj)
- By default it points to
  "frameworks": {
    "netstandard1.5": {}
  }
- Now create .Net Console Aplication (csProj) 
- point the .netframework to 4.6.2 
- Add project.json file to the same and add 
  {
  "frameworks": {
    "net462": { }
  },
  "runtimes": {
    "win": { }
  }
  }
- Build both projects and make sure it builds fine.
- Now refer the class library project from console app.

Expected 
Reference works and Builds successfully 

Actual 
Reference maps but build fails with this error 
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : Object reference not set to an instance of an object.
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.<GetPackagesFromTarget>d__104.MoveNext()
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetReferences(JObject lockFile)
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()
2>C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error :    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute()

**Comment by jasonmalinowski** [comment]
@yishaigalatzer @davidfowl This appears to be a NuGet client/restore issue. The reference in the `targets` section has this:

```
"xproj/1.0.0": {
  "type": "project",
  "framework": ".NETStandard,Version=v1.5",
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-23931"
  },
  "compile": {
    "netstandard1.5/xproj.dll": {}
  },
  "runtime": {
    "netstandard1.5/xproj.dll": {}
  }
}
```

But the package in the `libraries` has this:

```
"xproj/1.0.0.0": {
  "type": "project",
  "path": "../src/xproj/project.json",
  "msbuildProject": "../src/xproj/xproj.xproj"
}
```

Observe the extra `.0` in the version number. I assume those are supposed to be the same.

**Comment by emgarten** [comment]
They should match, and both be normalized to 1.0.0. I'll take a look at why this isn't happening.
