### ISSUE TITLE
Bad servername.cache.bin make server to not start

### ISSUE THREAD

**Issue by Tasteful** [NuGet/Home#2526]
I run out of discspace on my nuget-server and when I added a new package (without knowing about discspace) the servername.cache.bin was persisted in some bad state. After deleting some items on the disc I need manually delete servername.cache.bin to get the nuget-server to start again.

It should be good if nuget-server can recover itself if the cache-file is bad.

Using NuGet.Server.2.10.2 package as "nuget-server" and running that on Windows 2012r2.

**Comment by xavierdecoster** [comment]
This issue was moved to NuGet/NuGetGallery#2985
