### ISSUE TITLE
Support 204 responses for v2 requests in project.json

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2528]
V2FeedParser supports 204 responses, however project.json restore uses a different code path that does not support this.

Related: https://github.com/NuGet/Home/issues/1759

**Comment by emgarten** [comment]
Fixed in 3.4.3 NuGet/NuGet.Client@e2af9d13cc0e1d995eb53d2f9eba9f30f264b4a7

**Comment by emgarten** [comment]
Leaving this open until the 3.5.0 fix is in

**Comment by joelverhagen** [comment]
Verified with NuGet 3.5.0 (build 1249).
