### ISSUE TITLE
Add .NETStandard 1.6

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2536]
We need a .NETStandard1.6.  It should be mapped as follows:
- net4.6.3 > NETStandard1.6
- netcoreapp1.0 > NETStandard1.6

/cc @joelverhagen 
/cc @richlander @petermarcu @weshaggard @joshfree

**Comment by joelverhagen** [comment]
Confirmations:
- This changes netcoreapp1.0 from `netstandard1.5` to `netstandard1.6`.
- `dotnet5.7` will not have any explicit mappings.
- `netstandardapp1.6` will not have any explicit mappings.

**Comment by joelverhagen** [comment]
Also:
- All Xamarin TFMs should move up to `netstandard1.6` (according to the previous decisions that Xamarin should track highest .NETStandard version).

**Comment by ericstj** [comment]
> This changes netcoreapp1.0 from netstandard1.5 to netstandard1.6.

Correct

> dotnet5.7 will not have any explicit mappings.

Correct

> netstandardapp1.6 will not have any explicit mappings.

Folks have been discussion what we want to do with this TFM now that we have netcoreapp1.0.  I'll let @richlander chime in if he wants this.

> All Xamarin TFMs should move up to netstandard1.6 (according to the previous decisions that Xamarin should track highest .NETStandard version).

Correct

**Comment by joelverhagen** [comment]
Closed with https://github.com/NuGet/NuGet.Client/pull/511.
