### ISSUE TITLE
Reduce `netstandard` target for NuGet.* projects where possible

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2538]
Where possible, we should reduce the `netstandard` version that NuGet projects use, as it will broaden the compatibility. I suggest `netstandard1.2` if possible (which correlates to .NET 4.5.1, see https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) or `netstandard1.3`.

If you can go as low as `netstandard1.1` or even `netstandard1.0`, you may as well :)

**Comment by emgarten** [comment]
Almost all NuGet projects need to perform basic disk operations including NuGet.Common which is a dependency of most projects. The lowest I can get NuGet.Common to build at is `netstandard1.3` which is `net46`.

**Comment by analogrelay** [comment]
That's fine, it's mostly just about getting it as low as we can go :). Since you cross-target `net45`, we can still work on `net451`, we just have to cross-target ourselves (which is fine in this scenario).

**Comment by emgarten** [comment]
I've lowered the framework to netstandard1.3
