### ISSUE TITLE
Review IVsPackageInstaller2 and IVsPackageSourceProvider 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#254]
Review and update the new public APIs for IVsPackageInstaller2 and IVsPackageSourceProvider 

Suggestions from @yishaigalatzer
- ~~Add a context type for the install options~~ can't use context objects everything must be an interface
- Keep parameter order consistent
- Create an interface for `VersionSpec`

**Comment by yishaigalatzer** [comment]
We should remove the interface from RTM, and restore at a later release.

**Comment by emgarten** [comment]
Removed from 3.0.0 RTM NuGet/NuGet.VisualStudioExtension@aea19322751da19988a341b0ff4eb0737a702384
