### ISSUE TITLE
Update-Package reports Package is not found

### ISSUE THREAD

**Issue by digitalsigi** [NuGet/Home#2542]
I'm using nuget V 3.4.2.830 and have a custom nuget source configured in VS 2015 in addition to standard source. In GUI I selected "All" Sources. But when trying "update-package" I get following error:
PM> update-package
Attempting to gather dependency information for multiple packages with respect to project 'RemoteControlService', targeting '.NETFramework,Version=v4.5.1'
update-package : Package 'LoggingService' is not found in the following primary source(s): 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are 
available (OR) package id, version are specified correctly.
At line:1 char:1
- update-package
- ~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
    Working with GUI, update is found as expected.
    Josef

**Comment by emgarten** [comment]
@digitalsigi I don't see `LoggingService` on nuget.org. Is that where you are expecting it to come from?

**Comment by rrelyea** [comment]
@digitalsigi Just to confirm, did you change the package manager source in the UI of Package Manager Console?
![image](https://cloud.githubusercontent.com/assets/8865080/14543615/eb7d5068-0249-11e6-8955-127a49bcfdc9.png)

**Comment by jainaashish** [comment]
@digitalsigi Make sure you've "all" source selected in Package Manager Console and then try update-package command 
![image](https://cloud.githubusercontent.com/assets/18219758/14547066/079a8ddc-025f-11e6-8e81-72d71505f766.png)

**Comment by digitalsigi** [comment]
Hi @all, thanks for careing....
@emgarten : True, because this package lifes in our private repo
@rrelyea and @jainaashish : Thanks, that did point me in the right direction, I selected "All" at the Package Manager **GUI** not at the console. Thanks to all!
