### ISSUE TITLE
Respect SemVer

### ISSUE THREAD

**Issue by tugberkugurlu** [NuGet/Home#2543]
I have come across a very weird and annoying behavior with NuGet. I am able to pack a package with a version number of `1.0.0-rc1.1`. However, when I try to push it to NuGet.org, I get the below error from nuget.exe command line (v3.2.0):

```
'1.0.0-rc1.1' is not a valid version string.
```

If I try to upload the package on nuget.org, I get the below:

```
Package Version invalid: no '.' allowed in the release label.
```

See [this build](https://travis-ci.org/tugberkugurlu/AspNetCore.Identity.MongoDB/builds/123051772) for this example. This is the part it fails: https://travis-ci.org/tugberkugurlu/AspNetCore.Identity.MongoDB/builds/123051772#L1977

This is so wrong for several reasons:
- `1.0.0-rc1.1` is a valid semver and it creates fraction/confusion if NuGet keeps not respecting semver. 
- I get different errors from CLI and web site. That's also confusing.
- Let's say NuGet does this correct (side note: no, NuGet does this wrong!). Then, why am I allowed to pack it with that version at the first place?

Also see https://github.com/NuGet/Home/issues/1359, https://github.com/NuGet/Home/issues/1938. https://github.com/NuGet/Home/issues/1486.

**Comment by dotnetchris** [comment]
:+1:

**Comment by yishaigalatzer** [comment]
We blocked it already in 3.4.2
