### ISSUE TITLE
Add snapshot version of a package

### ISSUE THREAD

**Issue by agraignc** [NuGet/Home#2544]
Will you add s snapshot version for a package or something close ?

Snapshot version is something existing on Maven and really useful if you're working on multiple projects.

For example if you're working on 2 projects A and B, A has a dependency package to B.
In a release scenario it's fine because your project A will have a dependency to the project B (the project B with the right version will be in the packages NuGet folder).
In a dev scenario you want to work on both projects at the same time, but there's no way to tell project A to have a dependency to project B "under dev" instead of a version (only releases versions of package B will be in the packages NuGet folder).

So if I understand the Snapshot made by Maven, every time you build the project B, this project B "under dev" will have a version (this is what is called snapshot) in the packages NuGet folder and A will have a dependency to this snapshot.

**Comment by emgarten** [comment]
@agraignc have you tried using project.json (instead of packages.config) with snapshot versions?

**Comment by rrelyea** [comment]
With .xproj, we support this kind of feature. It will be released with v3.5.

**Comment by rrelyea** [comment]
Closing, but feel free to continue discussion.

**Comment by agraignc** [comment]
Hello,

The Nuget 3.5 Beta has been released last month but I don't see anything related to the xproj. Can you tell me more about it to do this "snapshot" feature ? thx

**Comment by red8888** [comment]
So project.json is dead and now msbuild is used for this instead. Is this feature just never going to happen?
