### ISSUE TITLE
Make errors easier to spot errors in restore output

### ISSUE THREAD

**Issue by MichaelSimons** [NuGet/Home#2545]
It would be nice if errors were easier to visually spot in the restore output.  Often there is a tremendous amount of output while restoring.  The first thing that comes to mind is to color errors red just like what is typically done with build errors.

```
root@4f5d809bb35f:/app2# dotnet restore
log  : Restoring packages for /app2/project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json 452ms
error: Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002374)' for '.NETCoreApp,Version=v1.0'.
info : Committing restore...
log  : Writing lock file to disk. Path: /app2/project.lock.json
log  : /app2/project.json
log  : Restore failed in 977ms.

Errors in /app2/project.json
    Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc2-3002374)' for '.NETCoreApp,Version=v1.0'.

NuGet Config files used:
    /root/.nuget/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json
```

**Comment by richlander** [comment]
I saw that, then these opaque error messages:

Richards-MacBook-Pro:test rlander$ dotnet run
The given key was not present in the dictionary.
Richards-MacBook-Pro:test rlander$ dotnet build
The given key was not present in the dictionary.
Richards-MacBook-Pro:test rlander$ dotnet --version
1.0.0-rc2-002426

**Comment by MichaelSimons** [comment]
@richlander FYI, I logged https://github.com/dotnet/cli/issues/2504 to improve the CLI error message in this scenario.

**Comment by nkolev92** [comment]
Apologies for the super long turnarounds. 
This was fixed early in 1.x.
