### ISSUE TITLE
NuGet update in VS2015 leaves old package traces in vcxproj

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#2546]
I've suddenly started experiencing problems with NuGet update in VS2015 U2 with NuGet plugin 3.4.2. This consistently occurs on one of my computers. Reinstalling NuGet or repairing VS2015 does not help. 

Steps to reproduce:
- Open any C++ project with outdated NuGet dependencies.
- Update the NuGet dependencies through the Visual Studio IDE.
- Observe that `packages.config` is correctly updated.
- Observe that new `<Import...>` and `<Error...>` tags are added to the vcxproj file for the new version, but the old ones are not removed.
- Observe that build fails due to the remaining references to the old package version.

Log output from NuGet:

> Attempting to gather dependency information for package 'ABC.0.116.0' with respect to project 'Apps\AppSupport', targeting 'native,Version=v0.0'
> Attempting to resolve dependencies for package 'ABC.0.116.0' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'ABC.0.116.0'
> Resolved actions to install package 'ABC.0.116.0'
> Removed package 'ABC.0.115.0' from 'packages.config'
> Successfully uninstalled 'ABC.0.115.0' from AppSupport
> Removed package 'ABC.redist.0.115.0' from 'packages.config'
> Successfully uninstalled 'ABC.redist.0.115.0' from AppSupport
> Adding package 'ABC.redist.0.116.0' to folder 'C:\Views\App\windows\packages'
> Added package 'ABC.redist.0.116.0' to folder 'C:\Views\App\windows\packages'
> Added package 'ABC.redist.0.116.0' to 'packages.config'
> Successfully installed 'ABC.redist 0.116.0' to AppSupport
> Adding package 'ABC.0.116.0' to folder 'C:\Views\App\windows\packages'
> Added package 'ABC.0.116.0' to folder 'C:\Views\App\windows\packages'
> Added package 'ABC.0.116.0' to 'packages.config'
> Successfully installed 'ABC 0.116.0' to AppSupport
> ========== Finished ==========

**Comment by rrelyea** [comment]
Tried to repro unsuccessfully with the following steps on both VS 2015 Update 1 (w/ 3.3.0) and VS 2015 Update 2 (w/ 3.4.2)
1) file new project > c++ project > win32 > console application > finish
2) add zlib nuget package (using a slightly old version of it, so I have room to update)
3) rebuild successfully
4) update to a newer zlib
5) rebuilt successfully

Can you give me a set of steps and packages (on a public package server) or via email (rrelyea @ microsoft) that can repro?

**Comment by forderud** [comment]
I am able to reproduce the problem by following your instructions above. The problem is therefore likely related to my local nuget install or computer setup. Possible reasons might be different versions of dependent DLLs, regional settings or something else. I really have no clue.

Is there a way to crank up the nuget logging verbosity in the IDE?
Do you have a debug build of the NuGet 3.4.2 VS plugin for 2015 with PDBs available, so that I can attach a debugger to figure out what is going on?

**Comment by rrelyea** [comment]
Here is the diff of the project before and after I upgrade my zlib.
![image](https://cloud.githubusercontent.com/assets/8865080/14560061/0450cbe2-02c2-11e6-8be7-c0feeefcdd5c.png)

I also did another upgrade with similar results.
Perhaps if you captured exact project state and emailed (rrelyea @ microsoft) a slimmed down zip file (delete binaries from inside package directories) with separate folders of exact project files, I can diff with my steps and look for any differences.

I'm not sure if you would see similar problems with NuGet.exe? That has better logging.
Perhaps you could try 3.3 and 3.4.0rc of NuGet.exe with similar steps (see http://dist.nuget.org/index.html) ?

I don't think we've published a debug version of the VSIX - but you could definitely build one and debug.

**Comment by forderud** [comment]
Unfortunately, I cannot reproduce through the command-line due to https://github.com/NuGet/Home/issues/1291. Also, I'm not able to build the Visual Studio plugin myself for debugging purposes due to https://github.com/NuGet/Home/issues/2419 . These bugs really reduce my ability to debug the problem myself.

I'll have to come back to you with regards to a minimal reproducer, since the failing project is fairly deeply wowed into our internal SW.

**Comment by rrelyea** [comment]
These may help you debug...
1) we have recently published the symbols publicly, so you may be able to debug the VSIX using the released version.
2) we are going to attempt to address https://github.com/NuGet/Home/issues/2401 in the dev branch in a couple hours.

**Comment by forderud** [comment]
I think you can move this issue from the 3.4.3 milestone and over to 3.5 or similar, since I'm struggling to create a minimal reproducer. Also, I'm able to work around the problem for the time being.

It would be great if you could instead focus on https://github.com/NuGet/Home/issues/1291 sometime soon, since that would greatly ease debugging for me.

**Comment by forderud** [comment]
This problem seem to have been fixed after upgrading to NuGet plugin 3.4.3 in VS2015. You can therefore resolve this issue.

Thanks for all the fixes delivered in 3.4.2 & 3.4.3. They are really making my life easier. :+1:
