### ISSUE TITLE
programmatic  NuGet Installation in the ASP.NET Website project 

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#2548]
Hi all,

I have working on the project template for the ASP.NET Website project. I Need to add the dependent Web config entries are add dynamically in the web config xml file while install the packages. But the Website project didn't have project file. So I cannot install the package with the use of the IVsPackageInstaller  interface.

How can I install the NuGet packages programmatic in the Website project.

Please suggest me if any way to install the package programmatic in the Website project.

Thanks,

Ganesan R.

**Comment by rrelyea** [comment]
Firstly, the way that WebSite project template does addition of NuGet packages can be seen here:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates\Web\CSharp\1033\WebApplication45\WebApplication45Dev14.vstemplate

You'll see: 

```
<WizardExtension>
    <Assembly>NuGet.VisualStudio.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>NuGet.VisualStudio.TemplateWizard</FullClassName>
  </WizardExtension>
  <WizardData>
    <packages repository="registry" keyName="WebFormsVS14" isPreunzipped="true">
      <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" skipAssemblyReferences="true" />
      <package id="jQuery" version="1.10.2" />
      <package id="Respond" version="1.2.0" />
      <package id="Modernizr" version="2.6.2" />
      <package id="bootstrap" version="3.0.0" />

```

And if you try this template, you'll see that NuGet package manager works inside VS for that project after creation as well. 

You could look at the code for our VS UI inside of NuGet/nuget.client repro and inspect or debug exactly what the VS package manager does to install a nuget package via programmatic communication with VS.

Please let us know how that goes.
