### ISSUE TITLE
NuGet 3.3 outputs v2 feed url when pushing to v3 feed url

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#2550]
I'm using nuget.exe version 3.3.0.212 to push a package to VSO feed:

```
nuget.exe push MyPackage.1.0.nupkg -Source https://mpsit.pkgs.visualstudio.com/DefaultCollection/_packaging/My_Feed/nuget/v3/index.json -ConfigFile nuget.config -ApiKey My_Feed
```

And get the following output:

```
Using credentials from config. UserName: alexbat
Pushing MyPackage 1.0 to 'https://mpsit.pkgs.visualstudio.com/DefaultCollection/_packaging/<id>/nuget/v2/'...
```

I can also post my nuget.config content but it contains only feed url and its credentials (security token).

**Comment by abatishchev** [comment]
Bump.

**Comment by abatishchev** [comment]
Any update on this, please? Was it fixed? Can it be closed? Or should it be addressed still?

**Comment by abatishchev** [comment]
Any update on this, please? Was it fixed? Can it be closed? Or should it be addressed still?

**Comment by abatishchev** [comment]
Any update on this, please? Was it fixed? Can it be closed? Or should it be addressed still?

**Comment by zhili1208** [comment]
this is by design, actually only v2 feed accept push, nuget translate v3 feed to v2 feed internally for push
