### ISSUE TITLE
NuGet.config settings being deleted by Visual C++

### ISSUE THREAD

**Issue by shepherd007** [NuGet/Home#2554]
It seems that when messing Visual C++ 2013 settings in Package Manager (such as selecting/deselecting available package sources) some of parameters configured by nuget (password, user...) are being removed. I've observed that affected parameters are: repository path, http proxy, username and password.
Did anyone observed such behavior?

**Comment by rrelyea** [comment]
I've not noticed that. If you can come up with a solid repro, please give us the detailed steps.

**Comment by shepherd007** [comment]
@rrelyea Here are the reproduction steps:
- create Visual C++ project (_New Project -> Templates -> Visual C++ -> Win32 -> Win32 Console Application_)
- go to: _Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources_
  -  add new pakage source with name TEST and address: https://www.nuget.org/api/v2/ - both feeds should be checkad as active
  - press OK
- go to _Tools -> NuGet Package Manager -> Manage NuGet Packages for solution_
  - find and install: **NuGet.CommandLine**
- restart Visual
-  go to: _Tools -> NuGet Package Manager -> Package Manager Console_
  - enter: **nuget config -set repositoryPath=c:\**
  - press enter
- from the windows start menu go to **%APPDATA%** and then to NuGet folder - open **NuGet.config** in text editor (i.e. Notepad++)
  - make sure at the end of config file is entry:

```
  <config>
    <add key="repositoryPath" value="c:\" />
  </config>
```
- go to: _Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources_
  - uncheck TEST feed 
  - press OK
- re-open **NuGet.config** and check that now repositoryPath entry is gone

The issue was observed on:
- Windows 7 and Windows 10
- Visual C++ 2013 (other Visual versions not checked)
- NuGet command line version 3.3.0 and 3.4.3

**Comment by zhili1208** [comment]
Please try VS 2017, if it still repro, feel free to reopen
