### ISSUE TITLE
NuGet Restore not writing 'serviceable' attribute to lock file

### ISSUE THREAD

**Issue by analogrelay** [NuGet/Home#2556]
CoreCLR packages have assemblies marked with an attribute indicating they are servicable. `dnu restore` would scan package assemblies and transfer this attribute over to the lock file so that other consumers could depend on this data without having to scan assemblies. NuGet v3 restore does not do this.

See also https://github.com/dotnet/cli/issues/2523

**Comment by schellap** [comment]
I believe this is not just coreclr packages although I haven't confirmed. The implication for us is rather serious: i.e., not being able to service. We are working around this for now to always check servicing for these assemblies.

**Comment by emgarten** [comment]
This was left out intentionally to keep NuGet from reading assemblies, I believe the plan was to read it at build/publish time.

What are the scenarios where this attribute needs to be read outside of build/publish?

**Comment by analogrelay** [comment]
That does sound reasonable and like something we decided :). Ok, I'll close this out then.

**Comment by schellap** [comment]
@anurse, could you pls re-open this and let @rrelyea or @yishaigalatzer triage to the right dev? I don't have permissions to open bugs in the repo.

**Comment by yishaigalatzer** [comment]
We decided to close this issue, we now have package level serviceable attribute and we need to write that one out. https://github.com/NuGet/Home/issues/2923 supersedes this issue
