### ISSUE TITLE
installing package hangs if package has required dependency that does not exist at source url

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#2560]
example:  (nuget version: 3.5.0.1150)
nuget install Microsoft.Azure.AzureServiceDeployClient -version 1.0.16-beta -source "http://wanuget/ManualMirror/nuget/"
It just hangs.

example: (nuget version: 2.8.60717.93)
nuget install Microsoft.Azure.AzureServiceDeployClient -version 1.0.16-beta -source "http://wanuget/ManualMirror/nuget/"
Unable to resolve dependency 'WindowsAzure.Storage (= 4.3.0)'.

Please note I don't own the wanuget feed but I am pretty sure it is an old v2.x feed.

**Comment by rrelyea** [comment]
We've fixed a number of server compat issues in later builds of 3.5.0. 
Can you please upgrade to the latest (3.5.0-beta-1178)...and confirm if this reproduces.

**Comment by kingerja** [comment]
This works with NuGet.Server v2.10.3.0
However older feeds that are not up to the latest 2.x nuget.server such as "http://wanuget/ManualMirror/nuget/" still cause nuget.exe to hang on missing dependencies.

**Comment by kingerja** [comment]
I tried with the latest build 3.5.0.1208 and it still repro's.
I also asked the wanuget guys and they report they are on 2.10 for their server feed.
I will add you to that thread in case you want to attempt a repro on your end.

**Comment by kingerja** [comment]
If you need anything for me please feel free to reach out to me.  

There are really two issues the first issue is it fails to find packages on the myget feeds.  This is annoying but given that later versions nuget aren't really backwards compatible this isn't unexpected.

The other issue which I think is the more important one is that the nuget client deadlocks.  So perhaps instead of fixing the back compat feed issue instead deal with the deadlock issue since nuget client should never deadlock no matter what scenario it enters.  So in this scenario it would hit some internal timeout or something and issue a timeout/whatever error instead of hanging forever.

**Comment by kingerja** [comment]
This is fixed in 3.4.5.53683
