### ISSUE TITLE
Improvements to Browse in Package Manager UI (Multi Install/Uninstall)

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#2584]

**Comment by johnegbert** [comment]
I need the ability to uninstall multiple packages at the same time (if that is what this issue is). Done similarly to the "Update" package tab where multiple package can be selected and then uninstalled.

**Comment by jainaashish** [comment]
Thanks for the feedback. This will be a good addition to NuGet UI but unfortunately we won't be able to get to this in near future since we are occupied with other important stuff.
