### ISSUE TITLE
Misleading error when attempting to install package that depends on design-time facades

### ISSUE THREAD

**Issue by divega** [NuGet/Home#2594]
As originally reported at https://github.com/aspnet/Identity/issues/783:
1. Open Visual Studio 2015 with NuGet Client 3.3 or 3.4.2 
2. File -> New -> Project -> Console Application targeting .NET 4.5.1 or 4.5.2
3. In PMC,  run "Install-Package Microsoft.AspNet.Identity.EntityFramework -Pre -Source nuget.org" 

That should install RC1 version of that package but the installation fails midflight and rolls back. The following warnings and errors appear in the output:

```
...
Added package 'Microsoft.AspNet.Identity.EntityFramework.3.0.0-rc1-final' to folder 'c:\users\divega\documents\visual studio 2015\Projects\ConsoleApplication49\packages'
Install failed. Rolling back...
Package 'Microsoft.AspNet.Identity.EntityFramework.3.0.0-rc1-final : EntityFramework.Relational [7.0.0-rc1-final, ), Microsoft.AspNet.Identity [3.0.0-rc1-final, )' does not exist in project 'ConsoleApplication49'
...
Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global 
Assembly Cache.
At line:1 char:1
+ Install-Package Microsoft.AspNet.Identity.EntityFramework -pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPac 
   kageCommand
```

I talked to @yishaigalatzer and we believe the reason this fails is that there is a dependency chain into a design-time façade: Microsoft.AspNet.Identity.EntityFramework -> 
    EntityFramework.Relational -> 
        System.Diagnostics.DiagnosticSource -> 
            System.Runtime

This isn't really supported by NuGet. Assuming I understand it correctly this seems to be the issue detailed in #2193. However surprisingly installing EntityFramework.Relational directly works without failure.

Filing this issue specifically because @yishaigalatzer wanted to improve the error, however #2193 might just make the scenario work.

**Comment by divega** [comment]
@yishaigalatzer I noticed that #2193 is assigned and in the 3.5 RC milestone. Wouldn't the error go away if you fix that one?

**Comment by divega** [comment]
Or perhaps I misread #2193 and that is only about changing that particular package to remove the reference?

**Comment by yishaigalatzer** [comment]
2193, is about supporting the scenario. We don’t know if we will be able to make it
