### ISSUE TITLE
nuget pack -MSBuildVersion fails with "Unknown option: '-MSBuildVersion'"

### ISSUE THREAD

**Issue by TimMurphy** [NuGet/Home#2595]
Using nuget.exe Version 2.8.60717.93 the following command:

```
nuget.exe pack ./source/projectname.csproj -MSBuildVersion 14 -Build
```

fails with with following error message:

```
Unknown option: '-MSBuildVersion'
```

**Comment by emgarten** [comment]
@TimMurphy get the latest nuget.exe from: http://dist.nuget.org/index.html

**Comment by TimMurphy** [comment]
@emgarten I was unaware of this distribution channel. I've always got latest nuget.exe from http://nuget.org/nuget.exe.

Do you think I should open another issue to replace or redirect http://nuget.org/nuget.exe?

**Comment by emgarten** [comment]
That's a known issue, we're leaving that copy of nuget.exe alone for awhile to avoid breaking any CI machines out there that depend on specific behaviors that 2.8.6. has.

**Comment by TimMurphy** [comment]
OK. Many thanks for the quick responses.
