### ISSUE TITLE
How to get total download count via v3 API?

### ISSUE THREAD

**Issue by Daniel15** [NuGet/Home#2596]
How can we get both the total download count as well as the per-version download count using the NuGet v3 API?

Also see https://github.com/badges/shields/issues/678

**Comment by xavierdecoster** [comment]
AFAIK there's no API for this yet

**Comment by yishaigalatzer** [comment]
@rrelyea can you point @Daniel15 in the right direction?

**Comment by Daniel15** [comment]
Is this available with the new API yet?

**Comment by devlead** [comment]
Any plans for an API?

**Comment by maartenba** [comment]
The V2 API is still around for this.

**Comment by Daniel15** [comment]
This is working again! The `SearchQueryService` returns the data.

Example API request: https://api-v2v3search-0.nuget.org/query?q=packageid:microsoft.aspnetcore.mvc (note: ensure you get the endpoint URL from https://api.nuget.org/v3/index.json - **do not** hardcode `api-v2v3search-0.nuget.org`)

```
"totalDownloads": 1670417,
```

Consequently I've re-added the download count badge to shields.io: https://github.com/badges/shields/pull/945
