### ISSUE TITLE
Package Manager UI uses OS' regional settings and not display language in VS2015

### ISSUE THREAD

**Issue by vcaraulean** [NuGet/Home#2599]
I've updated to latest VS 2015.2 and after that Package Manager speaks French to me. 

In the meantime, I have:
- VS 2015 in English
- Windows 10 display language set to English
- Regional formats are set to French as I'm living in a French speaking area
- I have 4 languages configured for input

Please, make Package Manager UI speak English by default. Local language should be an option, not the default choice. 

And please, if it's tricky to decide on the language, make possible to override your decision logic.

PS: Restarted my PC and it went back to English. Haven't tried to restart only VS (had reboot pending). So, no issue for me, but please be aware of this issue.

**Comment by yishaigalatzer** [comment]
Thanks @vcaraulean
