### ISSUE TITLE
Scripts fail to run to due to PS execution priviledge level

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#260]
1. Create a Win 8.1 hub app 
2. Delete out all packages
3. install-package Microsoft.ApplicationInsights.WindowsStore -Version 0.13.3-build03939 -pre

An error occurs due to PS:
Executing script file 'c:\Users\juste\documents\visual studio 2015\Projects\App4\packages\Microsoft.ApplicationInsights.WindowsStore.0.13.3-build03939\tools\win81\install.ps1'
& : File C:\Users\juste\documents\visual studio 2015\Projects\App4\packages\Microsoft.ApplicationInsights.WindowsStore.0.13.3-build03939\tools\win81\install.ps1 cannot be loaded because running scripts is 
disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ & 'c:\Users\juste\documents\visual studio 2015\Projects\App4\packages\Microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by danliu** [comment]
Looks like Fei already fixed this bug via https://github.com/NuGet/NuGet.VisualStudioExtension/commit/741ba2c836770dc5f89dea59e55eeb2bfe010d81, where the executionPolicy is set to ByPass for process. So the script will always run.
