### ISSUE TITLE
Nuget making tons of HTTP requests during "Attempting to resolve dependencies for package" phase

### ISSUE THREAD

**Issue by DavidKDeutsch** [NuGet/Home#2602]
When updating a package, Nuget 3.3 makes a _lot_ of requests to www.nuget.org, slowing things down considerably. Many of these requests seem to be for core libraries I already have installed, e.g.:

https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading' HTTP/1.1

Is this normal behavior?

**Comment by yishaigalatzer** [comment]
Thanks for the feedback, I'm going to respond to your questions and close the issue. Feel free to continue discussing on this thread.
1. Yes it is normal, we are trying to see if there are new dependencies or versions during updates.
2. In 3.4.2 (and shortly to be released 3.4.3) we have made significant improvements, so things should be much faster.
3. We do have a plan to improve and make less call, in future versions.
