### ISSUE TITLE
NuGet removes nuget.org from the settings file

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#2603]
Ever since installing VS 2013 Update 5, Visual Studio removes the offical nuget package source from my solution's NuGet.config. 

 Here's the file before I open the solution: 

``` xml
 <?xml version="1.0" encoding="utf-8"?> 
 <configuration> 
 <solution> 
 <add key="disableSourceControlIntegration" value="true" /> 
</solution> 
 <packageSources> 
 <add key="NuGet official package source" value="https://nuget.org/api/v2/" /> 
 <add key="custom package source" value="http://my-server/v2/nuget" /> 
 </packageSources> 
 </configuration> 
```

 And here it is after: 

``` XML
 <?xml version="1.0" encoding="utf-8"?> 
 <configuration> 
 <solution> 
 <add key="disableSourceControlIntegration" value="true" /> 
 </solution> 
 <packageSources> 
 <add key="custom package source" value="http://my-server/v2/nuget" /> 
 </packageSources> 
 </configuration> 
```

 While the change doesn't affect anything when working in Visual Studio, it does break my TFS builds, as TFS build no longer knows to check the offical nuget package source when restoring packages. So I have to revert this change to NuGet.config every time I check in my changes.

**Comment by rohit21agrawal** [comment]
@yishaigalatzer This is not repro'ing for Nuget 2.8.60610.756 with a Simple WPF project on Windows 7 Visual Studio 2013 Update 5

Can you provide more details on the kind of project? Or attach the project with which it repro's on your end, if possible?

**Comment by rohit21agrawal** [comment]
Closing this issue since haven't been able to repro this issue.

Please feel free to activate if anyone hits this again.
