### ISSUE TITLE
3.4.2.830 causing credentials UI to pop for corporate, internal NuGet server

### ISSUE THREAD

**Issue by rkeithhill** [NuGet/Home#2605]
We have an internal NuGet server for distributing packages and after the latest NuGet VSIX update for VS 2015 (3.4.2.830), folks are being prompted for credentials (which is new behavior).  When they supply their Domain credentials, they aren’t accepted.  The UI prompt appears again.  Yet if I open VS 2012 or VS 2013 (not having updated the NuGet VSIX), I can browse & install pkgs from our NuGet server just fine.  There are no prompts to enter credentials.  Is there a workaround for this?

**Comment by onslaughtq** [comment]
We're having this issue at my company as well unfortunately :-(

**Comment by kkm000** [comment]
Install https://dist.nuget.org/visualstudio-2015-vsix/v3.4.1/NuGet.Tools.vsix to fix. Do not forget to run VS as admin after that and disable automatic updates for the NuGet extension.

This has been open for 20 hours and not yet assigned the priority of -1.  :(

**Comment by kkm000** [comment]
@yishaigalatzer, PTAL. This is really serious.

nuget.exe uses SPNEGO just fine, as are not updated VS 2013 and downgraded v 3.4.1 of the package manager. But the version 3.4.2.830 blows SPNEGO completely. A credential box pops up, you may enter your creds if you want (it will not work), and after 3 attempts a message from Package Manager in the Output window is displayed:

```
[SmartAction Local] Unable to load the service index for source https://nuget.xxx.yyy:4488/nuget.
  Response status code does not indicate success: 401 (Unauthorized).
```

**Comment by rkeithhill** [comment]
@kkm000 That helps us get going again.  Thanks!!

**Comment by yishaigalatzer** [comment]
Fixed in 3.4.3, we have links on the closed 3.4.3 bugs with downloads

**Comment by rrelyea** [comment]
Here is a link to the original issue:
    https://github.com/NuGet/Home/issues/2521
That issue has been fixed in 3.4.3 (which is soon to be released), and like @yishaigalatzer said, there is a link to a private build of .vsix if you'd like to verify it fixes your issue.

**Comment by kkm000** [comment]
@rrelyea, @yishaigalatzer Thanks for the quick triage and the link to the fix! When do you think, roughly, the updated build could be available from the Gallery? Just planning ahead how to handle that internally (wait out, or have all engineers update from the above version, or update when they report, or..)

**Comment by rrelyea** [comment]
Should be out this week.

**Comment by kkm000** [comment]
@rrelyea: Excellent, thank you!
