### ISSUE TITLE
Solution PackageManager Version ComboBox can select separator via keyboard

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2606]
We couldn't repro this crash: https://github.com/NuGet/Home/issues/2540
So we took a null check fix.

@alpaix and @rrelyea figured out the way to repro.

Select the version separator via keyboard -- works in Solution NuGet Package manager.
In Project Package Manage -- it isn't possible to select.

**Comment by spadapet** [comment]
Just need to make sure that the separator isn't allowed to have focus or be selected.
