### ISSUE TITLE
Package installation takes more time

### ISSUE THREAD

**Issue by mathikp** [NuGet/Home#2609]
Hi,
We have used created the NuGet Package along with 400 files for our localization support with bulk of .js files. While we install this NuGet the installation process was very slow and it took 15 mins to install in VS2015. How can we improve the installation perfomance with bulk localization files? I have checked with AngularJS.Locale.1.5.3 NuGet it contains around 800 files but it took 30 seconds to install. Can anyone suggest to pack localization files without installation performance problem?

**Comment by rrelyea** [comment]
Can you please send us a package to support @ nuget . org

**Comment by mathikp** [comment]
Thanks for the update. I have check with my package with AngularJS.Locale they have used **i18n** as directory name of localization files. I have updated my package localization files directory name as **i18n** and try to install its installed in 20 seconds. 

Please update the below details to us.
1. What is the purpose of **i18n** ? 
2. If we used the package in console application it installed without time delay. But tooks more time to install that same package in MVC5 application in VS2015.  
3. Why we used the localization directory named like this?
4. How its installed fraction of seconds if we used **i18n** as directory name ? 
5. Is the directory names are handled by default in NuGet package manager?
6. Have we used this directory in our own packages ? Is there any licensing required to use this?

**Comment by rrelyea** [comment]
@mathikp - what version of nuget.tools.vsix are you using? if earlier version, please try latest.
is the project under source control?

**Comment by mathikp** [comment]
We have tried the latest VSIX of v3.4.2.830. And the issue raised in ASP.NET 4.5 Web Application (MVC) in VS2015 only. The package working fine in Console applications. And we need more info about TFM i18n.

**Comment by jainaashish** [comment]
This issue is not related to NuGet, please read about i18n online or other sources. This is a general approach for globalization, nothing specific to NuGet. From NuGet standpoint, you may refer [this link](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages) to know how to create localized packages.
