### ISSUE TITLE
Core project targeted  to framework net45 brings the net451 dependencies 

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#2610]
Repro Steps 
- Create a core Class Library 
- Change the project.json to 
  {
  "version": "1.0.0.0",
  
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24008"
  },
  
  "frameworks": {
     "net45": { }
  }
  }
- Build 
- Now add a .Net Console application , Add a project.json file to the same 
- Add below to the project.json 
  {
  "frameworks": {
    "net45": { }
  },
  "runtimes": {
    "win": { }
  }
  }
- Change the properties of the console application to point to Target Framework 4.5 
- Build 
- Reference core class library from console application.

Expected 
Reference works , packages are restores , build success and you are able to use the reference.

Actual 

Warning 
![45](https://cloud.githubusercontent.com/assets/12449387/14649153/a1e031c6-061a-11e6-918f-acf1632be0df.JPG)

output 
![45_2](https://cloud.githubusercontent.com/assets/12449387/14649161/a7fbd0f6-061a-11e6-93c0-0e06fc614bf9.JPG)

Not able to use the reference.

**Comment by emgarten** [comment]
The _may be incomplete_ warning occurs when the DTE reference property `Reference3.Resolved` is false. It lets the user know that that NuGet is unable to walk all of the references, it continues on with the restore, but in this case the warning is real as it cannot find the project.json file in the child project.

I don't see the error message for the build warning about 4.5.1 in NuGet either. I think this issue is coming from the project system.

NuGet will check project to project compatibility, when it fails the error is in the form: `Project {0} is not compatible with {1}.`

**Comment by jinujoseph** [comment]
@jasonmalinowski

**Comment by rrelyea** [comment]
The scenario isn't supported. When you use .NET Standard 1.5, you must target framework NET 4.6.2.

**Comment by jinujoseph** [comment]
Here i am trying to call consoleapplication (net45) to target core class library (net45) , should be able to do , if i change this to 4.5.1 ...every thing works fine.
Can you pls reopen this

**Comment by emgarten** [comment]
@rrelyea it's net45 but targeting the netstandard library, this should be fine.

**Comment by jasonmalinowski** [comment]
csproj.dll/msvbprj.dll is the thing that is producing this warning. We ask the xproj project's IVsHierarchy for it's TFM, and they're answering back .NET 4.5.1 even if you've said you're targeting net45. Not sure if the fix here is to:
1. Disable the check if the target is an xproj. We already do this for portable-targeting references.
2. Ensure the xproj isn't lying.
3. Both 1 and 2.

**Comment by jinujoseph** [comment]
Talking to @abpiskunov , The right solution is to create a new IVsHierarchy property and consume it for projects that can have multiple TFMs - this should be implemented in U3, then we will send all  TFMs, and caller can consume that new property.

Till that happens , to unblock the nuget scneario , does option 1 sounds feasible? Do we see any issue with disabling this check ?

**Comment by jasonmalinowski** [comment]
I've checked in internal pull request 20413 which disables the check. We should update the code properly once we have the ability to do so, but until then yeah this check isn't useful.
