### ISSUE TITLE
NuGet.Server custom IPackageAuthenticationService fiasco

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#2611]
We run a `NuGet.Server`-based server on our intranet. The server has a custom `IPackageAuthenticationService`, that authorizes package publishing through ASP.NET role (which is further defined through Active Directory group membership). I tried to upgrade the server to `NuGet.Server` v2.10.x (latest), and my attempt semi-failed.

Out current code uses `NuGet.Server`  v2.8.5, and this version uses Ninject to compose services, so all I had to do was

``` c#
[assembly: WebActivatorEx.PreApplicationStartMethod(typeof(SmartAction.NuGetServer.Initializers), "Start")]
namespace SmartAction.NuGetServer {
  public static class Initializers {
    public static void Start() {
      NinjectBootstrapper.Kernel.Rebind<IPackageAuthenticationService>().To<MyOwnFancyPackageAuthenticationService>();
    }
. . . 
```

The new version seems to have get ridden of Ninject in favor of semi-opaque `ServiceResolver`. Now, short of forking the Server's source, I found the following way to hack my authentication service in (sans locking entirely -- I am omitting locking for clarity)

``` c#
public class MyServiceResolver : IServiceResolver {
  static DefaultServiceResolver default_resolver_ = new DefaultServiceResolver();
  IPackageService package_service_ = null;

  public object Resolve(Type type) {
    if (type == typeof(IPackageService)) {
      if (package_service_ == null) {
        var repo_service = (IServerPackageRepository)default_resolver_.Resolve(typeof(IServerPackageRepository));
        package_service_ = new PackageService(repo_service, new MyOwnFancyPackageAuthenticationService());
      }
      return package_service_;
    }
  }
}
```

and then call `ServiceResolver.SetServiceResolver()` with the instance of this thing on startup.

Am I doing it wrong? There is something uneasy about this code, as it is entirely based on the knowledge of the internal structure of the `DefaultServiceResolver`, and on other assumptions which may or may not be valid even after a minor Server package upgrade.

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2996
