### ISSUE TITLE
Nuget.Server: Double-checked locking does not work

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#2612]
It has been long known that [double-checked locking is broken](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html). Here is a [prime example of double-checked lock in `NuGet.Server` code](https://github.com/NuGet/NuGet.Server/blob/8a068e8981c8d0e2f008efaf376998b0e6cc8b4d/src/NuGet.Server/Core/ServiceResolver.cs#L12).

Coming from the C++ land, I came to trust memory barriers to remedy the memory ordering issues (see the Doug Schmit's pattern in the referenced article), but I could never actually confirm they work same in .NET. I'd be happy to write a PR, but I would be even more happier to know the change I would send is correct. It would me certainly _more correct_ than the current code.

**Comment by rrelyea** [comment]
Lazy<T> may be the right solution here.

**Comment by kkm000** [comment]
Looks like it. Internally it uses thread barriers to load/store values when constructing the object--it's `LazyInitValue` method is very interesting!

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2995
