### ISSUE TITLE
With csproj->xproj references, the build fails unless all nested references are added to the csproj

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2615]
You need a solution with three projects, a csproj that references and uses an xproj. And the xproj references and uses another xproj. Ideally the csproj only needs to reference the first xproj, but the build won't succeed until it references both xprojs.

**REPRO**
- Install the latest dotnet tools and patches (ask @spadapet for info)
- Download the following refs.zip and unzip it:
- [refs.zip](https://github.com/NuGet/Home/files/226864/refs.zip)
- Open the refs.sln solution in VS 2015
- Build Solution

**RESULT**
You'll see this error in the error list:

![image](https://cloud.githubusercontent.com/assets/2523431/14656046/2d5e5baa-063a-11e6-92e8-ca6c006b3a07.png)

If you build on the command prompt, here is the text of the error:

```
CoreCompile:
  C:\Program Files\dotnet\dotnet.exe build "F:\cabs\refs\CoreLib2" --configuration Debug --no-dependencies --build-base
  -path "F:\cabs\refs\artifacts"
  Project CoreLib2 (.NETFramework,Version=v4.5) was previously compiled. Skipping compilation.
  Project CoreLib2 (.NETStandard,Version=v1.3) was previously compiled. Skipping compilation.
Done Building Project "F:\cabs\refs\CoreLib2\CoreLib2.xproj" (default targets).

C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140,5): error : The project.json is referencing
the project 'F:\cabs\refs\CoreLib\CoreLib.xproj', but an output path was not specified on an item in the ProjectReferen
cesCreatingPackages property. [F:\cabs\refs\WinExe\WinExe.csproj]
Done Building Project "F:\cabs\refs\WinExe\WinExe.csproj" (default targets) -- FAILED.
```

**EXPECT**
Build succeeds, I shouldn't have to reference both xproj libraries from the csproj executable.

**Comment by sayedihashimi** [comment]
Should we label this as RC2 and `blocking-release`?

**Comment by jasonmalinowski** [comment]
This is an issue trivially worked around, and the references you have to add would be required if everything was just csproj in the first place. This isn't nearly as important as the other bugs @spadapet has filed and we are investigating.

**Comment by jasonmalinowski** [comment]
Given the csproj/xproj convergence plan, this bug will not be fixed.

**Comment by sachinjoshi27** [comment]
@jasonmalinowski I'm facing exactly the same issue, however in our csproj we have explicitly referred both the xprojs.
