### ISSUE TITLE
Microsoft.DotNet.Props was not found.

### ISSUE THREAD

**Issue by xoofx** [NuGet/Home#2616]
Hi there,
will trying to build latest dev branch, I'm getting this error:

```
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found.
```

From where can I install this file? (Tried latest dotnet-cli runtime but it is not there...)

**Comment by rrelyea** [comment]
We have some dependencies in our build that are out of sync with things that are externally available right now. Choices:
1) Using the release-3.4.3 branch may be easiest right now.
or
2) With Dev branch: use build.ps1 and VS Code to work in NuGet.Core.sln and normal VS for NuGet.Client.sln

**Comment by daveaglick** [comment]
May I suggest adding this information to the readme in the NuGet.Client repository until the workarounds are no longer needed? It took me a long time of trying different things until I stumbled on this issue (especially since the issue is now closed).

**Comment by xoofx** [comment]
FYI @daveaglick with .NET Core rc2, branch like "release-3.5" can be compiled

**Comment by akajains** [comment]
Can we change the path to point to correct location?

**Comment by Silwood** [comment]
After upgrade  Microsoft .NET Core Tools (Preview 1) to RC2, I was able to open the sample solution without error. It didn't worked with RC1.
