### ISSUE TITLE
Install and update download packages without checking the packages folder first

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2618]
PackageManagement does not check if a package already exists in the packages folder before retrieving it from the source. Later when it goes to install the package it finds one with the same id and version and skips using the package it downloaded.
### Steps
1. Create a solution with 2 class library projects
2. in the first project: `install-package nuget.versioning -version 3.3.0`
3. clear the global cache with `nuget.exe locals -clear all`
4. _Verify that nuget.versioning no longer exists in the cache_
5. _Verify that nuget.versioning exists in the solution packages folder_
6. in the second project: `install-package nuget.versioning -version 3.3.0`
7. Check the global packages folder
### Expected
1. The primary source will be checked for the package to make sure it exists.
2. PackageManagement will check if the package already exists for the solution
3. No downloads will occur since the package is already installed for the other project.
### Actual
1. The primary source is checked for the package during the gather.
2. The package is downloaded again and added to the global cache
3. NuGet loads the nupkg from the global cache and begins the install process
4. Before extracting the package again NuGet detects that the package is already installed and skips using the copy from the global folder.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@84071d8ee466dbd9db4d670f3671c632db43e6a0

**Comment by rrelyea** [comment]
great. please make sure to port to 3.4.5 branch, in addition to dev.

**Comment by emgarten** [comment]
Ported to 3.4.5 
NuGet/NuGet.Client@81e26b1e89e7bf86d1dc4f224b02e97c471cf1e6
