### ISSUE TITLE
Usage of NuGet logo 

### ISSUE THREAD

**Issue by suchja** [NuGet/Home#2620]
I cannot find any license / usage information about the logo. Is it allowed to use the logo in articles / videos discussing NuGet?

**Comment by harikmenon** [comment]
Great question. Generally it is under CC, but I'm confirming this and will let you know soon.

**Comment by suchja** [comment]
Thanks!

**Comment by harikmenon** [comment]
Here you go. All our assets are covered under [https://creativecommons.org/licenses/by/2.0/](CC-BY). We will shortly add this detail to the .NET Foundation website and link to that from NuGet.org. Thanks for raising this issue. This helped start the discussion with the .NET Foundation team and resolve this for all projects under .NET Foundation.

**Comment by suchja** [comment]
Sounds great! I'm not closing this issue as I guess you need it for tracking and reference. If not, my problem is solved and the Issue can be closed. THANKS!

**Comment by maartenba** [comment]
@harikm86 We may want to add that to our Media repo https://github.com/NuGet/Media

**Comment by harikmenon** [comment]
done. added you for review https://github.com/NuGet/Media/pull/1

**Comment by harikmenon** [comment]
Tracking the changes for this on the PR.
