### ISSUE TITLE
Nuget doesn't read authentication from Nuget.config

### ISSUE THREAD

**Issue by CheloXL** [NuGet/Home#2621]
I think this might be related to #2529.
I have a private nuget feeds (using Nuget.Server). I also have a root (for all my solutions) Nuget.config where I have defined my custom sources/credentials, etc.
This configuration was working fine until the latest update. Now, every time I try to do something (from inside VS) using nuget, it asks for the credentials. Once I complete them, I can continue working as usually (no need to enter the credentials for the whole VS instance).

Checking with Fiddler I see that nuget is doing all the requests as usually but it is not including the Authorization header on first requests. Only after I fill in the credentials dialog the requests starts to include the headers.

**Comment by rrelyea** [comment]
The related issue you pointed to: #2529 has a link to a private build that has fixed the issue.
Please try that build out and re-open this issue if it is not addressed with that fix.

**Comment by CheloXL** [comment]
@rrelyea If you read that issue, I confirmed that the authentication thing worked with the private build. I opened THIS issue because the private build asks for authorization every time I open visual studio and doesn't read the authorization values from the .config.

**Comment by rrelyea** [comment]
Thanks for the clarification. That wasn't clear to me. Reopening.

**Comment by rrelyea** [comment]
@CheloXL  - where is your "root" nuget.config exactly? and can you show us the approximate location of your projects in relation to that location? if we have that info, we'll try to repro.

**Comment by CheloXL** [comment]
I have a folder where I have all my projects. On the root of that folder I have my Nuget.config.
Inside that folder I have subfolders that may/maynot have more subfolders where I have the different solutions.
So, basically:

```
- Code
|> Nuget.config
|> Folder1
|> Folder2
--|> SubFolder1
--|> SubFolder2
```

**Comment by alpaix** [comment]
I tried various combinations but I wasn't able to repro.
@CheloXL can you provide more details or maybe share your NuGet.Config with wiped out creds?

**Comment by CheloXL** [comment]
Sure, here you have.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositorypath" value="Packages\" />
        <add key="DefaultPushSource" value="http://nuget.private.com" />
    </config>
    <packageRestore>
        <add key="enabled" value="True" />
    </packageRestore>
    <apikeys>
        <add key="http://nuget.private.com" value="11111111-1111-1111-1111-111111111111" />
    </apikeys>
    <packageSourceCredentials>
        <_x0032_DSoluciones>
            <add key="Username" value="nuget" />
            <add key="ClearTextPassword" value="MyPassword" />
        </_x0032_DSoluciones>
        <_x0032_DSolucionesPush>
            <add key="Username" value="nuget" />
            <add key="ClearTextPassword" value="MyPassword" />
        </_x0032_DSolucionesPush>
    </packageSourceCredentials>
    <packageSources>
        <add key="2DSoluciones" value="http://nuget.private.com/nuget" />
    </packageSources>
    <disabledPackageSources>
        <add key="2DSolucionesPush" value="true" />
    </disabledPackageSources>
</configuration>
```

**Comment by alpaix** [comment]
Thanks for sharing it. I've got a repro!

I'm seeing following requests being sent by the NuGet Package Manager:

> 63    301 HTTP    nuget.private.com   /nuget  190 private text/html; charset=iso-8859-1   devenv:32608            GET 
> 64    302 HTTP    www.private.com /   20      text/html   devenv:32608            GET 
> 65    403 HTTP    www.private.com /home/  3,319       text/html; charset="utf-8"  devenv:32608            GET 

No credentials were sent in this transaction. Expected authentication protocol response in this case is 401 - not authorized with WWW-Authorize header listing supported authentication methods. This would trigger authentication negotiate by `HttpClient`. I assume you have a custom authentication module on your server. Is it possible to fix its behavior?

Also can you share NuGet server and client version you used before the update?

**Comment by CheloXL** [comment]
mmm.. Didn't know you would use that url for testing. The real url (that's a fake one) is not accessible from outside our VPN, sorry for the confusion.

What I get when I open the nuget package manager in vs is:

> GET http://nuget.private.com/nuget 401 Unauthorized (text/html)

After that, VS asks for credentials. I believe that before VS asks for credentials, nuget should check if the credentials are already setup on the .config file (it was that way before the update). "Remember my password" seems to be working only for the current session also.
Nuget server 2.10.2. Package manager 3.4.3.844

**Comment by CheloXL** [comment]
Ah... BEFORE the update: Server, same version. Package manager: don't remember, but the one that comes with VS2015 update 2.

**Comment by alpaix** [comment]
Okay VPN usage explains that weird behavior. 

Sorry for bugging you again, can you try renaming your source using alphabetic-only ascii symbols? Just to ensure it's not an encoding issue.

**Comment by alpaix** [comment]
Also to confirm. Does it find credentials if you put .config file at solution folder?
What's the full path to solution file?

**Comment by alpaix** [comment]
Here is the latest client build you can try as well:
https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.4.3.854.vsix

**Comment by CheloXL** [comment]
@alpaix I can confirm that the version you linked above fixed my issues. Now the authentication is automatic. Now I'm correctly getting

> GET http://nuget.private.com/nuget 401 Unauthorized (text/html)
> GET http://nuget.private.com/nuget 307 Redirect to http://nuget.private.com/nuget/

Thanks!

**Comment by alpaix** [comment]
That's typical auth with redirect scenario.
Closing as duplicate to https://github.com/NuGet/Home/issues/2521.
