### ISSUE TITLE
Visual Studio crash after trying to install package at solution level through package manager

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2622]
Repro Steps:
1. use project http://github.com/dotnet/roslyn-analyzers
2. Try installing Newtonsoft.Json package for all projects at solution level through package manager ui.
3. visual studio will crash here.

I also have dump file, let me know if you need it.
Stack trace:

NuGet.LibraryModel.dll!NuGet.LibraryModel.LibraryRange.TypeConstraint.get() Line 31 C#
NuGet.LibraryModel.dll!NuGet.LibraryModel.LibraryExtensions.IsEclipsedBy(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}, NuGet.LibraryModel.LibraryRange other = {NuGet.LibraryModel.LibraryRange}) Line 15    C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 185   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#  NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#
NuGet.DependencyResolver.Core.dll!NuGet.DependencyResolver.RemoteDependencyWalker.ChainPredicate.AnonymousMethod__0(NuGet.LibraryModel.LibraryRange library = {NuGet.LibraryModel.LibraryRange}) Line 198   C#

**Comment by rrelyea** [comment]
please validate that @emgarten's latest 3.4.3 fix solves this.

**Comment by jainaashish** [comment]
Duplicate of https://github.com/NuGet/Home/issues/2558 which is already fixed.
