### ISSUE TITLE
NuGet won't restore packages from local source when offline.

### ISSUE THREAD

**Issue by MichaelSimons** [NuGet/Home#2623]
**Repro Steps**
1. Download latest dotnet cli on windows - https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe
2. mkdir OfflineTest
3. cd OfflineTest
4. dotnet new
5. Create the following NuGet.config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
<!--To inherit the global NuGet package sources remove the <clear/> line below -->
<clear />
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
<add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
<add key="Microsoft Visual Studio Offline Packages" value="C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"/>
</packageSources>
</configuration> 
```
1. unplug network or create firewall outbound rule that blocks network connection to all programs.
2. dotnet restore

**Actual Results:**
Restore failed, the offline package source was not used.

```
error: Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.
error:   An error occurred while sending the request.
error:   The server name or address could not be resolved
```

**Expected Results:**
The local "offline" package source would be used.

The real scenario in which I encountered this was using the .NET VS Code tooling to create a project while being offline.  Package restore failed even though VS has a local offline package source configured.

**Comment by emgarten** [comment]
This should work if `--ignore-failed-sources` is passed to restore. Missing sources can affect the restore result which is why nuget defaults to failing on this, but the offline scenario here looks like it could be improved.

**Comment by MichaelSimons** [comment]
@emgarten yes the `--ignore-failed-sources` option works.  Are you suggesting the offline support should be improved within NuGet?  Without that it seems like NuGet users would have to make a decision in cases like this - do I want offline to work or do I want source verification.  Alternatively VS or CLI could add logic to conditionally use `--ignore-failed-sources` if they detect offline but this logic seems better placed within NuGet.

**Comment by yishaigalatzer** [comment]
This is by design. Please don't add logic to work around it.

**Comment by bob-devereux-zocdoc** [comment]
Why was it designed that way?

**Comment by yishaigalatzer** [comment]
Because there are several cases where you will get different results depending on your sources.

We are considering a strict mode that will also work offline, that would cover many of the cases and reduce the pain here. The comment is around not changing this behavior as is. I should have been more clear

**Comment by tandeday** [comment]
@yishaigalatzer  As a newcomer to the nuget ecosystem, what is the status of the strict mode you mentioned which would allow offline builds?

**Comment by thomasd3** [comment]
in the case of docker builds, right now we get all the containers pulled at every build without having an offline mode.

**Comment by beachwalker** [comment]
Also interested into the strict mode... requirement here in the ecosystem? any news? stops us from using core dotnet tools, currently.
