### ISSUE TITLE
"nuget.exe delete" doesn't delete a local package folder after the last version is deleted

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2624]
Using nuget.exe 3.4.3.854
Download any nupkg so that you can do the repro steps.

**REPRO**
- mkdir local
- nuget.exe add newtonsoft.json.8.0.3.nupkg -Source local
- nuget.exe delete newtonsoft.json 8.0.3 -Source local

**RESULT**
The folder "local\newtonsoft.json" still exists even though it is now empty after deleting the "8.0.3" subfolder.

**Comment by jainaashish** [comment]
This is by design, since NuGet didn't create the `local` folder
