### ISSUE TITLE
nuget.exe delete won't prompt for credentials (it's in non-interactive mode)

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2626]
Using nuget.exe 3.4.3.854

**REPRO**
- nuget.exe delete foo 99.99 -Source nuget.org

**RESULT**
WARNING: No API Key was provided and no API Key could be found for 'https://www.nuget.org/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
WARNING: Deleting foo 99.99 from the 'https://www.nuget.org/api/v2/package'.
  DELETE https://www.nuget.org/api/v2/package/foo/99.99
  Unauthorized https://www.nuget.org/api/v2/package/foo/99.99 335ms
Please provide credentials for: https://api.nuget.org/v3/index.json
UserName: **Cannot prompt for input in non-interactive mode.**

**EXPECT**
The command prompt shouldn't be in non-interactive mode. If there is some other reason that the username can't be typed, then show the real reason.

**Comment by rrelyea** [comment]
Putting in 3.4.3 for initial triage visibility.

**Comment by spadapet** [comment]
NOTE: Not a regression, I get the same thing with nuget.exe 2.8.60717.93 and 3.3.0.212
So, probably not needed for 3.4.3

**Comment by vijaik** [comment]
This issue happens during a push too.

**Comment by spadapet** [comment]
This is working with the latest code (someone must've fixed it for a different bug).
nuget.exe delete and push will ask for credentials unless -NonInteractive is used.
