### ISSUE TITLE
NuGet.exe Verbose mode should show the download url

### ISSUE THREAD

**Issue by magmax** [NuGet/Home#2629]
When enabling the verbose mode, it should show the path where the package is resolved.

Currently it just shows the "possible paths", but it would be useful to know the real final path to be used.

**Comment by rrelyea** [comment]
Thanks for the feedback. Please help with a bit more detail:
A) Which tool are you using?
- NuGet.exe
- NuGet package manager in VS?
- Other?

B) What version of that tool are you using?

**Comment by magmax** [comment]
Sorry!

nuget.exe 3.3.0.212

Thank you!

**Comment by magmax** [comment]
Output example:

```
$ nuget install comparenetobjects -version 3.01.0.0 -verbosity detailed
WARNING: Failed to load C:\bin\NuGet.ServerExtensions.dll, if this extension was downloaded from the
 internet please make sure it got unblocked (right click, properties, unblock).
WARNING: Could not load file or assembly 'NuGet.ServerExtensions, Version=2.8.60318.667, Culture=neu
tral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from H
RESULT: 0x80131515)
Feeds used:
  C:\Users\me\AppData\Local\NuGet\Cache
  https://www.nuget.org/api/v2/
  c:\tmp\packages

Attempting to gather dependencies information for package 'comparenetobjects.3.1.0' with respect to
project 'C:\tmp\bar', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'comparenetobjects.3.1.0' with DependencyBehavior 'Lo
west'
Resolving actions to install package 'comparenetobjects.3.1.0'
Resolved actions to install package 'comparenetobjects.3.1.0'
Adding package 'CompareNETObjects.3.1.0' to folder 'C:\tmp\bar'
Added package 'CompareNETObjects.3.1.0' to folder 'C:\tmp\bar'
Successfully installed 'CompareNETObjects 3.1.0' to C:\tmp\bar
```

I demand to know where was it found finally.

**Comment by rrelyea** [comment]
Logger may not be passed through the gather step (per @emgarten)

**Comment by jainaashish** [comment]
@magmax can you pls take the latest nuget.exe (3.4.3) from here https://dist.nuget.org/index.html and confirm if it gives you enough logs in verbose? We had recently added download urls and other stuff in there so hopefully it should be enough but still if you feel anything missing, then let us know!

**Comment by magmax** [comment]
Now it is really verbose.

Thank you very much!
