### ISSUE TITLE
Weird behavior with left zeros on versions.

### ISSUE THREAD

**Issue by magmax** [NuGet/Home#2630]
I'm having a weird problem with left zeros on CompareNetObjects package. From an empty directoy, I can do:

```
nuget install CompareNetObjects -version 3.01.0.0
nuget install CompareNetObjects -version 3.1.0.0
```

And it will create the 3.01.0.0 folder AND the 3.1.0.0, but doing (in an empty folder):

```
nuget install CompareNetObjects -version 3.1.0.0
nuget install CompareNetObjects -version 3.01.0.0
```

it just creates the 3.1.0.0 (what should be the correct behavior).

This implies that depending on what command is executed first, the compilation works or not.

In addition, when asking nuget.org from a nuget console, it returns the version as an object. The version shows "3.1.0.0", but running it with "toString()" it shows 3.01.0.0, despite being the same object:

```
PM>$pkg = Find-Package -AllVersions -Id CompareNETObjects -source https://nuget.org/api/v2/ -exactmatch
PM> $pkg

Id                                  Versions                                 Description                                                                                                                                                                      
--                                  --------                                 -----------                                                                                                                                                                      
CompareNETObjects                   {3.05.0.0, 3.04.0.0, 3.03.0.0, 3.02.0... What you have been waiting for. Perform a deep compare of any two .NET objects using reflection. Shows the differences between the two objects.

PM> $pkg.Versions[0]


Version         : 3.5.0.0
IsLegacyVersion : False
Revision        : 0
Major           : 3
Minor           : 5
Patch           : 0
ReleaseLabels   : {}
Release         : 
IsPrerelease    : False
HasMetadata     : False
Metadata        : 
```

_Note_: No 3.05.0.0 version is shown in any `$pkg.Versions` object internals.

I think this may be a bug in the `toString` method that is generating a mayor bug when creating the local folders, but I may be wrong.

**Comment by rrelyea** [comment]
What version of nuget.exe are you using?

**Comment by yishaigalatzer** [comment]
#### Some more info

The data objects in PowerShell are different than what happens in command line. Here is some more input on how things _should_ work

We have two scenarios:
1. Packages.config
2. V3 folder structure (hierarchial structure) or project.json related global packages folder.

In scenario one the expectation is that the project will keep a reference to the dll, the path is going to have a hard coded relative path including the version. This means that projects authored years ago will still need to work. And hence in this scenario the version written to disk should be what is defined by the nuspec (at similarly in the metadata from the server).

In scenario two, the version comes from project.json or the lock file, and there is no server interaction nor a hardcoded path anywhere, so the desire here is to hit a predicatable path without having to scan the drive and reinterpret versions. So this path will write a normalized version. Simply describing normalization 1, 1.0, 1.0.0, 1.0.0.0 -> 1.0.0 and 1.0.0.1 -> 1.0.0.1 

When installing a package through the nuget.exe install command we fall into the packages.config scenario.

The latest version of nuget.exe is 3.4.2-rc (we are going to ship 3.4.3 shortly).

**Comment by magmax** [comment]
Hi again.

That is not the point.

The problem starts with the package own version. The last version of package `CompareNetObjects` is 3.05.0.0, and when you ask `nuget.exe` to install it, it creates the `CompareNETObjects.3.05.0.0` folder.
The point is when you specify the version without the zero: `nuget install CompareNetObjects -version 3.5.0.0`, because it will create the `CompareNETObjects.3.5.0.0` folder, despite it already has the `CompareNETObjects.3.05.0.0` one, creating a conflict and making our builds to fail.

This problem is not deterministic, because it depends on which one is requested before: if 3.5.0.0 is asked before 3.05.0.0, then everything goes right.

IMHO, `nuget` should protect me against such a version mistake and avoid the left-zero problem, since both versions deploy exactly the same binaries.

**Comment by yishaigalatzer** [comment]
Yes I completely agree, I was describing how it is supposed to work rather than how it does

**Comment by ghost** [comment]
I'm having this issue suddenly as well with CompareNETObjects version 3.05.0.0 ... any workaround for the time being?

**Comment by magmax** [comment]
Look for the 3.5.0.0 directory in the cache and rename it to 3.05.0.0. It will start to work suddenly.

**Comment by ghost** [comment]
Thanks that worked!

**Comment by jainaashish** [comment]
We normalize all packages version and tried it to make it better with 3.5.0. Please check with latest version and try to have the correct package version at first place.
