### ISSUE TITLE
Visual Studio XML Comments Not Visible

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#2631]
If I create a Nuget package for a DLL to be used in another solution, the class XML comments (summary, remarks, etc) are not visible in the Visual Studio object browser.

**Comment by rrelyea** [comment]
Would love to help you address...a few questions:
do you see the intellisense in the code editing experience?
if not,
   in the packages folder, is there an .xml file next to the .dll?
   How are you creating that nupkg? (including what version of different tools like NuGet.exe)
   Is the project configured to create DLLName.xml with the intellisense files?
   What version of VS are you using?

**Comment by ghost** [comment]
Yes, I do see the Intellisense.  
In the packages folder there is not an XML in the lib directory.
I am creating the package via the Nuget Package Explorer
The project is configured to create the XML documentation.
I tried this in both VS2013 and VS2015.
Thanks for your help.

**Comment by ghost** [comment]
I did not realize that I had to include the xml file in the Nuget package.  (seems so obvious now).

Thanks.
