### ISSUE TITLE
Excessive allocations in version comparsion code

### ISSUE THREAD

**Issue by pakrym** [NuGet/Home#2632]
1. `HashCodeCombiner` is class so it gets allocated a lot
2. `SemanticVersion` operators create `VersionComparer` for each call
3. `SemanticVersion.IsPrerelease` allocates `IEnumerator` while underlying type of `_releaseLabels` is array.

**Comment by joelverhagen** [comment]
Seems reasonable, but where was this perf problem apparent? What scenario I mean.

**Comment by pakrym** [comment]
Resolving libraries in `dotnet build`. Around ~30 mb allocations in total from version comparsion.
