### ISSUE TITLE
NuGet build task picks up project.lock.json, even when the project doesn't have a project.json

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#2636]
I just ran into this - NuGet build task picks up project.lock.json even when the project doesn't have a project.json. 

Image this:

Project 'A' has a project.json in Branch future, but not in Branch master

1) Starting in _future_, you restore _A_
2) Switch to branch _master_
3) Build

Notice that NuGet task picks up the project.lock.json from future, even though the project does not have a project.json. It should check for project.json is present before opt'ing in the project.lock.json.

**Comment by jainaashish** [comment]
No more project.json besides, those build tasks are handled by Project system only.
