### ISSUE TITLE
[NuGet.PackageManagement] Uninstall.ps1 should not swallow exception and not fail uninstall package

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#264]
[NuGet.PackageManagement] Uninstall.ps1 should not swallow exception and not fail uninstall package
Functional test: UninstallPackageSwallowExceptionThrownByUninstallScript

**Comment by danliu** [comment]
The old behavior was actually swallow the exception thrown by uninstall.ps1 and not fail uninstall package.

With the new code that we have, we are re-throwing the exception and rolling back the uninstall action.

So this is more of a test case issue.
