### ISSUE TITLE
Add xplat nuget restore flag that fails restore when exact dependency not found

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#2645]
Right now, when NuGet can't find a dependency with the version number in a `project.json`, it tries to find an applicable version in the source feed. This causes problems like the ones listed in https://github.com/dotnet/buildtools/pull/652. The two that are probably the most important are:
1. The build isn't repeatable. If these "fuzzy-matched" dependencies are used, the build depends on which packages are available on the feed which may change at any time. (Similar to `*` dependencies, which we don't use for this reason.)
2. The wrong packages sometimes break builds.

We've hit this a few times now because we have a rapidly-changing prerelease, occasional minor/patch version bumps, and a auto `project.json` updater. We get into a state where we depend on `1.0.1-rc2-444` but the actual package is `1.1.0-rc2-444`, which makes NuGet restore `1.1.0-rc2-123` or something like that. We want to improve the auto-upgrade so these errors are avoided, but this seems like an issue that might be good to have detected during the restore call.

A new flag, `--ensure-package-exists` could check to make sure a package exists on the feed. Dependencies still upgrade as necessary to satisfy parent dependencies (since they are `>=`), but "auto-detection" of an applicable package on the feed would be disabled. (Might want a better flag name--I'm not sure exactly which NuGet mechanism this affects.)

/cc @weshaggard @ericstj @mellinoe @dhusemann

**Comment by emgarten** [comment]
Does this show up as a warning for you? Or is this a top level dependency in project.json?

You may want to use `[1.0.1-rc2-444]`. By specifying `1.0.1-rc2-444` you are actually saying `>= 1.0.1-rc2-444`.

**Comment by ericstj** [comment]
Using exact match isn't quite the same.  Suppose project A references package C version 2 and project B and project B references package C version 1.  Exact match here would cause A to fail to restore due to conflict.

**Comment by dagood** [comment]
Yep, it shows up as a warning:

> warn : Dependency specified was System.IO (>= 4.0.11-rc3-24022-00) but ended up with System.IO 4.1.0-rc2-23712.

There are other warnings that CoreFX gets, but maybe we could set up a regex to turn this particular type of warning into an error. (The warnings are tons of package downgrades. They look intentional but I'm not completely sure. [Example](https://gist.github.com/dagood/54607aa8f1d561ae22df703cf4321adf))

Or maybe there's a way to change these warnings into errors through NuGet? That would seem to be what this issue's asking for. :smile:

**Comment by emgarten** [comment]
The warnings as errors feature is being tracked here: https://github.com/NuGet/Home/issues/2395

**Comment by ericstj** [comment]
@dagood we actually need to clean up those warnings

**Comment by dagood** [comment]
Aha, thanks @emgarten! I didn't see that in my searches.

@ericstj Cool, I'll log a corefx issue on that.

**Comment by ericstj** [comment]
I think we already have an uber issue tracking moving to all latest packages and using non-deprecated monikers.

**Comment by dagood** [comment]
Hmm, I can't find it, but I'll leave it be, then.

Closing this--already ways to detect this now and plans already exist to be able to formally make it a restore error. Thanks!
