### ISSUE TITLE
Restore randomly fails with An item with the same key has already been added.

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#2646]
``` C#
trace:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
trace:    at NuGet.ProjectModel.PackageSpecReferenceDependencyProvider.GetPackageSpecResolver(String rootPath)
trace:    at NuGet.ProjectModel.PackageSpecReferenceDependencyProvider.GetLibrary(LibraryRange libraryRange, NuGetFramework targetFramework, String rootPath)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.FindProjectMatch(LibraryRange libraryRange, NuGetFramework framework, GraphEdge`1 outerEdge, CancellationToken cancellationToken)
trace:    at NuGet.DependencyResolver.RemoteDependencyWalker.<FindLibraryMatch>d__10.MoveNext()
```

Is there some sort of race condition at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/PackageSpecReferenceDependencyProvider.cs#L334 which needs to be guarded against?

**Comment by yishaigalatzer** [comment]
Version?

**Comment by pranavkm** [comment]
This failed as part of the CLI build (http://dotnet-ci.cloudapp.net/job/dotnet_cli/job/rel_1.0.0/job/release_windows_nt_x64_prtest/1415/consoleText) so, CLI 1.0.0-rc2-002476.

**Comment by joelverhagen** [comment]
I'm looking into this.

**Comment by joelverhagen** [comment]
Yes, there is a potential for a race condition here. We have a caching mechanism in a method that can be called from multiple threads simultaneously. That cache is a `Dictionary`. This should clearly be a `ConcurrentDictionary`.

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/c9a1ca1364202a80183deabc229d5fbab8166a76.

**Comment by pranavkm** [comment]
Does the CLI need to pick up a new build of NuGet?

**Comment by joelverhagen** [comment]
Yes. @rrelyea, can someone (maybe me) bump the NuGet version in CLI to include this fix?
