### ISSUE TITLE
restore is not using stored credentials from nuget.config for VSTS feeds

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2647]
Our build machines are failing to restore packages from VSTS with the latest nuget.exe downloaded from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  (3.4.3 published today)

We are storing the PAT token with the above NuGet.exe but during restore it still prompts. Surprisingly nuget.exe install seems to work.

We use the following command to store the credentials:
.\nuget.exe sources remove -Name Test
$PAT = "Your personal access token"
$Feed = "Your url"
.\nuget.exe sources add -Name Test -Source $Feed -UserName $Env:UserName -Password $PAT

Store-creds 3.3/Restore 3.3  works. 
Store-creds 3.3/Restore 3.4.3 works.
Store-creds 3.4.3/Restore 3.3 does not work.
Store-creds 3.4.3/Restore 3.4.3 does not work.

**Comment by rrelyea** [comment]
@alpaix found that out settings Save code likely double encrypts encrypted strings in NuGet.config.

**Comment by rrelyea** [comment]
Working with the internal reporter to confirm that this is fixed with this private build:
1.download not yet final version 3.4.4. of nuget.commandline.nupkg from https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.4.4-rtm-870 
2.rename the .nupkg to .zip
3.Grab nuget.exe from inside the zip file in the tools directory.
4.Try this version of nuget.exe to verify that it has fixed your issue.
5.Tell us how it went

**Comment by yishaigalatzer** [comment]
Reopening for validation

**Comment by jainaashish** [comment]
Verified with 3.4.4-872 by adding sources through nuget.exe sources with username n pwd and then used these sources to browse/install packages.
