### ISSUE TITLE
NuGet.Client: Package not found bug when using private nuget source

### ISSUE THREAD

**Issue by mynkow** [NuGet/Home#2649]
When I try to restore a nuget using the CLI tool with the following configuration I get an error that the package is not found:

**C:\Users\user\AppData\Roaming\NuGet\nuget.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <activePackageSource>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>
```

Then I have a custom nuget source for a specific project:
**D:\ProjectX\nuget.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="MyPrivateSource" value="http://192.168.1.50/nuget" />
  </packageSources>
</configuration>
```

Now, if I execute one of the following commands I get an error:
current dir = D:\ProjectX\

`C:\Users\user\AppData\Local\NuGet\NuGet.exe install Microsoft.Owin -Source "https://api.nuget.org/v3/index.json"`
`Unable to find package 'Microsoft.Owin'.`

`C:\Users\user\AppData\Local\NuGet\NuGet.exe install Microsoft.Owin`
`Unable to find package 'Microsoft.Owin'.`

I get exactly the same error if I have defined the custom nuget source in `C:\Users\user\AppData\Roaming\NuGet\nuget.config` and the only way to restore any package is to remove the custom source. I also tried different combinations to specify active sources like this without any success:

```
<activePackageSource>
    <add key="All" value="(Aggregate source)" />
</activePackageSource>
```

The private nuget source is working correctly and I can publish/restore packages from there.

**Detailed output:**

```
λ C:\Users\user\AppData\Local\NuGet\NuGet.exe install Microsoft.Owin -Source "https://api.nuget.org/v3/index.json" -Verbosity detailed
GET https://api.nuget.org/v3/index.json/FindPackagesById()?$filter=IsLatestVersion&$orderby=Version desc&$top=1&id='Microsoft.Owin'
GET https://api.nuget.org/v3/index.json/Packages()?$filter=tolower(Id) eq 'microsoft.owin'&$orderby=Id
GET https://api.nuget.org/v3/index.json/Packages()?$filter=tolower(Id) eq 'microsoft.owin'&$orderby=Id
System.InvalidOperationException: Unable to find package 'Microsoft.Owin'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepository, IPackageRepository localRepository, IPackageConstraintProvider constraintProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVersions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean allowPrereleaseVersions)
   at NuGet.Commands.InstallCommand.InstallPackage(IFileSystem fileSystem, String packageId, SemanticVersion version)
   at NuGet.Commands.InstallCommand.ExecuteCommand()
   at NuGet.Commands.Command.Execute()
   at NuGet.Program.Main(String[] args)
```

**Comment by emgarten** [comment]
@mynkow it looks like you are trying to use the nuget v3 source with nuget v2. Try using `https://www.nuget.org/api/v2`  instead of `https://api.nuget.org/v3/index.json`

Or update to the latest nuget.exe here: http://dist.nuget.org/index.html

**Comment by mynkow** [comment]
Correct. I did not realize this till now. Thank you.
