### ISSUE TITLE
Nuspec with escaped < or > (&lt; / &gt;) in text fields no longer builds

### ISSUE THREAD

**Issue by fluffynuts** [NuGet/Home#2651]
I have some packages (PeanutButter.*) which have, in their descriptions, xml-escaped entities: &gt; & gt;. As of Nuget commandline version 3.4.2.855, they no longer build unless I remove the escaped entities -- which is a pity, because I put them there to describe the packages' provisions, which are code-based.
These used to build fine, for over a hundred releases. Also, the error messages which I get are cryptic: one was that the package name field should only contain text (when the problem was a &gt; and &lt; in the description field); the other was that text fields should not contain code.

I've dumbed down my package descriptions for now but would appreciate this being investigated.

**Comment by toddm** [comment]
I'm starting to look at this.  Can you give us an example of a bad description so I can test for sure that my change fixes your file?

**Comment by fluffynuts** [comment]
Hi

Thanks for checking this out (:
Here's the commit before I encountered the issue:
https://github.com/fluffynuts/PeanutButter/blob/444b6893f771621a0321c361d9c185c10c56ec62/source/TempDb/PeanutButter.TempDb.LocalDb.NugetPackage/Package.nuspec
and here's after:
https://github.com/fluffynuts/PeanutButter/blob/9941e6f0519911a109ba67895875c6fcb68905b1/source/TempDb/PeanutButter.TempDb.LocalDb.NugetPackage/Package.nuspec

That particular one raises the issue in the summary node; I had another which raised the issue in the description node:
https://github.com/fluffynuts/PeanutButter/blob/9941e6f0519911a109ba67895875c6fcb68905b1/source/TestUtils/PeanutButter.TestUtils.MVC.NugetPackage/Package.nuspec

**Comment by toddm** [comment]
We've decided not to take a fix for this in 3.4.4. It works correctly in 3.3.0, and it is already fixed in nightly builds of 3.5.0 beta and rc.  The error only happens in the validation, so you can use --NoPackageAnalysis to skip the validation for 3.4.4 or use a different version of NuGet to workaround the problem.

**Comment by bastianeicher** [comment]
Edit: False alarm, sorry. Problem does indeed not occur on 3.3.0.

**Comment by pcgeek86** [comment]
I ran into the same problem on AppVeyor's build servers. My automated builds broke after they upgraded NuGet to 3.4. I posted about it on their forums, and they gave me a script to downgrade to NuGet 3.3.

https://ci.appveyor.com/project/pcgeek86/azure-powershell-extensions/build/1.0.66

![image](https://cloud.githubusercontent.com/assets/466713/15088026/d89f1990-13ab-11e6-97d4-8898d34ea49b.png)
