### ISSUE TITLE
Making pre-release packages using the new -Suffix argument

### ISSUE THREAD

**Issue by adameska** [NuGet/Home#2652]
When i'm making a pre-release package using the -Suffix argument and call packing on a csproj file it's referencing the other dependent package as non-prelease so it's failing to install my package. Is there a way to specify pre-release dependencies if i'm building my package with a suffix?

**Comment by adameska** [comment]
If i add -beta to the version number in the nuspec file the dependency reference is beta. But then i can't remove this beta tag using -Suffix because you can't pass an empty parameter to -Suffix. Is there any way to make all dependent csproj nugets use the same -suffix name as well when packing via a csproj file that has a same name nuspec? Or let me pass nothing into -Suffix so i can remove the -beta from the nuspec files?

**Comment by adameska** [comment]
I should note i'm using RC 3.4.2 command line

**Comment by jainaashish** [comment]
Please try with latest `nuget.exe` or `dotnet.exe` and create a new issue with repro steps if you still see problem.
