### ISSUE TITLE
DefaultPushSource in NuGetDefaults.config (ProgramData\NuGet) doesn't work

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#2653]
I always get the error message `Source parameter was not specified` even though my `NuGetDefaults.config` (stored in `C:\ProgramData\NuGet`) looks like this:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <config>
        <add key="DefaultPushSource" value="https://api.nuget.org/v3/index.json" />
    </config>
</configuration>
```

According to the [documentation](https://docs.nuget.org/consume/nuget-config-defaults#default-nuget.exe-push-source), this should work...

EDIT: I'm using NuGet 3.4.3.

**Comment by rrelyea** [comment]
Putting in 3.4.4 until we know if regression or not.

**Comment by holytshirt** [comment]
This is a regression from 3.3.0 

It just doesn't read the %ProgramData%\NuGet\NuGetDefaults.Config

This has just broken all our build servers as we do a `update -self` before `restore`

```
PS D:\TeamCityAgent\work\9ed84505b41a1255\src\.nuget> .\NuGet.exe sources
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  nuget.org -cached [Enabled]
      http://blah.blah.local:81/nuget/nuget.org
  3.  Blah Shared Libraries [Enabled]
      http://blah.blah.local:81/nuget/blah
  4.  Microsoft and .NET -cached [Enabled]
      http://blah.blah.local:81/nuget/nuget.org.microsoft
PS D:\TeamCityAgent\work\9ed84505b41a1255\src\.nuget> .\NuGet.exe update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 3.3.0.
Updating NuGet.exe to 3.4.3.
Update successful.
PS D:\TeamCityAgent\work\9ed84505b41a1255\src\.nuget> .\NuGet.exe sources
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
PS D:\TeamCityAgent\work\9ed84505b41a1255\src\.nuget>
```

**Comment by rrelyea** [comment]
@zhili1208 can you dig into this report from @holytshirt and look at more commands ensuring that progdata is appropriately being loaded. He reports that sources doesn't load it too.
/cc @yishaigalatzer

**Comment by yishaigalatzer** [comment]
I want to understand regressions from 3.3 vs regressions from 2.x in 3.4.4 we will only fix 3.3 and on regressions

**Comment by holytshirt** [comment]
I'm good with that, this is a regression from 3.3. If you need any more information or testing from me, just let me know.

**Comment by yishaigalatzer** [comment]
@holyshirt, are you referring to sources or defaultpushsource?

**Comment by zhili1208** [comment]
@yishaigalatzer I think he is referring to sources, we load sources from nugetDefault.config in 3.3, but doesn't do that in 3.4. This is regression from 3.3, but 3.3 has another issue: writing sources from nugetDefault.Config to local nuget.config during saving package sources.

**Comment by holytshirt** [comment]
@yishaigalatzer as @zhili1208 said 3.3 does not load `%ProgramData%\NuGet\NuGetDefaults.config`   due to a path issue.
This is suggest location for machine wide settings for nuget configuration https://docs.nuget.org/consume/nuget-config-defaults. 

Not loading this file causes all default settings to be not load for :
- Enabled package sources
- Registered, but disabled-by-default package sources
- The default nuget.exe push source

**Comment by fubar-coder** [comment]
I suggest fixing this for 3.4.4 anyway, because the removal of the default push source being nuget.org is a breaking change without a solution (yet).

**Comment by yishaigalatzer** [comment]
We will have a 3.4.4 build out today for verification

**Comment by rrelyea** [comment]
@holytshirt  I'm seeing slightly different behavior with my testing. can you tell us the paths of the different config files under %progdata%, along with their contents?

**Comment by holytshirt** [comment]
@rrelyea 
This is from a clean rebuilt build agent so %ProgramData%\NuGet\NuGetDefaults.config is the only nuget configuration on the machine, which gets pushed out via global policy.
`%ProgramData%\NuGet\NuGetDefaults.config` maps to `C:\ProgramData\NuGet\NuGetDefaults.config` and that files contains

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <!-- DefaultPushSource key is similar to the 'DefaultPushSource' key of NuGet.config schema-->
    <!-- This can be used by administrators to prevent accidental publishing of packages to nuget.org -->
    <config>
        <add key="DefaultPushSource" value="http://localnuget.company.local:81/nuget/company/" />
    </config>

    <!-- Default Package Sources -->
    <!-- They cannot be deleted or modified but can be disabled/enabled by user -->
    <!-- The following section is similar to 'packageSources' section of NuGet.config schema -->
    <packageSources>
        <add key="nuget.org -cached (localnuget)" value="http://localnuget.company.local:81/nuget/nuget.org" />
        <add key="companyShared Libraries (localnuget)" value="http://localnuget.company.local:81/nuget/company" />
        <add key="Microsoft and .NET -cached (localnuget)" value="http://localnuget.company.local:81/nuget/nuget.org.microsoft" />
    </packageSources>

    <!-- Default Package Sources that are Disabled by Default -->
    <!-- They cannot be modified or deleted either but can be enabled/disabled by user -->
    <!-- The following section is similar to 'disabledPackageSources' section of NuGet.config schema -->
    <!-- The value part of the entry in 'disabledPackageSources' section has no effect -->
    <disabledPackageSources>
    </disabledPackageSources>
</configuration>
```

Anything else you need?

**Comment by rrelyea** [comment]
That helps. Thx. We are considering options.
I was using %ProgramData%\nuget\config\foo.config, instead of %programdata%\nuget\NugetDefaults.config -- so my sources didn't disappear.
DefaultPushSource was broken in both ways.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/288fb184fb85e904aab461dcbf9460f4d40286a1

**Comment by spadapet** [comment]
I tested DefaultPushSource in local nuget.config, user nuget.config, and machine nugetdefaults.config. Works fine.
