### ISSUE TITLE
INuGetPackageManager needs to be updated to take target imports into consideration

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#2655]
With changes that Joel has done we can compare target frameworks using imports on project system side, however there is a scenario that happens outside of our project system:

INuGetPackageManager has an API Task<IReadOnlyCollection<FrameworkName>> GetSupportedFrameworksAsync(CancellationToken cancellationToken) which sends targets from project to nuget dialog so it could determine what targets support package that user selected and then sends those targets to project system in InstallPackage API. Then ProjectSystem adds new package to given frameworks in project.json.

However since GetSupportedFrameworksAsync never receives imports , in some scenarios it might not send all supported frameworks in InstallPackage and package will be installed to not all fxs.

INuGetPackageManager  lives in CPS , so please work with CPS team in U3 to extend it.

**Comment by yishaigalatzer** [comment]
Chatted with @billhiebert, please have an internal discussion and get back to us (or setup a meeting with us). 

My general thought is that we should avoid revving the API unless we absolutely have to, it is going to be short lived.

**Comment by jainaashish** [comment]
not specific to NuGet, should be handled at project system level
