### ISSUE TITLE
Can't install NuGet.PackageManagement 3.4.3

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#2656]
Based on the comment at https://github.com/NuGet/Home/issues/1870#issuecomment-169103414 as well as browsing through the code, it looks like NuGet.PackageManagement is a good place to start exploring in order to replace code based on the v2 APIs with v3 APIs. However, it doesn't look possible to install NuGet.PackageManagement 3.4.3 right now (at least not without some sort of alternate package feed).

NuGet.PackageManagement 3.4.3 depends on
NuGet.Protocol.Core.v2 (>= 3.4.3) depends on
NuGet.Core (>= 2.11.1-rtm-812)

Unfortunately, the most recent NuGet.Core that's available on the gallery is 2.10.1. Where can NuGet.Core >= 2.11.1-rtm-812 be obtained, and why does the dependency chain for a primary NuGet library end up reaching into an alternate feed? I'm also a little confused as to why a v2 NuGet library is needed in the first place - I thought one of the goals of the NuGet v3 APIs was to leave the v2 libraries behind.

**Comment by yishaigalatzer** [comment]
Yup, fixing it right now. Give it a couple of hours

**Comment by yishaigalatzer** [comment]
@daveaglick can you clear your cache and try again?

**Comment by daveaglick** [comment]
Alright, that was fast! :+1: 

Won't be back at my computer for a few hours, but I'll give it a shot when I am and let you know.

**Comment by yishaigalatzer** [comment]
Closing for now, ping me if this is not fixed

**Comment by daveaglick** [comment]
Worked like a charm, thanks again.
