### ISSUE TITLE
nuget setapikey <apikey> outputs the secure apikey

### ISSUE THREAD

**Issue by paddie** [NuGet/Home#2659]
Having the command output the secure apikey is really inconvenient - since it forces us to use the Verbosity quiet attribute on it. In my opinion, the command should simply confirm that the key was successfully added. A separate command should retrieve the key if that is required (which I am sure there is a way to do - but I have not had a need for it).

**Comment by rrelyea** [comment]
Thanks for the report.

**Comment by jainaashish** [comment]
Since apikey are now temp key which needs to be refreshed timely so this becomes low priority. And currently we're dealing with other priority items.
