### ISSUE TITLE
NuGet build task should output file and/or line information for project.json when error'ing

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#2663]
```
Severity    Code    Description Project File    Line    Suppression State
Error       Your project.json doesn't list 'win7' as a targeted runtime. You should add '"win7": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore.   DeployTestDependencies          
```

When I get this error, it would be very helpful if this error was associated with project.json - so I could double-click and open it. Currently, I need to hunt down the project in Solution Explorer and open project.json.

**Comment by jainaashish** [comment]
these build tasks are own by project system itself at https://github.com/NuGet/NuGet.BuildTasks please raise a bug for Project system to consider it.
