### ISSUE TITLE
NuGet package manager should make it clear that options list in packages detail does not apply to project.json

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#2665]
This is to track the continuation of work for https://github.com/NuGet/Home/issues/2486#issuecomment-214562003.

In this scenario, we should have a warning error message in the options section.

Icon: Information
Text: These options are not applicable to projects managing their dependencies through project.json.

Send me a mail offline if you need the warning icon.

**Comment by mishra14** [comment]
@harikmenon @rrelyea @yishaigalatzer @rohit21agrawal 

Please let me know if this looks fine?
1. WPF project launch - hence no warning.

![project_json warning - project launch](https://cloud.githubusercontent.com/assets/10507120/16529310/1652f60c-3f77-11e6-8779-bc1ffc93294b.png)

2/3. Solutionj launch - hence warning.

![project_json warning - solution launch 1](https://cloud.githubusercontent.com/assets/10507120/16529309/165240ea-3f77-11e6-868b-a0cb1e77f22f.png)
![project_json warning - solution launch 2](https://cloud.githubusercontent.com/assets/10507120/16529311/1654adee-3f77-11e6-9e74-686996c5604b.png)

**Comment by harikmenon** [comment]
Looks good to me.

**Comment by rohit21agrawal** [comment]
Screenshots look good..will wait for pull request before signing off!

**Comment by mishra14** [comment]
@harikmenon  @rrelyea @yishaigalatzer 

Had a PR/discussion with @rohit21agrawal . Based on that, I have changed the position of the warning to make it clearer.

Please let me know if this looks fine?
- Solution launch with project.json and project.config projects - hence warning -

![project_json warning - solution launch with warning](https://cloud.githubusercontent.com/assets/10507120/16603897/aea57bae-42d4-11e6-877d-9c56e795a176.png)
- Solution launch with only project.json projects - no warning - 

![project_json warning - solution launch without warning](https://cloud.githubusercontent.com/assets/10507120/16603898/aea79d76-42d4-11e6-8ab8-4fd5295c718d.png)
- WPF/non project.json project launch - no warning

![project_json warning - project config project launch](https://cloud.githubusercontent.com/assets/10507120/16603896/aea58900-42d4-11e6-8363-b3f69575df7e.png)
- UWP/project.json project launch - no warning

![project_json warning - project json project launch](https://cloud.githubusercontent.com/assets/10507120/16603899/aea7fb2c-42d4-11e6-96d2-0bc5d5ca30c1.png)

**Comment by rohit21agrawal** [comment]
I feel the warning icon should be aligned on the left with Install and Update options title

**Comment by mishra14** [comment]
Merged : https://github.com/NuGet/NuGet.Client/commit/e34c1928bc4915680e85bdebbfd5f5609deadb1d
