### ISSUE TITLE
[Newtonsoft.Json]  Visual studio 2013 nuget package manager

### ISSUE THREAD

**Issue by miladganjali** [NuGet/Home#2668]
When I trying add Newtonsoft.Json packages to my Projects this error appears :

> ```
> Installing 'Newtonsoft.Json 8.0.3'.
> Successfully installed 'Newtonsoft.Json 8.0.3'.
> Adding 'Newtonsoft.Json 8.0.3' to MyProjects
> Uninstalling 'Newtonsoft.Json 8.0.3'.
> Successfully uninstalled 'Newtonsoft.Json 8.0.3'.
> Install failed. Rolling back...
> Object reference not set to an instance of an object.
> ```

Other Packages work just fine

![untitled](https://cloud.githubusercontent.com/assets/8298544/14848946/900ce356-0c85-11e6-9794-9414ccf0da35.png)

**Comment by rrelyea** [comment]
Thanks for the report.
What version of NuGet is running with your copy of VS 2013?

**Comment by rrelyea** [comment]
Just tried this with VS 2013 Update 5 w/ NuGet 2.8.6 running on Window 10.0.10586 (Nov 2015 update)
1) create a WPF project
2) install Newtonsoft.Json 8.0.3
3) everything works.

What details are different about your repro attempts?

**Comment by rrelyea** [comment]
Closing. Please reopen if you can reproduce and give detailed repro steps.
