### ISSUE TITLE
Can't upload xBehave package due to "title similar to ID of existing package"

### ISSUE THREAD

**Issue by adamralph** [NuGet/Home#2670]
ref: https://twitter.com/adamralph/status/725372223586992129

![image](https://cloud.githubusercontent.com/assets/677704/14861573/25025e28-0cae-11e6-8610-0d718e53222c.png)

The title of this package has _always_ been "xBehave.net". See the history at https://www.nuget.org/packages/Xbehave/

I guess some change has been put into the gallery which now bans me from uploading the package with this title. I can understand the motivation, but this shouldn't apply to packages _which have always had this title!_

In order to release the package, I hacked the nupkg locally to make the title "xBehave" but this really isn't acceptable. Note that this happened after I had already uploaded 2.1 of https://www.nuget.org/packages/Xbehave.Core so I had to take what ever measure necessary to upload 2.1 of https://www.nuget.org/packages/Xbehave/ which, unfortunately, meant changing the title. The gallery web UI also won't let me change the package title back to what it should be, giving a similar error message.

Note also, that in this case, the refusal is due to this incorrectly uploaded package (by me) which I immediately de-listed when I realised it has the wrong ID - https://www.nuget.org/packages/Xbehave.net - I would have deleted the package immediately, but the gallery won't let me do that.

**Comment by adamralph** [comment]
Have I raised this in the correct repo?

**Comment by rrelyea** [comment]
You have raised this in the wrong repo. (Nuget/NugetGallery)

However, we have the right people in the room to give you the answer.
We enforce a strict policy on this...in which the title of a package cannot match the ID of another package.
You may either change it locally, or on the server for packages that already exist.
This change was made to address major security concerns of users about being confused between 2 packages...so we hope you understand why we won't allow a back door to do this.

**Comment by adamralph** [comment]
@rrelyea thanks for the response. I still have concerns to voice on this, but I'll continue the thread at https://github.com/NuGet/NuGetGallery/issues/3012
