### ISSUE TITLE
Can't restore ASP.Net Core Packages with Custom Package Source

### ISSUE THREAD

**Issue by cc-interview** [NuGet/Home#2671]
We have our own internal NuGet package source we use along with the standard NuGet repository. All that works fine with package restores with classic ASP.NET MVC.

With the new ASP.NET Core, nothing was restoring, even the basic built in packages when creating a new simple app off a template. Somewhere I found a post suggesting deleting the Nuget.config in AppData\Roaming to fix the issue (having it regenerated). 

Indeed that fixed it but to me it should've worked directly from the start. I don't think I ever directly modified NuGet.config, I just previously had added our custom package source through Visual Studio options.

I noticed in the attached NuGet.config that the only active package source was our custom one and the Nuget one was under just &lt;packageSources&gt; but not &lt;activePackageSources&gt;. It looked like it was just trying to restore the packages from our custom repository where they wouldn't exist. 

This created a poor first impression of ASP.NET Core along with issues with the project lock file. Attached is the config.

[NuGet.Config.txt](https://github.com/NuGet/Home/files/239083/NuGet.Config.txt)

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue.

This is a known bug, where the root nuget.config might have been missing a source. Regenerating it fixed it. The next version fixes it by adding the source (one time) for you automatically.

For the sake of completeness it would be helpfull to know exactly what version of visual studio, nuget and asp.net core did you use?

**Comment by cc-interview** [comment]
Thanks.

Visual Studio 2015 Update 2 (14.0.25123.00). NuGet Package Manager 3.4.3. Asp.net core *-rc1-final.

**Comment by jainaashish** [comment]
This is fixed with latest VS, please try with latest release.
