### ISSUE TITLE
Support minClientVersion for project.json

### ISSUE THREAD

**Issue by heaths** [NuGet/Home#2672]
Maybe this has limited use after RTM (or maybe not), but with things moving at a rapid pace it would be nice if _project.json_ supported something akin to `minClientVersion` supported today by _.nuspec_ files. So even if packages are attributed to require specific minimum clients, we can attribute our projects to require them and get better, more actionable error messages on different machines with older NuGet clients.

For example, we had NuGet 3.3 on our build agent and was getting an error that no runtimes were specified, though our _project.json_ referenced `netstandard1.1`. It wasn't immediately obvious that we needed to update NuGet to 3.4.

**Comment by ericstj** [comment]
It also seems like something that would be useful in pack-from-project.json scenario.  Looks like today pack only supports getting minClientVersion from the commandline args when packing a project.json.

**Comment by emgarten** [comment]
This is being tracked here: https://github.com/NuGet/Home/issues/2390

There is a plan to add netstandard to NuGet 2.8.x which will mean minClientVersion won't necessarily be useful for blocking clients without support for these new TFMs.

**Comment by heaths** [comment]
Perhaps a different concept then, like NPM's `engineDependencies`:

``` json
{
  "engines": {
    "nuget": "2.8.<whatever>",
    "nuget": "3.4"
  }
}
```

**Comment by rrelyea** [comment]
In order to do that, we'd need to ship 2.8._, 3.3._, etc... with support for that.

**Comment by ericstj** [comment]
I think you took this issue in a different direction than the initial intent.

NuGet now knows about project.json and what is valid to have in it.  Suppose a new feature comes along that requires a change to project.json (eg: new framework support, include/exclude etc).  Suppose my project is invalid if an old client tries to consume that.  What can I do in my source to catch early if someone is using an old client on it?

**Comment by niemyjski** [comment]
Has anyone been able to get this to work?
