### ISSUE TITLE
Watson crash due to ObservableCollection in InfiniteScrollList not being thread-safe

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#2673]
As per Sam Bent's analysis from WPF Team:
Nuget is adding a bunch of items to the ObservableCollection<object>.
Thread A adds the actual items (of typeNuGet.PackageManagement.UI.PackageItemListViewModel),
while Thread B adds and removes a fake item (of type NuGet.PackageManagement.UI.LoadingStatusIndicator).  
The threads aren't using the synchronization that governs the collection.   [This is the bug]

The two threads interleave as follows:

Thread A     Thread B
                   remove 25
                   notify remove 25
                   add 25
add 26
notify add 26
add 27
notify add 27
...
add 51
notify add 51
                   notify add 25

Thus the collection view gets "notify add 26" before it gets "notify add 25", and crashes trying to add at index 26 in the shadow collection whose length is only 25.

It's important that the collection view gets the notifications in the same order that the actions actually happened.
Using the registered synchronization will ensure that.  Not using it can lead to crashes like this one.

**Comment by rohit21agrawal** [comment]
checked ino dev :  https://github.com/NuGet/NuGet.Client/commit/2ee48fd368c4f4bb6037f6925e2e82607ff2493f

checked into 3.4.4 :  https://github.com/NuGet/NuGet.Client/commit/4d4a90b19db7fc65624b32acc41e541060dd9732

**Comment by alpaix** [comment]
The fix wasn't complete. Debug assert is raised when package installed notification is received:

> ---- DEBUG ASSERTION FAILED ----
> ---- Assert Short Message ----
> 
> ---- Assert Long Message ----
> 
>    at NuGet.PackageManagement.UI.InfiniteScrollList.get_Items() in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Xamls\InfiniteScrollList.xaml.cs:line 86
>    at NuGet.PackageManagement.UI.InfiniteScrollList.get_PackageItems() in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Xamls\InfiniteScrollList.xaml.cs:line 91
>    at NuGet.PackageManagement.UI.InfiniteScrollList.UpdatePackageStatus(PackageIdentity[] installedPackages) in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Xamls\InfiniteScrollList.xaml.cs:line 342
>    at NuGet.PackageManagement.UI.PackageManagerControl.Refresh() in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Xamls\PackageManagerControl.xaml.cs:line 692
>    at NuGet.PackageManagement.UI.PackageManagerControl.SolutionManager_ActionsExecuted(Object sender, ActionsExecutedEventArgs e) in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Xamls\PackageManagerControl.xaml.cs:line 190
>    at NuGet.PackageManagement.VisualStudio.VSSolutionManager.OnActionsExecuted(IEnumerable`1 actions) in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.VisualStudio\IDE\VSSolutionManager.cs:line 718
>    at NuGet.PackageManagement.UI.NuGetUI.OnActionsExecuted(IEnumerable`1 actions) in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\UserInterfaceService\NuGetUI.cs:line 168
>    at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext() in X:\NuGet3.4\src\NuGet.Clients\PackageManagement.UI\Actions\UIActionEngine.cs:line 213

**Comment by rohit21agrawal** [comment]
dev : https://github.com/NuGet/NuGet.Client/commit/a3459beec87da49f6c93113205ee58b463abcd31

release-3.4.4 : https://github.com/NuGet/NuGet.Client/commit/7d0c29d72214e60b22e365b2fa979e596b1c4de1
