### ISSUE TITLE
Nuget.Core: Double-checked locking does not work

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2677]
Similar to the issue opened on the Gallery:
https://github.com/NuGet/NuGetGallery/issues/2995

It has been long known that double-checked locking is [broken](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html).

We can see an example of this in client code: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/HttpSource/HttpSource.cs#L305

The suggestion is to use Lazy<> implementation instead.

**Comment by benaadams** [comment]
That's C and Java. Double checked locking is fine in C# the lock imposes a strong read/write memory barrier.

**Comment by rrelyea** [comment]
Triage - by design. We've reviewed the code and are ok with it because this isn't a double check locking and as Ben says it is fine.

**Comment by skofman1** [comment]
Take a look here: https://msdn.microsoft.com/en-us/library/ff650316.aspx
You have to use volatile to make double-checked locking work in C#.

**Comment by benaadams** [comment]
@skofman1 it also says:

> Note: The common language runtime resolves issues related to using Double-Check Locking that are common in other environments.

**Comment by yishaigalatzer** [comment]
@benaadams double checked with clr folks, this code is indeed safe. The warning applies to scenarios where you have two fields like bool _initialized.

We are going to add volatile to _httpClient for two reasons
1. This might fail on Mono
2. This stops the questions about is this ok or not.

**Comment by benaadams** [comment]
> This stops the questions about is this ok or not.

lol :smile_cat:

**Comment by emgarten** [comment]
NuGet/NuGet.Client@e9ba9f9cd3f34f3d49f24bf9e027b6e1fa7e5e47
