### ISSUE TITLE
Nuget pack should check if the package to be produced is structurally valid. And warn if it is not

### ISSUE THREAD

**Issue by cdmihai** [NuGet/Home#2678]
Nuget Pack should check if the package that the user wants to create is structurally valid and warn / error if it isn't.

Valid needs to be defined. Each folder in the nuget package has some semantics, and those semantics need to be checked.

For the CLI, we've hit the issue where a user added a native dll in a lib folder rather than in the native folder: https://github.com/dotnet/cli/issues/2660

This is the package producer side of the story. The package consumer issue is #2679.

@piotrpMSFT

**Comment by rrelyea** [comment]
Triage - pack isn't going to validate native vs managed DLLs.
