### ISSUE TITLE
NuGet 3.4.3 is unable to build a package with &amp; inside the copyright

### ISSUE THREAD

**Issue by MatzeG** [NuGet/Home#2680]
Hello 

in Nuget Version 3.4.3 the **&amp;** seems does not work any more.

Matthias

<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
    <metadata>
        <id>MyPackage</id>
        <version>1.0.0</version>
        <authors>MyName</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
       *\* <copyright>MyConpany &amp; Co. KG</copyright>**
    </metadata>
    <files />
</package>

**Comment by rrelyea** [comment]
Thanks for the report. We've already investigated the regression. 
See details here: https://github.com/NuGet/Home/issues/2651
