### ISSUE TITLE
Improve performance for WalkDependencies api for prune pre release packages for stable targets

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2683]
`nuget.exe install Microsoft.AspNet.Mvc -Version 6.0.0-beta2 -NoCache -Source https://api.nuget.org/v3/index.json`

Above command is taking 2 hr 10 mins to complete prune pre release api call since we uses DFS to walk dependencies in PrunePackageTree.cs and that too without maintaining a local cache for visited packages which makes it to process duplicate packages and add into stack calls. So if you have many versions for same package it's going to add too much performance overhead.

Right solution will be to maintain visited packages so that we don't end up calling same code again n again for the same package with different versions. Also use BFS to avoid recursion.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/Resolution/PrunePackageTree.cs#L89

**Comment by rrelyea** [comment]
ONLY If profiling shows this is a problem, then we are ok fixing it.

**Comment by emgarten** [comment]
Ported to 3.4.5 NuGet/NuGet.Client@feaa7bf5917913d157861fe8cdc7a33a02dcb473
