### ISSUE TITLE
Clean authentication state after pre-defined period of time

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2685]
Follow-up on https://github.com/NuGet/NuGet.Client/pull/388.

**Problem**
`HttpSource` retains authentication state of failed requests for entire application lifetime. Hypothetically this can reach significant redundant memory waste in VS.

**Solution**
Consider cleaning unused state objects after certain period of time. This can be implemented the same way as we did for image load failures.

**Comment by rrelyea** [comment]
Triage- let's close this issue...and handle a case of a user cancelling 3 times, or failing to authenticate 3 times -- by treating that source as a misbehaving source. #1627
