### ISSUE TITLE
Add validation for _._ file includes

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2687]
From @nil4

https://github.com/aspnet/KestrelHttpServer/issues/773

Using dotnet CLI 1.0.0-rc2-002485 and `Microsoft.AspNetCore.Server.Kestrel/1.0.0-rc2-20682` from the `aspnetcirelease` feed in an application targeting framework `net461` with RID `win7-x64`. The application fails to start with the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MyApp.Startup.Main(String[] args)
```

After running `dotnet build -f net461`, `System.Numerics.Vectors.dll` is not present in `bin\Debug\net461\win7-x64`. Manually copying the DLL from the NuGet package cache to this folder fixes the issue. 

Not sure whether this is relevant, but thought I should mention it: when copying the DLL manually I noticed that the NuGet package cache folder contains both the `_._` placeholder as well as the actual DLL/XML files, in both `ref\net46` and `lib\net46`:

```
 Directory of C:\Users\ME\.nuget\packages\System.Numerics.Vectors\4.1.1-rc2-24018\lib\net46

2016-04-17  21:01           111 328 System.Numerics.Vectors.dll
2016-04-17  21:01            50 223 System.Numerics.Vectors.xml
2016-04-17  21:01                 0 _._
               3 File(s)        161 551 bytes
```

**Comment by emgarten** [comment]
The nupkg itself contains both a dll and _._ in the same folder. I think this should be fixed in the package.

![image](https://cloud.githubusercontent.com/assets/6381138/14932242/496b1540-0e28-11e6-9ed9-71d62d241737.png)

**Comment by emgarten** [comment]
@toddm NuGet should check for this during validation if it does not already.

**Comment by ericstj** [comment]
We'll clean that up, but why does NuGet care here?  Shouldn't it deploy both or at least let the one that matches the impl pattern win over the placeholder?

**Comment by emgarten** [comment]
@ericstj NuGet doesn't really care, it's just listing all files in the folder. It could be filtered out before writing it to the lock file, it's just a question how far NuGet should go to work around strangeness in packages.

**Comment by ericstj** [comment]
Yeah, the bug turned out to be in CLI which was "caring".  I don't think NuGet should do anything special here.  It does need to communicate in the lock file that the package was applicable and explicitly decided not to provide assets.  I think the way NuGet persists the placeholder file entries in the lock is a resasonable way to do that.
I don't think NuGet should bother pointing out that someone has a placeholder file and other assets in a folder.  Suppose they had some unusual reason for having a file named _._?

**Comment by emgarten** [comment]
NuGet won't block those scenarios, it will just warn as part of the package validation (which can be turned off). It's similar to if a user has a dll outside of the known folders, NuGet will detect it and show a message, but it can be ignored if it was intentional.

**Comment by ericstj** [comment]
I see, that seems reasonable.

**Comment by toddm** [comment]
https://github.com/NuGet/NuGet.Client/commit/bba98883398ee64d8095e781c5cb3e2bbb6b5e98
