### ISSUE TITLE
NuGet package manager does not respect VS language settings

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#2689]
Opening in behalf of a couple of customers who complained about this on our gallery https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d/viewReviews/Reviews

Direct comment

"I've updated to latest VS 2015.2 and after that Package Manager speaks French to me.

In the meantime, I have:
- VS 2015 in English
- Windows 10 display language set to English
- Regional formats are set to French as I'm living in a French speaking area
- I have 4 languages configured for input

Please, make Package Manager UI speak English by default. Local language should be an option, not the default choice.

And please, if it's tricky to decide on the language, make possible to override your decision logic"

**Comment by luisrudge** [comment]
I'm having this as well

**Comment by rrelyea** [comment]
We've not been able to reproduce this internally. 
@luisrudge  - can you please give detailed info about how we might be able to reproduce this problem?

**Comment by luisrudge** [comment]
- VS 2015 in English
- Windows 10 display language set to English
- Regional formats are set to Portuguese - Brazil

Everything is in english, but the nuget UI is in portuguese

**Comment by skorunka** [comment]
I have got the same issue. But it speaks to me in Czech as my Windows regional settings are Czech, but display language is English.

![image](https://cloud.githubusercontent.com/assets/218913/15649591/9f983330-266a-11e6-8d64-36b2fff0c500.png)

**Comment by harikmenon** [comment]
Quick update. We believe this is a VS IDE issue since it affects, NuGet and other extensions like Team Explorer. We are working with on identifying a repro.

 If you have active repro/machine configuration that we can take look at that would be awesome. We are unable to get an internal repro at this time.

**Comment by 13xforever** [comment]
Workaround that worked for me:
- Open Tools → Options → Environment → International Settings
- Change Language to 'Same as Microsoft Windows'
- Restart VS
- Optionally, return to English and restart again

**Comment by san7hos** [comment]
@13xforever It has not worked for me

**Comment by jainaashish** [comment]
Please try with latest Visual Studio 2017 release and let us know if you still see this issue.

**Comment by janecek-m** [comment]
Hello,

I am still encountering this problem in VS 2019. 
Changing settings:
Open Tools → Options → Environment → International Settings
To 'Same as Microsoft Windows' and then back to 'English' does nothing.

Messages in **Package Manager Console** are still in the same language as my OS enviroment (Czech for me).

Any other tips for this issue? 

Thank you

**Comment by zivkan** [comment]
@janecek-m Do you mean the PowerShell running inside Package Manager Console is not in English, or do you mean that when you run NuGet's cmdlets, such as `Get-Help NuGet`, only that is not in English while the rest of PowerShell is?
