### ISSUE TITLE
'Strong name validation failed' for NuGet.Packaging.Core v3.4.3

### ISSUE THREAD

**Issue by aelij** [NuGet/Home#2690]
It seems there's something wrong with the signing of `NuGet.Packaging.Core`. The file is also missing its digital signature (right click -> properties -> no "Digital Signatures" tab).

The following exception is thrown when calling `NuGetPackageManager.InstallPackageAsync`:

```
System.IO.FileLoadException: Could not load file or assembly 'NuGet.Packaging.Core, Version=3.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'NuGet.Packaging.Core, Version=3.4.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__32.MoveNext()
```

**Comment by aelij** [comment]
The `NuGet.Packaging.Core.dll` file in the [VSIX distribution](https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix) is fine BTW.

**Comment by yishaigalatzer** [comment]
@jainaashish can we make sure this gets fixed in 3.4.4 (and validated completely before pushing)

**Comment by aelij** [comment]
@yishaigalatzer When will you be publishing 3.4.4?

**Comment by yishaigalatzer** [comment]
We plan to release by the end of the week if all goes well. Are you currently blocked?

**Comment by aelij** [comment]
Yes, but it's a side project so it can wait a few days. Thanks :)

**Comment by yishaigalatzer** [comment]
As a workaround you can create a new version for your purposes only, and swap in the dll from the vsix.

**Comment by jainaashish** [comment]
@aelij I just checked this nuget,packaging.core 3.4.3 dll and i can see digital signature tab in properties also checked through sn.exe it shows as valid strong name. Anything i'm missing here? could you help reproduce this issue? 
and just to confirm, you would have got the dll from https://www.nuget.org/packages/NuGet.Packaging.Core/  right?

**Comment by aelij** [comment]
Yup. I'm attaching the .nupkg file I downloaded directly from nuget.org.
[nuget.packaging.core.3.4.3.nupkg.zip](https://github.com/NuGet/Home/files/246377/nuget.packaging.core.3.4.3.nupkg.zip)

**Comment by jainaashish** [comment]
That's surprising, did you download this dll before 4/25? And can you take the latest nupkg file from nuget.org and try

**Comment by aelij** [comment]
I downloaded the file 5 days ago, right before opening this issue. Was it replaced, then? I think this could be a problem for other users who won't get the update unless they clean their cache.

Anyway, the current file works.

**Comment by jainaashish** [comment]
There were very few downloads before file got replaced n you happened to be one of those :) 

Thanks for confirming that current file works for you.

**Comment by pawelpabich** [comment]
Hey, just wanted to let you know that I hit this problem today on a 3 week old laptop. Something is still not right.
