### ISSUE TITLE
Include information about the dependency chain when a package is unable to restore

### ISSUE THREAD

**Issue by javiercn** [NuGet/Home#2693]
I have a project.json file with a list of dependencies. When I try to restore, it fails indicating that it can't resolve a given dependency that is not directly referenced in my project.json

When I try to look at the project.lock.json file, I can't see any information about who is bringing in that dependency that is failing. When running with -Verbosity detailed it doesn't tell me either.

It will be great that when a dependency fails to resolve we get to see the whole dependency chain, as this is extremely useful for root cause analysis. Maybe you can put that in -Verbosity detailed or through a new option.

I've tried this with nuget.exe from https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

**Comment by rohit21agrawal** [comment]
@mishra14 @emgarten has this been fixed with the recent warnings & error changes?

**Comment by emgarten** [comment]
The error message here hasn't changed.

**Comment by jainaashish** [comment]
This experience has been improved in latest release so please try with latest Visual Studio 2017 release and let us know if you still see any issue.
