### ISSUE TITLE
Request to introduce semantic versioning friendly $version3digit$ replacement token

### ISSUE THREAD

**Issue by brian-white** [NuGet/Home#2694]
Use case:
- We use Jenkins and the Change Assembly Version plugin to set toggle between version numbers like 3.0.1 for release packages and 3.0.1.${BUILD_NUMBER} for sandbox packages
- When we set it to 3.0.1 even though the dll says it's file version 3.0.1 the $version$ replacement token in the nuspec file turns that into 3.0.1.0 package and we want it to be 3.0.1 instead

Target audience:
- People who don't want to play around all day in jenkins trying to figure out why $version$ doesn't work as one would expect

I know there's another attribute which could be used, but we really need to decide on package version at build time, not at code writing time, and we build from Jenkins.  There is no plugin for changing the  AssemblyInformationalVersion attribute through Jenkins.

Acceptance:
- Given that <version>$version3digit$<version> is present in the nuspec file,
  and that the final number portion of the assembly version is 0,
  the nuget package generated will contain only the first three numbers of the assembly version
- Given that <version>$version3digit$<version> is present in the nuspec file,
  and that the final number portion of the assembly version is NOT 0,
  the nuget package generated will contain the full four numbers from the assembly version

**Comment by emgarten** [comment]
@brian-white what version of nuget.exe are you using? In the latest 3.4.3 nuget.exe the version should be normalized to three digits unless a fourth non-zero digit exists.

https://dist.nuget.org/index.html

**Comment by brian-white** [comment]
I realized I put in a bad name for the replacement token, given the behavior it should be something like version3digitPreferred

**Comment by brian-white** [comment]
Doh!  We must be behind, I'll check

**Comment by brian-white** [comment]
We had 3.3.0.212.  Thanks a bunch!  This will be much simpler than the silly windows batch scripting I put in our Jenkins build job

**Comment by brian-white** [comment]
I closed this prematurely.  This doesn't work as advertised for me.  I pulled out the extra environment variable we were using and this looked fine in 'sandbox' mode with .$BUILD_NUMBER at the end.  But when building for release with version set to 3.1.0 I still got a 3.1.0.0.nupkg file.

**Comment by brian-white** [comment]
Build output from Jenkins:
E:\Jenkins\workspace\concur-core-artifact-build>exit 0 
Changing the file(s) **/AssemblyInfo.cs to version : 3.1.0
Updating file : E:\Jenkins\workspace\concur-core-artifact-build\concur.core.test\Properties\AssemblyInfo.cs, Version : 3.1.0
Updating file : E:\Jenkins\workspace\concur-core-artifact-build\concur.core.test\Properties\AssemblyInfo.cs
Updating file : E:\Jenkins\workspace\concur-core-artifact-build\concur.core\AssemblyInfo.cs, Version : 3.1.0
Updating file : E:\Jenkins\workspace\concur-core-artifact-build\concur.core\AssemblyInfo.cs
....
E:\Jenkins\workspace\concur-core-artifact-build>nuget.exe pack ..\concur-core-artifact-build\concur.core\Concur.Core.csproj -properties configuration=release 
Attempting to build package from 'Concur.Core.csproj'.
MSBuild auto-detection: using msbuild version '12.0' from 'C:\Program Files (x86)\MSBuild\12.0\bin'.
Packing files from 'E:\Jenkins\workspace\concur-core-artifact-build\concur.core\bin\Release'.
Using 'Concur.Core.nuspec' for metadata.
Found packages.config. Using packages listed as dependencies
Successfully created package 'E:\Jenkins\workspace\concur-core-artifact-build\Concur.Core.3.1.0.0.nupkg'.

**Comment by brian-white** [comment]
This is with nuget.exe version 3.4.3.855

**Comment by emgarten** [comment]
@brian-white is the version correct in the nuspec? The filename shouldn't impact anything, but I think this was fixed in the latest nightly version already. Could you try nuget.exe from here: https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine

**Comment by brian-white** [comment]
We are using the $version$ replacement token there, not a hard-coded value.

**Comment by toddm** [comment]
I confirmed that this doesn't work in 3.4.3 and the upcoming 3.4.4, but it will be fixed in 3.5.  If you get the latest nightly build as Justin said above, it should work for you.

**Comment by brian-white** [comment]
Thanks, I'll have to wait until that's released though before adding it to our toolchain.
