### ISSUE TITLE
v3.4.3 introduced private feed regression

### ISSUE THREAD

**Issue by devlead** [NuGet/Home#2697]
When upgrading to v.3.4.3 NuGet console MyGet private feeds get a `returned an unexpected status code '401 Unauthorized'`error on AppVeyor CI
Going back to https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe or https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe resolves all issue with no change in build scripts.

Commands used sensitive info stripped.
1. NuGet.exe sources Add -Name "Feed-Name" -Source "https://www.myget.org/F/[REDACTED]/" -NonInteractive -UserName "[REDACTED]" -Password "[REDACTED]"
2. NuGet.exe setapikey "[REDACTED]" -Source "[REDACTED]" -NonInteractive
3. NuGet.exe" restore "[PathToSolution]" -NonInteractive

Same issue regardless using the v2 or v3 feed. Setting verbosity to detail didn't give any more clues, v.3.4.3 seem to be a bit more verbose by default.

Reproduced on 3 different AppVeyor projects with different MyGet feeds and users, all fixed by reverting back to previous version of the nuget.exe

**Comment by yishaigalatzer** [comment]
I suspect this might be related to https://github.com/NuGet/Home/issues/2647

Can you please pick up the 3.4.4 build, and tell us if this was fixed? Here are instructions:

1.download not yet final version 3.4.4. of nuget.commandline.nupkg from https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine/3.4.4-rtm-870 
2.rename the .nupkg to .zip
3.Grab nuget.exe from inside the zip file in the tools directory.
4.Try this version of nuget.exe to verify that it has fixed your issue.
5.Tell us how it went

**Comment by rrelyea** [comment]
Yes, looks like a dupe. Please reopen if that doesn't appear to be the case.

**Comment by devlead** [comment]
@yishaigalatzer @rrelyea Thanks for getting back to me.
3.4.4 indeed solves the issue and setting StorePasswordInClearText also seems to solve the issue when using 3.4.3, which confirms the #2647 issue. :shipit:
