### ISSUE TITLE
All nuget sources are queried when installing a package even if not selected, this forces redundant feed authentication

### ISSUE THREAD

**Issue by Mertsch** [NuGet/Home#2698]
In the list of NuGet feeds (3.4.3 with VS2015 Update 2) I have one private feed from VSTS package server. This private feed requires authentication.
The annoying thing is that nuget ALWAYS requires you to sign in to your MSA even if you browse and install specifically from another feed like nuget.org

Please update the client, so that auth is only required when actually connecting to the feed specifically or when querying "all" and not finding anything before the feed that requires authentication.

**Comment by rrelyea** [comment]
This is by design because other feeds may be used if there are dependencies.
We do the requests in parallel to satisfy the dependencies.

**Comment by Mertsch** [comment]
@rrelyea OK, understandable, but

if you fail to auth with the feed (e.g. by clicking cancel) NuGet will fail to restore any more packages as the unauthenticated feed blocks all further connections to other sources :-1:

**Comment by adamralph** [comment]
This is indeed very annoying.

The reason given for "by design" doesn't really hold up. If I install a package from a given source, it's reasonable to query that source first for the dependencies, before trying other sources (in parallel if so desired).

**Comment by adamralph** [comment]
After more thought, I think that parallel querying of the remaining sources after the initial source is attempted is also not a good idea. I order my NuGet sources in the order I would like them to be queried, and I believe this should also be respected.

**Comment by adamralph** [comment]
Do my comments warrant any response? I realise the issue is closed, but I challenge that closure. It seems reasonable to revisit this design as it seems to be a very bad and problematic approach.
