### ISSUE TITLE
Functional tests on FindPackage are failing

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#270]
Functional tests on FindPackage are failing

FindPackageByIdWildcard
FindPackageByIdAndPrereleaseVersion

**Comment by danliu** [comment]
1. The first test is a feature that's not implemented. We should discuss if need to support wildcards. So disabled the test for now before the feature is implemented. (may need server support also)

2. The 2nd test is failing because of a server issue - https://github.com/NuGet/Home/issues/319
