### ISSUE TITLE
nuget pack with project.json misses dependencies

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2700]
I just converted some internal nuget-deployed projects over to the project.json method, and noticed that the resulting nupkg files don't properly reference dependencies (which worked fine when the projects used packages.config). Am I missing something?

This is with nuget.exe 3.4.3.855

**Comment by yishaigalatzer** [comment]
No you are not missing a thing. This is a feature being developed and will show up in 3.5. For now you have to use a nuspec or make the leap of faith and grab a nightly build of of 3.5 (and give us feedback).

**Comment by wbradney** [comment]
Thanks, works perfectly with the nightly!

**Comment by wbradney** [comment]
Actually, I think I spoke too soon. Though the nupkg dependencies look fine, existing projects that reference the "top-level" package don't compile - it looks like the &lt;dependencies&gt; inside the package are still not being picked up at restore time. I made sure my local cache was clean to avoid picking up an old package.

**Comment by wbradney** [comment]
I have to explicitly add all the dependencies down the graph to the project.json file in order to compile again :-(

**Comment by yishaigalatzer** [comment]
@wbradney @toddm can you please work with us offline, I want to figure out exactly what is missing and see if this is code that is in PR or actually a bug. You can use support @ nuget.org with a sample

**Comment by wbradney** [comment]
OK I'll see if I can create a sample that reproduces

**Comment by yishaigalatzer** [comment]
Would be nice to clarify if the package has the right dependencies and compilation fails, or if the package is missing dependencies.

**Comment by wbradney** [comment]
The package created by nuget pack appears to have the correct dependencies, the project that references the resulting .nupkg fails to compile - missing the namespaces declared by the dependencies.

eg.

MyLibrary depends on log4net
nuget pack MyLibrary creates a nupkg containing a nuspec with:

```
    <dependencies>
      <group>
        <dependency id="log4net" version="2.0.5" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.5.1" />
    </dependencies>
```

MyProgram depends on MyLibrary:

```
{
  "dependencies": {
    "MyLibrary": "1.0.0-pre1"
  },
  "frameworks": {
    "net451": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

MyProgram fails to compile:
error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?)

Adding log4net to MyProgram's project.json gets it compiling again. When MyLibrary was using packages.config, I'm pretty sure this wasn't necessary.

I literally just converted "MyLibrary" from packages.config to project.json and recompiled MyProgram.

**Comment by wbradney** [comment]
With packages.config the MyLibrary package was being created with:

```
    <dependencies>
      <dependency id="log4net" version="2.0.5" />
    </dependencies>
```

With project.json:

```
    <dependencies>
      <group>
        <dependency id="log4net" version="2.0.5" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.5.1" />
    </dependencies>
```

Is that significant?

**Comment by toddm** [comment]
I have a PR out right now that will make it so that the dependency ends up inside the group with the targetFramework instead of in it's own group. There's a good chance that will fix it up for you. I expect to get that pushed to Dev today so I can let you know when to grab the latest build.

**Comment by wbradney** [comment]
Yep. I just reverted the redundant project.json entries and manually changed the nuspec in my package cache to:

```
<dependencies>
  <group targetFramework=".NETFramework4.5.1">
    <dependency id="log4net" version="2.0.3" />
  </group>
</dependencies>
```

And that seems to have done the trick. Thanks!

**Comment by wbradney** [comment]
Out of interest, what is the **exclude="Build,Analyzers"** all about?

**Comment by toddm** [comment]
It means that it won't try to build or run analyzers on the dependency.  This was the default behavior with a packages.config file, but gets set explicitly now to allow other options when needed.

**Comment by toddm** [comment]
Thanks for verifying the fix, even before I have it pushed :)

**Comment by wbradney** [comment]
No problem. I think this is all coming together nicely and the project.json style is going to be a big help to us.

**Comment by toddm** [comment]
I've pushed the fix to Dev.  Go ahead and try the next nightly when it comes out.

**Comment by harikmenon** [comment]
@wbradney - I'm the PM for NuGet and I loved your article on project.json on your blog http://lesscode.net/. If you have some time, I would love to get on a quick call with you to talk about your experience with it.

**Comment by wbradney** [comment]
@harikm86 : I'd be happy to talk, probably towards the end of this week I'll have time. I'll email you to co-ordinate.

**Comment by harikmenon** [comment]
Much appreciated. My email is harikm@microsoft.com. Also, you can use the following calendly link to block a slot on our calendar that works for youb https://calendly.com/harikm/nuget-feedback
