### ISSUE TITLE
Make MSBuildNuGetProjectSystemUtility public

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#2702]
There are a lot of valuable utility methods in the `NuGet.ProjectManagement.MSBuildNuGetProjectSystemUtility` class, including several that are more general than just MSBuild projects. For example, `MSBuildNuGetProjectSystemUtility.GetMostCompatibleGroup()` is very helpful to get the correct files from a package archive given a framework.

A related suggestion (though a little more work) would be to place the methods that aren't specific to MSBuild projects into a separate more general-purpose project system utility class.

**Comment by rrelyea** [comment]
We would accept a PR.
Note...our API surface is not very developed...and will change over time.

**Comment by daveaglick** [comment]
@rrelyea Okay, cool. And yeah, I'm aware the API isn't really designed for public use right now. That said, as more packages start requiring v3 anyone embedding NuGet into their own application is going to need to look at it whether it's ready or not (as I am having to do).

I certainly don't mind working up a contribution. What approach would be preferred?
- Just making the class public
- Doing a little refactoring to pull out the more generic operations and place them into a general project helper class

**Comment by jainaashish** [comment]
There hasn't been any noise here neither a pr so closing it assuming this might not be needed anymore.
