### ISSUE TITLE
"Connect to NuGet Source" via Powershell or Protocol?

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/Home#2703]
This is just a small idea to enhance the "Register a custom NuGet Endpoint inside VS"-scenario.

Somehow my NuGet.config got corrupted and I needed to re-register the NuGet.org Endpoint via my local Visual Studio and to be honest the Settings dialog with the Plus & Update confuses me from time to time.

So I thought: Maybe there is a command line interface for this and [there is one](https://docs.nuget.org/consume/Command-Line-Reference#sources-command), but with one constraint: I need to download NuGet.exe.

This is just a "luxery" problem, but with more and more MyGet feeds (and other NuGet sources of course) incomming it might be interesting to "register" NuGet sources more easily.

Option 1: PS-Enhancement
Make the ["Source-Command"](https://docs.nuget.org/consume/Command-Line-Reference#sources-command) available via the default NuGet Package Management Console.

With this in place we could do something like this:

![image](https://cloud.githubusercontent.com/assets/756703/14968568/b3232dbe-10bd-11e6-9587-31c4acfb3ff0.png)

Option 2: Protocol
This would even more comfortable, but also more challenging, because "something" would need to register as a Windows Protocol handler, just like the GitHub Client:

![image](https://cloud.githubusercontent.com/assets/756703/14968622/fe1f7a8e-10bd-11e6-8360-918a1f4be5ea.png)

I don't know enough about the current NuGet installer to tell if this would even be possible.

What do you think? Nice to have?

**Comment by rrelyea** [comment]
We'd also need the ability to remove a source, etc...

**Comment by robertmuehsig** [comment]
Well... Once configured I would say the normal remove would be ok. On the other hand we could implement all commands for managing the sources via PS.
Would a PR be accepted for option 1 or is this something that you don't want to see?

**Comment by robertmuehsig** [comment]
Hi @rrelyea 
I tried to start develop this feature, but I have 2 questions:

If I want to add some more options to the Powershell-Module, I should check the "PackageManagement.PowerShellCmdlets", right? If yes - is there an easy way to debug these cmdlets? My Cmdlet-dev knowledge is pretty basic, but those cmdlets also access VS, so... maybe you have a hint for me.

Second question:
The way to add a new source would be something like this, right?

```
        var sourceRepositoryProvider = ServiceLocator.GetInstanceSafe<ISourceRepositoryProvider>();
        if (sourceRepositoryProvider == null)
        {
            throw new ArgumentException("sourceRepositoryProvider");
        }
        var packageSourceProvider = sourceRepositoryProvider.PackageSourceProvider;
        var sources = packageSourceProvider.LoadPackageSources().ToList();
        sources.Add(new Configuration.PackageSource(source, name));
        packageSourceProvider.SavePackageSources(sources);
```

**Comment by robertmuehsig** [comment]
Any hints? Maybe from @rrelyea or @maartenba ?

**Comment by maartenba** [comment]
On adding the sources, that is correct. Not sure on first question.

**Comment by jainaashish** [comment]
No attraction here and neither we had any pr for this. And we won't be able to get to this since we are tied up with other priority workitems.
