### ISSUE TITLE
Package Manager filter not available in vs output window for restore command

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2704]
run nuget restore through visual studio UI and check output window, there won't be package manager filter to show output from. Now run install/update package from nuget package manager ui, then it will show package manager filter in output window.

It should show package manager filter in output window even for restore command as well.

**Comment by harikmenon** [comment]
Weird discrepancy, we should fix it :). Thanks for filing @jainaashish

**Comment by jainaashish** [comment]
This has been fixed.
