### ISSUE TITLE
There is no way to set logs verbosity level for Nuget package manager UI actions

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2705]
There is no way to set logs verbosity level for Nuget package manager UI actions like install or update packages. We have hard coded setting to always shows Info/Warning/Error logs only.

We need to provide a way to the users to set verbosity level for package manager logs similar to msbuild output verbosity option. And then based on this setting adjust verbosity level for package manager logs.

**Comment by harikmenon** [comment]
We should probably do this in 3.5, otherwise users who are running updates through the UI will never be able to get the full verbose logs. We will have to explicitly ask them to use the the Package Manager Console.

@rrelyea : What do you think?

**Comment by yishaigalatzer** [comment]
I'm not sure we want this in the settings UI directly. Can we please have a short discussion before adding UI items to NuGet?

**Comment by harikmenon** [comment]
sure, lets chat on Monday
