### ISSUE TITLE
Tools/Options - "Machine-wide package sources" is truncated in ENU

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2707]
Localization caught a problem with our English string in Tools/Options.
Appears that the label is not showing all the content, despite being placed into a tablelayoutpanel and having columnspan set to 4.
Perhaps having the hard coded size is the problem?

Related internal bug: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/193372

**Comment by shishirx34** [comment]
Fixed.
