### ISSUE TITLE
Is the NuGet mirror command still supported / Does NuGet.ServerExtensions.dll still exist?

### ISSUE THREAD

**Issue by dee-see** [NuGet/Home#2709]
The instructions on the [`mirror` command documentation](https://docs.nuget.org/consume/command-line-reference#mirror-command) are outdated and point to the old CodePlex repository where the ServerExtensions are still in the 2.8 version.

> Note
> To enable this command, navigate to https://nuget.codeplex.com/releases, select newest stable release, download NuGet.ServerExtensions.dll and Nuget-Signed.exe to your local disk and rename the Nuget-Signed.Exe to NuGet.exe.

What should I do to have this functionality with the latest NuGet version?

**Comment by rrelyea** [comment]
This is not supported in NuGet 3.x.
For now, we'll fix the docs.
We have an issue tracking supporting this scenario here: #2021

**Comment by harikmenon** [comment]
Here is the PR that updates the documentation https://github.com/NuGet/NuGetDocs/pull/460/files. @dee-see - We are working on some alternate designs at this time and if you would like to try this out, please email me at harikm@microsoft.com and I can give you some information around this that you can try out. Please note that the design and implementation is not final and subject to change.

**Comment by harikmenon** [comment]
@rrelyea can you review the PR above?

**Comment by dee-see** [comment]
Ok thanks for clearing that up.

I'll contact you @harikm86, I'm interested
