### ISSUE TITLE
Import fallback behavior is wrong

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2710]
Recreating https://github.com/NuGet/Home/issues/2377 because I'm still seeing issues with the latest NuGet.exe.

Consider the project

```
{
  "dependencies": {
    "System.Resources.ResourceManager": "4.0.1-rc3-24102-00"
  },
  "frameworks": {
    "netstandard1.3": { }
  }
}
```

Restore of this project is successful.  See https://gist.github.com/ericstj/a6d940bc23217b63c7d7cb5d16c7d9e6/cbe37f16491abfe0571779613b64111e50d961f0

Now add an import:

```
{
  "dependencies": {
    "System.Resources.ResourceManager": "4.0.1-rc3-24102-00"
  },
  "frameworks": {
    "netstandard1.3": {
      "imports": [ "portable-net45+win8" ]
    }
  }
}
```

Based on the spec for imports it should do **nothing** since the project was already restoring successfully.  Imports should only be used for a package if it was failing restore for the default framework.  That is not what happens, however.  The import is causing NuGet to resolve different assets in packages which previously resolved successfully.

Note the differences:
https://gist.github.com/ericstj/a6d940bc23217b63c7d7cb5d16c7d9e6/revisions#diff-c1e5585bccc57e553af12dd3b1ef45f8L42

**Comment by emgarten** [comment]
Assets are selected independently, the same issue could happen without imports where `ref` selects one TFM and `lib` selects another. Packages should add the same frameworks across all asset types to avoid situations like this.

That said, we have discussed selecting items from the lib, ref, runtime, and resources folders all at once so that they do not pivot independently and end up in this situation.  

//cc @davidfowl

**Comment by tmat** [comment]
@ericstj Is System.Resources.ResourceManager bad then?

**Comment by ericstj** [comment]
@emgarten I think you are missing the diff.

```
-          "ref/netstandard1.0/System.Reflection.Primitives.dll": {}
+          "ref/portable-net45+win8+wp8+wpa81/_._": {}
```

NETStandard1.3 is the target framework. Portable-\* is the import.  The netstandard1.0 asset should always be preferred here since it is better on the scale of target-framework > imports-target-frameworks.

I'm OK with the import adding a bunch of placeholders for Lib.  We'll still bring in impls via the runtime.json.  I'm not OK with NuGet deciding to take a less-specific ref.  That is most certainly a bug.

**Comment by ericstj** [comment]
I noticed that dotnet CLI doesn't exhibit this behavior, nor does the latest build of NuGet 3.5, so perhaps the fix for https://github.com/NuGet/Home/issues/2377 didn't make it into 3.4 somehow?

**Comment by rrelyea** [comment]
We expect CLI/NetCore users to be using 3.5.0-beta builds and later.
Given that, are we ok to close this issue?

**Comment by emgarten** [comment]
@ericstj yes, that does look like #2377. From the diff entries where it just adds in a new section and leaves compile the same it seemed like it was due to the package layout.

#2377 is not in 3.4.x, it went into 3.5.0

**Comment by ericstj** [comment]
Bummer. That means folks building PCLs with Update2 will hit this.  /cc @pilchie @rchande

**Comment by rrelyea** [comment]
Yes, 3.5.0-beta is the story for those users.
