### ISSUE TITLE
NuGet.Commands.RestoreCommand support for nuspec mode (work w/o nupkg on disk)

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2712]
NuGet.Commands.RestoreCommand should use `PackageFolderReader` instead of `PackageArchiveReader` when opening packages from the global folder. This is already true for most of the code but a few areas remain such as the CompatibilityChecker where `PackageArchiveReader` is used as a fallback.

When restoring packages with nuspec only mode the nupkg will not be saved, PackageArchiveReader will not be able to read the package in this mode.

**Comment by rrelyea** [comment]
Did you fix this in the minclientversion change?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@0836ef72d6b89d033f11ff21703dd693aea32515
