### ISSUE TITLE
Unhelpful error message when incorrectly using nuspec version tag of nuget pack

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/Home#2714]
I was just trying to use:

`nuget pack file.nuspec`

I was stuck for a while because of the error message:

`Value cannot be null or an empty string.
Parameter name: value`

Turns out this is because I was using `<version>$version$</version>` in my nuspec, but not explicitly passing the package version. That makes sense, but I struggled to track this down - would it be possible to improve the error message here, and perhaps at least point the user towards the part of the nuspec file causing the issue.

Thanks!

**Comment by rrelyea** [comment]
Repros in 3.4.3 nuget.exe. Attaching repro project.
1. build project
2. nuget pack blankconsole.nuspec

[repro2714-badErrorInPackWhenVersionIsParameterized.zip](https://github.com/NuGet/Home/files/249649/repro2714-badErrorInPackWhenVersionIsParameterized.zip)

**Comment by qwertie** [comment]
I'm sorry, what's wrong with using `<version>$version$</version>`? P.S. I'm having this problem too.

**Comment by qwertie** [comment]
If I add a version number then it complains about 

```
Id is required.
Authors is required.
Description is required.
```

The thing is, the references to `$author$`, `$title$`, etc **were produced by `nuget spec` itself** so I should think they ought to work.

**Comment by qwertie** [comment]
Ping! Geez, does anyone actually work on NuGet anymore?

**Comment by driscollwebdev** [comment]
@qwertie AssemblyInfo token replacement only works if you are calling nuget.exe pack and specifying your .csproj/.vbproj file to be packed. This behavior is documented [here](https://docs.nuget.org/create/creating-and-publishing-a-package):

> These tokens will only be replaced when you execute the pack command with the project file, and not with the nuspec file. The contents of the nuspec file will be located and honored, with the appropriate token replacements executed.

**Comment by qwertie** [comment]
@driscollwebdev Thanks! ... although this leaves me puzzled about how to get "token replacement" in case I want my package to have multiple versions of the same assembly - e.g. .NET 3.5 and .NET 4.5.

Targeting my csproj does basically work after dealing with #3049, although the output is kind of strange... 

```
> nuget spec
> nuget pack Loyc.Essentials.csproj -Build -IncludeReferencedProjects -Properties Configuration=Release.NET4
Building project 'D:\Dev\ecsharp\Core\Loyc.Essentials\Loyc.Essentials.csproj' for target framework '
.NETFramework,Version=v4.0,Profile=Client'.
...
... (misc output)
...
Successfully created package 'D:\Dev\ecsharp\Core\Loyc.Essentials\Loyc.Essentials.1.8.1.0.nupkg'.
Core Properties part: core property elements can contain only text data. Line 1, position 744.
```

A valid-looking nupkg **is** produced, but the final line is printed in red text. Hum.

**Comment by optical** [comment]
This is definitely an error message which could do with some improvement. It seems there are two problems with the message here.

Firstly it refers to a `value` parameter being null, which doesn't help with identifying that `version` is invalid. You basically have to resort to systematically editing/removing/replacing each element until the error goes away, which sucks.

The second is that if you run the pack command against a `.nuspec` which has replacement tokens in it, it'd be much nicer if there was an early exit with a helpful message letting you know that you should be using it against the corresponding csproj.

**Comment by lzybkr** [comment]
At a minimum, the error message should be improved, but as I mention in #6496 - sometimes expansion of a replacement token with nothing (because it was not specified) results in no error, and there should be a way to turn that into a good error.

**Comment by emz00** [comment]
Almost 2 years later, a simple error message improvement bug is still not fixed!

Is there a workaround for this when building a NuGet package for multiple .NET versions, as @qwertie  mentioned?

**Comment by btodts** [comment]
+1

**Comment by dsidirop** [comment]
+1

**Comment by emes001** [comment]
+1. I'm going zany trying to figure out what this missing "value" param is... ugh.

**Comment by dsidirop** [comment]
@emes001 Just append the flag "-Version 3.2.1.0"

**Comment by 0x241F31** [comment]
+1. :disappointed:

**Comment by brownbl1** [comment]
+10.

**Comment by TechnikEmpire** [comment]
Two years later, and hundreds of "developers" visiting this thread still haven't submitted a PR.

**Comment by btodts** [comment]
@TechnikEmpire What's holding you back then?

**Comment by TechnikEmpire** [comment]
@btodts I love it. Because I didn't fix it, it excuses the hundreds that have come before me, put useless "+N" comments, thumbs ups, sad faces etc. You're right, it's all on me.

Sorry I'm too busy contributing to over 50 other repositories. You guys are on your own, papa can't hold your hand today.

**Comment by driscollwebdev** [comment]
If you’re not offering a solution then you’re just contributing to the problem. What’s more, you’re being a jerk while doing it. Go spread your arrogance somewhere else.

**Comment by TechnikEmpire** [comment]
Hey why are so late to comment here? My comment was that the entire comment thread is not contributing to a solution, yet when I say, I'm a "jerk". Lol life must be rough being so sensitive.

**Comment by driscollwebdev** [comment]
Exhibit A:

“Sorry I'm too busy contributing to over 50 other repositories. You guys are on your own, papa can't hold your hand today.”

Was that really necessary? Did it add anything more to the discussion than the “useless +N” comments that you pointed out?

**Comment by TechnikEmpire** [comment]
So facts upset you? I was asked a question, specifically what was holding me back. I answered it. The fact that I'm contributing to an enormous amount of projects already is my excuse. If that offends you, well, as you said, noise that's not contributing to anything.

**Comment by driscollwebdev** [comment]
If you’re so busy then why bother commenting on this thread at all? Do you just enjoy stirring the pot and then conveniently bowing out when challenged to provide a constructive solution?

I managed to take time out of my 70+ hour work week to summarize the docs and explain the reason for the error message, no excuses.

**Comment by TechnikEmpire** [comment]
That's not a shock considering that web development isn't really work. Anyway you came here losing your mind over unconstructive input when my comment was that all the comments here are unconstructive. Makes no sense, except for the part where you accused me of arrogance, which means you just felt small and so lashed out. Anyway last comment because otherwise I'm going to have to bill you for psychotherapy.

**Comment by driscollwebdev** [comment]
Ah, so you really are just a troll. Noted. 👌🏻👍🏻

**Comment by TechnikEmpire** [comment]
3 lines of code lol

**Comment by driscollwebdev** [comment]
Sounds about right for catching and wrapping an ArgumentNullException.

**Comment by theunrepentantgeek** [comment]
Whoop! Thanks @TechnikEmpire
