### ISSUE TITLE
Can't install version 3.4.3.855 of VSIX - "IOException: The process cannot access the file..."

### ISSUE THREAD

**Issue by alareau** [NuGet/Home#2716]
Hi, 
When I went to update nuget this morning with version 3.4.3.855 (both directly from VS2015 and by downloading the extension from https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d)
I get the following error.
![nugeterrorscreen](https://cloud.githubusercontent.com/assets/959561/15016691/5804009c-11e0-11e6-8bff-2251cbd00d3f.PNG)

When I open the log file, I get Install _Error : System.IO.IOException: The process cannot access the file because it is being used by another process_.

I've rebooted the computer and made sure that vs2015 wasn't running before trying again but with the same issue. (i've zipped up the log file.)  It's not very descriptive.  I'm not sure if a corporate gpo is causing the issue or not.

[VSIXInstaller_fc19409f-fd64-47c8-a80f-1a36981a3adc.zip](https://github.com/NuGet/Home/files/248879/VSIXInstaller_fc19409f-fd64-47c8-a80f-1a36981a3adc.zip)

thanks!

**Comment by harikmenon** [comment]
Looks like an external issue. Can you try the workarounds listed here in this issue https://github.com/NuGet/Home/issues/1138

**Comment by rrelyea** [comment]
closing issue. Please chime in if anybody hits this issue with that or other versions.
