### ISSUE TITLE
Unable to find compatible `Microsoft.CSharp` version when installing from nuget.org

### ISSUE THREAD

**Issue by gmarz** [NuGet/Home#2717]
We're running into the following error when trying to install the latest version of our Elasticsearch.Net package (v2.3.1) when targeting any 4.x .NET Framework version.  This doesn't seem to be a problem on .NET Core (1.0.0-rc1-update1).

```
PM> Install-Package Elasticsearch.Net
Attempting to gather dependencies information for package 'Elasticsearch.Net.2.3.1' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'Elasticsearch.Net.2.3.1' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'Microsoft.CSharp' that is compatible with 'Elasticsearch.Net 2.3.1 constraint: Microsoft.CSharp (≥ 4.0.1-beta-23225)'.
At line:1 char:1
+ Install-Package Elasticsearch.Net
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

The project.json file for Elasticsearch.Net is [here](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/project.json).  There have been no dependency changes from 2.3.0 (which has no issues) to 2.3.1.

If I download the package files from nuget.org and install from a local feed, then it works fine.

Linking https://github.com/elastic/elasticsearch-net/issues/2079 for more context.

**Comment by rrelyea** [comment]
V2 or v3 feed from NuGet.org?

**Comment by gmarz** [comment]
Ah...this only happens on the v2 feed.

**Comment by gmarz** [comment]
So, I'm not really sure if this is an issue now since using the correct feed based on the version of VS works (v2/2013, v3/2015).

It just caught us (and users) by surprise since the v2 feed use to work in VS2015 for earlier versions of the package.

**Comment by rrelyea** [comment]
Looks similar to https://github.com/NuGet/NuGetGallery/issues/3015 which has been fixed.
A problem with our v2 feed from NuGet.org
Try v3 feed, see 4.5 and 4.6 w/ no dependencies
Try v2 feed on nuget.org, 4.5 and 4.6 are not mentioned in VSIX UI.

**Comment by gmoskovicz** [comment]
I got the same issue today:

```
Attempting to resolve dependencies for package 'NEST.2.3.1' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'Microsoft.CSharp' that is compatible with 'Elasticsearch.Net 2.3.1 constraint: Microsoft.CSharp (>= 4.0.1-beta-23225)'.At line:1 char:1
+ Install-Package NEST
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

I think that the min version from the nest Library is `4.0.1-beta-23225`: https://github.com/elastic/elasticsearch-net/blob/2.x/src/CodeGeneration/Nest.Litterateur/project.json#L76

Can this be causing this?

**Comment by russcam** [comment]
@gmoskovicz The `Nest.Litterateur` project is a supporting project to generate documentation from test source code so doesn't get packaged in either the Elasticsearch.Net or NEST packages.

The Elasticsearch.Net project's project.json has a dependency on `Microsoft.CSharp 4.0.1-beta-23225` for the `dotnet5.1` TFM build; [it's had this since late January](https://github.com/elastic/elasticsearch-net/commit/bb532d04d46bb660bb5ade1c456a6821f5fd14b4#diff-b8fcc6c7e6994169cf151c5a1207dc43R70) and there have been 12 releases with this dependency, with only the last (2.3.1) having this issue.

@rrelyea, Have there been changes to the v2 feed that would affect DNX RC1 project dependencies?

**Comment by maartenba** [comment]
Just flowed the package through our back-end again, seems we missed this one after fixing NuGet/NuGetGallery#3015. Package should now have the dependencies listed correctly.

**Comment by maartenba** [comment]
@gmarz is this working for you now?

**Comment by gmarz** [comment]
@maartenba Yes, looks to be working now.  Thank you.
