### ISSUE TITLE
NuGet.exe config needs to warn on incorrect syntax usage

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2727]
Removing config value doesn't work when `nuget config -set name` is used. But there is no warning on incorrect usage.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
