### ISSUE TITLE
NuGet.exe config should create new nuget.config file

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2728]
There is no way to create a new nuget.config file using the nuget.exe. I would expect `nuget.exe config -ConfigFile '<fileName>'` to create a new file. 
    1. Instead it fails saying there is no file.
    2. If there is an empty file, it says there is no writable config files.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
