### ISSUE TITLE
Lists in project.lock.json no longer sorted with OrdinalIgnoreCase

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2731]
I noticed that in NuGet.exe 3.3, project.lock.json lists (in the `files` field arrays) were sorted with OrdinalIgnoreCase. Now in NuGet.exe 3.4.4, they are sorted with Ordinal. 

This makes it harder to find files in the lists because they aren't where a person would typically find them in alphabetical order (`Z` appears before `a`).

Perhaps low priority, but wanted to raise it in case this was not intentional.

**Comment by jainaashish** [comment]
It might have been intentional with respect to cross platforms, but not sure. But let us know if this is still an issue, will look into it then.
