### ISSUE TITLE
Unable to install packages from private feed in Mac

### ISSUE THREAD

**Issue by mathikp** [NuGet/Home#2733]
We have a private NuGet feed (NuGet.Server). We are unable to install packages from that feed using nuget.exe in Mac. Can install package from nuget.org. But cant install package from the private feed. Also, I have tried to install packages from local directory as package source which also fails. How can I install package from any local directory in Mac?

**Comment by jainaashish** [comment]
No further communication here, closing it for now. Let us know if this is still an issue.
