### ISSUE TITLE
Collect dependencies for target packages is slow

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2736]
We collect all the dependencies for all the target ids which are to be updated or installed right before deciding the install/uninstall actions in nuget package manager. For a scenario where you have 5 targets each having 20-30 deep dependencies chain takes ~10 mins to complete. where as it should not have taken more than ~30ms.

Real issue is as in other cases, we dont maintain visited nodes while walking down the graph which forces it to calculate dependencies for same node again n again and bump up the stack with multiple duplicate entries.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L1063

**Comment by MichaelLogutov** [comment]
This is big. Updating packages in solution with 100 project taking HOURS. No really. It's not usable.
