### ISSUE TITLE
Dev15: Got "The extension is not installable on any currently installed products" during installing preview vsix 3.4.2

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2737]
This is user report from NuGet.org support request.

Hi, I am using VS 15 Preview and would like to install NuGet. I downloaded "VS '15' Preview VSIX (v3.4.2)" but the installer just says "The extension is not installable on any currently installed products". I installed Visual Studio 15.0.25123.0 Preview using the new slim installer (only the C++ components) on a secondary hard disc. The NuGet installer log only lists my other Visual Studio 2015 installation in the "Found installed product" section. The full log is attached below. Regards Fabian Löschner Install log: 06.05.2016 16:43:09 - Microsoft VSIX Installer 06.05.2016 16:43:09 - ------------------------------------------- 06.05.2016 16:43:09 - Initializing Install... 06.05.2016 16:43:09 - Extension Details... 06.05.2016 16:43:09 - Identifier : NuGet.72C5D240-F742-48D4-A0F1-7016671E405B 06.05.2016 16:43:09 - Name : NuGet Package Manager for Visual Studio 15 Preview 06.05.2016 16:43:09 - Author : Microsoft Corporation 06.05.2016 16:43:09 - Version : 3.4.2.827 06.05.2016 16:43:09 - Description : A collection of tools to automate the process of downloading, installing, upgrading, configuring, and removing packages from a VS Project. 06.05.2016 16:43:09 - Locale : en-US 06.05.2016 16:43:09 - MoreInfoURL : 06.05.2016 16:43:09 - InstalledByMSI : False 06.05.2016 16:43:09 - SupportedFrameworkVersionRange : [0.0,2147483647.2147483647] 06.05.2016 16:43:09 - 06.05.2016 16:43:10 - SignatureState : ValidSignature 06.05.2016 16:43:10 - SignedBy : Microsoft Corporation 06.05.2016 16:43:10 - Certificate Info : 06.05.2016 16:43:10 - ------------------------------------------------------- 06.05.2016 16:43:10 - [Subject] : CN=Microsoft Corporation, OU=MOPR, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 06.05.2016 16:43:10 - [Issuer] : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 06.05.2016 16:43:10 - [Serial Number] : 33000000FF6B54F91DD1781A1C0000000000FF 06.05.2016 16:43:10 - [Not Before] : 12.02.2016 02:12:29 06.05.2016 16:43:10 - [Not After] : 12.05.2017 03:12:29 06.05.2016 16:43:10 - [Thumbprint] : 6F1691367DB1D2F6278B8A82A1C4095D3BC0AF1C 06.05.2016 16:43:10 - 06.05.2016 16:43:10 - Supported Products : 06.05.2016 16:43:10 - Microsoft.VisualStudio.Pro 06.05.2016 16:43:10 - Version : [15.0,16.0) 06.05.2016 16:43:10 - Microsoft.VisualStudio.Community 06.05.2016 16:43:10 - Version : [15.0,16.0) 06.05.2016 16:43:10 - 06.05.2016 16:43:10 - References : 06.05.2016 16:43:10 - Signature Details... 06.05.2016 16:43:10 - Extension is signed with a valid signature. 06.05.2016 16:43:10 - 06.05.2016 16:43:10 - Searching for applicable products... 06.05.2016 16:43:10 - Found installed product - Microsoft Visual Studio Enterprise 2015 06.05.2016 16:43:10 - Found installed product - Microsoft Visual Studio Professional 2015 06.05.2016 16:43:10 - Found installed product - Microsoft Visual Studio Community 2015 06.05.2016 16:43:10 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated) 06.05.2016 16:43:10 - Found installed product - Global Location 06.05.2016 16:43:10 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products. at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported) at VSIXInstaller.App.InitializeInstall() at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task.Execute()

**Comment by w1th0utnam3** [comment]
Hi, I wrote the support request. More information (contains all from above, thanks web form for the great formatting...):
- I downloaded the `VS '15' Preview VSIX (v3.4.2)` package from the official website (https://dist.nuget.org/index.html)
- Error message: 
  
  > The extension is not installable on any currently installed products
- I can reproduce this on two physical Windows 10 machines.
- On both machines Visual Studio 2015 Enterprise and Visual Studio 15 Preview are installed
- Visual Studio 15 Preview was installed using the "new installer" with a minimal C++ environment on both machines
- One machine is running Windows 10 Pro Insider Preview build 14332, both Visual Studio versions are installed to a secondary hard disc
- The second machine is running Windows 10 Education (release build) and both Visual Studio versions are installed to their default directories
- The preview version number of Visual Studio is `Visual Studio 15.0.25123.0`
- The default `VS 2015 VSIX - latest (v3.4.3)` package installs successfully on both machines
- Log file: [VSIXInstaller_e403cab2-41af-4a06-8a5e-8a61a0284573.txt](https://github.com/NuGet/Home/files/252889/VSIXInstaller_e403cab2-41af-4a06-8a5e-8a61a0284573.txt)

**Comment by rrelyea** [comment]
We'll follow up with the VS team to understand if this is a problem with our VS "15" preview VSIX or if it is a generally VSIX installation issue.
(right now our VS "15" Preview version has a bug - it won't install any nuget components into C++ projects. So even if you did get it installed, you would be able to use it for much yet.
Thanks for the report.

**Comment by jainaashish** [comment]
fixed with latest release
