### ISSUE TITLE
VS API: Verify V2 compat

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#274]
Verify V3 VS API parity with the V2 VS API

Example scenarios:
1. Install package, Package not found exception
2. Install package - already installed
3. Install package - already installed, different version
4. Uninstall package - not found
5. Uninstall package - still required by another package
6. Package restorer errors

**Comment by yishaigalatzer** [comment]
Please verify and add functional tests as needed

**Comment by zhili1208** [comment]
Verified and added tests in https://github.com/NuGet/Home/issues/583
