### ISSUE TITLE
ResolveNuGetPackageAssets msbuild task fails processing analyzers

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#2740]
Build of NuProj fails when project depends on a package with analyzers.

> Severity  Code    Description Project File    Line
> Error     Object reference not set to an instance of an object.
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.IsFileValid(String file, String expectedLanguage, String unExpectedLanguage)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.TryGetFile(String packageName, String packageVersion, String file, String& path)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetAnalyzers(JObject lockFile)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute() NuGetPackage1   C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets  140

**Repro steps**
1. Create solution with .NET Core class library project
2. Install StyleCop.Analyzers 1.0.0 package
3. Add NuProj project
4. Add class library as a dependency to the latter
5. nuget restore
6. msbuild

**Comment by AArnott** [comment]
#2732 demonstrates that this failure is _new with nuget.exe 3.4.4_. That is, with the MSBuild Task unchanged, nuget.exe restore with v3.3 _can_ build, but using v3.4.4 of nuget.exe for restoring packages _can't_ build.

CC: @rrelyea @yishaigalatzer If I could pick just one bug to be sure to fix before 3.4.4's release, it would be this one (assuming it is in fact a dupe of #2732, which is the one I hit). The workaround for it isn't particularly pretty, and I'd rather not have to fix up all the project.json files in all my projects to workaround a regression if we can avoid it.

**Comment by yishaigalatzer** [comment]
Talked to Alex and Justin. We think this has to do with adding top level support for nuproj. We will verify this doesn't happen from csproj to csproj, and then we should proceed with a decision

**Comment by kovalikp** [comment]
The issue is caused by fact that NuProj does not set `Language` msbuild property. Setting it to any value does not appear to have any adverse effect on NuProj build system itself, but for sake of future-proofing it would be pertinent to handle possible null values of `ProjectLanguage` property in `ResolveNuGetPackageAssets` task.

**Comment by ias0nas** [comment]
Any updates on this?
I am getting the same issue when trying to build a .net core project with TeamCity.

> [ResolveNuGetPackageAssets] ResolveNuGetPackageAssets
> [11:16:38]  [ResolveNuGetPackageAssets] C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(140, 5): Object reference not set to an instance of an object.
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.IsFileValid(String file, String expectedLanguage, String unExpectedLanguage)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.TryGetFile(String packageName, String packageVersion, String file, String& path)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.GetAnalyzers(JObject lockFile)
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.ExecuteCore()
>    at Microsoft.NuGet.Build.Tasks.ResolveNuGetPackageAssets.Execute()

**Comment by jainaashish** [comment]
I don't think nuproj is supported for VS 2017. Let me know if it's indeed supported and still an issue.

**Comment by ViktorHofer** [comment]
This still happens, we currently face this in corefx when adding a PackageReference to xunit.analyzers. For any project type which doesn't have the Language property set, this will result in a NullReferenceException: https://github.com/NuGet/NuGet.BuildTasks/blob/0aa5091682343110f645ede1a184ee7fea127b7b/src/Microsoft.NuGet.Build.Tasks/ResolveNuGetPackageAssets.cs#L473

**Comment by jainaashish** [comment]
reactivating the bug since this is still an issue.

Tagging @Pilchie @tmeschter since this is own by Project System.

**Comment by tmeschter** [comment]
@ViktorHofer Can you describe your scenario in more detail? What kind of a project are you dealing with?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/corefx/pull/31260/files#diff-841e9e59d27acec708f2c73eaa3cf6a0R24

We are using a custom proj file. See that I hardcoded the language here as otherwise it will fail when referencing xunit.analyzers. I will change that line though to "unknown". cc @ericstj

**Comment by amamlesh** [comment]
We are facing this issue with pyproj file. Any updates on this?

**Comment by tmeschter** [comment]
@amamlesh This is a low priority for us as the problem can be avoided by setting the `Language` property. We would also consider a PR into the https://github.com/dotnet/NuGet.BuildTasks repo.

**Comment by nkolev92** [comment]
Moving this to https://github.com/dotnet/NuGet.BuildTasks/issues/73.
