### ISSUE TITLE
nuspec with empty files section still includes files

### ISSUE THREAD

**Issue by asherber** [NuGet/Home#2742]
Using NuGet client 3.4.3.855.

I'm trying to build a dependency-only package. My nuspec file includes a blank `<files />` element, but `nuget pack` still includes other files in the directory.

**Comment by rrelyea** [comment]
@toddm  can you please work to get details and check for regression, etc...

**Comment by toddm** [comment]
I'm able to see the issue. The code just checks if there any files in the list when deciding whether or not to include all files instead of whether not there was an element there. It is a regression from 3.3.0. I'll prioritize fixing it.

**Comment by rrelyea** [comment]
Consider fix for 3.4.4 if slam dunk fix.
