### ISSUE TITLE
checking for update of nuget packages in a solution/exe

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#2743]
When building a solution, all the nuget packages should check for updates (it can be in specified intervals also, instead of every build, like every one week, the solution would be checking for updates of nuget packages). This can also be implemented in the exe. Whenever the exe is run, it will check for updates of nuget packages that were used in building this exe.

**Comment by rrelyea** [comment]
We'd like to leave this in the customer hands. As we think auto-updating packages as part of the build would be problematic. 
Users could a pre-build script to check for updates if this was important to them.

**Comment by ranjan-2209** [comment]
OK. Another solution to the problem.
