### ISSUE TITLE
Nuget update command ignore "DependencyVersion" setting set in nuget.config

### ISSUE THREAD

**Issue by bondarchook** [NuGet/Home#2746]
In **nuget.config** i set  DependencyVersion to Lowest like this

```
<config>
    <add key="dependencyversion" value="lowest" />
</config>
```

when I do call nuget.exe update command this setting ignored completely and it update all packages to  highest version.

if I have next project structure 

```
Project1 ---+
                  ---- Package A (ver 1)
                  ---- Package B (ver 100)  <- Package B depends on Package A
```

I expect after update with DependencyVersion to **Lowest** to see something like this

```
Project1 ---+
                  ---- Package A (ver 2) 
                  ---- Package B (ver 101)  <- depends on Package A (ver 2)
```

So package A is resolved to version **2** because Package B depend on version 2 even though higher versions of package A available

**Comment by rrelyea** [comment]
When you run nuget update, you can choose to update 1 package via "-id" .. and you would get what you want.
If you don't specify this, we update all packages by default, and the behavior is correct for that.

**Comment by bondarchook** [comment]
What if I put more then one package id in to "-Id"? 
What if I put -Id "Package A; Package B" from example above?

Do I really have to update things one package at a time?
And how is it correct behavior if it is create inconsistency in references? 

I specifically choosing **Lowest** strategy to find lowest common denominator for all packages.

**Comment by knightpfhor** [comment]
I understand that the behaviour is as designed, but it is now inconsistent with the package manager console and with the VS plugin.  These will default to getting the highest versioned dependency, but allow for you to specify something different if you have to.

I suspect that the problem comes from the resolution strategy being hard coded in NuGet.CommandLineUpdateCommand.UpdatePackagesAsync:
    var resolutionContext = new ResolutionContext(
                           Resolver.DependencyBehavior.Highest,
                           Prerelease,
                           includeUnlisted: false,
                           versionConstraints: versionConstraints);

**Comment by knightpfhor** [comment]
It seems that this is already a high priority feature #1806.

**Comment by element533** [comment]
@rrelyea, it does not appear that NuGet.exe respects the DependencyVersion config setting in NuGet.config at all, even when specifying an individual package with the `-Id` parameter. The `nuget update` command seems to always use 'Highest'.

I have this in my `.\nuget.config` file:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <config>
        <add key="DependencyVersion" value="Lowest" />
      </config>
      ...

I have a solution file at `.\MyApplication.sln`. I am updating a package `MyPackage` to version `2.4.0`, which references `Newtonsoft.Json 8.0.3`. When I run `nuget update -Id MyPackage`, it installs `Newtonsoft.Json 10.0.2` (not the lowest):

    Attempting to gather dependency information for multiple packages with respect to project 'C:\Work\MyApplication\src\Core\MyApplication.Core.csproj', targeting '.NETFramework,Version=v4.5'
    Gathering dependency information took 1.32 sec
    Attempting to resolve dependencies for multiple packages.
    Resolving dependency information took 0 ms
    Resolving actions install multiple packages
    Retrieving package 'Newtonsoft.Json 10.0.2' from 'NuGet2'.
    Retrieving package 'MyPackage 2.4.0' from 'Artifactory'.
      GET http://(in-house-artifactory-server)/Packages(Id='MyPackage',Version='2.4.0')
      GET https://www.nuget.org/api/v2/Packages(Id='Newtonsoft.Json',Version='10.0.2')
    ...

The `nuget install` command also ignores this setting, although it uses a different default behavior. It seems to always use 'Lowest'.

In this case, when I set my `.\nuget.config` file to:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <config>
        <add key="DependencyVersion" value="Highest" />
      </config>
      ...

and run `nuget install MyPackage -Version 2.4.0`, NuGet ignores my DependencyVersion setting and uses 'Lowest':

    Attempting to gather dependency information for package 'MyPackage.2.4.0' with respect to project 'C:\Work\MyApplication\src\Core', targeting 'Any,Version=v0.0'
    Gathering dependency information took 3.2 sec
    Attempting to resolve dependencies for package 'MyPackage.2.4.0' with DependencyBehavior 'Lowest'
    Resolving dependency information took 0 ms
    ...

All of the documentation around this feature indicates it should work, but it does not.

**Comment by erick-thompson** [comment]
I've run into this same issue. The DependencyVersion is not getting picked up from the nuget.config specific on the command line via -ConfigFile.

**Comment by spotlesscoder** [comment]
When I read the documentation correctly and did not miss anything, the default global NuGet.config also does not support the dependency behaviour "IgnoreDependencies"

https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

Whyyyyy?

**Comment by jainaashish** [comment]
Current thinking is to let users move to `PackageReference` and use commandline for NuGet operations where you won't need all these different switches in nuget.config file. So I'm closing it in that regards.
