### ISSUE TITLE
Security issue: nuget sources add takes password in clear text on command line

### ISSUE THREAD

**Issue by rickwebiii** [NuGet/Home#2750]
Command lines are logged as part of Windows Command Line Auditing. https://technet.microsoft.com/en-us/library/dn535776.aspx. This is problematic with any command that takes a password on the command line, such as nuget sources add.

On a machine with this feature enabled (which by default is any machine as of Win 10), any password you type will be logged in clear text in the Event Viewer. To see such events, open, the event viewer, Windows Logs, click Filter Current Log... on the right, and fill in event id 4688.

All commands that take a password on the command line should instead securely prompt for the password after starting execution and the -Password switch be deprecated and removed.

**Comment by rickwebiii** [comment]
Ping

**Comment by fatso83** [comment]
It's open source. Try to look at the source and make a PR. Has far better chances of doing anything than pinging some GH issue.

**Comment by emgarten** [comment]
Credentials should be provided through NuGet.Config and encrypted. The prompt is an optional way to provide credentials if they were not set in NuGet.Config.
