### ISSUE TITLE
IVsPackageInstallerEvents could do with some more events

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [NuGet/Home#2751]
Sometimes I need to install NuGet packages programmatically in my VS extension.  I am using the API to do this, and it is working, however it would be nice to provide a little more feedback to the user during the process.

I would like for example the following events:
DependencyResolved 
DependencyResolving
PackageScriptExecuting
PackageScriptExecuted 

Currently these operations all happen in the background and I only know when a reference has been added or when a package is installed/uninstalled.  So currently my process runs, and at the end its all magically done, and I have to assume scripts have been run etc.

Some extra events that indicate more of the process that is going on would be very helpful so that I can provide this feedback to my users.

**Comment by rrelyea** [comment]
Putting into a future milestone. Could consider allowing caller to pass in a logger.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
