### ISSUE TITLE
Aliignment issues in Web.Config.Transform

### ISSUE THREAD

**Issue by mathikp** [NuGet/Home#2752]
Hi Team,

We have faced the alignment issue in web.config.transform file while installing our custom nuget package. I have created the sample NuGet packages for show this alignment issue.

I have added the below web.config.transform entries in my NuGet packages.

> <configuration>

```
<system.web>

    <compilation>
        <assemblies>
            <add assembly="ASSEMBLY1, Version=1.0.10, Culture=neutral"/>
            <add assembly="ASSEMBLY2, Version=1.0.11, Culture=neutral"/>
            <add assembly="ASSEMBLY3, Version=1.0.12, Culture=neutral"/>
            <add assembly="ASSEMBLY4, Version=1.0.13, Culture=neutral"/>
        </assemblies>
    </compilation>
</system.web>
```

</configuration>

Steps to reproduce.
1. Create ASP.NET MVC Application.
2. Download the Sample NuGet packages from [here ](https://github.com/NuGet/Home/files/256887/Web.config.Test.NuGets.zip) and unzip it.
3. install the package named as **MyPackage.1.0.0** as first. It shows the assemblies entries correctly in Web.Config.

![nuget 1](https://cloud.githubusercontent.com/assets/13851265/15142832/68a97e84-16c4-11e6-9fda-d0cf17d34d6a.PNG)

4.Then install the package named as **MyPackage2.1.0.0**. It will append all the assemblies entries in single line. Refer the screenshot below,

![nuget2](https://cloud.githubusercontent.com/assets/13851265/15142865/9fa781ce-16c4-11e6-9edb-4b40e19c652d.PNG)

Please suggest me how to resolve this issue ? 

Thanks in Advance.

**Comment by jainaashish** [comment]
Thanks for the feedback but currently we're tied up with other priority work so won't be able to get to this. Closing it with lower priority.
