### ISSUE TITLE
Changelog summary and links for package manager updates

### ISSUE THREAD

**Issue by jnm2** [NuGet/Home#2753]
The number one thing I want to do every time I upgrade a package in the VS package manager is read the changelog for every version between the version I have and the newest version. It would be fantastic to have an expandable section visible near the version dropdown or near the description when an upgrade is available, listing changes from each version.

Ideally once #1203 is resolved more packages will have better release notes, but if they are nonexistent even just a series of links to click for each version increment would be terrific.

Currently as far as I know there is nothing helpful for this; I have to scroll to the bottom and find each project URL link, then navigate around each website till I find the page(s) I need to skim. This can be time consuming and makes it difficult to rapidly absorb details that may be relevant to the upgrades.

**Comment by xoofx** [comment]
As per issue [markdig:167](https://github.com/lunet-io/markdig/issues/163)
I'm not sure this is exactly the same requirement, but it would be super nice if in the new csproj we could specify a `changelog.md` file that would be linked automatically from the NuGet Gallery , similar to the way Visual Studio Code extensions are working, which are nicely handling this...

**Comment by jainaashish** [comment]
Thanks for the feedback but currently we're tied up with other priority work items so won't be able to get to this.
