### ISSUE TITLE
nuget.exe pack fails when packaging csproj with rc2 dependencies in packages.config

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2754]
Repro happens in 3.3, 3.4, 3.5

Command ran:
NuGet.exe pack "C:\Nuget\NuGet.Jobs\src\NuGet.Services.Logging\NuGet.Services.Logging.csproj"

Result:
Attempting to build package from 'NuGet.Services.Logging.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Packing files from 'C:\Nuget\NuGet.Jobs\src\NuGet.Services.Logging\bin\Debug'.
Using 'NuGet.Services.Logging.nuspec' for metadata.
Found packages.config. Using packages listed as dependencies
**Core Properties part: core property elements can contain only text data. Line 4, position 33.**

In order to repro, pull this repo: https://github.com/NuGet/NuGet.Jobs/tree/feature/LoggingToRc2

**Comment by rrelyea** [comment]
Putting into 3.4.4 -- but could be 3.4.4 3.5.0-beta or later...

**Comment by ShikiGami** [comment]
is there any workaround for this in the meantime?

**Comment by Mertsch** [comment]
@ShikiGami and all who run into the same thing
Using https://www.myget.org/feed/nugetbuild/package/nuget/NuGet.CommandLine 3.5.0-rc-1365 fixes the issue

**Comment by mafalarz** [comment]
How do you run NuGet.CommandLine?
