### ISSUE TITLE
url encoding using HttpClient (Microsoft HTTP... 2.2.29 (latest stable))

### ISSUE THREAD

**Issue by rudras1** [NuGet/Home#2757]
Problem:

URL encoding is not working when I call a .net dll (that has the encoding logic) from SSIS script task. But works as expected when I call the same dll from a .net console project.

Description:

I have built a .net function that is part of a dll I reference in SSIS script task.

This .net function takes in a string value as parameter and builds a uri. I url encode the parameter value since it has special characters, in this case it is a / (forward slash).

When I reference this function in a .net console application the url encoding works as expected. But when I reference this same module in SSIS script task, the / does not get encoded. The target framework is 4.5 (both in .net dll and SSIS script task)

Http Request Generated from below code:

URl Request from SSIS Script task:

GET https://api-servername.net/client/office/Raleigh+Addr%3a+AFO-613/618/custom-data

URl Request from .Net Console application (correct one):

GET https://api-servername.net/client/office/Raleigh+Addr%3a+AFO-613%2f618/custom-data

.Net DLL Code that is referenced :

public void GetLCDClientOffice(string officename) 
{
    using (var client = BuildClient())
   {
       var url = String.Format("{0}/{1}/{2}"
                  , this.ResourceName 
                  , this.OFFICE_PATH 
                  , Uri.EscapeDataString(officename));          

```
  var uri = new Uri(ServiceUri, url);   

  string url1 = ServiceUri.ToString() + 
                String.Format("{0}/{1}/{2}",this.ResourceName
                              , OFFICE_PATH,  System.Web.HttpUtility.UrlEncode(officename));

    // Get Async unescapes %2F back to / when called from from SSIS script task but works from .net console project
    var response = await client.GetAsync(uri); 
    var response = await client.GetAsync(url1); // same behavior

    // do something with response
```

   }
}
public HttpClient BuildClient()
{
     var client = new HttpClient();
     client.Timeout = new TimeSpan(0, 30, 0);

```
return client;
```

}

**Comment by emgarten** [comment]
This does not look related to nuget.
