### ISSUE TITLE
System Test Nuget package before commiting to nuget server

### ISSUE THREAD

**Issue by raulplanas** [NuGet/Home#2759]
I am new to nuget package development. Curious on best way to locally test a nuget package before publishing. This is for internal development where packages are only hosted internally. I don't want to only test the binaries in nuget package.

Ideally I could have a project that I could redirect to consume my local copy of nuget package. Then after I publish the package, I can easily redirect it to consume the published package.

**Comment by emgarten** [comment]
Use a local folder as a package source.
