### ISSUE TITLE
Pack fails when properties have HTML encoded text

### ISSUE THREAD

**Issue by pvandervelde** [NuGet/Home#2761]
When you have HTML encoded text in a property nuget pack fails with the error

```
' is an unexpected token. The expected token is ';'. Line 15, position 16.
```

The nuspec file for this test case is:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>a</id>
        <version>1.0.0</version>
        <authors>b</authors>
        <owners>c</owners>
        <licenseUrl>http://www.apache.org/licenses/LICENSE-2.0</licenseUrl>
        <projectUrl>http://google.com</projectUrl>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>
            e
        </description>
        <releaseNotes>
            $Prop$
        </releaseNotes>
        <dependencies>
            <dependency id="other" version="1.0.0" />
        </dependencies>
    </metadata>
    <files>

    </files>
</package>
```

And the command line is:

```
nuget.exe pack "C:\temp\test.nuspec" -OutputDirectory "C:\temp\nuget" -Properties Prop="&gt;"
```

If you manually replace `$Prop$` in the nuspec file with `&gt;` then it works fine. But it doesn't work if you pass the text `&gt;` to nuget via the Properties argument.
I'm guessing this is a problem with not escaping correctly but I've tried everything I can think of (', ", \, ^, ^^^, ...) and nothing works.

**Comment by tcabanski** [comment]
Try enclosing in CDATA.  Worked for me (I actually had a problem with a URL but also seems to work in this case:

<![CDATA[<]]>

**Comment by emgarten** [comment]
CDATA is the correct way to handle this.
