### ISSUE TITLE
NuGet on Gitter?

### ISSUE THREAD

**Issue by ghuntley** [NuGet/Home#2762]
It would be really useful to have a place where other maintainers of packages could gather and seek advice on how to package stuff up and share knowledge with other package maintainers, etc. Similar to the corefx/coreclr channels on gitter.

**Comment by daveaglick** [comment]
Also for folks trying to integrate with the API. There's so little documentation on this right now that a place to exchange advice and ideas in real-time could be really helpful.

**Comment by harikmenon** [comment]
Thanks for raising this. We have been talking about this with the team for a while. We are currently thinking about gitter or slack. @daveaglick @ghuntley any preferences? I'm a bit more inclined to use slack since conversations are a bit more easier to follow along.

**Comment by ghuntley** [comment]
I love Slack but the standard for dotnet foundation / corefx / coreclr /
Xamarin is gitter. Please stick with Gitter.

**Comment by daveaglick** [comment]
@harikm86 My vote would strongly be for Gitter. I find the way that it natively integrates with GitHub events to be valuable. I also like that it's a default-open community with an official web interface (as opposed to a default-closed community with only clients for Slack). That makes it seem much more welcoming and easier to jump in and out of.

**Comment by harikmenon** [comment]
Let me circle back with the team, get their thoughts and will respond as soon as possible.

**Comment by harikmenon** [comment]
Not forgotten about this yet. Waiting for all the engineering managers to come back from their vacays before making a decision on this.

**Comment by harikmenon** [comment]
We took an inventory of all the feedback sources our team is monitoring, we have over 10 at this time. Given the capacity of the team, adding one more high volume source might stretch us quite a bit. 

So, we want to hold off for a bit until we can get better tools or process in place to either consolidate or eliminate some of these :(. I know this is probably not he answer you are looking for at this time, but I promised we will reconsider this once we can free up some capacity here.

Even if we let the community run itself, there is an implicit expectation for heavy product team participation, so we are a bit wary :)

**Comment by OsirisTerje** [comment]
Where is this issue now?  Still no gitter, nor slack?  Anything else?

**Comment by OsirisTerje** [comment]
(It says I unassigned @harikmenon , but nope, I didnt)

**Comment by rrelyea** [comment]
Looping in @anangaur -- and marking as needs triage.

**Comment by jnm2** [comment]
For what it's worth, this is the second or third time I've been looking for the NuGet gitter channel and ended up here.

**Comment by anangaur** [comment]
@jnm2 I think gitter channel would be a great value add, in general. What I am not sure right now is what the expectation from such a gitter channel would be from the NuGet team? 

Example, if there is a question on NuGet, should NuGet team be **obliged** to answer it or let the community take care of the conversation (Obviously the team members are free to participate at will)?

If it is the former, then we need a bigger discussion in the team to light this up as it requires time and effort from the team. 

Secondly while I feel a Gitter channel is good from conversation point of view for quick 'How to dos?', for any specific involved question I feel the Github issues serve better as they can be referred/searched easily in future.

Comments?

**Comment by jnm2** [comment]
My expectation is that it would be handled the same way that corefx, coreclr, roslyn, and others handle their channels. Not a support channel so much as a way for us to talk about things that are off-topic in, say, the corefx channel. If I don't get a response on Gitter and it's blocking me, I'll open an issue.

**Comment by daveaglick** [comment]
I don't think there _needs_ to be any level of expected participation by the NuGet team (though some participation would obviously be nice). The problem right now is that without an "official" real-time chat channel there's no where for the community to gravitate towards. Creating such a channel would help direct users to a common place.

**Comment by mwpowellhtx** [comment]
:+1:  Gitter would be great!

I agree, I wouldn't expect "team" involvement, per se, but it would be nice to have. It's more for community, experts, collegial activity, that sort of thing.

Just as an aside, I just published a number of packages. Not huge packages, but enough of them. I will say this, performance seems to have improved dramatically, I'm not waiting the minutes and minutes I was before it seems like for package verification, etc, to take place.

**Comment by zkat** [comment]
FYI there's now an official Discord for .NET that includes a NuGet channel: https://aka.ms/dotnet-discord.

**Comment by anangaur** [comment]
@zkat can you edit the comment to link the NuGet channel?

**Comment by nkolev92** [comment]
The link can't go to the channel, it can only go to the server. 

Can we close this now? @JonDouglas

**Comment by JonDouglas** [comment]
As mentioned by @zkat above, the NuGet team has it's own channel in the https://aka.ms/dotnet-discord where you can publicly join the #nuget channel and interact with team members & the community alike!

I'm closing this issue as we are on Discord.

**Comment by jnm2** [comment]
@nkolev92 

> The link can't go to the channel, it can only go to the server.

It's possible to create channel-specific links. https://www.reddit.com/r/discordapp/comments/6i79zb/link_directly_to_a_specific_channel_on_a_server/

**Comment by CharliePoole** [comment]
If a gitter channel is to be used as a place for devs to congregate, I guess anyone could create it. I find my discussions on builds cover cake, chocolatey and nuget. The first two are on gitter.
