### ISSUE TITLE
VS doesn't support environment variables in repositoryPath (NuGet.exe does)

### ISSUE THREAD

**Issue by dsagar3409** [NuGet/Home#2763]
Hi,

I have installed the latest Nuget Package (version: 3.4.3.855) and it is not able to resolve environment variable mentioned in the “repositoryPath” (Nuget.config). However, NuGet.exe (console application) is able to resolve it. 

The path is mentioned as shown below:
 `<config>
  <add key="repositoryPath" value="%MYNUGETPATH%" />
</config>
`

MYNUGETPATH should resolve to a folder located on my local machine. 

I get the following error when I try to install any package for a project.

"The given path's format is not supported."

**Comment by rrelyea** [comment]
Looks like 3.4 added the support for env vars. Haven't dug into it to see if it was meant to only work in NuGet.exe.
https://github.com/NuGet/NuGet.Client/pull/171
I believe it was done by @TravisTheTechie

**Comment by TravisTheTechie** [comment]
It was targeted for NuGet.exe (for CI), but I thought it would work for the Visual Studio plugin since it appeared to use the same `Settings` object. My first thought would be that Visual Studio can't resolve that environment variable -- but this isn't code I'm that familiar with to be 100% sure that's the case. I just fixed an issue that I needed. Sorry it doesn't work for you though! 😿

**Comment by zhili1208** [comment]
@dsagar3409 just tried it, it works on my machine. so what' s the path for that nuget.config and did you reopen the solution after adding nuget.config?

**Comment by dsagar3409** [comment]
@zhili1208 Could you let me know the Nuget packege version you tried ? 

The config file will be loacted in C:\Users\sadevana\AppData\Roaming\Nuget

I restarted the VS after adding the repository path but it didn't help.

**Comment by zhili1208** [comment]
@dsagar3409 I tried 3.4.3.855, looks like nuget read the repository path, but throws for path format. So what's your project type and what's the path you specified in nuget.config? If it's an relative path, please also share your solution path.

**Comment by dsagar3409** [comment]
@zhili1208 my project is a web application(its just a blank web app) and I am using full path in the environment variable. For example: 
<config> <add key="repositoryPath" value="%MYNUGETPATH%" /> </config>  
The above value should resolve to C:\logs. 

As mentioned above by the developers I think this will be fixed in 3.4.5. So I'm waiting for it.

**Comment by zhili1208** [comment]
@dsagar3409 I didn't see your config value, Can you share you NuGet.Config file? thanks

**Comment by zhili1208** [comment]
@dsagar3409 ping

**Comment by dsagar3409** [comment]
Hi @zhili1208 here in I have attached the config file. 

[NuGet.zip](https://github.com/NuGet/Home/files/277928/NuGet.zip)

**Comment by zhili1208** [comment]
what's the environment variable value? MYNUGETPATH = "C:\logs" ?

**Comment by dsagar3409** [comment]
Yes you are right . 

MYNUGETPATH = "C:\logs"

**Comment by rrelyea** [comment]
appears to have been fixed with that commit from @zhili1208. setting milestone to 3.5rtm, as it will first ship there.
