### ISSUE TITLE
Package Manager UI does not sort packages correctly by ascending/descending order

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#2764]
I verify the issue in nuget version 2.10.791 and 2.11.1.811, also repro this issue now, but not repro before.

Repro steps:
1.       Create a new project(like MVC or others).
2.       Open NuGet UI.
3.       Navigate to Online tab, sort by Ascending or Descending.

Expect: The packages sort by Ascending or Descending.

Actually: The packages doesn’t sort by Ascending or Descending.

**Comment by rohit21agrawal** [comment]
@yishaigalatzer  @maartenba 
This seems to be a server side issue. A simple way to verify it is using this URL : 

https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=concat(Title,Id),Id&$skip=0&$top=2&searchTerm=%27json%27 

You can see from the list of results returned that it's not ordered correctly. Are you aware of any changes that happened on the server side recently that's causing tests to fail in the recent runs?

**Comment by joelverhagen** [comment]
Did some digging here. Seems like we interpret all `$orderby=concat` as sorting by title ([source](https://github.com/NuGet/NuGetGallery/blob/c1c5a98077acff774d5c3ae8e560a8eb32888d8b/src/NuGetGallery/OData/SearchService/SearchAdaptor.cs#L259-L267)).

In addition to the details @rohit21agrawal gave, it looks like the old V2 search service used the ID as the title when sorting by title and a package had no title at all:
https://nuget-prod-0-v2searchwebsite.azurewebsites.net/search/query?q=json&skip=0&take=100&sortBy=title-asc&luceneQuery=false

**Comment by maartenba** [comment]
Concat was disabled in sorting a few months back. It did not play nice with DB load. Sort by title is probably the way to go. Is that fallback to use Id required?

**Comment by rohit21agrawal** [comment]
@maartenba Yes, from what I am seeing, a lot of packages have an empty string for a title, so for those cases we do need to fallback to id.

**Comment by maartenba** [comment]
A first part of the fix is now in the gallery. Second part will be a patch to search service (https://github.com/NuGet/NuGetGallery/issues/3035).

**Comment by maartenba** [comment]
Full fix should be live. Do results look okay now? This one looks correct: https://www.nuget.org/api/v2/Search()?%24filter=IsLatestVersion&%24orderby=concat(Title,Id),Id&%24skip=0&%24top=20&searchTerm=%27json%27

**Comment by rohit21agrawal** [comment]
The URL you provided looks fine, but I tried using the VS 2013 Client, and it still is flaky. Look at this URL for instance:

https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=concat(Title,Id),Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27net45%27&includePrerelease=false

For example, notice how a package named "With" is before a package named "As" .

**Comment by maartenba** [comment]
Weird, looks like a ranking is happening in there as well... Will look into this one.

**Comment by maartenba** [comment]
Looks like the sort field is analyzed in Lucene - will rebuild the index tomorrow morning, that should fix things.

**Comment by maartenba** [comment]
Sorting is now officially fixed. The above URL nicely orders packages. Do note that IE does not render this correctly as it sorts by Date when retrieving the page. In Fiddler, the order is good.

**Comment by rohit21agrawal** [comment]
This does look great now! Thanks @maartenba . Closing this issue now.
