### ISSUE TITLE
Verify using https only works from 2.12

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2765]
When using nuget.org sources, does 2.12 use https by default for everything?
If not, let's explore changing it to https.
We should test network traffic and search source code to understand any http content fetched by nuget.

**Comment by rohit21agrawal** [comment]
Verified the following:
https  works with V2 endpoints.
https is the default.
Adding a http nuget.org source works too.
NuGet 2.x clients do not work with V3 endpoints.

I also did a search for nuget.org on source code, and they are all https based URLs.
