### ISSUE TITLE
nuget restore project.csproj should error if the project isn't using nuget (p.config or p.json)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2766]
https://github.com/NuGet/Home/issues/1496 just fixed this for "nuget update" w/ packages.config.
Let's me sure we have similar fix for restore as well.

And should we change the error if the project would be using project.json, instead of packages.config -- for both nuget restore and nuget update.

**Comment by rrelyea** [comment]
We need this to be done on the project level, but not the solution level. Solutions are ok to call restore on, and not have any usages of NuGet.

If you restore|update a project, w/o p.j or p.c - we error then.
if you restore|update a solution w/o p.j or p.c, we shouldn't error or warn.

**Comment by rrelyea** [comment]
Customer feedback:
It has a major regression: it blows up on solutions that don’t use NuGet, when it used to no-op.

e.g. clone https://github.com/KuduApps/SimpleWebApplication and run nuget restore.

Beta 1 (and earlier):
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.

Beta 2:
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Unable to restore. The project does not contain a project.json or packages.config file.

Make sure you don’t ship that, and please add a test case to cover this scenario.

**Comment by rrelyea** [comment]
Please add several tests...
solution with no projects
solution with 1 project, w/ no nuget
solution with 2 project, 1 w/ no nuget, other with p.j
solution with 2 project, 1 w/ no nuget, other with p.c

**Comment by rrelyea** [comment]
meant to make b2, not b3

**Comment by TimBarham** [comment]
Fix is in 3.5 beta2 and dev.

**Comment by davidebbo** [comment]
Is it on https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe?

**Comment by davidebbo** [comment]
Build on there is `3.5.0.1484`, which is the same as before the fix, so I'm guessing not. @rrelyea, let me know when it gets there and I'll test with it.

**Comment by rrelyea** [comment]
Will do. ETA tomorrow morning.
