### ISSUE TITLE
Move to using https in all places possible in client scenarios

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2767]
When using nuget.org sources, does 3.x use https by default for everything?
If not, let's explore changing it to https.
We should test network traffic and search source code to understand any http content fetched by nuget.

similar to #2765 for 2.12

**Comment by nkolev92** [comment]
Can you please dedup @zivkan

**Comment by kartheekp-ms** [comment]
I think this should be a dedup of @erdembayar issue https://github.com/nuget/client.engineering/issues/1255

**Comment by zivkan** [comment]
Apologies to community members for linking to a private repo, but initial planning has already started here: https://github.com/NuGet/Client.Engineering/issues/1255. We will make things public as appropriate.
