### ISSUE TITLE
portable-net45 imports favored over netstandard1.0

### ISSUE THREAD

**Issue by tannergooding** [NuGet/Home#2768]
Create a C# Portable Class Library and delete the `AssemblyInfo.cs` file.

Modify the `project.json` file to the following:

```
{
  "dependencies": {
    "NETStandard.Library": "1.5.0-rc3-24102-00",
    "System.Linq": "4.1.0-rc3-24102-00"
  },
  "frameworks": {
    "netstandard1.3": {
      "imports": [
        "dotnet5.4",
        "portable-net45"
      ]
    }
  }
}
```

Modify the `Class.cs` file to the following:

```
using System.Linq;

namespace ClassLibrary
{
    public class Class
    {
        public void Test()
        {
            var array = new int[5];
            var first = array.First();
        }
    }
}
```

Build the Project.

**Expected:**
The build should complete succesfully.

**Actual:**
The build fails with the following:
    `ClassLibrary\Class.cs(1,14,1,18): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)`
    `ClassLibrary\Class.cs(10,31,10,36): error CS1061: int[]' does not contain a definition for 'First' and no extension method 'First' accepting a first argument of type 'int[]' could be found (are you missing a using directive or an assembly reference?)`

This appears to be caused by the `"imports": "portable-net45"` clause, which causes the ref to resolve to 'portable-net45+win8+wp8+wpa81`rather than to`netstandard1.0`

**Comment by emgarten** [comment]
@tannergooding what version of NuGet are you using?

This looks like: https://github.com/NuGet/Home/issues/2377 which has been fixed in 3.5.0.

**Comment by tannergooding** [comment]
@emgarten: I am using `v3.4.3`, which is the latest available from https://dist.nuget.org/index.html

Is there a location where I can get v3.5.0 to validate it fixes the issue?

**Comment by emgarten** [comment]
@tannergooding you can find it under the nightly build link on dist.

**Comment by tannergooding** [comment]
I've validated that the `v3.5.0-rc` package resolves the issue. Thanks!
