### ISSUE TITLE
Fix CachingSourceProvider and RestoreArgs based on comments from PR #586

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2769]
Original pull request: https://github.com/NuGet/NuGet.Client/pull/586
Fixing this original bug: https://github.com/dotnet/cli/issues/2510

The changes for the comments in that pull request were too destabilizing for a 3.5 beta fix. Need to go back and make "iteration 2" changes.

Also: Enable the two new tests from that PR, they are currently disabled. The nuget.config file needs to be stripped of all sources that aren't NuGetServer. Also, fix the copy of nuget.config in the team sharepoint so that the sources don't have invalid characters at the end.

**Comment by patrickjamesbarry** [comment]
Is this in a build where I can test it, in dotnet cli?
