### ISSUE TITLE
Pack multiple .net Framework targets in a nuget

### ISSUE THREAD

**Issue by anton-kirschhock** [NuGet/Home#2770]
My project has 2 release targets: 1 for .net 4.5 and one for 4.0.
I was wondering if there is a workflow to follow to create nuget packages of a library which has a .Net 4.0 AND a .Net 4.5 version?
For the moment i have to use the Nuspec to add the 4.0 DLL but was wondering if there is another way to do this?

**Comment by rrelyea** [comment]
There is some tooling available with ASPNET core tooling.
[RC1 tooling](https://blogs.msdn.microsoft.com/webdev/2015/11/18/announcing-asp-net-5-release-candidate-1/) is available today, RC2 should be in the near future.

that document includes:

> Introducing the .NET Platform Standard
> 
> There are several versions of .NET frameworks available, and the introduction of the .NET Core framework further introduces complications for portable class library authors.  To simplify the targeting of .NET frameworks for developers, we are introducing the .NET Platform Standard.  The short definition of the Platform Standard is that it is a single representation for binary compatible .NET Frameworks in packages and project.json instead of representing them as “portable-a+b+c”.  For various versions of the framework, they can be grouped together as “dotnet5.4” with this version of the 
> With this version of ASP.NET 5 templates, the “Class Library (package)” project template will target “dotnet5.4” which has binary compatibility with .NET 4.6, .NET Core 5, and Mono. 
> tools.  This is a work in progress, with the naming convention for these frameworks changing to ‘netstandard1.x’ in a future release.  More details on the plans for the .NET Platform standard roadmap are available on the .NET Roadmap.
> 
> NuGet and dnu both support this new representation of compatible .NET frameworks, and more details and tools will be made available as this new definition of .NET Framework compatibility evolves through our completion of the ASP.NET 5 RTM.
> 
> With this version of ASP.NET 5 templates, the “Class Library (package)” project template will target “dotnet5.4” which has binary compatibility with .NET 4.6, .NET Core 5, and Mono. 

Anyway, I've shown in this project ([Net40AndNet45.zip](https://github.com/NuGet/Home/files/262224/Net40AndNet45.zip)) how to use xproj and project.json to target 4.0 and 4.5.
The build output will be a .nupkg with appropriate artifacts inside.

Hope that helps.

**Comment by anton-kirschhock** [comment]
How about the "Legacy" .net projects like csproj?
The library is written with intention to be compatible with older projects we have running.
