### ISSUE TITLE
Multi-trageting basic class library with VS2015

### ISSUE THREAD

**Issue by gzak** [NuGet/Home#2773]
I have a very barebones class library, and here's its project.json file (it's just a data model with very basic types and so doesn't need any other dependencies):

```
{
  "version": "1.0.0",
  "description": "My.Models",
  "authors": [ "asdf" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "frameworks": {
    "dnxcore50": {
      "dependencies": {
        "System.Runtime": "4.0.20-*"
      }
    },
    "net451": {
      "frameworkAssemblies": {
        "mscorlib": ""
      }
    }
  }
}
```

I've checked the box in the xproj's Build settings to include output on build.

I also have a separate solution with a traditional csproj project inside targeting .net 451 (framework assemblies), and when I add a dependency on the My.Models package in the csproj I get the following error:

```
Could not install package 'System.Runtime 4.0.20'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

But why is it trying to install System.Runtime? That's only for the dnxcore50 target, for the .net451 target it's supposed to be using mscorlib instead. What am I doing wrong here? My.Models is as basic a class library as it gets...

**Comment by gzak** [comment]
Alternative solution: what's the minimal package I can add to the root-level "dependency" section such that it'll work in both targets and pull in the fewest dependencies?

**Comment by gzak** [comment]
Another interesting observation is that when I refer to My.Models from a different xproj project that's within the same solution as the My.Models xproj, then toggling the target in the IDE from .net451 to dnxcore50 makes the basic types (like `int` and `string`) resolve as you might expect: when you press F12 while targeting .net451, it navigates to mscorlib, and when you press F12 while targeting dnxcore50, it navigates to System.Runtime.

So the compiler appears to see the structure fine, just when I create the package and consume it from a pre-.netcore solution I get a problem.

**Comment by Eilon** [comment]
I recommend checking out .NET Core RC2, which was released yesterday. See the various announcements and links here: https://github.com/aspnet/Announcements/issues/177

This has become a lot simpler in .NET Core RC2, so there's probably not much point in working with RC1-era features and behaviors.

**Comment by gzak** [comment]
I've upgraded to RC2, now I have a different error in my csproj. Here's the new version of the project.json file for My.Models:

```
{
  "version": "1.1.0-beta2",
  "description": "My.Models",
  "authors": [ "asdf" ],

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```

And the error message in my csproj is:

```
Attempting to resolve dependency 'NETStandard.Library (≥ 1.5.0-rc2-24027)'.
'NETStandard.Library' already has a dependency defined for 'Microsoft.NETCore.Platforms'.
```

**Comment by gzak** [comment]
Moved the issue to here: https://github.com/dotnet/cli/issues/3206
