### ISSUE TITLE
Nuget.exe update -self includes pre-release versions by default

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#2775]
Nuget.exe update -self should have the option to specify whether we want to update it to a pre-release version or not.

Additionally, we might even consider the option of being able to specify the source from which to pick up Nuget.CommandLine in addition to specifying the -PreRelease option.

While the nuget.exe update command does allow the -PreRelease option, we ignore the option and pass it as true when -Self option is set:

IPackageRepository packageRepository = _repositoryFactory.CreateRepository(NuGetConstants.V2FeedUrl);
            IPackage package = packageRepository.GetUpdates(
                new [] { new PackageName(NuGetCommandLinePackageId, version) },
                includePrerelease: true, 
                includeAllVersions: false, 
                targetFrameworks: null,
                versionConstraints: null).FirstOrDefault();

**Comment by alainbryden** [comment]
NuGet update -self updated to pre-release package 3.4.4-rtm-final today and is no longer working on my build machine, so +1 for this.

**Comment by rohit21agrawal** [comment]
@alainbryden 3.4.4 is actually the latest available rtm version of nuget

**Comment by alainbryden** [comment]
Shows up as a prerelease here: https://www.nuget.org/packages/NuGet.CommandLine.XPlat/3.4.4-rtm-final
With 3.4.3 listed as the latest stable.
Maybe I'm misinterpreting that.

**Comment by cyanite** [comment]
When is NuGet update -self going to update past 3.5? It's really annoying that there is no way to get newer versions in an automatic fashion. Also, if I manually download 4.0.0, it doesn't auto update past that version either.

**Comment by knocte** [comment]
Not having a way to specify a specific version when using `-self` is really suboptimal. Today, my CI builds started breaking because nuget decided to update to version 4.3.0-preview3-4168, which seems to bring some MSBuild version detection which is broken.

**Comment by andmos** [comment]
Got the same case as @knocte now. A way to pick latest stable with a override flag for prerelease would be nice.

**Comment by knocte** [comment]
@andmos in case it's useful to you, I'm now using two target files from here (https://github.com/kzu/NuGet.Restore) which make the build of the solution download nuget from here (https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) which is version 4.1.0.2450 and works for me in Ubuntu Linux 16.04 (with Mono 4.2.1, that comes from the distro).

**Comment by andmos** [comment]
Nice! That might solve some of my problems.

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/897 probably? 
@joelverhagen

**Comment by nkolev92** [comment]
Change set: https://github.com/NuGet/NuGet.Client/commit/180fa576efe2578330c86a4952df253def6e2c1f

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/180fa576efe2578330c86a4952df253def6e2c1f

Note that we don't publish nuget.commandline prerelease versions on nuget.org, so the fact that the prerelease flag is respected, doesn't change much.
