### ISSUE TITLE
VS Package Manager: Uninstall of package uses the wrong line breaks when editing project.json

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2777]
**REPRO**
1. I have v3.5.0.1249 of NuGet Package Manager installed
2. File | New | Project | C# | .NET Core | Console App (.NET Core)
3. Right-click the project node and choose "Manage NuGet Packages"
4. Browse | Select Newtonsoft.Json
5. Install it
6. Uninstall it
7. Open project.json

**RESULT**
The inconsistent line break dialog shows
![image](https://cloud.githubusercontent.com/assets/2523431/15232448/2e681a1c-1856-11e6-89f5-32ce1616fa60.png)

Click "Yes" and you'll see that the bad line breaks were where the dependency was removed:
![image](https://cloud.githubusercontent.com/assets/2523431/15232471/528f775a-1856-11e6-8ca7-18f45f997d6a.png)

**EXPECT**
Use the correct line breaks when editing project.json

**Comment by rrelyea** [comment]
@spadapet - upon looking it up, figured out this build # is a dev branch build. Please confirm that it does or doesn't repro in 3.5.0-beta latest build.

**Comment by emgarten** [comment]
This is all done using json.net as far as I know. I wonder if there's a setting on save that could help normalize the endings.

**Comment by spadapet** [comment]
The OneNote says to use 1249, and I installed the VSIX from the link. So I think I was using the 3.5 beta build.

It says:
![image](https://cloud.githubusercontent.com/assets/2523431/15233141/07831d2a-185b-11e6-9386-f5e10bc5d3c5.png)

**Comment by rrelyea** [comment]
ah yes, you are right. I think I misread that number when I looked it up. please do include the release info when possible to help me distinguish between dev and release-3.5.0-beta
The other release branches are easier. thx.

**Comment by emgarten** [comment]
project.json is no longer used
