### ISSUE TITLE
Evaluate NuGetPackageVerifier errors 

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2779]
I ran ASP.NET's [NuGetPackageVerifier](https://github.com/aspnet/DnxTools/tree/dev/src/NuGetPackageVerifier) against NuGet packages and got a variety of errors:

`... missing the '[assembly: AssemblyMetadata("CommitHash", "<text>")]' attribute.`
- lib/net45/NuGet.Client.dll
- lib/net45/NuGet.Commands.dll
- lib/net45/NuGet.Common.dll
- lib/net45/NuGet.Configuration.dll
- lib/net45/NuGet.ContentModel.dll
- lib/net45/NuGet.DependencyResolver.Core.dll
- lib/net45/NuGet.DependencyResolver.dll
- lib/net45/NuGet.Frameworks.dll
- lib/net45/NuGet.Indexing.dll
- lib/net45/NuGet.LibraryModel.dll
- lib/net45/NuGet.PackageManagement.dll
- lib/net45/NuGet.Packaging.Core.dll
- lib/net45/NuGet.Packaging.Core.Types.dll
- lib/net45/NuGet.Packaging.dll
- lib/net45/NuGet.ProjectManagement.dll
- lib/net45/NuGet.ProjectModel.dll
- lib/net45/NuGet.Protocol.Core.Types.dll
- lib/net45/NuGet.Protocol.Core.v2.dll
- lib/net45/NuGet.Protocol.Core.v3.dll
- lib/net45/NuGet.Protocol.VisualStudio.dll
- lib/net45/NuGet.Repositories.dll
- lib/net45/NuGet.Resolver.dll
- lib/net45/NuGet.RuntimeModel.dll
- lib/net45/NuGet.Shared.dll
- lib/net45/NuGet.Versioning.dll
- lib/net46/NuGet.CommandLine.XPlat.exe
- tools/NuGet.exe

`... missing the 'AssemblyCompany' attribute.`
- lib/net45/NuGet.Shared.dll

`... missing the 'AssemblyDescription' attribute.`
- lib/net45/NuGet.Client.dll
- lib/net45/NuGet.Common.dll
- lib/net45/NuGet.ContentModel.dll
- lib/net45/NuGet.DependencyResolver.Core.dll
- lib/net45/NuGet.DependencyResolver.dll
- lib/net45/NuGet.LibraryModel.dll
- lib/net45/NuGet.Packaging.Core.Types.dll
- lib/net45/NuGet.ProjectModel.dll
- lib/net45/NuGet.Repositories.dll
- lib/net45/NuGet.RuntimeModel.dll
- lib/net45/NuGet.Shared.dll

`... missing the '[assembly: NeutralResourcesLanguage("en-us")]' attribute.`
- lib/net45/NuGet.Shared.dll

`... missing the '[assembly: AssemblyMetadata("Serviceable", "True")]' attribute`
- lib/net45/NuGet.Client.dll
- lib/net45/NuGet.Commands.dll
- lib/net45/NuGet.Common.dll
- lib/net45/NuGet.Configuration.dll
- lib/net45/NuGet.ContentModel.dll
- lib/net45/NuGet.DependencyResolver.Core.dll
- lib/net45/NuGet.DependencyResolver.dll
- lib/net45/NuGet.Frameworks.dll
- lib/net45/NuGet.Indexing.dll
- lib/net45/NuGet.LibraryModel.dll
- lib/net45/NuGet.PackageManagement.dll
- lib/net45/NuGet.Packaging.Core.dll
- lib/net45/NuGet.Packaging.Core.Types.dll
- lib/net45/NuGet.Packaging.dll
- lib/net45/NuGet.ProjectManagement.dll
- lib/net45/NuGet.ProjectModel.dll
- lib/net45/NuGet.Protocol.Core.Types.dll
- lib/net45/NuGet.Protocol.Core.v2.dll
- lib/net45/NuGet.Protocol.Core.v3.dll
- lib/net45/NuGet.Protocol.VisualStudio.dll
- lib/net45/NuGet.Repositories.dll
- lib/net45/NuGet.Resolver.dll
- lib/net45/NuGet.RuntimeModel.dll
- lib/net45/NuGet.Shared.dll
- lib/net45/NuGet.Versioning.dll
- lib/net46/NuGet.CommandLine.XPlat.exe
- tools/NuGet.exe

`... doesn't have a corresponding XML document file.`
- lib/net45/NuGet.Shared.dll
- lib/netstandard1.3/NuGet.Shared.dll

`... references the wrong Json.NET version. Current version '6.0.4'; Expected version '8.0.2'.`

(We probably can ignore this one)
- NuGet.ProjectModel; .NETFramework,Version=v4.5
- NuGet.ProjectModel; .NETStandard,Version=v1.3
- NuGet.Protocol.Core.v3; .NETFramework,Version=v4.5
- NuGet.Protocol.Core.v3; .NETStandard,Version=v1.3
- NuGet.RuntimeModel; .NETFramework,Version=v4.5
- NuGet.RuntimeModel; .NETStandard,Version=v1.3

**Comment by joelverhagen** [comment]
Part of resolving this issue should be integrating this verification into the CI.

**Comment by joelverhagen** [comment]
I have a fork of the tool which works well on NuGet packages:
https://github.com/joelverhagen/DnxTools/tree/jver/nuget

**Comment by rrelyea** [comment]
@joelverhagen - Let me know if any of this looks like a showstopper to you for 3.4.4, otherwise, 3.4.5. thx.

**Comment by rrelyea** [comment]
@TimBarham  - please investigate fixing these in dev and 3.4.5 branches.
Some may not be slam dunks, after looking into some of these, let us know if some look untenable, or a ton of work.

**Comment by rrelyea** [comment]
not asking for you to integrate into CI yet...unless that is easily in your baliwick

**Comment by rrelyea** [comment]
@TimBarham - can you please update this issue as appropriate?
was it fixed in dev? partially?
Changing to 3.5 rc

**Comment by TimBarham** [comment]
Partially fixed in dev. Remaining piece is the CommitHash meta data, which I have a possible fix for but need to verify non-Windows scenarios. Will look at that tomorrow.

**Comment by TimBarham** [comment]
I ran out of time to resolve the CommitHash piece. @emgarten has an idea for a solution. I'll create a new issue for that piece.
