### ISSUE TITLE
Shared packages are automatically deleted during uninstall (repositoryPath)

### ISSUE THREAD

**Issue by InteXX** [NuGet/Home#2780]
Currently the user has no control over whether packages under the `repositoryPath`-specified folder are deleted during `Uninstall-Package`. This means that other solutions using those now-deleted packages will have to either download them anew or retrieve them from cache.

I propose a new setting to exist alongside `repositoryPath`, to allow for package persistence upon uninstall. The default should be `Delete`, for backward compatibility.

I've discussed the issue [here](http://stackoverflow.com/questions/37106930).

**Comment by yishaigalatzer** [comment]
Thanks for cross posting! We will take a look triage and prioritize shortly

**Comment by rrelyea** [comment]
From link, sounds like this used to be ref counted using repositories.config in v2.x of the client (VS2013 and before.)

**Comment by rrelyea** [comment]
See issue #55 and #1097

**Comment by emgarten** [comment]
ref counting for packages is no longer supported as of 3.0.0
