### ISSUE TITLE
Update NuGet from command line

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2781]
_From @Kanimozhi12 on May 13, 2016 10:32_

Hi,

I have installed NuGet to a particular folder from command line by using following command.
install "Packagename"  -Version "version"  -Source "source"  -o "output directory".The package has been installed successfully . Now i need to update the packages in this folder for this i have used the following command
Update "Pacakge name"  -Source "source"  -RepositoryPath "directory in which previous packages are installed". But am unable to update since iam not having any packages.config or solution file. it shows the following message.
No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe.

SO how can i update packages without packages.config or solution folder

_Copied from original issue: NuGet/NuGetGallery#3023_

**Comment by rrelyea** [comment]
@kanimozhi12 - after you do:
1) nuget.exe install "PackageName" -version "1.0.0.0" -source source -o c:\packages
At a later date, to ensure you have the latest version, you could:
2) nuget.exe install "PackageName" -source source -o c:\packages
It will grab the latest version.
