### ISSUE TITLE
Unable to restore packages in web SITE project using NuGet 3 restore packages with whole solution (commandline)

### ISSUE THREAD

**Issue by IanGrainger** [NuGet/Home#2783]
Hi, because the path to a web _site_ project in the solution file looks like: 'http://localhost:1234', trying to run NuGet3's package restore on the whole solution results in an: `the given path's format is not supported` error.

It seems because NuGet tries to include the web URL rather than the path to the files on disk, which is not where the package.config resides (and is also invalid).

It works if you run restore on the web site project itself.

(This is preventing us from using NuGet3 properly)

**Comment by zhili1208** [comment]
Did some investigation on this, it repros in nuget 2.8.6 and nuget 3.5-beta. The issue here is nuget always read "relative path" from "Microsoft.Build.Construction.SolutionFile" type, for this case, that path will return "http://localhost:1234". looks like a msbuild bug

**Comment by IanGrainger** [comment]
Awesome clarifications! I'm not sure how old the version of NuGet2 on our build server is - does this mean something changed a while ago in msbuild and none noticed? Or that it was broken in that release of NuGet so should be fixable inside NuGet itself?

**Comment by rrelyea** [comment]
Thanks for the report. We just want to understand the severity of the issue. Understanding that it has been broken in 2.8.6 - 3.4.3 is important information for us to understand when determining how to address.

**Comment by rrelyea** [comment]
as discussed during standup, please consult with bill next door.

**Comment by rrelyea** [comment]
You said that you filed an MsBuild bug. Please update the info in this issue...

**Comment by zhili1208** [comment]
https://github.com/Microsoft/msbuild/issues/626
