### ISSUE TITLE
NuGet.exe push - timeout parameter doesn't work 

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2785]
@prestonj wrote in https://github.com/NuGet/NuGetGallery/issues/1094#issuecomment-219099916: 
I'm also having this problem but the suggestion for adding the Timeout switch from @maartenba did not fix the issue for me. Seems there is another timeout on the HTTP PUT request that hits after 100 seconds. My command line is basically:

C:\test>nuget push -ApiKey xxx -Timeout 120000 -Source http://nuget.org -Verbosity Detailed mything.nupkg

The output is:
Pushing mything.nupkg to 'http://nuget.org'...
PUT http://nuget.org/api/v2/package/
PUT http://nuget.org/api/v2/package/
PUT http://nuget.org/api/v2/package/
System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The HTTP request to 'PUT http://nuget.org/api/v2/package/' has timed out after 100000ms.
at NuGet.CommandLine.PushCommand.d__16.MoveNext()
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at NuGet.CommandLine.Command.Execute()
at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
---> (Inner Exception #0) System.TimeoutException: The HTTP request to 'PUT http://nuget.org/api/v2/package/' has timed out after 100000ms.
at NuGet.CommandLine.PushCommand.d__16.MoveNext()<---

I'm using nuget.exe version 3.4.3.855

**Comment by skofman1** [comment]
https://github.com/NuGet/NuGetGallery/issues/1094#issuecomment-219099916

**Comment by yishaigalatzer** [comment]
The fix here is to move to an async stream. We did a similar fix in `httpsource` to allow downloading very large packages. 

You will need to also add a timeout mechanism for when the stream "hangs" and bits no longer transmit, because async streams lack this feature.

CC @spadapet @joelverhagen

**Comment by EgorBo** [comment]
Does the latest stable nuget 3.4.4 contain this fix? Because it doesn't work for me. It keeps saying me "has timed out after 100000ms." (for -Timeout 2147483). It used to work in nuget 2.x for the same package on the same network

**Comment by joelverhagen** [comment]
Nope, 3.4.4 does not have this fix. Switch to version 3.5.0-beta2 of nuget.exe and the fix should be present:
https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe

**Comment by EgorBo** [comment]
@joelverhagen thank you! 3.5.0-beta2 works for my case.

**Comment by jogerh** [comment]
NuGet Version: 3.5.0.1737 seems to miss this fix, whereas NuGet Version: 3.5.0.1520 seems to work. Is   33a3740 removed from the later builds, or is there a regression?

**Comment by joelverhagen** [comment]
Yes, this looks like a regression. I'll take a look.

**Comment by jogerh** [comment]
Thank you @joelverhagen. I am impressed.
