### ISSUE TITLE
First open of .sln will claim that .NETStandard references can't be resolved, even though they can

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2786]
I used the latest 3.5 beta package manager extension

REPRO:
1. In VS 2015 Update 2: File | New | Project | .NET Core Class Library
2. Close solution
3. Clear all nuget caches by running: nuget.exe locals -clear all
4. Reopen that solution in VS

RESULT:
Package restore occurs, it succeeds. However, the solution explorer shows errors:
![image](https://cloud.githubusercontent.com/assets/2523431/15263673/fafd275a-1920-11e6-84e3-b4a9c568e076.png)

And opening up Class1.cs shows many errors since the references can't be resolved:
![image](https://cloud.githubusercontent.com/assets/2523431/15263684/0c93316c-1921-11e6-91d1-e3d8fd36c658.png)

NOTE:
Building works fine. Reopening the solution again will work fine. It's just this first restore with a clean nuget cache that fails to resolve any references.

**Comment by rrelyea** [comment]
Talk to ASP.NET team as they own the restore that runs on solution open.

**Comment by spadapet** [comment]
Another issue was logged: https://github.com/dotnet/cli/issues/3112
@rrelyea, this one can be resolved as dupe
