### ISSUE TITLE
More helpful error when installing a package targeting the wrong framework via VS UI 

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#2789]
E.g. installing a package which only targets net46 to a project targeting net452 will yield the following error.
![image](https://cloud.githubusercontent.com/assets/14225979/15264806/7163242a-192c-11e6-91df-666158287a75.png)

Version 3.5.0-beta, VS 2015.2

**Comment by rrelyea** [comment]
Some of these errors get put in output
