### ISSUE TITLE
Functional test failures on GetProject

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#279]
1. ProjectNameReturnsUniqueName fails

Looks like 3 projects ProjectA under Folder1, ProjectB under Folder1 and ProjectA at solution level are created. And,(Get-Project -All | Select-Object -ExpandProperty ProjectName) returns the same project name for both the 'ProjectA's

2. GetProjectCommandWithWildCardsWorksWithProjectHavingTheSameName

**Comment by danliu** [comment]
reassign to Deepak as he's going to address this in a full story.
