### ISSUE TITLE
Insert the real NuGet icon in VS context menus

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#2790]
Currently we have the following:
![image](https://cloud.githubusercontent.com/assets/14225979/15264822/bda2fcfc-192c-11e6-8f82-f64bc495b24d.png)

it would be a sharper experience if this generic package icon were replaced with the actual NuGet icon (even if a black outline representation of it)

**Comment by mishra14** [comment]
closing due to lack of customer traction.
