### ISSUE TITLE
Consolidate tab showing packages from non-selected feed

### ISSUE THREAD

**Issue by M-Zuber** [NuGet/Home#2791]
When opening the NuGet view for solution in VS2015.2 it will show packages from every connected feed non-regardless of what feed is selected in the package source dropdown.
This alone is simply a visual bug, **_but_** it creates a bug that you can't actually update the package until the correct feed is selected in the dropdown.

**Comment by yishaigalatzer** [comment]
Hey מרדכי

This is by design. The consolidate tab behaves the same as the installed tab. It shows all the installed packages, with a filter for packages that have multiple versions installed in the solution.

You do have to pick a feed to install the package from **OR** you the "all" source.

**Comment by M-Zuber** [comment]
Just to make sure I understand:

On the installed/update/consolidate tabs the dropdown is only to tell Nuget what feed to hit when installing/updating ect. and not what to display.
**But** when I am browsing for new packages then the dropdown also affects the display.

**Comment by yishaigalatzer** [comment]
very close, updates tab behaves like installed/consolidated rather than browse.

**Comment by M-Zuber** [comment]
TIL :grinning:
