### ISSUE TITLE
Package restore should inform users that 'runtimes' is not useful on a library

### ISSUE THREAD

**Issue by billwert** [NuGet/Home#2797]
I have a NETStandard1.5 library in which I accidentally (bad copy/paste) added a runtimes tag. This gave me this error:
    System.Security.Cryptography.Algorithms 4.2.0-rc3-24113-00 provides a compile-time reference assembly for System.Security.Cryptography.Algorithms on .NETStandard,Version=v1.5, but there is no run-time assembly compatible with win7-x64.
    One or more packages are incompatible with .NETStandard,Version=v1.5 (win7-x64).

Which makes sense: there isn't an agnostic version of that library it could include.

It would be nice if Nuget would properly identify that adding 'runtimes' to a library is the wrong thing to do.

**Comment by yishaigalatzer** [comment]
Thanks Bill! 

This is going away in the next release. So I don't think there is a point to fix it.
