### ISSUE TITLE
WebSite project from IIS fails with illegal characters in path

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2798]
@MosheL
From: https://github.com/NuGet/Home/issues/2601
1. web project, c:\inetpub\matimim on this error message
2. solution is on MyDocs, so in my machine it's have a hebrew name (E:\המסמכים שלי)
3. Install-Package : An error occurred while writing file 'e:\inetpub\matimim\packages.config': Failed to write packages.config as XML file 'e:\inetpub\matimim\packages.config'. Error: 'Illegal characters in path.'.
   the path is correct, tested via copy/paste to CMD (start e:....).

Visual studio 2015 u1 on 3.4.x I have the main problem. I was installed file from github - NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b.3.4.4.870.vsix. this file has the new error message..
Tried to install 3.3, installation failed.
I do not know what the specific version I was used before, but it works on these projects and still working on my other Machine on Web projects with similar configuration (solution in MyDocs, website in IIS folders))

**Comment by MosheL** [comment]
on my work machine threre is NuGet 3.3.0 (VS 2015.1), works with no problem with similar configuration.

**Comment by MosheL** [comment]
and  "main problem" is bug #2601

**Comment by alpaix** [comment]
@MosheL Can you share your project/solution? Can be a minimal web site project where this issue repros.

**Comment by MosheL** [comment]
Any blank  IIS web site.
create a website on IIS
Run VS  as admin, open website from IIS, open, save solution and try to use NuGet...

**Comment by alpaix** [comment]
Okay thanks for the details. 
What is the project name you see in a tree: `http://matimim.home.a7.org/` or `matimim.home.a7.org`?

**Comment by MosheL** [comment]
matimim.home.a7.org.slm

with http is full address...

**Comment by alpaix** [comment]
I see. In #2601 you shared the output:

> PM> Install-Package Microsoft.AspNet.Mvc -Version 5.2.3
> Attempting to gather dependency information for package 'Microsoft.AspNet.Mvc.5.2.3' with respect to project **'http://matimim.home.a7.org/'**, targeting '.NETFramework,Version=v4.6.1'

where **http://matimim.home.a7.org** is a project name. My theory is NuGet attempts to restore using full url for local file path.

I'll try to get a repro myself tomorrow.

**Comment by MosheL** [comment]
just to note, I do not named the project. VS do it from IIS  first Host header if exists, with some changes (localhost:83 will be localhost83.sln).

**Comment by alpaix** [comment]
Couldn't repro the issue following steps provided by @MosheL .

Used a lab box having installed:
- Win10 Enterprise (with Hebrew display language)
- Visual Studio 2015 Update 2
- NuGet Package Manager 3.4.4 b870

Created new IIS web site and opened it in VS.
Successfully installed NuGet packages:

> PM> Install-Package Microsoft.AspNet.Mvc -Version 5.2.3
> Attempting to gather dependency information for package 'Microsoft.AspNet.Mvc.5.2.3' with respect to project 'http://nuget456.contoso.com/', targeting '.NETFramework,Version=v4.5.2'
> Attempting to resolve dependencies for package 'Microsoft.AspNet.Mvc.5.2.3' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'Microsoft.AspNet.Mvc.5.2.3'
> Resolved actions to install package 'Microsoft.AspNet.Mvc.5.2.3'
> Adding package 'Microsoft.AspNet.Razor.3.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.Razor.3.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.Razor.3.2.3' to 'packages.config'
> Successfully installed 'Microsoft.AspNet.Razor 3.2.3' to http://nuget456.contoso.com/
> Adding package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.Web.Infrastructure.1.0.0' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.Web.Infrastructure.1.0.0' to 'packages.config'
> Successfully installed 'Microsoft.Web.Infrastructure 1.0.0' to http://nuget456.contoso.com/
> Adding package 'Microsoft.AspNet.WebPages.3.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.WebPages.3.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.WebPages.3.2.3' to 'packages.config'
> Successfully installed 'Microsoft.AspNet.WebPages 3.2.3' to http://nuget456.contoso.com/
> Adding package 'Microsoft.AspNet.Mvc.5.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.Mvc.5.2.3' to folder 'C:\המסמכים שלו\תיקיה חדשה\nuget456.contoso.com\packages'
> Added package 'Microsoft.AspNet.Mvc.5.2.3' to 'packages.config'
> Successfully installed 'Microsoft.AspNet.Mvc 5.2.3' to http://nuget456.contoso.com/

**Comment by MosheL** [comment]
Hi.
1.   I am using U1 (tried to update to U2, install fail sliently)
1. the project foder is  `E:\inetpub\matimim\www\packages.config`. it not on the solution folder, but in IIS's folder. maybe can change something ?

Thanks !

**Comment by rrelyea** [comment]
Missing 3.4.5 as we haven't been able to repro.

**Comment by MosheL** [comment]
update: upgraded to  3.4.4. from 3/6,   works on ConsoleApp, crashed on one of my  IIS projects. on other one the same problem.

**Comment by MosheL** [comment]
update: installed 3.5.0-rc1, VS crashed.

**Comment by MosheL** [comment]
@alpaix 
I was found it after all: the solution folder need to be the website folder.  on my config the project was in MyDocs but the website was in IIS  `inetpub` folder.

I can attach a debugger to VS ?

**Comment by MosheL** [comment]
Update again: Reinstall entire Visual Studio u3.  still not working,

**Comment by MosheL** [comment]
Update again: same machine, other User Account - works.

**Comment by MosheL** [comment]
problem found: Hebrew Date on the machine. switched to Gregorian date, and installed.


![image](https://cloud.githubusercontent.com/assets/2265043/20984973/194eda5c-bccb-11e6-8804-9285df5cad83.png)

**Comment by emgarten** [comment]
The date issue has been fixed.
