### ISSUE TITLE
NuGet installtion keep on asking for credentials

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/Home#2799]
HI ,

I have updated to latest NuGet package manager 3.4.3 . I have tried to install NuGet from my private server, how ever it asking credentials to access my NuGet Server even though the server is free from any kind of authentications .how to avoid this authentication window?

**Comment by rrelyea** [comment]
Can you please try version 3.3 on the same machine, and let us know if you hit the same problem. If so, we'll work with you to figure out the potential causes of the problem.

**Comment by Kanimozhi12** [comment]
I dint face this issue with 3.3 , this occurs only when i upgraded to 3.4.3

**Comment by emgarten** [comment]
Add the credentials to your nuget.config to avoid getting prompted.
