### ISSUE TITLE
Error: The package is invalid and cannot be uploaded. One or more files, such as '.rels' have a date in the future.

### ISSUE THREAD

**Issue by neurospeech** [NuGet/Home#2802]
This started only from today. 

I am in India, and I regularly publish NuGet Packages, till today everything was smooth. From today I started getting this error **The package is invalid and cannot be uploaded. One or more files, such as '.rels' have a date in the future.**.

I have tried both, command line publish as well as upload from the nuget.org website, but I get same error.

My clock is set to Indian Standard Time which is GMT+5.30, if I change my Timezone to GMT-6 CST, package can be uploaded successfully without any error. Your validation must consider UTC instead of localized timezone.

**Comment by maartenba** [comment]
@neurospeech We are looking into this.

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#3032
