### ISSUE TITLE
NuGet build task should complain if project.lock.json exists, but not XXX.nuget.props and XXX.nuget.targets

### ISSUE THREAD

**Issue by jasonmalinowski** [NuGet/Home#2803]
[This is migrated from dotnet/roslyn#6873 on behalf of @davkean]

If you check-in a project's project.lock.json but not the appropriate XXX.nuget.props/XXX.nuget.targets the NuGet build task does not complain that they are missing when you pull down the project on a build machine.

This leads to hard to diagnose build errors, such as this: https://gist.github.com/davkean/d19c5b909aa265357bf1. Here, I'm expecting a particular target to generate some code, which other parts of my project use. While this project happens to complain loudly when the targets files are missing, others may not and could silently build incorrectly.

Instead, the NuGet build task should verify that the appropriate props/targets exists if the project is expected to be in a restored state.

**Comment by nkolev92** [comment]
This is redundant now. 

CLosing.
