### ISSUE TITLE
TFS issue: Packages folder still exist in TFS after uninstalling the package.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#2804]
NuGet Version: dev branch
Repro Step:
1. open a Console App and bound the solution to TFS.
2. Install newtonsoft.json and check in to TFS
3. uninstall newtonsoft.json and check in to TFS

Expect: the package and all related folders are deleted in TFS.
Actual: all files are deleted but all folders still exist.

**Comment by emgarten** [comment]
Closing due to lack of feedback for packages.config
