### ISSUE TITLE
Pack should result in lowercase package file name

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2806]
This is a follow-up step for https://github.com/NuGet/Home/issues/2522.

Currently `nuget pack` results in `{original ID}.{version}.nupkg`, i.e. `Newtonsoft.Json.8.0.3.nupkg`. This should be `newtonsoft.json.8.0.3.nupkg`.

This part file name is more visible to the customer than paths in a local source, i.e. the contents of the global packages folder or `nuget push` to a local folder. However this emphasizes the case-insensitive and provides a more consistent end-to-end experience.

As part of this work, all other `nuget.exe` modes should be investigated for similar inconsistencies.

@toddm @emgarten

**Comment by rrelyea** [comment]
Would like to talk in person with @joelverhagen about this. Sounds like it will break scripts on case sensitive OSes, with no major gain, right?

**Comment by joelverhagen** [comment]
Closing. Offline discussion decided this is "pain with no gain".
