### ISSUE TITLE
symbols packages should not ever be used in install or update

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#2807]
update-package command in Package Manager Console works differently for symbols packages when used with or without -Version parameter. With version parameter, it fails to update package where as with -Version parameter it successfully update the same version.

repro steps: (make sure you only has My.Package.Id.1.0.0.symbols.nupkg in your local folder)
PM>update-package My.Package.Id -source d:\src\temp\packages -includeprerelease -version 2.0.0

will result into error : not able to find this package with this id.

PM>update-package My.Package.Id -source d:\src\temp\packages -includeprerelease

works fine and able to update My.Package to 2.0.0

**Comment by emgarten** [comment]
Local folders will now check for .symbols.nupkg in file names and exclude those packages.

NuGet/NuGet.Client@cea464c27a439406c669643e4a6901b56a67a337
