### ISSUE TITLE
C++ Package with .targets file not merging into vcxproj file

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#281]
From the XBox team:

-       Open the XboxSample in VS 2012 and point your local Nuget client to the NugetPackage directory you just downloaded.
-       Install the NugetPackage for the Xbox Social Sample.
-       Notice that the installation succeeds.
o    A packages.config is added to the solution with <package id="XboxLiveSDK" version="1.0.0.0" />
o    The package itself is added in the sample project folder under “packages-> XboxLiveSDK.1.0.0.0”
 
However, the XboxLiveSDK.targets file is never added to the Social110.vcxproj file.

**Comment by RanjiniM** [comment]
This works with new NuGet bits and XBOX team confirmed that.
