### ISSUE TITLE
NuGet -ConfigFile option supersedes %ProgramData% config file

### ISSUE THREAD

**Issue by lmgomes** [NuGet/Home#2812]
According to the documentation, you should be able to specify a custom config file while still using any additional config files that are located in %ProgramData%\Nuget\Config. However, that doesn't seem to be the case. If I specify a custom config file, any config file I have in %ProgramData% is unused:

C:\> nuget.exe sources

(output includes sources specified in my %ProgramData%\Nuget\Config\A.config)

C:\> nuget.exe sources -ConfigFile B.config

(output includes sources specified in B.config but not in ProgramData%\Nuget\Config\A.config)

As a matter of fact, if I specify the -ConfigFile option, I can even put xml errors in A.config and it doesn't complain at all.

Has anyone else run into this?

**Comment by zhili1208** [comment]
this behavior is by design, we should update the document. if you use -ConfigFile, nuget will only use the specified nuget.config. In your case, you can just put B.config and nuget.exe into the same folder. Then it will read B.config and machine wide config A.config. 

For the xml error issue, what's your nuget.exe version? I just tried 3.5-beta, it complains xml error.

**Comment by lmgomes** [comment]
Looks like this was a change in behavior between 3.3 and 3.4.

I had been using version 3.3.0.212, specifying -ConfigFile, and it was including the %ProgramData% config. I'm now using 3.4.3.855 and the behavior is how you describe it.

By the way, [this is the documentation](https://docs.nuget.org/consume/nuget-config-file) that needs to be updated:

```
Starting with NuGet 2.6, with the new config extensibility point, a new location for machine wide
config files located under directory %ProgramData%\NuGet\Config are read after the user specific
config file. So, the above list now becomes:

- c:\a\b\c\.nuget\nuget.config
- c:\a\b\c\nuget.config
- c:\a\b\nuget.config
- c:\a\nuget.config
- c:\nuget.config
- User specific config file, %AppData%\NuGet\nuget.config
- Or the user specified file thru option -ConfigFile
- %ProgramData%\NuGet\Config{IDE}{Version}{SKU}*.config, e.g. %ProgramData%\NuGet\Config\VisualStudio{VSVersion}\Pro\a.config
- %ProgramData%\NuGet\Config{IDE}{Version}*.config
- %ProgramData%\NuGet\Config{IDE}*.config
- %ProgramData%\NuGet\Config*.config

```

Given the current behavior, the failure to report the xml error makes sense. Note that I put the error in A.config, not B.config. So, if specifying the -ConfigFile B.config option causes A.config to be ignored, it makes sense to me that it wouldn't report errors in it.

**Comment by zhili1208** [comment]
Yes, this change is made in 3.4. We should update the documentation.

**Comment by lmgomes** [comment]
Okay, thanks. Also, I tested your workaround a bit and it works, but the custom config file needs to be in the **current directory**, not the nuget.exe directory. But okay, that should work for us too. Thanks!
