### ISSUE TITLE
Feature Request: Lockdown dev systems so only certain "pre-approved" packages can be downloaded

### ISSUE THREAD

**Issue by EdDore** [NuGet/Home#2814]
Basically, this is a request from a large enterprise customer, that asked if there was any way to lock down their developers machines such that they would only allow certain packages or specific feeds. 

They were looking for a feature that would allow them to allow only approved package to be downloaded/installed to their development machines.

**Comment by harikmenon** [comment]
We don't have plans to do this at this time for NuGet.org. Have your customers looked at other package repositories like VSTS Package Management, Artifactory, Nexus etc..that can provide this sort of functionality. They can mirror packages and provide access to only a select few approved feeds/packages. The customer can easily block NuGet.org then. We have seen a number of enterprises do this.
