### ISSUE TITLE
Can not update dependency version using nuget update

### ISSUE THREAD

**Issue by doronshai** [NuGet/Home#2816]
I can not update dependency version using **_"nuget update solution.sln"_**.

I have a dependency to another internal component that I need, and the version is stated specifically as 1.0.0.32 and when i run the update command it claims that there is nothing to do...

I saw that on the Nuget Package Manger Console via the Studio,  i have the option to run **_Update-Package_** and then the packages.config is updated for each dependencies with the latest avaialbe in artifactory. How can I do it without the studio? via Jenkins...

**Comment by rrelyea** [comment]
Sounds right, you should see the same behavior in those 3 cases. What version of Nuget.exe are you using? Does this happen with multiple solutions, or just one of yours?

**Comment by doronshai** [comment]
I tried to do the flow again, this time in a more clean way and it looks like it is working.
but inorder to have the latest dependencies downloaded and updated in the package.config I have to:
- [ ] 1. Execute nuget restore solution.sln
- [ ] 2. Execute nuget update solution.sln
- [ ] 3. Delete all content of packages folder
- [ ] 4. Execute nuget restore solution.sln once again and then the packages folder will have just the latest stuff...
