### ISSUE TITLE
project.json floating versions: is nuget supposed to warn if there's a dependency conflict in this case?

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2820]
I'll work on a clean repro when I get a chance, but I think this is what I just observed on our main solution:

Solution A:
  Project 1:
    dependencies: { PackageX: 0.1.1-\* }
  Project 2:
    dependencies: { PackageY: 0.1.1-\* }

Solution P:
  ProjectY (produces PackageY v0.1.1-pre01):
    dependencies: { PackageX: 0.1.1-pre15 }

The repo has:
PackageX.0.1.1-pre16
PackageX.0.1.1-pre15
PackageY.0.1.1-pre01

So our main solution calls for the latest version of basically everything, and one of the packages in the repo calls for a specific (and not latest) version of another package.

Everything seemed to compile just fine with no warnings, but at runtime we get a loader error on PackageX 0.1.1.15

PackageX v0.1.1.16 is what landed in the bin folder.

Now, in this case we had actually forgotten to rebuild ProjectY after a new PackageX was dropped (and the dependency manually updated in ProjectY). Simply rebuilding ProjectY to create PackageY.0.1.1-pre02 fixed the problem.

Was nuget supposed to warn us in this scenario?

This is with nuget.exe v3.5.0.1240

**Comment by wbradney** [comment]
After creating the repro I noticed this (ordinary) message in the build log:

```
  No way to resolve conflict between "ProjectX, Version=0.1.1.16, Culture=neutral, PublicKeyToken=d21765302d2c3127" and
   "ProjectX, Version=0.1.1.15, Culture=neutral, PublicKeyToken=null". Choosing "ProjectX, Version=0.1.1.16, Culture=neutral, PublicKeyToken=d21765302d2c3127" arbitrarily.
```

So nuget is detecting this situation correctly (I must have missed these messages in our larger build).
Is there a way to make this message a warning or error so that it's more obvious?

**Comment by wbradney** [comment]
Posting the repro now because with RC1 (3.5.0.1737) this solution doesn't build at all. It complains about not being able to resolve _either_ of the floating version references. Did something change between 3.5.0.1520 and 3.5.0.1737 related to floating versions?

[NugetConflictWarning.zip](https://github.com/NuGet/Home/files/420848/NugetConflictWarning.zip)

**Comment by emgarten** [comment]
I am unable to repro this. Try again with VS 2017 15.5 or higher.
