### ISSUE TITLE
Error update Npgsql v3.0 to 3.1

### ISSUE THREAD

**Issue by snessnes** [NuGet/Home#2822]
Error       An error occurred while retrieving package metadata for 'System.Diagnostics.DiagnosticSource.4.0.0-rc2-24027' from source '...EFTest\packages'.         0   

![image](https://cloud.githubusercontent.com/assets/17413819/15412960/a48013b2-1df1-11e6-9ea2-1bbc84f7b777.png)

**Comment by emgarten** [comment]
I am unable to repro this. Try again with VS 2017 15.5 or higher.
