### ISSUE TITLE
disableSourceControlIntegration default value documentation is not clear

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#2823]
The following line in the NuGet docs : https://docs.nuget.org/consume/nuget-config-settings

> section: solution
> key: disableSourceControlIntegration
> 
> Allows you to disable source control integration for the "Packages" folder. This key works at the solution level and hence need to be added to the NuGet.config file present in the $(SolutionDir).nuget directory. Enabling package restore from VS would add the .nuget\nuget.config file automatically. More details here.
> 
> **The default value for this key is true.**

default value being true makes me believe that even if I don't have a  NuGet.config file, or if I haven't explicitly specified the value of this key, I will still get the default value as true. However, this is not the case in our code.

We should either make the documentation more clearer or change the behavior in our code.

**Comment by kraigb** [comment]
This is fixed on https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file#solution-section.
