### ISSUE TITLE
NuGet error when creating project.json PCL with "zero impact projects"

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#2826]
In VS, tools > options > projects & solutions > uncheck "save new projects"
Create a new PCL targeting .NET 4.6 and UWP.

Get a dialog that says "Solution is not opened or not saved. Please ensure you have an open and saved solution."

This comes from NuGet:

`

>   NuGet.PackageManagement.dll!NuGet.PackageManagement.PackagesFolderPathUtility.GetPackagesFolderPath(NuGet.PackageManagement.ISolutionManager solutionManager, NuGet.Configuration.ISettings settings)   Unknown
>     NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.NuGetPackageManager(NuGet.Protocol.Core.Types.ISourceRepositoryProvider sourceRepositoryProvider, NuGet.Configuration.ISettings settings, NuGet.PackageManagement.ISolutionManager solutionManager, NuGet.PackageManagement.IDeleteOnRestartManager deleteOnRestartManager, bool excludeVersion)    Unknown
>     NuGet.VisualStudio.Implementation.dll!NuGet.VisualStudio.VsPackageInstaller.InstallInternalAsync(EnvDTE.Project project, System.Collections.Generic.List<NuGet.Packaging.Core.PackageIdentity> packages, NuGet.Protocol.Core.Types.ISourceRepositoryProvider repoProvider, NuGet.VisualStudio.VSAPIProjectContext projectContext, bool includePrerelease, bool ignoreDependencies, System.Threading.CancellationToken token)    Unknown
> `

**Comment by emgarten** [comment]
For a UWP project there is no solution level packages folder, it looks like the DeleteOnRestartManager should skip this check based on the project type.
