### ISSUE TITLE
Package manager UI doesn't show newly updated version

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#2828]
I was using the test VSIX for 3.4.4.1321, and I have dotnet RC2 and tools installed

REPRO
1. In VS 2015 Update 2: File | New | Project | C# | .NET Core | Class Library
2. Right click the project node: Manage NuGet Packages...
3. Click on Browse tab, click Newtonsoft.Json, install Latest Stable 8.0.3 (not the default)
4. Click on the Updates tab, click Newtonsoft.Json, click Install to get 8.0.4-beta1
5. The UI will clear since everything was updated
6. Click on the Installed tab, click Newtonsoft.Json

RESULT
It says that 8.0.3 is installed. Trying to install 8.0.4 from this UI will still show 8.0.3

EXPECT
Should say 8.0.4-beta is installed

**Comment by rrelyea** [comment]
Appears to happen in 3.4.4 and 3.5.0-beta

Project gets the following warnings:
Warning NU1007  Dependency specified was Newtonsoft.Json >= 8.0.4-beta1 but ended up with Newtonsoft.Json 8.0.3.    CoreClassLib1   F:\nugetExample\CoreClassLib1\project.json  6  
Warning NU1012  Dependency conflict. CoreClassLib1 1.0.0 expected Newtonsoft.Json >= 8.0.4-beta1 but got 8.0.3  CoreClassLib1   F:\nugetExample\CoreClassLib1\project.json  6  
Warning NU1006  Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.    CoreClassLib1   F:\nugetExample\CoreClassLib1\project.lock.json 1

**Comment by rrelyea** [comment]
@jainaashish - would love to understand how we can improve the UI here.

**Comment by jainaashish** [comment]
@rrelyea issue here is, while updating a package, it's not updating project.lock.json file which results in this inconsistency. So there isn't any UI issue rather dotnet restore should be called while updating a package like it's being called for install. I'll look more into it to understand install flow and have the similar flow for update.

**Comment by jainaashish** [comment]
This is actually projectK issue, not nuget. And they already have an opened tfs bug for this to be fixed.

From: Anton Piskunov 
Sent: Wednesday, May 25, 2016 3:36 PM
To: Bill Hiebert 
Cc: Ashish Jain 
Subject: Re: https://github.com/NuGet/Home/issues/2828

It can be fixed on our side or PMS. I opened a bug during signoff and can fix it if it is approved for the.

Thanks,
Anton

On May 25, 2016, at 6:27 PM, Bill Hiebert  wrote:
Anton – this issue sounds like a problem in our project system, not Nuget.  It sounds like updating the version of a Nuget package through the  Nuget UI (which calls us) doesn’t generate a restore. I know we had an issue where changing just the version number of a Nuget package wouldn’t cause a restore. Did you fix that already?

**Comment by jainaashish** [comment]
https://github.com/dotnet/cli/issues/3026
