### ISSUE TITLE
Partial Search Term match is not returned

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#283]
This is in re: this twitter thread: https://twitter.com/sbohlen/status/571267522571468800

Essentially this comes down to the following issue, which (depending on your POV) either merely hamper discoverability or indicate mostly-broken search functionality:
•	Partial matches of search terms names are not considered

Unless you know EXACTLY the package name for which you’re searching, it’s nearly impossible to use search to progressively refine/discover the package(s) you’re seeking.

**Comment by yishaigalatzer** [comment]
moved to gallery https://github.com/NuGet/NuGetGallery/issues/2789

CC @joyhui @johnataylor
