### ISSUE TITLE
repositoryPath working but build failing

### ISSUE THREAD

**Issue by mocsharp** [NuGet/Home#2830]
VS 2015 Update 2
NuGet 3.4.3.855

I have a nuget.config file next to my VS 2015 solution file and I have configured repositoryPath to **External\Packages**. VS downloaded/restored all packages fine but when I expand References, all are displayed with warning icon and build output shows:

> 1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
> 1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "EntityFramework.SqlServer, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

nuget.config
`
    <add key="repositoryPath" value="External\Packages" />`

**Comment by mocsharp** [comment]
It looks like if packages are removed and added back then everything would work again.  Either manually or by running **Update-Package -Reinstall**.

It would be nice if during automatic restore that nuget package manager would automatically update the project file with new paths to the repository path.

**Comment by rrelyea** [comment]
Understand the request, but don't see this work getting done. If we add support to edit repository setting nuget.configs in tools/options, you could imagine VS to help do this.
