### ISSUE TITLE
nuget pack zip file issue between Mono versus Windows

### ISSUE THREAD

**Issue by darrencauthon** [NuGet/Home#2833]
Before I say anything... I should say that I'm not sure this is a Nuget issue.  Perhaps it's a Mono issue?  I'm just starting here, as I've hit a wall.  

I wanted to move a build & deploy process from a manual Visual Studio & command line operation to a single-call Docker container with Mono.  I'm using nuget 3.4.3 on both Linux and Windows.

So I have two processes. I use `nuspec pack X.xsproj` in Windows (with a matching nuspec), but in Linux with Mono I have to use `nuspec pack X.nuspec`.  Despite that slight difference, both produce nupkg files that are identical.  Identical folder structures, DLLs that all work (Mono & VS dlls are a little different, but both work in VS & Linqpad), and XML files that match.  I unzipped both files and they both check out...

<img width="706" alt="nupkg diff" src="https://cloud.githubusercontent.com/assets/148768/15454861/93da4252-2009-11e6-9d1e-4b5b274de400.png">

... but there seems to be some sort of zip structure issue with the Mono call.  The Linux zip file [cannot be used by Visual Studio](https://www.nuget.org/packages/SparkPost/1.6.1), but the Windows one [is fine](https://www.nuget.org/packages/SparkPost/1.6.2).  I use Linqpad as a simple way to demonstrate the issue, but I can tell you that it does not work in Visual Studio as well:

<img width="819" alt="one" src="https://cloud.githubusercontent.com/assets/148768/15454932/503d204e-200b-11e6-8e8c-76621464a410.png">
<img width="827" alt="two" src="https://cloud.githubusercontent.com/assets/148768/15454933/50484cb2-200b-11e6-8190-a7d2290ac7f3.png">

Just as a little more background... I've been making nupkgs since Nuget was brand-new, and I've had Mono-built dlls on nuget.org for years.  I know this has worked in the past, and I believe it can work now. I just haven't done it for a while, and there is something silly that I'm missing.  

I've looked through tickets and have learned of one new idea... re-zipping the contents of the nupkg generated by Mono.  Any other ideas?  Or should I post this ticket somewhere else?

**Comment by darrencauthon** [comment]
Oh, for the record... here is the nuspec file:  https://github.com/SparkPost/csharp-sparkpost/commit/dd42dc7e8cc082c9acacf5a261511571e9d7f59d#diff-97491765f73a35f178a62b19e9d02bb5L20

Since I have to pack the nuspec instead of the project file, I found I had to manually copy the dlls into the appropriate folder in the nupkg.

**Comment by rrelyea** [comment]
Can you please point us towards a copy of a bad nupkg (and perhaps one that is good too)

**Comment by darrencauthon** [comment]
Sure @rrelyea, the good one is SparkPost 1.6.2 (https://www.nuget.org/packages/SparkPost/1.6.2) and the bad one is 1.6.1 (https://www.nuget.org/packages/SparkPost/1.6.1).

**Comment by darrencauthon** [comment]
So I played with this a little bit.

It seems that if I unzip the nupkg, then zip it up again (with zip 3.0, ubuntu apt-get), the nupkg is valid.

So this might be an issue with the way the nupkg is zipped up.  Still investigating.

**Comment by ravensorb** [comment]
I believe the issue is that zip on linux is creating a zip file folder structure that uses / (forward slash) and on windows it is using a \ (backslash) -- visual studio built in zip requires the backslash as I believe that is required for the windows based zip library.

**Comment by darrencauthon** [comment]
I'd love to take a look at this, myself. I'm a programmer, too! :smile:

**Comment by yishaigalatzer** [comment]
This looks a lot like this fix in mono - https://bugzilla.xamarin.com/show_bug.cgi?id=41775

**Comment by darrencauthon** [comment]
It looks like the fix for this may have been applied to mono 11 days ago.  

https://github.com/mono/mono/commit/dfb71501df717bfa587e4458b61cd50b0a85efa2

I'll verify that it fixes this issue, then close the ticket accordingly.  Thanks!

**Comment by tritao** [comment]
Hey, it indeed looks like that commit should deal with this issue. If after testing there are still any problems feel free to reach over so we can deal with them asap in Mono.

**Comment by darrencauthon** [comment]
Sounds good. I haven't had a chance to test, but I'm pretty confident this fix upstream will resolve the matter. (Did I just doom myself?)

I'll reopen if it's not resolved. Thanks for your help and consideration!
