### ISSUE TITLE
Using nuget for to create external package

### ISSUE THREAD

**Issue by patrickjamesbarry** [NuGet/Home#2835]
We have a need to create a zip file that contains a project and all of its dependencies. What I would like to do it still use nuget to treat the packages as separate libraries, yet need the ability to down load the project AND all of its dependencies into a local folder, zip them up in a flat hierarchy, and then provide this artifact to an external vendor.  How can I accomplish this with nuget command line?

**Comment by harikmenon** [comment]
is the zip file that you want to provide to the vendor a nupkg?

**Comment by patrickjamesbarry** [comment]
The end artifact needs to be a zip file, however I know nuget packages are really just a standardized zip file format.  I was really hoping to find something like:

`nuget install myproj -o c:\temp --includeDependencies`
that would download all the nuget packages mentioned above and put them in a temp dir for me to zip.  So the includeDepependencies flag obviously doesn't exist, and I would want to leverage nuget's version resolution logic, when there is more than one version of a dll.

The "home-run solution" would possibly be a command like:
`nuget export myproj -o c:\temp --includeDependencies --format=zip`

I know that is not possible today, but just looking for how to be accomplish this need. Hopefully that demonstrates better, what I am looking for.

**Comment by harikmenon** [comment]
This is probably a better question for stackoverflow, the community might have some good ideas. Here is an idea.

Create or modify nuget.config and change the repository path https://docs.nuget.org/consume/NuGet-Config-Settings to point to a location relative to the folder which you want to zip up (default is packages folder which is within the solution itself)
You can do restore on the commandline (https://docs.nuget.org/consume/package-restore) which will bring down the packages and its dependencies to the repository path you have configured
You should then be able to zip up the folder and its contents using any zip utils and unzip this on any other machine and get this to work.

**Comment by harikmenon** [comment]
Closing this issue since we are not looking into building a feature as you have described in the future at this point. However, we will keep an eye out for more feedback around this.
