### ISSUE TITLE
Can not push symbols nuget package

### ISSUE THREAD

**Issue by chinadragon0515** [NuGet/Home#2837]
Before we use nuget version 2.8.6, and we can use command,
1. nuget.exe setApiKey 8a07038c-1e59-4a3f-9615-01f3a13b651a  
2. nuget.exe push package.nupkg

We can successfully push package to nuget.org and source code to http://www.SymbolSource.org.

Today, when I try the command again, I will get issue to push symbols,
Pushing Microsoft.Restier 0.5.0-beta to the symbol server (http://nuget.gw.symbolsource.org/Public/NuGet)...
Failed to process request. 'Forbidden'.
The remote server returned an error: (403) Forbidden..

Then I download newest stable nuget, 3.4.3.855, 
1. I find it use a new symbol server, https://nuget.smbsrc.net/
1. When I push like 

nuget.exe push package.symbols.nupkg -Source https://nuget.smbsrc.net -ApiKey 8a07038c-1e59-4a3f-9615-01f3a13b651a  

nuget.exe push package.symbols.nupkg -Source https://nuget.smbsrc.net

None of them works, it still requests me to input a ApiKey, and nuget ApiKey does not work.

Then question is,
1. Whether older symbol server is deprecated? And access is revoked?
2. How to get the ApiKey to access new symbol server?
3. Can the symbol package automatically when pushing binary package?
4. For binary push, we still need to specify the -source to url like nuget.org?

thanks.

**Comment by harikmenon** [comment]
Yes, the old symbol server is now deprecated, you should use the new server which is https://nuget.smbsrc.net/. Can you try the following and let us know if it doesnt work. 

nuget.exe setApiKey 8a07038c-1e59-4a3f-9615-01f3a13b651a  

nuget.exe push %packagename% -Source https://nuget.smbsrc.net/. You are missing the trailing forward slash that might cause issues (it does for sure when you specify the symbol server in VS)

Symbol packges should get pushed automatically provided there are available, to the new endpoint when you push a package

For binary push, you need to specify the source going forward. This is a recent breaking change.

**Comment by maartenba** [comment]
I have reset your API key - it is no longer `8a07038c-1e59-4a3f-9615-01f3a13b651a` as the key was disclosed in this GitHub issue. Please **never share this key in public**.

**Comment by harikmenon** [comment]
:), good point. I haven't had my coffee yet.

**Comment by rrelyea** [comment]
@maartenba do you know the answer to his third question? 
If I call "nuget push *.nupkg -source https://www.nuget.org/api/v2" will it take all .symbols.nupkg files and automatically try posting to the symbol server? Or did nuget.org help broker the conversation with the symbol server?

**Comment by chinadragon0515** [comment]
I figure out this one works for me with nugget 3.4.3,

nuget.exe push Microsoft.Restier.0.5.0-beta.symbols.nupkg 8a07038c-1e59-4a3f-9615-xxxxxxxxx  -Source https://nuget.smbsrc.net

set the apikey first and the run push does not work for me.
specify -apikey options does not work for me neither.

I close the issue as I have a way to work, but I prefer we can update nugget help message if this is the only work command.

**Comment by harikmenon** [comment]
This should work, we will take a look at this. Our docs says we suppor this  https://docs.nuget.org/create/creating-and-publishing-a-symbol-package

**Comment by maartenba** [comment]
@rrelyea The client used to have some logic that would change the push URL. I believe it checks for the gallery push URL and a .symbols.nupkg file. If that is the case, SymSrc is used as the source instead. When pushing, SymSrc.org calls into the gallery to validate the API key used.
