### ISSUE TITLE
No proxy credentials dialog shown for http package source

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#2839]
The NuGet Package Manager 3.4.3 in Visual Studio 2015 does not display a dialog asking for proxy credentials for package sources that use http. The dialog is displayed for package sources that use https. A dialog is displayed in Visual Studio 2013 for both http and https package sources.

My steps to reproduce:
1. Open Visual Studio 2015.
2. Create a package source pointing to http://www.nuget.org/api/v2/
3. Set this as the default package source and check you can see NuGet packages from this source in Visual Studio.
4. Close Visual Studio 2015.
5. Run Fiddler and select Rules - Require Proxy Authentication.
6. Open Visual Studio 2015, open a project, select Manage Packages and select Browse.

Expected result:

A dialog is opened where you can enter the credentials for the proxy. Entering the credentials allows you to see the NuGet packages for the package source.

Actual result:

Error occurred message displayed.
Output window has the message:

[http://nuget.org] The V2 feed at 'http://www.nuget.org/api/v2/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='net45'&includePrerelease=true&$skip=0&$top=26' returned an unexpected status code '407 Proxy Auth Required'

**Comment by rrelyea** [comment]
@alpaix - regression from 2.x or 3.3?

**Comment by mrward** [comment]
Debugging NuGet 3.4.3 what seems to be happening is that for a https request an exception is thrown when [SendAsync](https://github.com/NuGet/NuGet.Client/blob/585b7f31574904ff627d1f41e83b477f3c797aaf/src/NuGet.Core/NuGet.Protocol.Core.v3/HttpSource/HttpHandlerResourceV3Provider.cs#L107) is called and the server responds with a proxy authentication request. This gets handled correctly since the exception is caught and the proxy authentication code is then executed.

For a http request an exception is not thrown when SendAsync is called and instead a response is returned with the status code ProxyAuthenticationRequired. This bypasses the proxy authentication code since no exception is thrown.

**Comment by mrward** [comment]
Looking at the latest code in the dev branch it looks like this has already been fixed. The logic has moved to the ProxyCredentialHandler which [checks the status code of the response](https://github.com/NuGet/NuGet.Client/blob/cea464c27a439406c669643e4a6901b56a67a337/src/NuGet.Core/NuGet.Protocol.Core.v3/HttpSource/ProxyCredentialHandler.cs#L70-L75).

**Comment by alpaix** [comment]
@mrward Thanks you for reporting the issue and verifying the fix!
This bug was accidentally fixed when resolving #1858 in https://github.com/NuGet/NuGet.Client/pull/380.

@rrelyea @yishaigalatzer We may want to decide porting the fix onto 3.4.5 branch.

**Comment by yishaigalatzer** [comment]
I would say we should please tentatively move it there. And we can discuss with Rob when he gets back

Get Outlook for Androidhttps://aka.ms/ghei36

On Wed, May 25, 2016 at 12:55 PM -0700, "Alex Panov" <notifications@github.com<mailto:notifications@github.com>> wrote:

@mrwardhttps://github.com/mrward Thanks you for reporting the issue and verifying the fix!
This bug was accidentally fixed when resolving #1858https://github.com/NuGet/Home/issues/1858 in NuGet/NuGet.Client#380https://github.com/NuGet/NuGet.Client/pull/380.

@rrelyeahttps://github.com/rrelyea @yishaigalatzerhttps://github.com/yishaigalatzer We may want to decide porting the fix onto 3.4.5 branch.

##

**Comment by rrelyea** [comment]
@alpaix - let's discuss  today. I lean towards getting this in 3.4.5, but want to understand risk/scope of change.

**Comment by alpaix** [comment]
Fixed in 3.4.5 with https://github.com/NuGet/NuGet.Client/commit/76bb5532e05664e4a03b97ef6fe84a0627efe325.
