### ISSUE TITLE
NuGet Install Fails with Error: Failed to add reference to 'System.Collections'

### ISSUE THREAD

**Issue by tonysneed** [NuGet/Home#2840]
When I create a multi-targeted .NET Core class library, which includes targets both for **.NETPortable,Version=v4.5,Profile=Profile111** and **netstandard1.3** with a dependency for _System.ComponentModel.Annotations_, installing the NuGet package for the library on a csproj-based project (for example Xamarin Android or iOS) causes the install to fail and roll back with the following error:

```
Failed to add reference to 'System.Collections'. Please make sure that it is in the Global Assembly Cache.
```

For a reproduction of this issue, please see the following GitHub repository: [NuGet.NETCore.MultiTarget.Error](https://github.com/tonysneed/NuGet.NETCore.MultiTarget.Error)

**Comment by harikmenon** [comment]
This might be related to the design time facade issue @https://github.com/NuGet/Home/issues/2594

**Comment by tonysneed** [comment]
The problem seems to go away when I remove `frameworkAssemblies` from the **.nuspec\* file which is included in the **.nupkg** file generated by the `dotnet pack` command.

According to section, "How to target a Portable Class Library (PCL)" in the article in the docs titled [Writing Libraries with Cross Platform Tools](http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html#how-to-target-a-portable-class-library-pcl):

> In this new entry, list every single assembly used for that target under a frameworkAssemblies entry. This includes mscorlib, System, and System.Core.

And unless I include  `frameworkAssemblies` in the framework that targets `.NETPortable,Version=v4.5,Profile=Profile111`, the project will not compile.

So it looks like the problem is that `dotnet pack` puts the [frameworkAssemblies section](https://github.com/tonysneed/NuGet.NETCore.MultiTarget.Error/blob/master/artifacts/MyTestClassLibrary.nuspec#L14-44) in the .nuspec file when it should not.

Does this shed any light?

**Comment by rrelyea** [comment]
@toddm - Addressable?

**Comment by toddm** [comment]
I'm not entirely sure what the correct behavior should be.  @emgarten - what do you think?

**Comment by tonysneed** [comment]
I'm wondering why frameworkAssemblies is required for PCL targets in project.json?

**Comment by emgarten** [comment]
This should be fixed as part of the issue Hari mentioned.

As a workaround remove any unneeded framework assembly references from project.json and add type: build to the rest.

**Comment by tonysneed** [comment]
Thanks @emgarten, I'll give the work around a try.

**Comment by Rivierg** [comment]
Hello, I am having a similar issue and I would like to ask for your help.
I have a PCL project, and 3 platform projects for Android, iOS and UWP. in VS2015.
I am trying to install the [Neo4J.Driver NuGet](http://www.nuget.org/packages/Neo4j.Driver), but I get the following errors. However it seems to have installed on UWP .
- On the PCL: 

> Could not install package 'Neo4j.Driver 1.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
- On Android:

> Could not install package 'System.Reflection.Extensions 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have these targets in the project: .Net Framework 4.5, ASP.NET Core 1.0, Windows 8.1, Windows Phone8.1, Windows Phone Silverlight 8, Xamarin.Android, Xamarin.iOS.
I tried to understand how to fix the issue reading (https://github.com/NuGet/Home/issues/1325) or (https://github.com/dotnet/corefx/issues/5955) but I don’t really understand what is going on.

Thank you in advance

**Comment by emgarten** [comment]
@Rivierg that compatibility issue looks unrelated to this one for adding framework references to a project. Please open a new issue and include details on what version of NuGet you are using.
