### ISSUE TITLE
Uploading large packages result in OutOfMemoryException

### ISSUE THREAD

**Issue by mocsharp** [NuGet/Home#2842]
Using latest (as of May 24,16) nightly build of nuget.exe, I was able to upload nuget packages over 300MB without timing out.  However, Nuget.Server now throws an OutOfMemory exception.  

Exception was thrown from StreamExtensions.cs > ToStreamFactory in the ZipPackage constructor, stream.ToStramFactory() call.

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#3042
