### ISSUE TITLE
Create MVC or Empty project, meet error.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2845]
NuGet version 3.5.0.1337, 3.5.0.1352
Repro steps:
1.Create MVC or Empty project.

Expected: Create successful.
Actually: Create project, meet error.
![capture](https://cloud.githubusercontent.com/assets/12129698/15531789/dc8bc25a-228e-11e6-9654-23478c966167.PNG)

**Comment by rrelyea** [comment]
Those 2 builds are dev branch builds. Please check 3.5-beta2 build too. If repros there, leave this issue in 3.5-beta2...and fix in dev and 3.5-beta2.
 If dev only, change issue to 3.5-rc milestone and fix in dev.

**Comment by zhili1208** [comment]
checked 3.5-beta2 1348, this doesn't repro, it repros in dev

**Comment by zhili1208** [comment]
the issue here is SemanticVersion in NuGet.VisualStudio.dll is not implemented yet.
