### ISSUE TITLE
Create UAP project, meet error.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2846]
NuGet version: 3.5.0.1337, 3.5.0.1352

Repro steps:
1.Create File->New Project->Visual C#->Windows->Universal->Blank App(Universal Windows) project.

Expected: The project create successful.
Actually: Meet error.
![capture](https://cloud.githubusercontent.com/assets/12129698/15534500/b13563e2-229b-11e6-8592-136e8e012830.PNG)

**Comment by rrelyea** [comment]
Those 2 builds are dev branch builds. Please check 3.5-beta2 build too. If repros there, leave this issue in 3.5-beta2...and fix in dev and 3.5-beta2.
If dev only, change issue to 3.5-rc milestone and fix in dev.

**Comment by zhili1208** [comment]
checked 3.5-beta2 1348, this doesn't repro, it repros in dev
