### ISSUE TITLE
Visual studio 2013 U5 hangs while accessing the offline(sync) folder location

### ISSUE THREAD

**Issue by mallikharjunaa** [NuGet/Home#2848]
We have one customer incident in which customer is trying to load the project solution from offline(sync) folder location and seeing VS hang. Customer was not seeing this problem if he removes the “.suo” file from the folder location.

1)  Customer has solution file on file server and its accessing via shared location
2)  Each client developer get their own copy on their local machine making its as offline files through sync center
3)  When the user log-on and sync is done, developer open the solution in VS 2013 by double clicking “.sln” file
a.  If .suo file is not present, the solution project opens successfully on time.
b.  If .suo file is present, the VS 2013 busy is opening the solution project and shows error balloon “Microsoft visual studio 2013 is busy waiting for an internal operation to complete”.
c.  If suo file deleted and try to open the project again, solution project file open successful.

We collected the dump file while VS 2013 hangs : \raviuppa-p\Customer_Files\Mallikharjuna\116051314161872
We see that, devenv.exe is manipulating the .suo file these two locations.
a)  C:\Windows\CSC\v2.0.6\namespace\10.0.0.132\ProductWorkspace\raja.sankaramoorthy\Documents\TFS\Analance_2010\Analance_2010.v12.suo
b)  \10.0.0.132\ProductWorkspace\raja.sankaramoorthy\Documents\TFS\Analance_2010\Analance_2010.v12.suo

However, the hang doesn’t seems to be because of file operations on .suo file, the thread (running under devenv process) seems to be spinning in high CPU (2-5%) and doesn’t return back.

Does the customer’s setup to open the project from offline sync folder is supported by VS or not? 

Is there a workaround ? customer’s don’t want to delete the .suo files always as it removes their user preferences.

**Comment by rrelyea** [comment]
This doesn't appear to be NuGet related, does it?
@harikm86 - can you please help them route this to the right VS feedback mechanism, if I am correct.

**Comment by harikmenon** [comment]
For context. I asked him to open the issue here since NuGet is the call stack for the hang

The file was likely corrupted by something in else in the product, and now it hangs when it tries to load it.
Based on the stack, it looks like NuGet is running some external code and that code has hung.  I would recommend following up with the NuGet team.

```
            [External Code] 
           [Frames below may be incorrect and/or missing, native debugger attempting to walk managed call stack]                
           [Managed to Native Transition]  
```

> ```
>         WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)         Unknown
> ```
> 
> mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Unknown
>                [Native to Managed Transition] 
>                [External Code] 
>                [Managed to Native Transition]  
>                mscorlib.dll!System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle waitableSafeHandle, long millisecondsTimeout, bool hasThreadAffinity, bool exitContext)              Unknown
>                mscorlib.dll!System.Threading.WaitHandle.WaitOne(int millisecondsTimeout, bool exitContext) Unknown
>                mscorlib.dll!System.Threading.WaitHandle.WaitOne()    Unknown
> System.Management.Automation.dll!System.Management.Automation.Runspaces.PipelineBase.Invoke(System.Collections.IEnumerable input)    Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.RunspaceDispatcher.InvokeCore.AnonymousMethod__5()                Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.RunspaceDispatcher.WithLock(System.Action act)        Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.RunspaceDispatcher.InvokeCore(System.Management.Automation.Runspaces.Pipeline pipeline, System.Collections.Generic.IEnumerable<object> inputs)         Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.RunspaceDispatcher.Invoke(string command, object[] inputs, bool outputResults) Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.RunspaceDispatcher.ExecuteScript(string installPath, string scriptPath, NuGet.IPackage package) Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.PowerShellHost.ExecuteInitScripts()                Unknown
> NuGetConsole.Host.PowerShell.dll!NuGetConsole.Host.PowerShell.Implementation.PowerShellHost.Initialize(NuGetConsole.IConsole console)              Unknown

@mallikharjunaa : Can you provide a full dump and stacktrace?

**Comment by mallikharjunaa** [comment]
Hi Harikrishna Menon,

This dump was collected using process explorer when we were seen continues CPU cycles.

we are seeing the following last error and seeing the NUGet package is trying to execute some script and waiting to complete.

0:000> !gle
LastErrorValue: (Win32) 0 (0) - The operation completed successfully.
LastStatusValue: (NTSTATUS) 0xc000007c - An attempt was made to reference a token that doesn't exist.  This is typically done by referencing the token associated with a thread when the thread is not impersonating a client.

Please let me know if want me to collect the dump file once again using procdump.

**Comment by harikmenon** [comment]
I will let Rob follow up on what exactly he would need to troubleshoot this issue.

**Comment by mallikharjunaa** [comment]
Hello Hariksrihna,

kindly share update on this problem.

**Comment by rrelyea** [comment]
Are you seeing this on Windows 7?
What version of .NET Framework do you have installed?

**Comment by mallikharjunaa** [comment]
Environment:
OS: Windows 7 SP1 x64
Role: Client machine
Development : VS 2013 update 5

**Comment by emgarten** [comment]
I am unable to repro this, please try with VS 2017 15.5 or higher.
