### ISSUE TITLE
Package's Dependencies not sorted properly

### ISSUE THREAD

**Issue by ikourfaln** [NuGet/Home#2849]
Hi

I see that dependencies list of a package are sorted by name, just like here: [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/8.0.4-beta1)

![named](https://cloud.githubusercontent.com/assets/9744226/15539166/db20becc-2278-11e6-804b-ebd6f6b315c4.png)

But in some packages, dependencies are not sorted properly (by name), just like here: [Microsoft.CSharp](https://www.nuget.org/packages/Microsoft.CSharp)

![notnamed](https://cloud.githubusercontent.com/assets/9744226/15539237/26dacf56-2279-11e6-837b-7c351904f526.png)

**Comment by emgarten** [comment]
This change does not meet the bar at this time.
