### ISSUE TITLE
Tab Expansion For Source Parameter doesn't work

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#285]
Related Function test : 
UpdatePackageCommandShowTabExpansionForSourceParameter
OpenPackagePageCommandShowTabExpansionForSourceParameter
GetPackageCommandShowTabExpansionForSourceParameter
InstallPackageCommandShowTabExpansionForSourceParameter

Repro:
at Nuget powershell console,
update-package -source , then tab

expected: source list
actual: solution file list

**Comment by danliu** [comment]
Fixed via https://github.com/NuGet/NuGet.VisualStudioExtension/commit/65916298f6cd707c1e435b337c5a8f327b471342
