### ISSUE TITLE
Leverage AssemblyMetadata attribute for nuspec token replacements

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#2851]
Currently there are a fixed number of attributes that are taken from a project's AssemblyInfo to be used as replacement tokens in a nuspec file when generating a package for a project. 

Additional replacement values must be specified via the nuget command line only, in order to be usable as replacement tokens. 

AssemblyMetadataAttribute (see http://msdn.microsoft.com/en-us/library/system.reflection.assemblymetadataattribute(v=vs.110).aspx) could be used to automatically extend the replacement tokens in a very convenient way. 

This would allow easy replacement of an $authors$ or $owners$ tokens in the .nuspec by simply having the following in a common assemblyinfo.cs: 

[assembly: AssemblyMetadata("authors", "foo, bar")] 
[assembly: AssemblyMetadata("owners", "Outercurve")] 

> Note: this brings back this issue that was reported, PR'ed and merged at codeplex, but apparently lost in the migration :(. See http://nuget.codeplex.com/workitem/4248

**Comment by kzu** [comment]
I'm in the process of migrating the original PR changes over. Will submit it soon.

**Comment by kzu** [comment]
@emgarten I see you merged it back in Codeplex, so I'll nag you for this merge ;)

**Comment by kzu** [comment]
Do the issues get assigned a milestone so we can track when it ships? (I'm eager to drop my custom build ;))

**Comment by rrelyea** [comment]
Yes, if this just got merged today, should make 3.5 rtm, per current plans.
