### ISSUE TITLE
Intellisense tab complete broken in Package Manager Console

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2853]
NuGet Version 3.5.0.1337(dev), 3.5.0.1352(dev), 3.5.0.1348(3.5.0-beta2)

Repro steps:
1.Create a new project(like MVC project).
2.Open Package Manager Console window.
3.Type "Install-Package " or "Install-Package jq" , press Tab key.

Expected: Show Intellisense.
Actually: Show "Time Elapsed: ...".
![capture](https://cloud.githubusercontent.com/assets/12129698/15564943/802275d4-2349-11e6-90ee-c7953dd6f517.PNG)

**Comment by jainaashish** [comment]
Since this bug was introduced because of the fix for https://github.com/NuGet/Home/issues/1909 hence backporting this as well to 3.4.5

**Comment by jainaashish** [comment]
Merged with 6acac0ab41bd87a6460990a17fd090e459e5ceec
