### ISSUE TITLE
Restore Packages does not actually restore many of the runtime dependent related packages

### ISSUE THREAD

**Issue by ravensorb** [NuGet/Home#2854]
I am currently trying to build my solutions via the CLI.  I am executing a nuget.exe restore <solution.sln> and while it does restore packages it only seems to restore 95% of them.  It consistently failes to restore packages likes Microsoft.CSharp.  It seems to only be an issue for the new project.json based projects

Ex:

```
The package Microsoft.CSharp with version 4.0.0 could not be found in c:\user\<myuser>\.nuget\packages. Run a NuGet package restore to download the package.
```

The problem is -- I did run the Nuget restore command and it didn't pick that one up.

Thoughts?

**Comment by ravensorb** [comment]
As an added note.  This seems to be mainly an issue on a fresh computer or after executing a "nuget locals all -clear" and then trying to build

**Comment by rrelyea** [comment]
Does Microsoft.CSharp exist in one of your package sources? Is that package source enabled? What version of NuGet.exe are you using? (when working with CLI, for best results you should be using 3.5.0-beta1 -- please download from http://dist.nuget.org/index.html)

**Comment by ravensorb** [comment]
Right now i am using build 3.4.3.855.  I'll try the beta version.  As for Microsoft.CSharp, no it is not directly referenced, it is a dependency reference through "Microsoft.NETCore.UniversalWindowsPlatform".  From what I can tell. the current command line version of nuget does not actually pull in any of the dependencies from nuget packages that are part of the project.json (it does however work for project.config).

The current workaround that I have had to do is to script a restore of all of the dependent packages prior to compiling.  The other interesting thing to note is, if these dependent packages are in the global cache folder, everything works (it will leverage them) -- it is only an issue when the global cache and local packages folder are 100% clean.

**Comment by ravensorb** [comment]
Quick update, the beta version is working a little better. It looks like most of the dependencies are being restored.  The odd part is, it seems that msbuild and the restore packages do not seem to be in agreement

![Image](https://i.imgur.com/zi73hvn.png)

If you look at the screen shot, it would appear that Microsoft.CSharp was restored, however it is not being found by the build system (or is there something wrong with the nuget.targets file)?

Note: This is the ONLY error in my build when using the beta build of the nuget.exe -- everything else seems to have restored correctly.

**Comment by ravensorb** [comment]
One note on the beta build -- the command line parameter for the API key that is used for delete is not working.  I get the following

```
Response status code does not indicate success: 401 (An API key must be provided in the 'X-NuGet-ApiKey' header to use this service).
```

**Comment by crenshaw78** [comment]
Just click on Packages -> Control Right Click -> Restore Packages. That fixed it for me.

**Comment by emgarten** [comment]
I am unable to repro this. Please try with VS 2017 15.5 or higher.
