### ISSUE TITLE
UWP give code analyzer warning - The referenced component could not be found

### ISSUE THREAD

**Issue by koko343** [NuGet/Home#2856]
My NuGet package contains .dll files that are build for specific platforms (arm, x86 and x64). It was created by the guide http://dontcodetired.com/blog/post/Creating-a-Windows-Store-App-NuGet-Package-for-ARM-x86-and-x64.aspx. Packages works fine, except one fact, I receiving warning from code analize with a following context : The referenced component 'C:...\1.0.0.8\build\uap10.0
![untitled](https://cloud.githubusercontent.com/assets/9040929/15613288/763a88d4-243b-11e6-9140-5aac5f6c3065.png)
the same in solution 
![untitled2](https://cloud.githubusercontent.com/assets/9040929/15613291/7baffd08-243b-11e6-9725-d2bb07d7aad9.png)
My nuget.targets file:
![image](https://cloud.githubusercontent.com/assets/9040929/15612714/a1c42346-2438-11e6-8a15-ffbad02c5864.png)

Please give me an idea, how can I figure it out.

**Comment by emgarten** [comment]
Take a look at the authoring docs: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
