### ISSUE TITLE
How to reference netframework35 library from net451 project?

### ISSUE THREAD

**Issue by Daniel15** [NuGet/Home#2859]
_From @Daniel15 on May 29, 2016 1:3_

Im trying to upgrade my site from ASP.NET 5 RC 1 to ASP.NET Core RC2. I'm encountering this error on one of the assemblies:

```
error: Package MarkdownDeep.NET 1.5.0 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package MarkdownDeep.NET 1.5.0 supports: netframework35 (.NetFramework 3.5,Version=v0.0)
```

The `MarkdownDeep.NET` package only contains an assembly for `netframework35`. I tried adding `netframework35` to the `imports` section but that doesn't seem to have worked.

`project.json` file:

```
{
    "version": "1.0.0-*",
    "description": "Daniel15.BusinessLayer Class Library",

  "dependencies": {
    "Daniel15.Data": {
      "target": "project"
    },
    "MarkdownDeep.NET": "1.5.0",
    "Microsoft.AspNetCore.Http.Extensions": "1.0.0-rc2-final",
  },

    "frameworks": {
        "net451": {
          "frameworkAssemblies": {
            "System.Net": "4.0.0.0"
          },
          "imports": [
            "netframework35"
          ]
        }
    }
}
```

_Copied from original issue: aspnet/Home#1517_

**Comment by Daniel15** [comment]
_From @davidfowl on May 29, 2016 1:33_

You don't need the imports, that should work without any issues. It looks like a nuget bug. 

/cc @emgarten @yishaigalatzer

**Comment by Daniel15** [comment]
_From @davidfowl on May 29, 2016 1:35_

I just noticed something bizzare in the error message:

```
supports: netframework35 (.NetFramework 3.5,Version=v0.0)
```

The package is busted. It's saying the framework name is .NETFramework 3.5 and the version is 0.0.

**Comment by Daniel15** [comment]
_From @davidfowl on May 29, 2016 1:36_

You can actually work around this by making this the import:

``` JSON
"imports": [
   ".NetFramework 3.5,Version=v0.0"
]
```

**Comment by Daniel15** [comment]
_From @davidfowl on May 29, 2016 1:38_

@emgarten Looks like a nuget bug where it can't parse the framework name. It works fine in `packages.config` based projects.

**Comment by Daniel15** [comment]
@davidfowl  - The package is basically abandoned (last updated 2012). I might fork it for my own uses.

However, I don't think the package itself is busted. This exact same package works fine in an ASP.NET 5 RC1 website, it only breaks once I switch to RC2.

**Comment by Daniel15** [comment]
_From @davidfowl on May 29, 2016 1:40_

Yea, it looks like a nuget bug to do with parsing the target framework.

**Comment by Daniel15** [comment]
_From @yishaigalatzer on May 29, 2016 5:16_

Please move the issue to the nuget repo.

**Comment by davidfowl** [comment]
The following parses as "unsupported":

``` C#
var fx = NuGetFramework.Parse(".NetFramework 3.5");
Console.WriteLine(fx.Framework);
Console.WriteLine(fx.Version);
```

Then we take treat it like the entire string is the name with version = 0.0:

https://github.com/NuGet/NuGet.Client/blob/0836ef72d6b89d033f11ff21703dd693aea32515/src/NuGet.Core/NuGet.Client/ManagedCodeConventions.cs#L115-L125

**Comment by davidfowl** [comment]
FWIW, NuGet.Core also parses it as unsupported, but somehow the installation works fine.

**Comment by Daniel15** [comment]
The error message says "Package MarkdownDeep.NET 1.5.0 supports: netframework35"... Where does that "netframework35" string come from? I assume something must be parsing ".NetFramework 3.5" -> "netframework35" right?

**Comment by emgarten** [comment]
This is an issue with the package.
