### ISSUE TITLE
nuget install doesn't create a package.config file

### ISSUE THREAD

**Issue by MadJlzz** [NuGet/Home#2864]
I am having an issue with nuget install.

In fact he doesn't generate a package.config file after my nuget install.

Steps to reproduce (NuGet Version: 3.4.3.855)
`nuget install <packageID> -Source <anySource> -ExcludeVersion -OutputDirectory <directory>`

Maybe all of this is normal but I am completely blocked when I want to use the `nuget update` command since it requires a package.config file.

Am I not understanding something ?
Thanks in advance.

**Comment by harikmenon** [comment]
What kind of project are you targeting? Maybe you have a project.json instead of packages.config?

**Comment by MadJlzz** [comment]
I am targeting for now just a directory where you can find some subdirectories. All of them are empty.

Something like this:
Directory1/
|__SubDirectory1 
|__SubDirectory2 

I launch my 
`nuget install <packageID> -Source <anySource> -ExcludeVersion -OutputDirectory SubDirectory1/`
inside Directory1 for example.

No, I don't have any project.json.
Do I need to write packages.config by myself ?

In the future I plan to use NuGet with Unity3D to manage my video game dependencies.

**Comment by harikmenon** [comment]
I don't believe this is supported at this time. Adding @yishaigalatzer , he will have some ideas here.

**Comment by yishaigalatzer** [comment]
This is not supported, also note that running nuget.exe update doesn't guarantee a proper update for packages including content or dlls (depending on the project system).

**Comment by MadJlzz** [comment]
Thanks for your answers.
I just founded a dirty workaround for now so I'll just go with that.
