### ISSUE TITLE
targetVersion is being set to 'net" when using nuget gui to search in visual studio 2015

### ISSUE THREAD

**Issue by kquinbar** [NuGet/Home#2866]
i am using visual studio 2015 and nuget package manager 3.4.3.855. I recently starting having issues when right clicking on solution and selecting manage nuget packages menu item. when searching in our private repository (and probably nuget.org), when it searches, it is passing in a targetFramework of just 'net' instead of the actual .net version, such as 'net451'. this does not happen on all solutions, but is happening on the one i need to work , plus i looked at 2 other similar ones and it failed there too. I have at least one solution where it works fine.

I have updated visual studio and all extensions to latest version in case that was causing any issues. any ideas on what could be causing this?

http://packages.zywave.com/nuget/Integration/Search()?$filter=IsLatestVersion&searchTerm='core'&targetFramework='net'&includePrerelease=false&$skip=0&$top=26

**Comment by kquinbar** [comment]
Update: this seems to occur when i have multiple projects in my solution and the first one is .net 4 or .net 4.5 but all the other are .net 4.52 or 4.6. meaning they all match except the first one.

**Comment by rrelyea** [comment]
Did you see different behavior with older versions of NuGet? Or are you just noticing this now?
What behavior were you hoping to see?
What is the impact of the current behavior?

**Comment by kquinbar** [comment]
- i have not tried an older version of nuget but i can for comparison.
- i would expect to see the same list of available packages at the project level and at the solution level
- impact is that i cannot add the package i want at the solution level, but i can at the project level. adding packages at the project levels leaves it open to having different versions of the same package in every project though and we dont usually do that. we try to always add packages at the solution level.

**Comment by yishaigalatzer** [comment]
This is not something we had an intentional design in mind for.

We could either pass the minimal version, that will somewhat solve this problem but will also hide packages you might have wanted to install in other projects. This will work for net45 + net40 but not for net45 + portable- project combination.

We could just not pass the filter at all in solution level packages, and show everything.

**Comment by youngdelaney** [comment]
o really i just pull it yesterday because was causing lot of problem some was using i split drop the issue

**Comment by kquinbar** [comment]
ok, i downgraded to v3.3.0 of nuget package manager. i then put my solution back to the way it was where one project was .net 4.5 and the other 4 were .net 4.5.2. now nuget properly returns all packages i would expect to see when i search.

the url that is being called is different though than with 3.4.3. it looks like it is passing in more than one targetFramework, so that must be the change that broke things at the solution level. 3.4.3 only passes in the first net version and i assume instead of something like net45, it just use "net" to represent a base of net45? even 3.3.0 passed in just "net" for the first project.

not sure what the correct fix is. to either not filter the list or to go back to passing through all the project versions? as long as the end result is that the correct version will get applied to each project.

/nuget/Integration/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&searchTerm='core'&targetFramework='net45%7Cnet452'&includePrerelease=false

**Comment by zachweg** [comment]
This issue was occurring for me too in VS 2015 VISX (v3.4.4) but it appears **fixed** in VS 2015 VSIX (v3.5.0-rc1)

I confirmed with Fiddler that in v3.5.0 when browsing for packages with 'Manage Packages for Solution" the targetFramework parameter now correctly specifies a value for each framework version used by the projects in a solution instead of only passing 'net' and excluding from the search all packages using the lib folder convention.

**Comment by raguayo-springcm** [comment]
This is happening to me as well.  Just as @kquinbar stated earlier, at a solution level the packages are not listing, on a project level the packages are listing.

I'm using Visual Studio Professional 2015 Version 14.0.25431.01 Update 3

NuGet Package Manager Version 3.3.0.167 produces:
/nuget/DevLib/Search()?$filter=IsLatestVersion&$orderby=DownloadCount desc,Id&searchTerm=''**&targetFramework='net45|net451|net452'**&includePrerelease=false 

NuGet Package Manager Version 3.5.0.1484 produces:
/nuget/DevLib/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''**&targetFramework='net'**&includePrerelease=true&$skip=0&$top=26

&targetFramework='net'  is definitely the source of the problem, it seems to filter out all of my packages from the feed.

**Comment by emgarten** [comment]
I am unable to repro this. Please try with VS 2017 15.5 or higher.
