### ISSUE TITLE
NuGet Extension in VS 2015 Update 2 throws Errors even though Project builds succesfully

### ISSUE THREAD

**Issue by joperezr** [NuGet/Home#2868]
We had an issue logged in .Net Framework repo which is not related to us, so moving into here to track. I'm not sure if this is the right place though, so apologies if it isn't.

Issue in corefx: dotnet/corefx#8963

This is the error we hit when we try to build the solution which restores a project.json that targets netcoreapp1.0:

```
1.Nuget package restore failed for project tests\System.Data/Sqlclient.Manualtesting.Tests for 'test-runtime' 
2.Unable to resolve test-runtime for .NETCoreApp, Version=v1.0.
```

Despite of this, we still get a successful build because the actual restore did work, just VS shows this error in the error list.

CC: @sravan1022

**Comment by rrelyea** [comment]
@sravan1022 - what version of NuGet do you have installed in VS2015?
If you are using .net core, you should be using NuGet 3.5.0-beta for best results.
Please try the build of the VS integration from http://dist.nuget.org/index.html and let us know how that works.
If it still has a problem, please tell us details on how we can see the same problem.

**Comment by tkopacz** [comment]
Hello, 
I have the same problem - I can run test from command line - but not from VS 2015 Update 2. Clear Windows installation etc.

Dependency '"test-runtime": {
  "target": "project",
  "exclude": "compile"
}' has invalid version specification.
------ Load Playlist started ------
========== Load Playlist finished (0:00:00) ==========
------ Discover test started ------
Dependency '"test-runtime": {
  "target": "project",
  "exclude": "compile"
}' has invalid version specification.
========== Discover test finished: 0 found (0:00:01.4680124) ==========

And in Build:

Unable to resolve 'test-runtime' for '.NETCoreApp,Version=v1.0'.
NuGet Package restore failed for project System.Buffers.Tests for 'test-runtime '.
NuGet package restore failed.

For example: corefx\src\System.Buffers\System.Buffers.sln

**Comment by sravan1022** [comment]
For my task, i don't need to run those test sources, so i unloaded them and successfully built my sqlClient sources. But with those, i am getting the errors as i mentioned above.
@joperezr Yeah i ran the init-tools.cmd present in tools folder but still doesn't work.I don't have work with those test projects/solutions but still it will be useful for someone if we can resolve this.

@rrelyea Nuget version manager version : 3.4.41321
I tried nuGet 3.5.0 beta in vs2015 and win-7 but the errors are same.

**Comment by joperezr** [comment]
@sravan1022 I actually tried installing the 3.5 beta nuget package manager and that fixed it for me. I believe what happened to you now is that you did install nuget3.5 but you didn't install the package manager for vs2015 as well. Close VS, [download and install this](https://dist.nuget.org/visualstudio-2015-vsix/v3.5.0-beta/NuGet.Tools.vsix) and then re-open VS. That should work and remove those errors.

**Comment by tkopacz** [comment]
Strange - for me -  Package Manager is showing that is correctly installed (3.5.0.1284 as for now)
I'll dig deeper - maybe again - from clean machine etc...

**Comment by sravan1022** [comment]
@joperezr I tried exactly the same way you said. Didn't work. May be the error lies in some other place. Anyway thanks for the help.

**Comment by vikas0380** [comment]
Facing the same problem

@rrelyea @joperezr   tried the 3.5 beta from the link provided by you, still same error

**Comment by emgarten** [comment]
I am unable to repro this issue. Please try with the latest VS 2017 15.5 or higher.
