### ISSUE TITLE
NuGet.Configuration: Click OK button failed save the package source selections to NuGet.Config

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#287]
This is the configurations on NuGet.Config. Start Package Source options, uncheck one of the sources and then click OK is not saving correctly. 

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageRestore>
        <add key="enabled" value="True" />
        <add key="automatic" value="True" />
      </packageRestore>
      <packageSources>
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
        <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
        <add key="WPF-Local (w/ DeferLoad)"     
    value="\\authoring\public\User\rrelyea\applocal\DemoBuild" />
      </packageSources>
      <disabledPackageSources>
        <add key="nuget.org" value="true" />
        <add key="WPF-Local (w/ DeferLoad)" value="true" />
      </disabledPackageSources>
      <activePackageSource>
        <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
      </activePackageSource>
    </configuration>

**Comment by zhili1208** [comment]
It's fixed
