### ISSUE TITLE
Spec, test, and doc servicable metadata in nuspec

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2870]
In nuspec file an attribute "like" this:
`<serviceable>true</serviceable>`
...will enable Microsoft Update servicing for Microsoft delivered packages.

1) Lock down metadata spec
2) test to ensure that "nuget pack foo.nuspec" works if the nuspec has this metadata. (test with 3.4.4 and 3.5.0-beta, 3.5.0-beta2)
3) Test to ensure no major problems with NuGet servers if we add this metadata.
4) Consider the ~19 Nuget.*.nupkg for addition of the metadata
5) change docs

**Comment by rrelyea** [comment]
Rohit already found that Nuget.exe pack validates and errors due to this unknown metadata. Considering taking a 3.5.0-beta2 fix to change the schema to allow it.

**Comment by rohit21agrawal** [comment]
@rrelyea  @ericstj 
I am currently testing my prototype ( https://github.com/NuGet/NuGet.Client/commit/f81b1b19cee8e1612632afb52fde303e6c134b25 ) which works with < serviceable > attribute on a nuspec file.

I have done the following validation so far:
1) nuget pack foo.nuspec works as expected with the new bits.
2) older clients (tested nuget 3.4.4 so far) are able to restore/list/install/update packages whose nuspec file has  < serviceable > attribute.
3) "dotnet pack" does not support nuspec file so can't test with it currently.
4) "nuget push" works for a nupkg with  < serviceable > attribute. (Tested 3.4.4 client with ProGet server so far).

**Comment by rohit21agrawal** [comment]
Merged release-3.5.0-beta2 : https://github.com/NuGet/NuGet.Client/commit/2521e6b13d79467b13dcc8e54ce45e8886b9e6e8
dev : https://github.com/NuGet/NuGet.Client/commit/be8f0ee13619e657779a6094fe060307d5f28b00
