### ISSUE TITLE
nuget solution update will only update projects under sln dir

### ISSUE THREAD

**Issue by hgran** [NuGet/Home#2875]
:>nuget.exe update  -id mypackage mysolution.sln
will only update projects that are located in a subfolder to the solution directory.
I have projects in subdirs to the directories src\A and src\B
The solution is src\B\solution.sln

Update is done in src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs 
For solutions the method UpdateAllPackages will get all *.config files below the solution directory and will therefore not update the projects that are in other directories.
It will probably also be the cause of:
https://github.com/NuGet/Home/issues/2747

**Comment by emgarten** [comment]
The only official way to update packages for packages.config is to use visual studio. nuget.exe update is limited in what it can change without the vs project system.

For improved command line support use PackageReference instead of packages.config.
