### ISSUE TITLE
NuGet pack - Missing Newtonsoft.Json package dependency

### ISSUE THREAD

**Issue by bednart** [NuGet/Home#2876]
Hi, 
I have problem with missing Newtonsoft.Json dependency in my own created NuGet package using NuGet.exe 3.4.3 
## Steps to reproduce
- Create .NET451 C# ClassLibrary TestPackage project
- Install NuGet package Microsoft.AspNet.WebApi.Client 5.2.3
- These packages are added to packages.config:

`<package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" />`
`<package id="Newtonsoft.Json" version="6.0.4" targetFramework="net451" />`
- Update Newtonsoft.Json to 8.0.3
- packages.config now contains:

`<package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net451" />`
`<package id="Newtonsoft.Json" version="8.0.3" targetFramework="net451" />`
- Build project in release configuration and run nuget pack command:

`nuget pack TestPackage.csproj -Properties Configuration=Release;Platform=AnyCPU`
- TestPackage.1.0.0.0.nupkg is created
- Open TestPackage.nuspec from created package
## Expected  behavior
- I would expect that these dependencies are in TestPackage.nuspec

`<dependency id="Microsoft.AspNet.WebApi.Client" version="5.2.3" />`
`<dependency id="Newtonsoft.Json" version="8.0.3" />` 
## Actual behavior
- There is only one dependency in TestPackage.nuspec file:

`<dependency id="Microsoft.AspNet.WebApi.Client" version="5.2.3" />`

This is problem because my TestPackage requires Newtonsoft.Json >= 8.0.3 but it is not in package and if you install TestPackage 1.0.0.0 there is only Newtonsoft.Json 6.0.4 installed which comes from Microsoft.AspNet.WebApi.Client dependencies.

So if I install TestPackage in another project I'm able to build project successfully because Newtonsoft.Json.dll is there but if I call method from TestPackage i got this runtime exception: **Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0**

So is it NuGet.exe bug or am I missing something?

Thanks in advice.

Best regards,
Tomas

**Comment by bednart** [comment]
Anyone please? :)

**Comment by rrelyea** [comment]
Can you please try NuGet 3.4.4, which is released now: http://dist.nuget.org/index.html

**Comment by bednart** [comment]
Thanks for reply ;) Result is same with NuGet 3.4.4 as with NuGet 3.4.3 :(

**Comment by rohit21agrawal** [comment]
Verified that this problem has been fixed in 3.5.0-beta2 . 
@bednart Could you try downloading [NuGet.exe 3.5.0-beta2](https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe) from [here](https://dist.nuget.org/index.html) and verify?

**Comment by rohit21agrawal** [comment]
@bednart We have verified on our end that this issue does not repro with 3.5.0-beta2, and so we are closing this bug. 
Please feel free to reactivate  if this issue still persists for you with 3.5.0-beta2. Thanks!

**Comment by bednart** [comment]
@rohit21agrawal Sorry I wasn't nearby PC. I just tested it and I can confirm it works ;) Thanks a lot.
