### ISSUE TITLE
UI delay when updating a NuGet package with XAML file open

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2878]
Please investigate fixes for update3 bug # 225323

**Comment by rrelyea** [comment]
please close after you cherry pick into 3.4.5.

**Comment by drewgillies** [comment]
https://github.com/NuGet/NuGet.Client/commit/d05cddb219921b5e5fe73490f93c9d357779af4b

Cherry-picked into release-3.4.5. Closing.

**Comment by alpaix** [comment]
Updating milestone for validation purposes.

**Comment by rrelyea** [comment]
We removed the changed because it regressed File>New Project>UWP (Blank App)
TFS Bug 225323 Original perf problem
TFS Bug 241263 Perf Regression

Reactivating. We should consider what the best fix is, if any.

**Comment by emgarten** [comment]
Batching has been explored and added where possible.
