### ISSUE TITLE
NuGet update through package manager removes properties from the project.json

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2888]
@vancem noticed this when trying to upgrade a project.

This is happening for both `"type": "platform"` and `"exclude": "compile"`.  The latter is definitely bug and something that should be fixed.  Package manager should preserve the dependency shape (properties vs not) in the project.json.

The former is a different question (NuGet from updating the shared framework) which I'll leave out of this issue. /cc @piotrpmsft

**Comment by rrelyea** [comment]
Are you using 3.5-beta of vsix?

**Comment by ericstj** [comment]
No, was using 3.4.3.

**Comment by rrelyea** [comment]
@vancem / @ericstj  - Can you please add repro steps and details?
Would be great to understand if 3.5-beta of the VSIX shows the same problem, too. That is the VSIX one should be using when doing netcore work.

**Comment by vancem** [comment]
I happen to reproduce it from VS 2015 (update 2)    To repo there 

Create a new  project

File -> New Project -> Visual C# -> .Windows -> .NET Core Console Application (.NET COre)

You get a new project with a  project.json which has type property in dependencies

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    }

Then I wanted to upgrade Microsoft.NETCore.App to the latest private drop.  I did this by right cliking on the 'References' node in the solution, -> Manage Nuget Packages.   I have made a feed for the myget repo (if you don't already have it) 

https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

and browsed to the Microsoft.NetCore.App package, and clicked the 'upgrade icon associated with that package.   

Once I upgraded, if I looked at my project.json I get 

  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0-rc4-000376"
  },

which did the upgrade but 'lost' the "type" : "platform" property, which basically broke my app in a way that I had to go get expert help (Eric) to figure out.

**Comment by rrelyea** [comment]
let's investigate with 3.5-beta2 - does it still repro? and investigate issue/fix.

**Comment by zhili1208** [comment]
Yes, it repros with 3.5-beta

**Comment by rrelyea** [comment]
This appears to be a ASPNET Tooling issue. As noted by Zhi above, we've opened an issue on them.
