### ISSUE TITLE
Excluding specific referenced projects when using IncludeReferencedProjects

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#2897]
Assume I have a solution that looks like:

```
Solution
  Project A
    References Project B
    References Project C
  Project B
  Project C
```

If I'm packing `Project A`, I can currently include a NuGet reference to `Project B` and `Project C` in one of two ways:
- I can add the dependencies explicitly in the nuspec. This isn't very good because if I add `Project D` to the solution later and add a reference to it in `Project A` I'll have to remember to update the nuspec as well. There's also the issue of keeping versions matched up, etc.
- I can use the `-IncludeReferencedProjects` flag, which works great in this scenario.

Now let's assume that `Project C` is a development dependency. If `Project C` wasn't in my solution and I had added the reference via NuGet, I could use the `developmentDependency` flag in the `packages.config` to exclude it from the list of dependencies for `Project A`. I can also add the `developmentDependency` flag to the nuspec for `Project C` to ensure that any external projects that reference it don't include it in their list of dependencies.

_However_, it doesn't seem like there's a way to address a development dependency if it's project reference and you want to continue to add _other_ project references as dependencies. I would expect/propose a couple things:
- If using `-IncludeReferencedProjects` and a referenced project has `developmentDependency` declared in its nuspec, that referenced project should not be among the list of dependencies in the package. This would match the behavior if you referenced the project via NuGet and packages.config (instead of being a project reference).
- There should be some alternate way to exclude specific project references. Perhaps a `developmentDependency` flag in the csproj for the referenced project.

This isn't just a hypothetical situation - I'm having this exact problem right now. My `Project C` is a "abstractions" library that will already be loaded wherever the `Project A` library is used. Having it be a dependency of `Project A` means a chance of runtime versioning/binding issues.

**Comment by JasonLawrenceDuncan** [comment]
FWIW, we have the same problem, and would be delighted to have a better solution. What we settled on (for now), is not using the IncludeReferencedProjects flag in our build script, and having to manually maintain any such dependencies.

**Comment by emgarten** [comment]
We are not planning to implement this feature at the current time.
