### ISSUE TITLE
Support for fallback package folders

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2899]
Design https://github.com/NuGet/Home/wiki/%5BSpec%5D-Fallback-package-folders

**Comment by TheRealPiotrP** [comment]
@rrelyea @emgarten I still don't see an API in the design which CLI can call to obtain the resolved path for an asset. As discussed offline, we'd strongly prefer not to duplicate the fallback logic in CLI as this introduces additional fragility in our integration. Can you share an ETA for the integration API?

**Comment by rrelyea** [comment]
We are waiting for go/no-go on this based on a new MVC runtime change that would be necessary. our work is checked into the dev branch.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@b5972d87fe8044843e4d4beb41d66807332ef226
