### ISSUE TITLE
Install package to lightswitch project doesn't work

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#290]
Create lightswitch desktop application.
Install entityframework to desktop client project.

expect: entityframework.dll be added to reference
actual: there is no entityframework.dll there.

Attempting to gather dependencies information for package 'EntityFramework.6.1.3' with respect to project targeting 'Silverlight, Version=v5.0'
Attempting to resolve dependencies for package 'EntityFramework.6.1.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EntityFramework.6.1.3'
Resolved actions to install package 'EntityFramework.6.1.3'
For adding package 'EntityFramework 6.1.3' to project 'Application1.DesktopClient' that targets 'sl5'.
For adding package 'EntityFramework 6.1.3' to project 'Application1.DesktopClient' that targets 'sl5'.
Package 'EntityFramework 6.1.3' already exists in folder 'C:\Users\zhi\Documents\Visual Studio 2015\Projects\WebApplication1\Application1\packages'
Added file 'App.config'.
Added package 'EntityFramework 6.1.3' to 'packages.config'
For adding package 'EntityFramework.6.1.3' to project 'Application1.DesktopClient' that targets 'sl5'.
For adding package 'EntityFramework.6.1.3' to project 'Application1.DesktopClient' that targets 'sl5'.
Executing script file 'C:\Users\zhi\Documents\Visual Studio 2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\install.ps1'...
Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully 
qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
You cannot call a method on a null-valued expression.
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "The specified path, file name, or both are too long. The 
fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully 
qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
You cannot call a method on a null-valued expression.
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "The specified path, file name, or both are too long. The 
fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\Documents\Visual Studio 
2015\Projects\WebApplication1\Application1\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully installed 'EntityFramework 6.1.3' to Application1.DesktopClient.
Added file 'app.config'.
========== Finished ==========

**Comment by ilmax** [comment]
@zhili1208  any workaround on this?

**Comment by zhili1208** [comment]
@ilmax this is working in latest build, Entityframework.dll target to net45 and net40, so Here is no dll added to Silverligh project. the install.ps script can run without any error.

**Comment by zhili1208** [comment]
Tested this issue with latest build, it's working well.

**Comment by ilmax** [comment]
@zhili1208 I'm experiencing this issue in a C# Web project (.NET 4.5

<ProjectGuid>{A4844BA5-C00B-402B-BF03-A40D7FEDC4C9}</ProjectGuid>
<ProjectTypeGuids>{349c5851-65df-11da-9384-00065b846f21};{fae04ec0-301f-11d3-bf4b-00c04f79efbc}</ProjectTypeGuids>

Interestingly enough, the path is not longer than windows limits (260) so I think the exception message is at least confusing here.
