### ISSUE TITLE
Add batch VS project event processing to packages.config projects

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#2903]
This was added for project.json projects in https://github.com/NuGet/NuGet.Client/commit/3b6f15a17a681dd4c5acc36fe5db2b13d9b058e0, increasing VS restore/install/update perf considerably. Currently it exists in MS build projects for AddFiles() and DeleteFiles() scenarios. Investigate and implement for package reference addition.

**Comment by drewgillies** [comment]
@rrelyea Added as discussed.

**Comment by rrelyea** [comment]
Let's work on this fix...and measure improvement / risk. 
Would love to be able to fit into 3.4.5 if reward / risk ratio is good.

**Comment by jainaashish** [comment]
I tried this today by adding batch processing start/end for install/uninstall packages in ms build projects and it did improve the overall performance by ~25% which isn't that significant compare to build integrated projects but still a decent improvement. 
I will discuss it little more for improvement / risk ratio and then raise a PR.

**Comment by rrelyea** [comment]
If we go forward with this, let’s get it into dev only for now…and leave the issue open. We’ll need approval to get it into 3.4.5 at this stage.

**Comment by jainaashish** [comment]
Merged only to dev a1b540bca7cc5ba78bd3c768396d468a31d080a0 as of now. reopening the issue for 3.4.5

**Comment by jainaashish** [comment]
Since now there is no 3.4.5 so closing this issue
