### ISSUE TITLE
Need a way to test installation of packages via command line

### ISSUE THREAD

**Issue by ravensorb** [NuGet/Home#2905]
As we move to more and more automated testing in our build environments it is becoming more and more important to be able to script everything. To that end, it would be ideal if there was a way to actually test the installation of a nuget package into a solution or a project file view the command line.

Scenario: I would like to create a nuget package that is designed to work in Windows 10, PCL, Xamarin iOS. This package should NOT install in a Windows 8 or Windows Phone 8 Silverlight solution.

Ideal Steps:
- Build solution via msbuild
- build nupkg via nuget.exe (or equiv)
- create/copy test projects for Windows 8, Windows 8.1, Windows 8.0 Silverlight, Windows 10, PCL Profile7, PCL Profile111, PCL Profile 259
- "deploy" nupkg file created in 2 step to 7 projects listed in step 3
- validate that package successfully "deployed" to 4 of the 7 projects (verify references are correct, files are copied to correct location).

Note: In a perfect world, I could do this on a build server that does NOT have visual studio installed.  However I would be willing to accept the need to have VS installed to get this functionality.

**Comment by yishaigalatzer** [comment]
You will have to script visual studio to do that. Look at our functional test projects, they go through similar steps.

It is currently quite impossible to do this through commandline only without visual studio

**Comment by yishaigalatzer** [comment]
The work here - Find the sample we have for this scenario and document it. Perhaps open an SO item and post it there for more visibility

**Comment by karann-msft** [comment]
The way to test this would be:
1. create the nuget package
2. copy it to a local folder
3. list that folder as a source
4. install the nuget package from that source into the 7 projects using nuget.exe
