### ISSUE TITLE
Nuget.exe currently doesn't install Packages on Mono 4.2.3

### ISSUE THREAD

**Issue by wmeints** [NuGet/Home#2907]
When I try to invoke `mono nuget.exe install <package>` on my Mac I get back an error telling me that it couldn't find a method. The exact message is:

```
Unable to load the service index for source https://api.nuget.org/v3/index.json.
  Method 'HttpResponseMessage.get_StatusCode' not found.
```

My mono version output is:

```
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
```

Gives me the feeling that nuget.exe currently doesn't work on mono. 
Any idea if I'm doing something wrong here?

**Comment by migueldeicaza** [comment]
This looks like NuGet.exe that you are trying to use was built with a different version of the APIs that are present in Mono.   You likely need to build `nuget.exe` on your machine, and not use a binary.

Could you point me to the binary for `nuget.exe` that you got and where you got it from?

**Comment by timothyparez** [comment]
I had the same issue, made the mistake of simply downloading the latest binary from NuGet.org  
The error message is misleading and the last line might explain more:

```
    https://api.nuget.org/v3/index.json: Unable to load the service index for source   https://api.nuget.org/v3/index.json.
  This method must be implemented in derived classes
```

**Comment by rrelyea** [comment]
@zhili1208  - please help

**Comment by zhili1208** [comment]
@wmeints could you try nuget 3.5? https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

**Comment by rrelyea** [comment]
@wmeints  - we believe this is already fixed. Have you been able to try NuGet 3.5 yet?

**Comment by wmeints** [comment]
Yup, just tested this. It's fixed by the looks of it.
