### ISSUE TITLE
Error Installing Newtonsoft.Json 9.0.1-beta1 package on 3.4.4+

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2908]
Nuget version: 3.4.4.1321(Release-3.4.4), 3.4.5.1429(Release-3.4.5)
Not repro in Dev branch

Repro steps:
1.Create Class Library(Portable) project.
2.Open NuGet UI, select Newtonsoft.Json package and click Install.

Expected:Install Successful.
Actually:Install meet error.

![capture](https://cloud.githubusercontent.com/assets/12129698/15811063/5aabef60-2bd7-11e6-8061-bc6fd63d859f.PNG)

Updated info from email: 
The newtonsoft.Json package version is latest prerelease 9.0.1-beta1, this version has the problem. But the other versions older than this version such as 8.0.2 or 7.0.1 and so on don’t have the problem

**Comment by zhili1208** [comment]
@v-lawu What's the portable target framework? Newtonsoft.json is not compatible with DNXCore 5.0

**Comment by v-lawu** [comment]
Create Portable Class Library project, select .NET Framework 4.6.1
check checkbox of Targets: .NET Framework 4.6, Windows Universal 10.0 and ASP.NET Core 1.0

**Comment by rrelyea** [comment]
Please investigate root cause and possible fixes.

**Comment by joelverhagen** [comment]
Newtonsoft.Json 9.0.1-beta1 has `netstandard1.0` assets. Also, when selecting the `netstandard1.0` assets, it brings in RC2 .NET Core dependencies (those ending with 24027). There was a bug in RC2 where the `dnxcore5.0` was not specified in the runtime.json file. Therefore, the `dnxcore50` guardrail fails against the RC2 dependencies pulled in by Newtonsoft.Json.

**Comment by joelverhagen** [comment]
This is the project.json generated by the repro sets:

``` json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {},
    "dnxcore50.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.0",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.0",
    "Newtonsoft.Json": "9.0.1-beta1"
  },
  "frameworks": {
    "dotnet": {
      "imports": "portable-net452+win81"
    }
  }
}
```

## Working project.json for RC2 packages

Does not include the supports since they were not mentioned in RC2 runtime.json (it was a bug that has since been fixed).

``` json
{
  "dependencies": {
    "Microsoft.NETCore": "5.0.1-rc2-24027",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1-rc2-24027",
    "Newtonsoft.Json": "9.0.1-beta1"
  },
  "frameworks": {
    "netstandard1.3": {}
  }
}
```

## Working project.json for "RC3" (will eventually be RTM) packages

Needs the following NuGet source:
https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

Does not have the `dnxcore50.app` guardrail since `dnxcore50` only supports up for `netstandard1.5`. This experience could be improved with https://github.com/NuGet/Home/issues/2919.

``` json
{
  "supports": {
    "net46.app": {},
    "uwp.10.0.app": {}
  },
  "dependencies": {
    "Microsoft.NETCore": "5.0.1-rc3-24206-00",
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1-rc3-24206-00",
    "Newtonsoft.Json": "9.0.1-beta1"
  },
  "frameworks": {
    "netstandard1.3": {}
  }
}
```

**Comment by joelverhagen** [comment]
Related bugs:
1. Improvement to PCL templates to not use the deprecated `dnxcore5.0`: https://github.com/dotnet/roslyn/issues/11823
2. Adding `netcoreapp1.0` guardrail to the runtime.json: https://github.com/dotnet/corefx/issues/9232

**Comment by joelverhagen** [comment]
After some thought and creating the two related bugs mentioned above, it seems to me that from a NuGet standpoint everything happened properly. I am going to close this as external. If anyone disagrees with this, please feel free to reply to this issue.
