### ISSUE TITLE
Support credential provider public extensibility in Visual Studio

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#2909]
Credential provider extensibility: custom MEF exports are not picked up by NuGet VSIX

The [`VsCredentialProviderImporter`](https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Clients/VsExtension/VsCredentialProviderImporter.cs#L17) does not resolve all available MEF exports, and only imports the hardcoded VisualStudioAccountProvider ([here](https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Clients/VsExtension/VsCredentialProviderImporter.cs#L78))

As a result, the credential provider mechanism is not extensible, and custom implementations can not be hooked up to resolve credentials for a package source other than VSTS and nuget.org.

**Comment by yishaigalatzer** [comment]
@xavierdecoster this is currently by design. We could look at changing this in a future release.

**Comment by apxltd** [comment]
Some of enterprise customers have a custom SSO integration with ProGet, and it’s always been a pain for them, because it’s not possible to integrate Windows Integrated Authentication. 

We like the idea of the new Credential Providers to help solve some of the authentication pains. However... because it doesn't work in NuGet VSIX, it's not really useful to our customers. 

The people who _would_ use nuget.exe (build engineers) just simply use a script and a PUSH, so having this work only for nuget.exe is fairly pointless. They would like to deploy something to developer machines so they don’t have to follow an instructions sheet on how to use NuGet.

**Comment by yishaigalatzer** [comment]
@apapadimoulis this is not pointless for VSTS there is a lot more complex handshake going on than something you just script. This is not only for pushing but also for consuming packages.

Going forward in dev15 we do have support (currently internal) for an external provider, we haven't yet spent time on making it a publiclly supported API, but it is something we would like to get to. I believe that would address your concerns, it is a matter of priority and time taken to validate the API, but the implementation is in place.

**Comment by apxltd** [comment]
Oh sorry I meant pointless for ProGet usage... when this supporting only the competing Microsoft produc/service doesn't really benefit them (or us) much :)

Of course, for VSO/VSTS, I do know there's a lot of weirdness with access tokens and stuff, so it's a must-have for that... but it would be nice to have this extensible credential system work outside of only Microsoft products. Or at least update the docs to say it's Microsoft only; our customers are the ones who pointed us to the 3.3 credential feature.

**Comment by yishaigalatzer** [comment]
Thanks @apapadimoulis 

We will update the docs. I also misspoke on the API, we only support a single credential provider in VS, we do need to make a small change (and lots of validation and sample work) to make an `[ImportMany]` instead of `[Import]`

**Comment by apxltd** [comment]
Cool, a doc update / clarification would be appreciated!  Basically just to say, VSIX only supports VSTS/VSO.

https://docs.nuget.org/consume/credential-providers

Basically our customers find that link and say, "why aren't you doing this in ProGet"

**Comment by yishaigalatzer** [comment]
Sure thing made the change.

Just small FYI for future reference, you are free to suggest edits to the docs there is a link at the bottom of each document that will take you to github, make a change and submit a PR right from there.

![image](https://cloud.githubusercontent.com/assets/1238711/15948418/890e2258-2e55-11e6-98f5-458b60587172.png)
