### ISSUE TITLE
NuGet.exe push 403 handling - Incorrectly prompting for credentials

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2910]
NuGet.exe is incorrectly prompting for credentials on push that results in 403 Unauthorized. I tested this against local gallery but verified it has the same behaviour against NuGet.org.
## Repro steps
- Push a package using a non-existing API key (so that authentication will fail)
  `NuGet.exe push <package> <random-guid-api-key> -Source https://www.nuget.org/api/v2/package`
## Expected

NuGet.exe 2.x, 3.2.0, 3.3.0 show a 403 Forbidden with the error message.

<img width="400" alt="1" src="https://cloud.githubusercontent.com/assets/485230/15825250/51e8ebf4-2c03-11e6-9806-41bb843477ec.png">
## Actual

NuGet.exe 3.4.3, 3.4.4 and 3.5.0-beta prompt for credentials.

<img width="400" alt="2" src="https://cloud.githubusercontent.com/assets/485230/15825255/55a6f132-2c03-11e6-8bf2-9b9cfaaf236a.png">

After 3 failed attempts, the 403 Forbidden is shown.

<img width="400" alt="3" src="https://cloud.githubusercontent.com/assets/485230/15825262/58b2219e-2c03-11e6-9dda-0da7c250db9c.png">

**Comment by joelverhagen** [comment]
We intentionally added prompting on 403. The reasoning was that if the server is returned 403, the user should be given a chance to enter different credentials. 403 generally means the server is saying "okay, I know who you are but you don't have permissions to access that resource". Therefore, a different set of credentials from the user could be used.

See PRs:
https://github.com/NuGet/NuGet.Client/pull/487
https://github.com/NuGet/NuGet.Client/pull/498

**Comment by maartenba** [comment]
That is somewhat annoying, for two reasons even 😄 
1. NuGet.org does not do basic auth. This means the username/password entered will never be considered valid during this flow (which you can see in the "after 3 failed attempts" where I did enter valid username/password).
2. If we decide to expire API keys, say in 90 days, I expect lots of build around the world waiting for input (and thus hanging) instead of failing fast, with fall-out to our support inbox.

**Comment by joelverhagen** [comment]
Yup seems reasonable. I think we have two options (spoke offline with @rrelyea and @yishaigalatzer):
1. Only prompt for 403 if the user has gotten 401 (or provided credentials of some kind) already for this source.
2. Only prompt for 403 if an API key has NOT been provided. This will take some plumbing.

**Comment by maartenba** [comment]
2 seems sleekest imo, but 1 may work as well.

**Comment by joelverhagen** [comment]
Time permitting, we will try to pull this in for 3.4.5.

**Comment by joelverhagen** [comment]
This fix has been committed to `dev` and `3.5.0-beta2` so far. I am working on porting the change to `3.4.5`.

**Comment by joelverhagen** [comment]
This change has now been ported to all destination branches:
`dev`: https://github.com/NuGet/NuGet.Client/commit/1ddcb743dbc15af115fc14ee452a6f61e17a85ee
`3.5.0-beta2`: https://github.com/NuGet/NuGet.Client/commit/efb2590f24981729df0746aff860283614c04483
`3.4.5`: https://github.com/NuGet/NuGet.Client/commit/b0ef84ea6db49636e69c8f00fc843c7b4abbe0ca
