### ISSUE TITLE
Expose package compatibility as a public API for consumption in CLI

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2911]
Expose an API in NuGet so CLI can solve this issue:
https://github.com/dotnet/cli/issues/3396

Something on `CompatibilityChecker.cs` probably. The code in CLI that is replicating this logic is here:
https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L35-L38

**Comment by nkolev92** [comment]
Lower priority
