### ISSUE TITLE
Enable installation of packages with type build or platform.

### ISSUE THREAD

**Issue by NTaylorMullen** [NuGet/Home#2912]
The scenarios listed are under the assumption that [this issue](https://github.com/NuGet/Home/issues/2476) has been completed and the following RazorTooling [issue](https://github.com/aspnet/RazorTooling/issues/80) has been completed.
## Scenario 1

User wants to install Razor tooling into their project (or ef, or scaffolding).
1. They install `Microsoft.AspNetCore.Razor.Tools`. It installs as a `DotnetCliTool`.
2. They install `Microsoft.AspNetCore.Razor.Design`. It installs as a dependency.
3. They publish their application/library etc.

**Result:** They now have a project with all of Razor.Tools dependencies included (definitely not intended) since the `Microsoft.AspNetCore.Razor.Design` package was installed as a full dependency and not build-time only.
## Scenario 2

User wants to upgrade their class library to be an executable.
1. They install `Microsoft.NETCore.App`. It installs as a dependency.
2. They try and run.

**Result:** Explosions. `Microsoft.NETCore.App` wasn't installed as type platform and the user did not specify runtimes.

This scenario is slightly less worrisome seeing that the user also needs to update their `project.json` to emit an entry point. However, that's more consistent with old-world experience of having to update your csproj.
## Fix

Should enable a way to install a package as a certain type: `build`, `platform`, `none`. The package could hint at what it thinks it should be installed as via some property in `project.json`. This could present itself as an option when installing the package. If the option is not provided it opts into what the package hinted.

---

Now the wording "type" is a bit overloaded given @joelverhagen's [this issue](https://github.com/NuGet/Home/issues/2476) about adding a new type configuration to a NuGet package so maybe the hint option would be labeled slightly different. Up for suggestions.

/cc @natemcmaster @prafullbhosale @Eilon

**Comment by emgarten** [comment]
@NTaylorMullen is this still needed?

**Comment by NTaylorMullen** [comment]
This was ages ago and now our RazorTooling packages are obsolete. Given that there hasn't been any other needed discussion on this I'd recommend closing.
