### ISSUE TITLE
Spurious error - "Could not locate packages.config" for projects with project.json

### ISSUE THREAD

**Issue by RandomEngy** [NuGet/Home#2913]
I've got some UAP projects that are correctly using the project.json, yet I'm still getting build errors saying 

> Could not locate ...\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.

Everything builds and runs fine, however. Using NuGet package manager 3.4.0.798 on VS 2015 Update 2.

There's a [StackOverflow question about it](http://stackoverflow.com/questions/35487496/build-error-for-uwp-app-microsoft-bcl-build-and-packages-config-next-to-the-proj). They suggest creating a packages.config to match the project.json but that would be a pain to maintain.

**Comment by rrelyea** [comment]
Are you still seeing this problem with NuGet package manager 3.4.4 which released last week?

**Comment by RandomEngy** [comment]
Yes it still happens with 3.4.4.1321 .

**Comment by emgarten** [comment]
This error message comes from a target included in the BCL nupkg, the package itself is incorrectly checking for packages.config. To fix this you will need to remove the dependency or reference the BCL package with `exclude: build`

**Comment by RandomEngy** [comment]
Thanks, that solved it!

**Comment by RandomEngy** [comment]
Though now I get another warning: All projects referencing SomePclProject.csproj must install nuget package Microsoft.Bcl.Build. Apparently setting it with `exclude: build` triggers this warning. Is this another problem with the BCL Build package? how can I get all these warnings cleared up?

**Comment by emgarten** [comment]
@RandomEngy this is another issue with the BCL package.

**Comment by RandomEngy** [comment]
Thanks. Contacted the owners of Microsoft.Bcl.Build about this.

**Comment by kinju4374** [comment]
I am also facing same issue. Can you please suggest how to exclude it? I am not aware how to do it. Also, if I update to Visual Studio Update 3, will it resolve this issue?

**Comment by RandomEngy** [comment]
You can apparently suppress the error by adding `<SkipValidatePackageReferences>true</SkipValidatePackageReferences>` to the at the top of your csproj/vbproj

**Comment by kinju4374** [comment]
ok thanks. Do I need to add this above <Project> tag or inside it?

**Comment by RandomEngy** [comment]
Put it in the first PropertyGroup

**Comment by kinju4374** [comment]
ok but there are total 7 PropertyGroup.Do I need to add in that also? Also, I have one Common project which includes all classes and two background task. Should I add same in that also?

**Comment by zipswich** [comment]
This the .csproj file with "<SkipValidatePackageReferences>true</SkipValidatePackageReferences>" added per the tip of @RandomEngy: 
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <SkipValidatePackageReferences>true</SkipValidatePackageReferences>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <RuntimeIdentifiers>win10-arm;win10-arm-aot;win10-x86;win10-x86-aot;win10-x64;win10-x64-aot</RuntimeIdentifiers>
	...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    ...
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    ...
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x86'">
    ...
  </PropertyGroup>
    ...
  <ItemGroup>
   ...
  </ItemGroup>
  <ItemGroup>
     ...
  </ItemGroup>
    ...
  <PropertyGroup Condition=" '$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' &lt; '14.0' ">
    <VisualStudioVersion>14.0</VisualStudioVersion>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>
```
It works.
