### ISSUE TITLE
Regression in ManifestReader on Unix

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2914]
https://github.com/NuGet/NuGet.Client/commit/02b2c3267a0eaae0ef224148b55b90f3ecf34139 regressed pack from nuspec on Unix.

Trimming slashes from the start of the `src` is incorrect.  A slash here is a semantically different path than without.  All full paths on Unix begin with a slash so this has completely broken our ability to build packages on Unix.

/cc @toddm @rrelyea

**Comment by rrelyea** [comment]
Please determine if this needs to be ported to 3.4.5 as well. Not sure if the first fix made it to 3.4.x

**Comment by toddm** [comment]
Yes, it went into 3.4.4.  I'll port to 3.4.5 after I finish with 3.5.0-beta2.

**Comment by toddm** [comment]
I pushed to 3.5.0-beta2.  CI is still building.

**Comment by ericstj** [comment]
Please let me know when it completes.  Thanks for the quick fix.

**Comment by toddm** [comment]
The CI build finished so you can grab it from our Drops folder.
