### ISSUE TITLE
Port lowercase paths from dev to 3.6b2

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2917]
If we get approval, including for the CLI fix, port https://github.com/NuGet/NuGet.Client/commit/b8372bbc3720b08b08337122d3e5569df3cf7c6c to 3.5b2

**Comment by rrelyea** [comment]
This hasn't been approved yet, email discussion to follow...collecting data for that email.

**Comment by rrelyea** [comment]
Looks like 3.5 rtm should be ok to ship with this in the code base. We may need to understand 1.0 and 1.1 projects in the future...and do old/new behavior.

**Comment by joelverhagen** [comment]
Duplicate of https://github.com/NuGet/Home/issues/2522.
