### ISSUE TITLE
Nuget.exe doesn't handle relative repositoryPath correctly when config file is in parent folder

### ISSUE THREAD

**Issue by brphelps** [NuGet/Home#2918]
I was doing some scripting and wanted to use the RepositoryPath value to locate installed nuget packages. I noticed this (it seems like a bug from a usability perspective):

If you have:

C:\Foo\nuget.config
C:\Foo\Bar\nuget.exe 

The value returned by nuget.exe config RepositoryPath is the same as invoking the same command in this folder structure:

C:\Foo\nuget.config
C:\Foo\nuget.exe 

Even if the nuget.config's path is "..\packages". This means I now need to know the location of the nuget.config in order to appropriately interpret the RepositoryPath, which sucks.

**Comment by zhili1208** [comment]
Yes, this is current design, you need to know the location of nuget.config to resolve the RepositoryPath,  what's your problem? we might can find a workaround for you, is it possible to put nuget.exe and nuget.config in the same folder for your case?

**Comment by brphelps** [comment]
The problem is that "need" doesn't really make sense and breaks encapsulation. If I'm running nuget.exe in an arbitrary subfolder with no knowledge of how containing folders may or may not have their nuget.exe configured, my life has become significantly more complex from this additional information that I need to know.

It seems much more appropriate for NuGet.exe to be responsible for encapsulating all details pertaining to the configuration file location, since it is the actor responsible for locating the configuration in potentially unexpected parent directories. Exposing something that lets consumers be agnostic of the configuration location seems like a minimum, but my ideal would be that any relative path settings would be coalesced into either (a) the correct relative path to nuget.exe or (b) an absolute path.

The basic principle here is that if your thing is going to do magic, it needs to do the magic consistently :). (The magic in question is configuration file location outside of current directory scope)
