### ISSUE TITLE
Do we support adding reference to javascript project? It doesn't work now

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#292]
Install entityframework into javascript project.
nuget message shows package be installed but it's not.

expect: ??? do we still support this in dev14
actual : reference can't be added to javascript project

**Comment by deepakaravindr** [comment]
I verified that the actual behavior is the expected behavior. Note that while the dll cannot be added, the package can be installed successfully. The current behavior was the behavior in Dev12 as well
