### ISSUE TITLE
CLI restore fails for dependencies to csproj (works in IDE)

### ISSUE THREAD

**Issue by AaronRM** [NuGet/Home#2920]
Repro steps (VS 2015 with .NET Core RC2 latest release, dotnet cli version 1.0.0-preview1-002702):
1. Create .NET Core project
2. Edit project.json to target net452/net46
3. Add a .NET 4.5/4.6 ClassLibrary C# project to the solution  (ClassLibrary1)
4. In VS, add a project reference to library added in step 3. This will give you something like the following in project.json:
    "dependencies": {
       "ClassLibrary1": {
         "target": "project"
       }
     }
5. Run 'dotnet restore'

RESULT
error: Unable to resolve 'ClassLibrary1' for '.NETFramework,Version=v4.6'.

The package restore from the IDE _works_ in this case, but the command line restore fails.

**Comment by emgarten** [comment]
`dotnet restore` does not support msbuild since there is no cross platform msbuild support yet. If you are running on windows you may use NuGet.exe to restore your solution. NuGet.exe is a superset of dotnet restore with msbuild support.
