### ISSUE TITLE
nuget.exe restore doesn't produce .props and .targets files for .msbuildproj (regression in v3.3.0-3.4.4 upgrade)

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#2921]
Similar to #2711, we have an .msbuildproj project that loads in VS and at the command line, and uses project.json. But nuget 3.4.4 no longer creates msbuild import files on restore the way 3.3.0 did.

Can we please get this working again? Preferably in some generalized way so that it Just Works for all the project types that support it, and keeps working consistently as nuget.exe evolves?

**Comment by rrelyea** [comment]
Thanks for the report. This sounds similar to the problem we had with .nuproj -- which we fixed late in the game, but didn't have time to solve generically. 
Putting in 3.4.5 now...we'll discuss if it can catch that release.
@emgarten

**Comment by rrelyea** [comment]
Hopefully, 3.6 beta.

**Comment by emgarten** [comment]
This should be fixed in the latest version of nuget.
