### ISSUE TITLE
NuGet Command Line - Could not find file (but file exists)

### ISSUE THREAD

**Issue by rbravo** [NuGet/Home#2924]
I'm using nuget command line for updating my packages hosted on our private NuGet Server. These packages have Content files inside, so I chose to update packages using the Command Line tool instead of the Visual Studio extension because on VS it takes too long to update content files packages (I think it's because VS has the Solution View, and it tries to refresh it every time, so when I'm using nuget on command line and with visual studio closed it's super fast).

The command I'm using is: 
`nuget update .\Cabinet\packages.config -Id QCPro.MVC -Verbose`
It works fine most of the time. But sometimes NuGet stops the update saying that
`Could not find file 'C:\dev\Cabinet\Cabinet\Scripts\cart.js'`
But the file is there! The path is correct! 

To get it going I open the .csproj and remove the reference to this file there. Then I try running the command again. It stops on some other random file with the same message:
`Could not find file 'C:\dev\Cabinet\Cabinet\Content\custom.css'`
And this file is there too, the path is correct! I don't know why this is happening. There is nothing special with these files. And I see no pattern on the conflicted files. 

Any ideas on what's going on?

**Comment by rrelyea** [comment]
Thanks for the report. 

What version of NuGet.exe are you using?
V3.4.4 is the latest, please try with that. (Download available from http://dist.nuget.org/index.html)

Are you using integrated source control in VS? What type of source control?
What version of VS?

**Comment by rrelyea** [comment]
@rbravo - ping. please respond with details.
(also, please try 3.5.0-Beta2 of NuGet.exe -- which just shipped today)
Closing until we get a response with more data.
