### ISSUE TITLE
NuGet's detection of missing packages on project load slows down project loading

### ISSUE THREAD

**Issue by hach-que** [NuGet/Home#2925]
We're profiling Visual Studio to find out why it's running slow for us, and we noticed this when it's loading all the projects:

![image](https://cloud.githubusercontent.com/assets/504826/15885484/d769542e-2d9a-11e6-990d-faf50f742f45.png)

It looks like every time a project loads (which happens quite frequently when the solution is being loaded), it recursively scans through all the files in package directories and possibly the solution as well.

We don't actually need this functionality on the solution because we have a PowerShell script that developers run before hand which actually restores any missing packages, however there doesn't appear to be anyway to turn this functionality off.

We'd like either an option in Visual Studio to disable this behaviour, or some solution level configuration file that allows us to disable it per-solution.

**Comment by rrelyea** [comment]
Thanks for the profiling. We hope to investigate soon.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/4037dd24f1ff2f79002c63cf545e6ce72c8d5c31
