### ISSUE TITLE
PackageManagerConsole cannot see some packages that nuget.exe or VS can - teamcity server

### ISSUE THREAD

**Issue by sutarmin** [NuGet/Home#2926]
I use VS 2015 update 2 with NuGet Package Manager 3.4.4. Also I have own Nuget server on Teamcity 9.1.7. I request avaliable packages through Package Manager Console (from VS) with command `Get-Package -ListAvailable`. There I see that some packages are missing.
At the same time:
1. When I'm requesting package list from command line with `nuget list` I see these packages.
2. When I'm installing one of available packages from VS, it also successfully installs missing package as a dependency.

**Comment by rrelyea** [comment]
Is this a regression with 3.4.4 of package manager? Which version worked differently?
Which version of NuGet.exe are you using?
Do you see the same behavior with NuGet.exe v3.4.4 (see http://dist.nuget.org/index.html)

**Comment by sutarmin** [comment]
@rrelyea,  I'm already using v3.4.4 of NuGet.exe. And I didn't try to reproduce it with other versions of extention or NuGet.exe. I'll try if it needed.

**Comment by rrelyea** [comment]
Just trying to help understand what happened here. Did nuget.exe break this? Is something wrong with your server / network? other? If you could point to older versions that this worked with, it will help us understand what the cause might be.

**Comment by Becklighter** [comment]
I am having the exact same problem. The version of NuGet Package Manager I have is 3.4.3, in VS 2015.
I also have NuGet Package Manager 2.8.50926.663 for VS 2013 and it can view all of the packages.

My version of Nuget.exe is 2.8.60717.93

Update:
I just updated my Nuget.exe to version 3.4.4.1321, and I get the same result.
VS 2013 with Package Manager 2.8.50926.663 works.
VS 2015 with Package Manager 3.4.3 does not work.

Discovered:
VS 2015 with Package Manager 3.0.0 works.

**Comment by emgarten** [comment]
Closing due to lack of feedback in this area.
