### ISSUE TITLE
Upgrade NuGet in 3.5.0-beta2 and dev branches to use latest corefx builds

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2929]
Per my email details.

**Comment by rrelyea** [comment]
Updated versions appear good. As long as tests pass, Zhi will integrate into "release-3.5.0-beta2" branch very soon.

**Comment by zhili1208** [comment]
Checked in the change to "release-3.5.0-beta2", waiting for CI

**Comment by zhili1208** [comment]
all packages are ready, working on pushing them to myget

**Comment by zhili1208** [comment]
Pushed all packages to MyGet, sent a PR to update Cli version https://github.com/dotnet/cli/pull/3441

**Comment by rrelyea** [comment]
Needed some other CLI changes, so went in with @eerhardt's change:
- Commit: https://github.com/dotnet/cli/commit/66f1a07c08f4c85a3fb48a01793dfd030bada4d6
- PR: https://github.com/dotnet/cli/pull/3455
