### ISSUE TITLE
NuGet V3 Client Telemetry Capabilities

### ISSUE THREAD

**Issue by RanjiniM** [NuGet/Home#293]
NuGet V3 client should have capability to record the following information

1. Which project type uses NuGet
2. What is the operation performed (Install, Uninstall, Update etc)
3. What is the client invoking the operation (Dialog, Console etc)

**Comment by harikmenon** [comment]
Closing this issue out as a duplicate https://github.com/NuGet/Home/issues?q=is%3Aissue+is%3Aopen+telemetry+label%3AType%3AFeature
