### ISSUE TITLE
re-Publish Nuget.CommandLine 3.4.4 to Nuget.org

### ISSUE THREAD

**Issue by giggio** [NuGet/Home#2931]
Right now the latest version available on Nuget for the package `Nuget.CommandLine` is `3.4.3`, while `3.4.4` [is already released](https://dist.nuget.org/index.html).
For some reason a `3.4.4-rtm-final` version was [published](https://www.nuget.org/packages/NuGet.CommandLine/3.4.4-rtm-final), but that version makes it a pre-release.

**Comment by rrelyea** [comment]
This was done a while ago.
