### ISSUE TITLE
(CLI dev branch remaining only) Tweak serviceable support in nuspec to not require a new xmlns uri for dotnet pack --serviceable

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2938]
To increase NuGet ecosystem happiness, we're tweaking our behavior here.
This will make old NuGet clients deal with these packages in much better ways.

**Comment by rrelyea** [comment]
please keep this open until you get it into the "dev" cli branch.

**Comment by toddm** [comment]
It's in preview2 which will flow to rel/1.0.0 so this is now done.
