### ISSUE TITLE
Case sensitivity issue

### ISSUE THREAD

**Issue by sebastienros** [NuGet/Home#2939]
Repro from customer https://github.com/andyalm/netcoreapp-netstandard-issue

If `NETStandard` is wrongly cased, restore fine, but there error on build:

```
error: Failed to resolve conflicts for .NETCoreApp,Version=v1.0.
error: Unable to satisfy conflicting requests for 'System.Buffers': System.Buffers (>= 4.0.0-rc2-24027) (via package/Microsoft.NETCore.App 1.0.0-rc2-3002702), System.Buffers (>= 4.0.0-rc2-24027) (via package/System.IO.Compression.ZipFile 4.0.1-rc2-24027)
```

**Comment by emgarten** [comment]
This looks related to https://github.com/NuGet/Home/issues/2901

**Comment by sebastienros** [comment]
Right

**Comment by teilin** [comment]
I think I have the same issue as this one, is this solved by the fix in the Nuget Client that is referenced?

**Comment by emgarten** [comment]
@teilin there have been several fixes for package id casing, not all of them are in released versions of NuGet yet.

**Comment by teilin** [comment]
Okey, thanks. Is it a way to specify a nuget.exe or something somewhere? In that case so I can take the latest, build it and check if it is the problem I actually have? So to be clear, what I hope is that it is some way to let dotnet restore use a Nuget.exe that I build.

**Comment by emgarten** [comment]
@teilin get the latest or latest nightly build from: https://dist.nuget.org/index.html 

nuget.exe restore can be used in place of dotnet restore

**Comment by teilin** [comment]
Thanks @emgarten
