### ISSUE TITLE
nuget setApiKey doesn't appear to be setting api key

### ISSUE THREAD

**Issue by daz10000** [NuGet/Home#2940]
I use nuget periodically to push packages and I recently installed on a new machine with latest version of nuget, and I've lost a few hours to a series of bugs.   See the session below, but TL;DR - setApiKey doesn't appear to actually save a usable apiKey on my machine, and it wasn't till I explicity supplied apikey on command line that nuget would do anything.

--- current version of nuget
$ nuget
NuGet Version: 3.4.4.1321
usage: NuGet <command> [args] [options]

--- have previously saved apikey,  try to push a package
$ nuget push fss_postgres.1.3.1.0.nupkg  -Source https://www.nuget.org/api/v2/package
WARNING: No API Key was provided and no API Key could be found for 'https://www.nuget.org/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
Pushing fss_postgres.1.3.1.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Unauthorized https://www.nuget.org/api/v2/package/ 1072ms
Please provide credentials for: https://www.nuget.org/api/v2/package
UserName:

---- ^^^^^^^^^^ fails and asks for auth

---- set my api key
$ nuget setApiKey xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -Source https://www.nuget.org/v2/api/packages
The API Key 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' was saved for 'https://www.nuget.org/v2/api/packages'.

---- try pushing again
$ nuget push fss_postgres.1.3.1.0.nupkg  -Source https://www.nuget.org/api/v2/package
WARNING: No API Key was provided and no API Key could be found for 'https://www.nuget.org/api/v2/package'. To save an API Key for a source use the 'setApiKey' command.
Pushing fss_postgres.1.3.1.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Unauthorized https://www.nuget.org/api/v2/package/ 941ms
Please provide credentials for: https://www.nuget.org/api/v2/package
UserName:

------ ^^^^^^^^^^^^^^^ still fails to use key and asks for auth credentials (which are shown plaintext on screen and fail)

If I push with api key explicitly it works (fails here b/c already pushed)
$ nuget push fss_postgres.1.3.1.0.nupkg xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx -Source https://www.nuget.org/api/v2/package
Pushing fss_postgres.1.3.1.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 1084ms
Response status code does not indicate success: 409 (A package with id 'fss_postgres' and version '1.3.1' already exists and cannot be modified.).

**Comment by zhili1208** [comment]
nuget.exe saved ApiKey in nuget.config but it's not used by push command. this is dup bug. https://github.com/NuGet/Home/issues/2627

**Comment by daz10000** [comment]
Thanks! - yes I can confirm that it did save the key, so it's the push command that's buggy.  Good luck wiping it out,
