### ISSUE TITLE
Unable to install package with stable version but prerelease dependencies

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2944]
Repro steps:
1. Create a package with prerelease dependencies using **project.json and dotnet pack**
2. Place the package in a folder and configure VS to use this folder as a local repository
3. Create a project with **packages.config**. Using package manager console/UI add the package to the project.

Error (for example):
`Unable to find a version of 'NuGet.Protocol.Core.v3' that is compatible with 'NuGet.Client.Staging 1.0.0 constraint: NuGet.Protocol.Core.v3 (>= 3.5.0-beta-final)'.`

**Comment by rrelyea** [comment]
sounds like a bug in dotnet pack. I think we shouldn't let you build a "final" version of a package if it has prerelease dependencies.

**Comment by emgarten** [comment]
This is fixed for PackageReference. We should determine if we want to fix this for packages.config, or leave it as is.

**Comment by nicbavetta** [comment]
@emgarten What needs to be added to PackageReference to get this to work?

**Comment by emgarten** [comment]
@nicbavetta with PackageReference it works by default. To find out more on converting take a look at https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by hamjo** [comment]
Any update on the status?

**Comment by WojciechNagorski** [comment]
Any update? 
This problem blocks me in two new features of BenchmarkDotNet.

I would like to use `Microsoft.Diagnostics.NETCore.Client`:
https://github.com/dotnet/BenchmarkDotNet/issues/1315
and `System.CommandLine`:
https://github.com/dotnet/BenchmarkDotNet/pull/1037

All interested: @AndreyAkinshin @adamsitnik @sywhang @jonsequitur

**Comment by adamsitnik** [comment]
@rrelyea any update on this? It's blocking us in BenchmarkDotNet

**Comment by rrelyea** [comment]
If this is blocking you, please be specific of which scenario is broken... it sounds like a few new issues got spun off this one.

Are you using packages.config? Do you have unique version upper bounds declared, etc...

**Comment by adamsitnik** [comment]
> If this is blocking you, please be specific of which scenario is broken... it sounds like a few new issues got spun off this one.

@rrelyea sure!


1. Create a new .NET Standard library
2. Add a dependency to a preview package. [System.CommandLine.Experimental](https://www.nuget.org/packages/System.CommandLine.Experimental/0.3.0-alpha.19577.1) is a good example
3. Create a NuGet package using `dotnet pack`
4. Publish the package to some nuget feed
5. Create a new Full .NET Framework Console App using Visual Studio 2017|2019
6. Try to install the new NuGet package (the app must be using **packages.config** file)
7. It fails with `Unable to resolve dependency` error				
`

Example:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.CommandLine.Experimental" Version="0.3.0-alpha.19577.1" />
  </ItemGroup>
</Project>
```

```cmd
dotnet pack -c Release
```

I've published it to NuGet.org: https://www.nuget.org/packages/net_std_lib/ and tried to install in .NET 4.6.1 app using Visual Studio 2017 and 2019 with **include prerelease unchecked**

VS 2017

![obraz](https://user-images.githubusercontent.com/6011991/70469111-b921c180-1ac8-11ea-9bce-0d6b0e4ab78f.png)

VS 2019

![obraz](https://user-images.githubusercontent.com/6011991/70469139-c63eb080-1ac8-11ea-8013-783c562e54e7.png)

**Comment by aortiz-msft** [comment]
Thank you for your feedback. We appreciate you letting us know about the problem. Based on input from the community, this is currently low priority for us. We will look at this again if the issue is upvoted by the community. Also, we recommend moving from packages.config to PackageReference if possible.
