### ISSUE TITLE
Establish consistent detail in issues/pr/commits

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#2948]
In general I have a hard time following NuGet issues/PR/commits.  The descriptions are one line and usually just say what is being done which is not helpful since I can see the same from the commit.  The purpose of the issue, commit description, pr is to give more detail.   Often times I'm looking to find a specific commit that regressed me, I find it and its a tiny description that doesn't indicate anything about what the work was actually trying to do.  I also see the opposite, where I know a lot about why a change is being made, but the description that actually gets commited does not include any of this detail.

I don't want to pick on individual users here, but I'd just like to see some more consistency across NuGet and have that be part of your approval process.

/cc @rrelyea @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Sure :)

**Comment by rrelyea** [comment]
Great feedback. Yes, we are actively working on improving this.
Love it!

**Comment by ericstj** [comment]
Here's the guidance we have for corefx, in case that helps: https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/contributing.md#commit-messages

**Comment by emgarten** [comment]
Fully agree with this, I'm going to close this out because it doesn't need a tracking issue. We'll work to ensure that git commit messages are improved during the PR process going forward.
