### ISSUE TITLE
VS API: AppInsights fails to install as part of a WCF Service Application project template

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#295]
1. Open VS (make sure PMC is closed and NuGet is not loaded)
2. Sign into VS 
3. File > New Project
4. Create a 'WCF Service Application'
5. Check the application insights box to add the telemetry package

This may be related to the VSSolutionManager changes.

---------------------------
Microsoft Visual Studio
---------------------------
Could not add Application Insights to project.  
Failed to install package: 
Microsoft.ApplicationInsights.Web 
with error: 
Unable to locate the solution directory. Please ensure that the solution has been saved.
Successfully created resource 'WcfService4' in Azure.

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/0edb608ce9c507d9194214f2e89ebfe3412373a7
