### ISSUE TITLE
Add capability for local VSIX builds to work with with VS projects

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#2951]
Local VSIX builds when installed to VS give assembly load errors when creating projects, because NuGet.VisualStudio.Interop is not strong named in local builds, and the VS templates require strong naming. The workaround is to replaced all references to "NuGet.VisualStudio.Interop Version=etc..." With "NuGet.VisualStudio.Interop" in all .template files (in archives) in the product directory and local app data VS directory. It would be good to remove this pain point.

**Comment by dmitriyse** [comment]
You can do this right now:
1) extract public key from any signed nuget assembly 

``` CMD
sn -e Nuget.*.dll nuget-pub.snk
```

2) pass this file to build script

``` PowerShell
 .\build.ps1 -configuration release  -buildNumber 7000 -SkipDev15 -SkipTests -NuGetPFXPath:"
c:\snk\nuget-pub.snk" -MSPFXPath:"c:\snk\nuget-pub.snk"
```

3) allow .NetFramework to use delay-signed nuget libraries - create and apply AllowNuGetDelaySigned.reg

``` Ini
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\StrongName\Verification\*,B03F5F7F11D50A3A]
[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\StrongName\Verification\*,B03F5F7F11D50A3A]
```

This helps, I checked.

Please consider to add some build instruction and mention about signing importancy.
After that issue can be closed.
