### ISSUE TITLE
Specific response from nuget server causes VS to hang

### ISSUE THREAD

**Issue by hvanbakel** [NuGet/Home#2954]
Today I found an issue where I’m able to make VS hang, which has to do with a ‘nuget mirror’ that we have for our local nuget server. We do this because our nuget server is on the other side of the country and this decreases latency (it also reduces the load significantly on the company wide nuget server). 

VS 2015 has diminished the need for this already significantly by reducing the number of calls to NuGet so that’s great. However we have this in place already so we plan to keep using it.
The scenario is as follows:
1.       I open visual studio
2.       I search for a package, that hits the ‘mirror’
3.       Visual studio hangs
I’ve attached the fiddler trace of the request that I think causes this. 
[VS Hang after nuget call.zip](https://github.com/NuGet/Home/files/309753/VS.Hang.after.nuget.call.zip)

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
