### ISSUE TITLE
Performance: Package Manager Console init.ps1 load time

### ISSUE THREAD

**Issue by hvanbakel** [NuGet/Home#2956]
In VS2015, when you work on a project with a lot of nuget references, switching to the package manager console is blocking Visual Studio. While it blocks, the entire packages folder is being scanned which (depending on the number of packages) can take a while.

Could this be made non-blocking or done in the background when the solution opens?

**Comment by emgarten** [comment]
How long does it take for your solution? How many of the packages have _init.ps1_ files under _tools_?

**Comment by hvanbakel** [comment]
I'm not talking about reinstalling, only a very small percentage will be outdated and need to be restored. A very small percentage will have scripts in their package, this is just to bring parts of the system together in a main solution.

**Comment by emgarten** [comment]
_Init.ps1_ scripts for each package in the solution are executed when the package manager console is opened, this loads up any powershell helper modules needed by the packages.

The core actions that NuGet performs when opening the window are minimal, but potentially the packages you are using could have very slow init.ps1 scripts. It is also possible that your own powershell settings are slowing things down.

In the case of init.ps1, Visual Studio's DTE API is passed into the script to give the script full access to Visual Studio. This can only be used on the UI thread as per the Visual Studio threading rules, which means NuGet cannot put this work on the background thread unfortunately.

It's possible you are hitting a delay from something else. As a test you could try deleting all init.ps1 scripts from your packages folder and checking to see if the performance improves.

**Comment by hvanbakel** [comment]
So here's an example of the problem I'm seeing. I've attached a solution that has a small number of packages. To reproduce, open the solution in 2015 and restore all packages.

Then in 2015 switch between some window and the package manager console. What will happen in 2015 is that it will go through the packages folder in order to find out if it has everything it needs. However, say you have a package that a lot of other packages are dependent upon, you can possibly suffice by scanning this folder once, not once for every package that has a dependency on that. As the latter will cause the number of disk operation to grow exponentially as packages are added. VS 2013 did this is a whole different way resulting is significantly less IO..

If I'm correct, the installed packages can be seen as a directed graph where all nodes will have to be visited at most once. You want to know if the package is there, what version it is and what it's dependencies are. But when you hit a node that you've already visited you can skip checking all of its children.

[ConsoleApplication1.zip](https://github.com/NuGet/Home/files/319347/ConsoleApplication1.zip)

[2013 vs 2015 console open.zip](https://github.com/NuGet/Home/files/319345/2013.vs.2015.console.open.zip)

**Comment by emgarten** [comment]
The logs and repro solution are very helpful, thank you! Which version of NuGet do you have installed in VS 2015?

**Comment by hvanbakel** [comment]
I have 3.4.0.798 installed.

**Comment by emgarten** [comment]
It looks like this can be improved, the root issue here is that NuGet is searching for each package within each sub folders. VS 2013 did this also in most scenarios, however it looks like it was optimized in the Powershell launch/init.ps1 scenario and VS 2015 is missing that.

How many packages does your solution contain and how long does it take Powershell to load?

In your VS 2015 log it shows 22 packages loading in under half a second.

**Comment by hvanbakel** [comment]
300+ packages with a lot of dependencies between the packages. 
Switching to the console takes 14 seconds in which it completely freezes.

**Comment by emgarten** [comment]
I've added a fix to both improve the folder search, and also limit the number of times a package is read to just once per target framework/id/version. Most of the time here was coming from reading packages per project in order to sort them by dependency order.

I tested a solution with 10 projects and the same 500 packages in each packages.config. 
Previous: 132 seconds
Now: 10 seconds

**Comment by hvanbakel** [comment]
Thanks Justin, that sounds like a major improvement. I'll test it as soon
as it gets wrapped in a version of niet client.

**Comment by hvanbakel** [comment]
I just checked the RC channel. What a difference, great work!
