### ISSUE TITLE
Fallbacksource seems to be a source, not a fallback source

### ISSUE THREAD

**Issue by victorhurdugaci** [NuGet/Home#2959]
Here's what I have. (1) a project created by VS with RC2 tool and (2) a folder (`D:\home\testrestore\final`) with all the nupkgs that the app requires (you can get them from `\\aspnetci`).

Then I try the following (each time I clear all the caches before running):
1. `dotnet restore --source https://api.nuget.org/v3/index.json`
2. `dotnet restore --source D:\home\testrestore\final`
3. `dotnet restore --source D:\home\testrestore\final --source https://api.nuget.org/v3/index.json`
4. `dotnet restore --source D:\home\testrestore\final --fallbacksource https://api.nuget.org/v3/index.json`

and see the following results (averaged over 10 runs each):
1. 87s
2. 69s
3. 88s
4. 87s 

1 and 2 are expected. 3 is a bit confusing because it's not clear in which order the sources are used (does it check all of them even though it finds the package on in the first? if that's the case, how is first defined?). 

However, I was expecting the 4th restore command to use the `--fallbacksource` only when it cannot find a package in the feeds specified as `--source`. Since all the packages are in the local folder (restore 2 is successful), and my `project.json` has no floating version, I was expecting to not hit `nuget.org` at all. However, in the log I see that it goes to `nuget.org` and the restore time confirms that.

Is my expectation wrong or fallbacksource does something unexpected?

If you need it, the dotnet version is 1.0.0-preview1-002702 (the public one) and the `project.json` file is:

``` json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by emgarten** [comment]
NuGet doesn't really support `fallbacksource` it just adds as a normal source. I believe this was done initially to support the DNU fallbacksource parameter. In DNU I understood this parameter to be used only if no sources were specified in nuget.config. At this point I think it should be removed to avoid confusion.

Non-http repositories are always checked first, so there may be an issue here if it is hitting nuget.org. However if the local folder is missing an exact version asked for by any of the packages, even if that package doesn't end up in the lock file at the end, it could need to go online to make sure there isn't a better match.

For reference this is where we check local first:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.DependencyResolver.Core/Remote/RemoteDependencyWalker.cs#L559-L567
