### ISSUE TITLE
Options Dialog: Microsoft and .NET displays as enabled when disabled

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#296]
1. Open the options dialog from PMC
2. Disable all sources
3. Click OK
4. Re-open the options dialog

Expected:
Microsoft and .NET will be disabled

Actual:
Microsoft and .NET shows as enabled and appears in the PMC drop down list

**Comment by zhili1208** [comment]
it's fixed by https://github.com/NuGet/NuGet.Configuration/commit/d770e442f413a1130897e258222c59657c9777a8
