### ISSUE TITLE
dotnet restore timeout

### ISSUE THREAD

**Issue by ssanp** [NuGet/Home#2961]
Hi,
I just installed rc2 for my visual studio 2015 on my windows 7 laptop, i keep getting timeout issues with multiple projects, the projects work fine on other machine except my local laptop, i am not sure what the issue is, below are the time out messages

`An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/autofac/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.testing.abstractions/1.0.0-preview1-002702/microsoft.extensions.testing.abstractions.1.0.0-preview1-002702.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.collections.concurrent/4.0.10/system.collections.concurrent.4.0.10.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.collections.concurrent/4.0.11-beta-23516/system.collections.concurrent.4.0.11-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.collections.nongeneric/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.collections.specialized/4.0.0/system.collections.specialized.4.0.0.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.componentmodel.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.componentmodel/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.debug/4.0.11-beta-23516/system.diagnostics.debug.4.0.11-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tools/4.0.1-beta-23516/system.diagnostics.tools.4.0.1-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracesource/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.globalization/4.0.11-beta-23516/system.globalization.4.0.11-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.io.compression/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.io.filesystem/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.io/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.net.nameresolution/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.net.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.net.security/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.net.sockets/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit.ilgeneration/4.0.0/system.reflection.emit.ilgeneration.4.0.0.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit.ilgeneration/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit.lightweight/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit/4.0.0/system.reflection.emit.4.0.0.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit/4.0.1-beta-23516/system.reflection.emit.4.0.1-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.emit/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.typeextensions/4.0.0/system.reflection.typeextensions.4.0.0.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.typeextensions/4.1.0-beta-23516/system.reflection.typeextensions.4.1.0-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection.typeextensions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.reflection/4.1.0-beta-23516/system.reflection.4.1.0-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.security.cryptography.algorithms/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.security.cryptography.x509certificates/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.text.encoding/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/4.0.10/system.text.regularexpressions.4.0.10.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/4.0.11-beta-23516/system.text.regularexpressions.4.0.11-beta-23516.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.text.regularexpressions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.threading.tasks/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.threading.thread/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.threading.threadpool/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/system.threading.timer/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/xunit.assert/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/xunit.core/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://api.nuget.org/v3-flatcontainer/xunit.runner.reporters/2.1.0/xunit.runner.reporters.2.1.0.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/autofac/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/castle.core.netcore/3.3.4-beta8/castle.core.netcore.3.3.4-beta8.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.netcore.dotnethost/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/moq.netcore/4.4.0-beta8/moq.netcore.4.4.0-beta8.nupkg'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.collections.nongeneric/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.componentmodel.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.componentmodel/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.diagnostics.tracesource/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.io.compression/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.io.filesystem/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.io/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.net.nameresolution/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.net.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.net.security/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.net.sockets/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.emit.ilgeneration/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.emit.lightweight/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.emit/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.primitives/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.typeextensions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.runtime.extensions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.runtime.interopservices.runtimeinformation/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.security.cryptography.algorithms/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.security.cryptography.x509certificates/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.encoding/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.regularexpressions/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.threading.thread/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.threading.threadpool/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.threading.timer/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/xunit.assert/index.json'. The request will now be retried.
An error was encountered when fetching 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/xunit.core/index.json'. The request will now be retried.
Failed to retrieve information from remote source 'https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/index.json'.
Failed to retrieve information from remote source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.typeextensions/index.json'.
Failed to retrieve information from remote source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.runtime.extensions/index.json'.
Failed to retrieve information from remote source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.regularexpressions/index.json'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/system.runtime.extensions/index.json' has timed out after 100000ms.
The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.reflection.typeextensions/index.json' has timed out after 100000ms.
The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.runtime.extensions/index.json' has timed out after 100000ms.
The HTTP request to 'GET https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.regularexpressions/index.json' has timed out after 100000ms.

I tried manually updating the packages but still get the same issue.

Any advice would be helpful!

Thanks!`

**Comment by kgrosvenor** [comment]
What was the fix??
