### ISSUE TITLE
Uninstalling NuGet.Server gives error message in output about Routes.cs

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#2962]
NuGet version: 
dev:3.5.0.1479; release-3.4.4:3.4.4.1321; release-3.4.5:3.4.5.1450; release-3.5.0-beta2:3.5.0.1480

Repro steps:
1.Create MVC or Empty web application.
2.Open NuGet UI and navigate to Browse tab
3.Install "NuGet.Server" package
4.Navigate to Installed tab, uninstall "NuGet.Server" package.

The same results as iPhone->Blank App, uninstall "BugSense.Xamarin.iOS" package.

Expected: Show uninstall package successful message in "Package Manager".
![1](https://cloud.githubusercontent.com/assets/12129698/16002803/123bdbae-318c-11e6-9aac-88f387fb7b87.PNG)

Actually: After click Uninstall button, the output window automatically turn into another option: "IntelliSense".
![capture](https://cloud.githubusercontent.com/assets/12129698/16002895/8e96d726-318c-11e6-8d9b-62397ed770aa.PNG)

Message:
[Failure] Could not find a part of the path 'C:\school\WebApplication1\DataServices\Routes.cs'.

**Comment by maartenba** [comment]
Not familiar with the BugSense.Xamarin.iOS package

**Comment by rrelyea** [comment]
I think that you should just read that as...
expected behavior: no error on uninstall.

**Comment by maartenba** [comment]
Relates to https://github.com/dotnet/roslyn/issues/8850 (at least the showing errors portion)

Seems related to content file being removed, an event being triggered with IntelliSense, and then IntelliSense no longerfinding the content file (which was rightfully removed).

(wondering if https://github.com/NuGet/NuGet.Client/pull/739 could fix this?)
