### ISSUE TITLE
Nuget pack .csproj ignores .nuspec file

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2965]
This is with v3.5.0.1365. I'm pretty sure the old behaviour was to use the .nuspec file with the same name as the project file (ie nuget pack blah.csproj would also include directives from blah.nuspec).

Am I missing something?

**Comment by wbradney** [comment]
Looking at the Nuget.Core code (PackCommandRunner), it seems that you can build a package from one of (exclusively) the project.json file, the proj file, or the .nuspec file. Is this a regression? I'm pretty sure that in prior versions specifying the proj file would also include the .nuspec directives if present. Is there a new way to include additional supplemental files in a .nupkg?

**Comment by wbradney** [comment]
Could be the same problem as issue 2726? There's a repro over there.

**Comment by wbradney** [comment]
Another data point is that I've noticed that since switching to project.json my internally generated packages no longer show our company logo in Visual Studio (this is specified in the .nuspec file).

**Comment by rohit21agrawal** [comment]
@wbradney there is a similar issue we are tracking , and the issue is summarized as follows:

3.4.4 -> gets info from nuspec, dependencies not included
3.5.0-beta2 -> ignores nuspec, dependecies included
nightly build -> same as 3.4.4 (gets info from nuspec, no dependencies)

https://github.com/NuGet/Home/issues/3145

**Comment by wbradney** [comment]
Any update on the ETA for this fix? RC1 doesn't seem to resolve it.

**Comment by rohit21agrawal** [comment]
@wbradney what scenario are you trying to use here? If you have a csproj + project.json, then we will ignore the nuspec. that is by design.

**Comment by wbradney** [comment]
Ok, I wasn't aware of that. So what's the new way to specify the stuff that used to be in the nuspec file (ie additional `<files>`, `<iconUrl>`)?

**Comment by wbradney** [comment]
OK, so I found the new documentation [here ](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json)and it seems like these options now belong in the project.json file, which makes perfect sense. However I'm struggling to find the right incantations needed.

For example, where I used to have something like this in the nuspec:

```
  <files>
    <file src="..\RefLib\bin\$configuration$\RefLib.dll" target="build" />
    <file src="$id$.targets" target="build" />
  </files>
```

This in the project.json doesn't seem to do it, either (nothing gets added under `build`in the .nupkg).

```
  "files": {
    "mappings": {
      "build": {
        "include": [ "../RefLib/bin/Debug/RefLib.dll",
                     "NugetBuildRefs.targets" ]
      }
    }
```

[I deliberately removed the $...$ property references in case they were not supported]

Case #2726 has a repro of what I'm trying to accomplish. I raised that case not understanding that the nuspec is _supposed_ to be ignored with project.json.

**Comment by rohit21agrawal** [comment]
can you try and change include to includeFiles ?

**Comment by rohit21agrawal** [comment]
@wbradney Also use a backslash instead of a forward slash on a windows system.

**Comment by wbradney** [comment]
"includeFiles" didn't seem to change anything. Still no "build" folder in my package.

Double backslashes instead of single forward slashes didn't seem to change anything, either.
Single backslashes get me this:

```
Error reading 'C:\...\NugetBuildRefs\NugetBuildRefs\project.json' at
   line 17 column 32 : Bad JSON escape sequence: \R. Path 'files.mappings.build.includeFiles', line 17, position 32.
    Bad JSON escape sequence: \R. Path 'files.mappings.build.includeFiles', line 17, position 32.
```

**Comment by rohit21agrawal** [comment]
can you attach your repro project here?

**Comment by wbradney** [comment]
Sure
[NugetBuildRefs.zip](https://github.com/NuGet/Home/files/420992/NugetBuildRefs.zip)

**Comment by wbradney** [comment]
I noticed as soon as I posted that the "files" section should be under 
"packOptions". D'Oh!

**Comment by rohit21agrawal** [comment]
haha..glad it fixed the problem! please close the issue if you are satisfied with the resolution :)

**Comment by wbradney** [comment]
Thanks for the help

**Comment by wbradney** [comment]
@rohit21agrawal : is there a way to use MSBuild properties in the project.json eg. $(Configuration) in the project.json file?

$id$ seems to work for the project name, but $configuration$ produces an error at pack time.

**Comment by wbradney** [comment]
Actually, $id$ doesn't work either

**Comment by rohit21agrawal** [comment]
no they don't . very soon we are going to be moving all of project.json to csproj in order to enable these scenarios.

**Comment by wbradney** [comment]
Ok, I figured that would be the case. Thanks
