### ISSUE TITLE
project.json: nuget does not include native libs in build

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#2966]
This is with 3.5.0.1365
The repro is attached. The example has a "wrapper" package for SQLite (which requires interop assemblies in the native bin folders). When a project.json-equipped project references the wrapper package, the native binaries are not copied. A packages.config-equipped project works fine.
[NugetSqliteRef.zip](https://github.com/NuGet/Home/files/312526/NugetSqliteRef.zip)

**Comment by emgarten** [comment]
Your nuspec is excluding build assets from the SQLite package, is this where you are expecting the native binaries to come from?

``` xml
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="System.Data.SQLite.Core" version="1.0.101" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

Try changing this to:

``` xml
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="System.Data.SQLite.Core" version="1.0.101" />
      </group>
    </dependencies>
```

**Comment by wbradney** [comment]
You're talking about the .nuspec that ends up in the .nupkg file, right?
That actually explains why it doesn't copy the build files, but my wrapper project doesn't have a .nuspec file to control this. I guess that means the bug is in nuget pack?

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
