### ISSUE TITLE
Move NuGet to depend on v1.0 of CoreFX/CoreCLR/etc...

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2967]

**Comment by rrelyea** [comment]
Please add PR/Commit to issue, then close.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/pull/677

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/1dea7f4b23264e36a0473cf0a5be8461e558fc88
