### ISSUE TITLE
Error shown when running NuGet.exe help -Markdown -All

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#2968]
Error: 
The resource type 'NuGet.CommandLine.NuGetCommand' does not have an accessible static property named 'RestoreCommandUsageExamples'.

**Comment by emgarten** [comment]
I've checked in a fix for this to unblock tests
NuGet/NuGet.Client@1cd6850fc8cb773b268c59ddc84762c8abe0a7f9
