### ISSUE TITLE
Issue determining installed target compatibility when a file with a target of "content" is included in files section

### ISSUE THREAD

**Issue by ravensorb** [NuGet/Home#2969]
I believe I have discovered an issue with how nuget determines if a package is compatible with a particular solution.  It appears that if a file with a target of "content" is included in the files section, the package will install in ALL projects regardless of actual target framework

Example

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>XLabs.Forms</id>
    <version>2.2.0-pre05</version>
    <title>XLabs - Forms</title>
    <authors>XLabs Team</authors>
    <owners>XLabs Team</owners>
    <licenseUrl>https://github.com/XLabs/Xamarin-Forms-Labs/blob/master/LICENSE</licenseUrl>
    <projectUrl>https://github.com/XLabs/Xamarin-Forms-Labs</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/XLabs/Xamarin-Forms-Labs/master/Design/Icons/nuget/icon_nuget.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>This package contains the cross-platform XLabs Forms framework and controls.</description>
    <summary>XLabs is a open source project that aims to provide a powerfull and cross platform set of controls tailored to work with Xamarin Forms.</summary>
    <releaseNotes>Updated for Xamarin Forms 2.2</releaseNotes>
    <copyright>Copyright © 2016 XLabs Team</copyright>
    <tags>Xamarin XLabs Forms Controls GridView ListView</tags>
    <dependencies>
      <group targetFramework="monoandroid">
        <dependency id="XLabs.Core" version="[2.2.0-pre05]" />
        <dependency id="XLabs.IoC" version="[2.2.0-pre05]" />
        <dependency id="XLabs.Platform" version="[2.2.0-pre05]" />
        <dependency id="XLabs.Serialization" version="[2.2.0-pre05]" />
        <dependency id="Xamarin.Forms" version="2.2.0.31" />
      </group>
    </dependencies>
  </metadata>
  <files>
    <!-- Content Files -->
    <file src="..\..\docs\XLabs.Forms.Readme.md" target="content\XLabs.Forms.Readme.md" />
    <!-- Assemblies: Android -->
    <file src="..\..\source\Forms\XLabs.Forms\bin\$configuration$\XLabs.Forms.dll" target="lib\monoandroid" />
    <file src="..\..\source\Forms\XLabs.Forms\bin\$configuration$\XLabs.Forms.pdb" target="lib\monoandroid" />
    <file src="..\..\source\Forms\XLabs.Forms.Droid\bin\$configuration$\XLabs.Forms.Droid.dll" target="lib\monoandroid" />
    <file src="..\..\source\Forms\XLabs.Forms.Droid\bin\$configuration$\XLabs.Forms.Droid.pdb" target="lib\monoandroid" />
  </files>
</package>
```

The above nuspec file will generate a package that will install in any project regardless of target (with the exception of a UWP project). This was tested with an Windows 8, Windows 8.1 Windows 8.1 SL, and iOS solution -- all of which allowed the package to install with NO changes in references.

If the following line

```
    <file src="..\..\docs\XLabs.Forms.Readme.md" target="content\XLabs.Forms.Readme.md" />
```

is removed the resulting package will ONLY install in a MonoDroid solution as was intended.  

As a possible suggestion I would recommend that any logic that determines package compatibility based on target explicitly exclude all targets for content and tools (or better yet only focus on lib based targets) unless also included i the "contentFiles" section for a specific targeted platform

**Comment by emgarten** [comment]
A target framework sub folder can be used with content, example:

`<file src="..\..\docs\XLabs.Forms.Readme.md" target="content\monoandroid\XLabs.Forms.Readme.md" />`

**Comment by ravensorb** [comment]
Cool, thats great to know (might be worth updating the documentation to indicate that).  The downside is, a separate line is needed for every platform just for a readme file -- seems like a lot of extra work just to fix an issue with the target platform supported detection?
