### ISSUE TITLE
NuGet.VisualStudioExtension: Package restore randomly hangs visual studio for unresponsive V2 source

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#297]
[Managed to Native Transition]	
 	System.dll!System.Net.Sockets.Socket.Receive(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags, out System.Net.Sockets.SocketError errorCode)	Unknown
 	System.dll!System.Net.Sockets.Socket.Receive(byte[] buffer, int offset, int size, System.Net.Sockets.SocketFlags socketFlags)	Unknown
 	System.dll!System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)	Unknown
 	System.dll!System.Net.FixedSizeReader.ReadPacket(byte[] buffer, int offset, int count)	Unknown
 	System.dll!System.Net.Security.SslState.StartReceiveBlob(byte[] buffer, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.Security.SslState.CheckCompletionBeforeNextReceive(System.Net.Security.ProtocolToken message, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.Security.SslState.StartSendBlob(byte[] incoming, int count, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.Security.SslState.ForceAuthentication(bool receiveFirst, byte[] buffer, System.Net.AsyncProtocolRequest asyncRequest)	Unknown
 	System.dll!System.Net.Security.SslState.ProcessAuthentication(System.Net.LazyAsyncResult lazyResult)	Unknown
 	System.dll!System.Net.TlsStream.CallProcessAuthentication(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.dll!System.Net.TlsStream.ProcessAuthentication(System.Net.LazyAsyncResult result)	Unknown
 	System.dll!System.Net.TlsStream.Write(byte[] buffer, int offset, int size)	Unknown
 	System.dll!System.Net.PooledStream.Write(byte[] buffer, int offset, int size)	Unknown
 	System.dll!System.Net.ConnectStream.WriteHeaders(bool async)	Unknown
 	System.dll!System.Net.HttpWebRequest.EndSubmitRequest()	Unknown
 	System.dll!System.Net.HttpWebRequest.SetRequestSubmitDone(System.Net.ConnectStream submitStream)	Unknown
 	System.dll!System.Net.Connection.CompleteConnection(bool async, System.Net.HttpWebRequest request)	Unknown
 	System.dll!System.Net.Connection.CompleteStartConnection(bool async, System.Net.HttpWebRequest httpWebRequest)	Unknown
 	System.dll!System.Net.Connection.CompleteStartRequest(bool onSubmitThread, System.Net.HttpWebRequest request, System.Net.TriState needReConnect)	Unknown
 	System.dll!System.Net.Connection.SubmitRequest(System.Net.HttpWebRequest request, bool forcedsubmit)	Unknown
 	System.dll!System.Net.ServicePoint.SubmitRequest(System.Net.HttpWebRequest request, string connName)	Unknown
 	System.dll!System.Net.HttpWebRequest.SubmitRequest(System.Net.ServicePoint servicePoint)	Unknown
 	System.dll!System.Net.HttpWebRequest.GetResponse()	Unknown
 	NuGet.Core.dll!NuGet.RequestHelper.GetResponse()	Unknown
 	NuGet.Core.dll!NuGet.HttpClient.GetResponse()	Unknown
 	NuGet.Core.dll!NuGet.HttpClient.DownloadData(System.IO.Stream targetStream)	Unknown
 	NuGet.Core.dll!NuGet.PackageDownloader.DownloadPackage(NuGet.IHttpClient downloadClient, NuGet.IPackageName package, System.IO.Stream targetStream)	Unknown
 	NuGet.Core.dll!NuGet.PackageDownloader.DownloadPackage(System.Uri uri, NuGet.IPackageMetadata package, System.IO.Stream targetStream)	Unknown
 	NuGet.Core.dll!NuGet.DataServicePackage.EnsurePackage.AnonymousMethod__0(System.IO.Stream stream)	Unknown
 	NuGet.Core.dll!NuGet.MachineCache.InvokeOnPackage.AnonymousMethod__31()	Unknown
 	NuGet.Core.dll!NuGet.MachineCache.TryAct(System.Func<bool> action, string path)	Unknown
 	NuGet.Core.dll!NuGet.MachineCache.InvokeOnPackage(string packageId, NuGet.SemanticVersion version, System.Action<System.IO.Stream> action)	Unknown
 	NuGet.Core.dll!NuGet.DataServicePackage.EnsurePackage(NuGet.IPackageCacheRepository cacheRepository)	Unknown
 	NuGet.Core.dll!NuGet.DataServicePackage.GetStream()	Unknown
>	NuGet.Protocol.Core.v2.dll!NuGet.Protocol.Core.v2.DownloadResourceV2.GetStream(NuGet.Packaging.Core.PackageIdentity identity, System.Threading.CancellationToken token) Line 92	C#
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.PackageDownloader.GetDownloadStream(NuGet.Protocol.Core.Types.SourceRepository sourceRepository, NuGet.Packaging.Core.PackageIdentity packageIdentity, System.Threading.CancellationToken token) Line 53	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.PackageDownloader.<GetDownloadStream>d__5>(ref NuGet.PackageManagement.PackageDownloader.<GetDownloadStream>d__5 stateMachine)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.PackageDownloader.GetDownloadStream(NuGet.Protocol.Core.Types.SourceRepository sourceRepository, NuGet.Packaging.Core.PackageIdentity packageIdentity, System.Threading.CancellationToken token)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.PackageDownloader.GetPackageStream(NuGet.Protocol.Core.Types.SourceRepository sourceRepository, NuGet.Packaging.Core.PackageIdentity packageIdentity, System.IO.Stream targetPackageStream, System.Threading.CancellationToken token) Line 45	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<NuGet.PackageManagement.PackageDownloader.<GetPackageStream>d__0>(ref NuGet.PackageManagement.PackageDownloader.<GetPackageStream>d__0 stateMachine)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.PackageDownloader.GetPackageStream(NuGet.Protocol.Core.Types.SourceRepository sourceRepository, NuGet.Packaging.Core.PackageIdentity packageIdentity, System.IO.Stream targetPackageStream, System.Threading.CancellationToken token)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.RestorePackageAsync(NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> sourceRepositories, System.Threading.CancellationToken token) Line 1132	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation..cctor.AnonymousMethod__6(object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(object source, System.Delegate method, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(object source, System.Delegate method, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
 	[Native to Managed Transition]

**Comment by deepakaravindr** [comment]
We tried to repro the issue using the following cases
1) Un-reachable feed
2) Authenticated feed
3) Package source name with hyphens and brackets on it which is an invalid package source

**Comment by deepakaravindr** [comment]
This happened only once and has not happened again. Tried different cases. No luck. Closing the issue
