### ISSUE TITLE
Package listing fails from private feed

### ISSUE THREAD

**Issue by mathikp** [NuGet/Home#2971]
We are maintaining a private NuGet feed with packages for MVC projects. Its working fine till now. But if we add some ASP.NET Core packages (ASP.NET 5-MVC 6) in the same feed, none of the packages are not listing in the NuGet Package Manager. The existing MVC packages are also not listing. An error is showing. This issue comes in all Visual Studio versions (2012, 2013, 2015). The following errors are coming in the output.

> [MVC Live] The HTTP request to 'GET http://nuget.privatefeed.com/nuget_aspnetmvc/nuget/getprivatepackages/aspnetmvc/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='unsupported'&includePrerelease=true&$skip=0&$top=26' has timed out after 100000ms. 
> 
> [MVC Live] The V2 feed at 'http://nuget.privatefeed.com/nuget_aspnetmvc/nuget/getprivatepackages/aspnetmvc/Search()?$filter=IsAbsoluteLatestVersion&searchTerm=''&targetFramework='unsupported'&includePrerelease=true&$skip=0&$top=26' returned an unexpected status code '500 Internal Server Error'. 

**I have sent the fiddler trace to support@nuget.org.**

**Comment by ronnyek** [comment]
I am seeing this too... I dont know where the 'unsupported' is coming from, but fairly certain that's the problem.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
