### ISSUE TITLE
VS2015: NuGet Package targeting .NET 451 and .NET Standard 1.3 always puts netstandard packages with a csproj project.

### ISSUE THREAD

**Issue by adamhathcock** [NuGet/Home#2972]
This has been an issue ever since trying to use a csproj project with NuGet and nuget packages created from xproj projects.  Has this supposed to have been fixed?

Here's a snippet of my xproj's project.json:

```

    "dependencies": {
        "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc2-final",
        "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc2-final"
    },

    "frameworks": {
        "net451": {
            "frameworkAssemblies": {
                "System.Runtime": {
                    "type": "build"
                } 
            }
        },
        "netstandard1.3": {
            "dependencies": {
                "System.Diagnostics.StackTrace": "4.0.1-rc2-24027",
                "System.Reflection.Extensions": "4.0.1-rc2-24027",
                "System.Reflection.TypeExtensions": "4.1.0-rc2-24027",
                "System.Security.Cryptography.Algorithms": "4.1.0-rc2-24027",
                "System.Text.RegularExpressions": "4.0.12-rc2-24027"
            }
        }
    }
```

I create a csproj targetting 4.5.2 and it errors trying to pull in System.Diagnostics.StackTrace since it's not supported on NET452.  However, it shouldn't be trying to do that at all, should it?

**Comment by rrelyea** [comment]
Please include a zip file with the full repro and repro steps? We get a ton of issues reported and appreciate issues which are easy to repro.

**Comment by adamhathcock** [comment]
Sorry, this appears to be an issue with Artifactory.  Not NuGet.

**Comment by RomainHautefeuille** [comment]
I just encountered the issue, also using Artifactory.
When bypassing it (setup a local package repository for instance) the issue is gone.

**Comment by adamhathcock** [comment]
Yeah.  I used a local file system source to validate what I should be seeing.

**Comment by RomainHautefeuille** [comment]
created an issue https://www.jfrog.com/jira/browse/RTFACT-10581

**Comment by adamhathcock** [comment]
Thanks!  My company also contacted them about this issue but yours is better.
