### ISSUE TITLE
Update with project.json in VS does not restore the package

### ISSUE THREAD

**Issue by toddm** [NuGet/Home#2976]
Repro steps:
Create .NET Core Class Library project in VS
Open NuGet 3.5beta2 package manager
Install CsvHelper 2.14.3 package
Go to Installed tab, and hit Update to update to 2.15.0

Output says it was installed but it does not do a restore on the package.  The project.json file gets updated but the references in the solution explorer show the old version and refreshing the package manager window shows the old version as well.

This works with a csproj with either a packages.config or a project.json.

**Comment by rrelyea** [comment]
beta2?

**Comment by emgarten** [comment]
This would be handled by the web tools, normally a restore is done when the project.json file is saved.

**Comment by rrelyea** [comment]
Tracking...but will be closed as external...

**Comment by rrelyea** [comment]
Just checked. This appears to be on track to be fixed, on the aspnet tooling side, for Preview2 release.

**Comment by rrelyea** [comment]
Believe it is shipping in preview2 wave of aspnet tooling.
@spadapet  - can you please verify with the latest webtools?

**Comment by spadapet** [comment]
@harikmenon - When I run through these repro steps, the restore happens and project.json and references are updated. But the package manager UI doesn't show the updated installed version right away (it updates after switching away from the tab)
Should this be a "known issue" added to the docs?

**Comment by harikmenon** [comment]
I don't think this meets the bar for a known issue IMO.

**Comment by spadapet** [comment]
Sounds good to me, you can re-close this
