### ISSUE TITLE
NuGet Package Manager GUI Install Button

### ISSUE THREAD

**Issue by vsriram11** [NuGet/Home#2979]
In the Package Manager GUI in Visual Studio, getting to the install button is a real pain point. It's located at the bottom of the right pane, which means expanding the window (there is no right scrollbar), and then scrolling down the right pane. I'd like to have the install button be easy to see from the getgo. 
![nugegui](https://cloud.githubusercontent.com/assets/3003836/16093575/4105f742-32f1-11e6-82d5-f1ed8c1eecbb.PNG)

**Comment by emgarten** [comment]
This is fixed in the latest version as far as I know.
