### ISSUE TITLE
Install entityframework into windows 8.1 universal app doesn't work

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#298]
Create a windows 8.1 universal app
install entityframework 6.1.3 into windows 8.1 project
then install entityframework 6.1.3 into windows phone 8.1 project

we got following error:

Attempting to gather dependencies information for package 'EntityFramework.6.1.3' with respect to project targeting 'WindowsPhoneApp, Version=v8.1'
Attempting to resolve dependencies for package 'EntityFramework.6.1.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EntityFramework.6.1.3'
Resolved actions to install package 'EntityFramework.6.1.3'
For adding package 'EntityFramework 6.1.3' to project 'App3.WindowsPhone' that targets 'wpa81'.
For adding package 'EntityFramework 6.1.3' to project 'App3.WindowsPhone' that targets 'wpa81'.
Package 'EntityFramework 6.1.3' already exists in folder 'c:\Users\zhi\documents\visual studio 2015\Projects\App3\packages'
Added reference 'System.ComponentModel.DataAnnotations' in the Global Assembly Cache to project 'App3.WindowsPhone'
Added file 'App.config'.
Added file 'App.config' to project 'App3.WindowsPhone'.
Added file 'App.config'.
Added package 'EntityFramework 6.1.3' to 'packages.config'
Added file 'packages.config' to project 'App3.WindowsPhone'.
For adding package 'EntityFramework.6.1.3' to project 'App3.WindowsPhone' that targets 'wpa81'.
For adding package 'EntityFramework.6.1.3' to project 'App3.WindowsPhone' that targets 'wpa81'.
Executing script file 'c:\Users\zhi\documents\visual studio 2015\Projects\App3\packages\EntityFramework.6.1.3\tools\install.ps1'...
Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully 
qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
You cannot call a method on a null-valued expression.
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "Invalid directory on URL."
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
Exception calling "LoadFrom" with "1" argument(s): "The specified path, file name, or both are too long. The fully 
qualified file name must be less than 260 characters, and the directory name must be less than 248 characters."
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:780 char:5
+     $utilityAssembly = [System.Reflection.Assembly]::LoadFrom((Join-P ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : PathTooLongException
 
You cannot call a method on a null-valued expression.
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:781 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Exception calling "CreateInstanceFrom" with "8" argument(s): "Invalid directory on URL."
At C:\Users\zhi\documents\visual studio 
2015\Projects\App3\packages\EntityFramework.6.1.3\tools\EntityFramework.psm1:809 char:5
+     $domain.CreateInstanceFrom(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Successfully installed 'EntityFramework 6.1.3' to App3.WindowsPhone.
========== Finished ==========

**Comment by yishaigalatzer** [comment]
This is a bug with EntityFramework's package. It should not work on phone, and they should put their dlls under a proper TFM.

@divega
