### ISSUE TITLE
Create a NuGet.Core 2.12 final nupkg and depend on it in V3

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#2983]
Right now we are depending on `2.12.0-rtm-*`:
https://github.com/NuGet/NuGet.Client/blob/1dea7f4b23264e36a0473cf0a5be8461e558fc88/src/NuGet.Core/NuGet.Protocol.Core.v2/project.json#L39

Also, packages meeting this spec are only on nuget-volatile feed and should be on NuGet.org.

**Comment by jainaashish** [comment]
As discussed offline with Rob and Joel, for now we'll depend on `2.12.0-rtm-815` which is what there in Nuget nupkg as of now and publish the same version to Nuget.org

**Comment by rrelyea** [comment]
Connected with corefx team so that people building via source to match what we ship in beta2, this change is important.
