### ISSUE TITLE
Misleading dependency resolution error message

### ISSUE THREAD

**Issue by ohadschn** [NuGet/Home#2984]
Earlier today I published a NuGet package to an internal network-share based source. This package had a dependency on the public [Microsoft.AspNet.WebApi.Client](https://www.nuget.org/packages/microsoft.aspnet.webapi.client/). I issued the following command to install it (NuGet.exe 3.4.4): `nuget install "My.Package" -Source \\my-server\NuGet`

I was then met with the following error:
`Unable to resolve dependency 'Microsoft.AspNet.WebApi.Client'. Source(s) used: 'nuget.org`

When in fact the official _nuget.org_ source was **not** used and was the reason for the failure (adding `-Source https://nuget.org/api/v2/` resolved the issue). Basically it's the worst error message possible in this situation since it's telling you that you don't need to fix the only thing that is wrong...

**Comment by emgarten** [comment]
@ohadschn does this repro in nuget.exe 4.4.1?

**Comment by ohadschn** [comment]
That environment is long gone, but running a similar command didn't result in this error now, so let's just assume it has been fixed :)
