### ISSUE TITLE
Revert dev changes in beta3

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#2986]
Should these changes go into beta3? They are currently in the dev branch.
1. lowercase paths in package folders
2. fallback package folders

**Comment by rrelyea** [comment]
We've decided that we don't need to do this in 3.5 RTM. May need to understand 1.0 vs 1.1 in future, so putting in 3.6 beta for that possible work.

**Comment by emgarten** [comment]
Fixed with the legacy path switch.
