### ISSUE TITLE
Nuget private server source not working

### ISSUE THREAD

**Issue by barrytang** [NuGet/Home#2988]
I added in my Nuget source a private server with this command. 
 nuget.exe sources add -Name NameOfTheSource -Source https://nuget.domain.com -UserName email@domain.com -Password ******\* 

It is working with "Normal" application, unfortunaltly not with dotnet core. It is impossible to do a Nuget restore if you do not remove it.

**Comment by barrytang** [comment]
Open on behalf of @Lenny32.

**Comment by rrelyea** [comment]
@Lenny32
when you say it is impossible to do a nuget restore if you don't remove it, do you mean when you run "dotnet restore" it errors? or do you mean nuget restore fails?
dotnet restore has a known limitiation that it won't work with encrypted passwords in the nuget.config file, which is the default in the sources add scenario you list. One option: choose to: -StorePasswordInClearText

**Comment by Lenny32** [comment]
@rrelyea 
I didn't try with the parameter "StorePasswordInClearText" before (I just did).
It is still not working. I still get the same error. In the end I get package restore failed. 
I tried in Visual Studio and with the command line "dotnet restore"

`info :   CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   GET https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   NotFound https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver' 41ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver''.
log  : Response status code does not indicate success: 404 (Not Found).
info :   GET https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   NotFound https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver' 12ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver''.
log  : Response status code does not indicate success: 404 (Not Found).
info :   GET https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
info :   NotFound https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver' 8ms
error: Failed to retrieve information from remote source 'https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver''.
error: Response status code does not indicate success: 404 (Not Found).
error: Failed to retrieve information from remote source 'https://nuget.company.com/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver''.
error:   Response status code does not indicate success: 404 (Not Found).`

**Comment by emgarten** [comment]
@Lenny32 what type of server is `nuget.company.com` here?

**Comment by Lenny32** [comment]
We just build up the server with a Nuget package we found on Scott Hanselman blog.

**Comment by emgarten** [comment]
@Lenny32 it looks like there may be an issue with your server if you are getting 404 responses as your log indicates. Double check that your source url is correct, your server may not be at the domain root.

**Comment by Lenny32** [comment]
It is working on "Normal" projects like a Console App.
I can see, get the packages I have available from this source.

I just retried (at least for the 10th time) and it is not working.
The server is using Basic Authentication.

If you need me to share my screen, I would be glad to help you like that.

**Comment by emgarten** [comment]
What version of NuGet.exe are you using? Please provide the exact repro steps you used to get the errors above.

It sounds like you are hitting issues with .NET Core projects with project.json, but packages.config projects are working correctly? Is that the case?

**Comment by Lenny32** [comment]
The error is only on .Net core yes, and the packages.config are working.
Server Nuget version => v2.10.0.0
Nuget.exe => NuGet Version: 3.4.3.855

I just did `nuget update -self` now I have the latest version => 3.4.4.1321 and it is working now.
even with an encrypted password.

But it seem that I cannot use the custom packages anymore.

I tried to `nuget install MyPackageName` and it messed up my project (just had to remove the folders).
I cannot see the packages anymore from the user interface.

**Comment by emgarten** [comment]
`nuget install` doesn't modify packages.config or your project. It just downloads and extracts the nupkg to a folder, there haven't been any changes in that area.

If you are trying to add a package to a project.json .NET Core project you can update your project.json file, then run `nuget restore`. Note also that for .NET Core you need 3.5.0-beta which is available on https://dist.nuget.org/index.html

**Comment by Lenny32** [comment]
With the beta version it is working but we are loosing the possibility to encrypt the password. Otherwise it is working well.

**Comment by emgarten** [comment]
Closing since it sounds like this was fixed.
