### ISSUE TITLE
Nuspec file src attribute is platform specific?

### ISSUE THREAD

**Issue by borrrden** [NuGet/Home#2989]
I sunk some time into wondering why Nuget.exe pack was not actually including the files I told it to.  It seems that on Unix platforms, the path needs to have forward slashes, while on Windows it needs to have backward slashes.  If the incorrect one is used then the files are silently skipped **and the command still succeeds without a warning or anything**.

Example:
On windows:
<file target="lib/net45" src="staging\Couchbase.Lite\net45\*" />  includes this output with verbose:

> Added file 'lib\net45\Couchbase.Lite.dll'.
> Added file 'lib\net45\Couchbase.Lite.pdb'.
> Added file 'lib\net45\websocket-sharp.dll'.
> Added file 'lib\net45\websocket-sharp.pdb'.

<file target="lib/net45" src="staging/Couchbase.Lite/net45/*" />  gives no output with verbose following the dependencies output, but I see the log 

> Successfully created package,,,

The situation on OS X is the exact opposite...which means I cannot use the same nuspec on my dev machine (Windows) and build machine (OS X).  Can this be more like MSBuild which works with either slash on both platforms?

**Comment by borrrden** [comment]
This is still an issue in the latest Nuget.exe...is this a hard thing to fix?

**Comment by mishra14** [comment]
@rohit21agrawal : is this fixed or in work?

**Comment by emgarten** [comment]
Closing due to lack of response. Please try this in the latest 4.4.1 version of nuget.exe.
