### ISSUE TITLE
NuGet.VisualStudioExtension: Add "Submit" button to search

### ISSUE THREAD

**Issue by detroitpro** [NuGet/Home#299]
The current "auto search" design of the NuGet.VisualStudioExtension creates many unnecessary searches that are unrelated to the items I'm looking for.

Turning off the default to use "include prerelease" causes another search, multiple searches happen in-between typing in the search box, often I copy and paste in the namespace (ex: nancy.authentication) but that returns zero results (I know that) but when I remove the . and add a space I created extra searches. Often I'm thinking "what do I need to type here because I know it's going to be too aggressive"

Adding a "search" or "submit" button to the form would be very helpful, make nuget appear faster (perception), reduce overhead and traffic on the nuget servers and make me :smile:

**Comment by yishaigalatzer** [comment]
We are keeping this behavior, but making search significantly faster.

Please reopen after RC if you still dislike it :)
