### ISSUE TITLE
Uninstalling package from packages.config project doesn't always remove from packages folder

### ISSUE THREAD

**Issue by TimBarham** [NuGet/Home#2990]
Normally when you uninstall a package from a project that uses `packages.config`, and no other project in the solution uses that package, the package's folder is removed from the packages folder.

However, If the only other projects that use the package are `project.json` projects, the package's folder should be deleted, but it isn't.

Repro steps:
1. Create a new Windows Command Line project in VS.
2. Add a .Net Core command line project to the solution.
3. Add the same package to both projects.
4. Delete the package from the first project - note that it's folder still exists under <solution dir>\packages.

**Comment by emgarten** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
