### ISSUE TITLE
Some files not found in NuGet2 project

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#2991]
_From @cnsharp on June 17, 2016 12:14_

The following files are not found after git clone,could you help me ?
NuGet.Frameworks/_.cs
NuGet.Frameworks/_.resx
NuGet.Shared/*cs

_Copied from original issue: NuGet/NuGetGallery#3085_

**Comment by rrelyea** [comment]
@cnsharp - can you give more details here?
When I compare nuget2\src\core\nuget.frameworks and nuget2\src\core\nuget.shared -- the contents cloned locally look identical to the server copy.

**Comment by cnsharp** [comment]
@rrelyea  
In my local copy,they are links from some other directory,but I cann't find the location.
Then I opened Core.csproj in text mode and found them.
`<Compile Include="..\..\NuGet.Client\src\NuGet.Core\NuGet.Shared\HashCodeCombiner.cs">
      <Link>NuGet.Shared\HashCodeCombiner.cs</Link>
    </Compile>
    <Compile Include="..\..\NuGet.Client\src\NuGet.Core\NuGet.Shared\SharedExtensions.cs">
      <Link>NuGet.Shared\SharedExtensions.cs</Link>
    </Compile>
    <Compile Include="..\..\NuGet.Client\src\NuGet.Core\NuGet.Shared\TypeExtensions.cs">
      <Link>NuGet.Shared\TypeExtensions.cs</Link>
    </Compile>
    <Compile Include="..\..\NuGet.Client\src\NuGet.Core\NuGet.Shared\TypeInfo.cs">
      <Link>NuGet.Shared\TypeInfo.cs</Link>
    </Compile>`

Maybe I should haved downloaded NuGet.Client source at first.

**Comment by sign42** [comment]
I ran into the same issue but powered through. It looks like in https://github.com/NuGet/NuGet2/commit/ba264c60ef35b491f6d0e06be2bf3fe0a8fddedc that a reference was made from the Nuget2 repo to the Nuget.Client repo and in https://github.com/NuGet/NuGet.Client/commit/9012fdecbf4ee085956cf68d2d947fcbe7c23164 the files that were being referenced got moved.

**Comment by PatoBeltran** [comment]
At this point we do not plan on releasing an update for Nuget2. Please try latest and let us know if you need more help from us.
