### ISSUE TITLE
[1] Enable Solution level restore in msbuild

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2993]
It is critical that Restore operates on a solution, not a project for:
- correctness (only by understand all the project to project references in a solution, and the set of nuget packages that the projects all use, are we able to get the right answers for version conflict resolution)
- performance (restore used to take 90 seconds for Roslyn before we did solution level restore, now it takes 10 - we can't give up those gains)

As such, today it needs to be run before build.
Ideally, we could make it part of build-however, msbuild limitations may make that difficult if not impossible.
Our options:
1) keep it two pass
    a) and run it before build like: "dotnet restore"
    b) or run it before build like: msbuild /t:restore and then msbuild /t:build
2) figure out a way to make it 1 pass and enable msbuild foo.sln or msbuild bar.csproj to just work properly with solution level restore.

**Comment by mhutch** [comment]
This should be possible with MSBuild - see http://sedodream.com/2010/10/22/MSBuildExtendingTheSolutionBuild.aspx

**Comment by harikmenon** [comment]
Thanks!!!! We were literally in a meeting discussing this when we saw your comment come in :)

**Comment by emgarten** [comment]
This has been added for CLI MSBuild, it still needs to be added to desktop MSBuild

**Comment by rrelyea** [comment]
is the appropriate issue opened in sdk or cli or ???, to take it from here?

**Comment by emgarten** [comment]
@rrelyea CLI work is done, this just needs to go into the desktop MSBuild now.

**Comment by rrelyea** [comment]
internal bug # 280293

**Comment by emgarten** [comment]
Verified fixed
