### ISSUE TITLE
[0] NuGet Restore Task & Targets

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#2994]
In the move from xproj/project.json to msbuild, we need to ensure Restore is well integrated into the build process.

how we are able to integrate it best will depend on the results of #2993

**Comment by emgarten** [comment]
Restore target spec https://github.com/NuGet/Home/wiki/%5BSpec%5D-MSBuild-restore-target

**Comment by rrelyea** [comment]
Integrated into CLI. Feature done. rest is bugs.
