### ISSUE TITLE
NuGet restore via Mono on Mac responses with 'Data unprotecting failed'

### ISSUE THREAD

**Issue by joshgerdes** [NuGet/Home#2996]
When running the nugget restore command via Mono on mac I receive a todo message. Can anybody shed any light on this?
###### Here's the output from running `mono --runtime=v4.0 ./nuget.exe restore`:

> TODO: unknown keyword platform
###### Environment info:
- Mac OS X 10.11.5 (15F34)
- NuGet Version 3.4.4.1321
- Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 30 13:57:48 PDT 2016)

**Comment by joshgerdes** [comment]
Retesting with newer beta version of NuGet (I had accidentally copied an older version).  

I'm now using NuGet Version: 3.5.0.1284 but I am receiving the following error:

> Restoring packages for /Users/joshgerdes/test/project.json...
>   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
> Unable to load the service index for source https://test.pkgs.visualstudio.com/DefaultCollection/_packaging/test/nuget/v3/index.json.
>   Data unprotecting failed.
>   Invalid data.

Any thoughts?

**Comment by mrward** [comment]
Do you have any encrypted passwords in your NuGet.Config?

The data unprotecting failed sounds like a bug in Mono. The bug was that if you stored an encrypted password in the NuGet.Config file, then upgraded Mono, then NuGet would fail to decrypt that password.

https://bugzilla.xamarin.com/show_bug.cgi?id=31199

This bug has been fixed however sometimes it seems to re-appear when new versions of Mono are released.

I would try deleting the credentials, if you have any, from your NuGet.Config file, then re-add them again using the nuget sources command line. That should hopefully encrypt the password so it can be read by NuGet.exe.

**Comment by joshgerdes** [comment]
@mrward Yes, the password is encrypted. Taking your advice, I upgraded to the latest mono and did some more testing.

Using:
Mono JIT compiler version 4.4.0 (tarball Wed Jun 15 18:28:03 BST 2016)

I was able to add the source with an encrypted password running the following command:
`nuget.exe sources add -Source <sourceurl> -Name <key> -UserName<username> -Password <secret>`

And the `nuget.exe restore` command would run successfully.

But if I do not add the source from the command line and just have the source defined in the project's NuGet.config it fails with the same error as I posted before.

Is there some sort of trick to get the encrypted password to be read from the NuGet.config correctly?

**Comment by mrward** [comment]
Using nuget.exe sources would add a new encrypted password to your machine's NuGet.Config file in ~/.config/NuGet/NuGet.Config.

How is the encrypted password set in your project's NuGet.Config file?

The error suggests that Mono cannot decrypt the password. So my guess is that either it was encrypted using an older version of Mono or it was encrypted on another machine. Either of these could cause NuGet to fail to decrypt the password.

**Comment by blackbaud-joshgerdes** [comment]
@mrward Yes, it does look like the encrypted password was invalid.  Using the one generated from the sources add command and written to ~/.config/NuGet/NuGet.Config did the trick.  I am now able do restores successfully.

Thanks for your help.

**Comment by joshgerdes** [comment]
@mrward Yes, it does look like the encrypted password was invalid. Using the one generated from the sources add command and written to ~/.config/NuGet/NuGet.Config did the trick. I am now able do restores successfully.

Thanks for your help!
