### ISSUE TITLE
Add netcoreapp11 and netstandard17 support

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#2998]
cc @ericstj 

In preparation for vNext we need to add netcoreapp11 and netstandard17 TFM support to nuget client

netcoreapp11 should map to netstandard17

we should also remap net463 to netstandard17 instead of its current netstandard16

**Comment by yishaigalatzer** [comment]
Wouldn't remapping net463 will be a breaking change. Why is that ok?

**Comment by weshaggard** [comment]
net463 has not yet shipped so it is currently in a floating state until that happens.

**Comment by yishaigalatzer** [comment]
This still means requiring a min version of NuGet and reshipping of 2.12. 

@rrelyea can we pull this into 3.5RTM?

**Comment by weshaggard** [comment]
As you know this is always a problem and I would much prefer a solution that didn't require nuget client changes. Have there been any further thoughts on how we can feed this configuration into the client as opposed to hard-coding it in there?

**Comment by yishaigalatzer** [comment]
We haven't made progress in this area, and it is below the watermark compared to things we have to deliver to dev15. Regardless the issue of flipping the mapping is something that should be changed very carefully.

A very simple approach would be to make the framework mapping owned by your team, and we can take dependency on it, but it still doesn't solve in place updates without shipping a new version of NuGet.exe

**Comment by joelverhagen** [comment]
> This still means requiring a min version of NuGet and reshipping of 2.12.

@yishaigalatzer, by this you mean having the corefx packages stamped with min client version matching the release this change coincides with, correct? As it looks today, that would be min client version of 2.13 as 2.12 has already shipped without this change.
