### ISSUE TITLE
Nuget restore failed for solutions which contans .xproj

### ISSUE THREAD

**Issue by sergeyzwezdin** [NuGet/Home#3001]
I've created new solution and added there a few .NET projects. It works ok.
But if I try to add ASP.NET Core project in the same solution, Nuget fails during restore command:

```
> nuget.exe restore c:\sources\test\test.sln
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
TODO: unknown keyword platform
```

It seems something broken in latest version.

**UPD:**
- nuget.exe - latest (v3.4.4) - **does not work**
- nuget.exe (v3.5.0-beta) - **works ok**

**Comment by emgarten** [comment]
3.4.4 does not support the `platform` keyword. It was added in 3.5.0-beta
