### ISSUE TITLE
File inclusion ignores files with paretheses in file names

### ISSUE THREAD

**Issue by DaRosenberg** [NuGet/Home#3003]
Using the "nuget.exe pack" command, if I have the following two files in the package source folder:
1. MyFolder\SomeFile.xml
2. MyFolder\SomeFile (Other).xml

And use the following inclusion element:

```
<file src="MyFolder\**" target="MyFolder" />
```

Then file 1 will be included in the resulting package, but **file 2 will not**.

If I rename file 2 to remove the paretheses, it is included.

It's worth mentioning that we only started seeing this recently when NuGet was upgraded to a newer version on our VSTS build agents. I don't know what version we had before, but the current version is `3.4.3.855`.

**Comment by toddm** [comment]
I just tried it with the latest 3.5.0 in Dev. The file was included but it was in the nupkg as SomeFile%20%28Other%29.xml so the encoding/decoding of the name isn't working right.  I'll look into it.

**Comment by toddm** [comment]
I spent more time on this.  Using the latest NuGet.exe from our Dev branch, and the soon to be released 3.5.0-beta2 is the same, the file does get included properly.  If you open the nupkg file with 7zip or something similar, the file name looks encoded badly, but when you actually install the package it decodes the name and ends up correct.  So I don't see any fix needed for 3.5.0.  There aren't any more versions of 3.4.x coming so there isn't anything for me to do.
Try using 3.5.0-beta2 to get around the issue.
