### ISSUE TITLE
Add option to "Remove dependencies" to only remove dependencies not being used by other packages

### ISSUE THREAD

**Issue by johnegbert** [NuGet/Home#3005]
Right now when I check "Remove dependencies" and click "Uninstall" it gives me an error that there is another package (that I am not uninstalling) that is also using one of the same dependencies, So it gives me an error and does not remove the dependencies. I believe the functionality should be that it should still remove the dependencies it can when uninstalling the package.

**Comment by PatoBeltran** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
