### ISSUE TITLE
Nuget pack gives "Value cannot be null."

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#3006]
I am using:
NuGet.exe  (3.5.0.1499)
https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe 

When I run the following command
nuget.exe pack "CodeSigner.Shell.csproj" -p "ModulePath=tools\Modules;Configuration=Debug;Platform=x86;packageversion=2.1.782.1;versionmajor=2;versionminor=1;versionbuildnumber=782;versionbuildrevision=1" -o "%enlistment_root%\Bin\x86\Debug\Product\CodeSigner\CodeSigner.Shell" -BasePath "%enlistment_root%\Bin\x86\Debug\Product\CodeSigner\CodeSigner.Shell" -Exclude *.nupkg -NonInteractive -NoPackageAnalysis -Tool

I get the following error.

Using 'CodeSigner.Shell.nuspec' for metadata.
Found packages.config. Using packages listed as dependencies
Value cannot be null.
Parameter name: path1

This only occurs if I point to using a csproj for packing.  
Currently I only have a repro on in my build system.  I will see about creating a standalone repro.

**Comment by kingerja** [comment]
Here is a stripped down repro.
pushd \\joshking-main\dump\nugetissue\3006
nugetv3\nuget.exe pack packfail.csproj

Note if you try with a previous version of nuget this operation works.  The msbuild of that csproj does complete successfully.

**Comment by toddm** [comment]
It seems to be caused by a call to GetSolutionDir() returning null.  This is probably because there is no sln file.  It should be fairly easy to fix it - just working out the best way.

**Comment by toddm** [comment]
Merged into 3.5.0-beta2 as well.
