### ISSUE TITLE
Updating a tools package moves it to dependencies

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#3008]
Add this to project.json:

```
  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-21343",
      "imports": "portable-net45+win8+dnxcore50"
    }
  }
```

Update `Microsoft.AspNetCore.Razor.Tools` through NPM or PMC.

Resulting project.json:

```
  "dependencies": {
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final"
  },

  "tools": { },
```

Using VS 2015 U3 25420 with NuGet 3.5.0 beta2 1484

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. At this time we suggest moving from project.json to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
