### ISSUE TITLE
Cannot disable machine-wide package sources

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#301]
Repro steps:
- Select Tools -> Options -> NuGet Package Manager -> Package Sources.
- Uncheck the machine-wide package sources to disable them.
- Click OK.
- Now select Tools -> Options again.

Expected: the machine-wide package sources remains unselected.
Actual: the machine-wide package sources are still selected.

**Comment by zhili1208** [comment]
it's fixed by https://github.com/NuGet/NuGet.Configuration/commit/d770e442f413a1130897e258222c59657c9777a8
