### ISSUE TITLE
Confirm that nobody is publishing .nupkg with "bad xmlns uri" for nuspec

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3012]
Please confirm that none of the nupkgs microsoft is publishing mistakenly used the 1st toolset to add serviceable to their nuspec. Check all packages in the verification feed.

**Comment by rrelyea** [comment]
Rohit confirmed that there were 8 nupkgs with the "bad" xmlns uri. We are fixing those packages for Roslyn, etc...

**Comment by rohit21agrawal** [comment]
just for context, here is the list of those packages : 

Microsoft.CodeAnalysis.Common.nuspec
Microsoft.CodeAnalysis.CSharp.nuspec
Microsoft.CodeAnalysis.Compilers.nuspec
Microsoft.CodeAnalysis.VisualBasic.nuspec
Microsoft.CodeAnalysis.CSharp.Workspaces.nuspec
Microsoft.CodeAnalysis.Workspaces.Common.nuspec
Microsoft.CodeAnalysis.VisualBasic.Workspaces.nuspec
Microsoft.DiaSymReader.nuspec
