### ISSUE TITLE
Creating PCL (net46 and windows 10) project get NullRef exception.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3014]
NuGet version dev branch 3.5.0-1507
Repro steps:
 Create PCL project (net46 and windows 10)

Expect: project is created successfully and restored well.

Actual: Got NullRef Exception and restore failed.

There are two issues here,
1. V2LocalFindPackageByIdProvider does not accept local sources with FeedType.UnzippedFileSystem.
2. PCL project is trying to install Microsoft.NETCore 5.0.0 for .net framework 4.6 by NuGet API from C:\Program Files (x86)\Microsoft SDKs\NuGetPackages, it depends on Microsoft.NETCore.Targets.NETFramework 4.6.0 and System.Net.NetworkInformation 4.0.10-beta-23123 , but for update 2, Microsoft.NETCore.Targets.NETFramework and System.Net.NetworkInformation are missing in C:\Program Files (x86)\Microsoft SDKs\NuGetPackages, for update 3, only Microsoft.NETCore.Targets.NETFramework is missing there.

**Comment by rrelyea** [comment]
Closing, since Zhi is out. Assuming this commit should address.
