### ISSUE TITLE
beta-final packages, Incorrect dependency on 'NuGet.Core`

### ISSUE THREAD

**Issue by dazinator** [NuGet/Home#3016]
Tried to use NuGet client, latest beta packages. Got following exception when application starting:

> {"Could not load file or assembly 'NuGet.Core, Version=2.10.1.766, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"NuGet.Core, Version=2.10.1.766, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}

This is seemingly because `NuGet.Protocol.Core.v2 3.5.0-beta-final` expects NuGet.Core >= 2.11.1

But other packages are looking for `2.10.1`.

The solution was to add `NuGet.Core` version `2.10.1` to project.json for force it to that version.

No idea if this will yield other exceptions at runtime yet.

![image](https://cloud.githubusercontent.com/assets/3176632/16272286/24715e88-3895-11e6-9352-f2962bfd97f7.png)

Here is the working project.json:

```
 "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc.TagHelpers": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Gluon.Core": "1.0.0-*",
    "NuGet.Core": "2.10.1",
    "NuGet.Client": "3.5.0-beta-final",
    "NuGet.Resolver": "3.5.0-beta-final",
    "NuGet.Repositories": "3.5.0-beta-final",
    "NuGet.Packaging": "3.5.0-beta-final",
    "NuGet.Protocol.Core.Types": "3.5.0-beta-final",
    "NuGet.Protocol.Core.v3": "3.5.0-beta-final",
    "NuGet.Protocol.Core.v2": "3.5.0-beta-final",
    "NuGet.ProjectManagement": "3.5.0-beta-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "NuGet.PackageManagement": "3.5.0-beta-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final"
  },
  "frameworks": {
    "net452": {
      "dependencies": {

      }
    }
  },
```

**Comment by rrelyea** [comment]
please investigate beta-final packages and beta2 packages from internal release share.
is there something we need to fix for beta2?
We have one issue that is known... https://github.com/NuGet/Home/issues/2983

**Comment by jainaashish** [comment]
@dazinator what are other packages which depends on 2.10.1? I tried to reproduce this but it successfully got Nuget.Core 2.11.1 package and worked fine. I'm also wondering how your specified project.json is working since it needs 2.11.1 where as you've specifically called for 2.10.1?

**Comment by dazinator** [comment]
@jainaashish 

When I specify `NuGet.Core` 2.11.1 - My project.json all looks fine, but get this exception on application startup:

> > {"Could not load file or assembly 'NuGet.Core, Version=2.10.1.766, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"NuGet.Core, Version=2.10.1.766, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}

So something is still expecting `2.10.1`. My guess is one of the NuGet libraries in the Beta packages was compiled against that version explicitly?

Here is a `Find in Files` on my solution for `NuGet.Core` which shows all the project.lock.json files all showing `NuGet.Core` version 2.11.1 - I have no reference to 2.10.1 anywhere.

```
Find all "NuGet.Core", Subfolders, Find Results 1, Entire Solution, ""
  E:\tst\src\Gluon.WebApplication\project.lock.json(1822):      "NuGet.Core/2.11.1": {
  E:\tst\src\Gluon.WebApplication\project.lock.json(1828):          "lib/net40-Client/NuGet.Core.dll": {}
  E:\tst\src\Gluon.WebApplication\project.lock.json(1831):          "lib/net40-Client/NuGet.Core.dll": {}
  E:\tst\src\Gluon.WebApplication\project.lock.json(2004):          "NuGet.Core": "2.11.1",
  E:\tst\src\Gluon.WebApplication\project.lock.json(2640):          "NuGet.Core": "2.11.1",
  E:\tst\src\Gluon.WebApplication\project.lock.json(4351):    "NuGet.Core/2.11.1": {
  E:\tst\src\Gluon.WebApplication\project.lock.json(4355):        "NuGet.Core.2.11.1.nupkg.sha512",
  E:\tst\src\Gluon.WebApplication\project.lock.json(4356):        "NuGet.Core.nuspec",
  E:\tst\src\Gluon.WebApplication\project.lock.json(4357):        "lib/net40-Client/NuGet.Core.dll"
  E:\tst\src\Gluon.Module.PackageManager\project.json(16):    "NuGet.Core": "2.11.1",
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(1440):      "NuGet.Core/2.11.1": {
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(1446):          "lib/net40-Client/NuGet.Core.dll": {}
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(1449):          "lib/net40-Client/NuGet.Core.dll": {}
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(1622):          "NuGet.Core": "2.11.1",
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(3258):    "NuGet.Core/2.11.1": {
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(3262):        "NuGet.Core.2.11.1.nupkg.sha512",
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(3263):        "NuGet.Core.nuspec",
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(3264):        "lib/net40-Client/NuGet.Core.dll"
  E:\tst\src\Gluon.Module.PackageManager\project.lock.json(5157):      "NuGet.Core >= 2.11.1",
  Matching lines: 19    Matching files: 3    Total files searched: 893

```

Now... If force 2.10.1 to be used by specifying that in my `project.json` like so:

```
  "NuGet.Core": "2.10.1",
```

Now the application starts up, I don't get that exception, the NuGet.Core assembly is resolved no problem.. However I see the warning squiggle that `NuGet.Protocol.Core.v2` expects atleast version `2.11.1`. So I am now wondering if I'll hit issues later on.

**Comment by dazinator** [comment]
Digging further, it looks like there is a binding redirect occurring:

```
=== Pre-bind state information ===
LOG: DisplayName = NuGet.Core, Version=2.11.1.812, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///E:/tst/src/Gluon.WebApplication/bin/Debug/net452/win7-x64/
LOG: Initial PrivatePath = NULL
Calling assembly : Gluon.Module.PackageManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: E:\tst\src\Gluon.WebApplication\bin\Debug\net452\win7-x64\Gluon.WebApplication.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 2.11.1.812 redirected to 2.10.1.766.
LOG: Post-policy reference: NuGet.Core, Version=2.10.1.766, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///E:/tst/src/Gluon.WebApplication/bin/Debug/net452/win7-x64/NuGet.Core.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

Building my RC2 application does indeed produce a config file `Gluon.WebApplication.exe.config` and inside is a binding redirect like this:

```
 <dependentAssembly>
        <assemblyIdentity name="NuGet.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="2.11.1.812" newVersion="2.10.1.766" />
      </dependentAssembly>

```

I have no idea where that comes from though. This is an ASP.NET RC2 web application, so I have an `appSettings.json` file, not any config files. Yet this is automatically produced by the build.

**Comment by dazinator** [comment]
Oh my god.. Deleting that file `Gluon.WebApplication.exe.Config` and rebuilding has produced a new one, without the binding redirect line in for `NuGet.Core.` and subsequently things work.

 This must be some issue where doing `dotnet build` does not clear / reproduce / update that file, leaving invalid binding redirects in it.

**Comment by dazinator** [comment]
Am closing this in favour of the underlying issue which I have raised here: https://github.com/dotnet/cli/issues/3674
