### ISSUE TITLE
Ensure all issues fixed in 3.5beta2 have milestone set to 3.5 Beta2

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3017]
Please walk through the fix validation table in onenote, and ensure that all issues that correspond with commits in 3.5 beta2 branch, have their milestone set appropriately.
This is primarily to enable us to adequately share information with NuGet users/partners via the closed issue query in milestone 3.5 beta2

**Comment by rrelyea** [comment]
@harikm86  - this will help you and our users understand fixes in this release

**Comment by zhili1208** [comment]
Done, only issue 2396 and 2779 are partially fixed in beta2. asked @TimBarham to create issues in beta2 for tracking

**Comment by rrelyea** [comment]
@TimBarham - please let us know when that is done, with pointers to those issues.

**Comment by harikmenon** [comment]
closing this issue @rrelyea reopen if I screwed up :)
