### ISSUE TITLE
<clear/> does not remove source api.nuget.org

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#302]
Repro steps:
- Create a console app c:\temp\ConsoleApplication1\ConsoleApplication1.sln.
- Create file c:\temp\consoleapplication1\nuget.config. Set its content to
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="my" value="c:\temp" />
  </packageSources>  
</configuration>
```
- In VS, close solution then open solution c:\temp\ConsoleApplication1\ConsoleApplication1.sln.
- Select Tools -> Options -> NuGet Package Manager -> Package Sources.

Expected: the only enabled source is "my".
Actual: in addition to source "my", source "api.nuget.org" is also enabled.

**Comment by zhili1208** [comment]
It's fixed

**Comment by boppbo** [comment]
This problem got worse. On VS2015 RTM the clear node gets removed from the config file. This leads to the same behavior.

**Comment by zhili1208** [comment]
@boppbo Can you provide more detail about this? repro step?your NuGet.config file? Thanks

**Comment by boppbo** [comment]
Repro steps:
* Create a console app c:\temp\ConsoleApplication1\ConsoleApplication1.sln.
* Create file c:\temp\consoleapplication1\nuget.config. Set its content to
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="my" value="c:\temp" />
  </packageSources>  
</configuration>
```
* In VS, close solution then open solution c:\temp\ConsoleApplication1\ConsoleApplication1.sln.
* Build solution
* Clear node is removed

Reproduced on two machines with VS 2015 RTM Pro with NuGet 3.0.60624.657

**Comment by zhili1208** [comment]
@boppbo thanks, I can repro this, it's a bug. Here is the workaroud, this bug only happens during nuget initialization. So first, open nuget powershell,then open the solution, clear node will not be removed.

**Comment by zhili1208** [comment]
the <clear> tag will be removed during nuget initialization.

**Comment by zhili1208** [comment]
it's fixed in latest version
