### ISSUE TITLE
confirm that 2.12 will only install on vs2012/vs2013

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3020]
Please ensure that 2.12's vsixmanifest properly lists which versions it should install on: Vs2012 and VS2013.

**Comment by rohit21agrawal** [comment]
Verified. Separate VSIX's for 2012 and 2013, and they only install on their respective versions.

**Comment by niemyjski** [comment]
They are not on the nuget download page or on the check for updates dialog of vs2012!!! Please fix this

http://blog.nuget.org/20160627/Announcing-NuGet-3.5-Beta-2-and-2.12-RTM.html

**Comment by harikmenon** [comment]
[Update]
2.12 RTM for VS 2012 RTM has not been released yet. 2.12 version of NuGet Packager Extension for VS 2013, I can see the downloads page https://dist.nuget.org/visualstudio-2013-vsix/v2.12.0/NuGet.Tools.vsix

**Comment by niemyjski** [comment]
Vs2012rtm was released 3+ years ago are you referring to a new update?

Get Outlook for iOS

On Fri, Jul 1, 2016 at 4:16 PM -0500, "Harikrishna Menon" notifications@github.com wrote:

VS 2012 RTM has not been released yet. 2.12 version of NuGet Packager Extension for VS 2013, I can see the downloads page https://dist.nuget.org/visualstudio-2013-vsix/v2.12.0/NuGet.Tools.vsix

**Comment by harikmenon** [comment]
Yes, sorry. updated my comment to reflect that

**Comment by niemyjski** [comment]
When will 2.12 come out with  VS2012???????????????????????? It's been months....

**Comment by SNajm** [comment]
I am unable to add Exceptionless to a project because the Nuget isn't updated for VS2012

when will this be fixed ?

**Comment by Zwergenpunk** [comment]
Any news vor VS 2012? ;(

**Comment by HiranPeri** [comment]
Any news for VS 2012?

**Comment by niemyjski** [comment]
Any news?

**Comment by HiranPeri** [comment]
Not available till date, forced to use VS2015 community

**Comment by rogercorrea** [comment]
I never see it. Why force the upgrade to 2013 version? What the problem with the 2012 version? A old resource?

**Comment by niemyjski** [comment]
@rogercorrea betting VS2015 will be on the chopping block next month as well.

**Comment by rogercorrea** [comment]
Very stranger. The Nuget want forcing us the update the new versions? It looks a Microsoft policy. What the reason for it? What the technical argument to I update the Visual Studio version always for use the Nuget? I have a project that work and was build in 2012 version but I did try use a library that install only with the 2.12 version of Nuget. Serious that I need update the Visual Studio version for it? For me it is a too big update only for it. I prefer find other library that allow use the Nuget version with the VS 2012.
