### ISSUE TITLE
Refactor test framework to not depend on external packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3022]
We have many tests depending on `Newtonsoft.Json`, `owin`, `dotNetRDF`, etc. This can lead to situations where package owners publish a new version of a package (or unlist a version) and our tests unexpectedly break.

New tests should depend on local packages or packages maintained by us. Old tests should be refactors to remove this external dependency.

**Comment by emgarten** [comment]
Related to https://github.com/NuGet/Home/issues/745

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/nuget/client.engineering/issues/214. 

No need to have the external tracking issue despite it being older.
