### ISSUE TITLE
Update docs for "Add pack options package type to project.json"

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3026]
You're b2 commit requires some docs, I believe.
https://github.com/NuGet/NuGet.Client/commit/22e34bed6732f1d43800d1006b2d3c9ac1630555
Ideally, we can do it by release time (Monday)...
#3021

**Comment by joelverhagen** [comment]
Talked to @rrelyea offline. These docs will coincide with general package type documentation, for 3.5 RTM.

**Comment by rrelyea** [comment]
please take this PR and make it public on ship day.
