### ISSUE TITLE
Update docs for "Adding nativeassets support"

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3027]
#2782 requires docs updates.

Ideally, we finish by release time (Monday).

**Comment by emgarten** [comment]
Here is a description of this new path:

NuGet 3.5.0 support an additional native assembly folder: `runtimes/{rid}/nativeassets/{tfm}/{any}` this path adds the option to pivot on both the runtime and target framework for native assemblies. This works in the same way as the managed assembly folder `runtimes/{rid}/lib/{tfm}/{any}`. For native assemblies that apply to all target frameworks the existing `runtimes/{rid}/native/{any}` path can still be used.

**Comment by emgarten** [comment]
@harikmenon can you add this into the new docs that cover package assets and paths?

**Comment by harikmenon** [comment]
We dont have exising docs that do this :)

**Comment by harikmenon** [comment]
@karann-msft : can you work with @emgarten to figure this out?

**Comment by lilith** [comment]
Documentation would be lovely. I don't think anyone knows about this. 

Github shows 1 usage: https://github.com/search?l=XML&q=nativeassets&type=Code&utf8=%E2%9C%93

https://github.com/natemcmaster/libsqlite3-package

**Comment by PatoBeltran** [comment]
Closing as issue opened in nuget docs repo https://github.com/NuGet/docs.microsoft.com-nuget/issues/238
