### ISSUE TITLE
OptimizedZipPackage cache leaves empty folders

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3029]
NuGet.Core creates a new guid folder under NuGetScratch for each session of Visual Studio or nuget.exe when local packages are used. Upon closing the sub folders are cleaned up, but not the root. Each session appears to add a new empty guid folder.

Steps
1. Open `%temp%/NuGetScratch` in file explorer
2. Create a new project in Visual Studio 2013
3. Install-package nuget.versioning
4. Observe that  `%temp%/NuGetScratch` now contains a guid folder with files
5. Close Visual Studio

Expected
The guid folder should be deleted

Actual
The guid folder is now empty, but still exists

Clean up code is here, if packages exist the top block of code is hit. If no operations were performed the folder is deleted fully.
https://github.com/NuGet/NuGet2/blob/2.12/src/Core/Packages/OptimizedZipPackage.cs#L314-L334

**Comment by rohit21agrawal** [comment]
This will be a continuation of the work done in https://github.com/NuGet/NuGet2/pull/33
