### ISSUE TITLE
Incorrect string: A stable release of a package should not have on a prerelease dependency.

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#3030]
A stable release of a package should not have on a prerelease dependency.

Is a noun missing?

https://github.com/NuGet/NuGet.Client/blob/d74b04c1bdd3a6bb14b0ba6edd319e9c839c6eae/src/NuGet.Core/NuGet.Packaging/PackageCreation/Resources/NuGetResources.resx#L160

**Comment by rohit21agrawal** [comment]
@rrelyea 

Would the correct string here be : 

<value>A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "{0}" or update the version field.</value>

**Comment by rohit21agrawal** [comment]
cc: @yishaigalatzer @harikmenon since rob is out, can you verify what the correct string to use here should be?

**Comment by harikmenon** [comment]
A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "{0}" or update the version field in the nuspec.

This feels a bit more correct.
