### ISSUE TITLE
.targets/.props files from build folder are not imported into .xproj projects

### ISSUE THREAD

**Issue by apawsey** [NuGet/Home#3031]
I have created set of custom MSBuild tasks (actually to do with managing a local nuget based development workflow), but although my nuget package appears to have everything in the correct places, nothing is imported into my .xproj.

In a normal .csproj file, the targets imports fine.

**Comment by emgarten** [comment]
Targets and props files are not added for xproj since xproj is design to work cross platform where msbuild doesn't exist currently. You will need to use csproj + project.json or reference the targets directly from your xproj.

**Comment by apawsey** [comment]
Kinda get your point...but... xproj isn't really cross platform as it was always designed for msbuild (it's an msbuild file after all), and it's not created by the cross platform dotnet cli, but by the very not-cross-platform visual studio.  So I'm not really sure how nuget not following the same behaviour it does for every other msbuild project file is the correct behaviour?

I do understand that msbuild is now on the way, project.json is going away etc, we live in a pre-release world, so I don't mind working around it, but is there a guide/hint on how I can use csproj and project.json together?  I wasn't aware this was an option (despite having been building with dotnet core stuff for the last 6-ish months now).

**Comment by emgarten** [comment]
@apawsey take a look at https://oren.codes/2016/02/08/project-json-all-the-things/

**Comment by emgarten** [comment]
Closing this issue since xproj is going away. With CSProj + PackageReferences targets/props will be generated.
