### ISSUE TITLE
Can't push a test package to internal NuGet.Server or Klondike

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#3032]
This functional test is failing for NuGet.Server and Klondike:
- NuGet.XPlat.FuncTest.XPlatPushTests.PushToServerSucceeds

Here's the package that the test is trying to push to the server (remove the .zip extension).
- [XPlatPushTests.PushToServerSucceeds.1.0.0.nupkg.zip](https://github.com/NuGet/Home/files/330322/XPlatPushTests.PushToServerSucceeds.1.0.0.nupkg.zip)

The push fails with 500 Internal Server Error with the server returning an error saying that the package doesn't have a manifest and was rejected. I'm pretty sure the package has a manifest, other servers accept the package.

To repro, uncomment the highlighted lines below and run the test in VS:
![image](https://cloud.githubusercontent.com/assets/2523431/16309601/242b9630-391e-11e6-90da-555bc128b2bb.png)

Or you can just use nuget.exe push command line with the correct source and API key.

**Comment by spadapet** [comment]
Found while adding a new functional test. Here's the PR: https://github.com/NuGet/NuGet.Client/pull/706

**Comment by PatoBeltran** [comment]
Closing as already linked to a PR
