### ISSUE TITLE
update-package isn't working without -Version attribute with Nuget 2.12.0

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3033]
update-package command on PMC results in no updates without specifying -Version attribute whereas it's able to update with -Version and specifying a specific version. 

Environment - nuget 2.12 with vs 2013 update 5.

**Comment by rohit21agrawal** [comment]
Seems to have worked for me : 

PM> Update-Package newtonsoft.json
Updating 'Newtonsoft.Json' from version '8.0.1' to '8.0.3' in project 'WpfApplication1'.
Removing 'Newtonsoft.Json 8.0.1' from WpfApplication1.
Successfully removed 'Newtonsoft.Json 8.0.1' from WpfApplication1.
Adding 'Newtonsoft.Json 8.0.3' to WpfApplication1.
Installing 'Newtonsoft.Json 8.0.3'.
Successfully installed 'Newtonsoft.Json 8.0.3'.
Successfully added 'Newtonsoft.Json 8.0.3' to WpfApplication1.
Uninstalling 'Newtonsoft.Json 8.0.1'.
Successfully uninstalled 'Newtonsoft.Json 8.0.1'.

@jainaashish  : Can you provide more details of your project/package? What version did you install initially?

**Comment by jainaashish** [comment]
there seemed to be some intermittent issue while accessing nuget v2 feed at that moment which is why it didn't updated. Now everything seems to be working fine. Closing this as non-repro
