### ISSUE TITLE
Referencing Portable Class Library from Universal Windows App produces restore errors

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#3034]
Using VS 2015 U3 25420 with NuGet 3.5.0 beta2 1484 
1. Create a Class Library (Portable)
2. Change target to netstandard1.0
3. Create a Blank App (Universal Windows)
4. Add a reference to the Class Library
5. Build

Build succeeds, but the following is shown in the output window:

```
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
NuGet package restore failed.
```

**Comment by rrelyea** [comment]
Package author should change assets to remove these error conditions.
Template problem.

**Comment by vborovikov** [comment]
Any clues how to change assets? I targeted my package to netstandard1.3 (it was 'dotnet' before) and no longer can install it in UWP projects
I noticed AutoMapper v5.0.0 has the same problem - it's cannot be installed to a blank UWP project. The error messages are the same.

**Comment by StefH** [comment]
Any update? I'm facing same issue : https://github.com/StefH/System.Linq.Dynamic.Core/issues/33

**Comment by niemyjski** [comment]
Any updates on this?

**Comment by buffcode** [comment]
Same error here when adding `Microsoft.Data.SQLite` to a UWP application.

**Comment by PatoBeltran** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
