### ISSUE TITLE
No Items Found in a local feed when using NuGet Package Manager in Visual Studio 2012

### ISSUE THREAD

**Issue by ryanewtaylor** [NuGet/Home#3035]
I have created a local feed with the following

```
> nuget spec MyProject.csproj
> nuget pack MyProject.csproj -Prop Configuration=Release
> nuget init . \\my\feed\location
```

I then added the feed via the NuGet Package Manager in Visual Studio 2012.
1. Tools > NuGet Packager Manager > NuGet Package Manager Settings > Package Sources
2. Add: Name: My Feed Source: \\my\feed\location
3. Click Update to save the changes

But, when I try to use that feed to locate my packages no packages are listed. I receive the same behavior when using the NuGet Package Manager from the console. 

```
PM> Get-Package -ListAvailable -Source "My Feed"
PM>
```

Interestingly, if I create I add another feed with the source referencing a specific package in the local feed, I do receive one result, for said package.
1. Tools > NuGet Packager Manager > NuGet Package Manager Settings > Package Sources
2. Add: Name: My Feed 2 Source: \\my\feed\location\packagename
3. Click Update to save the changes

```
PM> Get-Package -ListAvailable -Source "My Feed 2"

Id                       Version           Description/Release Notes                                                                                                                                         
--                       ------            -------------------------                                                                                                                                         
MyProject                0.2.0.0           MyProject Library    
```

NuGet Command Line works fine in either case and reports the expected results. My environment is.

Windows 10
Visual Studio 2012
NuGet Package Manager 2.8.60318.667
NuGet Command Line 3.3.0.212

**Comment by rrelyea** [comment]
NuGet init creates the folders in an optimized way, that works from NuGet 2.12 on VS2013 and NuGet 3.x on VS2015.
Your current version of NuGet on VS2012 only looks at the root folder for packages.
