### ISSUE TITLE
Assembly conflict on Visual Studio 2013 for a package using netstandard

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3036]
Converting newtonsoft.json 9.0.1 to a pure netstandard1.0 package does not work in Visual Studio 2013.

**Steps**
1. Use Visual Studio 2013
2. Take newtonsoft.json 9.0.1 and remove all lib folders except netstandard1.0. Remove all non-netstandard dependencies also.
3. Add the package to a local folder feed
4. Create a C# .NET 4.6.1 console app
5. install-package newtonsoft.json -source yourlocalfeed
6. Build

**Expected**
The project should build fine.

**Actual**
The build fails with an error:
`Error An assembly with the same identity 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' has already been imported. Try removing one of the duplicate references.    ConsoleApplication9\packages\System.Runtime.Serialization.Primitives.4.1.1\lib\net46\System.Runtime.Serialization.Primitives.dll    ConsoleApplication9`

Removing the mentioned reference fixes the issue. 
Also, for net45 this dll is not added and things work fine, but 4.6.1 appears to have trouble with it.

The same steps on Visual Studio 2015 work correctly. Both 2015 and 2013 add the same binding redirects, but for some reason this isn't working on 2013.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
    </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Serialization.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

System.Runtime.Serialization.Primitives by itself seems to work fine in Visual Studio 2013, the conflict appears to come from newtonsoft.json.dll's reference on System.Runtime.Serialization.Primitives 4.0.0. (since it targets netstandard1.0)

**Comment by rrelyea** [comment]
Working with @ericstj offline.

**Comment by emgarten** [comment]
@ericstj suggested adding `<ImplicitlyExpandDesignTimeFacades>false</ImplicitlyExpandDesignTimeFacades>` to work around this problem in Visual Studio 2013, which solves the problem for me.
