### ISSUE TITLE
Restore fails for project in root of file system

### ISSUE THREAD

**Issue by naamunds** [NuGet/Home#3038]
**Repro steps:**
1. Install the 1.0.0-preview2-003121 build of the [.NET CLI](https://github.com/dotnet/cli).
2. From the root of the file system ("C:\" on Windows or "/" on Unix), run `dotnet new`.
3. Run `dotnet restore`.

**Results:**

The restore fails, typically with an "access denied" error.  The specifics of the error vary based on the OS.

On Windows 10 and Windows Server Core, the error is:
`error: Access to the path 'C:\Documents and Settings' is denied.`

On Nano Server, the error is:
`error: Access to the path 'C:\Windows\System32\LogFiles\WMI\RtBackup' is denied.`

On Ubuntu, the error is:
`error: Access to the path '/var/lib/docker/aufs/diff/ba249489d0b6512128b60a4910e78fa2000c785d59e0599188a6802bd01155f2/var/run/user/1000/gvfs' is denied.`

In Debian (in a Docker container running on a Mac), the command appears to hang, requiring breaking out of it with Ctrl-C.

**Notes:**

I confirmed that the error is the same when using NuGet.CommandLine.XPlat.dll outside of the `dotnet restore` command, e.g.:
`dotnet exec --depsfile "C:\Program Files\dotnet\sdk\1.0.0-preview2-003121\dotnet.deps.json" --runtimeconfig "C:\Program Files\dotnet\sdk\1.0.0-preview2-003121\dotnet.runtimeconfig.json" "C:\Program Files\dotnet\sdk\1.0.0-preview2-003121\NuGet.CommandLine.XPlat.dll" restore`

**Comment by emgarten** [comment]
This is a good test :smile: 

`dotnet restore` with no additional parameters will search your current working directory and all sub folders for project.json files. Failing with these errors when a sub folder cannot be listed seems like the correct behavior to me, ignoring a potential project folder would be a problem.

**Comment by naamunds** [comment]
Thanks for the explanation.  I thought that `dotnet restore` would just restore the first project that it finds, but I see now that it actually restores all projects in every sub-directory, meaning that if you run it from the root, it would search the entire file system.

Running `dotnet restore .\project.json` from the root works, so I'm closing this issue.
