### ISSUE TITLE
Restoring Nuget packages hangs

### ISSUE THREAD

**Issue by dillipdora1985** [NuGet/Home#3040]
I had a recent change of my user name in my system, after this I'm not able to build my visual studio (VS 2015 updated 2) projects that has some nuget packages and dll(s) as dependencies.

I tried below options but didnt help:
1. Copying the .nuget from old C:\users\old_user.nuget to C:\users\new_user.nuget did not helped me.
2. Click on visual studio nuget restore button.
3. In msdos, executed nuget restore "myslnfile.sln".

Please help.

**Comment by rrelyea** [comment]
Are you using NuGet.exe v3.4.4 (http://dist.nuget.org/index.html) - the latest shipping bits?
Can you please give us steps to help reproduce the problem on our end?

**Comment by rrelyea** [comment]
What version of Nuget are you using in VS?

**Comment by NilufarMakhmudova** [comment]
Hi. I have similar problem with 3.4.4.1321. I have downloaded Template10 for creating Windows10 Universal app. I want to build the downloaded template which triggers restoration of packages. But restoration usually fails or never ends. Can you, please, help?

**Comment by dillipdora1985** [comment]
Sorry for the late reply.
I was able to resolve them now. I had to remove all the references of .nuget and then to a rebuild. 
It automatically compiled with all the nuget depedencies.
