### ISSUE TITLE
Package manager UI: Doesn't display new version after updating a package

### ISSUE THREAD

**Issue by spadapet** [NuGet/Home#3041]
This repro is the same as: https://github.com/NuGet/Home/issues/2976
Similar to: https://github.com/NuGet/Home/issues/2828

But now with the latest dotnet tooling, the package restore does happen after updating a package version. So there is no broken functionality. It's just the package manager UI that doesn't update the display of what version is installed.

Repro steps:
- Create .NET Core Class Library project in VS
- Open NuGet package manager (right click project node | manage nuget packages)
- Install CsvHelper 2.14.3 package from nuget.org
- Go to Installed tab, and hit Update to update to 2.15.0

Result:
- The installed version display still shows the old version (2.14.3) and should show 2.15.0

Note:
- Switching away from the tab and going back will update the displayed version

**Comment by rohit21agrawal** [comment]
@spadapet What version of dotnet tooling are you using with this? I have an older version which still repros the bugs you linked to.
