### ISSUE TITLE
Packing project.json produces incorrect excludes in nuspec

### ISSUE THREAD

**Issue by toddm** [NuGet/Home#3043]
Packing dotnet packages showed that the excludes that get set in the nupsec on runtime dependencies cause problems in the project.lock.json file when used.

Using dotnet pack didn't put any excludes on the dependencies. While that probably isn't the best solution either, the current ones cause differences in the build so there's something wrong.

An investigation is needed to determine what the excludes should be and then they should be fixed.

**Comment by rrelyea** [comment]
@emgarten said one possibility is to: not output "excludes" in the output .nuspec

**Comment by rrelyea** [comment]
Workaround for now is to use a .nuspec to get proper excludes. Have to let go past 3.5.0-rtm.

**Comment by rohit21agrawal** [comment]
@rrelyea 
if it's a project.json, then nuspec will be ignored completely.

**Comment by rohit21agrawal** [comment]
won't fix since project.json is no longer supported by dotnet pack.
