### ISSUE TITLE
"Blocked by package.config" in project.json (UWP, a.k.a build integrated) project

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3046]
## Steps
1. Install recent `dev` build of the VSIX. I used build `3.5.0-rc-1545`.
2. Create a new .csproj (I created a simple Console Application).
3. Add a project.json to the .csproj ([steps](https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json#making-the-change)). Make sure the framework in `"frameworks"` matches the project. My project.json is below.
4. Re-open the solution.
5. Manage NuGet packages and install `Newtonsoft.Json` version `6.0.4`.
6. Re-open the solution.
7. Go to the Installed tab and go to the update version dropdown in the `Newtonsoft.Json` detail pane.

``` json
{
  "dependencies": {
    "Newtonsoft.Json": "6.0.4"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win": {}
  }
}
```
## Excepted

The user should be able to select any version in the dropdown.
## Actual

The dropdown says "Blocked by package.config", which does not make sense in a project.json project. Also, it should say "packages.config" (the "s" is missing in the error message).

![image](https://cloud.githubusercontent.com/assets/94054/16348028/fb73e52a-3a04-11e6-8ea5-3980d95884ea.png)

**Comment by rrelyea** [comment]
Project.json use of "6.0.4" is interpreted as [6.04,)
We should not be saying that a downgrade is blocked in these scenarios.
