### ISSUE TITLE
NuGet Package Manager extension for VS2012, 2010 has wrong identifier

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3047]
The right identifier for the NuGet package manager VS2012 when installed from the gallery is:

``` xml
<Identifier Id="NuPackToolsVsix.Microsoft.67e54e40-0ae3-42c5-a949-fddf5739e7a5">
```

While the newest v2.12 built in CI has different identifier:

``` xml
<Identifier Id="NuGet.67e54e40-0ae3-42c5-a949-fddf5739e6a5">
```

This caused both of the versions being loaded at the same time:

![image](https://cloud.githubusercontent.com/assets/8239356/16350999/44f7de92-3a17-11e6-9403-58078715af3a.png)

**Comment by rohit21agrawal** [comment]
Fixed.
