### ISSUE TITLE
Visual Studio 2012 does not add the library strong name

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3048]
Adding the System.Runtime.Serialization.Primitives in VS 2012 results in a new reference, however the reference points to the facade assembly instead of the package dll. This appears to be due to the strong name and version not being added to the reference.

Steps
1. Visual Studio 2012, New C# Console App, .NET 4.6.1
2. Install-package System.Runtime.Serialization.Primitives -Version 4.1.1
3. Look at the csproj

**Expected**

``` xml
    <Reference Include="System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">      
      <HintPath>..\packages\System.Runtime.Serialization.Primitives.4.1.1\lib\net46\System.Runtime.Serialization.Primitives.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

**Actual**

``` xml
    <Reference Include="System.Runtime.Serialization.Primitives">      
       <HintPath>..\packages\System.Runtime.Serialization.Primitives.4.1.1\lib\net46\System.Runtime.Serialization.Primitives.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

The end result is that that Visual Studio shows the framework facade being used, and the dll in the hint path here is not used. 

Also, there are no binding redirects added to the project.

**Comment by rrelyea** [comment]
We could explore options on how to have strong name written:
1) send different data to DTE (right now we send path to DLL)
2) modify the msbuild xml via the msbuild project object to have strong name
3) other?

**Comment by PatoBeltran** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2012. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
