### ISSUE TITLE
Feature Request: New API which returns all direct dependencies for all package versions

### ISSUE THREAD

**Issue by forki** [NuGet/Home#305]
In http://fsprojects.github.io/Paket/resolver.html I describe how Paket's resolver works. It basically needs [two Nuget API's](http://fsprojects.github.io/Paket/resolver.html#Caching) in order to work.

I assume we could improve the resolver performance if NuGet would provide an Api which would return all versions + all direct dependency requirements for all package versions for a package.
Currently we need to call the NuGet feed for every single package version.

**Comment by yishaigalatzer** [comment]
This can be a very large result (for example packages that post daily builds will have thousands of versions over a few years).

**Comment by forki** [comment]
Yep, but you already implemented pagination and our algorithm is lazy.

**Comment by yishaigalatzer** [comment]
We don't have pagination on static resources (where we will do this, if we decide to proceed). I'm highly suspecting this will not happen in the near future

**Comment by forki** [comment]
I wonder if the new nuget resolver will run into the same issues.

**Comment by yishaigalatzer** [comment]
We are going to look at this post RTM

**Comment by yishaigalatzer** [comment]
We might be able to provide something with the current bits though.

**Comment by johnataylor** [comment]
Move to gallery issues
