### ISSUE TITLE
When installed VS 2015 update 3 on a VS that uses NuGet version 3.5.0 error occurs

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3053]
Repro:
1. On VS 2015 update 2, installe NuGet vsix version 3.5.0
2. Update to VS 2015 upgrade 3
3. Open VS

The error:

CreateInstance failed for package [NuGetPackage]Source: 'mscorlib' Description: Could not load file or assembly 'NuGet.Tools, Version=3.5.0.1284, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Tools, Version=3.5.0.1284, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. File name: 'NuGet.Tools, Version=3.5.0.1284, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark) at System.Activator.CreateInstance(String assemblyName, String typeName) at System.AppDomain.CreateInstance(String assemblyName, String typeName) WRN: Assembly binding logging is turned OFF. To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog](DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by drewgillies** [comment]
Not seeing the repro. Suggest closing and re-open if it turns up again.

**Comment by rrelyea** [comment]
Have you asked @skofman1 ? She and @emgarten were able to hit this, I believe.

**Comment by drewgillies** [comment]
Yes, but nothing has yielded a repro yet. I'll re-open and bang on it some more.

**Comment by drewgillies** [comment]
I'm closing this again. I've re-run the steps above using 3.5.0-beta2 as the NuGet install, and still no failure. I've created a UWP app, modified packages in the VS UI, built, no problems. Tagging @skofman1 and @emgarten --if you're able to find any extra steps which will yield this repro, please add them and re-open.
