### ISSUE TITLE
Updating dependencies through visual studio removes additional attributes

### ISSUE THREAD

**Issue by MistyKuu** [NuGet/Home#3054]
I have visual studio 2015 with nuget package manager console 3.4.2. I want to create a nuget package from my project but exclude dependencies. So foreach dependency in project.json I include "type" "build" like this:

  "Microsoft.Office.Interop.Excel": {
      "version": "11.0.0",
      "type": "build"
    }

Whenever I do an update through visual studio nuget UI it's changed to:
 "Microsoft.Office.Interop.Excel": "11.0.0.1"

Is there anything I am missing or is it a bug?

Edit:
I just noticed that dependencies are ignored by default when using nuget pack. Anyway the above question still does matter for other purposes

**Comment by yishaigalatzer** [comment]
This is a bug. 

Note to team: I'm not sure if we should spend time fixing it, given that we are planning to move away from project.json and into the msbuild file directly.

**Comment by MistyKuu** [comment]
They are going away from project.json but still they plan to use project.json in another file like nuget.json for nuget packages and this functionality is must have in this case.

**Comment by yishaigalatzer** [comment]
Clarification : There is no "they" in this discussion. This is all done by the NuGet team.

The plan currently is not to go to a nuget.json, but go straight to msbuild. Of course plans are subject to change, and if we stay with project.json, this issue will get addressed.

**Comment by MistyKuu** [comment]
Sorry, I wasn't aware. So you are planning to move back to msbuild + packages.config?

**Comment by yishaigalatzer** [comment]
We plan to move the package references into msbuild directly. The mode of operation will be the same as project.json, but the items will be written into the csproj file directly.

e.g.

`<PackageReference id="foo" version="bar> />`

**Comment by MistyKuu** [comment]
Thanks for clarification mate :)

**Comment by yishaigalatzer** [comment]
Notes:

The work here would mostly be in the .net tooling that actually updates the project. It will require a change to Visual studio to expose a new API to differentiate between delete/add to update so the tooling can preserve the extra properties. Right now the flow is

delete package
-> tooling removes the package and forgets about the extra properties
add package
-> tooling add the package and have no clue that there were extra properties

**Comment by abpiskunov** [comment]
To clarify, what happens here is a limited design for contract between Nuget  and xproj project system. Upgrade operation works as remove and re-add, i.e. Nuget dialog first removes package and then re-adds new version. Having that, project system does not know that a "remove" request is actually an "upgrade" and thus just adds package with default properties missing "type" etc.
At this point in VS 15 it can not be changed an din new version of VS the whole flow will be most likely very different without xproj. So I guess this should be a "no fix".

**Comment by MistyKuu** [comment]
why was it working correctly with packages.config?

**Comment by yishaigalatzer** [comment]
@MistyKuu because it is a different code path

**Comment by MistyKuu** [comment]
@yishaigalatzer but I don't understand how would it be different from packages.config. In packages.config you need to differentiate between update and delete/add as well, why do you need extra functionality from vs if you had it in packages.config?

**Comment by yishaigalatzer** [comment]
Like I said two completely different code paths

In packages.config and project.json for UWP, nuget itself updates the references
In xproj/project.json the project system itself does the updates (outside of nuget's control). In this world there is an API between the NuGet UI and the project system.
