### ISSUE TITLE
Nuget Debug verbosity should say where a package came from

### ISSUE THREAD

**Issue by cdmihai** [NuGet/Home#3055]
For debug purposes, it would be really useful if `restore -v Debug` said where a package came from. 

Useful information for a package that would be nice to have:
- whether it came from a local cache or server and the actual package path in either case
- the address of the feed it used for that package
- which Nuget.configs it took into consideration

**Comment by GiancarloLelli** [comment]
Hi @cdmihai 
I have forked the repo since I'd like to help out on this :)
Sounds good?

**Comment by cdmihai** [comment]
Sounds good to me, although the Nuget codebase is not my area of focus. @rrelyea may point you to somebody familiar with that part of the codebase in case you have questions.

**Comment by GiancarloLelli** [comment]
Ok @cdmihai no problem!
@rrelyea If it is easier for you guys we can discuss this in a quick teams call.
For now, I'm just trying to understand how the various pieces of the solution work together.

**Comment by GiancarloLelli** [comment]
Hey @PatoBeltran any chance you can help me with this? :)

**Comment by nkolev92** [comment]
Some ideas about this in: https://github.com/NuGet/Home/issues/7577

**Comment by KirillOsenkov** [comment]
This would be really useful because I need to consolidate 21 package sources into a single source and I have no idea how to do this for a large build. We have a binlog but the binlog doesn't contain the information I need.

**Comment by KirillOsenkov** [comment]
This is related, but not same as:

https://github.com/NuGet/Home/issues/10022
https://github.com/NuGet/Home/issues/8529
