### ISSUE TITLE
Nuget Hard Fails when package feed directory does not exist. 

### ISSUE THREAD

**Issue by vancem** [NuGet/Home#3058]
Currently if a add a directory as Nuget packageSource that does not exist, it hard fails with the exception

```
   FatalProtocolException("Failed to retrieve information from remote source 'XXXX'")
```

This should be a warning instead, allowing the package to be found if it can be in other package sources.  

The current behavior interferes with the following (very reasonable) scenario.  

We have builds that create nuget packages, and to allow these nuget packages to be used by other applications it is useful to add these build locations to the package source list.   For example 

  <packageSources>
    <add key="Local CoreCLR build" value="C:\Users\vancem\Source\Repos\coreclr-vancem\bin\Product\Windows_NT.x64.Release\.nuget\pkg" />
   ...

However typical clean builds will remove these directories (in the above example everything below 'bin' is deleted), causing nuget to FAIL the build that would replace the pacakges.  This is quite unfortunate.  

This can be avoided if an exception is not thrown if the directory does not exist.

**Comment by emgarten** [comment]
`--ignore-failed-sources` gives the behavior you are suggesting.

Depending on a local folder that isn't created until later in the build is a very common scenario, NuGet's build does this also, however it's risky to ignore bad sources so the default behavior is to fail.

**Example:**
A project depends on packageA which has a dependency on packageB >= 2.0.0
Feed1 contains packageB 3.0.0
Feed2 contains packageB 4.0.0

NuGet favors the lowest version here and the user will get 3.0.0 if Feed1 is accessible. 

If Feed1 is on a network share and is temporarily unreachable a restore that ignores the missing source will take 4.0.0 from Feed2. Later it can be difficult to figure out what happened, especially if this was on a CI machine which has now produced a build with different dependencies than before when nothing else has changed.

See also: https://github.com/NuGet/Home/issues/1916

**Comment by vancem** [comment]
While the --ignore-failed-sources is an interesting option, I don't think it captures the proper tradeoff between determinism and failure robustness.    I don't know what the guidance would be for its use (when is it 'safe' to use given your concern?).  

I do note that you can clearly distinguish between a clean 'directory not found' and any other error.   I agree that ignoring errors that may be transient is dubious.  

A variation on this is to add to the packageSource XML declaration an attribute that indicates that the source is 'may be empty' which indicates it is OK if there is no directory (again, I don't think it is a good idea to ignore things like network errors).  

For what it is worth...

**Comment by rrelyea** [comment]
Vance-
You could consider doing a few "mkdirs" in your build script, which is what we do in the NuGet build script. We'll consider this feedback for the future.
Thx, Rob

**Comment by vancem** [comment]
Indeed, I can work around it.   It seems like it will be a recurring problem however.

**Comment by mlorbetske** [comment]
Is there an equivalent to `--ignore-failed-sources` for restoring packages in VS? I know individual feeds can be selected in the package management UI, but looking for a more global option.

**Comment by emgarten** [comment]
@mlorbetske not currently, but that sounds like a useful option to add in VS.

**Comment by nkolev92** [comment]
I am aware that https://github.com/NuGet/Home/issues/6373 is a newer issue, but it has higher visibility, so I'm closing this one in favor of that.
