### ISSUE TITLE
One NuGet package for both ASP.NET Core & ASP.NET 4.5

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/Home#3059]
Is it possible to create 1 Nuget package which supports ASP.NET Core & ASP.NET 4.5?

If users uses NETSTANDARD, we know it's .NET Core and with NET40 we know it's ASP.NET 4.5

But how about NET451? It could be Core or non-Core.

**Comment by emgarten** [comment]
`net*` is non-core.
`netstandard*` and `netcoreapp*` are core.

**Comment by 304NotModified** [comment]
But you can run asp.net core on the full framework? 

> ASP.NET Core apps can run on .NET Core or on the full .NET Framework.

https://docs.asp.net/en/latest/intro.html

**Comment by 304NotModified** [comment]
Why is this issue closed?

**Comment by rrelyea** [comment]
Should have given an update. Transferred to aspnet team: https://github.com/aspnet/Home/issues/1618

**Comment by 304NotModified** [comment]
Ok thanks!
