### ISSUE TITLE
nuget pack of xproj is defaulting to invalid target path

### ISSUE THREAD

**Issue by CheloXL** [NuGet/Home#3060]
Using nuget.exe 3.5 beta 2.
On a simple .NETCore I run nuget spec, build the project, nuget pack, and I get
`Attempting to build package from 'Disposable.xproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Unable to find '.\bin\Disposable\bin\Debug\'. Make sure the project has been built.`

The path where the binaries are is 'bin\Release\netstandard1.6'. Not sure why is picking "Debug", as the project is on release build.

**Comment by rrelyea** [comment]
Unsure if this is inconsistent with a csproj?

**Comment by CheloXL** [comment]
@rrelyea Just a comment (as you changed the title): It's not only that it's defaulting to debug, but the folder where nuget tries to find the binaries is completely wrong. 
Even building in debug mode, the correct path (to the debug .dlls) is `bin\Debug\netstandard1.6`

**Comment by jainaashish** [comment]
@CheloXL To workaround you can always use .nuspec file instead of .xproj and that will just work fine. Mean time we'll analyze it.

**Comment by CheloXL** [comment]
@jainaashish nuget pack disposable.nuspec gives me "Value cannot be null or an empty string. Parameter name: value"

**Comment by jainaashish** [comment]
You need to update the .nuspec file and give values to metadata like id, version, title, etc...

**Comment by CheloXL** [comment]
Ah, ok. A nicer/clearer error message would be also great...

**Comment by jainaashish** [comment]
yeah, it's in pipeline to update error/ warning messages. And about picking 'Debug' then default configuration with MsBuild is Debug so it picks that. You can also change it to Release by passing `-Properties Configuration=Release` with Pack command and all these properties attributes are then passed into Msbuild.

You can also use project.json to create nupkg just like .nuspec... you would just need to add Authors n Description details in project.json 

So there is no further action required here as of now. Let us know if you face any issue with .nuspec or project.json file.

**Comment by CheloXL** [comment]
Excellent. Using project.json everything seems to work fine. Thanks!

**Comment by echarrod** [comment]
I have the same issue now - "Unable to find 'bin\Release\{Project}\bin\Release\'." or "Unable to find 'bin\Debug\{Project}\bin\Debug\'." for either configuration. 

My output is  'bin\Release\netstandard1.6'., the same as the original poster, but I am unable to create a project.json file as you suggested, as I'm using VS2017, do you know of another workaround?

**Comment by xRoulanDx** [comment]
I have the same problem. I want to pack my project from my CI pipeline and don't want to add some overhead step for preparing .nuspec file.

**Comment by echarrod** [comment]
I managed to get it working by:
1. Right clicking my project
2. Click Properties
3. Select Package from the left hand menu
4. Select "Generate NuGet package on build"
5. Using this NuGet package file instead of using `nuget pack`
