### ISSUE TITLE
How to install NuGet programmatically to a website project?

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/Home#3062]
HI,

I need to install NuGet Programmatically to my ASPNET WEbsite project. I  canot use the following code since Website project doesn't have project file.

`installer.InstallPackage(nugetLocation, project, packagename, id, false);`

How to install NuGet by code on Website project?

Is there any ways to achieve the below command line by means of code

nuget install packages.config

**Comment by rrelyea** [comment]
@harikmenon - I checked stackoverflow, but I didn't see this addressed there. Can you please help find the answer?

**Comment by harikmenon** [comment]
@Kanimozhi12 Can you give us a sample project and a detailed repro with the code you have written to call into this method. 

We believe this should also work for Website projects but would need to see how you went about constructing the objects and calling the method before we can take a look at this.

Also are you trying to install into a New Project -> WebSite?

**Comment by harikmenon** [comment]
CC: @joelverhagen

**Comment by Kanimozhi12** [comment]
@harikmenon  I have a VSIX project, which will create a new project->Website. I need to install NuGet while project creation.but the project object for website project gives the null value , so i when i call the below code am getting null exception.
installer.InstallPackage(nugetLocation, project, packagename, id, false);

**Comment by Kanimozhi12** [comment]
Any updates??

**Comment by joelverhagen** [comment]
Hey @Kanimozhi12, could you send a minimal repro for this problem? An example Website project as well as the VSIX project would be very helpful for our investigation. If you are concerned about privacy, feel free to upload a zip of the project to a file sharing website (like OneDrive, Dropbox, Google Drive, etc) and send the link to support@nuget.org.

**Comment by Kanimozhi12** [comment]
Hi @joelverhagen ,

I have sent my project to support@nuget.org.

**Comment by joelverhagen** [comment]
Hey @Kanimozhi12, I took a look at the project you sent and had to make some modifications so it could work in my own dev environment (namely porting it to be a Visual Studio 2015 extension). Ideally these changes did not effect the results.

I was able to indeed verify the DTE `Project` object could not be casted to a `VSProject`. However, I was able to install packages using the IVS API:

``` csharp
Project project = _dte.Solution.Projects.Parent.SelectedItems.Item(1).Project;
var componentModel = (IComponentModel)GetService(typeof(SComponentModel));
var packageInstaller = componentModel.GetService<IVsPackageInstaller>();
packageInstaller.InstallPackage("https://api.nuget.org/v3/index.json", project, "Newtonsoft.Json", "9.0.1", false);
```

Have you tried the same thing in Visual Studio 2015, with NuGet 3.5.0-beta2 (our latest release)?
http://dist.nuget.org/index.html

**Comment by madenwala** [comment]
Thank you so much for pointing out IVsPackageInstaller  --- this worked perfectly!
