### ISSUE TITLE
Package Installation failure : Microsoft.Odata.Spatial

### ISSUE THREAD

**Issue by ravedata** [NuGet/Home#3063]
Hi, 

While installing Microsoft.Odata.Client and consequently their dependencies, I got below error.

Install-Package : Could not install package 'Microsoft.Spatial 6.15.0'. You are trying to install this package into a project that targ
ets '.NETFramework,Version=v4.5', but the package does not contain any assembly references that are compatible with that framework. For
more information, contact the package author.
At line:1 char:16

 I am using visual studio 2012. How to resolve this ?

**Comment by rrelyea** [comment]
Using VS 2012 Update 4, with built in NuGet Package Manager 2.6.40627.9000, I was not able to see a problem.
1. File new project / Console app targeting .net 4.5
2. add new package "Microsoft.OData.Client" via package manager

Succeeded, with the following packages.config at end:

```
<packages>
  <package id="Microsoft.OData.Client" version="6.15.0" targetFramework="net45" />
  <package id="Microsoft.OData.Core" version="6.15.0" targetFramework="net45" />
  <package id="Microsoft.OData.Edm" version="6.15.0" targetFramework="net45" />
  <package id="Microsoft.Spatial" version="6.15.0" targetFramework="net45" />
</packages>
```

**Comment by rrelyea** [comment]
Please reactivate if you have more details on how this can be reproduced.

**Comment by ravedata** [comment]
Thank you.
