### ISSUE TITLE
How to confirm that the nuget call is happening on a TFS build?

### ISSUE THREAD

**Issue by davidxcrowe** [NuGet/Home#3065]
Basically, the build can't find packages, but I can't work out if nuget is even trying to restore them!

**Comment by rrelyea** [comment]
I'm not an expert on TFS build. Have you raised this issue with TFS build experts?
Can you share relevant parts of the log, etc...
Does TFS build have a way to increase the verbosity of the logging?

By the way, checked 3.4.4 and 3.5.0-beta2 of "nuget.exe restore" in a directory with a .sln and saw that we had pretty good output:

> C:\repro\C1>nuget restore
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Restoring NuGet package Microsoft.Net.Http.2.2.29.
> Adding package 'Microsoft.Net.Http.2.2.29' to folder 'c:\repro\packages'
> Added package 'Microsoft.Net.Http.2.2.29' to folder 'c:\repro\packages'
> 
> NuGet Config files used:
>     C:\repro\NuGet.Config
>     C:\Users\rob\AppData\Roaming\NuGet\NuGet.Config
>     C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
> 
> Feeds used:
>     C:\Users\rob\AppData\Local\NuGet\Cache
>     C:\Users\rob.nuget\packages\
>     https://api.nuget.org/v3/index.json
>     https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
>     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
> 
> Installed:
>     1 package(s) to packages.config projects

When there is no work to do:

> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> All packages listed in packages.config are already installed.

What version of NuGet is being used?
If it is an older version, is it possible to increase the verbosity for the command (-verbosity detailed)?

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
