### ISSUE TITLE
project.json with wildstar doesn't generate most recent dependencies when using pack

### ISSUE THREAD

**Issue by MistyKuu** [NuGet/Home#3067]
Hey,
I am using csproj + project.json approach but it seems that it doesn't produce (at least for me) expected result. When you specify dependencies like this:

```
{
  "dependencies": {
    "AutoMapper": "2.*",
  },
  "frameworks": {
    "net451": {}
  },
  "runtimes": {
    "win-anycpu": {},
    "win": {},
    "win-x86": {}
  }
}
```

As you can see my project will use the newest version of automapper possible with major version of 2. Nevertheless when I nuget pack this project I'll get dependencies generated like this: >= 2.0. As a result in a consumer project it will resolve the lowest possible version so the version used in both projects won't be the same. Is this expected behavior? As far as I read documentation it's expected but why is it the case? Why dependency should be lowest possible?

**Comment by rrelyea** [comment]
Please give more detailed repro steps.

I tried:
I took a consoleapp, added this project.json.
Ran "NuGet.exe restore"
Ran "NuGet.exe pack foo.csproj -build"
The nuspec file that was created had no dependency in it all.

How are your steps different?

Update:
retried with 3.5.0-beta2 instead of 3.4.4:
nuspec had the following dependency:
`<dependency id="AutoMapper" version="2.0.0" exclude="Build,Analyzers" />`

**Comment by MistyKuu** [comment]
Please use nuget.exe (v3.5.0-beta2). This version has introduced a concept of generating dependencies from this combination. If you want to stick with nuget 3.4.3 the steps to reproduce are the same except the fact that project shouldn't be csproj but rather .net core

**Comment by MistyKuu** [comment]
According to your update: yes it's 2.0.0 which is translated to >= 2.0.0. Now in a consumer project it will resolve 2.0.0 (the lowest possible). In the current project it will use 2.0.2 or whatever version is the highest (wildcard 2.0.\* will take the latest one). I would expect that it will create a package with dependency like this:
`<dependency id="AutoMapper" version="[current version used, wildcard 2.0.* means the highest one so take the highest one]" exclude="Build,Analyzers" />`

Edit: 
I just checked and in .NET core it does work differently. First of all project.json doesn't allow to do a wildcard like "2.0._" but instead "2.0-_" - why is that the case? 
When it comes to dependencies they are resolved as I suggested above (using dotnet pack not nuget pack). So it looks like it's only csproj + project.json related.

Edit2:
It doesn't even work when using 2.0-\* with csproj + project.json. Nuget pack produces a package with wrong dependency version: 2.0--

**Comment by rrelyea** [comment]
Moving to 3.6 beta. Cannot fit it into 3.5rtm.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. At this time we suggest moving from project.json to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
