### ISSUE TITLE
Find-Package fails to display but Install-Package works

### ISSUE THREAD

**Issue by chauncat** [NuGet/Home#3068]
We have a teamcity feedservice that has our private feeds.  In VS 2013 using Nuget 2.8.60318.734 we call get-package -ListAvailable and we get full list of packages.  When in VS2015 we use Find-Package and only get a small subset of available feeds.  Install-Package in VS2015 can find and usually works to install the package.  Sometime it will just update the package.config file but not the project.

**Comment by chauncat** [comment]
Forgot to mention version in VS2015.  3.4.4.1321

Found the issue with the package not installing but updated in the package.config.  VS2015 does not show the error but in VS2013.  When I corrected the targetfamework the error goes away.  not sure whey the error data does not display in 2015

Install failed. Rolling back...
Install-Package : Could not install package 'XXX.Core.Droid 1.2.683-dev'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v4.4', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.At line:1 char:1
- install-package XXX.Core.Droid -IncludePrerelease
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by rrelyea** [comment]
#2926 similar/same?

**Comment by chauncat** [comment]
Sounds like the same issue.

Date: Thu, 30 Jun 2016 11:22:32 -0700

**Comment by jainaashish** [comment]
@chauncat can you try to reproduce this with nuget 3.0.0 version? other thread mentioned it was not reproducible with that version so just wanted to confirm that with you.

**Comment by chauncat** [comment]
Do you have to link to download the vsix for version 3.  I can say that if I use the command line it works.  Just not the powershell or vsix forms.

**Comment by jainaashish** [comment]
issue is with Find-Package command? otherwise get-package -ListAvailable is working good with vs 2015 or 2013 right?

**Comment by chauncat** [comment]
VS 2013Id                             Version              Description/Release Notes                         --                             -------              -------------------------                                                                                                                                               XXX.Core                       1.2.112              XXX Core Portable Class Library, YoXXX.Core.Droid                 1.2.112              The Android implmentation of the XXX Core Droid Class LibraryXXX.Core.Library               1.2.112              XXX Core Portable Class LibraryXXX.Core.Test                  1.2.112              DescriptionXXX.Emdk.Bindings.Droid        1.2.12               DescriptionXXX.Messaging                  1.2.112              XXX messaging pclXXX.Messaging.Droid            1.2.112              XXX Messaging - Android implementationXXX.Messaging.Proxy.Droid      1.2.112              XXX Messaing - Proxy / Android implmeentationXXX.Mvvm                       1.2.112              XXX MvvmCross Portable Class Library Use this package to use shared XXX mvvmcrossXXX.Mvvm.Droid                 1.2.112              XXX Mvvm Cross Droid LibraryEsri.Binding.Droid             1.2.7                ESRI SDK BindingsKaazing                        1.2.10               NuGet package for Kaazing Gateway and JMS DLLsPlacard                        1.2.10               NuGet package for Placard Wizard DLLs

VS 2015PM> get-package -ListAvailable
Id                                  Versions                                 Description                                                                                                                                     --                                  --------                                 -----------                                                                                                                                     Kaazing                             {1.2.10}                                 NuGet package for Kaazing Gateway and JMS DLLs                                                                                                  Placard                             {1.2.10}                                 NuGet package for Placard Wizard DLLs  
Date: Thu, 30 Jun 2016 14:09:40 -0700

**Comment by chauncat** [comment]
Issue is with VS2015.  Things are very inconsistent.  it is so bad I would use VS2013 if we still could.
Browse tab, Find-pacakge, and Get-package -ListAvailable all have the same result in VS2015 which is a small subset of available packages.  I get 2 packages in VS2015 and 13 in VS2013.

**Comment by jainaashish** [comment]
It looks similar to https://github.com/NuGet/Home/issues/2456 And there's good explanation in this thread about moving away from teamcity nuget server since they only support nuget v1 protocol and that too there're bugs in here which they don't want to invest in. 

Also, you could try changing your teamcity feed to use V2 with `Teamcity.nuget.api.version=v2` and see if you can query all the packages with nuget 3.4.4

**Comment by jainaashish** [comment]
Also share a fiddler trace of working vs and non working vs to further investigate this.

**Comment by chauncat** [comment]
We have V2 on our TeamCity Server.
Looking at the requests made in fiddler I can see the problem.

Working VS2013
`http://freightteamcity.con-way.com:8080/tc/guestAuth/app/nuget/v1/FeedService.svc/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27portable-net45%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7Cportable-net45%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7CMonoAndroid60%7Cnet45%7Cnet45%27&includePrerelease=false`

Not working VS2015
`http://freightteamcity.con-way.com:8080/tc/guestAuth/app/nuget/v1/FeedService.svc/Search()?$filter=IsLatestVersion&searchTerm=%27%27&targetFramework=%27unsupported%27&includePrerelease=false&$skip=0&$top=26`

The targetFramework is unsupported for some reason in VS2015.  If I replace the target framework querystring it works.
`&targetFramework=%27portable-net45%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7Cportable-net45%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7CMonoAndroid60%7Cnet45%7Cnet45%27`

Why would it be unsupported in VS2015?

**Comment by chauncat** [comment]
Can you say why the query string shows unsupported for the targetFramework on vs2015 and not vs2013?

**Comment by jainaashish** [comment]
Can you update to latest version 2.12.0 and try again? And what's your project target framework with vs 2013?

**Comment by chauncat** [comment]
Not sure why updating vs2013 is needed the error is in vs2015.  

Updated to 2.12.0.817

It works still here is link it is using.

`http://freightteamcity.con-way.com:8080/tc/guestAuth/app/nuget/v1/FeedService.svc/Search()?$filter=IsLatestVersion&$orderby=DownloadCount%20desc,Id&$skip=0&$top=30&searchTerm=%27%27&targetFramework=%27portable-net45%2Bwin%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7Cportable-net45%2Bwin%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7Cportable-net45%2Bwin%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7Cnet45%7CMonoAndroid50%7Cnet45%7CMonoAndroid44%7Cnet45%7CMonoAndroid50%7Cnet451%7Cportable-net45%2Bwin%2Bwp80%2BMonoAndroid10%2Bxamarinios10%2BMonoTouch10%7CMonoAndroid50%7Cnet45%27&includePrerelease=false`

**Comment by jainaashish** [comment]
I didn't ask to update vs version rather nuget version, pls update nuget from 2.8.6 to 2.12.0 with vs2013

**Comment by jainaashish** [comment]
oops sorry, I wanted you to check with nuget 3.5 beta2 release with vs2015 and mean time if you can tell me the project configurations as well...

**Comment by chauncat** [comment]
I get more but it is not included all the target frameworks that are in the solution.  It only picks up profile78
Here is the link
`http://freightteamcity.con-way.com:8080/tc/guestAuth/app/nuget/v1/FeedService.svc/Search()?$filter=IsLatestVersion&searchTerm=%27%27&targetFramework=%27net-profile78%2F.netframework%27&includePrerelease=false&$skip=0&$top=26`

**Comment by jainaashish** [comment]
i see, does it work good for individual projects?

**Comment by chauncat** [comment]
Version v3.5.0-beta2 works for individual projects.  Having issue rolling back to 3.4.4 atm
