### ISSUE TITLE
NuGetGalley Private IIS 8.5

### ISSUE THREAD

**Issue by joeyzderadicka** [NuGet/Home#3069]
I was able to publish the site, create users and upload packages.  However, I was having trouble adding the server as a package source in visual studio 2015 update 3. I tried http://servername/api/v2, which doesn't return any results and errors.

When I goto http://servername/api/v2 in a browser, I get:
`<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="http://servername/api/v2">
<workspace>
<atom:title type="text">Default</atom:title>
<collection href="Packages">
<atom:title type="text">Packages</atom:title>
</collection>
</workspace>
</service>`

When I goto http://servername/api/v2/Search() in a browser, I get:

`<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code/>
<m:message xml:lang="en-US">An error has occurred.</m:message>
</m:error>`

Doing both of these on nuget.org seems to return results, however I'm not sure if I'm supposed to be using v3 of the feed.  If I am, would anyone have an idea how I might configure/add it as a package source in vs 2015 update 3?

Any help is appreciated.

Thanks

**Comment by yishaigalatzer** [comment]
CC @maartenba

**Comment by maartenba** [comment]
So here's the thing:
- the output at `http://servername/api/v2` is correct
- `http://servername/api/v2/Packages` should show packages (only one page)

If not there may be a file permissions issue or the .NET 4.6 runtime missing on the server.

Can you configure tracing for the app? (this should create a log file named `TextWriterOutput.log` which contains more details on the error)

Add the following to `Web.config`:

```
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="TextWriterOutput.log" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
```

**Comment by maartenba** [comment]
@joeyzderadicka Did you see anything in the logs?

**Comment by joeyzderadicka** [comment]
Seeing these types of logs when I go to the home page, however when browsing to the url `http://servername/api/v2/Packages`.  It doesn't generate any entries in `TextWriterOutput.log`.

Log file - http://pastebin.com/ibBsn8A3

Tried setting permissions to directories (everyone full control), sql (integrated app pool has sysadmin) and  Disabled UAC / DEP as well.  I saw a few .NET updates sitting in windows update.  Running those now and will update.

Thanks for the help looking for a solution.

**Comment by maartenba** [comment]
It looks like you may have to double check write permissions on the `App_Data` folder. Did you manage to get it running on a dev machine instead of local IIS?

**Comment by joeyzderadicka** [comment]
Will double check write permissions for `App_Data` (BUILTIN\Everyone has full control to root application folder) and try to get it working on a dev machine without deploying to IIS.

**Comment by maartenba** [comment]
Closing for now.
