### ISSUE TITLE
nuGet error - 1.0.0-* is not a valid version string

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#3070]
Originally at https://github.com/aspnet/Tooling/issues/604

Steps to reproduce:
1. Add the following line in tools section of project.json.
"tools": {
...
"Microsoft.AspNetCore.Razor.Tools":"1.0.0-*",

Tools->NuGet package manager->Mange NuGet packages for Solution. ![nuget_error](https://cloud.githubusercontent.com/assets/6814395/16226102/79640f8a-37dc-11e6-8353-54dd7ea8059c.pn
Only in 'tools' section version string like "1.0.0-*" has this issue.

**Comment by rrelyea** [comment]
Are you using nuget 3.5.0-beta2 out older version? Which one?

**Comment by johnkattenhorn** [comment]
We are getting this issue, just installed 3.5.0-beta2, effecting `Add-Bindings` and `Update-Database` commands from package manager

**Comment by joelverhagen** [comment]
Looks like the original image link is broken. I think it should be:

 ![nuget_error](https://cloud.githubusercontent.com/assets/6814395/16226102/79640f8a-37dc-11e6-8353-54dd7ea8059c.png)

**Comment by mlorbetske** [comment]
Probably related to https://github.com/NuGet/Home/issues/3095 as well (where it's manifesting in the test explorer output)
