### ISSUE TITLE
NoCache parameter not honored in nuget client version 3.4+

### ISSUE THREAD

**Issue by stpatrick2016** [NuGet/Home#3074]
The scenario is like this:
1. Push a package of version 1.0.0
2. Call nuget.exe with NoCache parameter to restore packages for solution (this will download a package and store it in cache)
3. Push a package of version 1.0.0, but recompiled binaries (binaries have increased version number), e.g. overwrite it in nuget server (we are using nuget server, not the gallery).
4. Completely remove "packages" folder and call nuget,exe with NoCache again on same solution.
5. Older package, cached during step 2, is downloaded into solution's packages folder.

This reproduces with client 3.4 and 3.5 (beta), but works as expected with client 3.3, 3.2, 2.8 (we didn't check others).

Looks very similar in results as issue 2354, but they had some other complication of having packages inside packages,  which is not the case for us.

Thanks!

**Comment by joelverhagen** [comment]
Adding link to mentioned issue: #2354.

**Comment by rrelyea** [comment]
tied up with joel's investigation of the large matrix of caching behaviors, etc... won't land in time for 3.5
