### ISSUE TITLE
nuget pack csproj with project.json -includeReferencedProjects does not work like Packages.Config

### ISSUE THREAD

**Issue by MistyKuu** [NuGet/Home#3075]
Hey,
I am trying to use 3.5.0-beta2 nuget commandline with csproj + project.json combination.
. In my nuspec file I have some `<files></files>` into tools added. When I pack my project with 3.4.3 nuget, all referenced projects in a solution were added to lib folder if they didn't contain nuspec file and `<files>`were placed properly in a nuget package. With 3.5.0-beta2 it ignores nuspec `<files>` so they are not added. In addition, even though my referenced projects are not nuget packages (they don't contain nuspec files) they are added as dependencies (with -IncludeReferencedProjects flag, without this flag they are simply ignored as expected) . With packages.config all is fine.
Edit:
Ok 3.5.0-beta2 completely ignores nuspec file.
Edit2:
How is it supposed to work with project references and transitive restore pattern? Imagine that project C references 10 nuget packages. Now I include C reference in project A. I don't want to create a package from C project so I don't create a nuspec for it. Nuget pack from project A should add dependencies from projects A and C because C is not a nuget dependency but plain .dll placed in a lib folder. It doesn't seem to work like this currently.

**Comment by rohit21agrawal** [comment]
@MistyKuu Would highly appreciate if you could provide a minimal repro project that highlights your problem, am not sure if I am understanding your issue correctly.

**Comment by MistyKuu** [comment]
@rohit21agrawal 
First part:
1. Download nuget 3.5.0-beta2.
2. Create Console app (.Net framework)
3. Download nuget package to create packages.config and delete it, create project.json
4. Create nuspec file for the project, add some files into nuspec
5. Pack csproj with nuget pack
6. Only libs are included, nuspec was ignored.
Second part:
1. Create 2 projects in a solution with project.json following steps in the first example. (A and B)
2. Create a nuspec file only for project A.
3. Add a reference to B in project A so A->B.
4. Add Newtonsoft.Json nuget package in project B.
5. Add NUnit nuget package in project A. 
6. Do nuget pack in project A with flag -IncludeReferencedProjects.

Nuget 3.4.3 in this case added project B in libraries because B nuspec file doesn't exist so it cannot be created like a nuget package. On the other hand nuget 3.5.0-beta2 creates a dependency which is expected only if there is a nuspec file because B is not a nuget package.
I would expect that project A and B will be added to libs and nuget dependencies will be taken from A and B which should be NUnit and Newtonsoft.Json. The general question should be: "what should be done with dependencies of solution referenced projects if they are not nuget package"

**Comment by rohit21agrawal** [comment]
@MistyKuu thanks for the detailed steps..I'll start investigating.

**Comment by rohit21agrawal** [comment]
@MistyKuu I tried the first scenario with nuget.3.5.0-beta2, and it works as expected. Here is the nuspec file i used : 

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>ConfigToJson</id>
    <version>1.0.0</version>
    <authors>Rohit Agrawal</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Helps convert packages.config to project.json</description>
  </metadata>
  <files>
    <file src="bin\Debug\*.exe" target="mylib" />
  </files>
</package>
```

I placed it in the same directory as the csproj file and ran nuget pack configtojson.csproj and it worked as expected. (Have attached the resulting nupkg)
[ConfigToJson.1.0.0.zip](https://github.com/NuGet/Home/files/364911/ConfigToJson.1.0.0.zip)

Maybe I am missing something here, can you attach a repro app that highlights the issue?

**Comment by MistyKuu** [comment]
Hey,
did you do that step ? - "3. Download nuget package to create packages.config and delete it, create project.json".
I think you are using packages.config not project.json.
Minimal reproducable example. Please read readme.txt for explanation
[ConsoleApplication61.zip](https://github.com/NuGet/Home/files/365419/ConsoleApplication61.zip)

**Comment by BladeWise** [comment]
@MistyKuu using the file you provided I was able to generate a proper NuGet package once I removed the reference to the NewtonsoftJson assembly, and restored packages at the solution level.
As far as I know, dependencies injected through project.json are not mapped to `Reference` nodes in the csproj, so you need to remove them by hand (or uninstall the package before upgrading to project.json).
Once I did that and rebuilt the project, `nuget pack ConsoleApplication6.csproj` produced [this (zipped) NuGet package](https://github.com/NuGet/Home/files/365563/ConfigToJson.1.0.0.nupkg.zip), that contains the `test` folder you expected.
Unfortunately, the final nuspec does **not** list NewtonsoftJson as a dependency tho...

I used both NuGet 3.4.4.1321 and 3.5.1.1597 (nightly build).

**Comment by MistyKuu** [comment]
@BladeWise Newtonsoft.json.dll dll reference is there by accident. You should remove it because Newtonsoft.json nuget package is used instead. The behaviour you are describing is true for 3.4.4 version of nuget. If you use 3.5.0-beta2 you'll notice this behavior. Please download official builds: https://dist.nuget.org/index.html.
To sumup 
3.4.4 -> `<files>` works, dependencies not included
3.5.0-beta2 -> `<files>` don't work, dependency included

**Comment by BladeWise** [comment]
@MistyKuu I can confirm that published 3.5.0-beta2 ignores the nuspec file but provides dependencies, the nightly build works exactly as the 3.4.4.

Recapping:
3.4.4 -> gets info from nuspec, dependencies not included
3.5.0-beta2 -> ignores nuspec, dependecies included
nightly build -> same as 3.4.4 (gets info from nuspec, no dependencies)

**Comment by rohit21agrawal** [comment]
@MistyKuu @BladeWise You are correct. I used the nightly build instead of 3.5.0-beta2.
Appreciate your detailed feedback and quick responses.

I am cutting a separate bug to track this issue: 
https://github.com/NuGet/Home/issues/3145

As for the second issue, what I am seeing with the nightly build is that , ProjectB gets added as a dependency, (NUnit does not, which is basically the part 1 of the bug), and that behavior seems correct for project.json scenarios, since it is expected that ProjectB will be a nuget package too.. However, at this time we are discussing this in more detail and will update once we have reached a decision.

**Comment by rrelyea** [comment]
The fact that Packages.Config uses the presence of a .nuspec --- is hard to carry forward in the time we have left in 3.5.0-rtm.

**Comment by PatoBeltran** [comment]
At this time we suggest moving from packages.config/project.json to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
