### ISSUE TITLE
Content files not added with recent release

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#3076]
I'm building a NuGet package using the following command:

```
c:\somepath\NuGet.exe pack "c:\work\103\s\MyRepo\MySolution\MyProject.csproj" -OutputDirectory "d:\work\103\a\package" -Properties Configuration=release;OutputPath=d:\work\103\a\output -Version 1.2.3 -Symbols
```

The project is some ASP.NET MVC code, with a `Content` folder containing some CSS files. The compiled binaries are in `d:\work\103\a\output`. There exists a `.nuspec` file besides the `.csproj` file, which doesn't contain any files or dependencies.

While with `nuget.exe` 2.8.50506.491 this created a NuGet package containing a content folder, the content folder is missing using `nuget.exe` version 3.4.3.855.

Is there a way to have the content folder added back again with recent NuGet release, or do we now need to explicitly add the content folder in the files section of the `.nuspec` file?

**Comment by rrelyea** [comment]
Can you please report the behavior in our latest publicly available work (3.5.0-beta2 nuget.exe) ?
see http://nuget.org/downloads

**Comment by TraGicCode** [comment]
I'm having the same issue even with the beta

**Comment by flaub** [comment]
I can't get content to be installed in version `3.5.0.1996`.

I've tried creating a `contentFiles` directory, specifying a `<contentFiles>` element, and specifying a `<file target="content">`. Nothing seems to work.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
