### ISSUE TITLE
nuget restore with PackageSaveMode nuspec always reinstalls package

### ISSUE THREAD

**Issue by MarkOsborneMS** [NuGet/Home#3082]
If a package has been restored with PackageSaveMode nuspec, then a subsequent attempt to restore the same package with PackageSaveMode nuspec will not detect that the package has already been installed. 
However if the package was previously restored with PackageSaveNode nupkg then nuget will not attempt to re-restore the package.
This is because it is checking for the presence of the nupkg file.
Confirmed in nuget.exe 3.4.4.1321

**Comment by rrelyea** [comment]
Can you please report the behavior in our latest publicly available work (3.5.0-beta2 nuget.exe) ?
see http://nuget.org/downloads

**Comment by MarkOsborneMS** [comment]
Confirmed in 3.5.0.1520

**Comment by rrelyea** [comment]
Looks like you have a PR out to fix this?
https://github.com/NuGet/NuGet.Client/pull/731

**Comment by joelverhagen** [comment]
Related https://github.com/NuGet/Home/issues/2402

**Comment by joelverhagen** [comment]
Closed with:
https://github.com/NuGet/NuGet.Client/pull/731
https://github.com/NuGet/NuGet.Client/pull/737
