### ISSUE TITLE
Unable to use package manager VS2013 Windows 10 PS2 not recognized

### ISSUE THREAD

**Issue by lachlann562** [NuGet/Home#3086]
After upgrading from windows 7 to windows 10 i'm unable to use the package manager. the error i get is (Visual Studio 2013): 
Error: The Package Manager Console requires PowerShell 2.0 runtime, which is not detected on this machine. Please install the PowerShell 2.0 from http://support.microsoft.com/kb/968929 and restart Visual Studio.

I've checked the steps to ensure PS2 is installed in windows features. i've tried several other suggestions online but have been unable to find a solution to this problem.

**Comment by rrelyea** [comment]
There is a PowerShell issue with Windows 10 10586.1 through 10586.62.
Run WinVer to see your version.
If that is the problem, run windows update to move to build 10586.63 or later.
If that does not address the problem, please reply.

**Comment by lachlann562** [comment]
it says 10240, i will run the windows update

**Comment by rrelyea** [comment]
I'm going to close for now. Please reactivate if you still have a problem after you've updated Windows.

**Comment by rrelyea** [comment]
@lachlann562  - did windows update fix it for you? other?

**Comment by lachlann562** [comment]
unfortunately i haven't been able to install the update as we have citrix and it appears the update is incompatible. Still working with IT to find a solution.
