### ISSUE TITLE
In NuGetProject, Need sync API for GetInstalledPackages and related methods

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#309]
In NuGetProject, Need sync API for GetInstalledPackages and related methods

**Comment by deepakaravindr** [comment]
//cc @yishaigalatzer , @emgarten 

I don't believe this is needed anymore, since, VS Extensibility API, uses JTF.Run and does not need synchronous API from the PackageManagement or the ProjectManagement layer

**Comment by yishaigalatzer** [comment]
Review NuGetProject API 
- turn into an interface
- Design review and cleanup

**Comment by deepakaravindr** [comment]
Closing, we will reconsider as part of refactoring
