### ISSUE TITLE
Command Line: Update of solution does not update app.config / web.config files

### ISSUE THREAD

**Issue by hermot** [NuGet/Home#3090]
I am using nuget.exe command line to update packages in a solution.
I compared the differences between the same solution that was updated in VS Package Manager Console and command line.
I then discovered that no app.config / web.config files were updated by the command line.
I need the binding redirects in config files to be updated in config files when using the command line tool.
Not sure if this is a missing feature or a bug. Can you please advise?

I am using version 3.4.4.1321

**Comment by hermot** [comment]
I am using version 3.4.4.1321

**Comment by PatoBeltran** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, currently the only supported way to update packages in packages.config is through VS. If there are more community feedback on this, then we'll re-evaluate this.
