### ISSUE TITLE
Windows 10, VS2015 Update 10, Nuget 3.4.4.1321 not working

### ISSUE THREAD

**Issue by NilufarMakhmudova** [NuGet/Home#3091]
I have upgraded to Windows 10. Installed VS2015 Professional with Upgrade 3. Current version of Nuget Package manager is Nuget 3.4.4.1321. Under this setup I have not been able to install a single package from nuget.org. Tried different types of projects and packages. Even installing Newtonsoft.Json to console app did not succeed. Sometimes, VS crashes. Sometimes, installation makes me wait (leaving installation running for 5 hours did not help). Please, help me with this issue. Thank you!

**Comment by emgarten** [comment]
@NilufarMakhmudova could you provide some repro steps along with the errors you are seeing?

**Comment by rrelyea** [comment]
#3111 had a similar issue that was fixed with a VS repair. Does that address your issue as well?

**Comment by NilufarMakhmudova** [comment]
@rrelyea I also tried VS repair, which did not fix the problem for me. To install packages, I applied the following workaround: Downloaded separate nuget packages from nuget.org (my 1mb/s internet connection managed 1.5MB download from nuget.org within 6 hours, from other sources the speed was fine), installed all packages from local source.
