### ISSUE TITLE
NuGet.Core InstallPackage fails with unable to find compatible version error

### ISSUE THREAD

**Issue by jc1001** [NuGet/Home#3096]
Hi there,

I've added a reference to the latest NuGet.Core libraries (2.12) to my project (.NET4.5.2 C#).  When using the `InstallPackage` method (`ignoreDependencies: false, allowPrereleaseVersions: false`) on the packagemanager to try and install the [RazorEngine ](https://www.nuget.org/packages/RazorEngine/3.8.2)package, I get the following error:

```
Updating 'Microsoft.AspNet.Razor 2.0.30506.0' to 'Microsoft.AspNet.Razor 3.0.0' failed. Unable to find a version of 'RazorEngine' that is compatible with 'Microsoft.AspNet.Razor 3.0.0'.
```

Here is the .dependencies section of the RazorEngine package:

``` xml
<dependencies>
    <group targetFramework=".NETFramework4.0">
        <dependency id="Microsoft.AspNet.Razor" version="[2.0.30506.0]" />
    </group>
    <group targetFramework=".NETFramework4.5">
        <dependency id="Microsoft.AspNet.Razor" version="3.0.0" />
    </group>
</dependencies>
```

To try and reproduce the error, I pulled the latest NuGet 2 source (2.13).  When running the following from the command-line:

```
nuget install RazorEngine -outputdirectory "D:\Git\NuGet\NuGet2\src\CommandLine\bin\Debug\Output" -source "https://www.nuget.org/api/v2/"
```

I get the same error.

The error is thrown by the following piece of code in the [InstallWalker ](https://github.com/NuGet/NuGet2/blob/2.13/src/Core/PackageWalker/InstallWalker.cs)(line 203):

``` c#
if (incompatiblePackages.Any() && !TryUpdate(incompatiblePackages, conflictResult, package, out incompatiblePackages))
{
    throw CreatePackageConflictException(package, conflictResult.Package, incompatiblePackages);
}
```

As a test, I did confirm that it can install correctly from the NuGet 3 command-line, but in my case I would like to do it from code using NuGet.Core.

If you require anything else from my side, please let me know.

**Comment by yishaigalatzer** [comment]
NuGet.Core is no longer supported as an API, so unfortunately we do not plan to invest further in it. 
Also we haven't yet made NuGet3 based API fully documented and officially supported either, but you can start by using the code that nuget.exe does for your scenario and use these packages instead.

**Comment by rrelyea** [comment]
@jc1001 - to clarify a bit. NuGet.Core is in the middle of being totally deprecated. As such, it is not being enhanced to handle new things like NETStandard.
Moving to the newer nuget packages, as @yishaigalatzer recommends (note his warnings about the API still changing a bunch), would be a way to go.
