### ISSUE TITLE
How to deal with sample files

### ISSUE THREAD

**Issue by natehitze** [NuGet/Home#3097]
Some packages install sample files into a project. Is there a way to stop certain packages from doing this?

We don't want sample files in our project, but they get added every time someone updates these packages. We figured we could just ignore it in source control, but that doesn't prevent the package from adding files to the .csproj file.

**Comment by harikmenon** [comment]
Have you considered moving to using project.json way of managing dependencies? http://docs.nuget.org/consume/ProjectJson-Intro. If you are using VS 2015, this is supported for most project types. A guide to transitioning is available here https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

**Comment by yishaigalatzer** [comment]
@laughinggoose I would contact the package owners, and suggest to remove the samples from being added to the project (and perhaps provide them in a separate package).

Long term we want to build a first class feature for samples, but we don't see it happening anytime soon given the current work items.

**Comment by natehitze** [comment]
So we have 2 packages that we publish internally.

I have a project that has both of those listed as dependencies. Only one gets pulled into the packages folder. The build reports that it completed successfully. Does anything come to mind as to why? I've tried reinstalling the package and that didn't fix it.

**Comment by natehitze** [comment]
I should also mention that I've converted all of the mentioned projects to use project.json.

**Comment by yishaigalatzer** [comment]
Content does not get added in project.json you have to use contentfiles node instead.

**Comment by natehitze** [comment]
My nuspec:

```
<package >
    <metadata minClientVersion="3.3.0">
                ... content snipped ...
        <contentFiles>
            <files include="**" buildAction="Content" />
        </contentFiles>
    </metadata>
    <files>
        <file src="contentFiles\**" target="contentFiles" />
        <!-- We might be able to get rid of the xcopy and just use this section to move files to contentFiles https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html -->
    </files>
</package>
```

I've confirmed that the nupkg contains a contentFiles folder with all of the content in it. I have setup a build script that copies some javascript and CSS into contentFiles\any\any. (That's what the xcopy comment is in reference to).

I installed this nupkg into another project, but I don't see any of the JS or CSS.

**Comment by natehitze** [comment]
I've tried different `include=""` patterns such as `**/*`, `**/*.*` and I still haven't been successful.

The target project is an ASP.NET webapp project if it matters (not core).

**Comment by natehitze** [comment]
Just made an ASP.NET core (.NET framework) web app and it doesn't work in that one either.

I see the files listed in the project.json.lock, but they are not appearing in the solution view!

**Comment by yishaigalatzer** [comment]
I believe the asp.net project system does not list them at this time. And I'm actually not sure that that's how you want to deliver CSS/Js files into it. I'm directing to the owners to provide guidance here:

@davidfowl

**Comment by PatoBeltran** [comment]
We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
