### ISSUE TITLE
Install of 0.7.2 nuget package fails

### ISSUE THREAD

**Issue by forki** [NuGet/Home#310]
original issue at https://github.com/fsprojects/FsReveal/issues/60 by @brodyberg 

"Trying to install 0.7.2 with VS 2015 I see an error about what appears to be an invalid nupkg in FsFormatting.

My version of VS:

Microsoft Visual Studio Ultimate 2015 Preview
Version 14.0.22310.1 DP
Microsoft .NET Framework
Version 4.6.00042

Installed Version: Ultimate

Screenshot of the actual error:

![image](https://cloud.githubusercontent.com/assets/57396/6924570/c0dfc9c6-d7d9-11e4-8631-24824c23d5e6.png)"

/cc @maartenba

**Comment by deepakaravindr** [comment]
Does not repro

**Comment by yishaigalatzer** [comment]
We can't see to repro this in the latest RC builds. Please reopen if you see this post RC

**Comment by forki** [comment]
It did repro, but the lastet nuget.org rejects such packages.

    <?xml version="1.0" encoding="utf-8" standalone="yes"?>
    <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
      <Default Extension="dll" ContentType="application/octet" />
      <Default Extension="pdb" ContentType="application/octet" />
      <Default Extension="xml" ContentType="application/octet" />
      <Default Extension="gitignore" ContentType="application/octet" />
      <Default Extension="yml" ContentType="application/octet" />
      <Default Extension="zip" ContentType="application/octet" />
      <Default Extension="md" ContentType="application/octet" />
      <Default Extension="js" ContentType="application/octet" />
      <Default Extension="html" ContentType="application/octet" />
      <Default Extension="" ContentType="application/octet" />
      <Default Extension="json" ContentType="application/octet" />
      <Default Extension="version" ContentType="application/octet" />
      <Default Extension="css" ContentType="application/octet" />
      <Default Extension="scss" ContentType="application/octet" />
      <Default Extension="eot" ContentType="application/octet" />
      <Default Extension="ttf" ContentType="application/octet" />
      <Default Extension="woff" ContentType="application/octet" />
      <Default Extension="png" ContentType="application/octet" />
      <Default Extension="fsx" ContentType="application/octet" />
      <Default Extension="nuspec" ContentType="application/octet" />
      <Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" />
      <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" />
    </Types>

Look at line 12. So this seems to be fixed by rejecting the package. Which is good.

I added 0.7.3 without this line.

**Comment by yishaigalatzer** [comment]
@forki did you try the visual studi rc build? It is not clear from your message. Either way I assume we can close this?

**Comment by forki** [comment]
Yes this concrete issue is solved. Unfortunately I directly run into the one https://github.com/fsprojects/Paket/issues/812

**Comment by yishaigalatzer** [comment]
Ok I'm going to close this one. We can take a look at the other one on Monday. Please file it on the nugetgallery repo
