### ISSUE TITLE
NuGet Visual Studio UI shows floating versions incorrectly

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3101]
For a .csproj + project.json project, floating versions are not displayed properly. For example, try this project.json:

``` json
{
  "dependencies": {
    "Newtonsoft.Json": "7.0.1-*"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win": {}
  }
}
```

The UI does `7.0.1--`, not `7.0.1-*`.

![image](https://cloud.githubusercontent.com/assets/94054/16701603/96e37e2e-4515-11e6-9000-7903611e9902.png)

**Comment by emgarten** [comment]
To match packages.config this would show the actual resolved version from project.lock.json. Having the range string verbatim from project.json would be great also. The UI was designed for packages.config and just needs support for the new concepts.

**Comment by nkolev92** [comment]
Consolidating this into https://github.com/NuGet/Home/issues/3788. 

I get that this is older but that issue is more popular and there's no benefit to keeping both issues open.
