### ISSUE TITLE
"dotnet restore" doesn't install custom MSBuild .targets files to users' projects

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#3102]
When a user has a NuGet package in their project that has custom .targets files (see [doc](http://docs.nuget.org/create/Creating-and-Publishing-a-Package#user-content-import-msbuild-targets-and-props-files-into-project)), the .targets files are not being installed into the .csproj when running "dotnet restore".

We need to enable this for cross-platform .Net Core projects to work with MSBuild in the CLI.

**Comment by eerhardt** [comment]
FYI - just to call this out explicitly.  This is blocking CLI working with MSBuild, since the .Net Core .targets files will be delivered to the users' projects in a NuGet package.

Also calling it out explicitly, this needs to work on non-Windows.

**Comment by emgarten** [comment]
NuGet skips targets/props for .xproj or when the project.json file is restored directly. I believe that when restoring a .dg file that contains .csprojs targets/props are restored normally. So everything should be in place already in dotnet restore, we just need to verify it after moving away from xproj/project.json.

**Comment by eerhardt** [comment]
There is no .xproj involved. I am using a project.json + .csproj.  The project.json has my dependencies, frameworks, and runtimes listed.  I am using MSBuild to build my .csproj.

**Comment by emgarten** [comment]
@eerhardt what is your input for dotnet restore?

**Comment by eerhardt** [comment]
`dotnet restore` in the current directory.  The CLI passes those args (i.e. no args) straight through.

**Comment by eerhardt** [comment]
@rrelyea @emgarten - any idea on when this might be fixed?  This is blocking our ability to ship the .NET Core .props/.targets files in a NuGet package, since it won't be loaded on non-Windows platforms.

**Comment by eerhardt** [comment]
@emgarten - can you let me know of a NuGet build number and feed that I can use to try this out?

**Comment by emgarten** [comment]
@eerhardt `3.5.0-rc1-1653` contains the change

Set the environment variable `NUGET_XPROJ_WRITE_TARGETS` to `true` to enable it.
