### ISSUE TITLE
Provide MSBuild integrated support for automating package builds

### ISSUE THREAD

**Issue by glopesdev** [NuGet/Home#3106]
I am currently migrating from the old MSBuild-integrated package restore workflow, but immediately found an annoying impediment: I was using the old **BuildPackage** target to automatically produce packages as a result of build.

With the new automatic package restore workflow, that functionality was removed. I understand I can add it by hand, but this seems somehow backwards. If NuGet is becoming more and more integrated with Visual Studio, then why shouldn't an integrated way of automating package builds be provided?

**Comment by rrelyea** [comment]
We plan on making "nuget pack" more integrated into VS and msbuild. This is being tracked via: https://github.com/NuGet/Home/issues/2995
