### ISSUE TITLE
Nuget Package Manager slow when having own nuget server

### ISSUE THREAD

**Issue by MarienMonnier** [NuGet/Home#3107]
Hi,

I created a post on the VS forums : https://social.msdn.microsoft.com/Forums/vstudio/en-US/fd1596b0-ca30-4b38-ac74-1af01d9f00f0/nuget-package-manager-slow-when-having-own-nuget-server?forum=visualstudiogeneral
But was redirected to nuget contact page.

I have a problem with the Nuget Package Manager that calls my nuget server for lots of packages (more than 250), so it takes 40s each time I want to do something with the nuget package manager.

![nuget_visualstudio](https://cloud.githubusercontent.com/assets/8627898/16722858/cd037d48-4749-11e6-918f-eb92740aa338.png)

How can I disable this behavior? Is this a known issue once you have our own Nuget.Server?

Thanks

**Comment by emgarten** [comment]
@MarienMonnier what operations are you performing with NuGet? Is this using the Visual Studio UI or the package manager console?

**Comment by MarienMonnier** [comment]
@emgarten this was from Visual Studio UI.

I just tested with the package manager console, and I have the same behavior :

```
Attempting to gather dependency information for package 'xxxx' with respect to project 'xxxx', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 38,82 sec
Attempting to resolve dependencies for package 'xxxx' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
```

This is my nuget sources list : 

```
C:\Users\m.monnier>nuget sources list
Sources inscrites :

  1.  nuget.org [Activé]
      https://api.nuget.org/v3/index.json
  2.  Nuget xxxx [Activé]
      http://nuget.xxx/nuget
  3.  Microsoft Visual Studio Offline Packages [Activé]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

The "Nuget xxxx" is our own Nuget.Server

**Comment by emgarten** [comment]
@MarienMonnier NuGet retrieves metadata for packages from all sources in parallel, from what you've pasted the above trace looks expected.

You can disable your local nuget server to avoid this behavior. 40s to look up 250 packages in parallel sounds very slow. Make sure that you are running the latest 2.11.2 version of NuGet.Server, it contains many performance improvements over older versions.

**Comment by rrelyea** [comment]
We are doing features to warn users when a slow or unavailable source is causing problems. It sounds like that may the case here. 
Please reopen this issue if you are using 2.11.2 of NuGet.Server or later, and you still see this problem.
