### ISSUE TITLE
Cannot package library targeting .Net Standard correctly

### ISSUE THREAD

**Issue by huoyaoyuan** [NuGet/Home#3108]
The project and project.json is generated by the option "Target .Net Standard Platform" in Visual Studio.
In csproj:

``` xml
<TargetFrameworkProfile>
</TargetFrameworkProfile> 
<TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
```

and in project.json:

``` json
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    "netstandard1.0": {}
  }
}
```

When packaging the project, there will be a "portable50" folder. Nuget 3.4.4 warns "invald framework folder", 3.5beta2 doesn't warn, but the folder name is the same.

**Comment by emgarten** [comment]
@huoyaoyuan what version of Visual Studio are you using?

**Comment by huoyaoyuan** [comment]
@emgarten Visual Studio 2015 Update 3, the latest version.

**Comment by rrelyea** [comment]
@huoyaoyuan  - sounds like 3.5.0-beta2 has fixed your issue, but 3.4.4 (an older version) had a problem.
If that is the case, you'll be happy with 3.5.0 when it releases. 
Please reopen if I misinterpreted?

**Comment by huoyaoyuan** [comment]
@rrelyea 3.5.0-beta2 just does not warn, but the folder name is still "portable50". According to [.Net Standard documentation](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#migrating-existing-pcls-in-nuget-packages), the corresponding folder name should be "netstandard1.0". I'm not sure whether "portable50" works or not.

**Comment by emgarten** [comment]
@huoyaoyuan try the latest nightly build from: http://dist.nuget.org/index.html

NuGet 3.4.4 does not support packing project.json and 3.5.0-beta2 may have limited support compared to the latest build. From what you are describing it looks like the project.json file isn't being used when you create the package.

**Comment by huoyaoyuan** [comment]
@emgarten the issue still exists in the latest nightly build. Still "portable50". Another issue of not applying .nuspec seems fixed.

**Comment by ipjohnson** [comment]
I've run into the same issue, it does look like the project.json file is used correctly as the package that is generated has the correct .netstandard1.0 dependencies. The problem seems to be the dll is being placed in the lib/portable50 directory rather than lib/netstandard1.0

**Comment by emgarten** [comment]
@ipjohnson thanks for the update, this looks like a bug in pack. The framework from project.json should be used.

**Comment by ipjohnson** [comment]
@emgarten thanks for the quick reply, do you have any guidance on working around this?

**Comment by emgarten** [comment]
@ipjohnson try `nuget.exe pack <project.json>`

**Comment by ipjohnson** [comment]
@emgarten I get the following error 

Attempting to build package from 'project.json'.
Object reference not set to an instance of an object.

**Comment by BladeWise** [comment]
@emgarten @rrelyea Using the NuGet.exe nightly build (3.5.1.1597) `nuget pack <projectname>.csproj` still places dll files inside `portable50` folder.
Moreover, using pack over the `<projectname>.project.json` is not a valid solution, since we cannot achieve the same results as before.

Ona a side note: using `<projectname>.csproj, <projectname>.nuspec, packages.<projectname>.config` and calling `nuget pack <projectname>.csproj` generates a package listing required dependencies and with substitution tokens (i.e. `$version$`, `$author$`) properly resolved. Moreover, using option `-includereferencedprojects` would append package dependencies for project references that have corresponding nuspec.
Will this scenario still be supported using `<projectname>.csproj, <projectname>.nuspec, <projectname>.project.json` and calling `nuget pack <projectname>.csproj`?

**Comment by ipjohnson** [comment]
@emgarten maybe I'm missing something but this seems like a rather large stumbling block for getting open source package developers to move to .netstandard. Should we not be using the "Target .NET Platform Standard" link in VS and create the projects by hand with xsproj files?

**Comment by emgarten** [comment]
@ipjohnson agreed, this looks like a critical bug in pack for project.json that should be fixed for the upcoming release.
