### ISSUE TITLE
Preserve reference aliases

### ISSUE THREAD

**Issue by rolfik** [NuGet/Home#3113]
Is it possible to preserve assembly reference aliases set manually on a reference added by NuGet accross package update etc.?

Before update:
![image](https://cloud.githubusercontent.com/assets/4658651/16766768/3bf010fc-483c-11e6-89e6-f9a190a658af.png)
After update (aliases reset instead of kept):
![image](https://cloud.githubusercontent.com/assets/4658651/16766821/9254fe26-483c-11e6-9bf7-75b2bbf88c40.png)

I use Visual Studio 2015, Package Manager Console Host Version 3.5.0.1284

Thank You

Marek Istvanek

**Comment by rrelyea** [comment]
Thanks for the request. We'll investigate this in the future, to see what it would take to fix.
This is based on the assumption that this hasn't worked properly in the past (with recent NuGet versions). If that assumption is wrong, please chime in.

**Comment by rrelyea** [comment]
Note, in Project.json this is not enabled, since the references are added on the fly by an msbuild task.

In both cases, packages.config and project.json, the answer is probably to have an msbuild target add this alias to the reference, which is either explicitly added to csproj or implicitly added by a build task.

Long term, we'll keep this open, but will only do if this shows up as a common request.

**Comment by rolfik** [comment]
Thank You for comments.

Long term is not satisfying, but we have to cope with it anyway.

At least this is a bug in Visual Studio allowing to set the aliases (or other properties) of references added by NuGet, which are reset after NuGet operations.

**Comment by gjsduarte** [comment]
+1

**Comment by brianpos** [comment]
+1

**Comment by andymac4182** [comment]
This could also be solved by https://github.com/NuGet/Home/issues/4989 probably

**Comment by PatoBeltran** [comment]
At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve this issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by andymac4182** [comment]
@PatoBeltran as per the issue I linked this isn't solved in PackageReference either.

**Comment by PatoBeltran** [comment]
@andymac4182 Yes, that issue should now track this bug. Sorry if I was not clear enough, we are trying to not have duplicate issues, and because we are moving to PackageReference, we should use that other issue for this specific issue.

**Comment by andymac4182** [comment]
No worries @PatoBeltran
