### ISSUE TITLE
NuGet push failure reason

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#3115]
Is there a way to distinguish the reason `nuget push` failed based on exit codes?  

Our official builds started failing recently on our NuGet package publish step.  The root cause was we simply failed to create the feed (oops). Took a bit of time to track that down as the problem though.  

It would have been much nicer if we could have examined the exit code and printed a helpful message to our log:
- Feed doesn't exist
- Bad API Key
- etc ...

Is there a way to do this today?

**Comment by rrelyea** [comment]
Are the error messages that we output for Nuget push failure not descriptive enough?
Seems like we should just make sure our error messages are helpful enough?

**Comment by PatoBeltran** [comment]
Closing as not enough information for the scenario.
