### ISSUE TITLE
Convert NuGet.BuildTasks to .NET Core

### ISSUE THREAD

**Issue by brthor** [NuGet/Home#3117]
In order to use https://github.com/NuGet/NuGet.BuildTasks with .net core msbuild in the dotnet cli, it needs to be converted to .net core.

A full list of needed changes:
- [ ] Convert https://github.com/NuGet/NuGet.BuildTasks to .NET Core
- [ ] Publish Nupkg with Task Binaries targeting netstandard.
- [ ] Alter ImportBefore/After .props/.targets files to fit new model 

cc @jasonmalinowski @rainersigwald @eerhardt

**Comment by eerhardt** [comment]
We no longer need this work. We are officially off of this package. It is no longer needed in the CLI and has been removed by https://github.com/dotnet/cli/pull/4288

Not sure I can close issues in this repo. @rrelyea - please close.
