### ISSUE TITLE
ContentFiles under any are not added for netstandard projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3118]
Create a package with a contentFile under any/any
ex: `contentFiles/any/any/myfile.txt`

Install the package into a netstandard project
#### Expected

contentFiles will show up in the lock file
#### Actual

No contentFiles are added

This is caused by ContentModel treating `any` as `dotnet` which is not compatible with `netstandard`, within the ContentFiles folder `any` should mean `any`

**Comment by dougbu** [comment]
/fyi @davidfowl this is the bug I mentioned yesterday evening.
