### ISSUE TITLE
Question - What is project.fragment.lock.json file?

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#3121]
In some projects we have seen this file generated either by VS, nuget or dotnet-cli. Can anyone clarify what is this json for?

Based on the conversation with @tillig at https://github.com/autofac/Autofac.Extras.Moq/commit/b7babdc3e969e3fe6728005a1a4abca307974742#commitcomment-18233479.

**Comment by dvalentine314** [comment]
I don't understand what it is in detail, but it's related to NuGet package management. Here's a quick explanation. [https://github.com/aspnet/Home/wiki/Lock-file](https://github.com/aspnet/Home/wiki/Lock-file)
