### ISSUE TITLE
nuget doesn't appear to utilize NuGetDefaults.config properly

### ISSUE THREAD

**Issue by sflanders** [NuGet/Home#3122]
We have setup nuget.exe (2.x and 3.x tried both) and added them to the path on our build servers.   We them added a NuGetDefaults.config to path C:\ProgramData\NuGet based on info here:

https://docs.nuget.org/consume/nuget-config-defaults

The problem is it never seems read it and always just recreates a nuget.config in the roaming path for the user.   For now we just added the config for each user that the build server uses   What i'm doing wrong?

**Comment by PatoBeltran** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for nuget.exe 3.x, please update to use nuget.exe 4.x and let us know if you need more help from us.
