### ISSUE TITLE
Guidance needed on how to publish packages for core to nuget and myget

### ISSUE THREAD

**Issue by govin** [NuGet/Home#3123]
My company internally uses myget to manage .NET 4.0 and .NET 4.5 packages. I would like to get some guidance on how to publish .NET Core 1.0 packages to internal myget as well as how to publish .NET Core 1.0 packages to nuget. 

Also, need guidance on how to do the above from mac/linux as we're trying to build the publishing pipeline in linux.

**Comment by rrelyea** [comment]
Before we address the first paragraph:
what do you mean by "internal myget"?

"dotnet push" or something similar is in our roadmap. We plan to deliver something in the timeframe of the next feature release of .NET Core.
Until then, pushing via "NuGet.exe push" is your best option.
Linux using Mono to run NuGet.exe may be an option now as well.

**Comment by govin** [comment]
@rrelyea by "internal myget", I mean we have a corporate account to which we publish packages which are meant for internal consumption within the company - https://companyName.myget.org/F/dev/

I'm looking for guidance on publishing Core packages to that myget instance which can be consumed by the rest of the company.

**Comment by rrelyea** [comment]
If you want to publish packages that can be consumed by .NET Core 1.0, you should look towards publishing packages with NetStandard support.

Choose a version depending on the API needs of your library. (1.0 - 1.6)
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Some NuGet servers may validate the target frameworks, and may need an update before they can support NetStandard. If you run into that, please contact the server vendor and ask them to start supporting NetStandard packages.

Does that answer your questions?

**Comment by rrelyea** [comment]
Closing. Please reactivate if this didn't answer your question, along with your follow up.
