### ISSUE TITLE
Update (all packages) wrongly verifies integrity of all projects in solution, declines to update packages

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#3125]
In my solution one of the projects has an internal project which was installed ignoring dependencies (too many of them while we need only interface definition).

When I open the Updates tab, select public NuGet.org feed, select All packages, click Update, I'm getting the following output:

> Attempting to gather dependency information for multiple packages with respect to project 'Api', targeting '.NETFramework,Version=v4.6.1'
> Gathering dependency information took 2.69 sec
> Attempting to resolve dependencies for multiple packages.
> One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'MediatR 2.0.2', 'PX3.Common 2.7.0 constraint: Bond.CSharp (>= 3.0.7)', 'PX3.Common 2.7.0 constraint: Bond.Runtime.CSharp (>= 3.0.7)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.Common (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.Caching (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.Configuration (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.Data (>= 6.0.1304.1)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.ServiceBus (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.WindowsAzure.Storage (>= 6.0.1304)', 'PX3.Common 2.7.0 constraint: Microsoft.ApplicationInsights.PerfCounterCollector (>= 1.2.3)', 'PX3.Common 2.7.0 constraint: Microsoft.ApplicationInsights.Web (>= 1.2.3)', 'PX3.Common 2.7.0 constraint: Microsoft.ApplicationInsights.WindowsServer (>= 1.2.3)', 'PX3.Common 2.7.0 constraint: Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel (>= 1.2.3)', 'PX3.Common 2.7.0 constraint: Microsoft.CommonSchema.Bond (>= 2.1.0)', 'PX3.Common 2.7.0 constraint: Microsoft.CommonSchema.Services (>= 4.0.0)', 'PX3.Common 2.7.0 constraint: Microsoft.Diagnostics.Tracing.EventRegister (>= 1.1.26)', 'PX3.Common 2.7.0 constraint: Microsoft.Diagnostics.Tracing.EventSource (>= 1.1.26)', 'PX3.Common 2.7.0 constraint: Microsoft.Diagnostics.Tracing.EventSource.Redist (>= 1.1.26)', 'PX3.Common 2.7.0 constraint: Microsoft.Diagnostics.Tracing.TraceEvent (>= 1.0.23)', 'PX3.Common 2.7.0 constraint: Microsoft.IdentityModel.Clients.ActiveDirectory (>= 2.19.208020213)', 'PX3.Common 2.7.0 constraint: Microsoft.IT.Diagnostics.ActivityInstrumentationDefinitions (>= 1.1.0.1)', 'PX3.Common 2.7.0 constraint: Microsoft.IT.Diagnostics.ActivityInstrumentationObserver (>= 1.1.0.1)', 'PX3.Common 2.7.0 constraint: Microsoft.IT.Diagnostics.AI.ActivityInstrumentation (>= 1.1.0.5)', 'PX3.Common 2.7.0 constraint: Microsoft.IT.Diagnostics.ETW.ActivityInstrumentation (>= 1.1.0.1)', 'PX3.Common 2.7.0 constraint: Microsoft.IT.Diagnostics.SLL.ActivityInstrumentation (>= 1.1.0.2)', 'PX3.Common 2.7.0 constraint: Rx-Core (>= 2.2.5)', 'PX3.Common 2.7.0 constraint: Rx-Interfaces (>= 2.2.5)', 'PX3.Common 2.7.0 constraint: Rx-Linq (>= 2.2.5)', 'PX3.Common 2.7.0 constraint: System.IdentityModel.Tokens.Jwt (>= 4.0.2.206221351)', 'PX3.Common 2.7.0 constraint: System.IdentityModel.Tokens.ValidatingIssuerNameRegistry (>= 4.5.1)', 'PX3.Common 2.7.0 constraint: Microsoft.IdentityModel.Protocol.Extensions (>= 1.0.2.206221351)', 'PX3.Common 2.7.0 constraint: xpf.Script.SQLServer (>= 0.1.1.1)', 'WindowsAzure.ServiceBus 3.2.4', 'WindowsAzure.Storage 7.0.0'
> Unable to find a version of 'EnterpriseLibrary.TransientFaultHandling.Data' that is compatible with 'PX3.Common 2.7.0 constraint: EnterpriseLibrary.TransientFaultHandling.Data (>= 6.0.1304.1)'.
> ========== Finished ==========
> Time Elapsed: 00:00:02.9627141

And nothing happens.

However, I can update packages, one by one, by clicking Install in right menu.

**Comment by rrelyea** [comment]
What version of NuGet are you using?
What version of VS?

How can we reproduce the problem? (please give specific steps)

**Comment by abatishchev** [comment]
NuGet 3.5.0.1484
Microsoft Visual Studio Enterprise 2015 Version 14.0.25422.01 Update 3
Microsoft .NET Framework Version 4.6.01055

**Comment by rrelyea** [comment]
Repro Steps? 
What kind of projects should we create (and how should we modify them) to minimally reproduce the problem?

**Comment by abatishchev** [comment]
I can present my desktop (internal alias alexbat) if you'd like.

In general, we have the following disposition:
- Package1 is on public feed and has an update available 
- Package2 is on private feed 
- Package2 is installed without its dependency Package3 (no matter what kind of feed it is on)
- Project1 references both Package1 and Package2

I open Manage packages for solution (however, it's same for project) and click Select all packages and then Update.

**Comment by jainaashish** [comment]
Select all sources from PackageManagement UI like below and then try the same scenario.

![image](https://cloud.githubusercontent.com/assets/18219758/17788071/bcce361a-6540-11e6-9de7-ac35f651250e.png)

**Comment by abatishchev** [comment]
Yes, this seems to fix the issue. I'll come back on this if it does not. Thanks!
