### ISSUE TITLE
Fix owner of Nuget.Configuration

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3126]
https://www.nuget.org/packages?q=nuget.configuration

**Comment by madnemesio** [comment]
Hi Good day.
Im having this problem when creating a new Project, referencing NuGet. 

Can you help mw with this?

![image](https://cloud.githubusercontent.com/assets/19720919/16859558/6dfdf748-49f5-11e6-975a-7329761ed0f8.png)

**Comment by rohit21agrawal** [comment]
removed deepak as owner from NuGet.Configuration and NuGet.PackageManagement.
