### ISSUE TITLE
The default restore verbosity is too verbose

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#3129]
See https://github.com/dotnet/cli/pull/3229#discussion_r64662866 and https://github.com/dotnet/cli/pull/3229#issuecomment-221735677.

Currently the CLI is setting the default verbosity to 'minimal' if one isn't set during `dotnet restore`.  I would like to remove that code in the CLI and have the CLI strictly pass all the args straight through to NuGet. In order to remove the code in CLI's `dotnet restore`, we need NuGet's default verbosity to be less verbose, or else we would be regressing the fix made in https://github.com/dotnet/cli/pull/3229.

**Comment by eerhardt** [comment]
This issue is blocking https://github.com/dotnet/cli/issues/3862.

**Comment by harikmenon** [comment]
@blackdwarf - Z, we need to chat about this like we discussed before we fix this.

**Comment by PatoBeltran** [comment]
Closing as https://github.com/dotnet/cli/issues/3862 appears to be complete. Please reopen if needed
