### ISSUE TITLE
packages.config operations should use the HTTP cache

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3132]
The following operation already uses the HTTP cache:
- `nuget.exe restore project.json`

The following operations do NOT use the HTTP cache and could benefit from it:
- `nuget.exe install ID -version VERSION`
- `nuget.exe install packages.config`
- `nuget.exe restore packages.config`

**Comment by PatoBeltran** [comment]
This issue is being solved by https://github.com/NuGet/NuGet.Client/pull/1703.
