### ISSUE TITLE
Updating multiple packages with rollback leaves the project in a broken state

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3139]
Repro 
1) Download Project from here https://1drv.ms/u/s!AiAm-9ay0h6wjpo4x5bCzer80z5R9A
2) In the Quandrant PCL you will see 2 updates in the nuget package manager
3) Update both

Expected
If any updates fail, then then it should be rolled back without leaving the project in a broken state

Actual
project is broken

**Comment by joelverhagen** [comment]
I was able to reproduce the problem on NuGet 3.4.4-rtm-1321, Visual Studio 2015 Update 3, and by doing a batch restore on the Irony project (not Quadrant). Investigating...
