### ISSUE TITLE
[NuGet.VisualStudioExtension] IsPackageInstalled returns false, even though package is installed in the project

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#314]
@PeterJausovec
[NuGet.VisualStudioExtension] IsPackageInstalled returns false, even though package is installed in the project

Call to IsPackageInstalled on IVsPackageInstallerServices returns false, even though package is installed.

**Comment by yishaigalatzer** [comment]
This is fixed, @emgarten is going to add the commit and close.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.VisualStudioExtension@d30ff6b7353465d41683408abd3d02a21c2b87b7
