### ISSUE TITLE
The type initializer for 'NuGet.ProxyCache' threw an exception

### ISSUE THREAD

**Issue by drieseng** [NuGet/Home#3144]
I get the following error whenever I try to run the nuget command line client from a network share:

The type initializer for 'NuGet.ProxyCache' threw an exception.
  An invalid argument was supplied

Any idea what may be causing this ?

**Comment by rrelyea** [comment]
Version of NuGet.exe?
Did this work before?

**Comment by drieseng** [comment]
It's version **3.4.4.1321**.
Can't tell if it worked before.
Is there a way to get the full stack trace?

**Comment by rrelyea** [comment]
Ok. Going to put in "future" milestone instead of 3.5 or 3.6...as it looks like this is a newly discovered issue, and not a regression. 
Please use NuGet.exe from the local drive for now.

If anybody has info different than that, please chime in.

**Comment by drieseng** [comment]
I did some more tests:
- 2.8.6: OK
- 3.2.0: FAIL
- 3.3.0: FAIL
- 3.4.3: FAIL
- 3.4.4: FAIL
- 3.5.0-beta2: OK

**Comment by PatoBeltran** [comment]
Per discussion, this seems to be fixed in 3.5. Closing issue, please feel free to reopen if this is still a problem
