### ISSUE TITLE
Floating versions: Is the wrong prerelease version being resolved here?

### ISSUE THREAD

**Issue by wbradney** [NuGet/Home#3147]
This is with v3.5.1.1597
I just observed some very strange behavior after converting a couple of core projects from using a fixed version ref to using a floating version.

eg. 0.1.1-pre12 => 0.1.1-*

ProjectX references PackageA 0.1.1-*
PackageA references PackageB 0.1.1-*

The intent here was to resolve to the latest prerelease version, on the assumption that prerelease versions would be sorted alphanumerically for the purpose of determining "latest".

In my internal repo I have several versions of those referenced packages, eg

PackageA 0.1.1-pre01
PackageA 0.1.1-pre02
PackageB 0.1.1-alpha1
PackageB 0.1.1-alpha2
PackageB 0.1.1-pre01
PackageB 0.1.1-pre02

I expect that any floating reference PackageB 0.1.1-\* would resolve to PackageB 0.1.1-pre02 in this case.
What I actually see is conflict warnings and errors between PackageB 0.1.1-alpha1 and PackageB 0.1.1-pre02.

Am I misunderstanding how a floating version of a prerelease package should work?

**Comment by wbradney** [comment]
Even more weird, as an experiment I removed all of the _-alpha_ packages from my repo and now the conflict is between 0.1.1-pre01 and 0.1.1-pre02. 
It looks like at least one resolve is resulting in the _first_ or _earliest_ version...
If I revert my project.json changes back to fixed versions everything builds fine.
Also, if I _add_ a redundant floating reference to the problem assembly, everything builds fine.
I'll try to work on a repro when I get time.

**Comment by rrelyea** [comment]
Can you focus on 3.5.0 builds? ( dev branch )
3.5.1 is a little behind 3.5.0 now...

Still a problem with 3.5.0? Which build?

**Comment by wbradney** [comment]
I just did a rebuild with 3.5.0.1520 and I get the same error

**Comment by wbradney** [comment]
While trying to create the repro I noticed something weird: in the .nupkg for PackageA (which has a floating dependency on PackageB), I see this:

```
    <dependency id="PackageB" version="0.1.1--" exclude="Build,Analyzers" />
```

Is this even valid?
Also, in VS I can't add a reference to PackageA from ProjectX (it doesn't show up in the Repo). If I try to add a ref using the Package Manager Console I get:

`An error occurred while retrieving package metadata for 'PackageA'`

So it looks like nuget pack might not be working with floating refs to dependencies.

**Comment by wbradney** [comment]
I was using the latest beta because I need the fix for issue 2817. I just noticed my builds are now rebuilding even when nothing changed (again). Argh. :-)
Any ETA on a consolidated release candidate with the fix for 2817?

**Comment by PatoBeltran** [comment]
This issue was resolved. Please update and use `msbuild /t:pack` from VS 2015 Update 3 or later, or `dotnet pack` from dotnet.exe 2.0 or later and give it a try. If you keep having issues feel free to open a new issue with detailed repro steps.
