### ISSUE TITLE
[NuGet.VisualStudioExtension] Feature suggestion: Multiple updates. 

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#315]
@Bartmax 
It would be great if one can select multiple project and update them all in once action.

Let's say I have 
Microsoft.Owin.Security.Facebook
Microsoft.Owin.Security.Google
Microsoft.Owin.Security.Twitter

the update all was removed (i can understand why) but it would be much better if I can just pick multiple packages and update all at once.

Thanks

**Comment by deepakaravindr** [comment]
Comment from @emgarten, as copied:

update-package (with no params) from the powershell console still allows you to update all packages, there are a few other options there that might help you out for bulk operations.

**Comment by xperiandri** [comment]
Absolutely agree!

**Comment by yishaigalatzer** [comment]
Done.

We can update all for multiple packages.

**Comment by xperiandri** [comment]
Cool! Which build to try?

**Comment by yishaigalatzer** [comment]
3.3, it will go out shortly.

Shoot me an email if you want an early peek. y i g a l a t z @ msft
