### ISSUE TITLE
Performance: Improve ProjectRestoreCommand.GetRuntimeGraph

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3152]
While profiling restore `ProjectRestoreCommand.GetRuntimeGraph` showed up as the majority of the total restore time. The method should be optimized and caching added if it makes sense.

**Steps**
1. clone https://github.com/troydai/live.asp.net/
2. Revert the fix for https://github.com/NuGet/Home/issues/3150 or add runtimes to the project.json file
3. Restore src/live.asp.net

**Expected**
Building the runtime graph should be much faster than the resolver walk

**Actual**
ProjectRestoreCommand.GetRuntimeGraph takes 4x longer to run than the resolver walk

**Comment by emgarten** [comment]
This should go into 3.5.0-rtm also //cc @rrelyea

**Comment by jainaashish** [comment]
Need to merge to 3.5.0

**Comment by jainaashish** [comment]
Merged to 3.5.0 with 369a708b3590b3b0ccab9f737a79bf252d64ca3b
