### ISSUE TITLE
New commandline switch? -- NuGet Install -tfm netfx35

### ISSUE THREAD

**Issue by MV10** [NuGet/Home#3153]
I have a scenario in which a NuGet package contains a set of files targeting two frameworks, lib/net35 (for a Unity game project) and lib/netstandard16 (for reusing the DLLs server-side in a .NET Core REST API). No problems loading up my package on the Core side through VS2015 as normal.

The trouble is getting the net35 files into the Unity game project. Unity routinely overwrites the solution/project files so NuGet doesn't really work well with Unity projects, and DLLs should be dropped somewhere under an "Assets" folder in a Unity project folder.

I tried to create a simple batch file in the folder where I store my packages with a command like this:

`nuget install ClientLibraries -OutputDirectory "C:\Users\Public\Documents\Unity Projects\Client\Assets\GameDLL"`

However, that dumps _both_ framework libs into the folder, which is a problem.  Would it be a big deal to add a switch along the lines of "-Framework net35" to the install command for times when a VS project file isn't around to consult?

**Comment by rrelyea** [comment]
NuGet install was not designed to work with multiple TFMs. In the short term, we won't be able to address this feature request. Putting into future.

**Comment by PatoBeltran** [comment]
We haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
