### ISSUE TITLE
When a empty `<references/>` element is specified all dlls are still added as references

### ISSUE THREAD

**Issue by samholder** [NuGet/Home#3154]
If I have a nuspec into which I have explicitly added an empty `<references/>` element I would expect that no references are added. However actually it seems to treat the omission of a `<references>` tag and it being empty as the same thing, and just adds references to all the dlls.

My use case is a plugin for an extension to VS. So I want to install the package and modify the app.config to point at the dll for the plugin in the packages folder. Then my extension will load the plugin from the dll for use at design time, but the project I'm adding it to doesn't need it at runtime, so no reference should be added.

I'll be happy to work up a PR for the fix for this if someone could point me in the general direction for the code for it.

**Comment by rrelyea** [comment]
What version of NuGet.Tools.vsix are you using?
What older version of NuGet.Tools.vsix used to work the way you wanted?

**Comment by samholder** [comment]
Sorry if I wasn't clear. There is no version in which this used to work as far as I am aware, although this is the first time that I have tried to use it, so I can't be 100% sure.

I'm reporting this as it seems from the documentation that this could work this way and if it did, it would give package authors an extra option for installing their packages. In order to get the functionality I want now I have to add my dll to the `Tools` folder so I can reference it from there but it is not added to the project as a reference or as a part of the solution.

As I said I'd be happy to submit a PR for this change when I get a little time to investigate where the `<references>` tag is used.

**Comment by harikmenon** [comment]
@samholder : Can you show where in the documentation were we allude to this? This is something that we wont support and if it is in the documentation we will make it clear it is not supported. Going the tools route is right thing here.

Making assumptions to how metadata is specified is guaranteed to break a number of customers based on our past experiences. There might be a number of folks who already have an empty tag in their metadata and would expect it the dependencies to get added nonetheless.

**Comment by samholder** [comment]
@harikmenon to my reading there are a couple of places on [this page](https://docs.nuget.org/create/nuspec-reference):

one says:

> v1.5 Names of assemblies under lib that are added as project references. If unspecified, all references in lib are added as project references. When specifying a reference, only specify the name and not the path inside the package.

This implies that without the tag all references will be added, but with it only the names of assemblies under lib are added. So if I have the `<references/>` tag then only the specific `<reference>` elements contained within will generate references.

Also further down:

> Use the <references /> element to explicitly specify assemblies that the target project should reference.

...

> If this element is omitted, then the usual behavior applies, which is to reference every assembly in the lib folder.

Again it implies that if I specify the `<references>` tag then I should be able to control which references get added and only if it is omitted (note: not empty) will all references be added.

Seems a shame that the functionality can't be extended to support this, but I understand that you might get a slew of issues if you change this behaviour from under peoples feet.

Thanks for the reply though, updating the documentation would be good.

**Comment by harikmenon** [comment]
@karann-msft. Can you please dupe this to the docs repo and add a issue to make sure that we call out specifying <references/> is a no-op, i.e reference will still get added.
