### ISSUE TITLE
BadImageFormatException

### ISSUE THREAD

**Issue by johnnycamby** [NuGet/Home#3155]
The past 2 days when i was using NuGet to add new packages to an mvc web application and then after debugor run the application , **a yellow screen of death with 'BadImageFormatException: Cannot load a reference assembly for execution.' has always been displayed**. 
I have checked most of stackoverflow and codeproject  solutions but non of their solutions has solved my problem. 
I then decide to create new web mvc application and on running the application works properly but as soon as i add packages using NuGet the same  **yellow screen of death with 'BadImageFormatException: Cannot load a reference assembly for execution.' is displayed.** 
I need help. Is using NuGet leading to this problem. Help needed.
- I am using Visual Studio 2015 with the latest NuGet update.

**Comment by johnnycamby** [comment]
Alright I now solved the problem though i do think it's not the right way. 
I went to the 'web.config' file and commented the **'System.Runtime'** assembly dependency .But still on building the application the **'System.Runtime'** assembly dependency is added automatically. Lead to doing the same process of comment it before running the application.
I don't think this is the solution to my problem, any better solution would be of great help.

**Comment by rrelyea** [comment]
Please tell us the exact version of NuGet that you are using.
Also, can you please give us full repro steps and/or a repro solution?

**Comment by johnnycamby** [comment]
NuGet version 3.5.0.1484

**Comment by PatoBeltran** [comment]
We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
