### ISSUE TITLE
How to filter for dotnetcore?

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#3156]
In VS, from a DotNetCore app or lib, I cannot find any way to filter the nuget packages that can be effectively used in .NET Core.
This means that I find a package, add it and obviously fails.
Am I missing something?

**Comment by harikmenon** [comment]
No, you are not. We don't yet support filtering the list in VS this way. A more detailed answer by @yishaigalatzer that applies to this case https://github.com/NuGet/Home/issues/2084
