### ISSUE TITLE
Remove Package missing in latest version

### ISSUE THREAD

**Issue by joebeernink** [NuGet/Home#3158]
I'm running VS2015 with NuGET 3.4.4.1321 and when I bring up the NuGET Package manager window, click on installed packages, select a NuGET package previously installed, I no longer see the Remove Package button on the UI.  I co-worker with an earlier version of 3.4 does see it.

![image](https://cloud.githubusercontent.com/assets/3885965/16923194/ea3988d8-4ccd-11e6-9016-2da87d90f322.png)

**Comment by rrelyea** [comment]
Can you please try to repro with 3.5.0-beta2 vsix? (see nuget.org/downloads)
Fixed there?

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
