### ISSUE TITLE
[NuGet.VisualStudioExtension] if the filter "Upgrade available" is choosen, then the default action should be "Upgrade"

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#316]
@DerAlbertCom

I've just installed AngularJS in seven projects ... instead of updated one.

And it happens before to me.

**Comment by feiling** [comment]
Fixed. https://github.com/NuGet/NuGet.PackageManagement/commit/f9d1fb990fc28f206da4cce23e97e8411a51b01c
