### ISSUE TITLE
nuget pack for project.json ignores packOptions tags like summary, authors , owners etc

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#3161]
packOptions in project.json supports the following tags:
(reference : https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json#packoptions)
summary
tags
owners
releaseNotes
iconUrl
projectUrl
licenseUrl
requireLicenseAcceptance
repository
files

So far, we only support files and take the value of other tags from the root of project.json instead of the ones from packOptions.

**Comment by rrelyea** [comment]
Assuming we've never shipped a released version with support for metadata at the root of Project.json, let's ship support in nuget pack for packoptions only. If we do that syntax will work with dotnet pack and nuget pack. DotNet pack today supports the older metadata at the root. Let's move towards the packoptions only.

**Comment by rohit21agrawal** [comment]
@rrelyea 
we currently do not have support for repository...should we add it?

**Comment by rrelyea** [comment]
what does dotnet pack do with it? add it to the nuspec?

**Comment by rohit21agrawal** [comment]
@rrelyea dotnet pack doesn't seem to add "repository" to nuspec, so I have left it out.
