### ISSUE TITLE
API to get the highest NetStandard compatible with a set of TFMs

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#3163]
The PCL tooling needs to take a set of TFMs and get the highest NetStandard that can be installed into each TFM. For example an input of `[net46, uap10.0]` would return `netstandard1.3` based on the netstandard compat chart. This can be implemented using `IVsFrameworkCompatibility.GetNetStandardFrameworks` and `IVsFrameworkCompatibility.GetNearest`, but perhaps there should be a dedicated API within NuGet for this operation?

cc @joelverhagen

**Comment by rrelyea** [comment]
Sounds like the update you are working on will have to work w/o this API (or with the API if it existed). We'll put in our backlog.

**Comment by joelverhagen** [comment]
Yes, @rchande and I spoke offline about how to achieve this with the existing IVS APIs. It's a simple algorithm but eventually should be mastered by us with a high level API.

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
