### ISSUE TITLE
PowerShell/OneGet search resource

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#317]
We're currently using UISearchResource, but need more options for OneGet and PsGet:

Query

SearchFilter should include PackageType (e.g. PowerShell)
[stretch] minimum, maximum, required version
Results

Custom metadata (especially PowerShell)
Copyright, Language, Release Notes

**Comment by yishaigalatzer** [comment]
moving out to beta 1. @emgarten who is waiting for this?

**Comment by yishaigalatzer** [comment]
I didn't hear any ask for this, will address when customer asks come in
