### ISSUE TITLE
Cannot install packages into C++/CLR project

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#3171]
As was reported in https://github.com/Reactive-Extensions/Rx.NET/issues/233, NuGet is not properly installing packages into C++/CLR projects.

To repro with VS 2015 U3:
1.  Create new C++ Console application using the "CLR Console Application" template
2.  Try to add `System.Interactive` using NuGet, either the package manager console or the UI

It fails with the following error:

`Could not install package 'System.Interactive 3.0.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by PatoBeltran** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.

**Comment by Laibalion** [comment]
This issue is still present in VS2017 15.5.1 (latest update)

**Comment by BennyH26** [comment]
Is there a solution or workaround here?
