### ISSUE TITLE
nuget 3.4.4-rtm fails when processing "bootstrap.3.3.4" or other older packages

### ISSUE THREAD

**Issue by schuettecarsten** [NuGet/Home#3172]
nuget 3.4.4-rtm fails when processing "bootstrap.3.3.4" or "jquery.2.1.3" packages. Both packages are older but should be processed by newer nuget versions without problems.

```
Restoring NuGet package bootstrap.3.3.4.
Die Eingabezeichenfolge hat das falsche Format.
```

```
Adding package 'jQuery.2.1.3' to folder '...'
Added package 'jQuery.2.1.3' to folder '...'
Die Eingabezeichenfolge hat das falsche Format.
```

nuget 3.3.0 works fine here.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
