### ISSUE TITLE
NugetPack .csproj + project.json: mappings do not preserve partial directory structure

### ISSUE THREAD

**Issue by BladeWise** [NuGet/Home#3173]
Using `nuget pack projectname.csproj` and having a nuspec like this

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <projectUrl>http://www.sample.it</projectUrl>
    <iconUrl>http://www.sample.it/sample.gif</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
    <copyright>Copyright 2013</copyright>
    <tags>sample pack nuget</tags>
  </metadata>
  <files>
    <file src="bin\Debug\net461\**\Sample.resources.dll"
          target="lib\net461"/>
  </files>
</package>
```

produced a package where `lib/net461` contained all `Sample.resources.dll` files in proper subfolders as specified in the pattern, i.e.
`bin\Debug\net461\en-US\Sample.resources.dll` -> `lib\net461\en-US\Sample.resources.dll`.

Using the equivalent (in terms of included files) project.json

``` json
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    "netstandard1.3": {}
  },
  "packOptions": {
    "summary": "This is the summary of the packatge.",
    "tags": "test sample nuget",
    "releaseNotes": "Test release",
    "iconUrl": "http://www.sample.it/sample.gif",
    "projectUrl": "http://www.sample.it",
    "licenseUrl": "http://www.sample.it/license.md",
    "requireLicenseAcceptance": false,
    "files": {
      "mappings": {
        "lib/net461": {
          "include": [
            "bin/Debug/net461/**/Sample.resources.dll"
          ]
        }
      }
    }
  }
}
```

will not produce the same structure, producing instead a mapping  like
`bin/Debug/net461/en-US/Sample.resources.dll` -> `lib/net461/Sample.resources.dll`.

I even tried using `includeFiles` insted of `include`

``` json
{
  "supports": {},
  "dependencies": {
    "Microsoft.NETCore.Portable.Compatibility": "1.0.1",
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    "netstandard1.3": {}
  },
  "packOptions": {
    "summary": "This is the summary of the packatge.",
    "tags": "test sample nuget",
    "releaseNotes": "Test release",
    "iconUrl": "http://www.sample.it/sample.gif",
    "projectUrl": "http://www.sample.it",
    "licenseUrl": "http://www.sample.it/license.md",
    "requireLicenseAcceptance": false,
    "files": {
      "mappings": {
        "lib/net461": {
          "includeFiles": [
            "bin/Debug/net461/**/Sample.resources.dll"
          ]
        }
      }
    }
  }
}
```

but in this case the full relative path is retained, generating something like
`bin/Debug/net461/en-US/Sample.resources.dll` -> `lib/net461/bin/Debug/net461/en-US/Sample.resources.dll`

Is this the intended behavior? How can I achieve the same result as using a nuspec file?

This [zip file](https://github.com/NuGet/Home/files/373946/Sample.zip) contains a project where I have performed multiple tests regarding files mapping. The generated package is [this one](https://github.com/NuGet/Home/files/373952/Sample.1.2.3.4.nupkg.zip).

**Comment by rrelyea** [comment]
As we mentioned in #3184, NuGet pack will not be adapted to work with Project.Json mappings. But we will be solving the scenario in our move to msbuild.
