### ISSUE TITLE
External: Project "Default" is not found error when copying VS2105 ASP.NET Core project from windows 8.1 to Windows 7

### ISSUE THREAD

**Issue by saf-itpro** [NuGet/Home#3176]
On my windows 8.1 with VS2015 I created [this ASP.NET tutorial project ](https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html) that ran fine. But when I copied the project directory to windows 7, deleted the Migration folder and ran the following command, I get the `Project "Default" is not found` error:
`PM> Add-Migration MyFirstMigration -context BloggingContext`

**Note**: I've ASP.NET Core 1.0 and VS2015 Update 3 installed on both machines
Thanks..Saf

**Comment by rrelyea** [comment]
Please start with this issue in the EF repo. Nothing from the context you have provide makes this sound like a NuGet issue:
https://github.com/aspnet/EntityFramework

**Comment by saf-itpro** [comment]
@rrelyea Rob, Per your suggestion, I've moved the issue to the link you provided. Moreover, the issue does not occur after I migrated Windows 7 to windows 10 as I pointed out in the my post there.
