### ISSUE TITLE
list only packages that are compatible

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#318]
It would be cool to have an API that lets me list only those packages that are compatible with the framework version of my current project. So for example if my current project targets .NET 2.0 and a package only has content for .NET 4.0 (\net40 is present but \net20 is not) it should not be listed in the first place.

**As a bonus it would be great that if an earlier version of this package exists that does support my current target framework it should be possible to list it instead.**

As the amount of packages grows, it becomes harder and harder to find to right package, especially when working with legacy code.

This is a similar issue: http://stackoverflow.com/questions/22568725/is-there-a-way-to-specify-net-framework-version-argument-while-using-install-pa

**Comment by davidfowl** [comment]
Server side? Noooooooooooooooo

**Comment by csharpfritz** [comment]
I think this has to be on our radar.  If you're targeting a core framework,
you won't want to be presented with a collection of packages that don't
support it.



Jeff

**Comment by emgarten** [comment]
This link isn't showing up, but this was copied from a customer bug in another repo.

**Comment by yishaigalatzer** [comment]
@davidfowl please talk with @coolcsh

This is to support both the client and the server.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/4071 
Closing this one.
