### ISSUE TITLE
ASPNET legacy projects in VS15 - packages are not expanded after template completes?

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3182]
Tracked by 242518 & 242789 in TFS.

[If we need a fix in Preview4, we'll need to check into dev, create a branch off of last commit in 1592, and cherry-pick that fix there.]

**Comment by rrelyea** [comment]
until we have verified the fix on vs15 as well, reopening.

**Comment by drewgillies** [comment]
Have checked in a fix from @emgarten (https://github.com/NuGet/NuGet.Client/commit/2eb229bcd9b0aeb7e25a84ced1686cf26269c8d3) to the VS build, awaiting integration tests. Will consider fixed until we hear otherwise.
