### ISSUE TITLE
Fix publishing of VS15 symbols for CI builds

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3185]

**Comment by rrelyea** [comment]
VS15 vsix is one of the problems. Let's discuss all the problems, and then decide which to fix when.

**Comment by rrelyea** [comment]
Let's keep this open until we've verified and inserted into preview4.

**Comment by alpaix** [comment]
Spotted minor flaws in build pipeline:
1. NuGet.Core.pdb is copied from a wrong "default" location of 2.11 instead of 2.13.824
2. Assemblies in *.symbols.nupkg are unsigned
3. nuget.exe doesn't have corresponding pdb

1 & 2 fixed manually. 3 is not relevant to VS15 scenario.
