### ISSUE TITLE
GB18030 investigation 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3186]

**Comment by mishra14** [comment]
Updated the assigned task with drafted report and demo video.

Artifacts - 
[Report](https://microsoft.sharepoint.com/teams/DD_Tenets/World%20Ready/_layouts/15/guestaccess.aspx?guestaccesstoken=1Q%2fRRT2Tx13XztxQw91CWj5%2f6VZj4fhkQIxTcK9aOq0%3d&docid=2_00e88f7bad8604d208924bc3282670b72&rev=1) 
[Video](https://microsoft.sharepoint.com/teams/DD_Tenets/World%20Ready/_layouts/15/guestaccess.aspx?guestaccesstoken=idAAPqCj7cPkD29tuCxW0WmbMg5C0sUt9%2fJIJK5qI9Q%3d&docid=2_0e438014b77cd4a9aaf95c2329bddc71b&rev=1)

Waiting for feedback from Kevin.

**Comment by rrelyea** [comment]
If we need to track more work in future milestones, please open a new issue.
