### ISSUE TITLE
[Gallery] Package disappear from the search results for api.nuget.org after unlist and then relist in the gallery

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#319]
Repro steps:
1. log onto nuget.org
2. find one of your packages, search from api.nuget.org to confirm it can be found
3. unlist that package, wait 5-10 minutes
4. confirm the package cannot be found now, on both nuget.org and api.nuget.org
5. relist the package, wait for 1-2 hours or so

Expected: the package can be found via search on both api.nuget.org and nuget.org

Actual: it cannot be found on api.nuget.org, although can be found via nuget.org

**Comment by yishaigalatzer** [comment]
Fixed
