### ISSUE TITLE
ManifestReader round-tripping (read/write) fails when NuSpec contains an unsupported framework

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#3193]
ManifestReader round-tripping (read/write) fails when NuSpec contains an unsupported framework.

Reason is this check for `.IsUnsupported`:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestReader.cs#L264

Can this check be moved out of the ManifestReader so that it reads any manifest (even with an unsupported framework)?

**Comment by rrelyea** [comment]
@maartenba  - Timeframe needed?

**Comment by maartenba** [comment]
Your call :-) Would be useful to have (e.g. for package edits in gallery). Since it's only that one specific line being in our way, I'm not sure how much work it would be to move that check out so roundtripping works?

**Comment by maartenba** [comment]
Not sure this is still relevant.
