### ISSUE TITLE
Project works locally but not when download from Nuget

### ISSUE THREAD

**Issue by facundomedica** [NuGet/Home#3195]
I'm trying to make my own Nuget Package (a fork of https://github.com/TareqAteik/ExtendedListView). When I import the project it works perfectly, but when I add it through the Package Manager it throws a 'System.NullReferenceException' the DLL and the ListView (which referenced from this library) doesn't scroll.

Is there any common problem that I'm not aware of? (I've tried uploading it in Debug and Release)

**Comment by rrelyea** [comment]
Please give us VS and NuGet version numbers. Also, precise repro steps.

**Comment by facundomedica** [comment]
@rrelyea sorry but the issue, like always as soon I ask, I see the problem. Bad configuration of Nuget. I'll keep reading. (Sorry again!)
