### ISSUE TITLE
Add API to NuGet.Core.dll (NuGet 2.x) to read package types

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3197]
It's supported in the V3 APIs.

**Comment by rrelyea** [comment]
NuGet.Server should support PackageType feature in nuspec.
In order to do this, they are moving to v3 apis...timeframe??? 
If too long, we could consider doing this work in v2 apis?

@maartenba

**Comment by maartenba** [comment]
It's quite an undertaking. @qianjun22 can prioritize.

**Comment by PatoBeltran** [comment]
Closing, please leave a comment if you need this reopen.
