### ISSUE TITLE
Nutget.server crashes when package id is from GB18030 char-set

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3200]
Repro - 

Start a nuget.server. Add a package with id from GB18030 char-set (e.g. - 㐀㒣㕴㕵㙉㙊䵯䵰䶴䶵).

The server throws unhandled exception soon after or on adding a new package.

The cause could be due to the move away from nuget core(?)

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#3159
