### ISSUE TITLE
Package restore fails to restore when 0-byte .tmp files exist

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#3202]
A few days ago, I updated to 3.5-beta2 in order to be able to restore my asp.net core packages from MyGet. However, it broke all other apps on the build agents (cannot find package in 'local cache directory').

Reverted back to 3.2 (or whatever version is currently available via _nuget update -self_), but I still have lots of issues because I cleared the cache hoping to solve some issues with the 3.5 beta. 

For example:

```
Restoring NuGet package Fody.1.30.0-beta01.
WARNING: Unable to find version '2.0.1.61' of package 'ControlzEx'. 
```

But it's _definitely_ available on NuGet. This keeps failing, no matter how often I restart the build. After investigating, it looks like there is a 0bytes .tmp file in the cache (%localappdata%\nuget\cache). As soon as I delete that, run the build again, it starts working. 

![image](https://cloud.githubusercontent.com/assets/1246444/17077835/3afd0072-50e0-11e6-9e7e-7175ce17869a.png)

I think NuGet should not only check for the existence of the file, but should require an exclusive lock on the .tmp file. If that succeeds, either delete it or overwrite it, but don't silently fail just because a file is there.

**Comment by emgarten** [comment]
The v2 machine cache (`%localappdata%\nuget\cache`) should no longer be used as of 3.4.0, it looks like some old code may be getting used here if removing the tmp file resolves the problem.

**Comment by GeertvanHorrik** [comment]
It is very reproducible. I had 8 packages with 0 byte tmp files. All builds that use these packages failed until I deleted them.

**Comment by rrelyea** [comment]
Can you please try the latest daily build of NuGet.exe? We've removed old code that handled this, so it may very well be working in 3.5 (post beta2)
http://nuget.org/downloads

**Comment by GeertvanHorrik** [comment]
This RC 1 does fix #3208 as well, so I'll check this one as well.

**Comment by GeertvanHorrik** [comment]
Yep, can restore with 0byte packages now. It doesn't restore into this directory any longer though, so I guess %LocalAppData%\NuGet\Cache can be deleted entirely?

**Comment by emgarten** [comment]
Thanks for verifying! Yes, you can remove `%LocalAppData%\NuGet\Cache`. 3.5.0 uses the global packages folder to store packages.

**Comment by PatoBeltran** [comment]
Closing issue as it does not repro in current latest version
