### ISSUE TITLE
Solution Package Manager UI version combo-box gets clipped in default layout of VS

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3204]
**Repro Steps:**
1. Create a new C# ConsoleApplication.
2. Right-click the solution and select “Manage NuGet Packages for Solution…”.
3. Click “Browse” tab and click anyone package.
4. Look at the version combo-box on the right pane.

**Expected Result:**
The drop-down button (on the right of the version combo-box) show correctly.

**Actual Result:**
The drop-down button get clipped as below screenshot.
![dropdownbuttonlostindefaultlayout](https://cloud.githubusercontent.com/assets/20632775/17096548/72d232e4-528c-11e6-9a98-7758a3fd2eb9.png)

**Note:**
1. The issue also repro on VS2015Update3 w/ NuGet 3.4.4.
2. It doesn’t repro in the project level Package Manager UI for the same scenario.
3. It will never repro after you resize the NuGet-Solution window to the right and repro again when you reset the window layout. Please see attached record
[DropDownButtonLostInDefaultLayout.zip](https://github.com/NuGet/Home/files/381126/DropDownButtonLostInDefaultLayout.zip).

**Comment by v-nancyj** [comment]
Verified this issue on VS D16.5\29814.53 with implicit NuGet Client Dev\5.5.0.6422, it has been fixed, close it.

**Comment by v-luzh** [comment]
Still repro on Main\31214.245 + NuGet Client Dev\5.10.0.7208. Verification: Not repro on 16.7 GA (D16.7\30330.147), but repro on 16.8 GA (D16.8\30705.32) Reactivate the bug now, thanks.

**Comment by v-longmin** [comment]
Verified the issue on Dev\6.8.0.59, it has been fixed, so close it.
