### ISSUE TITLE
[Test Failure] ‘Update-package’ command can’t update two packages ‘AspNet.ScriptManager.jQuery’ and ‘jQuery’ to the newest version

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3206]
**Repro Steps:**
1.  New project -> Visual C# -> Web -> ASP.NET Web Application, then uncheck the box for "Application Insights".
2.  Click Web Forms template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Open “Package Manager Console” and type "update-package".
5.  Open “Manage NuGet Packages for Solution…”and click “Update” tab.

**Expected Result:**
There should be no package waits for updating. All packages are updated to the newest version.

**Actual Result:**
"AspNet.ScriptManager.jQuery" and "jQuery" packages show in the “Update” tab. That is to say "Update-package" command can’t update the two packages to the newest version as below screenshot.
![twopackagescan tbeupdatetonewest](https://cloud.githubusercontent.com/assets/20632625/17097277/ca4417ec-528f-11e6-8c5e-838958aa63fc.png)

**Note:**
1. This issue also repro on VS2015Update3 w/ NuGet 3.4.4.
2. It doesn’t repro for other packages.
3. It doesn't repro in C# ConsoleApplication with the same scenario and same two packages.

**Comment by v-luzh** [comment]
It also repro with package **'Microsoft.Net.Compilers'** after **_include prerelease_** on NuGet 3.6.0.1738. The 'Update-Package' command can't update this package to the newest version on the same project.(Repro on VS2015Update3 w/ NuGet 3.4.4)

**Comment by jainaashish** [comment]
This is the right behavior since AspNet.ScriptManager.bootstrap 3.3.6 package doesn't allow bootstrap 3.3.7 which is why it restrict updating these packages.
