### ISSUE TITLE
<ForceLegacyNuGet> option for csproj + project.json case for MONO compatibility.

### ISSUE THREAD

**Issue by dmitriyse** [NuGet/Home#3207]
I am working with cross plafrom library, that targets  Win, CoreCLR, Mono.
(https://github.com/dmitriyse/ClrCoder)

I want to develop only in windows/VS2015 but compile in any platforms.

TROUBLE: when project.json present in a project folder, NuGet Visual Studio Extension works with it, even if it does not used in build of .csproj file.
1) I am using ClrCoder.csproj and ClrCoder.xproj in one folder and ... OMG project.json .
2) I know what is currently possible ( and i managed) to make xbuild and msbuild and VisualStudio build happy. I can create ClrCoder.project.json and migrate dependency from packages.json.
But !!!MONO!!!/xbuild currently (and until 4.6 version - many monthes to wait) cannot work with project.json.lock files. So migration is a not an option for my project.

3) When i use 

``` Xml
<ResolveNuGetPackages>false</ResolveNuGetPackages> 
```

msbuild works fine, mono works fine and old fation csproj files are built well everywere.

!!!BUT I AM UNABLE TO MANAGE NUGET PACKAGES!!! in packages.config from UI (for example add references in ClrProject.csproj and lines to packages.conf) .

SUGGESTION: Add switch to csproj file <ForceLegacyNuGet>true</ForceLegacyNuGet> to "just don't see project.json" in NuGet VS Extension.

This change is affects only NuGet VS Extension. It should take 1 day max (possibly 1 hour).

Thanks very much for help.

**Comment by dmitriyse** [comment]
Currently i use 
HideProject.Jsons.ps1

``` PowerShell
Get-ChildItem -Recurse -Include project.json | Rename-Item -NewName { $_.Name.replace(".json",".json.bak") }
Get-ChildItem -Recurse -Include project.lock.json | Rename-Item -NewName { $_.Name.replace("lock.json","lock.json.bak") }
```

And before commit:
RestoreProject.Jsons.ps1

``` PowerShell
Get-ChildItem -Recurse -Include project.json.bak | Rename-Item -NewName { $_.Name.replace(".json.bak",".json") }
Get-ChildItem -Recurse -Include project.lock.json.bak | Rename-Item -NewName { $_.Name.replace(".lock.json.bak",".lock.json") }
```

It's a significantly easier than complie latest mono from sources on different platforms. But this solution makes our team feel like we are monkeys.

**Comment by rrelyea** [comment]
Can you explain more deeply why you need a packages.config and a project.json in the same project?

**Comment by dmitriyse** [comment]
In short words i want to use the same codebase in the legacy toolset and in the modern toolset at the same time. Motivation is simple - I share folder with code between Linux and Windows machine. Use Mono to debug codebase on linux (and MONO CURRENTLY LUCK OF GOOD DNX SUPPORT thus i require legacy toolset) and under Windows with modern toolset.

I have two solutions ClrCoder.sln and ClrCoder.CoreCLR.sln. That solutions references the same code but different type of projects:
1) Classic csprojs (for Mono compatibility)
2) And new xproj for CoreCLR development
Whenewer i change some *.cs file i need to compile solution then in all platforms to ensure that code is cross-platform.
I have thee ways to do so:
1) Use two types of projects .csproj and .xproj (project.json) that references the same *.cs files. This allows me to open different IDE on the same folder and share file changes on the fly beetwen them.
This solution is most productive for me.

2) auto mirror *.cs files structure and keep .csproj and .xproj in different folders. This is sync hell.
3) Put .csproj and .xproj to different folders but force them to reference the same *.cs files. This will give bunch of issues with toolset/build tools. But will eliminate current one issue.

**Comment by dmitriyse** [comment]
I managed to build Nuget.Client  3.5.0-Beta2 with this dirty hack:

``` C#
        public NuGetProject CreateNuGetProject(EnvDTEProject envDTEProject, INuGetProjectContext nuGetProjectContext)
        {
            if (envDTEProject == null)
            {
                throw new ArgumentNullException(nameof(envDTEProject));
            }


            if (nuGetProjectContext == null)
            {
                throw new ArgumentNullException(nameof(nuGetProjectContext));
            }

            ThreadHelper.ThrowIfNotOnUIThread();

            NuGetProject result = null;

            // ===========   Almost DIRTY HACK =====================
            bool forceIgnoreKProject = false;
            try
            {
                forceIgnoreKProject = File.ReadAllText(envDTEProject.FullName).Contains("<ForceLegacyNuGet>true</ForceLegacyNuGet>");
            }
            catch (Exception ex)
            {
                // Mute all errors.
            }

            INuGetPackageManager projectK = null;
            if (!forceIgnoreKProject)
            {
                projectK = GetProjectKProject(envDTEProject);
            }
            // =====================================================


            if (projectK != null)
            {
                result = new ProjectKNuGetProject(
                    projectK, 
                    envDTEProject.Name, 
                    EnvDTEProjectUtility.GetCustomUniqueName(envDTEProject));
            }
            else
            {
                var msBuildNuGetProjectSystem = MSBuildNuGetProjectSystemFactory.CreateMSBuildNuGetProjectSystem(
                    envDTEProject, 
                    nuGetProjectContext);
```

And this elso

``` C#
                        if (File.Exists(projectJsonPath) && !forceIgnoreKProject)
                        {
                            result = new BuildIntegratedProjectSystem(
                                projectJsonPath,
                                msbuildProjectFile.FullName,
                                envDTEProject,
                                msBuildNuGetProjectSystem,
                                EnvDTEProjectUtility.GetCustomUniqueName(envDTEProject));
                        }
```

And problem was solved.

Dirty build attached as immediate solution.

Please consider to implement this improvement gracefully.

[NuGet.Tools.zip](https://github.com/NuGet/Home/files/385741/NuGet.Tools.zip)

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
