### ISSUE TITLE
Package readme is not automatically opening in VS 2015 CTP6

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#321]
@rkeithhill,

I'm loading a package from an internal repo running NuGet.Server 2.8.3.  I see that packages I load from api.nuget.org are opening their readme's correctly.  Hopefully, there will be an update to NuGet.Server that allows it to do this correctly as well - on both VS 2013 and VS 2015.

**Comment by yishaigalatzer** [comment]
This has not anything to do with the server. We believe this is probably a package issue, if you have a repro that shows a specific package working on one server but not on another please reopen

**Comment by yishaigalatzer** [comment]
This was an issue is VS2015 and got fixed.
