### ISSUE TITLE
Nuget command line no longer accepts file URI format

### ISSUE THREAD

**Issue by MarkOsborneMS** [NuGet/Home#3212]
Existing tools (such as CoreXT) pass file based feeds to nuget in URI format.
e.g.
`nuget restore -Source file://server/share -OutputDirectory packages packages.config`

This used to work, however with nuget 3.5 (verified with build 3.5.0.1655) this now returns an error:
`file://server/share: Failed to retrieve information from remote source 'file://server/share'.
      URI formats are not supported.`

Please restore the ability to parse file base URIs so we don't have to change our tools to support nuget 3.5.

**Comment by rrelyea** [comment]
please check into dev and cherry pick to release-3.5.0-rtm
