### ISSUE TITLE
The Command line say Unknow option "-version"

### ISSUE THREAD

**Issue by lindexi** [NuGet/Home#3214]
I find the https://docs.nuget.org/consume/command-line-reference ,when I use command line update my project to specific version.And the command line say Unknow option "-version".

```
    Nuget.exe update  E:\ConvenientNuget\ConvenientNuget\packages.config -version 1.0.0.10 -Id myid  -source http://localhost:8080/nuget
```

And the install version is 1.0.0.6.

The doc had say I can use version but I cant use in command line.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
