### ISSUE TITLE
Package Manager UI won't update after PMC command

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3216]
**Problem**
Opened the Package Manager 3.5.0 in VS "15" Preview 4 on Installed page. In my web project I installed jQuery.1.12.0. At the same time I opened PMC console and ran `Update-Package -Id jQuery`. After command completed UI didn't refresh automatically. Only after pressing the refresh button the list was updated.
![image](https://cloud.githubusercontent.com/assets/8239356/17147899/9deada0c-5319-11e6-829e-0967b04b83b5.png)

**Expected**
Package Manager UI shows updated jQuery version and icon.

**Comment by PatoBeltran** [comment]
This was solved in https://github.com/NuGet/NuGet.Client/pull/1908
