### ISSUE TITLE
NuGet restore throws Warning Project file cannot be found

### ISSUE THREAD

**Issue by vphad** [NuGet/Home#3220]
Hi Folks, 
When running the NuGet restore, we are seeing below warning, 

E:\xdp\data\RMI\1243096\Xoods\MFMS>nuget restore  -verbosity detailed
Restoring NuGet packages for solution E:\xdp\data\RMI\1243096\Xoods\MFMS\MFMS.sln.
**_WARNING: Project file E:\xdp\data\RMI\1243096\Xoods\MFMS\http://localhost:51509 cannot be found.
WARNING: Project file E:\xdp\data\RMI\1243096\Xoods\MFMS\http://localhost:51489 cannot be found._**

The solution file contains 9 Projects and there are total 11 project files present (2 are not part of solution)

**Environment details:**
Visual Studio 2012
NuGet 2.8

Restore command is ran from command line as part of build process from Jenkins, as well as from cmd as well

Please let us know if any additional information required.

**Comment by rrelyea** [comment]
Did this work in the past? With what versions of VS/NuGet?
What can you tell about those two website projects?
Can you replicate the problem on a newly created project and share the steps to reproduce?

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
