### ISSUE TITLE
Improve docs for nuget.exe restore -ConfigFile 

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3221]
We should improve the doc for `nuget.exe restore -ConfigFile` at [nuget.org](https://docs.nuget.org/consume/nuget-config-file#nuget-config-extensibility-point).

The behavior for nuget.exe, when a config file is specified using the `-ConfigFile`, is not very clear.

We should also clarify the behavior for different versions of nuget.exe separately. 

Originated from - https://github.com/NuGet/Home/issues/3208

**Comment by rrelyea** [comment]
Let's fix docs sooner than later. After we finish validation, please work with @harikmenon to address.

**Comment by rrelyea** [comment]
Status of this doc update?

**Comment by harikmenon** [comment]
adding @karann-msft . Karan can you work with Ankit to get this into our new docs?

**Comment by mishra14** [comment]
Merged : https://github.com/NuGet/NuGetDocs/pull/505
