### ISSUE TITLE
Project.json + csproj with 3.5-rc

### ISSUE THREAD

**Issue by MistyKuu** [NuGet/Home#3223]
Hey. Since I am not sure if it's a bug or not I will ask a few questions and if it's a bug I will create a separate issue. It's for csproj +project.json project. Version of nuget is 3.5-rc (basically the one that is going to be released in 1 August . https://github.com/NuGet/Home/files/369726/NuGet.zip)
1. Is it possible to replicate <developmentDependency> attribute in project.json?
2. Is it possible to use $id$ and $OutputPath$ so basically Msbuild attributes when using nuget pack from csproj?
3. I suspect that when I create a nuget package with developmentdependency=true it should add this dependency with type:build in project.json. It doesn't look like it's working.
4. When specyfying type:build on a dependency and running update from within VS or nuget CLI additional attributes get removed leaving only version number.
5. Is AttributeMetadata going to be supported with project.json and csproj?
6. How to create a tool project?

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. Sorry for the late response! At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
