### ISSUE TITLE
Should I include .pri, .xbf and .xr.xml files?

### ISSUE THREAD

**Issue by Evangelink** [NuGet/Home#3225]
Hi guys,

I am not sure if this is the correct place to post this question so please feel free to move it (or ask me to create it somewhere else).

I am building an internal, cross-platform, nuget package and I am facing some issues on files I should or should not include. I haven't found any good tutorial or doc on this so here I am with my question.
So I have multiple projects, MyProject (a PCL with my resx), MyProject.Desktop, MyProject.Windows, MyProject.WindowsPhone and MyProject.Shared (referenced by the 3 platforms projects). These projects contains some common code I would like to package as a nuget so every domain team can use this common code.

My first nuspec file wsa having the following content (I am giving you only the files part):

```
<files>
    <!-- PCL -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10" />
    <!-- .NET 4.5 -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\net45" />
    <file src="MyProject.Desktop\bin\Release\MyProject.Desktop.dll" target="lib\net45\MyProject.Desktop.dll" />
    <!-- Windows Store 8.1 -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\win81" />
    <file src="MyProject.Windows\bin\x64\Release\MyProject.Windows.dll" target="lib\win81\MyProject.Windows.dll" />
    <!-- Windows Phone -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\wpa81" />
    <file src="MyProject.WindowsPhone\bin\ARM\Release\MyProject.WindowsPhone.dll" target="lib\wpa81\MyProject.WindowsPhone.dll" />
</files>
```

Then I have tried to include the pri files and got some payload file does not exist errors on the consuming projects (at the compile time not the package installation time). So I have found those articles
[Packaging a windows store apps component with nuget](https://blogs.msdn.microsoft.com/mim/2013/09/02/packaging-a-windows-store-apps-component-with-nuget-part-2/)
[Package xaml components](https://dschenkelman.github.io/2014/06/25/windows-phone-8-1-nuget-packages-with-xaml-components/)
So I ended up with the following nuspec file:

```
<files>
    <!-- PCL -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\portable-net45+wp8+wpa81+win8+MonoAndroid10+MonoTouch10+Xamarin.iOS10" />
    <!-- .NET 4.5 -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\net45" />
    <file src="MyProject.Desktop\bin\Release\MyProject.Desktop.dll" target="lib\net45\MyProject.Desktop.dll" />
    <!-- Windows Store 8.1 -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\win81" />
    <file src="MyProject.Windows\bin\x64\Release\MyProject.Windows.dll" target="lib\win81\MyProject.Windows.dll" />
    <file src="MyProject.Windows\bin\x64\Release\MyProject.Windows.pri" target="lib\win81\MyProject.Windows.pri" />
    <file src="MyProject.Windows\bin\x64\Release\MyProject.Windows.xr.xml" target="lib\win81\MyProject.Windows\MyProject.Windows.xr.xml" />
    <file src="MyProject.Windows\bin\x64\Release\**\*.xbf" target="lib\win81\MyProject.Windows" />
    <!-- Windows Phone -->
    <file src="MyProject\bin\Release\**\MyProject*.dll" target="lib\wpa81" />
    <file src="MyProject.WindowsPhone\bin\ARM\Release\MyProject.WindowsPhone.dll" target="lib\wpa81\MyProject.WindowsPhone.dll" />
    <file src="MyProject.WindowsPhone\bin\ARM\Release\MyProject.WindowsPhone.pri" target="lib\wpa81\MyProject.WindowsPhone.pri" />
    <file src="MyProject.WindowsPhone\bin\ARM\Release\MyProject.WindowsPhone.xr.xml" target="lib\wpa81\MyProject.WindowsPhone\MyProject.WindowsPhone.xr.xml" />
    <file src="MyProject.WindowsPhone\bin\ARM\Release\**\*.xbf" target="lib\wpa81\MyProject.WindowsPhone" />
</files>
```

But when I look at some of the biggest cross-platforms projects on github I can see that they are not included (some do include the .pri though). My question is should I include the .pri file? If so, is there a way not to have an error saying it can find the payload files?

**Comment by harikmenon** [comment]
I believe pri files are required if you have resources (like res*) in your Window UWP projects. Otherwise lookup will fail. 

E.g of projects that package pri files
https://github.com/Microsoft/XamlBehaviors
https://github.com/Microsoft/Win2D

**Comment by Evangelink** [comment]
Thanks for the confirmation. 

I still have a few things that I don't understand. When I do include the .pri file into the nuget, the installation of the nuget is successful however, when trying to compile the project where the nuget is installed, I end up with some errors saying they can't find payload files: *.xr.xml, *.xbf and for 2 projects  that are using SQLite I also have a payload error saying it can't find sqlite3.dll, SQLite.Ext.pri, SQLite.Ext.dll. If I do try to include them into the nuget, then I have an error when installing the nuget (can't install sqlite3.dll).

Maybe your page is not the best place to ask this question, but I am wondering how people doing cross-platform manage to include pri files in their nuget without having payload error afterwards...

Any hint?

**Comment by harikmenon** [comment]
xr.xml is used for .NET Native, do we you have anything specific you have declared there? .xbf is for Xaml files, do you have Xaml control in your nuget that you are trying to pack. I would recommend that you dont include sqlite assemblies as libraries in your lib, instead add a dependency to your nuget package. If you can share you nuget package, and source I can take a look at it.

**Comment by Evangelink** [comment]
Thanks for your feedback. I actually had a look at the meaning of the different files before asking, my problem is more with having payload errors on the project using the nuget package. So I was wondering if it was an error on the files I was including on my nuget. I can understand I haven't really stated a clear problem so as requested I have set-up a little repro case, that you can found here: [ReproCase](https://github.com/Evangelink/ReproNugetPayloadErrors).

The project MyProject is a dumb example (with some of the nuget dependencies we have) of the nuget we create. The project MyApplication is the project where nuget package is installed. If you try to compile it, you will end up with some payload errors saying I haven't included:
- Views\WelcomePage.xbf
- MyProject.WindowsPhone.xr.xml
- sqlite3.dll
- SQLitePCL.Ext.pri
- SQLitePCL.Ext.dll

Hope the repro case will help you.

**Comment by Evangelink** [comment]
@harikmenon sorry to bother, any up on this "issue"?

**Comment by harikmenon** [comment]
Here is a link to the doc that we have written that shows the exact steps to get a package to build for UWP. Do note that this is for native, so you can skip the native lib sections.

http://nugetdocsbeta.azurewebsites.net/ndocs/guides/build-for-uwp

**Comment by Evangelink** [comment]
Thanks for the update and for the guide. 

I am updating the nuspec files now and will get back to you as soon as I have finished. On the website guide, you recommend to add the files into a `runtimes` folder and I have seen on some of the nugets we are using that people have put their content into a `sdk` folder. Could you tell me the difference? Is runtime only for UWP projects?

**Comment by harikmenon** [comment]
runtime is for platform specific binaries. Native project are compiled down into the assemblies compatible on the target OS. Runtime folders is used to put platform specific binaries.

**Comment by Evangelink** [comment]
@harikmenon I have updated the [repro case](https://github.com/Evangelink/ReproNugetPayloadErrors) using the guide you have created ([fixed link](http://nugetdocsbeta.azurewebsites.net/ndocs/guides/create-uwp-packages#adding-xaml-content)). Using your example helped me fix most of the errors but I am unable to reference controls coming from the nuget package using the .targets based on your example. Also, I had to integrate directly the sqlite3.dll and SQLitePCL.Ext.dll and .pri into my nuget.

Any idea on how to fix that?

**Comment by Evangelink** [comment]
Looking to ReactiveUI cross-platform nuget package, they do as follow:

```
-- lib
    -- Portable-Win81+WPA81
        -- ReactiveUI.dll
        -- ReactiveUI.pri
        -- ReactiveUI.xml
        -- ReactiveUI
            -- ReactiveUI.xr.xml
            -- Themes
                -- *.xbf
```

**Comment by harikmenon** [comment]
Hmm. On our end the example was tested thoroughly and it worked. Unless we have a look at your package, its hard to figure out what could be wrong.

**Comment by Evangelink** [comment]
@harikmenon I did gave you a failing example so you can have a look 27 days ago and I have updated it (as said in my previous comment) 3 days ago with your solution so you can see that it doesn't work.

Please have a look at the example project here: [EXAMPLE](https://github.com/Evangelink/ReproNugetPayloadErrors)
The MyProject project is an example of the kind of cross-platform nuget package we create. The MyApplication project is an example of cross-platform project where we try to install the nuget (MyProject). As you can see the MyApplication project doesn't successfully build because there are errors saying it can't find some controls that are present in the MyProject nuget package.

For info, if you put the files into the lib folder (what is done by ReactiveUI project for example) you will need to put all the files into the lib folder, including the sqlite3.dll which will cause an issue saying it can't add it.

You can download/fork the repro case to play with it. Hope you can find what's wrong here.

Thanks

**Comment by harikmenon** [comment]
Why are you adding SQLLite into the package? Cant you take a dependency on the SQLLite package instead?

**Comment by Evangelink** [comment]
As I was telling you. As soon as I include the .pri file into the nuget (which I need to do to get resources) and install that package, I end up with payload errors saying it can find `sqlite3.dll, SQLitePCL.Ext.dll and SQLitePCL.Ext.pri` into the nuget package.

EDIT:
On the given repro case, you can try to remove them. Then recreate a nuget package and install it on the MyApplication solution and you will see.

**Comment by Evangelink** [comment]
@harikmenon Have you made any progress regarding this case?

**Comment by harikmenon** [comment]
Sorry, I was on vacation. Just started looking at this. The NuGet package I'm building from the solution is incomplete, for some for the projects, X86, x64 or ARM is not being packaged. Please share the complete package from you end.

**Comment by Evangelink** [comment]
Np! I hope you had a good time off.

I have actually reproduced how the team is working with the code (always x64 for WinRT and always ARM for WindowsPhone) so there is no real benefits for me to add the other cases but if you prefer I can work on it.

**Comment by Evangelink** [comment]
@harikmenon Have you found something?

**Comment by harikmenon** [comment]
Can you send me an email? This is easier to do it there. harikm@microsoft.com. I will have one our of PMs help you through this.
