### ISSUE TITLE
Package Manager update fails with allowedVersions filter

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3228]
**Problem**
I have a solution with two projects. WebApplication1 project has a dependency of jQuery.1.12.3 with `allowedVersions` filter set to `[1.0,2.0)`. I opened a `Manage packages for solution...` dialog and switched to the Updates tab. I selected jQuery list entry and clicked the Update button. The update operation failed with following error:

> Unable to resolve 'jQuery'. An additional constraint '(>= 1.0.0 && < 2.0.0)' defined in packages.config prevents this operation.

![image](https://cloud.githubusercontent.com/assets/8239356/17186460/3c140020-53ea-11e6-8213-7806e123f438.png)

**Expected**
Package is successfully updated to 1.12.4.
The project level update works correctly.

![image](https://cloud.githubusercontent.com/assets/8239356/17186685/1218c5ac-53eb-11e6-838d-7ce3e0e2f170.png)

Detected in NuGet Package Manager 3.5.0.1592 for VS2015

**Comment by PatoBeltran** [comment]
Closing as packages.config is not supported.
