### ISSUE TITLE
After login with my AAD account, clicking "API Apps" tab will result in an infinite loop in browser

### ISSUE THREAD

**Issue by guangyang** [NuGet/Home#323]
**Repro**

1. Login to https://apiapps.nuget.org with an AAD account. I'm using a non @microsoft.com one.
2. Click the "API Apps" tab

**Expected**

See a list of API Apps published here.

**Actual**
Browser gets into an infinite loop with this in the address bar
https://login.microsoftonline.com/common/oauth2/authorize?client_id=52ec4d1d-541d-4df4-b1b5-907692940522&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dYn-F6FrMHlZjun9LBBIjA0_JiMGyrs2JdwBbiToWuakKVdQ3ZM07ghnBfzxerGa3BWGvNwi3MEfPzg5VIKnUqWTFy1Aiv7E6EOuAq6PAcNrS1QU5eNXpLADJ41AqYmAd-MVGFw&nonce=635634352469925830.YjU4MWMxZDYtMjE5NC00MDE0LWEwNDQtNzBkZmY0ZmVmNzU2OTU5NjgzYjgtYWUwZC00ZWEyLTg2MmYtMDIxNjY0YTk5NjMy&redirect_uri=https%3a%2f%2fapiapps.nuget.org%2f&post_logout_redirect_uri=https%3a%2f%2fapiapps.nuget.org

**Comment by yishaigalatzer** [comment]
@guangyang I Believe this this fixed already. Please ping an reopen if necessary
