### ISSUE TITLE
C++ Background App cannot successfully use a C# component

### ISSUE THREAD

**Issue by bfjelds** [NuGet/Home#3232]
IoT Background Application is a standalone BackgroundTask (no exe) ... a C++ Background Application cannot use a C# component because the .Net framework does not get included (i.e. Microsoft.CSharp.dll, etc).

Microsoft.NuGet.targets seems to exclude the possibility ... but changing the definition of CopyNuGetImplementations to this solves the problem (note the managed case is already handled, this change would just enable the native case in the same way):

<CopyNuGetImplementations Condition="'$(CopyNuGetImplementations)' == '' and ((('$(OutputType)' != 'library' or '$(AppxPackage)' == 'true') and ('$(OutputType)' != 'winmdobj' or '$(AppxPackage)' == 'true')) or '$(TargetFrameworkIdentifier)' == '.NETFramework')">true</CopyNuGetImplementations>

**Comment by jasonmalinowski** [comment]
NuGet/NuGet.BuildTasks#17 has been merged.
