### ISSUE TITLE
NuGet.ProjectModel should depend on Newtonsoft v9.0.1

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#3233]
NuGet.ProjectModel.nuspec looks like this:

```
      <group targetFramework=".NETStandard1.3">
        <dependency id="NETStandard.Library" version="[1.6.0, )" />
        <dependency id="System.Dynamic.Runtime" version="[4.0.11, )" />
        <dependency id="System.Threading.Thread" version="[4.0.0, )" />
        <dependency id="Newtonsoft.Json" version="[6.0.4, )" />
        <dependency id="NuGet.DependencyResolver.Core" version="[3.5.0-rc1-1653, )" />
      </group>
```

Notice that it is targeting netstandard1.3 and is depending on Newtonsoft.Json v6.0.4.  This is an issue because Newtonsoft.Json v6.0.4 does not support netstandard1.3.  Thus, anyone who wants to reference NuGet.ProjectModel needs to add `imports` into their project.json.

NuGet needs to move up to the new Newtonsoft.Json that supports netstandard.

**Comment by emgarten** [comment]
@eerhardt This will be in build 1667
