### ISSUE TITLE
Aggregate Exception Thrown and Package Not Installed When One Package Source Is Not Available

### ISSUE THREAD

**Issue by johnkoerner** [NuGet/Home#3234]
I have an environment where I have multiple package sources configured within Visual Studio.  Some of the package sources are only available when connected to my corporate VPN. If I am not connected to the VPN and attempt to add a package from the Nuget v2 gallery, I get the following error on install:

```
Exception 'System.AggregateException' thrown when trying to add source 'http://artifactoryserver.mycompany.com/nuget'. Please verify all your online package sources are available.
```

As a consumer of Nuget, it is unclear to me why that package source needs to be available if I am installing from the Nuget Gallery, which is available.

My current workaround is to disable the package source when installing while I am not connected to the VPN.  This is inconvenient, but does work.

**Comment by rrelyea** [comment]
We check all packages sources for dependencies. If the package source is down, we need to error.
Note that we don't love the user experience here, and have begun investing in a feature to improve the user experience: https://github.com/NuGet/Home/issues/1627
