### ISSUE TITLE
Visual studio extension does not handle disable/enable packages correctly for local nuget.config

### ISSUE THREAD

**Issue by dhvik** [NuGet/Home#3237]
I have a global nuget.config that disables a package source (`c:\users\myuser\AppData\Roaming\nuget\nuget.config`)

``` xml
<configuration>
  <packageSources>
    <add key="s1" value="http://someSite.com"/>
  <packageSource>
  <disabledPackageSources>
    <add key="s1" value="true"/>
  </disabledPackageSources>
</configuration>
```

Then i have a local nuget.config in my solution folder that also has the same package source defined

``` xml
<configuration>
  <packageSources>
    <add key="s1" value="http://someSite.com"/>
  <packageSource>
</configuration>
```

This will display the package source as not selected
![image](https://cloud.githubusercontent.com/assets/872128/17202506/e8cb409e-5499-11e6-8456-164c718058bd.png)
If I try to check it using the Options dialog in visual studio, and press OK, the choice is not persisted. If I check the local nuget.config, then it has been updated with the disablePackageSource from the parent config file instead. 

I can work around the issue by adding a `<clear/>` inside the `<disabledPackageSources>` tag.

What I would suppose the dialog to do is to make that package source available for me (in my local config) but not in the global one.

**Comment by rrelyea** [comment]
[updating]
This is by design today.
Our dialog doesn't yet support hierarchical config settings well.
We plan to address that in the future: https://github.com/NuGet/Home/issues/1820
