### ISSUE TITLE
[Test Failure] System.IO.FileLoadException throw when doing F5 after update-package for ASP.NET Web (Web Forms) Application

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3239]
**Description:** 
We got the System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json’, or one of its dependencies… when F5 after done ‘update-package’ in PMC with ASP.NET Web (Web Forms) Application.

**Repro Steps:**
1.  New project -> Visual C# -> Web -> ASP.NET Web Application, then uncheck the box for "Application Insights".
2.  Click Web Forms template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Build solution and do F5, no error.
5.  Open “Package Manager Console” and type "update-package".
6.  Build the solution again.
7.  Press F5.

**Expected Result:**
No exception thrown when doing F5.

**Actual Result:**
Rebuild (step6) is OK, but System.IO.FileLoadException throw out as below screenshot.
![exceptionafterupdate](https://cloud.githubusercontent.com/assets/20632625/17206513/a675cd06-54e2-11e6-9632-43f80d9b2399.png)

**Exception:**
$exception  {"Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"}    System.IO.FileLoadException

**Note:**
1. It doesn’t repro on VS2015Update3 w/ NuGet 3.4.4.
2. It doesn’t repro on Willow 25519.01.

**Comment by rrelyea** [comment]
Please investigate fix. I reproed on 15.0.25527.0 BCB2

**Comment by rrelyea** [comment]
Also, I didn't test dev14 and the vsix14 from dev branch.

**Comment by jainaashish** [comment]
It's reproducible on dev14 as well with latest dev build.

**Comment by rrelyea** [comment]
Keeping open until we get a decision about whether to cherry-pick into release-3.5.0-rc branch and insert into VS.

**Comment by rrelyea** [comment]
@drewgil - please validate this fix before 11 (checked into Dev already) - will be discussing with VS client dev mgrs at 11 -- for escrow consideration

**Comment by drewgillies** [comment]
Validated. dev build 3.5.0.1706 in VS 14.0.25421.03 Update 3 does not repro.

**Comment by jainaashish** [comment]
Merged to 3.5.0-rc
