### ISSUE TITLE
VS2015 Unable to resolve dependency

### ISSUE THREAD

**Issue by pdwetz** [NuGet/Home#3240]
While updating NancyFx to its latest build (on its [Myget feed](https://www.myget.org/F/nancyfx/api/v3/index.json)), Nuget threw an error while updating: Unable to resolve dependency 'Microsoft.Extensions.DependencyModel'. This happened for two separate projects, both .NET 4.6.1 and using IIS Express locally.

However, I discovered that the error only occurred when using the "left" update button (that is, checking the NancyFx box and clicking the Update button above). Both projects updated properly when I instead clicked on NancyFx and used the Update button in the resulting detail window. When adding the reference to a brand new project there were no errors regardless of the approach.

Visual Studio 2015 Professional, Version 14.0.25424.00 Update 3
NuGet Package Manager 3.5.0

**Comment by rrelyea** [comment]
@pdwetz - can you please try a recent nightly build of our VSIX: https://www.myget.org/F/nuget-vsix/vsix/NuGet.0d421874-a3b2-4f67-b53a-ecfce878063b-3.5.0.1666.vsix 
And let us know if it still has that problem.

**Comment by rrelyea** [comment]
@joelverhagen did fix in 3.6b1 to make (for .net core projects) the right update button do an uninstall and an install, like the checkbox/button code path did. We should verify if we can repro.

**Comment by rrelyea** [comment]
@pdwetz - can you please try 3.5.0-rc1 from http://nuget.org/downloads?

**Comment by rrelyea** [comment]
verify as part of 3.5 rtm verification.

**Comment by rrelyea** [comment]
Was validated as fixed in 3.5rtm validation pass.
