### ISSUE TITLE
Inconsistent -NoCache behavior

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3244]
Tested on `dev`, https://github.com/NuGet/NuGet.Client/commit/5932bf66f9845337db711e62d2779761962bde94.

When a package is available in the global packages folder but is not available on a source, `-NoCache` should mean the restore/install fails with a "package not available on the source" error.

For future reference, when restoring packages.config, the destination is the output directory. When restoring project.json, the destination is the user packages folder.

I have noticed varying behavior in nuget.exe:
## Succeeds with a zero exit code and package is available at the destination

```
(install packages.config + V3 source)
nuget.exe install packages.config -OutputDirectory packages -Source https://api.nuget.org/v3/index.json -NoCache

(restore packages.config + V3 source)
nuget.exe restore packages.config -PackagesDirectory packages -Source https://api.nuget.org/v3/index.json -NoCache

(restore project.json + V3 source)
nuget.exe restore project.json -Source https://api.nuget.org/v3/index.json -NoCache

(restore project.json + V2 source)
nuget.exe restore project.json -Source https://www.nuget.org/api/v2 -NoCache
```
## Warns about the missing package but returns a zero exit code

The destination directory is not populated. This seems like the odd one out.

```
(install packages.config + V2 source)
nuget.exe install packages.config -OutputDirectory packages -Source https://www.nuget.org/api/v2 -NoCache
```
### Fails with "package not found error"

It seems to me that this is the correct behavior.

```
(install specific package + V3 source)
nuget.exe install NuGet.Frameworks -Version 3.5.0-zlocal-4466 -OutputDirectory packages -Source https://api.nuget.org/v3/index.json -NoCache

(install specific package + V2 source)
nuget.exe install NuGet.Frameworks -Version 3.5.0-zlocal-4466 -OutputDirectory packages -Source https://www.nuget.org/api/v2 -NoCache

(restore packages.config + V2 source)
nuget.exe restore packages.config -PackagesDirectory packages -Source https://www.nuget.org/api/v2 -NoCache
```
### packages.config

``` xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="NuGet.Frameworks" version="3.5.0-zlocal-4466" targetFramework="net461" />
</packages>
```
### project.json

``` json
{
  "dependencies": {
    "NuGet.Frameworks": "3.5.0-zlocal-4466"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win-anycpu": {},
    "win": {}
  }
}
```

**Comment by emgarten** [comment]
`nuget.exe install` scenarios are a bug, tracked here: https://github.com/NuGet/Home/issues/5017
Fix: https://github.com/NuGet/NuGet.Client/pull/1634

project.json restore still needs to be investigated.

**Comment by PatoBeltran** [comment]
Closing as PR and bug pointed in this issue are closed.
