### ISSUE TITLE
How to use the version of installed NuGet package when defining dependency in NuSpec

### ISSUE THREAD

**Issue by khorvat** [NuGet/Home#3246]
How to specify the version range of dependency to use the version of installed NuGet package ?

I have described this issue in more detail on the Stackoverflow:
http://stackoverflow.com/q/38606969/467991

**Comment by emgarten** [comment]
try adding `allowedVersions` for the dependency entry in your packages.config file

**Comment by rrelyea** [comment]
Please reopen if you still have issues.

**Comment by khorvat** [comment]
Hi,

  allowedVersions should be placed in the packages.config but I'm searching for solution as described on StackOverflow:

> How to specify the version range of dependency to use the version of installed NuGet package ?
> 
> I'm aiming to something like the sample below, where one can use tag similar to $version$ tag to specify the 1.0.8-alpha version as minimum version.
> 
> Installed
> 
> `<package id="Name" version="1.0.8-alpha" targetFramework="net451" />`
> NuSpec
> 
> `<dependency id="Name" version="[$packageVersion$,2.0.0)" />`
> After NuGet package gets compiled it should resolve to (>= 1.0.8-alpha && < 2.0.0).
> 
> Is there a NuSpec tag for this or any alternative way to do this ?

So I'm asking if there is a variable that can be used in nuspec to always use installed version in project as minimum version in nuspec, note that I want to use the variable as the nuspec version range min. 

Thanks

**Comment by emgarten** [comment]
> So I'm asking if there is a variable that can be used in nuspec to always use installed version in project as minimum version in nuspec

No there is not. The token replace wouldn't need to be aware of the dependency context and that is not supported today, token replacements are global across the nuspec file.

**Comment by khorvat** [comment]
Is there a variable/token that can be used in allowedVersions to accomplish this:

`allowedVersion="[$packageVersion$,2.0.0)"`

this way I can use installed version as minimum and fixed 2.0 as maximum version ? If this is not supported at the moment do you plan to introduce this feature ?

Regards
