### ISSUE TITLE
VS2015 Comunity NuGet PackageManager fails

### ISSUE THREAD

**Issue by AlesDo** [NuGet/Home#3248]
NuGet Package manager does not work and the exception in the attached picture is shown. Tried to uninstall reinstall and it still does not work.
![nugeterror](https://cloud.githubusercontent.com/assets/13190278/17245338/b5ade428-558e-11e6-8d14-aa8538395dac.png)

**Comment by rrelyea** [comment]
Version of nuget? Which version of vs2015? Update 3?

**Comment by AlesDo** [comment]
VS2015 update 3. See image for the detailed version.
NuGet Package Manager version 3.5.0.1484
![vsversion](https://cloud.githubusercontent.com/assets/13190278/17248354/a950431a-55a2-11e6-9bba-4ab78e696692.png)

**Comment by emgarten** [comment]
@AlesDo can you give some repro steps? How are you starting NuGet before getting this error?

**Comment by AlesDo** [comment]
This error happens every time that the package manager starts. If you build a solution that checks for NuGet packages. Or even if you go to the Tools menu and try to open the NuGet package manager.
I suspect something had to happen on this specific PC that this happens because it worked before. The thing is that even if I uninstalled VS2015 and reinstalled it did not fix the issue. Is there any configuration stored anywhere that could affect this behavior. The operating system on the PC is Windows 7 and it has also VS2013 installed.
Is there a possibility to send you some kind of trace or log so you will se more information about what happens?

**Comment by rrelyea** [comment]
Can you please tell us if you still have this issue?

**Comment by AlesDo** [comment]
Yes it is still happening. I have attached also the visual studio log file
[vslog.zip](https://github.com/NuGet/Home/files/459177/vslog.zip)

.

**Comment by AlesDo** [comment]
After installing the latest v3.5.0 release of the tools the issue does not happen anymore.
