### ISSUE TITLE
VS2015 - Adding Files With TFS Is Done 1 File At A Time

### ISSUE THREAD

**Issue by issafram** [NuGet/Home#3249]
I have recently switched over to VS2015 from VS2013.

I install a package that I use quite often which has a couple thousand JS/CSS files.  Nothing crazy, just normal Content / Script files.

After hitting Install-Package _BigContentPackage_, it seems the high level process to loop through all the files in the package, add each file to the project, and then add that file to the source control provider.  This is incredibly slow with hundreds to thousands of files.

Wouldn't the process be improved by adding all the files to the filesystem **first** and _afterwards_ doing all source control operations?

Or is it possible that there is an issue on my end?

**Comment by rrelyea** [comment]
What version of VS 2015 are you using? What version of NuGet?
Are you seeing a regression from perf in VS2013 for the same scenario? How long did it take in VS2013 and how long in VS2015? What version of NuGet were you using in 2013?

**Comment by issafram** [comment]
**VS 2015 Enterprise** - Version 14.0.25424.00 Update 3
**NuGet for VS2015** - 3.4.4.1321
**NuGet for VS2013** - 2.12.0.817

In VS2013, it took maybe 15-20 minutes for the entire package install.
In VS2015, I abort the install after over an hour.  I check the Scripts folder and only about 150 or so files have been copied over. 

I see the file appearing in Windows Explorer, then Visual Studio pops up a **Adding File** dialog box for TFS (I assume), then it moves on to the next file.  This is where I think the slowdown is occuring.

I know there is no issue with the package itself.  I am using a local Klondike server and the package itself is copied over to the packages folder in about 5-10 seconds.  All the processing is done on the local machine.

I believe it is trying to hit TFS after every file copy operation for the Contents.  This doesn't seem optimal.

What are your thoughts?

**Comment by issafram** [comment]
Can this be updated to a newer milestone?  I feel like this has been lost.

**Comment by PatoBeltran** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us. I will close this issue, but feel free to open a new issue if you still see this problem in the latest version.
