### ISSUE TITLE
[NuGet.PackageManagement] install.ps1 is case-sensitive now. Should be fixed

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#325]
[NuGet.PackageManagement] install.ps1, init.ps1 and uninstall.ps1 are case-sensitive now. Should be fixed

**Comment by emgarten** [comment]
Init.ps1 also has this issue.

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/tree/9f4b53a7a953b571a227b54d898e8e2b91c95090
