### ISSUE TITLE
.NET Core and UWP project.json projects do not sent TFM in search HTTP request

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3250]
### Steps to reproduce
1. Open Fiddler
2. Create a new Class Library (portable) project.
3. Add a `"net45": {}` entry to the project.json of the PCL.
4. Add a .NET Core Class Library to the solution.
5. Manage NuGet Packages for Solution...
6. Search for something on a V2 source.
### Expected

The request should have all TFMs in the `targetFramework` query parameter:
### Actual

Only `dotnet` is sent.

```
GET https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&searchTerm='foo'&targetFramework='dotnet'&includePrerelease=false&$skip=0&$top=26 HTTP/1.1
Accept: application/atom+xml, application/xml
user-agent: NuGet Client V3/3.5.0-rc1-1667 (Microsoft Windows NT 10.0.10586.0, VS Enterprise/14.0)
Accept-Language: en-US
Host: www.nuget.org
Accept-Encoding: gzip, deflate
```

**Comment by PatoBeltran** [comment]
Closing as project.json is not supported. Feel free to reopen if this still repros in PackageReference
