### ISSUE TITLE
[scriptcs] Error using NuGet.Core to install latest Newtonsoft.Json package 

### ISSUE THREAD

**Issue by glennblock** [NuGet/Home#3252]
scriptcs is generating an error when using `scriptcs install` to install the latest `Newtonsoft.Json' package.

```
ERROR: Error installing package. [InvalidOperationException] 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'. ERROR: Package installation failed. [AggregateException] One or more errors occurred.
```

scriptcs depends on NuGet.Core (currently using version 2.8.6). I've debugged the issue and the exception is being thrown from NuGet.Core. You can see the full stack trace [here](https://github.com/scriptcs/scriptcs/issues/1171)

I tried updating scriptcs to the latest Nuget.Core (2.11.1) but then I get an error at runtime saying that Nuget.Client 2.12 is required.

Any help is appreciated as this is blocking several use cases of scriptcs

**Comment by harikmenon** [comment]
I believe this is due to the older NuGet not understanding NET Standard 1.6 that is defined in the latest NewtonSoft.Json package. You would need to use the latest nuget.core to support this. @emgarten @joelverhagen

**Comment by glennblock** [comment]
I tried upgrading but got the other error I described saying that I need Nuget client 12

**Comment by harikmenon** [comment]
NetStandard 1.6 is available only in 2.12 I belive @emgarten @joelverhagen can comment.

**Comment by glennblock** [comment]
Where do I get 2.12? It is not in the main feed?

**Comment by glennblock** [comment]
Thank you for the quick response btw!

**Comment by joelverhagen** [comment]
Newtonsoft.Json 9.0.1 has a dependency on the Microsoft.CSharp 4.0.1 package when targeting `netstandard1.0`. That package has a min client version of 2.12. This seems like the most likely explanation.

@rrelyea is working on publishing a 2.12 version of the NuGet.Core package that is not prerelease. Once that is up on NuGet.org, give it a try.

**Comment by joelverhagen** [comment]
Version 2.12 of NuGet.Core is available on NuGet.org:
https://www.nuget.org/packages/NuGet.Core/2.12.0

Let me know if you run into other issues.

**Comment by glennblock** [comment]
Excellent, thank you! I will let you know if that fixes it.

**Comment by glennblock** [comment]
Just tested, looks like that fixed it. Thanks!

**Comment by ahmedallam2995** [comment]
from nuget, install "JavaScriptSerializer" instead of Newtonsoft.Json it will work

**Comment by cihadaktaran** [comment]
@ahmedelsaka862  
I run this command: Install-Package JavaScriptSerializer 
get this error: Unable to find package 'JavaScriptSerializer'.

**Comment by ahmedallam2995** [comment]
@cihadaktaran 
Search for it in Nuget window not from console, Choose from results "WebApiContrib.Formatting.JavaScriptSerializer" then click install button, after installing it call namespace "using Newtonsoft.Json" in your code.

**Comment by ABajpaiAmphora** [comment]
Install nuget package manager for Visual studio 2013 from below link:
https://www.visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca

and restart the Visual Studio 2013.

For me this worked.
