### ISSUE TITLE
Automatically Displaying a Readme.txt File During Package Installation broken?

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3253]
_From @AnderssonPeter on July 29, 2016 8:51_

On the following page https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-displaying-a-readme.txt-file-during-package-installation
It says the following

```
A package can include a readme.txt file in the root of the package. This file will be displayed in Visual Studio immediately after the package is installed.

<file src="readme.txt" target="" />
If the package is installed because it is a dependency of another package, the readme.txt file will not be opened. Only the readme.txt file of the package that the user is explicitly installing will be shown.

This feature was added in NuGet 1.7. If the client is older than NuGet 1.7 the readme.txt file will be ignored.
```

I have added a Readme.txt to one of my packages but it isn't displayed when i install the package is this functionally still there or am i doing any thing wrong?

The package in question:
https://www.nuget.org/packages/CompressedStaticFiles/

Related issue: https://github.com/dotnet/cli/issues/3935#issuecomment-236023845

_Copied from original issue: NuGet/NuGetDocs#507_

**Comment by AnderssonPeter** [comment]
Its a asp.net core project if that matters?

**Comment by emgarten** [comment]
> Its a asp.net core project if that matters?

That explains it, NuGet will open readme.txt for packages.config and UWP project.json projects. ASP.NET Core projects are handled differently and do not yet have support for readme.txt

**Comment by AnderssonPeter** [comment]
Ok that makes more sense do you know if there is any plans or workarounds? like using a installation powershell script or some thing like that?

**Comment by rrelyea** [comment]
Sorry, no workaround since project.json won't run install.ps1.
