### ISSUE TITLE
Unable to write any unit test because of Nuget

### ISSUE THREAD

**Issue by SharpNoiZy** [NuGet/Home#3254]
Hi,

I tried to start a new project with Core RTM and want to write some unit tests for this project.
Which seems an easy task cost me hours now.

The issue is, I can not use xUnit nor Nunit and the error is always the same!
![projectjson](https://cloud.githubusercontent.com/assets/124893/17268737/1d534f6e-5634-11e6-9e74-1c88cc0ca325.png)

The fact that it is the same with both projects leads me to the fact that the issue have to do something with NuGet.

Can someone help?

**Comment by emgarten** [comment]
Check your package sources and verify that you have https://api.nuget.org/v3/index.json enabled. From the error message displayed it looks as if Visual Studio is unable to find the package online.

**Comment by rrelyea** [comment]
This may help: https://xunit.github.io/docs/getting-started-dotnet-core.html

If not, please answer the following:
What version of NuGet is installed in VS? 
Also, do you have .NET Core Tools preview 2 installed?
Please see 3.5.0-rc1 at http://nuget.org/downloads

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
