### ISSUE TITLE
NuGet pack on csproj ignores empty files element in nuspec file

### ISSUE THREAD

**Issue by arnovannijnatten** [NuGet/Home#3257]
Since NuGet client 3.4.4 the behavior of the pack command has changed and is not in line with the documentation anymore.

Before 3.4.4 it was possible to only include the output assembly and ignore content files in the nupkg by adding an empty files element in the nuspec file. From the docs (https://docs.nuget.org/Create/Creating-and-Publishing-a-Package#creating-a-package):

> Note that only the files defined inside the node will be included in the package. If you include an empty node in the nuspec, all content files will be omitted from the package and only the lib folder will be included.

See attached solution and its build output which reproduces this with 3.2.0, 3.4.3 (both working as expected) and 3.4.4 and 3.5.2 (both showing the bug).
[BuildOutput.txt](https://github.com/NuGet/Home/files/393130/BuildOutput.txt)
[NuGetClientIssueRepro.zip](https://github.com/NuGet/Home/files/393129/NuGetClientIssueRepro.zip)

It seems this change in behavior was introduced by fixing https://github.com/NuGet/Home/issues/2658
Also see https://github.com/NuGet/NuGet.Client/commit/c2443fd2aec84a1c9b1ab1b34a4abe79dd3eb1fa for reference

**Comment by rrelyea** [comment]
Please analyze if we do have a break in behavior here.

**Comment by rohit21agrawal** [comment]
3.5.0-rtm : https://github.com/NuGet/NuGet.Client/commit/b755c08b8419757c588b275795c10fa047028122

**Comment by stevenscreek** [comment]
This looks like it should have fixed #3149 as well.

**Comment by rohit21agrawal** [comment]
@stevenscreek yes it does look like these are the same issues and this should fix that one too!
