### ISSUE TITLE
Unable to install System.Runtime.InteropServices.RuntimeInformation 4.0.0 into PCL project targeting Profile 111

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#3258]
This was originally logged on [Xamarin's bug tracking system](https://bugzilla.xamarin.com/show_bug.cgi?id=42941)
# Steps to reproduce
1. Create a PCL project that targets Profile 111
2. Install System.Runtime.InteropServices.RuntimeInformation 4.0.0
   https://www.nuget.org/packages/System.Runtime.InteropServices.RuntimeInformation/
# Expected result

Package installs since it has an assembly that targets netstandard1.1 which is [compatible with PCL profile 111](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md).
# Actual result

```
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

This problem happens with:
- Visual Studio 2013 and NuGet 2.12
- Visual Studio 2015 and NuGet 3.4.3
- Visual Studio 2015 and NuGet 3.4.4
- Visual Studio 2015 and NuGet 3.5.0 beta 2

The contents of the System.Runtime.InteropServices.RuntimeInformation NuGet package is shown below:

![image](https://cloud.githubusercontent.com/assets/372361/17294307/e18bf5ce-57ed-11e6-9660-737fec7b2788.png)

If I copy the `ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll` into `lib/netstandard1.1` inside the global NuGet package cache on the local machine then the install succeeds. So I suspect the NuGet package needs to be updated to be compatible with NuGet unless NuGet should be handling the assembly being in the ref folder.

**Comment by emgarten** [comment]
> So I suspect the NuGet package needs to be updated to be compatible with NuGet unless NuGet should be handling the assembly being in the ref folder.

NuGet does not use the `ref` or `runtimes` folders for packages.config projects, those projects can only consume non-runtime specific assets from NuGet.

**Comment by mrward** [comment]
OK that means it is not something for NuGet to fix. I have looked at a few .NET Core NuGet packages and they all seem to have a lib\netstandard or a lib\portable folder so it may just be this one has not been updated.

I will close this issue and open one I guess on the dotnet/corefx GitHub repository and see if they plan to modify the NuGet package so it can be used by projects with a packages.config file.

**Comment by mrward** [comment]
Looks like this problem has already been reported on dotnet/corefx:

https://github.com/dotnet/corefx/issues/10445
