### ISSUE TITLE
-Force is documented on Install-Package but is not supported

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3260]
The [NuGet PMC documentation](https://docs.nuget.org/consume/package-manager-console-powershell-reference), the `Install-Package` command apparently should have (or once had) a `-Force` option. But it actually doesn't.

```
PM> Install-Package Newtonsoft.Json -Force
Install-Package : A parameter cannot be found that matches parameter name 'Force'.
At line:1 char:33
+ Install-Package Newtonsoft.Json -Force
+                                 ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

Actions:
1. Either the docs should be updated to remove this option or the option should be implemented.
2. We should more clearly document what `-Force` does on each command it an option on. `Uninstall-Package` is the only command that supports that option today and `-Force` seems to ignore the fact that the package you are uninstalling may be depended upon by other installed packages.
3. Should it be supported on `Update-Package` or `Sync-Package`?

**Comment by karann-msft** [comment]
updated docs. removed `force` option for `install-package`. 
`uninstall-package` would not uninstall a package if another depends on it unless you use it with `force` which seems like the expected behavior. 
Whether this should be supported for `update-package` or `sync-package` is a different discussion.
