### ISSUE TITLE
Test interactive scenarios in PMC

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3261]
Right now, we do not have tests covering the interactive prompts. These prompts are implemented using `Host.UI.PromptForChoice` in the cmdlet. Unfortunately, this API is [not easily testable](http://stackoverflow.com/a/21357835). 

We should figure out a way to test these things. Instances of this include:
- resolving file conflicts (e.g. during package update)
- warning about deprecated frameworks
- whether or not to display more packages in `Get-Package` list

**Comment by rrelyea** [comment]
If automation isn't reasonable, we can have this added to the manual test run that we have done daily. If we write the test "script", we can have this done.

**Comment by rrelyea** [comment]
as a short term, could you please -- 
1) write up a short test script
2) work with me to have test team add to manual test data.

**Comment by joelverhagen** [comment]
# Verify that the PMC warns about deprecated dotnet
1. Create a new C# Class Library (Portable) project.
2. When selecting the portable targets, select .NET Framework 4.6 and ASP.NET Core 1.0.
3. Open the project.json in the created project.
4. Verify that the "dotnet" framework is under the "frameworks" section.
5. Right-click on the project and Manage NuGet Packages...
6. In the Installed tab, verify the Microsoft.NETCore.Portable.Compatibility is eligible for updates.
7. Open the Package Manager Console and type "Update-Package"
8. Verify that there is a warning about the "dotnet" framework being deprecated.
9. Type the "N" option and press Enter.
10. Ensure that no more errors are outputted.

# Verify that interactively handling file conflicts works
1. Create a new C# Console Application project.
2. Add a folder to the project called "Scripts".
3. Add a text file to the "Scripts" folder called "jquery-3.1.0.js". Leave it empty.
4. Open the Package Manager Console and type "Install-Package jQuery -Version 3.1.0"
5. Verify there is a prompt about overwriting the text file you added.
6. Type the "N" option and press Enter.
7. Verify that the "jquery-3.1.0.js" file is still empty.

# Verify that listing packages in PMC is interactive
1. Open the Package Manager.
2. Type "Get-Package -ListAvailable -PageSize 1 -Source https://www.nuget.org/api/v2"
3. Verify a prompt comes up asking whether more packages should be displayed.
4. Type the "Y" option and press Enter.
5. Verify another package is display and another package is displayed.
6. Type the "N" option and press Enter.
7. Verify no more packages are displayed.

**Comment by joelverhagen** [comment]
I have given the test team these new test cases. They have added them to their routine pass.
