### ISSUE TITLE
Project based dependencies are being ignored in the project.json file

### ISSUE THREAD

**Issue by tsublette** [NuGet/Home#3263]
I have a fairly simple project that I am porting to .net Core. The following is my project.json file

```
{
  "version": "2.0.0-*",
  "description": "Library package for slicing and support optimization",
  "authors": ["3DSIM, LLC"],

  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "Newtonsoft.Json": "9.0.1",
    "StyleCop.Analyzers": "1.0.0",
    "_3DSIM.SupportOptimization.Core": {
      "type": "build",
      "target": "project"
    },
    "_3DSIM.Utility.Core": {
      "type": "build",
      "target": "project"
    }
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}
```

I have 2 project based dependencies _3DSIM.SupportOptimization.Core and _3DSIM.Utility.Core. When I call `nuget pack project.json -Prop Configuration=Debug` I expect the lib folder to contain all 3 dlls. It only contains the single dll from the main project and not utility or supportOptimization. Attached is the nuspec file created inside the nupkg file.
![image](https://cloud.githubusercontent.com/assets/6877180/17311330/b44ded1e-5807-11e6-9b49-6b2a09e50971.png)

The external packages are correct but my internal packages have been ignored.

**Comment by tsublette** [comment]
forgot to add that I downloaded the beta version of nuget -> 3.5.0.1520

**Comment by emgarten** [comment]
Try the latest nightly build from https://dist.nuget.org/index.html

**Comment by tsublette** [comment]
I get the same result with build 3.6.0.1726

**Comment by tsublette** [comment]
Bump - any update on this?

Thanks!

**Comment by tsublette** [comment]
Just tried this again 3.6.0.1842 (nightly build). It still does not include project dependencies.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. At this time we suggest moving from project.json to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
