### ISSUE TITLE
[Test Failure] Package ‘EntityFramework’ can’t be installed into UWP template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3265]
**Description:** 
Error: ‘Package restore failed’ and warning ’Could not find rule set file’ show in error list when trying to install Package ‘EntityFramework’ into an UWP template.

**Repro Steps:**
1. New project -> Other Languages ->Visual C# ->Windows ->Universal ->Blank App (Universal Windows).
2. Right-click on the project and click ‘Manage NuGet Packages…’.
3. Open ‘Browse’ tab and try to install package ‘EntityFramework’.

**Expected Result:**
Package ‘EntityFramework’ can be installed successfully.

**Actual Result:**
Package ‘EntityFramework’ can’t be installed with the error and warning as below screenshot.
![entityframeworkcannotbeinstalledintouwp](https://cloud.githubusercontent.com/assets/20632625/17322199/e6739574-58ce-11e6-9785-af9b0a9c2f38.png)

**Note:**
It also repro on Dev14 U3+NuGet VSIX 1704.

**Comment by rrelyea** [comment]
@v-luzh - couple of questions, since I don't find the report above totally without question. I'd like you to explain where it works, and where it doesn't.
Are you saying that this works with Dev14 U3 (which comes with NuGet 3.4.4) but it breaks as soon as you upgrade to 3.5.0.1704

**Comment by v-luzh** [comment]
**Note:**
1.It is found on Dev15 Preview4 25601.01.
2.It repro on Dev14 U3 (25420.01.00)+VSIX 3.5.0.1704.
3.It doesn't repro on Dev14 U3 only.

**Comment by v-nancyj** [comment]
Same error occurs when trying to install package 'NewtonSoft.json version 9.0.1' into a C#->Class Library (Portable) template on Dev14 U3 (25420.01.00)+VSIX 3.5.0.1726.
![untitled83](https://cloud.githubusercontent.com/assets/20632775/17359740/8e7b2806-599a-11e6-9971-03df494421b4.png)

**Comment by rrelyea** [comment]
@alpaix - need to consider for Dev15 preview 4. Sounds like serious regression.

**Comment by alpaix** [comment]
`EntityFramework` only targets `net40` and `net45`. Neither of them is compatible with UWP's `uap10`.
That's the reason package install fails.

You can clearly see this in output window:

<pre>
Restoring packages for 'App3'.
Restoring packages for c:\users\alpanov\documents\visual studio 15\Projects\App3\App3\project.json...
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0). Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0.
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package EntityFramework 6.1.3 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package EntityFramework 6.1.3 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'App3'.
Package restore failed. Rolling back package changes for 'App3'.
========== Finished ==========
Time Elapsed: 00:00:04.2305839
</pre>

**Comment by alpaix** [comment]
We just verified that Dev14 U3 (with NuGet 3.4.4) installed EF 6.1.3 incorrectly - it should be failing. So that was a 3.4.4 bug.

@v-luzh @v-nancyj Please remove this test from the test script.
We'll reconsider adding it back when EFCore starts supporting UWP projects.
