### ISSUE TITLE
[Test Failure] Menu items “Package Manager Console” and “Manager NuGet Package for Solution” are disabled after installing Dev14 VSIX 1704

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3267]
**Repro Steps:**
1. Create a new C#->SharePointApp project.
2. Select “Tools”-> “NuGet Packages Manager”.

**Expected Result:**
Menu items “Package Manager Console” and “Manager NuGet Package for Solution” are available.

**Actual Result:**
Menu items “Package Manager Console” and “Manager NuGet Package for Solution” are disabled as below screenshot.
![untitled882](https://cloud.githubusercontent.com/assets/20632775/17323050/f295686a-58d2-11e6-9a7d-cc32ed03be6a.png)
**Note:**
It doesn’t repro before installing Dev14 VSIX 1704.

**Comment by rrelyea** [comment]
@v-nancyj - are you saying this works with the preview dev branch build (1698), but breaks with 1704?

**Comment by v-nancyj** [comment]
@rrelyea -Yes,This works with the preview dev branch  build 1698,but breaks with build 1704.

**Comment by rrelyea** [comment]
@joelverhagen - this sounds like the dev14/dev15 clean happened on build 1704. did that break the dev14 vsix for this scenario?

**Comment by joelverhagen** [comment]
Attempts:
- VS: VS14, VS15
- Builds: 1698, 1704, 1721 (`release-3.5.0-rc` latest), 1731 (`dev` latest),
- Website type: Web forms, MVC
- Manage packages on: solution, add-on project, web project

Could not reproduce this. Could you provide us with a VM that can reproduce this issue?

Thanks!

**Comment by v-nancyj** [comment]
@joelverhagen -This bug can't repro on the last build 1731 ( dev latest) during my investigation, please help to close the bug. Thanks!
