### ISSUE TITLE
Add Profile151 to the _profilesWithOptionalFrameworks

### ISSUE THREAD

**Issue by JonDouglas** [NuGet/Home#3268]
It looks like there are some optional profiles potentially missing that support `monotouch1+monoandroid1` and `xamarin.ios1` 

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/DefaultPortableFrameworkMappings.cs#L110-L113

**Given a use-case:**
Attempting to add the following package to a blank Xamarin.iOS project:

https://www.nuget.org/packages/velox.core/

This package targets **Profile 151 (v4.6)** - `portable-net451-win81-wpa81`

This works in **XS 6.0** and **XS 6.1** because it is marked compatible in **Mono** via the `Xamarin.iOS.xml` file in `/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/xbuild-frameworks/.NETPortable/v4.6/Profile/Profile151/SupportedFrameworks`

However this will fail in **VS 2015** because the profile is not included in the `_profilesWithOptionalFrameworks` list above. Thus throwing an error such as:

`Could not install package 'velox.core 1.0.2.8'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Please let me know if this is the correct behavior, or if this bug is valid in this use case.

**Version Information:**
Visual Studio Professional 2015 - Update 3 (Version 14.0.25421.03)

NuGet Package Manager 3.5.0

Xamarin 4.1.2.18

Xamarin.iOS 9.8.2.22

**Comment by mrward** [comment]
Looking at the PCL profiles that currently ship with Mono 4.4.2 we should also look to add the following profiles to the list that are marked as compatible with the Xamarin frameworks:
- 44
- 240

The full list of PCL profile from my Mono 4.4.2 install are:

5, 6, 14, 19, 24, 37, 42, 47, 92, 102, 136, 147, 158, 225, 240, 255, 328, 336, 344
7, 49, 78, 111, 259
44, 151

/cc @mhutch

**Comment by mhutch** [comment]
Yes, the Xamarin frameworks should be compatible with all of those.

**Comment by nkolev92** [comment]
I think this issue is redundant at this point, so as such I'm closing it.
