### ISSUE TITLE
[VS 2015 CTP / 3.0.60225.100] Relative paths changed in a bad way?

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#327]
Note: import from http://nuget.codeplex.com/workitem/4492

Before when I installed a package, the relative paths would look like this:

```
<HintPath>..\..\..\lib\Catel.Fody.2.5.0\lib\portable-net4+sl4+wp7+win8+wpa81+MonoAndroid14+MonoTouch40\Catel.Fody.Attributes.dll</HintPath>
```

Now it looks like this:

```
<HintPath>C:\Source\Catel\src\..\lib\Catel.Fody.2.5.0\lib\portable-net4+sl4+wp7+win8+wpa81+MonoAndroid14+MonoTouch40\Catel.Fody.Attributes.dll</HintPath>
```

Doesn't this mean it will only work on my machine instead of on all machines?

**Comment by yishaigalatzer** [comment]
Thanks for reporting this. This indeed wrong and we fixed this for RC.
