### ISSUE TITLE
Update packages failed at solution level with multiple UWP projects

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3270]
Since we remove auto fallback of v2 lock file to v1, it creates nuget actions for all the project libraries including project references as well which fails at later stage to get package metadata. 

This only happens with update packages at solution level with all UWP projects.

**Comment by emgarten** [comment]
This can happen for any restore from the UI, it is not specific to solution level operations. The UI fails when checking if a project requires license acceptance.

**Comment by jainaashish** [comment]
Surprisingly it doesn't repro at project level.

**Comment by rrelyea** [comment]
Update 1 of VS 2015 had a bug in the build tasks.
Justin had removed the workaround for that.
Let's add the workaround back in for release-3.5.0-rtm branch, and leave the workaround removed for 3.6.

**Comment by emgarten** [comment]
Reverted changes for 3.5.0 in build 1734
