### ISSUE TITLE
Re-enable PackFromProjectWithDevelopmentDependencySet for VS15

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3272]
Disabled here: https://github.com/NuGet/NuGet.Client/pull/810

**Comment by drewgillies** [comment]
Disabled due to MSBuild break in VS15 preview 3.

**Comment by drewgillies** [comment]
Guidance at this point is to wait until preview 4 and re-evaluate MSBuild behavior.

**Comment by rrelyea** [comment]
I think you solved this. have you reenabled the test yet?

**Comment by drewgillies** [comment]
Blocked by VS15 E2E breaks, currently being attended to by @mishra14 .

**Comment by rrelyea** [comment]
Rohit - Can you please reenable?
