### ISSUE TITLE
Installing EF Core 1.0 into ASP.NET 4 app produces incorrect binding redirect version

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#3274]
EF Core 1.0 uses System.Collections.Immuable/1.2.0. When installed into a nuget2 project (packages.config), the wrong binding redirect version is created.
## Repro

File -> New Project... -> ASP.NET 4 WebAPI
Install-Package Microsoft.EntityFrameworkCore -Version 1.0.0
## Expected result

web.config should contain

``` xml
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.2.0.0" newVersion="1.2.0.0" />
      </dependentAssembly>
```
## Actual result

web.config contains

``` xml
      <dependentAssembly>
        <assemblyIdentity name="System.Collections.Immutable" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.36.0" newVersion="1.1.36.0" />
      </dependentAssembly>
```
## Setup info

VS 2015 Update 3
NuGet Package Manager 3.5.0.1484

**Comment by natemcmaster** [comment]
More information: this is conflated with dotnet/roslyn#12255. Although it is correct that 1.1.36.0 is the version of System.Collections.Immutable that actually ends up in the output folder, Microsoft.EntityFrameworkCore depends on 1.2.0.0. 

In this kind of scenario, should the binding redirect that NuGet generates pointing back to old versions? 
`<bindingRedirect oldVersion="0.0.0.0-1.2.0.0" newVersion="1.1.36.0" />`

**Comment by rrelyea** [comment]
NuGet should investigate, but won't likely get to for a while.
1) would setting specific version to true be best?

**Comment by natemcmaster** [comment]
FWIW this issue is fixed by upgrading to Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.2.

**Comment by natemcmaster** [comment]
Nothing actionable here for NuGet anymore.
