### ISSUE TITLE
NuGet doesn't add some references to the project file

### ISSUE THREAD

**Issue by tuzand** [NuGet/Home#3276]
I'm using the most recent version of Nuget (3.4.4) with VS 2015. I would like to reinstall the packages from packages.config in order to add the references to the vcxproj file.
After finishing the command Update-Package -Reinstall, the following two packages are missing from the vcxproj file, and must be manually added:
- hdf5-v120-complete
- boost_python2.7-vc120

The issue is the same with the most recent version of Nuget for VS2013 (2.12)
What am I doing wrong?
Thank you!

I attached my packages.config file.
[packages.zip](https://github.com/NuGet/Home/files/401333/packages.zip)

**Comment by emgarten** [comment]
Are the references added during Install-Package? Which references are missing after reinstall from the packages you mentioned?

**Comment by tuzand** [comment]
Thank you for your answer.
No Install-Package also doesn't help.
I tried to install first "gflags" package, it was added to the project file without any problem.
After that I tried "hdf5-v120-complete" and it won't be added to the project file.
I am generating the VS project with cmake, so I must always add a following line manualy to the "ExtensionTargets ImportGroup" in the vcxproj file in order to compile the project:
`<Import Project="..\..\..\NugetPackages\hdf5-v120-complete.1.8.15.2\build\native\hdf5-v120.targets" Condition="Exists('..\..\..\NugetPackages\hdf5-v120-complete.1.8.15.2\build\native\hdf5-v120.targets')" />`
I appreciate any help.

**Comment by emgarten** [comment]
From the import you shared it looks like the package is authored incorrectly. The target file name must match the package id. 

In your case it looks like the package id is: hdf5-v120-complete  however the targets name is hdf5-v120

**Comment by tuzand** [comment]
Thank you for the suggestion, but in the downloaded "hdf5-v120-complete" package folder there is really a target file with a name of "hdf5-v120.targets", and my project can be compiled if I add that import line.
The problem is that this line must be added manually, after installing hdf5-v120-complete.
The problem persists also if I install this package without packages.config but with the NuGet-Package-Manager.
Is this maybe a bug of NuGet?

**Comment by emgarten** [comment]
> in the downloaded "hdf5-v120-complete" package folder there is really a target file with a name of "hdf5-v120.targets"

That is a bug in the package, those names need to match. NuGet will only add imports to targets with the exact same name as the package. See: http://docs.nuget.org/Create/Creating-and-Publishing-a-Package#import-msbuild-targets-and-props-files-into-project

**Comment by tuzand** [comment]
Thank you for your answer, I wrote to the owner of the package (daniel.gracia), but he didn't answer me. Who could help me in this case with this issue?

Link to the package: https://www.nuget.org/packages/hdf5-v120-complete/
