### ISSUE TITLE
Force Highest version to be used, does not work

### ISSUE THREAD

**Issue by patrickjamesbarry** [NuGet/Home#3277]
According to docs, I should be able to specify a version range and in the nuget.config file, use this attribute:

> <add key="dependencyVersion" value="Highest" />

This is not working. An older version of the dependency is still getting used.  Working on a nuspec file to define the nuget dependency version range.

**Comment by emgarten** [comment]
Would you share some repro steps?

**Comment by patrickjamesbarry** [comment]
Add this to nuget.config file:

```
         <config>
        <add key="dependencyVersion" value="Highest" />
    </config>
```

Create a new c# project and create a new a nuspec for it.

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
    <metadata>
        <id>MyProj</id>
        <version>15.2.1</version>
        <dependencies>
            <group>
                <dependency id="Newtonsoft.Json" version="6.0.8" />
                <dependency id="my-lib" version="[15.2.1.36,)" />
            </group>
        </dependencies>
    </metadata>

    <files>
        <file src="dist\release\w64\my*.dll" target="lib"/>
    </files>

</package>
```

Upload 2 nuget packages to your nuget feed, named 'my-lib' . One with version 15.2.1.36 and one with 15.2.1.37. After that package is in your nuget feed, perform a 'nuget restore' on your new project and observe you always get the older version of the dependency.  

`nuget restore -ConfigFile C:\Users\<USER>\AppData\Roaming\NuGet\NuGet.Config`

Observed on windows 7, NuGet Version: 3.4.3.855

**Comment by emgarten** [comment]
What type of project are you restoring? packages.config or project.json?

**Comment by patrickjamesbarry** [comment]
Project.json

Same behaviour observed usign 'dotnet restore'

**Comment by emgarten** [comment]
DependencyBehavior isn't supported for project.json yet, there is an issue tracking it here: https://github.com/NuGet/Home/issues/3159

You can float to the highest version by adding the package as a dependency in your project.json file and using `*`. Example: `"my-lib": "15.2.1.*"`

**Comment by patrickjamesbarry** [comment]
Just to clarify:

I have a project My-Proj, that is a project.json c#, Net451 project.
It depends on older nuget packages that have nuspec in them.
These older nuspec projects are the ones I am having problems with.

So MyProj depends on MyDependency1: version 1.0.0.\*  (THIS WORKS)
MyDependency depends on MyDependency2 (with version range)  This does not
work. Brings in old builds.

Make sense?

**Comment by emgarten** [comment]
MyProj needs to also depend on MyDependency2 to specify the floating behavior

**Comment by patrickjamesbarry** [comment]
So in order to get this to work I need to not count on transitive
dependency resolution?  Meaning:

MyProj --> Dependency1 --> Dependency2  --> Dependency3

needs to be:
MyProj -- >Dependency1
            -- >Dependency2
           -- >Dependency3

?

**Comment by emgarten** [comment]
That's correct, everything you want to float needs to be top level. This will be fixed with https://github.com/NuGet/Home/issues/3159
