### ISSUE TITLE
Restore ignores reference assembly from some transitive dependencies

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#3278]
## Repro

Restore this:

``` json
{
  "dependencies": {
    "Microsoft.NETCore.App": "1.0.0"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

Example of a transitive dependency:
Package structure of System.Runtime.Loader/4.0.0

```
lib/
├── net462
│   └── _._
└── netstandard1.5
    └── System.Runtime.Loader.dll
ref/
└── netstandard1.5
    └── System.Runtime.Loader.dll
```
## Expected output

System.Runtime.Loader is a dependency of Microsoft.NETCore.App so it should be included in lock file and its reference assembly made available in the "compile" section of the lock file.

``` json
 "System.Runtime.Loader/4.0.0": {
        "type": "package",
        "dependencies": {
          "System.IO": "4.1.0",
          "System.Reflection": "4.1.0",
          "System.Runtime": "4.1.0"
        },
        "compile": {
          "ref/netstandard1.5/System.Runtime.Loader.dll": {}
        },
        "runtime": {
          "lib/netstandard1.5/System.Runtime.Loader.dll": {}
        }
      },
```
## Actual output

The reference assembly is left out and placeholder substitute instead.

``` json
      "System.Runtime.Loader/4.0.0": {
        "type": "package",
        "dependencies": {
          "System.IO": "4.1.0",
          "System.Reflection": "4.1.0",
          "System.Runtime": "4.1.0"
        },
        "compile": {
          "ref/netstandard1.5/_._": {}  //<--difference
        },
        "runtime": {
          "lib/netstandard1.5/System.Runtime.Loader.dll": {}
        }
      },
```

This is inconsistent across different packages. For example, this bug does not appear for System.Collections/4.0.11
## Setup info

Repros in NuGet 3.4 and up
## Workaround

Add System.Runtime.Loader explicitly as a top-level dependency in project.json

**Comment by emgarten** [comment]
Microsoft.NETCore.App.nuspec excludes compile for this package:
`<dependency id="System.Runtime.Loader" version="4.0.0" exclude="Compile" />`

Adding it as a top level dependency as your workaround states will include compile again and override this.

**Comment by natemcmaster** [comment]
Aha, makes sense. Thanks @emgarten. I missed that key piece of Microsoft.NETCore.App.nuspec.
