### ISSUE TITLE
[VS 2015 CTP 5 / 3.0.60225.100] Don't reset checks after changing versions

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#328]
Note: import from http://nuget.codeplex.com/workitem/4491

Situation: 

I have 10 projects referencing a specific package. Now I add a new project to the solution and want to reference the same version. Before I could just right click => manage nuget packages => installed => check the new project. This ensured that I was using the same version all over the solution. 

In the new version, I do this: 

1) Manage NuGet packages (sln level) 
2) Filter on installed / search for the package name 
3) Click on the package => select the new projects (but only some of them) 
4) Ah, darn, it installs the latest by default => change version to what I already have installed on the solution 
5) All checkboxes get enabled again 

I think changing the version should not have any impact on the selected projects. 

I have also added a screenshot to make things more clear.

![image](https://cloud.githubusercontent.com/assets/1246444/6940250/3afc602a-d875-11e4-8b30-84df7f68fc64.png)

**Comment by feiling** [comment]
Fixed
