### ISSUE TITLE
Unable to install Microsoft.Net.Http into an iOS or Android project

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#3280]
This was originally reported on [Xamarin's bug tracker](https://bugzilla.xamarin.com/show_bug.cgi?id=43070)

With NuGet 2.12 or higher it is not possible to install Microsoft.Net.Http into an iOS or Android project. It fails when trying to install Microsoft.Bcl.Build 1.0.14.

```
Package Manager Console Host Version 3.4.4.1321

PM> install-package Microsoft.Net.Http
Attempting to gather dependency information for package 'Microsoft.Net.Http.2.2.29' with respect to project 'iOSClassLib', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'Microsoft.Net.Http.2.2.29' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.Net.Http.2.2.29'
Resolved actions to install package 'Microsoft.Net.Http.2.2.29'
Install failed. Rolling back...
Package 'Microsoft.Bcl.Build.1.0.14' does not exist in project 'iOSClassLib'
Package 'Microsoft.Bcl.Build.1.0.14' does not exist in folder 'c:\projects\tests\iOSClassLib\packages'
install-package : Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project 
that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
```
- Xamarin Studio 6.0.1 (NuGet 2.8.7) - OK
- Xamarin Studio 6.0.2 (NuGet 2.12) - Fails.
- Visual Studio 2013 (NuGet 2.12) - Fails.
- Visual Studio 2015 (NuGet 3.4.4) - Fails.

A workaround is to install the latest Microsoft.Bcl.Build 1.0.21 before installing Microsoft.Net.Http.

The Microsoft.Bcl.Build 1.0.14 NuGet package contains:

![image](https://cloud.githubusercontent.com/assets/372361/17432312/7c8987ca-5af6-11e6-82f9-a13d449540ee.png)

Each of the subdirectories inside the contents directory contain a single empty _._ file which is not shown in the screenshot.

The PCL profile folder looks odd to me `content\portable-net40+win8+sl4+wp71+wpa81` since it does not seem to map to any known profile. If I change it to be profile 78 `content\portable-net45+wp80+win` then Microsoft.Bcl.Build 1.0.14 will install into an iOS project using NuGet 2.12. So I suspect it is a problem with the NuGet package.

**Comment by emgarten** [comment]
> If I change it to be profile 78 content\portable-net45+wp80+win then Microsoft.Bcl.Build 1.0.14 will install into an iOS project using NuGet 2.12. So I suspect it is a problem with the NuGet package.

This does look like a package issue. NuGet adds the additional xamarin compatibility mappings for known frameworks such as 78, it doesn't try to extend this to profile variations that could also be compatible.

**Comment by mrward** [comment]
Thanks. Since this is not a NuGet problem and is fixed in the latest version of Microsoft.Bcl.Build I am going to close this issue.
