### ISSUE TITLE
[Linux] How to make xbuild *.csproj download the needed packages specified in packages.config file automatically?

### ISSUE THREAD

**Issue by acrolink** [NuGet/Home#3282]
I have noticed that running `xbuild *.csproj` searches the the parent folder for the needed Nuget packages inside `../packages` folder. Running `xbuild *.csproj` returns errors if the packages are not on that location. I have currently solved this issue by running `mono ~/.nuget/NuGet.exe install -OutputDirectory ../packages` first. My question how to automate this action? How to make xbuild download any missing packages automatically on build, if they are missing? Thank you.

**Comment by emgarten** [comment]
@acrolink take a look at https://github.com/kzu/NuGet.Restore

**Comment by acrolink** [comment]
Thanks @emgarten
