### ISSUE TITLE
Exception thrown when trying to manage NuGet packages on a project

### ISSUE THREAD

**Issue by CoskunSunali** [NuGet/Home#3283]
I started having the following error displayed whenever I click on "Manage NuGet Packages..." option on Visual Studio solutions and projects. It used to work and I don't remember installing or updating anything so that it could get broken all of a sudden.

I cleared the component cache, etc but no luck so far.

What might have gone wrong?

![nuget](https://cloud.githubusercontent.com/assets/6509380/17484627/7bcb7862-5d93-11e6-9e47-37547cd8d5c8.png)

**Comment by CoskunSunali** [comment]
Restarting my computer seems to have fixed the issue...

Keeping the issue open since you may want to see that this error has been thrown. If it is no importance, please feel free to close the issue.

**Comment by rrelyea** [comment]
Odd error. Have not seen. Putting into textual form, so that future searches will work:
"The invocation of the constructor on type 'NuGet.PackageManagement.UI.InfiniteScrollList' that matches the specified binding constraints threw an exception."

Resolving not repro.
