### ISSUE TITLE
Nuget add does not support wildcard

### ISSUE THREAD

**Issue by mdkf** [NuGet/Home#3284]
nuget.exe add *.nupkg -Source D:\Test -NonInteractive returns:
Illegal characters in path.

**Comment by gavynriebau** [comment]
Far from ideal but this issue can be worked around by using batch or powershell to do the wildcard expansion, e.g.

``` powershell
$packages = dir "$projectdir\*.nupkg"

ForEach ($p in $packages)
{
  nuget add $p -Source D:\Test
}
```

**Comment by rrelyea** [comment]
"NuGet.exe init" does this exact thing. Can you try that please?
If you still have issues, we'll be happy to talk more.

**Comment by scottjohnstone** [comment]
@rrelyea NuGet.exe init doesn't handle wildcards.  Here's what I used
```
$packages = Get-ChildItem "C:\source\repos\Projects\*.nupkg" -Recurse -Force
ForEach ($p in $packages)
{
    nuget add $p -Source C:\source\NuGetLocal
}
```
hth someone
