### ISSUE TITLE
Install/Update/Uninstall in PM UI should be disabled during installing/Updating/Uninstalling a package in PMC

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3285]
**Repro Steps:**
1.  New project -> Visual C# -> Web -> ASP.NET Web Application, then uncheck the box for "Application Insights".
2.  Click Web Forms template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Open ‘Manage NuGet Package for Solution…’.
5.  Open “Package Manager Console” and type "update-package" (or install).
6.  Try to do Install/Update/Uninstall package in Manage NuGet Package UI during the installing/Upgrading/Uninstalling command is still executing in PMC.

**Expected Result:**
Install/Update/Uninstall operation in Package Manager UI should be disabled during installing/Updating/Uninstalling a package in PMC.

**Actual Result:**
Install/Update/Uninstall operation in Package Manager UI are not disabled during installing/Updating/Uninstalling a package in PMC.

**Note:**
1. It happened on Dev15 Preview4 Willow install+NuGet 3.6.0-Beta1-1738.
2. It repro on Dev14 U3+NuGet 3.5.0-RTM-1737.
3. It repro on VS2015Update3 w/ NuGet 3.4.4.

**Comment by v-luzh** [comment]
It still reproes om Main\33912.166 + NuGet Client Dev\6.8.0.22, so we reopen it to track the issue.

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
Closing as a dup of https://github.com/NuGet/Home/issues/8304
