### ISSUE TITLE
The vertical scrollbar is truncated in the default layout of Package Manager UI Window

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3286]
**Repro Steps:**
1.  New project -> Visual C# -> Web -> ASP.NET Web Application, then uncheck the box for "Application Insights".
2.  Click Web Forms template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Open ‘Manage NuGet Package for Solution…’.
5.  Click “Browse” tab and click a package.

**Expected Result:**
The vertical scrollbar in the right pane show correctly in the default layout of Package Manager UI Window.

**Actual Result:**
The vertical scrollbar in the right pane is truncated in the default layout of Package Manager UI Window as below screenshot. It thinner than normal scrollbar, so it is hard to select.
![verticalscrollbar](https://cloud.githubusercontent.com/assets/20632625/17510336/1554226e-5e51-11e6-911a-145a9cbd5aaa.png)
**Note:**
1. It happened on Dev15 Preview4 Willow install+NuGet 3.6.0-Beta1-1738.
2. It repro on Dev14 U3+NuGet 3.5.0-RTM-1737.
3. It doesn’t repro on VS2015Update3 w/ NuGet 3.4.4.
4. It will not repro after you drag the right-boundary of the window to the right side.
5. The scrollbar will disappear when you drag the right-boundary of the window to the left side.

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.

**Comment by v-luzh** [comment]
It's OK to close since it is fixed on Main\33912.166 as below.
![image](https://github.com/NuGet/Home/assets/20632625/e136d7c0-28a9-4a4c-aee3-5675723fed07)
