### ISSUE TITLE
Point people to v3 packages in docs

### ISSUE THREAD

**Issue by droyad** [NuGet/Home#3287]
The `Nuget.Core` nuget package can't be used by netcoreapp and ASP.NET Core projects as it only targets `4.0-client`.

Happy to at least spike this out if it fits into plans for the product, I couldn't find any issues discussing it.

Until xproj/csproj references work, I think a side-by-side project approach would be the best approach.

**Comment by emgarten** [comment]
netstandard is supported in the latest packages, checkout http://daveaglick.com/posts/exploring-the-nuget-v3-libraries-part-1

Source code is here: https://github.com/NuGet/nuget.client/

**Comment by droyad** [comment]
@emgarten Ah that explains it. I've put up a few PRs explaining this as I spent a couple of hours trying to find a later version. 

Perhaps updating the Nuget.org description for `Nuget.Core` to something like the following will help in the future:

> NuGet.Core is the core framework assembly for NuGet that the rest of NuGet builds upon. Starting with NuGet 3, this package has been broken down into smaller packages. See http://daveaglick.com/posts/exploring-the-nuget-v3-libraries-part-1 for more information.

**Comment by harikmenon** [comment]
@karann-msft  - cn you own this?

**Comment by seesharper** [comment]
What about NuGet.ProjectManagement ?

This package does not seem to support .NetCore

Or is there another way to do a package install from .NetCore?

**Comment by karann-msft** [comment]
Updated the link. Thanks for PR @droyad
