### ISSUE TITLE
Adding clear cache button to VS package manager settings

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3289]
Using this issue to track and get UI feedback for the clear cache button to be added into VS package manager settings page.

**Comment by mishra14** [comment]
![2016-08-09 6](https://cloud.githubusercontent.com/assets/10507120/17528699/4b0ebe04-5e25-11e6-8af0-feb8e1ff674e.png)

@harikmenon @yishaigalatzer @rrelyea : Let me know if this looks fine.

Thanks

**Comment by alpaix** [comment]
@harikmenon Do you think we need to emit telemetry events on errors here as well?

**Comment by harikmenon** [comment]
Yes, we should. We should create an Event Called NuGet Commands or something similar to track this.

**Comment by harikmenon** [comment]
Is there a spec for this?

**Comment by mishra14** [comment]
@harikmenon  : 
[Spec for button](https://github.com/NuGet/Home/wiki/Add-Clear-Cache-button-to-VS-Package-Manager-options)
[Spec for related work on dotnet nuget locals](https://github.com/NuGet/Home/wiki/Support-locals-command-in-dotnet-cli)

**Comment by harikmenon** [comment]
One change we should do is get rid of the confirmation box. If it succeeds, we should just add a text and icon below the button stating the success/failure of the operation. Modal dialog on top of modal dialog is not a good design IMO.

Something like.

Success: NuGet caches cleared successfully at {DateTime}

Failure:   Unable to clear NuGet cache at {DateTime}. + Any workarounds that might fix this?

In addition to this, we should instrument this.

Lets create a new NuGetVSCommands event and a property called VS.NuGet.CommandName and fire it every time someone clicks on the button.

I can work with you in person for more specific details.

**Comment by mishra14** [comment]
Based on offline discussion, i will remove dialog and add messages under the button and a webpage link to better handle errors. Updating the spec for this.

**Comment by mishra14** [comment]
Updated UI - [spec link ](https://github.com/NuGet/Home/wiki/Add-Clear-Cache-button-to-VS-Package-Manager-options)

![2016-08-18 7](https://cloud.githubusercontent.com/assets/10507120/17796340/96a187d8-6574-11e6-808b-077eab738780.png)

![2016-08-18 8](https://cloud.githubusercontent.com/assets/10507120/17796346/9c0885f0-6574-11e6-8843-3259e40d0180.png)

![2016-08-18 9](https://cloud.githubusercontent.com/assets/10507120/17796349/9f3c3ed8-6574-11e6-9fc4-0629f51150f3.png)

![2016-08-18 10](https://cloud.githubusercontent.com/assets/10507120/17796352/a3d44c24-6574-11e6-8b25-7b698d86b71a.png)

**Comment by harikmenon** [comment]
Looks good. Minor feedback.

Th button and the last option has a huge gap, make it consistent with the size of the current groups.

The link to the doc should be a hyperlink not text.

**Comment by mishra14** [comment]
Updated : 

![2016-08-19](https://cloud.githubusercontent.com/assets/10507120/17826473/f9382e90-6625-11e6-9b3d-a7bc19b779f6.png)

![2016-08-19 1](https://cloud.githubusercontent.com/assets/10507120/17826480/0471d0cc-6626-11e6-9939-dc8056e9d1da.png)

![2016-08-19 2](https://cloud.githubusercontent.com/assets/10507120/17826479/0470cd76-6626-11e6-95f6-4fd1f935773d.png)

![2016-08-19 8](https://cloud.githubusercontent.com/assets/10507120/17826485/1176b8c8-6626-11e6-87e4-82beebf69dec.png)

**Comment by harikmenon** [comment]
LGTM

**Comment by mishra14** [comment]
Merged : https://github.com/NuGet/NuGet.Client/pull/829
