### ISSUE TITLE
Creating NuGet package for Templated Control (using Generic.xaml)

### ISSUE THREAD

**Issue by ratishphilip** [NuGet/Home#3293]
Hi,
@emgarten @yishaigalatzer @Pilchie @jasonmalinowski  @ericstj 

This is an extension of discussion we had in the issue #1834

I have a control library which contains a TemplatedControl named **VisualControl**. Within the library there is a **Themes** folder which contains the **Generic.xaml** file. This file contains the default template for **VisualControl**.

Now I am creating a NuGet package which targets x86, x64 and ARM. 
Here is the directory structure I have created for the NuGet package
![nuget_theme_structure](https://cloud.githubusercontent.com/assets/7021835/17557324/976a429a-5ecb-11e6-81ff-0b8550e3ae15.png)

Now when I add this NuGet package to my test application and add the **VisualControl** to the XAML file, the default theme is not applied to the **VisualControl**.

Am I packaging the file in an incorrect way?

Are the following files required in the NuGet package. If yes, where should they be placed?
**Generic.xbf**
**TestVisualControl.pri**
**TestVisualControl.xr.xml**

**Comment by ratishphilip** [comment]
Found out the solution myself.
- The **Generic.xbf** file should be placed in the **Themes** folder along with **Generic.xaml**.
- The **TestVisualControl.xr.xml** file should be placed in a folder named **TestVisualControl**. This folder should be placed inside **uap10.0** folder of each platform.
- The **TestVisualControl.pri** should be placed inside the **uap10.0** folder of each platform.

Here is what the final folder structure should look like
![nuget_theme_correct_structure](https://cloud.githubusercontent.com/assets/7021835/17575329/379ce1ae-5f1d-11e6-9ad5-0e08877507fa.png)

Creating a NuGet package with this folder structure would ensure that the style defined in the **Generic.xaml** file is loaded.

**Comment by harikmenon** [comment]
Thanks @ratishphilip . We have been working on building a guide for this in NuGet docs. A sneak preview of this is available here. One thing to note is that you dont the xbf since the compilation of the host app will generate and override that for you.

http://nugetdocsbeta.azurewebsites.net/ndocs/guides/create-uwp-packages

**Comment by ratishphilip** [comment]
@harikmenon 
Thank you very much for the info.
