### ISSUE TITLE
Add source to detailed logging (consider for 3.5)

### ISSUE THREAD

**Issue by MarkOsborneMS** [NuGet/Home#3294]
Microsoft's internal CoreXT tool has been running with a fork of nuget that adds additional logging indicating the source when a package is download from a remote source. e.g.:
`Added package 'Newtonsoft.Json.9.0.1' to folder 'E:\repos\mytest\packages' from source 'https://api.nuget.org/v3/index.json'`

Adding this functionality to nuget would allow CoreXT to get back onto the mainline nuget rather than maintain its own fork.

@rrelyea please consider for 3.5
/cc @yishaigalatzer @harikmenon 

See PR: NuGet/NuGet.Client#783

**Comment by joelverhagen** [comment]
Merged into `dev` with https://github.com/NuGet/NuGet.Client/commit/b335ef98b50bffe1d5e07a987e881d4dd9994f2f. @rrelyea, we spoke offline about this potentially going into 3.5.
