### ISSUE TITLE
Have better UI to unlist all package versions at once

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#3295]
There should be a way to unlist all packages/package versions instead of having to go separately on each version and un-listing.

**Comment by rrelyea** [comment]
Rohit had a support request for a customer that had many things to unlist.
We ended up helping him write a script, but our server UI should be enhanced to support this better.

**Comment by rohit21agrawal** [comment]
Current workaround for doing this through a script :

Powershell : 

```
$apiKey = "[fill in API key here]"


$packageList = @() # fill in package list array

# foreach package, get the project.json and get the versions foreach($package in $packageList) {
    $lower = $package.ToLowerInvariant();

    $json = Invoke-WebRequest -Uri "https://api.nuget.org/v3-flatcontainer/$lower/index.json" | ConvertFrom-Json

    foreach($version in $json.versions)
    {
      Write-Host "Unlisting $Package, Ver $version"
      nuget delete $package $version $apiKey -source https://api.nuget.org/v3/index.json
    }
}
```

Ruby : https://gist.github.com/haf/760ac442e309b94bd891656444ef5615

**Comment by aloneguid** [comment]
@rohit21agrawal this is brilliant, thank you. A small modification to this and ready to use function for your profile:

```powershell
function Remove-AllNuGetPackageVersions($PackageId, $ApiKey)
{
    $lower = $PackageId.ToLowerInvariant();

    $json = Invoke-WebRequest -Uri "https://api.nuget.org/v3-flatcontainer/$lower/index.json" | ConvertFrom-Json

    foreach($version in $json.versions)
    {
      Write-Host "Unlisting $PackageId, Ver $version"
      Invoke-Expression "nuget delete $PackageId $version $ApiKey -source https://api.nuget.org/v3/index.json -NonInteractive"
    }
}
```

**Comment by PatoBeltran** [comment]
@joelverhagen can you take a look at this and see if this is still a relevant concern?

**Comment by rohit21agrawal** [comment]
This should be moved to NuGet gallery

**Comment by nkolev92** [comment]
Issue moved to [NuGet/NuGetGallery #5534](https://github.com/NuGet/NuGetGallery/issues/5534) via [**ZenHub**](https://www.zenhub.com/)
