### ISSUE TITLE
Add build assets to the TFM compatibility check and assets file

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3296]
The guardrails compatibility check for target frameworks is built for xproj/project.json and ignores build assets.

With the move to MSBuild NuGet should include build assets during the compat check, and it should also write these items to the lock file to make it clear that they are assets selected from the package.

**Comment by karann-msft** [comment]
[Issue restoring MSBuild only NuGet package.pdf](https://github.com/NuGet/Home/files/412340/Issue.restoring.MSBuild.only.NuGet.package.pdf)

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Client@efae789c75899ca0bdd063f34a4b73cd41510d56
