### ISSUE TITLE
Improve logging when Default project Initialization fails

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3299]
This is related to https://github.com/NuGet/Home/issues/1215
When Default Project returns null, We have no idea what happens and error message "configuration is invalid" is incorrect. Need to improve logging for this case, When default project return null, we should provide all projects in DTEProjectCache, projectSafeName for default project.

**Comment by rrelyea** [comment]
@zhili1208  - is this checked in already?

**Comment by zhili1208** [comment]
not yet

**Comment by PatoBeltran** [comment]
@zhili1208 is this issue still relevant?

**Comment by zhili1208** [comment]
My current thought is adding more data event for initialization

**Comment by nkolev92** [comment]
I don't believe this is relevant anymore. We haven't had issues where we can't object the project name in a while, so no point in keeping this open.
