### ISSUE TITLE
Package manager Console displays: Signature specified is zero-sized.

### ISSUE THREAD

**Issue by derekgreer** [NuGet/Home#3300]
I've got a fresh install of Visual Studio 2015 update 3 and am getting the following message in the Package Manager Console:

Signature specified is zero-sized. (Exception from HRESULT: 0x80131237)

I've tried reinstalling the Nuget Package Manager extension, but the problem remains.

**Comment by rrelyea** [comment]
We've not seen this before. Sorry.

Can you please try the following:
1) repair VS

if that doesn't work, try "devenv /setup"

if that doesn't work, uninstall and reinstall VS 2015?

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
