### ISSUE TITLE
[Test Failure] PMC update information is incorrect after executing command ‘update-package <packageID>’

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3309]
**Repro Steps:**
1.  Create a C# UAP - Blank App (Universal Windows) template.
2.  Open ‘Manage NuGet Package for Solution…’ and ‘Package Manager Console’.
3.  Open ‘Browse’ tab and install Newtonsoft.Json 6.0.1 by install button on PM UI.
4.  Type ‘Get-Package -Updates’ in PMC.
5.  Type ‘Update-Package Newtonsoft.Json’ in PMC.

**Expected Result:**
The update information in PMC should be ‘Successfully installed 'Newtonsoft.Json 9.0.1' (the newest version is 9.0.1) to App1’.

**Actual Result:**
The update information in PMC show: ‘Successfully installed 'Newtonsoft.Json 6.0.1' to App1’, actually the package had been updated to 9.0.1, which you can see in the below screenshot.
![incorrectupdatemessage](https://cloud.githubusercontent.com/assets/20632625/17616495/b09d8906-60a7-11e6-9190-fce30693a812.png)

**Note:**
1. It doesn’t repro when you directly install the package to the latest version in PMC.
2. It happened on Dev14 U3 (25425.01)+NuGet 3.6.0-beta1-1746.
3. It doesn’t repro on Dev14 U3 25425.01 (NuGet 3.4.4.1321).

**Comment by rrelyea** [comment]
@v-luzh - can you please help me understand if we need to fix in 3.5rtm or 3.6beta1? Does the latest build from release-3.5.0-rtm branch show this same regression from 3.4.4?

**Comment by rrelyea** [comment]
Putting into 3.5rtm now. We'll want to fix then or 3.6, depending on the answer from @v-luzh

**Comment by v-luzh** [comment]
@rrelyea, this bug repro on 3.5 RTM as below screenshot. It didn't repro on 3.4.4. So we think it should be fixed in 3.5 RTM.
![verified](https://cloud.githubusercontent.com/assets/20632625/17684036/b65cbdd6-638a-11e6-8b37-f705f0c4d99d.png)

**Comment by zhili1208** [comment]
fixed it https://github.com/NuGet/NuGet.Client/commit/abf55b06af8f85586410cbcbc8156867746b9b3a
