### ISSUE TITLE
[Test Failure] Build error occur after installing package ‘Mvvmlight’ to VB Silverlight Application

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3310]
**Repro Steps:**
1.  Create a VB Silverlight Application through 'New Project->Templates->Visual Basic'.
2.  Right-click the project ‘SilverlightApplication3’ and open ‘Manage NuGet Package…’.
3.  Build the project, no error.
4.  Type ‘Mvvmlight’ in the search box of ‘Browse’ tab.
5.  Install the ‘Mvvmlight 5.3.0’ package to the porject by clicking install button.
6.  Build the project again.

**Expected Result:**
No build error occur after the installation of ‘Mvvmlight 5.3.0’ package.

**Actual Result:**
Build error occur after the installation of ‘Mvvmlight 5.3.0’ package as the below screenshot.
![builderror](https://cloud.githubusercontent.com/assets/20632625/17616540/057bb79a-60a8-11e6-9387-67a1888a7c10.png)
**Note:**
1. It happened on Dev14 U3 (25425.01)+NuGet 3.6.0-beta1-1746.
2. It repro on Dev14 U3 25425.01 (NuGet 3.4.4.1321).

**Comment by rrelyea** [comment]
@v-luzh - are these part of automated or manual tests? Is this a package problem (did a previous version of Mvvmlight work fine, but the latest versions done)?

**Comment by v-luzh** [comment]
@rrelyea, this issue found from automation testing, but it also repro on manual during my investigation. It also repro on 3.5 RTM. It happen on VB Sliverlight, but it **doesn't repro** on **C# Sliverlight Application**. So we don't think that is a package problem.

**Comment by rrelyea** [comment]
If you look at mvvmlight 5.3.0, you'll find: ".nuget\packages\mvvmlight\5.3.0\Content\ViewModel\ViewModelLocator.cs.pp"
This is why this would be a problem in a vb project.
Closing as "PackageInappropriateForProject"
