### ISSUE TITLE
PowerShell5 breaks EntityFramework install?

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3312]
Please investigate this issue that came via internal email.

**Comment by divega** [comment]
@zhili1208 @rrelyea can you share more information about this?

**Comment by zhili1208** [comment]
@divega this issue only repro on customer's win7 machine, doesn't repro on customer's win10. Also I didn't get an repro on my win7 box. The problem is that the ps1 files literally does not exist when PowerShell tries to run it.  It is created and the contents written to it just milliseconds later.

**Comment by divega** [comment]
Thanks @zhili1208. Do you mean the ps1 file from the package hasn't been written to disk?

cc @bricelam and @natemcmaster for insights or in case they have seen anything like this.

**Comment by natemcmaster** [comment]
> The problem is that the ps1 files literally does not exist when PowerShell tries to run it. It is created and the contents written to it just milliseconds later.

EF Core commands has [two different ps1 files,](https://github.com/aspnet/EntityFramework/tree/1.0.0/src/Microsoft.EntityFrameworkCore.Tools/tools) tools/init.ps1 and tools/install.ps1. Does NuGet ensure extraction from nupkg is complete before executing init.ps1 and/or install.ps1?

**Comment by zhili1208** [comment]
@natemcmaster Yes, I think nuget ensure the extraction complete, I will ask customer to verify this again, will provide more info later.

**Comment by zhili1208** [comment]
@divega @natemcmaster the customer found the root problem, when they removed a policy that prevented powershell scripts from running, they still had an __PSLockDownPolicy environment variable set to 4, which after removal, appears to have corrected the issue.

**Comment by divega** [comment]
Glad to hear. Thanks!

**Comment by bricelam** [comment]
Can NuGet warn during package install if that's set?

**Comment by zhili1208** [comment]
@bricelam Yes, I think Nuget did some policy check even change policy for customer before, I will check that, if there is no that check, will file an bug for that.
