### ISSUE TITLE
Cryptic error when doing update package

### ISSUE THREAD

**Issue by jikkujj** [NuGet/Home#3313]
When i run the command

```
Update-Package <packagename> -version <packageversion> -IgnoreDependencies -IncludePreRelease -FileConflictAction Overwrite
```

I get the error

```
Update-Package : packages
At line:1 char:15
+ Update-Package <<<<  <packagename> -version <packageversion> -IgnoreDependencies -IncludePreRelease -FileConflictAction Overwrite
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

What does "packages" mean?

**Comment by rrelyea** [comment]
What version of VS/NuGet are you using?
Are you using private package names? or can you share exact repro steps so we can duplicate the same problem?

**Comment by jikkujj** [comment]
I am using visual studio 2015 update 3 and nuget package manager 3.4.4 in a windows 7 OS.

I am using private package names. I was trying to do update-package

I just wanted some hint as to what might be the issue on my side

**Comment by emgarten** [comment]
@jikkujj would you try this again using the latest 3.5.0-rc version from https://dist.nuget.org/index.html

If you still get the error try changing the msbuild verbosity in visual studio to diagnostic under _options > projects and solutions > Build and Run > MSBuild project build output verbosity_, this will increase the powershell logging.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
