### ISSUE TITLE
False (or misleading) error message

### ISSUE THREAD

**Issue by jlanng** [NuGet/Home#3314]
I need to reinstall my packages because some of their dependencies have changed.  I'm calling the command

`update-package -reinstall`

but I'm getting the confusing error below.  It says the constraint isn't matched, but you can clearly see that it is.  I have tried 3.4.4 and 3.5 RC.

```
Update-Package : Unable to resolve dependencies. 'Expression.Interaction 3.0.40218' is not compatible with 'MyCorp.MyDependency 5.0.0.17-pilot constraint: Expression.Interaction (>= 3.0.40218)'.At line:1 char:1
+ update-package -reinstall
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

**Comment by emgarten** [comment]
Are all dependency constraints resolved in packages.config before the update takes place? Or is the project already in a broken state? In 3.5 RC do you see any additional warnings during this operation?

**Comment by jlanng** [comment]
Thanks for your reply Justin.

Here's the yellow text from 3.5 RC.  TBH, I don't see any conflicts and all these packages are available. Could it be something to do with my dependencies being pre-release?

`One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'MyCorp.Core.Presentation 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Core.Presentation.Infragistics 5.0.0.17-pilot constraint: MyCorp.Core.Presentation (>= 5.0.0.17)', 'MyCorp.Core.Presentation.Infragistics 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.AlertBar.Gui 5.0.0.17-pilot constraint: MyCorp.Core.Presentation (>= 5.0.0.17)', 'MyCorp.Extensions.AlertBar.Gui 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.AlertBar.Gui 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar 5.0.0.17-pilot constraint: MyCorp.Extensions.Settings (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar 5.0.0.17-pilot constraint: MyCorp.Extensions.Transport.InProcess (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar 5.0.0.17-pilot constraint: MyCorp.Extensions.Transport (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar.Gui 5.0.0.17-pilot constraint: MyCorp.Core.Presentation (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar.Gui 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar.Gui 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.FilterBar.Gui 5.0.0.17-pilot constraint: MyCorp.Extensions.FilterBar (>= 5.0.0.17)', 'MyCorp.Extensions.Notification 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.Notification 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.Security 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.Security 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.Security 5.0.0.17-pilot constraint: MyCorp.Extensions.Settings (>= 5.0.0.17)', 'MyCorp.Extensions.Settings 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.Settings 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.Transport 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.Transport 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.Transport.InProcess 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.WindowState 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)', 'MyCorp.Extensions.WindowState 5.0.0.17-pilot constraint: MyCorp.Host (>= 5.0.0.17)', 'MyCorp.Extensions.WindowState 5.0.0.17-pilot constraint: MyCorp.Extensions.Settings (>= 5.0.0.17)', 'MyCorp.Host 5.0.0.17-pilot constraint: QuickGraph (>= 3.6.61119.7)', 'MyCorp.Host 5.0.0.17-pilot constraint: MyCorp.Core (>= 5.0.0.17)'`

**Comment by emgarten** [comment]
I see packages that require `MyCorp.Host (>= 5.0.0.17)` however it looks like `MyCorp.Host 5.0.0.17-pilot` is installed, which is a pre-release version that does not meet the constraints.

**Comment by jlanng** [comment]
OK, got it.  It's down to the way we're producing our builds. Thanks for the swift response, much appreciated.  Those extra messages in 3.5 are a lifesaver!
