### ISSUE TITLE
A question about project.json specification and NuGet dependencies

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#3317]
If I add a dependency from one CoreCLR project to another, VS creates lines like

``` js
  "dependencies": {
    "ClassLibrary1": "1.0.0-*"
  }
```

Also, I can add a dependency manually with

``` js
  "dependencies": {
    "ClassLibrary1": { "target": "project" }
  }
```

If we [open](https://github.com/NuGet/NuGet.Client/blob/c79e1a06adfe06f9f3d12ac0d34e8e16ff5c1783/src/NuGet.Core/NuGet.ProjectManagement/Utility/JsonConfigUtility.cs#L38) JsonConfigUtility.cs from the latest changeset, we have found the following code:

``` cs
public static PackageDependency ParseDependency(JToken dependencyToken)
{
    var property = dependencyToken as JProperty;

    var id = property.Name;

    string version = null;
    if (property.Value.Type == JTokenType.String)
    {
        version = (string)property.Value;
    }
    else if (property.Value.Type == JTokenType.Object)
    {
        version = (string)property.Value["version"];
    }

    if (string.IsNullOrEmpty(version))
    {
        throw new FormatException(
            string.Format(CultureInfo.CurrentUICulture, Strings.DependencyDoesNotHaveValidVersion, dependencyToken.ToString()));
    }

    var range = VersionRange.Parse(version);
    return new PackageDependency(id, range);
}
```

It looks like `ParseDependency` should throw an exception for each dependency without specified version. So, I have the following questions:
- Is syntax `{ "target": "project" }` still valid?
- Will it be valid in the future?
- How VS parse files with the `{ "target": "project" }` fragments?

**Comment by rrelyea** [comment]
yes, target project is still valid.
in the future, we plan to move projectreferences to csproj ... so this is short lived with preview2 of the tooling.
NuGet code running in VS parses those fragments with this code: https://github.com/NuGet/NuGet.Client/blob/e2b7161273f13bf3e51023a3b109c3eb5eabd318/src/NuGet.Core/NuGet.ProjectModel/JsonPackageSpecReader.cs#L389
