### ISSUE TITLE
Unable to install SpeechRecognition from Nuget

### ISSUE THREAD

**Issue by taimur38** [NuGet/Home#3319]
Cross-Linking from here: https://github.com/Microsoft/Cognitive-Speech-STT-Windows/issues/10

Have tried clearing all packages, uninstalling and reinstall nuget, restarting VS, running VS as administrator. Not sure if it's just a NuGet error, since I can, for example, install the Newtonsoft.Json package fine.

Anything I can do? using VS2015, Windows10, with NuGet 3.4.4 

```
PM> Install-Package Microsoft.ProjectOxford.SpeechRecognition-x86
Attempting to gather dependency information for package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' with respect to project 'Kinect8', targeting 'Windows,Version=v8.1'
Attempting to resolve dependencies for package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2'
Resolved actions to install package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2'
Adding package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' to folder '<path_1>'
Added package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' to folder '<path_1>'
Install failed. Rolling back...
Package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' does not exist in project 'Kinect8'
Removing package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' from folder '<path_1>'
Removed package 'Microsoft.ProjectOxford.SpeechRecognition-x86.0.4.10.2' from folder '<path_1>'
Install-Package : Failed to add reference to 'SpeechClient'.
At line:1 char:1
+ Install-Package Microsoft.ProjectOxford.SpeechRecognition-x86
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

**Comment by taimur38** [comment]
nuget.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
  <disabledPackageSources>
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
</configuration>
```

**Comment by rrelyea** [comment]
What type of project are you trying to install this package into?

**Comment by zhili1208** [comment]
From your log, I guess it's win8.1 project, looks like adding reference failed, I think becasue SpeechClient.dll is for .netframework, win8.1 targets .netcore, you can try this.
add reference "speechClient.dll" manually, you will get "the project targets '.NETCore' while the file reference targets '.NETFramework'", I got this error message on my machine.

**Comment by taimur38** [comment]
@zhili1208 I get that exact message, good find. Is there no way around that? I don't typically work in the .NET world, so not sure if that's a dumb question.

It's frustrating because earlier I had to target windows 8.1 to get the kinect library to work, and now that's precluding me using speech to text. If there's no way around that, then the only way to get speech to text working with a kinect as microphone would be either:
- have a separate process targeting windows 10 using the STT SDK and stream audio over socket from kinect process
- read docs and try to use STT service without the SDK
- look at watson/amazon speech/etc

**Comment by rrelyea** [comment]
Kinect nupkgs should work fine with .NET Framework.
If you goal is to use speech APIs, this package may help: https://www.nuget.org/packages/Microsoft.Kinect

(i'm a bit out of date on kinect APIs, but used to be on the team.)
This discussion forum may help: https://social.msdn.microsoft.com/Forums/en-US/home?forum=kinectv2sdk

**Comment by taimur38** [comment]
@rrelyea thanks for the links and all the help @zhili1208 -- really appreciate it
