### ISSUE TITLE
NuGet default exclusion problem

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#332]
@sbopf

Hi

I have been investigating an issue I am having with nuget excluding a sub directory of a recursively included directory.

The include statement:
<file src="Content\**\*.*" target="Content\" />

The sub directory that is missing:
Content\LessFiles\Compiler\node\node_modules\less\bin

I didn't think default exclusion would apply to this situation but it is not publishing to the package. I have no exclude statements and everything else in the directory I am recursively including is being published. 

 I know this is not a critical issue but Any help is appreciated. (sorry in advance if I am overlooking something simple, but I could not find a solution)

Thanks

Sam

**Comment by deepakaravindr** [comment]
Comment from @ChrisSfanos 

We need a bit more details - can you share the whole .nuspec file so we can get a better idea of what you are attempting - thanks

**Comment by ChrisSfanos** [comment]
@sbopf:  We haven't heard back yet on this issue - please let us know the exact scenario and sample and we will do our best to help.  If not, we will go ahead and close this and you can reopen when you have a repro/scenario - thanks!

**Comment by yishaigalatzer** [comment]
Since we have not heard back we are closing this issue.

@sbopf
