### ISSUE TITLE
NuGet Packager

### ISSUE THREAD

**Issue by MelbourneDeveloper** [NuGet/Home#3321]
I'm having a lot of difficulties with the NuGet packager. I get a lot of errors like "object reference not set to an instance of an objects" etc. But, my main issue is that it's not always entirely clear how to include the types of libraries I want to include.

For example, I want to include libraries that are compiled for .NET Standard 1.6, but there doesn't seem to be an option for this. It only goes up for 1.4

I want to include libraries compiled for .NET Core, but there doesn't seem to be an option for this.

More importantly, I want to include libraries for iOS, MacOS, Android, etc. etc. but, I don't want to include those individual versions. I want to include 1 Portable library that spans all those platforms. How do I achieve this?

Where is the repo for the packager? I'd really like to crack open the code.

**Comment by emgarten** [comment]
Can you provide some repro steps for scenarios where you are getting `object reference not set to an instance of an objects`?

**Comment by MelbourneDeveloper** [comment]
No. That's why I need to download the code so I can catch the exception. But anyway, the repo is here apparently:

https://github.com/NuGet/NuGet.Client

**Comment by emgarten** [comment]
What steps did you perform to get the error?

**Comment by MelbourneDeveloper** [comment]
I already said, I have no idea. That's why I went hunting for the repo which you ignored.

_But as I also said, 
my main issue is that it's not always entirely clear how to include the types of libraries I want to include._

_For example, I want to include libraries that are compiled for .NET Standard 1.6, but there doesn't seem to be an option for this. It only goes up for 1.4_

_I want to include libraries compiled for .NET Core, but there doesn't seem to be an option for this._

_More importantly, I want to include libraries for iOS, MacOS, Android, etc. etc. but, I don't want to include those individual versions. I want to include 1 Portable library that spans all those platforms. How do I achieve this?_

**Comment by rrelyea** [comment]
Yes, that is where our code is...let us know what you learn.

The following wasn't clear:
Are you complaining about "nuget pack" or something else?
If so, what version of "nuget.exe" are you running?
If you are talking about doing things in VS causing problems, what version of VS are you using...and what version of the NuGet VS extension are you using?

**Comment by MelbourneDeveloper** [comment]
I'm talking about the "NuGet Package Explorer". I thought that other referred to it as "NuGet Packager" as well, but perhaps not.

Specifically, this what I am talking about:
![library types](https://cloud.githubusercontent.com/assets/16697547/17719855/f8bea744-6460-11e6-93b0-ed6b88552828.png)

The questions are:
- How do I attach a library for .NET Standard 1.5, or 1.6?
- How do I include a library compiled for .NET Core (are these libraries exactly the same as .NET Standard?)
- How do I include one (and only one) library compiled for Xamarin Forms (Portable) that will be deployed to any Xamarin platform (MacOS, Android, UWP, iOS, etc.)

**Comment by MelbourneDeveloper** [comment]
As a general question, why does the tool force you to specify a version for .NET Standard?

**Comment by rrelyea** [comment]
This tool is not owned by our team/company. I think they live here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer 
Please open an issue in their repo.
