### ISSUE TITLE
[Test Failure] Three packages can’t be updated in Azure Mobile Service template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3322]
**Repro Steps:**
1.  Click File -> New project -> Visual C# -> Web -> ASP.NET Web Application, then check the box for "Application Insights".
2.  Click 'Web Forms' template and click ‘Azure Mobile Service’.
3.  Open ‘Manage NuGet Packages for Solution…’ and click ‘Update’ tab.
4.  Update package ‘Autofac’ to the newest version.
5.  Try to update packages ‘WindowAzure.MobileServices.Backend’, ‘WindowAzure.MobileServices.Backend.Entity’ and ‘WindowAzure.MobileServices.Backend.Tables’.

**Expected Result:**
Packages can be updated successfully in step5. NuGet should resolve the confliction automatically. Same with what we did in NuGet 3.4.4.

**Actual Result:**
These packages can’t be updated due to unable to resolve dependency as below screenshot.
![threepackagescan tbeupdated](https://cloud.githubusercontent.com/assets/20632625/17694826/5043d1e4-63d8-11e6-9511-a596dd63b99e.png)
**Note:**
It happened on Dev14 U3+NuGet 3.6.0-beta1-1751.
It also repro on Dev14 U3+NuGet 3.5.0-rtm-1737.
It doesn’t repro on Dev14 U3+NuGet 3.4.4.1321. (It will resolve the confliction automatically)

**Comment by jainaashish** [comment]
This is the right behavior and shows correct error. And the reason it was working with nuget 3.4.4, is because it was downgrading Autofac to 3.5.2 and resolving these conflicts... which was wrong.

![image](https://cloud.githubusercontent.com/assets/18219758/17712605/9c0c1a96-63ab-11e6-8a86-6fc1874647a3.png)

**Comment by v-luzh** [comment]
@jainaashish, got it, thanks for your description.
