### ISSUE TITLE
Restricting package dependencies in .nuspec (ex. '< 0.7' not working)

### ISSUE THREAD

**Issue by asjafjell** [NuGet/Home#3323]
I have two c# libraries:
- _main-library_
- _dependency-library_ (released in version 0.6 and 0.7)

The _main-library_ has the following defined in .nuspec:

```
<dependency id="dependency-library" version="[0.6,0.7)"/>
```

According to documentation for [Nuget Versioning ](https://docs.nuget.org/create/versioning) this should restrict the _dependency-library_ to version 0.6. Inspecting the Nuget.org listing gives the following:

```
dependency-library (>= 0.6 && < 0.7.0)
```

Exactly as expected. Still, Visual Studio suggests to update _dependency-library_ to 0.7, and does so without hesitation. I once managed to get an error in a similar situation, giving a message saying that package restrictions stops me from doing an update, whick is what I want. Am I missing something here? 

Tested in Visual Studio Professional 2015 via Nuget Package Explorer.

**Comment by emgarten** [comment]
What type of project are you installing this package into? Is it packages.config or project.json based?

**Comment by asjafjell** [comment]
The packages are installed into a .NET library, packages.config based, @emgarten.

**Comment by emgarten** [comment]
Does updating the dependency to 0.7 succeed?

**Comment by asjafjell** [comment]
The info panel for the package within Visual Studio shows the limitation correctly, stating it has to be  `<0.7`, but the update succeeds without hesitation.

**Comment by rrelyea** [comment]
What version of NuGet are you using? (I'm assuming 3.4.4 in VS2015, but please verify)

**Comment by asjafjell** [comment]
Package Manager Console states `3.4.3.855`. Do you need more info for this?  If yes, the repositories I am testing with are publicly available.

**Comment by asjafjell** [comment]
Updating Visual Studio 2015 Professional Update 1 to Update 3 seems to have fixed the issue. The version of NuGet is still`3.4.3.855`, but the restrictions are now enforced. Unclear what caused it, but as far as I can see the problem is fixed.

**Comment by emgarten** [comment]
@asjafjell thanks for the update, I don't know of this problem existing in any version of NuGet since it's a pretty basic scenario. I'm glad it is fixed for you. Let me know if it shows up again.

**Comment by asjafjell** [comment]
No worries, just happy to help!
