### ISSUE TITLE
Unhandled Exception: nuget.exe 3.4.4.1321 on Windows

### ISSUE THREAD

**Issue by DougWest** [NuGet/Home#3327]
I have Powershell 2.0 and VS 2010 Professional (Version: 10.0,.30319) both installed on Windows (XP) Embedded POSReady 2009 Version 2.0 Service Pack 3 with .NET 2.0 SP2, 3 SP2, 3.5 SP1, & 4.
Running nuget.exe 3.4.4.1321 I get: 
Unhandled Exception: System.NotSupportedException: The requested security protocol is not supported. at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value) at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) at NuGet.CommandLine.Program.Main(String[] args)

I can't move off of this version of Windows (yet, but it is in the plan).

May I get a fix for this?

**Comment by rrelyea** [comment]
What is the command you are running with NuGet.exe?
Is there a small project you could attach that reproduces the problem, so we can investigate the problem?

**Comment by DougWest** [comment]
I run nuget bare, which should result in version and use information. Or I've run nuget with various commands and I still get the same Unhandled Exception. No project in play.

> nuget.exe
> Unhandled Exception: System.NotSupportedException: The requested security protocol is not supported. at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value) at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args) at NuGet.CommandLine.Program.Main(String[] args)

**Comment by DougWest** [comment]
BTW, by 'bare', I mean from a command prompt and cwd is the folder containing the nuget.exe. This is as vanilla as it gets for running nuget.exe. The environment is old and odd, but if you can tell me what settings/dependencies could be missing, I can get this functional.

**Comment by rrelyea** [comment]
What version of NuGet.exe are you trying to run?
If you upgrade to a newer version (see http://nuget.org/downloads), does that work better?

**Comment by DougWest** [comment]
Version 3.4.4.1321 of nuget.exe, the newest general release. Downgrading to 3.2.0 gets a similar error.

**Comment by rrelyea** [comment]
Just noticed that your running this on Windows XP. 
NuGet's call to .NET Framework turns around and calls Windows.
Our belief is that Windows XP doesn't have the appropriate support.
As such, you probably have two options:
1) use NuGet on a supported OS version
2) downgrade to an older version of NuGet.exe (perhaps 2.8.6 would still work)?

**Comment by DougWest** [comment]
Nuget 2.8.6 gives the following error:
C:\packages>nuget.2.8.6.exe
Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by DougWest** [comment]
Nuget 3.2.0 gives this error:
C:\packages>nuget.3.2.0.exe
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

**Comment by bmjames** [comment]
I get the same exception (as the original issue) with NuGet 3.4.4. I am running Windows 7 with PowerShell 2.0 and .Net Framework 4.0.

**Comment by bmjames** [comment]
It turned out I needed a newer version of .NET Framework. 4.6 worked.

But there was a reason I installed 4.0 - the first time I ran NuGet, I got an error message about the .NET version which was oddly specific and asked for 4.0.30319, so I installed that one.
