### ISSUE TITLE
Nuget.Core : How to use v2/v3 api ?

### ISSUE THREAD

**Issue by MscrmTools** [NuGet/Home#3328]
Hi,

I'm using Nuget.Core with repository https://packages.nuget.org/api/v2 to get packages but I just noticed that download count seemed not to be updated anymore.

My guess is I have to use v2/v3 or v3 endpoint but I don't know how to use it with Nuget.Core

Any help?

**Comment by rrelyea** [comment]
Can you move to v3 apis?
there may be a solution with NuGet.Core, but people should be moving to v3.

**Comment by MscrmTools** [comment]
Nuget.Core is easy to use with a strong typed model object. Is there anything similar with v3? BTW, when you talk about v3, is there a .Net library?

**Comment by rrelyea** [comment]
To learn more about the APIs, I might recommend Dave Glick's posts from May/June 2016 here: http://daveaglick.com/tags/nuget

v3 packages have .NET Core or .NET Framework libraries.

**Comment by daveaglick** [comment]
@MscrmTools I'd be happy to answer any questions I can about general usage of the libraries. Just drop me a line over in the comments of the relevant blog post.

**Comment by MscrmTools** [comment]
I'm just reading your blog now and it is very instructive! I will perform some tests and let you know if I need help

Thank you

**Comment by MscrmTools** [comment]
@daveaglick Hi Dave, I didn't have much time to work with new nuget API but I guess you might drive me to the appropriate direction.
I'm using Nuget to distribute some plugins for an application I'm writing. 
With the new API (thanks to your blog posts), I'm able to list packages
Now, I would like to perform installation packages to a specific directory. The rest of the process will be to copy some files from the packages in my application plugins folder.
Do you have any all-made code to install a package from `PackageIdentity`to disk?

**Comment by daveaglick** [comment]
@MscrmTools Sure - check here: https://github.com/Wyamio/Wyam/blob/3dbdb81aabce034616f92ec4eb69e5f5628238e2/src/Wyam.Configuration/NuGet/Package.cs#L105 You'll notice the code calls `NuGetPackageManager.InstallPackageAsync()` and creates a new `PackageIdentity` for the call. The first argument is the key to placing the package in a folder of your choice. In this case, I'm passing a `FolderNuGetProject`. You can control where the package gets installed by creating and passing an appropriate `NuGetProject` to the install call.

**Comment by MscrmTools** [comment]
Thank you very much, I will review it and try to adapt it for my app
