### ISSUE TITLE
NuGet restore from the commandline is significantly slower than VS

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#3330]
It looks like NuGet commandline restore (and DotNET CLI) don't have a fast path to check if restore is actually needed.

VS does this using https://github.com/NuGet/NuGet.Client/blob/bc1f2415971455ac6e9c7da839913c75e369adae/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/BuildIntegratedRestoreUtility.cs#L276.

For our repo this means restore is about 12-times slower for some of our projects since NuGet still does all the work to calculate the entire lock file only to see that it didn't change.

This causes incremental build on our repo to take about 5 minutes to restore and do nothing.  I'm working around it by gating restore with my own fast-path check that is a port of this code, but NuGet should do that so that customers don't need to do the same.

/cc @weshaggard

**Comment by rrelyea** [comment]
The work for fast no-op optimization with nuget.exe is already under way. 
@jainaashish please dupe to existing issue.

**Comment by emgarten** [comment]
@ericstj try the latest nightly build of 3.6.0 from here: https://www.myget.org/F/nugetbuild/api/v2/package/NuGet.CommandLine

There have been some major perf fixes since the last release, it won't be as fast as a noop but it should help cut down your restore time until noop support is added.

**Comment by jainaashish** [comment]
dup of #3087
