### ISSUE TITLE
[Test Failure] The “Newtonsoft.Json” icon is hard to see when the color theme of VS is dark

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3332]
**Repro Steps:**
1. Set the color theme of VS to “dark”.
2. Create anyone project.
3. Right-click the project node and select “Manage NuGet Packages…”.
4. Click “Browse” tab and click package “Newtonsoft.Json”.

**Expected Result:**
The “Newtonsoft.Json” icon can be seen clearly.

**Actual Result:**
The “Newtonsoft.Json” icon is hard to see as below screenshot.

![capture818](https://cloud.githubusercontent.com/assets/20632775/17768442/8e29e48c-6566-11e6-8785-fdb8b47eaa4f.PNG)

**Note:**
1. The issue repro on VS2015 Version 14.0.25425.01 Update3 NuGet 3.4.4.1321/NuGet 3.6.0.1762/NuGet rtm-3.5.0.1737.
2. The issue also repro on VS2015 Dev15 preview 4 (25617.00) NuGet 3.6.0.1762.

**Comment by rrelyea** [comment]
Package authors should design icons that work with a variety of background.
#PackageAuthorGuidelines
