### ISSUE TITLE
Add VS quick launch command for nuget locals

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3333]
Based on the conversation with @harikmenon and @rrelyea. 

Ask : Add a quick launch nuget locals command which will be linked to the VS->Tools->Nuget Package Manager->Clear All NuGet Cache(s)

**Comment by harikmenon** [comment]
Clear All NuGet Caches might be a better term here since we have multiple caches.

**Comment by nkolev92** [comment]
Do we still want to do this?
//cc @rrelyea @mishra14

**Comment by mishra14** [comment]
Closing this as there has been no customer requests.
