### ISSUE TITLE
NuGet Install flags/behaviors

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3336]
NuGet install today will produce random results when a package has multiple TFMs. The behavior is random, and with the advent of netstandard this becomes much more of a standard practice for package authors.
### Suggestion
1. Warn when there are multiple TFMs anywhere in the package graph
2. Allow for passing a -tfm and -rid flags to the package
3. Allow for -ignoreDepenencies flag, to allow downloading just the specific package.
4. [Low Pri] Allow for -All TFMs. This flag will walk all the possible dependency group and restore for them, basically allowing to mirror a full package graph for all possible scenarios.
### Concern

-ExcludeVersion flag will break side by side scenarios, that are required for running multiple TFMs and in some cases even for restoring a single package graph.

**Comment by yishaigalatzer** [comment]
I'm also suggesting to follow this idea in #3447, and make download the official verb, and make install post a deprecated message use download instead.

**Comment by ghuntley** [comment]
INSTALL:
> As a package maintainer (or user) I want a way to download a specific package with a specified version without visiting the website. I want the raw, actual package, installing, unpacking and/repacking should be separate verbs.

UNPACK:
> As a package maintainer I want to unpack the nupkg because I'm going to be monkey patching the nuspec metadata and/or any numerous evil activities one might need to do under the hood.

REPACK:
> As a package maintainer, I want to repack (and validate nuspec validity) because I've monkey patched/modified the contents of a unpacked package.

INSTALL: 
> As a user, I want to "download & install" in a single step operation the specified package and update csproj and whatever. This is the default, hot path that 99.99% users will use.

**Comment by yishaigalatzer** [comment]
From @ghuntley  

> As a package maintainer (or user) I want a way to download a specific package without visiting the website. I want the raw, actual package, installing, unpacking and/repacking should be separate verbs.

The verb will be single download, with various extraction option as exists today.

FYI: You can today download the package directly from nuget.org with a simple http call, the purpose of  this feature it to allow (on top of the above for:
1. Correct access to other 3rd party servers with a single API/call.
2. Authentication for 3rd part servers. 
3. Extraction modes
4. Downloading the dependency graph.

There is a point for adding an extract verb for dealing with nupkg on disk. Worth a separate discussion.

**Comment by yishaigalatzer** [comment]
Also note we want this feature in commandline.xplat AND we want it as an official public API

CC @mlorbetske

**Comment by emgarten** [comment]
Framework parameter support is now covered here: https://github.com/NuGet/Home/issues/5736

Extraction mode would be handy, this would give similar behavior to the Add command, but from remote sources.

**Comment by nkolev92** [comment]
We don't think we'd be getting to this issue anytime soon.
