### ISSUE TITLE
NuGet throws Unable to connect to Remote Server & Version not found

### ISSUE THREAD

**Issue by vphad** [NuGet/Home#3338]
Hi Team, 
When trying NuGet restore sometimes we get this Warning Message followed by Unable to find version,

cmd>NuGet restore My.sln -NoCache 
WARNING: Unable to connect to the remote server
WARNING: Unable to connect to the remote server
Unable to find version '2.0.3930.0' of package 'DocumentFormat.OpenXml'.
Unable to find version '4.157.1212.0' of package 'Sybase.AdoNet4.AseClient'.

The above packages are available in the repository. This is an intermittent issue & can't be reproduce on demand.

**Comment by rrelyea** [comment]
What version of nuget.exe are you using?
What sources are configured? (characterize them...types of servers, location (corporate, internet, etc...), etc...)

**Comment by yurrriq** [comment]
Possibly related: https://dist.nuget.org => `404`

**Comment by rrelyea** [comment]
@vphad - please respond to the questions above.
@yurrriq - unsure why that would be related.

**Comment by yurrriq** [comment]
Turns out my problem was [my hosts file](http://someonewhocares.org/hosts/hosts).

**Comment by vphad** [comment]
My apologies for delay, this is with version 2.8 
Could this be issue with the network ?

**Comment by nkolev92** [comment]
This is a very old issue and I would like to close it. 

Please create another issue if you're still facing this with the latest version of the NuGet Client tools.
