### ISSUE TITLE
Install tab at solution level doesn't show package's version

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3339]
Open package management ui at solution level which has 4-5 projects and multiple packages installed. Move back and forth from install tab to update tab and come back to install tab, now it will not show version details for any of the package. Also if clicked any specific package, it doesn't show version list in details.

Repro with 3.5.0-rc1 and dev branch
Not repro with 3.5.0-beta2

**Comment by rrelyea** [comment]
We'd like to have all 3.5rtm vsix issues addressed by mid next week.

**Comment by jainaashish** [comment]
Merged to 3.5.0-rtm 76f30e9eb91f25890afc724e5785070a37c65f29
