### ISSUE TITLE
Add nuget command to dotnet cli

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3341]

**Comment by rrelyea** [comment]
Please make sure to update docs as appropriate here. (working with @harikmenon and team)

**Comment by drewgillies** [comment]
Sure thing, @rrelyea, @harikmenon. As well as any core docs, this work includes a readme in the cli code in md format (like this: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/README.md) and a man page in groff format for Linux (like this: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/manpages/sdk/dotnet-restore.1).

**Comment by harikmenon** [comment]
Adding @karann-msft 

Our current plan is to do the following and karan will work with the devs on our end owning the specific commands to document this in docs.microsoft.com/dotnet/\* space. In addiiton, we will add a new doc on our end which will point to these docs for these commands. We dont want to mix and match these commands (since the arguments could be a subset) with NuGet.exe CLI reference.

**Comment by karann-msft** [comment]
[New Doc for dotnet nuget push #955](https://github.com/dotnet/core-docs/issues/955)
[New Doc for dotnet nuget delete #956]https://github.com/dotnet/core-docs/issues/956()
[New Doc for dotnet nuget locals #957](https://github.com/dotnet/core-docs/issues/957)
[Update doc for dotnet restore #958](https://github.com/dotnet/core-docs/issues/958)
[Update doc for dotnet pack #959](https://github.com/dotnet/core-docs/issues/959)

**Comment by rrelyea** [comment]
@drewgil - this feature done? if not, what work remains? covered by this issue or another?

**Comment by drewgillies** [comment]
@rrelyea It needs some test coverage (which will be adapted from existing tests), and some general manual testing. I plan to get back to this now that other work is winding up.

**Comment by rrelyea** [comment]
finish in RC.

**Comment by drewgillies** [comment]
As this is functionally complete (though more scenario testing would be good), all that remains is to re-engineer some tests, which is to repurpose existing test infrastructure across to xplat--more of an engineering task than directly associated with this issue, tracked by https://github.com/NuGet/Home/issues/3727. Closing this one.
