### ISSUE TITLE
NuGet packages can't be added to netcoreapp1.0  projects

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [NuGet/Home#3345]
I have a question, I have been playing with creating some .Net Core applications to get a feel for it.

I tried to install a couple of the NuGet packages (Like NuGet.PackageManagement 3.3.0) in my application, but it seems it only supports the full framework and they are not compatible with netcoreapp1.0.

Is there an intention for these packages to support .net core apps? If so, is there a time frame for this?

 

 
## 

Kind Regards

Clare Moore

Consultant 
Development Frameworks | Enterprise Solutions | Systems Integration | Consulting services 

 

Email:Clare.Moore@ThinkAbout.com.au 
Web: ApplicationSpaceFramework.com.au

IMPORTANT NOTICE : The information in this email is confidential and may also be privileged. If you are not the intended recipient, any use or dissemination of the information and any disclosure or copying of this email is unauthorised and strictly prohibited. If you have received this email in error, please promptly inform us by reply email or telephone. You should also delete this email and destroy any hard copies produced. Opinions, conclusions and other information in this message that do not relate to the official

**Comment by rrelyea** [comment]
NuGet 3.5.0 packages will support .NetStandard1.3, which is compatible with Net Core 1.0.
3.5.0 packages are available in RC1 presently.

**Comment by ThinkAboutGitHub** [comment]
So I tried the RC version in my app, but when I restore packages I get this error:

log  : Restore failed in 2011ms.
Errors in C:\Workspace\Genesis\samples.Net Core Nuget Samples\NuGetSamples\src\NuGetSamples\NuGetSamples.xproj
    Package NuGet.PackageManagement 3.5.0-rc1-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package NuGet.PackageManagement 3.5.0-rc1-final supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
