### ISSUE TITLE
Add --clear | -c test coverage to xplat nuget locals function tests

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3347]
Based on the work done on supporting xplat locals done here : https://github.com/NuGet/NuGet.Client/pull/829

Clear test cases do not currently execute on CI machines, since multiple build/test processes on the same machine can interfere with clearing the global packages cache.

As discussed with @joelverhagen , the xplat locals test cases should start new process to execute the test and dummy pre-populated, cache locations should be specified to the test cases, to avoid lock conflicts on the standard cache locations.

**Comment by joelverhagen** [comment]
This work item should be considered at the same time, since it needs the same work of starting a new `dotnet.exe` process inside of a test: https://github.com/NuGet/Home/issues/2410.

**Comment by mishra14** [comment]
Merged : https://github.com/NuGet/NuGet.Client/pull/844
