### ISSUE TITLE
Remove "Restore NuGet Packages" from Solution node context menu when "Allow NuGet to download missing packages" is unchecked

### ISSUE THREAD

**Issue by dpoeschl** [NuGet/Home#3350]
With that option unchecked, the context menu entries are useless at best, but for me they were misleading/confusing.

**Comment by rrelyea** [comment]
Curious, why do you have the capability to download disabled?
Many Roslyn folks turn off restore at build.
Curious to understand your scenario.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. If this is still and issue with the latest NuGet version, please provide additional steps.
