### ISSUE TITLE
NuGet should have a mechanism for getting the path to the lock file in MSBuild

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#3351]
When a build task needs to consume the lock file (project.assets.json), it needs to calculate the path to the lock file in order to read it.  However, calculating the path isn't trivial, and the algorithm may change in the future.

To fix this, we should have some sort common MSBuild $(Property) or `<Target>` that is responsible for calculating the path to the lock file.  That way all consuming tasks can use this property/target instead of having to calculate the path themselves.

/cc @emgarten @rrelyea @yishaigalatzer

**Comment by yishaigalatzer** [comment]
I see it differently, the current design should eliminate all readers of the assets file, and there should be a single task reading it and translating it to msbuild language.

**Comment by eerhardt** [comment]
I don't agree because "msbuild language" doesn't represent graphs of objects as well as .NET does.

It is orders of magnitudes easier to consume a .NET object model as a graph than it is a bunch of string-string metadata items.  You also lose all sorts of type safety, intellisense, etc. when consuming "msbuild language".

Thus there are certain classes of tasks that are better written consuming the assets file using the object model https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.ProjectModel/LockFile.

**Comment by yishaigalatzer** [comment]
Let me re-iterate/clarify the stance, there will be a single point in msbuild that can load a lock file, there will be no guarantees to the shape of the lock file or the location other than that one entry point can load it.

**Comment by livarcocc** [comment]
@yishaigalatzer the CLI reads the lock file to find the tools available for the project when resolving tools commands. We will then use the tool's lock file to generate its deps file. So, we use it twice.

**Comment by yishaigalatzer** [comment]
We should really get rid of that and go through a single channel in the msbuild task if possible and not produce multiple code paths that understand the lock file. IMHO the lock file is an implementation detail of NuGet and not something we should have partners take a dependency on. 

By doing so we will be able to raise our confidence when making changes (even if additive) to the file.

I suggest getting in a room with David Kean and us if you still think this is not doable.

**Comment by brthor** [comment]
Assuming we keep the tool resolution and execution in c#, we need to be able to consume something that describes the dependency graph of the tool so we can find the appropriate assembly to execute.  

Today, that is the lock file through the LockFile model. 
Is this task becoming the thing we should consume to find the dependency graph, and other lock file information (tool groups for example)?

**Comment by yishaigalatzer** [comment]
I'm saying we should strive for one single model, so yes that should be the goal

**Comment by rrelyea** [comment]
@emgarten  - we'll move to the right msbuild property name in rc. currently we look at $(intermediateobjectpath) I believe.

**Comment by emgarten** [comment]
The path to project.assets.json is now written out under ``ProjectAssetsFile`` to the ``.props`` file.
