### ISSUE TITLE
Package Manager Console no longer working: The term 'Set-Location' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by WitnessMee** [NuGet/Home#3352]
Hi,

This issue might be related to "https://github.com/NuGet/Home/issues/974"
I have already executed all steps there but the Package Manager Console is still not working.
Fails both in Visual Studio 2013 and Visual Studio 2015. I have Windows 10 64-bit installed

In **Package Manager Console** I get this error:
"The term 'Set-Location' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

When I do an update of a package in **Nuget Package Manager** I get this:
"Failed to initialize the PowerShell host. If your PowerShell execution policy setting is set to AllSigned, open the Package Manager Console to initialize the host first."

**Steps that do not fix the problem:**
1. Updating Nuget Package Manager. I already have the latest version (VS2013: 2.12.0.817, VS2015:  3.4.4.1321)
2. Uninstalling and reinstalling Nuget Package Manager
3. Changing the execution policy in Powershell. When it still worked it was RemoteSigned. Changed it to Unrestricted but this had no impact.
4. Repairing Visual Studio

**Steps that temporarily fixed the problem:**
1. Updating the **devenv.config** file in _C:\Users<UserName>\AppData\Local\Microsoft\VisualStudio\xx.x_ and adding this:
   `<dependentAssembly>
       <assemblyIdentity name="System.Management.Automation" publicKeyToken="31bf3856ad364e35" />
       <publisherPolicy apply="no" />
   </dependentAssembly>
   <dependentAssembly>
     <assemblyIdentity name="Microsoft.PowerShell.Commands.Utility" publicKeyToken="31bf3856ad364e35" />
     <publisherPolicy apply="no" />
   </dependentAssembly>
   <dependentAssembly>
     <assemblyIdentity name="Microsoft.PowerShell.ConsoleHost" publicKeyToken="31bf3856ad364e35" />
     <publisherPolicy apply="no" />
   </dependentAssembly>
   <dependentAssembly>
     <assemblyIdentity name="Microsoft.PowerShell.Commands.Management" publicKeyToken="31bf3856ad364e35" />
     <publisherPolicy apply="no" />
   </dependentAssembly>
   <dependentAssembly>
     <assemblyIdentity name="Microsoft.PowerShell.Security" publicKeyToken="31bf3856ad364e35" />
     <publisherPolicy apply="no" />
   </dependentAssembly>
   <dependentAssembly>
     <assemblyIdentity name="Microsoft.PowerShell.Commands.Diagnostics" publicKeyToken="31bf3856ad364e35" />
     <publisherPolicy apply="no" />
   </dependentAssembly>`
   Both Package Manager Console and Nuget Package Manager worked fine after this but then suddenly stopped working again
2. Turn Windows features on or off. I disabled _Windows Powershell 2.0_, rebooted, enabled it again and both Package Manager Console and Nuget Package Manager worked fine after this but then suddenly stopped working again.

I tried about everything that is suggested here: [StackOverflow](http://stackoverflow.com/questions/23353951/cant-install-nuget-package-because-of-failed-to-initialize-the-powershell-host) but nothing works.
Currently I'm the only developer in my team that has this problem. I'm also the only one that has Windows 10 installed so I have a feeling it might have something todo with that.

**Comment by rrelyea** [comment]
Do you 1511 or 1607 builds of Windows 10 installed?
I believe if you have 1511, you need to have been updated to .64 or later of the builds...otherwise you run into a powershell bug.

**Comment by WitnessMee** [comment]
Hi Rob,

I had version 1511 of Windows 10 installed.
I updated to version 1607 (using this [link](https://support.microsoft.com/en-us/help/12387/windows-10-update-history))
Everything is working again!

**Comment by MuhammadTausif** [comment]
Facing the same issue, 👎

**Comment by MuhammadTausif** [comment]
I was facing the same issue,
I restart the VS, to get out of this issue.
