### ISSUE TITLE
Remove SemVer 2.0.0 block from pack

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3356]
Pack blocks SemVer 2.0.0 versions in packages. This should be removed.

**Comment by emgarten** [comment]
Related to https://github.com/NuGet/Home/issues/1359

**Comment by emgarten** [comment]
This change is needed for 3.5.0 RTM.  Now that SemVer 2.0.0 is supported in the client it should be possible to create SemVer 2.0.0 packages.

**Comment by rrelyea** [comment]
Note...spec was to warn when creating this package with a semver2.0 id.
When validating, please confirm the warning is being produced.

**Comment by kzu** [comment]
Is there a feed where we can get packages from CI for upcoming releases? (or even from dev branch?)

I desperately need a package containing this fix :)

**Comment by kzu** [comment]
Found it https://dotnet.myget.org/gallery/nuget-build :)

**Comment by Jaykul** [comment]
@kzu what build did you find worked? I tried the NuGet.Commandline package 3.6.0-rc-1927
and it still seems blocked?

**Comment by emgarten** [comment]
@Jaykul what error did you get? It should be unblocked in 3.6.0-rc

You can find the latest 3.5.0 build which is close to RTM here: https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829

**Comment by Jaykul** [comment]
Thanks for your patience, when I looked through there, I missed the fact that the "3.5.0-rtm" files were hiding down under the betas 😊
