### ISSUE TITLE
Document precedence rules for package frameworks

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#3361]
_From @harikmenon on July 18, 2016 17:4_

We need to explicitly call out our resolution rules and possibly link to joels site.

_Copied from original issue: NuGet/NuGetDocs#495_

**Comment by kraigb** [comment]
What information do you have on this that I can work from?

**Comment by kraigb** [comment]
@joelverhagen Do you have suitable information?

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #718](https://github.com/NuGet/docs.microsoft.com-nuget/issues/718) via [**ZenHub**](https://www.zenhub.com/)
