### ISSUE TITLE
Doc Request: Project.lock.json

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#3364]
_From @harikmenon on June 10, 2016 13:41_

Some examples of the content we would like to see
1.  If project.json contains \* and you want repeatable builds without checking in the lock file, you must lock down the sources used for restore so that you control the content.  This ensures that the \* will always pick the same version.
2.  If project.json contains \* and you want repeatable builds while checking in the lock file you can do so, but devs must be aware of this and know that whenever they change dependencies they need to update the lock file and check it in.
3.  If project.json does not contain *s then you should have repeatable builds so long as you have an exact-match to the versions you reference on one of your package sources and those packages remain immutable.

_Copied from original issue: NuGet/NuGetDocs#470_

**Comment by kraigb** [comment]
I'm not clear on what the * means here, or the surrounding context for these points. It seems that we're talking about using source control for one thing, but what about "repeatable builds"? Are we talking locally or on a build server? More context please.

**Comment by PatoBeltran** [comment]
@karann-msft can this issue be closed?

**Comment by nkolev92** [comment]
This is redundant right now, as the project.json.lock file is dead. 

We're working towards a true lock file to enable repeatable builds. 

I think it's safe to close.
