### ISSUE TITLE
NuGet packages listing failed in private repository

### ISSUE THREAD

**Issue by mathikp** [NuGet/Home#3367]
We are using NuGet.Server in private repository. If we add .NET Core packages in the repository, the packages listing failed and shows error if we select the respective package source. I have sent the fiddler trace of the issue to the mail id support@nuget.org by mentioned the issue id in the subject of the mail. Please look into it and help me asap. Thanks.

**Comment by yishaigalatzer** [comment]
@maartenba I don't believe we have support for this released yet. Can you please take a look? (and move the issue over to the right place)

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#3210
