### ISSUE TITLE
[Test Failure] The first selected version can’t be remembered in Package Manager for Solution Window

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3371]
**Repro Steps:**
1.  New a project [such as C# Blank Application (Universal Windows)].
2.  Open ‘Manage NuGet Packages for Solution’ and click ‘Browse’ tab.
3.  Click a package and select a **version (not the latest)** in ‘Version’ dropdown list.
4.  Select a project you want to install the package to.

**Expected Result:**
The selected version can be remembered in step3.

**Actual Result:**
The selected version can’t be remembered in step3, you must select the version again.
![can trememberversion](https://cloud.githubusercontent.com/assets/20632625/17963469/507f8844-6ae8-11e6-8c1e-f1b9a1dccc1b.png)

**Note:**
1. It happened on Dev14 U3+NuGet 3.6.0-Beta1-1775.
2. It doesn’t repro on NuGet 3.4.4.
3. It repro on Dev14 U3+NuGet 3.5.0-rtm-1777.

**Comment by rrelyea** [comment]
Sounds like 3.5.0-rc1 regression from 3.4.4 on vs2015 update3. Please investigate and analyze.
