### ISSUE TITLE
Assembly Binding Redirects Do Not Work as Expected in Project.json only

### ISSUE THREAD

**Issue by Mike-E-angelo** [NuGet/Home#3372]
3.0 is super awesome and amazing.  It is very impressive and vastly improves the user experience in Visual Studio reference management.  However, the one (noticeable) feature that seems to have been overlooked is that of assembly binding redirects.

As an example, I recently had an update arrive for `Moq` 4.5.21.0 (from 4.5.16.0).  The binding redirect looked like this in my unit testing [`App.config`](https://github.com/DevelopersWin/VoteReporter/blob/105a976a813c686bc081fdb87c643600f7d12314/Framework/DragonSpark.Testing/App.config#L18-L21):

```
<dependentAssembly>
    <assemblyIdentity name="Moq" publicKeyToken="69f491c39445e920" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.5.16.0" newVersion="4.5.16.0" />
</dependentAssembly>
```

After installing the latest `Moq` I would expect it to look like this:

```
<dependentAssembly>
    <assemblyIdentity name="Moq" publicKeyToken="69f491c39445e920" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.5.21.0" newVersion="4.5.21.0" />
</dependentAssembly>
```

However, this did not occur, and I had to do it manually.  In 2.0 this worked without intervention.  It would be great to have this return in 3.0.  Thank you for any consideration!

**Comment by rrelyea** [comment]
Let's discuss in tomorrow's meeting.

**Comment by nkolev92** [comment]
Binding redirects is not a concept that's handled by NuGet in project.json and PackageReference worlds.
It's now handled by the VS project-system.
