### ISSUE TITLE
Can't exclude "packages" folder from TFS pending changes list

### ISSUE THREAD

**Issue by SetTrend** [NuGet/Home#3375]
Using Visual Studio Enterprise 2015 Update 3 I can't get the solution's `\packages` folder excluded from TFS source control.

I have tried all the suggested workarounds, but to no avail:

![can t exclude packages folder](https://cloud.githubusercontent.com/assets/9283914/17993021/af488790-6b4c-11e6-8804-df5cb60108c4.gif)

---

Can we get an option in Nuget Options (Tools > Options > Nuget Package Manager) or in VS Solution file options (via property pages) to have the `\packages` folder be excluded from source control?

This issue is now going on for years. It would be great if you found a once and for all, final, working solution - without requiring `nuget.config` hacks.

**Comment by nkolev92** [comment]
In the Visual Studio 2015, NuGet use some custom logic to help manage TFS.
In Visual Studio 2017, we don't do any of that custom work so the experience is a little bit different. 
All the TFS logic is on TFS side.
