### ISSUE TITLE
[Test Failure] The installed package ‘bootstrap 3.3.6.1’ can’t be find in the ‘Version’ dropdown list

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3376]
**Repro Steps:**
1. Create a new C#->WebApplication->Web Forms project.
2. Open ‘Packages Manager Console’ and type ‘update-package’.
3. Right-click the project and select ‘Manage NuGet Packages…’.
4. Go to ‘Updates’ tab and update package ‘AspNet.ScriptManager.jQuery’.
5. Click the package ‘bootstrap’ and select the dropdown list of ‘Version’.

**Expected Result:**
The installed package ‘bootstrap 3.3.6.1’ can be find in the ‘Version’ dropdown list.

**Actual Result:**
The installed package ‘bootstrap 3.3.6.1’ can’t be find in the ‘Version’ dropdown list as below screenshot.

![untitled33333333](https://cloud.githubusercontent.com/assets/20632775/17999667/bcc0857a-6bac-11e6-8308-bc523b62de38.png)

**Note:**
1.  The issue repro on VS2015 Version 14.0.25425.01 Update3 NuGet 3.4.4.1321/NuGet 3.6.0-beta1-1782/NuGet 3.5.0-rtm-1779.
2.  The issue also repro on VS2015 Dev15 preview 4 (25617.00) NuGet 3.6.0-beta1-1782.
3.  The issue doesn’t happen before step4 because the package ‘bootstrap’ had been update from 3.3.6 to 3.3.6.1 after step4.
4.  The issue also repro in ‘Browse’ tab but doesn’t repro in ‘Installed’ tab.

**Comment by emgarten** [comment]
This package may have been unlisted, I don't see it on https://www.nuget.org/packages/bootstrap/ either.

**Comment by rrelyea** [comment]
This package is unlisted, and therefore shouldn't show up in that dropdown.
