### ISSUE TITLE
Invalid argument to dotnet restore throws a bogus error message

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3377]
The error message in the following scenario does not provide any help or insight into the problem.

Steps - 
1. Run dotnet restore RandomArgument
2. Observe error

The error I saw was - 

```
E:\cli [rel/1.0.0 ≡]> E:\cli\artifacts\win10-x64\stage2\dotnet.exe restore RandomArgument
error: RandomArgument
```

**Comment by rrelyea** [comment]
discussed in triage.
dotnet restore -a 45 -b 56 -c tom Fred -packagesdirectory c:\temp
Will pass through props like this to msbuild in the new world:
msbuild /t:restore -a 45 -b 56 -c tom Fred /p:restorepackagespath=c:\temp
(those params we know about, we'll convert, otherwise, we blindly pass).
