### ISSUE TITLE
Error: Illegal characters in path

### ISSUE THREAD

**Issue by OryanHassidim** [NuGet/Home#3381]
I can't install NuGet packages and the error in downloading and installing is:

An error occurred while writing file 'D:\turhh\Documents\Visual Studio projects\Room arrangement\Room_Arrangement\packages.config': Failed to write packages.config as XML file 'D:\turhh\Documents\Visual Studio projects\לישיבה\Room arrangement\Room_Arrangement\packages.config'. Error: 'Illegal characters in path.'.   

It is on my laptop and desktop on VS15 and I get this error all times!...

What can I do?

**Comment by rrelyea** [comment]
What version of VS15 are you using?
If you aren't using Preview4, try that.

If you are using Preview 4, how can we reproduce the problem? (please give us detailed repro steps)

**Comment by rrelyea** [comment]
@OryanHassidim  - ping

**Comment by OryanHassidim** [comment]
Is it free? from where?

**Comment by rrelyea** [comment]
VS "15" Preview 4 can be installed from: https://www.visualstudio.com/en-us/news/releasenotes/vs15-relnotes

**Comment by OryanHassidim** [comment]
The problem is NuGet doesn't works with different cultures.... 

The fix of the problem:
https://github.com/NuGet/Home/issues/5976
