### ISSUE TITLE
Add SemVer 2.0.0 support to NuGet.Core

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3383]
NuGet.SemanticVersion in NuGet.Core.dll needs to support SemVer 2.0.0 to enable NuGet.Server and other projects build on the NuGet.Core package to support packages created with NuGet.exe 3.5.0.

**Comment by rrelyea** [comment]
Let's target NuGet.Core.dll that ships after 3.5.0-rtm. (2.14?)

**Comment by emgarten** [comment]
Checked into 2.14 with NuGet/NuGet2@ed693fca1718a46f70da3c645d666240d07968ad
