### ISSUE TITLE
A better "give feedback" link

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#3384]
For starters https://docspreview.nuget.org/ is awesome. good work to all involved

Next a minor feature request 

so on a given page u have a give feedback link to https://github.com/Nuget/Home/issues 

But u can use the Github new issue url syntax to give a better experience. eg https://github.com/Nuget/Home/issues/new?title=Feedback%3A+PAGETITLE&body=PAGEURL

or whatever you want the title and body to be

**Comment by SimonCropp** [comment]
thanks to @shiftkey for providing the new issue url syntax

**Comment by harikmenon** [comment]
- Karan @karann-msft . Thanks for the feedbacK @SimonCropp!

**Comment by karann-msft** [comment]
@SimonCropp  appreciate the feedback. We are moving to docs.microsoft.com very soon. Hence, closing the issue.
