### ISSUE TITLE
Support contentFiles in regular .NET (.csproj)

### ISSUE THREAD

**Issue by davidmatson** [NuGet/Home#3386]
The newer contentFiles has some really nice properties - immutable content, allows specifying build action and copy to output directory.

I'm using this heavily for normal .NET assemblies and currently consumers have to do painful work around remembering to set CopyToOutputDirectory/ContentType manually. It would be really nice to have the same contentFiles feature that today only works with project.json-based consumers also work for full .NET/.csproj consumers.

**Comment by emgarten** [comment]
You can work around this for packages.config based projects by adding an install.ps1 file that modifies content added from the content folder to include additional properties.

**Comment by davidmatson** [comment]
Thanks! - is there a sample of how to set Copy To Output Directory, for example?

**Comment by rrelyea** [comment]
This is how I did this in a previous life: http://stackoverflow.com/questions/8474253/nuget-how-can-i-change-property-of-files-with-install-ps1-file

Otherwise, closing the issue, we aren't going to backport that feature to packages.config, but people can choose to migrate to "uwp-style project.json" for packages.config projects.

Thanks, Rob

**Comment by davidmatson** [comment]
Thanks, Rob.

For "uwp-style project.json", is there a non-packages.config approach that works for full .NET projects? (I thought project.json was only for .NET Core and had heard something about UWP, but I'm not familiar with the details.) Does this option also have full support in the VS UI?

(Or is there a good link to learn about which options are supported where?)

Thanks,

David

**Comment by davidmatson** [comment]
I tried looking here:
http://docs.nuget.org/ndocs/create-packages/project.json-and-uwp

But it says:
"Support for content inclusion in the project is planned for a later release"

Is there other documentation somewhere that explains how to migrate to "uwp-style project.json" for packages.config projects as suggested to get this feature?

Thanks,

David

**Comment by karann-msft** [comment]
Here you go:
https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

**Comment by jpierson** [comment]
Is there any clarification on how issues like this apply to the new SDK csproj project files now that _project.json_ is no longer a thing? Most of the NuGet documentation seems to still explicitly mention project.json everywhere but it's difficult to understand if the points still carry over to the new csproj format as well.
