### ISSUE TITLE
NuGet during restore doesn't respect the same compat shims as MSBuild when running in VS 15 command prompt

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#3387]
We're running into restore issues under VS 15 with the new installer.

Basically, we're importing MIcrosoft.VS.SDK.targets via:

``` XML
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\VSSDK\Microsoft.VsSDK.targets"/>
```

Under MSBuild.exe, this targets file will be looked for in two different paths:

_C:\Program Files (x86)\Microsoft Visual Studio\VS15Preview\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK_

-and-

_C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK (for compat)_

It exists only in the former. Under NuGet.exe when running msbuild, this targets is looked under only in the compat path:

_C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK_

This causes our build to fail in the new installer environment. NuGet should be respecting the same compat shims as MSBuild.

See: https://github.com/Microsoft/msbuild/issues/954

**Comment by radical** [comment]
`nuget.exe.config` would need to add the search paths like (taken from https://github.com/Microsoft/msbuild/blob/xplat/src/XMakeCommandLine/app.config )

```
<configuration>
    <configSections>
      <section name="msbuildToolsets" type="Microsoft.Build.Evaluation.ToolsetConfigurationSection, Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
    </configSections>
...
<msbuildToolsets default="15.0">
      <toolset toolsVersion="15.0">
        <projectImportSearchPaths>
          <searchPaths os="windows">
            <property name="MSBuildExtensionsPath" value="$(MSBuildProgramFiles32)\MSBuild"/>
            <property name="MSBuildExtensionsPath32" value="$(MSBuildProgramFiles32)\MSBuild"/>
            <property name="MSBuildExtensionsPath64" value="$(MSBuildProgramFiles32)\MSBuild"/>
          </searchPaths>
        </projectImportSearchPaths>
      </toolset>
</msbuildToolsets>

...
</configuration>
```

The above sets the fallback search paths used for importing projects from `$(MSBuildExtensionsPath)`. Any app hosting `msbuild` needs this to support the same search paths.

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@radical The toolset which includes search paths is only loaded from `msbuild.exe.config`, so no need to add anything to `nuget.exe.config`.

**Comment by radical** [comment]
Oh, I misunderstood then. I thought the program was hosting msbuild and so not running msbuild.exe .

**Comment by davkean** [comment]
This could be because NuGet is picking up the wrong/different version of MSBuild - and not the willow version. @Sarabeth-Jaffe-Microsoft Is there an environment variable to figure out what the "current" msbuild is?

**Comment by Sarabeth-Jaffe-Microsoft** [comment]
@davkean There's no environment variable except for `VSINSTALLDIR` if you're in a VS command prompt. Willow provides a COM API that could be used to locate Willow and thus MSBuild.

**Comment by rrelyea** [comment]
We are working to incorporate that COM API now. Assigning this bug to @drewgil, as he is doing that work.

**Comment by rrelyea** [comment]
@nkolev92 - With Drew's work finished to properly find msbuild.exe in VS 2017 installs, this should be fixed now. Can you please confirm?

**Comment by nkolev92** [comment]
Looks good.

Tested with: 
NuGet version: 4.0.0-RC3-2162
OS version: Windows 10 RS1_Release 14393.693
