### ISSUE TITLE
.NET assembly reference missing after install, frameworkAssemblies tag without effect

### ISSUE THREAD

**Issue by JochenHWezel** [NuGet/Home#3388]
VS2015 with NuGet 3.5.0.1484 shall import package CompuMaster.Imaging which uses following reference spec:

``` xml
        <frameworkAssemblies>
            <frameworkAssembly assemblyName="System.Drawing" /> 
        </frameworkAssemblies>
```

(Since the reference is required regardless to the target framework, I haven't added a target framework to the spec file of CompuMaster.Imaging.)

Unfortunately, after installing this package into the project, the reference from the project to System.Drawing.dll is still missing :-(

**Comment by joelverhagen** [comment]
Which type of project are you installing this package to? Could you provide some minimal steps to reproduce this issue?

**Comment by rrelyea** [comment]
@JochenHWezel  - what joel said, plus, what version of NuGet/VS supported this correctly? Does NuGet 3.4.4 which comes with Update 3 support this correctly?
Also, it would help if you could tell us if NuGet.Tools.vsix 3.5.0-rc1 from http://nuget.org/downloads fixes things. Thanks!

**Comment by jochenwezel** [comment]
Here is a step-by-step-guide for reproduction of the issue:
1. Create new empty library project (here with VB.NET in VS 2015, with NuGet.Tools.vsix 3.5.0-rc1 installed)
   ![image](https://cloud.githubusercontent.com/assets/3033827/18272361/bd332e84-7437-11e6-9fbd-53b03ffd8f8f.png)
   ![image](https://cloud.githubusercontent.com/assets/3033827/18272412/f3f99d54-7437-11e6-9ab2-86868ecbab3b.png)
2. Add NuGet package of CompuMaster.Imaging
   ![image](https://cloud.githubusercontent.com/assets/3033827/18272440/18293aae-7438-11e6-925e-c674deec918d.png)

Finally, CompuMaster.Imaging is referenced in the project, but System.Drawing is still missing:
![image](https://cloud.githubusercontent.com/assets/3033827/18272516/8adee95e-7438-11e6-876d-1215a4b2746d.png)

This is the CompuMaster.Imaging.nuspec:

``` xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata>
    <!-- [...] //-->
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
        <description>JIT resizing of images, EXIF tools and more</description>
        <releaseNotes/>
        <copyright>2005-2016 CompuMaster GmbH</copyright>
        <tags>Picture Frame Shadow Imaging CompuMaster camm</tags>
        <frameworkAssemblies>
            <frameworkAssembly assemblyName="System.Drawing" /> 
        </frameworkAssemblies>
  </metadata>
</package>
```

**Comment by yishaigalatzer** [comment]
@jochenwezel the packages on nuget.org do not contain the `frameworkassemblies` tag. Is that intentional?

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>CompuMaster.Imaging</id>
    <version>2016.8.26.100</version>
    <title>CompuMaster.Imaging</title>
    <authors>CompuMaster GmbH</authors>
    <owners>CompuMaster GmbH</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Description</description>
    <copyright>2004,2005,2006,2010,2015,2016 CompuMaster GmbH</copyright>
    <dependencies />
  </metadata>
</package>
```

**Comment by jochenwezel** [comment]
@yishaigalatzer you're absolutely right! Thanks for this valueable hint :-)

I created my package with:

``` Powershell
NuGet.exe pack "D:\GitHub-OpenSource\CompuMaster.Imaging\CompuMaster.Imaging\CompuMaster.Imaging.VS2015.vbproj" -Build -OutputDirectory "D:\GitHub-OpenSource\CompuMaster.Imaging\CompuMaster.Imaging\New-NuGetPackages"
```

The directory of CompuMaster.Imaging.VS2015.vbproj also contained my CompuMaster.Imaging.nuspec file.

Unfortunately, The packaging didn't use my CompuMaster.Imaging.nuspec file and that's why it created a new .nuspec file from scratch from project just-in-time.

After renaming my CompuMaster.Imaging.nuspec to CompuMaster.Imaging.VS2015.nuspec, nuget immediately packed the project with the information of my prepared .nuspec

**Comment by jochenwezel** [comment]
After republishing the package, everything works as expected :-)

The question is: is the not-using of CompuMaster.Imaging.nuspec (the .nuspec file which doesn't match the name of the .vbproj file) a bug or a feature?
My expectation was that if the project directory contains 1 .nuspec file, it automatically takes that...

**Comment by yishaigalatzer** [comment]
It is the design. Going forward we are building a complete pack feature that will include all the metadata directly in the project file (and with UI support) and not require a nuspec partly to alleviate this kind of pain.
