### ISSUE TITLE
Caching of version lists leads to not seeing a new package version for 30 minutes

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3389]
Talked to @pranavkm offline about this one.

Currently, we cache the following resources for 30 minutes in the HTTP cache (`v3-cache` directory):
1. Flat container index.json, in `HttpFileSystemBasedFindPackageByIdResource`
2. V2 `FindPackagesById()` OData endpoint, in `RemoteV2FindPackageByIdResource`

Note that `RemoteV3FindPackageByIdResource` (unused if the V3 server has a flat container resource) does not cache version lists.

The current workaround is using `-NoCache` (although `-NoCache` has its own problems). We could be clever with etags (if supported by the source) or even by not caching version lists and only caching .nupkgs.

Another interesting angle here is that since HTTP cache entries have there own cache timeout, it's possible for version lists of transitive dependencies to cache timeout before direct dependencies. Suppose A 1.0 depends on B 1.0. Then A 2.0 and B 2.0 are published to the source. If the cache timeout of the B version list is _after_ the A version list, you could mysteriously (to the user) not be able to find A 2.0's B dependency.

**Comment by pranavkm** [comment]
FYI @Eilon

**Comment by joelverhagen** [comment]
Another idea is to somehow be able to mark a source with `-NoCache`. This problem mainly happens on CI feeds when a lot of inter-related packages are frequently being pushed.

**Comment by rrelyea** [comment]
Could consider not caching lists. We added this list caching to reduce hit on MyGet and other servers.
Good ideas to consider in future.

**Comment by lbargaoanu** [comment]
I'm interested in solving this. I guess there are many options. I would mention two. Not caching version lists and having a separate MaxAge setting for version lists. What would work for you?

**Comment by pranavkm** [comment]
@lbargaoanu there's already a max age of 30 minutes. The problem is invalidation of caches for dependent package versions when any one package's version list updates. IMO, a simple fix would be to invalidate all cached version list from a feed when any of them is updated. Removing the caching entirely might be problematic especially if you're working with floating versions - every build with restore would now result in multiple server calls which would be less than ideal.

**Comment by lbargaoanu** [comment]
Yes, but the problem is the setting applies both to version lists and packages. How are the version lists supposed to be updated? That doesn't happen now, right?

**Comment by lbargaoanu** [comment]
A separate setting for version lists seems [simple enough](https://github.com/lbargaoanu/NuGet.Client/commit/d05341acbc1d762fcbe3dedddb76884c372a37cc).  I guess invalidating the cache by hand can be done outside NuGet. Find the folders for sources that have versions for that package and then delete all the version lists from those folders.

**Comment by nkolev92** [comment]
Dup of #3116
