### ISSUE TITLE
I can not download caffe 3rd package when compile caffe using VS2013 Nuget.

### ISSUE THREAD

**Issue by BaiYu0120** [NuGet/Home#3393]
Compile the caffe cnns framework needs to download 3rd package. When doing compile, the error is operation timed out. And It shows as below when I open the NuGet feed v2 (VS 2013 and earlier / NuGet 2.x): https://www.nuget.org/api/v2.

```
<service xml:base="https://www.nuget.org/api/v2">
<workspace>
<atom:title type="text">Default</atom:title>
<collection href="Packages"><atom:title type="text">Packages
</atom:title></collection>
</workspace>
</service>
```

**Comment by BaiYu0120** [comment]
<service xml:base="https://www.nuget.org/api/v2"><workspace><atom:title type="text">Default</atom:title><collection href="Packages"><atom:title type="text">Packages</atom:title></collection></workspace></service>

**Comment by rrelyea** [comment]
Please give us more detailed repro steps and re-open this issue when you do.
