### ISSUE TITLE
nuget & artifactory

### ISSUE THREAD

**Issue by jopdam** [NuGet/Home#3396]
Goodmorning everyone (it is morning here).

I am hoping you guys and/or ladies can help me with an issue I am facing.
I am trying to setup nuget client to use an internally hosted nuget feed on a private artifactory repository (Specific users are allowed to read and/or write)

We got an api key (based on a username:password combination) from the internal artifactory team.

We pushed a nuget package, no problems. See request and response.
###### 

PUT https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/ HTTP/1.1
X-NuGet-ApiKey: &lt;&lt;USERNAME&gt;&gt;:&lt;&lt;PASSWORD&gt;&gt;
user-agent: NuGet Command Line/3.4.4.1321 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Content-Type: multipart/form-data; boundary="fa51ab17-a192-4650-ad8d-dded8f77d839"
Host: &lt;&lt;ROOTURL&gt;&gt;
Content-Length: 1603715
Expect: 100-continue
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

HTTP/1.1 201 Created
Date: Thu, 01 Sep 2016 03:56:45 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: Artifactory/4.11.1
X-Artifactory-Id: 0000000000000000:-0000000000000000000:-8000

Successfully published NuPkg to: Newtonsoft.Json.9.0.1.nupkg
###### 

Now when I try to get the nuget package it does not find anything (see missing X-NuGet-ApiKey header). See request and response.
###### 

GET https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/FindPackagesById()?id='newtonsoft.json' HTTP/1.1
Accept: application/atom+xml, application/xml
user-agent: NuGet Command Line/3.4.4.1321 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Host: &lt;&lt;ROOTURL&gt;&gt;
Accept-Encoding: gzip, deflate

HTTP/1.1 200 OK
Date: Thu, 01 Sep 2016 03:57:53 GMT
Content-Type: application/atom+xml;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: Artifactory/4.11.1
X-Artifactory-Id: 0000000000000000:-0000000000000000000:-8000
DataServiceVersion: 2.0

&lt;?xml version='1.0' encoding='UTF-8'?&gt;
&lt;feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom" xml:base="https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/"&gt;
  &lt;title type="text"&gt;&lt;/title&gt;
  &lt;id&gt;http://schemas.datacontract.org/2004/07/&lt;/id&gt;
  &lt;updated&gt;2016-09-01T03:57:53Z&lt;/updated&gt;
  &lt;link rel="self" title="FindPackagesById" href="FindPackagesById"/&gt;
&lt;/feed&gt;
###### 

When I add the X-NuGet-ApiKey header (using fiddler), the response contains information about the package. See request and response.
###### 

GET https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/FindPackagesById()?id='newtonsoft.json' HTTP/1.1
Accept: application/atom+xml, application/xml
user-agent: NuGet Command Line/3.4.4.1321 (Microsoft Windows NT 6.1.7601 Service Pack 1)
Host: &lt;&lt;ROOTURL&gt;&gt;
Accept-Encoding: gzip, deflate
X-NuGet-ApiKey: &lt;&lt;USERNAME&gt;&gt;:&lt;&lt;PASSWORD&gt;&gt;

HTTP/1.1 200 OK
Date: Thu, 01 Sep 2016 03:58:58 GMT
Content-Type: application/atom+xml;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: Artifactory/4.11.1
X-Artifactory-Id: 0000000000000000:-0000000000000000000:-8000
DataServiceVersion: 2.0

&lt;?xml version='1.0' encoding='UTF-8'?&gt;
&lt;feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom" xml:base="https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/"&gt;
  &lt;title type="text"&gt;&lt;/title&gt;
  &lt;id&gt;http://schemas.datacontract.org/2004/07/&lt;/id&gt;
  &lt;updated&gt;2016-09-01T03:58:58Z&lt;/updated&gt;
  &lt;link rel="self" title="FindPackagesById" href="FindPackagesById"/&gt;
  &lt;entry&gt;
    &lt;id&gt;https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/Packages(Id='Newtonsoft.Json',Version='9.0.1')&lt;/id&gt;
    &lt;title type="text"&gt;Newtonsoft.Json&lt;/title&gt;
    &lt;summary type="text"&gt;Json.NET is a popular high-performance JSON framework for .NET&lt;/summary&gt;
    &lt;updated&gt;2016-09-01T05:56:45Z&lt;/updated&gt;
    &lt;author&gt;
      &lt;name&gt;James Newton-King&lt;/name&gt;
    &lt;/author&gt;
    &lt;link rel="edit" title="V2FeedPackage" href="Packages(Id='Newtonsoft.Json',Version='9.0.1')"/&gt;
    &lt;link rel="self" title="V2FeedPackage" href="Packages(Id='Newtonsoft.Json',Version='9.0.1')"/&gt;
    &lt;category term="NuGetGallery.OData.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/&gt;
    &lt;content type="application/zip" src="https://&lt;&lt;ROOTURL&gt;&gt;/artifactory/api/nuget/releases_nuget_TFS_Acceptance/Download/Newtonsoft.Json/9.0.1"/&gt;
    &lt;m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices"&gt;
      &lt;d:lastUpdated&gt;2016-09-01T05:56:45&lt;/d:lastUpdated&gt;
      &lt;d:Version&gt;9.0.1&lt;/d:Version&gt;
      &lt;d:Created m:type="Edm.DateTime"&gt;2016-09-01T05:56:45&lt;/d:Created&gt;
      &lt;d:Dependencies&gt;System.IO:4.1.0:.NETStandard1.0|System.Runtime:4.1.0:.NETStandard1.0|System.Threading.Tasks:4.0.11:.NETStandard1.0|::.NETFramework4.5|::.NETFramework3.5|::.NETFramework4.0|System.Globalization:4.0.11:.NETStandard1.0|::.NETFramework2.0|System.Collections:4.0.11:.NETStandard1.0|System.Reflection.Extensions:4.0.1:.NETStandard1.0|System.Runtime.Extensions:4.1.0:.NETStandard1.0|System.Runtime.Serialization.Primitives:4.1.1:.NETStandard1.0|System.Text.Encoding:4.0.11:.NETStandard1.0|System.Xml.XDocument:4.0.11:.NETStandard1.0|System.Text.Encoding.Extensions:4.0.11:.NETStandard1.0|System.ObjectModel:4.0.12:.NETStandard1.0|System.Dynamic.Runtime:4.0.11:.NETStandard1.0|System.Xml.ReaderWriter:4.0.11:.NETStandard1.0|::.NETPortable4.5-Profile259|Microsoft.CSharp:4.0.1:.NETStandard1.0|System.Linq:4.1.0:.NETStandard1.0|System.Reflection:4.1.0:.NETStandard1.0|System.Linq.Expressions:4.1.0:.NETStandard1.0|System.Diagnostics.Debug:4.0.11:.NETStandard1.0|System.Text.RegularExpressions:4.1.0:.NETStandard1.0|System.Threading:4.0.11:.NETStandard1.0|::.NETPortable4.0-Profile328|System.Resources.ResourceManager:4.0.1:.NETStandard1.0&lt;/d:Dependencies&gt;
      &lt;d:Description&gt;Json.NET is a popular high-performance JSON framework for .NET&lt;/d:Description&gt;
      &lt;d:DownloadCount m:type="Edm.Int32"&gt;0&lt;/d:DownloadCount&gt;
      &lt;d:IconUrl&gt;http://www.newtonsoft.com/content/images/nugeticon.png&lt;/d:IconUrl&gt;
      &lt;d:IsLatestVersion m:type="Edm.Boolean"&gt;true&lt;/d:IsLatestVersion&gt;
      &lt;d:IsAbsoluteLatestVersion m:type="Edm.Boolean"&gt;true&lt;/d:IsAbsoluteLatestVersion&gt;
      &lt;d:IsPrerelease m:type="Edm.Boolean"&gt;false&lt;/d:IsPrerelease&gt;
      &lt;d:Language m:null="true"/&gt;
      &lt;d:Published m:type="Edm.DateTime"&gt;2016-09-01T05:56:45&lt;/d:Published&gt;
      &lt;d:LicenseUrl&gt;https://raw.github.com/JamesNK/Newtonsoft.Json/master/LICENSE.md&lt;/d:LicenseUrl&gt;
      &lt;d:PackageHash&gt;U82mHQSKaIk+lpSVCbWYKNavmNH1i5xrExDEquU1i6I5pV6UMOqRnJRSlKO3cMPfcpp0RgDY+8jUXHdQ4IfXvw==&lt;/d:PackageHash&gt;
      &lt;d:PackageHashAlgorithm&gt;SHA512&lt;/d:PackageHashAlgorithm&gt;
      &lt;d:PackageSize m:type="Edm.Int64"&gt;1603487&lt;/d:PackageSize&gt;
      &lt;d:ProjectUrl&gt;http://www.newtonsoft.com/json
&lt;/d:ProjectUrl&gt;
      &lt;d:RequireLicenseAcceptance m:type="Edm.Boolean"&gt;false&lt;/d:RequireLicenseAcceptance&gt;
      &lt;d:Tags&gt;json&lt;/d:Tags&gt;
      &lt;d:Title&gt;Json.NET&lt;/d:Title&gt;
      &lt;d:VersionDownloadCount m:type="Edm.Int32"&gt;0&lt;/d:VersionDownloadCount&gt;
      &lt;d:Authors&gt;James Newton-King&lt;/d:Authors&gt;
      &lt;d:MinClientVersion m:null="true"/&gt;
    &lt;/m:properties&gt;
  &lt;/entry&gt;
&lt;/feed&gt;
###### 

So to my question: Is there a way to add an api key to the list, find package, etc requests?

I hope you guys can help me out with this.
Tnx.

**Comment by jopdam** [comment]
Btw, tried with nuget 3.4.4 and latest rc

**Comment by rrelyea** [comment]
Only push uses the API key.
The other commands rely on authentication from the server, and username/password on the client, which can be encrypted and put in nuget.config.
