### ISSUE TITLE
Debugging Package Source Code only works for ASP.NET Core projects (xproj)

### ISSUE THREAD

**Issue by xlegalles** [NuGet/Home#3398]
Debugging Package Source Code as described in this [article](https://msdn.microsoft.com/magazine/mt736459?f=255&MSPPError=-2147217396) does not work with a standard solution that contains only csproj. But as soon as you add an ASP.NET Core project (xproj), it does.

To make it short: you add in a global.json the path to the source code of the package dependency and VS automatically includes the package project in the current solution.

I cannot understand why such a feature that is related to Nuget should be restricted to ASP.NET Core? Don't you think that ANY project that uses Nuget dependencies should also need it? It's really disappointing.

Thank you

**Comment by rrelyea** [comment]
This is using a feature in .NET Core that allows the developer to switch between a package and a project.
NuGet does support debugging into source code if the publisher of a package has published a symbol package with source -- see http://docs.nuget.org/Create/Creating-and-Publishing-a-Symbol-Package (the first paragraph shows how to set up the symbol server in VS)

**Comment by xlegalles** [comment]
Thank you for your answer but it's not really what I was expecting: there is a major difference between a debugging experience using symbols and the one described in this article which uses the original source code and let you update it directly. Plus the fact that debugging with symbols works... sometimes and can be a real headache!

It's really disappointing to watch all improvements made for .NET Core (API, Tools, etc.) which are not available for the .NET framework. Remember guys that we are not supposed to, or can not, switch all to .NET Core!
