### ISSUE TITLE
Write out targets/props files on failed restore

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3399]
Today we don't write *.nuget.targets and *.nuget.props files when a restore fails but could give some confusing errors to the users for .net core projects. So we should write these files irrespective of restore failed or succeed.

**Comment by rrelyea** [comment]
@emgarten - did this already get fixed in 4.0?

**Comment by emgarten** [comment]
@rrelyea I think so, if not I'll make sure we do along with the content files change with tests.

**Comment by emgarten** [comment]
Related to https://github.com/NuGet/Home/issues/4116
