### ISSUE TITLE
NuGet doesn't support spaces in MsBuild path?

### ISSUE THREAD

**Issue by gzak** [NuGet/Home#3400]
I'm not sure if that's the issue exactly, but here's what I get when I try to restore packages in my solution from the command line:

```
> .\.nuget\NuGet.exe restore -NonInteractive .\MySolution.sln
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
The given path's format is not supported.
```

**Comment by gzak** [comment]
Actually there is another possibility, my solution has a somewhat strange structure.

Directory structure:

```
.\MySolution.sln
.\Project1\Project1.csproj
.\Project2\Project2.csproj
.\Project3\Project3.csproj
.\Project4\Project4.csproj
...
```

Solution structure:

```
.\MySolution.sln
.\Group1\Project1\Project1.csproj
.\Group1\Project2\Project2.csproj
.\Group2\Project3\Project3.csproj
.\Group2\Project4\Project4.csproj
```

In other words, I have virtual solution folders which group the projects together that don't actually exist on the underlying filesystem.

**Comment by rrelyea** [comment]
What version of NuGet.exe are you using?
Can you try 3.5.0-rc1 from http://nuget.org/downloads and tell us if that has fixed it or not?

**Comment by gzak** [comment]
@rrelyea sorry for not having tried this earlier, but I just tried it with the build you pointed to and i get the same error :-(

**Comment by nkolev92** [comment]
Thanks for filing this issue. 

Are you still able to reproduce this with the latest nuget 4.5.0?

Thanks.

**Comment by nkolev92** [comment]
At this point we don't have enough information to further investigate this issue. 

Closing it.
