### ISSUE TITLE
missing references in solution explorer when version in package.json is set to *

### ISSUE THREAD

**Issue by maciejw** [NuGet/Home#3402]
given package.json below in portable class lib in vs 2015 update 3

{
  "supports": {},
  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "NLog": "*"
  },
  "frameworks": {
    "netstandard1.5": {}
  }
}

nlog is missing in references in solution explorer tree. when I change version to 4.\* then it will appear. In both cases intellisense works fine and project will compile.

could it be related to nuget tooling problems?

**Comment by rrelyea** [comment]
Is this a .Net Core project or a UWP project?
What version of NuGet are you using? 3.4.4 or 3.5.0? 
If 3.5.0, can you please try 3.5.0-rc1 from http://nuget.org/downloads

**Comment by maciejw** [comment]
Microsoft Visual Studio Community 2015 Version 14.0.25425.01 Update 3
NuGet Package Manager 3.5.0.1484

project is newly created portable class library that targets .netstandard1.5. the same is for the project type class library with project.json added manually.

**Comment by yishaigalatzer** [comment]
So this is the UWP scenario class library scenario. We need to double check where the issue comes from.

Because intellisense works fine, I'm assuming NuGet does the right thing, but the project system for some reason does not pick it up correctly. Getting these folks involved

CC @rchande @jasonmalinowski @Pilchie

**Comment by jasonmalinowski** [comment]
@tmeschter Any chance this a bug that was caused by that filter to package references with a space in the lock file?

**Comment by tmeschter** [comment]
@jasonmalinowski Entirely possible. I can well imagine that the item in the `projectFileDependencyGroup` wouldn't have a version in this case, and thus would have been filtered out. If I have time today I'll try this out and verify if this is fixed or not in Dev15.

See. https://github.com/NuGet/NuGet.BuildTasks/pull/23 for more information.

**Comment by nkolev92** [comment]
This works ok with PR right now. 

Please open another issue if you can still encounter this issue with PR. We will not invest any effort in project.json
