### ISSUE TITLE
[Test Failure] The default value of ‘Version’ drop-down box is blank in Package Manager UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3403]
**Repro Steps:**
1. New a project [such as C# Blank Application (Universal Windows)].
2. Open ‘Manage NuGet Packages for Solution’ and click ‘Browse’ tab.
3. Click a package and look at the ‘Version’ dropdown box.

**Expected Result:**
The default value of ‘Version’ drop-down box is the latest stable version.

**Actual Result:**
The default value of ‘Version’ drop-down box is blank as below screenshot. It also repro in PM UI on project level.
![versionisblank](https://cloud.githubusercontent.com/assets/20632625/18194578/2c808c90-7119-11e6-9fd0-56a6f281fb59.png)
**Note:**
1. It happen on **Dev14 U3+NuGet 3.6.0-Beta1-1815**.
2. It doesn’t repro on NuGet 3.4.4.
3. It **repro** on Dev14 U3+NuGet 3.5.0-RTM-1810.
4. It **repro** on Dev15 WPT+NuGet 3.6.0-Beta1-1815.
**5. This issue blocked most of our automation test.**

**Comment by zhili1208** [comment]
I will look at it
