### ISSUE TITLE
Two .vcxproj files in the same directory share the same packages.config file without installing packages in both projects.

### ISSUE THREAD

**Issue by luckielordie** [NuGet/Home#3404]
When two .vcxproj files in the same solution are in the same directory they attempt to share the same packages.config file.

This results in both projects saying they have a package that is only installed in one project while the other project can still uninstall the package and corrupt the installation of the package in the first project.

To further illustrate the problem I've created a repo demonstrating ProjectA with a package installed and ProjectB 'thinking' it has a package installed when in fact its vcxproj hasn't been altered at all its just consuming ProjectA's packages.config

https://github.com/luckielordie/NugetPackagesConfigBug

This was using VS2013 Update 5 with version 2.12.0.817 of the Nuget Package Manager Extension.

**Comment by yishaigalatzer** [comment]
You should use packages.{project-name}.config in this scenario.

see https://docs.nuget.org/consume/nuget-faq

**Comment by luckielordie** [comment]
Thanks for the Info yishaigalatzer

**Comment by luckielordie** [comment]
For anyone stumbling upon this issue. I couldn't get this fix to work for my version of Nuget.
