### ISSUE TITLE
nuget.exe pack: exclude mask **\foo behaves identically to **foo.

### ISSUE THREAD

**Issue by tonicsoft** [NuGet/Home#3405]
Suppose we wish to create a NuSpec file that will exclude all files with a file name of "foo". We may try the following:

``` xml
<file src="**" target="lib" exclude="**\foo"/>
```

However, this will behave as if we had written `exclude="**foo"`, i.e. it will exclude all files whose file name _ends with_ foo.

The attached ZIP contains two nuspec files, one working and one which demonstrates the bug.
[NuGetBugReproduce.zip](https://github.com/NuGet/Home/files/453463/NuGetBugReproduce.zip)

To reproduce, execute the following commands with version 2.8.60717.93 of nuget.exe CLI.

`nuget pack working.nuspec`
`nuget pack broken.nuspec`

**Comment by tonicsoft** [comment]
I have created a failing test which documents the issue which I can submit a pull request for if helpful. If people agree that this is not the correct behaviour then I'm also happy to have a go at fixing it.

**Comment by rrelyea** [comment]
@rohit21agrawal - please analyze this issue and current behavior.

**Comment by tonicsoft** [comment]
Any update on this one guys? Should be straightforward to agree whether the behaviour is desirable or not.

**Comment by rohit21agrawal** [comment]
@tonicsoft this is a bug - we will fix this in the 3.6 RC timeframe. 

Appreciate your feedback!

**Comment by tonicsoft** [comment]
Great, thanks. If it helps you can use the tests I created on my fork.
