### ISSUE TITLE
Nuget picks unexpected version of MSBuild in VS "15" Preview 4 dev. command prompt

### ISSUE THREAD

**Issue by paulvanbrenk** [NuGet/Home#3408]
Using the VS "15" developer command prompt `Nuget.exe restore` picks the MSBuild 4, which I didn't expect based on the output of the `where` command.

Nuget output:

```
C:\Projects\VSIXProject1>NuGet.exe restore VSIXProject1.sln
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
```

```
C:\Projects\VSIXProject1>where msbuild
C:\Program Files (x86)\Microsoft Visual Studio 15.0\MSBuild\15.0\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```

This happens both for NuGet 3.4.4 and 3.5.0-rc1

**Comment by emgarten** [comment]
Which version do you get if you just run `msbuild /version` from your developer prompt?

NuGet tries to take the first one on the path, I'm not sure which would win here based on your `where msbuild` output.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L262

**Comment by paulvanbrenk** [comment]
Interesting: 

```
C:\TypeScript\VS>msbuild /version
Microsoft (R) Build Engine version 15.1.188.30335
Copyright (C) Microsoft Corporation. All rights reserved.

15.1.188.30335
```

**Comment by drewgillies** [comment]
The path isn't the only issue here. nuget.exe uses the path to find an MSBuild version _prior to 15.1_. But MSBuild 15.1 is a whole new ballgame, and nuget.exe needs to adapt. I have a prototype which should see the light of day soon.

**Comment by paulvanbrenk** [comment]
@drewgil Thanks for looking into this, if you need anything from me let me know.

**Comment by rrelyea** [comment]
Fixed in RC3

**Comment by VitaliyHetsman** [comment]
the same issue using NuGet Version: 4.5.0.4651
`MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.`

MSBuild.exe /version
`Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
15.5.180.51428`

where msbuild:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe`
