### ISSUE TITLE
[Test Failure] Package ‘Newtonsoft.Json’ can’t be installed into CPPWin32Project

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3409]
**Repro Steps:**
1. Create a new C++->Windows->Win32->Win32 Project.
3. Right-click the project and select ‘Manage NuGet Packages…’.
4. Go to ‘Browse’ tab and install package ‘Newtonsoft.Json’.

**Expected Result:**
Package ‘Newtonsoft.Json’ can be installed successfully.

**Actual Result:**
Package ‘Newtonsoft.Json’ can’t be installed with the error as below screenshot.
![untitled123456](https://cloud.githubusercontent.com/assets/20632775/18267875/c323c4cc-7453-11e6-9bcc-bb10278ccb57.png)

**Note:**
1.  The issue happen on VS2015 25425.01 Update3 + NuGet 3.6.0-beta1-1818.
2.  The issue also repro on VS2015 25425.01 Update3 + NuGet 3.5.0-rtm-1820.

**Comment by davidfowl** [comment]
CPPWin32Project? Isn;t that a C++ project? Why would Newtonsoft.Json work there?

**Comment by rrelyea** [comment]
@v-nancyj  - did this work in 3.4.4 -- agreed, likely doesn't make sense to work.

**Comment by v-nancyj** [comment]
@rrelyea This issue repro on 3.4.4.

**Comment by rrelyea** [comment]
yes, working as it should.
