### ISSUE TITLE
dll referred also to be shown in nuget window in VS

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#3411]
the dll referred by the solution also to be shown as marked in the snapshot
![4](https://cloud.githubusercontent.com/assets/16834561/18273648/f359e448-745b-11e6-836e-0a09d2ac7519.png)

**Comment by yishaigalatzer** [comment]
This is part of a bigger feature we want to do that shows package content, scripts that are going to run, content files that are going to get installed.

**Comment by yishaigalatzer** [comment]
Find or create the dup bug and link to a spec

CC @harikmenon @rrelyea

**Comment by nkolev92** [comment]
We currentl
