### ISSUE TITLE
NuGet does not use credentials from NuGet.Config

### ISSUE THREAD

**Issue by frobijn** [NuGet/Home#3412]
I'm trying to use NuGet.exe (no extra helpers) 3.4.4.1321 to list/... packages in a VSTS feed. That fails because the NuGet client is broken: it does not use the credentials from the NuGet.Config file. I've read the known issue on https://docs.nuget.org/Release-Notes/Known-Issues about double-encrypted passwords, but even when stored in clear text it does not work.

What I've done:
- Added username and password (= personal access token) to the global NuGet.Config file, via the NuGet command line:
  nuget sources add -name "Test" -source "https://xxx.pkgs.visualstudio.com/_packaging/Develop/nuget/v3/index.json" -username vsts -password "<my personal access token>" -StorePasswordInClearText
- Added the API key via the SetApiKey command
- Verified that all information is present in the %appdata%\NuGet\NuGet.Config file. It is the only VSTS feed present.
- NuGet fails with "The remote server returned an error: (401) Unauthorized." for:
  nuget list <package name> -Source "Test" -AllVersions -NonInteractive
- If the -NonInteractive option is omitted, nuget asks for the credentials. If I enter the same username and password/PAT that are in the NuGet.Config file, the command succeeds. I.e. there is nothing wrong with the VSTS feed or the credentials.
- Adding the option -ConfigFile %appdata%\NuGet\NuGet.config (just to be sure) does not solve the issue. There are no NuGet.Config files in the directory where NuGet.exe is located (and run) nor in its parent directories.
- There are no plugins in %localappdata%\NuGet

**Comment by frobijn** [comment]
Just verified:
- NuGet 2.8.60717.93 does work correctly with credentials in NuGet.Config (and the v2-endpoint of the feed: "https://xxx.pkgs.visualstudio.com/_packaging/Develop/nuget/v2").
- NuGet 3.4.4.1321 also works correctly with the v2-endpoint of the VSTS feed.

So the issue is related to the v3-versions of both the NuGet client and VSTS feeds.

**Comment by yishaigalatzer** [comment]
I believe this issue was fixed in 3.5 RTM, we don't have this up on the feed yet, but we will put it up and you can then with a build that has the fix from https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine 

CC @emgarten @zhili1208 @rrelyea

**Comment by emgarten** [comment]
@frobijn try the latest 3.5.0 build here: https://dotnet.myget.org/F/nuget-build/api/v2/package/NuGet.CommandLine/3.5.0-rtm-1822

**Comment by frobijn** [comment]
Indeed, in 3.5.0 this is fixed.

**Comment by emgarten** [comment]
@frobijn thanks for verifying!
