### ISSUE TITLE
Provide more information when template package install fails

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3413]
Suppose a VS template tries to install a package from the VS disk source (`C:\Program Files (x86)\Microsoft SDKs\NuGetPackages`) that does not exist. Currently, there is a very vague failure pop-up that the user will have a hard time acting upon.

This is related to VS bug 258630.

![image](https://cloud.githubusercontent.com/assets/94054/18282624/c46582e0-7416-11e6-9de7-134f9638a0ab.png)

**Comment by nkolev92** [comment]
We will not invest any effort in the template wizard for packages.config.
