### ISSUE TITLE
Creating PCL class library failed

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3414]
VS version: 14.0.25425 update 3
NuGet version: 3.5.0.1819

Repro step:
1. Create a C# Class Library (Portable) project.
2. In the "Add Portable Class Library" dialog, check ".Net Framework 4.6", "Windows Universal 10.0" and "ASP.NET Core 5.0"

Expected Result:
There is no error occur during creating.

Actual Result:

![capture](https://cloud.githubusercontent.com/assets/7131513/18286111/38d26f62-7426-11e6-8469-28cccbaec9b3.PNG)

**Comment by zhili1208** [comment]
@rrelyea should consider this for 3.5.0 (RTM). repro same issue on 3.4.4.1321

**Comment by rrelyea** [comment]
Known issue from VS2015 MicroUpdate 3.4. First problem is that two packages aren't found by template creation. Workaround would be to get them into the package cache.
MicroUpdate 3.5 will revert that change.

**Comment by rrelyea** [comment]
@zhili1208 -
1) please make sure to type in error strings so they are searchable: "Package Restore Failed. Rollling back package changes."
2) can the packagemanager output window provide any more information, to increase searchability as well? if so, please include
