### ISSUE TITLE
Command line - list outdated packages, similar to leiningen's "lein ancient" command

### ISSUE THREAD

**Issue by brianbegy** [NuGet/Home#3415]
This is a feature request for a command line "list outdated packages" feature. This would be similar to what "lein ancient" provides for Clojure developers.

NuGet command line offers an update command, but I'm looking for a read-only version. Just show me a list of all packages that are out of date in a solution and let me decide. This is something we could automate as part of our build process.

I'm open to just pulling the source and building this, but I'm looking for guidance on if this is something the team considered and explicitly rejected before I start.

**Comment by yishaigalatzer** [comment]
We could consider this, we have a similar feature in the powershell console. We need to agree on spec, and we will be open to a PR.

The equivalent command is `Get-Package -Updates`

Here is a top of my head strawman spec -

The scenarios this needs to work in:
1. packages.config
2. project.json
3. Upcoming `<packageref />`

Needs to work against a single or multiple servers
Needs to support pre-release flags
Needs to work from command line on windows or dotnet (linux/mac/windows)

**Comment by kevinkuszyk** [comment]
I may have some time coming up to dedicate to this.  

Before I get stated is there any preference on output?  I was thinking something like this based on `npm outdated`:

```
Package                Current     Wanted      Latest    Location
EntityFramework        6.1.2       6.1.2       6.2       SomeProject.Data
NUnit                  2.4.0       2.6.4       3.8.1     SomeProject.UnitTests
```

Also, is the preference still to add a new command for this, rather than adding a `-whatif` flag to the `update` command as per #5762?

**Comment by nkolev92** [comment]
Closing this issue as a dupe of #5762 

@kevinkuszyk If you're still willing to devote some to this, we'll be happy to work through a design. 

Thanks.

**Comment by dmprantz** [comment]
Was this ever implemented?  Over a year later, and I don't see it documented.  I can do it through VS, but need to do it from command line.
