### ISSUE TITLE
[NuGet.Protocol] V2Utilities SafeToNuGetVer is creating NuGetVersion with extra 0

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#342]
Repro steps:
1. Install-package Microsoft.aspnet.mvc -version 5.0.0
2. Get-package -updates against V2

Expected: NuGetVersion returned inside PSSearchMetadata is normalized version

Actual: Microsoft.Aspnet.MVC is shown with a version of 5.2.3.0.

**Comment by emgarten** [comment]
Fixed with c468e7c92881118f0834f27e6199d4bfd682e4a2
