### ISSUE TITLE
[Test Failure] Error occur when typing an ‘e’ in search filter of ‘Browse’ tab on PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3420]
**Repro Steps:**
1.  New a project [such as C# Blank Application (Universal Windows)].
2.  Open ‘Manage NuGet Packages for Solution’ and click ‘Browse’ tab.
3.  Type an ‘e’ in search filter.

**Expected Result:**
No error occur.

**Actual Result:**
An error occur as below screenshot.
![erroroccur](https://cloud.githubusercontent.com/assets/20632625/18340232/6a29552e-75d6-11e6-807b-78c2e39a691b.png)

**Note:**
1.  It was found on Dev15 WPT 25707.00+NuGet 3.6.0-Beta1-1830.
2.  It repro on Dev14 U3+NuGet 3.5.0-RTM-1829.
3.  It also repro on NuGet 3.4.4.1321.
4.  The issue will disappear when you go on typing the second character.
5.  It also repro in Package Manager UI on project level.

**Comment by rrelyea** [comment]
image uri problem? Please take a peek
