### ISSUE TITLE
Credentials from NuGet.Config not used in VS2013

### ISSUE THREAD

**Issue by MartinJohns** [NuGet/Home#3422]
Visual Studio 2013 Professional Update 5
NuGet Package Manager 2.12.0.817

`NuGet.Config` file at solution level:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="OurFeedName" value="https://[our-feed-uri]/" />
  </packageSources>
  <packageSourceCredentials>
    <OurFeedName>
      <add key="Username" value="[Username]" />
      <add key="Password" value="[Password]" />
    </OurFeedName>
  </packageSourceCredentials>
</configuration>
```

`NuGet.Config` in %AppData%/NuGet is empty.
I also tried to have this configuration in the system-wide %AppData%/NuGet configuration, but it made no difference. I also attempted to store the Password in clear text, with no difference either.

Expected behavior:
- No credentials dialog when restoring NuGet packages, searching for them or installing them using either the dialog or the Package Manager Console.

Actual behavior:
- Credentials dialog appears on any NuGet operation.

Any advice?

**Comment by yishaigalatzer** [comment]
@alpaix can you take a look and help @MartinJohns out? If there is a bug here, please change the tags and lets discuss

**Comment by alpaix** [comment]
@MartinJohns Will you be able to capture a Fiddler trace with network calls and send it to support@nuget.org? Also please share the output from PMC.

Another alternative to verify the configuration would be performing restore with command line nuget.exe.
