### ISSUE TITLE
Nuget add does not allow both a package with symbols and without to be in the same repo

### ISSUE THREAD

**Issue by mdkf** [NuGet/Home#3423]
On our MyGet feed we have 2 copies of all of our packages, one with symbols and one without. We would like to have the same setup on our optimized file share feed as well. After adding the package without symbols, we cannot add the package with symbols as nuget add says the package already exists.

**Comment by yishaigalatzer** [comment]
We do not plan to support it. There is an inherent collision between the two packages, and there is no meaning to the symbols in the same repo. You could have two repos and two feeds if you'd like instead.
