### ISSUE TITLE
NuGet fails to install a package targeting netstandard1.0 into a PCL(profile 111) project targeting Windows Phone 8.1

### ISSUE THREAD

**Issue by erezvani1529** [NuGet/Home#3424]
Hi,

**Solution/Project and references Structure**

We are using the VS2015(latest update) template to create a Native Portable solution. The solution consists of a Droid, iOS, Windows Phone 8.1 and a PCL (Profile 111) project which by default targets the following platforms:

NetFx 4.5
ASP .Net Core 1.0
Windows 8
Windows Phone 8.1
Xamarin.ndroid
Xamarin.iOS

The Nuget package we are trying to install supports following TFMs:
net45
netstandard1.0 (façade)
netstandard1.3
uap10.0
win81
wp8
wpa81

**Observed Failure** 

> Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**What works**
Following the discussion in [issue#1325](https://github.com/NuGet/Home/issues/1325) , we tried removing Windows 8 and Windows Phone 8.1 from the target list of the PCL project and the package is now installed successfully.

In issue#1325 you have mentioned:

> Consider that PCL requires a dll to compile against. It needs one that supports all the targets.

However, what is not clear to us is that netstandard1.0 is supposed to support all targets. Would you please help us clarify why this is happening in our case?

-- Azure Storage Client Library team is planning to release a façade targeting netstandard1.0 to ensure maximum support of all target platforms and this is one of the issues we need to address to make sure our façade plan will work as promised.

Thanks!

cc:/ @ericstj

**Comment by ericstj** [comment]
I believe is an issue with the RuntimeInformation package.  Have you seen issue https://github.com/dotnet/corefx/issues/10445?

**Comment by erezvani1529** [comment]
Thanks @ericstj! We will continue following that thread.
