### ISSUE TITLE
NuGet 3.5.0 no longer uses a default package source, you have to specify one in NuGet.Config

### ISSUE THREAD

**Issue by oatsoda** [NuGet/Home#3426]
See  [This SO Post](http://stackoverflow.com/questions/39352013/nuget-fails-to-restore-netstandard-libary-for-netstandard1-2-in-vnext-build-agen)

The [NuGet docs](https://docs.nuget.org/consume/nuget-config-defaults) state:

> Without any default package sources specified in the NuGet Config Defaults file, NuGet will continue to use nuget.org as the default package source.

But this no longer appears to hold true.  Instead you must supply a NuGet.config and specify a package source, e.g.

```
 <?xml version="1.0" encoding="utf-8"?>
 <configuration>
   <packageSources>
     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
   </packageSources>
 </configuration>
```

**Comment by yishaigalatzer** [comment]
Yes, this is true and by design. Will update the docs

**Comment by karann-msft** [comment]
Docs updated.
