### ISSUE TITLE
Nuget 2.12 doesn't install all files in package as expected

### ISSUE THREAD

**Issue by apolcyn** [NuGet/Home#3427]
When installing a certain nuget package, Grpc.Tools.1.0.0 in my case, not all of the files from the published nuget package are getting included in the resulting package folder after install.

To reproduce unexpected behavior:

Using nuget 2.12 on linux or OS X (nuget 2.12 downloaded via apt-get, or installed with Xamarin Studio 6.0 in my case):
1. `/path/to/nuget install Grpc.Tools` (should get version 1.0.0)
2. `cd Grpc.Tools.1.0.0/tools && ls`
3. The problem is that now only the `tools/windows_x86` and `tools/windows_x64` directories exist, when there should be more directories for linux and OS X (which contain pre-compiled executables for this package).

Unlike nuget 2.12, nuget 2.8 and 3.4 don't seem to have this problem - with 2.8 and 3.4, all files from the published nuget package are in the resulting install package folder. Unfortunately 2.8 is undesirable because it doesn't allow installation of packages that require 2.12 or higher, which we have a dependency on. And unfortunately 3.4 is undesirable because of its breaking behavior around solution restores. So being able to use the 2.12 version of nuget that comes installed with Xamarin Studio 6.0+, and available via apt-get, would be ideal here.

Wondering if this is a bug, or if not, if you might have any other advice for working around the issues described with the other versions of nuget. Thanks in advance!

**Comment by yishaigalatzer** [comment]
NuGet 2.12 commandline (nuget.exe) is not a supported product, we never tested it and we never intended for it go be distributed. I'll chat with the Xamarin folks about it

**Comment by jtattermusch** [comment]
@yishaigalatzer   on the Downloads page of www.nuget.org (https://dist.nuget.org/index.html), one can download "VS 2013 VSIX (v2.12.0)" which gives you nuget 2.12, also, installing the latest version of mono on Linux or Mac gives you nuget client of version 2.12. So it really sounds it is officially distributed.

It also should be distributed because you need it to be able to restore solutions that are using some of the newer nuget packages (such as System.Interactive.Async).

**Comment by yishaigalatzer** [comment]
@jtattermusch the nuget vsix is officially released. But from your bug it didn't seem to be that you have a problem with that artifact.

NuGet 2.12 is not released, the mono team chose to fork it and ship a version. We only support NuGet 3.5 and on, we do not ship (nor test) versions of nuget.exe for 2.12.
