### ISSUE TITLE
PSSearchMetadata is returned by calling UISearchResource

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#343]
which returns UISearchMetadata (contains lots of extra info that's not needed by PS), and then shove into PSSearchMetadata type.

This will affect the performance of PowerShell search. 

For long-term, we should have PSSearchResource that only do necessary metadata parsing for PowerShell needed fields.

**Comment by ChrisSfanos** [comment]
Will analyze this post RTM

**Comment by emgarten** [comment]
The extra information here is minimal. Changing this would require a v3 protocol change so I think we are fine with this as is.
