### ISSUE TITLE
Make nuget 2.12 available for download

### ISSUE THREAD

**Issue by jtattermusch** [NuGet/Home#3430]
On the www.nuget.org download page, one can download different versions of nuget command line client, but version 2.12 is missing.
The reason why it is important is that you need it to be able to restore solutions that are using some of the newer nuget packages (such as System.Interactive.Async).  Nuget 3.x is not usable because it doesn't allow to restore .sln files when on Linux on Mac (when using mono).

**Comment by rrelyea** [comment]
Sorry, nuget.exe won't be released for 2.12. Sorry, we cannot test that release, and therefore shouldn't release it. 
We are working on fixing the .sln restore on Mono.
