### ISSUE TITLE
Nuget 3.5.0rc1 can not parse solution file

### ISSUE THREAD

**Issue by alexxn** [NuGet/Home#3436]
1) Download Source code (zip) from https://github.com/dnnsoftware/Dnn.Platform/releases (direct link:https://github.com/dnnsoftware/Dnn.Platform/archive/v8.0.4.zip)
2) Unpack and run nuget restore command

D:\Temp\nuget350rc1.exe restore "D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Error parsing solution file at D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln: Exception has been thrown by the target of an invocation.

3) Packages are not restored

The issue can be reproduced in nuget-3.5.0rc1

**Comment by rrelyea** [comment]
Was there a version of NuGet that worked for this solution?
Does it help if you pass in the command to choose msbuild version 4 or something else?

**Comment by zhili1208** [comment]
I can't repro this issue with rc2 bits, Can you try https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine/3.5.0-rtm-1829?

**Comment by rrelyea** [comment]
@alexxn - please reply to both my early question and zhi's question as well. we are short on time. Please reply asap.

**Comment by alexxn** [comment]
Just tried 3.5.0-rtm-1829. Not working.

```
d:\Temp>D:\Temp\nuget_rtm-1829.exe restore "D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Error parsing solution file at D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln: Exception has been thrown by the target of an invocation.
```

**Comment by alexxn** [comment]
Not sure how to use msbuild 4, but I tried 

`d:\Temp>D:\Temp\nuget_rtm-1829.exe update "D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln" -MSBuildVersion 4
`

And got huge output with no errors. Afterwards I tried to restore again and got the same problem

```
d:\Temp>D:\Temp\nuget_rtm-1829.exe restore "D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln"
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Error parsing solution file at D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln: Exception has been thrown by the target of an invocation.
```

**Comment by alexxn** [comment]
Probably you will find this output useful as well:

```
d:\Temp>D:\Temp\nuget_rtm-1829.exe restore "D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln" -MSBuildVersion 4
Error parsing solution file at D:\Temp\Dnn.Platform-8.0.4\DNN_PlatformNoTests.sln: Error parsing the nested project section in solution file. A project with the GUID "{B816AB39-0689-420B-
94A3-581463EB9E40}" is listed as being nested under project "{29273BE6-1AA8-4970-98A0-41BFFEEDA67B}", but does not exist in the solution.
```

**Comment by zhili1208** [comment]
I tried 2.8, 3.4.4 and 3.5, this doesn't work with all the versions, I think the issue is msbuild can't parse this solution because 
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dnn.Modules.Newsletters", "DNN Platform\Admin Modules\Dnn.Modules.Newsletters\Dnn.Modules.Newsletters.csproj", "{DF9DA7E9-FBD6-4411-A4C1-768E0DC945E3}"
EndProject

doesn't exist on disk.

**Comment by rrelyea** [comment]
Our behavior sounds good. We should not silently ignore the problem with the solution.

**Comment by sercantimocin** [comment]
I Had same issue. The problem was the sln file has same blank lines. I removed the lines. It resolved

https://stackoverflow.com/questions/45100594/nuget-restore-exception-has-been-thrown-by-the-target-of-an-invocation
