### ISSUE TITLE
`Nuget.Packaging` does not have stable 3.4.4 package version

### ISSUE THREAD

**Issue by StephenCleary** [NuGet/Home#3438]
The [`NuGet.Packaging` version](https://www.nuget.org/packages/NuGet.Packaging) for the (presumably stable) 3.4.4 release is using a prerelease version string `3.4.4-rtm-final`.

So, if a user installs `NuGet.Packaging` into a new project (without including prerelease packages), they will get the older 3.4.3 version, which has bug #2690 in particular.

Please re-release `NuGet.Packaging 3.4.4-rtm-final` (and any other necessary packages)  as `3.4.4`.

**Comment by yishaigalatzer** [comment]
Are current plan of record is to release 3.5 shortly without the pre-release tag (and skip the step you suggested above). Mostly due to cost/timing, it is definitely the right thing to do, ignoring the effort to do so.

If you disagree, we'd love to hear feedback.

**Comment by yishaigalatzer** [comment]
to add a couple more details
1. To reship nuget.commandline we need to do more work because the metadata is nuget.exe affects nuget.exe update /self
2. To reship the other packages we just need to change the references without recompiling

Will get together and revisit the plan today

**Comment by StephenCleary** [comment]
I think that's fine. As long as 3.5 is released shortly. :)

**Comment by NickCraver** [comment]
+1 on not having suffixes in the future for any finals. Honestly, just from a historical standpoint `-final` in particular is asking for karma to strike :) I think we should _fully_ embrace semver. If 3.4.4 has a break, then that's 3.4.5. The "second release" semantics for fixes really need to be left behind across the board.

**Comment by yishaigalatzer** [comment]
@NickCraver this was a mistaken case of pushing the wrong packages. The -final is used in semver 1.0.0 to denote the released version of a CI prerelease milestone (hmmm that sounds confusing....)

So:
1.0.0-beta####

then 
1.0.0-beta-final

then 1.0.0-rc####

and so on.

When we push a release, it should just be 1.0.0 like you are suggesting above

**Comment by pvandervelde** [comment]
So this issue was opened 2 months ago and there's still no stable 3.50 release. 2 months is not shortly. It would be very nice if you could either release the 3.5.0 packages as the final packages (no pre-release) or release a 3.4.4 stable package so that we don't have to fall back to using a package that is nearly 7 months old.

**Comment by pvandervelde** [comment]
@yishaigalatzer Any idea when 3.5.0 will be properly released? We need to build NuGet packages based on the NuGet API packages but the last stable one is 3.4.3 which has known issues. And NuGet won't let us reference pre-release packages in a normal NuGet package.

**Comment by yishaigalatzer** [comment]
Rob is working on it right now, he should be able to provide the eta

Sent from Ninehttp://www.9folders.com/

**Comment by pvandervelde** [comment]
@yishaigalatzer Any news?

**Comment by pvandervelde** [comment]
@yishaigalatzer Is there any word on when there will be a stable version of the API? 3.5 has been released a while ago and the development for 4.0 has already started. Can you please release a stable (i.e non-preview) version of 3.5.0 or 3.4.4.

**Comment by NickCraver** [comment]
Pretty sure he's on vacation at the moment, @rrelyea @emgarten  can you take a look please?

**Comment by emgarten** [comment]
3.5.0 is available on nuget.org now, enjoy! 📦 📦 🎉

**Comment by NickCraver** [comment]
\o/ Thanks @emgarten!

**Comment by pvandervelde** [comment]
Awesome! Thanks heaps guys
