### ISSUE TITLE
Error during NuGet update

### ISSUE THREAD

**Issue by mdkf** [NuGet/Home#3440]
When updating a package, NuGet tells me that it first uninstalled the old package and all of the files included with it. However when it attempts to install the new version of the package, it complains about a file conflict with a file it said it had removed during the uninstall. Whats going on here? Log below:

D:\Jenkins_Home\workspace\CSGAP\My Project>"C:\nuget.exe" update "D:\Jenkins_Home\workspace\CSGAP\My Project\My.Project.sln" -Source https://www.myget.org/F/*** -Verbosity detailed 
NuGet Version: 3.5.0.1737
Scanning for projects...
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Found 1 project with a packages.config file. (My.Project.csproj)
Looking for installed packages in 'packages'.
Feeds used:
  https://www.myget.org/F/***

Attempting to gather dependency information for multiple packages with respect to project 'D:\Jenkins_Home\workspace\CSGAP\My Project\My.Project.csproj', targeting '.NETFramework,Version=v4.0,Profile=Client'
Total number of results gathered : 10
Gathering dependency information took 1.63 sec
Summary of time taken to gather dependencies per source :
D:\Jenkins_Home\workspace\CSGAP\My Project\packages      -              4.29 ms
https://www.myget.org/F/***         -              5.23 sec
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages

Removed package 'MyPackage.1.1.2440.0' from 'packages.config'
Removed file 'BoardRepository.xml' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'BoardRepository.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'ChipProtocolConfiguration.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'Config.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'ConfigurationSettings.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'DeviceModel.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'EvalComponentContentView.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'EvaluationComponents.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'Extensions.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'GpioPortDefinition.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'nuspec.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'Response.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'ServerConfiguration.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'Session.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'StandardCaptureChip.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'StandardMemoryChip.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed file 'Wizard.xsd' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\Schemas'.
Removed folder 'Schemas'.

Removed file 'packages.config' from folder 'D:\Jenkins_Home\workspace\CSGAP\My Project'.

Adding package MyPackage.1.3.2458' to folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\packages'
Added package 'MyPackage.1.3.2458' to folder 'D:\Jenkins_Home\workspace\CSGAP\My Project\packages'

File Conflict.
File 'Schemas\Wizard.xsd' already exists in project 'My.Project.csproj'. Do you want to overwrite it?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All ?[Y] Yes  [A] Yes to All  [N] No  [L] No to All ?[Y] Yes  [A] Yes to All………

**Comment by nkolev92** [comment]
@mdkf Are you still able to reproduce this problem?

**Comment by nkolev92** [comment]
Thanks for filing this issue. 

At this point, we don't have enough information to reproduce this issue. 

Please create a new one if you still hit this problem with our latest VS 2017 release.
