### ISSUE TITLE
nuget.exe list -allversions doesn't work

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3441]
Version: 3.5 rc2
Repro: 
Run:`NuGet.exe list packageid:EntityFramework -verbose -allversions`
Result: 

> EntityFramework
>  6.1.3
>  Entity Framework is Microsoft's recommended data access technology for new applications.
>  License url: http://go.microsoft.com/fwlink/?LinkID=320539

**Comment by rrelyea** [comment]
this appears to be broken in 2.8.6 and up. I didn't test before 2.8.6.
should fix or remove the switch/docs.

**Comment by joelverhagen** [comment]
This doesn't seem to be a client issue at all. This does not repro against servers that properly support all version (e.g. MyGet).

**Comment by nkolev92** [comment]
This is a nuget.org bug. 

Relevant bug https://github.com/NuGet/NuGetGallery/issues/3274.

Closing
