### ISSUE TITLE
Nuget Update from Command Line not running install.ps1 or editing csproj files for added/removed files

### ISSUE THREAD

**Issue by Mattygs6** [NuGet/Home#3444]
It does however add new hint paths for updated dll versions in the csproj files.

The setup:
git.reset-update-push.bat
@echo off

FOR /D %%G in (.*) DO (
 Pushd %%G
 CALL git.reset.bat
 FOR %%i in (*.sln) DO .nuget\nuget.exe update %%i -MSBuildVersion 14 -Verbosity Detailed -FileConflictAction Overwrite -source "http://nugets.client.com/nuget/Client-Shared;http://nugets.client.com/nuget/Client-Static;http://nugets.client.com/nuget/Client;http://nugets.client.com/nuget/Sitecore-8-1-0-160302;http://nugets.client.com/nuget/Open-Source;"
 git add .
 git commit -m "update nugets"
 git push
 Popd )

There are 4 folders that are git repositories at the same level as this batch file. These repositories have code that depend on the shared repository.
us
mx
ca
client

When building from master on our shared repository, we push nugets for those dlls to our nuget server.  We are using TeamCity, and we are not having any issues there.  There is a build on TeamCity which after successful build on master-shared + nugets being added to our server, will run the batch file listed above.  Say I added a new config file /App_Config/Include/Something.config to our configuration project.  This file does not get added to the csproj file of that project nor does it run the install.ps1.  This all works in visual studio when updating nugets for the entire solution.

**Comment by yishaigalatzer** [comment]
This is a known limitation of the packages.config pattern.

We have built a mechanism to include packages only as metadata which is currently expressed by project.json, and in the future directly in the msbuild file as packagereference element, but we do not know of a good way to make install.ps1 run outside of visual studio nor we plan to attempt to support it.
