### ISSUE TITLE
proposal: add nuget.exe download $package -version $version

### ISSUE THREAD

**Issue by ghuntley** [NuGet/Home#3447]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Idea: Method from CLI with <a href="https://twitter.com/nuget">@nuget</a> download $package -version $version to nab a package without packages.config.</p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/776201422140350464">September 14, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/GeoffreyHuntley">@GeoffreyHuntley</a> I actually wrote this a couple of months ago at work :)</p>&mdash; Patrik (@firstdrafthell) <a href="https://twitter.com/firstdrafthell/status/776205610048184320">September 14, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by emgarten** [comment]
Would this extract the package or just download the nupkg to disk?

**Comment by ghuntley** [comment]
This proposal is to download the nupkg into the current working directory and potentially add an `-destination "c:/downloads` configuration option. No strong feelings about configuration option naming. Feel strongly that download verb should only download a package. Nothing else. 

I'd also like to see two verbs added, unpack and repack. That unzip and then repack/zip. That should be discussed in another issue though.

**Comment by emgarten** [comment]
`nuget.exe install <package> -version <version>` will download and unpack the package directly, have you tried using that?

**Comment by yishaigalatzer** [comment]
This does look like a duplicate. And we do track enhancing install with flags to only download the package without dependencies.

I'm suggesting we close out this one as a dup

**Comment by yishaigalatzer** [comment]
Here is the dup - https://github.com/NuGet/Home/issues/3336

I'm also suggesting to follow this idea, and make download the official verb, and make install post a deprecated message use download instead.

**Comment by ghuntley** [comment]
Closing this out for 3336. Official verb would be great. Here's the context:

> As a package maintainer (or user) I want a way to download a specific package without visiting the website. I want the raw, actual package, installing, unpacking and/repacking should be separate verbs.
