### ISSUE TITLE
CI builds should run with isolated user packages folder and HTTP cache

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3448]
Today, they share these things. Since out NuGet.Clients projects has floating specs (e.g. `"NuGet.Frameworks": "3.5.0-*"`), it's possible that the wrong package (one from an online source) is picked instead of the package just built.

This can lead to unexpected test failures (new tests hitting old code) or compilation failures (new client code depending on old core code).

**Comment by nkolev92** [comment]
Wasnt nocache added to fix this scenario? 

Closing this now. 

@joelverhagen Please let me know if I misunderstood this.
