### ISSUE TITLE
NuGet.CommandLine tests should have isolated global packages folder and HTTP cache

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3449]
Right now, many of NuGet.CommandLine.Tests test cases shell out to the nuget.exe that was just built. When doing this, they may pass in the URL to a mock server (e.g. `http://localhost:53201/index.json`) that was used in a different test. If URL is cached in the HTTP cache, it's possible that the running test will encounter the wrong version of a resource. This is particular obvious when two tests mock up different `index.json` (service index) bodies. Since the mock server uses a port reserver that releases the port after the test is complete, two tests can use the same exact mock server URL.

**Comment by nkolev92** [comment]
This was already done. 
The mock servers have a random url, and the global packages folder is isolated per test context
