### ISSUE TITLE
Nuget Package Manager repeatedly breaking in Visual Studio 2015

### ISSUE THREAD

**Issue by BigDaddyD** [NuGet/Home#3450]
Any update to visual studio 2015 breaks the most recent version of the nuget package manager. Attempting to view it in the options menu after a Visual Studio update results in this display

![image](https://cloud.githubusercontent.com/assets/5808850/18564495/b260161a-7b59-11e6-9063-e605be03fa2a.png)

Options to manage Nuget packages have also disappeared from the Tools Menu
![image](https://cloud.githubusercontent.com/assets/5808850/18564509/c8c34486-7b59-11e6-8d66-13a91365cfaf.png)

as well as the project sub-menus in Solution Explorer
![image](https://cloud.githubusercontent.com/assets/5808850/18564533/ee94ae02-7b59-11e6-8245-1f43c2fd9ac7.png)

I have encountered this problem before and have previously implemented a very wonky solution, as described here: http://nuget.codeplex.com/workitem/3031

However, this time around that solution is not fixing this problem. 

Does anyone have any experience/advice for solving this issue. It should be handled promptly, as it essentially the result of broken software and makes it impossible to implement Nuget Packages in any of my enterprise projects

**Comment by rrelyea** [comment]
When did this stop working?
What build # of vs do you have installed?
What build # of NuGet do you have installed (see tools/extensions/installed/...)
Have you tried a VS repair?

**Comment by BigDaddyD** [comment]
Just today, when I went ahead with the updated recommend by VS. I have Visual Studio 14.0.25431.01 Update 3, I have tried repairing VS, no change. I've been using the most recent version, 3.4.4.1321

**Comment by rrelyea** [comment]
Can you try to uninstall the nuget extension via tools/extensions. Then shut down VS. Then install 3.4.4 again via http://nuget.org/downloads and Double click the vsix u download. 

If that does not work, uninstall 3.4.4 and install 3.5.0rc1

Please let us know.
We were not able to reproduce an upgrade problem on our end.

**Comment by BigDaddyD** [comment]
No change

**Comment by BigDaddyD** [comment]
![image](https://cloud.githubusercontent.com/assets/5808850/18585914/d3f1b2b4-7be7-11e6-9075-900fb8dcd590.png)

A new error message from visual studio regarding this issue. This one became present after I uninstalled the 3.5 version. I currently have no version of installed. Now the option has reappeared in the tools menu

![image](https://cloud.githubusercontent.com/assets/5808850/18585958/1f1be14c-7be8-11e6-9c6a-2d8a0fcd4249.png)

as well as the project submenu in the solution explorer

![image](https://cloud.githubusercontent.com/assets/5808850/18585978/3d48b7bc-7be8-11e6-9a61-ee48e8bf9d0b.png)

**Comment by rrelyea** [comment]
And those menus are not functional, I assume?

If not functional:
1) please install 3.4.4
2) run "devenv /setup" with VS closed from a command line.
3) then run VS again, and tell us behavior...

There is a cache of different components that seems to be out of sync with things that are installed.

**Comment by nkolev92** [comment]
We haven't received feedback on this. 

We haven't had these issues with 3.6.0 on VS 2015 and VS 2017.
