### ISSUE TITLE
Document library include flags

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#3451]
I couldn't find documentation for [library include flags](https://github.com/NuGet/NuGet.Client/blob/3.5.0-rc1-final/src/NuGet.Core/NuGet.LibraryModel/LibraryIncludeFlag.cs)  in project.json. The flags show up in schema store (which supplies VS autocompletion), but doesn't show up in https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json or https://docs.nuget.org/consume/projectjson-format

![image](https://cloud.githubusercontent.com/assets/2696087/18565445/a6307d5e-7b44-11e6-88d9-2afc943b3143.png)

**Comment by yishaigalatzer** [comment]
PJ is dead, there is no point in fixing this in PJ, we should document the feature in Msbuild

@emgarten @karann-msft

**Comment by karann-msft** [comment]
This has been documented for PackageReference https://docs.nuget.org/ndocs/consume-packages/package-references-in-project-files#controlling-dependency-assets
