### ISSUE TITLE
proposal: add nuget.exe unpack|repack MyCoolPackage.nupkg

### ISSUE THREAD

**Issue by ghuntley** [NuGet/Home#3452]
UNPACK:

> As a package maintainer I want to unpack the nupkg because I'm going to be monkey patching the nuspec metadata and/or any numerous evil activities one might need to do under the hood.

REPACK:

> As a package maintainer, I want to repack (and validate nuspec validity / standard packing verification workflow) because I've monkey patched/modified the contents of an unpacked package.

Scenario:

In the last couple days, I've had to download an older package of a package I control from NuGet.org and bump the version of a dependency, which is a nuspec metadata change. In doing so, we used unzip on windows and then zipped it right back up. Turns out Windows loves to URL Encode + in directory folders and we didn't notice.

Thus release 6.5.1 was a dud and we had to do 6.5.2 by repeating the process but using linux/mac host.

https://www.nuget.org/packages/reactiveui-core/6.5.1
https://www.nuget.org/packages/reactiveui-core/6.5.2

**Comment by nkolev92** [comment]
Thanks for filling this issue. 
Apologies for the long overdue reply.

At this point we're prioritizing other issues and we're not ready to invest in this space. 

Would be happy to take a second look if we get more engagement.

**Comment by melanchall** [comment]
Maybe now you're ready to implement this feature?
