### ISSUE TITLE
Integrate Restore3 into CLI

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3453]
This version of Restore3 does:
- Moves assets file to \obj from \obj\debug
- Rename props/targets
- Support packagereference (w/ Include/exclude/private assets)
- DG2 support
  - in dotnet.exe code path - (needs to support NetCore)
  - In nuget.exe code path - add support for NetCore projects via msbuild (for UWP Project.json or .NETCore projects)
  - In restorerunner
- Supports multitargeting

**Comment by emgarten** [comment]
Merged into CLI rel/1.0.0
