### ISSUE TITLE
Fix NuGet UI to support restore w/ PackageReferences in csproj

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3455]
Need solutions w/ packages.config, uwp style project.json or csproj (cps) with package references to be able to restore. Create intermediate DG2 file and pass to RestoreRunner.

In this step, we'll be creating the DG2 by asking msbuild /t:restore to create the DG2 file.
Longer term, but still in P5OOB, we'll be working with NugetRestoreManager to get info about CPS projects via the nomination process.

**Comment by joelverhagen** [comment]
Merged to `dev-msbuild` with https://github.com/NuGet/NuGet.Client/commit/bf2af74e48d174c0e97a3c41a93cf3aec5122aad.
