### ISSUE TITLE
Command help enable-migrations is not available

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#346]
Repro steps:
1.	Install package MvcScaffolding, through Package Manager Console
                 Install-Package MvcScaffolding
2.	Execute command "help enable-migrations" in console to verify help texts, here we got error.

error details:
PM> help enable-migrations
Get-Help : Get-Help could not find enable-migrations in a help file in this session. To download 
updated help topics type: "Update-Help". To get help online, search for the help topic in the 
TechNet library at http://go.microsoft.com/fwlink/?LinkID=107116.
At line:55 char:7
+       Get-Help @PSBoundParameters | more
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
+ FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand

**Comment by AndriySvyryd** [comment]
Enable-Migrations is part of the EntityFramework package starting with version 4.3
MvcScaffolding depends on EntityFramework 4.1, thus Enable-Migrations will not be available unless you update the EntityFramework package.
