### ISSUE TITLE
Problem with ASP Core running on traditional .NET Framework

### ISSUE THREAD

**Issue by greenplanet** [NuGet/Home#3460]
ASP.NET Core can be executed in .NET Core and traditional .NET environments. I am contributing to a library developer with 100,000+ installations. We provide the library for traditional ASP.NET projects as well as ASP.NET Core projects in a multi-targeting package.
Our library needs the HttpContext of the application, so we reference System.Web.dll for traditional ASP.NET applications and some Microsoft.AspNetCore.*.dll for Asp.NET Core apps.

These are currently our TFMs:

<pre>
package:
--lib/net40/Backload.dll                // .NET 4.0 with System.Web.dll
--lib/net451/Backload.dll               // .NET 4.5.1+ with System.Web.dll
--lib/netcoreapp1.0/Backload.dll        // .NET Core 1.0 with Microsoft.AspNetCore.*.dll
</pre>

When a **ASP.NET Core solution that runs on the full .NET Framework** installs this package, it references the 4.5.1 assembly which expects System.Web.HttpContext, while the application provides a Microsoft.AspNetCore.Http.HttpContext.

There must be a way (TFM?) that a package author for ASP.NET projects can mark an assembly to be used in traditional or new ASP.NET projects. Maybe just a flag like "useNetCore=true".

Another solution sometimes suggested is to create two separate Nuget packages. But this leads to a lot of confusion and we have to explain this over and over again (100,000+ installations). For example we already have two packages: A Backload (full functionality) and a Backload.Core package (for core functionality). What happens if we now change our strategy and assign the Backload package for traditional ASP.NET and the Backload.Core package for the ASP.NET Core environment?

NuGet resp. the project system have the information if an Asp.NET Core project runs on .NET Core or traditional .NET Framework. Why not just providing such a TFM or flag to the package?

Project:
[https://www.backload.org](https://www.backload.org/index.htm) and https://github.com/blackcity/backload

**Comment by nkolev92** [comment]
Apologies for the long overdue reply.

This is already supported by NuGet. 
NuGet selects the closest matching framework assets from each group. 
lib, ref, etc. 

So basically, if the target framework of the project is netcore, nuget will select only net core assets as those are the closest matching ones.
