### ISSUE TITLE
Is there a way to keep package version and AssemblyVersion in sync?

### ISSUE THREAD

**Issue by ivan-prodanov** [NuGet/Home#3461]
When using nuspec files, there's an option to set the version of the package from the assembly version / assembly informational version. How is this possible when using project.json? Is there a way to set package version from assembly version? How do we keep them in sync? 

I noticed a lot of libraries keep assembly version to be equal with the package version, but this I don't know how to do with a project.json file without manually editing them both. Isn't there another way?

**Comment by rrelyea** [comment]
I assume you are talking about Project.json for .NETCore?
If so, that is going away, and will be replaced with values in csproj. At that point, you won't have to keep two things in sync anymore.

**Comment by ivan-prodanov** [comment]
No, I'm asking for regular .NET .csproj files (not .NET Core, not UWP). There's an option for using project.json to both define the package and also list its NuGet dependencies instead of using a .nuspec file + keeping the NuGet as references in the .csproj. VS 2015 Update 2+ supports this for legacy .csproj files and NuGet 3.5 RC1 supports the 'version' field to be defined in the project.json, which is awesome.

Back to my question - I wrote a build vNext task that reads the 'version' from the project.json(NuGet v3.5 RC1+) and replaces all Assembly*Version attributes in the AssemblyInfo.cs file beneath the .csproj's directory with it. It does what it's supposed to do - keep the assembly version in sync with its package's version. But are there any plans to facilitate what I'm trying to achieve in future versions of NuGet?

P.S I'm aware about the NETCore situation, but project.json isn't going away for NuGet packages and .csproj files, right? I'm using 3.5 RC1 and am quite happy with it. Defining NuGet dependencies in the project.json and package metadata is awesome. This won't go away, am I correct?

P.S 2. I can edit this question and make it a feature request if you desire. I just don't know what the situation is - whether this already exists or it's planned for future versions or it's just plain wrong in its current form.
