### ISSUE TITLE
Restore3 for a RID

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3465]
msbuild /t:restore /p:runtimeIdentifier=win7-x86

/cc @eerhardt

**Comment by emgarten** [comment]
I've added support for reading RIDs from property: _RuntimeIdentifiers_

Since this allows for multiple RIDs I've made it plural, this also matches TargetFrameworks.

The property may be defined in the project file or passed in from the command line.

https://github.com/NuGet/NuGet.Client/commit/01453ff9d2fa066b97ed53c85f127c7ca3b337da

**Comment by eerhardt** [comment]
@emgarten - I'm not fully understanding the "RuntimeSupports" property.  If I just pass in `<RuntimeIdentifiers>win10-x64</>`, will NuGet still restore all the correct packages without me setting `<RuntimeSupports>`?

In project.json today, a user only needs to list `win10-x64` in the "runtimes" section, and all the packages get restored correct, even if that means falling back to `win7-x64` packages.

**Comment by eerhardt** [comment]
Also, since "RuntimeIdentifiers" is plural, I can pass `win10-x64;osx.10.11-x64` to restore for both RIDs.  How does "RuntimeSupports" map into that list? How would I say "these 3 RIDs map to win10-x64 and these other 2 RIDs map to osx.10.11-x64"?

**Comment by emgarten** [comment]
@eerhardt _RuntimeSupports_ is equivalent to the _Supports_ section in project.json. Supports performs additional restores, usually just on a TFM and then checks compatibility. So if for example of you are building a netstandard library you can add supports for net462 to verify that it can be installed there. Supports has zero impact on the resulting assets file, it can only cause errors. It is also referred to as guard rails.
