### ISSUE TITLE
Unable to uninstall package in VS UI if package source not selected

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3466]
VS version 25715.01, NuGet version 3.6.0.1821 (not a regression from 3.5, however)
- Install a package.
- Select a different source in the Package source dropdown, somewhere where this installed package doesn't live
- There is no uninstall option for the package

i.e. Unless you know from where your package is installed, you can't uninstall it in the VS UI.

**Comment by drewgillies** [comment]
This is somewhat bogus. While this is an accurate description of the experience on the Browse tab, the Installed tab gives an uninstallation route.

**Comment by drewgillies** [comment]
Reopening after discussing with @rrelyea. It's worth ensuring that we're happy with the design here. Briefly:
- On the Browse tab, even though there's an uninstall button, there's no way to enable that button for an installed package (even with its name in the search box) without that package being discovered in the source/s chosen--so if you don't know the source, you can't uninstall here, even though there's an uninstall button
- On the Installed tab, we can simply select the package and uninstall.

**Comment by drewgillies** [comment]
Setting as P2 as we have no P3. ;-)

**Comment by nkolev92** [comment]
This would need to be part of a comprehensive UI redesign, for which we have relevant issues. 
With Package Reference a lot of these things would not be looked at from a different perspective.

Closing it now.
