### ISSUE TITLE
[validation] Crash after authenticating a private v2 MyGet feed and clicking "Show x more results"

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/Home#3469]
VS version 25715.01, NuGet version 3.6.0.1821
- Create a private MyGet feed. Add a package to the feed.
- Add the v2 unauthenticated version feed as package source in VS.
- Wait for the password prompt. Click "Remember me" and input the username and password for the feed.
- Observe:

![packages found](https://cloud.githubusercontent.com/assets/18014088/18645084/aa2ba432-7e60-11e6-9389-101bc0592539.png)
- Click "Show x more results".
- Observe: the program crashes.
- Reopen VS.
- Note that the password prompt appears again when it should remember you. Re-enter credentials.
- Click "Show x more results" again.
- Observe: the program crashes again.

Did not get this to repro on VS 2015 Update 3, NuGet 3.4.4.

**Comment by zhili1208** [comment]
the issue is from this commit https://github.com/NuGet/NuGet.Client/commit/86ec4b29ec5ddea7dc08294ddd9054a3a4e1a4c4
it's not about credentials, the problem is UpdatePackageList() cause deadlock.
@jainaashish
