### ISSUE TITLE
Open a SL4 class library project in Dev14, migrate report doesn’t show upgrade error

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#347]
Repro steps:
Open SL4 class library project in Dev14

Expected results: migrate report show upgrade error related to NuGet packages(the first pic)
Actual results: no upgrade error (the second pic)
![expectshowupgradeerror](https://cloud.githubusercontent.com/assets/11768961/6964441/b8da41e0-d97b-11e4-8f84-df98a12c361b.PNG)
![actualnoupgradeerror](https://cloud.githubusercontent.com/assets/11768961/6964444/bea9fe8a-d97b-11e4-99b3-e2370435def0.PNG)

**Comment by deepakaravindr** [comment]
@danliu will take care of this

**Comment by danliu** [comment]
Fixed via https://github.com/NuGet/NuGet.VisualStudioExtension/commit/675c5d8e28493eaa2576e9b6d609f691d346af27
