### ISSUE TITLE
[validation] Browsing Klondike server from VS UI gives errors

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3470]
Error is:
Unable to retrieve results from one or more sources: Klondike. Error in out put is as follows:
  GET https://api.nuget.org/v3/registration1-gz/entityframework/index.json
  GET http://klondikeserver:8081/nuget/nuget/Packages(Id='EntityFramework',Version='6.1.3')
  OK http://klondikeserver:8081/nuget/nuget/Packages(Id='EntityFramework',Version='6.1.3') 5ms
  OK https://api.nuget.org/v3/registration1-gz/entityframework/index.json 65ms
Error finding repository for 'http://klondikeserver:8081/nuget/nuget': An error occurred while retrieving package metadata for 'EntityFramework.6.1.3' from source 'Klondike'.
  The 'link' start tag on line 14 position 6 does not match the end tag of 'head'. Line 17, position 5.
Restoring packages for 'App1'.
Restoring packages for c:\Users\drewgil\Documents\Visual Studio 15\Projects\App1\App1\project.json...
  GET https://api.nuget.org/v3-flatcontainer/entityframework/index.json
  GET http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'
  OK http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework' 4ms
Retrying 'FindPackagesByIdAsyncCore' for source 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework''.
The content at 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'' is not valid XML.
  For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
  GET http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'
  OK http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework' 5ms
Retrying 'FindPackagesByIdAsyncCore' for source 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework''.
The content at 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'' is not valid XML.
  For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
  GET http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'
  OK http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework' 4ms
Failed to retrieve information from remote source 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework''.
The content at 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'' is not valid XML.
  OK https://api.nuget.org/v3-flatcontainer/entityframework/index.json 123ms
  GET https://api.nuget.org/v3-flatcontainer/entityframework/6.1.3/entityframework.6.1.3.nupkg
Failed to retrieve information from remote source 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework''.
  The content at 'http://klondikeserver:8081/nuget/nuget/FindPackagesById()?id='EntityFramework'' is not valid XML.
  For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
========== Finished ==========
  OK https://api.nuget.org/v3-flatcontainer/entityframework/6.1.3/entityframework.6.1.3.nupkg 232ms
Time Elapsed: 00:00:01.1913901
[Klondike] The 'link' start tag on line 14 position 6 does not match the end tag of 'head'. Line 17, position 5.

**Comment by drewgillies** [comment]
VS version: 25715.01, NuGet version 3.6.0.1821

**Comment by yishaigalatzer** [comment]
Couple of questions to @drewgil 
1. can you compare to 3.4.4 ?
2. We should have these tests automated
3. We should have this work without the nuget.org feed

**Comment by drewgillies** [comment]
Closing this--there was a URL transcription error. In response to 2., I agree--let's look at how to make this happen. 3. we can discuss offline.
