### ISSUE TITLE
PMC said ‘No packages installed’ with command ‘Get-Package Updates’ even after several packages are installed

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3473]
**Repro Steps:**
1.  Click File -> New project -> Visual C# -> Web -> ASP.NET Web Application, then uncheck the box for "Application Insights".
2.  Click Web Forms template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Open ‘Package Manager Console’ and ‘Manage NuGet Packages…’.
5.  Click ‘Installed’ tab in PM UI and type command **‘Get-Package Updates’** in PMC.

**Expected Result:**
PMC would say the command is invalid, and the correct command should be 'Get-Package -Updates’.

**Actual Result:**
PMC said ‘No packages installed’, actually you can see in PM UI that there are several packages installed as below screenshot. So the information is wrong.
![nopackageinstalled](https://cloud.githubusercontent.com/assets/20632625/18661988/d4fb55b4-7f4a-11e6-9d70-00da3735560e.png)
**Note:**
1.  It was found on Dev14U3 + MicroUpdate3.5 (With NuGet 3.4.4.1321 in VS).
2.  It doesn’t repro on Dev14 U3 + MicroUpdate3.5 + NuGet 3.5.0-RTM-1846.

**Comment by rrelyea** [comment]
Please compare this result with 3.4.4.1321 and Dev14U3 (but no microupdate).
(is microupdate causing the problem, or did it exist with 3.4.4.1321 and U3)

**Comment by v-luzh** [comment]
@rrelyea It **doesn't repro** on Dev14U3 25425.01 (with NuGet 3.4.4.1321 in it, without microupdate). But it **repro** on **_Dev15 Preview 25719.02 (NuGet 3.6.0.1821_)**，**_Dev15 Preview 25719.02 + NuGet 3.6.0-xprivate-2004_** and **_Dev15 Preview 25721.01+ NuGet dev-msbuild 3.6.0-xprivate-2028_**.

**Comment by nkolev92** [comment]
@v-luzh Is this still reproducible in VS 2017?

**Comment by v-luzh** [comment]
It still repro on Master\30001.138 + NuGet Client Dev\5.6.0.6555.

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
The command is `Get-Package -Updates` by running `Get-Package Updates` you are setting the filter as "Updates" since you have no packages with that name it says no packages installed.
