### ISSUE TITLE
docs.nuget.org has invalid HTTPS certificate

### ISSUE THREAD

**Issue by svick** [NuGet/Home#3475]
When I open https://docs.nuget.org/ in Firefox, I get the following error:

> Your connection is not secure
> 
> The owner of docs.nuget.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
> 
> docs.nuget.org uses an invalid security certificate.
> 
> The certificate is only valid for the following names: *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net
> 
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by maartenba** [comment]
This has now been fixed. Can you verify things are as expected now?

**Comment by svick** [comment]
Yeah, it works for me now.
