### ISSUE TITLE
Docs incorrectly state that NuGet silently ignores invalid NuGet.Config xml

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/Home#3478]
https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior

`Although you can modify the file in any text editor, NuGet silently ignores the entire configuration file if it contains malformed XML (mismatched tags, invalid quotation marks, etc.).`

This is not true and has been changed intentionally. These docs should change.

![nuget config is not valid xml](https://cloud.githubusercontent.com/assets/18014088/18681862/b4c1abee-7f1e-11e6-84b1-5423cc98a8cf.png)

**Comment by rrelyea** [comment]
3.4.3 is the version that we made this change to fix https://github.com/NuGet/Home/issues/2158

**Comment by karann-msft** [comment]
updated docs to reflect the NuGet version this change was made.
