### ISSUE TITLE
NuGet packaging hangs if content folder contains too many files

### ISSUE THREAD

**Issue by neurospeech** [NuGet/Home#348]
Checked and verified, till 55 content files NuGet had no problem, but when we reached 65 content files, NuGet hangs and does not create new package.

**Comment by ChrisSfanos** [comment]
Can you please provide specific repro steps, specifically the command you ran and the types/sizes of the files you are using to generate the package

**Comment by ChrisSfanos** [comment]
If you've uploaded the package to NuGet, please send us the link

**Comment by neurospeech** [comment]
I have this repository, https://github.com/neurospeech/atoms.js which contains "nuget/Atoms.js" folder. And you can see nuget specs.

https://github.com/neurospeech/atoms.js/blob/master/nuget/Atoms.js/Package.nuspec

Inside "style" folder of my repository root, I have style sheets that are included in nuget package. But it looks like, if I add more LESS files, NuGet packager halts completely if there are more than current number of files.

https://github.com/neurospeech/atoms.js/tree/master/style

I had added 5 more LESS files, and I noticed the problem. Eventually, we combined all LESS files into one Unsorted.less file, that reduced total number of files, and we were able to build package.

**Comment by thomerow** [comment]
Has there been any progress on this? Today I ran into the same problem. If the number of files is greater than a certain number (49 in my case – the file sizes don't seem to matter), `nuget.exe pack` never exits.

**Comment by yishaigalatzer** [comment]
We haven't made much progress on this unfortunately. We plan to refactor pack to stop using OPC, and hopefully that should also resolve this issue.

**Comment by emgarten** [comment]
@toddm would you check if this repros in 3.5.0?

**Comment by toddm** [comment]
I cloned the repo, added 10 more css files, and did a pack with 3.5.0 and it worked without any problem.
