### ISSUE TITLE
Installing packages takes a very long time in Package Manager Console

### ISSUE THREAD

**Issue by emphasis87** [NuGet/Home#3480]
I just ran a command `Update-Package -reinstall -project <myproject>` to repair dependencies to 8 packages and It took a very long time to complete, almost 20 minutes. The same goes for `Install-Package` command. I am not really sure what goes on but it should have been over in seconds. I have noticed this behaviour perhaps for a month. I use VS 2015 community eidtion, version 14.0.25431.01 Update 3 and Nuget Package Manager 3.5.0, if it is of any help.

**Comment by nkolev92** [comment]
Reinstall is a heavy operation that involves a lot of IO and in packages.config means installation of a lot install/uninstall.ps1 scripts. 

We have made improvements in the performance in that area. 

Please try out the latest VS 2017 release and please do create another issue if you're still facing performance problems.
