### ISSUE TITLE
Update Solution Packages is VERY slow and vs is frozen

### ISSUE THREAD

**Issue by valeriob** [NuGet/Home#3485]
Hi,
i tried to upgrade 4 packages in a solution with 20 projects, and it took 21 minutes... after 4 hours of trying thinking it was hanging because visual studio was unresponsive....

Nuget 3.5.1737
Vs 2015 update 3
[nuget_solution_update.txt](https://github.com/NuGet/Home/files/484344/nuget_solution_update.txt)

Thanks.

**Comment by yishaigalatzer** [comment]
@valeriob thanks for reporting the issue. Can you clarify what do you mean by 4 hours?

Also can you tell us if you are using Resharper?

@jainaashish will take over from here.

**Comment by valeriob** [comment]
@yishaigalatzer sorry for deceiving you, i just meant that i've beeing trying to do that for hours. Not having the patience to wait for the process to finish 😄

**Comment by jainaashish** [comment]
@valeriob is it possible for you to share a small repro solution which takes this 20 mins to update these packages? I tried to repro it with the help of your logs but it's pretty fast in my case.

**Comment by valeriob** [comment]
I've been updating some more dependencies lately, and i've noticed that it happens on a specific web project, i could isolate the problem to the extension https://github.com/madskristensen/BundlerMinifier, if it's enabled Procmon shows a lot of activity around bundle files.
Sorry for bothering, i was sure to have made the test without that extension ! I think i forgot to restart visual studio 😄

**Comment by jainaashish** [comment]
Related external issue https://github.com/madskristensen/BundlerMinifier/issues/205

**Comment by jainaashish** [comment]
Closing as external
