### ISSUE TITLE
[Test Failure] Could not find the full path of reference ‘System.ValueTuple’ after creating F# ConsoleApplication template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3486]
**Repro Steps:**
1.  New a project (F# ConsoleApplication template).
2.  Expand ‘References’ node in Solution Explorer.
3.  Right-click ‘System.ValueTuple’ and look at the full path of it in ‘Properties’.

**Expected Result:**
There is no yellow warning icon on the reference and the full path is not empty.

**Actual Result:**
There is a yellow warning icon on the reference and the full path is empty as below screenshot.
![systemvaluetuple](https://cloud.githubusercontent.com/assets/20632625/18704195/9b5b26e6-801b-11e6-912f-6744be7bd48a.png)
**Note:**
1.  It found on Dev15 Preview 25719.02 (NuGet 3.6.0-Beta1-1821).
2.  It repro on Dev15 Preview 25719.02 + NuGet 3.6.0-xprivate-2004.
3.  It doesn’t repro on Dev14 Microupdate3.5 25431.01 (NuGet 3.4.4.1321).
4.  It doesn’t repro on Dev14 U3 25425.01 (NuGet 3.4.4.1321).
5.  It doesn’t repro on Dev14 U3 25425.01 + NuGet 3.5.0-RTM-1846.

**Comment by rrelyea** [comment]
Found as part of validation of your private build. Your fix, or just a regression in dev?

**Comment by joelverhagen** [comment]
From what I can tell, the `System.ValueTuple` is a new package dependency for the F# template. Dev14 U3 does not have this dependency at all. The Dev15 template simply has a .fsproj and packages.config with this dependency, meaning that NuGet does not have a change to restore this package when the user does File > New Project. When you build this project for the first time, the yellow "alert" disappears and the build completes successfully.

**Comment by joelverhagen** [comment]
I will reach out to the template owner to determine the proper course of action. My thought here is that the template should call one of the NuGet `InstallPackage*` APIs during project creation to install (and therefore restore) this package.

**Comment by joelverhagen** [comment]
This is an issue with the F# project template:
https://github.com/Microsoft/visualfsharp/issues/1558

Closed as external.
