### ISSUE TITLE
Assemblies are not properly referred from NuGet

### ISSUE THREAD

**Issue by Kanimozhi12** [NuGet/Home#3487]
Hi,

I have faced the following issue with NuGet.

Case 1:
1. Added some references from GAC to the project.
2. Due to some reasons installed the NuGet which contains the patch assemblies ,which i referred from GAC before.
3. The path of the reference is still GAC location not the NuGet packages location.

Case 2:
1. Created fresh project
2. Installed NuGet
3. reference path is set to GAC not the NuGet packages location
4. Once i refresh the project, the path get changed to packages location

Why this is happening?

**Comment by yishaigalatzer** [comment]
Can you share the exact entries you are referring to (xml from the csproj),  and what/where do you see stuff being picked up from.

Also what is the version of visual studio (include update level) and what is the version of NuGet.

I believe this is a common issue with how msbuild picks up references, but I want to be sure.

CC @davkean

**Comment by Kanimozhi12** [comment]
@yishaigalatzer
I have added Assembly "X" to my project using NuGet.
1. In my .csproj the hint path of Assembly X is set to NuGet packages location
2. While checking from my Visual Studio-> References-> Properties the  path of Assembly X is set to GAC location
3. Visual Studio Version is VS2015

**Comment by yishaigalatzer** [comment]
This is a bug in msbuild that was the supposed to be fixed already. Can you make sure you are on update 3?

**Comment by yishaigalatzer** [comment]
Also is assembly x in the GAC with the exact same strong name version or a different one? It will be very helpful if you included a concrete sample here.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
