### ISSUE TITLE
Sticky References!

### ISSUE THREAD

**Issue by abhidotnet** [NuGet/Home#3488]
This is an issue which I have dubbed "sticky references". I am adding a package. in this case Microsoft.WebApi from Nuget. There is a similar package in the GAC. The assembly that is being referenced in System.Web

When I add the package, my expectation is that the VS 2015 will stop referencing the System.Web from GAC and reference the one that is part of this package.

This does not happen. I have to add the reference to the downloaded assembly as the existing referenced assembly stays **STUCK** in the project.

**Comment by yishaigalatzer** [comment]
1. What version of VS 2015 and NuGet are you using
2. Can you share the actual reference added in your case?

**Comment by yishaigalatzer** [comment]
CC @davkean

**Comment by abhidotnet** [comment]
I am using Visual Studio 2015 Professional Edition - version 14.0.25431.01 Update 3
Nuget Version is 3.5.0
Operating system is Windows 7 64 bit.

**Comment by yishaigalatzer** [comment]
Thanks, can you also paste the actual entries from the csproj you are concerned with?

**Comment by dsplaisted** [comment]
> my expectation is that the VS 2015 will stop referencing the System.Web from GAC and reference the one that is part of this package.

Do you mean that you expect that the DLL will be copied to the output folder during the build (and it's not happening), that at runtime you expect the DLL to be loaded from the output folder instead of the GAC, or something else?

Also, I don't see a Microsoft.WebApi NuGet package.  Are you referring to [Microsoft.AspNet.WebApi.Core](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Core/)?

**Comment by abhidotnet** [comment]
I expect the DLL to be referenced in my project. I don't expect it to be a part of the output folder.
I am referring to the Microsoft.AspNet.WebApi Dll.

**Comment by yishaigalatzer** [comment]
@abhidotnet it will be really helpful if you can provide a clear picture of what exactly is that you are doing
1. What assembly is in the GAC, and what version
2. What package are you installing including what version

Preferrably walk us through the process step by step, and show what the entry in the csproj looks like at the end of the process.

**Comment by PatoBeltran** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
