### ISSUE TITLE
NuGet v3.4 not requesting full version on restore when normalized version results in 404

### ISSUE THREAD

**Issue by dmeyer573** [NuGet/Home#3492]
I am using the latest version of NuGet packaged with Visual Studio 2015 Update 3 (3.4.4.1321). When I attempt to restore packages from my internal NuGet feed (hosted in ProGet) I get the following error message on some of my packages, "Unable to find version '5.1.0' of package 'MyPackageName'". The portion of the error log showing the attempt to find the package on my internal feed shows the message, "The V2 feed at 'http://packages.ipcommerce.com/nuget/components/FindPackagesById()?id='MyPackageName'' returned an unexpected status code '404 Not Found'". The actual version of the package being restored is '5.1.0.0'. This issue seems similar to the one documented here: https://github.com/NuGet/Home/issues/2298. This issue is only occurring with my packages that have a version ending with .0.0. This functionality works using NuGet v3.3. My understanding based on the previous ticket I referenced is that v5.1 == v5.1.0.0. NuGet should detect the 404 being returned from ProGet and then attempt the 5.1.0.0 version as well. Please let me know if my assumption is correct and what I can do to resolve this issue. I'm happy to provide any additional information that would be helpful in understanding what's going on here.

Thank you!

**Comment by yishaigalatzer** [comment]
Hey @dmeyer573: We do not want to introduce extra calls to the server that will delay the most common case for users.

The reason proget returns 404 is that some of (very old projects) treat 5.1.0 differently than 5.1.0.0, that is not supported and we won't make it work again in NuGet.

Our recommendation is as follows
1. Use semver (5.1.0) rather than 4 numbers so 5.1.0 rather than 5.1.0.0
2. Contact @apapadimoulis from ProGet to figure out how to get a version that supports reading the normalized versions like most other servers do.

**Comment by dmeyer573** [comment]
Yishai,

Thank you for your quick response. I will consider the options you have provided. I’m sure we will find one of them suitable.

Thank you!

Derek Meyer
Director of Engineering

o. 303.357.5115 | m. 720.350.5768 | commercesync.comhttp://commercesync.com/

[http://commercesync.com/assets/emailsig/commsync_logo.png]http://commercesync.com/

[http://commercesync.com/assets/emailsig/FB.png]https://www.facebook.com/CommerceSync[http://commercesync.com/assets/emailsig/TW.png]https://twitter.com/CommerceSync[http://commercesync.com/assets/emailsig/LI.png]https://www.linkedin.com/company/commerce-sync

**Comment by apxltd** [comment]
I thought this was already addressed in NuGet Client 3.4?

"If we get a 404 we will get all versions of the packages and pick it from there"

**Comment by dmeyer573** [comment]
For documentation's sake, we are using ProGet version 2.1.4. We have plans to update this to the latest version (4.3.1) for other reasons. I'm happy to report back if this changes the issue in any way; however, it likely won't happen for at least a couple of weeks. Additionally, I am happy to provide any additional information that might be helpful.

**Comment by apxltd** [comment]
Oh my. Yeah, you should definitely upgrade. I'm surprised it still works.

**Comment by dmeyer573** [comment]
Agreed. That being said, it has served us well for years. Thanks!

**Comment by yishaigalatzer** [comment]
@dmeyer573 @apapadimoulis closing as I think this is resolved. Feel free to continue the discussion if I missed something.
