### ISSUE TITLE
Restore3 is looking for _SplitProjectReferences in the outer build

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3493]
I am working on getting a repro right now, but this was reported by @nguerrera.

/cc @rrelyea 

_edit: added repro steps and such_
## Repro steps
1. Download latest rel/1.0.0 CLI: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip
2. Download `Microsoft.Common.CrossTargeting.targets` from @nguerrera's commit: https://raw.githubusercontent.com/Microsoft/msbuild/93f8c8a50b1586e27cb93ed92f6910df4fcba29f/src/XMakeTasks/Microsoft.Common.CrossTargeting.targets (uploaded for posterity: 
   [Microsoft.Common.CrossTargeting.targets.zip](https://github.com/NuGet/Home/files/487923/Microsoft.Common.CrossTargeting.targets.zip))
3. Replace all instances of the `Microsoft.Common.CrossTargeting.targets` file in the downloaded CLI (I found two instances under the `sdk` directory).
4. Run `dotnet restore3` on this .csproj: [TestLibrary.zip](https://github.com/NuGet/Home/files/487918/TestLibrary.zip)
## Expected

The restore should complete successfully.
## Actual

Restore failure:

<pre>
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/21/2016 5:47:38 PM.
Project "C:\trash\nick\project\ClassLibrary3.csproj" on node 1 (Restore target(s)).
Building with tools version "15.0".
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
Target "_LoadRestoreGraphEntryPoints" in file "C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets" from project "C:\trash\nick\project\ClassLibrary3.csproj" (target "_GenerateRestoreGraph" depends on it):
Done building target "_LoadRestoreGraphEntryPoints" in project "ClassLibrary3.csproj".
Target "_GenerateRestoreGraph" in file "C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets" from project "C:\trash\nick\project\ClassLibrary3.csproj" (target "Restore" depends on it):
Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "Message"
  Generating dg file
Done executing task "Message".
Task "Message"
  C:\trash\nick\project\ClassLibrary3.csproj
Done executing task "Message".
Using "MsBuild" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "MsBuild"
  Global Properties:
    CustomAfterMicrosoftCommonTargets=C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets
    BuildProjectReferences=false
Project "C:\trash\nick\project\ClassLibrary3.csproj" (1) is building "C:\trash\nick\project\ClassLibrary3.csproj" (1:2) on node 1 (_GenerateRestoreSpecs target(s)).
Building with tools version "15.0".
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
<b>C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets(125,7): error MSB4057: The target "_SplitProjectReferencesByFileExistence" does not exist in the project. [C:\trash\nick\project\ClassLibrary3.csproj]</b>
Done Building Project "C:\trash\nick\project\ClassLibrary3.csproj" (_GenerateRestoreSpecs target(s)) -- FAILED.

Done executing task "MsBuild" -- FAILED.
Done building target "_GenerateRestoreGraph" in project "ClassLibrary3.csproj" -- FAILED.
Done Building Project "C:\trash\nick\project\ClassLibrary3.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

"C:\trash\nick\project\ClassLibrary3.csproj" (Restore target) (1) ->
"C:\trash\nick\project\ClassLibrary3.csproj" (_GenerateRestoreSpecs target) (1:2) ->
  C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets(125,7): error MSB4057: The target "_SplitProjectReferencesByFileExistence" does not exist in the project. [C:\trash\nick\project\ClassLibrary3.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.32
</pre>

**Comment by joelverhagen** [comment]
The full failure I am seeing is:

<pre>
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 9/21/2016 5:47:38 PM.
Project "C:\trash\nick\project\ClassLibrary3.csproj" on node 1 (Restore target(s)).
Building with tools version "15.0".
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
Target "_LoadRestoreGraphEntryPoints" in file "C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets" from project "C:\trash\nick\project\ClassLibrary3.csproj" (target "_GenerateRestoreGraph" depends on it):
Done building target "_LoadRestoreGraphEntryPoints" in project "ClassLibrary3.csproj".
Target "_GenerateRestoreGraph" in file "C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets" from project "C:\trash\nick\project\ClassLibrary3.csproj" (target "Restore" depends on it):
Using "Message" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "Message"
  Generating dg file
Done executing task "Message".
Task "Message"
  C:\trash\nick\project\ClassLibrary3.csproj
Done executing task "Message".
Using "MsBuild" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
Task "MsBuild"
  Global Properties:
    CustomAfterMicrosoftCommonTargets=C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets
    BuildProjectReferences=false
Project "C:\trash\nick\project\ClassLibrary3.csproj" (1) is building "C:\trash\nick\project\ClassLibrary3.csproj" (1:2) on node 1 (_GenerateRestoreSpecs target(s)).
Building with tools version "15.0".
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="15.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=293424.
<b>C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets(125,7): error MSB4057: The target "_SplitProjectReferencesByFileExistence" does not exist in the project. [C:\trash\nick\project\ClassLibrary3.csproj]</b>
Done Building Project "C:\trash\nick\project\ClassLibrary3.csproj" (_GenerateRestoreSpecs target(s)) -- FAILED.

Done executing task "MsBuild" -- FAILED.
Done building target "_GenerateRestoreGraph" in project "ClassLibrary3.csproj" -- FAILED.
Done Building Project "C:\trash\nick\project\ClassLibrary3.csproj" (Restore target(s)) -- FAILED.


Build FAILED.

"C:\trash\nick\project\ClassLibrary3.csproj" (Restore target) (1) ->
"C:\trash\nick\project\ClassLibrary3.csproj" (_GenerateRestoreSpecs target) (1:2) ->
  C:\trash\nick\dotnet-dev-win-x64.latest\sdk\1.0.0-preview3-003618\NuGet.targets(125,7): error MSB4057: The target "_SplitProjectReferencesByFileExistence" does not exist in the project. [C:\trash\nick\project\ClassLibrary3.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.32
</pre>

**Comment by emgarten** [comment]
These extra dependencies were not needed in the outer loop, I've removed them.

NuGet/NuGet.Client@7b45b1fb590a2eb9e835246e5e88b08d23cc0ff5
