### ISSUE TITLE
NuGet Restore support for PackageTargetFallback (f.k.a Imports)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3494]
Design posted: https://github.com/NuGet/Home/wiki/PackageTargetFallback-(new-design-for-Imports)

**Comment by rrelyea** [comment]
cc: @davidfowl

**Comment by brthor** [comment]
Is there a straw man for tool imports?

**Comment by emgarten** [comment]
@brthor can you share the id/versions of any tools that you know of that still require imports?

**Comment by brthor** [comment]
Perhaps @mlorbetske knows? You were mentioning a couple in the monday sync.

**Comment by mlorbetske** [comment]
Microsoft.composition 1.0.27 is the one we were discussing earlier
