### ISSUE TITLE
Generated restore props and targets need cross-targeting participation support

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#3496]
Quoting @srivatsn:

> Currently the way Microsoft.Common.CrossTargeting.targets finds the target to implement is through a property (CoreCrossTargetingTargetsPath) which is set in the SDK.props file to point to a file which contains the Build target that loops over TFMs. However, restore3 now generates a TFM specific props file. That is, the generated Consoleapp.nuget.g.props file looks like this:

``` XML
  <ImportGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.sdk\1.0.0-alpha-00000001-01\build\netstandard1.0\Microsoft.NETCore.Sdk.props"
                  Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.sdk\1.0.0-alpha-00000001-01\build\netstandard1.0\Microsoft.NETCore.Sdk.props')" />
  </ImportGroup>
```

> When this is imported in the outer build, TargetFramework is not set and so the props don’t get imported which means CoreCrossTargetingTargetsPath is not set. So in Microsoft.Common.CrossTargeting.targets, nothing gets imported. @Nick and I’ve discussed an approach before which, if present, could solve this problem. Essentially, if we have a convention for a place for cross-targeting props & targets similar to the current convention for TFMs (say a folder called build\cross) then restore could generate a section in the props\targets specific to the outer build.
> 
> So for example if a package had
> 
> ```
> Build
>         | cross | foo.props, 
>         | netstandard1.0 | foo.props
> ```
> 
> Then the consoleapp.nuget.g.props (and similarly targets) would look like

``` XML
  <ImportGroup Condition=" '$(IsCrossTargetingBuild)' == 'true' ">
    <Import Project="…..\build\cross\foo.props" />
  </ImportGroup>

  <ImportGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">
    <Import Project="…..\build\netstandard10\foo.props " />
  </ImportGroup>
```

**Comment by rrelyea** [comment]
Our plan: 
Nupkg needs to support \buildCrossTargeting\ folder - and import .targets/.props for "crosstargeting" msbuild scope

**Comment by emgarten** [comment]
https://github.com/NuGet/NuGet.Client/commit/9b3a460712c2c881f6ad120b822d2328688aefec

Use `buildCrossTargeting/{packageId}.targets` and `buildCrossTargeting/{packageId}.props`
