### ISSUE TITLE
Is it possible to include content files through a nuspec w/o installing them to a project. If not what is an appropriate mechanism for adding files to a nuget package w/o necessarily installing them?

### ISSUE THREAD

**Issue by maxgax** [NuGet/Home#3497]

**Comment by yishaigalatzer** [comment]
All depends on what you are trying to achieve. If you want files to exist in the package, get unpacked next to the package, but not get added to the project you can put them in a folder that is not one of the known folders affecting the project (lib/ref/content/contentfiles etc.).

It really depends on what you are trying to achieve, but for example you can look at the [EntityFramework](https://www.nuget.org/packages/EntityFramework/6.1.3) package. They put files that can be used by their scripts next to them. They don't get picked up or added to the project. Others have used their own top level folders that just get ignored.

@karann-msft we should add this to docs so we can just point to it in the future.

@maxgax for questions we recommend using stackoverflow so more people can find the answer easily.

**Comment by yishaigalatzer** [comment]
@karann-msft please triage if you think this is worth a doc entry, go ahead make it and then close this bug. Otherwise just go ahead and close it.
