### ISSUE TITLE
Restore3 fails to resolve a P2P ref

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#3501]
I am trying to run restore3 on a project like this:
- There’a TestApp.csproj which is targeting NETCoreApp 1.0 and still uses project.json for dependencies (no TargetFrameworks property in the csproj). 
- This has a `<ProjectReference Include=”..\TestLibrary\TestLibrary.csproj” />`
- The TestLibray targets netstandard1.5 (again project.json – no TargetFrameworks)

restore3 fails for this project saying it is unable to resolve the P2P for .NETCoreApp 1.0. This is the error from the log:

```
  Unable to resolve 'C:\sdk\bin\Debug\Tests\It_builds_the_project_successfully\AppWithLibrary\TestLibrary\TestLibrary.csproj' for '.NETCoreApp,Version=v1.0'.
```

**Comment by emgarten** [comment]
https://github.com/NuGet/NuGet.Client/commit/192818520df9d8a165d9ae0e2a24ed7c803f3def
