### ISSUE TITLE
Restore3 imports NuGet.targets twice

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#3502]
When running restore3 on a project, this msbuild warning is emitted:

```
C:\sdk\.dotnet_cli\sdk\1.0.0-preview3-003618\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(22,3): warning MSB4011: "C:\sdk\.dotnet_cli\sdk\1.0.0-preview3-003618\NuGet.targets" cannot be imported again. It was already imported at "C:\sdk\.dotnet_cli\sdk\1.0.0-preview3-003618\Microsoft.Common.CurrentVersion.targets (5585,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\sdk\bin\Debug\Tests\It_builds_the_project_successfully\AppWithLibrary\TestApp\TestApp.csproj]
```

**Comment by rrelyea** [comment]
Is this our fix, or msbuild's?

**Comment by emgarten** [comment]
This appears to be coming from NuGet's use of custom import after targets. My current plan is to add a property to enable/disable this. By default it will be off, and in NuGet.exe where it is needed and the output is not displayed to the user, the extra import will be turned on.

**Comment by emgarten** [comment]
This should be fixed in the latest NuGet.targets, I'll leave this open until it has been validated everywhere.

**Comment by rrelyea** [comment]
We just got a report in email today, think i included @mishra14  - please follow up and find that repro, which may be different than described above.

**Comment by mishra14** [comment]
@rrelyea, @emgarten: verified that this is fixed in the latest CI build.
