### ISSUE TITLE
Restore3 couples PackageReferences with TargetFrameworks.

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#3504]
Restore3 today only looks for PackageReference items in a project if the project has the TargetFrameworks property. While that is being used as a proxy for core projects, that introduces unwanted coupling. For eg, to enable packagereferences in UWP projects we will need to introduce this property there.

My proposal for restore3 behavior is:
Look for the existence of a project.json and if it exists, go into project.json mode. Otherwise assume that the project has PackageReferences. That also leads to the behavior that post Dev15, if someone creates a new project, PackageReference will be the default.

**Comment by nguerrera** [comment]
We also need to address this (quoting @srivatsn) when supporting a project with only `TargetFramework` singular:

> There’s another issue I mentioned to Nick yesterday. NuGet today generates a projectName.NuGet.props file which imports props from packages conditioned on TargetFramework.
> 
> However, we would normally define TargetFramework after importing Common.props (which would pull in the projectName.NuGet.props through the MSBuildProjectExtensionsPath mechanism). So if we just have TargetFramework, then props files from packages won’t get imported.
> 
> One solution could be that if there’s just a TargetFramework, then the generated props\targets could unconditionally import the props\targets for that TargetFramework.

+1 to the suggested solution.

**Comment by nguerrera** [comment]
It is also worth noting that we have a related problem for props in buildCrossTargeting: #3532. Fixing the issue for single TargetFramework is much higher priority, but it might help to think about the general problem while fixing this.

**Comment by emgarten** [comment]
@nguerrera would you open a different issue for tracking the use of TargetFramework in the imports targets/props with an explanation of what is expected there.

This issue relates to the precendence for how NuGet determines which type of Restore to perform, ex: create project.lock.json or obj/project.assets.json when a project contains both TargetFrameworks and project.json.

**Comment by nguerrera** [comment]
@emgarten OK. https://github.com/NuGet/Home/issues/3588. Is that clear enough?

**Comment by emgarten** [comment]
@nguerrera thanks!

**Comment by rrelyea** [comment]
This blocks legacy csproj from command line (msbuild /t:restore + nuget.exe)
