### ISSUE TITLE
Localization needs significant updating for NuGet.Tools.vsix and NuGet.exe

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3506]
Tracking an Internal bug - [266593](https://devdiv.visualstudio.com/DevDiv/_workitems?id=266593&_a=edit)
RElated:  vsfeedback 744804 --- 'detected package downgrade' warning in my error list on a French install

**Comment by mishra14** [comment]
It seems that vendors had not localized the new strings. Jacques Eloff is trying to get that started.

**Comment by rrelyea** [comment]
Just pinged the people involved in turning the crank on this.

**Comment by rrelyea** [comment]
Getting closer, but won't have this change in time for RC3.

**Comment by mishra14** [comment]
Seems like this is done. Cranking a build to check.

**Comment by mishra14** [comment]
It seems that a bunch of strings have not yet been localized. I have emailed Daniel and vendors to get their take on that.

**Comment by rrelyea** [comment]
another dupe to confirm when we think we are fixed.: vsfeedback 744804

**Comment by mishra14** [comment]
Working on adding comments/LCI files to prevent over localization.

**Comment by mishra14** [comment]
Finished commenting LCI files. But that caused mismatch between comments and existing translations. The vendors are updating the translations to react to the correct comments.

**Comment by mishra14** [comment]
Update: This is happening because 3 dlls (`NuGet.SolutionRestoreManager.dll`,` NuGet.Credentials.dll`, `NuGet.ProjectModel.dll`) are currently not being localized. I have started working on adding them to our artifacts and have informed the vendors.

**Comment by mishra14** [comment]
Current status: The localization of the 3 new dlls is done. We currently have 3 strings which are not translated (reason - change in string, vendors needed context on the strings etc.). Working on getting them done within the week.

**Comment by rrelyea** [comment]
We don't believe we have any more release blocking issues in this area.
Closing. Thanks Ankit!
