### ISSUE TITLE
NuGet.props file generated on `dotnet restore`?

### ISSUE THREAD

**Issue by MicahZoltu** [NuGet/Home#3511]
I recently updated all of my stuff to 1.0.1 along with updating `dotnet` to `1.0.0-preview3-003686`.  Now when I do `dotnet restore` a file named `<project_name>.nuget.props` is generated in the root of my project.  I am unable to find any information about this file, such as whether to commit it to source control, what it is for, why it is just now being created, etc.

If this is not a bug and that file should now be created, then some easier-to-find documentation would be valuable since it is a behavior change.

**Comment by yishaigalatzer** [comment]
We are going to generate props/targets files going forward. The idea is that with msbuild support in .net core package will start bringing their target/props and the way to link them into the build is by nuget writing out this file.

It shouldn't be checked in, and @emgarten can comment if this is the final location or not. And yes it should definitely be documented.

CC @blackdwarf @karann-msft

**Comment by emgarten** [comment]
These files are placed under the obj folder for projects using PackageReference. With csproj + project.json, which I am assuming you have, you get the UWP behavior of project.lock.json + targets and props files next to the lock file.

**Comment by kraigb** [comment]
FYI, docs for `dotnet restore` are part of the .NET docs rather that NuGet docs proper. I'll let the owner of that page (https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-restore) know. For NuGet docs, I'll add the necessary notes for `nuget restore`.

**Comment by kraigb** [comment]
See https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#restore for the note under nuget restore.

**Comment by MicahZoltu** [comment]
This issue is completed to my satisfaction (documented).  Feel free to close as appropriate.

**Comment by emgarten** [comment]
Thanks @MicahZoltu, closing this issue
