### ISSUE TITLE
[Test Failure] The order of listed package when searching in the filter of PM UI is confusing 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3512]
**Repro Steps:**
1.  New a project [such as C# Blank Application (Universal Windows)].
2.  Open ‘Manage NuGet Packages for Solution’ and click ‘Browse’ tab.
3.  Type a ‘c’ in search filter and look at the listed packages.

**Expected Result:**
The packages whose name include ‘c’ should be listed at first.

**Actual Result:**
The order of listed package is confusing. The packages whose name include ‘c’ are listed in the middle of the package list as below screenshot.
![confusinglistorder](https://cloud.githubusercontent.com/assets/20632625/18828441/86a98ed4-840a-11e6-8e1b-4da44cdda189.png)
**Note:**
1.  It was found on Dev15 Preview 25723.02 (NuGet 3.6.0-Beta1-1821).
2.  It repro on Dev15 Preview 25723.02+NuGet 3.6.0-Beta1-1882.
3.  It repro on Dev14 MU3 25431.01 (NuGet 3.4.4.1321).
4.  It repro on Dev14 MU3 25431.01+NuGet 3.5.0-RTM-1863.

**Comment by jainaashish** [comment]
Dupeof #4614
