### ISSUE TITLE
Is it wrong to define package metadata in project.json?

### ISSUE THREAD

**Issue by ivan-prodanov** [NuGet/Home#3514]
The official documentation says that project.json replaces packages.config, but doesn't mentioned at all the .nuspec file. The questions is **not** related to .NET Core. 

Let's say that I want to create a NuGet package - I can, for example, create a regular .csproj file, define all of its NuGet dependencies in the project.json file and **also define the package metadata** in that very same file.

E.g 
`{

  "version": "1.1.4",
  "authors": [ "Me" ],
  "description": "This package contains metadata in its project.json file",
  "dependencies": {
    "EnterpriseLibrary.Common": "6.0.1304",
    "EnterpriseLibrary.Logging": "6.0.1304",
    "CommonServiceLocator": "1.3.0",
    "Unity": "4.0.1",
    "Unity.Interception": "4.0.1",
    "NUnit": "3.4.1",
    "RhinoMocks": "3.6.1"
  },
  "frameworks": {
    "net45": {}
  },
  "runtimes": {
    "win-x64": {}
  },
  "supports": {
  }
}`

Creating the .nupkg file by passing the .csproj path to NuGet.exe (the "version" field is parsed by NuGet  only if the latest version is used - 3.5 RC1).

Questions:
1. Obviously I can do this, but is this planned to be supported?
2. Is it a bug?

**Comment by yishaigalatzer** [comment]
Hey @ivan-prodanov ,

This is a great question. A few months ago that was indeed what we wanted to do.  We did build a first cut of pack using project json, but did not advertise it. So it's there, but we didn't declare it as supported it "kind off" works today, but there is no support plan/bug fixing strategy around it.

Then lately we have decided to move support back into csproj for .netcore **and** for UWP. 

So the long term plan is to make `project.json` go away (as in we will support old project, and fix critical bugs, but in general urge devs to move to the unified `<PackageReference` model and invest the development efforts there including a common pack target.

Now specifically to your question:

> > 1. Obviously I can do this, but is this planned to be supported?
> >    No plans to support/enhance bug fix in this area, but yes it does work. Use at your own risk.
> > 2. Is it a bug?
> >    Not a bug, just an abandoned/undocumented development path.

Hope this answers your questions and clarifies the situation.
