### ISSUE TITLE
xbuild fails with missing _SplitProjectReferencesByFileExistence target

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#3515]
Not sure if we are planning to support xbuild or not. When I tried to run the following:

```
 xbuild /t:Rebuild MySolution.sln /p:PackOnBuild=true
```

I get an error:

```
error : Target '_SplitProjectReferencesByFileExistence', a dependency of target 'GetPackageContents', not found.
```

MSBuild on the Mac supports the _SplitProjectReferencesByFileExistence targets so replacing xbuild with msbuild in the command works.

**Comment by kzu** [comment]
We should focus on MSBuild I think, given that xbuild is going away... 

/cc @mhutch

**Comment by mrward** [comment]
On the Xamarin Studio side if only we support MSBuild then we may need to look at enabling MSBuild support on a per solution basis in the short term.

Currently MSBuild can only be enabled globally in Xamarin Studio's preferences so it affects all solutions. Right now this preference is marked as experimental and by default it is unchecked so xbuild is used.

Being able to turn on MSBuild support on a per solution basis would allow Xamarin Studio to enable it if NuGetizer is being used.

**Comment by kzu** [comment]
:+1:. With MSBuild almost ready for xplat (right @radical? ;)), I'd say
this is the best, rather than going backwards fixing the multitude of
xbuild workarounds we'll surely need to put in place otherwise..)

## 

/kzu from mobile

**Comment by kzu** [comment]
Closing for now since MSBuild is the default in VSfM nowadays
