### ISSUE TITLE
Could not find pdb file when packing Xamarin.iOS project on Mono

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#3516]
With a Xamarin.iOS project having NuGet package metadata when trying to pack the project with Mono there is an error finding a .pdb file.

```
msbuild /t:Rebuild TestPortableAndIOSNuGetPackage.sln /p:PackOnBuild=true
```

```
(_Pack target) -> 
  ~/Projects/Tests/TestPortableAndIOSNuGetPackage/packages/NuGet.Build.Packaging.0.1.40-dev/build/NuGet.Build.Packaging.targets(194,3): error : Could not find file "~/Projects/Tests/TestPortableAndIOSNuGetPackage/IOSLib/bin/Debug/IOSLib.pdb". [~/Projects/Tests/TestPortableAndIOSNuGetPackage/IOSLib/IOSLib.csproj]
```

Sample test project:  https://github.com/mrward/TestPortableAndIOSNuGetPackage

This looks more like an MSBuild problem on Mono since with /v:diag you can see the pdb file extension defined in a few places and the files being passed to the _CollectPackageContents target seem also have this file extension.

```
_DebugSymbolsIntermediatePath
    obj/Debug/IOSLib.pdb
_DebugSymbolsOutputPath
    bin/Debug/IOSLib.pdb

Added Item(s): 
    PackageFile=
        ~/Projects/Tests/TestPortableAndIOSNuGetPackage/IOSLib/bin/Debug/IOSLib.pdb
                FinalOutputPath=~/Projects/Tests/TestPortableAndIOSNuGetPackage/IOSLib/bin/Debug/IOSLib.pdb
                Kind=Symbols
                TargetPath=IOSLib.pdb
```

//cc @radical

**Comment by mrward** [comment]
This might be a problem with the Xamarin.iOS MSBuild targets. Xamarin.Android projects work fine.

**Comment by kzu** [comment]
Since latest Mono supports PPDBs already, maybe we should try generating them instead? Also, IIRC XI can't switch to PPDBs until the linker is updated accordingly (that is, Mono itself supports it, but the XI linker doesn't?). I may have gotten that wrong :)

/cc @spouliot

**Comment by kzu** [comment]
How about making sure the item that ends up in the [DebugSymbolsProjectOutputGroupOutput](https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.targets#L79) is the .mdb rather than the PDB in that case?

**Comment by mrward** [comment]
Yeah making the .mdb end up in DebugSymbolsProjectOutputGroupOutput seems fine to me. Android projects seem to already do that.

**Comment by jstedfast** [comment]
How do the Android targets do that?

**Comment by radical** [comment]
Why a `.pdb` and not `.mdb` here?

**Comment by radical** [comment]
@mrward I am not able to reproduce this. Could you share the XI/mono/msbuild versions that you are using? Also, could you please share the full diagnostic build log?

**Comment by radical** [comment]
JFYI, in mono's msbuild, if the C# compiler is `mcs` or `mcs.exe`, then `.mdb` files are used, else `.pdb` files. If you happen to change `$(CscToolExe)` to another name then it `.pdb` files would be used. You can override that behavior by setting `$(CscDebugFileExt)` to `.mdb`, for example.

Esee
https://github.com/mono/msbuild/blob/xplat-c8p/src/XMakeTasks/Microsoft.CSharp.Mono.targets#L25

**Comment by mrward** [comment]
@radical 

Mono 4.8.0 (mono-4.8.0-branch/25d7170) (64-bit)
Xamarin.iOS: 10.0.0.6
MSBuild: 14.1.0.0

[Full msbuild output after running a clean](https://gist.github.com/mrward/e0e87d8a7bea9ad63acb681964c56330)

**Comment by radical** [comment]
This should fix it - https://github.com/xamarin/xamarin-macios/pull/896

**Comment by kzu** [comment]
Closing as this was fixed in the proper external
