### ISSUE TITLE
Make CI builds repeatable

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3519]
CI build scripts evolve to accommodate the most recent dev and release changes. This makes re-building older releases virtually impossible.

**Proposed solution**
Move CI build, test, and publish scripts and settings into the NuGet.Client git repo. Minimize TeamCity integration protocol to a small number of commands.

**Comment by jainaashish** [comment]
CI builds have been moved from TeamCity to VSTS which has different build configurations.
