### ISSUE TITLE
[Mono issue]NuGet.exe pack doesn't work well for including files with wildcard

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3522]
PackCommand_JsonPackOptionsFiles() test failed on mono.

pack the project.json with following pack option:
""files"": {
      ""include"": ""contentFiles/**"",
      ""exclude"": ""contentFiles/**.txt"",
      ""includeFiles"": [ ""contentFiles/file2.txt"" ],
      ""excludeFiles"": [ ""contentFiles/image3.jpg"" ],
    }

Expected files path in Nupkg are : 
contentFiles/image1.jpg, contentFiles/image2.jpg

Actual files path are: 
image1.jpg, image2.jpg

**Comment by rrelyea** [comment]
Take a look at the comment that @yishaigalatzer made over here: https://github.com/NuGet/Home/issues/3514
