### ISSUE TITLE
[Mono issue] nuget.exe pack wild card exclude doesn't work on mono

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3526]
Related Test failure:
PackCommand_ExcludesFilesOutsideRoot()

pack packages.nuspec with following: 

``` xml
<files>
    <file src=""**"" exclude=""**\exclude.me"" target=""Content\package"" />
    <file src=""..\other\**"" exclude=""**\exclude.me"" target=""Content\other"" />
  </files>
```

Expect : 
Nupkg only contains include.me.

Actual:

Nupkg still contains exclude.me

I guess this issue is also related to "**" search.

**Comment by zhili1208** [comment]
3.4.4 can't pack this due to path issue, this is not an regression

**Comment by dtivel** [comment]
The issue is that on Unix-like operating systems the `\` character in the `exclude` attribute values are not interpreted as directory separators.  If the `exclude` values use `/` instead, `pack` works as expected.
