### ISSUE TITLE
Get-Package command in Find-Package example

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#3528]
@BartHamer commented on [Wed Sep 14 2016](https://github.com/NuGet/NuGetGallery/issues/3241)

The Find-Package examples section contains the following:

`Get-Package jquery -AllVersions -ExactMatch`

which should be

`Find-Package jquery -AllVersions -ExactMatch`

---

@maartenba commented on [Wed Sep 14 2016](https://github.com/NuGet/NuGetGallery/issues/3241#issuecomment-246961803)

@karann-msft Looks like a docs issue, can you look into it?

---

@karann-msft commented on [Mon Sep 26 2016](https://github.com/NuGet/NuGetGallery/issues/3241#issuecomment-249712195)

@BartHamer can you provide the link to the doc.

**Comment by BartHamer** [comment]
Of course, sorry about that: https://docs.nuget.org/ndocs/tools/powershell-reference
The text is part of the Examples section of the Find-Package command.

**Comment by karann-msft** [comment]
Fixed. Thanks for reporting. We encourage contribution from the community most docs can be edited by clicking on the Edit in Github button at the top.
