### ISSUE TITLE
[Mono issue] nuget.exe pack PCL with msbuild 14.1 doesn't work on mono

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3529]
Related test failure:
PackCommand_PclProjectWithProjectJsonAndTargetsNetStandard()

pack proj1.csproj -build Got "can't find Microsoft.Portable.CSharp.targets".

**Comment by zhili1208** [comment]
3.4.4 doesn't support project.json and netStandard, this is not an regression

**Comment by yishaigalatzer** [comment]
Disable the tests for 3.5

CC @mrward @kzu
