### ISSUE TITLE
Supporting Package Reference in UWP WPF WinForms and Classic Libraries

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3533]
Spec of the work is tracked here https://github.com/NuGet/Home/wiki/Supporting-Package-Reference-in-UWP-WPF-WinForms-and-Classic-Libraries/

**Comment by drewgillies** [comment]
This is all done except for altering the build task to support it.

**Comment by rrelyea** [comment]
Feature is in, except for the PackageTargetFallback.

**Comment by drewgillies** [comment]
PTF is operational. More test coverage of project desired, but test framework is in place, and we are complete.
