### ISSUE TITLE
Secondary header links in CLI references docs redirect to wrong section

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3534]
Details -

Clicking on a secondary header link on the new CLI reference page redirects to the wrong section

Repro - 
1. Go to [http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference](http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference)
2. Click any command (other than install) from the right hand sidebar.
3. Click on any secondary like usage or example.
4. Observe that the page is redirected to install/subsection instead.

Possible reason - 

It seems that all the commands have the same secondary headers and thus the page redirects to the first occurrence of the header.

**Comment by harikmenon** [comment]
@karann-msft

**Comment by kraigb** [comment]
@mishra14 this should be resolved as the docs are on a new site, https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference, in which secondary headers in the auto-gen TOC don't appear. I believe you can close this.
