### ISSUE TITLE
CLI reference does not mention update option for nuget sources command

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3535]
[http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#sources](http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#sources) does not mention update option for the nuget sources command.

**Comment by harikmenon** [comment]
@karann-msft

**Comment by mishra14** [comment]
Since other commands like sources add/remove/enable are not detailed, the doc is consistent for sources update.
