### ISSUE TITLE
How to indicate that Dependencies are for output only, and not added as References?

### ISSUE THREAD

**Issue by kabua** [NuGet/Home#3536]
First of all, thanks for creating a very useful tool!

Question: from within the `nuspec` file, how do we specify that only the package should be added as a Visual Studio project Reference (i.e. `<ItemGroup><Reference...>`) but all of its dependencies should be copied to the output folder?

**Use Case**:
We have two frameworks, the first is general content that could be used by any company, but for now it is only used internally. The second framework, which targets our new platform, depends on the first plus 15-25 other nuget packages.

The problem we are having is that our client applications / projects include References to EVERYTHING! We only want the client project(s) to 'see' (have direct access to) only the package(s) that are directly installed, not any of the dependencies these packages require.

From a different point of view, we use a layered architecture; which consists of: Business, Common, DataAccess, WebServices and WebSpa layers.  The Business layer should only see the Common and DataAccess layers - which it does. However, due to our current nuspec, when WebServices installs the Business package, the WebServices not only gets a Reference to the Business.dll but also to the DataAccess.dll; and ALL of their dependencies get injected into the WebServices project as References. We would like everything, except for the Business.dll and those dependencies we mark, to be included in some kind of `<ItemGroup>` that: 1) isn't shown in the Solution Explorer and 2) that _is_ copied to the output folder.

There are times when we include dependencies, not because the current project needs it, but because it is convenient to bundle several related packages together, and because we need to standardize an a specific version of these bundled packages. Therefore, these packages _do_ need to be added as References.

As a bonus, it might be nice to specify which dependencies are: 1) copied or not copied to the output folder, and 2) are included or not included as References.

**Example**:
Where: `IncludeAsReference="false"` and `CopyToOutput="true"` are the defaults.

```
         ...
        <dependencies>
            <dependency id="Microsoft.AspNet.WebApi.Client" version="[5.2.3]" />
            <dependency id="Microsoft.AspNet.WebApi.Core" version="[5.2.3]" />
            <dependency id="Newtonsoft.Json" version="[6.0.8,7.0)"  IncludeAsReference="true" />
            <dependency id="My.System" IncludeAsReference="true" />
            <dependency id="My.System.Designer" CopyToOutput="false" />
        </dependencies>
```

Can this currently be done in v3.4.4?

**Comment by jainaashish** [comment]
With PackageReference, you don't get transitive dependencies in the source project explicitly so your scenario will be fixed with that. You can find more details in this blogpost -https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html 

Other than this, we don't plan to support these properties at this time and the expectation is a package include everything it would need to install and work on a source project. If there are more community feedback and requirement for this feature, then we'll re-evaluate.

**Comment by kabua** [comment]
Thanks for the feedback, I didn't realize what 'Transitive Package Restore' did until I read it again tonight. I'm currently installing 15.4.1 to try it out!
