### ISSUE TITLE
API for <clear /> section in NuGet.config

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#3538]
NuGet.config may contain the `<clear />` section in `<packageSources>`:

``` xml
<packageSources>
    <clear />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
</packageSources>
```

Is there any way to specify this section via API?

**Comment by jainaashish** [comment]
No, there is no such api and we don't plan to add one as well.
