### ISSUE TITLE
Fix NuGet.targets for VS and Developer command line

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3542]
Need to install NuGet.targets in vsix.
Need to make vsix addressable with a constant file path.
Need to include NuGet.targets from msbuild targets somehow. Will start dialog with msbuild team about how.

**Comment by emgarten** [comment]
The VSIX has been updated with a ShortcutPath and now includes NuGet.targets. MSBuild will reference this targets file from Microsoft.NuGet.ImportAfter.targets.

The code changes are complete, everything just needs to make it into the same build to verify this is fixed.
