### ISSUE TITLE
Allow hiding packages from local repo

### ISSUE THREAD

**Issue by dotMorten** [NuGet/Home#3547]
Since you have the 250mb package limit, and we need more for iOS we split our packages into sub-packages (due to it needing static libraries in it for each platform).
On nuget.org we can hide these sub-packages, so you only find the main iOS Package. It gives a really great user experience without showing some confusing sub-packages that doesn't really do anything by themselves.

However with local repos it isn’t possible to hide sub-packages. It would be nice if we could just set the “Hidden” attribute on the nupkg, and it'll hide it from the Visual Studio Nuget dialog a well. Alternatively allow laying down a config next to it based on a naming pattern that allows us to give additional control over the package similar to what the webinterface on nuget.org allows us to do.

@harikmenon @rrelyea

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. So we're closing it for now, but if we see more community feedback on this issue, we'll further take a look.

**Comment by dotMorten** [comment]
@jainaashish So... you haven't had time to look at it, thus this is invalid feedback?
