### ISSUE TITLE
Nuget update does not sometimes update reference's version numbers from vsproj-files

### ISSUE THREAD

**Issue by kummahiih** [NuGet/Home#3553]
Nuget update does not sometimes update reference's version numbers to csproj -files. See the attached picture where the reference of the lifecare.desktop.theme was not updated.

![image](https://cloud.githubusercontent.com/assets/220791/18944588/fbbf79e2-862e-11e6-86af-0bae6545ea3c.png)

On this setup, the themeutil -files have been copied on nuspec -file via using files -tag  instead of being on the same project.

**Comment by rrelyea** [comment]
What version of NuGet.exe are you using?
What exact command are you running?
What type of project are you running it on?
What % of the time does it not work?
Does it always work for a project or not...or is it variable?

**Comment by wallymathieu** [comment]
I've seen this issue when you forget to save project (but then for csproj). It has happened to me when I want to upgrade the package references and check in, without compiling. Could it be that?

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
