### ISSUE TITLE
Wildcard in project.json version

### ISSUE THREAD

**Issue by Sebosek** [NuGet/Home#3555]
I'm able to pack library with flag `--version-suffix <VERSION_SUFFIX>` but in project.json I can's use wildcard for patch version

```
{
  "version": "1.0.*"
}
```

> '1.0.*' is not a valid version string.

I'm asking myself: so, why is there flag `--version-suffix`?

**Comment by emgarten** [comment]
What are you using to pack? And what version of the tool?

**Comment by Sebosek** [comment]
Oh, sorry. `.NET Command Line Tools (1.0.0-preview2-003121)`, `win10-x64` and tested on .net core class library and .net core web application (web api)

**Comment by rrelyea** [comment]
Thanks for the report. We'll investigate.
We are migrating .NET core project support to msbuild from project.json. We'll test this case in that new world.

**Comment by rohit21agrawal** [comment]
@Sebosek  can you paste a project.json that repros this issue here along with the exact command line you are using to pack your project?

**Comment by rohit21agrawal** [comment]
@Sebosek also note that version string for wildcards should be of the format 1.0.0-\* . then the \* will be replaced by whatever you pass in the --version-suffix.

**Comment by rohit21agrawal** [comment]
@Sebosek any update on this?

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
