### ISSUE TITLE
Nuget 3 .targets file not added to csproj file

### ISSUE THREAD

**Issue by psandhu79** [NuGet/Home#3558]
Hi 

Trying to use accord 3.0.2 nuget package with project.json . The package contains a .targets file and dll.config. I cannot see the targets file imported which copy the .dll.config file to the output directory.

The project.json.lock looks like this 

 "libraries": {
    "Accord/3.0.2": {
      "sha512": "Rr4qe5MkUql9qdEZyAMlRBFBEHztILnDdLongRgr8e5sp+EkZcZG3xCRhWCPKLyWD/Jk5Vn2aqPBttOfqvo+cQ==",
      "type": "package",
      "files": [
        "Accord.3.0.2.nupkg.sha512",
        "Accord.nuspec",
        "build/Accord.dll.config",
        "build/Accord.targets",

**Comment by emgarten** [comment]
What type of project is this package used from?

**Comment by psandhu79** [comment]
C# Class library , from reading the documentation i was suspecting the accord.targets file is added to the project.json.lock file

**Comment by yishaigalatzer** [comment]
The targets are not supposed to be added to the lock file, but to a target file at the root of the project

**Comment by psandhu79** [comment]
Ok, this is not created so is this a bug or a problem with the accord package

**Comment by emgarten** [comment]
@psandhu79 can you provide some repro steps for this issue? What version of NuGet are you using?

**Comment by psandhu79** [comment]
I am using Nuget 3.4.4

I created a project.json file with the following contents

{
  "dependencies": {
    "Accord": "3.0.2"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win": {},
    "win-x64": {}
  }
}

Then add this to the csproj file 

Then perform a nuget restore on the project.json file (because i am using teamcity)
Then build the .sln

**Comment by emgarten** [comment]
@psandhu79 here's what I tried
1. Create a new class library
2. Added your json to project.json
3. Reloaded the project
4. Restored in Visual Studio

Next to the project ClassLibrary1.nuget.targets was created with this output:

``` xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
    <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
  </PropertyGroup>
  <ImportGroup>
    <Import Project="$(NuGetPackageRoot)accord\3.0.2\build\Accord.targets" Condition="Exists('$(NuGetPackageRoot)accord\3.0.2\build\Accord.targets')" />
  </ImportGroup>
</Project>
```

Are you seeing that output?

**Comment by psandhu79** [comment]
Hi

Your correct this works in my situation too if i open the solution and use the automatic restore within visual studio.

What i need is to be able to do was restore using either the project.json file or packages.config not the sln before the building of the solution. And was hoping the targets file is created.

Or msbuild the .sln and it triggers the same automatic restore it does when you open a solution and start to build.

**Comment by yishaigalatzer** [comment]
You should be able to restore the csproj or the sln directly from nuget.exe as well. And as long as your nuget.exe version is new enough things should work.

Updating to the latest is nuget.exe update /self

**Comment by emgarten** [comment]
As @yishaigalatzer mentioned, you need to restore the MSBuild file to get the MSBuild targets/props.

Project.json by itself is treated as standalone/xproj which does not support targets/props, all imports are ignored when restoring project.json instead of the csproj.

**Comment by psandhu79** [comment]
@emgarten Will there be an automatic restore implemented from the command line when you build a solution, just like when you build in visual studio

**Comment by yishaigalatzer** [comment]
It is already, just need to run two command in a script :)

Nuget.exe restore xxx.sln
Build

Sent from Ninehttp://www.9folders.com/
