### ISSUE TITLE
Broken link from Use a Package to first related topic

### ISSUE THREAD

**Issue by davidmatson** [NuGet/Home#3559]
https://docs.nuget.org/ndocs/Quickstart/Use-a-Package

Has a broken link to:
•NuGet 3.0, .NET and project.json
https://docs.nuget.org/ndocs/consume-packages/projectjson-intro

**Comment by davidmatson** [comment]
Actually, all four Related topics links at the bottom of that page are broken.

**Comment by kraigb** [comment]
Fixed in PR649
