### ISSUE TITLE
Update/Redirect https://nuget.org/nuget.exe to download the latest version of NuGet

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/Home#3560]
Hello,

The path to download the latest NuGet.exe file used to be `https://nuget.org/nuget.exe` and now it seems it changed to `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe`

The latest nuget.exe as I'm writing this is `3.4.4.1321` and downloading from `https://nuget.org/nuget.exe` returns version `2.8.60717.93`

I'd suggest you add a redirect, so people who have automation scripts can continue to get the latest version, or at least remove it and return a 404.

Cheers

**Comment by yishaigalatzer** [comment]
This is by design. The intent is not to break existing builds that rely on 2.8.X given that the 3.X release introduces a set of breaking changes.

See the docs at - https://docs.nuget.org/ndocs/guides/install-nuget

> NuGet 2.x users
> Because there are a few breaking changes introduced in NuGet 3.2, https://nuget.org/nuget.exe points to the latest stable NuGet 2.x release to prevent CI systems from potentially breaking at this time.
