### ISSUE TITLE
[Test Failure] Additional information display after typing “Get-Package -Updates” in PMC

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3565]
**Repro Steps:**
1. Create a new project C#-> Windows 8->Hub App (Universal Windows 8.1).
2. Right-click the project **'HubApp.Windows(Windows 8.1)**'node and click "Manage NuGet Packages…" menu to start package manager.
3. Install package “Newtonsoft.Json” version **7.0.1**.
4. Start “Package Manager Console” and type “Get-Package -Updates”.

**Expected Result:**
The detail of update information display as below screenshot.
![93002](https://cloud.githubusercontent.com/assets/20632775/18981809/139feb9c-8714-11e6-9561-e3987b26fe69.png)

**Actual Result:**
Additional information displays under detail information. 
![93001](https://cloud.githubusercontent.com/assets/20632775/18981816/18d8acb6-8714-11e6-882d-f36fbce3e3a1.png)

**Note:**
It happens on NuGet 3.5.0-rtm-1930.
It not repro on 3.6-Beta1-1882.
It only happens on Hub App (Windows 8.1).

**Comment by rrelyea** [comment]
According to @zhili1208 This behavior is the same for 3.4.4 -- the message is for the other project in the solution.

**Comment by jainaashish** [comment]
This is the expected behavior and not a bug.
