### ISSUE TITLE
NuGet pack resolves dependency ID from directory name when -IncludeProjectReferences is used for csproj + project.json

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#3566]
My situation:

Visual Studio 2015 Update 3
Tested with nuget: 3.5 RC / 3.6 rc 1927 (nightly)
Setup:
- one solution folder "helpers" with two libs; lib1 in folder "lib1" and lib2 in folder "**monkey**"
- both libs are .NET standard 1.4 project types (with project.json files)
- lib1 has a project reference to lib2
- I didn't add any .nuspec file

I'm running the command:

```
nuget pack .\lib1\lib1.csproj -Properties Configuration=Release -IncludeReferencedProjects
```

The generated package has e dependency on package "**monkey**". Say what? Monkey... that's not what I expected!

Can anyone explain why this is happening. Am I doing something wrong?

**Comment by rohit21agrawal** [comment]
@tomkuijsten can you attach the repro project? That would really help.

**Comment by tomkuijsten** [comment]
Created a sample project, you can [download it here](https://1drv.ms/u/s!AgSBicI7Mqqmifg-0rQmhyaXbOBexQ)

I included the reproduction steps and the nupkg that was generated, quick recap:
- Visual Studio Community Edition 2015 update 3
- NuGet 3.5 RC1
- Build project in Release configuration
- Run: `nuget pack .\lib1\lib1.csproj -Properties Configuration=Release -IncludeReferencedProjects`

**Comment by rrelyea** [comment]
@tomkuijsten  - did this work differently in 3.4.4?

**Comment by tomkuijsten** [comment]
I honestly don't know, we starting moving to .NET standard about a week ago and I'm trying to get the same package creation behavior as we did have with csproj+nuspec, but now with csproj+project.json. I got it all working again, except for this weird thing.

**Comment by rohit21agrawal** [comment]
@tomkuijsten @rrelyea 3.4.4 is not complete when it comes to packing csproj + project.json . 

The issue here is that nuget is inferring the name of the dependency from the name of the directory in which it is located, instead of the assembly name or the "name" property from the referenced project's project.json .

@tomkuijsten Note that with csproj + project.json, the expected behavior is that the referenced projects are added as a dependency (the output DLLs are not included in the lib folder) . The bug here is how the dependency name is being resolved.

**Comment by tomkuijsten** [comment]
@rohit21agrawal thanks for the info. That is indeed my only problem, the name. Another question pops up: are all referenced projects added as dependencies? Even if they don't have "packageOptions" in the project.json? It used to be based upon the existence of a <projectname>.nuspec file.

**Comment by rohit21agrawal** [comment]
@tomkuijsten yes, all referenced projects are added as dependencies in the project.json world. If this was a packages.config file, then it would respect the nupec file rule. But project.json == nuspec basically, so we can't rely on the existence of the nuspec file.

**Comment by tomkuijsten** [comment]
Are there any work around or other options to be able to generate a correct package? (like using package.config instead)

**Comment by rohit21agrawal** [comment]
@tomkuijsten we are very soon going to be releasing a new version of pack for NETCore projects which will have all their dependencies and metadata managed in a csproj file. Do you think that will work for you?

packages.config should work too.

**Comment by tomkuijsten** [comment]
That would probably work for me, thanks. Does "very soon" imply a couple of days, or couple of weeks?

Adding a packages.config doesn't work. The `pack` doesn't do anything with it (I guess because I have a project.json as well, and that one takes preference).

**Comment by rohit21agrawal** [comment]
I'll let @rrelyea comment on the timeline.

**Comment by rrelyea** [comment]
@tomkuijsten - Our first release with this support should come later this year.

**Comment by tomkuijsten** [comment]
Any timeline updates? Really waiting for this as it would enable me to move to project.json for all my projects.

I just tested with 4.0 rc3, but it's still using the folder name.

**Comment by tomkuijsten** [comment]
It's not planned anymore, only for "future"? I guesse I'm doing something fundamentally wrong if the whole world can work around this bug and I can't. Can anyone tell me why this is not a problem for others?

**Comment by jainaashish** [comment]
@tomkuijsten you can use netcore projects and subsequently use `msbuild pack` command to pack your package the way you want to... Please find more details here - https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target
