### ISSUE TITLE
<clear /> on <packageSourceCredentials> does not work

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3568]
Tested in `3.3` - `3.5.0-rc1`. All the same behavior. This is a feature request, considering this never worked 😄 .
## Steps
1. Put some `<packageSourceCredentials>` in a NuGet.config.
2. Create a subdirectory.
3. Create a NuGet.config in that subdirectory.
4. Put a `<clear />` under `<packageSourceCredentials>`.
5. Run a nuget.exe command requiring those credentials (i.e. `nuget.exe install Newtonsoft.Json -Source SourceName`).
## Expected

nuget.exe should ask for credentials since the credentials have been `<clear />`'d.
## Actual

nuget.exe still has the credentials and the install succeeds without user interaction.

/cc @harikmenon @zhili1208 @tkrick

**Comment by tkrick** [comment]
splitting hairs a bit but the [documentation](http://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior) says: When <clear /> is present for a given node, previously defined configuration values for that node are ignored.

which means clear should have worked for packageSourceCredentials. Either way, thanks for looking in to this and appreciate your time.

**Comment by rrelyea** [comment]
workaround - use "-config" which will only put that config into effect, effectively dropping the config context based on directory location.

**Comment by pspill** [comment]
I don't think this issue should be fixed, as this seems to be a valid user scenario:  1) I have nuget.config in the root of my source control, 2) I use "clear" to ensure that no other package sources are used during restore, but 3) I do _not_ want to configure credentials in source, I want these to be specified in my user profile nuget.config.

**Comment by tkrick** [comment]
actually @pspill now that you say that, I agree. creds are meant to be user specific which means the result can't really reside in source control.  This is really about nuget 3.3 not falling back to cred provider when creds from nuget.config fail due to expiry/etc, which we can deal with by either upgrading (once 3.5 rtm comes out) or like rrelyea says to be specific about the config that should be consumed.

**Comment by jainaashish** [comment]
From the discussion looks like this is the desired behavior and no customer has complained about this so far. So we're gonna keep it until community feels otherwise.
