### ISSUE TITLE
Using NuGet to add Microsoft.CodeDom.Providers.DotNetCompilerPlatform to a Web Site

### ISSUE THREAD

**Issue by gary-b** [NuGet/Home#3569]
When I install Microsoft.CodeDom.Providers.DotNetCompilerPlatform to a web site (not app) from NuGet, I get the dll and a roslyn folder in my Web\Bin folder. (The roslyn folder has exes for the compiler and some other stuff.)
Packages.config in the web folder is updated as expected and the web.config is updated to use the new compiler.
I just checked in these 2 files to TFS, but when my colleagues get latest, the required files are not inserted into Web\Bin on build.
I tried keeping the dll.refresh file for all the associated files, on build the dll in the main Web\Bin folder does get pulled in, but none of the files in the roslyn directory are pulled in.
With web sites there are no csproject files - so I'm at a loss as to how to resolve this, without checking in all the files that nuget added to Web\Bin on my local.
I think the main issue is that roslyn sub folder.
Any ideas?

**Comment by yishaigalatzer** [comment]
I suggest working with the authors of the package directly (contact them on nuget.org). 

One potential way to workaround it is to add a post build script to execute the copy.
