### ISSUE TITLE
Performance: NuGetv3LocalRepository improvements

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3574]
NuGetv3LocalRepository performance could be improved. Restore should be profiled to see if it is a problem area and worth fixing.

Possible improvements
1. Avoid reloading nuspec files that have already been loaded. This class should be append only, there are no scenarios where packages are removed from the global folder during restore.
2. Improve clear/get locking. Clear could potentially store a timestamp of when the clear was requested. A get request could store the time it was made and verify that the current results are newer.

https://github.com/NuGet/NuGet.Client/blob/737af820d16c34dcb498832b1e26f03cf1b51aba/src/NuGet.Core/NuGet.Repositories/NuGetv3LocalRepository.cs

**Comment by rrelyea** [comment]
triage: If you have a profile showing significant issues, please reopen, otherwise, we'll let profiling drive this.
