### ISSUE TITLE
Update NuGet.Frameworks for NETStandard2.0

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#3576]
NETStandard2.0 will be supported by the following:
- net461, net462, net463
- netcoreapp2.0
- ~~uap10.1 (not uap10.0 nor netcore50).~~ UAP is not yet committed and folks who own UAP can't commit to the actual version.  That will need to be done separately.

Can these mappings please be added to NuGet?  Ideally to the version that is shipping with netstandard2.0 (dev15?)

We wouldn't have to ask if we have https://github.com/NuGet/Home/issues/3099 😉 

/cc @rrelyea @petermarcu @weshaggard @danmosemsft

**Comment by yishaigalatzer** [comment]
Is there a bigger/better spec with more details? As far as I heard the next RTM release doesn't yet support netstandard 2.0

**Comment by Petermarcu** [comment]
netcoreapp1.2 will support netstandard2.0.

**Comment by weshaggard** [comment]
Closest thing we have to a spec is https://github.com/dotnet/standard/tree/master/docs/netstandard-20. Let us know if you need further information.

cc @terrajobst

**Comment by ericstj** [comment]
This may also need to happen for NuGet 2.x since we want this to work for net461 which can be targeted by VS 2013.

**Comment by ericstj** [comment]
Can we get an ETA on this?  @yishaigalatzer @rrelyea

**Comment by yishaigalatzer** [comment]
This was planned to start after rtm of vs 2017, so not on a schedule yet

**Comment by ericstj** [comment]
We're shipping on the same timeline per https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/ so I believe we'll need this in place for Dev15.

> The tooling for targeting .NET Standard 2.0 will ship in the same timeframe as the upcoming release of Visual Studio, code-named “Dev 15”.

**Comment by yishaigalatzer** [comment]
That's news to us. Let's talk offline

**Comment by terrajobst** [comment]
Should this item be closed? Seems this is done, no?

@ericstj

**Comment by ericstj** [comment]
Yeah, this is done.
