### ISSUE TITLE
ndocs -> NuGet Package Manager in Visual Studio -> Page Not Found

### ISSUE THREAD

**Issue by Yousha** [NuGet/Home#3578]
Missing `NuGet Package Manager in Visual Studio` link in http://docs.nuget.org/ndocs/guides/install-nuget

404 : Page Not Found

http://docs.nuget.org/ndocs/guides/nuget-package-manager-in-visual-studio

**Comment by harikmenon** [comment]
Thanks. Fixed :). Was missing a #

https://github.com/NuGet/NuGetDocs/commit/77d719c097f4a3cf2753b3b559dab52f6bcaeea3
