### ISSUE TITLE
Finalize NuGet.Core.nupkg for publishing

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3581]

**Comment by rrelyea** [comment]
Anything else we need to do here?

**Comment by joelverhagen** [comment]
3.5.0 depended on 2.14.0-rtm-832, which has already been published to nuget.org. 2.14.0 has also been published. No sure what the full idea here was but everything seems good now.

One follow-up item in client is to switch from a 2.14.0-rtm-832 dependency to 2.14.0.

**Comment by jainaashish** [comment]
This has already been taken care of.
