### ISSUE TITLE
[validation] nuget.exe pack excludeemptydirectories ignores lib folders

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3582]
Determine expected behavior and fix (or complete the documentation if current behavior is expected).
NuGet.exe version 3.5.0 build 1938 (not a regression from 3.4.4).

See attached for an example (tweak the pack1.cmd file, adding and removing excludeemptydirectories option--you'll need nuget.exe in the parent dir)--the created nupkg does exclude the empty folder in content, but it excludes the empty folder in lib\uap10.0 regardless of whether excludeemptydirectories is specified.
FYI @rohit21agrawal @emgarten 

[uwp excludeemptydirectories pack.zip](https://github.com/NuGet/Home/files/509034/uwp.excludeemptydirectories.pack.zip)

**Comment by rrelyea** [comment]
@drewgil / @rohit21agrawal  - what would be the use of an empty folder under lib<tfm>\ ?
I cannot think of one. Seems reasonable to not include it, regardless of setting, doesn't it?

**Comment by rohit21agrawal** [comment]
talked to @emgarten  about this . The reason an empty folder would be included in lib would be to show that it's compatible for a given framework.

So if I had a lib\net45 and lib\netstandard13 folder which didn't have any DLLs under them, but instead had the placeholder _._ file, it would indicate that the nupkg is still compatible with net45 and netstandard13, as opposed to those folders not being present - which would indicate that the nupkg doesn't support those frameworks.

**Comment by rrelyea** [comment]
Not clear if this is by design or not. Please look at.

**Comment by jainaashish** [comment]
This is by design for now since we never include empty lib folder even to make it compatible with other TFMs, we always include a placeholder like _._
