### ISSUE TITLE
[documentation] typo in includereferencedprojects option in pack docs

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3583]
Here: http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#pack
includereferenceprojects should be includereferencedprojects
@karann-msft

**Comment by harikmenon** [comment]
Fixed https://github.com/NuGet/NuGetDocs/commit/32bd7010865afb11ff490df3b9cdf963974b60a0
