### ISSUE TITLE
Restore to project with single TargetFramework must not condition props

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#3588]
A project declaring a single TFM, e.g `<TargetFramework>netstandard1.0</TargetFramework>` will do so _after_ props are imported.  As such, if the .g.props file has a $(TargetFramework) condition as it does today, the condition will never be true, and the props will never be imported. 

Nuget needs to distinguish the single TFM case and not emit conditions to the .g.props file (and probably not to the .g.targets either for the sake of consistency).

**Comment by emgarten** [comment]
What is the expected behavior for buildCrossTargeting? Are they left out or are they also put in without a condition?

**Comment by nguerrera** [comment]
They should be left out of the single TFM case. There is no outer build there.

**Comment by emgarten** [comment]
> They should be left out of the single TFM case. There is no outer build there.

That makes sense. For Pack then it seems like the targets file will need to be under both buildCrossTargeting and build, one will be used for multiple TFMs, and the other for a single TFM. //cc @rohit21agrawal

**Comment by emgarten** [comment]
@nguerrera what is the expected behavior if a single TFM is passed in `<TargetFrameworks>`?

**Comment by eerhardt** [comment]
> what is the expected behavior if a single TFM is passed in <TargetFrameworks>?

The same behavior as if multiple TFMs are specified in $(TargetFrameworks).  There is an "outer" build, and NuGet would add the single condition on the Import.

**Comment by emgarten** [comment]
> The same behavior as if multiple TFMs are specified in $(TargetFrameworks). There is an "outer" build, and NuGet would add the single condition on the Import.

Thanks for confirming. NuGet will need to keep track of _how_ it got the single framework to decide if _buildCrossTargeting_ and TFM conditionals are used then.
