### ISSUE TITLE
NuGet.exe sources remove does not remove credentials associated with a source from a local nuget.config

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3589]
Repro steps - 
1. `.\NuGet.exe sources add -name SourceName -source http://Source.com/source -username UserName -password pass -configfile .\nuget.config`
2. Check local nuge.config to verify that the source has been added with the credentials.
3. `.\NuGet.exe sources remove -name SourceName`
4. Check the nuget.config to see that the credentials are not removed.

Note- Credentials are removed if we remove from the local nuget.config explicitly -`.\NuGet.exe sources remove -name SourceName -configfile .\NuGet.Config`

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
