### ISSUE TITLE
Latest NuGet.CommandLine will not build, missing NuGet.Configuration 3.0.0-beta package

### ISSUE THREAD

**Issue by taylorjonl** [NuGet/Home#359]
Latest NuGet.CommandLine will not build, missing NuGet.Configuration 3.0.0-beta package from public repository so when VS tries to download NuGet dependencies it fails.

**Comment by yishaigalatzer** [comment]
Can you please provide more details? What branch are you building from, and what are you trying to do with it.

FYI The 3.0 command line is not yet ready to go

**Comment by yishaigalatzer** [comment]
No Repro - We are building and using the command line. This might have been fixed outside of this bug.
