### ISSUE TITLE
[validation] nuget.exe pack -build -properties fails to pass property

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3590]
v3.6.0-beta1 (regressed from 3.5.0)
This repro passes Configuration=Release to the msbuild task, but the property isn't received by msbuild--we get a debug build and an ensuing error on pack.
FYI @joelverhagen 
[pack build properties - uwp.zip](https://github.com/NuGet/Home/files/509658/pack.build.properties.-.uwp.zip)

**Comment by rrelyea** [comment]
i think this is the fix you made in 3.5.0-rtm and 3.6-rc, right?
what was the original issue number? (this was broken in 3.4.4, right?)

**Comment by rohit21agrawal** [comment]
This fix went into dev and 3.5.0-rtm . https://github.com/NuGet/Home/issues/3432
