### ISSUE TITLE
Consider: nuget locals should still support nuget.exe locals -clear packages-cache

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3591]
From 3.5.0 to 3.6.0-rc1, `nuget.exe locals -clear packages-cache` is no longer supported:

```
> nuget.exe locals -clear packages-cache
An invalid local resource name was provided. Please provide one of the following values: http-cache, temp, global-packages, all.
```

We should consider continuing support for this option so a) CI's doing `nuget.exe locals -clear packages-cache` do not fail and b) it still has use today to clear old nuget.exe left-overs (versions that actually populated the packages cache).

That being said, package is no longer populated so perhaps it makes sense to block people from clearing it.

Another thing to consider it that any future concept of "package cache" would need to somehow disambiguate with this term.
## History

nuget.exe 3.3.0 (baseline)

```
http-cache: C:\Users\jver\AppData\Local\NuGet\v3-cache
packages-cache: C:\Users\jver\AppData\Local\NuGet\Cache
global-packages: C:\Users\jver\.nuget\packages\
```

nuget.exe 3.4.4 (`temp` added)

```
http-cache: C:\Users\jver\AppData\Local\NuGet\v3-cache
packages-cache: C:\Users\jver\AppData\Local\NuGet\Cache
global-packages: C:\Users\jver\.nuget\packages\
temp: C:\Users\jver\AppData\Local\Temp\NuGetScratch
```

nuget.exe 3.5.0 (same)

```
http-cache: C:\Users\jver\AppData\Local\NuGet\v3-cache
packages-cache: C:\Users\jver\AppData\Local\NuGet\Cache
global-packages: C:\Users\jver\.nuget\packages\
temp: C:\Users\jver\AppData\Local\Temp\NuGetScratch
```

nuget.exe 3.6.0-rc1 (`packages-cache` removed)

```
http-cache: C:\Users\jver\AppData\Local\NuGet\v3-cache
global-packages: C:\Users\jver\.nuget\packages\
temp: C:\Users\jver\AppData\Local\Temp\NuGetScratch
```

**Comment by mishra14** [comment]
@joelverhagen, package-cache was removed as part of https://github.com/NuGet/NuGet.Client/pull/829

Reason: I had an offline chat with @emgarten and @rrelyea while I was working on this and since it was no longer used, it seemed better to remove it.

**Comment by rrelyea** [comment]
Makes sense, for compat, leave it as it was.

**Comment by mishra14** [comment]
Per team discussion we will consider this in future based on feedback.

**Comment by aphel** [comment]
Just ran into a bit of an issue with this. We've got a few different versions of nuget used on our build agents (yeah, I know...). Some of them (the repo-specific ones) populate packages-cache whereas the system-wide version is up-to-date, thus it won't clear the packages-cache location (we want to do this on a weekly basis).
It appears to me that keeping the support of clearing the packages-cache should be kept as a matter of backward compatibility, shouldn't it?

**Comment by mishra14** [comment]
@aphel Thanks for the feedback. Is it possible for you to use an older version of `NuGet.exe` to clear the packages-cache? Especially considering that you have different versions already.

**Comment by jainaashish** [comment]
More than a year and we didn't get much feedback on this issue, which suggests most customer were either able to move to latest nuget versions or still continued with <=3.5.0 versions. Either case it doesn't seem like a high priority item at this time so we'll close it as won'tFix. If we get more community feedback on this, then we'll re-evaluate.
