### ISSUE TITLE
nuget locals help text still mentioned packages cache

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3592]
Problems with `nuget.exe locals -help`:
- Shows packages cache, which is no longer supported (https://github.com/NuGet/Home/issues/3591)
- Should mention `temp`
- The global packages folder is user-specific, not machine-wide
## Example

<pre>
usage: NuGet locals <all | http-cache | global-packages | temp> [-clear | -list]

Clears or lists local NuGet resources such as http requests cache, <b>packages cache</b> or machine-wide global packages folder.

options:

 -Clear                        Clear the selected local resources or cache location(s).
 -List                         List the selected local resources or cache location(s).
 -Help                    (?)  help
 -Verbosity                    Display this amount of details in the output: normal, quiet, detailed.
 -NonInteractive               Do not prompt for user input or confirmations.
 -ConfigFile                   The NuGet configuration file. If not specified, file %AppData%\NuGet\NuGet.config is used as configuration file.
 -ForceEnglishOutput           Forces the application to run using an invariant, English-based culture.

examples:

nuget locals all -clear

nuget locals http-cache -clear

<b>nuget locals packages-cache -list</b>

nuget locals global-packages -list

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference
</pre>

**Comment by mishra14** [comment]
Further
