### ISSUE TITLE
CoApp is dead

### ISSUE THREAD

**Issue by magol** [NuGet/Home#3594]
On [docs.nuget.org/ndocs/create-packages/native-packages](https://docs.nuget.org/ndocs/create-packages/native-packages), you say that you can use [CoApp](http://coapp.org/) to generate packages for C++ projects. The problem is that CoApp is only in beta stage, is dead and unsupported.

Is there no better alternative to suggest?

The documentation on how to create nuget-pack for C++ are nonexistent. I almost get the impression that you not support C++, that support for C ++ is more a hack.

**Comment by yishaigalatzer** [comment]
There is currently no good alternative yet for CoApp, and yes there is no good story for packing C++ packages.

@harikmenon we can add more info in the docs

**Comment by harikmenon** [comment]
@karann-msft : can you work with me on updating the language here?

**Comment by karann-msft** [comment]
Fixed

**Comment by magol** [comment]
https://github.com/NuGet/NuGetDocs/commit/4df939db55d9450963842d31be6bca5122be0df8

**Comment by yishaigalatzer** [comment]
Thanks @magol

**Comment by magol** [comment]
What a shame that there is no better option for C ++ :-(

Great that you removed the outdated information about CoApp. :-)
But now, the information about C++ is even more thinner. The information assumes that you are already well familiar with how NuGet works. If you do not have deep knowledge of how it works, it is almost impossible to create a NuGet package for C++ based on that information.

I think that it need a deeper explanation of how .Target and .Props works. And I think that a simple code examples is almost a requirement to get started.

Can you not build in functionality to create .target and .props into NuGet.exe?

I think this issue should be reopened in order to make the documentation more complete (or create a new issue). The minimum requirement should be that you at least easy can create you first simple NuGet packages based on the documentation.
