### ISSUE TITLE
Unable to restore from offline package source while offline

### ISSUE THREAD

**Issue by SeanKilleen** [NuGet/Home#3595]
This is a similar issue to those elsewhere on this repo, but not quite the same. I'm filing an issue though it may be a problem with my expectations.

This is not related to .NET core development.
## Versions
- Visual Studio Enterprise 2015 version 14.0.25241.03 Update 3 
- Nuget Package Manager 3.4.4.
- Windows 10
## Steps to Reproduce
- Take machine off internet  (disconnect wifi in this case).
- Copy nuget package folders into a central folder on my hard drive 
- Add an offline package source in the nuget settings within visual studio pointing to that folder
- Move that package source to the top of the source list
- Uncheck the other available package sources 
- Open the package manager console
- Select my offline package source explicitly from the package source drop down 
- Run Install-Package for a package that I know I have all of the dependencies for offline (e.g. xUnit)
## Expectation

The packages will be installed (this has worked for me in the past)
## Actual Behavior
- I receive the error message "Unable to load the service index for source https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/."

I don't believe I have the ability to add "--ignore-failed-sources" (as has been specified elsehwere) from the package manager console, and I can't find any corresponding setting within the cmdlet syntax or visual studio options.

This also happens when I specifically use the "-Source" option to specify my offline source.

Are my assumptions incorrect here? Are offline package restores still supported?

**Comment by yishaigalatzer** [comment]
From a cursory look I would assume that you didn't disable the source on the bottom of the UI?

![image](https://cloud.githubusercontent.com/assets/1238711/19161213/bd640da6-8ba7-11e6-938c-b8c1404a5a34.png)

**Comment by harikmenon** [comment]
We are working on detecting and making it easier to disable these sources. We have a rough spec that lays out some scenarios we are looking into. Any and all feedback is welcome :) Happy to get on a call to discuss any specific feedback you might have as well.

https://github.com/NuGet/Home/wiki/Package-Sources-Diagnostics

@karann-msft

**Comment by rrelyea** [comment]
@SeanKilleen - please confirm or correct @yishaigalatzer's assumption. I'm closing this issue now, assuming that he was correct.

**Comment by SeanKilleen** [comment]
@rrelyea After some more experimentation, it appears @yishaigalatzer's explanation is correct. (Thank you!)

I think my disconnect in this case was that I assumed package sources were searched in order. For example, when I searched "all sources", I assumed that it would search my offline nuget folder first before looking at the machine-wide package source.

To confirm: In order for offline nuget functionality to work, I have to not only add an offline folder and move it to top of the source list -- I have to un-check any package source with a URL so that the process doesn't error out. Is this correct?

**Comment by yishaigalatzer** [comment]
Yes, except the order doesn't really matter. Here is the logic:

First look at the cache, then all file based sources (because they are typically faster) if you find perfect matches, you are done. 

Then go to the http sources.

@harikm we should probably document it, and also add a tooltip to the up/down arrows explaining it

**Comment by SeanKilleen** [comment]
@yishaigalatzer I'm not sure that logic was followed in this case. I had all machine-wide package sources checked (which included the one with the URL). However, my file-based package source was the first one in my list of sources, and all other non-machine sources were unchecked.

if the logic as you described is followed, shouldn't it have hit my local package source (a file-based source), found the packages, and proceeded? This behavior happened even when I specified my offline source via the `-Source` parameter.   

I verified that it does pull from my offline package once that machine-wide source is un-selected, so it wasn't that my offline source didn't have the packages somehow.

Does nuget verify all package sources before applying the logic that you mentioned? If so, I can see how it would result in the behavior I experienced. If not, then it seems like there might be a different logic applied.

**Comment by yishaigalatzer** [comment]
It might need more info or there might be that the match is not perfect and then it goes online.

It would help to know what exactly you are restoring (project.json or packages.config).

Justin might know if I got the logic mixed up or is it only in 3.5 that it works this way

**Comment by SeanKilleen** [comment]
It's definitely a package.config restore. 

Was doing a quick demo of some testing tools so was creating two class libraries and looking to restore  xunit, specflow, and fluentAssertions -- all of which I'd copied from another project that I'd done for a similar demo previously.

I'll try to run some more tests to narrow it down.
