### ISSUE TITLE
NuGet.Packaging.Core assemblies are delay-signed/test-signed

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#3596]
I have a project that loads `NuGet.Packaging.Core` 3.4.3 and it worked for a while. I nuked my global packages repo and it was redownloaded. Now, it fails to load for strong name validation. When I run `sn -v NuGet.Packaging.Core.dll` I get the error:

```
Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

C:\Users\twsou\.nuget\packages\NuGet.Packaging.Core\3.4.3\lib\net45\NuGet.Packaging.Core.dll is a delay-signed or test-signed assembly
```

This happens with the `dnxcore50` version as well.

**Comment by twsouthwick** [comment]
btw seems like this is a repeat of an issue that looks like it was fixed #2690

**Comment by twsouthwick** [comment]
And if I download it directly from https://www.nuget.org/packages/NuGet.Packaging.Core/3.4.3 they are valid signatures - I only see it when I restore from the command line. I'll copy the fully signed ones into the package repro, but it seems like there may be some caching of the bad version somewhere

**Comment by jainaashish** [comment]
Already fixed as confirmed by customer.
