### ISSUE TITLE
Logging of nuget.exe push does not agree with source parameter

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3597]
## Steps

`nuget.exe push my.nupkg -Source https://www.nuget.org/api/v2/package`
## Expected

See an log message with an HTTP PUT to the same source URL.
## Actual

The log shows a forward slash appended:

<pre>
> nuget.exe push jvertestpackage.1.0.0.nupkg -Source https://www.nuget.org/api/v2/package
Pushing jvertestpackage.1.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT <b>https://www.nuget.org/api/v2/package/</b>
  Forbidden https://www.nuget.org/api/v2/package/ 529ms
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
</pre>

Most users won't care about this, but it is confusing since `https://www.nuget.org/api/v2/package` and `https://www.nuget.org/api/v2/package/` (with the trailing slash) are treated as different sources from the standpoint of `nuget.exe SetApiKey` but result in the same HTTP request.

Tested 3.6.0-beta1 (3.6.0-beta1-1942).

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. Thanks for helping us improve Visual Studio.
