### ISSUE TITLE
Remove noninteractive option from nuget.exe pack command

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3598]
It doesn't do anything. Pack doesn't use it.
Also remove it from documentation.

**Comment by karann-msft** [comment]
help for pack still shows this option. Will update docs once the help has been fixed.

**Comment by kraigb** [comment]
It's removed from the docs with NuGet/NuGetDocs#694; you can remove Type:Docs from this issue.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
