### ISSUE TITLE
Move NuGet.targets to contentFiles in NuGet.Build.Tasks

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3603]
NuGet.Build.Tasks currently contains NuGet.Targets under `runtimes/any/native/`  this should be moved to contentFiles. 

Previously contentFiles was not working when integrating into the CLI, possibly due to an older copy of the CLI without contentFiles support being used for the initial stage.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
