### ISSUE TITLE
Add end to end tests for MSBuild targets

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3605]
Restore and Pack can both be used directly from MSBuild. This is partially covered through NuGet.exe command line tests for Restore which uses the same targets.

To cover additional scenarios such as incomplete parameters there should be a new set of end to end tests that use MSBuild directly. This will need to be done in a way that allows for finding msbuild on the machine, and potentially for testing several versions of MSBuild.

**Comment by emgarten** [comment]
@rohit21agrawal is this complete for pack now?

**Comment by rohit21agrawal** [comment]
Yes

**Comment by jainaashish** [comment]
This is being covered as part of adding more and more e2e tests in apex which will also cover these scenarios.
