### ISSUE TITLE
Engineering: NuGet.Client should produce nupkgs using SemVer 2.0.0

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3606]
The NuGet.Client repo should make sure of SemVer 2.0.0 by producing nupkgs with release labels that include `.` instead of `-` for proper ordering.

Current: `3.6.0-rc-1950`

Expected: `3.6.0-rc.1.1950`

**Comment by bbowman** [comment]
would be super swell if this lifted the 20 character limit as well (20 characters per . separated portion perhaps?)

**Comment by emgarten** [comment]
@bbowman there's an issue for that here: https://github.com/NuGet/Home/issues/2735  Add your input and any scenarios you have where removing the limit would help there so we can prioritize what release the limit will be removed in.

**Comment by bbowman** [comment]
@emgarten added a comment to #2735 with an explanation of what I ran into.
