### ISSUE TITLE
ndocs ->Retargeting of Framework Message - no redirection

### ISSUE THREAD

**Issue by SabotageAndi** [NuGet/Home#3609]
This message is displayed in VS after changing framework of a project:

> Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. 
> Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  

Link goes to 404

Should go to https://docs.nuget.org/ndocs/consume-packages/reinstalling-and-updating-packages

**Comment by yishaigalatzer** [comment]
Thanks @SabotageAndi there are a few broken redirects on the new docs site, we will get the fixed ASAP.

**Comment by harikmenon** [comment]
Fixed https://github.com/NuGet/NuGetDocs/commit/f38e40cc66bda52b316f099f8086d9720fcb335f 

@karann-msft - Can you work with Kriag to make sure that updated pages have the right redirect?

**Comment by kraigb** [comment]
I'm checking all the redirects; this one will be fixed along with a number of others in an upcoming PR.

**Comment by kraigb** [comment]
@SabotageAndi This redirect was fixed with a publish in early January. Can you confirm and close?

**Comment by SabotageAndi** [comment]
I can confirm the fix.
