### ISSUE TITLE
Project and package reference conflict handling

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3612]
### Scenarios
- A project contains both a PackageReference to _A_ and a ProjectReference to a project that has the property or assembly name _A_
- Project -> PackageA and Project -> ProjectB and PackageA -> PackageB, here ProjectB should override PackageB since B was directly referenced. This matches the previous xproj behavior.
- Project -> ProjectA, Project -> ProjectB   where A and B both contain the same AssemblyName: X  (ambiguous reference X)

Tests should be added to cover these different combinations to ensure that the restore behavior stays consistent.

Restore should fail with a helpful message when it detects an ambiguous reference, and this behavior should be clear and documented.

**Comment by jainaashish** [comment]
This is not needed now, besides we're more focused on customer specific issues.
