### ISSUE TITLE
$(RestoreLegacyPackagesDirectory) should be respected at a project level by restore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3618]
This will allow projects targeting netcore 1.0.0 (and perhaps some other 1.0.x versions) to properly restore on case sensitive operating systems.

/cc @joelverhagen

**Comment by joelverhagen** [comment]
To be consistent with other restore switches, I am going to make call the MSBuild property `$(RestoreLegacyPackagesDirectory)`.

**Comment by rrelyea** [comment]
Need PR to integrate into CLI by 9pm tonight please.
Also need SDK synchronized to same bits.
please coordinate with livar and peter. will loop you into thread.
