### ISSUE TITLE
enabling Package reinstall from Package Manager UI

### ISSUE THREAD

**Issue by michaelAngeloEgypt** [NuGet/Home#3619]
Hi,
you describe in [this ](https://docs.nuget.org/ndocs/consume-packages/reinstalling-and-updating-packages) document how to reinstall a misconfigured package from the nuget prompt. Please target implementing this feature right from the Package Manager UI as not all team members are aware of the use of the nuget console. You can simply place a button below the buttons (Uninstall, Update) as in the image below

>  Update-Package –reinstall <package_name> 

![package manager new button](https://cloud.githubusercontent.com/assets/3001280/19196180/c6bb4e74-8cb4-11e6-8cd1-00531efc67f7.png)

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
