### ISSUE TITLE
NotImplementedException being thrown from a number of places. Fix it

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#362]

**Comment by johnataylor** [comment]
This tracks NuGet.PackageManagement and NuGet.VisualStudio. We would also like to move SimpleSearchBox into StandaloneUI.

**Comment by zhili1208** [comment]
Fixed NuGet.VisualStudio in https://github.com/NuGet/NuGet.VisualStudioExtension/commit/03f38f01161b50a9a319d54a6563cfe8f29fddb2
