### ISSUE TITLE
Issues when working with Visual Studio 2013

### ISSUE THREAD

**Issue by simon130** [NuGet/Home#3623]
Hi,

I see that when trying to install nugget package on Visual Studio 2013, it constantly asks me for credentials. We have ~8 nuget sources, but it asks more than 8 times for credentials. If I install nuget package from command line - it just works. Any clue what can cause that and how to work around that? I'd like to be able to use nuget in Visual Studio just like I can do from command line.

**Comment by rrelyea** [comment]
What types of NuGet sources do you connect to?  VSTS, NuGet.Server, etc...?
What version of NuGet are you using in Visual Studio 2013?

**Comment by simon130** [comment]
VSTS

**Comment by rrelyea** [comment]
What version of NuGet are you using in Visual Studio 2013?

**Comment by simon130** [comment]
2.12.0.817

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
