### ISSUE TITLE
Nuget Package Manager Installed Filter Behavior

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/Home#3626]
Just wanted to verify, is the filter behavior more strict (ie exact match) in the installed tab? I have a filter active in Browse tab that shows several of my installed packages. When I switch to the installed tab, they all disappear.

**Comment by rrelyea** [comment]
Can you give us the filter you are using, and the specific packages you are seeing in browse, but not install tabs?

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
