### ISSUE TITLE
unnecessary characters shown in NuGet window in VS 2015

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#3627]
I have created new UWP project in VS 2015 and opened NuGet window. There are some unrecognized characters there as shown in the snapshot
![1](https://cloud.githubusercontent.com/assets/16834561/19219359/b988384a-8e2e-11e6-88ee-79d8ade496e9.png)

**Comment by rrelyea** [comment]
looks like this is a problem in 5.1.0 of this package, that has been fixed in 5.2.2.
/cc @ericstj
