### ISSUE TITLE
Dotnet restore failed on Windows server 2012

### ISSUE THREAD

**Issue by Foroughi** [NuGet/Home#3628]
Hello
I am working on a project with the attached project.json. But Team City fails on restore step (dotnet restore --no-cache) .I`ve attached the log of TeamCity
Also I tried to run that command under administrator privilege , but the result is same as the TeamCity result. Let me raise this point that on my local system all work fine without any problem ! 
and --disable-parallel didn't help as well.

Dotnet --version output:
1.0.0-preview2-003133

[project.txt](https://github.com/NuGet/Home/files/518223/project.txt)
[SystemTicket_Build_59.txt](https://github.com/NuGet/Home/files/518225/SystemTicket_Build_59.txt)

**Comment by emgarten** [comment]
From the log it appears that restore is hitting network issues and timing out. Are you able to download the same packages to that machine manually?

**Comment by Foroughi** [comment]
hi , sorry for the delay
Yes I`ve checked 3 of them and all can be downloaded from my browser correctly

**Comment by jainaashish** [comment]
@Foroughi Apology for not following up until now, but are you still facing this issue with latest dotnet? If yes please share us the updated logs and if possible repro sln.
