### ISSUE TITLE
[Test Failure] Version.txt didn’t created under the installed package folder after installing package ‘TestPackage.SupportingMultipleFrameworks.1.2.0’

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3629]
**Repro Steps:**
1.  New a VB ClassLibrary project.
2.  Open ‘Manage NuGet Packages…’ and click ‘Browse’ tab.
3.  Install package ‘TestPackage.SupportingMultipleFrameworks.1.2.0’.
4.  Check the version.txt under C:\school[ProjectName]\TestPackage.SupportingMultipleFrameworks.1.2.0

**Expected Result:**
There is a version.txt file under the package folder as below screenshot.
![expected](https://cloud.githubusercontent.com/assets/20632625/19219843/9f74f188-8e50-11e6-8985-f9a9f676195c.png)

**Actual Result:**
There is no version.txt file under the package folder as below screenshot. The file was moved under 'tools' folder.
![noversionfile](https://cloud.githubusercontent.com/assets/20632625/19219846/a9e42d50-8e50-11e6-8e1a-5c3db3586e04.png)

**Note:**
1.  It happened on Dev14 MU3.5 25431.01+NuGet 3.6.0-RC-1968.
2.  It doesn’t repro on Dev14 MU3.5 25431.01+NuGet 3.5.0-RTM-1938.
3.  It doesn’t repro on Dev14 MU3.5 25431.01+NuGet 3.6.0-Beta1-1954.
4.  It doesn’t repro on NuGet 3.4.4.1321.

**Comment by rrelyea** [comment]
Concerned here because this looks like a behavior change for packages.config scenarios. Please work with @emgarten as needed.

**Comment by joelverhagen** [comment]
@mishra14 and I looked at this. This is a regression caused by https://github.com/NuGet/NuGet.Client/commit/4cccb13833ad29d6a0bcff055460d964f1b49cfe. There is a faulty assumption that `install.ps1` is always directly under the `tools` directory.

**Comment by mishra14** [comment]
@v-luzh : I have fixed this in https://github.com/NuGet/NuGet.Client/pull/935

Please test with dev build 1985 to validate.
