### ISSUE TITLE
Parsing a .NET Standard targetting PCL should properly recognize short name

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#3630]
This test fails:

```
    [Fact]
    public void when_getting_folder_name_for_pcl_then_gets_netstandard()
    {
        var tfm = ".NETPortable,Version=v5.0";
        var folder = NuGetFramework.Parse(tfm).GetShortFolderName();

        // 1.x or whatever
        Assert.Equal("netstandard1.4", folder);
    }
```

It should pass in some form. Out of the box, PCLs targetting .NET Standard are reported as "portable50". There should be a straightforward way to determine a project targets a certain version of .NET Standard (currently, there's no target framework profile to check, and the version is just "5.0" so it's not very useful either.

**Comment by kzu** [comment]
cc @rrelyea @yishaigalatzer

**Comment by jainaashish** [comment]
@kzu did you find a workaround? still relevant?

**Comment by kzu** [comment]
Well, in the latest VS2017, a class library reports `TargetFrameworkMoniker = .NETStandard,Version=v2.0` (or `TargetFrameworkMoniker = .NETStandard,Version=v1.6`), so I  think this is no longer relevant
