### ISSUE TITLE
Package Version - Support for Major.Minor.Build.Revision

### ISSUE THREAD

**Issue by bednart** [NuGet/Home#3632]
Hi,
I was trying to find the answer but without any clear result. I' am using **NuGet 3.5.0-beta2** CMD to create and publish packages to our own NuGet server. And my problem is how to version packages.

As described in documentation [here](https://docs.nuget.org/ndocs/schema/nuspec) "_version  - The version of the package, in a format like 1.2.3._" So it tells me that only A.B.C version is allowed which comes from [SemVer](http://semver.org/). But then there is example of [nuspec](https://docs.nuget.org/ndocs/create-packages/creating-a-package) where A.B.C.D is shown _"<version>1.8.3.331</version>"_

So where is the true?

I'm creating packages based on csproj and in AssemblyInfo.cs file I'm using **[assembly: AssemblyInformationalVersion("1.2.3.4")]**. This version is used in nuspec based on **<version>$version$</version>** element. Created package has right version 1.2.3.4 and I can use it in my projects without any trouble.

So my question is. Will there always be support for A.B.C.D version in next NuGet versions? And in general is it reasonable to use it or should I stay with A.B.C version as desribed by SemVer?

Thanks in advice,
Tomáš

**Comment by davidfowl** [comment]
> I'm creating packages based on csproj and in AssemblyInfo.cs file I'm using [assembly: AssemblyInformationalVersion("1.2.3.4")]. This version is used in nuspec based on $version$ element. Created package has right version 1.2.3.4 and I can use it in my projects without any trouble.

You should be doing the inverse. Making your assembly version based on the package version.

You should assume semver for package versions. The only reason nuget supports 4 part versions is because when we originally started, we followed assembly versions.

**Comment by bednart** [comment]
So it is better to set package version in nuspec file instead of AssemblyInfo.cs and propagate this version somehow (automatically) to AssemblyInformationalVersion during build?

And ok I will stay with 3 part versions ;)

**Comment by bednart** [comment]
So my final solution is to set 3 part version in nuspec and write this version to AssemblyInfo.cs during build. Thanks for help.
