### ISSUE TITLE
Restore logging in VS doesn't always show

### ISSUE THREAD

**Issue by balachir** [NuGet/Home#3633]
**INSTALL STEPS**
WPT.25810.00
Add private MyGet feeds to Package Manager Settings

**REPRO STEPS**
1. Open VS, File > New Console Application (.NET Core)
2. Right-click solution > Restore packages

**ACTUAL**
You get this dialog for a second or two and then it goes away
![image](https://cloud.githubusercontent.com/assets/8246794/19281069/4034f1c0-8f9d-11e6-9a5c-b39f190c3b06.png)

If I delete the %userprofile%.nuget folder and repeat step 2 above, then I get messages like this in the dialog
![image](https://cloud.githubusercontent.com/assets/8246794/19281105/78200674-8f9d-11e6-81ff-5db04866d3d5.png)

Once restore completes, the dialogs above simply go away and there's no way to go back and see the restore logs and what packages got restored

**EXPECTED**
Restore logs should be sent to the Output window. That way users can go back and see the restore logs, similar to the behavior with .NET Core tooling in Dev14.

**Comment by emgarten** [comment]
NuGet pops up a modal dialog while restoring. Is a restore actually taking place? Do you see the assets.json file appear after it completes? Are you able to build while the restore is taking place?

**Comment by balachir** [comment]
Restore is taking place. Updated the repro steps above to clarify my ask, thanks.

**Comment by emgarten** [comment]
Thanks @balachir, the updated steps help. I've noticed a behavior change around this also, I'll investigate to see where the log messages are being dropped.

**Comment by rrelyea** [comment]
Might also affect 3.5

**Comment by rrelyea** [comment]
Do we think this is affecting .net core only, or p.c and p.j too?

**Comment by rrelyea** [comment]
@zhili1208  - please figure out how this compares to uwp/p.j in 3.x and to .net core in vs2015

**Comment by zhili1208** [comment]
uwp/p.j in 3.x and .net core in vs2015 all doesn't have restore logs in output windows

**Comment by rrelyea** [comment]
@balachir  - We plan to address post-RC, as this isn't a blocker, as it is not a regression from preview2 tooling experience. Please yell if any of our analysis is wrong there.

**Comment by balachir** [comment]
@rrelyea, @zhili1208 , this is a regression from the experience in Dev14 though. Restore logs definitely did go into 'Package Manager' Output window pane in Dev14 for ASP.NET Core projects.

![image](https://cloud.githubusercontent.com/assets/8246794/19791069/a5939288-9c72-11e6-9a05-7e84d1731a19.png)

**Comment by jainaashish** [comment]
@balachir the logs you've pasted are from dotnet tooling auto restore and not from solution restore scenario. Even in Dev14 if you click restore on solution, it will not log anything in output window.

But there is a workaround for this, these solution restore logs are written under Build in output window. So if you build the solution once (even though it fails) and then do solution restore then it will write these restore logs in output window for dev14 as well as dev15.

Although this is regression for auto restore from dev14 to dev15 since we aren't writing logs for new auto restore for .net core project (CPS based) @alpaix we need to discuss this tomorrow and finalize on this.

**Comment by rrelyea** [comment]
Think about the experience for all scenarios.

**Comment by jinujoseph** [comment]
I still don't see any output in the output window.
The only information i have about restoring is in the info bar below.

![image](https://cloud.githubusercontent.com/assets/12449387/20069281/cd812556-a4d0-11e6-9daa-5efca3fbaec8.png)

which is lost once restoration completes , is that expected ? I would have expected the output window to display the packages restored.

**Comment by rrelyea** [comment]
Ashish- where did we end up with in RC with this?

**Comment by jinujoseph** [comment]
I filed a new bug for this https://github.com/NuGet/Home/issues/3884

**Comment by jainaashish** [comment]
We don't log auto restore messages to build output window since previous messages were from DotNet. NuGet only logs restore success or failure or noop message in build output window. We just changed to activate this window even without building the solution.

**Comment by KristinXie1** [comment]
This issue is still repro on build [d15prerel.26105.05](\\cpvsbuild\drops\VS\d15prerel\products\26105.05\bootstrappers\Enterprise\vs_enterprise.exe).
