### ISSUE TITLE
Automate offer suggestions for NuGet packages

### ISSUE THREAD

**Issue by SupporterMan** [NuGet/Home#3634]
While upgrading an older VS solution to VS 2015, it complained about MVC v3 references and I was able to update them to v5.2.3 and also related ones, but that got me thinking, it would be nice to have a tool that analyzes all of the non-NuGet references in a solution and offers suggestions to be migrated to their equivalent NuGet packages. This way, I can easily upgrade or downgrade as needed and have links to their corresponding NuGet profile pages.

**Comment by sonnypdx** [comment]
It would be great if this is offered as another tab (similar to Browse, Installed, Updates, & Consolidate) in the NuGet Package Manager for Solution.  For each project, it would show the list of references and for each reference show possible NuGet Package matches.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
