### ISSUE TITLE
NuGet Server creates temp files in  C:\Windows\Temp\nuget in server

### ISSUE THREAD

**Issue by NagarajMasub** [NuGet/Home#3635]
Hi,

we have our own nuget feed in our server,we are using NuGet.Server . C:\Windows\Temp\nuget in this location there are more than 100 gb of nuget files are stored, due to this my server gets hanged, how can i resolve this. Please update me as soon as possible

**Comment by rrelyea** [comment]
@qianjun22

**Comment by NagarajMasub** [comment]
Hi Guys,

Any update on this..?

**Comment by rrelyea** [comment]
CLosing this issue. Believe that NuGet Server issues should be filed in the NuGetGallery repo. Ported your issue to: https://github.com/NuGet/NuGetGallery/issues/3275
