### ISSUE TITLE
Nuget Installing

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#3636]
I'm trying to install Nuget package from C# code, it is downloading the folder but not installing the nuget packages. Please help me to solve the problem.

**Comment by rrelyea** [comment]
Please give details of what code you are executing, using which components (and versions), and how it is failing.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
