### ISSUE TITLE
If importing *.nuget.props/targets, add them to MSBuildAllProjects

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#3644]
The Microsoft common targets use the [MSBuildAllProjects](https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L521-L522) property to make it easy for targets to depend on changes to all project-modifying targets. 

NuGet contributes two key project-modifying imports of its own: [project].nuget.props and [project].nuget.targets, yet these aren't added to that property. 

The `Microsoft.NuGet.props` currently has:

```
  <Import Project="$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.props" Condition="Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.props') AND '$(IncludeNuGetImports)' != 'false'" />
```

It should add:

```
<PropertyGroup Condition="Exists('$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.props') AND '$(IncludeNuGetImports)' != 'false'">
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildProjectDirectory)\$(MSBuildProjectName).nuget.props</MSBuildAllProjects>
</PropertyGroup>
```

And the `Microsoft.NuGet.targets` should do the same.

**Comment by harikmenon** [comment]
adding @rrelyea. We will pick this up in triage today.
