### ISSUE TITLE
Allow a project with Any TFM to install any package

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#3647]
NuGet packaging projects should be able to reference any package, regardless of the 
target frameworks they support. 

Currently, none of the following TFMs in the nuget packaging project work for this scenario:
- NuGet,Version=v1.0
- Any,Version=v0.0
- Agnostic,Version=v0.0

They all result in errors like: `Package Newtonsoft.Json 9.0.1 is not compatible with any (Any,Version=v0.0) / win.`

NuGet restore should properly recognize one or all of them and assume there's no need to check for compatibility.

**Comment by emgarten** [comment]
@kzu can you give a scenario where this is useful? 

`nuget.exe install` runs the install with `Any` and it is seen as problematic, here is an example of where it gets into trouble.

```
PackageA
 |- net45 -> PackageB
              |- native -> PackageX
 |- native -> PackageC
 |- win8 -> PackageD
```

In the above dependency graph the target frameworks do not have a relationship that can be used to determine which path should be follow. The user ends up with an arbitrary set of packages, which would probably be: PackageA and PackageB. net45 is selected over native, but later native is used still even though net45 and native are not compatible. Everything is compatible with Any and only 1 option can be selected for each decision.

To actually select the assets needed for a package would be even more difficult (nuget.exe install doesn't handle this), and you could end up consuming a dll for a future framework that is not supported since the highest compatible one is used. For example if the package has net45 and net60, net60 will win since Any supports net60.

This could only work if the packages being installed had only one framework.

**Comment by kzu** [comment]
Here's the scenario: https://github.com/NuGet/Home/wiki/NuGetizer-3000

Install should only add the PackageReference (or entry in project.json), nothing more. In this case, all it has to do is add a reference to PackageA. It doesn't matter what other transitive dependencies exist. That's the purpose of another part, which is resolving the referenced package assets to use, which can trivially be disabled by `<ResolveNuGetPackages>false</ResolveNuGetPackages>`. 

So currently, you can disable the resolution, but you can't install anything, which seems wrong.

**Comment by emgarten** [comment]
So what you need is a way to force adding a reference to the package, and to not restore or do any checks on the nuget side after?

**Comment by kzu** [comment]
well, I only need a way for ResolveNuGetPackages=false to be honored after the reference is added :). Which I thought would happen automagically :)

**Comment by kzu** [comment]
Ok, I've been trying to submit a PR that would essentially honor the `ResolveNuGetPackages=false` project  "metadata" and not perform a restore but just install in that case, without much success.

There are many places where this logic could go, and I'm sure I can make an informed call as to which is the right one, so I'd better leave you to do it. I looked at the [BuildIntegratedRestoreUtility](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/BuildIntegratedRestoreUtility.cs#L106) (since we only want this behavior maybe for project.json-based projects? Is the new PackageReference-based project also going to be a "build integrated nuget project"?) and also the [NuGetPackageManager](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L2216) but I think the RestoreCommand invoked from the nuget.exe should also honor the opt-out, so obviously those places aren't the "right" ones...

**Comment by kzu** [comment]
Basically the issue here is that Xamarin Studio can trivially modify the behavior of what installing a nuget package means for the packaging project, and we (obviously) don't want to rewrite the entire GUI for browsing packages for the VS experience ;). They even had `<PackageReference>` working instead of `project.json`, but we can't depend on that yet, I guess?

**Comment by kzu** [comment]
@mhutch @mrward FYI

**Comment by kzu** [comment]
For now, the following hack worked (adding `imports` to the widest possible .NET): 

```
{
  "dependencies": {
    "EntityFramework": "6.1.3",
    "Newtonsoft.Json": "9.0.1",
    "NuGet.Build.Packaging": "0.1.106-dev"
  },
  "frameworks": {
    "NuGet,Version=v1.0": {
      "imports": "netstandard1.6"
    }
  },
  "runtimes": {
    "win": {}
  }
}
```

Ideally, we should switch to a build of NuGet that already does the PackageReference thing...

**Comment by mrward** [comment]
Some NuGet packages fail to install for me, such as NUnit and Moq, with just the netstandard1.6 import. I am assuming we would need to add imports for other frameworks.

**Comment by kzu** [comment]
Yes, I had to add many more imports afterwards

**Comment by jainaashish** [comment]
@kzu seems like you already have a workaround for this, besides this isn't the streamline scenario for NuGet. So I'm going to close it as wont fix for now. If you feel otherwise, let us know and we can re-evaluate.

**Comment by kzu** [comment]
The workaround is the ugliest ever: https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.Authoring.props#L16

Here's another scenario where it would have been super useful: https://github.com/kzu/corebuild (applied the exact same rabbit at https://github.com/kzu/corebuild/blob/master/src/build/corebuild.props#L10-L11).

:(
