### ISSUE TITLE
Inconsistency between packages folder and project's packages.config

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#3648]
This is a question and possible suggestion:

In a solution with several projects, if the list of packages in the current packages folder differs from the union of the packages from all of the projects' packages.config files, bring this to a user's attention.

Not sure how you feel about this, but we have some solutions (historic) that are in this state, and it becomes confusing when someone has added hard references to assemblies in the packages folder that won't be regenerated when another developer pulls the code from Git.

When they do this the system will restore all the packages it needs but of course it won't fetch a package that isn't listed in any of the packages.config files, so the solution ends up not building because some of the projects have hard references to assembly DLLs in the packages folder.

Maybe have some command on the solution's context menu "Check NuGet Integrity" or something? Perhaps that command could also have an option for "Add Orphan Packages"? This is a command that would be helpful in rapidly resolving/explaining some of the obscure problems and could be used by the "owner" of a solution before committing changes to Git.

Thoughts?

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
