### ISSUE TITLE
Details of the package are not displayed in VS 2015

### ISSUE THREAD

**Issue by axunonb** [NuGet/Home#3649]
After installation of package MailMergeLib there are no details shown on the package property window, like Description, Version, Authors, License etc. Everything below "Options" is blank.
In NuGet Package Explorer everything looks fine.
Can't figure out a reason for this behavior. Any hint appreciated.
Package: http://www.nuget.org/packages/MailMergeLib/

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
