### ISSUE TITLE
Completely remove any public methods related to legacy or msbuild based package restore from PackageManagement and Visual Studio extension

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#365]
Completely remove any public methods related to legacy or msbuild based package restore from PackageManagement and Visual Studio extension

Also, as a clean-up put each class in a separate file

**Comment by jainaashish** [comment]
We had a major refactoring in 15.3 timeframe to get rid of most of these issue. But we can't just get rid of all the public APIs which customers has already taken dependency. We're gradually making all our public apis available via IVS template wizard.
