### ISSUE TITLE
VS2015 "Manage Packages" can't see where packages are installed w/o internet

### ISSUE THREAD

**Issue by robertmclaws** [NuGet/Home#3651]
## Problem

If your internet connection goes down for some reason, the NuGet "Manage Packages" UI will show you which packages are installed in your solution, but will NOT load up the right-hand list showing which packages are installed in which project. 
## Expected Behavior

As each project has a packages.config or a project.json, an internet connection should not be necessary to make that determination.
## Steps to Reproduce
- Open a complex Visual Studio solution
- Disable your internet connection
- Right click the solution in the Solution Explorer and select "Manage NuGet Packages for Solution"
- Click the "Installed" tab.
- Scroll the list of installed packages.
- Click several different ones, and watch as the right-hand pane fails to load as you switch packages.

**Comment by emgarten** [comment]
@robertmclaws what version of NuGet are you using?

**Comment by robertmclaws** [comment]
Visual Studio says I'm using version 3.5.0.1484.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
