### ISSUE TITLE
dotnet restore3 is not restoring tools dependencies correctly

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#3652]
I ran into this when working on https://github.com/dotnet/cli/issues/4366.

To test this out I created a test project here: https://github.com/livarcocc/cli-1/blob/projectdependenciescommandresolver/TestAssets/TestProjects/MSBuildTestAppWithToolInDependencies/MSBuildTestAppWithToolInDependencies.csproj. This project has a tool dependency whose job is to then use the ProjectDependenciesCommandResolver to invoke a project dependency tool that is also set in the project.

The tool is here: https://github.com/livarcocc/cli-1/tree/projectdependenciescommandresolver/TestAssets/TestPackages/dotnet-invoke-portable.
The project dependency tool is here: https://github.com/livarcocc/cli-1/tree/projectdependenciescommandresolver/TestAssets/TestPackages/dotnet-portable

This code fails because when running the tool, it fails to load a dependency of the tool: Microsoft.DotNet.Cli.Utils.

This only happens when I use dotnet restore3 to restore the tool. If I restore the tool first using dotnet restore instead and then run dotnet invoke-portable for the test project, then it succeeds. I haven't done the exercise of running a diff between the good and bad project.assets.json files for tool. But one thing I noticed is that under the good Microsoft.DotNet.Cli.Utils node in the assets file, the dlls were under lib/netstandard1.5, while for the bad one they were showing under netstandard1.5 only.

Also note that this is blocking https://github.com/dotnet/cli/issues/4366.

**Comment by emgarten** [comment]
I am not able to get this to work. Following the directions above I get an error due to the tool package missing imports for newtonsoft.json 7.0.1 which is referenced by Microsoft.DotNet.ProjectModel, adding a 9.0.1 reference to dotnet-invoke-portable fixes the restore problem.

The lock file for the tool has lib/netstandard**1.6**/ for Microsoft.DotNet.Cli.Utils

I may have a different mix of packages but I was trying to clone the repositories mentioned and packed from those.

Running the tool with `dotnet.exe invoke-portable` gives:

```
Unhandled Exception: Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-portable"
```

Can you share the lock files and possibly the packages needed?

**Comment by livarcocc** [comment]
The packages are these. Had to change them to zip for github to let me upload them.
[dotnet-invoke-portable.1.0.0-rc-003846.zip](https://github.com/NuGet/Home/files/527918/dotnet-invoke-portable.1.0.0-rc-003846.zip)
[dotnet-portable.1.0.0.zip](https://github.com/NuGet/Home/files/527917/dotnet-portable.1.0.0.zip)

These are the tools assets.json files. Again, had to change the extension to txt for github:
This is the one that was generated through restore3 and does not work: 
[project.assets.txt](https://github.com/NuGet/Home/files/527923/project.assets.txt)
This one was generated with restore and works:
[project.assets.txt](https://github.com/NuGet/Home/files/527963/project.assets.txt)

Let me know if this helps.

**Comment by emgarten** [comment]
I've tracked this down to tool projects resolving packages to project.json projects through global.json and sibling directories. 

The workaround is to remove global.json and any projects that would conflict with package names.

I'll make a fix for this on the nuget side. 

Also, the sooner we can drop xproj restore the easier it will be for NuGet here.

**Comment by rrelyea** [comment]
per @yishaigalatzer's recommendation, we may want to skip a fix in nuget for this now. @livarcocc - would the workaround work for now?

**Comment by emgarten** [comment]
@rrelyea part of the problem here is that xproj resolution is happening for non-xproj projects including .NETCore csproj projects. I think it may make sense to make a small change which blocks that, and then remove all of it when xproj goes away.
