### ISSUE TITLE
Wrong version of System.Net.Http.Formatting.dll restored

### ISSUE THREAD

**Issue by joostvz** [NuGet/Home#3653]
Please see my attached solution. The structure is like this:
- ClassLibrary1 (depends on CacheCow and Microsoft.AspNet.WebApi.Client (System.Net.Http.Formatting.dll) nuget packages
- ClassLibrary2 (has a project reference to ClassLibrary1)

I've updated all nuget packages to the latest version; CacheCow requires version 4.0.3 of Microsoft.AspNet.WebApi.Client, but I use the latest version in my project, version 5.2.3. When I (re-)build ClassLibrary2, version 4.0.3 of the System.Net.Http.Formatting.dll is placed in the bin folder.  According to the build log, this file is found in the _C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Assemblies\_ folder. This creates a runtime error, because all app.config files redirect this dll to version 5.2.3.

Note: the issue is fixed when I add a reference to the nuget package Microsoft.Bcl.Build. In the sample I've attached, a warning will be shown that tells me to add this package. However, I've faced this issue in the source code of my company, where this warning isn't shown.

[NuGetVersionIssue.zip](https://github.com/NuGet/Home/files/526667/NuGetVersionIssue.zip)

**Comment by rrelyea** [comment]
What version of VS and NuGet are you using?

**Comment by joostvz** [comment]
I'm using VS 2015 Update 3, NuGet package manager is on version 3.4.4.1321.

**Comment by joostvz** [comment]
@rrelyea: Any news on this issue?

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
