### ISSUE TITLE
Get VSIX into build workload

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3660]
and do a design discussion post RC for updating story (nuget, etc...)

**Comment by dasMulli** [comment]
Is this still planned so that we can be sure that all combinations of `<PackageReference/>` and classic + sdk-based projects work on Build Tools? Or is it no longer needed going to be needed?

**Comment by niemyjski** [comment]
I'm also running into this with my classic desktop app. I installed Roslyn and it was installed only as a packagereference and now msbuild fails to compile the project because the project reference isn't sent along as a build reference.. I even updated the tools version.

**Comment by alpaix** [comment]
Actual work is track'd in #5562. Closing this one as dupe.
