### ISSUE TITLE
List of All NuGet Target Directories

### ISSUE THREAD

**Issue by falahati** [NuGet/Home#3662]
Hey guys,
I tried searching through documentations and google but found no page to list all valid nuget target directories. I have a situation in which I need to add multiple multi-platform projects in one nuget package using bait and switch pattern but I need a complete list of supported nuget target directories to make the nuspec file.
Even pages referenced in documentation about PLC profiles are old and invalid by now. And there is no information about Xamarin or other target platforms anywhere.

It would be great if some one could put me in right direction, thank you

**Comment by mrward** [comment]
The target frameworks are documented on the nuget.org site:

https://docs.nuget.org/ndocs/schema/target-frameworks

This includes the PCL profiles, .NET Standard and the Xamarin frameworks.
