### ISSUE TITLE
Nuget double-writes packages causing access denied in builds.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#3666]
in version 3.5.0.1938 of nuget.exe

If you run nuget restore on a packages.config that contains the same nuget package simultaneously then then each nuget process will try to install the nuget package.

I will add a comment to the repro steps and screen shot of procmon trace.

**Comment by kingerja** [comment]
\joshking-main\dump\nuget\issues\3666
If you run start procmon and run repro.cmd locally it should repro.
See procmon.jpg for procmon info.
See cmdoutput.jpg for command output.

**Comment by kingerja** [comment]
This is a regression of
https://github.com/NuGet/Home/issues/2628

**Comment by rrelyea** [comment]
@zhili1208  - not yet approved for 3.5.0-rtm, but please investigate

**Comment by kingerja** [comment]
Please note this appears to work in 3.5.0.1737.

**Comment by zhili1208** [comment]
@kingerja  I tried your repro, but I couldn't get the same procmon log, on my machine, only one process wrote files to disk.

**Comment by zhili1208** [comment]
Here is the log: 
there are two nuget.exe processes, PID 28536 and PID 16676
![writefile](https://cloud.githubusercontent.com/assets/7131513/19451182/2a0e7a56-9461-11e6-8b63-cc8191914345.PNG)

![readfile](https://cloud.githubusercontent.com/assets/7131513/19451198/385fbf7a-9461-11e6-952e-b1d29ef5fa7a.PNG)

NuGet.exe 28536 wrote all files to disk and NuGet.exe 16676 only read files, there are no write operations in 16676 log

**Comment by kingerja** [comment]
That's not good.

I retried my same repro in the same window running the same command and I am unable to repro it as well.  Leading me to suspect either something with my machine state has changed.  my repro.cmd previously just used nuget instead of nuget.exe so I went and tried all the different versions of nuget I am running on my machine to see if it was pulling a bad version for what ever reason.  However it was selecting the nuget.exe in the current folder as it should and results did not change so I am at a loss to why it isn't reproducing anymore.

However my builds are failing with a write after read build cop error.  This package is being re-installed during the build.  (Unfortunately these builds take 8 hours to run so using them as a repro is less then ideal.)  One interesting thing with the build cop failures is it doesn't report it for the same package everybuild.  This may suggest a transient behavior but in what way I don't know.

Now technically the buildcop issue being reported is a write after read which just implies the package is being re-installed it was my procmon repro that produced the installing in parallel theory which could also exhibit in this fashion.

Anyway I will keep digging into this to get a better understanding of the scenario that is triggering my issues.

Buildcop error below I am seeing with new version of nuget.  I do not see this with the rc1 build.

200>d:\b\s1\sources\buildcop : error : BC00003 : WriteAfterRead : Write after read was detected for file 'D:\NugetPackages\2014-06-23\FluentAssertions.3.3.0\lib\net45\FluentAssertions.Core.dll'. It was read in project d:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\Server\UpgradeScripts\UnitTests.Microsoft.ReportingServices.UpgradeScripts.csproj (target 'ResolveAssemblyReferences', task 'ResolveAssemblyReference', process 'D:\B\S1\Sources\tools\msbuild\12.0\bin\MSBuild.exe') and later updated in project 'd:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\DataExtension\SapBw\SapBwUnittests.csproj' (target 'PullNugetPackages', task 'Exec', process 'D:\B\S1\Sources\Tools\Nuget\NuGet.exe'). For more info see http://codebox/eebuild/Wiki/BC00003.200>d:\b\s1\sources\buildcop : error : BC00003 : WriteAfterRead : Write after read was detected for file 'D:\NugetPackages\2014-06-23\FluentAssertions.3.3.0\lib\net45\FluentAssertions.Core.dll'. It was read in project d:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\Server\UpgradeScripts\UnitTests.Microsoft.ReportingServices.UpgradeScripts.csproj (target 'CoreCompile', task 'Csc', process 'D:\B\S1\Sources\Tools\MSBuild\12.0\Bin\Csc.exe') and later updated in project 'd:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\DataExtension\SapBw\SapBwUnittests.csproj' (target 'PullNugetPackages', task 'Exec', process 'D:\B\S1\Sources\Tools\Nuget\NuGet.exe'). For more info see http://codebox/eebuild/Wiki/BC00003.200>d:\b\s1\sources\buildcop : error : BC00003 : WriteAfterRead : Write after read was detected for file 'D:\NugetPackages\2014-06-23\FluentAssertions.3.3.0\lib\net45\FluentAssertions.Core.dll'. It was read in project d:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\Server\UpgradeScripts\UnitTests.Microsoft.ReportingServices.UpgradeScripts.csproj (target '_CopyFilesMarkedCopyLocal', task 'Copy', process 'D:\B\S1\Sources\tools\msbuild\12.0\bin\MSBuild.exe') and later updated in project 'd:\b\s1\sources\testsrc\Rosetta\Tests\UnitTests\DataExtension\SapBw\SapBwUnittests.csproj' (target 'PullNugetPackages', task 'Exec', process 'D:\B\S1\Sources\Tools\Nuget\NuGet.exe'). For more info see http://codebox/eebuild/Wiki/BC00003.200>msbuild /noautoresponse @d:\b\s1\sources\tools\winsdk\tools\MSBuild.rsp /Target:Build failed - rc = 1

**Comment by zhili1208** [comment]
one question, the path "D:\NugetPackages\2014-06-23\" is repository path, right? what's the global packages folder path?

**Comment by kingerja** [comment]
That is the directory the packages are installed to.  So that error is saying that a project already read the references in that folder and the package was installed again (overwritten) at a later time.

That symptom may be related to the procmon doublewrite I was seeing and it may be an issue with the package re-installing when it shouldn't which would be a different issue.  It is just this issue that prompted me to run procmon which showed the package being installed by both invocations.  Of course the parallel install no longer repo's so ...

**Comment by rrelyea** [comment]
[‎10/‎18/‎2016 1:39 PM] Josh Kingery: 
So the issue is the long running builds I have which were showing the build cop error are broken at the moment so I can't use them for a repro.
The local repro doesn't work for me any more either.  Leaving me to conclude that this issue is likely a transient issue if not just an issue between my keyboard and chair.
Which would dictate the issue should probably not hold RTM.
I do wonder if perhaps there could be some external factor with the feeds or cred provider that could of caused this state and that that issue was cleared up.  But I don't know the code on if that would be even a possibility.

Me: ok josh. thanks for raising this issue. we will resolve it not repro for now. if you see this again, please yell.
