### ISSUE TITLE
Fail to install Neo4j.Driver NuGet on a .NetPortable solution

### ISSUE THREAD

**Issue by Rivierg** [NuGet/Home#3667]
Hello, I have an issue when trying to install the Neo4J.Driver NuGet. 

I have a PCL project, and 3 platform projects for Android, iOS and UWP. in VS2015.
I am trying to install the Neo4J.Driver NuGet, but I get the following errors. However it seems to have installed on UWP .
-  On the PCL:
  
  >  Could not install package 'Neo4j.Driver 1.0.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
-  On Android:
  
  >   Could not install package 'System.Reflection.Extensions 4.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My NuGet Package Manager version is My NuGet version is 3.4.4.

I have these targets in the project: .Net Framework 4.5, ASP.NET Core 1.0, Windows 8.1, Windows Phone8.1, Windows Phone Silverlight 8, Xamarin.Android, Xamarin.iOS.

I tried to understand how to fix the issue reading (#1325) or (dotnet/corefx#5955) but I don’t really understand what is going on.

Thank you in advance

**Comment by bytebuilder26** [comment]
Hi @Rivierg,
I am running into the same issue when trying to use neo4j in a xamarin forms mobile app.

Were you able to find a workaround for this? any ideas that may work?
thanks!!

**Comment by jainaashish** [comment]
This is a legit error since the package is not supported on the corresponding project's target framework. You can try to create a new .netstandard based pcl project in VS 2017 which targets .netstandard2.0 which is compatible with .net46 full framework which might work for you.
