### ISSUE TITLE
Content only packages

### ISSUE THREAD

**Issue by gerritgoetzen** [NuGet/Home#3668]
Nuget complains on installing _content only_ packages that are created without any assembly to a reference. The package is created from a _convention-based working directory_ with only a _build_ folder. The same problem seems to occur with a _content_ folder only ([reference](http://stackoverflow.com/q/37064746/2271552)).

The installation (NuGet Package Manager for VS 2015 v3.4.4.1321) fails with an error like: 

> Install-Package : Could not install package 'My-content-only-package 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

The solution is to add an empty _lib_ folder to the root package directory. This is not obvious (no error or warning while packing) and a little cumbersome and therefore I would treat that behavior as a bug.

**Comment by iernie** [comment]
Any news on this?

**Comment by emgarten** [comment]
Content and Build are both counted as assets. If you are seeing the error above it means that there are zero files in the package that apply to your target framework.

Please share what version of NuGet you are using, the project Target Framework, and the package if you are seeing different behavior.

**Comment by iernie** [comment]
Yeah, I found out I needed to have the files in a folder named "content" for it to work :) Thanks!

**Comment by emgarten** [comment]
This is fixed in 4.0.0, the build folder is now counted as compatible.
