### ISSUE TITLE
DotNetCliToolsReference using deps.json

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3673]
Spec: https://github.com/NuGet/Home/wiki/DotnetCliToolReference-restore

**Comment by natemcmaster** [comment]
@emgarten I see this is still in the RTM milestone. Are you still trying to get this in?

cc @Eilon

**Comment by rrelyea** [comment]
no, it was just tracking external work at one point. moving post 4.0

**Comment by natemcmaster** [comment]
Thanks.

**Comment by jainaashish** [comment]
We're not going to do anything here since current plan is to have global tools which will also cover this.
