### ISSUE TITLE
Get-Package in PMC does not cache credentials

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3674]
## Steps
1. Open VS, open PMC
2. `Get-Package -ListAvailable -Source http://nugetserverendpoint.azurewebsites.net/nuget`
3. Enter username and password
4. `Get-Package -ListAvailable -Source http://nugetserverendpoint.azurewebsites.net/nuget`
## Expected

No auth prompt the second time. Credentials should be cached.
## Actual

Prompted again.
## Affected versions

`dev`, 3.5.0-rtm have this problem.

3.4.4 works.

**Comment by joelverhagen** [comment]
The other PMC commands should be checked as well for the same problem.

**Comment by jainaashish** [comment]
Even though it's a regression, still marking it as p1 since not a single customer has reported this so far. We'll re-evaluate the priority if we see more customer feedback here.

**Comment by nkolev92** [comment]
Stale issue at this point. Closing as I'm pretty confident any issues would've been reported by customers/resolved already.
