### ISSUE TITLE
Restoring a solution with a custom nuget.config file ignores nuget.config files from solution dir

### ISSUE THREAD

**Issue by alfein** [NuGet/Home#3677]
We are doing 

Nuget restore -configFile {path-to-our-config-file} {rel-path-to-sln-file.sln}

And nuget cli client version 3.4.4 ignores the nuget.config file in the solution directory.  

I expected nuget would merge repository lists from both files.

**Comment by yishaigalatzer** [comment]
NuGet does not merge configs when you specify a -configFile, this is the expected behavior.

See:
https://github.com/NuGet/Home/issues/2812
https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior
http://stackoverflow.com/questions/37306281/nuget-configfile-option-supersedes-programdata-config-file

**Comment by alfein** [comment]
According to your docs, https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior

You would be merging configs

When nuget.exe is run from the command line or run implicitly within Visual Studio, it loads settings from config files in the following order:
1.    Files in %ProgramData%\NuGet\Config starting at this top folder and iterating down through the {IDE}{Version}{SKU}\ subfolders if they exist.
2.    The global config file, except in NuGet 3.4 and later if -configFile is used on the command line.
3.    The file specified with -configFile.
4.    Files found in the path to the current folder (where nuget.exe is invoked or the folder containing the Visual Studio solution), starting from the root and ending in the current folder.

Looks like 3 & 4 should still happen.

Please reopen

![capture](https://cloud.githubusercontent.com/assets/22887790/19490562/a605c416-953d-11e6-9047-a56928f7fd4f.PNG)

**Comment by yishaigalatzer** [comment]
Read the top of the doc, it clearly says 3 doesn't get merged. Can you point to the exact location in the doc where you see the disagreement? I'll make sure it's updated immediately

**Comment by yishaigalatzer** [comment]
Ok, I see the where the document is confusing, I'll update it to be more clear @karann-msft

**Comment by alfein** [comment]
OIC,  the doc is the problem.

But it worked before.  Was this an intentional change?  Our build server has predefined list of repos configured, but some projects may choose additional repos.  How would we support it?

I suspect your code is wrong, not the doc.

**Comment by yishaigalatzer** [comment]
I'm sorry for the inconvenience this is causing you. When we looked at the behavior we tried to optimize across multiple customers and made the choice to take a breaking change. Thanks for being understanding. I updated the doc to make is clearer, please let me know if I missed anything. 

The reason for the change is that typically on a build machine you want to have zero impact by other files that get merged and can potentially impact multiple different builds. So the -configFile is an isolated scenario.

There are a few alternatives to fix the issue on your build machine:
1. Include a config file per project that adds additional feeds in the config file passed
2. Merge manually by manipulating the XML
3. Use the config file from the project/solution if one exists (and have it include all the sources).

I'll be glad to help further feel free to reach my email directly yigalatz  @ msft
