### ISSUE TITLE
Unable to load the service index for source https:*

### ISSUE THREAD

**Issue by maxgax** [NuGet/Home#3681]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version 3.4.4.1321

OS version Linux version 2.6.32-642.3.1.el6.x86_64:

Worked before? If so, with which NuGet version: No
## Detailed repro steps so we can see the same problem
1. Run mono NuGet.exe install ... -Source "https://www.nuget.org/api/v2"
2. Output is 
   Feeds used:
   https://www.nuget.org/api/v2

Attempting to gather dependency information for package 'PackageName' with respect to project 'ProjectPath', targeting 'Any,Version=v0.0'
Unable to load the service index for source https://www.nuget.org/api/v2.
  Unable to load the service index for source https://www.nuget.org/api/v2.
  The HTTP request to 'GET https://www.nuget.org/api/v2' has timed out after 100000ms.
## Other suggested things

Is this potentially an issue with the version of OpenSSL installed? 
Current Version openssl-1.0.1e-48.sl6_8.3.x86_64

What is the required version of OpenSSL?

**Comment by jainaashish** [comment]
@maxgax  please try with latest nuget.exe and if it still doesn't work, please re-open it.
