### ISSUE TITLE
VS Package Management Console won't work on Windows Server 2016 (missing Powershell-V2

### ISSUE THREAD

**Issue by serbrech** [NuGet/Home#3682]
## Details about Problem

NuGet product used : Package Manager Console
NuGet version (3.4.4-rtm-final):
VS version : VS2015 update 2
OS version : Windows Server 2016 TP5
## Detailed repro steps so we can see the same problem

The package management console requires Powershell-V2 but that is not available anymore from Win Server 2016, making nuget in visual studio useless...

Can we help somehow on removing that old dependency (is the code on github)?
Is there a fix for this?

Note : Restoring and installing packages works fine if I use a project.json file. but all project templates are using package.config.

**Comment by jainaashish** [comment]
It's fixed with latest Visual Studio, please move to 15.4 or latest.
