### ISSUE TITLE
Switch NuGet version number to 4.0rc

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3685]
- update dev branch version to 4.0rc, instead of the current 3.6 rc
- update wsr-tc so that 1es package version is 4.0.0, instead of the current out of sync 3.5.0
- more?

**Comment by joelverhagen** [comment]
🙌

**Comment by joelverhagen** [comment]
> update wsr-tc so that 1es package version is 4.0.0, instead of the current out of sync 3.5.0

I have already updated it to `3.6.0`, and will update it again for `4.0.0` when appropriate.
