### ISSUE TITLE
Net4.x referencing netstandard DLL in the same solution

### ISSUE THREAD

**Issue by raffaeler** [NuGet/Home#3687]
The VS tooling is not yet finalized but I want to make sure that this scenario is addressed because it is critical to many large projects.

Simplified scenario:
- Netstandard DLL with some classes
- Net4.x (classic) App or DLL referencing the Netstandard DLL in the **same** solution
  This is going to be very popular when customers will begin migrating code to NetCore

The current tooling does **not** allow to reference directly a NetCore dll from a desktop app/dll.
There are two current workarounds:
1. create a nuget package for the netstandard dll and reference the nuget package from the net45
2. modify the netstandard dll to be a PCL instead

Solution 1 is unpractical because this requires to publish the nuget package every time the developer re-compile the netstandard project. This implies a change in the nuget package version (otherwise it would be cached).

Solution 2 belong to the past. We have been invited from the dotnet team to create netstandard DLLs but the tooling requires creating PCLs instead... definitely crazy.

I posted the request here because I understand that netcore deployment is currently only addressable only via nuget.

I believe this scenario should work **directly** so that pressing "F5" in the app, compiles the netstandard dependency and works as every developer would expect.

P.S. I did not post nuget versions or other because this issue is expected not working with the current tooling but I strongly believe it must work for the final bits.

**Comment by rrelyea** [comment]
I just tested this in yesterday's VS2017 build (26009.00)
steps:
1) file new project > WPF app
2) add new project to solution > .net core > class library (net standard)
3) build
THIS FAILED...told me that net standard 1.4 (the dll) isn't compat with net 4.5.2 (WPF app).
so I changed the dll from net standard 1.4 to 1.3 -- and it worked.

So I think you will be happy.

I didn't test with the first RC release...but it may have worked similarly????

Please yell if I didn't totally understand...but i'm going to close issue cause it looks like you'll be happy.
Thx, Rob

**Comment by raffaeler** [comment]
Thanks Rob, I still can't see the 26009 publicly available but what you describe would solve the issue.
The current publicly available bits are preventing me to work on any netcore project, so I reverted to VS2015 to avoid going crazy. I'll wait for the next build and retry.
Thanks again

**Comment by gulbanana** [comment]
it's true that this doesn't work in rc1, there is a bug in native code which prevents it.. nice to see it'll be fixed in the next version
