### ISSUE TITLE
Consider: Allow clearing a specific package from NuGet cache(s)

### ISSUE THREAD

**Issue by Kirua88** [NuGet/Home#3688]
Hello

Is it possible to clear cache of only one package ?
Actually I did the nuget locals global-packages - clear

**Comment by mishra14** [comment]
@Kirua88  that is currently not supported. BUt you can always do it manually by locating the global packages cache - 
`NuGet.exe locals -l global-packages`
And then delete the package that you need to delete.

I will make this a feature request and we will consider this. Thanks for taking the time to request this feature.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
