### ISSUE TITLE
Not possible to encrypt/decrypt passwords when running with Mono on the Mac

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#3689]
## Details about Problem

NuGet 3.6.0-rc-1952

The NuGet.Configuration.EncryptionUtility class throws exceptions when running with Mono on the Mac:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> NuGet.Configuration.NuGetConfigurationException: Password decryption is not supported on .NET Core for this platform. The following feed uses an encrypted password: 'test'. You can use a clear text password as a workaround. 
---> System.NotSupportedException: Encryption is not supported on non-Windows platforms.
  at NuGet.Configuration.EncryptionUtility.DecryptString (System.String encryptedString) 
  at NuGet.Configuration.PackageSourceCredential.get_Password ()
```

The latest version of the EncryptionUtility class has an explicit check to see if it is running on Windows. Previous versions of this EncryptionUtility class, in NuGet 3.5 and earlier, do not have this check and work with Mono on the Mac.

Xamarin Studio uses this EncryptionUtility class when saving and reading passwords for package sources.

Can the EncryptionUtility class check if it is running on Mono and not throw the exception if this is the case?

OS version: Mac

Worked before? If so, with which NuGet version: NuGet 3.4.3 and NuGet 3.5.

**Comment by steve-todorov** [comment]
@zhili1208 @dtivel I'm experiencing the same issue when trying to build the [HelloWorld](https://github.com/dotnet/core/tree/master/samples/helloworld) using [microsoft/dotnet:1.1.5-sdk](https://hub.docker.com/r/microsoft/dotnet/) which is running under Debian and has no mono installed. Are there any plans to fix this issue for linux?
