### ISSUE TITLE
When packing, only dependencies from packages.config that are in the cache are included. (NuGet.exe)

### ISSUE THREAD

**Issue by mhverbakel** [NuGet/Home#3692]
When packing a package, the dependencies are automatically taken from the `packages.config` file: `Found packages.config. Using packages listed as dependencies`. This only works for packages that are included in the `packages`-cache directory.

Expected behavior would be that all dependencies from the `packages.config` are imported, instead of only the downloaded ones.

---

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 3.4.4-rtm-1321

OS version (i.e. win10 v1607 (14393.321)): Windows 7
1. Take a NuGet package project with a `packages.config` file and no dependencies in the `.nuspec` file.
2. Build the project
3. Remove everything in the `packages` folder. (or just one of the dependencies to make the problem extra clear)
4. Run the `nuget pack` command.

If you extract the created package and look at the nuspec file, there are no dependencies listed.

**Comment by rohit21agrawal** [comment]
@mhverbakel  The expected behavior is that nuget should error if any package listed in packages.config is not present in the packages cache directory. NuGet 3.5.0-rtm has this fixed and works as expected. You can give it a try at  https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
