### ISSUE TITLE
Installing NuGet packages doesn't work when the Package source is "All"

### ISSUE THREAD

**Issue by Becklighter** [NuGet/Home#3694]
NuGet product used:        VS UI

NuGet version:                  3.5.0.1484

VS version:                        14.0.25424.00 Update 3

OS version:                        win10 Pro v1607 (14393.321)

I don't know the last version this was working in.
1. Set up a second internal Package Source.
2. Right click on a project and select "Manage Nuget Packages..." 
3. Check "Package source:", it should say "All"
4. Attempt to install any package that has a source of nuget.org
5. You should get the error I get, "An error occurred while retrieving package metadata for 'package name' from source 'my internal package source'.
6. Change "Package source:" to nuget.org
7. Attempt to install the package again, it should work this time.

**Comment by emgarten** [comment]
@Becklighter is your internal package source working correctly when selected in the drop down?

When a single source is selected NuGet ignores errors from other sources. When All is used, all sources must be working correctly to ensure that the highest version of a package can be found.

**Comment by Becklighter** [comment]
My internal package source is working correctly when selected. What else
could be the issue.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
