### ISSUE TITLE
Some packages can't be installed on multiple projects within a solution

### ISSUE THREAD

**Issue by rocifier** [NuGet/Home#3695]
It seems like the latest package types cannot be installed into multiple projects. The error that results when installing to the second project is:

```
An item with the same key has already been added.
```

There is no further error information. Example of a package which breaks on nuget.org feed:

```
AMCG.GlueIoC
```

That package is the simplest one I could find that breaks in .net 4.5 - it literally has no dependencies. This is with the latest visual studio 2015 extensions installed. I have checked my package.config files and there are no duplicates.

**Comment by emgarten** [comment]
@rocifier can you provide some repro steps? Which version of NuGet are you using?

**Comment by rocifier** [comment]
Just make a new web project and add a new c sharp project to it, so you have 2 projects in the solution. Update visual studio 2015 so that nuget is updated to the latest version on there (sorry I'm not at work for a few days and don't know what version that is).

Now go to tools -> manage nuget packages for solution and try to add the above package to both projects at once. It will install to one then fail because of the other with the error message described above.

Expected: the package would install to both projects at the same time. The same error occurs if installing the package to one project followed by the other, in any order.

Is there a way I can try to reproduce it with different versions of nuget?

**Comment by rocifier** [comment]
Hi, is anyone else able to reproduce this? I am still having issues on a weekly basis with all kinds of projects and packages. Should I try to build nuget from source and install it into visual studio 2015? What's the easiest way to upgrade my nuget package manager? According to VS2015 I have version 3.4.4.1321 and no updates are available. I have tried reinstalling that version using Extensions.

**Comment by emgarten** [comment]
@rocifier would you try the latest 3.5.0 version of nuget here: https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by rocifier** [comment]
Hi, I tried that and it was the same. I now tried building the client from source and attaching the debugger. The error occurs on line 107 of PrunePackageTree in dev branch ("installed.add"):

```
public static IEnumerable<SourcePackageDependencyInfo> PruneDowngrades(IEnumerable<SourcePackageDependencyInfo> packages, IEnumerable<Packaging.PackageReference> packageReferences)
    {
        // prune every package that is less that the currently installed package

        IDictionary<string, NuGetVersion> installed = new Dictionary<string, NuGetVersion>(StringComparer.OrdinalIgnoreCase);
        foreach (var packageReference in packageReferences)
        {
            installed.Add(packageReference.PackageIdentity.Id, packageReference.PackageIdentity.Version);
        }

        return packages.Where(package =>
            (package.HasVersion && installed.ContainsKey(package.Id))
                ?
            installed[package.Id] <= package.Version : true);
    }
```

It's trying to add another instance of the same package to the dictionary. I will try to debug more later, but my initial thoughts are that this logic isn't 100% correct. However, skimming through the code it may need to be fixed in other places in the core too like preferredPackageReferences in NuGetPackageManager.cs ?

**Comment by emgarten** [comment]
@rocifier does a packages.config file contain the same id more than once? Are you able to update each project individually?

**Comment by rocifier** [comment]
No they don't. I've checked at least 10 times all the package.config files in the solution. I can add the package to any one project, but when I try to add it to 2 projects either 1 after another, or both at the same time (after removing the package from all projects), I get this error.

**Comment by rocifier** [comment]
Hi after debugging this problem for a while, I couldn't manage to fix the code base.. I worked around the issue by setting the option in the VS2015 UI named "Dependency Behaviour" to "Ignore Dependencies" under "Install and Update Options". This meant the pruning code was not called and everything seems to be working fine now after making sure the known dependencies were already installed - deployments through visual studio team services using nuget beta version also work.

I'm not sure why but it seems that some packages include dependencies which they don't list. In a recent case this problem occurred again for me when using the Microsoft Azure Search package.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
