### ISSUE TITLE
Clean up PathUtility

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#370]
Clean up the original PathUtility code

Ex:
Common patterns like the below one should be combined so that GetRelativePath ensures the trailing slash, this would help avoid bugs where new code calls GetRelativePath alone.
string projectPath = PathUtility.EnsureTrailingSlash(ProjectFullPath);
string relativePath = PathUtility.GetRelativePath(projectPath, referencePath);

**Comment by yishaigalatzer** [comment]
The utility today uses URI to merge paths, and there are several cases where it doesn't work cleanly (particularly when the directory separators don't match). In that case it may throw a URI exception.

The pattern for get relative path should be re-written to recursively figure out the paths.

**Comment by emgarten** [comment]
@rohit21agrawal has hit this issue. We should fix this.

**Comment by nkolev92** [comment]
@rohit21agrawal merged both PathUtility classes, so I consider this as fixed now.
