### ISSUE TITLE
If we need a localized 3.5.0-rtm build, we need to modify wsr-tc configuration

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3703]
WSR-TC configuration is currently set up for the 3.6 build (dev branch) which no longer has NuGet.Core in the VSIX. 3.5.0-rtm VSIX still has NuGet.Core.

**Comment by jainaashish** [comment]
We've moved from wsr-tc to vsts where we dont need to change configuration everytime to get the localized build.
