### ISSUE TITLE
restore3 should display a friendly message when failing due to malformed nuget.config

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3704]
## Details about Problem

NuGet version (x.x.x.xxx):
NuGet Command Line 3.6.0.0

dotnet.exe --version (if appropirate):

.NET Command Line Tools (1.0.0-preview3)

Product Information:
 Version:            1.0.0-preview3
 Commit SHA-1 hash:  a9a6a72bc8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.11-x64

Worked before? If so, with which NuGet version:
No
## Detailed repro steps so we can see the same problem
1. Create a nuget.config file that points to a non-existent local path
2. restore a csproj in the context of this nuget.config

The command fails, as it should, but with a very large stack trace. It would be much better if the condition were handled gracefully with a meaningful message for the user.

**Comment by nkolev92** [comment]
Fixed now.

Nowadays you'd get something like: 

error : The 
local source C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\' 
doesn't exist.
