### ISSUE TITLE
Is there a way to generate project.framework.lock file using command line?

### ISSUE THREAD

**Issue by pneelam** [NuGet/Home#3705]

**Comment by rrelyea** [comment]
Do you mean project.lock.json?
What type of project are you using?
Are you using packages.config or project.json?

**Comment by pneelam** [comment]
I meant project.framework.lock.json. It is a visual studio project with c# code. I am using project.json

**Comment by rrelyea** [comment]
I'm sorry, but I don't know what "project.framework.lock.json" is. Can you describe how you build it w/o command line today...and give me exact steps so I can find it too.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
