### ISSUE TITLE
Nuget client tools in VS Dev15 should use MS.VS.Shell.Framework, not MS.VS.Shell.Immutable.*

### ISSUE THREAD

**Issue by IlyaBiryukov** [NuGet/Home#3707]
## Details about Problem

NuGet product used: VS UI
NuGet version: 3.6.0.1977
VS version: Dev15 bcb1 25818.01
OS version: Windows 10.0.10586

Worked before? If so, with which NuGet version: With Dev14.
Note: It's a perf issue in VS. Nuget or VS is not functionally broken. 
## Detailed repro steps so we can see the same problem
1. Start VS
2. Open or create a project and manage Nuget packages with it
## Expected:

VS only loads Microsoft.VisualStudio.Shell.Framework.
In Dev15 Preview5 and beyond, all types from MS.VS.Shell.Immutable.\* were moved to MS.VS.Shell.Framework. TypeForwardedTo attributes were added to keep run-time compatibility.
## Actual:

VS loads Microsoft.VisualStudio.Shell.Immutable.*
Functionality in NuGet is not broken, but there is an unnecessary perf overhead and extra images loaded.
Assemblies in _Common7\IDE\CommonExtensions\Microsoft\NuGet_ that reference immutables:
- _NuGet.Tools.dll_ uses _Microsoft.VisualStudio.Shell.Immutable.14.0_, _Microsoft.VisualStudio.Shell.Immutable.10.0_;
- _NuGet.PackageManagement.UI.dll_ uses _Microsoft.VisualStudio.Shell.Immutable.11.0_;
- _NuGet.Console.dll_ uses _Microsoft.VisualStudio.Shell.Immutable.10.0_.
## Other suggested things

Latest VSSDK on nuget.org has Dev15 Preview 5 assemblies. When you build with _Microsoft.VSSDK.BuildTools 15.0.25728-Preview5_, ensure you have /p:DeployExtension=false MSBuild property set.

**Comment by rrelyea** [comment]
Planning on addressing post RC, in RC2, as we're running out of runway. Yell if that isn't ok.

**Comment by rrelyea** [comment]
Please investigate fix.

**Comment by jainaashish** [comment]
Fixed with latest Visual Studio 15.4

**Comment by mishra14** [comment]
Reopening as this was closed in confusion. The merge was reverted at the time and should be refactored now.

**Comment by mishra14** [comment]
This was fixed during the solution migration effort last year.
