### ISSUE TITLE
NuGet Clients should send the NuGet-Operation header

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#3708]
Seems the NuGet clients no longer do this?
Used https://dist.nuget.org/win-x86-commandline/v3.5.0-rc1/NuGet.exe to repro.

See also https://github.com/NuGet/NuGetGallery/issues/3298
# Expected

`nuget.exe` operations should send the `NuGet-Operation` header in requests, e.g.

```
NuGet-Operation: Install-Package
```
# Actual

No `NuGet-Operation` HTTP header observed (used Fiddler to inspect the requests).

Screenshot of request headers as intercepted by Fiddler:

![image](https://cloud.githubusercontent.com/assets/880728/19593262/fc3d0c42-977f-11e6-9717-4ed09284e4eb.png)

**Comment by emgarten** [comment]
nuget.exe install is basically a restore. Is it still useful to capture this data? 

I see the operation header as passing along the action performed in the UI/PS Console, that is the only time the client can understand the user intent for the package being downloaded.

**Comment by xavierdecoster** [comment]
According to @harikmenon, this data is still useful to capture :)

We also used to differentiate between restoring direct and indirect package dependencies. Not sure that's still possible?

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
