### ISSUE TITLE
Support NuGet restore for Lightweight Solution Load for Packages.Config or Project.Json

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3711]
Since we need to get all the relevant information to create nuget projects from a solution in DPL mode which isn't there yet so we disabled onbuild restore. And in all other nuget operations, currently we just load solution before NuGet operation to get all projects.

This feature includes following work in their priority order:
1. Support onbuild restore when DPL is enabled.
2. Support Solution restore when DPL is enabled.

**Comment by jainaashish** [comment]
PR blocked by Roslyn bug# https://github.com/dotnet/roslyn/issues/15427

**Comment by alpaix** [comment]
Need to address To-Dos left in client code.
