### ISSUE TITLE
[Probably a dup] Clicking Manage Packages takes you to the install tab

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3712]
VS 2015, NuGet 3.5

When Right Clicking on a project, and loading the package manager window, we go to install by default. 

This is not always what I want to do, I find myself many times wanting to install a package in a fresh project and get confused when I land in the wrong tab.

Rough Ideas:
1. Remember the last tab (globally)
2. Add a Add NuGet Package, next to Manage NuGet packages

**Comment by jainaashish** [comment]
There is a more broader initiative to deal with it as par of package applicability so that will also cover this aspect.

**Comment by nkolev92** [comment]
Closing as stale. 

The tab selection is sticky nowadays.
