### ISSUE TITLE
Ctrl-X does not work in the search box in Manage Packages for project

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3713]
Please read the following information before posting the issue.
## Details about Problem

NuGet Package Manager UI 3.5.0

Type something in the search text box, select some of it. Hit Ctrl-X

Expected:
Text is cut

Actual:
Nothing happens

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
