### ISSUE TITLE
Given a UWP project created with Dev14, I want to build with a build agent that only has Dev15

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3715]
Using Nuget 3.4.4 fails with:

C:\code\LastApp>..\nuget344\nuget.exe restore
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
C:\code\LastApp\AppOne\AppOne.csproj(138,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Micros
oft\WindowsXaml\v15.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> de
claration is correct, and that the file exists on disk.

I tried the latest 4.0.0.2013, and it fails with this error:

C:\code\LastApp>..\NuGet.exe restore -MSBuildPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
Using Msbuild from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin'.
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Microsoft.NetNative.ImportBefore.targets(25,3
): warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0.Net.NetNative\15.0.24208\Microsoft.NetNative.Settings.target
s" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
\MSBuild\15.0\Microsoft.Common.targets\ImportBefore\Microsoft.NetNative.ImportBefore.targets (25,3)". This is most like
ly a build authoring error. This subsequent import will be ignored. [C:\code\LastApp\AppOne\AppOne.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Micros
oft.NuGet.ImportAfter.targets(22,3): warning MSB4011: "C:\Users\rmpablos\AppData\Local\Temp\NuGet-Scratch\vyv13avz.n50.
targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Ente
rprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets (5611,3)". This is most likely a build authoring error.
This subsequent import will be ignored. [C:\code\LastApp\AppOne\AppOne.csproj]
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.Net.CoreRuntime.ImportAfter.targets(
17,3): warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0.Net\CoreRuntime\Microsoft.Net.CoreRuntime.targets" cannot
be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\
15.0\Microsoft.Common.targets\ImportAfter\Microsoft.Net.CoreRuntime.ImportAfter.targets (17,3)". This is most likely a
build authoring error. This subsequent import will be ignored. [C:\code\LastApp\AppOne\AppOne.csproj]
C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NetNative.ImportAfter.targets(16,3):
warning MSB4011: "C:\Program Files (x86)\MSBuild\15.0.Net.NetNative\15.0.24208\Microsoft.NetNative.targets" cannot b
e imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15
.0\Microsoft.Common.targets\ImportAfter\Microsoft.NetNative.ImportAfter.targets (16,3)". This is most likely a build au
thoring error. This subsequent import will be ignored. [C:\code\LastApp\AppOne\AppOne.csproj]
C:\Users\rmpablos\AppData\Local\Temp\NuGet-Scratch\vyv13avz.n50.targets(243,5): error MSB4062: The "NuGet.Build.Tasks.G
etRestoreProjectJsonPathTask" task could not be loaded from the assembly C:\code\NuGet.exe.  Confirm that the <UsingTas
k> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a publi
c class that implements Microsoft.Build.Framework.ITask. [C:\code\LastApp\AppOne\AppOne.csproj]

**Comment by zhili1208** [comment]
This issue still happens with dev14

**Comment by jainaashish** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
