### ISSUE TITLE
Vs Crashes when installing MahApps.Metro

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3716]
Please read the following information before posting the issue.

VS 2015 U3 + 3.5.0
Create new WPF app
Manage packages for project
Install MahApps.Metro (MahApps.Metro 1.4.0-ALPHA023) was the latest when I tried it

Result:
VS Crashes

The crash was sporadic and I wasn't able to reproduce or get a dump. I don't know that it came from nuget/install.ps1 or the WPF designer that was open at the time.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
