### ISSUE TITLE
For UWP Project, improve restore error message

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3717]
NuGet verison: 4.0.0.2013
3.6-beta1 works well
Repro Step:
1. create an uwp project
2. NuGet.exe restore project.json

Expect: restore works well
Actual:
Got Error Message:
Invalid input 'project.json'. Provide the path of an msbuild solution file instead. Support for XProj and standalone project.json files has been removed, to continue working with legacy projects use NuGet 3.5.x from https://nuget.org/downloads

**Comment by emgarten** [comment]
Yes, as the error message says, restore the csproj :smile:

**Comment by rrelyea** [comment]
it says solution. should we say project or solution?

**Comment by jainaashish** [comment]
UWP projects have moved from project.json to PackageReference where this issue is fixed.
