### ISSUE TITLE
Pack task puts content files in both 'content/' and 'contentFiles/'

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#3718]
Pack a csproj that includes a 'content' item. The files ends up in both "<nupkg>/content" and "<nupkg>/contentFiles".

**Repro:**

``` xml
  <ItemGroup>
    <Content Include="somefile.txt" Pack="true" />
  </ItemGroup>
```

'dotnet pack3'

**Output:**
nupkg contains content files twice:

```
content/
    somefile.txt
contentFiles/
    somefile.txt
lib/
    netcoreapp1.0/
        testapp.dll
```

**Using:**
dotnet cli  1.0.0-preview3-003857
microsoft.net.sdk/1.0.0-alpha-20161021-1
NuGet.Build.Tasks.Pack/3.6.0-rc-1984

**Comment by rrelyea** [comment]
believe we are starting to do this by design. @rohit21agrawal?

**Comment by rohit21agrawal** [comment]
@rrelyea yes, this is by design.

**Comment by natemcmaster** [comment]
@rohit21agrawal can you share more details on this design? Duplicating content in a package is not something I would expected.

**Comment by joelverhagen** [comment]
Spoke to @natemcmaster offline.

This is by design ([spec](https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#including-content-in-package)):

> Everything gets added to the root of the content and contentFiles folder within a package and preserves the relative directory structure, unless you specify a package path

However, some people may want to only think about PackageReference/project.json consumers. We should consider an opt-out flag like:

``` xml
<PackLegacyContent>false</PackLegacyContent>
or
<UseLegacyContentPacking>false</UseLegacyContentPacking>
```

@yishaigalatzer, thoughts?

**Comment by yishaigalatzer** [comment]
Sounds ok to me
