### ISSUE TITLE
Modify the NuGet targets to log the package sources as High verbosity instead of Normal

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#3719]
This is related to this:

https://github.com/dotnet/cli/pull/4438.

We would like to take the PR above in the CLI so that we stop printing the Build Start/Succeeded when restoring in the CLI.

However, the sources won't be printed if we do that and we would like for them be so.

Would it be possible to change the verbosity of the used sources?

**Comment by rrelyea** [comment]
@livarcocc - Likely yes
@emgarten  - see any problem with this?

**Comment by livarcocc** [comment]
Thanks @rrelyea. I will wait to hear from @emgarten and then I will merge the PR on our side.

**Comment by emgarten** [comment]
@livarcocc are you referring to the summary printed out at the end that contains all feeds and config files used, along with all errors and warnings again?

**Comment by livarcocc** [comment]
Yeap.
