### ISSUE TITLE
NRM VS package fails to load (normally or in experimental instance)

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3720]
@alpaix 

The same issue also occurs if you install a VSIX from dev-vsdg build to Visual Studio

**Comment by drewgillies** [comment]
![image](https://cloud.githubusercontent.com/assets/14225979/19621972/49469d0e-9853-11e6-9bac-3e41dc7f5648.png)

**Comment by drewgillies** [comment]
SetSite failed for package [RestoreManagerPackage]Source: 'NuGet.SolutionRestoreManager' Description: Could not load file or assembly 'NuGet.PackageManagement, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.PackageManagement, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. File name: 'NuGet.PackageManagement, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' at NuGet.SolutionRestoreManager.RestoreManagerPackage.<InitializeAsync>d__12.MoveNext() at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine) at NuGet.SolutionRestoreManager.RestoreManagerPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress) at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e) at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck) at Microsoft.VisualStudio.Services.VsTask.GetResult() === Pre-bind state information === LOG: DisplayName = NuGet.PackageManagement, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (Fully-specified) LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/ LOG: Initial PrivatePath = NULL Calling assembly : NuGet.SolutionRestoreManager, Version=4.0.0.29233, Culture=neutral, PublicKeyToken=null. === LOG: This bind starts in LoadFrom load context. WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load(). LOG: Using application configuration file: C:\Users\drewgil\AppData\Local\Temp\dev9D8F.tmp LOG: Using host configuration file: LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config. LOG: Post-policy reference: NuGet.PackageManagement, Version=3.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PublicAssemblies/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PublicAssemblies/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/Program Files (x86)/Microsoft Visual Studio/wpt/25810.03/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/USERS/DREWGIL/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_E599B8B0EXP/EXTENSIONS/MICROSOFT CORPORATION/NUGET PACKAGE MANAGER FOR VISUAL STUDIO 15/99.99.99/NuGet.PackageManagement.DLL. WRN: Comparing the assembly name resulted in the mismatch: Major Version LOG: Attempting download of new URL file:///C:/USERS/DREWGIL/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_E599B8B0EXP/EXTENSIONS/MICROSOFT CORPORATION/NUGET PACKAGE MANAGER FOR VISUAL STUDIO 15/99.99.99/NuGet.PackageManagement/NuGet.PackageManagement.DLL. LOG: Attempting download of new URL file:///C:/USERS/DREWGIL/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_E599B8B0EXP/EXTENSIONS/MICROSOFT CORPORATION/NUGET PACKAGE MANAGER FOR VISUAL STUDIO 15/99.99.99/NuGet.PackageManagement.EXE. LOG: Attempting download of new URL file:///C:/USERS/DREWGIL/APPDATA/LOCAL/MICROSOFT/VISUALSTUDIO/15.0_E599B8B0EXP/EXTENSIONS/MICROSOFT CORPORATION/NUGET PACKAGE MANAGER FOR VISUAL STUDIO 15/99.99.99/NuGet.PackageManagement/NuGet.PackageManagement.EXE.

**Comment by joelverhagen** [comment]
The fact that there is a 3.6.0 version in there could be an issue. I recently made a fix in dev-vsdg bringing all version numbers up to 4.0.0.

**Comment by rrelyea** [comment]
doesn't repro anymore. perhaps wthe version change fixed it.
