### ISSUE TITLE
NetCore install from NuGet Package Manager UI installs to every TFM , instead of ones that the package supports

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#3721]

**Comment by rrelyea** [comment]
Setting to RC now...but we'll discuss in triage. Do not block insertion on this.

**Comment by rrelyea** [comment]
Confirmed with @yishaigalatzer that we only want to add PackageReferences on the install scenario. Not the upgrade scenario, or the upgrade several scenario.

**Comment by rrelyea** [comment]
ok to move to "in review"? if so, please do.

**Comment by joelverhagen** [comment]
Yes, moved.

**Comment by rrelyea** [comment]
As you are about to be OOF, let me know if you need us to transfer to somebody else from the team.
