### ISSUE TITLE
Legacy csproj projref - SupportsReferences must be called on the UI Thread

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3723]
![image](https://cloud.githubusercontent.com/assets/8865080/19624013/34850f78-9898-11e6-83f9-9ffceaabbaea.png)

**Comment by rrelyea** [comment]
Still repros with 2565.

**Comment by drewgillies** [comment]
After patching d15prerel with csproj.dll to light up the interface which gives us the legacy csproj codepaths, this repro goes away in favor of the repro from https://github.com/NuGet/Home/issues/3728. After 3728 is fixed, let's re-validate this scenario.

**Comment by drewgillies** [comment]
Scenario no longer repros on 25821.9. Although:
- we still have a squiggle on PackageReference
- we still have an error node in the solution explorer for the package.
  Tracked in different bugs. Closing.
