### ISSUE TITLE
UWP w/ PackageReferences - install tab doesn't show manually typed packageref from csproj

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3725]
**UWP Project.Json using dev-vsdg 2556 build - handpatched vsix**

File New project > Blank App (
Turn on Developer Mode on RS1 box
Project.json was created during project creation with:
    {
      "dependencies": {
        "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0"
      },
      "frameworks": {
        "uap10.0": {}
      },
      "runtimes": {
        "win10-arm": {},
        "win10-arm-aot": {},
        "win10-x86": {},
        "win10-x86-aot": {},
        "win10-x64": {},
        "win10-x64-aot": {}
      }
    }

BUG: Restore dialog still shown (WANTED TO LAND IN RC, but by design not in yet)

Upgraded to 5.2.2 of package. It worked.

Deleted project.json
Unloaded project, right click edit project

Add the following into an item group:

```
<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
    <Version>5.2.2</Version>
</PackageReference>
```

Save, reload  project.

Go to package manager UI.
Click on isntalled tab.

Our BUG: no packages appear to be installed.
VS BUG: packageref isn't converted into reference

Right click on solution, and ask to restore and see the following in error list:
Our BUG: explicit restore by user:
   Error occurred while restoring NuGet packages: SupportsReferences must be called on the UI thread.  
likely the same as #3723 

Our Bug: if you install a package, it adds packages.config -- despite the fact that it already had PackageReference in csproj

**Comment by drewgillies** [comment]
This scenario is now fixed (as is the included packages.config scenario). Build 25821.9. Closing.
