### ISSUE TITLE
Packages.config csproj - SupportsReferences must be called on the UI Thread

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3726]
Create .Net framework class library project (which will have packages.config) and do a restore from menu item. It throws below error:

`Error occurred while restoring NuGet packages: SupportsReferences must be called on the UI thread.`

On build restore is working fine, so some issues with explicit restore.

**Comment by rrelyea** [comment]
still repros with 2565

**Comment by mishra14** [comment]
Validated with build: d15prerel/25825.4 Nuget/4.0.0.2033
