### ISSUE TITLE
Any missing sources, will prevent restore from working

### ISSUE THREAD

**Issue by augustoproiete** [NuGet/Home#3730]
(copying from https://github.com/dotnet/cli/issues/2593 as per instructions)
### Steps to reproduce
1. Add nuget source to broken path
2. Navigate to empty directory and dotnet new dotnet restore
### Expected behavior

Packages should be restored
### Actual behavior

```
D:\Development\cstest>dotnet restore
log  : Restoring packages for D:\Development\cstest\project.json...
error: Failed to retrieve information from remote source 'D:\Development\MyOldNugetSource'.
```
### Registered sources

```
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  bokrnesource [Enabled]
      D:\Development\MyOldNugetSource
```

Why is the 2nd source taking precedence over the 1st?
### Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002429)

Product Information:
 Version:     1.0.0-rc2-002429
 Commit Sha:  612088cfa8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by rrelyea** [comment]
By design issue. 
We hope to improve the experience here with some future work: https://github.com/NuGet/Home/wiki/Package-Sources-Diagnostics
