### ISSUE TITLE
When a package is installed to UWP project.json, parent projects should also be restored

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3731]
Found on the `dev-vsdg` branch.
## Steps
1. Add two UWP project.json projects in VS.
2. Make one have a project reference to another (project1 -> project2).
3. Install a package to project2.
## Expected

There should be a project.lock.json in both projects.
## Actual

The parent project (project1) is not restored.

Related to the following E2E tests:
- `BuildIntegratedParentProjectIsRestoredAfterInstall`
- `BuildIntegratedParentProjectIsRestoredAfterUnInstall`
- `BuildIntegratedParentProjectIsRestoredAfterUpdate`
- `BuildIntegratedProjectClosure`

**Comment by emgarten** [comment]
UWP project.json projects were not passing adding project to project references to the package spec.
