### ISSUE TITLE
Get-Project no longer supports getting projects by short name

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3732]
Found in the `dev-vsdg` branch. I think `ProjectSystemCache.TryGetCacheEntry` should check the short name look-up. Ambiguity has to be handled but the following repro steps do not have ambiguity.
## Steps
1. Create an empty solution.
2. Add a solution folder.
3. Add a project to that solution folder.
4. Open PMC and type `Get-Project MyProjectName` (without the folder name).
## Expected

The project should be found since the short name is not ambiguous.
## Actual

```
PM> Get-Project ConsoleApplication2
Get-Project : Project 'ConsoleApplication2' is not found.
At line:1 char:1
+ Get-Project ConsoleApplication2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ConsoleApplication2:String) [Get-Project], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetProjectCommand
```

/cc @alpaix

**Comment by joelverhagen** [comment]
Note that if the short name and unique name are the same, this scenario works just fine (since the code is properly getting projects by unique name).

**Comment by joelverhagen** [comment]
Effected end-to-end tests:
- `GetProjectCommandWithWildCardsWorksWithProjectHavingTheSameName`
- `RemovingAmbiguousProjectAllowsSimpleNameToBeUsed`
- `RenameCreatingAmbiguityFollowedByRemovalAllowsSimpleNameToBeUsed`
- `RenamingSolutionFolderDoesNotAffectGetProject`
- `RenamingSolutionFolderWithDeeplyNestedProjectsDoesNotAffectGetProject`

**Comment by rrelyea** [comment]
can we also add unit tests to catch this earlier.

**Comment by joelverhagen** [comment]
Yes.
