### ISSUE TITLE
Make dependencies hyperlinks

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3733]
From user:
Consider making the package dependencies in the NuGet UI hyperlinks, so I can jump directly to the dependency and install that.

From me:
The hyperlink should load the item in the list with an id:packageId search

Consider:
Back navigation

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
