### ISSUE TITLE
TFMs and package manager dialog

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3735]
We need to bring back control of packages vs. their supported TFMs vs. what the project supports

There are a few things that need to happen
1. We will need to download the package in some cases to know what it actually supports
2. We need to show the TFMs in the package window
3. We need to perhaps add some UI gesture to the install/update buttons if we don't know the TFM compatibility (e,g. it's not default, or the server doesn't provide the data, or the server cannot be trusted because it provides bad data) , and warn or disable the buttons
4. We need to filter packages that are not compatible (but have the ability to show all of them, either grayed out or with the above filter)

**Comment by jainaashish** [comment]
We'll take it as part of Package Applicability spec and get the right behavior.
