### ISSUE TITLE
Hand migrate a project.json scenario doesn't work 

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3736]
Repro Step:
1) Create an UWP project and delete project.json
2) add following to csproj:

``` xml
<ItemGroup>
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>5.2.2</Version>
    </PackageReference>
  </ItemGroup>
```

3)  build solution.
4)  install newtonsoft.json.

Expect: nuget restore packages and add newtonsoft.json packageReference to csproj

Actual:

nuget doesn't restore packageReference packages and create package.config during installing newtonsoft.json.

**Comment by jainaashish** [comment]
Fixed with latest Visual Studio 15.4
