### ISSUE TITLE
Add the ability to favorite/bookmark a NuGet package in visual studio

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3738]
The suggestion is to "like"/favor/bookmark a package.

A bookmark is going to be remembered globally (best if roaming).

Features:
1. Remember that a package is favored and mark it in the package list
2. Show all favored packages (perhaps a tab?)
3. Record text about why the package is favored

Bonus - User favored packages on the server gallery UI

**Comment by yishaigalatzer** [comment]
CC @harikmenon

**Comment by NickCraver** [comment]
Related: A list of commonly used packages on the machine with no user action needed would also be very useful. At least inside companies, you're often using lot of the same packages across projects. Wherever " favorites" are shown, "common" or "recent" may equally or more useful to include as well.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by BalassaMarton** [comment]
Any chance you reopen this issue? My experience is that we use the same common packages for a lot of projects, and it would be nice to just go through a shorter list on a separate tab, check some packages and click install once.

**Comment by nk54** [comment]
Please add this feature ! Tired of looking over and over for the same packages...
Newtonsoft.json, XForms, SQLite etc. I need those package in 90% of my project. The 10% left are some project I create just to test a control or to do a micro P.o.C.

Can you consider adding a pin package option in the list so they remain on top ?
Or adding a tab of favored package ?

I can't edit the package.config anymore in .NET Standard and paste the package I copied from the previous project. Very frustrating to perform that so often without being able to pin/bookmark a package.

**Comment by Atulin** [comment]
I came from 2019 to ask for this issue to be reopened

**Comment by PawelDziedzic** [comment]
Was this idea ever implemented? If so, I can't find it

If not, please consider implementing it :3
