### ISSUE TITLE
Add support for imports, buildCrossTargeting, and runtimes to CpsPackageReferenceProject

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3739]
Restore for .NETCore project requires the following fields which are not present in CpsPackageReferenceProject yes
- `PackageTargetFallback`  - imports equivalent, this needs to be per TFM
- `CrossTargeting` - true when `$(TargetFrameworks)` is used, false otherwise. This enables writing `buildCrossTargeting` imports to the generated targets/props.
- `OriginalTargetFrameworks` - Generated imports needs the exact framework strings used in the project. (its unclear if this is being passed already or if the strings are modified)
- `RuntimeIdentifier`/`RuntimeIdentifiers` - Allows RID specific restore
- `RuntimeSupports` - Equivalent to the supports section in project.json

**Comment by emgarten** [comment]
One additional property that should be added is: `Version`, if provided in the property bag this should be applied to `PackageSpec.Version`

**Comment by rrelyea** [comment]
Eta?
