### ISSUE TITLE
Add RuntimeIdentifiers and RuntimeSupports to LegacyCSProjPackageReferenceProject

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3740]
UWP applications require RIDs, support for this should be added to LegacyCSProjPackageReferenceProject

This will cover both the Runtimes and Supports sections of project.json

Example of nuget.targets reading these properties:
https://github.com/NuGet/NuGet.Client/blob/29f3232dc472d2f0fe4536a2db28c334e903ca44/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L348-L349

**Comment by joelverhagen** [comment]
Talked to @drewgil offline about this, I'll take a look. @rrelyea, what's the priority on this?
