### ISSUE TITLE
VS UI and package manager very unhelpful when installing packages with unmet requirements

### ISSUE THREAD

**Issue by johndog** [NuGet/Home#3743]
Remove the content above here and fill out details below.
## Details about Problem

NuGet product used: VS UI 

NuGet version: NuGet Package Manager   3.4.4

VS version: Version 14.0.25431.01 Update 3

OS version: Win10 v1607 (14942.1000)
## Detailed repro steps so we can see the same problem
1.  Configure a project to target .net 4.5
2.  Using the Nuget PM GUI, find a package that requires .net 4.5.2
3.  In the PM GUI, select the package and select the project
   
   **Observe**:  there is no guidance in the UI that the package requires 4.5.2, or that the selected project does not meet the requirements.
4.  Click 'Install'

**Result**:

The following output in the Output window:

```
  Could not install package 'Nuget.vPack 1.5.160509001'. You are trying to install this package into a project that targets 
  '.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are 
  compatible with that framework. For more information, contact the package author. 
========== Finished ==========
```

Note that there is very little information to help the developer proceed.  In particular, the developer has no idea what framework version to target in order to avoid this error.

**Expect**:

One of the following:  
- The nuget console output should list the versions of .Net Framework that ARE supported
- The VS GUI should list the versions of the .Net Framework that are supported, it should grey out the install button, and it should print in RED the reason that the package cannot be installed for the selected project(s)

Either of these would help the developer move forward more efficiently.

**Comment by emgarten** [comment]
Does 1.0.4 or a higher stable version of the package exist?

Compatibility here is referring to the version constraint mentioned in the message, not framework compatibility which is checked later in the install process. 

The message could be improved to make that more clear.

**Comment by johndog** [comment]
Since the total fix at a GUI level might be complex to do all at once, I suggest the following progression of fixes:
1. Good:  Add logging of the supported versions to the nuget console output, so that native nuget users and VS UI users who are attentive to the Output window will have a chance to see the information.
2. Better:  Enable the UI to interpret the nuget output, and present the requirements miss in the UI as well as the requirements themselves, after the user clicks the Install button.
3. Best:  Enable the UI to proactively analyze the requirements of the selected nugets with respect to the current projects, and present clearly in the GUI when the requirements are falling short, before the user clicks the Install button.

:

**Comment by johndog** [comment]
@emgarten I originally reproduced this several weeks ago and reported via the VS feedback.  I tried to reproduce it the same way, but this error is not the same.  I've changed the log to the messages I originally saw.

**Comment by emgarten** [comment]
Thanks for the update, I'm curious to know if there are more problems here.

Install first does a preview which finds any problems. In this case it looks like there were zero version of the package that are `>= 1.0.4`

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
