### ISSUE TITLE
Mention only dll/xml files supported in lib package folder

### ISSUE THREAD

**Issue by clavecoder** [NuGet/Home#3745]
For
https://docs.nuget.org/ndocs/create-packages/creating-a-package#from-a-convention-based-working-directory

It's not clear what files are supported in the convention-based folder structure in the lib folder. Your documentation has:

lib Assemblies (.dll files) Added as assembly references

You should mention that only .dll + xml documentation files (.xml) are supported.

**Comment by clavecoder** [comment]
Also the pdb file, which is picked up when you use the -Sources flag.

**Comment by yishaigalatzer** [comment]
note is a good way to suggest changes https://github.com/NuGet/NuGetDocs/tree/master/NuGet.Docs/ndocs/Create-Packages/Creating-a-Package.md

**Comment by karann-msft** [comment]
Docs updated. Thanks for the feedback @clavecoder.
