### ISSUE TITLE
Provide support for project level attributes in the restore nomination API

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3746]
The data model of project restore info object currently doesn't support project level attributes needed for restore.

Among missing properties are:
- `PackageFallbackTarget` ("imports")
- `OriginalTargetsFrameworks`
- `CrossTargeting`
- `RuntimeIdentifiers`
- `RuntimeIdentifier`
- `RuntimeSupports`

**Comment by joelverhagen** [comment]
`PackageFallbackTarget` should be `PackageTargetFallback`.

**Comment by joelverhagen** [comment]
@emgarten will know the full list, essentially it's the set read by out build task.

**Comment by alpaix** [comment]
Duplicate to #3739
