### ISSUE TITLE
enable adding package references into csproj from dotnet.exe

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3751]
Need spec

**Comment by mishra14** [comment]
Spec draft: https://github.com/NuGet/Home/wiki/Support-dotnet-ref-add%7Cupdate%7Cdelete-packageref

**Comment by rrelyea** [comment]
splitting off the removing/listing and updating parts of this work to new issues.

**Comment by mishra14** [comment]
NuGet has been merged : https://github.com/NuGet/NuGet.Client/commit/dd0f0aa92c02bea6ea23140255d7c22d458a4011

Dotnet cli PR : https://github.com/dotnet/cli/pull/5122

**Comment by mishra14** [comment]
Patch merged : https://github.com/NuGet/NuGet.Client/commit/3a380d8715a2e8e6804ac8434d30473c6dd2bcbb
