### ISSUE TITLE
Add the option to compose package sources on the command line for the MSBuild-based SDK

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#3758]
In the project.json (preview 2) world of CLI tooling, the `dotnet restore` had an option to specify a "fallback source" per invocation using the `-f` switch. This allowed for feed composition at invocation time without having to deal with `NuGet.config` files.

This option has been removed from the MSBuild tooling, however, I believe it should be put back seeing as how it is incredibly useful in at least one major scenario and that is CLI extensions (tools) development as it allows _ad hoc_ testing of the tools in any project. Whether it is called `--fallbacksource` or something else (`--add-source`, `--additional-source` etc.) is less of an issue. 

/cc @rrelyea @yishaigalatzer

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
