### ISSUE TITLE
[NuGet.PackageManagement] The feature of packages.<projectName>.config is not ported to NuGet 3.0 yet

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#376]
run-test UpdatePackagePreservesProjectConfigFile 
run-test InstallPackageAddMoreEntriesToProjectConfigFile 
run-test InstallPackageToWebsitePreservesProjectConfigFile 
run-test InstallPackagePreservesProjectConfigFile

**Comment by deepakaravindr** [comment]
This is a duplicate of #74
