### ISSUE TITLE
[Mono Issue] Got "Error getting response stream(ReadDone2): Receive Failure" when retry credential three times

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3762]
Mono Version: 4.4.2
Repro Step:  
1. set up a nuget server with credential, for example: username: user, password: pass
2. try to restore one package from that server
3. type wrong username and password twice, for example, first time: a:b, second time: c:d
4. type right username and password at the third time.

Expected: restore works well
Actual: Got error message: Error getting response stream(ReadDone2): Receive Failure

Looks like this is a mono library bug, I will file a bug against them and add link here

**Comment by mrward** [comment]
@zhili1208 - This may be fixed in Mono 4.8.0 but I would like to test it.

In order to try to reproduce this:

1) How do I setup a NuGet server with a credential? Is this using the NuGet.Server NuGet package? Is the url using https?
2) The restore is done from the command line? Using NuGet.exe - any particular version?

**Comment by zhili1208** [comment]
@mrward please use my test app to repro this issue https://github.com/zhili1208/MockServerOnMono/blob/master/MockServer/Program.cs
it will set up server with credential for you, just call CredentialRetryIssue.ReproIssue(), it will repro the issue

**Comment by zhili1208** [comment]
@mrward any updates on this issue, I just tried 4.8, 4.8 throws this error at the second request and 4.4 throws at the third request.

**Comment by mrward** [comment]
@zhili1208 - Using your test program I get the same ReceiveFailure error with Mono 4.8.0.344. We should open a bug on [bugzilla](https://bugzilla.xamarin.com) so one of the Mono team can look into fixing this.

**Comment by mrward** [comment]
Opened [bugzilla bug 47700](https://bugzilla.xamarin.com/show_bug.cgi?id=47700) for this problem.

**Comment by nkolev92** [comment]
Closing as external. 
No significant customer engagement to keep open at this point.
