### ISSUE TITLE
Mono 4.8 fix - NetworkCredential needs to work with SecureString

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3763]
Mono version: 4.4.2

when passing SecureString to NetworkCredential on Mono, HttpRequest always send empty string for password.

Impacted NuGet scenario:
1. Restore package from credential server.
2. type right username and password

Expected: restore works well
Actual: still got 401 

we can work around this by using string for password on mono, will talk to mono team first.

**Comment by fatso83** [comment]
Is this why `nuget restore` always fails on Mono when using authenticated feeds? I was about to report that issue, but this seems very much like it.

**Comment by zhili1208** [comment]
reading username and password from nuget.config should work

**Comment by marek-safar** [comment]
We are tracking similar issue as https://bugzilla.xamarin.com/show_bug.cgi?id=44109

**Comment by akoeplinger** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=44109 is fixed now and will be released in Mono 4.8.

I tried connecting to an authenticated NuGet feed and supplying user/pass from the command line. It fails on Mono 4.6 and works on Mono 4.8 with the above fix, so I think this can be closed.

**Comment by zhili1208** [comment]
verified the fix in mono 4.8
