### ISSUE TITLE
preserve existing assembly reference properties as is

### ISSUE THREAD

**Issue by rupaks** [NuGet/Home#3764]
## Details about Problem

NuGet product used (VS UI | Package Manager Console):
NuGet version (2.12.0.817):
VS version (VS 2013):
OS version (i.e. Windows 7 64 Bit):
## Detailed repro steps so we can see the same problem
1. Install NuGet package
2. Set Copy Local to False for an assembly installed by NuGet
3. Update same NuGet package of latest version
4. Observe hat Copy Local set to true for the assembly on step 2
## Other suggested things

Install.ps1 does not help much, as it comes to action when actual  reference properties already updated.

**Comment by jainaashish** [comment]
It's by design to put this into a good state while installing or updating a package so we might not be able to do anything there. Besides, it's only with Packages.Config, it doesn't happen with PackageReference which is new format and will be used going forward.
