### ISSUE TITLE
Workaround Mono behavior - Passing username and password by redirecting nuget.exe input doesn't work on mono

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3765]
Mono Version: 4.4.2

Impacted NuGet scenario:
1. put username and password in txt file
2. restore package from a credential server by using "< password.txt"

or use ProcessStart a nuget.exe process and pass username and password to ProcessStartInfo

Expected: works well
Actual: ReadSecureStringFromConsole() got into endless loop

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Common/Console.cs#L312-L325

the issue here is mono doesn't throw on System.Console.ReadKey() if user redirect nuget.exe input, so nuget will wait for ConsoleKey.Enter forever.

**Comment by migueldeicaza** [comment]
On Unix, you can use this method to determine if the input is interactive or not:

```
    public class UnixUtils {
            [System.Runtime.InteropServices.DllImport ("libc", EntryPoint="isatty")]
            extern static int _isatty (int fd);

            public static bool isatty (int fd)
            {
                    try {
                            return _isatty (fd) == 1;
                    } catch {
                            return false;
                    }
            }
    }
```

if it returns true, it means that the user is typing at the console, otherwise, the input has been redirected.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/d34c9e0d8a47f63fb2a9ec53e21f53563e85c569
