### ISSUE TITLE
Workaround Mono behavior - PluginCredentialProvide got parse error

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3766]
Mono Version: 4.4.2

Impacted NuGet Scenario:

PluginCredentialProvide doesn't work for nuget on mono.

issue: mono add extra empty char at the start of process output buffer when we use Process.OutputDataReceived event to redirect output, it make json parsing fail. If we just read std output, it works.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.Credentials/PluginCredentialProvider.cs#L251

**Comment by migueldeicaza** [comment]
What is that empty character?   Is it perhaps the UTF8 marker?

**Comment by zhili1208** [comment]
from Xamarin studio, the first char value is
65279 ''

**Comment by mhutch** [comment]
Yes, that's a BOM.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/34f5670deeaee379dd86fa6413c7d5a620e863b0
