### ISSUE TITLE
ASP.NET Core web app, migrated from VS2015 to VS "15", unable to restore.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3773]
Internal bug 281338 Open ASP.NET Core web app using VS "15" RC, unable to restore packages and build project

**Comment by jainaashish** [comment]
If we open nuget manager ui and then do the restore on this migrated project then its working. But if we just do the restore then it throw error for unidentified project system. Further investigating...

**Comment by rrelyea** [comment]
Any update?

**Comment by jainaashish** [comment]
Restore is working for migrated projects. Although we've an open issue https://github.com/NuGet/Home/issues/3729 which sometimes clashes with migrated projects and throw error on restore. So Closing this bug as fixed.

**Comment by rrelyea** [comment]
marking as dupe of #3729
