### ISSUE TITLE
no_proxy containing wildcard breaks nuget

### ISSUE THREAD

**Issue by rlaveycal** [NuGet/Home#3776]
## Details about Problem

If the NO_PROXY environment variable contains a wildcard domain (e.g. *.acme.com) then all calls to nuget.org fail.

Looking at the source this shouldn't be an issue as https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Proxy/WebProxy.cs#L84 contains

``` cs
        private static string WildcardToRegex(string pattern)
        {
            return Regex.Escape(pattern)
                .Replace(@"\*", ".*?")
                .Replace(@"\?", ".");
        }
```

although those replace statements are in the wrong order (the ? in the 1st gets replaced by a . in the second)

NuGet product used: VS UI, Package Manager Console
NuGet version (x.x.x.xxx): 3.4.4.1321
VS version (if appropriate): 2015 update 3
OS version (i.e. win10 v1607 (14393.321)): win 10 v1511
Worked before? If so, with which NuGet version: 3.3
## Detailed repro steps so we can see the same problem
1. PM> `$env:NO_PROXY="localhost,127.0.0.1,*.acme.com"`
2. PM> find-package log4net
3. PM> _no output_
4. PM> `$env:NO_PROXY="localhost,127.0.0.1,.*\.acme.com"`
5. PM> find-package log4net
6. _lots of output_

**Comment by jainaashish** [comment]
Fixed with latest Visual Studio 15.4
