### ISSUE TITLE
[Test Failure] VS hang when building project (dev 2024)

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3777]
**Repro Steps:**
1.  Creat a C# ASP.NET Web Application.
2.  Click **Web Forms** template and check “Web Forms” and “Web API”.
3.  Change Authentication to “No Authentication” and click OK button.
4.  Build the project.

**Expected Result:**
Build is successful.

**Actual Result:**
VS crashed as below screenshot.
![buildprojectcrashvs](https://cloud.githubusercontent.com/assets/20632625/19720090/4ac82360-9b9f-11e6-921c-d31c3f6f37ef.png)
**Note:** 
1.  It also repro on other projects (MVC/F# console App).
2.  It was found on D15PreRel 25825.00+NuGet Client 4.0.0-RC-2024.
3.  It doesn’t repro on D15PreRel 25825.00 (NuGet Client 4.0.0-RC-2008).
4.  It doesn’t repro on Dev14 MU3.5 25431.01 (NuGet Client 3.4.4.1321).
5.  It doesn’t repro on Dev14 MU3.5 25431.01+ NuGet Client 3.5.0-RTM-1938.

**Repro Machine:** EXPRBLNVM65528

**Comment by jainaashish** [comment]
Another scenario to repro this bug:
1. Create ASP.Net web application project.
2. Open nuget manager ui
3. do restore.

It will make VS hang.

**Comment by jainaashish** [comment]
Merged 5cca35c90b93d6cecb050d0bed70500226f0b0ea
