### ISSUE TITLE
[NuGet.PackageManagement] After package update, old dependency package is not uninstalled

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#378]
If A 1.0 depends on B 1.0 and A 2.0 depends on C 2.0,

after A 1.0 is updated to A 2.0, B 1.0 is still installed to the project. While it should have been uninstalled.

**Comment by danliu** [comment]
run-test UpdatePackageInstallCorrectDependencyPackageBasedOnTargetFramework

**Comment by emgarten** [comment]
We have decided to leave dependencies installed. There is no way to know if the user installed the package or not.

NuGet/NuGet.VisualStudioExtension@7ff3133f672bb16a9a271285daf2f4ae9812a0ca
