### ISSUE TITLE
Due to risk of deadlock cannot call GetService from a background thread

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3782]
Repro - 
1. New .Net framework console app
2. build it.
3. launch pmc or nuget UI

![2016-10-26](https://cloud.githubusercontent.com/assets/10507120/19741624/4a0a3eaa-9b76-11e6-8938-0dbf1e9c4c33.png)

//cc: @rrelyea @alpaix

**Comment by alpaix** [comment]
The same as #3775
