### ISSUE TITLE
Replace GetService with GetServiceAsync everywhere in NuGet.Clients

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3784]
Follow up on #3775.

Recommended practice of acquiring VS services is always calling `GetServiceAsync` to avoid the high risk of deadlock. All the occurrences of `GetService` and `ServiceLocator` should be replaced.

**Comment by nkolev92** [comment]
The goal here is to just replace GetService with GetServiceAsync wherever possible. 

No need to focus on removing ServiceLocator.

**Comment by dominoFire** [comment]
119 calls to analyze from `src/*` and `test/*` folders

Some calls are noisy because component.GetService is also matched. Besides, end2end PowerShell test scripts makes calls to GetService and xml comment are also matched.

**Comment by nkolev92** [comment]
I would prioritize src/ only. 
Wouldn't bother too much with the test changes.

**Comment by dominoFire** [comment]
40 matches remaining from .cs files in `src` folder.

**Comment by dominoFire** [comment]
Branch with some progress is  dev-dominofire-service-async

https://github.com/NuGet/NuGet.Client/tree/dev-dominofire-service-async

**Comment by nkolev92** [comment]
How much work do we think is left here @dominoFire, @erdembayar 

Can you adjust the cost estimate.

**Comment by dominoFire** [comment]
34 `GetService()` calls to be replaced in 24 files.

Assuming 2 hours per file (1 for replacing the call, 1 for testing), that leads to 48 hrs/points ~ 10 work days + 1 day for e2e testing.

LineNumber | Line | Filename | Path
-- | -- | -- | --
41 | var initializer =   comSvc.GetService<IHostInitializer>(); | ConsoleInitializer.cs | src\NuGet.Clients\NuGet.Console\ConsoleInitializer.cs
23 | [assembly: SuppressMessage("Build",   "CA1062:In externally visible method 'T   CommonExtensionMethods.GetService<T>(IServiceProvider sp, Type   serviceType)', validate parameter 'sp' is non-null before using it. If   appropriate, throw an ArgumentNullException when the argument is null or add   a Code Contract precondition asserting non-null argument.",   Justification = "<Pending>", Scope = "member",   Target = "~M:NuGetConsole.CommonExtensionMethods.GetService``1(System.IServiceProvider,System.Type)~``0")] | GlobalSuppressions.cs | src\NuGet.Clients\NuGet.Console\GlobalSuppressions.cs
63 | PowerConsoleWindow =   ComponentModel.GetService<IPowerConsoleWindow>() as PowerConsoleWindow; | PowerConsoleCommands.cs | src\NuGet.Clients\NuGet.Console\PowerConsoleCommands.cs
51 | get {   return ComponentModel.GetService<IPowerConsoleWindow>() as   PowerConsoleWindow; } | PowerConsoleToolWindow.cs | src\NuGet.Clients\NuGet.Console\PowerConsoleToolWindow.cs
32 | public static T   GetService<T>(this IServiceProvider sp, Type serviceType) | CommonExtensionMethods.cs | src\NuGet.Clients\NuGet.Console\Utils\CommonExtensionMethods.cs
35 | return   (T)sp.GetService(serviceType); | CommonExtensionMethods.cs | src\NuGet.Clients\NuGet.Console\Utils\CommonExtensionMethods.cs
57 | var uiShell =   _serviceProvider.GetService<SVsUIShell, IVsUIShell>(); | SolutionUserOptions.cs | src\NuGet.Clients\NuGet.PackageManagement.UI\UserInterfaceService\SolutionUserOptions.cs
69 | var   uiShell = _serviceProvider.GetService<SVsUIShell, IVsUIShell>(); | SolutionUserOptions.cs | src\NuGet.Clients\NuGet.PackageManagement.UI\UserInterfaceService\SolutionUserOptions.cs
36 | () =>   serviceProvider.GetService<SVsUIShell, IVsUIShell>()); | OptionsPageActivator.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\OptionsPageActivator.cs
64 | ()   => componentModel.GetService<ISolutionRestoreWorker>()); | ProjectRetargetingHandler.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Handlers\ProjectRetargetingHandler.cs
42 | _threadingService =   _componentModel.GetService<IVsProjectThreadingService>(); | DeferredProjectServicesProxy.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\ProjectServices\DeferredProjectServicesProxy.cs
93 | public T   GetGlobalService<T>() where T : class =>   _componentModel.GetService<T>(); | DeferredProjectServicesProxy.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\ProjectServices\DeferredProjectServicesProxy.cs
23 | public T GetGlobalService<T>()   where T : class => _componentModel.GetService<T>(); | GlobalProjectServiceProvider.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\ProjectServices\GlobalProjectServiceProvider.cs
49 | return   (IVsSolutionWorkspaceService)serviceProvider.GetService(typeof(SVsSolutionWorkspaceService)); | DeferredProjectWorkspaceService.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Services\DeferredProjectWorkspaceService.cs
79 | var factory =   SolutionWorkspaceService.GetService<IVsSolutionMSBuildProjectServiceFactory>(); | DeferredProjectWorkspaceService.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Services\DeferredProjectWorkspaceService.cs
31 | var   versionControl = projectCollection.GetService<VersionControlServer>(); | DefaultTFSSourceControlManager.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\SourceControl\DefaultTFSSourceControlManager.cs
66 | return   serviceProvider.GetService<SVsTrackProjectDocuments,   IVsTrackProjectDocuments2>(); | VsSourceControlTracker.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\SourceControl\VsSourceControlTracker.cs
686 | var   retValue = sp.GetService(typeof(INuGetPackageManager)); | EnvDTEProjectUtility.cs | src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\Utility\EnvDTEProjectUtility.cs
631 | var job =   componentModel.GetService<ISolutionRestoreJob>(); | SolutionRestoreWorker.cs | src\NuGet.Clients\NuGet.SolutionRestoreManager\SolutionRestoreWorker.cs
263 | //   Switch to Main Thread before calling AddCommand which calls GetService()   which should | NuGetPackage.cs | src\NuGet.Clients\NuGet.Tools\NuGetPackage.cs
378 | var uiShell =   (IVsUIShell)GetService(typeof(SVsUIShell)); | NuGetPackage.cs | src\NuGet.Clients\NuGet.Tools\NuGetPackage.cs
35 | return   (IVsOutputWindow)serviceProvider.GetService(typeof(SVsOutputWindow)); | ShowErrorsCommand.cs | src\NuGet.Clients\NuGet.Tools\Commands\ShowErrorsCommand.cs
44 | return   (IVsUIShell)serviceProvider.GetService(typeof(SVsUIShell)); | ShowErrorsCommand.cs | src\NuGet.Clients\NuGet.Tools\Commands\ShowErrorsCommand.cs
37 | [assembly: SuppressMessage("Build",   "CA1062:In externally visible method 'TService   ServiceProviderExtensions.GetService<TService>(IServiceProvider   serviceProvider)', validate parameter 'serviceProvider' is non-null before   using it. If appropriate, throw an ArgumentNullException when the argument is   null or add a Code Contract precondition asserting non-null argument.",   Justification = "<Pending>", Scope = "member",   Target = "~M:NuGet.VisualStudio.ServiceProviderExtensions.GetService``1(System.IServiceProvider)~``0")] | GlobalSuppressions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\GlobalSuppressions.cs
38 | [assembly:   SuppressMessage("Build", "CA1062:In externally visible method   'TInterface ServiceProviderExtensions.GetService<TService,   TInterface>(IServiceProvider serviceProvider)', validate parameter   'serviceProvider' is non-null before using it. If appropriate, throw an   ArgumentNullException when the argument is null or add a Code Contract   precondition asserting non-null argument.", Justification =   "<Pending>", Scope = "member", Target =   "~M:NuGet.VisualStudio.ServiceProviderExtensions.GetService``2(System.IServiceProvider)~``1")] | GlobalSuppressions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\GlobalSuppressions.cs
134 | return   componentModel?.GetService<TService>(); | ServiceLocator.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\ServiceLocator.cs
19 | return   serviceProvider.GetService<SDTE, EnvDTE.DTE>(); | ServiceProviderExtensions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\ServiceProviderExtensions.cs
24 | return   serviceProvider.GetService<SComponentModel, IComponentModel>(); | ServiceProviderExtensions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\ServiceProviderExtensions.cs
27 | public static TService   GetService<TService>( | ServiceProviderExtensions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\ServiceProviderExtensions.cs
31 | return   serviceProvider.GetService(typeof(TService)) as TService; | ServiceProviderExtensions.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\ServiceProviderExtensions.cs
49 | return   ServiceProvider.GlobalProvider.GetService(typeof(SVsShell)) != null; | TelemetryUtility.cs | src\NuGet.Clients\NuGet.VisualStudio.Common\Telemetry\TelemetryUtility.cs
296 | var   solution = ServiceProvider.GlobalProvider.GetService(typeof(SVsSolution)) as   IVsSolution; | VsTemplateWizard.cs | src\NuGet.Clients\NuGet.VisualStudio.Implementation\VsTemplateWizard.cs
29 | var componentModel =   (IComponentModel)serviceProvider.GetService(typeof(SComponentModel)); | TemplateWizard.cs | src\NuGet.Clients\NuGet.VisualStudio.Interop\TemplateWizard.cs
180 | $repositoryProvider =   $componentModel.GetService([NuGet.Protocol.Core.Types.ISourceRepositoryProvider]) | nuget.psm1 | src\NuGet.Clients\NuGetConsole.Host.PowerShell\Scripts\nuget.psm1

**Comment by nkolev92** [comment]
You can create multiple PRs for this effort. 
Don't wait on completeing all the work for a PR.

**Comment by nkolev92** [comment]
Maybe it's a naive assumption by me, but most of these changes should be straightforward and not require individual testing, rather they can be tested as one entity.

**Comment by zivkan** [comment]
My memory is that some of the `GetService` calls are in sync code, so calling `GetServiceAsync` is not appropriate, without converting the method to async as well, and repeat all the way up the call stack until an "entry point". This will increase the code impact, and perhaps warrants a few PRs, rather than just 1. Unless I'm wrong and every `GetService` call is already in an async method.

**Comment by nkolev92** [comment]
I think approaching this with a mindset of making incremental improvements is great. 

Certain things will lead to changes from sync to async APIs and have a small footprint. 
Others will be harder. 

Focusing on the easy/frequent codepaths is a good first pass. 
Some changes might be harder to do. I think it's a reasonable suggestion to not do some of those immediately.

**Comment by nkolev92** [comment]
@srdjanjovcic's work for reducing UI delays overlaps with this one.

**Comment by nkolev92** [comment]
@erdembayar If you end up having more bandwith this sprint, please pick up this task. 

Remember to consider an incremental approach.

**Comment by erdembayar** [comment]
There are still few instances of 'GetService' are still left but replacing them with GetServiceAsync doesn't do any good for now, because we have wrap it inside another JTF, so end result would be same or bit worse. Most of them related to PMC and most likely will be addressed in the future when we refactor it.
