### ISSUE TITLE
Solution Restore and Build Restore still show dialogs

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3789]
when in .net core projects, there should be no way to see a restoring dialog.

1file new project> asp.net core web app
2auto restore works.
3 if you build, restore dialog shows up
or
4 if you solution restore, restore dialog shows up

**Comment by rrelyea** [comment]
evaluate risk, for .net core only.  then for that and uwp.

**Comment by alpaix** [comment]
Resolved with NuGet/NuGet.Client#1052.
