### ISSUE TITLE
[NuGet.VisualStudioExtension] Empty solution folder is not removed from WebSite project after package uninstall

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#379]
The folder was added by package install.

Run-test WebSiteUninstallPackageWithNestedSourceFilesAndAnotherProject 
Run-test WebSiteUninstallPackageWithNestedSourceFiles 
Run-test WebSiteUninstallPackageWithPPVBSourceFiles 
Run-test WebSiteUninstallPackageWithPPCSSourceFiles

**Comment by danliu** [comment]
assigned to @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Fixed in NuGet/NuGet.VisualStudioExtension@2dc7ffd2f619774be39ae86f421437a49949f24f
