### ISSUE TITLE
additional "g" in nuget props and target files for CPS project system

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3790]
Not sure if it's expected or issue but with CPS based project, nuget prop and target files names are as follow:

*.csproj.nuget.g.props
*.csproj.nuget.g.targets

Feels like an additional g?

**Comment by emgarten** [comment]
This is expected, the `.g` stands for generated file. It lets users know not to edit this file directly since something else is used as the input to create it.

**Comment by jainaashish** [comment]
ok then closing this.
