### ISSUE TITLE
GetService error while installing package on CPS project system

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3792]
1. Create CPS project with dev15
2. try installing newtonsoft.json 8.0.1 package, it will fail since not compatible with .net standard 1.4
3. then try installing newtonsoft.json 9.0.1 package, it will throw GetService error.

Complete logs:

Restoring packages for c:\users\asja\documents\visual studio 2017\Projects\CPSProj2\CPSProj2\CPSProj2.csproj...
Restoring packages for c:\users\asja\documents\visual studio 2017\Projects\CPSProj2\CPSProj2\CPSProj2.csproj...
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json 226ms
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/8.0.1/newtonsoft.json.8.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/8.0.1/newtonsoft.json.8.0.1.nupkg 228ms
Installing Newtonsoft.Json 8.0.1.
Package Newtonsoft.Json 8.0.1 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Newtonsoft.Json 8.0.1 supports:
- net20 (.NETFramework,Version=v2.0)
- net35 (.NETFramework,Version=v3.5)
- net40 (.NETFramework,Version=v4.0)
- net45 (.NETFramework,Version=v4.5)
- portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
- portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  One or more packages are incompatible with .NETStandard,Version=v1.4.
  Package restore failed. Rolling back package changes for 'CPSProj2'.

========== Finished ==========

Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should instead call GetServiceAsync (without calling Result or Wait on the resultant Task object) or switch to the UI thread with the JoinableTaskFactory.SwitchToMainThreadAsync method before calling GetService.
========== Finished ==========

**Comment by zhili1208** [comment]
Repro with 4.0.2027 and validate with 4.0.2028, 2028 doesn't repro this issue any more
