### ISSUE TITLE
Update tab not refreshed after installing a package

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3793]
1. create cps based library project with d15 25825.4 with 2027 nuget vsix
2. install jquery 3.1.0 

Expected:
After installation, it should show 1 update available in update tab.

Actual:

![image](https://cloud.githubusercontent.com/assets/18219758/19752907/90f5284a-9bb5-11e6-9ee1-74ae5388ab81.png)

**Comment by rrelyea** [comment]
any update (ha ha)

**Comment by jainaashish** [comment]
Fixed with latest 2033 build.
