### ISSUE TITLE
Restore fails to resolve p2p references

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3794]
Build 2028

Restore is unable to resolve p2p references from .NETCore projects.
### Steps
1. Create a new .NETCore console app
2. Create another new .NETCore console app in the solution
3. Add a reference from one to the other
4. (Restore auto runs)
### Expected

No failures
### Actual

```
Unable to resolve '..\ConsoleApp2\ConsoleApp2.csproj' for '.NETCoreApp,Version=v1.0'.
```

**Comment by rrelyea** [comment]
Assume this is package spec creation problem in auto restore?

**Comment by emgarten** [comment]
> Assume this is package spec creation problem in auto restore?

Yes, I think it's just a small fix there

**Comment by alpaix** [comment]
@emgarten Do you think the relative project path could be the root cause here?

**Comment by emgarten** [comment]
@alpaix yes, relative path was the main issue. Also project references now go under the restore metadata since these are paths instead of package ids, the project id is resolved later.
