### ISSUE TITLE
Can't browse packages while install is running

### ISSUE THREAD

**Issue by philmagr** [NuGet/Home#3796]
## Details about Problem

NuGet product used: VS UI

NuGet version: No idea. Google only tells me how to get the command line version.

VS version (if appropriate): 2015

OS version: win10 v1511 (10586.589)

Worked before? If so, with which NuGet version: no idea
## Detailed repro steps so we can see the same problem
1. Find a package
2. Install that package
3. Try to find next package you want to install

Expected: Able to search for packages while an install is running

Actual: Install disables search for some reason

**Comment by jainaashish** [comment]
This is by design, since install is running on UI thread which is why it doesn't allow you to start another action on UI. Even though it allows, then also it wont do anything until install is completed.
