### ISSUE TITLE
Successful restore message is displayed even after error during restore.

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3799]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VSIX

NuGet version (x.x.x.xxx): 4.0.0.2027

VS version (if appropriate): d15prerel/15.0.25825.4
## Detailed repro steps so we can see the same problem
1. Create new .Net core console app and build app.
2. Delete all packages in global packages folder.
3. Perform restore on the solution.
4. Check output window.
5. Even though there were errors, the message says that the restore was successful.
## Actual

========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
All packages are already installed and there is nothing to restore.
Error occurred while restoring NuGet packages: Access to the path 'Microsoft.NET.Build.Tasks.dll' is denied.
All packages are already installed and there is nothing to restore.

**Comment by nkolev92** [comment]
Doesn't repro anymore with:
NuGet Version: 4.0.0.2275
VS Version: 26206.0-d15rel
