### ISSUE TITLE
Add an overload to IVsPackageInstaller.InstallPackagesFromRegistryRepository that allows specifying a version range

### ISSUE THREAD

**Issue by eerhardt** [NuGet/Home#380]
`IVsPackageInstaller.InstallPackage` accepts a version spec which allows us to specify a `VersionRange`. However all the APIs that accept a registry key as the source treat the version as a specific version rather than a range.

Additionally, we need to ensure that the DNU directory structure can be consumed by these APIs. This should be addressed by https://github.com/NuGet/Home/issues/401

~~There are APIs to automate installing a NuGet package programmatically from inside VS.  We use these APIs in our tooling scenarios.  When we want to install a NuGet package from a local, well-known repository, we need to pass in the repository path into the APIs.  However, this path can change from machine to machine.  So currently the only way to do this reliably is to read the registry at HKLM\Software\NuGet\Repository to get the local repository path.~~

~~Instead, there should be an API where I can just pass in the local repository name, and the NuGet Package Manager figures out where the local repository exists.~~

**Comment by pranavkm** [comment]
Isn't this covered by `IVsPackageInstaller.InstallPackage` overloads that accept a source repository:

* http://nuget.codeplex.com/SourceControl/latest#src/VisualStudio/Extensibility/IVsPackageInstaller.cs
* https://github.com/NuGet/NuGet.VisualStudioExtension/blob/dev/src/VisualStudioAPI/Extensibility/IVsPackageInstaller.cs#L32

**Comment by eerhardt** [comment]
That API doesn't work for the "DNU_VS14" repository for ASP.NET 5 packages.  In the VS 2015 RC build, an exception is thrown when executing the following code:

        [Import(typeof(IVsPackageInstaller))]
        protected IVsPackageInstaller PackageInstaller { get; set; }

...
            this.PackageInstaller.InstallPackagesFromRegistryRepository("DNU_VS14", false, false, project,
                new Dictionary<string, string>
                {
                    { "Microsoft.Framework.ConfigurationModel.Json", "1.0.0-beta4" }
                });

System.InvalidOperationException: Download stream is null
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()

**Comment by pranavkm** [comment]
Sorry I'm not super familiar with the code here, but what do you mean by
> That API doesn't work for the "DNU_VS14" repository for ASP.NET 5 packages

Isn't this the code you need to be calling if you don't want the regsitry key:
`PackageInstaller.InstallPackage("DNU_VS14_Path", project, "Microsoft.Framework.ConfigurationModel.Json", "1.0.0-beta4" , ignoreDependencies: false);`?

**Comment by eerhardt** [comment]
"DNU_VS14_Path" isn't going to work as that isn't a valid source.  It throws the following exception:
System.InvalidOperationException occurred
  Message=Download resource not found
  Source=NuGet.PackageManagement
  StackTrace:
       at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__ea.MoveNext()

**Comment by pranavkm** [comment]
What happens when you pass in a real path \ name of a source?

**Comment by pranavkm** [comment]
cc @yishaigalatzer @emgarten Spoke to @eerhardt offline and we have a better understanding of what the changes are for this. Do we need to triage this again for RTM?

**Comment by pranavkm** [comment]
@eerhardt We discussed this yesterday and our current plan is to move away from the registry based specification for the repository to a centralized (well-known) repository location. We'll continue maintaining the APIs we have now, but don't plan on investing in them further. If the API that accepts a version range works for you, I'd recommend continue using it for the time being.
