### ISSUE TITLE
NuGet v3.0 API guidance

### ISSUE THREAD

**Issue by manu-st** [NuGet/Home#3802]
Hi,

I'm migrating some code that was using NuGet v2.0 to use the new NuGet v3.0. I'm having some issues most related to the way things are now working. One example is when installing a package, in the old API you could get callbacks on the progress of the download, in v3.0 I only found PackageProgressEventArgs but this is not used at all.

Where is the best place to discuss the API usage with others more knowledgeable?

Thanks,
Manu

**Comment by rrelyea** [comment]
Dave Glick has written a 3 part set of posts that provide a good starting point: http://daveaglick.com/tags/nuget

**Comment by manu-st** [comment]
I did read the 3 parts article but I'm afraid it doesn't go deep enough. Isn't there some group where we can discuss the underlying API? I have many questions on the way things are done.

For example in today's API, when you install a package, it will download the package, extract it in the main .nuget/packages, and then copy all the files where you want it to be installed. Whereas I'm looking at just downloading the package in .nuget/packages and then extracting the files where I want to.

Another scenario, deleting a package only deletes it from where you installed it. But how do you remove it from .nuget/packages?

So far due to the lack of communication/documentation, I've been hacking my way through customizing the API or adding stuff on top of it. That's not an ideal solution.

Thanks
