### ISSUE TITLE
UI does not always match project state in .NET Core multitargetting projects

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3803]
## Steps
1. Open a new d15 (I used d15prerel).
2. New .NET Core class library
3. Unload project and edit the .csproj.
4. Multi-target. `<TargetFrameworks>netstandard1.4;netstandard1.5</TargetFrameworks>` is the easiest.
5. Reload project and Manage NuGet Packages...
6. Install Newtonsoft.Json.
7. Switch to Installed tab
## Expected

Newtonsoft.Json should be listed.
## Actual

Newtonsoft.Json is not under the installed tab.
## Extra

Try uninstalls and updates as well. Same problem.
## Workaround

Reload the project.

**Comment by rrelyea** [comment]
This only repros with multitargetting?

**Comment by joelverhagen** [comment]
Yes, @jainaashish did you run into any weirdness without multi-targeting?

**Comment by jainaashish** [comment]
I thought I saw some weirdness even with single tfm but now it looks good. So this repros only with multi-tfms

**Comment by jainaashish** [comment]
Nominate project api isn't being called after packages are installed/ uninstalled which is why we aren't able to update UI. 
Communicated to Balaji/ Nat about the issue and awaiting their response.

**Comment by rrelyea** [comment]
External issue, we believe: https://github.com/dotnet/roslyn-project-system/issues/672

**Comment by jainaashish** [comment]
Validated and closing this issue since external issue is also closed.
