### ISSUE TITLE
Installing Newtonsoft.Json to Wpf throws error about execution of install.ps1 but still installs

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3805]
Versions: d15prerel/25825.4 NuGet/2033
## Steps
1. New wpf application
2. Install Newtonsoft.Json
3. See output logs
## Log

Attempting to gather dependency information for package 'Newtonsoft.Json.9.0.1' with respect to project 'WpfApp4', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 398.02 ms
Attempting to resolve dependencies for package 'Newtonsoft.Json.9.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.9.0.1'
Resolved actions to install package 'Newtonsoft.Json.9.0.1'
Retrieving package 'Newtonsoft.Json 9.0.1' from 'nuget.org'.
Adding package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\anmishr\documents\visual studio 2017\Projects\WpfApp4\packages'
Added package 'Newtonsoft.Json.9.0.1' to folder 'c:\Users\anmishr\documents\visual studio 2017\Projects\WpfApp4\packages'
Added package 'Newtonsoft.Json.9.0.1' to 'packages.config'
Executing script file 'c:\Users\anmishr\documents\visual studio 2017\Projects\WpfApp4\packages\Newtonsoft.Json.9.0.1\tools\install.ps1'...
& : File C:\Users\anmishr\documents\visual studio 
2017\Projects\WpfApp4\packages\Newtonsoft.Json.9.0.1\tools\install.ps1 cannot be loaded because running scripts is 
disabled on this system. For more information, see about_Execution_Policies at 
http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:45
- ... rgs+=$_}; & 'c:\Users\anmishr\documents\visual studio 2017\Projects\W ...
-                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : SecurityError: (:) [], PSSecurityException
  - FullyQualifiedErrorId : UnauthorizedAccess
    Successfully installed 'Newtonsoft.Json 9.0.1' to WpfApp4
    Executing nuget actions took 2.92 sec
    ========== Finished ==========
    Time Elapsed: 00:00:03.4934228

**Comment by jainaashish** [comment]
It's working fine. May be you didn't have the right execution policy set for your powershell. Execute below command from any powershell window n then try again.

`Set-ExecutionPolicy Unrestricted`

**Comment by rrelyea** [comment]
@zhili1208  - you've done investigations about this before, haven't you. Any info you can share?

**Comment by zhili1208** [comment]
What I investigated before is not the same issue, mine is about language mode, this is execution policies, user need to set right execution policies on their machine to enable script

**Comment by mishra14** [comment]
Tried with this setup: 
Win 10;
VS 2017 RC/d15prerel/15.0.25828.0; 
NuGet 4.0.0.2036; 

Cannot repro. Closing the bug.
