### ISSUE TITLE
Lock projects during restore with CPS IProjectLockService

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3807]
CPS Projects should be locked during restore so that consumers of restore outputs can wait until the result is complete.

**Comment by rrelyea** [comment]
Moving to RC2. We think the other fix in RC likely covers it, and this will be hard to converge in short order.

**Comment by rrelyea** [comment]
Looks like we'll need this asap. In my testing on 25928.3 (hard to install), net core console apps were having auto restore not run often.

**Comment by emgarten** [comment]
@rrelyea were you getting the same error dialog as we saw before? are we sure this locking would help trigger auto-restore reliably?

**Comment by rrelyea** [comment]
When i used 2034 build, with 25828.03 build, auto restore was not always working. Went back to 2033 and it did. Perhaps we just debit that situation.

**Comment by rrelyea** [comment]
drew is home sick, up for grabs.

**Comment by emgarten** [comment]
@rrelyea is this still needed? have we been able to confirm that auto-restore not happening was caused by CPS getting into a bad state due to not locking the restore outputs?

**Comment by rrelyea** [comment]
we believe this is not needed. will bring back if that changes.

**Comment by emgarten** [comment]
The current move fix seems to have resolved this. Adding extra locking for restore in Visual Studio would mean that restores done from the command line would not be protected, which is a problem. If there are remaining issues it should be fixed in the project system ideally.

**Comment by emgarten** [comment]
@rrelyea moving this to you for tracking

**Comment by emgarten** [comment]
Closing since this no longer appears to be needed.
