### ISSUE TITLE
Code fix: PowerConsoleToolWindow and other places should use ServiceLocator.GetInstance

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#381]
Code fix: PowerConsoleToolWindow and other places should use ServiceLocator.GetInstance

**Comment by deepakaravindr** [comment]
Assigning to @danliu who is the SME on this class

**Comment by danliu** [comment]
Fixed via https://github.com/NuGet/NuGet.VisualStudioExtension/commit/dea9fa38ee6909f6c8bee412bc09b0e62262123a
