### ISSUE TITLE
Renaming a project/solution folder breaks integrity

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#3811]
Because NuGet relies on <HintPath> a user can - legitimately - rename a project or solution and also the project and solution folder names. Any <HintPath> that was referring to these folder names thus becomes invalid.

This causes masses of unresolved references and the only fix seems to be manually and carefully editing the project file.

This is one more weakness in the whole NuGet design, innocent, valid user actions can break assumptions made by NuGet and render solutions unbuildable.

**Comment by rrelyea** [comment]
NuGet packages.config style does have this problem.
Project.Json, as used in UWP apps today, and possible for many project types to migrate to -- doesn't have this problem. It generates the references on the fly, during build.

We are focusing in our NuGet 4.0 release, in conjunction with the next VS release, on evolving our Project.Json benefits to a unified model for .net core and existing project types.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
