### ISSUE TITLE
Confirm restore works in asp.net core project per internal bug

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3813]
Internal bug 283939 - should be fixed by #3739 - please install 4.0.0.2036 and confirm

**Comment by mishra14** [comment]
Restore seems fixed. Tracking another internal bug 284913 to ensure that this is fixed

Update: 284913 is the typescript issue, which is fixed and closed.

**Comment by mishra14** [comment]
Validated 283939 on d15Rel/25831.1. Closing.
