### ISSUE TITLE
Runtimes error in console app restore

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3815]
Following error occurs when console app restored. Also seems to be giving misleading project.json error from a package reference project.

Build started 10/28/2016 11:03:42 AM.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.Solution.ImportAfter.targets(17,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (22,3)". This is most likely a build authoring error. This subsequent import will be ignored. [c:\Users\tomescht\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
Project "c:\Users\tomescht\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj" on node 1
(rebuild target(s)).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(162,5): error : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win": { } }' to your project.json and then re-run NuGet restore. [c:\Users\tomescht\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
Done Building Project "c:\Users\tomescht\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj" (rebuild target(s)) -- FAILED.

**Comment by drewgillies** [comment]
This is now unblocked. Missed a step in csproj conversion from project.json. Closing.

**Comment by jmelosegui** [comment]
@drewgillies could you share those steps??
