### ISSUE TITLE
Get-Project returns null (in CPS or Legacy csproj only)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3818]
Blocks EF team, and NuGet end-to-end tests.

**Comment by rrelyea** [comment]
this had some regressions in end to end tests. likely needs continued investigation.

**Comment by rrelyea** [comment]
nuget 4.0.0.2040 has this fix...@bricelam could try that out. however see above about regressions. did it help you?

**Comment by bricelam** [comment]
It works. Thank you!

**Comment by jainaashish** [comment]
Approved to insert on 11/1 VS shiproom.

**Comment by rrelyea** [comment]
In NuGet builds as of 4.0.0.2040. In VS as of d15Rel 25901.02.
