### ISSUE TITLE
Get-Project related errors in E2E failures

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3820]
Based on [http://nugetci/viewLog.html?buildId=56094&tab=buildResultsDiv&buildTypeId=EndToEndTests_Vs15EndToEndTestsPrivateDevBranches](http://nugetci/viewLog.html?buildId=56094&tab=buildResultsDiv&buildTypeId=EndToEndTests_Vs15EndToEndTestsPrivateDevBranches)

Its possible that Get-ProjectDir, Get-ProjectItem are failing because of a common issue with #3818

We need to investigate once #3818 is fixed. 

//cc : @jainashish @rrelyea

**Comment by jainaashish** [comment]
This should have been fixed with https://github.com/NuGet/Home/issues/3818 pls verify on new build!

**Comment by rrelyea** [comment]
E2E is clean of these issues. @mishra14 - please reactivate if that changes.
