### ISSUE TITLE
Page Not found is coming for "Matching assembly versions and target framework in a project"

### ISSUE THREAD

**Issue by Zulqarnain-ZQ** [NuGet/Home#3822]
I was going through the documentation of Nuget for creating a simple package and found out one link on below page:
https://docs.nuget.org/ndocs/create-packages/supporting-multiple-target-frameworks

That link was related to "Matching assembly versions and target framework in a project". On clicking that link, 404 Page not found message is shown. URL for that page is:
https://docs.nuget.org/ndocs/create-packages/matching-assembly-versions-and-the-target-framework-in-a-project

![nuget documentation](https://cloud.githubusercontent.com/assets/23140329/19831305/59890b0c-9e20-11e6-8dc0-f0c917311357.png)

**Comment by yishaigalatzer** [comment]
Thanks, we will get it fixed. I hope by early next week

**Comment by karann-msft** [comment]
Fixed!
