### ISSUE TITLE
Validate we Support Unicode in owner name and other properties

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#3824]
Validate that various properties in a package can support unicode:

For example - Owner = För

Validate that pack works for nuspec, and `<PackageReference>` scenario, and that the UI shows the owners correctly after pushing to a server/nuget.org

**Comment by rohit21agrawal** [comment]
Validated by using an authors value containing chinese charatcers, packing them from a csproj file, and uploading it to nuget.org. all characters were displayed properly.
