### ISSUE TITLE
Show the build number of NuGet in the Help-About entry

### ISSUE THREAD

**Issue by balachir** [NuGet/Home#3825]
## Details about Problem

NuGet product used: VS UI

NuGet version : 4.0.0.2039

VS version (if appropriate): d15prerel.25830.00

OS version: Win10 v1607
## Detailed repro steps so we can see the same problem
1. Install above build of Dev15 RC 
2. Start VS, open Help About
## ACTUAL

NuGet version shows up as 4.0.0
![image](https://cloud.githubusercontent.com/assets/8246794/19841781/accb8f26-9ecd-11e6-8fe6-12a869ed3bbb.png)
## EXPECTED

Show the build number as well in Help-About. Like: 4.0.0.2039

That way customers can easily know exactly what build of NuGet they have installed.

**Comment by PatoBeltran** [comment]
Closing this out. NuGet now ships hand in hand with VS, therefore specific NuGet versions are less important because they are tied to specific VS versions.
