### ISSUE TITLE
[NuGet.VisualStudioExtension] Fail to install satellite package to web site project

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#383]
Run-test InstallingSatellitePackageToWebsiteCopiesResourcesToBin

The resource dll was not copied/added to the bin folder of the web site project

**Comment by danliu** [comment]
assigned at @AndriySvyryd

**Comment by AndriySvyryd** [comment]
Problem:
   When installing a localized package to a Web Site the satellite assemblies are not copied to the Bin folder

Cause:
   The satellite assemblies are copied by the project system when the main assembly reference is added. But at the time when NuGet adds that reference the localized package hasn't been installed yet

Solution:
    All the packages should be installed first at the solution level and only after that should the references be added to the projects. However making this change is risky.

Workaround:
   Users can just build the project or use "Update Reference" from the context menu.

**Comment by AndriySvyryd** [comment]
Used the workaround in the test: NuGet/NuGet.VisualStudioExtension@a3935a78f236028634e63fefddff83d86ef7fa86
