### ISSUE TITLE
Fail to deploy Web Single Page Application on IE due to ‘Microsoft.AI.Web’ could not be loaded

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3831]
See internal bug # 285525 - which includes repro machines that you can log into via maddog. (let me know if you need help).
This appears to have regressed with Ashish' fix for #3818 
Please work with @jainaashish as necessary.

**Comment by rrelyea** [comment]
From chat with Zhi:
the issue is package installation doesn't add reference for applicationInsight, it only happens for single web application project, web api and mvc works well. still working on figuring out why

**Comment by rrelyea** [comment]
@emgarten is investigating wizard install of a package here: #3832
related?

**Comment by zhili1208** [comment]
I think this is a template issue, the template call nuget api to install 7 ApplicationInsight packages and pass true to skipAssemblyReferences, that means template hard code the package path in csproj, nuget will skip assembly adding part. But in SPA, there is no applicationInsight hard code path in csproj but skipAssemblyReference is true. then applicationInsight packages are not added to csproj

**Comment by rrelyea** [comment]
Can you see if this is a regression from VS 2015?
Update: Seems like template did change...
