### ISSUE TITLE
NuGet.exe restore on vs "15" machine only fails

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3834]
error MSB4062: The "NuGet.Build.Tasks.GetRestoreProjectJsonPathTask" task could ot be loaded from the assembly D:\tmp\tmp\NuGet.exe.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Mcrosoft.Build.Framework.ITask.

**Comment by unniravindranathan-okta** [comment]
@rrelyea @zhili1208 Please dupe against https://github.com/NuGet/Home/issues/3753

**Comment by rrelyea** [comment]
dupe of #3753. Going to bring #3753 to RC from RC2.
