### ISSUE TITLE
Install package may overlap with auto-restore

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3836]
Follow up on NuGet/NuGet.Client#986.

## Details about Problem

Install package runs restore/preview operation. This may overlap with auto-restore running in background. Potentially this may introduce dangerous race conditions as in current implementation there's no mutual blocking for these operations.

## Suggested solution

Consider chaining install/uninstall package operations with auto-restore using the same mechanism employed by on-build/explicit restore.

**Comment by rrelyea** [comment]
Do not block your other fix on this issue.
