### ISSUE TITLE
Behavioral changes in `dotnet pack --version-suffix foo`

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3838]
## Details about Problem

dotnet.exe --version (if appropirate):
1.0.0-preview3-003986

VS version (if appropriate):
Windows 10

Worked before? If so, with which NuGet version:
project.json-based nuget pack

## Detailed repro steps so we can see the same problem

1. Create a new csproj application `dotnet new`
2. Add a `versionprefix` property:
    `<VersionPrefix>1.2.3-preview3</VersionPrefix>`
3. Pack the project with a version suffix: `dotnet pack --version-suffix foo`

Expected:
Like in project.json, the resulting package version should be `1.2.3-preview3-foo`

Actual:
The later part of the prefix is ignored, resulting in `1.2.3-foo`

This is preventing migrated projects from packing as expected.

/cc @rohit21agrawal @rrelyea @livarcocc

**Comment by rrelyea** [comment]
@piotrpMSFT we'll dig into this. want to work well for scenarios, but not strictly trying to match all behaviors of pack from preview2.

**Comment by livarcocc** [comment]
We need this in the CLI because we need to pack signed bits. The way we do that is we build in one location, sign it and then do the pack pointing to the already built and signed bits.

**Comment by rrelyea** [comment]
We don't want dotnet.exe and nuget.exe to diverge. Joel to work with CLI to ensure scenario still works well.

**Comment by joelverhagen** [comment]
This feature was added to nuget.exe with https://github.com/NuGet/Home/issues/694. 3.4.0 was the first release with this feature, I believe. When it was implemented, the logic _replaces_ the release label, not appends to it. This has shipped and should not change in behavior.

@piotrpMSFT, @livarcocc: is this an representative summary of the preview2 CLI commands you are executing (build, pack, anything else) to achieve signing?
1. Put a suffixed version in your project.json, e.g. `2.0.0-beta-*`
2. `dotnet build --version-suffix final`
3. Sign.
4. `dotnet pack --version-suffix final --no-build`

Your expectation is that the assembly metadata and the package version match.

I propose that we keep nuget.exe and preview3 pack as-is and CLI will modify their pack steps to:

`dotnet pack --no-build "/p:Version=2.0.0-beta-final"`

**Comment by TheRealPiotrP** [comment]
@joelverhagen is there some middle ground? It's unfortunate if folks have to change their builds around this [we now have to move data from project file into build configuration... it'll be a lot of new data as we list project files to which a given suffix applies]. Can we enable some approach by which migrated project.json's actually pack correctly?

**Comment by joelverhagen** [comment]
An option could adding `--append-version-suffix` switch (`$(AppendVersionSuffix)` in MSBuild) which turns this behavior on. Migrated projects could bake this into the .csproj if the sourcing project.json had a version ending in `-*`, e.g. `"version": "1.0.0-*"`.

@rrelyea, @piotrpMSFT, @harikmenon, @rohit21agrawal, thoughts?

**Comment by rohit21agrawal** [comment]
1) I am personally not in favor of adding a new command line parameter - my suggestion would be to treat --version-suffix as an indication that the suffix needs to be appended into the string irrespective of whether the version ends in \* or not. 

2) --build-base-path : why can't you just use a msbuild variable to tell msbuild where to put the the build artifacts?

**Comment by joelverhagen** [comment]
Related: https://github.com/dotnet/sdk/issues/93

**Comment by joelverhagen** [comment]
Another option is to provide a convenience MSBuild property to migrated projects.

project.json:

``` json
{
  "version": "2.0.0-beta-*"
}
```

migrated .csproj:

``` xml
<VersionPrefix>2.0.0</VersionPrefix>
<VersionSuffix Condition="'$(AppendedVersionSuffix)' == ''">beta</VersionSuffix>
<VersionSuffix Condition="'$(AppendedVersionSuffix)' != ''">beta-$(AppendedVersionSuffix)</VersionSuffix>
```

commands

```
dotnet.exe build /p:AppendedVersionSuffix=1333
dotnet.exe pack /p:AppendedVersionSuffix=1333
```

**Comment by joelverhagen** [comment]
Design task is tracked here: https://github.com/NuGet/Home/issues/3887. For now, please work around the issue by providing MSBuild properties from the command line, `/p:FOO=BAR` style.
