### ISSUE TITLE
NuGet.Exe 3.4 Cli add command doesn't take FileConflictAction option

### ISSUE THREAD

**Issue by joshmachol** [NuGet/Home#3842]
> nuget add packagename -Source packagesource -FileConflictAction Overwrite
> Unknown option: '-FileConflictAction'

Same error with nuget 3.3 and 3.4.

The [NuGet.Exe Cli Reference](https://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#add) specifies that the add command is available for 3.3+, and it also includes fileconflictaction in the list of options being available for 2.5+.

I take this to mean that NuGet.Exe 3.4 Cli's add command should be able to take the option fileconflictaction. Am I misunderstanding the documentation, or should this option be supported by the add command?

**Comment by Jaben** [comment]
Having the same issue. Any resolutions?

**Comment by rrelyea** [comment]
Duping with #2321, which is in a distant future to consider - future-2 milestone.
Sorry, no progress, according to that issue, it hasn't worked in 2.8, 3.3 and 3.4 with same error.
