### ISSUE TITLE
Can't create VS project from template with Nuget packages if "Save new projects when created" is false

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/Home#3843]
If a VS template installs NuGet packages using the method documented [here](https://docs.nuget.org/ndocs/visual-studio-extensibility/visual-studio-templates), and the user has the Visual Studio option "Save new projects when created" unchecked, then the new project can not be created. The below error message is shown.

![image](https://cloud.githubusercontent.com/assets/4837132/19895012/0745f98a-a047-11e6-86ab-49275b005f57.png)

At the point where the error message is shown, the user hasn't yet had the option to save the project, they are just creating it. Once the error message is shown, the resulting project is created, but without the package reference, leading to a broken project. After saving, on attempting to reach the "Manage Nuget packages" UI - the following error is thrown:

![image](https://cloud.githubusercontent.com/assets/4837132/19895168/a1713786-a047-11e6-8fab-26231ce9f55b.png)

Finally, if the user closes and reopens VS, and reloads the project, the NuGet UI can be accessed, but there is no reference to the package specified in the template, meaning a broken project.

This was originally reported as https://github.com/nunit/nunit-vs-templates/issues/21. Are we correct in thinking this is a NuGet issue, as NuGet appears to control both the templating, and package restore, or should this be redirected to the Visual Studio team?

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS

NuGet version (x.x.x.xxx): 3.5.0

VS version (if appropriate): VS 2015 Update 3

OS version (i.e. win10 v1607 (14393.321)): Win 10

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Install any project template using NuGet packages (e.g. [NUnit Templates](https://visualstudiogallery.msdn.microsoft.com/6cd55f79-4936-49e7-b81d-c40fcd81abc7)) and restart.

2. In VS, go to `Tools > Options > Projects and Solutions` and uncheck `Save new projects when created`.

3. In VS, go to `File > New > Project` and create a project from template which includes nuget packages (e.g. NUnit 3 Unit Test Project).

**Comment by jainaashish** [comment]
This is by design from NuGet perspective, you can check with Visual Studio team if they can update the template to fix it.
