### ISSUE TITLE
Fix Restore for Tools in VS

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3845]

**Comment by alpaix** [comment]
ETA 11/3 11am

**Comment by rrelyea** [comment]
Can you please add PR link?

**Comment by rrelyea** [comment]
Ready for shiproom yet? If not, eta? Please drive it home.

**Comment by rrelyea** [comment]
In NuGet 4.0.0.2050 build, which is in VS 25904.02 build.
