### ISSUE TITLE
Binding Redirect related E2E test failures on dev15

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#3847]
[nugetci](http://nugetci/viewLog.html?buildId=56497&tab=buildResultsDiv&buildTypeId=EndToEndTests_Vs15EndToEndTests)

**Comment by rrelyea** [comment]
Current status of E2E tests?

**Comment by mishra14** [comment]
Binding redirect tests are passing dev build 2045.

Possible fix: NuGet Settings -> Check Skip binding redirect -> save -> un check skip binding redirect -> save.

Could have been caused by a test run crashing or the default value not being read correctly. Closing.

**Comment by mishra14** [comment]
reopening, since this is inconsistent.

**Comment by mishra14** [comment]
Merged: https://github.com/NuGet/NuGet.Client/commit/2057ef8e5d9f9219d25d0fd2e29af36755556607
