### ISSUE TITLE
NuGet.BuildTasks handles projectFileDependencyGroups wrong

### ISSUE THREAD

**Issue by tmeschter** [NuGet/Home#3848]
In order to show the set of referenced packages in the Solution Explorer the build task digs through the items in the "projectFileDependencyGroups" section of the project.lock.json/project.assets.json file. Currently, we assume all of the packages we care about will be in the subsection denoted by the empty string, "". It turns out that this is not true. This subsection may not exist at all, and when it does it only holds the set of packages common to all targets. Target-specific packages will be in target-specific subsections.

There is currently a pull request out to fix this issue:
https://github.com/NuGet/NuGet.BuildTasks/pull/23

**Comment by jainaashish** [comment]
PR has already been merged.
