### ISSUE TITLE
NuGet.exe restore not honoring the -nocache flag

### ISSUE THREAD

**Issue by emanuelquintero** [NuGet/Home#3852]
## Details about Problem

NuGet product used: **NuGet.exe**
NuGet version (x.x.x.xxx): **3.5.0.1737**
OS version (i.e. win10 v1607 (14393.321)):  **Win10 v1607**
Worked before? If so, with which NuGet version: No, tried with NuGet 3.3 and NuGet 3.4.4

## Detailed repro steps so we can see the same problem

1. NuGet restore package X from -source A where it exists
2. NuGet restore package X from -source B where it *doesn't* exist and pass in -NoCache flag

Expected: I cannot restore package X on step 2
Actual: I *can* restore package X on step 2. You can see only -source B is used, but it is actually copying the package from the cache because you see no outgoing HTTP requests.

### Verbose Logs
Nothing interesting even with -verbosity detailed

Edit: Removed sample project section

**Comment by emgarten** [comment]
@emanuelquintero can you try with the latest version nuget here: https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe

**Comment by emanuelquintero** [comment]
@emgarten It still doesn't work with the latest version.

**Comment by jainaashish** [comment]
`-NoCache` will simply avoid http cache but if you already have the package in global packages folder then it will take it from there and not hit the http source.
