### ISSUE TITLE
"dotnet.exe restore" fails on Windows 10 x86 due to new use of ProgramFiles

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3853]
NuGet restore fails on Windows 10 x86

https://github.com/dotnet/cli/issues/4567

**Comment by rrelyea** [comment]
@emgarten is getting a 32 VM to validate. Thinks the programfilesx86 shouldn't be used on x86 system

**Comment by emgarten** [comment]
This is only a problem for the CLI where the netstandard dlls are used. VS uses the net45 dlls which resolve the program files path using Environment.GetFolderPath
