### ISSUE TITLE
Legacy csproj needs NugetTargetMoniker and RuntimeIdentifiers set in proj/targets

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3854]
UWP projects will need:
<NugetTargetMoniker>.NETCore,Version=v5.0</NugetTargetMoniker>
<RuntimeIdentifiers>win10-arm;win10-arm-aot;win10-x86;win10-x86-aot;win10-x64;win10-x64-aot</RuntimeIdentifiers>

Desktop projects will need:
<RuntimeIdentifiers>win</RuntimeIdentifiers>

We need to decide what can go in targets and what needs to be added via migration tool or user who manually migrates.

**Comment by rrelyea** [comment]
Can you please dupe this to the work that already happened here?

**Comment by rrelyea** [comment]
Confirmed with Ashish that this was done in RC3.

**Comment by JohnGalt1717** [comment]
Can someone tell me what I need to put in the .csproj for a multi targeted project for these two properties for .net 452 and a .net standard 1.3 library?

Thanks!
