### ISSUE TITLE
[Test Failure] Message is incorrect when you attempt to update package Newtonsoft.json with latest version installed in .Net Core Console App

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3856]
**Repro Steps:**
1.	Create a project through New Project->Visual C#->.NET Core->Console App (.NET Core).
2.	After project load completed, open PMC.
3.	Install package ‘Newtonsoft.json’ to the latest version.
4.	Type ‘Update-package Newtonsoft.json’ in PMC.

**Expected Result:**
PMC say “No package updates are available from the current package source for project [Project Name]”.

**Actual Result:**
PMC didn’t say “No package updates are available from the current package source for project [Project Name]” as below screenshot.
![pmcmessageincorrect](https://cloud.githubusercontent.com/assets/20632625/19923168/21917550-a121-11e6-9884-a00e02359645.png)
**Note:**
1.	It is found on D15Rel 25901.00 + NuGet 4.0.0-RC-2044.
2.	It repro on D15Rel 25901.00 (NuGet 4.0.0-RC-2039).
3.	It repro on D15Rel 25901.00 + NuGet 4.0.0-xprivate-2675. 
4. This issue start to happen from NuGet build 4.0.0-RC-2026.

**Comment by zhili1208** [comment]
I don't think this is an regression.
.net core project on dev14 has same behavior. 

For .net core project and UWP (project.json),
update-package always uninstall first and install again.
So on dev15, nuget still keeps this behavior, that's why there is no that message.

For .net framework project (packages.config)
update-package will show this message if the package is already latest

**Comment by zhili1208** [comment]
dev14+.net core output:
![core](https://cloud.githubusercontent.com/assets/7131513/19950216/561353d8-a113-11e6-9f4b-8a15adfe4e18.PNG)

dev14+uwp output:
![uwp](https://cloud.githubusercontent.com/assets/7131513/19950235/7186b394-a113-11e6-85dc-b08c0cb4e522.PNG)

dev15+.net core output:
![core15](https://cloud.githubusercontent.com/assets/7131513/19950460/eaaf4d8e-a114-11e6-95d9-fe612b2bb713.PNG)

dev15+uwp output:

![uwp15](https://cloud.githubusercontent.com/assets/7131513/19950476/f6e64fb2-a114-11e6-9a97-7faf0c17c2ce.PNG)

**Comment by zhili1208** [comment]
This is Rob on Zhi's machine -- assigning back to me for triage.

**Comment by v-luzh** [comment]
@rrelyea @zhili1208 This issue is fixed on D15Rel 26112.00 (NuGet Client 4.0.0-RC3-2206) as below screenshot. The messages are consistent.
![fixed](https://cloud.githubusercontent.com/assets/20632625/21923462/359fc198-d9af-11e6-8bb3-9efe802f5c50.PNG)

**Comment by v-luzh** [comment]
@rrelyea, this issue is fixed on VSUWPT 26509.00+NuGet Client 4.3.0.4052 according to our verification. Please help to close this bug, thanks.
