### ISSUE TITLE
How does one set up NuGet Development Environment for NuGet 3.0?

### ISSUE THREAD

**Issue by AndrewSav** [NuGet/Home#386]
The home page (https://github.com/NuGet/Home) links to this page http://docs.nuget.org/contribute in two places:

- Contribute to NuGet gives an overview of how you can contribute to teh various NuGet projects.
- Check out the contributing page to see the best places to log issues and start discussions.

On http://docs.nuget.org/contribute when you click on "Setting up the NuGet Development Environment" you get to this page: http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment

And here it reads:
> Clone the repository. From a command prompt, run the following command in a directory where you want the source code to be placed. This will create a folder named "nuget" with the source.

> git clone https://git01.codeplex.com/nuget

Naturally when one clones codeplex repository one gets 2.x version of the source code, not 3.0.

So, how does one set up NuGet Development Environment for Nuget 3.0?

**Comment by yishaigalatzer** [comment]
Updated the instructions and included a new build script
