### ISSUE TITLE
Remove dependency on ImportsAfter for CrossTargeting

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3860]
NuGet should pass it's targets using the custom after cross targeting property instead of depending on msbuild to contain it.

This needs to happen by RTM in coordination with msbuild. 

https://github.com/Microsoft/msbuild/blob/master/src/XMakeTasks/Microsoft.Common.CrossTargeting.targets#L116

**Comment by rainersigwald** [comment]
Once this is done we can remove the workaround in Microsoft/MSBuild#1061.

**Comment by emgarten** [comment]
It looks like the fix for this is to add an import of NuGet.target to
``$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.CrossTargeting.targets\ImportAfter\``

Using the custom after property doesn't work for ``msbuild.exe /t:Restore project.csproj`` since the Restore target doesn't exist yet to begin loading the Restore target for projects with cross compile enabled.

Does that sound correct to you @rainersigwald

**Comment by rainersigwald** [comment]
Yes, that sounds right @emgarten.

Are y'all planning to do this for RTW? I'd love to remove the fallback in MSBuild before RTW so no one accidentally depends on it, but I'm not sure it meets the current bar.

**Comment by emgarten** [comment]
@rainersigwald fixing this will involve adding a file in Microsoft.Common.CrossTargeting.targets to both desktop MSBuild and CLI. And then removing the property from NuGet I believe.

Do you think it is worth taking for RTW?

//cc @rrelyea

**Comment by rainersigwald** [comment]
Per the latest bug-bar guidance, I think it's not worth pursuing for RTW. I'd love to see it for vNext though . . .

**Comment by jainaashish** [comment]
Seems it doesn't apply now, so closing it
