### ISSUE TITLE
Warnings of multiple msbuild imports - 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3863]
Internal bug: 284327

D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets" cannot be imported again. It was already imported at "D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (22,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\school\OneAspNetTestSolutions\CreateCSharpEmptyNoAuth\CreateCSharpEmptyNoAuth\CreateCSharpEmptyNoAuth.csproj]

**Comment by rrelyea** [comment]
@zhili1208  - please check out the internal bug for additional repro info. this may be a dupe of the other issue on your plate now.

**Comment by zhili1208** [comment]
it doesn't not repro in visual studio 26109.02
