### ISSUE TITLE
Dependencies Tree is not loaded sometimes until after reopening a .NET Core web project

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3864]
Internal bug # 283934
1. Install d15prerel.25827.01
2. Create an ASP.NET Core Web Application (.NET Framework)
 
Result:
 Dependencies tree is not load until after reopening the project
(auto restore didn't run).

Does this still repro?

**Comment by rrelyea** [comment]
Everybody needs to look for a repro here.

**Comment by mishra14** [comment]
@rrelyea  still investigating on d15prerel/25827.1 or latest d15rel?

**Comment by jainaashish** [comment]
Tried 10-12 times with .net core console app, class library, or web app but not able to repro with latest dev build (2046).

**Comment by rrelyea** [comment]
fixed in RC.
