### ISSUE TITLE
Fail to update jQuery after install jQuery.Validation1.8 to FSharp project

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#387]
Repro step:
1. Create FSharp Console Application project
2. Install-Package jquery.validation -Version 1.8
3. Update-package jquery -version 2.0.3 

Expected: Update package jQuery successfully and jquery.validation was updated to 1.8.0.1

Actual: Update jQuery failed as below screenshot. 
LightSwitch project and MVC5Application have the similar issue. The different is to fail to install jQuery.Validation to these projects. Remember to uninstall jQuery first.
![errortoupdatejquery](https://cloud.githubusercontent.com/assets/11768961/7043232/a962880a-de1a-11e4-9318-066ce69a0289.PNG)

**Comment by danliu** [comment]
Verified using latest build that this does not repro anymore.
