### ISSUE TITLE
Create UWP app create project & rebuild total elapsed time regressions

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3873]
Internal bugs: 
create project - 286587 - 24% regression
rebuild - 286956 - 6% regression

**Comment by rrelyea** [comment]
once your other things are done, can you examine the current status of those perf regresssion.s

**Comment by jainaashish** [comment]
286956 is fixed and resolved.
286587 - CPU time regression is taken care of, need little more investigation for byteallocation

**Comment by jainaashish** [comment]
286587 - CPU regression and byteallocation both have been improved.
