### ISSUE TITLE
dotnet pack always seems to set ProjectReference version to 1.0.0

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3874]
## Steps

1. `dotnet new` to .csproj (projectA and projectB)
1. Set `<Version>2.0.0</Version>` in projectB
1. Add a `<ProjectReference>` between the (projectA -> projectB)
1. Restore both.
1. Build both.
1. `dotnet pack` projectA
1. Look at the output .nuspec.

## Expected

The version of the projectB dependency should be 2.0.0.

## Actual

The version of the projectB dependency seems to be a default 1.0.0.

`dotnet --info`
```
.NET Command Line Tools (1.0.0-preview3-004007)

Product Information:
 Version:            1.0.0-preview3-004007
 Commit SHA-1 hash:  80ec02b4da

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by rrelyea** [comment]
RC2 and release note.

**Comment by emgarten** [comment]
This is likely related to: https://github.com/NuGet/Home/issues/3748

**Comment by rrelyea** [comment]
Please confirm if nuget pack has the same problem, and if there is a workaround.

**Comment by joelverhagen** [comment]
## Workaround

Put this in the reference projects:

``` xml
<PackageVersion Condition="'$(PackageVersion)' == ''">$(Version)</PackageVersion>
```

**Comment by joelverhagen** [comment]
This has only been checked into dev (4.0.0-rc2). This should be closed when we cherry-pick to 4.0.0-rc branch.

**Comment by emgarten** [comment]
@joelverhagen can this be closed?

**Comment by joelverhagen** [comment]
@rrelyea, I guess it's safe to say we're not shipping this in RC right? 😄
