### ISSUE TITLE
external/sdk - MSBuild-based dotnet pack does not pack console app's runtimeconfig.json

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#3878]
Using the 1.0.0-preview3-004040 version of the CLI, if I have an application (targeting `netcoreapp1.0`) and I run `dotnet pack`, the runtimeconfig.json will not get packed with the app's DLL.

This is a regression from Preview 2 tooling which packed this file by default (it makes sense, since you have to have it to run the application). 

/cc @rohit21agrawal @joelverhagen

**Comment by rrelyea** [comment]
@rohit21agrawal says "i believe this is an msbuild problem. will follow up with that team." - now tracked here: https://github.com/dotnet/sdk/issues/472
