### ISSUE TITLE
hosted nuget.server tips 502 (not found)

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3879]
@ColinZeb wrote:  
#Custom Nuget.Server by hostself.
hostname:https://nuget.jingshonline.com/nuget
I'm using chinese language with vs 2015 up3.
error:
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	响应状态代码不指示成功: 502 (Not Found)。	0
![image](https://cloud.githubusercontent.com/assets/16807822/20017927/017dd2e6-a283-11e6-840a-99da24629cd6.png)

NOTE: on other solution it's works fine

**Comment by maliming** [comment]
+1s

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
