### ISSUE TITLE
dotnet pack is packing from obj not bin

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3880]
Found by cli team.

**Comment by joelverhagen** [comment]
This has only been checked into dev (4.0.0-rc2). This should be closed when we cherry-pick to 4.0.0-rc branch.

**Comment by rrelyea** [comment]
?

**Comment by joelverhagen** [comment]
Weird. Pushing to a fork should not cause this...

**Comment by drewgil** [comment]
What the actual? How does my pushing a commit to a fork have any impact on this issue (that I've never looked at)? GitHub fail?

**Comment by joelverhagen** [comment]
Hmmm come to think of it how would GitHub know the affinity between NuGet/Home and NuGet/NuGet.Client repositories? How would it know there is any different relationship with drewgil/NuGet.Client. I think this is not a bug.

**Comment by drewgillies** [comment]
Something is amiss. According to this I pushed a commit to my fork of another repo, a commit of code that I didn't write, and it somehow associated a close event with a bug to which I'm not assigned.
