### ISSUE TITLE
[Test Failure] The latest version of packages installed by default in PCL template show inconsistently between PMC and PM UI

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3882]
**NuGet version:** 4.0.0.2050
**VS version:** Dev15 D15Rel 25904.02
**OS version:** Windows 10 RS1_Release 14393.332

**Repro Steps:**
1. Create a Class Library (Portable) project, select 'Targets' as below screenshot.
![channge](https://user-images.githubusercontent.com/20632775/42991202-6fb8093c-8bf4-11e8-8e7e-fd84e95960fe.png)

2. Open NuGet Package Manager with project node and select Installed tab.
3. Open NuGet Package Console, input ‘**Get-Package -Updates**’ and then press Enter.

**Expected Result:**
The latest version of packages ‘**Microsoft.NETCore**’ and ‘**Microsoft.NET.Core.Protable.Compayibility**’ should show consistently between PMC and PM UI.

**Actual Result:**
The latest version of packages ‘Microsoft.NETCore’ and ‘Microsoft.NET.Core.Protable.Compayibility’ show **inconsistently** between PMC and PM UI as below screenshot.

![88888888888](https://cloud.githubusercontent.com/assets/20632775/20049613/214590ea-a4ff-11e6-9001-23f8846832d7.png)

**Notes:**
1.	The issue repro on D15Rel 25904.02+ NuGet Client 4.0.0-RC-2053.
2.	The issue not repro on Dev14 MU3.5 25431.01 + NuGet Client 3.4.4-1321.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by v-nancyj** [comment]
@jainaashish   I verified the issue on d15.8 27918.00 and d16.0stg 27919.3000, it still repro on current VS build, could you please help to have a look? Thanks!

**Comment by jainaashish** [comment]
@v-nancyj check your selected source in UI (it'd be nuget.org) where as PMC is running against all the sources which include offline source as well. So there is difference in sources between PMC and UI which is why you're seeing it.

Select `All` sources in UI, then you'll see the consistent behavior.
