### ISSUE TITLE
Test Discovery is not working with DPL mode

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#3885]
Internal issue# 287536

Test explorer calls into Nuget template api IVsPackageInstallerServices.GetInstalledPackages while solution is still being loaded with DPL. Hence NuGet doesn't have any context of projects under this solution and returns nothing from this api call.

**Comment by jainaashish** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/1006 and Verified

**Comment by rrelyea** [comment]
don't believe this shipped in 4.0 fixed. In fact, I think we won't have this fixed until 4.4 ships with full LSL (formerly DPL) support enabled in NuGet.
