### ISSUE TITLE
Add log for failed restore/update of package

### ISSUE THREAD

**Issue by neurospeech** [NuGet/Home#389]
Many times NuGet does not find latest version of package just uploaded, sometimes it takes upto 5 to 15 minutes for restore to be successful. Either nuget is searching for some cache and does not have proper cache invalidation or there is network issue. If there is log, it will be helpful to identify what went wrong.

Strange part is, I can login to nuget and manually download package without any problem through website.

**Comment by yishaigalatzer** [comment]
Thanks for reporting this issue. We are aware and we are tracking it through: https://github.com/NuGet/Home/issues/268
