### ISSUE TITLE
Client "spams" autocomplete endpoint of search service 

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3892]
The "autocomplete" endpoint of the search service gets many illegal requests. Examples:
```
https://api-v2v3search-1.nuget.org/autocomplete?q=~/&supportedFramework=netcoreapp1.0&take=100&prerelease=true
https://api-v2v3search-0.nuget.org/autocomplete?q=%5C&take=100 
https://api-v2v3search-1.nuget.org/autocomplete?q=Micro%5C&supportedFramework=netstandard1.6&take=100&prerelease=true
https://api-v2v3search-1.nuget.org/autocomplete?q=Microsoft.AspNetCore.Http.Extensions"1.&supportedFramework=net452&take=100&prerelease=true
https://api-v2v3search-1.nuget.org/autocomplete?q=}&take=100
https://api-v2v3search-1.nuget.org/autocomplete?q=-&supportedFramework=netcoreapp1.0&take=100&prerelease=true
https://api-v2v3search-1.nuget.org/autocomplete?q=:&supportedFramework=netcoreapp1.0&take=100&prerelease=true
https://api-v2v3search-0.nuget.org/autocomplete?q=C:&includePrerelease=false

```
Up until now, the search service used to fail on those requests and return a 500, since they contain unescaped invalid characters (such as \, -, }) but this was fixed here: https://github.com/NuGet/NuGetGallery/issues/3330

However, the client shouldn't send autocomplete requests that contain characters that are invalid and package ids, since the result will be empty, and it's an unnecessary load on the server. 
I tested VS 2015, project.json editing, and every string that is entered by the user, is sent as is to the autocomplete endpoint.

**Comment by emgarten** [comment]
> the client shouldn't send autocomplete requests that contain characters that are invalid and package ids, since the result will be empty, and it's an unnecessary load on the server

This sounds like a good idea for both the v2 and v3 autocomplete providers.

> I tested VS 2015, project.json editing, and every string that is entered by the user, is sent as is to the autocomplete endpoint.

The VS 2015 project.json editor is part of the web project system, not the NuGet VSIX. The server may need to handle this efficiently since there may not be a way to fix this down level.

> the search service used to fail on those requests and return a 500, since they contain unescaped invalid characters (such as , -, }) 

Escaping is already handled in the client:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/Resources/AutoCompleteResourceV3.cs#L44-L47

My guess is that queries with `&includePrerelease` are coming from NuGet, and queries with `&prerelease` are coming from the project.json editor.

**Comment by yishaigalatzer** [comment]
> > The VS 2015 project.json editor is part of the web project system, not the NuGet VSIX. The server may need to handle this efficiently since there may not be a way to fix this down level.
> 
> the search service used to fail on those requests and return a 500, since they contain unescaped invalid characters (such as , -, })

Please file a bug against the webtools team CC @toddgrun

**Comment by emgarten** [comment]
For reference the package id validation code is here:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Utility/PackageIdValidator.cs#L14-L16

**Comment by jainaashish** [comment]
Is this still relevant?
