### ISSUE TITLE
Default Copy of ContentFiles are incorrect for MsBuild /t:pack

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3894]
## Details about Problem

NuGet Pack Task

NuGet version (x.x.x.xxx): 4.0

VS version (if appropriate): VS 15

## Detailed repro steps so we can see the same problem

1. Create a .Net Core class library

2. Add a text file

3. Pack the project

Expected
ContentFile is packed to contentFiles/any/netstandard1.4

Actual
Copied to ContentFiles root

**Comment by rrelyea** [comment]
@emgarten  - thoughts on Hari's feedback here? is that what you'd expect?

**Comment by emgarten** [comment]
yes, ``contentFiles/any/{projectTFM}`` is probably the best default

**Comment by rohit21agrawal** [comment]
@emgarten so for a project with multiple TFM all files would go to each of those TFMs ?
