### ISSUE TITLE
Cannot change Content type when packing using NuGet Pack Task

### ISSUE THREAD

**Issue by harikmenon** [NuGet/Home#3895]
## Details about Problem

NuGet Pack Task

VS version (if appropriate): VS 15

## Detailed repro steps so we can see the same problem

1. Create a NET Core class library

2. Add a Text File

3. Pack

Expected
Content is added a Content to the NuSpec and restored as such

Actual
Content is always set as Compile

**Comment by rohit21agrawal** [comment]
@harikmenon @rrelyea it's not clear at all what the problem is here.
