### ISSUE TITLE
Relisting on NuGet.Server

### ISSUE THREAD

**Issue by herecydev** [NuGet/Home#3896]
I can issue a `nuget delete ...` to unlist a package on `Nuget.Server` (providing that the option is set in the config). How do I go about "relisting" that package, a simple `nuget push` get's a 500 response because the package already exists. Is there an API that this functionality is available from?

## Details about Problem

NuGet Version: 3.5.0.1938
NuGet.Server: 2.11.2

**Comment by yishaigalatzer** [comment]
CC @skofman1 (and should move to the gallery repo) 

Please provide an answer if it's supported and make sure it is documented. Otherwise please close and open a feature request on NuGet.Server in the galleryrepo

**Comment by jainaashish** [comment]
Not related to NuGet client, if this is still a relevant ask, then please open an issue for NuGet.Server
