### ISSUE TITLE
bad project.lock.json generated by nuget restore (works with dotnet restore)

### ISSUE THREAD

**Issue by tbolon** [NuGet/Home#3898]
## Environment

NuGet product used: nuget.exe & dotnet.exe

NuGet Version: 3.5.0.1938

dotnet.exe --version: 1.0.0-preview2-003131

OS version: 10.0.14393

## Repro steps

1. Create an empty project folder with a simple project.json with a reference to latest xUnit:

```
{
  "version": "1.0.0-*",
    "dependencies": {
    "xUnit": "2.2.0-beta2-build3300"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "portable-net45+win8" ]
    }
  }
}
```

2. Create a single c# class file to generate a library:

```
namespace MyLib {
    public class MyClass {
    }
}
```

3. restore using `dotnet restore`: success
4. build using `dotnet build`: success
5. backup project.lock.json using `move project.lock.json project.dotnet.lock.json`
6. run `nuget restore`: success
7. run `dotnet build`: error

```
Project MyLib (.NETCoreApp,Version=v1.0) will be compiled because inputs were modified
Compiling MyLib for .NETCoreApp,Version=v1.0
C:\Projets\Tests\Test\MyLib\project.json(4,36): error NU1001: The dependency xUnit >= 2.2.0-beta2-build3300 could not be resolved.

Compilation failed.
    0 Warning(s)
    1 Error(s)

Time elapsed 00:00:00.0135262
```
By quickly comparing both project.lock.json I see differences in term of casing.

Both files are included here.

[project.lock.json.zip](https://github.com/NuGet/Home/files/578941/project.lock.json.zip)

**Comment by yishaigalatzer** [comment]
CC @joelverhagen

**Comment by tbolon** [comment]
Do not hesitate to ask if you want help. It seems nuget now lowercase all dependencies in `project.lock.json`, certainly for xplat. Certainly the culprit of the problem, perhaps with the http requests and case sensitivity.

**Comment by yishaigalatzer** [comment]
This is an intentional direction we want to take, so package id case changes (that are out there quite a lot) are dealt with on Linux.

I \* think \* that Preview2 did not implement that support yet. Joel will know more, and he is looking into it and will get back to you

**Comment by tbolon** [comment]
For context, I encountered this problem when using continuous deployment on azure app services (kudu). By default it uses `nuget restore` against the .sln file, then uses msbuild (dotnet build) against the .sln.

I will try to ping @davidebbo to see if he has already seen this issue.

**Comment by yishaigalatzer** [comment]
yes, we have seen a similar issue on kudu, but it was resolved by updating one of the packages (the core issue there was in dotnet build not handling case sensitivity correctly, and they couldn't ship a fix)

CC @piotrpMSFT

**Comment by joelverhagen** [comment]
@tbolon, if you change your project.json to have `xunit` instead of `xUnit`, does it work? There is a problem in preview 2 `dotnet build` where mismatched package ID casing yields this same build error.

**Comment by joelverhagen** [comment]
Also note that the package author's intent for ID casing here is `xunit`. This is apparent in the .nuspec. Open the .nuspec from here and look for the `<id>` tag.

```
%userprofile%\.nuget\packages\xunit\2.2.0-beta2-build3300\xunit.nuspec
```

**Comment by tbolon** [comment]
You are right, that was the root cause. Even the [xunit documentation](https://xunit.github.io/docs/getting-started-dotnet-core.html#add-xunit-ref) is correct.

The problem was certainly due to the fact that intellisense in VS expose versions when you type "xUnit" as a package name in project.json, and everythings works fine on VS (I suppose they use dotnet restore).

![intellisense](https://cloud.githubusercontent.com/assets/127185/20168423/737fc996-a722-11e6-802f-33ff35e0d07d.png)

What is the final word about that: should `package.json` be case sensitive regarding package name or not ?

**Comment by joelverhagen** [comment]
Due the bug in `dotnet build`, users of `project.json` **and** preview 2 tooling should use the package author's intended package ID casing. Moving forward, however, users of UWP project.json and package references in .csproj (preview 3 / RTM tooling) should consider package IDs case insensitive.

**Comment by joelverhagen** [comment]
> The problem was certainly due to the fact that intellisense in VS expose versions when you type "xUnit" as a package name in project.json, and everythings works fine on VS (I suppose they use dotnet restore).

Yes, this makes sense since our autocomplete HTTP endpoint which provides this version list is case insensitive. I agree that it would be a better user experience for the editor to fix up IDs with the incorrect casing. However, given that this is preview 2 tooling and preview 3 is moving away from project.json, my guess is that this will not be fixed.

**Comment by tbolon** [comment]
yes, it makes sense.

the other difficulty is the fact that there are actually 2 implementations of nuget restore: one from dotnet, and the other from nuget itself. I have heard that in the end, dotnet restore will make use of nuget restore on background. I hope it will make the behavior more consistent.

you can close this issue.

**Comment by yishaigalatzer** [comment]
NuGet.exe and dotnet restore are using the same code for the scenario they both support. However they ship on different cadence, you could see variations in behavior in-between particularly at preview releases were the compat bar is pretty low on version to version changes
