### ISSUE TITLE
Trim whitespace from project properties in LegacyCSProj

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3900]
Properties in MSBuild project files may contain additional whitespace. This space is generally ignored in MSBuild and the project system should handle this also.

This issue tracks the Legacy CSProj project system work for the original issue:
https://github.com/NuGet/Home/issues/3819

**Comment by jainaashish** [comment]
This is not needed for legacy csproj project system since IVsBuildPropertyStorage takes care of it.
