### ISSUE TITLE
Correctly communicate PackageSpec.Version for any project dependencies (PackageRef xplat)

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3901]
The CPS project system should set the PackageSpec version for a project based on:

1. ``PackageVersion`` if it exists
1. ``Version`` if it exists
1. ``1.0.0`` otherwise

This matches the pack and NuGet.targets behavior for determining a package version.

The version string must be valid, otherwise this should fail with a helpful error.

Original issue:
https://github.com/NuGet/Home/issues/3748

**Comment by rrelyea** [comment]
Requires this and https://github.com/dotnet/roslyn-project-system/issues/1132 to fix.
