### ISSUE TITLE
Correctly communicate PackageSpec.Version for any project dependencies (PackageRef)

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3902]
The legacy CSProj project system should set the PackageSpec version for a project based on:

1. ``PackageVersion`` if it exists
1. ``Version`` if it exists
1. ``1.0.0`` otherwise

This matches the pack and NuGet.targets behavior for determining a package version.

The version string must be valid, otherwise this should fail with a helpful error.

Original issue:
https://github.com/NuGet/Home/issues/3748

**Comment by rrelyea** [comment]
Has been approved for a checkin to dev (but NOT release-4.0.0-rc3). Please merge when ready.
