### ISSUE TITLE
"Access denied" to rtf files caused by silent package install errors when Kaspersky antivirus is enabled

### ISSUE THREAD

**Issue by JasonHewison** [NuGet/Home#3907]
## Details about Problem

This issue is affecting multiple developers in the office when we try to create a new ASP.NET Dot Net Core sample project.

Disabling antivirus resolves the issue, but doesn't explain why extraction of the package fails silently or why when installing the affected packages directly fixes the problem for each individual package (with antivirus still enabled).

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI and Package Manager Console

NuGet version (x.x.x.xxx):  3.5.0.1484 and 3.5.0.1996 (beta)

dotnet.exe --version (if appropirate): 1.0.0-preview2-003131

VS version (if appropriate): Microsoft Visual Studio Enterprise 2015 / Version 14.0.25431.01 Update 3

OS version (i.e. win10 v1607 (14393.321)): Windows 7 Professional Service Pack 1

Worked before? If so, with which NuGet version: Installing NuGet works normally with packages for older versions of .NET

## Detailed repro steps so we can see the same problem
With Kaspersky Endpoint Security 10 for Windows enabled, do the following;
1. In Visual Studio 15 go to File -> New -> Project

2. In the New Project Modal, under Installed select Templates > Visual C# > .NET Core and then create a new ASP.NET Core Web Application (.NET core)

3. In the New ASP.NET Core Web Application (.NET Core) modal select Web Application (Host in the cloud should be unticked) and click OK.

4. The project will be created and after a NuGet finishes restoring the packages you will see "Package restore failed" in Solution Explorer, when you click output the last line will be "error: Access to the path '%NUGET_PACKAGES%\Microsoft.CodeAnalysis.CSharp\1.3.0\ThirdPartyNotices.rtf' is denied."
 - NUGET_PACKAGES by default will be C:\Users\#UserName#\.nuget\packages, but I've changed it to E:\Nuget\Packages to rule out that the folder was the issue.

5. If you go to the %NUGET_PACKAGES%\Microsoft.CodeAnalysis.CSharp\1.3.0 folder you will see that the ThirdPartyNotices.rtf file is not there, but the following are present.
<pre>
└─ lib
      └─ net45
            └─ Microsoft.CodeAnalysis.CSharp.dll
            └─ Microsoft.CodeAnalysis.CSharp.xml
      └─ netstandard1.3
            └─ Microsoft.CodeAnalysis.CSharp.dll
            └─ Microsoft.CodeAnalysis.CSharp.xml
      └─ portable-net45+win8
            └─ Microsoft.CodeAnalysis.CSharp.dll
            └─ Microsoft.CodeAnalysis.CSharp.xml
└─ Microsoft.CodeAnalysis.CSharp.nuspec
└─ tm13v3r0.310
</pre>

6. If in Package Manager Console you run dotnet restore you will receive a similar error for a different package.
- For me this was error: Access to the path 'E:\NuGet\packages\Microsoft.CodeAnalysis.Analyzers\1.1.0\ThirdPartyNotices.rtf' is denied.

7. If in package manager you manually install the problem package it will succeed, Running dotnet restore again will fail on a different package.
- For me this was error: Access to the path 'E:\NuGet\packages\Microsoft.CodeAnalysis.Common\1.3.0\ThirdPartyNotices.rtf' is denied.

## Other suggested things

Disabling the antivirus fixes the problem, however this does not explain why the installing of the package appears to succeed or why NuGet packages for older versions of DotNet/ASP.NET succeed.

### Verbose Logs
1. Logs from initial project creation;
<pre>
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "E:\playground\WebApplication2\.vs\restore.dg" -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"
log  : Restoring packages for E:\playground\WebApplication2\src\WebApplication2\project.json...
log  : Installing NuGet.Configuration 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.Types 3.5.0-beta2-1484.
log  : Installing NuGet.Repositories 3.5.0-beta2-1484.
log  : Installing NuGet.Protocol.Core.v3 3.5.0-beta2-1484.
log  : Installing NuGet.LibraryModel 3.5.0-beta2-1484.
log  : Installing NuGet.Packaging.Core.Types 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.DataProtection.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Cryptography.Internal 1.0.0.
log  : Installing Microsoft.DotNet.InternalAbstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.0.
log  : Installing System.Xml.XPath 4.0.1.
log  : Installing System.Net.WebSockets 4.0.0.
log  : Installing System.ComponentModel.Primitives 4.1.0.
log  : Installing System.Collections.Specialized 4.0.1.
log  : Installing System.Collections.NonGeneric 4.0.1.
log  : Installing NuGet.DependencyResolver.Core 3.5.0-beta2-1484.
log  : Installing Microsoft.NETCore.App 1.0.1.
log  : Installing Microsoft.AspNetCore.Diagnostics 1.0.0.
log  : Installing NuGet.Packaging.Core 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.Mvc 1.0.1.
log  : Installing Microsoft.AspNetCore.Razor.Tools 1.0.0-preview2-final.
log  : Installing Microsoft.AspNetCore.Routing 1.0.1.
log  : Installing Microsoft.AspNetCore.Server.IISIntegration 1.0.0.
log  : Installing Microsoft.AspNetCore.Server.Kestrel 1.0.1.
log  : Installing Microsoft.AspNetCore.StaticFiles 1.0.0.
log  : Installing Microsoft.Extensions.Configuration.EnvironmentVariables 1.0.0.
log  : Installing NuGet.Common 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.Configuration.Json 1.0.0.
log  : Installing Microsoft.Extensions.Logging 1.0.0.
log  : Installing Microsoft.Extensions.Logging.Debug 1.0.0.
log  : Installing Microsoft.Extensions.Logging.Console 1.0.0.
log  : Installing NuGet.RuntimeModel 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.Options.ConfigurationExtensions 1.0.0.
log  : Installing Microsoft.VisualStudio.Web.BrowserLink.Loader 14.0.0.
log  : Installing Libuv 1.9.0.
log  : Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
log  : Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
log  : Installing Microsoft.AspNetCore.DataProtection 1.0.0.
log  : Installing Microsoft.CSharp 4.0.1.
log  : Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
log  : Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.4.
log  : Installing Microsoft.VisualBasic 10.0.1.
log  : Installing NETStandard.Library 1.6.0.
log  : Installing System.Buffers 4.0.0.
log  : Installing System.Collections.Immutable 1.2.0.
log  : Installing System.ComponentModel 4.0.1.
log  : Installing System.ComponentModel.Annotations 4.1.0.
log  : Installing Microsoft.Extensions.Globalization.CultureInfoCache 1.0.0.
log  : Installing System.Diagnostics.DiagnosticSource 4.0.0.
log  : Installing System.Diagnostics.Process 4.1.0.
log  : Installing Microsoft.Extensions.Localization.Abstractions 1.0.0.
log  : Installing System.Dynamic.Runtime 4.0.11.
log  : Installing System.Globalization.Extensions 4.0.1.
log  : Installing Microsoft.Extensions.DependencyModel 1.0.0.
log  : Installing System.IO.FileSystem.Watcher 4.0.0.
log  : Installing System.IO.MemoryMappedFiles 4.0.0.
log  : Installing System.IO.UnmanagedMemoryStream 4.0.1.
log  : Installing System.Linq.Expressions 4.1.0.
log  : Installing System.Linq.Parallel 4.0.1.
log  : Installing System.Linq.Queryable 4.0.1.
log  : Installing System.Net.NameResolution 4.0.0.
log  : Installing System.Net.Requests 4.0.11.
log  : Installing System.Net.Security 4.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Abstractions 1.0.1.
log  : Installing System.Net.WebHeaderCollection 4.0.1.
log  : Installing System.Numerics.Vectors 4.1.1.
log  : Installing System.Reflection.DispatchProxy 4.0.1.
log  : Installing Microsoft.AspNetCore.Authorization 1.0.0.
log  : Installing System.Reflection.Metadata 1.3.0.
log  : Installing System.Reflection.TypeExtensions 4.1.0.
log  : Installing System.Resources.Reader 4.0.0.
log  : Installing System.Runtime.Loader 4.0.0.
log  : Installing System.Security.Cryptography.Algorithms 4.2.0.
log  : Installing System.Security.Cryptography.Encoding 4.0.0.
log  : Installing System.Security.Cryptography.Primitives 4.0.0.
log  : Installing System.Security.Cryptography.X509Certificates 4.1.0.
log  : Installing System.Diagnostics.Contracts 4.0.1.
log  : Installing System.Threading.Tasks.Dataflow 4.6.0.
log  : Installing System.Threading.Tasks.Extensions 4.0.0.
log  : Installing System.Threading.Tasks.Parallel 4.0.1.
log  : Installing System.Threading.Thread 4.0.0.
log  : Installing System.Threading.ThreadPool 4.0.10.
log  : Installing System.Diagnostics.StackTrace 4.0.1.
log  : Installing System.Reflection.Extensions 4.0.1.
log  : Installing runtime.native.System.IO.Compression 4.1.0.
log  : Installing Microsoft.NETCore.DotNetHost 1.0.1.
log  : Installing Microsoft.AspNetCore.Diagnostics.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Hosting.Abstractions 1.0.0.
log  : Installing Microsoft.AspNetCore.Http.Extensions 1.0.0.
log  : Installing Microsoft.AspNetCore.WebUtilities 1.0.0.
log  : Installing Microsoft.Extensions.FileProviders.Physical 1.0.0.
log  : Installing Microsoft.Extensions.Logging.Abstractions 1.0.0.
log  : Installing Microsoft.Extensions.Options 1.0.0.
log  : Installing System.Xml.XPath.XDocument 4.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.ApiExplorer 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.Cors 1.0.1.
log  : Installing System.Xml.XmlDocument 4.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.DataAnnotations 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.Formatters.Json 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.Localization 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.Razor 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.TagHelpers 1.0.1.
log  : Installing Microsoft.AspNetCore.Mvc.ViewFeatures 1.0.1.
log  : Installing System.Text.Encoding.CodePages 4.0.1.
log  : Installing Microsoft.Extensions.Caching.Memory 1.0.0.
log  : Installing Microsoft.Extensions.DependencyInjection 1.0.0.
log  : Installing System.Diagnostics.FileVersionInfo 4.0.0.
log  : Installing Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003121.
log  : Installing System.Runtime.Serialization.Primitives 4.1.1.
log  : Installing Microsoft.AspNetCore.Razor.Runtime 1.0.0.
log  : Installing Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003121.
log  : Installing Microsoft.Extensions.CommandLineUtils 1.0.0.
log  : Installing Microsoft.Extensions.PlatformAbstractions 1.0.0.
log  : Installing Newtonsoft.Json 9.0.1.
log  : Installing System.Collections 4.0.11.
log  : Installing System.Text.RegularExpressions 4.1.0.
log  : Installing Microsoft.AspNetCore.Routing.Abstractions 1.0.1.
log  : Installing Microsoft.Extensions.ObjectPool 1.0.0.
log  : Installing System.Security.Principal.Windows 4.0.0.
log  : Installing Microsoft.AspNetCore.Http 1.0.0.
log  : Installing Microsoft.AspNetCore.HttpOverrides 1.0.0.
log  : Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
log  : Installing System.Globalization 4.0.11.
log  : Installing System.Diagnostics.Debug 4.0.11.
log  : Installing System.IO 4.1.0.
log  : Installing System.Linq 4.1.0.
log  : Installing System.Net.Primitives 4.0.11.
log  : Installing Microsoft.AspNetCore.Http.Features 1.0.0.
log  : Installing System.Runtime.Extensions 4.1.0.
log  : Installing System.ComponentModel.TypeConverter 4.1.0.
log  : Installing System.Runtime.InteropServices 4.1.0.
log  : Installing System.Text.Encoding 4.0.11.
log  : Installing System.Threading 4.0.11.
log  : Installing System.Threading.Tasks 4.0.11.
log  : Installing System.Threading.Timer 4.0.1.
log  : Installing System.Runtime.InteropServices.RuntimeInformation 4.0.0.
log  : Installing NuGet.ProjectModel 3.5.0-beta2-1484.
log  : Installing Microsoft.AspNetCore.Hosting 1.0.0.
log  : Installing NuGet.Frameworks 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.FileProviders.Abstractions 1.0.0.
log  : Installing Microsoft.Extensions.WebEncoders 1.0.0.
log  : Installing Microsoft.Extensions.Configuration 1.0.0.
log  : Installing System.IO.FileSystem 4.0.1.
log  : Installing NuGet.Packaging 3.5.0-beta2-1484.
log  : Installing Microsoft.Extensions.Configuration.FileExtensions 1.0.0.
log  : Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0.
log  : Installing System.Console 4.0.0.
log  : Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0.
log  : Installing Microsoft.Extensions.Configuration.Binder 1.0.0.
log  : Installing Microsoft.Win32.Registry 4.0.0.
log  : Installing System.Net.Sockets 4.1.0.
log  : Installing Microsoft.AspNetCore.Http.Abstractions 1.0.0.
log  : Installing Microsoft.NETCore.Platforms 1.0.1.
log  : Installing Microsoft.CodeAnalysis.Common 1.3.0.
log  : Installing System.ObjectModel 4.0.12.
log  : Installing System.Reflection 4.1.0.
log  : Installing System.Reflection.Primitives 4.0.1.
log  : Installing System.Resources.ResourceManager 4.0.1.
log  : Installing System.Runtime 4.1.0.
log  : Installing Microsoft.NETCore.DotNetHostResolver 1.0.1.
log  : Installing NuGet.Versioning 3.5.0-beta2-1484.
log  : Installing Microsoft.NETCore.Jit 1.0.4.
log  : Installing Microsoft.NETCore.Windows.ApiSets 1.0.1.
log  : Installing Microsoft.Win32.Primitives 4.0.1.
log  : Installing System.AppContext 4.1.0.
log  : Installing System.Collections.Concurrent 4.0.12.
log  : Installing System.Diagnostics.Tools 4.0.1.
log  : Installing System.Diagnostics.Tracing 4.1.0.
log  : Installing Microsoft.AspNetCore.Razor 1.0.0.
log  : Installing System.Globalization.Calendars 4.0.1.
log  : Installing System.IO.Compression 4.1.0.
log  : Installing System.IO.Compression.ZipFile 4.0.1.
log  : Installing System.IO.FileSystem.Primitives 4.0.1.
log  : Installing System.Net.Http 4.1.0.
log  : Installing Microsoft.DotNet.ProjectModel 1.0.0-rc3-003121.
log  : Installing System.Runtime.Handles 4.0.1.
log  : Installing Microsoft.Extensions.Caching.Abstractions 1.0.0.
log  : Installing System.Runtime.Numerics 4.0.1.
log  : Installing System.Text.Encoding.Extensions 4.0.11.
log  : Installing System.Xml.ReaderWriter 4.0.11.
log  : Installing System.Xml.XDocument 4.0.11.
log  : Installing runtime.native.System 4.0.0.
log  : Installing System.Reflection.Emit 4.0.1.
log  : Installing System.Reflection.Emit.ILGeneration 4.0.1.
log  : Installing System.Threading.Overlapped 4.0.1.
log  : Installing System.Reflection.Emit.Lightweight 4.0.1.
log  : Installing runtime.native.System.Net.Security 4.0.1.
log  : Installing runtime.native.System.Security.Cryptography 4.0.0.
log  : Installing System.Security.Claims 4.0.1.
log  : Installing System.Security.Cryptography.OpenSsl 4.0.0.
log  : Installing System.Security.Principal 4.0.1.
log  : Installing runtime.native.System.Net.Http 4.0.1.
log  : Installing System.Security.Cryptography.Cng 4.2.0.
log  : Installing System.Security.Cryptography.Csp 4.0.0.
log  : Installing Microsoft.NETCore.Targets 1.0.1.
log  : Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.0.
log  : Installing Microsoft.Net.Http.Headers 1.0.0.
log  : Installing Microsoft.AspNetCore.Html.Abstractions 1.0.0.
log  : Installing Microsoft.Extensions.Primitives 1.0.0.
log  : Installing System.Text.Encodings.Web 4.0.0.
log  : Installing Microsoft.Extensions.FileSystemGlobbing 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Core 1.0.1.
log  : Installing Microsoft.AspNetCore.Cors 1.0.0.
log  : Installing Microsoft.Extensions.Localization 1.0.0.
log  : Installing Microsoft.AspNetCore.JsonPatch 1.0.0.
log  : Installing Microsoft.AspNetCore.Localization 1.0.0.
log  : Installing Microsoft.AspNetCore.Mvc.Razor.Host 1.0.1.
log  : Installing Microsoft.Extensions.FileProviders.Composite 1.0.0.
log  : Installing Microsoft.AspNetCore.Antiforgery 1.0.1.
error: Access to the path 'E:\NuGet\packages\Microsoft.CodeAnalysis.CSharp\1.3.0\ThirdPartyNotices.rtf' is denied.
</pre>

2. Logs from dotnet restore in package manager
<pre>
PM> dotnet --verbose restore -v detailed
Telemetry is: Disabled
log  : Restoring packages for E:\playground\WebApplication2\src\WebApplication2\project.json...
log  : Installing Microsoft.CodeAnalysis.Analyzers 1.1.0.
log  : Installing Microsoft.CodeAnalysis.Common 1.3.0.
log  : Installing Microsoft.CodeAnalysis.VisualBasic 1.3.0.
log  : Installing Microsoft.CodeAnalysis.CSharp 1.3.0.
error: Access to the path 'E:\NuGet\packages\Microsoft.CodeAnalysis.Analyzers\1.1.0\ThirdPartyNotices.rtf' is denied.
</pre>

### Sample Project

Very helpful if you can zip a project and paste into this issue!
- I don't think this will help because creating a new project from scratch causes the problem and the missing files are outside the project folder.

**Comment by jainaashish** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
