### ISSUE TITLE
package update in 3.x is extremely slow in comparison to 2.x

### ISSUE THREAD

**Issue by vasiliy-popov-db** [NuGet/Home#3908]
A month ago my team started using Visual Studio 2015 (Enterprise) instead of Visual Studio 2012.
_Note_. All the described actions below are full reproducible on any workstation in my team.

Usually we use Package Manager Console to update our projects.
In VS 2015 Package Manager Console Host Version is 3.4.4.1321

For comparison I tried to use Package Manager Console Host Version 3.5.0.1996 from nuget beta gallery. 

Package Manager Console Host Version 2.8.60318.667 in Visual Studio 2012.

Resharper is suspened in both Studios by the following commands:
$dte.ExecuteCommand("ReSharper_Suspend");
Update-Package ...
Update-Package ...
Update-Package ...
...
Update-Package ...
$dte.ExecuteCommand("ReSharper_Resume");

OS version is Windows 7 Enterprise + SP1.

So, in VS 2015 nuget works much slower than in VS 2012.
Here are my results for the same actions.
1. Solution file with just one assembly, the assembly has a lot of dependencies - 100.
Let's try to execute update command for an library which has been already update.

a.	it takes 1 min 44 secs in 3.5-beta

PM> Update-Package MyNamespace.Library -Version 1.0.0; 
Attempting to gather dependency information for multiple packages with respect to project 'MyNamespace.Integration', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 12,17 sec
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages **The slowest step**
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'MyNamespace.Integration'.
Time Elapsed: 00:01:44.8483005

b.	it takes 1 sec in 2.8

PM> Update-Package MyNamespace.Library -Version 1.0.0; 
No updates available for 'MyNamespace.Library' in project 'MyNamespace.Integration'.

c.     it takes 1 sec in 3.5-beta if you add -IgnoreDependencies flag

PM> Update-Package MyNamespace.Library -Version 1.0.0 -IgnoreDependencies
Attempting to gather dependency information for multiple packages with respect to project 'MyNamespace.Integration', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 487,91 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'MyNamespace.Integration'.
Time Elapsed: 00:00:01.4520004

2. Solution file with just one assembly, the assembly has a lot of dependencies - 100.
Let's try to execute 10 update commands for different libraries. Some of them are updated, some not.
a.	it takes 45 secs in 3.5-beta with IgnoreDependencies
b.	it takes ~1 minute in 3.4 with IgnoreDependencies
c.	it takes ~18 minutes in 3.5-beta without IgnoreDependencies
d.	it takes 45 secs in 2.8 without IgnoreDependencies

I think the main problem in the number of packages (100) and in the dependencies between them.
For example,
If I try to update a package 'LEVEL0' which does not depend on any other library the update takes about 10 seconds in 3.5-beta in our solution.
If I remove all entries from packages.config except <package id="LEVEL0" version="1.0.0" targetFramework="net40" /> it takes less than 1 sec.
If I try to update a package 'LEVEL1' which depends on 'LEVEL0' then it takes about 20-30 secs.
In my first point above I tried to update some kind of LEVEL4 library. It took 1:45.
During the update CPU is fully loaded and procmon.exe show thousands operations like ReadFile, CloseFile, etc. for all installed packages in "packages" folder

So, at the moment we have to use VS 2012 with nuget 2.8
We try to add -IgnoreDependencies when it is possible.
We left only one required nuget gallery in settings.

**Comment by yishaigalatzer** [comment]
Can you please try using 3.5-RTM as well? If you still see a major difference in your scenario, please help us with a repro, and we will love to push for further improvements in this area.

**Comment by vasiliy-popov-db** [comment]
I used 3.5.0.1996 (https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix) 
So it was latest version.

Also tried to use command-line tool to update a single package (in fact, it has latest version already)

3.5.0

> nuget.exe myproject.sln -Id MyNamespace.Library
> Scanning for projects...
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Found 1 project with a packages.config file. (myproject.csproj)
> Feeds used:
>   http://xx.yy.com/api/v2

Attempting to gather dependency information for multiple packages with respect to project 'c:\Projects\myproject\myproject.csproj', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took **14,26 sec**
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
Executing nuget actions took 2,05 ms

In 3.4.4, 3.3.0, 3.2.0 it takes 18 seconds.
In 2.8.6, 2.8.5 it takes less than 1 second.

**Comment by yishaigalatzer** [comment]
Thanks, so now we need more details about your project and packages perhaps if possible a repro.

You can use support@nuget.org to communicate if the data is proprietary.

**Comment by vasiliy-popov-db** [comment]
After some investigations I found that the update works much faster if I just copy all nuget packages from our nuget server into a local folder. But it is not an enterprise solution to me.

Can't share my project but I've tried to create a small example of my thoughts.
Here is in attached file you will find Integration solution which can be used for comparison.

There are a few libraries in "Libraries" folder with a lot of dependencies between them.
It can be changed in Libraries.sln

All the libraries were published as nuget packages into "LibrariesGallery" folder.

The two solutions were created for repro
1. SimpleIntegration.sln
    Contains single project with "Level0" library as a dependency.
2. IntegrationWithMultiDependantLibraries.sln
    Contains single project with dependencies to all libraries from "LibrariesGallery".

Update package command works fine in both nuget.exe versions (2.8.6 and 3.5.0) when you use local folder for nuget gallery.
But if you move "LibrariesGallery" to a shared folder or publish to your network nuget server
and then if you run all command files (.cmd) you will see the big difference between 2.8.6 (00:00:05,30) and 3.5.0 (00:00:17,13)

[PerfTest_with_Binaries.zip](https://github.com/NuGet/Home/files/585810/PerfTest_with_Binaries.zip)
pass: 123
Please let me know if I should share a zip without binaries.

**Comment by yishaigalatzer** [comment]
First - thanks a lot! This is a great effort. A few more things before jumping on the retry
1. Is your local server a folder ? Are you familiar with using nuget.exe init command?
2. We have a newer version with more update improvements in the pipe 4.0-rc, it is currently only available on myget https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.CommandLine

**Comment by vasiliy-popov-db** [comment]
![hotspots](https://cloud.githubusercontent.com/assets/23354894/20220057/1c502d16-a83d-11e6-9106-00a5ecf8e6df.png)
![mainthread](https://cloud.githubusercontent.com/assets/23354894/20220059/1c85447e-a83d-11e6-824d-4e99f360a753.png)
![thread 28](https://cloud.githubusercontent.com/assets/23354894/20220058/1c7e98d6-a83d-11e6-9231-d445aaaa47cc.png)
1. We use nuget server which is located in a different city. I can't just push a lot of test libraries into it. So I provided an example with shared folder in a different city.
   I am not familiar with nuget.exe init
2. Same result

> C:\Projects\Sandbox\PerfTest>nuget_4.0.0.exe update IntegrationForLibraries\IntegrationForLibraries.csproj -Id Level0 -Source LibrariesGallery
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
> Feeds used:
>   C:\Projects\Sandbox\PerfTest\LibrariesGallery
> Attempting to gather dependency information for multiple packages with respect to project 'C:\Projects\Sandbox\PerfTest\IntegrationForLibraries\IntegrationForLi
> braries.csproj', targeting '.NETFramework,Version=v4.0'
> Gathering dependency information took 334,74 ms
> Attempting to resolve dependencies for multiple packages.
> Resolving dependency information took 0 ms
> Resolving actions install multiple packages
> Resolution was successful but resulted in no action
> There are no new updates available.
> No package updates are available from the current package source for project 'C:\Projects\Sandbox\PerfTest\IntegrationForLibraries\IntegrationForLibraries.cspro
> j'.
> Executing nuget actions took 3,19 ms
> 00:00:02,86
> C:\Projects\Sandbox\PerfTest>update_Level0_with_nuget_4.0.0_shared_folder_in_IntegrationForLibraries.cmd
> C:\Projects\Sandbox\PerfTest>set STARTTIME=18:42:23,69
> C:\Projects\Sandbox\PerfTest>nuget_4.0.0.exe update IntegrationForLibraries\IntegrationForLibraries.csproj -Id Level0 -Source \network_workstation\LibrariesGallery
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
> Feeds used:
>   \network_workstation\LibrariesGallery
> Attempting to gather dependency information for multiple packages with respect to project 'C:\Projects\Sandbox\PerfTest\IntegrationForLibraries\IntegrationForLi
> braries.csproj', targeting '.NETFramework,Version=v4.0'
> Gathering dependency information took 16,86 sec
> Attempting to resolve dependencies for multiple packages.
> Resolving dependency information took 0 ms
> Resolving actions install multiple packages
> Resolution was successful but resulted in no action
> There are no new updates available.
> No package updates are available from the current package source for project 'C:\Projects\Sandbox\PerfTest\IntegrationForLibraries\IntegrationForLibraries.cspro
> j'.
> Executing nuget actions took 3,54 ms
> 00:00:18,04

Also I tried to profile nuget.exe with JetBrains dotTrace. See my attachements.
I see a lot of calls during getting dependencies.
May be we need to cache something or to use HashSet instead of IEnumerable for list of packages in NugetPackageManager.CollectDependencies method.

Looks like we iterate here too many times to find a package by its id (why not hashset?)
`
var packageIdentity = packages.FirstOrDefault(p => p.Id.Equals(id, StringComparison.OrdinalIgnoreCase));
`

Same in the line
`
var sourceDepInfo = available.SingleOrDefault(p => packageIdentity.Equals(p));
`

**Comment by vasiliy-popov-db** [comment]
New fact:
I tried to create two different local folders
1. FullClone of our Nuget Server - 40000 .nupkg files
2. SmallClone - just 1000 versions of MyLibrary.dll

> .nuget\nuget update MyProject\MyProject.csproj -Id MyLibrary -Version 1.0.0 -Source c:\Nuget\FullClone
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Feeds used:
>   c:\Nuget\FullClone
> Attempting to gather dependency information for multiple packages with respect to project 'MyProject\MyProject.csproj', targeting '.NETFramework,Version=v4.0'
> Gathering dependency information took 39,61 sec
> Attempting to resolve dependencies for multiple packages.
> Resolving dependency information took 0 ms
> Resolving actions install multiple packages
> Resolution was successful but resulted in no action
> There are no new updates available.
> Executing nuget actions took 2,82 ms
> 
> .nuget\nuget update MyProject\MyProject.csproj -Id MyLibrary -Version 1.0.0 -Source c:\Nuget\SmallClone
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
> Feeds used:
>   c:\Nuget\SmallClone
> Attempting to gather dependency information for multiple packages with respect to project 'MyProject\MyProject.csproj', targeting '.NETFramework,Version=v4.0'
> Gathering dependency information took 986,21 ms
> Attempting to resolve dependencies for multiple packages.
> Resolving dependency information took 0 ms
> Resolving actions install multiple packages
> Resolution was successful but resulted in no action
> There are no new updates available.
> Executing nuget actions took 2,65 ms

It seems nuget.exe tries to read info for all packages from the source and it takes ~1 second for each 1000 .nupkg files

**Comment by yishaigalatzer** [comment]
Yup, here are two related blogs that can help you understand and optimize

http://blog.nuget.org/20160113/Accelerate-your-NuGet.Server.html

http://blog.nuget.org/20150922/Accelerate-Package-Source.html

**Comment by vasiliy-popov-db** [comment]
Thanks for the links, I can optimize local or shared folder with them but I used them just for investigation.
In real life http version is used on 2-year old web server which can't be easily upgraded in a big company.
So the main concern is about performance regression in 3.x version in comparison to 2.x

Also tried to add local cache into package source. And I am wondered why the client connects to http source even when local cache contains required package version.
