### ISSUE TITLE
NuGet.PackageManagement.VisualStudio.dll is forcing projects to calculate all capabilities during project startup

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#391]
Visual Studio has introduced a new mechanism to determine a project's capabilities without forcing the project to calculate them up-front. In previous versions, extensions could query the project's capabilities via the VSHPROPID_ProjectCapabilities property on the project's hierarchy, however, this has been replaced by using ```__VSHPROPID8.VSHPROPID_ProjectCapabilitiesChecker``` and casting the returned result to ```IVsBooleanSymbolPresenceChecker```, followed by a call to ```IsSymbolPresent```. Alternatively, if you have a reference to ```Microsoft.VisualStudio.Shell.14.0.dll```, you can use the ```IsCapabilityMatch``` extension method on hierarchy itself which does this for you.

NuGet itself is currently using the [old mechanism](https://github.com/NuGet/NuGet.VisualStudioExtension/blob/8455e9b0a48a8a6017515ea5b67c2010a6c42749/src/PackageManagement.VisualStudio/Utility/EnvDTEProjectUtility.cs#L1031)

__Why is this problematic?__

In UAP, Portable, Phone and Windows Store projects loading specific capabilities require resolving assemblies on disk (which underneath kicks off an MSBuild build). This is extremely problematic during project startup and is currently blocking from moving UAP/Portable to build against framework NuGet packages (if you would like more information on why this is the case, please send me an email).

We would like to see NuGet move to the new mechanism to avoid correctness and performance reasons. In the RTM timeframe, we will likely reject attempts to get the full list of capabilities before the project has fully initialized.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.VisualStudio@a559f4dba2a605e82edffa039d183ae97a4f9687

NuGet now uses IsCapabilityMatch instead of the older capability check.
