### ISSUE TITLE
Nugetizer should use a different name for its .targets file

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3910]
@kzu The nugetizer project helpfully creates and imports a .targets file when creating a new package project to allow for customizations in the packaging process. By default this file is called ProjectName.targets where ProjectName is also the default name of the package being produced. Unfortunately, this conflicts with the .props and .targets name that nuget looks for when building a native package (i.e. the .target/.props in /build/native). In order to not conflict with this convention if the consumer wants to include custom .props and .targets in a package, I propose changing the nugetizer generated .targets to ProjectName.Packaging.Targets

**Comment by kzu** [comment]
Yep, we have since removed it from the default template.
