### ISSUE TITLE
I'm using Packages.Config and feel that it is a MESS and has several major issues.

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#3912]
This entire system needs redesigning, I've submitted a few issues recently and they're unresponded to.  The entire system is fragile, surely someone needs to see the elephant in the room - the design is fundamentally flawed.

**Comment by rrelyea** [comment]
Do you mean the issues you filed in Feb? Perhaps you can link to which issues are affecting you.
Sorry if we haven't been as responsive as you have hoped, we are working hard to become more responsive to the issues.

**Comment by The-Futurist** [comment]
I posted some issues out of frustration more recently (3811 and 3648). I guess I'm just at the stage where NuGet's numerous handicaps cannot be overlooked much longer. At a fundamental level the architecture is flawed, it is easy for the various data structures (files/folders) upon which NuGet relies to become mutually inconsistent and this then leads to bewildering problems that require trawling through the internet in an attempt to unravel.

The system is fragile and has poor user interface, it should simply never allow some of the many frustrating scenarios to arise. All we're talking about here is references to assemblies, that's all this is about and I'm sorry but NuGet has become a monster, it's time for a clean fresh approach to this whole problem.

**Comment by rrelyea** [comment]
Yes, we are working on fresh approaches compared to the packages.config technique. Replied a bit to #3811 with some details of our direction.

**Comment by jainaashish** [comment]
Agree there were some fundamental design issues with packages.config which we've tried to overcome in PackageReference world. Please start using PackageReference, and let us know if it covers most of your concerns with packages.config. We might not be able to get every design issue fixed with packages.config but will try and make PackageReference works in all cases.
