### ISSUE TITLE
Missing migrations for pack-related properties

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3914]
I was going through project.json [docs](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json) and found a few properties that we are not yet migrating, according to tests. Amongst these are:

- {root}.authors
- {root}.shared
- {root}.sharedExclude
- {root}.sharedFiles

From design notes for migration I see these are all associated with the `pack` verb. Are we intentionally skipping migration for these? If not, do we know where they should migrate to in a csproj file?

/CC @joelverhagen @emgarten @rrelyea @livarcocc @blackdwarf

**Comment by joelverhagen** [comment]
`{root}.authors` maps to the `<Authors>` MSBuild property. I will investigate the other three as I am not familiar with them.

**Comment by emgarten** [comment]
ContentFiles is the replacement for shared files.

**Comment by TheRealPiotrP** [comment]
how about shared and shared exclude? Ideally, can you show a PJ example and how you want it to look in csproj, exercising all three properties?

**Comment by TheRealPiotrP** [comment]
👀

**Comment by joelverhagen** [comment]
Did some digging through preview2 CLI code and it looks like `shared`, `sharedExclude`, and `sharedFiles` all work hand-in-hand. `shared` is an include globbing pattern. `sharedExclude` is an exclude globbing pattern. `sharedFiles` is an explicit list of file paths (no patterns).

This is what the input JSON and migrated XML would look like:

``` json
{
  ...
  "shared": [
    "foo/**/*"
  ],
  "sharedExclude": [
    "foo/bar/**/*"
  ],
  "sharedFiles": [
    "D.cs"
  ],
  ...
}
```

``` xml
    <Content Include="foo\**\*;D.cs" Exclude="foo\bar\**\*">
      <PackagePath>contentFiles\any\any</PackagePath>
    </Content>
```

Note that we have a bug right now in this area: https://github.com/NuGet/Home/issues/3954.

**Comment by rohit21agrawal** [comment]
@piotrpMSFT if @joelverhagen answer satisfies your needs, please close this bug.

**Comment by TheRealPiotrP** [comment]
yes, thanks!
