### ISSUE TITLE
"packages" property in global.json not respected by 1.0.0-preview1-002702 tooling

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3915]
Moving from https://github.com/dotnet/cli/issues/3288 on behalf of @dneimke.

-----

## Steps to reproduce

Add the following configuration to global.json

`{
  "projects": [ "src", "test" ],
  "packages": "dotnet_packages",
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}`

Restore packages
## Expected  behavior

Packages should restore to the specified path (dotnet_packages) in the root folder of the solution 
## Actual behavior

Packages are restored to %userprofile%.nuget\packages
## Environment data

`dotnet --info` output:

`Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64`

**Comment by jainaashish** [comment]
`global.json` is no more a supported scenario.

**Comment by HenrikSommer-Energinet** [comment]
Best way to solve a problem is no longer support the feature.
