### ISSUE TITLE
dotnet pack produces a zip with no read-permissions on its file contents

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#3916]
Move of dotnet/cli#2175. 

--------------------------------

## Steps to reproduce

`dotnet new` then `dotnet restore` then `dotnet build` then `dotnet pack`

Go into the `bin/Debug` directory and `unzip Project.1.0.0.nupkg`

Try to view the contents of the nuspec: `more Project.nuspec`
## Expected  behavior

It should show me the contents of the file
## Actual behavior

It says `Project.nuspec: Permission denied`
## Rationale

I'm working on OSX. I need a way to inspect the contents of the nupkg that has been generated. Currently, the permission bits of the nuspec inside the nupkg zip file are "------". I have to do `chmod +rw Project.nuspec` to make the file readable. It's pretty unconventional to have to do this. You should create a zip which has the correct permissions from the get-go.
## Environment data

`dotnet --version` output: 1.0.0-beta-002133 on OSX

/cc @joelverhagen @rohit21agrawal @rrelyea

**Comment by rrelyea** [comment]
Please consider importance / timeframe.

**Comment by rohit21agrawal** [comment]
@rrelyea 
This problem exists on all OS, not just Mac.

There doesn't seem to be  an API provided System.IO.Compression that allows to set access permissions on a zip archive entry.

That being said, I don't think that there is any real user scenario where we need to set file permissions on the nuspec file inside the nupkg. If someone really wanted to do that, they have all the tools to do that themselves (chmod) .

My recommendation is we move this to Future-2.

**Comment by rrelyea** [comment]
consider post 4.0.0

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.

**Comment by brazilbean** [comment]
This is a problem for me too.
