### ISSUE TITLE
Perf: CLI extremely high memory usage and CPU load during restore all packages for corefx

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#3917]
## Steps to reproduce
 * Clone `corefx` repo and follow instructions to build. E.g. commit 4e961640ab618297326575bb70722760115e61d0
 * Run `build.cmd` in git powershell window on Windows 10.
 * Wait until all packages are restored.

## Expected  behavior
 * Restore should be fast, very little cpu usage and low memory usage.

## Actual behavior
 * Memory usage and CPU is extremely high for a long time...

![image](https://cloud.githubusercontent.com/assets/10798831/20171231/03c9c602-a730-11e6-9516-af157fb16753.png)

## Environment data
This uses `build.cmd` in corefx which downloads its own version of CLI tools as far as I understand, so see the given commit.

Moving this here from https://github.com/dotnet/cli/issues/4676

**Comment by nietras** [comment]
Thanks for moving it.

**Comment by emgarten** [comment]
Where version of NuGet is this using?

**Comment by nietras** [comment]
This is the properties of the `NuGet.Client.dll` found in `Tools` under the `corefx` repo after running `build.cmd`, so 3.6.0-rc-1987.

![image](https://cloud.githubusercontent.com/assets/10798831/20213078/fd034122-a806-11e6-9fbc-22722f8a96eb.png)

**Comment by emgarten** [comment]
3.6.0-rc-1987 should have the latest perf fixes. I'm not sure why it says 2016-09-11 there, that build was created on 2016-10-17

**Comment by nietras** [comment]
I don't know either, you should be able to reproduce this quite easily with the steps I have given, though. Otherwise, let me know how I can help. If time I could try profiling NuGet while this happens e.g. with perfview, xperf or similar.

**Comment by jainaashish** [comment]
We had made lot of perf fixes post 3.6.0 until 4.4.0 please try the latest one and let us know how it works now.
