### ISSUE TITLE
Add UI for packaging mode

### ISSUE THREAD

**Issue by drewgillies** [NuGet/Home#3921]
UI needs to be added to allow user to choose between packages.config/project.json and package references. 
Spec here: https://github.com/NuGet/Home/wiki/Supporting-Package-Reference-in-UWP-WPF-WinForms-and-Classic-Libraries

**Comment by jainaashish** [comment]
Still keeping it open for another part of the problem where we need to complete this feature end to end. We just checked in the UX resources so that localization team can pick these up.
