### ISSUE TITLE
UWP TargetPlatformVersion support

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3923]
Add support for reading the min UWP target framework version from Legacy CSProj projects.

This is needed both for command line restore with MSBuild and the Legacy CSProj project system in the VSIX.

**Comment by rrelyea** [comment]
@harikmenon said:
I have speced the behavior out here:
https://github.com/NuGet/Home/wiki/Converting-Extension-SDKs-into-NuGet-Packages
We should not worry about Min version and only worry about TargetPlatformVersion. For Min, we will document a workaround either using _._ semantics or custom tasks.
