### ISSUE TITLE
Null reference exception appears in output window creating asp.net core web application

### ISSUE THREAD

**Issue by BillHiebert** [NuGet/Home#3925]
1. Run Visual Studio 2017 RC
2. Create ASP.NET core web application
3. The Build output window contains the following:

Error occurred while restoring NuGet packages: Object reference not set to an instance of an object.

Here's the callstack
`> NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.EmitRestoreTelemetryEvent.AnonymousMethod__21_0(NuGet.ProjectManagement.NuGetProject project) Unknown
  System.Core.dll!System.Linq.EnumerableSorter<NuGet.ProjectManagement.NuGetProject, string>.ComputeKeys(NuGet.ProjectManagement.NuGetProject[] elements, int count) Unknown
  System.Core.dll!System.Linq.EnumerableSorter<NuGet.ProjectManagement.NuGetProject>.Sort(NuGet.ProjectManagement.NuGetProject[] elements, int count) Unknown
  System.Core.dll!System.Linq.OrderedEnumerable<NuGet.ProjectManagement.NuGetProject>.GetEnumerator() Unknown
  System.Core.dll!System.Linq.Enumerable.WhereSelectEnumerableIterator<NuGet.ProjectManagement.NuGetProject, string>.MoveNext() Unknown
  System.Core.dll!System.Linq.Buffer<string>.Buffer(System.Collections.Generic.IEnumerable<string> source) Unknown
  System.Core.dll!System.Linq.Enumerable.ToArray<string>(System.Collections.Generic.IEnumerable<string> source) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.EmitRestoreTelemetryEvent(System.Collections.Generic.IEnumerable<NuGet.ProjectManagement.NuGetProject> projects, NuGet.PackageManagement.UI.RestoreOperationSource source, System.DateTimeOffset startTime, NuGet.PackageManagement.UI.NuGetOperationStatus status, int packageCount, double duration) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.RestoreAsync(bool forceRestore, NuGet.PackageManagement.UI.RestoreOperationSource restoreSource, System.Threading.CancellationToken token) Unknown
  mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<RestoreAsync>d__20>(ref NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<RestoreAsync>d__20 stateMachine) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.RestoreAsync(bool forceRestore, NuGet.PackageManagement.UI.RestoreOperationSource restoreSource, System.Threading.CancellationToken token) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.ExecuteAsync(NuGet.PackageManagement.VisualStudio.SolutionRestoreRequest request, NuGet.PackageManagement.VisualStudio.SolutionRestoreJobContext jobContext, System.Threading.CancellationToken token) Unknown
  mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.Start<NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<ExecuteAsync>d__19>(ref NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.<ExecuteAsync>d__19 stateMachine) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreJob.ExecuteAsync(NuGet.PackageManagement.VisualStudio.SolutionRestoreRequest request, NuGet.PackageManagement.VisualStudio.SolutionRestoreJobContext jobContext, System.Threading.CancellationToken token) Unknown
  NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.SolutionRestoreWorker.StartRestoreJobAsync(NuGet.PackageManagement.VisualStudio.SolutionRestoreRequest jobArgs, bool blockingUi, System.Threading.CancellationToken token) Unknown
`

**Comment by jainaashish** [comment]
Fixed with latest Visual Studio 15.4
