### ISSUE TITLE
Pack should exclude items from targets/props files coming from packages

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3927]
Pack should exclude content items and other items declared in props/targets coming from dependency packages.

Currently this can be done by setting ``ExcludeRestorePackageImports=true``

### Steps

1. Install a package that contains a targets/props file with content items
1. Pack the project

### Expected

Content items from the package will not be included

### Actual

Content items from the package are included

**Comment by aL3891** [comment]
I open an issue for this, #4013 but I figured i'd add a note here as well, is it really necessary to also set this to true when doing a restore as well? doing that blocks a really interesting scenario for me :)

**Comment by rrelyea** [comment]
please investigate, and let's have an impact/timeframe discussion.

**Comment by dasMulli** [comment]
Note that having props/targets that contribute build logic might be vital for `pack` to work as expected.
First example would be packages that contain logic to calculate assembly & package version like GitVersion (though this currently does not work for package references).
Other uses would be code and content generation logic.

**Comment by rohit21agrawal** [comment]
@dasMulli calculating package version happens in the outer build, and this change wouldn't impact that. if you have a scenario that you are afraid might break, i'd really appreciate if you could test out some private bits. if you can, let me know and i will share them with you.

also tagging @AArnott @onovotny in case they are interested to try it out before i check this in.

**Comment by AArnott** [comment]
Thanks. I am concerned both with the goal and how it is implemented. Both concerns are on the PR.

**Comment by emgarten** [comment]
Closing based on the PR feedback.
