### ISSUE TITLE
Write NuGet tool version and restore type to generated props

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3928]
It is difficult to author packages that work across both packages.config and PackageReference projects. To help make this easier NuGet could write out a few extra pieces of metadata to the generated msbuild props file.

This could include

* The project type as NuGet sees it, example: PackageReference, UWP project.json,  this would allow build targets/props in a package to know that this is not a packages.config project.
* NuGet tool version, this could be used to detect older clients and add assets through targets/props for down level compatibility

**Comment by rrelyea** [comment]
$(NuGetProjectStyle) wiith the possible values:
PackagesConfig
ProjectJson
PackageReference
