### ISSUE TITLE
dotnet pack with --version-suffix option replaces dependency *'s

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3936]
Moved from https://github.com/dotnet/cli/issues/4030 on behalf of @deathrowe.

This bug is a bit nuanced. Apparently PJ pack injected a provided --version-suffix both for P2P's and for external packages. Opening here to make sure we don't have the same behavior in preview3+. Thanks, @piloi, for pointing out the nuance.

----

## Steps to reproduce

`dotnet pack  --version-suffix 15`
`"version": "2.0.0-*"
## Expected  behavior

the version of my nuget package will be changed to 2.0.0-15
## Actual behavior

the version of my nuget package is changed to 2.0.0-15 but any dependencies I have using the latest versioning (x.x.x-*) are also changed to version 15.

project.json
`"dependencies": { "my.dependency.name": "1.0.0-*"}`

.nuspec file

```
<dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="my.dependency.name" version="[1.0.0-15, )" />
      </group>
</dependencies>
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003223)

Product Information:
 Version:            1.0.0-preview3-003223
 Commit SHA-1 hash:  9d3b727392

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64
```

Also reproducible on Windows with same version

**Comment by rohit21agrawal** [comment]
we don't do this in dotnet.exe pack right now.
