### ISSUE TITLE
dotnet pack doesn't include files

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3937]
Moved from https://github.com/dotnet/cli/issues/4021 on behalf of @MCKRUZ.

## Steps to reproduce

Create a .net solution that has a readme.md file at the base, then create a project.json file like so

```
                "files": {
                    "includeFiles": ["readme.md"],
                    "mappings": {
                        "readme.md": "readme.md"
                    }
                }
```
## Expected  behavior

Readme.md will be inside the installed project
## Actual behavior

readme.md is NOT inside the installed project
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64

**Comment by rohit21agrawal** [comment]
Closing this as this definitely works with CSPROJ.

Include the readme.md as content in your csproj, and by default it will be packed into the content folder.
