### ISSUE TITLE
Throw error when trying to create a non prerelease package with prerelease dependencies

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3938]
Moved from https://github.com/dotnet/cli/issues/3844 on behalf of @niemyjski.

----

You can have a package (1.0.0) that depends on any prerelease package and it will create the 
package but you are unable to install it unless you specify a -pre flag.... This is a bug that just bit us.

**Comment by enricosada** [comment]
@piotrpMSFT you cannot neither `dotnet pack` a not prerelease (like `1.0.0`) with deps prerelease (like `0.3-preview2`), ref https://github.com/NuGet/Home/issues/1365
That's a behavior change respect preview2 and is painful ( f# fsharp.core IS prerelease, but lots of others packages too)

**Comment by niemyjski** [comment]
Yes, it's really painful and caused us and our end users much pain. I hope this gets resolved sooner and later just for the sake of the community.

**Comment by rohit21agrawal** [comment]
@rrelyea should we remove this restriction?

**Comment by rrelyea** [comment]
I'd want to consult with @yishaigalatzer -- who was involved in some long discussions.

**Comment by rohit21agrawal** [comment]
@rrelyea maybe until then, we start work on an opt-out flag to unblock some of the users?

**Comment by rrelyea** [comment]
let's get one plan, and then do that. an opt-out flag may be the technique, but let's focus on other things until we can get a cohesive plan.

**Comment by enricosada** [comment]
some ideas:

- read an env var `NUGET_SUPPRESS_ERR_1234` so is temporary and is an opt-out flag without cli/api changes.
- downgrade error as warning

I can send a PR if you choose how you want to resolve this issue

**Comment by rohit21agrawal** [comment]
we decided to downgrade this error as warning. have a pr out with this change
