### ISSUE TITLE
Add ability to specify NuGet package ID other than the project name

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#3939]
Moved from https://github.com/dotnet/cli/issues/3782 on behalf of @tsvetomir.

I believe this capability exists in `dotnet pack` with `csproj` but couldn't find a doc that specifies the property to set.

------

Currently the `name` setting is used as:
- Default namespace. [Not overridable](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile/CompilerUtil.cs#L146).
- NuGet Package ID. [Not overridable](https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-pack/PackageGenerator.cs#L384).
- Assembly name. Overridable through `buildOptions.outputName`

Suppose we want to give the NuGet package a user-friendly ID. Currently this is not possible.
It would be great if it can be overriden in packOptions:

```
"name": "My.Project",
packOptions: {
  "id": "My.Lovely.Project"
}
```

**Comment by emgarten** [comment]
@tsvetomir project.json no longer exists for .NETCore projects. In the new csproj use the `<PackageId>` property to change the package name.

https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

**Comment by rohit21agrawal** [comment]
@tsvetomir @piotrpMSFT this is how you override each of the properties you are looking for:

Default Namespace: $(RootNamespace)
AssemblyName : $(AssemblyName)
NuGet PackageId  : $(PackageId)

Closing this bug , but feel free to re-open if this doesn't answer your questions.

**Comment by mwpowellhtx** [comment]
Having the same issue. I have tried `<PackageId/>`, `<AssemblyTitle/>`, `<AssemblyName/>`, to no avail. Seems pretty firmly rooted in the project meta data. How do we get unstuck from that? Also some of the links above are obsolete, i.e. OP _"not overridable"_, as supporting claims.
