### ISSUE TITLE
[NuGet.VisualStudioExtension] Errorlist still shows error after a successful package restore

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#394]
It might be an issue not related to NuGet, but logging the bug so that the incorrect behavior can be tracked.

Repro steps:
1. create a new project
2. delete the packages folder
3. configure the package source to be one that does not contain the missing packages
4. build solution
5. configure the package source to add the feed that contains the missing packages
6. build again

Expected: build works fine, there are no errors shown on the list afterwards

Actual: build works, packages restored correctly, but there are still errors shown on the list

**Comment by zhili1208** [comment]
Tested this with nuget build 198 and latest D14rel VS, this issue didn't repro
