### ISSUE TITLE
[Test Failure] switching between 2 packages, the version in right pane doesn't change

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3941]
**Repro Steps:**
1.	New an F# Console Application template. 
2.	Open ‘Manage NuGet Packages…’ and click ‘Browse’ tab.
3.	Search package ‘FSharp’ in the filter.
4.	Click package **‘FSharp.Compiler.Tools’**, you can see the latest version is 4.0.1.20.
5.	Click package **‘FSharp.Core’** and then click package **‘FSharp.Compiler.Tools’** again.

**Expected Result:**
The latest version show correctly (4.0.1.20) as step4. 

**Actual Result:**
The latest version show incorrectly (4.0.0.1), actually it is the package FSharp.Core’s. Please see below screenshot.
![fsharpcompilertools](https://cloud.githubusercontent.com/assets/20632625/20260347/2ead992c-aa94-11e6-86e1-56fc2cb8a3df.png)

**Note:**
1.	It found on D15PreRel 25913.00 + NuGet Client 4.0.0-RC2-2079.
2.	It repro on D15PreRel 25913.00 (NuGet Client 4.0.0-RC-2065).
3.	It **doesn’t repro** on Dev14 MU3.5 25431.01 (NuGet 3.4.4.1321).
4.	It repro on Dev14 MU3.5 25431.01+ NuGet 3.5.0-RTM-1938.
5.	It repro on Dev14 MU3.5 25431.01+ NuGet 3.6.0-Beta1-1954.

**Comment by rrelyea** [comment]
Yes, repros on 3.5.0 rtm. Not sure why this happens for those specific packages.

**Comment by v-luzh** [comment]
Just repro after switching from package ‘FSharp.Core’. Doesn't repro after switching from other packages.

**Comment by v-luzh** [comment]
This issue is fixed on D15Rel 26424.02 (NuGet Client 4.2.0-RTM-2457) and D15PreRel 26426.04 + NuGet Client 4.3.0-Preview1-2524.
