### ISSUE TITLE
Discover msbuild project files from a folder in nuget.exe restore

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3942]
nuget.exe only discovers solution files and packages.config files from a folder. ``dotnet restore`` is able to discover both solution files and project files from a folder.

We should consider supporting project file discovery from folders.

### Steps

1. Create a .NETCore project
1. cd to the project folder
1. Run ``nuget.exe restore``

### Expected
The csproj should be restored

### Actual
nuget.exe only works on single solution files and packages.config files.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
