### ISSUE TITLE
Nuget restore when building a single project restores for all projects in in the solution

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3944]
Ideally it would only restore for this project and any dependent projects.

**Comment by rrelyea** [comment]
Can you please describe which version of VS/NuGet and what type of project you are seeing this with?

**Comment by bbowman** [comment]
Sorry about that.

I'm using VS2015, Nuget Package Manager version 3.5.0.1996, and a .vcxproj with a project.json.

The behavior I am seeing is that on a right click rebuild for that project, it is restoring for projects that aren't dependencies of the rebuilt project as well. Its not a huge deal and I'm guessing that the move to msbuild references will make the restore happen how I suggest naturally?

**Comment by rrelyea** [comment]
Yes, you are correct. This is an optimization that would be good for us to consider.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
