### ISSUE TITLE
dotnet restore doesnt support anymore the `-f` argument

### ISSUE THREAD

**Issue by enricosada** [NuGet/Home#3949]
The sdk `preview2` support `-f` in `dotnet restore` command. The `preview3` does not.

That was really useful for:

- local workflow, instead of define a feed, just point to a directory with new package version
- build script, easy to script for test packages, etc

What's the replacement, if avaiable?

## Details about Problem

NuGet product used: 
`dotnet.exe` ( `dotnet restore`)

dotnet.exe --version (if appropirate): 
`1.0.0-preview3`

Worked before? If so, with which NuGet version: 
worked ok in `1.0.0-preview2`

## Detailed repro steps so we can see the same problem

1. `dotnet restore -f`
2. error: `-f` unsupported

**Comment by jainaashish** [comment]
Works with latest dotnet.
