### ISSUE TITLE
Auto-Restore in legacy CSProj

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3950]
Implement auto-restore on project open and project reference change events.

**Comment by jainaashish** [comment]
Need to discuss with @Pilchie and the team to take this further and decide what should be the right approach here? We did some similar stuff for UWP where we provided a nominate api which just take a project name and run the restore whenever they need to... we can have the similar strategy for csproj.dll as well.

**Comment by rrelyea** [comment]
Let's call this done. We have a nominate() API which is callable from any project system.
So .NET Core kicks off autorestore and has to pass all the project info.
Other project systems can call Nominate() if it makes sense.
