### ISSUE TITLE
Move third party server tests to a new entry point

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#3952]
Third party restore tests were relying on the xplat restore entry point which no longer exists now that dotnet restore calls MSBuild.

These tests should be migrated to use a different entry point: https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Core.FuncTests/NuGet.XPlat.FuncTest/XPlatRestoreTests.cs#L14

**Comment by jainaashish** [comment]
We'll take care of this as part of clean-up drive for end to end as well as func tests
