### ISSUE TITLE
dotnet pack fails to add content files included with a pattern

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3954]
## Steps

1. `dotnet new` a .csproj
1. Add another .cs file to your project.
1. Add ```<Content Include="**\*.cs><PackagePath>contentFiles\any\any</PackagePath></Content>```
1. Pack

## Expected

All of the matches .cs files should be packed.

## Actual

Only the first is packed:

```
C:\Users\jver\.nuget\packages\nuget.build.tasks.pack\4.0.0-rc-2048\build\NuGet.Build.Tasks.Pack.targets(73,5): warning : File 'D:\trash\2016-11-15\sharedthingcsproj\foo\B.cs' is not added because the package already contains file 'contentFiles\any\any' [D:\trash\2016-11-15\sharedthingcsproj\sharedthingcsproj.csproj]
C:\Users\jver\.nuget\packages\nuget.build.tasks.pack\4.0.0-rc-2048\build\NuGet.Build.Tasks.Pack.targets(73,5): warning : File 'D:\trash\2016-11-15\sharedthingcsproj\D.cs' is not added because the package already contains file 'contentFiles\any\any' [D:\trash\2016-11-15\sharedthingcsproj\sharedthingcsproj.csproj]
```

**Comment by rohit21agrawal** [comment]
@joelverhagen this is happening because your PackagePath should end with a 

> '\\'

 otherwise it thinks its the full path, including the filename.

**Comment by rrelyea** [comment]
consider documenting the fact that the trailing slash is requried.

**Comment by rohit21agrawal** [comment]
It's already documented in the spec

**Comment by rrelyea** [comment]
consistent with nuget pack today. (including project.json packing). so we'll close by design.
rohit opened a separate doc issue to sync the spec info with the public docs.
