### ISSUE TITLE
Nugetizer doesn't detect package is installed for win32 .vcxproj 

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3956]
@kzu Please see attached zip of project that has a packaging project and a ConsoleApp using a packages.config to depend on Nuget Packaging. The _NoIsPackableProject is still getting tripped even though it explicitly imports the .props and .targets so it should have them. Is there something weird with reading project metadata for older .vcxproj types?
[ConsoleApplication8.zip](https://github.com/NuGet/Home/files/593809/ConsoleApplication8.zip)

**Comment by jainaashish** [comment]
@kzu please take care of this, if this isn't an issue anymore then please close this.
