### ISSUE TITLE
Can't install native package with project.json

### ISSUE THREAD

**Issue by dhcarmona** [NuGet/Home#3958]
## Details about Problem
Visual Studio 2015 update 3
NuGet v. 3.4.4

Building a native unmanaged C++ project, I'm trying to consume Crypto++ via[ the available NuGet package](https://www.nuget.org/packages/cryptopp/). I added the dependency in project.json, but nuget restore fails with the following:

Errors in c:\dev\win\win\apps\project\project.json
    Package cryptopp 5.6.3.4 is not compatible with native (native,Version=v0.0). Package cryptopp 5.6.3.4 supports: native (native,Version=v0.0)
    One or more packages are incompatible with native,Version=v0.0.
    Package cryptopp 5.6.3.4 is not compatible with native (native,Version=v0.0) / win. Package cryptopp 5.6.3.4 supports: native (native,Version=v0.0)
    One or more packages are incompatible with native,Version=v0.0 (win).

I'm aware that project.json is not aimed at native unmanaged projects, but I need to use it in order to support wildcard versions to simulate snapshot dependencies during development.

## project.json

{
  "dependencies": {
    "cryptopp":"5.6.3.4"
  },
  "frameworks": {
    "native": {}
  },
  "runtimes": {
    "win": {},
  }
}

**Comment by dhcarmona** [comment]
I just tried this with a more recent build:
4.0.0-rc2-2086

No luck, it shows the same issue.

**Comment by jogerh** [comment]
Is there any documentation on how to use project.json with native nuget packages in a native project?

**Comment by jainaashish** [comment]
Please move to latest Visual Studio 2017 which uses `PackageReference` which has fixed this issue. There won't be any development for project.json
