### ISSUE TITLE
Nuget solution restore has different behavior in UI vs commandline for .vcxproj with project.json

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3960]
Using command line client version 3.5.0.1938 and package manager version 3.5.0.1996, I see that with the UI, a .vcxproj with a project.json file produces:

Package restore completed successfully for 'hmapmaker'.
Writing lock file to disk. Path: Y:\Arcadia\WinObjC\WinObjC.Build\vsimporter\hmapmaker\project.lock.json
Generating MSBuild file hmapmaker.nuget.targets.
Generating MSBuild file hmapmaker.nuget.props.

which works and injects the .props and .targets sucessfully.

In the command line output, however, I see:
Writing lock file to disk. Path: Y:\Arcadia\WinObjC\WinObjC.Build\vsimporter\hmapmaker\project.lock.json

only.

It appears that on the command line, it is treating the project as only a stand-alone project.json and not as "part" of the project.

**Comment by jainaashish** [comment]
Please use latest Visual Studio 2017 which uses `PackageReference` which works across VS, dotnet.exe, or msbuild
