### ISSUE TITLE
Nuget restore in 4.0.0.2087 fails when 3.5.x succeeded

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#3961]
I have a project.json with .nuproj file that lists the following:

{
  "dependencies": {
    "GitInfo": "1.1.32",
    "NuGet.Build.Packaging": "0.1.163-pr61"
  },
  "frameworks": {
    "NuGet,Version=v1.0": {
      "imports": [
        "dotnet",
        "netstandard1.0",
        "netstandard1.1",
        "netstandard1.2",
        "netstandard1.3",
        "netstandard1.4",
        "netstandard1.5",
        "netstandard1.6",
        "net20",
        "net35",
        "net40",
        "native",
        "monoandroid",
        "xamarinios10"
      ]
    }
  }
}

Restore in 4.0.0.2087 fails with "Invalid restore input. Invalid target framework 'unsupported'. Input files: Y:\Arcadia\WinObjC\WinObjC.Build\WinObjC.Build\WinObjC.Build.nuproj, Y:\Arcadia\WinObjC\WinObjC.Build\WinObjC.Build\project.json."

**Comment by kzu** [comment]
Won't support project.json anymore. PackageReference will be the mechanism.
