### ISSUE TITLE
http://nuget.org/nuget.exe is version 2.8.6

### ISSUE THREAD

**Issue by ctaggart** [NuGet/Home#3962]
Why is http://nuget.org/nuget.exe still at version 2.8.6?

This leads to this issue:
```
The 'System.Interactive.Async 3.0.0' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60717.93'.
```

Naturally, I just changed my build script to do:
```
curl -sLO http://nuget.org/nuget.exe
mono nuget.exe update -self

Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 2.8.6.
Updating NuGet.exe to 3.4.4-rtm-final.
```

I noticed the documentation says:

https://docs.nuget.org/ndocs/guides/install-nuget#nuget-cli

> NuGet 2.x users
Because there are a few breaking changes introduced in NuGet 3.2, https://nuget.org/nuget.exe points to the latest stable NuGet 2.x release to prevent CI systems from potentially breaking at this time.

I was expecting it to be the latest stable version. Can you make it so and remove those notice?

**Comment by jainaashish** [comment]
Please go to https://www.nuget.org/downloads and pick the right link to download latest stable releases.
