### ISSUE TITLE
Feature request: Non-transitive package dependencies?

### ISSUE THREAD

**Issue by ig-sinicyn** [NuGet/Home#3964]
VS2015 upd3, nuget 3.5 (latest one), .net4.6 framework project.

**Use case:**
I have a `package X` depending on third-party `package Y`. By default (Visual Studio 2015 Upd3 + nuget 3.5) any project referencing to `package X` will be updated with reference to `package Y` too. The issue is, customers of `X` do not need reference to `Y` at all, as API of `package Y` is not and should not be exposed to customers. There should be a way to mark such dependencies.

**Expected implementation of the feature:**
1. X.nuspec, the `Package Y` is included as
```xml
   <dependency id="PackageY" version="1.2.3" private=true />
 ```
   (`private` is just a placeholder, have no idea for better name).

 2. In customer project: after adding reference to `package X`, content of `package Y` should be copied into output folder on build, but `package Y` should not be added into project references.

**Possible workarounds:**
Theoretically we can include sources of the infrastructure `package Y` into our `project X` (in our case both projects are opensource under MIT license) but I'd prefer to use more or less standard approach.

**Why we need it:**
* The case we're investigating right now: we have a nuget package with test helper that ensures that PDB files matches to the sources (references `Microsoft.DiaSymReader` package). We do not want all our test projects to reference `Microsoft.DiaSymReader` assembly.

* More or less theoretical one (not an issue for now but will be a problem if the project will be pushed into production): custom script engine that uses Roslyn to compile and run the scripts. We do not want references to the Roslyn assemblies in all projects that will use our script engine. 

Latter case is much worse as we cannot merge roslyn sources into our project, obviously, and cannot distribute roslyn binaries as a part of our package, too.

**Real-world example:**
There's a package with exactly same issue: `Benchmark.Net`.
Create a new project targeting .net 4.6+, add a reference to `Benchmark.Net` aand:

![references](https://cloud.githubusercontent.com/assets/11225241/20378633/6392d51a-aca8-11e6-83b0-580aa68b89bf.png)

Also [asked on stackoverflow](http://stackoverflow.com/questions/40616611).

**Comment by davidfowl** [comment]
This is supported in `project.json` which is becoming the new package reference node in csproj. Packages can also express this today with include/exclude flags on dependency nodes. This wiki article describes those features https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets. 

The reason it's so granular is because you want transitivity for runtime, but not compilation. You get that full expressiveness with these flags. 

Unfortunately, this doesn't work with the way `packages.config` does things...

**Comment by ig-sinicyn** [comment]
@davidfowl Great news to hear!

> Packages can also express this today with include/exclude flags on dependency nodes

The https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets
states that the following is supported:

``` xml
<dependencies>
  <group>
    <dependency id="packageB" version="1.0.0" include="all" />
  </group>
</dependencies>
```

but [official docs](https://docs.nuget.org/ndocs/schema/nuspec#dependencies) has no mention of `include` / `exclude` and do not clarify meaning of include flags. Is it supported by current VS nuget package manager?

If yes: what flag should be used for my use case?

``` xml
   <dependency id="PackageY" version="1.2.3" exclude="compile" />
```

, right?

**Comment by ig-sinicyn** [comment]
**UPD**: Looks like duplicate to #3052 

I'm still interested in getting an answer though : )

**Comment by davidfowl** [comment]
> If yes: what flag should be used for my use case?

Yes.

/cc @emgarten You guys should update the official docs

**Comment by emgarten** [comment]
The docs for this are being tracked here https://github.com/NuGet/Home/issues/4551
