### ISSUE TITLE
[Test Failure] Package install/update/uninstall should be disabled during debugging the project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3965]
**Repro Steps:**
1.	New a C# Blank Application (Universal Windows) template.
2.	Open ‘Manage NuGet Packages for Solution’ and PMC.
3.	Select ‘Debug x86’ in project config.
4.	Set a breakpoint and press F5.
5.	Try to install/update/uninstall a package (such as newtonsoft.json) through PM UI or PMC.

**Expected Result:**
Package installing/updating/uninstalling should be disabled during debugging the project.

**Actual Result:**
Package installing/updating/uninstalling can be done during debugging the project.
![installsucceedduringdebugging](https://cloud.githubusercontent.com/assets/20632625/20382895/b716029e-ace8-11e6-9385-cbd673c767ee.PNG)

**Note:**
1.	It found on D15PreRel 25916.00 (NuGet Client 4.0.0-RC2-2079). 
2.	It repro on D15PreRel 25916.00 + NuGet Client 4.0.0-RC2-2088.
3.	It repro on Dev14 MU3.5 25431.01 (NuGet 3.4.4.1321).
4.	It repro on Dev14 MU3.5 25431.01+ NuGet 3.5.0-RTM-1938.
5.	It repro on Dev14 MU3.5 25431.01+ NuGet 3.6.0-Beta1-1954.

**Comment by rrelyea** [comment]
Please describe the bad effect of the current behavior. When somebody adds a new package reference during debugging, does debugging work badly? Does the package get added badly?

**Comment by v-luzh** [comment]
@rrelyea, we worried about there would be some conflicts when updating a package during debugging, which would made the code can't be used anymore. For example, graphics debugging features are all disabled during F5 in VS. So base on that we suggest to make our feature disabled during F5 to avoid some conflicts.

**Comment by jainaashish** [comment]
Check with latest build and let us know the current behavior

**Comment by v-luzh** [comment]
@jainaashish, it also repro on D15Rel 27130.00 (NuGet Client 4.5.0.4685). You can install/update/uninstall package during debugging now. It is just a suggestion bug, no bad effect until now.
