### ISSUE TITLE
$version$ is not $version$ when using nuget.exe pack *.csproj

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#3968]
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: 3.4.4, 3.5, 4.0 RC

Worked before? If so, with which NuGet version: 2.8.6 for sure, haven't tried 3.2/3.3.

## Expected output

A NuGet package with a version number `1.0.0-ci-12345` -and- a dependency on `Logging.Contracts` with version `1.0.0-ci-12345`.

## Actual output

A NuGet package with a version number `1.0.0-ci-12345` -and- a dependency on `Logging.Contracts` with version `2.0.0`. (which seems to correspond to the assembly info version for some reason - so in fact the first $version$ is different from the second $version$)

## Detailed repro steps so we can see the same problem

1. Create a .csproj library
2. Populate assemblyinfo with a version number "2.0.0.0"
3. Run nuget.exe spec
4. Edit the .nuspec file:

```xml
<?xml version="1.0"?>
<package >
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>Test</title>
    <authors>Test</authors>
    <owners>Test</owners>
    <description>Test package</description>
    <copyright>Copyright 2016 Test</copyright>
    <tags>tag goes here</tags>
    <dependencies>
        <dependency id="Logging.Contracts" version="$version$" />
    </dependencies>
  </metadata>
</package>
```

5. Run nuget.exe pack <path to csproj> -version 1.0.0-ci-12345

**Comment by joelverhagen** [comment]
For step 5 in the repro, are you packing the .csproj or the .nuspec? Either way, I am seeing consistent behavior across the different versions.

nuget.exe version | pack .csproj | pack .nuspec
--------------------|--------------|----------------
2.8.6                      | 2.0.0.0         | 1.0.0-ci-12345
3.2.0                      | 2.0.0.0         | 1.0.0-ci-12345
3.3.0                      | 2.0.0.0         | 1.0.0-ci-12345
3.4.3                      | 2.0.0            | 1.0.0-ci-12345
3.5.0                      | 2.0.0            | 1.0.0-ci-12345

**Comment by maartenba** [comment]
Packing the .csproj. The version is correct for the package itself, but the version in dependencies is set to the assembly version instead of the command-line parameter. Try the PR's unit test with and without the fix :)

**Comment by maartenba** [comment]
Or if you prefer a repro using the command-line, see attached (check build.bat / run build.bat and check the resulting .nupkg files)

Seems this has been faulty for quite a while. 

[ClassLibrary1.zip](https://github.com/NuGet/Home/files/606141/ClassLibrary1.zip)

**Comment by maartenba** [comment]
Any news on this? Have a customer who is blocked by this...

**Comment by maartenba** [comment]
May be related - https://github.com/NuGet/Home/issues/3874

**Comment by joelverhagen** [comment]
#3874 is unrelated but this definitely seems like a bug worth fixing. I can't imagine how this is desired (or understandable to the user) functionality.

**Comment by maartenba** [comment]
Well, if you have project A and project B and they require the same version number at all times (fixed dependency), this is kind of very useful :-)
