### ISSUE TITLE
Including an unmanaged DLL in build output

### ISSUE THREAD

**Issue by jnm2** [NuGet/Home#3970]
I need to create a nuspec to package a net452 managed DLL and an unmanaged DLL, both of which we build, to be consumed by other net452+ csprojs, all of which use NuGet v3's project.json.

The hard part is getting the unmanaged DLL into the build output beside the managed DLL. I've been all over the docs which say nothing (!) on this subject.

On the internet, people don't have good answers. Tactics range from:
 * guessing at `Content\bin\Debug` and `Content\bin\Release` which (guess what) won't work in the projects where we need it
 * Install.ps1 (I don't think NuGet v3 supports this)
 * Content files with copy to output directory (yuck, it should just work without adding the DLL as a project file)
 * Msbuild targets (feels like a third-class hack, is this the best that can be done?)
 * Give up and embed the native DLL in the unmanaged DLL (...no.)

I see people talking about file targets of `/runtime`, but I can't find docs on this and it doesn't seem to work.

If support for this does not exist today, what would it take to make this a nice experience for the consuming project?
Planning ahead for example, when we move to the new csproj and NuGet v4, I would expect that adding `<PackageReference>` is the only change that should have to be made to the project file in order for the unmanaged DLL to show up in build output. No targets.

**Comment by rnagpal** [comment]
@jnm2 
Hi Joseph, I'm running into the same issue. Did you finally got that working?
I used to have a .targets file under build subdir in my package, that Nuget V2 would import to my .csproj(net45) and I used to specify the unmanaged dlls as Content with CopyToOutputDirectory set to true and it used to work. In NugetV3(based on project.json) if I have the same structure, the .targets file doesn't gets imported and the native dlls don't get copied.

Wanted to check if you were able to find a solution for that in Nuget v3.

**Comment by jnm2** [comment]
@rnagpal I have not, but if you are willing for the package to add a .targets to the referencing project file, just yesterday I ran across an example of this in http://stackoverflow.com/a/40652794 that might be applicable. I haven't tried it yet. (Or, it might have the same problem on NuGet v3?)

**Comment by jainaashish** [comment]
MSbuild target is the right approach to achieve this since NuGet now has first class support for msbuild tasks and targets.
