### ISSUE TITLE
Build errors and VS crash with .NET Core template

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#3973]
1. Installed VS2017 with a quite lean combination of components (web, .NET Core, classic desktop...)
2. Did a File/New project => ASP.NET Core Web Application (.NET Framework) with Target Framework 4.6.2
3. Built solution => resulting in multiple compiler errors complaining about namespaces not being found
4. Realized that several NuGet packages are outdated and not using 1.1 
5. Used the Package Manager to update all these packages at once
6. Visual Studio froze, temporarily showed some dialog that said something about it being probably "hung"
7. After a few minutes, a OS-Dialog tells me that "Microsoft Visual Studio 2017 RC is not responding"...

I let Windows "search for a solution" in hope it would upload a dump.

Note: cannot reproduce at the moment, even by following the exakt same steps.

vsfeedback/707012

**Comment by MisterGoodcat** [comment]
I have the Windows Error Reporting file for this, if it helps.

**Comment by jainaashish** [comment]
Fixed with latest visual studio 2017 release.
