### ISSUE TITLE
[Test Failure] The NuGet client can’t be uninstalled by command

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#3979]
**NuGet Version:** 4.0.0-RC2-2079(Installed by default)
**VS Version:** D15PreRel 25919.01
**OS Version:** Windows 10 RS1_Release 14393.570.16118-1731

**Repro Steps:**
Below error occur when uninstalling NuGet client by command ‘**Vsixinstaller /u:NuGet.72c5d240-f742-48d4-a0f1-7016671e405b**’ in Developer Command Prompt for VS as admin. 
![untitledvvvv](https://cloud.githubusercontent.com/assets/20632775/20472175/70971fbc-aff2-11e6-8008-c34dec2bf329.png)

**Note:** 
1. I investigated the NuGet Dev15 VSIXID **(NuGet.72c5d240-f742-48d4-a0f1-7016671e405b)** in the file ‘extension.vsixmanifest’ of NuGet version 2079 is correct.
2. The latest version 4.0.0-RC2-2089 of NuGet client can't be installed to VS D15PreRel 25919.01.

**Comment by v-luzh** [comment]
@rrelyea, this issue is fixed on VSUWPT 26509.00+NuGet Client 4.3.0.4052 according to our verification. Not support uninstalling NuGet Vsixinstaller for now. Please help to close this bug, thanks.
