### ISSUE TITLE
[Test Failure] Reloading projects with multiple packages.config failed

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3980]
**NuGet Version:** NuGet 4.0.0-xprivate-2849 
**VS Version:** D15PreRel 25917.00
**OS Version:** Windows 10 RS1_Release 14393.479.161110-2025

**Repro Steps:**
1.	Open VS in DPL mode.
2.	Create multiple packages.config projects with dependency like PC1 -> PC2.
3.	Open ‘Manage NuGet Packages…’ of each projects and install/update some packages.
4.	Save the solution and restart visual studio.
5.	Build the solution, succeed.
6.	Try to reload the projects by expand each projects.

**Expected Result:**
Packages.config projects can be load successfully.

**Actual Result:**
Packages.config projects cannot be load successfully as below screenshot.
![pcprojectloadfailed](https://cloud.githubusercontent.com/assets/20632625/20475863/da36cca4-b008-11e6-9a02-85dedad434f1.jpg)

**Note:**
It also repro on PC1->PJ2->PC3. (PJ2 project load successfully, but PC1 and PC3 load failed)

**Comment by jainaashish** [comment]
Roslyn Bug# https://github.com/dotnet/roslyn/issues/15427
