### ISSUE TITLE
VS hang when opening project against d15prerel.25916.01

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3985]
From @ToddGrun:

I’m hitting this during automation opening a solution. The hang appears related to nuget’s use of MEF (specifically, the VSSolutionManager constructor attempting to get to the UI thread while holding onto a MEF lock). 

/cc @alpaix

**Comment by joelverhagen** [comment]
LOL Alex and I basically did the exact same thing.

Closed as dupe of https://github.com/NuGet/Home/issues/3982.

**Comment by alpaix** [comment]
> great minds think alike
