### ISSUE TITLE
[documentation] restore -recursive doesn't work for package.config project

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3987]

**Comment by karann-msft** [comment]
Please provide more details and link to the doc if it is a docs issue.

**Comment by zhili1208** [comment]
we introduced a -recursive switch for restore in https://github.com/NuGet/Home/issues/2533,
it can restore dependent project recursively.
but this switch only works for UWP project.json and dotnet core. doesn't work for packages.config project

**Comment by karann-msft** [comment]
@emgarten can you please open a PR with the necessary doc updates for this. Thanks.

**Comment by kraigb** [comment]
Added -recursive to the CLI reference, see https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#restore

**Comment by kraigb** [comment]
@zhili1208 please review and close the issue if it's been addressed satisfactorily.

**Comment by robbyls** [comment]
It doesn't work for the case that dependencies are managed by packages.config file. I have a project which depends on another package, and the package has dependencies on some standard libraries such as NLog. Running "nuget restore" to either solution or project only brings the direct dependencies back.  After spending days to try and investigate, I gave up.   It is a basic feature in Maven but not sure why it doesn't exist in Nuget.

By the way, "-recursive" doesn't make any difference. In fact the document says this option does not apply to projects using packages.config.

However, using command "Update-Package -reinstall" in Package Manager works. But it has drawbacks too.  Basically it updates my packages.config and csproj files to include all those libraries as immediate dependencies of the project.  I only want to set up direct dependencies in a project.  Does Nuget support that?

**Comment by zhili1208** [comment]
@robbyls this looks like a bug, could you file a bug for this and provide more details there(repro steps, nuget versions, etc...)
