### ISSUE TITLE
Lightweight Solution support for Package Manager Console

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#3989]
From VSFeedback item: [](https://developercommunity.visualstudio.com/content/problem/3185/package-manager-console-opens-all-projects-in-ligh.html)
VS 2017 RC's package manager console will currently cause all projects in a solution to load.

Because scripts (init.ps1) require projects to be loaded, and scripts need to execute in dependency order, this is not a simple task.

**Comment by jainaashish** [comment]
This doesn't apply anymore so closing it.
