### ISSUE TITLE
Nuget.exe config command doesn't have any log message

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3991]
this is not an regression, repros on 2.8, 3.5, 4.0-rc

repro step:
Nuget.exe config -Set HTTP_PROXY=http://127.0.0.1 -Set HTTP_PROXY.USER=domain\user
Nuget.exe config -Set HTTP_PROXY=http://127.0.0.1 -Set HTTP_PROXY.USER=domain\user -verbosity detailed

Expected: 
some log message like "nuget config set successfully for nuget.config[config path]"

Actual:
there is no message.

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
