### ISSUE TITLE
NuGet delete against v3 endpoint doesn't work

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#3992]
It's not an regression, repros on 3.5, 4.0-rc, latest dev

repro step:
nuget delete testpacakge 1.0.0 -apikey [apikey] -source https://www.nuget.org/api/v3

DELETE https://www.nuget.org/api/v3/ZHI-TEST-PACK/2.0.0
NotFound https://www.nuget.org/api/v3/ZHI-TEST-PACK/2.0.0 428ms

from our document, v3 is supported for delete.
http://docs.nuget.org/ndocs/tools/nuget.exe-cli-reference#delete

**Comment by yishaigalatzer** [comment]
Did it work in 3.4.4 ?

**Comment by zhili1208** [comment]
No, it didn't work in 3.4.4, same error messgae

**Comment by jainaashish** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
