### ISSUE TITLE
dotnet pack fails when PackagePath is empty

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#3993]
```
error MSB4018: The "PackTask" task failed unexpectedly.
error MSB4018: System.ArgumentException: String cannot be empty.
error MSB4018: Parameter name: entryName
```
```xml
<Content Include="prefercliruntime">
  <Pack>true</Pack>
  <PackagePath></PackagePath>
</Content>
```

/cc @livarcocc

**Comment by rrelyea** [comment]
Talking with @rohit21agrawal -- this should target the root path "\" as per the spec which says:
" Specifying an empty package path would add the file to the root of the package." 
(https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target)
