### ISSUE TITLE
[Test Failure] Error occur when installing jQuery 3.0.0 into JavaScript UWP template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#3995]
**NuGet Version:** NuGet 4.0.0-RC2-2079
**VS Version:** D15PreRel 25921.01
**OS Version:** Windows 10 RS1_Release 14393.570.161118-1731

**Repro Steps:**
1.	New a JavaScript Blank Application (Universal Windows) template.
2.	Open ‘Package Manager Console’.
3.	Type command ‘install-package jQuery –version 3.0.0’ and press enter, or install it by PM UI.

**Expected Result:**
No error occur.

**Actual Result:**
Error ‘Cannot index into a null array’ occur during installing as below screenshot and log. But the package is installed successfully.
![installjquery3 0 0error](https://cloud.githubusercontent.com/assets/20632625/20517407/e2e4e9da-b0d5-11e6-98c6-b27defed58a3.png)

**Note:**
1. It also repro when installing jQuery 3.0.0 by PM UI.
2. Have not seen the same issue with jQuery versions: {3.1.1},{3.1.0},{3.0.0.1},{2.2.4},{2.2.3},{2.2.2}.
3. It repro on Dev14 MU3.5 25431.01 (NuGet 3.4.4.1321).
4. It repro on Dev14 MU3.5 25431.01+ NuGet 3.5.0-RTM-1938.

**Log:**
PM> install-package jQuery -version 3.0.0

Attempting to gather dependency information for package 'jQuery.3.0.0' with respect to project 'UWP_JS', targeting 'UAP,Version=v10.0.14393'
Gathering dependency information took 467.11 ms
Attempting to resolve dependencies for package 'jQuery.3.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'jQuery.3.0.0'
Resolved actions to install package 'jQuery.3.0.0'
Retrieving package 'jQuery 3.0.0' from 'nuget.org'.
Adding package 'jQuery.3.0.0' to folder 'c:\Users\mdTestAU\documents\visual studio 2017\Projects\UWP_JS\packages'
Added package 'jQuery.3.0.0' to folder 'c:\Users\mdTestAU\documents\visual studio 2017\Projects\UWP_JS\packages'
Added package 'jQuery.3.0.0' to 'packages.config'
Executing script file 'c:\Users\mdTestAU\documents\visual studio 2017\Projects\UWP_JS\packages\jQuery.3.0.0\tools\install.ps1'
Cannot index into a null array.
At C:\Users\mdTestAU\documents\visual studio 2017\Projects\UWP_JS\packages\jQuery.3.0.0\tools\common.ps1:105 char:1
+ $ver = $matches[1]
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Error deleting vsdoc file:  + System.Management.Automation.RuntimeException: Unable to delete project item after five attempts.
Successfully installed 'jQuery 3.0.0' to UWP_JS
Executing nuget actions took 5.45 sec
Time Elapsed: 00:00:05.9467783

**Comment by jainaashish** [comment]
This isn't a NuGet issue rather package issue with it's tool script. It's working with latest version of the package with latest NuGet
