### ISSUE TITLE
Package updated with different versions

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#3998]
@jansater wrote: 
Noticed a strange thing while updating my projects this morning. I have a package that belongs to several projects in my solution and while I was updating to the latest version (its my own package) I published an even newer version. The result was that the package manager in VS actually installed the older version on half my projects and the newer version on the rest. This could lead to very serious issues and should be fixed in my opinion...

I'm using vs 2015 and Package Manager Console Host Version 3.4.4.1321

**Comment by yishaigalatzer** [comment]
This is not a visual studio issue. There is an eventual consistency problem, that if you are trying to update the first operations might have got the older versions and the other got the newer. This makes sense, and I don't know what or if we should do something about it.

Oh and FYI 3.5 is out already, you can download from https://www.nuget.org/downloads
