### ISSUE TITLE
Support NuGet PMC when DPL enabled

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4002]
Currently when we open for NuGet Package Management Console with DPL enabled, we first load all the projects and then load console so that we can execute all the init.ps1 scripts across packages.

But we need to come up with a way to support DPL without loading into the projects.

**Comment by rrelyea** [comment]
Internal bug 299104 should also be addressed by this work.

**Comment by jainaashish** [comment]
Being done as part of https://github.com/NuGet/Home/issues/5180
