### ISSUE TITLE
Support restore for PackageReference projects (normal and xplat) and Lightweight Solution Load

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4003]

**Comment by jainaashish** [comment]
Waiting on VS plat team to provide AnyCode APIs to get project details per TargetFramework.

**Comment by rrelyea** [comment]
Checkin blocked on Roslyn Bug# dotnet/roslyn#15427

**Comment by jainaashish** [comment]
Merged https://github.com/NuGet/NuGet.Client/pull/1031
