### ISSUE TITLE
[Mono issue] process errorDataReceived event is still triggered after call process.CancelErrorRead

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4004]
This issue only happens on mono 4.8
Repro step:

1. start a process to write any output, redirect standard output and error output by using OutputDataReceived Event and ErrorDataReceived event.
process.OutputDataReceived += (object o, DataReceivedEventArgs e) => { outBuffer.AppendLine(e.Data); };
            process.ErrorDataReceived += (object o, DataReceivedEventArgs e) =>
            {
                if (!string.IsNullOrWhiteSpace(e?.Data))
                {
                    _logger.LogInformation($"{process.ProcessName}: {e.Data}");
                }
            };

2. start to read output and wait for exit, then cancel read
process.BeginOutputReadLine();
process.BeginErrorReadLine();
process.WatiForExit(1000);
process.CancelOutputRead();
process.CancelErrorRead();

3. return process.ExitCode

the issue is after the return, it will get invalidOperationException, because errorDataReceived event is triggered and that event try to get process.ProcessName but the process is already exited.

**Comment by zhili1208** [comment]
@mrward

**Comment by mrward** [comment]
Is it possible to get the full code that reproduces this and open a bug on [bugzilla](https://bugzilla.xamarin.com)? Thanks.

**Comment by zhili1208** [comment]
checked in the workaround

**Comment by rrelyea** [comment]
@zhili1208 has a repro. Please open Mono bug and update records (including adding a link here)

**Comment by mishra14** [comment]
@zhili1208 is this still an issue? If so can you please open a corresponding mono issue?

**Comment by nkolev92** [comment]
Closing as redundant, stale and low priority.
