### ISSUE TITLE
[Mono issue] long password will get 400 bad request error

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4005]
Repro Step:
1. send a put request to nuget server without any credential
2. got 401, add credentials like NetworkCredential("test", new string(‘a’,10000));
3. resend the request, got 400 bad request Invalid request line (parts).

if set the password to short one, like new string('a', 20), it works well.

Looks like it's following error message:
https://github.com/mono/mono/blob/master/mcs/class/System/System.Net/HttpListenerRequest.cs#L90

**Comment by zhili1208** [comment]
@mrward

**Comment by mrward** [comment]
Would you be able to create a small program that reproduces this and open a bug on [bugzilla](https://bugzilla.xamarin.com)? Thanks.

**Comment by zhili1208** [comment]
I don't have a small reproduces for this issue now because my small repro always hit https://github.com/NuGet/Home/issues/3762 for some reason, but nuget unit test doesn't hit issue 3762

**Comment by rrelyea** [comment]
Moving to future milestone, as this may not converge in 4.0

**Comment by mishra14** [comment]
@zhili1208 is this still an issue? If so can you please open a corresponding mono issue?

**Comment by nkolev92** [comment]
Closing as redundant, stale and low priority.
