### ISSUE TITLE
[Test Failure]  VS hang when restoring NuGet package

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4006]
**NuGet Version:** 4.0.0-RC2-2092
**VS Version:** Dev14 25431.01 Update3
**OS Version:** Windows 10 TH2_Release 10586.503.160709-1837

**Repro Steps:**
1.	Create a new F# Console Application
2.	Selecting ‘**Restore NuGet Package’** by right click Solution 

**Expected Result:**
NuGet package restore successful and VS doesn’t hang.

**Actual Result:**
VS hang as below screenshot.
![untitled11111](https://cloud.githubusercontent.com/assets/20632775/20555906/616fe04c-b19f-11e6-9c6b-7cd8db093f2a.png)

**Note:** 
1.	This issue also repro on other projects.
2.	It repro when building a solution(package restore is selected by default).
3.	It doesn’t repro when building the solution after uncheck ‘**Package Restore**’(click ‘Tools’->‘NuGet Package Manager’->‘Package Manager Settings’->‘NuGet Package Manager’->‘General’).
4.	It didn’t repro on Dev14 25431.01 Update3+NuGet 4.0.0-RC2-2091.

**Comment by rrelyea** [comment]
Based on data in bug, this broke with build 2092, which was the build associated with the fix for https://github.com/NuGet/Home/issues/3982

**Comment by alpaix** [comment]
Resolved by NuGet/NuGet.Client#1034. Verified with 4.0.0-rc2-2094.
