### ISSUE TITLE
Will project.json ever be officially supported for non-core projects?

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4007]
I used this blog post to use the project.json project format for a .net 4.6.1 console app:

https://blogs.msdn.microsoft.com/lucian/2015/08/19/using-project-json-for-other-project-types

Will this be an officially supported scenario in the future?

**Comment by davidfowl** [comment]
- https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/
- https://blogs.msdn.microsoft.com/dotnet/2016/10/19/net-core-tooling-in-visual-studio-15/
- https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/
- http://blog.nuget.org/20161121/introducing-nuget4.0.html

**Comment by tomkuijsten** [comment]
Thanks, I've already read most posts in the past. Anyhow, I've read them again and actually did find an answer in the last blog post (in the "What's next" paragraph):

_"enabling PackageReference support for all project types"_

**Comment by rrelyea** [comment]
Yes, PackageReference for all project types is our main direction.
We'll continue to support Packages.Config and UWP-Style project.json, but our goal is to help people migrate to PackageReference and keep the majority of our investment there.
We will fix some issues in Package.Config/UWP-Style Project.Json -- but very minimal. The bulk of our investment, including fixes and features will be in PackageReference.
