### ISSUE TITLE
VS Hangs when you Create new Core Console App, Close Solution, Open Solution and Close Solution 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4008]
Ported from dotnet/roslyn-project-system#777.

Repro:
VS Build D15PreRel 15.0.25918.0

1. Create a new Core Console App
2. Close Solution(not VS)
3. Open the previously created solution
4. Close Solution

VS Hangs with a message saying Unloading the project and after a while crashes.

**Comment by alpaix** [comment]
NuGet/NuGet.Client#1034 resolved the issue. Will validate the fix.

**Comment by rrelyea** [comment]
Appears fixed according to partners.
