### ISSUE TITLE
nuget.exe 4.0-rc pack and update doesn't work on dev15 by passing msbuildPath

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4009]
nuget.exe can't find Microsoft.build.framework.dll on dev15 during loading Microsoft.build.dll

**Comment by rrelyea** [comment]
Please port necessary part of @drewgillies other work to fix this, and check into dev and release-4.0-rc. This should be your P0 please.

**Comment by zhili1208** [comment]
https://github.com/NuGet/NuGet.Client/commit/a197992bde5121575cf0cb5527b6399d41b66032
