### ISSUE TITLE
Error in Nuget restore command - nuget 2.8.6

### ISSUE THREAD

**Issue by larbimeriem** [NuGet/Home#4010]
Hi
i have an error and i dont understand why because everything is correct i think, i am trying to restore package for a .net Project to do a build in Bamboo atlassian so i downloaded nugetto do that and we already use it in Stash (every project has Packages.config with the referenced Package) so i tried to nuget in CMD console but i faced an error: details below:

NuGet Version: 2.8.60717.93
OS version (i.e. win7 )):
Bamboo atlassian version 5.14.1

## Detailed repro steps so we can see the same problem

1. i am using the commande restore package like this :"nuget restore C:\Users\MLarbi\bamboo-home\xml-data\build-dir\TEST-WAT-JOB1/packages.config"

2.I have this error : "Impossible de déterminer le dossier de packages pour restaurer les packages NuGet. Veuillez spécifier soit -PackagesDirectory, soit -SolutionDirectory." 

THX
![1](https://cloud.githubusercontent.com/assets/23717850/20593486/f0a3db54-b232-11e6-9496-d49ff626c55d.PNG)
![2](https://cloud.githubusercontent.com/assets/23717850/20593513/09239fa2-b233-11e6-8253-af9d38946a98.PNG)
![3](https://cloud.githubusercontent.com/assets/23717850/20593521/0cb090b2-b233-11e6-9eda-3ee0837877c0.PNG)

**Comment by rrelyea** [comment]
Could you please try NuGet.exe v3.5.0 and tell us if the behavior or message changes?
http://nuget.org/downloads

**Comment by zhili1208** [comment]
No response, close it as not repro
