### ISSUE TITLE
NuGet.exe 3.3 pack performance on OSX (mono) [fixed with 3.5]

### ISSUE THREAD

**Issue by panxn** [NuGet/Home#4011]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe
NuGet version (x.x.x.xxx):
3.3
dotnet.exe --version (if appropirate):
4.0
VS version (if appropriate):
No
OS version (i.e. win10 v1607 (14393.321)):
OSX 10.11.2
Worked before? If so, with which NuGet version:
No
## Detailed repro steps so we can see the same problem

1. we are using nuget on OSX via mono 4.6

2. we have a folder consists of 10000+ cpp header files (about 130MB), pack them with following command:
mono --arch=64 {NugetDir}/nuget.exe pack xxx.nuspec -OutputDirectory {Output}/packages -NoPackageAnalysis

3. This process costs about 15 minutes to finish while it's only 2 minutes on windows.

4. we have noticed:
         during the entire 15 minutes, first 2 minutes are used to generate nupkg, then in the remaining 13 minutes nuget keeps running instead of exiting. we don't know what nuget is doing during the 13 minutes.

so we wonder if it's a bug, and how to improve the speed.

### Verbose Logs

mono --arch=64 {NugetDir}/nuget.exe pack xxx.nuspec -OutputDirectory {Output}/packages -NoPackageAnalysis

output: Attempting to build package from "xxx.nuspec"

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zhili1208** [comment]
@libaracy Could you try nuget 3.5? https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe

**Comment by panxn** [comment]
@zhili1208 much faster, thank you
