### ISSUE TITLE
.props file is not added during install in .NET Core project in VS 2017 RC

### ISSUE THREAD

**Issue by bkoelman** [NuGet/Home#4012]
## Details about Problem
During package install, the .props file is not added to the project file of a .NET Core project in VS 2017 RC. This works for non-Core projects in VS 2017 RC.

## Detailed repro steps so we can see the same problem
1. Install VS 2017 RC with Web/Cloud workload
2. Create a new Core Web Application (MVC)
3. From the package manager console: `Install-Package CSharpGuidelinesAnalyzer -pre`
4. Open the .csproj file and see no reference to the .props file.

The result of this is that not all analyzers run, because about half of them require IOperation support. The .props file activates that. Adding `<Features>IOperation</Features>` manually to the project and rebuilding will make all diagnostics run. You'll see extra warnings in the Error List then.

Applying the steps above on a .NET Framework Class Library project adds the .props file as expected. On [this page](http://docs.nuget.org/ndocs/create-packages/creating-a-package#including-msbuild-props-and-targets-in-a-package) it says:
*With NuGet 3.x, targets are not added to the project but are instead made available through the project.lock.json.*
That does not make sense to me. These is no more project.lock.json file in VS2017 RC.

Is this a bug or do I need to do something extra to the package to make adding IOperation support possible for .NET Core projects in VS 2017?

**Comment by bkoelman** [comment]
I have found [instructions for NuGet 4](http://docs.nuget.org/ndocs/schema/msbuild-targets).

The file "e:\Bart\Documents\Visual Studio 2017\Projects\CoreWebApplication1\src\CoreWebApplication1\obj\CoreWebApplication1.csproj.nuget.g.props" contains a reference to `CSharpGuidelinesAnalyzer.props` file:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
    <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.Sdk.props" Condition="Exists('$(NuGetPackageRoot)microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.Sdk.props')" />
    <Import Project="$(NuGetPackageRoot)microsoft.net.sdk.web.projectsystem\1.0.0-alpha-20161104-2-112\build\netstandard1.0\Microsoft.NET.Sdk.Web.ProjectSystem.props" Condition="Exists('$(NuGetPackageRoot)microsoft.net.sdk.web.projectsystem\1.0.0-alpha-20161104-2-112\build\netstandard1.0\Microsoft.NET.Sdk.Web.ProjectSystem.props')" />
    <Import Project="$(NuGetPackageRoot)csharpguidelinesanalyzer\0.3.0-pre-00001\build\CSharpGuidelinesAnalyzer.props" Condition="Exists('$(NuGetPackageRoot)csharpguidelinesanalyzer\0.3.0-pre-00001\build\CSharpGuidelinesAnalyzer.props')" />
  </ImportGroup>
</Project>
```

It turns out that all diagnostics *do* run after building the solution. It's just that they do not run in live analysis. So this might be a roslyn issue. Should I create an issue there?

Hope this helps in understanding what is going on.

**Comment by rrelyea** [comment]
nuget properly will import the .props file as part of the build. so yes, if you have questions about live analysis and things like that, you should ask that question elsewhere - as we are not the experts. Perhaps Roslyn?
