### ISSUE TITLE
Adequate UI Feedback during AutoRestore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4014]
Design and discussion necessary.

**Comment by rrelyea** [comment]
also, make sure that the logging works better... see vs feedback item 743659

**Comment by alpaix** [comment]
Auto-restore UI should be integrated with the Task Status Center. TSC will actually drive the status bar text and progress bar in the future.

**Comment by nkolev92** [comment]
Closing as stale. We log to the status ba.r

One would argue we log way too much.
