### ISSUE TITLE
[NuGet.VisualStudioExtension] Turn the error message of "Central Directory corrupt" into a more readable message

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#402]
Repro:

run-test installpackageusingforceswitch against int.nugettest.org

**Comment by danliu** [comment]
call stack: 

	System.IO.Compression.dll!System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory() Line 667	C#
 	System.IO.Compression.dll!System.IO.Compression.ZipArchive.Init(System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, bool leaveOpen) Line 519	C#
 	System.IO.Compression.dll!System.IO.Compression.ZipArchive.ZipArchive(System.IO.Stream stream, System.IO.Compression.ZipArchiveMode mode, bool leaveOpen, System.Text.Encoding entryNameEncoding) Line 138	C#
>	NuGet.PackageManagement.dll!NuGet.PackageManagement.MinClientVersionHandler.CheckMinClientVersion(System.IO.Stream packageStream, NuGet.Packaging.Core.PackageIdentity packageIdentity) Line 16	C#
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.ExecuteInstallAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, System.IO.Stream packageStream, System.Collections.Generic.HashSet<NuGet.Packaging.Core.PackageIdentity> packageWithDirectoriesToBeDeleted, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Threading.CancellationToken token) Line 1159	C#
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, System.Collections.Generic.IEnumerable<NuGet.PackageManagement.NuGetProjectAction> nuGetProjectActions, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Threading.CancellationToken token) Line 1019	C#
 	NuGet.PackageManagement.PowerShellCmdlets.dll!NuGet.PackageManagement.PowerShellCmdlets.PackageActionBaseCommand.InstallPackageByIdentityAsync(NuGet.ProjectManagement.NuGetProject project, NuGet.Packaging.Core.PackageIdentity identity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext projectContext, bool isPreview, bool isForce, NuGet.PackageManagement.UninstallationContext uninstallContext) Line 105	C#
 	NuGet.PackageManagement.PowerShellCmdlets.dll!NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand.InstallPackages(System.Collections.Generic.IEnumerable<NuGet.Packaging.Core.PackageIdentity> identities) Line 78	C#
 	NuGet.PackageManagement.PowerShellCmdlets.dll!NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand.ProcessRecordCore.AnonymousMethod__1() Line 62	C#
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task>.InnerInvoke() Line 680	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#

**Comment by yishaigalatzer** [comment]
@deepakaravindr please update on the checkin bug

**Comment by yishaigalatzer** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/33e0cd798572838b066770949f9965d3d6a2f3bc
