### ISSUE TITLE
NuGet docs for contribution guidelines contain dead link (404)

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4024]
Parent link - https://docs.nuget.org/ndocs/policies/governance#contributors

Within the link above the following links result in a 404

Contribution instructions for NuGet Client and NuGet Gallery
Contribution instructions for NuGet Docs.

**Comment by kraigb** [comment]
Thanks for catching these. I'll be fixing them shortly.

**Comment by kraigb** [comment]
Fixed with PR694.

https://github.com/NuGet/NuGetDocs/pull/694
