### ISSUE TITLE
Nuget package restore failing for new project

### ISSUE THREAD

**Issue by jenndluna** [NuGet/Home#4025]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 3.4.4.1321

VS version: VS 2015

OS version (Win 10 Pro):

## Detailed repro steps

1. Create new web application 
2. Open nuget package manager
3. Add EntityFramework version 6.1.3
4. Yellow error bar shows at the top: Message: "An error occurred while trying to restore packages: Central Directory corrupt." Output says the package was not installed

**Comment by emgarten** [comment]
@jenndluna what type of web application is this? Does it use xproj or csproj?

**Comment by jenndluna** [comment]
it is csproj, I created an empty  project

**Comment by emgarten** [comment]
Try NuGet 3.5.0 from: https://dist.nuget.org/index.html

You can also try clearing your caches using ``nuget.exe locals -clear all``

The error you are seeing typically occurs from an incomplete nupkg download. NuGet will retry the download several times, but if you are having some serious network issues or have a local source with invalid nupkgs it could still happen.

**Comment by rrelyea** [comment]
Please let us know if that doesn't solve it for you. Closing for now.
