### ISSUE TITLE
[Test Failure] Failed to restore mixed solution with PC and PJ projects after deleting a package manually

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4028]
**Repro Steps:**
1. Open visual studio in DPL mode.
2. Create a solution with multiple projects mixed with PC and PJ projects (dependency: **PC1->PJ2->PC3**).
3. Install packages. (PC1 install Newtonsoft.Json 8.0.2, PJ2 install jQuery 3.1.0 and PC3 install log4Net 2.0.5)
4. Save solution and close it.
5. Manually delete a package. (I deleted jQuery 3.1.0 from packages folder.)
6. Open the solution after restarting VS, build and restore the whole solution.

**Expected Result:**
The package can be restore successfully.

**Actual Result:**
Failed to restore the solution as below screenshot.
![restoredeletedpackagefailed](https://cloud.githubusercontent.com/assets/20632625/20706633/37cbc292-b663-11e6-8976-011ef33c442c.png)

**Warnings in Error List:**
Failed to resolve all project references. The package restore result for 'PJ2\PJ2.csproj' or a dependant project may be incomplete.
Failed to resolve all project references. The package restore result for 'SolutionMix\PC1.csproj' or a dependant project may be incomplete.

**Note:**
1. It found on D15PreRel 25928.07 (NuGet Client 4.0.0-RC2-2098).
2. It doesn’t repro in solutions with only PC or PJ projects.

**Comment by rrelyea** [comment]
this sounds like an issue with DPL minbar that was implemented in RC1.
Likely, this is fixed with your newer work??

**Comment by jainaashish** [comment]
It's fixed. But DPL restore code is not yet checked in. It will be checked in as part of RC3.

**Comment by v-luzh** [comment]
It is fixed on D15PreRel 26013.05+NuGet Client 4.0.0-RC3-2130.
