### ISSUE TITLE
Upgrading Microsoft.NETCore.App from 1.0.1 to 1.1.0 removes type: platform

### ISSUE THREAD

**Issue by HakanL** [NuGet/Home#4032]
Incorrectly opened the ticket here: https://github.com/dotnet/cli/issues/4869

## Steps to reproduce

Visual Studio 2015 Update 3, all latest .NET Core tools/extensions installed (including .NET Core 1.1 SDK).

**Note that this may not be related to the Microsoft.NETCore.App package, but may be a universal problem.**

Creating a new .NET Core Command line project adds this dependency to the project.json:
`
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    }
  },
`

If you then go under references and upgrade the NuGet packages to the latest (1.1.0) then the type:platform above is removed and the build fails saying runtimes section is missing.

`
   "dependencies": {
       "Microsoft.NETCore.App": "1.1.0"
   },
`

## Expected  behavior
It should keep the type:platform attribute when upgrading the Microsoft.NETCore.App NuGet package.

## Actual behavior
type:platform is removed.

## Environment data

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by HakanL** [comment]
This is in the Visual Studio NuGet UI, not sure if it happens elsewhere.

**Comment by emgarten** [comment]
@HakanL Try 3.5.0 from https://dist.nuget.org/index.html

**Comment by HakanL** [comment]
I'm doing this from inside Visual Studio, and the NuGet extension is updated to version 3.5.0.1484.

**Comment by emgarten** [comment]
@HakanL that is 3.5.0-beta2, you can get the 3.5.0 RTM version from dist.

**Comment by HakanL** [comment]
Ah, got it. I can confirm that this works in 3.5.0 RTM. So we can close this. Thanks for your help!

**Comment by Eilon** [comment]
Note to others: you have to manually install the new VSIX from here: https://dist.nuget.org/index.html

In VS2015 you won't see it listed in the Gallery / Updates.
