### ISSUE TITLE
.net core behavior in vs2017? - VS2015 package restore does not update instead downgrades

### ISSUE THREAD

**Issue by RussKie** [NuGet/Home#4034]
Copied from https://github.com/dotnet/corefx/issues/14110

I have an existing .NETCore app 1.0.0 which I am trying to update to 1.1.0.

I have:
* downloaded the latest .NET Core 1.1 SDK from https://go.microsoft.com/fwlink/?LinkID=835014
* tweaked the global.json to point to this version,
* tweaked project.json to point to Microsoft.NETCore.App 1.1.0 and netcoreapp1.1

```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "System.Xml.XmlSerializer": "4.0.11",
    "System.Xml.XmlDocument": "4.0.1",
    "Microsoft.IdentityModel.Tokens": "5.0.0",
    "System.IdentityModel.Tokens.Jwt": "5.0.0",
    "System.Security.Cryptography.Algorithms": "4.2.0"
  },

    "tools": {
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.DotNet.Watcher.Tools": "1.0.0-preview2-final"
    },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

    "scripts": {
        "prepublish": [ "bower install", "dotnet bundle" ],
        "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    },
    "userSecretsId": "aspnet-WebApplication1-20160823024436"
}
```

At this stage VS tells me I need to update the references. Fair enough.
Do package restore by clicking on "References" node:

```
PATH=%PATH%
C:\Program Files\dotnet\dotnet.exe restore "D:\Amber\WebApplication1\.vs\restore.dg"
log  : Restoring packages for D:\Amber\WebApplication1\src\WebApplication1\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in D:\Amber\WebApplication1\src\WebApplication1\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in D:\Amber\WebApplication1\src\WebApplication1\project.json...
log  : Restoring packages for tool 'Microsoft.DotNet.Watcher.Tools' in D:\Amber\WebApplication1\src\WebApplication1\project.json...
warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.3.0 to 4.2.0 
warn :  WebApplication1 (>= 1.0.0) -> Microsoft.NETCore.App (>= 1.1.0) -> System.Security.Cryptography.Algorithms (>= 4.3.0) 
warn :  WebApplication1 (>= 1.0.0) -> System.Security.Cryptography.Algorithms (>= 4.2.0)
log  : Writing lock file to disk. Path: D:\Amber\WebApplication1\src\WebApplication1\project.lock.json
log  : D:\Amber\WebApplication1\src\WebApplication1\WebApplication1.xproj
log  : Restore completed in 7043ms.
```

Project.json isn't updated:
![image](https://cloud.githubusercontent.com/assets/4403806/20735162/6e25cb82-b6f2-11e6-9075-d2ccc8debde6.png)

Microsoft Visual Studio Enterprise 2015
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
Microsoft .NET Core Tools (Preview 2) 14.1.21111.0
NuGet Package Manager 3.5.0

Question1: Why aren't the references and dependencies are updated to the correct version?
Question2: Why are the references and dependencies are downgraded?

**Comment by yishaigalatzer** [comment]
Because you specified top level  "System.Security.Cryptography.Algorithms": "4.2.0", this the nearest wins rule https://docs.nuget.org/ndocs/consume-packages/dependency-resolution

**Comment by RussKie** [comment]
I am still unconvinced this is correct.

The project.lock.json has the following in it:

```
  "projectFileDependencyGroups": {
    "": [
      "Microsoft.AspNetCore.Diagnostics >= 1.1.0",
      "Microsoft.AspNetCore.Mvc >= 1.1.0",
      "Microsoft.AspNetCore.Razor.Tools >= 1.1.0-preview4-final",
      "Microsoft.AspNetCore.Server.IISIntegration >= 1.1.0",
      "Microsoft.AspNetCore.Server.Kestrel >= 1.1.0",
      "Microsoft.AspNetCore.StaticFiles >= 1.1.0",
      "Microsoft.Extensions.Configuration.EnvironmentVariables >= 1.1.0",
      "Microsoft.Extensions.Configuration.Json >= 1.1.0",
      "Microsoft.Extensions.Logging >= 1.1.0",
      "Microsoft.Extensions.Logging.Console >= 1.1.0",
      "Microsoft.Extensions.Logging.Debug >= 1.1.0",
      "Microsoft.Extensions.Options.ConfigurationExtensions >= 1.1.0",
      "Microsoft.IdentityModel.Tokens >= 5.1.0",
      "Microsoft.NETCore.App >= 1.1.0",
      "Microsoft.VisualStudio.Web.BrowserLink.Loader >= 14.1.0",
      "System.IdentityModel.Tokens.Jwt >= 5.1.0",                               <-- here
      "System.Security.Cryptography.Algorithms >= 4.3.0",                 <-- here
      "System.Xml.XmlDocument >= 4.3.0",
      "System.Xml.XmlSerializer >= 4.3.0"
    ],
    ".NETCoreApp,Version=v1.1": []
  },
```

Also [Microsoft.IdentityModel.Tokens v5.1.0](https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/5.1.0) clearly states it requires System.Security.Cryptography.Algorithms (>= 4.3.0)

**Comment by rrelyea** [comment]
with VS 2017 next RC, please try out your scenario, but first change the TargetFramework from NetCoreApp1.0 to NetCoreApp1.1 using the UI or editing in csproj.
We think this will work correctly.

**Comment by eroller** [comment]
I am seeing this same behavior in VS2017 targeting netcoreapp1.1. Nuget Package Manager 4.0.0

Documentation here can be updated to indicate package downgrade is now just a warning:
https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution

My question: 

Shouldn't the default behavior be to treat downgrades as errors? Is there any way I can switch it back into an error? It seems dangerous to treat unmet dependencies as just warnings since it will very likely lead to runtime errors (e.g. missing method exception). My preference would be to treat them as errors and give us an easy way (through the nuget VS UI, maybe another tab after Consolidation, named Downgrades?) to resolve them by updating top level dependencies to the lowest version that satisfies all requirements.

**Comment by mishra14** [comment]
@emgarten : Can this be done as part of Restore Error and warnings task?

**Comment by emgarten** [comment]
> Can this be done as part of Restore Error and warnings task?

Yes, that would be part of that work.

**Comment by mishra14** [comment]
@eroller : As of 15.3 release, you will be able to make the choice to treat downgrade warnings as errors for package reference projects.

You can add the following to your csproj file - 

```
  <PropertyGroup>
    <WarningsAsErrors>NU1605</WarningsAsErrors>
  </PropertyGroup>
```

This will make the downgrade warning as an error in your build.

**Comment by mishra14** [comment]
Closing as there is no new request.

**Comment by eroller** [comment]
I've upgraded to 15.3.5 and am not getting any errors or warnings for unmet package dependency (see attached screenshot from visual studio). Note that this isn't a package downgrade since the Illumina.Common dependency is (= 4.5.0.298) rather than (>= 4.5.0.298) so everything happens to run fine, but it is still an unmet dependency that I would like to know about through a warning or error during package restore. If the dependency had been (>= 4.5.0.298 && < 4.7) and 4.7.0.309 introduced a breaking change then I could get a runtime error (missing method exception). Is this just not available right now? Should I submit a new issue for this?

![4034](https://user-images.githubusercontent.com/2440289/30675840-b9129ae4-9e37-11e7-973d-c5db4cf5d90d.png)

**Comment by emgarten** [comment]
@eroller this is covered by https://github.com/NuGet/Home/issues/2358 which has been added in VS 15.4. You can set NU1608 as an error to fail when a package is higher than the upper bounds.
