### ISSUE TITLE
New background restore writes milliseconds to status bar when it takes seconds to restore

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4036]
Can we use a more appropriate duration - measuring something in ms when it takes seconds just looks silly:

![image](https://cloud.githubusercontent.com/assets/1103906/20742379/d11df65c-b723-11e6-974f-1450db89ed38.png)

**Comment by yishaigalatzer** [comment]
The code should use the same pattern we use everywhere else - milliseconds if smaller than a second, seconds:milliseconds up to 60 seconds, minutes:seconds, (hours:minutes ???)

@alpaix @rrelyea
