### ISSUE TITLE
[Test Failure] Error ‘Object reference not set to an instance of an object’ occur when trying to open PMC and PM UI on VS Blend

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4037]
**Repro Steps:**
1. Open Microsoft Blend for VS.
2. Create C# UWP template.
3. Try to open PMC and PM UI (both project level and solution level).

**Expected Result:**
PMC and PM UI opened successfully and no error show.

**Actual Result:**
Error ‘Object reference not set to an instance of an object’ occur as below screenshot.
![blenderror](https://cloud.githubusercontent.com/assets/20632625/20743465/7e900810-b711-11e6-88f1-85d7f0fc37a7.png)
**Note:**
1.	It was found on D15PreRel 25929.05 (NuGet Client 4.0.0-RC2-2098).
2.	It repro on D15Rel 25928.00 + NuGet Client 4.0.0-RC2-2102.
3.	It just repro on VS blend, doesn’t repro on VS.
4.	No response after clicking the ‘Restore’ button or doing solution restore.
5. Repro on D15PreRel 25928.07 (NuGet 4.0.0-RC2-2098).

**Comment by rrelyea** [comment]
This was fixed in RC2 by the blend team. The fix for internal bug 297804 was checked into d15rel this morning.
