### ISSUE TITLE
[Test Failure]The information of output flashed and disappear when Install/Uninstall/Update package by UI on Web Application (.NET Core)

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4038]
**NuGet Version:** NuGet 4.0.0-rc2-2102
**VS Version:** D15Rel 25928.00
**OS Version:** Windows 10 RS1_Release 14393.571.161121-1745

**Repro Steps:**
1.	Create a new C#->Web->**Asp.NET Web Application (.NET Core) ->Web Application** project.
2.	Start Manage NuGet package dialog by right clicking of the project node.
3.	Install package ‘Newtonsoft.Json’ –version 9.0.1 shown on the Browser tab.
 
**Expected Result:**
The install information should appear in output windows.

**Actual Result:**
The output information flashed and disappear in output windows as below screenshot.
![1130](https://cloud.githubusercontent.com/assets/20632775/20747281/84a03028-b724-11e6-82e8-a46bc93f454d.png)

**Note:**
1.	The issue repro on Dev15 PreRel 25929.02 (NuGet 4.0.0-RC2-2098).
2.	The issue repro when Uninstall/Update package by UI.

**Comment by rrelyea** [comment]
@alpaix - related to the output cleanup you've been doing?

**Comment by alpaix** [comment]
This is not the same flow I'm working on. I'll verify if my fix resolves this issue as well.

**Comment by alpaix** [comment]
In .NET core scenario install package is followed by immediate auto-restore which cleans the output window. The ideal fix should handle such a sequence gracefully.
