### ISSUE TITLE
Could not find the Microsoft.AspNet.Loader.IIS.Interop Nuget package in your users package folder.This NuGet package required to run ASP.Net 5 Web application

### ISSUE THREAD

**Issue by moonir01** [NuGet/Home#4039]
i am trying many time nuget install error message are :

**Could not find the Microsoft.AspNet.Loader.IIS.Interop Nuget package in your users package folder.This NuGet package required to run ASP.Net 5 Web application**

But i have install the package using command :line using this command Install-Package Microsoft.AspNet.Loader.IIS -Pre [](http://prnt.sc/ddqigm) http://prnt.sc/ddqigm

install message : Successfully installed 'Microsoft.AspNet.Loader.IIS.Interop.1.0.0-beta7' to Project1 PM> Install-Package Microsoft.Dnx.Loader -Pre
[](http://prnt.sc/ddqj7e) http://prnt.sc/ddqj7e
but not running the loader where i have click IIS Express

Thansk
Md monirozzaman

**Comment by rrelyea** [comment]
What version of VS? 
What version of Nuget?
Did it work before? With what versions?

**Comment by rrelyea** [comment]
@moonir01 - we'd love to have more information. please answer our previous questions.

**Comment by moonir01** [comment]
@rrelyea  VS version  2015 update 2 and trying all Nuget Verson OS Version :  windows 8.1
but i have install another laptop and work fine

**Comment by moonir01** [comment]
@rrelyea problem solved im just change os Windows 8.1 32 bit  to 64 bit
