### ISSUE TITLE
Rename values of _ProjectRestoreType property

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#4047]
`NuGet.targets` sets the value of the `_ProjectRestoreType` property [based on how package references are expressed](https://github.com/NuGet/NuGet.Client/blob/e77e9f03232c06c044834f1b540ef6de85d98a38/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L254-L264).  However, the values of the property currently refer to what the project is targeting, which may not correspond to how package references are expressed.  For example, it's possible to use `PackageReference` with .NET Framework projects, but the value of `_PackageRestoreType` would be `NETCore`.

So I suggest considering changing `UAP` to `ProjectJson` and `NETCore` to `PackageReference`.

**Comment by emgarten** [comment]
@dsplaisted what scenarios are you relying on this internal property for?

The work to expose this publicly is in progress and being tracked here: https://github.com/NuGet/Home/issues/3928     ProjectJson and PackageReference are the two possible values so far.

**Comment by dsplaisted** [comment]
See #4046.  In the .NET SDK, we want the project restore type to be .NET Core, even if there aren't any `PackageReferences` in the project, so that we get the transitive package references from referenced projects.  Right now we do this [by injecting a target](https://github.com/dotnet/sdk/blob/8e5f56506c607ec6eaa40d05898b26075a9a183f/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L220-L226)
