### ISSUE TITLE
Is posible to use ApiKey when restore nugets

### ISSUE THREAD

**Issue by McMlok** [NuGet/Home#4049]
Hello,

we have our internal Nuget repository (Nexus 3) secured with ApiKey. I try to set ApiKey to nuget.config with command nugget setapikey for our repo URL. But when I try to restore packages from this repo I was prompted for username/password. When I try to push new package to repo it use apikey and it works. Is possible to configure nuget to use apikey for restore package?

I know I can use packageSourceCredentials and store username/password for source but it don't solve problem for long time because of password expiration policy.

I try this with Nuget.exe 2.8, 3.4, 3.5, 4.0RC3

Thanks

**Comment by emgarten** [comment]
The API key is only used for pushing packages. It is not used for authenticating to a private feed.
