### ISSUE TITLE
NuGet should use the global package location to avoid using memory stream.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#405]
Should NuGet use a machine cache in V3? In V2, there used to be a machine cache. Should we bring it back, possibly in a different form, in V3?

**Comment by emgarten** [comment]
We should use the DNX caching system if possible the for V2/V3 protocol

**Comment by yishaigalatzer** [comment]
We should be able to read the DNX style folder layout.

**Comment by deepakaravindr** [comment]
Fixed by NuGet/NuGet3@18a4559, NuGet/NuGet.PackageManagement@03e01cd and NuGet/NuGet.VisualStudioExtension@c150295
