### ISSUE TITLE
Shared Nuget Folder, Packages Are Removed

### ISSUE THREAD

**Issue by mafshin** [NuGet/Home#4053]
I have a central `Nuget `folder which is shared among multiple solutions.
In each solution there is virtual `Nuget `folder with the `Nuget.config` item (located in shared folder) inside that.

Whenever I remove a package from one of the solutions the output is as below:
```
Removing package 'Microsoft.Extensions.Primitives.1.1.0' from folder 'C:\Projects\XXX\$\..\Packages'
Removed package 'Microsoft.Extensions.Primitives.1.1.0' from folder 'C:\Projects\XXX\$\..\Packages'
```

**Question**
How can I configure the `Nuget ` not to remove the files from a shared `Nuget `folder after uninstalling ?

**Version**
Nuget: 3.4.4.1321
NuGet product: VS UI
VS 2015 Update 3
OS: Win10 build 14393

**Comment by zhili1208** [comment]
packages folder for packages.config is designed for one packages folder per solution scenario, for your case, I suggest you to move from packages.config to package reference which use a central package folder for all solutions. https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
