### ISSUE TITLE
Restore fails with custom framework names

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#4056]
When the `TargetFramework` of a project is unknown to NuGet, restore fails with `Invalid restore input. Invalid target framework 'unsupported'`.

NuGet should have sensible default behavior for both restore and install even for cases of unknown frameworks. This has caused a lot of problems in the past for Xamarin, and it's practically unfeasible to have NuGet know ahead of time every custom target framework people can come up with (i.e. Tizen on the horizon? ;)).

The following is a trivial repro case for a custom framework that causes `msbuild /t:Restore` to break under VS2017 RC as of today:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<TargetFramework>Xamarin.IoT</TargetFramework>
		<RestoreOutputPath>$(MSBuildThisFileDirectory).nuget</RestoreOutputPath>
	</PropertyGroup>

	<Import Project="$(RestoreOutputPath)\$(MSBuildProjectFile).nuget.g.props"
		Condition="Exists('$(RestoreOutputPath)\$(MSBuildProjectFile).nuget.g.props') And '$(SelfUpdating)' != 'true'" />

	<ItemGroup>
		<PackageReference Include="MSBuilder.DumpItems" Version="0.2.1" />
	</ItemGroup>

	<Target Name="Build">
		<Message Text="Build succeeded" Importance="high" />
	</Target>

	<!-- Import NuGet.targets for Restore -->
	<PropertyGroup>
		<NuGetRestoreTargets Condition="'$(NuGetRestoreTargets)'==''">$(MSBuildExtensionsPath)\..\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets</NuGetRestoreTargets>
	</PropertyGroup>
	<Import Condition="Exists('$(NuGetRestoreTargets)')" Project="$(NuGetRestoreTargets)" />

	<Import Project="$(RestoreOutputPath)\$(MSBuildProjectFile).nuget.g.targets"
			Condition="Exists('$(RestoreOutputPath)\$(MSBuildProjectFile).nuget.g.targets') And '$(SelfUpdating)' != 'true'" />

	<!-- Unfortunately, _GenerateRestoreProjectReferencePaths has a dependency on this target... -->
	<Target Name="_SplitProjectReferencesByFileExistence" />
</Project>
```

**Comment by kzu** [comment]
Another recent manifestation of this issue is at https://github.com/NuGet/Home/issues/3961, but the underlying issue is not directly related to NuGetizer.

**Comment by davidfowl** [comment]
What would nuget do with an unknown framework? Can you provide some concrete suggestions for the "sensible default behavior"

**Comment by kzu** [comment]
Generate the props/targets imports for build targets provided without a TFM
or with a matching one, for a start ;).

That would already be immensely useful, since the custom targets could then
do whatever is applicable to that custom framework (I.e. add references,
contents, embedded resources, etc.).

**Comment by davidfowl** [comment]
so you mean so string matching in the case where the framework is unknown? What does that package contain? Is it using nuget for anything other than build props/targets?

**Comment by kzu** [comment]
There is already a convention to turn TFMs to [identifier][major][minor],
so yes.

Build targets usually don't contain the TFM anyway.

The targets are almost everything in a custom framework (I.e. think
Xamarin, the whole iOS implementation could probably be turned into a
nuget. API binding assembly, build/compile/link targets, everything).
Revving XI or XA  typically involves just shipping new targets and ref asms

**Comment by davidfowl** [comment]
How would compatibility between frameworks work? Sadly I don't know is what you want scales very well past this simple scenario. What you describe is using one particular feature of nuget (ability to import build targets and props). It wouldn't work for anything else...

**Comment by kzu** [comment]
Well, maybe that's a good starting point, and as people need more features beyond importing targets, then we can think about it?

**Comment by emgarten** [comment]
With the current nupkg rules it is not possible to determine what is a framework and what isn't since the lib folder allows both sub folders with non-TFM names and sub folders that are TFMs. There is a plan to fix this here: https://github.com/NuGet/Home/issues/496

Beyond that things are a little more complicated now with netstandard. I would imagine many new TFMs would need compatibility mappings with that, but without support for it NuGet could only determine that it is compatible with other TFMs of the same name and a lower version.

**Comment by rrelyea** [comment]
4.0 is overloaded, moving to future-1 for discussion.

**Comment by kzu** [comment]
And that limitation @emgarten would be more than acceptable for "minimal support for custom TFMs", IMHO

**Comment by davidfowl** [comment]
@kzu It's not a custom TFM, you should stop thinking of it that way. It's a way to bring in targets while completely ignoring the project's TFM. You happen to be trying to invent TFMs using it, but those TFMs will never work with nuget without further changes (being able to also express a compatibility matrix).

**Comment by kzu** [comment]
That is exactly the behavior for targets included without a TFM, so what's
different? Mainly, that nuget has a hardcoded list of "valid" ones?

**Comment by davidfowl** [comment]
> That is exactly the behavior for targets included without a TFM, so what's
different? Mainly, that nuget has a hardcoded list of "valid" ones?

That's correct. All the places where TFMs exist, this "custom TFM" would have to be a drop in replacement and have identical behavior. Today it *cannot* do that because of other limitations.

**Comment by kzu** [comment]
Well, I guess what I'm proposing is for nuget to begin being more open and less hardcoded. I.e., contentFiles is another area where I don't think knowing what a TFM is makes sense either

**Comment by emgarten** [comment]
> contentFiles is another area where I don't think knowing what a TFM is makes sense either

Would it work for you to use the ``any`` folder then? You can avoid TFMs all together by using ``contentFiles/any/any/*`` and ``build/*``

**Comment by kzu** [comment]
`build/*` doesn't work, which is precisely the point of the issue ;)

Agreed that using `any` would suffice for contentFiles.

**Comment by zhili1208** [comment]
it's hard for nuget to differentiate a sub folder or an unknown target framework. Close it as won't fix
