### ISSUE TITLE
Updating a package across a solution throws errors for projects without the package

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#406]
1. Create a solution with multiple projects, install the package into half of the projects
2. Update the package using: update-package from PMC

Expected
Only projects with the package will be updated

Actual
An update is attempted on every project and an error is thrown when the package is not installed.

This behavior doesn't block anything, but it is a change from how update-package worked before

**Comment by yishaigalatzer** [comment]
@deepakaravindr this should have been fixed already?

**Comment by deepakaravindr** [comment]
@johnataylor, This bug will be fixed with your fix to not throw when updates are not available, right?

**Comment by deepakaravindr** [comment]
@johnataylor and I just verified that he has already fixed this, as part of another bug fix. Assigning this bug to him for tracking purposes
