### ISSUE TITLE
Microsoft.Nuget.Props should contain useful nuget properties.

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4060]
In Nuget 3.5x Microsoft.Nuget.Targets contains some useful properties like $(NuGetRuntimeIdentifier) and $(NuGetTargetMoniker) that could be useful for package authors to better hook into package creation and consumption.

The current use case I see for this is an in build detection of how to add items to a package. For instance, it looks like @kzu uses $(TargetFrameworkMoniker) etc. but this may not map 1-1 with the Nuget one since it uses custom logic for this.
 https://github.com/NuGet/NuGet.Build.Packaging/blob/ca91ebfada2e166ffe3a6bebe67e2073291e3023/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.targets#L290 

If the nuget ones were accessible it would be easier to make use of this and do something "smart"/integrated in the consuming .targets as well.

**Comment by kzu** [comment]
I see `$(NuGetTargetMoniker)` & friends still present under VS2017/NuGet4...

![nugetprops](https://cloud.githubusercontent.com/assets/169707/20931063/9993c0e2-bbae-11e6-9147-f45966842ba9.png)

**Comment by kzu** [comment]
I'd love to learn more about the smart-ness that you're thinking about based on that value, btw!

**Comment by bbowman** [comment]
@kzu @rrelyea 

Yes, I didn't mean to suggest that they are now missing in 4.0 ... The real issue is that they are exposed in a .targets that is included via the special MSBuild install folder ImportAfter area. This doesn't give the project files themselves the ability to make use of the properties defined there.

The smartness I'm thinking about is mostly related to making up for shortcomings in native package support in Nuget. As an example, I currently have a .dll and .lib (import lib) being placed in /runtimes/win10-x86-aot/uap/ inside my package (location determined from those variables as nugetizer chooses /lib/ instead of an architecture dependent runtimes folder). I need the consumer to be able to link against this so I need to add this path to the linker search directories. From MSBuild, I need to know what nuget thinks the consumer runtime and platform is reach into the right relative path of the package (vs say win10-arm/uap/) so that the correct .lib is picked up. I'm currently struggling a bit with the difference between consumer and producer in terms of a "compatibility matrix" (can win10-x86 consume win10-x86-aot etc) that nuget targets / tasks probably also handle somewhere in there. Exposing out these things would make the model more extensible.

**Comment by kzu** [comment]
>  This doesn't give the project files themselves the ability to make use of the properties defined there.

That is incorrect. They absolutely do, as far as they are imported. Any property/target defined anywhere imported by the csproj can be leveraged from the project file. Here is a plain MSBuild proj file importing the NuGet targets that showcases it, without even importing the MS Common targets:

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
		<TargetFrameworkVersion>4.6.2</TargetFrameworkVersion>
		<TargetFrameworkMoniker>.NETFramework,Version=v4.6.2</TargetFrameworkMoniker>
	</PropertyGroup>
	<Import Project="$(MSBuildExtensionsPath)\Microsoft\NuGet\15.0\Microsoft.NuGet.props" />

	<Target Name="Build">
		<Message Text="NuGetTargetMoniker: $(NuGetTargetMoniker)" Importance="high" />
	</Target>

	<Import Project="$(MSBuildExtensionsPath)\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" />
</Project>
```

Building this project yields this output:

```
Build:
  NuGetTargetMoniker: .NETFramework,Version=v4.6.2
Done Building Project "C:\Code\nugetmoniker.proj" (default targets).
```

**Comment by bbowman** [comment]
Yes you are correct. Again sorry for not being 100% clear. What you show works because you are in a target so the full property resolution has occurred. In my example use case, I was wanting to adjust the ItemDefinitionGroup for Link to include the AdditionalLibraryDirectories of the nuget package. This is the common pattern to do directly in the project file but I do understand I could potentially defer that by using a target that executes just before Link to "fixup" the link inputs to include this path. I suppose it may be just a difference of thinking like an "end user" that wants to adjust to the itemdefinitiongroup and a "library / package author" that wants to inject things. 

The fact that ItemDefinitionGroups have to be a top level item and can't be inspected from MSBuild is a different issue for a different time though. :-)

**Comment by emgarten** [comment]
This sounds related to: https://github.com/NuGet/Home/issues/3928

The plan is to write out properties to the generated .props file for PackageReference projects to expose some of what NuGet understands about the project. Examples: restore success (true/false), nuget version used, project style.

Target frameworks and RIDs could be listed also, but this is bit more difficult to support long term as projects move towards multiple TFMs and potentially different RIDs per TFM. Reading them yourself from the project file may be the best option.

**Comment by zhili1208** [comment]
close as dupe #3928
