### ISSUE TITLE
Add NuGet properties in target file for UWP projects

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4061]
We need to add following NuGet properties in a target file in order to support PackageReference for UWP project systems (except .net core)

```
<PropertyGroup>
    <NuGetTargetFramework Condition="'$(NuGetTargetFramework)'==''">$(TargetPlatformIdentifier),Version=v$(TargetPlatformMinVersion)</NuGetTargetFramework>
    <RuntimeIdentifiers Condition="'$(RuntimeIdentifiers)'==''">win10-arm;win10-arm-aot;win10-x86;win10-x86-aot;win10-x64;win10-x64-aot</RuntimeIdentifiers>
  </PropertyGroup>
```

As discussed offline, UAP team will be adding this property group in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppxPackage.Targets

**Comment by rrelyea** [comment]
Internal Bug 299177 - fixed on 12/13 - asking when next integration will make it to d15prerel

**Comment by rrelyea** [comment]
integrated into d15prerel
