### ISSUE TITLE
Documentation for NuGet.Client library

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#4062]
Hi. Is there any documentation for the [NuGet.Client library](https://www.nuget.org/packages/NuGet.Client/ )? If so, please would you add a link from the [readme](https://github.com/NuGet/NuGet.Client/blob/dev/README.md)?

Similarly for the [NuGet.PackageManagement](https://www.nuget.org/packages/NuGet.PackageManagement) library.

* * *

http://www.writethedocs.org/guide/writing/beginners-guide-to-docs/#why-write-docs

> You have written a piece of code, and released it into the world. You have done this because you think that others might find it useful. However, people need to understand why your code might be useful for them, before they decide to use it. Documentation tells people that this project is for them.
> 
> * If people don’t know why your project exists, they won’t use it.
> * If people can’t figure out how to install your code, they won’t use it.
> * If people can’t figure out how to use your code, they won’t use it.
>
> There are a small number of people who will source dive and use any code out there. That is a vanishingly small number of people, compared to people who will use your code when properly documented. If you really love your project, document it, and let other people use it.

**Comment by hickford** [comment]
A kind soul had the patience to dig into the code and write up their findings. Thank you!  https://daveaglick.com/posts/exploring-the-nuget-v3-libraries-part-1

> **There's almost no documentation about the new libraries** ...  It required a lot of digging through code and reverse engineering to get as far as I did. There could be much better ways to accomplish some of these tasks and some of my approaches might just be flat-out wrong

* * *

It's linked from https://docs.microsoft.com/en-gb/nuget/reference/nuget-client-sdk

> The NuGet v3 Client and NuGetGallery APIs are constantly evolving and we are working on having a stable surface area that we can document soon. In the meantime, you can find examples and documentation for some of the API in the following blog series by Dave Glick

**Comment by kraigb** [comment]
Work is in progress, see https://github.com/NuGet/docs.microsoft.com-nuget/pull/539.

**Comment by mishra14** [comment]
merged: https://github.com/NuGet/docs.microsoft.com-nuget/commit/49c3f58e65d62f0386c873debd741a7b6b1d1a2c

**Comment by hickford** [comment]
@mishra14 Where can I read the documentation? Please could you share a link?

**Comment by kraigb** [comment]
@hickford See https://docs.microsoft.com/en-us/nuget/api/overview.

**Comment by hickford** [comment]
> The NuGet API is a set of HTTP endpoints 

Hi @kraigb. That link documents the HTTP API. This issue concerns documentation for the NuGet.Client and NuGet.PackageManagement libraries (ie. the NuGet SDK).

Please reopen this issue.

**Comment by mishra14** [comment]
@hickford does https://docs.microsoft.com/en-gb/nuget/reference/nuget-client-sdk resolve what you are looking for?

**Comment by hickford** [comment]
@mishra14 I would like authoritative documentation for the NuGet Client SDK beyond a link to Glick's blog. As the page says...

> The NuGet v3 Client and NuGetGallery APIs are constantly evolving and we are working on having a stable surface area that we can **document soon**.

Please reopen this issue.

**Comment by kraigb** [comment]
I've transferred the issue to the NuGet docs issues backlog so this present issue can remain closed.
