### ISSUE TITLE
dotnet pack should pack tools with the versions that the package was built against

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4063]
This is for a situation where I have a library (or tool) that has a * dependency, like on Microsoft.DotNet.Cli.Utils: 1.0.0-preview4-*.

Today, the nuspec for this package gets generated with 1.0.0-preview4-, which means that when the tool gets restored, we end up with the lowest version of Cli.Utils, no matter what.

Instead, when the nuspec gets generated by pack, it should set the * versions to those in the project.assets.json file of the project being packaged.

I believe this used to be the behavior for project.json, so, in a way, we lost parity with it.

Also, we just hit this in the CLI itself and it was a bit of a pain to debug and understand all this.

cc @piotrp @emgartem @rrelyea

**Comment by davidfowl** [comment]
Yes that needs to work (pretty big regression otherwise)

**Comment by natemcmaster** [comment]
Is there any way we can workaround this in RC.2 bits? If not, this will likely cause major pain while trying to upgrade aspnet to vs2017. We liberally use floating versions e.g. `1.2.0-*`, but the nuspec contains `1.2.0--` on pack.

**Comment by natemcmaster** [comment]
Workaround for RC.2: add this to your project
```xml
    <Target Name="ResolveRestoredPackageVersions"
            BeforeTargets="GenerateNuspec"
            DependsOnTargets="ResolvePackageDependenciesDesignTime"
            Condition="'$(TargetFramework)'!=''">

        <ItemGroup>
            <_FloatingVersions Include="@(_PackageReferences)" Condition="$([System.String]::new('%(Version)').EndsWith('*'))" />
            <_ResolvedFloatingVersion Include="@(_FloatingVersions)">
                <ResolvedName>%(_DependenciesDesignTime.Name)</ResolvedName>
                <Version>%(_DependenciesDesignTime.Version)</Version>
            </_ResolvedFloatingVersion>
            <_PackageReferences Remove="@(_PackageReferences)" Condition="$([System.String]::new('%(Version)').EndsWith('*'))" />
            <_PackageReferences Include="@(_ResolvedFloatingVersion)" Condition="'%(Identity)'=='%(_ResolvedFloatingVersion.ResolvedName)'" />
        </ItemGroup>
    </Target>
```

**Comment by rrelyea** [comment]
@rohit21agrawal - please get your head around this. raised as a blocking issue by asp.net team. (note there is a workaround)

**Comment by rohit21agrawal** [comment]
@rrelyea  i already have a fix for this, this will be fixed in RC3.
