### ISSUE TITLE
Augment PackageReference with InstallPath metadata

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#4064]
Some packages may need to consume tools provided by other packages. One concrete example: ilmerge (the nuget package). That package provides the ILMerge.exe tool, but no MSBuild target to expose its location for other nuget packages to consume (or the project itself).

To avoid hardcoding versions (i.e. `$(NuGetPackageRoot)ILMerge\2.14.1208\tools\ILMerge.exe`) when invoking the tool, it would be great if the NuGet targets automatically augmented the `PackageReferece` with the determined version's install path, so that a consuming project could do, for example:

```
<ItemGroup>
    <ILMergeReference Include="%(PackageReference)" Condition="'%(Identity)' == 'ilmerge'" />
</ItemGroup>
<PropertyGroup>
    <ILMergePath>%(ILMergeReference.InstallPath)\tools</ILMergePath>
</PropertyGroup>
```

This mechanism may be useful for referencing other package's assets too, like samples, docs, etc.

Granted, this isn't impossible to solve today, by just modifying the package providing the tools so that it exposes a property for its own current location (i.e. ILMergePath property in an ilmerge.props), but this mechanism would make all package assets available reliably for anyone regardless of how well authored the package is.

**Comment by emgarten** [comment]
This would be really handy, but today NuGet has no rules for the format of the tools folder. It is just a place that NuGet doesn't read where authors can put things that the user needs to reference themselves. So trying to read this from existing packages would be difficult I think, for example if there were multiple exes like in xunit console runner it would be unclear what properties to create.

Do you think it would work to have generic helpers in MSBuild for working with NuGet packages? If you could get the root path of the package version that NuGet used from the package id, you could then just append the rest of the path as needed.

**Comment by kzu** [comment]
Well, I think just including the root install path for the package is enough. The author's/consumers can figure out how to chdir into tools or whatever.

Updated the example XML to showcase that the install path should be the root. I can figure out to to under tools myself of course.

**Comment by kzu** [comment]
More examples where this is generally useful but package authors have to manually provide this:

* https://github.com/gluck/il-repack/pull/192
* https://github.com/dotnet/symreader-converter/issues/88

I'd like at least the InstallPath to be present so that via MSBuild you can reach artifacts inside installed packages without resorting to hacks or PRs to package authors ;)

**Comment by rrelyea** [comment]
Closing...as the approach in this issue feels better=: https://github.com/NuGet/Home/issues/5975
and Dupe like.
