### ISSUE TITLE
Unknown parameter should be treated as error

### ISSUE THREAD

**Issue by ShadowDancer** [NuGet/Home#4065]
NuGet product used: NuGet.exe

NuGet version: 3.4.4.1321

OS version: win10 v1607

## Detailed repro steps so we can see the same problem

1. Open console

2. execute: `nuget restore dsgfasd asdf`

3. execute: `echo %errorlevel%`

Result:
```
>nuget restore dsgfasd asdf
restore: invalid arguments.
usage: (...)

>echo %errorlevel%
0
```

Comand failed to restore, because it got unknown paremeter. It may happen if You forget to put path in quotation marks. In my opinion it should return code > 0 to indicate error, and/or print something to stderr, because this is not success.

**Comment by nkolev92** [comment]
Testing today, it returns 1. 

Closing.
