### ISSUE TITLE
Feature Request: Enhance support for Management Pack projects (mpproj)

### ISSUE THREAD

**Issue by mfaulkinbury** [NuGet/Home#4068]
[System Center Visual Studio Authoring Extensions](https://www.microsoft.com/en-us/download/details.aspx?id=30169) adds support for developing Management Packs using Visual Studio.

![nuget4scom](https://cloud.githubusercontent.com/assets/9920907/12152282/5e2c829c-b479-11e5-9450-d9250d6eb7dc.PNG)

Previously, [support was added](https://github.com/NuGet/Home/issues/1888) to **enable (unlock)** NuGet for Management Pack projects, with the majority of the work relying on NuGet support for target/props, lib, and content files, which works fine for install and uninstall - _not so much for update_. 

### As a Management Pack author, I would like to leverage NuGet to manage Management Pack (MP) and Management Pack Bundle (MPB) references with the same user experience as is found when using NuGet to management assembly references in a C# project.

I would be happy to submit a pull request for this feature.

Best,
Mike

**Comment by rrelyea** [comment]
@yishaigalatzer and I will need to discuss post vacation.

**Comment by rrelyea** [comment]
@mfaulkinbury - We would be happy to take a pull request here.

**Comment by toddmeinershagen** [comment]
@rrelyea @yishaigalatzer I would like to add end to end testing around the Management Pack project template (ManagementPack_2012R2.zip shown below) and run the tests locally to validate.  I have added the folder with the associated artifacts to the \test\EndToEnd\ProjectTemplates directory.  

* What tests specifically target this functionality and what do I need to pass to the .\runTests.ps1 at the root of the project to make them run?  Is there another low level PowerShell script I need to run instead?
* Are these tests able to be run locally or do they require connectivity to the Microsoft corpnet as mentioned in the notes of the runTest.ps1 script?  If not, do you recommend that we issue this change as a pull request and have your group run the tests before merging the changes into the origin/develop branch?


![project-template-snapshot](https://cloud.githubusercontent.com/assets/177508/22523064/a760a5e4-e883-11e6-9b80-0bce75d59175.PNG)

**Comment by mfaulkinbury** [comment]
@rrelyea @yishaigalatzer @toddmeinershagen 
[PR](https://github.com/NuGet/NuGet.Client/pull/1192) added.

Please provide feedback and requests for changes at your earliest convenience.  

Note: we took care not to break the build when [Visual Studio Authoring Extensions](https://www.microsoft.com/en-us/download/details.aspx?id=30169) (VSAE) is not installed, but **we do require that VSAE is installed on the build servers** in order to achieve the requirement.

**Comment by mfaulkinbury** [comment]
@rrelyea @yishaigalatzer 

Please provide an update on the status of this PR.

**Comment by mfaulkinbury** [comment]
@rrelyea @yishaigalatzer

Just fetched the latest and resolved conflict with base.
Please provide an update on the status of this PR.

**Comment by mfaulkinbury** [comment]
@rrelyea @yishaigalatzer

Given that another month has passed since my last request for an update on the status of this PR, we are likely to create a public distro for those in the community who would like to benefit from our work.

We will continue to hope for a response, a request for changes to our PR, a friendly, "we're just busy right now", ...

**Comment by zhili1208** [comment]
unfortunately we can't take this PR. The right approach for this issue is NuGet should have new project system extensibility for new project system support #6046
