### ISSUE TITLE
NuGet.exe push from ASP.NET

### ISSUE THREAD

**Issue by william-gross** [NuGet/Home#4070]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 3.4.4

OS version: Windows 10 Pro (10.0.14393 Build 14393)

Worked before: Yes, with v2.8.6

## Detailed repro steps so we can see the same problem

I have a continuous integration workflow that includes pushing packages to a private MyGet feed, from ASP.NET running in IIS as the NETWORK SERVICE account (i.e. the IIS application pool uses NetworkService as the identity). I perform the push by using Process.Start and calling NuGet.exe with -ConfigFile and also a -Source that I've preconfigured in the ConfigFile with the MyGet username and password.

This works fine in NuGet.exe version 2.8.6. But it does NOT work in NuGet.exe v3.4.4. Here is what I see:

> Pushing abc.nupkg to 'https://www.myget.org/F/enduracode/'…

Then I receive this error output:

> Failed to read NuGet.Config due to unauthorized access. Path: 'c:\windows\system32\inetsrv\NuGet\NuGet.Config'.
> Access to the path 'c:\windows\system32\inetsrv\NuGet' is denied.

There is no `NuGet.Config` at that location nor should there be (by the way, that is the path of the IIS executable, which I suspect is why NuGet is looking there). But I have spent hours and can't get NuGet to stop trying to access that path.

According to your documentation at https://docs.nuget.org/ndocs/consume-packages/configuring-nuget-behavior#how-settings-are-applied , using the -ConfigFile switch "overrides [config] merging". This is not the behavior I am seeing.

**Comment by zhili1208** [comment]
Please try nuget.exe 4.3.0 from https://www.nuget.org/downloads, if it still repro, feel free to reopen it

**Comment by william-gross** [comment]
@zhili1208 This issue is not fixed; I just reproduced it again with nuget.exe 4.4.1. The error output is exactly the same. Please reopen.
