### ISSUE TITLE
Update-Package -Safe skips patch versions

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4075]
## Details about Problem
NuGet PMC
NuGet version: 4.0.0.2098
VS version: 15.0.26008.0
OS version: win10

## Repro

1. Create this .NET Core project 
    ```xml
    <Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.0</TargetFramework>
      </PropertyGroup>
      <ItemGroup>
        <Compile Include="**\*.cs" />
        <EmbeddedResource Include="**\*.resx" />
      </ItemGroup>
      <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.0" />
        <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
      </ItemGroup>
    </Project>
    ```
2. Open PMC and execute `Update-Package -Safe Microsoft.AspNetCore.Mvc` (also happens with `Update-Package Microsoft.AspNetCore.Mvc -ToHighestPatch`)

## Expected
Updates to Microsoft.AspNetCore.Mvc 1.0.0 => 1.0.1

## Actual
Updates to Microsoft.AspNetCore.Mvc 1.0.0 => 1.1.0

**Comment by zhili1208** [comment]
I can repro this issue with NuGet 4.4

**Comment by rohit21agrawal** [comment]
@AbdallahAbuHashem
