### ISSUE TITLE
Can we skip the NuGet installation of Windows platform in the Xamarin NuGet package

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#4078]
Hi,

I have create the custom Xamarin NuGet package with don't give the support for the Windows 8, Windows 8.1, WinRT. 

I am using the below lib folder structure for the package.

![image](https://cloud.githubusercontent.com/assets/16695209/21037360/3eec71a6-bdf3-11e6-9947-f2059ed485b8.png)

Then I tried to installed the package in the Xamarin project with select the Windows and Windows Phone checkbox, 

![image](https://cloud.githubusercontent.com/assets/16695209/21037473/1a7d2b0c-bdf4-11e6-9f37-8261026c23e3.png)

I faced the below error,
**Could not install package ''. You are trying to install this package into a project that targets 'Windows,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework.**

Then I tried to uncheck the Windows and Windows phone option the package installed successfully.

![image](https://cloud.githubusercontent.com/assets/16695209/21037481/26d2e6bc-bdf4-11e6-8752-1c05aeb19447.png)

Can we install the package with select the option Windows and Windows phone since we don't have the support for the windows? If yes Please suggest me how can I do that?

Thanks,
Ganesan R.

**Comment by zhili1208** [comment]
there is no way to install incompatible package to the project.
