### ISSUE TITLE
When a package version does not exist, NuGet throws "Missing Package Dependency information" error 

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#408]
When a package version does not exist, NuGet throws "Missing Package Dependency information" error 
It should be 'Package is not found' error

**Comment by RussianDragon** [comment]
Та же проблема на Windows 10, при наличии в Solution MVC Project на Fraemwork 4.5

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet3@9ee4da4646ede0370bd794e5bc63e763b9422f79

The new message is: Unable to find package '{0}'. Existing packages must be restored before performing an install or update.
