### ISSUE TITLE
Package restore does not correctly restore packages with a version of x.0.0.0

### ISSUE THREAD

**Issue by slowcelica** [NuGet/Home#4081]
Remove the content above here and fill out details below.

## Details about Problem
NuGet.exe 

NuGet version (3.4.4.1321):

VS version (visual studio 2015, TFS 2015):

OS version (win server 2012)):

Worked before? If so, with which NuGet version: 3.2

## Detailed repro steps so we can see the same problem

1. If building a visual studio project in TFS 2015, and you are using a nuget package whose version is 1.0.0.0, when the package is restored it will place it in a folder named MyPackage.1.0.0.0 where tfs and visual studio expect the package to be in folder name MyPackage.1.0.0 and cannot find the package.

**Comment by rrelyea** [comment]
believe there was a change in 3.4.0 for this - see issue: https://github.com/NuGet/Home/issues/2298

**Comment by slowcelica** [comment]
I am currently using 3.4 of nuget.exe and that is the machine it is happening on. We recently updated to this from 3.2, to fix a different issue where packages were not found in the server. 

The package in question downloads successfully and restores correctly using the 3.2 exe, but not with the 3.4 exe.

**Comment by zhili1208** [comment]
Please try nuget.exe 4.3 from https://www.nuget.org/downloads, if it still repro, feel free to reopen
