### ISSUE TITLE
Unable to install pagedlist in VS 2015 CE

### ISSUE THREAD

**Issue by haranblazer** [NuGet/Home#4087]
Hi Team,

I am trying to install PagedList.MVC using nuget in visual studio 2015 community edition 
and i get an error message that
Error downloading 'PagedList.1.17.0' from 'https://api.nuget.org/packages....

Please help what should I do

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
