### ISSUE TITLE
VS 2015 client has poor performance

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#4088]
The way the VS extension is designed is leading to poor performance. For example when doing consolidation across a multi-project solution, the GUI list of packages that appears (with their respective icons) gets cleared after consolidating a single package.

If I have several packages to address then the GUI is redrawn from scratch over and over. Why is this a problem? because it also seems to go back to the network to get the list of packages AGAIN, each time!

Ideally it would just remove the entry that corresponds to the package that I've just updated to, then the remaining list would not need to be redrawn.

I'm currently on a slow (DSL) network connection and this needless repetitive network traffic over and over and over is costing huge time.

Surely if you're using WPF for the GUI list (some form of StackPanel ?) it should be easy to dynamically remove the one element in the list without having to redraw (and it seems reprobe the network).

**Comment by rrelyea** [comment]
Appreciate the report. Can you please give us some repro steps, so when we can look at this, we'll have the appropriate info to start with?

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
