### ISSUE TITLE
Travis CI, mono, pushing to MyGet: SendChunked should be true.

### ISSUE THREAD

**Issue by kierenj** [NuGet/Home#4090]
## Details about Problem

Suddenly, `SendChunked should be true.`

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 3.5.01938

dotnet.exe --version (if appropirate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Travis CI

Worked before? If so, with which NuGet version: Yes,3.4.4 works fine, confirmed!  This is new with 3.5.0

## Detailed repro steps so we can see the same problem

1. Push to custom MyGet feed

### Verbose Logs

```

NuGet Version: 3.5.0.1938
Pushing RedRiver.SaffronCore.0.2.0-alpha1-999000146.nupkg to 'https://www.myget.org/F/redriversoftware/api/v2/package'...
  PUT https://www.myget.org/F/redriversoftware/api/v2/package/
An error was encountered when fetching 'PUT https://www.myget.org/F/redriversoftware/api/v2/package/'. The request will now be retried.
SendChunked should be true.
  PUT https://www.myget.org/F/redriversoftware/api/v2/package/
An error was encountered when fetching 'PUT https://www.myget.org/F/redriversoftware/api/v2/package/'. The request will now be retried.
SendChunked should be true.
  PUT https://www.myget.org/F/redriversoftware/api/v2/package/
System.AggregateException: One or more errors occurred. ---> System.Net.ProtocolViolationException: SendChunked should be true.
  at System.Net.HttpWebRequest.BeginGetRequestStream (System.AsyncCallback callback, System.Object state) [0x00000] in <filename unknown>:0 
  at System.Threading.Tasks.TaskFactory`1[System.IO.Stream].FromAsyncImpl (System.Func`3 beginMethod, System.Func`2 endFunction, System.Action`1 endAction, System.Object state, TaskCreationOptions creationOptions) [0x00000] in <filename unknown>:0 
```

### MyGet

They have confirmed nothing has changed their end

**Comment by kierenj** [comment]
Anything I can do to help / start digging?

**Comment by maartenba** [comment]
Looks like breaking client behaviour... Just tried this as well, works fine in 3.4.4

Seems to be coming from here: https://msdn.microsoft.com/en-us/library/d4cek6cc(v=vs.110).aspx or from Mono-specifics. Similar issue in Raven: https://groups.google.com/forum/#!topic/ravendb/cmG9BkrWyoM where this was the workaround on Mono: https://groups.google.com/d/msg/ravendb/cmG9BkrWyoM/tugBRl82W8kJ

**Comment by zhili1208** [comment]
Please try nuget.exe 4.3 from https://www.nuget.org/downloads, if it still repro, feel free to reopen
