### ISSUE TITLE
NuGet.exe push doesn't work for vsts [turns out it does, but there are a few related issues]

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4093]
tried nuget.exe 2.12, 3.3, 3.4, 3.5, dev. got same result.

Repro step:
1. set up a vsts package feed, put PAT into nuget.config.
2. nuget.exe push [package] -source vstsfeed
On windows, got 400 bad request.
On mac, with mono, got 400 bad request.
On mac, dotnet nuget push, got 401.

**Comment by infin8x** [comment]
Note on 2, the bad request is likely due to a missing -ApiKey vsts in your push command.

**Comment by zhili1208** [comment]
Yes, On windows, by providing -ApiKey vsts, push will work. 
For dotnet nuget push, create a nuget.config which contains PAT in current directory, push will work. 
Mono still doesn't work

**Comment by zhili1208** [comment]
Opened related: #4095 Dotnet nuget push can't find credentail from global nuget.config

**Comment by zhili1208** [comment]
THis turns out to be working fine.
The mono problem remains and is tracked by: https://github.com/NuGet/Home/issues/3251
