### ISSUE TITLE
Dotnet nuget push can't find credential from global nuget.config

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4095]

**Comment by zhili1208** [comment]
the issue here is 
Mono Appdata folder is /[username]/.config/
Dotnet Appdata folder is /[username]/.nuget/

so when we use mono nuget.exe to add credential, it will add them to /[username]/.config/NuGet/NuGet.Config

but dotnet push try to get credential from /[username]/.nuget/NuGet/NuGet.Config

that's why dotnet can't find credential.

Workaround is 
Mono nuget.exe add credential by 
Using -ConfigFile to specify the config file path : /[username]/.nuget/NuGet/NuGet.Config

**Comment by rrelyea** [comment]
Moving to post-4.0

**Comment by sartan** [comment]
For the time being, this inelegant workaround seems to do the trick:

`ln -s ~/.nuget/NuGet ~/.config/Nuget`

**Comment by nkolev92** [comment]
Closing as duplicate of https://github.com/NuGet/Home/issues/4413. 
https://github.com/NuGet/docs.microsoft.com-nuget/issues/2822 and https://github.com/NuGet/Home/blob/dev/designs/Consolidate-NuGetConfig_OnLinux.md have details.
