### ISSUE TITLE
Rename buildCrossTargeting/ folder to buildMultiTargeting/

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#4098]
See https://github.com/dotnet/sdk/issues/486. We've decided to use MultiTargeting everywhere.

We need to figure out how to make the transition. Should we accept both for some grace period? Is it possible to find out the full set of packages on nuget.org that are affected?

@rrelyea 

cc @mhutch

**Comment by rrelyea** [comment]
@emgarten - let's strategize on the best way
@mishra14  - can you please do a search (on packages published up to today) with any buildCrossTargeting directory in the .nupkg

**Comment by emgarten** [comment]
NuGet can support both folder names for a time.
