### ISSUE TITLE
[Test Failure] Fail to update package in C# .NET Standard Class Library App with an error

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4104]
**NuGet Version:** NuGet 4.0.0-RC3-2130
**VS Version:** D15PreRel 26013.05
**OS Version:** Windows 10 RS1_Release 14393.607.161209-1855

**Repro Steps:**
1.	New a Visual C#->.NET Core->**Class Library (.NET Standard)** template.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Click ‘Updates’ tab, select a package and click update button.

**Expected Result:**
The package updated successfully.

**Actual Result:**
Fail to update the package with an error showing in error list as below screenshot.
![classlibrary](https://cloud.githubusercontent.com/assets/20632625/21175520/a0fe0cbe-c21d-11e6-9c9f-41bf9a5ac10a.png)
**Note:**
1. I can repro it on D15Rel 26009.00 and D15PreRel (NuGet Client 4.0.0-RC2-2098) for the first time. But it gone after updating for several times. Nancy and Andy never met it (that's weird).
2. I can repro it with the same scenario in the updating of **C# .NET Core Web Application** package.
3. It doesn't repro with "update-package" command in PMC, just repro on PM UI.

**Comment by zhili1208** [comment]
doesn't repro in VS 15.4
