### ISSUE TITLE
Condition is not considered by Update-Package with multi TargetFrameworks

### ISSUE THREAD

**Issue by yyjdelete** [NuGet/Home#4105]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `Package Manager Console`

NuGet version (x.x.x.xxx): `4.0.0.2098`

dotnet.exe --version (if appropirate):`1.0.0-preview4-004233`

VS version (if appropriate):`VS2017 RC.2(15.0.26009.0)`

OS version (i.e. win10 v1607 (14393.321)):`win10 v1607 (14986.1000)`

Worked before? If so, with which NuGet version: None

## Detailed repro steps so we can see the same problem

1. `Update-Package Microsoft.NETCore.App`

2. Update Failed

...

## Other suggested things

The same thing works well with `VS UI`(the version bundled with VS).

### Verbose Logs

```
Update-Package : Package Microsoft.NETCore.App 1.1.0 is not compatible with net452 (.NETFramework,Version=v4.5.2). Package Microsoft.NETCore.App 1.1.0 supports: netcoreapp1.0 (.NETCoreApp,Version=v1.0)
```
Not tested with NuGet.exe.

### Sample Project

```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net452</TargetFrameworks>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.0'">
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
  </ItemGroup>
</Project>
```

**Comment by zhili1208** [comment]
Close as not repro, Please try Visual Studio 2017 15.4, if it still repro, feel free to reopen it
