### ISSUE TITLE
Additional configuration options for specifying dependency versions when using IncludeReferencedProjects

### ISSUE THREAD

**Issue by chrisalexander** [NuGet/Home#4106]
## Details about Problem

NuGet product used NuGet.exe

NuGet version (3.5.0.1938):

dotnet.exe --version (if appropirate): (not appropriate)

VS version (if appropriate): (not approproate)

OS version (i.e. win10 v1607 (14393.321)): Win10 v1511 10586.545

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create two projects, one of which has a reference to the other, e.g. Project A has a reference to Project B 

2. Create nuspec files for both projects

3. Use Nuget to pack Project A with the -IncludeReferencedProjects flag

4. Nuget package produced has a dependency on the exact version of the project

Ideally you would be able to specify an option such as having a dependency on the major and minor but not patch versions, or major only.

With the current scenario, if you were to update Project A to a new version and ship that nuget package, you would _also_ have to ship Project B (even if it had not changed) with the same version number, otherwise the prerequisite can't be fulfilled.

Clearly it is possible to deploy Project B if you only increment the patch version number, but given SemVer then you would want to also ship Project A without Project B assuming only a patch version change - basically I am asking to have that option available (probably not by default).

**Comment by zhili1208** [comment]
please use msbuild /t:pack in developer CMD to Pack Project A and specify Project B major and minor version as a msbuild property from commandline
