### ISSUE TITLE
Unfathomable

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#4108]
Once again I find NuGet support in Visual Studio (2015) very poor, how Microsoft are adopting this as a backbone system is beyond me.

Here's a message I got when trying to update to the latest versions of some internal packages:

_Unable to find a version of 'Ncu.Common' that is compatible with 'Ncu.Common.Data 2.0.48 constraint: Ncu.Common (>= 1.1.0)', 'Ncu.Common.GradeAppeals 1.0.4.1 constraint: Ncu.Common (>= 1.2.1)', 'Ncu.Component.CourseExtension 1.0.60 constraint: Ncu.Common (>= 1.1.0)', 'Ncu.Component.Schools 1.0.38 constraint: Ncu.Common (>= 1.1.0)', 'Ncu.Service.Rest.Common 1.0.3.2 constraint: Ncu.Common (>= 1.1.0)'._

Now this may be technically correct but it is to say the least bewildering, clearly NuGet is unhappy with something but offers no way to visualize or grasp the actual issue.

I'm looking at an older, large solution and I know it has problems and some of this is not NuGet's fault, but the tooling and extensions are far too weak, it is very very hard to understand what I must do to fix this solution.

I'm also seeing various cases of references not being found (yellow alert icon in the proj references tree). Yet the DLL does exist and the project file's hint path points to the correct path, so what does it tell me?

The referenced component 'Dapper' could not be found? But it's there! and the project file path seems correct !

By trial and error I find that adding <SpecificVersion>False etc enables the reference to be found, but NuGet itself provides no help, no suggestions or anything.

Once again you seriously need to add some analysis/consistency too - if I could have some tool explore the solution tree and report everything that wrongs or suspicious then it would help, as things stand it's opaque and despite fifteen years of in-depth .Net experience I'm struggling to get this sorted out !

Thx

**Comment by emgarten** [comment]
> Ncu.Common (>= 1.2.1)

Does version 1.2.1 of Ncu.Common exist in one of your internal sources?

> I'm also seeing various cases of references not being found (yellow alert icon in the proj references tree). Yet the DLL does exist and the project file's hint path points to the correct path, so what does it tell me?

This part is handled by Visual Studio. NuGet adds a reference to the project file, it sounds like other problems are preventing it from being resolved correctly here.

**Comment by zhili1208** [comment]
No response, close it
