### ISSUE TITLE
nuget.exe package my.nuspec -symbols excludes content and tools from symbols package

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#4110]
This seems weird. Shouldn't the symbols package be a superset of the original package?

Why are `tools` and `content` treated special?

https://github.com/NuGet/NuGet.Client/blob/fc119198b72255267879ec0f2c3f9748de7d357c/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L57-L60

**Comment by zhili1208** [comment]
I think symbol package is only used by symbol server for debugging, adding content and tools make no sense for this scenario, close it as by design
