### ISSUE TITLE
VSFeedback: Restore errors can obscure more complete error messages that build could give

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4113]
VSFeedback: https://developercommunity.visualstudio.com/content/problem/4056/build-errors-are-not-displayed-as-errors-in-case-o.html

Internal bug with data from Roslyn team: 296518

If you try to build and run a project (.NET 4.0) which references 4.5 assemblies, you get the status message "errors while building". However, the error log remains completely empty. Only if you make the warning list visible, you will see warnings like

Warnung Der primäre Verweis ".." konnte nicht aufgelöst werden, da er indirekt von Assembly "..." abhängig ist, die anhand des ".NETFramework,Version=v4.5.2"-Frameworks erstellt wurde. Dabei handelt es sich um eine höhere Version als das aktuelle Zielframework ".NETFramework,Version=v4.0". 

Warnung Failed to resolve all project references. The package restore result for '....csproj' or a dependant project may be incomplete.

The actual error should be communicated as error and not hidden among a list of warnings.

**Comment by emgarten** [comment]
The warning here is actually not the issue, the 4.0 compatibility error looks to be the correct message.

NuGet/NuGet.Client@c29b08a049252972361e0e5f4dc159120bdd2d3d
