### ISSUE TITLE
Is NuGet supported for use outside of Visual Studio?

### ISSUE THREAD

**Issue by NReilingh** [NuGet/Home#4115]
I'm a SQL Server DBA and find myself in need of a package management solution. I've been trying to learn as much as I can about NuGet. The introductory material I found at places like Pluralsight seemed to indicate that, while there was a GUI plugin for NuGet in Visual Studio, the command line tools could be used outside of VS. I spend most of my time in SSMS, and while I recognize that NuGet GUI tools are not going to be available, I presume that there shouldn't be anything stopping me from just using the command line tools to restore packages to the file system inside the git repository containing my SSMS solution.

So long story short, I've figured out how to do this just using the command line tool, a local filesystem package feed, self-created packages, and a handmade packages.config. But now I'm starting to worry that my introductory material was a bit out of date, pre version 3 of NuGet.

The documentation currently contains a [schema document for project.json](http://docs.nuget.org/ndocs/schema/project.json), indicating that it mostly(/entirely?) replaces packages.config, and I can find no similar documentation for creating a packages.config by hand. Realizing this, I set about to recreate my setup using a project.json instead of a packages.config. But, I reach an error that the project.json file does not specify any target frameworks: not a sensible question in the context of SQL Server.

So: is packages.config deprecated as of NuGet 3, or heading that way? If not, shouldn't there be documentation for editing a packages.config by hand? Can a project.json file be used outside the context of Visual Studio?

**Comment by emgarten** [comment]
@NReilingh take a look at https://github.com/NuGet/Home/issues/4066

**Comment by zhili1208** [comment]
Project.json is dead and packages.config is deprecated. Please use Package Reference for nuget.https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
