### ISSUE TITLE
dist.nuget.org download urls are case sensitive and inconsistent across versions

### ISSUE THREAD

**Issue by AGBrown** [NuGet/Home#4117]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: various

## Detailed repro steps so we can see the same problem

When downloading from `https://dist.nuget.org/win-x86-commandline/<version>/NuGet.exe`, the package naming is inconsistent with regard to case, but the web server is case sensitive. It is not possible therefore to write a simple script which can take a version parameter and insert it into the download url. For example, taking the most recent three versions and "latest" from https://dist.nuget.org/index.html

| version | Pascal case | Lowercase |
| --- | --- | --- |
| latest | ✘ [latest NuGet.exe](https://dist.nuget.org/win-x86-commandline/latest/NuGet.exe) | ✓ [latest nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) |
| v3.5.0 | ✓ [v3.5.0 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.5.0/NuGet.exe) | ✘ [v3.5.0 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.5.0/nuget.exe) |
| v3.4.4 | ✓ [v3.4.4 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe) | ✘ [v3.4.4 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe) |
| v3.3.0 | ✘ [v3.3.0 NuGet.exe](https://dist.nuget.org/win-x86-commandline/v3.3.0/NuGet.exe) | ✓ [v3.3.0 nuget.exe](https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe) |

## Suggestion for Fix

1. make the web server handler for nuget.exe download links case insensitive
1. if that is not possible then:
     - Future uploads to dist.nuget.org should be automated to ensure consistency
     - Both the lower and pascal case versions of all existing and future nuget.exe versions should be uploaded - standardising to lowercase will simply break things for half the nuget world and vice versa

And on a slightly flippant ending: it's lowercase in the text on the page at https://dist.nuget.org/index.html; the case varies in the download links; the case is pascal case in the page's title; and it is lowercase in the logo for nuget. I don't think there are [enough standards here](http://xkcd.com/927/). Maybe we should adopt nUgET?

**Comment by emgarten** [comment]
@AGBrown Thanks for pointing this out and the table of version casings. We'll investigate to see how this could be improved/fixed on dist.

//cc @skofman1 @joelverhagen

**Comment by joelverhagen** [comment]
dist.nuget.org is living directly on Azure blob storage which has case-sensitive URLs. Thanks for the report @AGBrown. I'm going to move this to the server-side bug tracker so the server team has better visibility.

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #3426](https://github.com/NuGet/NuGetGallery/issues/3426) via [**ZenHub**](https://www.zenhub.com/)
