### ISSUE TITLE
Writing a nuget aggregator

### ISSUE THREAD

**Issue by georgiosd** [NuGet/Home#412]
Hey all,

I've been crawling the web for a Nuget aggregator/proxy/server that will allow me to define security access on a package-level (e.g. department A can view/download packageA but not packageB) and when you add "free" to that, you get nothing. 

The repositories have changed a lot in relation to any relevant articles I could find (most of them referencing Nuget.Server) so I would appreciate some help.

How does one go about writing a Nuget aggregator?

Thank you

**Comment by maartenba** [comment]
I am not aware of any free or commercial solution offering package-level security. I do know ProGet and MyGet have connectors (or upstream feeds) where you can go wild with security configuration, but always at the feed level.

Check http://docs.nuget.org/Contribute/Ecosystem for an overview of available NuGet servers.

**Comment by georgiosd** [comment]
@maartenba thank you for the response - where can I find the `Nuget.Server` source nowadays? I can't seem to find a Github repo for it

**Comment by maartenba** [comment]
That one's still at http://nuget.codeplex.com
