### ISSUE TITLE
Hashing support for targets/props

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4120]
Checking if targets/props files have changed is currently done with simple string comparisons. This should be done by hashing the files instead or comparing the XML if possible.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/ca008ff53cd941d31cba2052c1fcf4c31770b294#diff-5bb386c4605ebbdd93f9449128236078.

We use XDocument equals instead
