### ISSUE TITLE
Nuget 3.4.x failed when Windows use an Hebrew Date on Regional Settings

### ISSUE THREAD

**Issue by MosheL** [NuGet/Home#4121]
I was suspect that the #2798   is on IIS, you was suspect hebrew Windows, I was tried a diffrent user account and I was foud on the end:

Hebrew Date (on Regional settings)

I was switched to Gregorian date, and then the NuGet was started working. the other user account on the same machine did not use the Hebrew Calendar.
I suspect the `"` is the problem, as the current date is י"ז כסלו תשע"ז. this can't be a filename,

![image](https://cloud.githubusercontent.com/assets/2265043/20984973/194eda5c-bccb-11e6-8804-9285df5cad83.png)

**Comment by MosheL** [comment]
something new?

**Comment by zhili1208** [comment]
Please try nuget 4.3 in Visual Studio 2017, close it, if it still repro with 4.3, feel free to reopen

**Comment by MosheL** [comment]
Executing nuget actions took 12.86 sec
Time Elapsed: 00:00:17.5303116
========== Finished ==========

VS 2015.3, nuge  4.3.1.4445
Thanks !
