### ISSUE TITLE
NuGet package references can't influence NuGet package build for VS2017 SDK builds

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4123]
When I have a `PackageReference` in my msbuild project that includes msbuild imports, they are imported with xml such as this:

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(NuGetPackageRoot)' == ''">
    <NuGetPackageRoot>$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
  </PropertyGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'net46' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)nerdbank.gitversioning\1.5.64-g355c5a8de9\build\NerdBank.GitVersioning.targets" Condition="Exists('$(NuGetPackageRoot)nerdbank.gitversioning\1.5.64-g355c5a8de9\build\NerdBank.GitVersioning.targets')" />
  </ImportGroup>
  <ImportGroup Condition=" '$(TargetFramework)' == 'netcoreapp1.0' AND '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)nerdbank.gitversioning\1.5.64-g355c5a8de9\build\NerdBank.GitVersioning.targets" Condition="Exists('$(NuGetPackageRoot)nerdbank.gitversioning\1.5.64-g355c5a8de9\build\NerdBank.GitVersioning.targets')" />
  </ImportGroup>
</Project>
```

But this means my imports are only imported on the target framework compilation builds. In particular, they are _not_ imported for the `Pack` target, which runs on the original project where `$(TargetFramework)` has been set. 

This makes it impossible to set the `PackageVersion` or `Version` properties from a NuGet package. Unless there is some way for a NuGet package to opt-in to providing imports to the project without target framework conditions.

VS 2017 RC: build 26014.00 (d15rel)

**Comment by emgarten** [comment]
@AArnott copy your targets file to ``buildCrossTargeting\NerdBank.GitVersioning.targets``

``buildCrossTargeting`` is used for the outer build.
``build`` is used for the TFM specific inner build.

I'm not sure if bringing this in through a package will work long term. NuGet evaluates the project version at restore time before packages have been downloaded. If a package changes the identity or dependencies of a project restore would need be run a second time. *ExcludeRestorePackageImports* set during restore ensure that all restores will give the same result as cloning a new repo and running restore.

There have been several asks for supporting packages like this, but is unclear how it could work without restoring special tool packages first and then starting MSBuild again and running the regular restore. Do you have any ideas on it?

**Comment by AArnott** [comment]
Thanks. I'll try the `buildCrossTargeting` approach.

How would the project/package Version impact package restore? Whether my project is version 2.0, 3.0, or 3.0-beta5, I would expect restore results to be equivalent. So if one of those packages, being restored, changes the version of the importing project, I fail to see the problem.

**Comment by AArnott** [comment]
@emgarten just to follow up, using `buildCrossTargeting` worked for me. 

[Nerdbank.GitVersioning 1.5.62](https://github.com/AArnott/Nerdbank.GitVersioning/releases/tag/v1.5.62) has the fix, and a workaround till https://github.com/NuGet/NuGet.Client/issues/1064 is merged.
