### ISSUE TITLE
NuGet hates Git submodules that use NuGet

### ISSUE THREAD

**Issue by SuperJMN** [NuGet/Home#4124]
OK, here's a nasty problem I'm facing, and I'm well aware that I'm not the only one (http://stackoverflow.com/questions/18609333/nuget-package-restore-with-git-submodule).

**The situation:** I'm using Git submodules to include code from third parties. My submodules are using NuGet packages themselves. 

During the build, NuGet tries to restore all the packages in my solution, including the ones from the submodules.

**The problem:** After the restore, every project that targets the full .NET Framework and has a dependency on a NuGet package **has their references broken**.

The only exception for me are the projects that are targeting .NET Standard.

Please, fix this, since modifying the HintPath for the projects in the submodules is just a bad hack.

**Comment by clairernovotny** [comment]
The only real solution to this is to use either `project.json` on those projects or the new `PackageReference` in VS 2017. The former will work on VS 2015 as I describe here: https://oren.codes/2016/02/08/project-json-all-the-things/

The "legacy" way that uses `packages.config` just can't handle this scenario (among many others).

**Comment by SuperJMN** [comment]
@onovotny Cool!! Does the new `PackageReference` work for Desktop applications (and others that use the full .NET Framework)? 

Thank you so much!

**Comment by clairernovotny** [comment]
@SuperJMN I believe that's the eventual goal but you'd have to ask one of the NuGet team @emgarten @rrelyea @yishaigalatzer about what the current status is in other project types. You can always try and see if it works :)

Just manually add a `<PackageReference>` before there's any `packages.config` or `project.json` file and see what happens.

**Comment by yishaigalatzer** [comment]
Yes, oren is right. We are not planning to fix the packages.config scenario. This is one of the main reason we introduced project.json and in 2017 packagereference

**Comment by SuperJMN** [comment]
Big thanks, @onovotny!
