### ISSUE TITLE
Install-Package results in error dialog in VS2017 RC

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4127]
Build: d15prerel 26015.8

1. Create a new .NET Core C# console app
1. Open the project file in the editor while it's still open, using the new "Edit ConsoleApp1.csproj" command.
1. Open the NuGet PackageManager Console.
1. Execute `Install-Package Validation`  (I personally used `install-package -source C:\git\Nerdbank.GitVersioning\bin\Debug\ nerdbank.gitversioning -version 1.5.61-g1ac9af822c` but I think the package is irrelevant).

A message box appears with this error:

> The project 'ConsoleApp15' has encountered an error.  You may need reload the project after fixing the problem.
> The imported project file "c:\users\andarno\documents\visual studio 2017\Projects\ConsoleApp15\ConsoleApp15\obj\ConsoleApp15.csproj.nuget.g.targets" could not be loaded. The process cannot access the file 'c:\users\andarno\documents\visual studio 2017\Projects\ConsoleApp15\ConsoleApp15\obj\ConsoleApp15.csproj.nuget.g.targets' because it is being used by another process.  C:\Program Files (x86)\Microsoft Visual Studio\2017\d15prerel\MSBuild\15.0\Bin\Microsoft.Common.targets

**Comment by zhili1208** [comment]
I tired latest vs build, can't repro this issue.
Build: d15prerel 26104.1
NuGet version : 4.0.0.2098
also tried latest nuget build: 4.0.0.2168
@AArnott Can you still repro this with latest build?

**Comment by AArnott** [comment]
No. This no longer repros for me either on d15prerel.
