### ISSUE TITLE
Nuget 3.5 rtm restore failure in Jenkins

### ISSUE THREAD

**Issue by MohdIrfanKhan** [NuGet/Home#4129]
Hi,  

The build in Jenkins in failing due to Nuget Restore failure.  error MSB3073: The command ""D:\NuGet\v3.5.0-rtm\NuGet.exe" restore "..\Demo.sln" -MSBuildVersion 14 -NonInteractive" exited with code 1.  In solution project.json is used with wild cards to get the latest version of nuget package. Also here in project file nuget cache is implemented.

<Exec Command='"$(NuGetPath)" restore "%(SolutionFile.Identity)" -MSBuildVersion 14 -NonInteractive -NoCache' Condition="'$(NuGetCache)' == 'NoCache'"/>
    <Exec Command='"$(NuGetPath)" restore "%(SolutionFile.Identity)" -MSBuildVersion 14 -NonInteractive' Condition="'$(NuGetCache)' != 'NoCache'"/>

The command for building:
msbuild TestProject.proj /t:Compile /p:BuildInParallel=true;NugetCache="Cache"

On removing NugetCache="Cache" the build is passing.

**Comment by rrelyea** [comment]
related to your fix for passing in multiple params?

**Comment by MohdIrfanKhan** [comment]
In Jenkins Job configuration these parameters are working whereas in my powershell window i need to give the command like:
msbuild TestProject.proj /t:Compile /p:BuildInParallel=true /p:NugetCache="Cache"

But the issue resolves when not passing this parameter as it considers it as 'noCache'.
![image](https://cloud.githubusercontent.com/assets/16488496/21315583/e46e6134-c622-11e6-8578-e29ee4ceb59c.png)

On removing NuGetCache="Cache" the build is passing. After adding NuGetCache again few build passes but after few days it starts fail.

Is it because some new package been pushed to nuget which is not there in cache and causing the build failure?

**Comment by rrelyea** [comment]
@rrelyea - who build this restore target? don't think this has anything to do with NuGet team.

**Comment by rrelyea** [comment]
Please investigate this customer scenario.

**Comment by zhili1208** [comment]
Please use nuget.exe 4.3 from https://www.nuget.org/downloads, close this for now, if 4.3 still repro, feel free to reopen it
