### ISSUE TITLE
Nuget.Config not taken by kudu and azure.

### ISSUE THREAD

**Issue by Bartmax** [NuGet/Home#413]
I don't know this is the right place to post this. Sorry if it isn't.

I created a github repo with mvc6 (starter web)

Created a web app and set up continuous integration.

And I received an error about beta-3 not fonud on nuget v2 feed. So i wanted to update my feed to use myget one, but kudu doesn't seem to recognize this nuget.config file. It's on solution root.

I went to scm and I can see the file is there and doing nuget sources I see the correct sources but on deploying, we app is not using that config file.

Here some screenshots to describe the problem better

![nuget-kudu-error](https://cloud.githubusercontent.com/assets/3386797/7103567/76fccb08-e083-11e4-9397-ff8452366503.png)
![nuget-kudu-source](https://cloud.githubusercontent.com/assets/3386797/7103568/7924d470-e083-11e4-8f50-bc35ba4cb0e9.png)

**Comment by davidfowl** [comment]
kvm doesn't respect NuGet.config (and probably never will). Your best bet would be to try using the actual beta3 release (as in 1.0.0-beta3 no build number)

**Comment by yishaigalatzer** [comment]
@davidfowl is there anything to do here on the nuget side? Should we close and track on aspnet? (Why wouldn't KVM respect nuget.config?)

**Comment by davidfowl** [comment]
This isn't a nuget issue either. File it on dnvm but it's by design
