### ISSUE TITLE
Latest Nugetizer (0.1.183-dev) is incompatible with a number of frameworks

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4132]
@kzu 

Package NuGet.Build.Packaging 0.1.183-dev is not compatible with uap10.0 (UAP,Version=v10.0). Package NuGet.Build.Packaging 0.1.183-dev supports: net46 (.NETFramework,Version=v4.6)
One or more packages are incompatible with UAP,Version=v10.0.

**Comment by bbowman** [comment]
<dependencies>
      <group targetFramework=".NETFramework4.5">
        <dependency id="ICSharpCode.Decompiler" version="2.3.1" />
        <dependency id="ICSharpCode.NRefactory" version="5.5.1" />
        <dependency id="Mono.Cecil" version="0.9.6.1" />
        <dependency id="Mono.Options" version="4.4.0" />
        <dependency id="SlowMonkey" version="1.1.1" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.6" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.6" />
    </frameworkAssemblies>

Appear to be the offenders. Perhaps in the packaging process a change occured that is no longer correctly picking up / respecting the "don't include legacy deps / frameworks"?

**Comment by bbowman** [comment]
Latest stable 0.1.173 does not show this behavior. I don't see any git tags to know what commit that stable release is off of to narrow down the offending commit.

**Comment by kzu** [comment]
That was a buggy drop. Please try again, it should be working again with latest.
