### ISSUE TITLE
Nugetizer creates 0 byte packages

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4133]
@kzu 

On failures, it looks like nugetizer still runs the pack process enough to output a zero kb file that makes the nuget client go a bit crazy if set as a local repo path.

**Comment by adalon** [comment]
@bbowman could you please provide some repro steps or the context where the package is being created empty? I just tried a couple of failures but I could not get the empty .nupkg in the output.

**Comment by bbowman** [comment]
@adalon sure. My scenario is a little complicated but I'll play around with it a bit and see if I can get a minimal repro. I was expecting that all failures would produce this result but as you say that apparently isn't the case.

**Comment by kzu** [comment]
Closing for now until a clean repro can be provided so we can use that as a regression test.
