### ISSUE TITLE
Pack from csproj does not include the minClientVersion attribute 

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4135]
Moved from https://github.com/dotnet/sdk/issues/509 filed by @onovotny

When using the pack command to create a NuPkg from a csproj, the `MinClientVersion` attribute is not written to the generated NuSpec despite being present in the csproj.

**Comment by rohit21agrawal** [comment]
@onovotny I tried to repro this on my end but couldn't. I have attached the project i tried to repro this issue with. You can download it, get the latest CLI+SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip , and run dotnet restore, dotnet build and dotnet pack on the project.

The nuspec file in the nupkg is the following :

```
`<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata minClientVersion="2.8">
    <id>ClassLibrary1</id>
    <version>1.0.0</version>
    <authors>ClassLibrary1</authors>
    <owners>ClassLibrary1</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard1.4">
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>`
```
[ClassLibrary1.zip](https://github.com/NuGet/Home/files/679078/ClassLibrary1.zip)

**Comment by rohit21agrawal** [comment]
@onovotny : were you able to try this at your end?

**Comment by clairernovotny** [comment]
Yes, sorry, was out last week.

Here's what I see -- the `nupkg` does have the attribute set, but the generated `NuSpec` in the `obj` directory does not....that's what threw me. I would have expected the generated `nuspec` file to have `minClientVersion` set as well.

**Comment by rohit21agrawal** [comment]
aah ok, if that's the case, it's a bug too. let me investigate more.
