### ISSUE TITLE
Preprocessing of contentFiles can corrupt binary files

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4138]
Moving from https://github.com/dotnet/sdk/issues/372 filed by @nguerrera

We call `NuGet.CommonPreprocessor.Preprocess(Stream, Func<string, string>)` which returns a `String` and then we do File.WriteAllText.

I found this because @harshjain2 hit an issue with dlls in contentFiles, which is dubious, but it strikes me that we could also have other binary content such as a jpeg or whatever. 

Question: Is it it by design that everything in contentFiles/ in a package must be text? Where does non-text content go?

* If it is by design, then we need to have a better failure mode than possible silent corruption or crash.
* If it is not by design, then we need to make sure that binary files can pass through safely somehow.

There is also a perf concern if binaries go through the preprocessor even if it were changed to ensure no corruption of binaries.

@rrelyea for nuget question

**Comment by clairernovotny** [comment]
This cannot be by design. We have to be able to have images and other binary assets as content.

**Comment by emgarten** [comment]
I would expect that ``NuGet.CommonPreprocessor.Preprocess`` is only used on ``.pp`` files, it sounds like an issue in the build task if everything is being transformed.

Having jpegs under ContentFiles is a common scenario, they should be referenced directly and not modified.

**Comment by nguerrera** [comment]
Aha, ok. This is broken in the build task.
