### ISSUE TITLE
Package Manager Console lacks "All sources" option

### ISSUE THREAD

**Issue by dougbu** [NuGet/Home#414]
The drop-down for "Package source:" does not include "All sources".  Though most commands appear to ignore the "Default project:" drop-down, "Package source:" unfortunately seems to matter.  Do `find-package` or `get-package` cmdlets have a `-source` option to use all enabled sources?

**Comment by yishaigalatzer** [comment]
All sources support was removed by design, we are tracking restoring that support and it is being tracked already.

**Comment by dougbu** [comment]
thx @yishaigalatzer. what issue tracks that restoration?

**Comment by albertjan** [comment]
@yishaigalatzer?
