### ISSUE TITLE
Publish NuGet.CommandLine.3.5.0.nupkg to become the latest stable release

### ISSUE THREAD

**Issue by Jarlotee** [NuGet/Home#4140]
It looks like the website and several other places have been update to note that v3.5.0 is the latest stable release with the exception of nuget.org.

Would love to be able to `update -self` to the latest version. Any idea when the package feed will be updated?

See
https://www.nuget.org/packages/NuGet.CommandLine

and 

https://dist.nuget.org/index.html

**Comment by Stephen-Randall** [comment]
http://blog.nuget.org/20161027/Announcing-NuGet-3.5-RTM.html

This is referenced as coming in a "few weeks" almost 8 weeks ago.  Can we get an updated ETA?

**Comment by rrelyea** [comment]
Done. Thx.
