### ISSUE TITLE
Source packages don't work with SDK style builds

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#4143]
Using VS 2017/preview 4 tooling, a source package reference doesn't have its content files included in the build.

To repro, check out the following commit:
https://github.com/Reactive-Extensions/Rx.NET/tree/36628232c94fba50aee92787a6ed17897ebe60de

Open up Rx.NET/Source/System.Reactive.sln and try to build. The `Microsoft.Reactive.Testing` library fails to build as the xunit source reference package's files aren't passed to the compiler.

**Comment by rrelyea** [comment]
fixed with contentFiles work?

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/Home/issues/3683

Note this hasn't been integrated into the CLI yet
