### ISSUE TITLE
Run Pack as a post build target conditioned on "GeneratePackageOnBuild" MSBuild property

### ISSUE THREAD

**Issue by mavasani** [NuGet/Home#4145]
Recently, we added a new Package property page for dotnet core projects in roslyn-project-system. This page allows you to set an MSBuild property `GeneratePackageOnBuild`, indicating that Pack target should run as a post build step. We need to update the Pack targets so that it is always run post build, conditioned on this property. See https://github.com/dotnet/sdk/issues/524#issuecomment-268404510 for details.

**Comment by mavasani** [comment]
Tagging @Srivatsn @rohit21agrawal

**Comment by rrelyea** [comment]
Per email thread, appears to be blocking the VS UI for Pack. @rohit21agrawal - let's discuss how hard this is to land (and eta).
