### ISSUE TITLE
Define a new ProjectCapability "Pack" in Pack targets for enabling Package related capabilities

### ISSUE THREAD

**Issue by mavasani** [NuGet/Home#4146]
Recently, we added a new Package property page and a context menu command to execute Pack for dotnet core projects in roslyn-project-system. Both the property page and the command are conditioned on a ProjectCapability named "Pack". @Srivatsn recommended that this project capability should be defined in the Pack targets, so that only the SDK/project importing this target get these new features.

**Comment by mavasani** [comment]
Tagging @rohit21agrawal

**Comment by rohit21agrawal** [comment]
@srivatsn @mavasani can you guys point me to how a ProjectCapability is added in a target file?

**Comment by mavasani** [comment]
You just need to add an item group with the capability like following:

```
<ItemGroup Condition="???">
     <ProjectCapability Include="Pack"/>
</ItempGroup>
```

**Comment by srivatsn** [comment]
@rohit21agrawal - how will the SDK pick up this package? I assume a vs insertion is needed for this to show up?
