### ISSUE TITLE
Latest NuGet PACK yields PREVIOUS version AssemblyVersionAttribute values

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#4149]
Please read the following information before posting the issue.

```
NuGet CLI v3.5 (latest)
Visual Studio 2015 Update 3
Windows 7 Pro 64-bit
```

Worked before? Don't know; I assume it did, but I don't know.

I am using ``PACK`` against ``CSPROJ`` with ``$version$`` token replacement. I have versioned ``NUSPEC`` and ``AssemblyInfo`` files.

I have three ``NUSPEC`` files thus far, and **ALL THREE** are replacing ``$version$`` with the **PREVIOUS** version of ``AssemblyVersionAttribute`` found in the projects.

```
NuGet.exe pack MyProject.csproj -symbols
```

**Comment by mwpowellhtx** [comment]
I should also mention, my ``AssemblyVersionAttribute`` looks something like this:

```C#
[assembly: AssemblyVersion("1.2.3.*")]
```

And somehow this is being cached, including ``*`` number, and which previous version is being used instead of the current one in the output ``Details``.

**Comment by rohit21agrawal** [comment]
can you attach a repro project?

**Comment by mwpowellhtx** [comment]
As far as I know, a version with 1.2.3.* yields the aforementioned outcome.

I am working around it for now with a static version, but $version$ would be preferred.

**Comment by zhili1208** [comment]
Please try nuget.exe 4.3 from https://www.nuget.org/downloads, close it for now, if it still repro with 4.3, feel free to reopen it

**Comment by mwpowellhtx** [comment]
@zhili1208 Thanks for the heads up. I haven't tried since the update, but I will keep it in mind for the next moment of opportunity.
