### ISSUE TITLE
[Package Manager Console] `Get-Project` cmdlet does not work in DNX projects

### ISSUE THREAD

**Issue by dougbu** [NuGet/Home#415]
with recent VisualStudio builds, WTE, and the NuGet client components that come with that VS install,
1. open a DNX solution e.g. Razor.sln
2. open Package Manager Console
3. type `get-project` (should return current project) or `get-project -all` (should return all projects)
4. observe return value is `$null`

similarly `get-project -Name 'Microsoft.AspNet.Razor'` or `get-project -Name 'src\Microsoft.AspNet.Razor'` throw `ItemNotFoundException`s

seems DNX-specific since `get-project` works in non-DNX solutions e.g. the CodePlex Runtime.sln

**Comment by yishaigalatzer** [comment]
Since DNX doesn't support Install.PS1, why is this of any importance? @davidfowl ?

**Comment by dougbu** [comment]
this cmdlet is useful in DNX because the DTE experience when hacking VS projects is ugly.  for example, I've used this for various "do undo all projects" updates that execute within VS.

**Comment by emgarten** [comment]
This should no longer be the case in VS 2017 now that all projects are handled by NuGet.
