### ISSUE TITLE
enable restore to share obj directory between projects

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4154]
vsfeedback internal link: https://vsfeedback/comment/729721

This is an open source project at https://github.com/lextm/sharpsnmplib

1. Clone and check out master.
2. Launch SharpSnmpLib.NetStandard.sln to compile the .NET Standard 1.3 project first in Visual Studio 2017 RC.
3. Close the solution and open SharpSnmpLib.Classic.sln to compile the PCL project, and the following errors can be seen,

Build started ...
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(162,5): error : Your project is not referencing the ".NETPortable,Version=v4.5,Profile=Profile7" framework. Add a reference to ".NETPortable,Version=v4.5,Profile=Profile7" in the "frameworks" section of your project.json, and then re-run NuGet restore.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(162,5): error : Your project is not referencing the ".NETFramework,Version=v4.5" framework. Add a reference to ".NETFramework,Version=v4.5" in the "frameworks" section of your project.json, and then re-run NuGet restore.

The workaround is to remove project.assets.json left by the .NET Standard project compilation.

I think it is a bug of NuGet or MSBuild, and hope it can be fixed soon.

**Comment by emgarten** [comment]
The build task here sees the ``project.assets.json`` file under ``obj\`` and assumes it is for the portable project also.

The best way to fix this is to not share intermediatedirectories for more than one project.
You can do this by changing ``BaseIntermediateOutputPath`` to a different folder.

**Comment by lextm** [comment]
@emgarten Then another observation.

If I set `<BaseIntermediateOutputPath>obj1\</BaseIntermediateOutputPath>` in a .NET standard class library project, then `dotnet restore` and `dotnet build` work flawlessly (SharpSnmpLib.NetStandard.csproj for instance).

However, if this trick is applied to a .NET Core console application (Tests.NetStandard.csproj), `dotnet build` gives a miserable error,
```
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\Users\lextm\Downloads\sharpsnmplib\Tests\Tests.NetStandard.csproj]
```
I assume it is a different issue, right?

**Comment by emgarten** [comment]
> I assume it is a different issue, right?

I would say so, this looks like a compile issue. Some part of the build may not be finding the updated output.

**Comment by rrelyea** [comment]
@lextm - can you please file that issue with entry point with the SDK repo? http://github.com/dotnet/sdk/issues
And mention this issue, so a link is created to that issue.

**Comment by rrelyea** [comment]
moving to 4.0.1 in case there is any left over issue on nuget side.
