### ISSUE TITLE
vsfeedback: NuGet restore give several project reference warnings for LinqToTwitter project

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4156]
https://vsfeedback/comment/729379

Linq To Twitter (https://github.com/JoeMayo/LinqToTwitter) is an open source project and the latest version is well supported in VS 2015. I configured NuGet auto-restore and it works well in VS 2015.

I had all kinds of build problems in VS 2017 RC. When building, I expected auto-restore to kick-in and it did for only some packages. Other packages, such as ASP.NET MVC 4.0.40804 (for the Linq2Twitter.AspNet project) would not update. The only way I got that to work was by removing the reference and re-adding the reference. I'm also getting a lot of missing reference errors when trying to build other projects. The entire package restore on project build is causing a lot of problems for new solutions that are cloned and built for the first time.

**Comment by rrelyea** [comment]
after auto restore, I see ~22 warnings.
then after build restore, I only see these 5:
Warning		Failed to resolve all project references. The package restore result for 'LinqToTwitter.net\LinqToTwitter.net.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'LinqToTwitter.xamarin\LinqToTwitter.xamarin.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'LinqToTwitter.AspNet\LinqToTwitter.AspNet.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for '..\..\Samples\net46\CSharp\ConsoleSamples\ConsoleSamples.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'LinqToTwitter.Tests\LinqToTwitter.Tests.csproj' or a dependant project may be incomplete.			0	
1) ideally, we should have the same behavior in both cases
2) also, why are we seeing these problems with resolving package references??? let's debug and figure that out, please.

**Comment by emgarten** [comment]
These warnings are unrelated to the project to project references. 

NuGet/NuGet.Client@c29b08a049252972361e0e5f4dc159120bdd2d3d
