### ISSUE TITLE
Removing a package with lots of files takes ages

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#416]
We have an internal Nuget package about 3 MB in size, containing one ASP.NET MVC site area. The package holds about 600 files (mostly small, for instance CKEditor buid) in some 300 folders. 

When initiating package update from within VS, NuGet starts to remove the old version and it is this step that takes "forever" (about 10-15 minutes on a modern highend machine with SSD drive). 

Once the package is removed the new version is installed pretty quickly (but still much slower than unzipping it manually). 

What does the NuGet team need from me to debug this?

**Comment by brgrz** [comment]
It seems NuGet moves the files to Recycle bin when removing the package. This could explain why removal takes so much time though I'm not sure about it.

**Comment by yishaigalatzer** [comment]
This is probably source control or DTE (Visual studio adding and removing the files).

1. Our recommendation going forward is to use something like Bower for content files. Typically these files don't need to be an actual part of the solution (as they are not supposed to be editable by the user).
2. Try making sure they are not under source control - That will definitely make a big difference (I'm just not sure if you are using source control in this project).
