### ISSUE TITLE
NuGet randomly fails to resolve project references

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4160]
VS version (if appropriate): 26028.1.d15prerel

Running into this ~3 or 4 times a day, where F5 or build NuGet will fail to resolve project references:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.UnitTests.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'ProjectSystemSetup\ProjectSystemSetup.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'VisualStudioEditorsSetup\VisualStudioEditorsSetup.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.UnitTests.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.AppDesigner\Microsoft.VisualStudio.AppDesigner.vbproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'ProjectSystemDogfoodSetup\ProjectSystemDogfoodSetup.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'DeployTestDependencies\DeployTestDependencies.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.ProjectSystem.CSharp.VS\Microsoft.VisualStudio.ProjectSystem.CSharp.VS.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS\Microsoft.VisualStudio.ProjectSystem.VisualBasic.VS.csproj' or a dependant project may be incomplete.			0	
Warning		Failed to resolve all project references. The package restore result for 'Microsoft.VisualStudio.ProjectSystem.Managed\Microsoft.VisualStudio.ProjectSystem.Managed.csproj' or a dependant project may be incomplete.			0	

```

The Output window shows no more information than above.

This ultimately breaks my build because certain packages are not found. Usually retrying the build or F5 will succeed. This is a recent occurrence, and have only seen this in the past month or two of builds.

This is occurring on http://github.com/dotnet/roslyn-project-system.

**Comment by emgarten** [comment]
These warnings are usually just noise and have been turned off in the latest build of NuGet. If you are seeing actual packages missing because a project to project reference is missing than there may be a problem with the project or the way NuGet is calling the project system.

If you look in the project.assets.json file to see what projects are considered part of the closure, are there any that are actually missing? Do you have a consistent repro of missing packages?

**Comment by davkean** [comment]
When above occurs - the project fails to build due to missing APIs (in my case above resulted in the System.ValueTuple package disappearing from the graph, so tuples usage failed to build).

This is not consistent - I run into it 3 or 4 times a day.

**Comment by davkean** [comment]
ie These don't appear to be noise, because when they are output my project fails to build due to missing NuGet packages getting written to the assets file.

**Comment by emgarten** [comment]
The warnings are generated when discovering project to project references before restore happens. Specifically when ``VSLangProj80.Reference3.Resolved`` is false for any item. (not specific to project references which is why this is noisy).

> the project fails to build due to missing APIs (in my case above resulted in the System.ValueTuple package disappearing from the graph, so tuples usage failed to build)

Does this package come through transitively from another project?

**Comment by davkean** [comment]
Yes this package comes transitively.

**Comment by emgarten** [comment]
It could be that NuGet is hitting errors when walking the project references then. Any ideas why the project system would fail to return the complete references for Roslyn? 

The code NuGet uses for project.json projects is here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/Utility/VSProjectRestoreReferenceUtility.cs#L111-L121

**Comment by davkean** [comment]
It's not Roslyn, it's the project system. That particular code looks fine (besides you assuming that all References are project references). Are you sure it's not throwing? Where is that Log in the Exception block logged to? https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/Utility/VSProjectRestoreReferenceUtility.cs#L88

**Comment by emgarten** [comment]
``log.LogDebug(ex.ToString());`` would go to the output window. NuGet uses the msbuild verbosity level in VS for filtering, so if you change that to diagnostic you should see the output.

**Comment by zhili1208** [comment]
close it for now, if it still repro, feel free to reopen
