### ISSUE TITLE
NuGet Error On Retrieving Package Metadata

### ISSUE THREAD

**Issue by Al00X** [NuGet/Home#4161]
NuGet product used (Package Manager Console):

NuGet version: 3.0.60624.657

VS version: VS2015 , 14.0.23107.0

OS version: Windows 10 v1607

   `PM> Install-Package Microsoft.CodeAnalysis.CSharp.Scripting`
    `Attempting to gather dependencies information for package 'Microsoft.CodeAnalysis.CSharp.Scripting.1.3.2' with respect to project 'MYPROJ', targeting '.NETFramework,Version=v4.5.2'`
    `Install-Package : An error occurred while retrieving package metadata for 'System.Reflection.Metadata.1.4.1' from 
    source 'H:\WORK\__Programming\Sources\MYPROJ\packages'.`
    `At line:1 char:1`
    `+ Install-Package Microsoft.CodeAnalysis.CSharp.Scripting`
    `+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
        `+ CategoryInfo          : NotSpecified: (:) [Install-Package], Exception`
       ` + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`

As you can see on the top , i have metadata issue , just when i want to install `Microsoft.CodeAnalysis.CSharp.Scripting` this error appears...
other packages install works fine.
What is the problem with this ?

**Comment by rrelyea** [comment]
You said you are using NuGet 3.0?
As a first step, are you able to try NuGet 3.5 and see if the problem still occurs?
http://nuget.org/downloads

**Comment by Al00X** [comment]
@rrelyea It Works Now , Thx

**Comment by rrelyea** [comment]
great. thanks for confirming.
