### ISSUE TITLE
Packages.config should not be the default in VS 2017 

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#4162]
Create a new .NET 4.5.2 console app in VS 2017. Add a NuGet package. It creates it with a `packages.config` file.

This leads people down too much pain. With PackageReference's, they must be the default so the ecosystem can move forward.

`PackageReference` must be supported **and** be the default if a package.config/project.json file doesn't already exist.

**Comment by rrelyea** [comment]
We are building UI to allow the user to choose between packages.config (which will work downlevel too) and packagereferences.
Spec is here: https://github.com/NuGet/Home/wiki/Supporting-Package-Reference-in-UWP-WPF-WinForms-and-Classic-Libraries

**Comment by davidfowl** [comment]
Can we still make the default PackageReference? I would hope we don't ask users as the very first thing they do...
