### ISSUE TITLE
Combo of csproj+project.json show no reference information

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#4164]
the properties should show the same info as other (non project.json) references

![image](https://cloud.githubusercontent.com/assets/122666/21558981/4493cd52-ce97-11e6-9786-34bea79a320f.png)

```
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586
NuGet Package Manager   3.5.0
Microsoft .NET Core Tools (Preview 2)   14.1.21111.0
```

**Comment by davidfowl** [comment]
This is the old project system + `project.json`. Support in the solution explorer is pretty minimal. Moving to PackageReference things will get better in vs2017

**Comment by clairernovotny** [comment]
@SimonCropp I'd recommend doing an "SDK style" build using VS 2017. Way nicer and better info is provided. I can provide some pointers if you need help.

**Comment by SimonCropp** [comment]
in this context i am distributing samples to a customer. not really an option to point them to pre-release software

**Comment by clairernovotny** [comment]
@SimonCropp in that case, csproj+project.json is probably the best it's going to get today until VS 2017 is released. :/

**Comment by zhili1208** [comment]
Moving to package reference is the solution here. close it
