### ISSUE TITLE
[Test Failure]Menu 'Restore NuGet Packages' is disabled.

### ISSUE THREAD

**Issue by v-chaf** [NuGet/Home#4168]
**NuGet version:** 4.0.0-RC3-2157

**OS version:** Windows 10 RS1_Release 14393.693

**VS Version:** D15PreRel 26029.01

**Repro Step:**
1.	Create C# UWP project.
2.	Right click solution and select “Restore NuGet Packages”.

**Expected:**
Menu 'Restore NuGet Packages' is enabled.

**Actual:**
Menu 'Restore NuGet Packages' is disabled.

![aaa](https://cloud.githubusercontent.com/assets/24838161/21561430/724c71b2-cea7-11e6-8d3d-dd198f89f02e.png)

 **Notes:**

1. It doesn't repro on NuGet Client 4.0.0-RC2-2098.
2. It also repro on other projects.

**Comment by rrelyea** [comment]
@nkolev92 - can you please dig into this problem.

**Comment by nkolev92** [comment]
It was a bug due to a merge problem. A line was mistakenly removed during the merge. 
@jainaashish has added that line back in https://github.com/NuGet/NuGet.Client/commit/5542ae5f29680714d58fc852c3762931601d1846

**Comment by nkolev92** [comment]
Verified with:

NuGet version: 4.0.0-RC3-2162

OS version: Windows 10 RS1_Release 14393.693

VS Version: D15PreRel 26028.06
