### ISSUE TITLE
Add a setting/switch to bypass Recycle bin when removing/updating

### ISSUE THREAD

**Issue by brgrz** [NuGet/Home#417]
It'd be useful to have a switch and a UI option to configure Nuget to bypass copying files to Recycle bin when updating/removing packages.

**Comment by yishaigalatzer** [comment]
This sounds like a potential optimization for diskspace but perhaps (didn't check) also for update when the project is on another drive than the recycle bin.

Given that we haven't gotten around to it, I'm marking it as Up For Grabs, without a strong justification I don't see it making into the next release.

**Comment by jainaashish** [comment]
I don't think we'll ever be able to get to this because of other prioritize work. So closing it.
