### ISSUE TITLE
No way to use tokens like $author$ with project.json.

### ISSUE THREAD

**Issue by DixonDs** [NuGet/Home#4170]
Please, correct me if I miss anything.

It is related to https://github.com/NuGet/Home/issues/2965. It is mentioned that
> If you have a csproj + project.json, then we will ignore the nuspec. that is by design

Which means it is a breaking change introduced in 3.5.0 since now there is no way to use $author$  and so on if project.json is used in the project. It is so because project.json doesn't support tokens and nuspec is ignored.

**Comment by SuperJMN** [comment]
Also, no package icon URL, tags or any other metadata. How would we add it if the nuspec files are ignored in the new version (3.5)?

**Comment by clairernovotny** [comment]
I think this is all moot with the pack targets/tooling in the `Preview3` and `Preview4` CLI tools. These are all defined in the `csproj` now and packing into a NuGet package respects those. That means as a property within MSBuild, you can set it to any MSBuild variable and/or pass in additional parameters on the command line.

**Comment by zhili1208** [comment]
Please move to Package reference for this issue
