### ISSUE TITLE
NuGet 3.5.0 not unpacking *.targets from package

### ISSUE THREAD

**Issue by mausch** [NuGet/Home#4171]
## Details about Problem

NuGet 3.5.0
Windows 10
Worked before in NuGet 3.3

## Detailed repro steps so we can see the same problem

1. Create a new project, add https://www.nuget.org/packages/Microsoft.Net.Compilers/1.3.2 with NuGet 3.3
2. Delete all files in the packages directory.
3. Restore packages with NuGet 3.5
4. Project build now fails with error:

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(321,5): error MSB4019: 
The imported project "C:\myproject\packages\Microsoft.Net.Compilers.1.3.2\tools\Microsoft.CSharp.Core.targets" was not found. 
Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

NuGet 3.5 does not unpack any `tools\*.targets` files when restoring this package, but NuGet 3.3 does.

**Comment by rrelyea** [comment]
@mausch - can you please test to see if NuGet 3.4.4 works?
Are you using nuget.exe and msbuild -- or doing this all inside of VS?
Which version of VS?

**Comment by mausch** [comment]
3.4.4 does unpack *.targets files.
This is all just using nuget.exe

**Comment by rrelyea** [comment]
@rohit21agrawal  - Sounds to be a pack regression from 3.4.4 that shipped in 3.5.0.
Can you please investigate?
Still happening in 4.0 release candidates?

**Comment by rohit21agrawal** [comment]
AFAIK , targets files need to be in build or buildCrossTargeting folder to be restored. In any case, this is likely a restore issue. @emgarten - comments?

**Comment by emgarten** [comment]
@mausch can you share some repro steps? I'm not seeing this problem.

Here is what I tried:

1. Create a new console app in VS 2015
1. ``Install-Package Microsoft.Net.Compilers -Version 1.3.2``
1. Verified ``packages\Microsoft.Net.Compilers.1.3.2\tools\Microsoft.CSharp.Core.targets`` was present
1. Deleted ``packages`` folder
1. ``nuget.exe restore Solution.sln``
1. Verified ``packages\Microsoft.Net.Compilers.1.3.2\tools\Microsoft.CSharp.Core.targets`` was present

I tried this with NuGet.exe 3.5.0 RTM and NuGet.exe 3.5.0 beta2 and did not see any cases where the targets were not extracted.

**Comment by rrelyea** [comment]
@mausch - can you please answer @emgarten's request from above for more details.

**Comment by mausch** [comment]
Weird, I can't reproduce it any more. I'll close this now, sorry for the trouble.
