### ISSUE TITLE
nuspec file is ignored

### ISSUE THREAD

**Issue by SuperJMN** [NuGet/Home#4172]
## Details about Problem

The existing nuspec file is ignored.

It happens with NuGet version 3.5.0.1938 - Windows 10 build 14986

## Steps to reproduce

1. In Visual Studio 2015 Update 3, create a Class Library PCL project that targets .NET Framework 4.6 and Windows Universal 10.0
2. Build it without touching anything
3. Execute `nuget spec`
4. Execute `nuget pack`

It was working in version 3.4.4

 # Expected results
The default metadata in the nuspec should be included in the resulting nupkg file.

 # Actual results
The metadata is empty. The nuspec file is ignored.

### Verbose Logs

> PS D:\Copia de SuperJMN\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1> nuget pack -verbosity detailed -ForceEnglishOutput
NuGet Version: 3.5.0.1938
Attempting to build package from 'ClassLibrary1.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Packing files from 'D:\Copia de SuperJMN\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug'.
Add file 'D:\Copia de SuperJMN\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll' to package as 'lib\dotnet5.0\ClassLibrary1.dll'
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'SuperJMN'.

> Id: ClassLibrary1
Version: 1.0.0.0
Authors: SuperJMN
Description: Description
Dependencies: Microsoft.NETCore [5.0.0, ), Microsoft.NETCore.Portable.Compatibility [1.0.0, )

> Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'ClassLibrary1.nuspec'.
Added file 'lib/dotnet5.0/ClassLibrary1.dll'.
Added file 'package/services/metadata/core-properties/0b40d7eab1e4418694316711e13d4a0a.psmdcp'.

> Successfully created package 'D:\Copia de SuperJMN\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\ClassLibrary1.1.0.0.nupkg'.
### Sample Project

[ClassLibrary1.zip](https://github.com/NuGet/Home/files/678899/ClassLibrary1.zip)

**Comment by SuperJMN** [comment]
OK, I've just discovered that it's the expected behavior:
https://github.com/NuGet/Home/issues/2965

Closing!

**Comment by Denis535** [comment]
@SuperJMN  why? .nuspec is deprecated or why?
