### ISSUE TITLE
NuGet manager UI not able to search packages incrementally

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4173]
I tried searching for package `QGEditors.WinForms` through NuGet manager UI, and typed `QGEditor` but it didn't show any search results for that. But when I typed `QGEditors `then it showed this package.

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #3439](https://github.com/NuGet/NuGetGallery/issues/3439) via [**ZenHub**](https://www.zenhub.com/)
