### ISSUE TITLE
Provide a mechanism to get root of the restore folder of the resolved nuget package

### ISSUE THREAD

**Issue by ramarag** [NuGet/Home#4174]
I am currently using the following to get the to the root:
FallbackPackagePathResolver.PathResolver.GetVersionListPath("") ;

as in https://github.com/ramarag/sdk/commit/a3521485aa3568a7e4cd9a877438789c4eb0da64#diff-42d31913aec3dcadaa9bf9b5eafba94cR42

Is this is the right way to consume The API ?

**Comment by ramarag** [comment]
cc @emgarten

**Comment by emgarten** [comment]
``packageDir  = pkginfo.PathResolver.GetInstallPath(packageId, version);`` will give you the root of the package folder.

Example: 
```
c:\users\user\.nuget\packages\a\1.0.0\a.nuspec

GetInstallPath("a", "1.0.0") -> c:\users\user\.nuget\packages\a\1.0.0\
```

Paths in the lock file are relative to the install path, you should combine based on that. In your case you already have it as ``packageDir``

**Comment by ramarag** [comment]
@emgarten i need the cache Root not packagDir
In the above example it translates to the nuget cache root directory

```GetVersionListPath("")  -> C:\users\user\.nuget\packages```

**Comment by emgarten** [comment]
There isn't a helper method for that currently, is this code copying all of the packages from each folder, or what will this do?

The safest way to get the root for all packages would be to:

1. Take the list of root package folders: https://github.com/ramarag/sdk/commit/a3521485aa3568a7e4cd9a877438789c4eb0da64#diff-42d31913aec3dcadaa9bf9b5eafba94cR51
1. Sort by path length desc
1. Take the first folder when the packageDir starts with the package folder path

Ordering by length would protect against any nested folder scenarios

**Comment by schellap** [comment]
Cc @gkhanna79

**Comment by emgarten** [comment]
I've checked in a fix to make the Root property public on the VersoinFolderPathResolver.
