### ISSUE TITLE
[Test Failure] The ‘Manage NuGet package’ dialog can’t be opened regularly

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4178]
**NuGet Version:** NuGet 4.0.0-RC3-2162
**VS Version:** D15PreRel 26101.01
**OS Version:** Windows 10 RS1_Release 14393.693.161220-1747

**Repro Steps:**
1.	Create a new **C#->Web->Asp.NET Web Application (.NET Framework) ->MVC** project.
2.	Start **‘Manage NuGet packages’** dialog by right clicking of the project node.

**Expected Result:**
The ‘Manage NuGet packages’ dialog can be opened regularly. 

**Actual Result:**
The ‘Manage NuGet packages’ dialog can’t be opened and pop up an error window as below screenshot.
 
![5555](https://cloud.githubusercontent.com/assets/20632775/21599321/c075808a-d1a5-11e6-8248-9dd845f1ea64.png)

**Notes:**
1.	The issue repro on Dev14 MU3.5 + NuGet 4.0.0-RC3-2162.
2.	The issue doesn’t repro on D15PreRel 26101.01(NuGet 4.0.0-RC2-2098)

**Comment by v-nancyj** [comment]
The issue repro on all .NET Framework projects

**Comment by v-nancyj** [comment]
When creating a C#->Web->Asp.NET Web Application (.NET Framework) project, an error window pop up as below screenshot.
![untitled333](https://cloud.githubusercontent.com/assets/20632775/21602451/fda5dc74-d1ce-11e6-900c-69b62c49d2e6.png)

**Comment by rrelyea** [comment]
Can you please link the commit/pr to this and close?

**Comment by emgarten** [comment]
NuGet/NuGet.Client@e0db9783fc3f3a4586397d922075f1f9a3217419
