### ISSUE TITLE
Package Update on TFS Bound Projects extremly SLOW

### ISSUE THREAD

**Issue by mittork** [NuGet/Home#418]
See last comment here: https://nuget.codeplex.com/workitem/2531

I updated to the most recent 2.8 version via VS 2013 Extension Manager.

The problem is not solved, yet.
E.g. it still takes 10-30 minutes to update ONE package which is referenced in all 32 projects of my solution.

I already tried to checkout everything, didn't help...

This is not efficient.... I need to update 10 packages today....
I thought, this will take a few minutes..... Now it will take hours! -.-

Please, fix this.

Kind regards,
Ramon

**Comment by yishaigalatzer** [comment]
@mittork you can turn off source control integration, that should spin things up significantly.

**Comment by mittork** [comment]
Thanks for the hint.
I will try next time.

Can you tell me whether this is a workaround or the best practice because the slowness on tfs bound projects is by design?

If TFS is located in local area network it is much better to have the packages inside... So, not every team member needs to redownload it from the internet....

Sent from my Windows Phone
________________________________

**Comment by yishaigalatzer** [comment]
> If TFS is located in local area network it is much better to have the packages inside... So, not every team member needs to redownload it from the internet....

@mittork actually this is not the case. You don't want your binaries checked in TFS, and if you worry about download speed (depending on where you work this might be an issue), you can just as well setup a local NuGet server that everyone case use.

Also NuGet uses a local cache so you might have a first time hit over the internet, but not the second time restoring a package from machine.

**Comment by mittork** [comment]
Thank you very much for clarification.

Today I enabled the package restore and removed the binaries from TFS.
My first tests showed that it is really (really) much faster!

Also, the local NuGet server sounds good.

Thanks again, this issue can be closed.
