### ISSUE TITLE
NuGet.exe msbuildpath fails when there is a trailing slash

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4180]
Restoring with a trailing ``\`` on the msbuildpath value restore fails. When removing the trailing slash nuget.exe finds msbuild correctly.

```
nuget.exe restore .\ConsoleApp8.sln -msbuildpath 'C:
\Program Files (x86)\VS\DogFood\d15prerel\26102.01\MSBuild\15.0\Bin\'
Using Msbuild from 'C:\Program Files (x86)\VS\DogFood\d15prerel\26102.01\MSBuild\15.0\Bin"'.
MSBuildPath : C:\Program Files (x86)\VS\DogFood\d15prerel\26102.01\MSBuild\15.0\Bin"  doesn't not exist.
```

This is using a recent build of nuget.exe 4.0.0

**Comment by emgarten** [comment]
//cc @zhili1208

**Comment by zhili1208** [comment]
the passing parameter is invalid, the trailing slash escaped the double quote. if user want to restore with a trailing slash, need add a space between slash and double quote.
nuget.exe restore .\ConsoleApp8.sln -msbuildpath "C:
\Program Files (x86)\VS\DogFood\d15prerel\26102.01\MSBuild\15.0\Bin\ "

then it will work well
