### ISSUE TITLE
Nuget.Client should use CPS JoinableTaskFactory when interacting with CPS to prevent deadlocks

### ISSUE THREAD

**Issue by jviau** [NuGet/Home#4185]
Currently Nuget.Client uses the Shell `JoinableTaskFactory` when interacting with CPS projects [NuGetUIThreadHelper](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.UI/Utility/NuGetUIThreadHelper.cs). This is causing deadlocks due to project lock issues. The CPS JTF has knowledge of the project lock and logic to prevent these issues. You can get the CPS version of JTF by importing the `IProjectThreadingService` from CPS. Let me know if you need assistance in the specifics of getting the `IProjectThreadingService`.

I am not sure how many deadlocks this is causing, but I have identified at least one when NuGet eventually sets an item property from within an `ExecuteAction`.

**Comment by rrelyea** [comment]
Please investigate this request.

**Comment by jviau** [comment]
@aarnott can you validate if my understanding of `JoinableTaskFactory` is correct? Is it necessary for NuGet to use the CPS JTF when interacting with CPS projects?

**Comment by AArnott** [comment]
Yes. The CPS JoinableTaskFactory is aware of project locks and can mitigate what would otherwise be deadlocks between code that controls the main thread and code that holds project locks. So when using JoinableTaskFactory.Run or RunAsync, you should use the CPS one when the delegate you pass in may call into CPS code that needs project locks.

**Comment by AArnott** [comment]
This is documented, BTW, here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/threading_model.md

**Comment by rrelyea** [comment]
Moving to RTM, as it is a bit risky for last day of RC3. Justin has fix.
