### ISSUE TITLE
NuGetizer regression with IncludeOutputsInPackage

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4188]
@kzu 
https://github.com/NuGet/NuGet.Build.Packaging/commit/1886901a33d8815efda828caa34ce2e326afde08

poses a number of problems for .vcxproj integration that I was using as it shuts off the project reference traversal as well as turning off the output inclusion for that project. I understand that simple .proj files may not have a project configuration so these items were moved in but it seems like $(IncludeOutputsInPackage) is being overloaded too far now. Should we introduce a new IncludeProjectReferencesInPackage or something that toggles the project dep walking?

**Comment by kzu** [comment]
Good point, we may indeed need such a property

**Comment by bbowman** [comment]
Any updates on this one? I also noticed you guys pushed a package to nuget.org now which awesome :-)

**Comment by kzu** [comment]
Fix on its way :)
