### ISSUE TITLE
[vsfeedback] msb4011 warnings at compile time

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4193]
internal bug: 293938
vs feedback item: 707802 - community site: https://developercommunity.visualstudio.com/content/problem/2728/msb4011-warnings-at-compile-time.html 

may be a dupe of an issue on @Emgarten and/or @rohit21agrawal  - please investigate.

I open a solution and build it (it uses stylecop.analyzers from nuget) and I get loads of MSB4011 warnings:

 1>------ Build started: Project: EntityTests, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\EntityTests\EntityTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\EntityTests\EntityTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Core\CronusBiz.Framework.Core.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Core\CronusBiz.Framework.Core.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Data\CronusBiz.Framework.Data.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Data\CronusBiz.Framework.Data.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework\CronusBiz.Framework.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework\CronusBiz.Framework.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\EntityModules\CronusBiz.Entity\CronusBiz.Entity.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\EntityModules\CronusBiz.Entity\CronusBiz.Entity.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\FrameworkTests\FrameworkTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\FrameworkTests\FrameworkTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Core\CronusBiz.Framework.Core.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Core\CronusBiz.Framework.Core.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Data\CronusBiz.Framework.Data.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework.Data\CronusBiz.Framework.Data.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\FrameworkTests\FrameworkTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\FrameworkTests\FrameworkTests.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework\CronusBiz.Framework.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\CronusBiz.Framework\CronusBiz.Framework.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Imports\Microsoft.Common.props\ImportBefore\Microsoft.NuGet.ImportBefore.props (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\d\fmk\main\FrameworkSource\CronusFramework\EntityModules\CronusBiz.Entity\CronusBiz.Entity.csproj]
 1>C:\Program Files (x86)\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(16,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets (16,3)". This is most likely a build authoring error. This subsequent import will be ignored. 1> EntityTests -> E:\d\fmk\main\FrameworkSource\CronusFramework\Tests\EntityTests\bin\Debug\EntityTests.dll
 ========== Build: 1 succeeded, 0 failed, 10 up-to-date, 0 skipped ==========

 I used to get this in VS15 preview 5 as well but though that by RC time that would be gone.

**Comment by rrelyea** [comment]
marking hi priority since it is our top vote getter on vsfeedback that isn't fixed yet.

**Comment by zhili1208** [comment]
the root cause of this issue is user have "Imports folder" which contains Microsoft.Common.Targets under both C:\Program Files (x86)\MSBuild\15.0 and C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\, they all imported Microsoft.NuGet.Targets.

not repro this on latest VS build, I think this issue only occur in some old vs build.

**Comment by dirq** [comment]
I think I fixed mine by renaming D:\ProgramFiles\VisualStudio\2017\Enterprise\MSBuild\Microsoft\NuGet to something else (NuGet-OLD).  Your VS install directory is probably different.

**Comment by brunoamancio** [comment]
"ClosedAs:NotRepro"
So, in which VS2017 build was this solved?
