### ISSUE TITLE
migrate vsix from v2 vsix to v3 vsix

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4196]
Tracking via internal bug 384559

**Comment by nkolev92** [comment]
Reverted NuGet change in:
https://github.com/NuGet/NuGet.Client/pull/1169
NuGet CI changes have been reverted as well.

**Comment by rrelyea** [comment]
Moving to 4.0.1 per decisions.

**Comment by rrelyea** [comment]
bring back to 4.0rtm. Please get ready for insertion into VS asap.
