### ISSUE TITLE
Rework Self-Updater with V3 Apis

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#4197]
Currently the self-updater uses NuGet.Core v2 code. 
The V3 APIs provide a similar functionality so this should be reworked.

**Comment by cyanite** [comment]
Would this mean that nuget.exe update -self will actually update nuget past version 3.5? Or does anyone know another way to do this? It's not so great that the help text says "Update the running NuGet.exe to the newest version available from the server." when this is clearly not true.

**Comment by nkolev92** [comment]
@cyanite 
This won't change the functional behavior of the update self command. 

We don't immediately allow the update self command to download the absolute latest version as we don't want to potentially break customers whose automation invokes this command, so we allow for a bake-in period after release.

We will publish the update to 4.1.0 within the next few days. 

//cc @rrelyea 

**EDIT:**
The new package has been published. 
**The update self command should now upgrade to version 4.1.0**

**Comment by JVimes** [comment]
One idea: `-Source` could pick the server for `-Self` updates. This may have let me work around today's [v2 api errors](https://github.com/NuGet/Home/issues/7333#issuecomment-425164133). Needs to be weighed against business value, though.

**Comment by nkolev92** [comment]
@JVimes 
There's a tracking issue for that already.
https://github.com/NuGet/Home/issues/1783
