### ISSUE TITLE
[vsfeedback] The "Version" drop down that shows available package versions, struggles to stay in-sync with the selected nuGet package... 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4198]
VS Feedback: 714137 & https://developercommunity.visualstudio.com/content/problem/4973/the-version-drop-down-that-shows-available-package.html

The following keeps happening to me:

I have a nuGet package installed in some packages of my solution, but I want it installed on the others too.
I open the Solution Package Manager.
I go to the Installed tab.
I type in something (say "Microsoft.Bcl") select all projects, hit install. It works.
I then switch to Microsoft.Bcl.Async because I want to install that in all projects too -- the Version drop down still has the versions from Microsoft.Bcl -- If I click install then it crashes with because it cannot find version specified.

Clicking around a bit to trigger a resync is a workaround -- but this has been very confusing and frustrating before I realised what was going on.

**Comment by zhili1208** [comment]
Repro step:
1. add a bad package source through UI setting
2. open solution package manager.
3. select nuget.org as active package sources.
4. switch package source to bad package source.
5. switch between packages.

Expect:
UI shows right information for all packages.

actual:
package versions list will be out of sync.
