### ISSUE TITLE
NuGet do not honor time-stamps when unpacking nupkg files

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#420]
NuGet uses the current time when unpacking nupkg files, instead of time-stamps stored in the ZIP files.

This leads to "dirty file" problems for build & deployment systems relying on time-stamps for figuring out which header/lib/dll files have changed. An example of this is robocopy-based SW deployment that only replaces new/modified files.

Steps to reproduce:
* With NuGet command-line: "NuGet.exe install zlib" (package found on nuget.org), or
* Create a Visual Studio 2013 C++ project. Add NuGet dependency to "zlib" and build project.
* Verify that unpacked *.h, *.lib & *.dll files are time-stamped with current time instead of the time in the downloaded nupkg files.

**Comment by forderud** [comment]
I don't know NuGet in detail, but my gut feeling is that the problem is caused by [ZipArchiveExtensions.cs](https://github.com/NuGet/NuGet.Packaging/blob/master/src/NuGet.Common/ZipArchiveExtensions.cs) using *entryStream.CopyTo(targetStream)* instead of *entry.ExtractToFile(...)* for extracting files.

**Comment by forderud** [comment]
I've tried to fix the issue on https://github.com/forderud/NuGet.Packaging/tree/unzip_timestamp

However, I have not been able to test the changes due to build issues with VS2015 RC. Therefore, I do not dare to send a pull request.

**Comment by rirl** [comment]
Sorry for my ignorance, but has this item been fixed somewhere?
In particular, can I download a beta of nuget.exe that might have this fix somehow?

**Comment by forderud** [comment]
Any progress on fixing this issue?

**Comment by mmclin** [comment]
I am also interested in a fix for this issue. We use Nuget for managing releases of libraries that are distributed to customers, and the incorrect timestamps have caused us some troubles.

**Comment by yishaigalatzer** [comment]
We haven't gotten around to fixing this, we hope this can happen on the next release.

@forderud we have simplified the build process significantly, and is should be a lot easier now, if you would like to give it another go. All the code is now in [Nuget Client](https://github.com/NuGet/nuget.client) [Directions](https://github.com/NuGet/home#how-to-build-nuget-visualstudio-extension).

**Comment by forderud** [comment]
@alpaix  any update on fixing this issue?

**Comment by alpaix** [comment]
@forderud it's in my work queue. Will look into this within next few days.

**Comment by forderud** [comment]
Thanks a lot @alpaix. I really apreciate your help in fixing this issue.

**Comment by yishaigalatzer** [comment]
@forderud can you please verify this solves it in your scenarios?

**Comment by forderud** [comment]
Unfortunately, the time-stamp issue persists even when building NuGet.Client from the latest "dev" branch.

Steps to reproduce:
1: Build NuGet.Client from "dev" branch.
2: Install artifacts\NuGet.Tools.vsix
3: Unzip & build  [NuGetTimeStamp-Reproducer.zip](https://github.com/NuGet/Home/files/72283/NuGetTimeStamp-Reproducer.zip)
4: Verify that time-stamps of files unzipped beneath the "packages" subfolder does not correspond to time-stamps in nupkg files.

**Comment by yishaigalatzer** [comment]
Alex my guess is that this I an opc code path from nuget2.

**Comment by yishaigalatzer** [comment]
@forderud just to try and validate this assumption, are you restoring from a V2 or V3 feed (api.nuget.org/v3/index.json)

**Comment by yishaigalatzer** [comment]
Actually I still see this repro with V3 api as well. @alpaix back in your hands to investigate. I will also add a commandline test to restore against a V2/V3 server

**Comment by forderud** [comment]
I'm restoring from the default VS2015 nuget feed, which is https://api.nuget.org/v3/index.json .

**Comment by alpaix** [comment]
Looking into this...

**Comment by forderud** [comment]
I'm still unable to reproduce this fix on my Win10 (x64) computer with VS2015 (update1). Unpacked nuget files are still time-stamped with current time instead of the time-stamp in the ZIP files.

Steps performed:
- Download and unzip NuGetTimeStamp-Reproducer.zip (link above).
- Download and extract nuget.exe from latest NuGet.CommandLine from https://www.myget.org/gallery/nugetbuild (build 3.4.0.348).
- Run "nuget restore NuGetTimeStamp.sln"

Log file with details: [log.txt](https://github.com/NuGet/Home/files/79162/log.txt)

**Comment by alpaix** [comment]
Got the same build 3.4.0.348, followed @forderud steps, didn't repro.

Can you run "nuget" command with no args to confirm build version is the same?

**Comment by forderud** [comment]
```
C:\Users\Fredrik\Desktop\NuGetTimeStamp-Reproducer>nuget
NuGet Version: 3.4.0.348
usage: NuGet <command> [args] [options]
Type 'NuGet help <command>' for help on a specific command.
...
```

This was very strange indeed. I've already tried to clean all NuGet caches under both "AppData" and ".nuget". Also, nuget.exe is not found elsewhere in my PATH.

**Comment by alpaix** [comment]
Okay, repro'd when forced v3 source:

```
 .\NuGet.exe restore NuGetTimeStamp.sln -NoCache -source https://api.nuget.org/v3/index.json -Verbosity detailed
```

Looking into this...

**Comment by alpaix** [comment]
Found yet another scenario of package extractor reading file from a cache and writing back as a FileStream, here https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageExtractor.cs#L127

Obviously this technique doesn't maintain original file attributes. Will work on fixing this.

**Comment by forderud** [comment]
Fix now verified with VS2015. Thank you very much for all your help @alpaix.

**Comment by chipplyman** [comment]
Is this really the right behavior?

This behavior definitely causes problems when converting from source-controlled references to Nuget-controlled references.  I have not tested, but I suspect that this breaks at build time in general.  If I build at time X, then restore Nuget package to a build from time X-100, then build again, I expect any projects dependent on the package to be rebuilt.  Because (X-100) < X, they will not.

IMO, Nuget should use the same timestamp behavior as source control.  TFS and P4 necessarily and correctly set file timestamps at sync time by default.

**Comment by jonnyyu** [comment]
Yes, the timestamp  preserving behavior causes incremental build issues when I need revert to an older package.
Should be an option to set like in P4 git etc.
