### ISSUE TITLE
Remove NuGet.Protocol.Core.V2 code

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#4200]
Once NuGet.Exe list command is fully ported to V3, the NuGet.Core.Protocol.Core.V2 code can be safely removed.

Classes used in NuGet.Core.Protocol.V2 like ListCommandResource need to be cleanup as well

**Comment by rrelyea** [comment]
@nkolev92 - can you please determine if this fix shipped in 4.0 or 4.1 and change the milestone to that.

**Comment by nkolev92** [comment]
Done. @rrelyea This went into 4.1
