### ISSUE TITLE
[vsfeedback] While using Package Manager Console, the 'Enter' key may not work at times.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4204]
[anangaur] Changed the title from "[vsfeedback] pmc will throw null ref when there is project which contains v1 project.lock.json"

vsfeedback item: 718874 (talk to me about how to look up internally)
https://developercommunity.visualstudio.com/content/problem/6350/package-manager-console-freezes.html

customer title: package manager console freezes 
Tools -> Nuget package manager -> Package Manager Console
prompt appears - but return key does not do anything 
e.g. try pwd or dir or ls command - but no response
Then error on trying to close down Visual Studio - see attachment

**Comment by nkolev92** [comment]
I cannot repro this. 
Seems like the issue is a month old, so it might have been fixed in the meanwhile?

**Comment by dg2k** [comment]
Happened to me a moment ago. The keyboard doesn't respond to the Console window at all. Mouse interaction seems OK because I can place the cursor anywhere in the pmc window.
If this is a hint, there is red text prompt on the last two lines reading:

    Value cannot be null.
    Parameter name: key

Exiting VS2017RC and re-launching it cured the problem and I can interact with the pmc.

**Comment by nkolev92** [comment]
Happened to me just now.
Opening our NuGet.Clients.sln in VS17 just after the migration reproduces the problem as of 4.0.0.2252

**Comment by nkolev92** [comment]
Potential workaround:

1. Open VS
2. Open PMC prior to opening a solution

**Comment by rrelyea** [comment]
Balancing to @zhili1208

**Comment by zhili1208** [comment]
the issue here is PMC is reading project.lock.json for running ps script during initialization, if the version of project.lock.json is v1, package type of all packages are null. nuget will throw null ref and user can't use pmc

**Comment by mrueedi** [comment]
So a solution for me was to close VS and rename or delete the old v1 project.lock.json. After starting VS again, a v2 version of the file was generated...

**Comment by anangaur** [comment]
@zhili1208 , @rrelyea  Is this fixed in 4.4? If so, can you close this? This has been a known issue since VS 15.3 RTW and I would have to keep it or remove it from 15.4 release notes based on whether this was fixed or not.

**Comment by zhili1208** [comment]
@anangaur few customers hit this, please remove it from know issues, close it as won't fix, we should be considering a better plan for moving to next version in the future.

**Comment by anangaur** [comment]
Thanks @zhili1208 This will not show up in 15.5 release notes.

**Comment by naleczynskia** [comment]
I can reproduce this. Just put "pause" in a bat script and run script from the console.

**Comment by patbecich** [comment]
https://github.com/NuGet/Home/issues/1329#issuecomment-170252340
Shift+Enter worked for me.

**Comment by lynnewu** [comment]
<enter> key has never worked for me in PMC, in **any** version of VS.  <shift><enter> does work.

**Comment by FLAMESpl** [comment]
it still occurs
