### ISSUE TITLE
Support for v3 versioned services

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4206]
Add support for selecting v3 services based on the client version. The previous model used hardcoded type strings which made it impossible for a server to optimize or support or new feature without breaking older clients unless the client added a new type.

Existing services will continue to work the same, this feature just allows a new service type to take precedence over the current hardcoded list **if** the index.json file contains the new types.

#### Benefits:
1. nuget.org and 3rd party servers can add support for features for clients that have already shipped
1. servers can control services on a client version level

#### Scenarios:
1. Support for SemVer 2.0.0 on nuget.org in NuGet 4.0.0/CLI 1.0.0
1. Support for compressed flatcontainer json files

The above scenarios work today in 3.5.0 but cannot be enabled without breaking older clients. Having this feature will make it possible to do the server work at a later date instead of when client work begins on a new version.

It would also make it possible for 3rd party servers to support new features instead of being limited to what nuget.org supports.

#### Example service entry
```json
    {
      "@id": "https://api.nuget.org/v3-flatcontainer/",
      "@type": "PackageBaseAddress/3.0.0",
      "comment": "Fallback for older clients"
    },
    {
      "@id": "https://api.nuget.org/updated-flatcontainer/",
      "@type": "PackageBaseAddress/Versioned",
      "comment": "Compressed flatcontainer service that is used for clients 4.0.0 and up",
      "clientVersion": "4.0.0"
    }
```

**Comment by emgarten** [comment]
NuGet/NuGet.Client@358f3b564b297f9a6db2094984e2f01fcde6936b

**Comment by maartenba** [comment]
Is there a spec of what version means which features are available? his will be useful for both server implementors as well as alternate client implementors.

Instead of this versioning aproach, can the `index.json` perhaps have a list of capabilities instead? E.g.

```
    {
      "@id": "https://api.nuget.org/v3-flatcontainer/",
      "@type": "PackageBaseAddress/3.0.0",
      "capabilities": [ "gzip" ]
    }
```

or just:

```
    {
      "@id": "https://api.nuget.org/v3-flatcontainer/",
      "@type": "PackageBaseAddress/4.0.0",
    }
```

**Comment by emgarten** [comment]
@maartenba Those work well for deciding what to use in new clients. This issue is trying to solve the reverse problem, when the client has already shipped and can't be changed how do light up new features in the client or redirect client versions to different endpoints after making a later change to the server that breaks older clients.

Adding support for a new type in the client still works great **if** the type is known and this feature already exists on the server. This feature doesn't replace that, it just adds a hook for the server to redirect clients based on version.

**Comment by maartenba** [comment]
Righto! Thanks for clarifying

**Comment by maartenba** [comment]
Will this apply to all resources?

**Comment by emgarten** [comment]
Yep, all resources that are used in the client today
