### ISSUE TITLE
NuGet restore is selecting compile assets from runtime section.

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#4207]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe

NuGet version (x.x.x.xxx):
4.0.0.2067

dotnet.exe --version (if appropirate):
1.0.0-preview5-004275

VS version (if appropriate):
N/A

OS version (i.e. win10 v1607 (14393.321)):
 win10 v1607 (14393.577)

Worked before? If so, with which NuGet version:
don't know

## Detailed repro steps so we can see the same problem

1. download repro project: https://gist.github.com/ericstj/452c243859cdc5f88da084d205bc73e9

2. run dotnet restore, examine assets.json.

Expect: no `compile` assets to be selected from `runtime.win7-x64.Microsoft.Private.CoreFx.NETCoreApp`.
Actual: NuGet chooses runtime-specific assets for compile:
```
      "runtime.win7-x64.Microsoft.Private.CoreFx.NETCoreApp/4.4.0-beta-24822-0": {
        "type": "package",
        "compile": {
          "runtimes/win7-x64/lib/netcoreapp1.1/Microsoft.CSharp.dll": {},
          "runtimes/win7-x64/lib/netcoreapp1.1/Microsoft.VisualBasic.dll": {},
          ...
```

I remember this happened in NuGet before and I thought it was fixed, but I went back and checked and it looks like it may have still been an issue in project.json.  Perhaps CLI never hit it because it wasn't using the RID-specific target for compile.  I'm going to file a separate issue on that.

/cc @emgarten

**Comment by emgarten** [comment]
Looks like you found the workaround, restore will try ``ref`` first and if it doesn't exist it will go on to use ``lib`` and ``runtimes`` to find compile assets. I've made a fix to limit this search to just ``ref`` and ``lib``.

I believe this has always been the restore behavior. Looking at existing runtime packages I see they contain a ``ref`` with ``_._``.  Do you know of many packages with only runtimes? Is it common?

**Comment by rrelyea** [comment]
@ericstj - what is the impact if this doesn't make 4.0 rtm? very late for a change.

**Comment by ericstj** [comment]
Given there's a workaround I think its OK to postpone but it should be fixed.  I've stumbled on it multiple times.

**Comment by ericstj** [comment]
Thinking about this more, it wasn't hit in NuGet-3/xproj-CLI because the RID-less target would be used for compile.  In NuGet-4/MSBuild it's being hit because https://github.com/dotnet/sdk/issues/592.  If this isn't fixed and https://github.com/dotnet/sdk/issues/592 isn't fixed then you'll expose this bad behavior.  If either one is fixed I think you may preserve correct behavior.
