### ISSUE TITLE
Error list has error after build solution which unload the referenced project

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4208]
d15prerel build number: 25824.05
internal bug: 284184

Steps to reproduce:
1.       Launch VS.
2.       Create a blank solution, add a  C++ Blank App(Universal Windows) project  name “aa” and a  C++ Windows Runtime Component(Universal Windows) project named “bb” to solution.
3.       Add reference “bb” to project “aa”.
4.       Unload project “bb”. 
5.       Build Solution.

Expected Result:  Build successfully. Error list has no error.
 Actual Result:  Warning text: Failed to resolve all project references for 'aa'. The package restore result for 'c:\Users\qqq\documents\visual studio 2017\Projects\aa\aa\aa.vcxproj' may be incomplete.

**Comment by emgarten** [comment]
This warning has been removed. In scenarios such as this it is expected that the unloaded project cannot be read.  NuGet/NuGet.Client@c29b08a049252972361e0e5f4dc159120bdd2d3d
