### ISSUE TITLE
[Watson] HANG: Microsoft.VisualStudio.ProjectSystem.VS.Implementation!ProjectConfigProviderBase.__c__DisplayClass39_0._Microsoft.VisualStudio.Shell.Interop.IVsCfgProvider2.GetCfgOfName_b_

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4209]
Please see internal bug 296572 for details and heap dumps.

Just noticed that bug comments believe this is a dupe of CPS JTF issue -- #4185

**Comment by rrelyea** [comment]
Moving to RTM, as it is a bit risky for last day of RC3. Justin has fix.

**Comment by emgarten** [comment]
Dupe of #4185 as mentioned
