### ISSUE TITLE
When project refers web.config in other folder than project root  web.config.install.config will not be applied to it

### ISSUE THREAD

**Issue by SergKanz** [NuGet/Home#421]
When project has something like this:
    <Content Include="..\..\SolutionItems\Web.config">
      <Link>Web.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <SubType>Designer</SubType>
    </Content>
web.config.install.xdt will be applied to web.config in root folder, not to one that project file references.

It will be great if it will respect this "redirection" and apply transformation to one that will be used by application - one that is referenced by project file.

**Comment by yishaigalatzer** [comment]
We are not planning to add more features in this area. In general we recommending moving away from using NuGet as a source for content files.
