### ISSUE TITLE
Support VS preprocessor variables in packages.config files

### ISSUE THREAD

**Issue by lovelycodex** [NuGet/Home#4210]
Does exist right way to use preprocessor variables in packages.config files? 
Like: 
`<package id="$name$" version="$version$" targetFramework="$framework$" />
`
VS 2015

**Comment by emgarten** [comment]
This isn't a feature today for packages.config. Installing/updating packages requires adding and removing references, just changing the packages.config file isn't enough.

You might be able to achieve this using Visual Studio 2017 which will support ``PackageReference`` elements in project files. These can be created dynamically in MSBuild.
