### ISSUE TITLE
VSTS internal feed package restore error on VS2015: array must contain atleast one element

### ISSUE THREAD

**Issue by sudipta-chaudhari** [NuGet/Home#4212]
I have published a simple NuGet package containing 4 .cs files on VSTS and download and install it successfully from VSTS Internal NuGet feed. While trying to update or uninstall the package, I get the error :  "The array must contain at least one element". If I delete the classes manually and packages.config and then install the package freshly again, it succeeds but the Update/Uninstall fails always.

This happens when I install/update/uninstall the package on a project connected to VSTS. Even on checking out the complete project causes this issue. VS displays an error message : "The package at 'D:\TestPath\..\PackageName.1.0.0.1.' failed to uninstall. Restart Visual Studio to finish the process". However, the package gets uninstalled/updated successfully. On a standalone project not connected to VSTS, the package gets installed/updated/uninstalled successfully.

How can I prevent such error for a project connected to VSTS from appearing while installing/updating/uninstalling the package from a internal VSTS package feed url.

Attached is the .nuspec file.
[MyProject.nuspec.txt](https://github.com/NuGet/Home/files/690528/MyProject.nuspec.txt)

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
