### ISSUE TITLE
[vsfeedback] .net core web project from vs2015 - dotnet watch tool hangs restore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4214]
see internal bug 295173 and the related vsfeedback item (where there is a repro project)

**Comment by zhili1208** [comment]
Tested user's repro project with dotnet rc4-004737, VS 26129, nuget 2252. it works well.

the old migration project doesn't work, nuget can't load that project in VS. Redo the migration with dotnet rc4-004737 will make it work
