### ISSUE TITLE
[vsfeedback] Autmatic Restore for Nuget Packages on Build

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4215]
see internal bug 342838 - and corresponding vsfeedback issue.

**Comment by rrelyea** [comment]
sounds like one of jevan's work arounds (restore in vs2015) solves this problem. wonder if this is the vsts issue also.

**Comment by rrelyea** [comment]
Can you touch base with the customer to ensure that this is fixed in latest build (when they can get it).

**Comment by rrelyea** [comment]
Actually, rereading the repro steps, i think we need to contact the user and investigate this issue. Sounds like VS2015 fixes the lock file, or downloads the file ... but vs 2017 couldn't. What broke?

**Comment by nkolev92** [comment]
The "MSB1008 Only one project can be specified" error indicated some potential MSBuild trouble.
This might be a possible dup.
https://developercommunity.visualstudio.com/content/problem/2703/msbuild-only-one-project-can-be-specified.html

**Comment by nkolev92** [comment]
Should have been resolved in previous RCs.
