### ISSUE TITLE
[vsfeedback] build errors are not displayed as errors in case of reference issues

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4216]
please see internal bug 296518 and the corresponding vsfeedback item. Some details:

**Comment by anangaur** [comment]
Is this still an issue? This  has been a known issue since 15.3 RTW.

**Comment by zhili1208** [comment]
@emgarten added to backlog for now

**Comment by anangaur** [comment]
Dupe of https://github.com/NuGet/Home/issues/4113
