### ISSUE TITLE
modification of web.config.debug.xdt is not "really" supported

### ISSUE THREAD

**Issue by SergKanz** [NuGet/Home#422]
According to this blog post modification of web.debug.config is supported by NuGet:
http://blogs.msdn.com/b/webdev/archive/2013/10/24/how-to-use-xdt-in-nuget-examples-and-facts.aspx

As web.config.Debug.config is an XDT file by itself - I cannot find a way to actually apply any meaningful transformation to it. Specifically, if I want to generate this:

```
<appSettings xdt:Transform="InsertIfMissing" >
    <add key="name" value="value" xdt:Transform="InsertIfMissing" xdt:Locator="Match(key)" />
</appSettings>
```
How can I generate it using another xdt?

**Comment by yishaigalatzer** [comment]
@danliu you wrote the blog post :) Please provide the answer.

**Comment by danliu** [comment]
I don't think this can be done using the current XDT library and NuGet. XDT will recognize it as a transforming phrase and try to do transformation on it.

The workaround might be having a install.ps1 file that manipulate web.config file and add the sections that is desired.

**Comment by SergKanz** [comment]
Yes, I already implemented powershell to do it. Any chance it will be fixed? It is an important feature to have to allow NuGet to configure different settings for different environments.
