### ISSUE TITLE
[vsfeedback] update tab doesn't work well in .net core projects

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4220]
please investigate internal bug 293945 and corresponding vsfeedback item.

**Comment by jainaashish** [comment]
Not able to repro with VS 2017 build. I think it could have been fixed with latest release.

**Comment by jainaashish** [comment]
No further response from customer, looks like it's fixed with later releases since it was logged on 4.0 and we had lot of improvements afterwards. Will revise it, if it surface again.
