### ISSUE TITLE
NuGet causes VS hang while performing on-build restore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4225]
please investigate internal bug 374623 (several dupes)
originally: 294056

**Comment by rrelyea** [comment]
Good info about blocking build here: #4386

**Comment by emgarten** [comment]
Is this issue related to https://github.com/NuGet/Home/issues/4420? They both have hangs involving on build restore.

**Comment by davkean** [comment]
I'm still hitting this on 26205.0.d15rel. In particular, we've registered a critical task here: http://index/?query=NuGetRestorer&rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5CVS%5CNuGet%5CNuGetRestorer.cs&line=135 that CPS is waiting to compete before it tells the Solution Build manager that build can progress.

I have the dump, but I cannot see any relevant NuGet threads in the background.

**Comment by rrelyea** [comment]
@alpaix - how goes the data search for how often this is hitting folks?

**Comment by rrelyea** [comment]
We are counting on the mitigation from #4420 to solve many of these problems. Pushing out to 4.0.1

**Comment by davkean** [comment]
To add more data to this, these bugs are dups of this:

https://github.com/dotnet/roslyn-project-system/issues/1188
https://devdiv.visualstudio.com/DevDiv/VS%20IDE/_workitems?id=372928&fullScreen=false&_a=edit
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=378399
https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=372930&triage=true

We've had two MVPs hit this, 5 or 6 internals.

**Comment by davkean** [comment]
Then some of these look related as well:
~https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=382043~
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=378151

**Comment by davkean** [comment]
Actually, 382043 looks like https://github.com/NuGet/Home/issues/4386. 378151 is dup'd  against it, but I really this is this one.

**Comment by davkean** [comment]
This also looks caused by it: https://developercommunity.visualstudio.com/content/problem/18863/cannot-build-a-solution.html?childToView=19896.
