### ISSUE TITLE
NuGet UX in VS shows the metapackage 

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#4227]
When you create a 1.0.1 .NET Core project in VS2017 and click on manage nuget packages, the UX shows the metapackage as updateable from 1.0.1 to 1.1.0. This should not happen with the newest csproj projects. 

/cc @rrelyea

**Comment by emgarten** [comment]
This would be fixed by having read only PackageReferences that the UI does not show in updates or allow changes to.

https://github.com/NuGet/Home/issues/4044

**Comment by rrelyea** [comment]
VS2017 RTM will recommend that 1.0.x users upgrade to 1.1.
#4044 - is an idea, but not a completed design, etc..

**Comment by zhili1208** [comment]
it's fixed by #4044
