### ISSUE TITLE
Can't resolve compatible packages if update is initiated on "wrong" package

### ISSUE THREAD

**Issue by mrahl** [NuGet/Home#423]
We create a whole suite of interdependent NuGet packages and we have seen several scenarios where updates don't work. I have simplified the repro for one such issue to a diamond dependency graph:

```
   A
 /   \
B     C
 \   /
   D
```
Assume all packages have version 1.0 and support version range [1.0, 2.0) on their dependencies. Then we release D 2.0 and compatible versions of the others: 
A 1.1 Dep: B [1.1, 2.0), C [2.0, 3.0) 
B 1.1 Dep: D [2.0, 3.0) 
C 2.0 Dep: D [2.0, 3.0) 

If the update is initiated on either A, C or D it succeeds to update all packages, but if it is initiated on B the update fails: "Updating 'D 1.0' to 'D 2.0' failed. Unable to find a version of 'C' that is compatible with 'D 2.0'." 

Are we doing something wrong with our dependencies and/or versions? 

__Why not update A?__

This is a reduced case of a much larger dependency graph and only one of several different cases of such large graphs where this fails, so it is very hard for the consumers of our packages to know how to trigger the update. 

An open Update-Package (without specifying package) is quite likely to fail as well if it happens to start with the wrong package. With a solution of several projects the problem gets even worse since the initiating package which works in one of the projects may not work in another project so a solution wide update. 

__Why does the depencency look like this?__

Imagine D is a framework, B and C are products and A is a plugin for B, integrating C. That is also a reason you may be inclined to trigger the update on B rather than A (there could be multiple plugins for B so B is the main package you install). 

__Additional repro info__
This was reproduced using Nuget 2.8.5. Both the full and the reduced scenario have been reproduced in unit tests using the 2.8.5 source (that is how I managed to reduce the scenario). 

I have also tried to repro this case on Nuget 3 beta 2, using the real world packages with the larger dependency graph, but it fails with a null reference exception on some linq projection by the look of it.

**Comment by yishaigalatzer** [comment]
We believe this works in NuGet 3.0. Please either wait for the RC release (or you can build the vsix yourself, we will post instructions in a day or two. @feiling is on top that.

**Comment by mrahl** [comment]
Thanks for the response. I was trying to add the same unit test scenario for 3.0 but I can't get the projects in the solution to load in VS2015. I'll wait for the guide.

Is there any hope of getting someone to look att his in 2.8.5? I will myself of course, and if I can find a fix I'll contribute it.

**Comment by mrahl** [comment]
I discovered that the unit tests run in build.cmd so I don't need VS. But I am not able to exactly recreate the failing unit test I have for 2.8.5. Because of the check in line 75 of [PackageResolver.cs](https://github.com/NuGet/NuGet.Packaging/blob/6121ef94a01047a3cd50cdbdfdb0bc3799bc3876/src/NuGet.Resolver/PackageResolver.cs) I have to pass all of the packages (A, B, C, D) to initiate the "update".

If you have the time, please hint towards how a "Update-Package B" would translate to a PackageResolver call, if at all.

**Comment by yishaigalatzer** [comment]
Because you can't? Not sure actually @deepakaravindr can you comment?

**Comment by deepakaravindr** [comment]
Please check out [ResolverTests.cs](https://github.com/NuGet/NuGet.Packaging/blob/master/test/NuGet.Resolver.Test/ResolverTests.cs), if you have not already. It has a few tests for Diamond Dependencies

Having said that; Unlike 2.8.5, Dependency Resolution in 3.0, happens in 2 phases; In phase 1, ResolverGather collects the necessary dependency information and in the second phase, PackageResolver resolves the dependency based on this. NuGetPackageManager is just above these 2 layers and performs operations such as Install, Uninstall, Update as a user would do. In other words, You will just do 'Update A' if you are using NuGetPackageManager

So, for what you want to do, I would look at using [NuGetPackageManager.cs](https://github.com/NuGet/NuGet.PackageManagement/blob/master/src/PackageManagement/NuGetPackageManager.cs) and [NuGetPackageManagerTests.cs] (https://github.com/NuGet/NuGet.PackageManagement/blob/master/test/PackageManagement.Test/NuGetPackageManagerTests.cs). For example, check out method [TestPacManPreviewUpdatePackagesSimple] (https://github.com/NuGet/NuGet.PackageManagement/blob/master/test/PackageManagement.Test/NuGetPackageManagerTests.cs#L1776)

**Comment by mrahl** [comment]
Thanks for the explanation @deepakaravindr. I did implement my test in ResolverTests.cs. I saw the diamond dependency tests but as far as I can understand it is an install scenario, not update. On a side note, the ResolveActionsForSimpleUpdate test seems to test like an install rather than an update (the existing project it defines is not used in the Act stage).

Anyway, I looked at how the resolver is used by NugetPackageManager and friends. My conclusion is that to emulate "Update-Package B -Version 1.1" the test should call PackageResolver.Resolve with parameters target = [A1, B1, C1, D1, B1.1] and installedPackages = [A1, B1, C1, D1]. And that test is indeed successful.

I will look into NuGetPackageManagerTests and ResolverGather to see if I can add more tests for my scenario or test from a different level (NugetPackageManager rather than PackageResolver).

Would you be at all interested in looking at and possibly inlcuding my test(s) so I should push them to a branch on my fork?

**Comment by yishaigalatzer** [comment]
Yes please, a pull request will be great

**Comment by mrahl** [comment]
Test in PR now, sorry for the delay.
