### ISSUE TITLE
NuGet fails to restore a project that does not have an explicit package reference

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4230]
The SDK now has implicit references to Microsoft.NETCore.App and NETStandard.Library, which means that the basic templates no longer need to reference them. And the goal is to actually not have these packages in the csprojs at all.

However, once we remove them, NuGet will fail to restore these projects.

**Comment by emgarten** [comment]
This will be fixed with: https://github.com/dotnet/sdk/issues/537

**Comment by rrelyea** [comment]
@livarcocc  - looks like this has been fixed in SDK. Can you please confirm that this has been fixed for you?
