### ISSUE TITLE
[Test Failure] Build error occur after installing a package with ‘PackageReference in project file’ selected as package management format

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4232]
**NuGet Version:** NuGet 4.0.0-RC3-2188
**VS Version:** D15PreRel 26108.00
**OS Version:** Windows 10 RS1_Release 14393.722.170106-1842

**Repro Steps:**
1.	New a Visual C#->Windows Classic Desktop->Console App (.NET Framework) template.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Try to install package 'Newtonsoft.Json 8.0.2'.
4.	Select ‘PackageReference in project file’ as package management format and click 'OK'.
5.	Build the solution after installing.

**Expected Result:**
Build is successful and the installed package is added under the ‘References’ node.

**Actual Result:**
Build error occur and the installed package is not added under the ‘References’ node as below screenshot.
![builderror](https://cloud.githubusercontent.com/assets/20632625/21760348/624d5330-d686-11e6-8088-19e4ee4ddce4.PNG)
![packagereference](https://cloud.githubusercontent.com/assets/20632625/21760167/005fc76c-d685-11e6-9897-f0497fcd0834.PNG)

**Comment by jainaashish** [comment]
This happens only for console app, but works fine for class lib projects. And only happens for first package installation, somehow project system is not refreshed after first package installed. Asked Tom (.net sdk team) to look into this.

**Comment by jainaashish** [comment]
internal bug# 366608

**Comment by jainaashish** [comment]
Associated external bug is merged/closed.
