### ISSUE TITLE
Recommended way of packaging a host application

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4236]
I want to package an application which uses MEF to load client implementations of a certain interface:

```cs
[ImportMany(typeof(IClientMetadata))]
IEnumerable<IClientMetadata> Clients { get; set; }
```

To provide a seamlessly development experience for my clients, I'm trying to create a nuget package. I want the clients to be able to:
- create a assembly
- reference the package
- implement the interface
- set the host.exe as "Start external program"
- start debugging

I tried the following nuget package configurations:

Attempt 1
Add the host.exe and host.exe.config as content files in the nuspec

Fail
Are added as project files, not what I want.

Attempt 2
Add the host.exe and host.exe.config as ref files in nuspec

Fail
Only the host.exe is added in the output folder, the config is emitted (although it is part of the package).

Attempt 3
Add the host.exe and host.exe.config as tools

Fail
Executable isn't copied to the output folder, only available in visual studio.

All attempts did probably what nuget was supposed to do according to specs. Is it even possible what I'm trying to achieve, or is nuget not the technology to use here?

**Details about Problem**
NuGet version 3.5.0 (cli)
Visual studio 2015

**Comment by emgarten** [comment]
Have you tried referencing these files through a .targets file?

Are you expecting host.exe to run instead of the project that this is being installed into?

**Comment by tomkuijsten** [comment]
I didn't try referencing through a .targets file, will lookup the docs on that (never used that before).

And yes, that's exactly what I'm trying to achieve. It's a default option in VS to run a exe instead of the project itself and I wanted to use that to give the client developer a nice "run and debug" option.

**Comment by emgarten** [comment]
> It's a default option in VS to run a exe instead of the project itself and I wanted to use that to give the client developer a nice "run and debug" option.

It should be possible to set that in a project, then look at the project file to see the changes. If you copy that to a .targets file it should allow it to work the same way after installing a package.

**Comment by tomkuijsten** [comment]
Ahh yes I see what you mean and that would be another great addition to the package but....

the problem is that I can't even create a package where the host.exe and host.exe.config get's added to the output folder.

**Comment by emgarten** [comment]
> the problem is that I can't even create a package where the host.exe and host.exe.config get's added to the output folder.

.targets files can control all of this :smile:

**Comment by tomkuijsten** [comment]
Seriously... cool, digging into the documentation now, thanks for pointing it out to me!

Although... that would mean that those files have to be added to the project that is using the package? It will be added as content file right? Cause that's not what I want.

**Comment by tomkuijsten** [comment]
[This article](http://stackoverflow.com/questions/19478775/add-native-files-from-nuget-package-to-project-output-directory) explains exactly what I want and got it working, thanks again for the pointers.
