### ISSUE TITLE
Picture not in sync with text in the dependency resolution docs

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4237]
@tomkuijsten commented on [Mon Jan 09 2017](https://github.com/NuGet/NuGetGallery/issues/3460)

The last picture (about the error situation) doesn't match the explanation:

[Cousing dependencies](https://docs.nuget.org/ndocs/consume-packages/dependency-resolution#cousin-dependencies)

**Comment by karann-msft** [comment]
@tomkuijsten all docs issues belong on the home repo.

**Comment by tomkuijsten** [comment]
You might want to update the [new issue template](https://github.com/NuGet/NuGetGallery/issues/new) which stated:

```
* If you're having trouble with the NuGet.org Website, you are posting in the correct issue tracker.
```

Docs excluded?

**Comment by kraigb** [comment]
@tomkuijsten Other than changing the typo "required" to "requires" after Package A, where is the mismatch? Are you referring to the >=1.0 in the Package C box (which doesn't match other diagrams)? Otherwise the diagram shows A needing B 1.0 and C needing B >=2.0, which is what the text says.

**Comment by tomkuijsten** [comment]
@kraigb you are right, I think I was looking at the versions mentioned in Package A and C. Can be closed.

**Comment by kraigb** [comment]
Understood...I'll tweak the image to be consistent with the others to avoid future confusion. In the meantime, @karann-msft can you close?

**Comment by kraigb** [comment]
I've updated the image. Thanks for filing the issue in the first, as it did point out that one inconsistency. :)

**Comment by tomkuijsten** [comment]
No problem, thanks for the not-reported-but-found-during-discussion-bug fix ... 👍
