### ISSUE TITLE
Class Lib (.NET Standard) has build error after restore

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4238]
Repro Steps
•	Install VS d15prerel 26108.01
•	File New Project -> Class Lib (.NET Standard)
•	Manage NuGet Packages…
•	Install Newtonsoft.json
•	Choose the option of ‘Package Reference’ format
•	Build. I get the following error
![error](https://cloud.githubusercontent.com/assets/8865080/21778896/1ba3a668-d65a-11e6-9007-7d9004cd5b10.jpg)

This should be fixed with: http://github.com/dotnet/sdk#537

**Comment by rrelyea** [comment]
Please confirm that the sdk issue would fix it.

**Comment by emgarten** [comment]
Is there an issue tracking the incorrect error message on the sdk side? This shouldn't refer to project.json for PackageReference projects, it is confusing.

**Comment by rrelyea** [comment]
d15rel - 26109 - couldn't repro. did not get prompted for packages.config v packagereference. by design.

**Comment by rrelyea** [comment]
@jainaashish didn't repro eiether with d15prerel 26108

**Comment by jainaashish** [comment]
Confirmed with user, it's working fine now.
