### ISSUE TITLE
dotnet restore (on xplat) fails if an http feed is specified after a local feed via command line

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#4243]
1. Create a new project
2. Create a temp directory to use as a source (`mkdir /tmp/some-source`)
3. Run `~/.dotnet/dotnet restore -s /tmp/some-source -s https://api.nuget.org/v3/index.json`

Restore fails with

```
  Restoring packages for ~/src/restore/restore.csproj...
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018: The "RestoreTask" task failed unexpectedly. [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018: System.AggregateException: One or more errors occurred. (Failed to retrieve information from remote source '~/src/restore/https:/api.nuget.org/v3/index.json'.) ---> NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information from remote source '. [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018:    at NuGet.Protocol.LocalV3FindPackageByIdResource.GetVersionsCore(String id, ILogger logger) [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018:    at NuGet.Protocol.LocalV3FindPackageByIdResource.<>c__DisplayClass11_0.<GetVersions>b__0(String keyId) [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018:    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018:    at NuGet.Protocol.LocalV3FindPackageByIdResource.GetVersions(String id, ILogger logger) [~/src/restore/restore.csproj]
~/.dotnet/sdk/1.0.0-preview4-004233/NuGet.targets(70,5): error MSB4018:    at NuGet.Protocol.LocalV3FindPackageByIdResource.GetAllVersionsAsync(String id, SourceCacheContext cacheContext, ILogger logger, CancellationToken token) [~/src/restore/restore.csproj]
````

For some reason, restore's treating the v3 feed as a local source (`~/src/restore/https:/api.nuget.org/v3/index.json`).

**Comment by pranavkm** [comment]
CLI info:

```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

**Comment by emgarten** [comment]
I wasn't able to repro this with the latest CLI on windows. It could be that xplat msbuild is having trouble with encoding.

https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/Program.cs#L86

**Comment by rrelyea** [comment]
@zhili1208 - can you please attempt repro on non-windows cli install, and work with @pranavkm (ms) as needed. thx.

**Comment by pranavkm** [comment]
@emgarten - yeah the issue doesn't reproduce on Windows builds, but was pretty consistent on our Ubuntu and OSX build agents.

**Comment by zhili1208** [comment]
@pranavkm I tried this on mac and ubuntu, but can't repro it, Could you provide a repro vm? thanks

**Comment by rrelyea** [comment]
Zhi has this reproing and is following up with msbuild team to understand issue.

**Comment by zhili1208** [comment]
Repro step:

“Dotnet msbuild /p:RestoreSource=/tmp/some-source%3Bhttps://api.nuget.org/v3/index.json /t:restore test.csproj” 

Then in msbuild output:

RestoreSources = /tmp/some-source;https://api.nuget.org/v3/index.json

But after this:
<Sources>$(RestoreSources)<Sources>

Sources= /tmp/some-source;https:/api.nuget.org/v3/index.json

The double slash becomes single slash.

If I only use single source like following:

“Dotnet msbuild /p:RestoreSource=https://api.nuget.org/v3/index.json /t:restore test.csproj”

RestoreSources = https://api.nuget.org/v3/index.json

And 

Sources= https://api.nuget.org/v3/index.json

nuget is checking "http://" or "https://" to determine the source is http source.
Since the source here is "http:/", nuget will treat it as a local source.

Msbuild bug: https://github.com/Microsoft/msbuild/issues/1622

**Comment by rrelyea** [comment]
Worked around by CLI here: https://github.com/dotnet/cli/issues/5540

**Comment by zhili1208** [comment]
validated with dotnet cli 1.0.0-rc4-004769
