### ISSUE TITLE
VSTS internal feed package uninstall error on VS2015:The array must contain at least one element.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#4244]
Copied from: 
https://github.com/NuGet/NuGetGallery/issues/3459#issuecomment-271346314 

symptom:
 The error display : "The array must contain at least one element" when update/uninstall the package on a project connected to VSTS.

The visual studio Enterprise 2015 version is 14.0.25431.01 Update 3.
 The NuGet Packager Manager version is 3.5.0.1996

Steps:
1.Published a simple NuGet package containing 4 .cs files on VSTS.
2.Create a simple project and add into VSTS.
3.Install the package published in step 1.
4.Uninstall the package and get the above error massages.

These steps working fine in the NuGet Packager Manager version is 3.5.0.1848

Only when I check in entire project with the installed package, the uninstall process could successful.
****

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
