### ISSUE TITLE
Cannot reference PackTask directly in an MSBuild project

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4246]
To replace `dotnet nuget pack *.nuspec`, I'm trying to to use 'PackTask' instead. However, I cannot use the NuGet.Build.Tasks.Pack.Library as a PackageReference to import PackTask.

Example:
```xml
  <ItemGroup>
    <PackageReference Include="NuGet.Build.Tasks.Pack.Library" Version="4.0.0-rc3-2192"/>
  </ItemGroup>

  <Target Name="Pack">
    <PackTask NuspecFile="$(MSBuildThisFileDirectory)Test.nuspec" />
  </Target>
```

MSBuild fails with

>   error MSB4036: The "PackTask" task was not found.

The targets carried in the NuGet.Build.Tasks.Pack.Library are not imported in the generated 'obj/*.nuget.g.targets' file.

IIUC, this could be fixed by renaming the Pack.targets file to match the package id. At the moment, is is named NuGet.Build.Tasks.Pack.targets, but to be imported automatically, it should be NuGet.Build.Tasks.Pack.**Library**.targets...but...this might require changes to Microsoft.NET.Sdk.

cc @rohit21agrawal

**Comment by rohit21agrawal** [comment]
@natemcmaster don't use the nuget.build.tasks.pack.library package, the correct package to use is NuGet.Build.Tasks.Pack

**Comment by natemcmaster** [comment]
Good to know. Didn't know there was a difference. That resolves the issue.
