### ISSUE TITLE
NuGet.exe 3.5 Regression: Failure restoring packages when directory contains project files for different file types

### ISSUE THREAD

**Issue by mesheets** [NuGet/Home#4251]
## Details about Problem

Product used: **NuGet.exe v3.5**
dotnet.exe --version (if appropirate): **N/A** - Failure occurs during NuGet package restore within NuGet.exe
VS version (if appropriate): **Visual Studio 2015 Update 3**
MSBuild Version (as reported by NuGet.exe): **14.0**
OS version (i.e. win10 v1607 (14393.321)): **Windows Server 2008 R1 SP1** 

Worked before? If so, with which NuGet version: **3.4.4**

## Detailed repro steps so we can see the same problem

Scenario:
* Executing a NuGet package restore on a solution
* Project files for different assembly types exist in the same source code directory (e.g. one project file might be for a PCL assembly and another for a .NET Standard assembly)
Command:
```
NuGet.exe restore MyAssembly.sln -verbosity detailed
```

Result:
* NuGet.exe 3.5 fails the package restore, whereas NuGet.exe 3.4.4 succeeds.
* NuGet.exe 3.5 will still fail even if executed immediately after a successful NuGet.exe 3.4.4 run.

...

### Verbose Logs

Error messages written to standard output with -verbosity detailed:
```
Errors in E:\Temp\NuGet350Error\Portable\Source\Business\Business.DNX.csproj
    Project Foundation.PCL is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Project Foundation.PCL supports: portable46-net451+win81 (.NETPortable,Version=v4.6,Profile=Profile44)
    One or more projects are incompatible with .NETStandard,Version=v1.4.
```

### Sample Project

Log file and sample project included in attached zip file.
[NuGet350Error.zip](https://github.com/NuGet/Home/files/695086/NuGet350Error.zip)

**Comment by mesheets** [comment]
This error still persists in NuGet 4.1
```
Errors in C:\_Temp\NuGetError\Portable\Source\Business\Business.DNX.csproj
    Project Foundation.PCL is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Project Foundation.PCL supports: portable46-net451+win81 (.NETPortable,Version=v4.6,Profile=Profile44)
    One or more projects are incompatible with .NETStandard,Version=v1.4.
```

Two independent issues might actually be surfacing here.
1.  When restoring packages for a project, NuGet is not checking the project.json file that is specific to that project, which in this case is Foundation.DNX.project.json
2. Profile44 is not being handled correctly

The issue initially reported here relates to item 1 above.  I have since seen behavior elsewhere indicating that Profile44 is not being handled correctly.

According to the documentation, Profile44 correlates to .NET Standard 1.2; as such, this should not be flagged as an incompatibility.
 - https://docs.microsoft.com/en-us/dotnet/articles/standard/library
 - https://github.com/dotnet/standard/blob/master/docs/versions.md (c.f. the "Mapping PCL Profiles to .NET Standard" section"
 - https://docs.microsoft.com/en-us/nuget/schema/target-frameworks (c.f. the "Portable Class Libraries" section)

Also compare to http://nugettoolsdev.azurewebsites.net/4.0.0/framework-precedence?framework=monoandroid60&exludedIdentifiers= and note that the short folder name for Profile44 ("portable46-net451+win81") is not listed.

**Comment by mesheets** [comment]
Here is more on the Profile44 issue.
```
Project Core is not compatible with monoandroid60 (MonoAndroid,Version=v6.0). Project Core supports: portable46-net451+win81 (.NETPortable,Version=v4.6,Profile=Profile44)
One or more projects are incompatible with MonoAndroid,Version=v6.0.
Project Core is not compatible with monoandroid60 (MonoAndroid,Version=v6.0) / win. Project Core supports: portable46-net451+win81 (.NETPortable,Version=v4.6,Profile=Profile44)
One or more projects are incompatible with MonoAndroid,Version=v6.0 (win).
Package restore failed. Rolling back package changes for 'xyz'.
```

Referencing back to the documentation (e.g. https://docs.microsoft.com/en-us/nuget/schema/target-frameworks), the full name for Profile44 should be "portable-net451+win81" and not "portable46-net451+win81" as the NuGet error is reporting when attempting to add a NuGet packages to project "xyz" when project "xyz" (monoandroid60) includes a reference to project "Core" (Profile44).

**Comment by mesheets** [comment]
In continuing to further analyze this issue, it seems that perhaps the Profile44 issue might be the primary issue.

**Comment by emgarten** [comment]
NETStandard is not fully compatible with portable class libraries.

To allow installing PCLs add an imports of portable-net45+win8 to the project.
See https://docs.microsoft.com/en-us/nuget/schema/project-json for an example of how to add this.

Note that for NETCore SDK projects using *PackageReference* the property name is now *PackageTargetFallback*.

**Comment by mesheets** [comment]
@emgarten This doesn't seem to explain why 3.4.4 succeeded and ran without error, whereas newer versions fail. Did you attempt the reproduction steps?  As can be seen and demonstrated in the sample code that was uploaded, this is _not_ a cross-PCL/NETStandard issue.  The PCL projects are only referencing PCL projects, and the NETStandard projects are only referencing NETStandard projects.  Thus, there doesn't seem to be a real explanation for the error.

I have noted Profile44 issues in other scenarios, so perhaps that might need to be broken out into a separate issue.

As such, the issue describe in the first post still appears to be open.

**Comment by mesheets** [comment]
According to the https://docs.microsoft.com/en-us/nuget/schema/target-frameworks documentation page (among others, as noted in an earlier comment), Profile44 is explicitly listed as analogous with netstandard1.2.

In the attached sample, the PCL projects target Profile44, and the DNX projects target netstandard1.4.

A project targeting netstandard1.4 should be able to reference a project/assembly targeting netstandard1.2 and thus--by extension based on the aforementioned documentation--Profile44.

I have observed other scenarios where Profile44 seemed to be an issue, some of which were worked around by backing down to Profile7 (explicitly listed in the aforementioned documentation as analogous to netstandard1.1), though that won't always be a viable alternative.

**Comment by emgarten** [comment]
@mesheets does adding imports to your netstandard1.4 project resolve the issue for you?

**Comment by zhili1208** [comment]
No response, close it
