### ISSUE TITLE
CPS based project systems get the wrong NuGet restore style

### ISSUE THREAD

**Issue by dbreshears** [NuGet/Home#4253]
## Details about Problem

Our Service Fabric code calls InstallPackage to install a NugetPackage from our extension folder which is failing after the last insert of NuGet into D15PreRel  (commit Id e55a5eafa93d09f70e5e33d74e99098fa1c1d09a

this line in our code is where we now see the exception.   
IVsPackageInstaller packageInstaller = ServiceProvider.GetServiceFromComponentModel<IVsPackageInstaller>();

packageInstaller.InstallPackage(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), appProject, packageId, packageVersion, ignoreDependencies: false);

NuGet product used  - VS

NuGet version (4.0.170106.1651):
VS - 15.0.0-RC.3+26109.0.d15rel
OS version (i.e. win10 v1607 (14393.1001)):

Worked before? If so, with which NuGet version:
Yes - 4.0.170105.1644
## Detailed repro steps so we can see the same problem

1.    Install D15Rel or D15PreRel RC.3 build
2.    Install the Azure Workload
3.    If clean machine, install  Install VCRuntime11.0 -> \\trinlab2\baqafiles\servicefabric\Dev15\VCRuntime11.0
4.    Install \\trinlab2\baqafiles\servicefabric\5.4\MicrosoftServiceFabric.5.4.145.9494.msi
5.    Install \\trinlab2\baqafiles\servicefabric\5.4\MicrosoftServiceFabricSDK.2.4.145.msi
6.    Launch VS and Createa new Cloud ->Service Fabric Application
7.   Choose Stateless Service and hit ok
...

## Error

InvalidOperationException - "The operation failed as details for project ApplicationX could not be loaded.”

Call stack 

> NuGet.PackageManagement.VisualStudio.dll!NuGet.PackageManagement.VisualStudio.CpsPackageReferenceProject.GetAssetsFilePathAsync()                Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.PreviewBuildIntegratedProjectActionsAsync(NuGet.ProjectManagement.Projects.BuildIntegratedNuGetProject buildIntegratedProject, System.Collections.Generic.IEnumerable<NuGet.PackageManagement.NuGetProjectAction> nuGetProjectActions, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Threading.CancellationToken token)       Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectActionsAsync>d__74>(ref NuGet.PackageManagement.NuGetPackageManager.<PreviewBuildIntegratedProjectActionsAsync>d__74 stateMachine)  Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.PreviewBuildIntegratedProjectActionsAsync(NuGet.ProjectManagement.Projects.BuildIntegratedNuGetProject buildIntegratedProject, System.Collections.Generic.IEnumerable<NuGet.PackageManagement.NuGetProjectAction> nuGetProjectActions, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Threading.CancellationToken token)       Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token) Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__65>(ref NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__65 stateMachine)                Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.PreviewInstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token) Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, NuGet.Protocol.Core.Types.PackageDownloadContext downloadContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token)       Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48>(ref NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48 stateMachine)             Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, NuGet.Protocol.Core.Types.PackageDownloadContext downloadContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token)       Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token) Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47>(ref NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__47 stateMachine)             Unknown
NuGet.PackageManagement.dll!NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity packageIdentity, NuGet.PackageManagement.ResolutionContext resolutionContext, NuGet.ProjectManagement.INuGetProjectContext nuGetProjectContext, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> primarySources, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> secondarySources, System.Threading.CancellationToken token) Unknown
NuGet.VisualStudio.Implementation.dll!NuGet.VisualStudio.VsPackageInstaller.InstallInternalCoreAsync(NuGet.PackageManagement.NuGetPackageManager packageManager, NuGet.PackageManagement.GatherCache gatherCache, NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity package, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> sources, NuGet.VisualStudio.VSAPIProjectContext projectContext, bool includePrerelease, bool ignoreDependencies, System.Threading.CancellationToken token)       Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__26>(ref NuGet.VisualStudio.VsPackageInstaller.<InstallInternalCoreAsync>d__26 stateMachine) Unknown
NuGet.VisualStudio.Implementation.dll!NuGet.VisualStudio.VsPackageInstaller.InstallInternalCoreAsync(NuGet.PackageManagement.NuGetPackageManager packageManager, NuGet.PackageManagement.GatherCache gatherCache, NuGet.ProjectManagement.NuGetProject nuGetProject, NuGet.Packaging.Core.PackageIdentity package, System.Collections.Generic.IEnumerable<NuGet.Protocol.Core.Types.SourceRepository> sources, NuGet.VisualStudio.VSAPIProjectContext projectContext, bool includePrerelease, bool ignoreDependencies, System.Threading.CancellationToken token)       Unknown
      NuGet.VisualStudio.Implementation.dll!NuGet.VisualStudio.VsPackageInstaller.InstallInternalAsync(EnvDTE.Project project, System.Collections.Generic.List<NuGet.Packaging.Core.PackageIdentity> packages, NuGet.Protocol.Core.Types.ISourceRepositoryProvider repoProvider, NuGet.VisualStudio.VSAPIProjectContext projectContext, bool includePrerelease, bool ignoreDependencies, System.Threading.CancellationToken token)                Unknown
    mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)  Unknown
               mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)           Unknown
               mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Unknown
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()                Unknown
mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()                Unknown
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()                Unknown
               mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()                Unknown
               mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()                Unknown
               mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItemHelper()  Unknown
mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()                Unknown
               mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()             Unknown
               mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Unknown

**Comment by rrelyea** [comment]
Internal bug 366059 is a duplicate issue with a different repro.

**Comment by rrelyea** [comment]
Status on improved fix?

**Comment by mishra14** [comment]
merged: https://github.com/NuGet/NuGet.Client/commit/f8cdb19f67edd0dc47eb25ddc946bdc38d2b9b96 and https://github.com/NuGet/NuGet.Client/commit/4102576776ec65d9a5b79ed05ef7d7b5c2d0bfdc
