### ISSUE TITLE
Visual Studio deadlocks if you attempt to close a project before NuGet restore has finished

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4257]
Ported from: https://github.com/dotnet/roslyn-project-system/issues/1104 (filed by @davkean)

26107.1.d15prel
Create new Empty Web Application
Close Solution and VS
Open Solution
File -> Close Solution before NuGet restore has started/finish
--Deadlock--
If I did this quickly, was I able to deadlock VS 100% of the time.
Dump: [internalMLshare]\public\davkean\project-system\1104

**Comment by davkean** [comment]
@AArnott [also ran into this](https://github.com/dotnet/roslyn-project-system/issues/1172#issuecomment-272971945), here's another dump: `\\andarno1\public\dumps\roslyn-project-system#1172`.

**Comment by AArnott** [comment]
Just hit this again. A new dump uploaded to the same location as listed above.

**Comment by davkean** [comment]
Here's another one: https://github.com/dotnet/roslyn-project-system/issues/1188, in particular hang on shutdown in [internal file share]\public\nicholg\roslyn-project-system_1189.

**Comment by davkean** [comment]
Make note I noticed that sometimes NuGet restore never happens, meaning that you will hit this regardless of how long you wait.
