### ISSUE TITLE
Package is not compatible with net45 (.NETFramework,Version=v4.5)

### ISSUE THREAD

**Issue by kamennikolov** [NuGet/Home#4259]
Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx):  3.5.0.1938

dotnet.exe --version (if appropirate): 4.5

VS version (if appropriate): 2015

OS version (i.e. win10 v1607 (14393.321)): win10 v1511 10586.753

Worked before? If so, with which NuGet version: Works fine for my colleagues. Used to work on my PC as well before I re-installed windows and VS, so the issue is specific for my PC only.

## Detailed repro steps so we can see the same problem

1. I'm calling nuget.exe -restore

2. The error message that I'm getting is :
Package NUnit 3.5.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package NUnit 3.5.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profile=n
et45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
Package Moq 4.5.16 is not compatible with net45 (.NETFramework,Version=v4.5). Package Moq 4.5.16 supports: net45 (.NETFr
amework,Version=v4.5)
Package Castle.Core 3.3.3 is not compatible with net45 (.NETFramework,Version=v4.5). Package Castle.Core 3.3.3 supports:

  - net35 (.NETFramework,Version=v3.5)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - net45 (.NETFramework,Version=v4.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl5 (Silverlight,Version=v5.0)
One or more packages are incompatible with .NETFramework,Version=v4.5.
Package NUnit 3.5.0 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package NUnit 3.5.0 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profile=n
et45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
Package Moq 4.5.16 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package Moq 4.5.16 supports: net45 (
.NETFramework,Version=v4.5)
Package Castle.Core 3.3.3 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package Castle.Core 3.3.3 sup
ports:
  - net35 (.NETFramework,Version=v3.5)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - net45 (.NETFramework,Version=v4.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl5 (Silverlight,Version=v5.0)
One or more packages are incompatible with .NETFramework,Version=v4.5 (win).

The project.json file looks like this:
{
   "dependencies": {
      "Microsoft.PowerShell.3.ReferenceAssemblies": "1.0.0",
      "NUnit": "3.5.0",
      "Moq": "4.5.16",
      "VMware.VimAutomation.Sdk.Impl": "*"
   },
  "frameworks": {
    "net45": {}
  },
  "runtimes": {
    "win": {}
  }
}

I don't understand why nuget says that the package does not support net45 and at the same time says that it does support net45.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

Errors in C:\projects\vicore4powercli\main\test\VMware.VimAutomation.ViCore.UnitTest\VMware.VimAutomation.ViCore.UnitTes
t.csproj
    Package NUnit 3.5.0 is not compatible with net45 (.NETFramework,Version=v4.5). Package NUnit 3.5.0 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profi
le=net45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
    Package Moq 4.5.16 is not compatible with net45 (.NETFramework,Version=v4.5). Package Moq 4.5.16 supports: net45 (.N
ETFramework,Version=v4.5)
    Package Castle.Core 3.3.3 is not compatible with net45 (.NETFramework,Version=v4.5). Package Castle.Core 3.3.3 suppo
rts:
      - net35 (.NETFramework,Version=v3.5)
      - net40-client (.NETFramework,Version=v4.0,Profile=Client)
      - net45 (.NETFramework,Version=v4.5)
      - sl4 (Silverlight,Version=v4.0)
      - sl5 (Silverlight,Version=v5.0)
    One or more packages are incompatible with .NETFramework,Version=v4.5.
    Package NUnit 3.5.0 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package NUnit 3.5.0 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profi
le=net45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
    Package Moq 4.5.16 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package Moq 4.5.16 supports: net
45 (.NETFramework,Version=v4.5)
    Package Castle.Core 3.3.3 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package Castle.Core 3.3.3
 supports:
      - net35 (.NETFramework,Version=v3.5)
      - net40-client (.NETFramework,Version=v4.0,Profile=Client)
      - net45 (.NETFramework,Version=v4.5)
      - sl4 (Silverlight,Version=v4.0)
      - sl5 (Silverlight,Version=v5.0)
    One or more packages are incompatible with .NETFramework,Version=v4.5 (win).

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by emgarten** [comment]
I copied the project.json file shown in the issue and ran: ``nuget.exe restore project.json``

I get a dependency conflict instead of a compat error

```
Failed to resolve conflicts for .NETFramework,Version=v4.5.
Unable to satisfy conflicting requests for 'nunit': project/nunit (>= 1.0.0) (via project/nunit 1.0.0)
Unable to satisfy conflicting requests for 'Microsoft.PowerShell.3.ReferenceAssemblies': Microsoft.PowerShell.3.ReferenceAssemblies (>= 1.0.0) (via project/nunit 1.0.0)
Unable to satisfy conflicting requests for 'NUnit': NUnit (>= 3.5.0) (via project/nunit 1.0.0)
Unable to satisfy conflicting requests for 'Moq': Moq (>= 4.5.16) (via project/nunit 1.0.0)
Unable to satisfy conflicting requests for 'VMware.VimAutomation.Sdk.Impl': VMware.VimAutomation.Sdk.Impl  (via project/nunit 1.0.0)
Unable to satisfy conflicting requests for 'Castle.Core': Castle.Core (>= 3.3.3) (via package/Moq 4.5.16)
Unable to resolve 'VMware.VimAutomation.Sdk.Impl' for '.NETFramework,Version=v4.5'.
```

@kamennikolov can you run ``nuget.exe locals -clear all`` and try again, or see if you get different results when restoring the project.json file directly.

It could be that a project reference is changing your restore graph and giving you different results.

**Comment by emgarten** [comment]
@kamennikolov  I'm not able to repro this, have you modified any of these packages locally?

Try: ``nuget.exe locals -clear all``

I had to remove a package that wasn't found: VMware.VimAutomation.Sdk.Impl

Here is my output:

```
D:\tmp\nunit-test> D:\tmp\NuGet.3.5.0.exe restore .\project.json
Restoring packages for D:\tmp\nunit-test\project.json...
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.powershell.3.referenceassemblies/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.powershell.3.referenceassemblies/1.0.0/microsoft.powershell.3.r
eferenceassemblies.1.0.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/nunit/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/nunit/3.5.0/nunit.3.5.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/moq/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/moq/4.5.16/moq.4.5.16.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/castle.core/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/castle.core/3.3.3/castle.core.3.3.3.nupkg
Installing Castle.Core 3.3.3.
Installing Moq 4.5.16.
Installing NUnit 3.5.0.
Installing Microsoft.PowerShell.3.ReferenceAssemblies 1.0.0.
Committing restore...
Writing lock file to disk. Path: D:\tmp\nunit-test\project.lock.json
D:\tmp\nunit-test\project.json
Restore completed in 650ms.
```

**Comment by kamennikolov** [comment]
I did nuget locals -clear all, but that didn't help either. I haven't modified the packages locally. As I mentioned none of my colleagues can reproduce this either, so it's an issue on my machine only, but I'm trying to find a solution or workaround. The message itself is really confusing. In the same message it says that the package is not compatible with net45 and that it supports net45
`Package Moq 4.5.16 is not compatible with net45 (.NETFramework,Version=v4.5). Package Moq 4.5.16 supports: net45 (.NETFramework,Version=v4.5).`
What could cause such a behavior?

**Comment by kamennikolov** [comment]
I tried installing Visual Studio 2017 and now everything works fine in both VS2015 and 2017. I have no idea how, but that fixed the issue.

**Comment by rrelyea** [comment]
that is strange. vs2017 shouldn't change the behavior of vs2015.
I guess, perhaps vs2017 has a bug fixed and vs2015 was able to benefit from the result in the project.lock.json file, or similar?
Longer term, NuGet 4.0 (the version we are building for vs2017) will likely be available for VS2015...

**Comment by qmfrederik** [comment]
@emgarten @rrelyea I can reproduce this behavior on VS2017 Preview. Looking at the NuGet package structure, the assemblies are located in `lib\{TFM}\AnyCPU\`, for example `lib\net20\AnyCPU\Vlc.DotNet.Forms.dll`. Did anything change in recent NuGet versions which would now cause it to reject files in the `AnyCPU` subfolder?

The error message is also extremely confusing.

**Comment by emgarten** [comment]
@qmfrederik there haven't been any changes in this area. Do you have a repro you can share?

**Comment by qmfrederik** [comment]
@emgarten This should do the trick:

project.cspoj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vlc.DotNet.Core.Interops" Version="2.2.0-develop161" />
  </ItemGroup>
</Project>
```

And then:

```
dotnet restore
```

This gives me:

```
C:\Users\frede\demo\tests>dotnet restore
  Restoring packages for C:\Users\frede\demo\tests\LibVlcSample.csproj...
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202: Package Vlc.DotNet.Core.Interops 2.2.0-develop161 is not compatible with net45 (.NETFramework,Version=v4.5). Package Vlc.DotNet.Core.Interops 2.2.0-develop161 supports:\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net20 (.NETFramework,Version=v2.0)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net35 (.NETFramework,Version=v3.5)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net40 (.NETFramework,Version=v4.0)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5)
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202: Package Vlc.DotNet.Core.Interops 2.2.0-develop161 is not compatible with net45 (.NETFramework,Version=v4.5) / win7-x86. Package Vlc.DotNet.Core.Interops 2.2.0-develop161 supports:\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net20 (.NETFramework,Version=v2.0)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net35 (.NETFramework,Version=v3.5)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net40 (.NETFramework,Version=v4.0)\r
C:\Users\frede\demo\tests\LibVlcSample.csproj : error NU1202:   - net45 (.NETFramework,Version=v4.5)
  Generating MSBuild file C:\Users\frede\demo\tests\obj\LibVlcSample.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\frede\demo\tests\obj\LibVlcSample.csproj.nuget.g.targets.
  Restore failed in 111.82 ms for C:\Users\frede\demo\tests\LibVlcSample.csproj.
```

**Comment by emgarten** [comment]
@qmfrederik thanks so much for helping track this down! I believe this is what causes *most* of the issues where a package is reported as incompatible, but then the same framework is shown as compatible.

The package in the original issue doesn't have the same problem as VLC, but from the initial report it sounds like that scenario doesn't repro consistently. That part may be improved with other changes that have gone into NuGet 4.x already.

**Comment by BruceWangNo1** [comment]
For those who ran into error NU1201, you might have come to the right place. This may not apply to the question asked but I ran into error NU1201 the other day and the reason for that is the nuproj configuration file for our nuget project has target configuration wrong. It should have been 

> `<TargetFrameworkVersion>v4.6.2</TargetFrameworkVersion>`

 instead of 

> `<TargetFramework>net462</TargetFramework>`

 because the project is not of "SDK-style."

References: [https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019)
