### ISSUE TITLE
VS perf regression

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4261]
Perf: ManagedLangs_CS_DDRIT.0200.Open Solution regressed Duration_TotalElapsedTime by 50.220 ms

internal bug# 297627

**Comment by rrelyea** [comment]
@jainaashish - has a fix in validation that may win back 18-20ms.

**Comment by rrelyea** [comment]
Update?

**Comment by jainaashish** [comment]
Merged to release-4.0.0-rc3 with e38f51cf510b0ab0cfaeae4a9083a9e69f7715b4

**Comment by jainaashish** [comment]
reverted from release-4.0.0-rc3 since it's now marked for RTM. So only merged to dev
