### ISSUE TITLE
Nuget3.4.4.1321.exe: Pack Command is not taking dependency from project.json. Nuget3.5.0.1938.exe: Restore Command is not installing transitive dependency.

### ISSUE THREAD

**Issue by KrupaMoliya** [NuGet/Home#4262]
**Nuget3.4.4.1321.exe: Pack Command is not taking any dependency from project.json. Nuget3.5.0.1938.exe: Restore Command is not restoring transitive dependency.**

## Details about Problem
NuGet product NuGet.exe
NuGet version 3.4.4.1321, 3.5.0.1938

Worked before? If so, with which NuGet version: 2.8.3

I am using nuget commands to build my project.
I have BuildDependsOn sequence as below:
1) NuGet.exe restore "$(ProjectPath)" -source "$(PackageSource)" -nocache -NonInteractive -RequireConsent
2) NuGet.exe pack "$(ProjectPath)" -Properties "Configuration=$(Configuration);Platform=$(Platform)" -NonInteractive -OutputDirectory "$(PackageOutputDir)" -includereferencedprojects -version "$(InformationalVersion)"
3) NuGet.exe push "$(PackageOutputDir)\*.nupkg" -source "$(PackageSource_Publish)" -apiKey "$(apiKey)" 

I have one Project "ClassLibrary1" Which is using reference of LightInject, so Project.json file as below
{
  "dependencies": {
    "LightInject": "[4.0.2]"
  },
  "frameworks": {
    "net46": {
    }
  },
    "runtimes":  {
        "win-x86": {},
        "win": {}
    }
}

****Issue:** Here Pack command is not creating nuget package with "LightInject" dependence.

**Solution:**
1) I can create nuspec file at csproj level and i can add  "LightInject" in that which works fine.
   But it's a repetitive. I have to mention package and it's version at 2 place (in project.json and in ClassLibrary1.csproj.nuspec)
   
2) I have upgraded to Nuget3.5.0.1938.exe.
   This is creating packages with it's dependencies. It takes all information from project.json like copyrights, author etc.

**So I Prefer option 2 and upgraded to nuget3.5.exe**
But Nuget3.5.0.1938.exe is not restoring transitive dependencies while Nuget3.4.4.1321.exe is installing  transitive dependencies.

I have one Project "ClassLibrary1" Which is using reference of LightInject.
ClassLibrary1 -->LightInject
Rebuild ClassLibrary1 : It restores LightInject package

I have one Project "ClassLibrary2" Which is using reference of ClassLibrary1 & NewtonsoftJson.
ClassLibrary2 -->NewtonsoftJson
Rebuild ClassLibrary2 : It restores NewtonsoftJson, ClassLibrary1 & LightInject package

I have one Project "ClassLibrary3" Which is using reference of ClassLibrary2.
ClassLibrary3 -->ClassLibrary2
Rebuild ClassLibrary3 : It restores ClassLibrary2, NewtonsoftJson & LightInject package

**Issue is nuget3.5 is not restoring ClassLibrary1.** 
If i install manually from visual studio, It restores ClassLibrary1.
Is i use nuget3.4exe it also restores ClassLibrary1.

-------------------------------------------------------------
So I am using nuget3.4 for restore, and nuget 3.5 for pack and push
Please check my nuget.target line 61.62.63 in attached code.

Is there any why i can achieve with only version. wither 3.4 or 3.5?
Is these 2 known issue in respective version

**Comment by KrupaMoliya** [comment]
[automation.zip](https://github.com/NuGet/Home/files/701262/automation.zip)

**Comment by zhili1208** [comment]
Project.json is deprecated, please move to package reference
