### ISSUE TITLE
Reference is not seen by C# despite the fact that it is in project.json

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4265]
See internal bug 366763:
The problem is in that I had local package source (folder) that didn’t contain any packages and nuget produced error in the output window that it could not find anything there. When I switched off the source in Tools | Options, the reference was finally added.

RR: not sure if our change of behavior is correct here. I'd think that a local folder that is empty shouldn't provide an error, right?

/cc @emgarten

**Comment by emgarten** [comment]
Any empty folder should be fine. A missing folder is a problem usually.
