### ISSUE TITLE
Remove element form of Version in PackageReference documenation, use attribute everywhere

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4270]
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

(don't even mention that it can be used as an element)

**Comment by kraigb** [comment]
@rrelyea Changes made. Please verify and close this issue.

**Comment by seangwright** [comment]
@rrelyea If it isn't supposed to be mentioned that `Version` can be used as an element, why am I experiencing this exact behavior in VS2017 when using the `<PackageReference>` approach to managing packages for a .net 4.7.1 ASP.NET WebForms project?

Is this something that is expected to change in the future?
Should I manually change all the updates of my .csproj from Nuget that include a `<Version>` element to use an attribute instead?

Myself and someone else have asked this question in the docs that were updated
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
