### ISSUE TITLE
investigate localization risk (build tool)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4271]
24 of 100 files changed with localization improvements are in 26106.10.
87 of 100 files are in 26112.00.
100 of 100 files would be in next build of RC3, if done.

We've just discovered this. Writing validation tool to confirm resources are complete in each language and the same set of {0}, {1}, etc... -- in each version of the string.

**Comment by mishra14** [comment]
Tool is ready at https://github.com/mishra14/NuGetBuildValidators and https://github.com/NuGet/Entropy/tree/master/NuGetBuildValidators

No risks detected. Closing this issue. I have opened another issue related to integrating the tool into our pipeline : https://github.com/NuGet/Home/issues/4305
