### ISSUE TITLE
NuGet opens the output window during background restore

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4274]
NuGet has a annoying behavior where it opens the Output window during restore. This might be okay for a certain operations such as explicit clicking of Restore solution, but it's annoying when it happens because of something completely unrelated such as editing the project file, or changing TFM for the Project properties.

Can we change this behavior?

**Comment by rrelyea** [comment]
Need to discuss what we want here, and when we want it...as part of our ui improvements in this area.

**Comment by davidfowl** [comment]
I thought we had a design for the notification window. Forcing the output window to show up is super annoying.

**Comment by davkean** [comment]
Been playing with this for a while now - and the current behavior is super annoying.

**Comment by davidfowl** [comment]
@rrelyea What's the status of the background restore notification? Are we going to get something for RTM?
