### ISSUE TITLE
[Test Failure] Many Errors occur when creating .NET Core xUnit Test Project due to restore failed

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4276]
**NuGet Version:** NuGet 4.0.0-RC3-2206
**VS Version:** D15PreRel 26112.00
**OS Version:** Windows 10 RS1_Release 14393.723.170109-1801
 
**Repro Steps:**
1.  Launch VS.
2.  Create a Visual C#->.NET Core->xUnit Test Project (.NET Core) template.
3.  Build the solution.

**Expected Result:**
No error show in Error List Window.

**Actual Result:**
There are so many errors (CS0246) show in Error List Window and restore failed message show at the bottom of VS as below screenshot.
![xunittestproject](https://cloud.githubusercontent.com/assets/20632625/21976579/80a0f3a0-dc0d-11e6-9350-48f0888e5fec.PNG)
**Error Info:**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'xunit (>= 2.2.0-beta5-build3474)' for '.NETCoreApp,Version=v1.0 (win-x64)'.			0	
Error	CS0246	The type or namespace name 'Xunit' could not be found (are you missing a using directive or an assembly reference?)	XUnitTestProject2	c:\users\mdtestau\documents\visual studio 2017\Projects\XUnitTestProject2\XUnitTestProject2\UnitTest1.cs	2	Active
Error	CS0246	The type or namespace name 'FactAttribute' could not be found (are you missing a using directive or an assembly reference?)	XUnitTestProject2	c:\users\mdtestau\documents\visual studio 2017\Projects\XUnitTestProject2\XUnitTestProject2\UnitTest1.cs	8	Active
Error	CS0246	The type or namespace name 'Fact' could not be found (are you missing a using directive or an assembly reference?)	XUnitTestProject2	c:\users\mdtestau\documents\visual studio 2017\Projects\XUnitTestProject2\XUnitTestProject2\UnitTest1.cs	8	Active
Error		Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0-beta5-build1225)' for '.NETCoreApp,Version=v1.0 (win)'.			0	
Error		Unable to resolve 'xunit (>= 2.2.0-beta5-build3474)' for '.NETCoreApp,Version=v1.0 (win-x86)'.			0	
Error		Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0-beta5-build1225)' for '.NETCoreApp,Version=v1.0 (win-x86)'.			0	
Error		Unable to resolve 'xunit (>= 2.2.0-beta5-build3474)' for '.NETCoreApp,Version=v1.0'.			0	
Error		Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0-beta5-build1225)' for '.NETCoreApp,Version=v1.0 (win-x64)'.			0	
Error		Unable to resolve 'xunit.runner.visualstudio (>= 2.2.0-beta5-build1225)' for '.NETCoreApp,Version=v1.0'.			0	
Error		Unable to resolve 'xunit (>= 2.2.0-beta5-build3474)' for '.NETCoreApp,Version=v1.0 (win)'.			0	

**Note:**
1. It also repro on D15Rel 26112.00+Nuget Client 4.0.0-RC3-2211.

**Comment by rrelyea** [comment]
Think that a new package was pushed to nuget.org to fix this issue. please confirm.

**Comment by v-luzh** [comment]
@rrelyea Yes, it is fixed on D15Rel 26117.00 (NuGet Client 4.0.0-RC3-2215). Thanks.
