### ISSUE TITLE
update packages on .net core projects not working

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4278]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.0.0

VS version (if appropriate): visual studio 2015 update 3

Worked before? If so, with which NuGet version: 3.5.0

## Detailed repro steps so we can see the same problem

1. Create a new .net core class library project
2. open nuget manager ui and go to update tab. it will show 1 update available.
3. try to update package, it will fail with below error
`The given key was not present in the dictionary.`

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
