### ISSUE TITLE
Improve PMC errors for projects that do not support nuget

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4281]
Improve PMC errors for projects that do not support nuget

NuGet 4.0.0-rc3 on VS 2017 (not a regression)

### Steps
1. Create a new Azure Data Lake > Pig Application
1. Install-Package nuget.versioning

### Expected
A friendly message saying that the project does not support NuGet.

### Actual
![image](https://cloud.githubusercontent.com/assets/6381138/21947661/1bc62e7e-d99b-11e6-8831-b774061839f3.png)

The UI solves this by disabling the Manage NuGet Packages, PMC should handle this better also.

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/Home/issues/9421. That's newer but has more detail and there's no customers tracking this report.
