### ISSUE TITLE
Visual Studio package manager not updated when NuGet.config is edited

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#4285]
## Details about Problem

NuGet product used: VS UI
NuGet version (x.x.x.xxx): 3.5.0
VS version (if appropriate): VS 2015 Update 3
OS version (i.e. win10 v1607 (14393.321)): win10 14393.693

Worked before? If so, with which NuGet version: Never worked

## Detailed repro steps so we can see the same problem

1. Add a NuGet.config to the solution level directory
2. Add a new source there
3. Go to the Package Manager and it won't be there
4. Restart VS, and it'll be there

This can also be done if you already have a NuGet.config and add a new entry to it

**Comment by zhili1208** [comment]
this is by design, user need to add source through Setting UI, otherwise need to reopen solution to make UI update

**Comment by twsouthwick** [comment]
Can this be documented? The Setting UI doesn't allow this kind of change, but it's not obvious it would require a restart since restore still works; just that UI doesn't update.

**Comment by zhili1208** [comment]
Sure, I filed a bug to ask a doc change for this: https://github.com/NuGet/Home/issues/6055
