### ISSUE TITLE
after rename of a .NET Core project, restore becomes broken until you unload project and reload it

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4287]
VS 2017 26114.00 (rc3 not final)

Unsure if this would take a RoslynProjectSystem/NuGet or both…

1.	Create a NetStandard project named ClassLibraryNetStandard
2.	Rename the project ClassLibraryNetStandard14
3.	Build

Expected: no error, restore works

Actual: In build output window, see a message: Error occurred while restoring NuGet packages: The operation failed as details for project ClassLibraryNetStandard14 could not be loaded.

Workaround: unload + reload project or close solution/open solution.
or: 	hand edit the project file and add/remove or change a package reference, and the Project and NuGet will be in sync again enabling NuGet package operations

**Comment by alpaix** [comment]
NuGet project info cache gets out of sync after rename has happened as CPS won't nominate the project.
Need to discuss the best way to resolve this issue on either side.

**Comment by natidea** [comment]
This can be duped against https://github.com/dotnet/roslyn-project-system/issues/1293

**Comment by alpaix** [comment]
Verified in RC.4 26201.1. Closing...
