### ISSUE TITLE
msbuild restore ouput with /v:minimal is not minimal

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4288]
## Detailed repro steps so we can see the same problem

1. Clone https://github.com/srivatsn/roslyn-project-system/tree/dogfood (or any PackageReference based project)

2. msbuild src\ProjectSystem.sln /t:restore /v:minimal 

Expected: Something minimal - For each project whether restore succeeded or not.

Found: The regular output which is a lot.

**Comment by nkolev92** [comment]
Fixed a while back...now it's 1 line per project.
