### ISSUE TITLE
Update-Package -reinstall does not reinstall in packages folder

### ISSUE THREAD

**Issue by michaelw-au** [NuGet/Home#4292]
I want to develop changes to PackageA and test them from a consuming project "ConsumerApp" as I go, without constantly changing the package version. For local iteration and testing on the package before the real release. 

I'm using these steps:

1. Build a change to PackageA, without incrementing the version.
2. Re-publish PackageA to a local feed, on my development machine. This works fine (I delete the previous instance first). 
3. Force that new package into ConsumerApp to test the change. From Package Manager Console:  `Update-Package -Reinstall PackageA -ProjectName ConsumerApp`
(See log output below)

But the result is the older version of the package is still in the packages folder (under the Visual Studio solution). I can tell from the contents.
I expected it to get the re-built and re-published package. 

Possibly related: I can't manually delete the folder `C:\dev\ConsumerApp\code\packages\PackageA.1.0.0`, while Visual Studio is open. I think VS has it locked somehow. As soon as I close VS I can delete the folder. 
Could the Update-Package command be hitting the same restriction? I assume it should be removing that folder as part of the reinstall. If the command is trying and failing to do this, it's silent about it.

Other notes:
- This package only exists at the local feed. Not in any other package source.
- This package is published with symbols (so includes a src folder under the packages\PackageA folder)
- The local feed is at the top of my package sources in Visual Studio.
- The log below indicates it is retrieving again from the Local feed, but later also says `Package 'PackageA.1.0.0' already exists in folder 'C:\dev\ConsumerApp\code\packages'`.
- In practice you might increase the version the first time you start iterating, to avoid a clash with the version previously released. But you'll hit the same problem on the iteration after that.

Products used:
Package Manager Console Host Version 3.5.0.1996
NuGet Version: 3.5.0.1938
Visual Studio 2015 Update 1
Windows 7.

    PM> Update-Package -Reinstall PackageA -ProjectName ConsumerApp -Verbose
    
    
    Attempting to gather dependency information for multiple packages with respect to project 'ConsumerApp', targeting '.NETFramework,Version=v4.5.2'
      GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='AWSSDK.S3'
      GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='AWSSDK.Core'
      GET https://api.nuget.org/v3/registration1-gz/awssdk.s3/index.json
      GET https://api.nuget.org/v3/registration1-gz/awssdk.core/index.json
      OK https://api.nuget.org/v3/registration1-gz/awssdk.s3/index.json 577ms
      OK https://api.nuget.org/v3/registration1-gz/awssdk.core/index.json 1243ms
      OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='AWSSDK.Core' 1245ms
      OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='AWSSDK.S3' 1273ms
    Total number of results gathered : 47
    Gathering dependency information took 3.99 sec
    Summary of time taken to gather dependencies per source :
    https://api.nuget.org/v3/index.json	-	3.86 sec
    C:\dev\ConsumerApp\code\packages	-	3.83 ms
    C:\work\nugetLocal	-	1.56 ms
    https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/	-	2.8 sec
    Z:\dev\nuget	-	19.36 ms
    Attempting to resolve dependencies for multiple packages.
    Resolving dependency information took 0 ms
    Resolving actions install multiple packages
    Retrieving package 'PackageA 1.0.0' from 'Local'.
    Retrieving package 'AWSSDK.S3 3.1.3.13' from 'C:\dev\ConsumerApp\code\packages'.
    Retrieving package 'AWSSDK.Core 3.1.4.3' from 'C:\dev\ConsumerApp\code\packages'.
    Removed package 'PackageA 1.0.0' from 'packages.config'
    Removed reference 'PackageA.dll' from project 'ConsumerApp'
    Successfully uninstalled 'PackageA 1.0.0' from ConsumerApp
    For adding package 'AWSSDK.S3 3.1.3.13' to project 'ConsumerApp' that targets 'net452'.
    Executing script file 'C:\dev\ConsumerApp\code\packages\AWSSDK.S3.3.1.3.13\tools\uninstall.ps1'
    Removed package 'AWSSDK.S3 3.1.3.13' from 'packages.config'
    Removed reference 'AWSSDK.S3.dll' from project 'ConsumerApp'
    Successfully uninstalled 'AWSSDK.S3 3.1.3.13' from ConsumerApp
    Removed package 'AWSSDK.Core 3.1.4.3' from 'packages.config'
    Removed reference 'AWSSDK.Core.dll' from project 'ConsumerApp'
    Successfully uninstalled 'AWSSDK.Core 3.1.4.3' from ConsumerApp
    For adding package 'AWSSDK.Core.3.1.4.3' to project 'ConsumerApp' that targets 'net452'.
    For adding package 'AWSSDK.Core.3.1.4.3' to project 'ConsumerApp' that targets 'net452'.
    Package 'AWSSDK.Core.3.1.4.3' already exists in folder 'C:\dev\ConsumerApp\code\packages'
    Added reference 'AWSSDK.Core' to project 'ConsumerApp'.
    Added package 'AWSSDK.Core.3.1.4.3' to 'packages.config'
    Successfully installed 'AWSSDK.Core 3.1.4.3' to ConsumerApp
    For adding package 'AWSSDK.S3.3.1.3.13' to project 'ConsumerApp' that targets 'net452'.
    For adding package 'AWSSDK.S3.3.1.3.13' to project 'ConsumerApp' that targets 'net452'.
    Package 'AWSSDK.S3.3.1.3.13' already exists in folder 'C:\dev\ConsumerApp\code\packages'
    Added reference 'AWSSDK.S3' to project 'ConsumerApp'.
    Added package 'AWSSDK.S3.3.1.3.13' to 'packages.config'
    For adding package 'AWSSDK.S3.3.1.3.13' to project 'ConsumerApp' that targets 'net452'.
    Executing script file 'C:\dev\ConsumerApp\code\packages\AWSSDK.S3.3.1.3.13\tools\install.ps1'
    Successfully installed 'AWSSDK.S3 3.1.3.13' to ConsumerApp
    For adding package 'PackageA.1.0.0' to project 'ConsumerApp' that targets 'net452'.
    For adding package 'PackageA.1.0.0' to project 'ConsumerApp' that targets 'net452'.
    Package 'PackageA.1.0.0' already exists in folder 'C:\dev\ConsumerApp\code\packages'
    Added reference 'PackageA' to project 'ConsumerApp'.
    Added package 'PackageA.1.0.0' to 'packages.config'
    Successfully installed 'PackageA 1.0.0' to ConsumerApp
    Executing nuget actions took 9.84 sec
    Time Elapsed: 00:00:13.8853613

**Comment by bjartekh** [comment]
I have experienced the exact same thing, and I also tested this with a 3rdparty package (not just locally development).

What we are trying to achieve is the following:

> Reinstalling a package during its development: 
> Package authors often need to reinstall the same version of package they're developing to test the behavior. The Install-Package command does not provide an option to force a reinstall, so use Update-Package -reinstall instead.
> 

Retrieved from the Microsoft docs:
https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages




Products used:
Nuget Package manager 4.2.0
NuGet Version: 4.1.0.2450
Microsoft Visual Studio Enterprise 2017 Version 15.2 (26430.14) Release
Windows 10

The work-around is to uninstall and install the package again.

**Comment by AbdallahAbuHashem** [comment]
The issue happens because the directory for the package does not get deleted. However, this is not because of a lock as the original post mentions. For performance reasons, `-Reinstall` flag does not delete the existing directories, but rather deals with broken references to a package as mentioned in the top of this page: https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages

In testing, we recommend you run `uninstall-package`, and `install-package`, which should give the expected behavior.

**Comment by SimonSDA** [comment]
I have a similar workflow regarding package development, however none of the solutions above work for me. If I do either update-package or uninstall-package / install-package it does not replace the current version as it seems to hang around in the NuGet cache. The only (tedious) thing I've found that works is to clear the nuget cache for the solution then do a package restore.
