### ISSUE TITLE
Restore failing on newly created xunit Test project 

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4296]
**Repro Steps**
Create new Project -> .NetCore -> xunit Test Project (.Net Core)

**Expected** 
restores successfully

**Actual**
![image](https://cloud.githubusercontent.com/assets/12449387/21997071/1920be66-dbe2-11e6-80a1-2b7112cfb3fc.png)

**Build**
26114.2.d15rel

**Comment by bradwilson** [comment]
I've just pushed the packages to NuGet. They should be available in the next few minutes.

**Comment by jinujoseph** [comment]
i can confirm that this works now .. 

I am getting 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1912,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by rrelyea** [comment]
@jinujoseph - that last issue sounds like a SDK/build issue, right? If so, can you please open an issue in that world and close this one?

**Comment by jinujoseph** [comment]
filed 368788 in vs repo to follow-up on warning.
