### ISSUE TITLE
NuGet Package Manager Always Returns to Installed Tab Rather than Last Tab

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4299]
_From @MarkMichaelis on January 16, 2017 21:35_

Each time you open up NuGet Package manager it returns to the Installed Tab rather than the last used tab, as the (for example) Browse tab which, at least for me, is far more common.
cc: @GrantErickson

_Copied from original issue: dotnet/roslyn-project-system#1193_

**Comment by srivatsn** [comment]
_From @scottaddie on January 16, 2017 22:14_

Related issue that I logged a while back [here](https://github.com/NuGet/Home/issues/2353). Would be nice to make this behavior configurable.

**Comment by zhili1208** [comment]
I tried this in VS 2017 15.4.3, if you reopen the same project which is opened before, Package Manager will return to the last used tab., looks like it's fixed. close it
