### ISSUE TITLE
Choose "NuGet Package Manager Format" dialog looks bad under dark theme

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4300]
![image](https://cloud.githubusercontent.com/assets/1103906/22002562/1dfe37c8-dca1-11e6-90de-d17d6eabb36a.png)

**Comment by davkean** [comment]
On behalf of @bradwilson.

**Comment by clairernovotny** [comment]
Related: no one knows what "Packages.config" or "PackageReference" means. Impossible for most people to make/understand the choice here.

**Comment by davkean** [comment]
@onovotny Can you open a different bug on that? That comment will get lost in this bug.

**Comment by clairernovotny** [comment]
Done in #4301
