### ISSUE TITLE
NuGet Package Manager dialog confused with netcoreapp1.0 TFM

### ISSUE THREAD

**Issue by scottaddie** [NuGet/Home#4302]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
```
VS 2017 RC3 UI with NuGet 4.0.0
```

NuGet version (x.x.x.xxx):
```
4.0.0
```

dotnet.exe --version (if appropriate):
```
1.0.0-rc3-004504
```

VS version (if appropriate):
```
15.0.26114.2 D15REL
```

OS version (i.e. win10 v1607 (14393.321)):
```
win10 v1607 (14393.576)
```

Worked before? If so, with which NuGet version:
```
No
```

## Detailed repro steps so we can see the same problem

1. Clone the following project: https://github.com/scottaddie/DotNetCoreSampleApp

2. Open the solution, right-click the project in Solution Explorer, choose the **Manage NuGet Packages** option, click the **Updates** tab, check the **Select all packages** checkbox, and click the **Update** button

3. After successfully updating the packages, the **Updates** tab in the **Manage NuGet Packages** dialog still indicates that updates are available:
![nuget_updates](https://cloud.githubusercontent.com/assets/10702007/22004206/b8e34abe-dc0e-11e6-9a69-e88f49b95e94.png)

If you click the refresh icon, the dialog shows that no updates are available.

## Other suggested things
If you start with the "netcoreapp1.1" TFM before updating packages via the Manage NuGet Packages dialog, this issue doesn't occur. The problem seems to be tied to the "netcoreapp1.0" TFM.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project
https://github.com/scottaddie/DotNetCoreSampleApp

**Comment by rrelyea** [comment]
#4035 sounds similar (but in vs2015)

**Comment by rrelyea** [comment]
@davidfowl - Should all 5 of these packages be handled like netcoreapp (with autoreferenced metadata?)
Should we try to stop the upgrade of these items, like with NetCoreApp?
Or is it ok to move to 1.1 and leave tfm at netcoreapp1.0?

**Comment by rrelyea** [comment]
#4035 is dupe.
