### ISSUE TITLE
NuGet outputs a bunch of warnings about duplicate imports during restore

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4304]
Build: 4.0.0.2215
VS: 26114.2 (D15Rel)

From a Visual Studio command-prompt:

1. `git clone http://github.com/donet/roslyn-project-system.git`
2. `git checkout 9f8cbdb0ca876ae037bb3e3fb0dd1bc1e70cf880`
3. Grab NuGet.exe 4.0.0.2215 and replace build\bin\nuget.exe
4. `build`

Expected: No warnings
Actual: About 50 warnings with:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Microsoft.Common.targets\ImportAfter\Microsoft.NuGet.ImportAfter.targets(22,3): warning MSB4011: "C:\Users\davkean\AppData\Local\Temp\NuGet-Scratch\gpvksigy.qfp.targets" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets (5679,3)". This is most likely a build authoring error. This subsequent import will be ignored. [E:\project-system\src\DeployTestDependencies\DeployTestDependencies.csproj] [E:\project-system\build\build.proj]
```

**Comment by rrelyea** [comment]
@zhili1208 - reviewing this code change...did we just filter this message out? are we still trying to import this thing many times. If so, concerned if this is the right fix.

**Comment by zhili1208** [comment]
Yes, we just filter this message out and we still import this thing many times for some scenario, discussed with @emgarten when we made this fix,  we didn't find a way to fix import twice at that time.
