### ISSUE TITLE
Getting local dependencies to add the correct version when `dotnet pack`ing

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#4306]
Posted on behalf of @avanderhoorn . Ported from https://github.com/dotnet/cli/issues/5151

## Steps to reproduce

Executed command
```
dotnet pack .\src\Glimpse.Common\Glimpse.Common.csproj --configuration Release --version-suffix beta2-123
dotnet pack .\src\Glimpse.Server\Glimpse.Server.csproj --configuration Release --version-suffix beta2-123
```
Target Glimpse.Common.csproj
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <AssemblyTitle>Glimpse Common</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFrameworks>net451;netstandard1.6</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Glimpse.Common</AssemblyName>
  </PropertyGroup>
...
```
Target Glimpse.Server.csproj
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <AssemblyTitle>Glimpse Server</AssemblyTitle>
    <VersionPrefix>2.0.0</VersionPrefix>
    <TargetFrameworks>net451;netstandard1.6</TargetFrameworks>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.10-x64;osx.10.11-x64;ubuntu.14.04-x64;ubuntu.16.04-x64;centos.7-x64;rhel.7.2-x64;debian.8-x64;fedora.23-x64;opensuse.13.2-x64</RuntimeIdentifiers>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>Glimpse.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Glimpse.Common\Glimpse.Common.csproj" />
  </ItemGroup>
...
```
Resulting Glimpse.Server.nuspec
```
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Glimpse Server</id>
    <version>2.0.0-beta2-123</version>
    ...
    ...
    <dependencies>
      <group targetFramework=".NETFramework4.5.1">
        <dependency id="Glimpse.Common" version="1.0.0" exclude="Build,Analyzers" />
        ...
      </group>
...
```

## Expected  behavior
I want the version of the `Glimpse.Common` dependency in above `Glimpse.Server.nuspec` to be `2.0.0-beta2-123` vs instead `1.0.0`. 

Previously with `project.json` this was all taken care of with the with the following [`pack.cmd`](https://github.com/Glimpse/Glimpse.Prototype/blob/43e6ef021473596143883501c47c94cfff77e688/pack.cmd) and by specifying dependencies like [this](https://github.com/Glimpse/Glimpse.Prototype/blob/43e6ef021473596143883501c47c94cfff77e688/src/Glimpse.Server/project.json#L10). But I can't figure out how to replicate these results with the new .csproj setup. Here is my reworked [`pack.cmd`](https://github.com/Glimpse/Glimpse.Prototype/blob/dev/pack.cmd).  

## Actual behavior
Shown above in the resulting Glimpse.Server.nuspec.

## Environment data
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by rohit21agrawal** [comment]
@avanderhoorn this is the bug that needs to be fixed for this to work : https://github.com/NuGet/Home/issues/3901

The timeframe for this is RTM, and once this is fixed, your scenario would work exactly as you expect it to.

**Comment by avanderhoorn** [comment]
Thanks! Is there any workaround in the mean time?

**Comment by rohit21agrawal** [comment]
@avanderhoorn unfortunately, no. The best you can do right now is to use the generated nuspec file in your obj folder, modify it manually and use it again to get the right package.

**Comment by rohit21agrawal** [comment]
I have unblocked @avanderhoorn which is basically to run a restore with /p:VersionSuffix argument before packing.

At this point, this is basically the dupe of : https://github.com/NuGet/Home/issues/4337

**Comment by avanderhoorn** [comment]
Thanks!
