### ISSUE TITLE
Run Add-Migration from NuGet package manager console, you get : The term 'Add-Migration' is not recognized

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4308]
from internal bug: 368394 & 372378 & 378413

REPRO STEPS
1. Create a 1.0 Core Web Application
2. F5
3. Register yourself as a user (click Register in upper right, fill in name and password, Register)
4. Add Movie.cs to the Models folder

    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
5. Add Controller - scaffold controller with EF / views
6. Ctrl-F5, navigate to http://localhost:54365/Movies 
7. Run EF migrations
Add-Migration AddMovies
Update-Database
 
ACTUAL
EF fails for me in an unexpected way:
 
PM> add-migration
add-migration : The term 'add-migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ add-migration
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (add-migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM>
 
PM> update-database
update-database : The term 'update-database' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path 
is correct and try again.
At line:1 char:1
+ update-database
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (update-database:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rrelyea** [comment]
@jainaashish has additional context here.

**Comment by zhili1208** [comment]
I think it's is due to ExecutionPolicy, Nuget can't execute the init.ps in entityframeworkcore.tool, if user log in VS as admin, nuget will set executionPolicy and run init.ps well

**Comment by rrelyea** [comment]
@zhili1208 - have you investigated default windows installations vs different VM environments to help find the cause of this?

**Comment by zhili1208** [comment]
the default windows powershell execution policy is restricted both on vm and real machine, but nuget will set executionPolicy to RemoteSigned, I tested xlab and azure vm, found out I can't repro it every time, looks like nuget can set executionPolicy correctly, but I hit this randomly, will look at it more

**Comment by rrelyea** [comment]
added new dupe bug number in first entry in this issue. 372378 - please read and confirm dupe. use that extra info (and/or the bug filer) to help reproduce the problem.

**Comment by rrelyea** [comment]
added new dupe in first entry: 378413

**Comment by MikeInSwitzerland** [comment]
Feb 2018, VS2017 v15.5.6, and this problem is still alive and kicking. 

However, what eventually fixed it for me was to go into VS2017, click on Tools\NuGet Package Manager\Package Manager Settings, then, in the General tab, click on "Clear all NuGet Cache(s)".   Then I quit VS2017, restarted VS2017, right-clicked on my Solution, and "Restore NuGet Packages".

After jumping through all of these hoops, the Add-Migration command was finally recognised.
(Sigh.)

**Comment by SMITHsharon** [comment]
all of this ^^^
Exact same error message. 
Walked through MikeInSwitzerland's fix, but on the "Restore NuGet Packages" part, getting error message, "Error occurred while restoring Nuget packages: Access to path 'C\Users ... \microsoft.codeanalysis.workspaces.common\2.6.1' is denied."

**Comment by abbastoz** [comment]
hi all for this you have to  go to tools-> nugetpackagemanager -> manage nuGut Package for solution
and install 
  Microsoft.AspNetCore.App
  Microsoft.EntityFrameworkCore.Tools" 
Microsoft.VisualStudio.Web.CodeGeneration.Design
then close vs and open it again .
reference 
https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

**Comment by petanikode-kode** [comment]
> hi all for this you have to go to tools-> nugetpackagemanager -> manage nuGut Package for solution
> and install
> Microsoft.AspNetCore.App
> Microsoft.EntityFrameworkCore.Tools"
> Microsoft.VisualStudio.Web.CodeGeneration.Design
> then close vs and open it again .
> reference
> https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/powershell

already with have it but still same issue there.

http://prntscr.com/qb86n8

Please help me i got error when runing console Update-Database
`Error Number:5123,State:1,Class:16
CREATE FILE encountered operating system error 5(Access is denied.) while attempting to open or create the physical file 'C:\Users\l-maninventory-management-codecanyon.mdf'.
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.`

http://prntscr.com/qb8ees
