### ISSUE TITLE
FrameworkReducer cannot determine nearest framework for dnx451 when choosing between net40 and aspnet50

### ISSUE THREAD

**Issue by ChengTian** [NuGet/Home#431]
In `NuGet.Frameworks`
```c#
public NuGetFramework GetNearest(NuGetFramework framework, IEnumerable<NuGetFramework> possibleFrameworks)
```
When `framework` is `dnx451` and `possibleFrameworks` contains both `net40` and `aspnet50`, it cannot determine the nearest framework and triggers an assertion failure.

This is blocking dnu refactoring, @emgarten , could you please help to tag this issue with proper labels? Thanks.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Packaging@b482b854a3b12ecc570c8eeef891f4fcdbf95f04

**Comment by ChengTian** [comment]
:+1: Thanks
