### ISSUE TITLE
ASP.NET Core VS2017 app open hangs without internet, (dotnet restore fails)

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#4310]
Copied from https://github.com/aspnet/Tooling/issues/931 per @damienbod

When I start an ASP.NET Core application in VS2017 and the application requires a nuget package from the server, and no internet connection exists, VS2017 hangs and needs to be killed.

**Comment by mlorbetske** [comment]
cc @rrelyea

**Comment by zhili1208** [comment]
@damienbod Could you share your visual studio version and nuget version?

How to check nuget version?

open package manager console from Tools/NuGet Package Manager, it will shows package console host version.

**Comment by zhili1208** [comment]
doesn't repro with VS 26117 and nuget version 4.0.0.2215

All required packages are from local feed and even I delete local feed, restoring will throw "can't connect to nuget.org" error, will not hang VS

**Comment by damienbod** [comment]
@zhili1208 
Package Manager Console Host Version 4.0.0.2098
VisualStudio/publiic.d15rel/15.0.26020.0

**Comment by zhili1208** [comment]
@damienbod I tried VS 26020 with nuget 2098, but didn't get repro, you mentioned "the application requires a nuget package from the server", do you know which package is required? Looks like all packages are from local feed.

**Comment by zhili1208** [comment]
@damienbod Ping, Do you still hit this issue?

**Comment by zhili1208** [comment]
@damienbod we just released VS 2017 RC3, could you try that one? https://www.visualstudio.com/vs/visual-studio-2017-rc/

**Comment by rrelyea** [comment]
closing as not repro. Please chime in if you repro with latest RC.
