### ISSUE TITLE
[vsfeedback] NuGet Package Manager seems to be saying the latest stable version of CsvHelper package is 1.1.0 when it's really 2.16.3 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4311]
(see vsfeedback issue 734614)
using RC2.2 -- reported by @daroth

**Comment by zhili1208** [comment]
this is dup of https://github.com/NuGet/Home/issues/4198

**Comment by rrelyea** [comment]
@danroth27 is the right alias.
