### ISSUE TITLE
[vsfeedback] votes   VS (External)  January 08  Developer Community   screenshot      watson log   .NET log    more files Select  Visual Studio 17 Community Edition - "Can't reach localhost" after nuget updates 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4312]
[see vs feedback item 735344 - reported from user using rc2.2]

I am using VS 17 Community Edition 15.0.26020.0. I created an ASPNET Core Web Application (.NET Core). Built it with no changes and it ran fine. Changed Target framework to .NETCoreApp 1.1. Again built it and it ran fine.

Then I used the "Nuget packages for Solutions" to update all the packages (some 14 packages, if I remember). Built it. Now I get "can't reach local host in the browser". Setting a breakpoint on the first line in main() shows that I never reach that code.

**Comment by zhili1208** [comment]
I got a repro with 26020 but doesn't repro with 26114, I think this is not nuget issue, Looks like dotnet.exe return error when hosting the webApp, but it's fixed in VS 26114.
