### ISSUE TITLE
[vsfeedback] VS hangs forever after package update 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4313]
[see vsfeedback item 735748]
Steps:
1- create a new ASP.NET core web application project
2- right click on the progect and click on manage NuGet packages
3- click on updates
4- click on 'select all packages' check box
5- click on 'update' button

Expected result:
NuGet packages updated to latest version (1.1.0)

Current result:
Packages are downloaded but during project file update visual studio enter an infinite loop it seems

**Comment by zhili1208** [comment]
can't repro it in d15rel 26114.2 with nuget 4.0.0.2215

**Comment by emgarten** [comment]
I'm going to close this as a dupe. The repro steps here are identical to: https://github.com/NuGet/Home/issues/4185  and this has been fixed.

I verified the repro steps in this bug many times on a solution with 10+ web app projects doing an update all across everything from the UI and was unable to get a hang after the fix.
