### ISSUE TITLE
[Test Failure] Project is not selected by default in ‘Default project’ drop box after installing a package

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4315]
**NuGet Version:** NuGet 4.0.0-rtm-2219
**VS Version:** D15Rel 26117.00
**OS Version:** Windows 10 RS1_Release 14393.726.170112-1758

**Repro Steps:**
1.	Launch VS.
2.	New a Visual C#->Windows Classic Desktop->Console App (.NET Framework) project.
3.	Open ‘Package Manager Console’ to verify the Project is selected by default in ‘Default project’ drop box .
4.	Right-click on the project and click ‘Manage NuGet Packages…’.
5.	Installing package 'Newtonsoft.Json 7.0.1'.
6.	Select **‘PackageReference in project file’** as package management format and click 'OK'.
7.	Open ‘Package Manager Console’ again.

**Expected Result:**
Project is still selected by default in ‘Default project’ drop box as below screenshot.
![1111222](https://cloud.githubusercontent.com/assets/20632775/22053663/34cb1a24-dd8d-11e6-9391-bf9d20d5ca42.png)

**Actual Result:**
Project is not selected by default in ‘Default project’ drop box as below screenshot.
![456789](https://cloud.githubusercontent.com/assets/20632775/22053664/36476bbe-dd8d-11e6-811c-7e4c99c36df9.png)

**Notes:**
The issue repro on D15Rel 26117.00 (NuGet release-4.0.0-RC3-2215).
The issue repro on other .NET Framework projects.

**Comment by jainaashish** [comment]
Correction, "Default project" drop box is not empty rather by default, project is not selected in that drop box.

**Comment by v-luzh** [comment]
Fixed on **_VSUMain 26313.00+NuGet Client 4.3.0-Beta1-2381_** and **_D15Rel 26228.00+NuGet Client 4.1.0-RTM-2382_**.
