### ISSUE TITLE
Unity 3D Support through Target Fallback 

### ISSUE THREAD

**Issue by tylerohlsen** [NuGet/Home#4319]
## Details about Problem

NuGet product used: Client tools within Visual Studio (UI and Powershell)
NuGet version: 3.4.4.1321
VS version: VS 2013, VS 2015, VS 2017
OS version: Microsoft Windows [Version 10.0.10586]
Worked before? No

## Detailed repro steps so we can see the same problem

1. Create new project in Visual Studio for target framework "Unity 3.5 .net Subset Base Class Libraries" or "Unity 3.5 .net full Base Class Libraries"
2. Use NuGet UI to browse NuGet packages online
3. Attempt to install a package that contains a .Net 3.5 assembly
Expected: Install package and eat cake
Actual: Package fails to install because it does not find a compatible target framework and the cake is a lie

## Other suggested things

Unity 3d uses a closed fork of an unknown version of the Mono framework.  We do know that it is mostly compatible with .Net 3.5.  See more [here](https://docs.unity3d.com/401/Documentation/ScriptReference/MonoCompatibility.html).  Most libraries that I attempt to use that do have a net35 target do function without fail.  Because this is a bit of a niche market, the support for libraries that target the exact Unity 3d target framework is practically zero (target identifiers: `net35-unity subset v3.5` and `net35-unity full v3.5`).  Which renders NuGet useless for us.

I propose the following change.  Set up a target framework fallback in the below order.  This would allow Unity developers to at least install packages that include a net35 or below target.  Yes, they may have compatibility issues with the libraries they install.  But what's worse: not being able to use NuGet in any practical sense or allow it to be used and a few compatibility issues that users may be able to work out.  My vote is for the latter.

Fallback Order
- net35-unity full v3.5
- net35-unity subset v3.5
- net35
etc

**Comment by cesarsouza** [comment]
Any updates about this issue? It would come really in hand for Unity developers right now.

**Comment by tylerohlsen** [comment]
As a workaround, I have moved our team's projects to target .Net 3.5 Full instead of a Unity specific profile.  But we run the risk of runtime errors due to no longer catching unsupported framework apis.  That's the tradeoff.  

To mitigate that issue, I may create a Roslyn analyzer to find those unsupported framework apis at compile time.  Which basically reproduces the Unity framework profile.  But I haven't found the time to do that yet.

**Comment by tylerohlsen** [comment]
Also see issue #5460

**Comment by zhili1208** [comment]
dupe this as #5460
