### ISSUE TITLE
[Perf] Slow installation of vnext package into a v4.5 app

### ISSUE THREAD

**Issue by suhasj** [NuGet/Home#432]
This is following up on the discussion of perf issue when installing a nuget package for a K class library on a v4.5.1 MVC project. The installation is really slow more so if the machine has lesser memory.

Below are the steps you can use to repro

1. Setup feed to point to myget feed for vnext `https://www.myget.org/f/aspnetvnext/api/v2`
2. Create a new MVC 5 project targeting v4.5.1
3. Now from in the web app, right click and choose ‘Manage Nuget packages’
4. Select the above feed and search for `Microsoft.AspNet.DataProtection.Extensions` and install it.

**Comment by maartenba** [comment]
Hi @suhasj,

Which VS version are you using? Which feeds are registered in your setup?

It would be helpful if you have some timings on how long it takes to get the search up.
Is it always slow or just this one occurence?

**Comment by suhasj** [comment]
I am using the latest internal version of VS 2015 with the vnext feed setup which is https://www.myget.org/f/aspnetvnext/api/v2. This was a consistence repro and I have been in touch with @deepakaravindr for this.

**Comment by maartenba** [comment]
Any additional info would be great to have. Would you happen to be able to capture a Fiddler trace (https decrypted)?

**Comment by maartenba** [comment]
We have deployed a number of performance improvements to MyGet. @suhasj can you try and give us some feedback if this is actually better from your end?

**Comment by suhasj** [comment]
sure. Let me give it a try and get back
