### ISSUE TITLE
Hide 'Pack' option for Unit Test Project (.Net Core)” / "ASP.Net Core Web Application (.Net Core) project"

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4323]
_From @jinujoseph on January 17, 2017 0:0_

_Copied from original issue: dotnet/roslyn-project-system#1204_

**Comment by srivatsn** [comment]
_From @mavasani on January 17, 2017 17:34_

Is the suggestion here even to hide the Package property page? Both the command and the page are currently based on "Pack" capability which is pulled in by NuGet Pack target.

Tagging @srivatsn

**Comment by srivatsn** [comment]
Ya we should have the pack capability only for class libraries then.

**Comment by srivatsn** [comment]
The pack capability comes from the Pack package so moving here.

**Comment by rohit21agrawal** [comment]
what would be the right condition to add this capability?

**Comment by srivatsn** [comment]
I assume just OutputType==Library? Do we pack any other projects? Does pack check for any other condition?

**Comment by rohit21agrawal** [comment]
Netcoreapp1.0 projects are packed but I think their output type is exe, right?

**Comment by srivatsn** [comment]
Yes.

**Comment by rrelyea** [comment]
Unit test project seems to have output type as equal to library.
perhaps unit test project should set IsPackable=false.
we'll change our logic to add capability if isPackable is true and outputtype is library
/cc @srivatsn

**Comment by srivatsn** [comment]
@codito @singhsarab for the change to the unit test projects. They infer the outputtype and I believe it's Exe for core projects and Library for desktop projects. Either way IsPackable=false makes sense.

**Comment by codito** [comment]
@srivatsn is right. Is this planned for rtm?

**Comment by rohit21agrawal** [comment]
No this has been moved to the next milestone.
Tagging @rrelyea for confirmation
