### ISSUE TITLE
add package command should add version as attribute instead of element

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4325]
Created from : https://github.com/dotnet/cli/issues/5386

Current : 

```
  <ItemGroup>
    <PackageReference Include="System.ValueTuple">
      <Version>4.3.0</Version>
    </PackageReference>
  </ItemGroup>
```

Expected: 

```
  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.3.0" />
  </ItemGroup>
```
@rrelyea

**Comment by DustinCampbell** [comment]
Adding myself over here so I can track.

**Comment by rrelyea** [comment]
Per email, failed barcheck for RTM in vs client Shiproom. moving to post rtm.

**Comment by nkolev92** [comment]
@mishra14 
https://github.com/NuGet/Home/issues/4440
Is the above issue a dup of this one?

**Comment by rrelyea** [comment]
Please finish PR review/feedback (if any).
Then ensure you've tested it all it needs.
Then merge into dev.
