### ISSUE TITLE
NuGet restore doesn't throw error when Allow NuGet to download pacakges disabled

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4327]
Steps:
1. Disable Allow NuGet to download missing packages option from tools-> options -> NuGet Package Manager
2. create a class library
3. install newtonsoft.json and select PackageReference as package management format
4. manually delete this newtonsoft.json package from the global packages folder
5. now, do restore. It will show restore succeed and all packages are installed. But this package is not present. Besides, it shows a warning in Error List window, and ask to run restore. But restore doesn't do anything when you disabled that option.

Expected:
Ideally NuGet restore would have thrown a error similar to it does for Package.Config case like below. Same issue is there for .net core projects as well (for anything which depends on PackageReference).

`One or more NuGet packages need to be restored but couldn't be because consent has not been granted. To give consent, open the Visual Studio Options dialog, click on the Package Manager node and check 'Allow NuGet to download missing packages during build.' You can also give consent by setting the environment variable 'EnableNuGetPackageRestore' to 'true'.`

**Comment by nkolev92** [comment]
Dup in https://github.com/NuGet/Home/issues/6016.
