### ISSUE TITLE
Get two errors when you have invalid references

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4328]
_From @davkean on January 13, 2017 8:23_

```
Error		Project ConsoleApp49 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Project ConsoleApp49 supports: netcoreapp1.1 (.NETCoreApp,Version=v1.1)			0	
Error		One or more projects are incompatible with .NETCoreApp,Version=v1.0.
```

Why do you get two errors when you have invalid references?

_Copied from original issue: dotnet/sdk#640_

**Comment by srivatsn** [comment]
_From @davkean on January 13, 2017 8:28_

Oh, maybe this is NuGet outputting this?

**Comment by srivatsn** [comment]
_From @davidfowl on January 13, 2017 9:0_

Yes that's a nuget error.

**Comment by emgarten** [comment]
Solving this would require a central component to de-dupe these messages along with writing errors to the assets file along with common numbered error codes.

From the NuGet side we have no idea what warnings/errors the project system duplicate and which still need to be shown.

Also, the same errors are displayed for nuget.exe as restore in Visual Studio.

**Comment by emgarten** [comment]
This is expected. The second error message is a summary of project compatibility.

**Comment by davkean** [comment]
Can you point me other examples where you get a summary of "errors"? It's unneeded, and adds no value over the first error.

**Comment by emgarten** [comment]
It would be similar to the build summary
``========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========``

NuGet is set up to log in the same way for both nuget.exe, dotnet.exe, and Visual Studio. It then writes all warnings/errors to the visual studio error list without filtering out some of these extra summaries. That should be improved as part of this.

**Comment by davkean** [comment]
The build summary isn't shown as an error in the Error List, output window or command-line.

**Comment by zhili1208** [comment]
this is already fixed
