### ISSUE TITLE
Support msbuild /t:restore;build gesture

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4329]
_From @onovotny on December 21, 2016 2:12_

Splitting from https://github.com/dotnet/sdk/issues/531

Today you have to explicitly do two commands for a proper build:
- `msbuild /t:restore`
- `msbuild /t:build`

It would be easier and more intuitive if the SDK could combine those to enable:
`msbuild /t:restore;build`, `msbuild /t:restore;pack` or even simply implicitly call restore (unless opted out with a variable?). 

It's true that the build may have to re-evaluate itself after the restore since additional props/targets may be imported, but somehow this should be made to work.

_Copied from original issue: dotnet/sdk#541_

**Comment by srivatsn** [comment]
_From @davidfowl on December 21, 2016 3:19_

We've been discussing what it would take to treat restore like a build dependency so that it's fully incremental and does everything at the required times. That would eliminate the need for running more than a single command.

**Comment by emgarten** [comment]
This requires a change to MSBuild as @davidfowl mentioned.

An example of the issue today:
1. MSBuild evaluates all imports and properties
1. Restore downloads packages and adds .targets and .props files from the packages
1. MSBuild does not load these new targets/props
1. Build runs without package targets/props

It is unclear what work NuGet would actually need to do here, if any.

**Comment by zhili1208** [comment]
"msbuild /restore" work for this scenario

**Comment by clairernovotny** [comment]
Huh? This is not closed... the goal was that `msbuild /t:restore` was not an explicit step. It needs to be chainable with build, so `msbuild /t:restore;build` works at the same time. More importantly, Build should have Restore as a dependency.

**Comment by emgarten** [comment]
@onovotny I think you may have better luck filing this on msbuild with that explanation.

**Comment by clairernovotny** [comment]
I didn't file it here :) Can one of you move this to the right repo then using that tool you have?
