### ISSUE TITLE
FrameworkReducer cannot determine nearest framework for dnxcore50 even there is ".NETPortable,Version=v0.0,Profile=Profile259" available

### ISSUE THREAD

**Issue by ChengTian** [NuGet/Home#433]
`NuGetFrameworkUtility.GetNearest()` returns `null` when I try to get nearest framework for `dnxcore50` in the following package:

![capture](https://cloud.githubusercontent.com/assets/1383883/7150935/7db434c6-e2d7-11e4-8e95-399cec9642e8.PNG)

The expected return result should be `portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1` (i.e. `.NETPortable,Version=v0.0,Profile=Profile259`) in this case

@emgarten @davidfowl @anurse

**Comment by emgarten** [comment]
@ChengTian 

I'll update NuGet.Frameworks. dnxcore50 is compatible with portable-net45+win8, correct?

**Comment by anurse** [comment]
Yes, I believe that is correct.

**Comment by emgarten** [comment]
closing this based on our discussion yesterday, DNX can handle this behavior.
