### ISSUE TITLE
"nuget add" hangs in Ubuntu with a local feed

### ISSUE THREAD

**Issue by lolwhatitis** [NuGet/Home#4333]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet binary in Ubuntu

NuGet version (x.x.x.xxx): 3.5.0.1996

dotnet.exe --version (if appropriate): 1.0.0-preview2-1-003155

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Ubuntu 16.04 LTS

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

On a Ubuntu machine:

1. Create a directory to store a NuGet local feed.

2. Create a NuGet package.

3. `nuget sources Add` the NuGet local feed directory.

4. Attempt to `nuget add` the package to the local feed.

`nuget add` creates a directory in the local feed. Then, it places a single file into the directory; the file appears to be the same size as the `.nupkg` you're attempting to add. However, `nuget add` appears to do nothing else; in fact, it hangs in such a way that `Ctrl+C` won't interrupt the process.

### Verbose Logs

$ sudo nuget add foo.nupkg -source /Projects/nuget-feed -verbosity detailed
NuGet Version: 3.5.0.1996
Acquiring lock for the installation of foo 1.2.1001
Acquired lock for the installation of foo 1.2.1001
Installing foo 1.2.1001.
--- END OF LOG ---

**Comment by zhili1208** [comment]
Please try latest nuget.exe from https://www.nuget.org/downloads, if it still repro, feel free to reopen it.
