### ISSUE TITLE
deliver localized nuget components for CLI

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4336]
As cli handles localization for rtm, we should deliver localized nupkgs to them. The exact method is still being discussed. I will update as we reach conclusions.

**Comment by rrelyea** [comment]
Not on track for RTM, sent mail. Moving to 4.0.1 to reflect taht.

**Comment by mishra14** [comment]
Related design task: https://github.com/NuGet/Home/issues/5561

**Comment by mishra14** [comment]
`NuGet.Localization` package generation is done. based on feedback from the cli team, we need to ilmerge pack resources as well. 

@rohit21agrawal is going to take over the task to get that done.
