### ISSUE TITLE
After updating to new Microsoft.NETCore.App 1.1.0  from 1.0.3 , some bugs are thrown during compile

### ISSUE THREAD

**Issue by arun-chief** [NuGet/Home#4338]
![devenv_2017-01-20_10-46-20](https://cloud.githubusercontent.com/assets/16814342/22137060/c5695efc-defe-11e6-99ff-023d94b931a7.png)

Otherwise the project works fine. Only this update seems to making the problem.

I am using visual studio 2015 community edition.

**Comment by zhili1208** [comment]
Please update to VS 2017
