### ISSUE TITLE
dotnet pack - allow "empty" packages to create convenience packages

### ISSUE THREAD

**Issue by blackdwarf** [NuGet/Home#4339]
Moved from dotnet/cli#4331

**Comment by rohit21agrawal** [comment]
@danielwertheim @blackdwarf 

you can already do this using dotnet.exe pack - you can use a command like the following : 

```dotnet.exe pack /p:IncludeBuildOutput=false```

**Comment by blackdwarf** [comment]
@rohit21agrawal splendid, that means it is fixed! :)
