### ISSUE TITLE
Saved a nuspec file with wrong reference whitelist when PackageSaveMode = nuspec 

### ISSUE THREAD

**Issue by micongjie** [NuGet/Home#434]
I'm using reference whitelist in nuspec to filter out contracts assembly. The filter stops working when the NuGet.config file has PackageSaveMode = nuspec.

Repro steps:
1. Create a package with 2 assemblies in lib folder and specify reference whitelist in nuspec to filter out one assembly.
2. Create a solution file and a class library project in VS and close the solution
3. Copy the default NuGet.config along side with the solution file and set PackageSaveMode = nuspec
4. Reopen the solution in VS and add that package to the project through NuGet Manager
5. Both assemblies get added to the project. The whitelist does not work...

**Comment by emgarten** [comment]
@micongjie are you still seeing issues with this using the latest 3.5.0 version of NuGet?

**Comment by jainaashish** [comment]
No new update for a long time. I'm closing it for now, please re-open or log a new issue if you can still repro it with latest NuGet 4.5.0 build.
