### ISSUE TITLE
Get a tonne of unintelligible errors when a project is missing from disk

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4340]
Current NuGet outputs a ton of errors when a project is missing from disk:

![image](https://cloud.githubusercontent.com/assets/1103906/22138279/e93378c4-df33-11e6-934c-ed40d090adf3.png)

I would prefer that it not output any errors in this case and let the project system handle the warnings.

**Comment by davkean** [comment]
Notice that the warnings are from the project system, they are short, sweet, correctly populate project information and play nicely with design-time builds.

**Comment by natidea** [comment]
This is fixed. NuGet now reports one error for each reference to that project:

> Error	NU1104	Unable to find project 'ClassLibrary1.csproj'. Check that the project reference is valid and that the project file exists.	

The existing warning from `Microsoft.Common.CurrentVersion.targets` is still present, so user is alerted twice

**Comment by davkean** [comment]
It sounds like there's still two errors - which is not ideal. We should have just MSBuild report the missing reference, not NuGet.
