### ISSUE TITLE
dotnet restore | build | publish do not respect nuget.config repository path

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4341]
Moved from dotnet/cli#2714 on behalf of @schaabs

the --packages parameter on restore gets us close to the described behavior, but a quick test of dotnet restore with rc4 bits showed that the NuGet.config configuration is not being honored.

----

## Steps to reproduce

use cli to restore | build | publish a project which has a nuget.config with a specific repository path.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
  </packageRestore>
...
  <config>
    <add key="repositoryPath" value=".\utpackage" />
  </config>
...
</configuration>
```

however if you create the following global.json in the same directory it functions as expected:

```
{
  "packages": "utpackage"
}
```
## Expected  behavior

dotnet cli should respect both global.json packages property and nuget.config repositoryPath
## Actual behavior

if only the nuget.config is present packages are restored to and referenced from the global packages cache
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-rc2-002468)

Product Information:
 Version:     1.0.0-rc2-002468
 Commit Sha:  a2f3c531fb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14318
 OS Platform: Windows
 RID:         win10-x64

**Comment by emgarten** [comment]
@schaabs use ``globalPackagesFolder`` instead of ``repositoryPath``.  ``repositoryPath`` is only for packages.config projects which produce a different output structure. The different project types cannot share the same folder.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Utility/SettingsUtility.cs#L16

**Comment by rrelyea** [comment]
@karann-msft - can we please make the docs clear to distinguish Justin's clarification above?

**Comment by kraigb** [comment]
@piotrpMSFT Done, see https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file.
