### ISSUE TITLE
Package Installation Status API

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4343]
This is needed to fix https://github.com/dotnet/cli/issues/5325 which was opened by @rrelyea 

dotnet CLI brings along a cached version of Microsoft.NetCore.App and several other metapackages. During first-run, CLI unpacks these packages and attempts to install them. As @rrelyea pointed out in the aforementioned issue, the UX on first run would be greatly improved if CLI could bypass this step altogether when the needed packages are already present. To do this, however, we need an API that will tell us that a given package identity, along with transitive dependencies, is already present in the current user context. `bool IsInstalled("Microsoft.NetCore.App", "1.1.0")` would be the pseudocode signature, I suspect...

We considered inspecting the packages folder directly, but per past conversations we decided not to pursue taking dependencies on the layout of nuget's packages store.

**Comment by rrelyea** [comment]
Consider post RTM.

**Comment by nkolev92** [comment]
I think the scenario mentioned in this issue is no longer relevant as fallback folders are not a thing anymore. 
Closing this as low priority.
