### ISSUE TITLE
[Test Failure] The package 'Microsoft.NETCore.UniversialWindowsPlatform' latest version shows inconsistently between PMC and PM UI 

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4345]
**NuGet Version:** NuGet 4.0.0-RC3-2228
**VS Version:** D15Rel 26118.01
**OS Version:** Windows 10 RS1_Release 14393.726.170112-1758

**Repro Steps:**
1.	New a Visual C#->Blank App (Universal Windows) project.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Go to installed tab to verify an installed latest package exists and install package 'Newtonsoft.json'.
4.	Open ‘Package Manager Console’ and type in **‘Get-Package -Updates’**.
5.	Check if the packages latest version show consistently between PMC and PM UI .
6.	Then select the 'include prerelease' in PM UI and type in **‘Get-Package -Prerelease -Updates’** in PMC.
7.	Check if the packages latest version show consistently between PMC and PM UI .

**Actual Result:**
The package **'Microsoft.NETCore.UniversialWindowsPlatform'** latest version shows inconsistently between PMC and PM UI in step 5 and step 7 as below screenshot.
![2](https://cloud.githubusercontent.com/assets/20632775/22181115/9148a494-e0bf-11e6-9398-d144d717bbd8.png)
![22](https://cloud.githubusercontent.com/assets/20632775/22181116/936bbea0-e0bf-11e6-89eb-ca830780f8bd.png)

**Comment by rrelyea** [comment]
@v-nancyj  - please always compare with previous versions... in this case how does 3.5 work on top of vs2015?

**Comment by rrelyea** [comment]
not repro anymore - but 5.3.0 was published 1/27.
I suspect this may be because the package was pushed, but unlisted? Perhaps PMC shows those...and PM UI doesn't. Ideally they should be consistent.

**Comment by v-nancyj** [comment]
@rrelyea The version 5.3.0 have been listed, please close the bug, Thanks!
