### ISSUE TITLE
OrleansHost.exe.config is not copied to output directory from package

### ISSUE THREAD

**Issue by attilah** [NuGet/Home#4347]
## Details about Problem

In [Orleans](https://github.com/dotnet/orleans) we're packaging OrleansHost.exe and OrleansHost.exe.config in a nuget package to provide an out of box experience to run a Silo host.

It turned out that something is wrong, since the config file is not getting deployed during project build. I can't remember if it worked before or not, but not it is not working.

I tried to played with ```contentFiles``` but it fails without any error message and did not find docs about what project types can use this 3.3+ feature?

the old ```content``` feature is just half baked, since I can't set the ```copyToBuild``` property to true.

Here is the nuspec file in question: [Microsoft.Orleans.OrleansHost.nuspec](https://github.com/dotnet/orleans/blob/master/src/NuGet/Microsoft.Orleans.OrleansHost.nuspec)

Can you point me to the right direction? What is the best and proper way to do this today? (and in the future?)

**Comment by emgarten** [comment]
@attilah take a look at https://github.com/NuGet/Home/wiki/%5BSpec%5D-Content-v2-for-project.json

You will need to add a ``contentFiles`` section to your nuspec to specify the copy to build output property in addition to copying the files under the ``contentFiles/`` folder. You need both and ``<files>`` is unrelated to ``contentFiles`` (a common source of confusion).

**Comment by attilah** [comment]
Thanks, I'll give it a try and coming back with the results.

**Comment by attilah** [comment]
Based on the discussion we have it turns out that it will not work for "old style" csprojs, so closing this issue now and going forward with either a targets or a ps1 file in the package (or just doing this for vNext and not for Orleans 1.x)
