### ISSUE TITLE
CreateWarehouseReports fails (Rate of failure exceeded Error threshold)

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#435]
From PagerDuty:

    {"component":"Nuget Work Service","ErrorMessage":"Rate of failure exceeded Error threshold for CreateWarehouseReports. Threshold count : 30%, failure in last 24 hour : 4"}

**Comment by RanjiniM** [comment]
This worker job has been converted to an exe and move to jobs VM. The job is successfully running now without any errors.
