### ISSUE TITLE
Error executing task CreateTrafficManagerStatusOverviewReportTask

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#436]
From PagerDuty:

    Error executing task NuGetGallery.Operations.CreateTrafficManagerStatusOverviewReportTask

    {"component":"Dashboard Ops","ErrorMessage":"Exception thrown while executing task NuGetGallery.Operations.CreateTrafficManagerStatusOverviewReportTask. Exception Message : The remote server returned an error: (500) Internal Server Error., Stack Trace : at System.Net.HttpWebRequest.GetResponse()\r\n at NuGetGallery.Operations.CreateTrafficManagerStatusOverviewReportTask.ExecuteCommand() in c:\\Users\\lzhi\\Documents\\GitHub\\NuGet.Services.Dashboard\\NuGet.Services.Dashboard.Operations\\Tasks\\DashBoardTasks\\AzureManagementTasks\\CreateTrafficManagerStatusOverviewReportTask.cs:line 32\r\n at NuGetGallery.Operations.OpsTask.Execute() in c:\\Users\\lzhi\\Documents\\GitHub\\NuGet.Services.Dashboard\\NuGet.Services.Dashboard.Operations\\Tasks\\OpsTask.cs:line 87"}

**Comment by RanjiniM** [comment]
@bhuvak is looking into this one.

**Comment by bhuvak** [comment]
Seems to be one off 500 error from Azure management APIs. Closing this one as there is nothing much to do from our side.
