### ISSUE TITLE
`dotnet restore` with update in the new csproj/msbuild-based core projects?

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4361]
Moving from https://github.com/dotnet/cli/issues/5425 on behalf of @brgrz.

This is also related to #4358 

----

How do I actually update the new csproj-based project's Nuget packages to the latest ones when using Visual Studio Code?

This is what I have within the .csproj file:

```
<PackageReference Include="Microsoft.AspNetCore" Version="1.0.3" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.2" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.1" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.1" />
<PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.0.0" />
```

If I do `dotnet restore` it will only install the specified package versions.

There is no `dotnet restore update` or `dotnet nuget update` option available.

All of the above referenced Microsoft.AspNetCore.* packages have newer versions (1.1.0).

I would like to update the packages and have the references updated automatically in the same way we do this in Visual Studio.

**Comment by emgarten** [comment]
@brgrz is this a question on Visual Studio Code? And is this the same as #4358?

**Comment by brgrz** [comment]
Yes, that's the issue I'm having. Pure VS Code environment.

**Comment by rrelyea** [comment]
There is no auto discovery of all updates that are available, yet.
https://github.com/NuGet/Home/issues/4358 covers having that added in future.

@mishra14 - can you please reply with the new syntax for "dotnet add package" if you know the version you want to upgrade to.

**Comment by mishra14** [comment]
@brgrz : try using 
* `dotnet add package Microsoft.AspNetCore` -> This will update the package to its latest stable version
* `dotnet add package Microsoft.AspNetCore --version <version>` -> This will update the package to the version that you specify

**Comment by brgrz** [comment]
thanks @mishra14 this is nice for in the meantime while we wait for https://github.com/NuGet/Home/issues/4358

**Comment by emgarten** [comment]
> this is nice for in the meantime while we wait for #4358

@brgrz any reason you need nuget.exe to do this also?

**Comment by brgrz** [comment]
@emgarten well this solution is not perfect and does not cover updating automatically to unknown new version and requires lots of typing

**Comment by rrelyea** [comment]
Ensure that #4358 covers this scenario.

**Comment by rrelyea** [comment]
#4358 is in 4.0.1 right now. REsolving this as a dupe.
