### ISSUE TITLE
NuGet VS17 sporadically fails connecting to VSO/VSTS feeds - VS Bug 365798

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#4365]
Dup of VS: Bug 365798
VS 2017 sporadically has trouble connecting to VSO feeds.
VS version: VS 15.0.0-RC3+26117.0.d15rel at least and later

The issue is sometimes resolved by random restart/clean cache.

Playing around with the entering/not entering credentials when prompted I managed to get it

**Comment by nkolev92** [comment]
Steps to a possible repro:
1. Launch VS
2. Auth VS user
3. Create project
4. Add dependency from a VSO feed
5. Log out from VS
6. Close VS
7. clear the cache ex. "NuGet.exe locals all -clear"
8. Launch VS and open project (not Auth'ed)
9. Do "Restore NuGet Packages" before doing a "Manage Nuget Packages"
10. Open "Manage NuGet Packages" and you should not get prompted to auth. 

And we're in the above mentioned scenario.

Everything seems fine, if the user does "Manage NuGet Packages" before doing a restore though. 
So that might be a workaround for now. 

*The problem with this repro is that it's not a normal user scenario to log in/log out of VS frequently. While this is an issue it's likely to be the root cause of the reports*

**Comment by nkolev92** [comment]
And here's a workaround that worked for me in a couple of test cases.

1. Log out from VS.
2. Close VS.
3. Launch VS and Auth.
4. Close VS.
5. Do a "NuGet.exe locals all -clear"
6. Launch VS
7. Open your solution
8. Do a "Manage NuGet Packages" 

*Note: If you have a Net.Core project make sure to turn off Auto Restore before Step 4*

That should fix it.

**Comment by nkolev92** [comment]
The issue is reproducible on VS.25019, prior to RC1.
Not an RC3 regression.

**Comment by rrelyea** [comment]
How is fix progressing? Should we balance due to your v3 vsix work today?
