### ISSUE TITLE
[Feedback] Crashes when changing .NETStandard target

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4368]
See internal bug 369383
1. Open a solution.
2. Open the Properties page of a portabl class library.
3. Change .NETStandard target from .NETStandart1.6 to .NETStandard1.7
4. VS crashes.

**Comment by rrelyea** [comment]
not positive i have the exact repro steps, as I created a PCL project in vs2017, and then upgraded it.
But that didn't crash.
We should create a VS2015 project, and then attempt to repro again.

**Comment by MattGertz** [comment]
Check if this is tracked in project already, and if not, please create an issue over there.

**Comment by davkean** [comment]
This repro says "Portable Class Library" not .NET Standard library.
