### ISSUE TITLE
Error: SQL Azure database alert activated for DBSuspendedRequests

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#437]
From PagerDuty:

    Error: SQL Azure database alert activated for DBSuspendedRequests

    {"component":"SQL Azure database","ErrorMessage":"Number of DBSuspendedRequests exceeded the Error threshold value. Threshold value 30, Current value : 36.all requests wait_type areRESOURCE_SEMAPHORE\n\n\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\n\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\n\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\nRESOURCE_SEMAPHORE\n\nRESOURCE_SEMAPHORE\n"}

**Comment by bhuvak** [comment]
fixed as part of https://github.com/NuGet/NuGetGallery/issues/2446
