### ISSUE TITLE
[Watson] apphangb1: APPLICATION_HANG_BusyHang_cfffffff_NuGet.PackageManagement.VisualStudio.dll!Unknown

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4372]
internal bug: 366614

**Comment by emgarten** [comment]
@rrelyea should ClosedAsDuplicate be removed here? Or where is the issue tracking this?

**Comment by emgarten** [comment]
46 hits on this overall. I don't see any hits in RC.3 however.
