### ISSUE TITLE
Restore output in minimal verbosity is confusing and not informative enough

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#4375]
## Details about Problem

In minimal verbosity output is just this:

Restoring NuGet packages...
Time Elapsed: 00:00:02.5866682
========== Finished ==========

- what project was restored?
- was restore successful or did it fail?

If we don't print even a restore result - output is just useless.

**Comment by nkolev92** [comment]
This has been fixed since. 
Restore logs 1 message per package from packages.config restored and nothing to do if not found and 1 message per project restored in PackageReference.
