### ISSUE TITLE
Confusing restore output: it did some restore on one of the projects, but at the end it still prints "All packages are already installed and there is nothing to restore"

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#4376]
## Details about Problem

open this https://github.com/srivatsn/roslyn-project-system/tree/dogfood (switch to dogfood branch), wait for first restore to complete. Then remove manually assets file for Composition.csproj. Run restore for solution again and check output (in Diagnostic verbosity  mode). It did restore new packages for Composition.csproj , but at the end printed: "All packages are already installed and there is nothing to restore." - i first had an impression that it did not notice that assets file is removed and skipped restore - confusing!

VS version (if appropriate):

RC3 build: d15rel 26116.1.

OS version (i.e. win10 v1607 (14393.321)):

win10

## Detailed repro steps so we can see the same problem
1. open this https://github.com/srivatsn/roslyn-project-system/tree/dogfood (switch to dogfood branch), 
2. wait for first restore to complete. Then remove manually assets file for Composition.csproj. 
3. Run restore for solution again and check output (in Diagnostic verbosity  mode). It did restore new packages for Composition.csproj , but at the end printed: "All packages are already installed and there is nothing to restore." 

### Sample Project
https://github.com/srivatsn/roslyn-project-system/tree/dogfood (switch to dogfood branch)

**Comment by nkolev92** [comment]
If not fixed yet, likely a tandem with https://github.com/NuGet/Home/issues/9402.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9915

**Comment by nkolev92** [comment]
Expanding the scope of this issue...the status bar should be accounted for as well.

**Comment by nkolev92** [comment]
assigning to @JonDouglas as the other issue was already assigned to him.

**Comment by nkolev92** [comment]
A few things here: 

1. Ensure that restore is not spamming the status bar. 
This can be annoying. 
1. Ensure the messages make sense when PC and PR are mixed.

**Comment by nkolev92** [comment]
Specifically see: https://github.com/NuGet/Home/issues/9915#issue-679473943

**Comment by nkolev92** [comment]
@JonDouglas Hoping I can get some support for this during customer sprint :)
