### ISSUE TITLE
nuget.exe pack -Version only overrides version element in .nuspec

### ISSUE THREAD

**Issue by veleek** [NuGet/Home#438]
I'm producing two NuGet packages from the same project. One is a base framework, and the second is some extensions to the framework. They are not both required but the extensions version always requires the same version of the base framework. 

e.g. If I'm using FrameworkExtensions 1.2, I must be using FrameworkBase 1.2.

To accomplish this, I have the following in the NuSpec for (extra stuff snipped):

```xml
<metadata>
  <id>FrameworkExtensions</id>
  <version>$version$</version>
  <dependencies>
    <dependency id="FrameworkBase" version="[$version$]" />
  </dependencies>
</metadata>
```

If override the version as part of the NuGet.exe command line
`NuGet pack -Version 2.0 ...`

The resulting NuGet package for FrameworkExtensions has a version of 2.0, but it depends on version 1.2 of of the FrameworkBase package.

Based on experimentation, the value of the `$version$` property in the dependency elment is set to the version of the FrameworkExtensions assembly (so if I don't override the version they are both equal to 1.2 in this example). When I override the version, only the version property is overridden, and not the value in the dependency element. This makes it difficult to require specific versions of the nuget packages. 

EXPECTED: When I provide a version override to nuget.exe it will replace all $version$ tokens in the NuSpec with this same version.

**Comment by veleek** [comment]
This bug is just being transferred from the Codeplex issue tracker: http://nuget.codeplex.com/workitem/3242

**Comment by emgarten** [comment]
We do not support for this currently. One way to handle this is to transform your nuspec, updating the version before calling pack.
