### ISSUE TITLE
Pack runs too often -- Generate NuGet package doesn't include all the configurations 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4380]
vsfeedback 744575

marked investigate, please do quick investigation to understand impact, etc..

To repro:
- Create a .NET Standard class library 
- edit the csproj file and change the property TargetFramework to TargetFrameworks and change the value to net461;netstandard1.4
- go to project properties -> Package and check the checkbox "Generate NuGet package" 

Expectation: the NuGet package will contain both net461 and netstandard1.4 assets
But it just contains netstandard1.4 assets

**Comment by rohit21agrawal** [comment]
the cause of this issue is the same as : https://github.com/NuGet/Home/issues/4381
