### ISSUE TITLE
Fallback RID are not used if packagereference has only native assets

### ISSUE THREAD

**Issue by ramarag** [NuGet/Home#4392]
## Details about Problem

NuGetVersion - 4.0.0-rc3-2193

## Detailed repro steps so we can see the same problem

 Do a nuget restore on [UnmanagedCache.csproj](https://github.com/dotnet/sdk/blob/6043430d97ec81ae05f1f66a3517c5fd530c75c1/TestAssets/TestProjects/UnmanagedCache/UnmanagedCache.csproj) with RID - win10-x64 no assets are restored

if nuget restore is done with RID win7-x64, the assets are restored correctly.

Interestingly if a manged nuget pakage reference is added to the project, The assets are resolved properly. For example Do a nuget restore on [SimpleCache.csproj](https://github.com/dotnet/sdk/blob/6043430d97ec81ae05f1f66a3517c5fd530c75c1/TestAssets/TestProjects/SimpleCache/SimpleCache.csproj) with RID - win10-x64, the correct assets for the fallback RID win7-x64 are restored

cc @gkhanna79 @srivatsn

**Comment by emgarten** [comment]
@ramarag restore discovers the hierarchy of RIDs from runtime.json files in the packages. If your project does not depend on a package containing the correct mappings then win10-x64 will have no relationship to win7-x64. Check that you have a package containing runtime.json with this mapping.

**Comment by ramarag** [comment]
@emgarten that might very well be the case, but by adding a manged package reference, it works
does that mean the fallback is identified from runtime.json of the manged package ?

**Comment by emgarten** [comment]
Can you explain managed package? If this package depends on netcoreapp or netstandard.library then it would bring in the package that contains the RID mappings in runtime.json.

**Comment by ramarag** [comment]
in the above example microsoft.netcore.coredistools's runtime.json has no entries for win10-x64.
which is the root cause of the issue.

If another project's runtime.json has a fallback for win10-x64, then it gets used to resolve the above packages's assets.
 so package authoring error is not clear and it appears that nuget is doing something different, it would be nice to issue a warning here

**Comment by emgarten** [comment]
> it would be nice to issue a warning here

This could be done during pack. However it is a difficult check to get right because some RIDs may not have fallbacks, or maybe use their own RID graph instead of the standard .NET one.

In general package authors have complete control over RIDs and how they fallback. From the NuGet side we see them only as opaque strings and if runtime.json provides relationships between them we can do fallback.

**Comment by ramarag** [comment]
I was hoping something on the lines that when we restore, if no assets were restored. Nuget would emit warning saying no assets were restored

**Comment by emgarten** [comment]
@ramarag set ``ValidateRuntimeIdentifierCompatibility`` to true in your project to get these additional checks on this. This check should be done during publish instead, at restore time the actual target project/RID isn't known so you may see a lot of extra noise.
