### ISSUE TITLE
vsfeedback - Pack warnings when targeting netcoreapp1.1

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4397]
vsfeedback 746030

1. Create netstandard class library
2. Change TargetFrameworks to "netstandard1.4;net451;netcoreapp1.1"
3. Pack

Expected: 
 Pack successfull no warnings

Actual:
  Content files warnings displayed:

1>------ Build started: Project: MyClassLibrary, Configuration: Debug Any CPU ------
1>MyClassLibrary -> C:\Users\pakrym\Documents\Visual Studio 2017\Projects\MyClassLibrary\MyClassLibrary\bin\Debug\netstandard1.4\MyClassLibrary.dll
1>MyClassLibrary -> C:\Users\pakrym\Documents\Visual Studio 2017\Projects\MyClassLibrary\MyClassLibrary\bin\Debug\net451\MyClassLibrary.dll
1>MyClassLibrary -> C:\Users\pakrym\Documents\Visual Studio 2017\Projects\MyClassLibrary\MyClassLibrary\bin\Debug\netcoreapp1.1\MyClassLibrary.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(89,5): warning : Issue found with package 'MyClassLibrary'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(89,5): warning : Issue: Assembly outside lib folder.

MORE WARNINGS _-- SEE VSFEEDBACK ISSUE

**Comment by rohit21agrawal** [comment]
Investigated this and found out that the reason this happens is because VS UI actually calls ```msbuild /p:GeneratePackageOnBuild=true``` under the hood when a user right clicks a project -> Pack.

as a result, Pack was being called after each inner build. However, this will be fixed by : 

https://github.com/NuGet/NuGet.Client/pull/1148
