### ISSUE TITLE
Improve PCL selection for UAP

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#440]
UAP is not compatible with all PCLs that support Win8. This should be improved and parity with v2 kept as much as possible.

**Comment by emgarten** [comment]
This has been improved with NuGet/NuGet.Packaging@207bf15b81e5ce66398aed40afd2ec26671dd0a9 

I am leaving this issue open until a decision has been made on how to best determine if older generations of PCLs will work on UAP.

**Comment by davidfowl** [comment]
Not going to lie, that logic is kinda crazy

**Comment by emgarten** [comment]
It is, but it only does this extra tie breaking when multiple PCLs have the same number of frameworks and are equally compatible with the project. Without this it would be random which one would get selected if the package were authored this way.
