### ISSUE TITLE
When producing a package with files or folders that contain words like 'bin' 'debug' or 'release' those files and folders are not unpacked properly when the package is installed

### ISSUE THREAD

**Issue by rjgotten** [NuGet/Home#4402]
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: 3.3.4
Known working version of Nuget: 2.8.6

When creating a nuget package which holds tooling based on NodeJS (e.g. Less compiler) with `nuget -pack` on a TeamCity build server, when this package is installed certain files are not properly unpacked into the package corresponding folder. This seems to be related to files or folders that are named, or contain in their name, words like 'bin', 'debug', 'release' or 'build'. Upon inspection of the concents of the nupkg file with 7-zip, those files *are* present.

The older Nuget 2.8.x series does not have this problem. The same nuspec packed with 2.8.6 with the same settings produces a nupkg that, when installed, properly unpacks all files.

**Comment by emgarten** [comment]
@rjgotten can you given an example of the file paths and the output?  Also it would help to see the input nuspec and output nupkg file lists for both the working 2.x version and the 3.x version.

**Comment by zhili1208** [comment]
close it as no response
