### ISSUE TITLE
NuGet falsely reports as package pushed on a redirect from incorrect source url

### ISSUE THREAD

**Issue by murali89** [NuGet/Home#4403]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

**NuGet.exe**

NuGet version (x.x.x.xxx): **3.5.0.1938**

dotnet.exe --version (if appropriate): 

VS version (if appropriate):

**OS version (i.e. win10 v1607 (14393.321)): win10 v1607 (10.0.14393, OS Build 14393.693)**

Worked before? If so, with which NuGet version:
**Didn't work before**

## Detailed repro steps so we can see the same problem

1. **.\NuGet.exe push -Source https://codesharing-su0.visualstudio.com/DefaultCollection/Test%20Project/_packaging?feedName=mmyfeed3 ..\pkgs\**\*.nupkg**

**The above source url is wrong endpoint and it redirects to auth when nuget client hits. This has been construed as a success and the CL log shows that packages are being pushed.**

### Command line output
_Pushing Newtonsoft.Json.9.0.1.nupkg to 'https://codesharing-su0.visualstudio.com/DefaultCollection/Test%20Project/_packaging?feedName=mmyfeed3'...
  PUT https://codesharing-su0.visualstudio.com/DefaultCollection/Test Project/_packaging?feedName=mmyfeed3/
  NonAuthoritativeInformation https://codesharing-su0.visualstudio.com/DefaultCollection/Test Project/_packaging?feedName=mmyfeed3/ 2584ms
**Your package was pushed.**_

**Fiddler Trace:** [NuGetFalseSuccess_FiddlerTrace.zip](https://github.com/NuGet/Home/files/731293/NuGetFalseSuccess_FiddlerTrace.zip)

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zhili1208** [comment]
Please try latest nuget.exe from https://www.nuget.org/downloads, if it still repro, feel free to reopen
