### ISSUE TITLE
Inconsistent handling of <VersionPrefix>, <VersionSuffix> between NuGet and Sdk

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4404]
This does not repro with available CLI builds. The mismatch across behaviors is forcing redesign of parts of the CLI's build to accommodate these contradictory implementations of Version calculation.

`<VersionPrefix>` and `<VersionSuffix>` are used by both NuGet and Sdk. NuGet uses these values to calculate the PackageVersion, while the Sdk uses the values to calculate the value of AssemblyInformationalVersionAttribute in AssemblyInfo.cs. The algorithms for these calculations are inconsistent. 

Given:
```
   <VersionPrefix>1.0.0-prefix</VersionPrefix>
   <VersionSuffix>suffix-1234</VersionSuffix>
```

NuGet will calculate the PackageVersion as:
```
   1.0.0-suffix-1234
```

While the SDK will calculate the AssemblyInformationalVersionAttribute as:
```
   1.0.0-prefix-suffix-1234
```

These values should be consistent. I'm opening the issue in NuGet/Home as the SDK behavior better matches my expectation of what the property names VersionPrefix and VersionSuffix intend.

# Customer Impact
The inconsistent handling of VersionPrefix and VersionSuffix make it easy to generate NuGet packages whose contents' identities cannot be tracked back to a package identity, rendering the generation of common identity from a csproj file a broken experience.

# Repro
With CLI RC3, create a new project with this csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <VersionPrefix>1.0.0-prefix</VersionPrefix>
    <VersionSuffix>suffix-1234</VersionSuffix>
  </PropertyGroup>

</Project>
```

Run:
1. dotnet restore
2. dotnet pack

Inspect:
1. Name of the nupkg
2. obj/Debug/netcoreapp1.0/*.assemblyinfo.cs

# Expected
The computed identities are identical

# Actual
The computed identities are different

/cc @jonsequitur @blackdwarf @livarcocc @srivatsn @rrelyea @rohit21agrawal

**Comment by rohit21agrawal** [comment]
already fixed by https://github.com/NuGet/NuGet.Client/pull/1139
