### ISSUE TITLE
obj/projectname.nuspec misleading when VersionPrefix and VersionSuffix present

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4405]
This is related strongly to #4404. Opening a separate issue as the customer impact is different.

This repros with RC3 CLI

When `<VersionPrefix>` and `<VersionSuffix>` are specified in a csproj file and /t:Pack is executed then the Pack task generates a nuspec file in the obj directory. The file's name and contents match my expectations: they both treat the package version as `$(VersionPrefix)-$(VersionSuffix)`. This leads me to believe that the generated NuGet package also contains this combined Version [and matches the contents of my AssemblyInfo.cs #4404]. 

Despite the generated nuspec in obj, the nuget package under `bin` bares a different version number. Furthermore, its nuspec does not match the nuspec in `obj`, also sporting the alternative version number. 

# Customer Impact
The inconsistency within the behavior of the `Pack` target is misleading. Artifacts generated within the users context should be self-consistent and indicative of the resultant contents of the `bin` directory. The presence of a nuspec file in the `obj` directory also suggests that it should be modifiable by other targets, but the obvious disregard of this file during the pack operation shows us that its purpose is actually undefined.

# Repro 
With CLI RC3, create a new project with this csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <VersionPrefix>1.0.0-prefix</VersionPrefix>
    <VersionSuffix>suffix-1234</VersionSuffix>
  </PropertyGroup>

</Project>
```

Run:
1. dotnet restore
2. dotnet pack

Inspect:
1. bin/Debug/{ProjectName}.1.0.0-suffix-1234.nupkg
 - The nuspec inside also has the unexpected `1.0.0-suffix-1234` version number
2. obj/Debug/{ProjectName}.1.0.0-prefix-suffix-1234.nuspec
 - This nuspec has the expected `1.0.0-prefix-suffix-1234` version number

# Expected
The artifacts generated by Pack are minimally self-consistent. Given that both 'Version' calculations are present, `1.0.0-prefix-suffix-1234` is preferable as it matches expectations set by the properties' names AND matches the behavior of the SDK as described in #4404.

# Actual
The Pack target produces two different projections of `Version`, clearly displaying a design conflict within the target's implementation.

/cc @jonsequitur @blackdwarf @livarcocc @srivatsn @rrelyea @rohit21agrawal

**Comment by rohit21agrawal** [comment]
already fixed by https://github.com/NuGet/NuGet.Client/pull/1139
