### ISSUE TITLE
NuGet cache should treat pre release version in different way than releases

### ISSUE THREAD

**Issue by jmusek** [NuGet/Home#441]
When package is "pre release" type should not be affected by cache or during Restore should be checked if package was not changed, because version can be same, but content different.

This behavior can be visible if you use Nexus server instead of NuGet galery where packages in Snapshot repositories can be overwritten with same version to minimize impact on users. Developers are not force then change version number at all until package is ready to be released. In a nutshell they are releasing every night from CI package 1.0.0-Snapshot which others can use next day for testing without changing anything (ideal for sprint when you don't change interface, but just fill functions content).

**Comment by deepakaravindr** [comment]
This does not work with nuget.org, because a package is immutable. But, we are considering floating versions feature, so, this problem should go away in the future
