### ISSUE TITLE
PCL Profile lib folder difference between Debug and Release build with Xamarin Cross-Platform

### ISSUE THREAD

**Issue by dev-nextprogress** [NuGet/Home#4410]
When creating packages with nuget.exe (tried 3.4.4 and 3.5.0) using a PCL library, in the debug build, it results in automatic detection of all supported platforms as configured in Visual Studio. In my case with profile 111:
portable-net45+win+wpa81+MonoAndroid10+xamarinios10+MonoTouch10

The exact same library, using the same nuget script, when built in release mode results in skipping all the Xamarin cross-platforms and the lib folder only contains:
portable45-net45+win8+wpa81

Has anybody seen this before ?
Is this a nuget or maybe a msbuild/Visual Studio Problem ?
Thanks

**Comment by rohit21agrawal** [comment]
Can you provide us with a repro project for the same so we can investigate?

**Comment by dev-nextprogress** [comment]
So, after creating a new small pcl project for you to investigate, it turns out that now all builds result in portable45-net45+win8+wpa81
No more MonoAndroid10+xamarinios10+MonoTouch10
BUT
It is a) consistent between debug and release builds and b) I can add the packages to the Android and iOS projects.
So something has changed, but I am pretty sure it is not related to nuget.exe, since it works the same between 3.4.4 and 3.5.0. Probably a Xamarin upgrade. I just have to change all the existing package reference hint paths.
Will close it from here. Thanks for your help and contribution.
