### ISSUE TITLE
Installing certain packages into a WinForms projects with Package reference fails.

### ISSUE THREAD

**Issue by unniravindranathan-okta** [NuGet/Home#4417]
1. Create a WinForms Project (by default it targets .NET 4.5.2, change it to 4.5)
2. Open Package Manager and search for Vlc.DotNet.Forms
3. Click Install

**Observed:**
If you select packages.config, everything installs fine
If you select PackagesRef, you get the following error: 

Restoring packages for c:\users\rmpablos\documents\visual studio 2017\Projects\WindowsFormsApp45\WindowsFormsApp45\WindowsFormsApp45.csproj...
Restoring packages for c:\users\rmpablos\documents\visual studio 2017\Projects\WindowsFormsApp45\WindowsFormsApp45\WindowsFormsApp45.csproj...
Package Vlc.DotNet.Core.Interops 2.1.130 is not compatible with net45 (.NETFramework,Version=v4.5). Package Vlc.DotNet.Core.Interops 2.1.130 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETFramework,Version=v4.5.
Package Vlc.DotNet.Core.Interops 2.1.130 is not compatible with net45 (.NETFramework,Version=v4.5) / win. Package Vlc.DotNet.Core.Interops 2.1.130 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETFramework,Version=v4.5 (win).
Package Vlc.DotNet.Core.Interops 2.1.130 is not compatible with net45 (.NETFramework,Version=v4.5) / win-x64. Package Vlc.DotNet.Core.Interops 2.1.130 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETFramework,Version=v4.5 (win-x64).
Package Vlc.DotNet.Core.Interops 2.1.130 is not compatible with net45 (.NETFramework,Version=v4.5) / win-x86. Package Vlc.DotNet.Core.Interops 2.1.130 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
One or more packages are incompatible with .NETFramework,Version=v4.5 (win-x86).
Package restore failed. Rolling back package changes for 'WindowsFormsApp45'.
Time Elapsed: 00:00:00.1879491
========== Finished ==========

**Comment by zhili1208** [comment]
it's fixed
