### ISSUE TITLE
Building soon after starting NuGet operation (install, update, restore), can cause VS to Hang

### ISSUE THREAD

**Issue by diverdan92** [NuGet/Home#4420]
1. File -> New C# Console App (.NET Framework)
2. Right click References -> Manage NuGet Packages...
3. Add Reference to Newtonsoft.Json using Packages.config
4. VS Hangs

Not 100% repro, but ping dajaco@microsoft.com for crash dump.

**Comment by emgarten** [comment]
@diverdan92 what version of Visual Studio are you seeing this with?

**Comment by diverdan92** [comment]
@emgarten D15prerel 26127.00 with a patch from @jainaashish

**Comment by jainaashish** [comment]
Crash dump doesn't reflect the above scenario, rather it says it crashed some where in auto-restore.

**Comment by jainaashish** [comment]
After analyzing the crash dump, I can see there are 3 different call stacks which is hard to understand as in how a user can create such a behavior. Also We're not able to repro it again so I really don't understand what would have happened at that time and how it came into this situation.

1. First call stack indicates that on build restore was in progress and Main thread was also waiting in there inside some JTF
2. Second call stack indicates that auto restore was also in progress and it was trying to write restore summary to output console and waiting in some JTF to get on the UI thread.
3. Third call stack shows that install package (newtonsoft.json) was also in progress for packages.config based project and it tried to execute install script which failed and it was trying to write error message on output console by trying to get on the UI thread.

**Comment by diverdan92** [comment]
Thanks @jainaashish - seem like reasonable conclusion to me. What do you propose for next steps? See if it reproduces in the future?

**Comment by jainaashish** [comment]
@diverdan92 after digging little more into crash dump, and analyzing it, I finally understood what were you doing 😄 and repro this issue locally. Scenario is you start a package install (newtonsoft.json) with packages.config based projects and immediately do F5 to build it as well which will make it hang.

**Comment by diverdan92** [comment]
@jainaashish that's great news 👍 you can get a consistent repro? Is the fix achievable then?

**Comment by jainaashish** [comment]
yeah i can get a consistent repro, not sure about the fix though

**Comment by emgarten** [comment]
@jainaashish are you able to tell why the UI thread is waiting?

**Comment by rrelyea** [comment]
@jainaashish - please brainstorm with @emgarten and @dtivel on possible fixes asap

**Comment by rrelyea** [comment]
also...perhaps @emgarten can help see how many watson hits we've seen of this, to understand customer impact.

**Comment by rrelyea** [comment]
Also, why doesn't this occur in VS2015? Do we show a dialog in that case? Etc...

**Comment by rrelyea** [comment]
@jainaashish & @emgarten  - update on this? what do you know? how likely is fix?
