### ISSUE TITLE
NuGet packages fail to restore for UWP projects

### ISSUE THREAD

**Issue by diverdan92** [NuGet/Home#4421]
1. File -> New UWP Project in VS 2017
2. Fails with dialog:
![image](https://cloud.githubusercontent.com/assets/6608201/22392919/89bec300-e4b3-11e6-8c58-8ba418748426.png)
3. Try to restore NuGet packages
![image](https://cloud.githubusercontent.com/assets/6608201/22392933/ba285cfe-e4b3-11e6-91de-7c08cde40f5f.png)

Completely blocked from building a UWP app.

**Comment by emgarten** [comment]
This looks like the same issue as https://github.com/dotnet/sdk/issues/745

**Comment by jainaashish** [comment]
@diverdan92 are you able to repro it again? I tried repro it several times but couldn't do that.

**Comment by diverdan92** [comment]
@jainaashish  not yet
