### ISSUE TITLE
Poor error message when referencing .NET Standard Library that is not applicable to project

### ISSUE THREAD

**Issue by diverdan92** [NuGet/Home#4423]
1. Create new .NET Standard Library targeting .NET Standard 1.4
2. Pack it as a NuGet Package
3. Create a new WPF app (targeting .NET 4.5.2) 
4. Try to reference the .NET Standard Library NuGet Package 
5. Add it as "Package Reference in Project File"

Error Message:
![image](https://cloud.githubusercontent.com/assets/6608201/22393292/b643c948-e4b8-11e6-8f61-47764feae659.png)

**Comment by zhili1208** [comment]
it's fixed
