### ISSUE TITLE
Consolidate removes "type": "build"

### ISSUE THREAD

**Issue by sm-g** [NuGet/Home#4425]
NuGet Version: 3.5.0.1938

before:

````json
"SonarAnalyzer.CSharp": {
      "version": "1.*",
      "type": "build"
    },
````

after Consolidate:

````json
"SonarAnalyzer.CSharp":  "1.1.0",
`````

**Comment by rrelyea** [comment]
We had to do work in NuGet 3.5 and .net core tools preview 2 to save metadata like this.
Looks like we missed this case. 

Currently, VS 2017 should not have this kind of problem. We won't be fixing this back in 3.5
