### ISSUE TITLE
Update-Package done manually in console work only one time for PackageRef projects that were just converted

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4431]
vs feedback 768960 using RC3

When I want to update some packages in my solution, the first time just after opening the solution, I click the Package Manager Console and type the command like "update-package ServiceStack.text"; it's working and I can see the traces.
Then, I try to update another package and I can see an error:

PM> update-package ServiceStack.common
update-package : Project 'Default' is not found.
At line:1 char:1
+ update-package ServiceStack.common
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Update-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

It's like that for any other package from my project.
If I restart VS, it will work once again and then fail for any other package.

**Comment by jainaashish** [comment]
This is same as https://github.com/NuGet/Home/issues/4315 after install or update package in PMC, Project is not being selected by default.

**Comment by rrelyea** [comment]
now a known issue with PackageReference .. will address post RTM.

**Comment by rrelyea** [comment]
Zhi has fix in local branch, for 4.0.1

**Comment by rrelyea** [comment]
Please create a PR, but don't add anybody to it yet. 
In addition to your normal details, please say "Once 4.0.1 work begins, i will add team members to the PR."

**Comment by zhili1208** [comment]
Rob asked me to put it in 4.1

**Comment by zhili1208** [comment]
fix is merged https://github.com/NuGet/NuGet.Client/commit/5ef411e023b61b5675dc973b402f2a71b674a6a3

**Comment by rrelyea** [comment]
Did you merge into Release-4.1.0-rtm as well? Please do.

**Comment by zhili1208** [comment]
Yes, it's also merged to 4.1
