### ISSUE TITLE
Microsoft.DiaSymReader.Native.x86.dll ends up in nuget package if TFM = netcoreapp1.1

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4432]
please engage with customer via vsfeedback number 768720

When I try to pack my class library targeted to .net core 1.1 to nuget package with Visual Studion 2017 RC3 resulting nupkg file contains files that must not... ('Microsoft.DiaSymReader.Native.x86.dll' and 'Microsoft.DiaSymReader.Native.amd64.dll' twice in folders 'content' and 'contentFiles')

**Comment by pakrym** [comment]
Might be related to https://github.com/NuGet/Home/issues/4397 (https://developercommunity.visualstudio.com/content/problem/14125/pack-warnings-when-targeting-netcoreapp11.html) warnings I was getting were exactly about these files.

**Comment by rohit21agrawal** [comment]
Yes, we have fixed this already

**Comment by sam-wheat** [comment]
@rohit21agrawal Is the fix released?  Where do I get it?  When I attempt to install  VS 15 Preview VSIX (v3.4.2) from https://dist.nuget.org/index.html I get an error message that the extension is not compatible with VS2017.   I install anyway and the pkg is not generated.  Am using VS2017 rc3.

**Comment by rohit21agrawal** [comment]
@sam-wheat 
This fix will be released before EOD today as an update to the RC3 build of visual studio you have.

You should not install a VSIX manually to your VS2017. VS2017 only support NuGet versions 4.0.0.*

**Comment by sam-wheat** [comment]
@rohit21agrawal  Thank you - just curious - the VSIX at the location I cited is for....... ?

**Comment by rohit21agrawal** [comment]
@sam-wheat it's about 6 months old as far as i can tell, and wouldn't work with the current builds of Visual Studio 2017. i'll ask the team to actually remove it from there so it doesn't mislead anyone . thanks for pointing it out :)

**Comment by sam-wheat** [comment]
@rohit21agrawal Thanks very much - one more question if you don't mind please as this fix is important to me -  will the fix be released on the download page here https://www.visualstudio.com/vs/visual-studio-2017-rc/ or will a hotfix be released?  If so, where will the fix be published?

**Comment by rohit21agrawal** [comment]
keep a watch out on https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes , it will be updated with the relevant info when the update goes live.

**Comment by sam-wheat** [comment]
@rohit21agrawal I installed the update however the problem remains.  Please advise, thx.

Microsoft Visual Studio Community 2017 RC
Version 15.0.26206.0 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Community

Visual Basic 2017 RC   00369-50000-00000-AA523
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA523
Microsoft Visual C# 2017 RC

Visual C++ 2017 RC   00369-50000-00000-AA523
Microsoft Visual C++ 2017 RC

Visual F# 4.1   00369-50000-00000-AA523
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00201.7
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30206.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30126.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.ApplicationInsights   1.0
Allows user to instrument their Service Fabric projects for Application Insights.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.13-alpha (2f64b6d)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61701.270
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual Studio Tools for Unity   3.0.0.1
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.26206.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.3.0.664 (f42aa37)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.1.0.31 (c9880f9)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.Android SDK   7.1.0.31 (c9880f9)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   10.4.0.102 (20d957a)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   10.4.0.102 (20d957a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

-------- Error Message: ------------------


1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'content\Microsoft.DiaSymReader.Native.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'contentFiles\any\netcoreapp1.1\Microsoft.DiaSymReader.Native.x86.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'content\Microsoft.DiaSymReader.Native.amd64.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Assembly outside lib folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The assembly 'contentFiles\any\netcoreapp1.1\Microsoft.DiaSymReader.Native.amd64.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'lib' folder if it should be referenced.

**Comment by rohit21agrawal** [comment]
Can you tell me the file version you have of : 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\CoreCLR\NuGet.Build.Tasks.Pack.dll"

**Comment by sam-wheat** [comment]
File Version 4.0.0.2259
Product version 4.0.0-rtm-2259

**Comment by rohit21agrawal** [comment]
weird..this should not happen..can you attach a repro project here so i can investigate?

**Comment by sam-wheat** [comment]
[pkgError.zip](https://github.com/NuGet/Home/files/759231/pkgError.zip)
Attachment per your request.

**Comment by rohit21agrawal** [comment]
quick observation - this only repros if TargetFramework is netcoreapp1.1, if i set it to netcoreapp1.0, everything works fine.

**Comment by sam-wheat** [comment]
Thanks!  Thats better than nothing - I will try and use it.

**Comment by rohit21agrawal** [comment]
This is due to the incomplete fix of : https://github.com/dotnet/roslyn/issues/15137

As a workaround for now, set ```<GeneratePackageOnBuild>false</GeneratePackageOnBuild>```

build using visual studio or CLI normally
run Pack from command line using : ```dotnet pack /p:ExcludeRestorePackageImports=true```

**Comment by rrelyea** [comment]
I need to absorb and consider the options for fixes on different sides here. Marking RTM and NeedsTriageDiscussion

**Comment by rrelyea** [comment]
lots of discussion from the folks on .net core call. 
hack in sdk or fix the package?

**Comment by rohit21agrawal** [comment]
This is being fixed by : https://github.com/dotnet/core-setup/pull/1424

**Comment by tmat** [comment]
Should be fixed in netcoreapp1.1.1.
A workaround is to add a nuget reference to https://www.nuget.org/packages/Microsoft.DiaSymReader.Native/1.4.2
