### ISSUE TITLE
When migrating to PackageRef, hybrid solutions have strange restore behavior

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4433]
vs feedback using RC3 -- vsfeedback number 747888

Opened existing VSIX project (targetting VS 2012 to 2015)
Project upgraded to support 2017
Removed existing EnvDTE references and started to replace them with NuGet package references
Added EnvDTE package successfully (chose to use PackageReferences instead of packages.config file)

Tried to add EnvDTE80 package, but getting this error:

System.ArgumentException: Value cannot be null or an empty string.
Parameter name: name
   at NuGet.PackageManagement.VisualStudio.ProjectSystemCache.ContainsKey(String name)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.RemoveEnvDTEProjectFromCache(String name)
   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<UpdateNuGetProjectToPackageRef>d__57.MoveNext()

**Comment by jainaashish** [comment]
I can repro it locally, and we should fix it.

**Comment by rrelyea** [comment]
Since we've gotten more hits, want to decrease customer pain, and noise to our team by fixing this. Will discuss today at shiprooms.

**Comment by rrelyea** [comment]
Please finish PR review/feedback (if any).
Then ensure you've tested it all it needs.
Then, we'll review it with @DoRonMotter .
if he approves, then merge into dev.

**Comment by rrelyea** [comment]
Please merge into dev
