### ISSUE TITLE
tools options default package management format - proper High DPI support

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4439]
![nuget tools options](https://cloud.githubusercontent.com/assets/16904420/22439430/6b3fa09c-e6e4-11e6-8df7-b1682de8f8ac.png)

**Comment by rrelyea** [comment]
Let's focus on the string change (from negative to positive, i believe) and the checkbox state, including correct roaming (or not) behavior.
High DPI can come in another delta.

**Comment by jainaashish** [comment]
Opened another issue to change default state and test -https://github.com/NuGet/Home/issues/4468 
And marking this bug as 4.0.1

**Comment by karann-msft** [comment]
Reactivating based on @anangaur feedback https://github.com/NuGet/Home/issues/4960

**Comment by rohit21agrawal** [comment]
@anangaur @karann-msft i don't see this repro-ing, if it still happens for you, give me the visual studio build number and dpi settings of your laptop. would be even better if you can bring it over to my desk.

**Comment by anangaur** [comment]
I see this fixed on 15.3 preview 2:
![image](https://user-images.githubusercontent.com/14800916/27654381-ed548d36-5bf6-11e7-90a8-eebce7349b15.png)

![image](https://user-images.githubusercontent.com/14800916/27654357-daddcb18-5bf6-11e7-97e2-b4d870bf8d69.png)
