### ISSUE TITLE
For UAP projects, nuget (pmc/nuget.exe) install checks TPV instead of TPMV

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4443]
nuget install checks TPV instead of TPMV.
1. create a blank UAP app with TPV = 14393, TPMV = 10586
2. from the PMC, attempt to install a nuget package which targets TPMV = 14393 i.e. lib\uap10.0.14393
Expected: package installation must fail
Actual: package installs successfully

Title was: For UAP projects, nuget checks TPMV instead of TPV
1. Create a blank UAP app with TPV = 14393, TPMV = 10586
2. Attempt to install a nuget package which targets TPV i.e. lib\uap10.0.14393
Package install fails.

Now, if I update TPMV = 14393, package installs successfully which leads me to believe we are checking TPV and not TPMV.

see [spec](https://github.com/NuGet/Home/wiki/Converting-Extension-SDKs-into-NuGet-Packages#supporting-platform-versions-in-uap-nuget-packages) for reference on expected behavior.

**Comment by emgarten** [comment]
This will be done once we determine which value to use in the TFM.

//cc  @diverdan92

**Comment by karann-msft** [comment]
alright, so the verdict is in and we are going with the current behavior. Let's repurpose this to track the work that now needs to be done to make the nuget.exe install/restore behavior to be consistent with this check i.e. check the project's TPMV.

**Comment by emgarten** [comment]
To fix this the framework helper needs to be updated: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/Utility/MSBuildProjectFrameworkUtility.cs#L15

And from VS and the command line it needs to read the TPMV instead of TPV and pass it in.
