### ISSUE TITLE
Adding nuget packages to NuGet app after deleting project.json shows error

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4444]
Steps:
1. Create UWP app that has project.json
2. Add one or more packages
3. Delete project.json
4. Try to add the same packages again

**Expected**: It should let one browse through the packages and re-add the packages while giving a choice to use PackageReference

**Actual**: It shows an error:

An error occurred while reading file '<path to old project.json>': Could not find file '<path to old project.json>'.
  Could not find file '<path to old project.json>'.

**Workaround**: Reload the project. 

**Note**: The same process works well in the packages.config world though.

**Comment by zhili1208** [comment]
project.json doesn't equal packages.config, it contains more information than packages.config, if it's missing, nuget can't create a new one for user. Close it as won't fix
