### ISSUE TITLE
UWP app: Trying to upgrade to PackageRef gives an option to opt for Packages.config and subsequently ends in error

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4445]
###Repro steps:

1. Create UWP app that has project.json
2. Add one or more packages
3. Delete project.json
4. Unload and Relaod project
5. Try to add the same packages again

**Expected**: It should not give an option to use packages.config as that's not supported. **FailFast**

**Actual**: It lets user to use packages.config approach and then throws the following error. The error too is **not useful**
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0'. You are trying to install this package into a project that targets '.NETCore,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by zhili1208** [comment]
we should provide migrate tool to user for migrating from project.json to package ref, deleting project.json is not a support approach
