### ISSUE TITLE
Updating packages deletes packages.config in TFS

### ISSUE THREAD

**Issue by stgit123** [NuGet/Home#4449]
Recurrence of issues #491 and #2215 

VS2015 Update 3 14.0.25422.01
Package Manager Console Host Version 3.4.4.1321

When updating nuget packages in Visual Studio, if there is only one package referenced in a package.config file, then sometimes that file is marked as deleted in the TFS changeset. 

Most of the time we remember to check for deleted package.config files and restore them before check-in, however sometimes a) a new developer doesn't know they have to do this, or b) we forget, and this costs us hours trying to figure out why things aren't working.

**Comment by zhili1208** [comment]
Thanks for reporting this issue. At this time we suggest moving from packages.config to PackageReference with VS 2017 to resolve your issue. You can find out more about this here: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
