### ISSUE TITLE
Xamarin.iOS10 not recognized as framework in content\ structure

### ISSUE THREAD

**Issue by madkat** [NuGet/Home#445]
Items targeting "content\Xamarin.iOS10" are handled incorrectly. In a C# project that targets Xamarin.iOS, the files are added to the project in a folder "Xamarin.iOS10", rather than to a project root. In a C# project that does NOT target Xamarin.iOS, the files are added to the project in a folder "Xamarin.iOS10", rather than not at all.

build, lib and tools all appear to behave correctly.

NuGet Package Manager 3.0.60326.141

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Packaging@4453f7eb6da937bdad6000655c52af3084ff2fc6

**Comment by madkat** [comment]
Thanks for taking care of this, @emgarten.
