### ISSUE TITLE
When a project needs to be restored, consider making autorestore restore the minimal set of projects

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4451]

**Comment by MikhailArkhipov** [comment]
Or provide switch to turn automatic operations off.

**Comment by alpaix** [comment]
@MikhailArkhipov This is tracked in NuGet/Home#3963.

**Comment by nkolev92** [comment]
Fixed through https://github.com/NuGet/Home/blob/dev/designs/VisualStudio-PartialRestoreOptimization.md
