### ISSUE TITLE
Implement a better method of blocking the build to execute restore operation

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#4457]
### Details about Problem

Current on-build restore operation is invoked by `BuildEvents.OnBuildBegin` event handler and executes synchronously while blocking the main VS thread. As a result VS UI freezes for some time until the restore completes.

### Repro steps

As reported in internal issue 375820:

1. Create a new asp.net core application
1. Build
1. Rebuild

Noticable 2-4 second delay where VS appears frozen. Output window shows nothing and then all of sudden it sill show the following

> Restoring NuGet packages...

To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'

And then the build completes almost immediately .

This is repeatable. Just do another rebuild. It's as if part of the build is happening on the UI thread.

### Possible solutions

As specified in [spec](https://github.com/NuGet/Home/wiki/NuGet-Restore-Manager#blocking-the-build-until-restore-is-complete).

**Comment by jainaashish** [comment]
Reopening this issue, since we reverted that PR because of RPS tests regression.

**Comment by jainaashish** [comment]
Need either of below thing from platform to figure out when project system is actually building:
-	A version of QueryBuildManager that returns the “modified” flags, and see there is no “SUA_BUILD” 
-	NotifyUpdateSolution_QueryDelayFirstUpdateAction() is only called ahead of the “Build” action (so not called when we chec for stuff like deploy/publish/clean_publish and other non-build actions. 
-	Have a version NotifyUpdateSolution_QueryDelayFirstUpdateActionEx(action BuildAction) that is called for each of  SBM supported steps and you latch on “action” = SUA_BUILD

**Comment by jainaashish** [comment]
VS platform corresponding bug# 440988
