### ISSUE TITLE
Ability to generate backward compatible packages

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#4461]
_From @tmat on January 31, 2017 23:1_

I tried to use packaging task from the SDK for [Microsoft.DiaSymReader.Portable](https://www.nuget.org/packages/Microsoft.DiaSymReader.PortablePdb/) package, but couldn't figure out how to add backward-compatible target frameworks in the package. Currently the package has the following structure:

```
    <dependencies>
      <group targetFramework="portable-net45+win8">
       ...
      </group>
      <group targetFramework="netstandard1.1">
       ...
      </group>
    </dependencies>
  </metadata>
  <files>
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\portable-net45+win8" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\portable-net45+win8" />
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\net45" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\net45" />
    <file src="Microsoft.DiaSymReader.PortablePdb.dll" target="lib\netstandard1.1" />
    <file src="Microsoft.DiaSymReader.PortablePdb.xml" target="lib\netstandard1.1" />
  </files>
```

```Microsoft.DiaSymReader.Portable.csproj``` only builds once (targeting ```netstandard1.1```) and the same DLL is then packaged to ```lib\portable-net45+win8``` and ```lib\net45``` and ```lib\netstandard1.1```. 
The package produced by the SDK task only contains ```netstandard1.1```. Is there a way to fill in the other targets without writing the entire .nuspec by hand?

_Copied from original issue: dotnet/sdk#769_

**Comment by srivatsn** [comment]
The pack SDK is built out of the NuGet repo. Moving this issue there.

**Comment by rohit21agrawal** [comment]
@tmat not sure i understand what you are trying to use here...could you attach your project file?

Are you using dotnet pack? What is the exact commandline you are using to pack your project?
What frameworks does your project file target?

**Comment by tmat** [comment]
@rohit21agrawal I'm trying to generate package using dotnet SDK that currently is generated using nuget.exe with this nuspec: https://github.com/dotnet/symreader-portable/blob/master/src/NuGet/Microsoft.DiaSymReader.PortablePdb.nuspec

**Comment by rohit21agrawal** [comment]
@tmat are you packing the nuspec directly or  packing using the csproj filewith the corresponding nuspec file?

it seems to me that you are hitting this issue : https://github.com/NuGet/Home/issues/2300

**Comment by tmat** [comment]
The latter. I want the nuspec to be generated from properties and package references specified in .csproj file. 
The nuspec above is how it's done now. I'm trying to migrate to the new project system. 

Yes,  #2300 looks like one of the missing parts.

**Comment by rohit21agrawal** [comment]
@tmat can you share your csproj file? Also, you are using the same DLL and XML files to output to different folders in your nupkg...so i would say that is expected given your nuspec.

**Comment by tmat** [comment]
Here: 
https://github.com/tmat/symreader-portable/blob/NewProjSystem1/src/Microsoft.DiaSymReader.PortablePdb/Microsoft.DiaSymReader.PortablePdb.csproj

**Comment by rohit21agrawal** [comment]
@tmat if you are moving to the new project system, then you don't really need a nuspec file. Move all of your dependencies and metadata to  your csproj file, and use the latest dotnet sdk from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip to pack your project.

You need to change your targetframework in the project so it targets and builds for each of the framework you want your package to be compatible with.

More details about how the new Pack works in dotnet cli can be found at : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

Please feel free to ask more questions.

**Comment by tmat** [comment]
I understand that I shouldn't need the nuspec file.

> You need to change your targetframework in the project so it targets and builds for each of the framework you want your package to be compatible with.

I don't want to build the project 3 times. The dlls for all 3 target frameworks are the same. ```lib\portable-net45+win8``` and ```lib\net45``` are there only to make the package compatible with older nuget.

**Comment by rrelyea** [comment]
We plan to address #2300 --- but it seems like this request won't be very common and can be achieved by using a nuspec. So closing this issue.

**Comment by tmat** [comment]
@rrelyea Although it's true it can be achieved using nuspec it means I now need to manage the dependencies manually again, gaining no benefit from the Pack task whatsoever.
