### ISSUE TITLE
"Generate NuGet package on build" doesn't play nicely with clean

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4464]
1. Turn on "Generate NuGet package on build"
2. Build
3. Clean

**Expected:** Obj/bin to be empty
**Actual:**

The generated nuspec and nupkg are still on disk.

To play nicely with Clean, you should add any file you write to the FileWrites items, here's an example: https://github.com/Microsoft/msbuild/blob/dd5e8bc3f86ac98bd77d8971b00a6ad14f122f1a/src/XMakeTasks/Microsoft.Common.CurrentVersion.targets#L2036.

**Comment by rrelyea** [comment]
we have taken a fix for nupkg clean already. without filewrites. reviewed with @rainersigwald. hasn't made it to VS build yet. @rohit21agrawal 
the assets file is a new issue. will track in 4.0.1.

**Comment by davkean** [comment]
I don't call out assets file above (which is a separate issue and needs some design work), but I do call out the Nuspec - do you clean this up?

**Comment by rohit21agrawal** [comment]
Yes

**Comment by davkean** [comment]
Okay so this bug is done? Do you have a bug about assets file cleanup? That's seems a lot harder to figure out (because of background restore).

**Comment by rohit21agrawal** [comment]
Yes closing this bug, and created a new one to track assets file clean up : https://github.com/NuGet/Home/issues/4476
