### ISSUE TITLE
NuGet sometimes fails to resolve a project after a reference is added

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4465]
Build: 26131.0.d15rel

1. Create a Console App (.NET Core)
2. Create a Class Library (.NET Standard)
3. Add a reference from the App -> Library

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve 'c:\users\davkean\documents\visual studio 2017\Projects\Foo\A\B\B.csproj' for '.NETCoreApp,Version=v1.0 (win-x64)'.			0	
Error		Unable to resolve 'c:\users\davkean\documents\visual studio 2017\Projects\Foo\A\B\B.csproj' for '.NETCoreApp,Version=v1.0 (win-x86)'.			0	
Error		Unable to resolve 'c:\users\davkean\documents\visual studio 2017\Projects\Foo\A\B\B.csproj' for '.NETCoreApp,Version=v1.0'.			0	
Error		Unable to resolve 'c:\users\davkean\documents\visual studio 2017\Projects\Foo\A\B\B.csproj' for '.NETCoreApp,Version=v1.0 (win)'.			0	
```

This happened to ~10 times tonight, it's not consistent and don't know what the repro is.  Once you get into this state, couldn't get rid of the errors until I closed the solution and reopened.

**Comment by davkean** [comment]
Hitting this a lot.

**Comment by rrelyea** [comment]
Which build did you last test when you didn't hit this? (want to investigate NuGet and other changes that may have caused problems here.)

**Comment by rrelyea** [comment]
can you tell more about your repro?
were you multi-targeting in either project?
using rids anywhere?
did the errors happen on the reference add? or some further step (like auto restore after that step)?

**Comment by rrelyea** [comment]
haven't been able to repro. putting into rtm for now and we'll keep trying a bit.

**Comment by davkean** [comment]
26131.0.d15rel, no rids, no multi-targeting very basic File -> New projects.

I spent some time thinking about this and this behavior could be described if you are mixing us Nominating   and then going and querying our IVsHierarchy or IVsSolution which we might not have published by that time.

ie We nominate a new project reference, you go and query for that reference from our VSProject - it could be missing because we've not yet published.

**Comment by davkean** [comment]
This is a race - it seems like whatever my box is, it tends to hit these races.

**Comment by davkean** [comment]
@alpaix @emgarten My comment above, would that describe what you are doing?

**Comment by rrelyea** [comment]
can you try to repro on a slow VM? Or other tricks to hit this race conditions...

**Comment by davkean** [comment]
Let me figure it out - we might be able to put a hack in place to "delay" the publishing of the tree to IVsHierarchy, etc - which would making it painfully obvious that your expecting our nominate data to match  it.

**Comment by emgarten** [comment]
@davkean does the project B show up in the powershell console project drop down list? I wonder if NuGet is missing the project add event and not tracking the project in the internal cache of projects in the solution.

**Comment by rrelyea** [comment]
Any news?

**Comment by rohit21agrawal** [comment]
no repro on my side yet. tried with a 1 core 1.7 GB Ram virtual machine on Xlab

**Comment by rrelyea** [comment]
If we can get a repro, we'll bring back to 4.0 rtm

**Comment by rohit21agrawal** [comment]
closing as no reports in the last 6 months almost.
