### ISSUE TITLE
vsfeedback: error building solution... - restore has problem loading system.io.filesystem?

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4467]
vs vsfeedback 769304

from vs feedback issue.... (more text can be found there):

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolvePackageDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.NET.Build.Tasks.LockFileCache.LoadLockFile(String path)
   at Microsoft.NET.Build.Tasks.LockFileCache.GetLockFile(String path)
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.get_LockFile()
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ReadProjectFileDependencies()
   at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

=== Pre-bind state information ===
LOG: DisplayName = System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.NET.Build.Tasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().

**Comment by paulomorgado** [comment]
It's a project file issue.

This is a fresh created project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <RootNamespace>Morgados.StateMachines</RootNamespace>
    <OutputTypeEx>library</OutputTypeEx>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="codecracker.CSharp" Version="1.0.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" />
  </ItemGroup>
</Project>
```

This is the corresponding original project files:

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>973ed6d3-f40b-48b6-b4fb-c5a0ebddefe5</ProjectGuid>
  </PropertyGroup>
  <PropertyGroup Label="Configuration">
    <AssemblyName>StateMachineExplorations</AssemblyName>
    <RootNamespace>Morgados.StateMachines</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="codecracker.CSharp">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="NETStandard.Library">
      <Version>1.6.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Sdk">
      <Version>1.0.0-alpha-20161104-2</Version>
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.3.0" />
    <PackageReference Include="System.ValueTuple" Version="4.3.0" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by piersdb** [comment]
I also experienced this issue. The fix was to make all the PackageReference version numbers inline, change the <project> directives to the new form and remove all tags that are not in the "new" .csproj format. Essentially convert from the old format to the new format.

**Comment by emgarten** [comment]
This has been fixed in the SDK and will be in the next release.

The workaround from @natidea is:
```
copy %USERPROFILE%\.nuget\packages\system.io.filesystem\4.0.1\lib\net46\System.IO.FileSystem.dll %VSINSTALLDIR%\MSBuild\Sdks\Microsoft.NET.Sdk\tools\net46\
devenv /updateconfiguration
```

Please reopen this if the above workaround doesn't help.

**Comment by 2rik** [comment]
Solution @natidea suggested does not work for me.

**Comment by rrelyea** [comment]
@2rik - which build of VS 2017 RC are you running with? A new one was released on 2/7.
Have you just tried moving to that version, where a workaround shouldn't be needed?

**Comment by 2rik** [comment]
I am running VisualStudio/15.0.0-RC.4+26206.0

**Comment by rrelyea** [comment]
@emgarten - which SDK bug was fixed? Should it be reactivated? Or should we reactivate this issue? or both?

**Comment by 2rik** [comment]
Sometimes it helps to create new empty ASP.NET Core project and close it. After it error disappears for some time.

**Comment by rrelyea** [comment]
team - reactivating since @2rik is seeing this on RC4 bits. please try to repro with old project loaded in RC4. can we repro? why? Will this be common enough that we should improve something?

**Comment by emgarten** [comment]
@rrelyea internal bug 365633

**Comment by natidea** [comment]
@2rik what does the project file that is reproing this look like? I cannot repro it on the project file presented above.

**Comment by rrelyea** [comment]
@emgarten @natidea  - i'm assuming this should continue to be driven from @natidea -- is that correct? 

please let us know if you need anything from us, or if we should drive?

**Comment by rrelyea** [comment]
Marking as external, and will keep open and report on progress we hear from @natidea and team

**Comment by 2rik** [comment]
@natidea I have this issue happening on the project attached.

[project.txt](https://github.com/NuGet/Home/files/767104/project.txt)

**Comment by natidea** [comment]
@2rik I have not been able to repro with your project file, though I did have some other issues in part because this is an old-style project file. I would recommend using the simplified project file format you see when you create a new ASP.NET Core project, (or if this project was originally migrated, you could try running migration again with the latest VS RC). 

Specifically in your project, you can add an SDK attribute to the project element:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
```
and remove the Common props and CSharp targets imports:
```xml
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
...
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
```
Following these changes, warnings will appear directing you to remove `Compile`,  `EmbeddedResource` and `Content` items that are now included implicitly. See http://aka.ms/sdkimplicititems for more details. Also see http://aka.ms/sdkimplicitrefs for warnings about removing implicitly referenced packages.

Hope this helps.
