### ISSUE TITLE
DotNetCliToolReference doesn't import targets.

### ISSUE THREAD

**Issue by olydis** [NuGet/Home#4469]
## Problem
We have a tool that's referenced by `DotNetCliToolReference`.
It installs correctly and will run from the command line.
When it installs, however, it does not put references to the `.targets` file in the tool package (into the `.g.targets` file).
For that to happen, we had to put a package reference in as well (workaround, see below).
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-razor" Version="1.0.0" />
    <PackageReference Include="dotnet-razor" Version="1.0.0" /> <!-- I shouldn't have to do this -->
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
</Project>
```

The following will only appear in the `.g.targets` file if we add the `PackageReference`:
```xml
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)dotnet-perks.codegen\1.0.0\build\netcoreapp1.0\dotnet-Perks.CodeGen.targets" Condition="Exists('$(NuGetPackageRoot)dotnet-perks.codegen\1.0.0\build\netcoreapp1.0\dotnet-Perks.CodeGen.targets')" />
  </ImportGroup>
```

## Details about Problem

NuGet product used: dotnet.exe

dotnet.exe --version: 1.0.0-rc4-004707

OS version: win10 v1607 (14986.1001)

## Detailed repro steps so we can see the same problem

1. Add a `DotNetCliToolReference` to a package that has a `.targets` file.

2. Call `dotnet restore`.

3. Find that `.g.targets` does not reference the `.targets` of the referenced tool, as it would be the case for a `PackageReference`.

## Other suggested things

We posted the issue at https://github.com/dotnet/cli/issues/5522 before.
They pointed us here and also suggested adding `<PrivateAssets>All</PrivateAssets>` to the `PackageReference` in order for the workaround to be less impactful.

### Verbose Logs (`dotnet restore -v diag`)

```
C:\Program Files\dotnet\sdk\1.0.0-rc4-004707\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\1.0.0-rc4-004707\dotnet.dll /m /t:Restore /v:m /verbosity:diag .\TestApp.csproj
  Restoring packages for C:\work\Perks\src\Microsoft.Perks.CodeGen.Tests\TestApp.csproj...
  Restoring packages for C:\work\Perks\src\Microsoft.Perks.CodeGen.Tests\TestApp.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\work\Perks\src\Microsoft.Perks.CodeGen.Tests\obj\project.assets.json
  Restore completed in 520.52 ms for C:\work\Perks\src\Microsoft.Perks.CodeGen.Tests\TestApp.csproj.
  Restore completed in 1.17 sec for C:\work\Perks\src\Microsoft.Perks.CodeGen.Tests\TestApp.csproj.

  NuGet Config files used:
      C:\Users\***\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

### Sample Project

https://github.com/Azure/Perks/tree/db0c447d8327472f41d382057950caf8b520dbe4/src/Microsoft.Perks.CodeGen.Tests

**Comment by rrelyea** [comment]
Don't want fix yet...but please dig into this, and let's discuss the situation.

**Comment by rrelyea** [comment]
Yes, by design. Putting in future milestone to consider evolving in future. For now, you'll need both.

**Comment by emgarten** [comment]
Adding a `PackageReference` is the correct approach. Tools are independent of the project, they do not contribute assets to the project's build. 

Likewise when a tool is executed it runs independent of the project's target framework and build.
