### ISSUE TITLE
AutoReferenced docs and fwlink

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4470]
The Package Manager UI contains a link to ``https://go.microsoft.com/fwlink/?linkid=841238`` when displaying the netcore app package that is referenced under the SDK.

We need
* A doc explaining what this means, why it can't be managed through NuGet and how to update this package
* Update https://go.microsoft.com/fwlink/?linkid=841238 to point to this doc

This link/message is shown in the UI for packages that have ``<IsImplicitlyDefined>true</IsImplicitlyDefined>``

**Comment by kraigb** [comment]
Do you know who owns the fwlink? I'd like to know what it's currently pointing to in order to see if there's older content that we can resurrect for this.

**Comment by emgarten** [comment]
@kraigb I had the fwlink created, it is brand new for this purpose.

**Comment by emgarten** [comment]
@kraigb has this doc been written?

**Comment by kraigb** [comment]
No, haven't pursued this one yet.

**Comment by kraigb** [comment]
@emgarten I'm at the point where I can work on this now, but I'll need more details to pull a doc together. 

- What are the circumstances under which an error appears? You mention "netcore app package" but that doesn't mean anything to me. Nor am I use what SDK you're referring to. I can see that it would apply to anything with the IsImplicitlyDefined tag, but where would that appear in the package itself?
- What is the specific error message that appears? (The docs should include that text for search.)
- What is the resolution for the error?

**Comment by emgarten** [comment]
There are no errors. Packages marked as implicitly referenced on the PackageReference found in the SDK will have the update/uninstall options disabled in the NuGet UI. They will also not be displayed under the updates tab.

The reason for this is that to upgrade this the user needs to upgrade their SDK and not just the nuget package.

**Comment by kraigb** [comment]
What SDK are we talking about here, exactly? I need to walk through the scenario to show a few screenshots too, I think. In other words, what are the repro steps to see this in action?

**Comment by kraigb** [comment]
You can set the fwlink to https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#updating-a-package, which describes the scenario.

**Comment by emgarten** [comment]
@karann-msft would you up the fwlink?

**Comment by karann-msft** [comment]
done
