### ISSUE TITLE
Improve UI description for AutoReferenced packages

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4471]
The current UI experience for auto referenced packages coming from the SDK is very basic due to localization concerns. This should be improved post 4.0-RTM.

#### Suggested text:
This is an auto referenced package which you cannot manage using the NuGet Package Manager. Learn more about auto referenced packages. (auto referenced is an http link).

**Comment by kraigb** [comment]
FWIW, the docs have a note about this now: https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#updating-a-package

**Comment by kraigb** [comment]
@emgarten You can close this one now. The fwlink from the UI goes to the docs page.
