### ISSUE TITLE
Extend auto-restore + init.ps1 fix to all project types

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#4478]
I introduced a fix just for CPS-based (xplat) PackageReference projects to help init.ps1 work properly after auto-restore is complete. The fix only works when there is at least one xplat PackageReference project in the solution. We made this selective change to limit risk.

We should extend this to non-xplat PackageReference, and project.json-based solutions. Even packages.config projects? Not sure.

**Comment by nkolev92** [comment]
No customer engagement for this. 

Closing as not relevant :)
