### ISSUE TITLE
Multi-TFM build failure : Asset file missing Target

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4479]
- Create a .Net standard class library 
- Edit the csproj and change TFM to 
`<TargetFrameworks>netstandard1.4</TargetFrameworks>`
will be promoted to reload 
Build 
- Edit the csproj and change to 
` <TargetFrameworks>netstandard1.4;netstandard1.0</TargetFrameworks>`
Build 

**Expected** 
Builds successfully 

**Actual** 

![image](https://cloud.githubusercontent.com/assets/12449387/22568433/b2760ecc-e948-11e6-9476-7e558af8866e.png)

> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(76,5): error : Assets file 'c:\users\jinuj\documents\visual studio 2017\Projects\ClassLibrary10\ClassLibrary10\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.0'. Ensure you have restored this project for TargetFramework='netstandard1.0' and RuntimeIdentifier=''.

I have tried restoring the solution and rebuilding , which doesn't resolve the issue
**Note**: Closing and reopening the project fixes it.

**Build**: 26201.01.d15rel

**Comment by davkean** [comment]
Changing the TFM -> TFMs, should have prompted a reload, no?

**Comment by rohit21agrawal** [comment]
This issue was moved to dotnet/roslyn-project-system#1503
