### ISSUE TITLE
GeneratePackageOnBuild=True: Ability to also specify package folder 

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4480]
_From @niemyjski on February 2, 2017 21:35_

Would be great if I could specify a path as well... Or maybe if a path is specified packages are just built....

_Copied from original issue: dotnet/roslyn-project-system#1452_

**Comment by rohit21agrawal** [comment]
@davkean @niemyjski  Doesn't ```<PackageOutputPath> ``` does exactly that?  Or am i misunderstanding the ask here?

**Comment by niemyjski** [comment]
Doh, I missed this property I searched everywhere. let me try that... Hitting race condition too https://github.com/dotnet/cli/issues/5563

**Comment by rohit21agrawal** [comment]
The race condition has already been fixed in the latest builds of CLI

**Comment by niemyjski** [comment]
Any ideas on a release of that or a good way to update to latest from a ci using vs2017 rc3 (appveyor)

I think I may need to log another issue for this unless this is fixed :)
![screen shot 2017-02-02 at 5 04 21 pm](https://cloud.githubusercontent.com/assets/1020579/22572427/b55151bc-e969-11e6-95d4-b02f0ab2af24.png)

**Comment by rohit21agrawal** [comment]
@niemyjski for command line , you can just download the latest SDK + CLI from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip

If you want to try visual studio, you'll have to wait for the first RTW build that is released for preview. However, you can test this out by patching your visual studio installation. Here are the steps:

1) Download the CLI + SDK from the link above.
2) Extract it and copy the folder ```sdk\1.0.0-rc4-004755\Sdks\NuGet.Build.Tasks.Pack```
3) Replace the NuGet.Build.Tasks.Pack folder in ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack``` with the folder specified above.

Restart Visual Studio and you are set.

**Comment by rohit21agrawal** [comment]
Also, here is the spec for the Pack feature which provides a list of all inputs it takes : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

**Comment by niemyjski** [comment]
Thanks

**Comment by niemyjski** [comment]
Should I log a bug somewhere where I run the build once and it creates two different packages with different version numbers?

**Comment by rohit21agrawal** [comment]
Yes please, if it still repros with the latest CLI+SDK or updated Pack SDK in VS.

Would appreciate if you attached a repro project too.

**Comment by rohit21agrawal** [comment]
@niemyjski haven't seen the bug about the two different packages with different version numbers being created.. is it fixed for you?

**Comment by niemyjski** [comment]
Yes, still seeing it with the repo above, I need to create the issue https://github.com/exceptionless/Foundatio/tree/feature/dotnet

**Comment by rohit21agrawal** [comment]
@niemyjski i was able to repro the issue using your repository, but the issue has since been fixed in the newer internal builds

If you do the steps i outlined in https://github.com/NuGet/Home/issues/4480#issuecomment-277122087 , you will not hit the issue again. Let me know if you still face issues though, i am happy to help.
