### ISSUE TITLE
When packing a project, the content files inside a folder with PackagePath errors out

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#4481]
Moving from https://github.com/Microsoft/msbuild/issues/1666 on behalf of @roysanchez

----

When a content file is inside a folder and has the PackagePath specified, the generated nuget spec joins the PackagePath and the current path of the file, resulting in a non existing route that fails when the package is imported.

The error happens in the new VS2017 build. 26127.3

Created this [gist of the issue](https://gist.github.com/roysanchez/66e838ad32bf9bbbaa384e4bb3484406).

These are the relevant parts:
csproj:
```csproj
  <ItemGroup>
    <Content Include="Folder\TextFile1.txt">
      <PackagePath>Test\TextFile1.txt</PackagePath>
    </Content>
    <Content Include="TextFile2.txt">
      <PackagePath>Test\TextFile2.txt</PackagePath>
    </Content>
</ItemGroup>
```
nuspec:
```nuspec
  <files>
    <file src="c:\users\u28827\documents\visual studio 2017\Projects\ClassLibrary9\ClassLibrary9\bin\Debug\netstandard1.4\ClassLibrary9.dll" target="lib\netstandard1.4\ClassLibrary9.dll" />
    <file src="c:\users\u28827\documents\visual studio 2017\Projects\ClassLibrary9\ClassLibrary9\Folder\TextFile1.txt" target="Test\TextFile1.txt\Folder\TextFile1.txt" />
    <file src="c:\users\u28827\documents\visual studio 2017\Projects\ClassLibrary9\ClassLibrary9\TextFile2.txt" target="Test\TextFile2.txt" />
</files>
```

**Comment by rohit21agrawal** [comment]
[packagepath4481.zip](https://github.com/NuGet/Home/files/749244/packagepath4481.zip)

@roysanchez @rainersigwald 

This has been fixed already,pending insertion in VS. See attached project.
To try it out from command line , use latest CLI+SDK from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.zip

**Comment by rohit21agrawal** [comment]
@roysanchez You can also test this out by patching your VS Installation : 

1) Download the CLI + SDK from the link above.
2) Extract it and copy the folder sdk\1.0.0-rc4-004755\Sdks\NuGet.Build.Tasks.Pack
3) Replace the NuGet.Build.Tasks.Pack folder in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack with the folder specified above.

Restart Visual Studio and you are set
