### ISSUE TITLE
Entire chain of Class Library (.NET Standard) dependencies need to be referenced to compile

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4482]
_From @praneethw on January 24, 2017 14:2_

In VS2017 the entire chain of Class Library (.NET Standard) dependencies need to be referenced to compile. 

For instance in the dependency hierarchy such as below below, 
.ASPNET Core **Web API** **->** .Net Standard **Class Library 1** **->** .Net Standard **Class Library 1**

Both .Net Standard **Class Library 1** and .Net Standard **Class Library 1** need to be referenced by .ASPNET Core **Web API** to compile.See the image attached for more info,
![comple error](https://cloud.githubusercontent.com/assets/13520386/22250283/59eace06-e26c-11e6-8bf4-e297e8299283.jpg)

Upon adding sub dependencies compilation suceeds. See the image attached for more info,
![comple success](https://cloud.githubusercontent.com/assets/13520386/22250462/fb546d60-e26c-11e6-90e6-81c8b8cf0c25.png)

_Copied from original issue: aspnet/Tooling#967_

**Comment by nkolev92** [comment]
I could not reproduce this in 26206.0-d15rel and NuGet version 4.0.0.2275.

@davkean Can you please provide the dummy project you're using?

**Comment by davkean** [comment]
@nkolev92 I just ported the bug, you might want to ask @praneethw.

**Comment by rrelyea** [comment]
Marking not repro. Pinged @praneethw in other repo for more info.

**Comment by rrelyea** [comment]
No response. No repro. Closing as no repro.
