### ISSUE TITLE
Build solution with ASP.NET Core web app, build does not start

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4486]
internal bug: 378399

**Comment by rrelyea** [comment]
just tried following:
1) clear nuget locals
2) new asp.net core web app project
3) build solution while restore is going on.
expected: restore would finish, then build would start
actual: restore would finish, then build would start
(it was odd that the build output window was up during this time, and looked like nothing was happening).

Is that what people are seeing??? or is build really not starting eventually?

**Comment by rrelyea** [comment]
@alpaix  - ?

**Comment by alpaix** [comment]
@rrelyea What's the difference b/w expected and actual?

Empty build output window while waiting for restore operation to complete is "by-design."

**Comment by rrelyea** [comment]
Is it possible for us to say something like, "waiting for restore completion" in that window to have a smoother user experience?

**Comment by alpaix** [comment]
If it's blocked by CPS it happens earlier than NuGet is engaged. In this particular scenario CPS was draining critical tasks that could be anything not necessarily restore.

**Comment by rrelyea** [comment]
Moved internal bug to CPS path and following up with appropriate folks to see if they can safely fix in 15.0 timeframe.

**Comment by rrelyea** [comment]
Let's see if the fix for https://github.com/NuGet/Home/issues/4420 improved the experience?

**Comment by jainaashish** [comment]
I looked into the crash dump and surprisingly neither the main thread nor any bg thread had any pointers towards NuGet.* assemblies or what so ever. So I couldn't relate the crash dump with repro steps and nor could i know where in NuGet it hanged if it indeed was related to NuGet.

Now, if I just go by the repro steps then https://github.com/NuGet/Home/issues/4420 should improve this experience, it may delay your solution build until auto restore is in progress but build will always happen. So let us know if you can repro this again with latest code.

**Comment by DoRonMotter** [comment]
This scenario and the scenario Jinu references should be covered in:
https://github.com/NuGet/Home/issues/4386
