### ISSUE TITLE
Packages with MinClientVersion 4.0.0 fail to install in Visual Studio 2017

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4492]
Visual Studio 2017 contains NuGet 4.0.0 however it is unable to install packages with ``<metadata minClientVersion="4.0.0">``

This is due to the assembly metadata which contains ``4.0.0-rtm-2265``. The MinClientVersion check sees this as a prerelease version of the client that is less than 4.0.0 stable, and rejects the package.

### Steps
1. Create a netstandard class library
1. Add ``<MinClientVersion>4.0.0</MinClientVersion>``
1. Pack
1. Install the nupkg into a NETCore project.

### Expected
The package will install.

### Actual
```
The 'TestPackageMinVersionFour 1.0.0' package requires NuGet client version '4.0.0' or above, but the current NuGet version is '4.0.0-rtm-2265'. To upgrade NuGet, please go to http://docs.nuget.org/consume/installing-nuget
```

### Workaround
The workaround for this would be use a MinClientVersion of 3.9999999999 instead of 4.0.0. This is very confusing however.

### Fixes
This could be fixed by one of the following
1. Ignore release labels when reading the assembly metadata to find the current version.
1. Update assemblies to use stable versions

**Comment by mishra14** [comment]
validated with NuGet 2275
