### ISSUE TITLE
[Test Failure] The installed package is blocked by project in .NET Core project

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4493]
**NuGet Version:** NuGet 4.0.0-rtm-2265
**VS Version:** D15Rel 26202.00
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.	New a Visual C#->.NET Core ->Console App (.NET Core) project.
2.	Right-click on the project and click ‘Manage NuGet Packages…’.
3.	Go to ‘Installed’ tab.

**Actual Result:**
The installed package is blocked by project as below screenshot.
![untitled202](https://cloud.githubusercontent.com/assets/20632775/22585710/1ca4d256-ea34-11e6-9bb4-10309c07b11b.png)
 

**Notes:**
The issue repro on all .NET Core project.

**Comment by rrelyea** [comment]
By design for netcoreapp.  Right way to change version is by changing target framework in project properties.

**Comment by MelbourneDeveloper** [comment]
Yes, but the project properties only allow us to select up to version 1.6.1 for .NET Standard. How can we select higher versions? Is there an extra SDK pack we need to download?
