### ISSUE TITLE
GeneratePackageOnBuild creates two packages with two different version numbers.

### ISSUE THREAD

**Issue by niemyjski** [NuGet/Home#4494]
If I turn generate package on build on with the latest 2017 RC3, I get two packages created:

clone https://github.com/exceptionless/Foundatio/tree/feature/dotnet , then turn on generate package on build on and then build the foundatio project from the command line

![screen shot 2017-02-02 at 5 04 21 pm](https://cloud.githubusercontent.com/assets/1020579/22600402/ecda1d58-e9ff-11e6-9396-9242091de76b.png)

**Comment by rohit21agrawal** [comment]
This has already been fixed in the latest builds as discussed in bug https://github.com/NuGet/Home/issues/4480

Refer to comment https://github.com/NuGet/Home/issues/4480#issuecomment-277122087 to get the workaround
