### ISSUE TITLE
Restore warnings name the solution file, not the project, that causes them

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4498]
Using dotnet-CLI 1.0.0-rc4-004757

When restoring a solution on command line, it is difficult to know which project is producing downgrade warnings. MSBuild shows the name of the solution, not the csproj.

Example:
https://github.com/aspnet/Entropy has dozens of projects. Restoring produces this warning:

> C:\dotnet\sdk\1.0.0-rc4-004757\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 1.6.2-beta-24913-01 to 1.6.1 \r [C:\dev\Universe\Entropy\Entropy.sln]

It's impossible to tell from command output which project is causing this, and with a large solution it took considerable time to hunt it down....especially considering that it was a transitive reference conflicting with an implicitly defined reference. :tear:

**Comment by nkolev92** [comment]
This has been fixed with coded warnings.
