### ISSUE TITLE
[Test Failure][Localization][CHS]String ‘Skip applying binding redirects’ is localized twice in the Package Manager Settings window

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4506]
**NuGet Version:** Dev 2265 VS15 Localized NuGet Client Vsix
**VS Version:** D15Rel 26203.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select CHS through ‘Tools -> Options -> International Settings’.
2.  Create a new C# Console Application via VS.
3.  Right-click on the project and click ‘Manage NuGet Packages…’.
4.  Click the settings button on the right-top of PM UI (or click Tools->**Package Manager Settings**).
5.  Click the **‘General’** tab.

**Expected Result:**
String **‘Skip applying binding redirects’** is localized correctly.

**Actual Result:**
String **‘Skip applying binding redirects’** is localized **twice** as below screenshot.
![chs](https://cloud.githubusercontent.com/assets/20632625/22618373/601bdfb6-eb15-11e6-81a6-d2763241ce3f.png)

**Note:**
It just repro in CHS, doesn’t repro for other languages.

**Comment by mishra14** [comment]
The translated string seems to contain two copies of the translation.

**Comment by mishra14** [comment]
Validated as fixed on wsr-tc build #1779.

**Comment by v-luzh** [comment]
Fixed on D15Rel 26213.00 (all languages) + VS.Redist.NuGet VS15.4.0.170213.1779.nupkg as below.
![4506fixed](https://cloud.githubusercontent.com/assets/20632625/22917693/4284563c-f2c1-11e6-8d98-7a6af00ab502.PNG)
