### ISSUE TITLE
Intended behavior for nuget.exe restore command - not restoring individual packages?

### ISSUE THREAD

**Issue by diegohb** [NuGet/Home#451]
Running nuget.exe restore against my solution file will not download and restore a single nuget package. It will only restore the entire packages folder if it is missing. So in my example below, if I delete nugetpackage1 directory and run restore, it doesn't restore it and it tells me all packages are installed. But if i delete the lib directory entirely and run restore, then it will recreate the lib directory and restore the nugetpackages accordingly.

I have always assumed it would restore each individual package based on existence of the package root directory (within the packages folder). What is the intended behavior?

My Configuration:
I'm setting up a blank solution with a class project (c# net45) and I've enabled package-restore. I have changed the targets file to set restorepackage = true and requirerestoreconsent = false. I also modified config to change default path of packages folder. nuget.exe in .nuget folder is version 2.8.50926.602.

My Directory Structure:
-*nuget.config*
-src
--mysolution.sln
--.nuget
----nuget.config
----nuget.targets
----nuget.exe
--project1
----project1.csproj
----packages.config
-lib
--nugetpackage1
--nugetpackage2
--repositories.config

**root nuget.config:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <!-- ref: https://docs.nuget.org/consume/nuget-config-file -->
  <packageRestore>
    <!-- Allow NuGet to download missing packages -->
    <!-- Note - potentially will only download missing packages if the entire packages location is missing.
		see https://github.com/NuGet/Home/issues/451 -->
    <add key="enabled" value="True" />
    <!-- Automatically check for missing packages during build in Visual Studio -->
    <add key="automatic" value="True" />
  </packageRestore>
  <config>
	<!-- override default packages directory -->
	<!-- Note - this location will be ignored in scm -->
    <add key="repositoryPath" value="lib" />
  </config>
</configuration>
```

ref: https://docs.nuget.org/consume/command-line-reference#user-content-restore-command

**Comment by emgarten** [comment]
It looks like you have a custom packages folder instead of the standard Packages folder. Can you provide the rest of the details on how you have this set up?

**Comment by diegohb** [comment]
I've updated the description to include the config file used at the root.

**Comment by bhuvak** [comment]
@diegohb, I am not able to repro this using the latest verison of nuget.exe ( 2.8.60318.667). I tried deleting both packages that are direct dependency and indirect dependency and they get restored properly.
Is it a consistent repro for you ? Can you try with the latest version of nuget.exe and see if it works ?

**Comment by bhuvak** [comment]
Closing this one as it doesn't repro on my end. Let me know if you still hit it.
