### ISSUE TITLE
1.psmdcp file date modified year 2038

### ISSUE THREAD

**Issue by acomarce** [NuGet/Home#4510]
When running NuGet pack with a nuspec file 1.psmdcp is created with a modified date of Jan 23 2038, and when uploading to the NuGet webiste the following error ocures: "The package is invalid and cannot be uploaded. One or more files, such as '.rels' have a date in the future."

Packet size is 13MB with some libs inside, when libs removed 50KB error does not occur.

NuGet product used: NuGet for ubuntu from repo

NuGet version: 2.8.7.0

OS version Ubuntu 16.04 x64

**Comment by emgarten** [comment]
@acomarce use the latest version of NuGet from http://dist.nuget.org/index.html

**Comment by acomarce** [comment]
@emgarten Which one works on Ubuntu? and ideally one that I don't have to compile from source as I got this version from the repo precompiled :)

**Comment by emgarten** [comment]
@acomarce take a look at using ``dotnet.exe pack`` using the latest build for ubuntu 16.04 from https://github.com/dotnet/cli

**Comment by rrelyea** [comment]
@acomarce - please follow up on @emgarten's request.
