### ISSUE TITLE
netstandard library packaged twice, and/or fails with access violation

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4511]
Build: d15rel 26203.0

When I build a new netstandard library with `<GeneratePackageOnBuild>True</GeneratePackageOnBuild>` set, building produces the message that it packed twice when I just Build Solution in VS.

```
1>------ Build started: Project: PCLCommandBase, Configuration: Debug Any CPU ------
1>PCLCommandBase -> C:\git\PCLCommandBase\src\PCLCommandBase\bin\Debug\netstandard1.0\PCLCommandBase.dll
1>Successfully created package 'C:\git\PCLCommandBase\src\PCLCommandBase\bin\Debug\PCLCommandBase.0.3.0.nupkg'.
1>Successfully created package 'C:\git\PCLCommandBase\src\PCLCommandBase\bin\Debug\PCLCommandBase.0.3.0.nupkg'.
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
```

[Detailed logs from command line, where the duplicate pack steps collided with each other in an access violation](https://github.com/NuGet/Home/files/753695/msbuild.zip). I couldn't even get it to build from the command line once due to this. Note I can delete the nupkg file from disk freely between builds, proving the access violation is just within the build itself.

Actual repro project:
https://github.com/AArnott/PCLCommandBase
commit: c21f38eddeeafebdf470eb2cffe901d7a7394c4e

**Comment by AArnott** [comment]
Ooh, after removing the `GeneratePackageOnBuild` property from the project, I was able to reproduce the twice pack from the command line when using the `/t:pack` parameter:

`msbuild /flp:verbosity=detailed /fl  /t:pack`
[Detailed build log](https://github.com/NuGet/Home/files/753703/msbuild.zip)

**Comment by rohit21agrawal** [comment]
this has been fixed now via https://github.com/NuGet/NuGet.Client/pull/1148

**Comment by AArnott** [comment]
@rohit21agrawal which build of d15rel can I expect this fix to be in?

**Comment by rohit21agrawal** [comment]
@AArnott sending you details via internal email
