### ISSUE TITLE
hand copied msbuild v15 to a directory, nuget couldn't find it.

### ISSUE THREAD

**Issue by watashiSHUN** [NuGet/Home#4516]
## Details about Problem
When the path to my msbuild15 is `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Msbuild.exe` `nuget restore` is able to locate it, but when I moved it to `C:\Program Files (x86)\MSBuild\15.0\Bin\Msbuild.exe`, `nuget restore` went for msbuild14 instead (which is under `C:\Program Files (x86)\MSBuild\14.0\Bin\Msbuild.exe` )

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
`NuGet.exe`

NuGet version (x.x.x.xxx):
`NuGet Version: 4.0.0.2268`
dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

> D:\home\site\repository>"C:\Program Files (x86)\MSBuild\15.0\Bin\Msbuild.exe" --version
> Microsoft (R) Build Engine version 15.1.523.56541
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> MSBUILD : error MSB1001: Unknown switch.
> Switch: --version
> 
> For switch syntax, type "MSBuild /help"
> 
> D:\home\site\repository>"C:\Program Files (x86)\NuGet.exe" restore
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
> Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.

## Other suggested things
I was able to make it work by using `-MSBuildPath`, I don't know how nuget looks for the path to Msbuild, but I think if it couldn't find vs2017, it should consider the latest msbuild in folder "C:\Program Files (x86)\MSBuild" ?

**Comment by emgarten** [comment]
> but when I moved it to C:\Program Files (x86)\MSBuild\15.0\Bin\Msbuild.exe

What steps did you take to move this? Did you cut/paste the folder, or did you use the installer?

**Comment by watashiSHUN** [comment]
cut and paste

**Comment by rrelyea** [comment]
@watashiSHUN - sounds like that is by design. We cannot find msbuild that you copy to other locations. We work when you give us an explicit path.
Sounds like you should be using an installer. Is there one you can use for msbuild? /cc @rainersigwald

**Comment by rainersigwald** [comment]
Yes, MSBuild should be installed through the VS or the [Build Tools](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017-rc) installer. That sets up the right machine state for NuGet.exe to locate it.

**Comment by tjaart** [comment]
I am unable to use the installer. The installer runs at 100% cpu usage on my windows server 2012 build server and is unusable. Consequently Nuget is picking the wrong MS build tools version (14) and my builds are failing. Can anyone tell me how I can force nuget to use MSBuild 15?

**Comment by watashiSHUN** [comment]
@tjaart  you can use the command line option `-MSBuildPath` ([here's](https://github.com/NuGet/docs.microsoft.com-nuget/blob/live/docs/Tools/nuget-exe-CLI-Reference.md#usage-11) the nuget doc)
that was the easy way, and there's a **hard** way...
nuget use's [willowAPI](https://www.nuget.org/packages/Microsoft.VisualStudio.Setup.Configuration.Interop/) to **automatically** discover available msbuild installed, you can research about how this library is used, and hack it (the key is to register your COM sever)

**Comment by rokx** [comment]
You cannot install MS Build Tool 2017 on Window Server 2012 (not R2). So this workaround is needed.
