### ISSUE TITLE
Nested references regression in 3.5 with nuget.exe Restore?

### ISSUE THREAD

**Issue by KrupaMoliya** [NuGet/Home#4518]
## Details about Problem
NuGet version (x.x.x.xxx):
3.5.1520, 
3.5.1938, 
3.5.1996

**Worked before? If so, with which NuGet version:**
Yes working in 3.4.4-rtm-1321

**Issue in Restore command at 3rd level dependency.**
I have 3 Project, all are in same solution.
"ClassLibrary1" Which is has reference of LightInject. 
"ClassLibrary2" Which is has reference of ClassLibrary1(nuget package) & NewtonsoftJson. 
"ClassLibrary3" Which is has reference of ClassLibrary2(nuget package).

Rebuild ClassLibrary3 with nuget 3.5: It restores ClassLibrary2, NewtonsoftJson & LightInject package
Rebuild ClassLibrary3 with nuget 3.4: It restores ClassLibrary2, ClassLibrary1, NewtonsoftJson & LightInject package

**Surprise:** Restore command downloads LightInject but is not downloading ClassLibrary1

Restore Command:

nuget.3.5.0.1938.exe restore "D:\Git\ClassLibrary3\ClassLibrary3.csproj" -source "http://nuget.local.com/v3/Internal/nuget/;http://nuget.local.com/v3/External/nuget/" -nocache -NonInteractive -RequireConsent -verbosity detailed

I have tried 3 different version for 3.5 but all has same behavior.

In 3.4.4-rtm It is working fine and restoring all the dependency. 
Reason to move on 3.5: 3.4.4 has a major issue in Pack command. It creates package without dependency.

Here i have added detailed logs of nuget restore command and attached project.json of both restore command with 3.4 and 3.5 version.

### Verbose Logs
Logs of restore command in 3.5
NuGet Version: 3.5.0.1938
MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to usea specific
 version of MSBuild.
Restoring NuGet packages...
To prevent NuGet from downloading packages during build, open the Visual Studio
Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to do
wnload missing packages'.
Running restore with 4 concurrent jobs.
Reading project file D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj.
Restoring packages for D:\Git\automation\ClassLibrary3\project.json...
Restoring packages for .NETFramework,Version=v4.6...
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary2'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary2'
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary2' 5ms
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary2' 21ms
  GET http://nuget.local.com/v3/Internal/api/v2/package/classlibrary2/2.0.0
  OK http://nuget.local.com/v3/Internal/api/v2/package/classlibrary2/2.0.0 4ms
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_LightInject'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_LightInject'
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32'
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_LightInject' 6ms
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_LightInject' 8ms
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32' 9ms
  GET http://nuget.local.com/v3/External/api/v2/package/ex_lightinject/4.0.2
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32' 11ms
  OK http://nuget.local.com/v3/External/api/v2/package/ex_lightinject/4.0.2 3ms
  GET http://nuget.local.com/v3/External/api/v2/package/ex_newtonsoftjson_32/9.0.1
  OK http://nuget.local.com/v3/External/api/v2/package/ex_newtonsoftjson_32/9.0.1 4ms
Resolving conflicts for .NETFramework,Version=v4.6...
Acquiring lock for the installation of Ex_LightInject 4.0.2
Acquired lock for the installation of Ex_LightInject 4.0.2
Installing Ex_LightInject 4.0.2.
Acquiring lock for the installation of Ex_NewtonsoftJson_32 9.0.1
Acquired lock for the installation of Ex_NewtonsoftJson_32 9.0.1
Installing Ex_NewtonsoftJson_32 9.0.1.
Acquiring lock for the installation of ClassLibrary2 2.0.0
Acquired lock for the installation of ClassLibrary2 2.0.0
Installing ClassLibrary2 2.0.0.
Completed installation of ClassLibrary2 2.0.0
Completed installation of Ex_LightInject 4.0.2
Completed installation of Ex_NewtonsoftJson_32 9.0.1
Scanning packages for runtime.json files...
Restoring packages for .NETFramework,Version=v4.6 (win)...
Resolving conflicts for .NETFramework,Version=v4.6 (win)...
Restoring packages for .NETFramework,Version=v4.6 (win-x86)...
Resolving conflicts for .NETFramework,Version=v4.6 (win-x86)...
Checking compatibility of packages on .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary1 1.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6.
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6.

All packages and projects are compatible with .NETFramework,Version=v4.6.
Checking compatibility of packages on .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary1 1.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6 (win).
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6(win).
All packages and projects are compatible with .NETFramework,Version=v4.6 (win).s
Checking compatibility of packages on .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary1 1.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6(win-x86).
All packages and projects are compatible with .NETFramework,Version=v4.6 (win-x86).
Committing restore...
Writing lock file to disk. Path: D:\Git\automation\ClassLibrary3\project.lock.js
on
D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj
Restore completed in 673ms.

NuGet Config files used:
    C:\Users\Krupa.Moliya\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    http://nuget.local.com/v3/Internal/nuget/
    http://nuget.local.com/v3/External/nuget/

Installed:
    3 package(s) to D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj

**Logs of restore command in 3.4**

MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'. Use option -MSBuildVersion to force nuget to use a specific
 version of MSBuild.
Restoring NuGet packages...
To prevent NuGet from downloading packages during build, open the Visual Studio
Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to do
wnload missing packages'.
Running restore with 4 concurrent jobs.
Reading project file D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj.
Restoring packages for D:\Git\automation\ClassLibrary3\project.json...
Restoring packages for .NETFramework,Version=v4.6...
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary2'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary2'
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary2' 6ms
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary2' 16ms
  GET http://nuget.local.com/v3/Internal/api/v2/package/classlibrary2/2.0.0
  OK http://nuget.local.com/v3/Internal/api/v2/package/classlibrary2/2.0.0 6ms
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary1'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary1'
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32'
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32'
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='ClassLibrary1' 6ms
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='ClassLibrary1' 9ms
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32' 11ms
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_NewtonsoftJson_32' 10ms
  GET http://nuget.local.com/v3/Internal/api/v2/package/classlibrary1/2.0.0
  OK http://nuget.local.com/v3/Internal/api/v2/package/classlibrary1/2.0.0 6ms
  GET http://nuget.local.com/v3/External/api/v2/package/ex_newtonsoftjson_32/9.0.1
  GET http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_LightInject'
  OK http://nuget.local.com/v3/External/api/v2/package/ex_newtonsoftjson_32/9.0.1 12ms
  GET http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_LightInject'
  OK http://nuget.local.com/v3/Internal/nuget/FindPackagesById()?id='Ex_LightInject' 11ms
  OK http://nuget.local.com/v3/External/nuget/FindPackagesById()?id='Ex_LightInject' 10ms
  GET http://nuget.local.com/v3/External/api/v2/package/ex_lightinject/4.0.2
  OK http://nuget.local.com/v3/External/api/v2/package/ex_lightinject/4.0.2 4ms
Resolving conflicts for .NETFramework,Version=v4.6...
Acquiring lock for the installation of Ex_LightInject 4.0.2
Acquired lock for the installation of Ex_LightInject 4.0.2
Installing Ex_LightInject 4.0.2.
Acquiring lock for the installation of Ex_NewtonsoftJson_32 9.0.1
Acquired lock for the installation of Ex_NewtonsoftJson_32 9.0.1
Installing Ex_NewtonsoftJson_32 9.0.1.
Acquiring lock for the installation of ClassLibrary1 2.0.0
Acquired lock for the installation of ClassLibrary1 2.0.0
Installing ClassLibrary1 2.0.0.
Acquiring lock for the installation of ClassLibrary2 2.0.0
Acquired lock for the installation of ClassLibrary2 2.0.0
Installing ClassLibrary2 2.0.0.
Completed installation of ClassLibrary1 2.0.0
Completed installation of ClassLibrary2 2.0.0
Completed installation of Ex_LightInject 4.0.2
Completed installation of Ex_NewtonsoftJson_32 9.0.1
Scanning packages for runtime.json files...
Restoring packages for .NETFramework,Version=v4.6 (win)...
Resolving conflicts for .NETFramework,Version=v4.6 (win)...
Restoring packages for .NETFramework,Version=v4.6 (win-x86)...
Resolving conflicts for .NETFramework,Version=v4.6 (win-x86)...
Checking compatibility of packages on .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for ClassLibrary1 2.0.0 with .NETFramework,Version=v4.6.
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6.
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6.

All packages are compatible with .NETFramework,Version=v4.6.
Checking compatibility of packages on .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for ClassLibrary1 2.0.0 with .NETFramework,Version=v4.6 (win).
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6 (win).
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6(win).
All packages are compatible with .NETFramework,Version=v4.6 (win).
Checking compatibility of packages on .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary3 1.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary2 2.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for ClassLibrary1 2.0.0 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for Ex_NewtonsoftJson_32 9.0.1 with .NETFramework,Version=v4.6 (win-x86).
Checking compatibility for Ex_LightInject 4.0.2 with .NETFramework,Version=v4.6(win-x86).
All packages are compatible with .NETFramework,Version=v4.6 (win-x86).
Committing restore...
Writing lock file to disk. Path: D:\Git\automation\ClassLibrary3\project.lock.js
on
D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj
Restore completed in 2733ms.

NuGet Config files used:
    C:\Users\Krupa.Moliya\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    http://nuget.local.com/v3/Internal/nuget/
    http://nuget.local.com/v3/External/nuget/

Installed:
    4 package(s) to D:\Git\automation\ClassLibrary3\ClassLibrary3.csproj

[project.lock.zip](https://github.com/NuGet/Home/files/757110/project.lock.zip)

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
