### ISSUE TITLE
Package Restore for Prerelease Nuget Version

### ISSUE THREAD

**Issue by bhawnablogs** [NuGet/Home#4520]
Hi,
I have question regarding alert for Nuget Package Update
I have released 5.0.4 Version. I know my packages would get restored automatically when I release 5.0.5.
But what if
1. I have released 5.0.6-alpha1
2. I have released 5.1.0
For me, in both the cases it's not getting updated. It is still pointing to 5.0.5. 
Is this how Nuget behaves or Am I missing something or I need to update manually.

Please help!!

**Comment by rrelyea** [comment]
Can you be more clear with what the user is doing, in what kind of project.
In addition with what you are doing with publishing new packages.
Then spell out what you'd expect and what you see. Then we'll try to help clear it up.
