### ISSUE TITLE
NuGet restore fails to restore dependencies in project.json when there are PackageRefs in other projects

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#4523]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS

NuGet version (x.x.x.xxx): 4.0

VS version (if appropriate): 26206.0

OS version (i.e. win10 v1607 (14393.321)): 14393.693

Worked before? If so, with which NuGet version: No - using package refs

## Detailed repro steps so we can see the same problem

I have a project that uses the new csproj for 4 of the 5 projects. The 5th one uses project.json as I can't get PackageRefs to work correctly (that's tracked here: https://github.com/dotnet/roslyn-project-system/issues/1121). I've tried a few configurations:

1. Restore from command line works and things build fine. ie msbuild /t:restore;build works as expected

2. Load in VS (from a clean state) and have automatic package restore enabled. None of the libraries in the project.json are available

3. Clean the repo, restore on command line with `msbuild /t:restore` and load in VS with automatic package restore disabled. This will compile fine.

This project is an internal project that we can't share externally, but I can share any logs needed.

**Comment by emgarten** [comment]
@twsouthwick can you create a simple solution that repros this? Or describe the project hierarchy.

Are you able to install a package into the project.json project using the NuGet UI? Does it show up in the project.json file?

**Comment by twsouthwick** [comment]
This may be another manifestation of #4316. The project with project.json is compiling for x86. Although it is through the flag of prefer-32bit being checked, the project.json still has the win-x86 runtime identifier.

**Comment by twsouthwick** [comment]
Turns out this was due to importing a `.targets` file that had a `PackageReference` node. This node was within a conditional `ItemGroup`, but it was apparently not being evaluated with the condition. After switching it to a `choose/when` block, it works as expected.

**Before:**
```xml
<ItemGroup Condition="'$(IncludeAnalyzers)' == 'true'">
  <PackageReference Include="StyleCop.Analyzers" Version="1.0.0" />
</ItemGroup>
```

**After:**
```xml
<Choose>
  <When Condition="'$(IncludeAnalyzers)' == 'true'">
    <ItemGroup>
      <PackageReference Include="StyleCop.Analyzers" Version="1.0.0" />
    </ItemGroup>
  </When>
</Choose>
```

The `IncludeAnalyzers` property is set in the project with the project.json since `PackageReference` doesn't mix with `project.json` too well. This work around got the restore in VS and commandline both working as expected.

@davkean Do you know if this is expected behavior?

**Comment by emgarten** [comment]
I tracked this down with @twsouthwick the project.json project contained a PackageReference that should have been excluded by a condition. Visual Studio seems to skip the conditions in some scenarios. Changing this to a choose/when solved the issue and kept the project from reporting PackageReferences to NuGet.

**Comment by davkean** [comment]
File a bug over on project system.

**Comment by twsouthwick** [comment]
Done - see https://github.com/dotnet/roslyn-project-system/issues/1542
