### ISSUE TITLE
Rebuilding a project with multiple targets does not produce a NuGet package

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4527]
*Rebuild* the following project inside VS:

``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

**Expected:** Project to produce a nupkg.
**Actual:** Project does not produce a nupkg

**Note:** If you just build, it does appear to build it.

**Comment by davkean** [comment]
Found via https://twitter.com/roryprimrose/status/829141692036980737, //cc  @roryprimrose

**Comment by rohit21agrawal** [comment]
closing in favor of : https://github.com/NuGet/Home/issues/4475
