### ISSUE TITLE
A question about LibraryDependencyTypeFlags

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#4529]
In the [LibraryDependencyTypeFlag](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.LibraryModel/LibraryDependencyTypeFlag.cs) class, we have the following declarations of 9 flags:
```cs
public static readonly LibraryDependencyTypeFlag MainReference = Declare("MainReference");
public static readonly LibraryDependencyTypeFlag MainSource = Declare("MainSource");
public static readonly LibraryDependencyTypeFlag MainExport = Declare("MainExport");
public static readonly LibraryDependencyTypeFlag PreprocessReference = Declare("PreprocessReference");
public static readonly LibraryDependencyTypeFlag SharedFramework = Declare("SharedFramework");

public static readonly LibraryDependencyTypeFlag RuntimeComponent = Declare("RuntimeComponent");
public static readonly LibraryDependencyTypeFlag DevComponent = Declare("DevComponent");
public static readonly LibraryDependencyTypeFlag PreprocessComponent = Declare("PreprocessComponent");
public static readonly LibraryDependencyTypeFlag BecomesNupkgDependency = Declare("BecomesNupkgDependency");
```
However, in the [LibraryDependencyTypeKeyword](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.LibraryModel/LibraryDependencyTypeKeyword.cs#L101) class we declare only 8 of them:
```cs
DeclareOnOff("MainReference", LibraryDependencyTypeFlag.MainReference, emptyFlags);
DeclareOnOff("MainSource", LibraryDependencyTypeFlag.MainSource, emptyFlags);
DeclareOnOff("MainExport", LibraryDependencyTypeFlag.MainExport, emptyFlags);
DeclareOnOff("PreprocessReference", LibraryDependencyTypeFlag.PreprocessReference, emptyFlags);

DeclareOnOff("RuntimeComponent", LibraryDependencyTypeFlag.RuntimeComponent, emptyFlags);
DeclareOnOff("DevComponent", LibraryDependencyTypeFlag.DevComponent, emptyFlags);
DeclareOnOff("PreprocessComponent", LibraryDependencyTypeFlag.PreprocessComponent, emptyFlags);
DeclareOnOff("BecomesNupkgDependency", LibraryDependencyTypeFlag.BecomesNupkgDependency, emptyFlags);
```
Could you please tell me why we skip `SharedFramework ` here? Is it a bug of a feature?

**Comment by AndreyAkinshin** [comment]
Any updates on this? It looks like a bug because UWP support doesn't work in Rider without the following dirty hack:
```cs
var libraryDependencyTypeKeyword = typeof(LibraryDependencyTypeKeyword);
var declareOnOffMethod = libraryDependencyTypeKeyword.GetMethod("DeclareOnOff", BindingFlags.NonPublic | BindingFlags.Static);
var emptyFlags = Enumerable.Empty<LibraryDependencyTypeFlag>();
declareOnOffMethod.Invoke(null, new object[] {"SharedFramework", LibraryDependencyTypeFlag.SharedFramework, emptyFlags});
```
I will be happy to make a PR if you confirm that it's ok to add the `SharedFramework` declaration.

**Comment by emgarten** [comment]
How is Rider using these flags and how is it broken?

Looking through the NuGet code these aren't really used, I see just one mention of SharedFramework in regards to pack.

**Comment by AndreyAkinshin** [comment]
@emgarten, it threw an exception. If it matters, I can check it and paste the full exception stacktrace.
However, the most important thing is why `SharedFramework` is skipped here? Will it be ok to add an additional `DeclareOnOff` in `LibraryDependencyTypeKeyword`?

**Comment by emgarten** [comment]
My current thinking is that most of these flags should be deleted since they aren't used. Restore isn't using it that I see unless I'm missing something.

The stack trace would help. I'm not sure why this flag is skipped, but I'm also not sure how this could impact anything.

**Comment by AndreyAkinshin** [comment]
Here is the original Rider issue: https://youtrack.jetbrains.com/issue/RIDER-3875
There are several different stack traces from different people.

**Comment by emgarten** [comment]
Thanks, that helps. Yes it looks like this flag should be added. A PR would be great.

SharedFramework here refers to the CLI assemblies shared by portable NETCoreApp projects, dependencies were set to type=platform and build read that, not nuget. That has seen been deprecated and this can no longer be set on PackageReference elements. So it seems incorrect if Rider is using this flag for UWP apps.

**Comment by AndreyAkinshin** [comment]
> A PR would be great.

Ok, will do it soon.

> SharedFramework here refers to the CLI assemblies shared by portable NETCoreApp projects, dependencies were set to type=platform and build read that, not nuget. That has seen been deprecated and this can no longer be set on PackageReference elements. So it seems incorrect if Rider is using this flag for UWP apps.

Thank you very much for the info. The original issue was reported in December 2016. I'm not completely sure that the problem is still here, but I don't want to remove my super hack without the SharedFramework fix in NuGet. I will investigate how UWP works now.

**Comment by AndreyAkinshin** [comment]
@emgarten https://github.com/NuGet/NuGet.Client/pull/1620
