### ISSUE TITLE
Nuget native library package creation - What are the current activities

### ISSUE THREAD

**Issue by MarkusWild** [NuGet/Home#453]
Hi, 

 we are using Nuget in our Company for C# Projects on TFS and it is a great Tool for us.

 Now we are going to migrate our C++ Libraries from ClearCase to TFS and we want to use Nuget for those Projects too. 

 I could use CoApp to create the Native Packages. But I am not sure if that is the actual way to do it -
cause what I read at the CoApp Thread by Garrett Serack  makes me wonder:

 You're talking about library package creation, and that'll be the last thing in CoApp -- I'm working with the NuGet team alot on mainlining all the features of CoApp-built native packages (believe it or not, we're going to use this internally for building windows too!). 
 Once they've implemented the infrastructure in NuGet itself, I'll make sure there is a zero-effort conversion available. 
 For the most part, they are following the patterns that I set down, with a few improvements to support some of the Building Windows Itself cases.. 

 My Question: 

 I could not find any hints at nugget.org about this activities. Could you please give me more clarity what efforts are going on in this subject? 
 Is there a roadmap for integrating CoApps native Library package creation in nuget? Some official Hints at the nuget Homepage would be very helpful.
By the way - the nuget move from codeplex to github makes it difficult to find the place where to drop questions. It would be gread if the disussion link at nuget.org could be changed.

 Thanks in advance.

**Comment by emgarten** [comment]
There are no current activities around CoApp for NuGet.

@stgates may have more information on this.
