### ISSUE TITLE
Package-delivered props files ignored when MSBuild.exe is run from outside a Developer Command Prompt

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#4530]
This was originally reported by @iskiselev as https://github.com/Microsoft/msbuild/issues/1678. The root cause of the issue is an order-of-MSBuild-imports thing, but it could be avoided with a NuGet change and affects primarily NuGet users so I'm filing a bug here too.

## Details about Problem

NuGet product used: Visual Studio 2017

VS version: 15.0.26206.0

Worked before? If so, with which NuGet version: Yes, with Visual Studio 2015

## Detailed repro steps

1. Reference a NuGet package that has a .props file.
1. Restore.
2. Invoke `MSBuild.exe` from a command prompt that has *not* run any of the VS-environment setting scripts.
3. Observe that the package's .props file is not imported.
2. Invoke `MSBuild.exe` from a "Developer Command Prompt for VS 2017 RC".
1. Observe that the package's .props file is imported as expected.

### Sample Project

https://github.com/iskiselev/msbuild_projecJson

**Comment by rrelyea** [comment]
As we work in developer command prompt, and there is a workaround if not - given the severity and the timeframe, moving to post 4.0

**Comment by rainersigwald** [comment]
@rrelyea You can probably close this; MSBuild plans to take a fix that will result in `VisualStudioVersion` being defined all the time: https://github.com/Microsoft/msbuild/pull/2258.

**Comment by emgarten** [comment]
Closing based on @rainersigwald's comment.
