### ISSUE TITLE
Invalid framework version '.0' error when updating a package

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4531]
vsfeedback issue 801862
https://developercommunity.visualstudio.com/content/problem/17885/cant-update-nuget-packages-in-my-solution.html
Looks like Xamarin/UWP project.

Got similar error here: https://github.com/NuGet/Home/issues/4418 (unsure if related)

**Comment by cni13** [comment]
I worked around the problem by recreating the non existent packages.config (also no project.json). I use VS 2017 and after the migration PackageReference in csproj I started getting the issue with packages.config.

**Comment by nkolev92** [comment]
We only have a workaround for VS only. MSBuild still doesn't work. 
The workaround is copying the frameworks from project.json  to a property in the .csproj
(in #4418, it was "dotnet", in the xamarin/uwp-it was uap10.0)

```
<PropertyGroup>
    <NugetTargetFramework>dotnet</NugetTargetFramework>
  </PropertyGroup>
```

Looks like a dup to #4418

**Comment by nkolev92** [comment]
Unfortunately there's no fully functioning workaround we can provide right now without bigger code changes for RTM.
