### ISSUE TITLE
NuGet.exe list from local packages folder does not work with the AllVersion flag

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#4537]
NuGet.exe list does not work with the AllVersions flag:

NuGet version: 4.0.0.2275
From an e-mail:

```
Nuget 4.0 doesn't mix -prerelease and -allversions correct from 'nuget list'.

Nuget.exe FileVersion 4.0.0.2275


\nuget.4.0\NuGet.exe list zjrunner.test.delist -prerelease -allversions -source \\zackrun1\f$\teststore
Zjrunner.Test.Delist 3.0.0-0



Compare to 3.6 (3.5 + one private fix for VisualStudio team done by markosb)

\nuget.3.6\NuGet.exe list zjrunner.test.delist -prerelease -allversions -source \\zackrun1\f$\teststore
Zjrunner.Test.Delist 1.0.0
Zjrunner.Test.Delist 2.0.0
Zjrunner.Test.Delist 3.0.0-0
```

**Comment by nkolev92** [comment]
Initial work pushed in the dev-nkolev92-list branch. 
Need to add tests for corner cases like, highest version package is unlisted.

**Comment by rrelyea** [comment]
let's get off of RTM plate, as we have too many other important things. We'll consider 4.0.1 and 4.0.2 depending on bar, etc...

**Comment by pvandervelde** [comment]
Any chance of getting this fixed? This not working makes it hard to figure out which packages exist in a feed. Now we need to manually iterate through a feed.

**Comment by nkolev92** [comment]
Related to 
NuGet/NuGetGallery#3274
In addition to the known local feed allversions bug nuget.org allversions in particular has a server-side bug as well.

**Comment by eatdrinksleepcode** [comment]
So at this point we are at (at least) _two years_ with this essential command line functionality being completely broken...

**Comment by jnm2** [comment]
Every tool I've written so far that works with NuGet feeds has had to work around this bug.

**Comment by andrewducker** [comment]
Just encountered this myself.  How can I tell what all the packages available are, when the List command only returns the latest versions?

**Comment by ddspectron** [comment]
Thank you @nkolev92.  

Is there any information on when this will be fixed?  It has been open since 8 Feb 2017!  

@rrelyea, are you able to help at all with this?

**Comment by stavvy-akamen** [comment]
upvote

**Comment by JonathanHiggs** [comment]
Still not fixed in the latest release... Originally referenced in #1219 in 2015

**Comment by cbries** [comment]
Running in this today. Need fix as well.

**Comment by Blinchik91** [comment]
Still not fixed....

**Comment by D4N4M8** [comment]
> Still not fixed....

I have the same problem with my local repository

**Comment by erdembayar** [comment]
@aortiz-msft @nkolev92 
Is someone working on it? Currently it's review pipeline. Looks low priority "Priority 3".
