### ISSUE TITLE
VS 2017 generates .nupkg that crashes NuGet Package Explorer

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#4539]
## Details about Problem

NuGet product used: VS UI

NuGet version (x.x.x.xxx): VS 2017 RC4 26205.0 d15rel

dotnet.exe --version (if appropriate): 1.0.0-rc4-004769

VS version (if appropriate): VS 2017 RC4 26205.0 d15rel

OS version (i.e. win10 v1607 (14393.321)): windows 8 6.3 (9600)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. In VS 2017 create a new .NETCore console app
2. In Project properties -> Package, check Generate NuGet package on build
3. Install NuGet Package Explorer from https://github.com/NuGetPackageExplorer/NuGetPackageExplorer
4. Double-click on the .nupkg to open it in NuGet Package Explorer

Expected: .nupkg should open and be viewable
Actual: message box

```
---------------------------
NuGet Package Explorer
---------------------------
The 'exclude' attribute is not declared.
---------------------------
OK   
---------------------------
```

This is because the .nuspec contains these attributes:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>StructuredLogger</id>
    <version>1.0.110</version>
    <authors>StructuredLogger</authors>
    <owners>StructuredLogger</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard1.5">
        <dependency id="Microsoft.Build.Utilities.Core" version="15.1.0-preview-000523-01" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="15.1.0-preview-000523-01" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build" version="15.1.0-preview-000523-01" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="15.1.0-preview-000523-01" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETFramework4.6">
        <dependency id="Microsoft.Build.Utilities.Core" version="14.3.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="14.3.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build" version="14.3.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Framework" version="14.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

I've filed https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/171 against the NuGet Package Explorer, but I need to know the exact spec of why these new attributes are there and where to find documentation about them.

**Comment by rohit21agrawal** [comment]
@KirillOsenkov The spec is here : https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets 

We are working on getting this documented soon.
