### ISSUE TITLE
NuGet adds "less specific" PCL to WinPhone 8.1 app

### ISSUE THREAD

**Issue by onovotny** [NuGet/Home#454]
The Newtonsoft.Json NuGet contains two PCL versions in it:
- portable-net40+sl5+wp80+win8+wpa81
- portable-net45+wp80+win8+wpa81+aspnetcore50

When adding Newtonsoft.Json to a Windows Phone 8.1 project (not SL), Nuget adds a reference to the first version (the net40 compatible one). That version has less functionality than the net45 one (and is incompat with .NET Native)

NuGet should add the highest "more specific" one (the one with net45).

**Comment by onovotny** [comment]
cc @jamesnk

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Packaging@207bf15b81e5ce66398aed40afd2ec26671dd0a9

**Comment by onovotny** [comment]
Thanks for the super-fast turnaround on this!

**Comment by onovotny** [comment]
Question on this:

For xUnit I have a win8 ver and then a portable-win81+wpa81 ver (for universal support). For a Win 8.1 app, NuGet 2.8.x will pick the win8 ver even though there's a higher compat version.

Can this be fixed too?

**Comment by emgarten** [comment]
What are framework options under the lib folder for this package?  Is this a package on nuget.org?

**Comment by onovotny** [comment]
This package is part of xUnit, specifically xunit.core. (I worked with @bradwilson to figure out how to get xunit working for winrt platforms). I noticed that for Win8.1 test projects, adding xunit (hence pulling in xunit.core) made it reference the win8 version of the lib and not the higher 8.1 version that was part of the "universal" package.

You can see an example here in the integration tests project:
https://github.com/xunit/visualstudio.xunit.integration/blob/master/v2_Win81/v2_Win81.csproj

that adds the win8 ver and not the portable-win81+wpa81 version of xunit.core.

**Comment by bradwilson** [comment]
It presumably prefers non-portable to portable, even though the portable version is a better match.

**Comment by emgarten** [comment]
That's correct, NuGet will take the non-portable compatible option first. win81+wpa81 indicates that it is the intersection subset of the APIs for those two frameworks, which means it potentially has a smaller surface area than win8 alone.

**Comment by onovotny** [comment]
I would think that it should pick the non-PCL only if the platform in the PCL is at or below in version.

If a PCL has a higher version of a platform than a non-portable, the PCL should win in that case.
