### ISSUE TITLE
VSFeedback: Provide an easy way (from the UI) to upgrade NuGet packages after retargeting the framework.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4541]
vsfeedback 802550

No contact info, but good idea to consider:
Provide an easy way (from the UI) to upgrade NuGet packages after retargeting the framework.

It should be that just doing a restore after you retarget will get the right assets into your build pipeline.
So likely need to talk to people to better understand what this customer meant.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
