### ISSUE TITLE
NuGet package restore keeps stealing focus in a .net core project

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4543]
Please engage with the customer from VS Feedback 786944 (https://developercommunity.visualstudio.com/content/problem/16748/nuget-package-restore-keeps-stealing-focus-in-a-ne.html)

Filed by internal user: @petermarcu
See @rrelyea for a few email threads about this.

#4542 sounds similar, but was caused by a bad package. We plan to help roslyn-project-system understand why that caused that situation.

**Comment by rrelyea** [comment]
Any outlook?

**Comment by alpaix** [comment]
The problem repro-es consistently in rc3.1 26127.03.d15svc/NuGet 4.0.0.2215.
The issue was resolved with NuGet/NuGet.Client#1138.
The fix was inserted into d15rel starting NuGet 4.0.0.2259.
Validated and confirmed with 26208.0.d15rel.

**Comment by alpaix** [comment]
The same as #4274.
