### ISSUE TITLE
Nuget manager does not respect dependencies in nuspec files

### ISSUE THREAD

**Issue by mide1234** [NuGet/Home#4546]
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

NuGet Package Manager   3.4.4

Let's have a nuget package with following dependencies:
![obrazek](https://cloud.githubusercontent.com/assets/25344432/22786186/c0d9d5ae-eed7-11e6-9536-cc08be744029.png)

See how VS2015 interprets the dependencies:
![obrazek](https://cloud.githubusercontent.com/assets/25344432/22786104/7afa23cc-eed7-11e6-8aa8-fb0370e8f839.png)

Expected: 
Serilog dependency shown in VS is supposed to be > 2.0.0 and not >= 2.0.0 based on nuget documentation.

Am I doing something wrong or is it a bug?

Thanks

**Comment by rohit21agrawal** [comment]
@mide1234 Could you try this with NuGet 3.5.0 VSIX that you can get from : https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by mide1234** [comment]
@rohit21agrawal I tried that with the latest NuGet 3.5.0 as you suggested but the issue persists. Let me know if you need any additional information.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
