### ISSUE TITLE
TemplateWizard needs option to install packages as PackageReferences

### ISSUE THREAD

**Issue by sbanni** [NuGet/Home#4549]
The template wizard for VisualStudio needs an option to install packages as PackageReference if the template does not already contain a PackageReference as NuGet does not recognize it as a PackageReference project.

**Comment by rrelyea** [comment]
Related to #4488 
Ideally, if there is no P.J around, we can make UWP default to PackageRef.
@jainaashish @emgarten

**Comment by rrelyea** [comment]
Putting in 4.0 to keep on radar for now. However, this is 4.0.1 work.
Please either troubleshoot and fix this, or coach @sbanni on how to.

**Comment by rrelyea** [comment]
@sbanni - how is this going?

**Comment by sbanni** [comment]
@rrelyea https://github.com/NuGet/NuGet.Client/pull/1187

**Comment by emgarten** [comment]
Fixed as part of the above PR
