### ISSUE TITLE
[NuGet.CommandLine:#8] Trying to update packages depends on the current version of the package having been restored 

### ISSUE THREAD

**Issue by ChrisMcKee** [NuGet/Home#455]
If I checkout a project and the packages folder is empty.
I then try to update the solutions nuget packages before doing anything else using the console (as the UI version is horrendously slow), using

```
.\.nuget\nuget.exe update .\My.sln -NonInteractive -verbosity detailed
```
It cycles through all of the projects
i.e. 
```
Scanning for projects...
Found 33 projects with a packages.config file. (list of project names)
Looking for installed packages in 'packages'.
Updating 'project1' 
etc
```

Then ends. The only way to make it then update is to restore first, then run then update, which is a bit fucky.
If you run an upgrade you don't really care about the current packages, or the current version, you just want the latest; also if you suffer data loss on a custom nuget server and no longer have the version referenced, you're forced to manually edit the csproj/package.config version numbers to get the system to update.

**Comment by emgarten** [comment]
Package dependency information exists only in the packages, for this reason the packages need to be restored before performing updates. The gesture you are looking for is equivalent to installing the latest version of the original packages installed.

We have some plans to improve this, but it will not be done in NuGet 2.8.x due to the limitations there.

**Comment by ChrisMcKee** [comment]
Hi; wouldnt it make more sense to base package versions on the config rather than the contents of a folder; as far as I'm aware that's how other package managers work.

**Comment by ChrisMcKee** [comment]
Will this be solved in V3?
