### ISSUE TITLE
Nuget timeouts running win7 as VM

### ISSUE THREAD

**Issue by JimSmith99** [NuGet/Home#4550]
Hi

I get nuget timeouts just as  [here:](https://github.com/dotnet/cli/issues/1732)
I have tried disable parallel but that doesn't help.
I use win7as a VM on qnap. I see people talk about disable 'VirtualBox Host-Only Network'  and 'disabled the VirtualBox interface. '
I'm not sure what to do with my settings on the qnap.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet version: 3.5.0
dotnet.exe --version:  1.0.0-preview2-003131
VS version: 2015 update 3
OS version: win 7 (Build 7601: Service pack 1) x64

Reproduce
1. git clone https://github.com/IdentityServer/IdentityServer4.Samples.git
2. Open any solution -> Package restore failed
3. Package manager console -> Update-Package -Reinstall -Safe
4. Loads of errors such as:
log  : Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json'.
log  : The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json' has timed out after 100000ms.

Hope you can help

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/2945

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
