### ISSUE TITLE
Document spec for "Managing dependency package assets"

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#4551]
https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

even though we have RTM'd this feature, this spec was never documented. Nuspec schema documentation also needs to be updated.

CC: @rrelyea @emgarten @karann-msft

**Comment by kraigb** [comment]
@rohit21agrawal Where can I find source material for the necessary docs?

**Comment by karann-msft** [comment]
@kraigb https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

**Comment by karann-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #624](https://github.com/NuGet/docs.microsoft.com-nuget/issues/624) via [**ZenHub**](https://www.zenhub.com/)
