### ISSUE TITLE
add msbuild.runtime package to the repository to make functional tests more modular

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4552]
Currently we depend on the system installed msbuild to run tests. We should make that easier for 3rd party contributors to test code.

**Comment by rohit21agrawal** [comment]
i'd like to this sooner than 4.0.1 as this might unblock some of the testing scenarios that we are unable to test currently. more details?

**Comment by mishra14** [comment]
Discussed offline. Use the package available at: http://www.nuget.org/packages/Microsoft.Build.Runtime/15.1.0-preview-000545-01

**Comment by rohit21agrawal** [comment]
@rrelyea this is exactly what we need to build the testing infrastructure to test UWP scenarios, especially for Pack. 

can we pull this in for 4.0 milestone? It's likely a day or two of work.

**Comment by mishra14** [comment]
Issue moved to [NuGet/Client.Engineering #53](https://github.com/NuGet/Client.Engineering/issues/53) via [**ZenHub**](https://www.zenhub.com/)
