### ISSUE TITLE
NuGetizer can package multiple PackageFile items with identical PackagePath

### ISSUE THREAD

**Issue by memontic-ms** [NuGet/Home#4554]
### Issue
A package can be created containing identical files at the same location in the package. Extracting this .nupkg produces conflicts and is presumably an invalid NuGet package.

### Expected Behavior
NuGetizer should warn of file conflicts and/or only put one distinct file in the .nupkg

### Constraints of Issue
Two or more PackageFile items that have:
- Different source path
- The same PackagePath (destination file name must also be the same)

### Repro
Using NuGet.Build.Packaging version 0.1.186
```
<PackageFile Include="one.txt">
    <PackagePath>build\samename.txt</PackagePath>
</PackageFile>

<!-- Duplicate 1: one.txt == somedir\one.txt -->
<PackageFile Include="somedir\one.txt">
    <PackagePath>build\samename.txt</PackagePath>
</PackageFile>

<!-- Duplicate 2 -->
<PackageFile Include="two.txt">
    <PackagePath>build\samename.txt</PackagePath>
</PackageFile>
```
So then this:
```
projectdir
└── one.txt
└── two.txt
└── somedir
     └── one.txt
```
Gets packaged to be this:
```
somepackage.npkg
└── build
     ├── samename.txt
     ├── samename.txt
     └── samename.txt
```

#### Note
When the source file paths are identical, only one copy of the file makes it into the package. No warning is produced.

**Comment by bbowman** [comment]
@kzu I noticed this as well. It definitely seems like a user error but it can be easy to miss in the automagic packaging that goes on.

**Comment by kzu** [comment]
Should this be turned into a warning or a straight error?

**Comment by bbowman** [comment]
Straight error seems good if it's something that is always user avoidable. I'm only afraid the automatic packaging may encounter this and the recovery from the error may not be obvious. Maybe warning if automatic and error if manual ... would require new metadata in the automatic targets to detect.

**Comment by kzu** [comment]
Fixed with https://github.com/NuGet/NuGet.Build.Packaging/pull/114
