### ISSUE TITLE
High DPI in issues VS2017

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#4556]
I'm running VS 2017 RC in a Parallels VM on OSX. Here's how the UI looks.

![image](https://cloud.githubusercontent.com/assets/95136/22816710/6e33c81e-ef18-11e6-8ef2-90d400479263.png)

**Comment by rohit21agrawal** [comment]
@jainaashish i believe this has already been fixed? 

@davidfowl what build of VS are you on?

**Comment by davidfowl** [comment]
"RC4"

**Comment by rrelyea** [comment]
Dupe of #4439 - currently a 4.0.1 issue.
