### ISSUE TITLE
vsfeedback - VS for Mac project causes restore over and over

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4559]
vsfeedback 803710 - https://developercommunity.visualstudio.com/content/problem/18658/restore-packages-for-net-core-never-ends.html

Opening a project created on Visualstudio for Mac seems to just forever restore nuget packages over and over.... they never restore and it keeps trying on a multi-project solution.   there seems to be no way to stop it either other than just close the project.

**Comment by rrelyea** [comment]
Likely suspect: Not sure if the template for VS for Mac is up to date with changes in VS RC4 or not???
(sent mail to a set of people to see if they have context that will help our investigation)

**Comment by mrward** [comment]
VS for Mac preview 3 should be creating nearly the same projects as VS RC4. Here is the .csproj file for a created .NET Core console project:

    <Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp1.0</TargetFramework>
      </PropertyGroup>

    </Project>

There are some small differences such as the xmlns being added and PackageReferences having a Version element when added from within VS for Mac. I would guess that the xmlns would not be causing the restore to not finish.

**Comment by mrward** [comment]
I ran a quick test. Ceated a .NET Core console project and a .NET Core NetStandard project in VS for Mac. Then opened the solution into VS 2017 RC4. Restore ran and finished.

**Comment by mrward** [comment]
Also tried the empty web project and that restored OK in VS 2017 RC4.

**Comment by mishra14** [comment]
@rrelyea since this does not repro, should we close this?

**Comment by rrelyea** [comment]
@mrward - thanks for trying.
Moving to blocked. Waiting for customer repro that we asked for from vsfeedback.

**Comment by rrelyea** [comment]
Perhaps this was another instance of #4575

**Comment by rrelyea** [comment]
Dupe of #4575
