### ISSUE TITLE
vsfeedback - NuGet restore of Packages.config project fails with RC4. Cannot build .NET Standard Class Library.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4560]
vsfeedback 803478 - https://developercommunity.visualstudio.com/content/problem/18548/nuget-restore-fails-cannot-build-net-standard-clas-1.html
See photo/etc in feedback item.

**Comment by zhili1208** [comment]
this is dupe of https://github.com/NuGet/Home/issues/4533
