### ISSUE TITLE
vsfeedback - PackageReference fails to install developmentDependency correctly (via install.ps1)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4561]
vsfeedback 803549 -- https://developercommunity.visualstudio.com/content/problem/18590/packagereference-fails-to-install-developmentdepen.html

Install CreateNewNuGetPackageFromProjectAfterEachBuild using PackageReference the build script fails to be added

**Comment by rrelyea** [comment]
Install.ps1 is not runnable in packages that are installed with one of NuGet's transitive project styles.
Packages.config -- does run install.ps1.
Project.json and PackageReference do not run install.ps1.

**Comment by rrelyea** [comment]
Need good positioning on move to transitive nuget world and what changes. please work with me and team

**Comment by roryprimrose** [comment]
Is this related to https://github.com/GitTools/GitVersion/issues/1188 ?
