### ISSUE TITLE
vsfeedback: NRE when trying to restore a large project in VS

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4568]
see internal vsfeedback 789471 -- found using 26202.1

Clone https://github.com/aspnet/Razor repository
Open Razor.sln in VS
Right click Solution -> Restore NuGet Packages

I get the following error:

Error		Error occurred while restoring NuGet packages: Object reference not set to an instance of an object.			0	

Workaround: Run `dotnet restore` from the command line

**Comment by jainaashish** [comment]
Dup# of https://github.com/NuGet/Home/issues/4487 

Fixed with  26206.0.d15rel
