### ISSUE TITLE
vsfeedback: "Error occurred while restoring NuGet packages: File not found" 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4569]
internal vsfeedback 787061 -- using 26201.1

When building "Microsoft.AspNetCore.Sockets.Common.Tests" in the attached ZIP, I get the following error in the Build Output Window: "Error occurred while restoring NuGet packages: File not found". Restoring from the command line (dotnet.exe version: 1.0.0-rc3-004530) does work.

Apologies for the large attachment, I wanted to make sure to capture as much of my project context as possible. 

Found via @anurse

**Comment by zhili1208** [comment]
this is dupe of https://github.com/NuGet/Home/issues/4533
