### ISSUE TITLE
vsfeedback: restore not working with project.json file (due to v1 project.lock.json file)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4570]
internal vsfeedback: 747014

New project was added to our source and the appropriate packages specified in the project.json.  These references do not properly show up in the "References" for the project.  Attempting to open Nuget Manager Console results in an error so I can't perform a manual restore. 

found using 26124.2 build.
internal user is contactable via email.

**Comment by zhili1208** [comment]
I think this is related to project.lock.json v1, talked with internal user, he can't test it now, will test it next week

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
