### ISSUE TITLE
Restore nuget packages failed and retries over and over again

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4575]
- Open the sln file \\mlangfs1\public\Jinuj\TestScenario\RestoreRetriesForEver\MultiTargetting here 

The problem here is  Client project  has a reference to classlibrary which doesn't exists.

**Comment by jinujoseph** [comment]
cc @rrelyea

**Comment by zhili1208** [comment]
@jinujoseph I tried your repro solution, it repros when I open that solution first time, but can't repro it any more after reopen solution, Do you know how to create a solution which can repro this issue?

**Comment by jinujoseph** [comment]
Take a copy of \\mlangfs1\public\Jinuj\TestCases\MultiTargetting\MultiTargetting  to your machine 
Delete the CoreLib and Lib Folder 
your folder structure should look like this 
![image](https://cloud.githubusercontent.com/assets/12449387/22901598/1cad2dce-f1e7-11e6-8a7d-2149c79bc0b4.png)

now open the solution and it should repro

**Comment by rrelyea** [comment]
adding by design -- as the external bug said that this case was caused by using the SDK as a packageref, which is not supported.
