### ISSUE TITLE
VSSolutionManager.GetOrCreateProjectAsync should handle non-projects gracefully

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4576]
*From an internal thread*

``VSSolutionManager.GetOrCreateProjectAsync`` should handle non-projects gracefully.

Looks like internally NuGet tries to create NuGet project for a given EnvDTE.Project (https://github.com/NuGet/NuGet.Client/blob/b89bb5750c475212213e14f750604d2ecaf704ff/src/NuGet.Clients/PackageManagement.VisualStudio/IDE/VSSolutionManager.cs#L1065)
with assumption that this should always succeed and result will be not null. In our case since VsVirtualProjectHierarchy represents project that does not has CPS or MSBuild or any other counterpart GetOrCreateProjectAsync presumably returns null which lead to failure downstream. To me it looks like a missing case in NuGet that should be fixed.

**Comment by zhili1208** [comment]
Same issue here: https://github.com/NuGet/Home/issues/4563

**Comment by emgarten** [comment]
@zhili1208 good catch, let me merge these together!
