### ISSUE TITLE
dotnet Restore (& therefore msbuild /t:restore) skips projects with an explicit solution project dependency

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4578]
Calling "msbuild.exe /t:Restore" on a solution skips a project in my solution.
This project has an explicit project dependency in the solution file.

**Repro**
1. Download https://github.com/aspnet/BuildTools/tree/4ec80c34339019266353e6e557f7ca68c89fbdb3
2. dotnet restore BuildTools.sln

**Expected**
Restores all csproj reference .sln file.

**Actual**
Skips NugetPackageVerifier.csproj
(see restore log here: https://gist.github.com/natemcmaster/016baf3563e369551d8f4c88cf9dcce0)

**Details**
msbuild.exe 15.0.26209.0
dotnet.exe 1.0.0-rc4-004771

*Right click on solution* -> Project Dependencies

![image](https://cloud.githubusercontent.com/assets/2696087/22849832/d7a3ff1a-efb5-11e6-874c-59b370953401.png)

Or see the raw [BuildTools.sln](https://github.com/aspnet/BuildTools/blob/4ec80c34339019266353e6e557f7ca68c89fbdb3/BuildTools.sln#L15-L17)

cc @emgarten

**Comment by emgarten** [comment]
Thanks for the repro @natemcmaster 

Restore reads the solution metaproj for all project references. For this solution I see it puts the reference to NuGetPackageVerifier in an external metaproj file and references it.

```xml
    <ProjectReference Include="C:\src\repros\BuildTools\src\NuGetPackageVerifier\NuGetPackageVerifier.csproj.metaproj">
      <ToolsVersion>15.0</ToolsVersion>
      <SkipNonexistentProjects>Build</SkipNonexistentProjects>
      <AdditionalProperties>Configuration=Debug; Platform=Any CPU</AdditionalProperties>
      <Configuration>Debug</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectReference>
```

I believe restore has had issues with these in the past and ignores them because they don't actually exist when it tries to resolve them.

@rainersigwald what is the best way to get the set of top level projects from a solution file?

Would it work to strip the .metaproj extension from these paths and continue walking them?

**Comment by rainersigwald** [comment]
That's not a _good_ way but I do think it might be the _best_ way.

References are added to the metaproj by [this code](https://github.com/Microsoft/msbuild/blob/99e95d0f55d2af82767ffd8c81dcfdc663092e49/src/Build/Construction/Solution/SolutionProjectGenerator.cs#L762-L767) which only adds either a direct reference or, if there's something special about the project, a reference to its metaproj. Filed https://github.com/Microsoft/msbuild/issues/1694 to consider creating an item with the contents you expect (definitely not for RTW though).

Hopefully no user has a real file on disk ending with `.metaproj` but you might try adding both under an if-exists clause.

**Comment by rrelyea** [comment]
Got another email complaint about this today from an external customer via @Pilchie

**Comment by davkean** [comment]
I also just ran into this: https://github.com/NuGet/Home/issues/4845
