### ISSUE TITLE
Request for configurable names of '\packages' and 'packages.config'

### ISSUE THREAD

**Issue by maettu-this** [NuGet/Home#4580]
## Details about Problem

NuGet Package Manager for VS 2015

## Other suggested things

I request to allow the user to configure the name...
...of the '\packages' folder.
...the 'packages.config' files.

e.g. in my case I'd like to name them...
...'\NuGet.Packages'
...'NuGet.Packages.config'

Rationale:

- My solution's root's folders are named by supplier/application, '\packages' does not fit.
- My solution's root's folders are PascalCased, '\packages' is camelCased.
- More obvious naming that these items are manages by NuGet, not anything else.
- A '\packages' folder may already exist in a solution.

Please allow users to name items according to user specific needs. Thanks.

**Comment by rrelyea** [comment]
Keeping this open in "future-2", but unlikely to address by the we would get to it.

PackageReferences support in VS2017 and later moves away from both artifacts.
Please consider evaluating that approach soon, and giving feedback to ensure that it meets your company's needs.

**Comment by rohit21agrawal** [comment]
If i am understanding correctly, you can already configure your packages folder to be anything you want : 

``` nuget config -set repositoryPath=c:\MyPackagesFolder ```

As far as packages.config is concerned, the only possibility that exists right now is to have it renamed to : 
```packages.<projectName>.config ```

**Comment by maettu-this** [comment]
I understand that I can achieve this at the console, but I'd like to see it configurable in the NuGet Package Manager **within VS 2015**.

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
