### ISSUE TITLE
Inconsistent handling of Version, VersionPrefix, VersionSuffix

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4583]
Microsoft.Net.Sdk has the following behavior:
`<Version Condition=" '$(Version)' == ''>$(VersionPrefix)-$(VersionSuffix)</Version>`

In other words, the version is the concatenation of the prefix and the suffix, but is overridden if set directly.

`Pack`, on the other hand, seems to consider VersionSuffix even if Version is defined directly. 

I'm not sure what behavior is correct, both have some merit, but the behavior must be consistent. Users shouldn't need to dig into SDK + NuGet targets to understand what is going on.

@rohit21agrawal @dsplaisted what do you guys think?

**Comment by rohit21agrawal** [comment]
this has already been fixed by : https://github.com/NuGet/NuGet.Client/pull/1139

```Pack``` doesn't read ```VersionSuffix``` anymore.
The only way to override the ```Version``` is to set the ```PackageVersion```

**Comment by rohit21agrawal** [comment]
@piotrpMSFT in case i misunderstood the issue in your OP, please feel free to reactive this issue.

**Comment by TheRealPiotrP** [comment]
@rohit21agrawal I cannot reopen the issue, but I did see it repro with latest CLI. Unless https://github.com/NuGet/NuGet.Client/pull/1139 only got inserted today, I think we have a problem...

**Comment by rohit21agrawal** [comment]
@piotrpMSFT  how exactly are you repro'ing this?

**Comment by TheRealPiotrP** [comment]
@rohit21agrawal thanks for chatting with me offline. My repro was based on CLI `master` builds which are taking advantage of 2.0.0 preview bits. Your fix is not available there yet, but I just confirmed that this is fixed in 1.0.0.
