### ISSUE TITLE
[Test Failure] Duplicated references show after installing package ‘System.Core’ into C# Console App with PackageReference mode

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4584]
**NuGet Version:** NuGet 4.0.0-RTM-2275
**VS Version:** D15Rel 26210.02
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.	Select **‘PackageReference in project file’** as default package management and check **‘Allow format selection on first package install’** format in NuGet Package Manager setting dialog.
2.	New a Visual C#->Windows Classic Desktop->Console App (.NET Framework) project.
3.	Right-click on the project and click ‘Manage NuGet Packages…’ and go to ‘Browse’ tab.
4.	Install **‘System.Core’** package.
5.	Open reference expander in Solution Explorer window.

**Expected Result:**
No duplicated references show under reference node.

**Actual Result:**
Duplicated references show under reference node as below screenshot. (They are both System.Core.dll)
![duplicatedreference](https://cloud.githubusercontent.com/assets/20632625/22875710/22565a2c-f208-11e6-9934-68a501bffb85.png)
**Note:**
It repro on D15Rel 26210.02+NuGet 4.0.0-RTM-2286.

**Comment by rrelyea** [comment]
Known issue, assigned to project system team (csproj.dll). Tracked by internal bug: 377624

**Comment by jainaashish** [comment]
This is not an issue,` System.core` was already there in the project as assembly reference and then on top of that, you added `System.core` as a NuGet package so it shows both one as assembly reference and another as NuGet package. When you were trying to add this as a package, then ideally you should remove it as assembly reference.
