### ISSUE TITLE
Local Nuget Server package Loading Failed

### ISSUE THREAD

**Issue by MohdIrfanKhan** [NuGet/Home#4585]
Hi,

We are having our own Nuget Server using v2.11.2.0 where we are managing our nuget packages. But
we faced a lot of problem with nuget restore. When I looked into the localserver.cache.bin
file I found only one package was there. On restarting IIS instance and clearing cache it works fine
but after some time it again behaves same in.
Could you please help me in identifying the cause of issue and how to resolve.

**Comment by emgarten** [comment]
@irfspy looks like you are using an older version of NuGet.Server. Try the latest here https://www.nuget.org/packages/NuGet.Server/  and see if this issue still occurs. 

Also, the source is available here for debugging: https://github.com/nuget/nuget.server

**Comment by MohdIrfanKhan** [comment]
Thanks @emgarten!

Earlier we don't have this issue but the system where we have our nuget server also have Jenkins since we have only 8 gb of RAM on that system out of which we allocated 6gb of RAM to Jenkins. Can this be a reason of its failure. Also we are pushing some packages with every build so can this be a reason?

**Comment by emgarten** [comment]
How large are the nupkgs?

What data was being held in the cache? I'm not clear on what was done to fix the issue temporarily.
