### ISSUE TITLE
Unable to open NuGet.Packaging solution in VS2013

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#459]
I'm unable to open the NuGet.Packaging solution in VS2013.

Steps to reproduce:
* Check out *master* branch of https://github.com/NuGet/NuGet.Packaging.git
* Open Packaging.sln
Error messages:
* *This version of Visual Studio is unable to open the following projects.*, followed of a list of all projects in the solution.

I've tried to look through http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment without any hints of what might be wrong.

**Comment by davidfowl** [comment]
It actually requires vs 2014 now

**Comment by forderud** [comment]
Then it would be nice if you could update http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment to prevent confusion.

**Comment by davidfowl** [comment]
Agreed. /cc @yishaigalatzer

**Comment by yishaigalatzer** [comment]
Fair enough good catch.
