### ISSUE TITLE
dotnet restore failure should list the feeds when it fails to find a package.

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4594]
Moved from https://github.com/dotnet/cli/issues/5684 on behalf of @kichalla

------

I was trying to restore packages in a repo when I ran into an error like below:

```
C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771\NuGet.targets(97,5): error : Failed to retrieve information about 'NETStandard.Library' from remote source 'c:\does-not-exist'. [C:\github\configuration\Configuration.sln]
```
I tried to find more information by doing: `dotnet restore -v diag` but this too didn't give any useful information.

I later realized that I had a temporary package source (pointing to a local folder) added a while back via Visual Studio which was being picked by dotnet restore.

It would be nice to print information about the feeds and the configuration files used for the restore information at least when specifying the verbosity flags like `detailed` or `diagnostic`

## Steps to reproduce
- Clone the repo `http://github.com/aspnet/configuration` and `cd configuration`
- Do a `dotnet restore` on any repo which you would have expected to work usually.
- Open Visual Studio and add a package source like `c:\doest-not-exist`
- Do a `dotnet restore -v diag` and this also doesn't give much information as to where its picking up the sources from. 

## Expected  behavior
Show detailed information of the feeds and NuGet.config source files when using the verbosity flags for 'detailed' or 'diagnostic'

## Actual behavior
Error similar to the following:
`C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771\NuGet.targets(97,5): error : Failed to retrieve information about 'NETStandard.Library' from remote source 'c:\does-not-exist'. [C:\github\configuration\Configuration.sln]`

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  d881d45b75

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\AppData\Local\Microsoft\dotnet\sdk\1.0.0-rc4-004771
```

**Comment by emgarten** [comment]
@kichalla a list of all feeds, fallback folders, and nuget.config files used are displayed in a summary when restore completes.  Does this solve your issue?

**Comment by kichalla** [comment]
@emgarten Have you tried the repro steps?

**Comment by emgarten** [comment]
> Have you tried the repro steps?

I've tried the repro steps.

Could you elaborate on:

> Show detailed information of the feeds and NuGet.config source files

What sort of additional information would have helped you solve this issue? Are you looking for a message saying that *c:\does-not-exist* was not found on disk?

**Comment by kichalla** [comment]
> What sort of additional information would have helped you solve this issue? Are you looking for a message saying that c:\does-not-exist was not found on disk?

I was looking for just the regular information that we show in other cases, example:

```
  NuGet Config files used:
      C:\temp\bugrepro\NuGet.Config
      C:\Users\kichalla\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json
      https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
      https://api.nuget.org/v3/index.json
      https://www.myget.org/F/aspnetcidev/api/v2
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
