### ISSUE TITLE
Improve Sign In expirience for VSTS

### ISSUE THREAD

**Issue by DerAlbertCom** [NuGet/Home#4595]
## Details about Problem

NuGet 3.4 and 3.5, Visual Studio 2015 and 2017
Win 10 1607

## Detailed repro steps so we can see the same problem

If you use NuGet against the Visual Studio Team Services NuGet Packages Extension then NuGet for the first time a window will be opened, with the Login over the VSTS SSO. Which is in general not a bad thing 😃.

But you have no clue for what you are entering the Credentials, you only see a Visual Studio login, not even you can see that this is for VSTS.

So i first entered my Microsoft Account for Visual Studio several times, that does not helped because the nuget feed needs by VSTS/Office 365 Credentials. But i was confused. Also i don't explicit restored the packages, i simple opened a ASP.NET Core project. Shortly after that i was asked about the Credentials, with no for what.

I don't know where to put it, so it write this here and the Visual Studio User Voice.

## What should be shown?

Information should be display for what i must enter the credentials. In two Parts
   
* Please Enter your Credentials for the following NuGet Feed
* https://feeadress

**Comment by DerAlbertCom** [comment]
Really?

**Comment by emgarten** [comment]
@DerAlbertCom we appreciate the suggestion. At this time your feature request does not meet the bar, and the team will not be able to work on this foreseeable future. If additional feedback or requests come in for this feature we will re-evaluate this.

We would accept a PR for this.
