### ISSUE TITLE
Remove CPS capability check from LegacyCSProjPackageReference NuGet project system

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4599]
Since CPS based project systems have started moving to VSProject4 implementation so our current not CPS capable check avoids these project systems to use PackageReference as package management format and forced to use Packages.config

Currently it's blocking Xamarin team to use PackageReference.

**Comment by jainaashish** [comment]
Waiting to get good justification from Xamarin team so that we can get this approved from VS shiproom.

**Comment by rrelyea** [comment]
command line restore still respects RestoreProjectStyle, which unblocks @kzu for rtm.

**Comment by kzu** [comment]
It doesn't unblock us, I'm afraid. My question regarding that was for a totally unrelated personal project.

We'll have to go the nasty reflection hacking route until we get it to work in some manner, until this is fixed.

**Comment by jainaashish** [comment]
@kzu unfortunately yes if you need it inside VS until next release. But we're also working on another fix with a partner team to get this property back even in RTM without impacting perf. So if that works out well, then we might be able to unblock you in RTM itself but nothing confirmed as of now.

**Comment by kzu** [comment]
I assume the alternative didn't happen and we'll just have this in 15.1. No prob.

**Comment by bbowman** [comment]
@rrelyea Is this going to hit in 15.1 and do we know if it will work for C++ UWP projects as well? Is there a way I can try this out sooner? Is there a CI drop of the packager manager VSIX?

**Comment by kzu** [comment]
@rrelyea we have users hitting this in 15.1 still. It didn't make it? :(
