### ISSUE TITLE
Installing specific version of package fails if another version of dependency exists in cache

### ISSUE THREAD

**Issue by matt-richardson** [NuGet/Home#460]
Installing a package fails when it has a dependency on a specific version of a component, and an older version of the package exists in the nuget cache.

Steps to reproduce:
1) clear nuget cache
2) `nuget install jquery -version 1.4.1 -source http://nuget.org/api/v2`
3) `nuget install jquery.ui.combined -version 1.11.4 -source http://nuget.org/api/v2`

(the `-source` param does not make a difference here, just left it in to narrow the problem)

Affects version 2.8.60318.667. It appears to be a regression introduced somewhere after 2.5.40416.9020.

Workaround: this can be worked around by using the `-nocache` param.

in PriorityPackageRepository.cs, line 72, in method `FindPackagesById(string packageId)`, it queries the primary repository (the nuget cache) by package name (only), and then only queries the secondary repository (the online feed) if it didn't find anything.

**Comment by matt-richardson** [comment]
A naive fix to this is to change the method to:

````
public IEnumerable<IPackage> FindPackagesById(string packageId)
{
    IEnumerable<IPackage> packages = _primaryRepository.FindPackagesById(packageId);
    packages = packages.Concat(_secondaryRepository.FindPackagesById(packageId));

    return packages.Distinct();
}
```` 
but I suspect that will have ramifications.

**Comment by deepakaravindr** [comment]
//cc @pranavkm

**Comment by AndriySvyryd** [comment]
Fixed by https://nuget.codeplex.com/SourceControl/changeset/82536eb6e7867af4c4c033c91e4729328cf48e0b
