### ISSUE TITLE
Entity Framework tools -- "No executable found matching command 'dotnet-ef'"

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#4600]
_From @tdykstra on February 14, 2017 23:12_

## Steps to reproduce
1. Install RC4 VS 2017
2. Create an ASP.NET Core/ASP.NET Core web project.
3. Add EF tools to .csproj
  ```<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.Dotnet" Version="1.0.0-msbuild3-final" />```
4. In project folder run dotnet restore
5. Try to run EF tools with "dotnet ef" commands.

## Expected  behavior

EF tools run 

## Actual behavior
```
No executable found matching command "dotnet-ef"
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-rc4-004802)

Product Information:
 Version:            1.0.0-rc4-004802
 Commit SHA-1 hash:  2384b5f1a8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004802
```

.csproj contents:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.Dotnet" Version="1.0.0-msbuild3-final" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
  </ItemGroup>

</Project>
```

_Copied from original issue: dotnet/cli#5704_

**Comment by rohit21agrawal** [comment]
_From @piotrpMSFT on February 15, 2017 1:17_

@rohit21agrawal I just repro'd this locally. I don't see any mention of the tool being restored, nor do I see it in the assets.json file...

**Comment by rohit21agrawal** [comment]
@emgarten it seems that the packages are being restored to the .tools folder in the global packages folder, however there is no mention of these packages in the assets.json file. The *.dotnetclitool.json file is not created either as this spec suggests : https://github.com/NuGet/Home/wiki/DotnetCliToolReference-restore

**Comment by emgarten** [comment]
@rohit21agrawal that spec is for a feature which did not go into NuGet 4.0.0.

**Comment by emgarten** [comment]
The assets file is written to ``.nuget\packages\.tools\microsoft.entityframeworkcore.tools.dotnet\1.0.0-msbuild3-final\netcoreapp1.0\project.assets.json`` and it contains dotnet-ef.dll as an asset.

**Comment by emgarten** [comment]
This is caused by the way the CLI reads the project.assets.json file to find the package.

NuGet is correctly writing out the tool assets file and normalizing the casing of package ids to match the nuspec.
