### ISSUE TITLE
local nupkg folder on linux

### ISSUE THREAD

**Issue by tmds** [NuGet/Home#4601]
I want to create a local folder where I put nupkg files and use those packages by configuring NuGet.config on linux.
I haven't found any documentation how to do this.

**Comment by mrward** [comment]
Create the folder, copy the .nupkg into it, and then add that folder to the ~/.config/NuGet/NuGet.Config file. You can add the package source to the NuGet.Config using the [nuget add command](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#sources).

**Comment by tmds** [comment]
@mrward does the nuget tool require mono or does it work on .NET core too?

**Comment by tmds** [comment]
> @mrward does the nuget tool require mono or does it work on .NET core too?

If it requires mono. Can you tell me what I need to add to the NuGet.Config file? I will do it manually.

**Comment by mrward** [comment]
NuGet.exe needs Mono to run.

.NET Core uses a different NuGet.Config location ~/.nuget/NuGet/NuGet.Config

So where you put your package source depends on what you are using to restore NuGet packages.

Below is a minimal NuGet.Config file with a single source that is a directory.

```
<configuration>
  <packageSources>
    <add key="test" value="/some/path/here" />
  </packageSources>
  <activePackageSource>
    <add key="test" value="/some/path/here" />
  </activePackageSource>
</configuration>
```
