### ISSUE TITLE
[Test Failure][Localization] The information from command ‘get-help NuGet’ in PMC is not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4604]
**NuGet Version:** VS.Redist.NuGet VS15.4.0.170213.1779
**VS Version:** D15Rel 26213.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select CHS through ‘Tools -> Options -> International Settings’ and restart VS.
2.  Create a new C# Console Application via VS.
3.  Open the Package Manager Console window, type **‘get-help NuGet’** and hit enter.

**Expected Result:**
Descriptive strings from the command ‘get-help NuGet’ are localized correctly.

**Actual Result:**
Descriptive strings from the command ‘get-help NuGet’ are not localized as below screenshot.
![gethelpnuget](https://cloud.githubusercontent.com/assets/20632625/23009605/e4563aa2-f451-11e6-99c3-59781cef8c77.png)

**Note:**
It repro for all languages.

**Comment by rrelyea** [comment]
Please help us understand previous behavior.  Please compare with  vs 2015 update 3 behavior.

**Comment by v-luzh** [comment]
These strings are all localized on OS: Win10 RS1_Release CHS+VS 2015 U3 CHS as below screenshot.
![4604dev14](https://cloud.githubusercontent.com/assets/20632625/23009565/b02a01fa-f451-11e6-8bfc-85286e13ac27.PNG)

**Comment by mishra14** [comment]
@v-luzh can you please re-test this in latest 15.6?

**Comment by v-luzh** [comment]
@mishra14 it still repro on D15.6 27226.00 CHS (Default NuGet Client 4.6.0.4759) as below screenshot.
![gethelpnuget](https://user-images.githubusercontent.com/20632625/34428482-1234f024-ec88-11e7-98d3-85437f39ca7f.PNG)

**Comment by dominoFire** [comment]
Root cause: localized files are not copied correctly.

**Comment by v-luzh** [comment]
The bug is fixed on NuGet dev-dominofire-pmc-help-fix\5.9.0.13547. Close this issue now, thanks.
