### ISSUE TITLE
[Test Failure][Localization] The message after typing incorrect command and parameter in PMC are not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4605]
**NuGet Version:** VS.Redist.NuGet VS15.4.0.170213.1779
VS Version: D15Rel 26213.00 (select all languages and workloads)
OS Version: Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select CHS through ‘Tools -> Options -> International Settings’ and restart VS.
2.  Create a new C# Console Application via VS.
3.  Open the Package Manager Console window and type ‘install-package newtonsoft.json –version 8.0.3’ and hit enter.
4.  Then type incorrect command ‘update-packge’ and hit enter.
5.  Then type incorrect parameter in command ‘get-package -updetes’ and hit enter.

**Expected Result:**
The message of incorrect command and incorrect parameter should be localized.

**Actual Result:**
The message of incorrect command and incorrect parameter are not localized as below screenshot.
![commanderrormessage](https://cloud.githubusercontent.com/assets/20632625/22968136/2f912fe4-f3a4-11e6-83f5-dc549260110b.PNG)

**Note:**
It repro for all languages.

**Comment by rrelyea** [comment]
Please help us understand previous behavior.  Please compare with  vs 2015 update 3 behavior.

**Comment by mishra14** [comment]
dupe: #4499 

This behavior hasnt changed since NuGet 3.4.4 at least. Possible reason could be that we do not pass culture to the powershell underneath PMC.

**Comment by v-luzh** [comment]
This doesn't repro on OS: Win10 RS1_Release CHS+VS 2015 U3 CHS.
![4605noreproondev14](https://cloud.githubusercontent.com/assets/20632625/23009865/4d951082-f453-11e6-9c5a-544a868ce73c.PNG)
