### ISSUE TITLE
[Test Failure][Localization] String ‘The pipeline has been stopped’ in PMC is not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4606]
**NuGet Version:** VS.Redist.NuGet VS15.4.0.170213.1779
**VS Version:** D15Rel 26213.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801

**Repro Steps:**
1.  Select TRK through ‘Tools -> Options -> International Settings’ and restart VS.
2.  Create a new C# Console Application via VS.
3.  Open the Package Manager Console window, type **‘get-help NuGet’** and hit enter.
4.  **Before the command execute succeed**, click the ‘stop command execution’ button in PMC.

**Expected Result:**
The string ‘The pipeline has been stopped’ should be localized.

**Actual Result:**
The string ‘The pipeline has been stopped’ is not localized as below screenshot.
![pipelinestopped](https://cloud.githubusercontent.com/assets/20632625/22968170/6278c8e0-f3a4-11e6-8ffe-6fa340e58463.PNG)

**Note:**
It repro for all languages.

**Comment by rrelyea** [comment]
Please help us understand previous behavior.  Please compare with  vs 2015 update 3 behavior.

**Comment by mishra14** [comment]
dupe: #4499 

This behavior hasnt changed since NuGet 3.4.4 at least. Possible reason could be that we do not pass culture to the powershell underneath PMC.

**Comment by v-luzh** [comment]
This doesn't repro on OS: Win10 RS1_Release CHS+VS 2015 U3 CHS.
![4606noreproondev14](https://cloud.githubusercontent.com/assets/20632625/23010015/2cf83c54-f454-11e6-8980-4c03b601e4bd.PNG)
