### ISSUE TITLE
[Test Failure][Localization] The information from execute commands show in PMC were not localized

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4608]
**NuGet Version:** VS.Redist.NuGet VS15.4.0.170213.1779
**VS Version:** D15Rel 26213.00 (select all languages and workloads)
**OS Version:** Windows 10 RS1_Release 14393.821.170127-1801 

**Repro Steps:**
1.	Select **JPN** through ‘Tools -> Options -> International Settings’.
2.	Create a new C# Blank UWP project via VS.
3.	Open ‘Package Manager Console’.
4.	Type some execute commands such as **‘Open-PackagePage’** or **'Sync-Package'** or **'Install-Package’**, then hit enter.

**Expected Result:**
The information from execute commands should be localized.

**Actual Result:**
The information from execute commands were not localized as below screenshot.
 ![215](https://cloud.githubusercontent.com/assets/20632775/22968786/cca92276-f3a6-11e6-8408-13de350efb94.png)

**Note:**
It repro for all languages

**Comment by rrelyea** [comment]
Please help us understand previous behavior.  Please compare with  vs 2015 update 3 behavior.

**Comment by mishra14** [comment]
dupe: #4499 

This behavior hasnt changed since NuGet 3.4.4 at least. Possible reason could be that we do not pass culture to the powershell underneath PMC.

**Comment by v-luzh** [comment]
This doesn't repro on OS: Win10 RTM RUS+VS 2015 U3 RUS.
![4608noreproondev14](https://cloud.githubusercontent.com/assets/20632625/23010930/04401a02-f459-11e6-8303-8515d3627621.png)
