### ISSUE TITLE
Rotativa Export Pdf returning error 500

### ISSUE THREAD

**Issue by baskar214** [NuGet/Home#4609]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): Latest

dotnet.exe --version (if appropriate): 4.6.2

VS version (if appropriate): 4.0

OS version (i.e. win10 v1607 (14393.321)): windows Server 2012 R2 Standard

Worked before? If so, with which NuGet version: No.

## Detailed reprot steps so we can see the same problem

1. Error on Export pdf using Rotativa in MVC application.
[System.Exception: Error: Failed loading page htps://sample.test.net:8007/appName/Report/ExportRotativaPDF (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError]

Working fine in development environment, Development Server(hosted env.).
The above error is throwing in only production environment where it is hosted with DNS name. but when the same URL access via IP, its working fine.

Please advise. Thanks in advance.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project

public ActionResult ExportToPdf(string Date)
	ObjWeekly = FillView();
	viewcontent = RenderRazorViewToString("WeeklyReportResult", ObjWeekly).Replace("\"", "'");
	ViewBag.inputhtml = viewcontent;
	return new Rotativa.ActionAsPdf("ExportRotavitaPDF") { FileName = "WeeklyReport.pdf" };
}
public ActionResult ExportRotavitaPDF()
{
        ViewBag.inputhtml = viewcontent;
        return View("ViewPdf");
}

**Comment by rrelyea** [comment]
You should report this question to the owners of that package, not to the NuGet team.
See links on the left side of: http://www.nuget.org/packages/Rotativa/1.7.1-beta for "project site" or "contact owners"
