### ISSUE TITLE
“nuget pack PROJECT.csproj” does not work in post-build event, but does via CMD

### ISSUE THREAD

**Issue by chrfin** [NuGet/Home#461]
I am building some NuGet packages via the following Post-build event:

    CALL "$(SolutionDir).nuget\PushPackage.bat" "$(ConfigurationName)" "$(DefineConstants)" "$(SolutionDir)" "$(ProjectPath)" "$(TargetDir)" "$(TargetName)"

`PushPackage.bat` contains:

    SET ConfigurationName=%~1
    SET Constants=%~2
    SET SolutionDir=%~3
    SET ProjectPath=%~4
    SET TargetDir=%~5
    SET TargetName=%~6
    
    IF %TargetDir:~-1%==\ SET TargetDir=%TargetDir:~0,-1%
    
    SET nuGet=%SolutionDir%.nuget\NuGet.exe
    SET nuGetDefaultParameter=-Properties "Configuration=Release;Platform=AnyCPU" -IncludeReferencedProjects -OutputDirectory "%TargetDir%" -NonInteractive -NoPackageAnalysis
    
    IF  %ConfigurationName%==Release (
    	ECHO Cleaning old packages...
    	DEL %TargetDir%\%TargetName%*.nupkg
    
    	"%nuGet%" pack "%ProjectPath%" %nuGetDefaultParameter% -symbols
    
    	REM publish pacakge according to constants...
    )

This did work fine in another solution, but this time it acts up really strange.  
In the Output I get the following warnings:

> 11>EXEC : warning : File 'E:\OUTPUT_DIR\PROJECT.dll' is not added because the package already contains file 'lib\net451\PROJECT.dll'

Where `PROJECT` is the name of the dll the current project is compiled to. This error shows up once for every referenced project in my solution and only `PROJECT.dll` ends up in my package:  
![Wrong package][1]  
I then "echo"ed out the pack command and executed it manually in a CMD-prompt and there the package was created as it should containing all dll's from all referenced projects:  
![enter image description here][2]

**Is this a bug or am I doing something wrong?**  
Note: This only happens if the referenced projects are not creating their own packages and have an appropriate *.nuspec file. In such case the referenced project is added as a dependency correctly.

P.S.: This is a double-post from the following StackOverflow question: http://stackoverflow.com/questions/29750809/nuget-pack-project-csproj-does-not-work-in-post-build-event-but-does-via-cmd

  [1]: http://i.stack.imgur.com/DztW4.png
  [2]: http://i.stack.imgur.com/iPsaY.png

**Comment by deepakaravindr** [comment]
Thanks for asking the question! StackOverflow is the correct forum for these questions
