### ISSUE TITLE
AutoRestore - can we not run on solution load

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4610]
from VS Feedback 744064, internal user.
Restoring nuget packages. on each solution load of a .nET core projects seems undesired. It should not be the default behavior for every project load.

1. It is consuming CPU and seem to cause UI delay.
2. Sometimes if u open the solution and right click -> rebuild - the context menu is dismissed and need to right click again.

**Comment by emgarten** [comment]
Restore can be disabled through tools > options.
