### ISSUE TITLE
vsfeedback - missing localization in PMC

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4611]
VS Feedback 807301 reported against RC4 bits - https://developercommunity.visualstudio.com/content/problem/19525/bug-with-the-package-manager-console.html 

Appears fixed recently - see internal bug 384934

When performing a package update using the following:
Update-Package -reinstall

At some point in the process you are asked to replace some files, where the following options are displayed:

O arquivo 'Gateway.aspx' já existe no projeto 'newservice-backend'. Deseja substituí-lo?
[S] Sim  [O] Sim para Todos  [N] Não  [S] Não para Todos  [?] Ajuda (o padrão é "N"):

[S] Not for Everyone, where you use the same letter as the [S] option, so when S is pressed, the [S] Yes option is Replacement of the requested file above the options.

OBS: this bug happens in Visual Studio 2017, with the language in Portuguese - Brazil

**Comment by grassiricardo** [comment]
@rrelyea Hello, if you need help or information I am at your disposa

**Comment by mishra14** [comment]
@GrassiRicardo @rrelyea: The translators have fixed the string from Não para Todo&s to  Não para &Todos. This should be fixed in the next insertion with new localized changes. 

I will close this once verified.

**Comment by grassiricardo** [comment]
@rrelyea Okay, thanks, I'm waiting for the correction.

**Comment by mishra14** [comment]
Not sure how to validate the output. But I have checked the strings in our localized resources to be changed in wsr-tc build 1803. I have also notified the translators to make the changes at their end.

@grassiricardo : If you have repro project/steps for this, that would be great!

**Comment by grassiricardo** [comment]
@mishra14 Okay, I do not understand what you would like me to reproduce
