### ISSUE TITLE
vsfeedback - hang after update all in VS (dump file available)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4612]
vs feedback 807883 - https://developercommunity.visualstudio.com/content/problem/19724/updating-nuget-packages-hangs-vs-2017-rc4.html

Please confirm that this is addressed by our recent RTM fix. See dump file in vs feedback item.

**Comment by jainaashish** [comment]
Can't open the provided dump file... have asked for more details from customer via email.

**Comment by jainaashish** [comment]
Ok I'm finally able to analyze this crash dump by getting the right CLR version. And the hang is inside Jetbrains calls so most likely Customer had Resharper installed which messed up this update operation.

@onovotny Can you try to repro this hang without resharper enabled? Meantime I'll forward this crash dump to Jetbrains to further analyze.

**Comment by clairernovotny** [comment]
The hang does not consistently repro...and yes, I do have R# 2017.1 EAP installed.

**Comment by jainaashish** [comment]
hmm, try it without R# and let us know if you ever repro this again.

**Comment by jainaashish** [comment]
Main thread:

Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll
Managed to Native Transition
JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.ExData.AddLine(string name, string value) Unknown
JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry.Render_Primitive(string name, object value, JetBrains.Util.ExceptionRenderer.ExData target)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry.Render(JetBrains.Util.ExceptionRenderer.ExData target)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.RenderSingleExceptionObject.AnonymousMethod__2d(JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry entry)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.Graph.GraphAlgorithms.DepthFirstSearch<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry>(System.Collections.Generic.IEnumerable<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry> rootcollection, System.Func<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry, System.Collections.Generic.IEnumerable<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry>> FGetLinkedNodes, JetBrains.Util.Graph.GraphAlgorithms.PassingOnWayDownDelegate<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry> FEnteringOnWayDown, System.Action<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry> FPassingOnWayDownSimple, System.Action<JetBrains.Util.ExceptionRenderer.HierarchicalDataEntry> FPassingOnWayUp)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.RenderSingleExceptionObject(JetBrains.Util.ExceptionRenderer.ExData exd, bool renderSensitiveData)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.CollectExDatas(System.Exception ex, bool renderSensitiveData)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.RenderException.AnonymousMethod__7()	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.GetExceptionDataCached(System.Exception ex, string key, System.Func<string> FProduce)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ExceptionRenderer.RenderException(System.Exception ex, System.Collections.Generic.IDictionary<object, System.Collections.Generic.IList<object>> customData, bool? renderSensitiveData)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.Logging.LogLog.LogException(System.Exception ex, string comment)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.Logging.ConfiguredLogger.Log(JetBrains.Util.LogEvent logEvent)	Unknown
 	JetBrains.Platform.Util.dll!JetBrains.Util.ILoggerEx.LogException(JetBrains.Util.ILogger this, JetBrains.Util.LoggingLevel level, System.Exception exception, JetBrains.Util.ExceptionOrigin exceptionOrigin, string comment)	Unknown
 	JetBrains.Platform.Shell.dll!JetBrains.Application.Environment.HostParameters.InitStdWindowsAppFxHostMixin.JetBrains.Application.Environment.HostParameters.IInitAppHostMixin.InitHost.AnonymousMethod__2(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs args)	Unknown
 	[Native to Managed Transition]	
 	[External Code]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.CatchException(System.Exception e)	Unknown

**Comment by jainaashish** [comment]
@onovotny can we share this crash dump with Jetbrains to further analyze it?

**Comment by clairernovotny** [comment]
Hi @jainaashish yes, that's fine to share.

**Comment by jainaashish** [comment]
Closing this issue, assuming this issue is fixed by external team. If it still exists, then please open an issue for Jetbrains R#
