### ISSUE TITLE
Package Search is nonsensical 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4614]
vsfeedback 806289 - https://developercommunity.visualstudio.com/content/problem/19260/nuget-package-search-is-nonsensical.html

Open nuget package manager for a project.
In the "Browse" tab type "Microsoft.Extensions" into the search box.
Witness the nonsense!

What is the ordering being applied to the result list?

Why are the three CacheManager.Microsoft.Extensions.* packages anywhere near the top of the list?
They "contain" the text, yes. But, the list is neither alpha ordering, nor ordered in any way that makes it easy to find what you are looking for.
Ordering by download count would be better than what is currently being done.

Also, if I know I'm looking for "logging" and I enter "Microsoft.Extensions.Log" into the search box I get: "No packages found". Are you **** kidding me?

**Comment by CornedBee** [comment]
Another example: type "entity core" in the search box. First result is "MySql.Data.Entity". Second is "EntityFramework" (that's the EF6 thing, not EF Core). Fourth result is "Miscrosoft.Aspnet.WebApi.Core" (nothing to do with EF), fifth is "NuGet.Core" (ditto).

"Microsoft.EntityFrameworkCore", which is what I actually want, is the 17th result and not even visible without scrolling down. It appears that the search result do not prioritize results that contain all search terms over those that contain only some. The first result that contains both "entity" and "core" is the 9th, and there "entity" only appears as a substring in "identity" ("Microsoft.AspNet.Identity.Core"). The first real full match is "Abp.EntityFrameworkCore", at place 15.

If I search for "EntityFrameworkCore", the real EFCore package is the 25th search result, despite having the most downloads (1.02M at the point of this writing; result 3 is a library with no meaningful description and a whopping 165 downloads). At least in this case the results before it have the search term in the title; they're all adapters and extensions. Search results might be improved by doing a PageRank-like thing: packages that are depended on by others are more central and thus rank higher.

**Comment by rendmath** [comment]
> Search results might be improved by doing a PageRank-like thing: packages that are depended on by others are more central and thus rank higher.

As far as package search is concerned, I would disagree. Packages that are heavily depended upon are often infrastructure packages that you don't want on top of your list of results because they are usually pulled as dependencies by other "higher-level" packages.

At the moment, the most obvious problems seem to be:

1. No partial match for package name. You either have to enter the full name or it doesn't work.
2. The download count is not weighted high enough. You often get dozens of obscure packages with a couple thousands downloads each, before getting to the most pertinent one.

**Comment by anangaur** [comment]
Related issue: https://github.com/NuGet/NuGetGallery/issues/4124

**Comment by emgarten** [comment]
Search ordering is handled on the gallery, closing this in favor of https://github.com/NuGet/NuGetGallery/issues/4124
