### ISSUE TITLE
vs feedback - NuGet does not remember password for custom feeds 

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4615]
vsfeedback 747008 - https://developercommunity.visualstudio.com/content/problem/14465/nuget-does-not-remember-password-for-custom-feeds.html

I subscribe to two custom NuGet feeds both of which require authentication. When I type in my username and password, I check the "Remember my credentials" box so I won't have to type them again. I check in "Credentials" from Control Panel and they are stored. However, when I restart Visual Studio, it prompts for them again, every time. 

Rob says: new problem? (note this was reported against RC2.2)

**Comment by nkolev92** [comment]
NuGet itself does not deal with the saving of the credentials.
This seems like a VSO question.
However I am not completely sure what the user meant here. 

We query the VS Account provider and get the credentials from there and those are saved even with multiple feeds.

**Comment by blimkemann** [comment]
Aside from nuget.org, I subscribe to two other feeds: Telerik's and my company's private feed. They both use different credentials. Telerik's uses whatever credentials I have with them and my company's uses Windows authentication.

Every time I open Visual Studio and browse either of those feeds, I am prompted for my credentials. There is a (seemingly) helpful checkbox asking to "Remember my credentials" that I check. Upon doing so, if I restart Visual Studio, my credentials are lost and I am prompted for them again. So it is this "Remember my credentials" feature that is not working.

I was finally able to work around this using nuget sources udpate to modify both of those sources to contain my credentials. But if Visual Studio is essentially telling me it will do the same thing when I check that box, shouldn't it?

**Comment by rrelyea** [comment]
Thanks for the additional info.
Can you help us with a little bit more info?
What kind of NuGet server is your company's private feed? Authentication technology used?
Can you point us toward Telerik's feed (or info about it) if it isn't private info? Any idea of what NuGet Server technology they use?
Thanks!

**Comment by blimkemann** [comment]
I created my feed using an empty ASP.net app and the NuGet.Server package. I access it over the internet and set IIS to use Windows authentication.

To access Telerik's feed (https://nuget.telerik.com/nuget) you need to have an account on their website (and obviously a license to use one or more of their products). I'm sure their support would be happy to help you though.

**Comment by nkolev92** [comment]
Might be related to #4938

**Comment by bazzilic** [comment]
Are there any updates on this issue? It is still there.

**Comment by lamontadams** [comment]
Still exists running against a TeamCity 2017.1.1 Nuget feed. I am prompted for credentials every time Visual Studio restarts, even though I check "Remember my password" every time.

**Comment by mishra14** [comment]
it seems NuGet part of this is fixed in https://github.com/NuGet/NuGet.Client/pull/1513. We will need another fix from Visual Studio.

**Comment by ghost** [comment]
@rrelyea is there a workitem for the partner team to support this like VS for Mac does?
