### ISSUE TITLE
Integrate AnyCode public API changes to NuGet

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4618]
AnyCode team changed their public APIs name which broke LSL (lightweight solution load) scenarios for NuGet so we need to coordinate with AnyCode team to get their changes and update NuGet code to accommodate these changes accordingly. 

Currently GetFileReferencesAsync() api is changed to GetReferencedFilesAsync()

**Comment by rrelyea** [comment]
No longer necessary, it appears.
