### ISSUE TITLE
Package restore is more than 50% slower on nuget.org compared to api.nuget.org. Perhaps, package restore from nuget.org is hitting the DB instead of lucene?

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#462]
Package restore is more than 50% slower on nuget.org compared to api.nuget.org

With around 34 packages to restore, api.nuget.org (likely with the browser cache in place) takes around 8-9 secs, whereas, nuget.org takes more than 19 secs (This is with the legacy machine cache having the packages to be restored)

Guess is that this may be related to DownloadResourceV2 using FindPackagesById instead of other optimized endpoint. Most importantly, this could mean that package restore from nuget.org, may be hitting the database instead of the lucene index

**Comment by deepakaravindr** [comment]
Consider using the hijack to lucene so that DB is not hit

**Comment by bhuvak** [comment]
I looked in to it. api/v2/packages(Id='xx',Version='xx') endpoint is being used in this case - both with 2.8.6 and 3.0.0. With around 35 packages, nuget.org takes around 13-15 secs with machine cache in both cases. There were couple of improvements on the server side - increase the instance size of the Gallery Cloud service and reducing load on DB and that might have helped. 
api/v2/Packages() endpoint currently hits DB and there is a tracking bug for it in Gallery repo : https://github.com/NuGet/NuGetGallery/issues/2428
