### ISSUE TITLE
Avoid downgrade warnings for Package vs Project checks

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#4620]
The version to use for a package when it is built to be published may depend on a build number, versionsuffix, or other information that is not available or not specified with a simple build of a project.  This means that when someone adds a `ProjectReference` to a project expecting NuGet package dependencies to be resolved to that project, the project's version may be lower than required by the dependency specification.  This will result either in downgrade warnings or in the restore operation resolving the dependency to a NuGet package instead of to the reference project.

To make source/package substition work better, the restore operation should probably ignore the version number of project references when checking to see if they satisfy a dependency.  This matches the way project.json behaved.

See https://github.com/aspnet/benchmarks/blob/9a805fee334f25ced7b8f89b3b36a3577ca62056/src/BenchmarksServer/Startup.cs#L217-L220 for how this is being worked around.

@cesarbs @davidfowl

**Comment by emgarten** [comment]
Projects should be overriding packages regardless of the version already. Do you have a repro that shows the issue?

**Comment by dsplaisted** [comment]
> Do you have a repro that shows the issue?

I repro'd this by following the instructions [here](https://github.com/aspnet/benchmarks/pull/188#issuecomment-279782289).  I think these steps should work:

- Clone https://github.com/aspnet/benchmarks, 
- Sync to commit `19ce7c64917fed03734d90e6293999e3091f610a`
- Also clone https://github.com/aspnet/hosting and https://github.com/aspnet/HttpAbstractions
- In the benchmarks code, add the following to `src/Benchmarks/Benchmarks.csproj` (updating the paths to correspond to where you cloned the repos to):

```xml
  <ItemGroup>
    <ProjectReference Include="C:\git\hosting\src\Microsoft.AspNetCore.Hosting\Microsoft.AspNetCore.Hosting.csproj" />
    <ProjectReference Include="C:\git\HttpAbstractions\src\Microsoft.AspNetCore.Http.Abstractions\Microsoft.AspNetCore.Http.Abstractions.csproj" />
  </ItemGroup>
```

- From command prompt, go to `src/Benchmarks` in the benchmarks code.
- Run `dotnet restore`

You'll get errors:

> C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004788\NuGet.targets(97,5): error : Version conflict detected for Microsoft.AspNetCore.Hosting.Abstractions. \r [C:\git\benchmarks\src\Benchmarks\Benchmarks.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004788\NuGet.targets(97,5): error :  Benchmarks (>= 1.2.0-preview1) -> Microsoft.AspNetCore.Mvc (>= 1.2.0-preview1-23476) -> Microsoft.AspNetCore.Mvc.ViewFeatures (>= 1.2.0-preview1-23476) -> Microsoft.AspNetCore.Antiforgery (>= 1.2.0-preview1-23476) -> Microsoft.AspNetCore.DataProtection (>= 1.2.0-preview1-23476) -> Microsoft.AspNetCore.Hosting.Abstractions (>= 1.2.0-preview1) \r [C:\git\benchmarks\src\Benchmarks\Benchmarks.csproj]
C:\Program Files (x86)\dotnet\sdk\1.0.0-rc4-004788\NuGet.targets(97,5): error :  Benchmarks (>= 1.2.0-preview1) -> Microsoft.AspNetCore.StaticFiles (>= 1.2.0-preview1-23476) -> Microsoft.AspNetCore.Hosting.Abstractions (>= 1.2.0-preview1). [C:\git\benchmarks\src\Benchmarks\Benchmarks.csproj]

If you run `dotnet restore /p:VersionSuffix=zzzzz-99999`, it will succeed.

**Comment by cesarblum** [comment]
Also, if you add project references to all projects under Hosting/src and HttpAbstractions/src, you don't get errors on restore but if you inspect `project.assets.json` you'll see that the Hosting references resolve to projects, while the HttpAbstractions references resolve to packages.

**Comment by nguerrera** [comment]
Is there a workaround for this. Cc @agocke @jaredpar

**Comment by dsplaisted** [comment]
You should be able to set the package version property of the project to the same version as the package it's replacing.

**Comment by jaredpar** [comment]
Which property is this?

**Comment by dsplaisted** [comment]
I don't know exactly (I'm on a phone). I think it's PackageVersion.  Version would also work but would also affect the assembly version.

**Comment by jaredpar** [comment]
Thanks.  Version was working but I was worried that it was having other consequences as well.
