### ISSUE TITLE
Nuget.config doesn't appear to be respected

### ISSUE THREAD

**Issue by mattgolding** [NuGet/Home#4621]
My current environment is OSX, VS Code, .netcore

I am trying to include a private nuget feed but it doesn't appear to be used when running the restore command.  My nuget.config file is places in the root folder of the .netcore console app and looks like this.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="CustomRepo" value="https://nuget.feed/nuget/" />
    </packageSources>

    <!-- Used to store credentials -->
    <packageSourceCredentials>
        <CustomRepo>
            <add key="Username" value="something" />
            <add key="ClearTextPassword" value="thepassword" />
        </CustomRepo>
    </packageSourceCredentials>

      <!-- Used to disable package sources  -->
    <disabledPackageSources />
</configuration>
```

I only get the intellisense in VS Code for the public nuget feed but even when I input a known package from the private feed the restore command fails.

Is this not correct?  I have seen others talk about the location of nuget.config being different but nothing really definitive.  Any advise would be great.

**Comment by emgarten** [comment]
@mattgolding what are you using to restore? Could you share the command you are running?

In some scenarios nuget.config needs to be in the solution root or a parent folder, it depends on how you restored.

**Comment by mattgolding** [comment]
Thanks @emgarten 

I tried both methods of restore

1. Through visual studio code (its pops up with a restore button on changes to project.json)
1. Through terminal inside the root folder of the project (the same folder which holds the nuget.config file). with dotnet restore

I should add I was able to try the exact project with the same nuget.config file on a windows box at work and it worked.  I did it through VS Code just as I was on OSX.

**Comment by emgarten** [comment]
@mattgolding what version of dotnet are you using? 

Both of the methods you tried did not work?

**Comment by mattgolding** [comment]
@emgarten I had another crack at it today.  I re-wrote the xml manually and what do you know it worked.  I have no idea why it started working.  It is in the same folder and I used the same methods of performing a restore.

Anyway this issue can now be closed.  Apologies for the time waste.
