### ISSUE TITLE
NuGet background restore waits until VS has focus

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4623]
Build: 26210.2 D15Rel

1. git clone https://github.com/aspnet/Mvc
2. cd Mvc
3. git checkout nimullen/migration.badvs
4. Open MVC.sln
5. File -> Open Output Window
6. Minimize VS
7. Wait 10 minutes
8. Maximum VS

Notice, that VS just starts to do background restore once you give it focus.

**Comment by davkean** [comment]
tag @NTaylorMullen as FYI as this affects MVC.

**Comment by emgarten** [comment]
This should be fixed in the latest version of nuget.
