### ISSUE TITLE
NuGet restore takes an extra-ordinary large amount of time to restore nothing when you have large amounts of projects

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4624]
1. git clone https://github.com/aspnet/Mvc
2. cd Mvc
3. git checkout nimullen/migration.badvs
4. Open MVC.sln
5. Make sure VS has focus (due to https://github.com/NuGet/Home/issues/4623)

Wait until restore is finished

It can take > 2 minutes to restore for ~50 projects that already have their packages downloaded and up-to-date assets file. This is too long.

**Comment by davkean** [comment]
tag @NTaylorMullen as FYI

**Comment by emgarten** [comment]
This looks the same as https://github.com/NuGet/Home/issues/4617
