### ISSUE TITLE
"Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number" opening MVC/CLI repros

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4626]
_From @davkean on February 16, 2017 2:9_

26210.2.d15rel 
No idea what this means or what is causing this, but opening CLI and MVC repros I see this error:

1.  git clone https://github.com/aspnet/Mvc.git
2.  git checkout d3cce192925ff41d0d79aba3728ab1ff80962a49
3.  build.cmd from VS admin command prompt
4.  Open MVC.sln at the root of the repo in VS

Wait

Expected: No errors
Actual: 216 errors with:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'Microsoft.AspNetCore.Razor.Evolution' with no version number.	FormatterWebSite	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
```

_Copied from original issue: dotnet/roslyn-project-system#1575_

**Comment by davkean** [comment]
tag @NTaylorMullen as FYI

**Comment by davkean** [comment]
CLI repro:

1. git clone https://github.com/dotnet/cli
2. cd cli
3. git checkout 18c01886cd8e1472cdde82b15684b8f8b27a2632
4. Open Microsoft.DotNet.Cli.sln

Expected: No errors
Actual: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unexpected dependency 'E:\cli\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj' with no version number.	Microsoft.DotNet.ProjectJsonMigration	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'E:\cli\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj' with no version number.	dotnet	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	
Error		Unexpected dependency 'E:\cli\src\Microsoft.DotNet.Cli.Utils\Microsoft.DotNet.Cli.Utils.csproj' with no version number.	dotnet	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	154	

```

**Comment by davkean** [comment]
@dsplaisted @nguerrera @natidea What does this mean?

**Comment by davkean** [comment]
Here's is one of the assets files for the FormatterWebSite: https://gist.github.com/davkean/038b91eeaecc129ea843394ba2d8aaf3

**Comment by davkean** [comment]
Looking at the code, it looks like this is occurring because Microsoft.AspNetCore.Razor.Evolution isn't showing up in the libraries section of the assets file. Not sure if this is expected or not @emgarten?

**Comment by davkean** [comment]
If I do a dotnet restore, I get different assets file altogether: https://gist.github.com/davkean/c4881f25bea854de43177d5f23062d7f where Microsoft.AspNetCore.Razor.Evolution is listed under libraries section . This looks to be a NuGet issue.

**Comment by emgarten** [comment]
> it looks like this is occurring because Microsoft.AspNetCore.Razor.Evolution isn't showing up in the libraries section of the assets file. Not sure if this is expected or not @emgarten?

That might mean that it wasn't found during resolution. I'll try restoring it and investigate.

**Comment by emgarten** [comment]
Trying locally I don't see these errors.

In https://gist.github.com/davkean/038b91eeaecc129ea843394ba2d8aaf3  I don't see entries for ``Microsoft.AspNetCore.Razor.Evolution`` anywhere. But in my own restore output it does appear.

I'm not sure how that project could be missing from the assets file without an error from restore.

**Comment by nguerrera** [comment]
Was this ever tracked down? Another incoming report from @moozzyk: https://github.com/dotnet/sdk/issues/920

**Comment by davkean** [comment]
Just unload a project, results in this: https://github.com/NuGet/Home/issues/4724

**Comment by DaveHarney** [comment]
I'm trying to add this line of code in a Property Group to my csproj in an otherwise unmodified project using the ASP.NET Core Web Application (.Net Core) template in VS 2017:
` <RuntimeIdentifier>win10-x64</RuntimeIdentifier>`
Without this line of code, the project runs fine.  However, as soon as I save the the csproj, I get 4 errors which are all similar to this one:
`Unexpected dependency 'runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR' with no version number.	`
If I try this in the PM `Install-Package Microsoft.NETCore.Runtime.CoreCLR` it refused to install as it appears to be a downgrade.
Pretty much at a dead end now!

EDIT:  If I use ASP.NET Core Web Application (.Net Framework) template then I don't get this error.  Unfortunately, the actual project for which I need SCD was created as (.Net Core).  Very frustrating waste of time.
EDIT2: ran update and repair for VS - same problem

EDIT3: The problem was I didn't notice an update to The ApplicationInsights package to Version 2.1.0.beta1.  Once I got this update in place, the win7-x64 errors disappeared.  How anyone is supposed to understand that this error message relates to this update .....
 PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.1.0-beta1"

**Comment by ch-hristov** [comment]
Just got this error, clueless what caused it.

**Comment by DaveHarney** [comment]
Hi ch-hristov, please see my last entry in this post: https://forums.asp.net/t/2119601.aspx?SCD+Deployment.  There really should be a better error message.

**Comment by DaveHarney** [comment]
I just posted a comment about this on the GitHub thread.

 

Sincerely, Dave Harney  harney.dave@gmail.com  www.bikex.net

**Comment by ch-hristov** [comment]
Actually I fixed it by just removing all the stuff in the project and transfered them to a new project. Neat right ;D

**Comment by benmccallum** [comment]
I just got this. Not sure if it was pre-existing, as I hadn't yet got this project ever building, but I was trying to upgrade a project generated from the SpaTemplates repo from asp.net core 1.x to 2.x. I added the aspnetcore-dev nuget feed to find the preview packages, di dotnet restore and currently get this on build across numerous dependencies. Again, it could have been happening before I added that nuget source but thought it may be useful nonetheless.

**Comment by mlorbetske** [comment]
Any ideas on this? Our vendor team is starting to see this occasionally with ASP.NET Core 2.0 project templates.

```
Unexpected dependency 'Microsoft.NETCore.App' with no version number.
```

**Comment by natidea** [comment]
This warning is removed as part of this change: https://github.com/dotnet/sdk/pull/1228
NuGet tries to ensure the asset file cannot be in this state.

**Comment by theCuriousOne** [comment]
I came to the same problem and it seems to be miraculously fix  when I add 
`<ReferenceOutputAssembly></ReferenceOutputAssembly>`
inside the .csproj file for which assembly is causing the error.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
