### ISSUE TITLE
Any way to avoid project references to be added as dependency when using msbuild pack target?

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4630]
## Versions
NuGet version: 4.0.x (included in VS2017)
VS version: VS 2017 RC3
OS version: Win 10

## Detailed repro

1. Create a new solution with two .NET standard projects
2. Add a project reference from the first to the seconds project
3. Use `msbuild /t:pack` to create a package
4. The package has the first project as dependency

## Problem
I don't want the first project as dependency.

**Comment by rohit21agrawal** [comment]
Use : ```<PrivateAssets>all</PrivateAssets>```

**Comment by tomkuijsten** [comment]
Didn't know that attribute could be used on `ProjectReference`, thanks!
