### ISSUE TITLE
Support credential provider extensibility on VS2015

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#4631]
At [MyGet](https://www.myget.org), we have built a [Credential Provider for Visual Studio 2017](http://docs.myget.org/docs/reference/credential-provider-for-visual-studio). Awesome, except the majority of users is still on VS2015 :-)

The extensibility support was never released as part of the NuGet VSIX for VS2015, so we can't add support for Visual Studio 2015.

We created a custom build of the NuGet extension, based on the [PR which added extensibility](https://github.com/NuGet/Home/issues/2909). For our customers, this is less than optimal as they have to use a custom build of something they expect to "just work" out of the box. We know the extensibility works though, using our custom build.

Is there any chance an update of the VS2015 extension can be released which contains this PR?

**Comment by rrelyea** [comment]
We aspire to release 4.0.1 to support VS 2015, but that will depend on resources and timing may vary.

**Comment by maartenba** [comment]
Any insight on the timing? (given the milestone name and description just changed :-))

**Comment by maartenba** [comment]
So given there sees to come a VS2015 update (seen in some of the issues floating around), is this one going in as well? @rrelyea

**Comment by rrelyea** [comment]
Bar is extremely high, so unlikely to be taken, but we'll discuss with leadership. Putting into 3.5.1 milestone to track.

**Comment by maartenba** [comment]
If it helps: We have shipped out custom NuGet VSIX with that one commit added, worked flawless so far, but I'd prefer not shipping our own NuGet extension.

**Comment by maartenba** [comment]
So seeing the release of this week, looks like it did not make it in. Pity. Any ETA on a next window?

**Comment by emgarten** [comment]
There are no updates planned for the 3.x branch of nuget at this time.

**Comment by maartenba** [comment]
Does that mean VS2015 is EOL or that 4.x will be made available for 2015?

**Comment by emgarten** [comment]
I don't know of any plans to make 4.x available to VS2015. The focus at this time is VS2017.
