### ISSUE TITLE
vsfeedback - cannot add assembly references - all appear invalid in VSIX project

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4632]
vsfeedback 808498 -- https://developercommunity.visualstudio.com/content/problem/19930/cannot-add-assembly-references-all-appear-invalid.html

I have installed VS2017 on my laptop, along with the visual studio extensibility templates - as described here: https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/prereqs.md

I cloned a repository, which contains a project that was created using the new extensibility templates.

After opening the solution, and doing a nuget restore, all the assembly references show little warning symbols - even though their paths are valid int he project file. Attempting a build produces errors saying that the assembly references cannot be found.

For example, the assembly reference shown on the attached image (envdte - broken assy ref.png - if i inspect the csproj file the reference looks fine and points to the assembly. I have included some other attached images showing the file on disk.

I have uninstalled VS2017 and re-installed it, and I still have the same problem. When I clone the same repository to my PC, I can open it there and it builds fine.

Also if I manaully add an assembly reference to the project - I get the same problem, just picking from any of the .net assemblies. 

It looks like the project system is not able to deal with assembly references for some reason on my environment, and a re-install of vs2017 hasn't fixed it.

**Comment by jainaashish** [comment]
dupe# of https://github.com/Microsoft/VSProjectSystem/issues/181 

Same user has already on going thread with VS Project System since the issue occurs with a specific VS analyzer package and it's install/ uninstall scripts.

**Comment by dazinator** [comment]
It's weird, because all NuGet packages are now installing successfully (I removed the analayser packages that were causing errors on nuget install) - but this problem with invalid references still persists. 
This only happens on my laptop, so I am just trying to narrow the problem down.
