### ISSUE TITLE
Solution Restore of corfxlab repo causes VS to go to Not Responding

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4636]
As part of the investigation of #4617 (corfxlab repro has some issues with Solution Open and Restore)

**Comment by jainaashish** [comment]
@mishra14 if i'm not wrong it was only happening with NuGet debug bits and that too when you've a break point at specific place... Are you able to repro it with release bits as well?

**Comment by alpaix** [comment]
The same as #4255. The right solution would be #3816.
