### ISSUE TITLE
 The package '...' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. 

### ISSUE THREAD

**Issue by 304NotModified** [NuGet/Home#4639]
## Details about Problem

As a package maintainer, we get reports that users cannot install our package on .NET 4.6.1.

They get the error: (I can reproduce it)

```
Install-Package : Failed to add reference. The package 'NLog.Extensions.Logging' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
```

I pin point the problem:

If I have this in the project.json (in the library), I can install it without problems

```json
"dependencies": {
  "Microsoft.Extensions.Logging.Abstractions": "1.1.0"
}, "frameworks": {
  "net461": {
    "dependencies": {

      "System.Xml.ReaderWriter": "4.3.0",
      "System.Runtime": "4.0.10.0",
      "NLog": "4.4.2"
    }
  },
  "netstandard1.3": {
    "dependencies": {
      "NLog": "5.0.0-beta05",
      "System.AppContext": "4.3.0"
    },
    "buildOptions": { "define": [ "NETCORE" ] }
  }
}

```

But no .NET 4.5.1. So adding .NET 4.5.1 support, which uses "frameworkAssemblies". NOTE 4.6.1 doesn't have "frameworkAssemblies". Tried also with vesion numbers for those frameworkAssemblies - same result

```json
 "dependencies": {
    "Microsoft.Extensions.Logging.Abstractions": "1.1.0"
  },
  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.Xml": "",
        "System.Runtime": "",
        "System.Xml.Serialization": ""


      },
      "dependencies": {
        "NLog": "4.4.2"
      }
    },
    "net461": {
      "dependencies": {

        "System.Xml.ReaderWriter": "4.3.0",
        "System.Runtime": "4.0.10.0",
        "NLog": "4.4.2"
      }
    },
    "netstandard1.3": {
      "dependencies": {
        "NLog": "5.0.0-beta05",
        "System.AppContext": "4.3.0"
      },
      "buildOptions": { "define": [ "NETCORE" ] }
    }
  }
```

and then the error 

```
Install-Package : Failed to add reference. The package 'NLog.Extensions.Logging' tried to add a framework reference to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the pa
ckage owners for assistance.
At line:1 char:1
+ Install-Package NLog.Extensions.Logging -Version 1.0.0-rtm-beta7 -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

![image](https://cloud.githubusercontent.com/assets/5808377/23045610/b4502b5c-f4a5-11e6-89a0-68ae76d10040.png)

What am I doing wrong?

**NuGet product used:** Visual Studio Package Manager console

**NuGet version**  3.5.0

**VS version (if appropriate):** VS2015 update 3

OS version: win10 x64

Worked before? If so, with which NuGet version:

Not that I am aware of

## Detailed repro steps so we can see the same problem

1. Start VS2015, create net Console project with .NET 4.6.1

2. install `Install-Package NLog.Extensions.Logging -Version 1.0.0-rtm-beta2 -Pre`

### Verbose Logs

Please let me know if you need this.

### Sample Project

Please let me know if you need this.

**Comment by emgarten** [comment]
Change ``"System.Runtime": "",`` to ``"System.Runtime": { "type": "build" }`` this will keep it from being added to the package and apply it only to your project at build time. Possibly all of these references should include this, but you'll need to verify that the package works without them.

The issue in the nupkg is that System.Runtime is listed in the nuspec

```xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Runtime" targetFramework=".NETFramework4.5.1" />
      <frameworkAssembly assemblyName="System.Xml.Serialization" targetFramework=".NETFramework4.5.1" />
    </frameworkAssemblies>
```

I know this is painful experience for package authors, but the fix is to just remove the framework assembly reference. The System.Runtime assembly is actually a facade and forwards to another assembly which ends up causing this problem for Visual Studio. 

You can find a full list of facades to avoid in:
``C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades``

**Comment by 304NotModified** [comment]
it worked!

Do I need also something like this in VS2017 (csproj) ?

**Comment by emgarten** [comment]
Pack for csproj in VS2017 does not include these framework assemblies by default, you should be fine there.

//cc @rohit21agrawal

**Comment by 304NotModified** [comment]
OK thanks!

**Comment by forrestab** [comment]
Sorry, I know this is not the right place to ask this, but it is the only place I have seen it said.

@emgarten, you said,

> Pack for csproj in VS2017 does not include these framework assemblies by default

Does this mean there is a switch to include them for dotnet core .csproj files?
