### ISSUE TITLE
Logging (via status bar, output window, and warning/error window) requires UI thread and slows down Restore greatly.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4640]
Split off from #4617

**Comment by emgarten** [comment]
Logging and error list improvements

* Moves from the legacy TaskProvider error list to the free threaded IErrorList
* Warnings/errors are no longer logged from the UI thread
* Optimized logging to only move to the UI thread when needed, this shows a 3x perf improvement in some scenarios
