### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#4641]
Hi NuGet,

I have faced the **"unable to connect to the remote server"** problem while install the NuGet packages by using NuGet.exe (3.5.0) with the FinalBuilder 7

Please see the error details:
![image](https://cloud.githubusercontent.com/assets/16695209/23053280/443acc2e-f4fe-11e6-8fcb-341dc884ee19.png)

This problem occurred randomly in Final builder. I didn't get any problem while install the NuGet package with the NuGet.exe in the command window. I have faced this issue only run the NuGet.exe with the finalbuilder.

please help me on this, how can I rectify this problem?

Thanks,
Ganesan R.

**Comment by emgarten** [comment]
@GanesanRengasamy I'm not familiar with Final builder, was it working in the past? Are any packages downloaded?

The error message indicates a download timeout, you might try adding ``-DisableParallelProcessing`` to limit the number of connections.

**Comment by GanesanRengasamy** [comment]
Hi @emgarten 

Thanks for the response. I have used the private feed to install the custom NuGet packages. If I use this same finalbuilder for install the local(offline) packages, I don't get this issue. I have faced this problem while use online private feed.

Also I have used the -DisableParallelProcessing with the NuGet install command like this "install %PackageName% -Version %VERSION% -Source %Url% -DisableParallelProcessing -o "%INSTALLPATH%\%Platform%". I have faced the below error.

![image](https://cloud.githubusercontent.com/assets/16695209/23064544/a5010d4c-f536-11e6-9883-1354502f273b.png)

if I used this wrongly, please suggest the right way.

Thanks,
Ganesan R.

**Comment by emgarten** [comment]
@GanesanRengasamy oh, for ``install`` this property cannot be used. You could try by running a restore instead against a packages.config file to see if it helps.

Is the timeout always the same, or does it change each run?

**Comment by emgarten** [comment]
Closing due to lack of response.
