### ISSUE TITLE
Dependency name of project reference not taken from PackageId

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4642]
## Versions
NuGet version: 4.0.x (included in VS2017)
VS version: VS 2017 RC3
OS version: Win 10

## Detailed repro
1. Create a new solution with two .NET standard projects (ClassLibrary1 and ClassLibrary2)
2. Add the `PackageId` property to the ClassLibrary1 project and use "CustomName" as value
3. Add a project reference from ClassLibrary1 to ClassLibrary2
4. Build the solution
5. Use `msbuild /t:pack` in the ClassLibrary2 folder to create a package
6. The package has "ClassLibrary1" as dependency

## Problem
I expected "CustomName" as dependency

**Comment by emgarten** [comment]
@tomkuijsten how did you restore the projects?

**Comment by tomkuijsten** [comment]
I didn't explicitly restore the projects, I changed the repro steps with where I executed the build.

**Comment by emgarten** [comment]
Try running msbuild /t:Restore and then building/packing.

**Comment by rrelyea** [comment]
Thanks for report. Dupe of #4586 
At risk for RTM.
Workaround: restore via command line before packing.
