### ISSUE TITLE
[Feedback] Can not update to .NETCore 1.1.0 after upgrading to Microsoft.NETCore.UniversalWindowsPlatform v5.3.0

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4643]
Internal bug 385268 

Create UWP project with VS2015 and upgrade UWP package to v5.2.2 Open project in VS2017 RC3 - RC4. Open Manage NuGet packages for solution and check available updates. Microsoft.NETCore.Runtime.CoreCLR v1.1.0 is listed as package available for update. Trying to update fails with error message:

GET https://api.nuget.org/v3/registration1-gz/microsoft.netcore.jit/index.json
OK https://api.nuget.org/v3/registration1-gz/microsoft.netcore.jit/index.json 661ms
Restoring packages for E:\src\tools\{Project path and Name}\project.json...
GET https://api.nuget.org/v3-flatcontainer/runtime.win8-arm.microsoft.netcore.jit/index.json
NotFound https://api.nuget.org/v3-flatcontainer/runtime.win8-arm.microsoft.netcore.jit/index.json 533ms
Unable to resolve 'runtime.win8-arm.Microsoft.NETCore.Jit (>= 1.1.0)' for 'UAP,Version=v10.0 (win10-arm)'.
Unable to resolve 'runtime.win8-arm.Microsoft.NETCore.Jit (>= 1.1.0)' for 'UAP,Version=v10.0 (win10-arm-aot)'.

it seems that win7-x86 and win7-x64 versions are available on nuget while arm version of assembly is available only as a preview package

**Comment by jainaashish** [comment]
`runtime.win8-arm.microsoft.netcore.jit` package isn't available on NuGet.org which is why this update failed. DotNet team needs to look into this and publish this package.

**Comment by rrelyea** [comment]
@ericstj  - should we create an issue here: https://github.com/dotnet/corefx?

**Comment by rrelyea** [comment]
Moved to: https://github.com/dotnet/corefx/issues/16275

**Comment by ericstj** [comment]
CoreCLR is the correct repo for that one.
