### ISSUE TITLE
'dotnet pack' puts nuspec under obj instead of obj\Debug

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4644]
Under a new .NET SDK project, when I type `dotnet pack`, the nupkg is placed under `bin\debug` as expected, but the nuspec is placed under `obj` instead of `obj\debug`. Since the nuspec contains debug-specific paths, it should be under the `obj\debug` folder, thereby allowing debug and release builds to not overwrite each others' files in a multi-proc build and otherwise to gain more from incremental build while maintaining reliability.

```
dotnet --version
1.0.0-rc4-004812
```

**Comment by rohit21agrawal** [comment]
CC: @rrelyea for assigning milestone
