### ISSUE TITLE
RuntimeEnvironmentHelper.IsLinux returns true for OSX

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4648]
The RuntimeEnvironmentHelper.IsLinux helper should be improved to properly detect OSX when running on Mono. 

Currently this method returns true when on OSX. In many scenarios this method is used to check if the file system is case sensitive. We should fix up any areas where this is being used incorrectly.

**Comment by rrelyea** [comment]
@zhili1208 - you said that we used this to check if case sensitive, but I didn't notice any cases of that in your change. Did we miss those, or did we not end up having them?

**Comment by rrelyea** [comment]
@zhili1208 - additional question - 2) this works with both dotnet.exe and (nuget.exe on mono) ?

**Comment by zhili1208** [comment]
some case sensitive check failed on Mac due to the IsMacOS return false on Mac. This change fix the issue, so no need to change any case sensitive check.

this is only for mono, dotnet.exe have another code path to do the check
