### ISSUE TITLE
PackTask throws NullReferenceException when NuspecProperties is specified

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4649]
As soon as any NuspecProperties is specified, dotnet pack fails.

```
dotnet new classlib
dotnet restore
dotnet build
dotnet pack
```

The pack succeeds. Now modify .csproj by adding this property definition in the `PropertyGroup`:

```xml
    <NuspecProperties>$(NuspecProperties);GitCommitIdShort=70f1d9353d</NuspecProperties>
```

Then pack again:

```
dotnet pack

Microsoft (R) Build Engine version 15.1.546.27743
Copyright (C) Microsoft Corporation. All rights reserved.

  d -> C:\temp\d\bin\Debug\netstandard1.4\d.dll
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: The "PackTask" task failed unexpectedly.\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: System.NullReferenceException: Object reference not set to an instance of an object.\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage(String path)\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage()\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Build.Tasks.Pack.PackTask.Execute()\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()\r [C:\temp\d\d.csproj]
C:\Program Files\dotnet\sdk\1.0.0-rc4-004812\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\temp\d\d.csproj]
```

```
dotnet --version
1.0.0-rc4-004812
```

**Comment by rrelyea** [comment]
@rohit21agrawal  - Please determine problem, so we can appropriately understand to triage.

**Comment by rohit21agrawal** [comment]
@AArnott can you provide a repro project?

**Comment by rohit21agrawal** [comment]
```NuspecProperties``` only has any meaning when it's provided with a ```NuspecFile```

**Comment by AArnott** [comment]
@rohit21agrawal: the repro steps are simple enough, right? It's the simplest repro project imaginable, plus one line.

> NuspecProperties only has any meaning when it's provided with a NuspecFile

That's unfortunate, because an extra nuspec file is rather cumbersome when all I want to do is set one property with a $macro$ in it. See [here](https://github.com/AArnott/Validation/commit/be79503a9431c984b60a29edda677f2db3ad2f49#diff-fcc665af66d56864b76ca425ae5a0848R24) for what I'm trying to do and how I workaround it. It's not a terrible workaround, but I was hoping I wouldn't need it.

BTW, even if you stick with your current design, I suppose we can do better than throw an NRE from the Task, yes?

**Comment by rohit21agrawal** [comment]
@AArnott Agree that the task shouldn't throw a NRE. We are tracking this in a bigger issue : https://github.com/NuGet/Home/issues/4472

As far as the scenario is concerned, this is what NuspecProperties is used for : https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#packing-using-a-nuspec

I still don't really understand what you were trying to achieve though. What did you hope to achieve by setting the NuspecProperties when you weren't even packing using a nuspec file?

**Comment by AArnott** [comment]
> What did you hope to achieve by setting the NuspecProperties when you weren't even packing using a nuspec file?

I was hoping that the NuspecProperties would be applied to evaluate macros I set in the .csproj file for those properties that get copied to the build-generated nuspec file.

**Comment by rohit21agrawal** [comment]
@AArnott we haven't designed a scenario like that, all the property evaluation when packing from csproj is done by msbuild. 

Reviewed this with @rrelyea , moving it to 4.0.1 to fix the null ref exception .

**Comment by AArnott** [comment]
> all the property evaluation when packing from csproj is done by msbuild.

I would accept that as an answer. Mixing two macro evaluation models into MSBuild instead of just one could be more confusing than it is valuable.

**Comment by emgarten** [comment]
Closing based on https://github.com/NuGet/Home/issues/4472

If this is still an issue let me know. Thanks!

**Comment by AArnott** [comment]
@emgarten Yes, it still repros:
```
dotnet --version
2.1.1-preview-007118

C:\Program Files\dotnet\sdk\2.1.1-preview-007118\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(204,5): error : Object reference not set to an instance of an object. [C:\temp\temp.csproj]
```

**Comment by emgarten** [comment]
@AArnott thanks! Moving this to the backlog for pack.
