### ISSUE TITLE
Need to make sure that references to VS dlls like Microsoft.VisualStudio.Threading, are VS version specific

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#465]
Need to make sure that references to VS dlls like Microsoft.VisualStudio.Threading, are VS version specific. Currently, There are references to Microsoft.VisualStudio.Threading.14.0.0 from PackageManagement and VisualStudioExtension, but, they are not under Version specific itemgroups. Need to make sure that it is, in order to build the NuGet extension for versions other than VS 2015

**Comment by yishaigalatzer** [comment]
@deepakaravindr please asses how necessary is this change for support versions newer than visual studio 2015

**Comment by emgarten** [comment]
This has been fixed by the facade projects.
