### ISSUE TITLE
Wiki Documentation Inconsistent and Out of Date

### ISSUE THREAD

**Issue by johnkoerner** [NuGet/Home#4651]
As a new user trying to build for the first time, I followed the contributing instructions linked from the [ReadMe.md](https://github.com/NuGet/Home/blob/dev/README.md) in the Nuget Home repository. After following these instructions, I ran into numerous errors and came to the determination that the wiki was out of date.

Specifically, the content in the [Setting up the NuGet Development Environment](https://github.com/NuGet/Home/wiki/Setting-up-the-NuGet-Development-Environment) seems to be out of date and is not consistent with the [ReadMe.md](https://github.com/NuGet/NuGet.Client/blob/dev/README.md) file in the Nuget.Client repo. It also appears that [Contributing.md](https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md) is inconsistent with the ReadMe.md file.

It may be best to consolidate the documentation for pulling and building into a single document, as to avoid having multiple sources of the same information.

**Comment by rrelyea** [comment]
Thanks for feedback. Sorry for trouble.

**Comment by rohit21agrawal** [comment]
@johnkoerner please let me know if you are still having trouble with building the repository, and i can help you out with it .

**Comment by johnkoerner** [comment]
@rohit21agrawal I haven't gotten back to that yet, but I am sure I can figure it out. I was just logging the issue to help others in the future.
