### ISSUE TITLE
MSBuildTool that depends on DotNetCliTool

### ISSUE THREAD

**Issue by ctaggart** [NuGet/Home#4653]
Hi, I'm working on tools to help automate the `/sourcelink` option for the compilers. I've packaged the tools as dotnet cli tools with simple MSBuild tools packages that are wrappers. Is it possible to have the MSBuild tools package reference the dotnet cli tool.

Currently, I must tell people to include both:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <DebugType>Portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.GitHub" Version="2.0.0-*" />
    <DotnetCliToolReference Include="dotnet-sourcelink-git" Version="2.0.0-*" />
  </ItemGroup>
</Project>
```

But I really just want to tell people to include one:
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
    <DebugType>Portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.GitHub" Version="2.0.0-*" />
  </ItemGroup>
</Project>
```

Is this possible or will this be possible?

## Environment data
`dotnet --info` output:

```
PS C:\Users\camer\cs\SourceLink> dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771
```

When I discussed in https://github.com/dotnet/cli/issues/5774, it sounded like this a feature request. One solution would be to add a  <PackageType>DotnetMSBuildTool</PackageType> and added some special handling.

Love the new tooling! Just seeing if it is possible to make it even easier.

**Comment by emgarten** [comment]
@ctaggart there are currently no plans allow mixing project tools and project dependencies. I can see how this would be useful for sourcelink (which is a great package that I use!). From a restore perspective the project restore and the tool restores are completely unrelated, with separate restore graphs, and they go into separate project.assets.json files.
