### ISSUE TITLE
Package dependencies are not suppressible when they come from a P2P reference

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#4655]
So I hit a project where [setting `PrivateAssets=all` doesn't eliminate the package dependency](https://github.com/AArnott/CodeGeneration.Roslyn/commit/32b5d88dc7d6e7233321d74877f22accb34761f3).

Even though I set `PrivateAssets=all` on all my PackageReference and even ProjectReference items, the generated nuspec file still retains the set dependencies that would have propagated from the P2P that *didn't* set PrivateAssets=all:

```xml
    <dependencies>
      <group targetFramework=".NETFramework4.5.2">
        <dependency id="CodeGeneration.Roslyn" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Build.Tasks.Core" version="14.3.0" exclude="Build,Analyzers" />
        <dependency id="Microsoft.CodeAnalysis.CSharp.Workspaces" version="1.3.2" exclude="Build,Analyzers" />
      </group>
    </dependencies>
```

See, for the P2P, which also creates a NuGet package, it is *appropriate* for the dependencies to be there. But for *this* project, which is an MSBuild extension, it should have *no* dependencies, and I take care to embed all the assemblies I need. So how can I get the generated nuspec to not have any?

d15rel 26220.0
dotnet version 1.0.0-rc4-004842

**Comment by AArnott** [comment]
Per [this doc](https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target#project-to-project-references) it seems what I'm asking for is by design.

**Comment by rohit21agrawal** [comment]
@AArnott  can you attach the assets file of your project here? it's likely that restore is doing the wrong thing here, and pack puts that dependency in the nuspec file as  a consequence of that.

**Comment by AArnott** [comment]
Sure: [project.assets.json.zip](https://github.com/NuGet/Home/files/791338/project.assets.json.zip)

**Comment by AArnott** [comment]
Oh snap. This is another case of needing to run restore after making the change. When I change the project file then re-pack without restoring, the change isn't applied. I don't find this intuitive and it will take some time for me to learn the new way things work.
