### ISSUE TITLE
[Test Failure] Package ‘Microsoft.NETCore.Platforms’ and ‘Microsoft.NETCore.Targets’ failed to install into ASP.NET Core Web App 1.1 template

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4656]
**NuGet Version:** NuGet 4.0.0-RTM-2300
**VS Version:** D15Rel 26220.00
**OS Version:** Windows 10 RS1_Release 14393.851.170215-1802

**Repro Steps:**
1. Create an **ASP.NET Core Web App 1.1** template via VS.
2. Open the ‘Manage NuGet Packages…’ for this project.
3. Try to install package **‘Microsoft.NETCore.Platforms 1.1.0’** and package **‘Microsoft.NETCore.Targets 1.1.0’** into this template.
4. Check the message in Output window and open NuGet node under Dependencies node in Solution Explorer window.

**Expected Result:**
There is package installed successfully message show in Output window and there are no warning icons beside the package name in Solution Explorer window.

**Actual Result:**
There is no package installed successfully message show in Output window and there are warning icons beside the package name in Solution Explorer window.
![twopackfailtoinstall](https://cloud.githubusercontent.com/assets/20632625/23157370/e0058afe-f855-11e6-9cbe-fd8ef238b63e.png)

**Note:**
1. The warning icons gone when opening the same project again.
2. No repro in ASP.NET Core Web App 1.0 template with the same packages.

**Comment by rrelyea** [comment]
@ericstj - my guess is that these packages are not meant to be added directly to a project. They are likely added implicitly by a metapackage or the like?

**Comment by mishra14** [comment]
@rrelyea, @v-luzh:

This seems to be happening because of filtering code [here](https://github.com/NuGet/NuGet.Client/blob/7676e7ff39faf3234e264b7b344e17e6900f3ead/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/BuildIntegratedRestoreUtility.cs#L127).

After the install, we display the "Successfully Installed" log onto for packages which were not present in the old assets file. But it seems that both `Microsoft.NETCore.Platforms 1.1.0` and `Microsoft.NETCore.Targets 1.1.0` are already present in the assest file of a new NetCore 1.1 Web app.

**Comment by ericstj** [comment]
@rrelyea any package should be upgrade-able.  Sure we don't expect folks to do this much (and I suspect they won't since these are typically indirect dependencies that are not offered for upgrade) but there is no reason why it shouldn't work.

**Comment by v-luzh** [comment]
@rrelyea @mishra14 Same issus occur when installing package **'Microsoft.CSharp 4.3.0'** into .NetCore and .NetStandard templates as below screenshot.
![samewithmicrosoft csharp](https://cloud.githubusercontent.com/assets/20632625/24495825/f58c09ae-1568-11e7-948a-0b63dd938f10.PNG)

**Comment by v-luzh** [comment]
Fixed on VSUWPT 26512.01 + NuGet Client Dev-4056. Close this bug now. Thanks.
