### ISSUE TITLE
Nuget restore package NUnitLite@3.6 cause Vs report fatal error

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4657]
vsfeedback 812089

**Comment by mishra14** [comment]
The project csproj file had 2 imports for NUnitLite which was causing a conflict. I have emailed the customer about the this. Waiting to hear back if that unblocks/fixes the customer problem.

**Comment by gameldd** [comment]
Yes this fix my problem. After i edit the csproj file, set both NUnitLite package references to the same version, no more error report!  It look like when you project target multiple framework, and each framework reference same package , update package action only update one PackageReference item, which cause the conflict.

**Comment by mishra14** [comment]
@gameldd : thanks for confirming that this fixed your problem. I will look into the problem a bit more before closing the bug.

**Comment by mishra14** [comment]
I did some more investigation and I could not get a repro without manually adding references into the csproj file. Closing the issue.

**Comment by mishra14** [comment]
I was able to get repro steps. I have opened another bug with more details - https://github.com/NuGet/Home/issues/4681
