### ISSUE TITLE
Unable to open NuGet.Packaging solution in VS2015

### ISSUE THREAD

**Issue by forderud** [NuGet/Home#466]
I'm unable to open the NuGet.Packaging solution in VS2015 CTP6.

Steps to reproduce:
* Checkout *master* branch of https://github.com/NuGet/NuGet.Packaging.git
* Open Packaging.sln

Error message (same for all projects):
* *NuGet.Packaging\src\NuGet.Frameworks\NuGet.Frameworks.xproj : error  : Value cannot be null.
Parameter name: projectMoniker*

**Comment by yishaigalatzer** [comment]
This is a known issue, latest DNX is not compatible with CTP6. You either need to wait for RC bits to come out, or use OmniSharp and command line build.

**Comment by forderud** [comment]
I'm surprised that NuGet cannot be built with any publicly available version of Visual Studio. This makes it difficult for external parties to contribute to the open-source project.

**Comment by yishaigalatzer** [comment]
It is built against vs 2015, and must use the SDK for build the vs extension. As for everything else it uses dnx, you can work on the daily dnx bits and use commandline/omnisharp or another text editor to build. See githib/aspnet/home on how to use nightly bits from dnx.
