### ISSUE TITLE
Modify NuSpecReader to throw when it encounters invalid data

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/Home#4662]
The Gallery deserializes data from `.nuspec`s using a `NuGet.Packaging` class called [`NuSpecReader`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/NuspecReader.cs). When this class sees an invalid version range, [it silently handles it](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/NuspecReader.cs#L130) and [returns a version range that contains all versions](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging.Core.Types/PackageDependency.cs#L64). As a result, the Gallery has no visibility on broken metadata and cannot reject packages with invalid version ranges.

We should modify `NuSpecReader` to support throwing an exception when it sees invalid metadata.

This can be done by either
1. Modifying everything that uses it to handle the exception.
2. Creating an additional path ("strict mode") so that the gallery can use it for the upload flow and the remaining client APIs can remain unchanged.

**Comment by emgarten** [comment]
Adding a strict mode sounds like a good idea for this.
