### ISSUE TITLE
Migrated project throws restore error 

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4663]
**Repro steps** 
- Copy the folder \\mlangfs1\public\Jinuj\TestCases\migrate\AspNetCoreWeb_IndAuth_WithAI_1 to your machine.
- open the sln file
- click for one way upgrade 
- Build the project 

**Expected** 
Builds without any error 

**Actual**

Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Unable to resolve 'Microsoft.Extensions.SecretManager.Tools (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
Error occurred while restoring NuGet packages: Value cannot be null.
Parameter name: path
Unable to resolve 'Microsoft.EntityFrameworkCore.Tools.DotNet (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
1>------ Rebuild All started: Project: AspNetCoreWeb_IndAuth_WithAI_1, Configuration: Debug Any CPU ------
Unable to resolve 'Microsoft.EntityFrameworkCore.Tools (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
Unable to resolve 'Microsoft.VisualStudio.Web.CodeGeneration.Design (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
1>AspNetCoreWeb_IndAuth_WithAI_1 -> C:\AspNetCoreWeb_IndAuth_WithAI_1\src\AspNetCoreWeb_IndAuth_WithAI_1\bin\Debug\netcoreapp1.0\AspNetCoreWeb_IndAuth_WithAI_1.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

![image](https://cloud.githubusercontent.com/assets/12449387/23182374/2dde27d2-f82d-11e6-9cc7-342fbe405ff3.png)

**Comment by emgarten** [comment]
This looks like an issue with the migration tool or the packages.

Project.json has ``"Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final"``

The errors here show the stable ``1.0.0`` version.

However on nuget.org the latest version is: ``1.1.0-preview4-final``
https://www.nuget.org/packages/Microsoft.Extensions.SecretManager.Tools/1.1.0-preview4-final

@livarcocc how should this work?

**Comment by livarcocc** [comment]
The RTM versions of these packages are in a myget feed, you need to add a NuGet.Config entry for them in order to restore. They will show up in NuGet once we RTM.

I believe this is the feed: `<add key="asp-msbuild3-feed" value="https://dotnet.myget.org/F/msbuildtools/api/v3/index.json" />`

**Comment by emgarten** [comment]
Thanks @livarcocc 

@jinujoseph try adding the source @livarcocc mentioned.
