### ISSUE TITLE
Error "'Add-Migration' is not recognized as the name of a cmdlet" when trying to add migration using Package Manager Console

### ISSUE THREAD

**Issue by balachir** [NuGet/Home#4664]
**INSTALL STEPS**
Win8.1 x64 ENU
Dev15 RTW VSP(Web + Azure workload)
Go offline after install by turning off the nuget.org feed
 
**REPRO STEPS**
1. Create a 1.0 Core Web Application (No Auth)
2. Add Movie.cs to the Models folder
    public class Movie
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public DateTime ReleaseDate { get; set; }
        public string Genre { get; set; }
        public decimal Price { get; set; }
    }
3. Register context in Startup.cs with dependency injection
4. Build solution 
5. Run EF migrations
Add-Migration MyFirstMigration

**ACTUAL** 

PM> Add-Migration MyFirstMigration
Add-Migration : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
 
![image](https://cloud.githubusercontent.com/assets/8246794/23182389/379f6574-f82d-11e6-8b52-12800662689c.png)

**EXPECTED**
Add-Migration command to be successful

**Comment by joelverhagen** [comment]
Have you verified that you have the **Microsoft.EntityFrameworkCore.Tools** package installed as a `<PackageReference>`? You can open up your .csproj to see this.

This Microsoft.EntityFrameworkCore.Tools package is what brings along the PowerShell commands like `Add-Migration`.

One investigation step you can take is to search your `obj\project.assets.json` file for any instances of the string `init.ps1`. If you don't find any, this means that you have no package references which add commands to the Package Manager Console (PMC).

I took at look at your specific project as noticed that the Microsoft.EntityFrameworkCore.Tools package is installed as a `<DotNetCliToolReference>`. If you change this to a `<PackageReference>` you should be fine. `<DotNetCliToolReference>` does not have init.ps1 support.

Note that the **Microsoft.EntityFrameworkCore.Tools.DotNet** package _should_ be installed as a `<DotNetCliToolReference>`, but this package does not have any `init.ps1` file in it.
