### ISSUE TITLE
Package should store which source it is installed from

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#4666]
@petterek commented on [Wed Feb 15 2017](https://github.com/NuGet/NuGetGallery/issues/3573)

I think it would be a good idea to add an attribute to the <package > tag, to indicate which source it was installed from. 

 <package id="NUnit" version="3.6.0" targetFramework="net461" src="nuget.org" />

When installing a package using the "Manage packages for soulution" in vs studio, then nuget will use the src from the tag, and not from the src selected in the DropDown 

nuget fails to install a package when the "wrong" packagesource is selected, with an "package not found"

---

@petterek commented on [Wed Feb 15 2017](https://github.com/NuGet/NuGetGallery/issues/3573#issuecomment-280018944)

I don't think this issue is about this.. 
This occure in mycase because I have 5 different package sources hosting different kind of packages. 

Might be my us case is "out of scope" but I also belive that adding a src attribute to the package tag could be useful. For information to the user as well when looking at the packages file

**Comment by emgarten** [comment]
@petterek using the ``All`` source would allow the client to find the package wherever it exists, does this solve the issue for you?

**Comment by petterek** [comment]
Yes it solves the issue, but it is also very annoying when you for some reason miss that it is not set to all and the package is not installing.



Sendt fra min Samsung Galaxy-smarttelefon.


-------- Opprinnelig melding --------
Fra: Justin Emgarten <notifications@github.com>
Dato: 22.02.2017 07:34 (GMT+01:00)
Til: NuGet/Home <Home@noreply.github.com>
Ko: Petter Ekrann <Petter.Ekrann@infotjenester.no>, Mention <mention@noreply.github.com>
Emne: Re: [NuGet/Home] Package should store which source it is installed from (#4666)


@petterek<https://github.com/petterek> using the All source would allow the client to find the package wherever it exists, does this solve the issue for you?

**Comment by emgarten** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, but we haven’t been able to fully investigate your problem as our focus has been on other problem reports. If there are more community feedback on this, then we'll re-evaluate this.
