### ISSUE TITLE
[Question] Use NuGet.config for both VS project and cli commands?

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4669]
_From @chuckries on February 17, 2017 20:40_

Is there a way to get the same NuGet.config file to be used from both 'dotnet restore' on the command line and IDE solution build?

```
dotnet --version
1.0.0-rc4-004788
```

I have a .NET Core test project. I have a NuGet.config file in the project directory next to the .csproj. Running dotnet restore works correctly. If, however, I build from VS 2017 RC, the package is not restore because the NuGet.config file is not used. 

Is there a way to make both methods pick up the same NuGet.config by default without using a machine specific setup?

_Copied from original issue: dotnet/cli#5761_

**Comment by TheRealPiotrP** [comment]
_From @chuckries on February 22, 2017 1:4_

Anybody?

**Comment by TheRealPiotrP** [comment]
@chuckries I believe this should work, but the folks at `nuget/home` will know for sure. I'll move the issue for you.

**Comment by emgarten** [comment]
Visual Studio reads settings at the solution level, place your NuGet.Config file in the solution root directory to apply it to both the IDE and dotnet CLI.

**Comment by chuckries** [comment]
This worked, thanks!
