### ISSUE TITLE
dotnet restore ignores --verbosity flag

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4670]
_From @natemcmaster on February 21, 2017 22:47_

## Steps to reproduce
dotnet restore -v quiet
dotnet restore -v detailed
dotnet restore -v diagnostic

## Expected  behavior
Console output should show different levels of verbosity.

## Actual behavior
Always displays minimal output.

## Environment data
Using 1.0.0-rc4-004842

_Copied from original issue: dotnet/cli#5783_

**Comment by TheRealPiotrP** [comment]
Moving to nuget/home.

**Comment by emgarten** [comment]
Dupe of https://github.com/NuGet/Home/issues/3772

@natemcmaster pass the verbosity parameter in msbuild format, example: ``/v:diag``

**Comment by DerAlbertCom** [comment]
Why is this a dupe?

```bat
dotnet restore --help
.NET dependency restorer

Usage: restore [arguments] [options] [args]

Arguments:
  [PROJECT]  Optional path to a project file or MSBuild arguments.

Options:
  -h|--help                          Show help information
  -s|--source <SOURCE>               Specifies a NuGet package source to use during the restore.
  -r|--runtime <RUNTIME_IDENTIFIER>  Target runtime to restore packages for.
  --packages <PACKAGES_DIRECTORY>    Directory to install packages in.
  --disable-parallel                 Disables restoring multiple projects in parallel.
  --configfile <FILE>                The NuGet configuration file to use.
  --no-cache                         Do not cache packages and http requests.
  --ignore-failed-sources            Treat package source failures as warnings.
  --no-dependencies                  Set this flag to ignore project to project references and only restore the root project
  -v|--verbosity                     Set the verbosity level of the command. Allowed values are q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

Additional Arguments:
 Any extra options that should be passed to MSBuild. See 'dotnet msbuild -h' for available options.

```
There is an Option to set the verbosity, which get's ignored. So this is clearly a bug, and not a dupe #3772.

```
dotnet restore /v:diag
dotnet restore /p:verbosity=Diagnostic
```
are both not delivering the diagnostic verbosity. Evertime minimal is used.

i found out the that with
```
 dotnet restore /clp:Verbosity=Diagnostic
```
i can set the desired verbosity. But this not user friendly when there is an official option on the cli for the verbosity which is ignored.

**Comment by vindicatorr** [comment]
About a decade since the non-dupe, and this elevator button that does nothing is still here and doing nothing.
EDIT0: To be specific, with "verbosity" set to diag (or anything), the output is `<pathToProject> <whitespace>* Restore (<elapsedTime>s)`

`diag` should be very noisy with at least fetch/get statements being made.

**Comment by zivkan** [comment]
@vindicatorr   You're probably running into the .NET SDK's change to enable the "terminal logger" by default:
* https://github.com/dotnet/sdk/issues/43293

**Comment by vindicatorr** [comment]
Likely. I know that when I `dotnet <...> | tee some.log`, I get my output.
Disabling terminalLogger also has that effect.
consoleLogger AND terminalLogger? oranges AND Oranges? Searching had g-ai explain it. Still weird.
Perhaps even more weird that even if you specify clp, tlp STILL has to be disabled to see anything. God-awful implementation.
