### ISSUE TITLE
Command to list all the package dependencies for a project

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4677]
If I have a project with following dependencies

Project: Foo
- DepencencyPackageA
- DepencencyPackageB
- DepencencyPackageC

I should have a command like 

> nuget.exe dependencies Foo.csproj

**Comment by mishra14** [comment]
@anangaur : We have a plan to add a `dotnet list package` command in dotnet cli. We have a bug tracking it at https://github.com/NuGet/Home/issues/4102

**Comment by nkolev92** [comment]
@mishra14 But that's for packageref only?
I would assume if we were to do this, it'd need to be done package.config & project.json.

A feature like this would also be functionally equivalent to https://github.com/NuGet/Home/issues/1264

**Comment by emgarten** [comment]
@mishra14 has a prototype of this

**Comment by mishra14** [comment]
closing this as a dupe of #4102.
