### ISSUE TITLE
server infrastructure should incorporate bulk-rebuild optimizations

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#468]
We materialize significant quantities of metadata across blob storage and we have jobs to incrementally keep this up to date. We know from experience that significant optimizations can be applied for a bulk rebuild of a metadata set.

This is a tracking issue to formalize these optimizations into reusable jobs we can run on demand if teh occasion arises.

**Comment by maartenba** [comment]
This issue was moved to NuGet/NuGetGallery#2623
