### ISSUE TITLE
Support installing standalone vsix v3 NuGet into experimental instance of VS

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4682]
**NuGet Version:** NuGet 4.0.0-rtm-2316
**VS Version:** D15Rel 26222.00
**OS Version:** Windows 10 RS1_Release 14393.851.170215-1802

**Repro Steps:**
1.	Create a new C#->Blank App (Universal Windows) project.
2.	Start **‘Manage NuGet packages’** dialog by right clicking of the project node.

**Expected Result:**
The ‘Manage NuGet packages’ dialog can be opened regularly.

**Actual Result:**
The ‘Manage NuGet packages’ dialog can’t be opened and pop up an error window as below screenshot.
![kkk](https://cloud.githubusercontent.com/assets/20632775/23247514/85fc3bb2-f9d5-11e6-8c8c-27e5fcad9be1.png) 

**Notes:**
1.	The issue repro on other projects.
2.	The issue repro on other NuGet build **(2311,2313,2314)** under **release-4.0.0-rtm** folder.

**Comment by v-nancyj** [comment]
The issue not repro on **Dev14 MU3.5+NuGet Client 4.0.0-rtm-2314**.

**Comment by nkolev92** [comment]
Workaround:

Rename the file in Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.PackageManagement.PowershellCmdlets.dll temporarily while playing with the experimental instance....rename it back once you've uninstalled the experimental instance. 

Clear the ComponentCache once you've renamed the dll.

**Comment by nkolev92** [comment]
There's a bug filled on powershell side. 
https://github.com/PowerShell/PowerShell/issues/3325

**Comment by nkolev92** [comment]
Another workaround for installing experimental VSIX into VS (No such luck on launching the experimental VS instance). 

- Install Exp VSIX.
- Start VS once, close it.
- Clear the MEF components Cache
- Start VS and voila. 

Issue here is that the when you install a different Exp VSIX (which means it goes to a different directory than the earlier VSIX) you end up having to do the same thing again.

**Comment by v-luzh** [comment]
@rrelyea, this issue is fixed on VSUWPT 26509.00+NuGet Client 4.3.0.4052 according to our verification. The non-insertable vsix can be installed successfully. Please help to close this bug, thanks.
