### ISSUE TITLE
.csproj file not updated in Visual Studio until user does a Save All or closes solution

### ISSUE THREAD

**Issue by dougbu** [NuGet/Home#4689]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

## Details about Problem

NuGet product used: VS UI
Nuget Package Manager 4.0.0

dotnet.exe --version: `1.0.0-rc4-004883`

VS version (if appropriate): `15.0.0+26222.1d15rel`

OS version: Win10 v1607 (14393.696)

Worked before? Not positive but thing old package.config file was updated immediately.

## Detailed repro steps so we can see the same problem

1. Create a .NET Core Console solution
2. Add a package e.g. Microsoft.EntityFrameworkCore.SqlServer v1.0.0
3. Save everything
4. Switch to a console window and confirm the .csproj file contains
    ``` xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.0" />
    ```
5. Open "Manage NuGet Packages&hellip;" again
6. Update the package to a newer version e.g. v1.1.0 in above case
7. Wait for restore to complete
8. Switch to console window and&hellip;
    *Expected*
    ``` xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.0" />
    ```
    *Actual*
    ``` xml
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.0" />
    ```
9. Save everything in Visual Studio
10. Now Actual will match Expected.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by dougbu** [comment]
> Not positive but thing old package.config file was updated immediately.

I am sure no similar problem existed when editing project.json files in Visual Studio 2015.

> Save everything in Visual Studio

At step 9, Visual Studio and the NuGet Package Manager show no indication anything at all needs to be saved.

**Comment by davkean** [comment]
This issue was moved to dotnet/roslyn-project-system#1628

**Comment by davkean** [comment]
I've moved this issue over to the project-system - this is our experience/issue, this issue can be closed.

**Comment by emgarten** [comment]
Thanks @davkean 

NuGet doesn't force a save here for perf reasons. With packages.config it was a much smaller file that was only used by NuGet so saving it at the end of an operation instead of letting VS save it when closing the solution made more sense. Now that PackageReferences are in the project file and no longer written directly by NuGet I think it makes more sense for the project system to handle this so it can be optimized appropriately.
