### ISSUE TITLE
Restore on build should not run for DNX projects and projects that do not use NuGet

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#469]
CC @balachir

**Comment by yishaigalatzer** [comment]
Projects that do not use NuGet should skip this whole process.
Similarly projectK that does not want to do restore through NuGet should be skipped.

**Comment by deepakaravindr** [comment]
Also, fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/80e6e5a7b902a40618bdfac118ac70e62713f5c1
