### ISSUE TITLE
VS2017 RC: I can not update NETStandard.Library in Nuget

### ISSUE THREAD

**Issue by gotoxu** [NuGet/Home#4692]
From the last update of VS2017 (VisualStudio/15.0.0-RC4+26206.0), I can't update the package NETStandard.Library in Nuget. I just create a new standard library project. See the message: 

![1](https://cloud.githubusercontent.com/assets/10518551/23331101/9e6424ba-fb99-11e6-9a75-23a673cf79f5.png)

It means the new version is blocked by the project or package.config limit.

So I can only add the `<NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>` in the csproj file, then it works.

Why can't I update it in the Nuget?

**Comment by emgarten** [comment]
@Jamesxql the package version is set in the SDK. To update this you need to update your SDK and dotnet CLI installation. The change isn't as simple as just updating the package unfortunately which is why this is now blocked in the NuGet UI.
