### ISSUE TITLE
msbuild /t:restore is nearly 5 times slower than nuget restore

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4696]
VS: 2617.2 D15Rel
NuGet restore: 3.6.0.1954

We switched over to using `msbuild /t:restore` instead of `nuget restore` and found that it's 5 times slower than using NuGet restore when there is nothing to restore:

Over three runs of http://github.com/dotnet/roslyn-project-system, I found the following:

NuGet restore: 3.43 seconds
MSBuild /t:restore: 16.64 seconds

This is nearly 5 times slower and has caused restore from taking just 3% of our build time, to taking nearly 20% of our build time. This is a significant regression.

**Comment by emgarten** [comment]
@davkean thanks for the numbers. The work to optimize this is being tracked here https://github.com/NuGet/Home/issues/4592
