### ISSUE TITLE
dotnet restore yield error: "Package X is not compatible with net461 (.NETFramework,Version=v4.6.1). Package X supports: net461 (.NETFramework,Version=v4.6.1)"

### ISSUE THREAD

**Issue by TheRealPiotrP** [NuGet/Home#4697]
_From @Ashthos on February 24, 2017 10:59_

## Steps to reproduce

The error in the title is occurring for a number of packages in our solution. But **only** for our Win2016 Teamcity Build agents. Our Win2012 build agents restore the package fine. We are using/restoring packages that are deployed to our internal nexus server.

dotnet --version:
win2012 - 1.0.0-preview2-003133
win2016 - 1.0.0-preview2-1-003177

## Expected  behavior

Package restores correctly.

## Actual behavior

Package fails to restore.

```
Errors in .\src\worker\<projectname>.Ioc\project.json
     Package X is not compatible with net461 (.NETFramework,Version=v4.6.1). Package X supports: net461 (.NETFramework,Version=v4.6.1)
     One or more packages are incompatible with .NETFramework,Version=v4.6.1.
```

Where X is "\<packagename\>-v140.net 83.0.0-RC-86057-1"

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

_Copied from original issue: dotnet/cli#5835_

**Comment by emgarten** [comment]
@Ashthos can you try this with preview4 of dotnet CLI? If it still repros would you also share the file structure of the nupkg.

**Comment by Ashthos** [comment]
Installed dotnet-dev-win-x64.1.0.0-rc4-004771.exe on our Win2016 build agent. Performed "dotnet migrate" then "dotnet restore" and the packages restored as expected.

Only issue for us right now is that we are still project.json based due to our dependency on vs2015, and many of our build scripts are expecting a project.json to be available :(

**Comment by emgarten** [comment]
Thanks @Ashthos, sounds like this is fixed in the latest bits. Let me know if you run into this again when using PackageReferences.
