### ISSUE TITLE
Regression: Fail to install some packages due to file name escaping

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#470]
Here: https://github.com/NuGet/NuGet.PackageManagement/blob/master/src%2FProjectManagement%2FUtility%2FPathUtility.cs#L175

and just below. 

MSBuild use to suffer the same issue.

There is a good reason to use them in filenames; to overcome file system naming limitations.

This is a regression in Nuget 3. It works fine on Nuget 2. 

Bug repro: `Install-Package IronScheme`

Results in a `ArgumentNullException`.

The encoded filename is `and-let%2a.sls` which in turn ends up being `and-let*.sls` which is clearly an invalid filename.

CC: @leppie

**Comment by yishaigalatzer** [comment]
@leppie what we see is that the file is not being copied over, which is different than seeing an `ArgumentNullException` can you provide more details about what version are you using (vs, NuGet) and into what type of project you are installing it.

https://github.com/NuGet/NuGetGallery/issues/2410

**Comment by leppie** [comment]
@yishaigalatzer: Sorry for the dupe, did not realise everything got copied over from codeplex :)

Normal C# console app.VS2015 CTP 6. Nuget 3.0.60225.100

From the PM console in VS2015 I get:

```
Install-Package : Value cannot be null.
Parameter name: zipArchiveEntry
At line:1 char:16
+ Install-Package <<<<  IronScheme
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

From the UI I get a dialog with (same exception):
```
System.ArgumentNullException: Value cannot be null.
Parameter name: zipArchiveEntry
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__d2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActions>d__1b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
```

I tracked this down to https://github.com/NuGet/NuGet.PackageManagement/blob/master/src%2FProjectManagement%2FUtility%2FMSBuildNuGetProjectSystemUtility.cs#L103

With https://github.com/NuGet/NuGet.PackageManagement/blob/master/src%2FProjectManagement%2FUtility%2FMSBuildNuGetProjectSystemUtility.cs#L81 doing the unescaping

From the debugger, I can see all entries are valid in the zip archive.

**Comment by deepakaravindr** [comment]
//cc @deepakaravindr

**Comment by yishaigalatzer** [comment]
Thanks, this wasn't a dup just a wrong repo. We are going to take a look. Also note that current code is all in dev (and not master) branch
