### ISSUE TITLE
Nuget.exe should work with csproj (PackageReference)

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#4702]
**Error:**
>C:\Users\<username>\Downloads\nuget.exe pack MyNetStandard.csproj
Attempting to build package from 'MyNetStandard.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Packing files from '\bin\Debug\netstandard1.4'.
**Unable to cast object of type 'System.String' to type 'NuGet.Frameworks.NuGetFramework'.**

**Nuget version:** 
downloanded from [nuget.exe (v4.0.0-rc4)](https://dist.nuget.org/win-x86-commandline/v4.0.0-rc4/nuget.exe)
NuGet Version: 4.0.0.2275  

**Project file attached:**
[MyNetStandard2.0.zip](https://github.com/NuGet/Home/files/805423/MyNetStandard2.0.zip)

**Comment by rohit21agrawal** [comment]
nuget.exe doesn't work on package reference based projects.

**Comment by AngusMcIntyre** [comment]
Are there any plans to derive nuget package dependencies from the csproj package references?
