### ISSUE TITLE
NuGet fails with "System.ArgumentException: '$(NetStandardImplicitPackageVersion)' is not a valid version string." when encountering PackageReference in legacy csproj with property as version

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4706]
26226:0.d15rel

Running into this in project system repro when we open some projects that have a PackageReference with a variable, looks like the items aren't being evaluated - not sure if this is NuGet or legacy project system's problem:

```
Error occurred while restoring NuGet packages: System.ArgumentException: '$(NetStandardImplicitPackageVersion)' is not a valid version string.
Parameter name: value
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.ToPackageLibraryDependency(LegacyCSProjPackageReference item)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.GetPackageSpec()
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<>c__DisplayClass36_0`1.<<RunOnUIThread>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<RunOnUIThread>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyCSProjPackageReferenceProject.<GetPackageSpecsAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<IsRestoreRequiredAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

```

**Comment by emgarten** [comment]
It looks like this string is coming out of VSProject4
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/PackageManagement.VisualStudio/EnvDTEProjectAdapter.cs#L342

I would need to debug it to know for sure, is this happening all the time, or what are the repro steps?

**Comment by davkean** [comment]
Open our repro at https://github.com/dotnet/roslyn-project-system/commit/8783c37817dfbe8fa7752a013d5516994a8118e3.

We're accidentally opening the VB-based SDK projects in legacy project system - but when you bring up PackageReference in legacy, you'll probably want to at least evaluate the items.

**Comment by lythix** [comment]
I've just started having a look at this repo (dotnet/roslyn-project-system) and discovered this Nuget fail/error when trying to build. Was there a fix/workaround to get past it? It blocks doing a build within Visual Studio 2017.

**Comment by davkean** [comment]
@lythix You should be able to build via the command-line first before opening VS - and it shouldn't block. If it still does, turn off package restore during build in tools -> options -> NuGet package manager.

@emgarten I did some research and this is basically because when PackageReference was implemented for old csproj, it was implemented using the MSBuild construction model not the evaluation model, hence variables are not evaluated. :(

**Comment by davkean** [comment]
That sounds like my team's issue - but regardless, this shouldn't stop restore for every other project. It also appears to block Test Explorer.

**Comment by emgarten** [comment]
Test explorer uses the list of installed packages to find the test adapter. NuGet is likely passing the exception up to test explorer here when it finds an invalid project. I think this is the correct behavior, silently ignoring a bad reference and returning the valid ones found seems like it could cause confusion.

> this shouldn't stop restore for every other project

I agree, this should be contained to only the project or project closures that are affected. NuGet should restore the rest of the projects here.

**Comment by davkean** [comment]
I can't see how `Error occurred while restoring NuGet packages: System.ArgumentException: '$(NetStandardImplicitPackageVersion)' is not a valid version string.` is a useful nor actionable error for the user.

**Comment by lythix** [comment]
Agreed. My experience, as a user, when encountered with this error message was confusion. I did not know what I had done (nothing, really. Restoring Nuget packages is generally the first thing one does so very common timing would be when you first clone a repo).
Given it was not my codebase (yet!) the error message, although descriptive of what was missing, gives no indication on what to do about it. 
Googling the error returns this exact thread as the first search result. :)

Building from commandline was my work around in this instance, that worked. (thanks @davkean)

**Comment by davkean** [comment]
@lythix If you pull the latest from master, restore should work for these projects because of https://github.com/dotnet/roslyn-project-system/pull/1900.

**Comment by lythix** [comment]
Tested that from a fresh clone and all built correctly. 

I did see some errors, first attempt but a second build passed. Possibly due to some build order dependencies not being built in correct order. 
Nuget restore worked in Visual Studio 2017 (which wasn't working before).

**Comment by davkean** [comment]
Build order should be correct, let me figure out what the cause of this is on Monday.

**Comment by lythix** [comment]
No probs. 
I will have a look on the weekend and see if I can work out what's going on. 
An example of some of the messages that showed up in Nuget Package Manager window (in red... that's new I think)

```
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS.UnitTests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.FSharp.VS could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.VisualStudio.ProjectSystem.Managed could not be loaded.
```

I tried it a second time from scratch as I only took a screenshot rather than cut error text first time, and it was slightly different second time. 

![2017-03-31_11-32-47](https://cloud.githubusercontent.com/assets/124019/24539417/0289c296-1621-11e7-90ee-de05d44755f4.png)

**Comment by davkean** [comment]
Yeah that's known, and shouldn't block restore.

**Comment by CyrusNajmabadi** [comment]
Also hitting this in Roslyn now.  We call into APIs like IVsPackageInstallerServices.GetInstalledPackages and it throws ArgumentExceptions with the above message.

**Comment by emgarten** [comment]
@davkean is there an issue tracking a fix for this on the project system side?

Having to parse these things on the caller side, evaluate all of them, and put together the result doesn't seem correct if NuGet were to do that.

If NuGet can't get the version from the PackageReference it can't restore. Quietly ignoring the error as suggested will lead to an incomplete restore result that would be difficult to debug.

``Error occurred while restoring NuGet packages: System.ArgumentException: '$(NetStandardImplicitPackageVersion)' is not a valid version string.`` is referring to the version used on the PackageReference. I think the confusion here is that the SDK is referencing it, but I don't see a good way for NuGet to explain that here.

**Comment by emgarten** [comment]
Closing in favor of https://github.com/dotnet/project-system/issues/2129

**Comment by davidwengier** [comment]
Thanks. I'll keep plugging away too. I think the submodules might be somehow incorrect actually.

In https://github.com/ashmind/ILSpy github is showing "cecil @ 53df0bc", however I have cecil at the latest commit 3bd25b. Looks like there are some breaking changing in that (eg the Name property on VariableDefinition is gone) so I'll start with trying to pin those submodules matching what is shown in github.

**Comment by paulomorgado** [comment]
I'm getting this on projects migrated from packages.config to PacakageReference.


If I had the PackageReference by hand to the .csproj, it shows up in the NuGet UI but when I try to compile it behaves as if the reference is not there.
