### ISSUE TITLE
Visual Studio becomes unusable while restore is occuring and it's logging errors/warnings

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4707]
Build: 26226.0.d15prel

1. Clone http://github.com/dotnet/roslyn-project-system
2. checkout 05a8c79edcb4c6a20b4f133e4a17aee33bd39368
3. Run Build.cmd from command-prompt
4. Open ProjectSystem.sln
5. Wait for restore to finish
6. Open src\build\targets\References.targets
7. On line 87 delete the project reference to Roslyn.csproj and replace it with `<PackageReference Include="Microsoft.VisualStudio.LanguageServices" Version="2.0.0-rc2" />`
8. Save
9. Unload any project (doesn't matter what)
10. Try to continue to make changes to References.targets

Expected: To be able to make changes
Actual: Restore continually sets focus to the Error List making it impossible to interact with the rest of VS

Having restore continually set focus to the Error List isn't helpful as it's processes projects one-by-one - build does it, but at the end of the build of the entire solution. If NuGet does this, it should be at the end of restore of the entire solution.

**Comment by davkean** [comment]
It also doesn't respect this option:
![image](https://cloud.githubusercontent.com/assets/1103906/23395414/923c7cf0-fde2-11e6-8b15-443053b12af3.png)

https://github.com/NuGet/Home/issues/4708

**Comment by davkean** [comment]
To top this off, you can't even just wait for Visual Studio to finish restoring and go and read email because it's [stops restoring when VS doesn't have focus](https://github.com/NuGet/Home/issues/4623) - so basically, your computer is unusable while it's in this state. You have to go off for a coffee while it's doing this.

**Comment by davkean** [comment]
Here's a video of how bad this experience is: https://vid.me/JNaT

Not all the errors here are because of NuGet, but the focus issues are definitely caused by restore.

**Comment by davkean** [comment]
It also continually restores every time I load and unload a project - is that expected?

**Comment by emgarten** [comment]
There have been several optimizations that have gone in since this issue was opened that should cover this
* Logging optimizations
* Perf/Memory allocation fixes
* Noop support which should cover unload/reload
