### ISSUE TITLE
NuGet package dependency added in different location in project.assets.json before second restore

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#4712]
## Details about Problem

NuGet version: 4.0.0.2275

VS version: Microsoft Visual Studio Enterprise 2017 RC 
Version 15.0.26206.0 D15REL

## Detailed repro steps so we can see the same problem

The project.assets.json file generated when installing a NuGet package into a .NET Core project is different to the final one produced. The NuGet package is moved from a dependencies section to inside the frameworks section. There seems to be a restore that is run right at the end, after the install completes, which modifies the project.assets.json file again. Noticed this since currently Visual Studio for Mac is not doing the restore at the end since I assumed the lock file generated during the install was OK to use, but it seems to be different.

1. Create a .NET Standard project.
2. Add Newtonsoft.Json 9.0.1
3. Open the obj\project\assets.json after the 'Writing lock file to disk' has completed but before the 'Restoring NuGet packages' is run.

```
Restoring packages for c:\projects\tests\NetStandardLib12\NetStandardLib12\NetStandardLib12.csproj...
Installing NuGet package Newtonsoft.Json 9.0.1.
Committing restore...
Writing lock file to disk. Path: c:\projects\tests\NetStandardLib12\NetStandardLib12\obj\project.assets.json
Restore completed in 2 sec for c:\projects\tests\NetStandardLib12\NetStandardLib12\NetStandardLib12.csproj.
Successfully installed 'Microsoft.CSharp 4.0.1' to NetStandardLib12
Successfully installed 'Newtonsoft.Json 9.0.1' to NetStandardLib12
Successfully installed 'System.Dynamic.Runtime 4.0.11' to NetStandardLib12
Successfully installed 'System.Reflection.Emit 4.0.1' to NetStandardLib12
Successfully installed 'System.Reflection.Emit.ILGeneration 4.0.1' to NetStandardLib12
Successfully installed 'System.Reflection.TypeExtensions 4.1.0' to NetStandardLib12
Successfully installed 'System.Runtime.Serialization.Primitives 4.1.1' to NetStandardLib12
Executing nuget actions took 8.09 sec
Time Elapsed: 00:00:10.7107619
========== Finished ==========

Restoring NuGet packages...
Time Elapsed: 00:00:01.8042815
========== Finished ==========
```
4. Then open the obj\project.assets.json after the second restore has run.
5. obj\project.assets.json after 'Writing lock file to disk' but before second restore is run:

```
  "project": {
    ...
    ,
    "dependencies": {
      "Newtonsoft.Json": {
        "target": "Package",
        "version": "[9.0.1, )"
      }
    },
    "frameworks": {
      "netstandard1.4": {
        "dependencies": {
          "NETStandard.Library": {
            "target": "Package",
            "version": "1.6.0",
            "autoReferenced": true
          }
        }
      }
    }
  }
```

6. obj\project.assets.json after the final restore is run:

```
  "project": {
    ...
    ,
    "frameworks": {
      "netstandard1.4": {
        "dependencies": {
          "NETStandard.Library": {
            "target": "Package",
            "version": "1.6.0",
            "autoReferenced": true
          },
          "Newtonsoft.Json": {
            "target": "Package",
            "version": "9.0.1"
          }
        }
      }
    }
```

With Visual Studio for Mac, the extra restore is not run. I did not think this was needed since the NuGet packages are restored during the install. However the project.assets.json generated at that point seems to be different compared to what is generated if another restore is then manually run from within Visual Studio for Mac.

**Comment by emgarten** [comment]
Fixed as part of the work for https://github.com/NuGet/Home/issues/5080

This should be in the NuGet 4.4 libraries
