### ISSUE TITLE
Very large retry count for GraphOperations to try resolving dependency conflicts

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4715]
There is some 1000 times retries logic in GraphOperations class to try n resolve dependency conflicts. We need to reevaluate this logic and such a high count of retries since it calls into lot of nested foreach loops so at times, it becomes really expensive and allocates bunch of memory.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.DependencyResolver.Core/GraphModel/GraphOperations.cs#L181

**Comment by nkolev92** [comment]
Given that it's difficult to estimate the impact of this potential problem & we haven't heard about a lot of problems where the resolver has failed, I think we're better off focusing on well understood scenarios. 

Closing this.
