### ISSUE TITLE
Nuget: Could not install package 'Microsoft.Extensions.Logging 1.1.0'.

### ISSUE THREAD

**Issue by ericf01** [NuGet/Home#4716]
## Details about Problem

NuGet product used: Package Manager Console

NuGet version (x.x.x.xxx): Package Manager Console Host Version 2.8.60610.756

OS version: win10 Pro v1607 (14393.693)):

## Detailed repro steps so we can see the same problem

1.  In Microsoft Visual Studio Express 2013, create a vbproject targeting .Net Framework 4.5.1

2.  Open Package Manager Console

3.  PM> Install-Package Npgsql
Attempting to resolve dependency 'System.Threading.Tasks.Extensions (= 4.3.0)'.
Attempting to resolve dependency 'Microsoft.Extensions.Logging (= 1.1.0)'.
Installing 'System.Threading.Tasks.Extensions 4.3.0'.
You are downloading System.Threading.Tasks.Extensions from Microsoft, the license agreement to which is available at http://go.microsoft.com/fwlink/?LinkId=329770. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'System.Threading.Tasks.Extensions 4.3.0'.
Installing 'Microsoft.Extensions.Logging 1.1.0'.
You are downloading Microsoft.Extensions.Logging from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.Extensions.Logging 1.1.0'.
Installing 'Npgsql 3.2.1'.
Successfully installed 'Npgsql 3.2.1'.
Adding 'System.Threading.Tasks.Extensions 4.3.0' to Relevance Suite.
Successfully added 'System.Threading.Tasks.Extensions 4.3.0' to Relevance Suite.
Adding 'Microsoft.Extensions.Logging 1.1.0' to Relevance Suite.
Uninstalling 'Microsoft.Extensions.Logging 1.1.0'.
Successfully uninstalled 'Microsoft.Extensions.Logging 1.1.0'.
Uninstalling 'System.Threading.Tasks.Extensions 4.3.0'.
Successfully uninstalled 'System.Threading.Tasks.Extensions 4.3.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'Microsoft.Extensions.Logging 1.1.0'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.
At line:1 char:1
+ Install-Package Npgsql
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by emgarten** [comment]
@ericf01 the package contains the netstandard1.1 target framework which requires NuGet 2.12

You can get it from here: http://dist.nuget.org/index.html

**Comment by ericf01** [comment]
@emgarten - Upgrading Nuget from 2.8 to v2.12 in Visual Studio 2013 solved my initial problem.  

However, the "Windows x86 Commandline" section of https://dist.nuget.org/index.html jumps directly from nuget.exe (v2.8.6) to nuget.exe (v3.2.0) without offering a v2.12.  I found that nuget.exe v3.2.0 does work with VS 2013's MsBuild v12; however, the latest nuget.exe v3.5.0 apparently requires MsBuild v14, which isn't included with VS 2013.

Thanks for your help resolving this issue.

**Comment by emgarten** [comment]
Re-opening for the msbuild version issue. You should be able to specify the path to msbuild's bin folder with ``-MSBuildPath``. 

Could you also try the 4.0.0-rc4 release of nuget.exe?

There is no 2.12 release since 4.0.0 should cover all packages.config scenarios and support backwards compat.

**Comment by emgarten** [comment]
@zhili1208 does nuget.exe auto detect msbuild12?

**Comment by zhili1208** [comment]
4.0.0 can auto detect msbuild12, 3.5 can't

**Comment by emgarten** [comment]
Thanks @zhili1208 

Closing this again as fixed based on that info

**Comment by ericf01** [comment]
I tested and confirmed that nuget.exe v4.0.0 auto-detects and uses MsBuild v12 whereas v3.5 does not.  This version should be marked as the "latest"
