### ISSUE TITLE
Migrated project shows warning when packed.

### ISSUE THREAD

**Issue by jinujoseph** [NuGet/Home#4718]
**Repro Steps**

- Copy the zip file from \\mlangfs1\public\Jinuj\TestCases\MigrationIssue1\EFGetStarted.AspNetCore.NewDb.zip 
- unzip and open the sln 
- Accept the migration and build once done.
- Right click the project and select "Pack" 

**Expected**
Packed with no error or warning 

**Actual**

1>------ Build started: Project: EFGetStarted.AspNetCore.NewDb, Configuration: Debug Any CPU ------
1>EFGetStarted.AspNetCore.NewDb -> C:\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\bin\Debug\netcoreapp1.0\EFGetStarted.AspNetCore.NewDb.dll
1>Successfully created package 'C:\EFGetStarted.AspNetCore.NewDb\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\bin\Debug\EFGetStarted.AspNetCore.NewDb.1.0.0.nupkg'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue found with package 'EFGetStarted.AspNetCore.NewDb'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: PowerShell file outside tools folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The script file 'content\wwwroot\lib\bootstrap\nuget\MyGet.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'tools' folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: PowerShell file outside tools folder.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The script file 'contentFiles\any\netcoreapp1.0\wwwroot\lib\bootstrap\nuget\MyGet.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Move it into the 'tools' folder.
1>Done building project "EFGetStarted.AspNetCore.NewDb.csproj".
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
