### ISSUE TITLE
`dotnet pack --include-source` places code sub-directories in the root of the package.

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4719]
From @brettfo at https://github.com/dotnet/cli/issues/5871

## Steps to reproduce
Create a package with sources that includes code in subdirectories.

``` bash
mkdir test
cd test
dotnet new classlib
mkdir SomeDir
touch SomeDir/OtherFile.cs
dotnet restore
dotnet pack --include-source
```

Then extract the `*.symbols.nupkg` file

## Expected  behavior
I expect the following structure:

```
...
src/
    test/
        SomeDir/
            OtherFile.cs
        Class1.cs
        test.csproj
...
```

## Actual behavior
The `SomeDir` directory was placed in the root of the package:

```
...
SomeDir/
    OtherFile.cs
src/
    test/
        Class1.cs
        test.csproj
...
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771
```

**Comment by TAGC** [comment]
I've encountered this issue just now too, as it was causing problems with source-stepping when I published these symbol packages to my MyGet feed. I've tried creating these packages using dotnet SDK 1.0.1 on both a Windows 64-bit development machine and within Bitbucket Pipelines CI builds using a variant of the microsoft/dotnet:latest Docker image.

This issue only seems to occur when running within the Docker environment, so it seems to be a Linux-specific issue. If I run the exact same commands in Windows using the same SDK version, I get the expected package structure.

Comparing the two package structures in Nuget Package Explorer (blurred for privacy reasons):

**Good package structure - created on Windows 7 dev machine**

![good symbols package-blurred](https://cloud.githubusercontent.com/assets/1588951/24499849/015b5a24-153b-11e7-8965-7b1c971ba85a.PNG)

```
$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Bad package structure - created within Docker environment**

![bad symbols package -blurred](https://cloud.githubusercontent.com/assets/1588951/24499875/199cc53c-153b-11e7-82b1-0a77321d5cbc.PNG)

```
root@590cde9ff603:/# dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by TAGC** [comment]
Is this ever actually going to get fixed or even looked at? It's getting pretty annoying to have to manually browse to every single one of my classes defined in a dependency package when debugging.

**Comment by mishra14** [comment]
Tagging @rohit21agrawal  for visibility

**Comment by TAGC** [comment]
@mishra14 Any progress made on this?

**Comment by mishra14** [comment]
@TAGC thanks for the ping. @rohit21agrawal has more context around this code path. 

@rohit21agrawal has this been triaged/considered?

**Comment by rohit21agrawal** [comment]
@TAGC to give you an update, i am working on fixing this issue as we speak. would you be interested in testing out private bits?

**Comment by TAGC** [comment]
Thanks for the update, and sure thing.

**Comment by rohit21agrawal** [comment]
@TAGC i have a private [nupkg ](https://1drv.ms/u/s!AqkZZxvzm4PPhIU0UxTHuxedCuNzgw)with pack fixes.

What you need to do to try it out is use the latest dotnet cli which you can download from :  https://github.com/dotnet/cli/tree/release/2.0.0

Once you have downloaded that, add the above nupkg as a package reference in your project, restore using the dotnet.exe that you downloaded from the above link and then pack.

Let me know if the results are what you expect.

**Comment by rohit21agrawal** [comment]
tagging @brettfo too since he filed the original bug, in case you want to try the fix too.

**Comment by rohit21agrawal** [comment]
@TAGC I am holding off merging my PR for your validation...let me know at the earliest when you can get to it.

**Comment by TAGC** [comment]
It seems to be working, yeah. I will follow up with what I did to check in a second.

**Comment by TAGC** [comment]
I created a reproducible setup to test the behaviour of `dotnet pack --include-source` with and without the NuGet package you linked me.

Both setups are executed in Docker containers based on microsoft/dotnet:2.0-sdk. In the case where I reference the NuGet package, it places `SomeDir` and its contents where they ought to go.

## Broken

```dockerfile
FROM microsoft/dotnet:2.0-sdk
RUN apt-get update
RUN apt-get install -y unzip tree
RUN mkdir test-bad \
    && cd test-bad \
    && dotnet new classlib \
    && mkdir SomeDir \
    && touch SomeDir/OtherFile.cs \
    && dotnet restore \
    && dotnet pack --include-source \
    && cd bin/Debug \
    && unzip test-bad.1.0.0.symbols.nupkg -d unpacked

ENTRYPOINT tree /test-bad/bin/Debug/unpacked
```

**Output**

```
$ docker run --rm broken
/test-bad/bin/Debug/unpacked
|-- SomeDir
|   `-- OtherFile.cs
|-- [Content_Types].xml
|-- _rels
|-- lib
|   `-- netstandard2.0
|       |-- test-bad.dll
|       `-- test-bad.pdb
|-- package
|   `-- services
|       `-- metadata
|           `-- core-properties
|               `-- 9c7bfc9f54a24e7687b8ce3a8dc80975.psmdcp
|-- src
|   `-- test-bad
|       |-- Class1.cs
|       `-- test-bad.csproj
`-- test-bad.nuspec
```

## Fixed

```dockerfile
FROM microsoft/dotnet:2.0-sdk
RUN apt-get update
RUN apt-get install -y wget unzip tree
RUN mkdir -p test-good/dependencies \
    && cd test-good/dependencies \
    && wget 'https://mntz4a.bn1304.livefilestore.com/y4mt1G4ueidJN3Ay2_W6AXJ3CDyTagqMSzFjw98Y59sZhKmNGtwCCQJEP7Kspr-J_96B-bsJymfgTzV1PLJpPpRRvTm8uRP_PS09w-OQq7GXQIrWjUC6yIzB-45cgugdAIcONEv4soKogNwL_Vq2T35jqNkN_E8DA9LHiNojzKXwPCMg0xllGSbbSdUmLaAptSsUfAURc3WQq9ZVR1iBDZQtQ/NuGet.Build.Tasks.Pack.4.4.0-xprivate-7485.nupkg?download&psid=1' \
    && mv "NuGet.Build.Tasks.Pack.4.4.0-xprivate-7485.nupkg?download&psid=1" NuGet.Build.Tasks.Pack.4.4.0-xprivate-7485.nupkg \
    && cd .. \
    && echo '<configuration><packageSources><add key="local-packages" value="dependencies"/></packageSources></configuration>' > NuGet.config \
    && dotnet new classlib \
    && dotnet add package Nuget.Build.Tasks.Pack -v 4.4.0-xprivate-7485 \
    && mkdir SomeDir \
    && touch SomeDir/OtherFile.cs \
    && dotnet restore \
    && dotnet pack --include-source \
    && cd bin/Debug \
    && unzip test-good.1.0.0.symbols.nupkg -d unpacked

ENTRYPOINT tree /test-good/bin/Debug/unpacked
```
**Output**

```
$ docker run --rm fixed
/test-good/bin/Debug/unpacked
|-- [Content_Types].xml
|-- _rels
|-- lib
|   `-- netstandard2.0
|       |-- test-good.dll
|       `-- test-good.pdb
|-- package
|   `-- services
|       `-- metadata
|           `-- core-properties
|               `-- da22d9e0d4054274a3d44c8e904557d5.psmdcp
|-- src
|   `-- test-good
|       |-- Class1.cs
|       |-- SomeDir
|       |   `-- OtherFile.cs
|       `-- test-good.csproj
`-- test-good.nuspec
```

**Comment by rohit21agrawal** [comment]
@TAGC considering this as a validation sign off from you, going to merge changes.
thanks for your feedback and effort you put in for testing this!
