### ISSUE TITLE
Fix default NuGet config sources path on CoreCLR

### ISSUE THREAD

**Issue by ChengTian** [NuGet/Home#472]
The current path we use to create default NuGet config sources is wrong.

We should use local application data folder it. @davidfowl found a good way to get the path from environment variable. See https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs#L653.

See current code: https://github.com/NuGet/NuGet.Configuration/blob/dev/src/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L68-L78

**Comment by yishaigalatzer** [comment]
We can use the environment variable `LOCALAPPDATA` and fallback if its empty to `XDG_DATA_HOME` mono style.

**Comment by yishaigalatzer** [comment]
We think this is fixed already, please verify and close

**Comment by zhili1208** [comment]
it's fixed
