### ISSUE TITLE
Netcore msbuild targets: Customizing Configuration and Platform produces unexpected results

### ISSUE THREAD

**Issue by mlacouture** [NuGet/Home#4720]
dotnet 1.0.0.-4c4-004842

.netcore targets permits to inject customizations to the build by placing a Directory.Build.props in the project directory.  However, this targets file is imported too late, some properties that depend on Configuration and Platform have already been defined so when customizing these properties the other ones get out of sync, for instance DebugSymbols property depend on Configuration and TargetPlatform on Platform.

Directoy.Build.props should be imported before any other targets.

To illustrate the problem do the following:
1. Create a console app: 'dotnet new console'
2. Copy the following code into a Directory.Build.props file and place it in the app dir:
3. Build.  You will get some warning showing the problem.

<Project InitialTargets="ValidateBeforeBuild" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Platform>x86</Platform>
    <Configuration>Release</Configuration>
    <OutputPath>$(MSBuildProjectDirectory)bin\$(Configuration)</OutputPath>
    
    <OutDir>$(OutputPath)</OutDir>
  </PropertyGroup>
  <Target Name="ValidateBeforeBuild">
    <Message Text="Pre-build validation" Importance="high" />
    <Warning Condition="'$(Configuration)' == 'Release' AND (!$(Optimize) OR $(DebugSymbols))" Text="Invalid Configuration: Configuration=$(Configuration) AND Optimize=$(Optimize) DebugSymbols=$(DebugSymbols)" />
    <Warning Condition="'$(Platform)' != 'Any CPU' AND '$(PlatformTarget)' != '$(Platform)'"  Text="Invalid Configuration: Platform=$(Platform) AND PlatformTarget=$(PlatformTarget)" />
    <Warning Condition="'$(OutputPath)' != '$(OutDir)'"  Text="Invalid Configuration: OutputPath=$(OutputPath) AND OutDir=$(OutDir)" />
  </Target>
</Project>

**Comment by mlacouture** [comment]
adding code again as the XML was resolved in my previous post.
` 
<Project InitialTargets="ValidateBeforeBuild" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Platform>x86</Platform>
    <Configuration>Release</Configuration>
   </PropertyGroup>
  <Target Name="ValidateBeforeBuild">
    <Warning Condition="'$(Configuration)' == 'Release' AND (!$(Optimize) OR $(DebugSymbols))" Text="Invalid Configuration: Configuration=$(Configuration) AND Optimize=$(Optimize) DebugSymbols=$(DebugSymbols)" />
    <Warning Condition="'$(Platform)' != 'Any CPU' AND '$(PlatformTarget)' != '$(Platform)'"  Text="Invalid Configuration: Platform=$(Platform) AND PlatformTarget=$(PlatformTarget)" />
  </Target>
</Project>
`

**Comment by dsplaisted** [comment]
I've filed https://github.com/dotnet/sdk/issues/924 for this, so feel free to close the issue here.
