### ISSUE TITLE
C++ projects should use package cache under %USERPROFILE%\.nuget instead of solution cache

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#4723]
NuGet product used: Visual Studio UI
NuGet version (x.x.x.xxx): 4.0.0.2286
VS version (if appropriate): VS 2017

1. Create a blank C++ UWP project.
2. Add a reference to some NuGet package.
3. Examine <SolutionRoot>\packages.

**Expected:**  Directory does not exist.  User's package cache at %USERPROFILE%\.nuget\packages is used instead.

**Actual:** Referenced package is copied to <SolutionRoot>\packages.

**Comment by emgarten** [comment]
I believe this is caused by C++ using packages.config still.

Once the project system adds support for VSProject4 and PackageReference is used with UWP this will be solved.

This should all happen without changes to NuGet.
