### ISSUE TITLE
Duplicate package produced when NuspecFile and IncludeSymbols=true are set

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#4726]
**Repro**
```xml
<PropertyGroup>
   <IncludeSymbols>true</IncludeSymbols>
   <NuspecFile>MyPackage.nuspec</NuspecFile>
</PropertyGroup>
```
msbuild /t:Pack

**Expected**
Just one package created, MyPackage.nupkg

**Actual**
Two identical packages created:
MyPacakge.nupkg
MyPackage.symbols.nupkg

The symbols package is unnecessary as the nuspec defines which files to include.

cc @rohit21agrawal

**Comment by emgarten** [comment]
@natemcmaster are you intending this flag to mean add the pdbs into the normal nupkg?

Symbol packages are typically pushed to a symbol feed and the normal nupkg does not include the symbols.

I think this is slightly more confusing now that there are flags for both symbols and source, I believe in nuget.exe before there was only one option and it included both symbols and source into the symbols nupkg, which made it quite a bit different.

**Comment by emgarten** [comment]
Also, I wouldn't expect the non-symbols nupkg to contain pdb files. If IncludeSymbols is adding those it seems like a bug.

**Comment by natemcmaster** [comment]
> are you intending this flag to mean add the pdbs into the normal nupkg?

Yes, that is how we used it. Generally when we have set NuspecFile, we are doing some kind of non-standard layouts, like packages with MSBuild tasks and or multiple assemblies included.

**Comment by emgarten** [comment]
@natemcmaster that makes sense, it seems like IncludeSymbols should be ignored with a nuspec file then. Is that what you expect, or are you relying on this partially?

**Comment by rohit21agrawal** [comment]
This is a bug alright. IncludeSymbols and IncludeSource should have no meaning when packing a nuspec

**Comment by natemcmaster** [comment]
I'm closing this because it turns out there are ways to make a custom nuspec and a IncludeSymbols work. We don't need changes here anymore.

**Comment by XtremeOwnageDotCom** [comment]
> I'm closing this because it turns out there are ways to make a custom nuspec and a IncludeSymbols work. We don't need changes here anymore.

Be pretty nice, if you included a few details...

Its 6 years later, and apparently there are still issues with symbol packages.... 

To the point where the pipelines task explicitly excludes symbols by default.

```
packagesToPush - Path to NuGet package(s) to publish
Input alias: searchPatternPush. string. Required when command = push. Default value: $(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg.
```
