### ISSUE TITLE
NuGet restore fails when two projects have the same PackageId

### ISSUE THREAD

**Issue by memontic-ms** [NuGet/Home#4730]
## Details about Problem
NuGet restore will fail if projects do not have unique PackageId values - but only if PackageReferences are used. Identical PackageId values do not cause an issue when project.json files are used instead.

NuGet.exe version: 4.0.1.2329
VS version: 15.0.0+26228.0.d15rel
MSBuild version: 15.1.548.43366
NuGetizer 3000 for VS2017 VSIX installed

## Repro
1. Create solution with one .vcxproj and one .nuproj 
2. Add a project reference in the .nuproj to the .vcxproj
3. Have the .vcxproj use PackageReference and the .nuproj use either project.json or PackageReference
4. Set the PackageId in the .vcxproj to match exactly the PackageId in the .nuproj (I have it set to "NuGetPackage")
5. Run Nuget.exe restore from the command line --> restore fails with error "System.InvalidOperationException: Ambiguous project name 'NuGetPackage'"

However, if instead the .vcxproj uses a project.json the restore does not fail. So project.json allows for duplicate PackageId values while PackageReference does not.

### Verbose Logs
The restore is fine until it tries to restore the second project: [NuGetRestoreLog.txt](https://github.com/NuGet/Home/files/812459/NuGetRestoreLog.txt)

### Sample Project
Comments inline in the sample's Foo.vcxproj and NuGetPackage.nuproj
[AmbiguousRepro.zip](https://github.com/NuGet/Home/files/812560/AmbiguousRepro.zip)

**Comment by bbowman** [comment]
@kzu may be interested here as well. Looks like the package id prop is also used for restore which may be tricky.

**Comment by emgarten** [comment]
Projects must have unique ids for transitive scenarios such as PackageReference. This ensures that projects and packages are treated the same, specifically that everything works the same when things are packages as they do when they are all packaged.
