### ISSUE TITLE
Deprecation and Security warnings in NuGet.exe/Visual Studio and NuGet.org

### ISSUE THREAD

**Issue by ghuntley** [NuGet/Home#4731]
Howdy - any plans to introduce this concept from the nodejs ecosystem into dotnet?

![image](https://cloud.githubusercontent.com/assets/127353/23490245/1377315a-ff43-11e6-8c96-74e4ca1833ac.png)

1) Provide way for package author to mark a package as deprecated.
2) Provide way for package consumer to receive this notice in Visual Studio/NuGet.exe
3) Provide way for package author to mark a package as containing a security issue and specify the reason.
4) Provide way for package consumer to receive this notice and reason in Visual Studio/NuGet.exe

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Home/issues/2867

**Comment by emgarten** [comment]
Related: https://github.com/NuGet/Home/issues/5856
