### ISSUE TITLE
ApiKey as an Http header is not in the Request from  Nuget-Clinet 

### ISSUE THREAD

**Issue by ryangle** [NuGet/Home#4732]
## Details about Problem

NuGet product used NuGet.exe and VS UI 
NuGet version:v3.5.0 and v4.0.0-rc4

dotnet.exe --version (if appropriate):

VS version :vs2017-rc 

## Detailed repro steps so we can see the same problem

 I set a apikey use the command ` nuget setaipke xxxx:xxxx -Source xxxxxxx`.
Then,when I restore the package from the source which can't read by anonymous，the response 
is empty。
There is no X-NuGet-ApiKey header in the HTTP Request ,I use Fiddler to debug the traffic.

**Comment by emgarten** [comment]
@RyanHuangWork the API key is only used for the ``push`` command. It is never sent as a feed credential.

**Comment by ryangle** [comment]
@emgarten thanks for your reply.
I use the JFrog Artifactory be a nuget repository in my scenario,so I can remove the read permission of anonymous.
I didn't find a way to request packages with my credential.

**Comment by emgarten** [comment]
@RyanHuangWork use the sources command to add a username/password

https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#sources

**Comment by ryangle** [comment]
@emgarten Thank you very much
