### ISSUE TITLE
The ‘Installed’ drop down in solution PM UI show incorrectly with multiple projects contained

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4733]
**NuGet Version:** NuGet 4.3.0-Beta1-2335
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS1_Release 14393.949.170224-1924

**Repro Steps:**
1. Create a solution with two C# Console Applications via VS.
2. Open the **‘Manage NuGet Package for Solution…’**.
3. Click ‘Browse’ tab and select package ‘Newtonsoft.Json’.
4. Check project1 in the right pane and click install button.
5. **Uncheck** project1 and **check** project2. 

**Expected Result:**
The ‘Installed’ drop down for project2 should show: not installed as below.
![correct](https://cloud.githubusercontent.com/assets/20632625/23501296/519a6a4e-ff6e-11e6-82b3-424587c36011.png)

**Actual Result:**
The ‘Installed’ drop down for project2 show the version which had just been installed into project1 as below. That doesn't make sense since I have not installed any package into project2 yet.
![incorrect](https://cloud.githubusercontent.com/assets/20632625/23501372/95638e2c-ff6e-11e6-96c8-55b01a15521e.png)

**Note:**
1. It also repro on Dev14 U3 25431.01 (NuGet Client 3.4.4.1321).
2. It also repro on Dev14 U3 25431.01 + NuGet Client 3.5.0-rtm-1938.
3. It repro on D15Rel 26228.00 + NuGet Client 4.1.0-rtm-2336.

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
That installed drop down is showing what version is currently installed in the solution, not specific to the project selected in the dropdown. If there are multiple versions installed you see it says something different: 
![image](https://github.com/user-attachments/assets/58ef6c08-3175-4c0a-842d-98709a815bf0)
