### ISSUE TITLE
Nuget install Packages + VS TransformXML

### ISSUE THREAD

**Issue by mhsmith01** [NuGet/Home#4735]
Also posted discussion on stackOverflow: http://stackoverflow.com/questions/41944337/how-to-use-nuget-install-packages-vs-transformxml

The issue is when installing nuget packages, changes are made to the end file like App.config which are lost once the file is generated from its App.base.config + App.MyEnv.config.  Much of what I have researched deals with setting up the package directly with XDT but all this means is installs/updates will continue to target the wrong config and be lost once that file is regenerated.  Is their anyway to redirect the installs/updates from nuget packages to effect a target file like App.base.config?

Thanks

**Comment by emgarten** [comment]
Thank you for the suggestion and scenario, there is currently no additional work planned for XDT transforms.
