### ISSUE TITLE
Need API to determine root of NuGet package that contains a specified file

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#4736]
I'd like a NuGet.VisualStudio API that, given a file path, will return the path to the root directory of the NuGet package containing that file.  It should support packages.config, project.json, and PackageReference scenarios.

So, for example:

**Input:** c:\users\erikd\.nuget\packages\erikdwpfsdk\1.0.3\lib\net40\WpfSdk.dll
**Result:** c:\users\erikd\.nuget\packages\erikdwpfsdk\1.0.3

**Input:** c:\temp\WpfApp1\packages\ErikWpfSdk.1.0.3\lib\net40\WpfSdk.dll
**Result:** c:\temp\WpfApp1\packages\ErikWpfSdk.1.0.3

**Input:** c:\foo.txt
**Result:** null (not in a NuGet package)

**Comment by joelverhagen** [comment]
This is the working idea I have. This comment may be edited as the idea evolves.

```csharp
namespace NuGet.VisualStudio
{
    /// <summary>
    /// An interface to allow fetching the package directory containing a given package asset path.
    /// </summary>
    public interface IVsPackageDirectoryProvider
    {
        /// <summary>
        /// Fetch all of the package directories containing the provided asset paths. If the provided project does not
        /// support NuGet, an empty result is returned. Null is not returned. If any of the asset paths are not within
        /// a package directory at all or if they correspond to an package directory different than the project's own
        /// package directory, a null package directory path is returned.
        /// </summary>
        /// <param name="project">The DTE project.</param>
        /// <param name="assetPaths">A <see cref="string"/> sequence which are absolute paths to package assets.</param>
        /// <returns>The package directory information.</returns>
        /// <example>
        /// Suppose the project is a packages.config project and the following asset paths are provided:
        /// 
        /// - C:\src\MyProject\packages\NuGet.Versioning.3.5.0-rc1-final\lib\net45\NuGet.Versioning.dll
        /// - C:\path\to\non\package\assembly\Newtonsoft.Json.dll
        /// - C:\src\MyOtherProject\packages\NuGet.Core.2.12.0\lib\net40\NuGet.Core.dll
        /// - C:\src\MyProject\packages\Autofac.3.5.2\lib\net40\Autofac.dll
        /// - C:\src\MyProject\packages\Autofac.3.5.2\lib\net40\Autofac.Fake.dll
        /// 
        /// The result will be:
        /// 
        /// - C:\src\MyProject\packages\NuGet.Versioning.3.5.0-rc1-final
        /// - null
        /// - null
        /// - C:\src\MyProject\packages\Autofac.3.5.2
        /// - C:\src\MyProject\packages\Autofac.3.5.2
        /// </example>
        Task<IVsPackageDirectories> GetPackageDirectoriesAsync(Project project, IEnumerable assetPaths);
    }

    /// <summary>
    /// An interface which contains package path information returned from <see cref="IVsPackageDirectoryProvider"/>.
    /// </summary>
    public interface IVsPackageDirectories
    {
        /// <summary>
        /// A <see cref="string"/> sequence which are absolute paths to the package directories. Duplicates or null
        /// strings can be returned. An empty sequence is also possible.
        /// </summary>
        IEnumerable PackageDirectoryPaths { get; }
    }
}
```

**Comment by debonte** [comment]
In my case I need to match the output values to the corresponding input value (ex. output[1] maps to input[1]).  If we think this will be common, I think the resulting collection should be a collection of KeyValuePair<string, string> or Tuple<string, string>.  Otherwise those consumers would need to do an input.Zip(output) or something along those lines.

**Comment by joelverhagen** [comment]
I think `KeyValuePair<string, string>` is right, where the key is the DLL (or any asset) path and the value is either the full path to the package directory or null.

If the project does not support NuGet at all, I think all of the values (of the `KeyValuePair`) should be null. Alternatively, the method could just return null.

**Comment by alpaix** [comment]
Couple of notes:
1. API for a single asset file would be clearer and would not require extra data structure. What was the motivation behind this design?
2. I don't feel comfortable with utilizing `EnvDTE.Project` as a key. The _interop_ API should not have external dependencies. Project unique name (full path) should have been used instead.

Thoughts?

**Comment by joelverhagen** [comment]
> API for a single asset file would be clearer and would not require extra data structure. What was the motivation behind this design?

Single asset file does not cover packages.config. We'd need some something else for that case. This API can support all project types. Also, 0pening up the entire assets file seems risky... that seems like too much information for this scenario. The assets file has also revved many time over the past couple years. 

Another way to simplify is to return an `IEnumerable<KeyValuePair<string, string>>` from the method directly, rather than returning `IVsPackageDirectories`.

> I don't feel comfortable with utilizing `EnvDTE.Project` as a key. The _interop_ API should not have external dependencies. Project unique name (full path) should have been used instead.

Seems like a good point, but we have many other IVs APIs that accept DTE project object, e.g.
https://github.com/NuGet/NuGet.Client/blob/26372c4bb50c710762481230b4841535a67285b7/src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPathContextProvider.cs#L68

The full path might be easier for a variety of callers to get though. @debonte mentioned that his side actually uses `IVsHierarchy`. How would we look up projects by full path? I don't see how this would be done on `ProjectSystemCache`.

**Comment by debonte** [comment]
> @debonte mentioned that his side actually uses  IVsHierarchy .

While we use IVsHierarchies now, we hope to move to AnyCode in the future.

> API for a single asset file would be clearer and would not require extra data structure. What was the motivation behind this design?

Maybe I misinterpreted the question from @alpaix, but I thought he was asking why GetPackageDirectoriesAsync takes (and returns) a collection.  Why it doesn't just get you the package directory for a single file.  @joelverhagen had told me that this API would need to do a lot of expensive work (file parsing?) that could be reused across multiple inputs.  So taking/returning a collection allowed the per-input cost to be lower.  In my use case I'll be passing in all of the project's reference assemblies in one shot.

That said, maybe there should be an overload of this method that takes a single path?

> If the project does not support NuGet at all, I think all of the values (of the  KeyValuePair ) should be null. 

For simplicity, I'd favor a collection where all of the package paths are null rather than a null collection.  If users need a "Does this project support NuGet?" API, it should be a different API.

**Comment by alpaix** [comment]
> While we use IVsHierarchies now, we hope to move to AnyCode in the future.

I'm quite convinced we should stick to a project's unique name/full file path as we did with other new APIs. 

>  So taking/returning a collection allowed the per-input cost to be lower.

Premature optimization should never be a driving factor for public extension API. Let's figure exact scenario and design the best API for it. 

My another concern for collection input was error handling, namely responding with an error result for a particular item in it.

> If users need a "Does this project support NuGet?" API, it should be a different API.

Excellent idea! Do you need this API? Should we consider designing it now as a placeholder? 
Do you know of any other queries that'd help us factoring our API?

**Comment by debonte** [comment]
> Excellent idea! Do you need this API? 

No, not at the moment.  If you want to do some brainstorming about new APIs that might be good to add in the future, we should include LutzR.
