### ISSUE TITLE
Inconsistent `dotnet nuget push` - or by design?

### ISSUE THREAD

**Issue by per-samuelsson** [NuGet/Home#4738]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

* NuGet CLI: 4.0.0.2275, **and**
* `dotnet nuget`, showing NuGet version 4.0.0.0

dotnet.exe --info
```
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:  \dotnet-dev-win-x64.1.0.0-rc4-004771\sdk\1.0.0-rc4-004771
```

## Detailed repro steps so we can see the same problem
1. Having empty folder `/packages/foo`, push a package there using
    * `nuget push my.nupkg -s file:///path/to/packages/foo`. 
2. Instead of [1], also starting from an empty folder, do **first**
    * `[NuGet 4.x standard client] add another.nupkg -s /packages/foo`, and **then**
    * `nuget push my.nupkg -s file:///path/to/packages/foo`

After a lone [1], the `/foo` folder now consist of my plain `my.nupkg` (with no given 3.x-ish hierarchical structure). But after a sequence of [2.1] + [2.2], that same command (i.e. [2.2]) will install it properly in the hierarchical structure setup by [2.1].

This inconsistency is a bit tricky to work around, and also will affect consuming clients. For example, adding the package using only [1], clients seem unable to list it (tried both 3.x and 4.x client for that).

Is this by design or should be considered a bug?

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
