### ISSUE TITLE
Packages.config projects are detected as Legacy CSProj

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4739]
**NuGet Version:** NuGet 4.3.0-beta1-2346 **(Insertable)**
**VS Version:** D15Rel 26228.00
**OS Version:** Windows 10 RS2_Release 15048.0.170228-1522

**Repro Steps:**
1.	New a Visual C#->ASP.NET Web Application (.NET Framework) -> Web Forms project.
2.	Open the **‘Reference’** node under solution and build the solution after creating project successfully.

**Expected Result:**
The solution should build successfully.

**Actual Result:**
There are many reference component warnings under ‘Reference’ node and the solution build failed with an error and many warnings as below screenshot.
 
![untitled](https://cloud.githubusercontent.com/assets/20632775/23543703/59f0b520-002e-11e7-93be-2098a041a775.png)

**Notes:**
1. The warnings have exist in error list after creating ASP.NET Web Application (.NET Framework)->**Web Forms/MVC/Web API/Single Page Application** projects, but the **MVC/Web API/Single Page Application** projects have no error after building solution.
2. The issue **not** repro on **D15Rel 26228.00 (NuGet 4.0.0-rtm-2323)** and **D15Rel 26228.00 + NuGet 4.1.0-rtm-2343.**

**Comment by emgarten** [comment]
The template is hard coded to have references. However the template wizard added PackageReferences instead of extracting the packages to the packages folder.

**Comment by emgarten** [comment]
Opened https://github.com/NuGet/Home/issues/4748 for further tracking on this scenario to ensure we don't enable this on accident.

**Comment by emgarten** [comment]
It looks like Legacy CSProj is winning for packages.config project types, and that is causing all of these issues.

**Comment by emgarten** [comment]
@jainaashish I'm moving this issue to you since it looks rooted in Legacy CSProj, let me know if you uncover anything else. I believe this issue is causing the problems on both 4.1.0 and 4.3.0
