### ISSUE TITLE
Nuget.exe -ExcludeVersion parameter incorrect behavior

### ISSUE THREAD

**Issue by rymeskar** [NuGet/Home#4744]
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: 3.4.4.1321
OS version:  win10 v1607 (14393693):

1. ./nuget.exe install $nugetPackage -ExcludeVersion -Version 1.0.0.0
2. Leave the installed package in the folder
3. From the same folder ./nuget.exe install $nugetPackage -ExcludeVersion -Version 1.0.0.10
4. Nuget.exe won't download the new version and will just use the one in the current folder (whatever it is)

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Home/issues/3957
