### ISSUE TITLE
Are contentFiles supported for SDK csproj based .NET Core Console Applications?

### ISSUE THREAD

**Issue by jpierson** [NuGet/Home#4745]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 3.4.3.855

VS version (if appropriate):

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26206.0 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-50000-00000-AA907
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017 RC   00369-50000-00000-AA907
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA907
Microsoft Visual C# 2017 RC

Visual C++ 2017 RC   00369-50000-00000-AA907
Microsoft Visual C++ 2017 RC

Visual F# 4.1   00369-50000-00000-AA907
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00201.7
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30206.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30126.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.3.41102.00
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61701.270
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development

Visual Studio Tools for Universal Windows Apps   15.0.26206.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

OS version (i.e. win10 v1607 (14393.321)): 10.0.14393 N/A Build 14393

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Create a nuget package using directory convention to add contentFiles.
2. Reference the package from a .NET Core Application using latest VS 2017RC

Expected results: I should see the contentFiles in my project build output (not sure exactly where that would be).
Actual results: The files under contentFiles in the package don't seem to turn up anywhere in the project or in the build output or anywhere I can find in the intermediate files.

**Comment by emgarten** [comment]
@jpierson check the props file under obj, if the contentFiles are valid for the project they should be added there.

As a test try adding ``contentFiles/any/any/a.txt`` to the package and ensure that it shows up, this should always be used.

If none of that works please share the package or some repro steps on creating a similar package and project.

**Comment by jpierson** [comment]
@emgarten, ok I'll check. I tried something very similar to `contentFiles/any/any/a.txt` but I wasn't checking this props file. Looking at the props file as is with out the `any/any` structure just looks like this.

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">C:\Users\me\Documents\Visual Studio 2017\Projects\DeleteMe1\DeleteMe1\obj\project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\me\.nuget\packages\</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.0.0</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
</Project>
```

**Comment by emgarten** [comment]
@jpierson with ``any/any`` it shows up?

**Comment by emgarten** [comment]
Can you share the package entry from project.assets.json from both the libraries section and the targets section.

**Comment by jpierson** [comment]
Ok, that seems to be the ticket. My mistake was a combination of not knowing to look at that props file along with not having my content packaged under a `lang`/`framework` hierarchy.

Thanks for your help @emgarten, I'll close this issue.

**Comment by emgarten** [comment]
Glad it worked! The structure differs from the older content folder and this isn't very obvious.
