### ISSUE TITLE
IVsPathContextProvider.CreateAsync returns incorrect value if project uses packages.config

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#4747]
@joelverhagen noticed this issue when we were talking yesterday.  Just wanted to make sure it was recorded.  He may want to correct my description of the problem.

IVsPathContext contains a UserPackageFolder and a collection of FallbackPackageFolders.  Neither of those are applicable to packages.config scenarios.  However if you call IVsPathContextProvider.CreateAsync on a packages.config project you get back a non-null value.

So the API should be updated to either:
1. Return a null value in this case.  It would be nice to support packages.config with this API though.
2. Place the solution-level package store path in IVsPathContext.UserPackageFolder even though that's misleading since the layout of UserPackageFolder directories (%USERPROFILE%\.nuget\packages) is different from solution-level caches.  For example, there's no version directory in the packages.config case.  (...\packages\mypackage\**1.0.0**\packagecontents vs. ...\packages\mypackage\packagecontents)
3. Improve/extend the API somehow to return the packages.config cache location in a way that makes it clear that it is not a UserPackageFolder.

**Comment by nkolev92** [comment]
Hey @debonte, 

Given that https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility/IVsPathContextProvider2.cs was added (which is your 3rd point), do you think this issue is safe to close?

**Comment by debonte** [comment]
@nkolev92, yes. Thanks!
