### ISSUE TITLE
Nuget should drop the dot in a few resources from src/NuGet.Core/NuGet.Commands/Strings.resx 

### ISSUE THREAD

**Issue by NinoFloris** [NuGet/Home#4750]
Currently a dotnet restore looks like this:

```
  Lock file has not changed. Skipping lock file write. Path: /PATHTOPROJECT/project.assets.json
  Restore completed in 10.14 sec for /PATHTOPROJECT/project.csproj.
```

Take note of the first line not having a dot after the path name, the second line however does.

This interferes with quite a few (and recently also vscode) click to go to file tools as they cannot find the file:
```
/PATHTOPROJECT/project.csproj.
```
They can however find 
```
/PATHTOPROJECT/project.csproj
```

It's very minor but an easy fix 

Restore completed:
https://github.com/NuGet/NuGet.Client/blob/3462a7d2a7f6c66bf364c1ec3b7a538f14e7bc92/src/NuGet.Core/NuGet.Commands/Strings.resx#L239
Restore failed:
https://github.com/NuGet/NuGet.Client/blob/3462a7d2a7f6c66bf364c1ec3b7a538f14e7bc92/src/NuGet.Core/NuGet.Commands/Strings.resx#L244

(And possibly others like `Restoring packages for  /PATHTOPROJECT/project.csproj...`)

**Comment by emgarten** [comment]
Thank you for the suggestion, based on the feedback received so far we do not plan to fix this issue.
