### ISSUE TITLE
[Potential bug] Dependency in group with targetFramework alias not honored

### ISSUE THREAD

**Issue by BrainCrumbz** [NuGet/Home#4754]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe 

NuGet version (x.x.x.xxx):  3.5.0.1938

dotnet.exe --version (if appropriate): 1.0.0-preview2-003131

VS version (if appropriate): not related. VS Community 2015 14.0.25431.01 Update 3.

OS version (i.e. win10 v1607 (14393.321)): win10 x64 v1607

Worked before? If so, with which NuGet version: not related to different NuGet versions

A package ([NSpec v3.0.2](https://github.com/nspec/NSpec/tree/v3.0.2) in detail) is targeting both *netstandard1.6* and *net451*. When targeting netstandard1.6, it also depends on *System.Reflection.TypeExtensions 4.1.0*. Hence its nuspec file recently included a dependency on that assembly within a group using a targetFramework with **netstandard** alias (taken from [Supported Frameworks](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks)).

When trying to restore a client project depending on that NSpec v3.0.2, the restore fails due to `System.Reflection.TypeExtensions` not being available for .NET Framework 4.5 but only for 4.6 and later. The fact is that the restore process should not try to install that for .NET Framework at all, as it is only required for .NET Core target.

After editing the package nuspec file in order to have a specific targetFramework, **netstandard1.6**, and publishing a new version, [NSpec v3.0.3](https://github.com/nspec/NSpec/tree/v3.0.3), the issue is gone.

I checked the actual .nupkg contents and its zipped nuspec file. When using the targetFramework alias, **netstandard**, the actual condition was expressed as `targetFramework=".NETStandard0.0"`, which looks somehow strange (but maybe is ok for you). When instead there was a specific targetFramework, **netstandard1.6**, the actual condition in zipped content was `targetFramework=".NETStandard1.6"`.

Although the issue happens during package restore phase, I'm posting this here as it seems that by changing something in NuGet nuspec file the issue is fixed. Please feel free to move to a more appropriate repository if needed. 

Disclaimer: we're contributors to NSpec OSS project.

## Detailed repro steps so we can see the same problem

1. Download a copy of [NSpec github repo](https://github.com/nspec/NSpec/) at version tagged [v3.0.2](https://github.com/nspec/NSpec/tree/v3.0.2)

1. Locally edit `examples/DotNetTestSample/test/LibrarySpecs/project.json` so to require NSpec **3.0.2** (and not 3.0.1 as it is originally)

1. Restore the same test project in `examples/DotNetTestSample/test/LibrarySpecs/` from command line with `dotnet restore`, or from Visual Studio *Restore Packages* menu command.

## Other suggested things

1. Download a copy of the same repository at version tagged [v3.0.3](https://github.com/nspec/NSpec/tree/v3.0.3) to see a regular behaviour when pointing to a package version with the fix included.

### Verbose Logs

None.

### Sample Project

See steps above.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
