### ISSUE TITLE
Improve Package Ref for Legacy CSProj

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#4757]
buffer task for unknown problems in this space.

**Comment by tomkuijsten** [comment]
Well I have one. I created two solutions, both with one project. The first sln has a .net core project, the other a .net framework project. In the core I added a floating dependency version which works fine, but in the .net framework project I got this message while building:

> Error occurred while restoring NuGet packages: '9.*' is not a valid version string.

I can't find any limitation in the [floating version documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution) for "legacy" projects.

**Comment by jainaashish** [comment]
Merged to release-4.1.0-rtm 4427dfdb4ad870889be69c1b4bffe4df3c89aa2a
