### ISSUE TITLE
TPMinV check should work for CPP UWP

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4765]
1. file new CPP UWP app TPM = RS2, TPMinV = TH2, having project.json
2. install a nupkg targeting RS1

Expected - install fails
Actual - Install succeeds

This should work from both VS and CLI.

**Comment by emgarten** [comment]
@karann-msft does this work when you update project.json to contain the correct TFM?  Is CPP + UWP + project.json an officially supported scenario?

**Comment by karann-msft** [comment]
The TPMinV check is a net new UWP scenario that should work for all UWP projects irrespective of the pc, pj or pr.

**Comment by nkolev92** [comment]
Closing this as stale. 
CPP projects use a different version compared to CS.
