### ISSUE TITLE
Option that causes you to get prompted on the package format is awkwardly worded

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4766]
It took me 2 or 3 times to read this option to understand what it meant:

![image](https://cloud.githubusercontent.com/assets/1103906/23686321/fe97a9cc-03fc-11e7-8b33-766bf6b8b679.png)

I propose something a little clearer such as:

`Prompt me to choose a format the first time I install a package into a project"

**Comment by emgarten** [comment]
Moving to @anangaur/@karann-msft  for the new text to use in this dialog.

**Comment by karann-msft** [comment]
Thanks for the feedback @davkean. I am closing the issue at the moment since we haven't heard this feedback more widely. We can revisit this decision in the future.
