### ISSUE TITLE
Nuget.Build.Tasks.Pack crashes when used with Mono MSBuild

### ISSUE THREAD

**Issue by borgdylan** [NuGet/Home#4770]
## Details about Problem

NuGet product used: Nuget.Build.Tasks.Pack

NuGet version: 4.0 RTM

OS version (i.e. win10 v1607 (14393.321)): Ubuntu 16.10 for x64

Mono version: 4.9.x (master branch)

MSBuild version: 15.2 (mono variant from mono/msbuild repo, xplat-master branch)

## Detailed repro steps so we can see the same problem (needs mono MSBuild)

1. Build a project that used the "Microsoft.Net.Sdk" SDK.

2. Try to pack it with ```msbuild /t:Pack```.

**Comment by borgdylan** [comment]
The crash involves a ```MissingMethodException``` in the ```PackageSpec``` property getter on the ```LockFile``` class within ```NuGet.ProjectModel.dll```.

**Comment by emgarten** [comment]
Use ``dotnet pack`` to pack NETCore projects

The error here looks like a mismatch nuget assemblies with msbuild.

**Comment by borgdylan** [comment]
I cannot in that case as it is a a ```net46``` project. The MSBuild that comes with the CLI lacks support for non-core TFMs.

**Comment by emgarten** [comment]
@borgdylan can you debug and find where the mismatch of nuget assemblies is coming from? Does the msbuild you are using contain an older copy of NuGet.ProjectModel.dll than the SDK?

**Comment by borgdylan** [comment]
It could be that is the case. I need to work with @radical to see where he is sourcing the dlls he installs for the restore task. The conflict is between what is deployed by the restore task support and the pack support i.e. a conflict between the ```Microsoft.NuGet.Build.Tasks``` and ```Nuget.Build.Tasks``` packages. It would have been simpler if both tasks were part of the same package.

**Comment by radical** [comment]
@borgdylan Could you please try the latest `xplat-master`? The assemblies were missing but have been added now. If it does not fix the issue, then could you please file a bug at http://bugzilla.xamarin.com with a test project?

**Comment by borgdylan** [comment]
@radical for pack support I still have to bring in the pack support which may likely conflict again.

**Comment by radical** [comment]
These are the nuget assemblies being included with the sdk with their assembly versions:

```
= Microsoft.NET.Sdk/tools/net46/NuGet.Common.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Configuration.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.DependencyResolver.Core.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Frameworks.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.LibraryModel.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Packaging.Core.Types.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Packaging.Core.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Packaging.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.ProjectModel.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Protocol.Core.Types.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Protocol.Core.v3.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Repositories.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.RuntimeModel.dll
Version:       4.0.0.0
= Microsoft.NET.Sdk/tools/net46/NuGet.Versioning.dll
Version:       4.0.0.0
```

The sdk is sourced from `Microsoft.NET.Sdk 1.0.0-alpha-20170224-6` nuget package.

**Comment by borgdylan** [comment]
@radical It worked! I had tried using the tools directory from the latest Sdk that was released up on NuGet. That conflicted. Your NEW binaries did not conflict. FYI if you would like to add pack support I can tell you what I did to install the pack sdk.

**Comment by borgdylan** [comment]
With this I can remove .NET CLI from my machine and talk to msbuild directly.
