### ISSUE TITLE
dotnet add package fails when tool is installed

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4771]
> From @johnkors at https://github.com/dotnet/cli/issues/5955

## Steps to reproduce
Using a ASP.NET Core app with the following tool (haven't tested if it's this tool specific, or tools in general).

```
<DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
```

## Expected  behavior
```
λ dotnet add package newtonsoft.json
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing C:\Users\johkor\AppData\Local\Temp\tmp3AEE.tmp
info : Adding PackageReference for package 'newtonsoft.json' into project 
info : PackageReference for package 'newtonsoft.json' version '9.0.1' added to file 'C:\code\my.csproj'.
```
## Actual behavior
```
λ dotnet add package newtonsoft.json
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing C:\Users\johkor\AppData\Local\Temp\tmp8166.tmp
info : Adding PackageReference for package 'newtonsoft.json' into project 'C:\code\my.csproj'.
error: Invalid restore input. Invalid restore input. DotnetCliToolReference-BundlerMinifier.Core Input files: C:\code\my.csproj.
```

## Environment data
`dotnet --info` output:
```
λ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

**Comment by mishra14** [comment]
@emgarten : This looks like that restore is complaining about the tools reference. Is this a known issue?

**Comment by emgarten** [comment]
@mishra14 haven't seen this before, it typically says what is invalid in the spec. There must have been an unexpected fatal error.

**Comment by shanselman** [comment]
I am seeing this locally also. 

* Add ANY tool before you add a reference
* Then try to add a reference "`dotnet add package Newtonsoft.Json`"

```
C:\Users\scott\Desktop\toolstest>dotnet add package Newtonsoft.Json
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing C:\Users\scott\AppData\Local\Temp\tmp6F09.tmp
info : Adding PackageReference for package 'Newtonsoft.Json' into project 'C:\Users\scott\Desktop\toolstest\toolstest.csproj'.
error: Invalid restore input. Invalid restore input. DotnetCliToolReference-BundlerMinifier.Core Input files: C:\Users\scott\Desktop\toolstest\toolstest.csproj.
```

**Comment by tulis** [comment]
In my case, I added AWS Lambda Tool before adding ImageSharp

```
C:\Users\m\Documents\atg\src\atg> dotnet add package ImageSharp
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing C:\Users\admin\AppData\Local\Temp\tmpBC11.tmp
info : Adding PackageReference for package 'ImageSharp' into project C:\Users\m\Documents\atg\src\atg\atg.csproj'.
error: Invalid restore input. Invalid restore input. DotnetCliToolReference-Amazon.Lambda.Tools Input files: C:\Users\m\Documents\atg\src\atg\atg.csproj.
```

**Comment by johnkors** [comment]
Anyone adding a tool first (or using a template that includes a tool, like mvc core + BundlerMinifier) will be subject to this behaviour and `add package` won't work. Not a great on-boarding experience for the CLI here.

I'll leave the priorities up to you, but shouldn't this issue at least be marked as a bug..?

**Comment by shanselman** [comment]
Yes, this is super annoying, and we also need "dotnet tool add" to have symmetry.

**Comment by mishra14** [comment]
This has been fixed in NuGet with https://github.com/NuGet/NuGet.Client/commit/34e1a9b070905d105d1e161aa374b3c6ff852e8b.

This should reflect with NuGet's next insertion into dotnet cli-sdk. Keeping this bug open till then.

**Comment by johnkors** [comment]
Thanks, @mishra14 . How do I track the updating of NuGet.Client in the SDK? Do you have a linked issue in another repo?

**Comment by mishra14** [comment]
@johnkors : you can track the status of the OR into sdk at https://github.com/dotnet/sdk/pull/1101

We have already inserted into cli.

**Comment by mishra14** [comment]
This should be fixed post insertions into cli and sdk. Closing.

**Comment by johnkors** [comment]
Are there any plans to add what @shanselman mentioned about `dotnet add tool <toolname>` or similar..? Would be super useful. If yes, any GitHub issue I mayfollow..?

Just created my first [CLI tool to track usage of known vulnerable NuGets](https://blogg.blank.no/hunting-for-vulnerable-nugets-in-net-core-3c37f30e467a) - would be neat if the install experience was a bit better!

**Comment by mishra14** [comment]
you can follow this bug: https://github.com/NuGet/Home/issues/4901
