### ISSUE TITLE
NuGet can´t handle two (or more?) Visual Studio Projects (*.csproj) in same folder (with shared packages.config)

### ISSUE THREAD

**Issue by WolfgangMeindl** [NuGet/Home#4775]
Hi, wie use LLBLGen, which generates two projects in one folder. 
NuGet can´t handle that. 

NuGet product used (NuGet Package Manager in Visual Studio)

NuGet version (x.x.x.xxx): (i dont know, where can i see it? i thought it´s integrated somwhere in VS?) 

VS version (Visual Studio 2012 and 2015):

OS version (Windows 8):

Worked before? no

## Detailed repro steps so we can see the same problem

1. We use LLBLGen (OR-Mapper) which creates two projects (*.csproj) in one Folder (both projects use/share the same packages.config) --> should be reproducable without LLBLGen, too

2. update or install nuget-packages on one or both projects and the references get f**ked up:

![fail](https://cloud.githubusercontent.com/assets/26297742/23744044/1cd4d372-04b3-11e7-8662-b0bfd3a5ded5.png)

only one project´s references got updated. the second one remains with the old (no longer existing) references 

### Sample Project

[Project1.zip](https://github.com/NuGet/Home/files/830334/Project1.zip)

**Comment by emgarten** [comment]
Use `packages.{projectname}.config`, two projects cannot share the exact same file.
