### ISSUE TITLE
Package "_Restore" button shows underscore rather than underline

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#478]
![_restore](https://cloud.githubusercontent.com/assets/3548/7290374/8dfdafc2-e932-11e4-8e08-c6847796e5e3.png)

This is on 3.0.60410.213

**Comment by feiling** [comment]
@AArnott, I couldn't repro the problem. The text "Restore" is displayed correctly. Also, the underline under "R" shows when I press Alt. All this is the standard behavior of WPF and we haven't done anything to change this. Could it be possible that this have something to do with the particular build of VS you're using?

**Comment by AArnott** [comment]
Well aside from the fact that I'm using a prerelease of VS2015, I couldn't
say that I have anything special going on.

**Comment by AArnott** [comment]
I just saw the bug elsewhere in VS (the New Project dialog). So it looks like this is a WPF/shell issue not a NuGet issue.
