### ISSUE TITLE
Visual Studio 2017 (NuGet 4.0.0) vs NuGetDefaults.config

### ISSUE THREAD

**Issue by ygeelen-tb** [NuGet/Home#4782]
We are using a %PROGRAMDATA%\NuGet\NuGetDefaults.config file to configure private package sources and supply Basic HTTP credentials to them as explained here: https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#nuget-defaults-file

We have switched to VS2017 because of issues with NuGet.exe passing the credentials correctly (NuGet 4.0.0 in VS2017 would supposedly fix this, but now things got worse because it doesn't even read the config file. See https://github.com/NuGet/NuGet.Client/pull/607#issuecomment-280389357

It seems that in Visual Studio 2017 (Enterprise edition on Windows 10) this config file is not loaded, so these package sources are not available from Visual Studio at all??
Should the file name or file path be different for VS2017?

**Comment by ygeelen-tb** [comment]
Are we obliged to use C:\Users\[username]\AppData\Roaming\NuGet\NuGet.Config instead now?

**Comment by emgarten** [comment]
Setting it per user is typically your best option. 

The machine wide location has moved to ``Program Files (x86)\NuGet``

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/PathUtil/NuGetEnvironment.cs#L18-L34

**Comment by ygeelen-tb** [comment]
Thanks! But the file name is still NuGetDefaults.config ?

Why would you prefer the per user option?
The thing is we are using an Active Directory Group Policy script, which copies the config file to all users in an AD group. The script needs to be aware of the user's directory name (normally the username).

By the way, do you happen to know the location of nuget.exe 4.0.0 ? Is it included in Visual Studio 2017 itself? Or in the VS extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.PackageInstaller ?

**Comment by emgarten** [comment]
NuGet.exe doesn't ship with visual studio, you can find it here: http://dist.nuget.org/

For an AD group scenario putting this under Program Files sounds like the right way to do this.

The name should be the same, let me know if it isn't working for you.

**Comment by ygeelen-tb** [comment]
Actually that's where I found the info: "NuGet 4.x is included in the Visual Studio 2017 installation. Latest NuGet releases are delivered as part of Visual Studio updates."

**Comment by emgarten** [comment]
@ygeelen-tb that doesn't refer to nuget.exe

**Comment by gwicksted** [comment]
@emgarten that really should be clarified on http://dist.nuget.org/ as it currently alludes to VS2017 having _all_ of the "batteries" included; however, only 1 of the two parts of NuGet are installed (the VSIX not the .exe CLI)

Even a different background color for Windows x86 Commandline vs all other options would help.

I assume the NuGet.CommandLine package is not referenced by VS2017 since it contains a NuGet.exe
