### ISSUE TITLE
Plans to unify all package configuration types

### ISSUE THREAD

**Issue by tomkuijsten** [NuGet/Home#4783]
Is there a concrete plan to unify the different nuget configuration types?

I create a solution in VS2017 and added three projects:
 - UWP
 - .net standard
 - .net framework

I end up with three different type of NuGet configuration (packages.config, project.json and packagereference). Our repository uses all of these types and it's pretty hard to automate package upgrades if I have to support all three variants.

**Comment by emgarten** [comment]
The plan is to move all three types to use PackageReference.

You currently have: 

 - UWP (project.json)
 - .net standard (PackageReference)
 - .net framework (packages.config)

**Comment by tomkuijsten** [comment]
Thanks for your answer. Is there any timeline on this plan?

I have to decide to wait for this to happen or create automation scripts to do the update. Would you recommend to update the packages.config to project.json? That would be one step closer to a single approach for me and a lot less custom scripting (packages.config is the hardest to script).

**Comment by emgarten** [comment]
If you are fine with waiting a couple months you can switch to ``.net framework PackageReference``. Otherwise project.json is very similar but doesn't like you do things dynamically with msbuild.

**Comment by tomkuijsten** [comment]
Thanks for the answers, I decided to wait.
