### ISSUE TITLE
NuGet 3.3.0 reports failure to upload the package, though the package is uploaded

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4784]
Reported on twitter, here: https://twitter.com/rappen/status/840100945983819776

![image](https://cloud.githubusercontent.com/assets/14800916/23804469/dc919162-056e-11e7-82ec-bc5cdf837875.png)

**Comment by emgarten** [comment]
This seems like it could be a server issue, if the package was uploaded but the server didn't respond afterwards I could see this happening.

**Comment by rappen** [comment]
Not really sure how to comment on that, but yes I agree it would be a server issue, as only servers were involved; VSTS performing the build and NuGet recieving the package.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
