### ISSUE TITLE
Nuget 4.0.0 - Unable to deploy and then install package

### ISSUE THREAD

**Issue by GitMonkey007** [NuGet/Home#4786]
1. I've created a simple class in an assembly that just takes and then returns a string.

`public static string EchoEcho(string s) => s;`

2. I've then followed the instructions [here](https://docs.microsoft.com/en-gb/nuget/quickstart/create-and-publish-a-package) to create a package. 
3. I've then pushed the package to a private Nexus instance. 
4. I've then tried to use nuget to install the package and the installation fails. In the case of the library and the console application both target .Net 4.6.

The commands I've run are as follows...

>nuget.exe spec

Created 'Echo.nuspec' successfully.

>nuget.exe pack Echo.csproj -Properties Configuration=Release -ForceEnglishOutput

Attempting to build package from 'Echo.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from '\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Packing files from '\projects\nexus_test\ConsoleNexusTest\Echo\bin\Release'.
Using 'Echo.nuspec' for metadata.
Successfully created package '\projects\nexus_test\ConsoleNexusTest\Echo\Echo.1.0.0.nupkg'.
WARNING: Issue found with package 'Echo'.

WARNING: Issue: Remove sample nuspec values.
WARNING: Description: The value "http://PROJECT_URL_HERE_OR_DELETE_THIS_LINE" for ProjectUrl is a sample value and should be removed.
WARNING: Solution: Replace it with an appropriate value or remove it and rebuild your package.

WARNING: Issue: Remove sample nuspec values.
WARNING: Description: The value "http://LICENSE_URL_HERE_OR_DELETE_THIS_LINE" for LicenseUrl is a sample value and should be removed.
WARNING: Solution: Replace it with an appropriate value or remove it and rebuild your package.

WARNING: Issue: Remove sample nuspec values.
WARNING: Description: The value "http://ICON_URL_HERE_OR_DELETE_THIS_LINE" for IconUrl is a sample value and should be removed.
WARNING: Solution: Replace it with an appropriate value or remove it and rebuild your package.

WARNING: Issue: Remove sample nuspec values.
WARNING: Description: The value "Tag1 Tag2" for Tags is a sample value and should be removed.
WARNING: Solution: Replace it with an appropriate value or remove it and rebuild your package.

WARNING: Issue: Remove sample nuspec values.
WARNING: Description: The value "Summary of changes made in this release of the package." for ReleaseNotes is a sample value and should be removed.
WARNING: Solution: Replace it with an appropriate value or remove it and rebuild your package.

>nuget setapikey dd3ce58c-XXXX-XXXX-XXXX-a3ec2f462394 -source http://{host}:{port}/repository/nuget-group/

The API Key '{...}' was saved for '{..}'

>nuget.exe push Echo.1.0.0.nupkg -Source http://{host}:{port}/repository/nuget-group/

Pushing Echo.1.0.0.nupkg to 'http://{host}:{port}/repository/nuget-group/'...
  PUT http://{host}:{port}/repository/nuget-group/
An error was encountered when fetching 'PUT http://{host}:{port}/repository/nuget-group/'. The request will now be retried.
Error while copying content to a stream.
  Unable to write data to the transport connection: An established connection was aborted by the software in your host machine.
  An established connection was aborted by the software in your host machine
  PUT http://{host}:{port}/repository/nuget-group/
  OK http://{host}:{port}/repository/nuget-group/ 10ms
Your package was pushed.

In VS 2017 Community Edition

Create a console application
Goto Manage Nuget Packages
Install package that we just added to the private repository
Get error message as follows

Could not install package 'Echo 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Microsoft Visual Studio Community 2017
Version 15.0.26228.4 D15RTWSVC
Microsoft .NET Framework
Version 4.7.02046

>nuget
NuGet Version: 4.0.0.2283

>ver
Microsoft Windows [Version 10.0.15048]

I've renamed the package to .zip. It looks to have the relevant structure for net46.
[Echo.1.0.0.zip](https://github.com/NuGet/Home/files/835392/Echo.1.0.0.zip)

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
