### ISSUE TITLE
project.assets.json not made if no packages used

### ISSUE THREAD

**Issue by borgdylan** [NuGet/Home#4788]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Restore targets

NuGet version (x.x.x.xxx): 4.0.0.0 RTM

OS version (i.e. win10 v1607 (14393.321)): ubuntu 16.10 x64

MSBuild Version: 15.0 (xplat-master branch for mono fork)

## Detailed repro steps so we can see the same problem

1. run msbuild /t:Restore on a project that has no ```PackageReference``` items
...

I have projects that do not need packages but only use the reference assemblies bundled with mono. Some of the build targets of the .NET SDK require the project.assets.json file to be present but NuGet only makes it if packages are consumed.

**Comment by borgdylan** [comment]
As a side note, this issue becomes relevant after the compiler runs because the build targets cannot detect the RIDs I set in the project file.

**Comment by emgarten** [comment]
Try setting the property ``RestoreProjectStyle`` to ``PackageReference``.  This should be set by the SDK if you are in a NETCore SDK project.

**Comment by borgdylan** [comment]
Is it set conditionally by default? Only if I use packages?

**Comment by borgdylan** [comment]
Without it i Get ```Nothing to do. None of the projects specified contain packages to restore.```. With it set the assets file is indeed written. Thanks for the workaround. Since I am using a custom compiler, I will add it to the props file for it so it is there by default.

**Comment by emgarten** [comment]
You need one of the following to get a project.assets.json file:
* A PackageReference item
* RestoreProjectStyle=PackageReference

The NETCore SDK should set this all the time by default, you might be missing something from the SDK, but this workaround should be the same.

Without any of the above NuGet treats the project as if it is a packages.config project or a non-NuGet project.

**Comment by borgdylan** [comment]
I guess it wasn't set as I was targeting net46 i.e. Mono and did not have the netstandard1.x/netcoreapp1.x TFM present.

**Comment by emgarten** [comment]
TFM doesn't matter here, just the targets/props you reference.
