### ISSUE TITLE
Visual Studio 2017 with PackageReference and C++ UWPs don't auto restore

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#4793]
I only get:
```
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.0010032
========== Finished ==========
```

even though using nuget.exe command line restore  or msbuild /t:restore works. Why are these different? I would think that VS package manager would use the msbuild target in 2017? 

Note this happens with or without an obj folder in my project.

@emgarten @rrelyea 
Are improvements here slated for Update 1?

**Comment by bbowman** [comment]
From Debugging looks like .vcxproj UWP is falling down the NuGetProjectFactory path for MSBuildNuGetProjectProvider which has the following:

```

                    // Treat projects with project.json as build integrated projects
                    // Search for projectName.project.json first, then project.json
                    // If the name cannot be determined, search only for project.json
                    string projectJsonPath = null;
                    if (string.IsNullOrEmpty(projectNameFromMSBuildPath))
                    {
                        projectJsonPath = Path.Combine(msbuildProjectFile.DirectoryName,
                            ProjectJsonPathUtilities.ProjectConfigFileName);
                    }
                    else
                    {
                        projectJsonPath = ProjectJsonPathUtilities.GetProjectConfigPath(msbuildProjectFile.DirectoryName,
                        projectNameFromMSBuildPath);
                    }

                    if (File.Exists(projectJsonPath))
                    {
                        result = new ProjectJsonBuildIntegratedProjectSystem(
                            projectJsonPath,
                            msbuildProjectFile.FullName,
                            envDTEProject,
                            EnvDTEProjectUtility.GetCustomUniqueName(envDTEProject));
                    }
```

Which overlooks the possiblity of an .vcxproj with **PackageReference** i.e. is build integrated but with project.json. What can we do here?

**Comment by bbowman** [comment]
Other possible culprit would be if its expected to go down the CpsPackageReferenceProjectProvider path, its failing at:

```
            // Check if the project is not CPS capable or if it is CPS capable then it does not have TargetFramework(s), if so then return false
            if (!hierarchy.IsCapabilityMatch("CPS"))
            {
                return false;
            }
```

Not sure what CPS is or how to add capabilities...

**Comment by bbowman** [comment]
@emgarten and I looked into this some more and it appears vcxproj doesn't implement VSProject4 like it needs to. @olgaark do you any details?

**Comment by olgaark** [comment]
This is the first time I hear about VsProject4 so sorry, cannot tell much.

**Comment by emgarten** [comment]
Support for VSProject4 is tracked internally

**Comment by rrelyea** [comment]
Pointers to some other customer requests for PackageReference in C++ projects:

-	https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33909292-use-packagereference-in-vcxproj
-	https://developercommunity.visualstudio.com/content/idea/351636/use-packagereference-in-vcxproj.html
-	https://developercommunity.visualstudio.com/content/problem/50373/obtaining-nuget-packages-via-packagereference-does.html
