### ISSUE TITLE
Directory structure for content files flattened if not adding Windows directory separator at the end of PackagePath

### ISSUE THREAD

**Issue by alfonsogarciacaro** [NuGet/Home#4795]
Using dotnet sdk 1.0.1. Maybe related to #4709.

I want to add a directory and its subdirectories of content files to the package. I do it like this.

```xml
    <Content Include="../../../build/fable-core/**/*.*">
      <PackagePath>fable-core</PackagePath>
      <Pack>true</Pack>
    </Content>
```

The problem is the directory structure of `fable-core` is flattened unless I add `\` at the end of PackagePath:

```xml
      <PackagePath>fable-core\</PackagePath>
```

> Please note that using `/` instead doesn't work.

This is not very intuitive and it's different behaviour from the .nuspec file where `\` is not needed at the end. Could it be fixed?

**Comment by rohit21agrawal** [comment]
@alfonsogarciacaro thanks for the report..yes this will be fixed soon.
