### ISSUE TITLE
NuGet pack does not skip content files from packages dependencies

### ISSUE THREAD

**Issue by henkmollema** [NuGet/Home#4796]
## Details about Problem
NuGet product used: NuGet.exe
NuGet version: `4.0.2283`
VS version: VS 2015
OS version: Windows 10 

Worked before? If so, with which NuGet version: `3.4.4.1321`

## Repro steps
Look at the repo here: https://github.com/henkmollema/NuGetDependencyContentFiles

Basically the problem is that NuGet does not skips content files from package dependencies anymore. The behavior changed with this commit: [f74af8bc5](https://github.com/NuGet/NuGet.Client/commit/f74af8bc52b895908dc829f87834aa7bb1105b07). The call to `GetInstalledPackagesAsync()` always returns an empty array: [FolderNugetProject.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectManagement/Projects/FolderNuGetProject.cs#L51)

### Verbose Logs

**Calling with NuGet 4.0.0:**
```
C:\src\NuGetDependencyContentFiles (master)
λ nuget pack WebApplication1\WebApplication1.csproj
Attempting to build package from 'WebApplication1.csproj'.
MSBuild auto-detection: using msbuild version '15.1.548.43366' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Packing files from 'C:\src\NuGetDependencyContentFiles\WebApplication1\bin'.
Found packages.config. Using packages listed as dependencies
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'HenkMollema'.
Successfully created package 'C:\src\NuGetDependencyContentFiles\WebApplication1.1.0.0.nupkg'.
```

**Calling with NuGet 3.4.4:**
```
λ nuget pack WebApplication1\WebApplication1.csproj
Attempting to build package from 'WebApplication1.csproj'.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
Packing files from 'C:\src\NuGetDependencyContentFiles\WebApplication1\bin'.
....
File from dependency is not changed. File 'Scripts\ckeditor\plugins\scayt\README.md' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\plugins\scayt\LICENSE.md' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\plugins\scayt\CHANGELOG.md' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\package.json' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\LICENSE.md' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\CHANGES.md' is not added.
File from dependency is not changed. File 'Scripts\ckeditor\styles.js' is not added.
Found packages.config. Using packages listed as dependencies
WARNING: Description was not specified. Using 'Description'.
WARNING: Author was not specified. Using 'HenkMollema'.
Successfully created package 'C:\src\NuGetDependencyContentFiles\WebApplication1.1.0.0.0.nupkg'.
```

### Sample Project
https://github.com/henkmollema/NuGetDependencyContentFiles

**Comment by emgarten** [comment]
Many packages purposely provide content to the project being packed in this way. There isn't a good way for NuGet to determine what should and what shouldn't get included.

@rohit21agrawal can you provide some help on how to turn this content off?

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Home/issues/3927

**Comment by henkmollema** [comment]
@emgarten there seemed to be a way in NuGet 3.x. I wonder how such a change cannot be found in any release notes. This has major impact on our build/package pipeline and forces us to keep using NuGet 3.4.4.
