### ISSUE TITLE
VS crashes on solution close

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4798]
VS branch - VS 2017 RTW (26228.0)
NuGet version - 4.1.0.2357

Sometimes when I close solution while it might be still auto restoring, visual studio crash.

Steps:
1. Clone git repo https://github.com/dotnet/eShopOnContainers
2. Open eShopOnContainers-ServicesAndWebApps.sln
3. Close solution while auto restore is in progress or auto restore hasn't even started. It doesn't happens all the time.

Crash dump shared @ \\scratch2\scratch\asja

**Comment by rrelyea** [comment]
does crash data support fixing in 4.1 or later?

**Comment by jainaashish** [comment]
It was one of the top hit for VS 2017 RC releases but got fixed in RTW and after that i don't see any watson crash data for this.

Previos internal issue# 268787 and it was fixed by VS IDE team. So I'll log a bug for this in their repo and close this as external.

**Comment by jainaashish** [comment]
Associated VS IDE bug# 395991
