### ISSUE TITLE
dotnet nuget push *.nupkg -k <key> push symbol package to package feed

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#4799]
From Chris:

My initial experience was less than perfect. I have my packages building with symbols into a single folder. Pretty typically stuff IMO.  When I run:

dotnet nuget push *.nupkg -k <key>

It tried to push both the *.nupkg files and the *.symbol.nupkg files to the package feed.  This results in 409 for the *.symbol.nupkg file because they both were picked up to push to the package server (as opposed to the symbol server). Fortunately, the real package is published first.

Since *.nupkg and *.symbol.nupkg are the standard file extensions, here’s what I’d love to see it do in additional to its current capabilities:

•	dotnet nuget push *.nupkg -k <key> - push the package and push the complementary *.symbols.nupkg to the symbol server, if any; like nuget.exe
•	dotnet nuget push -key <key> - push all *.nupkg files in the current directory and any complementary *.symbol.nupkg files to the symbol server

At least in my “limited” experience of publishing packages, there are two primary use cases:
•	Publish one package
•	Publish all packages

In both cases, if there is a generated symbol package, I want that published too (which seems to jive with the “--no-symbols” option).  I see no reason to not have options to support additional scenarios, but I’d surmise that those are the most prolific.

**Comment by emgarten** [comment]
Thank you for the suggestion, we are not planning to add this feature to dotnet.exe at this time.

Users can currently workaround this by moving symbol packages out of the folder before pushing, and then pushing the symbols packages to the symbol server as needed. The NuGet protocol currently does not differentiate between symbol and non-symbol servers, they are both feeds and some feeds support both types, while others support only one.
