### ISSUE TITLE
Auto-complete in PMC works incorrectly with object methods

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#4800]
Tab-completion on object property or method replaces the entire expression instead of just property/method name.

For example, following expression
```ps1
$x = $context.try
```

after pressing <kbd>Tab</kbd> key will be replaced with
```ps1
$x = TryResolvePackageAsset(
```

instead of
```ps1
$x = $context.TryResolvePackageAsset(
```

**Comment by emgarten** [comment]
Closing based on lack of customer feedback on this.

Please comment here to support fixing this so that this work can be prioritized.
