### ISSUE TITLE
Target is Windows 8.1 in properties

### ISSUE THREAD

**Issue by I2obiN** [NuGet/Home#4805]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'MPI.NET 1.2.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by emgarten** [comment]
@I2obiN it looks you are in a native C++ project and trying to install a package for net40.
