### ISSUE TITLE
DotNetCliTool package included in publish output

### ISSUE THREAD

**Issue by sbomer** [NuGet/Home#4814]
## Problem description

An indirectly-referenced DotNetCliTool package is included in the publish output.

This appears related to https://github.com/NuGet/Home/issues/4653. A fix for this would allow a single `PackageReference` to pull down tools packages without including them in the output, but I believe more work would be needed to make dotnet look for these indirectly-referenced tools when running from the command line.

Worked before? Not to my knowledge.

## Version info

NuGet product used: dotnet pack, dotnet restore

NuGet version: 4.3.0.0

dotnet --info:

```
.NET Command Line Tools (2.0.0-preview1-005414)

Product Information:
 Version:            2.0.0-preview1-005414
 Commit SHA-1 hash:  01e7bfde74

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/2.0.0-preview1-005414/
```

OS version: ubuntu 16.04

## Reproducing the issue

**Repro steps:**

- [toolDemo.tar.gz](https://github.com/NuGet/Home/files/845793/toolDemo.tar.gz)
- ./build.sh

**The repro does the following:**
- Create a package with `packageType` `DotnetCliTool` (see [nuget docs](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package))
- Create a package that depends on the cli tool package.
- Add a reference to the second package in a project.
- Publish the project. The output contains the cli tool.

## Expected behavior

The cli tool is not included in the consuming app's publish output.

## Actual behavior

After `dotnet publish`, cliTool.dll is in the publish directory despite it coming from a DotNetCliTool package:

```
consumer/
├── bin
│   └── Debug
│       └── netcoreapp2.0
│           ├── consumer.deps.json
│           ├── consumer.dll
│           ├── consumer.pdb
│           ├── consumer.runtimeconfig.dev.json
│           ├── consumer.runtimeconfig.json
│           └── publish
│               ├── cliTool.dll          <----------------
│               ├── consumer.deps.json
│               ├── consumer.dll
│               ├── consumer.pdb
│               ├── consumer.runtimeconfig.json
│               └── testMsbuildTasks.dll
```

**Comment by emgarten** [comment]
@sbomer if a tool package is added under a ``PackageReference`` it will be treated as a normal package regardless of the package type. To add it as a tool reference it with ``DotnetCliToolReference``.

**Comment by sbomer** [comment]
Thanks @emgarten! In that case, what's the effect of setting the packageType to `DotNetCliTool`? The docs at https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package make it sound like this can be used to prevent it from being included in the app's dependencies:

> Beginning with NuGet 3.5, packages can be marked with a specific package type to indicate the package's intended use. Packages that are not marked with a type, including all packages created with earlier versions of NuGet, are assumed to be the Dependency type.

> 
> DotnetCliTool type packages are extensions to the .NET CLI and are invoked from the command line. Such packages can be installed only in .NET Core projects and have no effect on restore operations. More details about these per-project extensions are available in the .NET Core extensibility documentation.
> 
> When a DotnetCliTool package is installed, Visual Studio will place the package in the project.json tools node instead of the dependencies node.

**Comment by emgarten** [comment]
The NuGet UI in visual studio will check the type and block the install, but if you edit your csproj manually or the package comes in transitively restore will assume it was intended as a normal dependency.

**Comment by sbomer** [comment]
Thanks for the explanation. Feel free to close the issue if that's the intended behavior. :)
