### ISSUE TITLE
[VSFeedback] Setting the build output folder of multiple projects with the same nuget reference to the same folder generates random build errors

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#4816]
Internal issue 389572 (vsfeedback)

>When I build a big Project with many references (among others nuget references) witch are set to copy local, then the build failes with a random copy with the error 'access to the path '...' is denied.'.
>
>With enouth projects that contain the same reference and output folder basicly every rebuild fails.
With my ~50 projects set to the same output folder and many of them with the same (nuget) references I often have to build 4-5 times to ensure everything compiled because of the many access deneied build errors, if I did a clean/rebuild before.

**Comment by emgarten** [comment]
This sounds like a general MSBuild problem. NuGet does not perform the actual copy of files.
