### ISSUE TITLE
[VSFeedback] PostBuildEvent runs before GenerateNuspec

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#4817]
Bug 389579:[Feedback] PostBuildEvent runs before GenerateNuspec

repro steps

1. create ClassLibrary (.NET Standard) project
2. configure &quot;Generate package on build&quot;
3. set Post Build Event command line.
4. build

I expect PostBuildEvent is LAST target of Build.

actualy. 

 PostBuildEvent, _WalkEachTargetPerFramework, GenerateNuspec

**Comment by rrelyea** [comment]
options?

**Comment by rohit21agrawal** [comment]
let's have a discussion offline about this, but i am against this behavior. I think everything related to pack should happen after PostBuildEvent.

**Comment by emgarten** [comment]
Closing based on the comments here.
