### ISSUE TITLE
Attribute xmlns="nuspec.xsd" in packages.config causes NullReferenceException and empty <packages />

### ISSUE THREAD

**Issue by abatishchev** [NuGet/Home#4819]
I faced a weird issue on machine of my teammate. By some reason one of his projects in its packages.config got the `xmlns` attribute. NuGet stopped working, now throws an exception on all attempts to install any package.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI or Package Manager Console
NuGet version (x.x.x.xxx): 3.5.0.1996
dotnet.exe --version (if appropriate): n/a
VS version (if appropriate): 14.0.25431.01 Update 3
OS version (i.e. win10 v1607 (14393.321)): 10.0.14393 Build 14393
Worked before? If so, with which NuGet version: n/a

## Detailed repro steps so we can see the same problem

1. Add xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd" to the `<packages>` node in packages.config
2. Install a package (e.g. Owin)

## Result

packages.config looses **all** its content, now contains only one element `<packages />`.

### Verbose Logs
```
PM> Install-Package Owin
Attempting to gather dependency information for package 'Owin.1.0.0' with respect to project 'Api', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 0.57 ms
Attempting to resolve dependencies for package 'Owin.1.0.0'
Resolving dependency information took 0 ms
Resolving actions to install package 'Owin.1.0.0'
Resolved actions to install package 'Owin.1.0.0'
Found package 'Owin 1.0.0' in 'D:\Projects\PIE.Authorization\packages'.
Package 'Owin.1.0.0' already exists in folder 'D:\Projects\PIE.Authorization\packages'
Install failed. Rolling back...
Package 'Owin.1.0.0' does not exist in project 'Api'
Removing package 'Owin.1.0.0' from folder 'D:\Projects\PIE.Authorization\packages'
Removed package 'Owin.1.0.0' from folder 'D:\Projects\PIE.Authorization\packages'
Executing nuget actions took 1.24 sec
Install-Package : Object reference not set to an instance of an object.
At line:1 char:1
+ Install-Package Owin
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:03.2583579
PM> 
```
I try to attache a repro project within a zip but GitHub says:

>We don’t support that file type. with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or **ZIP**.

**Comment by abatishchev** [comment]
Can you please take a look into this?

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by abatishchev** [comment]
I was able to easily reproduce this in VS 2017 15.3.5

**Comment by emgarten** [comment]
After working with @abatishchev I was able to reproduce this. However it seems like the only way to get into this situation is to manually edit the packages.config file, based on that I don't think this meets the bar.
