### ISSUE TITLE
Nuget as a Protocol  

### ISSUE THREAD

**Issue by cgatian** [NuGet/Home#482]
I am attempting to use nuget.core to retrieve packages from a private server and install them. These packages are considered "update packs" and will replace dlls/content within a running application. I was able to successfully create packages, serve them, and create a package retrieval application. However, I was stuck wondering if Nuget has the mechanisms to perform the proper file copies? I'm pretty sure once you download a package it's then in the developer's hands to properly extract the package appropriately. The magic that happens in visual studio is due to leveraging the existing functionality to add/remove files and references within the MSBuildProjectSystem class.

Are my findings correct? Or did I miss a piece of functionality within one of the libraries that will allow me to update dlls/content on a target folder.

**Comment by yishaigalatzer** [comment]
You are correct, and a good sample (though not guaranteed to work forever) is: http://nuget.codeplex.com/SourceControl/latest#WebMatrixExtension/

Also note that we are enabling a new type of feed (NuGet V3) that is based completely on static files. It is a lot more efficient and the code for it is here (start from Home repo). We don't yet have a public server implementation for you to build a server from, just something to keep in mind for now.

**Comment by cgatian** [comment]
Thank you for the information. I've been deep in Nuget source for the last couple of days.  If I have any future questions is it alright to post them here? Or is there some other medium I should use?

**Comment by yishaigalatzer** [comment]
We typically send people over to stackoverflow, where more people will see it. Come here if its not answered within a couple of days. This is mostly for bugs and feature requests.

Thanks for being polite and asking :) and also thanks for using our bits.

**Comment by cgatian** [comment]
Will do.

If you don't mind one last simple request. I've been looking this over and I'm pretty confident we should use nuget.core for 60% of the leg work for building a application update framework. My boss wants to bundle zip files and have people place them in a certain folder.  I'm like, why build everything from the ground up? A LOT of thinking and structure is already there, go out and use it!  I know you probably have a slightly biased option, but slap me if I'm wrong.   

Nuget is so much more than the VS Extension shows.  I have a meeting tomorrow to try to convince higher ups nuget is the way to go.  Wish me luck, as I don't want to be stuck at ground zero ;)

Again thanks for being so kind to a nuget noob. I pray I get to sink my teeth into it.

**Comment by yishaigalatzer** [comment]
Not sure what you are looking for exactly, but feel free to use our code, assemblies or packages. Production update is typical not done directly with nuget because of the fact that many a times deployment has more concerns than just copying files and even for that it requires dealing with locked files etc. But NuGet is definitely used as part of such systems.
