### ISSUE TITLE
How to change version of nuget.exe

### ISSUE THREAD

**Issue by jagrutichavan** [NuGet/Home#4822]
I have the issue with nuget.exe version.
I am using visual studio 2013 and when I say "enable nuget package restore" then I get the nuget.exe file with version 3.5.0 but i want this file to be generated with version 3.4.4
Can anyone please help to solve this issue.Any help will be appreciated.I need solution for this urgently.

**Comment by emgarten** [comment]
Instead of using "enable nuget package restore" download nuget.exe using a script and run nuget.exe restore on your solution before the build starts.

You can find 3.4.4 here:
https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe

Also, is there any reason you are unable to use 3.5.0?

**Comment by jagrutichavan** [comment]
for 3.5.0 it requires Msbuild version 14 and my Msbuild version on Jenkins is 12 . I cant change Msbuild version on Jenkins server
For Msbuild 12 it requires nuget.exe v3.4.4

**Comment by emgarten** [comment]
Use ``-MSBuildVersion 14`` or ``-MSBuildPath``, you can also try 4.0.0 which has some of the issues fixed around auto detecting msbuild.

**Comment by rrelyea** [comment]
Please let us know if that doesn't resolve it for you.
