### ISSUE TITLE
[Test Failure] An extra package is added to reference after installing a package on multiple projects

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4823]
**NuGet Version:** NuGet 4.3.0-Beta1-2394 (Insertable)
**VS Version:** D15VSUML 26315.00
**OS Version:** Windows 10 RS2_Release 15058.0.170310-1436

**Repro Steps:**
1.	Check **‘Allow format selection on first package install’** format in NuGet Package Manager setting dialog and restart VS.
2.	Create a solution included two C# Class Library (.Net Framework) projects (renamed PC1 and PC2), and **add reference** PC2 to PC1 (PC1->PC2).
3.	Open the ‘Manage NuGet Packages…’ for PC1 project.
4.	Install package ‘Newtonsoft.Json’ into PC1 project by PM UI with **PackageReference** mode.

**Expected Result:**
The package ‘Newtonsoft.Json’ is added to PC1 reference.

**Actual Result:**
An extra PC2 package is added to PC1 reference as below screenshot.
![8882](https://cloud.githubusercontent.com/assets/20632775/23990034/b3de17b2-0a6f-11e7-84c1-01e4a304c37a.png)

**Notes:**
The issue repro on D15Rel 26315.00 + NuGet 4.1.0-RTM-2395 Insertable.

**Comment by zhili1208** [comment]
this looks like "Project references also show up as Package references in Solution Explorer" bug(VSTS 377624)
the fix is already in PR: https://github.com/NuGet/NuGet.BuildTasks/pull/33

**Comment by rrelyea** [comment]
yes, should see the fix show up in d15rel builds today or tomorrow. Fix may take a bit longer to get into vsuwpt branch (for 4.3 verification)

**Comment by v-nancyj** [comment]
The issue has fixed in D15Rel 26319.00 + NuGet Client 4.1.0-RTM-2405.
