### ISSUE TITLE
Microsoft.Bcl.Async package cannot resolve dependencies in VS2017

### ISSUE THREAD

**Issue by blackcity** [NuGet/Home#4824]
## Details about problem
NuGet package Microsoft.Bcl.Async for Net40 target cannot be resolved in a multi-target library after switching to VS2017. Worked in VS2015.

NuGet version: 4.0.0
VS version: 2017
OS version: win10 x64
Worked before? Worked in NuGet version: 3.5.0 (using VS2015)

## Detailed repro steps so we can see the same problem
Details see: https://github.com/dotnet/cli/issues/5993

**Comment by rrelyea** [comment]
Investigate -- is it package issue and/or NuGet 4 change in behavior.

**Comment by blackcity** [comment]
The error states that the package expects a different version of System.Threading.Tasks. Under VS2015 there is no such error. The package Microsoft.BCL.Async hasn't changed for years, but it is wildly used because it brings async/await to .NET4.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
