### ISSUE TITLE
API for restoring/refreshing UWP packages

### ISSUE THREAD

**Issue by javitosanchez** [NuGet/Home#4825]
I'm creating a VS extension. I'll need an API for restoring packages the first time a UWP project is created in VS2017. The same thing VS does when right click under solution node in solution explorer:

![restore](https://cloud.githubusercontent.com/assets/3597066/23995467/0389ca5c-0a4a-11e7-8dd2-d8cb0422d25e.jpg)

I cannot use the NuGet template wizard because my packages are added to project.json dinamically depending on user actions.
The workaround I'm doing right now uninstall and install the packages.

```
            var componentModel = (IComponentModel)Package.GetGlobalService(typeof(SComponentModel));

            var installer = componentModel.GetService<IVsPackageInstaller>();
            var uninstaller = componentModel.GetService<IVsPackageUninstaller>();
            var installerServices = componentModel.GetService<IVsPackageInstallerServices>();

            var installedPackages = installerServices.GetInstalledPackages().ToList();

            installedPackages.ForEach(p => uninstaller.UninstallPackage(GetActiveProject(), p.Id, false));
            installedPackages.ForEach(p => installer.InstallPackage("All", GetActiveProject(), p.Id, p.VersionString, true));
```

Thanks!!

**Comment by rrelyea** [comment]
@emgarten - can you please recommend best way to handle today? (my guess is that restore isn't necessary?)

**Comment by emgarten** [comment]
I asked @javitosanchez to open this issue. The uninstall/install method is currently the best way we could come up with to do this until there is a way to invoke a restore programmatically.

Long term if auto restore was done for UWP projects this would also solve the issue.

**Comment by emgarten** [comment]
This API exists now as `IVsSolutionRestoreService2.NominateProjectAsync`
