### ISSUE TITLE
[NuGet.Protocol] In V2 Dependency gather, for each package, multiple calls to V2 endpoint FindPackagesById are made where 1 would work. Currently, FindPackagesById, hits the DB, so this can be slow for package with lot of dependencies

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#483]
[This is only applicable to V2 endpoint]

[NuGet.Protocol] In V2 Dependency gather, for each package, multiple calls to V2 endpoint FindPackagesById are made where 1 would work. Currently, FindPackagesById, hits the DB, so this can be slow for package with lot of dependencies

V2 Dependency gather uses FindPackages. And, FindPackages on IPackageRepository, in NuGet.Core, actually calls into FindPackagesById, which then hits the server to get all the versions. And, FindPackages filters out the versions based on the IVersionSpec passed in. So, multiple calls to FindPackages actually results in multiple calls to FindPackagesById. In addition, currently, FindPackagesById hits the DB every time. So, this can get compounded into a slow experience when there is a deep dependency graph

**Comment by emgarten** [comment]
DependencyInfo requests will now retrieve all versions of a package and cache the results.

Fixed with NuGet/NuGet3@fddf5dc3e3af91f3d07878d1616c40a6faa15c75
