### ISSUE TITLE
Continuous "Restoring NuGet packages" for non-fixed package version

### ISSUE THREAD

**Issue by hubuk** [NuGet/Home#4830]
## Details about Problem

**NuGet product used:**
Package Manager Host

**NuGet version:**
Name             : Package Manager Host
Version          : 4.0.0.2323
InstanceId       : 8c772c92-46b0-43ed-86c2-3e11d0663fb2
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : pl-PL
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

**VS version:**
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC

**OS version:**
win10 v1607 (14393.693)

**Worked before? If so, with which NuGet version:**
Not known

## Detailed repro steps so we can see the same problem

1. Create a new project: .NET Standard -> Class Library (.NET Standard)
2. Edit csproj file using "Edit ClassLibrary1.csproj" context menu from Solution Explorer
3. Add following line to PropertyGroup:
```XML
<VersionSuffix>t$([System.DateTime]::Now.ToString(ssff))</VersionSuffix>
```
4. Save the project.
5. Observe continuous "Restoring NuGet packages" in Package Manager Output window
```
Restoring NuGet packages...
Time Elapsed: 00:00:00.0801728
========== Finished ==========

Restoring NuGet packages...
Time Elapsed: 00:00:00.1057414
========== Finished ==========
(...)
```

### Sample Project
Opening one of the following projects in VS2017 will also trigger the problem:
[ClassLibrary1.zip](https://github.com/NuGet/Home/files/849016/ClassLibrary1.zip)
[GitHub repo](https://github.com/hubuk/ClassLibrary1)

**Comment by rrelyea** [comment]
@alpaix  - We likely need to work with the Roslyn-Project-System to solve this one. Can you please propose a solution after working with them?

**Comment by emgarten** [comment]
I believe this was fixed on the project system side in the latest vs.

**Comment by hubuk** [comment]
@emgarten Still reproducible in 15.4

**Comment by emgarten** [comment]
This issue was moved to dotnet/project-system#2901
