### ISSUE TITLE
After upgrading from project.json to PackageReference fails, build no longer works

### ISSUE THREAD

**Issue by branh** [NuGet/Home#4832]
When I call the new IVsProjectJsonToPackageReferenceMigrateResult API and it fails, the project is no longer buildable.

The steps are:
1. Create a new UWP project targeting RS1.
2. Open project.json.
3. Change frameworks to read 

"frameworks": {
    "uap10.0": {},
    "net45": {}
  },

4. Call the upgrader API to convert from project.json to PackageReference.

Expected: Upgrade will fail. Project will still be buildable.
Actual: Upgrade fails, but project build fails after this point. Clean and build, and even deleting the .vs folder do not fix the problem.
 
Comparing the .csproj and project.json files before and after with diff shows that they are identical. The only difference I can find is that after the upgrade fails there are three new files in the project's obj directory:
App.csproj.nuget.g.props
App.csproj.nuget.g.targets
project.assets.json

If I delete the files manually, the project builds.

**Comment by rohit21agrawal** [comment]
cannot repro this issue.
