### ISSUE TITLE
copyToOutput attribute is not working

### ISSUE THREAD

**Issue by fahadash** [NuGet/Home#4834]
I packed my project with the following 

```xml
 	<contentFiles>
		<files include="content\obfuscated.dll" buildAction="Content" copyToOutput="true" />
	</contentFiles>
```

When I pull the package into my project and I look at the obfuscated.dll, I see the following in the property window
![screenshot](http://i.imgur.com/DuOJVq4.png)

I am not sure if I am getting the right idea about *copyToOutput* attribute. I was expecting this property to be set to "Copy Always". How do I accomplish that?

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version :3.5.0.1938

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2015 CE

OS version (i.e. win10 v1607 (14393.321)): Win7

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a package using the following Nuspec

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata minClientVersion="3.3">
    <!-- Required elements-->
    <id>obfuscated</id>
    <version>0.1.1</version>
    <description>details</description>
    <authors>fahadash</authors>
	<title>title</title>
	<releaseNotes>
	</releaseNotes>
    <!-- Optional elements -->
    <!-- ... -->
	<contentFiles>
		<files include="content\obfuscated.dll" buildAction="Content" copyToOutput="true" />
	</contentFiles>
    </metadata>
    <!-- Optional 'files' node -->
</package>
```

2. Add it to a gallery, install it into any visual studio project
3. Observe obfuscated.dll added to project, look at CopyToOutputDirectory property in property window

...

**Comment by emgarten** [comment]
It looks like you are putting the dll under the ``content`` folder and using it with a ``packages.config`` project. ``contentFiles`` items usually have a format similar to ``contentFiles/any/any/obfuscated.dll`` and these items are used in ``PackageReference`` or ``project.json`` projects.  The nuspec section you've added is likely not being used here.

For a packages.config style project that uses the ``content`` folder you will need to use an install.ps1 file to change the property or include it with a targets file.

**Comment by rrelyea** [comment]
@emgarten speaks the truth.
