### ISSUE TITLE
NuGet.CommandLine 4.0.0 package was not published on nuget.org

### ISSUE THREAD

**Issue by dtretyakov** [NuGet/Home#4836]
Despite NuGet 4.0 was releases there is no NuGet.CommandLine package in https://www.nuget.org/packages/NuGet.CommandLine.

Do you have any ideas when it will be available there?

**Comment by rrelyea** [comment]
We should publish to our docs site... but for now, check out my tweet: https://twitter.com/rrelyea/status/843839843054444544 

![image](https://cloud.githubusercontent.com/assets/8865080/24105913/a371e8e6-0d43-11e7-8a51-64c9f3b22ea9.png)
