### ISSUE TITLE
dnx feed dropping packages that miss-name nuspec file

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#484]
some of the nuspec files in the packages fail because they do not follow the stated convention of <package-id>.nuspec

the issue is that the client is actually more forgiving.

the dnx job should follow the implemented client behavior for these packages and look for any file that ends with nuspec in the root of the zip (and presumably if it finds more than one - use the <package-id>.nuspec convention)

**Comment by yishaigalatzer** [comment]
How many of these pacakges exist? Should we just stop them from being uploaded from now on?
