### ISSUE TITLE
dotnet restore no longer restores recursivly all csproj files

### ISSUE THREAD

**Issue by niemyjski** [NuGet/Home#4849]
I'm running the latest VS2017 release and dotnet 1.0.0 on windows 10 x64 stable.  I came across an issue that worked in the previous dotnet cli (project.json). If I took my project (https://github.com/exceptionless/Exceptionless.Net/tree/5d063552f395fe8b43402ed7ed3566420d007e95) and did dotnet restore it would find all projects (.csproj) including those not in the solution file and do a restore. This no longer happens.

**Comment by rrelyea** [comment]
by design. we are now working similarly to "dotnet build". given a project, we will recursively restore all project dependencies. Or if you restore a solution, will will restore all of those projects.
Make sense to make build and restore work the same way?

/cc: @emgarten

**Comment by emgarten** [comment]
@niemyjski which version of dotnet was this last working in? 

Can you give me an example of a project in that repo that isn't restored, and the parent project that references it?

**Comment by emgarten** [comment]
Also, Visual Studio doesn't support loading projects outside of the solution. This is true everywhere not just restore. There it is expected, but command line on the other hand does allow this.

**Comment by niemyjski** [comment]
I remember it working this way in `1.0.0-preview2-003131` as per the master branch right now (https://github.com/exceptionless/Exceptionless.Net) upon upgrading it I had to change the scripts around restores as they weren't happening to half my projects (signed container projects)

**Comment by emgarten** [comment]
This is expected. Preview2 did not use msbuild and would recursively search the file system. In RTM msbuild runs the restore and it automatically detects project and solution files in your current directory. What you are likely seeing is that the projects that aren't being restored aren't linked to in any way by the one msbuild is finding. 

Your best option is to create a solution file that includes everything you would like to restore.

**Comment by niemyjski** [comment]
I don't like having duplicated projects in a solution file just for restore. And then have to process those projects every time  I load vs. I'll just close this issue as it's by design.
