### ISSUE TITLE
Stop button on Powershell console is not truly cancelling the operation

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#485]
Stop button on Powershell console is not truly cancelling the operation. It simply stops the pipeline that has been invoked asynchronously. Note that the CancellationToken from the CancellationTokenSource on the ConsoleDispatcher needs to be passed down to the powershell cmdlets

Repro steps
1. Create a new console application
2. On PMC, Install-Package Microsoft.AspNet.Mvc
3. After a few dependencies have been installed, click the stop button

Expected:
Installation goes through for the package being installed when stop is pressed. And, then, the whole installation is rolled back

Actual:
Installation stops abruptly and does not roll back

**Comment by mishra14** [comment]
@jainaashish: Did you fix this with the work on cancellation token on PMC?

**Comment by jainaashish** [comment]
Yes, it was fixed with that work.
