### ISSUE TITLE
dotnet pack is unable to package files from outside of the project directory

### ISSUE THREAD

**Issue by niemyjski** [NuGet/Home#4854]
I'm running the latest VS2017 release and dotnet 1.0.0 on windows 10 x64 stable. I came across a bug with dotnet pack.

Here is the a link the source:
https://github.com/exceptionless/Exceptionless.Net/tree/9614d2bc1d2cb949945d05ff4dbf0d8bed0738f0

So I read over the docs for pack and the following should work... But I can't seem to get a psm1 script that's common across all my projects to copy from a parent folder. Also something should jsut be a whole lot simpler.

``` xml
  <ItemGroup Label="Package">
    <None Update="NuGet\tools\*">
      <PackagePath>tools</PackagePath>
      <Pack>true</Pack>
    </None>
    <None Update="..\..\Exceptionless\NuGet\tools\exceptionless.psm1"">
      <PackagePath>tools\exceptionless.psm1</PackagePath>
      <Pack>true</Pack>
    </None>
    <None Update="readme.txt">
      <PackagePath>readme.txt</PackagePath>
      <Pack>true</Pack>
    </None>
  </ItemGroup>
```

I'd expect the above to be as simple as this:

``` xml
  <ItemGroup Label="Package">
    <None Update="NuGet\tools\*">
      <PackagePath>tools</PackagePath>
    </None>
    <None Update="..\..\Exceptionless\NuGet\tools\exceptionless.psm1">
      <PackagePath>tools\exceptionless.psm1</PackagePath>
    </None>
    <None Update="readme.txt"></None>
  </ItemGroup>
```

**Comment by niemyjski** [comment]
I'm also seeing issues where I can't even get the readme to get packed into half of my projects (src\Exceptionless)

**Comment by rohit21agrawal** [comment]
it looks like this doesn't work with ```Update``` but works with ```Include``` . @niemyjski can you help me understand why you are using ```Update``` here? trying to come up with workarounds for you as i investigate this.

**Comment by niemyjski** [comment]
All the examples and docs I saw were update, don't think I ever saw include once. I can try changing this to include and see fi it fixes. My understanding was that if you do update on a file path it could change the action / where that file is placed

**Comment by rohit21agrawal** [comment]
@niemyjski can you point me to some of those example and docs..?

**Comment by niemyjski** [comment]
@rohit21agrawal I did a quick search but I can't find them now. I saw it mentioned a few times in the conversion guides and I thought I saw it in the csproj docs. Either the blogs / docs were updated or I'm seeing things. But I wouldn't have logged this issue or came up with this code if I had seen it done this way.. I would have tried `<None Include` if I saw it....
