### ISSUE TITLE
Ability to find and remove unsued NuGet packages in a project/solution

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4857]
Feedback from David:

I saw your post about what is new with the NuGet package manager in Visual Studio 2017. One feature that is not there that I would guess most of us need is  a way to find NuGet packages that are no longer used and remove them. This is especially important when moving to CI builds.

I can't find anything out there that helps with this.

Thanks,
David McCarter
Microsoft MVP
http://dotnettips.com

**Comment by emgarten** [comment]
This is somewhat related to https://github.com/onovotny/ReferenceGenerator  This tool removes unneeded dependencies at pack time.

Also, a tool could find which dlls are used, but it may be difficult to determine which meta packages are needed, and which packages contain additional things such as init.ps1 files and runtime.json files that are actually used but aren't directly depended on by the assemblies that are written out.
