### ISSUE TITLE
Can't package a .NETStandard class library

### ISSUE THREAD

**Issue by mthamil** [NuGet/Home#4858]
## Details about Problem
Visual Studio 2017
Nugetizer-3000 Visual Studio Extension v0.1.227
NuGet.Build.Packaging v0.1.227

## Detailed repro steps so we can see the same problem
I am trying to migrate from the NuProj system, so I have a separate project that creates a package. I have a class library targeting NETStandard 1.3

1. Create a class library targeting NETStandard 1.3.
2. Make sure class library is not generating its own nuget package (I can't seem to control the version sufficiently through my CI that way).
3. Add reference to NuGet.Build.Packaging to class library.
4. Use the Visual Studio Add New Project dialog, choose Nuget -> Package.
5. Add a project reference to the class library.
5. Try to build, it fails with error: 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.Common.targets(73,5): error : Project 'G:\Development\SharpEssentials\SharpEssentials\SharpEssentials.csproj' targets '.NETStandard,Version=v1.3'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.`

I am assuming it thinks the package project targets v4.0 for some reason? I don't have any projects that target 4.0, I have a unit test project that targets 4.6, but that builds and runs fine.

**Comment by emgarten** [comment]
@mthamil what type of class library did you create?

**Comment by mthamil** [comment]
It's multitargeting .NETStandard 1.3 and .NET 4.6 (however I started out just targeting .NETStandard 1.3 and had the same issue) using the new abbreviated csproj format.
The following is its entire contents:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard1.3;net46</TargetFrameworks>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netstandard1.3\SharpEssentials.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\netstandard1.3\SharpEssentials.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Build.Packaging" Version="0.1.227" />
    <PackageReference Include="System.ComponentModel" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.EventBasedAsync" Version="4.3.0" />
    <PackageReference Include="System.ComponentModel.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Process" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Watcher" Version="4.3.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
    <PackageReference Include="System.Threading.ThreadPool" Version="4.3.0" />
  </ItemGroup>
</Project>
```

**Comment by mthamil** [comment]
I guess i'll add the nuproj contents too:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <Import Project="$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.props" Condition="Exists('$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.props')" />
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|AnyCPU">
      <Configuration>Debug</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|AnyCPU">
      <Configuration>Release</Configuration>
      <Platform>AnyCPU</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Configuration">
    <PackageId>SharpEssentials</PackageId>
    <PackageVersion Condition="'$(PackageVersion)' == ''">1.0.0</PackageVersion>
    ...
  </PropertyGroup>
  <PropertyGroup Label="Globals">
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <ProjectGuid>3d6ce7df-9570-4216-b1ed-55270e880c3e</ProjectGuid>
  </PropertyGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpEssentials\SharpEssentials.csproj" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.Common.targets" />
  <Import Project="$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.targets" Condition="Exists('$(NuGetAuthoringPath)\NuGet.Packaging.Authoring.targets')" />
</Project>
```

I'll add that if I unload the nuproj project the solution builds fine.

**Comment by emgarten** [comment]
@kzu this looks like a nugetizer issue, how should the target framework be found?

**Comment by kzu** [comment]
@emgarten it's part of the [Authoring.props](https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.Authoring.props#L14), which is [imported automatically](https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.props#L124) for [packaging projects](https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.props#L15).

Based on another bug report, we are essentially allowing packaging projects to [reference anything](https://github.com/NuGet/NuGet.Build.Packaging/commit/8926d8bb7c456eba2a934728213e2d34bbd8f05e). I was not expecting a referenced project to verify *additionally* that its referencing projects have certain properties :\.

How could we enable that scenario?

**Comment by emgarten** [comment]
If we did skip the TFM compatibility check restore would end up selecting strange dependencies for packages within the project. 

NuGet needs a TFM to base the decision of which dependency group is nearest when walking the dependency graph. I don't see how we could remove the requirement and not end up with very random results.

Example: Project target framework: ``any``
Package dependency groups: win8, native, net45

There's no way to decide which group should be selected, they are all equally unrelated and compatible with ``any``. If each group has different packages under it then the result is that restore ends up with a random set of packages.

**Comment by kzu** [comment]
The point is that for a nugetizer project it makes no sense to restore anything. Maybe the authoring project should set that flag to false then? A package added to such a project is only used to define a dependency that should end up in the resulting nupkg as a dependency, that's all.

Thoughts?

**Comment by emgarten** [comment]
A property to disabling restore for the project could work. What causes the project to get restored today? Does it have PackageReferences in the authoring project? Or just child projects?

**Comment by kzu** [comment]
Yes, the authoring uses PackageReference. References projects could of course also use them

**Comment by mthamil** [comment]
Is there anything I can do to the project files in the meantime as a work around?

**Comment by kzu** [comment]
I wonder if setting `ResolveNuGetPackages=false` would work?

**Comment by emgarten** [comment]
There isn't a flag for this currently (at least that I know of)

**Comment by kzu** [comment]
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props#L77-L78 ?

**Comment by emgarten** [comment]
@kzu that handles reading the restore outputs, it doesn't stop restore itself.

**Comment by mthamil** [comment]
I'm still keeping an eye on this, but I figured out how to control versioning with the new autopackaging of netstandard projects by using environment variables.

**Comment by kzu** [comment]
@emgarten we currently have this in place: https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/VisualStudio/NuGet.Packaging.VisualStudio/Targets/NuGet.Packaging.Authoring.targets#L18-L20

Shouldn't that be enough to make restore happy?

**Comment by kzu** [comment]
Fixed in https://github.com/NuGet/NuGet.Build.Packaging/pull/120

If you have already unfolded a .nuproj project, plz updated it to include the [following three elements](https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/VisualStudio/NuGet.Packaging.VisualStudio.15/Templates/Projects/Nuget/Package/Package.nuproj#L20-L22) for proper restore behavior.
