### ISSUE TITLE
[Test Failure] The installed package can’t be added to reference on multiple projects

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4862]
**NuGet Version:** NuGet 4.3.0-Beta1-2413 (Insertable)
**VS Version:** D15VSUWPT 26320.03
**OS Version:** Windows 10 RS2_Release 15062.0.170316-1539

**Repro Steps:**
1.	Create a solution included two C# Class Library (Universal Windows) projects (renamed PJ1 and PJ2).
2.	**Add reference** PJ2 to PJ1 (PJ1->PJ2).
3.	Open the ‘Manage NuGet Packages…’ for **PJ1 project**.
4.	Install package ‘Newtonsoft.Json’ into PJ1project by PM UI.
5.	Open the ‘Reference’ node under the PJ1 project.

**Expected Result:**
The package ‘Newtonsoft.Json’ is added to PJ1 reference.

**Actual Result:**
 The package ‘Newtonsoft.Json’ is not added to PJ1 reference as below screenshot.
![88775963222222](https://cloud.githubusercontent.com/assets/20632775/24138626/e6cf74d0-0e53-11e7-91a3-73abfe18a767.png)

**More info:**
This issue **not happened** on D15Rel 26320.00 + NuGet Client Release-4.1.0-RTM-2405.

**Comment by rrelyea** [comment]
@emgarten - does this sound like a non-NuGet issue? I guess we could test this with 4.1.0-rtm on vsuwpt to determine that.

**Comment by emgarten** [comment]
This should be read from the projectFileDependencies section of the project.assets.json file. If it exists there then NuGet is doing the right thing.

**Comment by v-nancyj** [comment]
Update **Actual Result:**
The **package ‘Newtonsoft.Json’** is not added to PJ1 reference as above screenshot.

**Comment by emgarten** [comment]
@v-nancyj does newtonsoft.json exist in obj\project.assets.json under projectFileDependencies?

**Comment by v-nancyj** [comment]
@emgarten Yes,the newtonsoft.json exists in obj\project.assets.json file

**Comment by emgarten** [comment]
> Yes,the newtonsoft.json exists in obj\project.assets.json file

This looks like a project system issue then.

**Comment by v-luzh** [comment]
@rrelyea, this issue is fixed on VSUWPT 26509.00+NuGet Client 4.3.0.4052 according to our verification. Please help to close this bug, thanks.
