### ISSUE TITLE
dotnet nuget push - Missing value for option

### ISSUE THREAD

**Issue by dtretyakov** [NuGet/Home#4864]
```
> dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1
```

When you trying to specify `--no-symbols` or `--disable-buffering` flag push command fails with:
```
dotnet nuget push **.nupkg -k ******* --no-symbols
Specify --help for a list of available options and commands.
error: Missing value for option 'no-symbols'

dotnet nuget push **.nupkg -k ******* --disable-buffering
Specify --help for a list of available options and commands.
error: Missing value for option 'disable-buffering'
```

Why should we need to provide some value for these flags and why it does not present in the docs?

**Comment by emgarten** [comment]
These flags should not take values.

https://github.com/NuGet/NuGet.Client/blob/a7e7dbba7a19b1fb26fc0f628f0b3cffe09651b6/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PushCommand.cs#L61

**Comment by Kampfmoehre** [comment]
I have the same problem, workaround for me is to specify `-n true`

**Comment by CoskunSunali** [comment]
The issue appears when one uses `dotnet nuget push` too.

**Comment by gpresland** [comment]
Getting this error despite documentation stating no value to be specified:

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore2x#options

**Comment by f00f** [comment]
Same here :-(

Happens (at least) for `--no-symbols` and `--interactive`.

```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.109
 Commit:    586f23c400

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.109\

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.2.109 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by coultonluke** [comment]
Same

**Comment by donnie-msft** [comment]
Looks (cautiously) simple to fix. For some reason these options are set to expect a SingleValue which doesn't make sense at a glance.

**Comment by Mazas17** [comment]
For me workaround was to use `--no-symbols 1`

**Comment by donnie-msft** [comment]
I'll take a look as part of Quality Week in a couple weeks.
Considering the workarounds that are in-place, will have to evaluate not breaking everybody by fixing this.

**Comment by babelshift** [comment]
Should be simple enough to work as expected if no value is supplied. In the case where people are supplying workaround values, just let them override the behavior.
