### ISSUE TITLE
NuGet.VisualStudioExtension: NuGet in Intranet not useable (without Internet connection) 

### ISSUE THREAD

**Issue by MichaelSteinecke** [NuGet/Home#4865]
## Details about Problem
When working with NuGet VS AddIn on computers with network connection, but without internet connection, the AddIn tries to load additional package information from the publisher URL and freezes eventually due to failing DNS requests and timeouts.

The entire issues has been discussed previously in issue #1056 [https://github.com/NuGet/Home/issues/1056](url) and should have been fixed with 3.4. However, it seems the fix has never been included in the main branch. In the VS2017 client, the bug is still present (or at least a similar one).

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS2015 & VS2017 UI

NuGet version (x.x.x.xxx):
Probably every Version

dotnet.exe --version (if appropriate):

VS version (if appropriate):
2010-2017

OS version (i.e. win10 v1607 (14393.321)):
Win7, Win 10

Worked before? If so, with which NuGet version:
A private build from @zhili1208 for 3.3 had fixed the issue

## Detailed repro steps so we can see the same problem
[https://github.com/NuGet/Home/issues/1056#issuecomment-128834527](url)

**Comment by emgarten** [comment]
@Torgrimm please try the latest version of NuGet in VS 15.4 and let us know if this issue still exists.
