### ISSUE TITLE
Enable UWP and ProjectJson Migration related E2E tests

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#4866]
Disabling 3 tests - 

1. Test-UwpPackageRefClassLibraryCreate
2. Test-UwpPackageRefClassLibInstallPackage
3. Test-MigrateVanilaUwpProjectJsonToPackageReference

Reason -

Current E2E machines (Win2016 Server) do not allow creating new UWP projects.

Fix - 

Next set of machines created for E2E will need to have client/developer experience added on during install.

**Comment by rohit21agrawal** [comment]
@mishra14 provide the commit here that we can revert when this bug can be fixed.

**Comment by mishra14** [comment]
Commit: https://github.com/NuGet/NuGet.Client/commit/98c810eadd6d614425abf437de27c9d2ed8e7cb0

**Comment by mishra14** [comment]
Fixed for VSTS with https://github.com/NuGet/NuGet.Client/commit/79a745606a61368228bc7b87700aed0de0aacd14
