### ISSUE TITLE
[VS2017RC3] EntityFramework - No app.config created when using "packageReference" iso packages.config

### ISSUE THREAD

**Issue by ErikEJ** [NuGet/Home#4876]
File, New Project, Console Appliation, Target .NET 4.0, add EntityFramework package, use PackageReference,
Result: app.config file with EF settings created
Actual: no app.config file at all... Causing EF to fail completely

Reported here: https://github.com/aspnet/EntityFramework6/issues/189

**Comment by emgarten** [comment]
From the referenced issued it sounds like this was previously using install.ps1. This is is no longer used since it requires visual studio to perform the commands, however with PackageReference uninstall/install could occur during a restore from the command line outside of visual studio.

@ErikEJ do you know what settings are needed in app.config to make this work?

**Comment by ErikEJ** [comment]
@emgarten Yes, the package was using install.ps1 - you can install the package in a class library to see what happens to app.config, basically this:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
     <configSections>
        
        <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
      </configSections>
      <entityFramework>
        <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
          <parameters>
            <parameter value="mssqllocaldb" />
          </parameters>
        </defaultConnectionFactory>
        <providers>
          <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
        </providers>
       </entityFramework>
    </configuration>

**Comment by emgarten** [comment]
Thanks for pasting it. It looks like the package will need to find a different way to configure itself that works from the command line and cross platform. I suggest working around it by adding this App.config in yourself.

**Comment by ErikEJ** [comment]
OK - that is understood - I just notice that you have now "broken" the second most downloaded NuGet package of all time "by design"

**Comment by rrelyea** [comment]
Thanks for reporting this. We are internally discussing how to best support the ecosystem.

This general problem, and the steps the NuGet team needs to drive, are explained here: https://github.com/NuGet/Home/issues/4942
