### ISSUE TITLE
[Test Failure] The package can’t be added to ‘Reference’ node by add package code to ‘project.csproj’ file

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4877]
**NuGet Version:** **NuGet 4.1.0-RTM-2427** (Insertable)
**VS Version:** D15Rel 26322.00
**OS Version:** Windows 10 RS2_Release 15063.0.170317-1834

**Repro Steps:**
1.	Create a new C# Console App (.NET Framework) project.
2.	Right click the project and select ‘Unload Project’.
3.	Right click the project and select ‘Edit project.csproj’.
4.	Add the following properties to the **property** group  the top of the csproj file:
![333](https://cloud.githubusercontent.com/assets/20632775/24240717/93c93708-0fed-11e7-8fd0-c69872d6eaff.png)

5.	Add the following reference to the csproj file, before the final targets **import** line starting with <Import Project="$(MSBuildToolsPath)…>:
![444](https://cloud.githubusercontent.com/assets/20632775/24240724/97d6c068-0fed-11e7-9bcc-56aadf3e3465.png)

6.	Save the csproj file and reload project.
7.	Right click the solution node and click ‘Restore NuGet Package’
8.	Open PM UI and ‘Reference’ expender, the package is installed in PM UI **but not** added to ‘Reference’ as below screenshot.
![555](https://cloud.githubusercontent.com/assets/20632775/24240737/a136278e-0fed-11e7-9c7b-a69dbcab4084.png)

9.	Install package ‘NUnit’ with PM UI, the installed package ‘Newtonsoft.Json’ and ‘NUnit’ are added to ‘Reference’ **together** as below screenshot.
![222](https://cloud.githubusercontent.com/assets/20632775/24240753/aafb500a-0fed-11e7-97d7-baa45280aa13.png)

**Comment by jainaashish** [comment]
This isn’t a valid test case now. Instead of doing this, you should follow below steps:
-	Create a new C# Console App (.NET Framework) project.
-	Enable “Allow package format chooser dialog” from tools -> options -> NuGet
-	Open PM UI and install newtonsoft.json package as PackageReference
-	Verify package is successfully installed and appears in Project References.

**Comment by rrelyea** [comment]
@jainaashish sent email to @v-nancyj about this. closing. please open a new issue if the new repro steps shows any problem.
