### ISSUE TITLE
nuget pack csproj -version overrides version of dependencis with *

### ISSUE THREAD

**Issue by maciejw** [NuGet/Home#4878]
When I use project.json and class library, with dependency version *
{
  "runtimes": { "win": {} },
  "frameworks": { "net461": {} },
  "dependencies": {
    "NLog": "*"
  }
}

and nuget.exe pack ClassLibrary1\ClassLibrary1.csproj -version 1.2.3

will put wrong version of my dependency in nuspec

<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ClassLibrary1</id>
    <version>1.2.3</version>
    <authors>author</authors>
    <owners>owner</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="NLog" version="1.2.3" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>

        <dependency id="NLog" version="1.2.3" exclude="Build,Analyzers" /> 

should look like that:

        <dependency id="NLog" version="4.4.4" exclude="Build,Analyzers" />

because this version was restored and project was compiled with.

I'm using nuget.exe version 3.5.0.1938 and 4.0.0.2283

**Comment by emgarten** [comment]
Nuspec dependencies cannot contain a ``*``, pack gives you the version of the package that your code was compiled again.

Users can opt in to floating package versions themselves, but getting them from a package would be unexpected. When floating major versions with a ``*`` something will eventually break and this would leave users of the package in a broken state without making any changes themselves.
