### ISSUE TITLE
NuGet v3 fails to install StyleCop.Analyzers.1.0.0-alpha005

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#488]
I can install alpha004 into my class library just fine. But updating to alpha005, or installing it fresh, always yields this error:

> update-package : Missing dependency information for package: StyleCop.Analyzers
At line:1 char:1
+ update-package StyleCop.Analyzers -version 1.0.0-alpha005
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

Is this a known bug?

See DotNetAnalyzers/StyleCopAnalyzers#713

**Comment by AArnott** [comment]
Also noticed that this command tries to install alpha004 instead of alpha005

> PM> install-package stylecop.analyzers -pre
Attempting to gather dependencies information for package 'stylecop.analyzers.1.0.0-alpha004' with respect to project targeting '.NETFramework, Version=v4.5.1'

**Comment by johnataylor** [comment]
This appears to have hit a known issue we have for the services regarding some of the data getting out of sync. We are working on a fix. This does not appear to be a problem in the client code.

**Comment by AArnott** [comment]
Thanks, @johnataylor. Would that also explain why it takes 1-2 *minutes* to install it even when it does work?
