### ISSUE TITLE
ProjectReference treats paths to projects case sensitive and can not resolve projects if caseingis different for folder name

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#4880]
## Details about Problem

Create a sample class library A , and then create another classs library B and put it into some subfolder. Then add reference form A to B.

  <ItemGroup>
    <ProjectReference Include="..\SomeFolder\B\B.csproj" />
  </ItemGroup>

 after restore is done, open A project file and change SomeFolder with SomeFol**D**er. Restore would complaiN:

Unable to resolve 'c:\users\antonpis\documents\visual studio 2017\Projects\A\SomeFolDer\B\B.csproj' for '.NETCoreApp,Version=v1.1'.

VS version (if appropriate):

Dev15 RTW

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

Create a sample class library A , and then create another classs library B and put it into some subfolder. Then add reference form A to B.

  <ItemGroup>
    <ProjectReference Include="..\SomeFolder\B\B.csproj" />
  </ItemGroup>

 after restore is done, open A project file and change SomeFolder with SomeFol**D**er. Restore would complaiN:

Unable to resolve 'c:\users\antonpis\documents\visual studio 2017\Projects\A\SomeFolDer\B\B.csproj' for '.NETCoreApp,Version=v1.1'.
### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbose | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by emgarten** [comment]
@rohit21agrawal this is fixed post-RTM already, right?

**Comment by rohit21agrawal** [comment]
Yes, but for 15.3

**Comment by emgarten** [comment]
@rohit21agrawal can you dupe it out?

**Comment by rohit21agrawal** [comment]
already fixed via : https://github.com/NuGet/NuGet.Client/pull/1191
