### ISSUE TITLE
Update NuGet coding guidelines 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4881]
NuGet coding guidelines were originally copied over from ASP. Much of the doc no longer applies such as the requirements on using xproj and sake. We should review and update this document with the team so that we can provide good instructions for community members looking to contribute.

https://github.com/NuGet/Home/wiki/Coding-Guidelines

**Comment by nkolev92** [comment]
Done: https://github.com/NuGet/NuGet.Client/blob/dev/docs/coding-guidelines.md
