### ISSUE TITLE
[Test Failure] The PMC doesn’t respond when updating package by command in Web Application

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#4885]
**NuGet Version:** NuGet 4.3.0-Beta1-2434 (Insertable)
**VS Version:** D15VSUWPT 26323.00
**OS Version:** Windows 10 RS2_Release 15063.0.170317-1834

**Repro Steps:**
1.	Create a C# ASP.NET Web Application (.NET Framework) -> MVC project.
2.	Open ‘Package Manager Console’.
3.	Type in ‘Update-Package’ and press ‘Enter’.

**Expected Result:**
The PMC should appear package update information.

**Actual Result:**
The PMC **doesn't respond** as below screenshot.
 ![1555555555555](https://cloud.githubusercontent.com/assets/20632775/24287454/caa1b63e-10b4-11e7-8627-e12b7f85920a.png)

**Notes:**
1.	The issue doesn't repro on D15VSUWPT 26323.00(NuGet 4.3.0-Beta1-2418 **Insertable**)
2.	The doesn't repro on D15Rel 26323.00 + NuGet 4.1.0-RTM-2427
3.	The issue doesn't repro on other C# ASP.NET Web Application (.NET Framework) projects.

**Comment by jainaashish** [comment]
Merged to release-4.3.0-beta1 branch as well df70151ad3e7c1a5b51c8b7c0e057ef0feb88bad
