### ISSUE TITLE
dotnet restore is extremly slow on Azure Websites

### ISSUE THREAD

**Issue by jozefizso** [NuGet/Home#4888]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version: 3.5.0.1938

dotnet.exe --version (if appropriate): 1.0.1

VS version (if appropriate): Microsoft Windows NT 6.2.9200.0

OS version (i.e. win10 v1607 (14393.321)): Azure App Service

## Detailed repro steps so we can see the same problem

1. Create ASP.NET Core project in Visual Studio 2017
2. Add some ASP.NET tools using nuget
3. Create Azure website and use Git deployment
4. Create kudu deployment script which restores packages
5. Run several deployments
6. Each deployment takes several minutes to complete, because NuGet restores packages for tens of seconds for each tool in the project.

## Other suggested things

Sample tools used by my project:
```
<DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0-msbuild3-final" />
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
<DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0-msbuild3-final" />
<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
```

I tried to optimize the speed by setting repository location to local drive using `SCM_REPOSITORY_PATH` env variable (as suggested here: https://blogs.msdn.microsoft.com/webdev/2016/07/13/notes-from-the-asp-net-community-standup-july-5-2016/ )

### Verbose Logs

Please include verbose logs (dotnet.exe restore --verbosity diag)

```
D:\local\repository\Project1>dotnet restore --verbosity diagnostic
D:\Program Files (x86)\dotnet\sdk\1.0.1\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /m /t:Restore /v:m /verbosity:diagnostic .\Project1.csproj
  Restoring packages for D:\local\repository\Project1\Project1.csproj...
  Lock file has not changed. Skipping lock file write. Path: D:\local\repository\Project1\obj\project.assets.json
  Restore completed in 12.71 sec for D:\local\repository\Project1\Project1.csproj.
  Restoring packages for D:\local\repository\Project1\Project1.csproj...
  Restore completed in 11.75 sec for D:\local\repository\Project1\Project1.csproj.
  Restoring packages for D:\local\repository\Project1\Project1.csproj...
  Restore completed in 12.41 sec for D:\local\repository\Project1\Project1.csproj.
  Restoring packages for D:\local\repository\Project1\Project1.csproj...
  Restore completed in 14.57 sec for D:\local\repository\Project1\Project1.csproj.
  Restoring packages for D:\local\repository\Project1\Project1.csproj...
  Restore completed in 14.65 sec for D:\local\repository\Project1\Project1.csproj.
  
  NuGet Config files used:
      D:\local\repository\NuGet.Config
      D:\local\AppData\NuGet\NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
```

### Sample Project

This is a private project, but a default ASP.NET Core app sample with added tools will do.

**Comment by emgarten** [comment]
Please try the latest 4.4.0 version of nuget, it contains a large number of perf fixes that should help your scenario.
