### ISSUE TITLE
Build warnings which should not  be ignored. PowerShellAutoCompleteResourceV2 and UIMetadataResourceV2 in Protocol do not use the CancellationToken and/or do not await but use the async keyword

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#489]
Build warnings which should not  be ignored. PowerShellAutoCompleteResourceV2 and UIMetadataResourceV2 in Protocol do not use the CancellationToken and/or do not await but use the async keyword

PowerShellAutoCompleteResourceV2.IdStartsWith and PowerShellAutoCompleteResourceV2.VersionStartsWith do not use the CancellationToken or the await keyword

UIMetadataResourceV2 do not use the CancellationToken or the await keyword. But, it may not be possible to use the CancellationToken easily, since NuGet.Core does not support CancellationToken. Perhaps, by using the xml parsing method used by dnu instead of using NuGet.Core

Following are the build warnings from protocol which should not be ignored

C:\nuget\NuGet.Protocol\src\NuGet.Protocol.VisualStudio\PowerShellAutoCompleteRe
sourceV2.cs(27,57): warning CS1998: This async method lacks 'await' operators an
d will run synchronously. Consider using the 'await' operator to await non-block
ing API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thr
ead.
C:\nuget\NuGet.Protocol\src\NuGet.Protocol.VisualStudio\PowerShellAutoCompleteRe
sourceV2.cs(41,63): warning CS1998: This async method lacks 'await' operators an
d will run synchronously. Consider using the 'await' operator to await non-block
ing API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thr
ead.
C:\nuget\NuGet.Protocol\src\NuGet.Protocol.VisualStudio\UIMetadataResourceV2.cs(
27,68): warning CS1998: This async method lacks 'await' operators and will run s
ynchronously. Consider using the 'await' operator to await non-blocking API call
s, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

**Comment by bhuvak** [comment]
Fixed with https://github.com/NuGet/NuGet3/pull/51
