### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#4890]
I'm exploring project "Package" options in VS 2017 for a .Net Core library project. I can see (and like) the settings for creating and building a package when the project is built.

But there are many settings and there seems to be no documentation for them.

For example "Repository URL" sounds like there's some support for publishing a package to a NuGet server but is that true?

And what of "Repository Type"?

Are all of these new features not documented? how can I find out what each setting does?

Also this recent article:

https://docs.microsoft.com/en-us/nuget/guides/create-net-standard-packages-vs2017

Makes no mention whatsoever of a project's new "Package" settings and implies manual editing of project files etc, yet the "Package" settings for a project seem to require no manual editing, which is it?

Thanks

(I understand that most are self explanatory but not all).

**Comment by emgarten** [comment]
Docs are continually being added. Please open issues for specific things you would like to see covered here: https://github.com/NuGet/docs.microsoft.com-nuget
