### ISSUE TITLE
TFM support in VS 2015: NetStandard2.0 & more

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4893]

**Comment by rrelyea** [comment]
This is the downlevel (VS2015) side to #4892
We need to consider which new TFMs from NuGet 4.3 need to be supported on VS2015.
Clearly NetStandard2.0 is a requirement.
Need to discuss Unity and Tizen with appropriate folks.

Current thought is that this is part of NuGet.tools.vsix v3.5.1 release for VS2015. We will selectively pick which fixes go there. TFMs being the key thing.

**Comment by emgarten** [comment]
@jainaashish @nkolev92 is the 3.6.0 release complete?

**Comment by nkolev92** [comment]
Yep this is done.
