### ISSUE TITLE
NET Core 2.0: CLI localized assemblies

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4896]
NET Core libraries got an exception for localization, in the last release. This release we may have to localize.
The following steps are required to enable localization:
1.	Make NuGet libraries localizable
2.	Localize the libraries
3.	[Open] Localization strategy w.r.t delivering the localized assemblies. Design needs to be reviewed
4.	Adapt the nupkg based on approach taken in #3.

**Comment by rrelyea** [comment]
dupe of #4336
