### ISSUE TITLE
Perf: Improve NuGet package 'restore' times

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4897]
Placeholder for all perf improvements in this area till VS 2017 Update 3

**Comment by anangaur** [comment]
[Rob] Measure current performance for restore times as part of the Perf Infra work being done with Apex in S116. Find bottlenecks and then improve.

[AG] This is an epic and hence individual perf fixes can be linked to this issue.

**Comment by emgarten** [comment]
I would say this is complete as part of the perf work for CLI 2.1
