### ISSUE TITLE
dotnet.exe - additional nuget functionality - update and update --all

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4899]
In the order or priority:

1. updateall
2. update - this functionality is present with 'add' command
3. list

**Comment by anangaur** [comment]
Making separate issues for each command

**Comment by anangaur** [comment]
Update - https://github.com/NuGet/Home/issues/4965
List - https://github.com/NuGet/Home/issues/4966

**Comment by mishra14** [comment]
dupe of https://github.com/NuGet/Home/issues/4102 and https://github.com/NuGet/Home/issues/4103
