### ISSUE TITLE
Could not add Application Insights to project when create an Azure Mobile App(Preview)

### ISSUE THREAD

**Issue by v-yanlli** [NuGet/Home#490]
1.Start VS.
2.New project->Web->ASP.NET Application->Check Add Application Insights->Azure Mobile App(Preview)
Result:There will be a dialog.
repro in api.nuget,org and nuget.org config.
![1](https://cloud.githubusercontent.com/assets/12131845/7342644/9e24be6c-ece9-11e4-9750-bb775c95d972.png)

**Comment by v-yanlli** [comment]
VS build is D14Rel.22823.01

**Comment by emgarten** [comment]
The resolution error occurs when the project loads and the script executor attempts to run all init.ps1 scripts. PS is using the resolver to find the order of dependencies, but the Owin package is missing (which could be an issue with the template for this project).

The resolver checks more than is needed and is too strict on missing packages for the init.ps1 run, this ordering should be done in a different way.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@20785be9ec6e4b521e3c945c2ae986190fb18db9
