### ISSUE TITLE
dotnet add tool

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4901]
_From @shanselman on March 27, 2017 4:10_

I wish we could

`dotnet add tool DotnetWatcher:1.0.0`

and get

```
<ItemGroup>
 <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="1.0.0" />
</ItemGroup>
```

_Copied from original issue: dotnet/cli#6156_

**Comment by awesley** [comment]
I request that this get prioritized as there are a good number of people producing documentation and tutorials on dotnet core with comments like "copy this csproj file".  Alleviating this problem early will improve the quality of education material related to .NET core and the tooling surrounding it.

**Comment by MaximRouiller** [comment]
Is there any progress?

**Comment by mishra14** [comment]
@rrelyea do we have a plan for this?

**Comment by rrelyea** [comment]
Sorry, cannot land 4.3 with this work done.

**Comment by MaximRouiller** [comment]
@rrelyea So this goes into the "we want to do it but don't have the time right now" bucket?

**Comment by johnkors** [comment]
> Sorry, cannot land 4.3 with this work done.

Not sure I understand that sentence.  :| Do you mean it'll have to wait, @rrelyea ?

**Comment by shanselman** [comment]
If I did a PR could it be done? Or are there too many moving parts?

**Comment by ibqn** [comment]
what is the status here? This one moves forward very slowly

**Comment by wholroyd** [comment]
Also interested in seeing this happen

**Comment by rrelyea** [comment]
Properly putting it in the backlog as 4.4 didn't happen as we hoped. @mishra14 wants to do this badly.  Just need to clear his plate of other critical things.

**Comment by fyn-dev** [comment]
Yes me too. I really need this feature.

**Comment by ertw** [comment]
I'd like to add that as a new user to .net core, this was a real blocker for me. I spent a long time trying to run `dotnet ef`, and the error messages from trying to run that command and from trying to add other packages were not clear, and didn't really point me in the correct direction. Also, most documentation still references project.json, making this even more confusing.

**Comment by shanselman** [comment]
@kathleendollard @rrelyea How we doing on this? Feels like just a day of someone's time. I'd do it if I could get this repo to build.

**Comment by mishra14** [comment]
@shanselman what issues are you having in building the repo?

**Comment by mishra14** [comment]
@ertw Can you please point us to documentation that you are referring to? I can look at getting ti fixed.

**Comment by ertw** [comment]
@mishra14 The out of date information I found mostly came from old MSDN posts and private bloggers. The canonical tutorial for EF (https://docs.microsoft.com/en-us/ef/core/get-started/netcore/new-db-sqlite) is up to date and in wiki form, so something I can edit as well if I find anything wrong. I'll let you know if I find any more Microsoft resources that are incorrect.

**Comment by evil-shrike** [comment]
Some more complains:
It's very unclear what is the point in marking a nuget package as cli tool if it's totally ignored on installing by nuget and dotnet-cli: 
I mean that if a DotnetCliTool-package with nuspec:
```
    <packageTypes>
      <packageType name="DotnetCliTool" />
    </packageTypes>
```
installed via `dotnet add package` will get into `PackageReference` as normal nuget package. And `dotnet <tool>` will not find it. 
If we have to tell dotnet explicitly that a package is a cli-tool via `DotNetCliToolReference` in csproj why then we have to set packageType for that package? 

But anyway. If such a notion as "custom cli tool" was introduced it should be supported by dotnet for installing. It's a must. Isn't it so hard to implement?

What's the point in distributing nuget packages with cli tools if while installed in common way they won't work?!

**Comment by cottsak** [comment]
Doco at https://github.com/aspnet/DotNetTools says `dotnet install tool dotnet-watch` but with `2.4.1` it's still not working.

[Instructions here](https://github.com/aspnet/DotNetTools/tree/release/2.0#how-to-install) still show manually installation. :cry:

**Comment by dasMulli** [comment]
@cottsak the syntax now changed to `dotnet install tool -g {something}` and you'd need a preview tooling that is at least 2.1.300-preview1-*. This isn't part of any released tooling yet.

**Comment by fcavaco** [comment]
@dasMulli , fine went through that and I am using 2.1.300-preview1-* SDK, nevertheless, it still does not add the tool in the project file as DotNetCliToolReference. talking about dotnet-watch for example. while creating a solution using shell script this forces me to manually edit the csproj file to add that reference still. as someone said before , if the package type is marked as a tool, that should suffice to add both entries in the proj file.

**Comment by KirkMunro** [comment]
Any update on this?

**Comment by dasMulli** [comment]
Is this still needed? `DotNetCliToolReference` is de-facto deprecated now with global tools.. (though some scenarios involving project or solution specific tools / versions still being thought about)

**Comment by KirkMunro** [comment]
Probably not. I came here looking for it because I was working through an ASP.NET Core 2.1 tutorial, but that tutorial needs updating so I think my issue was simply symptomatic of an out of date tutorial.

**Comment by shanselman** [comment]
@KirkMunro which tutorial?

**Comment by KirkMunro** [comment]
@shanselman [Razor Pages with Entity Framework Core in ASP.NET Core - Tutorial](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/intro?view=aspnetcore-2.1&tabs=visual-studio).

**Comment by ptoonen** [comment]
@dasMulli probably not, especially not when https://github.com/dotnet/cli/issues/10288 is resolved.

**Comment by KoalaBear84** [comment]
Still no progress?

**Comment by KathleenDollard** [comment]
[`DotNetCliToolReference` is being phased out.](https://github.com/dotnet/announcements/issues/107)

Please see the explanation there. 

As a result, I suggest this issue be closed. cc @rrelyea

**Comment by rrelyea** [comment]
Absolutely. Thx.
