### ISSUE TITLE
Restore not picking up PackageReference in legacy csproj

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#4904]
NuGet version: 4.0.0.2283

I'm attempting to convert [dotnet/roslyn](https://github.com/dotnet/roslyn) to use PackageReference over our csproj / project.json mix today.  The goal for the moment is to remain on the old project system so this isn't a full conversion to the new SDK.  It's only about moving to PackageReference.  

I've moved over a large set of our files but when I restore I'm getting the following error:

``` txt
Using Msbuild from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\msbuild\15.0\Bin'.
Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.
```

Clearly I'm missing something in the conversion but I can't determine what from the output.  Can someone get me pointed in the right direction here?

Repo steps:

``` cmd
> git clone https://github.com/jaredpar/roslyn
> git checkout repo-restore1
> powershell -NoProfile build\scripts\download-nuget.ps1
> NuGet.exe restore -msbuildpath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\msbuild\15.0\Bin" Compilers.sln
```

Note: this assumes that Visual Studio 2017 is installed at the above location.

**Comment by jainaashish** [comment]
Taking this forward in email. Will explain the discussion here later.

**Comment by jaredpar** [comment]
After some discussion the basic problem is that I'm trying something which is not supported.  The projects in Roslyn can be essentially broken up into two categories:

1. PCL producing Net Standard compatible libraries
1. Desktop projects

The errors were coming from my attempt to move 1 above to use PackageReference.  This is not a supported operation.  In order for us to move we'll need to convert these projects fully to the new csproj + SDK format first.
