### ISSUE TITLE
dependencies are not copied recursively

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4905]
https://github.com/NuGet/Home/issues/3830#issuecomment-278031018

http://disq.us/p/1ha0f36

NuGet does the right thing in copying only what's specified in <references>, but after that there's a step missing. Adding a reference is not just a matter of copying a dll to the bin. Perhaps taking the information from the assembly manifest, dependencies must be copied as well, recursively. If foo.dll depends on bar.dll, which in turn depends on baz.dll, then all three should end up in bin. And if lib contains other assemblies that are not an explicit (using <references>) or implicit dependency, then those should not end up in bin.

**Comment by emgarten** [comment]
This is for the most part determined by the SDK/build. To copy the complete closure users should do a publish if using the CLI.
