### ISSUE TITLE
Failed to resolve dotnet packages on some machines because feed defined in local NuGet.Config is ignored

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4907]
_From @hongdai on March 27, 2017 23:55_

Failed to resolve dotnet packages on some machines because feed defined in local NuGet.Config is ignored

For example, the below output shows the local config file is used, however the local feed is missing:

Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'.
NuGet Config files used:
C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
**C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap\NuGet.Config**
**Feeds used:
https://api.nuget.org/v3/index.json
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages**

I can use **dotnet add package -s <local feed>** to restore the package successfully. The problem is I need to create a process for this operation in the runtime and it's pretty expensive. **Is there an equivalent API I could use?**

**Any recommendation I can always resolve the package successfully?** It's a pretty bad experience for our customers.

Thanks,
Hong

_Copied from original issue: dotnet/roslyn-project-system#1871_

**Comment by davkean** [comment]
I'm not understanding the bug or the issue, can you clarify?

**Comment by davkean** [comment]
_From @hongdai on March 28, 2017 0:58_

1. The app is in: C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap
2. Under the root of the app, I have a local NuGet.Config that has the following package source information:
```
 <packageSources>
    <add key="SvcUtilLocalFeed" value="C:\myfeed" />
  </packageSources>
```
3. My project file depends on below package that is located under C:\myfeed
 `<PackageReference Include="dotnet-svcutil" Version="0.5.10327.0-preview"></PackageReference>
`
4. **dotnet restore** failed on some machines because it ignored the feed in the local NuGet.config, the log below shows **c:\myfeed is not used.**

Unable to resolve 'dotnet-svcutil (>= 0.5.10306-preview)' for '.NETCoreApp,Version=v1.1'.
NuGet Config files used:
C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
C:\Users\pennerg\AppData\Local\Temp\WCFConnectedService\2017_Mar_21_06_41_30\svcutil_bootstrap\NuGet.Config

**Feeds used:
https://api.nuget.org/v3/index.json
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages**

**Comment by emgarten** [comment]
@hongdai from what you've shared it looks like the config file is being used by the feed isn't used.

Try adding ``clear`` to the ``disabledPackageSources``, it is possible the source has been disabled in ``C:\Users\pennerg\AppData\Roaming\NuGet\NuGet.Config``. Adding the clear tag will make sure that this doesn't happen. Here's an example:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <packageSources>
    <add key="SvcUtilLocalFeed" value="C:\myfeed" />
  </packageSources>
  <disabledPackageSources>
     <clear />
  </disabledPackageSources>
</configuration>
```

**Comment by hongdai** [comment]
@emgarten  Adding the clear tag does not work, a customer just verified it.

**Comment by hongdai** [comment]
@emgarten Any other suggestions to workaround the issue?

**Comment by emgarten** [comment]
@jainaashish @zhili1208  can you take a look at this?

**Comment by OskarKlintrot** [comment]
Did you solve it @hongdai? I get the same issue. I can't use `dotnet add package -s` though. I get the same issue on [my own project on Travis (and locally)](https://travis-ci.org/Certaincy/Intranet/builds/240802420) as well as when trying with @andrewlock's [project](https://github.com/andrewlock/blog-examples/tree/master/AspNetCoreImageResizingService/AspNetCoreImageResizingService).

It fails on:
- Travis CI using Ubuntu 14.04 with CAKE
- W10 with CAKE
- W10 with dotnet restore
- W10 with dotnet add package
- W10 with nuget.exe

I'm using dotnet cli v1.0.4 both on Travis CI and locally.

**Comment by OskarKlintrot** [comment]
I forgot, it works just fine when adding the feed to the global `nuget.config` (and I did try to add the `disabledPackageSources` fix but it didn't help and I don't think Travis has any package source's disabled anyway...).

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
