### ISSUE TITLE
Updating packages deletes packages.config in TFS

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#491]
When there are projects in the solution that reference only one NuGet package, after updating the packages we get trapped with the following issue: (we use local TFS workspaces)

After updating, the package.config is marked as deleted in TFS, but there is a new package.config on the disk. The root cause seems to be that during update the old package is uninstalled, and because it was the last package, the package.config gets deleted, but the pending deletion is not restored before the new package.config is created upon installing the new package.

Now TFS won't allow to undo the deletion because the new package.config is already there. The only way to solve this is to 
- rename the new package.config on disk, 
- undo the deletion in TFS, 
- delete the old package.config restored by TFS on disk
- rename back the new package.config on disk.

If you have lot's of projects in the solution, this can be a very annoying task!

**Comment by yishaigalatzer** [comment]
@tom-englert are you using Visual Studio 2015 or an earlier version? We believe we fixed this for Visual studio 2015 (and don't currently plan to fix for 2013 and earlier),

**Comment by tom-englert** [comment]
I'm using VS2013, and due to company regulations we will probably have to go with this for the next years. So fixing this only for the early adopters will leave the main stream struggling!
Maybe you can point out the commit where this fix was done for 2015, so we can do the back-port by our own?

**Comment by yishaigalatzer** [comment]
This fix should go to 2.8.6 release (for 2013 downlevel release)

**Comment by AndriySvyryd** [comment]
I wasn't able to repro this using VS2013.4 with NuGet 2.8.60318.734
@tom-englert Are you using different versions?

**Comment by tom-englert** [comment]
That's exactly the configuration I use. I have a local workspace and use the PM GUI, not the console.

**Comment by AndriySvyryd** [comment]
Tried console and GUI. Upgrading EntityFramework 6.0.0 to 6.1.3.
packages.config is deleted, then recreated and checked out for editing.

@tom-englert Does this happen for a specific project type or package?

As a workaround can you pend packages.config before performing the upgrade?

**Comment by tom-englert** [comment]
I have played around and found the following: 
It's rarely reproducible with one project, but with three projects in the solution where two of them had outdated packages to update it always happened - sometimes only in one and sometimes in both projects.
I have prepared a solution on codeplex.com, if you have an account there I could add you to the team members so you can reuse this for testing.

**Comment by yishaigalatzer** [comment]
Please share the link to the project.

**Comment by AndriySvyryd** [comment]
My Codeplex username is the same - AndriySvyryd

**Comment by tom-englert** [comment]
https://nugettestclient.codeplex.com, added AndriySvyryd as coordinator

**Comment by AndriySvyryd** [comment]
Tried updating JetBrains.Annotations 9 times, all succeeded.

**Comment by tom-englert** [comment]
Since it's not the same behavior always I guess this could be a timing issue, where the local workspace might detect a delete only if there is a certain time gap between deleting the file an removing it from the solution - so your test machine is maybe either too slow or too fast. 
Can you give me a hint were I can find the source code for the package manager, so I'm able to debug this?

**Comment by AndriySvyryd** [comment]
The issue is most likely here - https://nuget.codeplex.com/SourceControl/latest#src/TeamFoundationServer/TfsFileSystem.cs

**Comment by wkosten1982** [comment]
Facing the same problems with the latest version of visual studio 2013 against tfs 2013. When the nuget update is performed the following happens;

Update Package A from 1.0 to 1.1

---- BEFORE UPDATE
Solution
Project 1
	-> packages.config
		- Package A = 1.0
		- Package B = 1.1
Project 2
    -> packages.config
		- Package A = 1.0

		
---- AFTER UPDATE
Solution
Project 1
	-> packages.config (state=edit)
		- Package A = 1.0
		- Package B = 1.1
Project 2
    -> packages.config (state=deleted)
		- Package A = 1.0

Look like when there is only one package installed in a project a remove is called first by the nuget update command, you can see that in the output window as well. Then it will try to add the new package but the item already has the state deleted. 

I have no idea what is causing this behavior, the same solution and same action performed on another machine by a colleague is going fine. I might have some other extensions installed on my pc.
I have repaired VS2013 installation, re-installed nuget extensions but nothing seems to help.

Do you guys have found a solution for your problem and maybe mine?

**Comment by yishaigalatzer** [comment]
These are good hints. We are trying to get a repro and fix it this week.

If you are worried about server connection,
try to create a local workspace.

**Comment by tom-englert** [comment]
I did some more investigation and found the following: 
- I could not reproduce it on my laptop with only SSDs.
- I can reliably reproduce it on my PC where the code is checked out to a HDD.
- When debugging the source code with some breakpoints set it was never reproducible.
- Once I could reproduce it and luckily watch in solution explorer that the symbol on the packages.config changed from "checked out" (correct) to "deleted" (wrong) **after** nuget had finished updating!
- Looking at the source code I found that the TfsFileSystem.cs is never used in this code path. 
 
My conclusion: 

The VS local workspace handler tries to detect file changes and gets a "File Deleted" event from the disk, which is handled asynchronous. If the event arrives **after** nuget has already added the file again - which seems to happen mostly on HDD, SSD is probably too fast - the local workspace handler marks the file as deleted, without cross-checking that the file is back again.

To prove my assumption I have added a Thread.Sleep(1000) in the loop of method ExecuteActions() [src\V3\NuGet.Client\Installation\ActionExecutor.cs line 93], to ensure the file is not restored before the local workspace has processed all disk events. This reliably solved the problem.

**Comment by tom-englert** [comment]
@yishaigalatzer: This **only** happens if you use a **local** workspace!

**Comment by wkosten1982** [comment]
I am looking forward for a patch, this will probably be fixed in the 3.0 release only isnt?

**Comment by yishaigalatzer** [comment]
from what @tom-englert is describing this looks like a bug in TFS local workspace implementation. So if this gets fixed by TFS, it is up to them where they want to move it to.

@wkosten1982 we are going to try and fix for both.

Aside - Personally after working on both TFS and Git implementations/integrations before I find that git works better with local workspaces, and since TFS now natively supports git, it might be the better way to go?

**Comment by tom-englert** [comment]
I've added a bug report for VS here: https://connect.microsoft.com/VisualStudio/feedback/details/1344773/tfs-local-workspace-marks-files-as-deleted
It would be a good idea if as many people as possible vote for this and mark "repros" to give it some importance.

We use TFS repositories in our company; even though technical possible git is not an option for us.

**Comment by yishaigalatzer** [comment]
We need this in older version of NuGet as well, so putting in the 2.8.7 milestone. This needs to be fixed in the 3.x train as well

**Comment by taylorjonl** [comment]
This isn't only for local workspaces, it happens on normal workspaces also.  I here late at night again fixing a solution with 30 projects because it deleted the packages.config file and the developer didn't check this before they blindly checked in the changes.

I surely hope a fix is found and put into VS2013, my team will likley not get VS2015 for at least a year or so, corporations are very slow to adopt and if I have to fix these issues with these solutions as frequently as I am now I am likely just going to drop nuget use because it takes hours to recover sometimes.

**Comment by yishaigalatzer** [comment]
This is tracking a fix for 2013

**Comment by makhdumi** [comment]
+1 

I can consistently reproduce this issue using the nuget executable:
`nuget.exe update MySolution.sln -Source https://my-nuget-repo.com/nuget`

Running the above will update the .csproj but delete the packages.config for all projects with only one package.

**Comment by yishaigalatzer** [comment]
@makhdumi please update your executable to 3.3

**Comment by ShaneCourtrille** [comment]
I am seeing this on VS2015 using 3.3 with an SSD drive so I don't think it's slow HD related like @tom-englert thought..

**Comment by wkostn** [comment]
I am also facing the same issue still with VS2015, its going fine when all files are checked out before the update is applied. I guess we just have to live with this behavior haha.

**Comment by yishaigalatzer** [comment]
What version of nuget are you using? This was supposed to be fixed in 3.3, but if not I'd love a good repro

**Comment by bitbonk** [comment]
I got the same issue today, using  Visual Studio Enterprise 2015 Version 14.0.24720.00 Update 1 with Nuget Package Manager 3.3.0

**Comment by ddrinka** [comment]
I'm seeing this issue as well after installing VS2015 Update 1 (no issues with 2015 RTM).  I'm running 14.0.24720, NuGet 3.3.0.167.  I can reproduce all day long, and would love a fix in the short term.  Let me know if I can help debug.

**Comment by yishaigalatzer** [comment]
This issue is tracking VS 2013, can you open a new bug, and provide exact repro steps (what version of TFS, and how it is configured as well as specific steps). Please mention @zhili1208 on the bug

**Comment by ddrinka** [comment]
For those of you who recently commented with VS2015 issues, I have opened Issue #2215 which documents the recurrence of this issue in Update 1.

**Comment by codefox42** [comment]
I believe I am experiencing the same or at least a similar behavior with VS2015.1 (14.0.24720.00)) and **Mercurial** (via [VisualHg 1.1.7](http://visualhg.codeplex.com/)): `packages.config` _gets deleted_ if the single NuGet package it consists is updated (and _not only marked as deleted_). So I guess in my case this is nothing VisualHg can change? (NuGet 3.3.0.167)

**Comment by zhili1208** [comment]
@mdvtj Yes, NuGet 3.3 has this bug, it's fixed in 3.4-rtm.

https://github.com/NuGet/NuGet.Client/commit/1d38c36b9c266cf13f591b2824cfd57f83ee1942#diff-18b7a6d1d31f5d214f93945b51923913

**Comment by codefox42** [comment]
@zhili1208, thanks for the good news! Now patiently waiting for 3.4-rtm (as the currently available 3.4-rc (3.4.0.653) seems not yet to be including the mentioned fix). (Or is 3.4-rtm available for download by other means?)

**Comment by nbenninghoff** [comment]
This just happened to me in VS2015 update2
Package Manager Console Host Version 3.4.4.1321

**Comment by adrianm64** [comment]
I have packages which contain source files.
This TFS problem occur around 50% of the time on the source files when I update these packages.
Sometimes some files in a package works fine while others are marked as deleted.

VS2015 update 3, nuget 3.4.4

**Comment by stgit123** [comment]
This is happening to us consistently and often. 
VS2015 Update 3 14.0.25422.01
Package Manager Console Host Version 3.4.4.1321

**Comment by cdichter** [comment]
So you've been talking about this problem for two years, and I still see it in VS 2015 update 3 (NuGet Package Manager 3.5.0).

How about a fix or a work-around?

It does appear to be improved in VS 2017 (newer version of NuGet).

**Comment by dee-see** [comment]
Same issue here on fully updated VS2015.3. It happens randomly to everyone on the team.

It hasn't happened yet with VS2017 though,

**Comment by NArnott** [comment]
I'm using VS 2017, and it's still happening. It appears to be random, as it sometimes does it, and other times not, for the exact same action.

**Comment by MatteoSp** [comment]
same here. VS2017, randomly.

**Comment by dee-see** [comment]
I've just updated packages across several solutions for about 200 projects and 13 packages.config were deleted.

**Comment by jainaashish** [comment]
We're not planning to release this fix for VS2013 which is what this issue originally was. So if anyone still facing this issue for VS2017 please log a new issue with relevant details.

**Comment by stgit123** [comment]
I HAVE raised a new issue for later VS versions ([#4449](https://github.com/NuGet/Home/issues/4449)), which you have closed without fixing the problem either.

**Comment by tom-englert** [comment]
@jainaashish just happened to me now in VS2017 - this has never been fixed for no version.

Seems the only strategy here is to obfuscate the problem by randomly changing issues and versions.

**Comment by jainaashish** [comment]
I was going through the comments and from there it looks like it was fixed in VS 2015 which is why I closed it, apology if that wasn't the case.

Then @stgit123 also mentioned about #4449 which gives the more appropriate reasoning of closing this issue and asking to move from packages.config to PackageReference. Since our current direction is making PackageReference more compatible for existing solutions and packages so we might not be able to get everything back to packages.config.

**Comment by dee-see** [comment]
I made a PowerShell script that automates the rename-undelete-rename task for every package.config that has a delete change pending but isn't really deleted following a package update.

https://gist.github.com/dee-see/7acf6fd5efc06ff7cd447c07563a0041

Throwing it out there if it can help anyone in the same situation.
