### ISSUE TITLE
Extensibility model for package download

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#4913]
This request is from VSTS.

1.  A mechanism for providing custom package download implementation through a plugin.
2.  A plugin must run in a process separate from NuGet tools.

The primary motivation is to provide alternate forms of package transmission.

CC @jmyersmsft

**Comment by maartenba** [comment]
Is there a spec for this somewhere?

**Comment by jmyersmsft** [comment]
Details are still in progress, but it's here: https://github.com/NuGet/Home/wiki/NuGet-Package-Download-Plugin

**Comment by maartenba** [comment]
Thanks!
