### ISSUE TITLE
Nuget Command Line not executing Powershell

### ISSUE THREAD

**Issue by v703612** [NuGet/Home#4914]
Hello,

We are currently trying to implement the following functionality
https://everydaylifein.net/netframework/running-powershell-scripts-during-nuget-package-installation-and-removal.html .

This all works great when we use the visual studio package manager console. But when we want to execute this with Powershell or Command line this doesn't work. So this means that the packages are get correctly but the powershell script is not executed. Do you have any experience with this?

**Comment by davidfowl** [comment]
It never did execute on the command line and it doesn't even execute in Visual Studio going forward. Don't rely on it.

**Comment by v703612** [comment]
The execution does work on Visual studio that we tested yesterday and this works but we just want to launch our powershell script on nuget install

**Comment by davidfowl** [comment]
> The execution does work on Visual studio that we tested yesterday and this works but we just want to launch our powershell script on nuget install

Read this http://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html
