### ISSUE TITLE
Unable to Install a .Net Core class lib nuget to a .net core console app

### ISSUE THREAD

**Issue by Mythreyeehr** [NuGet/Home#4915]
I am using VS2015 Enterprise edition with .NetCore tools Preview 2

Here is what I did, Created a  .net core class library project (framework 4.6). Added a simple log class. Project.json file looks like below 
```
{
  "version": "1.0.0",
  "dependencies": {
    "log4net": "2.0.8",
    "Microsoft.AspNetCore.Diagnostics.Abstractions": "1.0.0",
    "Microsoft.AspNetCore.Http": "1.0.2",
    "NETStandard.Library": "1.6.0"
  },
  "frameworks": {
    "netstandard1.6": {
      "imports": [ "dnxcore50" ]
    }
  }
}

```

Created a nuget package "Logger" for this. 

Tried installing this package into a .net core console application. Project.json file is below:
```
`{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.1"
    },
    "Logger": "1.0.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": ["dnxcore50"]
    }
  }
}
```
`

But when I install I get error. It says 

Package Logger 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Logger 1.0.0 supports: net (.NETFramework,Version=v0.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

Anybody has an insight why this happens. I saw many reporting similar issue.

**Comment by jainaashish** [comment]
@Mythreyeehr how did you created this Logger package? and look into created nupkg if you've any valid library assembly in there.

Ideally, you should be using `dotnet pack project.json` command to create the right nupkg.

**Comment by Mythreyeehr** [comment]
I used `nuget pack logger.nuspec `  command. I shall give a try with what you suggested

**Comment by Mythreyeehr** [comment]
I tried creating using the `dotnet pack project.json `command  it creates both .nupkg and .symbols.nupkg.

But in this case, packaging succeeds even if there is no .nuspec file. This was little surprising for me. I always assumed .nuspec file is required for creating a package.

Anyhow, restore still fails.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps. 

Please also try with a PackageReference project instead of a project.json based project.
