### ISSUE TITLE
[Test Failure] Package Reference is added into the wrong project when using ‘PackageReference’ format in multiple-projects

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4916]
**NuGet Version:** NuGet 4.2.0-RTM-2431
**VS Version:** D15PreRel 26327.00
**OS Version:** Windows 10 RS2_Release 15165.1000.170325-1411

**Repro Steps:**
1. Check ‘**Allow format selection on first package install’** format in NuGet Package Manager setting dialog.
2. Restart VS and create a C# Console App (.NET Framework)-ConsoleApp1.
3. Add another C# Console App (.NET Framework)-ConsoleApp2 into this solution.
4. Open the ‘Manage NuGet Packages…’ for **both projects**.
5. Install package ‘Newtonsoft.Json’ into ConsoleApp2 by PM UI with **PackageReference** format.
6. Click back to the NuGet Package Manager tab of ConsoleApp1 and try to install package ‘NUnit’ into ConsoleApp1 by PM UI with **PackageReference** format.

**Expected Result:**
The package reference of ‘NUnit’ is added into ConsoleApp1 successfully.

**Actual Result:**
The package reference of ‘NUnit’ is added into ConsoleApp2 as below screenshot.
![packagereferenceaddedintowrongproject](https://cloud.githubusercontent.com/assets/20632625/24400399/e0ec404a-13e2-11e7-8ad6-4100b6692372.PNG)

**Note:**
1. It doesn’t repro if you open the PM UI of ConsoleApp1 after step5.
2. It repro on VSUWPT 26327.03+NuGet Client 4.3.0-beta1-2439.
3. It repro on D15Rel 26324.01 (NuGet Client 4.1.0-RTM-2427).

**Comment by jainaashish** [comment]
dupe# https://github.com/NuGet/Home/issues/4675
