### ISSUE TITLE
nVenture issue with auto restore performance

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4917]
Email discussion with Jerome (nVenture) about auto restore performance issue. We've got the perf etl logs from the customer to investigate.

**Comment by jainaashish** [comment]
Replied to customer with my findings and asked for more details about the specific scenario. Awaiting customer response.

**Comment by jainaashish** [comment]
Some improvements made for auto restore scenario via https://github.com/NuGet/NuGet.Client/pull/1285 

But still, waiting on the customer to get his specific repro and if we can improve performance there.

**Comment by rrelyea** [comment]
@jainaashish - have we gotten more info back from customer?

**Comment by jainaashish** [comment]
@rrelyea No, let me send a reminder to him.

**Comment by jainaashish** [comment]
NuGet restore perf has been improved since this issue was logged. And now there are couple of other issues with Xamarin and Roslyn to improve customer experience.
