### ISSUE TITLE
Can't install a package when there are some leftovers in the packages folder

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#492]
After installing some packages I found that some projects had the wrong Target Framework set, so I have reverted all changes, including removal of all packages.config and the repository.config. Only the downloaded packages binaries are in the packages folder.
Now with the package manager there is the following problem: 

Installed packages shows "No items found", which is correct since there is nothing installed yet.

Now searching for the desired package online shows the package already with a green check mark, indicating that this package is already installed - and there is no way to reinstall, it never appears again in the installed packages list!

**Comment by yishaigalatzer** [comment]
This still repros in 3.3, I don't know that we can clean this completely (imagine one content of the file is missing), but at least we can make the installed list and the indication on browse the same.

You can drop to PS and reinstall the package, or clean out the folder, but I'm sure you already knew that.

**Comment by jainaashish** [comment]
This has been fixed in Visual Studio 2017. Please try with latest VS2017 15.5.
