### ISSUE TITLE
Inconsistent behavior between VS2017 and cli restore command regarding contentFiles inclusion

### ISSUE THREAD

**Issue by jeromelaban** [NuGet/Home#4921]
Using nuget Version: 4.0.0.2283 and VS2017+26228.4, restoring a package that contains "compile" content files:
- nuget.exe generates a .nuget.g.props file that only contains imported .props files
- VS2017 generates a .nuget.g.props file that contains all the "compile" contentFiles, making builds from the IDE fail because of duplicate items sent to the CSC task.

This happens because _NuGetContentItems also appends the same "compile" files to the Compile item group.

This only seems to happen if the packages are referenced through the new PackageReference nodes.

Adding this works around the issue:

```
  <Target Name="AssetsCleanup" BeforeTargets="ResolveNuGetPackageAssets">
     <ItemGroup>
      <Compile Remove="%(Compile.Identity)" Condition="'%(Compile.NuGetPackageId)'!=''" />
    </ItemGroup>
     <ItemGroup>
      <Page Remove="%(Page.Identity)" Condition="'%(Page.NuGetPackageId)'!=''" />
    </ItemGroup>
  </Target>
```

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
