### ISSUE TITLE
Suggest needed: equivalent API for dotnet add package -s command

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4923]
_From @hongdai on March 28, 2017 21:9_

Hi,
I need to use dotnet add package -s to add/restore a nuget package to a .net core project. I need to do it in runtime. Is there an equivalent API I could use so that I do not need to create a process?

Thanks,
Hong

_Copied from original issue: dotnet/cli#6179_

**Comment by livarcocc** [comment]
These APIs are owned by NuGet. So, moving this issue there.

**Comment by emgarten** [comment]
Adding a package involves adding a `PackageReference` item to the project file, most of what happens there is handled by MSBuild.

At this time there are no plans to create an API in nuget to handle all of this programmatically.
