### ISSUE TITLE
NuGet.exe command line help uses HTTP link to docs even though HTTPS is available

### ISSUE THREAD

**Issue by Eilon** [NuGet/Home#4925]
## Details about Problem

NuGet product used: NuGet.exe
NuGet Version: 4.0.0.2283

## Detailed repro steps so we can see the same problem

1. Run NuGet.exe from Windows command line without any params
2. The help output shows an HTTP link even though HTTPS is available:
   * http://docs.nuget.org/docs/reference/command-line-reference
   * Could be: https://docs.nuget.org/docs/reference/command-line-reference

**Comment by zivkan** [comment]
Fixed in 2019: https://github.com/NuGet/NuGet.Client/commit/bd0c5fb12076a7f1678d825541a978caa4ac0bc0
