### ISSUE TITLE
Avoid user specific data from nuget props/targets files

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4929]
Starting after my team updated to VS2017, the .nuget.props file for one of our projects now started to have user-specific data in it:

```
<RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
<ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">D:\Users\XXXXX\Source\Repos\XXX\App\project.lock.json</ProjectAssetsFile>
<NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
<NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\XXXXXX\.nuget\packages\</NuGetPackageFolders>
<NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">ProjectJson</NuGetProjectStyle>
<NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.0.0</NuGetToolVersion>
```

So either we should get rid of user specific data from these properties (have relative paths) or include this in .gitignore file by default.

**Comment by emgarten** [comment]
Users can specify any folder as the global packages folder during a restore, and the way build and other tools discover that path is through the project.assets.json and targets files. So this isn't something we can get rid of.

As already mentioned users should not check these intermediate files into source control. Updating .gitignore sounds like the right approach.
