### ISSUE TITLE
Make it easier to omit packages from TFVC

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#493]
We should review the `.nuget\nuget.config` requirement to `disableSourceControlIntegration` for TFVC. Combined with adding a .gitignore/.tfignore, this currently seems over-complicated.

**Comment by vtbassmatt** [comment]
I got a Send-a-Smile from an external customer about this issue today.

**Comment by jdrake3** [comment]
I am not sure why this is closed as it continues to happen in 2015 today.  Even with .nuget/NuGet.config in place.

**Comment by jainaashish** [comment]
We've been focusing on PackageReference, where there is no solution level packages folder. Also, we don't see getting to this in near future.
