### ISSUE TITLE
Filename or extension is too long.

### ISSUE THREAD

**Issue by mukhole** [NuGet/Home#4931]
Nuget.exe hits the command line string limit and displays error "Filename or extension is too long."  for solutions having a large number of projects (200+) and which reside deep within a drive:
nuget restore C:\User\<name>\documents\projects\...\..\..\..\*.sln.
Directory shortening is a workaround for this problem, but the same problem manifests itself if the project name (<ProjectName> tag in .vcxproj file) is too long. The only difference being, when the project name is too long we get a different error message:
_### Unable to resolve 'E:\WinObjC\WinObjC_Internal\Source\winmd2objc\ObjCUWP\ObjCUWP\Windows\projects\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget.vcxproj' for 'UAP,Version=v10.0'.
Unable to resolve 'E:\WinObjC\WinObjC_Internal\Source\winmd2objc\ObjCUWP\ObjCUWP\Windows\projects\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget.vcxproj' for 'UAP,Version=v10.0 (win)'.
Unable to resolve 'E:\WinObjC\WinObjC_Internal\Source\winmd2objc\ObjCUWP\ObjCUWP\Windows\projects\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget.vcxproj' for 'UAP,Version=v10.0 (win-x64)'.
Unable to resolve 'E:\WinObjC\WinObjC_Internal\Source\winmd2objc\ObjCUWP\ObjCUWP\Windows\projects\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget\ObjCUWP_Windows_ApplicationModel_DataTransfer_ShareTarget.vcxproj' for 'UAP,Version=v10.0 (win-x86)'._

It would be better if Nuget could pass the parameters in a file to avoid hitting command line string limit and display a more informative error message when <ProjectName> in .vcxproj files is too long.

NuGet product used: NuGet.exe

NuGet version : 4.0.0.2283

VS version (if appropriate): VS 2017

OS version Win10 Build 15164.rs_onecore_dep.170323-1738

## Detailed repro steps so we can see the same problem

1. You will need a solution with more than 200 projects with very long project names (ie > 50 characters), put it deep within some drive.

2. Open Developer command prompt for VS, try to restore the packages for solution:
nuget restore <path to the deeply nested solution file>

Even using a project which references all other projects to restore package using -Recursive switch will not work as we hit the <ProjectName> too long issue.

[NugetRestoreErrors.txt](https://github.com/NuGet/Home/files/880210/NugetRestoreErrors.txt)

[NugetPersistDGOutput.txt](https://github.com/NuGet/Home/files/880209/NugetPersistDGOutput.txt)

**Comment by marky15** [comment]
To solve this problem I recommend the use of a long  path tool. This will help you on any kinds of similar issues. proven and tested by many users.

**Comment by emgarten** [comment]
The workaround for this is to use ``msbuild /t:restore``
