### ISSUE TITLE
For UWP projects, keep TPMinV and project.json in sync

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#4932]
keep TPMinV (proj property) in sync with project.json frameworks version for uap during any package install or update or uninstall (from VS as well as any CLI)

**Comment by shishirx34** [comment]
Got auto closed.

**Comment by karann-msft** [comment]
Did this get auto-closed again?

**Comment by shishirx34** [comment]
Nope.. closed it because its done.
