### ISSUE TITLE
Targeting Multiple Frameworks and dotnet pack fails

### ISSUE THREAD

**Issue by patricknolan** [NuGet/Home#4934]
Attached is a copy of my project file Configuration.EntityFramework.csproj (Configuration.EntityFramework.zip).

It was converted from xproj to csproj when I installed 2017. 

I am targeting multiple frameworks 
`<TargetFrameworks>netcoreapp1.0;net462</TargetFrameworks>`

And performing a dotnet pack command
```
<Target Name="PostcompileScript" AfterTargets="Build" Condition=" '$(IsCrossTargetingBuild)' != 'true' ">
   <Exec Command="dotnet pack --no-build --configuration $(Configuration)" />
</Target>
```

When I try and build I get the error  - (full error attached as msbuild.error.txt)
Error	MSB4018	The "PackTask" task failed unexpectedly. [D:\workspace\tagit\Configuration.EntityFramework\src\Configuration.EntityFramework\Configuration.EntityFramework.csproj]	Configuration.EntityFramework	C:\Program Files\dotnet\sdk\1.0.0\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets	104	
Error	MSB4018	System.IO.FileNotFoundException: File not found: 'D:\workspace\tagit\Configuration.EntityFramework\src\Configuration.EntityFramework\bin\Debug\net462\Configuration.EntityFramework.dll'. [D:\workspace\tagit\Configuration.EntityFramework\src\Configuration.EntityFramework\Configuration.EntityFramework.csproj]	

This is happening because net462 fails to build. If I remove the dotnet pack command both netcoreapp1.0 and net462 build successfully. If I add the dotnet pack command back in and only target netcoreapp1.0 or net462 then it works and I get no error.

Could you please advise if this is a bug\issue?

My environment info is 
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

[Configuration.EntityFramework.zip](https://github.com/NuGet/Home/files/881230/Configuration.EntityFramework.zip)

[msbuild error.txt](https://github.com/NuGet/Home/files/881242/msbuild.error.txt)

**Comment by rohit21agrawal** [comment]
@patricknolan are you trying to basically execute pack every time you build your project?
If that is the case, I suggest you set the property ```<GeneratePackageOnBuild>true</GeneratePackageOnBuild>``` and it will take care of everything for you.

**Comment by emgarten** [comment]
Closing, let me know if @rohit21agrawal's answer does not work for you
