### ISSUE TITLE
Intellisense doesn’t work when typing ‘Get-Package n’ in PMC of the project with the packages ‘N***’ installed

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#4936]
**NuGet Version:** NuGet 4.2.0-RTM-2446
**VS Version:** D15PreRel 26329.00
**OS Version:** Windows 10 RS2_Release 15063.2.170323-1837

**Repro Steps:**
1. Create a C# Class Library (.NET Framework) via VS.
2. Open the ‘Manage NuGet Packages…’ for the project.
3. Install packages **‘Newtonsoft.Json 10.0.1’** and **‘NUnit 3.6.1’**.
4. Open Package Manager Console.
5. Type **‘Get-Package n’** and hit Tab.

**Expected Result:**
There is a list contain the installed packages who's name begin with n.

**Actual Result:**
The intellisense doesn’t work as below screenshot.
![getpackagenointellisense](https://cloud.githubusercontent.com/assets/20632625/24497826/458b2f7e-156f-11e7-86cc-c7f251a91c90.png)

**Note:**
1.It also repro on D15Rel 26329.02 (NuGet Client 4.1.0-RTM-2427).
2.It also repro on VSUWPT 26329.01 + NuGet Client 4.3.0-beta1-2444.
3.The description of 'Get-Package' is: _Gets the set of installed packages._ So the intellisense should works.

**Comment by emgarten** [comment]
@v-luzh does this still repro? is this a regression?

**Comment by v-luzh** [comment]
@emgarten Yes, it still repro on D15Rel 27108.00 (NuGet Client 4.5.0.4574). We believe it is not a regression.

**Comment by CiciLi1** [comment]
Verified this issue on VS Main\34807.21 + NuGet Client Dev\6.11.0.9, it's fixed, so closed it, thanks!
