### ISSUE TITLE
NET Core 2.0: VS/Dotnet CLI should start using existing NuGet functionality: FallBack folders

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4939]
Tracking issue for dotnet issue : https://github.com/dotnet/cli/issues/6100. May require some work at NuGet end.

**Comment by rrelyea** [comment]
CLI is now using these. Enabled it by providing support to set fallback folders via msbuild props.
(otherwise, setting via nuget.config didn't work -- as it impacted v1 and v2 cli -- which didn't work with v1)

**Comment by rrelyea** [comment]
Fallback folders enable the first time restore to be much faster, as it avoids disk activity.
