### ISSUE TITLE
Creat new WAP, open package.config ,show one warning.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#494]
Repro steps:
1.New Project -> C# ->Web->asp.net Web Application->Web Forms/Web API etc.
2.Open package.config ,show one warning.
3.Close package.config, there is no warning.
Also repro in Dev12.
Repro build:D14Rel 22823.01(VS+SDK), Main 22827.01,Main 22828.01,WPT 22828.00(VS+SDK+NuGet VSIX)
![capture](https://cloud.githubusercontent.com/assets/12129698/7366071/44336356-edc8-11e4-929e-db81ef90c18a.PNG)

**Comment by deepakaravindr** [comment]
This has always been the case since there is no schema for packages.config. Closing this as Won't Fix
