### ISSUE TITLE
[Bug with repro] - Sdk attribute and vstemplate nuget wizard interop

### ISSUE THREAD

**Issue by dazinator** [NuGet/Home#4943]
## Details about Problem

UPDATE: sample to reproduce here: https://github.com/dazinator/VSProjectSystem/tree/issue-nugetwizard

1. Run the sample
2. Create the project from the project template
3. During project creation, nuget will error:

![image](https://cloud.githubusercontent.com/assets/3176632/24580249/c24ea4da-16fc-11e7-8093-b8d358e74fef.png)

Details:

I have a project template, and inside the project template I am using:

```
 <WizardExtension>
    <Assembly>NuGet.VisualStudio.Interop, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>NuGet.VisualStudio.TemplateWizard</FullClassName>
  </WizardExtension>
  <WizardData>
    <packages repository="extension"
          repositoryId="WindowsScript.ProjectType..61d255dd-a819-4936-9f07-e660d0572111">
      <package id="newtonsoft.json" version="10.0.1" />
    </packages>
  </WizardData>
```

..to install a nuget package when the project is created.

My project file uses the new "sdk" attribute to import the .net sdk.

When I create the project from this template, in VS, this is what happens:

![image](https://cloud.githubusercontent.com/assets/3176632/24580301/aa0c329c-16fd-11e7-8078-c5766e609b88.png)

It looks like NuGet is unable to load necessary project information.

However after the project has been created, I can install the same nuget package using the nuget package management UI, without any issues.

My project file looks like this:

```

<Project Sdk="Microsoft.NET.Sdk">

  -- some stuff
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net45</TargetFramework>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <RootNamespace>MySample</RootNamespace>
    <ProjectFileToPack>$(MSBuildProjectFullPath)</ProjectFileToPack>
  </PropertyGroup>
    
  </Project>

```

I should also mention, that I have an item template, in which I bundle a nuget package using exactly the same technique and this works fine. So it only seems to be an issue that occurs in project templates, during project creation

NuGet product used: VS UI.
NuGet version (4.0.0.0):
VS version: 2017 update 1.
OS version: win 10:

**Comment by dazinator** [comment]
Have updated with a sample to reproduce: https://github.com/dazinator/VSProjectSystem/tree/issue-nugetwizard

**Comment by dazinator** [comment]
Also, if I switch to using a `<PackageReference>` in my proj file, nuget restores the package when I create the project and this works. However this has the downside that I can't install the package that is bundled with my vsix as nuget package restore can only restore from configured nuget repositories. The wizard extension allows me to install the package from my extensions installation directory. This is important as it allows the project creation process to work irrespective of internet connectivity or nuget configuration.

**Comment by timcomport** [comment]
I'm also seeing this issue on Visual Studio 15.3.4.

As shown in the first screenshot the error is _"The operation failed as details for the project \<ProjectName\> could not be loaded."_

The project is working when the template uses the old csproj format but failing as above with the new "sdk" csproj format.

**Comment by dazinator** [comment]
I also raised this issue on the vsproject system repo as I was not sure who it sits with: https://github.com/Microsoft/VSProjectSystem/issues/221

**Comment by emgarten** [comment]
`File > New Project` for SDK projects uses auto restore to run the restore/install. You should be able to write the PackageReferences directly into the template.

Please let me know if this doesn't work for you.

**Comment by dazinator** [comment]
@emgarten adding a `PackageReference` directly to the template does work but it means if the nuget package isn't in the users nuget package directory already (Which it won't be for the first project they create on their machine) it will be downloaded from the internet (requiring web access). I want to bundle the nuget package inside my vsix and install it from there - which was previously possible using the nuget interop approach. This means the user can create a new project and have the nuget packages installed even if they have no internet connection..
