### ISSUE TITLE
nuget restore fails with version 4.0.0 on a specific solution

### ISSUE THREAD

**Issue by jairbubbles** [NuGet/Home#4947]
## Details about Problem

NuGet product used: NuGet.exe 4.0.0.2283
Worked before? If so, with which NuGet version: 3.5.0.1938

## Detailed repro steps so we can see the same problem

1. Unzip this example:  [issueNuGetRestore.zip](https://github.com/NuGet/Home/files/886143/issueNuGetRestore.zip)

2.  Execute `nuget.exe restore "projects\win64/MaxHammer.vs2015.sln"` (project.json) or `nuget.exe restore "projects\win64/MaxHammer.vs2017.sln"` (packageReference)

In both cases it will fail:

```
Restoring packages for C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\ubisoft.controls\project.json...
Unable to resolve 'C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\Ubisoft.ApplicationModel\ApplicationModel.vs2015.csproj (>= 1.0.0)' for '.NETFramework,Version=v4.6.1'.
Unable to resolve 'C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\Ubisoft.ApplicationModel\ApplicationModel.vs2015.csproj (>= 1.0.0)' for '.NETFramework,Version=v4.6.1 (win)'.
Unable to resolve 'C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\Ubisoft.ApplicationModel\ApplicationModel.vs2015.csproj (>= 1.0.0)' for '.NETFramework,Version=v4.6.1 (win-anycpu)'.
Unable to resolve 'C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\Ubisoft.ApplicationModel\ApplicationModel.vs2015.csproj (>= 1.0.0)' for '.NETFramework,Version=v4.6.1 (win-x64)'.
Unable to resolve 'C:\Users\jrichard\Desktop\issueNuGetRestore\extern\alexandrie\libraries\Ubisoft.ApplicationModel\ApplicationModel.vs2015.csproj (>= 1.0.0)' for '.NETFramework,Version=v4.6.1 (win-x86)'.
```

With nuget 3.5 the exact same code will succeed.

## Some observations that might help you out

- The solution contains a CLR project.
- If I removed the . in `alexandrie\libraries` subfolders the problem was not there anymore
- Sometimes the project reference for ApplicationModel appeared with a NuGet icon in VisualStudio (very weird)
- I tried to produce a more simple example but it wouldn't fail, the problem seems to be tied to the exotic folder structure

Thx !

**Comment by stonstad** [comment]
I can reproduce this error with VS 2017 Update 1.

**Comment by jairbubbles** [comment]
I tried to debug directly with NuGet source code but I couldn't compile it 😭

**Comment by jairbubbles** [comment]
I've tried again with `nuget.exe` 4.3.0 and it's now working properly.
