### ISSUE TITLE
IVsPackageInstaller, method InstallPackage package management format PackageReference

### ISSUE THREAD

**Issue by WimBoom** [NuGet/Home#4948]
## Details about Problem
When we use the IVsPackageInstaller, method InstallPackage from dll (Nuget.VisualStudio.dll) in a VSIX template project to create a MVC5 project, the NuGets are installed with the old package management format: packages.config. How can IVsPackageInstaller, method InstallPackage use the latest package management format: PackageReference? In Visual Studio we have select default package management format PackageReference.

NuGet product used:
Nuget.VisualStudio.dll 

NuGet version: 
4.1.0.2427

VS version: 
Microsoft Visual Studio Enterprise 2017 Preview (2) 15.1 (26323.1)

OS version: 
win10

Worked before? If so, with which NuGet version:
No

**Comment by jainaashish** [comment]
Currently it doesn't allow you to specify the package format type in `installPackage` api but we'll add that option soon. 

For now, as a workaround you can define `RestoreProjectStyle` msbuild property in your project or template and set it to `PackageReference` then while installing the first package into the project, it will use that property to select the package format type.

`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`

**Comment by jainaashish** [comment]
closing it as dupe of https://github.com/NuGet/Home/issues/7005 

we'll run with that issue to at least read package management format set in visual studio to install package with the same format

**Comment by jainaashish** [comment]
closing it as dupe of https://github.com/NuGet/Home/issues/7005 

we'll run with that issue to at least read package management format set in visual studio to install package with the same format
