### ISSUE TITLE
Package Manager UI shows package summary while the website shows package description

### ISSUE THREAD

**Issue by xt0rted** [NuGet/Home#4955]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2015 & 2017

OS version (i.e. win10 v1607 (14393.321)): Win 10 build 15063

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Search for `nancy` on nuget.org

2. Search for `nancy` in VS

3. Results are the same, but the description of the packages differ (website uses the description while VS uses the summary)

This originally came up in https://github.com/NancyFx/Nancy/issues/2727

**Comment by emgarten** [comment]
This is currently the expected behavior, remove the summary to keep both in sync.
