### ISSUE TITLE
Auto copy dll.config files to build output for non json projects

### ISSUE THREAD

**Issue by realvictorprm** [NuGet/Home#4959]
### This issue is only related to cross platform projects targeting Mono and .NET Framework 

Currently it isn't possible to declare dll.config files as files which must be copied like assemblies to the build output directory. 

For my library this is _breaking_ the whole intention of a nuget package. If the dll.config file isn't  copied for OS like linux and Mac the library will through runtime exceptions and so it won't be usable.I prefer that the devs hasn't to mind about how my library works. 

So in general:
The current nuspec layout does not allow to specify files expect dll's to be copied to the output folder.
My suggestion is to make changes to the specification which allows dll.config files being copied to the output path. There is no reason to not copy them if they're specified as _assembly_ for example. Theyre as important as the assembly itself.

However, beside all that general stuff. Is there any nice workaround?

PS:
1. For projects which are using project.json there is the contentFile keyword. However as told already this is not possible for _old_ projects types.

2. If it's possible to fix this with making small changed please give me a clue how to and I'll make a PR.

**Comment by emgarten** [comment]
@realvictorprm to get control over how the files are copied use a targets file in the `build/` folder of the package. You can reference the assemblies and config files from the targets file.

**Comment by gilescope** [comment]
It's not unreasonable to expect .dll.config files to be supported by default.
