### ISSUE TITLE
Add quirking/package version to eliminate the "any" lib folder

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#496]
Strawman: We should add a new meta tag to nuspec specifying that this package has no any folder. This will work only for 2.8.6 (minclient), and after 2.8.6. is public on all platforms we should stop allowing packages without it to be uploaded to the nuget.org server.

This will eliminate the need to specify new TFMs if ever any new one shows up, because the any (any unknown folder under lib is considered any today) both on clients and server.

CC @davidfowl @emgarten

**Comment by yishaigalatzer** [comment]
@pranavkm please work with @davidfowl on how this looks like and get it into 2.8.6 and 3.0.

We should then block new packages of the shape being shipped in the gallery.

**Comment by yishaigalatzer** [comment]
Work begun here but never completed:

https://github.com/Haacked/NuGet/commit/c06b0d3cb3a95822555e65b915d7e50029712493 

This will need to ship downlevel

**Comment by jainaashish** [comment]
We're not going to get to this in near future since our focus has been on other priorities like performance, full integration into MSBuild with PackageReference.
