### ISSUE TITLE
The help link on NuGet settings window is incorrect

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4960]
1. The help link seems to be incorrect
2. The drop-down overlaps the label in high DPI (regression?)

![image](https://cloud.githubusercontent.com/assets/14800916/24619675/a898dd36-184f-11e7-94ab-d467afeaa8d3.png)

**Comment by karann-msft** [comment]
to Rob for triage.

**Comment by kraigb** [comment]
The ? is likely a docs issue, because VS generates a query using certain F1 keywords that we don't currently have in the metadata of the NuGet docs pages. @karann-msft please the Docs label to this issue.

**Comment by karann-msft** [comment]
I reactivated the high dpi bug we had before....feels like a regression....https://github.com/NuGet/Home/issues/4439

Let's use this issue just for the help link

**Comment by karann-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #523](https://github.com/NuGet/docs.microsoft.com-nuget/issues/523) via [**ZenHub**](https://www.zenhub.com/)
