### ISSUE TITLE
Strange dependency resolution for NETStandard library

### ISSUE THREAD

**Issue by MatthewSteeples** [NuGet/Home#4961]
From NuGet within Visual Studio (Version 4.0.0.2323), trying to update hyak.common to the latest version (1.1.2) from 1.1.0. 

> Attempting to gather dependency information for multiple packages with respect to project 'Ledgerscope.Core', targeting '.NETFramework,Version=v4.6.2'
Gathering dependency information took 13.05 sec
Attempting to resolve dependencies for multiple packages.
Update-Package : Unable to resolve dependencies. 'Newtonsoft.Json 10.0.2' is not compatible with 'Hyak.Common 1.1.2 constraint: Newtonsoft.Json (>= 6.0.8 && < 7.0.0)'.
At line:1 char:1
> + Update-Package hyak.common

My understanding is that as this is a .NET 4.6.2 project then it should be happy resolving the [dependencies](https://www.nuget.org/packages/Hyak.Common/1.1.2) for .NETStandard 1.5. The packages.config has this package (and every other package) installed as net462. Before starting this I had Newtonsoft.JSON 9.0.1 installed, but upgraded it to 10.0.2 to see if that made a difference at all.

If you need any project files or anything then let me know

## Details about Problem

NuGet product used: VS UI and Package Manager Console

NuGet version (x.x.x.xxx): 4.0.0.2323

VS version (if appropriate): 15.0.26228.10

OS version: 15063.11

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
