### ISSUE TITLE
NET Core 2.0: Finish UI work for auto-ref packages like NET Core libraries

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4964]
The following highlighted text needs to be fixed as it shows little information: 
![image](https://cloud.githubusercontent.com/assets/14800916/26323825/398d3074-3ee5-11e7-9570-23d512f095d9.png)

**Comment by anangaur** [comment]
New text: 

`AutoReferenced: This package is part of a larger framework or SDK and should not be updated independently. To update the package, update the SDK to which it belongs. More details: https://go.microsoft.com/fwlink/?linkid=841238`


Additionally we should update the new screenshot on the docs page: https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#updating-a-package

**Comment by mellinoe** [comment]
What's the significance of "AutoReferenced" ? Can that part be removed, or rephrased like "This package is automatically referenced by the SDK. It is part of ..."

**Comment by anangaur** [comment]
@mellinoe Thanks for the suggestion. I left the AutoReferenced word there to refer the term from documentation. But now that I think about it, documentation can be reworded too :)

`This package is automatically referenced by the SDK and should not be updated independently. To update the package, update the SDK to which it belongs. More details: https://go.microsoft.com/fwlink/?linkid=841238`

Also created a doc issue to remove the "AutoReferenced" keyword.

**Comment by anangaur** [comment]
@shishirx34: We need to make the text shorter as it doesn't look good on the UI. Also we should make the link URL a hyper link.

**Updated text:** 
Implicitly referenced by an SDK. To update the package, update the SDK to which it belongs. [Learn more](https://go.microsoft.com/fwlink/?linkid=841238)
