### ISSUE TITLE
Read PackageReferences from CollectPackageReferences

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#4967]
Restore should read PackageReferences from ``CollectPackageReferences`` instead of the items directly.

see: https://github.com/dotnet/project-system/issues/653

**Comment by emgarten** [comment]
As part of this work we will need to ensure that PackageReferences coming from targets/props in packages are ignored. This would cause the first restore to give a different result than the 2nd and 3rd restores.

**Comment by emgarten** [comment]
https://github.com/dotnet/project-system/blob/708af7ef0b285f85fcc624e0b5c1a8ab193ea573/src/Targets/Microsoft.Managed.DesignTime.targets#L272

**Comment by davkean** [comment]
@emgarten What release will this be in - so that we can remove our version?

**Comment by emgarten** [comment]
@davkean VS 15.4, NuGet 4.4.0
