### ISSUE TITLE
There should be a way to revert to packages.config if you select the csproj format

### ISSUE THREAD

**Issue by wayne-o** [NuGet/Home#4973]
I created a project using the csproj format for packages and everything worked fine - now I am trying to get it working on appveyor and i'm having all manner of issues and there is no way to revert the project to using packages.config 

My only option it seems is to create a whole new solution and copy everything over rewiring as I go - I tried commenting out the package refs form the csproj files and readding them as packlages.config but that also led to all sorts of issues

**Comment by emgarten** [comment]
Please open issues or comment in existing issues that cover your problems with PackageReference.  Packages.config will remain supported, but automatically migrating projects from PR -> PC is not something that will be supported.
