### ISSUE TITLE
AutoReferenced UI tweaks

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#4977]
The highlighted text in the following UI has to be improved:
![image](https://cloud.githubusercontent.com/assets/14800916/24822010/edfdac3a-1ba6-11e7-92ae-070f41107267.png)

**Comment by anangaur** [comment]
Proposal:
This package reference is implicitly added and managed by the SDK installed. To change the package reference version, you need to change the underlying SDK that you project depends on. [Learn more](TBD link)

**Comment by rrelyea** [comment]
@shishirx34 did this already right? (title was mislabeled)

**Comment by shishirx34** [comment]
@rrelyea Yes, with this PR: https://github.com/NuGet/NuGet.Client/pull/1399 
Tracking issue was: https://github.com/NuGet/Home/issues/4964
May be close this one as duplicate?

**Comment by rrelyea** [comment]
Dupe of https://github.com/NuGet/Home/issues/4964
