### ISSUE TITLE
Fix MEF part constructors with thread affinity. Also, switch to main thread where IServiceProvider is used or casts are performed

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#498]
Fix MEF part constructors with thread affinity. Also, switch to main thread where IServiceProvider is used or casts are performed

This related to https://github.com/NuGet/Home/issues/449. This is phase-2. Related item is phase-1

**Comment by deepakaravindr** [comment]
Note that this causes a hang right now when creating a new MVC WebApp or a Universal application

**Comment by AndriySvyryd** [comment]
This reproes for all ASP.NET 4.6 templates except the Empty one

**Comment by emgarten** [comment]
This appears to be fixed.
