### ISSUE TITLE
VS NuGet restore is causing VS to not responding for few minutes (photos app)

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#4986]
internal bug: Bug 401176:VS NuGet restore is causing VS to not responding for few minutes (photos app)

**Comment by MikhailArkhipov** [comment]
Frankly simple switch to turn automatic off would also be useful. Even it is not blocking it will burn CPU cycles (VS has many threads) and drain laptop battery.

**Comment by emgarten** [comment]
@MikhailArkhipov you can disable automatic package restore under the Visual Studio options for NuGet.

**Comment by MikhailArkhipov** [comment]
Which one of the options is it?

![image](https://cloud.githubusercontent.com/assets/12820357/25308035/3d4e18ea-2761-11e7-8e4f-2808136ea547.png)

I would like to restore packages when I do run build.

**Comment by emgarten** [comment]
There currently isn't an option to disable auto restore separate from on build restore. The pattern I typically use when restore gets in the way is to uncheck both of those boxes, and then manually restore when needed using the right click restore packages option on the solution node from solution explorer.

**Comment by alpaix** [comment]
Not for 4.2. Duplicate to #4457.
