### ISSUE TITLE
extern alias support for NuGet package references

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#4989]
* [Design document](https://github.com/NuGet/Home/blob/dev/designs/PackageReference-Extern-Alias.md)

_From @fubar-coder on April 5, 2017 15:59_

Currently, when a NuGet package reference is added, there is no way to set the alias from the project system for the new style csproj projects.

This feature is needed, because NuGet package references don't result in direct assembly references any more and only those can have an alias.

My proposal is to add the alias(es) to all assemblies referenced for the NuGet package, but not the indirectly referenced NuGet packages.

_Copied from original issue: dotnet/project-system#1930_

notes

https://github.com/dotnet/sdk/issues/10947 The build tasks on (.NET Core SDK side)
https://github.com/dotnet/NuGet.BuildTasks/issues/70 The build tasks for the non-SDK based PackageReference
https://github.com/dotnet/project-system/issues/6011 Nomination updates on project-system side.

**Comment by davkean** [comment]
Great suggestion. I'll move this over to the NuGet repo, they own the syntax for PackageReference.

**Comment by andymac4182** [comment]
This would be great since we are running into this issue due to https://www.nuget.org/packages/StackExchange.Redis/ and https://www.nuget.org/packages/StackExchange.Redis.StrongName/

**Comment by brianpos** [comment]
We have this issue to if we want to add both of these
https://www.nuget.org/packages/Hl7.Fhir.DSTU2
https://www.nuget.org/packages/Hl7.Fhir.STU3

**Comment by wburgers** [comment]
@brianpos exactly the same problem here.
We would like to run both fhir versions next to each other.

**Comment by brianpos** [comment]
@wburgers i have a project using the extern alias trick https://github.com/brianpos/FhirPathTester but do have to set manually after inclusion. So can't wait for this to be fixed.

**Comment by JoseFMP** [comment]
+1, can't wait for this. I think this is important because right now different packages implementing same namespaces.

@brianpos could you share your trick please?

**Comment by fubar-coder** [comment]
IIRC you can configure NuGet to store the NuGet packages in an packages folder instead of using the cache in the users home folder using the NuGet.config. This allows you to manually specify project-relative assembly references (via `Reference Update`) which can include the alias. The problem with this approach is, that you have to update the reference whenever the package version changes. However, you **can** restore the packages into folders without the package version of you don't have conflicting package versions.

**Comment by JoseFMP** [comment]
Ok, so basically referencing the .dll quasi-manually and including then the alias, right? I was also thinking about that as a work around

**Comment by davkean** [comment]
As a side note, a workaround is to write a target that does something like this: https://github.com/dotnet/project-system/blob/master/build/Targets/VSL.Imports.targets#L340.

Here we're setting the EmbedInteropTypes metadata, but the same could be applied to alias.

**Comment by andymac4182** [comment]
It would be great if someone on the NuGet team could point in the right direction of the repo that requires the change. I am sure people are happy to look if they know where to look.

**Comment by davkean** [comment]
I think they'll need a design first, I don't see a flushed out proposal on syntax/behavior. Once we do that, we'll then need to work with the project systems (http://github.com/dotnet/project-system) and SDK (http://github.com/dotnet/project-system) to add/respect the property so that it can be passed to NuGet/show in Properties, etc, added to the `<REference/>` when we dynamically produce them, and then plumbed through pack (what does an aliased set of references do when we add the package as a reference in the nuspec?). Just to set expectations, this isn't a couple of lines change.

**Comment by davkean** [comment]
I'll help sponsor, point to the locations that need to change in SDK, ProjectSystem (NuGet team will need to jump in on the nuget side, as I don't have context), and driving this through, if a community member wants to pick up the design/changes.

**Comment by gertjvr** [comment]
After some experimentation and got it to work.

Placed the below snippet into my csproj file where I had both references of `StackExchange.Redis` and `StackExchange.Redis.StrongName`  nuget dependencies.

```xml
<Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'StackExchange.Redis.StrongName'">
        <Aliases>signed</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

**Comment by JoseFMP** [comment]
@gertjvr sounds great! I will give it a try over here

**Comment by ewoutkramer** [comment]
> if a community member wants to pick up the design/changes.

What would that entail?  Sorry, I am not very familiar with the process!

**Comment by fubar-coder** [comment]
@gertjvr Just to clarify: `ChangeAliasesOfStrongNameAssemblies` is just a random target name? Does it need to be called/targeted somewhere?

**Comment by gertjvr** [comment]
@fubar-coder the target name is just a random name same goes for the alias signed, the snippet above was all I added to my csproj file.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.6.0" />
    <PackageReference Include="AutofacSerilogIntegration" Version="2.0.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.1.5" />
    <PackageReference Include="AWSSDK.S3" Version="3.1.7.2" />
    <PackageReference Include="ConfigInjector" Version="2.2.1175" />
    <PackageReference Include="Linq2DynamoDb.DataContext" Version="2.0.0" />
    <PackageReference Include="Linq2DynamoDb.DataContext.Caching.Redis" Version="2.0.0" />
    <PackageReference Include="MassTransit" Version="3.5.7" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Core" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNet.SignalR.Redis" Version="2.2.2" />
    <PackageReference Include="Microsoft.Owin" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Owin" Version="1.0.0" />
    <PackageReference Include="Serilog" Version="2.5.0" />
    <PackageReference Include="ThirdDrawer" Version="1.1.9" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  
  <Target Name="ChangeAliasesOfStrongNameAssemblies" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'StackExchange.Redis.StrongName'">
        <Aliases>signed</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
  
</Project>
```

**Comment by emgarten** [comment]
This workaround should be added to the official docs.

@nkolev92 @anangaur

**Comment by brianpos** [comment]
I've tried this out with the Fhir assembly @ewoutkramer, works a treat.
Agree this should be in official docs

**Comment by jez9999** [comment]
@gertjvr Sorry, I'm really confused by your workaround.  You say you have "both references of StackExchange.Redis and StackExchange.Redis.StrongName nuget dependencies" but then in your example `csproj` file, there is no `PackageReference` to either of these nuget packages.  So..... where are the dependencies?  And what does `StackExchange.Redis.StrongName` refer to?  A namespace?  The name of the DLL file that you will be using with `extern alias` or something?  It's all very unclear.

**Comment by andymac4182** [comment]
@jez9999 One of the packages referenced by that csproj references the non strong named version and one references the strong named version. You can't see that reference since `PackageReference` only shows the first level reference. 

MSBuild enumerates all the direct and otherwise references and adds them. 

`StackExchange.Redis.StrongName` refers to the file name of the DLL that needs to have the aliases property updated. 

I hope that helps.

**Comment by jcoutch** [comment]
Thank you @gertjvr for the workaround!!!  I've been going nuts for the past couple hours trying to figure out how to work around the `StackExchange.Redis.StrongName` dependency in the `Microsoft.AspNetCore.All` metapackage...when my code and all the third party packages I use reference the non-strong-named version.  Your workaround at least lets me side-step the issue for now.

**Comment by StefDotmailer** [comment]
I'm getting the same issue with `FSharpx.Extras` and `FSharp.Control.AsyncSeq` both declaring `FSharp.Control.AsyncSeq`. Unfortunately in F# there is no such thing as `extern alias`. Would it be possible to implement an alias for NuGet packages directly referencing the package without the need of `extern alias`? An alias to redirect to types into a specific package, making them available only thorough that alias.

**Comment by UnoSD** [comment]
I'm getting the same issue with `FSharpx.Extras` and `FSharp.Control.AsyncSeq` both declaring `FSharp.Control.AsyncSeq`. Unfortunately in F# there is no such thing as `extern alias`. Would it be possible to implement an alias for NuGet packages directly referencing the package without the need of `extern alias`? An alias to redirect to types into a specific package, making them available only thorough that alias.

**Comment by davethieben** [comment]
I took @gertjvr 's solution and made it a bit more generic. you can drop this snippet into `Directory.Build.targets`:

```
    <Target Name="AddPackageAliases" BeforeTargets="ResolveReferences" Outputs="%(PackageReference.Identity)">
        <PropertyGroup>
            <AliasPackageReference>@(PackageReference->'%(Identity)')</AliasPackageReference>
            <AliasName>@(PackageReference->'%(Alias)')</AliasName>
        </PropertyGroup>

        <ItemGroup>
            <ReferencePath Condition="'%(FileName)'=='$(AliasPackageReference)'">
                <Aliases>$(AliasName)</Aliases>
            </ReferencePath>
        </ItemGroup>
    </Target>
```
and then use it in your csproj like this:

```
    <ItemGroup>
        <PackageReference Include="StackExchange.Redis.StrongName" Version="1.2.6" Alias="signed" />
    </ItemGroup>
```

**Comment by roybrew** [comment]
Does anyone know when this will actually be fixed?  Seems like you can have aliases on ProjectReferences but not PackageReferences.

**Comment by commonsensesoftware** [comment]
Adding to the mix... I just ran into this problem between `Microsoft.Extensions.Primitives` and the NuGet libraries themselves because the NuGet libraries are linking the source files via a submodule rather than referencing the package. I'm not sure what the rationale behind that is, but it led to me needing an alias.

To expand upon @davethieben solution, if you need an alias for a **transitive** dependency, then this will do the trick:

```xml
<Target Name="AddTransitivePackageAliases"
        AfterTargets="AddPackageAliases"
        Outputs="%(TransitivePackageReference.Identity)">

 <PropertyGroup>
  <AliasPackageReference>@(TransitivePackageReference->'%(Identity)')</AliasPackageReference>
  <AliasName>@(TransitivePackageReference->'%(Alias)')</AliasName>
 </PropertyGroup>

 <ItemGroup>
  <ReferencePath Condition="'%(FileName)'=='$(AliasPackageReference)'" Aliases="$(AliasName)" />
 </ItemGroup>

</Target>
```

Then you can just add an entry in your source project as:

```xml
<ItemGroup>
 <TransitivePackageReference Include="Microsoft.Extensions.Primitives" Alias="primitives" />
</ItemGroup>
```

**TransitivePackageReference** is a made up item name and can technically be anything, but I thought that was appropriately named enough. Being able to use something like:

```xml
<ItemGroup>
 <PackageReference Update="Microsoft.Extensions.Primitives" Alias="primitives" />
</ItemGroup>
```

**would** be better, but I couldn't make it work. I presume that's because the items aren't directly resolved in the current project (since they're transitive). If this ever gets fixed, this is how we'd want aliases for transitive dependencies to be defined IMO.

**Comment by nkolev92** [comment]
It's common for packages to carry more than one assembly. 
What do you think the behavior is in that case?

Because of the flexibility it allows (specifically only alias one of many assemblies), I'd be more in favor of having a separate item/target than putting this on a PackageReference. 

Note that a more complete solution is ensuring that the assembly is coming from the right package, like the following [example](https://github.com/NuGet/Samples/blob/f10ee44dbe94568f1a1ac14fde579ba0f4b326d6/ExternPackageReference.Example/ConsoleApp/ConsoleApp.csproj#L17).

```xml
  <Target Name="AddCustomAliases" BeforeTargets="FindReferenceAssembliesForReferences;ResolveReferences">
    <ItemGroup>
      <ReferencePath Condition="'%(FileName)' == 'ClassLib2' AND '%(ReferencePath.NuGetPackageId)' == 'ClassLib2'">
        <Aliases>ClassLib2</Aliases>
      </ReferencePath>
    </ItemGroup>
  </Target>
```

**Comment by commonsensesoftware** [comment]
@nkolev92 fair, though I'd submit that need tends to be quite rare. It's reasonable to consider to make the feature _complete_. In that case, I would suggest something like:

```xml
<ItemGroup>

 <ReferenceAlias Include="Companion"
                 PackageReference="Microsoft.Extensions.Primitives"
                 Assembly="CompanionLibrary" />

 <ReferenceAlias Include="Sys" Reference="System" />

</ItemGroup>
```

This would provide a new type of metadata that could be applied to any reference, including transitive dependencies. In this example, **PackageReference** and **Reference** are mutually exclusive and indicate the source of the alias (unambiguously). If **Assembly** is specified, then the alias only applies to that assembly; for example, in a NuGet package. If **Assembly** is not specified, then the alias applies to all assemblies in the referenced source (which could be one or many).

I'm pretty sure that item metadata cannot subsequently have its own attributes. I believe you can use nested XML as the body of metadata, but it will be treated as literal text. This would probably require a custom build task to match things up prior to compile, but it _should_ be pretty straight forward.

Defining aliases inline is best IMO, but making that work within the conventions of MSBuild might work the way we'd like.

Just a suggestion...

**Comment by nkolev92** [comment]
@commonsensesoftware 

That's similar to the thought process I had. :) I just wanted to validate it by the MSBuild/SDK/Build targets folks. 
 
Why the need for a `Reference` though? 
If you have a reference, you can already use the Aliases metadata.

**Comment by commonsensesoftware** [comment]
Ah - yes. You're correct. I guess that wouldn't be needed then. To make things completely specific to NuGet only, then something like this would make more sense:

```xml
<ItemGroup>

 <PackageReferenceMetadata Include="Microsoft.Extensions.Primitive" Alias="primitives" />

 <PackageReferenceMetadata Include="Microsoft.Extensions.Primitive"
                           Alias="companion"
                           Assembly="CompanionLibrary" />

</PackageReferenceAlias>
```

The first form provides an alias for all libraries in the package, while the second only provides an alias for a single package.

Using the more generic name **PackageReferenceMetadata** (or something like that) could open the door to solve other, existing issues such specifying **NoWarn** on transitive dependencies. Effectively, there needs to be a way to _bolt on_ certain types of settings and configuration that are currently not supported or cannot be provided by the intrinsic item capabilities of **Include** or **Update**.

**Comment by nkolev92** [comment]
I'm not sure how NoWarn will be affected by this, but I think that's a fair proposal. 

I'll write up some things and start a discussion across the different products. 

In the meantime, I'll document the example in samples repo.

**Comment by commonsensesoftware** [comment]
What I'm saying is that there is no way to specify **NoWarn** for a transitive dependency. This _could_ be potentially achieved with:

### Option 1
Use the **Update** directive for an existing `<PackageReference />` that sets **NoWarn**

```xml
<ItemGroup>
  <PackageReference Update="Microsoft.Extensions.Primitives" NoWarn="NU###" />
</ItemGroup>
```

### Option 2
Use `<PackageReferenceMetadata />` to set **NoWarn** and other metadata such as **Alias**

```xml
<ItemGroup>
  <PackageReferenceMetadata Include="Microsoft.Extensions.Primitives" Alias="primitives" NoWarn="NU###" />
</ItemGroup>
```

I don't want to go completely off-topic here. I merely wanted to illustrate that there are other pieces of metadata that currently suffer from the same problem and should be _considered_ in a complete solution.

**Comment by bording** [comment]
> What I'm saying is that there is no way to specify NoWarn for a transitive dependency.

Yep: https://github.com/NuGet/Home/issues/5740

**Comment by nkolev92** [comment]
Hey all, 

You can take a look at our design for this here: 
[Design document](https://github.com/NuGet/Home/blob/dev/designs/PackageReference-Extern-Alias.md).

**Comment by dhinesh-v** [comment]
Hi @nkolev92 , 

Is there a way to alias three packages which have the same namespace. I have tried the design document mentioned solution, but I can't able to achieve that. 

I have tried below solution, 

``` xml 
<Target Name="AddPackageAliases" BeforeTargets="ResolveReferences" Outputs="%(PackageReference.Identity)">
    <PropertyGroup>
        <AliasPackageReference>@(PackageReference->'%(Identity)')</AliasPackageReference>
        <AliasName>@(PackageReference->'%(Alias)')</AliasName>
    </PropertyGroup>

    <ItemGroup>
        <ReferencePath Condition="'%(FileName)'=='$(AliasPackageReference)'">
            <Aliases>$(AliasName)</Aliases>
        </ReferencePath>
    </ItemGroup>
</Target>

<ItemGroup>
	 <PackageReference Include="KeyGen_Old.Core" Version="1.0.0" Alias="OldCore" />
	 <PackageReference Include="KeyGen.Core" Version="2.0.0" Alias="Core" />
	 <PackageReference Include="KeyGen_Latest.Core" Version="3.0.0" Alias="LatestCore" />
</ItemGroup>
```

But only one alias is working, Other aliases are not working and showing below error, 
`
The extern alias 'LatestCore' was not specified in a /reference option
`

**Comment by nkolev92** [comment]
@dhinesh-v That workaround is not handling the cases where the assembly name is not equal to the package name. 

Specifically:

```xml
        <ReferencePath Condition="'%(FileName)'=='$(AliasPackageReference)'">
```

**Comment by dhinesh-v** [comment]
@nkolev92  Thanks for mentioning this case. But all the packages that i'm using has single assembly in it and named same as the package. So the mentioned case didn't  cause any problem in my project. 

Using this workaround, I can able to alias **three assemblies which has different namespaces.** 

But I'm unable to alias **three assemblies which has same namespaces.**

Can you please let me know that aliasing three assemblies which has same namespaces is possible or not.

**Comment by nkolev92** [comment]
@dhinesh-v 
Adding aliases to multiple assemblies are independent actions. 
So both scenarios you mentioned are possible.

**Comment by nkolev92** [comment]
Hey all, 
the NuGet.Client side change has been merged.
However, this is a multi product feature. So I'm working on making sure the experience works end to end before I close this issue. 

You can track the effort in the following issues:

https://github.com/dotnet/sdk/issues/10947 The build tasks on (.NET Core SDK side) (https://github.com/dotnet/sdk/pull/11451)
https://github.com/dotnet/NuGet.BuildTasks/issues/70 The build tasks for the non-SDK based PackageReference
https://github.com/dotnet/project-system/issues/6011 Nomination updates on project-system side.

**Comment by nkolev92** [comment]
With https://github.com/dotnet/sdk/issues/11612 and https://github.com/dotnet/sdk/pull/11954, finally all the legs of this feature are completed. 

The feature will be available in 16.7 and all the matching tooling versions (3.1.400 of the SDK, 5.0 of the SDK) & 5.7 of NuGet.exe. 

If you are using NuGet.exe, keep in mind that you need VIsual Studio/ MSBuild to be 16.7

**Comment by anangaur** [comment]
Awesome!! Thanks @nkolev92 for consistently following up on this one 👏

**Comment by TFTomSun** [comment]
@nkolev92  can you please provide a link to the documentation / sample?

**Comment by nkolev92** [comment]
@TFTomSun Design at https://github.com/NuGet/Home/blob/dev/designs/PackageReference-Extern-Alias.md. 

I'll update the docs by the time this ships in a GA release.

**Comment by TFTomSun** [comment]
@nkolev92 are the aliases transistive? I mean, are they applied to indirect, transistive dependencies, too?

**Comment by nkolev92** [comment]
They only apply to the package reference they are specified on. 

The challenge with applying to transitive dependencies is the `diamond dependency` scenario where: Project -> A -> C and Project -> B -> C. 

For the time being the answer to how do I apply metadata to a transitive package still remains `elevate it to top level`.

**Comment by TFTomSun** [comment]
@nkolev92  Is there a possibility to somehow iterate over transistive dependencies using MSBuild script? Or is there an existing task that can be reused to do that? That would help those who would like to push through the aliases for a specific package and it's dependencies.

**Comment by YanerTavuz** [comment]
Hi! 
We're waiting for Visual Studio 16.7 to use this feature, do you know if it's available yet in any of the VS16.7 previews? Saw that Preview 3 was just released.

**Comment by nkolev92** [comment]
@YanerTavuz Preview 3 should have it

**Comment by YanerTavuz** [comment]
Got it to work with VS16.7 Preview 3.1 and .NET 5 Preview 6 with a .NET project SDK style.

Trying to get it to work with .NET Framework 4.8 with old csproj style,, any tips on how to get it working there? @nkolev92 
It works when the csproj is SDK-style, but our solution projects uses the old style.


Edit: After some investigating, it seems that the dll for Microsoft.NuGet.Build.Tasks that is shipped with Visual Studio 16.7 Preview 3.1 does not contain your changes from https://github.com/dotnet/NuGet.BuildTasks/issues/70 so I guess that's the issue.

**Comment by YanerTavuz** [comment]
@nkolev92 Using it now in VS16.7.2, seems to work. 
Only issue I've encountered is with XAML files where a xmlns with schema from the nuget package is used. 
E.g xmlns:wizard="http://schemas.actiprosoftware.com/winfx/xaml/wizard"
Probably normal dll aliasing is affected by this. 
"Type or namespace name xxx could not be found".
Any ideas what to do?

**Comment by brian-pickens** [comment]
Will this work to alias different versions of the same package?

**Comment by fubar-coder** [comment]
> 
> 
> Will this work to alias different versions of the same package?

Yes

**Comment by davkean** [comment]
No, this cannot be used to alias different versions of the same package that has the same identifier. This is entirely used to alias assemblies within a package.

**Comment by tdhatcher** [comment]
@davkean Is there any plan to enable this in the case of "different version of same nuget package"? 

This would be very handy for versioning classes and allowing a single service to interop with both (or many versions) concurrently using aliases.

**Comment by davkean** [comment]
@tdhatcher I'm aware of no plans to allow the ability to reference multiple versions of the same NuGet packages, but one of the NuGet folks would need to chime in, @nkolev92 .

**Comment by nkolev92** [comment]
> @davkean Is there any plan to enable this in the case of "different version of same nuget package"?

There are no active plans to enable multiple versions of the same package in a project at this point.

**Comment by tdhatcher** [comment]
@nkolev92 my feedback is as someone who is not familar with inner workings of nuget package resolution. I'm curious if this doesn't exist because it's more of a technical hurdle to accomplish or more of a logical decision?

It seems if two or more distinctly named packages can resolve namespace collision with aliases then two or more of the same named packages should be able to resolve namespace collision.

I haven't really come across a solid prescribed strategy as for how to actually implement your API versions especially when breaking changes are present (and without separately hosting older version of the API). Just that there is flexibility in ASP.NET Core to support mapping multiple API versions to different controllers to handle the request/response (concurrently in the same running instance of an API).

Consider a common scenario when you publish a nuget package that serves as a convenient SDK for your API. That SDK contains all the classes that act as the contracts and client for consumers to interact with the API. The version of the SDK's nuget package is kept in-sync with the version of the API (eg. you'd use version 5 of the SDK you are communicating with v5 of the API). 

By allowing aliases on same Nuget package with different versions, the API implementation would be able to reference the proper version of the SDK nuget package to obtain the proper contracts for the specific version of API controllers.

![Nuget Multiple Version Support](https://user-images.githubusercontent.com/360359/215829013-29da780f-84c7-4e69-ad1e-68bb9755c79f.svg)

This approach would be in contrast to an approach of maintaining a versioned yet disjointed SDK library separately while in the API it is cloning/maintaining multiple versions of the contracts globbed together in a single project to support backwards compatibility. Seems like a clean option like this is missing.

Allowing aliases for the same package but different versions would be a very complementary feature to ASP.NET Core API versioning. https://github.com/dotnet/aspnet-api-versioning/wiki/Existing-Services-Quick-Start

**Comment by nkolev92** [comment]
@tdhatcher Having multiple versions of the same assembly (by extension of package) is a pretty involved feature. 

I won't be able to address all your concerns, but one difficult challenge is what happens transitively. Sure if you reference a package directly, you can choose to alias it's assemblies, but what happens for the transitive dependencies that might have some incompatibilities? 

You're likely to need some sort of assembly rewriting to make this work, which would have it's own set of problems.

If you'd like you can file a different issue with that ask. 

The first thing that would need to happen to make progress on your idea is for the tooling overall to support `multiple versions of the same package within 1 project`.

**Comment by commonsensesoftware** [comment]
@tdhatcher I appreciate the callout 😉 , but an API version is not like a _Semantic Version_ or assembly version; this is a false equivalency. Backward compatibility should in no way be implied or inferred from any API version. This is a common misconception. The rules for versioning binaries are quite different and are well-known across many languages and tools. These rules do not generically apply to an API. Even if the changes to the message body of an API is additive, a server cannot guarantee that the client implements a [tolerant reader](https://www.martinfowler.com/bliki/TolerantReader.html) and will not break. There's nothing about `1.1` that says it's backward compatible with `1.0`. I could have just as easily removed a data attribute and that would be considered a _minor_ change. The conflation with numbers for API versions and binary versions are one reason why dates are often a better choice for an API version. Nothing about `2023-01-01` implies that it is compatible with `2019-07-01`. 😸 

API authors that vend a client that they want to have affinity to the API version usually take one of the following approaches:

1. Include all supported API versions in a single package, separated by namespace
2. Include a single package that maps to the most recent supported API versions
3. Include a _meta_ package that maps to individual packages corresponding to independently versions clients

While it is possible, it's usual and uncommon to need multiple versions of the same API simultaneously. Azure SDKs are backed by versioned Azure APIs. When you use a particular version of the client SDK, you typically don't think about the backing API version and certainly not multiple API versions at the same time. As @nkolev92 mentioned, the complexity of SxS assemblies is involved and goes beyond just aliasing. Even if you got it to work, it's pretty painful for package consumers. I doubt many would actually _want_ that.

There are like other ways to achieve your goals, including, but not limited to having a clearly defined API versioning policy such as `N-2`.
