### ISSUE TITLE
When create Web API, VS crashed.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#499]
Repro steps:
1.File -> New project -> Visual C# -> Web -> ASP.NET Web Application->Web API.
2.Check the box for "Application Insights"
3.Make sure to check the "Web API" +"MVC" box below for "Add folders and core references for , and click "Authentication" to "Windows"
4.Click OK.
5.Wait for a few minutes, VS crash.
Repro in: Main build "22827.01",Main 22828.01 nuget.org, WPT 22828.00  VS+SDK+NuGet VSIX(\\\nuget\NuGet\Share\Drops\CI\dev\268)

![crash](https://cloud.githubusercontent.com/assets/12129698/7383337/0d860d76-ee50-11e4-85fa-0264a5ab423e.png)

Call Stack +Dump file link: \\\vwdbuild01\temp\V-lawu\dumpfile\499

**Comment by deepakaravindr** [comment]
This is a tracking bug for an external issue

**Comment by deepakaravindr** [comment]
Assigning to Dan for verification

**Comment by deepakaravindr** [comment]
@danliu

**Comment by v-lawu** [comment]
Call Stack +Dump file link: \\\vwdbuild01\temp\V-lawu\dumpfile\499

**Comment by danliu** [comment]
this bug is external to NuGet
