### ISSUE TITLE
Nuget - Pack command failed

### ISSUE THREAD

**Issue by Moodys-SCMTeam** [NuGet/Home#4990]
Hi,

We are getting the following exception while trying to run the pack command

[INFO] Your package was pushed.
[INFO] Package was deployed successfully.
[INFO] MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
[INFO] Attempting to build package from 'Moodys.Epi2.Publish.csproj'.
[ERROR] The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  E:\JWS\epi2\w_epi2-Dissemination_156\Projects\Moodys.Epi2.Publish\Moodys.Epi2.Publish.csproj
[ERROR] Pack command failed.
[ERROR] Package deploy failed.

In the initial logs, we have noticed that msbuild version is taken automatically.

E:\JWS\epi2\w_epi2-Dissemination_156>E:\mdp\app\bin\nuget-runner.cmd restore Solutions/Dissemination/Moodys.Epi2.Dissemination.Setup.sln -NoCache 
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.

[JenkinsBuildLog.txt](https://github.com/NuGet/Home/files/902459/JenkinsBuildLog.txt)

**Comment by rohit21agrawal** [comment]
@Moodys-SCMTeam would really appreciate if you could share more information such as:
1) Version of NuGet being used for packing
2) Any details of the project you could share publicly. (The best bug reports often have an attached sample project which help us repro the bug to diagnose the underlying issue)

Thanks,
Rohit

**Comment by Moodys-SCMTeam** [comment]
Hi Rohit,

          Please find attached a sample C# web app. It’s a very basic app nothing much.
          While doing a “Nuget Pack” I am getting the same exception which I was getting with our original app. I have attached the log as well.

          NuGet Version: 3.3.0.212


Regards,
Gaurav Kushwaha
Software Configuration Management (SCM)
Architecture & Engineering
Mobile +91 9763907559
Direct  +91 2066348000 ext 336715

**Comment by Moodys-SCMTeam** [comment]
Hi Rohit,

          Do you have any update for us?



Regards,
Gaurav Kushwaha
Software Configuration Management (SCM)
Architecture & Engineering
Mobile +91 9763907559
Direct  +91 2066348000 ext 336715

From: Kushwaha, Gaurav (non-empl)
Sent: Thursday, April 13, 2017 7:11 AM
To: 'NuGet/Home' <reply@reply.github.com>; NuGet/Home <Home@noreply.github.com>
Cc: Moody's - SCM Team <Moodys-SCMTeam@moodys.com>; Mention <mention@noreply.github.com>
Subject: RE: [NuGet/Home] Nuget - Pack command failed (#4990)

Hi Rohit,

          Please find attached a sample C# web app. It’s a very basic app nothing much.
          While doing a “Nuget Pack” I am getting the same exception which I was getting with our original app. I have attached the log as well.

          NuGet Version: 3.3.0.212


Regards,
Gaurav Kushwaha
Software Configuration Management (SCM)
Architecture & Engineering
Mobile +91 9763907559
Direct  +91 2066348000 ext 336715

**Comment by rohit21agrawal** [comment]
i will get back to you by the end of day regarding this. in the meanwhile, could you try using later versions of NuGet.exe (3.5.0, 4.0.0, 4.1.0) from https://dist.nuget.org/index.html .

**Comment by rohit21agrawal** [comment]
@Moodys-SCMTeam i don't see the attachment in your comment. perhaps you could upload it to OneDrive and share a link with us?

**Comment by vphad** [comment]
[ErrorLogNugetPack.txt](https://github.com/NuGet/Home/files/977171/ErrorLogNugetPack.txt)
[WebApplication1.zip](https://github.com/NuGet/Home/files/977172/WebApplication1.zip)


Hi Rohit, 
PFA the required files.

**Comment by vphad** [comment]
Hi Team, 
Were you able to look into this ?

**Comment by emgarten** [comment]
Based on the msbuild error shown the SDK is missing, this does not look related to nuget or pack. Please update your project or specify the version of msbuild to use by adding it to your `PATH`.
