### ISSUE TITLE
Local Packages folder missing with packagereferences

### ISSUE THREAD

**Issue by igloo15** [NuGet/Home#4991]
Basically there is no local packages folder everything is getting installed to the global cache and referenced from there not sure if this is an issue with packagereference or not. Need to have a local packages folder. Also related is that it ignores the repositoryPath configuration option in NuGet.Config if it exists. On top of that it sometimes is unable to uninstall packages as well claiming they don't exist. 

## Details about Problem

NuGet product used : VS UI

NuGet version : 4.1.0

VS version (if appropriate): 15.1

OS version : Windows 10 Pro 1607

## Detailed repro steps so we can see the same problem

1. Start a Net Core Library Project

2. Install any package (Newtonsoft.Json)

3. No $(SolutionDir)/packages folder

**Comment by igloo15** [comment]
I see now that packagereferences only looks at globalPackagesFolder. Changing that got packages to install in a new location. While this works there are still some issues. One is that all the runtime and netstandard packages also get installed to this location. 

It would be nice if there was a way to separate the packages installed by the user Newtonsoft.Json, etc. and those installed automatically by dotnet cli in order to target a framework. Obviously since everything is now nuget packages they could all be manually installed by the user via VS UI but in the situations where the User doesn't manually install via ui or command line nuget they should go to a different location.

**Comment by emgarten** [comment]
See https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file for additional help on setting the folder location.
