### ISSUE TITLE
NuGet failing to restore packages for projects containing ProjectReferences

### ISSUE THREAD

**Issue by tyohekim** [NuGet/Home#4993]
## Details about Problem

I'm running a ASP.NET Core app on the .NET 4.6.1 framework. I have 1 solution with multiple projects in it.  All of the projects are class libraries that reference each other via PackageReferences (this way we can build, package and version them independently).  In order to test integration in real-time without needing to push up NuGet packages, there is one runnable sandbox project that references all of the other projects by ProjectReferences in the .csproj.  Restoring and building this sandbox project results in errors, though it was working a few days ago.

I can build and restore packages on each of the class library project's just fine.

Consider the following .csproj for the sandbox project:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyName>TestProject</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>TestProject</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyProject1\MyProject1.csproj" />
    <ProjectReference Include="..\MyProject2\MyProject2.csproj" />
    <ProjectReference Include="..\MyProject3\MyProject3.csproj" />
    <ProjectReference Include="..\MyProject4\MyProject4.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle" Version="6.0.0-beta902" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.5" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

Here's an example of one of the referenced project's:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.3.0</VersionPrefix>
    <TargetFramework>net461</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>MyProject1</AssemblyName>
    <PackageId>MyProject1</PackageId>
    <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MyProject2" Version="1.0.0-*" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
```

Since TestProject references both MyProject1 and MyProject2 as ProjectReferences, and MyProject1 pulls in MyProject2 as a NuGet reference, there are a ton of errors - I'm guessing because NuGet or .NET doesn't know which to use (they both have the same project GUID after all).

Here's an example of the errors - the first looks like an infinite loop:
`C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Unable to satisfy conflicting requests for 'System.Runtime.CompilerServices.Unsafe': System.Runtime.CompilerServices.Unsafe (>= 4.3.0) (via package/Microsoft.Extensions.Primitives 1.1.0), System.Runtime.CompilerServices.Unsafe (>= 4.3.0) (via package/Microsoft.Extensions.Primitives 1.1.0),[...]`

This error appears for every ProjectReference:
`C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : An item with the same key has already been added. Key: (MyProject2 1.0.0) [C:\Program Files\CustomProject\src\TestProject\TestProject.csproj]`

I can see how this set-up could cause problems, but is there any work around to this?

NuGet product used: VS UI and dotnet.exe

NuGet version: VS (from package manager console): 4.0.0.2323, cmd line: 3.4.3.855

dotnet.exe --version: 1.0.1

VS version: 2017 v4.6.01055

OS version: win7 Pro 6.1.7601

Worked before? Not sure, broke without any noticeable updates within the last week.

## Detailed repro steps so we can see the same problem

1. Have one project in a solution reference the other projects by ProjectReference in the .csproj
2. Have one of the referenced projects pull in another project in the solution via PackageReference (from NuGet)

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
