### ISSUE TITLE
%temp%\NuGetScratch Excessively Large

### ISSUE THREAD

**Issue by dtbiedrzycki** [NuGet/Home#4994]
## The Problem
The NuGetSratch folder grows to be incredibly large. In my case, after about a month after clearing, I'm up to 80GB (again).

This issues is directly related to a closed issue (#802) that is still a problem.

## Details about Problem
NuGet product used:
* NuGet.exe
* NuGet Package Manager for VS 2015
* VS UI
* Package Manager Console

NuGet version: 3.4.4.1321

dotnet version: 4.6.01586

VS version: 2015

OS version: win10 v1607, build 14393.693

Worked before? Not that I am aware of.

## Detailed repro steps

1. 3-4 instances of VS opened and closed regularly
2. some VS instances will stay open for days to weeks at a time
3. Over a month, my machine has a NuGetSratch folder with 80GB

**Comment by emgarten** [comment]
@dtbiedrzycki what files do you see in NuGetScratch?

You may also want to update to NuGet 3.5.0 from http://dist.nuget.org/  it has some changes around how extracted packages are cached.

**Comment by dtbiedrzycki** [comment]
I've just cleared mine, so I'll have to check back in when it starts to fill. In the meantime, I'll see if I can update to the latest and if I still get the issue.

**Comment by ogrim** [comment]
Just deleted around 40 GB yesterday. Will update nuget at work tomorrow and see how it evolves

**Comment by dtbiedrzycki** [comment]
@emgarten, do you happen to know why the latest packages don't show up in the Visual Studio Extension and Updates? According that tool, the latest version is the 3.4.4.1321.

**Comment by emgarten** [comment]
> happen to know why the latest packages don't show up in the Visual Studio Extension and Updates?

3.5.0 hasn't been published to the extension gallery yet. Currently the only way to get it is through dist.

**Comment by dtbiedrzycki** [comment]
After updating, it seems to be a bit better, but still needs improvement. My NuGetScratch in the Temp directory is currently 25GB since updating shortly after my comment in April.

**Comment by emgarten** [comment]
@dtbiedrzycki what files do you see in the scratch folder?

**Comment by dtbiedrzycki** [comment]
A number of directories with guids for names and in them are what I believe to be downloaded NuGet packages (i.e. Newtonsoft.Json.9.0.1).

**Comment by emgarten** [comment]
That sounds like the older NuGet behavior where it cached packages in scratch. This no longer exists in 3.5.0 for Visual Studio but other tools such as ReSharper that use NuGet.Core.dll may still end up writing here and may not be cleaning it up.
