### ISSUE TITLE
Restoring only accounts for depnedency project's nuget dependencies

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#4995]
_From @am11 on April 6, 2017 6:25_

Consider `A.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>

</Project>
```

is referenced by `B.csproj`:

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="System.Spatial" Version="5.8.2" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include=".\A.csproj" />
  </ItemGroup>

</Project>
```

▶️  Both csprojs are in same directory
*(in my real scenario, they are in same folder and by the virtue of glob pattern, compiling different code files)*

Running `dotnet restore --packages packages B.csproj` results in *only* restoring `newtonsoft.json` in `./packages` directory.

If I remove this part:

```csproj
  <ItemGroup>
      <ProjectReference Include=".\A.csproj" />
  </ItemGroup>
```

then it successfully restores `system.spatial` package from `B.csproj` (but naturally not newtonsoft.json).

> What happens in VS2017

It shows the good old yellow exclamation sign for System.Spatial packages under B.csproj's Dependencies > NuGet node. In old csproj format, it used to mean that "check if the assembly exists at HintPath", but what does that mean in new csproj format where there is no HintPath? Hovering over yellow triangle with exclamation does not yield any information. It took some time to figure out the self-contained steps to repro.

_Copied from original issue: dotnet/sdk#1085_

**Comment by am11** [comment]
After updating to dontet 1.0.3, VS2017 [Update / v15.1](https://blogs.msdn.microsoft.com/visualstudio/2017/04/05/visual-studio-2017-update/), while many of the issues I had with large solutions have been resolved, this one is still reproducible.

Re-emphasizing on note: this happens only when same directory has multiple csproj files referencing each other.

**Comment by emgarten** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
