### ISSUE TITLE
Nuget takes highest prelease

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#4999]
@v703612 commented on [Fri Apr 07 2017](https://github.com/NuGet/NuGetGallery/issues/3760)

Hello,

We are currently doing some testing of nuget to use nuget command line in our deploy system. We would like to use the latest version of nuget but there we encountered that when you are having prereleases that it is always taking the lowest(first) prerelease and we would need the latest prerelease. Is this possible?

kr,

**Comment by emgarten** [comment]
@v703162 please see https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior for help configuring resolution behavior.
