### ISSUE TITLE
NuGet.PackageManagement: Use DownloadResource.Progress event

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#50]
NuGet.PackageManagement: Use DownloadResource.Progress event

Repro steps
1. Create a console application
2.  From the powershell console, install a fairly large package, say, EntityFramework

Expected:
1. There is a progress bar at the bottom-right of powershell console

Actual:
1. There is no progress bar at the bottom-right of powershell console. When downloading a large package, there is no visual feedback to the user

**Comment by jainaashish** [comment]
We aren't going to do it for packages.config and for PackageReference, it's not individual install.
