### ISSUE TITLE
DotNetCliToolReference fails to restore

### ISSUE THREAD

**Issue by sbomer** [NuGet/Home#5000]
## Details about Problem

Restore fails on a DotNetCliToolReference, where both the cli tool and the consumer target netcoreapp2.0. It complains that the cli tool is not compatible with netcoreapp1.0, even though I'm not using netcoreapp1.0 anywhere.

```
/home/sven/bin/sdk/2.0.0-preview1-005414/NuGet.targets(97,5): error : Package cliTool 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package cliTool 1.0.0 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [/home/sven/tmp/repro/app/app.csproj]
/home/sven/bin/sdk/2.0.0-preview1-005414/NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [/home/sven/tmp/repro/app/app.csproj]
```

NuGet product used: dotnet.exe

```
sven@sven-ubuntu:~/tmp$ dotnet --info
.NET Command Line Tools (2.0.0-preview1-005414)

Product Information:
 Version:            2.0.0-preview1-005414
 Commit SHA-1 hash:  01e7bfde74

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/sven/bin/sdk/2.0.0-preview1-005414/
```

Worked before? If so, with which NuGet version: Not to my knowledge.

## Repro steps

[repro.tar.gz](https://github.com/NuGet/Home/files/907051/repro.tar.gz)
./repro.sh

Detailed steps:

1. Create, restore, and package a new console app (this is the cli tool app).
2. Create a new console app to consume the cli tool.
3. Add the path to the package from step 1. to the NuGet.Config
4. Add a DotNetCliToolReference to the cli tool.
5. dotnet restore

**Comment by CoskunSunali** [comment]
Copied from https://github.com/aspnet/DotNetTools/issues/297#issuecomment-309010069

> Sorry to hijack the thread. Seems it might be relevant to the issue I am having.
> 
> I see that the latest version of the watch tool is `2.0.0-preview1-final` on nuget.org, thus updating the tool reference as below:
> 
> ```
> <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0-preview1-final" />
> ```
> 
> My app is already configured to use `netcoreapp2.0` as the target framework and everything works fine.
> 
> The output I am getting as soon as I build the project with the above configuration, I get the following two errors.
> 
> ```
> Package Microsoft.DotNet.Watcher.Tools 2.0.0-preview1-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.DotNet.Watcher.Tools 2.0.0-preview1-final supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)				
> ```
> 
> and
> 
> ```
> One or more packages are incompatible with .NETCoreApp,Version=v1.0.				
> ```
> 
> The problem with the first error is that, none of the projects in my application are using `netcoreapp1.0` as its target.
> 
> The problem with the second error is that, I actually don't expect any of my packages to be compatible with `netcoreapp1.0` but eventually something does.
> 
> If I revert back the watch tool's version to `1.0.1`, everything seems to work.
> 
> I have two question in this case;
> 
> 1. May I stay on 1.0.1 and keep running my projects targeting `netcoreapp2.0`?
> 2. Are the errors I am getting above expected?

**Comment by natemcmaster** [comment]
@rrelyea @mlorbetske this appears to be the same problem we were talking about yesterday. We've received multiple reports of this happening with dotnet-watch (https://github.com/aspnet/DotNetTools/issues/297). 

Essentially, the problem is that NuGet takes in an MSBuild property named [DotnetCliToolTargetFramework](https://github.com/NuGet/NuGet.Client/blob/release-4.3.0-preview2/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L309) to determine how to restore CLI tools. This defaults to `netcoreapp1.0`. What is supposed to happen is that Microsoft.NET.Sdk is [supposed to lift](https://github.com/dotnet/sdk/blob/release/2.0.0-preview2/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.Common.targets#L41-L44) this to `netcoreapp2.0` when newer versions of the SDK are installed...but this doesn't appear to be happening. cc @dsplaisted

**Comment by rrelyea** [comment]
This second issue is a dupe to: https://github.com/NuGet/Home/issues/5397
The first issue is already fixed from the command line.
