### ISSUE TITLE
Package Manager Console failed to initialize

### ISSUE THREAD

**Issue by andrew-vdb** [NuGet/Home#5001]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (4.0):

VS version : 15.1 (26403.0)

OS version : Win7 x64

Worked before? If so, with which NuGet version: 4.0

View->Other Windows->Package Manager Console

![image](https://cloud.githubusercontent.com/assets/12871379/24864865/cb3c4754-1e05-11e7-8247-eed0c8de4123.png)

![image](https://cloud.githubusercontent.com/assets/12871379/24864679/4f867986-1e05-11e7-9b6e-de89aa46276e.png)

Most of the fix of this problem by re-installing nuget package manager, now its included in vs2017, its not extension anymore and i got this errors on my vs2017

**Comment by andrew-vdb** [comment]
It works if I open visual studio 2017 that has no project

![image](https://cloud.githubusercontent.com/assets/12871379/24866206/c4e1d578-1e09-11e7-9d88-acad75ac026e.png)

**Comment by andrew-vdb** [comment]
Installing this and still have the error
https://www.microsoft.com/en-us/download/details.aspx?id=50395

**Comment by rohit21agrawal** [comment]
@andrew-vandenbrink it's not immediately clear how you got into this state. Did you try to install a nuget vsix on top of what was already installed? where did you get the vsix from? In VS2017, we do not support the scenario of installing a vsix separately as NuGet is a system component within Visual Studio.

**Comment by andrew-vdb** [comment]
Its also not clear for me too how do I get into this state.
I found a workaround anyway,

Assuming, Package Manager Console working fine when you open visual studio 2017
Open the solution/projects from that visual studio

(Don't double click solution directly from explorer as the package manager console will failed to initialize)
