### ISSUE TITLE
Failed to update binding redirects for (<>). Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by dbreshears** [NuGet/Home#5002]
From https://github.com/Azure/service-fabric-issues/issues/184

Repro steps:
Service fabric SDK  2.5.216 

create new service fabric project in VS2015, adding a stateless web api service
update nuget packages for solution
select all update options (at the moment mainly Owin, Owin.Hosting, Owin.HttpListener & Newtonsoft.Json)
apply the update
Notice package manager output - "Failed to update binding redirects for (<>). Object reference not set to an instance of an object"
...

**First question** : Can this be safely ignored?  

**Second question** : This doesn't repro in VS 2017.    Is there any way to provide an updated version of Nuget Package Manager on the VS Marketplace for 2015 that fixes this issue?

**Comment by mishra14** [comment]
Hi, thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
