### ISSUE TITLE
Wrong version constraint when building dependant libraries using ProjectReference and GitVersion

### ISSUE THREAD

**Issue by thoemmi** [NuGet/Home#5003]
I have a solution with two library projects, using VS2017. Project B has a ProjectReference to A. The version are determined at compile time by GitVersion (4.0.0-beta0011). The current version of my libraries is 0.1.0.

I create the NuGet packages using msbuild:
```
msbuild /t:restore;build;pack
```
While both packages have the version **0.1.0**, the nuspec of B says it depends on A, version **1.0**! However, v1.0 doesn't exist, so you cannot add package B to any project.

You can reproduce the issue with my repository [StickyWindows](https://github.com/thoemmi/StickyWindows): **StickyWindows.WPF** depends on **StickyWindows**, **version >= 1.0** (see [NuGet gallery](https://www.nuget.org/packages/StickyWindows.WPF/)), though both packages are **0.1.0**, created with the same build.

**Comment by thoemmi** [comment]
I also tried `msbuild /t:restore;build /p:GeneratePackageOnBuild=true`, but the result is the same.

**Comment by rohit21agrawal** [comment]
@thoemmi restore and build should not be done in one msbuild session. Could you try executing them separately to see if the problem still persists?

@emgarten will be better able to explain why restore and build should not be run in one msbuild session.

**Comment by thoemmi** [comment]
The result is the same if I call MSBuild for each target separately.

**Comment by rohit21agrawal** [comment]
@thoemmi i think this is a dupe of : https://github.com/NuGet/Home/issues/4790 . There is a [workaround](https://github.com/NuGet/Home/issues/4790#issuecomment-288098255) listed there too . If you think that's the issue, can you please close this out and subscribe to that issue for updates?

**Comment by thoemmi** [comment]
@rohit21agrawal I can confirm that the referenced [workaround](https://github.com/AArnott/Nerdbank.GitVersioning/issues/113#issuecomment-285903085) does work. I've created following file and imported it in my `.csproj`'s:
```xml
<Project>
  <!-- GitVersion version -->
  <PropertyGroup>
    <GitVersionTaskVersion>4.0.0-beta0011</GitVersionTaskVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- reference GitVersionTask package -->
    <PackageReference Include="GitVersionTask" Version="$(GitVersionTaskVersion)" PrivateAssets="All" />
  </ItemGroup>

  <!--
    Import GitVersionTask target
    This ugly workaround is necessary because of this NuGet issue: https://github.com/NuGet/Home/issues/4790
  -->
  <ImportGroup Condition="'$(ExcludeRestorePackageImports)' == 'true'">
    <Import
      Project="$(UserProfile)\.nuget\packages\gitversiontask\$(GitVersionTaskVersion)\buildMultiTargeting\GitVersionTask.targets"
      Condition="Exists('$(UserProfile)\.nuget\packages\gitversiontask\$(GitVersionTaskVersion)\buildMultiTargeting\GitVersionTask.targets')" />
  </ImportGroup>
  <Target
    Name="FixUpVersion"
    BeforeTargets="_GenerateRestoreProjectSpec"
    DependsOnTargets="GetVersion"
    Condition="'$(GitVersion_Task_targets_Imported)' == 'True'" />
</Project>
```
I'll close this issue and subscribe to #4790 as requested.
