### ISSUE TITLE
msbuild /t:pack fails to pack an sdk project with a reference to a framework project which contains a PackageReference

### ISSUE THREAD

**Issue by gulbanana** [NuGet/Home#5008]
This is kind of the opposite of https://github.com/NuGet/Home/issues/4532, but still occurs now that #4532 is fixed. Perhaps it's really a build issue, but it manifests as a failure to pack, because the build is done in Visual Studio using the full-framework version of msbuild.

## Details about Problem
NuGet product used: dotnet.exe and msbuild (the only ways to pack sdk projects)
NuGet version: 4.0.1
dotnet.exe --version: 1.0.2
msbuild -version: 15.1.1012.6693
OS version: Windows 10

## Detailed repro steps so we can see the same problem
1. Clone https://github.com/gulbanana/repro-packagereference-transitive
2. `cd SdkProject`
3. Either run `dotnet msbuild SdkProject.csproj /t:pack`, or just `dotnet pack`.

### Verbose Logs
Here is the output:  https://pastebin.com/vgCyU7p5 

### Sample Project
https://github.com/gulbanana/repro-packagereference-transitive

**Comment by rohit21agrawal** [comment]
can you try restoring and building the project first and then doing ``` dotnet pack --no-build ``` ?

**Comment by gulbanana** [comment]
OK, I ran a build in Visual Studio and then dotnet pack --no-build. This created a package.
So the only problem with pack in this scenario is that it tries to perform a build (which can't succeed, since it is using core msbuild).

**Comment by mishra14** [comment]
@gulbanana you should be able to do the following - 

```
msbuild /t:restore .\SdkProject\SdkProject.csproj
msbuild /t:build .\SdkProject\SdkProject.csproj
msbuild /t:pack .\SdkProject\SdkProject.csproj
```
