### ISSUE TITLE
After create Console/Azure Cloud Service project, click "Add Connected Service" and add "Azure Storage", meet error.

### ISSUE THREAD

**Issue by v-lawu** [NuGet/Home#501]
Repro steps:
1.File -> New project -> Visual C# -> Console Application
2.Right-click on the References node and select "Add Connected Service" 
3.Choose "Azure Storage" and click configure.
4.Choose "Azure Storage" and click Configure
5.Select a storage account, and click Add
6.Wait for NuGet packages to be installed, the error dialog pop up.
Also repro in  Azure Cloud Service with ASP.NET application do same steps.

Repro build: Main 22827.01,Main 22828.01,WPT 22828.00 VS + SDK + NuGet VSIX

![storage](https://cloud.githubusercontent.com/assets/12129698/7383446/03c8ddc0-ee52-11e4-8fd4-03b306b47455.png)

**Comment by deepakaravindr** [comment]
@yishaigalatzer, We don't think this is related to NuGet and may be related to connected services

**Comment by deepakaravindr** [comment]
This is a tracking bug

**Comment by deepakaravindr** [comment]
Assigning to @danliu for verification

**Comment by danliu** [comment]
assign to Deepak as he already has a fix for this issue.

**Comment by deepakaravindr** [comment]
This turned out to be a hang after the VS threading changes. It has been fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/a4637d1f4811dfcee66f0bdcc0a3f894de33a5ae
