### ISSUE TITLE
For UWP projects, NuGet exposes an API that keeps the project file and project.json in sync

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#5010]
Work related to -  For UWP projects, keep TPMinV and project.json in sync #4932

**Comment by shishirx34** [comment]
Issue Repro steps

```
If you use 15.1 and create a UWP project, then use notepad to edit the TPMV to use RS2 10.0.14393 (i think).
Reload the project.
The nuget package node in the solution explorer disappears, breaking intellisense.
Do a restore, and it fixes.
 
In project.json scenario, this same issue doesn't occur, even if you edit project.json and the tpmv in the csproj.
```

With my change to fix #4932 this should repro in project.json scenario too now.

**Comment by shishirx34** [comment]
I verified and this issue repros with project.json as well with my changes for #4932

**Comment by shishirx34** [comment]
Partly Fixed with https://github.com/NuGet/NuGet.Client/pull/1395 

TODO: Add sync support in MSBuild Restore task for TFM and TPMinV

**Comment by emgarten** [comment]
@shishirx34 is there any work needed for this?

**Comment by shishirx34** [comment]
@emgarten - I believe the only related work remaining is to add the sync support in MSBuild Restore task for TFM and TPMinV, with regards to your comment on https://github.com/NuGet/NuGet.Client/pull/1395 PR. Not sure if it was done after my handoff, @rrelyea might have more information on it.

**Comment by emgarten** [comment]
I don't see any changes to the restore target around this. This would mean that UWP projects would work in Visual Studio but would fail from command line builds and from nuget.exe on the CI machines.

Potentially this could be fixed only for nuget.exe after 15.3 and before 4.3.0 nuget.exe is shipped. `MSBuild /t:restore` would not work for UWP, but that would be less common than using nuget.exe for UWP in my opinion.

**Comment by emgarten** [comment]
Moving to 4.4 since this scenario is limited to CI + UWP. Newer projects using PackageReference will not hit this issue.

**Comment by mishra14** [comment]
closing as "Wont Fix", based on an offline chat with @emgarten.
