### ISSUE TITLE
Pack and Restore targets don't import props/targets from PackageReferences

### ISSUE THREAD

**Issue by m0sa** [NuGet/Home#5013]
I've been trying to pack up a workaround for #4853 as a nuget package (the WIP project [is here](https://github.com/m0sa/NuGet.FrameworkAssemblyPacker)), but it turns out that the `build/*` files from the `<PackageReference>` are only included in the Build target, but skipped in the Pack and Restore targets.

I was trying that on
```
dotnet --version
1.0.3
```

**Comment by emgarten** [comment]
@rohit21agrawal is pack excluding package content?

@m0sa As a workaround you could inject props/targets for these scenarios by writing out a props or targets file to: ``$(BaseIntermediatePath)\$(MSBuildProjectFile).<toolname>.g.props``

In the props file reference your package, or include the needed targets there.

Restore needs to exclude all package content to avoid restore outputs changing the inputs for the next restore, which would lead to the need for endless restores.

**Comment by rohit21agrawal** [comment]
Pack runs in the outer build, so you need to put your target in buildCrossTargeting.

**Comment by m0sa** [comment]
TIL, didn't know that's a thing till now, thanks!
