### ISSUE TITLE
nuget does not filter netstandard projects

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5015]
_From @jmarolf on April 11, 2017 15:52_

1. Create new netstandard1.4 class library
2. Use nuget to install `Microsoft.Diagnostics.Tracing.TraceEvent` version 1.0.41

**Expected:** 
either nuget tells me that this package is incompatible or it install and works without error

**Actual:**
nuget package successfully installs, but none of the types it contains can be referenced

_Copied from original issue: dotnet/project-system#1967_

**Comment by emgarten** [comment]
@jmarolf the targets file in the root of ``build/`` allows the package to be compatible with **all** target frameworks.

When using a targets file in the root it is expected that the targets file will handle all scenarios, including erroring when the package is not compatible.

A better structure for this would be to add the same tfm folders under the build folder as the lib folder instead of putting the targets file in the root.

**Comment by jmarolf** [comment]
@emgarten so [Microsoft.Diagnostics.Tracing.TraceEvent](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.TraceEvent) has authored their package wrong and declared that they support all platforms when they do not?  @davkean can the project system warn when we add a reference to a dll that is incompatible with out TFM?

**Comment by emgarten** [comment]
>  Microsoft.Diagnostics.Tracing.TraceEvent has authored their package wrong and declared that they support all platforms when they do not?

Yes, but putting things in the root of build is a common approach, and it usually works the majority of users. However the result is that on the nuget side there is no way to check compatibility.

**Comment by davkean** [comment]
@jmarolf Not sure what you are suggesting the project should check? You mean if you manually reference a binary?

The project system is getting out of the business of validating references - instead, we now rely on MSBuild . This allows a consistent experience regardless of how you add the reference (ie via editing project file, or in VS Code, etc). 

If there's an invalid reference that you want MSBuild to check then we should make changes to consume the data from RAR in the sdk.

**Comment by jmarolf** [comment]
@davkean  I would prefer that nuget simply rejected this case but I understand that this is an escape hatch for package authors.  In lieu of that, I would like us to issue at least a warning indicating that the reference is incompatible with our TFM.  I assume the only sane way to do this is through MSBuild?
