### ISSUE TITLE
Inconsistency in the casing of the "ID" abbreviation

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#5018]
This error message is used in NuGetGallery (www.nuget.org) when rejecting invalid version ranged:
https://github.com/NuGet/NuGet.Client/blob/dcd728cf9ff33223cead100938a75d35773cd9c3/src/NuGet.Core/NuGet.Packaging/Strings.resx#L133

It has the abbreviation "ID" displayed as "id". This is inconsistent with the rest of the gallery.

I did a search for the possible different casings of "ID" in our NuGet.Client RESX files:

Variant | Count
-------- | ------
ID         | 49
Id          | 31
id          | 26
iD         | 0 (thankfully)

It looks like there is a lot of inconsistency. I am not talking about the casing of "ID" in code. I am just talking about messages displayed to the user. [According to the English Stack Exchange](http://english.stackexchange.com/a/101251):

> In English, both letters should be capitalized ("ID"). The lower case word "id" has a specific meaning that does not invoke the meaning "identifier," or "identification." In documentation it should be spelled out (ID abbreviates two different words, after all), or be in all caps.

This is low priority.

**Comment by mishra14** [comment]
@joelverhagen feel free to create a PR to fix this.
