### ISSUE TITLE
Included DLLs inside lib/ folder throw warnings

### ISSUE THREAD

**Issue by ek68794998** [NuGet/Home#5019]
## Details about Problem
NuGet product used:
MSBuild v15.1.1012.6693 with `Pack` target.

NuGet version:
Whatever version is included in VS2017 with the MSBuild version designated above. If this is important, let me know how I can get this version number.

`dotnet.exe --version`:
N/A

VS version:
15.1 (26403.3)

OS version (i.e. win10 v1607 (14393.321)):
win10 v1703 15165.1002

Worked before? If so, with which NuGet version:
Yes, 4.0.0.2283, when using `nuget pack` on a `nuspec` file with the same inclusions (`<file src="bin\$configuration$\**\*" target="lib" />`).

## Detailed repro steps so we can see the same problem
1. In Visual Studio 2017, create a `csproj` which produces an executable.
1. Include a NuGet package and reference it in some way in the code.
1. Ensure that `<TargetFrameworks>net452</TargetFrameworks>` is set in the `csproj`.
1. Since library references (DLLs from NuGets) required for the project are not included, add:
	```
	<ItemGroup>
		<None Include="bin\$(Configuration)\**\*.dll">
			<PackagePath>lib/net452/</PackagePath>
			<Pack>true</Pack>
		</None>
	</ItemGroup>
	```
1. Run from VS2017 Developer Command Prompt: `msbuild /t:Pack MyProject.csproj`

The console will output a bunch of warnings such as:
```
warning : Description: The assembly 'lib/net452/Newtonsoft.Json.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
warning : Description: The assembly 'lib/net452/MyProject.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
```

Clearly the error message is wrong as the DLL *is* inside the `lib` folder. (If I put it in `lib/` instead of `lib/net452/`, I get "no framework specified" warnings.) There should be no warnings thrown here.

### Verbose Logs
https://pastebin.com/QF8BMMrT

### Sample Project
https://drive.google.com/open?id=0B8JHaidj6UhEc2hMQUp1YThDbkE

**Comment by rohit21agrawal** [comment]
this has been fixed as part of : https://github.com/NuGet/NuGet.Client/pull/1609
