### ISSUE TITLE
Define nuspec Metadata in project files

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#5027]
I have a question about this (which is briefly explained on your blog [here](http://blog.nuget.org/)).

Are there any plans to make this feature available for Class Library projects that target .Net Framework?

The blog post doesn't seem to clearly state what project types do support this feature and which don't.

I'd dearly like to be able to specify the nuget properties and auto generate the package on build for other project types.

Thanks

**Comment by rohit21agrawal** [comment]
@Korporal this feature is only supported .NET Core project types. However, you can still build for the full framework by setting TargetFramework = net46 or whatever you want to target. Let me know if you have any more questions I can answer.

**Comment by The-Futurist** [comment]
@rohit21agrawal 

Hi, basically I do not understand what you say. First the features seems to be present for .Net Core projects **and** .Net Standard (not just .Net Core).

Do you mean I can create a new .Net Core/Standard class library project and then manually edit the project to target some other framework like .Net 4.5?

Thanks !

**Comment by rohit21agrawal** [comment]
> Do you mean I can create a new .Net Core/Standard class library project and then manually edit the project to target some other framework like .Net 4.5?

Exactly. Just set ```<TargetFramework>net45</TargetFramework>``` in the csproj and you will have built a .net 4.5 library!

when i said .net core, i mean the project type is .net core and not the target framework or platform. .net core project types are the ones which have ```<Project Sdk="Microsoft.NET.Sdk">``` at the top of the project file.
