### ISSUE TITLE
First restore after installing latest .NET Core SDK takes a very long time

### ISSUE THREAD

**Issue by danroth27** [NuGet/Home#5030]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

dotnet.exe --version (if appropriate): .NET Core SDK 2.0.0-preview1-005791

OS version (i.e. win10 v1607 (14393.321)): win10 v1607 14393.1066

## Detailed repro steps so we can see the same problem

1. Install latest .NET Core SDK
2. dotnet new mvc -au Individual

After the local package cache is created and the project is created the CLI does a restore. This first restore takes a long time (~1min).

**Comment by mishra14** [comment]
```
C:\Users\anmishr\Desktop\temp\test> Measure-Command{ dotnetlocal new mvc -au Individual --force}

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 433
Ticks             : 44332604
TotalDays         : 5.13108842592593E-05
TotalHours        : 0.00123146122222222
TotalMinutes      : 0.0738876733333333
TotalSeconds      : 4.4332604
TotalMilliseconds : 4433.2604
```
