### ISSUE TITLE
Floating versions with prereleases

### ISSUE THREAD

**Issue by matkoch** [NuGet/Home#5031]
With the new csproj format I can write:

`<PackageReference Include ="ExamplePackage" version="1.4.*"/>`

But how can I define that prereleases should be included?

**Comment by bbowman** [comment]
@emgarten seems like another *-* request. Can you comment on if this is in plan anytime soon?

**Comment by danielgreen** [comment]
+1 for this.

Also seems to relate to #4099

**Comment by emgarten** [comment]
Dupe of https://github.com/NuGet/Home/issues/912
