### ISSUE TITLE
[Authentication] In multi-feed scenario, NuGet install does not honor the feed selected as package source in PM-UI

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5034]
Repro steps:
1. Have multiple feeds setup with atleast one authenticated feed and one local feed
2. Open PMUI, select the authenticated feed as your source.
3. Search for a package that is present in both local and authenticated feed.
4. Install the package

Expected: It should install the package from the authenticated feed that is selected in the PM-UI as package source.

**Actual**: It may install from local feed. May be authentication takes time while the other feed returns with the package to install. Ideally NuGet should not look for other feeds to install the package when a particular feed is selected as package source.

Note: You need to clear cache for subsequent repro.

**Comment by nkolev92** [comment]
The behavior is different for PC and PackRef scenarios. 
See related https://github.com/NuGet/Home/issues/5848

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6373.
