### ISSUE TITLE
Extra props file being added to lock file in NuGet 4.0

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#5036]
Presently moving the [dotnet/roslyn](https://github.com/dotnet/roslyn) repo to the new SDK on our [features/sdk branch](https://github.com/dotnet/roslyn/tree/features/sdk).  

This also involves us upgrading from NuGet 3.6 to 4.X.  Sorry to be unspecific about the NuGet version but now that restore is driven by MSBuild I'm not sure what version to report.  MSBuild though is 15.1.1012.6693 (Int Preview channel build).  

In doing this move I noticed an expected lock file change to many of our test projects ([example CodeAnalysisTest](https://github.com/dotnet/roslyn/blob/features/sdk/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj)).  There is a new entry in our xunit.runner.visual studio section:

Before

``` json
"xunit.runner.visualstudio/2.2.0-beta4-build1194": {
  "type": "package"
},
```

After

``` json
"xunit.runner.visualstudio/2.2.0-beta4-build1194": {
  "type": "package",
  "build": {
    "build/net20/xunit.runner.visualstudio.props": {}
  }
},
```

The inclusion of this props file occurs everywhere we use xunit.runner.visualstudio.  Nothing of significance in the containing projects appears to have changed.  Before and after the changes they are Desktop 4.6 projects.  

This is causing us problems because the props file itself unconditionally copies files to the output directory.  One of these, xunit.abstractions.dll, is already copied via a different NuGet package.  This results in a double write to the output directory which in turn fails our build.  

Is there a reason for this change?  Hoping yes so I can go back to the old way and avoid including the props file.

**Comment by emgarten** [comment]
@jaredpar was *xunit.runner.visualstudio.props* being referenced in *projectName.nuget.props* when using project.json?

The build entry in 4.x is there for completeness, it should not be read by the SDK during the build. NuGet handles these imports by writing them out to the project's generated props file. All of this *should* be the same between 3.x and 4.x.

The project here looks like it is net46 and the package contains build\net20 which is being selected. So it looks correct that this would be referenced.

To exclude the props file use *ExcludeAssets*

```xml
 <PackageReference Include="xunit.runner.visualstudio">
      <Version>$(xunitrunnervisualstudioVersion)</Version>
      <ExcludeAssets>build</ExcludeAssets>
</PackageReference>
```

**Comment by jaredpar** [comment]
> was xunit.runner.visualstudio.props being referenced in projectName.nuget.props when using project.json?

Yes.  The entry exists there as a conditional import on the file existing. 

> The build entry in 4.x is there for completeness, i

Sounds like in 3.X it was used, hence put in the projectName.nuget.props, but excluded from the lock file.  It was added in 4.X to the lock file for completness but didn't otherwise change behavior.  Is that the right of it?

**Comment by emgarten** [comment]
> but didn't otherwise change behavior. Is that the right of it?

That's correct, it would all be the same.

> Yes. The entry exists there as a conditional import on the file existing.

Is the missing condition causing your issue? Previously this was added because restore would be unable to load the project if packages were not yet restored, the current behavior is that the imported props/targets files are excluded during restore. Outside of restore these files should exist unless you are doing something to change that.

**Comment by jaredpar** [comment]
> Is the missing condition causing your issue? 

No.  I added that comment for completeness just in case it was unexpected.  

Thanks for the answers here!
