### ISSUE TITLE
When restoring DotNetCliToolReferences, generate .targets and .props files for imports from NuGet packages

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#5037]
For DotNetCliToolReferences, each reference is restored separately and a project.assets.json is written out to the `.nuget\.tools\<ToolPackageId>\<ToolVersion>\<TargetFramework>` folder.  For .NET Core 2.0, the Microsoft.NETCore.App package has a .props file in it that is used to set some MSBuild properties and items used for conflict resolution.

In order for these to be picked up, it would be helpful if the DotNetCliToolReferences restore process could generate .props and .targets files next to the project.assets.json that it creates for the tool with imports for .props and .targets files from NuGet packages in the tool restore graph, similar to the `<projectname>.nuget.g.targets` files it generates for a normal restore.

Related comment: https://github.com/dotnet/cli/issues/6087#issuecomment-294184765

cc @emgarten @rrelyea @livarcocc

**Comment by rrelyea** [comment]
can consider post 4.3

**Comment by nkolev92** [comment]
At this point `DotNetCliToolReferences` are not the recommended approach. 

Closing as no longer relevant.
