### ISSUE TITLE
Area:NuGetizer - NuGetizer installed ... and nothing happens

### ISSUE THREAD

**Issue by rpokrovskij** [NuGet/Home#5038]
VS version: 2017

Installed to .NET Classic Library project but absolutely unclear what to do after it. Huge and verbose documentation is misleading:  "Elize adds New Project..."  I do not see any new projects available. This is only in your fantazies or what? 

What I see after nugetizer installed:
new folder  `...packages\NuGet.Build.Packaging.0.1.243`

and those entries in the csproj:

```
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.props'))" />
    <Error Condition="!Exists('..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.targets'))" />
  </Target> 
<Import Project="..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.targets" Condition="Exists('..\packages\NuGet.Build.Packaging.0.1.243\build\NuGet.Build.Packaging.targets')" /> 

```
It is absolutely not obvious what all this things do.

Expected: step by step documentation how to compile a) .NET Classic. b) .NET Core/Standard  projects and build nuget package together.

**Comment by emgarten** [comment]
@kzu

**Comment by kzu** [comment]
Here's a concise readme: https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/README.md

Being in its early stages, user-focused documentation (as opposed to developer-focused spec we have now) is still missing, yes.

**Comment by kzu** [comment]
Also, for the most part, what you're asking is basically documented at https://docs.microsoft.com/en-us/nuget/guides/create-net-standard-packages-vs2017

Nugetizer supports basically the same metadata, but in any project type. Plus, the (not documented yet) IDE project and templates mentioned in the readme above.

**Comment by ghost** [comment]
@kzu Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
