### ISSUE TITLE
Inconsistent package location between CI server and local

### ISSUE THREAD

**Issue by jochenvanwylick** [NuGet/Home#504]
Here's the StackOverflow question I've got going for this problem: http://stackoverflow.com/questions/29939947/could-not-resolve-this-reference-nuget-on-ci-server 

I'm using a NuGet package: `Fluent.Validations` ( `<package id="FluentValidation" version="5.5.0" targetFramework="net45" userInstalled="true" />` ).

`.csproj` file looks like: 

    <Reference Include="FluentValidation, Version=5.5.0.0, Culture=neutral, processorArchitecture=MSIL">     
      <HintPath>$(SolutionDir)\packages\FluentValidation.5.5.0\lib\Net40\FluentValidation.dll</HintPath>
      <SpecificVersion>False</SpecificVersion>
      <Private>True</Private>
    </Reference>

Locally - package is downloaded to  `/packages/FluentValidation.5.4.0` - on the server it's downloaded to `FluentValidation.5.4.0.0`.

Local system: running win10 + VS2015CTP6
CI server: Win2012R2 + VS2013 + VS2015CTP6

I updated the NuGet VS plugin on the CI server and I placed the latest NuGet.exe in the .nuget folder in source control - which is called for auto-restore.

![local vs ci](https://cloud.githubusercontent.com/assets/3002474/7391459/a513e34e-ee81-11e4-9eff-aac035143954.png)

**Comment by deepakaravindr** [comment]
This is fixed in VS 2015 RC. Please try the latest builds

**Comment by jochenvanwylick** [comment]
@deepakaravindr Thanks! I'm using NuGet auto-restore with a bundled NuGet.exe in the .nuget folder in the solution. Should I update that nuget.exe file then? And if so, update it to 2.8.5 or the v3 beta?

**Comment by deepakaravindr** [comment]
@jochenvanwylick, Migrating to automatic package restore is better. Thanks!
