### ISSUE TITLE
Nugetizer Floating Version Ranges should be resolved when creating package

### ISSUE THREAD

**Issue by bbowman** [NuGet/Home#5040]
@kzu 

Including a PackageReference with a floating version range yields .nuspec that can't be uploaded to nuget.org

The PackageReference is [here](https://github.com/Microsoft/WinObjC/blob/72583443d48460645b042289b8008314c874beac/msvc/sdk-build.props#L47)

and the resulting nuspec looks like

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>WinObjC.Frameworks</id>
    <version>0.2.170408-dev-20170415100906</version>
    <title>WinObjC.Frameworks</title>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <iconUrl>https://avatars2.githubusercontent.com/u/6154722?v=3&amp;s=200</iconUrl>
    <description>WinObjC.Frameworks</description>
    <summary>WinObjC.Frameworks</summary>
    <releaseNotes></releaseNotes>
    <copyright>Copyright © Microsoft</copyright>
    <language></language>
    <tags>WinObjC.Frameworks</tags>
    <dependencies>
      <dependency id="NuGet.Build.Packaging" version="0.1.186" />
      <dependency id="WinObjC.Language" version="0.2.170408-dev-20170415100153" />
      <dependency id="cppwinrt" />
      <dependency id="ANGLE.WindowsStore" version="2.1.13" />
      <dependency id="WinObjC.Frameworks.UWP" version="0.2.170408-dev-20170415100906" />
    </dependencies>
  </metadata>
</package>
```

Uploading to nuget.org complained with:

2017-04-15T15:53:34.8780823Z System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: **400 (Invalid package version for a dependency with id 'cppwinrt' in package** '********.Frameworks.0.2.170408-dev-20170415100906': '').
2017-04-15T15:53:34.8780823Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()

I think it would make sense to resolve floating versions when nugetizing / to actually forward on the floaitng version (not positive how transitive floating versions are)

**Comment by kzu** [comment]
Yep, at a minimum, it should have preserved the `*` as the version.

**Comment by emgarten** [comment]
@rohit21agrawal how is pack handling this currently?

**Comment by rohit21agrawal** [comment]
It looks at the assets file for the resolved version

**Comment by emgarten** [comment]
> I think it would make sense to resolve floating versions when nugetizing / to actually forward on the floaitng version (not positive how transitive floating versions are)

Packages cannot float the version of other packages. Only projects may opt into this behavior.

> It looks at the assets file for the resolved version

From the example @bbowman gave it looks like there may be an issue with pack finding the version then, it is dropping the version attribute completely.

**Comment by rohit21agrawal** [comment]
@emgarten this project is being packed via nugetizer, and not dotnet pack.

**Comment by emgarten** [comment]
@rohit21agrawal didn't catch that at first, thanks :smile:

> Yep, at a minimum, it should have preserved the * as the version.

@kzu stars are not allowed in nuspecs, it will need to find the actual version.

**Comment by bbowman** [comment]
@emgarten @kzu I've seen Nugetizer produce "--" before in a nuspec. Is that valid?

To solve the issue, it seems like there should be something in the nuget object model to inspect what was restored. Does that exist? I know the generated targets has some extra metadata but does it include the restored version? Would be handy to have it add an item group like RestoredPackages that looks like PackageReferences but includes the restored version instead of the requested version. Failing that i guess @kzu needs to look at project.lock.json / project.assets.json in the various places it could wind up?

**Comment by TheXenocide** [comment]
I also have an issue with this; it looks like MSBuild /t:Pack resolves version numbers when generating the nuspec, but NuProj seems to be confused by the *. I was really hoping it would set version to the locally resolved version and then set the range to allow any higher version than the locally resolved, up to the maximum of the floating positions (i.e. `PackageReference Version="1.1.1.*"` would become `dependency version="1.1.1.5" allowedVersions="[1.1.1.5,1.1.2)"`)

**Comment by kzu** [comment]
Would you mind contributing a PR to https://github.com/NuGet/NuGet.Build.Packaging/  to fix this? Thanks!

**Comment by TheXenocide** [comment]
I saw this in my notifications and just wanted to drop by and note that it would be really nice if packages were allowed to use `.*` versions in their dependencies.
