### ISSUE TITLE
IntelliSense fails on newly installed packages with ContentFiles

### ISSUE THREAD

**Issue by davidmatson** [NuGet/Home#5047]
On VS 2017 (15.1, 23403.0).

1. Create a CPS-style csproj with a target framework of full .NET framework (for example, net462).
2. Install a NuGet package that has contentFiles with C# code in it.
3. Reference this package from other source code.
4. Build. Watch the build succeed.
5. Try to Go to Definition or otherwise use IntelliSense on the new package.

Expected:
IntelliSense works

Actual:
IntelliSense cannot resolve the identifiers. If the solution is closed and re-opened, it succeeds.

**Comment by davidmatson** [comment]
The attachment on #5048 should also provide a repro for this issue.

**Comment by davidmatson** [comment]
It appears that the linked items are only being evaluated if the solution is re-loaded, and not at package install time.

**Comment by emgarten** [comment]
This issue was moved to dotnet/project-system#2022
