### ISSUE TITLE
Cross-Plat Compatibility

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#505]
Currently GetEnvironmentVariable is called in a few places with EnvironmentVariables specific to Windows, e.g. "ProgramData" and "APPDATA", we should figure out what the *nix path equivalents are and add checks for those.

Second, we need to be careful with case-sensitivity for the paths. I know in v2 we used some lower-case paths that wouldn't work cross-plat, but a quick glance at v3 I didn't find any problems.

**Comment by yishaigalatzer** [comment]
@BrennanConroy please try to be specific when issues like this are filed (point to code samples), specify what this is blocking and when you need a fix. etc.

**Comment by deepakaravindr** [comment]
This is a duplicate of #472
