### ISSUE TITLE
Lightweight Solution Load: Common Core for PM UI, PMC, and IVs*

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#5057]
1. Create a shared interface (IVsProjectAdapter) for all DteProject API and LSL API, remove all DteProject dependency and make all nuget logical depends on IVsProjectAdapter. [Done]
2. Add all DTE API and LSL API service to IVsProjectAdapdter.
4. VsSolutionManager works with LSL mode.

**Comment by rrelyea** [comment]
This ended up not shipping in 4.3, switching milestone to 4.4 (where we think it will ship)
