### ISSUE TITLE
Support dependency groups for native packages

### ISSUE THREAD

**Issue by pepone** [NuGet/Home#5065]
Native packages currently don't support dependency groups, for projects that need to build with different Platform Toolset will be nice to have per toolset dependencies

	<dependencies>
	    <group platformToolset="v120">
	        <dependency id="expat.v120" />
	    </group>

	    <group platformToolset="v140">
	        <dependency id="expat.v140" />
	    </group>
	</dependencies>

So we can have native packages that is platform independent and NuGet will install the dependencies for the platform being use in the project.

**Comment by mishra14** [comment]
This should be solved with PackageReference style projects that allow conditional package references. Closing after an offline discussion with @emgarten.
