### ISSUE TITLE
Allow for custom conditions in package imports

### ISSUE THREAD

**Issue by pepone** [NuGet/Home#5066]
I want to disable package imports selectively, to be able to build the same project with or without a NuGet package.

In this circumstance I found myself having to hack the generated Imports and Errors to add custom Conditions

It will be nice if the Package Manager allows for custom conditions , so an import can be conditioned by custom MSBuild properties.

**Comment by emgarten** [comment]
@pepone you could do this by conditionally setting the ExcludeAssets property on the package reference. 

```xml
<PackageReference Include="NuGet.CatalogReader" Version="1.2.0">
   <ExcludeAssets Condition=" '$(CustomCondition)' == 'true' ">build</ExcludeAssets>
</PackageReference>
```

For this to take effect you will need to run a restore and pass /p:CustomCondition=true

**Comment by pepone** [comment]
Will this work for native packages where you have .props/.target files imported as part of the package? In my case using NuGet native packages with .props/.targets files I end-up having to add this Conditions in multiple places manually/

        <Project DefaultTargets="Build" 
             ToolsVersion="14.0" 
             xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
        <Import Project="packages\zeroc.ice.v141.3.7.0-beta0\build\native\zeroc.ice.v141.props"
                Condition="Exists('packages\zeroc.ice.v141.3.7.0-beta0\build\native\zeroc.ice.v141.props') 
                           and '$(ICE_BIN_DIST)' == 'all'" />
        ...
        <ImportGroup Label="ExtensionSettings">
            <Import Project="packages\zeroc.ice.v140.3.7.0-beta0\build\native\zeroc.ice.v140.targets" 
                    Condition="Exists('packages\zeroc.ice.v140.3.7.0-beta0\build\native\zeroc.ice.v140.targets')
                              and '$(ICE_BIN_DIST)' == 'all'" />

        <Target Name="EnsureNuGetPackageBuildImports" 
                BeforeTargets="PrepareForBuild" 
                Condition="'$(ICE_BIN_DIST)' == 'all'">
        ...

**Comment by emgarten** [comment]
It looks like you are using a packages.config project. Adding custom conditions on the nuget added conditions is currently the only way to do this for those projects.

**Comment by mishra14** [comment]
This should be solved with `PackageReference` style projects that allow conditional package references. Closing after an offline discussion with @emgarten.

**Comment by pepone** [comment]
@mishra14 how this work for C++ native projects?
