### ISSUE TITLE
Expose OriginalVersion property on NuGetVersion

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#5068]
There's no reliable way to get a hold of the _original, unmodified version string_ used to construct a `NuGetVersion` instance.

[`NuGetVersion.ToString()`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs#L154) returns normalized version string for SemVer2 versions, and original version string for non-SemVer2 versions.

[`NuGetVersion.ToFullString()`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/SemanticVersionBase.cs#L27) returns normalized version string + metadata (e.g. when original version was `"01.0.42.0"`, this will return `"1.0.42"`, which is not the original version string).

Simply exposing the `_originalString` field through a readonly public property would allow the caller to get a hold of the original version string.

**Comment by emgarten** [comment]
Is there a reason to allow non-normalized SemVer2 versions?

If it were not for legacy reasons ToString() would also return the normalized version. The design here was that going forward everything would be normalized, since SemVer2 is new, all of those should be normalized.

**Comment by xavierdecoster** [comment]
The issue here is that V2 endpoints (OData) currently have the behavior of always returning the original version string as-is in the Version property. For SemVer2 packages, that would be a call to `.ToFullString` (to include the metadata). However, that very call would return a normalized version string instead of the original version string for non-SemVer2 packages.

To not break that behavior, an easy-to-access OriginalVersion property would come in really useful.

**Comment by xavierdecoster** [comment]
Just discovered another inconsistency: I noticed that e.g. `new NuGetVersion("1.0.0+metadata")` returns `"1.0.0"` as the original version, which is incorrect. This never surfaced, as the `Metadata` property is correctly set, and the `.ToString` method never had to return SemVer2 original version strings so far :)
