### ISSUE TITLE
Add compat package for netstandard 2.0 during pack

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5070]
Pack on a csproj should auto add the compat shim to a net461 dependency group. net471 should clear this out.

We should also warn during package analysis if this is missing. Potentially during custom nuspec scenarios we should just warn instead of adding it.

**Comment by anangaur** [comment]
I am assuming this covers VS pack option in the project context menu as it would call msbuild /t:pack?
![image](https://cloud.githubusercontent.com/assets/14800916/25208001/b9eb865e-2526-11e7-967b-819cf689e5a3.png)

**Comment by rrelyea** [comment]
This was our original plan. no longer needed though.
Now, targets in VS2017/CLI and in an installable VS2015 based MSI will handle.
