### ISSUE TITLE
Unable to Build a NuGetizer .nuproj in TFS with the Hosted VS2017 agent

### ISSUE THREAD

**Issue by sashkode** [NuGet/Home#5071]
Hi,

I just installed the NuGetizer Visual Studio Extension for VS2017 and created a NuGet Package Project using the template. However, doing so broke our TFS build for the solution in which we added this project. Our build uses the default Hosted VS2017 agent.

Here's the error:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2630,7): Error MSB4057: The target "CreateManifestResourceNames" does not exist in the project.`

The NuGet Package Project builds fine within Visual Studio, it is able to package up the code in a .nupkg.

Let me know if there are some additional steps that I need to perform to have the build run on the TFS agent or if this is a known limitation of the current release.

Thanks,

Alex

**Comment by emgarten** [comment]
@kzu

**Comment by kzu** [comment]
heya @adaoust, the latest template for a nuget package project will properly restore on CI.

To update your already unfolded project to support this, please add these three properties somewhere in your .nuproj inside a `PropertyGroup`:

```
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
<TargetFramework>netstandard1.0</TargetFramework>
<PackageTargetFallback>net11;net20;net35;net40;net403;net45;net451;net452;net46;net461;net462;net47;netcore;netcore45;netcore451;netcore50;win8;win81;win10;sl4;sl5;wp;wp7;wp75;wp8;wp81;wpa81;uap;uap10;netstandard1.0;netstandard1.1;netstandard1.2;netstandard1.3;netstandard1.4;netstandard1.5;netstandard1.6;netstandard2.0;netcoreapp1.0;netcoreapp2.0;monoandroid;monotouch;monomac;xamarinios;xamarinmac;xamarinpsthree;xamarinpsfour;xamarinpsvita;xamarinwatchos;xamarintvos;xamarinxboxthreesixty;xamarinxboxone</PackageTargetFallback>
```

**Comment by michaelkollmann** [comment]
Hi!

I just downloaded and installed the latest NuGetizer Visual Studio Extension for VS2017 and also created a NuGet project, just like @adaoust did. 

The latest version of the project template shipped with the extension already contains the three properties @kzu mentioned but it still doesn't compile.

@adaoust has been able to build the project locally but not on TFS. I don't have a TFS but I'm not able to build it locally either.

Can you help me with this?


Michael

**Comment by kzu** [comment]
Please provide a full diagnostics build log so I can investigate.

Thanks!

Important: you need to be on VS2017 Preview in order for NuGetizer to work property.

**Comment by michaelkollmann** [comment]
Thanks for your quick reply! 

So VS2017, Version 15.2 (26430.6) is not supported, only the latest Preview release?
Where is this defined? Couldn't find any details information about this, only that it requires VS2017.

Here you can find the build log:
[diagnosticsbuildlog.txt](https://github.com/NuGet/Home/files/1057060/diagnosticsbuildlog.txt)

**Comment by kzu** [comment]
Well, it depends, really. The *authoring* project (.nuproj) requires 15.3 to properly open and use (CPS issues prevented that from properly working in prior versions, where it would fallback to adding a packages.config and nothing working at all).

Building packages using the `/t:pack` target requires 15.3 for SDK-style projects, unless you workaround the issue in previous versions by passing a `/p:NuGetBuildTasksPackTargets=SOME_STRING` which causes the SDK targets for Pack to *not* be imported and override ours.

Your build log contains:

```
6>  Task "AssignTargetPath"
6>    Task Parameter:
6>        Files=
6>            packages.config
6>                    CopyToOutputDirectory=Never
```

Which is exactly the symptom I mention for the authoring project. You'll need to either create it again on a 15.3 preview VS, or manually tweak it to ressemble: https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/VisualStudio/NuGet.Packaging.VisualStudio.15/Templates/Projects/Nuget/Package/Package.nuproj

You'll need to add the NuGetizer package after that of course, like you would on any other project that needs to be packed.

I hope this makes sense!

**Comment by epicstar** [comment]
I thought I had this same exact problem (nuproj builds a nupkg as expected in my local machine but not my build slave), but it turned out that Visual Studio (Visual Studio Mac 7.6.9 build 22) was generating `<Nuproj_Project_Name>.nuget.props` and `<Nuproj_Project_Name>.nuget.targets` files with an absolute path pointing to my current user's home directory (see `$(NugetPackageRoot)`)

I replaced the absolute path to my $<MY_HOME_DIRECTORY>/.nuget/packages to $(UserProfile)/.nuget/packages and it seems to have fixed my problem, but the better question is: Why would creating a nuproj create files with absolute paths in the first place?

EDIT: actually, the solution is to use $(HOME) on macos's, and $(UserProfile) on Windows. So there needs to be different logic when setting the $(NugetPackageRoot) per OS. (ridiculous... I'm hating msbuild more and more everyday)

This issue I'm seeing is actually related to https://github.com/NuGet/Home/issues/1095
