### ISSUE TITLE
[Test Failure] No update under ‘References’ node after installing a package through PMC in C# UWP

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#5073]
**NuGet Version:** NuGet 4.3.0-Preview1-2506 (Insertable)
**VS Version:** D15Rel 26419.00
**OS Version:** Windows 10 RS2_Release 15063.2.170323-1837

**Repro Steps:**
1. Create a C# UWP through New Project->Visual C#->Windows Universal->Blank App (Universal Windows).
2. Open PMC and PM UI for this project.
3. Expand the **‘References’** node of the project in Solution Explorer.
4. Type **‘Install-package NUnit’** in PMC and hit Enter.
5. Check the ‘References’ node.

**Expected Result:**
The installed package show under the ‘References’ node.

**Actual Result:**
The installed package doesn’t show under the ‘References’ node as below screenshot.
![blendprneverupdate](https://cloud.githubusercontent.com/assets/20632625/25220439/62a19e10-25e4-11e7-8c58-eac57f8a297c.PNG)

**Note:**
1.It doesn’t repro if you install the package through PM UI.
2.It repro on D15Rel 26419.00 (NuGet Client 4.2.0-RTM-2451).

**Comment by v-luzh** [comment]
Repro on D15Rel 26507.00 both on VS and Blend. Update the title.

**Comment by mishra14** [comment]
No repro with VS 15.3.3
