### ISSUE TITLE
Updating NuGet packages in Visual Studio 2015 causes the project build to fail

### ISSUE THREAD

**Issue by saf-itpro** [NuGet/Home#5077]
In the Updates tab of NuGet Package Manager in `VS2015` I saw updates available for about 25 already installed packages. Most of the updates indicated an update from 1.0 to 1.1. So, I decided to update them. But, after the updates, when I tried to Rebuild solution the build failed with the errors shown below. I ran dotnet restore command as suggested by one error below but the build still fails with same errors. I followed the 3 steps described [here](https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/). I double clicked on each error to go to the place where error occurs but could not figure out what needs to be done. **Question**: How can I resolve the following errors so I can rebuild the solution again?

![capture](https://cloud.githubusercontent.com/assets/10931726/25236624/4feaa42a-25b6-11e7-8127-d1b0b433439c.PNG)

**Comment by mishra14** [comment]
@saf-itpro Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
