### ISSUE TITLE
Add a functional test/automation test that creates a project and adds a connected service. This ensures that NuGet on connected services scenario works properly

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#508]
Add a functional test/automation test that creates a project and adds a connected service. This ensures that NuGet on connected services scenario works properly

Steps should be the following:

1) Create Console application
2) Add connected service
3) Add Azure Storage
4) Configure and select an account

This installs a bunch of NuGet packages using the NuGet VS extensibility API

At this point, I don't know how this can be automated using powershell. Perhaps, UI framework is the only way to go

**Comment by danliu** [comment]
It would be hard for UI framework also for all of these steps. We have daily manual verifications on this scenario using latest builds, so automation can be P2 at this point.
