### ISSUE TITLE
[Consider] dotnet add package should support adding a package as a tool

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5086]
e.g. - 

`dotnet add package <tool_name> --isTool` -> This can be done within NuGet with least work load.

or

`dotnet add tool <tool-name>` -> This would require more work on dotnet cli side. But seems cleaner.

**Comment by mishra14** [comment]
Related: https://github.com/NuGet/Home/issues/5087

**Comment by shanselman** [comment]
PLEASE. :)

@mishra14 Maybe I can do this PR myself. Why is dotnet add tool "a lot more work?" Why can't we pair and do this in an hour?

**Comment by anangaur** [comment]
Second option please. 
`dotnet add tool <tool-name> `

**Comment by dasMulli** [comment]
Maybe something can even be done automatically for cli tools packages if the package type of the nuget package is set to `DotnetCliTool` (https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#setting-a-package-type)

**Comment by mishra14** [comment]
dupe of https://github.com/NuGet/Home/issues/4901
