### ISSUE TITLE
[Consider] dotnet remove package should support removing tools

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5087]
e.g. - 

`dotnet remove package <tool_name> --isTool` -> This can be done within NuGet with least work load.

or

`dotnet remove tool <tool/-name>` -> This would require more work on dotnet cli side. But seems cleaner.

**Comment by mishra14** [comment]
Related: https://github.com/NuGet/Home/issues/5086

Related task for dotnet add tool: https://github.com/NuGet/Home/issues/4901

**Comment by rrelyea** [comment]
as #4901 details, dotnetclitoolreferences are being phased out.
See: dotnet tool install -g
