### ISSUE TITLE
Package should include private lib assets from package ref

### ISSUE THREAD

**Issue by mhutch** [NuGet/Home#5103]
When building a NuGetizer package, if the project has PackageReferences with PrivateAssets=lib, then those references are copied to the output directory. However, they are not included in the the package.

This is important, for example, for msbuild tasks that depend on other assemblies and need them to be bundled alongside the tasks assembly.

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by mhutch** [comment]
This does not work for transitive package references :(

**Comment by kzu** [comment]
Ok, it looks like this will need some deeper inspection of the artifacts that nuget generates to determine this, because I'm not sure we're getting all the info we need in plain MSBuild to distinguish them (i.e. no `%(PrivateAssets)` metadata on assets resolved from nuget?

**Comment by kzu** [comment]
Full transitive support added in NuGetizer @mhutch. Feel free to close this :)

**Comment by aortiz-msft** [comment]
Closing per last comment. Also, this issue was for Nugetizer :)
