### ISSUE TITLE
Issue with powershell command from install.ps1 locking visual studio

### ISSUE THREAD

**Issue by adayIvey** [NuGet/Home#5107]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGetPackageExplorer, vs2017

NuGet version (x.x.x.xxx): 4.1.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.1 (26403.7)

OS version (i.e. win10 v1607 (14393.321)): win 7 sp1

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

i am trying to create a NuGet package that will run some Powershell the will call 'Scaffold-DbContext'
then i do this is looks like visual studio is trying to build the project but it just hangs and i have to end the process because visual studio never comes back.

if i run the 'Scaffold-DbContext' in the pm console directly is works fine but not from a powershell script that is executed during a NuGet package install.

Here is my powershell function

```
Function btnOK_Click()
{
	param($dbConnection, $modelName)
	
    	[void]$MyForm.Close()

	Write-Host 'dbConnection: ' $dbConnection
	Write-Host 'modelName: ' $modelName
         
        Scaffold-DbContext -Connection "data source=Test;initial catalog=Test;user id=TestUser;password=TestPassword" -Provider Microsoft.EntityFrameworkCore.SqlServer -OutputDir "Models" -Context "TestContext" -Force

}

```
1. - create Nuget package with Nuget package Explorer
    - add install.ps1 to nuget package
    - add code to install.ps1 to call Scaffold-DbContext (part of Entity Framework Core)

2. add Nuget Package to empty class library project in VS
 - VS locks up and never responds must kill vs process in task manager

...

I contacted the Entity Framework Core Team and got this reply:

install.ps1 is not something we have seen used very much and is not supported in the modern variants of NuGet. We strongly recommend that you find a different approach. If you still have problems when not using install.ps1, then please open a new issue for that.

Should i be running this command another way?

[EF Github issue i logged orginaly](https://github.com/aspnet/EntityFramework/issues/7926)

**Comment by zhili1208** [comment]
@alpaix looks like the issue you fixed

**Comment by alpaix** [comment]
Same as #4797.
