### ISSUE TITLE
When opening solution in VS2015RC with Nuget 3.0.0 error message is shown in Pacakge Manager Console:   "An item with the same key has already been added."

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#511]
When opening solution in VS2015RC with Nuget 3.0.0 error message is shown in Pacakge Manager Console:   "An item with the same key has already been added."

Because of the following. one of the project in solution had this in packages.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
<package id="EntityFramework" version="6.1.3" targetFramework="net452" />
<package id="EntityFramework" version="6.1.2" targetFramework="net452" />
</packages>
```

how did it get there? no idea.

**Comment by yishaigalatzer** [comment]
#481

**Comment by leonmeijer** [comment]
You can use the Powershell script below to find all duplicate packages in your solution. It finds all packages.config files recursively and per packages.config file, it checks for duplicate package ids.

$solutionFolder = "C:\MySolution"
$nugetPackageFile = "packages.config"

$files = Get-ChildItem -Path $solutionFolder -Filter $nugetPackageFile -Recurse

foreach ($file in $files)
{
    [xml]$xml = Get-Content $file.FullName
    $nodes = Select-Xml "/packages/package/@id" $xml
    $packageIds = @{}

    foreach ($node in $nodes) {
        $packageId = $node.Node.'#text'
        try
        {
            $packageIds.Add($packageId, $packageId)
        }
        Catch [System.ArgumentException]
        {
            Write-Host "Found duplicate package in " $file.FullName ". Duplicate package: $packageId"
        }
    }
}

**Comment by yishaigalatzer** [comment]
You probably want to move this comment to 481
