### ISSUE TITLE
Nugetizer is over-eager about adding framework references

### ISSUE THREAD

**Issue by mhutch** [NuGet/Home#5110]
Nugetizer always adds framework references, even when the primary output is tool or build extension and won't actually be referenced by the project.

IncludeFrameworkReferencesInPackage should default to false for primary output types.

**Comment by kzu** [comment]
> IncludeFrameworkReferencesInPackage should default to false for primary output types.
 
What would `primary output types` entail? Just build/tool or also lib?

**Comment by mhutch** [comment]
@kzu personally i would lean towards making `IncludeFrameworkReferencesInPackage` fully opt-in:

```xml
<IncludeFrameworkReferencesInPackage Condition="'$(IncludeFrameworkReferencesInPackage)'==''">
  true
</IncludeFrameworkReferencesInPackage>
````

But I think doing it for just lib projects would be okay:

```xml
<IncludeFrameworkReferencesInPackage Condition="'$(IncludeFrameworkReferencesInPackage)' == '' And '$(PrimaryOutputPackageFileKind)'=='lib'">
  true
</IncludeFrameworkReferencesInPackage>
````

**Comment by kzu** [comment]
Makes sense. I made it unnecessarily more complicated than that.
