### ISSUE TITLE
NuGetizer should not set target framework for build packages

### ISSUE THREAD

**Issue by mhutch** [NuGet/Home#5111]
NuGetizer always assigns a target framework to `PackageFiles` created from project output, even if they are `build` or `tool`.

This generally not the desired behaviour, as it causes them to be dependent on the framework of the host project. This make it impossible, for example, to write tools or build targets using .NET 4.6 and consume them from a .NET 4 or netstandard 1.6 project.

**Comment by kzu** [comment]
Good point. Since build *can* be TF dependent (if you want different imports depending on the project's TF), we just need a way to opt in/out of either behavior.

For tools, it may not make sense, I think?

**Comment by mhutch** [comment]
Agreed 👍
