### ISSUE TITLE
Why are nuget web requests so slow?

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#5112]
eg 

 * OK https://api.nuget.org/v3/registration1-gz/vandelay.fody/index.json 74412ms

**Comment by emgarten** [comment]
//cc @karann-msft @rrelyea who are investigating similar scenarios

**Comment by karann-msft** [comment]
+@skofman1 to do a server side investigation....

**Comment by mishra14** [comment]
This issue was moved to NuGet/NuGetGallery#4859

**Comment by SimonCropp** [comment]
this got moved to the gallery repo , when i was experiencing it in VS
