### ISSUE TITLE
Update error message from "-f" to "-force" since there are now two commands that start with f.

### ISSUE THREAD

**Issue by Thaoden** [NuGet/Home#5116]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
4.1.0.2450

## Detailed repro steps so we can see the same problem

1. Use nuget.exe spec on a project.
>nuget.exe spec MyProject.csproj
> Created 'MyProject.nuspec' successfully.

2. Attempt to re-spec the project. NuGet fails with:
> nuget.exe spec MyProject.csproj
> 'MyProject.nuspec' already exists, use -f to overwrite it.

3. Attempt to use suggested parameter -f, that parameter does not exist:
> e:\nuget.exe spec -f MyProject.csproj
> Ambiguous option 'f'. Possible values: Force ForceEnglishOutput.

4. Use parameter -force to overwrite:
> e:\nuget.exe spec -force .\MyProject.csproj
> Created 'MyProject.nuspec' successfully.

**Comment by zhili1208** [comment]
nuget.exe spec command have two option start with f : Force and ForceEnglishOuput. we need to fix error message

**Comment by mishra14** [comment]
This has been fixed - 

```
> ..\..\..\paths\nuget.exe spec
'project.nuspec' already exists, use -Force to overwrite it.
> ..\..\..\paths\nuget.exe help
NuGet Version: 4.4.0.4475
```
