### ISSUE TITLE
Silverlight package goes to sl14 instead of sl15

### ISSUE THREAD

**Issue by chris1248** [NuGet/Home#5118]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (4.0.0.2283):

dotnet.exe --version (1.0.0-preview2-003131):

VS version (2015):

OS version (win10):

Worked before? If so, with which NuGet version: 2.8

## Detailed repro steps so we can see the same problem

We are creating a nuget package for a silverlight DLL. The Silverlight package uses version 5.0 of Silverlight. 
Anyways, we pack and publish the assembly which works great. Then I wrote some build scripts to update the solution projects that depend on it. i.e. `Nuget update ....`

Previously when we used nuget version 2.8 the package would get restored to a folder that looked like this:
  <HintPath>packages\foo28.1704.20120-alpha\lib\sl**5**\foodll</HintPath>
but now the 'sl*' folder changed: it now looks like this:
  <HintPath>packages\foo28.1704.20120-alpha\lib\sl**4**\foodll</HintPath>

Is that fact that the 'sl*' folder changed a big deal? Or is it a non-issue?

**Comment by zhili1208** [comment]
@chris1248 it should not change the folder name, I just tried a sl5 package, the folder name is "sl50".
Could you provide a sample package we can look at?
