### ISSUE TITLE
dotnet restore should work for all configurations or have a parameter for specifying the configuration

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5119]
_From @stephan-tolksdorf on April 25, 2017 16:1_

The `dotnet restore` command should either restore dependencies and tools for all configurations of a solution/project or support specifying the configuration with a command line parameter. 

The `build` and `clean` commands have the `c|--configuration` parameter for this purpose.  With the `restore` command one currently has to use `dotnet restore /property:Configuration=Release`.

## Steps to reproduce

Create a new project with `dotnet new classlib -lang f#`.

In the created fsproj file replace `<TargetFramework>...</TargetFramework>` with 

```
<TargetFrameworks Condition="'$(Configuration)' == 'Debug'">netstandard1.6</TargetFrameworks>
<TargetFrameworks Condition="'$(Configuration)' != 'Debug'">net45</TargetFrameworks>
```

Then run `dotnet restore` and `dotnet build -c Release`.

## Expected  behavior

dotnet should properly build the project. 

## Actual behavior

The build fails with an error.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

_Copied from original issue: dotnet/cli#6404_

**Comment by zhili1208** [comment]
@livarcocc I followed the repro steps, the issue is building for netStandard included Compile Item Library.fs twice, one is included by default from disk, another is from csproj. I tried to remove the Compile Item or conditional include it from csproj, but it caused other issue. I don't think this is related to nuget.

**Comment by stephan-tolksdorf** [comment]
@zhili1208 Please note this is a repro case with an F# project where files shouldn't be included by default. If you run `dotnet restore /property:Configuration=Release` before `dotnet build -c Release` you won't get this error. AFAICT, this error is caused by `dotnet restore` not properly restoring for the `Release` configuration.

**Comment by zhili1208** [comment]
@stephan-tolksdorf thank you, "dotnet restore /property:Configuration=Release" fixed this error. But then I built successfully, what's the error message you got?

**Comment by stephan-tolksdorf** [comment]
I got the same error as you, before running "dotnet restore /property:Configuration=Release". 

The repro case is just a simple example demonstrating why the `dotnet restore` behaviour is problematic, or, depending on your point of view, `dotnet restore` should have a simple command-line option for setting the configuration, like `dotnet build` and `dotnet restore`.

**Comment by zhili1208** [comment]
I see, actually dotnet restore call "msbuild /t:restore" to start nuget restore, in this case, dotnet restore should use the configuration parameter like dotnet build, internally call "msbuild /t:restore /property:Configuration=Release". On nuget side, we might need to add "configuration parameter" to nuget.exe.

**Comment by lennoncork** [comment]
I have a similar problem with a project using the new .csproj format. The project file sets the build output based on configuration. If I delete the output and build a "Debug" configuration from withing Visual Studio everything works. If I switch to a "Release" project I get missing assembly references and nuget restore says there isn't anything to do. I have to unload and reload the project to kick nuget to realize that it needs to do a restore. 

The same problem applies when calling nuget from the command line. Nuget restore only restores to the "Debug" configuration by default. This means that we weren't able to build "Release" configurations from the build server. 

The workaround was switch from nuget to msbuild and call the configuration manually. 

```
<PropertyGroup>
    <TargetFrameworks>net461</TargetFrameworks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\output\$(AssemblyName)\bin\$(Configuration)</OutputPath>
    <BaseIntermediateOutputPath>..\output\$(AssemblyName)\obj\$(Configuration)</BaseIntermediateOutputPath>
</PropertyGroup>
```

**Comment by dasMulli** [comment]
Note that upcoming CLI 2.0.0-preview2 builds will do an implicit restore on run/build/publish/pack (https://github.com/dotnet/cli/pull/6762) so `dotnet build -c Release` will implicitly perform a restore for the desired configuration, so many of the issues here may already be mitigated in upcoming previews.

**Comment by rrelyea** [comment]
Discussed with @emgarten 

As @dasMulli says, it can work from command line, and will be easier with implicit restore in cli 2.0.0.

However, when you hinge what restore should do based on Debug/Release this is problematic inside of VS.
Currently, we don't use configuration when we restore.
Batch build will also not work, as you might build debug and release, but it would need 2 different restores.

given that we don't want to over-encourage usage of configuration to change restore -- we don't want to create a --configuration parameter for dotnet restore.

**Comment by timer84** [comment]
> Discussed with @emgarten
> 
> As @dasMulli says, it can work from command line, and will be easier with implicit restore in cli 2.0.0.
> 
> However, when you hinge what restore should do based on Debug/Release this is problematic inside of VS.
> Currently, we don't use configuration when we restore.
> Batch build will also not work, as you might build debug and release, but it would need 2 different restores.
> 
> given that we don't want to over-encourage usage of configuration to change restore -- we don't want to create a --configuration parameter for dotnet restore.

I have to say using configuration for restore makes a lot sense especially for solutions contain multiple dotNet targets. More and more projects are migrating from Framework to Core and it is common to have both versions live under the same hood. In this case we normally use 2 "Release" configurations to build the two separately. Unfortunately because "restore" doesn't use the configuration so it always fails when trying to restore the entire solution. Otherwise we need to restore each desired project one by one.
