### ISSUE TITLE
Pass $solution as a param to init.ps1

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#512]
From the [documentation](https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-running-powershell-scripts-during-package-installation-and-removal):

> At the top of your file, add this line: param($installPath, $toolsPath, $package, $project) .... 

> $project is a reference to the EnvDTE project object and represents the project the package is installed into. Note: This will be null in Init.ps1. In that case doesn't have a reference to a particular project because it runs at the solution level. 

Would be immensely useful for init scripts to actually have *some* context of the solution it's being installed into. I propose you pass the DTE.Solution as the $solution parameter for Init.ps1.

**Comment by davidfowl** [comment]
Why not just use $dte.Solution? It's not like you can have more than one...

**Comment by johnataylor** [comment]
What @davidfowl says. If you can get to it yourself just do it this way.

**Comment by kzu** [comment]
Would be nice if that was documented in the context of running scripts,
just like it is for projects. Seems like it's such an obvious thing ;)

**Comment by yishaigalatzer** [comment]
It is in the DTE documentation. We don't document every piece of every .NET/Visual Studio in NuGet itself.
