### ISSUE TITLE
dotnet restore doesn't restore Microsoft.NETCore.App package when a fixed RuntimeFrameworkVersion is used

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5120]
_From @kichalla on April 25, 2017 18:28_

**Scenario:** As part of our mirroring we currently get latest CLI and latest shared runtime. As you know the shared runtime that comes with CLI has been older compared to the one available as a separate download, we have been using `<RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>` property to get the latest version. But we sometimes want to lock into the shared runtime version that comes along with the CLI since this is general user experience

## Steps to reproduce
- Create a `.csproj` file using the following text
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.0-*</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>win7-x64;win7-x86;osx.10.12-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>
</Project>
```
- Run `dotnet restore /p:RuntimeFrameworkVersion=2.0.0-preview1-002028-00 -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --packages c:\temp\packoutput`

## Expected  behavior
Restores `microsoft.netcore.app` package into the package output directory
I see only these packages restored:
![image](https://cloud.githubusercontent.com/assets/6559784/25401306/4234e1e0-29aa-11e7-9064-00982996eb1b.png)

## Actual behavior
Does not restore the `microsoft.netcore.app` package into the package output directory

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview1-005825)

Product Information:
 Version:            2.0.0-preview1-005825
 Commit SHA-1 hash:  b4a821109d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\kichalla\.dotnet\x64\sdk\2.0.0-preview1-005825\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002061-00
  Build    : 2b70ec9c3b014af0c2a5f45de0e5b73a1ae51c09
```
cc @mikeharder 

_Copied from original issue: dotnet/cli#6406_

**Comment by zhili1208** [comment]
@kichalla Could you try to use dotnet cli preview2? I followed your repro steps, but couldn't repro the issue.
dotnet cli version is 2.0.0-preview2-005840

![capture1](https://cloud.githubusercontent.com/assets/7131513/25407812/ac54ecf8-29c0-11e7-8113-993adbebf512.PNG)
![capture](https://cloud.githubusercontent.com/assets/7131513/25407811/ac45c78c-29c0-11e7-94d6-f567fa9524a7.PNG)

**Comment by emgarten** [comment]
You might also check the ``packageFolders`` property in ``obj\project.assets.json``, this package could be coming from a fallback folder.

If restore completed successfully then it would have been found in one of the locations listed.

**Comment by kichalla** [comment]
You can close this issue. We are currently not getting shared runtime separately and are using the one from the CLI. Thanks.
