### ISSUE TITLE
Within Visual Studio Online, I can not restore private feed from VSTS

### ISSUE THREAD

**Issue by bytemaster-0xff** [NuGet/Home#5121]
## Details about Problem

NuGet product used: NuGet.exe, VSTS

Seems to be an issue with: NuGet version 3.3, 3.5 and 4.0:

Using VSTS Nuget Install (and Restore) Task

Within the Task Settings: 
Path to solution or packages.config: Engine.sln (originally had **\*.sln) 

I can restore from the private feed with Visual Studio.net, however I get the error below when attempting to restore as part of a build script. 

### Verbose Logs

Task         : NuGet Installer
Description  : Installs or restores missing NuGet packages
Version      : 0.2.31
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)

C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 3.5.0.1938 / 3.5.0
SYSTEMVSSCONNECTION exists true
C:\a\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe install -NonInteractive C:\a\1\s\Engine.sln -Verbosity Detailed
NuGet Version: 3.5.0.1938
Feeds used:
  https://slsys.pkgs.visualstudio.com/_packaging/lagovista/nuget/v3/index.json
  https://www.nuget.org/api/v2/
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='C:%5Ca%5C1%5Cs%5CEngine.sln'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='C:%5Ca%5C1%5Cs%5CEngine.sln' 16ms
  GET https://slsys.pkgs.visualstudio.com/_packaging/075c9aa6-9284-4390-ba1d-d7596d679056/nuget/v3/registrations2/c:/a/1/s/engine.sln/index.json
  BadRequest https://slsys.pkgs.visualstudio.com/_packaging/075c9aa6-9284-4390-ba1d-d7596d679056/nuget/v3/registrations2/c:/a/1/s/engine.sln/index.json 40ms
System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: An error occurred while retrieving package metadata for 'C:\a\1\s\Engine.sln' from source 'LagoVista Private Feed'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.HttpSource.<>c__DisplayClass13_0`1.<<ProcessStreamAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### Sample Project - nuget.config
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>    
    
    <clear />
    
    <add key="LagoVista Private Feed" value="https://slsys.pkgs.visualstudio.com/_packaging/lagovista/nuget/v3/index.json" />
    
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
</configuration>

**Comment by zhili1208** [comment]
nuget install can't use path of sln file, you need to use restore like following:
 NuGet.exe restore -NonInteractive C:\a\1\s\Engine.sln -Verbosity Detailed
