### ISSUE TITLE
Visual Studio 2015 NuGet 3.5 Unable to do Updates due to '500 Internal Server Error'

### ISSUE THREAD

**Issue by tkumark** [NuGet/Home#5122]
I get the below error when I try to do updates

> The V2 feed at 'https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/FindPackagesById()?id='Microsoft.ServiceFabric.Actors'' returned an unexpected status code '500 Internal Server Error'.
> The V2 feed at 'https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.ApplicationInsights'' returned an unexpected status code '500 Internal Server Error'.

I am running VS 2015 Update 3 with NuGet 3.5.
![nuget](https://cloud.githubusercontent.com/assets/2689801/25422025/01a6087e-2a7d-11e7-8d2c-aeed7bf70758.PNG)

**Comment by NuclearFishin** [comment]
I observed the same issue on my build server (AppVeyor), but seems to be working OK now- successful for 2 consecutive builds.

**Comment by zhili1208** [comment]
we had some server issue yesterday, they are fixed now. the v2 source should work now.
