### ISSUE TITLE
Hint path and Reference path

### ISSUE THREAD

**Issue by VQuery** [NuGet/Home#5123]
I set Hint path and reference path for same dll but hint path location not correct .Project getting unresolved assembly reference .Reference path contains that hint path mentioned assembly. 

Can we use same hint and reference path both reference in csproj?

**Comment by zhili1208** [comment]
@VQuery hint path is used during build time and reference path is used by VS to load all reference dll when VS IDE loads project. why hint path location is not correct in your case?
