### ISSUE TITLE
Visual Studio and project-local nuget.config

### ISSUE THREAD

**Issue by MarkPflug** [NuGet/Home#513]
I have a solution that has a local nuget.config in the root which adds a custom nuget package source. There seems to be a problem with Visual Studio caching the nuget server list before the solution is opened, so the custom server in the local nuget.config is not properly getting picked up. 

Repro steps:
Create a solution.
Add a nuget.config in the root solution folder, with a custom package source.
Open VS. 
Close the package manager console pane if it is open.
Restart VS with the package manager console closed.
Open the solution.
Open the Nuget package manager for the sln or the nuget console.
Notice that the custom source is in the package source dropdown list (expected)
Close VS.
Open VS (but not the solution).
Ensure the package manager console is open.
Notice that the dropdown list doesn't show the custom package source (expected).
Open the solution.
**Notice that the dropdown STILL doesn't show the custom package source.**

Operations against the custom package source will fail in this state. It seems that whatever configuration is cached in VS needs to be updated when a solution is opened.

**Comment by johnataylor** [comment]
@MarkPflug what vesrion of Visual Studio did you see this in?

**Comment by MarkPflug** [comment]
2015ctp6. Latest nuget as of today.
________________________________

**Comment by danliu** [comment]
assigned to harshgmsft

**Comment by harshgMSFT** [comment]
I tried to repro it with the latest build of vs and nuget, does not repro. @yishaigalatzer  I suggest we close this. @MarkPflug please let us know if you can repro this with the latest build.
