### ISSUE TITLE
Dependencies not installed when adding a package to a .NET Core application in Visual Studio 2015

### ISSUE THREAD

**Issue by Steve51D** [NuGet/Home#5130]
## Details about Problem

NuGet product used: NuGet.exe for creating package | VS UI for installing

NuGet versions: 
Package manager for Visual Studio 2015: 3.5.0.1484 
Version used to build package: 3.5.0.1938

VS version: Enterprise 2015 Update 3

OS version: Win10 v1607 14393.1066

## Detailed repro steps so we can see the same problem

1. Get package attached to this issue.
2. Create new .NET Core console application in VS 2015.
3. Add the package from step 1 as a reference using NuGet Package manager.

The assembly is added to the project as a reference but the dependencies are not added as expected.

## Other suggested things

Repeating the steps above in Visual Studio 2017, the dependencies are added as expected.

If a version of the package is built that adds the same dependencies for .NET Framework and the package is then installed for a regular .NET framework console application in Visual Studio 2015 then dependencies are added as expected.

### Sample NuGet package

[51Degrees.mobi-core.3.2.16.2.zip](https://github.com/NuGet/Home/files/962554/51Degrees.mobi-core.3.2.16.2.zip)

**Comment by Steve51D** [comment]
Just a little extra info - I updated to the latest beta of NGPM on VS 2015 (3.5.0.1996) and the dependencies are still not added as I would expect.
The version of NGPM I'm using in VS 2017 is 4.1.0.2427

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.

**Comment by MagicJohnJang** [comment]
Clean cache at `VS2017 > Tools > Options > NuGet Package Manager > General > Clear All NuGet Cache(s)` (Actually in %USERPROFILE%\.nuget)
That works for me.
