### ISSUE TITLE
Suppress the <dependencies> element when packing a project

### ISSUE THREAD

**Issue by jnm2** [NuGet/Home#5132]
Via https://github.com/NuGet/Home/issues/4059#issuecomment-297855568

When I pack my project using `msbuild /t:pack`, the generated nuspec contains an empty dependencies section. I'd like to be able to entirely remove the `<dependencies>` element:

```xml
    <dependencies>
      <group targetFramework=".NETFramework4.6.2" />
    </dependencies>
```

To me it makes sense to remove it by default if there are no dependencies, but if removing it can't be the default behavior for some reason, could I have some way to suppress it? In order of preference:

 1. Remove it by default if there are no dependencies
 2. A project-level `<SuppressDependencies>` property
 3. A command line switch I could use when calling msbuild

Edit: the new property to use is `<SuppressDependenciesWhenPacking>`.

**Comment by jnm2** [comment]
The only case where it makes sense to insert this is when there are no `net462` or lower folders, to allow the package to install.

**Comment by dazinator** [comment]
It seems I have logged a similar issue here: https://github.com/Microsoft/msbuild/issues/3044

What is the outcome of this?

**Comment by chuanboz** [comment]
I also want this to build source code only package, any update for this?

**Comment by bording** [comment]
@rohit21agrawal This something I'd like to see supported as well. Any thoughts on the feasibility of doing this?

**Comment by adamralph** [comment]
I really need this too.

**Comment by gitfool** [comment]
I had the same problem until now. Adding the following to the `csproj` file works for me:
```xml
<PropertyGroup>
  <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
</PropertyGroup>
```
See https://github.com/NuGet/NuGet.Client/pull/2237. (Note that the property was renamed along the way.)

**Comment by adamralph** [comment]
Thanks @gitfool, that works perfectly!

If only these things were documented... or at least if only someone from the NuGet team could have told us this earlier...

**Comment by adamralph** [comment]
FTR this is a dup of https://github.com/NuGet/Home/issues/6354 and I believe it can be closed.

**Comment by jnm2** [comment]
Yes, thanks for finding!

**Comment by mujdatdinc** [comment]
This is not working as expected. Looks like only one guy is using this.

**Comment by jnm2** [comment]
@mujdatdinc It's been working for me and several others. Can you clarify what you are doing and what you expect to see?
