### ISSUE TITLE
Suppress the <owners> element when it is redundant

### ISSUE THREAD

**Issue by jnm2** [NuGet/Home#5134]
When I pack my project using `msbuild /t:pack`, the generated nuspec contains this element which is redundant because the contents are identical to the `<authors>` element:

```xml
    <owners>...</owners>
```

To me it doesn't make sense to write the element at all because there is currently [no way to override it](https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target) in the csproj to become different than the authors element.

**Comment by zhili1208** [comment]
@rohit21agrawal  is there any way override this from /t:pack?

**Comment by anangaur** [comment]
@nkolev92 , isn't the owners element deprecated as the owners are decided on nuget.org and not at the client side?

**Comment by nkolev92** [comment]
Can't recall the exact details, but maybe @joelverhagen or @rrelyea have more context.

**Comment by joelverhagen** [comment]
It is not even read on nuget.org. That being said, it's possible other server implementations read it. I know NuGet.Server does.

In my opinion, it should not be populated by default and even "warned" if included.

**Comment by anangaur** [comment]
Thanks @joelverhagen . @jnm2 more add-on things for you if you want to implement this one too 😊

**Comment by jnm2** [comment]
I do! Is one PR for both okay?

**Comment by jnm2** [comment]
Eh, never mind. This one adds a warning. Separate is probably better.
