### ISSUE TITLE
nuget pack returns an ambiguous and confusing error when a dependency element isnt complete

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#5147]
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet version (3.4.4.1321):
VS version (if appropriate): 2017
OS version (i.e. win10 v1607 (14393.321)): Win 10 UWP edition
Worked before? If so, with which NuGet version: No idea, but this program has some very misleading error messages

## Detailed repro steps so we can see the same problem

Use this or similar nuspec. Note the prominent `<id>This.IS.the.ID</id>`. Also note the non-prominent `<dependency/>`. this is the problem component needed to repro the issue.
```
<?xml version="1.0" ?>
<package>
  <metadata>
    <id>This.IS.the.ID</id>
    <version>$version$</version>
    <title>$title$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>whoop de doop</description>
    <copyright>Copyright 2017</copyright>
    <tags>1990 tag soup</tags>
    <dependencies>
      <dependency />
    </dependencies>
  </metadata>
  <files>
    <file src="bin\$configuration$\my.dacpac" target="lib\net11" />
    <file src="tools\Install.ps1" target="tools\Install.ps1" />
    <file src="tools\Uninstall.ps1" target="tools\Uninstall.ps1" />

  </files>
</package>
```

2. Run a `nuget pack` with this nuspec

Expected: Either it builds or tells me whats wrong. 
Actual: It says `The required attribute 'id' is missing.`

I was checking to make sure the right files were being used, and tried changing the package ID several times before I started over and found this difference. I get that its my bad, but the error should at least say what element has the missing ID attribute.

**Comment by mishra14** [comment]
@StingyJack The error I am seeing has more context - 

`The required attribute 'id' is missing. This validation error occurred in a 'dependency' element.`

The dependency node does not have an `id`. Please let us know if you need more help.

**Comment by StingyJack** [comment]
I dont remember that additional text as it was a few months ago now, but the message as you state is still confusing.

It should really read `A validation error occurred in a 'dependency' element, the required attribute 'id' is missing. `.
