### ISSUE TITLE
Documentation and behavior flaws with PackageReference

### ISSUE THREAD

**Issue by JoGillis** [NuGet/Home#5151]
NuGet.exe 4.1.0.2450
VS2017 Enterprise 15.1(26403.7) - NuGet 4.1.0

1. The documentation lists the Version under PackageReference as an attribute, but when a reference is added to a project by the VS Addin, it is stored as an element. The NuGet executable does not seem to have any problem with this, but it is rather confusing.

2. The VS Addin will always force the complete version number into this Version Element, which is inconvenient if it was configured to use a floating version, you will loose the floating part after an update in VS. It also seems the VS Addin does not recognize the floating part and will interprete 1.1.1.* as 1.1.1, which is something completely different in behavior. (the exe does not seem to have this problem and offers the latest version available in range). A solution could be to use the attribute for the (manually probably) permissive range definition and the element for the current used version in VS. And the two tools (addin and exe) should behave the same on those definitions.

3. The PackageReferences are not automatically transferred into a nupkg file if the exe is used (Nuget.exe pack UC.vbproj). (Tested on a CI server with only build tools; a nuspec file is present in the project with the same name as the project file to get a little more control over description, icon etc.) 

Doc available at:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by JoGillis** [comment]
Not only regarding documentation: Also Tool behavior

**Comment by mishra14** [comment]
Closing after offline discussion with @jainaashish
