### ISSUE TITLE
Option in nuget.exe to push dependencies located in same source folder as the target nupkg file

### ISSUE THREAD

**Issue by vskab** [NuGet/Home#5155]
We need an option in nuget.exe to push dependencies located in same source folder as the target nupkg file.

NuGet product used: NuGet.exe
NuGet version: 3.5.0.1938

We have several nupkg files in a drop folder, all are "ours", produced by our build. 
But we want to push only one of them plus all its dependencies from the same drop folder.

**Comment by mishra14** [comment]
@vskab you can do this by generating the package and the closure in a separate directory using the `OutputDirectory` option in pack. The you can run `nuget push *.nupkg` in that directory.
