### ISSUE TITLE
NuGet.org gallery doesn't support packages with minClientVersion = 4.0.0

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#5156]
**Repro**
1. Create a package with
```xml
<metadata minClientVersion="4.0.0">
```
2. Attempt to push package via NuGet.exe or upload on the nuget.org manually.

**Error**
The push fails with this error
> This package requires version '4.0.0' of NuGet, which this gallery does not currently support. Please contact us if you have questions.

**Comment by skofman1** [comment]
Issue moved to [NuGet/NuGetGallery #3866](https://github.com/NuGet/NuGetGallery/issues/3866) via [**ZenHub**](https://www.zenhub.com/)
