### ISSUE TITLE
Files without an extension cannot be added to NuGet package

### ISSUE THREAD

**Issue by alinapopa** [NuGet/Home#5158]
Using Visual Studio 2017 and the new project system.
File is included as:
` <Content Include="..\..\LICENSE" />`
The resulting NuGet package gives the following error when trying to open it with NuGet Package Explorer:
![image](https://cloud.githubusercontent.com/assets/8061142/25688452/1b37826a-3034-11e7-8bce-c1662893c4dd.png)
This is caused by LICENSE file not having an extension (does not happen if file is renamed to LICENSE.txt or another extension; also happens with any file that does not have an extension).
Repro project: https://github.com/alinapopa/Windsor/tree/NuGetReproFileWNoExtension
Link to resulting packages: https://ci.appveyor.com/project/alinapopa/windsor/build/1.0.90/artifacts
There is a similar issue #2936 that is closed/fixed but in this scenario the problem does not appear to be fixed.

**Comment by nkolev92** [comment]
NuGetPackageExplorer is not a Microsoft product and it's not managed by the NuGet team.

You can create an issue for that here:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

**Comment by alinapopa** [comment]
The same error appears for publishing:
Error publishing NuGet package artifact Packages/Castle.LoggingFacility.3.4.0.nupkg: NuGet package cannot be read: Part URI is not valid per rules defined in the Open Packaging 
https://ci.appveyor.com/project/alinapopa/windsor/build/1.0.90/messages
