### ISSUE TITLE
Package Manager should make network calls for package details in background

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#516]
The Package Manager needs to make multiple network calls to display the information required by the UI.

For V2 in a search after making the initial Search query call the subsequent FindPackageById calls should all be made in the background. (Note they are made concurrently and are reasonably fast on a good network, they are not in the background.)

This is not an issue with V3 because all the data is returned in the initial search call.

This also happens for showing "Installed" packages. Although the client has the package details, it does not have knowledge of the other versions which it needs to display the "update available" icon which is shown in the main package list. (It also needs this data for the version drop down, though that is less significant and easily made on demand.)

### Note it needs to make network calls for "Installed" packages for both V2 and V3. ###
The side effect is that packages coming from an invalid source are not shown! 

The result is that even for "Installed" packages the left hand pane shows the "Loading..." delay when you scroll.

A better user experience would be had if the UI made many of these network calls in the background and lazily update the relevant aspects of the view.

**Comment by feiling** [comment]
This was fixed by Yishai. Now the version lists are loaded in the background. See https://github.com/NuGet/NuGet.PackageManagement/commit/1dcd25c4a7e66aae2a8d601e017f1dd6f4be89f4
