### ISSUE TITLE
AppendTargetFrameworkToOutputPath=false causes packaging errors for multi-targeting projects

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5160]
I set AppendTargetFrameworkToOutputPath=false in my projects because I use a read only source tree and redirect my bin and obj directories to other places. In particular, I add the TFM to my path myself to layout my directories in a way that makes sense for my repo. But I discovered that in setting AppendTargetFrameworkToOutputPath=false, when nuget packs my projects, it malfunctions and causes all assemblies to be added to the lib folder directly instead of under lib\TFM folders.

## Repro steps

Define a csproj file with this content:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.1;net45</TargetFrameworks>

    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <BaseIntermediateOutputPath>obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\$(TargetFramework)\</IntermediateOutputPath>
    <OutputPath>bin\$(Configuration)\$(TargetFramework)\$(MSBuildProjectName)\</OutputPath>
    <PackageOutputPath>bin\$(Configuration)\Packages\</PackageOutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

</Project>
```

Then execute these commands:
```
dotnet restore
dotnet pack
```

## Expected
No build warnings, and a nuspec file in my obj folder that reveals that two assemblies are copied into the nuget package, like this:

```xml
  <files>
    <file src="F:\temp\bin\Debug\netstandard1.1\temp\netstandard1.1\temp.dll" target="lib\netstandard1.1\temp.dll" />
    <file src="F:\temp\bin\Debug\net45\temp\net45\temp.dll" target="lib\net45\temp.dll" />
  </files>
```

I see the expected behavior when `AppendTargetFrameworkToOutputPath=true`.

## Actual

The Nuspec file only specified one assembly, without the TFM path:
```xml
  <files>
    <file src="F:\temp\bin\Debug\netstandard1.1\temp\temp.dll" target="lib\temp.dll" />
  </files>
```

And the build emitted several warnings stating that the temp.dll should be under a lib\TFM directory.

## Version info
```
dotnet --version
2.0.0-preview1-005842
```

**Comment by rohit21agrawal** [comment]
@AArnott this has already been fixed (but not integrated into CLI) . please ping me if you are interested to use nightly build of Pack.

**Comment by rohit21agrawal** [comment]
was fixed via : https://github.com/NuGet/NuGet.Client/pull/1255

**Comment by AArnott** [comment]
@rohit21agrawal yes, please. It will cost me 1-2 full days to workaround this bug. So I'd prefer to apply a patch with your nightly build if possible.

**Comment by rohit21agrawal** [comment]
i'll send you an email
