### ISSUE TITLE
Language Satellite assemblies not copied to output directory in CPS PackageRef for net46

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#5164]
When using a NuGet package that uses satellite assemblies for localized resources in a CPS net46 with PackageReference, the localized resources are not copied to the correct subdirectory in the output folder.

.NET Core apps work fine because they resolve from the package cache directly with the .deps.json file.

To repro:
Check out the `integration-test` branch of Humanizer: https://github.com/Humanizr/Humanizer/tree/integration-test

Restore and build the test project. Look at the output directory. Humanizer.dll is there. So is one particular languages Humanizer.resources.dll (but that doesn't belong in the root folder, it goes in a subfolder). There are dozens of languages missing. Tests naturally fail.

A P2P reference works fine.

**Comment by clairernovotny** [comment]
Looks like a dup/another instance of https://github.com/dotnet/sdk/issues/1006

**Comment by rrelyea** [comment]
Which version/build of VS are you using?

**Comment by clairernovotny** [comment]
I'm using 15.2 (26430.1-Preview)

**Comment by rrelyea** [comment]
It does appear that this is the same issue as the SDK bug. Reason to keep it open over here?

**Comment by clairernovotny** [comment]
@rrelyea nope - I didn't see that bug until after I opened this one

**Comment by rrelyea** [comment]
k. thx.
