### ISSUE TITLE
dotnet pack takes dependencies from other .csproj file!

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5165]
_From @joelharkes on May 4, 2017 9:33_

I have an an repo like this

```
\src
-\RestClient
--\Models\..
--\Api\..
--\Client\..
--\RestClient.csproj
--\RestClient.Models.csproj
\solution.sln
```

My RestClient.Models.csproj consists of:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45</TargetFrameworks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.3.0" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Model\*.cs" />
  </ItemGroup>
</Project>
```

Now when i run `dotnet pack -c Release`. But in the .nupkg their are now dependencies that i register in the `RestClient.csproj`, instead of having no dependencies!

in Nuget Package Explorer:
![image](https://cloud.githubusercontent.com/assets/2960938/25697966/54695458-30bd-11e7-96eb-9fafad8be9ab.png)

## Expected result

I Expect to have no nuget package dependencies!

_Copied from original issue: dotnet/sdk#1177_

**Comment by joelharkes** [comment]
It seems dependencies are taken from bin or obj folder instead of Csproj

**Comment by joelharkes** [comment]
I got it working by moving one of the project files to another folder next to it.

**Comment by nguerrera** [comment]
Ah! I missed the subtlety that the two projects are next to each other and end up with colliding assets file paths. Looks like a dupe of #4463, which itself dupes #4154.

**Comment by joelharkes** [comment]
@nguerrera thanks, i see the dup's, I'll close this issue.

**Comment by joelharkes** [comment]
Ah you posted it you may close it.
