### ISSUE TITLE
dotnet restore performance

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5169]
_From @Mpdreamz on May 5, 2017 11:55_

`dotnet restore` seems to behave very poorly on my machine, even in cases where nothing has changed and the lock files are in sync:

![dotnet-restore](https://cloud.githubusercontent.com/assets/245275/25744429/2bd72b22-319a-11e7-8eb1-3fdc7bad5a34.gif)

The call to `MsBuild.dll` is immediate (as is the telemetry http call). Then there is a mysterious lag before we continue. 

The lock file checks themselves seem slow as well.

```
c:\Projects\elastic\net-5>dotnet restore src\Elasticsearch.sln -v diagnostic
C:\Program Files\dotnet\sdk\1.0.1\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\1.0.1\dotnet.dll /m /t:Restore /v:m /verbosity:diagnostic src\Elasticsearch.sln
  Restoring packages for c:\Projects\elastic\net-5\src\Tests\Tests.csproj...
  Restoring packages for c:\Projects\elastic\net-5\src\Nest\Nest.csproj...
  Restoring packages for c:\Projects\elastic\net-5\src\Elasticsearch.Net\Elasticsearch.Net.csproj...
  Restoring packages for c:\Projects\elastic\net-5\src\CodeGeneration\ApiGenerator\ApiGenerator.csproj...
  Restoring packages for c:\Projects\elastic\net-5\src\CodeGeneration\DocGenerator\DocGenerator.csproj...
  Restoring packages for c:\Projects\elastic\net-5\src\Tests\Tests.csproj...
  Lock file has not changed. Skipping lock file write. Path: c:\Projects\elastic\net-5\src\CodeGeneration\ApiGenerator\obj\project.assets.json
  Restore completed in 139.27 ms for c:\Projects\elastic\net-5\src\CodeGeneration\ApiGenerator\ApiGenerator.csproj.
  Lock file has not changed. Skipping lock file write. Path: c:\Projects\elastic\net-5\src\Elasticsearch.Net\obj\project.assets.json
  Restore completed in 291.05 ms for c:\Projects\elastic\net-5\src\Elasticsearch.Net\Elasticsearch.Net.csproj.
  Lock file has not changed. Skipping lock file write. Path: c:\Projects\elastic\net-5\src\Nest\obj\project.assets.json
  Restore completed in 300.35 ms for c:\Projects\elastic\net-5\src\Nest\Nest.csproj.
  Lock file has not changed. Skipping lock file write. Path: c:\Projects\elastic\net-5\src\CodeGeneration\DocGenerator\obj\project.assets.json
  Restore completed in 303.13 ms for c:\Projects\elastic\net-5\src\CodeGeneration\DocGenerator\DocGenerator.csproj.
  Restore completed in 827.75 ms for c:\Projects\elastic\net-5\src\Tests\Tests.csproj.
  Lock file has not changed. Skipping lock file write. Path: c:\Projects\elastic\net-5\src\Tests\obj\project.assets.json
  Restore completed in 1.2 sec for c:\Projects\elastic\net-5\src\Tests\Tests.csproj.

  NuGet Config files used:
      c:\Projects\elastic\net-5\NuGet.Config
      C:\Users\Mpdreamz\AppData\Roaming\NuGet\NuGet.Config
```

_Copied from original issue: dotnet/cli#6524_

**Comment by emgarten** [comment]
@nkolev92 this looks like it would be fixed with the noop work.

**Comment by neilcawse** [comment]
@emgarten There are serious issues with dotnet restore performance in the latest 2.0.0-preview2 SDK.
dotnet restore is crazy slow even after its succeeded.
I deleted *all* files out of my project except for around 200 .cs files in various sub directories and added a minimal project below.
Restore took 30s. If I remove all the cs files its instant.
This can't be released like this.
I do have both 1.0.4 SDK and 2.0.0-preview2 installed if that matters.
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
        <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
</Project>

**Comment by emgarten** [comment]
Restore uses msbuild to evaluate the projects and get the list of *PackageReferences*. If the project is very slow to load Restore will also be slow, same as other targets. A good way to compare is to run *dotnet msbuild /t:clean* on your solution, that time should be similar to how long it takes just to evaluate the projects.

The original issue here for improving performance on the 2nd restore has been fixed here: https://github.com/NuGet/Home/issues/5080

**Comment by neilcawse** [comment]
@emgarten on this minimal project I ran:
dotnet restore
Time Elapsed 00:00:26.94
and
dotnet msbuild /t:clean
Time Elapsed 00:00:09.51

in verbose mode it looks like msbuild is being run 3 times by dotnet restore so poor performance in msbuild is magnified 3 times.

**Comment by emgarten** [comment]
@neilcawse would you open a new issue and provide a repro solution that I can try?
