### ISSUE TITLE
NuGet VS and nuget.exe restore with different results in project.lock.json

### ISSUE THREAD

**Issue by wilgf** [NuGet/Home#5175]
[Download All Attachments.zip](https://github.com/NuGet/Home/files/982267/Download.All.Attachments.zip)
## Details about Problem

The problem is the NuGet Package Manager in Visual Studio automatic restore writes different output to the project.lock.json file than nuget.exe does.  The end result is three xml files in TelerikLib.nupkg are omitted from the build.  Dir output for both scenarios is below.

1. If I run a build + automated restore from visual studio I get my nupkg restored and built into the bin folder minus three xml files. 12 files total.

May/07/2017  10:39 AM    <DIR>          .
May/07/2017  10:39 AM    <DIR>          ..
May/06/2017  11:19 AM           315,904 TelerickLib.dll
May/06/2017  11:19 AM         2,657,280 Telerik.WinControls.dll
May/06/2017  11:19 AM         1,644,544 Telerik.WinControls.GridView.dll
May/06/2017  11:19 AM           590,848 Telerik.WinControls.Themes.TelerikMetro.dll
May/06/2017  11:19 AM         4,862,464 Telerik.WinControls.UI.dll
May/06/2017  11:19 AM           342,016 TelerikCommon.dll
May/07/2017  10:39 AM             7,680 WindowsFormsApplication1.exe
May/07/2017  10:28 AM               184 WindowsFormsApplication1.exe.config
May/07/2017  10:39 AM            19,968 WindowsFormsApplication1.pdb
May/07/2017  10:28 AM            22,688 WindowsFormsApplication1.vshost.exe
May/07/2017  10:28 AM               184 WindowsFormsApplication1.vshost.exe.config
Jul/16/2016  07:44 AM               490 WindowsFormsApplication1.vshost.exe.manifest
              **12 File(s)     10,464,250 bytes**
               2 Dir(s)  334,890,049,536 bytes free

2. If I disable automatic restore (no checkboxes set in VS options.Nuget), but run nuget.exe restore on the solution and follow with a build I get the three xml files as well as TelerikLib.dll.

May/07/2017  10:46 AM    <DIR>          .
May/07/2017  10:46 AM    <DIR>          ..
May/06/2017  11:19 AM           315,904 TelerickLib.dll
May/06/2017  11:19 AM         2,657,280 Telerik.WinControls.dll
May/06/2017  11:19 AM         1,644,544 Telerik.WinControls.GridView.dll
May/06/2017  11:19 AM         1,236,915 Telerik.WinControls.GridView.xml
May/06/2017  11:19 AM           590,848 Telerik.WinControls.Themes.TelerikMetro.dll
May/06/2017  11:19 AM         4,862,464 Telerik.WinControls.UI.dll
May/06/2017  11:19 AM         2,973,007 Telerik.WinControls.UI.xml
May/06/2017  11:19 AM         1,128,044 Telerik.WinControls.xml
May/06/2017  11:19 AM           342,016 TelerikCommon.dll
May/07/2017  10:46 AM             7,680 WindowsFormsApplication1.exe
May/07/2017  10:28 AM               184 WindowsFormsApplication1.exe.config
May/07/2017  10:46 AM            19,968 WindowsFormsApplication1.pdb
May/07/2017  10:28 AM            22,688 WindowsFormsApplication1.vshost.exe
May/07/2017  10:28 AM               184 WindowsFormsApplication1.vshost.exe.config
Jul/16/2016  07:44 AM               490 WindowsFormsApplication1.vshost.exe.manifest
              **15 File(s)     15,802,216 bytes

**
               2 Dir(s)  334,878,879,744 bytes free

FIFTEEN files.  Three xml files get restored as well, which is what I was expecting within Visual Studio Package Manager.

Two different build and restore approaches, but two different outputs?

I have included a sample winforms project (net new, nothing in it but project.json file) and my TelerikLib.nupkg package.

It appears that when the automatic build and restore happens the build writes 117 lines to the project.lock.json file.

when I use the manual restore from nuget.exe and a manual build the process writes 73 lines instead.

I am including the two project.lock.json files as well for reference.

This is just a basic windows forms project.  I do have a full project at work, but the problem exists even with a stripped down project like attached.

The two restore approaches (NPM and nuget.exe) seem to write different output to project.lock.json.  That appears to be the root of the problem.

--------------------------------------------------------------------------------------------
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 3.5.0.1938

dotnet.exe --version (if appropriate):NA

VS version (if appropriate): VS 2015 Enterprise

OS version (i.e. win10 v1607 (14393.321)): Microsoft Windows [Version 10.0.14393]

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Use automatic build and restore (SET allow Nuget to download missing packages + SET automatically check for missing packages during build in Visual Studio.  Run clean solution and build.  You get 12 files in your bin.

2. UNSET allow Nuget to download missing packages and UNSET automatically check for missing packages during build in Visual Studio.  Run nuget.exe restore $(SolutionPath), and then build solution in Visual Studio.  You get all 15 files in your bin.

Why does VS NPM omit the xml files but nuget.exe restores them just fine?  Should they not behave the same way?

The two restore approaches (NPM and nuget.exe) seem to write different output to project.lock.json. That appears to be the root of the problem.
...

### Sample Project

I have attached a SAMPLE project, the two project.lock.json file outputs for both scenarios, as well as a copy of the TelerikLib.nupkg file I am using.

**Comment by nkolev92** [comment]
Hey @wilgf 

Apologies for the long delay. 
At this point we've tried to address as many of the discrepancies as possible among commandline and VS restore. 

Given the age of this issue, move to packagereference, and the fact that the lock files in the attachment are unactionable (one of the contains a class file, not the project.lock.json content), I'm gonna close this issue. 

if you are still seeing a related problem, please open a new issue. 

Thank you.
