### ISSUE TITLE
[Consider] Keep track of a source which contains a package

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5184]
We should allow users to correlate a package with a source. This will prevent the initial discovery phase and the corresponding http calls to all the sources till the package is pulled down into the cache.

Possible solutions (In the order of preference)- 

1. Allow users to correlate a source with packages in `NuGet.Config` files.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>

  <packageDependencies>
    <nuget.org>
      <package id="PackageThatIsOnlyOnNuGet.Org"/>
    </nuget.org>
  </packageDependencies>
  
</configuration>

```
2. Create a new restore graph file.
3. Write the information into the `NuGet.Cache` file that will be added with restore no-op work.
2. Write down this info into the assets file and make restore use that.

**Comment by nkolev92** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/6867. 

This one is older but the other one is tracked by customers.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/6867

**Comment by MV10** [comment]
Ideally we could also indicate that it should _only_ come from the source. Particularly during active development with a local source, caching just gets in the way. This is badly needed.

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/3785.

> Ideally we could also indicate that it should _only_ come from the source. Particularly during active development with a local source, caching just gets in the way. This is badly needed.

Yep, definitely something on our radar. https://github.com/NuGet/Home/issues/6867 and https://github.com/NuGet/Home/issues/6579 are the 2 related issues.
