### ISSUE TITLE
Nugetizer doesn't install

### ISSUE THREAD

**Issue by bradphelan** [NuGet/Home#5194]
I tried to install

https://ci.appveyor.com/api/buildjobs/c8kgd3o5mu4vqwp6/artifacts/out%2FNuGetizer3000-VS2017.vsix

to VS2017 but it crashed with the following log

> 5/9/2017 12:00:04 PM - Microsoft VSIX Installer
> 5/9/2017 12:00:04 PM - -------------------------------------------
> 5/9/2017 12:00:04 PM - vsixinstaller.exe version:
> 5/9/2017 12:00:04 PM - 15.0.26403.7 built by: D15SVC
> 5/9/2017 12:00:04 PM - -------------------------------------------
> 5/9/2017 12:00:04 PM - Command line parameters:
> 5/9/2017 12:00:04 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,C:\Users\phelan\Downloads\NuGetizer3000-VS2017 (2).vsix
> 5/9/2017 12:00:04 PM - -------------------------------------------
> 5/9/2017 12:00:04 PM - Microsoft VSIX Installer
> 5/9/2017 12:00:04 PM - -------------------------------------------
> 5/9/2017 12:00:04 PM - Initializing Install...
> 5/9/2017 12:00:04 PM - Extension Details...
> 5/9/2017 12:00:04 PM - 	Identifier         : NuGet.Packaging
> 5/9/2017 12:00:04 PM - 	Name               : NuGetizer-3000
> 5/9/2017 12:00:04 PM - 	Author             : Microsoft
> 5/9/2017 12:00:04 PM - 	Version            : 0.1.252
> 5/9/2017 12:00:04 PM - 	Description        : NuGet Package Authoring Tools
> 5/9/2017 12:00:04 PM - 	Locale             : en-US
> 5/9/2017 12:00:04 PM - 	MoreInfoURL        : 
> 5/9/2017 12:00:04 PM - 	InstalledByMSI     : False
> 5/9/2017 12:00:04 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - 	SignatureState     : Unsigned
> 5/9/2017 12:00:04 PM - 	Supported Products : 
> 5/9/2017 12:00:04 PM - 		Microsoft.VisualStudio.Pro
> 5/9/2017 12:00:04 PM - 			Version : [15.0]
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - 	References         : 
> 5/9/2017 12:00:04 PM - 		-------------------------------------------------------
> 5/9/2017 12:00:04 PM - 		Identifier   : Merq
> 5/9/2017 12:00:04 PM - 		Name         : Extensibility Message Bus
> 5/9/2017 12:00:04 PM - 		Version      : [1.1.17,)
> 5/9/2017 12:00:04 PM - 		MoreInfoURL  : 
> 5/9/2017 12:00:04 PM - 		Nested       : Yes
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - 		-------------------------------------------------------
> 5/9/2017 12:00:04 PM - 		Identifier   : Clide
> 5/9/2017 12:00:04 PM - 		Name         : Clide
> 5/9/2017 12:00:04 PM - 		Version      : [3.0.107,)
> 5/9/2017 12:00:04 PM - 		MoreInfoURL  : 
> 5/9/2017 12:00:04 PM - 		Nested       : Yes
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - 	Prerequisites      : 
> 5/9/2017 12:00:04 PM - 		-------------------------------------------------------
> 5/9/2017 12:00:04 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 5/9/2017 12:00:04 PM - 		Name         : Visual Studio core editor
> 5/9/2017 12:00:04 PM - 		Version      : [15.0,16.0)
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - Signature Details...
> 5/9/2017 12:00:04 PM - 	Extension is not signed.
> 5/9/2017 12:00:04 PM - 
> 5/9/2017 12:00:04 PM - Searching for applicable products...
> 5/9/2017 12:00:04 PM - Found installed product - Microsoft Visual Studio Professional 2015
> 5/9/2017 12:00:04 PM - Found installed product - Microsoft Visual Studio Community 2015
> 5/9/2017 12:00:04 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
> 5/9/2017 12:00:04 PM - Found installed product - Global Location
> 5/9/2017 12:00:04 PM - Found installed product - Visual Studio Professional 2017
> 5/9/2017 12:00:04 PM - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\master.pkgdef
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: Creating PkgDefCacheNonVolatile
> 5/9/2017 12:00:04 PM - PKGDEF Information: Double-checking master pkgdef file
> 5/9/2017 12:00:04 PM - PKGDEF Information: PkgDefManagement initialized
> 5/9/2017 12:00:04 PM - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.admin.pkgdef
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Users\phelan\AppData\Local\Microsoft\VisualStudio\15.0_4b5c1cff\Extensions
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions
> 
> 5/9/2017 12:00:04 PM - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
> 5/9/2017 12:00:04 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
> 5/9/2017 12:00:04 PM - PKGDEF Information: PkgDefCache flags, PKGDEF: 7001
> 5/9/2017 12:00:04 PM - PKGDEF Information: Could not find ConfigurationChanged timestamp., PKGDEF: 80070002
> 5/9/2017 12:00:04 PM - PKGDEF Information: PkgDefManagement startup complete
> 5/9/2017 12:00:05 PM - The extension with ID 'NuGet.Packaging' is not installed to Visual Studio Professional 2017.
> 5/9/2017 12:00:09 PM - The following target products have been selected...
> 5/9/2017 12:00:09 PM - 	Visual Studio Professional 2017
> 5/9/2017 12:00:09 PM - 
> 5/9/2017 12:00:10 PM - Beginning to install extension to Visual Studio Professional 2017...
> 5/9/2017 12:00:13 PM - Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'Merq' nested within 'NuGet.Packaging' failed to install.
> Installation of Extensibility Message Bus failed. To install this extension please install at least one of the following components: Xamarin ---> System.InvalidOperationException: Installation of Extensibility Message Bus failed. To install this extension please install at least one of the following components: Xamarin
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
>    --- End of inner exception stack trace ---
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformLegacyInstall(InstallableExtensionImpl extension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Boolean isPackComponent, IInstalledExtension& newExtension)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
>    at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
>

**Comment by kzu** [comment]
Fixed with https://github.com/NuGet/NuGet.Build.Packaging/issues/121
