### ISSUE TITLE
Tools lock file should not be written to global location

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5196]
_From @pakrym on May 10, 2016 23:8_

Changing tools import would produce different lock files which will conflict if storing in global location.
@davidfowl  @piotrpMSFT 

_Copied from original issue: dotnet/cli#2979_

**Comment by livarcocc** [comment]
_From @brthor on May 11, 2016 0:55_

cc @joelverhagen @emgarten 

This is a design issue with imports in tools. The package graph of an individual tool is dependent on the project and is not global because of imports. 

As long as we have imports I think we must move the lock file/deps file to be project local to solve this issue.

**Comment by livarcocc** [comment]
_From @joelverhagen on May 11, 2016 15:45_

@brthor, is the global lock file really needed? Can't the hosting project's lock file be inspected for the interesting bits of information, i.e. the `"tools"` and `"projectFileToolGroups"` sections in the lock file.

**Comment by livarcocc** [comment]
_From @brthor on May 11, 2016 18:0_

@joelverhagen That's a good solution but wouldn't we then need an entire lock file for the tool inside the lock file for the project?

The issue being that we need all of the same information to generate a deps file.

**Comment by livarcocc** [comment]
_From @piotrpMSFT on May 11, 2016 23:54_

We need to figure out how to get rid of imports. What is being suggested here won't scale for global commands.

**Comment by livarcocc** [comment]
_From @brthor on May 12, 2016 0:1_

Removing import support would be ideal for retaining the current design. The issue there being many of the tools rely on imports for bringing in packages like IxAsync. 

Some folks suggested those tool packages could make stronger use of packInclude to work around this.

**Comment by livarcocc** [comment]
_From @piotrpMSFT on May 26, 2016 23:10_

Let's make the plan to remove imports by the time we RTM the CLI?

**Comment by emgarten** [comment]
Import support for tools was removed in 4.0.0
