### ISSUE TITLE
SemVer 2.0: client ignores metadata part when packing

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#5197]
Client version: 4.3.0.4045
Repro:
1. Project used: https://github.com/NuGet/NuGetGallery/tree/master/src/NuGetGallery.Core
2.  Add attribute [assembly: AssemblyInformationalVersion("10.0.2-skofman.1.1.1.1+bla22")] for version
3. Run pack:  \\nuget\nuget\Share\Drops\CI\NuGet.Client\dev\4045\artifacts\VS15\NuGet.exe pack NuGetGallery.Core.csproj

Result: metadata part is ignored and package is created with version 10.0.2-skofman.1.1.1.1

//cc @joelverhagen @emgarten

**Comment by mishra14** [comment]
@rohit21agrawal could you please evaluate this?
