### ISSUE TITLE
Nuget.exe pack -Version, ignores the version argument

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#5200]
NuGet.exe -pack -Version does not create the version that is passed as argument.

NuGet version (4.3.0):
\\nuget\nuget\Share\Drops\CI\NuGet.Client\dev\4045\artifacts\VS15\NuGet.exe

Comand used:
 NuGet.exe pack -Version 1.0.0+git 

Result:
The package created but the version is:
<version>1.0.0</version>

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!
[NBBMathLib.zip](https://github.com/NuGet/Home/files/987576/NBBMathLib.zip)

**Comment by rohit21agrawal** [comment]
@cristinamanum just checked, it is +git part and not actually ignoring the version argument. this is being tracked by https://github.com/NuGet/Home/issues/5197
