### ISSUE TITLE
nuget.exe Update doesn't work with wix projects

### ISSUE THREAD

**Issue by antkon** [NuGet/Home#521]
Updating a wix project is only possible through the IDE. The command line tool won't work. 
It always outputs this error message: 
Unable to locate project file for 'path to packages.config'

**Comment by davidfowl** [comment]
NuGet.exe update is a bit of a mess. It was only ever intended for CI scenarios when you wanted to test rolling updates against other packages. 

I have no idea how NuGet interacts with WiX projects today. What are you trying to do?

**Comment by antkon** [comment]
Yes, for CI scenarios. I want to update a nuget packages on every build.
I have a .targets file that is imported into .wixproj. Add support of .wixproj, plz.

(see https://nuget.codeplex.com/workitem/2573)

**Comment by pranavkm** [comment]
Merged PR in http://nuget.codeplex.com/SourceControl/changeset/9265e85b6e18acdb8b2a2c8a1b1d110428966514
