### ISSUE TITLE
NuGet incorrectly classifies UWP as .NET Standard 1.3 instead of .NET Standard 1.4

### ISSUE THREAD

**Issue by mqudsi** [NuGet/Home#5212]
I'm hoping that this is the right place to raise this issue, and apologize and beg direction if it isn't.

In [the official "release article" for .NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/), Microsoft includes a char wherein the compatibility of each .NET platform is charted against its implemented version of .NET Standard:

<img src="https://wpcf.neosmart.net/20170508165849/NET-Standard-support.png" />

According to that chart, UWP is a valid .NET Standard 1.4 target. However, the NuGet package manager module shipping in Visual Studio 2017 incorrectly considers UWP 10.0 to be a .NET Standard *1.3* target, which means it refuses to install any packages built against .NET Standard 1.4 (though they *can* be manually referenced/installed without changing a thing in the project settings, so it is a NuGet/PM issue and not a VS2017 issue).

For example, our project [Unicode.net](https://github.com/neosmart/unicode.net) has been published on NuGet as [version 0.1](https://www.nuget.org/packages/Unicode.net/0.1.0), built against .NET Standard 1.4 (amongst others), and [as version 0.1.1](https://www.nuget.org/packages/Unicode.net/0.1.1), built against .NET Standard 1.3, (amongst others).

Attempting to install version 0.1 (.NET Standard 1.4) in a modified VS2017 project (that's another bug, see #5213) targeting UWP10, results in the following:

    PM> Install-package Unicode.net -version 0.1.0
      GET https://api.nuget.org/v3/registration1-gz/unicode.net/index.json
      OK https://api.nuget.org/v3/registration1-gz/unicode.net/index.json 46ms
    Restoring packages for C:\Users\Mahmoud\git\AsyncLock\AsyncLock\AsyncLock.csproj...
    Install-package : Package Unicode.net 0.1.0 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Unicode.net 0.1.0 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net30 (.NETFramework,Version=v3.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
      - net45 (.NETFramework,Version=v4.5)
      - netstandard1.4 (.NETStandard,Version=v1.4)
    At line:1 char:1
    + Install-package Unicode.net -version 0.1.0
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
     

But version 0.1.1 (.NET Standard 1.3) installs just fine:
    PM> Install-Package Unicode.net -version 0.1.1
      GET https://api.nuget.org/v3/registration1-gz/unicode.net/index.json
      OK https://api.nuget.org/v3/registration1-gz/unicode.net/index.json 37ms
    Restoring packages for C:\Users\Mahmoud\git\AsyncLock\AsyncLock\AsyncLock.csproj...
    Installing NuGet package Unicode.net 0.1.1.
    Committing restore...
    Writing lock file to disk. Path: C:\Users\Mahmoud\git\AsyncLock\AsyncLock\obj\project.assets.json
    Restore completed in 105.93 ms for C:\Users\Mahmoud\git\AsyncLock\AsyncLock\AsyncLock.csproj.
    Successfully installed 'Unicode.net 0.1.1' to AsyncLock
    Restoring packages for C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\project.json...
    Committing restore...
    Lock file has not changed. Skipping lock file write. Path: C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\project.lock.json
    Restore completed in 1.48 sec for C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\WinMessageUwp.csproj.
    Executing nuget actions took 1.85 sec
    Time Elapsed: 00:00:02.0272786

As far as I can tell, this is a bug and NuGet/PM needs to be updated to treat UWP10.0 targets as valid .NET Standard 1.4 targets.

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
