### ISSUE TITLE
NuGet/PM parsing "UAP10" or "UAP10.0" as "10.0.0.0", complaining it is less than "10.0.1024.0" which is the actual minimum

### ISSUE THREAD

**Issue by mqudsi** [NuGet/Home#5213]
Once again, I'm hoping that this is the right place to raise this issue, and apologize and beg direction if it isn't.

Visual Studio 2017 projects (and previous versions, for what its worth) targeting UWP are created including the following in the `.csproj`:

    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.15063.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.1024.0</TargetPlatformMinVersion>

There is no `TargetPlatformMinVersion` below `10.0.1024.0` because that's the RTM release of Windows 10.

Attempting to install a NuGet package via the Package Manager for such a project results in the following error:

	Install-Package : Project WebAllowedObjects is not compatible with uap10.0 (UAP,Version=v10.0). Project WebAllowedObjects supports: uap10.0.1024 (UAP,Version=v10.0.1024)
	At line:1 char:1
	+ Install-Package Unicode.net
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
	    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
	 
	Install-Package : One or more projects are incompatible with UAP,Version=v10.0.
	At line:1 char:1
	+ Install-Package Unicode.net
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
	    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
	 

It seems that NuGet/PM is doing a direct comparison between the latter part of "UAP10" and the `TargetPlatformMinVersion`, and erroring out because the interpreted version `10.0.0.0` derived from "UAP10.0" is less than the `TargetPlatformMinVersion` of `10.0.1024.0`.

Manually editing the `csproj` file and changing  `TargetPlatformMinVersion`  to the following:

    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.15063.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.0.0</TargetPlatformMinVersion>

Causes the Package Manager installation to succeed:

	PM> Install-Package Unicode.net
	  GET https://api.nuget.org/v3/registration1-gz/unicode.net/index.json
	  OK https://api.nuget.org/v3/registration1-gz/unicode.net/index.json 16ms
	Restoring packages for C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\project.json...
	Committing restore...
	Writing lock file to disk. Path: C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\project.lock.json
	Restore completed in 1.48 sec for C:\Users\Mahmoud\git\WinMessage\WinMessageUwp\WinMessageUwp.csproj.
	Successfully installed 'Unicode.net 0.1.1' to WinMessageUwp
	Executing nuget actions took 1.03 sec
	Time Elapsed: 00:00:02.9321985
	PM> 

I'm not sure *why* NuGet is trying to do a version comparison at all, let alone between build/revision fields of the expanded version string. UAP10 is an alias for UAP10.0, which should just be mapped to its supported .NET Standard version (1.4, per #5212), and that should be used to determine whether or not a package is supported.

If NuGet/PM is determined to use version comparison, the partial version number "10.0" derived from the "UAP10.0" alias for "UAP10" (which, in turn, is an alias for "UWP") should be interpreted as "10.0.\*.\*" and **not** as a hard "10.0.0.0" which would fall under the project's `TargetPlatformMinVersion` value.

**Comment by emgarten** [comment]
@mqudsi does your project contain a ``project.json`` file? Does WebAllowedObjects contain ``PackageReference`` items in the csproj?

**Comment by mqudsi** [comment]
@emgarten no and no.

**Comment by mqudsi** [comment]
I updated a typo in the original comment (blrgh markdown):

> If NuGet/PM is determined to use version comparison, the partial version number "10.0" derived from the "UAP10.0" alias for "UAP10" (which, in turn, is an alias for "UWP") should be interpreted as "10.0.*.*" and **not** as a hard "10.0.0.0" which would fall under the project's `TargetPlatformMinVersion` value.

should be

> If NuGet/PM is determined to use version comparison, the partial version number "10.0" derived from the "UAP10.0" alias for "UAP10" (which, in turn, is an alias for "UWP") should be interpreted as "10.0.\*.\*" and **not** as a hard "10.0.0.0" which would fall under the project's `TargetPlatformMinVersion` value.

**Comment by xavier-rigau** [comment]
I believe is the same as [https://forums.xamarin.com/discussion/101603/issues-producing-a-nuget-package-that-targets-uwp](url)

**Comment by xavier-rigau** [comment]
The suggested workaround didn't work for me. VS 2017 15.3.4 with Nuget 4.3.1

This is the error I was getting

> Restoring packages for C:\Users\Xavier\Documents\Visual Studio 2017\Projects\App1\App1\App1.csproj...
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586). Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-arm. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-arm-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x64. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x64-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x86. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x86-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package restore failed. Rolling back package changes for 'App1'.
> Time Elapsed: 00:00:01.1944625
> ========== Finished ==========

Manually editing the csproj file and changing TargetPlatformMinVersion to the following:

```
<TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
<TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">10.0.15063.0</TargetPlatformVersion>
<TargetPlatformMinVersion>10.0.0.0</TargetPlatformMinVersion>
```
Gives me this error which doesn’t make any sense.

> Restoring packages for C:\Users\Xavier\Documents\Visual Studio 2017\Projects\App1\App1\App1.csproj...
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0). Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0 (UAP,Version=v10.0)
> Package restore failed. Rolling back package changes for 'App1'.
> Time Elapsed: 00:00:01.2434439
> ========== Finished ==========
> 

Then I decided to try **change the package to UAP10.0.10240**:

And got this error:

> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240). Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-arm. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-arm-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x64. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x64-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x86. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package HP.Pdsmq.Xamarin.2015 1.0.0.1 is not compatible with uap10.0.10240 (UAP,Version=v10.0.10240) / win10-x86-aot. Package HP.Pdsmq.Xamarin.2015 1.0.0.1 supports: uap10.0.10240 (UAP,Version=v10.0.10240)
> Package restore failed. Rolling back package changes for 'App1'.
> Time Elapsed: 00:00:15.6177723
> ========== Finished ==========
>

**Comment by shirazLavi** [comment]
The workaround worked for me.
But will it affect other things that I should know of? is there any other way?

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
