### ISSUE TITLE
VS 2017 MSBuild.exe pack command produces bad .netstandard 1.6 packages

### ISSUE THREAD

**Issue by jseely** [NuGet/Home#5217]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): msbuild.exe

msbuild version (x.x.x.xxx): 15.3.118.39484

VS version (if appropriate): VS 2017 Update 2 RTM

OS version (i.e. win10 v1607 (14393.321)): Win10 15063.296

## Detailed repro steps so we can see the same problem

1. use MSBuild.exe to create a nuget package (`msbuild.exe /t:pack`) for a .netstandard 1.6 library

2. Try to add package to .netcoreapp 1.1 project

3. Add fails due to incompatible version

## Other suggested things

I was talking to @eerhardt, it appears the package gets created without the `lib\netstandard1.6` directory.

### Verbose Logs

https://gist.github.com/jseely/afaea3383b3c0a8e56c419f8c30d81e0

**Comment by rohit21agrawal** [comment]
can you attach or show the contents of the package?

**Comment by jseely** [comment]
These are the contents of the package
```
.                                                          
├── [Content_Types].xml                                    
├── E2EStandard.Logging.nuspec                             
├── lib                                                    
│   ├── E2EStandard.Logging.dll                            
│   └── netstandard1.6                                     
│       └── E2EStandard.Logging.pdb                        
├── package                                                
│   └── services                                           
│       └── metadata                                       
│           └── core-properties                            
│               └── 6c823090ee5f401e8803b4026d188c3d.psmdcp
└── _rels                                                  
```

**Comment by rohit21agrawal** [comment]
Dll is not in your framework directory. Can you've attach your csproj and the exact command you used to pack?

**Comment by jseely** [comment]
I used `msbuild.exe /t:pack /p:Configuration=Release /p:IncludeSymbols=true`

My csproj is:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Version>1.0.6340.20990</Version>
    <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CoreCompat.System.Configuration" Version="4.2.3-r4" />
    <PackageReference Include="Microsoft.Azure.EventHubs" Version="1.0.1" />
    <PackageReference Include="Serilog" Version="2.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="5.1.0" />
    <PackageReference Include="Serilog.Sinks.PeriodicBatching" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Trace" Version="2.1.0" />
    <PackageReference Include="System.Collections.Immutable" Version="1.3.1" />
    <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
  </ItemGroup>
</Project>
```

**Comment by jseely** [comment]
Can't repro the issue anymore, closing the issue.

**Comment by jseely** [comment]
I was able to repro it again the with following steps:
1. Create a new `.net core` or `.net standard` project in VS 2017 Update 2 RTM
2. Use `msbuild.exe` that comes with VS 2017 Update 2 RTM to create a nuget package for that project (`msbuild.exe /t:pack /p:Configuration=Release /p:IncludeSymbols=true`)
3. Package contains `lib` directory with DLL directly placed there (should be in `lib/<framework>`)

**Comment by rohit21agrawal** [comment]
@jseely  i can't repro this VS2017 update 2 RTM. i tried this on the attached project, and the resultant nupkg is in the bin dir of the project. 
[pack5217.zip](https://github.com/NuGet/Home/files/994760/pack5217.zip)

**Comment by jseely** [comment]
@rohit21agrawal back to not being able to repro this myself. It's weird, I managed to repro it two or three times in a row when I reopened but now it's working correctly... There must be something else interfering, I'll close the Issue for now but if I can get a more consistent repro, I'll reopen.
