### ISSUE TITLE
15.3 Preview's in-VS package restore fails where command line restore succeeds

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5221]
dotnet.exe --version (if appropriate): 2.0.0-preview1-005842
VS version (if appropriate):  d15rel 26510.00

Worked before? If so, with which NuGet version: I believe it worked fine in VS 15.1 and probably 15.2.

## Detailed repro steps so we can see the same problem

```
git clone https://github.com/microsoft/vs-threading
cd vs-threading\src
msbuild /t:restore
msbuild
```

Build succeeds.

But it fails in Visual Studio:

1. Open the solution Visual Studio 15.3 Preview.
1. Build. (Visual Studio executes package restore before build starts, and screws up the restore artifacts)

**Build fails.**

In particular, the failure is in the Microsoft.VisualStudio.Threading project's portable-net45+win8+wpa81 TFM. The other two TFMs (net45 and netstandard1.1) build just fine.

**Comment by AArnott** [comment]
My workaround for now will be to disable automatic package restore in VS and restore from the command line. It's the same workaround I've used for much of VS2015, sadly. I hope this in-VS package restore experience can be made as reliable as the command line one soon.

**Comment by mishra14** [comment]
@AArnott Are you still running into this issue with 15.5 Preview 4?

**Comment by AArnott** [comment]
No repro with 15.5 Preview 4.
