### ISSUE TITLE
Failed to add NuGet from the UI when <AssemblyName> is not fixed. 

### ISSUE THREAD

**Issue by magol** [NuGet/Home#5222]
## Details about Problem

NuGet product used: VS UI

dotnet.exe --version (if appropriate): 1.0.4

VS version (if appropriate): 15.2 (26430.4)

OS version (i.e. win10 v1607 (14393.321)): Microsoft Windows [Version 6.1.7601]

## Detailed repro steps so we can see the same problem

1. Create a new project of type "Class Library (.NET Standard)"

2. In the "Solutution Explorer", right click on the project and select "Edit ClassLibrary1.csproj".

3. Update the project file to this:
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net4.5;net4.6</TargetFrameworks>
    <AssemblyName>$(MSBuildProjectName).$(TargetFramework)</AssemblyName>
  </PropertyGroup>
</Project>
```
4. Save the changes and reload the project.

5. In "Solution Explorer", right click on the project and select "Manage NuGet packages...".

6. Try to add a NuGet package.

**Expected behavior:**
The NuGet package is added.

**Actual behavior:**
Following error message is written in the Output window:

`The operation failed as details for project ClassLibrary1 could not be loaded.`

**Comment by mishra14** [comment]
@magol I think the problem is that you are using `$(TargetFramework)` in the `AssemblyName` property. But that is never defined, since you define `$(TargetFrameworks)`.

**Comment by magol** [comment]
But the output assembly is named ClassLibrary1.net4.5.dll and ClassLibrary1.net4.6.dll as expected.  So obvious $(TargetFramework) is working.

**Comment by mishra14** [comment]
@magol Your thought is right. But that is done internally by msbuild. It reads '$(TargetFrameworks)' and then internally oops through it.

**Comment by magol** [comment]
Ok, i can accept that explantation. But what is the correct solution if i want the output binary to have the target framework in the name?
