### ISSUE TITLE
Doesn't support packaging pre-release deps as rtm release

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5228]
_From @haf on May 14, 2017 14:43_

Given: Proj A-v1.0, dep B-v1.0-beta1.

Then: A cannot be packaged as a nuget with `dotnet pack` despite being v1.0.

Expected: to be packed.

_Copied from original issue: dotnet/cli#6593_

**Comment by anangaur** [comment]
IMO, a functionality from a pre-release (potentially unstable code base) makes the parent code-base unstable. So a package should not be a release/stable package if it has a dependency on a beta/pre-release package. Looks like right behavior to me.

**Comment by mishra14** [comment]
dupe of https://github.com/NuGet/Home/issues/1365  which has been fixed.
