### ISSUE TITLE
Intermittent connectivity issues from AppVeyor build environment

### ISSUE THREAD

**Issue by FeodorFitsner** [NuGet/Home#5229]
Hi guys,

Starting from last Thursday, May 11 we started seeing a lot of timeouts while restoring NuGet packages on build worker VMs in our primary environment. The environment is located in Rackspace DFW3 data center, San Antonio, TX. We are not experiencing the issues on VMs running in Google Compute Engine cloud. 

Could it be that requests from our environment are being throttled/dropped somehow (it uses a single outgoing IP address)? Could it be related to [recent issues in NuGet's CDN provider](https://status.verizondigitalmedia.com/#network-status)? Do you see dropped requests on your side coming from our IP?

Any help with this ongoing issue is highly appreciated!

**Comment by alpaix** [comment]
@FeodorFitsner Sorry for the late response. I forwarded your complain to the NuGet server team.

**Comment by FeodorFitsner** [comment]
Thank you!

**Comment by alpaix** [comment]
Duplicate to NuGet/NuGetGallery#3961.
