### ISSUE TITLE
VS2017 can't open package manager console

### ISSUE THREAD

**Issue by bryanjhogan** [NuGet/Home#5230]
I get the below error when opening the package manager console. 

I am using VS2017 15.2 26430.4.
Nuget package manager 4.2.0.
 
![image](https://cloud.githubusercontent.com/assets/5768871/26072473/a03fddd8-3979-11e7-8d1e-a967dad542c8.png)

**Comment by bryanjhogan** [comment]
Just updated to VS2016 15.2 26430.6 and now I get a different error. 

![image](https://cloud.githubusercontent.com/assets/5768871/26073846/f5e41372-397d-11e7-8a9d-7149014a8d6a.png)

**Comment by alpaix** [comment]
@bryanjhogan Will you be able to submit a feedback ticket via the Visual Studio Report-a-Problem tool at the top right corner? It provides a method of recording steps and more info for us to investigate the issue.

**Comment by bryanjhogan** [comment]
@alpaix What information will be public? 

Title
Body
Screenshots
Recorded data/video
Logs
etc

**Comment by alpaix** [comment]
Information you provided will be public on the [Developer Community](https://developercommunity.visualstudio.com/) web site, including Title, Description, and Discussions.

Attachments if any, and diagnostics data will be available to Microsoft engineering stuff only.

For more details please refer to [Microsoft Enterprise and Developer Privacy Statement](https://www.microsoft.com/en-us/privacystatement/enterprisedev).

**Comment by mishra14** [comment]
This does not repro with 15.4.2.

```
Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 4.4.0.4475

Type 'get-help NuGet' to see all available NuGet commands.

PM> get-help NuGet
TOPIC
    about_NuGet
    
SHORT DESCRIPTION
    Provides information about NuGet Package Manager commands.
           
LONG DESCRIPTION
    This topic describes the NuGet Package Manager commands. NuGet is an integrated package 
    management tool for adding libraries and tools to .NET projects.
```
