### ISSUE TITLE
Unnecessary warning when floating version (e.g. "8.*") used  

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5231]
When I use the following
`<PackageReference Include="Newtonsoft.Json" Version="8.*" />`
I get warning that's unnecessary:
![image](https://cloud.githubusercontent.com/assets/14800916/26072638/0d9fb9ac-3961-11e7-8481-9d3bb2af323c.png)

However, when I use another way to define floating version:
`<PackageReference Include="Newtonsoft.Json" Version="[8.0.3,9.0.0)" />`
there is no such warning.

**Expected:** No warning.

VS version:
![image](https://cloud.githubusercontent.com/assets/14800916/26072717/644afe6a-3961-11e7-8d50-6179c4df6189.png)

**Comment by alpaix** [comment]
@emgarten @mishra14 Will your errors improvement work address this issue?

**Comment by emgarten** [comment]
@anangaur are you able to get that error from restore, or does this only happen in VS?

I don't think NuGet writes out this message, it looks like it could come from the additional diagnostics done by build to recreate warnings/errors that restore would have displayed.

Now that restore will write the warnings/errors to the assets file there shouldn't be any need for those additional diagnostics.

**Comment by anangaur** [comment]
@emgarten Currently i see this only in VS. Is https://github.com/NuGet/Home/issues/4895 the correct issue you are tracking for the errors/warnings feature?

**Comment by anangaur** [comment]
This issue seems to have been fixed.

**Comment by mishra14** [comment]
@anangaur: should we close this issue then?

**Comment by anangaur** [comment]
Yes. Done :)
