### ISSUE TITLE
Nuget restore fails when uninstalling a package which is missing remotely

### ISSUE THREAD

**Issue by spotlesscoder** [NuGet/Home#5236]
## Details about Problem

NuGet product used: VS UI

NuGet version 3.4.4.1321

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2015 Update 3

OS version (i.e. win10 v1607 (14393.321)): 

Worked before?: No

## Detailed repro steps so we can see the same problem

1. Create solution with C# project. Install a package prerelease e.g. A.B v1.6.0-unstable20 where 20 is the build number from the CI system

2. Check in the source code with nuget packages config

3. Prerelease packages are changed to only have the latest unstable version, not all CI builds (so unstable20 is deleted and only v1.6.0-unstable is available)

4. Checkout source code somewhere else to make sure the old "unstable20" package is not present

5. Open the solution. Try to uninstall the package v1.6.0-unstable20 via VS UI with the red "X" next to the version number in the packages list for the project (right click on project in solution explorer -> "Manage NuGet Packages"). Nuget tries to restore the package when clicking the red "X". Restore fails because package v1.6.0-unstable20 is missing. The package is not uninstalled.

It should not restore when uninstalling something. It should just remove the entries from the project and the packages.config file.

At least it should be configureable to not try to restore packages when uninstalling.

Thanks already!

**Comment by StingyJack** [comment]
This also happens in VS 2017, even with "force" options selected.

**Comment by JackGrinningCat** [comment]
I had the same problem with a package that I had on a debug package folder and removed by me, because I got the dependencies wrong, and just deleted it.
So I guess it is necessary to have the package to compare the content. Force should always work. 

Basically it's the duty from the developer/package provider to avoid such situation.

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.

**Comment by StingyJack** [comment]
@mishra14  - Did it get fixed it in 2017 then?
