### ISSUE TITLE
Need info on knowing the nuget package installed location

### ISSUE THREAD

**Issue by PrashanthIBM** [NuGet/Home#5237]
Hi , 

I am creating a package and i have put the <package_id>.targets file in the package/build directory.

Package creation is successful.

The projects which consume my package  need to copy some of the content files from the package installed location to application bin directory during build time. I wanted to achieve this using the .targets file but here is my problem : 

1) Nuget package installed location is user dependent and can be set to any location. So how can i get installed location info and put that  in targets file ?

2) I need this info for supporting .Net Core projects(both using project.json and csproj ) .
So can you please let me know how can i solve this .

Some of the findings i came to know are : 
a) Globalpackagefolder
b) RepositoryPath
c) NUGET_PACKAGES

what is the hierarchy and how can i get the value of these variables in .targets ?

Sample Targets file : 
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
     <None Include="<user_specified_nuget_location>\<packages_name>\contentfiles\**">
      <Link>contentfiles\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):  

NuGet version (x.x.x.xxx): 4.2.0 / 3

dotnet.exe --version (if appropriate): 1.0.4

VS version (if appropriate): 2015 / 2017

OS version (i.e. win10 v1607 (14393.321)): win 2008 R2 

Thanks and Regards,
Prashanth.

**Comment by emgarten** [comment]
@PrashanthIBM take a look at ``obj\projectName.csproj.nuget.g.props`` in your project.

You should see all package folders used in the property: ``NuGetPackageFolders`` which covers *a* and *c* in your list.

For packages.config projects there currently isn't a way to get the ``repositorypath`` without reading nuget.config or finding the solution file.

**Comment by PrashanthIBM** [comment]
@emgarten : ya i had seen that but have few questions on that. 

1) All projects which are based on the new csproj will have the obj\projectName.csproj.nuget.g.props . 
So in  .targets file, if i use this variable NuGetPackageFolders  as it is , will it work ? 

sample : 
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
     <None Include="**$NuGetPackageFolders**\<packages_name>\contentfiles\**">
      <Link>contentfiles\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```
2) what will be the value of **NuGetPackageFolders**  ? will it be always pointing to %userprofile%/.nuget/packages folder or  will it be based on what end user has set as package install location ?

3) Projects containing project.json , how can we support them ? . 

4) For .Net Core projects, what are the possible ways end user can set the package install location ?
do we have document link ?

**Comment by PrashanthIBM** [comment]
@emgarten  : any info on the questions i have asked ?

**Comment by emgarten** [comment]
> All projects which are based on the new csproj will have the obj\projectName.csproj.nuget.g.props .
So in .targets file, if i use this variable NuGetPackageFolders as it is , will it work ?

yes

> what will be the value of NuGetPackageFolders ? will it be always pointing to %userprofile%/.nuget/packages folder or will it be based on what end user has set as package install location ?

It will be the location set by the user, the value matches where the packages were installed or read from.

> Projects containing project.json , how can we support them ?

project.json projects will not always write out the props, you will need to read *project.lock.json* and check the *packagesFolder* property to get the same list.

> For .Net Core projects, what are the possible ways end user can set the package install location ?
do we have document link ?

NuGet.Config, NUGET_PACKAGES env var, various command line parameters.

**Comment by PrashanthIBM** [comment]
Hi , 

Thanks a lot for the inputs. 

i am not able to see packagesFolder property in project.lock.json.  Can you please tell me how to get it ?

Also is the project.json project still supported  ? 

Thanks,
Prashanth.

**Comment by emgarten** [comment]
project.json is still used for UWP, but it is no longer used for NETCore projects.

If the packages folder path is not listed in project.lock.json then you can check:
1. NUGET_PACKAGES env var which overrides the default
1. Use the default location of ``%USERPROFILE%/.nuget/packages``

**Comment by PrashanthIBM** [comment]
Thanks a lot for answering all the questions. 

Will close the issue.

**Comment by bjorn-ali-goransson** [comment]
This actually works, packaging the following my-nuget-package-id.targets inside build\ :

    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <ItemGroup>
        <None Include="$(NuGetPackageFolders)\Admin\1.0.10\content\admin.tar">
          <Link>admin.tar</Link>
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
      </ItemGroup>
    </Project>

Two questions. There's no way of getting the version here, right? I guess there's not because the consuming project is executing this at its own scope ... No variable containing this packages version will be there.

And, this .targets file is only used when directly referencing the package, not if I package it in another package. Then it won't be used by a project using that package. I think I confirmed this by checking the respective .props files.

Any workaround for that, you think?

**Comment by bjorn-ali-goransson** [comment]
As of .NET Core 2, I think, this does not work anymore. The offending code is the one above mentioned. When commenting it out, building works.

    1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4406,5): error MSB3025: The source file "C:\Users\Bjorn\.nuget\packages\" is actually a directory.  The "Copy" task does not support copying directories.
    1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4406,5): error MSB3030: Could not copy the file "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\Admin\1.0.10\content\admin.tar" because it was not found.

@emgarten Do you have any input?

**Comment by bjorn-ali-goransson** [comment]
When looking at the .props file in obj, the following appears:

    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Bjorn\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>

Maybe the reason for failure is the extra backslash?...

**Comment by bjorn-ali-goransson** [comment]
https://github.com/dotnet/sdk/issues/1250#issuecomment-303791974

**Comment by bjorn-ali-goransson** [comment]
Sorry for spamming this one, but it works again by changing NuGetPackageFolders to NuGetPackageRoot. Will create separate issue for this.
