### ISSUE TITLE
Don't restore in the IDE if everything is already restored

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#5239]
After running a very long `build.cmd` that fully restores, builds and run tests before opening visual studio, after opening a solution file the IDE proceeds to run restore again which can take a long time for a big project.

Not only that but if I close and reopen the solution after all of that, it proceeds to restore again. It seems like we blindly restore on open.

**Comment by emgarten** [comment]
@nkolev92 is fixing this for 15.3. 

Restore will hash all inputs and persist it to the obj folder, both VS and the command line will use this.
https://github.com/NuGet/Home/issues/5183

**Comment by nkolev92** [comment]
The no-op restore work went in starting with d15prerel-26609.0.
It was also inserted into the CLI/SDK on the 8th as well. CLI builds from 9th June and later have this change.

**Comment by davidfowl** [comment]
I just installed 15.3 preview 3 and it still does a restore on project open:
```
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project SampleApp could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.AspNetCore.Http.Tests could not be loaded.
Error occurred while restoring NuGet packages: The operation failed as details for project Microsoft.AspNetCore.Authentication.Core could not be loaded.
Restoring NuGet packages...
Time Elapsed: 00:00:00.8443961
========== Finished ==========
```

**Comment by nkolev92** [comment]
@davidfowl There are still some inconsistencies among the restore behavior between the commandline clients and VS for some project types. 
Tracked here:
https://github.com/NuGet/Home/issues/5444
& 
https://github.com/NuGet/Home/issues/5452

Which project type do you have?
Which client does the build.cmd restore call? What version are the exact versions of both the command line client and VS?

The SDK based Package Reference inconsistency is fixed, but there some caveats based on which commandline tool you're using.
