### ISSUE TITLE
NuGet.Core package ID uses different casing to the Nuget.Core package listing

### ISSUE THREAD

**Issue by urbas** [NuGet/Home#524]
This breaks on case-sensitive file systems.

For example, NuGet installs the package into `Nuget.Core.2.8.5/lib/...` but when resolving the path through the correct package ID `NuGet.Core`, the file is not found.

Suggested resolution:
- rename the package ID in the NuGet page listing (from `Nuget.Core` to `NuGet.Core`)
- rename the package ID in the nuspec (from `NuGet.Core` to `Nuget.Core`)

Here's an example of how it goes wrong in the code:

```csharp
// The following returns a package with the ID "Nuget.Core"
var foundPackage = packageManager.SourceRepository.FindPackage("NuGet.Core", "2.8.5", false, false);
packageManager.InstallPackage(foundPackage, false, false);
// The following returns a package with the ID "NuGet.Core"
foundPackage = packageManager.LocalRepository.FindPackage("NuGet.Core", "2.8.5", false, false);
```

Expected behaviour:
- both local repository and source repository must return the package with the same casing of the package ID

**Comment by deepakaravindr** [comment]
We will fix it for 2.8.6

**Comment by bhuvak** [comment]
The casing seems to be fine in the actual package - NuGet.Core 2.8.5.This works properly in NuGet 3.0 client ( both against v2 and v3 sources). With 2.8.6, it works from commandline. The issue happens while installing from UI (package manager console and dialog). The fix is to take the package Id from the nuspec while creating the local folder ( instead of picking up the value returned by the server).

**Comment by rohit21agrawal** [comment]
@urbas Are you still facing this issue? Page listing seems to have been updated with the correct casing and package id seems to be consistent for local and package repository for NuGet.Core 

If you are still facing the issue, please let me know the version of VS and NuGet that you are using.

**Comment by urbas** [comment]
Great, I'm not facing the issue anymore. Thanks a bunch!
