### ISSUE TITLE
nuget.exe update does not read projects from solution file

### ISSUE THREAD

**Issue by polyzois** [NuGet/Home#5241]
Compare https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/UpdateCommand.cs#L111

with https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/RestoreCommand.cs#L806

nuget cli update command does not parse solution file to find affected projects. It will only look at directory of solution and recursively search that directory and below. I would have expected update to work as restore. Restore parses solution file to find all projects and then restore each. 

    nuget.exe update my.sln 

    mysol (directory)
      my.sln
    myproj (directory same level as 'mysol' above)
     myproj.csproj
     packages.config

Above layout will not work with update but will work with restore.

**Comment by chm-tm** [comment]
I worked around using [this gist to retrieve projects from sln in MSBuild](https://gist.github.com/jrkd/4b60d1cca342ef9b69f37c9bba3a1977).

**Comment by vdachev** [comment]
In addition, the `UpdateCommand` does not look for a "packages.**ProjectName**.config" file in the project folder.

**Comment by nkolev92** [comment]
Thanks for this issue @polyzois. 

I am closing this in favor of https://github.com/NuGet/Home/issues/6166, despite the other being longer, since it contains more context. 

@vdachev thanks for the heads up.

**Comment by anirudhbagri** [comment]
Facing the same issue...any update on this?
