### ISSUE TITLE
Devenv.exe.config needs binding redirect for NuGet.Frameworks 4.3 in Update 3

### ISSUE THREAD

**Issue by adrianvmsft** [NuGet/Home#5242]
## Details about Problem
The version of Nuget.Frameworks.dll that gets shipped with Visual Studio 2017 Update 3 was increased to 4.3.
However, devenv.exe.config doesn't have a binding redirect to the new version.
That casues extensions built against the old version (4.0) to stop working after installing Update 3 - backward compatibility issue.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.Frameworks.dll

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate): Visual Studio 2017 Update 3

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. On a build of Visual Studio 2017 Update 3
2. Build and run this extension: https://github.com/dotnet/projfiletools
3. Attach a debugger to the vs instance with the extension installed
4. Open a project file (.csproj) in the Visual Studio editor
5. Inside an <ItemGroup> tag - start typing
<PackageReference Include="Microsoft.VisualStudio.
Expected: to work just fine
Error: exception get caught in the debugger as NuGet.Frameworks.dll 4.0 could not be loaded

## Other suggested things
There may be additional similar nuget related dlls that need to have binding redirects

### Sample Project
https://github.com/dotnet/projfiletools

**Comment by rrelyea** [comment]
recommendation is to use IVSFramworkParser or similar via NuGet's extension APIs via MEF.
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility/IVsFrameworkParser.cs

We do not support VS components calling their own versions of our NuGet assemblies.
