### ISSUE TITLE
dist.nuget.org nightly build of NuGet.CommandLine links to a weird build

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#5243]
https://dist.nuget.org/
![image](https://cloud.githubusercontent.com/assets/94054/26171008/4b52f492-3af8-11e7-8de8-de68c0c5bd61.png)

https://dotnet.myget.org/F/nuget-build/api/v2/package/NuGet.CommandLine

Actual package version: [4.3.0-xprivate-14](https://dotnetmyget.blob.core.windows.net/privatefeednuget0build/NuGet.CommandLine-4.3.0-xprivate-14?sv=2015-12-11&sr=b&sig=S%2BVWEsc8mxcj0nqxBp5J%2Fw7rRneH%2BG1GiJo9NMw66sg%3D&st=2017-05-17T17:55:00Z&se=2017-05-17T19:05:00Z&sp=r&rscc=max-age%3D3600&rsct=binary%2Foctet-stream&rscd=filename%3DNuGet.CommandLine.4.3.0-xprivate-14.nupkg)

We should probably remove this xprivate build.

**Comment by mishra14** [comment]
This is fixed to NuGet.CommandLine.4.6.0-preview1-4622.nupkg
