### ISSUE TITLE
PackageReferences not adding package sources to source control

### ISSUE THREAD

**Issue by burreld** [NuGet/Home#5244]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.1.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.1 (2017)

OS version (i.e. win10 v1607 (14393.321)): Windows 7

Worked before? If so, with which NuGet version: 4.1.0

## Detailed repro steps so we can see the same problem
1. disableSourceControlIntegration = false

2. Add a nuget package using the new reference type

3. Locate the Package folder.  It does not exist

...

## Other suggested things

We need to have an audit copy of the source and all of the dependent libraries.  We need the nuget packages to be added to the source control library.  

We also don't want the build machine loading nuget packages form the web.  We need the files to be included when the code is retrieved for  the build

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by burreld** [comment]
Is this not a problem for other users?  I just read about the hacked github accounts, using a common misspelled github url. 

The repository was modified with malicious code and then consumed by other developers.

I know adding the libraries to source control is not full proof, but it does allow for a single download instead of each developer in each environment to download copies of the libraries.

**Comment by mishra14** [comment]
@burreld if you are on PackageReference style of project then it is expected. If you are using a packages.config file then let us know.
