### ISSUE TITLE
Sync brush color resources with VS shell's EnvironmentColors

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#5245]
### Problem

NuGet vsix has implicit dependency of VS platform module `Microsoft.VisualStudio.ExtensionsExplorer.UI` which should be eliminated. As it happened earlier #5232 any change made by the platform team in this module may potentially break NuGet PM UI.

### Proposed solution

Replace referenced resources with our own based on `EnvironmentColors`.

**Comment by mishra14** [comment]
closing as dupe of internal issue: 497251
