### ISSUE TITLE
Can't restore NuGet packages from MSBuild

### ISSUE THREAD

**Issue by ArcanoxDragon** [NuGet/Home#5247]
I've encountered this problem twice in the last couple days. I'm trying to work with .NET Core projects (`project.json`), specifically AngleSharp and its libraries. When I try and build a project from Visual Studio 2017 or through a Cakefile, I get an error from NuGet stating something along the lines of:

`Invalid restore input. UAP projects must contain exactly one target framework. Input files: C:\Users\<me>\Projects\AngleSharp\src\AngleSharp\AngleSharp.Core.csproj, C:\Users\<me>\Projects\AngleSharp\src\AngleSharp\project.json.`

I can't find any instance of this error anywhere on the internet, which is really frustrating. If I manually run `nuget restore` in `Projects\AngleSharp\src\AngleSharp\`, it works fine and restores all packages properly. The only version of NuGet in my `PATH` is `4.1.0.2450`, which I just installed today. I can't figure out which version of NuGet is being run by MSBuild, but the MSBuild version that is being run is from Visual Studio 2017, which I just installed earlier this week, so it has to be a recent version of NuGet as well.

**Comment by emgarten** [comment]
@briman0094 since you are using VS 2017 consider moving from project.json to a NETCore SDK project that uses PackageReference.

From the error message it looks like you may have an invalid project.json file that contains multiple frameworks. Reduce it to a single framework, or move to NETCore SDK projects to get multiple framework support.

**Comment by ArcanoxDragon** [comment]
I'm trying to build a dependency from source, so it's not my project. I'm wondering if AngleSharp is possibly in-limbo between non-NETCore and NETCore and their build process isn't fully adapted yet. The solution file doesn't reference the NETCore project, but the `.cake` file does. Even when I remove references to NETCore in their `.cake` file, NuGet still tries to reference `project.json` when restoring, and throws the error in my original comment.

**Comment by alpaix** [comment]
@briman0094 From my observation the AngleSharp repo contains `.xproj` project file next to `project.json`. I presume their solution should be used with Visual Studio 2015 only as `.xproj` support has been deprecated in Visual Studio 2017. Please contact AngeSharp stuff for detailed instructions.

Closing the issue.
