### ISSUE TITLE
Support for NuGet settings in MSBuild projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5248]
Restore should allow setting sources, fallback folders, and the packages directory dynamically through MSBuild. This enable users to override and set these as needed for advanced builds and for the SDK to override settings based on the project type.

This needs to be done for nuget.exe, msbuild, dotnet, and VS.

https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-settings-in-MSBuild

**Comment by nkolev92** [comment]
Relevant to https://github.com/dotnet/project-system/issues/2225

**Comment by nkolev92** [comment]
In VS, we currently don't read these properties, they're directly overriden from the settings.
