### ISSUE TITLE
NuGet.exe update -self doesn't update past 3.5.0

### ISSUE THREAD

**Issue by cyanite** [NuGet/Home#5251]
As the title says. I am kind of puzzled that this hasn't been reported, and indeed fixed, already, since using that command is the only automatic way I know of to get the newest version.

Even with 4.0.0 installed it doesn't update to anything newer:

    $ nuget update -self
    Checking for updates from https://www.nuget.org/api/v2/.
    Currently running NuGet.exe 4.0.0.
    NuGet.exe is up to date.

No it's not, the current release version is 4.1.0, according to https://dist.nuget.org/index.html

**Comment by anangaur** [comment]
Thanks for reporting this issue. We marked NuGet 4.1.0 as the latest release just yesterday (though it was released sometime back) and seems like the transition is not yet done. I will follow up.

**Comment by emgarten** [comment]
@anangaur the command line package still needs to be pushed
https://www.nuget.org/packages/NuGet.CommandLine/

**Comment by anangaur** [comment]
Gotcha. Thanks @emgarten. @cyanite Stay tuned. We should be fixing this asap - probably early next week. Hope that works.

**Comment by cyanite** [comment]
@anangaur sounds good :)

**Comment by anangaur** [comment]
@cyanite - the issue should be fixed now. .

**Comment by cyanite** [comment]
It works. Great work, thanks!
