### ISSUE TITLE
NuGet pack - Unexpected token error with complex icon url

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#526]
Have a spec file with this url for the icon:
<iconUrl>http://download-codeplex.sec.s-msft.com/Download?ProjectName=vstnet&DownloadId=34897</iconUrl>

When trying to create a package it says:
'=' is an unexpected token. The expected token is ';'. Line 10, position 92.

Pos:92 is the second! '=' char. (after '&' ?)

Hope it helps,
Marc Jacobi

@obiwanjacobi, This is a duplicate of https://github.com/NuGet/NuGetGallery/issues/2304

**Comment by alpaix** [comment]
Doesn't sound like a bug to me. Nuspec file is in XML format therefore any raw text value should be properly encoded/escaped. 

I created a nuspec with the following string:

```
http://download-codeplex.sec.s-msft.com/Download?ProjectName=vstnet&amp;DownloadId=34897
```

And it worked!

Closing the issue.
