### ISSUE TITLE
NuGet restore via VS gives different warnings vs msbuild restore

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5261]
**Build:** Version 15.3.0-pre.1.0+26521.1.d15prerel

1. `git clone http://github.com/dotnet/project-system`
2. `cd project-system`
3. `git checkout 162e76d7626ef3e6369a6614a9084a607c30bd1e`
4. `build.cmd` -> which restores (notice no errors/warnings - bin\debug\logs\Restore.log for log)
5. Open src\ProjectSystem.sln
6. Wait for restore to finish

**Expected:** Command-Line and VS to have the same set of warnings/errors
**Actual:**

Command-line has no warnings
Visual Studio has the following warnings:

```
Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10 
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06) 
 DeployIntegrationDependencies (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)
Detected package downgrade: Microsoft.VisualStudio.LanguageServices from 2.3.0-beta2-61711-06 to 2.3.0-beta1-61703-10 
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.IntegrationTest.Utilities (>= 2.3.0-beta2-61711-06) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta2-61711-06) 
 Microsoft.VisualStudio.ProjectSystem.IntegrationTests (>= 1.0.0) -> Microsoft.VisualStudio.LanguageServices (>= 2.3.0-beta1-61703-10)
```

We have warnings as errors turned on, but command-line didn't catch the above issue - so this got merged in.

**Comment by davidfowl** [comment]
Are those all project references?

**Comment by davkean** [comment]
No, they are all package references.

**Comment by mishra14** [comment]
@davkean are you still facing this problem with VS 15.5 Preview 4?

**Comment by nkolev92** [comment]
My guess is dup of https://github.com/NuGet/Home/issues/9864, but we can take a look at customer sprint.

**Comment by nkolev92** [comment]
Confirmed dup of https://github.com/NuGet/Home/issues/9864. 

While that issue is newer, it contains *more* details, so closing this as a dup of that.
