### ISSUE TITLE
Nugetizer - Adding/building Nuget Package project fails

### ISSUE THREAD

**Issue by BryantL** [NuGet/Home#5263]
Adding a new Nuget Package project results in the following error message in Visual Studio:

*Package Installation Error*

*Could not add all the required packages to the project.  The following packages failed to install from [extension location path]\Packages:*
*NuGet.Build.Packaging.0.1.276 : The operation failed as details for project [projectname] could not be loaded.*

I've checked and the nuget package does exist in the indicated location.

Compiling results in the following error:

*Error occurred while restoring NuGet packages: The operation failed as details for project [projectname] could not be loaded.*

0.1.259 is the last version that worked successfully.  I've checked 0.1.267, 0.1.270 and 0.1.276.

Using VS 15.2 (26430.6)

**Comment by kzu** [comment]
Fixed by https://github.com/NuGet/NuGet.Build.Packaging/issues/124
