### ISSUE TITLE
dotnet restore failing in VSTS task

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5265]
_From @singharun1990 on May 22, 2017 18:9_

## Steps to reproduce
In VSTS Build definition we have a task  to restore one of the dotnet core project  before building it so that we are able to resolve all the dependencies and it fails with following error:
"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj -v diag
C:\Program Files\dotnet\sdk\1.0.3\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /m /t:Restore /v:m /verbosity:diag d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj
  Restoring packages for d:\a\1\s\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for d:\a\1\s\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.. [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]

We are using a custom package as well

getting same error from running dotnet restore locally as well

PS C:\Repos\UserDataStoreService\UserDataStoreService> dotnet restore .\UserDataStoreService.csproj
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
  Restoring packages for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj...
  Lock file has not changed. Skipping lock file write. Path: C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\obj\project.assets.json
  Lock file has not changed. Skipping lock file write. Path: C:\Repos\UserDataStoreService\UserDataStoreService.Core\obj\project.assets.json
  Restore completed in 1.28 sec for C:\Repos\UserDataStoreService\UserDataStoreService.Core\UserDataStoreService.Core.csproj.
  Restore completed in 1.28 sec for C:\Repos\UserDataStoreService\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj.
  Restore completed in 3.65 sec for C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj.
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.\r [C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\Repos\UserDataStoreService\UserDataStoreService\UserDataStoreService.csproj]

## Actual behavior
"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj -v diag
C:\Program Files\dotnet\sdk\1.0.3\MSBuild.dll /NoLogo /ConsoleLoggerParameters:Verbosity=Minimal /m /t:Restore /v:m /verbosity:diag d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj
  Restoring packages for d:\a\1\s\UserDataStoreService.Core\UserDataStoreService.Core.csproj...
  Restoring packages for d:\a\1\s\UserDataStoreService.Persistance\UserDataStoreService.Persistance.csproj...
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to load the service index for source https://microsoftxxxx.pkgs.visualstudio.com/_packaging/xxxxxxxxxxx.. [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [d:\a\1\s\UserDataStoreService\UserDataStoreService.csproj]

## Environment data
`dotnet --info` output:

_Copied from original issue: dotnet/cli#6659_

**Comment by dalestone** [comment]
Is there a work around for this? I am getting the same error when trying to restore packages.

I tried setting the permissions on feed to the following:
**Contributors**: Project Collection Build Service
**Readers**: Project Collection Valid Users

The error persists.

I am using the Hosted VS2017 Queue.

**Comment by Igorbek** [comment]
I've faced this issue as well, without any workaround found so far. Trying to access the feed via `dotnet restore` from a build that definitely has access.

**Comment by dalestone** [comment]
I manged to work around this by targeting VS2017 host agent and using nuget restore and pointing it at a nuget.config which has the VSTS feed URL in. I also left permissions to what i mentioned above and it now restores with no issues.
<img width="1059" alt="vsts" src="https://user-images.githubusercontent.com/3886432/27394519-6372100e-56a4-11e7-84a5-17b3bcde00ef.png">

**Comment by gforceg** [comment]
@dalestone, do you have tests? Are they working?
This was our work around until I noticed that nuget doesn't seem to care about DotNetCliToolReference tags in my project's solution. So 'dotnet xunit' fails because the command cannot be found.

**Comment by phil-hodgson** [comment]
Restoring NuGet packages for .NET Core projects is supported by VSTS build tasks. See https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/dotnet-core for details.

**Comment by nkolev92** [comment]
In 2.1.400 of the dotnet SDK support for a cross platform authentication plugin was added. 
https://github.com/NuGet/Home/issues/6486

The ADO's build tasks have since then been updated to use that plugin. 

I think all the concern raised in this thread should have already been addressed.
