### ISSUE TITLE
Nuget push fails with timeout for some packages - fixed in netcore CLI 2.0

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5267]
_From @rudolfdobias on May 22, 2017 23:16_

Hello, hope this is the right place where to put this issue..:
Have an package (https://www.nuget.org/packages/Firefly.net/1.2.1-alpha1) and it cannot be pushed to the nuget.org by any way from the command line.

## Steps to reproduce

```
dotnet nuget push -k xxx-s https://www.nuget.org/api/v2/package ..path to the/Firefly.net.1.2.1-alpha1.nupkg'
```

 - Tried desktop OSX / Ubuntu / Docker on Ubuntu - same behavior.
 - Tried myget, it does not work too.
 - Tried raise the timeout - nope
 - Tried to create new blank project and push it - it works.
 - (The package has about 40kbites)

## Expected  behavior

(package successfuly pushed)

## Actual behavior

```
info : Pushing Firefly.net.1.2.1-alpha1.nupkg to 'https://www.nuget.org/api/v2/package'...
info :   PUT https://www.nuget.org/api/v2/package/
info : An error was encountered when fetching 'PUT https://www.nuget.org/api/v2/package/'. The request will now be retried.
info : An error occurred while sending the request.
info :   Failure when receiving data from the peer
```

## Environment data
`dotnet --info` output:

Testing on OSX:
```
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

Testing on ubuntu:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```

Thanks

_Copied from original issue: dotnet/cli#6666_

**Comment by roelofb** [comment]
We see exactly the same errors on the same platforms, and also when building using the official ASP.NET Core build image https://hub.docker.com/r/microsoft/aspnetcore-build/

**Comment by neoeinstein** [comment]
Also have been experiencing this same issue, but we are pushing to a private MyGet feed. Setting logging to `Verbose` verbosity doesn't provide any additional information that looks useful.

**Comment by jamiegs** [comment]
I've also been seeing this behavior.. I tried doing a push with the same nuget package from a windows computer and it worked. so it seems to be an issue with the linux+mac implementation.

Update: I was seeing the issue in our build pipeline, to work around the issue I've switched to using nodeJS to push to nuget. https://www.npmjs.com/package/nuget-push   Not ideal, but we haven't had any problems with it since.

**Comment by stefandevo** [comment]
Same here! Push not working.
```
PUT https://www.nuget.org/api/v2/package/
An error was encountered when fetching 'PUT https://www.nuget.org/api/v2/package/'. The request will now be retried.
An error occurred while sending the request
  Error getting response stream (ReadDone1): ReceiveFailure
  Unable to read data from the transport connection: Connection reset by peer.
  Connection reset by peer
  PUT https://www.nuget.org/api/v2/package/
```

**Comment by tarurar** [comment]
Thу same issue. Time out during publishing version update. Any workaround here?

**Comment by anangaur** [comment]
cc: @rrelyea , @rohit21agrawal

**Comment by rrelyea** [comment]
Those of you who are seeing this issue, does this fail 100% of the time, with 100% of packages?
Sounds like folks have seen failures pushing to nuget.org and myget.
Has anybody tried dotnet sdk v2 bits? (that are very close to final release)

**Comment by tarurar** [comment]
For me it fails 100% of the time for particular package. Haven't tried v2.
By the way, I've finally found which change in code brakes the nugget push. You will be surprised. Here it is: https://github.com/LykkeCity/Lykke.Service.OperationsRepository/commit/a21a04511dd595a47b98ff64e62365809423df49.

Once I make this change, the package will never be published to nuget. If I remove the implementation for the method and leave `throw new NotImplementedException();` instead. It will be published successfully.

**Comment by rrelyea** [comment]
@tarurar  - have you only found 1 package that has problems? Have you tried pushing other packages?
That code change you point towards isn't in NuGet client or NuGet server ... so I have no clue how that could have broken push. Are you saying that if you build your library w/o that change, push works for the package with that library??? Please explain more.

**Comment by tarurar** [comment]
@rrelyea Yes, I have only 1 package with that problem. Other packages are being pushed successfully.
You are right, I am saying if I build my library w/o that change push works fine. Moreover, I've just discovered that issue is in changing method definition. If I add `async` to definition - it breaks the push.

**Comment by tarurar** [comment]
This code works fine. The package is being published successfully.
```csharp
public Task UpdateBlockChainHashAsync(string clientId, string recordId, string hash)
{
   throw new NotImplementedException();
}
```

This code breaks the publication:
```csharp
public async Task UpdateBlockChainHashAsync(string clientId, string recordId, string hash)
{
   throw new NotImplementedException();
}
```

The only difference is in adding `async` to method definition. That's it.

**Comment by rrelyea** [comment]
@tarurar - are you sure the package is getting built successfully? 
I would be very surprised if push was broken based on a code change in your DLL!!

**Comment by tarurar** [comment]
@rrelyea Yes, I'm pretty sure. I've already spent at least one day trying to find out the breaking change. Package is getting built successfully in both cases. But for second case (with `async` keyword) the publication always fails by timeout.

```
PUT https://www.nuget.org/api/v2/package/
[17:07:23][Step 6/7] info : An error was encountered when fetching 'PUT https://www.nuget.org/api/v2/package/'. The request will now be retried.
[17:07:23][Step 6/7] info : An error occurred while sending the request.
[17:07:23][Step 6/7] info :   Failure when receiving data from the peer
```

Just to clarify: I am using the same build script every time. Nothing changes except code.

**Comment by jamiegs** [comment]
I did quite a bit of troubleshooting on this issue 2 months ago.  What I found was I could take the same nuget package file, it would fail to push on mac and linux, but successfully push on windows.  I tried with both nexus and this simple nuget server https://hub.docker.com/r/sunside/simple-nuget-server/ to rule out a server issue, same results between the servers.

I used ngrep to view the network request differences between windows and linux.   I wish I would've kept the results but I do remember there being some differences in the headers being sent and the request contents.    One difference I remembered specifically was that keep-alive headers were being sent for one, but not the other.

We switched to using a nodejs library for the nuget push, and we haven't seen the issue since.  So it appears to be some implementation/behavioral difference between windows and linux versions of the nuget plugin for the dotnet cli.

**Comment by tarurar** [comment]
Here are the nugget packages:
1. Version 1.0.35. I am getting timeout error.
2. Version 1.0.37. Published successfully.

The only difference between them is as I mentioned here: https://github.com/NuGet/Home/issues/5267#issuecomment-319738912

[Lykke.Service.OperationsRepository.Client.1.0.35.zip](https://github.com/NuGet/Home/files/1195404/Lykke.Service.OperationsRepository.Client.1.0.35.zip)
[Lykke.Service.OperationsRepository.Client.1.0.37.zip](https://github.com/NuGet/Home/files/1195405/Lykke.Service.OperationsRepository.Client.1.0.37.zip)

**Comment by tarurar** [comment]
@rrelyea, It seems I found the issue. The point is the aforementioned example (https://github.com/NuGet/Home/issues/5267#issuecomment-319738912) adds 26th async method to the package. If I remove any of existing async methods and add this one, the total number of async methods will be 25 and the package will be published successfully.

Moreover, have a look at the screenshot. This method is not async but the implementation inside works with async methods. And this also breaks the publication if this method appeared to be 26th with async operations.
<img width="895" alt="screen shot 2017-08-03 at 12 01 20" src="https://user-images.githubusercontent.com/142044/28918784-08b96b58-784b-11e7-9b2a-37b5d9d9504b.png">

**Comment by jamiegs** [comment]
@rrelyea @tarurar I'm not sure if you guys saw my response above about differences on linux vs windows, but I'm wondering if it's actually an issue with size of payload rather than contents. Maybe adding the 26th async method just pushes it over the limit.

**Comment by tarurar** [comment]
@jamiegs Maybe. I've just realised, I have a lot of code in package generated with autorest. And it has a lot of async methods. So, at least it means the magic number is not 25 ))), but more.

**Comment by tarurar** [comment]
@rrelyea, @jamiegs Finally, it seems there are some limits for assemblies inside the package but not for the package itself. I moved out the autorest generated code to another Core assembly, added it as a dependency and the nuget package now is being published successfully.

This approach makes assemblies and amount of async and/or regular methods in each assembly lesser. I believe it is a key for investigation.

**Comment by zhili1208** [comment]
@tarurar I tried latest CLI to push Lykke.Service.OperationsRepository.Client.1.0.35.zip on Mac to nuget.org and myget. it works well. 

this issue might be already fixed in latest CLI.

Please verify that.
```
.NET Command Line Tools (2.1.0-preview1-007012)

Product Information:
 Version:            2.1.0-preview1-007012
 Commit SHA-1 hash:  b60272d64d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/nugetciagent/Downloads/dotnet/sdk/2.1.0-preview1-007012/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by zhili1208** [comment]
@tarurar Ping

**Comment by tarurar** [comment]
Unfortunately I can't verify that as we are using TeamCity for building and pushing our packages.

**Comment by zhili1208** [comment]
@jamiegs could you verify latest CLI in your scenario? Thanks

**Comment by jamiegs** [comment]
@zhili1208 yeah, I should have time to test it later today.

**Comment by zhili1208** [comment]
also tested CLI 2.0.1
```
.NET Command Line Tools (2.0.1-servicing-006924)

Product Information:
 Version:            2.0.1-servicing-006924
 Commit SHA-1 hash:  1ed6be56ca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/nugetciagent/Downloads/dotnet/sdk/2.0.1-servicing-006924/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by jamiegs** [comment]
@zhili1208 I spent awhile trying to get a test up and running and I realized I don't know enough about the dotnet cli and cli utils to be able to test it.  I was having a problem where it couldn't find some beta dependancies.

A co-worker of mine created a github repo which can be used to reproduce the issue though. https://github.com/lshearer/NuGetPushFailRepro   You should be able to pull master and follow the steps in the readme to reproduce it.

**Comment by zhili1208** [comment]
@jamiegs I can't repro the issue with your sample

```
NUGETCI-A03:NuGetPushFailRepro nugetciagent$ ./test-publish.sh
+ cd src/NugetPushIssueRepro/
+ rm -rf ./build
+ rm -rf ./bin
+ rm -rf ./obj
+ /Users/nugetciagent/Downloads/dotnet-dev-osx-x64.1.0.4/dotnet restore
  Restoring packages for /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/NugetPushIssueRepro.csproj...
  Generating MSBuild file /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/obj/NugetPushIssueRepro.csproj.nuget.g.props.
  Generating MSBuild file /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/obj/NugetPushIssueRepro.csproj.nuget.g.targets.
  Writing lock file to disk. Path: /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/obj/project.assets.json
  Restore completed in 831.59 ms for /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/NugetPushIssueRepro.csproj.

  NuGet Config files used:
      /Users/nugetciagent/Downloads/NuGetPushFailRepro/NuGet.Config
      /Users/nugetciagent/Downloads/NuGet.Config
      /Users/nugetciagent/.nuget/NuGet/NuGet.Config

  Feeds used:
      https://api.nuget.org/v3/index.json
+ /Users/nugetciagent/Downloads/dotnet-dev-osx-x64.1.0.4/dotnet build --no-incremental -c Release
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  NugetPushIssueRepro -> /Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/bin/Release/netcoreapp1.1/NugetPushIssueRepro.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.45
+ /Users/nugetciagent/Downloads/dotnet-dev-osx-x64.1.0.4/dotnet ./bin/Release/netcoreapp1.1/NuGetPushIssueRepro.dll
Hello
++ echo 6548
+ /Users/nugetciagent/Downloads/dotnet-dev-osx-x64.1.0.4/dotnet pack --no-build -o build -c Release --version-suffix publishtest6548
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Successfully created package '/Users/nugetciagent/Downloads/NuGetPushFailRepro/src/NugetPushIssueRepro/build/NugetPushIssueRepro.3.0.0-publishtest6548.nupkg'.
+ /Users/nugetciagent/Downloads/dotnet-dev-osx-x64.1.0.4/dotnet nuget push ./build/NugetPushIssueRepro.3.0.0-publishtest6548.nupkg --api-key 1234 --source http://localhost:5000/api/v2/package
info : Pushing NugetPushIssueRepro.3.0.0-publishtest6548.nupkg to 'http://localhost:5000/api/v2/package'...
info :   PUT http://localhost:5000/api/v2/package/
info :   Created http://localhost:5000/api/v2/package/ 52ms
info : Your package was pushed.
+ cd ../../
```

**Comment by zhili1208** [comment]
I can repro this issue by pushing  Lykke.Service.OperationsRepository.Client.1.0.35.zip on Mac to nuget.org with CLI 1.0.4.

CLI 2.0.1 and 2.1.0 works well

**Comment by zhili1208** [comment]
I think it's fixed in CLI 2.0.0 which will be released next Monday(8/14/17), also you can try CLI 2.0.x nightly build from https://github.com/dotnet/cli/tree/release/2.0.0. Close it, feel free to reopen it if you still hit this issue in CLI 2.0.0

**Comment by pedershk** [comment]
Still hitting this issue with certain packages when running on Ubuntu 16.04 with dotnet-sdk-2.0.0. So doesn't seem like the problem is entirely fixed..

**Comment by zhili1208** [comment]
@pedershk Could you please share those repro packages?

**Comment by pedershk** [comment]
Hi @zhili1208 

Please find attached the offending package. 

Looking more closely into it - this is actually made from a class library that doesn't yet have a single code file in it. Might that be the issue? It still uploaded/pushed fine on Windows, though.

Also - here's dotnet info for the build agent in question (all Linux build agents we run run off the same exact image, so error occurs on all agents)

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

[Nabo.Security.Contracts.6.0.0-develop-994.zip](https://github.com/NuGet/Home/files/1336662/Nabo.Security.Contracts.6.0.0-develop-994.zip)

**Comment by mishra14** [comment]
This should be fixed in cli v2.0.1 or later. If you are still facing this issue, please let us know.

**Comment by ilexp** [comment]
I'm experiencing a `nuget push` timeout after 300 seconds with the attached package using the following command line:

```
nuget push *.nupkg -Source "https://nuget.org"
```

Previous versions of the same package uploaded just fine. I tried nuget version `4.3.0.4406` and `4.4.1.4656`, both with the same result. Package contents have not changed since the last working push, except for the compiled `dll` or `pdb`.

[AdamsLair.WinForms.1.1.14.nupkg.zip](https://github.com/NuGet/Home/files/1661526/AdamsLair.WinForms.1.1.14.nupkg.zip)

I have manually uploaded the package using the web interface for now, any feedback on this appreciated.

**Comment by anangaur** [comment]
I was able to push the same package successfully (I changed the name and title)
```
C:\tmp>nuget push *.nupkg -Source "https://nuget.org"
Pushing AdamsLair.WinForms.1.1.14.nupkg to 'https://nuget.org'...
  PUT https://nuget.org/api/v2/package/
  Created https://nuget.org/api/v2/package/ 13174ms
Your package was pushed.
```
@ilexp  Can you check if this is a consistent problem and still repros?

**Comment by ilexp** [comment]
The problem still reproduces, even now that the package is already up and I should simply be getting an error because that version / name combo is already taken. Here's what I get instead:

```
nuget push *.nupkg -Source "https://nuget.org"
Pushing AdamsLair.WinForms.1.1.14.nupkg to 'https://nuget.org'...
  PUT https://nuget.org/api/v2/package/
Eine Aufgabe wurde abgebrochen.
Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout <seconds> option with the push command.
```

**Comment by anangaur** [comment]
@cristinamanum is there a way to look into this specific issue in light of similar issues you are debugging? What additional data would you need from @ilexp?

**Comment by ilexp** [comment]
Currently doing the next package release (`AdamsLair.WinForms.1.1.15.nupkg`) and am still experiencing the same problem. I am now using NuGet 4.6.2.5055.

**Comment by ilexp** [comment]
The problem persists. I have attached the most recent package, but I guess that doesn't add new info compared to the last one above.

[AdamsLair.WinForms.1.1.16.nupkg.zip](https://github.com/NuGet/Home/files/2238096/AdamsLair.WinForms.1.1.16.nupkg.zip)

Interestingly, the [web UI for uploading](https://www.nuget.org/packages/manage/upload) also seems to have trouble - I managed to upload it now, but I had to try multiple times and progress always got stuck at some point. It may be unrelated, but I got the following errors:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

I only got past the upload progress bar on something like the fourth page reload - in which case I got directly to the submit page.

**Comment by skofman1** [comment]
@ilexp , we have an open issue on the progress bar that might explain the behavior you are seeing: 
https://github.com/NuGet/NuGetGallery/issues/6085
Would you be able to send us a screen recording so that we would be able to determine if this is indeed the bug in question?

**Comment by ilexp** [comment]
@skofman1 I have created a new package for testing purposes. Same contents, same version, same metadata except for the ID, so no conflict with the previously uploaded package occurs. First, I verified that this package has the same problem with the command line upload - it has, the PUT command gets stuck. Next, I uploaded it via web, getting the following result:

https://gfycat.com/PaleWanBull

After the screen capture while writing this, I left the upload tab open, and as I was about to close it, maybe a few minutes later, I saw that there's another error now, similar to before:

![chrome_2018-07-29_10-00-02](https://user-images.githubusercontent.com/14859411/43364214-4c5e6994-9316-11e8-8320-d0aa6260a9ad.png)

Could the late internal server error be related to the PUT timeout?

Here's the test package in case you need it for reproducing this behavior. Except for its ID and the fact that it's not in the NuGet package repository, it should be identical to the previous ones:
[AdamsLair.WinForms.TestCaseForNuGetIssue.1.1.16.nupkg.zip](https://github.com/NuGet/Home/files/2238593/AdamsLair.WinForms.TestCaseForNuGetIssue.1.1.16.nupkg.zip)

**Comment by skofman1** [comment]
@ilexp , thanks for the repro. This is caused by NuGet/NuGetGallery#6085. The frequency in which the bug repros rises on slow networks. We will fix this soon.

**Comment by SimonCropp** [comment]
given https://github.com/NuGet/NuGetGallery/issues/6085 is fixed, should this one be closed?
