### ISSUE TITLE
No log with PowerShell console command "Update-Package" and -Verbose switch

### ISSUE THREAD

**Issue by pellea** [NuGet/Home#5269]
If I execute this command from VS2017 inside the console:

`Update-Package -reinstall -verbose`

- it prints nothing (-verbose is totally useless)
- it's been more than 30 minutes already and not a single line of log has been displayed
- I don't even know if the command will be done one day ...

Versions:
- VS2017 15.3 (26510.0-Preview)
- Package Manager Console Host Version 4.3.0.2462
- NuGet Version: 3.5.0.1996

**Comment by mishra14** [comment]
I am unable to repro this issue - 

```
PM> Update-Package -reinstall -verbose
  GET https://dotnet.myget.org/F/cli-deps/api/v3/registration1/nunit/index.json
  GET https://api.nuget.org/v3/registration3-gz-semver2/nunit/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/nunit/index.json 263ms
  NotFound https://dotnet.myget.org/F/cli-deps/api/v3/registration1/nunit/index.json 1480ms
No package updates are available from the current package source for project 'ClassLibrary1\ClassLibrary1.csproj'.
Executing nuget actions took 0.1 ms
Time Elapsed: 00:00:01.4981299
PM> 
```

**Comment by pellea** [comment]
Can you try the same command with and without the -verbose flag. It produces the same output. It should not.

> No package updates are available from the current package source for project 'ClassLibrary1\ClassLibrary1.csproj'.

Which package has been checked for update?
How many packages do you have in the project?

Why don't we see these kind of info in the log when using the verbose switch?

**Comment by mishra14** [comment]
It means it checked all the packages for that project. There are other commands for that - https://docs.microsoft.com/en-us/nuget/tools/powershell-reference

**Comment by pellea** [comment]
I was using a source which had a lot of packages dependencies and needed to wait 11 min to get one package. During those 11 *really* long minutes the console had zero log at all (even with the -verbose flag).

So when your Update-Package command got stuck and you don't know why nor where; there is absolutely a big problem here.

The problem is not "there are other command to see referenced package ..."; the problem is that inside the Update-Package if something takes longer you don't see it. Now you should see why it could be useful to see that referenced package where it blocks.

BTW in the latest build of VS, "Update-package -reinstall" doesn't reinstall packages but try to update them. It wasn't doing that in a previous version.
