### ISSUE TITLE
nuget has problems with pwds with special chars

### ISSUE THREAD

**Issue by abcdabcdabcd** [NuGet/Home#527]
If your config uses repos with validation and you store the password in cleartext in the config file and it is has some special chars in it, VS fails to load the config file and just shows the default repos

**Comment by deepakaravindr** [comment]
@abcdabcdabcd 

Thanks for the feedback! We will fix this post RTM

As a workaround, Consider using 'nuget.exe -config'  to set encrypted password. Check out http://docs.nuget.org/consume/Command-Line-Reference

**Comment by yishaigalatzer** [comment]
@abcdabcdabcd thinking some more about this issue, my guess is that the special chars break XML, so not much we can do other than XML encoding it and supporting a command to add it.

Was that the intent?

**Comment by zhili1208** [comment]
@abcdabcdabcd  can you share those special chars? thanks

**Comment by yishaigalatzer** [comment]
Since we have no more feedback on this, and we have a bug with details https://github.com/NuGet/Home/issues/2158, I'm closing as a dup
