### ISSUE TITLE
Logging:  warnings reported as errors

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#5278]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):  NuGet.exe

NuGet version (x.x.x.xxx):  latest dev branch

dotnet.exe --version (if appropriate):  N/A

VS version (if appropriate):  N/A

OS version (i.e. win10 v1607 (14393.321)):  Windows 10 v1703 (15063.296)

Worked before? If so, with which NuGet version:  4.1.0

## Detailed repro steps so we can see the same problem

1.  Create packages.config with the following content:
```
<packages>
  <package id="Newtonsoft.Json" version="1.0.0" />
</packages>
```
2.  Open a command prompt, path into the directory containing the above packages.config, and execute:

```
nuget.exe restore -source https://api.nuget.org/v3/index.json -outputdirectory .\packages
```

Expected result:  1 warning and 1 error

Actual result:  1 warning and 2 errors

The issue is that the [warning is reported as an error](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Common/Logging/CollectorLogger.cs#L42), even though the default verbosity is `LogLevel.Debug`.

**Comment by emgarten** [comment]
@mishra14 is this fixed in the feature branch?

**Comment by mishra14** [comment]
Yup. This is fixed in feature branch. Will wait for dev merge before closing this bug.

**Comment by mishra14** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/commit/345115292dcb6b3643898454e77701746d5605dc
