### ISSUE TITLE
Custom content location within solution?

### ISSUE THREAD

**Issue by Ylaana** [NuGet/Home#5280]
I'm using Visual Studio 2015 Update 3 with NuGet 3.5.0 to build ASP.NET WebForms apps. Any packages I add sit in a packages folder above the solution level, which is fine. By default, the content of these packages is extracted to folders in the root of my solution (Content, Images, Scripts). I know it's possible to change the location of the packages folder with a nuget.config file, but can the same be done for the content folders? I want to keep them away from the rest of my files in a separate root folder, instead of them clogging up my solution. Thanks.

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
