### ISSUE TITLE
Issues with VS2017 and myget repo

### ISSUE THREAD

**Issue by moraleslos** [NuGet/Home#5283]

**Comment by moraleslos** [comment]
Using VS2017 Community, I'm trying to dotnet restore a project that uses OpenIddict hosted on myget.  For some reason, nuget doesn't pull from myget.  I get the following error: 

**C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Unable to resolve 'OpenIddict (>= 1.0.0-beta2-0614)' for '.NETCoreApp,Version=v1.1'.**

Not sure why it won't grab OpenIddict.  The nuget.config file in my project looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="aspnet-contrib" value="https://www.myget.org/F/aspnet-contrib/api/v3/index.json" />
  </packageSources>
</configuration>
```
In the AppData the nuget config looks like:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
<packageSources>
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
</packageSources>
</configuration>
```

This worked before using project.json in VS2015.  So not sure if there were any breaking changes when migrating to VS2017.

**Comment by mishra14** [comment]
Thanks for reporting the issue. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
