### ISSUE TITLE
MSBuild /t:Restore exit code is always 0

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#5284]
_From @nguerrera on May 19, 2017 18:7_

_From @Jonathan34 on May 10, 2017 21:41_

## Steps to reproduce
- have an invalid csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <!--<RuntimeFrameworkVersion>2.0.0-preview1-005957-00</RuntimeFrameworkVersion>-->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta2-build1317" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\API.csproj"></ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>Invalid Characters to fail processing of the project file
````
then dotnet restore

## Expected  behavior
```
/app/code/test/IntegrationTests/IntegrationTests.csproj(18,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 18, position 11
.
exit code is not 0
```
## Actual behavior
exit code is 0

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0-preview1-005957)

Product Information:
 Version:            2.0.0-preview1-005957
 Commit SHA-1 hash:  056ac0e9cd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005957/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983
```

_Copied from original issue: dotnet/cli#6569_

_Copied from original issue: Microsoft/msbuild#2113_

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

Interestingly, this does not repro on Windows

```
D:\qqq>dotnet restore
D:\qqq\qqq.csproj(8,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 8, position 11.

D:\qqq>echo %ERRORLEVEL%
1
```

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

_From @Jonathan34 on May 10, 2017 22:51_

This is my test script

```
#!/bin/bash

cleanup () {
}

trap 'cleanup ; printf "Tests Failed For Unexpected Reasons\n"'\
  HUP INT QUIT PIPE TERM

dotnet restore $(pwd)/API
if [ $? -ne 0 ] ; then
  printf "dotnet restore failed$\n"
  exit 1
fi
```
Does not fail :(

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

_From @livarcocc on May 11, 2017 0:15_

This issue was moved to NuGet/Home#5211

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

_From @Jonathan34 on May 11, 2017 1:7_

Thanks!

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

This isn't a nuget issue. MSBuild is failing to load the project file, it's not up to the restore target to signal that with non-zero exit. Possible culprits are msbuild, cli, or runtime. Let's investigate here and route once we know the cause.

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

@Jonathan34 This didn't repro for me on mac either with 2.0.0-preview1-005977 

Here were my steps:

* Install from https://www.microsoft.com/net/core/preview#macos
* `mkdir repro`
*  `cd repro`
* `dotnet new console`
* `echo junk >> repro.csproj`
* `dotnet restore`
* `echo $?`

```
$ dotnet restore
/Users/nicholg/repro/repro.csproj(9,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 9, position 1.

$ echo $?
1
```

Do you see the same correct result when using my steps? If so, are you able to come up with a more specific repro that incorrectly flips `$?` to 0?

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

_From @Jonathan34 on May 12, 2017 14:53_

@nguerrera you need two projects and a sln referencing the two projects. then you mess up with one and restore the sln. either the return code is the one fro the last project, either it is OR'ed and should be AND'ed (not really english!)

it will return 0.

```
mkdir repro
cd repro
mkdir proja
mkdir projb
cd proja
dotnet new console
cd ../projb
dotnet new console
cd ..
dotnet new sln
dotnet sln add proja/proja.csproj
dotnet sln add projb/projb.csproj
echo junk >> proja/proja.csproj
dotnet restore
echo $?
```

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:7_

Thanks! I'll take a look

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:8_

Repros on windows too with msbuild /t:restore on sln.

**Comment by rainersigwald** [comment]
_From @nguerrera on May 19, 2017 18:9_

[msbuild.binlog.zip](https://github.com/Microsoft/msbuild/files/1015134/msbuild.binlog.zip)

**Comment by rainersigwald** [comment]
I thought I'd reduced this to only reproduce when run in multiproc mode but that's not the case; it fails with `dotnet msbuild /t:restore /m:1`.

**Comment by rainersigwald** [comment]
_From @nguerrera on May 24, 2017 19:33_

AFAICT, this is not specific to .NET Core

```
D:\Temp\qwe\repro>"C:\Program Files (x86)\Microsoft Visual Studio\D15PreRel\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" /t:restore /v:m
Microsoft (R) Build Engine version 15.3.246.41955 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Temp\qwe\repro\proja\proja.csproj(9,1): error MSB4025: The project file could not be loaded. Data at the root level
is invalid. Line 9, position 1.
  Restoring packages for D:\Temp\qwe\repro\projb\projb.csproj...
  Lock file has not changed. Skipping lock file write. Path: D:\Temp\qwe\repro\projb\obj\project.assets.json
  Restore completed in 246.46 ms for D:\Temp\qwe\repro\projb\projb.csproj.

  NuGet Config files used:
      D:\Temp\qwe\repro\projb\NuGet.Config
      C:\Users\nicholg\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://api.nuget.org/v3/index.json
      C:\Users\nicholg\.dotnet\NuGetFallbackFolder
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

D:\Temp\qwe\repro>echo %ERRORLEVEL%
0
```

**Comment by rainersigwald** [comment]
_From @jeffkl on May 24, 2017 19:48_

Is this because NuGet.targets is setting `ContinueOnError` to `true` by default:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L235

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L47

So the error is still logged but the task does not fail the build?

**Comment by rainersigwald** [comment]
@jeffkl 🔔 we have a winner!

```
S:\work\restore_exit\repro>dotnet restore /p:RestoreContinueOnError=ErrorAndContinue
S:\work\restore_exit\repro\proja\proja.csproj(9,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 9, position 1.
  Restoring packages for S:\work\restore_exit\repro\projb\projb.csproj...
  Lock file has not changed. Skipping lock file write. Path: S:\work\restore_exit\repro\projb\obj\project.assets.json
  Restore completed in 696.86 ms for S:\work\restore_exit\repro\projb\projb.csproj.

  NuGet Config files used:
      C:\Users\raines\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      https://dotnet.myget.org/F/roslyn/api/v3/index.json
      C:\Users\raines\.dotnet\NuGetFallbackFolder
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

S:\work\restore_exit\repro>echo %ERRORLEVEL%
1
```

**Comment by emgarten** [comment]
@jeffkl @rainersigwald thanks for tracking this down! :smile:

This was done to avoid failing when walking child projects that do not support restore. It looks like Restore should instead limit the targets where it ignores errors, this could be done much better.

**Comment by emgarten** [comment]
I went through this again, the current behavior is expected. Users should discover problems with invalid projects at build time. Displaying errors in both scenarios leads to duplicate errors which we are trying to avoid.

One scenario where errors are expected is when a C# project depends on a C++ project that doesn't support ``CustomAfterMicrosoftCommonTargets``. Restore tries to call the restore target in the child project and it fails.

Is there a better way that projects can be checked to see if a target exists before calling into it? That would help solve the main scenario that blocking these restores, however I'm still not sure the behavior of having restore validate all of the projects and duplicate errors is a good one.

**Comment by Jonathan34** [comment]
The simple scenario is for CI. I want to stop the build if restore fails rather than going to build. Otherwise I see build errors that happened because of the previous step.

**Comment by emgarten** [comment]
> Otherwise I see build errors that happened because of the previous step.

Which errors do you see? If the the project is invalid xml you will see only that error, not errors from missing packages. For project references it should be the same, child projects will build first and fail. Am I missing a scenario here where packages aren't build restored and a build still starts?

**Comment by jeffkl** [comment]
> If the the project is invalid xml you will see only that error, not errors from missing packages. 

@emgarten When using stand-alone NuGet.exe, it writes out [NuGet.targets](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets) and calls: ([here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L103))
```
MSBuild.exe
  %TEMP%\NuGet.targets
  /t:GenerateRestoreGraphFile
 /p:RestoreGraphProjectInput=MyOriginalProject.csproj
 /p:RestoreContinueOnError=WarnAndContinue
  ...
```

`NuGet.targets` then fires off an `<MSBuild />` task against the project which could have malformed XML.  In this case, the target fails but there is nothing reported to the user.

```xml
<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DoesNotExist" Version="1.0" />
  </ItemGroup>
</Project>  BADXML!
```

```
C:\>NuGet4.exe restore nuget.proj
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\15.0\bin'.
Nothing to do. This project does not specify any packages for NuGet to restore.
```

Things mostly go awry when the top-level project is fine but a dependency has either bad XML or something else goes wrong.  Since that call is a different `<MSBuild />` task with `WarnAndContinue`, the build does not stop if restore fails.  That said, I'm not sure the best fix.  There's `$(MSBuildLastTaskResult)` and `<OnError />` but I don't think they'll help.

**Comment by emgarten** [comment]
@jeffkl right, and it will also fail if the project is a non-NuGet project that doesn't support restore or need to restore.

In your example there are no valid projects to restore, the build that happens after should display the XML error.

A feature in msbuild to check if a target existed or to just get the value of a property from a project reference before trying to call into it would help solve this.

**Comment by Jonathan34** [comment]
@emgarten if the restore steps fails on one prokject, packages might not be restored, build will likely fail in CI due to missing dependencies.

**Comment by emgarten** [comment]
> @emgarten if the restore steps fails on one prokject, packages might not be restored, build will likely fail in CI due to missing dependencies.

Wouldn't it fail on a project dependency with invalid XML first? I don't think it would get building against the missing package references.

**Comment by Jonathan34** [comment]
This is for .net core and it's tooling. It comes in two steps and is not via visual studio. In my case I have a batch script that does `dotnet restore` and then `dotnet build`.  Restore return 0 so it goes to build....

**Comment by emgarten** [comment]
> Restore return 0 so it goes to build....

What is the result when it goes to build?

**Comment by Jonathan34** [comment]
Build fails since a project was not restored properly and the build exit code is not 0 since at least one project failed to build

**Comment by emgarten** [comment]
@Jonathan34 can you share the error message :smile: 

I'm trying to understand how errors due to missing packages show up **before** an invalid project file during build.

**Comment by Jonathan34** [comment]
It is in the first comment already. Not sure what else you need? The build error?

**Comment by emgarten** [comment]
Here is an example using dotnet 2.0.0-preview2-006098

Project A references project B and uses a transitive dependency from B. Without this package dependency A cannot build.

### Directory structure
```
root
  | a.sln
  |- a/a.csproj
  |- a/Class1.cs
  |- b/b.csproj
```

### a/a.csproj

A references project B

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../b/b.csproj" />
  </ItemGroup>

</Project>
```

### b/b.csproj

Project B includes Newtonsoft.Json, but the project is invalid.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
  </ItemGroup>

</Project>Invalid Characters to fail processing of the project file
```

### a/Class1.cs

Project A uses Newtonsoft.Json

```cs
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace a
{
    public class Class1
    {
        public JObject Test()
        {
            return null;
        }
    }
}
```


### Steps
1. ``dotnet restore a.sln``
1. ``dotnet build a.sln``

```
D:\tmp\exitcodetest> D:\tools\dotnet\dotnet.exe build
Microsoft (R) Build Engine version 15.3.234.47922 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

D:\tmp\exitcodetest\b\b.csproj(11,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 11, position 11.
D:\tmp\exitcodetest\b\b.csproj(11,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 11, position 11.

Build FAILED.

D:\tmp\exitcodetest\b\b.csproj(11,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 11, position 11.
D:\tmp\exitcodetest\b\b.csproj(11,11): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 11, position 11.
    0 Warning(s)
    2 Error(s)
```

I get the same result when building ``a.csproj`` or ``b.csproj``

**The error is clear that the project is invalid at build time. There is no noise from the missing package references, only errors for the invalid XML.**

Relying on restore to provide build errors will always be error prone, ideally these two steps would happen together so that users do not need to be concerned about one vs the other.

**Comment by emgarten** [comment]
This has been improved with NuGet/NuGet.Client@76a7439c5f4180697e8ef284b42f158a7ff328e1

The initial walk will continue to skip invalid projects, these will be reported at build time. Errors when reading package references and targets executing before and after restore will now be treated as errors.
