### ISSUE TITLE
NuGet 4.1.0 packages

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#5287]
Are there plans for NuGet 4.1.0 packages, e.g. NuGet.Versioning.

Looks like the latest stable is 4.0.0:
https://www.nuget.org/packages/NuGet.Versioning

**Comment by maartenba** [comment]
+1

**Comment by joelverhagen** [comment]
Any plans for this @rrelyea?

**Comment by maartenba** [comment]
Or 4.2 and 4.3 for that matter, given I've seen those numbers in several issues here :-)

**Comment by rrelyea** [comment]
4.3 preview packages are posted. We'll go back and do 4.1 and 4.2 as part of #5573

**Comment by jainaashish** [comment]
4.1 and 4.2 packages are published to nuget.org
