### ISSUE TITLE
Interface missing in symbol package

### ISSUE THREAD

**Issue by tom-englert** [NuGet/Home#529]
After adding an interface to my project, uploading symbols fails with the message:

The remote server returned an error: (506) Package submission failed: Source file d:\Develop\My Open Source\TomsToolbox\Main\TomsToolbox.Core\INotifyChanged.cs
not found in package. Source file is declared in TomsToolbox.Desktop.pdb

The project is at https://tomstoolbox.codeplex.com/SourceControl/latest (Main branch)

**Comment by deepakaravindr** [comment]
@tom-englert , Can you please check if the package has the INotifyChanged.cs?

**Comment by yishaigalatzer** [comment]
@tom-englert we are not able to repro this and haven't heard back from you for over a week. Please get back to us with more details, so we can keep this rolling

**Comment by tom-englert** [comment]
Sorry, I've been away for holidays. 
Here are some more details I wasn't aware myself in the first place:
- INotifyChanged is defined in the Core module. The Core symbol package is fine an contains the INotifyChanged.cs
- INotifyChanged is implemented once in the Desktop module in DependencyObjectExtensions.cs
- The error is in the **Desktop** modules symbol package. It only references the INotifyChanged interface, but analyzing the package complains it was build from the source file ..\TomsToolbox.Core\INotifyChanged.cs, which seems to be a wrong assumption.

**Comment by yishaigalatzer** [comment]
Sounds like either a build issue or a symbol server issue (likely the first). Not sure nuget has anything to do with this.

**Comment by tom-englert** [comment]
The package is generated with 
- nuget pack -symbols "$(ProjectPath)" -IncludeReferencedProjects -Prop Configuration=$(ConfigurationName)
Checking the package with "Package Explorer" and the "SymbolSource.Integration.NuGet.PackageExplorer [1.3.4]" plugin shows the same error

**Comment by emgarten** [comment]
@tom-englert  Can you provide a project that repros this issue?

**Comment by yishaigalatzer** [comment]
@tom-englert we need a project to look into this. I'm not clear if INotifyChanged.cs shows up in the Desktop PDB (which will mean it is not a NuGet issue, but a compiler/build system issue) or it is not and then it might be a NuGet issue after all.

**Comment by tom-englert** [comment]
The project is at https://tomstoolbox.codeplex.com/SourceControl/latest (Main branch)

**Comment by tom-englert** [comment]
I could finally locate the problem. It only happens if the CodeContracts runtime rewriter (https://github.com/Microsoft/CodeContracts) is active. The rewriter adds the additional reference to the .pdb file.

**Comment by tom-englert** [comment]
According to code contracts this behavior is correct (https://github.com/Microsoft/CodeContracts/issues/45) - and NuGet should include the file if it is referenced by the .pdb!

**Comment by yishaigalatzer** [comment]
I understand that it is. But this is a super obscure behavior, and NuGet is not going to add a pdb reader for this scenario. My suggestion is to pack manually in this case or ditch code contracts.
