### ISSUE TITLE
"Installed" view shows the version of the latest available package, not the installed version

### ISSUE THREAD

**Issue by aBaechtold** [NuGet/Home#5293]
This is not an issue/bug report, but a behavior/feature consideration/request.

For the version I'm using (see further below) the NuGet tool window (e.g. Solution Explorer > Right click solution item > Select "Manage NuGet packages for Solution") shows in the "Installed" view the version of the latest available package. I was expecting to see there the installed version of the package (e.g. the package list acting like an version overview) and got confused a couple of times. Arguably there might be multiple versions of a package installed, but still then I would not expect to have to click the item from the package list in order to see what versions are really installed. Things may be different for other views like upgrade or consolidation.

Using NuGet Package Manager for Visual Studio 2015: v.3.4.4.1321
Visual Studio Enterprise 2015 v14.0.25431.1 Update 3
Windows 10 Enterprise 2015 LTSB

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
