### ISSUE TITLE
Package Manager Console can run with only PowerShell version 5

### ISSUE THREAD

**Issue by techmike2kx** [NuGet/Home#5294]
I'm aware of a security risk in in PowerShell 2.0 (see this : http://www.leeholmes.com/blog/2017/03/17/detecting-and-preventing-powershell-downgrade-attacks/ ) so I removed the 2.0 dependency from my pc.  

this somehow resulted in Package Manager Console  issues in Visual Studio 2017 (but I reckon it can also happens in lower versions)

is this behavior normal, so depending on PowerShell 2.0?

![error_001](https://cloud.githubusercontent.com/assets/1908220/26587496/cc6d7d72-4552-11e7-902a-acca6b873e0a.png)
![error_002](https://cloud.githubusercontent.com/assets/1908220/26587493/cb17719e-4552-11e7-8002-f66285876db9.png)
![error_003](https://cloud.githubusercontent.com/assets/1908220/26587495/cb5320cc-4552-11e7-8d9c-0cb0c96862b1.png)

+ @blowdart #3682

**Comment by blowdart** [comment]
That's odd. It shouldn't IMO. I'll chase this up.

**Comment by techmike2kx** [comment]
thanks sir :-)!

**Comment by rrelyea** [comment]
Today, it looks like NuGet client code in VS requires Powershell 2, 3, or 4 to be installed on the machine.
We are investigating.

**Comment by anangaur** [comment]
@rrelyea Windows 10 comes with Powershell 5.0 by default.
![image](https://user-images.githubusercontent.com/14800916/26988227-5c49de74-4d03-11e7-8f64-fe9b2f57c7b3.png)

**Comment by rrelyea** [comment]
@karann-msft - this bug was fixed in 4.3. Can you make sure our release notes call it out as fixed? I just fixed the labels on it.

**Comment by rrelyea** [comment]
VS 2017 version 15.3 shipped on 8/14/2017 with the fix for this bug.
