### ISSUE TITLE
[MAS] The search control in the PackageManagerControl does not report it's status

### ISSUE THREAD

**Issue by Newrad0603** [NuGet/Home#5296]
## Details about Problem

NuGet product used: "Manage NuGet Packages..." UI

VS version: 26526.0

## Detailed repro steps so we can see the same problem

0. Turn on Narrator and launch VS

1. Create a WPF project

2. Right-click on the project node in Solution Explorer 

3. Click Manage NuGet Packages...

4. Click on the Browse tab

5. Enter a search term into the search box

Expected:
The search control reads out the number of found search results like other search controls in VS now do.

Actual:
Nothing is read off, so screen reader users do not know when the search completes.

## Other suggested things
The issue here is that the search functionality for the PackageManagerControl returns a null task for the IVsSearchTask.CreateTask method. Additionally, nothing implements the IVsSearchCallback, so the search control never reports it's completion status and the number of results found.

**Comment by rrelyea** [comment]
closing this issue, as we reactivated internal bug 395888 and assigned to our team.
