### ISSUE TITLE
Support for marking files executable when running NuGet pack on Windows

### ISSUE THREAD

**Issue by agocke** [NuGet/Home#5298]
NuGet provides a `tools` directory as a convenient place to put executable tools, but doesn't provide a way to indicate that a file should be marked executable when it is restored on a Unix machine. This makes it difficult to pack shell scripts for Unix machines since the Windows file system does not provide a way to mark shell scripts executable.

**Comment by emgarten** [comment]
Everything gets marked as executable with this recent change: https://github.com/NuGet/NuGet.Client/pull/1346

**Comment by mishra14** [comment]
@agocke This should be fixed as @emgarten  mentioned. can you please try and let us know if you are still facing an issue.
