### ISSUE TITLE
Link VS Package Entries to Gallery Package Pages

### ISSUE THREAD

**Issue by jonwchu** [NuGet/Home#5299]
In Visual Studio, when you search for package for a package, you should be able to see in the package info view, a link back to the NuGet Gallery. Since the Gallery may contain information that isn't present in VS it would be helpful to users to be able to navigate to the Gallery to find out more.

**Comment by rrelyea** [comment]
Might be a good idea.
@jonwchu - Which information should be on the site, but not on the client?

**Comment by mishra14** [comment]
@karann-msft is this covered in your spec for package compatibility?

**Comment by karann-msft** [comment]
@jainaashish yes https://github.com/NuGet/Home/wiki/Package-applicability-in-NuGet-package-manager-UI#a-more-concise-package-details-pane
Its the last image in the spec. You might have to zoom in up to 200%

![image](https://user-images.githubusercontent.com/16904420/34132277-f9febe9a-e403-11e7-9e62-3fe013d0d16f.png)

**Comment by joelverhagen** [comment]
I took an initial stab at this here: https://github.com/NuGet/NuGet.Client/pull/2518.

![image](https://user-images.githubusercontent.com/94054/48216865-b2ab9e00-e33a-11e8-9453-02599f8d2006.png)

Works on V2 with only a client change and works on V3 with a tiny server change (very cheap and low risk).

**Comment by karann-msft** [comment]
@joelverhagen  WAIT! am i reading this right? requires no client change for V3?

**Comment by joelverhagen** [comment]
Sorry, wasn't clear.

V2: small client change, no server change
V3: small client change, small server change

**Comment by karann-msft** [comment]
:shipit:

**Comment by nkolev92** [comment]
Let's triage this appropriately about whether we want to take it and close on Joel's PR. 

There's already a discussion in the PR.

**Comment by rrelyea** [comment]
This made it into 5.1 right? Any reason to keep it open?

**Comment by karann-msft** [comment]
PSA: And this is how it finally looks:

![image](https://user-images.githubusercontent.com/16904420/58112739-f2382a00-7ba8-11e9-987d-4f9d385a0830.png)
