### ISSUE TITLE
NuGet restore does not return failure if there is an error from a project

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#5309]
Run `dotnet restore` on the following project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <Target Name="ErrorBeforeRestore" BeforeTargets="_GenerateRestoreProjectSpec">
    <Error Text="Failing before restore" />
  </Target>

</Project>
```

## Expected

The restore command returns a non-zero exit code, indicating there was a failure

## Actual

The restore command returns a zero exit code, indicating success.  Output is as follows:

>C:\git\dotnet-sdk\bin\repro\WrongFramework\WrongFramework.csproj(12,5): error : Failing before restore
>  Nothing to do. None of the projects specified contain packages to restore.

## Comments

This is because the `RestoreContinueOnError` property [defaults to `WarnAndContinue`](https://github.com/NuGet/NuGet.Client/blob/12331b7b6f95522433bf1d2c80849f6ccf00a230/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L49).  Perhaps this is so that if there is an issue with one project, as much as possible of the restore can still be completed.  Perhaps `ErrorAndContinue` would be a better default value.

**Comment by emgarten** [comment]
This has been fixed in the restore noop work, it will go into dev this week.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Client@76a7439c5f4180697e8ef284b42f158a7ff328e1
