### ISSUE TITLE
Package Manager is making extra network calls

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#531]
Package Manager is making extra network calls to retrieve package details available in search.

On the Package Manager dialog half of the details come from a single network call to the search service. And half come from a subsequent call to fetch the registration blob which also in-lines the details.

Switching between detail view causes more network calls.

Some of the details return in the search are ignored.

This is both an issue for performance and coupling.

Extending the search result to include all the details required by the view is trivial (the is already available for other scenarios).

**Comment by yishaigalatzer** [comment]
@johnataylor please make the server change, I can help with the client changes after that.

**Comment by johnataylor** [comment]
The most significant extra network calls are now addressed. (For example with packages like FAKE and RavenDB the client was fetching ALL the metadata for ALL versions.)

Further optimizations are possible, leaving this open, possible deprioritize now.

**Comment by johnataylor** [comment]
This requires changes in the UI code. The problem is mostly addressed. Further optimizations can be done from the server and in the next release of the client.
