### ISSUE TITLE
"msbuild /t:restore" target missing in 15.3 Preview

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5310]
This has been broken for over a week. It seems the most basic restore operation is broken.

```
git clone https://github.com/microsoft/vs-validation
cd vs-validation\src\Microsoft.visualstudio.validation
MSBuild /t:restore
```

Produces this result:

> C:\git\validation\src\Microsoft.VisualStudio.Validation\Microsoft.VisualStudio.Validation.csproj : error MSB4057: The target "restore" does not exist in the project.

Repros on:
d15rel 26530.1
d15prerel 26530.4

This does not repro on 15.2 or early builds of 15.3.

`dotnet restore` works where `MSBuild /t:restore` does not, BTW.

**Comment by emgarten** [comment]
Thanks for the build info! I'll try reproing this. 

Duping this in favor of https://github.com/NuGet/Home/issues/5300
