### ISSUE TITLE
dotnet restore ignores user-wide config

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5311]
_From @matkoch on May 31, 2017 23:8_

## Steps to reproduce

- Project with dependencies located on a different source (not nuget)
- Call `dotnet restore XXX.csproj --configfile customfile.config`

## Expected  behavior

- Passed configfile (custom source) and user-wide config `$HOME/.nuget/NuGet/NuGet.config` (default nuget source) should be used to restore packages

## Actual behavior

- All dependencies are resolved
- Note that it works, if I copy/paste the default nuget source from the user-wide config into the `--configfile` config

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.0-preview2-006127)

Product Information:
 Version:            2.0.0-preview2-006127
 Commit SHA-1 hash:  946ea7980a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/matthias.koch/Desktop/test/IN/.dotnet/sdk/2.0.0-preview2-006127/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25319-02
  Build    : 7983b575ebcbdc3a825eea4b141ff7fb69d25f9d

/cc @emgarten 

_Copied from original issue: dotnet/cli#6725_

**Comment by emgarten** [comment]
When using ``--configfile`` only that config file is used, it is **not** added to the current configs.

**Comment by matkoch** [comment]
But according to https://github.com/dotnet/cli/issues/2154#issuecomment-204793753 I thought the machine-wide config is picked up? Or is `$HOME/.nuget/NuGet/NuGet.config` something different?

**Comment by matkoch** [comment]
It is very much unexpected if the global config was not considered during restore. I would understand if you would introduce a parameter like `--no-global-config` or something, to prevent loading in special circumstances. But in this case, what's the use of a global nuget.config?!

**Comment by emgarten** [comment]
The global nuget.config is that it is always applied **unless** you specify an exact nuget.config to use, then **only** that nuget.config file will be used.

**Comment by matkoch** [comment]
Well, but in this case it doesn't correctly resolve the solution nuget config. My folder structure is as follows:

```
+ build/build.csproj
+ source/
   + .nuget/NuGet.config (with additional source)
   + Other projects
   + Solution.sln
```

In previous nuget versions, I could add `-SolutionDirectory /source` to make the config file being picked up when restoring `build.csproj`.

Note that it's totally legitimate that a project is not contained in the same subtree as the solution file.

**Comment by emgarten** [comment]
Move ``NuGet.config`` to the source directory instead of ``.nuget``

``dotnet.exe`` differs from the legacy NuGet behavior which used the ``.nuget`` folder and worked only on solutions.

**Comment by matkoch** [comment]
I assume you mean `/build` ?

**Comment by emgarten** [comment]
> I assume you mean /build ?

You're right, in this case it would need to be in ``/build`` or ideally above both folders.

**Comment by matkoch** [comment]
It does solve the restore issue, however, putting it:
- next to the csproj file, won't include the source in VisualStudio PackageManager.
- into the first common parent feels like a hack/unclean, because the solution file is somewhere else.

So either the `-solutionDirectory` switch should be re-introduced, or VisualStudio should finally support project-related nuget.configs.

**Comment by emgarten** [comment]
> So either the -solutionDirectory switch should be re-introduced, or VisualStudio should finally support project-related nuget.configs.

I agree, the differences here are painful. NuGet is stuck between the old packages.config behavior and the old xproj behavior which didn't use solution files cross platform.

One option could be to specify settings as msbuild project properties or through a props file that all projects include.

**Comment by emgarten** [comment]
For reference the original issue behind this change is here: https://github.com/NuGet/Home/issues/2087
