### ISSUE TITLE
nuget package restore triggered while building fails if package source is a secured private nuget server

### ISSUE THREAD

**Issue by softlion** [NuGet/Home#533]
Facts:
- A project contains a missing nuget package that has been obtained from a private nuget server which requires authentication
- Build the project

The build fails to restore the nuget package and does not pop the authentication box. The user must use the restore button in the "manage nuget package" dialog instead.

This is not really an issue, as it is not expected from builds to display an interactive UI. Especially for build servers.

**Comment by deepakaravindr** [comment]
@softlion 
Please check http://docs.nuget.org/consume/NuGet-Config-Settings for setting up the credentials in nuget.config, so that, package restore can use it and not fail. In this scenario, UI is not the option
