### ISSUE TITLE
Installing Microsoft.Azure.Graphs through NuGet API package results in an exception

### ISSUE THREAD

**Issue by dend** [NuGet/Home#5333]
I am using the NuGet API package in my own project to pull NuGet packages from the v3 feed. Everything works fine, with the exception of one package - [Microsoft.Azure.Graphs](https://www.nuget.org/packages/Microsoft.Azure.Graphs/).

When I install the package in a test console app in Visual Studio, there are no issues.

![packagedep](https://cloud.githubusercontent.com/assets/1389609/26756589/d7a743c0-485a-11e7-9c9c-4b1e67b395c2.PNG)

I am triggering the package install with:

```
NuGetProject project = new TargetedFolderNuGetProject(rootPath, Parameters["tfm"]);

var packageManager = new NuGetPackageManager(sourceRepositoryProvider, settings, rootPath)
{
    PackagesFolderNuGetProject = (FolderNuGetProject)project
};

var resolutionContext = new ResolutionContext(DependencyBehavior.Lowest, true, true, VersionConstraints.None);

INuGetProjectContext projectContext = new ProjectContext();
var sourceRepository = new SourceRepository(packageSource, providers);

// Check if we have a metapackage flag
if (package.CustomPropertyBag.ContainsKey("metapackage"))
{
    var metaFlag = Convert.ToBoolean(package.CustomPropertyBag["metapackage"]);
    package.IsMetaPackage = metaFlag;
}

ConsoleEx.WriteLine($"Attempting to install: {package.GetFullName()}. Installing...",
        ConsoleColor.Yellow);
var identity = new PackageIdentity(package.Name, NuGetVersion.Parse(package.Version));
await packageManager.InstallPackageAsync(packageManager.PackagesFolderNuGetProject,
    identity, resolutionContext, projectContext, sourceRepository,
    null, // This is a list of secondary source respositories, probably empty
    CancellationToken.None);
```

I am using the NuGet.Client package 4.3.0-beta1-2418.

**Comment by rrelyea** [comment]
@dend  - can you give more details on "a test console project in VS"

**Comment by dend** [comment]
@rrelyea To clarify, what I mean by "test console project" is if I create a new console project, and use the NuGet package manager to install the package, it works perfectly fine. I can't do it through the API though for some reason.

**Comment by rrelyea** [comment]
My guess is that the type of project you are installing into is the problem. Still don't understand which one works. What kind of console project (full framework? core?), which TFM?
I don't know offhand what a PackagesFolderNuGetProject is. Is that similar to the test console project?

**Comment by dend** [comment]
@rrelyea to give you a better example, we are trying to use the NuGet API to install the following package:

_Microsoft.VisualStudio.Services.ExtensionManagement.WebApi 15.118.0-preview_

One of the dependencies is this package:

[https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Gallery.WebApi](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Gallery.WebApi)

Notice that **Microsoft.VisualStudio.Services.ExtensionManagement.WebApi** for .NET Framework has a hard dependency on **Microsoft.VisualStudio.Services.Gallery.WebApi** that NuGet API fails to resolve, for some reason, when I install the package and set the TFM to **net47** (which, ideally, should fallback on a lower TFM).

**Comment by dend** [comment]
This no longer repros for the `Microsoft.Azure.Graphs` package, however #4512 is a good demonstration of the original issue with a different package. @rrelyea

**Comment by mishra14** [comment]
Closing as #4512  is marked as external.
