### ISSUE TITLE
NuGet not deploying on ASP.NET Core web application

### ISSUE THREAD

**Issue by lordofscripts** [NuGet/Home#5334]
I have created NuGet packages before but this was my first NuGet targetting an ASP.NET Core web application.

My NuSpec hierarchy looks like this:

     Content\
          Views\
               Shared\
                   _Partial1.cshtml.pp
                   _Partial2.cshtml.pp
          wwwroot\
                css\
          Models\
                Bootstrap\
                    Model1.cs.pp
                    Model2.cs.pp

There are no issues with the package. I am able to build the package and save the NuSpec as well. I installed the NuGet into my ASP.NET Core (1.1) web application and no errors were given but NONE of the files in my NuGet appear anywhere in the project.

## Details about Problem

NuGet executable v3.21.0

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate): 

VS version (if appropriate): VS.2017 Community Edition

OS version (i.e. win10 v1607 (14393.321)): Win 7 Ultimate

Worked before? If so, with which NuGet version:

**Comment by emgarten** [comment]
@lordofscripts NETCore SDK projects do not support the legacy `content/` folder, the `contentFiles/` folder is used instead.

Take a look at http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

**Comment by lordofscripts** [comment]
@emgarten tried that just now and the package analysis fails because it says the transforms will not be done because they must be in the CONTENT folder and not in contentFiles.

**Comment by emgarten** [comment]
In NETCore SDK projects there is only a restore operation, it doesn't have install/uninstall operations like packages.config projects had, and there is no state tracking for this that is checked into source control. For this reason ``contentFiles`` only supports immutable content that does not change the project, and transforms are not used.

To run custom actions you can use a targets file in the build folder to run as part of the build and make any needed changes.

**Comment by mishra14** [comment]
@lordofscripts please let us know if you are still facing this issue latest [VS2017](https://www.visualstudio.com/#).
