### ISSUE TITLE
A question about RestoreCommand.VerifyCompatibility

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#5338]
When I call restore via `DependencyGraphRestoreUtility.RestoreAsync`, it always does package compatibility verifying which takes a lot of time (even when I know that everything is fine). Is it possible to manually disable all the checks or at least cache the check results somehow?

**Comment by emgarten** [comment]
Runtime asset validation can be turned off. There isn't a way to turn off framework compatibility checks yet, but restore should make this an option that can be turned off in the project.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L29

Are you sure the compat check is the slow down? Care to share any perf numbers?

**Comment by AndreyAkinshin** [comment]
Cool, thanks for the info about `CompatibilityChecker.cs`.

> Are you sure the compat check is the slow down? Care to share any perf numbers?

Right now it takes about 4..8 sec on a medium size solution to perform `RestoreAsync` for cases when we didn't make any changes. I want to do it instantly. =)

I will make a few snapshots tomorrow and share with you the detailed statistics.

**Comment by emgarten** [comment]
NuGet 4.3.0 will persist a cache file to disk and no-op if there haven't been any changes. You should be able to use this also through RestoreAsync.

Here is the spec https://github.com/NuGet/Home/wiki/NuGet-Restore-No-Op

**Comment by AndreyAkinshin** [comment]
@emgarten,
> NuGet 4.3.0 will persist a cache file to disk and no-op if there haven't been any changes.

Is it already available in 4.3.0-beta1-2418?

**Comment by emgarten** [comment]
No, these packages haven't been published to nuget.org yet, and they probably will not be until preview3 for Visual Studio goes out. For reference preview2 still hasn't gone out.

Nightly build packages are on https://dotnet.myget.org/gallery/nuget-build
4.3.0-preview3-4133  and up would have these changes.

**Comment by AndreyAkinshin** [comment]
> 4.3.0-preview3-4133 and up would have these changes.

Thanks, will try it.

**Comment by AndreyAkinshin** [comment]
@emgarten Why the latest version of https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Protocol.Core.Types is `4.3.0-beta2-2463` instead of `4.3.0-preview3-4133`

**Comment by derigel23** [comment]
And the latest version of [NuGet.Client](https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Client) is `4.3.0-preview1-3937`

**Comment by emgarten** [comment]
@derigel23 preview1 is the latest version used by Visual Studio, but you can find higher versions of NuGet n the *nuget-build* feed.

**Comment by derigel23** [comment]
@emgarten Yes, the link I've provided is from nuget-build feed on myget

nuget sources
Registered Sources:

  1.  dotnetV3 [Enabled]
      **https://dotnet.myget.org/F/nuget-build/api/v3/index.json**

nuget list id:"NuGet.Client" -pre
NuGet.Client **4.3.0-preview1-3937**

**Comment by emgarten** [comment]
NuGet.Client was removed in Preview3. Try NuGet.Versioning

**Comment by derigel23** [comment]
@emgarten @AndreyAkinshin And, as I can see by sources, NuGet.Protocol.Core.Types is also dropped in preview3. Big shuffle of packages, right?

**Comment by emgarten** [comment]
NuGet.Protocol.Core.Types and NuGet.Packaging.Core.Types are gone, they've been merged into other packages. 4.3.0 is the first release built with NETCore SDK projects and some long overdue clean up work was done when migrating from xproj.

**Comment by mishra14** [comment]
@derigel23 @AndreyAkinshin please let us know if you are still facing this issue with 4.6.0-preview1 packages on myget.
