### ISSUE TITLE
Advanced RestoreSummary

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#5339]
It would be nice to provide additional diagnostics information in `NuGet.Commands.RestoreSummary`:
* List of installed packages (`result.GetAllInstalled()` instead of `result.GetAllInstalled().Count`)
* A bool flag which indicates that there are any changes in `project.assets.json`

**Comment by emgarten** [comment]
@nkolev92 is it possible to tell from the RestoreSummary when a noop happens with your recent changes?

**Comment by emgarten** [comment]
@AndreyAkinshin would you share a bit more about your scenario and how you using this info? 

More diagnostic info on the result would be helpful, we need some of this within NuGet also since only the restore knows the full graph and what happened, after it is written out as an assets file much of this is lost.

**Comment by AndreyAkinshin** [comment]
I'm working on NuGet support in Rider. We have to detect changes in our project model (which can me affected by changes in `project.assets.json` files) and reload the corresponded projects. Reloading takes some time, so we want to reload only projects which really has project model changes. Right now we read the content of `project.assets.json` files before and after restore; it would be nice if we will get an API which allows getting the list of the affected project automatically.

It would also be nice to have the list of installed packages for advanced diagnostics. Our users often have some NuGet problems (especially on non-Windows OS), the NuGet log is our main way for investigations. It takes some time to understand what's going on with NuGet on user's machine; of course, I can find all the packages in the full log, but it would be much easier to have it in summary.
Also, It would be cool to provide some brief info about restore to a user. Right now we have such feature for classic projects: the notification looks like "5 packages were restored in 2 projects," and the list of these packages and project can be found in the last lines of log. In NetCore projects, we can only provide information about an amount of affected projects, but not about packages. It's just a "nice-to-have" feature; it's hard to implement on the Rider side, but it should be super-easy to do it on the NuGet.Client side.

**Comment by emgarten** [comment]
> Reloading takes some time, so we want to reload only projects which really has project model changes

VS does this by checking the file modified time. Restore checks if the assets file is about to write out is the same as the one on disk and skips updating it to avoid changing the time.

**Comment by nkolev92** [comment]
@emgarten 
Github crashed when i wrote the earlier reply so I guess it didn't post.

I do have a flag in the RestoreResult that specifies No-Op.
There's some more work I want done in that area, but so far there's only a bool there.

**Comment by AndreyAkinshin** [comment]
@emgarten 
> Restore checks if the assets file is about to write out is the same as the one on disk and skips updating it to avoid changing the time.

Good to know, thanks. But still, it would be more convenient to have an API for such list instead of additional checks.

**Comment by AndreyAkinshin** [comment]
@nkolev92,
> I do have a flag in the RestoreResult that specifies No-Op.

Awesome, that's what I need! However, it wasn't obvious to me. =) I'm not sure that there are a lot of users who use this API manually, but probably it makes sense to add a few xml-docs which explain it.

**Comment by nkolev92** [comment]
@AndreyAkinshin 

We have a spec written for the no-op behavior, however it hasn't been updated with the latest design changes from the last few weeks.

I will update the spec today or tomorrow and ping you here with the latest info.
Keep in mind that this feature is being validated currently and might still change though.

**Comment by AndreyAkinshin** [comment]
> I will update the spec today or tomorrow and ping you here with the latest info.

Great, thanks again for your help!
