### ISSUE TITLE
Functional test failure InstallPackageWithUnsupportedReference

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#534]
![ref](https://cloud.githubusercontent.com/assets/1087852/7488317/5f6f48dc-f37d-11e4-9370-129efba85587.PNG)

packages with dll residing in unrecognized framework is still added as reference, where it was not in 2.* versions.

**Comment by danliu** [comment]
assign to Justin as he has most context.

**Comment by emgarten** [comment]
We support sub folders, for example lib\x86\assembly.dll needs to be added here, and x86 is not a valid framework. We should consider removing this test.
