### ISSUE TITLE
Make the "Package source" filter in Manage Packages for Solution work in Installed and Consolidate tabs

### ISSUE THREAD

**Issue by jjanuszkiewicz** [NuGet/Home#5340]
I've originally reported this as a bug on [Developer Community](https://developercommunity.visualstudio.com/content/problem/47258/package-source-filter-in-manage-packages-for-solut.html), but that got closed as "works as designed", so I'm proposing this as a new feature here.

I'd like the "Package source" filter (dropdown) in the Manage Packages for Solution window work in Installed and Consolidate tabs. Currently the selection on that dropdown doesn't affect the displayed packages - packages from all sources are listed.

**Comment by mishra14** [comment]
@jjanuszkiewicz: The Package Source drop down does filter the updates displayed for each installed package.

We will consider if it should filter the installed packages as well. Thanks for your request.

cc: // @rrelyea @emgarten

**Comment by jjanuszkiewicz** [comment]
@mishra14 This is interesting to know. What use case is there behind the current behavior? I imagine it's not very common to have the same package in different feeds (as I think this would be the only case where you'd want to filter available updates for an installed package) - is this to support having a private/company feed with custom private versions of public packages, so limiting just the updates to one source is desired?

My use case is: the rather large multi-repository project I'm working on uses a company-internal package feed which we use to publish contract packages and common functionality. It's very useful to see what internal packages are installed in a solution or project. There are other ways to do it, but only the Manage Packages window has the Source filter and it feels like a natural place to look for such information.

The current behavior of that filter is very confusing, because there are 4 tabs (Browse, Installed, Updates, Consolidate) and on 2 of them the filter affects the list of packages, while on the other 2 it affects only the updates, but not the list of packages. I don't believe this is documented and it's impossible to tell it when looking at the GUI, so at least there could be some text added somewhere in the UI which explains what the filter does in which tab.

BTW thanks for taking the time to reply.

**Comment by mishra14** [comment]
@jjanuszkiewicz 👍 
Thanks for the detailed explanation for your request/bug.

It is the design that the installed tab should always display all the packages installed to the project. Given this baseline for the installed tab, the filters (pre-release checkbox and source drop-down) only affect the updates.

For the browse and updates tabs, the filter can affect the visible list of packages as these is no such baseline to adhere to. 

I understand your request has 2 parts - 

1. Improve the documentation or UI to make it easier for people to understand the behavior.
2. Allow filtering in the installed tab as well.

We can definitely improve the documentation from point 1 and possibly improve the UI. We will consider point 2. Thanks for your request.

**Comment by mishra14** [comment]
@jjanuszkiewicz: I have opened 3 different bugs to track each of the requests/issues separately. I will close this issue out in favor of the new ones. Please follow them to track the progress and feel free to reopen this one if we missed something here. Thanks!

https://github.com/NuGet/Home/issues/5395 - Improve documentation around PM UI
https://github.com/NuGet/Home/issues/5394 - Improve UI on the filters to make the behavior more clear
https://github.com/NuGet/Home/issues/5393 - Allow filtering in installed tab based on package source

**Comment by jjanuszkiewicz** [comment]
@mishra14 Thanks, I will definitely follow these issues.
