### ISSUE TITLE
Dependencies cannot be made framework agnostic

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#5345]
The following explicit dependency:

```
<PackageFile Include="EnvDTE80" Version="8.0.1" Kind="Dependency" />
```

Ends up as a framework-specific dependency, even if the primary output kind is not-framework specific, or even if it's updated to specify `FrameworkSpecific='false'`

**Comment by davidfowl** [comment]
That's probably a good thing. Why does it matter?

**Comment by kzu** [comment]
Because you can totally create dependencies that apply to all TFs :)
