### ISSUE TITLE
Question: Is there a story for Hight DPI icons? I am safe to use them?

### ISSUE THREAD

**Issue by Bartmax** [NuGet/Home#5346]
Is it safe to add a 128 or 256 icon on the package icon setting to account for the nuget website display and ui for high dpi monitors?

I tried and looks likes there are no real *issue* but before moving into mainstream packages I want to ask if there's a story around or any unintended sideeffects for including a bigger dimension as the spec.

Thanks.

**Comment by mstum** [comment]
Hijacking this to ask if Vectors (Safe subset of SVG?) are on some roadmap?

**Comment by nkolev92** [comment]
@anangaur Can you please help here.

**Comment by Bartmax** [comment]
Ping ...

**Comment by anangaur** [comment]
I don't see a problem with either 128 or 256 icons.

**Comment by anangaur** [comment]
@mstum not in our backlog as of now.

**Comment by zivkan** [comment]
closing as a duplicate of https://github.com/NuGet/Home/issues/2519. Please upvote (👍 ) that issue.
