### ISSUE TITLE
NuGet/NuGet.Build.Packaging#128 causes command line build to fail.

### ISSUE THREAD

**Issue by williamb1024** [NuGet/Home#5347]
NuGet/NuGet.Build.Packaging#128 causes command line build to fail.

Target "_SetPropertiesFromCapabilities" in NuGet.Build.Packaging.targets uses the "ProjectReferences" capabilitiy to determine "_GetReferencePackageContentsDependsOn" additions. The "ProjectReferences" capability is only set during a build within Visual Studio.

This leads to BuildPackage complaining that it will build a package that has no content or references. I haven't tested this, but assume that a packaging project with direct content would build successfully but not include referenced projects.

**Comment by kzu** [comment]
Thanks for the fix!
