### ISSUE TITLE
Invoke must be called on a background thread

### ISSUE THREAD

**Issue by gabrielmartini** [NuGet/Home#5348]
Sometimes it works but almost everytime I'm getting error "Invoke must be called on a background thread." when using Package Manager Console to use migrations, other commands are affected too. After this error I can't run other commands at Package manager console

Package Manager Console
V4.2.0.2457

VS 15.2 (26430.12) Enterprise

Windows 10 1703 15063.332

Steps to reproduce:

1.Open VS2017

2.Open Package Manager Console

3.enable-migrations/add-migration/update-database... it gives error "Invoke must be called on a background thread."
after this given error, every command I try returns that the term is not reconized.

**Comment by alpaix** [comment]
@gabrielmartini Thank you for reporting this issue. Will you be able to file a feedback ticket via the Report-a-Problem tool in Visual Studio 2017 at the top-right corner. The tool allows recording repro steps along with attaching screenshots or any other helpful files.

**Comment by gabrielmartini** [comment]
Done.
https://developercommunity.visualstudio.com/content/problem/65296/invoke-must-be-called-on-a-background-thread.html

Thanks! :)

**Comment by 41northstudios** [comment]
I am having the exact same issue.

Package Manager Console 4.2.0.2457

VS 2017 Enterprise 15.2 (26430.6)

EDIT: Confirmed that starting VS as admin allowed me to run the commands with no issues. I then was able to close VS and re-open as the non-admin user and the commands are still working.

Will update if I get more info...

**Comment by gabrielmartini** [comment]
Yeah, sometimes it works as admin, but it's not a fix as for myself the problem disappears (not always) after some time, I mean, after I turn on Windows and wait for, lets say half one our, and the problem is gone, magically.

But it not behave this way everytime.

Try rebooting your machine... other day I did this and the problem reappeared, and sometimes rebooting fix the issue.

**Comment by jeni4** [comment]
I am having the same issue; however, rebooting nor running as admin has not helped my situation yet.  Following.

**Comment by lcshan** [comment]
same here,I got 3 machines, 2 of them are working fine, but they got other versions of VS as well like 2015 and 2013.
the one with problem is a brand new one and just vs 2017, and reboot or admin doesnt really help

**Comment by 41northstudios** [comment]
I can confirm, running as admin is not a consistent fix. The problem had gone away on both of my development PCs and now has returned on one. Rebooting and running as admin do not work.

Here is the full text of the error I get once this problem rears its head:

```
Invoke must be called on a background thread.
add-migration : The term 'add-migration' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ add-migration
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (add-migration:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by alpaix** [comment]
The error is generated by NuGet attempting to execute `init.ps1` scripts for packages installed in a project. It happens when user tries to invoke a command in PMC after pressing <kbd>Enter</kbd>. I noticed the problem occurred more often in earlier builds of Visual Studio. 

Possible workaround would be opening a project with PMC window closed. You'll have to start a new instance of Visual Studio. Also make sure PMC window is closed before closing Visual Studio thus new instance will remember last window layout. In this scenario `init.ps1` scripts will be executed correctly when PMC window is opened for the first time in current Visual Studio session.

Will work on figuring right fix to be shipped with next Visual Studio 2017 release.

**Comment by Stonne** [comment]
Had the same issue in the package management console. My solution was to do the migrations in acmd prompt see link
https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/migrations

**Comment by frontegi** [comment]
Same problem here, really annoying ! Thanks Alpaix for future bugfix and workaround.
However the workaround doesn't work everytime. 
My workaround has been to downgrade the Package **Microsoft.EntityFrameworkCore.Tools** from version **1.1.1** to ver **1.1.0**

**Comment by axedaddy** [comment]
Mine was working, but just started occurring after I installed SQLServer 2016.
I first start the shell then attempt to paste a command in. I found when I paste a cd command into the command line it fails (using right click, paste).  If I type it by hand it worked, here's an example (output right from the start of when I opened package manager console):

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 4.2.0.2457

Type 'get-help NuGet' to see all available NuGet commands.

PM> cd C:\Vaughan\BeautyAxeCore\BeautyAxe.WebUI
Invoke must be called on a background thread.
PM> cd c:\vaughan
PM> cd beautyaxecore
PM> cd beautyaxe.webui
PM> dir


    Directory: C:\vaughan\beautyaxecore\beautyaxe.webui


Mode                LastWriteTime         Length Name                                                                                                                                                 
----                -------------         ------ ----                                                                                                                                                 
d-----         7/5/2017   8:18 PM                bin                                                                                                                                                  
d-----         7/5/2017   8:07 PM                Controllers                                                                                                                                          
d-----         7/6/2017   6:03 PM                Migrations                                                                                                                                           
d-----         7/5/2017   9:39 PM                obj                                                                                                                                                  
d-----         7/5/2017   8:07 PM                Properties                                                                                                                                           
d-----         7/5/2017   8:07 PM                ViewComponents                                                                                                                                       
d-----         7/5/2017   8:07 PM                ViewModels                                                                                                                                           
d-----         7/5/2017   8:07 PM                Views                                                                                                                                                
d-----         7/5/2017   8:07 PM                wwwroot                                                                                                                                              
-a----         7/5/2017   8:07 PM             36 .bowerrc                                                                                                                                             
-a----         7/5/2017   8:07 PM            178 appsettings.Development.json                                                                                                                         
-a----         7/6/2017   8:02 PM           2141 appsettings.json                                                                                                                                     
-a----         7/5/2017   8:07 PM           3194 BeautyAxe.WebUI.csproj                                                                                                                               
-a----         7/5/2017   8:18 PM            257 BeautyAxe.WebUI.csproj.vspscc                                                                                                                        
-a----         7/5/2017   8:07 PM            502 bower.json                                                                                                                                           
-a----         7/5/2017   8:07 PM           1153 bundleconfig.json                                                                                                                                    
-a----         7/5/2017   8:07 PM            738 Program.cs                                                                                                                                           
-a----         7/5/2017  10:35 PM           6617 Startup.cs                                                                                                                                           


PM> dotnet ef migrations add FirstMigration

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.07
Done. To undo this action, use 'ef migrations remove'
PM> dotnet ef database update

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.82
Done.
PM> 

NOTE:  The migration command was right clicked and pasted in, as was the update. Both of which worked that time. . Also note that like others I tried restarting both VS2017 and then restarting the computer after closing the package manager first.  The package manager was opened fresh each time I started VS.  May not be of significance, but may help track this bug down hopefully.

**Comment by alpaix** [comment]
The fix will be available in Preview 4.

**Comment by manuel-ojeda** [comment]
@alpaix I love you.

**Comment by alpaix** [comment]
Thanks everyone for reporting this issue and confirming the workaround and the fix. I'm sorry this bug caused inconvenience to you. We'll be working hard to avoid this in future!

**Comment by jonkerr** [comment]
None of the above workarounds work for me.  Package Manager Console Host Version 4.2.0.2457, VS 2017 Version 15.2 (26430) Release

**Comment by jonkerr** [comment]
Downgraded to Tools 1.1.0 as per some folks instructions.  Closed all instances of VS and deleted packages from c:\users\my_name\.nuget\packages\microsoft.entityframework.*

After restarting VS and reloading project with PMC minimized (auto package restore turned on) I see both 1.1.0 and 1.1.1 packages under microsoft.entityframeworkcore.tools  Is there some other dependency that's preventing me from downgrade?

After opening PMC, I now get the "microsoft.entityframeworkcore.tools\1.1.1\tools\init.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again." error again for both 1.1.1 and now 1.1.0 as well.

I really need to get these migrations created asap.  Please help.

**Comment by jonkerr** [comment]
Got a preview version of 15.3.  
Loaded project
Opened PMC
Same error: ..\tools\init.ps1:String) [], CommandNotFoundException

**Comment by alpaix** [comment]
Make sure restore is done. In certain rare cases it takes longer than usual. If that's the case next attempt to run a command in PMC should succeed.

**Comment by alpaix** [comment]
Also as the error message is different it must be a different issue. I'd suggest you to file a feedback ticket via the [Report-a-problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool. So that we could address your problem separately.
