### ISSUE TITLE
How to use IgnoreDependencies option from MAC machine

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#5351]
I have used the Xamarin.Forms NuGet package as a dependent NuGet package for my custom NuGet package. I need to ignore this dependent package in some situation in my Xamarin application. I have used the IgnoreDependecies option to achieve this in Windows machine. But, Package installation failed while using the IgnoreDependencies option in MAC machines. 

Is there any option to ignore the dependencies of the package in MAC machines?

Please suggest the solution to use the IgnoreDependencies in MAC machine.

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Please suggest the solution to use the IgnoreDependencies in Xamarin studio mac.

**Comment by mishra14** [comment]
Hey @GanesanRengasamy. What did you use while creating your custom NuGet package?
