### ISSUE TITLE
Nominations for auto restore don't come in for multi-tfm projects

### ISSUE THREAD

**Issue by JoyceLiang** [NuGet/Home#5355]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS NuGet Package Manager

NuGet version (x.x.x.xxx): 4.3.0

dotnet.exe --version (if appropriate): 2.0.0-preview1-005977

VS version (if appropriate): 15.3 Preview 3.0 [26604.2.d15prerel]

OS version (i.e. win10 v1607 (14393.321)): Win 10 Pro

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1. Create a .Net Core Console app

2. Update the csproj file, make this project target to multiple frameworks, add reference to nugget package WindowsAzure.Storage
[project file in attach]

Expected
Build this project, nuget manager can solve the dependency and download all missing package automatically.

Actually
Build fail due to missing assembly references.

When I run msbuild /t:restore from developer command prompt, all missing package is downloaded correctly.

[ConsoleApp10.zip](https://github.com/NuGet/Home/files/1056449/ConsoleApp10.zip)

**Comment by emgarten** [comment]
There is an issue in some 15.3 preview3 builds where projects with multiple frameworks are not auto restored. Does this work when using ``TargetFramework`` singular?

**Comment by JoyceLiang** [comment]
Yes, target to singular framework works fine. 
So the multiple frameworks is a known issue, which release will take the fix?
