### ISSUE TITLE
It is not possible to pack multiple projects into one NuGet package

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5360]
_From @quarion on May 29, 2017 13:34_

## Steps to reproduce

Using VS 2017 and new .csproj format

1. Create CommonLib.csproj project, it should not be published as NuGet package.
2. Create ProjectA.csproj project, it should be published as NuGet package.
3. Add project reference from ProjectA to CommonLib.
4. Pack the ProjectA (with Visual Studio or CLI).

## Expected  behavior

ProjectA.nupkg is created. It contains ProjectA.dll and CommonLib.dll.

## Actual behavior

ProjectA.nupkg is created. It contains only ProjectA.dll. CommonLib is added as a NuGet dependency.

## Additional info

I have tried to add `<IsPackable>false</IsPackable>` property to the CommonLib.csproj, but it is not take into the consideration.

## Environment data
`dotnet --info` output:
NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1

_Copied from original issue: dotnet/cli#6707_

**Comment by nguerrera** [comment]
_From @Patrickkk on June 2, 2017 7:48_

While it would probably be nice to have (especially for legacy stuff). 
Isn't it a bit strange that there are 2 projects when it is distributed as 1 package? Unless there are some external factors into play forcing you to separate shouldn't  it simply be 1 project since it is distributed as 1 package?

**Comment by nguerrera** [comment]
_From @quarion on June 2, 2017 8:42_

Yes, that is definitely possible to just merge the two projects together, and this is a workaround that I will use.

But I would imagine, that there might be some valid scenarios similar to this one:

CommonLib.csproj <- this provide no value on its own, so it should not be published.
ProjectA.csproj <- Published as NuGet. Refers CommonLib, so it would need to contain it as part of the package.
ProjectB.csproj <- Published as NuGet. Refers CommonLib, so it would need to contain it as part of the packages.

**Comment by mishra14** [comment]
ping: @emgarten  @rohit21agrawal

**Comment by rohit21agrawal** [comment]
Closing as duplicate of : https://github.com/NuGet/Home/issues/3891

**Comment by greatkeke** [comment]
I wonder if it will be possible to pack multiple projects into one NuGet package?

**Comment by jangix** [comment]
My solution:
1. Create package from A.csproj
2. Create package from Common.csproj
3. Open A.nupkg and Common.nupkg with 7zip
4. Copy Common.lib from Common.nupkg to the same folder of the A.nupkg
5. From Common.nuspec file copy dipendecies nodes and merge with same nodes of the A.nuspec
6. Delete Common.nupkg and push customized A.nupkg to the your repository.

**Comment by AraHaan** [comment]
Another solution: nupkg is just another zip file so just generate it with a tool you make instead.

**Comment by daiplusplus** [comment]
@jangix  Can you post an example input and output `.nuspec` files? I'm having trouble reproducing your steps.
