### ISSUE TITLE
dev15 E2E failures for Init script execution scenarios

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5365]
Currently on dev15 E2E the following test seems to be failing across multiple runs - 

NetCoreWebAppExecuteInitScriptsOnlyOnce

Ref- http://nugetci/viewLog.html?buildId=100251&tab=buildResultsDiv&buildTypeId=EndToEndTests_Vs15EndToEndTests

**Comment by mishra14** [comment]
Dev15 tests seem to be hanging at some point on d15prerel VS on the test machine. The call stack for the hang does not have NuGet, so I am trying to find the right people in ProjectSystems for it.

**Comment by jainaashish** [comment]
This is because of this issue# https://github.com/NuGet/Home/issues/5381 and this test will be fixed once I merge this PR.

**Comment by mishra14** [comment]
Seems fixed.
