### ISSUE TITLE
Allow packages to contribute to cross-targeting build

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#5367]
With the increasing usefulness of cross targeting, comes the usefulness to extend it too 
via nuget packages. 

At the moment, in cross targeting scenarios, nuget restore will simply create an import for 
props/targets under the package's `build` folder, conditioned to the values in TargetFrameworks 
and nothing more. This means that nuget packages cannot participate in the `outer` build. 

How about introducing a new top-level folder named `buildCrossTargeting` (to follow the 
SDKs convention) that is imported conditionally on `TargetFrameworks != '' and TargetFramework == ''`,
which is [the condition for IsCrossTargeting](https://github.com/Microsoft/msbuild/blob/master/src/Tasks/Microsoft.CSharp.targets#L24-L26) on the built-in targets?

**Comment by nguerrera** [comment]
This is already implemented and works exactly how you want. ;)

**Comment by emgarten** [comment]
As @nguerrera said 😄

**Comment by mishra14** [comment]
Closing as already implemented.

@kzu : Feel free to reopen this in case your scenario is not covered.

**Comment by kzu** [comment]
Sigh, some docs on it would have been great ;).I Isearched nuget.client repo for any traces of the string `buildCrossTargeting` and found nothing, and assumed it wasn't supported therefore :(

**Comment by emgarten** [comment]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/ContentModel/ManagedCodeConventions.cs#L482-L485

*buildCrossTargeting* is the deprecated name, *buildMultiTargeting* is the official name

**Comment by kzu** [comment]
Makes sense.

Thanks!
