### ISSUE TITLE
NullReferenceException when trying to create a simple package

### ISSUE THREAD

**Issue by bartoszkp** [NuGet/Home#5368]
I'm using NuGet.exe Version: 4.3.0.0 (I've tested also previous version: 4.1 and 3.5 - the same problem exists) on Windows 8.

All I want is to have a csproj file to define some properties shared between the nuspec file and the Targets file, that is the main content of my package. This however fails with a NRE. MVCE follows (with irrelevant parts such as the mentioned properties, the Targets file and contents of the build and tools directories omitted).

1. Create a Package.csproj:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="Build">
    <MakeDir Directories="NuGetTest\bin" />  <!-- without this complains about a missing bin folder, doesn't matter whether empty or not -->
  </Target>
</Project>
```

2. Create a corresponding Package.nuspec file:
```
<?xml version="1.0"?>
<package>
  <metadata>
    <id>Test</id>
    <version>1.0.0</version>
    <authors>BartoszKP</authors>
    <description>MVCE for a NRE bug in NuGet</description>
  </metadata>
  <files>  <!-- Doesn't matter whether empty or not -->
  </files>
</package>
```

3. Run command: `nuget.exe pack Package.csproj -Build -ForceEnglishOutput -Verbosity detailed`

Result:

> NuGet Version: 4.3.0.0
> Attempting to build package from 'Package.csproj'.
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 2017-06-08 14:37:14.
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.02
> Packing files from 'C:\Users\bartoszp\Documents\Cs\NuGetTest\NuGetTest\bin'.
> Using 'Package.nuspec' for metadata.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at NuGet.CommandLine.ProjectFactory.AddDependencies(Dictionary`2 packagesAndDependencies)
>    at NuGet.CommandLine.ProjectFactory.ProcessDependencies(PackageBuilder builder)
>    at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
>    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
>    at NuGet.CommandLine.PackCommand.ExecuteCommand()
>    at NuGet.CommandLine.Command.ExecuteCommandAsync()
>    at NuGet.CommandLine.Command.Execute()
>    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

[NuGetTest.zip](https://github.com/NuGet/Home/files/1060999/NuGetTest.zip)

**Comment by viceice** [comment]
It seems to be https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L967 is the line, which is throwing the exception.

The property TargetFramework is null.

**Comment by viceice** [comment]
Adding `<TargetFrameworkMoniker>.NETFramework,Version=v2.0</TargetFrameworkMoniker>` helps

**Comment by bartoszkp** [comment]
@ViceIce Thanks, I'll try that next time when trying to go from nuspec packing to csproj packing :-) The NRE still shouldn't be getting its way out of the application IMHO ;)

**Comment by mishra14** [comment]
Please let us know if you are still blocked.

**Comment by bartoszkp** [comment]
Hi @mishra14. No, I'm not blocked anymore. I'm not developing this part anymore, and as far as I remember the workaround posted above worked for me.
