### ISSUE TITLE
Functional test failures - Improve the messages of the resolver/gather

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#537]
Failed SubTreeUpdateWithConflict Expected <Updating 'C 1.0' to 'C 2.0' failed. Unable to find a version of 'G' that is compatible with 'C 2.0'.> but got <Unable to satisfy package dependency constraints.>. At update.ps1: line 336

Failed UpdateScenariosWithConstraints Missing dependency information for package: A

Failed UpdatePackageWithDependentsThatHaveNoAvailableUpdatesThrows Expected <Updating 'B 1.0' to 'B 2.0' failed. Unable to find a version of 'A' that is compatible with 'B 2.0'.> but got <Already referencing a newer version of 'A'..>. At update.ps1: line 800

Failed UpdatePackageDoesNothingIfNewVersionLessThanInstalledPrereleaseVersion Already referencing a newer version of 'PreReleaseTestPackage'..

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.VisualStudioExtension@79705888d4a18fc829dc6ad69f3a58ea1e3ec050
