### ISSUE TITLE
msbuild /t:Restore on sln with a Microsoft.NET.Sdk.Web project.

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5372]
_From @dazinator on June 7, 2017 14:1_

In my vs2017 solution, I have multiple csproj files, most of them use `Microsoft.NET.Sdk` but the web site uses `Microsoft.NET.Sdk.Web`.

When I do an `msbuild /t:Restore` on the solution file, only the projects consuming `Microsoft.NET.Sdk` are restored, the website project consuming `Microsoft.NET.Sdk.Web` appears to be ignored. There is no warning about this, I just couldn't see the project listed anywhere in the build output. This then results in an msbuild /t:Build on the sln failing, as that does attempt to build the project, but it's dependencies were not restored.

_Copied from original issue: dotnet/sdk#1314_

**Comment by emgarten** [comment]
@dazinator I'm not able to repro this. Could you share a simple repro or repository where you are seeing this?

**Steps**
1. Create a NETCore Web API project in VS 2017 15.2
1. Add a netstandard class library
1. msbuild /t:restore <solution path>

Both projects are restored.

Does it work if you restore a web project directly? What output is displayed when restoring a web project directly?

**Comment by emgarten** [comment]
@dazinator please ping this issue if you are still seeing this problem and have a repository I can try reproing this in. Thanks!

**Comment by dazinator** [comment]
Sorry, I haven't had time to put together a repro for this yet. My current build process restores the sln file, and I then have to do another restore on the project file that is missed. If I am the only one seeing this I think I'll leave this for now. If it happens with any more solutions i'll try and create a repro for you. Cheers.
