### ISSUE TITLE
Setting the default value of Description property doesn't work well with GenerateAssemblyInfo task 

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#5374]
_From @tmat on June 8, 2017 19:48_

```NuGet.Build.Tasks.Pack.targets``` sets the default value of Description property to "Package Description":

```xml
    <Description Condition="'$(Description)'==''">Package Description</Description>
```

If the project doesn't set Description this default value ends up in its AssemblyDescriptionAttribute:

```xml
<AssemblyAttribute Include="System.Reflection.AssemblyDescriptionAttribute" Condition="'$(Description)' != '' and '$(GenerateAssemblyDescriptionAttribute)' == 'true'">
```

I propose changing the line
```xml
    <Description Condition="'$(Description)'==''">Package Description</Description>
```

to 
```xml
    <PackageDescription Condition="'$(PackageDescription)'==''">$(Description)</PackageDescription>
    <PackageDescription Condition="'$(PackageDescription)'==''">Package Description</PackageDescription>
```

and then use PackageDescription in Pack task to avoid the collision.

_Copied from original issue: Microsoft/msbuild#2202_

**Comment by rainersigwald** [comment]
Sounds like a good change to me. @rohit21agrawal ?

**Comment by rohit21agrawal** [comment]
sounds good. i'll make this change for 4.4

**Comment by rohit21agrawal** [comment]
@rainersigwald does the project set a default value of $(Description) ?

**Comment by rainersigwald** [comment]
@rohit21agrawal not that I can see: https://github.com/dotnet/sdk/search?l=XML&q=description&type=&utf8=%E2%9C%93

(but I'm not the OP, I just moved this bug to the right repo)
