### ISSUE TITLE
Pack targets miss library layout files with UWP 

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#5379]
The pack targets aren't automatically including required output of UWP class libraries that contain UI controls.

To repro:
Clone https://github.com/xunit/devices.xunit
checkout commit 3aeb67d7092bfd8f91dd5afe88dd9e27023b5239 
Try to build/pack https://github.com/xunit/devices.xunit/blob/3aeb67d7092bfd8f91dd5afe88dd9e27023b5239/src/xunit.runner.devices/xunit.runner.devices.csproj

the generated nupkg is missing the folder that needs to be along side the dlls -- it's of the same name as the assembly.

So \lib\uap10.0\xunit.runner.devices.dll should have a directory \lib\uap10.0\xunit.runner.devices. This directory exists in the output directory and needs to be included as-is.

This is with 15.3 preview 2

**Comment by rohit21agrawal** [comment]
ideally the UWP targets should add all project outputs to the BuiltProjectGroupOutputGroup so that it gets picked up by pack automatically.

@onovotny let me know if you need a workaround for this.

**Comment by clairernovotny** [comment]
Here's the fix:

https://github.com/onovotny/MSBuildSdkExtras/blob/master/src/build/platforms/Windows.targets#L54-L66

There is a different output group and set of items that can be triggered. And I had to use the lowest-level extension point because the easier one didn't work. #5810

**Comment by mishra14** [comment]
Closing in favor of an [internal issue](https://microsoft.visualstudio.com/OS/_workitems?id=13740952&fullScreen=false&_a=edit) on UWP team.
