### ISSUE TITLE
NuGet.VisualStudio.dll cannot be referenced from Dev12

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#538]
Referencing the current NuGet.VisualStudio.dll from a project in Dev12 produces compiler errors about duplicate types. From Dev14 it compiles without issues.

The older package from mid-March works fine in Dev12:
https://www.myget.org/feed/nuget-volatile/package/nuget/NuGet.VisualStudio

We should find what changed with the assembly or how it was built that causes this.

**Comment by yishaigalatzer** [comment]
Are we sure this is a bug?

**Comment by emgarten** [comment]
I'm not sure, it is just very strange behavior. It doesn't appear related to the NuGet APIs themselves, just with how the assembly is consumed. Other users may hit this once the RTM package for NuGet.VisualStudio.dll is pushed to nuget.org.

**Comment by johnataylor** [comment]
The work here is to limit this package to only interfaces and remove all implementation. This is root cause of this issue.
