### ISSUE TITLE
Not able to install System.Runtime.Serialization.Json and System.Runtime.Serialization.Xml both in a project

### ISSUE THREAD

**Issue by arpit-nagar** [NuGet/Home#5388]
Don't know if this is a right place for this issue.
Please redirect or transfer issue in respective project.

I have visual studio 17. My project is targeting net461 and netstandard1.6
I want to use System.Runtime.Serialization.Json and System.Runtime.Serialization.Xml. but I am facing issues.

Steps to reproduce:
1. Install nuget System.Runtime.Serialization.Xml - 4.3.0
2. Now install nuget System.Runtime.Serialization.Json - 4.3.0

But when I am trying step 2 it uninstall  System.Runtime.Serialization.Xml .
How to use both nuget in code.

![capture](https://user-images.githubusercontent.com/16220515/27013697-b38d5698-4f06-11e7-8f78-1bde87a1e1d1.JPG)

**Comment by emgarten** [comment]
I wasn't able to repro this using Visual Studio 15.2 (2017)

I tried:
1. Create a new netstandard class library
1. Edit target frameworks to include net461 and netstandard1.6
1. Install System.Runtime.Serialization.Xml - 4.3.0 using the nuget UI
1. Install System.Runtime.Serialization.Json - 4.3.0 using the nuget UI

My resulting csproj file is:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net461;netstandard1.6</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Serialization.Xml" Version="4.3.0" />
  </ItemGroup>

</Project>
```

@arpit-nagar could you share additional repro steps? Does manually changing the csproj to what I have above work for you?
