### ISSUE TITLE
How to identify package feed url?

### ISSUE THREAD

**Issue by leaderanalytics** [NuGet/Home#5389]
Given I have 
/feed1
/feed2

configured in Visual Studio and I have 

    <package id="Package" version="1.0.11" targetFramework="net47" />

in packages.config - OR -

     <Reference Include="Package, Version=0.17.2.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\Package\lib\netstandard1.2\Package.dll</HintPath>
    </Reference>

Please tell me how I can tell if "Package" was downloaded from /feed1 or /feed2.
More generally - How do I find the feed url for a given package?

Edit:
I've seen [this document](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file) and I'm still not clear.

Thanks

**Comment by emgarten** [comment]
The location package was downloaded from is not persisted on disk. Packages should be unique on id and version alone, which means, *Package 1.0.0* should be identical on both feed1 and feed2. Scenarios where the same version is different between feeds is not supported.

**Comment by leaderanalytics** [comment]
@emgarten  Thanks Justin, my question really relates to knowing which feed to download from versus versioning.  I have certain packages that exist on one feed only.  So I suppose the only approach is to start with the first feed and keep trying till it works.

**Comment by emgarten** [comment]
> I suppose the only approach is to start with the first feed and keep trying till it works.

Yes, this is how restore handles it also. Each feed is checked for the package until it is found.

**Comment by mishra14** [comment]
@leaderanalytics Please let us know if you are still blocked.
