### ISSUE TITLE
Docs: Documentation on NuGet PM UI should have information about the tabs and filters

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5395]
Original Customer request: https://github.com/NuGet/Home/issues/5340

Currently our documentation on NuGet PM UI for VS does not contain any information about the the 4 tabs (purpose and default behavior) and more importantly the effects of the filters (pre-release checkbox and the Package Source drop down) on each of the tabs. More details in the original bug.

We should have some documentation to make it easier for users to understand the default behavior.

**Comment by mishra14** [comment]
tagging PM team for visibity: @anangaur @karann-msft @kraigb

**Comment by karann-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #455](https://github.com/NuGet/docs.microsoft.com-nuget/issues/455) via [**ZenHub**](https://www.zenhub.com/)
