### ISSUE TITLE
Question: Does NuGet use the stored credentials for feeds on a file share

### ISSUE THREAD

**Issue by pvandervelde** [NuGet/Home#5398]
## Details about Problem

using nuget.exe 4.0.0.2283 on Windows Server 2016

I'm trying to restore NuGet packages on a Windows machine which is not attached to the company Active Directory. After adding the feeds and their credentials the nuget.config for the user looks like:

	<?xml version="1.0" encoding="utf-8"?>
	<configuration>
	  <packageRestore>
		<add key="enabled" value="True" />
		<add key="automatic" value="True" />
	  </packageRestore>
	  <packageSources>
		<add key="CompanyFeed1" value="http://server1.company.com" />
		<add key="CompanyFeed2" value="\\server2.company.com\nuget" />
	  </packageSources>
	  <disabledPackageSources>
		<add key="nuget.org" value="https://www.nuget.org/api/v2/" />
	  </disabledPackageSources>
	  <packageSourceCredentials>
		<CompanyFeed1>
		  <add key="Username" value="DOMAIN\SomeDomainUser" />
		  <add key="Password" value="Encrypted_Password_for_SomeDomainUser" />
		</CompanyFeed1>
		<CompanyFeed2>
		  <add key="Username" value="DOMAIN\SomeDomainUser" />
		  <add key="Password" value="Encrypted_Password_for_SomeDomainUser" />
		</CompanyFeed2>
	  </packageSourceCredentials>
	</configuration>

The following works

    nuget install MyPackage -Source http://server1.company.com

But this does not

    nuget install MyPackage -Source \\server2.company.com\nuget

Even though both feeds have at least one version of the `MyPackage` package.

Executing both commands from a computer on the Active Directory works just fine.

The verbose output is:

    NuGet Version: 4.0.0.2283
    Feeds used:
      \\server2.company.com\nuget

    System.AggregateException: One or more errors occurred. ---> NuGet.CommandLine.CommandLineException: Unable to find package 'MyPackage'
       at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at NuGet.CommandLine.Command.Execute()
       at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
    ---> (Inner Exception #0) NuGet.CommandLine.CommandLineException: Unable to find package 'MyPackage'
       at NuGet.CommandLine.InstallCommand.<InstallPackage>d__30.MoveNext()<---

From this I'm assuming that NuGet does not deal with 'local' directories that need password authentication. If this is the case how can we access a NuGet feed on a UNC file share. Unfortunately we cannot use a HTTP server for this feed.

**Comment by emgarten** [comment]
NuGet does not use credentials for local folders or network shares. Credentials are only handled for HTTP sources.

This is an interesting scenario, do you have an example of how credentials could be provided in your scenario? How is your share hosted?

Here is the folder reader in NuGet for reference: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs

**Comment by pvandervelde** [comment]
The scenario is this:

We have 2 private NuGet feeds, one is an HTTP one (currently an instance of https://github.com/themotleyfool/Klondike) which contains both the final version of our internal packages and mirrored packages from nuget.org. The second one is on a Windows file share.

The feed on the file share is used during development of our NuGet packages. Because NuGet doesn't cache packages from the file share we can overwrite a package in the file share with a new version. This allows us to implement, test and patch the code in the package before locking it down and releasing it. Once it has been released (and pushed to the HTTP nuget feed) any changes will be done in a new version of the package as per normal.
And yes we know about pre-release versions, however due to the way our source code is set up we need to update all versions of the nuget package in one go, a process that can take upto 3 hours, thereby making pre-release versions not usable in our case.

The share is hosted as a standard Windows file share on a computer that is attached to the company Active Directory. The whole development team has read permissions on that file share and the build servers have write permissions to the file share.

One of our current goals is to disconnect the build agents from the active directory so that we can start moving our builds to single-use containers / VMs. However if the build agent is not on the Active Directory then the access to the file share requires that NuGet provides credentials. I'm not sure how NuGet would pass the credentials on. I have added the credentials to the nuget.config file but like you said those are not used. 

If I connect to the file share via Windows explorer it asks me for the credentials so there must be a way to pass said credentials but I haven't looked into how this might work.

Note that the UNC file shares are our way to get around the fact that we cannot turn off caching in NuGet. If we would be able to do that we could make our development/test feed not cache and we would be able to use an HTTP feed. Until that is possible we'll be happy to work with UNC shares though.

**Comment by emgarten** [comment]
Are you able to mount the share to a local drive using ``net use`` or ``substr`` first and authorizing there? You could point NuGet at that folder path afterwards.

Updating dependencies during development has been made easier in VS 2015 with project.json and VS 2017 with PackageReferences, both of these allow floating versions and can allow you to take the highest package version each time you restore. If that is an option for you I recommend checking it out.

**Comment by pvandervelde** [comment]
I'll try the `net use` / `substr` approach.

As for `project.json` / `PackageReferences` that won't help us much because we have to support a number of versions of our software so we don't necessarily want to take the latest version :( 
We might have a look to see if we can add a configuration option to NuGet to turn off caching selectively.

**Comment by altinoren** [comment]
Here's our use case.

At a client, we're using a UNC share in local domain to `nuget init` from one project and to `nuget restore` from another. We're moving the consumer project to Azure through Team Services CI/CD scenario and wanted to move the local nuget drop folder to an Azure File Share so that custom packages can be restored during Team Services build.

We already have the UNC path working during restore, defined in `nuget.config` as a package source. Documentation mentions `packageSourceCredentials` for package sources, so we assumed the same credentials work for UNC `packageSources` entries, but it appears not to be the case.

Supporting UNC credentials for both `init` and `restore` would be helpful.

**Comment by emgarten** [comment]
@altinoren using Azure File Share to host packages sounds like a great idea.

The problem for both this and other network shares is, NuGet is accessing them through calls such as `File.Open` and `File.Exists`, there isn't a way to pass credentials to these calls like HTTP.

If there is a simple way to enable support for this in nuget.exe I'd be happy to investigate.

For now with Azure File Shares it looks like the best approach is to map the share in windows and provide credentials, then use it is as a normal share. 
https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-use-files-windows

Giving nuget native support for dealing with password protected shares and rebuilding the support windows has doesn't seem like the right approach but I'm open to suggestions here.
