### ISSUE TITLE
Add 'list' command to NuGet.CommandLine.XPlat

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#5402]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe

NuGet version (x.x.x.xxx):
4.3.0.2418

dotnet.exe --version (if appropriate):
2.0.0-preview1-005977

VS version (if appropriate):
N/A

OS version (i.e. win10 v1607 (14393.321)):
win10 v1703 (15063.296)

Worked before? If so, with which NuGet version:
Worked with nuget.exe

## Detailed repro steps so we can see the same problem

1. Run dotnet nuget list

Expect: be able to list nuget packages from a source.

Actual: `error: Unrecognized command or argument 'list'`

**Comment by emgarten** [comment]
@nkolev92 is there anything preventing this from working xplat now that you updated the list command for nuget.exe?

**Comment by nkolev92** [comment]
The list APIs are cross-plat so I think the only work required is hooking it up.

**Comment by mishra14** [comment]
@nkolev92 can you please dupe this out.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6060
