### ISSUE TITLE
NU1201 Does Not Produce a Library Id

### ISSUE THREAD

**Issue by natidea** [NuGet/Home#5405]
Warning NU1201 Project is not compatible with [targetframework], does not produce a LibraryId pointing to the project reference that is broken. Hence there is no way to attach the resulting diagnostic to the dependencies tree in the solution explorer.

NuGet version: 4.3.0-preview3-4146

Tracking as part of https://github.com/dotnet/project-system/issues/2436

/cc @emgarten @mishra14

**Comment by mishra14** [comment]
Issue could be here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L96

Talking with @emgarten on this.

**Comment by rrelyea** [comment]
approved
