### ISSUE TITLE
Regression: msbuild /t:pack fails with `The file '' to be packed was not found on disk.`

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5408]
**Repro machine**: d15rel 26612.0

This regressed since 15.2 and earlier 15.3 previews.

Execute these commands in a VS2017 Developer Prompt:

```
git clone -b v15.3 https://github.com/Microsoft/vs-mef
cd vs-mef\src
msbuild /t:restore
msbuild /t:pack
```

**Expected**

A successful build with two output packages

**Actual**

```
  Multilingual App Toolkit v4.0.6810.0
  Multilingual App Toolkit build started.
  Multilingual App Toolkit build completed successfully. (515 ms)
  Microsoft.VisualStudio.Composition.LocalizationShell -> C:\git\mef\bin\Microsoft.VisualStudio.Composition.Localizatio
  nShell\Debug\netstandard1.0\Microsoft.VisualStudio.Composition.LocalizationShell.dll
  Microsoft.VisualStudio.Composition -> C:\git\mef\bin\Microsoft.VisualStudio.Composition\Debug\net45\Microsoft.VisualStudio.Composition.dll
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(141,5): error : The file '' to be packed was not found on disk. [C:\git\mef\src\Microsoft.VisualStudio.Composition\Microsoft.VisualStudio.Composition.csproj]
```

> C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(141,5): error : The file '' to be packed was not found on disk.

**Comment by rohit21agrawal** [comment]
@AArnott none of your *.resources.dll have "FinalOutputPath" metadata set on them which is something msbuild always does on all project outputs, and Pack relies on this metadata to figure out the source location for a file.

**Comment by AArnott** [comment]
Thanks. I already made a fix to our MicroBuild.Plugins.Localization package to set `FinalOutputPath` to accomodate your change. I just wasn't using the latest version of that package on my box. Thanks for pointing that out.

IMO, if you are adding a dependency on this metadata, it should be a soft dependency to avoid a breaking change in an Update. For example, you could ignore items that are missing that metadata. Or assume the item name is the path you should use if the metadata is not present (my personal favorite). Otherwise, please consider adding an explicit error message explaining the problem when it occurs, since the error message I was getting isn't helpful and looks like a bug in the .targets.

Thanks.

**Comment by AArnott** [comment]
Actually I take that back. I'm using the latest localization plugin that sets that metadata and I'm still seeing the error. Let me investigate a bit more...

**Comment by AArnott** [comment]
Oh, gosh. I totally forgot: this project doesn't even using the MicroBuild localization package. This is straight up .NET .targets. So to your point:

>  none of your *.resources.dll have "FinalOutputPath" metadata set on them which is something msbuild always does on all project outputs

Why do you say MSBuild always does this, and what do suppose is different about my projects that would suppress this metadata? When I look at the diagnostic build log, I don't see the metadata that you say is required and "always there" on the satellite assemblies:

![image](https://user-images.githubusercontent.com/3548/27154316-781bdb70-5109-11e7-8d3d-3870cd57c9b9.png)

**Comment by rohit21agrawal** [comment]
@rainersigwald are satellite assemblies not supposed to have "FinalOutputPath" metadata or is this something that recently changed?
The original identity has path that comes from the obj folder so i don't want to be using that.

**Comment by AArnott** [comment]
Whatever you do, @rohit21agrawal, don't guess what the path should be. It's far better to use the `obj` path than make up a bin path that isn't given in the item metadata. 
I agree that at least sometimes `FinalOutputPath` metadata may be present and it's fine IMO to use it when it's present. But if it isn't, using the identity of the item itself seems perfectly reasonable.

I'm happy to hear what @rainersigwald has to say though, of course.

**Comment by rohit21agrawal** [comment]
@AArnott  had a chat with @rainersigwald about this, and msbuild does infact set this metadata:
https://github.com/Microsoft/msbuild/blob/vs15.3/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5500

Is there anything in your project that is touching the SatelliteProjectGroupOutputGroup?

**Comment by AArnott** [comment]
Yes, I see MSBuild's .targets file sets that metadata. But that is irrelevant (unfortunately) because that MSBuild target is overridden by another .targets file that last I checked is very commonly imported by projects implicitly:
See this log message from my build:

>  Overriding target "SatelliteDllsProjectOutputGroup" in project "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets" with target "SatelliteDllsProjectOutputGroup" from project "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets".

Needless to say, this overriding target does *not* contain the new metadata that you require. And servicing it in .NET Framework, while it may be an option, may be much harder than alternatives, including: 

1. stop importing the file from .NET Framework. Instead import one that ships with VS so we can service it more frequently.
1. stop importing the Microsoft.WinFx.targets file period. I don't know what it buys us. 
1. Stop depending on the metadata.

**Comment by rohit21agrawal** [comment]
why are Microsoft.WinFx.targets being imported? AFAIK, those targets are meant to be imported in legacy projects, which dotnet pack doesn't actually support. Can you do a pre-processor to see what is causing the file to be imported?

@livarcocc @dsplaisted do net core SDK projects have any dependency on Microsoft.WinFx.targets ?

**Comment by rainersigwald** [comment]
@rohit21agrawal It's imported for all `msbuild.exe` driven builds (`dotnet msbuild` invocations skip it and don't hit problems, apparently). Clarified this in https://github.com/Microsoft/msbuild/issues/2223#issuecomment-308836945.

Fixes to the real problem in MSBuild are pretty scary at this point in the cycle, because no one deeply understands the full implications of the change and we wouldn't have much time for beta feedback.

In addition, that would only help for this specific situation--users could have arbitrarily overwritten the target themselves.

I think changing the Pack task to use `%(FinalOutputPath)` but fall back to `%(Identity)` if it's not present is probably the best short-to-medium-term solution, since it gives robustness to a variety of situations.

**Comment by AArnott** [comment]
Please re-open this issue as it repros with d15rel 26711.00

I'm afraid this bug isn't fixed yet as shown in this trivial repro: https://github.com/AArnott/ReproNuGet5408/tree/master/ReproNuGet5408

Repro Steps:
1. Create a .NET Standard class library.
1. Change target framework to net45
1. Add a resources.resx and resources.es.resx file
1. Pack the library (from the command line if necessary to workaround an up-to-date check bug in VS)

I wonder if the item identity (or its name) is not metadata on the item. It may only be available via the `EvaluatedInclude` property on the item object itself (or in your terms, the [IMSBuildItem.Identity property](https://github.com/NuGet/NuGet.Client/blob/e8baa66689677bd8bd99900edf801c57fdb2704f/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/IMSBuildItem.cs#L16)).

**Comment by rohit21agrawal** [comment]
@rainersigwald we decided to implement the fallback behavior to %(Identity) as per your suggestion but turns out satellite dlls don't even have identity set for msbuild.exe driven builds. Do you know if this is expected?

**Comment by AArnott** [comment]
I wasn't talking about the `%(Identity)` property. I was talking about the item identity (i.e. the item name or EvaluatedInclude). The MSBuild docs on MSDN suggest that this value also appears as Identity metadata but I can't confirm that that actually happens and this failure suggests it doesn't.

**Comment by dsplaisted** [comment]
I would guess that `Identity` is special metadata that can be accessed as metadata from MSBuild XML code (`%(Compile.Identity)`, for example), but not via the MSBuild APIs that allow you to access metadata on an item.  To get this value via the APIs, you probably need to use the `EvaluatedInclude` property as @AArnott suggests.

**Comment by rohit21agrawal** [comment]
@AArnott i just verified that the fix i made was correct, and the error is because dotnet core sdk is resolving to an older version of the pack sdk. if you look at the log for nguet.build.tasks.pack.targets, its being read from "C:\Program Files\dotnet\sdk\2.0.0-preview2-006502\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets"  (or whatever version you have installed on your machine) and the corresponding sdk has nuget version 4.3.0-preview3-4168 which doesn't have my fix.

**Comment by rainersigwald** [comment]
To be clear on the MSBuild OM aspects of this:

* `Identity` is a [well-known item metadatum](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata). It is available for every item and is

> The item specified in the `Include` attribute.

* You can access well-known metadata in all the usual ways, including transforms `@(ItemName->'%(Identity)')` and through the OM `item.GetMetadata("Identity")`.
