### ISSUE TITLE
Nuget.CommandLine Assembly information version parsing

### ISSUE THREAD

**Issue by ttvrdon** [NuGet/Home#5409]
## Details about Problem

NuGet product used: NuGet.exe
NuGet version: 4.1.0.2450
VS version: 15.2
OS version: win10 v1511 (10586.916)

## Detailed repro steps so we can see the same problem

Use NuGet.exe pack command for any assembly with following AssemblyInformationalVersion: `1.3.5+Branch.release/releaseName.Sha.dde81779cf90c3332a9ae5d0c1b717870517259c`

Version part after + character are Build Metadata. There is no definition about format of this metadata.
From this article (http://blog.nuget.org/20140924/supporting-semver-2.0.0.html): 

> While build metadata doesn’t affect version precedence, it allows the package author to embed metadata into the version number such as a commit hash, date, build number, or anything else that could be used for diagnostics.

So forcing Build Metadata to contain only letters, numbers and dashes is bug.

**Comment by rrelyea** [comment]
Please use NuGet.exe 4.3.0 or later if you'd like it to work with SemVer 2.0.0

http://dist.nuget.org/index.html has 4.3.0 preview1 available today.

**Comment by ttvrdon** [comment]
Nuget 4.3.0 is causing same error.
Please re-open this ticket.

Build metadata cannot be forced to only following characters:
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-"
`(x >= 48 && x <= 57) || (x >= 65 && x <= 90) || (x >= 97 && x <= 122) || x == 45;`
