### ISSUE TITLE
dotnet restore help text should specify default verbosity

### ISSUE THREAD

**Issue by danroth27** [NuGet/Home#5411]
Looking at the `dotnet restore` help text I had expected the default verbosity level to be normal, but its actually minimal. I suggest updating the help text to clarify the default is minimal. The makes it clearer that you generally want to jump to normal when you have restore issues (ex. to see which feeds you have configured and where they are configured).

**Comment by emgarten** [comment]
I believe the default verbosity is set in dotnet.exe, but the actual help is in nuget.commandline.xplat.dll. We should investigate how this can be improved and kept in sync.

**Comment by nkolev92** [comment]
Closing as stale.
