### ISSUE TITLE
Missing nuget restore error messages in VS Package Manager output window

### ISSUE THREAD

**Issue by danroth27** [NuGet/Home#5412]
I had a restore failure when I updated my csproj include package references for packages versions that don't exist (I used `*` for the package version, when a stable version is not available yet). The VS Error List windows shows the restore errors:

![image](https://user-images.githubusercontent.com/1874516/27153086-fe9ce09a-5104-11e7-814d-c093edc3b415.png)

However, I don't see these errors listed in the output window text. The output text says the restore failed, but it doesn't say why, like it does in the VS Error List window:

![image](https://user-images.githubusercontent.com/1874516/27153184-4584ccde-5105-11e7-9c91-5cd5c6cfcab1.png)

I had expected the output text to be a superset of whatever shows up in the error list

**Comment by emgarten** [comment]
@mishra14 should filtering be done at a higher level so that errors/warnings written to project.assets.json still go to the output window? Or restore could also replay the assets file messages to the output.

**Comment by mishra14** [comment]
@danroth27 : Do you have the repro project? If not, then maybe the project type?

If this is a net core project then this is expected because we rely on sdk target to log the errors. We can reconsider this design to improve the user experience.

**Comment by danroth27** [comment]
Yes, this was with a .NET Core project.

It's pretty easy to reproduce. Just create a .NET Core project with a non-existent package reference:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0-preview2-25661" />
    <PackageReference Include="DoesNotExist" Version="2.0.0-preview2-25661" />
  </ItemGroup>

</Project>
```

**Comment by rrelyea** [comment]
as ankit mentioned, by design. we don't report any messages for netcore projects in output log, other than to say it failed. and then we show the errors/warning dialog.
