### ISSUE TITLE
NuGet concurrency issues

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5416]
Though reported for MacOS and Linux, we should test on Windows to see if same issues persist.

**Environment:** v2.8.6 and v4.0.0 NuGet versions have been tested on macOS (Sierra), also v2.8.6, v3.5.0, and v4.3.0-preview1 NuGet versions have been tested on Linux (Fedora).
Test case: open two terminals (instances) with different working directories and run “nuget install” command simultaneously (with empty cache).
**Results:** 
1.       v2.8.6 - First NuGet instance works fine. A second one fails with "Object reference not set to an instance of an object" error.
2.       v3.5.0 - Each instance can restore (and download) only half of packages.
3.       v4.0.0 - A deadlock like occurs when two instances try to download the same package. After a while, one instance wins and both processes are successfully completed. 

So NuGet works fine when all packages already cached, but it does not work well in cases it needs to download packages from the Internet.

**Comment by nkolev92** [comment]
Restore triage: I tested this on Windows, with latest and no issues there. 

Given the low community engagement I don't think it's worth keeping this anymore, so closing.
