### ISSUE TITLE
 System.ValueTuple pacakge not properly downloaded from nuget.

### ISSUE THREAD

**Issue by vsinghal7** [NuGet/Home#5418]
Hi,

I have a solution which is referencing System.ValueTuple package from Nuget gallary. I am trying to build(it restores the nuget packages) this solution from multiple machines, but it is giving me reference error for this package on some machines while working fine on some.

As per my research, Nuget is creating different named folders inside the System.ValueTuple folder inside packages folder.

Folder which is working for me - packages\System.ValueTuple.4.3.0\lib\net45

Folder which is not working fine for me - packages\System.ValueTuple.4.3.0\lib\netstandard1.0

This is the problem area, we are actually stuck on finding the solution. Please suggest the possible solution.

Thanks

Vinod

**Comment by emgarten** [comment]
What version of Visual Studio are you using? What version of NuGet are you using? What type of project are you installing this package into? What is the error you see when trying to reference it?

How did you verify that net45 works but netstandard1.0 does not? Are you referencing these dlls manually?

**Comment by vsinghal7** [comment]
Hi,
I am using the following version
Visual Studio version - 2015 and 2017
Nuget version - 2.8.50506.491
Project type - C# library
Error - Error	CS8179	Predefined type 'System.ValueTuple`2' is not defined or imported.
When we install package on the project, Nuget add reference to .dll automatically. I can see the path to .dll by peeking into properties of reference. 


Thanks
Vinod

**Comment by mishra14** [comment]
I cannot repro this with the following csproj - 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard1.0;net45</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.4.0" />
  </ItemGroup>

</Project>
```

@vsinghal7 please try latest VS 2017 15.5 and let us know if you are still facing this issue.
