### ISSUE TITLE
NuGet 2.8.6 should only depend on .NET 4.5 and not 4.5.1

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#542]
Visual Studio 2013 requires only .NET 4.5 and not 4.5.1.
Starting from (or might be earlier) Nuget 2.8.3 we depend on 4.5.1, we should restore to 4.5 for Visual Studio Update 5

**Comment by davkean** [comment]
Looking at VSIXManifest, it states the following:     ```<SupportedFrameworkRuntimeEdition MinVersion="4.0" MaxVersion="4.5" />```

**Comment by feiling** [comment]
Verified that current build of 2.8.6 depends on .NET 4.5.
