### ISSUE TITLE
Branding: VS 2017 15.3 update should start using the latest NuGet logo

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5420]
1. Ensure the logo is accessibility compliant
2. Replace the NuGet logo everywhere in VS 2017
3. When the package does not have any logo, the default logo should also be updated

**Comment by rrelyea** [comment]
Please investigate fix.

**Comment by anangaur** [comment]
@jonwchu can provide the icons if required.

**Comment by mishra14** [comment]
punting to 4.4 based on team feedback

**Comment by mishra14** [comment]
We should revive https://github.com/NuGet/NuGet.Client/pull/1523 when possible.

**Comment by anangaur** [comment]
@rrelyea Can this be picked again? Its odd to see old NuGet icons when the default icon shows up when package does not have it defined.

On VS:
![image](https://user-images.githubusercontent.com/14800916/56620069-7c0dcb00-65dc-11e9-8575-f078d395d7f7.png)


On nuget.org:
![image](https://user-images.githubusercontent.com/14800916/56620090-89c35080-65dc-11e9-818a-1922cdc709b1.png)

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/1623, the work done for https://github.com/NuGet/Home/issues/5694
