### ISSUE TITLE
[NuGet.VisualStudioExtension] 'All' package source is missing in VS2015 RC

### ISSUE THREAD

**Issue by karldodd** [NuGet/Home#543]
Hi,

I have multiple nuget package sources set up in my environment. In VS2015 RC's Package Manager, I failed to find the 'All' option on the UI, which used to be there in VS2013.

I also tried the command line:
```
Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> Update-Package -Reinstall -Source All
Update-Package : Invalid URI: The format of the URI could not be determined.
At line:1 char:1
+ Update-Package -Reinstall -Source All
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], UriFormatException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
```

In VS2013, 'All' works:   

```
Package Manager Console Host Version 2.8.50926.663

Type 'get-help NuGet' to see all available NuGet commands.

PM> Update-Package -Reinstall -Source All
Reinstalling 'Common.Logging 2.2.0' in project 'XXX.YYY.LogService'.
```

**Comment by deepakaravindr** [comment]
Thanks for your feedback! We will fix it post RTM

**Comment by albertjan** [comment]
:+1:  Please add this back in.

**Comment by stavnskov** [comment]
We are really missing this a lot.
What is the plan here? It was added to milestone 3.1.0, but still open.

**Comment by yishaigalatzer** [comment]
we intend to bring this feature back in 3.4, we did not manage to finish it for 3.3

**Comment by alpaix** [comment]
Attaching new UX design proposal.

[search-all-rev1.pdf](https://github.com/NuGet/Home/files/133352/search-all-rev1.pdf)

**Comment by csharpfritz** [comment]
I like the direction of this design proposal but the colors and font size in the progress bar make the text difficult to read.  Is it safe for me to assume that there is a design enhancement coming for those styles?

**Comment by yishaigalatzer** [comment]
this is fixed in 3.4 RTM

**Comment by madelson** [comment]
@yishaigalatzer When will 3.4 be out? We routinely use three separate package sources so this is a real pain point for us trying to upgrade to NuGet 3 and VS2015.

Also, will this fix work for the package manager console as well?

**Comment by yishaigalatzer** [comment]
Shouldnt be too long. It will coincide with update 2

**Comment by cbp123** [comment]
I install the 3.4 RC but it still wasn't available... looks like the performance issues are finally being resolved, but the missing "All" option is keeping the whole team off VS 2015.

**Comment by yishaigalatzer** [comment]
It will show up in rtm
