### ISSUE TITLE
NuGet 3.5.0 update fails with 'An additional constraint ... defined in packages.config prevents this operation

### ISSUE THREAD

**Issue by phatcher** [NuGet/Home#5432]
NuGet product used (Package Manager Console):

NuGet version (3.5.0.1484):

VS version (if appropriate): VS 2015 Enterprise Update 3

I'm updating a package Microsoft.IdentityModel.Clients.ActiveDirectory which needs to be constrained to < 3.0 due to diffferences in ADAL 2 vs ADAL 3

    <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="2.19.208020213" allowedVersions="[2.19, 3.0)" targetFramework="net462" />

There are later versions available on both v2 and v3 but when I try to update the package I get

	update-package : Unable to resolve 'Microsoft.IdentityModel.Clients.ActiveDirectory'. An additional constraint '(>= 2.19.0 && < 3.0.0)' defined in packages.config prevents this operation.
	At line:1 char:1
	+ update-package Microsoft.IdentityModel.Clients.ActiveDirectory
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
		+ FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

I notice something similar reported in #1816 and I'm wondering if in this case it's due to new versions on v2 and v3?

It does work if I specify the version explicitly i.e.

    update-package Microsoft.IdentityModel.Clients.ActiveDirectory -Version 2.28.4

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
