### ISSUE TITLE
Consider deprecating `Source` parameter

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#5435]
### Problem

Specifying a source when installing a package in `PackageRef` or `project.json` project won't make any effect on subsequent restores, because v3 restore operation will always look for best match across all **listed** sources.  Hence install operation will fail eventually. Moreover it might confuse user as providing one of listed sources won't give it a preference when resolving packages.

Behavior is similar for PMC `Install-Package` and for extension APIs.

### Solution
Consider deprecating `Source` parameter by marking the API as obsolete for v3. At minimum give meaningful error or warning message. Update documentation. Package Manager UI should use `All Sources` by default.

**Comment by nkolev92** [comment]
This has partly been done. 

Source is deprecate as is for PR. 

With source mapping, we now have different considerations. 

This is not as relevant going forward.
