### ISSUE TITLE
build\native\PackageName.targets isn't imported after installing package in C++ project

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#5439]
## Details about Problem

NuGet product used: VS UI or Package Manager Console
NuGet version (x.x.x.xxx): 4.3.0.4168
VS version (if appropriate): d15prerel 26615.05
OS version (i.e. win10 v1607 (14393.321)): rs2_release 15063.2.170323-1837

Worked before? If so, with which NuGet version: Yes in 4.2.0.2457 with d15svc 26430.13 (15.2)

## Detailed repro steps so we can see the same problem

1. Create new Blank C++ UWP project in VS
2. Install this package --> [XetNativeSdk.1.0.0.zip](https://github.com/NuGet/Home/files/1082172/XetNativeSdk.1.0.0.zip)
I tried two different approaches to installing it.  The bug repros either way.
a) In Manage NuGet Packages, added a custom package source pointing at its location on disk and then added package from Browse tab.
b) Added solution-level nuget.config containing packageSource pointing at its location on disk and adding package via Install-Package in the Package Manager Console.

**Expected:** XetNativeSdk is now visible under References in Solution Explorer.  vcxproj now contains an <Import> for XetNativeSdk.targets.

**Actual:** XetNativeSdk is not in References because .targets hasn't been imported.

**Comment by alpaix** [comment]
@debonte The package doesn't have `.targets` files matching `uap10.0.xxx` framework. 
The package structure should be similar to this [sample](https://github.com/NuGet/Samples/blob/master/ExtensionSDKasNuGetPackage/NativePackage/NativePackage.nuspec).

**Comment by debonte** [comment]
@alpaix So Targets\native\MyNativePackage.targets used to be sufficient (in 15.2), but now Targets\uap\...\MyNativePackage.targets is required?  Can I get away with just Targets\uap\10.0\MyNativePackage.targets or do I also need a version-specific directory like Targets\uap\10.0.14393\MyNativePackage.targets?  This package is going to be used by automated tests and I'd like to make it future proof if I can (i.e. avoid Win10 build numbers).

**Comment by alpaix** [comment]
Confirming regression in native framework evaluation. Will work on a mitigation. As a workaround try using public build of Visual Studio 2017 to install your package.
