### ISSUE TITLE
NoWarn PackageReference Metadata is not respected in netcoreapp2.0

### ISSUE THREAD

**Issue by natidea** [NuGet/Home#5448]
`NoWarn` on a Package reference is not functioning properly for netcoreapp2.0 or netstandard2.0

Given the following project file:

```xml 
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.1;netcoreapp2.0;net461</TargetFrameworks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
 
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.0'">
    <PackageReference Include="newtonsoft.json" Version="10.0.0" NoWarn="NU1603" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp1.1'">
    <PackageReference Include="newtonsoft.json" Version="10.0.0" NoWarn="NU1603" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net461'">
    <PackageReference Include="newtonsoft.json" Version="10.0.0" NoWarn="NU1603" />
  </ItemGroup>
</Project>
```

The NoWarn correctly removes the warning from net461 and netcoreapp1.1, but not for netcoreapp2.0 and the assets file still contains:

```json 
    {
      "code": "NU1603",
      "level": "Error",
      "message": "ConsoleApp5 depends on Newtonsoft.Json (>= 10.0.0) but Newtonsoft.Json 10.0.0 was not found. An approximate best match of Newtonsoft.Json 10.0.1 was resolved.",
      "libraryId": "Newtonsoft.Json",
      "targetGraphs": [
        ".NETCoreApp,Version=v2.0",
        ".NETCoreApp,Version=v2.0/win7-x86"
      ]
    }
```
Similar behavior is observed for netstandard2.0.

## Details about Problem

NuGet version (x.x.x.xxx):  4.3.0-preview3-4168

dotnet.exe --version (if appropriate): 2.0.0-preview3-006478

**Comment by mishra14** [comment]
Cause:
The Warning Properties collection holds package specific `NoWarn` properties in a `HashSet<NugetFramework>`. Currently that hash set did not have a comparer and used the `Equals` and `GetHashCode` methods from the objects being added/compared.
With work for `ATF` certain frameworks like `netcore2.0` were being read as `AssetTargetFallbackFramework` as a result the behavior for `GetHashCode` differed between `NuGetFramework` and `AssetTargetFallbackFramework` and the comparison logic was broken.

Fix PR: 
https://github.com/NuGet/NuGet.Client/pull/1504
