### ISSUE TITLE
restore no-op doesn't work if VS restore is followed by msbuild restore for UWP project.json < RS2

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5452]
Repro steps:
File -> New Project -> UWP Class Library, TPMinV 10586, TPV 14093
Build Solution (this will cause a restore)
Build solution again. (This will cause a no-op restore).

Open Dev Command prompt, do msbuild /t:restore . Restore does not no-op.

CC: @nkolev92

**Comment by rohit21agrawal** [comment]
noticing this for sdk based projects too.

**Comment by nkolev92** [comment]
This was fixed in https://github.com/NuGet/NuGet.Client/pull/1659
