### ISSUE TITLE
Multi target project cant be installed using VS 2017 with all updates

### ISSUE THREAD

**Issue by kukjevov** [NuGet/Home#5457]
## Details about Problem

NuGet product used (VS UI):

NuGet version (4.2):

VS version (if appropriate): 15.2 (26430.13)

OS version (i.e. win10 (15063 build)):

Worked before? If so, with which NuGet version: Not tested before

## Detailed repro steps so we can see the same problem

I have created project which looks like this.

```xml
<Project Sdk="Microsoft.NET.Sdk">
    <!-- BASIC INFO -->
    <PropertyGroup>
        <AssemblyName>Asseco.Extensions.Common</AssemblyName>
        <Version>1.0.5</Version>
        <Description>Asseco.Extensions.Common Class Library</Description>
        <Authors>marek.bukovsky</Authors>
        <Company>Asseco Central Europe a.s.</Company>
        <Copyright>Copyright © 2017</Copyright>
    </PropertyGroup>

    <!-- BUILD OPTIONS -->
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <SignAssembly>True</SignAssembly>
        <AssemblyOriginatorKeyFile>..\..\.include\Ace.snk</AssemblyOriginatorKeyFile>
        <DelaySign>False</DelaySign>
    </PropertyGroup>

    <!-- FRAMEWORK -->
    <PropertyGroup>
        <TargetFrameworks>netstandard1.6;net40</TargetFrameworks>
        <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
    </PropertyGroup>

    <!-- PACKAGING -->
    <PropertyGroup>
        <PackageTags>common;tools;utilities;abstractions</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://gitlab/ace-common/Asseco.Extensions.Common</RepositoryUrl>

        <PackageReleaseNotes>
            v1.0.5
                - added strong name
            v1.0.4
                - added support for .net 4.0
            v1.0.2
                - added DoubleExtensions
            v1.0.1
                - added ThrowIfNotNull to ValidationResultExtensions
            v1.0.0
                - initial version
        </PackageReleaseNotes>
    </PropertyGroup>

    <!-- PROJECT REFERENCE -->
    <ItemGroup>
        <ProjectReference Include="..\Asseco.Extensions.Common.Abstractions\Asseco.Extensions.Common.Abstractions.csproj" />
    </ItemGroup>

    <!-- DEPENDENCIES COMMON -->
    <ItemGroup>
        <PackageReference Include="Asseco.NuGet.Deployment" Version="2.1.0" PrivateAssets="All" />
    </ItemGroup>

    <!-- DEPENDENCIES NET 40-->
    <ItemGroup Condition="'$(TargetFramework)'=='net40'">
        <Reference Include="System.ComponentModel.DataAnnotations" />
    </ItemGroup>

    <!-- DEPENDENCIES NETSTANDARD 1.6 -->
    <ItemGroup Condition="'$(TargetFramework)'=='netstandard1.6'">
        <PackageReference Include="System.ComponentModel.Annotations" Version="4.3.0" />
    </ItemGroup>
</Project>
```

Published this package to our NuGet repository. We are hosting NuGet repository in  Nexus 2.12.0-01.
It uses probably v2 NuGet api, but I am not sure.
For creating `nupkg` was used `dotnet pack`.

Generated `nuspec` looks like this

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Asseco.Extensions.Common</id>
    <version>1.0.5</version>
    <authors>marek.bukovsky</authors>
    <owners>marek.bukovsky</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Asseco.Extensions.Common Class Library</description>
    <releaseNotes>v1.0.5
                - added strong name
            v1.0.4
                - added support for .net 4.0
            v1.0.2
                - added DoubleExtensions
            v1.0.1
                - added ThrowIfNotNull to ValidationResultExtensions
            v1.0.0
                - initial version</releaseNotes>
    <copyright>Copyright © 2017</copyright>
    <tags>common tools utilities abstractions</tags>
    <repository type="git" url="https://gitlab/ace-common/Asseco.Extensions.Common" />
    <dependencies>
      <group targetFramework=".NETFramework4.0">
        <dependency id="Asseco.Extensions.Common.Abstractions" version="1.0.5" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard1.6">
        <dependency id="Asseco.Extensions.Common.Abstractions" version="1.0.5" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers" />
        <dependency id="System.ComponentModel.Annotations" version="4.3.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

As you can see project is multiplatform, targeting .net 4.0 and .net standard 1.6, but if i try to install it using NuGet package manager UI in VS 2017 and click install, it will fail, log is below.

Maybe problem is Nexus and its API which is not using latest NuGet API.

But it is not working, if i add it manually into project by editing csproj, everyting is working as it should.

### Verbose Logs

Attempting to gather dependency information for package 'Asseco.Extensions.Common.1.0.5' with respect to project 'src\Asseco.Plantago.Allium.Service', targeting '.NETFramework,Version=v4.0'
Gathering dependency information took 20,67 sec
Attempting to resolve dependencies for package 'Asseco.Extensions.Common.1.0.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Asseco.Extensions.Common.1.0.5'
Resolved actions to install package 'Asseco.Extensions.Common.1.0.5'
Retrieving package 'Asseco.Extensions.Common 1.0.5' from 'ACE NuGet'.
Retrieving package 'NETStandard.Library 1.6.1' from 'nuget.org'.
Retrieving package 'System.ComponentModel.Annotations 4.3.0' from 'nuget.org'.
Adding package 'NETStandard.Library.1.6.1', which only has dependencies, to project 'Asseco.Plantago.Allium.Service'.
Adding package 'NETStandard.Library.1.6.1' to folder 'D:\Data\git\plantago-allium\packages'
Added package 'NETStandard.Library.1.6.1' to folder 'D:\Data\git\plantago-allium\packages'
Added package 'NETStandard.Library.1.6.1' to 'packages.config'
Successfully installed 'NETStandard.Library 1.6.1' to Asseco.Plantago.Allium.Service
Install failed. Rolling back...
Package 'System.ComponentModel.Annotations.4.3.0' does not exist in project 'Asseco.Plantago.Allium.Service'
Removed package 'NETStandard.Library.1.6.1' from 'packages.config'
Package 'System.ComponentModel.Annotations.4.3.0' does not exist in folder 'D:\Data\git\plantago-allium\packages'
Removing package 'NETStandard.Library.1.6.1' from folder 'D:\Data\git\plantago-allium\packages'
Removed package 'NETStandard.Library.1.6.1' from folder 'D:\Data\git\plantago-allium\packages'
Executing nuget actions took 899,92 ms
Could not install package 'System.ComponentModel.Annotations 4.3.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:21.7835461

**Comment by mishra14** [comment]
@kukjevov can you try uploading the package to nuget.org and then see if this succeeds?

Also, please try the latest VS 2017 15.5 and let us know if you are still facing this issue.
