### ISSUE TITLE
Satellite assemblies from PackageReference all copy to root bin folder

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5458]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): 4.3.0

VS version (if appropriate): 15.3.26616.2.d15rel

OS version (i.e. win10 v1607 (14393.321)): Win10 15063.rs2_release.170317-1834

Worked before? If so, with which NuGet version: Yes, this worked in 15.1 or 15.2 I believe.

## Detailed repro steps so we can see the same problem

Create a new .NET Core library, then replace the project file content with this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Composition" Version="15.0.71" />
  </ItemGroup>
</Project>
```

Restore, and build. 

**Expected**

The project's bin folder has just a few DLLs, and a bunch of culture folders, each with a few `*.resources.dll` assemblies.

**Actual**

The bin folder that contains the project output no sub-folders. Instead, "all" the satellite assemblies are copied into that one root bin folder, causing each one to overwrite another so that only one culture wins. And at runtime, the satellite assemblies cannot be found.

**Comment by rohit21agrawal** [comment]
shouldn't this go to msbuild?

**Comment by AArnott** [comment]
I expected NuGet owned the .targets that copy files from nuget packages into the user's bin folder based on PackageReference.

**Comment by rohit21agrawal** [comment]
NuGet doesn't decide where the DLLs would be copied to on disk. It only creates an assets file which is a dependency graph, then NuGetBuildTasks convert these to References. Finally, SDK targets decide what to do with these references. So I would lean towards this being something that SDK isn't handling well.

**Comment by AArnott** [comment]
Very well. It only seems to repro for .NET SDK projects so I'll move to dotnet/sdk

**Comment by AArnott** [comment]
This issue was moved to dotnet/sdk#1360
