### ISSUE TITLE
Framework assembly dependencies still missing from nuspec on `dotnet pack`

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5459]
#4853 added `frameworkAssemblies` back to the nuspec file when the nuspec is generated by .NET SDK projects. But those references only show up for `msbuild /t:pack`, and are omitted from the generated nuspec file when using `dotnet pack`. 

| tool | version |
|--|--|
dotnet.exe --version | 2.0.0-preview1-005842
VS version | 15.3.26616.2.d15rel

**Comment by rohit21agrawal** [comment]
the latest dotnet from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-win-x64.zip has the pack change.
