### ISSUE TITLE
[NuGet.VisualStudioExtension] When setting filter to "Upgrade available", default action should be update instead of uninstall

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#546]
When I am filtering on packages to upgrade, I am not necessarily interested in removing them ;-)

Please change the default action from "Uninstall" to "Update" (or "Upgrade"). I know they are alphabetically sorted, but please put the default to Update.

**Comment by deepakaravindr** [comment]
Thanks for the feedback! We have fixed this issue for RTM
