### ISSUE TITLE
Reference assembly generation fails

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#5465]
Fails with:

/Users/nater/.nuget/packages/nuget.build.packaging/0.1.318/build/NuGet.Build.Packaging.ReferenceAssembly.targets(3,3): Error MSB3202: The project file “/Users/nater/.nuget/packages/nuget.build.packaging/0.1.318/build/GenerateReferenceAssembly.csproj” was not found. (MSB3202)

Looks like we missed adding the csproj to the package when we updated to latest nugetizer.

**Comment by NateRickard** [comment]
Rebuilt with v0.1.323 and I can confirm this is resolved.

**Comment by kzu** [comment]
Cool!
