### ISSUE TITLE
Searching for a never searched before package in the Installed tab in an empty project takes > 1 minute

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5475]
## Details about Problem

VS version (if appropriate): Version 15.3.0 Preview 3.0 [26618.0.d15prerel]

## Detailed repro steps so we can see the same problem

1. Create a new .NET Console App (.NET Framework)
2. Open Managed Package Dialog
3. Enter "TermIveNeverSearchedBefore"
4. Press ENTER to search

Expected: For this to be instant
Actual: Takes over a minute to search a package with zero packages or packages.config

**Comment by davkean** [comment]
It's quicker to search the Browse tab then the Installed tab.

**Comment by mishra14** [comment]
@davkean I am not able to repro this locally. Please let us know if you are still facing this with latest VS 2017.
