### ISSUE TITLE
Unhandled Exception: System.NotSupportedException: The requested security protocol is not supported.

### ISSUE THREAD

**Issue by afficionaddo** [NuGet/Home#5480]
Please read the following information before posting the issue.

My project is not building.
Whenever I build it says "Nuget command Line has stopped working".

The errors shown in the console are:
* Error1	Unhandled Exception: System.NotSupportedException: The requested security protocol is not supported.	Coach.Business.Components

* Error2	   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)	Coach.Business.Components

* Error3	   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)	Coach.Business.Components

* Error4	   at NuGet.CommandLine.Program.Main(String[] args)	Coach.Business.Components

* Error5	The command ""D:\Projects\xxxxx\Releases\xxxxxxxxAdmin\.nuget\NuGet.exe" install "D:\Projects\xxxxx\Releases\xxxxxxxxx-Admin\Business.Components\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "D:\Projects\xxxxxxxx\Releases\xxxxxxx\xxxxxxx-Admin\ "" exited with code -532462766.

### Details about Problem
- I had formatted my system & took latest from TFS.
- After format, I have not been able to build my project.
- My company also recently setup a local Nexus repository & denied access to Nuget.org for downloads.
- The .nuget folder has Nuget.exe v3.3.xxx
- Whenever I double-click & exexute Nuget.exe It says "Nuget command line has stopped working".

Please help as this is a blocker in my work & I am unable to resolve this.

**Comment by wicharypawel** [comment]
Have the same problem, after reinstallation of a system. My setup is fresh instance of VS 2010 with NuGet extension 2.8.60318.667

**Comment by mishra14** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015 or older. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
