### ISSUE TITLE
Creation of nuget package using the csproj creates a content file instead of content folder

### ISSUE THREAD

**Issue by ja0b** [NuGet/Home#5482]
## Details about Problem
Using .Net 4.6.1, in a web project I tried to create a nuget package of it using the csproj but the package ends up with a file called content instead of a folder with the files I want to include in there.

This warning gets thrown for each of the files I try to add

`WARNING: File 'C:\....\Web.config.install.xdt' is not added because the package already contains file 'content'`

Things I've tried using nuget pack .... csproj :

Using nuspec file WITHOUT the file section and setting the build actions to content/copyifnewer
Using nuspec file WITH the file section specifying each file destination.
Using only the csproj

I managed to create the package using the nuspec file but I would like to get it working with the csproj to use replacement tokens for the version, title, etc, etc.

Any thoughts?

NuGet product used: NuGet.exe
NuGet version: 4.1.0
dotnet.exe --version: 4.6.1

**Comment by rohit21agrawal** [comment]
@ja0b is it possible for you to attach a repro project for us to investigate?
