### ISSUE TITLE
Provide migration tool to move from packages.config project to packagereference

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#5488]
Some users would prefer to use VS2017's support for PackageReference, instead of the default Packages.config.

We've provided a way, in tools/options/nuget -- to choose what to use in a new project.
However, many people would like to migrate existing projects as well.

This issue is tracking our future work item to make that migration easier.

Note -- not all packages are compatible with PackageReference, so migration may not work for some projects/packages. See https://github.com/NuGet/Home/issues/4942

**Comment by gmajian** [comment]
There is  a GitHubGist for "Converts packages.config into PackageReference at *.csproj project file"
https://gist.github.com/a4099181/074a6c3dd524ea0d343382137492399c

**Comment by Kassoul** [comment]
An another good tool on Github that use https://github.com/hvanbakel/CsprojToVs2017

**Comment by tomkuijsten** [comment]
@gmajian that script is very limited, eg doesn't work for packages where it's version number are different then the containing assembly version numbers.

**Comment by tomkuijsten** [comment]
@Kassoul this tool has the same problem as the script, a lot of references aren't removed.

**Comment by tomkuijsten** [comment]
@rrelyea do you want to convert to the new csproj format  as well?

**Comment by jainaashish** [comment]
We've made some progress here but needs to continue with it.

**Comment by jainaashish** [comment]
We've the initial code ready but needs to work with PM to finalize the spec.

**Comment by rohit21agrawal** [comment]
@tomkuijsten no, our tool (which is work in progress) isn't currently intending to convert to the new csproj format.

**Comment by tomkuijsten** [comment]
Thanks for the clear statement!

**Comment by rohit21agrawal** [comment]
The migrator tool (on a per project basis) will be available in 15.7 Preview3

**Comment by mdell-seradex** [comment]
When will migration support C++ and/or ASP.NET Projects?
