### ISSUE TITLE
Cannot restore pre-release dependecies of the package

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5489]
_From @AlexByte on June 26, 2017 11:42_

## Steps to reproduce

```
dotnet new
dotnet add package ImageSharp --version 1.0.0-alpha9-00148 --source https://www.myget.org/F/imagesharp/api/v3/index.json
```

## Actual behavior

Pre-release [dependencies](https://www.myget.org/feed/imagesharp/package/nuget/ImageSharp/1.0.0-alpha9-00152) are not installing 
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

info : Adding PackageReference for package 'ImageSharp' into project '.csproj'.
log  : Restoring packages for .csproj...
info :   GET https://www.myget.org/F/imagesharp/api/v3/flatcontainer/system.memory/index.json
info :   GET https://www.myget.org/F/imagesharp/api/v3/flatcontainer/system.runtime.compilerservices.unsafe/index.json
info :   NotFound https://www.myget.org/F/imagesharp/api/v3/flatcontainer/system.runtime.compilerservices.unsafe/index.json 825ms
info :   NotFound https://www.myget.org/F/imagesharp/api/v3/flatcontainer/system.memory/index.json 1094ms
error: Unable to resolve 'System.Runtime.CompilerServices.Unsafe (>= 4.4.0-preview1-25305-02)' for '.NETCoreApp,Version=v1.1'.
error: Unable to resolve 'System.Memory (>= 4.4.0-preview1-25305-02)' for '.NETCoreApp,Version=v1.1'.
error: Package 'ImageSharp' is incompatible with 'all' frameworks in project 
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

```

The original issue https://github.com/JimBobSquarePants/ImageSharp/issues/256

_Copied from original issue: dotnet/cli#7003_

**Comment by zhili1208** [comment]
if you use "--source", nuget will only search from specified source.

So please specify nuget.org as a source.

```
dotnet add package ImageSharp --version 1.0.0-alpha9-00148 --source "https://www.myget.org/F/imagesharp/api/v3/index.json;https://api.nuget.org/v3/index.json"
```

**Comment by mishra14** [comment]
@AlexByte:
could you please try - 

`dotnet add package ImageSharp --version 1.0.0-alpha9-00148 --source https://www.myget.org/F/imagesharp/api/v3/index.json;https://api.nuget.org/v3/index.json`

If you are using powershell, then please add a ` before the ; between the sources.

I think the problem may be that the source override is causing the problem

**Comment by larssb** [comment]
@mishra14 sorry for writting in an old closed case but, by any chance, do you know how Imagesharp would install in PowerShell, with either install-package or install-module from the ImageSharp myget repo?

**Comment by mishra14** [comment]
@larssb : It seems that we have a bug there. I have logged it at https://github.com/NuGet/Home/issues/5837.

In the meantine, i would suggest, adding the sources to the config file or through the UI. You can use this [doc](https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations) if you need. 

Please let me know if you need any more help!

**Comment by arnotes** [comment]
is there some kind of `dotnet restore --try-all-source`?
i already have a global nugetconfig file. having to type a long url every restore seems...dunno...just why????
