### ISSUE TITLE
[V2] Revisit AggregateRepository.IgnoreFailingRepositories behavior

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#549]
Currently AggregateRepository flattens any AggregateRepository added to it and uses the same IgnoreFailingRepositories setting for all the contained repositories. However this might not always be desired, e.g. a local repository should throw, but a remote repository should not when contained in the same AggregateRepository.

**Comment by deepakaravindr** [comment]
Can you provide more information? How critical do you think this is?
Also, this is only for 2.8.6, right?

**Comment by AndriySvyryd** [comment]
This is something @pranavkm was concerned about. This is 2.8.6 and was probably there since AggregateRepository was introduced. It might not be actually a problem due to the way AggregateRepository is used in the code.

**Comment by emgarten** [comment]
This is by design as far as I know. A UNC share could be down, and currently v2 expects those failures to be suppressed.
