### ISSUE TITLE
Problems downloading big packages?

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#5491]
@matthid commented on [Sat Jun 24 2017](https://github.com/NuGet/NuGetGallery/issues/4277)

Please see https://github.com/Microsoft/visualfsharp/issues/3253
The package I just had problems with was: `StrawberryPerl64.5.22.2.1`
Basically it seems like the NuGet server sends 504 responses on this package, or even stops responding from time to time...

---

@cartermp commented on [Sat Jun 24 2017](https://github.com/NuGet/NuGetGallery/issues/4277#issuecomment-310851191)

This issue can prevent people from successfully contributing to the F# compiler and tools.  Not sure what the solution here is, but it would be great to get it looked at.

**Comment by zhili1208** [comment]
cloned and built visualfsharp, but can't repro this issue, restoring StrawberryPerl64 took some time but didn't get any error

**Comment by mishra14** [comment]
@skofman1 we were not able to repro this issue. This seems like  a server issue since the users were getting a 504 while manual download. Can you please elaborate on why do you think this is a client issue?
