### ISSUE TITLE
Microsoft.Bot.Builder Nuget Package does not Install

### ISSUE THREAD

**Issue by dbaechtel** [NuGet/Home#5492]
In VS 2017 Community version, .Net Standard C# Class Library project, Microsoft.Bot.Builder Nuget Package does not Install. target .Net Framework 4.0 gets the error messages below.

What do I need to do to install Microsoft.Bot.Builder package?

Restoring packages for c:\users\dbaec\documents\visual studio 2017\Projects\Bot8\Bot8\Bot8.csproj...
Detected package downgrade: Newtonsoft.Json from 9.0.1 to 8.0.3 
 Bot8 (>= 1.0.0) -> Microsoft.Bot.Builder (>= 3.8.2) -> Microsoft.Rest.ClientRuntime (>= 2.3.2) -> Newtonsoft.Json (>= 9.0.1 && < 10.0.0) 
 Bot8 (>= 1.0.0) -> Microsoft.Bot.Builder (>= 3.8.2) -> Newtonsoft.Json (>= 8.0.3)
Package Microsoft.Bot.Builder 3.8.2 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.Bot.Builder 3.8.2 supports: net46 (.NETFramework,Version=v4.6)
Package Autofac 3.5.2 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Autofac 3.5.2 supports:
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
Package Chronic.Signed 0.3.2 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Chronic.Signed 0.3.2 supports: net40 (.NETFramework,Version=v4.0)
Package Microsoft.AspNet.WebApi.Core 5.2.3 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.AspNet.WebApi.Core 5.2.3 supports: net45 (.NETFramework,Version=v4.5)
Package Newtonsoft.Json 8.0.3 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Newtonsoft.Json 8.0.3 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
Package System.IdentityModel.Tokens.Jwt 4.0.4.403061554 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package System.IdentityModel.Tokens.Jwt 4.0.4.403061554 supports: net45 (.NETFramework,Version=v4.5)
Package Microsoft.IdentityModel.Protocol.Extensions 1.0.4.403061554 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.IdentityModel.Protocol.Extensions 1.0.4.403061554 supports: net45 (.NETFramework,Version=v4.5)
Package Microsoft.AspNet.WebApi.Client 5.2.3 is not compatible with netstandard1.4 (.NETStandard,Version=v1.4). Package Microsoft.AspNet.WebApi.Client 5.2.3 supports:
  - net45 (.NETFramework,Version=v4.5)
  - portable-net45+netcore45+wp8+wp81+wpa81 (.NETPortable,Version=v0.0,Profile=wp8+netcore45+net45+wp81+wpa81)
One or more packages are incompatible with .NETStandard,Version=v1.4.
Package restore failed. Rolling back package changes for 'Bot8'.
Time Elapsed: 00:00:00.1332061
========== Finished ==========

**Comment by zhili1208** [comment]
some dependency packages of this package only support netframework, it doesn't work for netstandard class library,

you can follow instruction here: https://docs.microsoft.com/en-us/bot-framework/dotnet/bot-builder-dotnet-quickstart by using bot application template.

Or you can install this package to a net46 class library

**Comment by mishra14** [comment]
@emgarten it seems that the warning experiences may have degraded here.

**Comment by mishra14** [comment]
@dbaechtel  can you please let us know if you are still facing this issue with latest VS 2017 15.5.
