### ISSUE TITLE
Show SemVer 2 build metadata on Package details page on VS

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5494]
For VS 2017 and VS 2015, we should show the SemVer 2 build metadata in the version string on Package details page:
Related issue to warn during pack and push is here: https://github.com/NuGet/Home/issues/5493
![image](https://user-images.githubusercontent.com/14800916/27563634-ae564702-5a87-11e7-907d-cbd8c304f9c7.png)

**Comment by rrelyea** [comment]
Merged into dev.
