### ISSUE TITLE
Targetframework incompatibility error message doesn't show which package is incompatible

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#5496]
NuGet Version: 4.3.0.4168

Running restore with 2 concurrent jobs.
Reading project file c:\users\lzhi\source\repos\ClassLibrary5\ClassLibrary5\ClassLibrary5.csproj.
The restore inputs for 'ClassLibrary5' have changed. Continuing restore.
Restoring packages for c:\users\lzhi\source\repos\ClassLibrary5\ClassLibrary5\ClassLibrary5.csproj...
Restoring packages for .NETStandard,Version=v1.4...
Resolving conflicts for .NETStandard,Version=v1.4...
Checking compatibility of packages on .NETStandard,Version=v1.4.
Checking compatibility for ClassLibrary5 1.0.0 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.Bot.Builder 3.8.2.0 with .NETStandard,Version=v1.4.
Checking compatibility for NETStandard.Library 1.6.1 with .NETStandard,Version=v1.4.
Checking compatibility for Autofac 3.5.2 with .NETStandard,Version=v1.4.
Checking compatibility for Chronic.Signed 0.3.2 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.AspNet.WebApi.Core 5.2.3 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.Rest.ClientRuntime 2.3.2 with .NETStandard,Version=v1.4.
Checking compatibility for Newtonsoft.Json 8.0.3 with .NETStandard,Version=v1.4.
Checking compatibility for System.IdentityModel.Tokens.Jwt 4.0.4.403061554 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.IdentityModel.Protocol.Extensions 1.0.4.403061554 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.Win32.Primitives 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.AppContext 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Collections 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Collections.Concurrent 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Console 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Diagnostics.Debug 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Diagnostics.Tools 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Diagnostics.Tracing 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Globalization 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Globalization.Calendars 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.IO 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.IO.Compression 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.IO.Compression.ZipFile 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.IO.FileSystem 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.IO.FileSystem.Primitives 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Linq 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Linq.Expressions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Net.Http 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Net.Primitives 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Net.Sockets 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.ObjectModel 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Reflection 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Reflection.Extensions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Reflection.Primitives 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Resources.ResourceManager 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime.Extensions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime.Handles 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime.InteropServices 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime.InteropServices.RuntimeInformation 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Runtime.Numerics 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Security.Cryptography.Algorithms 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Security.Cryptography.Encoding 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Security.Cryptography.Primitives 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Security.Cryptography.X509Certificates 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Text.Encoding 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Text.Encoding.Extensions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Text.RegularExpressions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Threading 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Threading.Tasks 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Threading.Timer 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Xml.ReaderWriter 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Xml.XDocument 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.AspNet.WebApi.Client 5.2.3 with .NETStandard,Version=v1.4.
Checking compatibility for Microsoft.NETCore.Targets 1.1.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.native.System 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.native.System.IO.Compression 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Buffers 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Diagnostics.DiagnosticSource 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for System.Threading.Tasks.Extensions 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Checking compatibility for runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0 with .NETStandard,Version=v1.4.
Incompatible packages: 8
Package restore failed. Rolling back package changes for 'ClassLibrary5'.
Time Elapsed: 00:00:00.5399234
========== Finished ==========

**Comment by nkolev92** [comment]
We write to error list in 16.6. This was probably fixed a lot earlier.
