### ISSUE TITLE
Pressing CTRL+C in Package Manager Console closes Visual Studio

### ISSUE THREAD

**Issue by spotlesscoder** [NuGet/Home#5499]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

Package Manager Console
Package Manager 

NuGet version (x.x.x.xxx):

4.1.0.2450

dotnet.exe --version (if appropriate):

1.0.0

VS version (if appropriate):

2015 Professional Update 3 (14.0.25424.00 Update 3)
- Package Manager Console Host Version 4.0.0.2323

2017 Professional (15.0.0+26228.12)
- Package Manager Console Host Version 3.5.0.1996

OS version (i.e. win10 v1607 (14393.321)):

6.1.7601

Worked before? If so, with which NuGet version:

Don't know whether it worked before.

## Detailed repro steps so we can see the same problem

1. Open a solution with NuGet package references

2. Open a file, change it, DON'T save the change, leave the file open

3. Open the Package Manager Console

4. Execute an action that takes a little while

5. Recognize that I wanted to nuget restore instead of nuget update

6. Press CTRL+C to cancel the current action

Seen behaviour: Visual Studio closes immediately, even though there are changed, unsaved files open

Wanted instead:

Alternative 1: (most preferred): current command is cancelled and VS stays open

Alternative 2: a warning / confirm window is shown and VS only closes when accepting

**Comment by mishra14** [comment]
I cannot repro this issue. can you please try with latest VS2017 15.5 and let us know if you are still facing this problem.

**Comment by spotlesscoder** [comment]
Seems to be fixed
