### ISSUE TITLE
NoWarn does not flow transitively through P2P references

### ISSUE THREAD

**Issue by natidea** [NuGet/Home#5501]
## Repro

1. Create two .NETStandard projects and create a P2P reference: ProjA -> ProjB

2. Add the following package reference to **ProjB**:
```xml
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.0" />
  </ItemGroup>
```

3. Observe two NU1603 warnings, and corresponding warnings in the Dependencies Node:

![image](https://user-images.githubusercontent.com/7732033/27611923-0e8303b0-5b49-11e7-9606-f4406fbf8c4f.png)

4. Suppress the warning in **ProjB** either with `NoWarn` metadata on the package reference, or a global NoWarn property, or through Project Properties UI

**Expected**
All warnings go away

**Actual**
The warning for ProjB goes away but the warning for ProjA remains in the error list, and is also in the assets file. The dependency node also displays what looks like a phantom warning for ProjA.

![image](https://user-images.githubusercontent.com/7732033/27613527-e1c07db4-5b50-11e7-8f34-f29153f4f921.png)

This phantom warning is happening because the diagnostic in the assets file was raised and sent to the dependencies node, but it is not displayed because the faulty package reference does not actually exist in ProjA. (Dependencies node should probably do better about not showing a warning icon if the underlying diagnostic is not visible)

Workaround is to also suppress the warning in ProjA, but this can only be done using a global NoWarn. Updating the transitive package reference in ProjA with an MSBuild "Update" does not work, i.e.:

```xml
  <ItemGroup>
    <PackageReference Update="Newtonsoft.Json">
      <NoWarn>NU1603</NoWarn>
    </PackageReference>
  </ItemGroup>
```
Of course, another workaround is to explicitly add the project reference to ProjA instead of receiving it transitively.

### Details about Problem

VS: d15prerel.26625.0

NuGet: 4.3.0-preview3-4168

dotnet.exe --version: 1.1.0-preview1-005051

/cc @mishra14 @emgarten @rrelyea @srivatsn

**Comment by natidea** [comment]
Perhaps the real problem here is that the original NU1603 warning should not flow transitively through the P2P ref in the first place, because it ends up looking like a duplicate:

![image](https://user-images.githubusercontent.com/7732033/27614250-4837235a-5b55-11e7-89e9-773da75fc109.png)

**Comment by mishra14** [comment]
I did some preliminary analysis. It seems that on restore, Newtonsoft.Json does flow up to ProjA as we take the flattened graph while restoring ProjA and that contains all the dependencies from ProjB.

Will discuss this a bit more internally.

**Comment by rrelyea** [comment]
Let's continue meeting on friday. for now, this is pushed to post 4.3

**Comment by mishra14** [comment]
Moving to 4.4/To-Do based on internal discussion.

**Comment by nkolev92** [comment]
Feedback ticket 463600 also raised this concern.

**Comment by mishra14** [comment]
- [x] #5689 - Design task 
- [x] #5691 - Implement the code/feature task
- [x] #5693 - Test task

**Comment by bording** [comment]
Will this work also change how NoWarn is handled for transitive dependencies on a package reference?

For example, in a netcoreapp2.0 project, if I have the following package reference:
```
<PackageReference Include="ApprovalTests" Version="3.0.13" NoWarn="NU1701" />
```
The warning is suppressed for the ApprovalTests package itself, but I still see a warning for the ApprovalUtilities package that it depends on:
![image](https://user-images.githubusercontent.com/753669/29183366-676ac630-7dd0-11e7-923c-4e4318f7f3c8.png)

I currently have to add an additional package reference to suppress that warning:
```
<PackageReference Include="ApprovalUtilities" Version="3.0.13" NoWarn="NU1701" />
```

It doesn't make sense to me that I should have to do this. If I've suppressed the warning on the package I care about, it should apply to all of its dependencies implicitly.

**Comment by mishra14** [comment]
@bording - Thanks for bringing up a great point. Unfortunately, current plan will not resolve your case.

but you can easily work that by adding a project wide no warn property - 

```
  <PropertyGroup>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
```

If you feel that your scenario needs to be resolved as well, please feel free to open up a new issue and link it here. We will add it to our next triage/discussion. 

hope this helps!

**Comment by bording** [comment]
@mishra14 I'd like to avoid a global warning suppression since it would hide the warning for any new packages I might add in the future as well.

I'll open a new issue then, thanks!

edit: Issue opened: https://github.com/NuGet/Home/issues/5740

**Comment by mishra14** [comment]
@bording thanks! We will consider the issue.

**Comment by mishra14** [comment]
Spec for resolving this issue - https://github.com/NuGet/Home/wiki/%5BSpec%5D-Transitive-Warning-Properties

**Comment by mishra14** [comment]
Merged: https://github.com/NuGet/NuGet.Client/commit/4be29f39b0d9bb897f914e9607f14c31569239ed
