### ISSUE TITLE
No build warnings generated for netstandard1.0 project referencing a  net461 project

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5503]
reported by @natidea 

Original text - 
`I’m observing that netstandard1.0 projects that reference net461 do not generate any compatibility warnings. Similarly, netstandard1.6 referencing net45 projects does not generate any warnings. (Not sure which of those combinations is supposed to be invalid looking at https://docs.microsoft.com/en-us/dotnet/standard/net-standard )`

Seems to repro with VS Preview 3 (d15rel.26621.2) with CLI Preview installed (2.0.0-preview3-006546)

**Comment by mishra14** [comment]
Investigating.

**Comment by mishra14** [comment]
Update:
Restore does throw an error if the net 461 project contains a package reference and that is the expected behavior.

We feel that the build system/sdk should fail when a netstandard1.0 project references a net461 project.

I tried a net45 project referencing a net461 project and there is a warning. I dont think NuGet is throwing that warning.

**Comment by rrelyea** [comment]
@mishra14 - if this is resolved as external, let's mark it as such. also link external bug.
Otherwise, should we reactivate if we didn't get agreement from the external team?

**Comment by mishra14** [comment]
@rrelyea I have opened https://github.com/dotnet/sdk/issues/1492 on the sdk repo. Will wait for any action on it.

**Comment by livarcocc** [comment]
@mishra14 How is this something that the SDK should do? The compatibility matrix between TFM lives entirely in NuGet and is checked during restore. How will the SDK even know what is or isn't compatible without looking at the project.assets.json?

I don't believe we want to start duplicating the compatibility matrix. Can you help me understand how/why you feel this should happen in the SDK?
