### ISSUE TITLE
Failed to retrieve information from source, if source is empty and package was not found

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5504]
_From @daxian-dbw on June 28, 2017 5:49_

## Steps to reproduce
`dotnet new console`

## Expected  behavior
No error and successfully restored

## Actual behavior
```
PS:52> dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on C:\Arena\Apps\dotnet2\bb\bb.csproj...
  Restoring packages for C:\Arena\Apps\dotnet2\bb\bb.csproj...
C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\NuGet.targets(102,5): error : 
Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'C:\Users\usr\.dotnet\NuGetFallbackFolder'. [C:\Arena\Apps\dotnet2\bb\bb.csproj]


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

PS:53> dotnet restore
  Restoring packages for C:\Arena\Apps\dotnet2\bb\bb.csproj...
C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\NuGet.targets(102,5): error : 
Failed to retrieve information about 'Microsoft.NETCore.App' from remote source 'C:\Users\usr\.dotnet\NuGetFallbackFolder'. [C:\Arena\Apps\dotnet2\bb\bb.csproj]
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview3-006607)

Product Information:
 Version:            2.0.0-preview3-006607
 Commit SHA-1 hash:  81dd304f72

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Users\usr\AppData\Local\Microsoft\dotnet\sdk\2.0.0-preview3-006607\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview3-25426-01
  Build    : 122309e7e7fb9bb233fe4910f822c28ec73f0957
```

_Copied from original issue: dotnet/cli#7013_

**Comment by livarcocc** [comment]
_From @JonathanLoscalzo on June 28, 2017 12:47_

this happens for all templates too :(

**Comment by livarcocc** [comment]
_From @JonathanLoscalzo on June 28, 2017 13:19_


@daxian-dbw maybe [this issue](https://github.com/dotnet/cli/issues/3330) solve the problem?

Create a nuget.config local and add => 
`
<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" /> 
`
it solve my problem... or help for others (like me)

**Comment by livarcocc** [comment]
@JonathanLoscalzo, look under %appdata%/NuGet/NuGet.Config and remove any references to CLIFallbackFolder from it. This is an entry that we no longer need in preview3. If you do that, you will get the real error, which is that we can't find the M.NC.App package. The reason for that is that the runtime between the CLI and asp.net are out of sync and when that happens, you need the feed above.

Still, I am moving this issue to NuGet, I don't think NuGet should say that it failed to find the package on that feed if the folder is empty, it should just say that it failed to find the package.

**Comment by nkolev92** [comment]
Dupping this to https://github.com/NuGet/Home/issues/6373. 

Failing when a source is unavailable is by design. https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#packagereference-and-sources

**Comment by jzabroski** [comment]
In case this is useful to anyone else... if you run `dotnet tool install <packageid> --version <packageversion> --verbosity diag > temp.txt` and search the temp.txt for "NuGet Config files used", you will find the following info:

```
                     Failed to restore D:\Users\John.Zabroski\AppData\Local\Temp\1\a9c19ab0-2f28-440b-962e-1cd32af6c609\restore.csproj (in 2.64 sec). (TaskId:38)
                      (TaskId:38)
                     NuGet Config files used: (TaskId:38)
                         D:\Users\John.Zabroski\AppData\Roaming\NuGet\NuGet.Config (TaskId:38)
                         C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config (TaskId:38)
```

In my case, for some reason, D:\Users\John.Zabroski\AppData\Roaming\NuGet\NuGet.Config , had an old URL for our internal package server.  Pretty weird.
