### ISSUE TITLE
NuGet project cache data not updated on package uninstall

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5505]
## Details about Problem
I ran into this while looking into https://github.com/NuGet/Home/issues/5503

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS2017

NuGet version (x.x.x.xxx): 4.3.0.4199

VS version (if appropriate): d15prerel/26627

## Detailed repro steps so we can see the same problem

1. File new project, ProjA, Net standard class library. Change the framework to net standard 1.0. -> 

2. Add new project, ProjB, to solution i.e. Net framework class library. Ensure the target framework is net461 or higher.

3. Add reference to ProjB in ProjA.

4. Restore solution. No errors or warnings.

5. Add a package targeting net461 to ProjB.

6. Restore solution. Error in ProjA since ProjB targets a higher framework.

7. Uninstall package from ProjB.

8. Restore solution.

## Expected

Solution should restore , just as in step 4.

## Actual

Error in ProjA since ProjB targets a higher framework.

Seems that we do not update the NuGet cache on package uninstall.
[netstandard1.0.zip](https://github.com/NuGet/Home/files/1110448/netstandard1.0.zip)

**Comment by mishra14** [comment]
Seems that the actual problem is that the ProjectStyle is Set to unknown for a new legacy csproj project.

@emgarten worked on ProjectStyle.

**Comment by nkolev92** [comment]
Low priority restoer scenario. 

Closing.
