### ISSUE TITLE
[Feature request] Recommended updates with checkboxes

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#551]
I have a lot of packages to manage (as does every developer), and one thing bothers me for a while now.

For some packages I want prereleases, for some I want stable versions. Make it easier:

1) For packages for which I already have a prerelease => show both stable and prerelease updates
2) For packages for which I installed stable versions => show only stable versions 

This feature is called "recommended updates". This should pop up as a screen with checkboxes so I can check which packages I actually want to update. If so, then boom, everything is directly as I want my solution to be.

We implemented a similar service in our NuGet client that we use to distribute extensions of our applications to our customers:

https://github.com/WildGums/Orc.NuGetExplorer/blob/develop/src/Orc.NuGetExplorer/Orc.NuGetExplorer.Shared/Services/PackagesUpdatesSearcherService.cs#L40

**Comment by deepakaravindr** [comment]
Thanks for the suggestion! Sounds like a good idea. We will consider it post RTM

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik in 3.3, we introduced a large chunk of this feature. Would you mind (after getting Update I), to get back to this issue and provide your feedback?

**Comment by GeertvanHorrik** [comment]
Great to hear progress. Is there a prerelease version available so I can already test it?

**Comment by yishaigalatzer** [comment]
No but shoot me an email y i g a l a t z @ msft

**Comment by GeertvanHorrik** [comment]
This is awesome, thanks! Works like a charm, updating all our apps in consolidation week (about 20 packages for 7 apps) can be done under 45 minutes now!
