### ISSUE TITLE
[regression since 15.2]  net standard PM.UI package install rollback no longer displays detailed error in output window

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5510]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS 

NuGet version (x.x.x.xxx): 4.3.0.4250

VS version (if appropriate): d15prerel/26627.3006

Worked before? If so, with which NuGet version: 4.2.0.2457 in VS 15.2

## Detailed repro steps so we can see the same problem

1. File New Project -> Net standard class library.

2. Change target framework to netstandard1.4.

3. Close Error list and output windows if open.

4. Launch PM.UI and install Microsoft.AspNetCore.Mvc.ViewFeatures/1.1.3

...

### Expected 

The output window should display an actionable error as in 15.2 - 
![installfrompmuiin15 2](https://user-images.githubusercontent.com/10507120/27712943-1ec10556-5cde-11e7-929d-015d05aeae05.PNG)

### Actual 

The output window displays a generic failure message - 
![installfrompmuiin15 3](https://user-images.githubusercontent.com/10507120/27712945-20b3e07c-5cde-11e7-84ff-4a401b894209.PNG)

**Comment by rrelyea** [comment]
triage: we should have hideerrorsandwarnings set to false for this restore that run for install.
