### ISSUE TITLE
nuget package manager Ui shows installed version 0.0.0

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5513]
dotnet new classlib
add package reference newtonsoft.json , version= "*" or no version
dotnet restore

open package manger ui in visual studio, go to installed tab -> newtonsoft.json is shown as 0.0.0

26621.2 d15rel build of VS 
dotnet.exe version: 2.0.0-preview2-006502 

CC: @zhili1208 @rrelyea

**Comment by nkolev92** [comment]
Fixed by @martinrrm
