### ISSUE TITLE
Full .net 4.6.2 framework Console application package containing a dll instead of an exe

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [NuGet/Home#5514]
## Details about Problem
I have a solution which contains 5 projects.  They all produce their own Nuget packages.

4 of the projects are Class Library projects which  produce dlls, and I am not having an issue with these.

The 5th project is a tool, it is a Console Application which produces an exe file.
The project is configured to produce a package on build.

When I build this project in Visual Studio 2017, the Nuget package that is produced contains the exe file as expected.

However, when I build and pack the project in the Developer Command Prompt, using msbuild,exe, the package that is produced contains a dll file.

The command used is:
msbuild src\DependencyCopy\DependencyCopy.csproj /t:Pack /p:Configuration=Release /p:IncludeSource=true /p:IncludeSymbols=true /p:GeneratePackageOnBuild=true

VS version: Visual Studio 2017 Version 15.2 (26430.12) 

OS version: win10 v1607 (14393.1358)

## Detailed repro steps so we can see the same problem

1.Create a solution in vs 2017 with two projects.  One of which has to be a Console application.

Here is a sample proj file for your info of the console app i'm talking about
[proj file example.txt](https://github.com/NuGet/Home/files/1114264/proj.file.example.txt)

2. Set up the Console application so that it produces a package when you build.
3. Now build and pack the project using msbuild
4. The package should contain an exe file, but contains a dll

**Comment by maartenba** [comment]
Seeing the same issue.

**Comment by mishra14** [comment]
tagging @rohit21agrawal for pack.

**Comment by mishra14** [comment]
@ThinkAboutGitHub:

Could you please try the following commands and let us know the result - 

`msbuild src\DependencyCopy\DependencyCopy.csproj /t:Restore /p:Configuration=Release`

`msbuild src\DependencyCopy\DependencyCopy.csproj /p:Configuration=Release /p:IncludeSource=true /p:IncludeSymbols=true /p:GeneratePackageOnBuild=true`

---------------------
Update - 

I think I know the problem here. In the csproj file the OutputType is only defined for Configuration Debug.

options for you -
1. If you want this project to always build as an Exe then change the first property group to - 

```
  <PropertyGroup>
    <OutputType>exe</OutputType>
  </PropertyGroup>
```
2. Or you should fix the `OutputType` tag in the second property group, which seems to be spelled wrong as `OutputTypeEx`-  

```
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <AssemblyName>Nugety.DependencyCopy</AssemblyName>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <Version>1.0.0</Version>
    <AssemblyTitle>Nugety.DependencyCopy</AssemblyTitle>
    <IncludeBuiltProjectOutputGroup>true</IncludeBuiltProjectOutputGroup>
    
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Company>ThinkAbout</Company>
    <Authors>Clare Moore, Patrick Nolan</Authors>
    <PackageIconUrl>https://raw.githubusercontent.com/thinkabouthub/NugetyCore/master/nugety_icon.png</PackageIconUrl>
    <PackageTags>nugety;nugetydependencycopy;c#</PackageTags>
    <PackageReleaseNotes>Initial Release</PackageReleaseNotes>
    <ApplicationIcon />
    <OutputType>exe</OutputType>
    <StartupObject />
  </PropertyGroup>
```


Please let us know if this fixes your problem.

**Comment by ThinkAboutGitHub** [comment]
Thank you! I have clearly been staring at that for too long, I have fixed the Outputtype tag and its now working correctly.

**Comment by mishra14** [comment]
@ThinkAboutGitHub great to hear that your issue is fixed!
I am going to close this bug.

@maartenba If you are seeing the same issue then please feel free to reopen. 
Or if you have a different cause then, please make a new issue with relevant info.

**Comment by maartenba** [comment]
@mishra14 Seems the above indeed fixed it - seem to have looked over the property.
