### ISSUE TITLE
Some files are being locked when using nuget.exe v4.3.0-preview3

### ISSUE THREAD

**Issue by UweKeim** [NuGet/Home#5515]
Not a much detailed buth rather vague error report, still I want alt least document it here:

Having various build scripts where I use nuget.exe from batch/[CS-Script](https://github.com/oleg-shilo/cs-script) files to copy files and build my SLN files through MSBUILD, I discovered the following:

Since switching to "[nuget.exe (v4.3.0-preview3)](https://dist.nuget.org/index.html)", I keep getting locked files every now and then during the second time I call my build scripts after I reboot my Windows 10 machine and having Visual Studio 2017 opened on the same SLN.

Sometimes my build scripts run OK. Most of the time getting I'm getting locking errors and my build script fails.

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4322,5): error MSB3021: Die Datei "c:\P\ZetaUploader-dev\Core\Source\packages\Microsoft.Net.Compilers.2.2.0\tools\Microsoft.CodeAnalysis.CSharp.dll" kann nicht in "bin\roslyn\Microsoft.CodeAnalysis.CSharp.dll" kopiert werden. Der Zugriff auf den Pfad "bin\roslyn\Microsoft.CodeAnalysis.CSharp.dll" wurde verweigert. [c:\P\ZetaUploader-dev\Core\Source\WebMain\WebMain.csproj]

_(German error message, sorry)_

There are several other locking errors following like this one.

My impression is that there is something strange in the way the nuget.exe v4.3.0-preview3 locks files, in correlation with Visual Studio 2017.

When switching back to "[nuget.exe (v4.1.0)](https://dist.nuget.org/index.html)", and closing Visual Studio 2017, no more locking occurs.

**Comment by zhili1208** [comment]
@UweKeim Could you share any small repro steps or how you use nuget.exe and msbuild in your script?

**Comment by UweKeim** [comment]
Sorry, I have to withdraw this ticket.

After long tries, it also happens with nuget.exe 4.1.0.

Seems to be more of an issue with Visual Studio 2017 and/or other components on my system.

**Comment by UweKeim** [comment]
In case anyone has a similar issue:

I was able to reduce the issue to an executable called "VBCSCompiler.exe" that lives inside the "bin\roslyn" folder of my website.

When calling "msbuild.exe" via command line, it seems that this executable isn't cleaned up upon exit of the build process.

The pragmatic solution in my case was to simply kill the "VBCSCompiler" at the very beginning of my build script.
