### ISSUE TITLE
Improve NuGet UI to invert icons to match the current VS theme

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5518]
Observed while working on https://github.com/NuGet/Home/issues/5420

Currently we have only one set of NuGet icons for VS. We should add feature to -

1. Detect current VS theme.
2. Either choose the right icon based on the theme or invert icons in code.

It might be possible to leverage existing VS APIs for this - 

```
Color inversion for dark themes

In order to make icons appear with the correct contrast ratio in the Visual Studio dark theme, an inversion is applied programmatically. 
The colors in this guide have been chosen in part so that they invert correctly. 
Restrict your use of color to this palette, or you will get unpredictable results when the inversion is applied.
```
Source - https://msdn.microsoft.com/en-us/library/mt186350.aspx

**Comment by mishra14** [comment]
cc: @anangaur

**Comment by donnie-msft** [comment]
Closing as no longer relevant. We now use an icon asset. A better tracking issue for this is to move the default package icon to image service: https://github.com/NuGet/Home/issues/5937
