### ISSUE TITLE
NuGet update slow in VS2015/2017 despite add reference batching

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#5519]
Issue came in the email from one of the internal customer:
takes about an hour to update 15 packages in 6 projects out of 178 projects total in the solution.

We've got the logs and repro solution.

**Comment by jainaashish** [comment]
Most of the time is being spent in AddReference apis for this issue. We already added batch apis to improve performance in this case but somehow these AddReference calls aren't being batched correctly and so each add reference is being executed separately. Dropped an email to Project System to look further and provided them the etl logs.

**Comment by jainaashish** [comment]
Corresponding MSBuild issue# https://github.com/Microsoft/msbuild/issues/2265

**Comment by davkean** [comment]
@jainaashish Note that MSBuild issue isn't the bug - that's just an incidental performance issue, it's not going to be the cause of the bulk of the issue.

**Comment by jainaashish** [comment]
Logged corresponding Project-System bug - https://github.com/dotnet/project-system/issues/2630

**Comment by RudeySH** [comment]
@mishra14 Why was this closed? I'm also having issues with NuGet update performance, similar to what is described here and in #4534.

**Comment by jainaashish** [comment]
@RudeySH because the issue has been moved to another team - https://github.com/dotnet/project-system/issues/2630 and they are working on it.
