### ISSUE TITLE
Multi targetting with conditional references copies only one version to each output

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5520]
_From @Roemer on June 28, 2017 7:49_

## Steps to reproduce
Create a multitargetting project which includes different versions of an assembly based on the target.
For example:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net40;net45</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net35'">
      <HintPath>..\libs\Interop\3.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net40' Or '$(TargetFramework)'=='net45'">
      <HintPath>..\libs\Interop\4.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

</Project>
```

## Expected  behavior
In each output folder is the correct referenced file.
In this example, net35 should have the 3.5 version of the Interop.UIAutomationClient.dll and net40 and net45 should have the 4.5 version of the Interop.UIAutomationClient.dll.

## Actual behavior
All three outputs contain the 3.5 version of the Interop.UIAutomationClient.dll.

## Environment data
`dotnet --info` output:

> .NET Command Line Tools (1.0.4)
> 
> Product Information:
>  Version:            1.0.4
>  Commit SHA-1 hash:  af1e6684fd
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  6.3.9600
>  OS Platform: Windows
>  RID:         win81-x64
>  Base Path:   C:\Program Files\dotnet\sdk\1.0.4

## Other notes
I had to remove net35 in order to build with ```dotnet msbuild``` (and not with Visual Studio 2017) and just modified the file that the 3.5 version of the dll is referenced in net40 and the 4.5 version in net45 with the same result: both contain the 3.5 version.

_Copied from original issue: dotnet/cli#7015_

**Comment by livarcocc** [comment]
_From @Roemer on June 28, 2017 13:45_

The only workaround I could think of for now would be to not copy the dlls to the output and using post-build hooks to manually copy the files.

**Comment by livarcocc** [comment]
@nguerrera can you take a look? @Roemer have you tried moving the condition into the ItemGroup and then having the 3.5 and 4.0/4.5 references inside these conditioned ItemGroups instead?

**Comment by livarcocc** [comment]
_From @nguerrera on June 28, 2017 19:57_

@livarcocc The conditions are fine where they are.

@Roemer I cannot reproduce this issue. Here is my attempt showing the correct behavior:  [ct.zip](https://github.com/dotnet/cli/files/1110040/ct.zip)

Is it possible that an error has caused the 3.5 Interop.UIAutomationClient.dll to land in the ..\libs\Interop\4.5\ folder? I ask because I actually had build authoring issue that caused that in my first attempt to make the output directories line up directly to what your reference hint paths expect.

**Comment by livarcocc** [comment]
_From @Roemer on June 28, 2017 20:52_

Hmm I must say I cannot reproduce it with the pc I am right now. Will double-check tomorrow with the one where I found the issue.

**Comment by livarcocc** [comment]
_From @Roemer on June 29, 2017 9:32_

The problem is actually something different. I Want to add those library files to the generated nuget assemblies as well. For that I use:
```xml
<ItemGroup Label="Additional nuget files">
  <None Include="..\libs\Interop\3.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net35" />
  <None Include="..\libs\Interop\4.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net40;lib\net45" />
</ItemGroup>
```

I tried having an `Interop\net35`, `Interop\net40` and `Interop\net45` folder (where net40 and net45 have the same content) and just using the ```$(TargetFramework)``` variable in the path like:
```xml
<ItemGroup Label="References">
  <Reference Include="Interop.UIAutomationClient">
    <HintPath>..\libs\Interop\$(TargetFramework)\Interop.UIAutomationClient.dll</HintPath>
    <EmbedInteropTypes>false</EmbedInteropTypes>
    <SpecificVersion>false</SpecificVersion>
  </Reference>
</ItemGroup>

<ItemGroup Label="Additional nuget files">
  <None Include="..\libs\Interop\$(TargetFramework)\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\$(TargetFramework)" />
</ItemGroup>
```
This works for the ```Reference Include``` but for some reason not for the ```None Include``` :(

Adding a `Condition` to both `None Include` also does not work. It seems that the variables are not defined in the `None Include`.

**Comment by livarcocc** [comment]
_From @Roemer on June 29, 2017 10:31_

I actually can't make this work with the csproj. Maybe someone of you got an idea. Otherwise I probably need to go back to nuspec or cake for building the nuget packages.
I added my sample here: [ReproSample.zip](https://github.com/dotnet/cli/files/1111677/ReproSample.zip)

**Comment by livarcocc** [comment]
_From @Roemer on June 29, 2017 10:41_

The problem seems to be that the files to include into the nuget are "added" to the project (with `None`) and according to [this](https://blogs.msdn.microsoft.com/manishagarwal/2005/09/28/resolving-file-references-in-team-build-part-2/) it first searches in the project files. That is probably why it is using the "wrong" file in the output.
The correct solution should be to find a way to add files to the nuget package without adding them to the project.

**Comment by livarcocc** [comment]
Given that this is an issue with pack, I am moving this to NuGet. If there this turns out to require changes in the CLI/SDK, please, just move it back. We will be glad to help.

**Comment by Roemer** [comment]
# I will recap the issue here

### Steps to reproduce
Create a project with the following content:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net45</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net35'">
      <HintPath>..\libs\Interop\3.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="Interop.UIAutomationClient" Condition="'$(TargetFramework)'=='net45'">
      <HintPath>..\libs\Interop\4.5\Interop.UIAutomationClient.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

  <ItemGroup Label="Additional nuget files">
    <None Include="..\libs\Interop\3.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net35" />
    <None Include="..\libs\Interop\4.5\Interop.UIAutomationClient.dll" Pack="true" PackagePath="lib\net45" />
  </ItemGroup>
  
</Project>
```
### Expected result
In build output there should be the .net folders with either the 3.5 oder 4.5 version of the interop.
Also there should be a nuget package with the interop dlls.

### Effective result
Because the `None Include` kinda adds the files to the project, the 3.5 version is copied to the output of both .net versions. The nuget package is fine.

There should be another way to add additional files to a nuget package wihout adding them to the project.

Here's a sample project:
[ReproTest_Del.zip](https://github.com/NuGet/Home/files/1117054/ReproTest_Del.zip)

**Comment by Roemer** [comment]
Please close, I rewrote the issue into #5523
