### ISSUE TITLE
Question: Nuget.Client Something like NugetFolderProject that uses cache folder directly

### ISSUE THREAD

**Issue by danwalmsley** [NuGet/Home#5524]
Hi,

     I have been using Nuget.Client api, and I would like to try something perhaps a little unusual.

I would like something like NugetFolderProject, expect where it just uses the packages directly from the cache rather than copying to a separate folder.

Is there a way to get the nuget cache folder? or a recommended way to achieve the above?

**Comment by nkolev92** [comment]
I assume you are using packages.config, with that in mind there's a few ways to solve this. 
In packages.config you can use repository path in your NuGet config. 
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

You can move to package reference. By default package reference downloads the packages to a global packages folder and each project would just reference the package from the global packages folder and not create multiple copies.
