### ISSUE TITLE
RestoreAdditionalProjectSources nominations for multi TFM projects are different

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5529]
Related to https://github.com/NuGet/Home/issues/5478

Versions:
Latest NuGet
SDK preview3 and newer

In the multi-tfm case, the nominations for the different TFMs contain different values for the above mentioned property.

netcoreapp nominations contain the fallback folder value while the net45 in my case does not contain any. 

NuGet expects a single value, and because of that we hard fail. 
The consequences are that the cache is not initialized and restore won't happen at all. 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0;net45</TargetFrameworks>
  </PropertyGroup>

</Project>
```

I've verified that adding adding a property like RestoreSources in the csproj does arrive in the nominations for both tfms. 

Solution:

I can see why it might make some sense on SDK side, but in NuGet currently we expect 1 distinct value per project. 
NuGet does not have the ability to categorize sources based on TFM and I'm not sure it makes sense adding support of it. 

By adding the ability to specify restore settings as msbuild properties however like RestoreSources property however, a user can technically create a csproj by conditioning on a tfm that would cause us to hit the same issue. 

We need to discuss what our options are. 

The easiest (imo best) approach here would be for the SDK to just add this property for the non-netcore nominations as well. 

//cc 
@rrelyea @livarcocc @emgarten

**Comment by livarcocc** [comment]
Like you said, this would just reduce the likelihood of this being hit. Customers could edit their project to get to this as well.

Now, regarding the RestoreAdditionalProjectSources, that should be doable in the SDK. But this difference may still happen, for instance, for projects that target netstandard2.0 and say netstandard1.6, for whatever reason. 2.0 will have a fallback folder, while 1.6 will have the package source. Will we hit this as well? And what about projects with netcoreapp1.x and netcoreapp2.0?

**Comment by alpaix** [comment]
Just discovered `NuGet.sln` won't load in Visual Studio 15.3 Preview 4+ due to this bug.
Whereas number of our core projects target `netstandard1.3` and `net45`.

**Comment by livarcocc** [comment]
This is being fixed by: https://github.com/dotnet/sdk/pull/1409. However, it will require changes in Nuget and the ProjectSystem as well.

**Comment by emgarten** [comment]
This may also be fixed by: https://github.com/NuGet/Home/issues/5596
