### ISSUE TITLE
4.3.0-preview3 expects certain targets to exist (nuget.exe regression, msbuild /t:restore was broken)

### ISSUE THREAD

**Issue by MikhailArkhipov** [NuGet/Home#5530]
Wix (MSI) projects do not have `_GenerateRestoreProjectPathWalk` or `_GenerateRestoreGraphProjectEntry`. 

`nuget.exe restore Mysolution.sln` fails if solution contains wixproj.
```
E:\A\_work\4\s\private\src\Setup\RemoteBundle\SetupRemoteBundle.wixproj : error MSB4057: The target "_GenerateRestoreGraphProjectEntry" does not exist in the project.
```
Workaround: added
```
  <Target Name="_GenerateRestoreProjectPathWalk" />
  <Target Name="_GenerateRestoreGraphProjectEntry" />
```
to my wix projects for now.

**Comment by vanjar** [comment]
Thanks for workaround

**Comment by emgarten** [comment]
This error occurs when projects do not include the common props/targets that bring in restore targets.

Previously these projects were being skipped but it looks like the improvements to error handling are now causing projects which are invalid for restore to fail completely. Restore should ignore these projects and warn instead.

**Comment by emgarten** [comment]
Moving to 4.3 for triage discussion and further investigation.
