### ISSUE TITLE
VS2017 Community csproj doesn't like wildcards

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#5537]
_From @moraleslos on May 8, 2017 20:4_

I'm converting one of my asp.net core projects from VS2015 that uses project.json to VS2017 community that converts it to csproj.  This project uses openiddict (and related libs).  My csproj file contains this:

```
    <PackageReference Include="OpenIddict" Version="1.0.0-*" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="1.0.0-*" />
    <PackageReference Include="OpenIddict.Mvc" Version="1.0.0-*" />
    <PackageReference Include="AspNet.Security.OAuth.Validation" Version="1.0.0-*" />
```

When building the above I get the following errors:
**Unable to resolve 'OpenIddict.Mvc(>=1.0.0)' for '.NETCoreApp,Version=v1.1'**
Same for the other 3 packages with wildcards.  When I explicitly set the version numbers for those, it builds ok:

```
<PackageReference Include="OpenIddict" Version="1.0.0-beta2-0614" />
<PackageReference Include="OpenIddict.EntityFrameworkCore" Version="1.0.0-beta2-0614" />
<PackageReference Include="OpenIddict.Mvc" Version="1.0.0-beta2-0614" />
<PackageReference Include="AspNet.Security.OAuth.Validation" Version="1.0.0" />
```

Is there a bug when using wildcards in csproj files?

Attached is the VS2017 I'm using
![image](https://cloud.githubusercontent.com/assets/4968017/25822794/73ddfb82-33ff-11e7-8e88-0bab59c1c7a3.png)

_Copied from original issue: aspnet/Tooling#1035_

**Comment by TravisBoatman** [comment]
VS Developer Community post for more exposure: https://developercommunity.visualstudio.com/content/problem/53224/vs2017-community-csproj-doesnt-like-wildcards.html

**Comment by mishra14** [comment]
I cannot repro this with D15Rel 26725.2

I have asked the customer to provide a csproj file.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
