### ISSUE TITLE
NU1701 - Change the wording of this warning

### ISSUE THREAD

**Issue by g0t4** [NuGet/Home#5538]
In a netcoreapp2.0 project, if I add a package that targets net461, I get a new warning as of 2.0 preview2:

> /api/api.csproj : warning NU1701: Package 'Faker.Net 1.0.3' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'. This may cause compatibility problems.

I had a hunch that this was just warning me about the new behavior in 2.0 to reference netfx packages. But I wasn't certain from the message alone. Upon looking up `NU1701` here https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings#nu1701 I found an explanation that I understood: 
> PackageTargetFallback was used to select assets from a package. This is a warning to let the user know that the assets may not be 100% compatible.

Two things helped me verify what the warning was really about: `PackageTargetFallback was used to select assets` and `may not be 100% compatible`

Could we use some of this explanation in the warning? 

Perhaps:

> /api/api.csproj : warning NU1701: Package 'Faker.Net 1.0.3' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'.   This package may not be 100% compatible.

or

> /api/api.csproj : warning NU1701: Package 'Faker.Net 1.0.3' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'.   This package may not be 100% compatible because AssetTargetFallback was used to select assets from this package.

**Comment by emgarten** [comment]
@anangaur would you take a look at the text of this message?

**Comment by anangaur** [comment]
I like the first suggestion. I would avoid the use of `PackageTargetFallback` or `AssetTargetFallback` terms here as that's unnecessary confusion.

Proposed text:
> /api/api.csproj : warning NU1701: Package 'Faker.Net 1.0.3' was restored using '.NETFramework,Version=v4.6.1' instead the project target framework '.NETCoreApp,Version=v2.0'.   This package may not be fully compatible with your project.

**Comment by g0t4** [comment]
Sounds good to me, if you want I can create a PR

-- 



----------
On Wed, Jul 5, 2017 at 7:27 PM, Anand Gaurav <notifications@github.com>
wrote:

I like the first suggestion. I would avoid the use of PackageTargetFallback
or AssetTargetFallback terms here as that's unnecessary confusion.

Proposed text:

/api/api.csproj : warning NU1701: Package 'Faker.Net 1.0.3' was restored
using '.NETFramework,Version=v4.6.1' instead the project target framework
'.NETCoreApp,Version=v2.0'. This package may not be fully compatible with
your project.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/NuGet/Home/issues/5538#issuecomment-313253810>, or mute
the thread

**Comment by anangaur** [comment]
Sure. Go ahead. :)

**Comment by g0t4** [comment]
Should I update the message in https://github.com/NuGet/NuGet.Build.Localization?

i.e. https://github.com/NuGet/NuGet.Build.Localization/blob/8f3a16696bfaf39c22963fcd21feb9cdf5d66eed/localize/ITA/15/NuGet.Commands.dll.lcl#L945

I obviously can't update all the translations :)

**Comment by emgarten** [comment]
@g0t4 you don't need to worry about localization, that will be updated later.

**Comment by g0t4** [comment]
PR ready, do we need to do anything to make sure that the wiki and localization get updated? Create issues?

wiki: https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings#nu1701

**Comment by rohit21agrawal** [comment]
@g0t4 you don't have to worry about localization at all.

**Comment by anangaur** [comment]
I made the changes to the [wiki](https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings)
