### ISSUE TITLE
Occasionally see the error: Error occurred while restoring NuGet packages: The supplied user buffer is not valid for the requested operation.

### ISSUE THREAD

**Issue by BillHiebert** [NuGet/Home#5539]
Please read the following information before posting the issue.
## Details about Problem
Sometimes after creating a new ASP.NET Core web application in Visual Studio, the restore fails with the following in the output window:
```
Restoring NuGet packages...
Time Elapsed: 00:02:37.7699079
========== Finished ==========

Error occurred while restoring NuGet packages: The supplied user buffer is not valid for the requested operation.
```

NuGet version (x.x.x.xxx): From VS help About: Nuget Package Manger 4.3.0. Note that I have seen this occur since VS2017 RTW.

VS version (if appropriate): 15.3.0 Preview 3.0 [26630.2.d15prerel]

OS version (i.e. win10 v1607 (14393.321)): 10.0.15063

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem
This only occurs occasionally, 
1. Start VS
2., New ASP.NET (.Net core) web application
3. Wait for restore to complete and check the output window. 

Manually, restoring via Restore Nuget Packages corrects it for me.
...

**Comment by nkolev92** [comment]
@BillHiebert 
Does this issue still reproduce? 


I am not sure we can much here with the current information.

**Comment by BillHiebert** [comment]
It was pretty common for a while but I haven't noticed it in recent builds. Feel free to close and I can re-activate it if I see it again.

**Comment by nkolev92** [comment]
Thanks, closing for now.
