### ISSUE TITLE
Initialization error when opening console

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#554]
Reported originally by @GeertvanHorrik #547

btw. when I open package manager console:

```
Each package is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

Unable to satisfy package dependency constraints.
PM> 
```

Is the "Unable to satisfy package dependency constraints" normal?

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@20785be9ec6e4b521e3c945c2ae986190fb18db9

**Comment by danliu** [comment]
this issue needs more fix. Now I see a null reference exception when opening an existing solution with packages folder deleted. Will send a review.
