### ISSUE TITLE
Project reference version when packing project

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5540]
_From @danielwertheim on July 5, 2017 20:24_

I have a solution with two projects **A** and **B** where **B depends on A** as a project reference.

I've tried packing the csprojs using `dotnet pack` and `msbuild` with target "Pack" passing version. This works fine, how-ever, what I want is to set the passed version on the project reference to A from B. How do I do this? The result should be A.1.0.0.nupkg and B.1.0.0.nupkg where B -> A with fixed version 1.0.0

Previously (.NET classic) and using NuGet to pack with NuSpec, you could inject the `$version` to the dependency. Is that the way I have to go now as well? Using a NuSpec file?

_Copied from original issue: dotnet/cli#7079_

**Comment by Necroskillz** [comment]
see my issue: #5525. I think we have the same problem.

/cc @danielwertheim

**Comment by danielwertheim** [comment]
Turns out that it works if you ensure you pass the `\p:Version=<>` to the `restore` target not the `pack` target. Would expect it to work with `pack` as well, unless you specify `NoBuild`

@livarcocc With that sorted... do you know how to get the `restore` target to generate locked versions like `[1.2.3]` instead of `1.2.3`?

**Comment by Necroskillz** [comment]
First issue is already solved in .NET Core 2 preview 2 (see #4337).

For your other question - see my issue above. I would also like to be able to do this.

**Comment by aarondandy** [comment]
Thanks for the tip @danielwertheim . For me, since I am using `dotnet msbuild` the workaround was to prefix my target list with Restore like so: `/t:Restore;Build;Pack`

**Comment by rohit21agrawal** [comment]
@aarondandy with .net core 2.0 having released today, a restore happens automatically for build. if you pack your project with .net core 2.0 now, it will automatically build (and restore for you) preserving any pack arguments you pass and making them consistent with restore.

**Comment by nkolev92** [comment]
Are all the questions answered here? 

@danielwertheim @rohit21agrawal 

From what I can tell from the replies, it seems like it's resolved. 

I will close it, but please do chime in, if you didn't get something answered, and we'll be happy to reopen.
