### ISSUE TITLE
Automatic package restore hangs VS 15.3

### ISSUE THREAD

**Issue by bricelam** [NuGet/Home#5541]
VS 15.3 Preview 3 is unusable on the [aspnet/EntityFramework](https://github.com/aspnet/EntityFramework) repo's solution. It stalls after every key press in the editor and eventually hangs indefinitely. Unchecking **Allow NuGet to download missing packages** avoids the issue.

Sorry I haven't been able to narrow it down any further.

This is on a clean install with the following workloads selected:
- Universal Windows Platform development
- .NET desktop development
- ASP.NET and web development
- Mobile development with .NET
- Visual Studio extension development
- .NET Core cross-platform development

cc @ajcvickers @Eilon

**Comment by Eilon** [comment]
NuGet folks - if there's some kind of logging or debug setting we can enable to provide more info please let us know.

**Comment by jainaashish** [comment]
Can you provide the dump file for this hang?

**Comment by bricelam** [comment]
Repairing Windows seems to have fixed the issue. Many .NET-related things were behaving strangely. (Settings app was freezing, F5 in VS wouldn't show the Console...) I'll let know if it starts happening again.

**Comment by bricelam** [comment]
I spoke too soon. I'll try go get a dump...

**Comment by bricelam** [comment]
This only seems to happen after I restore with a local copy of `dotnet.exe` version 2.0.0-preview3-* then try to use the solution in VS with .NET Core 2.0 Preview 2 installed.

Probably low priority since it's an unsupported scenario and will most likely sort itself out in 2.0.0 RTM.

**Comment by nkolev92** [comment]
@bricelam Are you still hitting any problems here?
Thanks.

**Comment by bricelam** [comment]
Nope. Either RTM fixed it or my workflow changed to avoid it. No problems lately.

**Comment by nkolev92** [comment]
Cool. 
I'll close this issue now.
