### ISSUE TITLE
NuGet pack does not automatically detect files and dependencies for multi-platform project

### ISSUE THREAD

**Issue by RezaJooyandeh** [NuGet/Home#5545]
To create a package for a Any CPU csproj, one could have practically an empty nuspec:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>$id$</id>
    <version>$version$</version>
    <title>$id$</title>
    <authors>$author$</authors>
    <owners>$author$</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>$description$</description>
  </metadata>
</package>
```
and everything would be detected when we do `nuget pack foo.csproj` and all the dependencies would be added automatically. But if the project is multi-architecture, we should manually specify all the files and dependencies and keep updating the dependencies versions which could cause a lot of mistakes and it is a big hassle. It would be great if nuget client would automatically create the package for those projects too.

**Comment by nkolev92** [comment]
There is currently no support for packing .net core projects in nuget.exe.

We have a task for that here, please follow and up vote there. 

https://github.com/NuGet/Home/issues/4491

As a workaround, can you please try to use dotnet.exe  pack?

Thanks!
