### ISSUE TITLE
NuGet restore path differs from NuGet install path for source code files

### ISSUE THREAD

**Issue by KatarinaOttosson** [NuGet/Home#5547]
When installing a nuget package to a Visual Studio solution the package content will be restored to a package folder and if the package consists of dll's, the solution will reference these dll's as located in this package folder.
Building the same solution on another machine will restore the nuget package to the package folder and included dll's will be found as referenced by solution projects, all working very smoothly. If, however, the nuget package consists source code  files, such as .cs or .js files, installing the nuget package will also restore the content to the nu package folder but the files will also be 'sucked' into the solution project structure and when building the solution they are used from this internal project structure. Building that same solution on another machine will restore the nuget package to the package folder but the files will NOT also be propagated to the project internal structure to wich they were install thus these files will be missing -> build failing.
This also applies to use of NuGet restore via TFS build automation Nuget Installer plugin.
We have had a practice to check-in installed nuget packages to source control, also including internally installed files, thus this has not been a problem. However, as a part of the work to ensure that 3pp SW is used correctly and in accordance with license agreements in our SW we now wish to avoid check-in of 3pp SW and instead strictly use nuget restore with restrictions only to use our own nuget server feeds with validated and allowed SW. As described above this cause us problems when it comes to nuget restore of source code. Am I doing wrong, is there a way to handle this so that nuget packages will be restored as used by the solution?

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (3.5.0 / 4.1.0):

VS version (VS 2015):

OS version (Win7 Enterprise SP1):

Worked before? -  Not to my knowledge

## Detailed repro steps so we can see the same problem

1. Install for example Angular.UI.Bootstrap to a C# project. This will result in a Scripts\angular.ui folder with 4 ui.bootstrap.xx.js files added to the project. Save and close solution and check-in the solution but NOT the installed angular.ui structure with files.

2. Open the solution on another computer and build the solution. This will result in the Angular.UI.Bootstrap restored to the package folder and a Scripts\angular.ui folder with 4 ui.bootstrap.xx.js files is expected in the project but the ui.bootstrap.xx.js files are missing.
...

### Sample Project
[NuGetRestoreSourceCode_Nuget_restored_packages_omitted.zip](https://github.com/NuGet/Home/files/1130410/NuGetRestoreSourceCode_Nuget_restored_packages_omitted.zip)
[NuGetRestoreSourceCode_after_install_Nuget_packages.zip](https://github.com/NuGet/Home/files/1130412/NuGetRestoreSourceCode_after_install_Nuget_packages.zip)

**Comment by nkolev92** [comment]
Unfortunately this is by design in the packages.config world. 

In packages.config, nuget install in VS is the only command that would add references/copy content files to the project structure. 

NuGet restore would just download the packages and not do any actions with the project system.

To workaround this, you should check-in the content files into your versioning system.
