### ISSUE TITLE
ArgumentOutofRangeException got logged to ActivityLog.xml when using the powershell manager console

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#555]
ArgumentOutofRangeException got logged to ActivityLog.xml when using the powershell manager console

Repro steps:
No clear repro steps available. This issue happened randomly and following is the call stack

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: span at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span) at NuGetConsole.Implementation.Console.WpfConsoleClassifier.GetClassificationSpans(SnapshotSpan span) at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__1.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__1.MoveNext()

**Comment by deepakaravindr** [comment]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: span at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span) at NuGetConsole.Implementation.Console.WpfConsoleClassifier.GetClassificationSpans(SnapshotSpan span) at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__1.MoveNext() at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__1.MoveNext()

**Comment by yishaigalatzer** [comment]
This means we need to write good unit tests for the classifier

**Comment by deepakaravindr** [comment]
https://github.com/NuGet/Home/issues/652 is the same as this one.
And,
Customer also observed the same issue with https://github.com/NuGet/Home/issues/1470
