### ISSUE TITLE
Visual Studio 2017 Package Manager Console Requires PowerShell 2.0

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5550]
PowerShell 2.0 has gotten the ban hammer at work due to security issues, since then the Visual Studio package manager console won't work.

I keep getting the error 
Error: The Package Manager Console requires PowerShell 2.0 runtime, which is not detected on this machine. Please install the PowerShell 2.0 from http://support.microsoft.com/kb/968929 and restart Visual Studio.

I am running a windows 10 machine that was upgraded from windows 7. I tried looking through previous tickets that had similar issues and seemed to have been resolved. I tried some of the suggested solutions to the problem to no avail. Any help on this issue would be greatly appreciated. 

Thanks

**Comment by OraDotNetDev** [comment]
Looks as though there's a fix [here](https://github.com/NuGet/Home/issues/5294) but it's waiting to get pushed into the live stream?

**Comment by rohit21agrawal** [comment]
@OraDotNetDev is right. the fix will be available in Visual Studio 2017 Update 3 soon.

**Comment by ghost** [comment]
Thanks.

**Comment by rrelyea** [comment]
VS 2017 version 15.3 shipped on 8/14/2017 with the fix for bug #5294 . So this should be fixed, as well, since this is a duplicate.
