### ISSUE TITLE
Nuget restore throws exception in multiple versions of VS

### ISSUE THREAD

**Issue by attilah** [NuGet/Home#5552]
Building from VS is not working, building via dotnet.exe works as expected.

I’ve attached the repro project.

The reason to cause the failure is the targetFrameworks element. If it is net462 OR netstandard1.5 it works, if it is both, then don’t.

I’ve dotnet core sdk 2.0.0-preview3-006689 on my machine.

VS2017 15.2 Works, but I think that does not pickup this version of the SDK.
VS2017 15.3 Preview 3 Throws the same error
VS2017 15.3 Preview 4 26706.0.d15rel (15int3) Throws the same error

Stacktrace:

Error occurred while restoring NuGet packages: System.InvalidOperationException: The operation failed as details for project Orleans.PlatformServices could not be loaded.
[repro.zip](https://github.com/NuGet/Home/files/1132125/repro.zip)
   at NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
   at NuGet.PackageManagement.DependencyGraphRestoreUtility.<GetSolutionRestoreSpec>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestorePackageSpecProjectsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<RestoreAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.SolutionRestoreManager.SolutionRestoreJob.<ExecuteAsync>d__15.MoveNext()

And because of this, assets.json files are not generated, so build fails.

**Comment by rrelyea** [comment]
@attilah  reached out in email with:

After I hit another problem, this issue was created for CPS: https://github.com/dotnet/project-system/issues/2601
Since the same solution caused the https://github.com/NuGet/Home/issues/5552 error I think this can help your investigation and fix.
After I replaced the project factory guids, the same solution was building correctly!

**Comment by nkolev92** [comment]
Likely dup of https://github.com/NuGet/Home/issues/5529

**Comment by simonfox** [comment]
Context:
VS2017 15.4.0
Package Manager Console Host Version 4.4.0.4475
Using VS2017 `csproj` format, target `net461`
xunit/xunit.runner.visualstudio 2.3.0 (although this is not an xunit issue as tests run fine using the console runner)

Not sure this is the right place but I'm running into something similar to this...

Problem started after updating to VS2017 15.4.0 (same solution working fine on my laptop - VS2017 15.3.5)

Test discovery is failing (silently, but no tests are found).
In `%Temp%/VSFaultInfo` I have `ErrorInformation.txt` containing the following stacktrace:

```
Exception:
 System.InvalidOperationException
 The operation failed as details for project Drive.Search.DomainServices.UnitTest could not be loaded.
 NuGet.PackageManagement.VisualStudio.NetCorePackageReferenceProject.GetPackageSpecsAsync(DependencyGraphCacheContext context)
 NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass10_0.<<GetInstalledPackages>b__0>d.MoveNext()
 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
 Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
 Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
 NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages(Project project)
 Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.PackageServicesProxy.GetInstalledPackages(Project project)
 Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService.ProcessProjectChange(Solution solution, ProjectId projectId)
```

**Comment by simonfox** [comment]
@rrelyea @alpaix sorry to ping but wasn't sure if you will have got a notification re my comment above? Let me know if you want anymore details or if you want me to just open a new issue...

**Comment by simonfox** [comment]
ok so the test discovery issue was unrelated. I deleted the `.vs` (containing the `.suo`) and now test discovery is working again. I still get the faults above, although they do not seem to affect usage of VS i.e. VS, including NuGet, appears to be functioning correctly.
