### ISSUE TITLE
nuget service is down? i am getting error on downloading the package

### ISSUE THREAD

**Issue by josephjoychristopher** [NuGet/Home#5554]
nuget service is down? i am
![image](https://user-images.githubusercontent.com/8872113/28012094-62494296-6582-11e7-8b43-a787f7b28a30.png)
 getting error on downloading the package

**Comment by rrelyea** [comment]
Which package source do you have set in the drop down list box in Package Manager console? (name & url?)

**Comment by mishra14** [comment]
@josephjoychristopher Are you still facing this issue?

It seems that the source is empty, maybe fix the sources to point to a valid url. You can read more about sources from our [docs](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui#package-sources).
