### ISSUE TITLE
What is the msbuild /t:pack counterpart for nuget's IncludeReferencedProjects option

### ISSUE THREAD

**Issue by bigwad** [NuGet/Home#5558]
With nuget it's possible to automatically add referenced project's output into a package. How to achieve the same with msbuild /t:pack?

**Comment by rohit21agrawal** [comment]
@bigwad this is not possible out of the box right now, but you can do some msbuild magic to achieve this. let me know what scenario are you trying to solve and I will help you out with it.

**Comment by bigwad** [comment]
I have a multitarget (net45 and netstandard1.6) library project that has direct and transitive dependencies on several another multitarget library projects. I want to pack top-level library along with all its dependencies into a single package.
Would be interesting to see "msbuild magic" you mentioned but in practice I prefer simple solutions so I created .nuspec file and listed all dependencies manually.

**Comment by dasMulli** [comment]
fyi:
The main GH issue for this is probably https://github.com/NuGet/Home/issues/3891
I just summarised the ways to do it in a [StackOverflow answer](https://stackoverflow.com/questions/44976879/msbuild-multiple-dll-in-a-single-nuget-package/45004898#45004898) and uploaded an example project for the SDK csproj + nuspec at https://github.com/dasMulli/nuget-include-p2p-example (see `LibA` which adds two projects to its nupkg)
