### ISSUE TITLE
Remove all NotImplementedException instances from Nuget3

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#558]
There is round about 10 of them. This is scary stuff and it should all go away before RTM

**Comment by davidfowl** [comment]
Should the list of features be called out

**Comment by csharpfritz** [comment]
Agreed: can we put those entries into new issues?

**Comment by yishaigalatzer** [comment]
Bah, repro steps
Open nuget3 solution
Search term new notimplementedexception
Eradicate

Call it done

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet3/commit/b81dbad143b9b09a13e6875fe63aadd4c469c66a
