### ISSUE TITLE
Enable a way to add a dependency not use by the project but by children

### ISSUE THREAD

**Issue by bhugot** [NuGet/Home#5585]
Maybe I missed the configuration for it,

I have a project with build dependency that come from another lib and I need to be able to add the dependency to the other lib without import the target.

It there a way to do it?

**Comment by jhudsoncedaron** [comment]
If I understand what you want this exist but is currently bugged: https://github.com/NuGet/Home/issues/5490

**Comment by emgarten** [comment]
You can prevent packages from flowing to parent projects by adding ``PrivateAssets="all"`` to your ``PackageReference``

https://github.com/NuGet/Home/wiki/%5BSpec%5D-Managing-dependency-package-assets

**Comment by bhugot** [comment]
I would like the opposite

**Comment by emgarten** [comment]
> I would like the opposite

If you have ProjectA -> ProjectB -> PackageC

You are saying that you have ProjectA to get PackageC assets and ProjectB to get zero assets from PackageC?

**Comment by bhugot** [comment]
Yeah I want target from C

**Comment by emgarten** [comment]
> Yeah I want target from C

I don't understand what you are asking for. Would you provide a complete example similar to what I gave with A, B, and C?

**Comment by bhugot** [comment]
I use https://github.com/AArnott/CodeGeneration.Roslyn
I have my own attribute project and it pull my own generator as tool.
I would like to pull CodeGeneration.Roslyn.BuildTime that is needed with my attribute project. But this attribute project doesn't need it.

**Comment by emgarten** [comment]
The idea of adding a type of package that skips the current parent and only applies to higher generations is interesting, but I do not see this as a common scenario that would justify the extra flags or type.

The workaround for this is to reference the package at a higher level.  Please let me know if I'm missing something here.
