### ISSUE TITLE
dotnet restore works for too long (almost 2 hours)

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5586]
_From @lampersky on July 11, 2017 6:50_

## Steps to reproduce
1. Go to sln directory,
2. Run "dotnet restore Solution.sln".

## Expected  behavior
This task should finish in few seconds if nothing has changed in your dependecies.

## Actual behavior
This task takes about 7000 seconds in azure environment.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.2.9200
 OS Platform: Windows
 RID:         win8-x86
 Base Path:   D:\Program Files (x86)\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

![image](https://user-images.githubusercontent.com/6403130/28054796-a890884c-6616-11e7-919a-acf601b54e21.png)

_Copied from original issue: dotnet/cli#7123_

**Comment by emgarten** [comment]
@lampersky do you have a github repository that reproduces this?

**Comment by emgarten** [comment]
Closing due to lack of response. If this still repros in the latest CLI 2.0.0 build please let me know.

**Comment by lampersky** [comment]
Sorry guys, I've created this issue, just before my holidays. This is why I can't answer.
Here you have some example code.
[exampleCode.zip](https://github.com/NuGet/Home/files/1187278/exampleCode.zip)

with '2.0.0-preview2-006497' task dotnet restore takes 4 minutes and 9 seconds,
with '1.0.4' task dotnet restore takes only 19 seconds.

![slow](https://user-images.githubusercontent.com/6403130/28775114-9f0e6728-75f0-11e7-8014-48f1e2f07f9a.JPG)

**Comment by emgarten** [comment]
Thanks @lampersky, we will investigate

**Comment by emgarten** [comment]
I was not able to repro this with CLI 2.0.0 RTM.

Restore for me took 1500ms with `--force`

@lampersky let me know if you are still seeing this with the latest bits. If you are please provide a network trace to see where the time is being spent. Currently it looks like this is not an issue with the NuGet client.
