### ISSUE TITLE
Package is not shown as resolved in the UI

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5588]
- Create a new .NET Core console app
- Add a dependency
```
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-*" />
  </ItemGroup>
```
- It should restore at resolve 2.0.0-preview2-final.
- Now change the dependency to 2.0.0-preview2-final explicitly
```
<PackageReference Include="Microsoft.AspNetCore" Version="2.0.0-preview2-final" />
```
- The package fails to be resolved in Microsoft.AspNetCore 2.0.0-*

![pic](https://user-images.githubusercontent.com/2878341/28096624-163ef05c-665f-11e7-9519-a207e632a99b.png)
Note:
Closing and opening the solution fixes it. 
Restore actually runs here, so this seems to be only a UI only issue. 
Little bit of a redundant test since it's not really compatible, but this issue does not repro on 15.2.

**Comment by nkolev92** [comment]
This is a Project System bug. 
https://github.com/dotnet/project-system/issues/2510
Closing the NuGet bug.

**Comment by rrelyea** [comment]
Project system bug appears to be scheduled for 15.5

**Comment by rrelyea** [comment]
@PatoBeltran - please take a look at this issue as well. Another issue with *. This bug is in a partner team, but would like you to be aware since you are looking at similar issues.
