### ISSUE TITLE
Invalid fallback folder doesn't show any restore errors in visual studio

### ISSUE THREAD

**Issue by davidfowl** [NuGet/Home#5591]
I manually deleted `'C:\Users\dfowler\.dotnet\NuGetFallbackFolder` from my hard drive and tried adding a dependency to my .NET Core project. When I added it, auto restore ran and the solution explorer showed this icon:

![image](https://user-images.githubusercontent.com/95136/28107844-471ab208-669e-11e7-9642-e45ab87f98bc.png)

However, the assets file had no warning or error and the error list was empty:

![image](https://user-images.githubusercontent.com/95136/28107872-5c8e7796-669e-11e7-8d28-ea43e9ed695a.png)

When running `dotnet restore` on the command line in the project it shows the following:

```
C:\Users\dfowler\.dotnet\x64\sdk\2.0.0-preview3-006729\NuGet.targets(102,5): error : Failed to retrieve information about 'Serilog.Sinks.ElasticSearch' from remote source 'C:\Users\dfowler\.dotnet\NuGetFallbackFolder'. [C:\Users\dfowler\Documents\visual studio 2017\Projects\WebApplication17\WebApplication17\WebApplication17.csproj]
```

PS: Earlier versions of `dotnet restore` shows the searched sources and configuration files and that was *very* useful information when debugging a restore failure. How do I get that information back?

**Comment by anangaur** [comment]
cc: @mishra14 @emgarten 

>PS: Earlier versions of dotnet restore shows the searched sources and configuration files and that was very useful information when debugging a restore failure. How do I get that information back?

Agree. Should have an additional bug for this if the same doesn't exist

**Comment by nkolev92** [comment]
Duping this to https://github.com/NuGet/Home/issues/7245, while this one is older, the linked issue has more engagement.
