### ISSUE TITLE
Nuget.exe command line has stopped working

### ISSUE THREAD

**Issue by afficionaddo** [NuGet/Home#5595]
My project is not building.
Whenever I build it says "Nuget command Line has stopped working".

The errors shown in the console are:
* Error1	Unhandled Exception: System.NotSupportedException: The requested security protocol is not supported.	Coach.Business.Components

* Error2	   at System.Net.ServicePointManager.set_SecurityProtocol(SecurityProtocolType value)	Coach.Business.Components

* Error3	   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)	Coach.Business.Components

* Error4	   at NuGet.CommandLine.Program.Main(String[] args)	Coach.Business.Components

* Error5	The command ""D:\Projects\xxxxx\Releases\xxxxxxxxAdmin\.nuget\NuGet.exe" install "D:\Projects\xxxxx\Releases\xxxxxxxxx-Admin\Business.Components\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "D:\Projects\xxxxxxxx\Releases\xxxxxxx\xxxxxxx-Admin\ "" exited with code -532462766.

### Details about Problem
- I had formatted my system & took latest from TFS.
- After format, I have not been able to build my project.
- My company also recently setup a local Nexus repository & denied access to Nuget.org for downloads.
- The .nuget folder has Nuget.exe v3.3.xxx
- Whenever I double-click & exexute Nuget.exe It says "Nuget command line has stopped working".

Please help as this is a blocker in my work & I am unable to resolve this.

**Comment by emgarten** [comment]
@afficionaddo any ideas where `Coach.Business.Components` is coming from?

Would you try using the latest NuGet.exe 4.3.0? https://dist.nuget.org/win-x86-commandline/v4.3.0-preview3/nuget.exe

**Comment by afficionaddo** [comment]
Thanks for replying @emgarten.

-Coach.Business.Components is class library in my asp.net project which I use.
-Also I tried using the latest Nuget.Exe & pasted it into .nuget folder in solution. But the errors are still there.

Unable to make any headway.

**Comment by emgarten** [comment]
@afficionaddo this looks like the .NET Framework is rejecting the connection, possibly due to an unsupport SSL protocol. Are you able to repro this with nuget.org or other types of sources? If not it seems like this may be a Nexus issue.

**Comment by afficionaddo** [comment]
@emgarten Yes I tried the below:

1. Used latest Nuget.exe inside .nuget folder & tried to build. It fails with the same error.
2. Removed all package folders & tried to build project. All packages were downloaded but build still fails.

**Comment by nkolev92** [comment]
@afficionaddo Are you still able to reproduce this issue?
Have you made any progress diagnosing it?
Not sure we can do much on our side.

**Comment by TarikIbrahim** [comment]
@afficionaddo @nkolev92 
I have working solution after wasting hours , inside the ".nuget" folder press right click on "Nuget.exe" select properties then in "General" tab click "Unblock"

**Comment by bhushan-firake** [comment]
@afficionaddo Were you able to workaround this one? I have stuck with a lot of work pending.

**Comment by anangaur** [comment]
Another report: https://twitter.com/btfirake/status/1003692411036422144
cc: @nkolev92

**Comment by nkolev92** [comment]
@bhushan-firake 

Is that a Visual Studio error you have in your screen shot?
What are the actions you are taking? 

I am not sure why nuget.exe is being in VS.

**Comment by mishra14** [comment]
Closing due to lack of response.
