### ISSUE TITLE
Add support for RestoreAdditionalProjectSourcesExcludes and RestoreAdditionalProjectFallbackFoldersExcludes

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5596]
1. Read additional source and fallback folder properties in the inner build
1. Aggregate values between frameworks, this should concat all includes and then remove all excludes
1. Excluded values that do no exist in the included list will be ignored.

Property names:
* RestoreAdditionalProjectSources
* RestoreAdditionalProjectFallbackFolders
* RestoreAdditionalProjectFallbackFoldersExcludes 

Original issue:
https://github.com/NuGet/Home/issues/5529

**Comment by livarcocc** [comment]
We should also do something to remove duplicates, or that is not needed?

**Comment by emgarten** [comment]
> We should also do something to remove duplicates, or that is not needed?

Do you mean remove a source if it is also a fallback folder?

**Comment by livarcocc** [comment]
I mean, if multiple inner loops add the same source, should they be de-dupped? The only thing that should remove items from the "inserts" should be the Excludes.

**Comment by emgarten** [comment]
> I mean, if multiple inner loops add the same source, should they be de-dupped? 

Dupes will be removed as part of aggregating. I'll leave the same path in both sources and fallback folders, there might be some scenarios where it needs to be in both.
