### ISSUE TITLE
Incorrect installed version reported on NuGet Package Manager UI when floating version used

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5598]
Repro steps:

1. Create a PackageReference based project
2. Specify a floating package version dependency to it. E.g.
`    <PackageReference Include="Newtonsoft.Json" Version="10.*" />`

3. NuGet resolves to 10.0.3 the highest that matches the floating range.

Expected: On PM UI, it should show the 10.0.3 installed and should not offer any update.

Actual: It shows 10.0.0 and offers an update:
![image](https://user-images.githubusercontent.com/14800916/28182326-aafc82e2-67c0-11e7-900b-ddca6217a0da.png)

VS version:
![image](https://user-images.githubusercontent.com/14800916/28182583-88db82a2-67c1-11e7-96c1-a978ef717aec.png)

**Comment by emgarten** [comment]
Dupe of https://github.com/NuGet/Home/issues/3101
