### ISSUE TITLE
TopologicalSortUtility.GetParentCount has a high allocation rate due to LINQ

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5601]
The call to `Any` in [`TopologicalSortUtility.GetParentCount`](https://github.com/NuGet/NuGet.Client/blob/a7367359ce8d0bb3cf08f1bc884deb58526f5fa4/src/NuGet.Core/NuGet.Packaging/TopologicalSortUtility.cs#L46-L47) calls `GetEnumerator()`, resulting in substantial allocations after opening a project in Visual Studio. For the limited trace I was working with at the time, this enumerator was responsible for nearly 400MiB of heap allocations and 5% of the overall allocation cost of the trace.

This code should be expanded (using a `foreach` statement to avoid the use of LINQ, and a comment added to prevent future regressions. This change will avoid a number of less costly delegate allocations as well.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Visual Studio 2017 15.3 Preview 4

NuGet version (x.x.x.xxx): The one that comes with Visual Studio

OS version (i.e. win10 v1607 (14393.321)): win10

## Detailed repro steps so we can see the same problem

1. Open Roslyn.sln

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/1585
