### ISSUE TITLE
Package ID and package title displays are inconsisntent on nuget.org and Visual Studio

### ISSUE THREAD

**Issue by diverdan92** [NuGet/Home#5604]
## Problem 
In Visual Studio, package ID is displayed everywhere you see package details - both in search and in the package details pane. 
![image](https://user-images.githubusercontent.com/6608201/28233770-13f5b730-68ae-11e7-9f50-9d1607eb3d27.png)

In nuget.org, the package title is displayed everywhere. The only way to get the package ID is to look at the package details page where the CLI installation instructions are shown:
![image](https://user-images.githubusercontent.com/6608201/28233778-2ac2ce08-68ae-11e7-9cc5-a8947529397b.png)

![image](https://user-images.githubusercontent.com/6608201/28233784-31893574-68ae-11e7-9f74-4f3d204cc9c2.png)

This inconsistency can result in confusion as to which package is which. 

## Proposal
To promote consistency in identifying package properties, I propose you display package ID everywhere (as this is the property used to install a package from the package manager console), and show package title as supplementary information on nuget.org

For example, the Netownsoft.Json package would take the form:
Newtonsoft.Json
Title: Json.NET
in the package search, and package details page.

**Comment by rohit21agrawal** [comment]
@diverdan92  can you file this bug on nuget gallery instead since the  client is already doing the right thing?

**Comment by rohit21agrawal** [comment]
Issue moved to [NuGet/NuGetGallery #4413](https://github.com/NuGet/NuGetGallery/issues/4413) via [**ZenHub**](https://www.zenhub.com/)
