### ISSUE TITLE
Nuget for .net core does not work for packages mixed of dll libraries and client side codes like js and css

### ISSUE THREAD

**Issue by mesuttalebi** [NuGet/Home#5605]
I have a package named MT.Notifications, with this package I created a c# class (dll) for simply create javascript scripts for calling notifications in client side, and there is also a notifications.js and css files in client side, that mixed various notification libraries like toastr.js, jquery.gritter.js, bootstrap sweet alert and etc, and some overload functions to simply call a notifications. 
with asp.net mvc 5 nuget package I can add one nuget package, and it adds dll reference and also copies my js and css files into its places in Scripts folder or Content folder. 
but with .net core application I want to do same, reference my dll and also copy my client side codes into wwwroot/lib folder. 

please help this possible. I Don't want my package users install a part from nuget and another part from bower.

**Comment by emgarten** [comment]
@mesuttalebi you can provide immutable content as part of your package for PackageReference projects using `contentFiles`. 

http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

**Comment by FlukeFan** [comment]
Unless I am missing something, the contentFiles are not (and cannot be?) copied to the consuming project.

So there is currently no way to package (and consume) content like css (or js) which might be required for some projects (e.g., a library of tag-helpers that generate html requiring related css/js) using nuget and PackageReference projects.
