### ISSUE TITLE
Feature: Consider adding ability to always get latest version on build/restore

### ISSUE THREAD

**Issue by logankp** [NuGet/Home#5613]
We would like the ability to be able to always get the latest version of a package on build (or restore) without having to manually update. Something like [floating versions](https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions) but for the actual package and not its dependencies.

This could be useful for developers in an enterprise setting with a large number of in-house packages that are constantly being updated.

I apologize if this has been asked before, search didn't turn up much.

**Comment by emgarten** [comment]
> Something like floating versions but for the actual package and not its dependencies.

Floating versions only work for the directly referenced packages, not the dependencies. Can you elaborate on how this would work differently?

**Comment by logankp** [comment]
I guess I misunderstood the documentation on this feature... It appears to only work with project.json and the new project files. I tried floating versions in packages.config and got an error therefore assuming the referenced documentation was referring to another scenario.

Perhaps update the issue to add support for floating versions to packages.config/VS2015 (unless I'm missing something there too)?

**Comment by emgarten** [comment]
There is no support for floating in packages.config. Is there any reason you can't move to PackageReference or project.json to get floating support?

**Comment by logankp** [comment]
I'd love to move to PackageReference or project.json but we're dealing with WinForms code on VS2015 and there seems to be no plan to use the newer project format any time soon.

**Comment by emgarten** [comment]
You can add `PackageReference` to a WinForms projects in VS 2017. In VS 2015 you can add a project.json file to get the same behavior.

**Comment by logankp** [comment]
That's really good to know, I'll play around with that. Thanks!

**Comment by emgarten** [comment]
@logankp take a look at https://oren.codes/2016/02/08/project-json-all-the-things/ for more info on using project.json

**Comment by logankp** [comment]
Seems to work, however the package manager UI doesn't seem to play nicely with floating versions:
![image](https://user-images.githubusercontent.com/5343074/28384731-555d6ac0-6c8b-11e7-90a1-02654ebdccf9.png)

Here is my project.json:
`{
  "dependencies": {
    "Dapper": "1.50.*",
    "vanWagenen.vWImpersonation": "1.0.*",
    "vanWagenen.vWSQLDataAccess": "1.0.*"
  },
  "frameworks": { "net451": {} },
  "runtimes": {
    "win-x86": {},
    "win-x64": {}
  }
}`

And my project.lock.json:
`".NETFramework,Version=v4.5.1/win-x64": {
      "Dapper/1.50.2": {
        "frameworkAssemblies": [
          "System.Data",
          "System.Xml",
          "System.Xml.Linq"
        ],
        "compile": {
          "lib/net451/Dapper.dll": {}
        },
        "runtime": {
          "lib/net451/Dapper.dll": {}
        }
      },`

So the project.lock.json is showing the correct (latest) version but the NuGet package manager UI is not.
