### ISSUE TITLE
NuGet fails if environment variable "Version" is set

### ISSUE THREAD

**Issue by wasaczd** [NuGet/Home#5614]
## Details about Problem

NuGet product used : NuGet.exe 
NuGet Version: 4.1.0.2450

I don't understand why NuGet reads environment variable "Version". I didn't find any information about it in NuGet documentation. Please see the sample project and batches below:

## Detailed repro steps so we can see the same problem
Project:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.5</TargetFramework>
    <PackageTargetFallback>portable-net45+win8+wpa81+wp8</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Update="NETStandard.Library" Version="1.6.1" />
  </ItemGroup>
</Project>

```
Batch:
```
set Version=debug
nuget.exe restore ClassLibrary1.csproj -Verbosity detailed > nuget.log
```

After running the above batch, in "nuget.log" I see:
NuGet Version: 4.1.0.2450
Using Msbuild from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\'.
MSBuild P2P timeout [ms]: 120000
<long command line here>
NuGet.CommandLine.CommandLineException
   at NuGet.CommandLine.MsBuildUtility.<GetProjectReferencesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<GetDependencyGraphSpecAsync>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<DetermineInputsFromMSBuildAsync>d__38.MoveNext()
WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
All packages listed in packages.config are already installed.

Similar behaviour occurs when I call nuget through msbuild. 
Batch:
```
set version=debug
msbuild.exe ClassLibrary1.csproj /t:restore > nuget.log

```
After running the above batch, in "nuget.log" I see:
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 19.07.2017 13:09:37.
Project "ClassLibrary1.csproj" on node 1 (restore target(s)).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : 'debug' is not a valid version string. [ClassLibrary1.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(97,5): error : Parameter name: value [ClassLibrary1.csproj]
Done Building Project "ClassLibrary1.csproj" (restore target(s)) -- FAILED.

**Comment by emgarten** [comment]
MSBuild treats env vars as properties which is where this is coming from. NuGet.exe shells out to msbuild and gives the same behavior as what you would see if you ran msbuild yourself.

**Comment by wasaczd** [comment]
But why env var / property 'Version' is considered at all in nuget? It makes no sense - each component has its own version specified either in <PackageReference> tag in .csproj or in <package> tag in packages.config or in .json.

**Comment by emgarten** [comment]
@wasaczd `Version` is used to set the package version.

https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets
