### ISSUE TITLE
Unable to install Json.NET into Xamarin iOS Unified project in VS 2015 RC

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#562]
**Steps to reproduce**

With Visual Studio Community 2015 RC, NuGet Package Manager 3.0.60410.213 and Xamarin installed (Xamarin was installed through the Visual Studio installer. No need to install the Android components).
 1. In VS 2015 create a new iOS project (e.g. Templates - Visual C# - iOS - Universal - Blank App (iOS)). Do not create a template from the Classic API category since this will have a MonoTouch target framework.
 2. Use NuGet UI to add Json.NET 6.0.8 to the iOS Unified project.

**Expected result**

Json.NET is installed and a PCL assembly is referenced by the project. NuGet should pick the Newtonsoft.json.dll from the lib\portable-net40+sl5+wp80+win8+wpa81 directory to be referenced by the project.

**Acual result**

Error reported: "Could not install package 'Newtonsoft.Json 6.0.8'. You are trying to install this package into a project that targets 'Xamarin.iOS, Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information contact the package author."

Installing Json.NET into an Android or iOS Classic project succeeds without any errors.

Looking at the [NuGet source code](https://github.com/NuGet/NuGet3/blob/1c2d8547a0a7b24eedf5d43b69255a5bc19074a5/src/NuGet.Frameworks/DefaultPortableFrameworkMappings.cs#L123-L125) it looks like the Xamarin frameworks are no longer treated as optional as they are in NuGet 2.8.x. Only the Mono frameworks are treated as optional.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet3@2ef374b9d6f5eae6e6316c6de14044e2f8c73b4b

Xamarin.iOS has been added to the optional framework list along side monoandroid and monotouch for portable profiles containing those frameworks.
