### ISSUE TITLE
I’m having issues with the https://www.nuget.org/packages/ExcelDataReader/

### ISSUE THREAD

**Issue by prosenba** [NuGet/Home#5620]
I tried changing the version in the project file and packages.config but didn't help.

The version of the dll is 3.0.0.0 but nuget is looking for version 3.0.0
Unable to find version '3.0.0' of package 'ExcelDataReader'.
Unable to find version '3.0.0' of package 'ExcelDataReader.DataSet'.
Unexpected exit code 1 returned from tool NuGet.exe

Here’s the output of the packages.config
```xml
<package id="ExcelDataReader" version="3.0.0" targetFramework="net461" />
  <package id="ExcelDataReader.DataSet" version="3.0.0" targetFramework="net461" />
```

Project file
```xml
<Reference Include="ExcelDataReader, Version=3.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa, processorArchitecture=MSIL">
      <HintPath>..\..\packages\ExcelDataReader.3.0.0\lib\net45\ExcelDataReader.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ExcelDataReader.DataSet, Version=3.0.0, Culture=neutral, PublicKeyToken=93517dbe6a4012fa, processorArchitecture=MSIL">
      <HintPath>..\..\packages\ExcelDataReader.DataSet.3.0.0\lib\net45\ExcelDataReader.DataSet.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

**Comment by rohit21agrawal** [comment]
@prosenba can you attach a repro project? That will help speed up investigation. Also provide details of what version of Visual Studio you are using.

**Comment by emgarten** [comment]
@prosenba use Visual Studio to install and update packages. NuGet.exe does not support installing packages to a project, and update is very limited in what it can modify in the project.

**Comment by prosenba** [comment]
Thanks for the comments, I'm working on visual studio 2015 enterprise. I'm confused about this statement  "NuGet.exe does not support installing packages to a project" 
This is an asp.net project, 
Here's my understanding of how a nuget package works, correct me if I'm wrong
pull up the nuget console, at the prompt
Install-Package ExcelDataReader
nuget installs the new dll in the reference folder,
it adds the new nuget package to packages.config file
<package id="ExcelDataReader" version="3.0.0" targetFramework="net461" />
  <package id="ExcelDataReader.DataSet" version="3.0.0" targetFramework="net461" />
if you unload the project file and edit the file you will see nuget package information in the project file.


Now I can use the new nuget package without issue and everything is working.
I go to build the project to dev and I get this error
Unable to find version '3.0.0' of package 'ExcelDataReader'.
Unable to find version '3.0.0' of package 'ExcelDataReader.DataSet'.

I'm assuming that the dll is version 3.0.0.0 but tfs is looking for version 3.0.0
I tried changing the version number in the project file and packages.config file and still see the error.

Phillip

**Comment by emgarten** [comment]
@prosenba `Install-Package` is a powershell console command which is part of Visual Studio, so it looks like you are doing this correctly. NuGet.exe is a different tool which is not part of Visual Studio, it does not have the command you are mentioning.

I'm not clear on the repro steps here, would you provide additional details containing your exact steps?

Note, modifying packages.config is not a valid way to change packages, you must use Install-Package or Update-Package.

**Comment by prosenba** [comment]
The issue is resolved now,  the issues had to do with directory structure and how to build server was trying to pull the nuget packages in from the wrong directory.
Thanks for suggestions.

**Comment by emgarten** [comment]
Glad to hear your issue is resolved @prosenba
