### ISSUE TITLE
nuget install will change referenced project to nuget reference

### ISSUE THREAD

**Issue by czb182** [NuGet/Home#5629]
VS2017 15.2

Nuget Packages built with 3.5.0

Setup
Solution 1
 - Projects A
    - Has nuspec, gets published as nuget package 1A
 - Project B
    - project reference to A
    - has nuspec, gets published as nuget package 1B
       - uses -IncludedReferencedProjects, so that nuget has dependency on A via project reference

Solution 2
 - Project A
    - Nuget Reference to 1A
    - Has nuspec, gets published as nuget package 2A

This is all fine.  However, if I now decide that Solution 1 Project B needs a nuget reference to nuget 2A, it will pull in nuget dependency it has on 1A and change Solution 1 Project B project reference to A to a a nuget reference to 1A.  Now instead of project references keeping things in sync in Solution 1, I have to maintain the nuget references.

It would be nice if there was some way that Nuget could know that a nuget file dependency already exist as a project reference, and therefore doesn't need to do anything.  Maybe it could check that the same libraries are already referenced as project reference and ignore.

Hopefully this was all clear.

**Comment by nkolev92** [comment]
@czb182 Which project style are you using? 

I'm not sure I fully understand your scenario, can you provide a repro project prior to adding the package?

**Comment by nkolev92** [comment]
Closing as stale. 

If you are still having problems, please create a new issue.
