### ISSUE TITLE
UI Search: searching for Xamarin.OpenTok.iOS against nuget.org returns no result

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#563]
although it does exist on nuget.org as https://www.nuget.org/packages/Xamarin.OpenTok.iOS/. 

searching against api.nuget.org works fine though.

**Comment by johnataylor** [comment]
This is V2 search.

**Comment by yishaigalatzer** [comment]
@danliu who reported this? I want to understand if there is something more interesting here.

This right now gets filtered by target framework, that filter is not support by v3.

**Comment by danliu** [comment]
@yishaigalatzer, the manual testers found this. They were exercising the scenarios once against api.nuget.org, once against nuget.org.

**Comment by bhuvak** [comment]
Searching for the package from nuget.org website returns proper result. We will be removing target framework filtering in v2 as well ( as part of consolidating v2/v3 search). Hence linking  it to https://github.com/NuGet/NuGetGallery/issues/2419 and close it.
