### ISSUE TITLE
NuGet issuing new warnings via MSBuild 

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#5633]
Recently I installed a preview build of VS2017: 26621.2.d15rel. This build is now issuing a number of new warnings when building / restoring Roslyn.sln:

```
E:\code\roslyn\src\EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj : warning NU1603: StreamJsonRpc 1.0.2-rc depends on Microsoft.VisualStudio.Threa ding (>= 15.0.58-pre) but Microsoft.VisualStudio.Threading 15.0.58-pre was not found. An approximate best match of Microsoft.VisualStudio.Threading 15.0.83-pre w as resolved. [E:\code\roslyn\Roslyn.sln]
E:\code\roslyn\src\EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj : warning NU1603: Microsoft.ServiceHub.Client 1.1.18-rc-g92b2150dd1 depends on M icrosoft.VisualStudio.Threading (>= 15.0.116-pre-g43c3d919cd) but Microsoft.VisualStudio.Threading 15.0.116-pre-g43c3d919cd was not found. An approximate best ma tch of Microsoft.VisualStudio.Threading 15.0.240 was resolved. [E:\code\roslyn\Roslyn.sln]
E:\code\roslyn\src\EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj : warning NU1603: Microsoft.VisualStudio.Composition 15.0.66-rc depends on Micro soft.VisualStudio.Validation (>= 15.0.42-pre) but Microsoft.VisualStudio.Validation 15.0.42-pre was not found. An approximate best match of Microsoft.VisualStudi o.Validation 15.0.55-pre was resolved. [E:\code\roslyn\Roslyn.sln]
E:\code\roslyn\src\EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj : warning NU1603: Microsoft.ServiceHub.Client 1.1.18-rc-g92b2150dd1 depends on S treamJsonRpc (>= 1.0.12-rc) but StreamJsonRpc 1.0.12-rc was not found. An approximate best match of StreamJsonRpc 1.0.36
```

Why are these warnings appearing in MSBuild but not NuGet.exe (version 4.1.0)? 

This was fairly surprising and it's blocking our ability to upgrade builds at the moment. Our build fails on warnings (warn as error) and these are new warnings for code that has restored + built fine for some time now.

**Comment by nkolev92** [comment]
The preview build that you installed is 15.3, Preview 3.
When you use msbuild there it will pick up the NuGet bits that came with VS. 
The coded NuGet warnings and errors are part of the 15.3 release which is basically the NuGet.exe 4.3 release. 
https://github.com/NuGet/Home/wiki/Warnings-and-Errors-Combined-Specs

The recommended thing here would be to upgrade to the latest NuGet.exe.
https://dist.nuget.org/

And then use the properties described here to resolve your errors:
https://github.com/NuGet/Home/wiki/Improved-NuGet-warnings

Let us know if you have further questions. 
Closing this for now. 

//cc
@emgarten @mishra14

**Comment by jaredpar** [comment]
Thanks for the explanation.

How could I find out about these warnings in advance? Essentially not get surprised, and have portions of our team blocked on them, when we upgrade to a new build. It's very time consuming to have a mini-fire drill to fix a bunch of warnings we weren't expecting here. In this case though it seems like they're planned hence probably could have found out a bit this sooner and gotten ahead of the problem.

**Comment by emgarten** [comment]
> How could I find out about these warnings in advance?

Good question, for the 4.3.0 release NuGet did a lot of work on warnings and errors. I'm not sure how common this will be going forward, but it should be in the release notes to avoid surprises.

@anangaur can we start calling out new warnings and errors in the release notes, including for previews?

**Comment by anangaur** [comment]
We have documented the 4.3.0 (PREVIEW) warnings and errors with PackageReference based projects. The reference to these errors/warnings can be found here: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings

If there are more previews for VS 2017 version 15.3, we can definitely link this reference from the release notes.
