### ISSUE TITLE
NuGet restore fails to restore package if a nested project reference has the same name as the package ID.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#5634]
## Details about Problem

NuGet product used (NuGet.exe ):

NuGet version (4.1.0.2450):

OS version (Win10 (15063.447)):

## Detailed repro steps so we can see the same problem

1.  Create msbuild project file that takes a project reference on a msbuild project file with the same name as a nuget package id that has a packagereference.  
Example a project file that has:
&lt;ProjectReference Include="Newtonsoft.json.csproj"&gt;
&lt;PackageReference Include="Newtonsoft.json" version="9.0.1"&gt;

2. run nuget restore on the project file notice it doesn't install Newtonsoft.json

## Other suggested things
You may simply use attached zip file and run 
nuget restore repro\proja\ClassLibrary.csproj

### Verbose Logs

See attached zip file for verbose.log and restore.log

### Sample Project

Attached samples require msbuild 15 or higher.
[TraversalRestore-Fail-When-ProjectName-Match.zip](https://github.com/NuGet/Home/files/1170989/TraversalRestore-Fail-When-ProjectName-Match.zip)

**Comment by emgarten** [comment]
Packages are Projects are treated the same to ensure that when you pack your projects into nupkgs it will all work the same.

You can work around this by renaming Newtonsoft.json.csproj to something else, or specifying `<PackageId>differentName</PackageId>` in Newtonsoft.json.csproj

**Comment by kingerja** [comment]
As this is a constraint introduced by nuGet shouldn't some warning or error be generated instead of silently doing unexpected behavior?

**Comment by emgarten** [comment]
> As this is a constraint introduced by nuGet shouldn't some warning or error be generated instead of silently doing unexpected behavior?

Yes it should, that work is tracked here https://github.com/NuGet/Home/issues/3612
