### ISSUE TITLE
NuGet.exe documentation should clarify that "nuget restore <packages.config> requires the -PackagesDirectory or -SolutionDirectory parameter

### ISSUE THREAD

**Issue by pspill** [NuGet/Home#5635]
In all versions of nuget.exe, "nuget.exe restore <packages.config>" requires the use of the -PackagesDirectory or -SolutionDirectory parameter or an error will occur.  This should be clarified in the documentation for the restore command.

Note that install does not have the same restriction -- it will assume a local "packages" folder no output folder is supplied.

**Comment by karann-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #623](https://github.com/NuGet/docs.microsoft.com-nuget/issues/623) via [**ZenHub**](https://www.zenhub.com/)
