### ISSUE TITLE
NuGet does not preserve package ID during restore

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5637]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 4.1.0.0

Worked before? If so, with which NuGet version: It's very hard to tell. Some packages seem to be correct, while others are not.

### Detailed repro steps so we can see the same problem

1. Create a package with a package ID which contains a character in the range `[A-Z]`
2. Restore the package under the new project system

### Expected result

The package directory, however formed, does not change the package ID. Package IDs should be preserved from input to output for all cases to ensure that deviations are correctly detected at input.

### Actual result

The restore directory does not match the package ID. On some file/operating systems, e.g. NTFS on Windows, the directory coincidentally matches. However, the deviation can be detected through other APIs in the file system.

### Other suggestions

This behavior appears to be due to an assumption that package authors and/or consumers are not able to properly write package IDs in `<PackageReference>` items. However, in the event this occurs, it would be a bug on the end user and certainly not the responsibility of NuGet to try and rectify. Alterations to the package ID as part of the restore process makes everything more confusing and makes it harder for end users to work within the behavior of the system.

**Comment by emgarten** [comment]
NuGet package ids are case insensitive, both locally and on remote feeds.

> This behavior appears to be due to an assumption that package authors and/or consumers are not able to properly write package IDs in <PackageReference> items. However, in the event this occurs, it would be a bug on the end user and certainly not the responsibility of NuGet to try and rectify.

This was tried in early previews of NETCore and was changed to case insensitive behavior after much negative feedback and confusion.

Originally for NETCore projects NuGet did try to preserve case, however after scanning through packages on nuget.org it was found that a non-trivial number of packages contained inconsistent casings of the package id between versions. Example: `NuGet.Core` and `Nuget.Core`.  It was also found that many packages referenced other dependencies with incorrect casings.

Enforcing case for the above scenarios causes packages of the same id to be put in different folders if their case varies, or if on windows a random case to be used (whichever is installed first). It also means that packages referencing lowercase `newtonsoft.json` for example would fail to resolve their dependencies.

Overall sensitive ids with NuGet was extremely painful and at this point bringing it back would be a major breaking change since all versions that support `PackageReference` have used lowercase.

NPM has taken a similar approach by only allowing lowercase ids from what I understand.

> The package directory, however formed, does not change the package ID. Package IDs should be preserved from input to output for all cases to ensure that deviations are correctly detected at input.

@sharwell would share additional scenarios and reasons why this is important and this change should be considered?

**Comment by sharwell** [comment]
Why not implement the case correction during the restore process, with a warning when a `<PackageReference>` is encountered that needed to be case-corrected during restore? This allows packages to be the source of truth regarding their own ID, while remaining tolerant to incorrect references.

**Comment by emgarten** [comment]
> Why not implement the case correction during the restore process, with a warning when a <PackageReference> is encountered that needed to be case-corrected during restore?

1. Slower restore performance, checking if a package already exists during a noop restore becomes scanning every directory for possible cases of ids and versions  vs a file.exists
1. Versions of the same id are put in different folders on case sensitive file systems if the id changed case between versions
1. Id folder uses the case of the first version installed on case insensitive file systems
1. It would be a breaking change that could cause issues for older xplat clients using the same package folder

> This allows packages to be the source of truth regarding their own ID, while remaining tolerant to incorrect references.

Can you give some examples of why it is important for a package to own the casing of the folder they are extracted to?

**Comment by sharwell** [comment]
> 1. Slower restore performance

Assuming the restore is based off the information in **project.assets.json**, this shouldn't end up the case. The assets file contains the finally-resolved dependencies using the casing declared in the package, not the casing that appears on disk (for either the `<PackageReference>` or the current form in the cache). Avoiding the case manipulation would actually *improve* restore performance by avoiding the overhead of running ToLower operations on information in the assets file which is already correct.

> 2. Versions of the same id are put in different folders on case sensitive file systems if the id changed case between versions
> 3. Id folder uses the case of the first version installed on case insensitive file systems

Each of these cases is the expected behavior. In the latter case, the case mismatch is due to the package author, not NuGet. To the best of its ability, NuGet preserved IDs during restore.

> Can you give some examples of why it is important for a package to own the casing of the folder they are extracted to?

* Violation of principle of least surprise.
* Package IDs that contain proper nouns and company names end up writing incorrect forms of those names to disk.
* When looking at the packages cache, it is difficult to read some package IDs in all lowercase, especially when you are used to seeing the names in PascalCase *literally everywhere else*.
* Degraded restore performance.

**Comment by emgarten** [comment]
> Assuming the restore is based off the information in project.assets.json, this shouldn't end up the case.

project.assets.json is the output, not the input. In the most basic scenario for example, a package cannot be put in place until after it has already been downloaded and the nuspec read. Only then can restore know the truth about what the package id is and place it where it needs to go.

The most common operation in NuGet is finding all packages by id and getting the full set, which includes all casings of the ids.

I appreciate the feedback, but having already suffered from all of these problems in the past when NuGet was case sensitive there aren't many unknowns here. It would be great if this could work, but after much feedback from users and investigating existing packages on nuget.org we had to consistently treat package ids as case insensitive.
