### ISSUE TITLE
Conditionally excluding package

### ISSUE THREAD

**Issue by srivatsn** [NuGet/Home#5638]
_From @karthiknadig on June 9, 2017 21:27_

When I try to build my project in linux I run into this error:
```
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : Unable to load the service index for source https://mseng.pkgs.visualstudio.com/DefaultCollection/_packaging/VS/nuget/v3/index.json. [/mnt/g/GIT/RTVS/src/R.sln]
/usr/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error :   Response status code does not indicate success: 401 (Unauthorized). [/mnt/g/GIT/RTVS/src/R.sln]
```
The package is needed on windows but not on linux. 

_Copied from original issue: dotnet/project-system#2417_

**Comment by emgarten** [comment]
@karthiknadig do you have have credentials for this feed in your nuget.config file using clear text? Encrypted credentials are not supported on linux, and VSTS does not have a credential provider for linux yet either.

**Comment by emgarten** [comment]
@karthiknadig closing this due to lack of details here. Please ping this issue if clear text credentials do not solve your issue.
