### ISSUE TITLE
Unable to build the client libraries from either the command line or in visual studio

### ISSUE THREAD

**Issue by SeanFarrow** [NuGet/Home#5648]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet client libraries
NuGet version (x.x.x.xxx):
Dev branch
dotnet.exe --version (if appropriate):
1.1
VS version (if appropriate):
VS2017
OS version (i.e. win10 v1607 (14393.321)):
Windows server 2012 R2
Worked before? If so, with which NuGet version:
No
## Detailed repro steps so we can see the same problem

1.
Clone the repo and ensure you are on the dev branch.
2.
run the configure script from powershell.
3. 
If the configure script succeeds, run the build scrip from powershell.
4. 
Either the build or configuration script will fail to run as it's looking for "c:\build\common.props" when it should be looking for a common.props file in a build directory relative to the folder in which the repository was cloned. This mean that not only can build/configure not be run form the commandline but none of the projects can be loaded in visual studio.

**Comment by emgarten** [comment]
@SeanFarrow could debug why build\common.props is getting the wrong location for you? Are you using msbuild 15?

**Comment by SeanFarrow** [comment]
Hi,

I’ve got vs 2013, 2015 and 2017 on this machine.
It seems to be getting or thinking that the build folder is in the folder above readme.md.

**Comment by emgarten** [comment]
I'm not able to reproduce this locally, builds are working for me.

**Comment by SeanFarrow** [comment]
Ok, let me blow away the repo and see whether that makes any difference!
