### ISSUE TITLE
Adding NuGet.Core package to csproj as PackageReference has no any effect in restore/build process

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5650]
_From @maestrow on July 26, 2017 6:49_

## Steps to reproduce

1. `dotnet new`
1. Change `TargetFramework` in `csproj` file to `net461`
1. `dotnet add package NuGet.Core`
1. Add `using NuGet;` to `Program.cs` (this namespace is exists in NuGet.Core Assembly, I checked)
1. `dotnet restore`
All above executed successfully. Next:
6. `dotnet build`

## Expected  behavior

Successfull Build

## Actual behavior

Error: "The type or namespace name 'NuGet' could not be found".

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

I'm tried on both versions: 1.0.4 and 2.0.0-preview2-25407-01

_Copied from original issue: dotnet/cli#7268_

**Comment by livarcocc** [comment]
_From @maestrow on July 26, 2017 14:20_

[Problem solved with nuget cache clearing](https://stackoverflow.com/questions/45314575/after-i-add-nuget-core-package-to-my-csproj-as-packagereference-i-have-no-any-e). But I think there should be a meanungfull message if some references was not created while project build. In my case **there is** `<PackageReference Include="NuGet.Core" Version="2.14.0" />` in `csproj`, **but no** correnponding reference in created assembly after build. However I'm not sure what software should check it - nuget or msbuild. So I'm just leave my thoughts here in hope that the knowing people will deal with it.

**Comment by emgarten** [comment]
Packages with no references will fail during restore as incompatible. It sounds like something else may have happened to the cache, there isn't a good way to detect this without impacting performance.
