### ISSUE TITLE
nuget.exe list does not find packages in a local feed; Visual Studio does

### ISSUE THREAD

**Issue by alx9r** [NuGet/Home#5652]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 4.1.0.2450

dotnet.exe --version (if appropriate):

VS version (if appropriate): 14.0.25431.01 Update 3

OS version (i.e. win10 v1607 (14393.321)): Windows 8.1 (6.3.9600)

Worked before? If so, with which NuGet version:

### Folder Structure

```
c:
   temp
      test1
         Test1.nuspec
         content
            nothing.txt
   packages
   feed
```

### Test1.nuspec
```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>test1</id>
        <version>0.1</version>
        <title>test1</title>
        <authors>author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
</package>
```

1. Create folder structure and Test1.nuspec.

2. Invoke the following commands at the command line.

```
cd c:\temp
nuget pack .\test1\test1.nuspec -OutputDirectory .\packages
nuget init .\packages .\feed
nuget list c:\temp\feed
```

## Expected Result

I expected `nuget list c:\temp\feed` to list the `test1` nuget package.

## Actual Result

`nuget list c:\temp\feed` outputs "No packages found."

Here is the entire console session:

```
C:\temp>nuget pack .\test1\test1.nuspec -OutputDirectory .\packages
Attempting to build package from 'test1.nuspec'.
Successfully created package 'C:\temp\packages\test1.0.1.0.nupkg'.

C:\temp>nuget init .\packages .\feed
Installing test1 0.1.0.
Successfully added package '.\packages\test1.0.1.0.nupkg' to feed '.\feed'.

C:\temp>nuget list c:\temp\feed
No packages found.
```

## Verbose Output

Here is the verbose output from `nuget list c:\temp\feed`:

```
C:\temp>nuget list c:\temp\feed -verbosity detailed
NuGet Version: 4.1.0.2450
  GET https://www.nuget.org/api/v2/$metadata
  OK https://www.nuget.org/api/v2/$metadata 77ms
  GET https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&
searchTerm='c:%5Ctemp%5Cfeed'&targetFramework=''&includePrerelease=false&$skip=0
&$top=30
  OK https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&s
earchTerm='c:%5Ctemp%5Cfeed'&targetFramework=''&includePrerelease=false&$skip=0&
$top=30 99ms
No packages found.
```

### Visual Studio sees the Feed

1. Add the feed to Visual Studio.

![image](https://user-images.githubusercontent.com/11237922/28634664-c22faa44-71ec-11e7-8447-0d9f4ba00da5.png)

2. Package `test1` appears in the "Manage Nuget Packages for Solution" dialog box in Visual Studio.

![image](https://user-images.githubusercontent.com/11237922/28634688-d99a4248-71ec-11e7-95d7-56f127ccf6f6.png)

**Comment by emgarten** [comment]
I got confused myself on the syntax trying to repro this, but the problem is that the path is being passed as a search term and not as a source.

`nuget list c:\temp\feed` should be `nuget list -Source c:\temp\feed`

The syntax is: `nuget list <search term>`

Let me know if this doesn't solve the issue.

**Comment by alx9r** [comment]
Oops.  Indeed that was my error. Thanks @emgarten.
