### ISSUE TITLE
nuget.exe list does not find package with alphabetic pre-release suffix in a local feed; Visual Studio does

### ISSUE THREAD

**Issue by alx9r** [NuGet/Home#5653]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 4.1.0.2450

dotnet.exe --version (if appropriate):

VS version (if appropriate): 14.0.25431.01 Update 3

OS version (i.e. win10 v1607 (14393.321)): Windows 8.1 (6.3.9600)

Worked before? If so, with which NuGet version:

### Folder Structure

```
c:
   temp
      nosuffix
         nosuffix.nuspec
         content
            nothing.txt
      alphabeticSuffix
         alphabeticSuffix.nuspec
         content
            nothing.txt
   packages
   feed
```

### nosuffix.nuspec

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>nosuffix</id>
        <version>0.1.0</version>
        <title>nosuffix</title>
        <authors>author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
</package>
```

### alphabeticSuffix.nuspec

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>alphabeticSuffix</id>
        <version>0.1.0-abcdef</version>
        <title>alphabeticSuffix</title>
        <authors>author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
</package>
```

1. Create the folder structure, nosuffix.nuspec, and alphabeticSuffix.nuspec.

2. Invoke the following commands at the command line:

```
cd c:\temp
nuget pack .\nosuffix\nosuffix.nuspec -OutputDirectory .\packages
nuget pack .\alphabeticSuffix\alphabeticSuffix.nuspec -OutputDirectory .\packages
nuget init .\packages .\feed
nuget list -Source c:\temp\feed
```

## Expected Result

I expected `nuget list -Source c:\temp\feed` to list both the "nosuffix" and "alphabeticSuffix" packages.

## Actual Result

`nuget list -Source c:\temp\feed` outputs only "nosuffix 0.1.0".

Here is the entire console session:

```

C:\temp>nuget pack .\nosuffix\nosuffix.nuspec -OutputDirectory .\packages
Attempting to build package from 'nosuffix.nuspec'.
Successfully created package 'C:\temp\packages\nosuffix.0.1.0.nupkg'.

C:\temp>nuget pack .\alphabeticSuffix\alphabeticSuffix.nuspec -OutputDirectory .
\packages
Attempting to build package from 'alphabeticSuffix.nuspec'.
Successfully created package 'C:\temp\packages\alphabeticSuffix.0.1.0-abcdef.nup
kg'.

C:\temp>nuget init .\packages .\feed
Installing alphabeticSuffix 0.1.0-abcdef.
Successfully added package '.\packages\alphabeticSuffix.0.1.0-abcdef.nupkg' to f
eed '.\feed'.
Installing nosuffix 0.1.0.
Successfully added package '.\packages\nosuffix.0.1.0.nupkg' to feed '.\feed'.

C:\temp>nuget list -Source c:\temp\feed
nosuffix 0.1.0
```

## Verbose Output

Here is the verbose output from `nuget list -Source c:\temp\feed`:

```
C:\temp>nuget list -Source c:\temp\feed -verbosity detailed
NuGet Version: 4.1.0.2450
nosuffix
 0.1.0
 My package description.
```

## Visual Studio sees both Packages

1.  Add the feed to Visual Studio.

![image](https://user-images.githubusercontent.com/11237922/28643985-825b60fa-720c-11e7-8dfe-1e43b793288d.png)

2. Both packages appear in "Manage Nuget Packages for Solution" dialog box in Visual Studio.

![image](https://user-images.githubusercontent.com/11237922/28643809-ef4a5de8-720b-11e7-934a-227a82263c5d.png)

**Comment by alx9r** [comment]
I wonder if this is related to #4537.

**Comment by nkolev92** [comment]
@alx9r 
You need to use the -Prerelease with list. 

In the VS screenshot, the include prerelease is checked, calling list with prerelease  is the equivalent.

**Comment by alx9r** [comment]
@nkolev92 Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
