### ISSUE TITLE
Visual Studio does not find a package with numeric pre-release suffix in a local feed; alphabetic suffix works

### ISSUE THREAD

**Issue by alx9r** [NuGet/Home#5654]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 4.1.0.2450

dotnet.exe --version (if appropriate):

VS version (if appropriate): 14.0.25431.01 Update 3

OS version (i.e. win10 v1607 (14393.321)): Windows 8.1 (6.3.9600)

Worked before? If so, with which NuGet version:

### Folder Structure

```
c:
   temp
      alphabeticSuffix
         alphabeticSuffix.nuspec
         content
            nothing.txt
      numericSuffix
         numericSuffix.nuspec
         content
            nothing.txt
   packages
   feed
```

### alphabeticSuffix.nuspec

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>alphabeticSuffix</id>
        <version>0.1.0-abcdef</version>
        <title>alphabeticSuffix</title>
        <authors>author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
</package>
```

### numericSuffix.nuspec

```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>numericSuffix</id>
        <version>0.1.0-123456</version>
        <title>numericSuffix</title>
        <authors>author</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>My package description.</description>
    </metadata>
</package>
```

### Steps
1. Create the folder structure, alphabeticSuffix.nuspec, and numericSuffix.nuspec.

2.  Invoke the following commands at the command line:

```
cd temp
nuget pack .\alphabeticSuffix\alphabeticSuffix.nuspec -OutputDirectory .\packages
nuget pack .\numericSuffix\numericSuffix.nuspec -OutputDirectory .\packages
nuget init .\packages .\feed
```

3. Add the feed to Visual Studio.

![image](https://user-images.githubusercontent.com/11237922/28645117-2db3675a-7211-11e7-9408-9e2d0e4cbf6c.png)

4. Inspect "Manage Nuget Packages for Solution" dialog box.  Note that the "numericSuffix" package is missing.

![image](https://user-images.githubusercontent.com/11237922/28644829-f4c5b2dc-720f-11e7-9729-ba848a4c4fcc.png)

**Comment by emgarten** [comment]
@alx9r update to NuGet 3.5.0 from https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

**Comment by alx9r** [comment]
That works.  Thank you @emgarten.

![image](https://user-images.githubusercontent.com/11237922/28901627-6f01036e-77ae-11e7-8f44-645e131d021f.png)
