### ISSUE TITLE
Invalid warning "Assembly outside lib folder." in dotnet pack

### ISSUE THREAD

**Issue by mellinoe** [NuGet/Home#5655]
```
Product Information:
Version:            1.0.1
Commit SHA-1 hash:  005db40cd1
OS Name:     Windows
OS Version:  10.0.15063
```

## Detailed repro steps so we can see the same problem

1. Create a csproj with something like following packaging options:

```
<Content Include="..\..\deps\cimgui\win7-x64\cimgui.dll">
  <PackagePath>runtimes/win7-x64/native</PackagePath>
  <Pack>true</Pack>
</Content>
```
2. Run `dotnet pack`

See https://github.com/mellinoe/ImGui.NET for a real-world project this affects.

## Results

The following bogus warning is generated:

```
warning : Issue found with package 'ImGui.NET'.
warning : Issue: Assembly outside lib folder.
warning : Description: The assembly 'runtimes/win7-x64/native\cimgui.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project.
warning : Solution: Move it into the 'lib' folder if it should be referenced.
```

NuGet should not be warning about this, because it is not invalid. The assembly in question is a native assembly (a PInvoke target for the main managed assembly being packaged), and should not be referenced directly from consumers of the nuget package.

@terrajobst mentioned to me that setting `NoPackageAnalysis=true` can be used to silence this warning, but I would probably rather not set that in case there are other, legitimate problems that could be detected.

Is there any other way that this warning can be silenced?

**Comment by emgarten** [comment]
> Is there any other way that this warning can be silenced?

That is currently the only way to turn off the warning. Pack could potentially use NU codes to allow disabling these on a per issue basis.

**Comment by mellinoe** [comment]
@rohit21agrawal Which release will this be fixed in?

**Comment by terrajobst** [comment]
> That is currently the only way to turn off the warning. Pack could potentially use NU codes to allow disabling these on a per issue basis.

Please do that. It makes sense for 80% of packages but as we're also using NuGet more and more for tooling (i.e. templates and global tools) those warnings will become a nuisance. Given them individual IDs allows suppressing them individually  and also give folks a unique way to search for them.

@rohit21agrawal: I assume you fixed this specific issue; should I file a general feature requests for outputting IDs?

**Comment by rohit21agrawal** [comment]
@mellinoe 15.4 should have this fix
@terrajobst yes, that would be great! ping @rrelyea for prioritizing this

**Comment by mellinoe** [comment]
I'm on 15.4 and this still happens.
