### ISSUE TITLE
NuGetizer3000 fails to build for .net 4.6.2 projects

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5656]
## Details about Problem

NuGet product used: NuGetizer3000 (VS2017 extension) 0.1.324

VS version (if appropriate): Version 15.2 (26430.16)

OS version: Microsoft Windows [Version 10.0.15063]

## Detailed repro steps

1. Create a new solution containing a single project. The project should be a C# Class Library (.NET Framework), targeting .Net Framework 4.6.2.

2. Add "Package" project to solution.

3. Add reference for the .net 4.6.2 Class Library project, to the Package project.

4. Build.

5. Get build errors.

### Verbose Logs

Warning	MSB3274	The primary reference "c:\users\XXX\documents\visual studio 2017\Projects\N3000Repro\N3000Repro\bin\Debug\N3000Repro.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.6.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".	NuGetPackage1	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1964

**Comment by kzu** [comment]
NuGetizer requires Visual Studio 2017 15.3 because of core changes in the project system and NuGet that didn't make it in 15.2.

Please try the latest released version (v0.2.x).
