### ISSUE TITLE
NuGet should be able to edit TFS versioned config files

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5661]
Originally filed here: https://developercommunity.visualstudio.com/content/problem/85156/getting-error-when-attempting-to-enable-package-so.html?childToView=85997#

NuGet handles the editing of the packages config files for TFS versioned solutions but it does not do the same for the configuration files.

**Comment by rrelyea** [comment]
Setting to P2 since there is a reasonable workaround, and we've not heard this feedback much in the past 2 years, since the bug was probably introduced. However, would be nice to fix, as it is common to check nuget.configs in.

**Comment by nkolev92** [comment]
Closing as lower priority.
