### ISSUE TITLE
GC pressure caused by SZGenericArrayEnumerator allocations

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5666]
Opening Roslyn.sln on Visual Studio 2017 (15.3 Preview 6).

The `TopologicalSortUtility.GetParentCount` method [calls `Enumerable.Any` on an array](https://github.com/NuGet/NuGet.Client/blob/e6e7d4ddb2499f2cce370f9f1c477d204aec90ba/src/NuGet.Core/NuGet.Packaging/TopologicalSortUtility.cs#L46), resulting in 1757MiB of allocations of the enumerator for the array. The use of LINQ should be replaced with a `foreach` over the array to avoid these allocations.

:memo: Since [`PackageDependencyInfo.Dependencies`](https://github.com/NuGet/NuGet.Client/blob/e6e7d4ddb2499f2cce370f9f1c477d204aec90ba/src/NuGet.Core/NuGet.Packaging.Core/PackageDependencyInfo.cs#L48) is exposed as an interface, avoidance of this allocation may require the `Any` functionality be implemented on the `PackageDependencyInfo` object.

**Comment by sharwell** [comment]
:bulb: If this issue is resolved by the creation of a `PackageDependencyInfo.Any` method which takes a predicate delegate, it should have the form `Func<T, TArgs, bool>` so the args parameter can be used to avoid delegate allocations, saving another 65MiB.

**Comment by benaadams** [comment]
Fix https://github.com/NuGet/NuGet.Client/pull/1585
