### ISSUE TITLE
GC pressure caused by allocations in PatternExpression.Match

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5667]
Opening Roslyn.sln on Visual Studio 2017 (15.3 Preview 6)

:memo: The allocations due to #5665 *are not* included in the numbers presented for this issue.

| Cause | Amount |
| --- | --- |
| `LiteralSegment.TryMatch` calls `Substring` | 1334MiB |
| `TokenSegment.TryMatch` calls `string.Concat` | 1159MiB ¹ |
| `TokenSegment.TryMatch` calls `string.Substring` | 565MiB |
| `TokenSegment.TryMatch` converts `char` to `string` | 215MiB ¹ |

¹ These are both caused by the expression `item.Path + _delimiter`.

**Comment by benaadams** [comment]
I think https://github.com/NuGet/NuGet.Client/pull/1590 mostly resolved this
