### ISSUE TITLE
GC pressure caused by boxing `LibraryType`

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#5669]
Opening Roslyn.sln on Visual Studio 2017 (15.3 Preview 6)

A total of 156MiB is allocated due to boxing `LibraryType`. This is relatively small compared to some of the other issues, but fortunately is easily resolved.

* `LibraryType` has operators `==` and `!=` which call `Equals(left, right)`. Since the value type arguments can never be null, each of these two calls should be changed to `left.Equals(right)`, leveraging the existing non-boxing `Equals` method.
* `LibraryIdentity.GetHashCode` ~~compares a `LibraryType` with null, resulting¹ in a boxing allocation~~ (I was browsing old code, see below).

¹ This is a guess. I couldn't find any other reason for a `LibraryType` allocation in the indicated method.

**Comment by benaadams** [comment]
> LibraryIdentity.GetHashCode compares a LibraryType with null, resulting¹ in a boxing allocation

`combiner.AddObject(Type)` rather than `combiner.AddInt32(Type.GetHashCode())`

**Comment by benaadams** [comment]
Fix https://github.com/NuGet/NuGet.Client/pull/1582

**Comment by sharwell** [comment]
@benaadams Thanks, I was apparently browsing at a commit prior to #1319 so the combiner use wasn't visible.
