### ISSUE TITLE
Minor typo in German translation

### ISSUE THREAD

**Issue by JackGrinningCat** [NuGet/Home#5671]
Hey, 

in the german translation there is an error. :-)
wrong
update      Pakete auf die aktuellsten verfügbaren Versionen aktualisieren. Dieser Befehl aktualisiert auch **s**ie Datei "NuGet.exe" selbst.
right
update      Pakete auf die aktuellsten verfügbaren Versionen aktualisieren. Dieser Befehl aktualisiert auch **d**ie Datei "NuGet.exe" selbst.

Btw: Actually i tried to find and fork and correct it and make it shiny new with a pull request. But cannot find the string with google in your repos ... so 

Have fun :)

**Comment by zhili1208** [comment]
@mishra14 loc issue

**Comment by mishra14** [comment]
@JackGrinningCat : Thanks for bringing this to our notice. We have a translation pipeline, which continuously inserts translations from our vendors. So fixing the string once will not do the trick. 

I will ask our translation vendors to take a look and fix it in the pipeline.

**Comment by nkolev92** [comment]
@mishra14 This is one of those issues that are just localized once and not being updated? 

It's in the NuGetCommandLineResources right?
