### ISSUE TITLE
  Edit New issue Opt-in NuGet support for new project types

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#569]
From @sharwell

I'm working on a Visual Studio extension that includes a new project type. A basic requirement of this extension is that it be distributed as a VSIX and not as a MSI. In order to successfully accomplish this, the project templates included in the extension install a NuGet package which adds the .targets file used to build the project.

I am now looking into migrating to using CPS instead of MPFProj to implement the basic project type support in order to address a long list of outstanding MPFProj bugs. Unfortunately, I don't see an easy way in CPS to opt-in to NuGet support in a custom project type.

Aside from simply reusing one of the rarer project type IDs for our project type (a workable but unpleasant solution for users who may want to install both), what can we do to declare support for NuGet in our extension?

**Comment by yishaigalatzer** [comment]
Can you share a few more details about your project type?

**Comment by sharwell** [comment]
It's not just one project type. This strategy should be capable of supporting any project type meeting all of the following characteristics, without involving the NuGet team or waiting for an updated release of NuGet.

1. The project is built using the version of MSBuild associated with the IDE, for at least Visual Studio 2012+.
2. When installing a NuGet package with build tools, the **.props** file is included at the top of the project file, and the **.targets** file is included at the bottom of the project file.

**Comment by sharwell** [comment]
If the above is not possible and additional constraints are required, we just need to know what those constraints are so we can meet them and enable the functionality. :+1:

**Comment by yishaigalatzer** [comment]
Is number one a pre-requirement and number 2 the ask?

**Comment by emgarten** [comment]
For your scenario it seems like the right solution is to include the target and props in the template itself. We believe this should resolve your issue, if you want support for a new project system beyond this, please open another bug. Note that we likely will not be able to support for this down level versions of Visual Studio.

**Comment by sharwell** [comment]
@emgarten That won't work for a number of reasons. The primary two are:

1. We don't put the build tools in source control. We rely on the ability to exclude them as part of the **packages/** directory and restore them the next time the project is open.
2. We want to be able to update the build tools as we fix bugs, etc.

**Comment by yishaigalatzer** [comment]
@sharwell did you actually try it an it doesn't work? Folks here seems to think this just works in CPS. If it doesn't can you tell us what is not working?

We are assuming you are using the same project Guid as CPS.

**Comment by sharwell** [comment]
@yishaigalatzer I finally had the chance to test this with the [nuproj](https://github.com/nuproj/nuproj) project system. It doesn't work because CPS does not provide a project guid. You are required to [provide your own](https://github.com/nuproj/nuproj/blob/db1a902dafd9f876a9fa2e5f272817b23df6622b/src/NuProj.ProjectSystem.12/NuProjUnconfiguredProject.cs#L15), and NuGet does not recognize it.

**Comment by yishaigalatzer** [comment]
We don't support nuproj and just spoke with Andrew arnott about it. We will tackle this for update I

**Comment by yishaigalatzer** [comment]
@sharwell we are tracking this work through https://github.com/NuGet/Home/issues/603. The plan is to use project capabilities and perhaps an msbuild target you need to drop in. This is not a small item and we will tackle it like I said most likely for Update I

**Comment by sharwell** [comment]
@yishaigalatzer The problem could be immediately resolved by making `IsSupported` simply return true.

**Comment by sharwell** [comment]
As I mentioned before (in the original issue), the only other alternative for us is intentionally reusing an existing whitelisted GUID, but that will mean that users cannot have our extension installed at the same time as whatever other one we used, and that is something we really want to avoid.

**Comment by yishaigalatzer** [comment]
That is not how we are going to suport nuproj or cps projects in general.

We are also not going to create instant legacy problems by doing premature things wihout thinking them through.

We are focused on bringing up nuget quality up towards RTM, this unfortunately is probably going to wait for update 1. In the off chance we finish the rtm work ahead of schedule we will take another look.

-----Original Message-----

**Comment by yishaigalatzer** [comment]
@sharwell I'm going to take another look and see if we can come up with something stable enough for RTM. If I find a way I will re-open this bug. I can't promise this will make it down level (vs 2013 or 2012), or if it does when will that happen.

**Comment by sharwell** [comment]
@yishaigalatzer Thank you. This functionality will be a big deal to a bunch of people. :+1:

**Comment by yishaigalatzer** [comment]
Does your project support add reference and content?

**Comment by sharwell** [comment]
In theory yes, although we are not currently using this aspect in the NuGet packages we install automatically. If you can point me to the specific interfaces which need to be implemented for this support, I would be able to confirm it.

**Comment by maartenba** [comment]
Linking https://github.com/NuGet/NuGet.VisualStudioExtension/pull/30

**Comment by AArnott** [comment]
Yay! We're getting this fixed! Thanks, @sharwell  for filing this and thanks @maartenba and @yishaigalatzer for making it happen!

**Comment by maartenba** [comment]
Merged NuGet/NuGet.VisualStudioExtension#30 - once you have a drop please verify the resolution.

**Comment by AArnott** [comment]
Note that to verify you'll need both the NuGet client drop and the very latest MSBuild .targets from VSPro_Platform or to add this XML to your project file:

    <ItemGroup>
        <ProjectCapability Include="DeclaredSourceItems" />
        <ProjectCapability Include="UserSourceItems" />
    </ItemGroup>

**Comment by yishaigalatzer** [comment]
Fixed
