### ISSUE TITLE
Source name of credential  Setting in NuGet.Config are case sensitive

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#5695]
need to check 2.8 behavior, make sure this is not an regression

**Comment by zhili1208** [comment]
checked nuget.exe 2.8, 3.5 and 4.1, source Name of credential in NuGet.Config is case sensitive in all nuget version. this is not an regression

**Comment by rrelyea** [comment]
@zhili1208 - where did this bug come from? hard to tell origin of issue

**Comment by zhili1208** [comment]
from our CI test
