### ISSUE TITLE
NullReferenceException after VS 2017 command line started in AppVeyor

### ISSUE THREAD

**Issue by IlyaFinkelshteyn** [NuGet/Home#5696]
OS: Windows Server 2016
Nuget: 4.1.0.2450

[Here](https://ci.appveyor.com/project/IlyaFinkelshteyn/nugetnullrefdemo/build/0.10.1.2) is failed build.
[Here](https://ci.appveyor.com/project/IlyaFinkelshteyn/nugetnullrefdemo/build/0.10.1.1) is happy build

Workaround to make it happy is [remove msbuild-related paths](https://github.com/IlyaFinkelshteyn/NugetNullRefDemo/blob/master/appveyor.yml#L17-L22) added by vcvars32.bat.

Removing `vcvars32.bat` or calling `nuget restore` before `vcvars32.bat` helps too.

**Comment by zhili1208** [comment]
Could you try nuget 4.3.0-preview3 from https://dist.nuget.org/index.html?

**Comment by IlyaFinkelshteyn** [comment]
Thanks! Seems like [the same result](https://ci.appveyor.com/project/IlyaFinkelshteyn/nugetnullrefdemo/build/0.10.1.3)

**Comment by zhili1208** [comment]
I can repro this, I suspect the VS API ISetupInstance can't find msbuild path in AppVeyor, need more invesitgation

**Comment by IlyaFinkelshteyn** [comment]
Oh, thanks! I actually have a hard time to repro this on my local machine, though `vcvars32.bat` updates  `path` variable the same way. This maybe something special to our build worker image, any hint what can I try is greatly appreciated.

**Comment by zhili1208** [comment]
one workaround you can try, use "nuget restore -MsbuildPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin", ask nuget to find msbuild from defined path, it should skip the whole discovery process.

**Comment by IlyaFinkelshteyn** [comment]
That [works](https://ci.appveyor.com/project/IlyaFinkelshteyn/nugetnullrefdemo/build/0.10.1.4). I have what to propose to our customers who hit this, so we are good. Thank you!
I would still made this error a little bit less generic :)

**Comment by nkolev92** [comment]
We think this is fixed right now with the latest NuGet. 

If you can still repro it, please open another issue.
