### ISSUE TITLE
"MSBuild-Integrated package restore" or "Automatic Package Restore"

### ISSUE THREAD

**Issue by HansKindberg-Net** [NuGet/Home#570]
This is more a question than an issue but I found no where else to put it. Codeplex/discussions points to GitHub so.

The following article, https://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore, explains howto migrate MSBuild-Integrated solutions to use Automatic Package Restore.

I have used "MSBuild-Integrated package restore" for some time now. I like it. I keep the following out of source control:
- .nuget/NuGet.exe
- packages/* (the whole packages folder)

Before I used to keep the file "packages/repositories.config" in source control to but I have understood that it is not necessary.

So the files regarding NuGet that I keep in source control are the following:
- .nuget/NuGet.config
- .nuget/NuGet.targets

I do the following changes to the NuGet.targets file (I have only included changed tags):

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;PropertyGroup&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;RestorePackages Condition="  '$(RestorePackages)' == '' "&gt;true&lt;/RestorePackages&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;RequireRestoreConsent Condition=" '$(RequireRestoreConsent)' != 'false' "&gt;false&lt;/RequireRestoreConsent&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;DownloadNuGetExe Condition=" '$(DownloadNuGetExe)' == '' "&gt;true&lt;/DownloadNuGetExe&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;...
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/PropertyGroup&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;ItemGroup Condition=" '$(PackageSources)' == '' "&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;PackageSource Include="https://www.nuget.org/api/v2/" /&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;PackageSource Include="http://mycompany.com/nuget/" /&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;/ItemGroup&gt;
&nbsp;&nbsp;&nbsp;&nbsp;...
&lt;/Project&gt;

The main advantage with this as I see it:
If a developer want to open the solution from source control he/she does not even have to have the NuGet Package Manager extension for Visual Studio installed. It will work anyhow. When the developer builds the solution the NuGet.targets settings will see that NuGet.exe is downloaded and then the packages are downloaded.

I can not see the advantage of moving from "MSBuild-Integrated package restore" to "Automatic Package Restore".

So my questions are:
- Is there a recommendation to move from "MSBuild-Integrated package restore" to "Automatic Package Restore"?
- If I move over to "Automatic Package Restore" do every developer need to have "NuGet Package Manager" installed?
- Should I then move the solution specific package-sources (&lt;PackageSource Include="" /&gt;) from NuGet.targets to NuGet.config?
- The setting, &lt;DownloadNuGetExe Condition=" '$(DownloadNuGetExe)' == '' "&gt;true&lt;/DownloadNuGetExe&gt;, is there a setting like this to use in NuGet.config?

Regards Hans

**Comment by emgarten** [comment]
Going forward we will recommend separating NuGet restore from msbuild. You will have a build.cmd that downloads nuget.exe restore and then calls msbuild. Solution level packages will be deprecated as well.

**Comment by HansKindberg-Net** [comment]
Hi Emgarten

I am not with you

Going over to "Automatic Package Restore" - does it require "NuGet Package Manager" to be installed? Or will this build.cmd that downloads NuGet.exe that you mention exist when installing Visual Studio and then handle everything?

Regards Hans

**Comment by yishaigalatzer** [comment]
On a build machine nuget package manager is not required to be installed. The build.cmd you have to build yourself, but its fairly straight forward.
