### ISSUE TITLE
FileNotFoundException for pdb files, when you create nuget package with dotnet tool and custom OutDir

### ISSUE THREAD

**Issue by oakio** [NuGet/Home#5701]
## Details about Problem
When you create nuget package using `dotnet pack` command with `IncludeSymbols=true`, `NoBuild=true` and custom `OutDir` than you got an error:

> C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: The "PackTask" task failed unexpectedly. [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: System.IO.FileNotFoundException: File not found: 'C:\App\src\App\obj\Debug\net461\App.pdb'. [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.MSBuildProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder) [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path) [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage(String path) [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Commands.PackCommandRunner.BuildPackage() [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at NuGet.Build.Tasks.Pack.PackTask.Execute() [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\App\src\App\App.csproj]
>                    C:\Program Files\dotnet\sdk\1.0.4\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [C:\App\src\App\App.csproj]

`PackTask` could not found pdb-file because `TargetPathsToSymbols` incorrect.
I guess that the reason is that instead of the line in file `NuGet.Build.Tasks.Pack.targets` (see PackTask):

> TargetPathsToSymbols="@(_TargetPathsToSymbols)"

should be:

> TargetPathsToSymbols="@(_TargetPathsToSymbols->'%(FinalOutputPath)')"

where `_TargetPathsToSymbols`:

> _TargetPathsToSymbols=
> &nbsp;&nbsp;&nbsp;&nbsp;**C:\App\src\App\obj\Debug\net461\Finam.App.pdb**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**FinalOutputPath=C:\App\build\bin\App\net461\Finam.App.pdb**
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MSBuildSourceProjectFile=C:\App\src\App\App.csproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MSBuildSourceTargetName=DebugSymbolsProjectOutputGroup
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OriginalItemSpec=C:\App\src\App\App.csproj
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TargetPath=Finam.App.pdb (TaskId:8)
>

**Comment by zhili1208** [comment]
@rohit21agrawal

**Comment by rohit21agrawal** [comment]
@oakio  could you please try the dotnet cli 2.0.0-preview2 bits? You can download it from : https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/2.0.0/dotnet-sdk-latest-win-x64.zip

We have made changes in this particular area which I believe will fix your problem.

**Comment by oakio** [comment]
@rohit21agrawal Yes, this bug was fixed in dotnet 2.0.0-preview3-006912
