### ISSUE TITLE
VS hang on project open

### ISSUE THREAD

**Issue by sayedihashimi** [NuGet/Home#5702]
I was working on a project and when I tried to open the solution VS got into a hung state. I investigated the dump with @abpiskunov and it looks like NuGet restore is on the stack and maybe waiting for something.
After closing VS, and restoring the NuGet packages on the command line I was able to successfully open the project in VS.

Links to files which may help investigations.

 - Dump file `\\scratch2\scratch\sayedha\devenv.zip`
 - Source folder `\\scratch2\scratch\sayedha\sidewafflev2.zip`

The files are too big to share on a public drop location.

## VS Info
Microsoft Visual Studio Enterprise 2017 Int Preview (2)
Version 15.3.0 Preview 8.0 [26801.0.d15rel]
VisualStudio.15.IntPreview/15.3.0-pre.8.0+26801.0.d15rel
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA852
Microsoft Architecture Diagrams and Analysis Tools

Visual Basic 2017   00369-60000-00001-AA852
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA852
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA852
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA852
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.8.00712.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30728.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.7
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

NuGet Package Manager   4.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

WebJobs Tools v1.0.0   __RESXID_PRODUCTVERSION__
WebJobs Tools v1.0.0

**Comment by zhili1208** [comment]
@sayedihashimi @abpiskunov I looked at the dump file, but didn't find nuget restore on UI thread call stack.
Could you share the call stack?

**Comment by abpiskunov** [comment]
See Main thread.

**Comment by jainaashish** [comment]
Dump shows there was a commandline restore in progress where as you said you loaded the solution in VS which fault into this hung state. Both these things don't add, can you tell the specific scenario? or if there was something specific with this solution (may be some specific targets which calls into NuGet restore on sln load...)

And do you have a consistent repro of it? and mind sharing the repro details...

**Comment by zhili1208** [comment]
I can repro it by open the solution from \\scratch2\scratch\sayedha\sidewafflev2.zip, looks like "msbuild /t:restore" is triggered from VS UI.

**Comment by zhili1208** [comment]
it's caused by package "WaffleBuilder.0.0.1-beta" which triggered msbuild restore from VS UI, I don't think msbuild restore during open solution can work, we can investigate more.

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you for letting us know about the problem you encountered, we have decided that this is an unsupported scenario, and we won't invest any work in here.
