### ISSUE TITLE
Nuget client tools not found

### ISSUE THREAD

**Issue by radjivF** [NuGet/Home#5705]
I have install Nuget with brew ``` ==> Pouring mono-5.0.1.1.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/man5/mdoc.5
/usr/local/share/man/man5 is not writable. ``` 

And I try ```brew link mono
Linking /usr/local/Cellar/mono/5.0.1.1...
Error: Could not symlink share/man/man5/mdoc.5
/usr/local/share/man/man5 is not writable.```

But didnt work either, any idea ?

**Comment by emgarten** [comment]
This seems like an issue with the brew, can you log an issue on the owner?

**Comment by Ic3fr0g** [comment]
Try `sudo chown -R (username-here) /usr/local/share/man/man5`.
