### ISSUE TITLE
The performance of "nuget pack" decreases with increasing levels in the source paths

### ISSUE THREAD

**Issue by psmolkin** [NuGet/Home#5706]
I have a project that contains about 1800 files. It is in the directory, i.e. c:\source
Packing with `nuget.exe pack test.nuspec -NoPackageAnalysis` takes about 8 seconds.
When I add one more level to the source path, for example c:\Repos\2 , the packaging time increases to 9 seconds. But the more levels the more time increases:
c:\source\2 - 9sec
c:\source\2\3\ - 10sec
c:\source\2\3\4\ - 12sec
c:\source\2\3\4\5\ - 17sec
c:\source\2\3\4\5\6\ - 25sec
c:\source\2\3\4\5\6\7\ - 44sec
c:\source\2\3\4\5\6\7\8\ - 1m 22sec

The nuspec does not contain anything except
`<file src="c:\source\" target="test" />`

NuGet.exe v4.1.0-4.3.0
OS version: win10 v15063 

Nuget v3.5 doesn't have this issue

**Comment by zhili1208** [comment]
@rohit21agrawal

**Comment by dtivel** [comment]
Resolved by NuGet/NuGet.Client#1644

**Comment by rohit21agrawal** [comment]
had to revert change because of functional test failures

**Comment by BlackGad** [comment]
PR with fix was merged, problem solved in dev branch :)

**Comment by psmolkin** [comment]
![IMG_20210331_000339_484](https://user-images.githubusercontent.com/24776038/113056653-b9aa0400-91b4-11eb-8971-5c5b74691f74.jpg)
