### ISSUE TITLE
"nuget sources update" removes all NuGet sources

### ISSUE THREAD

**Issue by TAGC** [NuGet/Home#5707]
## Description

I have a bitbucket pipelines build that failed after I upgraded from a Docker image based on microsoft/dotnet:1.1.2-SDK to microsoft/dotnet:2.0-SDK.

I found that it was caused by this command:

```
nuget sources update -name "<Company Feed>" -source https://www.myget.org/F/<company>/api/v3/index.json -user $MYGET_USER -pass $MYGET_PASS -StorePasswordInClearText -configFile NuGet.Config
```

I ran the same set of commands within Docker containers based on both images, and found that it only failed in one. The one that this command **failed** in has NuGet version **2.8.7.0** installed, and the passing one has version **2.8.1.0** installed.

## Expected Behaviour

In the container with NuGet 2.8.1.0 installed, my NuGet config correctly retains all package sources after running this command:

```
  <packageSources>
    <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    <add key="Code Comb" value="https://www.myget.org/F/codecomb-rc2/api/v3/index.json" />
    <add key="ASP.NET Core Master" value="https://dotnet.myget.org/F/aspnetcore-master/api/v3/index.json" />
    <add key="<Company Feed>" value="https://www.myget.org/F/<company>/api/v3/index.json" />
    <add key="https://www.nuget.org/api/v2/" value="https://www.nuget.org/api/v2/" />
  </packageSources>
```

This is the expected behaviour.

## Actual Behaviour

In the container with NuGet 2.8.7.0 installed, it's like this:

```
  <packageSources>
    <add key="https://www.nuget.org/api/v2/" value="https://www.nuget.org/api/v2/" />
  </packageSources>
```

This of course causes `dotnet restore` to subsequently fail, complaining about not being able to resolve my company's packages.

**Comment by TAGC** [comment]
I realise that these are both old versions of NuGet; however, they're the latest versions used by Debian Jessie and Stretch respectively, which Microsoft's .NET Core SDK Docker images are based on.

That means anyone trying to install NuGet on even the latest versions of these Docker images may face this issue.

**Comment by zhili1208** [comment]
there are lots of setting issue in nuget 2.x, we should ask them to update docker images to 4.X

**Comment by TAGC** [comment]
I'd appreciate that, thanks.

**Comment by TAGC** [comment]
Any update on this?
