### ISSUE TITLE
Out of memory exception while installing Umbraco

### ISSUE THREAD

**Issue by JSinghDev** [NuGet/Home#571]
I was installing Umbraco 7.2.4 & 7.2.5 using nuget on visual studio 2015 RC and it is giving an out of memory exception. I examined the memory usage of visual studio it kept on climbing with no progress on the installing and it was stuck at getting package dependencies.

**Comment by emgarten** [comment]
This looks related to https://github.com/NuGet/Home/issues/539

This is likely due to umbraco depending on unlisted packages.
