### ISSUE TITLE
VS Running the restore command for package.config when Restore is disabled displays incorrect message 

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#5718]
there are two issues about restore error message for packages.config when restore is disabled.

1. all packages are installed, VS still show error message if restore is disabled
2. VS shows typo name instead of package information for missing package

![capture](https://user-images.githubusercontent.com/7131513/29048791-539ce444-7b87-11e7-9b44-8385265e7bdd.JPG)

**Comment by zhili1208** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/e02233b8872ec0769fe9836d60d8c48900655bb3

**Comment by rrelyea** [comment]
is this a dupe of #5659 ?
or two different sets of issues fixed with one commit?

**Comment by zhili1208** [comment]
not a dupe, two related issue fixed in one commit
