### ISSUE TITLE
NuGet v3 error message for missing packages is misleading

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#572]
> PM> update-package System.Collections.Immutable -version 1.1.34-beta
Attempting to gather dependencies information for package 'System.Collections.Immutable.1.1.34-beta' with respect to project targeting '.NETFramework, Version=v4.5.1'
Attempting to resolve dependencies for package 'System.Collections.Immutable.1.1.34-beta' with DependencyBehavior 'Lowest'
update-package : Missing dependency information for package: System.Collections.Immutable
At line:1 char:1
+ update-package System.Collections.Immutable -version 1.1.34-beta
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

This error message is just like #488 where there was an error in the service.
But the problem here is that 1.1.34-beta does not even exist on the server. I should have typed `1.1.34-rc`. But this error message doesn't help me realize the package just isn't there, instead mentioning that dependencies for that package couldn't be collected.

Can the error message be improved?

**Comment by emgarten** [comment]
We have a fix for this in the works. i'll update this issue once the fix is checked in.

**Comment by emgarten** [comment]
Fixed NuGet/NuGet.Packagemanagement@20785be9ec6e4b521e3c945c2ae986190fb18db9
