### ISSUE TITLE
Auto Restore and Solution Restore should fail immediately when consent is not granted.

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#5722]
OnBuild restore fail immediately when consent is not granted.

But Auto Restore and Solution Restore still start a restore job and fail in the restore job.

The reason we do that is we need to raise the missing package bar for packages.config.

Open question is do we still need to raise missing package bar when restore is disabled.

Onbuild restore doesn't do that in current design.

**Comment by nkolev92** [comment]
Nikolche triage: Closing this. Disabling consent is not super common and we've never heard complaints about this scenario.
