### ISSUE TITLE
NuGet output log doesn't seem to complete when restoring packages

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5728]
Remove the content above here and fill out details below.

## Details about Problem

Version 15.3.0 Preview 7.0 [26730.0.d15rel]

## Detailed repro steps so we can see the same problem

1. Open Output window
2. Create new .NET Core (Console Application)
3. Wait for restore to finish

Expected: Package Manager output to say it's done
Actual:
![image](https://user-images.githubusercontent.com/1103906/29108145-16685d60-7d21-11e7-86c6-13554e2f40bd.png)

**Comment by nkolev92** [comment]
That looks weird. 
I did a quick sanity test and it seems fine. 
Did VS hang or something? 

Can you repro it consistently?

**Comment by nkolev92** [comment]
Closing this as we haven't hit this issue.
