### ISSUE TITLE
nuget restore from command line fails with 4.3-preview

### ISSUE THREAD

**Issue by GouriKumari** [NuGet/Home#5730]
## Details about Problem

nuget restore from command line fails for Windows UWP projects with 4.3-preview

NuGet product used : NuGet.exe

NuGet Version: 4.3.0.4

OS version : windows and macOS

Worked before? If so, with which NuGet version: NuGet Version: 4.1.0.2450 and 3.5.0.x

## Detailed repro steps so we can see the same problem

1. Download  a forms sample , https://developer.xamarin.com/samples/xamarin-forms/Behaviors/AttachedNumericValidationBehavior/AttachedNumericValidationBehavior.zip

2. Execute 'nuget.exe restore AttachedNumericValidationBehavior\WorkingWithBehaviours.sln' from commandline

3. Nuget packages fails to restore

### Verbose Logs
Restore failure : https://gist.github.com/GouriKumari/19aea37f9a8709f8b0bbfb136bed4f0b
Restore success: https://gist.github.com/GouriKumari/51b826690580857d9c100333f67042e8

### Sample Project
https://developer.xamarin.com/samples/xamarin-forms/Behaviors/AttachedNumericValidationBehavior/AttachedNumericValidationBehavior.zip

**Comment by nkolev92** [comment]
This has been fixed in the latest previews. 
We will release our rtm version at the beginning of next week. 
https://dist.nuget.org/index.html

**Comment by nkolev92** [comment]
@GouriKumari Can you please make sure that this problem is fixed on your end as well. 
These are our latest preview bits.
https://1drv.ms/f/s!Atw9UGgSyF-E1TIU_-1le9R2zDWH

Thanks.

**Comment by GouriKumari** [comment]
@nkolev92 : 
It's working from my end as well.
https://gist.github.com/GouriKumari/f4a71c04d357d470f977738940f05af3

**Comment by nkolev92** [comment]
@GouriKumari 
awesome. thanks!

**Comment by xavier-rigau** [comment]
What version of Nuget has this fix?

**Comment by nkolev92** [comment]
@xavier-rigau NuGet.exe version 4.3.0
https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

**Comment by xavier-rigau** [comment]
I don't know if it is exactly the same issue but I got redirected here. 4.3.0 still has this problem:

https://forums.xamarin.com/discussion/comment/295279

**Comment by nkolev92** [comment]
@xavier-rigau It doesn't look like the same issue to me. 

If your problem persists can you please create a  <a href="https://github.com/NuGet/Home/issues/new">new bug</a> and add the repro steps and details there.

- Version used. 
- Did it ever work before (do earlier nuget.exe releases have this problem) ? 
- Logs from update on the solution/project. 
- Can you provide a repro solution?

Thanks!
