### ISSUE TITLE
4.4 Bugs

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#5732]
- [x] https://github.com/NuGet/Home/issues/5641 - [DesignConsistency] Confusing message when adding a NuGet package
- [x] https://github.com/NuGet/Home/issues/5642 - [DesignConsistency] NuGet Installation status text doesn’t look correct on dark theme currently.

**Comment by mishra14** [comment]
@PatoBeltran can we re-triage this with the right milestone?
