### ISSUE TITLE
test bug

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5733]
@NuGet/nuget-client

**Comment by rrelyea** [comment]
can you fix this? :-)

**Comment by emgarten** [comment]
I am blocked by this, is there a workaround yet?

**Comment by rohit21agrawal** [comment]
@emgarten yeah. run the following command on your machine:
``` git config user.email "email@microsoft.com" ```

**Comment by emgarten** [comment]
Looks like a malicious command that would steal my identity

**Comment by rohit21agrawal** [comment]
@NuGet/nuget-client trying to make it public to see if that would work

**Comment by mishra14** [comment]
@rohit21agrawal  seems like the work of a hacked account. very suspicious.

**Comment by nkolev92** [comment]
Are we shipping a hotfix for this @rohit21agrawal

**Comment by nkolev92** [comment]
We've had our fun, closing this :)
