### ISSUE TITLE
Multiple NU1603 warnings in Error List for the same issue

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5734]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS

NuGet version (x.x.x.xxx): 4.4.0.4365

VS version (if appropriate): d15rel 26730.0

## Detailed repro steps so we can see the same problem

1. Create new net core console app (ProjA)

2. Add a new net core class library to the solution (ProjB)

3. Add project reference to ProjB

4. Add the following to ProjB.csproj

```
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.0" />
  </ItemGroup>
```

5. Restore solution.

## Actual Behavior

2 warnings are generated in the VS Error List

## Expected Behavior

Only one warning should be generated for ProjB.csproj

**Comment by nkolev92** [comment]
@mishra14 
Any updates here?
Did anything change? Still needs worked on?

**Comment by nkolev92** [comment]
This has been long fixed. 
I have verified this in 4.9.3 and 5.0 previews.
