### ISSUE TITLE
Add support for HTTP Authorization header

### ISSUE THREAD

**Issue by infin8x** [NuGet/Home#5739]
Feature request

NuGet product used: NuGet.exe | dotnet.exe
NuGet version (x.x.x.xxx): any
dotnet.exe --version (if appropriate): any

We'd like to have the ability to add a single-use token (provided by the VSTS Team Build system) into the HTTP Authorization header for restore and push requests. In our flows, the build agent already handles authorization and has a token that other tools (e.g. Git.exe) already use when accessing VSTS resources.

**Comment by maartenba** [comment]
Can't you use an API key for this? Already supported in all NuGet versions.

**Comment by emgarten** [comment]
@alexmullans can you explain what would be needed from nuget for this? An extension point for injecting headers provided by the current credential provider extension points?

**Comment by infin8x** [comment]
We discussed more internally, it looks like we'll continue to use the Credential Provider rather than this header.
