### ISSUE TITLE
Client should handle incorrect json

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#574]
This bug was found by an external user.

When parsing json response from the v3 server, the client code does not handle incorrect result. E.g. this is the code in nuget 3.0 RC that gets the RequireLicenseAcceptance property:
```
var requireLicenseAcceptance = 
    metadata[Properties.RequireLicenseAcceptance] == null ? 
    false : 
    metadata[Properties.RequireLicenseAcceptance].ToObject<bool>();
```
If the value of Properties.RequireLicenseAcceptance cannot be parsed into bool, `ToObject<bool>()` throws an exception and this crashes VS. Right now, this happens package fsharp.quotations.compiler is returned. This is the snippet of the returned json 
```
 "requireLicenseAcceptance": "",
```

In the current dev branch this problem doesn't occur since this parsing code is on longer used by the UI search. But there are still many places where `ToObject<>()` and `Value<>()` are used and we need to fix them so that we don't throw exceptions and crash VS when an malformed result is returned.

**Comment by davidfowl** [comment]
Try to avoid ToObject<T> for known shapes, it's hella slow :smile:

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet3/blob/d8919d66892348e04301d33ccf22f52afb22c113/src/NuGet.Protocol.Core.v3/PackageMetadataParser.cs#L25

https://github.com/NuGet/NuGet3/blob/d8919d66892348e04301d33ccf22f52afb22c113/src/NuGet.Protocol.Core.v3/PackageMetadataParser.cs#L39

**Comment by yishaigalatzer** [comment]
@johnataylor the server should probably normalize this as well
