### ISSUE TITLE
Restore doesn't work with modified build output

### ISSUE THREAD

**Issue by lennoncork** [NuGet/Home#5742]
This problem applies to both VS2017, nuget.exe and MSBuild restore If you modify the build output and use configuration variables. 

## Example
`<OutputPath>..\output\$(AssemblyName)\bin\$(Configuration)</OutputPath>`
`<BaseIntermediateOutputPath>..\output\$(AssemblyName)\obj\$(Configuration)</BaseIntermediateOutputPath>`

## Reproduction (VS2017)
1. Create a netstandard project in VS2017
2. Change the build output to be conditional on the configuraiton and assembly name
3. Build "Debug"
4. Switch configuration to Release
5. Build "Release"
_At this point the build fails saying that the dlls provided by NuGet cannot be found._ 
6. Restore packages for solution
_NuGet package manager says nothing to be done._ 

## Reproduction (NuGet.exe)
1. Same setup as above
2. Run NuGet restore
_It looks like restore only works for the "Debug" configuration._ 
3. Running MSBuild on a "Release" configuration fails. 

## Workaround (1)
Don't modify the build output or have it conditional on variables. 

## Workaround (2)
Restart visual studio after switching configurations. This will force a restore and allow you to build correctly. 

## Workaround (3)
Run MSBuild restore target for both "Release" and "Debug" configurations before building. This is what we ended up doing on the build server. 

### Sample Solution
The sample solution provides both projects, one that works when switching configurations, one that doesn't
[NuGetTests.zip](https://github.com/NuGet/Home/files/1216972/NuGetTests.zip)

**Comment by emgarten** [comment]
@lennoncork does visual studio automatically restore when you change configuration?

Restore does not support multiple configurations, but potentially visual studio could detect this change and trigger a new restore.

For command line scenarios what you describe is expected, restore allows for multiple TargetFrameworks, but configuration and other properties require that restore be executed first to sync up the restore output with the project.

**Comment by lennoncork** [comment]
@emgarten yes, Visual Studio does restore, but it say's there is nothing to be done (even though the .dlls don't exist in the output). I suspect that NuGet/MSBuild doesn't realize that the build output is different from default. It could be that VS does not re-evaluate the .csproj file when switching configurations. 

To be clear, even if you manually force a restore from withing Visual Studio you still get build errors. You have to either restart VS or manually call MSBuild restore with the appropriate configuration. I don't think you can use NuGet restore because there is no configuration switch to call (it seems to only restore "Debug" when the build output is changed).

**Comment by lennoncork** [comment]
@emgarten do you think this is worth reporting against MSBuild? Is it a NuGet issue or something related to Visual Studio?

**Comment by dasMulli** [comment]
Setting `BaseIntermediateOutputPath` inside a project isn't safe and there even is an sdk issue about making it an error: https://github.com/dotnet/sdk/issues/803
You can find a few workarounds at https://github.com/dotnet/sdk/issues/1518 and some more explanations on https://stackoverflow.com/questions/45575280/msbuild-nuget-restoreoutputpath-how-to-make-it-work/45589468#45589468
However, none of the workarounds allow using variables that are defaulted in the common properties, like `$(AssemblyName)` or `$(Configuration)` (unless you set / default them manually).

**Comment by lennoncork** [comment]
@dasMulli thanks you very much for the information.

I think for now we're going to drop the unified build output and stick with default. It's a shame because it works for the most part, just doesn't restore appropriately. Referencing another issue for anyone else coming across this: dotnet/sdk#867.

**Comment by lennoncork** [comment]
In the end, the solution for us was to use "Directory.Build.Props". Works well with no obvious issues. Thanks to @dasMulli and @emgarten for the help. Closing this as I suspect "Directory.Build.Props" is the correct solution.
