### ISSUE TITLE
Provide means/ways/option to measure underlying service execution times.

### ISSUE THREAD

**Issue by JackGrinningCat** [NuGet/Home#5745]
Hi,

I had recently a problem with the update and installing of a packet. I took around a minute.
So it dropped to 5 seconds after some changes and retries. But sometimes its hard to say where the problem is lying. But within, I was searching for the issues here and wrote a commend to not let it drop.

A college reported later, that network was slow on that day. So this days I wish for an option tool, something, to have a times log for the action, complexity, amount of request for a certain action.

When 80 percent from my problems arise due to an a problem the nuget team cannot changes anything, I do not need to raise a issue here, but with my IT/network, Team, Providers.

It's like blaming the delivery service that the producer did't deliver the goods beforhand.

If your versioning with pre-releases is fexing. I should pressure our team to make an release, instead of waiting for nuget to improve such the update times for stupid complex case.
If our IT/network is slow, ...
If our PCs are low-end (ok, they are not)

If the nuget Team would provide such option/means tools, it would give ways to improve my satisfaction with nuget.

I posted here my comment
#4897
This seems to be the epic story
#1909

**Comment by nkolev92** [comment]
Lower priority.
