### ISSUE TITLE
Seems SearchLatestResource is no longer used. If so, we should remove it.

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#575]
While investigating issue https://github.com/NuGet/Home/issues/574, I found that the class SearchLatestResource (which calls the method that triggers the error) is no longer used in the current dev branch code. If that's the case, then we should remove this class plus its derived classes from our code base.

**Comment by emgarten** [comment]
This resource has been removed.

**Comment by zhili1208** [comment]
Verified fixed with 3.5.0-beta (build 3.5.0.1249)
