### ISSUE TITLE
Improve RestoreOperationLogger performance using idle task priority

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#5750]
### Problem
`RestoreOperationLogger` schedules log tasks using conventional `JTF.RunAsync` API. This can potentially overwhelm VS UI thread and make it unresponsive in case of hundreds log messages.

### Solution
Consider using the extension method `JTF.StartOnIdle` to reduce the main thread stress.

Further logger improvement may involve batching log messages as well.

**Comment by nkolev92** [comment]
Related: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.outputwindowtextwriter.-ctor?view=visualstudiosdk-2019.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9915.

**Comment by nkolev92** [comment]
This is no longer an issue. 
https://github.com/NuGet/NuGet.Client/commit/da818d72953901420bfc731e4b7c1100289fc6f3, https://github.com/NuGet/NuGet.Client/commit/20d69ae4af83071e040a9db4d9939a8564001a74,
https://github.com/NuGet/NuGet.Client/commit/77baa1563bb5aa8726bcf0f54d913ebe71e657ee have in a way helped improve this.
