### ISSUE TITLE
VS2017 .NET Standard - Pack option - generate Nuget Packages in a unified directory for all projects in the solution / customize package creation path

### ISSUE THREAD

**Issue by sakher-sawan** [NuGet/Home#5753]
Please read the following information before posting the issue.
## Details about Problem

NuGet product used (VS UI | Package Manager Console | dotnet.exe):

NuGet version (Package Manager Console Host Version 4.1.0.2427):

dotnet.exe --version (2.0.0-preview2-006497):

VS version (VS2017 26403.7):

OS version (win10):

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a .NET Standard project (class library)

2. Configure it to create a Nuget package (from project properties, Package tab).

3. Build, it will build in (bin/debug), but there is no way to configure it to create the package in a relative path, where that path can be set as a local package repo, to reference from it later.

## Other suggested things
Suggest to add this option (to customize the path where Nuget packages are created).

**Comment by rohit21agrawal** [comment]
@mss37  you can set the ``` <PackageOutputPath> ``` property in your csproj (which is relative to your project directory) to determine where the package gets output. 

For reference , https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target

**Comment by sakher-sawan** [comment]
I realized that, then the request is to make this available in VS 2017 UI (Package tab in project properties page).
![image](https://user-images.githubusercontent.com/15035699/29285080-17ac13e4-8125-11e7-9a05-44e4714d5f42.png)

**Comment by rohit21agrawal** [comment]
oh, let me move this to the appropriate repository then.
Appreciate the feedback @mss37 ! Keep it coming :)

**Comment by rohit21agrawal** [comment]
This issue was moved to dotnet/project-system#2709
