### ISSUE TITLE
Unlike V3, NuGet V2 Protocol does not return comparable properties as V3, when looking at package details pane of UI.

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#576]
Unlike V3, NuGet V2 Protocol does not return the 'Report Abuse Url' and more. Need to take care of other properties as well

**Comment by danliu** [comment]
I've fixed the report Abuse URL to unblock functional tests.

**Comment by danliu** [comment]
Discussed with Deepak, the other part seems that when the feed is V2, the package details pane does not return all of the properties as of V3 feed. Need to investigate which property is missing from the protocol layer for V2.

**Comment by danliu** [comment]
Compared the properties on the UI for V2 and V3 feed, they seems to be matching, since now reportAbuse URL for V2 is showing as well. 

Close this bug, fixed via https://github.com/NuGet/NuGet3/commit/ecc3ed3546d644bbdff845c34fbf56b2cbf6e241
