### ISSUE TITLE
NuGet/Media repository contains outdated artwork

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#5770]
The [NuGet/Media](https://github.com/NuGet/Media) repository has historically been the home of all NuGet high-res logos, vector graphics and artwork.

However, the repo is outdated since our redesign, and does not contain the new logo and updated artwork.
New vector graphics are spread over the NuGet.Client and NuGetGallery repositories currently.

It would be good to have this NuGet/Media repository updated with an aggregation of all up-to-date graphics, to facilitate brand consistency whenever someone desires to use one of the NuGet logos.

**Comment by rrelyea** [comment]
@anangaur - do you have a handle on the set of things that we might pull in here?

**Comment by anangaur** [comment]
I do have the main images. However we would need to convert into different sizes to replace already present files. @jonwchu may be able to help here.

**Comment by nkolev92** [comment]
Pinging @jonwchu, @anangaur again

**Comment by jonwchu** [comment]
Just submitted a pull request: https://github.com/NuGet/Media/pull/2
