### ISSUE TITLE
Missing license headers in EndToEnd test templates

### ISSUE THREAD

**Issue by omajid** [NuGet/Home#5774]
Various files in EndToEnd directory in NuGet.Client have no license headers. For example: https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/ProjectTemplates/CppWinStoreApplication.zip/App.xaml or https://github.com/NuGet/NuGet.Client/blob/dev/test/EndToEnd/ProjectTemplates/CppWinStoreApplication.zip/App.xaml.h

Is that intentional? If so, can you confim that the license in the root of repository covers these files?

cc @rrelyea @leecow

**Comment by rrelyea** [comment]
Digging into this.

Believe that these templates were all created like this:

- File/New Project/choose a project type/Ok

- Project/Export Template

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet.Client/commit/3e5a0f4ed1e98244f8dd7204e8468460116ff559
