### ISSUE TITLE
Test files with confusing licenses

### ISSUE THREAD

**Issue by omajid** [NuGet/Home#5776]
Two files in NuGet.Services.Metadata have a very confusing license header:

    /*
    * Note: While Microsoft is not the author of this file, Microsoft is
    * offering you a license subject to the terms of the Microsoft Software
    * License Terms for Microsoft ASP.NET Model View Controller 3.
    * Microsoft reserves all other rights. The notices below are provided
    * for informational purposes only and are not the license terms under
    * which Microsoft distributed this file.
    *
    * jQuery Validation Plugin - v1.13.1 - 2/4/2013
    * https://github.com/jzaefferer/jquery-validation
    * Copyright (c) 2013 Jörn Zaefferer; Licensed MIT
    *
    */

See https://github.com/NuGet/NuGet.Services.Metadata/blob/release/tests/AAD/NuGet.Test.WebSite/Scripts/jquery.validate-vsdoc.js and https://github.com/NuGet/NuGet.Services.Metadata/blob/release/tests/PublishTestDriverWebSite/Scripts/jquery.validate-vsdoc.js

Are these files not under the MIT license that the last lines of the header states or under Apache 2.0 that the LICENSE file in the root of repo states?

Searching for the MVC 3 license leads me to https://www.microsoft.com/web/webpi/eula/aspnetmvc3update-eula.htm which seems completely inappropriate as a license for an open source project.

Could you please fix this license header?

**Comment by omajid** [comment]
cc @leecow @rrelyea

**Comment by omajid** [comment]
cc @richlander

**Comment by omajid** [comment]
cc @Bob-Davis

**Comment by zhili1208** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/3e5a0f4ed1e98244f8dd7204e8468460116ff559
