### ISSUE TITLE
Nuget package install fails for any Nuget core  packages on .Net core app 1.1.2

### ISSUE THREAD

**Issue by nimisha84** [NuGet/Home#5780]
![nuget error](https://user-images.githubusercontent.com/4319227/29482113-ce9a3852-843f-11e7-8623-c9a50db41e51.png)

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Nuget package Manager UI or console tool
NuGet version (x.x.x.xxx):
4.3.0-preview3-4168

dotnet.exe --version (if appropriate):

VS version (if appropriate):VS2017

OS version (i.e. win10 v1607 (14393.321)):Win 8 - Virtual machine

Worked before? If so, with which NuGet version: No nuget version works for installing .Net core 1.1.2 project related packages like-
Microsoft.AspNetCore.StaticFiles
Microsoft.AspNetCore.Mvc

## Detailed repro steps so we can see the same problem

1. Downloaded .Net Core SDK 2.0.0 and installed it.
2. Then created .Net Core web application in VS 2017.
3. Nuget Package Restore is failing for any nuget packages

...

## Other suggested things

Added screenshot of error.
[OdeToFood.zip](https://github.com/NuGet/Home/files/1235995/OdeToFood.zip)

### Sample Project

Added.

**Comment by davidfowl** [comment]
Did you update your project to .NET Core 2.0.0?

**Comment by nimisha84** [comment]
No, I did not. In my screenshot the Nuget folder refers to AspNetCore-1.1.2

**Comment by davidfowl** [comment]
There's no issue then. The packages you're trying to install require .NET Standard 2.0. The error messages looks wrong though. Maybe you're nuget is old. Are you using VS 2015 15.3?

**Comment by nimisha84** [comment]
I updated my Nuget to NuGet version (x.x.x.xxx):
4.3.0-preview3-4168

and I'm using VS2017. Still got the same error. I have attached my project for reference.

**Comment by davidfowl** [comment]
The error message is still bad then, but the error in general is by design.

**Comment by nimisha84** [comment]
Ok, let me update to .Net Core 2.0 and then retry. Will update you. Thanks!

**Comment by nimisha84** [comment]
It works on updating to .Net Core 2.0. Thanks for the help.
