### ISSUE TITLE
non compliant behavior on update

### ISSUE THREAD

**Issue by smalldek** [NuGet/Home#5783]
nuget update does not conform to the documentation regarding the modifications to the project file. Documentation states that

>  'The update command also updates assembly references in the project file, **provided those references already exist**.'

 but it removes the references and install the new package instead. It results in unused references in the csproj.
Expected behavior would be that only existing references are modified (i.e. updated version number in path and assembly name).

## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe
NuGet version (x.x.x.xxx): 4.1.0.2450
OS version (i.e. win10 v1607 (14393.321)): Win 8.1 Pro

## Detailed repro steps so we can see the same problem
1. Create a package containing more than one assemblies in 'lib' folder
2. Install the package inside a .NET project
3. Remove all added references but one
4. Publish a new version of the package (no need to have actual changes, just increase version number)
5. Launch nuget update on the project
The resulting .csproj contains references to all assemblies from the package.

**Comment by rrelyea** [comment]
We're moving away from Packages.Config towards a better future system "PackageReferences" for this kind of reason...so there is only one place the package is listed...and references work under the covers (during the msbuild pipeline).
This gets around the problem you mention, and many other similar problems.
Today, the migration is manual, but we hope to make it easier in the coming releases.
