### ISSUE TITLE
cs files are not honored in net 4.61 with dotnet pack and are not marked as build only content

### ISSUE THREAD

**Issue by bklooste** [NuGet/Home#5785]
cs files are not honored  , we have a large test base class for a contract which people cant  step through to debug so I wanted to deploy it as source . Packing is with dotnet pack this used to be possible but we moved to new project files due to major issues with package.config  and the number of packages mvc core produces ( nuget updates were take over 6 minutes) ..

From the generated files I get either 

    <contentFiles>
      <files include="any/net461/contentFiles/Sources/Cosmos.Services.SharedTests/StandardCrudServiceTestsv1.cs" buildAction="Content" />
   </contentFiles>

or 

    <contentFiles>
      <files include="any/net461/contentFiles/Sources/test3.pp" buildAction="Content" />
    </contentFiles>

Source project 

```
>    <PropertyGroup>
>     <TargetFramework>net461</TargetFramework>
>     <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
>     <IsPackable>true</IsPackable>
>     <IncludeBuildOutput>false</IncludeBuildOutput>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <None Remove="Cosmos.Services.SharedTests.Sources.nuspec" />
>   </ItemGroup>
> 
>     <Content Include="contentFiles\Sources\test3.pp">
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>     </Content>
>   </ItemGroup>
>   
>   <ItemGroup>
>     <ProjectReference Include="..\..\Cosmos.Services.Contract\Cosmos.Services.Contract.csproj" />
>     <ProjectReference Include="..\Cosmos.Services.Shared.xTests\Cosmos.Services.Shared.xTests.csproj" />
>   </ItemGroup>
>   
>   <ItemGroup>
>     <Compile Update="contentFiles\Sources\Cosmos.Services.SharedTests\StandardCrudServiceTestsv1.cs">
>       <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
>     </Compile>
>   </ItemGroup>
```

Also the content files do not seem to refresh until VS is restarted ( using 17,.2) .. Been on this for 2 days and the doco is very sketchy ,its frustrating that I can get the cs file in but its always marked as a resource not compile. Hence trying to get pp working.

Will this work with a hand crafted file and using <NuspecFile> in the proj ?

I note https://github.com/NuGet/Home/issues/4803  seems to have some ability to generate compile eg 
       <contentFiles>
            <files include="contentFiles\App_Packages\**\*.*" buildAction="Compile" />
        </contentFiles>

but I haven't been able to work it out...via dotnet pack.  It is a matter of putting it in App_Packages or do I need a custom nuspec and then put a  <NuspecFile>MyNuspec.nuspec</NuspecFile> 

Since the above issue talks about pp I have changed this to refer to raw cs files.

**Comment by rrelyea** [comment]
@rohit21agrawal  - please work with @bklooste

**Comment by rohit21agrawal** [comment]
@bklooste set ``` <Pack>true</Pack> ``` on your ```Compile``` items and those files should be included as contentFiles automatically with BuildAction = Compile

**Comment by rrelyea** [comment]
@bklooste  - closing as it appears to be resolved. Please reactivate or comment again if problem.
