### ISSUE TITLE
How to uninstall NuGet packages while that package not available in Nuget cache location

### ISSUE THREAD

**Issue by joo92** [NuGet/Home#5787]
Issue 1: I have uninstall Nuget package which unavailable in NuGet cache using below code I get error like package uninstall failed.

  var installer = componentModel.GetService<IVsPackageUninstaller>();
  installer.UninstallPackage(project, NuGetPackageName, false);

Issue 2: I have removed unavailable package entry from ASP.NET Core project and install same package with available version, it's show exception like Package restore failed. Rolling back package changes in projectName before try to install that package. 

installer.installPackage(project, NuGetPackageName,false);

Can you please update if there's any solution to resolve above issue? 

I need to uninstall NuGet packages which unavailable in NuGet cache location and install same NuGet package another version which available in NuGet cache location.

Its possible to uninstall Nuget package which unavailable in NuGet cache location programmatic?

Thanks,
joo

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version : latest 

VS version (if appropriate): VS2010,VS2012,VS2013,VS2015

OS version : windows 10

## Detailed repro steps so we can see the same problem
**Issue 1:**
1. Install Nuget package in x.x.x version in ASP.NET Core project

2. Remove Nuget packages from Nuget cache location.

3. After that Uninstall that package form project using installer.

**Issue2**
1. Install Nuget package in x.x.x version in ASP.NET Core project

2. Remove Nuget packages from Nuget cache location.

3. Remove Nuget package entry from ASP.NET Core project file. Then save project and try to install same package with another version. it's show exception like "Package restore failed. Rolling back package changes in projectName"

**Comment by jainaashish** [comment]
Can you share more details about your issues:
1. What is the NuGet version and VS version? please be specific than just `latest`
2. Are you using packages.config file or PackageReference to maintain NuGet dependencies?
3. Can you share the complete error message which is being returned for both the cases?
4. Do these issues only repro's with Installer API? how about Manager UI or PMC inside VS?

As for workaround then try below steps depending on your explanation, they might work.
1. You can remove that package completely from project which means - remove it from packages.config (if exists), remove that reference or packageReference from .csproj file, delete project.assets.json file from <projectDir>/obj folder (if exists). 
2. Restore that project
3. Then install the package.

**Comment by joo92** [comment]
Yes. I have tried above provided workaround steps. I have removed packageReference from .csproj file then  project saved. Now I will try to install the package its will be get exception like  **"Package restore failed. Rolling back package changes in projectName"**.

Can you please update solution to restore and install removed package with another version?

**Comment by nkolev92** [comment]
@joo92 Can you please provide the information that @jainaashish requested?

The package restore failing could be due to a multitude of reasons, among which it might be that the package is just incompatible with your project.
