### ISSUE TITLE
Feature request: nuget pack -symbols should embed sources for PortablePDB files

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#5788]
Feature request: nuget pack -symbols should embed sources for PortablePDB files.

Right now, just the PortablePDB is embedded, which has no source code in it. This renders creating symbols packages useless, as they can't be used to do source stepping etc.

Repro steps:
* Pack any project that uses the new .csproj format
* Publish the package and its symbols
* Install the package on another machine, try source stepping
* Source stepping will not work

**Comment by dasMulli** [comment]
There are a lot of options at the moment, maybe a good time to re-evaluate the defaults:

* SourceLink: embeds reference to a remote source to get the source code - now works in portable and windows PDB
* PDB-Embedded sources: Should work for both portable and windows PDBs, no debugger support yet AFAIK (but some issues in 15.5 milestone).
* Embedded PDBs: it should be possible to embed sources into the pdb **and** the pdb into the output dll, so no need for symbol package (but one huge dll).

Th question is how `nugget pack` and `dotnet pack` should behave by default..

**Comment by maartenba** [comment]
IMHO a behaviour that "almost always works best", or a command-line switch of course :)

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/4142

**Comment by maartenba** [comment]
And #6104

**Comment by rrelyea** [comment]
SourceLink for your portable pdbs, and then pack them in a .snupkg file is the strategy now.
Shipped in VS2017 15.9 and NuGet 4.9.

**Comment by mattleibow** [comment]
I think 4K packages disagree with this: https://github.com/search?q=AllowedOutputExtensionsInPackageBuildOutputFolder&type=code

Also, how is this to work from a CLI perspective? Will the app know how to download symbols? Maybe I am building a MSBuild task?
