### ISSUE TITLE
Authorized NuGet feeds error with 401 instead of prompting

### ISSUE THREAD

**Issue by NickCraver** [NuGet/Home#579]
We use an internal NuGet feed (v2) provided by TeamCity which is an authorized feed. In VS 2013 this would result in prompting for credentials (though, the checkbox to remember them never worked). In 2015 this instead errors **without** ever prompting for credentials to login. Stack below:

    Error occured:\nSystem.Net.WebException: The remote server returned an error: (401) Unauthorized.
       at System.Net.HttpWebRequest.GetResponse()
       at NuGet.RequestHelper.GetResponse()
       at NuGet.HttpClient.GetResponse()
       at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
       at NuGet.RedirectedHttpClient.EnsureClient()
       at System.Lazy1.CreateValue()
       at System.Lazy1.LazyInitValue()
       at System.Lazy1.get_Value()
       at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean absoluteExpiration)
       at NuGet.RedirectedHttpClient.get_CachedClient()
       at NuGet.RedirectedHttpClient.get_Uri()
       at NuGet.DataServicePackageRepository.get_Context()
       at NuGet.DataServicePackageRepository.Search(String searchTerm, IEnumerable1 targetFrameworks, Boolean allowPrereleaseVersions)
       at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, IEnumerable1 targetFrameworks, Boolean allowPrereleaseVersions)
       at NuGet.Protocol.VisualStudio.UISearchResourceV2.<>c__DisplayClass4_0.<<GetSearchResultsForVisualStudioUI>b__0>d.MoveNext()

The server response is:

    HTTP/1.1 401 Unauthorized
    WWW-Authenticate: Basic realm="TeamCity"
    Pragma: no-cache
    Expires: Thu, 01 Jan 1970 00:00:00 GMT
    Cache-Control: no-cache
    Cache-Control: no-store
    Content-Type: text/plain;charset=UTF-8
    Transfer-Encoding: chunked
    Date: Mon, 04 May 2015 17:27:45 GMT

    52
    "Authorization" header is not specified
    To login manually go to "/login.html" page

It makes the same request without the Authorization header 3 times, never prompting for credentials. If it matters, this request is being made over TLS in our case.

The issue was originally created [on the tooling repo with some discussion here](https://github.com/aspnet/Tooling/issues/54).

**Comment by yishaigalatzer** [comment]
@NickCraver there might be two things going on in your case:
1. This issue which was fixed after RC. https://github.com/NuGet/Home/issues/180 Workaround - plug the password into nuget.config
2. There could be on top of that an issue with TLS 1.2 if your server uses it. This is a visual studio bug (where `ServicePointerManager` is not setup to enable TLS1.2). This will be fixed for RTM. The workaround for this own is a bit harder, you need to have something running inside the VS AppDomain (so you might need a vsix for this) that simply sets - `ServicePointManager.SecurityProtocol to enable TLS1.2) see https://msdn.microsoft.com/en-us/library/system.net.securityprotocoltype(v=vs.110).aspx

**Comment by NickCraver** [comment]
Thanks for the info @yishaigalatzer! We support TLS 1.0-1.2 on this feed so that should work on the older protocols. Putting my password anywhere in plaintext is obviously far less than desirable even for a workaround (I'm a domain admin) - so I'll ask: Is there a reason there's not a NuGet extension update available for 2015 RC users that would resolve this? I may be missing other large internal changes that makes it incompatible - but if not can you guys just release an update to the gallery?

**Comment by yishaigalatzer** [comment]
You don't have to place the password in plain text, you can place it encrypted. VS 2013 will do it for you.

When it comes to updating the extension - We plan to, but I cannot commit to a date yet. We are trying to make a rather large suite of fixes between RC and now, and we are waiting for a stable enough build with a large enough mass of changes for us to release.

I hope my suggestion above already unblocks you.

**Comment by yishaigalatzer** [comment]
Oh and using your admin account to restore packages is obviously bad form. Can you setup another account just for restore/install?

**Comment by NickCraver** [comment]
@yishaigalatzer It's a little confusing to put in text here, but the admin account I'm passing credentials for to retrieve the packages is not an admin on the system (e.g. I am not using my Windows login credentials) - our remote developers are generally not on the domain. I appreciate the concern though, it's certainly solid advice when dealing with untrusted ps1 scripts and such :)

**Comment by yishaigalatzer** [comment]
Sure. Let me know if this workaround solves the issue for you.

**Comment by emgarten** [comment]
Closing this issue. Please ping @yishaigalatzer if you need further help.
