### ISSUE TITLE
Question regarding Nuget target path in MSBuild project files

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#5791]
_From @jonathanbyrne on August 17, 2017 19:19_

I am trying to put .targets and .props files into the build directory of my NuGet package.  I know how to do this with a .nuspec file but I was hoping to do this in my MSBuild project file.

I can find no documentation of how to do this but it appears to be done in the core-setup file [Microsoft.NETCore.App.pkgproj](https://github.com/dotnet/core-setup/blob/master/src/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj).
```
    <File Include="$(PropsFile)">
      <TargetPath>build/$(NETCoreAppFramework)</TargetPath>
    </File>
```
When I try to replicate the usage above, the build succeeds but the element is apparently ignored because no build directory exists in the NuGet package.  Is there some trick to using this?  Thanks for any guidance you can provide.  (My apologies in advance if this is a question best posed to the NuGet team. I have also asked them.)

_**Version details:**
MSBuild 15.3.409.57025
NuGet 4.3.0.3
Visual Studio 2017 (15.3.0 Preview 7.1)
Windows 10.0.10586_

_Copied from original issue: Microsoft/msbuild#2451_

**Comment by rainersigwald** [comment]
_From @jonathanbyrne on August 22, 2017 15:23_

I found a different way to accomplish my objective but I'm still confused how the example I referenced above was able to work.  If anyone has a quick explanation, I would love to know but please don't waste time researching anything.

```
<Content Include="MyTargets.targets">
    <Pack>true</Pack>
    <PackagePath>build</PackagePath>
</Content>
```

**Comment by rohit21agrawal** [comment]
@jonathanbyrne the above usage of setting Pack=true and PackagePath on your content is correct, can you please tell me what issue are you facing here?

**Comment by jonathanbyrne** [comment]
I was hoping to get clarification on the \<file\> element used in some .Net Core projects files.  (See [this](https://github.com/dotnet/core-setup/blob/master/src/pkg/projects/Microsoft.NETCore.App/Microsoft.NETCore.App.pkgproj) for an example.)

**Comment by rohit21agrawal** [comment]
@jonathanbyrne the ```  <file> ``` element is something that is specific to pkgproj projects , and not something related to NuGet.
I can try finding the owners of pkgproj project types for you if you like, but this is not something I can answer on my own since it has nothing to do with NuGet.

**Comment by jonathanbyrne** [comment]
Thank you for the clarification Rohit.  If that tag and project type aren't related to NuGet, don't worry about trying to find the owners.

In addition to including content files, I also need to include referenced assemblies in the NuGet package.  The \<Content\> tag won't work for this because the referenced assembly will not yet be in the build output directory.  In a .nuspec file, it would be as simple as something like this:

`
    <file src="bin/release/MyLibrary.dll" target="bin" />
`

I've tried everything I can think of but I can't figure out how to do this inside a MS Build project file.

I'm sorry to keep bothering you with questions.  I was very excited to start using the ability to pack a project from inside Visual Studio but it won't be a catastrophe if I need to keep using the .nuspec files for fine-grained control.

**Comment by rrelyea** [comment]
@rohit21agrawal - can you help with that last question?

**Comment by rohit21agrawal** [comment]
@jonathanbyrne you can write a target like this like this:
```
<Target Name="CustomBuildOutputTarget">
    <ItemGroup>
      <BuildOutputInPackage Include="bin\Debug\$(TargetFramework)\abc.dll">
        <FinalOutputPath>{AbsolutePathToDll}</FinalOutputPath>
      </BuildOutputInPackage>
    </ItemGroup>
  </Target>
```

You would also need to set a property so NuGet can run the above target:
``` <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CustomBuildOutputTarget</TargetsForTfmSpecificBuildOutput> ```

**Comment by jonathanbyrne** [comment]
Thank you @rohit21agrawal, that was a **_huge_** help!  I do have one question regarding your example.  When would \<FinalOutputPath\> be different than the Include property on \<BuildOutputInPackage\>?  I omitted \<FinalOutputPath\> and still got the desired result in the NuGet package.  (See example below.)

```
    <PropertyGroup>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CustomBuildOutputTarget</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>
    <Target Name="CustomBuildOutputTarget">
        <ItemGroup>
            <BuildOutputInPackage Include="$(OutputPath)MyAssemblyPrefix*.dll" />
        </ItemGroup>
    </Target>

```

**Comment by rohit21agrawal** [comment]
@jonathanbyrne if the include string is an absolute path, then you don't need the FinalOutputPath.

also, I am closing this issue for tracking purposes, but please feel free to keep using this forum to ask any more questions related to this.
