### ISSUE TITLE
Add friendly license name (string property) to IPackageSearchMetadata

### ISSUE THREAD

**Issue by ohadschn** [NuGet/Home#5793]
It would be very useful to be able to tell the friendly license name (e.g. `MIT` or `Apache 2.0`) from the NuGet management API .

VS and the NuGet gallery know how to do this since 2013:
https://blog.nuget.org/20131011/friendly-license-names.html

Might be related to https://github.com/NuGet/Home/issues/110.

**Comment by jainaashish** [comment]
The original issue #110 is closed as deprecated which happened more than 2 years ago. I'll try n get the reasoning behind it.

**Comment by ohadschn** [comment]
After posting this I realized the friendly name is no longer present, not in the web nor in the VS gallery. So I guess the friendly license feature itself was deprecated. The following issue is probably its replacement (and would be much better if implemented since no heuristic would be involved): https://github.com/NuGet/Home/issues/4628.

**Comment by rrelyea** [comment]
We've moved #4628 into the backlog (with no priority currently). As such, closing this one. Thanks for input.
