### ISSUE TITLE
VS Package Manager. Icons lost after scrolling

### ISSUE THREAD

**Issue by ridomin** [NuGet/Home#5796]
Using Visual Studio 2017 package manager, after scrolling a couple of times some icons are replaced with the default.

See attached animated GIF.

![nugetscroll](https://user-images.githubusercontent.com/1918324/29640158-69f596ae-8812-11e7-9901-67a1b266fb0c.gif)

**Comment by anangaur** [comment]
Why would you scroll so much? ;) Good catch!

**Comment by dominoFire** [comment]
By testing by trial and error, I realized that by removing Virtualization in the InfinteScrollList and the Object Cache in the Converter on top of nuget/nuget.client@38a89ac2c924313a0b2b1e958728bbc7bebcabc1, the issue goes away. But, the performance of the list is degraded. See the table below:

| Cache | Virtualization Result | Comments |
|----|------------------------|----------|
| 0  |   0         |     OK |
| 1  |   0         |     OK |
| 0  |   1         |     Icons disappear in details pane |
| 1  |   1         |     Icons disappear in the scroll list |

**Comment by dominoFire** [comment]
There are some cases when even by removing the Image cache in the Converter and the Virtualization leads to disappearing icons. In the image below, dotnet.icon and dotnet.icon.file packages should have the same image icon but, it only appears on the Package Details pane.

![image](https://user-images.githubusercontent.com/1192347/70682002-447a8e80-1c52-11ea-96a9-e9a2b0b92243.png)

**Comment by dominoFire** [comment]
UPDATE: By setting VirtualizingPanel.IsVirtualizing="false", the issue disappears.

**Comment by dominoFire** [comment]
Possible root cause: when the `InfinteScrollList` is virtualized, some elements with previous broken icons trigger a `PackageIconImage_ImageFailed` event but, the event arrive when a new icon is loaded. See link below

https://github.com/NuGet/NuGet.Client/blob/6e40b4f38b07cabb03eaf10045743ef34c3a87af/src/NuGet.Clients/NuGet.PackageManagement.UI/Resources/Resources.xaml.cs#L16
