### ISSUE TITLE
 Nuget.exe install not getting latest package

### ISSUE THREAD

**Issue by rick-morrow** [NuGet/Home#580]
We maintain multiple versions of the same package in a local nuget repository. We recently discovered that calling

nuget.exe install "packagename"

without specifying a version no longer gets the latest package. This is specific to versions with different number of digits, as it appears to get the package with the higher "string value" (i.e. it will choose packagename.1.0.9 over packagename.1.0.12). I tried with multiple versions of nuget.exe (v2.8.0 - v2.8.5) and the last one that gets packagename.1.0.12 is v2.8.0. Is this a bug that hasn't been fixed yet?

**Comment by AndriySvyryd** [comment]
I'm unable to repro this using nuget.exe v2.8.6
Could you share the .nuspec files from the latest and older packages?

**Comment by rick-morrow** [comment]
Here are the contents of the files (redacted some info for confidentiality purposes). 

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>packageName</id>
    <version>1.0.9</version>
    <authors>National Instruments</authors>
    <owners>National Instruments</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Name Description</description>
    <copyright>Copyright 2015</copyright>
  </metadata>
</package>
```
```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>packageName</id>
    <version>1.0.13</version>
    <authors>National Instruments</authors>
    <owners>National Instruments</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Name Description</description>
    <copyright>Copyright 2015</copyright>
  </metadata>
</package>
```

**Comment by pranavkm** [comment]
Not seeing it repro. Here's what I tried - https://github.com/pranavkm/580_Repro. (Run `test.bat`).
Feel free to update the repository in case you're able to repro the bug and reopen the bug.
