### ISSUE TITLE
Nugetizer packs reference assemblies into NuGet package

### ISSUE THREAD

**Issue by chkn** [NuGet/Home#5800]
## Details about Problem

NuGet product used: Nugetizer 3000

NuGet version (x.x.x.xxx): 4.3.0.4199

dotnet.exe --version (if appropriate): 2.0.0

VS version (if appropriate): Visual Studio for Mac 7.3 Preview (7.3 build 302)

OS version (i.e. win10 v1607 (14393.321)): OS X 10.12.5 (16F73)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. In VS for Mac, create a new .NET Standard 2.0 library project.

2. Open Project Options -> NuGet Package -> Build and check "Create a NuGet package when building the project"

3. Go to the Metadata page and enter a package ID, version, and description.

4. Build the project. If you get an error, you may need to update the `NuGet.Build.Packaging` package.

5. Find the built package in the project output directory. Rename the ".nupkg" extension to ".zip" and unzip it.

6. Inside the package, under the `lib/netstandard2.0` directory, note that there are a ton of System.*.dll reference assemblies.

Expected result: These assemblies should not be packaged in the NuGet package.

Workaround: The reference assemblies are not packaged if you add an explicit PackageReference to `NETStandard.Library` in the csproj:
```
<PackageReference Include="NETStandard.Library" Version="2.0.0" />
```
However, this causes a build time warning telling you that you shouldn't do this.

## Sample Project

Project created using the above steps:
[NETStandard20Test.zip](https://github.com/NuGet/Home/files/1247701/NETStandard20Test.zip)

**Comment by rmarinho** [comment]
have the same issue.

**Comment by pauldendulk** [comment]
Same here.

**Comment by rmsutton** [comment]
Seems like the fix was put in but I am not seeing the changes in 0.2.2. When is this being pushed?

**Comment by kzu** [comment]
From the [readme](https://github.com/NuGet/NuGet.Build.Packaging#installing):

Add the following NuGet feed to Visual Studio:

    https://ci.appveyor.com/nuget/nugetizer3000

Install the following package:

    Install-Package NuGet.Build.Packaging

We won't be pushing to nuget.org regularly until we have a final release.

Thanks!

**Comment by rmsutton** [comment]
I tried version 0.2.3 from the repo above but the problem appears to persist. Has anyone been able to verify if this works in 0.2.3?

**Comment by kzu** [comment]
According to the [latest CI build](https://ci.appveyor.com/project/MobileEssentials/nuget-build-packaging/build/artifacts), the latest version should be `0.2.5-dev.1`. Please make sure to check the "pre-release" checkbox in the IDE.

**Comment by randysimplist** [comment]
The latest version 0.2.5-pr169.7 seems to have the same problem when targeting .NET Core 2.2

**Comment by praeclarum** [comment]
0.2.5-pr169.7 works for me when targeting netstandard, iOS, mac, Android.

**Comment by CarbonLabsUK** [comment]
Hi, I'm still seeing this error when building for netstandard2, ios and android.
I'm using v 0.2.5-dev.8 of NuGet.Build.Packaging.

Is it still an outstanding issue?
