### ISSUE TITLE
Nuget Msbuild does not respect excluding TypeScript generated content based on csproj setting.

### ISSUE THREAD

**Issue by rjamesnw** [NuGet/Home#5801]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS 2017 Community

NuGet version (x.x.x.xxx): N/A (in msbuild)

dotnet.exe --version (if appropriate): 1.1.0

VS version (if appropriate): 15.3.2

OS version (i.e. win10 v1607 (14393.321)): Win 10

Worked before? If so, with which NuGet version: First time trying

## Detailed repro steps so we can see the same problem

1. Create a .Net Core C# library.
 
2. Edit the csproj and set this: `<Project Sdk="Microsoft.NET.Sdk.Web">`
WHY? Because this allows compiling (to catch errors) and embedding cshtml files while also creating a library file, and it works great.

3. \# 2 causes the project to reload.  Open project settings and set Output Type to "Class Library".

4. Enable "Generate NuGet package on build" in the project settings under "Package".

5. Create default tsconfig.json. I had something like:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ],
  "compileOnSave": true
}
```

6. Create a .ts file.

7. Enter "var n = 1;" in the .ts file so it has content. On save it should compile (make sure).

8. Build, and observe the .json files included in `obj\{YOUR LIBRARY}.nuspec`.

9. Add this to csproj:
```
  <ItemGroup>
    <Content Remove="**\*.*" />
  </ItemGroup>
```

10. Build again. Observe that .js and .js.map files included, but all other content removed.

## Output Issue Example

 ```
   <contentFiles>
      <files include="any/netcoreapp1.1/file.js" buildAction="Content" />
      <files include="any/netcoreapp1.1/file.js.map" buildAction="Content" />
    </contentFiles>
  </metadata>
  <files>
    <file src="e:\users\james\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\netcoreapp1.1\ClassLibrary1.dll" target="lib\netcoreapp1.1\ClassLibrary1.dll" />
    <file src="e:\users\james\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\file.js" target="content\file.js" />
    <file src="e:\users\james\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\file.js" target="contentFiles\any\netcoreapp1.1\file.js" />
    <file src="e:\users\james\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\file.js.map" target="content\file.js.map" />
    <file src="e:\users\james\documents\visual studio 2017\Projects\ClassLibrary1\ClassLibrary1\file.js.map" target="contentFiles\any\netcoreapp1.1\file.js.map" />
  </files>

```

## Other suggested things

I think that the TypeScript compiler is updating the files and causing msbuild Nuget integration to pick them up, since the build action is `buildAction="Content"`, when in fact the content should be removed.

### Verbose Logs

I don't know how to do this, but the project is easy to create, so you can easily do this yourself when checking it out.

### Other Comments

This is the issue I am having with another very large project of mine.  This has been working perfectly for months, since the web project and libraries were in the same solution, and it compiled and ran the ASP.Net Core MVC project perfectly.  I decided to separate the libraries into a separate solution and have packages created for Nuget, but these content files are getting in my way, and also causing build errors when including the packages in other projects.  The only work-around is to open the package in the NuGet Package Explorer and remove them manually, but it is easy to forget and very annoying to have to do this on EVERY build.

**Comment by jainaashish** [comment]
@rohit21agrawal can you take a look at it? Thanks!

**Comment by rohit21agrawal** [comment]
can you  try setting ```<IncludeContentInPack>false</IncludeContentInPack>``` in your project?

**Comment by rjamesnw** [comment]
That worked!!! Thanks. ;) I assume though this is just a work-around, since one day I might need to add content and this will be a problem again. For now, it solves my problem.

**Comment by rohit21agrawal** [comment]
is it possible for you to just attach a repro project? it will make it much easier to investigate

**Comment by rjamesnw** [comment]
[ClassLibrary1.zip](https://github.com/NuGet/Home/files/1250705/ClassLibrary1.zip)

After build, open the obj\ClassLibrary1.1.0.0.nuspec file see what I mean - but I'm guessing you know that already lol. ;)

**Comment by rohit21agrawal** [comment]
This issue was moved to aspnet/Home#2166
