### ISSUE TITLE
Cannot add items to TargetsForTfmSpecificBuildOutput unless the extensions are in whitelist and there is no way to customize the extension whitelist

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#5810]
[log.zip](https://github.com/NuGet/Home/files/1254659/log.zip)
Using the `TargetsForTfmSpecificBuildOutput` extension point, I'm unable to add all the required files:

![image](https://user-images.githubusercontent.com/1427284/29753278-eb20577e-8b3b-11e7-9357-54809cb485ae.png)

You can see that they are passed into the PackTask, but the generated NuSpec drops a few:
![image](https://user-images.githubusercontent.com/1427284/29753281-100f7dd0-8b3c-11e7-92ea-40ee5fc73d7c.png)

I've attached the binlog from the Structured Log tool, so you can see the whole thing: https://github.com/KirillOsenkov/MSBuildStructuredLog

As a workaround, I can use `TargetsForTfmSpecificContentInPackage` with something like this:

``` xml
  <Target Name="IncludeLibraryLayoutItems" DependsOnTargets="PrepareLibraryLayout">

    <ItemGroup>
      <TfmSpecificPackageFile Include="@(_LayoutFile)" PackagePath="lib\$(TargetFramework)\%(_LayoutFile.TargetPath)" />
    </ItemGroup>
  </Target>
```

**Comment by rohit21agrawal** [comment]
@onovotny this is not a bug because that target still filters files based on extensions.
If you need to add file extensions which are not whitelisted, you need ```TargetsForTfmSpecificContentInPackage``` like you did as a workaround.

**Comment by clairernovotny** [comment]
That still feels wrong, IMO. If I add custom items per TFM, then you should not be filtering those on a white list.

**Comment by rohit21agrawal** [comment]
I do have a separate PR which i am about to send out that allows you to customise what extensions go into the whitelist, perhaps that would be sufficient to fill this gap?

**Comment by clairernovotny** [comment]
I guess that'll help, but that now means two customizations are needed. It seems that whitelist should be inferred or at least include whatever is in the TargetsForTfmSpecificBuildOutput
