### ISSUE TITLE
`nuget list` hangs in case of redirect Console output to file

### ISSUE THREAD

**Issue by sbespalov** [NuGet/Home#5811]
## Details about Problem

My goal is to capture `nuget list` command output to check the result within my Integration Tests.
I am trying to redirect console output into file using command below:
`$ mono --runtime=v4.0 nuget_2-8-6.exe list Org.Carlspring -ConfigFile NuGet.config > list-stdout.txt 2> list-stderr.txt`

When I am doing so the command execution hangs forever and never ends. When I am using the same command without Console output redirect everything works fine and it shows the list of packages found.

### NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
`NuGet.exe`

###  NuGet version (x.x.x.xxx):
`NuGet Version: 2.8.60717.93`

### dotnet.exe --version (if appropriate):
I am using `mono`
`Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:10:37 UTC 2016)`

### OS version (i.e. win10 v1607 (14393.321)):
`Ubuntu 16.04.1 LTS`

### Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

`list-stdout.txt` contents below:

```
Using credentials from config. UserName: admin
GET http://localhost:48080/storages/nuget-common-storage/nuget-releases/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='Org.Carlspring'&targetFramework=''
GET https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='Org.Carlspring'&targetFramework=''&includePrerelease=false


```

`list-err.txt` is empty

**Comment by sbespalov** [comment]
Hi guys, 
we will be very happy if you can provide solution or workaround for this issue.

**Comment by emgarten** [comment]
@sbespalov 2.8.6 is very old, try the latest 4.3.0 version here: https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

**Comment by sbespalov** [comment]
@emgarten thank you for quick response
I know that `2.8.6` is not the last version, and `nuget list` works fine for `v4.x`, but I need to use `v2.x` in my Integration Test script. 
The goal is to test how our package manager works with `Nuget v2` protocol version.
Maybe you can provide some workaround for `v2.x`, if it's not supported any more?

**Comment by emgarten** [comment]
> The goal is to test how our package manager works with Nuget v2 protocol version.
Maybe you can provide some workaround for v2.x, if it's not supported any more?

I'm not sure I understand. The 2.x server protocol is supported in nuget.exe 3.x and 4.x. Are you seeing a scenario where it doesn't?

**Comment by sbespalov** [comment]
Yes, seems that `nuget.exe` client have a backward protocol compatibility. But how I can be sure that I am using server protocol v2, when the client version is 4.x?

**Comment by sbespalov** [comment]
Also, How I can be sure that our protocol v2 server will work for `nuget.exe` v2 clients if our Integration tests using `nuget.exe` client v4? :)

**Comment by emgarten** [comment]
To test your own server implementation using old clients makes sense. :smile:

I'm not sure of the workaround for this, this is the first time I've seen this problem reported. You could try using nuget.exe as an assembly reference and calling into the same code, or running a modified version of nuget.exe where you've fixed the issue.

**Comment by sbespalov** [comment]
the problem is that I am not common with `.Net`, that's why I have asked for your help here. I can't fix this Issue by myself.

**Comment by anangaur** [comment]
We do not have any servicing train to fix issues in older versions of NuGet clients 2.x as of today. I would suggest you should explore ways  to move to 4.x clients as they are kept up to date with bug fixes and new functionalities.

**Comment by sbespalov** [comment]
Can I strictly specify the server protocol version to use for v4 client?

**Comment by emgarten** [comment]
If the server is v2 protocol then the client has to use v2 OData. If the server is v3 json protocol then it uses that. 

Note that there have been a lot of changes to how nuget reads v2 feeds in 3.x and 4.x, so it could potentially be different.

You can see how common usage of different nuget client versions are here: https://www.nuget.org/stats/packages/Newtonsoft.Json?groupby=ClientName&groupby=ClientVersion

**Comment by sbespalov** [comment]
@emgarten thank you for explanation. But I want to understand how `nuget.exe` client knows what protocol version to expect from server?

**Comment by emgarten** [comment]
If it is a json file it is v3, if it is OData XML it is v2.

**Comment by sbespalov** [comment]
you mean that it's determined according to the 'Content-Type' HTTP response header?

**Comment by rrelyea** [comment]
If the URI of the source ends with ".json" the code base currently treats the source as a v3 source.
