### ISSUE TITLE
Version 4.3.0 changes facade deployment

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#5819]
I'm in the process of migrating the Roslyn repo from the 1.1 to 2.0 SDK. As a part of that I also moved NuGet.exe from 4.1.0 to 4.3.0. Doing so broke 90% of our tests because NuGet changed the set of facades that were deployed for our unit test projects. In particular it changed how the facade for System.Security.Cryptography.Algorithms is deployed. 

The unit tests which broke all had net461 as a target framework. Some of them are multi-targeted to netcoreapp2.0 as well but this problem occurs when building the net461 target. Prior to this change it caused the net461 facade for System.Security.Cryptography.Algorithms to be deployed to our test directory. This is important because net461 uses assembly version 4.1.0.0. DLLs lower in our build chain target net46 and hence have a reference to the assembly at version 4.0.0.0. This is reconciled with a binding redirect from 4.0.0.0 -> 4.1.0.0 in our test app.config files. 

However NuGet 4.3.0 broke our logic here. It no longer deploys System.Security.Cryptography.Algorithms to our output directory. That means the facade is missing, our binding redirect logic is broken and that breaks our unit tests.

What changed here between the versions? While I can fix this specific problem by adjusting binding redirects it is a break from NuGet 4.1.0. It could conceivably hit other parts of our infrastructure (NuGet packaging for example where we often have to reference facades). It seems like a decent break here to no longer deploy this facade.  Is this a known issue? 

In order to repro this problem you'll need to use the branch `sdk2` on my fork of Roslyn. Probably another couple days until this gets merged to our master branch:

> https://github.com/jaredpar/roslyn/tree/sdk2

I shared out the files internally to make the investigation easier. Curious readers can reproduce them by running NuGet.exe restore on `src\Compilers\CSharp\Test\Semantic\CSharpCompilerSemanticTest.csproj`.

- 4.1.0: `\\mlangfs1\public\jaredpar\issues\nuget-change\old\project.assets.json`
- 4.3.0: `\\mlangfs1\public\jaredpar\issues\nuget-change\new\project.assets.json`

**Comment by jaredpar** [comment]
After further investigation this is turning into a really bad break for us. There is seemingly no way out of this problem:

- The transitive closure of assemblies does not appear to use System.Security.Cryptography.Algorithms 4.1.0.0 assembly. I've hand scanned every output DLL and all are using 4.0.0.0. Possible I'm missing something but don't see it. 
- Automatically generating binding redirects includes a redirect from 4.0.0.0 to 4.1.0.0

It appears binding redirect generation and deployment are in disagreement here. This pretty much blocks progress for us as our redirects are busted and tests aren't runnable.

**Comment by rohit21agrawal** [comment]
@ericstj @natidea  this is probably something NuGet.BuildTasks does rather than what NuGet does
@emgarten thoughts?

**Comment by ericstj** [comment]
> However NuGet 4.3.0 broke our logic here. It no longer deploys System.Security.Cryptography.Algorithms to our output directory.

@jaredpar I believe this is actually caused by this: https://github.com/dotnet/sdk/issues/1510
