### ISSUE TITLE
Visual Studio package manager does not handle `ItemGroup Condition` very well

### ISSUE THREAD

**Issue by mqudsi** [NuGet/Home#5823]
_Running Visual Studio 2017.3 Preview 7.1_

Visual Studio's package manager has a hard time dealing with conditional dependencies. I'm not sure this is always reproducible as I believe some internal state values also come into play, but with a `.csproj` for a multi-targeted project similar to what follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net20;net30;net35;net40;net45;netstandard1.3</TargetFrameworks>
    <!--omitted-->
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net20'">
    <PackageReference Include="LinqBridge">
      <Version>1.3.0</Version>
    </PackageReference>
    <PackageReference Include="Stream.CopyTo">
      <Version>1.0.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
      <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation">
          <Version>1.1.2</Version>
      </PackageReference>
      <PackageReference Include="System.Security.Cryptography.Primitives">
        <Version>4.3.0</Version>
      </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>

</Project>
```

Attempting to uninstall a conditional dependency such as `System.Security.Cryptography.Primitives` (even though it was installed and automatically placed in the pre-existing conditional dependency `ItemGroup` for `netstandard1.3`) results in an error about the package not being found in the project nuget dependencies file.

**Comment by emgarten** [comment]
This issue is tracked here along with a possible workaround: https://github.com/dotnet/project-system/issues/1542

**Comment by rrelyea** [comment]
Keeping open, but tracking as external issue. Thanks @emgarten
