### ISSUE TITLE
Correctly create 'copyToOutput' .nuspec from .csproj

### ISSUE THREAD

**Issue by mamaso** [NuGet/Home#5825]
I'm trying to use the new .csproj format to generate a .nuspec which copies files to output directory for dependent projects, something like.:
```
<contentFiles>
  <files include="any/any/someContent.txt" buildAction="None" copyToOutput="true" flatten="false"/>
</contentFiles>
```

However, I can't seem to get a .csproj which does this correctly. The following .csproj does not generate any <contentFiles> element in the .nuspec.
```
  <ItemGroup>
    <None Include="context.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```

In contrast, using Content generates contentFiles, but does not copyToOutput in dependent projects.
```
  <ItemGroup>
    <Content Include="context.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

// generated nuspec
<contentFiles>
      <files include="any/netstandard2.0/context.txt" buildAction="Content" />
</contentFiles>
```

Is the best option to create the nuspec manually?

**Comment by dasMulli** [comment]
https://github.com/NuGet/NuGet.Client/pull/1450 introduced specifying metadata `PackageCopyToOutput="true"` on content elements.

**Comment by mamaso** [comment]
thanks @dasMulli!
