### ISSUE TITLE
Ability to dogfood nupkg via PackageReference

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5826]
_From @am11 on August 22, 2017 17:51_

In addition to #1151 (swapping package reference with sources when available available), would be cool if we can also easily dogfood our `.nupkg` produced by `dotnet pack` which can be used in the integration / packaging tests, for instance.

```xml
  <!-- packaging test project -->
  <ItemGroup>
    <PackageReference Include="$(SolutionDir)/bin/$(Configuration)/MyLib.1.0.0.nupkg" />
  </ItemGroup>
```

Here `PackageReference` task will first figure out if `Include` value is a local path then don't hit the server, then if it's nupkg or nuspec file, run install package task on it.

_Copied from original issue: dotnet/sdk#1525_

**Comment by rrelyea** [comment]
@am11 `<RestoreAdditionalProjectSources>$(SolutionDir)/bin/$(Configuration)/</RestoreAdditionalProjectSources>`
should provide the same capability for you today. We don't plan on doing the DCR you are asking for, so please try.

**Comment by am11** [comment]
@rrelyea, thanks for sharing the solution, I will give it a try.
Perhaps a rookie question, but what does DCR stand for? :)
