### ISSUE TITLE
Duplicate NU1701 warnings when multi-targetting to netcoreapp2.0 and net461

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#5829]
_From @anangaur on August 4, 2017 18:24_

1. Create a new NetCore 2.0 Console App
2. Multi-target to netcoreapp2.0;net461:
`   <TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>`
3. Add a NuGet reference to a net 461 compat package like RestSharp
**Expected**: One NU1701 warning for .NET Core 2.0 target platform
**Actual**: Two warnings but both for the same .NET Core 2.0 target platform:
![image](https://user-images.githubusercontent.com/14800916/28981661-8089a76c-7907-11e7-9978-6d94c48aee3a.png)

_Copied from original issue: dotnet/sdk#1474_

**Comment by rohit21agrawal** [comment]
@mishra14  would you take a look here? pretty easily repro-able

**Comment by mishra14** [comment]
This seems like an issue in the sdk target that reads the warnings from assets file because the nuget generated assets file contains only 1 warning - 

![capture](https://user-images.githubusercontent.com/10507120/29939860-392a29e6-8e42-11e7-9a76-915076d557be.PNG)

**Comment by mishra14** [comment]
I have commented on the sdk issue to re open it.

**Comment by nguerrera** [comment]
Reopened sdk issue

**Comment by mishra14** [comment]
Thanks @nguerrera. I am closing this issue.
