### ISSUE TITLE
Feature Request: Project wildcard in CLI Pack command.

### ISSUE THREAD

**Issue by alexdrl** [NuGet/Home#5830]
Is there any chance to get project wildcard like in 'nuget push' command, but in the 'nuget pack' command?. We updated to TFS 2017 Update 2, and Nuget Packager Build Task got deprecated, so we need to use the CLI. Using the CLI we discovered that with the pack action, we need to specifiy one project.

We also discovered that 'dotnet pack' already supports it, but dotnet CLI does not work with pre-MSBuild 15 projects.

Thank you for the good work.

**Comment by rohit21agrawal** [comment]
@alexdrl could you please elaborate on your scenario with an example ? i am not sure i understand completely what you are trying.

**Comment by alexdrl** [comment]
@rohit21agrawal what we want to do is something like 'nuget.exe pack **\*.csproj'

**Comment by rohit21agrawal** [comment]
oh, i see what you are saying. nuget.exe doesn't support it out of the box, but you can easily leverage the power of msbuild to enable a scenario like that. let me know if  you need help writing a target to do the same.

**Comment by alexdrl** [comment]
@rohit21agrawal the problem is that we don't have the 'Pack' target in the .Net Desktop packages so the build fails. I know it's a complex scenario, but I expect pack to work like push.

**Comment by rrelyea** [comment]
Sorry, this doesn't rank high enough in our backlog to keep it open. Thanks for your suggestion though. We'll keep our ears open for similar feedback.
