### ISSUE TITLE
nuget spec doesn't detect csproj dependencies

### ISSUE THREAD

**Issue by hoagsie** [NuGet/Home#5833]
When I run `nuget spec` on a directory containing a csproj, I don't get any dependencies generated in the nuspec for either project or package references regardless of whether they are in a packages.config or a package reference.

I'm using 4.3.0 of the CLI.

**Comment by rohit21agrawal** [comment]
@hoagsie nuget spec only look at metadata (either from assembly or csproj) and isn't supposed to fill up dependencies ( project refs or package refs) . What is the scenario you are trying to do exactly?

**Comment by hoagsie** [comment]
I have a project with 5 nuget packages that I want to pack. When I used `nuget spec project.csproj`, none of those packages were added to the nuspec as dependencies. From the description of the spec command [here](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-visual-studio-project), I would expect it to do that. I had to do this part myself.

**Comment by rohit21agrawal** [comment]
oh i see. my bad. would you be able to attach a repro project for us to investigate?

**Comment by hoagsie** [comment]
[NuspecSample.zip](https://github.com/NuGet/Home/files/1268500/NuspecSample.zip)

The nuspec in there was generated with a `nuget spec` using the 4.3 CLI. However, as you can see in the following, I do, in fact, have some nuget references.

![nuspec references](https://user-images.githubusercontent.com/20057078/29945210-4792f6ee-8e6e-11e7-83dd-f8f745652130.PNG)

Updated with new zip. Old one had a csproj that wasn't committed to disk.

**Comment by hoagsie** [comment]
A small update. I just converted a project from using package references in the csproj to the traditional packages.config and reran `nuget spec -force` and dependencies still didn't get generated in the resulting nuspec. This aspect of `spec` seems completely busted.

To give some context as to why this is important to me at the moment, I'm having some issues with binding redirects in some in-house packages and I'm trying to get my custom stuff out of the way as much as possible to help diagnose the problem. I was really hoping `nuget spec` would reveal some small error in my version declarations (or something else) that would fix the problem downstream.

**Comment by rrelyea** [comment]
We recommend you look at Packages.config file or for PackageReference (look at Project.assets.json file) to understand dependencies.
