### ISSUE TITLE
Visual Studio 15.3.3 displaying incorrect version on "Installed" tab

### ISSUE THREAD

**Issue by chiefengineer** [NuGet/Home#5834]
## Details about Problem
Visual Studio NuGet package manager UI is showing an incorrect package version for installed packages.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
- not sure how to tell this, it's what comes with VS 2017 15.3.3 (latest version). The nuget.exe program has independently been upgraded to version 4.1.0.2450.

dotnet.exe --version (if appropriate):
N/A

VS version (if appropriate):
15.3.3

OS version (i.e. win10 v1607 (14393.321)):
Win10 v1703

Worked before? If so, with which NuGet version:
Not sure, didn't pay that much attention, sorry.

## Detailed repro steps so we can see the same problem
1. Create a new solution.
2. Create a project for said solution, use the 1.0.1.1 versioning scheme.
3. Create the package and upload it to a local nuget server (created using ASP.NET MVC and nuget.server).
4. Create a second solution.
5. Create a project for the second solution.
6. Install the newly created nuget package into the section solution.
7. Go back to the first solution.
8. Update the project in some meaningful fashion.
9. Change the version number such that it reflects 1.0.1.2 or some such.
10. Upload the new package to the same nuget server.
11. Back to the second solution.
12. Open the nuget package manager for "Manage packages for solution". 
13. There should be 1 update available, version 1.0.1.2.
14. Flip to the "Installed" page, observe the version number of the INSTALLED package - it will show 1.0.1.2 in the version column, yet if one selects the package, one may observe that the actual version number is displayed correctly in the install/uninstall box.

This may be the intended behavior but allow me to say that it's very confusing to me as I expected the version column to show what is installed on the "Installed" page, not what could be upgraded to. It is my opinion that I should not have to select each package to see what the actual installed version is on the "Installed" page.

The only time that the "Installed" tab shows the correct information about a package is when there is
no upgrade to be applied, then the current version that is actually installed is displayed in the version column (and by version "column", I mean the displayed version to the right of each entry in the list of installed packages).

Screen shots follow.
![beforelibraryupdate - notice version 8 2 0 9](https://user-images.githubusercontent.com/3935857/29933900-180f2680-8e2e-11e7-975b-8dcd02d31ed0.png)
![updated screen selected - notice the update to the same version](https://user-images.githubusercontent.com/3935857/29933899-1809c4ba-8e2e-11e7-99f5-6a888aff517a.png)

**Comment by rohit21agrawal** [comment]
@PatoBeltran would you take a look at this as you are already working on something related?

**Comment by chiefengineer** [comment]
uh, sorry, but take a look at what, exactly? All I see is the request to
"take a look..."


"Bang the Button - It Just Works!"

**Comment by PatoBeltran** [comment]
@chiefengineer Thank you for your feedback and repro steps, we are aware and looking for the best way to resolve the inconsistencies in our UI. We will update you when we have a proposal for a fix.

**Comment by nkolev92** [comment]
Thanks for this issue. 

At this point we have decided not to fix this issue, as we are trying to fix other higher impact bugs and deliver new features.
If there are more community feedback on this, then we'll re-evaluate this.
