### ISSUE TITLE
pack does nothing if you delete the previous output from disk

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5836]
[ClassLibrary46.zip](https://github.com/NuGet/Home/files/1268533/ClassLibrary46.zip)

Right click on the project in solution explorer, and click "Pack" - the nuget package is produced in the output folder (I.e bin/debug). Now open windows explorer and delete the nuget package file. Right click on the project in solution explorer and click "pack" again. Nothing happens. No errors or warnings. No nuget package is produced.

**Comment by nkolev92** [comment]
This doesn't repro anymore. 

Closing
