### ISSUE TITLE
Copy concrete files

### ISSUE THREAD

**Issue by cdibbs** [NuGet/Home#5839]
With the latest NuGet 4.3, I have not been able to get CI-related files copied as concrete files to a .NET Core project folder. I've gotten as far as virtual links to the files within the nupkg via the contentFiles metadata tag. Is it still possible to create real files without an init.ps1 in NuGet?

I've been scouring the issues here trying to determine whether this is possible, but have been unable. Perhaps my hopes have blinded me. :-) If this feature has been set aside, I'd like to recommend re-adding it in a future release. Even just a "createReal='true'" attribute on the files tags within contentFiles. For my particular use-case, the files don't even need to be visible within Visual Studio, nor added to the .csproj file. Thanks!

**Comment by emgarten** [comment]
You can run these actions from a .targets file in the build folder of a package.

Currently content in the project folder is not supported since the set of package versions/files copied is not tracked, which means when the version changes NuGet is unable to uninstall the old files.

**Comment by rohit21agrawal** [comment]
@cdibbs contentFiles has a copyToOutput attribute that you can set to true to control this behavior, does that not meet your needs? or perhaps i am misunderstanding your scenario here? could you elaborate with an example?

**Comment by cdibbs** [comment]
@emgarten and @rohit21agrawal - Thanks for your quick replies! Without altering our existing CI/NuGet processes, I would need the nupkg to install files that will be visible to processes outside Visual Studio (and MSBuild) prior to building the project. Both `copyToOutput` and .targets files only create real files in the filesystem after the project is built.

However, I sympathize with the desire to avoid installing untracked files. I'll try to rework our CI processes not to need such a thing.

Thanks for your help. Hope the weekend was long and relaxing! :-)
