### ISSUE TITLE
NRE during package restore

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#584]
1. Install a package into a .NET 4.5 project
1. Close solution
1. Delete packages folder
1. Open solution
1. Restore packages
1. NullReferenceException is logged

NuGetPackageManager.GetDependencyInfoFromPackagesFolder returns a list that can contain nulls for packages that are not installed, so when it is processed in NuGetPackageManager.GetInstalledPackagesInDependencyOrder NRE is thrown from the .Select call

UninstallResolver.GetPackageDependents also consumes this list and has the same problem.

**Comment by yishaigalatzer** [comment]
This is a great bug!

The fix should be that for restore we probably don't need to make the `NuGetPackageManager.GetInstalledPackagesInDependencyOrder`

For uninstall, update, and possibly install we need to detect this, and trigger a restore. If restore succeeds we proceed, if it fails we fail the operation.

If this needs a new strings they need to get in ASAP before string lock.

CC @emgarten @deepakaravindr @feiling
