### ISSUE TITLE
Unable to load DLL 'e_sqlite3' on EF Core 2.0

### ISSUE THREAD

**Issue by bdominguez** [NuGet/Home#5841]
Referenced from EF Core repo:

aspnet/EntityFrameworkCore#9505

@bricelam said that it looks like an issue with transitive packages in project references in NuGet.

**Comment by bricelam** [comment]
Something about the project structure is preventing the native assets from making it into the output directory. Adding a more direct reference to the package makes it work.

**Comment by emgarten** [comment]
Build targets and props files from packages do not flow transitively to parent projects. As @bricelam mentioned here and the original issue, adding a direct reference to the package is the correct way to bring these targets in.

`PrivateAssets=None` will also help flow these targets up to the next level.
