### ISSUE TITLE
Adding additional nuget sources through the property RestoreAdditionalProjectSources in a target are not picked up by Restore in Visual Studio

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#5842]
_From @atanasa on September 1, 2017 11:9_

I am using a target to register additional nuget package source like this:
```
  <Target Name="RegisterCustomPackageSource"
          BeforeTargets="_GetRestoreSettingsPerFramework">
	...
    <PropertyGroup>
      <RestoreAdditionalProjectSources>....</RestoreAdditionalProjectSources>
    </PropertyGroup>
  </Target>
```

When I run Restore from the command line, it works. When I do a Restore in Visual Studio it does not work. The sources listed in the log of the operation in Visual Studio does not include the additional source.

Is there any particular reason why the project system calls into the Restore operation through code rather than through MSBuild (as the cli restore does)?

_Copied from original issue: dotnet/project-system#2780_

**Comment by davkean** [comment]
Restore in VS is much harder than via the command-line, as you need to play nicely with UI and unsaved projects, hence why we don't "restore" via MSBuild.

This looks like a NuGet bug, this should be a dependency of CollectPackageReferences.

**Comment by emgarten** [comment]
`CollectPackageReferences` is a supported extension point that should work here.

NuGet receives these property values from the project system, if this isn't working in VS is sounds like this isn't being picked up there.

This should be tracked here: https://github.com/dotnet/project-system/issues/2780
