### ISSUE TITLE
Inconsistent text between VS ouptut and Tools -> Option

### ISSUE THREAD

**Issue by unniravindranathan-okta** [NuGet/Home#5844]
Customer Repro:
1. Install VS217 Community.
2. Create any project that has a NuGet reference (UWP, .NET Standard, etc.)
3. Once your shared library is referenced by each project, right-click
the UWP project, and select "Build"

RESULT: Output window has following text:
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual
Studio Options dialog, click on the Package Manager node and...

RESULT: Options dialog has a "NuGet Package Manager" node, not a
"Package Manager" node.

EXPECTED: Text matches Option dialog node text.

I would recommend updating the build output text.

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
