### ISSUE TITLE
Feature request: Support more filters for src attribute in <file> element (nuspec)

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#5846]
In nuspec `<files>` / `<file>` element has `src` attribute where two kinds of wildcards are supported: `*` and `**`:

> The location of the file or files to include, subject to exclusions specified by the exclude attribute. The path is relative to the .nuspec file unless an absolute path is specified. The wildcard character * is allowed, and the double wildcard ** implies a recursive folder search.

Reference: https://docs.microsoft.com/en-us/nuget/schema/nuspec#including-assembly-files

# Problem
For target `lib` actually we need limited set of files to include - *.dll, *.pdb, *xml. 
But using wildcard `*` and `**` like:
```
    <file src="bin\$configuration$\**" target="lib" />
```
can easily include other files like `*.deps.json` or `*.dll.config`.

# Suggestion
It'd be nice to be able to specify a list of extensions:

    <file src="bin\$configuration$\**\*.[xml|dll|pdb]" target="lib" />

or

    <file src="bin\$configuration$\**\*.(xml|dll|pdb)" target="lib" />

**Comment by emgarten** [comment]
You can control which files are included/excluded by packing with msbuild. 

See: https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#pack-target

**Comment by nkolev92** [comment]
Thanks for reporting this issue. 

We have decided not to fix this issue as there is an easy workaround. 
```
<file src="bin\$configuration$\**\*.xml" target="lib" />
<file src="bin\$configuration$\**\*.dll" target="lib" />
```
