### ISSUE TITLE
Packages.config should be modified instead of rewritten each time

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#585]
packages.config is re-written each time and drops attributes that it does not understand. This could cause problems if we add attributes in the future. Instead the file should be modified and ignore what it does not understand.

**Comment by yishaigalatzer** [comment]
We can just load it as an `XmlDoc` or `XDocument` and apply changes to that entity.

**Comment by danliu** [comment]
PRs for this bug are here:

https://github.com/NuGet/NuGet3/pull/95
https://github.com/NuGet/NuGet.PackageManagement/pull/50
https://github.com/NuGet/NuGet.VisualStudioExtension/pull/52

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@ab760f954410d6da54c4faf473c6537b0856f71e
