### ISSUE TITLE
Feature Request: NuGet.exe pack should drop resolved nuspec to support network share hosted Package Source

### ISSUE THREAD

**Issue by nschwerzler** [NuGet/Home#5850]
## Details about Problem

Feature request (not a bug).

NuGet product used NuGet.exe

NuGet version: 4.3.0.3

dotnet.exe --version (if appropriate):

VS version (if appropriate): Visual Studio 2017

OS version (i.e. win10 v1607 (14393.321)): Windows 10

Worked before? If so, with which NuGet version: Not applicable, New feature request

## Detailed repro steps so we can see the same problem

**Background:** Need to host nuget packages on an private internal network share. For fast indexing and low bandwidth consumption, the article [Accelerate your network share hosted Package Source](https://blog.nuget.org/20150922/Accelerate-Package-Source.html) solves a important problem for my team.

**Issue**: The resolved nuspec file needs to be side by side with the nupkg according to the above documentation. We have many [properties,variables,tokens that need to be resolved and replaced](https://docs.microsoft.com/en-us/nuget/schema/nuspec). Pulling the nuspec out of the zip file would substantially increase our processing time for the volume of nupkgs we plan on creating. We also need the sha512 file.

So something like this in the output directory:
yourpackage.0.0.1-beta.nupkg (current behavior)
yourpackage.nuspec (new)
yourpackage.0.0.1-beta.nupkg.sha512 (new)

## Other suggested things
Would like a switch in the nuget.exe pack command that drops the resolved nuspec file next to the nupkg, an exact mirror of what already exists in the nupkg but have the same name as the nupkg with a nuspec extension to follow the guidelines in [Accelerate your network share hosted Package Source](https://blog.nuget.org/20150922/Accelerate-Package-Source.html).

### Verbose Logs

Not applicable

### Sample Project

Not applicable

**Comment by emgarten** [comment]
Just to clarify and provide some background on this, this can be done today by calling pack and then `nuget.exe add`.  The request here is to do all of these actions at once to improve performance, correct?

**Comment by nschwerzler** [comment]
"The request here is to do all of these actions at once to improve performance, correct?"
Yes, we have a large volumn of nuget packages and need pack command to do everything to prepare the files for the share feed.
