### ISSUE TITLE
Ability to expire a pre-release package

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5856]
Many times authors release beta packages for testing waters but they do not want users to continue working with these packages.

There should be a mechanism to put an expiry date on the beta packages after which NuGet restores should start warning users.

**Comment by xavierdecoster** [comment]
Could this be part of the Package Deprecation spec? We have an issue tracking that feature: https://github.com/NuGet/Home/issues/2867

**Comment by anangaur** [comment]
https://github.com/NuGet/Home/issues/2867 looks similar. However, https://github.com/NuGet/Home/issues/2867 lets you deprecate a package at any point in time. This proposal is to have a time-bomb attached with the nupkg so that even the cached version would have the expiry and NuGet CLIs can warn once it expires.

**Comment by maartenba** [comment]
Who knows, maybe I want to auto-update my v2 version when I publish v3 next Tuesday. (Or: perhaps they are indeed the same feature, with an enhanced scope in the current issue?)

**Comment by nkolev92** [comment]
This seems like a high-cost low benefit thing tbh. Worth having a triage discussion over.

**Comment by anangaur** [comment]
Closing this as duplicate of https://github.com/NuGet/Home/issues/2867
