### ISSUE TITLE
Update NU log code docs

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5857]
The NU log code doc should be updated for 4.4

* NU1607 has moved to NU1107
* NU1606 has moved to NU1108
* NU1608 has been added

https://github.com/NuGet/Home/wiki/Restore-errors-and-warnings/_compare/a2fe6b4f2f97ef5929b17a3c7dbddc44449114b3...ecc7b4cd554f633c5f9c288e9ff594b7eb78ea37

**Comment by anangaur** [comment]
Moved to https://github.com/NuGet/docs.microsoft.com-nuget/issues/447
