### ISSUE TITLE
Multiframework Nuget package installation failed for.Netcore Applictaion 

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5860]
Please help me on this.

**Comment by emgarten** [comment]
@AnithaL try restoring using the latest nuget.exe 4.3.0 from here: https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

If that doesn't work please share the project and list of files in `SPGMI.RdKafka`

**Comment by AnithaL** [comment]
Still I was not able to install Nuget package of Netstandarad1.6 version to .neycore1.0 application.

Can we install nuget pacakage of Netstandard1.6 to Netstandard1.0?project please help.

**Comment by emgarten** [comment]
`netcoreapp1.0` supports `netstandard1.6`

@AnithaL try deleting your obj folder, specially project.assets.json and running restore again.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. 

As we have not received response in some time, we are closing this issue. 

If you can still reproduce this with the latest version of NuGet please, please reach out to us again.
