### ISSUE TITLE
Use IPackageReferencesService to get package references from net core project system

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#5865]
Original issue was: test were not being discovered in Test window on solution load for net core projects. And that's because Test window team called into NuGet IVS api to retrieve package references for the project, even before project was nominated to NuGet so NuGet didn't had any information.

The current proposal from SDK team is to use [IPackageReferencesService](http://index/?query=IPackageReference&rightProject=Microsoft.VisualStudio.ProjectSystem&file=References%5CIPackageReferencesService.cs&line=20) to get the list of package references for these projects without relying on nomination call.

**Comment by rrelyea** [comment]
Missed 4.4. Setting to backlog now.

**Comment by nkolev92** [comment]
This has been changed. 

We have a bunch of things that make this change not needed anymore. 

- Nomination protocol is now a 2-way conversation, where NuGet knows when nominations are in progress. 
- IVsNuGetProjectUpdate allows other components to wait for a restore to complete.
- Operation Progress APIs allow components to wait for the intellisense stage (DTB, restore, DTB) to complete.
