### ISSUE TITLE
Generate NuGet package on publish mode does not generate multiple target framework

### ISSUE THREAD

**Issue by deepumi** [NuGet/Home#5866]
**VS version** = Microsoft Visual Studio Community 2017 Version 15.3.2
**OS** = Windows 10
**Project type** = .NET Standard 2.0

I have created a .NET Standard 2.0 project which target multiple .net frameworks like netstandard2.0, net461 & net47 and the package works fine in debug mode and I am able to see multiple target framework does generate on package explorer like below.  However, when I publish the package on release mode I see only .NET Standard 2.0.  Could you please tell me what I am missing?

**DEBUG** 

![image](https://user-images.githubusercontent.com/554039/30236696-32d6a82e-94ed-11e7-9352-fee6d3c068d1.png)

**PUBLISH MODE**

![image](https://user-images.githubusercontent.com/554039/30236741-cbbedc54-94ee-11e7-86a7-9630162370c6.png)

![image](https://user-images.githubusercontent.com/554039/30236843-b6037570-94f1-11e7-9f16-98eecfa72d89.png)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461;net47;</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <!--<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>-->
  </PropertyGroup>
</Project>
```
```csharp
  public class Hello
  {
        public Hello(string name) {}
       
        #if NET461

        public Hello() {}
        
        #endif
  }
 ```

**Comment by emgarten** [comment]
@deepumi how are you changing between debug and release mode? Are you able to create a release package when building from the command line using msbuild directly?

**Comment by deepumi** [comment]
@emgarten I m publishing package via VS publish option.

![image](https://user-images.githubusercontent.com/554039/30240413-195100c4-953e-11e7-825c-9b85a55a244d.png)

**Comment by emgarten** [comment]
Try building normally under release. From your screen shot it looks like Publish is only publishing for a single target framework which is why the package contains only netstandard2.0.

**Comment by deepumi** [comment]
@emgarten Debug and Release always works, I only noticed publish does not work. 

Is in't that a glitch or is the default behavior?

**Comment by emgarten** [comment]
I would say this is expected. When using `GeneratePackageOnBuild` pack will add what was built to the nupkg. When running publish it only builds a subset of the project, there is no way for pack to get the rest.

If this were improved I would say that pack should skip generating the nupkg all together here, but I'm not sure if it is possible to detect this from within the pack target.

**Comment by rohit21agrawal** [comment]
you could work around it by removing GeneratePackageOnBuild from your csproj, and packing your project  using dotnet.exe after you have published all target frameworks.
