### ISSUE TITLE
VS 15.3 installs NetStandard dependencies for .Net framework project

### ISSUE THREAD

**Issue by plainionist** [NuGet/Home#5871]
## Details about Problem

NuGet product used: Package Manager Console
NuGet version:  4.3.1.4445
VS version (if appropriate): 15.3.x
OS version: windows 7
Worked before? If so, with which NuGet version: unknown. At least worked with VS 15.2 and most probably the nuget version shipped with it

## Detailed repro steps so we can see the same problem

1. Create a new F# console application for .net fw 4.6.x
2. open package manager console
3. "install-package suave -whatif"

Expected: Only suave package and its dependency to fsharp.core should be resolved - as documented on suave package as dependency in case of target framework being .net fw 4.6.x
(https://www.nuget.org/packages/Suave/2.2.1).

Instead nuget resolves all NetStandard dependencies also!
(and if I remove "-whatif" really all Netstandard dependencies get downloaded and installed)

I tried it with 2 fresh f# console projects with exactly the same effect.

workaround: specify "-ignore-dependencies" and install the dependencies manually :(

**Comment by emgarten** [comment]
NuGet selects the nearest compatible dependency group. For net46 the nearest group in suave is netstandard1.6. Ideally Suave should contain a group without the netstandard dependencies that specifically targets .NETFramework to avoid unneeded dependencies.

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Suave</id>
    <version>2.2.1</version>
    <title>Suave</title>
    <authors>Ademar Gonzalez, Henrik Feldt</authors>
    <owners>Ademar Gonzalez, Henrik Feldt</owners>
    <licenseUrl>https://github.com/SuaveIO/Suave/blob/master/COPYING</licenseUrl>
    <projectUrl>http://suave.io</projectUrl>
    <iconUrl>https://raw.githubusercontent.com/SuaveIO/resources/master/images/head_trans.png</iconUrl>
    <description>Suave is a simple web development F# library providing a lightweight web server and a set of combinators to manipulate route flow and task composition.</description>
    <releaseNotes>Release Notes:
* [infra] v2.2.1 fixes #641, related to #642
* [infra] update dotliquid dep</releaseNotes>
    <copyright>Ademar Gonzalez, Henrik Feldt</copyright>
    <language>en-GB</language>
    <dependencies>
      <group>
        <dependency id="FSharp.Core" version="4.0.0.1"></dependency>
      </group>
      <group targetFramework=".NETStandard1.6">
        <dependency id="NETStandard.Library" version="1.6.1" exclude="Build,Analyzers"></dependency>
        <dependency id="FSharp.Core" version="4.1.17" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Data.Common" version="4.1.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Diagnostics.Process" version="4.1.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Security.Cryptography.Primitives" version="4.3.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Net.Security" version="4.0.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Globalization.Extensions" version="4.3.0" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Security.Claims" version="4.0.1" exclude="Build,Analyzers"></dependency>
        <dependency id="System.Runtime.Serialization.Json" version="4.0.2" exclude="Build,Analyzers"></dependency>
      </group>
    </dependencies>
  </metadata>
</package>
```

**Comment by plainionist** [comment]
That sounds reasonable. Anyhow it worked with VS 15.2 - maybe in that version the group without explicitly mentioned targetFramework was selected?
How is this group handled now?
(just would like all the details so that I can address the topic at suave more easily)
thx!

**Comment by emgarten** [comment]
> Anyhow it worked with VS 15.2 - maybe in that version the group without explicitly mentioned targetFramework was selected?

The way NuGet selects the group hasn't changed. I believe there was a change to the compatibility rules to allow net461 to consume additional netstandard frameworks. This might be what you are seeing, which is really confusing and unfortunate!

**Comment by plainionist** [comment]
ok. I opened an issue at suave here: https://github.com/SuaveIO/suave/issues/650.

thx for the fast feedback and all the details - I think this issue can be closed
