### ISSUE TITLE
Support floating versions with IVsPackageInstallerServices.GetInstalledPackages

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#5872]
IVsPackageInstallerServices.GetInstalledPackages currently uses the minimum bound of the version range for the package. 

This should instead use the actual version in project.assets.json

There are several issues blocking this today
* Performance of loading up the assets file to get this info. Caching may be needed.
* When the API is called before auto restore has happened. Example: Test explorer is pinned and immediately requests installed packages from NuGet before NuGet has received the nomation from the project system to even start restore.

**Comment by rrelyea** [comment]
@emgarten  - can you put the customer impact here? Including details on how we learned about this, and why it would be important? This will help us prioritize.

**Comment by emgarten** [comment]
Test explorer does not recognize test projects that reference unit test packages with floating versions. An internal team ran into this issue.

**Comment by nkolev92** [comment]
Supported in NuGet.VisualStudio.Contracts https://www.nuget.org/packages/NuGet.VisualStudio.Contracts/, code at  https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Contracts/NuGetInstalledPackage.cs, fixed by @zivkan
