### ISSUE TITLE
build failed Nuget.resources not found.

### ISSUE THREAD

**Issue by scottbommarito** [NuGet/Home#5876]
@oliviergauthier commented on [Sat Sep 09 2017](https://github.com/NuGet/NuGetGallery/issues/4637)

I can't build NugetGallery. It throw the next exception :
 Impossible de charger le fichier ou l'assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\fr\NuGet.resources.dll'

it's seems related to this issue : https://github.com/NuGet/Home/issues/4780
I have updated Nuget with command :   .\.nuget\NuGet.exe update -self but when i launch build command again, it reset Nuget version to 4.0.0.2275

**Comment by zhili1208** [comment]
script in NuGetGallery always pull nuget.exe 4.0.0.2775, this is need to be fix in build script of NuGetGallery. Moved back to NuGetGallery
