### ISSUE TITLE
Move the MSBuild detecting logic to a library different than NuGet.Commandline

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5886]
The MSBuild Toolset detection logic currently resides in NuGet.Commandline.
We'd like to use this code in different scenarios, like tests etc and make it accessible to anyone. 

//cc
@emgarten @zhili1208

**Comment by Nirmal4G** [comment]
Can we merge the logic into [`MSBuildLocator`](/Microsoft/MSBuildLocator) project and use it here?

**Comment by nkolev92** [comment]
I think it's totally possible that MSBuildLocator has the same functionality that the logic in NuGet.exe does.

At this point, it's largely, don't change what's not broken.

**Comment by nkolev92** [comment]
Given that, I'm gonna go ahead and close this. Given the maturity of MSBuild locator, there's not much to win here.
