### ISSUE TITLE
VS NuGet writes absolute paths into project files under specific circumstances

### ISSUE THREAD

**Issue by forbjok** [NuGet/Home#5888]
## Details about Problem

Under very specific circumstances, Visual Studio's built-in NuGet client will write absolute paths into the project file in various places, such as target import paths and reference HintPaths.

I've narrowed down the exact criteria to reproduce this issue: Run Visual Studio on the solution with the current working directory set to the solution directory **with a lowercase drive letter**.
Yes, that's right. For some reason the drive letter being lowercase actually makes a difference.
The working directory **MUST be set to exactly the solution directory**, and **the drive letter in the path MUST be in lowercase**.

Unfortunately, double-clicking a solution in the file manager DoubleCommander to open Visual Studio fulfills exactly these criteria.

I know this issue must have been introduced quite recently in VS, as I've been using the same version of DoubleCommander for a long time and I've never encountered this issue until a week or so ago.

Editing a file outside of VS and selecing "Reload solution" in the popup dialog will make the problem go away until VS is restarted in the same way as before.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
VS built-in version.

VS version (if appropriate):
VS2017 v15.3.3 and v15.3.4 at least

OS version (i.e. win10 v1607 (14393.321)):
Windows 10 Pro v1703

Worked before? If so, with which NuGet version:
Yes, but not sure exactly when it was introduced.
Sometime recently, as I haven't encountered the problem until about a week ago.

## Detailed repro steps so we can see the same problem

1. Create a new class library (or probably any project capable of installing NuGet packages)
2. Close Visual Studio
2. Create a batch file containing:
```batch
start /D "<path to solution dir with lowercase drive letter>" "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe" "<path to solution file>"
```
4. Run VS by executing the batch file
5. Install Fody from NuGet

The project file should now have something like this at the bottom:
```csproj
  <Import Project="C:\Users\Forb.Jok\Documents\Visual Studio 2017\Projects\ClassLibrary1\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets" Condition="Exists('C:\Users\Forb.Jok\Documents\Visual Studio 2017\Projects\ClassLibrary1\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('C:\Users\Forb.Jok\Documents\Visual Studio 2017\Projects\ClassLibrary1\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', 'C:\Users\Forb.Jok\Documents\Visual Studio 2017\Projects\ClassLibrary1\packages\Fody.2.1.2\build\netstandard1.0\Fody.targets'))" />
  </Target>

```
instead of, as I would expect, and as happens in every other situation, the same but with paths relative to the project file.

**Comment by rrelyea** [comment]
@zhili1208  says this appears to have worked in 15.0. Broke sometime since then.
Small fix. Please address for 15.5, since we missed 15.4.

**Comment by grisharav** [comment]
Any update on this issue? The scenario happens from TotalCommander as well and the issue is reproduced

**Comment by careri** [comment]
I nice catch with the drive letter. I was browsing the nuget source code without much success.
Thanks for the sanity check :)
