### ISSUE TITLE
NuGet 3.0.0 is unable to install packages with a min client version of 3.0.0

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#589]
NuGet 3.0.0 uses NuGet.Core 2.8.6 which enforces a min client version of 2.8.6 for scenarios using a local package repository.

**Comment by pranavkm** [comment]
Tries this out on both 2.8.6 and v3. The client can read the metadata for packages in both the scenarios. Installation fails on `2.8.6`, but that is expected.
