### ISSUE TITLE
Nuget package added but not used TFS

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5890]
Hi guys! I have some problem with my packages which i add in runtime with this code:
``  <Target Name="BeforeResolveReferences" 
<Exec Command="&quot;\\out-oracle\nuget\nuget&quot; update $(MSBuildProjectDirectory)\packages.config -id Sbt.CMS -FileConflictAction overwrite -Source \\out-oracle\nuget -Version 1.0.$(BUILD_BUILDID); &quot;\\out-oracle\nuget\nuget&quot; update $(MSBuildProjectDirectory)\packages.config -id Sbt.CMS.Infrastructure -FileConflictAction overwrite -Source \\out-oracle\nuget -Version 1.0.$(BUILD_BUILDID)" /></Target>``
Packages successfully added but not used ans i show this error in TFS logs:
``2017-09-14T16:44:03.9210456Z Output file "obj\Debug\Sbt.CMS.Cashflow.Infrastructure.dll" does not exist.
2017-09-14T16:44:03.9210456Z Task "Csc"``
And then a lot of errors about missing reference when msbuild tries to build solution. Who knows, why?
How I may say msbuild copy this refernce to output folder and use it?

NuGet 4.3
TFS 2017 Build Step Visual Studio Build
[buildLog19.txt](https://github.com/NuGet/Home/files/1303801/buildLog19.txt)

**Comment by zhili1208** [comment]
Could you do not use BeforeResolveReferences and try to use nuget.exe update in a script and run the script before build solution? Does that work? Looks like msbuild didn't get reference correctly here. Or Please share a small repro solution, I can take a look.

**Comment by ghost** [comment]
@zhili1208 thanks for response. Update and restore before build works, but it restores packages which added to package.config before build process started. New versions of some packages generates in previous steps in anouther solutions  and added to this solution in runtume  with this version 1.0.$(BUILD_BUILDID)" which I don't know before build started
Initial version of package looks like 
<package id="Sbt.CMS" version="2017.9.14.141659-alpha" targetFramework="net462" />
This versions we use in developers PC's.
In TFS we use versioning that looks like below
<package id="Sbt.CMS.Infrastructure" version="1.0.7812" targetFramework="net462" />
When developer commit his changes packages.config in first state, then when executes command from BeforeResolveReferences
packages.config looks like second string

**Comment by ghost** [comment]
@zhili1208 We have a 4 solution(~ 6-7 projects in every), three of which have projects that used in main  solution. Maybe more better way is combine all projects in one new solution which used only for build in TFS? With this approach need for use packages will disappear.

**Comment by zhili1208** [comment]
Yes, One approach is use one solution for all projects, Or you can migrate from package,config to packageReference (https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) which have floating version support (https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#floating-versions), you can specify floating version for your package, restore from your private feed before build, then your project will use 1.0.$(BUILD_BUILDID version

**Comment by rrelyea** [comment]
@Sm1le291  - closing, but would love to have you confirm that the suggest from @zhili1208 has helped.
