### ISSUE TITLE
Feature Request: Add response file support to NuGet.exe

### ISSUE THREAD

**Issue by nschwerzler** [NuGet/Home#5891]
## Details about Problem
Feature request (not a bug).

NuGet product used: NuGet.exe

NuGet version: 4.3.0.3

VS version: Visual Studio 2017

OS version: Windows 10

Worked before? If so, with which NuGet version: Not applicable, New feature request

## Detailed repro steps so we can see the same problem
Feature Request: Add response file support to NuGet.exe. Response files are text files that contain NuGet.exe command line switches. Each switch can be on a separate line or all switches can be on one line.

My current scenario is we have a lot of potential token replacments using 'nuget.exe pack -properties key1=value, key2=value...' which will not fit into the command line limit.

There is also value here where the nuget tools can have command line switches added without having to worry about command line limits. It also gives users flexability to have customized command line profiles without having to create a command line wrapper.

Example tools that use the response file pattern:
- **CSC**: [C# Compiler Options](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/response-file-compiler-option)
- **MSBuild**:  [MSBuild Response Files](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files)

### Verbose Logs

Not applicable

### Sample Project

Not applicable

**Comment by rrelyea** [comment]
Love the idea. Would like us to also work with DotNet CLI team here.
Likely should add to NuGet.exe and then to DotNet.exe code base (GitHub.com/dotnet/cli) as well.
Please submit PR for the NuGet.exe side. I'll open an issue with CLI team, and include you there. We'll discuss that with them as well.
