### ISSUE TITLE
NuGet.exe pack file access is causing warnings in some build tools

### ISSUE THREAD

**Issue by nschwerzler** [NuGet/Home#5892]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.3.0.3

VS version: Visual Studio 2017

OS version: Windows 10

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. NuGet.Config file is getting accesses when doing NuGet.exe pack. This violates rules in some build tools. 

C:\Users\\[user]\AppData\Roaming\NuGet\NuGet.Config
C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

See [Configuring NuGet behavior](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior)

### Verbose Logs

Not applicable

### Sample Project

Not applicable

**Comment by emgarten** [comment]
This is a problem all over for NuGet. I think the client should ignore config files it can't read and warn on a verbose level about it.

**Comment by nschwerzler** [comment]
After experimenting with the code, I found that by allowing pack to take a config file, it no longer tries to read the default config file(s) if you pass in a config to the pack command. This solves the problem we are seeing.
