### ISSUE TITLE
nuget.exe list PackageName -IncludeDelisted doesn't show unlisted package

### ISSUE THREAD

**Issue by van800** [NuGet/Home#5896]
nuget list JetBrainsRiderProtocol -IncludeDelisted -PreRelease -verbosity detailed
GET https://www.nuget.org/api/v2/Search()?$filter=IsAbsoluteLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm='JetBrainsRiderProtocol'&targetFramework=''&includePrerelease=true
No packages found.
NuGet Version: 3.4.3.855

https://www.nuget.org/api/v2/Packages?$filter=Id%20eq%20%27JetBrainsRiderProtocol%27
Successfully finds my package

![pasted image at 2017_09_15 12_30 pm](https://user-images.githubusercontent.com/1482681/30476199-89eabab2-9a09-11e7-8079-cc02566c97fa.png)

Related JetBrains Rider request https://youtrack.jetbrains.com/issue/RIDER-9545

**Comment by mishra14** [comment]
@nkolev92 can you please take a look?

**Comment by nkolev92** [comment]
Thanks for creating this issue. 

The NuGet client itself still respects the flag, so it might work with other package sources.
The list command favors the search endpoint over the packages endpoint if available. 
NuGet.org however does not support this anymore as it goes against the intentions of the customers when they unlist this package. 

Without sufficient traction our community, we have decided not to address this issue. 
We will consider it again if we get enough feedback from our community.

**Comment by TiltonJH** [comment]
I have a similar problem.

`nuget list -IncludeDelisted` does not seem to work anywhere (v.4.4.1.4656).  I have tried it with NuGet.Server 2.11.3 and 3.0.0. As well as -allversion and/or -prerelease.

Looking at `/nuget/Packages()` show the delisted packages. 

So `-IncludeDelisted` is generally not supported? So why does this switch exist at all?

Related NuGet.Server Issue [https://github.com/NuGet/NuGetGallery/issues/5066](url)
