### ISSUE TITLE
Packaged NuSpec file truncating version when version parameter passed to CLI

### ISSUE THREAD

**Issue by wozzo** [NuGet/Home#5902]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 4.1.0.2450

## Detailed repro steps so we can see the same problem

1. Create a nuspec file which contains a version including build metadata (after + symbol), e.g. `19.0.0-cathy+1709061515.ref610cb`

2. Run the cli passing in the version there
```
.\NuGet.exe pack -Version "19.0.0-cathy+1709181354.wbates" -BasePath "C:/Projects/dev/_tools" -OutputDirectory "C:/Projects/dev/_tools" "C:/Projects/dev/_tools/AcService.temp.nuspec" -NoPackageAnalysis
```

3. Check the nuspec version in the package and the version will be missing the build metadata, i.e. "19.0.0-cathy"

4. Run the same command without the -Version parameter
```
.\NuGet.exe pack -BasePath "C:/Projects/dev/_tools" -OutputDirectory "C:/Projects/dev/_tools" "C:/Projects/dev/_tools/AcademyService.temp.nuspec" -NoPackageAnalysis
```

5. The version in the nuspec will now be correct and include the metadata

### Verbose Logs

```
NuGet Version: 4.1.0.2450
Attempting to build package from 'AcademyService.temp.nuspec'.

Id: AcademyService
Version: 19.0.0-cathy
Authors: Artesian Solutions
Description: Artesian AcademyService
Dependencies: None

Added file '[Content_Types].xml'.
Added file '_rels/.rels'.
Added file 'AcademyService.exe'.
...
```

**Comment by nkolev92** [comment]
@wozzo 
Semver2 support was added to NuGet in 4.3.

Can you please test with https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe ?

**Comment by wozzo** [comment]
Thanks. It works in 4.3
