### ISSUE TITLE
Fn+F1 does not take to the right help page for PM UI and Console

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5912]
Steps:

1. Go to VS PM UI:
![image](https://user-images.githubusercontent.com/14800916/30669774-62c70684-9e14-11e7-98ce-8be7452653f9.png)

2. Click Fn+F1

**Expected**: This should take to the page: [NuGet Package Manager UI](https://docs.microsoft.com/en-us/nuget/tools/package-manager-ui)

**Actual**: This takes to completely unrelated page:  https://msdn.microsoft.com/query/dev15.query?appId=Dev15IDEF1&l=EN-US&k=k(VS.Ambient)&rd=true

Note that this searches for unrelated term: **VS.Ambient**

**Edit**: The same should happen for PMC. See comments below from @kraigb 

cc: @karann-msft , @kraigb

**Comment by kraigb** [comment]
There are two things that need to happen here.

1. The PM UI needs to set F1 keywords for Visual Studio. The link shown in this issue indicates that VS is simply searching on "VS.Ambient", which indicates that the UI in question has not set its keywords properly. (It can also show up as VS.Properties, which is equally ambiguous.)

2. Once the keywords are being set, it's necessary to edit https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Tools/Package-Manager-UI.md and add the keyword string to the f1_keywords: field in the header metadata. This is what completes the F1 linkage. Please create a doc issue once we know what the keywords are.

@anangaur You should create a similar issue for the PM Console. It has the same issue. In this case the keywords need to be added to https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/Tools/Package-Manager-Console.md.

**Comment by anangaur** [comment]
Updated the title and description to cover both PM UI and PM Console

**Comment by anangaur** [comment]
We should fix this in the next VS release.

**Comment by rohit21agrawal** [comment]
@anangaur please provide the keyword for both pm console and package manager ui so I can add them in code

**Comment by anangaur** [comment]
PM Console: `VS.NuGet.PackageManager.Console`
PM UI: `VS.NuGet.PackageManager.UI`

Made the changes on the doc pages as suggested by @kraigb : https://github.com/NuGet/docs.microsoft.com-nuget/pull/642
