### ISSUE TITLE
NuGet client inside VS (StartBackgroundJobRunnerAsync) uses a long running loop inside a thread pool thread.

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#5916]
## Details about Problem

VS 15.5 update

## Detailed repro steps so we can see the same problem

1. Open any .Net Core solution, use windbg or other debugger to check threads.

2. One thread pool threads is under:
0e 45dee27c 71f53c73 mscorlib_ni!System.Threading.Monitor.Wait(System.Object, Int32, Boolean)+0x17 [f:\dd\ndp\clr\src\BCL\system\threading\monitor.cs @ 203] 
0f 45dee294 71f53bae mscorlib_ni!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(Int32, UInt32, System.Threading.CancellationToken)+0x4b [f:\dd\ndp\clr\src\BCL\system\threading\SemaphoreSlim.cs @ 469] 
10 45dee2f8 70d2b26f mscorlib_ni!System.Threading.SemaphoreSlim.Wait(Int32, System.Threading.CancellationToken)+0x1ee [f:\dd\ndp\clr\src\BCL\system\threading\SemaphoreSlim.cs @ 297] 
11 45dee348 70d2b15f System_ni!System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].TryTakeWithNoTimeValidation(System.__Canon ByRef, Int32, System.Threading.CancellationToken, System.Threading.CancellationTokenSource)+0xff [f:\dd\NDP\fx\src\sys\system\collections\concurrent\BlockingCollection.cs @ 712] 
12 45dee368 7122b2ee System_ni!System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].TryTake(System.__Canon ByRef, Int32, System.Threading.CancellationToken)+0x3f [f:\dd\NDP\fx\src\sys\system\collections\concurrent\BlockingCollection.cs @ 667] 
13 45dee380 270ec6d4 System_ni!System.Collections.Concurrent.BlockingCollection`1[[System.__Canon, mscorlib]].Take(System.Threading.CancellationToken)+0x1a [f:\dd\NDP\fx\src\sys\system\collections\concurrent\BlockingCollection.cs @ 578] 
14 45dee3e0 71f56ba9 NuGet_SolutionRestoreManager!NuGet.SolutionRestoreManager.SolutionRestoreWorker+<StartBackgroundJobRunnerAsync>d__42.MoveNext()+0x1c4 [E:\A\_work\7\s\src\NuGet.Clients\NuGet.SolutionRestoreManager\SolutionRestoreWorker.cs @ 337] 
15 45dee3e8 71fb99fa mscorlib_ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.InvokeMoveNext(System.Object)+0x19 [f:\dd\ndp\clr\src\BCL\system\runtime\compilerservices\AsyncMethodBuilder.cs @ 1090] 

...

## Other suggested things

This code takes away one thread pool thread out of the pool.  It is an incorrect way to use thread pool, which is designed to be reused and shared to process small requests.  NuGet should change this code to an async await, so it doesn't block the thread, until there is a request.  Maybe an async way to use the Semaphore, instead of blocking the thread.

Blocking a thread pool thread increases the chance to run into thread pool exhaustion issues, which typically shows that VS freeze for half seconds without CPU activity (sometime rarely hit, but can use random UI delay issues very hard to reproduce and investigate. 

Because the stack is already inside an Async method chain, a fix should be easy.

**Comment by jainaashish** [comment]
Thanks @lifengl for the issue and suggested workaround. How about if we move it from thread pool thread to local thread? or we can also look for ways where we dont run an infinite loop rather asynchronously run it whenever there is a new request for restore.

**Comment by lifengl** [comment]
I think both will work.  If restoring process itself is very long and slow (when it processes a request, maybe it need wait network or something), using a separated thread might be a better option.
