### ISSUE TITLE
Duplicate errors when adding project dependency

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#5921]
Hi,

I am trying to create a NuGet package with NuGetizer 3000 in Visual Studio 2017 15.3.5. When I add a reference to the project that I need to create the NuGet packgage of, I get a lot of the same errors on different dll's:
"Duplicate package source files detected for target package file path 'lib\netstandard2.0\System.Diagnostics.Debug.dll'".

![nuget_dependencies](https://user-images.githubusercontent.com/14166838/30727152-cdd54024-9f92-11e7-93d8-a163ffd219c4.png)
![nuget_errors](https://user-images.githubusercontent.com/14166838/30727182-054090e0-9f93-11e7-8cc9-0c1db86de711.png)

What is the right way to add dependencies to the NuGet package? Do I need to manually add them?

NuGet version: 4.3.1
NuGetizer: https://github.com/NuGet/NuGet.Build.Packaging

**Comment by kzu** [comment]
Could you please provide a binary log by building with the `/bl` switch? Thanks!

**Comment by thorgeir** [comment]
I managed to to fix this in my project.

In my project, the nuget-project referenced a projectA that referenced projectB
I was getting duplicate errors for projectB

in projectA.csproj I added `<Private>true</Private>` in the `<ProjectReference>`  node for projectB

Hope this helps someone.

**Comment by kzu** [comment]
If the files truly point to identical files, we are smarter at de-duplicating now. 

Fixed via https://github.com/NuGet/NuGet.Build.Packaging/pull/151
