### ISSUE TITLE
fix failing nuget.protocol functional tests

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5922]
![image](https://user-images.githubusercontent.com/1857490/30729642-fda09e7a-9f15-11e7-819c-817c23800b4f.png)

we should at least investigate enough to make sure that this is not a product defect since we are shipping 15.4 pretty soon.

CC: @rrelyea

**Comment by nkolev92** [comment]
Tests are working now. 
Closing this.
