### ISSUE TITLE
Missing announcements for three new specs

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#5924]
In case anyone missed these (they were announced overnight in various issues/comments but not (yet?) part of the [NuGet/Announcements](https://github.com/NuGet/Announcements/issues)) repo:

* Package immutability - [spec](https://github.com/NuGet/Home/wiki/Package-Immutability) / [discussion](https://github.com/NuGet/Home/issues/5917)
* Package download API - [spec](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Package-download-API) / [discussion](https://github.com/NuGet/Home/issues/5919)
* Enable repeatable builds for PackageReference based projects - [spec](https://github.com/NuGet/Home/wiki/Enable-repeatable-builds-for-PackageReference-based-projects) / [discussion](https://github.com/NuGet/Home/issues/5602)

@karann-msft / @anangaur Seems anyone can post to https://github.com/NuGet/Announcements/issues, is that intended? (may want to set that to project admins only)

**Comment by anangaur** [comment]
All of these specs will be announced when they are ready to be reviewed. Right now these are in incubated state which means we are still adding details. I guess the first one is close to be announced.

**Comment by maartenba** [comment]
Thanks! BTW do check permissions for https://github.com/NuGet/Announcements/issues - seems everyone could in theory announce things there.

**Comment by anangaur** [comment]
It seems its not possible to limit issue creation to some, on a public GitHub repo. https://help.github.com/articles/creating-an-issue/

I see the same is the case for https://github.com/dotnet/announcements repo.

Is there an alternative way to achieve this?

**Comment by maartenba** [comment]
Indeed! Just tried on one of my own repo's, issues always seem possible. Ah well, guess it's clear in that repo others should not be posting. Thanks @anangaur for checking!

**Comment by anangaur** [comment]
Feel free to close this issue or wait for the above specs do be announced and then close :)

**Comment by maartenba** [comment]
Closing for now.
