### ISSUE TITLE
Referencing SQL Database Project from Azure Function in the same solution

### ISSUE THREAD

**Issue by mlorbetske** [NuGet/Home#5928]
This originally came in as an e-mail on the Azure Functions discussion distribution group.

Hi all, I am trying to refactor an existing data-mining Azure solution we have from using a Classic Cloud Service to using an Azure Function. When I add the Azure Function, I can add a reference to all other projects in the solution except for the SQL Database Project. In which case, I get the exception: “Unable to find project information for ..\SQLDatabase1.sqlproj'. The project file may be invalid or missing targets required for restore.”
 
To test whether it’s something specific to the configuration of this project, I created a new Solution, added an Azure Function and a SQL Database Project and tried referencing the SQL Database Project from the Azure Function and I see the same exception: 

![image](https://user-images.githubusercontent.com/1414993/30775621-ce85f2ce-a04c-11e7-9391-f8b52b02120d.png)
 
Is there any way I can reference a SQL Database Project from an Azure Function?

**Comment by zhili1208** [comment]
I think the ask here is not "Add support for SQL", we need to ignore sqlproj during restore like what we did for .shproj in nuget.exe.

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet.Client/commit/7fc2573b76fceb8a007a25012027c5b829c0801a
