### ISSUE TITLE
A design weakness - Visual Studio

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#5931]
No idea if this is the correct area to post this, but here goes.

NuGet has numerous design flaws and I've ranted about these before, well another one has come to my attention and I wanted to see what the prospects are for addressing it.

When I add a NuGet package to a project in a solution the tools insert a `<HintPath>` into the project's project file that points to the target assembly. That `<HintPath>` is always a relative path using .. notation and usually/always points to somewhere within the solution's "packages" folder - this is all fine and dandy.

Until I have a different solution and I want to add the above project to it, that is I want two _unrelated_ solutions to include the same project.

Unless this is done with great care it breaks because the project with the relative path .. to the NuGet is tied to the folder structure of the solution that we were in _**when we added**_ the NuGet package, the project is no longer easy to move around or to access from a different solution.

It surely would be much better design to use `"$(SolutionDir)"` in the `<HintPath>` rather than a raw relative path? 

This way the project can simply "assume" that whatever solution context it happens to be in, it can always refer to the packages folder as `"$(SolutionDir)\Packages"`.

Currently a project can only be used this way if all the solutions its included in follows a standard folder structure (with respect to their contained project sub-folders) which greatly limits flexibility, bear in mind solution folder structures do not have to follow a particular structure (most do) and the actual structure is sometimes beyond the control of a developer.

If one solution folder contains the .sln file and a sub folder "projects" that in turn contains all the project folders for the solution's projects then the `<HintPath>` will reflect this, but if one of these projects is now added to a _**different**_ solution who's solution folder contains the .sln and other projects but no intermediate "projects" folder then it breaks because the relative path to "packages" is not compatible with the folder structure of this second solution, that is the "packages" folder in this second case will have a different relative path to that defined in the contained project's `<HintPath>`.

I've had to manually unravel numerous situations like this recently where the behavior of NuGet is almost unfathomable and requires deep investigations, all time consuming.

So how about addressing this and in an upcoming release use `"$(SolutionDir)"` to root the packages folder references?

UPDATE

I just edited a sample project here and changed this:

`<HintPath>..\packages\Dapper.1.50.2\lib\net451\Dapper.dll</HintPath>`

to this:

`     <HintPath>$(SolutionDir)packages\Dapper.1.50.2\lib\net451\Dapper.dll</HintPath>
`

with no ill effects, the project refreshed in VS and the reference to Dapper resolves fine.

With the former path the packages folder that will be used will always be the packages folder for the solution in which the package was initially added.

With the latter it will always be the packages folder of the solution we are building and this more reasonable I think.

Thx

**Comment by rrelyea** [comment]
Packages.Config is an early NuGet technology.
We are attempting to ensure that PackageReference will fix many of the fragilities of PackagesConfig.
We don't plan to major change Packages.Config code paths, and hope to provide a smooth transition to customers to PackageReference techniques. We aren't all the way there yet.
We'd love for you to learn about PackageReference, and let us know of any problem you may hit while migrating a small solution to use it.

**Comment by mishra14** [comment]
Useful links realted to @rrelyea's comment: 
https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#dependency-resolution-with-packagereference-and-projectjson

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by dasMulli** [comment]
btw the docs still say:

> At present, package references are supported in Visual Studio 2017 only, for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update).

Is this still true or do the docs need a change?

**Comment by mishra14** [comment]
@jainaashish: Do we need to update the "important" not in this [page](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)? If so, what is the expected change here?

**Comment by nkolev92** [comment]
@mishra14 Created https://github.com/NuGet/Home/issues/6009 and linked to our epic.
