### ISSUE TITLE
NuGet Package Manager ignores source argument

### ISSUE THREAD

**Issue by twsouthwick** [NuGet/Home#5932]
## Details about Problem

Package Manager Console (VS 2017 15.3)

NuGet PS Module v2.0.0.0
NuGet Extension 4.3.1

## Detailed repro steps so we can see the same problem

We have a CI build for our project located here: https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml. When I try the command it says to install in the Package Manager, I get an error:

```
PM> Install-Package DocumentFormat.OpenXml -Version 2.8.0-vnext0051 -Source https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json
Restoring packages for [project].csproj...
  GET https://api.nuget.org/v3-flatcontainer/documentformat.openxml/index.json
  OK https://api.nuget.org/v3-flatcontainer/documentformat.openxml/index.json 351ms
Install-Package : Unable to find package DocumentFormat.OpenXml with version (>= 2.8.0-vnext0051)
  - Found 4 version(s) in nuget.org [ Nearest version: 2.7.2 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
At line:1 char:1
+ Install-Package DocumentFormat.OpenXml -Version 2.8.0-vnext0051 -Sour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for '[Project]'.
At line:1 char:1
+ Install-Package DocumentFormat.OpenXml -Version 2.8.0-vnext0051 -Sour ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:02.1350295
```

**Comment by nkolev92** [comment]
@twsouthwick What's your restore project style?
Package Reference or Packages.Config ?

**Comment by rrelyea** [comment]
My guess is that this failed because you didn't include "-IncludePrerelease" switch in the include prerelease command.

**Comment by twsouthwick** [comment]
So, if I ask for a specific version, I still need to specify that it should use prerelease? I would expect if this were the case, that NuGet would give me a warning that I am requesting a pre-release version without including prerelease versions. So, either way, it seems the behavior is unintuitive, and should be one of the following:

1. If a prerelease version is requested, automatically include the `-IncludePrerelease` flagg
2. If a prerelease version is requested, and no `-IncludePrerelease` flag is included, there should be some warning that that arg is being skipped

**Comment by rrelyea** [comment]
I'm unsure. Can you try again with the -includeprerelease flag and see what it does?  Also, can you answer @nkolev92 's questions to you?

**Comment by nkolev92** [comment]
Thanks for the suggestion. 
At this point we'd like to shift our focus to other higher impact issues as there is a simple workaround for your scenario.
