### ISSUE TITLE
nuget.exe should find the config file path based on the original working directory

### ISSUE THREAD

**Issue by WardenGnaw** [NuGet/Home#5933]
## Details about Problem
Updating to a newer version on NuGet.exe breaks building solution. Errors show that it is looking for nuget.config in project folders when there already is a nuget.config at the solution level. 

Targets _IsProjectRestoreSupported and _GenerateRestoreProjectPathWalk seem to be needed. 

Command: NuGet.exe restore -ConfigFile src\.nuget\nuget.config -PackagesDirectory packages\ src\Project.sln

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe and VS UI

NuGet version (x.x.x.xxx): 4.5.0.4487

VS version (if appropriate): 15.4.0 Preview 3.0 [26919.1.d15rel]

OS version (i.e. win10 v1607 (14393.321)): win10 v15063 (10.0.15063) 

Worked before? If so, with which NuGet version: 3.4.4.1321

### Verbose Logs
error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
AppData\Local\Temp\NuGetScratch\bpguxuqr.e1t.nugetrestore.targets(476,5): error : File \InnerProject1\src\.nuget\nuget.config' does not exist.

**Comment by emgarten** [comment]
@WardenGnaw did this work in 4.3.0?

Is the problem that the config file is skipped, or that the error above is shown?

Would you also provide a repro solution either as a zip or a github repro where I can try this out?

This sounds like it could be blocking for 4.4.0.

**Comment by emgarten** [comment]
@WardenGnaw confirmed that this is not a regression from 4.3.0.

Lowering the priority

**Comment by emgarten** [comment]
The working directory appears to change between projects which causes the relative path passed for -ConfigFile to be evaluated differently for each project.

A simple fix for this would be to convert all restore inputs to absolute paths up front to avoid having to resolve them in MSBuild.

**Comment by WardenGnaw** [comment]
That would be the solution to this. Using a relative path for a msbuild targets file is improper, therefore it would be passing in an incorrect ConfigFile path. 

Thanks!

**Comment by emgarten** [comment]
Glad the workaround helped @WardenGnaw 

I'm going to reopen this for tracking, nuget.exe should handle this better.
