### ISSUE TITLE
Enable locking of package dependencies and their versions (version range) at a solution/repo/global level

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5934]
More details coming soon.. 

Related features:
* Enable repeatable builds for PackageReference based projects #5602 
* Allow users to determine package resolution strategy during package restore - direct or transitive #5553

**Comment by MaximRouiller** [comment]
Any updates on the status of those features?

**Comment by anangaur** [comment]
https://github.com/NuGet/Home/issues/6764
