### ISSUE TITLE
Exception "Empty path name is not legal" when calling IVsPackageInstaller.InstallPackage on old projects and packages folder does not exist.

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#5936]
## Details about Problem

See TFS BUG 441552 for repro project.

- What is happening there is that when we try to install package, nuget logic tries to check if it is installed already and gets it from packages.config. 
- After that it assumes that path solution\packages\package exist and tries to uninstall package.
- But when packages folder does not exist, that path does not exist too , but no one checks the path for existense thus there is exception on this line when stream is opening: https://github.com/NuGet/NuGet.Client/blob/e5b934af0acf3b079ef083ac4f90949f3a7cdee0/src/NuGet.Core/NuGet.PackageManagement/Projects/MSBuildNuGetProject.cs#L445 

VS version (if appropriate):

d15prerel 26911.3004 

Worked before? If so, with which NuGet version: 

no, always was there

**Comment by rrelyea** [comment]
@abpiskunov  - as a packages config issue, we aren't investing a ton here. can you help us understand the severity and priority of this problem?
Is it important? Why? How many customers are hitting this? How bad is the impact?

**Comment by abpiskunov** [comment]
This repro for us when users try to Enable Latest C# / VB language features (C#7 and VB xx) on older web projects. However it reveals pretty obvious bug which i described. It could be easily repro for anyone (internal/external) using your COM extension API. According to Justin Emgarten even Nuget Package Manager dialog might have this exception in similar scenarios. 
I don't know how many customers are affected and how important it is, it is up to you to decide. I know that it is one line fix to check if path exist or not before opening a stream.

**Comment by PeterBrende** [comment]
I think this should be fixed.  There is a very legitimate scenario that will cause this, especially when using source control.  If I have upgraded to a new version of a NuGet package, and then roll back the code, the packages.config gets rolled back, but the folder under packages is gone at that point.  When trying to upgrade to the higher version again, this error is encountered.  At least that is what happens with my company's VSPackage which manages some of the NuGet packages installed on different projects in our applications.

**Comment by sprotty** [comment]
Also hitting this issue, a fix would be appreciated
