### ISSUE TITLE
Install/Uninstall operations from PMC do not refresh PM UI for legacy project system

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5939]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI and PMC

NuGet version (x.x.x.xxx): 4.4.4475

VS version (if appropriate): 15.4 Preview 3 | 26923.0.d15rel

## Detailed repro steps so we can see the same problem

1. Create new classic desktop console application.

2. Launch PM UI and PMC

3. In PMC type `install-package newtonsoft.json`

4. Refresh PM UI.

5. In PMC type `uninstall-package newtonsoft.json`

## Expected
PM UI should refresh to indicate that the package has been uninstalled.

## Actual 
PM UI needs manual refresh.

![pmc and ui](https://user-images.githubusercontent.com/10507120/30837338-33c803ca-a219-11e7-84e2-075093c86b9b.PNG)

## Notes
This does not happen for a net core sdk project because the restore nomination refreshed the PM UI.

**Comment by rrelyea** [comment]
@jainaashish  - PR bug. Please be aware and help make judgement of impact/priority.
