### ISSUE TITLE
Experience around bad resources are not consistent with http, UNC share and local disk for UI

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#594]
1. For bad http source:

Failed at private async Task<IEnumerable<UISearchMetadata>> GetSearchResultsForVisualStudioUIAsync with a WebException.

Error occured:\nSystem.Net.WebException: The remote name could not be resolved: 'packagesource'
   at System.Net.HttpWebRequest.GetResponse()
   at NuGet.RequestHelper.GetResponse()
   at NuGet.HttpClient.GetResponse()
   at NuGet.RedirectedHttpClient.GetResponseUri(HttpClient client)
   at NuGet.RedirectedHttpClient.EnsureClient()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at NuGet.MemoryCache.GetOrAdd[T](Object cacheKey, Func`1 factory, TimeSpan expiration, Boolean 

2. For bad UNC share such as \\abc\defgh

Loading for a long time (about 1 min) and then say "No items found"

3. For bad local disk name:

Loading quickly and then say "No items found" almost instantly

**Comment by yishaigalatzer** [comment]
@danliu can you please provide repro steps?

**Comment by emgarten** [comment]
We should stop displaying the stack trace here and just show a generic error message. The stack isn't going to help the user.

**Comment by danliu** [comment]
Repro steps:
1. Add the following 3 feeds to the package sources:
1) http://packagesource
2) \\abc\defgh
3) d:\baddisk

2. start package manager UI and try to connect to each of the 3 feed one by one and watch package pane for messages

**Comment by yishaigalatzer** [comment]
What justin said.

Also can we figure out why it takes so long to figure a unc path(probably by design, but I wanted to be sure).

**Comment by harshgMSFT** [comment]
@danliu don't see the stack trace in UI anymore, this seems to be handled by 
https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement.UI/Xamls/InfiniteScrollList.xaml.cs#L137. 
The message in this particular scenario seems to be correct as the `packagesource` does not exist, if we searched in a valid source (like nuget.org), and the package was not found, we log the same message as every other part `No items found.`

I think there is no consistency argument here, the error messages should infact be different. The only enhancement that can be done here is we do log a similar error message like `The path could not be resolved: '<path>'`  if a UNC/local file path was bogus), but the code which searches for the path in in NugetCore. Not sure we want to take it right now @yishaigalatzer

**Comment by harshgMSFT** [comment]
The longer wait time is because we try to do a directory search, which we have to do (and UNC path search is slower).

**Comment by yishaigalatzer** [comment]
We can fix nuget core. And if we can improve the perf for unc that's goodness

**Comment by harshgMSFT** [comment]
8749a5396f7f9f310c6bed8f289a15855f2d1f45

**Comment by yishaigalatzer** [comment]
I think we are done here. Lets wait for more user feedback on this before doing more work.
