### ISSUE TITLE
Ctrl+E in NuGet PM UI does not change control to the search bar

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5943]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS PM UI

NuGet version (x.x.x.xxx): 4.4.4475

VS version (if appropriate): 15.4Preview3 

Worked before? If so, with which NuGet version: Not sure

## Detailed repro steps so we can see the same problem

1. launch VS and file new project

2. right click and launch 'Manage NuGet Packages'

3. observe that the search bar displays a shortcut of ctrl+E.

4. press Ctrl+E. 

### Expected 
The control should have changed to the search bar

### Actual
The control is not changed to the search bar.

**Comment by rrelyea** [comment]
@nkolev92 - putting in your backlog...next bug fix week, please take a look.
