### ISSUE TITLE
Fix flaky E2E tests and help clean up

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5944]
[Results.txt](https://github.com/NuGet/Home/files/1335110/Results.txt)

The above test file has the list of most common E2E test failures.

NetCoreWebApp10AppInstallPackage
NetCoreWebApp10DowngradePackage
NetCoreWebApp10InstallMultiplePackages
NetCoreWebApp10ProjectReference
NetCoreWebApp10UninstallMultiplePackage
NetCoreWebApp10UninstallPackage
NetCoreWebApp10UpgradePackage

Help clean our CI and pick some of them, specially if you are the owner of any of them. If they are going to stay flaky, then consider adding a functional test instead and remove it from E2E.

- [ ] https://github.com/NuGet/Home/issues/5950 - EndToEnd test timeouts

**Comment by PatoBeltran** [comment]
These issues should also be considered as part of cleanup https://github.com/NuGet/Home/issues/3169, https://github.com/NuGet/Home/issues/3226
