### ISSUE TITLE
Fix GetInstalledPackagesWithCustomRestorePackagesPath  & GetInstalledPackagesForProjectWithCustomRestorePackagesPath 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5945]
These 2 E2E have been failing since they were added. 
Added in https://github.com/NuGet/NuGet.Client/pull/1666

I did a short investigation and I think that there are 2 issues here.

1. Looks like a product bug, the metadata is not populated with any value whatsoever. 
2. There are no packages installed other than NetCoreApp in the netcore case, so even if it did populate it with a value there it would be from the Fallback Folder one (??) //cc @emgarten for this. 

Think we need to investigate this ASAP, cause there's a chance it might be a product bug.

**Comment by jainaashish** [comment]
Test needs to be updated, since it returns fallback folder path for netcore sdk package. I didn't see any product code bug here.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/1727 by @jainaashish
