### ISSUE TITLE
Question: I

### ISSUE THREAD

**Issue by aberbegall** [NuGet/Home#5946]
Is it possible to get similar output with nuget.exe (outside Visual Studio) for this "Package Manager Console" command:

```powershell
PM> (Get-Project -All | ForEach-Object { Get-Package -ProjectName $_.Name })
```
using nuget.exe command line?

**Comment by mishra14** [comment]
@aberbegall unfortunately there is no equivalent yet. But we do have a backlog item for a list command that does the same thing per project.

You can track that issue - https://github.com/NuGet/Home/issues/4102

Please let us know if you need any more help from us.
