### ISSUE TITLE
[api] [nuget.org] api/v2/FindPackagesById()/$count endpoint is broken

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#5947]
Previously url `api/v2/FindPackagesById()/$count` worked - for example:
https://www.nuget.org/api/v2/FindPackagesById()/$count?includePrerelease=false&$top=160&id=%27Rx-Linq%27&includeAllVersions=false
Now it returns 404 Not Found.
I couldn't find any announcements about such API breaking changes. 
We use Artifactory extensively as out internal nuget server, it also is used as proxy for nuget.org (for CI builds). Now we're getting errors.

**Comment by mishra14** [comment]
This issue was moved to NuGet/NuGetGallery#4760

**Comment by mishra14** [comment]
@evil-shrike this is a NuGet Gallery issue. Please let us know if you need any more help.
