### ISSUE TITLE
[V3] Leading zero is dropped from revision

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#595]
Install Moq 4.2.1502.0911 to a .Net 4.5 project
The package file is saved as "packages\Moq.4.2.1502.0911\Moq.4.2.1502.911.nupkg"
However when running the Init.ps1 scripts V2 dependency resolver is looking for "packages\Moq.4.2.1502.0911\Moq.4.2.1502.0911.nupkg"

Note that V2 client named the file correctly.

**Comment by emgarten** [comment]
Does it make a difference if you use the v2 or v3 server?

**Comment by AndriySvyryd** [comment]
@emgarten No, same result

**Comment by yishaigalatzer** [comment]
@emgarten assigning to @AndriySvyryd if you have guidance please help him out

**Comment by AndriySvyryd** [comment]
Actually It does make a difference. v3 server only returns the 4.2.1502.911 version.
Discussed with @deepakaravindr and @yishaigalatzer. To fix all of these types of errors and still maintain compatibility with V2 projects we would need to use the non-normalized version from .nuspec consistently everywhere

**Comment by AndriySvyryd** [comment]
This depends on NuGet/NuGetGallery#2518
After it is fixed the client changes to be checked in are:
https://github.com/NuGet/NuGet3/tree/Issue595
https://github.com/NuGet/NuGet.PackageManagement/tree/Issue595
https://github.com/NuGet/NuGet.VisualStudioExtension/tree/Issue595
Additionally the functional tests will need to be updated accordingly.

**Comment by yishaigalatzer** [comment]
Fixed
