### ISSUE TITLE
EndToEnd test timeouts

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#5950]
The NetCore/NetStandard end-to-end tests sometimes timeout on project creation/initial restore. 

We can solve this in a couple of ways. 

- [ ] Write a task that would run an initial restore so subsequent restores are faster. 
- [ ] Add a fallback folder and add the needed packages there.

**Comment by rrelyea** [comment]
I've been involved in a discussion between the UWP Tools team and the Project system team. UWP folks need to understand when autorestore is done...and when the references due to it have all shown up in the project system.
@nkolev92  - I will loop you into that discussion.
