### ISSUE TITLE
Add a link to NuGet warning properties doc to the restore warnings and error page

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5953]
NuGet warnings and errors page: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings

The page lists out all the restore warnings and errors correctly. But I do not see a link to warning properties except the [compiler option page](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings), which is not very helpful to the users.

Can we please have a similar page for NuGet warning properties which merges the following specs - 

https://github.com/NuGet/Home/wiki/%5BSpec%5D-Transitive-Warning-Properties
https://github.com/NuGet/Home/wiki/Improved-NuGet-warnings

**Comment by mishra14** [comment]
Assign both PMs for better visibility :)

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1999](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1999) via [**ZenHub**](https://www.zenhub.com/)
