### ISSUE TITLE
Project A referencing package B via AssetTargetFallback, doesn't use that same AssetTargetFallback to pull B's dependency package C

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#5957]
@nkolev92 edit:

* Design - https://github.com/NuGet/Home/pull/11460
* Implementation - conditional on design approval - https://github.com/NuGet/NuGet.Client/pull/4372

-----------------------------

When I [added netcoreapp2.0 as a target for my console application](https://github.com/AArnott/VSMefSample/commit/ce6bef7cc49d0c0c15b2da322ef2a78b86e6d178), it failed at runtime because it couldn't find an assembly that was a transitive dependency of one of my package references. When I add the package reference explicitly, it works fine. I inspected the VSMefSample.deps.json file and found that there is no mention of the transitive dependency until I add it as a direct dependency.

It would seem then, that `dotnet restore` (or equivalent in VS) is not fully restoring transitive dependencies when it tries to see through net45 packages to adapt them to work on netcoreapp2.0.

**Repro**

```
git clone https://github.com/AArnott/VSMefSample
cd VSMefSample
git checkout ce6bef7cc49d0c0c15b2da322ef2a78b86e6d178
cd VSMefSample
dotnet restore
dotnet run -f netcoreapp2.0
```

**Expected**

```
dotnet run -f netcoreapp2.0
C:\Users\andarno\source\repos\VSMefSample\VSMefSample\VSMefSample.csproj : warning NU1701: Package 'Microsoft.VisualStudio.Composition 15.3.38' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
C:\Users\andarno\source\repos\VSMefSample\VSMefSample\VSMefSample.csproj : warning NU1701: Package 'Microsoft.VisualStudio.Composition 15.3.38' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Tree
   Apple (IsJuicy: True)
   Apple (IsJuicy: False)
   Pear (IsDelicious: True)
```

**Actual**

```
dotnet run -f netcoreapp2.0
C:\Users\andarno\source\repos\VSMefSample\VSMefSample\VSMefSample.csproj : warning NU1701: Package 'Microsoft.VisualStudio.Composition 15.3.38' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
C:\Users\andarno\source\repos\VSMefSample\VSMefSample\VSMefSample.csproj : warning NU1701: Package 'Microsoft.VisualStudio.Composition 15.3.38' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
   at VSMefSample.Program.Main(String[] args)
```

**Version info**

```
dotnet --info
.NET Command Line Tools (2.0.2-vspre-006949)

Product Information:
 Version:            2.0.2-vspre-006949
 Commit SHA-1 hash:  23fc6ec23d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2-vspre-006949\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by rrelyea** [comment]
Assigned to @mishra14  in backlog as P1.  Seems like ATF should work identically to non-ATF restores.
cc @emgarten

**Comment by mishra14** [comment]
@AArnott are you still facing this issue with latest VS preview build?

**Comment by AArnott** [comment]
@mishra14 Yes, it still repros with the latest int.preview build:

```
dotnet --info
.NET Command Line Tools (15.5.0-preview-007044)

Product Information:
 Version:            15.5.0-preview-007044
 Commit SHA-1 hash:  278cbf6c44

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\15.5.0-preview-007044\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

**Comment by rrelyea** [comment]
retitled: Project A referencing package B via AssetTargetFallback, doesn't use that same AssetTargetFallback to pull B's dependency package C

@AArnott likely had a scenario where A called an API in B and B called an API in C so he ran into a runtime issue.
When I tried creating the same situation...and had A call B and C, it was a compile time error.

**Comment by rrelyea** [comment]
@nkolev92 - please address...this is likely more important with netcoreapp3 increased usage.
if you can balance to a new member of team, that is fine also.

**Comment by rrelyea** [comment]
workaround is to manually reference C as a top level package reference, I believe.

**Comment by clairernovotny** [comment]
Bump?

**Comment by nkolev92** [comment]
Initial thoughts on this at https://github.com/NuGet/Client.Engineering/pull/97. 
Still deliberating and discussing.

**Comment by clairernovotny** [comment]
Bump? This is still an issue AFAIK.

**Comment by brinko99** [comment]
Indeed continues to be an issue. I found this issue through a StackOverflow question I posted further describing this:

https://stackoverflow.com/questions/63197142/nuget-framework-package-with-dependencies-from-core-project

If you can control the NuGet package, you can list the dependency under a blank / 'any' group as well as a specify target framework as an ugly workaround.

**Comment by KirillOsenkov** [comment]
This is a major adoption blocker for .NET and causing unnecessary friction in the ecosystem. Would be nice to prioritize this please.

@clairernovotny do you know anyone on the NuGet team who could perhaps champion this? ;)

**Comment by nkolev92** [comment]
Design out at https://github.com/NuGet/Home/pull/11460. 

Once that's been reviewed and approved, https://github.com/NuGet/NuGet.Client/pull/4372 is merge quality already.

**Comment by nkolev92** [comment]
This should land in 6.2/6.0.200/17.2. 

Not inserted yet, but should be in preview 1 of 17.2
