### ISSUE TITLE
Follow up with Internal partners to move from packages.config to PackageReference

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#5960]
** WORK WITH PACKAGE OWNERS - FIRST EMAIL ROUND WITH INTERNAL MSFT **

 Analyze how many packages have install/uninstall.ps1 and analyze the impact this change would have.
 Analyze contentfiles vs content packages
 Analyze lib/foo.dll packages

**Comment by jainaashish** [comment]
We started our first communication with internal partners to make packages ecosystem compatible with `PackageReference` Will create further follow up tasks in subsequent sprints to follow on this.
