### ISSUE TITLE
msbuild target/task for Nuget sign command

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5961]
Related tasks - https://github.com/NuGet/Home/issues/5907 https://github.com/NuGet/Home/issues/5904

**Comment by rrelyea** [comment]
As we discussed in standup. This is questionable whether we end up doing this or not. Need to continue discussion with CLI team.

**Comment by mishra14** [comment]
Closing this as we have no current plan for supporting this in waves 1 through 3.
