### ISSUE TITLE
nuget.exe push returns a 400/BadRequest

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5972]
From a Support Request - 

Using command line to push nuget package. Used to work a month ago. Today not working at all: 
`nuget push C:\projects\search\Ingeniux_InSite_Search_2.2.9.2-prerelease.nupkg [api key] -Source https://www.nuget.org `

Getting following response: 
```
Pushing PACKAGE_NAME-prerelease.nupkg to the NuGet gallery (https://www.nuget.org)... 
PUT https://www.nuget.org/api/v2/package/ 
BadRequest https://www.nuget.org/api/v2/package/ 2485ms 
nuget : Response status code does not indicate success: 400 (Bad Request). At line:1 char:1 + nuget push C:\downloads\Ingeniux_InSite_Search_2.2.9.2-prerelease.nup ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (Response status... (Bad Request).:String) [], RemoteException + FullyQualifiedErrorId : NativeCommandError 
```

I have tried to generate a new API key and not making any difference. Because the tool doesn't provide any details of the response text, I cannot figure what is going on. Note: The package is indeed a new pre-release version. I am on a tight deadline to deliver. Your earliest help is greatly appreciated.

--------

**Comment by anangaur** [comment]
Is the -Source parameter right? Which version of NuGet is this?

**Comment by mooTheo** [comment]
@mishra14 I'm having the same issue, did you find a workaround?
There are users that are suggesting to increment the version but that did not work in my case.

**Comment by mwpowellhtx** [comment]
I'm receiving a similar error.

The command I am sending is this:

```
%nuget_exe% push "%%f" -Source %nuget_api_source% -ApiKey %api_key%
```

And the result:

```
Pushing mypackage.1.0.0.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  BadRequest https://www.nuget.org/api/v2/package/ 671ms
Response status code does not indicate success: 400 (Bad Request).
```

My current NuGet version:

```
NuGet Version: 3.5.0.1938
```

I also checked whether my API Key was expiring, etc, or not. It's an original key, for instance; never expires, scoped to all.

Should we be using NuGet API v3 instead of v2?

**Comment by mwpowellhtx** [comment]
Similar report from me as the OP here. I was pushing packages perhaps a month ago. Now all of a sudden, not working for me. See my previous remarks an hour ago. Any update on the status of this? Perhaps it is v2 "deprecation"? Use v3 instead? It's a block for me at the moment. Thank you.

**Comment by mwpowellhtx** [comment]
Does this have anything to do with legacy API keys? In other words, are legacy keys being rejected and we must now generate new keys in whatever scope(s) are appropriate to us?

**Comment by anangaur** [comment]
Can you try the latest client i.e. 4.3.0?

**Comment by mwpowellhtx** [comment]
@anangaur A [new client](http://www.nuget.org/downloads)? Of course. I can definitely try that, thank you.

Yes, that was it, thanks!

**Comment by mishra14** [comment]
@mooTheo can you please try to push with the [latest nuget client](https://www.nuget.org/downloads)?

**Comment by erezvani1529** [comment]
confirming that the latest version works.

Thanks!

**Comment by nkolev92** [comment]
Closed as fixed.

**Comment by mwpowellhtx** [comment]
@nkolev92 Definitely fixed, thank you. I was able to investigate and identify the solution including with feedback from this issue. However, the only thing is the NuGet notification "announcing" the issue was 3-4 weeks late in coming. That'd be my only criticism.

**Comment by msaraf1** [comment]
I am facing the same issue with the latest version, can anyone help me which version should i use to fix this issue.

**Comment by nkolev92** [comment]
@msaraf1 
Download the recommended latest from http://nuget.org/downloads. 

File another issue with clear repro steps/setup/server if you're facing a similar problem.

**Comment by ckuetbach** [comment]
dotnet nuget push mypackage.nupkg -k <API-KEY> will produce the same error, but how do I specify the nuget version wrapped bei dotnet?

dotnet nuget --version
NuGet Command Line
5.0.0.6

**Comment by CrazyPyro** [comment]
This will happen if you try to push the same version number more than once.  https://alastaircrabtree.com/400-bad-request-when-pushing-a-package-to-octopus-deploy-using-nuget-push/

**Comment by anangaur** [comment]
You may want to use “—skip-duplicate” option or “-SkipDuplicate” options with dotnet.exe and NuGet.exe respectively.

**Comment by PeterPann23** [comment]
I had the same error, how did I fix it
- I have uploaded the .cer file to my NuGet organisation
- After doing that I created a new API key
- I then signed my packages using CLI 
` "for %%f in (X:\ASP-WAF\DLL\*.nupkg) do X:\Nuget\Nuget.exe sign %%f -CertificatePath CodeSign.pfx -CertificatePassword Pa$$word -Timestamper http://timestamp.sectigo.com" 
`
note that the password  and the pfx must be on disk

- I then push the packages using CLI
`for %%f in (X:\ASP-WAF\DLL\*.nupkg) do X:\Nuget\Nuget.exe push %%f -Source https://www.nuget.org/api/v2/package -SkipDuplicate myApiKex`

- Alternatively, you can use the ThumbPrint of the certificate if it's in the certificate store and get the certificate with out having the certificate exposed ondisk and no need for adding a password in my script, my bach sample for this:
`for %%f in (X:\ASP-WAF\DLL\*.nupkg) do Nuget.exe sign %%f -CertificateFingerprint 99c87c230e301138957eafbd35f465c028c29547 -HashAlgorithm SHA384 -Timestamper http://timestamp.sectigo.com`


I also sign my DLL's in visual studio using 
In the visual studio I add the following PostBuild command when compiling release packages, this is picked up when publishing the solution in release mode and my artifacts in the NuGet package are signed before being copied in the .nupkg file
```
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="signtool.exe sign /a /t http://timestamp.sectigo.com /fd SHA384 &quot;$(TargetPath)&quot;" Condition="$(ConfigurationName) == Release" />
	</Target>
```

I use the /a switch to get my code sign certificate from the certificate store and I need not specify any credentials, perhaps update the documentation with samples like this.
