### ISSUE TITLE
Use NuGet with different Culture

### ISSUE THREAD

**Issue by OryanHassidim** [NuGet/Home#5976]
## Details about Problem

NuGet product used: VS UI

VS version (if appropriate): Visual Studio Community 2017 version 15.3.5

Worked before? No.

## Detailed repro steps so we can see the same problem

1. Control Panel > Clock, Language, and Region > Region ;

2. In "Format" ComboBox, select "Hebrew (Israel)";

3. Click on "Additional settings..." in the bottom of the window;

4. In "Date" tab, in the "Calendar" section, in "Calendar type" ComboBox, select "לוח שנה עברי";

5. Click on "OK" button, and than "OK" button on the first window,

6. Now, If I try Download a package (in Nuget Package Manager Or Console), I get the error:
An error occurred while writing file 'C:\Users\Oryan\Desktop\WpfApp1\WpfApp1\packages.config': Failed to write packages.config as XML file 'C:\Users\Oryan\Desktop\WpfApp1\WpfApp1\packages.config'. Error: 'Illegal characters in path.'.

\>\>I can't download packages from Nuget for VS if I using the Hebrew calendar!!!

## Other suggested things
The same problem was with the VS Installer, and they fixed it. I guess that the problem is with "DateTime.Now.ToString()" without customize some specific format for all culture.

I will be happy if you will inform me when you will fix the bug. Thanks.

**Comment by PatoBeltran** [comment]
Hello @OryanHassidim, thanks for reporting this issue! I have been looking at it and opened a PR with a fix.
