### ISSUE TITLE
Unable to use `dotnet restore` behind corp firewall

### ISSUE THREAD

**Issue by jpierson** [NuGet/Home#5980]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 4.3.0.4406

dotnet.exe --version (if appropriate): 2.0.0

VS version (if appropriate): 2015

OS version (i.e. win10 v1607 (14393.321)): Windows 7

Worked before? If so, with which NuGet version: First time tried

## Detailed repro steps so we can see the same problem

1. Get behind corporate proxy with .pac script

2. Create a new project. ex: `dotnet new console -lang f#`.

3. Run `dotnet restore` to repeat the same error shown in step 2.

Expected: All referenced packages to be restored without error

Actual: The following error occurs.

> Response status code does not indicate success: 407 (authenticationrequired).

## Other suggested things

I've tried setting up a NuGet.config file in my project directory which looks like it is being read because when I get bad syntax it complains. But when I have everything in there that looks right I still get the same error.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
         <add key="dependencyVersion" value="Highest" />

        <add key="http_proxy" value="http://<my_org_proxy_domain>:9090" />
        <add key="http_proxy.user" value="<my_user>" />  
        <add key="http_proxy.password" value="<my_encrypted_password>" />
    </config>
</configuration>
```

### Verbose Logs

[dnrestore.log](https://github.com/NuGet/Home/files/1352438/dnrestore.log)

### Possibly related issues

https://github.com/dotnet/cli/issues/2190
https://github.com/NuGet/Home/issues/5358
https://github.com/NuGet/Home/issues/5078
https://github.com/NuGet/Home/issues/4668
https://github.com/NuGet/Home/issues/2880

**Comment by PatoBeltran** [comment]
Hey @jpierson thanks for opening this issue! Have you tried using nuget.exe `config` command to add your `http_proxy` configurations? [Here](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#config) is a link to our docs. You could also see [this](https://stackoverflow.com/a/15463892) SO answer that might be helpful. Please let me know if this fixes your issue!

**Comment by jpierson** [comment]
I've tried the config command, that is how I was able to get my generated encrypted password in my config. I've also tried the basic concept from the SO post as shown above except I set my config values in my local config file. I'm confident the local file was picked up though based on the log messages attached.

**Comment by jpierson** [comment]
I believe I have found a solution to the issue I was having. I believe our organization has a policy through our proxy to force use of HTTPS and possibly some centrally controlled settings on each dev machine to force NuGet to do the same. Either way appending an "s" to "http" for all of the proxy settings listed seems to have addressed my problem and allowed me to run `dotnet restore` without error.

### Example NuGet.config for proxies that enforce HTTPS:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
         <add key="dependencyVersion" value="Highest" />

        <add key="https_proxy" value="http://<my_org_proxy_domain>:9090" />
        <add key="https_proxy.user" value="<my_user>" />  
        <add key="https_proxy.password" value="<my_encrypted_password>" />
    </config>
</configuration>
```

Credit to Romain Mahrer who's [Stackoverflow answer](https://stackoverflow.com/a/23804030/83658) led me to the solution.

**Comment by PatoBeltran** [comment]
Nice to hear you were able to find a solution for your issue!

**Comment by prisar** [comment]
how to get my password encrypt

**Comment by jpierson** [comment]
Sorry @prisar I don't recall.

**Comment by ganeshgk** [comment]
@prisar running 
nuget config Set http_proxy.password="plaintextpass" 
Will encrypt password in your Nuget.Config

**Comment by ganeshgk** [comment]
@PatoBeltran I tried with both http & Https & still have the same issue, with proxy authentication on CentOS. Any solution?

**Comment by prisar** [comment]
> @prisar running
> nuget config Set http_proxy.password="plaintextpass"
> Will encrypt password in your Nuget.Config

@ganeshgk encode the password into base64 string

**Comment by ganeshgk** [comment]
> how to get my password encrypt

Yes it was a reply for this. @prisar
