### ISSUE TITLE
dotnet pack might include the same file multiple times, producing invalid package

### ISSUE THREAD

**Issue by zvirja** [NuGet/Home#5981]
## Details about Problem
VS version: 2017 Update 3 
dotnet --version: 2.0.0

`dotnet pack` could include the same file multiple times, producing invalid packages.

## Detailed repro steps so we can see the same problem
1. Create project with the following content:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludePDBsInPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <Target Name="IncludePDBsInPackage" Condition=" '$(IncludeBuildOutput)'!='false' ">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\$(AssemblyName).pdb" PackagePath="lib/$(TargetFramework)" />
    </ItemGroup>
  </Target>
</Project>
```

Motivation - I use SourceLink and want my primary package to include `pdb` files. Also I want to produce package with sources to support older clients. The code above was copied from [here](https://github.com/ctaggart/SourceLink/blob/6996bd38b61d24600f890b95b3ee8386c16e59fd/README.md#known-issues).

2. Create symbols package using `dotnet pack --include-source`
3. Open the produced package.

**Result:** PDB file was included twice.
...

## Other suggested things

If I change slash in the `PackagePath`, package will be correct:
```xml
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\$(AssemblyName).pdb" PackagePath="lib\$(TargetFramework)" />
    </ItemGroup>
```

The issue is that you don't normalize path before checking for duplicates.

**Comment by rohit21agrawal** [comment]
@zvirja i believe this issue has been fixed by : https://github.com/NuGet/NuGet.Client/commit/f422abd6b2f789bfbb75235355f145fd6e3f833e 

this will be available in Visual Studio 2017 Update 4.

If you want  to try it out right away, you can use the latest sdk/cli from : https://github.com/dotnet/cli/tree/release/15.5 

Also, we have a new feature that will enable you to include pdbs in your main package checked in as part of : https://github.com/NuGet/NuGet.Client/pull/1680 

It allows you to say something like this in your csproj:

```  <AllowedOutputExtensionsInPackageBuildOutputFolder>.pdb;$(AllowedOutputExtensionsInPackageBuildOutputFolder)</AllowedOutputExtensionsInPackageBuildOutputFolder>  ```

**Comment by zvirja** [comment]
@rohit21agrawal Many thanks for the prompt response! Yes, likely, the issue was fixed by that commit - however should be tested whether paths are normalized now in setter.

For now the workaround I mentioned works, so I'll wait till next VS update and  consume the better API later - it looks awesome! :blush:

**Comment by rohit21agrawal** [comment]
@zvirja i am going to close this issue, if you would like to verify it on your end, download the CLI i linked to in my above commit and try it out!

feel free to reactivate if you see any other issues
