### ISSUE TITLE
Plugin credential providers do not work with URIs containing spaces

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#5982]
There's a bug in PluginCredentialProvider in that it calls ToString() on the Uri rather than AbsoluteUri. By using ToString(), %20 is converted into a space. When we later construct the process arguments, the uri argument isn't quoted either (and shouldn't have to be, as URIs shouldn't contain literal spaces), so the credential provider gets a partial url.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.Credentials/PluginCredentialProvider.cs#L105

Example:
C:\Users\zarenner>c:\bin\nuget.exe list -Source http://zarenner-srv:8080/Collection%20With%20Spaces/_packaging/ZachTest/nuget/v3/index.json -Verbosity detailed
NuGet Version: 4.4.0.4475
CredentialProvider.VSS: Exit message: Unknown error ocurred in the provider.
CredentialProvider.VSS: Unexpected argument: With

**Comment by rrelyea** [comment]
Thanks for finding and sending the PR.

**Comment by rrelyea** [comment]
merged into dev, but issue was left open. closing. should make 4.5 given that merge date.
cc @emgarten
