### ISSUE TITLE
Net Core Build should use Company Name as Owner in favor of Authors

### ISSUE THREAD

**Issue by fjallemark** [NuGet/Home#5983]
When building NuGet-packages using net core 2.0  the **Authors** property in the csproj are also inserted as **Owner** in the NuGet package. I recommend that the **Company** property in the csproj  is inserted as **Owner** instead.

**Comment by rrelyea** [comment]
@rohit21agrawal - can you take a quick look at this suggestion?

**Comment by rohit21agrawal** [comment]
we had decided to deprecate Owners in NETCore projects, we just use the same value as Authors to be compatible with the server ask - the point was owners and authors should not be different.

**Comment by fjallemark** [comment]
The point is that in my world they are different: Authors are the developers that are writing the software, while the Owner is the legal entity owning the rights to the software. In Visual Studio's NuGet Package property page, there is no Owner field, but a Company field that can serve the same purpose. But the Company field is not included in the NuGet package. So what is the solution to include both names of responsible developers AND the name of the legal owner of the software in a NuGet package?

**Comment by rohit21agrawal** [comment]
@fjallemark are you concerned about the owner as displayed on NuGet.org ? The owner displayed on NuGet.org is actually the publisher of the package - which is the account that was used to publish the NuGet packge.

The owner as specified in the nuspec of your package is not really used anywhere, hence it is not being supported in SDK projects. Is there another reason that I do not understand that you want it in your nuspec?

CC: @joelverhagen

**Comment by fjallemark** [comment]
We use NuGet internally within our company group. NuGet metadata is a perfect way to publish which company (Company-property) that wrote the package and which developers that are primarily responsible (Author-property). The Company property is not included in the package, but the owner property is. Because the Owner property is set to the same value as the Author property, we manually have to change this to be the same value as the Company property. 
So for internal publishing it make sense that the Company property in the projects NuGet property page will be the value used as Owner instead of duplicating Author, even if its not used for public NuGet packages.
![skarmklipp2](https://user-images.githubusercontent.com/3410208/31582739-3a8f0410-b18c-11e7-8dd6-ba93ac9fbb44.PNG)

**Comment by emgarten** [comment]
The owners field in the nuspec typically corresponds to the **feed** owner. This information does not make sense for pack.

If you are using this locally or with some other feed that isn't setting this then I suggest using a custom tool to modify the nuspec and set this information.

**Comment by ahaleiii** [comment]
That answer is not intuitive to me. If I am looking at the metadata on a `.nupkg` and I see a property for `Owner`, I would consider this the owner of the **package**.
