### ISSUE TITLE
Incorrect diagnostic for floating versions

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5985]
_From @abpiskunov on February 9, 2017 16:30_

From @davidfowl :

![incorrect-diagnostic](https://cloud.githubusercontent.com/assets/1592091/22792531/f014062c-eea1-11e6-9008-f3062ab5ca84.png)

This shouldn't happen for floating versions...

_Copied from original issue: dotnet/sdk#845_

**Comment by emgarten** [comment]
I can't find `Dependency conflict` in the nuget code base, is it possible that this message is created by build? Everything should come from project.assets.json now that warnings/errors are written there by restore.

This is likely fixed in VS 15.3 already

**Comment by abpiskunov** [comment]
@natidea could you please confirm if this is still an issue?

**Comment by natidea** [comment]
This is fixed in 15.3. The code path was removed.

**Comment by mishra14** [comment]
@natidea in that case can we close this issue?

**Comment by natidea** [comment]
@mishra14 yes, you can close this

**Comment by mishra14** [comment]
Thanks @natidea
