### ISSUE TITLE
Implement 'X-NuGet-Protocol-Version' for push operations

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#5988]
More details can be found here: https://github.com/NuGet/Announcements/issues/10

**Comment by rrelyea** [comment]
@anangaur, @skofman1  - we need to discuss the transition plan for nuget.exe.
I'm assuming NuGet.exe 4.1 supports something similar.
What is the plan from the server side...will it support 4.1 and later for a while?
let's chat.

**Comment by skofman1** [comment]
On server side we support both "X-NuGet-Client-Version" and "X-NuGet-Protocol-Version". However, "X-NuGet-Client-Version" is not the correct name for the intention of this header, and clients are encouraged to use "X-NuGet-Protocol-Version". 
NuGet.org already supports both header, so you can test it.

**Comment by rohit21agrawal** [comment]
as per discussion with the team, we are going to document the fact that "X-NuGet-Client-Version" is a reserved header for official NuGet clients by Microsoft. All other clients should use the "X-NuGet-Protocol-Version" header with a min value of 4.1.0 to be able to push to NuGet.org . In addition, we should also ask them to start setting the user-agent string for telemetry purposes.

We should also fix the user-agent strings for all client entry points (except nuget.exe which already does this correctly).

CC: @anangaur

**Comment by anangaur** [comment]
We have already documented 3rd party clients to use the "X-NuGet-Protocol-Version" header. As stated in the meeting it would really be weird for third party clients using the NuGet.Command package and start sending the "X-NuGet-Client-Version"
