### ISSUE TITLE
[Enhancement] Intellisense in CSPROJ files should have fuzzy case insensitive matching

### ISSUE THREAD

**Issue by bradphelan** [NuGet/Home#5991]
https://twitter.com/bradgonesurfing/status/915835615597531137

> Microsoft.re

matches

> MicroSoft.re

doesn't. I'm not sure if nuget is case sensitive but intellisense for package matching should use something like case insensitive Levenshein distance metrics. It's easy to forget the exact name of a package and even remembering the exact prefix of a package can be easy to get wrong. Then you have to go hit google to find the right name.

**Comment by rrelyea** [comment]
@bradphelan  - Is this for an SDK based project? Or for a normal csproj w/ packageref? (please give exact repro steps...open VS...file new project...)

**Comment by bradphelan** [comment]
This is not a bug with a repro. It is an enhancement request on the intellisense completion for the package name in package reference. I assume it works the same for SDK or old style csproj.

repro is simple:

(1) edit a csproj file. 
(2) insert a package reference
(3) start typing the name of the package but with spelling mistakes and case errors
(4) visual studio should still suggest close matches.

**Comment by nkolev92** [comment]
This is not something that NuGet does directly, rather something the exp team handles. 
Creating an issue https://github.com/dotnet/ProjFileTools/issues/33 as I don't have the rights to move this issue. 

@bradphelan Can you please add more details there if needed.
