### ISSUE TITLE
NuGet push xplat path issues. 

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#5992]
_From @wojciechrak on October 5, 2017 13:56_

## Steps to reproduce
`nuget push C:\dev/nugets\*.nupkg`

## Expected  behavior
All packages in directory C:\dev\nugets are pushed to nuget repository.

## Actual behavior
Error is returned
`File does not exist (c:\dev/nugets\*.nupkg).`

## Additional notes
`nuget pack -OutputDirectory C:\dev/nugets\` or `nuget pack solutiondir/projectdir/project.csproj` work correctly
I am using standalone nuget.exe
NuGet Version: 4.3.0.4406

## Issue background
In our CI we are fetching feature branches from git and path on disk contains branch name, eg. "feature/123". This branch name is then used in our build scripts.

_Copied from original issue: dotnet/cli#7764_

Edit:
This one is similar https://github.com/NuGet/Home/issues/3544

**Comment by rohit21agrawal** [comment]
\ on mac and linux is a valid character for filenames and not treated as a directory separator char. 

we normalize paths everywhere, but this might be one of the few places where we don't , good catch.

**Comment by rrelyea** [comment]
We likely have a dupe or two about "/" and "\" in our code base. Let's find the dupes, and make sure we have the mega issue in the backlog.

**Comment by nkolev92** [comment]
Adding pushing with multiple slashes in path to the list. 

Original issue: https://github.com/NuGet/Home/issues/3544

**Comment by nkolev92** [comment]
Closing this in favor of https://github.com/NuGet/Home/issues/3584

That's a mega issue that contains all our of xplat path resolver problems.
