### ISSUE TITLE
Package versions not ordered correctly when using full semver 2.0

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#5993]
VS Feedback Item - 501328

I'm having the problem with sorting in "manage package for solution page", but also in automatic references upgrading of packages within the projects. I have this 2 packages in my repository:
0.0.0-branchname.10
0.0.0-branchname.9
but 0.0.0-branchname.9 is considered as latest, which is wrong obviouslyI think last number is not taken as number but as string which I think is wrong basic on semantic versioning specification

Hello, I'm using our packages generated within jenkins pipeline, we always put branchname as branchname in the example from gitlab, but I believe there is as problem after last dot, it seems to me like it is considered as string, but it's number based on semver2 spec. But I took a quick look in public nuget repo a there are no packages numbered like this. For example package "Microsoft.AspNetCore.Routing" has prerelease version 2.1.0-preview1-27020 but I need to have like this 2.1.0-preview1-27020.1, this should be completely fine if we are talking about semver2 support, so the last number after last dot is not ordered as number but as string and that's wrong

**Comment by mishra14** [comment]
On a quick look I saw that the packages were not correctly ordered in our UI either - 

![2017-10-05 2](https://user-images.githubusercontent.com/10507120/31246731-3116e702-a9c3-11e7-8c17-9d85cfd844d6.png)

---------

Seems I had a wrong repro. The ordering is correct here.

**Comment by emgarten** [comment]
@mishra14 the screen shot looks correct to me, what version are you expecting as the latest?

**Comment by risogolo** [comment]
Have you used .* convention? 0.0.0-branchname.* when referencing, then you will probably get version 9 as latest, not 10, at least I'm experiencing that kind of issue

**Comment by emgarten** [comment]
@risogolo take a look at the screenshot

**Comment by risogolo** [comment]
I'm afraid, this information is not visible on the screenshot

**Comment by risogolo** [comment]
what kind of repository have you used? recently I got on advice to delete obj folders from projects, but also this may be caused by different nuget repository manager. In my case. Also look at my screenshot now I'm talking only about websocket branch, I'm expecting 15 to be up as 1st
![image](https://user-images.githubusercontent.com/13233569/31267159-6aa78314-aa77-11e7-85dd-61ad78c3616e.png)

**Comment by risogolo** [comment]
In solution explorer I see v3, but in nuget package search v0, I'm using  Version="0.0.0-websockets.*"
![image](https://user-images.githubusercontent.com/13233569/31267564-e572f29e-aa78-11e7-91b6-9f43dea13baf.png)

**Comment by emgarten** [comment]
@risogolo the NuGet UI doesn't show the actual resolved version, but solution explorer does. Is `.3` the correct version?

**Comment by risogolo** [comment]
yes it suppose to be 3

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
