### ISSUE TITLE
References are not updated properly for a csproj files.

### ISSUE THREAD

**Issue by ievgennaida** [NuGet/Home#5996]
Hello. 
The problem can be reproduced only sometimes. Visual studio 2013 and Visual studio 2015.

Nuget version: 4.3.0.4168
```

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```

We have few big solutions with many projects in it. 
And sometimes references are not updated properly. 
Some files are updated ok and  some not. 
I cannot find any regularities.

Example (the csproj file):
```

    <Reference Include="Contracts, Version=2.4.200.0, Culture=neutral, PublicKeyToken=a13S4C41DSBC1s4a, processorArchitecture=MSIL">
     <HintPath>..\..\packages\Contracts.2.4.203.0\lib\net35\Contracts.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

See that **Include and Hint Path** has different versions!

**Comment by rohit21agrawal** [comment]
@ievgennaida the Version in the Include string is the AssemblyVersion , while the version you seen on the hint path is the NuGet package version , and it's acceptable that both may differ. Versioning is a choice that the package author makes and nuget just respects that decision.

Are you seeing any issues functionality wise?

**Comment by ievgennaida** [comment]
@rohit21agrawal 
_"Versioning is a choice that the package author makes and nuget just respects that decision."_

Than it's a bug definitely. 
I have a solution with a 50 or more projects (tfs+vpn+internal server for a packages) all reference each other. And some are deployed with Nuget. For example I have a lib installed  **Assembly.Contracts 2.4.200** .
The steps I do (vs2013):
1. Click Manage Nuget Packages 
2. Update the package from  **2.4.200** to **2.4.203** for all projects.

And what I got _sometimes_:

- All packages.config files are updated properly.
`<package id="Assembly.Contracts" version="2.4.203.0" targetFramework="net35" />`

- Some project files has wrong version !  while hintPath is updated:
```  
<Reference Include="Assembly.Contracts, Version=2.4.200.0, Culture=neutral, PublicKeyToken=a13S4C41DSBC1s4a, processorArchitecture=MSIL">
     <HintPath>..\..\packages\Assembly.Contracts.2.4.203.0\lib\net35\Contracts.dll</HintPath>
      <Private>True</Private>
    </Reference>

```
- But most of the projects are updated successfully (expected result):
```
` <Reference Include="Assembly.Contracts, Version=2.4.203.0, Culture=neutral, PublicKeyToken=a13S4C41DSBC1s4a, processorArchitecture=MSIL">
     <HintPath>..\..\packages\Assembly.Contracts.2.4.203.0\lib\net35\Contracts.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

This behavior is not constant. On a second run other project files can be not updated.

Assembly info:
```
[assembly: AssemblyTitle("Assembly.Contracts")]
[assembly: AssemblyVersion("2.4.203.0")]
[assembly: AssemblyFileVersion("2.4.203.0")]
```

P.s. Also some other developers has the same behavior on their machines. 
P.s.s. Sometimes I see the "out of memory exception" in the update window (16gb installed).

**Comment by rohit21agrawal** [comment]
@ievgennaida sorry i misunderstood your initial question. this definitely seems like a bug, i will try to repro it on my end and investigate the root cause.

**Comment by nkolev92** [comment]
@ievgennaida You say you are using VS 2013 and VS 2015 and you list a nuget version that has only shipped with VS 2017.

At this point we do not plan on releasing an update for VS2013/VS2015. 

Can you please tell us if you can reproduce this in VS 2017?

**Comment by ievgennaida** [comment]
@nkolev92 
Unfortunately I don't have vs 2017 yet and I don't think that we will migrate soon. 

We have Nuget\Nuget.exe added for each solution.
**Web solution:**
Version of exe file: 3.4.4.1321. 
VS 2015 nuget extention 3.4.4.1321 .

**Desktop solution:**
Version of exe file (Nuget.exe): 4.3.0.4168
VS2013  nuget extention 2.12.0.817

**Comment by nkolev92** [comment]
We're sorry for the inconvenience this is causing you. 

Unfortunately at this point we are not servicing 3.x and 2.x versions.

**Comment by ievgennaida** [comment]
I got same issue on VS 2017 @nkolev92  @rohit21agrawal  So problem is still there.
```
  <package id="TEST.TEST" version="3.3.77" targetFramework="net45" />

<Reference Include="TEST.TEST, Version=3.3.54.0, Culture=neutral, PublicKeyToken=b35cbb71b63bcbcf, processorArchitecture=MSIL">
     <HintPath>..\..\..\..\..\packages\TEST.TEST.3.3.77\lib\net35\POSServices.Contracts.dll</HintPath>
    </Reference>
```

**Comment by ievgennaida** [comment]
Attempting to gather dependency information for package 'TEST.TEST.3.3.77' with respect to project 'UnitTesting\BusinessLayer\ServiceInterface\Implementation\TESTInterface.Test', targeting '.NETFramework,Version=v4.5'
Gathering dependency information took 1,66 sec
Attempting to resolve dependencies for package 'TEST.TEST.3.3.77' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'TEST.TEST.3.3.77'
Resolved actions to install package 'TEST.TEST.3.3.77'
Retrieving package 'TEST.TEST3.3.77' from 'TEST'.
Removed package 'TEST.TEST.3.3.54' from 'packages.config'
Successfully uninstalled 'TEST.Contracts.3.3.54' from TESTInterface.Test
Adding package 'TEST.TEST.3.3.77' to folder 'C:\p\Branches\\packages'
Added package 'TEST.TEST.3.3.77' to folder 'C:\p\Branches\packages'
Overwriting existing file 'Properties\AssemblyInfo.Template.txt'..
Added package 'TEST.TEST.3.3.77' to 'packages.config'
Successfully installed 'TEST.TEST3.3.77' to TESTInterface.Test
Removing package 'POSServices.Contracts.3.3.54' from folder 'C:\p\Branches\packages'
Removed package 'POSServices.Contracts.3.3.54' from folder 'C:\p\Branches\packages'
Executing nuget actions took 3,66 sec
Time Elapsed: 00:00:05.4663423
========== Finished ==========

**Comment by formiaczek** [comment]
NuGet version 4.6.2.5055 still has this.

This problem is described well here, too:

https://stackoverflow.com/questions/45088790/why-are-c-sharp-references-added-differently-between-nuget-and-visual-studio

And this is exactly what I can see / reproduce every time.
