### ISSUE TITLE
Reinstalling a single package causes reinstallation of every package in the solution

### ISSUE THREAD

**Issue by stijnherreman** [NuGet/Home#5997]
## Details about Problem

After retargetting a project to a different .NET version, I followed the instructions to reinstall some packages. Instead of reinstalling a single package, it reinstalled every package in the solution.

NuGet product used: Package Manager Console

NuGet version: NuGet Package Manager 4.3.1, Package Manager Console Host Version 4.3.1.4445

VS version: Enterprise 2017

OS version: win10 v1607 (14393.1715)

Worked before? If so, with which NuGet version: n/a

## Detailed repro steps so we can see the same problem

1. Retarget a project from v4.5.2 to v4.6.1, in a solution containing multiple projects

2. Observe the following error: 
    > Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: System.IO.Compression, System.Net.Http, System.Xml.ReaderWriter

3. Open the Package Manager Console and execute the following command, as is described [in the docs referred to by the error](https://docs.microsoft.com/en-gb/nuget/consume-packages/reinstalling-and-updating-packages#using-update-package):
    `PM> Update-Package -Id System.Net.Http -reinstall`

4. Observe NuGet reinstalling every package for every project in the solution, including the execution of `install.ps1` scripts. It took a total of 1m32s in my case, and and even reinstalled packages like jQuery and Bootstrap in one of the projects:
    ```
    Removed package 'bootstrap 3.0.0' from 'packages.config'
    Skipping 'C:\<redacted>\Scripts\bootstrap.js' because it was modified.
    Skipping 'C:\<redacted>\Scripts\bootstrap.min.js' because it was modified.
    Successfully uninstalled 'bootstrap 3.0.0' from <redacted>
    Executing script file 'C:\<redacted>\packages\jQuery.1.10.2\Tools\uninstall.ps1'
    Skipping 'Scripts\jquery-1.10.2.intellisense.js' because it was modified.
    Removed package 'jQuery 1.10.2' from 'packages.config'
    Successfully uninstalled 'jQuery 1.10.2' from <redacted>
    Removed package 'Antlr 3.4.1.9004' from 'packages.config'
    Successfully uninstalled 'Antlr 3.4.1.9004' from <redacted>
    Package 'Antlr.3.4.1.9004' already exists in folder 'C:\<redacted>\packages'
    Added package 'Antlr.3.4.1.9004' to 'packages.config'
    Successfully installed 'Antlr 3.4.1.9004' to <redacted>
    Package 'jQuery.1.10.2' already exists in folder 'C:\<redacted>\packages'
    Added package 'jQuery.1.10.2' to 'packages.config'
    Executing script file 'C:\<redacted>\packages\jQuery.1.10.2\Tools\install.ps1'
    Successfully installed 'jQuery 1.10.2' to <redacted>
    Package 'bootstrap.3.0.0' already exists in folder 'C:\<redacted>\packages'
    File Conflict
    File 'Scripts\bootstrap.min.js' already exists in project '<redacted>'. Do you want to overwrite it?
    [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [?] Help (default is "N"):l
    'Scripts\bootstrap.min.js' already exists. Skipping...
    'Scripts\bootstrap.js' already exists. Skipping...
    ```

**Comment by rrelyea** [comment]
Sorry that was not an ideal experience.
Packages.Config was our v1 effort.
As such, we've come up with better ways to do packagemanagement that avoid the need to uninstall/reinstall. Moving to PackageReference in VS2017 is something that you could consider...and we hope to continue investing in that technology to make a great developer experience.
Please let us know how it goes...as we are doing major investments to find any problems in that space and address.

**Comment by stijnherreman** [comment]
@rrelyea Unfortunately, company policy currently prevents me from upgrading to the new csproj format, but thank you nevertheless for the info.

**Comment by svisagie** [comment]
@rrelyea, but why did you guys go and break something that was working perfectly in VS2015
