### ISSUE TITLE
We need docs for AssetTargetFallback, both generally and migrating from PackageTargetFallback .

### ISSUE THREAD

**Issue by Petermarcu** [NuGet/Home#5998]
@richlander opened this here: https://github.com/dotnet/core/issues/725

We need docs for AssetTargetFallback, both generally and migrating from PackageTargetFallback .

**Comment by rrelyea** [comment]
@karann-msft  - can you please help drive as necessary

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #511](https://github.com/NuGet/docs.microsoft.com-nuget/issues/511) via [**ZenHub**](https://www.zenhub.com/)
