### ISSUE TITLE
Package restore checkboxes in Options dialog is not hierarchical anymore

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#600]
Package restore checkboxes in Options dialog is not hierarchical anymore

Please check VS 2013, NuGet 2.8

1. Tools -> Options -> NuGet Package Manager -> General
2. Note that the checkboxes are linear. 'Automatically *' check box should be under 'Allow NuGet to download missing packages' checkbox. Because the 'Automatically *' checkbox is dependent on the other one

**Comment by yishaigalatzer** [comment]
The UI looks clear enough to me

![image](https://cloud.githubusercontent.com/assets/1238711/11406555/c0e88bb6-9362-11e5-885e-9481cfd1e3d0.png)
