### ISSUE TITLE
Build action not applying to contentFiles

### ISSUE THREAD

**Issue by mghextreme** [NuGet/Home#6000]
## Details about Problem

Dear Nuget community,

I've been stuck for some time now and I need your help. I've been trying to solve a single problem: attach a .dll file to a project (as an Embedded Resource). I had a relatively easy way placing it as a content, but having it as an Embedded Resource just doesn't work! It places the file in the correct place, but sets the Build Action to "Content".

I've read and followed the [official documentation](https://docs.microsoft.com/en-us/nuget/schema/nuspec) and placed a &lt;contentFiles&gt; section in the metadata, but it's still not working. Also, I found similar issues (#1908) with other parameters inside &lt;contentFiles&gt;.

I've attached my .nuspec file (with files names changed, for privacy):

myNuspec.nuspec (changed the extension to .txt so I could upload the file):
[myNuspec.1.0.0.0.txt](https://github.com/NuGet/Home/files/1363579/myNuspec.1.0.0.0.txt)

Bellow I've placed the data recommended:

NuGet product used: NuGet.exe
NuGet version: 4.1.0.2450
dotnet.exe --version: 1.1.0
VS version: Professional 2017
OS version: Windows 10.0.14393.1715 (v1607) [can't update]

**Comment by rohit21agrawal** [comment]
@jainaashish your recently investigated contentFiles, any idea abouut this issue?

**Comment by rohit21agrawal** [comment]
@mghextreme are you trying to consume this in a packages.config project or a PackageReference based project? 

If you are trying to use contentFiles, it only works for PackageReference projects , and you will have to place your file in the package in the following structure:

```contentFiles/{codeLanguage}/{TxM}/{any?}```

codeLanguages may be cs, vb, fs, any, or the lowercase equivalent of a given $(ProjectLanguage)

TxM is any legal target framework moniker that NuGet supports (see Target frameworks).
Any folder structure may be appended to the end of this syntax.

For example:

Language- and framework-agnostic:
    /contentFiles/any/any/config.xml

net45 content for all languages
    /contentFiles/any/net45/config.xml

C#-specific content for net45 and up
    /contentFiles/cs/net45/sample.cs

So try the same nuspec file you have and change the target in your file element to be contentFiles/any/any/ and see if it works

**Comment by mghextreme** [comment]
Hello, @rohit21agrawal . The path I already tryed to change, but no progress.

I'm using it on a `packages.config` project. The weird thing is: It works to add the file to the Project, the only part that doesn't work is the `Embedded Resource` part... Is there a way to change the project? Or should I use Json? Maybe `.targets` (already tried)? What should I change?

**Comment by rohit21agrawal** [comment]
@mghextreme  if you want this to make it work for packages.config based projects, include a targets file (with the same name as that of the package) in the build folder of your package. The targets file can include the embedded resource by specifying a relative path to it within the package.

If you want to go the contentFiles route instead, i would suggest you move all your dependencies to csproj file via PackageReference. If you need more info on how to do that, please refer to : https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

**Comment by mghextreme** [comment]
@rohit21agrawal I changed the destination project to a PackageReference project ([used this](https://gist.github.com/a4099181/074a6c3dd524ea0d343382137492399c), works nicely). Also, I updated my `.nuspec` file as the one attached below:

[myNuspec.1.1.0.0.txt](https://github.com/NuGet/Home/files/1375647/myNuspec.1.1.0.0.txt)

But now, when I install the package, it is not downloading the file nor attaching it to the project. I checked the project folder, the packages folder (which, btw, didn't include the package), the `bin\Debug` folder and also the `.dll` generated (with ILSpy) and I couldn't find the file that was supposed to be attached.

**Comment by rohit21agrawal** [comment]
@mghextreme 
with PackageReference, the contentFiles bild action is dynamically applied upon build - so you won't any changes in your csproj. I just packed the nuspec you provided , installed it into a wpf class library project (using PackageReference format) , and built the project, and was able to inspect the DLL under ILSpy and find the DLL embedded.

Here is the project: 
[contentFilesPackage.zip](https://github.com/NuGet/Home/files/1380408/contentFilesPackage.zip)

**Comment by mghextreme** [comment]
@rohit21agrawal Well... that's disappointing for me... I will check everything once again to see what I'm doing wrong. The only difference I've seen is I'm using an online Nuget Server, but that isn't (or at least, shouldn't be) a problem.

Anyway... Thanks so much for all the help these last few days!

**Comment by SeriousM** [comment]
> The only difference I've seen is I'm using an online Nuget Server, but that isn't (or at least, shouldn't be) a problem.

To pickup this problem: what the nuspec is actually doing is moving the `content\myDllFile.dll` to `contentFiles/any/any/myDllFile.dll` so that the `<contentFiles>` node can pick the file from `any/any/myDllFile.dll` (without contentFiles). This is very confusing but works...
