### ISSUE TITLE
Cookier Banner does not behavior on the NuGet blog

### ISSUE THREAD

**Issue by unniravindranathan-okta** [NuGet/Home#6004]
a) The banner should only show up in the right locales (not in the US).
b) There is no way to dismiss
c) Navigating to an article and coming back to the blog gets rid of the banner (wrong behavior).

**Comment by emgarten** [comment]
Should this be logged on the gallery instead? Home is primarily for the client.

**Comment by nkolev92** [comment]
Issue moved to [NuGet/NuGetGallery #7082](https://github.com/NuGet/NuGetGallery/issues/7082) via [**ZenHub**](https://www.zenhub.com/)
