### ISSUE TITLE
Update Package Reference Support documentation

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6009]
Update the important box in here. 

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

And other relevant documentation there.  

Issue "inspired" by https://github.com/NuGet/Home/issues/5931

Updating per Karann's request, 

The following box:
```
At present, package references are supported in Visual Studio 2017 only, for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update).
```
is not really correct, as what it's really talking abotu is which project tempaltes have package reference by default. 

The correct thing is that all project types that support packages.config, support package reference as well, but that's a sweeping statement, and we still have eco-system issues that prevent us from broadcasting that. 

Full Framework csproj (non SDK based projects) also "Support" package reference and can be converted to package reference. 

There's even an option users can enable to "allow selecting" the default project restore style. 

So I don't know all parts of the above braind dump we want to include, but the important box, at minimum should be something along the lines of:

``` At present, package references are supported in Visual Studio 2017 only.
.NET Core projects, .NET Standard projects,  and UWP projects targeting Windows 10 Build 15063 (Creators Update) and later are by default in the Package Reference management format.
```
Potentially include a line about fujll framework as well:

```
.NET full framework project support package reference, but currently the new project templates default to packages.config. 
```
The last part could have a link to the doc on how to change the default management format.

**Comment by karann-msft** [comment]
assigning back to @nkolev92 for more information.

**Comment by nkolev92** [comment]
Hey @karann-msft 
I have updated the issue with some braiin dump and suggestions. 
Let me know if you need more clarification/have questions/wanna chat through this.

**Comment by karann-msft** [comment]
Thanks @nkolev92

**Comment by karann-msft** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #593](https://github.com/NuGet/docs.microsoft.com-nuget/issues/593) via [**ZenHub**](https://www.zenhub.com/)
