### ISSUE TITLE
Remove the progress dialog shown on package restore on build

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#601]
Consider removing the progress dialog shown on package restore

**Comment by deepakaravindr** [comment]
As discussed with @yishaigalatzer , moving this bug to Update 1

**Comment by yishaigalatzer** [comment]
We don't have a solution for this, because VS doesn't let us run a blocking operation (that is required because build will fail otherwise), and without a dialog things just seem to hang.
