### ISSUE TITLE
Nuget exe throws long path issue

### ISSUE THREAD

**Issue by VQuery** [NuGet/Home#6011]
Errors in packages.config projects
    NU1000: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 cha
racters, and the directory name must be less than 248 characters.

**Comment by rohit21agrawal** [comment]
tracking issue: https://github.com/NuGet/Home/issues/5324

**Comment by nkolev92** [comment]
That was closed in favor of https://github.com/NuGet/Home/issues/3324
