### ISSUE TITLE
[security/spam] nuget.org gallery links do not have nofollow

### ISSUE THREAD

**Issue by ghuntley** [NuGet/Home#6021]
# Backstory
https://twitter.com/GeoffreyHuntley/status/918298133439774720
https://www.nuget.org/packages/poop/1.0.0

# Problem
Currently there is a huge incentive for bad actors to publish garbage packages as part of conducting dark SEO to boost page rankings of shady websites.

1) parsing description automatically adds links without nofollow

![image](https://user-images.githubusercontent.com/127353/31475899-214169a6-af4f-11e7-8d9c-e3e2f17ec57f.png)

2) project url does not have nofollow

![image](https://user-images.githubusercontent.com/127353/31476065-40f6f3fa-af50-11e7-9ae3-935cd73e2451.png)

# Resolution

https://support.google.com/webmasters/answer/96569?hl=en

**Comment by rohit21agrawal** [comment]
Issue moved to [NuGet/NuGetGallery #4839](https://github.com/NuGet/NuGetGallery/issues/4839) via [**ZenHub**](https://www.zenhub.com/)
