### ISSUE TITLE
Discrepancy in trailing backslashes in NuGetPackageFolders

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [NuGet/Home#6032]
Hello,

Using latest VS 15.4.0, Nuget package manager 4.4.0, I have started getting an error when trying to build a project referencing a Nuget package containing this .targets file:

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <None Include="$(NuGetPackageFolders)\SweekCms.Admin\1.0.24\content\sweek-admin.tar">
      <Link>sweek-admin.tar</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

Error is: 

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4406,5): error MSB3025: The source file "C:\Users\Bjorn\.nuget\packages\" is actually a directory.  The "Copy" task does not support copying directories.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4406,5): error MSB3030: Could not copy the file "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\SweekCms.Admin\1.0.10\content\sweek-admin.tar" because it was not found.
```

This worked in june. When looking at the obj\WebApplication1.csproj.nuget.g.props I see that the NuGetPackageFolders value is:

```
<NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Bjorn\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>
```

ie. a discrepancy in trailing backslashes. When changing the .targets file to utilize NuGetPackageFolderRoot, it started working again.

Looks a bit like this comment here: https://github.com/dotnet/sdk/issues/1250#issuecomment-303791974

I fixed my issue, but giving a heads up in case something is wrong here?

**Comment by bjorn-ali-goransson** [comment]
Background: https://github.com/NuGet/Home/issues/5237

**Comment by emgarten** [comment]
@bjorn-ali-goransson the issue is that `NuGetPackageFolders` contains multiple semi colon delimited folder paths and your example tries to use it as a single path.

`C:\Users\Bjorn\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder`

Beyond that it does look like NuGet should normalize these paths and add a trailing slash to make these easier to use. Currently I believe theses are written out as they were provided by the project. The fallback folder here comes from a project property in the SDK.

**Comment by bjorn-ali-goransson** [comment]
That's very interesting, thanks for the information!

**Comment by rrelyea** [comment]
Work here for us to (either us or the SDK team) normalize the paths to not have trailing slashes.

**Comment by nkolev92** [comment]
Dupping to https://github.com/NuGet/Home/issues/7968. 

I understand that it's newer, but it contains more relevant links.
