### ISSUE TITLE
Default Project Dropdown Empty After Adding/Saving New Solution & Project

### ISSUE THREAD

**Issue by julielerman** [NuGet/Home#604]
VS2015RC

Package Manager Console is active/open
No solution open
Create new project. (I"m targetting .net 4.6 and have tried with console and with class library)
Save project & solution.
Default Project dropdown remains empty
Get-Project myproject returns 'default project not found'
close console
open console
still empty
close solution
open solution
the project is now available in the dropdown

I'm not used to this behavior via VS2013.
Hope that my issue search did not miss a duplicate of this problem.
THanks

**Comment by danliu** [comment]
@julielerman, we could not repro the issue that you've reported using latest build. Can you please let us know the version of Visual Studio as well as NuGet you were using?

Also to confirm, the project template you were using is just plain c# class library and console application?

**Comment by julielerman** [comment]
Thanks for looking so quickly. I'll be at my computer later tonight. For now I can tell you ita the RC that was released at build and should be whatever version I'd nuget was part of that. Yes I was using a plain c# class lib and console. No aspnet5.

I don't think I did anything out of the ordinary. I think resharper was installed. I will try to see what happens without r#.

Thanks again for looking into it.

Julie

-----Original Message-----

**Comment by danliu** [comment]
thanks @julielerman. Please keep us updated.

**Comment by julielerman** [comment]
finally got home! (family emergency) but best I could think of to show you the problem was to create a little video. I put it on googledrive. Here: https://drive.google.com/drive/u/0/folders/0B0q9tUxAcMl2bWV2eG9EU1VVZ0U  (I haven't watched the final results since google keeps telling me it is still processing it)
Also my version is 14.0.22823.1 D14REL
HTH

**Comment by danliu** [comment]
@julielerman, sorry for the late response. I cannot view the video now, it says

The open folder can no longer be viewed.
It no longer exists or you non longer have permission to access it.

Can you please re-upload it, thanks!

**Comment by danliu** [comment]
@julielerman, please try out RC2 VSIX from https://nuget.codeplex.com/releases/view/615507, to see if your issue still reproes.

**Comment by julielerman** [comment]
Thanks. I'm out of band right now so was unable to respond re the video. I will try the new version and report back as soon as I'm able.


-----Original Message-----

**Comment by julielerman** [comment]
have not yet tried the vsix but here is (hopefully) a better link to the video so you don't think I'm seeing things. :)
https://drive.google.com/file/d/0B0q9tUxAcMl2RW5JdmhrcE1WT2M/view?usp=sharing

**Comment by danliu** [comment]
Thanks for the video! The repro steps seem very simple. 

What's the version of NuGet VSIX that you've installed? If you pick a different path to create a new class library project, does it still repro?

**Comment by julielerman** [comment]
Checking Visual studio, I see that the nuget extension version is 3.0.60410.213.

I’ll try a new project with a different path and get back with that info.

julie

**Comment by julielerman** [comment]
I get the same effect when I save the project to a different folder path

**Comment by danliu** [comment]
It's a bit strange, the steps are simple but we cannot repro it here. Can you please try the RC2 VSIX to see if it solves the issue?

**Comment by julielerman** [comment]
grabbing the beta now to check out.

**Comment by danliu** [comment]
Thanks, download link is https://nuget.codeplex.com/releases/view/61550

**Comment by julielerman** [comment]
ok ...still the same with the new version. Even if I was somehow doing something weird, a thousand other people will do the same thing. But maybe it's something about my machine. When I get a chance, I will reinstall VS2015RC. I will ask on twitter to see if anyone else can reproduce it.

**Comment by danliu** [comment]
Yeah, we haven't heard other people reporting it. Please let us know if they do have the same issue.

**Comment by julielerman** [comment]
should we close this then?

**Comment by danliu** [comment]
yes, please feel free to reopen if more people report it.

**Comment by ToineSeiter** [comment]
Hello, I've the same issue but I can't fill the dropdown by closing/reopening the solution.

**Comment by ray023** [comment]
I also have this problem with one of my VS2015 solutions.  

This started happening after I removed one of my projects and made a bunch of code changes.

Here is a screenshot from the package manager console:
![Package Manager Console](http://i.stack.imgur.com/Tl2ue.png)

Notice the dropdown is empty and when I run command Get-Package -ListAvailable, I get the following text returned:

Get-Package : Project 'Default' is not found.
At line:1 char:1
- Get-Package -ListAvailable
- ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (Default:String) [Get-Package], ItemNotFoundException
  - FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.GetPackageCommand

**Comment by jose-e-rodriguez** [comment]
I'm getting the same error when working on a new project. Any older project works fine.

![get-project_error](https://cloud.githubusercontent.com/assets/12707130/9704511/d6e79288-5477-11e5-8c40-8dd740670df1.png)

**Comment by jose-e-rodriguez** [comment]
As a workaround I found that creating first a Visual Studio Solution (_File --> New Project --> Other Project Types --> Visual Studio Solutions_) and then creating the project inside the solution the issue does not show. Shouldn´t creating a new project create a new solution as well?

**Comment by ToineSeiter** [comment]
I solved my error like you. The issue was due to my MVC project file.
My workaround : 
- create a new MVC project, 
- import all the Nuget packages I want,
- import my code in this project.

**Comment by kim3er** [comment]
Visual Studio 2015 14.0.25123.00 Update 2
NuGet Package Manager 3.4.3.855

Only noticed the problem, after updating site from .NET 4.5.1 to 4.6.1.

![screen shot 2016-05-18 at 15 29 37](https://cloud.githubusercontent.com/assets/250666/15362531/5e65cae6-1d0d-11e6-91d5-3dc7e99a020d.png)

**Comment by kim3er** [comment]
Fixed the issue, at least for me. For issue seems to be in the attributes used in a SLN file, for a Website (not Web Application).

These are the changes I made to the SLN:

```
Project("{...}") = "ProjectName", "http://localhost:1256", "...}"
```

Became:

```
Project("{...}") = "ProjectName", "ProjectName\", "{...}"
```

The following additions/deletions were made in the `ProjectSection`:

```
- UseIISExpress = "true"
- SlnRelativePath = "ProjectName\"
- DefaultWebSiteLanguage = "Visual Basic"
+ VWDPort = "1256"
```

**Comment by julielerman** [comment]
so I wasn't seeing things!!

**Comment by weloytty** [comment]
I had the same issue, and resolved it the same way kim3er did:

Changed

`Project("{...}") = "ProjectName", "http://localhost:1256", "...}"`

to
`
Project("{...}") = "ProjectName", "ProjectName\", "...}"`

**Comment by soroshsabz** [comment]
I had the same issue, and resolved it with close and reopen visual studio.

My visual studio is 2015 update 3
My nuget version is 3.5.0.1484

**Comment by hamed-mahdizadeh** [comment]
I had the same issue and I Solved my problem by changing order of External web tools location and restarting the VS 2015 

my nuget version: 3.3.0.167
vs version 2015 update 1

![image](https://cloud.githubusercontent.com/assets/10191772/20178907/8e9c6658-a768-11e6-9fd4-ea85bef7dbe6.png)

**Comment by simbo1905** [comment]
I had the same problem on Visual Studio 2017 Community Edition after adding then deleting a project from an existing solution. None of the suggested solutions above worked. As all the code was checked into Git at the point I was doing this so I just deleted everything and started again.

**Comment by agentgates** [comment]
I've got the same problem on Visual Studio 2017 Community Edition after cloning the following project: https://github.com/OrchardCMS/OrchardCore

**Comment by kaankeskin** [comment]
I had the same problem with Visual Studio 2019 Enterprise Edition. Closing and reopening the VS solved the problem.

**Comment by ned98** [comment]
Closing and reopening does not solve the problem for me.
