### ISSUE TITLE
DLLs being placed in root of solution

### ISSUE THREAD

**Issue by tjsimmons** [NuGet/Home#6040]
NuGet product used: NuGet/Package Manager Console

NuGet version (x.x.x.xxx): 3.3.0.212

VS version (if appropriate): 2017 15.4

OS version (i.e. win10 v1607 (14393.321)): Win7 SP1

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Create package with dependencies on MSTest.TestFramework and MSTest.TestAdapter

2. Install new package into a new solution

3. DLLs copied to root

...

### Verbose Logs

```
PM> install-package framework.unittests -Verbose
  GET https://customrepo/nuget/FindPackagesById()?id='framework.unittests'&semVerLevel=2.0.0
  OK https://customrepo/nuget/FindPackagesById()?id='framework.unittests'&semVerLevel=2.0.0 436ms

Attempting to gather dependency information for package 'framework.unittests.1.0.0' with respect to project 'Framework.Core.Tests', targeting '.NETFramework,Version=v4.5'
Package framework.unittests from source Custom gathered from cache.
  GET https://customrepo/nuget/FindPackagesById()?id='MSTest.TestAdapter'&semVerLevel=2.0.0
  GET https://customrepo/nuget/FindPackagesById()?id='MSTest.TestFramework'&semVerLevel=2.0.0
  OK https://customrepo/nuget/FindPackagesById()?id='MSTest.TestAdapter'&semVerLevel=2.0.0 37ms
  OK https://customrepo/nuget/FindPackagesById()?id='MSTest.TestFramework'&semVerLevel=2.0.0 228ms
Total number of results gathered : 8
Gathering dependency information took 249.64 ms
Summary of time taken to gather dependencies per source :
https://customrepo/nuget/	-	283.3 ms
ProjectRoot\Framework\Framework.Core.Tests\packages	-	22.55 ms
Attempting to resolve dependencies for package 'framework.unittests.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'framework.unittests.1.0.0'
Resolved actions to install package 'framework.unittests.1.0.0'
Retrieving package 'Framework.UnitTests 1.0.0' from 'Custom'.
For adding package 'Framework.UnitTests.1.0.0' to project 'Framework.Core.Tests' that targets 'net45'.
For adding package 'Framework.UnitTests.1.0.0' to project 'Framework.Core.Tests' that targets 'net45'.
Adding package 'Framework.UnitTests.1.0.0' to folder 'ProjectRoot\Framework\Framework.Core.Tests\packages'
Added package 'Framework.UnitTests.1.0.0' to folder 
'ProjectRoot\Framework\Framework.Core.Tests\packages'
Added package 'Framework.UnitTests.1.0.0' to folder 'ProjectRoot\Framework\Framework.Core.Tests\packages' from source 'https://customrepo/nuget/'
Added reference 'Framework.UnitTests' to project:'Framework.Core.Tests'. The Reference was Resolved To Package (resolvedToPackage):'True', where Reference Path from DTE(dteOriginalPath):'ProjectRoot\Framework\Framework.Core.Tests\packages\Framework.UnitTests.1.0.0.0\lib\net45\Framework.UnitTests.dll' and Reference Path from package reference(assemblyFullPath):'ProjectRoot\Framework\Framework.Core.Tests\packages\Framework.UnitTests.1.0.0.0\lib\net45\Framework.UnitTests.dll'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll' to project 
'Framework.Core.Tests'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll' to project 'Framework.Core.Tests'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll'.
Added file 'Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll' to project 'Framework.Core.Tests'.
Added package 'Framework.UnitTests.1.0.0' to 'packages.config'
Successfully installed 'Framework.UnitTests 1.0.0' to Framework.Core.Tests
```

### Sample Project

Unable to provide; here is the nuspec for the package in question

```xml
<?xml version="1.0"?>
<package>
  <metadata>
    <id>Framework.UnitTests</id>
    <version>1.0.0.0</version>
	<dependencies>
		<dependency id="MSTest.TestAdapter" version="1.2.0" />
		<dependency id="MSTest.TestFramework" version="1.2.0" />
	</dependencies>
  </metadata>
</package>
```

### Pictures Showing Issue
![b98a8cc8-7767-42cb-9240-ac932a85d90d](https://user-images.githubusercontent.com/303067/32177474-709337de-bd58-11e7-9bfd-935df89b7343.png)
![3179578b-f15b-4847-be65-4ebe14054cdb](https://user-images.githubusercontent.com/303067/32177475-70baf7d8-bd58-11e7-988d-20e81057e283.png)
![12c61e03-1cdd-4b1e-919c-54133d0f996f](https://user-images.githubusercontent.com/303067/32177476-70dde4dc-bd58-11e7-8466-6b244c709c9a.png)

**Comment by jainaashish** [comment]
@tjsimmons Can you provide more details on your issue? What do you mean by "Dlls being placed in root of solution"? And provide complete repro steps as well.

**Comment by tjsimmons** [comment]
The steps I gave are basically it. I can, later tonight, upload a test package to NuGet if needed. 

And, my work blocks uploading pictures so I'm going to try and attach from my mobile. The one that details what happens is the one showing the Solution Explorer. The three Microsoft.VisualStudio DLLs are placed in the root of the solution once the package is added.

**Comment by tjsimmons** [comment]
Okay. I added the pictures to the end; they give the workflow and detail the issue.

**Comment by jainaashish** [comment]
@tjsimmons please upload a test package to NuGet which depict this issue.

**Comment by tjsimmons** [comment]
@jainaashish Package has been uploaded. https://www.nuget.org/packages/tjsimmons.github.6040/1.0.0

**Comment by jainaashish** [comment]
I looked at this nupkg, since these 3 dlls are added under `content` folder inside this nupkg hence it's adding these directly under project. So if you remove the content folder then it should work fine.

**Comment by tjsimmons** [comment]
Good catch. I've tried this with a nupkg without that content folder, but encountered the same thing. I now think it's a caching issue - I uploaded, to our local repo, a version with an incremented ID and it behaved as expected.

How would I modify the nuspec to exclude those files, so I don't have to manually edit the archive every time? Every method I've tried didn't work.

**Comment by tjsimmons** [comment]
Nevermind - apparently, an empty `<files>` element does the trick. Thanks, @jainaashish

**Comment by kieronlanning** [comment]
@jainaashish / @tjsimmons I've this same issue.

Even with an empty `<files></files>` element, those three dll's are included in the package.

For reference, the package I'm creating is a microservices testing framework containing some base classes for unit tests in other internal solutions - the actual microservices themselves.
