### ISSUE TITLE
Build dependencies carry over to Nugetizer package

### ISSUE THREAD

**Issue by mhutch** [NuGet/Home#6041]
There is no way to stop library packages referenced by my project (such as Microsoft.Build.Framework) becoming dependencies of my package.

This is a big problem when I'm writing a build package, because it references Microsoft.Build.Framework), but I don't want that dependency to transfer to my consumers. I can't use PrivateAssets=All because I don't want the MSBuild assemblies _bundled_ into my output directory either. 

On possible fix would be `IsDevelopmentDependency=true` metadata on the `PackageReference`, it is not included as a dependency of the produced package. This is _orthogonal_ to whether/how the assets are consumed, as controlled by `PrivateAssets`. This could also be `Pack=false` for consistency with other item types, though that seems weird semantically.

I would also suggest that we default to this behavior when the primary output type is `build`.

**Comment by gravypower** [comment]
this is exactly what I was looking for this morning, is there any plans to include it?

**Comment by kzu** [comment]
Fixed and shipped in 0.3.0-beta of nugetizer.
