### ISSUE TITLE
NuGet pack of NuSpec with zero files includes a file

### ISSUE THREAD

**Issue by mistachkin** [NuGet/Home#6042]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 4.3.0.4406

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): win7 32-bit

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Given the NuSpec file "https://eagle.to/cgi-bin/eagle/artifact/cf172baed43cc869" with "1.0.X.X" replaced with the appropriate build number, use the "nuget pack" command.

2. Take note that the NuSpec file in question contains zero file elements.

3. However, when built inside the Eagle source code checkout, it ends up including the "Eagle.NuGet.targets" file.  This file is present in several directories during the build process; however, none of them are referenced from the above mentioned NuSpec file.

4. Perhaps I'm doing something wrong?  However, I do not understand how a NuSpec that refers to zero files can contain a file it should know nothing about.

### Sample Project

The Eagle Project is completely open source and a complete development snapshot can be downloaded at the following URL:

https://eagle.to/cgi-bin/eagle/zip/eagle-trunk.zip?uuid=a6739d074bfb1f0f

**Comment by mistachkin** [comment]
A couple more pieces of data:

1.  It appears to be picking up the "Eagle.NuGet.targets" file from the "Eagle\NuGet\build" directory.

2.  Renaming the directory to "build.out" caused it to include that directory name instead of "build".

3.  Renaming the targets file itself to "Eagle.NuGet.targets.foo" still causes it to include the file.

4.  Deleting the targets file causes it to include an empty "build" directory with a zero byte file named "\_.\_".

5.  Deleting the entire "build" directory, including the file, results in a correct NuGet package.

6.  The directory can be seen here "https://eagle.to/cgi-bin/eagle/dir?ci=trunk&name=Eagle/NuGet"

7. Changing the BasePath via the command line causes it to include *ALL* files within that directory.  This seems to be something of a security issue.  In my project, this generated a 420MB NuGet package file.

**Comment by mistachkin** [comment]
After carefully reviewing your client code, I believe that I've pinpointed the issue.  In the file "src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs", there is a method named "ReadManifest", which is called from several constructors.  It contains the following code:

```C#
private void ReadManifest(Stream stream, string basePath, Func<string, string> propertyProvider)
{
    // Deserialize the document and extract the metadata
    Manifest manifest = Manifest.ReadFrom(stream, propertyProvider, validateSchema: true);

    Populate(manifest.Metadata);

    // If there's no base path then ignore the files node
    if (basePath != null)
    {
        if (!manifest.HasFilesNode)
        {
            AddFiles(basePath, @"**\*", null);
        }
        else
        {
            PopulateFiles(basePath, manifest.Files);
        }
    }
}
```

Given this code in the context of this issue, it seems the base path, although not explicitly specified on the command line, is somehow being set to non-null (aside: is it even possible for it to be null at this point?).  Furthermore, there are no file nodes, which means the nested "if" statement is "true"; therefore, all files are being added to the resulting NuGet package.

**Comment by rohit21agrawal** [comment]
yes. that is expected behavior - if you really want no files in your package, specify an empty files node in your nuspec otherwise it will include files as per convention : https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

**Comment by mistachkin** [comment]
Adding hundreds of megabytes of files simply because an empty element is missing in the NuSpec file?  Also, it appears that the documentation you linked to is talking about the "nuget spec" command, not the "nuget pack" command.
