### ISSUE TITLE
nuget.exe list -allversions doesn't work

### ISSUE THREAD

**Issue by SurajGupta** [NuGet/Home#6044]
Here's a write-up of the issue:
https://stackoverflow.com/questions/46777920/nuget-exe-doesnt-return-all-versions-of-specified-package

As such, there's no way to list all versions, which is a serious handicap when it comes to managing and building features against a gallery.

**Comment by joelverhagen** [comment]
This is a known issue and a bug on NuGet.org.
Existing server bug: https://github.com/NuGet/NuGetGallery/issues/3274
Existing client bug: https://github.com/NuGet/Home/issues/3441

**Comment by SurajGupta** [comment]
These bugs were opened over a year ago and I think the issue has existed for longer than that based on some bugs I've seen in the old repo.  This seems like a pretty serious deficiency - there are categories of scenarios that just don't work without being able to retrieve all versions of a package.  I think the severity is pretty obvious - I mean there are only a handful of core features that anyone designing a package management system would solve for day 1 and this seems like one of them.  Can this issue be escalated?  What's the ETA on a fix?

**Comment by joelverhagen** [comment]
Escalation seems quite reasonable to me. Let's try again 😄!

@skofman1, @rrelyea - could we escalate this one? I believe this is a server-side only fix.

**Comment by jainaashish** [comment]
Thanks for the feedback. But closing this issue as dupe, please follow already logged issues for this and up-vote there to increase priority. It will also help if you elaborate on your specific scenario for the need of this feature.
