### ISSUE TITLE
Add new project system extensibility for nuget

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6046]
we have some asks from customer about how to add new project system to nuget. we should provide an API for new project system extensibility

**Comment by jainaashish** [comment]
I think we need to thoroughly design this feature and properly spec out, since who will take the responsibility to support that new Project System after it's been supported and like-wise there will be many other critical pieces.

**Comment by rrelyea** [comment]
@zhili1208 - let's discuss this please. want to understand more details about the feature need here.

**Comment by zkat** [comment]
Not much context on this one and there doesn't seem to be much of a push for it, so I'm closing it.
