### ISSUE TITLE
Configure.PS1 fails downloading .NET CLI - Can't build

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#6049]
After cloning the NuGet.Client repo and following the instructions to configure for a build.  Configure.PS1 fails when attempting to download the .NET CLI.  The output from the Powershell console is below:

`PS D:\Reference Source\Microsoft\nuget\nuget.client> .\configure.ps1
[17:10:09 +0]   Configuring NuGet.Client build environment
[17:10:09 +0]   [BEGIN] Configuring git repo
[17:10:09 +0]   [DONE +00:00:00] Configuring git repo
[17:10:09 +0]   [BEGIN] Installing NuGet.exe
NuGet Version: 4.0.0.2283
http-cache: C:\Users\spmys\AppData\Local\NuGet\v3-cache
global-packages: C:\Users\spmys\.nuget\packages\
temp: C:\Users\spmys\AppData\Local\Temp\NuGetScratch
[17:10:09 +0]   [DONE +00:00:00] Installing NuGet.exe
[17:10:09 +0]   [BEGIN] Installing .NET CLI
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   D:\Reference Source\Microsoft\nuget\nuget.client\cli1.0.4\sdk\1.0.1
[17:10:10 +0]   Downloading .NET CLI
Error-Log : [17:10:13 +3]    [FAILED +00:00:03] Installing .NET CLI
At D:\Reference Source\Microsoft\nuget\nuget.client\build\common.ps1:142 char:17
+ ...             Error-Log "[FAILED +$(Format-ElapsedTime $sw.Elapsed)] $B ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Error-Log

Exception calling "Invoke" with "0" argument(s): "Failed to download
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.0/latest.version."
At D:\Reference Source\Microsoft\nuget\nuget.client\cli\dotnet-install.ps1:106 char:20
+             return $ScriptBlock.Invoke()
+                    ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException

PS D:\Reference Source\Microsoft\nuget\nuget.client>`

Any thoughts on what the issue is and how to resolve it?

Thanks

-marc

**Comment by jainaashish** [comment]
Created a bug for dotnet cli - https://github.com/dotnet/cli/issues/7867
