### ISSUE TITLE
Hang/Fail to install issue EF 7 packages on .NET 4.6 project

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#605]
See more details here https://github.com/aspnet/EntityFramework/issues/2209

This might be EF issue with the packages, but we should definitely not be stuck for 5+ minutes try to figure out the graph.

Is this a dup of the unlisted issue?

**Comment by yishaigalatzer** [comment]
CC @julielerman

**Comment by julielerman** [comment]
thx

**Comment by yishaigalatzer** [comment]
This seems to repro also with Beta4 packages on the latest bits. But not with Beta5 (we just see the IX failing to add a reference correctly)

**Comment by rowanmiller** [comment]
I was just playing around with this (using the public VS2015 RC bits) and was seeing the hang when installing latest builds from the aspnetvnext myget feed but not when installing from build server share. 

Not sure how that plays into anything but thought I'd mention it incase it helps isolate the issue. BTW for me the Beta4 packages on NuGet.org install without the hang (though it sounds like others do see the hang for that scenario).

**Comment by yishaigalatzer** [comment]
@johnataylor I believe this is fixed? Can you resolve?

**Comment by rowanmiller** [comment]
@johnataylor do we have a workaround folks can use with the currently public bits (VS2015 RC) to install our nightly packages?

**Comment by julielerman** [comment]
thanks for continuing to try this, Rowan. I've been unable to work since Sunday so haven't had a chance to check status beyond these comments on GH. WHy closed, though, @johnataylor?

**Comment by johnataylor** [comment]
Playing with the problem a little, I found that if I installed a couple of the dependencies independently it worked fine.

For example, EF depends on EF.Cmds which, in the 4.5 case, depends on five other packages. I tried installing a couple of these first, explicitly, then the went back and installed EF and it worked.

I can't remember the exact ones I tried but I think it was something like:
Microsoft.CodeAnalysis.CSharp 1.0.0-rc2
then:
EntityFramework.Relational.Design 7.0.0-beta4
then finally
EntityFramework 7.0.0-beta4

maybe this can even be simplified.

**Comment by johnataylor** [comment]
This should be fixed in future builds. The above "manual" work around is for the RC bits.

**Comment by yishaigalatzer** [comment]
Closed because it is fixed.

**Comment by julielerman** [comment]
Ahh got it, thanks!

**Comment by rowanmiller** [comment]
Thanks guys, I'll distill down the workaround and add it to the issue in the EF repo.

**Comment by rowanmiller** [comment]
@johnataylor did you also verify installing EntityFramework.SqlServer from the nightly ASP.NET 5 feed? I was seeing that fail on more machines than installing Beta4 from nugget.org.

```
PM> Install-Package EntityFramework.SqlServer -Pre -Source https://www.myget.org/F/aspnetvnext/api/v2
```
