### ISSUE TITLE
Examples on how to use NuGet API?

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#6050]
I'm trying to integrate the API into an internal auto application update tool.

I'm having the following issues:
1) Determine the correct combination of Nuget API packages to install?
2) Determine how to use the API? I've reviewed the articles by [Dave Glick](https://daveaglick.com/posts/exploring-the-nuget-v3-libraries-part-2). However, I'm still having issues.  For example, when I execute this line of code: 
`PackageMetadataResource packageMetadataResource = await sourceRepository.GetResourceAsync<PackageMetadataResource>();
`
The call to GetResourceAsync returns a null object.  

I don't know what it doesn't like. I'm only using the V2 protocol, and I have validated that the URL to my internal Nuget feed is correct.

Thanks

-marc

**Comment by jainaashish** [comment]
Can you share us the full code you wrote to make sure you've added the right provider and package source? And list NuGet packages and their versions you're using to get this working.

**Comment by mhsimkin** [comment]
I tried to close this earlier today.  I guess it didn't take.

I was using the 3.X packages.  When I changed to only use the 4.X packages and only use the V3 protocol, my issues were resolved.

Thanks

-marc
