### ISSUE TITLE
Localize string resources in nuget.exe

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6051]
we are currently adding new commands to nuget.exe. Currently these strings are not being localized. we should fix this before shipping.

**Epic tasks**

- https://github.com/NuGet/Client.Engineering/issues/1757
- https://github.com/NuGet/Client.Engineering/issues/1804
- https://github.com/NuGet/Client.Engineering/issues/1771
- https://github.com/NuGet/Home/issues/12066
- https://github.com/NuGet/Home/issues/12067

**Comment by nkolev92** [comment]
@rrelyea assigned it you as you are actively working on this.

**Comment by rrelyea** [comment]
We've started to fix this as part of https://github.com/NuGet/NuGet.Client/pull/3206.
However, to fix completely, we'd have to also start creating nuget.resource.dll for each language and then merge it. (also delete a bunch of strings).
We should do this soon.

**Comment by nkolev92** [comment]
Team Triage: Assigning to @dominoFire

**Comment by dominoFire** [comment]
Started localization onboarding with loc team.

**Comment by dominoFire** [comment]
Created issue to add nuget.exe to localization artifacts.  https://github.com/NuGet/Client.Engineering/issues/1757

**Comment by dominoFire** [comment]
All subtasks are completed. Closing this issue.
