### ISSUE TITLE
[Doc] Need to reopen solution to update nuget UI after change NuGet.config manully or add new NuGet.config

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6055]

**Comment by karann-msft** [comment]
doc issues should always include: 
•	Additional details information on the issue at hand (e.g. a doc request for some flag or option should include at least a rough description of what it does),
•	Pointers to where we can find such information, and/or
•	The name of the appropriate subject-matter experts who can provide such information.

In short, it’s very difficult to write documentation without suitable details, and it’s a poor use of our time to be hunting down the appropriate people and details. So help us by shortcutting the process and providing the information up front. 

If you want to shortcut even further, you’re always welcome to just brain-dump into some file in a branch, from which Kraig and I can work to bring the material up to publish quality. Edits are especially great for correcting small details, and working through PRs is most efficient.

**Comment by nkolev92** [comment]
This is currently documented. 
We're gonna work on https://github.com/NuGet/Home/issues/1538 instead.
