### ISSUE TITLE
consider how documentation.md can be specified in nuspec via URL (or embedded file??)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#6056]
NuGet.org supports a documentation markdown file to be specified by the owner of a package.
How should we support this via csproj file settings, pack, etc...

@chenriksson @anangaur

**Comment by matthidinger** [comment]
I love this, and was literally just looking up the nuspec docs if such a feature existed. I was expecting something like this in my .csproj:
   

```xml
<DocumentationMarkdownUrl>https://raw.githubusercontent.com/MicrosoftDocs/AdaptiveCards/master/AdaptiveCards/create/libraries/NET.md</DocumentationMarkdownUrl>
```

**Comment by anangaur** [comment]
@matthidinger So should it keep changing based on the content that changes on the github URL? 

IMO this should be a way to get the contents and the snapshot of the content is stored at NuGet gallery.

Also both relative path vs. public https based URL should be acceptable.
```xml
<DocumentationMarkdownURL>https://raw.githubusercontent.com/MicrosoftDocs/AdaptiveCards/master/AdaptiveCards/create/libraries/NET.md</DocumentationMarkdownURL>
```
OR
```xml
<DocumentationMarkdownURL>documenation/myMarkDown.md</DocumentationMarkdownURL>
```

**Comment by joo92** [comment]
@matthidinger I have face same issue while update documentation URL in Nuspec file. I can’t able to use markdown file gitlab or public URL in Nuspec file.
Can we use only https://raw.githubusercontent.com site(GitHub URL) for set markdown file as documentation URL ? else can we use public  or GitLabURL?

Please suggest steps to use gitlab or public URL make documentation URL.

**Comment by bruno-garcia** [comment]
I agree with @anangaur that a snapshot for the specific package seems like the best call. Convention based by picking up a file named 'Documentation.md' or having the exact file name specified via nuspec/csproj for example.

URL-based solution would more likely point to the repo at some branch which might bet deleted and projects move around to different repos/renamed. I've [raised that on SO](https://stackoverflow.com/questions/47497923/push-markdown-documentation-to-nuget-org) a couple of months ago. Would be happy to find a solution.

**Comment by nkolev92** [comment]
Supported with READMEs https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
