### ISSUE TITLE
NuGet should Avoid other VS extension call NuGet APi unless they are IvsAPIs in nuget.visualStudio

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6058]
From internal VSTS issue 484785
Issue around this:

Extension authors who depend on the NuGet APIs should never include the NuGet DLLs in their VSIX. Otherwise it might hit VS InvalidMEFCacheException because NuGet DLL version in memory doesn't match the version in MEFCache.

What we can do:
1. Provide codebase https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.providecodebaseattribute.aspx. for every nuget dlls in VS Extension, it will ensure NuGet DLLs always loads from extension directory.

2. Add NuGet dlls to suppressionList then other extension author can't include nuget dlls in their extension.

3.we should probably add the DLLs to the vsix suppression list that exists in the vssdk.targets themselves (extension developers have to reference the VSIXSuppression nuget package in order to get the suppression from the targets in step 2) – if you can send me the list of DLLs that extension authors may reference, that would be great – I can add them to the suppression list.

We found some VS extensions which include nuget dlls in their extension from VS marketplace for VS2017
 
Episerver CMS Visual Studio Extension
Sitecore Rocks
Sitrion ONE AppBuilder
DotVVM for Visual Studio
Package Licenses
Nexus IQ for Visual Studio

**Comment by kzu** [comment]
You could also extend the VSIX supresssion list from your own nuget.visualstudio package-provided targets instead and keep control of what gets excluded.

It might also be a good idea to providing binding redirects, so that those extensions keep working as the main extension revs its version.

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/Home/issues/9611 as that one is reacher with a lot more details.
