### ISSUE TITLE
Support for dotnet search command (equivalent to nuget.exe list, later search)

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6060]
_From @Kemyke on October 19, 2017 13:29_

## Steps to reproduce
There is no substituting functionality for 'nuget.exe list' feature. That would be great if it would be possible to use the dotnet CLI for automation on every platform. Currently the mono should be installed on Ubutnu to run nuget.exe. Is there a plan to add all the missing functionality to the dotnet CLI?

## Expected  behavior
dotnet nuget list <Filter expression>

## Actual behavior
There is no funcionality in the dotnet CLI to list the available packages.

_Copied from original issue: dotnet/cli#7869_

**Comment by rrelyea** [comment]
in talks with CLI team for proper design for dotnet.exe (may be dotnet search packages ...)

**Comment by divinebovine** [comment]
@rrelyea any chance that this will get looked at in next quarter or so? Adding this capability would help with some of our automation pipelines.

**Comment by rrelyea** [comment]
Shipped this in dotnet sdk 2.2.100.

**Comment by John0King** [comment]
@rrelyea  I think the current `dotnet list` is not the proposal  of this issue.
this issue is about search nuget package in nuget.org , and the current command `dotent list` is about list the reference of current project.
Should this issue be reopen ?

**Comment by nkolev92** [comment]
Related issue: https://github.com/nuget/home/issues/8040

**Comment by anangaur** [comment]
`dotnet tool search` command already works now with .NET 5. Obviously it applies a filter to search results. So can't we use that code to remove filter and support `dotnet packager search`? Its odd that too search is available but not regular NuGet package search :)

![image](https://user-images.githubusercontent.com/14800916/83419346-c9f92300-a3d9-11ea-9ddb-35921070324d.png)

**Comment by John0King** [comment]
today, on Devbog https://devblogs.microsoft.com/nuget/getting-started-with-nuget-5-8/  ,  it saids that now nuget.exe support  `nuget search` ,  but no `dotnet nuget search`

**Comment by John0King** [comment]
nobody care ?

**Comment by JonDouglas** [comment]
We do care. We do not have a formal spec for `dotnet package search` or `dotnet nuget search`, but when we do, you can check out our proposals in our repository & we'll notify all those in related issues.

**Comment by John0King** [comment]
this is really nobody cared！！！！！！
`nuget.exe search`  https://docs.microsoft.com/zh-cn/nuget/reference/cli-reference/cli-ref-search 
have been implemented a year ago,  and `dotnet cli`  still don't have this  command.

related: 
https://github.com/dotnet/sdk/issues/9675    >> dotnet sdk  repo issue
https://github.com/NuGet/Home/issues/7217   >> moved to nuget
https://github.com/NuGet/Home/issues/6060   >> referenced  by #7217

it's a total year I mean.

**Comment by red8888** [comment]
Just want to add the community tool `dotnet-search` is frequently referenced as a workaround, but it doesn't support specifying sources and doesn't read the system config for auth so its not usable- the repo is also 3 years old.

https://github.com/billpratt/dotnet-search

**Comment by hiredgunhouse** [comment]
Wow, in just over 4 months it will be 5 YEARS!!! since this issue has been created. 
How long does it take Microsoft to implement such an obvious feature that should have been there from the start?
I am speechless :)
BTW. This death by 1000 cuts all over the place makes me seriously consider ditching .NET for Java or Node.js. 
C# is pretty great language but the platform and developer experience is far from optimal and we developers need both.

**Comment by pflannery** [comment]
This would be a great feature. It would remove some complexity from the [versionlens vscode extension](https://gitlab.com/versionlens/vscode-versionlens) and would enable authentication without trying to fetch usernames and passwords for multiple sources on a "no need to know basis"

**Comment by JauniusPinelis** [comment]
This is really needed for better .NET development experience in VSCode. Hope this will be completed soon.

**Comment by boggylp** [comment]
Any plans on prioritising this? It's been an open issue for ~ 6 years now

**Comment by JonDouglas** [comment]
Folks...this is almost live! 🤩🚢
