### ISSUE TITLE
nuget.exe update doesn't update only when -id is specified

### ISSUE THREAD

**Issue by Kittyfisto** [NuGet/Home#6064]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.3.0.4406

OS version: win7 SP1

## Detailed repro steps so we can see the same problem

1. Have an artifactory instance registered as nuget package source

2. Push any package to artifactory (nuget push ...)

3. Create C# project (and solution) which references the previously package (Step 2.)

4. Push a newer package version to artifactory

5. using nuget.exe, run the following command:
nuget.exe update <Your Solution> -Source <Name For Artifactory Package Source> -Id <Your Package>

Current behavior: nuget will not find find the newer version and NOT install it.
Expected behaviour: nuget should update the package since a newer version is clearly available

This problem does NOT occur when I remove the "-Id ..." parameter, as I will proof using two excerpts below:

> C:\Snapshots\Redacted>**"..\Redacted\nuget.exe" update Foo.sln -Source Artifactory -Id Bar -Verbosity detailed**
NuGet Version: 4.3.0.4406
Scanning for projects...
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to us
e a specific version of MSBuild.
Found 2 projects with a packages.config file. (Foo.csproj, Foo.Test.csproj)
Looking for installed packages in 'packages'.
Feeds used:
  https://artifactory.redacted.net/api/nuget/redacted

> Attempting to gather dependency information for multiple packages with respect to project 'C:\Snapshots\Redacted\Foo\Foo.csproj', targeting '.NETFramework,Version=v4.5'
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0 10ms
Total number of results gathered : 4
Gathering dependency information took 1,82 sec
Summary of time taken to gather dependencies per source :
https://artifactory.redacted.net/api/nuget/redacted -       84,85 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'C:\Snapshots\Redacted\Foo\Foo.csproj'.
Executing nuget actions took 4,36 ms
Feeds used:
  https://artifactory.redacted.net/api/nuget/redacted

> Attempting to gather dependency information for multiple packages with respect to project 'C:\Snapshots\Redacted\Foo.Test\Foo.Test.csproj', targeting '.NETFramework,Version=v4.5'
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Foo'&semVerLevel=2.0.0
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Foo'&semVerLevel=2.0.0 10ms
Total number of results gathered : 9
Gathering dependency information took 30,57 ms
Summary of time taken to gather dependencies per source :
https://artifactory.redacted.net/api/nuget/redacted -       19,02 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'C:\Snapshots\Redacted\Foo.Test\Foo.Test.csproj'.
Executing nuget actions took 0,18 ms

And now without the -Id parameter:

> C:\Snapshots\Redacted>"..\8NT_Tools_Build\BuildTools\nuget.commandline 4.0.0\nuget.exe" update Foo.sln -Source Artifactory -Verbosity detailed
NuGet Version: 4.3.0.4406
Scanning for projects...
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to us
e a specific version of MSBuild.
Found 2 projects with a packages.config file. (Foo.csproj, Foo.Test.csproj)
Looking for installed packages in 'packages'.
Feeds used:
  https://artifactory.redacted.net/api/nuget/redacted

> Attempting to gather dependency information for multiple packages with respect to project 'C:\Snapshots\Redacted\Foo\Foo.csproj', targeting '.NETFramework,Version=v4.5'
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='log4net'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0 12ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='log4net'&semVerLevel=2.0.0 15ms
Total number of results gathered : 4
Gathering dependency information took 347,18 ms
Summary of time taken to gather dependencies per source :
https://artifactory.redacted.net/api/nuget/redacted -       434,08 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Found package 'log4net 2.0.8' in 'C:\Snapshots\Redacted\packages'.
Found package 'Bar 1.1.219-alpha' in 'C:\Snapshots\Redacted\packages'.
Removed package 'Bar 1.1.216-alpha' from 'packages.config'
Successfully uninstalled 'Bar 1.1.216-alpha' from Foo.csproj
Removed package 'log4net 2.0.3' from 'packages.config'
Successfully uninstalled 'log4net 2.0.3' from Foo.csproj
For adding package 'log4net.2.0.8' to project 'Foo.csproj' that targets 'net45'.
For adding package 'log4net.2.0.8' to project 'Foo.csproj' that targets 'net45'.
Package 'log4net.2.0.8' already exists in folder 'C:\Snapshots\Redacted\packages'
Added package 'log4net.2.0.8' to 'packages.config'
Successfully installed 'log4net 2.0.8' to Foo.csproj
For adding package 'Bar.1.1.219-alpha' to project 'Foo.csproj' that targets 'net45'.
For adding package 'Bar.1.1.219-alpha' to project 'Foo.csproj' that targets 'net45'.
Package 'Bar.1.1.219-alpha' already exists in folder 'C:\Snapshots\Redacted\packages'
Added package 'Bar.1.1.219-alpha' to 'packages.config'
Successfully installed 'Bar 1.1.219-alpha' to Foo.csproj
Executing nuget actions took 331,84 ms
Feeds used:
  https://artifactory.redacted.net/api/nuget/redacted

> Attempting to gather dependency information for multiple packages with respect to project 'C:\Snapshots\Redacted\Foo.Test\Foo.Test.csproj', targeting '.NETFramework,Version=v4.5'
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='log4net'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Moq'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='NUnit'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='FluentAssertions'&semVerLevel=2.0.0
  GET https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Castle.Core'&semVerLevel=2.0.0
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='log4net'&semVerLevel=2.0.0 21ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Bar'&semVerLevel=2.0.0 22ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Moq'&semVerLevel=2.0.0 24ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='FluentAssertions'&semVerLevel=2.0.0 26ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='NUnit'&semVerLevel=2.0.0 26ms
  OK https://artifactory.redacted.net/api/nuget/redacted/FindPackagesById()?id='Castle.Core'&semVerLevel=2.0.0 26ms
Total number of results gathered : 9
Gathering dependency information took 50,29 ms
Summary of time taken to gather dependencies per source :
https://artifactory.redacted.net/api/nuget/redacted -       295,95 ms
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Found package 'log4net 2.0.8' in 'C:\Snapshots\Redacted\packages'.
Found package 'Bar 1.1.219-alpha' in 'C:\Snapshots\Redacted\packages'.
Removed package 'Bar 1.1.216-alpha' from 'packages.config'
Successfully uninstalled 'Bar 1.1.216-alpha' from Foo.Test.csproj
Removed package 'log4net 2.0.3' from 'packages.config'
Successfully uninstalled 'log4net 2.0.3' from Foo.Test.csproj
For adding package 'log4net.2.0.8' to project 'Foo.Test.csproj' that targets 'net45'.
For adding package 'log4net.2.0.8' to project 'Foo.Test.csproj' that targets 'net45'.
Package 'log4net.2.0.8' already exists in folder 'C:\Snapshots\Redacted\packages'
Added package 'log4net.2.0.8' to 'packages.config'
Successfully installed 'log4net 2.0.8' to Foo.Test.csproj
For adding package 'Bar.1.1.219-alpha' to project 'Foo.Test.csproj' that targets 'net45'.
For adding package 'Bar.1.1.219-alpha' to project 'Foo.Test.csproj' that targets 'net45'.
Package 'Bar.1.1.219-alpha' already exists in folder 'C:\Snapshots\Redacted\packages'
Added package 'Bar.1.1.219-alpha' to 'packages.config'
Successfully installed 'Bar 1.1.219-alpha' to Foo.Test.csproj

You can clearly see that nuget.exe doesn't have any problem updating the Foo package when I omit the Id parameter, however I do not want to do that because nuget.exe updates packages I most certainly do NOT want to be updated, hence my usage of this parameter.

**Comment by jainaashish** [comment]
@Kittyfisto Please provide more details:
- Can you also repro this issue with latest nuget.exe version 4.4.0?
- Did it worked any of the previous release?
- Can you also repro this issue for any other source like default NuGet.org?

**Comment by Kittyfisto** [comment]
@jainaashish 

I've downloaded nuget 4.4.0 from https://www.nuget.org/downloads and it also refuses to update the dependencies when I specify the "Id" command-line parameter.  
I've never gotten it to work, and tested it with versions 4.0.0, 4.3.0 and 4.4.0.  
I'll have to setup a smaller test case to reproduce this issue with nuget.org as a package source, it'll take a few hours and I'll report back with the results.

**Comment by mishra14** [comment]
@Kittyfisto Since you are working with prerelease packages, you should use the `-Prerelease` flag.

e.g. - 

`nuget.exe" update Foo.sln -Source Artifactory -Id Bar -Verbosity detailed -Prerelease`

Please let us know if you are still blocked.

**Comment by Kittyfisto** [comment]
Just in case other's stumble upon the same problem: -Prerelease indeed solved my problem. Guess I didn't properly read the manual, my bad. Thanks a bunch!
