### ISSUE TITLE
Perf lab

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#6067]
- [x] 1. signing measurements and scenarios.
- [x] 2. understand and start running Perf lab XAML infrastructure
- [x] 3. Create NuGet perf tests based on XAML infrastucture and run locally
- [ ] 4. Integrate NuGet perf tests to be run in Maddog
- [x] 5. Innerloop perf

**Comment by jainaashish** [comment]
We completed some of these task (1,2,5) in 4.6 - oct24-Nov11 but stll left with other open tasks so will continue to make progress there in current sprint.

**Comment by jainaashish** [comment]
I was able to run a initial NuGet specific perf test on a local box but it's still not able to measure performance which might needs specific ETW events instead of just telemetry events. So still needs to look into that and work with VS telemetry team.

**Comment by jainaashish** [comment]
I'm able to run a initial NuGet perf test locally and measure performance with telemetry events.

Next ask is to run this test in maddog environment which also requires our nuget specific vs branch to be building.

**Comment by jainaashish** [comment]
It was blocked since VS was upgrading msbuild tooling so no work was done in Sprint130. Will pick it as soon as some bandwidth is available.

**Comment by rohit21agrawal** [comment]
made good progress,  should continue to work on it when we get the time.

**Comment by nkolev92** [comment]
@srdjanjovcic has been working on this. 

Closing this old issue in favor of https://github.com/NuGet/Client.Engineering/issues/302
