### ISSUE TITLE
Installing NuGet packages with readme.txt does not open the readme.txt

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#607]
Per [the documentation on readme.txt](http://docs.nuget.org/create/Creating-and-Publishing-a-Package#automatically-displaying-a-readme.txt-file-during-package-installation), a nupkg that carries a readme.txt in its root directory should result in that readme.txt being displayed to the user when that package is directly installed. This works in NuGet 2.8 but not in 3.0.

**Comment by yishaigalatzer** [comment]
Repro steps?

**Comment by AArnott** [comment]
Sure: run this command in the NuGet Console window:

    Install-Package Nerdbank.GitVersioning -Pre

**Comment by AArnott** [comment]
This repros on VSPro_Platform 22912.00

**Comment by yishaigalatzer** [comment]
What kind of project, what framework?

**Comment by AArnott** [comment]
C# console app. .NET 4.5

**Comment by mplessis** [comment]
I use client NuGet v3.1.6 in my VS2015 and this issue is still present. That this issue is resolved in another version of V3.1.x please or only from a v3.2?

**Comment by yishaigalatzer** [comment]
This does work with the 3.1.x releases, but only for packages.config scenarios. If you are developing a UWP app, it doesn't yet work.

**Comment by mplessis** [comment]
Ok thanks you, the project is UWP. We are waiting.
