### ISSUE TITLE
Long term support strategy for NuGet to support packages without providing a bad package upgrade experience for users.

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#6070]
Long term support strategy for NuGet to support packages without breaking

**Comment by jainaashish** [comment]
Synced with Azure team for thei LTS support, and their scenarios can be accomplished with `Tag` or `Description` fields, instead of having a separate field to Azure SDK API versions.

**Comment by mishra14** [comment]
closing as we are done from our side.

**Comment by jainaashish** [comment]
We had another discussion here with ASP.NET team and after the design discussion, we agreed that we don't need anything from NuGet here, they can use existing features like Version range and private assets to restrict package update.
