### ISSUE TITLE
Clarify on nuget.org/downloads that VS 2017 doesn't include nuget.exe

### ISSUE THREAD

**Issue by kraigb** [NuGet/Home#6078]
nuget.org/downloads has the following text:

> NuGet 4.x is included in the Visual Studio 2017 version 15.x installation. Latest NuGet releases are delivered as part of Visual Studio updates.
> Batteries are included!

However, this is not entirely accurate, as VS does not include nuget.exe specifically, which is implied by the text and its placement on the page. At least one customer was confused by this (submitted a PR to edit the installer docs on docs.microsoft.com).

I recommend the following edits:

> The NuGet 4.x Package Manager UI and Package Manager Console are included with Visual Studio 2017 (all 15.x versions). Latest NuGet releases are delivered as part of Visual Studio updates.
> However, the nuget.exe CLI itself is not included with any version of Visual Studio. Download the latest version of the CLI using the links to the left, storing the .exe (which is nuget.exe) to a suitable location.

**Comment by karann-msft** [comment]
https://stackoverflow.com/questions/43326748/nuget-cli-in-visual-studio-2017-how-to-run

**Comment by karann-msft** [comment]
Fixed.
@kraigb please a take a look and if it looks good, close the issue :)
