### ISSUE TITLE
Why is packages.config build action set to content by default ?

### ISSUE THREAD

**Issue by rekna1** [NuGet/Home#608]
This makes packages.config go with publish. Shouldn't it be better to set default build action to None?

**Comment by yishaigalatzer** [comment]
That's a good idea, we are going to take a look if it can be reliably changed.

**Comment by yishaigalatzer** [comment]
We should also update nuget 2.X

**Comment by thomaswr** [comment]
Oh yes please. It also resets back to "Content" on Update-Package -reinstall.

**Comment by yishaigalatzer** [comment]
Just verified in 3.3, it is set a none.

![image](https://cloud.githubusercontent.com/assets/1238711/10861165/b2105c32-7f34-11e5-9eb2-6e6ff78d77c0.png)
