### ISSUE TITLE
Cannot disable NuGet behavior in existing project

### ISSUE THREAD

**Issue by ridomin** [NuGet/Home#6080]
As a workaround for #6079 we tried to disable NuGet targets in the wapproj using

```xml
    <ResolveNuGetPackages>false</ResolveNuGetPackages>
    <SkipImportNuGetProps>true</SkipImportNuGetProps>
    <SkipImportNuGetBuildTargets>true</SkipImportNuGetBuildTargets>
```

However, these properties have no effect on the `msbuild /t:restore` and the build still fails

**Comment by mishra14** [comment]
@ridomin what is the exact failure that you see. Can you please give us the logs/error that you get?

**Comment by rrelyea** [comment]
these msbuild properties are not ours. So it is understandable that it didn't stop nuget.
Let's close this issue, as fundamentally, we shouldn't ever need to do this.
