### ISSUE TITLE
Certificate error on https://nuget.smbsrc.net

### ISSUE THREAD

**Issue by FeodorFitsner** [NuGet/Home#6082]
Getting an error while pushing symbols package with NuGet 4.1 command-line client on Windows:

```
An error was encountered when fetching 'PUT https://nuget.smbsrc.net/'. The request will now be retried.
An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.
```

Opening https://nuget.smbsrc.net in the browser confirms the problem with certificate.

**Comment by mishra14** [comment]
cc @skofman1

**Comment by anangaur** [comment]
@FeodorFitsner, thanks for letting us know. We have passed on this information/feedback to SymbolSource.org.

**Comment by fredericDelaporte** [comment]
As written [here](https://stackoverflow.com/a/46941071/1178314), it is possible to work around this certificate expiration by going through http instead...

>```
>nuget push dist/MyPackage.1.0.0.symbols.nupkg -Source http://nuget.smbsrc.net  -ApiKey [my key]
>```

Of course this then means the thing goes un-encrypted over the Internet, likely the API key too. (Unless some application level ciphering is done by NuGet on it.)

**Comment by FeodorFitsner** [comment]
Is there any update guys? I can't believe installing a new certificate could take so long. Is there any way to approach SymbolSource.org maintainers directly?

**Comment by pavkam** [comment]
Still errs out. Any progress?

**Comment by rrelyea** [comment]
We have passed this info to the symbolsource folks, but haven't gotten a response.

**Comment by mishra14** [comment]
Folks, please see https://github.com/NuGet/Home/issues/6101 for a potential fix to this problem.

**Comment by anangaur** [comment]
@mishra14 that's not a fix to the problem but rather a way out to not **fail** CI builds on secondary push to SymbolSource. 
However, the auto-push experience is **not right** especially in **failure** scenarios. There is another proposal to disintegrate the current overloaded `push` to just do an atomic operation of pushing packages to one source: https://github.com/NuGet/Home/issues/6113
If we implement https://github.com/NuGet/Home/issues/6113, I feel https://github.com/NuGet/Home/issues/6101 would no longer be required.

**Comment by FeodorFitsner** [comment]
Looks like the certificate was updated.

**Comment by anangaur** [comment]
Closing this issue now as the cert was renewed. Nevetheless, we plan to stop auto-push of packages to SymbolSource as announced here: https://github.com/NuGet/Announcements/issues/13

**Comment by evadelnuevo** [comment]
It seems the certificate expired again

**Comment by bilal-fazlani** [comment]
It's expired again

**Comment by FeodorFitsner** [comment]
Yep, publishing of symbol packages from AppVeyor builds is not working.

**Comment by skofman1** [comment]
If you are publishing portable PDBs take a look at the NuGet hosted Symbol server: https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by CarlosLanderas** [comment]
We are having trouble as well

**Comment by unaizorrilla** [comment]
One year later, certificate is expired again....

**Comment by yevhen** [comment]
C'mon ((

**Comment by JoshClose** [comment]
Use @skofman1's suggestion. That worked for me.

**Comment by FeodorFitsner** [comment]
@skofman1 Am I correct to assume `.snupkg` is doable from/with VS 2017 only or is it the latest `nuget.exe` that works with VS 2015 too?

**Comment by skofman1** [comment]
@FeodorFitsner , the blog provides all the details on this. You will need to build your code using VS 2017 15.9 to generate the PDBs. There were changes to the compiler in 15.9 that are required.

**Comment by FeodorFitsner** [comment]
OK, what about VS 2015 support with "old" symbol packages?

**Comment by JoshClose** [comment]
I'm using VS 2015 but building with `dotnet pack` using the latest dotnet core.

**Comment by FeodorFitsner** [comment]
Right, but I'm talking about "traditional" .NET Framework apps.

**Comment by JoshClose** [comment]
I build netstandard2.0 and net 45 using `dotnet pack`
```xml
<TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
```

**Comment by weitzhandler** [comment]
Same problem here.

**Comment by fredericDelaporte** [comment]
In other words, the certificate has expired again. That is the third time it expires without being renewed on time. Isn't this slightly deceptive?

**Comment by anangaur** [comment]
Checkout NuGet symbol server: https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html

**Comment by FeodorFitsner** [comment]
...and if you are deploying from AppVeyor `.snupkg` publishing was implemented in AppVeyor long time ago.

**Comment by fredericDelaporte** [comment]
@anangaur, @FeodorFitsner , the new symbol system is very likely to be well known by most people here, and that is not the subject.

Letting a certificate expiring without renewing it is no way of obsoleting a feature previous version.
Beside, there is also legacy versions of software which may need some new release, notably for fixing security issues, while the code base of those legacy versions is very likely not updated to be able to publish snupkg.

**Comment by FeodorFitsner** [comment]
@fredericDelaporte I agree. I'm not sure I understand who is standing behind that web site, who is responsible for its maintenance?
