### ISSUE TITLE
Find-Package Elmah -StartWith fails when all sources are selected

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#6087]
```
PM> Find-Package Elmah -StartWith
Find-Package : The source does not have a Search service!
At line:1 char:1
+ Find-Package Elmah -StartWith
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Find-Package], FatalProtocolException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.FindPackageCommand
 
```

This should retrieve results from sources that do provide a search service such as NuGet.org.

**Comment by rrelyea** [comment]
@karann-msft  - which sources are causing this for you? another http one? a file: one?

**Comment by karann-msft** [comment]
This happens when "All" is selected in the Package Source selector in PMC
![image](https://user-images.githubusercontent.com/16904420/32015112-f7936d2c-b974-11e7-8362-ebbf1b0b6f15.png)

This is a bug and not consistent with using Find-Package without the "-StartWith". So what sources I have don't seem to matter.

![image](https://user-images.githubusercontent.com/16904420/32015212-476c07c8-b975-11e7-971a-1eaaf1645911.png)

**Comment by mishra14** [comment]
I cannot repro this - 

![image](https://user-images.githubusercontent.com/10507120/32028335-f867e29a-b9a2-11e7-96c6-85a3edbc44c9.png)
