### ISSUE TITLE
Build targets not imported from packages referenced by top-level package references

### ISSUE THREAD

**Issue by redoz** [NuGet/Home#6089]
VS version: 15.4.1
OS version: Microsoft Windows [Version 10.0.16299.19]

I haven't been able to find anything online regarding this (though perhaps I'm searching for the wrong keywords), so I figured I'd create an issue here, if this is documented/expected behavior I apologize in advance.

1. Include a NuGet Package that depends on a NuGet package that contains custom build targets.
2. Build project
3. Custom build targets of transitively included packages are not imported.

The project NuGet depdencies:

![image](https://user-images.githubusercontent.com/1670030/31938089-d6075b6e-b8b6-11e7-90f8-2b024da9692a.png)

This is the .targets file from the highlighted package:

![image](https://user-images.githubusercontent.com/1670030/31938197-2cfa0bf6-b8b7-11e7-95bf-47ad2250b9af.png)

But the targets file doesn't get imported on build (From the excellent MSBuild Structured Log Viewer):

![image](https://user-images.githubusercontent.com/1670030/31937918-36014602-b8b6-11e7-99dc-3a46cd124132.png)

However, if I reference the package directly from my project:

![image](https://user-images.githubusercontent.com/1670030/31938332-98e9c5ea-b8b7-11e7-83e2-abcd9468f07a.png)

It gets imported and the build works:

![image](https://user-images.githubusercontent.com/1670030/31938483-f6ed628c-b8b7-11e7-905a-842d2c35c84a.png)

If this is designed behavior, what's the proper way to handle dependencies like this?

**Comment by dasMulli** [comment]
Is the top-level package built from a `nuspec` file or a `ProjectReference` based solution? A project reference defaults to excluding Build, Analyzers and ContentFiles assets from referencing projects unless they also explicitly reference this package (see [docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) => default value for `PrivateAssets`).

**Comment by redoz** [comment]
You're right, setting ```PrivateAssets``` to ```none``` for the ```PackageReference``` in the top-level package fixed the problem. Thank you!
