### ISSUE TITLE
[Cleanup - Non blocking] Create a PackageSpec writer for project.json

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#609]
A package spec writer is needed to write out project.json after making in memory changes to test installs/uninstalls.

**Comment by anurse** [comment]
This probably isn't going to happen in 3.1 since it isn't really required.

**Comment by ericstj** [comment]
:+1: Would be nice.  I need to do this a lot when writing tools to transform our project.json's.
/cc @dagood

**Comment by toddm** [comment]
https://github.com/NuGet/NuGet.Client/commit/88330551e465e5673505c525515e74129f73d98c
