### ISSUE TITLE
Build targets are not included on installing

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#6090]
VS 2017 15.4.1

1. create a new VSIX project 

2. install package Microsoft.VSSDK.BuildTools in it

## Problem
The package Microsoft.VSSDK.BuildTools contains `.props` and `.targets` files which are expected to be included into csprj. But they are not included. 
I can see the package reference is added:

    <PackageReference Include="Microsoft.VSSDK.BuildTools">
      <Version>15.5.72</Version>
    </PackageReference>

but including `Microsoft.VSSDK.BuildTools.props` and `Microsoft.VSSDK.BuildTools.targets` didn't happen.
These file are in `build` folder of the package.

**Comment by jainaashish** [comment]
With PackageReference, these files will be included as part of `<projectName>.csproj.nuget.g.props` and `<projectName>.csproj.nuget.g.targets` inside `/obj` folder.

**Comment by evil-shrike** [comment]
My csproj isn't in new SDK-style format but old one (VSIX template generates such one) but with PackageReference inside.

**Comment by rrelyea** [comment]
in both csproj styles, with PackageReference, the targets do not get added directly into the csproj. Instead, some common targets import obj\<projectname>.csproj.nuget.g.targets and .props into the scope of the project.

So the targets should be part of your project, via some imports that you won't directly see in your csproj.

Generally, you can type "msbuild /pp:pp.txt foo.csproj" -- to create a preprocess file that lists every targets and props that is in scope.

**Comment by evil-shrike** [comment]
Let me clarify the problem.
In a project in legacy format
```
<Project ToolsVersion="15.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```
a nuget package with build targets is being installed . At the this VS will ask which format for nuget references I want: old packages.json or new with ProjectReference. I chose the new one ProjectReference.
There're no imports in csporj as it's the ProjectReference format and there're no imports as it's old format built with msbuild. At the end build targets are ignored.

**Comment by evil-shrike** [comment]
@rrelyea I understand that imports work in difference way with PackageReference, but should they work with MSBuild.exe ? I mean in case when I build csproj with msbuild (from VS2017 or BuildTools) for .net framework.
