### ISSUE TITLE
Suggested minor edits to nuget.exe CLI built-in help

### ISSUE THREAD

**Issue by kraigb** [NuGet/Home#6093]
After reconciling the nuget.exe docs with the help coming out of the CLI itself, I have two suggestions for changes to the CLI:

1.	Add: in the CLI help, the expand option is described as “If provided, a package added to offline feed is also expanded.” In the docs, it reads as, “If provided, all the files in the package are added to your package source.” Given that add works only with non-HTTP sources, it seems that the CLI help’s text is a little misleading and would do better to match the docs.

2.	Delete: CLI help shows NoPrompt but the tool gives a warning that it’s deprecated. I think it should be removed from the CLI altogether.

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
