### ISSUE TITLE
Error reporting exception for cancelled package download task

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6096]
In `NuGet.PackageManagement.PackageDownloader.GetDownloadResourceResultAsync(...)`, NuGet accumulates package download tasks with any state other than `TaskStatus.RanToCompletion`.  If the package download ultimately fails, NuGet attempts to [report the exception for each task](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/PackageDownloader.cs#L183).

Sometimes this reporting results in the following output:

    NU1000: Value cannot be null.
    Parameter name: exception

The reason is that package download tasks may or may not have an associated exception.  Tasks without exceptions (e.g.:  cancelled tasks) result in the above error report.

**Comment by mishra14** [comment]
@dtivel can you please add a milestone to the issue? If it is not meant for a specific release, then use the backlog milestone and add a priority label.

**Comment by rrelyea** [comment]
@dtivel  - When you are done with this, let's discuss whether to fix in nuget.exe only, or VSIX as well. ANd which releases...
