### ISSUE TITLE
Incremental Pack has wrong target output

### ISSUE THREAD

**Issue by jp2masa** [NuGet/Home#6099]
The paths that are added to the GenerateNuspec target output are wrong:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L172
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L181

The nuspec output path is `$(NuspecOutputAbsolutePath)`:
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/Pack.targets#L237

**Comment by mishra14** [comment]
@jp2masa can you please elaborate on the exact issue that you are facing?

Can you please give us a sample repro or steps to repro the issue?

**Comment by jp2masa** [comment]
I'm not facing any issue, I was reading the targets file and the path looks wrong, so I opened a PR.
