### ISSUE TITLE
Project to project closure is not used by RestoreCommand

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#610]
The project to project closure is not used by the restore command.

Steps
1. Create 3 projects
2. Link 1 -> 2 -> 3
3. Install nuget.versioning into 3

Expected
The 1 & 2 lock file should contain nuget.versioning

Actual
nuget.versioning is only in the lock file for 3

**Comment by yishaigalatzer** [comment]
This is not just for commandline

**Comment by anurse** [comment]
I'm assigning this to @pranavkm only because his PR NuGet/NuGet3#33 will fix this. If necessary, I can take over the PR, but if he gets that working and checked in, we should be good.

**Comment by pranavkm** [comment]
Verified this works correctly
