### ISSUE TITLE
Make symbols package (auto) push failure a warning for the `push` operation

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6101]
If the user creates a symbols package along with the NuGet package and then tries to `push` the package to NuGet.org, NuGet does the following (**non-atomic** steps):

1. Pushes the NuGet package to NuGet.org
2. Pushes the Symbols package (if present in the same folder) to SymbolSource.org (https://nuget.smbsrc.net)

If the Step 2 fails, the NuGet package is already pushed to NuGet.org but the `push` operation returns failure. This is not entirely correct as the primary push did pass and any subsequent push retry by the user will be rejected by NuGet.org as the package (with version) is already present on NuGet.org.

The primary functionality of `push` operation is to push the NuGet package to NuGet.org (or other package sources). If this function is successful, the CLI should return success.
The secondary functionality of pushing the symbols package automatically should result in a warning and **not** error. This will ensure enough traction on the symbols (auto) push failure but will not fail a build process (that also publishes the package).

**Comment by mishra14** [comment]
@anangaur can you please assign a milestone to the issue based on the target for fixing this?

**Comment by anangaur** [comment]
Still debating if we need to do this.

**Comment by anangaur** [comment]
No longer required as we plan to implement https://github.com/NuGet/Home/issues/6113
