### ISSUE TITLE
NuGet Package from new .csproj - Summary/Title Tag missing

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/Home#6102]
We are using the new .csproj and the integrated NuGet package building feature and I was wondering why I can't specify "Summary" and "Title" within Visual Studio?

When I upload the produced package to nuget.org, a title and summary field is shown without any input and the summary seems kind of important, because it is related to search?!

![image](https://user-images.githubusercontent.com/756703/32023471-8efecb70-b9d9-11e7-868c-4aa52fb10ac1.png)

Repo steps:
* Create new csproj
* fill out some package details
* upload produced package to nuget.org via the Web UI

I guess this is by design, but then the NuGet Gallery should render the fields differently.

**Comment by robertmuehsig** [comment]
Is this part OSS and are PRs possible/welcome?

**Comment by mishra14** [comment]
@robertmuehsig this UI page is not owned by NuGet. I will move your bug to a better repo.

**Comment by mishra14** [comment]
This issue was moved to Microsoft/VSProjectSystem#258

**Comment by robertmuehsig** [comment]
Question regarding those fields: Are they even still required? I guess if "Title" is not set, you will just use the PackageId, which in my point of view makes perfectly sense.

Even the "Summary" element doesn't seem to be that important, because I see my description text in the VS search, which is also great.

My question is: Does it really make sense to add those two fields to the VS page or should the NuGet Gallery avoid to show those fields in such a prominent way? (e.g. if the package don't have those values, just hide them).

**Comment by TheArchitectDev** [comment]
> Even the "Summary" element doesn't seem to be that important, because I see my description text in the VS search, which is also great.

> My question is: Does it really make sense to add those two fields to the VS page or should the NuGet Gallery avoid to show those fields in such a prominent way? (e.g. if the package don't have those values, just hide them).

I'm wondering the same thing. You make excellent points about their absence seeming to produce a desirable effect.
