### ISSUE TITLE
"Import documentation" - part of the .nuspec/.csproj settings?

### ISSUE THREAD

**Issue by robertmuehsig** [NuGet/Home#6103]
Everytime I update my NuGet package via the WebUI upload I need to reenter the documenation url. I know this is a pretty new feature, but is there some kind of PackageDocumentation tag that I can use so that I don't have to reenter the GitHub URL each realease?

![image](https://user-images.githubusercontent.com/756703/32023766-9743dc7a-b9da-11e7-9306-68908dfe08f9.png)

**Comment by mishra14** [comment]
@robertmuehsig this is an issue related to nuget.org.

This issue was moved to NuGet/NuGetGallery#4920
