### ISSUE TITLE
NuGet package try to retrieve in all configured NuGet sources

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#6106]
Hi all,

While installing the NuGet packages from the NuGet package manager with configured multiple NuGet package sources in VS2017, the NuGet client try to retrieve the package in all the configured NuGet sources and return the message like "Not Found". 

For Example: 
I have configured the below NuGet sources in my NuGet.Config,

`  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
	<add key="nuget_org" value="https://api.nuget.org/v3/index.json" />
    <add key="customfeed" value="https://www.myget.org/F/sample-feed-edge/api/v3/index.json" />
  </packageSources>`

I have tried to install the Newtonsoft.Json NuGet package from command prompt by using the "nuget restore" command. NuGet client will try to retrieve the Newtonsoft.Json NuGet packages from my customfeed NuGet source which is not contains the Newtonsoft.Json NuGet package and return the NotFound NuGet package message in the output. Please check the below log,

C:\Users\admin\.nuget>nuget restore C:\Users\admin\source\repos\App4\App4.sln
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
Restoring NuGet package Newtonsoft.Json.10.0.3.
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg 169ms
Installing Newtonsoft.Json 10.0.3.
  GET https://www.myget.org/F/sample-feed-edge/api/v3/flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg
  **NotFound https://www.myget.org/F/sample-feed-edge/api/v3/flatcontainer/newtonsoft.json/10.0.3/newtonsoft.json.10.0.3.nupkg 316ms**
  GET https://www.nuget.org/api/v2/Packages(Id='Newtonsoft.Json',Version='10.0.3')
  OK https://www.nuget.org/api/v2/Packages(Id='Newtonsoft.Json',Version='10.0.3') 324ms
  GET https://www.nuget.org/api/v2/package/Newtonsoft.Json/10.0.3
  OK https://www.nuget.org/api/v2/package/Newtonsoft.Json/10.0.3 1005ms
Adding package 'Newtonsoft.Json.10.0.3' to folder 'C:\Users\admin\source\repos\App4\packages'
Added package 'Newtonsoft.Json.10.0.3' to folder 'C:\Users\admin\source\repos\App4\packages'
Restoring packages for C:\Users\admin\source\repos\App4\App4\App4.UWP\project.json...
Committing restore...
Generating MSBuild file C:\Users\admin\source\repos\App4\App4\App4.UWP\App4.UWP.nuget.props.
Generating MSBuild file C:\Users\admin\source\repos\App4\App4\App4.UWP\App4.UWP.nuget.targets.
Writing lock file to disk. Path: C:\Users\admin\source\repos\App4\App4\App4.UWP\project.lock.json
Restore completed in 13.09 sec for C:\Users\admin\source\repos\App4\App4\App4.UWP\App4.UWP.csproj.

NuGet Config files used:
    C:\Users\admin\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\admin\.nuget\packages\
    https://api.nuget.org/v3/index.json
    https://www.nuget.org/api/v2/
    https://www.myget.org/F/sample-feed-edge/api/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    1 package(s) to packages.config projects

My Question is,

1. Why NuGet client try to retrieve in all configures sources?
2. Is this the bug from NuGet?

I have used the Visual Studio 2017 (15.4) and NuGet package Manager (4.4.0)

Please suggest the solution on this.

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Hi Team,

Any update on this?

**Comment by mishra14** [comment]
@GanesanRengasamy NuGet queries all sources for a package. This is done to reduce the total restore time. If any of the feeds responds that it contains the package then restore will use that feed. Your restore operation will not fail as long as any one of the feeds (e.g. -  nuget.org) contains the package.

**Comment by GanesanRengasamy** [comment]
Hi @mishra14 

Thanks for the update.

We have automated the NuGet restore process in our build server while compile our source application and we have faced some problem because of this "NotFound" message. 

So, please suggest the solution/workaround for avoid the "NotFound" message in the output.

Thanks,
Ganesan R.
