### ISSUE TITLE
Support by solution folder path configuration for PackageReference.

### ISSUE THREAD

**Issue by malylemire1** [NuGet/Home#6107]
Support by solution folder path configuration for PackageReference.

There is currently not way to specify path per solution. This could cause a problem if nuget package version is no longer available in nuget. We used to put nuget packages in our Git repository using configuration file to prevent this kind of problems.

Use case :

- Setup a new computer without any nuget package cache.
- Pull a 5 years old branch from our repository.
- Old nuget reference versions are no available on nuget anymore.
- Cannot build solution because packages cannot be restored.

Thanks

**Comment by mishra14** [comment]
@malylemire1 In Package reference, we do use cache(s) on the machine to reduce iterative restore time. They are not meant to be package sources. If you are concerned about the packages being unavailable then you can use the `-OutputDirectory` option while doing [NuGet restore](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore) and pass a custom path that you can save/version control.

Please let us know if you need more help from us.
