### ISSUE TITLE
How to get package size before downloading it from a feed?

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#6108]
I'm working on a internal tool to replace Click-once and a few other home grown application deployment solutions.  The goal is to use a Nuget feed to maintain the latest version of an application that needs to be deployed.

I'm using the v4.x.x version of the NuGet.* packages.

I would like to make sure there is enough disk space free to download the package from the feed.  Using the API is there anyway to determine the size of the package before it is downloaded?

Thanks

-marc

**Comment by joelverhagen** [comment]
Hey @mhsimkin,

The package size is not a first class property in any of the 4.x NuGet.* APIs. However, there are some strategies you can employ to fetch the package size.. Note that this value is not used by the official NuGet client so there is no assurance of this value being available on different feed types (V2 vs. V3) or server implementations (e.g. NuGet.org, MyGet, VSTS, etc).

If you are interested in the V3 API (e.g. https://api.nuget.org/v3/index.json), there are two possible strategies:

1. HTTP `HEAD` request against the .nupkg URL. This one is the simplest to implement but does not work on MyGet. I think they don't support `HEAD`.
1. `packageSize` from the `catalogEntry`'s `@id` property in the registration hive.

Note that the structure of the V3 API (the HTTP endpoints themselves) is currently being documented by me 😄, issue tracked here: https://github.com/NuGet/NuGetGallery/issues/4103.

I have demonstrated these options in this Gist:
https://gist.github.com/joelverhagen/32e7264f17b6259de80ea4224e47b48f

If you are using a V2 source (not recommended), both MyGet and NuGet.org expose a `<d:PackageSize>` OData property containing the package size. This is another approach but note that V2 is the "old API". New applications should depends on the V3 API as it is much more stable and performant.

**Comment by rrelyea** [comment]
thanks @joelverhagen  for your answer. (although i'm a bit confused how we refer to client APIs versus v3 APIs -- probably need a better name than "v3" for server provided APIs).
Closing as question, as this seems well handled.

**Comment by joelverhagen** [comment]
Yeah, naming is a bit tricky here. I personally refer to the HTTP endpoints/API surface area as the "V3 API". The client SDK is "3.x" or "3.x and newer". I don't know if this is widely accepted but it seems clear to me.
