### ISSUE TITLE
dotnet restore running in VSTS build cannot auth against VSTS feed

### ISSUE THREAD

**Issue by lukepuplett** [NuGet/Home#6109]
## Details about Problem

NuGet product used: dotnet.exe

NuGet version: 4.1.0.2450

dotnet.exe --version: 2.0.0

VS version:  n/a using VSTS build

OS version (i.e. win10 v1607 (14393.321)): Not sure on build server :-/

Worked before? If so, with which NuGet version: n/a

## Detailed repro steps so we can see the same problem

1. Create a NuGet library project for .NET Standard 2.0 in VS2017 into a Git repo.

2. Ref another home-made NuGet .NET Standard 2.0 package hosted on private VSTS feed.

3. Setup VSTS build for project made in step 1 using new dotnet core build step tasks.

4. Watch build fail on connection to private VSTS NuGet feed with HTTP 401.

Obviously there's a ton more detail. I think our Azure build VMs are in a private Azure subnet and use a proxy to get out. The http_proxy and https_proxy settings are set. Many other builds for apps and stuff work fine.

Here's a reduced and redacted folder layout for my repo. I had to put the NuGet.Config and other stuff under \src (instead of \src\\.nuget which I what works for other msbuild projects) so it gets discovered.

```
C:\DATA\Git\PamplemoussePackage\src
C:\DATA\Git\PamplemoussePackage\src\.nuget
C:\DATA\Git\PamplemoussePackage\src\.nuget\Readme.txt
C:\DATA\Git\PamplemoussePackage\src\Pamplemousse
C:\DATA\Git\PamplemoussePackage\src\Pamplemousse\Pamplemousse.sln
C:\DATA\Git\PamplemoussePackage\src\Pamplemousse\Pamplemousse.sln.GhostDoc.xml
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\.vs
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\.vs\PamplemousseStandardLib
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\.vs\PamplemousseStandardLib\v15
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\.vs\PamplemousseStandardLib\v15\.suo
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\PPP.Instrumentation.AspNetCore
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\PPP.Instrumentation.AspNetCore.Extensions
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\Microsoft.AspNetCore
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\PamplemousseStandardLib.csproj
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib\PamplemousseStandardLib.csproj.user
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests\PPP.Instrumentation.AspNetCore
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests\PPP.Instrumentation.AspNetCore.Extensions
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests\Microsoft.AspNetCore.Http
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests\PamplemousseStandardLib.UnitTests.csproj
C:\DATA\Git\PamplemoussePackage\src\PamplemousseLib.UnitTests\PamplemousseStandardLib.UnitTests.csproj.user
C:\DATA\Git\PamplemoussePackage\src\CredentialProvider.VSS.exe
C:\DATA\Git\PamplemoussePackage\src\NuGet.Config
C:\DATA\Git\PamplemoussePackage\src\NuGet.exe
C:\DATA\Git\PamplemoussePackage\src\NuGet.targets
C:\DATA\Git\PamplemoussePackage\src\VSS.NuGet.AuthHelper.exe
C:\DATA\Git\PamplemoussePackage\.gitignore
C:\DATA\Git\PamplemoussePackage\README.md
```

The dotnet build command works locally on my workstation.

NuGet.Config contents looks like this.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageRestore>
    <add key="enabled" value="true" />
    <add key="automatic" value="true" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="MyCorpNetFramework" value="https://corp-dpt.pkgs.visualstudio.com/_packaging/MyCorpNetFramework/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

```
2017-10-27T12:13:44.4783529Z [command]"C:\Program Files\dotnet\dotnet.exe" build C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\Pamplemousse.csproj --configuration release
2017-10-27T12:13:46.4940161Z C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(102,5): error : Unable to load the service index for source https://corp-dpt.pkgs.visualstudio.com/_packaging/MyCorpNetFramework/nuget/v3/index.json. [C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\Pamplemousse.csproj]
2017-10-27T12:13:46.4940161Z C:\Program Files\dotnet\sdk\2.0.0\NuGet.targets(102,5): error :   Response status code does not indicate success: 401 (Unauthorized). [C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\Pamplemousse.csproj]
```

**Comment by lukepuplett** [comment]
Interestingly, I added 
```
.\src\NuGet.exe restore .\src\EMTInstrumentationAspNetCorePackageStandardLib\EMTInstrumentationAspNetCoreStandardLib.csproj
```
To a PowerShell build task and that fails to see/use the NuGet.Config file alongside the NuGet.exe that's being run.

However, locally on my workstation when I run the exact same PS command line from the same current working directory, it does see the NuGet.Config file. That's esp. odd because its the same actual NuGet.exe executing but behaving differently.

**Comment by lukepuplett** [comment]
Managed to move the error on by adding a test NuGet.exe command line running in a PowerShell build task and specifying the location of the NuGet.Config file.

This is just an experiment to see if I can get the NuGet.exe 4.1.0.2450 command line to work.

PowerShell command task script:

```
$env:NUGET_CREDENTIALPROVIDERS_PATH="src\CredentialProvider.VSS.exe"
ls $env:NUGET_CREDENTIALPROVIDERS_PATH

ls .\src\NuGet.Config

.\src\NuGet.exe restore .\src\PamplemousseLib\Pamplemousse.csproj -ConfigFile .\src\NuGet.Config
```

Running under the VSTS build task I see this:

```
2017-10-27T13:17:41.9142177Z CredentialProvider.VSS: Getting new credentials for source:https://corp-dpt.pkgs.visualstudio.com/_packaging/MyCorpNetFramework/nuget/v3/index.json, scope:vso.packaging_write vso.drop_write
2017-10-27T13:17:58.6602935Z ##[error]Unable to load the service index for source https://corp-dpt.pkgs.visualstudio.com/_packaging/MyCorpNetFramework/nuget/v3/index.json.
  Response status code does not indicate success: 402 (Payment Required).
```

I don't know how the auth works for build servers on VSTS. It always gets very messy around auth, especially now we live in an OAuth world, it's complicated and opaque, it's made life pretty miserable for me as a programmer in the last few years.

**Comment by lukepuplett** [comment]
Updated the NuGet.exe version to 4.3.0.4406 and its now worse!

```
2017-10-27T13:37:35.3871979Z     Directory: C:\AZURE-CICD-AGENT1\_work\95\s\src
2017-10-27T13:37:35.3871979Z 
2017-10-27T13:37:35.3871979Z 
2017-10-27T13:37:35.3871979Z Mode                LastWriteTime         Length Name                                                                  
2017-10-27T13:37:35.3871979Z ----                -------------         ------ ----                                                                  
2017-10-27T13:37:35.3871979Z -a----       10/27/2017   2:37 PM        8659040 CredentialProvider.VSS.exe                                            
2017-10-27T13:37:35.3871979Z -a----       10/27/2017   2:37 PM            555 NuGet.Config     
2017-10-27T13:37:36.0175799Z MSBuild auto-detection: using msbuild version '15.1.548.43366' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'.
2017-10-27T13:37:36.4862733Z ##[error]C:\AZURE-CICD-AGENT1\_work\_temp\NuGetScratch\4zx5mptz.hga.nugetrestore.targets(466,5): error : File 'C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\src\NuGet.Config' does not exist. [C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\Pamplemousse.csproj]

2017-10-27T13:37:36.5018974Z ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.
2017-10-27T13:37:36.5018974Z ##[section]Finishing: PowerShell Script
```

Completely unable to locate the NuGet.Config file even though my sanity check PS `ls` command sees it fine.

**Comment by mishra14** [comment]
@lukepuplett Thanks for the detailed feedback. I see 2 issues here (along with my comments)- 

1. You are having trouble getting past the auth on a private VSTS feed.
Looking at your config file in the first post. I do not see any credentials. Is that expected?

2. With NuGet 4.3.0.4406 you are not able to locate the config file.
can you please give us the exact command that you ran ? 
I see that the ls directory is `C:\AZURE-CICD-AGENT1\_work\95\s\src` but logs indicate that we are looking for the config file in `C:\AZURE-CICD-AGENT1\_work\95\s\src\PamplemousseLib\src`. Knowing the exact command will clarify the input parameter.

**Comment by rrelyea** [comment]
Credential Provider does not work on DotNet.exe today. This is a known backlog issue #5447

**Comment by lukepuplett** [comment]
Hey thanks.

1. Yes I am. I don't know if it should have credentials or not. I don't know how auth really works. It runs fine for me in VS and locally using `dotnet` command line but we're running on a VSTS build server so I don't know how its designed to work.

2. The exact command was:

`.\src\NuGet.exe restore .\src\PamplemousseLib\Pamplemousse.csproj -ConfigFile .\src\NuGet.Config`

It seems that for the PS command line the `.` means the current folder in the context of the running PS script, but NuGet.exe when it runs with the `-ConfigFile` switch is interpreting `.` to mean "from the location of the .csproj file" which is odd, inconsistent and not what someone writing the command would expect.

I'll play tomorrow with it. In the meantime, I'd like to understand how NuGet or `dotnet` CLI are designed to do auth under VSTS when run as a raw command line, and when run under the new "dotnet" VSTS build tasks, i.e. does it somehow pass through the identity of the build agent?

Luke
