### ISSUE TITLE
Newtonsoft.Json 7.0.1-beta3 does not show up as a lock file target

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#611]
1. install newtonsoft.json 7.0.1-beta3
2. build

newtonsoft.json.dll does not show up in the lock file under targets.

**Comment by anurse** [comment]
It looks like this is caused by NuGetFrameworks not finding a matching framework in the list of frameworks supported by the package. We need to lock down the set of allowed portable profiles for `core50` to fix this.

**Comment by emgarten** [comment]
Updated NuGet.ContentModel to support nearest framework tie breaking.

NuGet/NuGet3@7c5fd6840de59c1a49df4c7e8648837079e3bde2
