### ISSUE TITLE
Content headers are not available using HttpSource

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#6112]
The content headers, such as `Content-Length` and `Content-Type` are lost because we replace the original `HttpContent` (probably `StreamContent`) with a `DownloadTimeoutStreamContent`. The headers are not copied over.

This limits extensibility.

**Comment by emgarten** [comment]
Any suggestions on where to expose this? Is there an existing part of the response it could go on or would this need something new?

**Comment by joelverhagen** [comment]
We can copy the HTTP headers over to the `DownloadTimeoutStreamContent` instead. This is available when using the `ProcessResponseAsync` method on `HttpSource`.

**Comment by rrelyea** [comment]
Would love to know impact and importance of this issue. Can you fill in some more details?

**Comment by joelverhagen** [comment]
> Would love to know impact and importance of this issue. Can you fill in some more details?

Sure! The goal here is to allow custom client code (e.g. other people using the 3.x/4.x client libraries) and future official client code to better handle HTTP responses. Potential scenarios include:

1. `ETag`: great for detecting if a HTTP resource has changed.
1. `Content-Length`: determine the size of an HTTP response body before committing to download it.

When investigating https://github.com/NuGet/Home/issues/6108, I found that a `HEAD` request is nearly useless when using `NuGet.Protocol` `HttpSource` type since the resulting `HttpResponseMessage.Content` has no header set.
