### ISSUE TITLE
Disable auto-push of symbols package

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6113]
### Context
If a user creates a symbols package along with their NuGet package and then tries to push the package to NuGet.org, NuGet does the following steps in sequence:
1. Pushes the NuGet package to NuGet.org
2. Pushes the Symbols package (if present in the same folder) to SymbolSource.org (https://nuget.smbsrc.net)

If Step 2 fails, the NuGet package is already pushed to NuGet.org but the push operation returns failure. This response is not entirely correct as the primary package push did pass and any subsequent push retry by the user will be rejected by NuGet.org as the package (with version) is already present on NuGet.org. 

#### Disable auto-push of symbols package to SymbolSource.org
Since the 2 pushes (as mentioned above) are non-atomic (they operate independently), it makes sense to separate out these steps. This will help users identify the failure and only retry the failing operation.
We have also seen frequent issues where SymbolSource.org becomes unreachable. The project is not being actively maintained. Of late, there is  [an issue](https://github.com/NuGet/Home/issues/6082) where the SSL certificate for https://nuget.smbsrc.net is invalid (expired).  Though we are working on getting this fixed by SymbolSource.org, there is no ETA on the fix.

This solution would not prevent users to use the Symbol Server of their choice. They can continue to push symbols package separately as follows:

```
> nuget push MyPackage.symbols.nupkg -source <symbol server endpoint>
```

To summarize, the changes proposed here are:
1. Stop auto push of symbols package to SymbolSource when the symbols package (.symbols.nupkg) is present in the same folder as NuGet package (.nupkg)
2. Stop defaulting to SymbolSource while pushing Symbols package.

### Next steps

The NuGet team is working on improving the debugging and symbols experience holistically. Look out for more details by subscribing to the [NuGet/Announcements](https://github.com/nuget/announcements) repo where we will announce the spec when the spec has more details.

| Spec wiki| Discussion issue| 
| :------------- |:-------------| 
|[NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements)|https://github.com/NuGet/Home/issues/6104|

**Comment by rohit21agrawal** [comment]
@anangaur can you get the new behavior documented?

**Comment by anangaur** [comment]
@rohit21agrawal Thanks. Lets sync up on what changes we want to document. We need to provide information on how to publish symbols if required.
