### ISSUE TITLE
NuGet restore improperly NoOps when 2 projects are sharing obj directory

### ISSUE THREAD

**Issue by BrennanConroy** [NuGet/Home#6114]
@emgarten 

1. `dotnet new console`
2. `dotnet run` (just to make sure it runs)
3. change name of csproj and downgrade the netcoreapp version to 1.0 or 1.1
4. `dotnet restore`
5. `dotnet run` (make sure it runs too)
6. rename csproj to original name
7. undo the previous downgrade
8. `dotnet restore` (does nothing)
9. `dotnet run`
10. See error:
```
C:\Program Files\dotnet\sdk\15.5.0-preview-007044\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(167,5):
error : Assets file 'C:\app\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.0'.
Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project. [C:\app\app.csproj]

The build failed. Please fix the build errors and run again.
```

**Comment by mishra14** [comment]
@BrennanConroy Thanks for reporting this issue. I think this is an issue with some no-op check that we have to prevent restore if no files have changed. Requesting @nkolev92 to investigate. 

in the mean time please use `dotnet restore --force` to ensure that a new restore is done if you run into such an issue.

**Comment by nkolev92** [comment]
@BrennanConroy 

This scenario is equivalent to having ProjectA (NetCore20) and ProjectB (NetCore10) in the same directory.

They both create the same assets file (project.assets.json), while they each create a separate cache file that's used for no-op. 

This is not exactly a supported scenario, not sure if we want to do something about it. 

The workaround as @mishra14 mentioned is very simple, you can do a restore force the time. 

But the reality is that you have leftover build files in the obj folder that should not be there. 

cc @emgarten

**Comment by rrelyea** [comment]
Although the title says edge case, no-op is important enough to make this issue a p1 backlog issue.

**Comment by emgarten** [comment]
Related: https://github.com/NuGet/Home/issues/4463
