### ISSUE TITLE
PackageReference does not work correctly with ClickOnce publishing

### ISSUE THREAD

**Issue by Daniel-Svensson** [NuGet/Home#6116]
I am I bit unsure about where to add this issue, so it this is the wrong place please move it to the correct repository.

## Details about Problem

I've been trying to update som of our existing projects to use the new PackageReference format to include nuget packages. One of them is a WPF application using ClickOnce. 
We been able to use workarounds found to make all project compile and run with the exception of projects with clickonce enabled.

The problem seems to be that libraries coming from nuget packages are marked included as "Prerequisite (auto)" in ClickOnce instead of "Include (auto)" which is problematic.

1. This prevents them from beeing automatically included in the clickonce manifest
2. This makes build fail when referencing libraries which are not strongly signed 

Others seems to have this issue: I found this https://stackoverflow.com/questions/46736788/clickonce-application-with-packagereferences-auto-to-prerequisites which seems to concern the same issue.

## Detailed repro steps so we can see the same problem

Short steps:
1. Build the sameple Project. (se below)

Long steps
1. Create a application and reference an nuget with unsigned binareies such as OpenRiaServices.Client) using PackageReference format
2. Enable ClickOnce publishing for the Project

## Expected result

1. I expect the solution to build
2. assemblies from nuget packages should be automatically included in clickonce publish

### Sample Project

In VS 2017 (15.4 or earlier) build the "HttpClient.sln" solution found att https://github.com/Daniel-Svensson/OpenRiaPlayground/tree/feature/clickonce_repro/HttpClient 

The same solution works fine if packages.config is used

The last 2 commits includes 
1. enabling clickonce to make build fail
2. build log

**Comment by emgarten** [comment]
I'm not familiar with ClickOnce. At a high level restore writes out assemblies that should be included in the build to project.assets.json. These entries are then turned into MSBuild reference items by the build SDK.

My guess is that the reference items created are not set with the metadata that ClickOnce is looking for when deciding if they should be included in the output.

I suggest looking at the diagnostic output of your build using https://github.com/KirillOsenkov/MSBuildStructuredLog  to determine what is different between the assemblies that are being included, and the ones that aren't. You can then write a target to update the references coming from NuGet packages.
