### ISSUE TITLE
NuGet PMC makes VS crash

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#6119]
As soon as I press enter in PMC window, it crash.

VS version - 15.5 preview2

Steps:
1. Create a new asp.net core app
2. open PMC window and press enter

**Comment by emgarten** [comment]
Is this perf because the window isn't loading fast enough? This seems like a bug to me.

**Comment by jainaashish** [comment]
it's a performance bug since it was a crash and more importantly a regression so should be investigated asap.

**Comment by emgarten** [comment]
@jainaashish thanks, setting this to pri 0.

**Comment by jainaashish** [comment]
It came out to be the issue with an old version of Microsoft.Internal.Performance.CodeMarkers.dll being loaded. Removing that, fixes this issue. So we can close it.
