### ISSUE TITLE
Use CPS Async APIs to resolve references.

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6120]
Consequence of internal issue 504715. 

Per internal e-mail thread. 
From Lifeng Lu:
```
That conforms that NuGet might want to use CPS async APIs like IBuildDependencyProjectReferencesService and IAssemblyReferencesService to resolve references.  Because this delay is coming from several different sources, it is better to address them separately.  The GetFullProjectPath one should be cheap to fix without touching much code.
```

This task is to address getting the references as per the following stack:

\|     nuget.packagemanagement.visualstudio.dll!NuGet.PackageManagement.VisualStudio.VsCoreProjectSystemReferenceReader+<GetProjectReferencesAsync>d__.MoveNext | 18 | 2,082
-- | -- | --
\|     +vcproject.dll!CVSReference::get_Resolved | 14 | 1,612
\|     \|+microsoft.visualstudio.project.visualc.vcprojectengine.dll!Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCReferenceShim.get_IsResolvable | 13 | 1,630

\|\|\|      \|        \|\|       +nuget.packagemanagement.visualstudio.dll!NuGet.PackageManagement.VisualStudio.VsCoreProjectSystemReferenceReader.GetExcludedReferences | 24 | 3,648
-- | -- | --
\|\|\|      \|        \|\|       \|+microsoft.visualstudio.projectsystem.vs.implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNodeWrapper.GetItemAttribute | 17 | 3,804
\|\|\|    \|          \|\|     \|\|   microsoft.visualstudio.projectsystem.vs.implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Microsoft.VisualStudio.Shell.Interop.IVsBuildPropertyStorage.GetItemAttribute | 17 | 3,804

/cc
@jainaashish 
@rrelyea 
@lifengl

**Comment by jainaashish** [comment]
With the second PR# it now resolves only project references which should improve this experience. We'll still keep an eye on this failure in future releases.
