### ISSUE TITLE
Restore target should return a status item 

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6122]
Related to https://github.com/Microsoft/msbuild/issues/2677

The restore target should return an item containing the status of restore. Specifically this should provide a way to tell if the props/targets files changed during restore. 

This could be done by checking the timestamps before and after, or by actually passing this information up from each restore.

Consider also if this should be provided only at the solution restore level, or if the status should list the path to each project that was changed.

**Comment by rrelyea** [comment]
Design discussion with @Emgarten, @andygerlicher -- 
Need to research:
Do we do an item result at the project or solution level?
Or do we do a property result at each project level?

ideally...nuget could tell that an evaluation cannot be reused only iff the .g.props and .g.targets were not written.

**Comment by emgarten** [comment]
The restore target should return an item or a property that indicates if props/targets files changed on disk.

https://github.com/NuGet/NuGet.Client/blob/2cd603d1b54f9ccb92429102576f7edc1b48cbec/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L92

Example:
```xml
<Target Name="Restore" DependsOnTargets="_GenerateRestoreGraph" Returns="$(RestoreHasModifiedImports)">
```

This property should be set based on the auto generated props/targets changing. An easy check to start with is to see if restore was a noop. If so then no changes were made.

The actual check should probably be done in the RestoreTask and returned through an output parameter.
https://github.com/NuGet/NuGet.Client/blob/2cd603d1b54f9ccb92429102576f7edc1b48cbec/src/NuGet.Core/NuGet.Build.Tasks/RestoreTask.cs#L24

**Comment by nkolev92** [comment]
Closing this as it will not bring us the initially expected expected benefit, due to the fact that restore evaluation is with `ExcludeRestorePackageImports=true`.

For OrchardCore:

/t:build /restore
Time Elapsed 00:00:57.75
Time Elapsed 00:00:58.31

/t:restore,build
Time Elapsed 00:00:57.81
Time Elapsed 00:00:58.82
