### ISSUE TITLE
Adding <GeneratePackageOnBuild>true</GeneratePackageOnBuild> causes build errors.

### ISSUE THREAD

**Issue by loekd** [NuGet/Home#6123]
## Details about Problem
Adding `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` to the csproj file causes many errors to be generated during build.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGetizer 3000

NuGet version (x.x.x.xxx):
0.2.1

dotnet.exe --version (if appropriate):
2.0.2

VS version (if appropriate):
15.4.1

OS version (i.e. win10 v1607 (14393.321)):
10.0.15063

Worked before? If so, with which NuGet version:
unknown

## Detailed repro steps so we can see the same problem

1. Create a new solution with 2 class libraries, using netstandard 2.0. (shared1 and shared2)
2. Add third project (packaging), that is intended to package the other 2. 
   Reference the other 2 projects.
3. install nuget package NuGet.Build.Packaging in all projects
4. Build packaging project.
5. Package is produced, together with lots of errors similar to;
`nuget.build.packaging\0.2.1\build\NuGet.Build.Packaging.targets(377,3): error NG0012: Duplicate package source files detected for target package file path 'lib\netstandard2.0\System.Xml.XPath.XDocument.dll'`
...

### Sample Project

[demosln.zip](https://github.com/NuGet/Home/files/1430946/demosln.zip)

**Comment by emgarten** [comment]
@kzu

**Comment by kzu** [comment]
Fixed on https://github.com/NuGet/NuGet.Build.Packaging/pull/151
