### ISSUE TITLE
Feature Request: config file transform redirect configuration

### ISSUE THREAD

**Issue by AlexisColes** [NuGet/Home#6126]
We have a custom configuration transform process which means that the web.config/app.config file that we use as a source is actually called web.seed.config/app.seed.config.  This allows us to use tokens in our config files that get replaced on build/deploy time depending on msbuild args.

It would be great if we could have a way of adding configuration to nuget to allow us to map transforms that target a config file to another file.

eg: instead of adding a binding redirect to web.config we could add a mapping like the following
```
<TargetFileRedirects>
    <Redirect From="web.config" To="Web.seed.config" />
</TargetFileredirects>
```
Which would instead run the transform against web.seed.config.

Hope that makes sense,

Cheers.

**Comment by emgarten** [comment]
@AlexisColes are you able to run these transforms as part of a pre-build MSBuild target?

**Comment by emgarten** [comment]
All customized actions like this should be handled through msbuild or some other means. I'm not sure that nuget should handle all XML transforms for things that are not related to nuget or packages, but I do appreciate the suggestion.

Please let me know if there is a reason this needs to be done in nuget and not msbuild.

**Comment by AlexisColes** [comment]
Sorry, I have been a little on the slow side seeing your response.

I am not asking nuget to do anything outside install nuget packages, I am just asking for a way to map the transforms that it does to a different filename.

We cannot use the web.config file as our source file as we want to add tokens into the web.config and transforming said web.config on build would replace the tokens with the run time dev values the first time you ran it.  So we need to use a different file as the source file.

However all the nuget packages want to transform the web.config.  However we treat these files as a run-time files and not a source files, so after adding a new get package and running the code, all the transformations the nuget package has made to the web.config(runtime file) gets over written with the source code from web.seed.config(source file).

So as far as our set up goes nuget is targeting a runtime file not a source code file and we would like to be able to tell it which file it should be targeting.  It is like it is injecting some IL into the exe and expecting it to work the next time it is compiled.
  
I suppose the only reason we need to do this is for asp.net projects as the web.config that is used at runtime is in the same location as the source code (this seems a terrible separation of concerns).  If it was a windows service, we could just use the app.config as the source file as the runtime file is moved to a different folder and called something different.

I suppose I was hoping this would be easy enough to do from your perspective, just a remapping of the file name via the config and would make our life much easier.
