### ISSUE TITLE
Can not run most recent version of nuget package

### ISSUE THREAD

**Issue by sam-wheat** [NuGet/Home#6127]
I made an update to a nuget package I authored and pushed it to the nuget server. 
I updated a project I'm working on to use the new version of the package.  However when I step through my code I see I'm still running the old version of the package. I opened windows explorer and looked at the .dlls in the package folder and confirmed they are the correct version.

How I've tried to fix this:
Ran update-package -reinstall
Deleted the nuget package from my project and re-added it
Deleted all bin and obj directories for all projects
Cleared nuget cache from VS (Tools => options -> Nuget => Clear all)
Deleted all files from appdata\local\temp
Deleted the package folder from my solution
Deleted the .vs folder from my solution

I created a dummy project and added the nuget package and it works fine.

I need to use the new version of the nuget package in my project - how do I do that?  Why does it work with my dummy project but not with the production project? 

By the way when I pushed the new version of my pkg I ran into a https problem with the symbol server.  Same problem as described here: https://stackoverflow.com/questions/46925445/certificate-error-when-pushing-nuget-symbol-package

I thought perhaps nuget was downloading the old version of the symbol file so I tried turning off my network connection after cleaning and rebuilding my project but it still does not work.

Thanks

Microsoft Visual Studio Community 2017 
Version 15.4.2
VisualStudio.15.Release/15.4.2+27004.2006
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA017
Microsoft Visual Studio Tools for Applications 2017

Visual Basic 2017   00369-60000-00001-AA017
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA017
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA017
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.9.00809.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30925.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.50921.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30915.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17297.4
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

CustomizeVSWindowTitle 3   1.0
Information about my package

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Markdown Editor   1.11.214
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.8
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.179
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

Project   1.0
Information about my package

Python   3.0.17297.4
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17297.4
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17297.4
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17297.4
Profiling support for Python projects.

R Tools for Visual Studio   1.2.30905.1244
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Analysis Services   14.0.1012.227
Microsoft SQL Server Analysis Services Designer 
Version 14.0.1012.227

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

SQL Server Integration Services   
Microsoft SQL Server Integration Services Designer
Version 14.0.800.98

SQL Server Reporting Services   14.0.1012.227
Microsoft SQL Server Reporting Services Designers 
Version 14.0.1012.227

SsmsVsIntegration   1.0
Information about my package

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.3.5.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Universal Windows Apps   15.0.27004.2006
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.IoT   1.0
Package with IoT components for Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WebJobs Tools v1.0.0   15.0.30915.0
WebJobs Tools v1.0.0

Xamarin   4.7.10.33 (70936af)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   8.0.2.1 (HEAD/c2a33d8ea)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.2.1.0 (12e80e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by emgarten** [comment]
@sam-wheat are you overwriting the same version of the package on the server?

**Comment by sam-wheat** [comment]
No

Sent from my Windows Phone
________________________________

**Comment by emgarten** [comment]
Use `nuget.exe locals -clear all` to clear your caches. Delete any local package folders, it is likely that you have an older version of the package that is getting used.

**Comment by sam-wheat** [comment]
@emgarten Thanks Justin.  I did seventy-one Hail Marys and reinstalled Visual Studio.  I'm not sure which one worked.
