### ISSUE TITLE
nuget VS 2017 DLL using profile 259

### ISSUE THREAD

**Issue by xavier-rigau** [NuGet/Home#6128]
Profile 259 is listed [here ](https://portablelibraryprofiles.stephencleary.com/) says the Nuget Target is `portable-net45+win8+wpa81+wp8` but when using WireShark to see the traffic between VS2017 and our Nexus server (see attachment) it asks for` portable45-net45+win8+wp8+wpa81`

Note the extra **45** after `portable`!

[Wireshark extract](https://github.com/NuGet/Home/files/1435640/Nuget.Bug.zip)

**Comment by emgarten** [comment]
The format of a TFM is `{framework}{version}-{profile}`

For portable the version is optional and typically excluded, but it is not incorrect to have it. Nexus server should be able to handle parsing these TFMs correctly.

**Comment by xavier-rigau** [comment]
What should be the path forward @emgarten ?

**Comment by emgarten** [comment]
> What should be the path forward @emgarten ?

Where is this a problem? Is nexus having a problem with this?
