### ISSUE TITLE
ArgumentNullException when restoring project.json file using RestoreRunner C# API

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#6131]
## Details about Problem

NuGet product used: `NuGet.Commands` package, version `4.3.0` inside a custom MSBuild custom task

Worked before in `NuGet.Commands` `4.3.0-preview2-4095`

## Detailed repro steps so we can see the same problem

Create a `RestoreArgs` for a project.json and pass it to `RestoreRunner.RunAsync` in C# (see [EncryptedConfigNuGetRestore.cs](https://github.com/dotnet/buildtools/blob/1c66c0fbb15eacce3707f26fff3ac689004c31df/src/Microsoft.DotNet.Build.Tasks/EncryptedConfigNuGetRestore.cs)):

```C#
var args = new RestoreArgs
{
    Inputs = Inputs.Select(item => item.ItemSpec).ToList(),
    ConfigFile = ConfigFile,
    GlobalPackagesFolder = PackagesDir,

    Sources = new List<string>(),
    CacheContext = new SourceCacheContext(),
    RequestProviders = new List<IRestoreRequestProvider>
    {
        new ProjectJsonRestoreRequestProvider(new RestoreCommandProvidersCache())
    },
    Log = new NugetMsBuildLogger(new TaskLoggingHelper(this))
};

RestoreRunner.RunAsync(args).Wait();
```

Run the task on a simple `project.json` with a `NuGet.Config`. The result is a `System.ArgumentNullException` exception. Stack trace:

```
The "EncryptedConfigNuGetRestore" task failed unexpectedly.
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at NuGet.Commands.RestoreArgs.GetEffectiveSourcesCore(ISettings settings, IList`1 dgSpecSources)
   at NuGet.Commands.RestoreArgs.<>c__DisplayClass81_0.<GetEffectiveSources>b__1(String root)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at NuGet.Commands.RestoreArgs.GetEffectiveSources(ISettings settings, IList`1 dgSpecSources)
   at NuGet.Commands.ProjectJsonRestoreRequestProvider.Create(String inputPath, RestoreArgs restoreContext)
   at NuGet.Commands.ProjectJsonRestoreRequestProvider.CreateRequests(String inputPath, RestoreArgs restoreContext)
   at NuGet.Commands.RestoreRunner.<CreateRequests>d__12.MoveNext()
...
```

## Other suggested things

I looked at the execution flow and saw this odd sequence of events added in https://github.com/NuGet/NuGet.Client/pull/1391. It looks like this will always cause that exception:

[`var sources = restoreContext.GetEffectiveSources(settings, null);`](https://github.com/NuGet/NuGet.Client/blob/4b227680d6fcf0aa8372ca8aae59cd58cd3143a5/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/ProjectJsonRestoreRequestProvider.cs#L74)

[`List<SourceRepository> GetEffectiveSources(ISettings settings, IList<PackageSource> dgSpecSources)` ... `GetEffectiveSourcesCore(settings, dgSpecSources)`](https://github.com/NuGet/NuGet.Client/blob/4b227680d6fcf0aa8372ca8aae59cd58cd3143a5/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs#L117-L127)

[`List<SourceRepository> GetEffectiveSourcesCore(ISettings settings, IList<PackageSource> dgSpecSources)` ... `var sourceObjects = dgSpecSources.ToDictionary(k => k.Source, v => v, StringComparer.Ordinal);`](https://github.com/NuGet/NuGet.Client/blob/4b227680d6fcf0aa8372ca8aae59cd58cd3143a5/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/RestoreArgs.cs#L129-L131)

## Workaround

I was able to work around this by creating a derived class from `ProjectJsonRestoreRequestProvider` and changing the line to a simpler way to get sources. I know that we're in shaky territory by still being on project.jsons, but having some way to continue with this (whether we stick with the workaround or get a NuGet fix) buys us some time.

**Comment by emgarten** [comment]
This isn't really used in NuGet anymore, it was meant for discovering standalone project.json files from disk which isn't a supported scenario now. We are currently just using this in tests still.

We would accept a PR for this, or maybe having your own implementation is a better approach since this is effectively dead in NuGet.

**Comment by dagood** [comment]
Thanks, at this point I agree it's best for us just to use the workaround in our code. This lets us stay on the stable version of the package and avoids causing problems for others if a fix has some other effects. We also have a plan to stop using project.json for this task anyway, in the long run.

**Comment by emgarten** [comment]
Thanks for raising the issue, I'm going to close this out since it seems like we are not going to take action it. Let me know if anything changes!
