### ISSUE TITLE
nuget push alters file name and renders unusable from VS

### ISSUE THREAD

**Issue by xavier-rigau** [NuGet/Home#6132]
1.  When I try to install the package from my desktop **(local file)** it works and the dependencies displayed in VS make sense 

![vs image 1](https://user-images.githubusercontent.com/11412909/32298038-5849e5b2-bf0e-11e7-93b9-c4622e8136b5.jpg)

2.  Once we push this package to our Nexus server (Nexus Repository Manager OSS 2.14.1-01) the package changes name and has a dash (‘-‘) instead of a dot (‘.’) before the version. Goes from `HP.Pdsmq.Xamarin.2015.6.0.1.26.nupkg` to `HP.Pdsmq.Xamarin.2015-6.0.1.26.nupkg`

3. After that package is manually downloaded **(local file)**, VS finds it but can’t provide the preview and if you try to install it, it errors out

![vs image 2](https://user-images.githubusercontent.com/11412909/32298178-c5de0086-bf0e-11e7-85b5-63d7449a6b3a.jpg)

```
Attempting to gather dependency information for package 'HP.Pdsmq.Xamarin.2015.6.0.1.26' with respect to project 'ClassLibrary4', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
Package 'HP.Pdsmq.Xamarin.2015 6.0.1.26' is not found in the following primary source(s): 'H:\Code\Pepto60Stab\src\Windows\Xamarin\NuGet'. Please verify all your online package sources are available (OR) package id, version are specified correctly.
Time Elapsed: 00:00:00.6369319
========== Finished ==========
```
4)	Once this local file is renamed back to use ‘.’ It displays and installs fine. 
5)	When the package with the ‘-‘ is up in Nexus and VS queries for it then the response we get is wrong. Again, incorrect preview and it won’t install. (see Nuget Bug.zip) to see the WireShark capture.
[Nuget Bug.zip](https://github.com/NuGet/Home/files/1435726/Nuget.Bug.zip)

![vs image 3](https://user-images.githubusercontent.com/11412909/32298306-330031b6-bf0f-11e7-855f-65571baf4d45.jpg)

**Comment by emgarten** [comment]
@xavier-rigau this looks like a bug in Nexus if the response from Nexus is wrong.

Older versions of NuGet did not support pre-release labels that start with numbers. This is likely causing the issue. I would expect that Nexus would reject this package when pushed if it is not supported, but it seems this is not being validated.

**Comment by xavier-rigau** [comment]
I am not using any pre-release label. Have you examined the Wireshark traffic? Is it definitely a Nexus issue? If so how do I proceed?

**Comment by emgarten** [comment]
I was basing this on:

> When the package with the ‘-‘ is up in Nexus and VS queries for it then the response we get is wrong. Again

It is also common that errors in the feed break the UI, since everything shown in the UI came from the feed. When using a local folder there is no feed involved and NuGet reads everything directly. So if this were a nuget issue it would likely happen for local also. The nature of the problem is that it breaks when doing something old nuget 2.x cannot handle, and that is very likely a feed problem.

**Comment by xavier-rigau** [comment]
Thanks. The package was pushed as HP.Pdsmq.Xamarin.2015.6.0.1.26.nupkg. I don't know what, where and when it became HP.Pdsmq.Xamarin.2015-6.0.1.26.nupkg. Looks like you are stating is a Nexus bug. Where do I submit this bugs?

**Comment by emgarten** [comment]
@xavier-rigau from searching around it looks like nexus issues are here: https://issues.sonatype.org/projects/NEXUS/issues/NEXUS-11435?filter=allopenissues
