### ISSUE TITLE
Package Manager shows "ghost" update notifications

### ISSUE THREAD

**Issue by unniravindranathan-okta** [NuGet/Home#6134]
Repro steps:
a) Clone the repo from https://aka.ms/eshopuwp/src
b) Open this solution, change configuration to x86 and do a full rebuild.
c) Open the package manager UI

Observed: Both the Browse and Installed tabs show artifacts for updates available, as in the attached screenshot.
Expected: They should not.

![nugettabs](https://user-images.githubusercontent.com/5762284/32340183-1f129204-bfb7-11e7-96e4-2bbe8757b3a2.JPG)

**Comment by emgarten** [comment]
I don't see any conditions on the configuration in the csproj files. It is unclear why this is happening.
