### ISSUE TITLE
Git tags corresponding to nuget versions for `NuGet.BuildTasks`

### ISSUE THREAD

**Issue by radical** [NuGet/Home#6135]
I can't find any git tag corresponding to the nuget versions released for `NuGet.BuildTasks`. Is there another
way to find the commit hash used for building a particular nuget version?

**Comment by emgarten** [comment]
@radical https://github.com/nuget/nuget.buildtasks the repository, or for `nuget.build.tasks` the restore task? 

Just want to clarify on these very similar names first :smile:

**Comment by radical** [comment]
Oh, I had mixed up the two. The *nuget* I was referring to was for the restore task stuff. And that changes my question a bit.

IIUC, https://github.com/dotnet/cli/blob/release/15.5/build/DependencyVersions.props#L19 is used as the version to use for the nuget - `NuGet.Build.Tasks` (for the restoretask).

Similarly:

1. Where is the `Microsoft.NuGet.Build.Tasks` assembly+targets (built from the https://github.com/nuget/nuget.buildtasks repo) taken from when installing with VS?
2a. If that is from a nuget then where is the version for that listed?
2b. And how I do find the commit corresponding to that nuget version?

**Comment by emgarten** [comment]
Use the branch `release-4.5.0-rtm` from https://github.com/nuget/nuget.client

**Comment by radical** [comment]
> Use the branch release-4.5.0-rtm from https://github.com/nuget/nuget.client

um that is for the `NuGet.Build.Tasks.RestoreTask`(etc), and I already get the version that a VS release would use from https://github.com/dotnet/cli/blob/release/15.5/build/DependencyVersions.props#L19 (using the appropriate branch for the VS release). 

But I was asking about:

1. Where is the `Microsoft.NuGet.Build.Tasks` assembly+targets (built from the https://github.com/nuget/nuget.buildtasks repo) taken from when installing with VS?

2a. If that is from a nuget then where is the version for that listed?
2b. And how I do find the commit corresponding to that nuget version?

I need to track what gets included with a VS release, so that I can figure out the msbuild commit that was used + NuGet.BuildTasks commit (from https://github.com/nuget/nuget.buildtasks) that was used, and match that for Mono packaging. So, I need to know how to track this on an ongoing basis.

**Comment by emgarten** [comment]
@tmeschter would you answer @radical's question on NuGet.BuildTasks tagging?

**Comment by emgarten** [comment]
🔔 @tmeschter any updates?

**Comment by tmeschter** [comment]
@radical @emgarten There's no good way to do that right now. We don't actually build Microsoft.NuGet.Build.Tasks.dll from the NuGet.BuildTasks repo. Instead, it gets mirrored into the VS repo and built from there using a different build process (which affects versioning, etc.).

The right long-term fix is to update the NuGet.BuildTasks repo to produce the proper binaries, and then insert those binaries into the VS repo. However, that's a decent chunk on work; I'll have to see if we can fit it in to 15.6.

@radical What do you actually need for "Mono packaging"? The actual binaries?

**Comment by nkolev92** [comment]
I think we should consider this issue as redundant at this point with .NET 5 and all :)
