### ISSUE TITLE
SLN file format detection is not same as msbuild's

### ISSUE THREAD

**Issue by azchohfi** [NuGet/Home#6137]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.3.0.4406

OS version: Windows 10 v16299

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Try to execute a nugget restore like this:
.\nuget.exe restore BarcodeScanner.sln

2. If the SLN file starts with a empty blank lines (supported in msbuild), the nuget.exe throws:
"Error parsing solution file at BarcodeScanner.sln: Exception has been thrown by the target of an invocation.  No file format header found."

3. This behavior should be equivalent of msbuild, that it just ignores empty lines. This is specially painful on VSTS, where the build task works, but the restore packages one doesn't.

### Verbose Logs

NuGet Version: 4.3.0.4406
MSBuild auto-detection: using msbuild version '15.4.8.50001' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Error parsing solution file at C:\Users\alzollin\source\repos\Windows-universal-samples\Samples\BarcodeScanner\cs\BarcodeScanner.sln: Exception has been thrown by the target of an invocation.  No file format header found.  C:\Users\alzollin\source\repos\Windows-universal-samples\Samples\BarcodeScanner\cs\BarcodeScanner.sln
NuGet.CommandLine.CommandLineException: Error parsing solution file at C:\Users\alzollin\source\repos\Windows-universal-samples\Samples\BarcodeScanner\cs\BarcodeScanner.sln: Exception has been thrown by the target of an invocation.  No file format header found.  C:\Users\alzollin\source\repos\Windows-universal-samples\Samples\BarcodeScanner\cs\BarcodeScanner.sln
   at NuGet.CommandLine.MsBuildUtility.GetAllProjectFileNamesWithMsBuild(String solutionFile, String msbuildPath)
   at NuGet.CommandLine.RestoreCommand.ProcessSolutionFile(String solutionFileFullPath, PackageRestoreInputs restoreInputs)
   at NuGet.CommandLine.RestoreCommand.<DetermineRestoreInputsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.RestoreCommand.<ExecuteCommandAsync>d__34.MoveNext()

### Sample Project

https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/BarcodeScanner/cs/BarcodeScanner.sln

**Comment by emgarten** [comment]
Interesting scenario, NuGet has always used the msbuild libraries to read solution files so I am surprised that this is different.

@azchohfi any reason whitespace at the beginning of a solution file *should* be supported? How did this file get created like this?

I can understand wanting parity, but since this has never been supported could you help me understand why it should be fixed now so I can prioritize this?

**Comment by azchohfi** [comment]
The NuGet restore option inside the MSBuild’s VSTS build task is being deprecated (and the recommended way of doing restore is thru the NuGet restore VSTS build task), then their behavior should match, and right now, they don’t.

I have no idea how this files were created, and I agree that they are bizarre...

**Comment by azchohfi** [comment]
I think this was a mistake from my end. MSBuild also throws when there are blank lines at the header. VS doesn't, but MSBuild does.

**Comment by emgarten** [comment]
Thanks for the update @azchohfi, NuGet uses msbuild libraries for parsing. I don't think we want to recreate VS's parsing logic also for restore.
