### ISSUE TITLE
NU1605 by default treated as error instead of warning, breaks updating packages in solutions

### ISSUE THREAD

**Issue by patroza** [NuGet/Home#6141]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): VS 15.4

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.4

OS version (i.e. win10 v1607 (14393.321)): win 10 creators

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a solution with 4 .net standard or core 2 projects (2 depends on 1, 3 depends on 2, 4 depends on 3), install a package to all 4 of them, at an older version than the latest

2. Nuget update the project 1 (has no other project dependencies)

3. Now try to upgrade all projects through solution nuget package management to the latest version

4. Observe that you cannot get the packages installed because package restore throws NU1605 and prevents further updates from happening.

## Workaround

Edit 10's of csproj's to not treat NU1605 as error.

**Comment by zhili1208** [comment]
NuGet treat NU1605 as warning by default, but looks like net standard template set TreatsWarningAsErrors to true for NU1605. @terrajobst Do you have any ideas why net standard template do this?

**Comment by emgarten** [comment]
This is intentional since downgrading from netstandard2.0 to netstandard1.0 packages can cause problems.

As mentioned, this setting comes from the SDK and you can override it in your project. Restore is getting the values from TreatsWarningAsErrors and WarningsAsErrors.

**Comment by patroza** [comment]
@emgarten I understand it is intentional in the scope of .net standard, as well as that it is a good default in general.
Howeve it isn't in practice. This results in a very painful situation to deal with, would be great if this can get reopened and addressed.

**Problem:** Treating NU1605 as error will leave solutions in an unusable state when upgrading NuGet packages solution wide because dependent projects will get updated, and then the projects who depend on them will fail updating because of NU1605.

**Workaround**: Go into all the csproj's and disable the NU1605 treat as error setting.
(Tedious effort, as well as defeating the purpose of the feature)

**Solution**: Continue updating NuGet packages when NU1605 happens, so that at the end of the process, the solution is in a usable state. So while builds should indeed fail because of NU1605, it shouldn't disrupt the updating of packages.

**Comment by emgarten** [comment]
I understand the frustration around this.

I suggest importing a common props file into all projects to make it easier to control these settings, you can also use a dirs.props file.

To continue the discussion I think it would be better to open an issue at: https://github.com/dotnet/sdk/issues

The property is set here: https://github.com/dotnet/sdk/blob/cd25d6bbfc2aac61cc790c511900427ac64fdaa8/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.CSharp.props#L20
