### ISSUE TITLE
Higher priority for search results of reserved prefixes

### ISSUE THREAD

**Issue by ENikS** [NuGet/Home#6142]
It would be nice if package search returned results for registered prefixes on top of the search list. For example if I search for package ``Unity``, which is reserved prefix, it returns 500+ results with other packages mixed in into the list:
```
Unity
...
Unity.Configuration
Prism.Unity                     <-- should not be here
Unity.ServiceLocation
...
``` 
It would be nice if prefix would be recognized and given higher priority 

```
Unity
Unity.*
...
Rest.Of.The.Packages
```

**Comment by emgarten** [comment]
This issue was moved to NuGet/NuGetGallery#4986
