### ISSUE TITLE
Restore nuget failed : Ambigous project name

### ISSUE THREAD

**Issue by AlexTeixeira** [NuGet/Home#6143]
# Version details

**Nuget version** : AppVeyor version ( Current Visual Studio 2017 version )

**MSBuild version** : 15.4.8.50001

**OS** : AppVeyor version

**Project Type** : Multiplaform nuget for Xamarin

**Link to appveyor** :
https://ci.appveyor.com/project/AlexTeixeira/askmethat-xforms-controls/build/1.1.1-CI-11-ythksvpb

**Link to GitHub project** :
https://github.com/AlexTeixeira/Askmethat-XForms-Controls/tree/master/src

# Problem

```
Restoring packages for C:\projects\askmethat-xforms-controls\src\Askmethat.XForms.Controls.NuGet\Askmethat.XForms.Controls.NuGet.nuproj...
nuget : Ambiguous project name 'Askmethat.XForms.Controls'.
At line:1 char:1
+ nuget restore .\src\Askmethat.XForms.Controls.sln
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Ambiguous proje...orms.Controls'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: Ambiguous project name 'Askmethat.XForms.Controls'.

```

This error is thrown when nuget restore try to restore all project, it's happens with Askmethat.XForms.Controls.NuGet project.

I check all configuration files ( csproj & sln ) and I do not found any duplicate project name or package id.
I also try to check if any circular dependency exist...

The nuget restore work on my machine ( macOS : up to date ).

If I remove the package ID from the nuget it works. The problem it that stop working when I tried to release version **1.0.1-beta-1**

# .nuProj

Here the link for the nuProj

https://github.com/AlexTeixeira/Askmethat-XForms-Controls/blob/development/src/Askmethat.XForms.Controls.NuGet/Askmethat.XForms.Controls.NuGet.nuproj

# EDIT

I can repro the issue in a machine windows under Windows 10 and Last Stable version of nuget ( 4.3 )
.

The issue come from the netstandard Library :

```
<Project Sdk="Microsoft.NET.Sdk" >
  <Import Project="..\packages\Xamarin.Forms.2.4.0.38779\build\netstandard1.0\Xamarin.Forms.props" Condition="Exists('..\packages\Xamarin.Forms.2.4.0.38779\build\netstandard1.0\Xamarin.Forms.props')" />
  <Import Project="..\packages\NuGet.Build.Packaging.0.2.1\build\NuGet.Build.Packaging.props" Condition="Exists('..\packages\NuGet.Build.Packaging.0.2.1\build\NuGet.Build.Packaging.props')" />
  <PropertyGroup>
        <TargetFramework>netstandard1.5</TargetFramework>
        <TargetFrameworks>netstandard1.1;netstandard1.3;netstandard1.5;</TargetFrameworks>
        <RootNamespace>Askmethat.XForms.Controls</RootNamespace>
        <AssemblyName>Askmethat.XForms.Controls</AssemblyName>
        <ReleaseVersion>1.1.0</ReleaseVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Build.Packaging" Version="0.2.1" />
    <PackageReference Include="Xamarin.Forms" Version="2.4.0.38779" />
  </ItemGroup>
    <Import Project="..\packages\NuGet.Build.Packaging.0.2.1\build\NuGet.Build.Packaging.targets" Condition="Exists('..\packages\NuGet.Build.Packaging.0.2.1\build\NuGet.Build.Packaging.targets')" />
    <Import Project="..\packages\Xamarin.Forms.2.4.0.38779\build\netstandard1.0\Xamarin.Forms.targets" Condition="Exists('..\packages\Xamarin.Forms.2.4.0.38779\build\netstandard1.0\Xamarin.Forms.targets')" />
    <Import Project="..\Askmethat.XForms.Controls.Shared\Askmethat.XForms.Controls.Shared.projitems" Label="Shared" Condition="Exists('..\Askmethat.XForms.Controls.Shared\Askmethat.XForms.Controls.Shared.projitems')" />

</Project>

```

if I change the Assembly Name it work again. 
I cannot build the nuget package in the windows machine, I will try later if it totally correct my issue.

**Comment by emgarten** [comment]
The ambiguous error message is correct.

The name `Askmethat.XForms.Controls` is used for both:

```
Askmethat-XForms-Controls\\src\\Askmethat.XForms.Controls.NuGet\\Askmethat.XForms.Controls.NuGet.nuproj
Askmethat-XForms-Controls\\src\\Askmethat.XForms.Controls.Forms\\Askmethat.XForms.Controls.Forms.csproj
```

And the nuproj references the csproj.

During restore packages and projects are treated the same in the dependency graph, which means the package id is used.  The result is `Askmethat.XForms.Controls -> Askmethat.XForms.Controls` which is caught by restore as two projects trying to re-use the same name, which will not work.

**Comment by RVoiseyFirstApp** [comment]
Could this be a valid use case? Following the Xamarin tutorial on creating usable plugins (https://blog.xamarin.com/creating-reusable-plugins-for-xamarin-forms/) and they have the same assembly name.

I have a few different projects:
- AppUtils.Forms (common code)
- AppUtils.Android (android implementation), references AppUtils.Forms
- AppUtils.iOS (ios implementation), references AppUtils.Forms
- AppUtils.NuGet (nuget project used for packaging), references .Android and .iOS

Looking at the source for the .csproj files, they all have the same AssemblyName (AppUtils.Forms) and the .nuproj also has the package id AppUtils.Forms.

I can build it properly on my local mac machine but cannot build it on VSTS using any of the agents (using nuget v4.1.0). Any ideas? Could this be a different issue?

**Comment by bjorn-ali-goransson** [comment]
> During restore packages and projects are treated the same in the dependency graph, which means the package id is used. The result is `Askmethat.XForms.Controls -> Askmethat.XForms.Controls` which is caught by restore as two projects trying to re-use the same name, which will not work.

I'm not sure I understand. Does this mean that I can't reference a project with the same name as a project that exists on nuget? 'Cause that's what I'm experiencing right now...

It would seem then that I could break someones build by peeking at someones project names and then go publish a dummy nuget package with the same name as one of the solutions projects.

This can't be correct though can it?

**Comment by bjorn-ali-goransson** [comment]
No, wait. In my case this is because I use something for packaging referenced DLLs, and I reference two projects "packaging" the same local project.

Tell me if you'd like details on that...

The stuff in the csproj packaging the DLLs:

    <PropertyGroup>
      <TargetsForTfmSpecificBuildOutput>
        $(TargetsForTfmSpecificBuildOutput);PackReferencedProjectOutputs
      </TargetsForTfmSpecificBuildOutput>
      <PackageId>Poetry.UI.AspNetCore</PackageId>
      <Product>Poetry.UI.AspNetCore</Product>
    </PropertyGroup>

    <Target Name="PackReferencedProjectOutputs" DependsOnTargets="BuildOnlySettings;ResolveReferences">
      <ItemGroup>
        <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference')-&gt;WithMetadataValue('PrivateAssets', 'All'))" />
      </ItemGroup>
    </Target>

**Comment by bjorn-ali-goransson** [comment]
No, wait again. There it is, a stray PackageId in my targets. False alarm!!
