### ISSUE TITLE
NuGet restore failed if one source is down even all packages are in cache

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6145]
the scenario is:

one enabled source is down and all package which need to be restored are in cache.

NuGet restore still fail due to one source is down.

**Comment by anangaur** [comment]
Historical issues with sources: https://github.com/NuGet/Home/issues/4949

**Comment by emgarten** [comment]
If all packages are in the global packages folder and there are zero misses, and zero floating versions then NuGet will not attempt to go online. We should have nuget.exe tests that verify there are zero network calls.

If NuGet does need to resolve a package then it will check the sources, and in that case is needs to contact all sources to get a coherent result.

So I'm unsure that this is a real issue unless this refers only to the http cache.

**Comment by emgarten** [comment]
Steps
1. Open NuGet solution
1. Restore
1. Disconnect network
1. Restore (should pass)

Try also using -Force or removing the obj folders to ensure it still does not go online.

**Comment by emgarten** [comment]
We could improve this overall by ignoring source failures until we are sure the package doesn't exist.

**Comment by anangaur** [comment]
@emgarten, we should do the same for floating versions. May be issue warnings in this case?

**Comment by emgarten** [comment]
I'm not sure that it is safe to ignore failed sources when floating, but it could work as a warning with the option to make it an error.

**Comment by anangaur** [comment]
Yep. In addition, we could put the ignore failing sources under an option. Like we do for NuGet command line.

**Comment by jainaashish** [comment]
one more vs feedback - https://developercommunity.visualstudio.com/content/problem/157492/packages-from-nugetorg-cant-install-if-a-secondary.html

**Comment by jainaashish** [comment]
I just checked it If all packages are in the global packages folder and there are zero misses, and zero floating versions then NuGet doesn't tries to go to online. It works fine.

About ignoring failed sources, then we already have a separate workitem for that - https://github.com/NuGet/Home/issues/5643
