### ISSUE TITLE
Package restore failed. Rolling back package changes

### ISSUE THREAD

**Issue by PhilPJL** [NuGet/Home#6147]
VS version 15.4.2.

1. I have an existing .NET 4.5 project which uses packages.config
2. Change to use package references using VS extension "NuGet PackageReference Upgraded" - looks good
3. Try to downgrade a referenced package (e.g. Entity Framework from 6.2. to 6.1.3).  Get error message
  "Package restore failed. Rolling back package changes"

4. Remove package and add desired version (6.1.3) - works ok
5. Update to latest version (6.2) - works ok
6. Try to downgrade to 6.1.3 - get same error message

**Comment by zhili1208** [comment]
Could you share the error message from error list?

**Comment by PhilPJL** [comment]
The error list says: "Package restore failed. Rolling back package changes for ..."

The output window says: 
Running restore with 8 concurrent jobs.
Reading project file C:\Users\ImpPhil\source\Workspaces\HexcelAppFx\AppFramework\Hexcel.Business.Shared\Hexcel.Business.Shared.csproj.
Restoring packages for C:\Users\ImpPhil\source\Workspaces\HexcelAppFx\AppFramework\Hexcel.Business.Shared\Hexcel.Business.Shared.csproj...
Restoring packages for .NETFramework,Version=v4.5...
Resolving conflicts for .NETFramework,Version=v4.5...
Scanning packages for runtime.json files...
Restoring packages for .NETFramework,Version=v4.5/win...
Resolving conflicts for .NETFramework,Version=v4.5/win...
Restoring packages for .NETFramework,Version=v4.5/win-x64...
Resolving conflicts for .NETFramework,Version=v4.5/win-x64...
Restoring packages for .NETFramework,Version=v4.5/win-x86...
Resolving conflicts for .NETFramework,Version=v4.5/win-x86...
Dependency specified was EntityFramework (>= 6.1.3) but ended up with EntityFramework 6.2.0.
Checking compatibility of packages on .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Business.Shared 1.0.0 with .NETFramework,Version=v4.5.
Checking compatibility for EntityFramework 6.2.0 with .NETFramework,Version=v4.5.
Checking compatibility for JetBrains.Annotations 11.1.0 with .NETFramework,Version=v4.5.
Checking compatibility for Microsoft.Net.Compilers 2.4.0 with .NETFramework,Version=v4.5.
Checking compatibility for System.Interactive 3.1.1 with .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Business.Resources 1.0.0 with .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Data.Shared 1.0.0 with .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Shared.DataContracts 1.0.0 with .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Shared.Log4Net 1.0.0 with .NETFramework,Version=v4.5.
Checking compatibility for Hexcel.Shared 1.0.0.0 with .NETFramework,Version=v4.5.
All packages and projects are compatible with .NETFramework,Version=v4.5.
Checking compatibility of packages on .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Business.Shared 1.0.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for EntityFramework 6.2.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for JetBrains.Annotations 11.1.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Microsoft.Net.Compilers 2.4.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for System.Interactive 3.1.1 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Business.Resources 1.0.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Data.Shared 1.0.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Shared.DataContracts 1.0.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Shared.Log4Net 1.0.0 with .NETFramework,Version=v4.5 (win).
Checking compatibility for Hexcel.Shared 1.0.0.0 with .NETFramework,Version=v4.5 (win).
All packages and projects are compatible with .NETFramework,Version=v4.5 (win).
Checking compatibility of packages on .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Business.Shared 1.0.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for EntityFramework 6.2.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for JetBrains.Annotations 11.1.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Microsoft.Net.Compilers 2.4.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for System.Interactive 3.1.1 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Business.Resources 1.0.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Data.Shared 1.0.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Shared.DataContracts 1.0.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Shared.Log4Net 1.0.0 with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility for Hexcel.Shared 1.0.0.0 with .NETFramework,Version=v4.5 (win-x64).
All packages and projects are compatible with .NETFramework,Version=v4.5 (win-x64).
Checking compatibility of packages on .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Business.Shared 1.0.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for EntityFramework 6.2.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for JetBrains.Annotations 11.1.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Microsoft.Net.Compilers 2.4.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for System.Interactive 3.1.1 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Business.Resources 1.0.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Data.Shared 1.0.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Shared.DataContracts 1.0.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Shared.Log4Net 1.0.0 with .NETFramework,Version=v4.5 (win-x86).
Checking compatibility for Hexcel.Shared 1.0.0.0 with .NETFramework,Version=v4.5 (win-x86).
All packages and projects are compatible with .NETFramework,Version=v4.5 (win-x86).
Package restore failed. Rolling back package changes for 'Hexcel.Business.Shared'.



I am unable to reproduce this error when creating a new project, either starting with packages.config or not.

I'm also curious why we have "Dependency specified was EntityFramework (>= 6.1.3) but ended up with EntityFramework 6.2.0.".  What if I want a specific version?

**Comment by zhili1208** [comment]
Could you please share the project.asset.json file from obj folder? Did you get any error in ErrorList windows?

**Comment by PhilPJL** [comment]
Here it is.
[project.assets.json.zip](https://github.com/NuGet/Home/files/1453687/project.assets.json.zip)

**Comment by zhili1208** [comment]
For this case, "Dependency specified was EntityFramework (>= 6.1.3) but ended up with EntityFramework 6.2.0", it's a warning by default and caused by "Another dependency package required a higher version and bumped the package up.", but since your project set allWarningsAsErrors to true, it failed restore.

**Comment by emgarten** [comment]
Per @zhili1208's comment it looks like NuGet is behaving as expected here.

**Comment by PhilPJL** [comment]
I don't agree - the comment about was about my question "Dependency specified was EntityFramework (>= 6.1.3) but ended up with EntityFramework 6.2.0" - I'll accept that.

Why I get "Package restore failed. Rolling back package changes." hasn't been explained.

**Comment by emgarten** [comment]
A rollback will happen if there is an error during restore.

Since you have warnings as errors enabled, any warning that happens during the install/restore will cause the install to fail and rollback.
