### ISSUE TITLE
[NuGet.VisualStudioExtension] Packages without references cannot be updated

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#615]
I have a VS 2015 RC solution. When searching for updates, it somehow doesn't pick up updates for Fody (a package that doesn't install any references). Installed version is 1.26.1, but according to NuGet, it should see the update 1.28.3.

**Comment by GeertvanHorrik** [comment]
Calling this in the package manager console works though:

PM> Update-Package Fody

**Comment by GeertvanHorrik** [comment]
What I did:

1) Open existing solution where some projects already had 1.28.3
2) Create new project
3) Install Fody (via "installed packages") into the new project
4) 1.26.1 gets installed => no way to upgrade via UI

**Comment by feiling** [comment]
Don't repro with the current dev branch. Whatever the original bug must have been fixed.
