### ISSUE TITLE
VSTO VS2017 hosted build of unit test project with project reference to a Web UI project - nuget restore fails with error NU1105

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6157]
@IainmXray commented on [Thu Nov 02 2017](https://github.com/NuGet/NuGetGallery/issues/4944)

I have already raised this issue via Microsoft support ticket and have been asked by them to raise a ticket here as have suggested that it is a Nuget issue.

Nuget resolve is working locally but failing on the VSTO hosted VS2017 build server with the following error:

2017-10-31T16:04:14.5903315Z d:\a\1\s\Link.Ui.UnitTest\Link.Ui.UnitTest.csproj : error NU1105: Unable to find project information for 'd:\a\1\s\Link.Ui\Link.Ui.csproj'. The project file may be invalid or missing targets required for restore.

I am attaching the source code used in the build
[Link.Ui.zip](https://github.com/NuGet/NuGetGallery/files/1438277/Link.Ui.zip)

[logs_436.zip](https://github.com/NuGet/NuGetGallery/files/1438254/logs_436.zip)

**Comment by emgarten** [comment]
@IainmXray in order to help you I need:

1. Repro steps for how you are running restore (ex: VS, dotnet.exe, nuget.exe)
1. Please include the version of nuget that you are using.

I also suggest retrying with the latest 4.4.0 version of nuget.
