### ISSUE TITLE
SSL misconfigured on nuget.org

### ISSUE THREAD

**Issue by hickford** [NuGet/Home#616]
I found a problem with the SSL configuration for https://www.nuget.org , the Strict-Transport-Security header is invalid due to a typo

    > http -h get https://www.nuget.org
    HTTP/1.1 200 OK
    Strict-Transport-Security: maxage=31536000; includeSubDomains

It should be `max-age` with a hyphen per https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security#Enabling_Strict_Transport_Security

See also https://www.ssllabs.com/ssltest/analyze.html?d=nuget.org

**Comment by yishaigalatzer** [comment]
Thanks for a cool bug and a PR
