### ISSUE TITLE
dotnet pack produces an invalid symbols package under linux

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6160]
_From @sheltonc on October 4, 2017 5:2_

The following repository contains scripts and a sample project to reproduce the issue. You will need docker installed.

https://bitbucket.org/sheltony/dotnetpackbug

The sample dotnet project contains two classes
- dotnetPackBug.Class1
- dotnetPackBug.Namespace.Class2

To run this, just execute **run.ps1**

You'll end up with two folders **WindowsOut** and **LinuxOut**, Each of which will have **dotnetPackBug.1.0.0.symbols.nupkg**, which you can use to observe the following:

When creating a symbols package under windows, the output symbols.nupkg output contains a valid package. Inside the nupkg. we have a src folder with the following structure.

```
WindowsOut/dotnetPackBug.1.0.0.symbols.nupkg
src
    dotnetPackBug
        Namespace
            Class2.cs
        dotnetPackBug.csproj
        Class1.cs
```

However, under linux, the same command produces a package with the following incorrect structure:

```
LinuxOut/dotnetPackBug.1.0.0.symbols.nupkg
src
    dotnetPackBug
        dotnetPackBug.csproj
        Class1.cs
```

You can see that any source files that are not at the root level in the dotnet project (e.g. everything in a namespace) are not included in the symbols package in the src folder. They're in fact included in the package at the wrong level (the root level of the package).

_Copied from original issue: dotnet/cli#7759_

**Comment by livarcocc** [comment]
Moving this to NuGet so that they can have first look. If this turns out to be an issue in the SDK, please move it back.

**Comment by rohit21agrawal** [comment]
what version of dotnet are you using? we have fixed related issues in the newer releases.

**Comment by sheltonc** [comment]
microsoft/dotnet:2.0.0-sdk

**Comment by rohit21agrawal** [comment]
@sheltonc that doesn't tell me anything. please paste the output of ``` dotnet --version ``` here.

Or it would be even better if you could scroll down the page on https://github.com/dotnet/cli/tree/release/15.5 and download the appropriate cli+sdk for your OS, and give it a shot as those are the latest versions

**Comment by sheltonc** [comment]
The version is 2.0.3

**Comment by rohit21agrawal** [comment]
@sheltonc i just tried the latest dotnet sdk for linux (downloaded from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/release/15.5/dotnet-sdk-latest-linux-x64.tar.gz version 2.1.1-preview-007216 ) and ran it on your sample on an ubuntu 16.04 machine, and it works as expected.

**Comment by rohit21agrawal** [comment]
closing because of lack of response. please feel free to reactive if using the above version still repros the issue.
