### ISSUE TITLE
NuGet pack task leaves the resulting .nupkg files locked

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#6165]
PackTask leaves the .nupkg files it produces locked even after it finishes running. Processes running after the task might thus fail due to access violation.

The issue is likely in ```PackCommandRunner.BuildPackage```: 

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/CommandRunners/PackCommandRunner.cs#L84

where the instance of ```PackageArchiveReader``` is not disposed. This instance holds on an open stream which keeps the output file locked until it is collected by GC.

A quick fix would be to call dispose like so:

```C#
public void BuildPackage()
{
  PackageArchiveReader package = BuildPackage(Path.GetFullPath(Path.Combine(_packArgs.CurrentDirectory, _packArgs.Path)));
  package?.Dispose();
}
```

It seems though that ```PackageArchiveReader``` doesn't even need to be created in the first place, which would be even better fix.

**Comment by nkolev92** [comment]
Thanks for the issue and analysis @tmat.
What you recommend seems like the correct way to go.

**Comment by tmat** [comment]
@rrelyea Submitted PR with a fix. Can we get it into next release?

**Comment by rrelyea** [comment]
@nkolev92 - thanks for making this happen.
@tmat - appreciate the issue and the pr. thx.
