### ISSUE TITLE
dotnet pack doesn't honor AppendTargetFrameworkToOutputPath in package structure

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6184]
_From @thomaslevesque on November 8, 2017 11:44_

[This project](https://github.com/FakeItEasy/FakeItEasy/blob/8f649f313f8afaa35871475ca00ae94a55db91ec/src/FakeItEasy.Analyzer/FakeItEasy.Analyzer.CSharp.csproj) used to produce the following package structure with the 1.0.4 SDK:

![image](https://user-images.githubusercontent.com/1864281/32543775-d0b3abc4-c476-11e7-9690-d58de230462d.png)

But with the 2.0.2 SDK, it produces this instead:

![image](https://user-images.githubusercontent.com/1864281/32543798-e903c2a4-c476-11e7-9cd2-df7916c9f368.png)

It looks like the `AppendTargetFrameworkToOutputPath` property is ignored by `dotnet pack`.

Is this change intentional? Is there a workaround?

_Copied from original issue: dotnet/sdk#1717_

**Comment by emgarten** [comment]
_From @thomaslevesque on November 8, 2017 14:4_

Apparently, including the TFM in the path is [hard-coded](https://github.com/NuGet/NuGet.Client/blob/eb6fe311289908d5e1fe6f644030c704be2bc15c/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L142) and can't be disabled...

For the project I mentioned, it generates an analyzer packages that installs correctly in SDK-style projects, but not in classic csproj (the analyzer is not referenced).

**Comment by emgarten** [comment]
_From @livarcocc on November 9, 2017 3:6_

@emgarten Is this something that NuGet relies on the SDK for or is NuGet doing its own path calculation for the folder under pack?

**Comment by emgarten** [comment]
I'm not completely sure if NuGet appends the TFM to $(BuildOutputTargetFolder) here, or how this is getting added. 

//cc @rohit21agrawal for pack

**Comment by emgarten** [comment]
_From @thomaslevesque on November 10, 2017 16:18_

> I'm not completely sure if NuGet appends the TFM to $(BuildOutputTargetFolder) here, or how this is getting added.

From the [code I linked to](https://github.com/NuGet/NuGet.Client/blob/eb6fe311289908d5e1fe6f644030c704be2bc15c/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L142), it seems pretty clear that it does ;)

**Comment by emgarten** [comment]
_From @livarcocc on November 10, 2017 16:50_

I agree with @thomaslevesque. It seems NuGet is the one that is doing this and not honoring the Append property.

**Comment by emgarten** [comment]
_From @blairconrad on November 14, 2017 2:38_

> It seems NuGet is the one that is doing this and not honoring the Append property.

Does this mean that the issue should move to NuGet/NuGet.Client?

**Comment by rohit21agrawal** [comment]
i disagree that pack should honor this property. This will lead to cases where DLLs are put right under lib folder and we don't want to encourage such packages.

Pack can only honor a property like this when restore knows how to make sense of these files without them being in the TFM folder - in those cases, users can manually set package paths.

**Comment by emgarten** [comment]
Closing based on @rohit21agrawal's answer. This seems like the expected behavior.

**Comment by blairconrad** [comment]
>  This will lead to cases where DLLs are put right under lib folder and we don't want to encourage such packages.
> Pack can only honor a property like this when restore knows how to make sense of these files without them being in the TFM folder

Visual Studio knows how to use Roslyn Analyzers when the files don't live in the TFM folder, and requires it when the project importing the analyzer is a classic csproj style.

Just to make sure I understand, the official position is that if we're producing a Roslyn analyzer package that is intended to be used from classic csproj projects (as well as the new SDK-style projects), we should revert to using a nuspec + nuget.exe instead of `dotnet pack`?

**Comment by rohit21agrawal** [comment]
No. Dotnet pack can still do what you want to do. I will post a solution for you in a couple of hours

**Comment by rohit21agrawal** [comment]
extension point has been provided for files that need to go in the nupkg outside of lib folder but are still target framework dependent in context of build. A user can write their own custom target and specify it as the value of the property ```$(TargetsForTfmSpecificContentInPackage)```. The target should write out any files that need to be included in the nupkg into the ItemGroup ```TfmSpecificPackageFile``` and set the following metadata:
a) PackagePath : Path where the file should be output in the package. NuGet will throw a warning if more than one file is added to the same package path. This is where you will set your .dll path to ```analysers\dotnet\cs```
b) BuildAction: Default value has been set to None. This is only required if the package path is in contentFiles folder.

```
<Target Name="GetMyPackageFiles">
  <ItemGroup>
    <TfmSpecificPackageFile Include="$(OutputPath)$(AssemblyName).dll">
           <PackagePath>analysers/dotnet/cs</PackagePath
    </TfmSpecificPackageFile>
  </ItemGroup>
</Target>
```

**Comment by thomaslevesque** [comment]
Thanks @rohit21agrawal, I'll give it a try.

**Comment by blairconrad** [comment]
Indeed thanks, @rohit21agrawal. I'd've responded earlier, but hadn't yet had a chance to try it out. @thomaslevesque was able to apply the technique to our project: FakeItEasy/FakeItEasy#1274.

**Comment by thomaslevesque** [comment]
I looked at the new analyzer project templates, and they're using a simpler approach: https://gist.github.com/thomaslevesque/a49864fc64db661d627fdad7508a28e0#file-analyzer1-csproj

(relevant parts on lines 5 and 37)

**Comment by jnm2** [comment]
@thomaslevesque You're a lifesaver!

Current template:
https://github.com/dotnet/roslyn-sdk/blob/master/src/VisualStudio.Roslyn.SDK/Roslyn.SDK/ProjectTemplates/CSharp/Diagnostic/Analyzer/DiagnosticAnalyzer.csproj

Sample:
https://github.com/dotnet/roslyn-sdk/blob/master/samples/CSharp/Analyzers/Analyzers.Implementation/Analyzers.CSharp.csproj
