### ISSUE TITLE
dotnet add no longer updates the package

### ISSUE THREAD

**Issue by rlm95** [NuGet/Home#6189]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
  - dotnet.exe 

dotnet.exe --version (if appropriate):
  - 2.0.2

OS version (i.e. win10 v1607 (14393.321)):
  - win10 v1607 (14393.1770)

Worked before? If so, with which NuGet version:
  - worked with dotnet.exe version 2.0.2 
## Detailed repro steps so we can see the same problem

1.  In a folder with a .csproj file with an out of date nuget package (ex: Newtonsoft.Json version 10.0.2) run command dotnet add package Netwonsoft.Json 

2.  Should automatically try to update package and restore nuget

...

#### Logs from dotnet.exe version 2.0.0 (EXPECTED)
PS C:\sampleProject\sampleProject> dotnet add package newtonsoft.json
  Writing C:\Users\millrya\AppData\Local\Temp\tmp3753.tmp
info : Adding PackageReference for package 'newtonsoft.json' into project 'C:\sampleProject\sampleProject\sampleProject.csproj'.
log  : Restoring packages for C:\sampleProject\sampleProject\sampleProject.csproj...
info :   CACHE http://proget.chrobinson.com/nuget/Pre-release/FindPackagesById()?id='Newtonsoft.Json'
info :   CACHE http://proget.chrobinson.com/nuget/Release/FindPackagesById()?id='Newtonsoft.Json'
info :   CACHE https://api.nuget.org/v3-flatcontainer/newtonsoft.json/index.json
info : Package 'newtonsoft.json' is compatible with all the specified frameworks in project 'C:\sampleProject\sampleProject\sampleProject.csproj'.
info : PackageReference for package 'newtonsoft.json' version '10.0.3' updated in file 'C:\sampleProject\sampleProject\sampleProject.csproj'.
PS C:\sampleProject\sampleProject>

#### Logs from dotnet.exe version 2.0.2 (ACTUAL)
PS C:\sampleProject\sampleProject> dotnet add package newtonsoft.json
  Writing C:\Users\millrya\AppData\Local\Temp\tmp3A42.tmp
info : Adding PackageReference for package 'newtonsoft.json' into project 'C:\sampleProject\sampleProject\sampleProject.csproj'.
log  : Restoring packages for C:\sampleProject\sampleProject\sampleProject.csproj...
info : Package 'newtonsoft.json' is compatible with all the specified frameworks in project 'C:\sampleProject\sampleProject\sampleProject.csproj'.
info : PackageReference for package 'newtonsoft.json' version '10.0.2' updated in file 'C:\sampleProject\sampleProject\sampleProject.csproj'.
PS C:\sampleProject\sampleProject>

### Sample Project

[sampleProject.zip](https://github.com/NuGet/Home/files/1475935/sampleProject.zip)

**Comment by nkolev92** [comment]
Thanks for reporting the issue @rlm95. 
We will look into it.

**Comment by nkolev92** [comment]
Self-assigning as this should be resolved by my fix for VSTS bug 521955.

Even though they're dups, they manifest in totally different ways, so keeping it open for better visibility.
