### ISSUE TITLE
Nuget needs to handle .NETPortable,Version=v5.0 as core50

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#619]
We won't be burning in nuget short names to project.json and instead will have the full moniker.  For PCLs this will be .NETPortable,Version=v5.0 (without any profile).  We expect nuget/dnx to accept this and treat it in the same way it does other new TFMs, falling back to core50.  //cc @emgarten @rchande @pilchie @jasonmalinowski

**Comment by emgarten** [comment]
netportable50

**Comment by emgarten** [comment]
Added support for .NETPlatform,Version=v5.0

NuGet/Nuget3@ad6ccc039ff9f8ff1ed15465ce5d06deb8b9bc0f
