### ISSUE TITLE
how to integrate .net application with Nuget in jenkins

### ISSUE THREAD

**Issue by bhanu1989** [NuGet/Home#6190]
please help me with integrating .net application with nuGet in jenkins and deploy it in IIS

**Comment by nkolev92** [comment]
Thanks for creating the issue @bhanu1989 
Unfortunately I do not think we can help you with much here. 

NuGet is just one minor component of the whole build process and we provide a nuget.exe which you can download [here](nuget.org/downloads) and use on your CI. 

Start with Jenkins docs and the the [dotnet docs](https://docs.microsoft.com/en-us/dotnet/index). 

The NuGet docs are [here](https://docs.microsoft.com/en-us/nuget/).
