### ISSUE TITLE
Downloading Nuget.exe from dist.nuget.org blocked

### ISSUE THREAD

**Issue by georgecheyne** [NuGet/Home#6191]
Hi, 

I'm not certain if this is the right issue tracker maybe it should be in the one for the website?

Anyway the url:

https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

to download nuget.exe is being blocked in my company.  Apparently dist.nuget.org has been marked as suspicious as per this site:

https://sitereview.bluecoat.com/sitereview.jsp#/?search=https%3A%2F%2Fdist.nuget.org

This means our security systems block us from downloading it.

I thought you might want to fill out the form about getting the suspicious status removed.

Thanks,

George

Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
@joelverhagen Any ideas?

**Comment by nkolev92** [comment]
Issue moved to [NuGet/NuGetGallery #5018](https://github.com/NuGet/NuGetGallery/issues/5018) via [**ZenHub**](https://www.zenhub.com/)
