### ISSUE TITLE
Package Manager Console (PMC): Sorting in "default project" combobox changes after selection

### ISSUE THREAD

**Issue by greenmooseSE** [NuGet/Home#6194]
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **Package Manager Console**
NuGet version (x.x.x.xxx): **Manager Console Host Version 4.4.1.4633**
VS version (if appropriate): **2017**

OS version (i.e. win10 v1607 (14393.321)): **Win10 1703**

Worked before? If so, with which NuGet version: **Not sure**

## Detailed repro steps so we can see the same problem
1. Have project structure in src and test folders with different names.
1. Try to pick different projectds in "Default project" combo, notice the sorting is incorrect (sometimes when selecting an item a totally different item ends up being selected so you accidentally manage packages in wrong project).

## Other suggested things
Using dotnet core 2, vstudio 2017 15.4.4
in below screenshots I simply click the combo and it change every time (I am not selecting anything)
![image](https://user-images.githubusercontent.com/31244330/32938637-21bbee98-cb7d-11e7-9efb-c94443c533b0.png)

*Edit: I have other issues with PMC as well: init.ps1 is not executed any longer, it crashes vstudio from time to time (e.g. when doing a simple "dir <folder>") due to "app hang". Using "Manage packages for solution" in UI works though so PMC is pretty much unusable for me currently. Is there a way I can update the PMC only?

**Comment by nkolev92** [comment]
@GreenMooseWork Thanks for reporting this issue.

We are aware of this particular issue and we already have a [fix](https://github.com/NuGet/NuGet.Client/pull/1794) for the 15.5 release. 
If you are using the 15.5 preview channel, it already is in the latest preview, so feel free to check it out.

**Comment by rrelyea** [comment]
dupe bug scraped from the "fix" PR link above is:
* 513587, feedback here https://developercommunity.visualstudio.com/content/problem/134981/package-manager-conole-default-project-dropdown-no.html
