### ISSUE TITLE
Filter /tools on only TFM and RID, so the settings XML can be put in /tools folder

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6197]
## Additional requirement:

To support filter with sub folder
Given following folder structure,
```
├───tools                                                  
│   └───netcoreapp2.0                                      
│       └───any                                            
│           │   DotnetToolSettings.xml                     
│           │                                              
│           ├───tool1                                      
│           │       Newtonsoft.Json.dll                    
│           │       tool1.dll                              
│           │       tool1.json                             
│           │       tool1.pdb                              
│           │       tool1.runtimeconfig.json               
│           │                                              
│           └───tool2                                      
│                   Newtonsoft.Json.dll                    
│                   tool2.dll                              
│                   tool2.json                             
│                   tool2.pdb                              
│                   tool2.runtimeconfig.json               
│                                                          
```
Both
``` 
tools/netcoreapp2.0/any/tool1/tool1.dll
tools/netcoreapp2.0/any/tool1/tool1.runtimeconfig.json
...
and
tools/netcoreapp2.0/any/tool2/tool2.dll
tools/netcoreapp2.0/any/tool2/tool2.runtimeconfig.json
...
```
Should be in asset.json-target-tools session.

**Comment by wli3** [comment]
CLI ask for tools

**Comment by emgarten** [comment]
@wli3 can you can some extra template paths to get this started? Will this need support for the `runtimes/{rid}/native/` equivalent, or just `runtimes/{rid}/lib/{tfm}`

**Comment by wli3** [comment]
> can you can some extra template paths to get this started?

Sorry, could you add more detail of this question? Do you mean if I can get it started without blocking? Today, as in https://github.com/dotnet/cli/pull/8035 without nuget filter,  I am downloading everything

**Comment by wli3** [comment]
> Will this need support for the runtimes/{rid}/native/ equivalent, or just runtimes/{rid}/lib/{tfm}

Yes, we do need support for `native`. A folder named `native` is the same convention as in /lib folder right? 

In the end, we need a place to store native tools, and NuGet can filter by TFM(including native) and RID, however, we hope the folder structure to be close to existing NuGet conversion, or what NuGet think is the best.

**Comment by emgarten** [comment]
Native is similar, but there is no TFM.

**Comment by wli3** [comment]
We decide off line. The folder structure should be

`tools/{TFM}/{RID}/mytool.dll`

For portable, it should be
`tools/{TFM}/any/mytool.dll`

https://github.com/dotnet/cli/issues/8133

**Comment by wli3** [comment]
FYI to unify the term "metadata xml" should be called "settings xml" file

**Comment by wli3** [comment]
Added the subfolder support we talked about today

**Comment by nkolev92** [comment]
Closed in https://github.com/NuGet/NuGet.Client/pull/1900
