### ISSUE TITLE
Allow nuget.config probing start path to be able to set in project file

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6199]
Tools CLI ask

**Comment by emgarten** [comment]
@wli3 as a workaround until this is added you might be able to use `RestoreSolutionDirectory`

Relevant code is here:
* https://github.com/NuGet/NuGet.Client/blob/572962f1b1ee890533e5a75163264bd021426dc7/src/NuGet.Core/NuGet.Build.Tasks/GetRestoreSettingsTask.cs#L115
* https://github.com/NuGet/NuGet.Client/blob/572962f1b1ee890533e5a75163264bd021426dc7/src/NuGet.Core/NuGet.Build.Tasks/RestoreSettingsUtils.cs#L19

**Comment by nkolev92** [comment]
Added RestoreRootConfigDirectory
