### ISSUE TITLE
Content Packages - Friendly Error Messages

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#620]
In the ASP.NET 5 environment, NuGet does not install content packages and does not execute powershell scripts.  NuGet should display an appropriate message in the console if content is not handled and possibly emit an appropriate link to search bower.io (something like http://bower.io/search/?q=jquery) for an appropriate package.

**Comment by yishaigalatzer** [comment]
This is an ASP.NET bug, please move over.
