### ISSUE TITLE
Provide verson 4.4.1 of nuget.commandline package

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#6203]
Latest published version of the [nuget.commandline package](https://www.nuget.org/packages/NuGet.CommandLine/) on nuget.org is 4.4.1-svc. 

What does the `svc` stand for here? 
Would it be possible to also release 4.4.1 final as it is now the latest recommended download?

**Comment by nkolev92** [comment]
@pascalberger 
I will upload that version today, didn't want to do it on Friday, just in case we run into issues with people have nuget update -self in the build scripts/CIs
