### ISSUE TITLE
Nuget Support does not work with Visual Studio for Mac

### ISSUE THREAD

**Issue by petersuwara** [NuGet/Home#6204]
## Details about Problem

Piotrs-MacBook-Pro:ContosoUniversity piotrsuwara$ dotnet add package Microsoft.VisualStudio.Web.CodeGeneration
  Writing /var/folders/c9/z9kxysr57hb5m7npd1lgtm400000gn/T/tmpfn7AP0.tmp
info : Adding PackageReference for package 'Microsoft.VisualStudio.Web.CodeGeneration' into project '/Users/piotrsuwara/Development/ContosoUniversity/ContosoUniversity/ContosoUniversity.csproj'.
log  : Restoring packages for /Users/piotrsuwara/Development/ContosoUniversity/ContosoUniversity/ContosoUniversity.csproj...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   An error occurred while sending the request.
error:   Couldn't connect to server

NuGet product used (VS UI | Package Manager Console):

NuGet version (4.3.0.5):

dotnet.exe --version (2.0.0):

VS version (if appropriate): 7

OS version (i.e. win10 v1607 (14393.321)): OS X High Sierra

Worked before? If so, with which NuGet version: No has not worked

## Detailed repro steps so we can see the same problem

Try adding any NuGet package. api.nuget.org is not reachable.

1.
dotnet add package Microsoft.VisualStudio.Web.CodeGeneration

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by petersuwara** [comment]
If I VPN to a USA IP Address I can access api.nuget.org.

Go figure...

**Comment by petersuwara** [comment]
How on earth are you managing the hosting if it only runs via US IP ? What about the rest of the world ?

**Comment by emgarten** [comment]
This issue was moved to NuGet/NuGetGallery#5041
