### ISSUE TITLE
Is there any way to transform Views/_ViewImports.cshtml on instaling nuget package for asp.net project

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6207]
@WeihanLi commented on [Wed Nov 15 2017](https://github.com/NuGet/NuGetGallery/issues/5014)

Is there any way to transform Views/_ViewImports.cshtml on instaling nuget package for asp.net project?

I wanna transform the file like transform web.config or app.config, but I don't know how.

**Comment by jainaashish** [comment]
You can always use msbuild targets to apply xdt transform files to transform web.config or app.config files.

Look at a sample solution - https://github.com/NuGet/Samples/tree/master/XDTransformExample
You can also look at some documentation around it, but keep it in mind this docs was written keeping `packages.config` in mind so dont follow this documentation. Just get a idea from that and use targets to apply transform files.

**Comment by WeihanLi** [comment]
Hi @jainaashish  .I've read the document,but the file I wanna change is not web.config or app.config.So I'm wondering if there is a solution for change any other files other than web.config or app.config

**Comment by jainaashish** [comment]
Not that NuGet provide anything out of the box. But you can try that with MSBuild targets if that can work for you.

**Comment by WeihanLi** [comment]
OK. I'll try. Thanks.
