### ISSUE TITLE
`NuGet.CommandLine.XPlat  package add` support `--config` 

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6210]
CLI tools ask (optional).

Without this CLI are coping the config file to the temporary project root. It would be real nice to have this opinion so only path to the nuget config file is needed.

**Comment by nkolev92** [comment]
Discussed offline, this is nice to have, but not a priority or a requirement for global tools.

**Comment by jainaashish** [comment]
design has changed so it is no more required.

**Comment by wli3** [comment]
Hi @jainaashish Could you illustrate the design change? For global tools, we are using a non ideal walk around(copy the config file to fake project location). We still hope this feature can be implemented

**Comment by jainaashish** [comment]
@nkolev92 can give more details here. Since he suggested that we don't need this feature anymore.

**Comment by nkolev92** [comment]
@wli3 
The add command is not used in the global tools implementation though. 

We're using the MsBuild property to set the starting point to iterate the config file.

**Comment by wli3** [comment]
Thanks! This issue is no longer needed.

I can replace dotnet add with restore with version * and add RestoreConfigFile to fake project
