### ISSUE TITLE
Resolve open questions about SignedPackageArchive Verification

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6211]
Open questions - 

For all NuGet packages that will be signed/verified.
+ Is it safe to asume we don't have an encryption header?
+ Is it safe to asume we don't have a data descriptor?
+ Is it safe to asume we don't have Archive Decryption Header and Archive Extra data record?

**Comment by PatoBeltran** [comment]
We should not assume anything about the archive. Code should be general enough to handle this.
