### ISSUE TITLE
Build instructions for NuGet.Client don't work

### ISSUE THREAD

**Issue by cclauson** [NuGet/Home#6214]
The build instructions for NuGet.Client don't work for me, and fail with the following errors:

RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(6,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.c
sproj]
RestoreCommand\ContentFiles\FileProviderGlobbingFile.cs(5,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj
]
RestoreCommand\ContentFiles\VirtualFileInfo.cs(7,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]
(etc...)

I pulled origin/master on 11/21/2017.  I have both Visual Studio 2015 and 2017 Enterprise installed.  Windows Enterprise 10.0.15063.  Build instructions are to execute /configure.ps1 and then ./build.ps1 in powershell.

Full error text:
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(6,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.c
sproj]
RestoreCommand\ContentFiles\FileProviderGlobbingFile.cs(5,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj
]
RestoreCommand\ContentFiles\VirtualFileInfo.cs(7,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]
RestoreCommand\ContentFiles\VirtualFileProvider.cs(7,17): error CS0234: The type or namespace name 'AspNet' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(104,52): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.
csproj]
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(17,26): error CS0246: The type or namespace name 'IFileProvider' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Comman
ds.csproj]
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(18,26): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.c
sproj]
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(23,13): error CS0246: The type or namespace name 'IFileProvider' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Comman
ds.csproj]
RestoreCommand\ContentFiles\FileProviderGlobbingDirectory.cs(24,13): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.c
sproj]
RestoreCommand\ContentFiles\FileProviderGlobbingFile.cs(17,41): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj
]
RestoreCommand\ContentFiles\VirtualFileInfo.cs(11,38): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]
RestoreCommand\ContentFiles\VirtualFileProvider.cs(15,42): error CS0246: The type or namespace name 'IFileProvider' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]
RestoreCommand\ContentFiles\VirtualFileProvider.cs(27,16): error CS0246: The type or namespace name 'IDirectoryContents' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.cs
proj]
RestoreCommand\ContentFiles\VirtualFileProvider.cs(73,16): error CS0246: The type or namespace name 'IFileInfo' could not be found (are you missing a using directive or an assembly reference?) [D:\git\NuGet.Client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj]

**Comment by PatoBeltran** [comment]
Hey @cclauson thanks for submitting your issue. I'm trying to understand why you are seeing these errors.

Did you download the code from the client repository (https://github.com/NuGet/NuGet.Client)? We don't have a `master` branch, we have the latest development in the `dev` branch. Did you try using that one to build?

Building the repository should be as easy as running the `configure.ps1` script followed by the `build.ps1` script (if building from a windows machine) once you have the latest code from `dev`.

**Comment by cclauson** [comment]
I git cloned this URL:
https://github.com/NuGet/NuGet.Client.git
I seem to be on the dev branch (sorry, it seems I misstated this in my original post).

Since posting this, I have gotten it to build, but I had to change the source code to do it.  Specifically, I had to change "using Microsoft.AspNet.FileProviders" to "Microsoft.Extensions.FileProviders" on a few files, manually get this source code:
https://github.com/aspnet/AspLabs
And copy it into the directory required by the NuGet.Commands csproj.

I checked my git repository, I do seem to be on dev.

**Comment by cclauson** [comment]
More specifically, if you look at NuGet.Commands.csproj, you will find the following line:

    <Compile Include="..\..\..\submodules\FileSystem\src\Microsoft.Extensions.FileSystemGlobbing\**\*.cs;..\..\..\submodules\FileSystem\src\Microsoft.AspNet.FileProviders.Abstractions\**\*.cs;..\..\..\submodules\FileSystem\src\Microsoft.AspNet.FileProviders.Sources\**\*.cs;..\..\..\submodules\Common\src\Microsoft.Extensions.Primitives\IChangeToken.cs" Exclude="..\..\..\submodules\FileSystem\src\**\AssemblyInfo.cs;bin\**;obj\**;**\*.xproj;packages\**" />

I had to get this source code and populate these directories manually.  Also the version of the source was not up to date with the source code, so I ended up manually changing the nuget source to agree with changes there (renames, etc).

**Comment by PatoBeltran** [comment]
It is good to see that you found a workaround this issue. Yeah, we have those repos managed as submodules in our code. I will investigate this issue to see why you were seeing this problem and we weren't. Thanks for taking the time to open this issue and investigate!

I will close this as it has been resolved and a workaround has been provided. Please feel free to reopen it if you feel like it hasn't been solved!
