### ISSUE TITLE
Issue in Publish NuGet packages by CLI

### ISSUE THREAD

**Issue by Abbas1546** [NuGet/Home#6218]
I got the below error messages while trying to publish my NuGet packages in Staging NuGet server by CLI.

**Commands**:
>nuget setApiKey <MY_API_KEY> -Source https://staging.nuget.org/api/v2/
The API Key '<MY_API_KEY>' was saved for 'https://staging.nuget.org/api/v2/'.

>nuget push D:\F\NuGetTest\Common\MySample.15.4.0.17.nupkg -Source https://staging.nuget.org/api/v2/

**Error Message:** 
Pushing MySample.15.4.0.17.nupkg to 'https://staging.nuget.org/api/v2/'...
PUT https://staging.nuget.org/api/v2/
**InternalServerError https://staging.nuget.org/api/v2/ 4429ms**
PUT https://staging.nuget.org/api/v2/
**InternalServerError https://staging.nuget.org/api/v2/ 2398ms**
PUT https://staging.nuget.org/api/v2/
**InternalServerError https://staging.nuget.org/api/v2/ 1760ms**

**Response status code does not indicate success: 500 (Internal Server Error).**

Anyone please help me to figure it out ?

**Comment by rohit21agrawal** [comment]
@joelverhagen any idea what might be going on here?

**Comment by anangaur** [comment]
This should be temporary and we have already fixed the issue. @Abbas1546 can you check if this works for you now?

**Comment by jainaashish** [comment]
Should be fixed by now, let us know if there's still any issue.
