### ISSUE TITLE
Read the lock file in Restore and check for locked:true

### ISSUE THREAD

**Issue by anurse** [NuGet/Home#622]
If the lock file exists and contains "locked: true", it should be used to constrain the packages that are restored. This code needs to be added to `RestoreCommand`.

**Comment by yishaigalatzer** [comment]
We changed our design, and we think we can't just port it like with thought initially - so this looks like a 1-2 days of work, will probably happen next week.

**Comment by yishaigalatzer** [comment]
This is a new scenario - locked lock files are not supported yet.
