### ISSUE TITLE
Cannot restore packages on Linux from repository with auth

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#6221]
dotnet 2.0.3 on Linux Ubuntu 14.04

I want to install a package from my internal nuget repository (Artifactory). 
The repository works fine. I can install the package on Windows machines.
The repository requires authentication. As nuget on Linux still (how long folks?) doesn't support encrypted passwords I specify credentials in clear text in nuget.config. I did it inside a local `NuGet.Config` (besides csproj):
```
<configuration>
  <packageSources>
    <add key="rnd-virtual" value="https://company/api/nuget/nuget-virtual" />
  </packageSources>
  <packageSourceCredentials>
    <rnd-virtual>
      <add key="Username" value="user" />
      <add key="ClearTextPassword" value="password" />
    </rnd-virtual>
  </packageSourceCredentials>
</configuration>
```

Then I run `dotnet restore` (csproj already has a reference):
```
shrike@ubuntu:~/work/rnd/demo/Server$ dotnet restore --verbosity d
[SKIPPED]

     1>/home/shrike/work/rnd/demo/Server/Server.csproj : error NU1101: Unable to find package Croc.XFW3.DotnetCliTool. No packages exist with this id in source(s): nuget.org, rnd-virtual
     1>/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Value cannot be null. [/home/shrike/work/rnd/demo/Server/Server.csproj]
/usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Parameter name: path [/home/shrike/work/rnd/demo/Server/Server.csproj]
         System.ArgumentNullException: Value cannot be null.
         Parameter name: path
            at System.IO.Path.GetFullPath(String path)
            at NuGet.Commands.RestoreCommand.GetAssetsFilePath(LockFile lockFile)
            at NuGet.Commands.RestoreCommand.<ExecuteAsync>d__8.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Commands.RestoreRunner.<ExecuteAsync>d__7.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Commands.RestoreRunner.<ExecuteAndCommitAsync>d__6.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Commands.RestoreRunner.<CompleteTaskAsync>d__9.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Commands.RestoreRunner.<RunAsync>d__2.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Commands.RestoreRunner.<RunAsync>d__0.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at NuGet.Build.Tasks.RestoreTask.<ExecuteAsync>d__31.MoveNext()
       Done executing task "RestoreTask" -- FAILED.
     1>Done building target "Restore" in project "Server.csproj" -- FAILED.
     1>Done Building Project "/home/shrike/work/rnd/demo/Server/Server.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

       "/home/shrike/work/rnd/demo/Server/Server.csproj" (Restore target) (1) ->
       (Restore target) -> 
         /home/shrike/work/rnd/demo/Server/Server.csproj : error NU1101: Unable to find package Croc.XFW3.DotnetCliTool. No packages exist with this id in source(s): nuget.org, rnd-virtual
         /usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Value cannot be null. [/home/shrike/work/rnd/demo/Server/Server.csproj]
       /usr/share/dotnet/sdk/2.0.3/NuGet.targets(102,5): error : Parameter name: path [/home/shrike/work/rnd/demo/Server/Server.csproj]

    0 Warning(s)
    2 Error(s)
```

**What to do?**

**Comment by evil-shrike** [comment]
On another machine in WSL I've created a global NuGet config in `~/.config/NuGet/NuGet.Config` with the same configuration. Then run `dotnet add package`
It fails with 404:
```
root@sdorogin-mob:/home/work# dotnet add package xfw3.webclient
  Writing /tmp/tmpJ12HbY.tmp
info : Adding PackageReference for package 'xfw3.webclient' into project '/home/work/work.csproj'.
log  : Restoring packages for /home/work/work.csproj...
info :   GET https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient'
info :   Forbidden https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient' 262ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesBy
Id()?id='xfw3.webclient''.
log  : Response status code does not indicate success: 403 (Forbidden).
info :   GET https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient'
info :   GET https://api.nuget.org/v3-flatcontainer/xfw3.webclient/index.json
info :   Forbidden https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient' 100ms
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesBy
Id()?id='xfw3.webclient''.
log  : Response status code does not indicate success: 403 (Forbidden).
info :   GET https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient'
info :   NotFound https://api.nuget.org/v3-flatcontainer/xfw3.webclient/index.json 146ms
info :   Forbidden https://artifacts.croc.ru/api/nuget/nuget-virtual/FindPackagesById()?id='xfw3.webclient' 90ms
error: Failed to retrieve information about 'xfw3.webclient' from remote source 'https://artifacts.croc.ru/api/nuget/nug
et-virtual/FindPackagesById()?id='xfw3.webclient''.
error:   Response status code does not indicate success: 403 (Forbidden).
root@sdorogin-mob:/home/work#
```

While if I open the url in browser it'll ask for credentials (basic auth). If I already authenticated then the url returns xml feed. 
But nuget client shows me Forbidden (404. Why not Unauthorize (401)? In any case nuget obsiously ignores credentials in `~/.config/NuGet/NuGet.Config` : 

```
<configuration>
  <packageSources>
    <add key="nuget-virtual" value="https://company/api/nuget/nuget-virtual"/>
  </packageSources>
  <packageSourceCredentials>
    <nuget-virtual>
      <add key="User" value="user"/>
      <add key="ClearTextPassword" value="password"/>
    </nuget-virtual>
  </packageSourceCredentials>
</configuration>
```

**Comment by evil-shrike** [comment]
It seems that I'm having the same issue as #3664

**Comment by evil-shrike** [comment]
Hi, 
any reaction? 

Currently I can't build any .NET app on Linux because of dotnet-cli/nuget on Linux ignores auth info in `~/.config/NuGet/NuGet.Config`.

Is there ANY workaround?

**Comment by mrward** [comment]
Did you try adding the credentials to `~/.nuget/NuGet/NuGet.Config`? The dotnet cli does not use ~/.config/NuGet/NuGet.Config as far as I am aware on Linux nor on Mac.

**Comment by evil-shrike** [comment]
@mrward 
> Did you try adding the credentials to ~/.nuget/NuGet/NuGet.Config? 

yes, sure, please see the 2nd comment in this topic

> The dotnet cli does not use ~/.config/NuGet/NuGet.Config

I'm not sure that I understand you. If dotnet cli doesn't use `~/.config/NuGet/NuGet.Config` what's the point in adding credentials into it?

**Comment by mrward** [comment]
In the comments and bug report it seems that you are adding the credentials to ~/.config/NuGet/NuGet.Config and not ~/.nuget/NuGet/NuGet.Config. The dotnet cli does not use ~/.config/NuGet/NuGet.Config, as far as I am aware, so any credentials added to ~/.config/NuGet/NuGet.Config will not be used.

**Comment by evil-shrike** [comment]
@mrward Ah, I missed the difference. Yes, you're right, I've been using `~/.config/..`. I took it from http://lastexitcode.com/projects/NuGet/FileLocations/ as unfortunately it's not documented in the [docs](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior). 

So I've change to `~/.nuget/NuGet/NuGet.Config` but I can't see any difference (getting same 403 errors).

**Comment by evil-shrike** [comment]
I've resolved my issue.

There were several problems on my side which at different times took place. 

1. I was using `~/.config/NuGet/NuGet.Config` instead of `~/.nuget/NuGet/NuGet.Config`
2. I was using `PasswordClearText` key instead of `ClearTextPassword` in `NuGet.Config`
3. I was using incorrect command in Dockerfile:
```
COPY NuGet.Config.docker ~/.nuget/NuGet/NuGet.Config
```
it just doesn't work. Instead we should use a path without `~/`:
```
COPY NuGet.Config.docker /root/.nuget/NuGet/NuGet.Config
```

Hope it helps somebody else.
Closing for now. Sorry for disturbing.

**Comment by niraj-bpsoftware** [comment]
Hi @evil-shrike ,
I am facing similar issue when trying to run dotnet restore in docker image. dotnet restore picks up private nuget source only and not the public one (nuget.org). Could you please help?
My Nuget.Config:
`<?xml version="1.0" encoding="utf-8"?> <configuration> <packageSources> <add key="nuget.org" value="https://api.nuget.org/v3/index.json"/> <add key="BPNuget" value="http://myprivatenugetserver/nuget/" /> </packageSources> <packageSourceCredentials> <BPNuget> <add key="Username" value="<<NugetOwner>>" /> <add key="ClearTextPassword" value="<<APIKey>>" /> </BPNuget> </packageSourceCredentials> <packageRestore> <add key="enabled" value="True" /> <add key="automatic" value="True" /> </packageRestore> <bindingRedirects> <add key="skip" value="False" /> </bindingRedirects> <packageManagement> <add key="format" value="1" /> <add key="disabled" value="False" /> </packageManagement> </configuration>`

**Comment by fernandocerkal** [comment]
> I've resolved my issue.
> 
> There were several problems on my side which at different times took place.
> 
> 1. I was using `~/.config/NuGet/NuGet.Config` instead of `~/.nuget/NuGet/NuGet.Config`
> 2. I was using `PasswordClearText` key instead of `ClearTextPassword` in `NuGet.Config`
> 3. I was using incorrect command in Dockerfile:
> 
> ```
> COPY NuGet.Config.docker ~/.nuget/NuGet/NuGet.Config
> ```
> 
> it just doesn't work. Instead we should use a path without `~/`:
> 
> ```
> COPY NuGet.Config.docker /root/.nuget/NuGet/NuGet.Config
> ```
> 
> Hope it helps somebody else.
> Closing for now. Sorry for disturbing.

Thanks for this explanation!
I did this and I could run dotnet restore.
