### ISSUE TITLE
Cannot install entityframework nuget package

### ISSUE THREAD

**Issue by Legends** [NuGet/Home#6223]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet Version: 3.4.4.1321

dotnet.exe --version : 2.0.3

VS version (if appropriate): VS2017 v15.4.4

OS version : Win10 v1703 (OS Build 15063.726)
 
## Detailed repro steps so we can see the same problem

I have deleted all Entityframework references and dependencies 

 1. from the project references, 
 2. from the packages.config and 
 3. from the packages folder of the solution.

    Install-Package EntityFramework -Version 6.1.3

What happens now is, that the entityframework package is added again to the packages folder, but without the dll!

**Results in this error:**
> Attempting to gather dependency information for package
> 'EntityFramework.6.1.3' with respect to project 'MyApp.Web', targeting
> '.NETFramework,Version=v4.5.2' Gathering dependency information took
> 473,82 ms Attempting to resolve dependencies for package
> 'EntityFramework.6.1.3' with DependencyBehavior 'Lowest' Resolving
> dependency information took 0 ms Resolving actions to install package

> 'EntityFramework.6.1.3' Resolved actions to install package
> 'EntityFramework.6.1.3' Found package 'EntityFramework 6.1.3' in
> 'C:\Users\Admin\Downloads\MyAppNET-3.0.3\MyAppNET-3.0.3\src\packages'.

> Package 'EntityFramework.6.1.3' already exists in folder
> 'C:\Users\Admin\Downloads\MyAppNET-3.0.3\MyAppNET-3.0.3\src\packages'

> Install failed. Rolling back... Package 'EntityFramework.6.1.3' does
> not exist in project 'MyApp.Web'
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by emgarten** [comment]
Does this repro with NuGet 4.5.0 and VS 15.5?

**Comment by jainaashish** [comment]
Not enough information so closing it for now.
