### ISSUE TITLE
NuGet restore extremely slow in large solution targeting UAP 10.0

### ISSUE THREAD

**Issue by cclauson** [NuGet/Home#6224]
Hi,

NuGet restore is incredibly slow for me.  I am working on a solution with 600+ projects, when restore is run without a preexisting src.bld directory, the process takes about 10 minutes.  Restore is being done for .NET Framework 4.6 and UAP 10.0.

I've pulled the nuget source code and run the restore process from Visual Studio to try to get an idea of what is taking so long.  There seem to be two main culprits, RemoteDependencyWalker.CreateGraphNode() (in RemoteDependencyWalker.cs), and GraphOperations.Analyze() (in GraphOperations.cs) in this case called from RestoreTargetGraph.Create() (in RestoreTargetGraph.cs).  More specifically RemoteDependencyWalker.CreateGraphNode() seems to recursively traverse a dependency graph, and is running 30,000 - 40,000 times when resolving UAP 10.0 dependencies (.NET Framework dependencies do not seem to result in so many calls, frequenty on the order of magnitude of 100).  Each time takes a substantial fraction of a second, and is happening maybe 10 or so times per project.

I'm still not totally comfortable with what's happening in the code, but I thought I would ask, is this an issue which is known of and is there any possibility or plan to improve perf?  I also noticed that in RuntimeGraph.cs there are a number of comments related to possible perf impacting improvements, would these have any impact on this workload?

Thanks so much in advance for any insight into this!

**Comment by emgarten** [comment]
A couple of questions on your environment:
* What version of NuGet are you using?
* How are you running restore?
* Do all of the projects restore in a single operation or are you calling restore multiple times?
* Are downloads happening during the 10 minute restore?

How long does it take when using nuget.exe 4.4.1?
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

There have been a lot of performance improvements in 4.3.0 which has noop support to avoid walking the graph and calling create graph node if everything is up to date. And memory and other improvements in 4.4.0, so make sure you are using the latest bits.

**Comment by cclauson** [comment]
Thanks for your response on this!

My nuget.exe version is 4.4.1.4656.  The restore I've been trying is "nuget restore .\MySln.sln" (we're actually using restore from MSBuild on each project individually elsewhere in our workflow, but I've been testing this since it seems to be the same slow perf).  I do not believe it's downloading anything, and checked this by running the restore with my network cable disconnected.

Also, since I'm using testing with source code I pulled from your github, I'm guessing everything will be up to date?

**Comment by cclauson** [comment]
Actually I'm looking at your change from Nov 10, I don't seem to have this, I can check to see if that improves things.

**Comment by cclauson** [comment]
In the logs I see your change to caching from November 10 and I have this in the enlistment that I'm running.  If I undestand correctly, this seems to create a potential for reducing work in ProjectRestoreCommand.InstallPackagesAsync() in the case where packagesToInstall.Count > 0.  However, in my case packagesToInstall.Count is always zero and this code never executes, so probably this change does not impact the restore times I'm seeing?

**Comment by emgarten** [comment]
> Also, since I'm using testing with source code I pulled from your github, I'm guessing everything will be up to date?

That's right, dev branch will have the latest.

> I do not believe it's downloading anything, and checked this by running the restore with my network cable disconnected.

That's a good test. Restore should have failed if it needed to go online unless you specified to ignore failed sources.

Restoring the solution should be much faster than restoring each project individually in separate restores due to how msbuild info and package info is cached between restores when running in the same process.

Try the following: 
1. Set the env var `NUGET_PERSIST_DG=true`
1. Set the env var `NUGET_PERSIST_DG_PATH=c:\tmp\pathtoyourfile.dg`
1. Run `nuget.exe restore MySln.sln`   (this will generate the dg file as part of this restore)
1. Run `nuget.exe restore c:\tmp\pathtoyourfile.dg`  (this will skip all msbuild operations)

Let me know the time of 3 vs 4

**Comment by emgarten** [comment]
> ProjectRestoreCommand.InstallPackagesAsync() in the case where packagesToInstall.Count > 0

This will always be zero if everything is in the global packages folder already, so you are right, this perf fix which is in NuGet 4.5.0 (not yet released) doesn't benefit your scenario.

**Comment by cclauson** [comment]
Both of these took the same amount of time, 11 minutes

**Comment by emgarten** [comment]
How long does it take to run:
`msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=c:\tmp\graph.dg MySln.sln`

**Comment by emgarten** [comment]
Also, what kind of projects are these? NETCore SDK style projects using the new minimal format, or are these classic csproj files with PackageReferences? 

If possible it would be helpful if you could share the .dg file you generate.

**Comment by cclauson** [comment]
They use "PackageReference"

**Comment by emgarten** [comment]
Do they contain `<Project Sdk="Microsoft.NET.Sdk">`?

**Comment by cclauson** [comment]
They do not appear to.  Do you think adding this might help?

**Comment by emgarten** [comment]
> They do not appear to. Do you think adding this might help?

No, that just tells me which type of project it is. 

How long does the GenerateRestoreGraphFile target take on the solution?

**Comment by cclauson** [comment]
It took a few seconds.

**Comment by cclauson** [comment]
More specifically, about 35 seconds

**Comment by emgarten** [comment]
35 seconds for 600 projects seems reasonable or fast. A large solution with 155 projects I profiled recently took 22 seconds to create the dg file, and then 6 seconds to run the actual restore.

Is there anything unique about your solution or the packages referenced? For example:
* Are the projects heavily interlinked? A -> B -> C -> D where you have project A referencing B, C, and D directly?
* How many packages does the solution use?
* Are the packages heavily interlinked?
* What is the highest number of versions available for a package used by the solution in the global packages folder?
* Are transitive dependencies duplicated in parent projects? Example: ProjectA -> ProjectB where both A and B reference the same package X. X will flow transitively from B to A and does not need to be referenced in A. This also applies to package to package dependencies. ProjectA -> PackageC -> PackageD -> PackageE,  only the reference to C is needed in A.

If you restore a project with no project references (leaf node) directly by running `nuget.exe restore pathto.csproj` how long does it take?

MSBuild generating the dg file typically takes much longer than the restore so I'm very curious as to why your solution is so much slower. The methods you mentioned from profiling are expecting to be hit many times, the graph walk is the main part of restore, but usually a small percent of the time it takes. I could see this becoming a problem if the dependency graph where very extreme with a lot of packages, and a lot of edges between nodes in the dependency graph.

**Comment by cclauson** [comment]
A leaf node with 6 package references took about 2 seconds.  Overall the solution seems to use something like 80 packages.

**Comment by emgarten** [comment]
That sounds fairly simple, maybe something in the graph walk isn't scaling properly. Any chance you could share the .dg file and the project.assets.json files from restore?

//fyi for perf/graph caching @davidfowl

**Comment by cclauson** [comment]
I'd love to show it to you.  Let me look into this and see if I can get this to you.  Thanks so much for your help!

**Comment by cclauson** [comment]
File sent over email.

**Comment by emgarten** [comment]
I see some improvements that could be made here on the NuGet side, but the primary reason for this restore taking so long is the number of graphs required.

`400 projects x 2 frameworks x 7 RIDs = 5600 restore target graphs`

Many of these graphs would be very similar between projects, that could be re-used.

I suggest reducing the number of projects, frameworks, or RIDs if possible to help work around this. Even if restore were twice as fast it would still be more than 5 minutes for this solution.

Removing redundant dependencies would also help. If a project references A it flows transitively to all parent projects, they do not need to reference it again.

net46 ends up getting restored for every RID probably isn't needed and likely taking a large amount of the time.

I'll keep working on general improvements to restore which should help bring this time down. Watch for those improvements in NuGet 4.6 and higher.

**Comment by emgarten** [comment]
I am also seeing a large amount of time spent due to all projects depending on a missing package version. The warning for this is currently suppressed with `NoWarn=NU1605` in all projects. I suggest fixing this and treating `NU1605` as an error for perf reasons.

**Comment by emgarten** [comment]
@cclauson have any of these help?

**Comment by emgarten** [comment]
Closing due to lack of response. 4.6.0 will contain several performance improvements that should help this.
