### ISSUE TITLE
$version$ token's cause Manifest.ReadFrom to throw

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#6228]
If you have a NuSpec that uses tokens in any version field, the Manifest / version parsing logic will throw.

This is because `NuGetVersion` does not understand the tokens.

This also affects other places `NuGetVersion` is used, like in Dependency version ranges.
`NuGetVersion` needs to support the tokens.

**Comment by emgarten** [comment]
The tokens should be replaced at write time and pack should handle this. At any time after pack it is invalid to have a non-version in a nuspec version field.

What is the scenario where you are hitting this?

**Comment by clairernovotny** [comment]
The scenario is using the Manifest types to read/write the nuspec for NuGet Package Explorer. We are not actively packing then, it's an edit operation.

**Comment by emgarten** [comment]
@rohit21agrawal how does pack handle this?

**Comment by rohit21agrawal** [comment]
@onovotny can you paste a working example here?

**Comment by clairernovotny** [comment]
What do you mean by a working example?

Pack handles it by replacing the values with the `propertyProvider` func Preprocessor before the Manifest is deserialized.

**Comment by clairernovotny** [comment]
The repro is easy though, put `$version$` into the `<version>` element of a nuspec (or in a dependency version attribute), and then try to open with the latest NuGet Package Explorer. The version in master now uses NuGet.Packaging instead of custom deserialization, that's why we hit this.

You can either build it locally if you want to debug and use NuGet.Packaging as a source reference or as a binary by installing this:
https://nugetpackageexplorer.blob.core.windows.net/nightly/PackageExplorer.Package.Nightly.appxbundle

**Comment by rohit21agrawal** [comment]
yeah I just saw that. 

I am not sure what the right behavior should be right now. Based on the scenarios for which this was designed, it has the correct behavior.

If you still want the tokens, can't you use a simple XmlReader?

**Comment by clairernovotny** [comment]
We don't want to do custom xml parsing. That lead to all kinds of nasty parsing issues. The solution is pretty easy, extend NuGetVersion to understand the tokens similar to what we did when we were custom:

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/v3.25/Types/Packages/TemplatebleSemanticVersion.cs

It just needs to round-trip for serialization and be displayable in some form of ToString/property with an IsToken property, etc.

**Comment by rohit21agrawal** [comment]
can you help me understand why does nuget package explorer (which opens up a nupkg) would ever encounter a situation of reading a nuspec file with a token in it?

or are you just using the package explorer to open a nuspec file?

**Comment by clairernovotny** [comment]
Because people have nupsecs that have tokens in them (checked into version control, etc), and they want to use the tool to edit the nuspec metadata. They are not creating a package that way. Think about it like a nuspec editor.

This was actually one of the most requested features in the CodePlex site before it moved to GitHub.

NuGet Package Explorer supports opening up and editing Nuspecs directly, not just packages.

**Comment by clairernovotny** [comment]
If we can come up with what the updated API shape should look like, I can make the changes if that'll help get it done sooner.

**Comment by rohit21agrawal** [comment]
@rrelyea where would you put this in terms of priority? we will have to allocate time accordingly

**Comment by clairernovotny** [comment]
Ping @rrelyea ? I'm happy to do the implementation since I otherwise need nasty hacks to support this in NPE.

Here's an initial idea for extending `NuGetVersion`:

```csharp
public class NuGetVersion
{
  public bool IsTokenized { get; }
  public string TokenValue { get; }
}
```

Parse would try to parse the version as it does today, and if it fails checks for the token marker. It'll store the value and use `0.0.0.0` as the version itself. Relevant formatters/ToString would return the token if present. Serialization would serialize the token value if present. Validation of writing packages would ensure that it's not a token value when doing a pack, etc.

Thoughts?

**Comment by 304NotModified** [comment]
Another option would be to subtype the `NuGetVersion`, e.g.

```c#

public class TokenizedNuGetVersion : NuGetVersion
{
    public string TokenValue { get; }
}
```
