### ISSUE TITLE
Regression: Pack targets failing - trying to add pdb for embedded type

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#6230]
I’m seeing a regression that’s causing Ix.NET to fail with 2.0.3 and higher. I don’t know when the break was introduced. Nothing in Ix has changed related to this:
https://github.com/Reactive-Extensions/Rx.NET/tree/develop/Ix.NET/Source

Getting errors like this:
"C:\dev\RxNET\Ix.NET\Source\System.Interactive\System.Interactive.csproj" (pack target) (1) ->
(GenerateNuspec target) ->
  C:\Program Files\dotnet\sdk\2.1.1-preview-007165\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(204,5): err or : The file 'C:\dev\RxNET\Ix.NET\Source\System.Interactive\bin\Release\net45\System.Interactive.pdb' to be packed was not found on disk. [C :\dev\RxNET\Ix.NET\Source\System.Interactive\System.Interactive.csproj]

And the build log shows this:
![image](https://user-images.githubusercontent.com/1427284/33298428-54458240-d3b4-11e7-9198-2a1278805e70.png)

This is in error because there are no symbols for DebugType = embedded. The build log clearly shows DebugType set to embedded.

[msbuild.zip](https://github.com/NuGet/Home/files/1508255/msbuild.zip)

**Comment by emgarten** [comment]
@rohit21agrawal can you take a look?

**Comment by rohit21agrawal** [comment]
I will have to blame msbuild for this because if _GetDebugSymbolsWithTfm target (that resides in NuGet.Build.Tasks.Pack.targets) depends on DebugSymbolsProjectOutputGroup . The target outputs for DebugSymbolsProjectOutputGroup should have been an empty list for DebugType = embedded but instead it points to a non-existent pdb file on disk.

**Comment by rohit21agrawal** [comment]
This issue was moved to Microsoft/msbuild#2754
