### ISSUE TITLE
list -IncludeDelisted does not seem to work

### ISSUE THREAD

**Issue by TiltonJH** [NuGet/Home#6234]
`nuget list -IncludeDelisted` does not seem to work anywhere (v.4.4.1.4656). I have tried it with NuGet.Server 2.11.3 and 3.0.0. As well as `-allversion` and/or `-prerelease`.

Looking at `/nuget/Packages()` shows the delisted packages.

So `-IncludeDelisted` is generally not supported? So why does this switch exist at all?

Related closed issue #5896
Related NuGet.Server Issue [https://github.com/NuGet/NuGetGallery/issues/5066](url)

**Comment by rohit21agrawal** [comment]
@nkolev92 do you have any context on this?

**Comment by nkolev92** [comment]
It favors the search endpoint, which doesn't work with unlisted packages.

**Comment by rohit21agrawal** [comment]
is there an existing bug to associate with this?

**Comment by nkolev92** [comment]
It's the already linked closed one. 
//cc 
@joelverhagen 

EDIT:
Clicked Close instead of comment on this issue by accident.

**Comment by TiltonJH** [comment]
@nkolev92 What do you mean by 

> It favors the search endpoint, which doesn't work with unlisted packages.

Please elaborate?

I thought:

- `nuget list -source XYZ` lists all the highest packages from XYZ
- `nuget list -source XYZ -AllVersions` lists all packages from XYZ
- `nuget list -source XYZ -AllVersions -Prerelease` lists all packages including prereleases from XYZ
- `nuget list -source XYZ -AllVersions -Prerelease -IncludeDelisted` lists all packages including prereleases and delisted from XYZ

So that `-AllVersions` `-Prerelease` `-IncludeDelisted` act like _and_-combined filter flags, which can be used in all possible combination.

**Comment by nkolev92** [comment]
Sources can have 2 different endpoints to search for packages, 
/nuget/Packages()  and /nuget/Search().
Packages is the old, primitive and a poorly performing protocol. 
List looks if the server has the Search endpoint and uses that. 
The search endpoint implementation however, by default excludes the unlisted packages, because the exact reason why someone would unlist a package would be to make in undiscoverable.

**Comment by TiltonJH** [comment]
So the old `/nuget/Packages()` can show delisted packages, but has bad performance?
And `/nuget/Search()` doesn't have an implementation that supports showing desisted packages, which is by design.
Correct?

So `-IncludeDelisted` is a left over option of the past? Why is it still here?

How do I switch `nuget list` to `/nuget/Packages()` so that I can see delisted packages of my own not local nuget sever via the commandline?
So that I end up knowing that an already existing but delisted package can not be pushed to the server without having to deal with an error?
And if I'd like a list of all delisted packages for lets say statistical reasons?

**Comment by nkolev92** [comment]
At this point we are not investing in list, it will be renamed to search and at that point the include delisted flag will be removed: https://github.com/nuget/home/issues/8040
