### ISSUE TITLE
PackageIdentity.ToString throws NullReferenceException if version is null

### ISSUE THREAD

**Issue by ohadschn** [NuGet/Home#6235]
The case of a `null` version is clearly supported, specifically see the [HasVersion](https://github.com/NuGetArchive/NuGet.Packaging/blob/b0a0bead29c480186142a42daa8478f7b4a778f0/src/NuGet.Packaging.Core.Types/PackageIdentity.cs#L62) property.

However, [`NuGet.Packaging.Core.ToString`](https://github.com/NuGetArchive/NuGet.Packaging/blob/b0a0bead29c480186142a42daa8478f7b4a778f0/src/NuGet.Packaging.Core.Types/PackageIdentity.cs#L137) does not check for version nullity: ` return String.Format(CultureInfo.InvariantCulture, ToStringFormat, Id, Version.ToNormalizedString());`

Naturally `NullReferenceException` should not be thrown, though I'm not sure what `ToString` should produce in this case. Perhaps just `<packageId>` (rather than `<packageId>.<packageVersion>`)?

**Comment by rohit21agrawal** [comment]
@emgarten any thoughts on what the correct behavior here should be?

**Comment by emgarten** [comment]
I agree, it should be fixed and just display the Id.

I believe we reluctantly had to add support for null versions with identity, originally it wasn't supported but there are scenarios where it is needed. ToString likely wasn't cleaned up after that change was made originally.

**Comment by emgarten** [comment]
Would love a PR for this if someone has time 🍰

**Comment by emgarten** [comment]
Thanks for the fix @ohadschn!
