### ISSUE TITLE
Unable to load the service index for source

### ISSUE THREAD

**Issue by mdczaplicki** [NuGet/Home#6236]
## Details about Problem

I cannot browse/install/update any package in VS 2017. I have tried updateing VS 2017 to the newest version, but it doesn't work.
I have completely reinstalled VS 2017 - didn't help.

NuGet product used:  VS UI

NuGet version (x.x.x.xxx): 3.4.4.1321

dotnet.exe --version (if appropriate): 2.0.3

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): Windows 7 Version 6.1 Build 7601

Worked before? If so, with which NuGet version: Yes, probably the same version.

## Detailed repro steps so we can see the same problem
Click RPM on project
Select Manage NuGet Packages
Select Browse

In output window it shows:
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  The ServicePointManager does not support proxies with the https scheme.

I have tried to change to http://...
but then there is:
[nuget.org] Unable to load the service index for source http://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote server returned an error: (400) Bad Request.
.

This happens only in a specific solution and only on my computer. In VS 2015 also fails - same error.

**Comment by mdczaplicki** [comment]
It started working just like that. Didn't do anything.

**Comment by rrelyea** [comment]
We were going to ask which OS & OS Version, and which .net framework version was installed while you were having this problem.
However, since it appears fixed, perhaps it doesn't need investigation?

**Comment by mdczaplicki** [comment]
Windows 7 Enterprise, build like above.
In this solution&project it was .NET 4.6.1.
I can share more information if you need.

**Comment by mkabhishekdev** [comment]
I am facing a similar problem. can you explain how what change you did in settings to make it work?
