### ISSUE TITLE
Package manager UI: Missing install/update/uinstall options

### ISSUE THREAD

**Issue by Tchami** [NuGet/Home#6237]
In the "Manage Packages for Solution" dialog, the "Install and Update Options" as well as "Uninstall Options" are missing from the Options, when you try to install/update/consolidate a package. All options are available if you manage packages for a single project using the package manager ui.

I'm guessing this is by design(?), but in some situations e.g. when working with multiple projects where you need to update packages but ignore their dependencies, those options are a real time saver.

NuGet product used: Package Manager UI
NuGet version: 4.4.1.4633
VS version: 2017 15.4.5
OS version: win10 v1703 (15063.726)

Worked before?: Yes, but I don't know which version

1. See attached solution
2. Manage packages for the project and verify all options are available
3. Manage packages for the solution and verify that options are missing

[UpdateOptions.zip](https://github.com/NuGet/Home/files/1514214/UpdateOptions.zip)

**Comment by jainaashish** [comment]
This has been in latest NuGet with VS 15.5 which is currently in preview but soon be rtm.

**Comment by nkolev92** [comment]
Fixed in 4.5, couldn't find the duplicate.
