### ISSUE TITLE
API Question: How can custom HTTP headers be added to request?

### ISSUE THREAD

**Issue by mhsimkin** [NuGet/Home#6238]
Version Nuget.* 4.x.x

I'm building a automated application update process that will rely on using a Nuget feed.  Our internal Nuget Server (ProGet) supports several custom HTTP Headers.  These headers can be used to send the username, date, application, etc.

How can I add these headers to at least the DownloadResource::GetResourceAsync() call?

Thanks

-marc

**Comment by rohit21agrawal** [comment]
where is the DownloadResource::GetResourceAsync method defined?

**Comment by mhsimkin** [comment]
src/NuGet.Core/NuGet.Protocol/Resources/DownloadResource.cs.  I need a way to get to the underlying HTTPClient object that is wrapped by the [HttpSource](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpSource.cs) object.

**Comment by rohit21agrawal** [comment]
this might be one place to add it: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/UserAgent.cs#L43

@zhili1208 will be better able to help on this.

**Comment by mhsimkin** [comment]
I can't add headers using the UserAgent. All I can do is change to User Agent string. :o(

**Comment by mhsimkin** [comment]
This [issue](https://github.com/NuGet/Home/issues/5095) lead me to a solution.

I need to implement my own HttpHandlerResourceProvider.  I can then hook up handler derived from DelegatingHandler.  In the SendAsync method, I can add the custom http headers.
