### ISSUE TITLE
Issue of managing NuGet package

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6255]
@Samuel98005 commented on [Mon Dec 04 2017](https://github.com/NuGet/NuGetGallery/issues/5117)

Hi,

I have an issue of managing NuGet package. Basically I tried to resolve this issue with a new Visual Studio installation after uninstalling the existing one. This happens in both Visual Studio 2015 Professional and Enterprise edition in Windows Server 2012. 

The error message I have encountered: "Solution is not saved. Please save your solution before managing NuGet packages."
 
Could someone please help on this?

Kind regards,
Samuel

**Comment by emgarten** [comment]
@samuel98005

> Please save your solution before managing NuGet packages.

Did this solve your problem?

**Comment by Samuel98005** [comment]
Please find below what I actually tried out before escalate this issue to NuGet support. 

-	Saving the solution (even when there is no need to save the solution since there is no change). 
-	Reopen Visual Studio.
-	Restart the machine.
-	Remove the existing VS, and fresh VS installation.

However it repros same for all. 

Kind regards,
Samuel

**Comment by jainaashish** [comment]
@Samuel98005 did you try this with VS 2017? if yes, then please tell us your complete repro steps so that we can repro it locally and investigate the issue.

If, you haven't tried with VS 2017 then please try with that and let us know how it goes.

**Comment by Samuel98005** [comment]
Recently the plugin I need to use in my project is only compatible with VS 2013 and 2015 (not support VS 2017) because of this there is no point of trying VS 2017. Thank you!

**Comment by jainaashish** [comment]
We can't do much about VS 2015 or 2013 since there isn't any active development there. If you can repro your issue with VS 2017 then we can further look into the issue, otherwise I'm afraid I need to close it as is.

**Comment by elmandodge** [comment]
![error](https://user-images.githubusercontent.com/36224688/37555569-11c731fe-29f2-11e8-9434-694ac25429b7.JPG)

the same issue has happened with me in VS2017 Enterprise ..
Any clue to what has to be done ?

ps : i'm not planning on reinstalling as i have many plugins installed already .. i hope there is an easier fix

thank you in advance
Elman

**Comment by jainaashish** [comment]
This error is thrown when 
- Solution is not open or 
- Solution is not unsaved or 
- NuGet doesn't support any project in that solution.

So provide mire details:
- Does this solution ever showed NuGet Manager UI in any other version of VS?
- Try with any other solution (or just create a c# class library) and see if that also throws or works?
