### ISSUE TITLE
dotnet nuget push may not push packages properly from Linux env

### ISSUE THREAD

**Issue by AvapiDotNet** [NuGet/Home#6257]
Hello guys,

I don't know if I am posting in the right place but I am using .NET Core on a Linux Box (Ubuntu) on AWS and I am trying to push a nuget package on nuget.org.

At the moment I am using this command:
dotnet nuget push <package_name>.nupkg -k <api_key> -s https://www.nuget.org/api/v2/package
but I got this error:

info : Pushing package_name.nupkg to 'https://www.nuget.org/api/v2/package'...
info : PUT https://www.nuget.org/api/v2/package/
info : BadRequest https://www.nuget.org/api/v2/package/ 975ms
error: Response status code does not indicate success: 400 (A client version '4.1.0' or higher is required to be able to push packages. Please contact support@nuget.org to get more details.).

Is there a way to fix this issue?

Thank you very much

**Comment by jainaashish** [comment]
In order to push to NuGet.org, all users must have NuGet 4.1 or later client code, as the error message states. Using dotnet.exe means that you'd need to update to dotnet.exe 2.0 or later, we believe.

Please update your dotnet cli to latest version and then try again.

**Comment by anangaur** [comment]
https://github.com/NuGet/NuGetGallery/issues/5065 has the details.

**Comment by AvapiDotNet** [comment]
I have upgraded dotnet-cli and it worked. Thank you very much guys, you can close ths issue.

**Comment by anangaur** [comment]
Awesome!
