### ISSUE TITLE
Visual Studio 2015 RC does not pick up the repositoryPath setting from nuget.config in solution folder

### ISSUE THREAD

**Issue by lawrencejohnston** [NuGet/Home#626]
[StackOverflow question](http://stackoverflow.com/questions/30335211/how-do-i-get-visual-studio-2015-rc-to-pick-up-the-repositorypath-setting-from-my)

We use a custom location for our packages folder which we specify in a nuget.config file in the same folder as our solution:

    <settings>
        <repositoryPath>..\..\lib\packages</repositoryPath>
    </settings>

Visual Studio 2013 picks this up fine and the NuGet package manager installs packages into the specified folder, lists installed packages correctly, etc.

In Visual Studio 2015 RC the NuGet package manager pops up the "Some packages are missing from this solution, click here to restore" message and if I click the button it creates a new packages folder in the same folder as the solution rather than using the location specified in the nuget.config. Installing a completely new package also puts it into a packages folder under the solution folder rather than the specified one.

The Visual Studio 2015 RC NuGet package manager needs to respect the repository path specified in the nuget.config the same way 2013 did.

**Comment by lawrencejohnston** [comment]
I just tested this and am still able to reproduce the issue with RC2 released today. Am I correct in assuming that this fix didn't make it in?

**Comment by zhili1208** [comment]
@lawrencejohnston made this fix in on 6/4, RC2 release is 6/2 build. So this fix is not in RC2 release.

**Comment by lawrencejohnston** [comment]
Thanks; that explains it.

**Comment by lawrencejohnston** [comment]
This is still broken in 2015 RTM. In the package Manager the green checkmark shows up next to installed packages now, but so does the "Some NuGet packages are missing from this solution. Click to restore from your online package sources" and clicking that still creates a packages folder in the solution directory and restores everything to it.

Could you please reopen this issue?

> Version info:
> Microsoft Visual Studio Professional 2015
> Version 14.0.23107.0 D14REL
> Microsoft .NET Framework
> Version 4.6.00081

**Comment by zhili1208** [comment]
@lawrencejohnston I can't repro this issue.
<settings>
    <repositoryPath>..\..\lib\packages</repositoryPath>
</settings>
this is wrong, it should use <config>, like this:
  <config>
    <add key="repositoryPath" value="..\..\lib\packages" />
  </config>

here is document for this: http://docs.nuget.org/consume/nuget-config-settings

and delete default packages folder, make sure your solution nuget.config exist in solution folder, then open your solution in vs. 
can you try this again?

**Comment by lawrencejohnston** [comment]
Switching to  `<add key="repositoryPath"...` fixed it. Thanks.

**Comment by tjrobinson** [comment]
@zhili1208 The <repositoryPath> variation used to work, but perhaps not officially. Some background: http://stackoverflow.com/a/4197201/12124

**Comment by f0rt** [comment]
Hi team,
I'm unable to change the location of my packages folder. I followed the instructions in this bug. Here is my setup:
- VS2015 U2
- Class Library Project (not PCL)  with project.json
- Nuget.config at solution level
  `<?xml version="1.0" encoding="utf-8"?>
  <configuration>
    <config>
       <add key="repositoryPath" value="c:\teampackages" />
    </config>
  </configuration>`

VS always restores packages to default location: **C:\Users\user\ .nuget\packages**

**Comment by zhili1208** [comment]
@f0rt project.json project doesn't support repositoryPath config now, if you want to change packages default location, you can set "NUGET_PACKAGES" environment variable to do that. Just Set "NUGET_PACKAGES" = "c:\teampackages".

**Comment by f0rt** [comment]
**Is project.json project going to support this key in the future?**

The following case can only be handled with this feature:
We are using a internal build system. Build component dependencies are defined with dependency specification files. We don't want maintain 2 files with dependencies so we've set "*" for our dependencies in project.json and nuget is configured to pick the highest version of nupkg files located in local for the solution folder(<solutionFolderPath>\nugetPackages). This doesn't work for 2 project if we have common "packages" folder because both projects will pick the highest dependency which is not desired. This may look like a corner case but it is actually a common scenario when you work a in a big company and you're bound to the internal policies and tools.

**Can you suggest another way to handle the scenario above?**

**Comment by emgarten** [comment]
@f0rt floating versions that use a `*` are checked against the source in NuGet 3.4.x, with nuget.exe you may need to use `-NoCache` to see this behavior.

**Comment by f0rt** [comment]
Is there a way to accomplish this with VS restore? If not I need to setup a pre-build event for my project and run "nuget restore -nocache", right?

**Comment by emgarten** [comment]
It should work in VS
