### ISSUE TITLE
`dotnet pack` product broken .nupkg with the latest daily build(2.2.0-preview1)

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6267]
_From @yyjdelete on December 7, 2017 1:34_

Test with dotnet sdk `2.2.0-preview1-007736`/7622/7460, Windows 10 x64(17064).
And `2.1.1` in VS15.5preview5 works well.

# Step:
1. Install the latest daily build of sdk
2. `dotnet new classlib`
3. `dotnet pack`
4. Open the output .nupkg with `NuGet Package Explorer` or some zip manager( and try unpack it), and get an error.
5. Found the `.nuspec` file in the `nupkg` has wrong CRC(but the packed data is right)

_Copied from original issue: dotnet/sdk#1801_

**Comment by livarcocc** [comment]
@rohit21agrawal can you take a first look? If this turns out to be a CLI/SDK issue, please tell us and re-activate the original issue.

**Comment by rohit21agrawal** [comment]
What’s CRC?

**Comment by yyjdelete** [comment]
The zipEntry's crc32 of `.nuspec` in `.nupkg`


[nupkgs.zip](https://github.com/NuGet/Home/files/1538272/nupkgs.zip)

**Comment by rohit21agrawal** [comment]
@yyjdelete while i can repro on the nupkg you provided, i can't repro it locally using the build and steps you mentioned.

was the nupkg you produced encrypted? @PatoBeltran has some thoughts about encryption and how it relates to crc32

**Comment by yyjdelete** [comment]
@rohit21agrawal
It's not encrypted.

Just product with the Daily Build(`2.2.0 preview`) can be found at there, tested with both windows and linux x64. And all `stable` versions works well.
https://github.com/dotnet/cli/blob/master/README.md#installers-and-binaries
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

---
`dotnet mubuild /t:pack` also get the same result.

**Comment by yyjdelete** [comment]
@rohit21agrawal @livarcocc 
Seems something is wrong with `netcoreapp2.1(preview)`, the below code works well with `netcoreapp2.0` but product broken zipfile with `netcoreapp2.1`.
Any idea where to post this issue?

<details>

```cs
using System;
using System.IO;
using System.IO.Compression;
using System.Xml.Linq;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var fs = File.Create("test.zip"))
            using (var package = new ZipArchive(fs, ZipArchiveMode.Create, leaveOpen: true))
            {
                //This file has an bad crc in netcore2.1
                ZipArchiveEntry entry1 = package.CreateEntry("x1.txt", CompressionLevel.Optimal);
                using (Stream stream = entry1.Open())
                {
                    CreateDocument().Save(stream);
                    //Console.WriteLine(stream.Position);//50
                }

                ZipArchiveEntry entry2 = package.CreateEntry("x2.txt", CompressionLevel.Optimal);
                using (Stream stream = entry2.Open())
                using (var writer = new StreamWriter(stream, Encoding.UTF8))//make both has an BOM
                {
                    CreateDocument().Save(writer);
                    writer.Flush();
                    //Console.WriteLine(stream.Position);//50
                }
            }
        }

        public static XDocument CreateDocument()
        {
            return new XDocument(
                new XElement("Foo")
                );
        }
    }
}
```
</details>

**Comment by rohit21agrawal** [comment]
@livarcocc I have re-opened the original sdk issue as this is definitely not a NuGet big.

@yyjdelete sorry for the inconvenience and really appreciate you taking out the time to send feedback, Livar’s team will investigate this as soon as they can
