### ISSUE TITLE
New Pack can build packages with dependencygroups, which don't work well in NuGet 2.12 (vs 2013)

### ISSUE THREAD

**Issue by SergeyKanzhelev** [NuGet/Home#6268]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

VS 2013 Update 5, Package Manager 2.12.0.817
![image](https://user-images.githubusercontent.com/9950081/33704449-5b5e0e24-dae1-11e7-965b-c8342ecc68d1.png)

NuGet version (x.x.x.xxx): whatever NuGet Package Manager uses?

VS version (if appropriate): VS 2013 Update 5

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:
Different version of the package works there.

## Detailed repro steps so we can see the same problem

1. Package compiled using [nuspec](https://www.nuget.org/packages/Microsoft.ApplicationInsights.NLogTarget/2.4.0) shows dependencies 

![image](https://user-images.githubusercontent.com/9950081/33704550-d1992d76-dae1-11e7-9767-8c4eeba4cf27.png)

2. Package compiled using [new project type](https://github.com/Microsoft/ApplicationInsights-dotnet-logging/blob/develop/src/NLogTarget/NLogTarget.csproj) doesn't. You can find compiled NuGet [here](https://www.myget.org/feed/applicationinsights/package/nuget/Microsoft.ApplicationInsights.NLogTarget/2.5.0-beta1) 

![image](https://user-images.githubusercontent.com/9950081/33704584-eb8e4112-dae1-11e7-8b2b-ab27ea27626e.png)

**Comment by hchengmx** [comment]
Windows Version:10.0.14393.

**Comment by Hubert-Cheng** [comment]
Windows Version [10.0.14393]

**Comment by SergeyKanzhelev** [comment]
Small update here. It seems that the problem is the target framework of the project. Somehow NuGet allows to install the package that only has something for 4.5+ on project that targets FW 4.0. There is no complains or errors. It simply do not set any references.

Is it expected behavior? Can we somehow block installation on FW 4.0 that is not supported?

**Comment by jainaashish** [comment]
@SergeyKanzhelev New package format type is not supported with Visual Studio 2013 and NuGet 2.12. It's only supported with Visual Studio 2017 and NuGet 4.x So please upgrade your Visual Studio to take advantage of the new format type.

**Comment by SergeyKanzhelev** [comment]
@jainaashish so you are saying that we SHOULD NOT build our packages using new approach if we have customers consuming them from VS 2013? Is it also by design?

**Comment by SergeyKanzhelev** [comment]
CC: @Dmitry-Matveev

**Comment by jainaashish** [comment]
ohh sorry, if it's only about consuming that package, then it should have shown those dependencies. But I'm afraid if we can do anything for VS 2013. So I'll suggest that you can try packing your project with an explicit `.nuspec` file where you can include these dependencies without target framework group.

About the target framework, then the reason it allows to install this package on either net45 or net40 without errors or warning because package has some content files which makes it compatible with net40 but it only include library for net45 which is why reference is only added for net45+.

If you remove content files then this package will block installation on net40 or less since it will only have library assets which is net45+

**Comment by jainaashish** [comment]
Reopened for now for tracking purpose.

**Comment by SergeyKanzhelev** [comment]
> if it's only about consuming that package, then it should have shown those dependencies

It should be fine for me if it doesn't show dependencies. As long as installation blocked...

>About the target framework, then the reason it allows to install this package on either net45 or net40 without errors or warning because package has some content files which makes it compatible with net40 but it only include library for net45 which is why reference is only added for net45+.

@jainaashish can I target content files to `net45` only? How to do it using csproj file approach? 
Is it because of `content` folder or `contentFiles` folder?

**Comment by jainaashish** [comment]
Its because of `content` you can have something like `any/net45/xyz.xdt` in content folder similar to `contentFiles`

**Comment by jainaashish** [comment]
Although I'm not sure if `any/net45` will work similarly there or not so let me just check.

**Comment by SergeyKanzhelev** [comment]
@jainaashish so any recommendations how to change our project file so resulting NuGet will not be installable on `net40` projects? Now I see that `contentFiles` folder created mentioned subfolder, when `content` folder did not.

BTW, this behavior report on last versions of Visual Studio as well.

**Comment by jainaashish** [comment]
for `content` you can use tfm as a subfolder and put all the files inside that like `content/net45`
