### ISSUE TITLE
msbuild /t:pack packs unnecessary files

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6270]
From mail conversation:
I made myself a NetStandsrd 2 library.   3k with of code.  When I create a NuGet with /t:pack it includes 122 additional assemblies.   Some 300k for a 3k library.

Repro is here:
https://github.com/migueldeicaza/TldExtract

Use msbuild /t:pack on the csproj

**Comment by kzu** [comment]
cloned, updated to nugetizer with:

```xml
  <ItemGroup>
    <PackageReference Include="NuGetizer" Version="0.4.11" />
  </ItemGroup>
```

and removed all MSBuild customizations in the project. Updated that PR at https://github.com/migueldeicaza/TldExtract/pull/1.

and got:

![image](https://user-images.githubusercontent.com/169707/98163464-a1fa7800-1ec1-11eb-82d3-7d725a0983a9.png)

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
