### ISSUE TITLE
Signing:  code signing and timestamping EKU's should not be asserted outside of ApplicationPolicy

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6271]
The [spec](https://github.com/NuGet/Home/wiki/Package-Signatures-Technical-Details#-certificate-minimum-requirements) incorrectly said that certificates must have specific EKU's.  I corrected the spec.  Clients instead should assert that a certificate is valid for those EKU's.

**Comment by joelverhagen** [comment]
The custom validation:
https://github.com/NuGet/NuGet.Client/blob/216a50311e3b77eb7d665b69a6ea9a890a492090/src/NuGet.Core/NuGet.Commands/SignCommand/SignCommandRunner.cs#L110-L120

The validation that depends on the platform (correct):
https://github.com/NuGet/NuGet.Client/blob/216a50311e3b77eb7d665b69a6ea9a890a492090/src/NuGet.Core/NuGet.Packaging/Signing/SigningUtility.cs#L154-L162
