### ISSUE TITLE
Make sure verify and sign commands do the same verification and output the same messages

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#6274]
A package that has been created by NuGet sign should be verifiable by NuGet verify -Signatures right after creation. Both commands should perform the same validations.

In case of a failure (either error or warning) the messages shown by both should be consistent.

**Comment by clairernovotny** [comment]
This PR/fix prevents use of self-signed untrusted certs for test purposes without reverting to nasty reflection. 

What if we want to create untrusted packages for testing? :)

/cc @dtivel

**Comment by PatoBeltran** [comment]
@onovotny right now untrusted certificates are not supported by package signing. If you wanted to sign a package with a self signed certificate for testing you could add that certificate to your trusted root. Note that this should only be done for testing.

If you wanted to have a package signed with an untrusted certificate, you could trust the certificate, sign, and the remove the trust. This way when you verify the package the certificate would not be trusted.

**Comment by clairernovotny** [comment]
As I raised in my GitHub issue though, the related methods need to be public. They also require this workaround for me to support self-signed untrusted certs:

https://github.com/onovotny/NuGetKeyVaultSignTool/blob/004fde144e5b303870e3bc5828ad6272aad448dd/NuGetKeyVaultSignTool/SignCommand.cs#L80-L87

To be clear, I don't want to have to trust a cert just to use it for signing.
