### ISSUE TITLE
.NET Core Console App Project (.csproj) folder level Nuget.Config can't be used as current project's owned 3rd party's nuget packages source folder  in Visual Studio 2017 v15.5.0 

### ISSUE THREAD

**Issue by AwesomeYuer** [NuGet/Home#6280]
I want make .NET Core App solution use it's child folder level nuget packages folder, but I can't do it. in VS2017 (v15.5) 

1. run Visual Studio 2017 v15.5.0
2. create new Console App(.NET Core)
3. add new item: nuget.config for current project
4. edit the nuget.config as below: 

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
        <add key="Project" value="..\NuGetPackages" />
    </packageSources>
</configuration>`

5. create new folder named with "NuGetPackages" in Solution folder, that's Parent folder of project folder
6. save and close Solution
7. open solution again
8. add one 3rd party nuget package reference for the project
9. open .csproj as below:

`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
  </ItemGroup>
</Project>
`

10. the 3rd Party Nuget Packages files have not been moved to Solution level folder, that's 
`<add key="Project" value="..\NuGetPackages" />`

For your reference
the Test Solution and Projects as below:
https://github.com/Microshaoft/NugetPackageReference.NETCore.test

**Comment by jainaashish** [comment]
Please tell us which documentation did you follow to create your solution like this? This is not a right way to achieve what you're trying to achieve.

`<add key="Project" value="..\NuGetPackages" />` means you added a new NuGet source to get packages. It doesn't mean that it will restore packages in this folder. In order to set that you need to use `globalPackagesFolder`  property. Please go through documentation to get more details.  https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

**Comment by AwesomeYuer** [comment]
thanks your feedback in time. 
I want make my solution use offline packages folder, like '.NET framework'  solution's  packages folder if the packages have been downloaded from internet for the first reference in some projects in the solution.
just I have add nuget.config/packages.config
 for my .NET Core App project, the content as below:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value="..\nugetpackages" />
 </config>
</configuration>`
but it's not affect, the referenced nuget packages in the original folder yet. 
![nuget issus](https://user-images.githubusercontent.com/1026479/33791948-852f6cbc-dccf-11e7-9ffe-793d88d804cf.jpg)

**Comment by rrelyea** [comment]
Your nuget.config has told NuGet that there are two places to try to fetch packages from.
With a .netcore SDK based project, we do not support a Solution level folder to keep packages in.
Instead, we "restore" packages into the global packages folder, which defaults to, "users\<yourname>\.nuget\packages".

Each solution doesn't need its own copy...we have a shared folder for all solutions on your machine.

**Comment by AwesomeYuer** [comment]
@rrelyea , I have a lot of solutions depends on multiple different versions of nuget package, such as json.net 1.0～10.0, I want save them into their  solution owned directory, it's like .net solution(not net core), in .net solution situation, there is a sub directory named packages in solution directory, and every sub project will depends and reference package from here. also these packages asset can be commited to version control system with their owned solution. I strongly suggest this function can be used in .NET core/standard solution and project.

**Comment by emgarten** [comment]
NuGet.Config needs to be next to the solution file for VS.

Take a look at the docs for further help on configuring custom restores like this.

**Comment by AwesomeYuer** [comment]
@emgarten thanks for your support

**Comment by sdg002** [comment]
Hi All,
Thanks for the responses. I have a question which related to Nuget packages on the Build Server. We are using Jenkins. We have been used to checking in the Nuget packages folder into Source Control because we found that this was a reliable way to version control all our dependencies. The Packages folder was under the .NET Solution folder and all worked well.

With the changes to Nuget as described in this post, Nuget will look into %userprofile% or at the machine level. Does that mean we no longer need to checkin the Nuget packages folder?

thank you.

**Comment by akyriako** [comment]
> Your nuget.config has told NuGet that there are two places to try to fetch packages from.
> With a .netcore SDK based project, we do not support a Solution level folder to keep packages in.
> Instead, we "restore" packages into the global packages folder, which defaults to, "users<yourname>.nuget\packages".
> 
> Each solution doesn't need its own copy...we have a shared folder for all solutions on your machine.

And what is happening when MSBuild tries to restore these packages (there is no user folder)? How do I configure this ? because it breaks the build process in Jenkins 

Thanks in advance
