### ISSUE TITLE
Should we be enforcing 1 package type per package

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6298]
Motivated by https://github.com/NuGet/Home/wiki/Global-Tools---NuGet-Implementation/

@rrelyea  thinks that we should have already been enforcing 1 package type per package, but currently that's allowed by both specification and the implementation of Pack. 

Update:

Pack doesn't validate. 
Install through PM UI validates. 
Adding in the package reference manually and restoring doesn't validate. 

This would be a breaking change.

**Comment by natemcmaster** [comment]
What exactly is the concern with having multiple packageType's per package? I'm not sure I understand why this restriction is important to NuGet when last year the design was _intentional_ about supporting multiple types per package. https://github.com/NuGet/Home/wiki/Package-Type-%5BPacking%5D

For example, today, this is a totally valid package:

```xml
<nuspec>
  <metadata>
     <packageTypes>
        <packageType name="Dependency" />
        <packageType name="DotNetCliTool" />
        <packageType name="Template" />
    </packageTypes>
   </metadata>
</nuspec>
```

It is possible for a package author to construct one template that provides multiple pieces of functionality in one package.

**Comment by nkolev92** [comment]
The answer here is no for the general feature.

However, certain package types can declare themselves incompatible with others and we have done that with DotnetTool and DotnetPlatform
