### ISSUE TITLE
ResolverGather is not pruning prerelease packages properly

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#630]
Repro steps:
Run-test FSharpDependentPackageUninstall

The failure of this test is due to the addition of the call below to ResolverGather.

package.SetIncludePrereleaseForDependencies();

The effect of it is that all prerelease versions are included in dependency resolution during install (even though –pre is not specified) for dependency packages. 

In the functional test itself, it’s breaking another contract of considering prerelease version (1.0.0-a) not satisfying the version range of [0.5, 2.0] (when -pre is not specified), while populating the depenendentDictionary. Hence expected exception was not thrown as the depenendentDictionary is null.

**Comment by yishaigalatzer** [comment]
@johnataylor I believe you fixed this already, can you close and open up the follow up issue we discussed?
