### ISSUE TITLE
Signing:  verify command's CertificateFingerprint not enforced

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6304]
1. Create a certificate using the following PowerShell script:
```
$certificate = New-SelfSignedCertificate -Type CodeSigningCert -CertStoreLocation "Cert:\CurrentUser\My" -Subject "CN=Test certificate for testing NuGet package signing" -KeyAlgorithm RSA -HashAlgorithm SHA256 -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeySpec Signature -AlternateSignatureAlgorithm

$fingerprint = $certificate.Thumbprint
$currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$pfxFilePath =".\$fingerprint.pfx"

$output = Export-PfxCertificate -Cert "Cert:\CurrentUser\My\$fingerprint" -ProtectTo $currentUser -FilePath $pfxFilePath
$output = Import-PfxCertificate -FilePath $pfxFilePath -CertStoreLocation Cert:\CurrentUser\Root

Get-ChildItem "Cert:\CurrentUser\My\$fingerprint" | Remove-Item
Remove-Item $pfxFilePath

Write-Host Certificate created with fingerprint $fingerprint
```
2. Sign a package:  `NuGet.exe sign <PackageFilePath> -CertificateStoreName Root -CertificateFingerprint <Fingerprint>`
3. Verify the package:  `NuGet.exe verify -signatures <PackageFilePath> -CertificateFingerprint abc`

Expected result:  step 3 will fail with an error saying the package wasn't signed with a matching certificate
Actual result:  no errors are reported

**Comment by v-luzh** [comment]
It is fixed on NuGet Client Dev 4716.

**Comment by dtivel** [comment]
@v-luzh, this still repros for me on dev 4716 and the latest dev branch sources.

**Comment by v-luzh** [comment]
@dtivel , you are right. The bug still repro on NuGet Client Dev 4721.
