### ISSUE TITLE
The returned type for DNX project on PMC is unknown

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#631]
PM> get-project

![capture](https://cloud.githubusercontent.com/assets/1087852/7737684/e63e6980-ff01-11e4-900c-5f84313d6149.PNG)

**Comment by zhili1208** [comment]
I don't think this is related to nuget, for get-project, nuget just get the EnvDte.project from DTE and pass it to powershell command, the project type should be defined in DNX part.

**Comment by yishaigalatzer** [comment]
This should be fixed by the DNX (CLI) project owners
