### ISSUE TITLE
unable to list or publish the packages using NPE with Nuget Server version 3.0.1.0

### ISSUE THREAD

**Issue by cmreddyv** [NuGet/Home#6319]
unable to publish/list the packages in Nuget Package Explorer for the latest version of New Nuget server version 3.0.1.0

FY!, this a plain nuget server using to host the packages, created using the approach creating a empty asp.net web application and then installed the nuget server in that solution using manage nuget package sources and then host the applciation on IIS.

We are able to list the packages using the nuget.exe and VS but not with the Nuget package explorer.

Nuget package explorer is working with the previous version of Nuget server after upgrading to the latest version it stopped working

Can find the details at https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/275#issuecomment-351087962

**Comment by emgarten** [comment]
@joelverhagen any ideas why this would have changed on NuGet.Server?

NPE is using very old 2.x NuGet libraries.

**Comment by joelverhagen** [comment]
Moving to [NuGetGallery repository](https://github.com/NuGet/NuGetGallery/issues), as this is a server-side issue.

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #5193](https://github.com/NuGet/NuGetGallery/issues/5193) via [**ZenHub**](https://www.zenhub.com/)
