### ISSUE TITLE
AssetTargetFallback support for GetReferenceNearestTargetFrameworkTask

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6322]
GetReferenceNearestTargetFrameworkTask should allow additional fallback frameworks to be passed. This would enable scenarios such as `net47 + UAP` to work.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/GetReferenceNearestTargetFrameworkTask.cs

**Comment by rrelyea** [comment]
Can we get this in current sprint?

**Comment by rrelyea** [comment]
Would need to coordinate with msbuild team in their 15.7 codebase, to take advantage of this.
