### ISSUE TITLE
Access denied for restore/update packages

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#6328]
I am using Windows 10 with Visual Studio 2017 Community. I am creating Xamarin project and right after that I am updating NuGet packages, but I see this error - `Access to the path c:users/username/.nuget/packages/* is denied`. The Nuget creates read-only folders with no access for all Windows users to them and after that it has no access to these folders. I am using Visual Studio as admin. If restart Visual Studio I have access to these folder, but after that if I try to update some or all packages again I get same error.

**Comment by emgarten** [comment]
@vladi160 NuGet doesn't specifically set permissions on these files, it uses the defaults.

I suggest changing the permissions on your `.nuget` folder manually to ensure that you can also access these files from a non-admin process.

**Comment by mishra14** [comment]
@vladi160 Please let us know if you are still blocked.

**Comment by ghost** [comment]
Hi, `.nuget` folder is with full permissions. This problem is not for all package folders. For the example when I test now is this folder `Error: Access to the path 'C:\Users\username\.nuget\packages\xamarin.android.support.design\25.4.0.2' is denied.`

**Comment by emgarten** [comment]
Set the permission on your packages folder and try again.

**Comment by bgavrilMS** [comment]
This is still happening, was there an actual fix?

**Comment by TerryDieckmann** [comment]
Having the same issue.

- Running Visual Studio as administrator or not does not affect this problem.
- Deleting the project and clone it from the remote again does not fix the problem.
- Removing all NuGet packages results in another error: _Assets file project.assets.json not found. Run a NuGet package restore to generate this file_.
- Removing or adding NuGet packages will give you the same "access denied" error, but with different package-names.
- Same behaviour with `dotnet restore` as with `Update-Package`

**Comment by MendelBak** [comment]
I'm having a similar issue. Running VS as admin or running `dotnet restore` in my console as an admin does not overcome this error message saying that I've been denied access.

**Comment by AnisTss** [comment]
Any updates on this issue ?
I cleared NuGet cache, and now I am having this problem.

**Comment by ttamaranazc** [comment]
I have cleared the nuget cache. After that I ran dotnet restore.

I received below error:

C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error : Access to the path 'System.Diagnostics.DiagnosticSource.dll' is denied. [E:\XXXX\My project.sln]

Looks like clearing nuget cache causing issue. 
Please guide.

**Comment by ttamaranazc** [comment]
> I have cleared the nuget cache. After that I ran dotnet restore.
> 
> I received below error:
> 
> C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error : Access to the path 'System.Diagnostics.DiagnosticSource.dll' is denied. [E:\XXXX\My project.sln]
> 
> Looks like clearing nuget cache causing issue.
> Please guide.

Deleted mentioned file(s) and folder as mentioned in the [question ](https://developercommunity.visualstudio.com/content/problem/24316/nuget-access-is-denied-to-path.html) description.

`I've encountered similar issues with VS 2015 but was able to delete my AppData\Roaming\NuGet\NuGet.config or delete <my user profile path>.nuget\packages to fix it.`

**Comment by StachuDotNet** [comment]
I've just faced a similar issue on linux (Ubuntu) and felt like this would be the best place to record the resolution:

I run 64-bit Ubuntu, and I think I installed `dotnet` with sudo (for some reason).
As such, when NuGet packages were downloaded to `/home/{me}/.nuget/{etc.}`, the folders inside were owned by `root`.
Because of this, when I attempted to download those NuGet packages (actually via Paket, a NuGet client alternative), it failed due to access issues.

To resolve, this I `cd`'d my way to the `.nuget` folder inside `home`, and did this bad boy: `sudo chown -R $USER:$USER .`

Then, I got past that hurdle.

**Comment by davidcorbin** [comment]
I had this issue and fixed it by setting `$USER` before running `dotnet new <proj type>`. Also make sure your user has permission for files in the the `~/.nuget/` directory.

**Comment by joshmcode** [comment]
Same issue. I had 3 instances of Visual Studio 2017 open. It appears one of them may have acquired some kind of lock on a resource? Anyway, after closing down the other two instances, the restore worked.

**Comment by jalaniz1** [comment]
> I've just faced a similar issue on linux (Ubuntu) and felt like this would be the best place to record the resolution:
> 
> I run 64-bit Ubuntu, and I think I installed `dotnet` with sudo (for some reason).
> As such, when NuGet packages were downloaded to `/home/{me}/.nuget/{etc.}`, the folders inside were owned by `root`.
> Because of this, when I attempted to download those NuGet packages (actually via Paket, a NuGet client alternative), it failed due to access issues.
> 
> To resolve, this I `cd`'d my way to the `.nuget` folder inside `home`, and did this bad boy: `sudo chown -R $USER:$USER .`
> 
> Then, I got past that hurdle.

Thank you. I had this issue on a fresh install of visual studio 19 on MacOS Mojave(10.14.6). I used `sudo chown -R myUsername .`

**Comment by StachuDotNet** [comment]
Glad it was helpful @jalaniz1 !

**Comment by ashutoshsinghparmar** [comment]
I am also facing the same issue... in VS2015

**Comment by shafeenakabir** [comment]
I also faced the same issue. The issue was that dll at the given Nuget/packages* location was read-only. The fix was to make the dll non read-only in file properties.
Thanks.

**Comment by ashutoshsinghparmar** [comment]
So my case was...
VS2015 Update-3, had solution folder .nuget which had our own nuget repositories referred.

This .nuget solution folder was creating trouble.
I deleted that .nuget folder and added those local nuget repository directly to the Visual Studio.

After that I am able to install and update packages.

Issue was with solution .nuget folder.

**Comment by svdHero** [comment]
I did a
```
dotnet nuget locals all -c
```
and now I can neither access nor delete the `package` subdirectory. :sob: 
I am on Windows 8.1. Does anybody have an advice? I should add that I do have local admin rights on my machine. I can't even delete the folder from an admin `cmd`.

**Comment by svdHero** [comment]
Never mind. Problem solved. I forgot about the good old Windows rule:

![classic](https://user-images.githubusercontent.com/24250824/72595286-c624a280-3909-11ea-9ccf-8ab2cb92f5c3.jpg)

**Comment by ronwarner** [comment]
> Never mind. Problem solved. I forgot about the good old Windows rule:
> 
> ![classic](https://user-images.githubusercontent.com/24250824/72595286-c624a280-3909-11ea-9ccf-8ab2cb92f5c3.jpg)

What is that image from?

**Comment by ronwarner** [comment]
@svdHero - What is that image from?

**Comment by StachuDotNet** [comment]
@ronwarner IT Crowd - first episode, I think.

**Comment by svdHero** [comment]
Yes. Brilliant TV series. At least the first two seasons.

**Comment by Belereg** [comment]
> So my case was...
> VS2015 Update-3, had solution folder .nuget which had our own nuget repositories referred.
> 
> This .nuget solution folder was creating trouble.
> I deleted that .nuget folder and added those local nuget repository directly to the Visual Studio.
> 
> After that I am able to install and update packages.
> 
> Issue was with solution .nuget folder.

where is that folder?

**Comment by lucastedeschi** [comment]
> Never mind. Problem solved. I forgot about the good old Windows rule:
> 
> ![classic](https://user-images.githubusercontent.com/24250824/72595286-c624a280-3909-11ea-9ccf-8ab2cb92f5c3.jpg)

Restart the Windows solved here too

**Comment by woter1832** [comment]
The solution/project built fine on my Windows device in VS Code, (`dotnet build`) but was failing on my Azure DevOps agent running Linux Fedora core:
```
##[error]/usr/share/dotnet/sdk/5.0.403/NuGet.targets(131,5): Error : Access to the path /usr/share/dotnet/.nuget/packages/nlog/4.7.11' is denied.
  Permission denied
``` 
In my case, the agent couldn't install/copy the `nlog` package to the path. Looking at the permissions, everything was owned by root.

I am not sure why, but my guess is when installing NuGet, it looks for the install location of dotnet and installs itself under `/usr/share/dotnet`. As dotnet is installed as root (`sudo dnf net5.0`), it ends up being owned by root.

I guess this can be controlled by `NuGet.targets` (`/usr/share/dotnet/sdk/5.0.403/NuGet.targets`), but that's one scary looking file! I'm leaving it alone.

The AzDO agent is not allowed to be installed as root and is installed as a user and therefore doesn't have permission to access `/usr/share/dotnet/.nuget/packages`. 

I noticed I had two Nuget package locations:
* `/home/vsts_user/.nuget/packages/`
* `/usr/share/dotnet/.nuget/packages/` 

How this has happened, I do not know, but my thinking was that there must be a way to control where packages are installed/copied to.

A Google came up with https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section, and under the `globalPackagesFolder` key, is a mention to an environment variable: `NUGET_PACKAGES`.

## TL&DR
You can set the attribute any way you like, in your `NuGet.config` file or an environment variable. I chose the quickest option which was to set a variable in my pipeline:
`NUGET_PACKAGES: '/home/vsts_user/.nuget/packages'`

Problem solved.

P.S. This won't work as it needs to be an absolute path.
`NUGET_PACKAGES: '~/.nuget/packages'`
