### ISSUE TITLE
nuget install packages.config vs nuget install package

### ISSUE THREAD

**Issue by jlovs** [NuGet/Home#6335]
NuGet product used NuGet.exe
NuGet version (4.5.0.4696)
OS version (Windows 10.0.14393)

I am using nuget as a standalone package manager, not using Visual Studio at all.
Each project has a .nuspec and a packages.config file.

Example:
If I have a project P with a packages.config with one dependency towards package A. Package A has a dependency to package B.
My problem is that I don't get package B installed when running:
`nuget install packages.config`
in project P. I only get package A installed.

When I run:
`nuget install A`
in project P, I get both A and B installed.

Is this the expected behavior?
If it is, is there a way to get both packages installed with one command using packages.config?
Or is there any other way of making this work?

**Comment by emgarten** [comment]
`nuget install A` resolves the dependencies and downloads/extracts all resolved packages.

`nuget install packages.config` is the same as `nuget restore packages.config` and does not resolve dependencies.

**Comment by jlovs** [comment]
@emgarten Ok, so there is no way to resolve all dependencies with a CLI command, using the contents of packages.config?

**Comment by emgarten** [comment]
No, a packages.config file is the output of resolving all dependencies. There isn't a way to use it as the input to resolve further.

**Comment by jlovs** [comment]
@emgarten Ok, so if I want to use NuGet CLI standalone without Visual Studio, how can I then manage this?
I want to have a file with the direct dependencies, which I thought was packages.config file? 
Is there a way to generate this file using the CLI with the input of another file that only contains direct dependencies? 

Or is it not possible to use the CLI standalone and get a working package management system?

**Comment by emgarten** [comment]
@jlovs are you consuming the packages from projects and building? Or are you *just* trying to get the packages onto disk to use in a different way?

Install/update/uninstall operations for packages.config must be done in VS. NuGet.exe install only supports downloading the package, it cannot update your project.

For full CLI support outside of VS take a look at using `PackageReference`: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by gerektoolhy** [comment]
this is confusing:
```
`nuget install` A resolves the dependencies and downloads/extracts all resolved packages.

`nuget install` packages.config is the same as nuget restore packages.config and does not resolve dependencies.
```

What was the reasoning to make `install` behave differently depending on the argument passed?  I would expect `install` to behave same way - either resolve all packages, or not, but not both.
