### ISSUE TITLE
VS does not show a NU3002 error when installing a tampered package

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6337]
With package signing, package readers will fail to install signed packages that have been modified. 

As described in [NuGet-package-signing-Errors-and-Warnings](https://github.com/NuGet/Home/wiki/NuGet-package-signing-Errors-and-Warnings) this failure should generate a message in the error list with the specific NU3002 error code.

Current VS client only shows the generic error message: `Package restore failed. Rolling back package changes for <ProjectName>`

**Comment by mishra14** [comment]
As discussed in email - 

We seems to have regressed this since initial work done for package signing. Initially we displayed the following message - `Package integrity check failed. The package has been tampered.`

Assigning to @zhili1208 who did the initial work in this space.

**Comment by rrelyea** [comment]
Discussion with @rido-min & @mishra14
Let's confirm that output window has the details of the failure.

We need some UI (or similar) work in NuGet to reflect the install failure.
Error list may not be the right place...Do we have a dialog? yellow bar?

**Comment by rido-min** [comment]
Dicussed with @dtivel, we should show a proper error message in the Error List if Installs fails.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.Client@b130abccf5302f47a3e791062ab43436bbafc297
