### ISSUE TITLE
Package Manager Console hook for ASP.NET 5 projects

### ISSUE THREAD

**Issue by rowanmiller** [NuGet/Home#634]
If a user is developing on Windows in Visual Studio, it's clear from aspnet/EntityFramework#1196 that they still expect to be able to use the Package Manager Console with ASP.NET 5 projects.

The piece that's missing for us to light up the Entity Framework PowerShell commands on ASP.NET 5 projects is a hook to import our PowerShell module.

For *.csproj projects this is as simple as calling `Import-Module` inside of [tools/init.ps1](https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Commands/tools/init.ps1#L7).

**Comment by yishaigalatzer** [comment]
Please talk to your friends in the DNX project.
