### ISSUE TITLE
VS nuget restore is not respecting NoWarn on package references

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#6340]
When I restore in VS, NoWarn on PackageReference has no effect.

When I restore via msbuild /t:restore, it works as expected. 

This is a regression in the 15.6 dogfood build I have. It works fine on VS 15.5.1 RTM.

## Details about Problem

* **NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe)**: VS UI
* **NuGet version (x.x.x.xxx)**: 4.6.0.??? (VS About doesn't show 4th part)
* **VS version (if appropriate):** 15.6.0 Preview 1.1 [27217.0.d15.6]
* **Worked before? If so, with which NuGet version**: Yes, worked fine in VS 15.5.1 RTM.

## Detailed repro steps so we can see the same problem

1. Build this project with restore having been done in VS:

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NewtonSoft.Json" Version="4.5.11" NoWarn="NU1701" />
  </ItemGroup>
</Project>
```

## Expected result

Builds without warnings

## Actual result
```
1>c:\users\nicholg\source\repos\ConsoleApp22\ConsoleApp22\ConsoleApp22.csproj : warning NU1701: Package 'Newtonsoft.Json 4.5.11' was 
restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be 
fully compatible with your project.
```

cc @emgarten @davkean

**Comment by davkean** [comment]
@nguerrera Can you set `PROJECTSYSTEM_PROJECTOUTPUTPANEENABLED=1` before opening VS and attach the contents of the Output -> Project category after restore? This will help us figure if a project system or NuGet issue.

**Comment by mishra14** [comment]
I found the issue. it was a change we took recently. I am working on a fix.
