### ISSUE TITLE
[Test Failure][Signing] "Cannot prompt for input in non-interactive mode" when signing with a certificate is password protected without using CertificatePassword

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#6341]
## Details about Problem
NuGet Version : Release-4.6.0-Preview2 4745
VS Version : D15.6 27218.00
OS Version : RS3_Release 16299.15.170928-1534

## Detailed repro steps so we can see the same problem
1.	Create a new package.
2.	Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -Password password.
3.	Sign a package:  NuGet.exe sign “PackageFilePath” -CertificatePath “PfxFilePath”.
4.	Try to enter the password at the prompt.
## Expected:
I can enter the password at the prompt.
## Actual:
I can not enter the password at the prompt and there is an error saying that: Cannot prompt for input in non-interactive mode as below screenshot.
![cannotenterpassword](https://user-images.githubusercontent.com/20632625/34198940-fda63c4a-e5a6-11e7-8d09-00daf6cf5035.png)

## Note:
It didn’t repro on D15.6stg 27207.3001 + NuGet Client Dev 4716.

**Comment by mishra14** [comment]
@v-luzh Can you please give me the value for the following environment variables - 

1. `NUGET_EXE_NO_PROMPT`
2. `FORCE_NUGET_EXE_INTERACTIVE`
3. `VisualStudioVersion`

You can get the values by using powershell - 
```
PS > $env:NUGET_EXE_NO_PROMPT
PS > $env:VisualStudioVersion
PS > $env:FORCE_NUGET_EXE_INTERACTIVE
```

**Comment by v-luzh** [comment]
@mishra14 We can not get the value for the above environment variables except for VisualStudioVersion on D15.6stg 27224.3000+NuGet Client Dev 4763 as below screenshot. Did we miss any additional step?
![powershell](https://user-images.githubusercontent.com/20632625/34335694-bff89c7e-e98b-11e7-898b-4a079bd0ca9f.PNG)

**Comment by mishra14** [comment]
@v-luzh can you please try this scenario in a powershell/cmd.exe outside of the developer command prompt?

**Comment by emgarten** [comment]
`VisualStudioVersion` might be the problem here. I came across this when testing auth and believe it is a bug, it shouldn't skip the prompt based on the variable. I've opened https://github.com/NuGet/Home/issues/6385 to fix it.

**Comment by v-luzh** [comment]
@mishra14, it still repro on D15.6stg 27310.3001+NuGet Client Release-4.6.0-RTM 4802. Would you please help to re-active this bug?

And I got nothing after typing all the command in a powershell/cmd.exe as below.
![command](https://user-images.githubusercontent.com/20632625/34812481-a2d0ccba-f69d-11e7-8d38-c2e4a034d1dd.PNG)

**Comment by emgarten** [comment]
Reopening for @mishra14 to investigate with signing

**Comment by mishra14** [comment]
@v-luzh I cannot repro this - 

```
C:\Users\anmishr\Source>e:\NuGet.Client\artifacts\NuGet.CommandLine\15.0\bin\Debug\net46\NuGet.exe sign f:\validation\sign\unsigned\nuget.server.3.0.0.nupkg -OutputDirectory f:\validation\sign\signed -CertificatePath f:\validation\sign\certs\test.pfx
WARNING: NU3002: The '-Timestamper' option was not provided. The signed package will not be timestamped. To learn more about this option, please visit https://docs.nuget.org/docs/reference/command-line-reference
Please provide password for: f:\validation\sign\certs\test.pfx
Password: ****
```

-------------------------------------
Update, I think Justin's change was not in the rtm branch. I will try to get that in.

**Comment by mishra14** [comment]
@v-luzh I have cherry-picked the [commit](https://github.com/NuGet/NuGet.Client/commit/84e870aa0c5336284155f8111eccdf4277ca4290) from dev. Can you please retry with the new build tonight?

If you are still facing this issue then can you please email me details about the machine that I can access to repro this issue?

**Comment by v-luzh** [comment]
@mishra14, It had been fixed on D15.6 27316.00+NuGet Client Release-4.6.0-RTM 4825. Please help to resolve it as fixed and close this bug, thanks.
![6341fixed](https://user-images.githubusercontent.com/20632625/35077780-b8e263c0-fbf6-11e7-9c88-1099dab394bc.PNG)
