### ISSUE TITLE
dotnet nuget push *.nupkg --config-file ./config/My.Config    error: Unrecognized option '--config-file'

### ISSUE THREAD

**Issue by huaryliu** [NuGet/Home#6342]
dotnet nuget push *.nupkg --config-file ./config/My.Config

error: Unrecognized option '--config-file'

Env:

NuGet Version: 4.3.0.4406
dotnet.exe --version (if appropriate): 2.1.2

.NET Command Line Tools (2.1.2)                 
                                                
Product Information:                            
 Version:            2.1.2                      
 Commit SHA-1 hash:  5695315371                 
                                                
Runtime Environment:                            
 OS Name:     Windows                           
 OS Version:  10.0.16299                        
 OS Platform: Windows                           
 RID:         win10-x64

**Comment by mishra14** [comment]
`dotnet nuget push` command does not support `--config-file` switch. 

Please run `dotnet nuget push --help` to learn more about the switches that it supports. 

e.g. - 

```
E:\NuGet.Client [dev-anmishr-packfix ≡]> dotnet nuget push --help


Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Specifies the server URL
  -ss|--symbol-source <source>   Specifies the symbol server URL. If not specified, nuget.smbsrc.net is used when pushing to nuget.org.
  -t|--timeout <timeout>         Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
```

**Comment by JoryUK** [comment]
Following documentation incorrectly suggests that it does
https://docs.microsoft.com/en-us/nuget/tools/cli-ref-push
