### ISSUE TITLE
AngleSharp 0.9.9 is not listed in visual studio VS2017 references

### ISSUE THREAD

**Issue by hiromi3** [NuGet/Home#6347]
Hello,
NuGet product used: VS UI
NuGet version (x.x.x.xxx): 4.5.0
VS version (if appropriate): VS2017 Community Ver 15.5.2
OS version (i.e. win10 v1607 (14393.321)): ver 10.0.16299 build 16299

## Detailed repro steps to reproduce the same problem
In my VS2017 ver 15.5.2 with Japanece language setting, the following procedure will reproduce the problem.
1. Create C# New Console Project with .NET Framework 4.7 .
2. Add AngleSharp 0.9.9 by NuGet Package Manager.
The messages in output window show that the installation was successfully done, but AngleSharp is not listed in reference.
3. Then I downgrade it to 0.9.8.1 , AngleSharp is shown in reference list.
4. Then, I upgrade it to 0.9.9, it is removed from the list.
So, it is very strange!
Important notice: This symptom does not always occurr by the above steps.
Some of my C# projects do not have this problem and AngleSharp 0.9.9 is listed fine.

I reported this symptom to AngleSharp's author and he recommended me to report it in this page.
If you can reproduce the problem, please fix it.

**Comment by mishra14** [comment]
@hiromi3 Thanks for the detailed feedback. I tried a quick repro and I am not seeing this issue.

Are you only getting this issue in Japanese language or does it happen in English as well?
Also, can you try with .NET Framework 4.6 as well?

Thanks!

**Comment by hiromi3** [comment]
Hi, 
Thank you for quick reply.
I changed the language setting to English and tested again.
For all the following .NET Framework versions
4.7
4.6
4.5
4.0
the symptom reproduced.

For example, .NET Framework 4.7 with English environment, I created a Console Application.
Then I installed AngleSharp 0.9.9 .
The following messages are shown, but AngleSharp is not listed references.
------------------------
Attempting to gather dependency information for package 'AngleSharp.0.9.9' with respect to project 'ConsoleApp3', targeting '.NETFramework,Version=v4.7'
  GET https://api.nuget.org/v3/registration3-gz-semver2/anglesharp/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/anglesharp/index.json 159ms
Total number of results gathered : 1
Gathering dependency information took 255.08 ms
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	223.27 ms
Attempting to resolve dependencies for package 'AngleSharp.0.9.9' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'AngleSharp.0.9.9'
Resolved actions to install package 'AngleSharp.0.9.9'
Retrieving package 'AngleSharp 0.9.9' from 'nuget.org'.
For adding package 'AngleSharp.0.9.9' to project 'ConsoleApp3' that targets 'net47'.
For adding package 'AngleSharp.0.9.9' to project 'ConsoleApp3' that targets 'net47'.
Adding package 'AngleSharp.0.9.9' to folder 'e:\MyDocuments\Visual Studio 2017\Projects\ConsoleApp3\packages'
Added package 'AngleSharp.0.9.9' to folder 'e:\MyDocuments\Visual Studio 2017\Projects\ConsoleApp3\packages'
Added package 'AngleSharp.0.9.9' to folder 'e:\MyDocuments\Visual Studio 2017\Projects\ConsoleApp3\packages' from source 'https://api.nuget.org/v3/index.json'
Added package 'AngleSharp.0.9.9' to 'packages.config'
Added file 'packages.config' to project 'ConsoleApp3'.
Successfully installed 'AngleSharp 0.9.9' to ConsoleApp3
Executing nuget actions took 321.16 ms
Time Elapsed: 00:00:00.6972842
========== Finished ==========

and packages.config is:

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;packages&gt;
 &lt;package id="AngleSharp" version="0.9.9" targetFramework="net47" /&gt;
&lt;/packages&gt;

**Comment by hiromi3** [comment]
Hello,
Today, I installed the latest AngleSharp 0.9.9.1, I could install it successfully.
I do not know why previous 0.9.9 has a installation problem in my VS2017, anyway, the problem was solved.
If the problem happens again, I will report to you.
