### ISSUE TITLE
Nuget push error  Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'

### ISSUE THREAD

**Issue by huaryliu** [NuGet/Home#6348]
I run this command in Ubuntu 
 
nuget push *.nupkg [apikey] -src http://***/repository/nuget/ -configFile Nuget.config

Pushing l 1.0.0 to 'http://***/repository/nuget/'...
Using credentials from config. UserName: ***
**Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'**

Nuget.config like this
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="A" value="http://***/repository/nuget/" />
  </packageSources>
  <packageSourceCredentials>
    <A>
      <add key="Username" value="***" />
      <add key="ClearTextPassword" value="*****" />
    </A>
  </packageSourceCredentials>
</configuration>
```

**This Commond can successful run in Windows**

I found nuget version is 2.8.7.0 in linux ,How can i get latest nuget in linux？

**Comment by emgarten** [comment]
> I found nuget version is 2.8.7.0 in linux ,How can i get latest nuget in linux？

https://www.nuget.org/downloads

**Comment by mishra14** [comment]
@JianhuaLiu on linux you can use the [`dotnet nuget push`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) command using the [dotnet  cli](https://www.microsoft.com/net/learn/get-started/linuxredhat).

Please let us know if you are still blocked with the latest release of `nuget.exe` or `dotnet`.

**Comment by huaryliu** [comment]
@mishra14  on Linux I want to use custom config file,the command `dotnet nuget push` can not support custom config file .
the command `dotnet nuget push *.nupkg --config-file ./config/My.Config` can not run correctly
do you have other solution ?

**Comment by mishra14** [comment]
@JianhuaLiu have you tried using the latest NuGet.exe from https://www.nuget.org/downloads?

**Comment by huaryliu** [comment]
On windows,i used Nuget.exe,and it is effective,but on linux,i canot use Neuget.exe.do you have other solution ?

**Comment by mishra14** [comment]
@JianhuaLiu Thanks for clarifying that.

`dotnet nuget push` supports passing of source through command line along with api keys. 
Why do you need to pass a config file?

**Comment by huaryliu** [comment]
@mishra14 
Our nexus repository Maybe  have some  problem, i will check our config.
Thanks for your help.
