### ISSUE TITLE
Dead link on 'How to contribute' page

### ISSUE THREAD

**Issue by ngruson** [NuGet/Home#6350]
On the page https://github.com/NuGet/Home/wiki/How-to-contribute, there's a dead link to 'Engineering guidelines' which points to https://github.com/contribute/coding-guidelines.
Not sure what it should be.

**Comment by mishra14** [comment]
@ngruson Thanks for pointing that out to us. I have fixed this. 

You can check out the updated [page](https://github.com/NuGet/Home/wiki/How-to-contribute).
