### ISSUE TITLE
Invalid URI: The Authority/Host could not be parsed

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6352]
I'm using NuGet within Visual Studio 2017, when i try to install a package on an Web Forms project hosted in local IIS, it is failing with the following error:

Invalid URI: The Authority/Host could not be parsed

This is package manager console details:

Attempting to gather dependency information for package 'Newtonsoft.Json.10.0.3' with respect to project 'http://iis.domain.local/', targeting '.NETFramework,Version=v4.5.1'
Gathering dependency information took 222,41 ms
Attempting to resolve dependencies for package 'Newtonsoft.Json.10.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.10.0.3'
Resolved actions to install package 'Newtonsoft.Json.10.0.3'
Retrieving package 'Newtonsoft.Json 10.0.3' from 'nuget.org'.
Adding package 'Newtonsoft.Json.10.0.3' to folder 'E:\Progetti_VBNET\customer\project\packages'
Added package 'Newtonsoft.Json.10.0.3' to folder 'E:\Progetti_VBNET\customer\project\packages'
Install failed. Rolling back...
Package 'Newtonsoft.Json.10.0.3' does not exist in project 'http://iis.domain.local/'
Removing package 'Newtonsoft.Json.10.0.3' from folder 'E:\Progetti_VBNET\customer\project\packages'
Removed package 'Newtonsoft.Json.10.0.3' from folder 'E:\Progetti_VBNET\customer\project\packages'
Executing nuget actions took 860,1 ms
Failed to add reference to 'Newtonsoft.Json'.
  Invalid URI: The Authority/Host could not be parsed.
Time Elapsed: 00:00:01.2113135

This error appear with all packages that i try to install.
This error appears after windows fall creators update and last visual studio version.
In another PC with older version of visual studio and windows creators uptdate, the packages are installed correctly.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/170931/invalid-uri-the-authorityhost-could-not-be-parsed.html
VSTS ticketId: 541991_
_These are the original issue comments:_

Matteo Gattei on 12/20/2017, 01:37 AM (37 hours ago): <p>Are you able to see any already installed package?</p><p>Check also this thread: https://developercommunity.visualstudio.com/content/problem/167181/update-1551-nuget-does-not-work-anymore-on-my-solu.html</p>

s ei on 12/20/2017, 11:37 PM (15 hours ago): After installing update to 15.5.2, nuget doesn't see any installed packages. Attempting to isntall a package ends up with failure described above.
_These are the original issue solutions:_
(no solutions)

**Comment by jainaashish** [comment]
`Failed to add reference to 'Newtonsoft.Json'.
Invalid URI: The Authority/Host could not be parsed.`

This should be moved to Project System for investigation. This error is being thrown from them while adding reference. There was a email communication as well for the same issue and there also I added project system folks to investigate.

**Comment by emgarten** [comment]
This issue was moved to dotnet/project-system#3124

**Comment by jainaashish** [comment]
This is indeed NuGet issue introduced with PR# https://github.com/NuGet/NuGet.Client/pull/1777

**Comment by glooydatonnookanthegs** [comment]
any workaround for this? I can't install my packages

**Comment by jainaashish** [comment]
This post has a workaround for this issue - https://stackoverflow.com/questions/47843907/nuget-package-install-error-invalid-uri-the-authority-host-could-not-be-pars
