### ISSUE TITLE
"How to build NuGet VisualStudio extension" steps do not work.

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#6357]
## Details about Problem
Following the steps in the readme on the [nuget home](https://github.com/NuGet/Home) page for the "How to build NuGet VisualStudio extension" doesnt work.

Following the steps gets to this. Without having to cull through the script is there a correct option to use (or no option)?

```
PS E:\Projects\NuGet.Client> .\build.ps1 -CleanCache
E:\Projects\NuGet.Client\build.ps1 : A parameter cannot be found that matches parameter name 'CleanCache'.
At line:1 char:13
+ .\build.ps1 -CleanCache
+             ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [build.ps1], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,build.ps1
```

**Comment by rohit21agrawal** [comment]
@StingyJack  i will update the documentation. You can just run ``` .\build.ps1 ``` to build the extension. If you want to skip unit tests, run ``` .\build.ps1 -SkipUnitTests ```

**Comment by StingyJack** [comment]
Thanks, I read through the script and saw that, Feel free to close this when that is updated.

**Comment by rohit21agrawal** [comment]
fixed.
