### ISSUE TITLE
[Test Failure][Signing] Package signing is successful when certificate is expired

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#6360]
## Details about Problem
**NuGet Version:** Dev 4764
**VS Version:** D15.6 27226.00
OS Version: RS3_Release 16299.15.170928-1534
## Detailed repro steps so we can see the same problem
1.	Create a new package.
2.	Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -NotBefore "2010-01-01 00:00:00" -NotAfter "2010-01-02 00:00:00".
3.	Sign a package:  NuGet.exe sign "C:\Users\mdTestAU\source\repos\Package004\Package004\JamiePackage004.1.0.0.nupkg" -CertificatePath "C:\Users\mdTestAU\Desktop\14B2A233B81E4DA585DDE93B9DB94237DA412C95.pfx"
## Expected:
Package signing should failed with an error saying "Certificate chain validation failed with error: NotTimeValid" and the package was not changed.
## Actual:
Package signing is successful without an error as below screenshot.
![timeexpired](https://user-images.githubusercontent.com/20632625/34373347-799f3112-eb15-11e7-84bd-737088703758.png)

## Note:
1. It didn’t repro on D15.6stg 27207.3001 + NuGet Client Dev 4716.
2. It didn’t repro on D15.6 27218.00 + NuGet Client Release-4.6.0-Preview2 4745.

**Comment by dtivel** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/1918.
