### ISSUE TITLE
[Test Failure] [Signing] No error show when installing signed package with expired signing certificate

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#6361]
## Details about Problem

NuGet version : Dev-4764

VS version : D15.6 27226.00

OS version : RS3_Release 16299.15.170928-1534

## Detailed repro steps 

1. Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority -NotAfter "<1 minute in the future from current local time>" .
2. Sign a package:  NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>.
3. Wait for the author signature certificate to expire.
4. In Package Manager UI, install the package into a project.
5. Verify the previous step failed with an error saying "Certificate chain validation failed with error: NotTimeValid."
6. Verify the package was not installed in the project.

### Expected:

There is an error saying "Certificate chain validation failed with error: NotTimeValid." and the package was not installed in the project.

### Actual:

There is no error show and the package is installed in the project successfully as below screenshot.
![error tets](https://user-images.githubusercontent.com/20632775/34377073-46e1f65a-eb2a-11e7-9055-1cee978c125c.png)

**Comment by v-nancyj** [comment]
1. After the step3, verify the package use command :  NuGet.exe verify -signatures "PackageFilePath"
2. Verify the previous step failed with an error saying "Certificate chain validation failed with error: NotTimeValid."

But the actual error message is different from expected as belowscreenshot.
![111](https://user-images.githubusercontent.com/20632775/34377330-84ea7a84-eb2b-11e7-8db1-4734ce8a6cb7.png)

**Comment by rrelyea** [comment]
Spec discussion may make this not a bug. @rido-min ?

**Comment by dtivel** [comment]
@v-nancyj, the product behavior is correct.  The test case needs to be updated such that the expected result matches the actual result described above.

Note that there is a discrepancy between VS and "NuGet.exe verify" behavior with respect to verifying this signed package.  The default VS policy allows a package signed with an expired certificate and no steamp to be installed as an unsigned package.  "NuGet.exe verify" will report this signed package with an error.

CC @rido-min
