### ISSUE TITLE
SSDT & SSDT-BI Support

### ISSUE THREAD

**Issue by shawnallen85** [NuGet/Home#637]
Howdy, all!

I originally posted this in the NuGetGallery project, but I think it is a better fit here -- sorry about that ...

Would it be possible to add support for Database, SSRS, SSAS, and SSIS projects to NuGet?

For the Database project, you can deploy custom static code analysis assemblies to the project.

For the BI tools, it would be nice to manage templates, resources, etc., in a NuGet package that can be easily deployed to new and existing projects.

Thanks!!
Shawn

**Comment by yishaigalatzer** [comment]
We have been asked in the past about it, and we don't plan to add support in NuGet for this project type. We are ok with taking a pull request for it though if the team that owns this is willing to test it out.

We just enabled CPS based projects (without yet granular support) which enables any project type to opt into NuGet without any NuGet changes. If these projects move to CPS things will light up automatically once we enable the finegrained feature support.

**Comment by jamiekt** [comment]
Hi, What is a "CPS based project"?

**Comment by shawnallen85** [comment]
I'm assuming Common Project System.

**Comment by jamiekt** [comment]
Got it, thanks Shawn

**Comment by andyfenna** [comment]
when will this feature be picked up?

**Comment by yishaigalatzer** [comment]
No plans at the moment

**Comment by rohit21agrawal** [comment]
if this is still an important enough ask in VS2017, please open a separate issue

**Comment by Adam-S-Daniel** [comment]
@rohit21agrawal - This is still a very important issue, as evidenced by the ongoing comments on https://github.com/NuGet/Home/issues/545. What did you mean exactly by “a separate issue”? Just a new duplicate of this one?
