### ISSUE TITLE
PackageReference with Version ranges and wildcards

### ISSUE THREAD

**Issue by marceloavf** [NuGet/Home#6376]
Using **PackageReference** when we try to specify `Version="[1.3.2, 2)"`, it should get all the range close to version number 2, but, even if it has a `1.4.0` for example, it only get the `1.3.2`

It should get the `1.4.0`, not the `1.3.2`, right?

Only work if I say with the wildstar `1.*`

```
<PackageReference Include="jQuery" Version="[1.10.2,2)"/>
```
In the example above, jquery stay in `1.10.2`, doesn't try to go up.

---

NuGet product used: Visual Studio UI, Package manager and Dotnet

NuGet version: 4.4.1.4656 (I think)

dotnet.exe: 2.1.2

VS version: VS 2017 15.5.2

OS version: Windows 10 Pro 10.0.16299

**Comment by emgarten** [comment]
Restore takes the lowest version. Using a `*` is the correct way to float to a higher version.

You can also use an upper bound with a floating range:
`<PackageReference Include="jQuery" Version="[1.*, 2.0.0)"/>`

**Comment by marceloavf** [comment]
It'll always upgrade when a greater version in the same range appear? 
In order to get consistent installs across machines, there is some way to store exactly which versions of each dependency were installed ?

**Comment by emgarten** [comment]
It will upgrade each time you run a restore with `--force` or when restore needs to re-walk the dependency graph. 

Locking the version through source control is covered here: https://github.com/NuGet/Home/issues/4394

**Comment by Dietatko** [comment]
> Restore takes the lowest version. Using a `*` is the correct way to float to a higher version.
> 
> You can also use an upper bound with a floating range:
> `<PackageReference Include="jQuery" Version="[1.*, 2.0.0)"/>`

How can I specify "highest minor version but at least 1.2.3"?
"[1.*, 2)" would pick also version 1.1. But that does not include feature introduced in 1.2.
"[1.2.*, 2)" will not pick version 1.3.

**Comment by ilya-spv** [comment]
Would not just "1.2.*" work? If I understand it correctly you will get highest minor version which will for sure be above 1.2.3 if this version exists?

**Comment by Dietatko** [comment]
> Would not just "1.2.*" work? If I understand it correctly you will get highest minor version which will for sure be above 1.2.3 if this version exists?

This would not pick version 1.3 once available. So it is not the highest minor version but highest patch.
