### ISSUE TITLE
The Microsoft.Azure.CognitiveServices.Language nuget does not install in my main UWP app

### ISSUE THREAD

**Issue by ArchieCoder** [NuGet/Home#6377]
Hello,

I tried to install the Microsoft.Azure.CognitiveServices.Language nuget in my 1 year old UWP project. You can see the following video for the procedure: https://1drv.ms/v/s!Aj7hlcEeURZflqkGFh-OZiYCnu3A9g

The output is:

Restoring packages for E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\Kortext.Reader.Common\project.json...
Restoring packages for E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\DLReader (UniversalWindows)\project.json...
Committing restore...
Writing lock file to disk. Path: E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\Kortext.Reader.Common\project.lock.json
Restore completed in 557.1 ms for E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\Kortext.Reader.Common\Kortext.Reader.Common.csproj.
Successfully installed 'Microsoft.Azure.CognitiveServices.Language 1.0.0-preview' to Kortext.Reader.Common
Successfully installed 'Microsoft.Rest.ClientRuntime 2.3.10' to Kortext.Reader.Common
Successfully installed 'Microsoft.Rest.ClientRuntime.Azure 3.3.10' to Kortext.Reader.Common
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\DLReader (UniversalWindows)\project.lock.json
Restore completed in 13.93 ms for E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\DLReader (UniversalWindows)\Kortext.Reader.App.csproj.

NuGet Config files used:
    C:\Users\sebas\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.Fallback.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
Executing nuget actions took 412.29 ms
Committing restore...
Writing lock file to disk. Path: E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\DLReader (UniversalWindows)\project.lock.json
Restore completed in 629.97 ms for E:\Kortext\UWP\samples\DLReader\DL-Reader\DLReaderRT\DLReader (UniversalWindows)\Kortext.Reader.App.csproj.
Executing nuget actions took 103.75 ms
Time Elapsed: 00:00:01.9380341
========== Finished ==========

For some reasons, I am able to add the nuget in the Common project library, but at runtime, the dll is missing.

In a blank new UWP app, adding the nuget works and it works at runtime.

**Comment by zhili1208** [comment]
Could you provide more details? which dll is missing for which project at runtime? And please provide the project.lock.json file for that project. Thanks

**Comment by ArchieCoder** [comment]
Here is the project.lock.json of the main app (which the Nuget is not added correctly in the References)[project.lock.json.txt](https://github.com/NuGet/Home/files/1601702/project.lock.json.txt)

At runtime, I get this error: {System.IO.FileNotFoundException: Could not load file or assembly 'http://Microsoft.Azure .CognitiveServices.Language, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system...

**Comment by zhili1208** [comment]
From the Project.lock.json file, the dll is at Microsoft.Azure.CognitiveServices.Language\1.0.0-preview\lib\netstandard1.4\Microsoft.Azure.CognitiveServices.Language.dll @emgarten

**Comment by mishra14** [comment]
@ArchieCoder Please let us know if you are still facing this issue.
