### ISSUE TITLE
Suppress No-Op Restore messages in Visual Studio

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6384]
When a noop restore occurs in VS it currently writes out several messages to the status bar. This causes extra noise and makes it appear as though work is happening. VS should instead suppress these messages unless a real restore is happening.

Example scenarios where noop restores happen often:
1. Changing between Debug -> Release
1. Running tests with test explorer

**Comment by mishra14** [comment]
cc : @nkolev92

**Comment by nkolev92** [comment]
Done as a side-effect of https://github.com/NuGet/Home/blob/dev/designs/VisualStudio-PartialRestoreOptimization.md and https://github.com/NuGet/Home/issues/9513. 

The reporting now happens on the 1st restore. Every subsequent no-op *does not* report on the status bar.
