### ISSUE TITLE
Need to integrate calls to Metric Service into client installs

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#639]
As we install packages directly from storage/cdn we need to track install metrics by some other mechanism.

A "best effort" call to the Metric Service is one such mechanism.

(Alternatively we can have the client always attempt to download from a service we run where by we redirect the request to storage/cdn. And we record the redirects. However the availability of this service then becomes an issue. Though that can be mitigated by having multiple download locations in root index.json. This would, however, require the client understanding the need to roll over to an alternative download location.)

**Comment by johnataylor** [comment]
The client should also support reporting FAILED install attempts to the service. This way we can be proactive about addressing potential problems in package resolution. Given the complexity of the more recent package dependency graphs and the fact that we have a lot of new code such a reporting mechanism might be very useful.

**Comment by yishaigalatzer** [comment]
We want to separate this into two issues

1. Need a way to track download counts on V3 - Lets first explore getting CDN logs as input, and as a secondary have a compute end point that does redirects to storage. We would really like to avoid compute if possible.

2. Need an end point and client behavior to report failed installs, we need to discuss this one in details to make sure we are ok tracking this and that we are not exposing personal user data.

@csharpfritz can you take on `#2` with the legal folks, while @xavierdecoster handels `#1`

**Comment by yishaigalatzer** [comment]
We are not making changes in the client, @xavierdecoster I'm assuming we have another bug to track the data from CDN. @csharpfritz we still need legal chat to figure out if we can capture failed installed

**Comment by xavierdecoster** [comment]
Issue https://github.com/NuGet/NuGetGallery/issues/2416 tracks the task to collect data from the CDN.

**Comment by csharpfritz** [comment]
Email sent to LCA to discuss options

**Comment by xavierdecoster** [comment]
Successful downloads are reported in the CDN raw logs and tracked by another GitHub issue (https://github.com/NuGet/NuGetGallery/issues/2416). 
Assigning this issue to @csharpfritz who can update/reassign based on the LCA-status/requirements for tracking failed installs.

**Comment by csharpfritz** [comment]
What information do we want to collect from a failed install in addition to the standard HTTP headers that are sent?

**Comment by yishaigalatzer** [comment]
The idea is to send back an extra call if installed has failed. Some sort of a full post describing the project tfms and other dependencies

Sent from my Windows Phone

**Comment by csharpfritz** [comment]
Agreed - lets get some scope around the specific items we want to send on
this follow-up "troubleshooting" post so that we can discuss any privacy
concerns.  We may need to add an 'opt-in' option to facilitate this type of
troubleshooting.

Are we considering sending back: packages.config/project.json, project type
guid, and nuget.config?

**Comment by yishaigalatzer** [comment]
Yeah. This is low pri vnext kind of thing right now. Lets move it out and get into it again after u2

**Comment by csharpfritz** [comment]
Yes, lets push install failure reporting out as it will require client
updates to support it.

**Comment by harikmenon** [comment]
Parented this to the telemetry epic and added the install failure to my spec to track. @rrelyea - assigning it back to you at this time to reassign to an engineer.

**Comment by yishaigalatzer** [comment]
This issue is not ready to be assigned. We already track download by CDN, but tracking failed installed needs a lot more thought and design, and I don't see us doing it in 3.5-RC.

Moving out to Future
