### ISSUE TITLE
I suggest that you could specify a repository from where nuget.exe should update from

### ISSUE THREAD

**Issue by gordonAndersen** [NuGet/Home#6392]
I suggest that you could specify a repository from where nuget.exe should update from. E.g. nuget update -self -repository my.corperate.server
It wold then be easier for a company to control the version of the nuget.exe version and also no need to open for the firewall - when you already only use a local nuget repository.

**Comment by nkolev92** [comment]
Thanks for filing this issue. 
We understand you concern, but we also need to consider the fact that "update -self" should never update to a non-Microsoft NuGet release. Allowing "any" source there introduces that risk. 

We will triage this appropriate and come back to this issue.

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Home/issues/1783
