### ISSUE TITLE
dotnet-nuget install (reopening #6375)

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#6394]
I believe #6375 is NOT a duplicate of ##5919 as @zhili1208 mentioned.

Request is to simply add `install` to `dotnet-nuget`.

This works today:

```
dotnet nuget push -s <my-registry-endpoint> my-package.nupkg
```

we need `dotnet nuget install` command:

```
dotnet nuget install -s <my-registry-endpoint> my-package
```

similar to:

```
nuget install -Source <my-registry-endpoint> my-package
```

with explicit source, even without requiring to have NuGet.Config.

**Comment by emgarten** [comment]
@kasper3 can you explain how this is different from https://github.com/NuGet/Home/issues/5919?

https://github.com/NuGet/Home/issues/5919 covers adding support download packages outside of a project, the same thing `nuget.exe install` does.
