### ISSUE TITLE
nuget update can't update project when there are multiple project files in a folder

### ISSUE THREAD

**Issue by nirbar** [NuGet/Home#6396]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.4.1.4656

OS version: Windows 7

## Detailed repro steps so we can see the same problem

1. Create a folder with two or more project files and a single packages.config
1. Execute nuget.exe update packagesconfig

- *Result*: Found multiple project files for '...\packages.config'
- *Expected*: Support command line flag to specify which project file to update

**Comment by nkolev92** [comment]
This is not a supported scenario for NuGet 4.4.1.
Your options here are either define a project-level packages.config and manage each project's packages independently, or try some tricks where you update the packages.config for 1 project, and then just copy the updated references into the other one.
