### ISSUE TITLE
Breaking public API in minor version updates of NuGet API causes runtime errors and/or compilation errors

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#6398]
Between 4.5.0 and 4.6.0-rtm-4789, some public API has been removed from NuGet's assemblies. This binary incompatibility is causing failures in @aspnet's build tools and infrastructure as we try to upgrade to new versions of the .NET Core SDK.

Examples:
 - https://github.com/NuGet/NuGet.Client/commit/8bc20a92f97b5007b8cb80b2e4285da7c7a63a03 - removed `NuGet.Protocol.Core.Types.MetadataResource.Exists(string, ILogger, CancellationToken)` and `GetVersions(string, bool, bool, SourceCacheContext, ILogger, CancellationToken)` cc @jainaashish 
 - https://github.com/NuGet/NuGet.Client/commit/e91dbf3ec37f60f902079bafd001c1173bfb5c25 - removed `NuGet.Packaging.VersionFolderPathContext` cc @zhili1208 

This causes `MissingMethodException` at runtime in our tools that depend on NuGet's public APIs, and compilation errors when upgrading our source code.

Questions:
 - Were these changes intentional? Or just missed during review?

If intentional....
 - Could API be marked `Obsolete` before complete removal to give users a heads up? This prevents `MissingMethodException` at runtime and other errors.
 - If a user is not supposed to be using these types, how would they know? They are public, shipped on NuGet.org, and documented API.
 
cc @emgarten 
FYI - @ryanbrandenburg

**Comment by muratg** [comment]
👀

**Comment by nkolev92** [comment]
The only APIs that we "officially" publicly support are the IVs ones. 

What kind of documentation are you referring to about the above APIs? 
These are more dynamic and have evolved as we see fit. 

We'll discuss and get back to you on this.

**Comment by natemcmaster** [comment]
Another example. https://github.com/NuGet/NuGet.Client/pull/2043 

Just so you know what this means to us...everytime there is a breaking change, it typically takes a few hours to investigate and discover the issue because NuGet is effectively a global singleton between VS and MSBuild. It takes time to dig down the layers of dependencies to figure out what version of NuGet is bundled in MSBuild, to then find matching packages, and to re-compile all MSBuild tools for the new API. It also means we cannot write MSBuild tasks that will work across multiple versions of the .NET Core SDK.

**Comment by muratg** [comment]
cc @rrelyea FYI

**Comment by natemcmaster** [comment]
Ran into this again. Breaking changes between 4.7.0 and 4.9.0-preview3.5473 were made on constructors on `PackageSignatureVerifier` and `PackageExtractionContext`.

**Comment by PatoBeltran** [comment]
Hey @natemcmaster, we since then updated the `PackageExtractorContext` and you also won't need to create your own `PackageSignatureVerifier` anymore. This changes will be released in 4.9.0-preview5 so I would advice to wait a couple of days for this change to update versions

**Comment by natemcmaster** [comment]
I had to merge changes to aspnet's buildtools with 4.9-preview3 so we could unblock other 3.0 work. When you get around to inserting preview5 into the .NET Core 3.0 SDK, I'll react accordingly. Thanks for the heads up.

**Comment by zivkan** [comment]
The APIs listed in this issue were broken such a long time ago, that there's no benefit to bringing them back, so I'm closing this issue.

For what it's worth, we're now using Roslyn's PublicApiAnalyzers, and I try to catch changes to public APIs and I've significantly raised awareness of breaking API changes within the team, so this should be much less likely.
