### ISSUE TITLE
Exclude feature doesn't work when using PackageReferences and .NetStandard

### ISSUE THREAD

**Issue by JKennedy24** [NuGet/Home#6399]
I am trying to use the `Exclude` feature outlined here: https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution#excluding-references

I have a .Net standard 1.4 library and a UWP project.

I have added a nuget package to my UWP project using the `PackageReference` technique and added the `Exclude="All"` flag to my packagereference but the libraries are still included and causing a build conflict.

The following Package reference format does not work:

`<PackageReference Include="PackageC" Version="1.0.0" Exclude="All" />`

**Comment by rohit21agrawal** [comment]
use ExcludeAssets instead of Exclude

**Comment by nkolev92** [comment]
As @rohit21agrawal pointed out. There's a mistake in the docs. 

I've already filed a PR to get that fixed. 
https://github.com/NuGet/docs.microsoft.com-nuget/pull/641

The correct usage is shown here:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

Apologies for the inconvenience again.

**Comment by JKennedy24** [comment]
Thanks.

Using `ExcludeAssets` worked. Hopefully get that PR merged soon
