### ISSUE TITLE
VS 2017 "Error in type" when opening nuget console

### ISSUE THREAD

**Issue by Ro3A** [NuGet/Home#6400]
Opened Nuget console today to run a command and got the following:

![image](https://user-images.githubusercontent.com/19931334/34692108-f25883f8-f48c-11e7-9e56-524da2e5b3d9.png)

I'm using VS 2017 on Windows 10. Have not had any issues with nuget in the past and I've been away from the computer for a couple days over the holidays and thus have not installed anything or otherwise changed my development environment.

It looks like it was a windows update that may be the root cause but this seemed like a decent place to post this issue. 

Any ideas on the root cause here and if a fix is in progress?

**Comment by nkolev92** [comment]
What's the command you are trying to run here?

NuGet just bootstraps powershell here, nothing fancy. Later we just add our powershell command module. 

Can you please check if your powershell version has been upgraded?

For example mine is:
```
PM> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1944    
```

**Comment by Ro3A** [comment]
I wasn't trying to run a command. I opened the Nuget console from the tools menu in VS 2017 and while it was initializing, I got that message. From there, I'm unable to even type in the console. 

My version is 
![image](https://user-images.githubusercontent.com/19931334/34723868-f7a63a8e-f519-11e7-900e-398b4287a22c.png)

  I also wanted to leave this here. Others are having the same issue:
https://developercommunity.visualstudio.com/content/problem/161123/windows-update-broke-nuget-package-manager-in-vs20.html?childToView=178652#comment-178652

https://developercommunity.visualstudio.com/content/problem/35803/help-error-the-package-manager-console-requires-po.html

**Comment by Ro3A** [comment]
@nkolev92 Have you had a chance to review my comments above? Any thoughts?

I've tried implementing the binary version redirect work around and got no error message, but the console was stuck on loading / initializing.

**Comment by nkolev92** [comment]
I've done some looking around. 

Since it's not a NuGet issue, there isn't much we cna do here, but I found the following blog that might of some help to you. 

https://joshuachini.com/2017/07/13/visual-studio-package-manager-console-fails-to-start/

**Comment by nkolev92** [comment]
I've also found the following:

https://docs.microsoft.com/en-us/nuget/release-notes/Known-Issues#opening-package-manager-console-fails-with-objectsecurity-exception

Please attempt the solutions provided in the links.

**Comment by Ro3A** [comment]
I've seen both of those as well. No luck. I'm concerned too that some of these articles regarding this specific error have been around for quite so me time. 

Can you refer me to the right team?

**Comment by nkolev92** [comment]
You can reach out to the powershell team, [here](https://github.com/powershell/powershell). They should be able to help route you further if needed.
