### ISSUE TITLE
RestoreSources are not used for cli tool references

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6402]
_From @firelizzard18 on January 7, 2018 4:23_

I have a project, `dotnet-mycmd`. I want to use this as a tool in another project via `DotNetCliToolReference`. I've exported a nupkg to a folder and added that folder to the target project's `RestoreSources`. I then added the tool reference and attempted to `dotnet restore`.

This succeeds when the project is named something like `mycmd` but fails in all sorts of ways when its named `dotnet-mycmd`. And of course it doesn't work as a tool when the name isn't prefixed with `dotnet-`.

In my reproduction ([test.zip](https://github.com/dotnet/cli/files/1609495/test.zip)):
  * A is a netstandard lib
  * A2 is a netstandard lib dependent on A
  * B/dotnet-mycmd is a netcoreapp dependent on A and A2
  * C is a netstandard lib dependent on A with a tool reference to B/dotnet-mycmd

Currently, I'm getting these errors (in my reproduction attempt):
```
% dotnet restore C
  Restoring packages for /Users/me/Source/test/C/C.csproj...
  Restore completed in 10.04 ms for /Users/me/Source/test/A/A.csproj.
  Restore completed in 22.78 ms for /Users/me/Source/test/C/C.csproj.
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package dotnet-mycmd. No packages exist with this id in source(s): nuget.org
/usr/local/share/dotnet/sdk/2.1.3/NuGet.targets(103,5): error : Value cannot be null. [/Users/me/Source/test/C/C.csproj]
/usr/local/share/dotnet/sdk/2.1.3/NuGet.targets(103,5): error : Parameter name: path [/Users/me/Source/test/C/C.csproj]
```

These are the errors I was getting before I tried to reproduce the issue, translated into the projects I created for the reproduction:
```
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package A. No packages exist with this id in source(s): nuget.org
/Users/me/Source/test/C/C.csproj : error NU1101: Unable to find package A2. No packages exist with this id in source(s): nuget.org
```

_Copied from original issue: dotnet/cli#8342_

**Comment by emgarten** [comment]
I was able to repro this. It looks like RestoreSources are not being used for tools when restoring with msbuild or dotnet.exe. From nuget.exe however this works fine.

There is also an issue where an unresolved tool causes a NRE here https://github.com/NuGet/NuGet.Client/blob/b43eff20b7392c373f57d6b4ad6f50f1ba816217/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreCommand.cs#L282

**Comment by nkolev92** [comment]
VSTS bug [543484](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/543484) might be hitting the NRE you describe here.

**Comment by PatoBeltran** [comment]
This has been solved as part of the latest rework on the nuget.configuration code paths.

**Comment by nkolev92** [comment]
This looks like it should've been fixed before this issue was reported (maybe the version used did not contain this change)
https://github.com/NuGet/NuGet.Client/pull/1403

Regardless, @PatoBeltran took a look at and it's seems good :)

**Comment by Mpdreamz** [comment]
Still hitting this on my machine:

```
C:\Projects\elastic\AssemblyRewriter>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.400
 Commit:    8642e60a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.400\

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  1.1.10 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
