### ISSUE TITLE
Nuget credential provider crashed after user login with uncaught "CannotUnloadAppDomainException" error

### ISSUE THREAD

**Issue by fernisoites** [NuGet/Home#6405]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (4.4.1.465):

OS version (win10 v1709 (16299.125)):

## Detailed repro steps so we can see the same problem

1.Download credential provider from 
 url: "https://nuget.org/api/v2/"
 package:"Microsoft.VisualStudio.Services.NuGet.CredentialProvider"
 exe: "CredentialProvider.VSS.exe"

2.Open command line prompt, run:
CredentialProvider.VSS.exe -Uri https://ossmsft.pkgs.visualstudio.com/DefaultCollection/_apis/packaging/OSS_All/nuget/index.json

This command prompted interactive user logon window, after typed in username and password the window disappeared. But Credential provider crashed afterwards "Microsoft Visual Studio Team Services Credential Provider for Nuget has stopped working", here is error message:
"
Unhandled Exception: System.CannotUnloadAppDomainException: Error while unloading appdomain. (Exception from HRESULT: 0x80131015)
   at System.AppDomain.Unload(AppDomain domain)
   at Microsoft.VS.Services.NuGet.CommonLoader.AssemblyLoader.OuterMain(String[] args)
   at Microsoft.VS.Services.NuGet.CommonLoader.AssemblyLoader.Main(String[] args)
"

**Comment by nkolev92** [comment]
This is not a NuGet issue, but rather a VSTS one. 

I have created an issue on VSTS side. 

https://developercommunity.visualstudio.com/content/problem/179458/nuget-credential-provider-crashed-after-user-login.html

Please follow that issue and make sure to say hi in the issue, so you provide them further details as they need it. 

Thanks.

**Comment by fernisoites** [comment]
Thanks
