### ISSUE TITLE
[Perf] [VSTS] NuGet restore slower on Windows agents than on Linux agents

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6406]
[Twitter thread](https://twitter.com/willia4/status/950168052703875072) that states most of the *free* build time on VSTS is consumed in NuGet restore.

This lead to a generic problem that's been observed where restores have been faster on Linux agents than on Windows agaents. Details:

[VSTS build stats dashboard](https://chrispatmsft.visualstudio.com/yaml-samples/yaml-samples%20Team/_dashboards/dashboard/20ab77a1-3df5-4878-b896-0c28ac0698c1?teamid=yaml-samples%20Team)

Summarizing below what I could see in the build steps. Note the relative difference between build on Windows vs. Build on restore as well as the absolute numbers.

  | Linux   - Build | Linux   - Restore | Win   - Build | Win   - Restore
-- | -- | -- | -- | --
Dotnet-no-sdk-download | 25 | 23 | 89 | **168**
dotnet-sdkdownload-no-first-time | 19 | 39 | 14 | **104**
dotnet-sdkdownload-with-first-time | 186 | 58 | 11 | **62**

\* *Time in secs*
\* *Looking at latest builds*

**Comment by dtivel** [comment]
Possibly fixed by https://github.com/NuGet/NuGet.Client/pull/2488.

**Comment by dtivel** [comment]
Resolved by https://github.com/NuGet/NuGet.Client/pull/2488.
