### ISSUE TITLE
Nuspec Replacement tokens don't have values.

### ISSUE THREAD

**Issue by kabua** [NuGet/Home#6407]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.4.xxx

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.5.2

OS version (i.e. win10 v1607 (14393.321)):win10

Worked before? If so, with which NuGet version: nuget.exe

## Detailed repro steps so we can see the same problem

Create Directory.Build.Props:
```
<Project>
  <PropertyGroup>
	<NuspecFile>my.nuspec</NuspecFile>
  </PropertyGroup>
</Project>
```

Create my.nuspec in same folder as the Directory.Build.Props
```
<?xml version="1.0"?>
<package >
    <metadata>
        <id>$id$</id>
        <version>$version$</version>
        <title>$title$</title>
        <authors>$author$</authors>
        <owners>$author$</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>$description$</description>
        <releaseNotes></releaseNotes>
        <copyright>Copyright 2017</copyright>
    </metadata>
    <files>
        <file src="bin\$Configuration$\my.dll" target="Lib" />
    </files>
</package>
```
Run `msbuild "my-solution.sln" /t:clean,build,pack /m /p:Configuration=Debug`

## Results
None of the `$xxx$` have values.

For example: if I replace all the __tokens__ with actual values except for `$Configuration$` and I run `msbuild`. Then I get an error stating can't find file. The search path is: `bin\\my.dll` Note that `$Configuration$` resolves to an empty string. Thus I assume all the other __tokens__ resolve to empty strings as well.

**Comment by nkolev92** [comment]
msbuild/dotnet pack works a bit differently from the old nuget.exe nuspec pack. 

In nuget.exe you can pack a nuspec, with msbuild you have to have a project. 
Which means when you run the above command, it'll call the pack target on each compatible project in the solution. 

Each project should point to a nuspec and the way to provide the token values is to use the NuspecProperties property, as described here: 
https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets#packing-using-a-nuspec

We pack projects, so we'd need to see the project files or at least make sure that the nuspec properties are being passed. 

Once you've double check that there isn't any issues with the above, please try again. 

If you're still having issues after that, we'd really appreciate if you can create a small repro solution and zip it up for us to test. 

Lastly, I'd recommend running the command without the /m flag, to see if there's any difference in the output.

**Comment by nkolev92** [comment]
At this point, we don't have enough information to continue the investigation of this issue.

Please do let us know if you face further problems, by opening a new issue.
