### ISSUE TITLE
Nuget repository has packages with virus!

### ISSUE THREAD

**Issue by rpringadi** [NuGet/Home#641]
A virus was detected on one of the package that was downloaded using nuget.exe.
https://nuget.codeplex.com/workitem/8328 

https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=nuget&WorkItemId=8328&FileAttachmentId=1458680

**Comment by yishaigalatzer** [comment]
Where did you download the package from? What is the package id?

**Comment by rpringadi** [comment]
I don't know which package, since I downloaded so many of them. I downloaded them using nuget.exe

If you work or have access to the repository itself try finding this "Worm.Attachments.dll"
As seen in the picture.

**Comment by maartenba** [comment]
Seems to be this one http://www.nuget.org/packages/Worm/. I just ran all files from this package through a variety of virus scanners using www.virustotal.com, only AVG seems to mark this file as "infected": https://www.virustotal.com/nl/file/4393327c929502b54c34cd97aed0b5ffb6fe05de58e7801ac1b9076cf5da771c/analysis/1432646514/

This may be a false positive, although we'll have to investigate to make sure.

**Comment by blowdart** [comment]
Maarten can you reach out to the package author and let him know?

**Comment by maartenba** [comment]
@blowdart Done. Is there a way of getting a proper scan of this package?

**Comment by blowdart** [comment]
You've pretty much done what I would. We have an internal site that runs through multiple scanners, but virustotal actually has more :)

**Comment by yishaigalatzer** [comment]
@maartenba please verify if this is indeed a virus or not and update the bug.

As far as we can tell it is not a Virus as far as we know.

**Comment by maartenba** [comment]
Our internal scanning service marked this package as safe, closing the issue.
