### ISSUE TITLE
setapikey results in prompt for username/password (key ignored)

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#6415]
Ubuntu 16.04 LTS w/latest updates, running on Mono... (yeah, I know)
```
NuGet.exe
NuGet Version: 4.4.1.4656
```

Add Artifactory and set API key:
```
nuget sources add -Name Artifactory -Source https://[company].jfrog.io/[company]/api/nuget/nuget-local
nuget setapikey [username]:[api-key] -Source Artifactory
cat /home/vagrant/.config/NuGet/NuGet.Config
[snip -- it's there]
```

Try to restore packages:
```
nuget restore
Please provide credentials for: https://[company].jfrog.io/[company]/api/nuget/nuget-local
UserName: [username]
Password: *******
GET
OK
```

...have to do this every time. Of course, if I set it up this way:

```
nuget sources add -Name Artifactory -Source https://[company].jfrog.io/[company]/api/nuget/nuget-local -username [username] -password [*******] -StorePasswordInClearText -configfile /home/vagrant/.config/NuGet/NuGet.Config
```

then it works, but that is not ideal.

**Comment by nkolev92** [comment]
Thanks for filing this issue. 

The API key is not used to authorize when reading a feed, it's only used for push. 

Related comment here:
https://github.com/NuGet/Home/issues/3664#issuecomment-355099555

**Comment by emgarten** [comment]
@nkolev92 is correct, you need to add the username/password to nuget.org for the source.
