### ISSUE TITLE
stabilize apex tests and prevent failures and hang and reduce run duration

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6416]
Apex tests are failing very often either due to crashing, hanging or false assertions.

They are also taking a long time to run since each tests opens its own instance of visual studio.

**Comment by emgarten** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/commit/c6a91da2f8b0dd13bb73b238ff9a8b66bd86c844
