### ISSUE TITLE
Command line client hangs if publish feed is password-protected and credential in nuget.config is incorrect

### ISSUE THREAD

**Issue by stefann42** [NuGet/Home#642]
Expected: an error message should be displayed saying credentials are incorrect. I watched the transaction with Fiddler, NuGet server responds with 401 Status Code and command line client hangs waiting for..., not sure for what.

**Comment by yishaigalatzer** [comment]
Can you provide as with more info, like the version of nuget.exe you are using, what server are you trying to push to?

**Comment by stefann42** [comment]
Using command line version 2.8.60318.667 and server version 2.8.60318.667 deployed according to these instructions http://docs.nuget.org/create/hosting-your-own-nuget-feeds password protected with Basic Authentication over SSL.

**Comment by yishaigalatzer** [comment]
@stefann42 please try nuget command line 3.3 for this scenario. - Available on myget.org/nugetbuild (or in a few days publicly of dist.nuget.org)

**Comment by yishaigalatzer** [comment]
@stefann42 are you still able to repro this issue? This is something we definitely test for and know works, so please let us know if you see a repro with 3.3 and we can re-open

**Comment by stefann42** [comment]
Sorry, I don't have the time to recreate the test setup to verify. If you fixed it and test for it by all means it should be closed.
