### ISSUE TITLE
Improve VS error experience for signed packages

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6427]
@rido-min will work on the spec.
@emgarten  will work with @rido-min to get the feasible changes into product.

**Comment by mishra14** [comment]
Known issues - 
https://github.com/NuGet/Home/issues/6337
https://github.com/NuGet/Home/issues/6411

**Comment by emgarten** [comment]
Moving to 4.7 after an offline discussion with @rido-min, this is still important to fix but it is likely not something users will hit right away in 4.6.
