### ISSUE TITLE
No Error message when installing a tampered package with NuGet.exe

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6433]
Create a project  and add a reference to a known package. 

Sign that package, and modify it's contents.

`nuget verify -signature MyPackage.nupkg` should show NU3008 error.

Running `nuget restore` fails, however there is no error message or warning, while VS shows the NU3008 Error.

Sample output (for PR and PC projects)

```
Restoring NuGet package MyPackage.1.0.0.
Adding package 'MyPackage.1.0.0' to folder 'C:\code\NuGet.TestNPS\packages'
WARNING:

Errors in packages.config projects
```

**Comment by mishra14** [comment]
@zhili1208 is this expected?

**Comment by zhili1208** [comment]
NO, this is not expected, looks like a bug
