### ISSUE TITLE
Nuget wiki still contains project.json upgrade recommendations when project.json is currently deprecated.

### ISSUE THREAD

**Issue by ericnewton76** [NuGet/Home#6436]
These wiki pages need substantial rethink to evaluate their correctness now that project.json itself is deprecated:

- https://github.com/NuGet/Home/wiki/NuGet-Upgrader.-Helping-to-move-to-NuGet-3.0
- https://github.com/NuGet/Home/wiki/Converting-a-csproj-from-package.config-to-project.json

**Comment by emgarten** [comment]
@ericnewton76 use https://docs.microsoft.com/en-us/nuget/ for official documentation. 

The NuGet wiki contains development specs that are often in progress or out of date.

**Comment by PatoBeltran** [comment]
Closing this issue as the wiki is not intended to be used as documentation.
