### ISSUE TITLE
VS2015 RC: Install-Package hangs

### ISSUE THREAD

**Issue by nul800sebastiaan** [NuGet/Home#644]
Tried installing the UmbracoCms package using NuGet `3.0.60410.213`:
File > New Project > .NET Framework 4.5 > ASP.NET Web Application > Empty (using ASP.NET 4.6 Templates)

```
Package Manager Console Host Version 3.0.0.0

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package UmbracoCms
Attempting to gather dependencies information for package 'UmbracoCms.7.2.5' with respect to project targeting '.NETFramework, Version=v4.5'
Attempting to resolve dependencies for package 'UmbracoCms.7.2.5' with DependencyBehavior 'Lowest'
```

The "Attempting to resolve" message then just stays there and nothing else happens (waited about 10 minutes).

I tried disabling the v3 feed as a source and using the default `https://www.nuget.org/api/v2/` but that resulted in an error: `Install-Package : Could not connect to the feed specified at 'https://www.nuget.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.`

This used to work fine in an older NuGet version (`3.0.51210.242`), see: [https://tndhuy.wordpress.com/2015/05/14/solved-nuget-package-management-problem-in-visual-studio-2015-rc/](https://tndhuy.wordpress.com/2015/05/14/solved-nuget-package-management-problem-in-visual-studio-2015-rc/)

Let me know how I can help debug or if you need more steps to reproduce this problem.

**Comment by maartenba** [comment]
This was caused by an issue on www.nuget.org. It should be resolved right now. Feel free to respond to this issue in case you are still seeing issues.

**Comment by nul800sebastiaan** [comment]
Thanks @maartenba - did you mean that the issue was solved yesterday just before you posted this reply? 
Currently, I can't even manage to get to the `Attempting to resolve dependencies` any more now, I only see `Attempting to gather dependencies` and then after a looong wait (10+ minutes) I get the following error when using the `api.nuget.org` feed:
```
Install-Package : Exception of type 'System.OutOfMemoryException' was thrown.
At line:1 char:1
+ Install-Package UmbracoCms
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
``` 
Using the v2 feed, VS15 just crashes about a minute after showing `Attempting to resolve dependencies`.

**Comment by maartenba** [comment]
That sounds like it may have a different cause. Is this on every package or just this one?

**Comment by nul800sebastiaan** [comment]
Seems to be just Umbraco, NewtonSoft.Json works great immediately. I've suspended ReSharper just in case that was causing issues (it has before) but no luck there.
We do have a lot of dependencies in the UmbracoCms.Core project, they may cause issues with the new version of NuGet? 
See: https://www.nuget.org/packages/UmbracoCms.Core/

**Comment by nul800sebastiaan** [comment]
As an update: I tried installing each of the dependencies individually, VS15 seems to crash when installing AutoMapper (3.0.0 and 3.3.1).  
I'll try again on a different PC to see if I can install Umbraco and Automapper there.

**Comment by tstahnke** [comment]
I also saw visual studio crashing when trying to install automapper. I had to do a devenv.exe /ResetSettings to resolve that issue.

Then, I was able to install Umbraco 7.2.5 in VS2015 RC with the new nuget by following this order of package installation. From what I gathered while banging it out, there is a circular dependency that conflicts when installing MVC with dependency resolution.

newtonsoft.json 6.0.8
microsoft.aspnet.webapi 5.2.3
automapper 3.3.1
microsoft.aspnet.mvc 5.2.3
microsoft.aspnet.mvc.fixeddisplaymodes 5.0.0 - must be done second otherwise it wants mvc 6.0
microsoft.net.http 2.2.29
miniprofiler 2.1.0
htmlagilitypack 1.4.9
lucene.net 2.9.4.1
xmlrpcnet 2.5.0
clientdependency 1.8.3.1
clientdependency-mvc 1.8.0.0
examine 0.1.63.0
imageprocessor.web 4.3.1
umbracocms.core 7.2.5

**Comment by nul800sebastiaan** [comment]
@tstahnke That's just insane, we already list all of the dependencies, you shouldn't have to install them manually first.

**Comment by tstahnke** [comment]
Yeah, I think that was required when nuget had the bug earlier. It's no longer needed to install it in that order, but I felt it might be helpful for reference if there is still some kind of dependency resolution bug somewhere.

**Comment by tstahnke** [comment]
Something interesting too: If you install automapper using the v2 api, and then try to install umbracocms.core, that resolves dependencies _instantly_. If you try to install umbracocms on the other hand without installing umbracocms.core, then it hangs.

**Comment by nul800sebastiaan** [comment]
I REALLY want to help debug this problem but I need pointers on where to start, how can I get more helpful debugging info, logging, etc.?

**Comment by nul800sebastiaan** [comment]
@maartenba This is also reproducible by multiple members in the Umbraco community, could we re-open this and investigate please?

**Comment by maartenba** [comment]
@yishaigalatzer This may be a V3 client issue after all.

**Comment by yishaigalatzer** [comment]
Can you provide clear repro steps with nuget 3.0 rc2 as well as a crash dump?

**Comment by nul800sebastiaan** [comment]
Okay, with `3.0.60602.486` (RC2) this issue is actually resolved! Sorry, don't mean to be the boy who cried wolf. ;-)

**Comment by thalseth** [comment]
Thank you guys!
[Download NuGet 3.0 RC2] (https://nuget.codeplex.com/downloads/get/1459895)

**Comment by saurabha5** [comment]
Updating Nuget Package extension from "Tools -> Extensions and Updates" worked
