### ISSUE TITLE
Restore fails for AutoMapper when project is netcoreapp2.0

### ISSUE THREAD

**Issue by rgamage** [NuGet/Home#6445]
The Restore step fails in my build definition with this error:

error NU1100: Unable to resolve 'AutoMapper (>= 6.2.2)' for '.NETCoreApp,Version=v2.0'.

This is in a .NETCoreApp 2.0 that is using AutoMapper. Restore succeeds locally in VS 2017. Locally I am using dotnet sdk 2.0.0, and nuget 4.3.1. On the VSTS (cloud) server, I am specifying the latest nuget version, 4.5.0. I have tried many other versions, including 4.3.1 with no success.

I know there is an older, similar question on stackoverflow, but that was never answered satisfactorily, in my opinion.

If I look at the meta data in VS, at the top of one of the Automapper files I can see this:

Assembly AutoMapper, Version=6.2.2.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005
// C:\Users\randyg.nuget\packages\automapper\6.2.2\lib\netstandard1.3\AutoMapper.dll

From this you can see it's taking the netstandard1.3 version, which is correct. I'm wondering if the nuget on the build server is looking for a netcoreApp2.0 folder, rather than the netstandard1.3 folder? Following this theory, I tried adding this to my .csproj file:

<AssetTargetFallback>$(AssetTargetFallback);netstandard1.3</AssetTargetFallback>
My theory was this would tell nuget to look for a netstandard1.3 version of automapper if it couldn't find a netcoreapp2.0 version. However, this didn't have any effect. I later read that behind the scenes this fallback is already added automatically.

If anyone has any ideas I would greatly appreciate it. I'm pulling out (what's left of) my hair on this, as this is the only package giving me trouble, and it's a critical one for my project.

On the build server I'm using .NET Core sdk 2.0.3 as well, if that matters.

Update - I just tried adding a new project to my solution, with a target of netstandard1.3, then adding AutoMapper as a dependency. Restore is now working on the build server for this project. So it seems the problem is specific to having a project with target = netcoreapp2.0??

**Comment by emgarten** [comment]
`NU1100` can occur if you do not have any sources, it means that the package wasn't found or is corrupt in your global packages folder in a way that can't be fixed normally. The assemblies in the package would not give you this error, those are not read until build.

**Comment by rgamage** [comment]
emgarten - I tried checking the box that clears the package cache, with no change in behavior.  Also as mentioned in my update, if my project type is netstandard1.3, there are no problems.  I don't think the problem is a missing source or corrupt package.

**Comment by emgarten** [comment]
@rgamage can you provide a simple repro project for this?

You can also take a look at the code here: https://github.com/NuGet/NuGet.Client/blob/9c1502ee06d60ff9d8b0c9f5477b95ffed45b8cc/src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnresolvedMessages.cs#L114-L122  which may help you determine the cause. In general NU1100 is a generic error displayed when there is no normal cause that can be found, usually something is corrupt.
