### ISSUE TITLE
nuget.server: pushing symbol.nupkg package not adding package to repository

### ISSUE THREAD

**Issue by luisabreu** [NuGet/Home#6446]
## Details about Problem
Nuget.server: 3.0.2

## Detailed repro steps so we can see the same problem

1. Create new web app
2. Add nuget.server packages
3. Create IIS web site
4. Set the ignoreSymbolsPackages flag to false in web.config
5. Configure new source
6. push symbols.nupkg package with nuget push mypackage.symbols.nupkg -source https://mysite/nuget

Even though the cmd says that the package was pushed, the truth is that it's not listed in the feed (nor is it added to the packages folder).

**Comment by PatoBeltran** [comment]
@joelverhagen could you please take a look at this nuget.server issue?

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #5289](https://github.com/NuGet/NuGetGallery/issues/5289) via [**ZenHub**](https://www.zenhub.com/)
