### ISSUE TITLE
How to create a package supporting multiple runtimes for Donet Classic?

### ISSUE THREAD

**Issue by akordowski** [NuGet/Home#6452]
The goal is to create a NuGet package for Dotnet Classic dlls (net20, net40, net45, etc) which supports runtimes for x86 and x64. No UWP, NetStandard or NetCore.

The examples in the docs with the `runtimes` folder doesn't work. I even can't install the package (VS 2015 and VS 2017). The combination with the `lib` and `build` folder don't work either. I spend hours to figure it out but don't found any solution. Help is highly appreciated.

**Comment by PatoBeltran** [comment]
@emgarten could you please take a look at this issue

**Comment by emgarten** [comment]
Use the `ref/` and `runtimes/` folders for PackageReference projects. For packages.config projects you will need to use a targets file.

To work in both you can condition the targets file to skip adding the references if the properties from nuget.g.props are set.

**Comment by akordowski** [comment]
I've tried to create a package based on this example: [Nugetx86x64](https://github.com/Cheesebaron/Nugetx86x64).
Here the `.nuspec` and `.props` file.

```<?xml version="1.0"?>
<package>
  <metadata>
    <id>ProjectLibrary</id>
    <version>1.0.0</version>
    <title>ProjectLibrary</title>
    <description>Description</description>
    <authors>Author</authors>
  </metadata>
  <files>
    <file src="bin\x86\*" target="lib\net45" />
    <file src="bin\x64\*" target="build\x64" />
    <file src="bin\x86\*" target="build\x86" />    
    <file src="ProjectLibrary.props" target="build\net45" />
  </files>
</package>
```
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Reference Include="Library" Condition="'$(Platform)' == 'x86'">
      <HintPath>$(MSBuildThisFileDirectory)..\x86\ProjectLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Library" Condition="'$(Platform)' == 'x64'">
      <HintPath>$(MSBuildThisFileDirectory)..\x64\ProjectLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

It seems the `.props` file is not used on build. In the x86 mode the app start without problems, when I switch to x64 I got an `BadImageException`. 

Have you an idea why it doesn't work?

Here is my test project: [NuGetTest](https://github.com/akordowski/NuGetTest)

**Comment by emgarten** [comment]
@akordowski NuGet adds a reference the props/targets file from the package. How the props/targets file runs is not a NuGet issue, it is the same as having the props/targets in your project file directly.

I suggest debugging this first as part of your project and not as part of a nupkg to see why your assemblies are failing with BadImageException.
