### ISSUE TITLE
Verification warnings not being propagated to VS

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#6454]
When a package should be treated as unsigned there are warnings passed up from the verification APIs and should be shown in VS whenever we are restoring or installing a package. We also need to specify that a package was treated as unsigned.

cc. @rido-min

**Comment by PatoBeltran** [comment]
@mishra14 was this solve as part of your current work with verification warnings on VS? Should this issue be closed?

**Comment by mishra14** [comment]
Should be solved in VS 15.8 P2 [27715.0] as part of https://github.com/NuGet/NuGet.Client/commit/e95a67ded682c5727ec3a2ff138cf748251006ce
