### ISSUE TITLE
TxM for dot net 4.7.x

### ISSUE THREAD

**Issue by ratishphilip** [NuGet/Home#6456]
Hi,

I am trying to create a nuget package for a WPF project. This package should contain dll's targeting multiple dotnet frameworks like
- v4.6
- v4.6.1
- v4.6.2
- v4.7
- v4.7.1
- v4.7.2

Though the TxM for the first three frameworks are **net46**, **net461** and **net462**, I cannot find the TxMs for v4.7.x anywhere.

The [FrameworkConstants.cs](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Frameworks/FrameworkConstants.cs) file does not mention the same too.

**Comment by emgarten** [comment]
NuGetFramworks understands that higher version numbers are compatible. Are you actually seeing problems when using net471?

**Comment by ratishphilip** [comment]
I haven't tried them yet.
I am planning to create one. I was reading through this [document](https://docs.microsoft.com/en-us/nuget/schema/target-frameworks#supported-frameworks) and didn't see **net471** listed.
