### ISSUE TITLE
Incorrect publish output for netcoreapp1.1 on linux-x64 targets

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6458]
_From @sbomer on August 1, 2017 20:46_

**Repro steps**

- Install preview2 SDK
- `dotnet new console`
- change TFM to netcoreapp1.1
- `dotnet restore`
- `dotnet publish -r linux-x64 -c Release -o out`

**Expected behavior:**
Either this works and the output has the required runtime assets (host, System.Private.CoreLib.dll), or this is not a supported scenario, and I get an error message.

**Actual behavior:**
Publish seems to succeed, but the published app contains no host or System.Private.CoreLib.dll. If I understand correctly, the linux-x64 rid isn't supported for netcoreapp1.1 targets, so the SDK should detect this and emit an error message.

@richlander @russellhadley 

_Copied from original issue: dotnet/sdk#1464_

**Comment by livarcocc** [comment]
The SDK does not own the mapping of TFMs and RIDs. I believe that is between NuGet and the Microsoft.NetCore.Platforms target.

I am going to move the issue to NuGet initially, if that's not the appropriate location, please comment and tag me and I can follow up with the runtime team to see what else can be done. But in my mind, this should fail at restore time.

**Comment by jainaashish** [comment]
@livarcocc There is no mapping between TFMs and RIDs. We use TFMs to resolve packages and check compatibility. RIDs are then used to filter runtime assets based on the specified value. You can also confirm that from project.assets.json file which clearly indicates what are the runtimeTargets assets for each TFM/RID combo. Also, NuGet doesn't participate in publish process, it should be the platform team responsibility to consume project.assets.json file and act accordingly.

@emgarten if he has any further thoughts here.

**Comment by emgarten** [comment]
@livarcocc I think this would be better tracked on the CLI side. Restore removed guardrails for runtime assets in 4.0 since it wasn't working for restore to check this based only on the name. The plan was to bring it back outside of nuget in publish or a later step if *if it was needed*. So far this is maybe the only request I've seen for validating this.

As a workaround the old UWP style check can be turned in NuGet with: `ValidateRuntimeIdentifierCompatibility=true`

**Comment by livarcocc** [comment]
I will re-activate the SDK issue and follow up with the runtime team what can be done here. I really don't want the SDK to be aware of the RIDs - TFM compatibility matrix.
