### ISSUE TITLE
nuget cli Could not load file or assembly

### ISSUE THREAD

**Issue by uujwnqjgim** [NuGet/Home#6459]
NuGet product used (Windows x86 Commandline):
NuGet version (4.5.0.4696):
OS version (win10 v 1703 (15063.483)):
![image](https://user-images.githubusercontent.com/4583234/35148168-ef584612-fd19-11e7-8f3e-b9a5cac2c941.png)

When I run nuget cli with the any command it first show four warnings and continues to execute the command.
Tried with restore command the same behavior.

>c:\>nuget.exe help
WARNING: Could not load file or assembly 'HolographicExtensions.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
WARNING: Could not load file or assembly 'HoloSHExtensions.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
WARNING: Could not load file or assembly 'PerceptionSimulationExtensions.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
WARNING: Could not load file or assembly 'Windows.Devices.Printers.Extensions.dll' or one of its dependencies. The module was expected to contain an assembly manifest.
NuGet Version: 4.5.0.4696
usage: NuGet <command> [args] [options]
Type 'NuGet help <command>' for help on a specific command.
...

**Comment by jainaashish** [comment]
Can you consistently repro this across multiple machines? I tried but couldn't repro it. May be you're missing some windows updates on the machine?

**Comment by JeremyOne** [comment]
I came across this same issue when I attempted to put nuget.exe in `%WINDIR%\System32` to make it accessible in `%PATH%` and all terminals. I solved the issue by moving nuget.exe to another PATH location: 
`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps`

**Comment by kraeg75** [comment]
Thanks JeremyOne.  That solved my problem.

**Comment by dotnetchris** [comment]
Still occurs with nuget.exe 4.6.2, perhaps you want to include in the handling that dumps out the warning statements "maybe you shouldn't have this in system32"

**Comment by cheyong007** [comment]
This Warnning still prompt at nuget.exe 5.0.2.5988, with powershell automatically downloaded to "system32". OS Version Win10-1809(17763.615)

Thanks to @JeremyOne , it fixed!

> I came across this same issue when I attempted to put nuget.exe in %WINDIR%\System32 to make it accessible in %PATH% and all terminals. I solved the issue by moving nuget.exe to another PATH location:
> %USERPROFILE%\AppData\Local\Microsoft\WindowsApps

**Comment by JerryJian** [comment]
Thanks to @JeremyOne , it fixed! 
NuGet Version: 5.2.0.6090, single .exe file downloaded from nuget.org.

**Comment by zkat** [comment]
This.... is probably not a scenario we'll try to support. Please use the usual PATH mechanism on Windows instead of putting it in the system folder ;)

**Comment by ghost** [comment]
The problem is still present in 5.5.1
@zkat is there any good reason why this scenario will not be supported?
For me it comes in very handy to put it in System32

Merci @JeremyOne

**Comment by armplinker** [comment]
I had tried the hack of putting nugget.exe in C:\Windows\System32.  Putting nugget in %USERPROFILE%\AppData\Local\Microsoft\WindowsApps resolved the  problem for me. What is troubling is how I make nuget globally accessible to all users of the box.  How do I do that?

**Comment by JeremyOne** [comment]
> What is troubling is how I make nuget globally accessible to all users of the box. How do I do that?

@armplinker add a new path to your environment variables everyone has access to, or use chocolatey to install nuget: https://chocolatey.org/packages/NuGet.CommandLine

**Comment by belachkar** [comment]
Fixed by installing **NuGet** using chocolaty on windows:
`choco install NuGet.CommandLine`.
And cleaning, rebuild.
