### ISSUE TITLE
Console Commands in powershell

### ISSUE THREAD

**Issue by NicTanghe** [NuGet/Home#6460]
My comments seem to keep on getting removed on the technet page.

So i'll post this as a bugreport even tho it is more of a WHY is this not a feature request.
So why can't you just run all the colsole commands straight from powershell.

# Not being able to update your packages from powershell is just plain ridiculess.
And i'm sure it whouldn't take allot of time for you guys to implement this.

I'm sure that a lack of this feature is keeping nuget from being implemented in buisnesses all around the world.

ps,
It sort of looks like microsoft doesn't want to move into their partners territory instead of a feature you haven't thought of.
In anny case package deployment should be standart and free just like installing exe's was.

**Comment by emgarten** [comment]
NuGet commands are built into PS with OneGet https://github.com/OneGet/oneget

For packages.config projects it is not possible to install/update/packages without Visual Studio and the DTE automation system that runs in VS.

The most recent version of NuGet supports updating outside of VS with PackageReferences and is purely command line based and cross platform.
Take a look at: https://blog.nuget.org/20170316/NuGet-now-fully-integrated-into-MSBuild.html

**Comment by StingyJack** [comment]
@Drunkenpanda2000 - what commands do you mean?  

I can call `nuget restore` from powershell and `install` runs (not that it actually installs into a project - be it packages.config or package ref).

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
