### ISSUE TITLE
[vsfeedback] NuGet Update tab freezes for a local package source

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6470]
NuGet &quot;Updates&quot; tab sometimes freezes when it's looking at a local folder. It doesn't always do this, but it's common enough to be annoying.

Please don't ask me to give more information. I cannot. Not least because NuGet doesn't give any feedback or produce any useful logs for me to send you.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/164682/nuget-freezes.html
VSTS ticketId: 536181_
_These are the original issue comments:_

Justin Emgarten [MSFT] on ‎12‎/‎15‎/‎2017, 03:01 PM (35 days ago): <p>How many packages are in the local folder?</p><p>How many MB total is the local folder?</p><p>Is this a flat folder of nupkgs, or is it using the v3 format of id\version\?</p>
Maria Ghiondea [MSFT] on ‎12‎/‎15‎/‎2017, 04:13 PM (34 days ago): <p>Thank you for your feedback! For us to investigate this further, could you please provide on the contents of the local folder and how long the freeze occurs. We look forward to hearing from you!</p>

_These are the original issue solutions:_

Dan solved on ‎12‎/‎16‎/‎2017, 02:40 AM (34 days ago), 0 votes: 
<p>At the moment, there are 73 packages in the local folder. It varies as I use it as a store for the packages that I build from github. The package names vary. Here's a sample of some typical ones (produced by the Orleans build):</p>
<pre>10/12/2017  09:58            12,460 Microsoft.Orleans.Client.2.0.0-dev-201712100954.nupkg
10/12/2017  09:58            12,962 Microsoft.Orleans.Client.2.0.0-dev-201712100954.symbols.nupkg
14/12/2017  10:38            12,457 Microsoft.Orleans.Client.2.0.0-dev-201712141034.nupkg
14/12/2017  10:38            12,960 Microsoft.Orleans.Client.2.0.0-dev-201712141034.symbols.nupkg
10/12/2017  09:58            63,618 Microsoft.Orleans.Clustering.AzureStorage.2.0.0-dev-201712100954.nupkg
10/12/2017  09:58           159,966 Microsoft.Orleans.Clustering.AzureStorage.2.0.0-dev-201712100954.symbols.nupkg
14/12/2017  10:38            56,245 Microsoft.Orleans.Clustering.AzureStorage.2.0.0-dev-201712141034.nupkg
14/12/2017  10:38           145,679 Microsoft.Orleans.Clustering.AzureStorage.2.0.0-dev-201712141034.symbols.nupkg
10/12/2017  09:58            22,552 Microsoft.Orleans.Clustering.ServiceFabric.2.0.0-dev-201712100954.nupkg
10/12/2017  09:58            64,369 Microsoft.Orleans.Clustering.ServiceFabric.2.0.0-dev-201712100954.symbols.nupkg
14/12/2017  10:38            22,541 Microsoft.Orleans.Clustering.ServiceFabric.2.0.0-dev-201712141034.nupkg
14/12/2017  10:38            65,341 Microsoft.Orleans.Clustering.ServiceFabric.2.0.0-dev-201712141034.symbols.nupkg
1</pre>
<p>It is a flat folder - no subdirectories.</p>

**Comment by nkolev92** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/pull/2858
