### ISSUE TITLE
Wrong app.config file is updated on package install

### ISSUE THREAD

**Issue by julealgon** [NuGet/Home#6476]
When using MSBuild's `<AppConfig>` property to change the default app/web.config path on a given project, nuget.exe will completely ignore this property and try to generate a new app/web.config file whenever configuration changes are needed (like binding redirects).

This behavior is clearly incorrect. This `AppConfig` property is part of the algorithm used by MSBuild to find a project's configuration file and should be taken into account by nuget.exe as well.

Some information about the MSBuild logic and support for `AppConfig`:
https://timvw.be/2008/03/17/easily-switching-between-appconfig-files-with-msbuild/

I tried attaching a zipped project here but Github simply refuses to accept it (tried zipping a solution and then an isolated project). Adding even a PNG is not working, so let me know if you need extra information here and how I can provide it.

**Comment by jainaashish** [comment]
This is weird github didn't allow you to add zip or image. Can you upload to some online drive and share the link?

**Comment by nkolev92** [comment]
Thanks for filing this issue.
Unfortunately we haven't received enough details to further analyze this issue.
