### ISSUE TITLE
UI updates to reflect V3 scenarios

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#648]
1. Dependency behavior is not supported
2. Verify preview still works
3. File conflict action does not work
4.

**Comment by csharpfritz** [comment]
When entering NuGet UI from Solution node of Solution Explorer, its hard to tell which package version is installed in each project.

**Comment by emgarten** [comment]
Fixed NuGet/NuGet.PackageManagement@c2ccc7d29440007b0f2f2cc95cb06273ae44d34c
