### ISSUE TITLE
Retrieve list of all packages from private feed with V3 API

### ISSUE THREAD

**Issue by virmitio** [NuGet/Home#6480]
Our team is moving from V2 feeds to V3 feeds hosted in VSO, and I have been tasked with updating some of our build-time tooling that does sanity checks on the packages in the private feeds.

In V2 it was fairly trivial to get a complete listing of package IDs in a gallery and then drill into versions and specific package metadata.  Having read through the available documentation on using the API directly (which appears to be rather sparse at the moment) and reviewed existing bugs/issues/enhancements that appear recent and related (eg, #6393 ), it seems what I'm looking for is a Catalog resource in the feed.

It would appear that VSO NuGet feeds don't supply this resource, as I cannot locate any index entries with `@type` containing `Catalog`.  Is the Catalog resource the only practical means for getting a complete package listing from V3 feeds?

**Comment by emgarten** [comment]
VSTS I think you would need to use search to discover all ids: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource

Adding an id service to the v3 protocol has been discussed here: https://github.com/NuGet/NuGetGallery/issues/3878

//cc @joelverhagen

**Comment by joelverhagen** [comment]
I am pretty sure VSTS has a notion of "unlisted" so I imagine search would not return those. Also, search order is probably not a totally stable thing like catalog ordering is (e.g. if a package is pushed while you are paging through search results you may miss it). That being said, @emgarten is spot on. I think that's the best you're gonna get.

VSTS provides both V2 and V3 endpoints for a single feed (a.k.a. package source), right? Therefore, you should be able to use V3 for all of your developer environments, tooling, etc and V2 just for the comparison of two feeds.

**Comment by nkolev92** [comment]
Closing this as question.
