### ISSUE TITLE
NuGet whacked my LOCAL packages

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#6481]
Why doesn't NuGet drop ***SOLUTION*** packages in the ***SOLUTION***?

Furthermore, NuGet seems to have ***WHACKED*** my LOCAL packages.

I ***INTENTIONALLY*** keep some of my packages ***LOCALLY*** to support on going projects, but NuGet has ***ENTIRELY DELETED THEM!!!***

Would be great to have known that in advance so that I can make adjustments to my strategies.

**Comment by mishra14** [comment]
@mwpowellhtx What is the scenario here?

Can you please provide the steps that you performed and the end result?

**Comment by mwpowellhtx** [comment]
I had local packages stowed away in a path, */path/to/nuget/packages*. Then I upgraded to the latest ``nuget``. Recently when I accepted a dependency to *Chutzpah* (or */insert/package/here/*). When I reviewed for my *packages*, they were **GONE!!!** I hadn't removed them, as I want to maintain my local packages.

For future strategies, I will acknowledge */path/to/nuget/packages/* was a poor choice of names on my part, ***BUT STILL!***

**Comment by mishra14** [comment]
If I understand correctly -

1. You had some nuget packages in `/path/to/nuget/packages`.
2. You upgraded `nuget.exe` that you use.
3. You added a dependency on package `Chutzpah` into a project.

And as a result your packages at `/path/to/nuget/packages` were deleted?

**Comment by mwpowellhtx** [comment]
That is correct.

**Comment by emgarten** [comment]
* Is this a packages.config project or a PackageReference project?
* What version of NuGet.exe were you using before?
* What version of NuGet.exe did you upgrade to?
* What commands did you run that may have caused this?

**Comment by mwpowellhtx** [comment]
I'm not sure what a *PackageReference* project is. Yes, the solution/projects contains *packages.config*, from VS2015. I was simply running from the NuGet Package Manager from the IDE. NuGet version *4.3.0.4406*. I didn't run anything out of the ordinary for NuGet package references, certainly not anything apart from NuGet that would result in the packages vanishing.

**Comment by emgarten** [comment]
With packages.config NuGet does put the packages in the solution by default.

Was `/path/to/nuget/packages` where the packages were kept a source, or was it the `repositoryPath` where they were installed to and referenced by the project?

**Comment by mwpowellhtx** [comment]
I don't know what changed. Nothing I changed. But that's not where the packages are landing.

*/path/to/nuget/packages* was my local package repository. I ***expected*** Chutzpah, etc, to land in my ***solution***, however, apparently, it did not.

**Comment by emgarten** [comment]
Are you sure that it was NuGet that deleted the packages and not something else?

You haven't mentioned any commands that you ran, or how you were using the path so it is difficult to even guess what might have happened here. But in general NuGet doesn't delete packages unless an update was run for packages.config, and in that case only the older version is removed. NuGet.exe for example doesn't even have an uninstall command on it.

**Comment by mwpowellhtx** [comment]
I haven't touched that folder, and haven't run anything else **BUT** NuGet anywhere near that folder. Like I said, I maintain my local nuget packages there; now somewhere else that I'm aware of this kind of corruption.

**Comment by emgarten** [comment]
How did you pass the folder to NuGet? Was this a command line argument, or was it using nuget.config?

**Comment by mwpowellhtx** [comment]
I orient Nuget to my local packages via the Visual Studio IDE *Tools/Options*, etc.

**Comment by emgarten** [comment]
Thanks, that is helpful. That would mean it is added as a source to nuget.config.

Did you use `nuget.exe delete` or `nuget.exe push`?

**Comment by mwpowellhtx** [comment]
No sir. I "push" my packages there via simple, ordinary *Windows Command Prompt* commands, *copy*, *move*, etc. No reason to "involve" NuGet in that way since my source is local.

**Comment by emgarten** [comment]
`NuGet.exe delete` will remove a package from a local source, or unlist it for http sources.

Beyond that there are no scenarios I know of where NuGet.exe will remove or create any files on a source like you are describing. Sources are often immutable, or are network shares where the user does not have write access.

This is the first time I've heard of packages being removed from a source. My best guess here is that something external removed the packages. There just isn't code in NuGet that would delete everything from a source. `NuGet.exe delete` needs the package id specified, and will prompt to confirm that you want to delete a package. Even if you were to run that command it would take some effort to remove all of the packages.

If you are able to repro this or find out more on what may have happened I would be happy to help improve the experience and help safe guard against it in NuGet, it sounds like it has caused you a lot of pain.

**Comment by mwpowellhtx** [comment]
To recap, I didn't see this problem manifest until after I subscribed to Chutzpah via "ordinary" NuGet channels. Somehow or another the solutions packages were seen as my */path/to/nuget/packages*. Which is a surprise to me because I expected it to be */path/to/solution/packages*.

Coincident to that, but I fail to see why it may contribute to the issue, is that I deleted the solution *.nuget* folder, preferring instead the latest *nuget.exe* in my */path/to/nuget/bin* folder.

**Comment by mwpowellhtx** [comment]
One thought, if not code in nuget itself, perhaps code in the integration bits, NuGet Package Manager? or the IDE itself?

**Comment by emgarten** [comment]
> I didn't see this problem manifest until after I subscribed to Chutzpah via "ordinary" NuGet channels

Can you explain this further?

`Chutzpah` is a tool package, and NuGet doesn't use anything from this directly. The normal scenario for this is that NuGet would download the package for you and extract the package. After it is extracted it is up to the user to call things from the `tools/` folder themselves, NuGet doesn't execute or even read that folder itself.

Are you saying that after calling the exe in `Chutzpah`  that things changed and it started using your package source in a different way?

**Comment by mwpowellhtx** [comment]
I'm not saying it's a problem which Chutzpah, per se. The packages were fine until that point. I deleted the .nuget local to the solution. Then I added the Chutzpah package reference. I couldn't find it in my solution/packages where I expected it, which then I happened to find it in my nuget/packages. And all my packages GONE.

**Comment by emgarten** [comment]
Does your `%AppData%\NuGet\nuget.config` contain a `repositoryPath` setting? Or any other NuGet.Config files you have around?

**Comment by emgarten** [comment]
Check also if `nuget.exe -List all` displays `nuget/packages` where the packages were.

**Comment by mwpowellhtx** [comment]
The solution *did* contain a *NuGet.Config*. I deleted that folder, however, so I presume that perhaps the global settings are somehow used? *%AppData%/Roaming/NuGet/NuGet.Config* does not contain this setting. The options I have are *nuget.exe list all*; however, I don't see the packages listed there.

```Xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="Autofac (MyGet.org)" value="https://www.myget.org/F/autofac/api/v2/" />
    <add key="Locally Published Packages" value="/path/to/nuget/local/published" />
    <add key="Gemini AppVeyor" value="https://ci.appveyor.com/nuget/gemini-g66c82jjbsu1" />
    <add key="My Gemini AppVeyor" value="http://ci.appveyor.com/nuget/gemini-70mwm1iwg2qc" />
    <add key="NuGet.org (V3)" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <apikeys>
    <add key="https://www.nuget.org" value="..." />
    <add key="https://nuget.smbsrc.net/" value="..." />
  </apikeys>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <disabledPackageSources>
    <add key="Gemini AppVeyor" value="true" />
  </disabledPackageSources>
</configuration>
```

I've updated my local source since learning of this snafu.

**Comment by emgarten** [comment]
Sorry, I meant `nuget.exe Locals -List all`  I dropped the command name when pasting it earlier.

That config looks fine to me, it is only setting sources, not the install locations.

**Comment by mwpowellhtx** [comment]
I don't know what else to report at the moment. I'll keep an eye on it, especially as I work to rebuilt my local packages. Fortunately, I control much of that source code to begin with.

**Comment by emgarten** [comment]
Let me know if you see this happen again.

My only other thought on this is that the path may have been configured as a cache location, possibly through an env var. This would show under `NuGet.exe Locals`, and it would be possible to delete these from the UI under Tools > Options (if that button existed in VS 2015, I'm not sure).

I'm going to close this issue out since, but feel free to continue adding info here and we can reopen as needed.

**Comment by mwpowellhtx** [comment]
@emgarten Will do; thanks for diving into this anyway.
