### ISSUE TITLE
NuGet adds app.config

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6487]
@hndavis commented on [Tue Jan 23 2018](https://github.com/NuGet/NuGetGallery/issues/5337)

I am using visual studio 2017 c# 4.52.   After I use nuget to add a package I see that nuget has also added app.config.  Why is this happening ?  how can I turn it off ?

**Comment by emgarten** [comment]
NuGet support for binding redirects can be disabled through Tools > Options > NuGet > General. 

See: https://github.com/NuGet/Home/issues/1147

If you are still getting app.config after turning binding redirects off then you may be getting this file from settings in your project itself or the SDK used by your project.

**Comment by jainaashish** [comment]
Closing this as question for now. Let us know if there is any further concern.
