### ISSUE TITLE
Investigate the assets file comparison further and add more extensive lock file comparison tests

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6488]
Issue became apparent in this PR. 
https://github.com/NuGet/NuGet.Client/pull/1979
https://github.com/NuGet/NuGet.Client/pull/2052

We need to add tests for the above PR and make sure there aren't any other low hanging fruits there.

**Comment by nkolev92** [comment]
Some basic AssetFallbackFramework equality tests added dev-nkolev92-lockfileequalityimprovements

**Comment by anangaur** [comment]
Is it related to the proposed lock file feature or the current assets file in obj directory? Or something else altogether :)

**Comment by nkolev92** [comment]
This is the assets file. 
There are some bugs in the comparison there that cause more DT builds, which already have perf problems.

**Comment by nkolev92** [comment]
We've caught many of these, but at this point this is not a low return of investment issue.

**Comment by nkolev92** [comment]
I fixed this in https://github.com/NuGet/NuGet.Client/commit/7aefbcf4c192ee87af5799556e455c667dcaff30. 

The impact was actually significantly larger than I thought :)
