### ISSUE TITLE
Duplicate NuGet package sources are silently ignored.

### ISSUE THREAD

**Issue by peterhuene** [NuGet/Home#6489]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **NuGet.exe**

NuGet version (x.x.x.xxx): **4.7.0.30392**

dotnet.exe --version (if appropriate): **N/A**

VS version (if appropriate): **N/A**

OS version (i.e. win10 v1607 (14393.321)): **Windows 10 x64 1709 (16299.192)**

Worked before? If so, with which NuGet version: **N/A**

## Detailed repro steps so we can see the same problem

1. Create a NuGet.config containing the following:

```xml
<?xml version="1.0" encoding="utf-8"?>
  <configuration>
  <packageSources>
    <clear />
    <add key="foo" value="bar" />
    <add key="foo" value="baz" />
  </packageSources>
</configuration>
```

2.  Run the following command:

```
NuGet.exe sources -ConfigFile NuGet.config -verbosity detailed
```

## Expected result

NuGet emits an error (preferable) or warning about the duplicate package source.

## Actual result

```
NuGet.exe sources -ConfigFile NuGet.Config -verbosity detailed
NuGet Version: 4.7.0.30392
Registered Sources:

  1.  foo [Enabled]
      ...\bar
```

Note: the "first one in" won.  The second entry was (seemingly) silently ignored.

## Other notes

We ran into this issue from an automated build that generated a NuGet.config file dynamically and accidentally used the same package source key for each entry added; this resulted in difficult to diagnose build failures during package installation relating to packages not being found.

**Comment by jainaashish** [comment]
This is actually by design to ignore duplicate sources and pick the first one. Since there could be multiple config files at different level like solution-wide, user-wide, or machine-wide. And sometimes user explictly wants it to configure duplicate source at different level to use dev latest bits at dev boxes vs stable bits at CI. Besides, NuGet explicitly doesn't allow to add duplicate source either by UI or commandLine so only way you could do it when you manually edit or write a config file.

**Comment by peterhuene** [comment]
I hadn't thought of it that way. Unfortunately that design does make a diagnostic warning undesirable since the ignoring of the duplicate source would be intentional. Given we did in fact programmatically generate the config in question, I'm not imposed to putting the onus on us to catch these problems.

I believe this is can be closed. Thanks for the feedback!
