### ISSUE TITLE
add commit hash to informational version

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#6492]
When trying to build code from source we need to be able to track back the source code used to build a particular library. Most .NET libraries have the sha embedded as metadata in the binary as well as in the package. It would be very useful if the nuget libraries carried this information.

**Comment by jainaashish** [comment]
I'm not sure what's the ask here? The assembly informational version could have the git hash embedded which can always help to cross reference the CI build number to the specific git hash. What do you need special from NuGet?

**Comment by weshaggard** [comment]
The ask is to put the actual sha into the informational version like most other .NET Core libraries we ship. Why would we make people do an unnecessary cross reference just for your library. General folks approaching your libraries and repo will not know how to cross reference the CI build number. I had to ask someone on the nuget team to get the sha I needed.

**Comment by rohit21agrawal** [comment]
all our release bits are tagged with the file version...so anyone who has a file version say, 4.6.0.4323, can just git checkout 4.6.0.4323 to get the relevant source code.

**Comment by weshaggard** [comment]
That doesn't work for everything. I don't see a tag for 4.5.0-rtm-4651 (https://www.nuget.org/packages/NuGet.CommandLine.XPlat/4.5.0-rtm-4651) which is what I was trying to find the matching sources for.  In an open source world it is good practice to leave enough information in the binaries to track back the source where they came from which is why I still highly suggest adding the sha into the informational version.

**Comment by emgarten** [comment]
Related: https://github.com/NuGet/Home/issues/6547

**Comment by rohit21agrawal** [comment]
@weshaggard is there particular metadata in which SHA is embedded or it can be arbitrary? We can't really use AssemblyInformationVersion/AssemblyFileVersion/AssemblyVersion as that breaks some of our version checks, but I can embed the SHA in description.

**Comment by weshaggard** [comment]
For our corefx libraries we generally add it to AssemblyInformationalVersion and the embedded product version, which is what I recommend. However some folks also just add the information as in an AssemblyMetadata attribute. Either would work and allow folks to find the information. For the package version we also sometime drop in a version text file with the information in our packages, which is a way to provide the information until there is first class support via #6547.

**Comment by weshaggard** [comment]
Thanks for fixing this. Can I also suggest you consider porting the change to your release branches so that servicing events will have these markers.
