### ISSUE TITLE
Update Errors and warning docs to reflect signing related scenarios

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6498]
We should update the Errors and Warnings docs [page](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings) to cover package signing related scenarios.

@dtivel made an excel sheet that covers the scenarios and can be used as a reference.

cc: @anangaur @karann-msft

**Comment by mishra14** [comment]
Assigning to @rido-min  after chatting with @anangaur. Please correct me if needed.

**Comment by rido-min** [comment]
Main pages created in https://github.com/NuGet/docs.microsoft.com-nuget/commit/43179234b0544b5c68fc026ef2e45e79a33427b6

CLI referece and Errors/Warnings assigned to @dtivel

**Comment by mishra14** [comment]
Documentation for pack has been completed with - https://github.com/NuGet/docs.microsoft.com-nuget/pull/1014

Updating the bug title to reflect that.

**Comment by mishra14** [comment]
~27 of the signing codes have also been documented as part of - https://github.com/NuGet/docs.microsoft.com-nuget/pull/1019

the remaining ones are - 
```
NU3024
NU3025
NU3026
NU3027
NU3028
NU3029
NU3030
NU3031
NU3032
NU3033
NU3034
NU3035
NU3036
NU3037
NU3038
```
