### ISSUE TITLE
[V3] NRE thrown from package manager UI

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#650]
1. Create a new .NET 4.5 project
2. Manage NuGet Packages...
3. Search for Moq
3. Install Moq
4. Set filter to Installed
5. Click on Uninstall

NullReferenceException thrown from NuGet.PackageManagement.UI.NuGetUI.FileConflictAction, model is null

**Comment by zhili1208** [comment]
can't repro on my machine

**Comment by AndriySvyryd** [comment]
For me it reproes on 22823.1 D14REL, but doesn't on 22923.0 VSCLIENT_1

**Comment by AndriySvyryd** [comment]
This is probably a dupe of #701

**Comment by zhili1208** [comment]
Yes, it's a dupe of #701, close it as a dupe
