### ISSUE TITLE
proxy setting in NuGet.Config did not work

### ISSUE THREAD

**Issue by chucklu** [NuGet/Home#6501]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):
NuGet Version: 4.4.1.4656

OS version (i.e. win10 v1607 (14393.321)):
OS Name:                   Microsoft Windows Server 2008 R2 Standard
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation

Worked before? If so, with which NuGet version:
No.

## Detailed repro steps so we can see the same problem

1.  run nuget restore with local system account in a windows service(Jenkins)
>whoami
nt authority\system

2. restore failed
>nuget.exe restore .\UnitTest.sln 
MSBuild auto-detection: using msbuild version '15.5.180.51428' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Restoring NuGet package NUnit3TestAdapter.3.9.0.
Restoring NuGet package NUnit.3.9.0.
WARNING: Unable to find version '3.9.0' of package 'NUnit'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'NUnit.3.9.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.75.89.224:443

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

NuGet Config files used:
    D:\NuGet.Config
    C:\Windows\system32\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

I  have checked the first two files, both of them have the correct proxy setting.
(I have modify the value when I paste them here, I configured them by the command line with nuget config command)
```xml
<add key="http_proxy" value="http://172.31.135.41:8080" />
    <add key="http_proxy.user" value="domain\user" />
    <add key="http_proxy.password" value="PaswordDqQcW/Pfd8yizBino48RmsbLK1yh/7bM+3GCZOxU4ro=" />
    <add key="-configfile" value=".\NuGet.Config" />
```

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by emgarten** [comment]
@chucklu unfortunately we are unable to diagnose your local proxy issues. Unless you are seeing a regression between different versions of nuget.exe then it is likely that the problem is with your network or the provided settings.

I suggest looking at the documentation here for further info on configuring your proxy:
https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file

Using a tool to trace your network calls may also help you diagnose the issue.

**Comment by chucklu** [comment]
@emgarten  Is it possible for you to make the nuget output the detail of proxy setting?
I am  not sure if nuget really read the proxy setting form the config file successfully.

**Comment by chucklu** [comment]
@emgarten  The previous output is run as Local System.
When  I run it as a normal user, the proxy works fine.
> NuGet Version: 4.4.1.4656
> MSBuild auto-detection: using msbuild version '15.5.180.51428' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
> MSBuild P2P timeout [ms]: 120000
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\msbuild.exe "C:\Users\dev\AppData\Local\Temp\2\NuGetScratch\ogakn5tg.btq.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\dev\AppData\Local\Temp\2\NuGetScratch\mqan3qxb.gqi.nugetrestore.targets" /p:RestoreTaskAssemblyFile="D:\JENKINS_HOME\nuget.exe" /p:RestoreSolutionDirectory="D:\JENKINS_HOME\CodeCoverage" /p:SolutionDir="D:\JENKINS_HOME\CodeCoverage"
> 
> Restoring NuGet package NUnit3TestAdapter.3.9.0.
> Restoring NuGet package NUnit.3.9.0.
> Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\nunit\3.9.0\nunit.3.9.0.nupkg
> Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\nunit3testadapter\3.9.0\nunit3testadapter.3.9.0.nupkg
> Adding package 'NUnit3TestAdapter.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages'
> Adding package 'NUnit.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages'
> Added package 'NUnit3TestAdapter.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages'
> Added package 'NUnit3TestAdapter.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages' from source 'C:\Users\dev\.nuget\packages\'
> Added package 'NUnit.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages'
> Added package 'NUnit.3.9.0' to folder 'D:\JENKINS_HOME\CodeCoverage\packages' from source 'C:\Users\dev\.nuget\packages\'
> 
> NuGet Config files used:
>     D:\JENKINS_HOME\NuGet.Config
>     C:\Users\dev\AppData\Roaming\NuGet\NuGet.Config
>     C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
> 
> Feeds used:
>     C:\Users\dev\.nuget\packages\
>     https://api.nuget.org/v3/index.json
>     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
> 
> Installed:
>     2 package(s) to packages.config projects
> 


So, I think maybe you did not read the proxy settings when the command line run under Local System,
> whoami
> nt authority\system

**Comment by chucklu** [comment]
@emgarten  I found maybe it's the permission problem about proxy.
The Local System account might can not access the proxy configured in NuGet.config.

Solution:
I  am using Jenkins run this command, so I switch the Jenkins windows service to another normal account who has access to proxy.
![default](https://user-images.githubusercontent.com/3004057/35607518-8302f816-068f-11e8-9672-b2991d7bf984.png)

**Comment by emgarten** [comment]
@chucklu thanks for the update, I'm glad you were able to track it down!
