### ISSUE TITLE
can't build with msbuild

### ISSUE THREAD

**Issue by thyn** [NuGet/Home#6502]
Please read the following information before posting the issue.

(NuGet.exe | VS UI ) -

NuGet version (4.5.0):

Worked before? If so, with which NuGet version: 4.4.1

build with msbuild from latest vs 2017 community results in 
 "Process 'NuGet.exe' exited with code '1'."

error MSB3073: The command ""...\NuGet.exe" install "...\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "...."" exited with code 1. [....Project.csproj]
...

When I downgrade to 4.4.x everything is ok

**Comment by thyn** [comment]
another issue

https://stackoverflow.com/questions/48508960/nuget-restore-in-ms-build-step/48517163#48517163

**Comment by emgarten** [comment]
Duplicate of https://github.com/NuGet/Home/issues/6503
