### ISSUE TITLE
Nuget tries internet even though only local package repository

### ISSUE THREAD

**Issue by erict-powersoft** [NuGet/Home#6504]
## Details about Problem
Computer is on a network that cannot be connected to the internet.  When browsing for local package sources, VS hangs until internet timeout even though nuget.org package source not enabled.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): v3.6.0

dotnet.exe --version (if appropriate): 

VS version (if appropriate): VS2015 SP3  (14.0.25420.01)

OS version (i.e. win10 v1607 (14393.321)): Windows 7 SP1 - not up to date - classified computer
PowerShell: 2.0

Worked before? If so, with which NuGet version: 

## Detailed repro steps so we can see the same problem

1.  Set up local package source and verify that it works, and uncheck 'https://www.nuget.org/api/...' source

2. Disconnect your computer from the network

3. Open NuGet Package Manager, click on Browse.  

4.  Observe that VS2015 not responding for about 40 seconds.  Presumably until internet timeout.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by erict-powersoft** [comment]
Note that in our case, we are on a network (which is different than the recreate steps).  But our network does not have access to the internet.

**Comment by emgarten** [comment]
This could be due to NuGet trying to load icons from http urls.

**Comment by rohit21agrawal** [comment]
@erict-powersoft do you also see this issue in VS2017?

**Comment by StingyJack** [comment]
If you have any package references in your project (like the ones that can come as part of a web  templates) that were sourced from nuget.org, this can also happen. 

Can fiddler or another http trace be used on your workstation to see if VS is attempting to contact any internet sites?

**Comment by erict-powersoft** [comment]
That’s a great thought.  Starting NuGet Package Manager Console, VS2015 tries to get to a bunch of sites, all seemingly related to certificates (see list below).  Once it’s done that, access to the GUI is swift, until VS has shutdown

Interestingly it seems to access the same sites when first starting VS (not verified if they’re identical).

There’s also an attempt to tunnel to raw.githubusercontent.com:443, and to cdn.rawgit.com:443.  Not sure what that is about.  They could be related to the 5 packages I installed in the local repository, because I also see for example an attempt to tunnel to system.data.sqlite.org:443.  SQLite is one of the packages in the local repo.

There’s probably nothing I can do about this.
Thanks,
Eric
[cid:image002.jpg@01D3A687.305D8F30]

**Comment by chadAtGA** [comment]
I have this exact problem in my offline scenario. Please give us a way to either stop requesting icons and have them be part of the package. I'm using VS 2017 15.9.1. I used Fiddler and saw it requesting Host www.castleproject.org Url /img/castle-logo.png among others but you get the point.

**Comment by rrelyea** [comment]
We've released 5.3-preview3 with a warning for the old icon technique...and ask package authors to use a new embedded icon. This is the start of the move to embedded icons.
@karann-msft

**Comment by rrelyea** [comment]
going to close this issue.
if you find NuGet accessing sources when they shouldn't, please open an issue with full details.

Following up on my 9/19/2019 comment: as for, icons, nuget.org feed in search tab no longer hits the URLs. And people will be evolving packages forward to fix it. That is being addressed as part of that investment.
