### ISSUE TITLE
Issue restoring Fody

### ISSUE THREAD

**Issue by dansiegel** [NuGet/Home#6506]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet cli on Mac

NuGet version (x.x.x.xxx):
4.3.0
updated to 4.5.1.4879 with the same result

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): macOS X 10.13.2

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PropertyChanged.Fody" Version="2.2.5" />
    <!-- The following makes no difference in results with the error -->
    <PackageReference Include="Fody" Version="2.3.23" />
  </ItemGroup>
</Project>
```

- Have a package directly or indirectly referencing Fody version >=2.3.19
- Try restoring the project 
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

**Comment by emgarten** [comment]
@dansiegel can you share the output logs? I don't see anything indicating an error here or what you are expecting.

**Comment by dansiegel** [comment]
I can't publicly share log files on this project, and some combination rebooting, downgrading and then upgrading seems to have resolved whatever was causing the issue

**Comment by emgarten** [comment]
Thanks for the update @dansiegel, I'll close this out unless you are able to repro it again.
