### ISSUE TITLE
MSBuild Fails to Restore Packages with Package Manager Console Version Requirements Using NuGet.exe

### ISSUE THREAD

**Issue by justincockrell** [NuGet/Home#6512]
Project that builds on local machine with Package Manager Console does not build on server using NuGet.exe due to NuGet versioning. Prior to the addition of the offending package, the project built without issue for 2 years.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.5.1

dotnet.exe --version (if appropriate): NA

VS version (if appropriate): VS 2013 Pro and VS 2017 Pro

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2008 R2

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Install a package in a Visual Studio project that requires NuGet version 2.12 or above (MailKit version 2.0.1 in our case)

2. Move project to build server (Windows Server 2008 R2 in our case) using nuget.exe 4.5.1 for package restore

3. Using msbuild, try to build project on server

4. Get error "The 'MailKit 2.0.1' package requires NuGet client version '2.12' or above, but the current NuGet version is '2.8.60318.667'."

**Comment by emgarten** [comment]
> using nuget.exe 4.5.1 for package restore
> the current NuGet version is '2.8.60318.667'."

Are you sure that nuget.exe 4.5.1 is being used and not nuget.exe 2.8.6 or VS 2013?

**Comment by justincockrell** [comment]
I really didn't think it was, but doing a search on the server, it appears Kudu DOES keep a local copy in a Scripts folder that it uses when running msbuild, as opposed to the one I thought it was using. I replaced it and the project built again.

Thanks for making me double check!
