### ISSUE TITLE
/t:restore causes NotFound https://api.nuget.org/v3-flatcontainer/{My Nuget package}/index.json

### ISSUE THREAD

**Issue by gdodd1977** [NuGet/Home#6513]
I am using /t:restore on my MSBuild task in TFS for a ServiceFabric WebApi project. When it goes to do the restore, it is attempting to do a GET https://api.nuget.org/v3-flatcontainer/{My Nuget package}/index.json. Why is it looking for my nuget package in that location? I have a few custom nuget packages in this project, but it only seems to be doing it for this one. 

EDIT: I also see this:  No packages exist with this id in source(s): nuget.org. So again, not sure why it's looking in nuget.org.

**Comment by gdodd1977** [comment]
I figured this out. You need to specify all package locations to MSBuild.

**Comment by bangaruchary** [comment]
Hi, I am using DotNet Build command.
Initially i was getting this error:
error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
For this I have set HTTP_PROXY variable to the proxy.

Even though I have used DotNet Restore, build command again trying to restore the packages, is there any way that I can stop restoring while build.

Thank you
Chary
