### ISSUE TITLE
Add netstandard2.0 support to NuGet.* packages

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#6516]
I'm trying to prototype a standalone netcoreapp2.0 app that uses NuGet APIs, but am running into what appears to be an authoring error in dependencies of NuGet.Protocol

## Repro
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Protocol" Version="4.6.0-rtm-4825" />
  </ItemGroup>

</Project>
```

dotnet restore produces 35 errors like this.
```xml
C:\tmp\nuget_slim\nuget_slim.csproj : error NU1605: Detected package downgrade: System.Threading from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.
C:\tmp\nuget_slim\nuget_slim.csproj : error NU1605:  nuget_slim -> NuGet.Protocol 4.6.0-rtm-4825 -> NuGet.Packaging 4.6.0-rtm-4825 -> NuGet.Packaging.Core 4.6.0-rtm-4825 -> System.Xml.XDocument 4.0.11 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Threading (>= 4.3.0)
C:\tmp\nuget_slim\nuget_slim.csproj : error NU1605:  nuget_slim -> NuGet.Protocol 4.6.0-rtm-4825 -> NuGet.Packaging 4.6.0-rtm-4825 -> NuGet.Packaging.Core 4.6.0-rtm-4825 -> System.Xml.XDocument 4.0.11 -> System.Threading (>= 4.0.11)
```
Full list of errors:
[msbuild.log](https://github.com/NuGet/Home/files/1690524/msbuild.log)

## Details
```
dotnet --version
2.1.300-preview1-008009
```

**Comment by emgarten** [comment]
NuGet packages should add support for netstandard2.0. I've hit problems like this also when consuming the packages from netcoreapp2.0 projects.

**Comment by natemcmaster** [comment]
That would be even better. Would you drop netstandard1.x or net45? Or just add ns2.0?

**Comment by emgarten** [comment]
Ideally this would be just adding ns2.0. But if msbuild and the cli are no longer using ns1.3 then we might be able to drop it completely.

**Comment by emgarten** [comment]
Updating the title to match the work that needs to be done here.

**Comment by Nirmal4G** [comment]
Any progress on this?

**Comment by nkolev92** [comment]
@Nirmal4G The issue status is up to date. It's not being actively worked on. 
The PR linked is blocked, likely because of some ILmerge issues.

**Comment by Nirmal4G** [comment]
Thanks for the update. Will it make into 5.0 update?
