### ISSUE TITLE
Fix NuGet's packages' metadata

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#6518]
Our NuGet packages should be updated to use the required metadata.

​Autho​rs
The Authors for the package should just be "Microsoft".

License URL - https://github.com/NuGet/NuGet.Client/blob/dev/LICENSE.txt
Requiring License Acceptance - true
​Project URL - https://github.com/NuGet/nuget.client/
Copyright - "© .NET Foundation. All rights reserved."
Logo
Update the package logos to use the new official nuget logo

**Comment by anangaur** [comment]
For Project URL, we may use https://aka.ms/nugetprj. Will this be fine @karann-msft ?

Should it point to just nuget.org?

**Comment by rohit21agrawal** [comment]
why should project url not point to the github repo?

**Comment by rohit21agrawal** [comment]
please give a url for the package logo

**Comment by anangaur** [comment]
Icon: https://aka.ms/nugetlogo

I am fine either way for the project URL. In my mind project URL is the product landing page and repoUrl is other one.

**Comment by rohit21agrawal** [comment]
getting http 404 for aka.ms/nugetlogo

**Comment by rrelyea** [comment]
Sounds like the email thread went dead. Moving to 4.8.

**Comment by karann-msft** [comment]
@rohit21agrawal the logo url that @anangaur gave seems to work fine...

**Comment by karann-msft** [comment]
based on discussion with CELA, going forward any new packages that the NuGet team publishes on NuGet.org, should use the following metadata
Author = Microsoft
Copyright = © Microsoft Corporation. All rights reserved.

cc: @rrelyea @skofman1

**Comment by jainaashish** [comment]
@karann-msft @anangaur why shouldn't project url be `nuget.org`?

**Comment by anangaur** [comment]
There is often this confusion between `projectURL` and `repository` metadata fields. IMO, `projectURL` should be nuget.org and `repository` should point to the GitHub repo. We are planning to show the repository info on nuget.org, soon!

**Comment by rrelyea** [comment]
Time ran out for 15.8 and we don't have closure on all these items. Moving to 4.9.

**Comment by karann-msft** [comment]
In addition to Author = Microsoft and Copyright = © Microsoft Corporation. All rights reserved.
The package description must specify:

Microsoft holds the copyright for this NuGet package.
.NET Foundations holds the copyright to the source.

Based on discussion with @jongalloway

**Comment by karann-msft** [comment]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/NuGet.CommandLine.nuspec#L13 
it should be .NET Foundation 
not .NET Foundations
there is an extra "s"

it's my bad since I put the errant "s" in my comment above. :(

**Comment by karann-msft** [comment]
Ensure that all packages irrespective of branch/release are compliant with requirements for Microsoft packages on nuget.org and any packages generated this point on comply with all requirements listed on aka.ms/nuget

Some of them are listed below:
* The author must be just **Microsoft** <br> `<authors>Microsoft</authors>`
* The copyright must be **© Microsoft Corporation. All rights reserved.** <br> `<copyright>© Microsoft Corporation. All rights reserved.</copyright>` <br> or <br> `<copyright>&#169; Microsoft Corporation. All rights reserved.</copyright>`
* projectUrl cannot be null. <br> `<projectUrl>This must be a valid team or product URL. It can be an FWLink. This must be a permalink that will never be deprecated. This is typically your product's marketing page where users can go to understand more about the product/package.</projectUrl>` 
* licenseUrl cannot be null. <br> `<licenseUrl>This must be a valid product license URL</licenseUrl>`

**Comment by rrelyea** [comment]
@karann-msft  - The PR has comments, which I agree about that the:
Microsoft holds the copyright for this NuGet package.
.NET Foundation holds the copyright to the source.
in description is really clumsy.
 perhaps we can talk monday morning.
