### ISSUE TITLE
Argument out of range exception in NuGet console

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#652]
// Tracking TFS 1174753

Bad things happened while I was trying to use the package manager console.

 <entry>
 <record>1608</record>
 <time>2015/05/20 13:55:10.997</time>
 <type>Error</type>
 <source>Editor or Editor Extension</source>
 <description>System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: span&#x000D;&#x000A; at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)&#x000D;&#x000A; at NuGetConsole.Implementation.Console.WpfConsoleClassifier.GetClassificationSpans(SnapshotSpan span)&#x000D;&#x000A; at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.&lt;GetTags&gt;d__1.MoveNext()&#x000D;&#x000A; at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__1.MoveNext()</description>
 </entry>

**Comment by yishaigalatzer** [comment]
There are no repro steps here, I don't know what we can do about this. @csharpfritz can you please follow up with the customer?

**Comment by rmestre** [comment]
I have a similar problem installing a number of different packages, including the latest versions of Newtonsoft JSON.NET, DocumentDB, Entity Framework and a number of others.

The errror message is: 
Specified argument was out of the range of valid values.
Parameter name: supportedFrameworks

Microsoft Visual Studio Ultimate 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.6.00057
NuGet Package Manager   2.8.60318.734

**Comment by csharpfritz** [comment]
Emailed customer for additional information and repro

**Comment by csharpfritz** [comment]
@rmestre Are you still seeing this problem with the latest version of the NuGet extension? 

Note: the original report has indicated that they are not currently working in Visual Studio 2015 and have not tried to reproduce on recent versions of the NuGet extension

**Comment by yishaigalatzer** [comment]
We believe this was fixed by #555 please let us know if this still repeats after installing nuget 3.3
