### ISSUE TITLE
[Spec] Add support for trusted signers in commandline

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6524]
This follows the work in https://github.com/NuGet/Home/issues/6419 to enable users to update the repository certificates/keys/trust via commandline and UI.

Commandline is specc'd [here](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Config-schema-changes-to-enable-repository-signatures).

UI: To be done.

**Comment by mishra14** [comment]
cc: @rido-min

**Comment by zhili1208** [comment]
CommandLine is done in https://github.com/NuGet/NuGet.Client/commit/4af25d047d1b63a54608498b5dc5e5e254c73c20

**Comment by mishra14** [comment]
Punting for a formal triage based on internal discussions.

**Comment by PatoBeltran** [comment]
Closing this as this is covered by https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Config-schema-changes-to-enable-trusted-signers
