### ISSUE TITLE
Add support for storing trusted repository information into nuget config

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6525]
Follows the spec task: https://github.com/NuGet/Home/issues/6419

**Comment by mishra14** [comment]
Fixed by https://github.com/NuGet/NuGet.Client/commit/430cb7a9ec4e7f977e8947a571cdadca366cc468.

**Comment by rrelyea** [comment]
Enabled in codebase in 4.7 -- however, the commands to use it and to respect it are coming in a future release.
