### ISSUE TITLE
Update All option missing from NuGet UI

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#653]
// Tracking TFS 1178242
// Reported multiple times by many customers, listed in TFS

 where is the "update all" button?

-----

New NuGet package manager design is awful! Please, return Update all button.

-----

I cannot find an "Upgrade All" option in the NuGet package manager.

----

Where is the option to upgrade all nuget packages ( I miss the checkbox feature).

**Comment by yishaigalatzer** [comment]
Duplicate of #142
