### ISSUE TITLE
Course of action for packages that raise warnings, fail the build in the migrator

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6532]
Determine what our plan is. 
How do we report this. 

Ask in upgrade report via feedback, have an open entry point? Github issue? Feedback etc.

**Comment by karann-msft** [comment]
As we discussed, the report will have a link to open an issue on our GitHub home repo.

**Comment by nkolev92** [comment]
As Karann said. 

We will add a pointer in the report, asking users to open a github issue for any build/runtime problems they face once they switch to PR. 

In there, we will try to provide them with workarounds and/or communicate with  package authors to "fix" the problem packages. 

+ we will add some events for problem packages. 

//cc @rohit21agrawal 
I will sync up with you tomorrow on how to get these changes through to the migrator.

**Comment by rrelyea** [comment]
Done.
