### ISSUE TITLE
Package Manager Dialog sometimes doesn't reflect state of packages.config after uninstall

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#654]
Repro steps:
1) file new project console app
2) install Microsoft.Diagnostics.Tracing.EventSource.Samples samples
3) Show "Installed" packages
4) remove all the packages (in a reasonable order) 
5) UI shows all the packages gone
6) Microsoft.Diagnostics.Tracing.EventRegister is left behind in package.config but UI shows it is gone. Expected behavior: package is also gone from packages.config

7) close NuGet dialog, and reopen, now this package appears in UI
8) you can now delete it from UI

**Comment by yishaigalatzer** [comment]
We have a separate issue tracking refreshing the UI properly.

For this scenario we should make sure that `Microsoft.Diagnostics.Tracing.EventRegister` actually gets removed

**Comment by johnataylor** [comment]
We can't get a repro on 14.0.22915.0 VSCLIENT_1

**Comment by yishaigalatzer** [comment]
Verify on d14rel

**Comment by zhili1208** [comment]
didn't get a repro on 14.0.23004.0 D14Rel with latest NuGet
