### ISSUE TITLE
VS verify package signature when package is resotred from global folder for package.config

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#6542]
Repro Step:
1. Create a .net framework class lib.
2. make sure newtonsoft.json is already in .nuget/packages folder
3. install newtonsoft.json
4. remove package from solution packages folder
5. restore package.

Expect: no signature verification in restore
Actual: nuget verify signature

**Comment by PatoBeltran** [comment]
This has been fixed in https://github.com/NuGet/NuGet.Client/pull/2471
