### ISSUE TITLE
Package Manager Console and Interface in Visual Studio returns 404 for .NetCore and .Net Standard packages

### ISSUE THREAD

**Issue by AlexaCodex** [NuGet/Home#6545]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe, VS UI, Package Manager Console

NuGet.exe version (x.x.x.xxx): 4.5.1.4879

dotnet.exe --version (if appropriate): 2.1.4

VS version (if appropriate): Visual Studio is 2017 15.5.6

OS version (i.e. win10 v1607 (14393.321)): win 10 enterprise

Klondike version : v2.1.1 https://github.com/themotleyfool/Klondike/releases
## Detailed repro steps so we can see the same problem

1. Search for the nuget package through Manage Nuget Package UI  or Package Console in Visual Studio e.g dapper 1.54.0 or nunit 3.9.0

2. Select a package and click install 

You get an error

![image](https://user-images.githubusercontent.com/4513589/35926033-1f1714a0-0c1f-11e8-99a2-a1b1e41eafae.png)

I can install package from Klondike using nuget.exe but not from Visual Studio.

Other packages not .Net Core or standard works fine.

Our Klondike server is privately hosted and doesn't require authentication to download packages.

**Comment by emgarten** [comment]
@Rajshall this appears to be a configuration problem with your klondike server. I suggest checking your configuration and ensuring that the server is putting the expected resources at the URL shown.

**Comment by AlexaCodex** [comment]
@emgarten How is this working with nuget.exe? As i am able to download this using the nuget install command.

**Comment by emgarten** [comment]
@Rajshall that seems unexpected, are you using the same version of nuget.exe?  They use the same code.

**Comment by AlexaCodex** [comment]
@emgarten I am not sure how to check the Package manager console version in VisualStudio
My Nuget.exe version is : 4.5.1.4879

**Comment by emgarten** [comment]
Then it should be the exact same code executing for network requests between nuget.exe and VS. Do you have any proxy settings for VS or nuget.exe that would change things?

**Comment by AlexaCodex** [comment]
This is the fiddler log of **unsuccessful** installation of package through visual studio:
![image](https://user-images.githubusercontent.com/4513589/36053804-2a3719e8-0deb-11e8-8c30-23960967fc82.png)

This is fiddler log of **successful** installation of package when installed through nuget.exe:

![image](https://user-images.githubusercontent.com/4513589/36053931-b9fcd554-0deb-11e8-8c09-8c16423abc15.png)

I have a proxy server but afaik it is only for external websites, internal websites should be fine.
Also if the project is not .Net Core Web API, I can download packages from this server just fine using Visual Studio i.e. for .Net 4.6 framework

**Comment by emgarten** [comment]
Thanks for the trace, that is helpful. Is the difference here that in VS, packages.config projects work with your Klondike server, but PackageReference/NETCore projects fail?

**Comment by AlexaCodex** [comment]
@emgarten In VS it fails for PackageReference/Packages.config (I tired both setting for the sake if it)  settings for .Net  core application. 
The .Net 4.6 framework works with packages.config
Also these libraries are  .Net standard Libraries that are failing.

Let me know if you need anything else, i don't mind even screen sharing if that helps.

**Comment by emgarten** [comment]
From an implementation perspective, the TFM makes no difference on which code paths are executed. But the style: packages.config or PackageReference does.

**Comment by AlexaCodex** [comment]
Sorry for wasting your time, i think i have resolved it. The url was wrong in VS :-(

**Comment by emgarten** [comment]
Glad you were able to track it down, and thanks for the update on this!

**Comment by AlexaCodex** [comment]
Thanks for your help!
