### ISSUE TITLE
Add repository/commit attribute to nuspec format

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6547]
Nuspecs currently include repository type and url, this should be extended to include the commit hash.

Example:
```xml
    <repository type="git"
               url="https://github.com/NuGet/NuGet.Client"
               commit="17caacc71d2cfa40f6ce10d4f0bbec8ea68f4cda" />
```

Pack should be updated to allow passing this in from a property in the same way the repo url is set.

**Comment by joelverhagen** [comment]
Related: https://github.com/NuGet/NuGetGallery/issues/4941.

If this starts showing up in .nuspec, we could also show this on the gallery.

**Comment by emgarten** [comment]
Would *branch* be useful information also? A user could find the branch from the commit hash, but for the gallery's purposes it might be easier to just have this info in the nuspec instead of having to track it down in git.

**Comment by joelverhagen** [comment]
Branch can change over time so capturing at pack time would be great, in my opinion.

**Comment by StingyJack** [comment]
I've tinkered with using projecturl to point to the TFS build that originated the package. Perhaps a set of origination uri's for changeset/commit, branch ident, etc.  

Please no git or nuget.org specific implementations.

**Comment by emgarten** [comment]
These strings are free form, type currently allows any source control system name, so TFS should work fine.
