### ISSUE TITLE
nuget sources remove does not remove credentials if the sources is not in the user wide config

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6550]
steps - 

1. dotnet new nuget.config
2. nuget sources add -Name test -Source random -Username testuser -Password testpassword -configfile .\nuget.config
3. nuget sources remove -Name test
4. observe that the source is removed, but the credentials are left.

Culprit code is [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/PackageSource/PackageSourceProvider.cs#L431). The delete section call is only made for the top most setting which is either the user wide or machine wide config file.

**Comment by PatoBeltran** [comment]
This has been solved as part of the latest rework on the nuget.configuration code paths.
