### ISSUE TITLE
[Question] How to get all tags for package using NuGet v3 API

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#6554]
It looks like sometimes the tags displayed on the nuget.org website are not reflected in the metadata returned by the catalog API. Example: [this](https://www.nuget.org/packages/adam.jsgenerator/) has a `javascript` tag, but there is no `tags` attribute here: https://api.nuget.org/v3/catalog0/data/2015.02.01.06.22.45/adam.jsgenerator.1.1.0.json How can I reliably get the tags associated with a package?

**Comment by zhili1208** [comment]
moved to nuget.org issues
