### ISSUE TITLE
Could packages hosted on private servers become open to hackers?

### ISSUE THREAD

**Issue by tjl10** [NuGet/Home#6555]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
3.4.4

VS version (if appropriate):
2015 (14.0.25431.01 Update 3)

OS version (i.e. win10 v1607 (14393.321)):
Win10 v1709 (16299.192)

## Detailed repro steps so we can see the same problem

1. Host a package on a private nuget server.
2. Install that package in a project.
3. Open the project and observe that NuGet sends a request to nuget.org:
https://api.nuget.org/v3/registration3-gz/{my private package id}/index.json

If a bad actor were to create a package on the nuget.org gallery with the same ID as my private package, might Visual Studio offer to update to that bad version? And if the developer is not careful, could a hacker then gain some level of control over the software built by that project?

I would expect NuGet to only allow package installs from the nuget server that the package was originally installed from.
I would also expect NuGet to not leak private package ids by sending requests to nuget.org.

**Comment by tjl10** [comment]
Just read the [blog post on package signing](https://blog.nuget.org/20170914/NuGet-Package-Signing.html) which sounds like it would help this.

But is there any workaround while waiting for these features to be implemented?

**Comment by zhili1208** [comment]
nuget is using all enabled source to resolve dependency, that's why nuget send a request to nuget.org for your case. the workaround is disable nuget.org here.

**Comment by tjl10** [comment]
Is there a way today to use the nuget.org source to browse for new packages, but disable nuget.org source for existing packages?

Or change the order of the source resolution so nuget.org is only used for resolution if the package is not resolved by another source?

**Comment by zhili1208** [comment]
Unfortunately there is no way to do that today, source resolution is not one by one, all source are processing parallel
