### ISSUE TITLE
Uninstall Experience is tedious

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#656]
// Feedback from TFS 1178238

The NuGet Uninstall Experience has gotten so much worse! used to just click one time and say uninstall all the crap that came with this package and now it has me removing crap one thing at a time. 

--------

We should revisit the user experience for this to identify steps that could be simplified.

**Comment by yishaigalatzer** [comment]
This is already supported. @csharpfritz can you please update TFS, and customer issue.

![image](https://cloud.githubusercontent.com/assets/1238711/7890267/ca9ee692-05f9-11e5-9341-1da59f1d2e57.png)
