### ISSUE TITLE
Add support for requesting nomination data for projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#6575]
GetPackageSpec should block and request nomination info from the project system when there is no data present. The current behavior is to return null which ultimately causes a failed restore when project details are missing.

This requires a way to query the project system for that information instead of just waiting until it is pushed to the nomination API.

### Expected flow
Test explorer **->** NuGet **->** Project system

A request for installed packages requires the list of PackageReference entries. When the call is received NuGet should block and request the information from the project system in order to get the information.

### Actual flow
Test explorer **->** NuGet **<-** Project system

Since both arrows are incoming for NuGet, it can't block. Instead it just gives up immediately when it doesn't have the data. Other times NuGet returns out of date information.

### Examples
* Test explorer often fails to determine if a project has xunit installed because NuGet throws an exception until the project system pushes the needed info.
* Auto restore fails with an error related to missing project details. NuGet is unable to determine if all nomination info has been sent.
* Back to back package operations fail. For example: install, then uninstall. Uninstall does not see the latest project info because the project system is still processing it and will fail saying that the package isn't installed.

Relevant code:
https://github.com/NuGet/NuGet.Client/blob/7fc2573b76fceb8a007a25012027c5b829c0801a/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/NetCorePackageReferenceProject.cs#L110-L118

**Comment by nkolev92** [comment]
We have a new contract that's slightly different today: 

That, https://github.com/NuGet/Home/blob/dev/proposed/2021/BulkRestoreCoordination.md, in addition to changes in GetPackagesAsync renders this less important. 

I'm sure we'll revisit if necessary.
