### ISSUE TITLE
Unable to see my Private Server inside NuGet.Config file with docker

### ISSUE THREAD

**Issue by RamazanBIYIK** [NuGet/Home#6581]
I have ASP.Net Core 2.0 project and ı am using packages from nuget.org and My Private Server. I succesfully launch my API with visual studio. But when issue come to docker it gets complicated. It was not seeing my private server at the beginning because of NuGet.Config file was absend inside project directory. This time nuget see only 1 of sources(Nuget.org or my private server).

NuGet product used :

Package manager Console , dotnet.exe , NuGet.exe, Docker

NuGet version (x.x.x.xxx):

v4.5.1

VS version (if appropriate):
VS 17
OS version (i.e. win10 v1607 (14393.321)):
 Win 10

1.My NuGet.Config
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
	 </packageSources>
	<packageSources>
    <add key="MyPrivate" value="http://nugetserver.azurewebsites.net/nuget/Packages" />
  </packageSources>

  <apikeys>
    <add key="https://www.nuget.org" value="Some_Long_Value" />
 
  </apikeys>
  <disabledPackageSources />
</configuration>

```

2.My Dockerfile

```
FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers and NuGet.Config
COPY *.csproj ./
COPY NuGet.Config /root/.nuget/NuGet/NuGet.Config

# Copy everything else and build
COPY . ./
RUN dotnet restore

RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "MyProject.dll"]
```

I wrote the problem here because i think Docker can see my NuGet.Config file but not servers due to inappropriation inside NuGet.Config file. When ı type `docker build -t webserv .` the error pops up at Dockerfile's  `dotnet restore` command.

> MyProject.csproj : error NU1101: Unable to find packageWebApi.Utils. No packages exist with this id in source(s): nuget.org

If i add a source to NuGet.Config under  "addkey" tag 

> add key="http://nugetserver.azurewebsites.net/nuget" value="ApiKey" /

 This time ı have this error for every package inside my project:

>  Retrying 'FindPackagesByIdAsyncCore' for source 'http://nugetserver.azurewebsites.net/nuget/Packages/FindPackagesById()?id='SwaggerUi''.
  Response status code does not indicate success: 404 (Not Found).
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error : Failed to retrieve information about 'Microsoft.VisualStudio.Web.CodeGeneration.Design' from remote source 'http://nugetserver.azurewebsites.net/nuget/Packages/FindPackagesById()?id='Microsoft.VisualStudio.Web.CodeGeneration.Design''. [C:\app\MyProject.csproj]
C:\Program Files\dotnet\sdk\2.1.4\NuGet.targets(103,5): error :   Response status code does not indicate success: 404 (Not Found). [C:\app\MyProject.csproj]
The command 'cmd /S /C dotnet restore' returned a non-zero code: 1

As you can see at the NuGet.Config ı have 2 source but it says i have only one source. If ı can build and run my project with VS 17 then ı think my NuGet.Config file is correct but with Docker Commands it doesn't. Is nuget incompatible with docker or my settings are wrong. That blows my mind. Plase help.

**Comment by RamazanBIYIK** [comment]
Ok i figure it out. My NuGet.Config file was wrong. When ı delete  

 ```
<apikeys>
     <add key="https://www.nuget.org" value="Some_Long_Value" />
  </apikeys>
```
that it worked.

**Comment by venmaram** [comment]
same error. can anyone help on this issue? Thanks

**Comment by niraj-bpsoftware** [comment]
same error

**Comment by hugonavak** [comment]
Same error.

**Comment by testpbb** [comment]
same error.

**Comment by lintakumar** [comment]
same error..Pls help 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    
    <add key="enabled" value="True" />
    
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="no_proxy" value="http://ctnuget1.thisis.com/NugetFeed/nuget/Packages"/>    
  </packageSources>
</configuration>

**Comment by eaaguirren** [comment]
same error pls

**Comment by lintakumar** [comment]
My Nuget config -
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <!-- Allow NuGet to download missing packages -->
    <add key="enabled" value="True" />
    <!-- Automatically check for missing packages during build in Visual Studio -->
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="GlobalInternalFeed" value="http://test.global.com/NugetFeed/nuget"/>    
  </packageSources>
</configuration>
```

Docker File has this -
`RUN dotnet restore "Persistence.EntityFramework/Persistence.EntityFramework.csproj" --configfile "Persistence.EntityFramework/Nuget.config"
`
This worked for me

**Comment by yonahochieng** [comment]
Using the IP address of the private repo instead of the server name sorted out the problem for me. 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="CreditQuestAPIPackage" value="http://**10.XX.254.XX**:1211/nuget" />
  </packageSources>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
</configuration>
```

**Comment by yonahochieng** [comment]
> My Nuget config -
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageRestore>
>     
>     <add key="enabled" value="True" />
>     
>     <add key="automatic" value="True" />
>   </packageRestore>
>   <packageSources>
>     <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>     <add key="GlobalInternalFeed" value="http://test.global.com/NugetFeed/nuget"/>    
>   </packageSources>
> </configuration>
> ```
> 
> Docker File has this -
> `RUN dotnet restore "Persistence.EntityFramework/Persistence.EntityFramework.csproj" --configfile "Persistence.EntityFramework/Nuget.config" `
> This worked for me

Change test.global.com to IP

**Comment by VGerris** [comment]
Why on earth is this closed? How about DNS resolution is made to work, like it does for all other command I use like ping?
Please reopen this issue and address the issue if that is actually the problem.
I had this issue on Ubuntu Linux at initial run and continuously in docker.

Related seem:
https://github.com/dotnet/sdk/issues/8299
https://github.com/NuGet/Home/issues/6140

**Comment by SP-SuperPoney** [comment]
Same problem here !

**Comment by hippieZhou** [comment]
I have the same issue and fix it with this docs: [Managing NuGet Credentials in Docker Scenarios](https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md)

![image](https://github.com/NuGet/Home/assets/13598361/2b1bc969-cb1c-42fd-a9ac-2c680f83574f)
