### ISSUE TITLE
NuspecFile is not an up-to-date check input

### ISSUE THREAD

**Issue by sharwell** [NuGet/Home#6582]
## Details about Problem

NuGet product used: Visual Studio 2017 version 15.6 Preview 5

NuGet version (x.x.x.xxx): Built in

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): See above

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: Unknown

### Detailed repro steps so we can see the same problem

1. Create a project with the following configuration

    ```xml
    <PropertyGroup>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <NuspecFile>..\MyPackageSpec.nuspec</NuspecFile>
    </PropertyGroup>
    ```

2. Build the project inside VS

3. Make a change to the **MyPackageSpec.nuspec** file

4. Build the project inside VS

### Expected result

During step 4, the project builds.

### Actual result

During step 4, Visual Studio reports that the project is up-to-date.

### Solution

Add the `NuspecFile` property as an input to the fast up-to-date check:

```xml
<ItemGroup Condition="'$(GeneratePackageOnBuild)' == 'true'">
  <UpToDateCheckInput Condition="'$(NuspecFile)' != ''" Include="$(NuspecFile)" />
</ItemGroup>
```

**Comment by nkolev92** [comment]
Does not repro anymore as well. 
CLosing.
