### ISSUE TITLE
[Question] Why do some packages show up twice in the catalog API?

### ISSUE THREAD

**Issue by jamesqo** [NuGet/Home#6583]
There appear to be some packages showing up twice here: https://api.nuget.org/v3/catalog0/page0.json, e.g. `Autofac` and `Antlr`. Is there any reason for this?

**Comment by maartenba** [comment]
The catalog is basically an event stream. So whenever a change happens to a package (list, unlist, delete, intentional reflow from the NuGet team, ...), it will have an entry in there.

**Comment by mishra14** [comment]
Closing this as a question.
