### ISSUE TITLE
Should I put .mdb or .pdb files up on NuGet?

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6585]
@define-private-public commented on [Sun Feb 18 2018](https://github.com/NuGet/NuGetGallery/issues/5504)

I'm a little confused by this.  At the moment, I've got two instances of MonoDevelop configured.  One where it's generating `.pdb` files, and the other one where it's making `.mdb` files.  When packing & submitting my library, is there one that I should be giving preference to?  IIRC, they are different.

I currently develop on a Linux system, but my library is compatible with Windows & OS X.  Here's the .nuspec file too:
https://gitlab.com/define-private-public/SharpCamera/blob/develop/SharpCamera/SharpCamera.nuspec

**Comment by zhili1208** [comment]
@define-private-public mdb file is generated by xbuild and pdb file is generated by msbuild. I believe mono is moving from xbuild to msbuild now. So I think you should be giving preference to pdb files.

**Comment by define-private-public** [comment]
Okay.  At the moment I'm using `mono` as provided by their .debs (not the ones in the ubuntu repos).  It is generating .pdbs instead of .mdbs.  I'm worried if they are portable or not.  Is there some flag/magic no. in the .pdb file itself I can check to see if it's a Portable PDB?

**Comment by zhili1208** [comment]
added mono people @mrward

**Comment by mrward** [comment]
[Mono 5.0](http://www.mono-project.com/docs/about-mono/releases/5.0.0/) switched to using the Roslyn C# compiler. This generates .pdb files.

**Comment by mishra14** [comment]
@define-private-public please let us know if you are still blocked on this.

**Comment by define-private-public** [comment]
I'm using Mono 5.x right now, so it is generating PDB files,  I'm just not sure if they are portable or not.  Like I asked yesterday, is there someway I can inspect the file to tell if it is a portable PDB?

**Comment by mishra14** [comment]
@mrward do you have more info for @define-private-public ?

**Comment by mrward** [comment]
@davidkarlas ^

**Comment by DavidKarlas** [comment]
If you are using Linux or macOS your .pdb is 100% Portable .pdb, since "native .pdb" can only be generated on Windows.

**Comment by define-private-public** [comment]
Okay.  I'm good then.  Thanks!
