### ISSUE TITLE
Dotnet restore gives 401 and nothing seams to help when compse docker yml

### ISSUE THREAD

**Issue by jnormen** [NuGet/Home#6590]
I can run Dotnet restore in package-manager in VS .Net without any problem.
I can run my project in Docker from Visual Studio as well. But when I will compose my yml file the command for Dotnet Restore will give 401 against my private VSTS packages.

I have NuGet.config and I have also tried to use --configfile for Dotnet restore and pointed out my NuGHet.config but still 401...

When I ping inside an interactive docker image to api.nuget.org it works so no network problems.

And I can't find any other having just this problem that was resolved. Please really need to fix this.
(might be the wrong forum but don't know where to ask. )

my NuGet.config
`<?xml version="1.0" encoding="utf-8"?> <configuration> <packageSources> <clear /> <add key="JobOffice" value="https://joboffice.pkgs.visualstudio.com/_packaging/JobOffice/nuget/v3/index.json" /> <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" /> </packageSources> <packageSourceCredentials> <JobOffice> <add key="Username" value="<username goes here>" /> <add key="ClearTextPassword" value="<my password goes here>" /> </JobOffice> </packageSourceCredentials> </configuration>`

Steps to reproduce the issue
version: '3'

```
services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./JobOffice.Cart.WebApi.sln && dotnet publish ./JobOffice.Cart.WebApi.sln -c Release -o ./obj/Docker/publish"
docker-compose -f <thebuilder.yml> up
```
Expected behavior
To work ;)

Actual behavior
401

Output of dotnet --info
```
 .NET Command Line Tools (2.1.4)
Product Information:
Version:            2.1.4
Commit SHA-1 hash:  5e8add2190
Runtime Environment:
OS Name:     debian
OS Version:  9
OS Platform: Linux
RID:         linux-x64
Base Path:   /usr/share/dotnet/sdk/2.1.4/
Microsoft .NET Core Shared Framework Host
Version  : 2.0.5
Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
Output of docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d011701
ID: HAZG:3TIA:FI7G:N2AR:UCIT:T45P:MZQQ:NGBU:PCDL:KVEJ:CMWG:3FFF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 36
 System Time: 2018-02-20T19:12:07.338847Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mishra14** [comment]
@nkolev92 this looks like a VSTS auth issue. Can you please see if this is same as the one that you are planning to work on?

**Comment by nkolev92** [comment]
@mishra14 
Part of the auth experience, but not necessarily directly related to what I'll be looking into. 

@jnormen 
Does this happen when you're not running inside a docker image

**Comment by jnormen** [comment]
@nkolev92 
Hi, It suddenly started to work for me. Not sure if it's temporary or not. I did nothing. My keys are active in VSTS and so on. I know that I also have some random problem on Mac host in VSTS that make my dotnet restore go bananans 4 of 5 times with some socket error. But don't know if that is related. 

`An error occurred while sending the request
Error: SecureChannelFailure (One or more errors occurred.)
One or more errors occurred.
Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'..
Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.`

**Comment by nkolev92** [comment]
Hmm, weird. 

The Mac issues sound weird.
Does  --disable-parallel make a difference at all?
There were some weird issues with that, but in mono, never heard of this error with dotnet.exe

**Comment by jnormen** [comment]
@nkolev92  I can do a test with  --disable-parallel  
I know there is issues up regarding this iOS Xamarin dotnet restore issue https://github.com/Microsoft/vsts-tasks/issues/6429 one more has the problem, but no feedback at all regadring this... it's random... And I have tried different nuget versions but the same. But this is another topic. just wanted you to know if it might be related but I think not.

**Comment by nkolev92** [comment]
Yeah, they're definitely not related. 

Those exceptions would happen auth or no auth. 

If you still hit the auth issues, a fiddler trace or an equivalent would go a great way to help us investigate this.

**Comment by jnormen** [comment]
@nkolev92 can't do any fiddler in VSTS tasks on build. Regarding the odd random socket problem. 
The other problem I cannot create now. It just works :/ So if it happens again I will let you know it a new thread I guess? I have built the docker yml all day with no 401 problems at all. So maybe it was something temporary with the services in vsts I don't know :( and can't reproduce it... tried a new project as well. all works fine now.

**Comment by nkolev92** [comment]
Yeah, not sure, it's possible that there were some issues with the VSTS services. 

Yeah, feel free to open a new thread if you still face any issues. 

Unfortunately authentication issues are very hard to investigate without a reliable repro or at least a fiddler trace.

You good with closing this issue @jnormen ?

**Comment by jnormen** [comment]
@nkolev92  yes you can close it :) thank you. It still rocking today so must have been some temporary thing.
