### ISSUE TITLE
Nuget flatten true along with copyToOutput true not working

### ISSUE THREAD

**Issue by thrnkumar** [NuGet/Home#6597]
Hi,
Please find below the nuspec configuration which I tried to use to create the nuget package, but when I install this package to any consumer, the text file is placed inside the contentFiles folder and not under the root. Please check what I have done wrong and let me know:

<?xml version="1.0"?>
<package>
  <metadata minClientVersion="3.3.0">
    <id>ClassLibrary9</id>
    <version>1.0.0</version>
    <authors>nuget</authors>
    
    <owners>nuget</owners>
    
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>A content v2 example package.</description>
    <tags>contentv2 contentFiles</tags>
    
    <contentFiles>
      
      <files include="*.*" copyToOutput="true" flatten="true" />
    </contentFiles>
  </metadata>
 </package>

**Comment by mishra14** [comment]
@thrnkumar can you please give us the nuspec file that you used. From the above description it is unclear.

**Comment by thrnkumar** [comment]
@mishra14 Please have a look at this, below is the one which I have been using. Please let me know where I have done wrong.
![netstandardcapture](https://user-images.githubusercontent.com/36723215/36573133-40807eaa-1837-11e8-8975-aa5d942a4b62.PNG)

**Comment by nkolev92** [comment]
Can you provide a full package + project repro here?

What kind of project are you trying to install your package into?

NuGet does not do the copying of these files, it's up to the build targets to do it. 
For ex. UWP has some issues where contentFiles are both copied flat and non-flattened.
