### ISSUE TITLE
Why does NuGet.Build have a dependency on NuGet.CommandLine if it doesn't use it?

### ISSUE THREAD

**Issue by paulomorgado** [NuGet/Home#6598]
[NuGet,Build 2.12.0](https://www.nuget.org/packages/NuGet.Build/2.12.0) has a dependency on [NuGet.CommandLine](https://www.nuget.org/packages/NuGet.CommandLine/), which makes sense to me.

But, as far as I can tell, it doesn't use it.

Wouldn't it make sense to have a package that includes a version of NuGet.exe and adds MSBuild properties to its location?

**Comment by mishra14** [comment]
@paulomorgado you are referring to an old implementation of nuget found [here](https://github.com/NuGet/NuGet2/blob/2.13/src/Build/NuGet.Build.nuspec). We no longer use that and the package is no longer updated.

THe new implementation of NuGet.Build can be found [here](https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Build.Tasks). The package is [here](https://www.nuget.org/packages/NuGet.Build.Tasks/4.6.0-rtm-4825).

So you may be right, but we dont plan on updating that package in the future.

**Comment by paulomorgado** [comment]
Thanks, @mishra14!

Is there any documentation on what those tasks are and how to use them?

**Comment by mishra14** [comment]
Unfortunately we don't have awesome docs for our API. Your best source of information should be https://docs.microsoft.com/en-us/nuget/

I hope this helps. Feel free to reach out to us with a new issue for any specific problems...

**Comment by paulomorgado** [comment]
Well, you could start by bootstrapping the documentation and let the community chime in to add to it.
