### ISSUE TITLE
EPPlus OOXML, when generating excel file then status bar dose not showing AVG and SUM for the selected range of values.

### ISSUE THREAD

**Issue by chiragcSharp** [NuGet/Home#6599]
Hi,

I'm using EPPlus to generate the excel file for various reports, I have numeric values in one column, if I select the range of that column the bottom status bar not showing the Average and SUM of the selected values. It only shows the count of the selected range. Please find the attached Image for more details.
![issue](https://user-images.githubusercontent.com/36402952/36532906-0439646a-17e8-11e8-8789-7e6c3d5a7907.png)

**Comment by mishra14** [comment]
This issue was moved to JanKallman/EPPlus#140

**Comment by mishra14** [comment]
@chiragcSharp I have moved your issue to the EPPlus repo. NuGet does not provide support for individual packages. Please contact the package owners directly, in the future.
