### ISSUE TITLE
Signing:  SignedPackageVerifierSettings.VSClientDefaultPolicy is unused

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6601]
[`SignedPackageVerifierSettings.VSClientDefaultPolicy`](https://github.com/NuGet/NuGet.Client/blob/e2fb49fed454bcdd48c53efcb40ba26a50be761e/src/NuGet.Core/NuGet.Packaging/Signing/Verification/SignedPackageVerifierSettings.cs#L72) is not used anywhere.  Instead, `SignedPackageVerifierSettings.Default` is used and `Default` settings happen to match `VSClientDefaultPolicy` settings.

**Comment by jainaashish** [comment]
@dtivel are you planning on fixing it in 4.7? if not, can you please move it to appropriate milestone? May be put it in Backlog with right priority?

**Comment by dtivel** [comment]
This member was removed/replace over two commits (https://github.com/NuGet/NuGet.Client/pull/2139 and https://github.com/NuGet/NuGet.Client/pull/2138).
