### ISSUE TITLE
building NuGet.Client on unix: make build.sh just work

### ISSUE THREAD

**Issue by atsushieno** [NuGet/Home#6604]
## Details about Problem

First of all, it should be possible that NuGet.Client builds on Mac and Linux. The README.md prerequisites says it is Windows-only.

If I try to build NuGet.Client on Ubuntu 17.10 with "build.sh", it results in CoreCLR crash:

	/sources/NuGet.Client$ ./build.sh 
	Installing dotnet CLI
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
									 Dload  Upload   Total   Spent    Left  Speed
	100 25228  100 25228    0     0  25228      0  0:00:01 --:--:--  0:00:01 50456
	Failed to initialize CoreCLR, HRESULT: 0x80131500
	=================
	/sources/NuGet.Client/cli/dotnet msbuild build/build.proj /t:RestoreTests /p:VisualStudioVersion=15.0 /p:Configuration=Release /p:BuildNumber=1 /p:ReleaseLabel=beta
	Failed to initialize CoreCLR, HRESULT: 0x80131500
	Restore failed!!

tested with NuGet.Client master (4c0c965)

- OS: Ubuntu 17.10
- installed msbuild: Microsoft (R) Build Engine version 15.4.0.0 ( Wed Nov 29 14:56:11 UTC 2017) for Mono

It used to be that old dotnet 1.x (dotnet/cli) did not support Linux well (supported only Ubuntu 14.04 and 16.04) but IIRC dotnet 2.0 removed such distros/versions limitations, so dotnet itself should not be a blocker to fix this issue.

**Comment by nkolev92** [comment]
What are you trying to build here?
Only the core NuGet libraries are cross-plat. The whole NuGet product is not cross-plat. 
So the prerequisites are correct.

While some components are cross-plat, developing for NuGet cross-plat is not a common scenario.

If you look into the build.ps1 that builds our libraries, you will see that in the end it just calls msbuild on the build proj. 
So as long you have dotnet you can build the xplat libraries. 

Example [here](https://github.com/dotnet/source-build/blob/dev/release/2.0/repos/nuget-client.proj#L21-L32)
The source-build effort is one that enables the whole .NET Core world to be build from source on linux.

We'll be happy to take a PR for this.

**Comment by atsushieno** [comment]
> What are you trying to build here?

I am trying to build the console client.

>  Only the core NuGet libraries are cross-plat. The whole NuGet product is not cross-plat.

At least there is something that is built within this repository for Linux, otherwise the git history for `build.sh` doesn't make sense: https://github.com/NuGet/NuGet.Client/commits/dev/build.sh

>  So as long you have dotnet you can build the xplat libraries.

That is "true", but we are not trying to build "dotnet" xplat libraries. NuGet is not only about dotnet (core). We restore NuGet packages for Xamarin.Android SDK which makes it possible to build apps on Linux console.

A newer NuGet console client will be required when we are going to support custom SDK which is what I am trying to get working and get stuck because of lack of modern NuGet console client (even if not a requirement, it's a hindrance at least).

**Comment by nkolev92** [comment]
That script is used for testing .NET Core libraries only. 
NuGet.exe was never built cross-plat. 

Can you please clarify why are you trying to build nuget.exe cross-plat?
What benefit would you get from it?

**Comment by akoeplinger** [comment]
FWIW I was able to build nuget.exe on OSX with Mono 5.10 by just doing the following:

```
$ nuget restore .nuget/packages.config -PackagesDirectory packages
$ cd src/NuGet.Clients/NuGet.CommandLine
$ msbuild /restore /v:minimal /p:VisualStudioVersion=15.0
```

It only failed to ILMerge nuget.exe with all the assemblies at the end but I didn't care about that.

**Comment by atsushieno** [comment]
`nuget` console tool is used to build monodevelop. So far nuget v2 is buggy and cannot manipulate packages on case-sensitive filesystems.

**Comment by atsushieno** [comment]
I got this build failure on my same machine instead: https://gist.github.com/atsushieno/7c117aa0f1dd4819f2c02c600baec90d

**Comment by mishra14** [comment]
@atsushieno are you still facing this issue?

**Comment by atsushieno** [comment]
Yes, dotnet-install.sh (downloaded by build.sh) does not support Ubuntu 17.10 (adding an entry for it didn't make it to work, resulting in 404 for some download attempt).

**Comment by mishra14** [comment]
@atsushieno Thats an issue on dotnet/cli. Can you please file an issue at https://github.com/dotnet/cli/issues?

**Comment by mishra14** [comment]
@atsushieno  Please file an issue on dotnet cli and let us know if you are still blocked.

**Comment by atsushieno** [comment]
It is a known and long-standing dotnet/cli issue. https://github.com/dotnet/cli/issues/8474 is an example, I also had reported it a few years ago with earlier Ubuntu version (I forgot how it went). What needs to be done is to not depend on dotnet/cli script, unless dev at dotnet/cli becomes serious on that issue.

(I'm an MS internal, no need to re-tag WaitingForCustomer.)

**Comment by darkdragon-001** [comment]
My restore fails with the following error (starting from version 4.8.0):

```
PathUtil/PathUtility.cs(386,39): error CS3002: Return type of 'PathUtility.GetEntry(ZipArchive, string)' is not CLS-compliant [/nuget/NuGet.Client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj]
PathUtil/PathUtility.cs(386,59): error CS3001: Argument type 'ZipArchive' is not CLS-compliant [/nuget/NuGet.Client/src/NuGet.Core/NuGet.Common/NuGet.Common.csproj]
```

In version 4.7.0 this was only a warning, therefore I could reproduce the findings of @akoeplinger and it fails with an `ILMerge` error. Where do I find the newly built `nuget.exe` file?

_Note: I ran `msbuild` with ` /p:BuildInParallel=false` to disable parallel downloads and don't run in timeout issues._
