### ISSUE TITLE
multiple targets for the nuspec file element

### ISSUE THREAD

**Issue by mistachkin** [NuGet/Home#6605]
Currently, the "target" attribute of the file element only supports a single target directory, e.g. "build/net40".

Normally, this is fine; however, there are some cases where it would be nice to be able to support multiple target directories without causing the nupkg (zip) file to significantly increase in size.

One example of this is being able to copy an assembly to both the "build" directory (e.g. for use with a custom MSBuild task) and the "lib" directory, for use by the project itself.

I see at least two ways this could be accomplished.  One would be to modify the "target" attribute to accept a semicolon (or comma?) separated list of target directories.  Alternatively, a "targets" attribute could be added.

**Comment by rohit21agrawal** [comment]
@mistachkin  You can just specify the file element twice with same source but different target to achieve this. Here is an example:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.nuspec#L17-L18

**Comment by mistachkin** [comment]
@rohit21agrawal Funny, I've tried exactly that and it (apparently) causes the file contents to be included twice, resulting in a much larger NuPkg file.  Example can be seen here:

https://www.nuget.org/packages/Eagle.Tools.CLRv4/1.0.6543.59000

To clarify, the "Eagle.dll" is included twice, as it is needed in both contexts.

**Comment by mistachkin** [comment]
Example can be seen here:

https://www.nuget.org/packages/Eagle.Tools.CLRv4/1.0.6543.59000
