### ISSUE TITLE
Update-Package -Reinstall should reinstall, not update version numbers

### ISSUE THREAD

**Issue by bchavez** [NuGet/Home#6611]
Once upon a time, typing `Update-Package -Reinstall` in the **Package Manager Console** meant reinstalling all packages at their current versions as defined in `packages.config` and `<PackageReference>`.

After a recent update of **Visual Studio 2017** from `15.3` to `15.5.7` seems much has changed.

Now, `Update-Package -Reinstall` means ignore the version numbers defined inside `packages.config` and `<PackageReference>` and aggressively install the latest version of everything. `-Reinstall` has lost its original meaning. ***This is a problem.***

To demonstrate, create a simple **.NET Standard** library project with the following `.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="22.0.1" />
    <PackageReference Include="xunit" Version="2.3.1" />
  </ItemGroup>

</Project>
```
Notice the [**Bogus**](https://www.nuget.org/packages/Bogus/) version number `v22.0.1`. Next, run `Update-Package -Reinstall` in **Project Manager Console** in **Visual Studio 2017**:
```
PM> Update-Package -Reinstall
Restoring packages for C:\Code\Projects\Testing\BogusTest2\BogusTest2\BogusTest2.csproj...
Installing NuGet package Bogus 22.0.2.
Committing restore...
Writing lock file to disk. Path: C:\Code\Projects\Testing\BogusTest2\BogusTest2\obj\project.assets.json
Restore completed in 30.42 ms for C:\Code\Projects\Testing\BogusTest2\BogusTest2\BogusTest2.csproj.
Successfully uninstalled 'Bogus 22.0.1' from BogusTest2
Successfully installed 'Bogus 22.0.2' to BogusTest2
Executing nuget actions took 59.77 ms
Time Elapsed: 00:00:00.6596081
PM> 
```

No dice. :game_die: I want to reinstall Bogus `v22.0.1` ***as defined in*** `<PackageReference>` but instead I get `v22.0.2` (latest version). Re-opening the `.csproj` indeed, shows the `<PackageReference>` has been updated to the latest version.

![devenv_1199](https://user-images.githubusercontent.com/478118/36645557-9f0ee54e-1a1f-11e8-87a5-4d4522bf150e.png)

The situation is worse in large projects that have 100s of references against 3rd-party packages that need to be reinstalled at their current versions to avoid breaking changes. Also, it's hard to get reliable/deterministic builds on CI servers & dev boxes when package restore commands like `Update-Package -Reinstall` are not deterministic since it sources latest version numbers on NuGet.

Additionally, according to the official **Microsoft Documentation** for `Update-Package -Reinstall`:

https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#using-update-package

> Using this command is much easier than removing a package and then trying to locate the same package in the NuGet gallery with the same version. Note that the -Id switch is optional.
>
> The same command without `-reinstall` updates a package to a newer version, if applicable. The command gives an error if the package in question is not already installed in a project; that is, `Update-Package` does not install packages directly.

And more concretely, the PowerShell [**Update-Package Reference**](https://docs.microsoft.com/en-us/nuget/tools/ps-ref-update-package):
https://docs.microsoft.com/en-us/nuget/tools/ps-ref-update-package
```
Reinstall | Resintalls packages using their currently installed versions
```
... which, currently, appears **not** to be the case.

-------

## Details about Problem

NuGet product used **Package Manager Console**

NuGet version (x.x.x.xxx):
![devenv_1196](https://user-images.githubusercontent.com/478118/36645121-0c21ae70-1a19-11e8-808e-46ae9b5a38ef.png)

dotnet.exe --version (if appropriate):
```
R:\>dotnet --version
2.1.4
```

OS version (i.e. win10 v1607 (14393.321)): 

* ![winver_1202](https://user-images.githubusercontent.com/478118/36645639-bd1ba17a-1a20-11e8-9699-3fde8e240549.png)
   **Windows 7** for life. :heart: 

Worked before?
* **Yes.**

If so, with which NuGet version:
* Whatever version of NuGet was installed with **Visual Studio 2017** `15.3.*`.

### Verbose Logs

```
PM> Update-Package -Reinstall -Verbose
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='xunit'&semVerLevel=2.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='xunit'&semVerLevel=2.0.0 97ms
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Bogus'&semVerLevel=2.0.0
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Bogus'&semVerLevel=2.0.0 86ms
Running restore with 12 concurrent jobs.
Reading project file C:\Code\Projects\Testing\BogusTest2\BogusTest2\BogusTest2.csproj.
Restoring packages for C:\Code\Projects\Testing\BogusTest2\BogusTest2\BogusTest2.csproj...
Restoring packages for .NETStandard,Version=v2.0...
Resolving conflicts for .NETStandard,Version=v2.0...
Checking compatibility of packages on .NETStandard,Version=v2.0.
Checking compatibility for BogusTest2 1.0.0 with .NETStandard,Version=v2.0.
Checking compatibility for NETStandard.Library 2.0.1 with .NETStandard,Version=v2.0.
Checking compatibility for xunit 2.3.1 with .NETStandard,Version=v2.0.
Checking compatibility for Bogus 22.0.2 with .NETStandard,Version=v2.0.
Checking compatibility for Microsoft.NETCore.Platforms 1.1.0 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.core 2.3.1 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.assert 2.3.1 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.analyzers 0.7.0 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.extensibility.core 2.3.1 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.extensibility.execution 2.3.1 with .NETStandard,Version=v2.0.
Checking compatibility for xunit.abstractions 2.0.1 with .NETStandard,Version=v2.0.
All packages and projects are compatible with .NETStandard,Version=v2.0.
Installing NuGet package Bogus 22.0.2.
Committing restore...
Writing lock file to disk. Path: C:\Code\Projects\Testing\BogusTest2\BogusTest2\obj\project.assets.json
Writing cache file to disk. Path: C:\Code\Projects\Testing\BogusTest2\BogusTest2\obj\BogusTest2.csproj.nuget.cache
Restore completed in 18.44 ms for C:\Code\Projects\Testing\BogusTest2\BogusTest2\BogusTest2.csproj.
Successfully uninstalled 'Bogus 22.0.1' from BogusTest2
Successfully installed 'Bogus 22.0.2' to BogusTest2
Executing nuget actions took 59 ms
Time Elapsed: 00:00:00.6741174
```

### Sample Project
:package: [BogusTest2.zip](https://github.com/NuGet/Home/files/1756623/BogusTest2.zip)

:sunny: :crescent_moon: ***["I've been counting down the days and the nights..."](https://www.youtube.com/watch?v=uMcYRk_o82M)***

**Comment by nkolev92** [comment]
You should never need to do -Reinstall in PackageReference. 
That concept is rendered moot, because package elements are not part of the project file. 
The restore/install actions are equivalent in package reference. 

In Package Reference this has not implemented because it's not relevant. 

Duplicate of https://github.com/NuGet/Home/issues/6088.

Note, that I was not able to repro this in packages.config case. If you can repro this for packages.config, please open a new issue.

**Comment by joshmouch** [comment]
I want to do a -Reinstall because I want it to update my assembly bindings like Nuget used to with package.config.

**Comment by MikeRosoft** [comment]
I believe that in PackageReference binding redirects are generated automatically on build; you don't need to have them in an app.config file unless you want to manually add or override them. But I agree: for new-style (PackageReference) projects -Reinstall should be a no-op and display a warning instead of upgrading the package version.

**Comment by qsdfplkj** [comment]
I build a package locally. Don't want to change version numbers just tell it use the newly build file.
