### ISSUE TITLE
How to get the DLL of a dependency to be included in the build output of a project

### ISSUE THREAD

**Issue by define-private-public** [NuGet/Home#6613]
I've tried googling for this and scouring the NuGet docs and I've been hard pressed to find a solution to my problem.  I've got two packages: `libgphoto2` and `SharpCamera`.  The first is C# friendly bindings to the library of the same name, and the second is a friendlier interface to using a tethered camera.  Right now `libghoto2` doesn't have and dependencies, but `SharpCamera` has a dependency on the other.

The problem I'm running into is that I have a project that uses `SharpCamera` (and thus `libgphoto2`).  When I build my project, `SharpCamera.dll` is in the `bin/Debug|Release` folder, but `libgphoto2.dll` is not found.  This causes an issue because `SharpCamera` requires `libgphoto2` to be present to run.  I've tried fiddling with that `include` attribute of the `<dependency>` tag and including `libgphoto2.dll` in the `<files>` section, but I've had zero luck.

Right now I'm stuck to copying over `libgphoto2.dll` via an automatic build script, but that really sucks.  What am I doing wrong, and how can I fix it?  Here's a link to the .nuspec file:

https://gitlab.com/define-private-public/SharpCamera/blob/develop/SharpCamera/SharpCamera.nuspec#L17

**Comment by define-private-public** [comment]
Okay, I've figured out how to make this issue a bit better, if I set `Copy Local` to `true`, then this mitigates the issue.  Is there some way that I can have this automatically happen for my users of `SharpCamera`?

**Comment by nkolev92** [comment]
Hey @define-private-public thanks for creatring this issue.

I was unable to reproduce this. Can you please provide a full repro?
Both packages and an example csproj would be great.

Thanks.

**Comment by define-private-public** [comment]
Hi,

I can't seem to repro the issue. I may have bumped something or had a snag somewhere else.  I'm sorry for not double checking this in a clean solution.

**Comment by nkolev92** [comment]
@define-private-public 
No worries, happy it's working fine for you now. 

Thanks for getting back to us.
