### ISSUE TITLE
Cannot update to 2.1.0-preview1-final

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6617]
_From @mhosman on February 27, 2018 21:26_

## Steps to reproduce
Update from 2.0.5 to 2.1.0-preview-final using NuGet Administrator (Preview releases included).

## Expected  behavior
Update to 2.1.0-preview-final

## Actual behavior
Error: Restore package failed (no inner errors, no extra information)

## Environment data
`dotnet --info` output:

Herramientas de la línea de comandos .NET (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5

  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

_Copied from original issue: dotnet/cli#8694_

**Comment by rrelyea** [comment]
@mhosman - can you clarify the repro steps....

I not sure how to do this: "Update from 2.0.5 to 2.1.0-preview-final using NuGet Administrator (Preview releases included)." 
what is NuGet Administrator? etc...

**Comment by rrelyea** [comment]
@mhosman - which type of app were you trying to upgrade?? When I try this with a asp.net core 2.0 app, it starts with:
`    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />`

However, if I create a new Asp.net core 2.1 app, it has the following package in it:
`    <PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-preview1-final" />`

updating the Microsoft.AspNetCore.All to 2.1.0-preview1-final didn't work properly...restore fails.
However, if you change your targetframework to netcoreapp2.1 first, it seemed to succeed.

Would love to understand the exact scenario you were trying...

**Comment by rrelyea** [comment]
From asp.net team...need to change targetframework from netcoreapp2.0 to netcoreapp2.1 if you want to use 2.1 packages.

NuGet has a backlog task to improve search and update to only show compatible packages...this experience will improve then.
