### ISSUE TITLE
[Test Failure][Signing] Package was changed when timestamp signing certificate does not satisfy certificate requirements

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#6627]
## Details about Problem
NuGet Version: Dev 4969
VS Version: D15.7 27427.00
OS Version: RS3_Release 16299.15.170928-1534
Note: It doesn’t repro on D15.6 27427.00 + NuGet Client Release-4.6.0-RTM 4964.

## Detailed repro steps so we can see the same problem
1.	Create a new package.
2.	Create a new test certificate:  .\CreateTestCertificate.ps1 –AddAsTrustedRootAuthority.
3.	Sign the package:  NuGet.exe sign “PackageFilePath” -CertificatePath “PfxFilePath” -Timestamper http://freetsa.org/tsr.

## Expected:
The original package was not changed and verifying should tell user the package is not signed as below screenshot.
![expected](https://user-images.githubusercontent.com/20632625/36835965-d550f3c8-1d2f-11e8-880d-5404fe99c030.png)
## Actual:
Package was changed and the verifying errors are not the expected as below screenshot.
![actual](https://user-images.githubusercontent.com/20632625/36836014-f713ac44-1d2f-11e8-9ab6-0f39502c091d.png)

**Comment by rrelyea** [comment]
@PatoBeltran - is this related to the fixes you were working on yesterday?
/cc @dtivel
