### ISSUE TITLE
Can NuGet.exe take a RestoreGraphProjectInput list of projects like the MSBuild restore task?

### ISSUE THREAD

**Issue by cclauson** [NuGet/Home#6641]
The MSBuild restore task allows a semicolon separated list of projects to restore to be passed to it (RestoreGraphProjectInput), is there any syntax for passing this to NuGet.exe from the command line?  If not, can I request this feature?

**Comment by PatoBeltran** [comment]
Hey @cclauson thanks for taking the time to open this issue. NuGet.exe supports solutions to restore multiple projects. You can just pass the solution path to the restore command and it will restore all projects there. If you want more customization that is available in MSBuild there is a way to pass MSBuild arguments to nuget.exe with the `NUGET_RESTORE_MSBUILD_ARGS` environment variable. You can see more about this at https://docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
