### ISSUE TITLE
nuget.exe verify -signature is slow

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6643]
Validating 48 signed packages, using the same author and timestamp CA certificates took more than 5 minutes. 

We expect the OCSP responses are cached at the process level, so the verification should be as fast as calculating the hash and comparing with the signature digest.

**Comment by dtivel** [comment]
Reopening to track the [4.6.x fix](https://github.com/NuGet/NuGet.Client/pull/2088).
