### ISSUE TITLE
nuget.exe verify -Signatures p/invokes into Windows APIs when verifying timestamp signature hash

### ISSUE THREAD

**Issue by akoeplinger** [NuGet/Home#6652]
I'm currently working on fixing issues found when running `nuget.exe verify -Signatures` under Mono on OSX/Linux.

I noticed that in [VerificationUtility.cs#L111](https://github.com/NuGet/NuGet.Client/blob/625af6d87951a1f0c68e6e3c4ac440a627e7503b/src/NuGet.Core/NuGet.Packaging/Signing/Utility/VerificationUtility.cs#L111) when getting the signature hash you're calling [PrimarySignature.cs#L106-L109](https://github.com/NuGet/NuGet.Client/blob/625af6d87951a1f0c68e6e3c4ac440a627e7503b/src/NuGet.Core/NuGet.Packaging/Signing/Signatures/PrimarySignature.cs#L106-L109) which uses native Windows APIs.

That obviously won't work on other platforms so I'm curious what the plans for this are.

/cc @marek-safar

**Comment by nkolev92** [comment]
//cc @dtivel @PatoBeltran

**Comment by dtivel** [comment]
Cross platform support is scheduled later.  (See the Roadmap section [here](https://blog.nuget.org/20170914/NuGet-Package-Signing.html).)

For now, NuGet should not attempt signed package verification in this scenario.

**Comment by dtivel** [comment]
CC @rido-min, @rrelyea
