### ISSUE TITLE
Unresolveable warnings about packing source files with same name

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#6653]
### Details about Problem
NuGet product used: dotnet CLI
dotnet.exe --version (if appropriate): 2.1.300-preview2-008251
Worked before? Not sure

### Repro
1. Clone this repo: https://github.com/aspnet/Diagnostics/tree/4a098af457b16537408d5f90d3019f73fa595dfa
2. Run `build.cmd /t:package`

### Result

Pack issues warning because we have `IncludeSource=true` and there are several files with the same file name. I cannot figure out how to workaround this.

> C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008251\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : File 'C:\dev\aspnet\Diagnostics\src\shared\AttributeValue.cs' is not added because the package already contains file 'src\Microsoft.AspNetCore.Diagnostics\AttributeValue.cs' [C:\dev\aspnet\Diagnostics\src\Microsoft.AspNetCore.Diagnostics\Microsoft.AspNetCore.Diagnostics.csproj]
C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008251\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : File 'C:\dev\aspnet\Diagnostics\src\shared\BaseView.cs' is not added because the package already contains file 'src\Microsoft.AspNetCore.Diagnostics\BaseView.cs' [C:\dev\aspnet\Diagnostics\src\Microsoft.AspNetCore.Diagnostics\Microsoft.AspNetCore.Diagnostics.csproj]
C:\Users\namc\.dotnet\x64\sdk\2.1.300-preview2-008251\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : File 'C:\dev\aspnet\Diagnostics\src\shared\HelperResult.cs' is not added because the package already contains file 'src\Microsoft.AspNetCore.Diagnostics\HelperResult.cs' [C:\dev\aspnet\Diagnostics\src\Microsoft.AspNetCore.Diagnostics\Microsoft.AspNetCore.Diagnostics.csproj]

For example, one file comes from this:
https://github.com/aspnet/Diagnostics/blob/4a098af457b16537408d5f90d3019f73fa595dfa/src/shared/HelperResult.cs

The other comes in as a contentfile from this package:
https://github.com/aspnet/Common/blob/f2162984a113dac201c8ebee508049bdff9bc1ad/shared/Microsoft.Extensions.RazorViews.Sources/HelperResult.cs

### Verbose Logs
[msbuild.binlog.zip](https://github.com/NuGet/Home/files/1794679/msbuild.binlog.zip)
![image](https://user-images.githubusercontent.com/2696087/37174484-7a563eb4-22cb-11e8-8169-f17395763581.png)

### Sample Project

https://github.com/aspnet/Diagnostics/tree/4a098af457b16537408d5f90d3019f73fa595dfa

**Comment by PatoBeltran** [comment]
@rohit21agrawal can you take a look into this?

**Comment by rohit21agrawal** [comment]
@natemcmaster If you are looking at hiding these warnings, then these warnings are now suppressible with latest version of pack using ```SuppressWarnings``` property in csproj file.

I am not sure what Pack can do here to be smarter about this , I am open to suggestions.

**Comment by natemcmaster** [comment]
How hard would it be to support setting some kind of metadata value like `PackagePath` on compile items?

Also, it looks like `TargetPath` varies between the two items. I'm not sure how that is getting set and if it's guaranteed to be unique.

**Comment by natemcmaster** [comment]
Re: SuppressWarnings. 

Interesting, I didn't see that in https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets. Is that defined somewhere else? `SuppressWarnings` sounds a little generic, so I'd want to make sure first that this property won't suppress warnings in other targets such as the compiler or restore.

**Comment by rohit21agrawal** [comment]
EDIT: I meant NoWarn when I said SuppressWarnings. This property takes a semi-colon separated list of error codes and works for all warnings thrown by msbuild , which now includes Pack. Pack warnings will have a unique warning code that you can use to suppress them.

Pack now also respects WarningsAsErrors and TreatWarningsAsErrors

This work was done as part of : https://github.com/NuGet/NuGet.Client/pull/2013

**Comment by rohit21agrawal** [comment]
> How hard would it be to support setting some kind of metadata value like PackagePath on compile items?

Depends what is the scenario for including the source in the package? The Pack target tries to preserve the relative directory structure of the source file and uses that to construct the target path in the package. We can support PackagePath on Compile ItemGroup types, but I can't promise a timeline for this.

**Comment by natemcmaster** [comment]
> Depends what is the scenario for including the source in the package?

It's only a problem for the .symbols.nupkg file. We set `<IncludeSource>true</IncludeSource>`.

> Pack now also respects WarningsAsErrors and TreatWarningsAsErrors

Interesting. We have TreatWarningsAsErrors set to true, but this is still only a warning. Should it be raised to an error? 

Also, there is no warning code associated with this, so I'm not sure what to add to `<NoWarn>`.
```
NuGet.Build.Tasks.Pack.targets(198,5): warning : File 'C:\dev\aspnet\Diagnostics\src\shared\AttributeValue.cs' is not added because the package already contains file 'src\Microsoft.AspNetCore.Diagnostics\AttributeValue.cs'
```

**Comment by rohit21agrawal** [comment]
It looks like you this fix hasn’t yet been merged to dotnet cli and sdk

**Comment by natemcmaster** [comment]
So, I researched a little what is going on under the hood. I recommend you use `TargetPath`. It's less likely you'll have a conflict when using this value, and it will also be automatically set to `Link`, which is a well-known convention used when pulling in files from directories not under the project root.

By the way, you may be able to use `TargetPath` and skip your implementation of path normalization when it is present. If your SourceFile item came from `SourceFilesProjectOutputGroupOutput`, then MSBuild has already taken care of normalizing the path to the project root using the `<AssignTargetPath>` task. 
cref https://github.com/Microsoft/msbuild/blob/4037f0694eee49321d61f4453fade907f71e6a9a/src/Tasks/Microsoft.Common.CurrentVersion.targets#L5598
https://github.com/Microsoft/msbuild/blob/master/src/Tasks/AssignTargetPath.cs#L40

It's still possible someone could create a .csproj file that produces conflicting TargetPath values, but if so, their Solution Explorer in VS wouldn't be working correctly either. Visual Studio has safeguards to prevent users from doing this. If you try to add a file to a project using "Add as Link", VS will not allow it if it would cause a conflict in TargetPath.

**Comment by natemcmaster** [comment]
So, was this made an error in recent versions of NuGet? Our build started failing with error NU5118 

> C:\b\w\6e78c7aba2f17cd5\.dotnet\x64\sdk\2.1.300-preview2-008407\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(198,5): error NU5118: File 'C:\b\w\6e78c7aba2f17cd5\modules\Diagnostics\src\shared\AttributeValue.cs' is not added because the package already contains file 'src\Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore\AttributeValue.cs'

FYI @ryanbrandenburg @muratg @Eilon - this may block us from moving forward to the preview2 SDK.

**Comment by rohit21agrawal** [comment]
@natemcmaster this is a warning. It's probably being upgraded to an error because of your project file settings. You can suppress this warning like you suppress any other msbuild warning using the warning code listed in the log.

**Comment by natemcmaster** [comment]
I see. We will have to suppress to workaround for now, but is there anyway we can properly resolve the real issue? We want two files named "AttributeValue.cs" in our symbols package, but don't have a way to tell /t:Pack how to differentiate between the two

**Comment by rohit21agrawal** [comment]
i like the solution you posted as part of [comment](https://github.com/NuGet/Home/issues/6653#issuecomment-371984378) , but i am not sure how quickly we can prioritize this. If you want to take a shot at sending a PR, i would be happy to get it in.

**Comment by natemcmaster** [comment]
If I get a few minutes, I might be able to make a PR, but I can't promise timeliness on this. For now, we've decided to disable IncludeSource to workaround. Turns out we don't need our source code in our .symbols.nupkg files now that we have source link enabled.

**Comment by natemcmaster** [comment]
I no longer need changes here since we have stopped using the IncludeSource feature altogether. The bug still exists, but I don’t care anymore if you fix it or not, so I’m closing this.
