### ISSUE TITLE
credentials not used

### ISSUE THREAD

**Issue by let-thomas** [NuGet/Home#6655]
Hi,
we are willing to use artifactory as nuget storage. We do have there private repo which requires login (certificate chain ends with self signed cert).
Nuget.exe is not able to download/install package. Neither restore.
nuget install <packagename>
Output:
Feeds used:
  https://servername.com/artifactory/api/nuget/tsupocnuget
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installing package 'packagename' to 'c:\work\tsu'.
  GET https://servername.com/artifactory/api/nuget/tsupocnuget/FindPackagesById()?id='packagename'&semVerLevel=2.0.0
  OK https://servername.com/artifactory/api/nuget/tsupocnuget/FindPackagesById()?id='packagename'&semVerLevel=2.0.0 55ms
Unable to find package 'packagename'

Interesting is push works fine!
nuget.exe push Newtonsoft.Json.11.0.1\Newtonsoft.Json.11.0.1.nupkg -Source etb
Pushing Newtonsoft.Json.11.0.1.nupkg to 'https://servername.com/artifactory/api/nuget/tsupocnuget'...
  PUT https://servername.com/artifactory/api/nuget/tsupocnuget/
  Created https://servername.com/artifactory/api/nuget/tsupocnuget/ 2305ms
Your package was pushed.

Repo work fine, see test by curl:
CASE 1 - without usr/passwd
curl -k -v https://<servername.com>/artifactory/api/nuget/nuget-gallery/FindPackagesById()?id='<packagename>'&semVerLevel=2.0.0
Output:
< HTTP/1.1 200 OK
< Date: Fri, 09 Mar 2018 15:59:50 GMT
< Server: Artifactory/4.16.0
< X-Artifactory-Id: 296e457e22b3a553:65dee1fd:161900ffee3:-8000
< DataServiceVersion: 2.0
< Content-Type: application/atom+xml;charset=utf-8
< Transfer-Encoding: chunked
<
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom" xml:base="https://servername.com/artifactory/api/nuget/nuget-gallery/">
  <title type="text"></title>
  <id>http://schemas.datacontract.org/2004/07/</id>
  <updated>2018-03-09T15:59:50Z</updated>
  <link rel="self" href="https://www.nuget.org/api/v2/Packages"/>
  <m:count>0</m:count>
  <author>
    <name></name>
  </author>
</feed>* Connection #0 to host servername.com left intact
'semVerLevel' is not recognized as an internal or external command,
operable program or batch file.

CASE 2 - with username/pwd:
curl --user <user>:<pwd_with_!> -k -v https://<servername.com>/artifactory/api/nuget/tsupocnuget/FindPackagesById()?id='<packagename>'&semVerLevel=2.0.0
Output:
< HTTP/1.1 200 OK
< Date: Fri, 09 Mar 2018 16:01:55 GMT
< Server: Artifactory/4.16.0
< X-Artifactory-Id: 296e457e22b3a553:65dee1fd:161900ffee3:-8000
< DataServiceVersion: 2.0
< Content-Type: application/atom+xml;charset=utf-8
< Transfer-Encoding: chunked
<
<?xml version='1.0' encoding='UTF-8'?>
<feed xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom" xml:base="https://servername.com/artifactory/api/nuget/tsupocnuget/">
  <title type="text"></title>
  <id>http://schemas.datacontract.org/2004/07/</id>
  <updated>2018-03-09T16:01:55Z</updated>
  <link rel="self" title="FindPackagesById" href="FindPackagesById"/>
  <entry>
    <id>https://servername.com/artifactory/api/nuget/tsupocnuget/Packages(Id='packagename',Version='18.1.0.3')</id>
    <title type="text">packagename</title>
    <summary type="text">blablabla</summary>
    <updated>2018-02-28T18:04:10Z</updated>
    <author>
      <name>Windows User</name>
    </author>
    <link rel="edit" title="V2FeedPackage" href="Packages(Id='packagename',Version='18.1.0.3')"/>
    <link rel="self" title="V2FeedPackage" href="Packages(Id='packagename',Version='18.1.0.3')"/>
    <category term="NuGetGallery.OData.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
    <content type="application/zip" src="https://servername.com/artifactory/api/nuget/tsupocnuget/Download/packagename/18.1.0.3"/>
    <m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">
      <d:lastUpdated>2018-02-28T18:04:10</d:lastUpdated>
      <d:Version>18.1.0.3</d:Version>
      <d:Copyright>Copyright ┬ę Windows User 2015</d:Copyright>
      <d:Created m:type="Edm.DateTime">2018-02-28T18:04:10</d:Created>
      <d:Dependencies>MongoDB.Bson:2.4.4:|Newtonsoft.Json:6.0.8:</d:Dependencies>
      <d:Description>bla bla bla</d:Description>
      <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
      <d:IsLatestVersion m:type="Edm.Boolean">false</d:IsLatestVersion>
      <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">false</d:IsAbsoluteLatestVersion>
      <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
      <d:Language m:null="true"/>
      <d:Published m:type="Edm.DateTime">2018-02-28T18:04:10</d:Published>
      <d:PackageHash>uBoGag2NNzIWSbMf3Cr4sLZcPa9etPrHU5KCm+D0bUXZ0mzQv6LyBu6zDEIQm1XYPfOhITV3CVz+ONBgiAnURg==</d:PackageHash>
      <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
      <d:PackageSize m:type="Edm.Int64">31164</d:PackageSize>
      <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
      <d:Title>packagename</d:Title>
      <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
      <d:Authors>Windows User</d:Authors>
      <d:MinClientVersion m:null="true"/>
    </m:properties>
  </entry>
  <entry>
    <id>https://servername.com/artifactory/api/nuget/tsupocnuget/Packages(Id='packagename',Version='18.1.0.4')</id>
    <title type="text">packagename</title>
    <summary type="text">bla bla banana</summary>
    <updated>2018-02-28T18:18:44Z</updated>
    <author>
      <name>Windows User</name>
    </author>
    <link rel="edit" title="V2FeedPackage" href="Packages(Id='packagename',Version='18.1.0.4')"/>
    <link rel="self" title="V2FeedPackage" href="Packages(Id='packagename',Version='18.1.0.4')"/>
    <category term="NuGetGallery.OData.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme"/>
    <content type="application/zip" src="https://serername.com/artifactory/api/nuget/tsupocnuget/Download/packagename/18.1.0.4"/>
    <m:properties xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices">
      <d:lastUpdated>2018-02-28T18:18:44</d:lastUpdated>
      <d:Version>18.1.0.4</d:Version>
      <d:Copyright>Copyright ┬ę Windows User 2015</d:Copyright>
      <d:Created m:type="Edm.DateTime">2018-02-28T18:18:44</d:Created>
      <d:Dependencies>MongoDB.Bson:2.4.4:|Newtonsoft.Json:6.0.8:</d:Dependencies>
      <d:Description>bla bla bla</d:Description>
      <d:DownloadCount m:type="Edm.Int32">0</d:DownloadCount>
      <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
      <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
      <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
      <d:Language m:null="true"/>
      <d:Published m:type="Edm.DateTime">2018-02-28T18:18:44</d:Published>
      <d:PackageHash>HbVu9wPXBkUeA9ddhI2lcS6zbcAk3eH+GJRFYrsZEsTE8+8E/5uo+Lf6xibVjlzv0h4tKwYM2ZFtRXRaX1qX/g==</d:PackageHash>
      <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
      <d:PackageSize m:type="Edm.Int64">31560</d:PackageSize>
      <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
      <d:Title>packagename</d:Title>
      <d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
      <d:Authors>Windows User</d:Authors>
      <d:MinClientVersion m:null="true"/>
    </m:properties>
  </entry>
</feed>* Connection #0 to host servername.com left intact
'semVerLevel' is not recognized as an internal or external command,
operable program or batch file.

## Details about Problem
NuGet.exe versions tested: 3.4.4, 3.5.0, 4.4.1, 4.5.1, 4.6.0
OS: win10 v1703

**Comment by let-thomas** [comment]
The issue is:
Artifactory is set up to work only with authenticate users.
API key is defined in nuget.config. But whole this does not work until I store to nuget.config also username and password as plain text. Why is apikey not used for restore automatically? It seems artifactory replies with 0 artifacts found when user not authenticated (apikey is not used). 
Partial help is to check in artifactory force authentication.

**Comment by nkolev92** [comment]
Hey @let-thomas 

Sorry for the delayed response. 

API Keys are only used for pushes, while package source credentials can be used for all purpsoes: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials
