### ISSUE TITLE
VS UI and PMC take 30min to see new package (nuget.exe sees it right away)

### ISSUE THREAD

**Issue by JVimes** [NuGet/Home#6657]
## Details about Problem

I published a new version of a package to a private ProGet server. Nuget.exe sees the new version right away, but VS UI and Package Manager Console take 30 minutes or so to see the new version. The whole situation worked fine until recently.

Here's output showing the difference right after publishing (note the version number difference):

	PSPM> Find-Package Company.Resources.Controls

	Id                                  Versions                                 Description                                                                                                                                                       
	--                                  --------                                 -----------                                                                                                                                                       
	Company.Resources.Controls            {15.2.0}                                 UI stuff useful across Company applications.       

	PSPM> Nuget.exe list Company.Resources.Controls
	Company.Resources.Controls 15.3.0

**NuGet version:** Package Manager Console Host 4.6.0.4964, NuGet.exe 4.6.0.4971

**VS version (if appropriate):** 15.6.1

**Worked before?:** Yes. 15.5.7

## Detailed repro steps so we can see the same problem

1. Publish a new package

2. Click "refresh" in VS UI (or check using `Find-Package` in Package Manager Console)

Actual: new version doesn't show up for 30min

Expected: new version shows up as soon as I click "refresh"

## Other suggested things

Clicking "Clear All NuGet Cache(s)" causes VS UI and PMC to see the new version right away. Otherwise I have to wait a half hour.

### Verbose Logs

How do you get logs from VS UI/Package Manager Console? Nuget.exe works fine.

**Comment by JVimes** [comment]
Do the VS clients use a different server API than nuget.exe?

**Comment by jainaashish** [comment]
was it working with previous versions like 15.5 or 15.4?

**Comment by JVimes** [comment]
@jainaashish I just verified, yes. I downgraded to VS 15.5.7, and the problem went away. I re-upgraded to latest, and the problem appeared again.

**Comment by jainaashish** [comment]
I couldn't repro it with 15.6.1 release. Can you capture the fiddler trace when you see this issue and send it to us? Publish a new package, and wait once package is validated and indexed on NuGet.org then refresh on PM UI. When you refresh, you will see a http call to https://api-v2v3search-0.nuget.org/ host in your fiddler.

**Comment by JVimes** [comment]
I'm using [ProGet](https://inedo.com/proget/download) (freemium NuGet server). Nothing was shown in Fiddler when I clicked the refresh button. The Browse tab got a response showing the new package version, `16.0.1`, while the UI still shows the old version `16.0.0`. VS 15.6.2 just rolled out to me, same behavior.

Here's the HTTP transaction:

```
GET http://elbonia-packages.company.com/nuget/NuGet/Search()?$filter=IsLatestVersion&searchTerm='Controls'&targetFramework='net46'&includePrerelease=false&$skip=0&$top=26&semVerLevel=2.0.0 HTTP/1.1
Accept: application/atom+xml, application/xml
user-agent: NuGet VS VSIX/4.6.0 (Microsoft Windows NT 10.0.17115.0, VS Community/15.0)
X-NuGet-Client-Version: 4.6.0
Accept-Language: en-US
Host: elbonia-packages.company.com
Accept-Encoding: gzip, deflate


HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 5461
Content-Type: application/atom+xml
Server: Microsoft-HTTPAPI/2.0
X-AspNet-Version: 4.0.30319
X-UA-Compatible: IE=edge
X-ProGet-Version: 5.0.10.5
Date: Tue, 13 Mar 2018 23:31:42 GMT

<?xml version="1.0" encoding="utf-8"?>
<feed xml:base="http://elbonia-packages.company.com/nuget/NuGet/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
	<title type="text">Packages</title>
	<id>http://elbonia-packages.company.com/nuget/NuGet/Search()/</id>
	<updated>2018-03-13T23:31:42Z</updated>
	<link rel="self" title="Search" href="Search" />
	<entry>
		<id>http://elbonia-packages.company.com/nuget/NuGet/Packages(Id='company.Resources.Controls',Version='16.0.1')</id>
		<title type="text">company.Resources.Controls</title>
		<summary type="text"/>
		<updated>2018-03-13T23:21:32Z</updated>
		<author>
			<name>company foo bar, LLC.</name>
		</author>
		<link rel="edit-media" title="Package" href="Packages(Id='company.Resources.Controls',Version='16.0.1')/$value" />
		<link rel="edit" title="Package" href="Packages(Id='company.Resources.Controls',Version='16.0.1')" />
		<category term="NuGet.Server.DataServices.Package" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<content type="application/zip" src="http://elbonia-packages.company.com/nuget/NuGet/package/company.Resources.Controls/16.0.1" />
		<m:properties xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
			<d:Version>16.0.1</d:Version>
			<d:Title>company.Resources.Controls</d:Title>
			<d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
			<d:Description>UI stuff useful across company applications.</d:Description>
			<d:ReleaseNotes/>
			<d:Summary/>
			<d:ProjectUrl/>
			<d:IconUrl/>
			<d:LicenseUrl/>
			<d:Copyright>Copyright © company foo bar 2017</d:Copyright>
			<d:Tags/>
			<d:Dependencies/>
			<d:IsLocalPackage m:type="Edm.Boolean">true</d:IsLocalPackage>
			<d:Created m:type="Edm.DateTime">2018-03-13T23:21:32.0570000Z</d:Created>
			<d:Published m:type="Edm.DateTime">2018-03-13T23:21:32.0570000Z</d:Published>
			<d:PackageSize m:type="Edm.Int64">65213</d:PackageSize>
			<d:PackageHash>79bNqRVAPieEZH25JWYSksh/ir2iEgZReJ+Q49uk7oIczn5H1rcKLolajsxYuVz3+89CxvfuT6opmznKXrtgMQ==</d:PackageHash>
			<d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
			<d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
			<d:IsProGetHosted m:type="Edm.Boolean">true</d:IsProGetHosted>
			<d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
			<d:IsCached m:type="Edm.Boolean">false</d:IsCached>
			<d:NormalizedVersion>16.0.1</d:NormalizedVersion>
			<d:Listed m:type="Edm.Boolean">true</d:Listed>
			<d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
			<d:HasSymbols m:type="Edm.Boolean">true</d:HasSymbols>
			<d:HasSource m:type="Edm.Boolean">true</d:HasSource>
			<d:DownloadCount m:type="Edm.Int32">75</d:DownloadCount>
			<d:VersionDownloadCount m:type="Edm.Int32">0</d:VersionDownloadCount>
		</m:properties>
	</entry>
	<entry>
		<id>http://elbonia-packages.company.com/nuget/NuGet/Packages(Id='company.Engineering.Controls',Version='0.2.1')</id>
		<title type="text">company.Engineering.Controls</title>
		<summary type="text"/>
		<updated>2018-02-27T22:56:10Z</updated>
		<author>
			<name>company foo bar, LLC.</name>
		</author>
		<link rel="edit-media" title="Package" href="Packages(Id='company.Engineering.Controls',Version='0.2.1')/$value" />
		<link rel="edit" title="Package" href="Packages(Id='company.Engineering.Controls',Version='0.2.1')" />
		<category term="NuGet.Server.DataServices.Package" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<content type="application/zip" src="http://elbonia-packages.company.com/nuget/NuGet/package/company.Engineering.Controls/0.2.1" />
		<m:properties xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
			<d:Version>0.2.1</d:Version>
			<d:Title>company.Engineering.Controls</d:Title>
			<d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
			<d:Description>Description</d:Description>
			<d:ReleaseNotes/>
			<d:Summary/>
			<d:ProjectUrl/>
			<d:IconUrl/>
			<d:LicenseUrl/>
			<d:Copyright>Copyright © company foo bar, LLC. 2018</d:Copyright>
			<d:Tags/>
			<d:Dependencies>company.Resources.Controls:13.1.0</d:Dependencies>
			<d:IsLocalPackage m:type="Edm.Boolean">true</d:IsLocalPackage>
			<d:Created m:type="Edm.DateTime">2018-02-27T22:56:10.4500000Z</d:Created>
			<d:Published m:type="Edm.DateTime">2018-02-27T22:56:10.4500000Z</d:Published>
			<d:PackageSize m:type="Edm.Int64">16591</d:PackageSize>
			<d:PackageHash>UrhLvmb8RRSUPCq4d4y1uFiwgVBRm8YtTxBW4CquWU3pK0ZwdEURKj9nCKctApuHRspl3u/HcJFKmOEcN+pRNQ==</d:PackageHash>
			<d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
			<d:IsAbsoluteLatestVersion m:type="Edm.Boolean">true</d:IsAbsoluteLatestVersion>
			<d:IsProGetHosted m:type="Edm.Boolean">true</d:IsProGetHosted>
			<d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
			<d:IsCached m:type="Edm.Boolean">false</d:IsCached>
			<d:NormalizedVersion>0.2.1</d:NormalizedVersion>
			<d:Listed m:type="Edm.Boolean">true</d:Listed>
			<d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
			<d:HasSymbols m:type="Edm.Boolean">true</d:HasSymbols>
			<d:HasSource m:type="Edm.Boolean">true</d:HasSource>
			<d:DownloadCount m:type="Edm.Int32">7</d:DownloadCount>
			<d:VersionDownloadCount m:type="Edm.Int32">4</d:VersionDownloadCount>
		</m:properties>
	</entry>
</feed>
```

**Comment by jainaashish** [comment]
if this is your public feed then can you give me a repro? And are you saying Browse tab shows new version but install/update tab doesn't?

**Comment by JVimes** [comment]
@jainaashish It's my company's private repo, unfortunately. It might be faster for you to install ProGet locally ([download](https://inedo.com/proget/download)), but I'll try to set up up a public repository somewhere if your time is limited.

As for the browse tab, it shows the old version. Everywhere in Visual Studio shows the old version (UI, PowerShell). Only nuget.exe shows the new version.

**Comment by johnegbert** [comment]
Have same issue here. Just seem like a caching issue. Please expire cache when refresh button is pressed.

**Comment by jainaashish** [comment]
@JVimes that's ok I could repro it locally for install/update tabs. But browse tab always got the latest package version. So can you again try with browse tab? And with browse tab only, you can update existing package version, it shows a up arrow right there on the package which will allow you to update that package. You can use this workaround for now.

**Comment by JVimes** [comment]
@jainaashish Thanks for looking into it. I definitely do not see the new version on the Browse tab (screenshot below). Race condition, maybe? 🤔 My workaround is `Install-Package` passing the new version via `-Version` arg (even though `Find-Package` doesn't show it).
![image](https://user-images.githubusercontent.com/6148201/37499595-2d970738-288a-11e8-9683-0a43984abf62.png)
