### ISSUE TITLE
NU1103 error message lists oldest versions, not newest versions

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#6658]
Follow-up to in-person meeting about https://github.com/dotnet/cli/issues/8485

The error message when restoring using wildcards shows the oldest version of the package, not the newest.

**Repro**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dotnet-watch" Version="*" />
  </ItemGroup>

</Project>
```
`dotnet restore`

We have two versions of dotnet-watch on nuget.org right now, 2.1.0-preview1-final, and 0.0.1-alpha.

0.0.1-alpha was a placeholder to squat on the package name, and is unlisted on nuget.org, so we would like to see 2.1.0-preview1-final in the error message instead.

**Expected**
```
/private/tmp/test1/test1.csproj : error NU1103: Unable to find a stable package dotnet-watch with version 
/private/tmp/test1/test1.csproj : error NU1103:   - Found 2 version(s) in nuget.org [ Nearest version: 2.1.0-preview1-final ]
```

**Actual**
```
/private/tmp/test1/test1.csproj : error NU1103: Unable to find a stable package dotnet-watch with version 
/private/tmp/test1/test1.csproj : error NU1103:   - Found 2 version(s) in nuget.org [ Nearest version: 0.0.1-alpha ]
```

@nkolev92

**Comment by nkolev92** [comment]
This is definitely a bug. 
I managed to reproduce it. 
It's not a regression. 

The related code is [here.](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnresolvedMessages.cs#L153)

It doesn't consider floating versions. 

The fix should be minor, but need to do a further analysis to confirm that. 

/cc @rrelyea 
I assume we want this fixed soon?

Should it go for .300 version?
What would the right timeline there.

/cc @livarcocc @wli3 @kathleendollard

**Comment by livarcocc** [comment]
I vote for .300 version of the CLI.

**Comment by KathleenDollard** [comment]
I agree with @livarcocc on this.
