### ISSUE TITLE
Inconsistency in the way UI window is launched for projects and solutions. Either only 1 window should show up or multiple windows should show up in all the cases

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#666]
a. Repro steps
	i. Create a console application
	ii. Launch the 'Manage NuGet Packages' for solution. It opens a new window
	iii. Launch the 'Manage NuGet Packages' for a project.
        iv. Expected: It opens a new window
	iv. Actual: It selects the 'Manage NuGet Packages' for solution rather than open a new window.
b. NOTE: If this is by design, note that 2 windows can be opened if the window for the project is opened first. Also, note that the project can be renamed to something other than the name of the solution. Does not matter. Same inconsistency observed.

**Comment by yishaigalatzer** [comment]
This sounds like by design, we should at least show that it is the solution package manager instead of the project package manager to avoid confusion.

**Comment by yishaigalatzer** [comment]
Conclusion: Change the API that opens the window to make it clear if it opens a per solution window or per project. And make the UI show clearly if you are managing the whole solution or a single project.
