### ISSUE TITLE
Content group items from Nuget not included in publish output

### ISSUE THREAD

**Issue by AndrewTriesToCode** [NuGet/Home#6661]
Files designate as Content in a Nuget package are not being copied to the publish output folder. They are only coping to publish output if the `CopyToOutput` attribute is set on the contentFiles/file entry. Per its [definition](https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-content-files) `CopyToOutput` should only toggle output to the build folder.

**Environment**

* using dotnet pack / dotnet restore / dotnet build / dotnet publish
* using VSCode 1.21

dotnet --info
.NET Command Line Tools (2.1.300-preview1-008174)

Product Information:
 Version:            2.1.300-preview1-008174
 Commit SHA-1 hash:  b8df89a54f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.300-preview1-008174/

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26216-03
  Build    : f2c3216183d20416568a4bbf5bb7d153e826f153

**Reproduction Steps**
1. Create a simple Nuget package with with a contentFile/files entry, make sure the `BuildAction` is "Content" and `CopyToOutput` is "false" or not set (I don't want to copy to the build output--only the publish output).

2. Consume the Nuget package and run `dotnet publish`, the Nuget content files will not be included.

If I do include `CopyToOutput` then the file appears in both the build and publish output.

**Comment by rohit21agrawal** [comment]
@achandlerwhite the documentation is from way back when .NET Core was not even a thing, so the publish target didn't exist.

This is the right behavior, we will update the docs.
