### ISSUE TITLE
Pack should emit warning when a targets  file is included in build/buildCrossTargeting folder with a name different than package id.

### ISSUE THREAD

**Issue by alpaix** [NuGet/Home#6664]
### Details about Problem
VS 15.7.0 Preview 1.0
NuGet.exe version: 4.5.1.4879

### Detailed repro steps so we can see the same problem

1. Create a package using `nuget.exe pack <packageName>.nuspec` containing an arbitrary `.targets` file.
2. Try to install the package into a .NET Core 2.0 project
3. Inspect the contents of `project.assets.json` file

### Result

The target file from the package is not referenced. 

While this behavior is by design it'd be better to emit a warning per included target file if it doesn't match certain criteria. The warning can be generated by pack as well as install command.

**Comment by rohit21agrawal** [comment]
@alpaix you know the code, send a PR ;) (JK)

**Comment by rohit21agrawal** [comment]
the targets files are referenced in the .g.props or .g.targets file inside the obj folder, did you take a look there?

**Comment by alpaix** [comment]
Target file was not referenced until I renamed it after the package name. I presume there's no workaround for that limitation?

**Comment by rohit21agrawal** [comment]
no. that is by design. 
It's a good idea to add the warning to the pack validation.

**Comment by rohit21agrawal** [comment]
is there a specific scenario where you wouldn't want the target file to be named after the package id?

**Comment by alpaix** [comment]
We were trying to package interop assemblies with a boilerplate targets file setting `EmbedInteropTypes` property to true. So we spent some time trying to understand why it didn't work.

**Comment by rohit21agrawal** [comment]
@nkolev92 can you provide Alex with the recommended way of including interop assemblies? I know we have a GitHub sample somewhere

**Comment by rohit21agrawal** [comment]
oh, here it is : https://github.com/NuGet/Samples/tree/master/NuGet.Samples.Interop 
CC: @alpaix

**Comment by alpaix** [comment]
Cool! Thanks! I think I've got one of this sample project variations.

**Comment by nkolev92** [comment]
Done. https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5129
