### ISSUE TITLE
Migrator dogfooding issues

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#6666]
1. typo in gold bar **[FIXED]**
   ![image](https://user-images.githubusercontent.com/16904420/37317668-706fd7ce-2623-11e8-8c8a-48a7ebef617a.png)

2. gold bar should have an info icon **[CUT]**
   ![image](https://user-images.githubusercontent.com/16904420/37318257-bee6f7d6-2626-11e8-9f8a-4f2b4d5dd533.png)

3. gold bar should have a close "X" at the end **[FIXED]**
   ![image](https://user-images.githubusercontent.com/16904420/37319322-e4733c1c-262b-11e8-8a06-045273595182.png)

   Compare with other gold bars in the product
   ![image](https://user-images.githubusercontent.com/16904420/37319353-0350145c-262c-11e8-8cf6-8aaaa9a31fdf.png)

4. Package issues messages need to be rephrased **[OPEN]**
   * "install.ps1" script will be ignored when the package is installed after the migration
   * "content" assets will not be available when the package is installed after the migration
   * XDT transforms will not be applied when the package is installed after the upgrade
   * "lib\foo.dll" will be ignored when the package is installed after the migration

5. Migration report must open in the browser and not in VS **[OPEN]**

6. Only one backup folder should be created.  **[KINDA FIXED]**
   ![image](https://user-images.githubusercontent.com/16904420/37320024-fa39b000-262e-11e8-830e-895c20ae05af.png)

7. Rename the report file - NuGetMigrationLog. Also, ensure it reflects in the page title that shows up on the browser tab **[OPEN]**
   ![image](https://user-images.githubusercontent.com/16904420/37320299-47cb1fc4-2630-11e8-956e-97017aa7e159.png)

8. Update the text and link for revert the migration. **[OPEN]**
   Text - Help me rollback to packages.config
   URL - https://aka.ms/nuget-pc2pr-migrator-rollback

9. Clicking on the link to the backup should open the backup folder **[OPEN]**

10. Small nits in the report headings **[OPEN]**
   * Packages **P**rocessed -> Packages **p**rocessed
   * Top-level **D**ependencies -> Top-level **de**pendencies
   * Transitive **D**ependencies -> Transitive **d**ependencies

**Comment by rohit21agrawal** [comment]
About the backup folder, the addition of guid prefix has been done to avoid accidentally deleting user data as Backup is a very generic folder name. I don't think creating multiple backup folders should be too big of an issue.

**Comment by karann-msft** [comment]
Rename the folder to "migration backup" or something more exotic if that's your concern. At the very least, remember the folder you created since you know that there would be no user data in that and use that for subsequent migrations. 
In my opinion, change the folder name and call it good unless we are using this as a workaround for some other issue.

**Comment by karann-msft** [comment]
Reopening since some issues haven't been addressed.

**Comment by rohit21agrawal** [comment]
@karann-msft please tell which issues haven't been addressed?

**Comment by karann-msft** [comment]
I have tagged all the issues listed above. Everything with **[OPEN]** needs to be addressed. As and when you fix them, change the associated tags.

**Comment by rrelyea** [comment]
@rohit21agrawal  - seems like we should fix any of these needed for 15.7 this week.

**Comment by rohit21agrawal** [comment]
@karann-msft can you show me where you see NuGet Upgrade Report in the migrator report? it's already been fixed

**Comment by rohit21agrawal** [comment]
same for item # 10 & 8 . Please send me screenshots if you still see the issue.

**Comment by rohit21agrawal** [comment]
number 9 cannot be done for security reasons : https://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page/18246357#18246357
