### ISSUE TITLE
How to add the particular framework version assemblies while installing the NuGet package in another framework version project

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#6668]
Hi All,

I have tried to install the MVC4 NuGet package with the some dependent NuGet packages which is in below structure in the 4.6 framework application.

Dependent package Structure is,

![image](https://user-images.githubusercontent.com/16695209/37341195-8dededcc-26e6-11e8-99b4-6a5443cbc205.png)
![image](https://user-images.githubusercontent.com/16695209/37341577-e688c3e8-26e7-11e8-9276-7f5057e99858.png)

But in MVC4 application the assemblies (which is available in the dependent package) are added in the 4.5 framework version instead of the 4.0 framework version. But the parent MVC4 NuGet packages assemblies are have the 4.0 Framework version assemblies as a dependent. In my side I need to add the 4.0 framework version assemblies while installing the above dependent NuGet package.

My parent package spec file structure is,

![image](https://user-images.githubusercontent.com/16695209/37341667-3865d160-26e8-11e8-8a4f-899932e7e149.png)

My question is,

How can I refer the 4.0 framework version assemblies in the 4.6 framework version project while installing the above structure NuGet package?
Is there any changes are need in the above NuGet structure?

Please suggest any idea regarding this,

Thanks in advance.

Regards,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Hi All,

Please update me Is there any suggestion regarding this?

Thanks,
Ganesan R.

**Comment by rohit21agrawal** [comment]
@GanesanRengasamy NuGet always picks the most compatible target framework group from the package, which in your case is net45.

If you want to make your project use assets from net40, change your project target framework, to something less than net45, or remove the net45 folder from the package
