### ISSUE TITLE
What is the best way to pack an assembly as a reference assembly?

### ISSUE THREAD

**Issue by mattleibow** [NuGet/Home#6676]
I am building a multi-targeting project which has (for this example) 4 platforms:
 - netstandard1.0
 - uwp
 - ios
 - android

The current `/t:Pack` operation is fine and works well. However, I am wanting to make the netstandard library a reference library and not include it in the app build output. The reason for this is that I would like to make the package "extendable" to other developers. I will be working on the iOS/Android/UWP, but Tizen may be something that is wanted.

I believe the `ref/<platform>` package folder is only used at build-time, so I was hoping to be able to move my netstandard assembly there instead of the `lib` folder.

This is the current package:

```
lib/netstandard1.0/Assembly.dll
lib/xamarin.ios/Assembly.dll
lib/monoandroid/Assembly.dll
lib/uap10.0/Assembly.dll
```

What I would like is this:

```
ref/netstandard1.0/Assembly.dll
lib/xamarin.ios/Assembly.dll
lib/monoandroid/Assembly.dll
lib/uap10.0/Assembly.dll
```

This way - at least in my mind - Bob from Samsung could create his package and just depend on mine:

```
lib/tizen4/Assembly.dll
```

What is the best way to not actually ever include the netstandard assembly in any app package or deployment?

**Comment by rohit21agrawal** [comment]
@mattleibow i don't have an out of the box solution for you, but i can recommend a workaround.

1) build before you pack so it has build outputs for all 4 frameworks you are targeting.
2) when you pack using ```msbuild /t:pack``` , pass an additional property which indicates that this is packing. For ex ``` msbuild /t:pack /p:RandomProperty=true```
3) In your project file, condition your TargetFrameworks property so that when ```RandomPropert==true```, netstandard1.0 is not a framework.
4) Add an item group like the following:

```
<None Include="bin\$(Configuration)\netstandard1.0\Assembly.dll" Pack = "true">
    <PackagePath>ref/netstandard1.0</PackagePath>
</None>

```

**Comment by rohit21agrawal** [comment]
However, this is a valid scenario and good feedback which makes me thing we should have out of the box support for something like this.

We currently have a property called ``` BuildOutputTargetFolder ``` , which can be changed to set build output to something other than ```lib```. However, that is an all or nothing switch, and based on this feedback, we should make this conditional on target framework.

So you could have something like : 

```
<BuildOutputTargetFolder>lib</BuildOutputTargetFolder> 
<BuildOutputTargetFolder Condition = "'$(TargetFramework)' == 'netstandard1.0'">ref</BuildOutputTargetFolder>
```

**Comment by rohit21agrawal** [comment]
i have filed an issue to track this feedback. Closing this issue as question 

https://github.com/NuGet/Home/issues/6689
