### ISSUE TITLE
How to get the list of owners of a given package on nuget.org

### ISSUE THREAD

**Issue by Jericho** [NuGet/Home#6679]
How can I get the list of owners of a given package hosted in nuget.org? What I'm looking for is the information circled in red in this screenshot:

![sshot-14](https://user-images.githubusercontent.com/112710/37443249-5c16cc6e-27e1-11e8-8111-888309c05edc.png)

When I query nuget with the following code, the `Owners` property is always null. So I'm wondering if there is an alternative?
```
var providers = new List<Lazy<INuGetResourceProvider>>();
providers.AddRange(NuGet.Protocol.Core.Types.Repository.Provider.GetCoreV3());
var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
var sourceRepository = new SourceRepository(packageSource, providers);
var nugetPackageMetadataClient = sourceRepository.GetResource<PackageMetadataResource>();
var packageMetadataResult = await _nugetPackageMetadataClient.GetMetadataAsync("Cake.Email", true, true, new Logger(), CancellationToken.None);
var mostRecentPackage = packageMetadataResult
    .OrderByDescending(p => p.Published)
    .First();
var owners = mostRecentPackage.Owners;
```

**Comment by rohit21agrawal** [comment]
@joelverhagen does the v3 feed not send the owners metadata?

**Comment by Jericho** [comment]
@joelverhagen can you help me figure out why the `Owners` property is always `null` and/or suggest an alternative to get the owners of a given package hosted on nuget.org?

**Comment by joelverhagen** [comment]
Hey @Jericho, today there is no official way on NuGet.org to fetch the current list of owners on a package. This is a known shortcoming of our API and (in my own personal opinion) should be improved in the future. I will move this issue to the NuGetGallery repository to track this feature request.

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #5647](https://github.com/NuGet/NuGetGallery/issues/5647) via [**ZenHub**](https://www.zenhub.com/)
