### ISSUE TITLE
[Area:NuGetizer] Microsoft.NuGet.targets requires reference to .NET Framework 4.0

### ISSUE THREAD

**Issue by GuyWhoKnowsTheGuy** [NuGet/Home#6682]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Visual Studio 2017 Build Tools (15.6.82.30579)
Jenkins 2.89.4

NuGet version (x.x.x.xxx):
4.5.1.4879 (used to restore in build process)

dotnet.exe --version (if appropriate):
N/A

VS version (if appropriate):
N/A

OS version (i.e. win10 v1607 (14393.321)):
Windows Server 2016 Standard

Worked before? If so, with which NuGet version:
No

## Detailed repro steps so we can see the same problem

1. In Jenkins, restore Nuget packages for attached solution

2. In Jenkins, build attached solution

3. Error shown below in log section.  

4. Run the same commands from the command prompt and the build succeeds  

...

### Verbose Logs

Building in workspace c:\workspace\NugetizerBug
Cloning the remote Git repository
Cloning repository c:\src\NugetizerBug
 > git.exe init c:\workspace\NugetizerBug # timeout=10
Fetching upstream changes from c:\src\NugetizerBug
 > git.exe --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git.exe fetch --tags --progress c:\src\NugetizerBug +refs/heads/*:refs/remotes/origin/*
 > git.exe config remote.origin.url c:\src\NugetizerBug # timeout=10
 > git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git.exe config remote.origin.url c:\src\NugetizerBug # timeout=10
Fetching upstream changes from c:\src\NugetizerBug
using GIT_ASKPASS to set credentials 
 > git.exe fetch --tags --progress c:\src\NugetizerBug +refs/heads/*:refs/remotes/origin/*
 > git.exe rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > git.exe rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision 2c7c992251e44a526adadbe4e176d5ce45b3d444 (refs/remotes/origin/master)
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 2c7c992251e44a526adadbe4e176d5ce45b3d444
Commit message: "bug;"
First time build. Skipping changelog.
[NugetizerBug] $ cmd /c call C:\Windows\TEMP\jenkins3330454504531483085.bat

c:\workspace\NugetizerBug>c:\nuget.exe restore c:\workspace\NugetizerBug\ClassLibrary1.sln 
MSBuild auto-detection: using msbuild version '15.6.82.30579' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Restoring NuGet package NuGet.Build.Packaging.0.2.3.
Adding package 'NuGet.Build.Packaging.0.2.3' to folder 'c:\workspace\NugetizerBug\packages'
Added package 'NuGet.Build.Packaging.0.2.3' to folder 'c:\workspace\NugetizerBug\packages'
Restoring packages for c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj...
Committing restore...
Generating MSBuild file c:\workspace\NugetizerBug\NuGetPackage1\obj\NuGetPackage1.nuproj.nuget.g.props.
Generating MSBuild file c:\workspace\NugetizerBug\NuGetPackage1\obj\NuGetPackage1.nuproj.nuget.g.targets.
Writing lock file to disk. Path: c:\workspace\NugetizerBug\NuGetPackage1\obj\project.assets.json
Restore completed in 604.92 ms for c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj.

NuGet Config files used:
    C:\Windows\system32\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Windows\system32\config\systemprofile\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    1 package(s) to packages.config projects

c:\workspace\NugetizerBug>exit 0 
Path To MSBuild.exe: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe
Executing the command cmd.exe /C " chcp 1252 & "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" /target:Build /p:Configuration=Debug "/p:Platform=Any CPU" ClassLibrary1.sln " && exit %%ERRORLEVEL%% from c:\workspace\NugetizerBug
[NugetizerBug] $ cmd.exe /C " chcp 1252 & "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe" /target:Build /p:Configuration=Debug "/p:Platform=Any CPU" ClassLibrary1.sln " && exit %%ERRORLEVEL%%
Active code page: 1252
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/15/2018 7:12:13 AM.
Project "c:\workspace\NugetizerBug\ClassLibrary1.sln" on node 1 (Build target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "c:\workspace\NugetizerBug\ClassLibrary1.sln" (1) is building "c:\workspace\NugetizerBug\ClassLibrary1\ClassLibrary1.csproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Data.DataSetExtensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Net.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\System.Xml.Linq.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\ClassLibrary1.dll /subsystemversion:6.00 /target:library /utf8output Class1.cs Properties\AssemblyInfo.cs "C:\Windows\TEMP\.NETFramework,Version=v4.6.2.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\ClassLibrary1.dll" to "bin\Debug\ClassLibrary1.dll".
  ClassLibrary1 -> c:\workspace\NugetizerBug\ClassLibrary1\bin\Debug\ClassLibrary1.dll
  Copying file from "obj\Debug\ClassLibrary1.pdb" to "bin\Debug\ClassLibrary1.pdb".
Done Building Project "c:\workspace\NugetizerBug\ClassLibrary1\ClassLibrary1.csproj" (default targets).
Project "c:\workspace\NugetizerBug\ClassLibrary1.sln" (1) is building "c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj]
Done Building Project "c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj" (default targets) -- FAILED.
Done Building Project "c:\workspace\NugetizerBug\ClassLibrary1.sln" (Build target(s)) -- FAILED.

Build FAILED.

"c:\workspace\NugetizerBug\ClassLibrary1.sln" (Build target) (1) ->
"c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj" (default target) (3) ->
(ResolveNuGetPackageAssets target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project is not referencing the ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "frameworks" section of your project.json, and then re-run NuGet restore. [c:\workspace\NugetizerBug\NuGetPackage1\NuGetPackage1.nuproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.37
Build step 'Build a Visual Studio project or solution using MSBuild' marked build as failure
Finished: FAILURE

### Sample Project
[NugetizerBug.zip](https://github.com/NuGet/Home/files/1815698/NugetizerBug.zip)

Very helpful if you can zip a project and paste into this issue!

**Comment by GuyWhoKnowsTheGuy** [comment]
Anyone using Nugetizer 3000 with Jenkins?  Any help is appreciated.

**Comment by brandonchastain** [comment]
+1, same issue happening to me, but instead on Azure DevOps instead of Jenkins.
@Heteroculturalism, did you find a fix?

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

You can use a [packaging project](https://www.clarius.org/nugetizer/#packaging-projects) supported out of the box by Visual Studio and NuGetizer.
