### ISSUE TITLE
IVsPackageRestorer does not restore

### ISSUE THREAD

**Issue by kzu** [NuGet/Home#6688]
In Xamarin, our project flavors use code like the following to trigger a restore as soon as a template is unfolded, since proper dependencies are required in order for designers, previewers and intellisense to work properly from the get go:

```csharp
var componentModel = (IComponentModel) this.ServiceProvider.GetService(typeof(SComponentModel));
var restorer = componentModel.GetService<IVsPackageRestorer>();
if (restorer.IsUserConsentGranted())
{
    restorer.RestorePackages(activeProject);
}
```

If the project has a package reference like the following:

```xml
 <PackageReference Include="Xamarin.Android.Support.Design" Version="27.0.2"/>
```

The previous code will *not* cause the package to be restored. 

You can test this by creating a VSIX that has a simple command and paste the above code in it to reproduce the issue.

We do not know if this is something that regressed or if it was always (broken?) like this (for `PackageReference`). We have verified that using `packages.config` instead, the *same* code *does* work.

This is a serious issue since it basically breaks a perfectly valid usage of nuget package references in templates.

It would be awesome if this could be fixed in the 15.7 timeframe :)

**Comment by kzu** [comment]
related https://github.com/NuGet/Home/issues/2066, suspicious https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.PackageManagement/IDE/PackageRestoreManager.cs#L167

**Comment by zhili1208** [comment]
@kzu Yes, that's the issue, this API only works for package.config, it's not a regression.

**Comment by kzu** [comment]
The regression is in behavior: an API that used to work and restore, no longer does if the user changes to `PackageReference`, without *us* changing anything. Moreover, the scenario that used to work, no longer does and there is no workaround that we could find.

This means we cannot recommend anyone using Xamarin to switch to `PackageReference` and we'll have to modify all our newer templates to use the old `packages.config`, with the *significant* issues that had and which are the very reason we moved to `PackageReference`. One of which is that creating a new project takes *forever* and makes for a terrible first-run experience for Xamarin.

Please do advise on how should we proceed. Should we consider `PackageReference` broken "by design" for anyone doing templates?

**Comment by pierceboggan** [comment]
To add to what @kzu said, before switching to `PackageReference`, our most popular project templates were taking 1-2 minutes to unfold. After switching to `PackageReference`, the unfold process sped up by 4-5x, depending on machine. The `packages.config` method had a negative impact on retention, so we are not keen to move back to that approach. 

This is just one of the many issues we had when using `packages.config`.

**Comment by jainaashish** [comment]
As mentioned on email, there are couple of options to work this around:
1.	Try using NominateProjectAsync api from IVsSolutionRestoreService2 interface which works similar to IVsPackageRestorer and restore the provided project. So you just need to pass the project unique name. This interface is available via NuGet.SolutionRestoreManager.Interop package (https://www.nuget.org/packages/NuGet.SolutionRestoreManager.Interop )

2.	Another option is, to try using IVsPackageInstaller which has multiple variations of InstallPackage api which is also plump to support PackageReference.

**Comment by kzu** [comment]
Solved by switching to:

```csharp
    [Guid("88BE06DF-97B7-47E8-8047-28279C02E401")]
    public interface IVsSolutionRestoreService2
    {
        // Summary:
        //     An entry point used by CPS to indicate given project needs to be restored.
        Task<bool> NominateProjectAsync(string projectUniqueName, CancellationToken token);
    }
```

Note that you should *ignore* the comment about CPS ;)
