### ISSUE TITLE
Performance of toggling UI elements can be improved with caching

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#669]
Redundant Network calls on toggling 'Include Prerelease' check box. There are multiple scenarios here.

The issue here is of course that we don't have proper caching for results, and if we did then we will probably need a refresh button to deal with changes, a caching strategy (how long do we hold on the results, 5 min?)

		a. In V2, 3 queries are made to get the versions of the packages, when a package is selected in the search result
		b. In addition to the search query to get the results, Query to get all the versions of the selected package is made as well. There is no caching of results by the client
		c. Query to get all the versions of the first package in the search result, even though it is not the selected package
		d. In V3, In 'All' tab, not all the versions of the installed packages which are also in the search results are queried for. While, In V2, we do. There is inconsistency in the caching policy

**Comment by yishaigalatzer** [comment]
This is already covered in the work items for @feiling for 3.4

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/1494
