### ISSUE TITLE
NuGet build task passes strong type as parameter to msbuild logger

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#6691]
Repro:
Turn on design time build log, and open Roslyn.sln in visual studio. 
You will see lots of failure messages like:

16:45:04.035 Verbose] - BuildManager - C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1603,5): error MSB4018: The "GetReferenceNearestTargetFrameworkTask" task failed unexpectedly.

System.TypeLoadException: Could not load type 'NuGet.Common.INuGetLogMessage' from assembly 'NuGet.Common, Version=4.7.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

   at NuGet.Build.MSBuildLogger.Log(ILogMessage message)

   at NuGet.Common.LoggerBase.Log(LogLevel level, String data)

   at NuGet.Build.Tasks.BuildTasksUtility.LogTaskParam(ILogger log, String direction, String name, String[] values)

   at NuGet.Build.Tasks.GetReferenceNearestTargetFrameworkTask.Execute()

   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()

   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

This happened because:
The type loading issue was not inside msbuild process, but in the VS process, when a msbuild logger here deserialize messages from the msbuild process.  Basically, turning on build log will expose this problem, until maybe some other features in the VS loads the NuGet.common.dll.  That DLL lives inside one CommonExtensions folder is not in the assembly searching path, so it won’t be found until other features load it.  If NuGet restore runs earlier, it could hide this problem.

NuGet msbuild logger can be found at https://github.com/NuGet/NuGet.Client/blob/e6ae38cd1ff41bea78346ca348e10eac557d45bb/src/NuGet.Core/NuGet.Build.Tasks/Common/MSBuildLogger.cs

It passes a strong type INuGetLogMessage to the msbuild logger as a message parameter.   Those parameters will be serialized/deserialized inside msbuild message object 

The result is that NuGet task will pass a type to another process processing msbuild message, and causes this failure.  It seems to be the only reason msbuild to do that is to create the message string lazily to reduce string allocation when it is not needed.  But passing a type seem to be worse, so I think NuGet team need fix the issue and prevent passing its own type there.

**Comment by rohit21agrawal** [comment]
the issue has been discussed on an email thread, this was not the root cause of the issue
