### ISSUE TITLE
Adding ImageSharp (.NET Standard 1.1+) results in mind-boggling install experience

### ISSUE THREAD

**Issue by riverar** [NuGet/Home#6694]
# General
When adding ImageSharp to a .NET Framework 4.7.2 project, I'm confronted by a number of monstrous looking dialogs that give the impression I'm importing the entire .NET Core framework plus the packing peanuts it came in.

I [spoke with the vendor briefly](https://gitter.im/ImageSharp/General?at=5aaef27e458cbde5574cb535) and it wasn't clear who's at fault here. The project appears to correctly target [.NET Standard 1.1+](https://github.com/SixLabors/ImageSharp/blob/bfa854939d71b4bcfea3ff8f6b5ab0cb65186925/src/ImageSharp/ImageSharp.csproj#L8) ([with a few CoreFx items referenced](https://github.com/SixLabors/ImageSharp/blob/bfa854939d71b4bcfea3ff8f6b5ab0cb65186925/src/ImageSharp/ImageSharp.csproj#L43)).

I expected most, if not all, of the .NET Core dependencies to be **silently** resolved **prior to download and install** as I'm targeting full desktop framework. As I don't see all these items in my output (or .exe.config) I assume they were thrown away after NuGet evaluation realized I have most of this stuff already. **What a waste of nearly 600MB of downloaded data.**

# System
```
Microsoft Visual Studio Professional 2017 
Version 15.6.1
VisualStudio.15.Release/15.6.1+27428.2002
Microsoft .NET Framework
Version 4.7.03056
Installed Version: Professional
NuGet Package Manager   4.6.0
```

# Try it!
1. Start a .NET Framework 4.7.2+ console project
2. Add the NuGet package ImageSharp (beta 2)
3. Note these dialogs appear:

![image](https://user-images.githubusercontent.com/475132/37572861-a053bfb4-2ace-11e8-8e61-d417036e2738.png)
![image](https://user-images.githubusercontent.com/475132/37572900-388c9bde-2acf-11e8-9e2c-2e9407b0873e.png)

**Comment by nkolev92** [comment]
Hey @riverar 

Apologies for the long overdue reply, this slipped through the cracks. 

Unfortunately I have to call this by design. 
Some of the old versions of imagesharp reference .NET Standard Library, which effectively is all of .NET Core at that time. 

The prompt displays a list of all the packages getting installed and all the ones that have a license. 

These cases are a lot less frequent in .NET Standard2.0 and especially .netcoreapp3.0 and later.

**Comment by riverar** [comment]
Agree, thanks @nkolev92
