### ISSUE TITLE
contentFiles feature is broken

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#6695]
Let's take the official sample "ContentFilesExample" from https://github.com/NuGet/Samples/tree/master/ContentFilesExample and build a package with contentFiles. 
Then create a new project with `dotnet new console` and add the package via `dotnet add package ContentFilesExample --source path/to/ContentFilesExample/authoring `

**Expected result**:
Files from `contentFiles` folder are added into the project.

**Actual result**:
Files in contextFiles are ignored. Just a PackageReference is added and nothing more.

Documentation says that the feature `contentFiles` is for "NuGet 4.0+ with PackageReference". But the consuming sample in https://github.com/NuGet/Samples/tree/master/ContentFilesExample is old csproj format. So it's useless. Also please note that the documentation is terribly unclear. 

ps:
```
D:\Work\Learn\nuget\Samples\ContentFilesExample\consuming\test>dotnet --info
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.101\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

**Comment by rohit21agrawal** [comment]
@evil-shrike the content from contentFiles folder is not meant to be copied to the project directory, instead, at build time it is copied to the output directory (usually ``` bin\$(Configuration) ```

**Comment by evil-shrike** [comment]
Source:
Given a package - Package.1.0.0.nupkg, with contentFile in nuspec:
```
    <contentFiles>
      <files include="**/Reports/*.*" buildAction="Content" copyToOutput="true" />
    </contentFiles>
```
files inside nupkg: 
\contentFiles\any\any\Reports\test.xsd 

Destination:
Givien a project with installed that nuget package (as `dotnet add package Package --source ..`):
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Package" Version="1.0" />
  </ItemGroup>
</Project>
```
Now build it via `dotnet build`.
Go to Output bin\Debug\netcoreapp2.0 - nothing.
dst.dll
dst.pdb
dst.deps.json
dst.runtimeconfig.json
dst.runtimeconfig.dev.json

**Comment by StingyJack** [comment]
Content files are apparently not supported in package ref https://github.com/NuGet/Home/issues/6659

EDIT: @jainaashish - I dont want to add another comment and muddy up the chain, so I'm editing this one. You are probably correct, and I can unintentionally be quite thick at times, but expecting someone to discern a clear intent and difference between "content files" and "contentfiles" that isnt a typo may be a bit unreasonable. In the linked thread, I've been trying to elicit that difference, and more importantly the value I'd be getting with what I think is intended to be the replacement, perhaps you can explain over there (or email, w/e).

**Comment by evil-shrike** [comment]
But where are they supported? For package.config only?

**Comment by jainaashish** [comment]
@StingyJack Please read carefully before commenting, otherwise people will be confused. 

Content files are supported with PackageReference via `ContentFiles` folder and not through `Content` folder. There are two different folders hierarchy in NuGet package a) `Content` which is only supported with `packages.config` and b) `ContentFiles` which is only supported with `PackageReference`.

This is clearly mentioned on NuGet docs and multiple issues. If you still find it confusing, please let us know and we'll try to make it more understandable.

**Comment by rohit21agrawal** [comment]
@evil-shrike can you attach the nupkg which isn’t working for you?

**Comment by evil-shrike** [comment]
@rohit21agrawal 
[Package.1.0.0.zip](https://github.com/NuGet/Home/files/1849000/Package.1.0.0.zip)

**Comment by rohit21agrawal** [comment]
@evil-shrike I just tried this on my machine, and the Reports folder is copied to my bin directory.

```
 E:\temp\contentfiletest> dotnet --version
2.1.200-preview-007474
```

Does a restore happen between ```dotnet build``` and ```dotnet add package``` command?

After you run the restore, could you zip the obj folder and attach it so we can see where it's going wrong?

**Comment by evil-shrike** [comment]
@rohit21agrawal finally got it working. Sorry for the noise. The reason why it wasn't working is caching. I removed the package from .nuget folder in my profile, restore with `-f` and got the files from contentFiles folder in bin-output (once again persistent non-avoidable cache and subtle `--force` option hits me). 

May I suggest to improve documentation on https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files - it says nothing about how contentFiles is processed and why it's needed.
Also the section ["Including content files"](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files) is misleading as it talks about old "content" not "contentFiles" while it's referenced from ["Files element"](https://docs.microsoft.com/en-us/nuget/reference/nuspec#files-element):
> The `<package>` node may contain a `<files>` node as a sibling to `<metadata>`, and a or `<contentFiles>` child under `<metadata>`, to specify which assembly and content files to include in the package. See Including assembly files and Including content files later in this topic for details.

**Comment by GF-Huang** [comment]
Same issue, the docs maybe out of date.
https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations
