### ISSUE TITLE
NuGet.PackageManagement: PackageRestoreManager needs to execute package restore under a lock to allow for parellel restores across a machine

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#67]
NuGet.PackageManagement: PackageRestoreManager needs to execute package restore under a lock to allow for parellel restores across a machine

**Comment by pranavkm** [comment]
This should be addressed by our use of https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Common/ConcurrencyUtilities.cs#L22
