### ISSUE TITLE
Deleting a project closes corresponding UI window, but, renaming a project does not rename the UI window. Note that PMC listens to project rename and project remove events

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#670]
a. Repro steps
			i. Create 2 Console Applications in a solution
			ii. Open the 'Manage NuGet Packages' window for both the projects
			iii. Delete a project. The window corresponding to the project goes away
			iv. Rename the other project
			v. Expected: The title of the UI window corresponding to the renamed project is renamed as well, just like responding to the project delete event
			vi. Actual: No rename of the UI window happens. Package Manager Console renames the selected project properly

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/commit/25cd04ed70c4505bfed81c7705035c80c4821f46
