### ISSUE TITLE
Cross-plat plugin trust validation for nuget plugins

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6702]
Related to : https://github.com/nuget/home/issues/6642

Authenticode is not xplat, we need a way to verify trust between nuget and the plugins on in .netcore on linux/mac.

**Comment by nkolev92** [comment]
Currently the authenticode check is only done for Windows. 
Code [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/EmbeddedSignatureVerifier.cs#L28-L33)

It's also supported on mono per https://www.mono-project.com/docs/faq/security/#authenticoder-code-signing

**Comment by nkolev92** [comment]
In 4.8, we won't be doing this validation due to framework limitations. 

Changing this to Backlog as a feature

**Comment by nkolev92** [comment]
Closingn in favor of a mroe detailed issue 
https://github.com/NuGet/Home/issues/7338
