### ISSUE TITLE
[Simple	bug] Invalid signature file format message is not specific

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#6712]
Suppose the signature file is compressed. The code is very nearly producing the error message:

```
The package signature file entry is invalid. The central directory header field 'compression method' has an invalid value (8).
```

However, only this error is showing:

```
The package signature file entry is invalid.
```

`AssertValue` is being called like `errorMessagePrefix` is a string format. But it isn't.

**Comment by mishra14** [comment]
@joelverhagen the actual problem is unclear, can you please elaborate?

**Comment by joelverhagen** [comment]
Here's the source:

https://github.com/NuGet/NuGet.Client/blob/0f6d609e9767dc58c519914e255993642ef48228/src/NuGet.Core/NuGet.Packaging/Signing/Archive/SignedPackageArchiveIOUtility.cs#L417-L419
