### ISSUE TITLE
Suggestion - Git repository on RestoreSources information

### ISSUE THREAD

**Issue by rodrigogq** [NuGet/Home#6716]
When configuring Nuget packages restore on MSBuild in the new **`PackageReference`** format, allow to use a personal git repository containing all the packages as if it was a Windows Shared folder.

This would simplify a lot several Continuous Integration / Testing / Deployment and DevOps operations.

It also would be cool to be able to set different branches for different build targets (e.g.: point to a .git#development branch when building on a Testing scenario for getting preview packages, not still used on production).
```
<PropertyGroup>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <RestoreSources>http://source-control/project.git</RestoreSources>
</PropertyGroup>
```

**Comment by nkolev92** [comment]
Hey @rodrigogq, 

Thank you for this issue. 
Given the packages features that Github announced, I'm closing this feature ask as a won't fix.
