### ISSUE TITLE
NuGet PM UI improvements

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#6718]
From twitter:
https://twitter.com/robertmclaws/status/976237953944088576
![image](https://user-images.githubusercontent.com/14800916/37726702-35c36312-2cf3-11e8-8212-a61ec1b47e6c.png)

This issue is to discuss the concerns further.

**Comment by nkolev92** [comment]
There's lots of related bugs that this can be duped against.
Like https://github.com/NuGet/Home/issues/1236.
We should either dupe out the ones that have the same ask, or create an epic containing all of the UI related ideas.

**Comment by anangaur** [comment]
@nkolev92 May be. But I need to understand the exact issues and enhancements first. Let it be open for a while to have this discussion and then we can find the right home for the required improvements.

**Comment by rohit21agrawal** [comment]
i dislike the fact that new bugs are opened even though there are existing ones around. We spend a few hours every sprint trying to clean up this mess, and this is just increasing work for us.

CC: @rrelyea

**Comment by anangaur** [comment]
Please ignore all issues assigned to me if you want to clean up. I want to have a different discussion here and not about the process. :)

**Comment by anangaur** [comment]
Closing it as there was no further discussion on this.
