### ISSUE TITLE
Package Manager Console does not load back the active package source when a solution is open unlike UI windows for a project or the solution

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#672]
a. Repro steps
	i. Create or open a solution with 2 projects. Console applications will do. It should also have a nuget.config at the solution level with a custom package source
	ii. Switch the active package source to the custom package source on the UI window for the solution and one of the projects. Do the same for package manager console
	iii. Close solution. Note that the active package source on Package Manager Console changes to the custom package source
	iv. Re-open solution
	v. Expected: Package Manager Console uses the custom source on the solution level nuget.config as Active Package Source. UI windows for the solution and the projects persist this information properly
	vi. Actual: Package Manager Console does not use the custom source as active package source. Instead, it simply uses the first package source, that is, api.nuget.org as the active package source

**Comment by yishaigalatzer** [comment]
We decided that since PMC is global, this behavior makes at least some sense :) We are not going to try and fix it, because we are concerned with the location where that information will be saved into and potential bug tail/side effects
