### ISSUE TITLE
Installing package causing error about unable to find EOCDR

### ISSUE THREAD

**Issue by mishra14** [NuGet/Home#6721]
On another topic, I seem to have gotten my test solution in a state where the nuget UI is broken. Is this related to this issue in anyway?

![issue](https://user-images.githubusercontent.com/10507120/37743963-f39f2b38-2d29-11e8-94c4-3382282764d1.png)

How to repro the above:
1.	Get this solution: \\fsu\shares\MsEng\MSBuild\micodoba\investigations\ReadonlyCollection\App27-broken.zip
2.	Right click App5 -> manage nuget packages
3.	Try to install Xamarin.Forms

**Comment by PatoBeltran** [comment]
I have been investigating this issue. This is not a signing related issue. When we try to install `Xamarin.Forms` we do a restore and it tries to install all of it's dependencies. For some reason the file `Xamarin.Android.Support.Animated.Vector.Drawable.25.4.0.2.nupkg` has been modified when we try to extract it and that is why we see that error, the nupkg for the dependency is at one state that is unreadable. @mishra14 @nkolev92 any clue on why can this happen during restore?

**Comment by mishra14** [comment]
@PatoBeltran do you have a copy of the package?

**Comment by PatoBeltran** [comment]
it seems to not only be one dependency that is being modified as part of this process, but multiple.

**Comment by PatoBeltran** [comment]
The issue here is that the solution level packages folder had some packages that were not valid nupkgs. I will work on propagating a better error for this scenario.
