### ISSUE TITLE
Allow empty replacement tokens in NuspecProperties 

### ISSUE THREAD

**Issue by natemcmaster** [NuGet/Home#6722]
## Details about Problem
When using `<NuspecProperties>` and `<NuspecFile>` in .csproj, I cannot use empty replacement tokens. This is important sometimes because metadata may not always be available, or I may want it empty.

## Detailed repro steps so we can see the same problem

1. Create a project
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <NuspecFile>repro.nuspec</NuspecFile>
    <NuspecProperties>commithash=$(CommitHash)</NuspecProperties>
  </PropertyGroup>
</Project>
```
1. Create a nuspec like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>repro</id>
    <version>1.0.0</version>
    <authors>repro</authors>
    <description>Package from $commithash$</description>
    <dependencies />
    <repository type="git"
      url="http://github.com/NuGet"
      commit="$commithash$" />
  </metadata>
  <files>
    <file src="bin/Debug/netstandard2.0/repro.dll" target="lib/netstandard2.0/repro.dll" />
  </files>
</package>
```
2. `dotnet pack`

## Expected

Empty values in NuspecProperties are okay. Let nuspec validation decide when something is required or not.

## Actual

Pack fails with:

> /Users/namc/.dotnet/sdk/2.1.300-preview2-008367/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error : NuspecProperties should be in the form of "key1=value1;key2=value2". [/private/tmp/repro/repro.csproj]

## Details
```
$ dotnet --version
2.1.300-preview2-008367
```

@rohit21agrawal

**Comment by rohit21agrawal** [comment]
@natemcmaster if you packed the nuspec directly using nuget.exe , and didn't pass in the replacement token, what would you get?

**Comment by natemcmaster** [comment]
I don't have nuget.exe cuz I'm on macOS, but using nuget 4.3.0 from Mono I get this
```
$ nuget pack test.nuspec
Attempting to build package from 'test.nuspec'.
Successfully created package '/private/tmp/repro/repro.1.0.0.nupkg'.
$ nuget pack test.nuspec -properties commithash=
Attempting to build package from 'test.nuspec'.
Successfully created package '/private/tmp/repro/repro.1.0.0.nupkg'.
$ nuget pack test.nuspec -properties commithash=1234
Attempting to build package from 'test.nuspec'.
Successfully created package '/private/tmp/repro/repro.1.0.0.nupkg'.
```
In all cases, `nuget pack` doesn't complain. It just leaves `$commithash$` empty.

**Comment by rohit21agrawal** [comment]
interesting. should be a pretty simple fix, i will take a look tomorrow.
