### ISSUE TITLE
Disable LegacyVersionRule when MinClientVersion is high enough

### ISSUE THREAD

**Issue by fubar-coder** [NuGet/Home#6724]
## Details about Problem

When I create a `*.nupkg` with `dotnet pack`, then I get a warning from `LegacyVersionRule`. Currently, there is no way to disable this warning.

dotnet.exe --info:
```
.NET-Befehlszeilentools (2.1.102)

Product Information:
 Version:            2.1.102
 Commit SHA-1 hash:  8d409357db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17123
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.102\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

## Detailed repro steps so we can see the same problem

1. `dotnet new classlib`
2. Set `VersionPrefix` in `*.csproj` to `0.1.0`
3. Run `dotnet pack <yourproject>.csproj --version-suffix "alpha.1"`

## Other suggested things

I suggest that setting the `MinClientVersion` to `4.0` should disable this warning. Maybe a version of `3.5` is enough?

**Comment by rohit21agrawal** [comment]
@fubar-coder actually we have recently added a way to disable each warning for pack (or even elevate them to errors). This feature will be available in dotnet sdk 2.1.200 and VS 15.7

**Comment by fubar-coder** [comment]
How would this look like?

**Comment by nkolev92** [comment]
Dup of https://github.com/nuget/home/issues/5201
