### ISSUE TITLE
Package metadata API returns an empty string instead of an object in repository value

### ISSUE THREAD

**Issue by geneh** [NuGet/Home#6725]
## Details about Problem

Projects that contain repository field in nuspec have incorrect value in https://api.nuget.org/v3/catalog0/data/ API: `"repository": ""`.

Example 1:
https://api.nuget.org/v3-flatcontainer/castle.core/4.2.1/castle.core.nuspec contains 
`<repository type="git" url="https://github.com/castleproject/Core"/>` 
but https://api.nuget.org/v3/catalog0/data/2017.10.10.15.15.58/castle.core.4.2.1.json (catalogEntry in https://api.nuget.org/v3/registration3/castle.core/4.2.1.json) doesn't: `"repository": "",`

Example2:
https://api.nuget.org/v3-flatcontainer/newtonsoft.json/11.0.1/newtonsoft.json.nuspec:
`<repository type="git" url="https://github.com/JamesNK/Newtonsoft.Json"/>`
https://api.nuget.org/v3/catalog0/data/2018.02.17.23.26.12/newtonsoft.json.11.0.1.json (catalogEntry in https://api.nuget.org/v3/registration3/newtonsoft.json/11.0.1.json):
`"repository": "",`

Documentation:
https://docs.microsoft.com/en-us/nuget/api/package-base-address-resource#download-package-manifest-nuspec

https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource#registration-leaf

**Comment by zhili1208** [comment]
Moved to NuGetGallery
