### ISSUE TITLE
Unable to load service index for api.nuget.org/v3/index.json

### ISSUE THREAD

**Issue by neo0000** [NuGet/Home#6728]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 4.5.0.4685

dotnet.exe --version (if appropriate):

VS version (if appropriate): VS2017 version 15.5.6

OS version (i.e. win10 v1607 (14393.321)): win10 v1709

Worked before? If so, with which NuGet version: Worked before with same version: 4.5.0.4685

## Detailed repro steps so we can see the same problem

1. Accessing nuget.org via visual studio using NuGet Package Manager
2. Desktop is connected to the internet.
3. One item did appear from the list, which is Error occured from the NuGet Package Manager UI.
4. From the output window of VS2017 it says: 
[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
  The remote server returned an error: (502) Bad Gateway.
5. Tried to access API url: https://api.nuget.org/v3/index.json from the browser, and this is what it return:
![nuget_error](https://user-images.githubusercontent.com/37679573/37808553-ec9a35be-2e85-11e8-8a83-edf1bef5bab5.PNG)
6. Also tried to access API url from a different network but the problem still persist.

Thanks.

**Comment by zhili1208** [comment]
Moved to NuGetGallery
