### ISSUE TITLE
Nuget.exe verify, limitation for packages around 100MB and more

### ISSUE THREAD

**Issue by solekspen** [NuGet/Home#6730]
NuGet.exe version (4.6.0.4825)

Issue: If *.nuget packege around 100mb and more It can't be verified after signing.

nuget verify -signatures '*******.nupkg' -verbosity detailed
Signature Hash Algorithm: SHA256
**NU3008: The package integrity check failed.**
Signature type: Author
Verifying signature with author certificate:
Subject Name: CN=localhost
SHA1 hash: E36126C2829F97D0B22D6A90DFDFE9DE7CBA521B
Issued by: CN=localhost
Valid from: 2/20/2018 1:51:39 PM to 2/20/2019 1:51:39 PM

Finished with 1 errors and 0 warnings.
**Could not verify package(s) signature.**

Small nuget packeges pass verification:

nuget verify -signatures '*******.nupkg' -verbosity detailed
Signature Hash Algorithm: SHA256
Signature type: Author
Verifying signature with author certificate:
Subject Name: CN=localhost
SHA1 hash: E36126C2829F97D0B22D6A90DFDFE9DE7CBA521B
Issued by: CN=localhost
Valid from: 2/20/2018 1:51:39 PM to 2/20/2019 1:51:39 PM

Finished with 0 errors and 0 warnings.
**Successfully verified package(s).**

**Comment by rohit21agrawal** [comment]
@dtivel can you take a look?

**Comment by solekspen** [comment]
New NuGet Version: 4.6.1.5019
Resolved this issue

Thanks!
