### ISSUE TITLE
NuGet runs into dead lock in .Net Core project system (new regression).

### ISSUE THREAD

**Issue by lifengl** [NuGet/Home#6733]
Reported by Resharper: https://youtrack.jetbrains.com/issue/RSRP-468710

The repro can be found in the Resharper link.  The regression was introduced by https://github.com/NuGet/NuGet.Client/commit/e2fb49fed454bcdd48c53efcb40ba26a50be761e  

The bug is in https://github.com/NuGet/NuGet.Client/blame/e2fb49fed454bcdd48c53efcb40ba26a50be761e/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Services/NuGetLockService.cs

The code need pick up JoinableTaskContext from CPS for .Net Core project system and it is used to do that before that refactoring.  After the change, it picks up from VS Shell, and that context doesn't handle project lock dependencies, and can easily run into dead locks.

**Comment by rrelyea** [comment]
First showed up as a problem in 15.6.0-preview4.
Partially fixed this in 15.6.5 and fixed the rest in 15.7.0
