### ISSUE TITLE
Nupkg structure for multi OS platform and multi framework (45 - 471) support + net standard

### ISSUE THREAD

**Issue by ashishnegi** [NuGet/Home#6739]
I have a c# library. It has some different apis in netstandard than net47.

I want to generate a nupkg which should be usable from both .net specific framework and .net coreclr projects. So, if someone creates a fullframework net46/net47 project Or coreclr project targeting netcoreapp2.0 or net47, it should pick up dll based on its version. Also, for .net standard, since it targets multiple platform, I have `Linux` and `win` specific dll.

How should I structure my nupkg so that during compilation and packaging, it takes the right dll ?

I have the following structure of nupkg :

```
my_lib.NUPKG
|   my_lib.nuspec
|   [Content_Types].xml
|
+---lib
|   \---net45
|           my_lib.dll
|           my_lib.xml
|
+---package
|   \---services
|       \---metadata
|           \---core-properties
|                   f173822ccbd74dfb9a5338af5508d1b6.psmdcp
|
+---ref
|   \---netstandard2.0
|           my_lib.dll
|
+---runtimes
|   +---linux
|   |   \---lib
|   |       \---netstandard2.0
|   |               my_lib.dll
|   |
|   \---win
|       \---lib
|           +---net461
|           |       my_lib.dll
|           |
|           +---net462
|           |       my_lib.dll
|           |
|           +---net47
|           |       my_lib.dll
|           |
|           +---net471
|           |       my_lib.dll
|           |
|           \---netstandard2.0
|                   my_lib.dll  // this is different from above my_lib.dll
|
\---_rels
        .rels

```

This is working for most cases.

However, when user creates a .net sdk coreclr project targeting net471 using dotnet cli :
```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <TargetFramework>net47</TargetFramework>
</PropertyGroup>
```
during compilation, it refers to netstandard2.0 dll and fails to compile. If I comment out the incompatible apis, in the generated build, it has right net47 `my_lib.dll`. This means that during compilation `only`, it is referring to netstandard2.0 dll.  

I think that their might be something wrong with how I have structured my nupkg.
What is the right way for this ? Can you point me to some documentation around this ?

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 
```
NuGet.exe help
NuGet Version: 3.4.3.855
```

dotnet.exe --version (if appropriate):
```
.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```
VS version (if appropriate): `15.4.5`

OS version : `win 10 enterprise v1709 16299.309`

**Comment by jainaashish** [comment]
Please follow documentation from https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks to understand how to create a package which targets multiple target frameworks.

If you find, it doesn't help much, then please add comment there to help improve this further.

**Comment by ashishnegi** [comment]
@jainaashish  Thanks for sharing the document. It has good information. I am not able to sign in using twitter account on that page. Hence, unable to comment.  Can you tell :

If I have OS specific dll for netstandard, what is the hierarchy for lib folder. Should it be :

```
lib\netstandard2.0\win\my.dll
lib\netstandard2.0\linux\my.dll
```
