### ISSUE TITLE
Incompatible\unloaded projects are not available to be updated with NuGet VSUI.

### ISSUE THREAD

**Issue by ievgennaida** [NuGet/Home#6740]
We have solutions with a tons of projects.
And sometimes, probably because of visual studio bug, some of the projects are not loaded and market as **"incompatible"** when visual studio is started. (some of the unittests basically and after the reload click they are successfully loaded)

But the bad part that NuGet will skip such projects when you do the update with VSUI.

And a build will be successful while visual studio will skip those. 
So sometimes we get the commits where incompatible part of the solution is not updated.

But should VS UI really skips those? 

![image](https://user-images.githubusercontent.com/17121033/37922643-cd404b6a-3135-11e8-95bc-1df6db656c9a.png)

It it possible to show warning in the update box for this case?
![image](https://user-images.githubusercontent.com/17121033/37922910-8a262a10-3136-11e8-97b2-d920e1209e44.png)

I believe that user should get the information that some projects are unloaded and won't be updated.

Package Manager Console Host Version 4.5.0.4685

**Update:**
Unloaded projects are skipped there:
```


GetAllEnvDTEProjectsAsync(EnvDTE.DTE dte)

...
               // ProjectItems property can be null if the project is unloaded
                if (envDTEProjectItems != null)
                {
                    foreach (EnvDTE.ProjectItem envDTEProjectItem in envDTEProjectItems)
                    {
                        try
                        {
                            if (envDTEProjectItem.SubProject != null)
                            {
                                envDTEProjects.Push(envDTEProjectItem.SubProject);
                            }
                             
                        }
                        catch (NotImplementedException)
                        {
                            // Some project system don't implement the SubProject property,
                            // just ignore those
                        }
                    }
                }



```
It's possible to check project type to warn NuGet user about the unloaded projects:

    if (string.Compare(EnvDTE.Constants.vsProjectKindUnmodeled, envDTEProject.Kind, StringComparison.OrdinalIgnoreCase) == 0)
                {
                    // Project is unloaded. Not sure that also "incompatible", it's hard to reproduce that.
                    // Warning can be returned to inform client about the unloaded projects.
                }

`

**Comment by jainaashish** [comment]
NuGet doesn't have any information about unloaded projects so they are not even listed in NuGet Manager UI at solution level. So Can you even see the unloaded project in the NuGet UI?

**Comment by ievgennaida** [comment]
@jainaashish Yes, they are not listed and that's the problem.  
 
When solution is loaded and updated via NuGetVSUI than "incompatible" are skipped.
And sometimes developers even did not notice that. 
It will be very nice to have some kind of warning in this case.

P.s. NuGet.exe does the update for the same solution without any problems.

P.s.s.Was able to debug it and it's possible to return warning about the unloaded projects in the solution.

**Comment by jainaashish** [comment]
Thanks for the suggestion. But I'm afraid we'll be able to do anything there for next few cycles (meaning for next 6-8 months). NuGet.exe will work fine since it doesn't rely on dte project.

I understand you already debugged into it and knows some changes, but this is a design change which requires more discussion across teams and partners. Also, this has been the same behavior from beginning and not many customers have asked for it. So I'm going to close it as design for now, but if there are more feedback for this request then we'll certainly reconsider that.

**Comment by ievgennaida** [comment]
@jainaashish It's ok :).  Anyway this is just one of the annoying small issues that we have faced and I believe that product can be more friendly without those.
