### ISSUE TITLE
Copying content files into the install project wwwroot folder

### ISSUE THREAD

**Issue by SergeySagan** [NuGet/Home#6743]
I already have a SO going on this issue, but it is not getting any response: https://stackoverflow.com/questions/49425012/dotnet-core-nuget-package-copying-content-files-on-restore

The problem is I need a way to copy `contentFiles` into the `wwwroot` folder of the project that is installing my `NuGet` package. 

I can get a reference to it to show up in `Visual Studio` using this XML in the `NuGet` source project's `csproj`:

```
  <ItemGroup>
    <Content Include="Scripts\js\Utility.js">
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\wwwroot\js\</PackagePath>
      <CopyToOutputDirectory>true</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
```

The problem is that when I try to reference that file in my web project it can not find my `Utility.js`, how do I get an actual copy of that content file in my installing project?

**Comment by purplepiranha** [comment]
I'm trying to find a way to do this as well - been speaking to @Serjster on SO.

Hope someone has some insight.

**Comment by purplepiranha** [comment]
Been looking into his some more today:

From: [Announcing NuGet 3.1 with Support for Universal Windows Platform](https://blog.nuget.org/20150729/Introducing-nuget-uwp.html#deprecated-features)

Importing content from a Nuget package was depreciated for projects using a project.json file in Nuget v3.1. Since then the project.json file has been dropped in favour of the new .csproj format. Importing content from a Nuget package should still work though if you're using the packages.config file instead.

Also mentioned is the fact that there are other package managers available for delivering content.

It looks to me like the answer in the new world is to create a node module containing utility.js and let npm deliver it to your project.

**Possible Workaround:**
I've looked at .targets to copy files and got this working, but it does run on each build - which may or may not be a problem for you. I can't do what I want with it.

![image](https://user-images.githubusercontent.com/15064668/38137858-47e5e1e0-341f-11e8-88ca-63eb5894958f.png)

In [PackageId].targets:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <!-- Either do this for all scripts in the Scripts/js folder -->
   <Target Name="CopyScriptsToProject" BeforeTargets="Build">
      <Message Text="Copying scripts to project" />
         <ItemGroup>
            <SourceScripts Include="$(MSBuildThisFileDirectory)..\..\content\Scripts\js\**\*.*"/>
         </ItemGroup>
         <Copy 
            SourceFiles="@(SourceScripts)"
            DestinationFiles="@(SourceScripts -> '$(MSBuildProjectDirectory)\wwwroot\js\%(RecursiveDir)%(Filename)%(Extension)')"
            Condition="!Exists('$(MSBuildProjectDirectory)\wwwroot\js\%(RecursiveDir)%(Filename)%(Extension)')"
         />
   </Target>
   <!-- Or do this for the individual script -->
   <Target Name="CopyUtilityScriptToProject" BeforeTargets="Build">
       <Copy      
          SourceFiles="$(MSBuildThisFileDirectory)..\..\content\Scripts\js\Utility.js"
         DestinationFiles="$(MSBuildProjectDirectory)\wwwroot\js\Utility.js"
         Condition="!Exists('$(MSBuildProjectDirectory)\wwwroot\js\Utility.js')"
        />
  </Target>
</Project>
<!-- Note: condition can be removed from either if you want it to overwrite each build -->
```
and in the .csproj file (replacing [PackageId] with the name of your package):
```xml
<Project Sdk="Microsoft.NET.Sdk">

  ... any Globals for source control stuff ...

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <Version>7.0.0</Version>
    <PackageId>[PackageId]</PackageId>
  </PropertyGroup>

... any PackageReference stuff ...

  <ItemGroup Label="Packaging">
    <Content Include="build\netcoreapp2.0\[PackageId].targets" PackagePath="build\netcoreapp2.0\[PackageId].targets" />
   <!-- Either -->
    <Content Include="Scripts\js\**\*.*" PackagePath="content\Scripts\js;contentFiles\Scripts\js" />
   <!-- or -->
   <Content Include="Scripts\js\Utility.js" PackagePath="content\Scripts\js;contentFiles\Scripts\js" />
  </ItemGroup>
</Project>
```

There seemed to be a bug whereby when the ```<PackageId>[PackageId]</PackageId>``` wasn't set explicitly in the .csproj, the build targets didn't work. Although that may well be an issue with my development environment.

**Comment by rohit21agrawal** [comment]
@Serjster having a file in contentFiles folder with copyToOutput set to true will copy the file in the build output folder right before the build starts. are you not seeing the wwwroot folder in your build output directory?

**Comment by SergeySagan** [comment]
We certainly tried that and the file certainly did not copy to the wwwroot folder.

**Comment by rohit21agrawal** [comment]
@Serjster instead of CopyToOutputDirectory , can you set ``` PackageCopyToOutput``` true on your Content ItemGroup files and give it a shot?

**Comment by purplepiranha** [comment]
I can't get either of those options to work. They get copied to bin, but they can't be used from within the project.

**Comment by rohit21agrawal** [comment]
can you show me your .g.props and .g.targets file? It should be under the obj folder

**Comment by purplepiranha** [comment]
**copyToOutput=true**

props:

```xml<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
<RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">C:\Users\Paul\documents\visual studio 2017\Projects\Testing123\WebApplication1\obj\project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Paul\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.6.1</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props')" />
  </ImportGroup>
</Project>
```

targets:
```xml<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)netstandard.library\2.0.0\build\netstandard2.0\NETStandard.Library.targets" Condition="Exists('$(NuGetPackageRoot)netstandard.library\2.0.0\build\netstandard2.0\NETStandard.Library.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration.usersecrets\2.0.1\build\netstandard2.0\Microsoft.Extensions.Configuration.UserSecrets.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration.usersecrets\2.0.1\build\netstandard2.0\Microsoft.Extensions.Configuration.UserSecrets.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.3\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.3\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.all\2.0.6\build\netcoreapp2.0\Microsoft.AspNetCore.All.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.all\2.0.6\build\netcoreapp2.0\Microsoft.AspNetCore.All.targets')" />
  </ImportGroup>
</Project>
```

**or for PackageCopyToOutput=true**

props:

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">C:\Users\Paul\documents\visual studio 2017\Projects\Testing123\WebApplication1\obj\project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Paul\.nuget\packages\;C:\Program Files\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">4.6.1</NuGetToolVersion>
  </PropertyGroup>
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.props')" />
  </ImportGroup>
</Project>
```

targets:

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
  </PropertyGroup>
  <ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <Import Project="$(NuGetPackageRoot)netstandard.library\2.0.0\build\netstandard2.0\NETStandard.Library.targets" Condition="Exists('$(NuGetPackageRoot)netstandard.library\2.0.0\build\netstandard2.0\NETStandard.Library.targets')" />
    <Import Project="$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets" Condition="Exists('$(NuGetPackageRoot)microsoft.netcore.app\2.0.0\build\netcoreapp2.0\Microsoft.NETCore.App.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration.usersecrets\2.0.1\build\netstandard2.0\Microsoft.Extensions.Configuration.UserSecrets.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.configuration.usersecrets\2.0.1\build\netstandard2.0\Microsoft.Extensions.Configuration.UserSecrets.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.3\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.3\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets')" />
    <Import Project="C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.all\2.0.6\build\netcoreapp2.0\Microsoft.AspNetCore.All.targets" Condition="Exists('C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.all\2.0.6\build\netcoreapp2.0\Microsoft.AspNetCore.All.targets')" />
  </ImportGroup>
</Project>
```

**Comment by rohit21agrawal** [comment]
it doesn't look like your package with contentFiles has it setup correctly, otherwise those files will be listed above. Can you send me the package? (also make sure you restore to see the updated .g.props and targets file)

**Comment by purplepiranha** [comment]
I could send the package, but you're right. I just checked, neither of those packages have any contentFiles - I have no idea why. My packages from earlier did, but I did so many tests that I don't know which is which.

My script that I want included is at 'Scripts\js\Utility.js'

Perhaps it may be easier if you give an example of how this would look is a working .csproj?

**Comment by rohit21agrawal** [comment]
@purplepiranha  attached an example project for you that creates a package with contentFiles that will be copied to output directory 
[contentfilesexample.zip](https://github.com/NuGet/Home/files/1873751/contentfilesexample.zip)


The file will also be available as any other ``` Content ``` would be in the project.

**Comment by SergeySagan** [comment]
`PackageCopyToOutput` does not seem to work, here's a GitHub: https://github.com/SaganMarketing/NuGetContentFiles

**Comment by rohit21agrawal** [comment]
@Serjster when you point to a GitHub repo, please also provide instructions/steps on what I am supposed to look for?

I have pasted a sample project in my previous comment, which if you run dotnet pack on, will create a nuget package with a content file. You should try installing that package in your project, and inspect your .g.props and .g.targets file in the obj folder, and check your bin output directory to see if the file gets copied.

**Comment by purplepiranha** [comment]
Thanks @rohit21agrawal for the sample project. This does copy the file to bin output directory and it also shows in solution explorer in the right place:

![image](https://user-images.githubusercontent.com/15064668/38298050-1bca2ea4-37ee-11e8-8f7a-f0eb147198af.png)

However, when you try to use it, it cannot be found. Ive just put `<script src="~/js/Utility.js"></script>` before the `</body>` tag on a page to test this, and get the following result when running:

![image](https://user-images.githubusercontent.com/15064668/38298169-8e4e98e8-37ee-11e8-8110-badfafa73a49.png)

**Comment by SergeySagan** [comment]
@rohit21agrawal The GitHub has a TestParent which creates the package and the a TestChild which consumes that package, and as @purplepiranha mentioned it only creates a ref to the file, it doesn't actually copy it into the TestChild so that when you try to reference it via like a web call, the file is not actually there and therefore that reference is pretty much useless.

**Comment by rohit21agrawal** [comment]
@Serjster @purplepiranha can you help me understand how you are trying to use the file from the package?

CC: @jainaashish since he has more context in the area

**Comment by jainaashish** [comment]
@Serjster in yout GitHub repro https://github.com/SaganMarketing/NuGetContentFiles, `PackagePath` for this content is not correct which is why it was included in TestChild.

```
<ItemGroup>
    <Content Include="Scripts\Utility.js">
      <Pack>true</Pack>
      <!--<PackagePath>contentFiles\all\all\wwwroot\js\;content\all\all\wwwroot\js\</PackagePath>-->
      <PackagePath>contentFiles\all\all\wwwroot\js\</PackagePath>
        <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>
```

Update` <PackagePath>contentFiles\all\all\wwwroot\js\</PackagePath>` to ` <PackagePath>contentFiles\any\any\wwwroot\js\</PackagePath>`

That should fix it, let us know if it still see this issue.

**Comment by SergeySagan** [comment]
Thanks for that. Even after fixing that however, it does not copy the file. Please see image: 
![nuget-gh](https://user-images.githubusercontent.com/3606218/38347836-33667884-385b-11e8-9e24-14e4f9f06174.png)

**Comment by jainaashish** [comment]
It will not copied into project, rather it will always be available as link item. So it will be kind of immutable content which is available to be consumed but to be updated. And since you also set `CopyToOutput` to true, then this file will be copied into `/bin` folder.

**Comment by SergeySagan** [comment]
That is completely useless to me. I need the file to be copied from the package when I build... the actual file,.. one that I can serve up via HTTP into my `wwwroot\js` folder! I tried using a TypeScript file there, but the compiler freaks out trying to compile that as well. If we can't include JS, which is so crucial to web content... then this does not meet the need. We need a solution that actually copies the content... and please don't point to using tools like `npm`, `NuGet` should be able to do this!

**Comment by rohit21agrawal** [comment]
@Serjster forgive me for my lack of experience with web projects, but could you help me understand if ```wwwroot``` is a special folder that ASP.NET looks for in the project root directory? Is this location configurable?

Would having javascript files as embedded resource instead of content help?

**Comment by SergeySagan** [comment]
Yes `wwwroot` is a special folder in ASP.NET, `wwwroot` is not really configurable, there might be a way but.. the simple answer is no. No, `Embeded Resource` will not help.

**Comment by jainaashish** [comment]
Again, this will always work fine in production since all these files will be copied on deployment. And for debugging, you can use MSBuild to physically copy and unblock yourself.

**Comment by SergeySagan** [comment]
Why must I use `MSBuild` to do this? Can I configure this in my package, to run this `MsBuild` copy step? If so, how? What if we have thousands of projects consuming our package, will each of them need to add this build step? This is not a workable solution unless the package can be configured to do so.

**Comment by jainaashish** [comment]
`Why must I use MSBuild to do this?`
Because this is currently not supported and if you want to unblock yourself immediately then you must do this, otherwise ignore it. Meantime, we'll work with ASP.NET team to understand the whole scenario and come up with right solution for this.

Yes, you can configure it in your package itself, add a .target file in build folder of your project which contains a beforeBuild target which copy this file in appropriate location. That way whichever project consumes this package, will have that target available.

**Comment by rohit21agrawal** [comment]
@Serjster here is an example of using a targets file to achieve the copying:

Create a ```build``` folder in your package, and have a targets file with the name ``` <packageId>.targets``` .

The targets file will look something like this:

```

<ItemGroup>  
        <MySourceFiles Include="..\scripts\a.js;..\scripts\b.js;..\scripts\c.js"/>  
    </ItemGroup>  
  
    <Target Name="CopyFiles" BeforeTargets="Build">  
        <Copy  
            SourceFiles="@(MySourceFiles)"  
            DestinationFolder="$(MSBuildProjectDirectory)"  
        />  
    </Target>  
  

```

If you end up using the build targets approach, you don't need to have ```contentFiles``` in your package

**Comment by SergeySagan** [comment]
Using that `targets` file worked. I pushed the changes so the repo here works now: https://github.com/SaganMarketing/NuGetContentFiles

Thanks for your help. It sounds like you will connect with ASP.NET team to see if this can be made easier? In any case, using this work around is acceptable to me. Thanks again.

**Comment by demonguru18** [comment]
Here is the answer: Right-Click on Project > Manage Client Side Libraries Asp.Net will add libman.json File to your Project in the file for libraries add this: In this Example I have added packages for Bootstrap 4
```
{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "twitter-bootstrap@4.1.3",
      "destination": "wwwroot/lib/bootstrap/dist",
      "files": [
        "js/bootstrap.min.js",
        "js/bootstrap.js",
        "css/bootstrap.min.css",
        "css/bootstrap-reboot.css",
        "css/bootstrap-grid.css",
        "css/bootstrap.css"
      ]
    },
    {
      "library": "jquery@3.3.1",
      "destination": "wwwroot/lib/jquery/dist",
      "files": [
        "jquery.min.js",
        "jquery.js"
      ]
    },
    {
      "library": "popper.js@1.14.4",
      "destination": "wwwroot/lib/popper.js/dist",
      "files": [
        "esm/popper-utils.min.js",
        "esm/popper.js",
        "umd/popper-utils.min.js",
        "umd/popper.min.js",
        "popper.min.js",
        "popper-utils.min.js"

      ]
    }
  ]
}
```

**Comment by tiagoavila** [comment]
I've followed the @Serjster 's example and changed a little bit to generate the files inside ProjectDiretory instead of MSBuildProjectDirectory. 

That's my csproj file:

>  
    <ItemGroup Label="Packaging">
        <Content Include="build\PackageToGenerateFile.targets" PackagePath="build\PackageToGenerateFile.targets" />

        <Content Include="scriptsToGenerate/*.js">
          <Pack>true</Pack>
        </Content>
    </ItemGroup>

That's my targets file:

>
    <Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <ItemGroup>
          <SourceScriptFiles Include="$(MSBuildThisFileDirectory)..\content\scriptsToGenerate\*.js" />
      </ItemGroup>
      <Target Name="CopyScriptsToProject" BeforeTargets="Build">
          <Copy SourceFiles="@(SourceScriptFiles)" DestinationFolder="$(ProjectDir)\wwwroot\js\scriptsToGenerate\"
        />
      </Target>
    </Project>

You can see the repo for this here [https://github.com/tiagoavila/NugetGeneratingFilesInDestinationProject](https://github.com/tiagoavila/NugetGeneratingFilesInDestinationProject)

**Comment by TaiNguyen2406** [comment]
Is there any new solutions for this case?
Do I still need to use Msbuild target?

**Comment by SaveliyShur** [comment]
> <PackageCopyToOutput>true</PackageCopyToOutput>

Thank you for your example
