### ISSUE TITLE
Can't fix account login for old MSFT account

### ISSUE THREAD

**Issue by eschneider999** [NuGet/Home#6749]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)

If this link worked......
(http://github.com/nuget/nugetgallery/issues)

**Comment by mishra14** [comment]
This issue was moved to NuGet/NuGetGallery#5707
