### ISSUE TITLE
nuget.exe 4.3 uses V2 endpoint when list

### ISSUE THREAD

**Issue by morad3741** [NuGet/Home#6751]
HI,
im using nuget.exe on mac (NuGet Version: 4.3.0.4406)
ive notice the list command uses V2 endpoint:
````
nuget list jquery -Source nuget.org  -verbosity detailed
````
````
NuGet Version: 4.3.0.4406
  GET https://www.nuget.org/api/v2/$metadata
  OK https://www.nuget.org/api/v2/$metadata 981ms
  GET https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='jquery'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
  OK https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm='jquery'&targetFramework=''&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0 865ms
````
1. is the V3 search service been used already?
2. on which version you will start using the V3 search service?

**Comment by joelverhagen** [comment]
Hey @morad3741, you are correct that `nuget.exe list` indeed uses the V2 protocol for list. In fact, even if you explicitly provide the V3 source URL to nuget.exe, V2 will still be used.

**Same output:**
```
nuget.exe list NuGet.Versioning -Source https://api.nuget.org/v3/index.json -verbosity detailed
nuget.exe list NuGet.Versioning -Source https://www.nuget.org/api/v2 -verbosity detailed
```

This is done via the `LegacyGallery` resource in the V3 service index. 

> is the V3 search service been used already?

Yes, it is used for other scenarios. For example, when you use the "Browse" tab in Visual Studio, this hits the V3 search service ([REST API docs](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource)).

> on which version you will start using the V3 search service?

There is no plan to do this today. Could you explain why this is important? 

Also, as a side note, we implement the V2 search requests internally by delegating queries to the same back-end service that handles V3 search requests. 

Another related work item you may be interested is https://github.com/NuGet/Home/issues/6060, which tracks getting the `nuget.exe list` feature on .NET CLI. This is in the backlog for us but you can keep an eye on that issue for activity.

**Comment by mishra14** [comment]
@morad3741 Please let us know if you are blocked by this or if you have feature/design change request.

**Comment by morad3741** [comment]
Thanks for the detailed answer,
Im not blocked by this just wanted to know how Nuget.CLI work.

I thought Visual Studio rely only on Nuget.CLI , so when you use the "Browse" tab VS make direct call to the V3 search api ?.

**Comment by joelverhagen** [comment]
> I thought Visual Studio rely only on Nuget.CLI

Visual Studio does not call into nuget.exe directly. Instead, both Visual Studio and nuget.exe call into some common NuGet libraries. For example, the code that implements the client side of the V2 and V3 protocol is in the [NuGet.Protocol](https://www.nuget.org/packages/NuGet.Protocol) library.

> so when you use the "Browse" tab VS make direct call to the V3 search api ?.

That's right, assuming you have the V3 source URL configured (https://api.nuget.org/v3/index.json) which is the default on a new installation of Visual Studio.

**Comment by mishra14** [comment]
Closing this as a question. Please let us know if you need any more info.
