### ISSUE TITLE
Cannot restore with fallbacks and unknown framework

### ISSUE THREAD

**Issue by mhutch** [NuGet/Home#6752]
I have a project that has a custom framework that's not known to NuGet. However, it also defines `PackageTargetFallback` and `PackageAssetFallback` to both be `netstandard2.0`, as the framework is compatible with .net standard 2.0.

When I try to restore it, I get `Invalid restore input. Invalid target framework 'unsupported'.`

**Comment by rohit21agrawal** [comment]
is there a repro project you can provide @mhutch  ?

**Comment by mhutch** [comment]
@rohit21agrawal not easily, it requires building [a fork of Unreal Engine](https://mono-ue.github.io/) from source :/

**Comment by PatoBeltran** [comment]
Will close this since we don't have a way to repro it. Please feel free to reopen this issue if it is still problematic and there is a way we can work on it.
