### ISSUE TITLE
ResolveNuGetPackageAssets allocates 3.7% of solution-wide design-time build

### ISSUE THREAD

**Issue by nguerrera** [NuGet/Home#6755]
_From @davkean on September 26, 2017 12:55_

This is literally turning text -> text, can we do this without NewtonSoft.Json? Otherwise, try the lower level reader API that JSON.NET has?
![image](https://user-images.githubusercontent.com/1103906/30861318-ab9065ec-a30d-11e7-98ce-04584375a089.png)

_Copied from original issue: dotnet/sdk#1605_

**Comment by nguerrera** [comment]
_From @davkean on October 4, 2017 23:16_

Some of this allocations is due to reading line annotations - turn that off via JsonLoadSettings.LineInfoHandling.

**Comment by nguerrera** [comment]
This is the version of package resolution for non-SDK projects. cc @Pilchie Does this go in project-system or nuget?

**Comment by nguerrera** [comment]
_From @Pilchie on February 5, 2018 22:28_

project-system has tended to make the changes, but the code lives at https://github.com/NuGet/NuGet.BuildTasks/.

**Comment by rohit21agrawal** [comment]
my understanding was that the build tasks in NuGet.BuildTasks are actually owned by @Pilchie 's team, and not NuGet even though they live in our repository.

CC: @rrelyea

**Comment by nguerrera** [comment]
Yes, I understood as much from https://github.com/NuGet/Home/issues/6755#issuecomment-377583085

I also interpreted that as implying I should file the bug where the code lives, which is why I moved it here.

**Comment by nkolev92** [comment]
Moved from: https://github.com/dotnet/NuGet.BuildTasks/issues/81
