### ISSUE TITLE
Nuget.CLient: rename the target directory 'packages' to 'nuget'

### ISSUE THREAD

**Issue by zosrothko** [NuGet/Home#6765]
## Details about Problem

When installing a Nuget package into a VisualStudio project, nuget.exe pulls the downloaded files in a subdirectory named `packages`. This name is too mush generic and may clash with others packaging tools. This issue is requesting to change the name of the `packages`directory to a more nuget specific name: `nuget` would be the best choice IMO.

C:\Users\fandre\Documents\git\poco-1.9.1>"C:\Program Files (x86)\NuGet\nuget.exe"
NuGet Version: 4.5.1.4879

**Comment by rohit21agrawal** [comment]
@zosrothko this behavior is already configurable by setting the ```repositoryPath``` in your nuget.config file.

See : https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior

**Comment by zosrothko** [comment]
OK for setting the repositoryPath as a local matter. But can you consider this renaming as a global Nuget change so that no configuration has to be done on a third party computer for a zero config fonctionality?

**Comment by rohit21agrawal** [comment]
Unfortunately no, this will be too big of a breaking change and we cannot change the default

**Comment by zosrothko** [comment]
OK, so can you add a new option to setup locally all receiving directories name as for example

nuget config -set repositoryName='nuget'
