### ISSUE TITLE
Downgrade is not overriden by direct package dependency

### ISSUE THREAD

**Issue by pakrym** [NuGet/Home#6766]
1. `git clone git@github.com:aspnet/IISIntegration.git`
2. `cd IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration`
3. `git checkout pakrym/downgrade-repro `
3. `dotnet restore`

Expected:

Direct dependency on `Microsoft.AspNetCore.Http.Extensions (>= 2.1.0-a-preview2-mpr-16655)` overrides the downgrade error (as stated in error message)

Actual:

```
D:\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration [pakrym/downgrade-repro ≡]> dotnet restore
  Restoring packages for D:\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\Microsoft.AspNetCore.Server.IISIntegration.csproj...
D:\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\Microsoft.AspNetCore.Server.IISIntegration.csproj : error NU1605: Detected package downgrade: Microsoft.AspNetCore.Http.Extensions from 2.1.0-preview2-30500 to 2.1.0-a-preview2-mpr-16655. Reference the package directly from the project to select a different version.
D:\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\Microsoft.AspNetCore.Server.IISIntegration.csproj : error NU1605:  Microsoft.AspNetCore.Server.IISIntegration -> Microsoft.AspNetCore.HttpOverrides 2.1.0-preview2-30500 -> Microsoft.AspNetCore.Http.Extensions (>= 2.1.0-preview2-30500)

D:\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\Microsoft.AspNetCore.Server.IISIntegration.csproj : error NU1605:  Microsoft.AspNetCore.Server.IISIntegration -> Microsoft.AspNetCore.Http.Extensions (>= 2.1.0-a-preview2-mpr-16655)
```

/cc @emgarten

**Comment by nkolev92** [comment]
It should not be overriden in your case.  

This error in particular is about a closer package overriding the version requested by more distant packages. 

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings#nu1605

This is normally a warning, so you very likely have TreatWarningsAsErrors set to true. 

You have 2 choices here:
- [ ] Add NU1605 to NoWarn.
- [ ] Add a version of Microsoft.AspNetCore.Http.Extensions, that doesn't break the graph for Microsoft.AspNetCore.HttpOverrides
