### ISSUE TITLE
The position of "Get more info about installation options" link should be changed.

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#677]
After localization, the labels could be much longer than in English:

![image](https://cloud.githubusercontent.com/assets/2679220/7868102/8e3db802-052e-11e5-875a-d20045713006.png)

Seems it's better to change the position of the link so that its left is the same as the labels instead of the drop down boxes.

**Comment by yishaigalatzer** [comment]
The link should also wrap if it is too long
