### ISSUE TITLE
Update-Package ignores PackageReference version range

### ISSUE THREAD

**Issue by chlowell** [NuGet/Home#6775]
## Details about Problem
NuGet product used: Package Manager Console
VS version: 15.7

## Repro
1. Start with a csproj and PackageReference with an exact version range, for example:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="[9.0.1]" />
  </ItemGroup>
</Project>
```
2. From the Package Manager Console, run Update-Package.
```
> Update-Package
Restoring packages for ...

Installing NuGet package Newtonsoft.Json 11.0.2.
...
Successfully uninstalled 'Newtonsoft.Json 9.0.1' from ConsoleApp1
...
Successfully installed 'Newtonsoft.Json 11.0.2' to ConsoleApp1
```

Installing the newer version is unexpected because version range constraints are legal for PackageReference, and Update-Package respects them in `packages.config`. For example, given 
`<package id="Newtonsoft.Json" version="9.0.1" allowedVersions="[9.0.1]" />`, it doesn't install a newer version.

**Comment by rohit21agrawal** [comment]
@chlowell thanks for the feedback! we will look into it, just a quick question - did this scenario work for you before and has regressed in 15.7 preview builds?

**Comment by chlowell** [comment]
No, it doesn't work in 15.6.4 either.

**Comment by davevans** [comment]
Thanks @chlowell  - having the same issue as outlined here - https://stackoverflow.com/questions/49398602/constrain-packagereference-upgrade-version-when-update-package-run/

**Comment by chlowell** [comment]
@rohit21agrawal has this been triaged or investigated yet?

**Comment by rohit21agrawal** [comment]
yes, we will look at at it for 15.8 possibly.

**Comment by chlowell** [comment]
Please do. This bug blocks a scenario which no other tool covers today and adds friction to .NET Core migrations.
