### ISSUE TITLE
nuget install fails and reports wrong constraint info.

### ISSUE THREAD

**Issue by kingerja** [NuGet/Home#6788]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version:
latest version 4.6.2 also present in nuget 3.5.0

OS version (i.e. win10 v1607 (14393.321)): 
win10 v1703 15063.966

Worked before? If so, with which NuGet version:
not sure it worked before.

## Detailed repro steps so we can see the same problem

1.  md d:\tmp\foo
2.  cd /d d:\tmp\foo
3.  nuget.exe  install Microsoft.SqlServer.FiniteStateMachines.MOSM -version 150.500.9 -source \\joshking-dev\dump\nuget\issues\ds-feed;https://msdata.pkgs.visualstudio.com/DefaultCollection/_packaging/SQLDS_Shared/nuget/v3/index.json /verbosity detailed

## Other suggested things
The real issue is
packages:
Microsoft.SqlServer.FiniteStateMachines.MOSM
Microsoft.SqlServer.FiniteStateMachines.MOSM.XEvents
have a dependency on a missing package of 
Microsoft.SqlServer.FiniteStateMachines.Common.XEvents

The actual error below is incorrect.
### Verbose Logs

Attempting to resolve dependencies for package 'Microsoft.SqlServer.FiniteStateMachines.MOSM.150.500.9' with DependencyBehavior 'Lowest'
Unable to find a version of 'hostregdll' that is compatible with 'Microsoft.Xdb.Common.Runtime 150.500.9 constraint: hostregdll (= 150.500.9)'.
System.InvalidOperationException: Unable to find a version of 'hostregdll' that is compatible with 'Microsoft.Xdb.Common.Runtime 150.500.9 constraint: hostreg
dll (= 150.500.9)'. ---> NuGet.Resolver.NuGetResolverConstraintException: Unable to find a version of 'hostregdll' that is compatible with 'Microsoft.Xdb.Comm
on.Runtime 150.500.9 constraint: hostregdll (= 150.500.9)'.
   at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by ghost** [comment]
Due to lack of recent activity, this issue has been marked as a candidate for icebox cleanup. It will be closed if no further activity occurs within 14 more days. Any new comment (by anyone, not necessarily the author) will add a `Triage:NeedsTriageDiscussion` label and lead to a triaging process.
This process is part of the experimental [Stale icebox issues cleanup](https://github.com/NuGet/Home/issues/12113) we are currently trialing. Please share any feedback you might have in the linked issue.
