### ISSUE TITLE
[Test Failure][Signing] Test Certificate can’t be created on the Developer Command Prompt 

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#6791]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet Version: NuGet Client release-4.7.0-preview3\5059
VS Version: D15.7stg 27608.3000
OS Version: Windows 10 RS3_Release 16299.15.170928-1534
                                         
Installation steps:
Full install VS2017: \\cpvsbuild\drops\VS\d15.7stg\products\27608.3000\bootstrappers\Enterprise\vs_enterprise.exe --quiet --wailt --all –includeoptional 

## Detailed repro steps so we can see the same problem

1. Git clone https://github.com/NuGet/Entropy.git.
1. Open Developer Command Prompt for VS. 
2. Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority.

### Expected: 

Test Certificate should be created successfully.

### Actual: 

Test Certificate can’t be created as below.
![error](https://user-images.githubusercontent.com/20632775/38487917-4ddc9e2c-3bd1-11e8-837c-ce2e019b2604.png)

### Error message:
.\CreateTestCertificate.ps1 : File C:\Entropy\TestCertGenerator\CreateTestCertificate.ps1 cannot be loaded. The file
C:\Entropy\TestCertGenerator\CreateTestCertificate.ps1 is not digitally signed. You cannot run this script on the
current system. For more information about running scripts and setting execution policy, see about_Execution_Policies
at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by mishra14** [comment]
This is a powershell execution policy issue. As @dtivel responded to the mail, this should be fixed by following the steps - 

1.	Open Task Manager.
2.	Navigate on the main menu to File | “Run new task.”
3.	In the Open textbox type:
              `powershell -ExecutionPolicy Bypass`
4.	Enable the option “Create this task with administrative privileges.”
5.	Click OK.
