### ISSUE TITLE
"An item with the same key has already been added" - when project graph has projectName == packageRef name (of same version)

### ISSUE THREAD

**Issue by ceddlyburge** [NuGet/Home#6795]
The problem occurs when a dll is referenced as a nuget package and as a project reference.

If there are 3 projects, `Source`, `Intermediate` and `DoublyReferencedTarget`

Then the problem will occur when `Source` has:
- ProjectReference to project `Intermediate`
- ProjectReference to project `DoublyReferencedTarget`

And 'Intermediate' has 
- PackageReference to project `DoublyReferencedTarget`. 

Thus project DoublyReferencedTarget is referenced twice in two different ways, which creates this error.

I realise that this is a genuine error, but a better error message would be very useful. Some of our solutions contains 100's of projects (a bad idea I know), and it's just taken me a week to track down this problem.

I have created a repo to demonstrate the problem at https://github.com/ceddlyburge/nuget-error.

**Comment by nkolev92** [comment]
@ceddlyburge 
I am unable to reproduce this with the latest 15.7 preview.

Which version of VS are you using?

**Comment by laszlohorvath** [comment]
I am able to reproduce it with the demo repo. VS 2017 Ent 15.6.6

And we also have this issue, and it is a quite big problem here, I've spent days to solve it, but we were unable to. So any help (hotfix, workaround, etc...) would be appreciated.

**Comment by ceddlyburge** [comment]
Hi there, I am on VS 2017 Professional 15.6.4

I also get the problem on the command line using nuget 4.3.0.4406, which in turn uses msbuild 15.6.82.30579

**Comment by MisterJimson** [comment]
Running into this as well...

**Comment by natemcmaster** [comment]
Ran into this as well with VS 15.9. Anyone found a solution?

**Comment by JosepBalague** [comment]
NuGet 4.9.2.5706 (nuget restore), msbuild version '15.9.21.664', VS2017 15.9.6 still failing. When this will be solved?

**Comment by bdongus** [comment]
Nuget 4.9.3.5777, VS2017 15.9.11. This still is an issue.

**Comment by thyn** [comment]
vs19 same issue

**Comment by GraySerg** [comment]
VS 2019 same error

**Comment by ivankarpey** [comment]
This is insane to see such a problem exist for such a long time without any response or workaround provided by the Nuget team. As I still could confirm these issues exist (vs 2019, .net core 3.0 preview) the simple workaround is to change the version of a package you do reference in sources. With the new version, it should start working fine.

**Comment by zivkan** [comment]
I was able to reproduce the error. The exception is thrown here: https://github.com/NuGet/NuGet.Client/blob/3113c5ddf420ae0c9c34959108e127136c8f141e/src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs#L152

The issue appears to be that the same name+version pair is both a package and a project reference. If they had different versions, it would work, or if it was consistently a package or a project reference both times, I expect it would work.

My initial reaction is that the assets file might need to change to support this scenario, rather than being a simple bug to fix.

**Comment by zivkan** [comment]
From the sample, if we remove the project reference to `intermediate` from `source`, `source` can reference both the package and project and it works fine, NuGet selects the project. This "prefer project over package" logic doesn't appear to be happening for transitive dependencies, which I think is the bug.

**Comment by redwyre** [comment]
I got this message, which I was able to fix by converting the project to the new project format. Have no idea what the real problem was.

**Comment by morbidcamel101** [comment]
Hey so I got this issue when doing some coding and adding a reference to a project that was already in the project as a nuget package. I removed the nuget package - added a project reference but the dotnet restore command failed. A work-around was to change the version number of the referenced project.

**Comment by MABrunner** [comment]
Thanks for this commit!  Will this fix the issue in Visual Studio itself, or in the DevOps pipelines?  Or neither?

**Comment by KrabatTilt** [comment]
I had the same issue using a TeamCity CI Pipeline. But I cloud slove the problem by switching to dotnet cli to restore packages. 
The difference is that the _NuGet.exe restore_ command targets the whole .sln file whereas the _dotnet.exe restore_ command can be configured to target only a certain .csproj file.

All my projects have the new csproj format and use PackageReference instead of packages.config file.

**Comment by madaleno** [comment]
It would be nice that the error message mentions the duplicate package that NuGet found.
In big solutions it's hard to find what that duplicate package is.

**Comment by colinin** [comment]
我也遇到了这个问题，把通过项目直接引用的包去掉，改为通过Nuget引用可以解决这个问题

**Comment by colinin** [comment]
I have also encountered this problem, which can be resolved by removing the package that is referenced directly through the project and replacing it with a Nuget reference

**Comment by JosepBalague** [comment]
Still failing in Microsoft Visual Studio Enterprise 2019 Version 16.5.4:

![image](https://user-images.githubusercontent.com/4932314/81495426-8d417c80-92b0-11ea-9acd-5c6f5c6b2bfa.png)



But not failing when "nuget restore sln" in NuGet Version: 5.4.0.6315
![image](https://user-images.githubusercontent.com/4932314/81495461-b9f59400-92b0-11ea-954c-14047e6c5530.png)

**Comment by Sasino97** [comment]
> Hey so I got this issue when doing some coding and adding a reference to a project that was already in the project as a nuget package. I removed the nuget package - added a project reference but the dotnet restore command failed. A work-around was to change the version number of the referenced project.

I had the same exact issue. I removed the nuget package, and added the code as a project instead, and I couldn't get rid of the error, even after deleting all .vs folders, packages, and %temp%

**Comment by MuhKuh7** [comment]
Is there any chance we might see a bug fix for this more than 2 year old bug? It's kind of sad for such a widely used project to have a bug like this completely ignored.

**Comment by ogxd** [comment]
It is still an issue today

**Comment by erdembayar** [comment]
> I was able to reproduce the error. The exception is thrown here: https://github.com/NuGet/NuGet.Client/blob/3113c5ddf420ae0c9c34959108e127136c8f141e/src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs#L152
> 
> The issue appears to be that the same name+version pair is both a package and a project reference. If they had different versions, it would work, or if it was consistently a package or a project reference both times, I expect it would work.
> 
> My initial reaction is that the assets file might need to change to support this scenario, rather than being a simple bug to fix.

It looks any change to lock file might break existing build and restore since we can't support both project reference and packagereference for same Id&version. Even we support which one take more priority is tricky question. So I believe best course of action is display "Explicit error" for what is wrong. I already talked with @nkolev92  on this.

**Comment by erdembayar** [comment]
> From the sample, if we remove the project reference to `intermediate` from `source`, `source` can reference both the package and project and it works fine, NuGet selects the project. This "prefer project over package" logic doesn't appear to be happening for transitive dependencies, which I think is the bug.

@zivkan 
Do we have logic written somewhere in documents or code for  "prefer project over package"?

**Comment by zivkan** [comment]
From a quick search, I couldn't find it. @nkolev92  do you know?

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/blob/3ef6cd3c0145e59314a495569c2d53296794fbf3/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/IncludeFlagUtils.cs#L200-L221 which is called by https://github.com/NuGet/NuGet.Client/blob/3ef6cd3c0145e59314a495569c2d53296794fbf3/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/IncludeFlagUtils.cs#L67-L165, which in turn is called when the dependencies are flattened, ie when the assets file is created: https://github.com/NuGet/NuGet.Client/blob/3ef6cd3c0145e59314a495569c2d53296794fbf3/src/NuGet.Core/NuGet.Commands/RestoreCommand/LockFileBuilder.cs#L171

**Comment by erdembayar** [comment]
@nkolev92 
With my fix `dotnet restore` is fixed.
But `dotnet build` fails due to following error:

```
Determining projects to restore...
  All projects are up-to-date for restore.
  DoublyReferencedTarget -> C:\NuGetProj\IssueRepro\6795\111\nuget-error\DoublyReferencedTarget\bin\Debug\net40\DoublyReferencedTarget.dll
  Intermediate -> C:\NuGetProj\IssueRepro\6795\111\nuget-error\Intermediate\bin\Debug\net40\Intermediate.dll
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(13,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(18,12): error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]
C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\obj\Debug\net40\source.AssemblyInfo.cs(19,12): error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute [C:\NuGetProj\IssueRepro\6795\111\nuget-error\source\source.csproj]

Build FAILED.
```

**Comment by erdembayar** [comment]
@NuGet/nuget-client 
Do we need to show warning message to user that we picked up project over package in this case instead of doing it silently?

**Comment by nkolev92** [comment]
@erdembayar 
Given that it's an implementation detail and a question to the team, let's continue the discussion on the PR instead.
