### ISSUE TITLE
Install-Package -Force does not install dependencies. It also tries to pull in prerelease versions even if not specified

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#680]
Install-Package -Force does not install dependencies. There is already a  '-IgnoreDependencies' switch. It also tries to pull in prerelease versions even if not specified

Repro steps

1. Create Console application targeting net45
2. Install-Package Microsoft.AspNet.Mvc -Force

Expected: Installs the latest stable version of Microsoft.AspNet.Mvc (5.2.3) and its dependencies
Actual: Tries to install the latest prerelease version alone of Microsoft.AspNet.Mvc and fails as it does not have supporting files

**Comment by johnataylor** [comment]
The main problem with the semantics of the command are that it hides a package upgrade. Having the package upgrade semantic in isolation of prerelease and ignoreDependencies is fundamentally what introduces the ambiguity.

Secondarily the semantic is not really "Force" as force implies doing what you ask and override any errors or warnings. This is not exactly what is being said with "Force" on the command.

The solution is:

1) Limit the command to strictly overwrite the exact version of a package that is installed and no more: no dependency resolution and no upgrade. Prerelease is implicitly covered by this: there is no need for the explicit flag. This will allow users to repair a damaged implementation or overwrite an existing package from a different (potentially local debug) source.

2) Rename the argument "-Force" to something more accurate: either "-Reinstall" or "-Repair"

**Comment by johnataylor** [comment]
We are removing the feature, refer to #697
