### ISSUE TITLE
NU1105 due to case sensitivity in path

### ISSUE THREAD

**Issue by ghelyar** [NuGet/Home#6802]
## Details about Problem

NuGet product used NuGet.exe

NuGet Version: 4.3.0.4406 (from VSTS's packages tab)

## Detailed repro steps so we can see the same problem

1. subst a directory to a drive e.g. S: (upper case)
2. clone git repository containing two asp.net core projects, one of which references the other, to a directory at the root of that drive
3. cd /d to that drive but using a different case e.g. s: (lower case)
4. nuget restore the sln

cd /d S: (upper case) restores fine, and there is definitely no absolute path anywhere in the code

...

## Other suggested things
There is also a service fabric application in the solution, which references the outer asp.net project (sfproj -> csproj -> csproj) - deleting it seemed to make the restore get further, but it still worked.

It seems to be something to do with the reference from the outer project to the inner project.

outer.csproj contains:
```
<ItemGroup>
  <ProjectReference Include="..\inner.csproj" />
</ItemGroup>
```

### Verbose Logs

> Restoring packages for .NETFramework,Version=v4.6.2/win7-x64...
> Resolving conflicts for .NETFramework,Version=v4.6.2/win7-x64...
> NU1105: Unable to find project information for 's:\...\inner.csproj'. The project file may be invalid or missing targets required for restore.
> Committing restore...
...
> Errors in s:\...\outer.csproj
>     NU1105: Unable to find project information for 's:\...\inner.csproj'. The project file may be invalid or missing targets required for restore.

**Comment by mishra14** [comment]
@ghelyar can you please try the scenario with latest [nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe)?

Also, do you have any `DotnetCliToolReference` in the any of the 3 projects?

In recent past we have fixed some issues in case sensitivity.

**Comment by ghelyar** [comment]
The problem does not occur with the latest nuget.exe (although the version I have is the latest I can get from VSTS, with the credential provider)

The projects do have `<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />`

So this can probably be closed.

Thanks
