### ISSUE TITLE
FileConflictAction on the VS API should be IgnoreAll not OverwriteAll. Project templates are overwriting files now, instead of, ignoring them

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#681]
FileConflictAction on the Visual Studio API should be IgnoreAll not OverwriteAll. Project templates are overwriting files now, instead of, ignoring them

@emgarten and @yishaigalatzer , This needs to be fixed for RTM

**Comment by yishaigalatzer** [comment]
This is a regression from visual studio 2013

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/992bcd57d3aba0e6a461ed1063f1af506bc37662
