### ISSUE TITLE
IVsPackageInstaller.InstallPackage  install pre-release packages

### ISSUE THREAD

**Issue by BilgehanYildiz** [NuGet/Home#6810]
How can I install prelease packages in nuget3  with IVsPackageInstaller

**Comment by nkolev92** [comment]
@BilgehanYildiz Please refer to https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio/Extensibility/IVsPackageInstaller2.cs#L38

**Comment by BilgehanYildiz** [comment]
Yes this is helpfull but when I want to install with dependencies it is not install latest version of dependency.It is installing lowest version of dependency.
