### ISSUE TITLE
Nuget restore breaks Visual Studio v15.6.6 builds

### ISSUE THREAD

**Issue by fguinan** [NuGet/Home#6813]
## Details about Problem
Nuget restore breaks Visual Studio v15.6.6 builds

Steps:
1) Launch Visual Studio v15.6.6 and create new project/solution, using template "Visual C++ > Windows Universal > Unit Test App".
2) Build Solution. Everything builds fine.
3) Launch cmd.exe and navigate to the solution's enclosing directory. Run 'nuget.exe restore xxx.sln', where xxx is replaced by the name of the newly created solution.
4) Go back to Visual Studio and rebuild solution.

Result: Build failure - "Your project is not referencing the "UAP,Version=v10.0" framework. Add a reference to "UAP,Version=v10.0" in the "frameworks" section of your project.json, and then re-run NuGet restore."

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Nuget.exe v4.6.2.5055
Visual Studio v15.6.6

NuGet version (v4.6.2.5055):

dotnet.exe --version (if appropriate):

VS version (v15.6.6):

OS version (win10 v1709 (16299.309)):

Worked before? If so, with which NuGet version:
Worked before with Visual Studio v15.x prior to 15.6.

## Detailed repro steps so we can see the same problem

1) Launch Visual Studio v15.6.6 and create new project/solution, using template "Visual C++ > Windows Universal > Unit Test App".
2) Build Solution. Everything builds fine.
3) Launch cmd.exe and navigate to the solution's enclosing directory. Run 'nuget.exe restore xxx.sln', where xxx is replaced by the name of the newly created solution.
4) Go back to Visual Studio and rebuild solution.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by rohit21agrawal** [comment]
@fguinan thanks for the report. while we investigate this, could you let us know if this scenario has worked with previous versions of VS or NuGet.exe ?

**Comment by fguinan** [comment]
@rohit21agrawal Yes, it did work with prior versions of VS and nuget. The issue was also logged by somebody else on the Microsoft/vstest git repo.
https://github.com/Microsoft/vstest/issues/1533

**Comment by rohit21agrawal** [comment]
@fguinan we have determined on an internal email thread that the bug will be fixed on the VSTest side. They will release a fix for 15.7.

**Comment by rohit21agrawal** [comment]
External issue: https://github.com/Microsoft/vstest/issues/1533
