### ISSUE TITLE
.Net Core templates Dependencies section

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#6815]
@MNie commented on [Tue Apr 10 2018](https://github.com/NuGet/NuGetGallery/issues/5792)

I wondering if there is a possibility to create some section for .net core templates, where we could list all dependencies of a concrete template. Right now it is doable via dependencies element in NuSpec, so all dependencies could be listed correctly. But it has some problems for example when installing a template:

@mlorbetske

> ...As far as the hang goes, it turns out (at least on Windows, I haven't tried this on my mac yet) that this isn't actually a hang. Because of the way that the template is authored (where the libraries used by the template are referenced in the template package itself) the installation process ends up looking through all of the types in all of the DLLs that are restored by the dependencies to see if there are any components that are required for making the template - this process takes a long time (multiple minutes) but does eventually complete, discovering the contained templates and no "components".

So if a template doesn't contain a dependency section it is downloaded almost immediately. But because of that dependencies section could looks like this:

![image](https://user-images.githubusercontent.com/7689103/38489381-8333b2da-3be6-11e8-9706-0bd14e73a331.png)

So the final question is, Is it possible to create some section on nuget.org which would depend only on a specific element in a NuSpec file?

[Related issue](https://github.com/dotnet/templating/issues/1506)

**Comment by rohit21agrawal** [comment]
@skofman1 what exactly is the expectation from the client here?

**Comment by rohit21agrawal** [comment]
@skofman1 ping..

**Comment by nkolev92** [comment]
@MNie can you be more clear about the ask here? 

I don't think nuget.org is the right place to display graphs for templates or anything like that.

**Comment by MNie** [comment]
@rohit21agrawal @nkolev92 . Right now if .net core template doesn't include anything in dependencies section in a NuSpec file. Dependency section on NuGet is empty. 
I have an idea (maybe stupid idea), that this would be great if there would be some separate section for dependencies of a .net core template project (on nuget.org page, based on some new section in NuSpec file (or existing one), which doesn't trigger a download of packages which are listed as a `dependencies`).

**Comment by nkolev92** [comment]
@MNie 

I'm not sure I follow. 

What do you mean by .net core template projects? 

Are you talking about the projects generated by
> dotnet new console 

or?

**Comment by nkolev92** [comment]
Closing this as we haven't gotten enough information to further analyze/discuss this request.

**Comment by MNie** [comment]
@nkolev92 

> What do you mean by .net core template projects?
> Are you talking about the projects generated by
> >dotnet new console

> or?

Yes, projects created by `dotnet new someTemplate`

**Comment by nkolev92** [comment]
@MNie 
I don't believe NuGet.org is the right place for information like that. 

They're unrelated concerns. 
The usage of packages in templates is something done after the fact, however the nuspec is created at packaging time.
