### ISSUE TITLE
Update dependencies to fix package graph warnings (nu1605)

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#6816]
At this point we have too many nowarns in our solution. 

We need to clean those. 
Specific targets:
TFM conditional NoWarns as per https://github.com/NuGet/NuGet.Client/pull/2157. 
Those are there because signing is not yet xplat. 

CS1701 in Commandline.XPLAT

Any NU* in our graph is worth revisiting.

**Comment by nkolev92** [comment]
Cleaned up a bunch. 
Closing this.

**Comment by rrelyea** [comment]
@nkolev92  - pointer to PR / Commits?

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/pull/2674
https://github.com/NuGet/NuGet.Client/pull/2681
