### ISSUE TITLE
dotnet pack equivalent of NoPackageAnalysis

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#6817]
Converting a bit of code from using `nuget pack` to `dotnet pack` that needs `-NoPackageAnalysis` in order to pack cleanly. What is the equivalent flag for `dotnet pack`?

**Comment by rohit21agrawal** [comment]
it's a property in your csproj ``` NoPackageAnalysis ```.

Also note that since pack throws msbuild based warnings now, you can individually suppress each of them like you would any other warning using noWarn.

**Comment by jaredpar** [comment]
> it's a property in your csproj NoPackageAnalysis.

Is this documented anywhere? 

Our conversion from `nuget pack` to `dotnet pack` has been rather bumpy. Feel like a lot of these issues are going to be run into by other customers. Many times the features are there, it's just not discoverable. Would be nice to have a conversion "HOWTO" to refer to. 

> Also note that since pack throws msbuild based warnings now, you can individually suppress each of them like you would any other warning using noWarn.

The warnings I was seeing are emitted without a number hence there was no way to suppress it.

**Comment by rohit21agrawal** [comment]
@jaredpar in that case you are using an older version of CLI that doesn't have the updated nuget assemblies. I recommend using the release/2.1.2xx branch of CLI.

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target-inputs

**Comment by jaredpar** [comment]
@rohit21agrawal we are using 2.1.300-preview2-008324

**Comment by rohit21agrawal** [comment]
I am not sure what version of NuGet.Build.Tasks.Pack was shipped in the SDK contained in 2.1.300-preview2-008324. Can you look under sdks\NuGet.Build.Tasks.Pack and look at the file version? It's definitely outdated otherwise it would have definitely showed the warnings.

**Comment by jaredpar** [comment]
@rohit21agrawal sure. The version I see is:

``` c#
[assembly: AssemblyInformationalVersion("4.7.0-preview1-4927")]
```

That's same for the assembly under Desktop and CoreClr. 

Also here is the output I see if I go back to not passing the `/p:NoPackageAnalysis=true` flag. I grabbed a subset of the errors but they all have this form:

``` cmd
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Issue: Assembly outside lib folder. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Description: The assembly 'System.Security.Claims.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Solution: Move it into the 'lib' folder if it should be referenced. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Issue: Assembly outside lib folder. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Description: The assembly 'System.Security.Cryptography.Algorithms.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Solution: Move it into the 'lib' folder if it should be referenced. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Issue: Assembly outside lib folder. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview2-008324\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning : Description: The assembly 'System.Security.Cryptography.Encoding.dll' is not inside the 'lib' folder and hence it won't be added as reference when the package is installed into a project. [E:\code\roslyn\src\Nuget\NuGetProjectPackUtil.csproj]
```

**Comment by rohit21agrawal** [comment]
@jaredpar that version definitely doesn't have it. Is this version of NET Core later or earlier than 2.1 preview2?

**Comment by jaredpar** [comment]
@rohit21agrawal noted earlier that we are on SDK 2.1.300-preview2-008324. That is before preview2 RTM to my understanding.

**Comment by rohit21agrawal** [comment]
ok, if you can try with preview2, that will definitely have the msbuild based errors and warnings support.
