### ISSUE TITLE
Mark NuGet.Client's NuGet.Configuration.csproj with XPLATProject property

### ISSUE THREAD

**Issue by dagood** [NuGet/Home#6818]
The NuGet.Configuration project is missing this property. This makes xplat build produce an incomplete package set, causing errors when trying to restore the outputs.

Missing:

https://github.com/NuGet/NuGet.Client/blob/75dbda58560c7db281816015ad19a6bffdcc0f79/src/NuGet.Core/NuGet.Configuration/NuGet.Configuration.csproj#L12-L13

Example `XPLATProject` definition:

https://github.com/NuGet/NuGet.Client/blob/75dbda58560c7db281816015ad19a6bffdcc0f79/src/NuGet.Core/NuGet.CommandLine.XPlat/NuGet.CommandLine.XPlat.csproj#L13-L15

After adding it, the NuGet.Client xplat build seems to produce the NuGet.Configuration package fine in source-build's xplat build. (I don't see any reason to intentionally exclude this project.)

This is required to remove a NuGet.Client patch in source-build: https://github.com/dotnet/source-build/issues/420.

/cc @rrelyea @dleeapho @dseefeld

**Comment by nkolev92** [comment]
I thought this was already supposed to be fixed at some point. 

/cc @rohit21agrawal 

I'll create a PR shortly.

**Comment by nkolev92** [comment]
@dagood The PR is out https://github.com/NuGet/NuGet.Client/pull/2158
