### ISSUE TITLE
View in Object browser does not work Nuget Packages

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#6820]
There are couple issues regarding dependencies brought by Nuget packages and &quot;View in Object Browser&quot; command in .Net core projects

1) I can right click on a nuget package dependency and choose View in Object browser but nothing happens. (Object browser window doesn't even come up)

2) When I expand nuget reference and right click on a reference dll, there is no object browser command.

The only way is to open object browser manually and navigate to type I want to check.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/230689/view-in-object-browser-does-not-work-nuget-package.html
VSTS ticketId: 597301_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by nkolev92** [comment]
@mishra14 This is probably more fitting for project-system.

**Comment by rohit21agrawal** [comment]
This issue was moved to dotnet/project-system#3473
