### ISSUE TITLE
NuGet Package manager gives an error upon loading in vs 2017

### ISSUE THREAD

**Issue by ErikvdBurgwal** [NuGet/Home#6834]
Hi,

I am facing the same issue as listed in [#2858](https://github.com/NuGet/Home/issues/2858) since about 1 week; when opening the package manager console, I get the following error:

`The module to process 'nuget.psm1', listed in field 'ModuleToProcess' of module manifest 'F:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\NUGET\Modules\NuGet\NuGet.psd1' was not processed because no valid module was found in any module directory.`

I am not sure when it started appearing; either after apply the Windows 10 annual update or installing a new instance of Visual Studio (next to an existing installation). 

I uninstalled all Visual Studio 2017 instances and re-installed one, but the problem persists.

## Details about Problem
NuGet version: 4.6.0
VS version: 15.6.6
OS version: win10 v1803 (17133.73)
 
If you need any additional information, please let me know which..

Thanks in advance,
Erik

**Comment by nkolev92** [comment]
@ErikvdBurgwal 
This sounds like a setup problem, not a NuGet one. 

Can you please try repair your visual studio installation?

Open the Visual Studio Installer, find the affected installation there and click repair.

**Comment by ErikvdBurgwal** [comment]
@nkolev92 thanks for your support!

I tried the repair function, unfortunately the problem is not solved; I still get the same error message while opening the package manager console.

Any other suggestions?

Thanks,
Erik

**Comment by ErikvdBurgwal** [comment]
Sorry for the repeating request, but do you have any suggestion what I can do? 
I tried; 
- uninstall / reinstall / repair visual studio 2017 (Enterprise, Community)
- uninstall all older versions of visual studio (along with related applications), reïnstalled visual studio 2017
- install visual studio 2017 Preview

but all with no result. 

This way, I am unable to continue my software developments. What other options do I have?

**Comment by nkolev92** [comment]
Can you check if 

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\Modules\NuGet

contains anything? 
Would you please list out the files there?

Normally repair should fix it. 

Which workloads do you have installed?

**Comment by ErikvdBurgwal** [comment]
The NuGet files existed. 

I tried another couple of install / uninstall / repair attemts, then contacted MS and finally got the advise to re-install my Windows to get this sorted.
