### ISSUE TITLE
Support NuGet CLI on Nano Server

### ISSUE THREAD

**Issue by MichaelSimons** [NuGet/Home#6835]
Does the NuGet CLI support running on Nano Server? Following the [Windows installation instructions](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference) don't work.  Nano Server doesn't support full .NET FX apps.

Ideally the following would work: 
```
FROM microsoft/windowsservercore:1709 AS installer
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest -OutFile nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
RUN .\nuget.exe help

FROM microsoft/nanoserver:1709
COPY --from=installer nuget.exe ./
RUN nuget.exe help
```

Running nuget.exe works fine in the windowsservercore container.  It fails in the nanoserver container with `The command 'cmd /S /C nuget.exe help' returned a non-zero code: 3221225781`.

The scenario in which this is useful is to be able to manipulate the nuget.config especially to set passwords for proxy's and private feeds.  For non-password configuration changes, you can use a multi-stage Dockerfile in which the NuGet.config is manipulated in a windowsservercore stage.  This doesn't work for PWDs that get encrypted as PWDs in the NuGet.config are not portable.  Furthermore, NuGet.exe doesn't support `-StorePasswordInClearText` for all scenarios such as the `config` cmd (see https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ConfigCommand.cs#L48).

This is related to https://github.com/dotnet/dotnet-docker/issues/463

**Comment by nkolev92** [comment]
NuGet.exe does not run on Nano Server. 
The only way to make it work on nano server would be make it .NET Core. However dotnet.exe is the .net core cli and it ships with all required nuget commands. 

The `-StorePasswordInClearText` switch is available for the sources command.

**Comment by MichaelSimons** [comment]
> However dotnet.exe is the .net core cli and it ships with all required nuget commands.

@nkolev92  - How do you use the .NET Core cli to manipulate the NuGet.config (e.g. set the password for a proxy)?

**Comment by prisar** [comment]
@nkolev92 i also have the same question asked by @MichaelSimons 
i want to run nuget.exe in Dockerfile so that i can build using docker-compose
