### ISSUE TITLE
CredentialProvider.VSS.exe fails when TLS 1.0 is disabled

### ISSUE THREAD

**Issue by gholliday** [NuGet/Home#6837]
NuGet product used: `nuget.exe`

NuGet version: `4.6.2.5055`

OS version: `win10 v1803 (17133.1)`

## Detailed repro steps

1. Disable support for TLS 1.0/1.1 protocols in Windows/SChannel to simulate servers not supporting these older protocols, or businesses disabling them to meet PCI compliance requirements:

```
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Client" /v Enabled /f /t REG_DWORD /d 0
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server" /v Enabled /f /t REG_DWORD /d 0
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client" /v Enabled /f /t REG_DWORD /d 0
reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server" /v Enabled /f /t REG_DWORD /d 0
:: Reboot after setting these keys
```

2. Attempt to connect to a feed that uses `CredentialProvider.VSS.exe` to authenticate. i.e. a VSTS Packages feed

### Verbose Logs

```
C:\Project\src>C:\Project\tool\nuget\nuget.exe restore -Verbosity detailed -ConfigFile C:\Project\src\nuget.config -OutputDirectory C:\Project\npc C:\Project\src\.nuget\tools\packages.config
NuGet Version: 4.6.2.5055
Restoring NuGet package Microsoft.TestPlatform.15.7.0.
Missing C:\Users\username\.nuget\packages\microsoft.testplatform\15.7.0\microsoft.testplatform.15.7.0.nupkg
CredentialProvider.VSS: Microsoft Visual Studio Team Services Credential Provider for NuGet 0.35.0.0
CredentialProvider.VSS: Probing https://accountname.pkgs.visualstudio.com/_packaging/f6b7f438-85e8-43f5-876b-b6c0f875dd16/nuget/v3/index.json
CredentialProvider.VSS: Auth probe failed for https://accountname.pkgs.visualstudio.com/_packaging/f6b7f438-85e8-43f5-876b-b6c0f875dd16/nuget/v3/index.json: An existing connection was forcibly closed by the remote host
CredentialProvider.VSS: Exit message: Unknown error ocurred in the provider.
CredentialProvider.VSS: Exit code: Failure
```

From Fiddler, it appears that it is trying to negotiate SSL3, which is not supported by the server. 
```
CONNECT accountname.pkgs.visualstudio.com:443 HTTP/1.1
User-Agent: VSServices/15.112.26224.0 (CredentialProvider.VSS.exe) VssPkgsAuthLib/0.35.0.0 CredentialProvider.VSS/0.35.0.0
Host: accountname.pkgs.visualstudio.com
Connection: Keep-Alive

A SSLv3-compatible ClientHello handshake was found. Fiddler extracted the parameters below.

Version: 3.0 (SSL/3.0)
```

### Root Cause
- The root cause is that ```CredentialProvider.VSS.exe``` has a `targetFramework` of `v4.5`.
- Versions of .NET prior to `v4.7` hard-code `ServicePointManager.SecurityProtocols` to only allow `Ssl3 or Tls10` 
- Since `Tls10` was disabled in the OS, the only available protocol becomes `Ssl3`, which is not accepted on the server, because it is insecure.

### Workarounds

**Workaround A**
If .NET Framework 4.7 is installed on the machine, you can use [AppContextSwitchOverrides](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element) to opt-in to the desired "let the OS decide" functionality.

Create a ```CredentialProvider.VSS.exe.config``` file with the following contents:
```
<?xml version="1.0" encoding="utf-8"?>
 <configuration>
   <runtime>
     <AppContextSwitchOverrides value="Switch.System.Net.DontEnableSystemDefaultTlsVersions=false" />
  </runtime>
</configuration>
```

**Workaround B**
A machine-wide registry key can be set to opt-in ALL .NET apps on the machine to the desired "let the OS decide" functionality. 
```
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v2.0.50727 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v2.0.50727 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32
```

### Suggested Fixes
**Suggested Fix A**
Per [.NET Framework TLS Recommendations](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), the first recommendation is to compile for and change target framework to `v4.7` where possible. That's not a great option unless you want to force non-Windows-10 clients to install .NET Framework 4.7 (since it's not installed by default until Windows 10 Creators Update - `v1703 10.0.15063 April 2017`)

**Suggested Fix B**
If you are unwilling to shift the target framework to `v4.7`, then the only reasonable option is to add `TLS 1.2` as an available protocol.

Note that this change is not future-compatible, since if `Tls13` or some other protocol becomes available on the machine, it will not be able to use it.

```
// Add this somewhere near the top of Program.Main() before any network connections are made
System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
```

**Comment by nkolev92** [comment]
The VSS CredentialProvider is not owned by the NuGet team. 

I'd suggest filing an issue here: https://developercommunity.visualstudio.com/spaces/21/index.html

//cc 
@alexmullans @keithrob
