### ISSUE TITLE
PackageBuilder compatibility issues

### ISSUE THREAD

**Issue by ovidiuiliescu** [NuGet/Home#6838]
In older versions of NuGet (e.g. 2.X), the `PackageBuilder.WriteManifest()` method supported unicode package IDs by escaping them if needed, e.g. for a package with id `告`, the .nuspec file would be named `%E5%91%8A.nuspec` instead of `告.nuspec`.

In newer versions (e.g. 4.5), the package name is used as-is. 

This causes problem when creating a package with 4.5 and trying to use it with something that expects the old behavior (e.g. an older version of the NuGet server).

**Comment by nkolev92** [comment]
@ovidiuiliescu This was done as requested in https://github.com/NuGet/Home/issues/5956. 

Your options are to either use an earlier version of nuget.exe for packing, or use a newer version of nugetserver that supports this if it does.
If the latest version of nugetserver does not support that, please file an issue there.
