### ISSUE TITLE
The remote name could not be resolved: 'nuget.org'

### ISSUE THREAD

**Issue by mkabhishekdev** [NuGet/Home#6845]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe|Package Manager console

NuGet version (4.0)

dotnet.exe --version (if appropriate):NA

VS version (if appropriate): VS 2017/2015

OS version (i.e. win10 v1607 (14393.321)): win 10

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. https://api.nuget.org/v3/index.json: 
Unable to load the service index for source https://api.nuget.org/v3/index.json.
An error occurred while sending the request.
The remote name could not be resolved: 'api.nuget.org'

2. I am behind a company's firewall and we are trying to setup CI/CD pipeline.

3. I configured the http_proxy in NuGet.config file.
...

## Other suggested things
1.  I followed the steps of creating a NuGet.config like exactly mentioned here : https://stackoverflow.com/questions/9232160/nuget-behind-proxy/15463892#15463892
[NuGetIssue_gitHub.zip](https://github.com/NuGet/Home/files/1925252/NuGetIssue_gitHub.zip)

But after, setting the proxy. In VS, NuGet Package Manager: "api.nuget.org" is getting unchecked.

 So, I went to the Nuget.config file getting generated in the %appdata%\NuGet, there looks to be this tag <disabledPackageSources> getting generated which has the 'nuget.org'. If I delete the proxy config it won't get generated. Facing a weird issue. Need help

**Comment by nkolev92** [comment]
@coderkemp 
do you have any other configs in your path? 
NuGet should not uncheck that source. 

Can you try specifying the config directly?

**Comment by mkabhishekdev** [comment]
@nkolev92 
I just have the NuGet.config in  '%appdata%\NuGet' .

specifying the config directly?

**Comment by nkolev92** [comment]
-config configName when you do restore. 

If you run it with -detailed, NuGet will tell you which configs it's using and which sources it's used.

**Comment by mkabhishekdev** [comment]
it seems to be fine. 
Have configured the nuget.config in this form:
`<configuration>

    <config>

        <add key="http_proxy" value="http://my.proxy.address:port" />

        <add key="http_proxy.user" value="mydomain\myUserName" />

        <add key="http_proxy.password" value="base64encodedHopefullyEncryptedPassword" />

    </config>

</configuration>`

Any other way you want me to try for this issue: An error occurred while sending the request.
The remote name could not be resolved: 'api.nuget.org' ?

**Comment by nkolev92** [comment]
@coderkemp That should normally work. 

Does any nuget.exe version work?
4.0, 4.3, 4.6?

**Comment by mkabhishekdev** [comment]
so I ran nuget -config commands to insert http_proxies. If I run the commands using nuget.exe 4.6 and in the build server if the nuget.exe version is 4.0. Can that be a issue?

**Comment by nkolev92** [comment]
@coderkemp 
No that shouldn't affect it. The schema hasn't changed.

**Comment by nkolev92** [comment]
@coderkemp 
Did you manage to fix your problem?

**Comment by mishra14** [comment]
Closing due to lack of customer response.
