### ISSUE TITLE
NuGet.exe install without a project should not validate the PackageType metadata

### ISSUE THREAD

**Issue by dschuermans** [NuGet/Home#6849]
## Details about Problem

NuGet product used (NuGet.exe): **NuGet.exe**

NuGet version (x.x.x.xxx): **4.6.2.5055**

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): **win10 1709 16299.309**

Worked before? If so, with which NuGet version: haven't had the need before. I know it works when using the nuget package manager console in VS

## Detailed repro steps so we can see the same problem

1. nuget.exe install NupkgWrench -IgnoreDependencies

### Verbose Logs

```
D:\test> nuget install nupkgwrench -source nuget.org -IgnoreDependencies -Verbosity detailed
Unknown option: '-IgnoreDependencies'
NuGet.CommandLine.CommandLineException: Unknown option: '-IgnoreDependencies'
   at NuGet.CommandLine.CommandLineParser.GetPartialOptionMatch[TVal](IEnumerable`1 source, Func`2 getDisplayName, Func`2 getAltName, String option, String value)
   at NuGet.CommandLine.CommandLineParser.ExtractOptions(ICommand command, IEnumerator`1 argsEnumerator)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
D:\test>
```
### Sample Project

Not applicable, any nuget package will do

**Update by @nkolev92 **

Running
> nuget install nupkgwrench -DependencyVersion Ignore 
errors out with 
> Error NU5000: Package 'NupkgWrench 1.3.0' has a package type 'DotnetCliTool' that is not supported by project 'E:\tmp'.

This is probably not needed because the intention here is to just download said nupkg, and there's no project or a packages.config.

**Comment by dschuermans** [comment]
and fyi, the docs for the CLI suggested this got posted:
https://docs.microsoft.com/en-us/nuget/tools/cli-ref-install:
![image](https://user-images.githubusercontent.com/6634696/39002704-685ce826-43f9-11e8-8ba2-a5566c2f699a.png)

**Comment by dschuermans** [comment]
And as a final touch, the docs for the package manager console claims the following:
![image](https://user-images.githubusercontent.com/6634696/39006908-cb56385a-4404-11e8-96d7-7944e4f03c9a.png)
See https://docs.microsoft.com/en-us/nuget/tools/package-manager-console

**Comment by emgarten** [comment]
`-DependencyVersion Ignore` should handle this, I think it was added in 4.6

Using that I get an error now that nuget checks the package type, so it is still blocked.
`Error NU5000: Package 'NupkgWrench 1.3.0' has a package type 'DotnetCliTool' that is not supported by project 'E:\tmp'.`

**Comment by nkolev92** [comment]
@dschuermans 
You're effectively looking for a way to just download a nupkg and then run the executable? 

@emgarten 
Global tools maybe? :)
I think the package type checking has been there since 4.x 

The scenario being asked for here is not a bug, but nupkgwrench in particular won't work because it's a dotnetclitool.

**Comment by dschuermans** [comment]
@nkolev92 - That assumption is correct. Although it could be rephrased as "I'm looking for a way to download a nupkg and use something that is contained within that nupkg." Doesn't have to be an executable 😉

**Comment by nkolev92** [comment]
Thanks for clarifying it @dschuermans 

Here's the status right now:

- The ability to download a single package without any package type/project type/dependency restrictions is tracked in https://github.com/NuGet/Home/issues/5919. 

- The correct approach for netcore executable assemblies is global tools - More [info](https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x) This is how executable should be packaged, and how executables should be shipped. 

- As @emgarten mentioned earlier, there's DependecyVersion Ignore which covers the original ask to download a package with dependencies. 

Now lastly, the issue is that there's PackageType validation in simple NuGet install where you're not installing to a project. That package validation is not necessary for this scenario in my opinion.

I'm going to change this issue name and description into that.

Does that sound good?

**Comment by dschuermans** [comment]
@nkolev92 perfect :) thanks for the clarification!

**Comment by AraHaan** [comment]
> 
> 
> `-DependencyVersion Ignore` should handle this, I think it was added in 4.6
> 
> Using that I get an error now that nuget checks the package type, so it is still blocked. `Error NU5000: Package 'NupkgWrench 1.3.0' has a package type 'DotnetCliTool' that is not supported by project 'E:\tmp'.`

could we do this with the dotnet.exe version of nuget too?

**Comment by nkolev92** [comment]
@AraHaan 

There's no dotnet.exe equivalent of the `nuget.exe install` command, can you clarify what you're referring to?

Keep in mind, that the message about `DotnetCliTool` is valid, you cannot install that package into a project.

**Comment by AraHaan** [comment]
Yes, but I wanted to be able to use the .NET CLI version of nuget to install a package into a folder without a project, let's say for example I wanted to manually install a version of ``Microsoft.NETCore.App.Ref`` into ``$DOTNET_ROOT/packs/`` using the .NET CLI's version of nuget that does not come by default with that version of the .NET SDK for example without needing to also install that older .NET SDK first for it.

**Comment by nkolev92** [comment]
There's no equivalent command available in .NET exe, ie no command that'd just download a single package, all dotnet commands are project related. 

That'd need to be a new feature. Can you please create an issue for that. 

Note that your exampple is something that the SDK should be able to automatically do. 

For example, if you target net3.0 and only install the net6.0 SDK, it'd automatically download the targeting pack for 3.0

**Comment by nkolev92** [comment]
Team Triage: Tools packages such as `NupgkWrench` can today be installed via `dotnet tool install`, https://www.nuget.org/packages/NupkgWrench. 

![image](https://github.com/NuGet/Home/assets/2878341/11a4ce2c-806e-41f8-bf2c-d40b8427de01)

**Comment by mletterle** [comment]
Bumping this because it's still a valid ask.

**Comment by DominicSchell** [comment]
I have the same use case. I simply want to download a nuget package that was packaged as dotnet tool, but works easily as standalone tool.

**Comment by nkolev92** [comment]
Hey folks, please take a look at https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-package-download.
