### ISSUE TITLE
Adding packages folder to TFS is not consistent

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#685]
Repro step: 
 1. create a class library project, install some packages 
 2. Add solution to TFS, which will not add packages folder 
 3. check in pending changes, install some other packages 
 4. check pending changes again. 

Expected: NuGet should be consistent if Packages folder is considered as the source pending changes 

Actual: after step 3, the newly installed packages will be marked with pending changes with their files in Packages folder. The suggestion is, if NuGet detected that packages folder are not checked in, or having pending changes, do not mark the packages folder contents as pending addition.

**Comment by yishaigalatzer** [comment]
@danliu is this a regression from Visual Studio 2013? If not then I think this behavior is fine.

Please take a look and if it is not a regression please close the issue, if you think otherwise please remove the milestone so we can pick it up in triage again.

**Comment by danliu** [comment]
verified with Visual Studio 2013 that this is not a regression. 

However, in Visual Studio 2013/NuGet 2.*, we are adding packages folder to TFS (step 2 above) by default. But now we are not adding packages folder by default in step 2. With this change, it's a little strange to add the packages folder to TFS in following steps.

**Comment by yishaigalatzer** [comment]
Who is "we". Is visual studio changing its behavior, so when adding the solution to TFS visual studio stopped adding packages to TFS? Or is it that we used to do some magic for it?

**Comment by danliu** [comment]
"we" is NuGet.

In NuGet 2.* versions, NuGet has the menu of "Enable NuGet package for restore", which will add the .nuget folder with nuget.exe and nuget.targets file. When this is enabled, NuGet will not add packages folder to TFS by default. If .nuget folder is not present, then NuGet 2.* will add packages folder to TFS.

In NuGet V3, the "Enable NuGet package for restore" menu has been removed. And NuGet is not adding packages folder to TFS even though .nuget folder is not present.

**Comment by zhili1208** [comment]
it doesn't repro in 3.3
