### ISSUE TITLE
Nuget Duplicates Import References of csproj in visual studio

### ISSUE THREAD

**Issue by BilgehanYildiz** [NuGet/Home#6853]
Hi when I use IVSInstaller.Install it duplicates the solution nuget references
I have a special nuget package it is not project reference ,it is import reference in csproj but when i try to update it in packages config it updates but when I check my csproj it duplicates the import references in visual studio.Is it bug?As you see normaly it updates 1.0.4 to 1.0.6.10 but there are multiple references

```
<Import Project="..\packages\MySolutionReferencePackage.1.0.4\build\MySolutionReferencePackage.targets" Condition="Exists('..\packages\MySolutionReferencePackage.1.0.4\build\MySolutionReferencePackage.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\MySolutionReferencePackage.1.0.4\build\MySolutionReferencePackage.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MySolutionReferencePackage.1.0.4\build\MySolutionReferencePackage.targets'))" />
    <Error Condition="!Exists('..\packages\MySolutionReferencePackage.1.0.6.10\build\MySolutionReferencePackage.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MySolutionReferencePackage.1.0.6.10\build\MySolutionReferencePackage.targets'))" />
  </Target>
  <Import Project="..\packages\MySolutionReferencePackage.1.0.6.10\build\MySolutionReferencePackage.targets" Condition="Exists('..\packages\MySolutionReferencePackage.1.0.6.10\build\MySolutionReferencePackage.targets')" />
```

**Comment by jainaashish** [comment]
This is expected, since IVSInstaller.Install will only install the new package and won't update the existing one. If you're requirement is such that you need to update the existing package, then first uninstall it with IVSInstaller.Uninstall and then install the expected version.

**Comment by BilgehanYildiz** [comment]
Normally when I use install command it updates existing one if exist(csproj normal references) but specific import references are duplicated only ..

**Comment by jainaashish** [comment]
that's just because Project System takes care of that while adding reference if that already exists they just overwrite it. But that's not the case when imports are being updated via msbuild. That's why I said it's by design and current workaround would to uninstall first and then install.

**Comment by BilgehanYildiz** [comment]
I can do it as you said with workaround,but if it is working for import references than it is more useful(overwrite)
