### ISSUE TITLE
PM UI will be closed automatically when clicking the “Migrate packages.config to PackageReference…”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#6854]
## Details about Problem
NuGet Version: Release-4.7.0-RTM 5122
VS Version: D15.7 27619.00
OS Version: RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1.	Create a C# Class Library (.NET Framework) template via VS.
2.	Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3.	Install a package with “Packages.config” format.
4.	Right-Click the “References” node and select the “Migrate packages.config to PackageReference…”
## Expected
The PM UI should not be closed automatically.
## Actual
The PM UI will be closed automatically as below screenshot.
![pmuiclosedautomatically](https://user-images.githubusercontent.com/20632625/39043326-aec4cc56-447c-11e8-97ca-076a85026325.png)
## Note
1. The PM UI for solution will not be closed after clicking “Manage NuGet Packages for Solution…” on solution node in step2.
2. It also repro on the first project with multiple projects in one solution (not repro for other project except for the first one).
![onlyfirstpmuiclosed](https://user-images.githubusercontent.com/20632625/39043351-b9e7f856-447c-11e8-8864-aa7a400884b5.png)
3. It repro on D15.7 27619.00 (default NuGet Client 4.7.0.5104).
4. It repro on D15.8stg 27618.3003+NuGet Client Dev 5121.

**Comment by rrelyea** [comment]
Rohit - can you comment on this behavior?  If we decided we wanted to keep the dialog open, what would it take? /cc: @karann-msft

**Comment by rohit21agrawal** [comment]
it's a pretty easy fix, need to remove two lines of code that explicitly close the PM UI if it's open.

**Comment by jainaashish** [comment]
I think it makes sense to close PM UI while migrating for two reasons a) otherwise we'll need to make sure project is updated as part of existing UI once its moved from PC to PR. b) It will unnecessary create lot of UI delays for uninstalling all existing dependencies and then installing them.

So, my vote is to keep it this way.

**Comment by rohit21agrawal** [comment]
I can be motivated either way - I feel this is a nit issue, and no customer has reported or complained about it.

I tried a private branch with the fix, and it works like it should. so, it shouldn't be a big deal to fix it or keep it this way.

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
Issue is 6 years old now, since we haven't had any complaints about this experience it doesn't make sense to change it.
