### ISSUE TITLE
Unable to restore packages from private VSTS source on macOS

### ISSUE THREAD

**Issue by nicolas-garcia** [NuGet/Home#6855]
Hello,

I'm working on a Xamarin.Forms project, usually on Windows 10, and I would like to switch to macOS for the iOS development part.

My problem right now is that I am not able to restore my NuGet packages from a private feed hosted on Visual Studio Team Services. It works well on Windows though.

## Details about Problem

NuGet product used:
nuget.exe
(/Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/nuget/nuget.exe)
NuGet, shipped with the latest Visual Studio for Mac

NuGet version:
4.6.2.5055

VS version (if appropriate):
Visual Studio for Mac 7.4.3 (build 10)

OS version (i.e. win10 v1607 (14393.321)):
macOS High Sierra 10.13.4

Worked before? If so, with which NuGet version:
It works on Windows, and my macOS VSTS build agent too! My build agent use nuget v4.3.0.

## Detailed repro steps so we can see the same problem

1. Create a Xamarin.Forms project
2. Add a private package source, hosted for example on VSTS
3. Add one of the packages from this source to your project
4. Restore your NuGet, through Visual Studio or CLI
5. NuGet ask you for your credentials for the private source
6. It keeps asking you, even if your credentials are OK

I don't have any special character in my password.
I tried from CLI and popup in Visual Studio, same result.

Adding my credentials for the feed in my nuget.config didn't helped, same error.

```
Unable to load the service index for source https://xxxx.pkgs.visualstudio.com/_packaging/MyPackageFeed/nuget/v3/index.json
  401 (Unauthorized)
```

Thank you :)

**Comment by jainaashish** [comment]
Did you put your credentials in clear text format in NuGet.config and tried with latest nuget.exe?

**Comment by nicolas-garcia** [comment]
Hi,
I tried to put my credentials in clear in the NuGet.config and with the latest nuget.exe version available but I still have the issue.
I have the issue within Visual Studio for mac too.

**Comment by t-smirnov** [comment]
Very annoying behavior,
but, if you're using JetBrains rider and nuget.config - all packages from private feed restores correctly, but dotnet-cli - fails.

**Comment by nicolas-garcia** [comment]
I confirm it works with JetBrains Rider. Unfortunately, it's not a solution for me because Rider do not support Xamarin.Forms yet 😄 
Thank you though for pointing out the fact it works with Rider!

**Comment by t-smirnov** [comment]
@nicolas-garcia )) we solved that, just up standalone nuget server and all is ok

**Comment by Emilien-M** [comment]
Same problem with visual studio for mac 7.6.9 (build 22). Any update for this issue ?

**Comment by sarthak199526** [comment]
I am having the same problem On latest Visual studio mac latest version

**Comment by sbkrishnan2506** [comment]
I am having the same problem On the latest Visual studio mac latest version.

Visual Studio Community 2019 for Mac
Version 8.3.4 (build 8)
Installation UUID: 9bfa8c79-690d-4b08-8475-634d745a196a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 606000126

Mono Framework MDK
Runtime:
	Mono 6.6.0.126 (2019-08/8969f2cc99b) (64-bit)
	Package version: 606000126

NuGet
Version: 5.3.0.6192

**Comment by nicolas-garcia** [comment]
Hi,

I found a solution today to this issue, that may be a lack of documentation ?

In Visual Studio for Mac, you need to follow this documentation for making it work: https://docs.microsoft.com/en-us/azure/devops/artifacts/nuget/consume?view=azure-devops#macos-add-the-feed-to-your-nuget-configuration

Basically, instead of logging in using your regular credentials on VSTS (Azure DevOps now), you need to use a Personal Access Token instead of your password.

**Comment by sarthak199526** [comment]
Yes this is exactly what I ended up doing.

**Comment by nkolev92** [comment]
Hey all,

If you are facign issues with Visual Studio for Mac please report them through https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019. 
The VS 4 Mac issues are not tracked here. 

@nicolas-garcia 
Are still having these issues? 
Are they VS4Mac related or some other tool?

Thanks.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by sbkrishnan2506** [comment]
> I am having the same problem On the latest Visual studio mac latest version.
> 
> Visual Studio Community 2019 for Mac
> Version 8.3.4 (build 8)
> Installation UUID: 9bfa8c79-690d-4b08-8475-634d745a196a
> GTK+ 2.24.23 (Raleigh theme)
> Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)
> 
> ```
> Package version: 606000126
> ```
> 
> Mono Framework MDK
> Runtime:
> Mono 6.6.0.126 (2019-08/8969f2cc99b) (64-bit)
> Package version: 606000126
> 
> NuGet
> Version: 5.3.0.6192

Resolved the issue  by adding Personal access token
