### ISSUE TITLE
published package on Nuget.org badly out of date for NuGet.Client

### ISSUE THREAD

**Issue by PaluMacil** [NuGet/Home#6856]
Please read the following information before posting the issue.

## Details about Problem

I believe this still counts as a client tools issue since it's about https://github.com/NuGet/NuGet.Client but none of the template applied...

https://github.com/NuGet/NuGet.Client has released versions in the 4.7 range, but the latest release published to nuget.org is a beta of 4.3: https://www.nuget.org/packages/NuGet.Client/4.3.0-beta1-2418

**Comment by nkolev92** [comment]
NuGet.Client library is no more. 
It was merged into NuGet.Packaging a while back. 
https://github.com/NuGet/NuGet.Client/pull/1277
