### ISSUE TITLE
Be able to set suppress all dependency in nupkg using dotnet pack

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#6859]
The default behavior of dotnet pack is to change package reference to dependency in nuspec. But the nupkg of global tools does not have package reference.

One way I found while still use dotnet pack is to change all PackageReference to _PrivateAssets=all_. However that [breaks test project](https://github.com/dotnet/cli/issues/9109). Since the main project’s dependency cannot be accessed by the test project. And the only way to alter the dependency in dotnet pack is changing asset.json. 

relate issue:
https://github.com/dotnet/cli/issues/9109
https://github.com/NuGet/Home/issues/6354

**Comment by wli3** [comment]
cc: @rrelyea @rohit21agrawal this is the issue created after today's sync meeting

**Comment by rohit21agrawal** [comment]
i'll close this and re-activate #6354
