### ISSUE TITLE
Nuget support for mutual ssl authentication

### ISSUE THREAD

**Issue by emmellee** [NuGet/Home#6865]
My organization wishes to create nuget packages for release to our internal feed provided by our TFS Server. The Department of Defense (DoD) relies heavily on the use of smartcards and CA certs and, like any DoD webserver, our TFS Server requires mutual ssl authentication. Unfortunately, we are unable to get past nuget issues on servers requiring SSL Client Certificates. Any help your team can provide towards resolving this issue would be greatly appreciated. Nuget support of windows certificate stores would be ideal.  Microsoft's TFS/VSTS teams plan to update their credential providers to support mutual SSL auth in coordination with your work.

**Comment by jainaashish** [comment]
Thanks for the issue. This feature work is already being tracked through https://github.com/NuGet/Home/issues/5773 please follow that issue to get future updates. You can also respond there to help increase the priority of the issue.
