### ISSUE TITLE
Don't NullRef in NuSpec packing scenario, also improve options

### ISSUE THREAD

**Issue by rohit21agrawal** [NuGet/Home#6866]
currently if using dotnet.exe to pack a nuspec file (via a csproj property), you need to set IncludeBuildOutput=false if you use the --no-build switch. The project also needs to have been restored.

When packing via a nuspec file, both of these things shouldn't be needed.

CC: @jaredpar

**Comment by rohit21agrawal** [comment]
turns out removing dependency on restore is not in NuGet's control as it is also required by Microsoft.PackageDependencyResolution.targets:
```
C:\Users\ragrawal\Sources\NuGet\NuGet.Client\.test\work\425c9064\53d53bfd\sdk\2.2.0-preview1-007853\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(337,5): error : Assets file 'C:\Users\ragrawal\Sources\NuGet\NuGet.Client\.test\work\0c36606d\86c6ab5d\ClassLibrary1\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [C:\Users\ragrawal\Sources\NuGet\NuGet.Client\.test\work\0c36606d\86c6ab5d\ClassLibrary1\ClassLibrary1.csproj]
```

**Comment by jaredpar** [comment]
If it's not within NuGet's control then was a bug filed on the appropriate team?

Is the idea of packing a nuspec file being reconsidered? Giving back that functionality would preclude the need to even fix this bug.
