### ISSUE TITLE
Add Link to NuGet Gallery on Package Details in Visual Studio

### ISSUE THREAD

**Issue by spottedmahn** [NuGet/Home#6869]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.6.0

VS version (if appropriate): 15.6.6

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version: no

## Other suggested things

When I'm looking at the package details in VS, I frequently want to go out to the NuGet gallery and view it there.  It would seem natural to have a link to it like the others:

![image](https://user-images.githubusercontent.com/14079228/39317438-949b27d6-4949-11e8-8f3d-2617fd8303ed.png)

Maybe I'm missing it?

**Comment by nkolev92** [comment]
The info displayed there is only the baked in information that's in the package/nuspec itself. 

The nice package page is not something that the client knows about. 
That's not part of the protocol. MyGet/VSTS/NuGet.org's display package pages are different. 
A feed is not even required to have a display page. 

I don't think this is feasible, unless it gets added to the protocol.

/cc @loic-sharma @jainaashish @joelverhagen

**Comment by spottedmahn** [comment]
I see.  Darn.  Thanks for the quick reply!!

**Comment by spottedmahn** [comment]
what is Type:DCR?  DCR stands for?

**Comment by jainaashish** [comment]
Dupe of https://github.com/NuGet/Home/issues/5299
