### ISSUE TITLE
NuGet - Signing - Timestamp URL can not be https:// ?

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#6871]
While trying out some of the signing features in the latest NuGet SDK packages, it seems it is not possible to use `https://www.freetsa.org/tsr` as a timestamper?

https://github.com/NuGet/NuGet.Client/blob/53734d0e377ec1bce8a29dba65a715dd2dd7e17c/src/NuGet.Core/NuGet.Packaging/Signing/Timestamp/Rfc3161TimestampRequest.cs#L189 seems to allow only `http://` - is this by design?

**Comment by maartenba** [comment]
Thanks! Any NuGet packages this change is in? (latest 4.7 on NuGet.org seems to a bit older)

**Comment by mishra14** [comment]
You should be able to get one from https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Packaging

**Comment by maartenba** [comment]
Latest 4.7 is from Tue, 24 Apr 2018 21:36:16 GMT ?
(nor sure we want to switch from 4.7 RTM to 4.8 prerelease...)

**Comment by mishra14** [comment]
The fix in only in dev which targets 4.8 or VS 15.8 P2. You will have to use that because this change is not targeted for 4.7 as VS 15.7 has a high escrow bar at this point in time.

**Comment by maartenba** [comment]
Ok guess we will wait then.

**Comment by maartenba** [comment]
When using `https://freetsa.org/tsr` as the server, signing seems impossible. Should I open a separate issue or is this something you could check? (exception is `TimestampException` with message about signature algorithm, but not a lot of info...)

**Comment by mishra14** [comment]
`https://freetsa.org/tsr` uses `SHA1` as its digest algorithm. We only allow `SHA256`, `SHA384` and `SHA512`, hence the error.

We have an [issue ](https://github.com/NuGet/Home/issues/6498) tracking adding more errors and warnings into our docs, to improve this experience.

**Comment by Busindre** [comment]
The response of the time stamp depends on the algorithm used in the request.

```
# Create a time stamp request (sha256)
openssl ts -query -data Selección_00426.png -no_nonce -sha256 -out file.tsq

sha256sum Selección_00426.png
df03eb7607d796616cb984d98fd493ed8ad5394d8b7e9ba594c33c52ead43cae  Selección_00426.png

# Timestamp.
curl -H "Content-Type: application/timestamp-query" --data-binary '@file.tsq' https://freetsa.org/tsr > file.tsr


# Timestamp response (in Text).
openssl ts -reply -in file.tsr -text

Status info:
Status: Granted.
Status description: unspecified
Failure info: unspecified

TST info:
Version: 1
Policy OID: tsa_policy1
Hash Algorithm: sha256   <---------
Message data:
    0000 - df 03 eb 76 07 d7 96 61-6c b9 84 d9 8f d4 93 ed   ...v...al.......  <--------- sha256
    0010 - 8a d5 39 4d 8b 7e 9b a5-94 c3 3c 52 ea d4 3c ae   ..9M.~....<R..<.
Serial number: 0x07DCC9
Time stamp: May  4 08:50:16.235511 2018 GMT
Accuracy: 0x01 seconds, 0x01F4 millis, 0x64 micros
Ordering: yes
Nonce: unspecified
TSA: DirName:/O=Free TSA/OU=TSA/description=This certificate digitally signs documents and time stamp requests made using the freetsa.org online services/CN=www.freetsa.org/emailAddress=busilezas@gmail.com/L=Wuerzburg/C=DE/ST=Bayern
Extensions:

# Verify (File)
 openssl ts -verify -data Selección_00426.png -in file.tsr -CAfile cacert.pem -untrusted tsa.crt 
Using configuration from /etc/ssl/openssl.cnf
Verification: OK


# Verify (digest sha256).
openssl ts -verify -digest df03eb7607d796616cb984d98fd493ed8ad5394d8b7e9ba594c33c52ead43ca1 -in file.tsr -CAfile cacert.pem -untrusted tsa.crt
Verification: OK


# sha1 (FAIL!)
sha1sum Selección_00426.png
73e4a7c4b609ae5d043287e6b9fe3d33131799d1  Selección_00426.png

openssl ts -verify -digest 73e4a7c4b609ae5d043287e6b9fe3d33131799d1 -in file.tsr -CAfile cacert.pem -untrusted tsa.crt 
Verification: FAILED
```
