### ISSUE TITLE
IVsPackageInstallerProjectEvents/IVsPackageInstallerEvents events not raised with PackageReference

### ISSUE THREAD

**Issue by meziantou** [NuGet/Home#6872]
## Detailed repro steps so we can see the same problem

1. Create a VSIX that registers the `IVsPackageInstallerProjectEvents` and `IVsPackageInstallerEvents`
2. Start Visual Studio with this VSIX loaded
3. Create a new solution
4. Create a new project
5. Add a NuGet reference as packages.config => Events are raised
6. Create a new project
7. Add a NuGet reference as PackageReference => Events are not raised

Code of the extension: [VSIXProject1.zip](https://github.com/NuGet/Home/files/1955574/VSIXProject1.zip)

Question: Is there a way to be notified when a PackageReference is added/removed using the NuGet UI?

## Details about Problem

NuGet product used:
VSIX in VS 2017

VS version (if appropriate): 
15.6.7

OS version:
Windows 10 v1607 14393.2125

**Comment by kzu** [comment]
This is preventing Xamarin from providing tooling around some common user mistakes around packages. 

Could this be prioritized higher @rrelyea?

Related work items: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/656082, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/638278

Thanks!

**Comment by tonyhallett** [comment]
Please make it consistent.  What is your suggested workaround ? Poll IsInstalled ?

**Comment by dreddy-work** [comment]
Any alternative work arounds here?

**Comment by nkolev92** [comment]
In 17.2, we're adding an API that's kind of equivalent, represents how PackageReference projects work.

~You can read more about it in https://github.com/NuGet/Home/blob/dev/proposed/2021/ProjectUpdateEventsInVisualStudio.md~

That's the design doc. 

You can see the API docs at https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivsnugetprojectupdateevents-interface.

**Comment by nkolev92** [comment]
Hey all, 

Please refer to the https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivsnugetprojectupdateevents-interface API for project updates in PackageReference projects. 

The end goal is to make this API handle packages.config projects as well. and you can track that here: https://github.com/NuGet/Home/issues/11707

I will update the documentation with these details and close this issue. 

We won't be making IVsPackageInstallerProjectEvents support PackageReference.

**Comment by nkolev92** [comment]
PR out for both the documentation update and the fix to enable https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivsnugetprojectupdateevents-interface for the packages.config based projects.
