### ISSUE TITLE
Spec: nuget signing client policies

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#6881]
Finish the [spec](https://github.com/NuGet/Home/wiki/%5BSpec%5D-NuGet-Package-Signing-Client-Policy) on nuget package signing client policy. 

This should include discussing the solutions  for config file changes and new command line and VSUI experiences to allow the user specify client policies and trusted signers.

**Comment by mishra14** [comment]
@PatoBeltran there is already an issue for this - https://github.com/NuGet/Home/issues/6526

**Comment by PatoBeltran** [comment]
@mishra14 Alright, I will take over that one issue.. closing this
