### ISSUE TITLE
Package manager UI : preview changes, ok button not automatically useable by keyboard

### ISSUE THREAD

**Issue by Styxxy** [NuGet/Home#6893]
Regarding the (Visual Studio) package manager UI.

The preview changes dialog box can't be accepted (= ok button) automatically by the enter key ("accept button"), while generally this is possible. Can you please provide this functionality, to make it more keyboard friendly?

![nuget-preview-changes](https://user-images.githubusercontent.com/1635825/39525961-c201dc96-4e1d-11e8-9a6b-911b277072fd.png)

**Comment by PatoBeltran** [comment]
Thanks for opening this issue @Styxxy! We are working on making our nuget tools more accessible. 

Are you able to tab your way into the "OK" button or is it unreachable by keyboard?

We will put this on out backlog and try to get it as soon as possible!

**Comment by Styxxy** [comment]
@PatoBeltran
Yes it is possible using tab, but sometimes I am in a flow of using keyboard and all dialogs are easily accepted by enter, so it kinda breaks the flow. Especially when installing many packages in many solutions.

Not high priority for me personally, but maybe for other people it is more important.
