### ISSUE TITLE
Nuget pack ignore version assembly when exe renamed to something different than nuget.exe

### ISSUE THREAD

**Issue by SiOuz** [NuGet/Home#6895]
I updated my nuget.exe  from 2.8.6 to (3.5.0, 4.4.1,, 4.6.2), since then, the execution of "pack" command create a new nupkg with the 1.0.0 version. I didn't have this issue with the previous version.

My AssemblyInfo.cs : 

> using System.Reflection;
> using System.Runtime.CompilerServices;
> using System.Runtime.InteropServices;
> 
> // Les informations générales relatives à un assembly dépendent de 
> // l'ensemble d'attributs suivant. Changez les valeurs de ces attributs pour modifier les informations
> // associées à un assembly.
> [assembly: AssemblyTitle("Popcorn.WebClient.Authentication")]
> [assembly: AssemblyDescription("Librairie d'accès au serveur de configuration de Popcorn Media")]
> [assembly: AssemblyConfiguration("")]
> [assembly: AssemblyCompany("")]
> [assembly: AssemblyProduct("Popcorn.WebClient.Authentication")]
> [assembly: AssemblyCopyright("Copyright ©  2015")]
> [assembly: AssemblyTrademark("")]
> [assembly: AssemblyCulture("")]
> 
> // L'affectation de la valeur false à ComVisible rend les types invisibles dans cet assembly 
> // aux composants COM. Si vous devez accéder à un type dans cet assembly à partir de 
> // COM, affectez la valeur true à l'attribut ComVisible sur ce type.
> [assembly: ComVisible(false)]
> 
> // Le GUID suivant est pour l'ID de la typelib si ce projet est exposé à COM
> [assembly: Guid("856e07fc-a6f0-490f-864f-b8749256b2da")]
> 
> // Les informations de version pour un assembly se composent des quatre valeurs suivantes :
> //
> //      Version principale
> //      Version secondaire 
> //      Numéro de build
> //      Révision
> //
> // Vous pouvez spécifier toutes les valeurs ou indiquer les numéros de build et de révision par défaut 
> // en utilisant '*', comme indiqué ci-dessous :
> // [assembly: AssemblyVersion("1.0.*")]
> [assembly: AssemblyVersion("1.14.0")]
> [assembly: AssemblyFileVersion("1.14.0")]
> [assembly: AssemblyInformationalVersion("1.14.0")]

My nuspec file :

`<?xml version="1.0"?>
<package >
  <metadata>
    <id>Popcorn.WebClient.Authentication</id>
    <version>$version$</version>
    <title>Popcorn.WebClient.Authentication.nuspec</title>
    <authors>Popcorn Media</authors>
    <owners>Popcorn Media</owners>
    <licenseUrl>http://www.popcorn-media.fr</licenseUrl>
    <projectUrl>http://www.popcorn-media.fr</projectUrl>
    <iconUrl>https://pop-lc-dev02/popcorn-media.png</iconUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Popcorn.WebClient.Authentication</description>
    <releaseNotes></releaseNotes>
    <copyright>Copyright 2017</copyright>
    <tags>Popcorn.WebClient.Authentication</tags>
  </metadata>
</package>`

Log : 

>  C:\Jenkins\workspace\Popcorn.WebClient.Authentication>"C:\Nuget\nuget_3.5.0.exe"
>  pack Popcorn.WebClient.Authentication.csproj -Build -Properties Configuration=R
> elease -IncludeReferencedProjects -symbols
> Attempting to build package from 'Popcorn.WebClient.Authentication.csproj'.
> MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86
> )\MSBuild\14.0\bin'.
> Building project 'C:\Jenkins\workspace\Popcorn.WebClient.Authentication\Popcorn.
> WebClient.Authentication.csproj' for target framework '.NETFramework,Version=v4.
> 5'.
> Microsoft (R) Build Engine version 14.0.25420.1
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 02/05/2018 17:26:10.
> Project "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\Popcorn.WebClien
> t.Authentication.csproj" on node 1 (default targets).
> GenerateTargetFrameworkMonikerAttribute:
> Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output fi
> les are up-to-date with respect to the input files.
> CoreCompile:
> Skipping target "CoreCompile" because all output files are up-to-date with resp
> ect to the input files.
> _CopyOutOfDateSourceItemsToOutputDirectoryAlways:
>   Copying file from "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\Popc
>   orn.WebClient.Authentication.nuspec" to "bin\Release\Popcorn.WebClient.Authen
>   tication.nuspec".
>   Copying file from "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\popc
>   orn-auth.cer" to "bin\Release\popcorn-auth.cer".
>   Copying file from "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\popc
>   orn-cert.cert" to "bin\Release\popcorn-cert.cert".
>   Copying file from "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\popc
>   orn-key.key" to "bin\Release\popcorn-key.key".
> _CopyAppConfigFile:
> Skipping target "_CopyAppConfigFile" because all output files are up-to-date wi
> th respect to the input files.
> CopyFilesToOutputDirectory:
>   Popcorn.WebClient.Authentication -> C:\Jenkins\workspace\Popcorn.WebClient.Au
>   thentication\bin\Release\Popcorn.WebClient.Authentication.dll
> Done Building Project "C:\Jenkins\workspace\Popcorn.WebClient.Authentication\Po
> pcorn.WebClient.Authentication.csproj" (default targets).
> 
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.12
> Packing files from 'C:\Jenkins\workspace\Popcorn.WebClient.Authentication\bin\Re
> lease'.
> Using 'Popcorn.WebClient.Authentication.nuspec' for metadata.
> Found packages.config. Using packages listed as dependencies
> Successfully created package 'C:\Jenkins\workspace\Popcorn.WebClient.Authenticat
> ion\Popcorn.WebClient.Authentication.1.0.0.nupkg'.
> 
> Attempting to build symbols package for 'Popcorn.WebClient.Authentication.csproj
> '.
> Packing files from 'C:\Jenkins\workspace\Popcorn.WebClient.Authentication\bin\Re
> lease'.
> Using 'Popcorn.WebClient.Authentication.nuspec' for metadata.
> Found packages.config. Using packages listed as dependencies
> Successfully created package 'C:\Jenkins\workspace\Popcorn.WebClient.Authenticat
> ion\Popcorn.WebClient.Authentication.1.0.0.symbols.nupkg'.

**Comment by PatoBeltran** [comment]
Hey @SiOuz I'm trying to reproduce your issue but I'm not able to. I created a new .NETFramework class library and used your `AssemblyInfo` and your `.nuspec` file, but after running pack I got the expected version of the nupkg:

```
D:\repos\ClassLibrary112\ClassLibrary112>nuget.exe pack -Build -Properties Configuration=Release -IncludeReferencedProjects -symbols
Attempting to build package from 'ClassLibrary112.csproj'.
MSBuild auto-detection: using msbuild version '15.7.172.38367' from 'D:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'.
Building project 'D:\repos\ClassLibrary112\ClassLibrary112\ClassLibrary112.csproj' for target framework '.NETFramework,Version=v4.6'.
Microsoft (R) Build Engine version 15.7.172.38367 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/2/2018 1:50:13 PM.
Project "D:\repos\ClassLibrary112\ClassLibrary112\ClassLibrary112.csproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Release\".
  Creating directory "obj\Release\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
  D:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\Microsoft.CSharp.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\mscorlib.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Data.DataSetExtensions.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Data.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Net.Http.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.dll" /reference:"D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Xml.Linq.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\ClassLibrary112.dll /ruleset:"D:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static AnalysisTools\\RuleSets\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output Class1.cs Properties\AssemblyInfo.cs "D:\AppData\Local\Temp\.NETFramework,Version=v4.6.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: D:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "obj\Release\ClassLibrary112.dll" to "bin\Release\ClassLibrary112.dll".
  ClassLibrary112 -> D:\repos\ClassLibrary112\ClassLibrary112\bin\Release\ClassLibrary112.dll
  Copying file from "obj\Release\ClassLibrary112.pdb" to "bin\Release\ClassLibrary112.pdb".
Done Building Project "D:\repos\ClassLibrary112\ClassLibrary112\ClassLibrary112.csproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.95
Packing files from 'D:\repos\ClassLibrary112\ClassLibrary112\bin\Release'.
Using 'ClassLibrary112.nuspec' for metadata.
Successfully created package D:\source\repos\ClassLibrary112\ClassLibrary112\Popcorn.WebClient.Authentication.1.14.0.nupkg'.

Attempting to build symbols package for 'ClassLibrary112.csproj'.
Packing files from 'D:\repos\ClassLibrary112\ClassLibrary112\bin\Release'.
Using 'ClassLibrary112.nuspec' for metadata.
Successfully created package D:\repos\ClassLibrary112\ClassLibrary112\Popcorn.WebClient.Authentication.1.14.0.symbols.nupkg'.
```

Can you please provide me with a sample project in a zip or a onedrive where you can reproduce this issue that can help me investigate?

**Comment by SiOuz** [comment]
Here the project.

the command line :
`
./nuget_4.6.2.exe pack Popcorn.WebClient.Authentication.csproj -Build -Properties Configuration=Release -IncludeReferencedProjects -symbols`




[DemoNuget.zip](https://github.com/NuGet/Home/files/1973708/DemoNuget.zip)

**Comment by PatoBeltran** [comment]
Thanks for the demo project! I am able to reproduce this issue with the nuget.exe you had stored in that project. It seems that this only happens when the exe file is not named `nuget.exe` (in your case it was name `nuget_4.6.2.exe`). I will keep investigating on why this happens, for now you can rename the exe and it should work as you expect.

**Comment by PatoBeltran** [comment]
Hey @SiOuz I found that we already have an issue for this. I will close this issue in favor of https://github.com/NuGet/Home/issues/3146, please feel free to vote on it or continue the conversation as needed. Thanks!
