### ISSUE TITLE
Restore not incremental when running publish after a restore

### ISSUE THREAD

**Issue by weshaggard** [NuGet/Home#6896]
While updating the core-setup repo to the RC1 version of the SDK we started hitting failures in our tool initialization. See https://github.com/dotnet/core-setup/pull/4115. 

Our tool project calls "dotnet restore" followed by "dotnet publish" and the restore during the publish command isn't incremental in some cases. I've not been able to repro this locally but our CI hits it every time on our linux machines. 

The fact it isn't incremental causes issues because we don't pass the restore sources to the publish command so the restore fails. We can adjust our scripts to pass "--no-restore" or the sources to workaround this issue but I think you guys should investigate why the incremental restore is failing.

**Comment by rohit21agrawal** [comment]
has this ever worked before? if so, in what version?

**Comment by nkolev92** [comment]
The incremental restore is failing due to the sources change. 
That hasn't changed. 

You could have some extra packages in the global packages folder locally which is why it doesn't need to talk to the server in that situation. 

Can you give us a pointer to the extract project that fails? 
I couldn't figure out from the logs as it's named only project.csproj

**Comment by weshaggard** [comment]
The project is https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tool-runtime/project.csproj.

>The incremental restore is failing due to the sources change.

The sources do change but it is correctly incremental on all my local tests. 

>has this ever worked before? if so, in what version?

Yes this has worked and continues to work everywhere except this one linux CI machine. I'm not sure what is unique about that CI machine.

**Comment by nkolev92** [comment]
It's only reproducible on RHEL72, it seems like the root cause is https://github.com/dotnet/corefx/issues/29095.

**Comment by weshaggard** [comment]
@nkolev92 thanks for the investigation. Did you find evidence of the corefx issue being the cause or are you just making an assumption? If you have some evidence please share I will help get that issue fixed as well.

**Comment by nkolev92** [comment]
@weshaggard 
It's an assumption, but I can easily pinpoint why NuGet would behave the way it does if that bug is hit.

**Comment by weshaggard** [comment]
Any pointers or hints you can share would be helpful in tracking down the issue.

**Comment by weshaggard** [comment]
OK we were able to confirm that the corefx issue https://github.com/dotnet/corefx/issues/29095 is the problem. It was fixed in master with https://github.com/dotnet/corefx/pull/29502 with plans to get it approved for 2.1

**Comment by nkolev92** [comment]
Thanks for closing the loop @weshaggard
