### ISSUE TITLE
PATH setup issue with numerous subpackages when targetPlatform=native

### ISSUE THREAD

**Issue by zosrothko** [NuGet/Home#6897]
## Details about Problem
Let say my C++ application is using a NuGet package that brings a transitive dependencies tree of 20 differents packages with each one a `bin`, `inc`, `lib` directory. The `*.target` of each package allows a smooth integration with the build process of my applicaton, but when it comes to its execution, one needs to setup the PATH with ALL THE 20 `bin` directories where the DLLs of each package are found.
This is a real nigthmare and is error prone, notably if the transitive dependencies are varying time. Thus this issue is requesting for adding a global property like for exemple `NUGET_DLL` where nuget.client will put all the content of the `bin` directory of each package. As such, one will have to add only one directory to the PATH in order to run the application

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zosrothko** [comment]
Hello NuGet team... This issue is a real PITA. Can someone have a look?

**Comment by zhili1208** [comment]
Could you explain more about what you want to do? Does the each package bin folder contain a exe which you want to run during your build? Or there is only one exe you want to run, all other packages contain dependency dll?

**Comment by zosrothko** [comment]
I am building an application (an app.exe) that is using a Nuget package P1 delivered as a bin/p1.dll that is using itself another nuget package P2 as bin/p2.dll. Thus for running my app.exe I need to put the P2/bin and P1/bin on the PATH. Thus it is your second case "Or there is only one exe you want to run, all other packages contain dependency dll?"

More generally, imagine that the transitive dependency subtree  of the first package contains 20 subpackages, it is a real nigthmare to setup the PATH. That's why I am proposing the `NUGET_DLL` extension to put all the subpackage dll so that the only statement needed be: PATH=%NUGET_DLL%;%PATH%

**Comment by zhili1208** [comment]
I want to understand how you run your app.exe, after build your exe, you can copy all dependency dlls to one folder with your exe. Why you need to add all bin folders to PATH?

**Comment by zosrothko** [comment]
because **I do not want to copy all dependency dlls to one folder.**. **I do not know and do not want to know which package is/are delivered as dll or lib.** This is uneccessary and wastefull. Moreover, it is error prone and make errors difficult to trap if one or more dlls are updated and one forgets to copy. Thus an automatic tool as Nuget should do the job as it already download the dependency dll

**Comment by nkolev92** [comment]
@zosrothko 
This is not supported.
NuGet does not participate in your runtime, but only in your build. 

If you want to have an executable in a package it should be self-contained.
