### ISSUE TITLE
Managed NuGet packages for Solution doesn't work with an empty solution or a solution containing only unloaded projects

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#690]
1. File -> New C# Console Application
2. Right-click on C# Console Application and Choose Unload
3. Right-click on Solution
4. Choose Manager NuGet packages for Solution

Expected: For the package manager to open for the solution
Actual: Nothing

Repro in recent build of VS 2015.

**Comment by yishaigalatzer** [comment]
This is expected, there is no more solution level package in NuGet. Manage packages for solution means manage it for all the loaded projects "together"

**Comment by davkean** [comment]
I don't understand. How is doing _nothing_ a correct behavior? Shouldn't the menu be disabled in this case?

**Comment by yishaigalatzer** [comment]
Probably true. I missed that piece

**Comment by yishaigalatzer** [comment]
This menu shows up before NuGet is loaded, so it is impossible to disable it. But we can probably show an error message in this case and perhaps disable it later.

Priority doesn't seem to be high enough to try and fix it for RTM, moving to Update I

**Comment by davkean** [comment]
You can use capabilities now to disable/hide a menu. In this case, we should make sure to have the right capabilities registered across all the project types you care about so that you can hide yourselves when not applicable.

**Comment by yishaigalatzer** [comment]
This has nothing to do with capabilities. Ping me tomorrow and I can explain in person

**Comment by davkean** [comment]
It does have to do with capabilities. You can now disable/enable menu items based on capabilities _without_ loading your package. You mark your menu item as only being enabled when the right project types are loaded, then it doesn't show up nor load your package.

**Comment by yishaigalatzer** [comment]
We are going to wait for user feedback on this before prioritizing it into a release

**Comment by rohit21agrawal** [comment]
the menu option has been disabled
