### ISSUE TITLE
Consider adding a "Add a new package source" UI right under the package source drop down 

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#691]

**Comment by yishaigalatzer** [comment]
@feiling can you provide more information, screen shot with the suggestion and why do you think this is important?

**Comment by yishaigalatzer** [comment]
We already have a configuration button on the right side of the UI

![image](https://cloud.githubusercontent.com/assets/1238711/7944036/32178d44-091d-11e5-97a9-f6c84a0b3114.png)
