### ISSUE TITLE
IsLatestVersion Metadata flag is always false with query param semVerLevel=2.0.0

### ISSUE THREAD

**Issue by morad3741** [NuGet/Home#6911]
Hi,
Ive encountered some inconsistency with the Search and FindPackagesById endpoints, i would like to get your opinion on that:

1. When reaching:
https://www.nuget.org/api/v2/FindPackagesById()?id=%27sleet%27
Ive noticed the next metadata: 
> <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>

on entry with version: 1.0.1,
but when reaching the same endpoint with semVerLevel param:
https://www.nuget.org/api/v2/FindPackagesById()?id=%27sleet%27&semVerLevel=2.0.0
there is no entry with IsLatestVersion flag set to true,
why is that?

2. When using nuget list command the client reaching to:
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30
you will notice 2 entries with IsLatestVersion flag set to true : 1.0.1 & 0.2.5 (Why there is two versions with that flag?),
but when doing the same query with semVerLevel=2.0.0 param:
https://www.nuget.org/api/v2/Search()?$filter=IsLatestVersion&$orderby=Id&searchTerm=%27sleet%27&targetFramework=%27%27&includePrerelease=false&$skip=0&$top=30&semVerLevel=2.0.0
there is no entry with IsLatestVersion flag set to true,
why is that?

thank you for your help.

**Comment by zhili1208** [comment]
Issue moved to [NuGet/NuGetGallery #5904](https://github.com/NuGet/NuGetGallery/issues/5904) via [**ZenHub**](https://www.zenhub.com/)
