### ISSUE TITLE
Error when fetching packages from a V3 endpoint that lists the `RepositorySignatures/4.7.0` resource

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#6912]
In VS2017 (15.7), we are seeing the following error when fetching packages from a V3 endpoint that lists the `RepositorySignatures/4.7.0` resource.

The error:
```
Unable to get repository signature information for source https://...../api/v3/repository-signatures/index.json
Unable to parse allRepositorySigned information from https://...../api/v3/index.json
```

The service index lists:
```
    {
      "@id": "https://......./api/v3/repository-signatures/index.json",
      "@type": "RepositorySignatures/4.7.0",
      "comment": "The endpoint for discovering information about this package source's repository signatures."
    },
```

The repository signatures resource: (with an empty array of signing certificates):
```
{
  "allRepositorySigned": "false",
  "signingCertificates": []
}
```

Can the client handle this more gracefully?

**Comment by morad3741** [comment]
Hi @maartenba,
Im not seeing "repository-signatures" resource in https://api.nuget.org/v3/index.json ,
which feed url do you use?

**Comment by maartenba** [comment]
This was on a private NuGet server. If you need to repro, try this URL as the package source:
https://stagingmyget.blob.core.windows.net/public/nuget-issue-6912/index.json

**Comment by maartenba** [comment]
Wondering if this is caused by the `"allRepositorySigned": "false"` being a string instead of a boolean. (the [code seems to expect a boolean](https://github.com/NuGet/NuGet.Client/blob/c4c7d2d3dd75604be94161a19c3c4e31dd4fb7d3/src/NuGet.Core/NuGet.Protocol/Resources/RepositorySignatureResource.cs#L25))

**Comment by nkolev92** [comment]
//cc @PatoBeltran @mishra14 @zhili1208

**Comment by zhili1208** [comment]
it's caused by this https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Converters/JsonExtensions.cs#L118

if the type is not Boolean, converter return null

**Comment by maartenba** [comment]
Got it, thanks! So just making it a boolean in the JSON should do it, right?
