### ISSUE TITLE
Could not found the symbol package after it successfully pushed to the server.

### ISSUE THREAD

**Issue by liushuanggang** [NuGet/Home#6916]
## Details about Problem

I have successfully pushed a  symbol package to the  symbol server, but I could not list it after that, it return me "No packages found".

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet.exe

NuGet version (x.x.x.xxx):

4.5.1

OS version (i.e. win10 v1607 (14393.321)):

Win10

## Detailed repro steps so we can see the same problem

1. Push the symbol package to the symbol server with command line:

`nuget push PackageARMTest.1.0.1.symbols.nupkg -source https://nuget.smbsrc.net/`

2. List the pushed package with command line:

`nuget.exe list PackageARMTest -AllVersion -Prerelease -source https://nuget.smbsrc.net`

But return "No packages found", Then I have check another symbol package, which pushed very early **LSGTestNuGetPackage**, it works fine.

**Comment by jainaashish** [comment]
Please try with latest NuGet.exe (https://dist.nuget.org/win-x86-commandline/v4.7.0/nuget.exe ) if that works for you. There was an issue with 4.5.1 build where it was reading it from cache and waiting for 30 mins to refresh it.

**Comment by liushuanggang** [comment]
@jainaashish, Thanks for your reply. Using nuget.exe 4.7.0 still not found that symbol package.

**Comment by zhili1208** [comment]
looks like a symbol server issue, please file a bug at https://github.com/SymbolSource/SymbolSource/issues, nuget team is also working on a better symbol experience, check the blog post: https://blog.nuget.org/20180501/Welcoming-SymbolSource-to-Dot-Net-Foundation.html, welcome feedback in issue #6104

**Comment by liushuanggang** [comment]
@zhili1208, Thanks, I will when I free.

**Comment by Fresa** [comment]
Any progress? This does not seem to have been resolved. I have the same issue.

**Comment by JeremyTCD** [comment]
Same issue, my CI script failed to push symbols, so I tried pushing them manually:
```
PS D:\Downloads> nuget push .\JeremyTCD.WebUtils.SyntaxHighlighters.Prism.1.0.0-beta.1.symbols.nupkg -Source https://nuget.smbsrc.net/
Pushing JeremyTCD.WebUtils.SyntaxHighlighters.Prism.1.0.0-beta.1.symbols.nupkg to the symbol server (https://nuget.smbsrc.net/)...
  POST https://www.nuget.org/api/v2/package/create-verification-key/JeremyTCD.WebUtils.SyntaxHighlighters.Prism/1.0.0-beta.1
  OK https://www.nuget.org/api/v2/package/create-verification-key/JeremyTCD.WebUtils.SyntaxHighlighters.Prism/1.0.0-beta.1 1124ms
  PUT https://nuget.smbsrc.net/api/v2/package/
  OK https://nuget.smbsrc.net/api/v2/package/ 2510ms
```
Reponse seemed to indicate that the push was successful, but:
```
PS D:\Downloads> nuget list JeremyTCD.WebUtils.SyntaxHighlighters.Prism -AllVersions -Prerelease -Source https://nuget.smbsrc.net
No packages found.
```
`nuget list` indicates that the push was not successful. Attempting to download the symbols when debugging in VS also fails. Seems like pushing new symbols is straight up not working right now.

**Comment by zhili1208** [comment]
looks like the symbol server issue, close it as dup of https://github.com/SymbolSource/SymbolSource/issues/7
