### ISSUE TITLE
After installing VS 15.7 cannot find migrate pacakge.config in menu.

### ISSUE THREAD

**Issue by msmolka** [NuGet/Home#6917]
## Details about Problem
Based on update information about Visual Studio 2017 (15.7), there should be option to migrate `packages.config` to `PackageReference`.

However after updating Visual Studio today, I cannot see such option when right-click on `references` or `package.config`

**Comment by msmolka** [comment]
after 30 mins doing nothing menu item shown up

**Comment by crenshaw-dev** [comment]
Same issue. I haven't waited 30min yet, but it's still a significant issue for people who read the release notes and immediately want to migrate packages.config. A bit disconcerting.

A reboot had no effect.

**Comment by icalvo** [comment]
I was able to see the menu item after going to Tools > Options > Nuget Package Manager, and choosing PackageReference as the default package management format.

**Comment by crenshaw-dev** [comment]
Confirmed. Thanks for the reference to the other issue. After changing the default package management format, the migrate option appeared for the non-ASP.NET projects, but not the ASP.NET projects.
