### ISSUE TITLE
Completely broken on VS2015 RC

### ISSUE THREAD

**Issue by Daniel15** [NuGet/Home#692]
I just upgraded from VS2015 CTP to RC, and NuGet seems completely broken out of the box:

![screen shot 2015-05-30 at 3 13 38 pm](https://cloud.githubusercontent.com/assets/91933/7895711/7cbee49e-06e0-11e5-883a-ce5675cb40d5.png)

I tried `devenv.exe /ResetUserData` but it didn't help.

Here's another exception I got:
```
The instance 042c2b4b-c7f7-49db-b7a2-402eb8dc7892 of extension point Microsoft.VisualStudio.Shell.Interop.IVsSearchProvider cannot be obtained from the package 5fcc8577-4feb-4d04-ad72-d6c629b083cc, or the extension is not of type Microsoft.VisualStudio.Shell.Interop.IVsSearchProvider.\r\nException of type 'System.Exception' was thrown.
```

**Comment by Daniel15** [comment]
I've also attempted the "fix" from https://connect.microsoft.com/VisualStudio/feedback/details/809074/nuget-failing-to-load-vs2013-becomes-unusable:
 - Uninstalled NuGet extension
 - Deleted the directories from C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions that contained NuGet stuff (oyyujfkb.u2o, 2fiugnvl.45a, gnp5qihb.x0j)
 - Reinstalled NuGet from https://visualstudiogallery.msdn.microsoft.com/5d345edc-2e2d-4a9c-b73b-d53956dc458d

Same error.

**Comment by Daniel15** [comment]
I "fixed" it by completely uninstalling Visual Studio, deleting all the remaining stuff in `C:\Program Files (x86)\Microsoft Visual Studio 14.0`, then reinstalling. Really annoying, this should be called out in the release notes if it's an issue.

**Comment by yishaigalatzer** [comment]
@csharpfritz can we please include this in the next set of release notes?

**Comment by csharpfritz** [comment]
I'll include these directions in the v3 release notes and announcement blog post
