### ISSUE TITLE
Frequent timeouts when establishing a connection to api-v2v3search-0.nuget.org

### ISSUE THREAD

**Issue by AndreyAkinshin** [NuGet/Home#6921]
Sometimes, requests to `api-v2v3search-0.nuget.org` and `api-v2v3search-1.nuget.org` are failed by timeout. It affects NuGet search experience in Visual Studio and Visual Studio for Mac (sometimes users have to wait up to several minutes before the NuGet search results are shown):
![vs](https://user-images.githubusercontent.com/2259237/39778540-4315958e-530f-11e8-9c38-998f08783334.gif)

Here are some logs from `RawSearchResourceV3`:
```
Information   GET https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0
Information An error was encountered when fetching
  'GET https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0'. The request will now be retried.
The HTTP request to 'GET https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0'
  has timed out after 100000ms.
Information   GET https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0
Information   OK https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0 1090ms
```

A minimal example which reproduces the issue:
```cs
for (int i = 0; i < 100; i++)
{
    using (var client = new HttpClient { Timeout = TimeSpan.FromSeconds(10000) })
    {
        Console.Write("Request #" + (i + 1).ToString("000") + ": ");
        var sw = Stopwatch.StartNew();
        try
        {
            var r = await client.GetAsync(
                "https://api-v2v3search-0.nuget.org:443/query?q=&skip=0&take=10&prerelease=false&semVerLevel=2.0.0");
            Console.Write("OK");
        }
        catch (Exception e)
        {
            Console.Write("FAIL                 .");
            Console.WriteLine(e);
        }
        sw.Stop();
        Console.WriteLine($" Time: {sw.Elapsed.TotalSeconds:0.000} sec");
    }
}
```

I tried it on my local machine and on an Azure VM:
![azure](https://user-images.githubusercontent.com/2259237/39778584-6389e586-530f-11e8-976e-7b2205155ab8.png)

You can find a detailed investigation here: https://aakinshin.net/blog/post/nuget-package-browsing/

**Comment by VahidN** [comment]
`using (var client = new HttpClient())` rings a bell!
- [You're using HttpClient wrong and it is destabilizing your software](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/)
- [Disposable, Finalizers, and HttpClient](https://blogs.msdn.microsoft.com/alazarev/2017/12/29/disposable-finalizers-and-httpclient/)
- [Using HttpClient as it was intended (because you’re not)](https://www.codeproject.com/Articles/1194406/Using-HttpClient-as-it-was-intended-because-you-re)
- [Singleton HttpClient? Beware of this serious behaviour and how to fix it](http://byterot.blogspot.co.uk/2016/07/singleton-httpclient-dns.html)
- [Beware of the .NET HttpClient](http://www.nimaara.com/2016/11/01/beware-of-the-net-httpclient/)
- [Effectively Using HttpClient](https://www.csantos.me/effectively-using-httpclient/)

**Comment by 0xced** [comment]
The linked blog post explains why the HttpClient is used this way:
> It's very important to create a new instance of HttpClient for the each iteration: otherwise, the connection will be reused, and we will not get such a picture.

**Comment by AndreyAkinshin** [comment]
In the first version of the repro, I used a single `HttpClient` instance for all requests. In this case, the first request fails in ~30% cases, other requests are successful because the connection is already established. From the practical point of view, it means that user can get hanged NuGet Package Manager in VS only once after startup.
However, in this case, it's hard to investigate the problem because it's very unstable. Thus, the code snippet creates a new HttpClient instance each time *on purpose*. So, it's very easy to reproduce the problem.

**Comment by zhili1208** [comment]
Issue moved to [NuGet/NuGetGallery #5899](https://github.com/NuGet/NuGetGallery/issues/5899) via [**ZenHub**](https://www.zenhub.com/)
