### ISSUE TITLE
Migrate Package References Added In 15.7, but removed in 15.7.1?

### ISSUE THREAD

**Issue by andrejohansson** [NuGet/Home#6922]
## Details about Problem

Yesterday I upgraded to 15.7.0 an was very happy that the [migrate package references tool](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) had been added to studio and it worked like a charm.

Today I updated to 15.7.1, and now the tool is gone again. Why?

![image](https://user-images.githubusercontent.com/2828428/39803596-b5bdc4fa-5371-11e8-9063-e917f26286c6.png)

## Detailed repro steps so we can see the same problem

1. Right click on any packages.config or "References" section of an old csproj style project
2. Expect the menu ``Migrate packages.config to PackageReference....`` to be present. But its not.

## Other suggested things
Nothing in the release log mentions anything about that the feature should be removed again.

**Comment by rrelyea** [comment]
Have not removed feature.
If you cannot see menu item, most likely due to the fact that some packages.config project types may not be fully compatible.

Asp.net projects are not yet enabled.
C++ projects are not yet enabled.

**Comment by andrejohansson** [comment]
I can confirm that I can see it on some projects but not others. But I cant really determine which ones I do not see them in. For example, I have unit test projects where it doesn´t show up (and I could swear it did show up yesterday). As for ServiceFabric Actor projects, I could understand if it doesnt show on these projects. 

But isnt unit test projects supported?

Thanks for your reply.

**Comment by icalvo** [comment]
Maybe related: in 15.7.0, if you don't change the default option to PackageReference in Tools > Options > Nuget Package Manager, you won't see the context menu item. See #6917.

**Comment by andrejohansson** [comment]
So this is no issue, its a matter about which project types are compatible (is there a list somewhere?), closing.
