### ISSUE TITLE
NuGet doesn't emit a warning when it relies on PackageTargetFallback

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#6925]
## Details about Problem
Project's using PackageTargetFallback don't emit a warning so folks are often unknowingly using a package that may not be compatible with what they are targeting

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe & VS

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):
2.1.300-rc1-008673

VS version (if appropriate):
15.7 preview 4

OS version (i.e. win10 v1607 (14393.321)):
win10 1709 (16299.431)
 
Worked before? If so, with which NuGet version:
Don't know

## Detailed repro steps so we can see the same problem

1. dotnet new console, targeting netcoreapp2.0 or netcoreapp2.1.
2. Add reference to <PackageReference Include="Newtonsoft.Json" Version="6.0.8" />
3. dotnet restore.
4. Observe warning `warning NU1701: Package 'Newtonsoft.Json 6.0.8' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.`  This is good.
5. Change project to use PackageTargetFallback: 
```xml
    <DisableImplicitAssetTargetFallback>true</DisableImplicitAssetTargetFallback>
    <PackageTargetFallback>net461</PackageTargetFallback>
```
6. dotnet restore
7. Observe no warning.  This is bad

### Sample Project
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <DisableImplicitAssetTargetFallback>true</DisableImplicitAssetTargetFallback>
    <PackageTargetFallback>net461</PackageTargetFallback>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="6.0.8" />
  </ItemGroup>

</Project>
```

I understand that the warning addition was part of the AssetTargetFallback feature, but for the same reason that we needed it there we need it on PackageTargetFallback as well (since PTF isn't deprecated and still used).

**Comment by nkolev92** [comment]
At this point we haven't received enough feedback to change this behavior. 

We can reconsider if we receive more feedback.
