### ISSUE TITLE
Update-Package fails with "Empty path name is not legal."

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#693]
A package I'm developing is frequently having trouble updating or removing from projects:

    PM> update-package MicroBuild.Teams.Project -version 1.0.0-alpha-g0cfe4257d3
    Attempting to gather dependencies information for package 'MicroBuild.Teams.Project.1.0.0-alpha-g0cfe4257d3' with respect to project targeting '.NETFramework, Version=v4.5'
    Attempting to resolve dependencies for package 'MicroBuild.Teams.Project.1.0.0-alpha-g0cfe4257d3' with DependencyBehavior 'Lowest'
    Resolving actions to install package 'MicroBuild.Teams.Project.1.0.0-alpha-g0cfe4257d3'
    Resolved actions to install package 'MicroBuild.Teams.Project.1.0.0-alpha-g0cfe4257d3'
    Install failed. Rolling back...
    Package 'MicroBuild.Teams.Project.1.0.0-alpha-g7dfefa638a' already exists in project 'Microsoft.VisualStudio.Validation'
    update-package : Empty path name is not legal.
    At line:1 char:1
    + update-package MicroBuild.Teams.Project -version 1.0.0-alpha-g0cfe425 ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.Updat 
       ePackageCommand
 
    PM> 

What does this error even mean? What path is empty?

**Comment by AArnott** [comment]
This is on VSPro_Platform 22915.00 with NuGet Package Manager extension 3.0.60410.213.

Reloading the solution doesn't seem to fix it, but restarting VS usually does.

**Comment by yishaigalatzer** [comment]
@AArnott can you please provide us with a repro project? Can you please pickup the latest NuGet extension?

**Comment by AArnott** [comment]
I'd love to try your latest VSIX. I just keep forgetting the UNC path to go get it.
If it repros with that, yes, I'll share that with you.

**Comment by AArnott** [comment]
No repro on recent builds of D14Rel with latest VSIX so far.

**Comment by joshcomley** [comment]
I am getting this error on the latest public VSIX from the VS Gallery all over the place. I am running VS2015, so I tried downloading the latest build VSIX (http://build.nuget.org/NuGet.Tools.vsix) but it is not compatible with VS2015.

How can I update to the latest Nuget to try to fix this?

**Comment by yishaigalatzer** [comment]
Latest public version http://nuget.codeplex.com/releases is rc2. We don't have newer versions in the public.

**Comment by grokys** [comment]
Getting this too on VS2015 RTM. Can't update or uninstall packages.

**Comment by newton3** [comment]
Same here. I am on VS 2015 RC.

**Comment by yishaigalatzer** [comment]
@grokys can you please open a new bug with exact repro steps?
@newton3 we are no longer taking reports from vs2015 rc please move to RTM

**Comment by grokys** [comment]
It now appears to show itself as #1135 using the latest NuGet.
