### ISSUE TITLE
MonoAndroid5.0 does not load .net40 packages correctly built in new VS2017 format

### ISSUE THREAD

**Issue by generik0** [NuGet/Home#6933]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used from: VS 2018 15.7.1

## Detailed repro steps so we can see the same problem

1. I have a .net standard template C# project that has <TargetFrameworks>net40;net45;netstandard1.6;netstandard2.0</TargetFrameworks>

2. The csproj uses NLog but has target "ItemGroup Condition" saying the net4 should use NLog 4.3.3 but net standard use Version <Version>4.5.4</Version>

3. When the packages is loaded intro a monoandroid5 , that should use net40 i would beleive, it trys to load dependancy 4.5.4. 

I have added into the csproj
<PackageTargetFallback>net40</PackageTargetFallback>
<DisableImplicitAssetTargetFallback>true</DisableImplicitAssetTargetFallback>
but this does not help

- Should monoandroid not load net40 framework? it does not support .net standard?
- Why is the package manager loading the incorrect dependency version?
- Is there a better way to insure Monoandroid 5 when creating packages using new VS2017 .net standardard tempate?

csproj included in zip

[Comapny.Common.Core.zip](https://github.com/NuGet/Home/files/2003999/Comapny.Common.Core.zip)

**Comment by mishra14** [comment]
This issue was moved to mono/mono#8724

**Comment by mishra14** [comment]
@generik0 it is unclear what mono android5.0 is. I have moved this issue to the mono team.

**Comment by generik0** [comment]
@mishra14
Hi, I think it is strange you moved this.
In nuget packages you can add a lib called 
Monoandroid 

Also it is nuget resolving a dependency
Version that is higher than defined. 
This is definitely not a mono android issue.

It is a nuget issue. Nuget is not defaulting back to correct dependency versions.

**Comment by mishra14** [comment]
@generik0 thanks for responding. I am happy to track it here. But it is not clear what monoandroid5 is?
Is it a package? Do you have a link for it?

I looked at your csproj file and on restore, its assets file chooses the artifacts correctly. I packaged the csproj and its nuspec seemed fine as well.

Can you please give me exact repro steps that I can use to reproduce your problem?

**Comment by generik0** [comment]
@mishra14
When using VS2017 with Android xamarin, the framework is monoandroid for nuget packages.
Older android xamarin use a framework android 5 I the csproj. This resolves packages as monoandroid50 in the packages.config

Monoandroid5.0 supports importing net40 libs from nuget.
But if a package is multi target (as the csproj I added) then nuget tries to resolve the netstandard20 dependency.
It should try to resolve the net40 dependancy

**Comment by generik0** [comment]
I would expect that packages med using the new vs2017 .net stanard with target framework inkluding net40, that the net40 versions and dependancies should be installed as:

![image](https://user-images.githubusercontent.com/2411563/40143043-9e00ee0c-595a-11e8-9a5c-2b0195a8b373.png)


It appears that the packages defaly to the net40 libs from the nuget package, but the dependancies resolve as netstandard.
