### ISSUE TITLE
Transitive PackageReference packages do not contribute build logic

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#6934]
_From @dansiegel on May 15, 2018 16:0_

### Description

When adding a top level dependency with PackageReference, children are not properly loaded, causing build Tasks to be missing during build.

### Steps to reproduce

See attached sample project with binlog

[Foo.zip](https://github.com/Microsoft/msbuild/files/2005711/Foo.zip)

### Expected  behavior

Install a top level PackageReference such as Prism.DryIoc.Forms with a dependency on Prism.Forms, with a dependency on Xamarin.Forms and the build tasks from Xamarin.Forms should be executed during the build.

### Actual behavior

Build tasks are missing from the build pipeline unless Xamarin.Forms is added as it's own PackageReference.

### Environment data
`msbuild /version` output:
Microsoft (R) Build Engine version 15.7.0.0 (xplat-master/402b4b23 Wed Mar 28 23:51:55 EDT 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

OS info: OSX 10.13.4

If applicable, version of the tool that invokes MSBuild (Visual Studio, dotnet CLI, etc):

_Copied from original issue: Microsoft/msbuild#3314_

**Comment by rainersigwald** [comment]
Thanks for reporting. This looks like a NuGet restore behavior, so I'm going to move this to the NuGet repo.

**Comment by nkolev92** [comment]
Currently by design. 
Relevant [docs](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets).
Related work item tracking a potential change, although I am not too hopeful that it'll change. 

https://github.com/NuGet/Home/issues/6091

**Comment by Adam-S-Daniel** [comment]
@nkolev92 - I created an issue about the docs page you referenced. Do you think my concern there is accurate?

https://github.com/NuGet/docs.microsoft.com-nuget/issues/997 "_Clarify that props and targets assets will not be imported through transitive dependencies_"

**Comment by nkolev92** [comment]
@geeeyetee Yeah that's valid. 
I've added a small clarification.
