### ISSUE TITLE
15.7 changes the ValueTuple reference picked during restore

### ISSUE THREAD

**Issue by jaredpar** [NuGet/Home#6936]
This is a follow up investigation to #6367. The restore behavior for NuGet changed between 15.6 and 15.7 in such a way that it breaks the ability to build VsVim. Here are the repro steps:

- Clone the [VsVim project](https://github.com/jaredpar/VsVim)
- Run `git reset --hard 307a8b7fbc26917a113d5929817de05e3eb564ae`
- Run `msbuild /v:m /m /t:Restore VsVim.sln`.
- Run `msbuild /v:m /m VsVim.sln` 

**Note**: Make sure to use the command line, not Visual Studio. There are VS bugs in 15.6 which will give you flaky results (see #6367). 

When this is done in 15.6 the build will succeed warning free. When this is done in 15.7 the following warning will be produced multiple times:

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2220,5): warnin g MSB3836: The explicit binding redirect on "System.ValueTuple, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" conflicts with an aut ogenerated binding redirect. Consider removing it from the application configuration file or disabling autogenerated binding redirects.  The build will replace it with: "<bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" xmlns="urn:schemas-microsoft-com:a sm.v1" />". [E:\code\VsVim\Test\VimCoreTest\VimCoreTest.csproj]

This appears to be due to a restore behavior change. Examining the assets file for VimCoreTest.csproj (Binaries\obj\VimCore\project.assets.json) you can see a different ValueTuple is chosen:

15.6
``` json
  "System.ValueTuple/4.4.0": {
    "type": "package",
    "frameworkAssemblies": [
      "System",
      "mscorlib"
    ],
    "compile": {
      "ref/net461/System.ValueTuple.dll": {}
    },
    "runtime": {
      "lib/net461/System.ValueTuple.dll": {}
    }
  },

```

15.7
``` json
  "System.ValueTuple/4.3.1": {
    "type": "package",
    "compile": {
      "lib/netstandard1.0/System.ValueTuple.dll": {}
    },
    "runtime": {
      "lib/netstandard1.0/System.ValueTuple.dll": {}
    }
  },
```

This difference also shows up when looking at the binary log from the resulting build.

**Comment by jaredpar** [comment]
CC @cartermp as this is potentially related to F# targets changes. Specifically these lines

https://github.com/Microsoft/visualfsharp/blob/7aa7cd3734dcf5e9ff9a29cd2f5814be301f308b/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.targets#L90-L108

**Comment by cartermp** [comment]
@kevinransom as well - I'm not sure why we remove anything. Wouldn't just specifying SVT as a packagereference work?

**Comment by jaredpar** [comment]
> Wouldn't just specifying SVT as a packagereference work?

Possibly. In what solution should I make this reference? If it's in the C# code then are we saying that C# must reference ValueTuple in order to reference F# code?

**Comment by nguerrera** [comment]
There's a lot of strange going on in those F# targets. It's unconditionally adding a SVT ref to all projects then removing it in a target. My mind is melting trying to understand it.

**Comment by cartermp** [comment]
Sorry, I was referring to the F# targets. I think we came to a resolution about a better way to specify this dependency for F# via overrides, since they're currently bonkers. Not sure what the workaround here is.

**Comment by KevinRansom** [comment]
That code needs to change.  It went in before we had a good location to add project references.

However, what is the explicit redirect mentioned here.

We have always selected 4.3.1 by default for SVT and so do you explicit add 4.4.0 as a package reference somewhere?  Although that is definitely supposed to work.

````
The explicit binding redirect on "System.ValueTuple, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" conflicts with an aut ogenerated binding redirect. Consider removing it from the application configuration file or disabling autogenerated binding redirects. The build will replace it with: "". [E:\code\VsVim\Test\VimCoreTest\VimCoreTest.csproj]
````

**Comment by KevinRansom** [comment]
@jaredpar 

What did I do wrong, I didn't see those warnings, when I followed your repro using a 15.7.1 installof VS :

````
C:\jaredpar>git clone https://github.com/jaredpar/VsVim.git
Cloning into 'VsVim'...
remote: Counting objects: 37284, done.
remote: Total 37284 (delta 0), reused 0 (delta 0), pack-reused 37284
Receiving objects: 100% (37284/37284), 42.83 MiB | 9.20 MiB/s, done.
Resolving deltas: 100% (24482/24482), done.
Checking out files: 100% (720/720), done.

C:\jaredpar>cd VsVim

C:\jaredpar\VsVim>git reset --hard 307a8b7fbc26917a113d5929817de05e3eb564ae
HEAD is now at 307a8b7f Merge pull request #2133 from ricksladkey/paging-fixes

C:\jaredpar\VsVim>msbuild /v:m /m /t:Restore VsVim.sln.
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\jaredpar\VsVim\Src\VimTestUtils\VimTestUtils.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\CleanVsix\CleanVsix.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VimWpf\VimWpf.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VimApp\VimApp.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VimCore\VimCore.fsproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VimEditorHost\VimEditorHost.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VsInterfaces\VsInterfaces.csproj...
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimEditorHost\VimEditorHost.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\CleanVsix\CleanVsix.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\CleanVsix\CleanVsix.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimEditorHost\VimEditorHost.csproj.nuget.g.targets.
  Restore completed in 532.76 ms for C:\jaredpar\VsVim\Src\VimEditorHost\VimEditorHost.csproj.
  Restore completed in 532.76 ms for C:\jaredpar\VsVim\Src\CleanVsix\CleanVsix.csproj.
  Restoring packages for C:\jaredpar\VsVim\Src\VsSpecific\Vs2012\Vs2012.csproj...
  Restoring packages for C:\jaredpar\VsVim\Src\VsSpecific\Vs2013\Vs2013.csproj...
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimCore\VimCore.fsproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimCore\VimCore.fsproj.nuget.g.targets.
  Restore completed in 1.12 sec for C:\jaredpar\VsVim\Src\VimCore\VimCore.fsproj.
  Restoring packages for C:\jaredpar\VsVim\Src\VsSpecific\Vs2015\Vs2015.csproj...
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimWpf\VimWpf.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimWpf\VimWpf.csproj.nuget.g.targets.
  Restore completed in 1.14 sec for C:\jaredpar\VsVim\Src\VimWpf\VimWpf.csproj.
  Restoring packages for C:\jaredpar\VsVim\Src\VsSpecific\Vs2017\Vs2017.csproj...
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsInterfaces\VsInterfaces.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsInterfaces\VsInterfaces.csproj.nuget.g.targets.
  Restore completed in 863.59 ms for C:\jaredpar\VsVim\Src\VsInterfaces\VsInterfaces.csproj.
  Restoring packages for C:\jaredpar\VsVim\Src\VsVimShared\VsVimShared.csproj...
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimApp\VimApp.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimApp\VimApp.csproj.nuget.g.targets.
  Restore completed in 1.19 sec for C:\jaredpar\VsVim\Src\VimApp\VimApp.csproj.
  Restoring packages for C:\jaredpar\VsVim\Src\VsVim\VsVim.csproj...
  Installing xunit.core 2.3.1.
  Installing xunit.analyzers 0.7.0.
  Installing xunit.assert 2.3.1.
  Installing xunit.extensibility.core 2.3.1.
  Installing xunit 2.3.1.
  Installing xunit.extensibility.execution 2.3.1.
  Installing Moq 4.5.28.
  Installing Castle.Core 4.0.0-beta002.
  Installing Microsoft.ApplicationInsights 2.0.0.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVimShared\VsVimShared.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2015\Vs2015.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2012\Vs2012.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2013\Vs2013.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVimShared\VsVimShared.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2017\Vs2017.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2012\Vs2012.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2015\Vs2015.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2013\Vs2013.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\Vs2017\Vs2017.csproj.nuget.g.targets.
  Restore completed in 783.16 ms for C:\jaredpar\VsVim\Src\VsVimShared\VsVimShared.csproj.
  Restore completed in 835.78 ms for C:\jaredpar\VsVim\Src\VsSpecific\Vs2015\Vs2015.csproj.
  Restoring packages for C:\jaredpar\VsVim\Test\VimWpfTest\VimWpfTest.csproj...
  Restoring packages for C:\jaredpar\VsVim\Test\VimCoreTest\VimCoreTest.csproj...
  Restore completed in 1.37 sec for C:\jaredpar\VsVim\Src\VsSpecific\Vs2013\Vs2013.csproj.
  Restore completed in 817.92 ms for C:\jaredpar\VsVim\Src\VsSpecific\Vs2017\Vs2017.csproj.
  Restoring packages for C:\jaredpar\VsVim\Test\VsVimSharedTest\VsVimSharedTest.csproj...
  Restore completed in 1.37 sec for C:\jaredpar\VsVim\Src\VsSpecific\Vs2012\Vs2012.csproj.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVim\VsVim.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVim\VsVim.csproj.nuget.g.targets.
  Restore completed in 806.02 ms for C:\jaredpar\VsVim\Src\VsVim\VsVim.csproj.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimTestUtils\VimTestUtils.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimTestUtils\VimTestUtils.csproj.nuget.g.targets.
  Restore completed in 2.12 sec for C:\jaredpar\VsVim\Src\VimTestUtils\VimTestUtils.csproj.
  Installing xunit.runner.visualstudio 2.3.1.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimCoreTest\VimCoreTest.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVimSharedTest\VsVimSharedTest.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VsVimSharedTest\VsVimSharedTest.csproj.nuget.g.targets.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimCoreTest\VimCoreTest.csproj.nuget.g.targets.
  Restore completed in 598.34 ms for C:\jaredpar\VsVim\Test\VimCoreTest\VimCoreTest.csproj.
  Restore completed in 596.53 ms for C:\jaredpar\VsVim\Test\VsVimSharedTest\VsVimSharedTest.csproj.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimWpfTest\VimWpfTest.csproj.nuget.g.props.
  Generating MSBuild file C:\jaredpar\VsVim\Binaries\obj\VimWpfTest\VimWpfTest.csproj.nuget.g.targets.
  Restore completed in 618.94 ms for C:\jaredpar\VsVim\Test\VimWpfTest\VimWpfTest.csproj.

C:\jaredpar\VsVim>msbuild /v:m /m VsVim.sln
Microsoft (R) Build Engine version 15.7.177.53362 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  CleanVsix -> C:\jaredpar\VsVim\Binaries\Debug\CleanVsix\net461\CleanVsix.exe
  VimEditorHost -> C:\jaredpar\VsVim\Binaries\Debug\VimEditorHost\net461\Vim.EditorHost.dll
  VimCore -> C:\jaredpar\VsVim\Binaries\Debug\VimCore\net45\Vim.Core.dll
  VimWpf -> C:\jaredpar\VsVim\Binaries\Debug\VimWpf\net45\Vim.UI.Wpf.dll
  VsInterfaces -> C:\jaredpar\VsVim\Binaries\Debug\VsInterfaces\net45\Vim.VisualStudio.Interfaces.dll
Mock\MockVimHost.cs(19,57): warning CS0067: The event 'MockVimHost._beforeSave' is never used [C:\jaredpar\VsVim\Src\Vi
mTestUtils\VimTestUtils.csproj]
  VimTestUtils -> C:\jaredpar\VsVim\Binaries\Debug\VimTestUtils\net461\Vim.UnitTest.Utils.dll
  VimApp -> C:\jaredpar\VsVim\Binaries\Debug\VimApp\net461\VimApp.exe
  VimWpfTest -> C:\jaredpar\VsVim\Binaries\Debug\VimWpfTest\net461\Vim.UI.Wpf.UnitTest.dll
  VimCoreTest -> C:\jaredpar\VsVim\Binaries\Debug\VimCoreTest\net461\Vim.Core.UnitTest.dll
  VsVimShared -> C:\jaredpar\VsVim\Binaries\Debug\VsVimShared\net45\Vim.VisualStudio.Shared.dll
  Vs2013 -> C:\jaredpar\VsVim\Binaries\Debug\Vs2013\net45\Vim.VisualStudio.Vs2013.dll
  Vs2012 -> C:\jaredpar\VsVim\Binaries\Debug\Vs2012\net45\Vim.VisualStudio.Vs2012.dll
  Vs2017 -> C:\jaredpar\VsVim\Binaries\Debug\Vs2017\net46\Vim.VisualStudio.Vs2017.dll
  VsVimSharedTest -> C:\jaredpar\VsVim\Binaries\Debug\VsVimSharedTest\net461\Vim.VisualStudio.Shared.UnitTest.dll
  Vs2015 -> C:\jaredpar\VsVim\Binaries\Debug\Vs2015\net45\Vim.VisualStudio.Vs2015.dll
  VsVim -> C:\jaredpar\VsVim\Binaries\Debug\VsVim\net45\VsVim.dll
  VsVim -> C:\jaredpar\VsVim\Binaries\Debug\VsVim\net45\VsVim.vsix
  Setting up Visual Studio for debugging extensions. This one-time operation may take a minute or more.

C:\jaredpar\VsVim>
````

**Comment by jaredpar** [comment]
@KevinRansom those are the exact steps I'm doing. 

Here are the various binary logs for the cases:

1. [15.7.1](https://vsvim.blob.core.windows.net/logs/vsvim-15.7.1.binlog)
1. [15.6.2](https://vsvim.blob.core.windows.net/logs/vsvim-15.6.2.binlog)

> so do you explicit add 4.4.0 as a package reference somewhere?

No. There is no use of ValueTuple in any of the project files.

**Comment by jainaashish** [comment]
@jaredpar If this is specific to F# target change, then can we move it to their repo?

**Comment by jaredpar** [comment]
> If this is specific to F# target change, then can we move it to their repo?

Don't think that is confirmed at this point, just suspected. At this point there is a visible difference between restoring a project in 15.6 and 15.7 (that causes build errors). Until it's confirmed that it's F# I think we should keep it here.

**Comment by nguerrera** [comment]
The 15.6.2 binlog isn't finding any F# targets and the only instance of ValueTuple in "Find in Files" is in a tmp_proj where the ReferencePath to 4.4.0 got persisted. It's still unclear how 4.4.0 was chosen by 15.6.2. I suspect some things are missing from .binlog somehow or not rendering correctly in the viewer. cc @KirillOsenkov

**Comment by nguerrera** [comment]
Same thing in the 15.7 binlog. On my machine, I got a repro using 15.8 dogfood and a better binlog.

**Comment by KevinRansom** [comment]
Okay now I see it.

**Comment by jaredpar** [comment]
Some updates. This repository has a Directory.Build.props file with the following entry:

``` xml
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.2.3" ExcludeAssets="all" Condition="'$(MSBuildProjectExtension)' != '.fsproj'"/>
  </ItemGroup>  
```

This is done as a partial work around for #6367. If I change the file to be the following then the errors go away:

``` xml
  <ItemGroup>
    <PackageReference Include="FSharp.Core" Version="4.2.3" ExcludeAssets="all" Condition="'$(MSBuildProjectExtension)' != '.fsproj'"/>
    <PackageReference Include="System.ValueTuple" Version="4.3.1" ExcludeAssets="all" />
  </ItemGroup>  
```

**Comment by KirillOsenkov** [comment]
@nguerrera if you feel like there's anything wrong with binlog or viewer, please ping me, attach .binlog and explain what's wrong. Thanks! Or file a bug at https://github.com/KirillOsenkov/MSBuildStructuredLog/issues

**Comment by jaredpar** [comment]
Update: the work around I described in my earlier comment about excluding assets from System.ValueTuple is not universally effective. It fails in [AppVeyor runs](https://ci.appveyor.com/project/jaredpar/vsvim/build/1.0.756). 

```
NU1605: Detected package downgrade: FSharp.Core from 4.3.4 to 4.2.3. Reference the package directly from the project to select a different version. 
 VimApp (>= 1.0.0) -> Vim.Core (>= 1.0.0) -> FSharp.Core (>= 4.3.4) 
 VimApp (>= 1.0.0) -> FSharp.Core (>= 4.2.3)
```

The exact [same SHA](https://github.com/jaredpar/VsVim/commit/11593e5e141894e42c74b4477a602ea632d4113b) works just fine on my local machine. Verifief that AppVeyor and my machine are using same MSBuild here: 15.7.177.53362.

At this point I'm pretty much stuck. If I make changes to enable local builds I break my ability to verify in AppVeyor.

**Comment by nguerrera** [comment]
Appveyor.yml and log output looks like it's using nuget.exe (and not msbuild /t:restore). What version?

Some of the behavior differences here look like they depend on whether that CollectPackageReferences target in F# ran or not. And I think at one point command line restores didn't run CollectPackageReferences.

**Comment by jaredpar** [comment]
> Appveyor.yml and log output looks like it's using nuget.exe (and not msbuild /t:restore).

Just noticed that as well. I can't figure out what version. Trying to move it to use msbuild based restore. 

Whatever version though it has the bug outlined in  #6367.

**Comment by jaredpar** [comment]
Looks like the NuGet version is  4.3.0.4406 on AppVeyor. I'm going to ask them to push to a new version.

**Comment by nkolev92** [comment]
It's been a while since we've investigated this issue.
Based on the links here, I think the original problem here is likely by the fsharp targets.

The related problem in #6367 is pretty likely https://github.com/NuGet/Home/issues/9864, which we're hoping to fix soon.
