### ISSUE TITLE
Fix NuGet.exe to support longfilenames on Windows 10

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#6937]
See some context in #3324 

This issue is meant to cover NuGet.exe scenarios with long file paths.

The following changes would be required in NuGet.exe to fix this:
a.	Setting longPathAware to true in the win32 manifest
b.	Programmatic setting of UseLegacyPathHandling and UseLongPath to false in beginning of main() (to avoid needing nuget.exe.config, so we keep the single file distribution of NuGet.exe)

Note: In current versions of Windows 10, the user will also need to change group policy to "enable win32 long paths". A version shipping later this year, is planning to enable that setting by default -- but that may be delayed?

If the user is not using Windows 10, Net Framework 4.6.2 or later, or does not have the group policy set appropriately, we plan on having a good error experience.

For more details on these steps, see this blog post: https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

Our plan is to address this in the next version of NuGet.exe -- 4.8 -- We have the basic work done already, but need to work on the "good error experience" mentioned above.

**Comment by nkolev92** [comment]
@zhili1208 
Can this be closed now?
