### ISSUE TITLE
NuGet pack append prerelease suffix to version

### ISSUE THREAD

**Issue by spankr** [NuGet/Home#694]
Currently, our team stores the version number within the _AssemblyInfo.cs._ All our info is in there so we just pack off the .csproj. What we'd like to do is have our CI build publish a prerelease package for testing/evaluation. (1.0.0-build2 or 1.2.0-nightly, for examples). Right now CI runs the _pack_ with a hard-configured **-Version 1.0.0-build2** for that but we have to change the CI build command each time the _AssemblyInfo.cs_ is updated.

We would like to have the _pack_ able to dynamically pull the version number from the _AssemblyInfo.cs_ but allow an optionally injected suffix for the prerelease designation. 

_(...or a link to where we can find documentation on how to do this. I wasn't able to find anything on my own.)_

**Comment by yishaigalatzer** [comment]
That's a nice idea. Note that we will not take versions from `AssemblyInfo.cs` but perhaps from the assembly version itself.

I'm moving this out beyond Update I, but if you want this coming in faster you are more than welcome to submit a PR.

Note that we are going to move nuget.core and command line into GitHub in the coming days/weeks, you might want to wait on that if you are interested in submitting a PR.

**Comment by spankr** [comment]
That answered my next two questions too! I'll keep an eye out for the migration and see if I can submit a PR.

**Comment by petterek** [comment]
I like this idea. +1

**Comment by yishaigalatzer** [comment]
@spankr the command line now builds from https://github.com/nuget/nuget.packagemanagement repo, start with the home repo for build scripts

**Comment by spankr** [comment]
Woot! I'll start taking a look.

**Comment by spankr** [comment]
Hrm, I seem to have issues trying to get the dev environment up and running. I've been following the [instructions](http://docs.nuget.org/Contribute/Setting-up-the-NuGet-Development-Environment) and most of it seems to be building from my Powershell (v5) prompt.

I am seeing a lot of _Build succeeded._ and passing tests so that's good. I just seem to be having difficulties finding the ProjectManagement namespace

```
IDE\NuGetAndEnvDTEProjectCache.cs(8,13): error CS0234: The type or namespace name 'ProjectManagement' does not exist in the namespace 'NuGet' (are you missing an assembly reference?)
C:\Users\Spankr\Source\Repos\NuGet.VisualStudioExtension\src\PackageManagement.VisualStudio\PackageManagement.VisualStudio.csproj]
... snip snip...
9 Warning(s)
148 Error(s)

Time Elapsed 00:00:02.10
Build failed
At C:\Users\Spankr\Source\Repos\Home\build-nuget.ps1:129 char:9
```

I looked through the issues on [Home](https://github.com/NuGet/Home/issues) to see if anyone else had something similar and [this issue](https://github.com/NuGet/Home/issues/787) was the closest I could find. That issue mentions using [NuGet.Client](https://github.com/NuGet/NuGet.Client) (comment of @yishaigalatzer) so I may give those steps a try.

**Comment by yishaigalatzer** [comment]
Yes. Use nuget.client, we finally got good builds there.

Make sure you have aspnet 5 beta7 installed and deleted as well as vs SDK and win 10 toolset

Sent from my Windows Phone

**Comment by spankr** [comment]
Will do. Thanks for the help, Yishai!

**Comment by spankr** [comment]
Okay, Nuget.Client\build.ps1 ran with no errors yesterday on my Win10 system so I'll use that. :+1: 
_(I seem to have 18 build errors from my Win7 about not finding packages\NuGet.MsBuild.Integration.)_

To clarify, I want to use [Nuget.Client](https://github.com/NuGet/NuGet.Client) for investigating the change and not the [Home](https://github.com/NuGet/Home) + [PackageManagement](https://github.com/NuGet/NuGet.PackageManagement) environment?

Either way, I think this should be enough to dig around for now.

**Comment by yishaigalatzer** [comment]
Yes, some code might still be in nuget2

Sent from my Windows Phone

**Comment by yishaigalatzer** [comment]
You need win10 tools on your win7 machine

Sent from my Windows Phone

---

From: Yishai Galatzermailto:yigalatz@microsoft.com
Sent: ‎10/‎13/‎2015 8:27 AM
To: NuGet/Homemailto:reply@reply.github.com; NuGet/Homemailto:Home@noreply.github.com
Subject: RE: [Home] NuGet pack append prerelease suffix to version (#694)

Yes, some code might still be in nuget2

Sent from my Windows Phone

**Comment by logankp** [comment]
I've started looking into this one, I can send a PR whenever.

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/NuGet.Client/pull/144/files

**Comment by feiling** [comment]
PR merged.

**Comment by FransBouma** [comment]
http://docs.nuget.org/consume/command-line-reference doesn't contain info about this, the nuget.exe usage dump does.

**Comment by harikmenon** [comment]
Thanks for letting us know. I will assign this to myself and mark this issue as a doc

**Comment by karann-msft** [comment]
docs updated https://github.com/NuGet/NuGetDocs/pull/694

**Comment by BrainCrumbz** [comment]
Hello all

referencing current docs:

> suffix 	Appends a suffix to the internally generated version number, typically used for appending build or other pre-release identifiers. For example, using -suffix nightly will create a package with a version number like 1.2.3.45-nightly.

if one does that, is the generated version number compatible with SemVer 1 (and hence with Nuget 3.5) ?

Currently our *.nuspec* file has `<version>1.1.0</version>`, then command in PowerShell script has `& "nuget" pack -suffix $env:APPVEYOR_BUILD_NUMBER` where e.g. `$env:APPVEYOR_BUILD_NUMBER = "123"`.

That produces a package with version `OurPackageName.1.1.0-123`, with a *dash* separating original number from added suffix. Which in turn makes NuGet complain in a number of places, eventually preventing VS 2015 Package Manager to list that package when installed (from package manager console).

How do you use `-suffix` option and still manage to have a compatible version number, something like `1.1.0.123` ?

Thanks

**Comment by logankp** [comment]
@BrainCrumbz SemVer 1 spec allows this. I'm not sure why NuGet is complaining, but a version number of 1.1.0-123 is perfectly valid.

Per SemVer specs:
```
A pre-release version number MAY be denoted by appending an arbitrary string immediately following the patch version and a dash. The string MUST be comprised of only alphanumerics plus dash [0-9A-Za-z-]. Pre-release versions satisfy but have a lower precedence than the associated normal version. Precedence SHOULD be determined by lexicographic ASCII sort order. For instance: 1.0.0-alpha1 < 1.0.0-beta1 < 1.0.0-beta2 < 1.0.0-rc1 < 1.0.0.
```

**Comment by BrainCrumbz** [comment]
Thanks for quick reply @logankp . My "Not compatible SemVer 1" might be a wrong statement, if that's the case, but still Nuget has issues with that naming scheme, as found when googling around. As of now, a workaround seems to be the following:

1. add some build number in *.nuspec* file: `<version>1.1.0.0</version>`
1. start suffix with some text, not with a number: `-suffix "dev-$env:APPVEYOR_BUILD_NUMBER"`

**Comment by kraigb** [comment]
@BrainCrumbz Thanks for the workaround, and I'll make a small note in the suffix docs to say that the suffix should start with a letter. The nuget 4.0 RC4 CLI indicates this as a warning, in fact:

WARNING: Issue: Package version not supported on legacy clients.
WARNING: Description: The package version '1.0.0-123' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. This message can be ignored if the package is not intended for older clients.
WARNING: Solution: Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter.

I also did some experiments with the VS2017 Package Manager Console and UI (which are v4 for NuGet) and they're both happy with numeric suffixes. (For example, the Package Manager Console will show it both with "Find-Package -IncludePrerelease -AllVersions" and with "Get-Package". Install-Package with -version 1.0.0-123 also works. Numeric suffixes appear fine in the version drop-down of the UI too.)

**Comment by kraigb** [comment]
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#pack now has the note under the suffix argument.
