### ISSUE TITLE
NuGet verify command could have better default

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#6942]
If you run `nuget verify x.nupkg` you get the error message:

> Verification type not supported. Please use only one of the following supported types: -All, -Signatures

It would be convenient if the NuGet verify command defaulted to the `-All` type

**Comment by PatoBeltran** [comment]
Closing this as it doesn't seem like a clear path to go to. We don't know if once we add more validations `-All` will be a valid scenario that makes sense. Therefore it doesn't seem reasonable to add this as a default now.
