### ISSUE TITLE
"Package Integrity check failed." should have package ID in message (and error code)

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#6944]
When VS tries to install a package with an invalid signature, it reports the next error in the ErrorList

![image](https://user-images.githubusercontent.com/14916339/40194592-d896240a-59bf-11e8-94c0-63eb7c85641d.png)

The error should include:

- PackageID 
- Error Code NU3008 with a link to the docs
- Affected Project

**Comment by rrelyea** [comment]
This got into Dev. Is it already in Release-4.8.0-rtm or not?  I forget.

**Comment by mishra14** [comment]
This fix is not in `release-4.8.0-rtm` branch
