### ISSUE TITLE
dotnet core failed t add package below proxy

### ISSUE THREAD

**Issue by imben1109** [NuGet/Home#6947]
## Details about Problem

NuGet product used ( dotnet.exe):

NuGet version (2.1.4):

dotnet.exe --version (2.1.4):

## Detailed repro steps so we can see the same problem

1. dotnet add package Newtonsoft.Json

error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   Response status code does not indicate success: 407 (Proxy Authentication Required).

**Comment by imben1109** [comment]
Sorry. I fixed the issue myself as I found a way to add configuration of proxy info. 
I added **NuGet.Config** to **~/.config/NuGet**

```
<config>
	<add key="http_proxy" value="XXXX" />
	<add key="http_proxy.user" value="XXXXX" />
	<add key="http_proxy.password" value="XXXXXX" />
</config>
```

**Comment by mishra14** [comment]
@imben1109 thanks for letting us know that you have resolved your problem! :)

**Comment by surfmuggle** [comment]
For anyone wondering where this file is stored. 
Pasting `%appdata%\NuGet\` into windows explorer should open the path to the file `NuGet.Config`
