### ISSUE TITLE
Test.Utility publishing stopped

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#6948]
As of 4.8.x, the Test.Utility package is no longer published to MyGet.  The NuGet server team uses this for testing.

The change occurred on or around April 12th.  The first build to not drop the Test.Utility package was for [this commit](https://github.com/NuGet/NuGet.Client/commit/5aaced85e5f9f150dc32faa6b45640803f22a23e).

**Comment by mishra14** [comment]
@nkolev92 can you please take a look to see if this was caused by the commit above?

**Comment by nkolev92** [comment]
Yeah, that's when it started happening. 
The root cause is that the props from xunit set a property which made the project unpackable. 

We need to add that manually. 

The PR is out.

**Comment by dtivel** [comment]
The Test.Utility package is again being dropped as part of the build, but I still don't see the package getting published automatically.

**Comment by nkolev92** [comment]
@dtivel 

I couldn't find any automatic publishing of Test.Utility in our pipeline. 

https://dotnet.myget.org/feed/nuget-build/package/nuget/Test.Utility
contains only 8 published versions of the test utility. 

I'm not sure how/when those nupkgs where published on myget. 

This is our scripts for publishing and it has always excluded nupkgs with test in their name  
https://github.com/NuGet/NuGet.Client/blob/dev/scripts/cibuild/PublishArtifactsFromVsts.ps1

**Comment by dtivel** [comment]
Sounds good.  Thanks, @nkolev92!
