### ISSUE TITLE
NuGet.Client repo fails to build when building source-build for Windows

### ISSUE THREAD

**Issue by safern** [NuGet/Home#6950]
When building [source-build](https://github.com/dotnet/source-build) nuget-client repo fails with following error: 

```
E:\repos\source-build\packages\pdbgit\3.0.41\tools\PdbGit.targets(9,5): error MSB4062: The "PdbGit" task could not be loaded from the assembly E:\repos\source-build\packages\pdbgit\3.0.41\tools\PdbGit.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

Steps to repro:

1. Clone [source-build repo](https://github.com/dotnet/source-build)
2. Checkout release/2.1 branch
3. Run: `build.cmd /p:RootRepo=nuget-client`

Build will fail, and if you open `nuget-client.log` file you can see the error.

cc: @mishra14 @weshaggard

**Comment by nkolev92** [comment]
@safern 
Which version of VS/MSbuild are you using?

**Comment by safern** [comment]
I'm using latest version of VS 2017 and therefore using the MSBuild that comes with it. This failure is when building on source-build though, which uses the dotnetcli built in msbuild:

https://github.com/dotnet/source-build/blob/master/repos/nuget-client.proj#L28

**Comment by nkolev92** [comment]
@safern 

I see some weirdness here. 
I was not able to repro it on 1 machine. 
It fails with some weird errors on others. 

Where is the DotnetToolCommand set?
Which version of dotnet is supposed to be used here?

I don't see the log after building. 
In which directory is the log supposed to be?
Can you attach your log?

**Comment by nkolev92** [comment]
@safern 
Any further issues here?

I'm closing this as stale for now.
