### ISSUE TITLE
Get 500 internal server error from internal local feed when select package source to all

### ISSUE THREAD

**Issue by karthikanandan** [NuGet/Home#6952]
Hi Team,
 
We are configured our own NuGet feed for our company using NuGet Server Assembly.
 
**Issue**: (which is only occurred in **Visual Studio 2017**):

We have configured three feedlink

Link 1 (Internal local Feed url) : \\sfil01\data\NuGetFeed

Link 2 (nuget.org url) : https://api.nuget.org/v3/index.json

Link  3 (Public Feed url) : http://testdoamin.com/nuget_aspnet/nuget/getpackages/aspnet
 
**Case 1**:

If I Choose  **ALL**  in package source and tried to install my internal local nuget feed link, but which is not installed and returns "500 internal server error" from my public Feed link.

For your reference, please find the image:
 
![image](https://user-images.githubusercontent.com/37404382/40306725-62785066-5d1d-11e8-981c-368cb3210701.png)

 
**Case 2**:

If I select my **Public Feed link**  in  package source and tried to install which is working fine.
 
**Case 3** : 

If I select **Internal local feed url** in package source and tried to install which is working fine.
 
So the issue came only when I select  **All** and tried to install the local nuget feed url, then returns 500 internal server error from public feed link.
 
 
In case it helps my Nuget.config is as follows: 
  
<?xml version="1.0" encoding="utf-8"?> 
<configuration> 
  <packageSources> 
    <add key="privatefeedlink" value="\\sfil01\data\NuGetFeed" /> 
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" /> 
    <add key="publicfeedlink" value="http://testdoamin.com/nuget_aspnet/nuget/getpackages/aspnet" /> 
  </packageSources> 
</configuration>
 
So can you please provide the solution for that issue?
 
Thanks in advance.

**Comment by zhili1208** [comment]
Did you try to install PSolve.PropertyChanged.Fody 1.5.2.0 from internal local feed url?

**Comment by karthikanandan** [comment]
Hi Zhili,

Thanks for your quick response. 

yes, whenever I select all from package source, and tried to install any of the internal package feeds, we returned 500 internal server.

Can you please provide the solution for that?

Thanks in advance.

**Comment by karthikanandan** [comment]
Hi Zhili,

Can you please update on this?

Thanks in advance.

**Comment by PatoBeltran** [comment]
Hey @karthikanandan, so sorry that we missed this issue. Is this still a problem? If so, would it be possible for you to provide a repro project or some repro steps so I can investigate on this issue? Thanks! And again, sorry that it took us so long to respond.
