### ISSUE TITLE
Nuget Update fails when using package.[ProjectName].config

### ISSUE THREAD

**Issue by DavidHaitch** [NuGet/Home#6963]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `Nuget.exe`

NuGet version (x.x.x.xxx): `4.6.2.5055`

OS version (i.e. win10 v1607 (14393.321)): `Win10  v1703 (15063.1088)`

Worked before? If so, with which NuGet version: `Unknown if worked before.`

## Detailed repro steps so we can see the same problem

1. run Nuget.exe on a packages file named in the form of "packages.ProjectName.config"

2. Nuget reports that no packages config was found.

This behavior can be simply tested with the solution attached, with this command:
`    .\nuget.exe update .\NugetTest\packages.NugetTest.config -verbosity detailed`

### Verbose Logs
```
NuGet Version: 4.5.1.4879
No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe.
NuGet.CommandLine.CommandLineException: No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe.
   at NuGet.CommandLine.UpdateCommand.<ExecuteCommandAsync>d__43.MoveNext()
```

### Sample Project

[NugetTest.zip](https://github.com/NuGet/Home/files/2023905/NugetTest.zip)

**Comment by DavidHaitch** [comment]
I believe this is down to ``GetPackagesConfigPath(string path)`` in ``UpdateCommand.cs``.
It checks if the path ends with ``Constants.PackageReferenceFile``, which is set to ``"packages.config"``, and returns null if it doesn't.
Other Nuget tasks work with package files named "packages.PROJECTNAME.config", so I believe this behavior is a bug.

**Comment by nkolev92** [comment]
@DavidHaitch 
We'd be happy to take a PR for this.

**Comment by DavidHaitch** [comment]
Thanks, I'll put one together today!
