### ISSUE TITLE
New nuget lock files should include information about dependencies

### ISSUE THREAD

**Issue by nathansoz** [NuGet/Home#6965]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
All

dotnet.exe --version (if appropriate):
N/A

VS version (if appropriate):
N/A

OS version (i.e. win10 v1607 (14393.321)):
N/A

Worked before? If so, with which NuGet version:
N/A

## Feature Suggestion

The new spec for nuget lock files should include dependency information (both Yarn and Npm's lock files do this). This information is useful for people examining the lock file statically to report on vulnerable components and what top level components brought in a particular component. I'm creating this issue as a result of a conversation with @anangaur

**Comment by anangaur** [comment]
Related lock file issue: https://github.com/nuget/home/issues/5602

**Comment by rrelyea** [comment]
@anangaur  - this should be closed? or is there more to do?

**Comment by anangaur** [comment]
This can be closed.
