### ISSUE TITLE
Question: Is it allowed to specify more than one PackageType ("dependency" + user defined) for search filtering purposes?

### ISSUE THREAD

**Issue by Apollo3zehn** [NuGet/Home#6966]
My applications allows to install extensions that are hosted in a NuGet repository. Because this repository contains not only extensions for my application, but also completely different ones (which is the case for e.g. NuGet.org), I would like to specify a second PackageType to filter the [PackageSearchResource](https://github.com/NuGet/NuGet.Client/blob/4eed67e7e159796ae486d2cca406b283e23b6ac8/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResource.cs) search results. 

From point of view of my application everything works. But I cannot install these extensions anymore in Visual Studio or using the CLI because of more than one package type. I get something like "The paket 'NugetPackageTypeTest 1.0.0' has multiple package types. This is not supported."

I would also like to avoid to enforce specific package name prefixes or certain tags. I think the package type would be the natural choice. But since this does not work, my question is, is there another option for the above described scenario?

**Comment by zhili1208** [comment]
this scenario is not supported, Could you split your package into two packages? one contains all the staff for extension, and another contains everything for dependency use. and let extension package depends on the dependency package.

**Comment by Apollo3zehn** [comment]
Thanks for your suggestions. Although I don't like the idea to have twice as many projects for such a simple requirement, I tried to simply duplicate the packages (call `dotnet pack` twice) such that they only differ in `PackageId` and `PackageType`. But unfortunately it turned out that a query string like 
https://api-v2v3search-0.nuget.org/query?q=&skip=0&take=15&prerelease=true&packageTypeFilter=OneDasExtension&semVerLevel=2.0.0 does not work on Nuget.org or myget.org, i.e. the results are not filtered by `packageTypeFilter`.

I also tried to modify the `q` parameter itself (according to [this](https://github.com/NuGet/Home/wiki/Search-by-Package-Type-and-Query-Language-Surfacing) document), to get a query like:
https://api-v2v3search-0.nuget.org/query?q=PackageType%3AOneDasExtension&skip=0&take=15&prerelease=true&semVerLevel=2.0.0, which is equal to `PackageType:OneDasExtension` but this also failed. 

_Info: Right now there is no package of type `OneDasExtension `hosted on Nuget.org. Therefore this query is not good for testing. But if you want to filter by e.g. `DotnetTool`, try this query: https://www.nuget.org/packages?q=PackageType%3ADotnetTool or this one https://api-v2v3search-0.nuget.org/query?q=PackageType%3ADotnetTool&skip=0&take=20&prerelease=true&semVerLevel=2.0.0. Both versions do not give correct results. **I think the search API described [here](https://github.com/NuGet/Home/wiki/Search-by-Package-Type-and-Query-Language-Surfacing) is not (fully) implemented. Is that correct?**_

Because none of these queries worked, I switched back to use a special tag instead. This works much better but also not perfectly. If I execute the following query (`id:HDF tags:OneDAS`) against Nuget.org, I get a single result:
https://api-v2v3search-0.nuget.org/query?q=id%3AOneDas%20tags%3A+HDF&skip=0&take=20&prerelease=true&semVerLevel=2.0.0
It seems that this is an AND operation, **which is what I want**. 

But if I instead execute this query against myget.org, I get too many results:
https://www.myget.org/F/onedas/api/v3/query?q=id%3AOneDas%20tags%3A+HDF&skip=0&take=20&prerelease=true&semVerLevel=2.0.0
Here it seems that myget applies an OR operation: either the package has `id: HDF` **or** the package contains a tag named OneDAS.

Do you know where this discrepancy comes from or is there another possibility to make searching for certain packages more precise / reliable, either using PackageType, Tags or something else?

**Comment by zhili1208** [comment]
Issue moved to [NuGet/NuGetGallery #5999](https://github.com/NuGet/NuGetGallery/issues/5999) via [**ZenHub**](https://www.zenhub.com/)
