### ISSUE TITLE
Packaging multitargeting framework project results in one target framework package

### ISSUE THREAD

**Issue by xander199** [NuGet/Home#6977]
## Details about Problem
I have created .NET standard 2.0 class library project in my application. However I also need this library to be available in .NET Framework 4.7.1 project. To make it possible, I changed target framework to target frameworks of netstandard2.0;net471 to have this build two ways. Build/Rebuild itself in VS works fine - two folders for different frameworks are beeing generated. However, when I try to create nuget package using NuGet.Build.Packaging, it creates only one framework folder in the package. I was trying the version of 0.2.3 and latest release 0.2.5-pr160.1 of NuGet.Build.Packaging. What should I do to get package for both frameworks?

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe 4.5.1.4879
VS UI 15.7.2
Package Manager Console 4.7.0.5212
.NET Framework 4.7.2
OS version: Win 10 v1803

## Detailed repro steps so we can see the same problem

1. Create .NetStandard 2.0 class library project

2. Modify .csproj adding net471 to target framework (remember to rename TargetFramework to TargetFrameworks)

3. Rebuild package

4. Create Nuget package with Nuget.Build.Packaging

Regards,
Ariel Zakrzewski

**Comment by nkolev92** [comment]
I am not able to repro this issue @IIUJ-ArielZakrzewski 
The package is created just fine with 2 different frameworks. 

Can you clarify what do you mean by 
> Create Nuget package with Nuget.Build.Packaging

What do you do here?

**Comment by rohit21agrawal** [comment]
@nkolev92 NuGet.Build.Packaging is the nugetizer package.

CC: @kzu

**Comment by pbalaga** [comment]
Does it mean that Nugetizer has no support for multitargeting currently?

Below is what I'm experiencing:
1. `nuget pack MyProject.nuspec` is able to pack output for multiple target frameworks (given that the `files` section is configured correctly).
2. Running `msbuild "/t:Clean;Restore;Rebuild" /p:PackOnBuild=true /p:NuspecFile=MyProject.nuspec` fails with:

> nuget.build.packaging\0.2.5-pr160.1\build\NuGet.Build.Packaging.targets(377,3): error : Path cannot be the empty string or all whitespace

3. Running  `msbuild "/t:Clean;Restore;Rebuild" /p:PackOnBuild=true` succeeds but the resulting `.nupkg` contains only files for one target platform.

I'm not sure if this is to be treated as a bug or "not yet supported" scenario.

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

**Comment by nkolev92** [comment]
Closing per @kzu's comment.
