### ISSUE TITLE
Cannot pack, NuGet cannot find DLL

### ISSUE THREAD

**Issue by dkalkwarf** [NuGet/Home#6979]
I followed the procedure in the link below.  

**https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework**

The DLL was built, but I get the following error:

**Unable to find "AppLogger.dll".  Make sure the project has been built.""**

NuGet.exe version:  4.6.2.5055
Visual Studio Community 2017 version: 4.7.03056
.Net version: 4.6.1
OS version: Windows 10.0.17134

VERBOSE LOG:

NuGet Version: 4.6.2.5055
Attempting to build package from 'AppLogger.csproj'.
MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
NuGet.CommandLine.CommandLineException: Unable to find 'AppLogger.dll'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)

**Comment by rohit21agrawal** [comment]
@dkalkwarf can you paste your csproj here? Is this a netcore project or a full framework project? nuget pack, by default, looks for debug bits, unless otherwise specified.

**Comment by dkalkwarf** [comment]
[AppLogger.zip](https://github.com/NuGet/Home/files/2052035/AppLogger.zip)


Please find attached a zip file containing my csproj file.  This is a full framework project.

**Comment by rohit21agrawal** [comment]
the csproj seems fine. can you also paste the full project here?

**Comment by dkalkwarf** [comment]
Attached is a zip file of the solution.  I also included a file (error.txt) containing the command line and error message.


Thanks for your help.


[NuGetTest.zip](https://github.com/NuGet/Home/files/2056254/NuGetTest.zip)

**Comment by dkalkwarf** [comment]
Previously, I was trying to package my project with 'nuget pack.'  I have now experimented with other command lines.

'nuget pack AppLogger.csproj' gives me the same error.

'nuget pack AppLogger.nuspec' gives me a different error: 

Values cannot be null or any empty string
Parameter name: value

After some investigation, it seemed that NuGet was looking for a version.  Therefore, I tried 'nuget pack AppLogger.nuspec -Version 1.0.0.0'  This yielded yet another error message:

WARNING: Issue: Assembly outside the lib folder
WARNING: Description: The assembly 'bin\Debug\AppLogger.dll' is not inside the 'lib' folder and hence it won't be added....

The message continues to tell me to move it into the 'lib' folder.

I don't get any of this.  

First, the article describing the process is very simple.  Why doesn't following those directions work?

Further investigation seems to indicate I need a lib folder.  Why?  Isn't NuGet supposed to integrate with Visual Studio.  If so, then why doesn't it understand that Visual Studio does not natively create those folders.  Why doesn't it know that the DLL is in bin\Release|Debug?

The article describing how to create a NuGet package seems very wrong.

**Comment by rohit21agrawal** [comment]
here is what i get when i try and pack your provided project using nuget.exe 4.6.2:

```
E:\temp\NuGetTest\AppLogger> E:\DevTools\nuget462\nuget.exe pack .\AppLogger.csproj -Build
Attempting to build package from 'AppLogger.csproj'.
MSBuild auto-detection: using msbuild version '15.8.60.28450' from 'C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin'.
Building project 'E:\temp\NuGetTest\AppLogger\AppLogger.csproj' for target framework '.NETFramework,Version=v4.6.1'.
Microsoft (R) Build Engine version 15.8.60.28450 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/4/2018 12:16:48 PM.
Project "E:\temp\NuGetTest\AppLogger\AppLogger.csproj" on node 1 (default targets).
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input
 files.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:1701,
  1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Refere
  nce Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Microsoft.CSharp.dll" /reference:"C:\Program Files (x86)\Referenc
  e Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assembli
  es\Microsoft\Framework\.NETFramework\v4.6.1\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Micr
  osoft\Framework\.NETFramework\v4.6.1\System.dll" /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\AppLogger.d
  ll /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Team Tools\Static Analysis Tools\\Rule Set
  s\MinimumRecommendedRules.ruleset" /subsystemversion:6.00 /target:library /utf8output Logger.cs Properties\AssemblyInfo.c
  s "C:\Users\ragrawal\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\
  MSBuild\15.0\bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "obj\Debug\AppLogger.dll" to "bin\Debug\AppLogger.dll".
  AppLogger -> E:\temp\NuGetTest\AppLogger\bin\Debug\AppLogger.dll
  Copying file from "obj\Debug\AppLogger.pdb" to "bin\Debug\AppLogger.pdb".
Done Building Project "E:\temp\NuGetTest\AppLogger\AppLogger.csproj" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.70
Packing files from 'E:\temp\NuGetTest\AppLogger\bin\Debug'.
Using 'AppLogger.nuspec' for metadata.
Successfully created package 'E:\temp\NuGetTest\AppLogger\AppLogger.1.0.0.nupkg'.
```

I deleted the bin and obj folder and passed the ```-Build``` flag to the commandline to make sure that the project gets built before packing. You can choose to skip ```-Build``` and build the project manually first before running pack without the build flag.

**Comment by dkalkwarf** [comment]
It didn't work.  Here is a dump of the error message.

------------------------------------------------------------------

`C:\projects\NuGetTest\AppLogger>nuget pack .\applogger.csproj -Build
Attempting to build package from 'applogger.csproj'.
MSBuild auto-detection: using msbuild version '15.7.179.6572' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
Building project 'C:\Projects\NuGetTest\AppLogger\applogger.csproj' for target framework '.NETFramework,Version=v4.6.1'.
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 6/4/2018 7:13:23 PM.
Project "C:\Projects\NuGetTest\AppLogger\applogger.csproj" on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(780,5): error : The OutputPath property is not set for project 'applogger.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='HPD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Projects\NuGetTest\AppLogger\applogger.csproj]
Done Building Project "C:\Projects\NuGetTest\AppLogger\applogger.csproj" (default targets) -- FAILED.

Build FAILED.

"C:\Projects\NuGetTest\AppLogger\applogger.csproj" (default target) (1) ->
(_CheckForInvalidConfigurationAndPlatform target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Microsoft.Common.CurrentVersion.targets(780,5): error : The OutputPath property is not set for project 'applogger.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='HPD'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Projects\NuGetTest\AppLogger\applogger.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.17

Failed to build 'applogger.csproj'.
`
------------------------------------------------------------------

Note that my version of MSBuild is slightly different, 15.7.X.X.

The message complains that the OutputPath property is missing.  It is not missing from my csproj file, it is set for Debug as well as Release.  My platform target is Any CPU.  I do not know what HPD is.

**Comment by rohit21agrawal** [comment]
can you just run msbuild on your project to see what happens? this is most likely a msbuild issue, and not a nuget one. msbuild issues can be filed at https://github.com/microsoft/msbuild

**Comment by nkolev92** [comment]
Closing this as stale. 

Please comment again if you're still facing this problem.
