### ISSUE TITLE
Show helpful error message when package restore triggered by another action fails.

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#698]
When using package manager UI to perform an action on a package a package restore will be run if necessary. If there were any errors during the restore they will be shown in the restore bar, but it might not be evident that the package restore errors prevent any actions on the packages. To be consistent with PMC an error message should pop-up explaining this.

**Comment by yishaigalatzer** [comment]
Since it is too late for localizing, moving out to Update I
