### ISSUE TITLE
Can I use source control path as reposityPath? If yes any example

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6980]
_From @chilakamarthi on May 28, 2018 7:20_

I would like to use Source control path as repositoryPath instead of local path. Can I do that? Any sample code?

_Copied from original issue: dotnet/cli#9356_

**Comment by livarcocc** [comment]
In which context are you asking this question? Sorry, I am not sure what these refer to.

**Comment by livarcocc** [comment]
_From @chilakamarthi on May 29, 2018 10:29_

I added NuGet.Config to my solution and set it like below:
`<configuration>
  <config>
    <add key="repositoryPath" value="../../../../Test/Test/Packages" />
  </config>
</configuration>`

Here repository path is relative path to solution file location. can I make it source control path instead of local path is the Q.

**Comment by nkolev92** [comment]
@chilakamarthi
I'm not sure I understand what you mean by 
> source control path

Can you please elaborate?

**Comment by chilakamarthi** [comment]
I am using TFS as my SD. So instead of giving local if I can give sd path something like $/CASE/TestAutomation/Dev/ABCD.Automation.All/Packages, If it is this way, I dont need to give local path, Visual Studio can take it from mapped local path. Hope I am clear

**Comment by nkolev92** [comment]
NuGet works with full paths, or UNC shares. 

I don't think what you're articulating would work, but you can for sure figure out the relative path out of it.

**Comment by nkolev92** [comment]
Closing this as stale.
