### ISSUE TITLE
Nuget CLI does not support dotnet-tool

### ISSUE THREAD

**Issue by tebeco** [NuGet/Home#6982]
## Details about Problem

Until this  #6981 #6978  #6761 is fixed ... i have to use `nuget install` instead of `dotnet whatever` to install nuget ... so this is begining to be not funny anymore

NuGet product used :
* NuGet.exe
* VS UI
* dotnet.exe

NuGet version : `NuGet Version: 4.6.0.4971`

dotnet.exe --version : `2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]`

VS version : `Vs2017 15.7.2`

OS version :
```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.15063 N/A Build 15063
```

Worked before? Never probably ?

## Detailed repro steps so we can see the same problem

```
SET BUILD_PACKAGES=BuildPackages
SET FAKE_CLI="%BUILD_PACKAGES%/fake.exe"

    nuget install fake-cli^
        -OutputDirectory ./%BUILD_PACKAGES% ^
        -Source https://www.myget.org/F/fake-vsts/api/v3/index.json ^
        -Prerelease ^
        -ExcludeVersion
```

OutPut :
```
"Installing 'fake-cli' dotnet tool"
Feeds used:
  https://www.myget.org/F/fake-vsts/api/v3/index.json

Installing package 'fake-cli' to './BuildPackages'.
  CACHE https://www.myget.org/F/fake-vsts/api/v3/registration1/fake-cli/index.json


Attempting to gather dependency information for package 'fake-cli.5.0.0-rc017.241' with respect to project './BuildPackages', targeting 'Any,Version=v0.0'
Gathering dependency information took 39.63 ms
Attempting to resolve dependencies for package 'fake-cli.5.0.0-rc017.241' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'fake-cli.5.0.0-rc017.241'
Resolved actions to install package 'fake-cli.5.0.0-rc017.241'
Retrieving package 'fake-cli 5.0.0-rc017.241' from 'https://www.myget.org/F/fake-vsts/api/v3/index.json'.
WARNING: Install failed. Rolling back...
Executing nuget actions took 89.01 ms
Error NU5000: Package 'fake-cli 5.0.0-rc017.241' has a package type 'DotnetTool' that is not supported by project './BuildPackages'.
```

soooo, any solution knowing that as of today `dotnet` does not authenticate on the proxy (error 407) ?

**Comment by nkolev92** [comment]
This is by design. 
NuGet alone does not know how to do the setup for dotnet tool. 
it's primarily a dotnet.exe feature that NuGet helps enable. 
 
Some details [here](https://github.com/NuGet/Home/wiki/Global-Tools---NuGet-Implementation).

Please refer to http://aka.ms/globaltools for any dotnet tool related information.

Related to some of the issue linked above:
https://github.com/NuGet/Home/issues/6486

**Comment by tebeco** [comment]
that why i said

> Until this #6981 #6978 #6761 is fixed

dotnet restore/install is broken behind a proxy as you already know
soooo how do you deal with it when you are in a team with multiple developper and a CI ?

before `Milestone 4.8` of course

**Comment by tebeco** [comment]
http://aka.ms/globaltools seems broken btw

**Comment by nkolev92** [comment]
@tebeco 
I'm merely referring to this issue. 

It's very unlikely that NuGet.exe supports global tools. 
It just doesn't have enough information to setup the shims. It also can't execute those tools. 

Someone will come back to you to help investigate the other issues.

**Comment by tebeco** [comment]
well i use it as a workaround of `dotnet` for proxy
i really do not care about “execution” but it makes me sad that
* HTTP GET
* download 
* unzip in a folder
* and i will do the `dotnet run foobar`

basic stuff for nuget client right ?
checking the log is also sad since it managed to `retrieve it`

**Comment by nkolev92** [comment]
@tebeco 
dotnet.exe does more than just unzip the package though.

**Comment by tebeco** [comment]
i would love to have a full tchat / take / whatever about that long existing issue of `dotnet restore` not working with NTLM proxy then
How could we setup a Skype call so i would share my feedback and failed attempt since the last two year ?
i probably posted issues on repos like Omnisharp / Dotnet / this one since `dnx` probably beta 7 ...
and i still got 407 unless i use password explicitly which is a no go

**Comment by nkolev92** [comment]
//cc @anangaur
