### ISSUE TITLE
Show/hide package restore bar when package restore is triggered from PMC

### ISSUE THREAD

**Issue by AndriySvyryd** [NuGet/Home#699]
When package restore is triggered from PMC and the restore bar was visible then even if the restore is successful the restore bar will remain visible.
When package restore is triggered from PMC and the restore bar was not visible and the restore fails the restore bar will still be not visible.

**Comment by zhili1208** [comment]
@AndriySvyryd Can you provide repro step, I can't repro it. thanks

**Comment by AndriySvyryd** [comment]
First scenario:
1. Create a project
2. Install the xunit package
3. Close VS
4. Delete the 'packages' folder
5. Open the project
6. Open PMC, the restore bar should be visible
7. Call 'Install-Package Moq' from PMC
8. Both Moq and xunit are in the  'packages' folder and the restore bar is still visible.

Second scenario:
1. Create a project
2. Install the xunit package
3. Open PMC
4. Modify packages.config by changing 'xunit' to 'invalid' to make the package restore fail
5. Delete the 'packages' folder
6. The restore bar should not visible
7. Call 'Install-Package Moq' from PMC
8. An error will be shown in the console, but the restore bar will still not be visible
