### ISSUE TITLE
dotnet pack does not create project.assets.json when no referenced nuget packages

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#6990]
_From @mairaw on May 31, 2018 19:4_

@hansenfreddy commented on [Wed May 30 2018](https://github.com/dotnet/docs/issues/5680)

# Problem

Running dotnet pack will give these error messages if no referenced nuget packages:

`C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018: The "GetProjectReferencesFromAssetsFileTask" task failed unexpectedly.
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018: System.InvalidOperationException: The assets file produced by restore does not exist. Try restoring the project again. The expected location of the assets file is C:\...
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at NuGet.Build.Tasks.Pack.GetProjectReferencesFromAssetsFileTask.Execute()
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\Program Files\dotnet\sdk\2.1.201\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(284,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext()`

Seems to apply to only .net framework projects.
dotnet version: 2.1.201

## Reproduce
1. Create new class lib .net framework (I used 4.5 in my repro)
2. Run `dotnet pack`

## Workaround
Add a random nuget package (no need to reference it in code) with the new PackageReference for csproj (enable via Visual Studio Option or modify csproj manually)

_Copied from original issue: dotnet/cli#9385_

**Comment by livarcocc** [comment]
@rohit21agrawal moving to nuget for you to take a first look. If this is something we need to change in the CLI/SDK, just re-activate the CLI issue.

**Comment by nkolev92** [comment]
@hansenfreddy
If I understand this correctly, you do not have any packages in your project?

Then it's likely that NuGet is discovering your project as a non-NuGet project.
Does running dotnet restore on that project do anything? Can you post the logs?

dotnet pack on a csproj would only work if the project is PR? 
@rohit21agrawal can you confirm?

**Comment by mishra14** [comment]
Closing this due to lack of customer response.

**Comment by jonathanmendez** [comment]
I am seeing this same error in a very similar setup.
I have a .net framework project.
I'm referencing the Nuget.Build.Tasks.Pack nuget using packages.config.
I was first seeing this invoking msbuild or building within VisualStudio (GeneratePackageOnBuild is set to true), but I can also reproduce it using invoking dotnet.

Running dotnet restore on the project does nothing:
"Nothing to do. None of the projects specified contain packages to restore."

If i convert the reference to Nuget.Build.Tasks.Pack to PackageReference, then it succeeds (i.e. this reference by itself is enough to trigger the workaround).

**Comment by Havlat82** [comment]
Hi, I was stepping through [quick start tutorial at docs.microsoft.com](https://docs.microsoft.com/cs-cz/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli) and when I tried to pack it, I got very same error. I tried to pack net standard 2.0 class library.

**Comment by dca00** [comment]
Reopen. The same problem here.
