### ISSUE TITLE
Nuget pack fails with a 0 error code

### ISSUE THREAD

**Issue by StephenMolloy** [NuGet/Home#6992]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.6.2.5055

dotnet.exe --version (if appropriate): n/a

VS version (if appropriate): n/a

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2016, Version 1607 (14393.2248)

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Setup a nuget project with a nuspec file that declares a dependency on another package, with 'version="[]"'.

2. 'nuget pack' the project

Expected: Error message about invalid version string AND non-zero exit code.
Actual: Error message about invalid version string, but the exit code is 0.

**Comment by nkolev92** [comment]
Not sure when this got fixed, but it's not a problem in the latest NuGet. 

Closing now.

```
C:\Users\Nikolche\Documents\Code\NuGet\NuGet.Client [dev ≡ +1 ~0 -0 !]> .\artifacts\VS15\NuGet.exe pack .\Package.nuspec
Attempting to build package from 'Package.nuspec'.
An error occured while trying to parse the value '[ ]' of property 'version' in the manifest file.
  '[ ]' is not a valid version string.
  Parameter name: value
C:\Users\Nikolche\Documents\Code\NuGet\NuGet.Client [dev ≡ +1 ~0 -0 !]> $LASTEXITCODE
1
```
