### ISSUE TITLE
Installed packages tab shouldn't paginate the list

### ISSUE THREAD

**Issue by tomeverin** [NuGet/Home#6995]
NuGet VS UI
NuGet version 4.6.0
VS version 15.7.1
OS version Windows 10 1803 build 17134.48

## Detailed repro steps so we can see the same problem

1. Open any project with a reasonable number of NuGet packages installed (e.g. 40-50)

2. Open the NuGet package manager UI and select the "installed" tab

3. Scroll to the bottom of the list of installed NuGet packages. Note that the list is page loaded and several scrolls are required to load the entire list.

Preferred behaviour would be for the list of installed packages to be fully loaded from the start so that scrolling through the list is more efficient.

**Comment by jainaashish** [comment]
This make sense for installed tab.
