### ISSUE TITLE
Include ProjectReference in the nuget package lib and do not set it as a dependency in the nuspec

### ISSUE THREAD

**Issue by bgavrilMS** [NuGet/Home#6998]
This is related to #3891

1. ProjA has a project reference to ProjB
2. I implemented the workaround in #3891, so ProjB.dll now appears in the nupkg lib folder
3. Pack ProjA

Actual:  ProjB is still listed as a <dependency> in the nuspec
Expected: ProjB should not be listed as a dependency, as this will require me to publish a nuget package for it 

Note: Setting PrivateAsset="All" on the ProjectReference element will cause ProjB to not be listed as a dependency, however this is causing build failures because ProjB needs to be made available for build etc.

**Comment by rohit21agrawal** [comment]
did you set PrivateAssets=all on the project reference?
make sure you run a restore before packing when you modify the project reference,

**Comment by mishra14** [comment]
@bgavrilMS Please let us know if you are still blocked by this.

**Comment by rohit21agrawal** [comment]
closing since @bgavrilMS hasn't responded for over a month. Please feel free to reactivate if there are still any issues.

**Comment by bgavrilMS** [comment]
Oops, sorry guys, this slipped off my radar. At this point we decided to do a manual packaging by laying out the contents + nuspec etc. There are too many problems with /t:pack, including the fact that the /t:pack  target will actually rebuild ProbB. This is a problem because it will override ProjB.dll which I have signed.
