### ISSUE TITLE
Nuget restore ingores repositoryPath setting in nuget.config if Directory.Build.props file exists

### ISSUE THREAD

**Issue by evil-shrike** [NuGet/Home#7003]
Given a project 
```
Apps\
Apps\Server_Legacy\
Apps\Server_Legacy\.nuget\
Apps\Server_Legacy\.nuget\NuGet.Config 
Apps\Server_Legacy\MyProject.sln
packages_legacy\
```

Inside NuGet.Config  I have `repositoryPath` specified:
```
	<config>
		<add key="repositoryPath" value="../../../../packages_legacy" />		
	</config>
```

I run `nuget.exe restore MyProject.sln -Source https://company.org/api/nuget/nuget-virtual -NoCache`
and have all packages restored into packages_legacy folder.

Have been working for year without problems.

Now I've  added a `Directory.Build.props` file at root folder (besides packages_legacy folder) and nuget restore doesn't work any more. I restores packages w/o errors but doesn't put them into repositoryPath folder.

NuGet: 4.6.2.5055

Probably it's because Directory.Build.props contains `<PackageReference >`

If I put empty `Directory.Build.props` besides sln file then `nuget restore` starts working as before.

**Comment by jainaashish** [comment]
I don't think that should make any difference. Do you have anything specific to NuGet in your `directory.build.props` file? Can you provide repro solution?

**Comment by nkolev92** [comment]
I think the answer is this part:
```
Probably it's because Directory.Build.props contains <PackageReference >

```

NuGet will treat this project as Package Reference if there's a package reference element in it. 
PackageReference projects don't use repository path.

**Comment by jainaashish** [comment]
ohh yes, I didn't see that line :)

**Comment by evil-shrike** [comment]
My `Directory.Build.props` is:
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup>
    <PackageReference Include="SourceLink.Create.CommandLine" Version="2.8.1" PrivateAssets="All" /> 
  </ItemGroup>
  <PropertyGroup>
    <SourceLinkServerType>BitBucketServer</SourceLinkServerType>
  </PropertyGroup>
</Project>
```
But it's not for the project that I'm currently restoring packages in. 

To make it more clear. I have a git repo with several csprj/sln
```
Apps\
Apps\Server\ (here .net core project)
Apps\Server\NuGet.Config (config with `globalPackagesFolder`)
Apps\Server\MyProjectNetCore.sln
Apps\Server_Legacy\ (here .net fw project)
Apps\Server_Legacy\.nuget\NuGet.Config  (config with `repositoryPath`)
Apps\Server_Legacy\MyProject.sln
packages\ (packages for dotnet core)
packages_legacy\ (package for old .net/msbuild/nuget)
```
Currently I found a workaround - to put empty `Directory.Build.props` besides legacy sln `Apps\Server_Legacy\MyProject.sln`:
```
<?xml version="1.0" encoding="utf-8"?>
<Project>
</Project>
```
But it's a bit weird.

**Comment by nkolev92** [comment]
@evil-shrike 

Not sure how directory.build.props is getting imported. 
That'd be something that msbuild would be able to take a look at.
It is my understanding that it will only search upwards. 

https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#search-scope 

You can run `msbuild /pp:pp.txt` to see all the imports and understand where it is coming from.

**Comment by evil-shrike** [comment]
Well, yeah directory.build.props with PackageReference is imported for msbuild building a legacy project. I realize that. But I can't see a reason why that should remove repositoryPath setting that was set in nuget.config.

**Comment by nkolev92** [comment]
@evil-shrike 

It shouldn't remove it. 

That project itself is treated as PackageReference. 
PackageReference uses the globalpackagesfolder property and not the repository path property. 
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section

**Comment by mishra14** [comment]
@evil-shrike Please let us know if you are still blocked by this.

**Comment by jbastnagelcwp** [comment]
I'm having the same issue.

My NuGet.Config:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
<config>
  <add key="repositoryPath" value="$/../packages" />
</config>
<packageSources>
  <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
</packageSources>
</configuration>
`
Directory.Build.props:
`<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <PackageReference Include="SlnGen">
      <Version>2.0.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>
`

I haven't found a work-around to this issue.

**Comment by jbastnagelcwp** [comment]
@mishra14 I'm not sure how/if I can re-open this issue.

**Comment by jainaashish** [comment]
As it has been multiple times in this thread, and repeating again, `repositoryPath` will be ignored if your project is `PackageReference` type so this is not an issue, rather by design.

Now, when you need to make sure that the project whcih wants to use `repositoryPath`, should not import `Directory.build.props` file. You can either do that by having an empty directory.build.props file at the project level or make sure there is no directory.build.props from project level to root.

**Comment by jbastnagelcwp** [comment]
My project is not a PackageReference type.

**Comment by jainaashish** [comment]
yes but importing this directory.build.props file making it as `PackageReference`
