### ISSUE TITLE
NuGet.VisualStudio.IVsPackageInstaller - calling on a project with no package references always uses packages.config, even if the default is set to PackageReference

### ISSUE THREAD

**Issue by ticktickMOF** [NuGet/Home#7005]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS Extensability API

NuGet version (x.x.x.xxx): 4.6.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.6.6

OS version (i.e. win10 v1607 (14393.321)):  Win 7 SP 1

Worked before? If so, with which NuGet version: don't know, probably not.

## Detailed repro steps so we can see the same problem
1. Make a basic VS extension which uses IVsPackageInstaller to add a package reference
```C#
var componentModel = (IComponentModel)Microsoft.VisualStudio.Shell.ServiceProvider.GlobalProvider.GetService(typeof(SComponentModel));
IVsPackageInstaller installer = componentModel.GetService<IVsPackageInstaller>();
installer.InstallPackage(null, project, NugetPackageId, (string)null, false);
```
2. Install extension.
3. Set default package management format to PackageReference in Tools -> Options -> NuGet Package Manager
4. Create a new .net Framework project.
5. Invoke VS extension's command created in step 1 to add a new package reference.
6. Observe package reference is added using packages.config

**Comment by jainaashish** [comment]
Thanks for the issue. We recently made it work through NuGet TemplateWizard apis but still not supported through IVS apis. We'll work on bridging this gap as well. Meantime, you can use `RestoreProjectStyle` property to set `PackageReference` before trying to install a package, which will make sure that NuGet uses `PackageReference` to manage dependencies.

Set below code in project csproj:
`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`

**Comment by ticktickMOF** [comment]
Is there a way to add this programatically so that it actually affects NuGet?  I tried setting it via IVsBuildPropertyStorage and via the Microsoft.Build.Construction.ProjectRootElement and neither affected NuGet without reloading the project.  It seems like the NuGetProject is already cached and I can't figure out how to reset it.

**Comment by jainaashish** [comment]
yes you're right NuGet project is cached, there is no way you can set this property without reloading the project.
