### ISSUE TITLE
UAP project target framework support for RTM

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#702]
Currently UAP projects that are not using project.json return win81 as the project target framework.

Does this need to be changed for RTM?

The fix for this is to check the TPM and update the framework to UAP (a small code change) as we did for the UAP RC release.

**Comment by yishaigalatzer** [comment]
Chatted with Navit and KevinPI and decided not to support this scenario. Developers will have to port over from RC builds to project.json
