### ISSUE TITLE
[Test Failure][Localization][FRA][RUS] PM UI can’t be opened successfully

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7021]
## Details about Problem
NuGet version : NuGet Client release-4.8.0-preview3-4.8.0.5266
VS version : D15.8 27811.00
OS version : Windows 10 16299.RS3_Release_svc_escrow.180502-1908.

Worked before? If so, with which NuGet version:
NuGet Client Dev 4.8.0.5234

## Detailed repro steps so we can see the same problem
1.Create a C#->Windows Desktop ->Class Library (.NET Framework) project.
2.Right click the project and open ‘Manage NuGet Packages’.

## Expected: 
‘Manage NuGet Packages’ should be opened successfully.
 
## Actual: 
‘Manage NuGet Packages’ can’t be opened successfully as below screenshot.
![123](https://user-images.githubusercontent.com/40230425/41340759-a3e456fe-6ee7-11e8-8dbe-78f48bef95ed.png)

## Error Message:

Microsoft Visual Studio

La propriété Set 'System.Windows.Controls.ColumnDefinition.Width' a levé une exception.

OK   

## Notes:
1. The issue only repro FRA and RUS.
2. The issue can repro on other templates.
3. PMC can be opened successfully.

**Comment by jainaashish** [comment]
Did you restarted the VS and tried again?
Did you try to repair the VS and checked if that resolved this issue?

**Comment by v-longmin** [comment]
@jainaashish The issue still repros after I tried to restarting and repairing the VS.

**Comment by mishra14** [comment]
@v-longmin I tested the latest build with FRA - 

![image](https://user-images.githubusercontent.com/10507120/41495011-7407c0b4-70d2-11e8-954a-d47eb3866395.png)


Please try the latest dev15.8 build to see if the problem persists. Also, please try on a different machine to confirm.

**Comment by v-longmin** [comment]
@jainaashish The issue has fixed on D15.8 27187.00 + NuGet Client Dev 4.8.0.5288, closed it, thanks.
