### ISSUE TITLE
dotnet restore fails if NuGet package feed lacks <d:version> node in one of the entries

### ISSUE THREAD

**Issue by robertas-kerpys** [NuGet/Home#7026]
NuGet Restore will fail with `System.NullReferenceException` if a feed about NuGet package contains an entry without `<d:version>` node in the <m:properties> node of the entry. 

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): 4.6.1.5019

dotnet.exe --version: 2.1.103

VS version (if appropriate): 15.6.4

OS version: win10 10.0.15063

Worked before? If so, with which NuGet version:
Started failing when entry with missing `<d:version>` appeared in NuGet feed.

## Detailed repro steps so we can see the same problem

NuGet Restore will fail with System.NullReferenceException if a feed about NuGet package contains an entry without `<d:version>` node in the <m:properties> node of the entry. 

1. Have a remote feed with one of the entries missing `<d:version>` node. E.g. an entry of Foo package version v1 does not contain `<d:version>` in the feed.

2. Try to add some other version (Foo v2 which has `<d:version>2.0</d:version>` set) of the package from the feed the test project.

Fails to add the package to the test project. 

## Other suggested things
The issue is with [BuildModel ](https://github.com/NuGet/NuGet.Client/blob/76391da0b108dad7993e461eafcff8e857c6c2d3/src/NuGet.Core/NuGet.Protocol/RemoteRepositories/RemoteV2FindPackageByIdResource.cs#L450) method of `RemoteV2FindPackageByIdResource.cs`. BuildModel method does not account for missing version xml node and throws an exception. However the consumer of BuildModel method ([FindPackagesByIdAsyncCore](https://github.com/NuGet/NuGet.Client/blob/76391da0b108dad7993e461eafcff8e857c6c2d3/src/NuGet.Core/NuGet.Protocol/RemoteRepositories/RemoteV2FindPackageByIdResource.cs#L395)) is expecting null values and filters those.

I would suggest to change BuildModel to return null if version xml node was not found in an entry.

### Verbose Logs
```
NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information about 'Swashbuckle.AspNetCore' from remote source 'https://localsource/nuget/Default/FindPackagesById()?id='Swashbuckle.AspNetCore''. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.RemoteV2FindPackageByIdResource.BuildModel(String id, XElement element)
   at NuGet.Protocol.RemoteV2FindPackageByIdResource.<>c__DisplayClass22_0.<FindPackagesByIdAsyncCore>b__2(XElement x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at NuGet.Protocol.RemoteV2FindPackageByIdResource.<>c__DisplayClass22_2.<<FindPackagesByIdAsyncCore>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

### Sample Project
One could modify the unit test source xml to reproduce the issue.
Add to NuGet.Client\test\NuGet.Core.Tests\NuGet.Protocol.Tests\compiler\resources\XunitFindPackagesById.xml an entry with `<d:version>` node missing. E.g. place the below entry before `</feed>` node:
```
  <entry>
    <id>https://www.nuget.org/api/v2/Packages(Id='xunit',Version='2.1.0--rc1')</id>
    <category term="NuGetGallery.OData.V2FeedPackage" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
    <link rel="edit" href="https://www.nuget.org/api/v2/Packages(Id='xunit',Version='2.1.0--rc1')" />
    <link rel="self" href="https://www.nuget.org/api/v2/Packages(Id='xunit',Version='2.1.0--rc1')" />
    <title type="text">xunit</title>
    <updated>2015-10-09T16:10:26Z</updated>
    <author>
      <name>James Newkirk, Brad Wilson</name>
    </author>
    <content type="application/zip" src="https://www.nuget.org/api/v2/package/xunit/2.1.0--rc1" />
    <m:properties>
      <d:Id>xunit</d:Id>
      <!--<d:Version>2.1.0</d:Version> Version node is missing. -->
      <d:NormalizedVersion>2.1.0--rc1</d:NormalizedVersion>
      <d:Authors>James Newkirk, Brad Wilson</d:Authors>
      <d:Copyright m:null="true" />
      <d:Created m:type="Edm.DateTime">2015-09-27T18:29:32.007</d:Created>
      <d:Dependencies>xunit.core:[2.1.0--rc1]:|xunit.assert:[2.1.0--rc1]:</d:Dependencies>
      <d:Description>
        xUnit.net is a developer testing framework, built to support Test Driven Development, with a design goal of extreme simplicity and alignment with framework features.

        Installing this package installs xunit.core and xunit.assert.
      </d:Description>
      <d:DownloadCount m:type="Edm.Int32">1592239</d:DownloadCount>
      <d:GalleryDetailsUrl>https://www.nuget.org/packages/xunit/2.1.0--rc1</d:GalleryDetailsUrl>
      <d:IconUrl>https://raw.githubusercontent.com/xunit/media/master/logo-512-transparent.png</d:IconUrl>
      <d:IsLatestVersion m:type="Edm.Boolean">true</d:IsLatestVersion>
      <d:IsAbsoluteLatestVersion m:type="Edm.Boolean">false</d:IsAbsoluteLatestVersion>
      <d:IsPrerelease m:type="Edm.Boolean">false</d:IsPrerelease>
      <d:Language>en-US</d:Language>
      <d:LastUpdated m:type="Edm.DateTime">2015-10-09T16:10:26.483</d:LastUpdated>
      <d:Published m:type="Edm.DateTime">2015-09-27T18:29:32.007</d:Published>
      <d:PackageHash>u/7VQSOSXa7kSG4iK6Lcn7RqKZQ3hk7cnyMNVMpXHSP0RI5VQEtc44hvkG3LyWOVsx1dhUDD3rPAHAxyOUDQJw==</d:PackageHash>
      <d:PackageHashAlgorithm>SHA512</d:PackageHashAlgorithm>
      <d:PackageSize m:type="Edm.Int64">2986</d:PackageSize>
      <d:ProjectUrl>https://github.com/xunit/xunit</d:ProjectUrl>
      <d:ReportAbuseUrl>https://www.nuget.org/package/ReportAbuse/xunit/2.1.0--rc1</d:ReportAbuseUrl>
      <d:ReleaseNotes m:null="true" />
      <d:RequireLicenseAcceptance m:type="Edm.Boolean">false</d:RequireLicenseAcceptance>
      <d:Summary m:null="true" />
      <d:Tags m:null="true" />
      <d:Title>xUnit.net</d:Title>
      <d:VersionDownloadCount m:type="Edm.Int32">212201</d:VersionDownloadCount>
      <d:MinClientVersion>2.8.5</d:MinClientVersion>
      <d:LastEdited m:null="true" />
      <d:LicenseUrl>https://raw.githubusercontent.com/xunit/xunit/master/license.txt</d:LicenseUrl>
      <d:LicenseNames m:null="true" />
      <d:LicenseReportUrl m:null="true" />
    </m:properties>
  </entry>
```
Run unit tests. 
**Expected result**: all tests passing
**Actual result**: `GetAllVersionsAsync_ReturnsAllVersionsAsync` fails with `System.NullReferenceException`:
```
NuGet.Protocol.Core.Types.FatalProtocolException : Failed to retrieve information about 'xunit' from remote source 'http://6c3dcd8c-5200-44e0-80f6-e10f860900f8/FindPackagesById()?id='xunit'&semVerLevel=2.0.0'.
---- System.NullReferenceException : Object reference not set to an instance of an object.
   at NuGet.Protocol.RemoteV2FindPackageByIdResource.<FindPackagesByIdAsyncCore>d__23.MoveNext() in C:\github\NuGet.Client\src\NuGet.Core\NuGet.Protocol\RemoteRepositories\RemoteV2FindPackageByIdResource.cs:line 443
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by jainaashish** [comment]
This doesn't seem like a issue with NuGet client, instead a issue /w feed itself. What is the real scenario to have packages on feed without version? 

I feel throwing exception in this case, is the right thing to do so that it can be fixed at feed otherwise all these issues will go without noticed and more trouble at later point in time. Like what will happen if somebody specifically asked for that version which is missing `<d:version>`...
