### ISSUE TITLE
Improve error/warning code logging in nuget

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#7028]
In our current design, the default error handling path doesn't handle exception with error code properly.
every time we want to show some error/warning code, we have to catch the specified exception and call some logMessage service to show the error/warning code properly.

Ideally, we should automatically show error/warning code if the exception have one. We have tons of exception like PackagingException, ProtocolException don't show error/warning code.

**Comment by nkolev92** [comment]
Fixed afaik. Closing.
