### ISSUE TITLE
Error message of project-package compatbility may need to be improved for multiple projects in a solution

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#703]
Repro steps:
1. create a solution with a .net 4.5 project and a dnx project
2. start package manager for solution dialog, install package only supporting dnx project 

Expected: error saying the package cannot be installed to one of the projects with error ...

Actual: only the following error is shown, which does not indicate which project it failed to install. (Installing succeeded with the other project).

Severity    Code    Description Project File    Line
Error       Could not install package 'OnlyDNXCore 6.0.8'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.            0

**Comment by zhili1208** [comment]
it still repro in 3.3

**Comment by rrelyea** [comment]
@emgarten says this is fixed for project.json restore. Likely still an issue with packages.config.

**Comment by rohit21agrawal** [comment]
i think we have covered this with our work with errors and warnings in nuget 4.x
