### ISSUE TITLE
Add support for static http hosting of package repositories to Nuget client

### ISSUE THREAD

**Issue by mungojam** [NuGet/Home#7031]
We are fairly restricted in our ability to host Nuget.Server, however we can easily set up static http hosting using GitHub pages internally. However NuGet seems to only support the two extremes of OData or a folder share (which is what we currently use).

Python and R both have support for static http hosting by parsing the directory index page that comes back and going into each folder as needed. It would be good if this could be supported by NuGet client, using the same hierarchical folder structure as for local folders.

**Comment by nkolev92** [comment]
NuGet also supports the V3 protocol in addition to local feeds and the V2 feed. 
The V3 feed is more performant. 

Unfortunately currently there aren't a lot of easy to setup servers to host a V3 feed. 

While I understand the pain, I think this should be solved by having more performant server alternative to NuGet.Server than making protocol changes in the client itself. 

//cc @rrelyea @skofman1 @loic-sharma

**Comment by loic-sharma** [comment]
What's preventing you from using NuGet.Server?

**Comment by mungojam** [comment]
It probably sounds rediculous but we can't easily get a web server set up without a lot of internal cost and headache. Hopefully that will improve as our cloud maturity increases but that won't happen for at least a year.

Having GitHub Enterprise with GitHub pages has suddenly opened up possibilities as long as it's statically hosted. I had just assumed till today that I'd be able to put our hierarchical folder nuget repo up there

**Comment by loic-sharma** [comment]
I see. There's an open-source community project, Sleet, that lets you create a statically hosted feed: https://github.com/emgarten/Sleet. Would this work for you?

/cc @emgarten

**Comment by mungojam** [comment]
Sleet works really well thanks! I reckon you should call it out on [your package hosting page](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview) as that is where I first looked before I raised this. It talks a lot about OData under the [server section](https://docs.microsoft.com/en-us/nuget/hosting-packages/nuget-server) which was what made me think static hosting couldn't work.

**Comment by loic-sharma** [comment]
Good suggestion! I opened an issue to document Sleet: https://github.com/NuGet/docs.microsoft.com-nuget/issues/937
