### ISSUE TITLE
NuGet.PackageManagement.dll in NuGet.PackageManagement.NetStandard 4.6.0 has invalid strong name

### ISSUE THREAD

**Issue by jherby2k** [NuGet/Home#7037]
## Details about Problem

I get the following error when using NuGet.PackageManagement.NetStandard with a full framework project. .NET core works fine for some reason.

> Could not load file or assembly 'NuGet.PackageManagement, Version=4.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)'

Running sn.exe -v NuGet.PackageManagement.dll results in

> Failed to verify assembly -- Strong name validation failed.

NuGet product used (NuGet.PackageManagement.NetStandard nuget package):

## Detailed repro steps so we can see the same problem

1. Check out https://github.com/jherby2k/AudioWorks.git

2. In AudioWorks\tests\AudioWorks.Api.Tests, run dotnet.exe test -c Release-Windows -f net471. Test will fail.

3. run dotnet.exe test -c Release-Windows -f netcoreapp2.1. Test will pass.

### Sample Project

https://github.com/jherby2k/AudioWorks.git

**Comment by rohit21agrawal** [comment]
The package https://www.nuget.org/packages/NuGet.PackageManagement.NetStandard/ is not owned by NuGet. Please contact the package author for any issues specific to the package.
