### ISSUE TITLE
Source parameter was not specified when pushing

### ISSUE THREAD

**Issue by msmolka** [NuGet/Home#7044]
## Details about Problem

NuGet product used NuGet.exe:

NuGet version (4.7.0.5148):

I'm trying to push both package and related symbols however when doing following command based on doc: https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages
`nuget push MyPackage.nupkg`

my command:
`NuGet.exe Push ../../.nuget/ZNetCS.AspNetCore.ResumingFileResults.2.1.1.nupkg`

I'm having error:
_Source parameter was not specified._

my files are named:
`ZNetCS.AspNetCore.ResumingFileResults.2.1.1.nupkg`
`ZNetCS.AspNetCore.ResumingFileResults.2.1.1.symbols.nupkg`

**Comment by nkolev92** [comment]
Do you have a default push source configured? 

This is the expect behavior otherwise as NuGet does not know where to push. 

https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

**Comment by msmolka** [comment]
@nkolev92 based on docs:
https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages
There is nothing about additional configuration. It says:

> You can also push both primary and symbol packages to both repositories at the same time using the following:
> cli
> nuget push MyPackage.nupkg

I'm using nuget.exe. 

On the link you provided I cannot find any section related to symbol source. I always thought that `nuget.config` is used to consume packages not for publish. In documentation there is nothing about `nuget.config` in the nuget.exe folder.

**Comment by nkolev92** [comment]
@msmolka 
In my above link, refer to defaultPushSource. 

That specifies the default push source. 

The symbol source push is disable due to https://github.com/NuGet/Home/issues/6113. 

@anangaur 
Did the new behavior get documented?

**Comment by msmolka** [comment]
@nkolev92 I've seen that, but because of Microsoft Docs I was hope there is a way to push both with one command.

**Comment by anangaur** [comment]
@msmolka We did document the new behavior of not auto pushing the .nupkg and .symbols.nupkg together. Looks like we can clean it up more to reflect this behavior.

---
![image](https://user-images.githubusercontent.com/14800916/42338678-7c9bea08-803f-11e8-9301-8ed87d508cfd.png)

**Comment by nkolev92** [comment]
@msmolka 
Does that answer your concern? 

Currently there is no way of doing it. 

We are working on a related feature, spec [here](https://github.com/NuGet/Home/wiki/NuGet-Package-Debugging-&-Symbols-Improvements)
https://github.com/NuGet/Home/issues/6104
