### ISSUE TITLE
DevelopmentDependency package nuspec should not include dependency groups

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#7049]
I have a .csproj that builds to a package with a couple properties set:

```xml
    <developmentDependency>true</developmentDependency>
    <IncludeBuildOutput>false</IncludeBuildOutput>
```

This is a build authoring package, which should apply to all projects without regard to the project's target framework. Yet the generated nuspec file retains this xml:

```xml
    <dependencies>
      <group targetFramework=".NETCoreApp1.0" />
      <group targetFramework=".NETFramework4.5" />
    </dependencies>
```

This effectively blocks the package from installing to certain projects based on target framework. 

I believe there is no way to suppress generation of these dependencies without completely taking over the nuspec file, which is a huge burden since otherwise I've already written all the msbuild authoring to help nuget to generate the nuspec file.

Please offer a way to control/suppress the target frameworks for a package.

**Comment by rohit21agrawal** [comment]
you can add ```<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>``` moving forward in 4.8.

**Comment by rohit21agrawal** [comment]
https://github.com/NuGet/NuGet.Client/pull/2237/files#diff-ae1f77c571bde930d7337bb1415f66f3R48
