### ISSUE TITLE
nuget.exe does not respect true/false parameter on disabledpackagesources

### ISSUE THREAD

**Issue by LogikBlitz** [NuGet/Home#705]
In the documentation at https://docs.nuget.org/consume/nuget-config-defaults
the substract for the config states that you can specify ```<disabledPackageSources>```

```XML
 <!-- Default Package Sources that are Disabled by Default -->
    <!-- They cannot be modified or deleted either but can be enabled/disabled by user -->
    <!-- The following section is similar to 'disabledPackageSources' section of NuGet.config schema -->
    <disabledPackageSources>
        <add key="nuget.org" value="true" />
    </disabledPackageSources>
```

The ```value="true"``` part of the entry has no effect.
One would expect the following
1. ``` <add key="nuget.org" value="true" />``` -> feed is disabled
1. ``` <add key="nuget.org" value="false" />``` -> feed is enabled

My testing shows that nuget.exe 2.8.5 and 2.8.3 ignore the value part and only defines a disabled source by only using the ```key```.
Thus any entry in disabled source are disabled regardless of the true/false bit.

Tested using ```using nuget.exe source -configfile PATH\TO\nuget.config```

Example config
```nuget.org``` disabled and ```Local``` should be enabled but both are **disabled** using above command
```
	<packageSources>
		<clear /> <!-- ensure only the sources defined below are used -->
		<add key="nuget.org" value="https://www.nuget.org/api/v2/"/>
		<add key="Local" value="http://OUR/OWN/FEED/Local"/>
	</packageSources>
	<disabledPackageSources>
		<add key="nuget.org" value="true"/>
		<add key="Local"  value="false"/>
	</disabledPackageSources>
```

OUTPUT ```nuget.exe source -configfile PATH\TO\nuget.config```

```
  1.  nuget.org [Disabled]
      https://www.nuget.org/api/v2/
  2.  Local [Disabled]
      http://OUR/OWN/FEED/Local
```

nb.
The documentation does not specify the meaning of the **true/false** parameter but my assumption is that it must be a on/off switch as is the case with other nuget.config parameters.
If that is not the case the documentation should be updated to reflect this and this issue be closed.

**Comment by yishaigalatzer** [comment]
Please update the docs
