### ISSUE TITLE
Leveraging NuGet.Versioning.SemanticVersion for semantic version bump

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#7055]
Hello,

I don't know if y'all have a Gitter? That would be better, probably for my question. However...

I'm looking at leveraging ``SemanticVersion`` for purposes of supporting the ``System.Reflection.AssemblyInformationalVersionAttribute`` and just wanted to posture a couple of questions along these lines.

1) Am I even in the correct forum for purposes of possibly leveraging [``SemanticVersion``](/NuGetArchive/NuGet.Versioning/blob/master/src/NuGet.Versioning/SemanticVersion.cs)? I would say possibly excepting for the fact that I found ``SemanticVersion`` code in a *NuGetArchive*.

1) What does the ``ToString`` incorporate? Does it support major, minor, patch, and ``label``? i.e. ``1.2.3-dev456``?

1) What sort of text can ``Metadata`` contain? Seems fairly open ended from what I could analyze from the ``SemanticVersion`` code, but I wanted to double check? i.e. ``1.2.3-dev456+someMetaData``

Thanks!

**Comment by mwpowellhtx** [comment]
A follow up question... Are the delimiters always as such? ``a.b.c.d-release+metadata``? That is, *dot* (``.``), *minus* (``-``) and *plus* (``+``)? Thanks!

**Comment by rohit21agrawal** [comment]
@mwpowellhtx I suggest you use [NuGetVersion](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs) which also supports Semantic versioning.

Rules on semver can be found here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/NuGetVersion.cs

**Comment by mwpowellhtx** [comment]
@rohit21agrawal Thanks, yes, I came to discover there was the ``NuGetVersion``. I'm not quite sure what you mean by *"rules"* however. There is source code, to be sure. But I don't see anything there that would lead me to consider anything a rule.

**Comment by rohit21agrawal** [comment]
my bad, wrong link: https://semver.org/ 

About delimiters in particular, https://semver.org/#spec-item-9 and https://semver.org/#spec-item-10

**Comment by mwpowellhtx** [comment]
@rohit21agrawal Spec items 9 and 10? If the links were supposed to go some where, they did not. I found the listed items under ``Semantic Versioning Specification (SemVer)``, however. Thanks!

**Comment by rohit21agrawal** [comment]
yeah, i am referring to point  point 9 and 10 under "Semantic Versioning Specification (SemVer)" basically. The links were generated from the website but aren't pointing to the right page.

**Comment by mwpowellhtx** [comment]
@rohit21agrawal Yes, they are a listed item, but not a heading, so I guess they do not show up as such accordingly.
