### ISSUE TITLE
[Test Failure] ‘Unable to get auto-refresh path’ warnings occur after transitive updating of package ‘Microsoft.Net.Http’

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7056]
## Details about Problem
NuGet version: NuGet Client release-4.8.0-preview3-4.8.0.5278
VS version: D15.8 27823.00
OS version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1. Create a C#->Web ->Previous Versions -> Asp.Net Web Site (Razor v3) project.
2. Right-click the project and open ‘Manage NuGet Packages’.
3. Click the ‘Updates’ tab, then select all packages and click ‘Update’ button.
4. Update the package ‘Microsoft.Net.Http’ which is installed from previous updating of package ‘Microsoft.AspNet.WebPages.OAuth’ in step 3.
5. Build the project.
## Excepted
No Warning shows in the Error List.
## Actual
‘Unable to get auto-refresh path’ occur after transitive updating of package ‘Microsoft.Net.Http’ as below screenshot.
![123456](https://user-images.githubusercontent.com/40230425/41837147-37626ff2-784c-11e8-8f0c-ff116922ebcd.png)
## Notes:
1. The issue not repro after installing package ‘Microsoft.Net.Http’.
2. The issue also repro on D15.8stg 27821.3003 + NuGet Client Dev 4.8.0.5293.

**Comment by v-luzh** [comment]
Fixed on D16.0\28613.55+NuGet Client Dev\5.0.0.5831.
