### ISSUE TITLE
get package missing on this computer error when the missing file suggested is acctual in the folder

### ISSUE THREAD

**Issue by coyuX** [NuGet/Home#7059]
NuGet product used : Package Manager Console
NuGet version (x.x.x.xxx): 4.7.0.5212
VS version : 2017
OS version : win10

GOT THIS ERROR:
This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\opencv3.1.redist.1.0\build\native\opencv3.1.redist.targets.	video-demo	

HOWEVER, I went to the native folder to check, and the file is right there. 
Anyone have similar problems?
How can I fix this?

**Comment by mishra14** [comment]
@coyuX You should be able to unblock yourself by - 

1.  Deleting the packages folder. 
2.  Then right click on the solution in VS.
3. Restore packages.

You should be able to build after that. Please let us know if you are still blocked.
