### ISSUE TITLE
Command that cleans up the output of the restore

### ISSUE THREAD

**Issue by atanasa** [NuGet/Home#7061]
Is there an option to run a command similar to the Clean target but to clean up the output of the Restore operation?

Currently the `dotnet build` triggers an implicit Restore. The Clean target, as I understand it, is meant to clean up the output of the Build but not the output of the Restore.
I assume that running the Rebuild target would trigger a Clean but not trigger a Restore prior to running the Build target. I would like to have a way to do a Rebuild that would clean up and rerun the Restore too. For that I was thinking of having a target such as CleanRestore that would handle that.

**Comment by mishra14** [comment]
I think what you are loooking for is `dotnet restore --force` or `msbuild /t:restore /p:restoreforce=true`.

The `--force` options performs a full restore and overwrites the results. You can read more about dotnet restore [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x).

Please let us know if you need any more help on this.
