### ISSUE TITLE
.Netstandard lib is not added as a reference to the project? Not sure why?

### ISSUE THREAD

**Issue by eschneider999** [NuGet/Home#7062]
## Details about Problem
When add my package, my .netstandard lib is not added as a reference to the project? Not sure why?
My package is: Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4

Nuget Package Manager 4.6.0
Visual Studio 15.7.4
Windows 10 Pro

Worked before? Not that I'm aware of

## Detailed repro steps so we can see the same problem

1. Create new .net 4.6.1 class library project. 

1.5. You must save the project first.

2. Use Nuget manager to add package "Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4"

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

Could not get "Verbosity" working, could not find docs on proper usage.

Attempting to gather dependency information for package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' with respect to project 'ClassLibrary1', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 382.8 ms
Attempting to resolve dependencies for package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4'
Resolved actions to install package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4'
Retrieving package 'Symbiotic_Micro_ORM_Net_Standard_x64 2.0.4' from 'nuget.org'.
Retrieving package 'System.Data.Common 4.3.0' from 'nuget.org'.
Adding package 'System.Data.Common.4.3.0' to folder 'C:\Users\eric.Schneider\source\repos\ClassLibrary1\packages'
Added package 'System.Data.Common.4.3.0' to folder 'C:\Users\eric.Schneider\source\repos\ClassLibrary1\packages'
Added package 'System.Data.Common.4.3.0' to 'packages.config'
Successfully installed 'System.Data.Common 4.3.0' to ClassLibrary1
Adding package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' to folder 'C:\Users\eric.Schneider\source\repos\ClassLibrary1\packages'
Added package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' to folder 'C:\Users\eric.Schneider\source\repos\ClassLibrary1\packages'
Added package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' to 'packages.config'
Successfully installed 'Symbiotic_Micro_ORM_Net_Standard_x64 2.0.4' to ClassLibrary1
Executing nuget actions took 3.61 sec
Time Elapsed: 00:00:04.2011994
========== Finished ==========

**Comment by mishra14** [comment]
@eschneider999 Thanks for your feedback. 

Couple of things that I can see from the logs - 

1. `Added package 'Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4' to 'packages.config'` - This shows that you have a `packages.config` file in your project and the package reference was added to that.
2. `Successfully installed 'Symbiotic_Micro_ORM_Net_Standard_x64 2.0.4' to ClassLibrary1` - This shows that there were no installation errors. 

Can you please check the `packages.config` file to find the package reference?

**Comment by eschneider999** [comment]
ok, makes sense, yet all the other libs show in the references for the project?

config does show the lib, yet if I try to use the lib, I get errors.
I tried it in both c# and vb.net. I have to manually add the lib reference to get it working.

I may be doing something wrong, just don't know what, and I would like it to work.


<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Symbiotic_Micro_ORM_Net_Standard_x64" version="2.0.4" targetFramework="net461" />
  <package id="System.Data.Common" version="4.3.0" targetFramework="net461" />
</packages>

**Comment by mishra14** [comment]
NuGet supports 2 reference formats - `packages.config` and `PackageReference`.

You are currently using `packages.config` which is older and non-transitive. The new format is `PackageReference` in which the references are added to the project file. 

If you want to change the default to `PackageReference`, you can do it as follows - 
1. Tools -> Options -> NuGet Package Manager
2. Package Management -> Default package management format
3. Change the drop down to PackageReference.

From then on, any project template that supports package reference will start using that format.

**Comment by eschneider999** [comment]
ok, tried that (with a new project) and it's even worse. No references at all?

Restoring packages for C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\ClassLibrary4.csproj...
Restoring packages for C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\ClassLibrary4.csproj...
Committing restore...
Generating MSBuild file C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\obj\ClassLibrary4.csproj.nuget.g.props.
Generating MSBuild file C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\obj\ClassLibrary4.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\obj\project.assets.json
Restore completed in 236.24 ms for C:\Users\eschneider\source\repos\ClassLibrary4\ClassLibrary4\ClassLibrary4.csproj.
Successfully installed 'Symbiotic_Micro_ORM_Net_Standard_x64 2.0.4' to ClassLibrary4
Successfully installed 'System.Data.Common 4.3.0' to ClassLibrary4
Executing nuget actions took 686.1 ms
Time Elapsed: 00:00:01.6870115
========== Finished ==========

**Comment by eschneider999** [comment]
Can we assign someone to this? I have another package to build, and would like to resolve this?

**Comment by mishra14** [comment]
@eschneider999 can you click on File -> Save all and then open the csproj file in a text editor. It should display all the package references.

**Comment by eschneider999** [comment]
for which scenario? the packages.config or the PackageReference ?

I'm just using a blank empty project for testing, just as outlined in my Detailed repro steps. I can continue to follow your directions but I think it will just slow the process down.

**Comment by mishra14** [comment]
@eschneider999 Sorry for the confusion. For the `PackageReference` scenari - 

1. Install a package
2. File -> Save All
3. Open csproj file in a text editor. It should contain all package references.

> ok, tried that (with a new project) and it's even worse. No references at all?

Where are you checking for the references?

**Comment by eschneider999** [comment]
Typically all the references show in the "Solution Explorer" window in Visual Studio (Pro).
Under the project node / References node.

**Comment by mishra14** [comment]
I see thats what you mean. So ideally, all NuGet references should show up in the dependency tree. For instance, I was able to create a new project and  install a package - 

![image](https://user-images.githubusercontent.com/10507120/41994892-c1624f38-7a04-11e8-9591-e93df407acdb.png)

If you are not getting this, I would recommend closing and reopening the solution. If you still do not see the node, then can you please zip the project and attach it to this issue?

**Comment by eschneider999** [comment]
Did you try it with my package?  
Symbiotic_Micro_ORM_Net_Standard_x64.2.0.4

Also since my package is a netstandard you must be in a .Net Framework 4.6.1 or higher

**Comment by mishra14** [comment]
I tried your package with `PackageReference` format - 

![image](https://user-images.githubusercontent.com/10507120/41995222-d09097d4-7a05-11e8-939f-ddf77af279a0.png)

**Comment by eschneider999** [comment]
Where's the specific data provider libs?
And what framework did you choose for that lib?

Looks like the netstandard lib is working/showing there.

If you open the package in the "Windows Package Explorer" you should see all the libs.

**Comment by eschneider999** [comment]
If I exit VS and reopen then project I can see the reference for Symbiotic_Micro_ORM_Net_Standard_x64.
**( I shouldn't need to re-open the project)**

_I can reference in code all the data provider libs, but not the NetStandard orm lib._


[ClassLibrary6.zip](https://github.com/NuGet/Home/files/2143227/ClassLibrary6.zip)

Restoring packages for C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\ClassLibrary6.csproj...
Restoring packages for C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\ClassLibrary6.csproj...
Committing restore...
Generating MSBuild file C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\obj\ClassLibrary6.csproj.nuget.g.props.
Generating MSBuild file C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\obj\ClassLibrary6.csproj.nuget.g.targets.
Writing lock file to disk. Path: C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\obj\project.assets.json
Restore completed in 229.57 ms for C:\Users\eschneider\source\repos\ClassLibrary6\ClassLibrary6\ClassLibrary6.csproj.
Successfully installed 'Symbiotic_Micro_ORM_Net_Standard_x64 2.0.4' to ClassLibrary6
Successfully installed 'System.Data.Common 4.3.0' to ClassLibrary6
Executing nuget actions took 431.64 ms
Time Elapsed: 00:00:01.3967478
========== Finished ==========

**Comment by eschneider999** [comment]
as it stands now, I like the packages.config method. for a couple reasons.

I can see where the references go in the properties window.
And I can remove some of the references if I want. So in my example the intent was for the user to remove the data provider libs that they did not intend to use.

That said, it still does not add the netstandard lib and has no errors, but at least you can look at the other libs and add it manually.

Am I doing something wrong or is Nuget Package Manager broken? Someone please tell me....

**Comment by eschneider999** [comment]
I think the problem is that Nuget doesn't know that my project (.Net 4.6.1) can reference a Net Standard lib, which it can. Maybe I should ad my ORM lib to both package folders? both net461 & netstandard2.0 ?

Is this documented someplace?

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
