### ISSUE TITLE
EINVRES Request to https://bower.herokuapp.com/packages/syncfusion-javascript failed with 502

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7068]
Hi, 

I have faced the below issue while trying to install the bower packages in my project. 

![image](https://user-images.githubusercontent.com/16695209/41976189-17cb1f96-7a3a-11e8-8573-0f29f9c43d99.png)

Could you please help me to resolve this issue?

Thanks,
Ganesan R.

**Comment by mishra14** [comment]
This issue was moved to bower/bower#2519

**Comment by mishra14** [comment]
@GanesanRengasamy  I have moved this issue to the Bower repository. Please track the new issue linked above.
