### ISSUE TITLE
dotnet pack includes all dependencies even if specific TargetFramework is given

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7069]
_From @xalikoutis on June 27, 2018 11:1_

## Steps to reproduce
After upgrading to dotnet sdk 2.1.300 using dotnet pack for specific TargetFramework includes also dependencies from the other TargetFrameworks.

Thats my csproj

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.3</VersionPrefix>
    <TargetFrameworks>netstandard1.6;netstandard1.5</TargetFrameworks>
    <AssemblyName>In.Dto</AssemblyName>
    <PackageId>In.Dto</PackageId>
    <NetStandardImplicitPackageVersion>1.6.1</NetStandardImplicitPackageVersion>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.6' ">$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netstandard1.5' ">$(PackageTargetFallback);dnxcore50;portable-net45+win8</PackageTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.6' ">
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="1.1.2" />
    <ProjectReference Include="..\In.Shared\In.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' ">
    <DefineConstants>$(DefineConstants);MOBILE</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard1.5' ">
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="PropertyChanged.Fody" Version="2.1.3" />
  </ItemGroup>
</Project>
```

Previously with .net sdk 2.0 when running
```
dotnet pack --no-build  /p:TargetFrameworks=netstandard1.5 /p:P
ackageVersion=1.0.36
```

![snap1](https://user-images.githubusercontent.com/847472/41970038-077d64b4-7a12-11e8-9359-dff108a618f9.png)

after installing .net sdk 2.1 i am getting all dependencies
![snap2](https://user-images.githubusercontent.com/847472/41970084-2d22af44-7a12-11e8-8ff5-796bbd66ec32.png)

## Expected  behavior
produced nupkg should include dependencies for specific TargetFramework

## Actual behavior

produced nupkg includes dependencies from all TargetFrameworks
## Environment data
```
dotnet --version
2.1.300
```

_Copied from original issue: dotnet/cli#9569_

**Comment by livarcocc** [comment]
Can you guys take a first crack at this? If it is a CLI/SDK issue, just re-activate the original issue.

**Comment by rrelyea** [comment]
@xalikoutis - pack needs the project.assets.json file that is created by restore.

When you say --no-build, it is skipping the implicit restore.

Fix on your side should be:
1) do a restore with the same settings (set targetframeworks), before you call pack

Please let us know if that doesn't work for you...

/cc @mishra14

**Comment by Temtaime** [comment]
@rrelyea hi
I have a project with
` <TargetFrameworks>netcoreapp3.0;net472</TargetFrameworks>`

and facing this issue when trying to build only for one specific framework only on release:

```
   <Target Name="CustomPack" AfterTargets="build" Condition="'$(Configuration)' == 'Release' And '$(TargetFramework)' == 'netcoreapp3.0'">
     <Exec Command="dotnet pack --no-build -p:TargetFrameworks=netcoreapp3.0 -p:PackAsTool=true -c:Release" />
   </Target>
```

What can i do ?
