### ISSUE TITLE
nuget.exe restore doesn't produce .props and .targets files 

### ISSUE THREAD

**Issue by jarfer** [NuGet/Home#7073]
I've hit the same problem detailed here: https://github.com/NuGet/Home/issues/2711 (closed and fixed in a previous version) this is with nuget 4.1.0.2450

Doing:

C:\Users\someuser\Source>nuget restore MyProject

MSBuild auto-detection: using msbuild version '15.6.85.37198' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Restoring NuGet package a
Restoring NuGet package b
Restoring NuGet package c
...
NuGet Config files used:
    C:\Users\SomeUser\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Users\SomeUser\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Installed:
    3 package(s) to packages.config projects

--------------------------------------------

Packages were restored, but are all missing the .props and .target files, so the solution doesn't build.

**Comment by jainaashish** [comment]
NuGet doesn't produce .props and .targets files for packages.config based project rather directly import those in project file (.csproj). 
So there shouldn't be any issue with respect to these props and targets files. Do you see props or targets files being skipped from the packages?

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
