### ISSUE TITLE
Very confusing behavior when adding a package via Visual Studio

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#7074]
This is very simple:

I'm adding the nuget package `Microsoft.Exchange.WebServices` to a project, I get a problem whether I use VS 2015 or VS 2017.

On one machine after I add the package I see this in the project file:

```
    <Reference Include="Microsoft.Exchange.WebServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Exchange.WebServices.2.2\lib\40\Microsoft.Exchange.WebServices.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Microsoft.Exchange.WebServices.Auth, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Exchange.WebServices.2.2\lib\40\Microsoft.Exchange.WebServices.Auth.dll</HintPath>
      <Private>True</Private>
    </Reference>

```

Note the version folder is "2.2" and the framework folder is "40".

The assemblies then get placed into that folder.

However on someone else's machine, when they open the solution and build, it restores the packages but places them in sub folders named "2.2.0.0" and "net40" and so that project then cannot build (because the project file is looking for folders "2.2" and "40".

Has anyone ever seen anything as weird as this?

**Comment by mishra14** [comment]
@Korporal Thanks for the feedback. I am getting the same path as you described above. 

Can you please ask your co-worker to check the version of NuGet that they have? They can do this by launch "Package Manager Console" and the first few lines should display the NuGet version. 

Please give us the version numbers on both of the machines.

**Comment by The-Futurist** [comment]
@mishra14 - I'll try to get this in a week or so as I'm away fro, office just now. I can tell you that we were each using VS 2017 though. May I ask, has this kind of behavior _ever_ been seen or reported before?

**Comment by nkolev92** [comment]
@Korporal Have you gotten a chance to answer @mishra14's question?

**Comment by nkolev92** [comment]
Closing as we have gotten no response.
