### ISSUE TITLE
[Test Failure] ‘Tool No-Op Restore’ doesn’t work for ASP .NET Core Web Application (.NET Core 2.1)

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7077]
## Details about Problem
NuGet version: NuGet Client Dev 4.8.0.5314
VS Version: D15.8stg 27828.3003
OS Version: Windows 10 RS4_Release 17134.1.180410-1804

## Detailed repro steps so we can see the same problem
1.	Create an ASP .NET Core Web Application (.NET Core 2.1).
2.	Set the diagnostics build format through Tools->Options->Projects and Solutions->Build and Run.
3.	Build the project.

## Expected
The build restore should be no-op for both the tool and the project restore.

## Actual
The build restore is no-op for just the project restore (the ‘Tool No-Op Restore’ doesn’t work) as below screenshot.
![toolnoopdoesnotwork](https://user-images.githubusercontent.com/20632625/42085119-0e86253e-7b7f-11e8-9cd7-319d750f69ed.png)

## Note:
1.	It doesn’t repro for ASP .NET Core Web Application (.NET Core 2.0) on the same machine.
2.	It repro for ‘msbuild /t:restore /v:d’.
3.	It repro on D15.8stg 27828.3003 (default NuGet Client 4.8.0.5278).
4.	Repro Machine: 172.16.194.30 (Added Nikolche's alias into the administrators group).

**Comment by nkolev92** [comment]
From the logs it looks like there is not tool restore happening at all here. 

Did they maybe remove the tool from the template completely?

**Comment by nkolev92** [comment]
The tool is removed from the template right now.
