### ISSUE TITLE
Request Azure ActiveDirectory support for NuGet.exe and NuGet VisualStudio Plugin.

### ISSUE THREAD

**Issue by oliver-feng** [NuGet/Home#708]
I have some code works for AzureAD where server send a challenge, client attach token in http header after authentication. Using the code in AAD sample to do authentication https://github.com/AzureADSamples/NativeClient-DotNet.

With this, it's very easy to host a NuGet with AAD authentication. Here is a private PR.
https://github.com/oliver-feng/nuget/pull/1/files

There are existing support for STS authentication by NuGet server sending a challenge.
See https://nuget.codeplex.com/SourceControl/latest#src/Core/Http/STSAuthHelper.cs
This is useful for enterprise users like http://ms-nuget. 

contact:olfeng@microsoft.com

**Comment by yishaigalatzer** [comment]
Thanks for the issue and the PR! We are locking down for RTM, and this is a rather large change. We will take a look for Visual Studio 2015 Update I

**Comment by oliver-feng** [comment]
Can we add this feature to NuGet 2.8.*?

**Comment by yishaigalatzer** [comment]
We could post dev12 u5 rtm

**Comment by oliver-feng** [comment]
Thank you. when should I check back?

**Comment by yishaigalatzer** [comment]
Lets work on the pr now

**Comment by knudmt** [comment]
this thread is a bit old, did support for this ever get pushed in a release?

**Comment by yishaigalatzer** [comment]
No progress was made, and this is not going to make it into 3.3

**Comment by oliver-feng** [comment]
VSO has a similar solution which is in beta, and they will contribute back
once that's ready.

**Comment by chrisalexander** [comment]
Hello, is there any update on the VSO implementation? Thanks

**Comment by yishaigalatzer** [comment]
The vso bits are in and will go live in update 1

**Comment by chrisalexander** [comment]
@yishaigalatzer Thanks, it twigged that this would be turning up reasonably soon when I found the ms.feed plugin for VSO / VSTS. Cheers!

**Comment by kfehribach** [comment]
I've installed Update 1 (14.0.24720.00) and I'm still seeing this issue. (Specifically, trying to access an Azure AD secured nuget feed from Visual Studio)

**Comment by yishaigalatzer** [comment]
This is only supporting visual studio plugin at this point and not generic aad secured feed

**Comment by kfehribach** [comment]
Can you clarify what you mean by that? I'm confused by which plugin you are speaking of and which feed that it would support. Just trying to understand what the valid use cases are.

**Comment by yishaigalatzer** [comment]
Visual studio online introduced authenticated nuget feeds. These are now supported through a plugin model in visual studio 2015+nuget3. There is also a plugin model for the command line

**Comment by mocsharp** [comment]
I have a private NuGet feed hosted on Azure WebSites which requires user to login using their Windows Azure AD account.  With VS 2015 Update 1, the dialog it opens when I switch to my NuGet feed is still a standard authentication dialog.  It would be great if it support IdP (OAuth) types of dialogs.

**Comment by Wylice** [comment]
There hasn't been any updates on this in over 8 months.  Is there any solution yet for accessing a private NuGet feed behind Azure AD?

**Comment by oliver-feng** [comment]
Checkout how NuGet runs VSTS credential provider if you want to implement
you own credential provider. We have decided to use VSTS packaging feature
and not create our own.

**Comment by oliver-feng** [comment]
Checkout how NuGet runs VSTS credential provider if you want to implement you own credential provider. We have decided to use VSTS packaging feature and not create our own.

"NuGet.Client-release-3.4.3\src\NuGet.Clients\NuGet.CommandLine\ExtensionLocator.cs"(48,36):        public IEnumerable<string> FindCredentialProviders()
"NuGet.Client-release-3.4.3\src\NuGet.Clients\NuGet.Credentials\PluginCredentialProviderBuilder.cs"(60,49):            var pluginPaths = _extensionLocator.FindCredentialProviders();
"NuGet.Client-release-3.4.3\src\NuGet.Core\NuGet.Configuration\Utility\IExtensionLocator.cs"(21,29):        IEnumerable<string> FindCredentialProviders();

**Comment by zairhenrique** [comment]
So NuGet will not be able to work with Azure AD?

**Comment by rafaelsc** [comment]
Any solution or alternatives to accessing a private NuGet feed behind Azure AD?
