### ISSUE TITLE
latest version not shown in NuGet package manager

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7082]
Hi all,

I have used the custom nuget feed (https://nuget.syncfusion.com/nuget_aspnetcore/nuget/getsyncfusionpackages/aspnetcore) to install the NuGet packages. But when I configure this in Visual studio and trying to install the latest version (16.2.0.41) NuGet packages, I can't see the latest version by default in the first of the version order.

![image](https://user-images.githubusercontent.com/16695209/42147723-b6d5edb8-7dec-11e8-9ba2-7989e06a9081.png)

Could you please suggest me the idea to how can I show the latest version in the first of the order.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
What you are seeing is correct. 

`1600` > `2`, so it's a later version.

**Comment by GanesanRengasamy** [comment]
Yes, But I want the solution there is any way to show the 16.2.0.41 on top of the order.

**Comment by nkolev92** [comment]
@GanesanRengasamy 
Nope, that's not possible. 

Relevant info: https://semver.org

Closing this now.

**Comment by GanesanRengasamy** [comment]
Okay @nkolev92 . Thanks for your response
