### ISSUE TITLE
[Test Failure] ‘Manage NuGet Packages…’ can’t be opened after Installing a package.

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7086]
## Details about Problem
NuGet Version: NuGet Client Dev\4.8.0.5320
VS Version: D15.8stg 27902.3002
OS Version: Windows 10 RS4_Release 17134.1.180410-1804.
## Detailed repro steps so we can see the same problem
1. Create a C#->Windows Desktop-> Class Library (.NET Framework) project.
2. Open the ‘Manage NuGet Packages…’ for the project.
3. Install a package (e.g. Newtonsoft.Json) and close the PM UI.
4. Right-click the project on Solution Explorer window and check the ‘Manage NuGet Packages… ’.
## Expected
‘Manage NuGet Packages…’ is still available.
## Actual
‘Manage NuGet Packages…’ is disabled as below screenshot.
![bug1111](https://user-images.githubusercontent.com/40230425/42208444-b9c55b44-7e9b-11e8-8927-db38a6e05ba1.png)
## Notes
1. The issue also repro after building the solution/project.
2. The issue also repro on other projects.
3. The issue also repro when creating a new project if the previous project not closed. 
4. The workaround is reopening the VS and creating a new project.

**Comment by nkolev92** [comment]
@rohit21agrawal This seems to be caused by https://github.com/NuGet/NuGet.Client/commit/358c198ead904aa4070c7fb65d9fba6fa47cd370.
