### ISSUE TITLE
Automatically reserve username package prefix

### ISSUE THREAD

**Issue by dasMulli** [NuGet/Home#7088]
The bar to register a prefix on nuget.org is "quite high" at the moment and requires manual steps, which is good for arbitrary prefixes.

I suggest automatically reserving the prefix matching the username of nuget.org users.

E.g. my username is "dasMulli", so I should be the only one allowed to upload new packages starting with "DasMulli."

**Comment by nkolev92** [comment]
This issue was moved to NuGet/NuGetGallery#6138

**Comment by nkolev92** [comment]
@dasMulli 
Thanks for creating this. 

I moved it to the gallery repo as I it's more appropriate for this ask.
