### ISSUE TITLE
ContentFiles Causing Bloated Package and an Extra Configuration Step for Consumers

### ISSUE THREAD

**Issue by JeremyTCD** [NuGet/Home#7090]
# TL,DR
- In a dependency chain of packages, do `ContentFiles` need to be replicated in every package? Is there a configuration to avoid this?
- Answered here: https://github.com/NuGet/Home/issues/6091 ~~Is it possible to exclude `ContentFiles` from the `PrivateAssets` attribute of a `PackageReference` by default?~~

# Problem Description
Consider 3 hypothetical projects with the following dependency tree:
```
ConsoleApplication
└─ ClassLibrary2
      └─ ClassLibrary1
```
## ClassLibrary1
`ClassLibrary1.dll` requires `bundle.js` to work, so ClassLibrary1 defines a `Content` item in its `.csproj`:
```xml
<Content Include="bundle.js">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <PackageCopyToOutput>true</PackageCopyToOutput>
</Content>
```
The `.nuspec` generated for ClassLibrary1 has the following `contentFiles` element:
```xml
<contentFiles>
    <files include="any/netcoreapp2.1/bundle.js" buildAction="Content" copyToOutput="true" />
</contentFiles>
```
ClassLibrary1 and its package are fine.
## ClassLibrary2
ClassLibrary2 references ClassLibrary1:
``` xml
<PackageReference Include="ClassLibrary1" Version="1.0.0" PrivateAssets="None" />
```
Answered here: https://github.com/NuGet/Home/issues/6091 ~~The `PackageReference` for `ClassLibrary` requires extra configuration for the `PrivateAssets` attribute so that `ContentFiles` are included.~~  

The `.nuspec` generated for ClassLibrary2 has the following `metadata` element:
```xml
<metadata>
    ...
    <dependencies>
        ...
        <dependency id="ClassLibrary1" version="1.0.0" include="Runtime,Compile,Native,ContentFiles" />
        ...
    </dependencies>
    <contentFiles>
        <files include="any/netcoreapp2.1/bundle.js" buildAction="Content" />
    </contentFiles>
</metadata>
```
`ClassLibrary2.nupkg` contains a redundant copy of `bundle.js`.

# My Questions
- When building `ConsoleApplication`, is it possible for Nuget to use `bundle.js` from `ClassLibrary1.nupkg`? - after all, `ConsoleApplication` indirectly references `ClassLibrary1`, so `ClassLibrary1.nupkg` is installed. Is having `bundle.js` replicated in `ClassLibrary2.nupkg` necessary?

- Answered here: https://github.com/NuGet/Home/issues/6091 ~~Typically, any class library that includes content files in its package needs those files to function. Why does ClassLibrary2 exclude ClassLibrary1's `ContentFiles` by default? Is it possible to override this default from `ClassLibrary1`?~~

## Actual packages
These are the actual "ClassLibrary1" packages: https://www.nuget.org/packages/JeremyTCD.WebUtils.SyntaxHighlighters.HighlightJS/  
https://www.nuget.org/packages/JeremyTCD.WebUtils.SyntaxHighlighters.Prism/

This is the offending "ClassLibrary2" package: https://www.nuget.org/packages/Jering.Markdig.Extensions.FlexiBlocks/  

`Jering.Markdig.Extensions.FlexiBlocks.nupkg` is 648KB zipped, JS bundles account for 600KB (the bundles each appear twice in `Jering.Markdig.Extensions.FlexiBlocks.nupkg` - in the `content` and the `contentFiles` folders). To reiterate, the same bundles are already present in `JeremyTCD.WebUtils.SyntaxHighlighters.HighlightJS.nupkg` and `JeremyTCD.WebUtils.SyntaxHighlighters.Prism.nupkg`.

# Client Versions
NuGet product used: dotnet.exe
NuGet version (x.x.x.xxx): 4.7.0.5
dotnet.exe --version (if appropriate): 2.1.300
VS version: 15.7.4

# Edit
https://github.com/NuGet/Home/issues/6091 answers my second question. For anyone wondering, at present, the only way to have build/contentFile assets flow through multiple class libraries is to specify `PrivateAssets` for every `PackageReference` in the chain.

# Edit
As mentioned in the comment below, you can also reference the package with the contentFiles directly at the root of the dependency tree.

**Comment by nkolev92** [comment]
> When building ConsoleApplication, is it possible for Nuget to use bundle.js from ClassLibrary1.nupkg? - after all, ConsoleApplication indirectly references ClassLibrary1, so ClassLibrary1.nupkg is installed. Is having bundle.js replicated in ClassLibrary2.nupkg necessary?

Yes, you can do some authoring side tricks. 
If ConsoleApplication has a PackageReference to ClassLibrary2.nupkg, and the default PrivateAssets there is `contentfiles;analyzers;build`, you can override that to `analyzers;build`. 

Other than that, there is not much that can be done. I'm glad you found the answer to the 2nd question. 

//cc @rohit21agrawal

**Comment by JeremyTCD** [comment]
Ah okay, I think you meant:
> ConsoleApplication has a PackageReference to **ClassLibrary1.nupkg**

Anyway, it works, thanks for the tip!
