### ISSUE TITLE
Nuget Publish Got 500 Against Large (276MB) Package.

### ISSUE THREAD

**Issue by singku** [NuGet/Home#7091]
## Details about Problem
We were uploading packages using nuget.exe. One day one of the packages failed to be uploaded to nuget gallery. Previous version of this package has 207MB. The failed one has 276MB.
Package: https://www.nuget.org/packages/AWSSDKCPP-EC2/1.3.20161115.48

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
nuget.exe

NuGet version (x.x.x.xxx):
4.6.2.5055

OS version (i.e. win10 v1607 (14393.321)):
Windows Server 2012

## Detailed repro steps so we can see the same problem
1. nuget.exe setApiKey **[KEY]**
2. powershell.exe -NonInteractive -ExecutionPolicy RemoteSigned "Publish-NuGetPackage -Packages **[PKGPATH]**   -Repository https://www.nuget.org/api/v2/package -SymbolRepository https://nuget.smbsrc.net -ApiKey **[KEY]** Verbose }"

...

### Verbose Logs
VERBOSE: PublishNuGetPackage:Pushing package file C:\nupkg\AWSSDKCPP-EC2.1.4.20161115.80.nupkg.

 Pushing AWSSDKCPP-EC2.1.4.20161115.80.nupkg to 'https://www.nuget.org/api/v2/package'...
 PUT https://www.nuget.org/api/v2/package/
 InternalServerError https://www.nuget.org/api/v2/package/ 9115ms
 PUT https://www.nuget.org/api/v2/package/
 InternalServerError https://www.nuget.org/api/v2/package/ 8134ms
 PUT https://www.nuget.org/api/v2/package/
 InternalServerError https://www.nuget.org/api/v2/package/ 8362ms
 Response status code does not indicate success: 500 (Object reference not set to an instance of an object.).

**Comment by singku** [comment]
Got a response from support team that the file size limit is 250MB. Will this limit be increased?

**Comment by shishirx34** [comment]
@singku - Do you regularly expect to push packages with sizes greater than 250Mb? Would it be not possible for you to break up the package to a size lesser than the limit?

@anangaur, @skofman1 for consideration to increase size limit.

**Comment by singku** [comment]
Our package include both V120/140/141 versions for VS2013/15/17 and those packages include static/dynamic linked versions. When it's static the size is huge. As far as I know, I cant break V120/140/141 to separate ones.

**Comment by anangaur** [comment]
@singku How is this package used? Looks like this is an SDK package. Do you use nuget CLI to install these packages? Or msbuild.exe to install it as a MSBuild SDK?

**Comment by singku** [comment]
We are the SDK packages' vendor. When using it, I just manage packages from VS's Nuget manage UI.

**Comment by nkolev92** [comment]
@shishirx34 @anangaur 
When this discussion has been completed can you loop back to close the this issue?
Or should we move it to the gallery directly?

**Comment by anangaur** [comment]
Issue moved to [NuGet/NuGetGallery #6144](https://github.com/NuGet/NuGetGallery/issues/6144) via [**ZenHub**](https://www.zenhub.com/)
