### ISSUE TITLE
Nuget Restore issue

### ISSUE THREAD

**Issue by san1850** [NuGet/Home#7093]
I am adding nuget packages from a internal project source. My visual studio application builds fine locally after referring nuget packages. When any other dev is taking my shelveset of this changes they are getting error as below.

**Unable to perform operation on ../{path}/packages/Telerik.Web.UI.2018/nuget.exe. The item ../{path}/ packages/Telerik.Web.UI.2018/nuget.exe is locked in workspace. 

Unable to perform operation on ../{path}/packages/Telerik.Web.UI.2018/lib/Telerik.Web.UI.dll. The item    ../{path}/packages/lib/Telerik.Web.UI.dll. is locked in workspace.** 

Cant understand why is it locking when some one is trying to restore nugets from shelve set. This is happening to any nuget that we are trying to refer.

**Comment by nkolev92** [comment]
@san1850 
I'm not really sure I follow what's going on here. Can you please provide full steps for a repro? 

That error is not coming from NuGet, but from TFS. Don't think there's anything NuGet can do here. 

Please note that the recommendation is to **not** check-in your packages folder in source control.

**Comment by rohit21agrawal** [comment]
closing issue due to lack of response. please reactivate if this is still an issue.
