### ISSUE TITLE
Unable to copy file / The given path's format is not supported

### ISSUE THREAD

**Issue by dvdobrovolskiy** [NuGet/Home#7095]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI 

NuGet version (x.x.x.xxx):  4.6.2.5055

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2.1.201

OS version (i.e. win10 v1607 (14393.321)): win10 Version 10.0.17134.1

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

Happens during build

### Verbose Logs

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3021	Unable to copy file "C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\es\Hangfire.Core.resources.dll" to "bin\Debug\net461\win7-x86\$([System.IO.Directory]::GetParent(C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\es\Hangfire.Core.resources.dll).get_Name())\Hangfire.Core.resources.dll". The given path's format is not supported.	Dispatcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3021	Unable to copy file "C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\zh-TW\Hangfire.Core.resources.dll" to "bin\Debug\net461\win7-x86\$([System.IO.Directory]::GetParent(C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\zh-TW\Hangfire.Core.resources.dll).get_Name())\Hangfire.Core.resources.dll". The given path's format is not supported.	Dispatcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	
Error	MSB3021	Unable to copy file "C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\zh\Hangfire.Core.resources.dll" to "bin\Debug\net461\win7-x86\$([System.IO.Directory]::GetParent(C:\Users\Dz'\.nuget\packages\hangfire.core\1.6.19\lib\net45\zh\Hangfire.Core.resources.dll).get_Name())\Hangfire.Core.resources.dll". The given path's format is not supported.	Dispatcher	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	4343	

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by PatoBeltran** [comment]
hey @dvdobrovolskiy thanks for opening the issue. I tried reproing this by creating a new project and downloading `Hangfire.Core`, but had no success. By looking on the error message you provide, certainly the path `C:\Users\Dz'.nuget\packages\hangfire.core\1.6.19\lib\net45\es\Hangfire.Core.resources.dll` looks weird. What does your `%userprofile%` look like? If you go to `%userprofile%\.nuget\packages\hangfire.core\1.6.19\lib\net45\es\` can you find `Hangfire.Core.resources.dll` there? 

We get those links from the `project.assets.json` file found in the `obj` directory of your project. Can you please provide a copy of your assets file to make sure the correct path is shown there?

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
