### ISSUE TITLE
No way to resolve conflict warnings occur after updating package of ASP.Net Web Application

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7097]
## Details about Problem
NuGet version: NuGet Client Dev 4.8.0.5324
VS Version: D15.8stg 27907.3001
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps
1. Create an ASP.Net Web Application (.NET Framework 4.6.1) - take MVC as example.
2. Select MVC and check “MVC” and “Web API” under “Add folders and core references for“.
3. Select “Windows Authentication” and click OK button.
4. Build the project and open Error List window.
5. Open PMC through Tools->NuGet Package Manager->Package Manager Console.
6. Type "Update-Package" and build again.
## Expected
No error or warning occur in Error List window.
## Actual
No way to resolve conflict between different versions of the same dependent assembly Newtonsoft.Json even after auto-fixing by double-clicking this warning in Error List window as below screenshot.
![mvcwarnings](https://user-images.githubusercontent.com/20632625/42442359-ff1c66d4-8359-11e8-977d-f88271d1a5fd.png)
## Note
1. It repro on Dev16 Master 27910.4000 (Default NuGet Client 4.8.0.5244).
2. It repro on D15.8stg 27910.3002 (Default NuGet Client 4.8.0.5328).

**Comment by hilvarenbeek** [comment]
Possibly related to MSBuild issue as described here: https://stackoverflow.com/questions/50638711/msbuild-is-replacing-newtonsoft-json-dll-with-an-older-version

**Comment by v-luzh** [comment]
This issue is fixed on VS Main\35221.199 + NuGet Client Dev\6.12.0.81. I will close this bug soon.
