### ISSUE TITLE
Nuget restore producing differing structure within same solution depending on target

### ISSUE THREAD

**Issue by Joev-** [NuGet/Home#7098]
## Details about Problem

I have a solution with many projects in it, ASP.NET MVC, several console applications, and class libraries. Where possible the projects use the new csproj format. The MVC project is the only one that does not. The MVC project still uses packages.config, the rest use PackageReference.

I have a solution file which is used to group a single console application and it's dependent projects. I have another solution file with the web project and again it's dependent projects. When I run `nuget restore WebSolution` nuget will restore all packages to the `packages` directory in the root of the solution. Every package is named with the version appended to the end of the directory.

When I run `nuget restore ConsoleSolution -PackagesDirectory packages` (the PackagesDirectory is required here for reasons I cannot understand nor see documented) nuget will restore the packages, but in a structure where the version is an additional sub directory within the named package directory.

The reason this is an issue for me is that I have a shared MSBuild script that references a DLL for the XUnit MSBuild test runner. I have tests in the two, different, specific solutions which relate to the product, and would like to be able to have a single simple reference to the XUnit runner package.

Either this is a bug based around the difference between PackageReference and packages.config or there is some behavior I should be able to toggle that I cannot see documented.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe

NuGet version (x.x.x.xxx):
4.6.2.5055

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):
Win10 1803 (17134.112)

Worked before? If so, with which NuGet version:
Unsure

## Detailed repro steps so we can see the same problem

1. Create a new solution containing a MVC project. .NET Framework, 4.7.1
2. Add a new Console project, .NET Framework 4.7.1
3. Install Newtonsoft.Json (Common to both projects) to the ConsoleProject, selecting PackageReference if prompted.
4. Create a new blank solution and add ConsoleProject to it.
5. Clear the packages directory (observe the structure should have folders name x.x.x.major.minor.patch)
6. Run `nuget restore ConsoleSolution.sln -PackagesDirectory packages` from the root of the solution
7. Observe the new structure in the packages folder of `x.x.x\major.minor.patch\`
8. Clear folder again and run `nuget restore InitialSolution.sln` and note the changed folder structure

### Sample Project
[NuGetRepro.zip](https://github.com/NuGet/Home/files/2175605/NuGetRepro.zip)

**Comment by PatoBeltran** [comment]
Hey @Joev- thanks for opening the issue. This behavior you mention is by design. 

Packages config, uses the V2 protocol, which has a different directory structure from Package Reference, which uses the V3. 

Now, you don't need to specify `-PackagesDirectory packages` to your restore unless you explicitly want your packages to be in that location. On Package Reference, we switched over from the solution level packages folder to a user level packages folder, which is located in `%userprofile%/.nuget/packages`, here all the packages from every project will be share and will make it faster for all of your projects because you can reuse the package files for multiple projects. This was also one of the reasons a change from the V2 to the V3 of the protocol was needed, it is a has a more powerful and performant way of referencing the dependencies for projects.

**Comment by Joev-** [comment]
Hi @PatoBeltran 

Thanks for the explanation, I can see the benefits of sharing packages between projects, I must have missed the announcement on the design changes and it caught me out.

Is there a reasonable solution for referencing a package's directory from a shared MSBuild script? I am aware of the `.nuget.g.props` and `.targets` files, but they don't help me in this situation as this script is shared between several projects and is executed directly as an additional post-build step, isolated from the project build, on our build server.

Appreciate any additional info you can provide.

**Comment by PatoBeltran** [comment]
In Package Reference there is the concept of the `project.assets.json` file (it is under the `obj/` directory). This file has all the information about the dependencies (top level and transitive) references in a given project and where they are stored. You could use that file to get information about where the packages are located and referencing the dlls. Is this useful?

**Comment by Joev-** [comment]
Hi,

This does not help me as the project.assets.json are still project dependent. I can work around the problem by specifying a well known PackagesDirectory option, and I am sure when I eventually get my MVC project off of V2 of the protocol there will be a clearer solution for me.

I'll close this for now as I don't see any clear way of resolving this.

**Comment by Joev-** [comment]
I figured in the end that the nuget package root is going to be the same for all projects using V3 of the protocol, so it can be retrieved from any of the *.nuget.g.props files in the newer projects. Using this I can access the same xUnit MSBuild runner DLL regardless of where it is installed.
