### ISSUE TITLE
After installing nuget server, I do not see well-formatted OData over ATOM feed of packages

### ISSUE THREAD

**Issue by csimone86** [NuGet/Home#7099]
I am creating a free private nuget server with visual studio. I am following exactly the indicated steps on [nuget server site](http://nugetserver.net/) (those one on the right).

I think I have done everything, and nothing should miss and nothing should have been done in a different way.

But when I run my site, and I click on "here" (step 5) I do not see a well-formatted page like [this one](http://nugetserver.net/gfx/OData-over-ATOM-package-feed.png)...

But I see just the XML.

I am using Chrome.

What's wrong?

Thank you

**Comment by PatoBeltran** [comment]
Issue moved to [NuGet/NuGetGallery #6162](https://github.com/NuGet/NuGetGallery/issues/6162) via [**ZenHub**](https://www.zenhub.com/)

**Comment by PatoBeltran** [comment]
@csimone86 I moved this to `NuGetGallery` since they own the nuget server implementation.
