### ISSUE TITLE
NuGet.VisualStudioExtension: MEF error regarding to IVsFrameworkMultiTargeting

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#71]
System.ComponentModel.Composition.ImportCardinalityMismatchException occurred
  Message=No exports were found that match the constraint: 
    ContractName    Microsoft.VisualStudio.Shell.Interop.IVsFrameworkMultiTargeting
    RequiredTypeIdentity    Microsoft.VisualStudio.Shell.Interop.IVsFrameworkMultiTargeting
  InnerException:

**Comment by madnemesio** [comment]
Hi, I have a similar problema with NuGet.

No exports were found that match the constraint.
Referencing NuGet.VisualStudio.IVsTemplateWizard.

¿how can I solve this? Please help.
