### ISSUE TITLE
Package description/details are not shown on Installed tab 

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#710]
Repro steps:
1. have api.nuget.org and aspnetVnext feed both enabled
2. create a new MVC5 application
3. start package manager, go to installed tab
4. select package source to AspNetVnext

Expected: If we can retrieve the metadata from any of the enabled feeds, we should use it

Actual: metadata is not shown and we ended up with very blank lists like below:

![capture](https://cloud.githubusercontent.com/assets/1087852/7949577/028d96c8-0944-11e5-9abd-1d28a2127be5.PNG)

**Comment by yishaigalatzer** [comment]
We should probably show something like - Not available in this source

**Comment by escamoteur** [comment]
I just encountered this message on packages that I created and host in VSTS. What does it mean? The packages work and can be installed
