### ISSUE TITLE
Issue with installing package to directory

### ISSUE THREAD

**Issue by hamfar** [NuGet/Home#7101]
## Details about Problem
Installing a package via nuget.exe to a directory from a private feed causes a dependency issue when there are no dependencies on package. The dependencies seem to arise from the directory the package is being installed to and previous packages installed in that location. For below error, Nunit.Console is not a requirement for Package1 but was installed by a previous command to c:\tools

Attempting to gather dependency information for package 'Package1' with respect to project 'c:\tools', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Package1' with DependencyBehavior 'Lowest'
Unable to find package 'NUnit.Console'. Existing packages must be restored before performing an install or update.
 System.InvalidOperationException: Unable to find package 'NUnit.Console'. Existing packages must be restored before performing an install or update. ---> NuGet.Resolver.NuGetResolverInputException: Unable to find package 'NUnit.Console'. Existing packages must be restored before performing an install or update.
    at NuGet.Resolver.PackageResolver.Resolve(PackageResolverContext context, CancellationToken token)
    at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
    --- End of inner exception stack trace ---
    at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__66.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__48.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at NuGet.CommandLine.InstallCommand.<InstallPackageAsync>d__40.MoveNext()

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 4.6.2.5055

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):Windows Server 2012

Worked before? If so, with which NuGet version: 3.5.0.1938

## Detailed repro steps so we can see the same problem

1. Install a package to a local directory: command run "nuget.exe install Package1 -ExcludeVersion -Source http://localfeed"

2. Install a second package to the same directory as above
"nuget.exe install Package2 -ExcludeVersion -Source http://localfeed"

...

**Comment by hamfar** [comment]
After further testing, I found that this occurs if I install nunit.console first with the -ExcludeVersion, any packages installed after with -ExcludeVersion fails with a dependency on Nunit.Console

**Comment by PatoBeltran** [comment]
hey @hamfar thanks for the issue, I was trying to repro your problem but I had no luck. I tried creating a new folder and ran `nuget.exe install NUnit.console -ExcludeVersion -Source https://api.nuget.org/v3/index.json` and after that I ran `nuget.exe install newtonsoft.json -ExcludeVersion -Source https://api.nuget.org/v3/index.json` and it installed successfully.

Can you provide a repro project that we can use to understand better the issue? Do you know if the `C:/tools` directory only has a V2 directory structure? or does it have a mix between v2 and v3? it might be that nuget is getting confused because it doesn't know which version of the folder structure to use. V2 is the version used with packages.config (where the package is named with id.version) and v3 is the hierarchical structure used in pacakge references where the first directory is the id and under it there are directories for each version.

**Comment by hamfar** [comment]
Hi, 

Thanks for this information, it has shed light on the issue. I am investigating a 3rd party application we are using. This has a connector to Nuget.org and could be why there is a mix between v2 and v3

Thanks

**Comment by kshanafelt** [comment]
@PatoBeltran I also could not repro this issue using @hamfar steps.  But I was getting the same error.

I can repro them the following way:
1. nuget pack something no currently in your source path.
    1. I created a file called `Test.Nuget.Install.nuspec`:
      ```xml
      <?xml version="1.0" encoding="utf-8"?>
      <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
        <metadata>
          <id>Test.Nuget.Install</id>
          <version>1.0.0.7101</version>
          <authors>me</authors>
          <requireLicenseAcceptance>false</requireLicenseAcceptance>
          <description>Testing nuget install ExcludeVersion, when nupkg exists in folder that is not in source</description>
          <releaseNotes></releaseNotes>
        </metadata>
      </package>
      ```
   1. Just so my temp file would have content, I added an empty folder called `stuff`, with and empty txt file called `empty.txt`.
  1. next run: `nuget pack Test.Nuget.Install.nuspec`
1. Now you will not be able to `nuget.exe install -ExcludeVersion` any package that contains this `Test.Nuget.Install.1.0.0.7101.nupkg` file in the folder you are installing to.

I was able to repo this with: 
NuGet Version: 4.5.1.4879, and NuGet Version: 4.6.2.5055

and this works with: 
NuGet Version: 3.5.0.1996

OS: Windows Server 2008 R2 Standard, and Windows 10 Enterprise

**Comment by Ausxor** [comment]
I am also experiencing this issue on NuGet.CommandLine 4.9.3. It was not an issue on version 3.

1. I have a nuget.config with a relative source for nuget packages.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>&gt;
  <config>
    <add key="globalPackagesFolder" value="packages" />
    <add key="dependencyVersion" value="Highest" />
    <add key="defaultPushSource" value="." />
  </config>
  <packageSources>
       <add key="local" value=".\" />
       ...
  </packageSources>
</configuration>
```
2. I have a package stored at the same location as the nuget.config file. ABC.123.API.0.0.0.nupg.
3. I install the package.
`install ABC.123.API -ExcludeVersion -Source local -PreRelease -OutputDirectory "C:\inetpub\project"-Version 0.0.0 -NoCache -Verbosity detailed`
4. The package restore fails.
> Unable to find package 'ABC.123.UI'. Existing packages must be restored before performing an install or update.
System.InvalidOperationException: Unable to find package 'Chubb.DBS.Web.UI'. Existing packages must be restored before performing an install or update

Earlier I had performed the install of the 'ABC.123.UI' package using the same means, which had worked. Resulting in the folder "C:\inetpub\project\ABC.123.UI'.

Note that if I simple change the path of the above command to 'C:\inetpub\project\1' then the ' ABC.123.API' package installs successfully. So it seems to acknowledge the existence of the other folder as a dependant package.

**Comment by Ausxor** [comment]
I am also experiencing this issue on NuGet.CommandLine 4.9.3. It was not an issue on version 3.

1. I have a nuget.config with a relative source for nuget packages.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <config>
    <add key="globalPackagesFolder" value="packages" />
    <add key="dependencyVersion" value="Highest" />
    <add key="defaultPushSource" value="." />
  </config>
  <packageSources>
       <add key="local" value=".\" />
       ...
  </packageSources>
</configuration>
```
2. I have a package stored at the same location as the nuget.config file. ABC.123.API.0.0.0.nupkg.
3. I install the package.
`install ABC.123.API -ExcludeVersion -Source local -PreRelease -OutputDirectory "C:\inetpub\project"-Version 0.0.0 -NoCache -Verbosity detailed`
4. The package restore fails.
> Unable to find package 'ABC.123.UI'. Existing packages must be restored before performing an install or update.
System.InvalidOperationException: Unable to find package 'ABC.123.UI'. Existing packages must be restored before performing an install or update

Earlier I had performed the install of the 'ABC.123.UI' package using the same means, which had worked. Resulting in the folder "C:\inetpub\project\ABC.123.UI'.

Note that if I simple change the path of the above command to 'C:\inetpub\project\1' then the ' ABC.123.API' package installs successfully. So it seems to acknowledge the existence of the other folder as a dependant package.

**Comment by pvandervelde** [comment]
@PatoBeltran Do you still need a repo for this? We run into this one on a regular basis and are unable to upgrade to 4.9.x because of this issue. We use 4.3.0 which works but would like to upgrade.

**Comment by pvandervelde** [comment]
@PatoBeltran Is there any plan to get this issue fixed? We're still stuck on using 4.3 due to this issue which blocks us from using .NET core. Would love to be able to update to the latest version of the nuget command line

**Comment by nkolev92** [comment]
@pvandervelde 

Can you provide a repro for your scenario? 

Following @Ausxor's repro steps I was not able to repro this issue with NuGet 5.6.0-preview.2

**Comment by nkolev92** [comment]
Triage: At this point, we are not able to repro some of these scenarios with the latest tooling, so we're closing this issue as no repro. 

If you are still facing a similar issue, please upgrade to the latest tooling and create a new bug if you can still repro.
