### ISSUE TITLE
Condition References

### ISSUE THREAD

**Issue by shishirx34** [NuGet/Home#7102]
@eschneider999 commented on [Sun Jul 08 2018](https://github.com/NuGet/NuGetGallery/issues/6149)

If I have optional references, what is the best way to achieve this? 

In my case it's a database vendor library. If they choose Oracle, Sql Server, My Sql, there would be a specific vendor lib needed. 

Currently I add all and allow the developer to remove the unneeded verdors, but with the new Package reference you can't remove specific libs?

I thought about adding a content folder and adding them to it, then dynamically referencing them in code. But it seems the package reference doesn't support content/project folders?

I would rather not add create packages for all the database vendors? Is there A way to create a skeleton package that combines other packages?

**Comment by eschneider999** [comment]
Not sure how this answers any of my questions...

**Comment by PatoBeltran** [comment]
Hey @eschneider999 I'm not sure I understand what you are trying to do. In your csproj you can have conditions on an item group, so you could have different item groups with different dependencies based on whichever variable you want. Something like:

```
  <ItemGroup Condition="'$(VendorLibrary)' == 'Oracle'">
    <PackageReference Include="Package1" Version="1.0.0">
     …
     </PackageReference>
  </ItemGroup>
```

Does this solve your question?

**Comment by eschneider999** [comment]
the projects are just sample projects. The user will only look at these for reference to understanding the ORM.

What I would like is and options dialog, which the user can pick a database vendor.
Making a package for each database is a pain and can cause me circular reference issues when deploying.

**Comment by PatoBeltran** [comment]
The scenario you are talking about is not supported by our tools. There is no way to control NuGet transitive resolution based on user input, and also you cannot have granular control for assets selected during restore.

The way I see it, there are two ways you can solve this issue:

1. Create a package with everything, where you have a switch in your code and only let the user actually use what you want depending on your constraints.

2. Create one package per database and let the user only download the minimal set of things they need.
To avoid circular references between packages you can have core packages that have your implementation and are referenced by the different packages.

**Comment by eschneider999** [comment]
Why not add support for it, should be pretty easy

On July 13, 2018 4:38:38 PM CDT, Patricio Beltran <notifications@github.com> wrote:
>The scenario you are talking about is not supported by our tools. There
>is no way to control NuGet transitive resolution based on user input,
>and also you cannot have granular control for assets selected during
>restore.
>
>The way I see it, there are two ways you can solve this issue:
>
>1. Create a package with everything, where you have a switch in your
>code and only let the user actually use what you want depending on your
>constraints.
>
>2. Create one package per database and let the user only download the
>minimal set of things they need.
>To avoid circular references between packages you can have core
>packages that have your implementation and are referenced by the
>different packages.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NuGet/Home/issues/7102#issuecomment-404960775

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
