### ISSUE TITLE
Deadlock due to threading issues when calling into CPS (CommonProjectSystem)

### ISSUE THREAD

**Issue by jviau** [NuGet/Home#7103]
## Details about Problem

VS version (if appropriate): 15.8 preview 4

Worked before? If so, with which NuGet version: Yes, previous VS releases.

NuGet is calling into CPS API's under its own `PumpingJTF`. This has regressed a fix previously made for #4185. We plan on removing this requirement of using the CPS JTF when calling into CPS APIs in a future release, but this is currently causing deadlocks in 15.8 preview.

I can supply a dump file if needed.

**Comment by jainaashish** [comment]
PR merged.
