### ISSUE TITLE
Access Denied while updating credential via "Nuget sources update"

### ISSUE THREAD

**Issue by fernisoites** [NuGet/Home#7106]
## Details about Problem

NuGet product used:  NuGet.exe

NuGet version (4.7.0.5148):

Worked before? If so, with which NuGet version: 4.6.2.5055

## Detailed repro steps so we can see the same problem

1. nuget.exe sources update -Name {ANY_NUGET_FEED} -UserName {USER_NAME} -Password {VSTS_TOKEN}

### Verbose Logs
Failed to read NuGet.Config due to unauthorized access. Path: 'C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config'.
  Access to the path 'C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config' is denied.

**Comment by asalvo** [comment]
I get the same error using "sources remove".

**Comment by PatoBeltran** [comment]
Hey @fernisoites thanks for opening the issue! It is weird that nuget.exe is trying to update the config file in `C:\Program Files (x86)\NuGet\Config\`, it usually tries to write by default to the user global config found in `%appdata%\NuGet`, therefore this looks like a bug. 

Does this happen with any source or are you seeing this repro with a specific one? Also, can you give me more information about your `nuget.config` hierarchy? Do you have a `nuget.config` in `%appdata%\NuGet`? Did you recently deleted any `nuget.config` that might have make nuget confused about where to update this settings? Are you running this command from a specific directory?

Thanks!

**Comment by fernisoites** [comment]
Hey @PatoBeltran thanks for responding. I do have a `nuget.config` under `%appdata%\Nuget`, and it's just a plain placeholder nuget config without any modification. I was running the command from the root of our repo, under which there was another `nuget.config` which contains a few different Nuget feeds from several VSTS accounts, and Nuget.exe version 4.7.* failed to updated for everyone of them.

This also happened to all of our cloud builders, so I don't think it has anything to do with my machine.

Another piece of info, this was working right before the release of 4.7.*

**Comment by PatoBeltran** [comment]
I was able to repro this with nuget.exe 4.7.0, but then I tried with the latest 4.8.0 nuget.exe and it seems like it does not repro. Can you try using the latest available 4.8.0 nuget.exe and see if the issue still exists? You can get a 4.8.0 copy from https://www.nuget.org/downloads

**Comment by fernisoites** [comment]
I just tried Nuget version 4.8.0.5278, the issue still repros

**Comment by fleed** [comment]
Same issue after updating a build server from VS 2017 **15.4** to **15.8**

**Comment by PatoBeltran** [comment]
This has been solved as part of the latest rework on the nuget.configuration code paths.
