### ISSUE TITLE
Improve experiences with NU1107 install failures

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7107]

**Comment by rrelyea** [comment]
@zhili1208 - please port the fix for 1107 into release-4.8.0-rtm branch asap.

**Comment by rrelyea** [comment]
Updating title to remove 1605...since it won't ship in 4.8/15.8

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet.Client/commit/bd9167095f8e45872877cf9cee275feef38690dc
