### ISSUE TITLE
Improve customer success with NuGet operations

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7108]
Analyze the top reasons for NuGet operations (Install/Update/Restore) failures and fix them

**Comment by PatoBeltran** [comment]
Related: https://github.com/NuGet/Home/issues/7107 - Improve experiences with NU1107 install failures

**Comment by StingyJack** [comment]
@anangaur - What are you measuring "top" by?

**Comment by anangaur** [comment]
Count/% of failure rate that can be attributed to a given reason or an error code.

**Comment by StingyJack** [comment]
Please also consider stats like "average amount of time spent working around issues" or "significance of impediment".   Counts (and votes) often miss the actual impact measurement.

**Comment by jainaashish** [comment]
Sprint task completed

**Comment by StingyJack** [comment]
@jainaashish - whats this kind of issue for? There is no attached commit or other work visible and no summary to it.
