### ISSUE TITLE
Package Manager Console does not support interactive command line tools

### ISSUE THREAD

**Issue by hrumhurum** [NuGet/Home#7109]
## Details about Problem

Package Manager Console
Visual Studio 2017 version 15.7.5
OS version: Windows 10 Pro 10.0.17134.112

## Detailed repro steps so we can see the same problem

1. Open Package Manager Console from Visual Studio menu Tools --> NuGet Package Manager --> Package Manager Console

2. Type `cmd` command and hit Enter

3. Note that Package Manager Console is now hanging and no keystrokes are redirected to cmd.exe

## Actual results

* Package Manager Console becomes unresponsive

## Expected results

* Package Manager Console happily hosts interactive cmd.exe

## Other suggested things

It would be very helpful to get this working, especially since `<PackageReference>` arrival.

A typical use case: a developer installs Lisp NuGet package as a `<PackageReference>` and wants to launch Lisp REPL to try out some Lisp expressions in quick manner.

Currently there is no direct way to do that (Package Manager Console hangs just as with `cmd.exe`). As a workaround, a developer has to go to `%USERPROFILE%\.nuget` folder trying to manually locate the appropriate package and tool. This tends to be too involved and mentally consuming at times, distracting from the task at hand.

### Verbose Logs

PM> cmd
Microsoft Windows [Version 10.0.17134.112]
(c) 2018 Microsoft Corporation. All rights reserved.

<-- Package Manager Console is unresponsive at this stage -->

**Comment by PatoBeltran** [comment]
@hrumhurum thanks for opening this issue! 

This is a scenario that we don't currently support. PMC is thought of as a command line alternative to the Package Manager UI, not as a general usage shell for VS. 

I can see how enabling this scenario could be usefull so I will set this issue as a DCR in our backlog and prioritize it with our other planned work. Thanks for helping us improve the VS experience!

**Comment by jainaashish** [comment]
Sorry, We don't have enough bandwidth to get to this feature ask at this point in time and neither this aligns with our current strategy.
