### ISSUE TITLE
Searching results for packages are not consistent between All and Upgrade available filters

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#711]
Repro steps:
1. create a new MVC 5 application
2. add a feed to AspNetVnext and select it as the active package source
3. search "mvc" in All tab, then search "mvc" in Upgrade available filter

Expected: Package `Microsoft.aspnet.mvc` should be shown in the search results of "All"

Actual:
 All filter:

![1](https://cloud.githubusercontent.com/assets/1087852/7949833/42ab7344-0947-11e5-8f99-2708f749d398.PNG)

Upgrade available filter:

![2](https://cloud.githubusercontent.com/assets/1087852/7949837/4a2e5ed8-0947-11e5-92db-5d43fd3046a4.PNG)

**Comment by yishaigalatzer** [comment]
@danliu does this repro in nuget.org? This could be a server behavior

**Comment by feiling** [comment]
This is a server issue. The search request is https://www.myget.org/F/aspnetvnext/api/v2/Search()?$filter=IsAbsoluteLatestVersion&$orderby=DownloadCount%20desc,Id&searchTerm='mvc'&targetFramework='net45'&includePrerelease=true, and only Microsoft.AspNet.Mvc.Razor.Host & Microsoft.AspNet.Mvc.Common are returned.

Microsoft.AspNet.Mvc is returned if the repo is nuget.org.

**Comment by maartenba** [comment]
The filter from that URL denotes `targetFramework=net45`. When uploading the packages, MyGet extracts the supported frameworks using `NuGet.Core 2.8.6-beta-03`. This may be an issue in `NuGet.Core`, as the current result using the current `NuGet.Core` is expected behaviour.

# Root cause

## Nuspec for Microsoft.AspNet.Mvc

The `.nuspec` for `Microsoft.AspNet.Mvc`:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Microsoft.AspNet.Mvc</id>
    <version>6.0.0-beta6-14033</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>ASP.NET MVC is a web framework that gives you a powerful, patterns-based way to build dynamic websites and Web APIs. ASP.NET MVC enables a clean separation of concerns and gives you full control over markup.</description>
    <dependencies>
      <group targetFramework="DNX4.5.1">
        <dependency id="Microsoft.AspNet.Authorization" version="1.0.0-beta6-12483" />
        <dependency id="Microsoft.AspNet.Cors" version="1.0.0-beta6-10490" />
        <dependency id="Microsoft.AspNet.Mvc.ApiExplorer" version="6.0.0-beta6-14033" />
        <dependency id="Microsoft.AspNet.Mvc.Razor" version="6.0.0-beta6-14033" />
        <dependency id="Microsoft.Framework.Caching.Memory" version="1.0.0-beta6-11436" />
        <dependency id="Microsoft.Framework.DependencyInjection" version="1.0.0-beta6-11437" />
      </group>
      <group targetFramework="DNXCore5.0">
        <dependency id="Microsoft.AspNet.Authorization" version="1.0.0-beta6-12483" />
        <dependency id="Microsoft.AspNet.Cors" version="1.0.0-beta6-10490" />
        <dependency id="Microsoft.AspNet.Mvc.ApiExplorer" version="6.0.0-beta6-14033" />
        <dependency id="Microsoft.AspNet.Mvc.Razor" version="6.0.0-beta6-14033" />
        <dependency id="Microsoft.Framework.Caching.Memory" version="1.0.0-beta6-11436" />
        <dependency id="Microsoft.Framework.DependencyInjection" version="1.0.0-beta6-11437" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System.Core" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="DNX4.5.1" />
    </frameworkAssemblies>
    <licenseUrl>http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm</licenseUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <copyright>Copyright © Microsoft Corporation</copyright>
    <projectUrl>http://www.asp.net/</projectUrl>
  </metadata>
</package>
```

Calling into `LocalPackage.GetSupportedFrameworks()` yields: `DNX4.5.1|DNXCore5.0`

## Nuspec for Microsoft.AspNet.Mvc.Common

The `.nuspec` for `Microsoft.AspNet.Mvc.Common`:

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Microsoft.AspNet.Mvc.Common</id>
    <version>6.0.0-beta6-14033</version>
    <authors>Microsoft</authors>
    <owners>Microsoft</owners>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>Microsoft.AspNet.Mvc.Common</description>
    <dependencies>
      <group targetFramework="DNXCore5.0">
        <dependency id="System.Runtime" version="4.0.20-beta-22913" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="System.Core" targetFramework="DNX4.5.1" />
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="DNX4.5.1" />
    </frameworkAssemblies>
    <licenseUrl>http://www.microsoft.com/web/webpi/eula/net_library_eula_enu.htm</licenseUrl>
    <iconUrl>http://go.microsoft.com/fwlink/?LinkID=288859</iconUrl>
    <copyright>Copyright © Microsoft Corporation</copyright>
    <projectUrl>http://www.asp.net/</projectUrl>
  </metadata>
</package>
```

Calling into `LocalPackage.GetSupportedFrameworks()` yields: `.NETFramework4.5|DNX4.5.1|DNXCore5.0`

## Query with tragetFramework=net45

Calling into `VersionUtility.IsCompatible()` yields:

* `Microsoft.AspNet.Mvc` (`DNX4.5.1|DNXCore5.0`) compatible with `net45`? `false`
* `Microsoft.AspNet.Mvc.Common` (`.NETFramework4.5|DNX4.5.1|DNXCore5.0`) compatible with `net45`? `true`

May need fixing in `NuGet.Core 2.8.6-beta-03` (@emgarten?)

**Comment by emgarten** [comment]
Would it be possible to move search to NuGet.Frameworks? The compatibility checks for UAP and dotnet are a bit more complicated and I don't see those ever being added into NuGet.Core. Right now NuGet.Core understands how to parse dnx, uap, and dotnet, but outside of this search scenario there is nothing using it for compatibility.

**Comment by maartenba** [comment]
Which feed is the most stable one for NuGet.Frameworks? We'll be taking this to production if we add it...

(is it safe to assume net45 when dnx451 is present?)

**Comment by emgarten** [comment]
Dev and 3.0-rtm should be the same code for NuGet.Frameworks. I would use Dev, NuGet.Frameworks is kept very stable since it is used everywhere.

It is safe to assume net45 for dnx45 and up.  dnx451 -> net451 -> net45

**Comment by maartenba** [comment]
In NuGet.Frameworks, what's the best call to get the supported frameworks from a package? And what's the best call to check compatibility?

**Comment by emgarten** [comment]
GetSupportedFrameworks() matches the old behavior on PackageReader
https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Packaging/PackageReaderBase.cs#L58

You can use IsCompatible from the default compatibility provider to see if any of the returned frameworks are compatible.
https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Frameworks/CompatibilityProvider.cs#L32
https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Frameworks/DefaultCompatibilityProvider.cs#L15

The CompatibilityTable might be useful also, it was created for search to use in determining the full matrix of compatible frameworks to packages.
https://github.com/NuGet/NuGet3/blob/dev/src/NuGet.Frameworks/CompatibilityTable.cs

**Comment by maartenba** [comment]
Fixing this in the laziest way possible for now, switching to the SDK has quite a big impact on our codebase as a lot of calls (unrelated to target fx) are different from how it was done in `NuGet.Core`.

```
if (package.SupportedFrameworks.Contains("DNX4.5.1") && !package.SupportedFrameworks.Contains(".NETFramework4.5"))
{
    package.SupportedFrameworks = ".NETFramework4.5|" + package.SupportedFrameworks;
}
```

**Comment by maartenba** [comment]
Does NuGet.Core 2.8.6 detect UWP?
