### ISSUE TITLE
nuget.exe push failed with 400 (Bad request) error

### ISSUE THREAD

**Issue by msaraf1** [NuGet/Home#7110]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):v4.7.0

dotnet.exe --version (if appropriate):

VS version (if appropriate):2017

OS version (i.e. win10 v1607 (14393.321)):win10

Worked before? If so, with which NuGet version:No

## Detailed repro steps so we can see the same problem

1.nuget push .nupkg -Source Artifactory
response status code does not indicate success 400 (Bad Request)

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by PatoBeltran** [comment]
Hey @msaraf1 thanks for opening the issue! I'm trying to understand and reproduce your issue but I haven't had any success. Can you please give me more information about your scenario? [Here](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-push) is the documentation for the nuget push command.

How was the package you are trying to push generated? Is the name of the package empty (only ".npkg") ? What source are you trying to push to? Are you sure it supports pushing packages to it? Does this happen only with a specific package? I would love to have enough information that can make me reproduce this behavior and investigate any issue in our product!

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by CrazyPyro** [comment]
This will happen if you try to push the same version number more than once.  https://alastaircrabtree.com/400-bad-request-when-pushing-a-package-to-octopus-deploy-using-nuget-push/
