### ISSUE TITLE
Multiple definitions for target during auto packaing

### ISSUE THREAD

**Issue by singku** [NuGet/Home#7113]
I have been searching around but can't find a solution for following example:
```
targets {
    [tag]
    Defines += MACRO_ONE;
}
```
Above scripts can defines a single macro to target. How can I define more than one? Is following the correct way?
```
targets {
    [tag]
    Defines += MACRO_ONE;
    Defines += MACRO_TWO;
}

**Comment by PatoBeltran** [comment]
Hey @singku I think you opened this issue by mistake since I'm not familiar with the scripting you are talking about. Can you please clarify how is this related to NuGet tools? Thanks!

**Comment by rohit21agrawal** [comment]
closing due to lack of response. please feel free to reactive if needed.

**Comment by singku** [comment]
It turns out that in following content in .autopkg file:
```
targets {
    [dynamic]
    Defines += MACRO_ONE;
    [dynamic]
    Defines += MACRO_TWO;
}
```

Can help defining multiple preprocessors macros for you.

**Comment by rohit21agrawal** [comment]
autopkg is not owned by nuget .please file an issue on their repository: https://github.com/autopkg/autopkg

**Comment by singku** [comment]
I mean the packaging specification when writing a Nuget package. Sorry for the confusion.
