### ISSUE TITLE
To fix `NuGet update self` NuGet.Commandline nupkg should not be semver2.0

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7116]
Currently it is https://www.nuget.org/packages/NuGet.CommandLine/4.7.0. 

This prevents updates from clients `< 4.3` to 4.7.0. 

//cc @rrelyea 

//cc @NuGet/nuget-client

**Comment by emgarten** [comment]
Wouldn't 4.2 clients update to 4.6 and then update the next time to 4.7?

**Comment by nkolev92** [comment]
@emgarten 
Yeah that's true. 

It's just inconvenient :)

**Comment by pascalberger** [comment]
@emgarten I for example consume the package through Chocolatey which doesn't handle semver2 yet. So SemVer2 might not be an issue for people consuming it through nuget.exe, but there might also be other clients which are more of an issue.

**Comment by jainaashish** [comment]
this is not just inconvenient, it actually doesn't work. NuGet.exe can't update self from 4.6.2 to 4.7.0 since self-updater still uses V2 api which doesn't support semver2. 

So we have to publish `NuGet.Commandline 4.7.0` without `semver2`

**Comment by nkolev92** [comment]
Related: https://github.com/NuGet/Home/issues/4197

Self updater uses the CoreV2 APIs. 

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Common/SelfUpdater.cs

**Comment by pascalberger** [comment]
@jainaashish Thanks for fixing this. Do you plan to also publish a version of `nuget.commandline` 4.7 without metadata to nuget.org or will this only be fixed with the next release?

**Comment by jainaashish** [comment]
Yes, we're working towards that and will be done in next couple of days.

**Comment by jainaashish** [comment]
Done
