### ISSUE TITLE
[Test Failure] Fail to install NuGet Client Dev 5.0.0.5339 into D16.0stg 27913.3000

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7119]
## Details about Problem
NuGet version: NuGet Client Dev 5.0.0.5339
VS Version: D16.0stg 27913.3000
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps
1.	Instll OS “RS4_Release 17134.1.180410-1804” into a clean machine.
2.	Run “preinstall.cmd”.
3.	Install VS: d16.0stg 27913.3000 (Enterprise).
4.	Install NuGet Client Dev 5.0.0.5339 on top of d16.0stg as "VsTargetBranch" (in buildinfo.json file) said.
## Expected
Installation is successful.
## Actual
Fail to install NuGet Client Dev 5.0.0.5339 into D16.0stg 27913.3000 as below screenshot.
![failtoinstallnuget](https://user-images.githubusercontent.com/20632625/42744951-9696416e-88bf-11e8-965e-88a8c5b30182.png)
## Install Log
7/15/2018 10:36:37 PM - Microsoft VSIX Installer
7/15/2018 10:36:37 PM - -------------------------------------------
7/15/2018 10:36:37 PM - vsixinstaller.exe version:
7/15/2018 10:36:37 PM - 15.8.3204
7/15/2018 10:36:37 PM - -------------------------------------------
7/15/2018 10:36:37 PM - Command line parameters:
7/15/2018 10:36:37 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\v-luzh\Desktop\5.0.0.5339\artifacts\VS15\NuGet.Tools.vsix
7/15/2018 10:36:37 PM - -------------------------------------------
7/15/2018 10:36:37 PM - Microsoft VSIX Installer
7/15/2018 10:36:37 PM - -------------------------------------------
7/15/2018 10:36:37 PM - Initializing Install...
7/15/2018 10:36:38 PM - Extension Details...
7/15/2018 10:36:38 PM - 	Identifier         : NuGet.72c5d240-f742-48d4-a0f1-7016671e405b
7/15/2018 10:36:38 PM - 	Name               : NuGet Package Manager for Visual Studio 2017
7/15/2018 10:36:38 PM - 	Author             : Microsoft Corporation
7/15/2018 10:36:38 PM - 	Version            : 15.0.50000.5339
7/15/2018 10:36:38 PM - 	Description        : A collection of tools to automate the process of downloading, installing, upgrading, configuring, and removing packages from a VS Project.
7/15/2018 10:36:38 PM - 	Locale             : en-US
7/15/2018 10:36:38 PM - 	MoreInfoURL        : 
7/15/2018 10:36:38 PM - 	InstalledByMSI     : False
7/15/2018 10:36:38 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
7/15/2018 10:36:38 PM - 
7/15/2018 10:36:39 PM - 	SignatureState     : ValidSignature
7/15/2018 10:36:39 PM - 	SignedBy           : Microsoft Corporation
7/15/2018 10:36:39 PM - 	Certificate Info   : 
7/15/2018 10:36:39 PM - 		-------------------------------------------------------
7/15/2018 10:36:39 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
7/15/2018 10:36:39 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
7/15/2018 10:36:39 PM - 		[Serial Number] : 33000001FC5DB8191027A666C10000000001FC
7/15/2018 10:36:39 PM - 		[Not Before]    : 10/5/2017 11:26:08 AM
7/15/2018 10:36:39 PM - 		[Not After]     : 10/5/2018 11:26:08 AM
7/15/2018 10:36:39 PM - 		[Thumbprint]    : 5E940B33DEAE5945F506ADAB946A997867A40FEF
7/15/2018 10:36:39 PM - 
7/15/2018 10:36:39 PM - 	Supported Products : 
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.Pro
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.Community
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.VWDExpress
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.VPDExpress
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.VSWinExpress
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 		Microsoft.VisualStudio.VSWinDesktopExpress
7/15/2018 10:36:39 PM - 			Version : [15.0,16.0)
7/15/2018 10:36:39 PM - 
7/15/2018 10:36:39 PM - 	References         : 
7/15/2018 10:36:39 PM - 	Prerequisites      : 
7/15/2018 10:36:39 PM - 		-------------------------------------------------------
7/15/2018 10:36:39 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/15/2018 10:36:39 PM - 		Name         : Visual Studio core editor
7/15/2018 10:36:39 PM - 		Version      : [15.0,16.0)
7/15/2018 10:36:39 PM - 
7/15/2018 10:36:39 PM - Signature Details...
7/15/2018 10:36:39 PM - 	Extension is signed with a valid signature.
7/15/2018 10:36:39 PM - 
7/15/2018 10:36:39 PM - Searching for applicable products...
7/15/2018 10:36:39 PM - Found installed product - Global Location
7/15/2018 10:36:39 PM - Found installed product - Visual Studio Enterprise 16 d16.0stg
7/15/2018 10:36:39 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by nkolev92** [comment]
The extension manifest says which versions are compatible. 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Client/source.extension.vs15.vsixmanifest

This is part of the cleanup prepping 15.x to 16.x migration. 

We might need to update the dependencies and the SDK used to build the VSIX. 
//cc @NuGet/nuget-client

**Comment by v-luzh** [comment]
Fixed on NuGet Client Dev 5.0.0.5346.
