### ISSUE TITLE
UpgradeAvailable filter is showing the latest stable version as the default, although include prerelease has been checked

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#712]
Repro steps:
1. create a new MVC5 application
2. go to upgrade available tab with api.nuget.org
3. select EntityFramework

Expected: version 7.0.0-beta4 is displayed in Version combobox

Actual: latest stable 6.1.3 is displayed, whereas the package has a prerelease tag on the list

![3](https://cloud.githubusercontent.com/assets/1087852/7950012/ac93d664-0949-11e5-8d70-d13cf34be9e2.png)

**Comment by yishaigalatzer** [comment]
This is based on user feedback
