### ISSUE TITLE
Is periodically deleting the `project.assets.json` (the whole obj folder) going to cause problems for nuget?

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#7120]
Per [this comment](https://github.com/NuGet/Home/issues/7098#issuecomment-404984941)
> ...there is the concept of the project.assets.json file (it is under the obj/ directory). This file has all the information about the dependencies (top level and transitive) references in a given project and where they are stored.

In order to get a _clean_ build with as little reference "help" from VS as possible, it is required that I delete the bin/obj folders prior to building the solution/project. Is periodically deleting this `project.assets.json` going to be a problem?

**Comment by mishra14** [comment]
@StingyJack Please help us understand your requirement here.
>In order to get a clean build with as little reference "help" from VS as possible, it is required that I delete the bin/obj folders prior to building the solution/project. 

What are you trying to do here?
NuGet has options to force restore via `nuget restore -force` or `dotnet restore --force`.

**Comment by StingyJack** [comment]
Visual Studio has always had the habit of finding a referenced library for a project when one was not where the project thought it should be. Sometimes that's useful and sometimes its led to broken deployments.   In order to check that behavior periodically I'll either manually delete the bin/obj folders or run a script like [this one](https://github.com/StingyJack/Vs-Utility/blob/master/Remove-SolutionOutputs.ps1) to cleanse **all** project outputs (not just the active configuration).  This way when I build, any reference issues are immediately visible. 

I typically delete the bin and obj folders and do a clean build at least once before a checkin. Will this new file recreate itself properly if I delete it?

**Comment by mishra14** [comment]
Thanks for linking the script that you run. I am not sure what `Remove-AllProjectOutput` does. But I will leave that to you. To answer your question, yes , the file will be recreated the next time you execute `nuget restore` on the solution/projects. But if you delete the file then `intellisense` may not work inside Visual Studio will you run a restore.

I would recommend that you run the following after running your script to ensure that your project restores and builds fine before deployment  - 

`nuget restore <solution_file> -force`
`msbuild /t:rebuild <solution_file>`

Let us know if you have any more questions.

**Comment by StingyJack** [comment]
That script cleans all output paths for a project. MSB/VS clean only affects the active configuration.

Thanks for the tip about intellisense storing files there. I remember reading that the obj folder was for transient compilations, which is why I was deleting it entirely. I'll add an exclusion for that and this file, and anything else that isn't a direct part of a compilation.
