### ISSUE TITLE
Feature Request: Add dotnet nuget list cli

### ISSUE THREAD

**Issue by peterhuene** [NuGet/Home#7121]
_From @divinebovine on July 9, 2018 19:37_

This is a feature request to add the listing capability from the nuget cli. Currently there is no way to use the dotnet cli to query a nuget server for a list of available packages with their versions. It would be nice to be able to do this so CI tools can check to make sure a push won't overwrite existing packages.

_Copied from original issue: dotnet/cli#9623_

**Comment by nkolev92** [comment]
Duplicate of https://github.com/NuGet/Home/issues/6060
