### ISSUE TITLE
please automatically update dependencies in .nuspec file when update package reference by Nuget Manager

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#7123]
@softboy99 commented on [Fri Jul 13 2018](https://github.com/NuGet/NuGetGallery/issues/6164)

please automatically update dependencies in .nuspec file when update package reference by Nuget Manager,Otherwise, when forget to update the dependencies in .nuspec file manually, after package builded and published, it will cause the MSBuild runtime error for loading the old version dependency when this package being used.

**Comment by rohit21agrawal** [comment]
thanks for the feedback @softboy99 . For now, we do not have this planned in our backlog, however, if we receive more feedback on this in the future, we will reconsider the need for this feature.

**Comment by rohit21agrawal** [comment]
c

**Comment by kosist** [comment]
> thanks for the feedback @softboy99 . For now, we do not have this planned in our backlog, however, if we receive more feedback on this in the future, we will reconsider the need for this feature.

One more feedback on this topic :) Would be really nice to have such feature...

**Comment by nkolev92** [comment]
@kosist 

If you're using PackageReference, and the dotnet pack or msbuild /t:pack commands, then all of this is automatically managed: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack.

**Comment by softboy99** [comment]
Is this available for dotnet framework project?

**Comment by nkolev92** [comment]
It is available for PackageReference projects, https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files. 

Most project types, exclude ASP.NET Framework & C++, can migrate to PackageReference, https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference after which you can do https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild.

**Comment by kosist** [comment]
> It is available for PackageReference projects, https://learn.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files.
> 
> Most project types, exclude ASP.NET Framework & C++, can migrate to PackageReference, https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference after which you can do https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild.

msbuild allows to build one nuget per project. In my case, I'd like to pack multiple projects into single nuget. Is it still possible to pull project's dependencies into that nuget please? So my main concern is about use case, when multiple projects are packed into single nuget package...

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/3891 is tracking the work of packing multiple projects and there are some workarounds there. 
There's a proposal for that, but there's also a good amount of feedback why this should be done with a lot of care: https://github.com/NuGet/Home/pull/11708#pullrequestreview-1049965684.
