### ISSUE TITLE
Allow uploading certificates with PEM encoding using CRT files.

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#7125]
Most CA's share public keys in PEM format using CRT files, but NuGet.org only accepts .CER files in DER format. 

Users must import/export or convert the certificate from one format to another.

/cc @onovotny

**Comment by joelverhagen** [comment]
Today we only support DER encoded.

Another common format is base64 encoded, e.g.

```
-----BEGIN CERTIFICATE-----
base64stuffhere==
-----END CERTIFICATE-----

**Comment by joelverhagen** [comment]
Issue moved to [NuGet/NuGetGallery #6178](https://github.com/NuGet/NuGetGallery/issues/6178) via [**ZenHub**](https://www.zenhub.com/)
