### ISSUE TITLE
TFVC + VS 2017 + VS expects to see the manually deleted solution level packages folder

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7127]
@Rod-in-NM commented on [Tue Jul 17 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/983)

I have been struggling with this issue. I wasn't able to check in the project into TFVC. I talked with our TFS admin. He said that even though I had manually deleted the packages folder, VS 2017 still thought that the packages folder existed, at least as a part of the solution. I had to Undo packages and all of the files under it, before VS would let me check it in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d965aea9-a6cc-06da-a347-6e8c89458c98
* Version Independent ID: 6775f211-f4b6-6d0c-6f2e-6664b3e9721e
* Content: [NuGet Packages and Source Control](https://docs.microsoft.com/en-us/nuget/consume-packages/packages-and-source-control#omitting-packages-with-team-foundation-version-control)
* Content Source: [docs/consume-packages/Packages-and-Source-Control.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Packages-and-Source-Control.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
@Rod-in-NM 

Are you able to reproduce this consistently?
Anything you can point us to, to help us investigate?

**Comment by Rod-in-NM** [comment]
No @nkolev92, I'm not able to reliably reproduce this problem, sorry.

**Comment by nkolev92** [comment]
Thanks for getting back @Rod-in-NM. 
If you do notice a pattern, please let us know what you've done. 
Unfortunately these issues are difficult to fix without a scenario.

**Comment by karann-msft** [comment]
Let's reopen this issue if we get a repro / more info.
