### ISSUE TITLE
It will require admin rights

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7128]
@vivekwaghmare commented on [Wed Jul 18 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/984)

On some installations specially in enterprise setup of Domain(active directory) nuget.exe may not work correctly if not ran with admin rights. I was expecting it to be documented. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd704fe8-fd6e-ba7f-6021-15f280657f4d
* Version Independent ID: dc047102-284f-ad70-99ee-dac5be511392
* Content: [NuGet CLI sources command](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sources)
* Content Source: [docs/tools/cli-ref-sources.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/tools/cli-ref-sources.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

---

@karann-msft commented on [Wed Jul 18 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/984#issuecomment-406164446)

@vivekwaghmare what is the scenario? Can you provide steps to repro the issue?

**Comment by rrelyea** [comment]
@vivekwaghmare - we'd love more details. Can you tell us how to reproduce the problem? What happens? Should we change our behavior, or just documentation?

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
