### ISSUE TITLE
PackageDependencyResolution: JoinItems task failed: Path too long

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#7132]
MSBuild: 15.8.160-preview+gaf9d27ba72
15.8.160.40367
VS Version: 15.8.0 Preview 5.0 [27917.1.d15.8]

Repro project:
\\mlangfs1\public\kirillo\NuGetJoinItemsPathTooLong\ddafsdsadfs.zip

Build using MSBuild (zip contains .binlog). You get error:
```
C:\Program Files\dotnet\sdk\2.1.400-preview-009088\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(421,5): error MSB4018: The "JoinItems" task failed unexpectedly.
System.InvalidOperationException: The item metadata "%(FileName)" cannot be applied to the path "C:\Program Files\dotnet\sdk\2.1.400-preview-009088\Sdks\Microsoft.NET.Sdk\targets\..\..\..\..\NuGetFallbackFolder\microsoft.aspnetcore.server.kestrel.transport.abstractions\2.0.0\lib\netstandard2.0\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInvalidOperation(String resourceName, Object[] args)
   at Microsoft.Build.Shared.FileUtilities.ItemSpecModifiers.GetItemSpecModifier(String currentDirectory, String itemSpec, String definingProjectEscaped, String modifier, String& fullPath)
   at Microsoft.Build.Evaluation.BuiltInMetadata.GetMetadataValueEscaped(String currentDirectory, String evaluatedIncludeBeforeWildcardExpansionEscaped, String evaluatedIncludeEscaped, String definingProjectEscaped, String name, String& fullPath)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetBuiltInMetadataEscaped(String name)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadataEscaped(String metadataName)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.GetMetadata(String metadataName)
   at Microsoft.NET.Build.Tasks.JoinItems.<>c__DisplayClass32_0.<ExecuteCore>b__0(ITaskItem item)
   at System.Linq.Enumerable.<JoinIterator>d__38`4.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.NET.Build.Tasks.JoinItems.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [C:\Users\toddgrun\Documents\Projects\ddafsdsadfs\ddafsdsadfs\ddafsdsadfs.csproj]
```

This is because the paths in question (Item `ResolvedCompileFileDefinitions`) are too long (261 characters). They are an output of the `ResolvePackageAssets` task. 

Our understanding is that the long paths are coming from the project.assets.json file (included in the .zip). In fact here's what we see there:

```
  "packageFolders": {
    "C:\\Users\\kirill\\.nuget\\packages\\": {},
    "C:\\Program Files\\dotnet\\sdk\\2.1.400-preview-009088\\Sdks\\Microsoft.NET.Sdk\\targets\\..\\..\\..\\..\\NuGetFallbackFolder": {}
  },
```

We think that the path that contains `..\..\..\` should be shortened using Path.GetFullPath() at some point, but we don't know where's the best place to make this change.

**Comment by KirillOsenkov** [comment]
cc @toddgrun

**Comment by rainersigwald** [comment]
Related: Microsoft/msbuild#53. cc @ccastanedaucf.

**Comment by ccastanedaucf** [comment]
I know over in MSBuild [FileUtilities](https://github.com/Microsoft/msbuild/blob/7d8c8da147252ea57f35d2c6ceee8e7c5ba458f5/src/Shared/FileUtilities.cs#L915) we have an ```AttemptToShortenPath()``` method for conditionally using ```Path.GetFullPath()``` to avoid failing in situations like this. If it's not necessary to keep the original path, I'm thinking replacing the 4 ```FileUtilities.FixFilePath()``` calls that set ```itemSpec``` [here](https://github.com/Microsoft/msbuild/blob/7d8c8da147252ea57f35d2c6ceee8e7c5ba458f5/src/Build/Instance/ProjectItemInstance.cs#L808) and [here](https://github.com/Microsoft/msbuild/blob/7d8c8da147252ea57f35d2c6ceee8e7c5ba458f5/src/Utilities/TaskItem.cs#L82) would work and also prevent this from popping up elsewhere.

**Comment by KirillOsenkov** [comment]
Looks like this might be a dupe or related: https://github.com/dotnet/sdk/issues/2132

**Comment by zhili1208** [comment]
this is not an issue in NuGet. close it as a dup

**Comment by KirillOsenkov** [comment]
@zhili1208 please reactivate. We think it's NuGet who needs to normalize the paths when writing to project.assets.json.

**Comment by nkolev92** [comment]
It's weird that it's not getting normalized. 

Which client generates the assets file? (dotnet or VS)

Related code for the cmd tools [here](https://github.com/NuGet/NuGet.Client/blob/deab84db30cbd8cc738cd46ad694aebdbb43a1cf/src/NuGet.Core/NuGet.Build.Tasks/GetRestoreSettingsTask.cs#L149)

**Comment by KirillOsenkov** [comment]
We think it's VS restore. Adding @mrward for VSMac NuGet restore.

**Comment by nkolev92** [comment]
Thanks @KirillOsenkov 
Code [here](https://github.com/NuGet/NuGet.Client/blob/c76681f6400c0b2883543ba6a911abcbc9e7bfc8/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Utility/VSRestoreSettingsUtilities.cs#L104)

This probably has something to do with the fact that Uri is being used for path combination. 

https://github.com/NuGet/NuGet.Client/blob/deab84db30cbd8cc738cd46ad694aebdbb43a1cf/src/NuGet.Core/NuGet.Common/UriUtility.cs

I faced similar problems in https://github.com/NuGet/NuGet.Client/pull/2283

//cc @rrelyea

**Comment by rrelyea** [comment]
Do we know what has changed here?
Clearly this will get a little better when 2.1.400 ships (it will no longer have "-preview-009088")
Is this a change in the 2.1.400 encoding of the fallbackfolder path?
etc...

**Comment by KirillOsenkov** [comment]
Our theory is that some component of the path got longer by one character. It could be the version of one of the referenced NuGet packages, the version number got another digit, or literally anything else. The offending path that breaks us is 261 characters long (can you believe this?)

**Comment by KirillOsenkov** [comment]
Basically, we were getting lucky all the time previously, but as our version numbers grow the inevitable has happened ;)

**Comment by rrelyea** [comment]
We plan to take this early in 15.9, however it won't actually be a problem for 15.8, since "-preview-009088" will not be used in that build.
It will impact 15.9-preview-xxxxxx though.

A bit afraid of changing our path combination code last minute for something that won't actually impact 15.8 users.

**Comment by rrelyea** [comment]
I should correct myself. We plan to investigate this for possible inclusion in 15.9 -- depending on what we find.

**Comment by KirillOsenkov** [comment]
Please let me know once you have a candidate fix, regardless of the ship vehicle - I suspect it should be a single Path.GetFullPath() in one place, but I'd like to be sure.

**Comment by zhili1208** [comment]
@mrward the project.asset.json file is created by monodevelop, Nuget normalize the path, I can't repro same issue, in VS 2017. msbuild.  any ideas?

**Comment by KirillOsenkov** [comment]
I'm not sure monodevelop is involved. This reproduces with restore using nuget.exe and command-line build using MSBuild, but maybe the project.assets.json was written by MonoDevelop?

**Comment by zhili1208** [comment]
@KirillOsenkov Do you have a repro which only use nuget.exe/msbuild restore the project and get the path in project.asset.json. I worked with @ToddGrun yesterday, the asset file is produced by monodevelop in his repro

**Comment by zhili1208** [comment]
I found the code https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs#L950 in monodevelop,  monodevelop created the PackageSpec which includes unnormalized fallback folder path.

**Comment by KirillOsenkov** [comment]
You're right, I couldn't repro with just command line. So it's a monodevelop bug indeed! Thanks for looking. Feel free to close this issue and i'll open a corresponding one against MonoDevelop.

**Comment by nkolev92** [comment]
Nice catch @zhili1208.

**Comment by KirillOsenkov** [comment]
@zhili1208 thank you very much for helping root cause this. Much appreciated.

**Comment by zhili1208** [comment]
Great, since this bug is not in nuget side, close it as external
