### ISSUE TITLE
Add NuGet.exe to the Developer Command Prompt

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#7133]
Please make NuGet.exe available from the Visual Studio Developer Command Prompt. It's a commonly needed tool and the expectation is that `msbuild`, `dotnet` and `nuget` just work from the command prompt.

**Comment by zhili1208** [comment]
is there any reason for this? we expect dotnet can replace nuget.exe in the future.

**Comment by KirillOsenkov** [comment]
Nuget.exe is a very useful tool used by millions of developers daily, it works for packages.config, project.json and PackageReferences. This need isn't going away anytime soon. Every time I'm on someone's machine helping someone, they take a long time to find NuGet.exe and run it.

There are situations where NuGet.exe works, but `msbuild /r` or `dotnet restore` don't.

Most of the users don't complain, so consider me being a voice to represent them. Thanks!

**Comment by dotMorten** [comment]
Agreed. This has always boggled my mind:
![image](https://user-images.githubusercontent.com/1378165/99583670-ba29c700-2998-11eb-9762-817092c92e08.png)

> we expect dotnet can replace nuget.exe in the future.

Two years later, and it's still not a full replacement (no signing support for instance). Also I doubt it'll ever apply to C++'s `.vcxproj` projects that uses nuget packages too.

**Comment by timheuer** [comment]
Signing is my wish to @dotMorten https://github.com/NuGet/Home/issues/9006

**Comment by dotMorten** [comment]
@timheuer Agreed it's one of the two reasons I use nuget.exe. The other is I use nuget packages in my C++ projects, and they need explicit restore with nuget.exe or the msbuild-based CI build fails.

**Comment by dotMorten** [comment]
@timheuer Signing now works with "`dotnet nuget sign`". So it's probably just C++ projects left where we need this.

**Comment by KirillOsenkov** [comment]
nuget.exe is still needed for two important scenarios:

nuget pack custom.nuspec
nuget push

**Comment by timheuer** [comment]
> nuget.exe is still needed for two important scenarios:
> 
> nuget pack custom.nuspec 

`dotnet pack myproj.csproj /p:NuspecFile=custom.nuspec`

> nuget push

`dotnet nuget push ...`

Solved?

**Comment by KirillOsenkov** [comment]
Not really. I don't want to have `myproj.csproj`. It's not a C# project. The fact that you need to have `myproj.csproj` to pack is a hack.

**Comment by nkolev92** [comment]
Correlating this issue to https://github.com/NuGet/Home/issues/4254. 

I think it'd be great if https://github.com/NuGet/Home/issues/4254 is completed over this.

**Comment by KirillOsenkov** [comment]
#4254 would solve nuget pack, but it wouldn’t solve nuget push and nuget list.

**Comment by zivkan** [comment]
[`dotnet nuget push`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) has existed since .NET Core 3.1 SDK. I'm not aware of any functionality differences between `dotnet nuget push` and `nuget.exe` push, except that the dotnet CLI uses more GNU style arguments, whereas nuget.exe uses PowerShell style arguments. But there's a 1:1 mapping between the two.

https://github.com/NuGet/Home/issues/6060 is the proposed replacement for list

**Comment by dotMorten** [comment]
@civkan package signing is one difference and I think there might be a few more. And it’s weird to use dotnet nuget to restore nuget packages for c++ projects (don’t even think that would work)

**Comment by zivkan** [comment]
does `msbuild -t:restore -p:RestorePackagesConfig=true` work? https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-msbuild.

[`dotnet nuget sign`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-sign) was added in the .NET 6 SDK.

**Comment by nkolev92** [comment]
I took a look at *all* the NuGet.exe commands and generated a table for the behaviors


| Command Name | Description | NuGet.exe | dotnet.exe | msbuild.exe | Notes |
|--------------|-------------|-----------|------------|-------------|-------|
| add | add package to hierarchical source | Yes | [No](https://github.com/NuGet/Home/issues/12004) | N/A | Parity not reached. No community asks I could find. |
| client-certs | Client certs management | Yes | Yes | N/A | Full parity. |
| config | Individual config items management | Yes | [No](https://github.com/NuGet/Home/issues/10294). Community ask in [4855](https://github.com/NuGet/Home/issues/4855) | N/A |  No parity. |
| delete | Unlist package | Yes | Yes | N/A | Full Parity |
| init | init packages to a hierarchical source | Yes | [No](https://github.com/NuGet/Home/issues/12004) | N/A | Parity not reached. No community asks I could find. |
| install | Downloads a package and it's dependencies or run restore | Yes | Partially. No community ask for the install package. | N/A | Parity not reached. Not community asks for this |
| list | Search in sources | Yes | [No](https://github.com/NuGet/Home/issues/6060) | N/A |  No parity. |
| locals | local folders and caches | Yes | Yes | N/A | Full parity |
| pack | pack nuspec/csproj | Yes | Yes [4254](https://github.com/NuGet/Home/issues/4254) is a gap. | Yes, msbuild will only ever support PackageReference pack. | Parity not reached. Scenario without parity has an easy workaround. |
| push | push package | Yes | Yes | N/A | Full parity |
| restore | restore package | Yes, both PR & PC | Yes (no PC support) | Yes, both PR and PC, PC is [opt-in](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-msbuild) | Scoped parity. What this means is that dotnet.exe does not support old style, so there's no point to add restore support for that there. |
| search | Search in sources | Yes | [No](https://github.com/NuGet/Home/issues/6060) | N/A | No parity. |
| setapikey | set api key in config | Yes | [No](https://github.com/NuGet/Home/issues/6437) | N/A | No parity |
| sign | Sign package | Yes | Yes | N/A | Full parity |
| sources | manage sources | Yes | Yes | N/A | Full parity |
| spec | creates nuspec | Yes | No | N/A | No community asks |
| trusted-signers | manage trusted signers config | Yes | Yes | N/A | yes |
| update | updates | Yes | [No](https://github.com/NuGet/Home/issues/4103) | N/A | Not full parity, but the commands will work totally differently. Think packages.config vs PR. nuget.exe update never worked 100% correctly. |
| verify | verify packages | Yes | Yes | N/A | Full parity |

Digesting the above table leads to the following list of relevant community requested issues, related to pack nuspec, setapikey, config, update and search commands

- https://github.com/NuGet/Home/issues/4855
- https://github.com/NuGet/Home/issues/4254
- https://github.com/NuGet/Home/issues/6060
- https://github.com/NuGet/Home/issues/6437
- https://github.com/NuGet/Home/issues/4103

**Comment by dotMorten** [comment]
Even if the feature gap was closed, it still seems rather silly to me that you have to install the dotnet 6+ sdk just to restore or create nuget packages for non-dotnet projects (C++, .NET Framework etc).

**Comment by nkolev92** [comment]
Team Triage: 
NuGet.exe can be downloaded from https://www.nuget.org/downloads. At this point we do not have any plans to add NuGet.exe to Visual Studio.

**Comment by fowl2** [comment]
Many, many components currently bundled with Visual Studio are downloadable separately.  I'm not sure that's a compelling reason.

Note that "being able to run the command you found in the article you found online" and "not learn an alternative syntax" are a features not listed in the above table :)
