### ISSUE TITLE
dotnet restore doesn't restore if dependencies present

### ISSUE THREAD

**Issue by MicahZoltu** [NuGet/Home#7138]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `dotnet restore`

NuGet version (x.x.x.xxx): Unknown

dotnet.exe --version (if appropriate): `dotnet 2.1.302`

OS version (i.e. win10 v1607 (14393.321)): Windows 10

Worked before? If so, with which NuGet version: Unknown

## Detailed repro steps so we can see the same problem

1. Clone https://gist.github.com/MicahZoltu/62fa172a4a3e9bfa6083f77de1155111
2. dotnet restore tests.csproj
3. **Notice that tests project is not restored, which means its dependencies are not fetched.**
4. Remove `<ProjectReference>` from `test.csproj`
5. dotnet restore tests.csproj
5. **Notice that the tests project is now restored.**

### Verbose Logs

https://gist.github.com/MicahZoltu/156019f9dee6399389331d739543b627

### Sample Project

https://gist.github.com/MicahZoltu/62fa172a4a3e9bfa6083f77de1155111

**Comment by rrelyea** [comment]
dotnet SDK based projects don't currently support restoring to a shared obj directory.
If you move your test project to another directory, do things work?

**Comment by MicahZoltu** [comment]
Yes.  In that case, I should be given way more feedback on the problem.  The failure is silent and it took me 30 minutes before I realized restore wasn't working and another hour before I figured out enough of "why" that I could file this bug (I ended up creating a repro case to troubleshoot).

If NuGet would have just told me "need separate object folders for restore" I would have saved a lot of time.

**Comment by nkolev92** [comment]
You can do restore independently for different projects. 
NuGet cannot really suggest that unfortunately. 
What we can do is make the assets file better to work with shareable intermediates Please follow this issue for that https://github.com/NuGet/Home/issues/4463.
