### ISSUE TITLE
NuGet Restore (and more) broken in build tools SKU (missing NuGet.Credentials.dll in install)

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7144]
In https://github.com/NuGet/NuGet.Client/pull/2080, NuGet.Credentials was made cross-plat. 
In https://github.com/NuGet/NuGet.Client/pull/2126, the NuGet.Credentials assembly started being loaded by msbuild.exe and dotnet.exe. 

However it wasn't added in the build tools SKU VSIX and because of that any operation, including simple restores,  will fail with:
```
Could not load file or assembly 'NuGet.Credentials, Version=4.8.0.5, Culture=neutral, PublicK
eyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [C:\Users\nikolev\Documents\test\test.csproj]
```

**Comment by rrelyea** [comment]
Let's get this fixed in Dev...and port to release branch.

**Comment by nkolev92** [comment]
Discussed offline. 

This is a 4.8 blocker.

**Comment by rrelyea** [comment]
added "including simple restores" to your first comment...cause I didn't realize that when I read it the first time. Yes, big blocker.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/2365
