### ISSUE TITLE
Nuget install on VS works, but installing in VS Code via Cake Script throws "Error: Failed to install tool 'EWSoftware.SHFB.NETFramework'"

### ISSUE THREAD

**Issue by JayBeAl** [NuGet/Home#7149]
## Details about Problem

_**Same nuget package works in VS Enterprise but doesnt in VS Code via CakeScript.**_

**NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):**

dotnet.exe, nuget.exe (Visual Studio Code - Cake Script)
and
Visual Studio Enterprise 2017

**NuGet version (x.x.x.xxx):**

4.7.0.5148

**dotnet.exe --version (if appropriate):**

2.1.302

**VS version (if appropriate**):

15.7.5

**Worked before? If so, with which NuGet version:**

I didn't use it before.

## Detailed repro steps so we can see the same problem

**SHFB(Sandcastle Help File Builder): A tool to create documentation out of XML-Comments**

1. Installed following nuget packages with the Visual Studio nuget-package-manager:
- EWSoftware.SHFB  --> version 2018.7.8
- EWSoftware.SHFB.NetFramework --> version 4.7.2

-> worked properly and i had no problems to use it.

2. Now i used a cake script in Visual Studio Code to automate documentation creation.
i tried to add both packages like this:

#tool nuget:?package=EWSoftware.SHFB&version=2018.7.8
#tool nuget:?package=EWSoftware.SHFB.NETFramework&version=4.7.2

on command "./build" the first package installed without problems.
the second package didn't, i got this error: "Error: Failed to install tool 'EWSoftware.SHFB.NETFramework'"

I tried all possible Versions of the .NETFramework nuget package (4.6.0; 4.6.1; 4.6.2; 4.7.0; 4.7.2)
Same Error on every Version.

Edit: I also contacted the product owner and he couldn't help me.

**So my Question is, why is the same package working for VS and not working for cakescript in VS Code?**

Here to project with cakescript etc. to reprodouce my problem in VS Code:
[JaysProblem.zip](https://github.com/NuGet/Home/files/2234915/JaysProblem.zip)

Thanks in advance!

Greetings
Jay

**Comment by zhili1208** [comment]
looked at this issue, nuget install finished correctly and the package is in the tools folder ,the error is from cake.exe. looks like this is not a nuget issue. I would suggest file a issue at https://github.com/cake-build/cake/issues, let them to investigate from their code first, if there is any issue from NuGet API, we can take a look from there.

**Comment by PatoBeltran** [comment]
Closing this since it doesn't seem to be a nuget issue.
