### ISSUE TITLE
Eliminate the concept of PackageSaveModes and always extract all the files in the nupkg

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#715]
Eliminate the concept of PackageSaveModes and always extract all the files in the nupkg

By default, the nuspec file is not extracted on the packages folder. nuspec file and all the other files should always be extracted

**Comment by yishaigalatzer** [comment]
I don't think we want to eliminate it from the library. But I do think we always want to extract all files when we explode the packages into the global packages folder.

**Comment by yishaigalatzer** [comment]
We don't even want to always extract all the files, in the case of caching flags are asking for it, to save on disk space for large packages
