### ISSUE TITLE
[Test Failure][Localization][PTB] Strings on NuGet Client VSIX installer are not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7152]
## Details about Problem
NuGet version: NuGet Client release-4.8.0-RTM-4.8.0.5362
VS Version: D15.8 27924.00
OS Version: Windows-10-Enetrprise-RS3-PT-PT
## Detailed repro steps
1. Install OS “Windows-10-Enetrprise-RS3-PT-PT” on a clean machine.
2. Install VS: D15.8 27924.00
3. Try to install NuGet Client VSIX from: Release-4.8.0-rtm\4.8.0.5362
## Expected
Strings on NuGet Client VSIX installer are all localized correctly. 
## Actual
Strings on NuGet Client VSIX installer are not localized as below screenshot. 
![installernotlocalized](https://user-images.githubusercontent.com/20632625/43313639-27984fea-9180-11e8-84a6-26ec652aca99.PNG)

## Note
It just repro on PTB.

**Comment by zhili1208** [comment]
@mishra14 are those strings owned by nuget team?

**Comment by mishra14** [comment]
talking to the extensibility team.

**Comment by mishra14** [comment]
There is nothing nuget can do to fix this. You need to install the vsix with a language switch - 

`vsixinstaller nuget.tool.vsix -culture:pt-br`

**Comment by v-luzh** [comment]
@mishra14 Thanks for your tracking. Just want to confirm with you that why there was no need to install the similar vsix with other languages?
