### ISSUE TITLE
ContentFiles are not being copied when NuGet package is not added directly

### ISSUE THREAD

**Issue by ppekrol** [NuGet/Home#7153]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet

dotnet.exe --version (if appropriate): 2.1.302

VS version (if appropriate): 2017 (15.7.5)

OS version (i.e. win10 v1607 (14393.321)): win10 (17134.191)

Worked before? If so, with which NuGet version: Probably was not working

## Detailed repro steps so we can see the same problem

Hi, I have a NuGet package (let's call it 'MyContentFilesPackage') which contains 'contentFiles'. Referencing this package works flawlessly, the 'contentFiles' are being copied to the output dir.

The problem starts, with another package ('MyNewPackage') that has a dependency on 'MyContentFilesPackage'). After installing the 'MyNewPackage' it resolves the 'MyContentFilesPackage' (it contains beside 'contentFiles' also DLLs that are resolved correctly) but the 'contentFiles' are not being copied. It looks like it is only working when 'MyContentFilesPackage' is added directly to the project. Is this how it should behave? Could you assist?

**Comment by zhili1208** [comment]
in this case ,you have to pack the "MyNewPackage" with referenced "MyContentFilesPackage" like following: 
```
<PackageReference Include="MyContentFilesPackage" Version="[the version]">
        <PrivateAssets>analyzers;build</PrivateAssets>
   </PackageReference>
```

Doc from here : https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

ContentFiles are treated as private assets by default, they are not flowed to parent project. so you have to override the PrivateAssets to get contentfiles flow transitively.

**Comment by ppekrol** [comment]
This was the article that I couldn't find anywhere. That helped. Thank you!

**Comment by javafun** [comment]
> in this case ,you have to pack the "MyNewPackage" with referenced "MyContentFilesPackage" like following:
> 
> ```
> <PackageReference Include="MyContentFilesPackage" Version="[the version]">
>         <PrivateAssets>analyzers;build</PrivateAssets>
>    </PackageReference>
> ```
> 
> Doc from here : https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
> 
> ContentFiles are treated as private assets by default, they are not flowed to parent project. so you have to override the PrivateAssets to get contentfiles flow transitively.

How can you get contentfiles flow transitively?

**Comment by javafun** [comment]
> in this case ,you have to pack the "MyNewPackage" with referenced "MyContentFilesPackage" like following:
> 
> ```
> <PackageReference Include="MyContentFilesPackage" Version="[the version]">
>         <PrivateAssets>analyzers;build</PrivateAssets>
>    </PackageReference>
> ```
> 
> Doc from here : https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
> 
> ContentFiles are treated as private assets by default, they are not flowed to parent project. so you have to override the PrivateAssets to get contentfiles flow transitively.

How can you get contentfiles flow transistively?

**Comment by zivkan** [comment]
With the code snippet you quoted: ` <PrivateAssets>analyzers;build</PrivateAssets>`
