### ISSUE TITLE
Incorrect error message when restoring a tampered signed package 

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#7156]
Nuget.exe  4.8.0.5278 , and Visual Studio: 15.8.27929.0 with packages.config

When trying to install a package that has been tampered with, I got the expected error:

```
NU3008: The package integrity check failed.
```
But if I open a project/solution that uses the offending package, during the restore operation,  there is no indication that the package has been tampered. In this case the error is:

```
Unable to find version '1.0.1' of package 'MySSCLib'.
```

I was expecting to see the same `NU3008` error.

/cc @mishra14  (related to #6318)

**Comment by mishra14** [comment]
@rido-min I am seeing the error in the error list (NuGet 5.0 latest)- 

![image](https://user-images.githubusercontent.com/10507120/43550633-1a908bec-9599-11e8-821b-1548a4af543b.png)

**Comment by mishra14** [comment]
Discussed this offline. Does not repro with latest nuget (5.x)
