### ISSUE TITLE
Nuget restore package not overwrite content files

### ISSUE THREAD

**Issue by BilgehanYildiz** [NuGet/Home#7157]
Hi we have a nuget package which has content files in nupkg.When we want to upgrade package that time dll's are updated but some of contents like css files are not updated.But when we delete old contents and try to update it again that time it is updated.(Note:We can succesfully create our nuget package with these contents files,no problem in this part).

**Comment by jainaashish** [comment]
Did you check if those content files were ever modified after install? NuGet doesn't update content files when they've been modified. If that's not your case, then provide repro steps or solution to investigate it.

**Comment by BilgehanYildiz** [comment]
I have a nuget package ,it has some files like that version MyWork.1.0.0
MyWork.dll
MyWork.Css
I have some changes in my nuget package MyWork.1.0.1
when I try to update nuget package
MyWork.dll -->1.0.1
MyWork.css-->1.0.0(not upgrade this file)
If I remove MyWork.1.0.0.0 completely and Make new instalitaion of MyWork.1.0.1 that time it is okey.

I am not clearly understand what "content files were ever modified after install" is mean?my expectation is to use nuget not only dll file sharing and I want also css ,ascx like other file sharing...
Is there a way to do this with nuget?

**Comment by StingyJack** [comment]
@BilgehanYildiz  - if you diff or checksum the css in the project with the one in the original package, are they the same?

If anyone made a modification to the file (reformatted, added a style, etc), nuget wont update it. 

You can get around this with an `init.ps1` or `install.ps1` script (the install.ps1 does not work for newer versions of nuget), or by including a script in the package that can force the files to be copied in.  A T4 (.tt) file may work too (they able to do more than generate a single output file).

**Comment by BilgehanYildiz** [comment]
They are not same ,there are different css .We added some style or etc.

I am not clearly understand we include some script to our nuget package but how can we run it automatically?

In newer version of nuget,is there any feature about this case,not only to update dll ,content also?

**Comment by jainaashish** [comment]
@BilgehanYildiz did your MYWork.css (1.0.0) still the same file which came from MyWork 1.0.0 package or did you modify this file after installing MyWork 1.0.0?

NuGet always updates content files like it updates dll, only exception is when the file has been modified after installation. Then NuGet leaves it as is. You don't need to go for scripts route, I'd highly discourage it.

Try this:
1. Create a new project
2. install your MyWork 1.0.0
3. Update MyWork 1.0.0 to MyWork 1.0.1
4. Check all your files must be updated from 1.0.0 to 1.0.1. If not, then please provide your sample package.

**Comment by BilgehanYildiz** [comment]
Hi ,We dont manuelly upgrade css file but for some design reason we exclude css file from our csproj but not change it.That time it is not upgraded but if it is include csproj that time no upgrade problem.Our problem is somefiles in nuget package but not included our csproj,that time not upgrade these files.

**Comment by jainaashish** [comment]
ahh then this is by design. NuGet will only update those files which were included in project. If you already excluded them, then you need to handle the update scenario as well.

You can have MSBuild targets to manage the update of these files.
