### ISSUE TITLE
Some times nuget doesn't config Assembly Binding in projects config file

### ISSUE THREAD

**Issue by xsoheilalizadeh** [NuGet/Home#7159]
## Details about Problem

NuGet product used:  VS UI && Package Manager Console

NuGet version: 4.6.0

VS version: VS2017 15.7.5

OS version: win10 v1803 (17134.191)

Worked before? If so, with which NuGet version: I have this problem always

## Detailed repro steps so we can see the same problem

1. I uninstall the package (MVC, json.net, automapper, etc ...) 

2. I install the package (MVC, json.net, automapper, etc ...) 

3. I check project config file (app.config or web.config both of them)

The problem is `assemblyBinding` in the project config files. When we install or uninstall package form the project, nuget should (remove or update or add) `assemblyBinding` elements such as:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Web.Mvc" publicKeyToken="31bf3856ad364e35"  />
        <bindingRedirect oldVersion="0.0.0.0-5.2.6.0" newVersion="5.2.6.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed"  />
        <bindingRedirect oldVersion="0.0.0.0-5.2.6.0" newVersion="5.2.6.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2"/>
  </startup>
</configuration>
```
Well, I going to explain this problem suppose I install Newtonsoft.Json package and then nuget insert a `dependentAssembly` element in `assemblyBinding`. If nuget doesn't add it to config  file when we run our project we get following exceptions:

```
Could not load file or assembly 'Newtonsoft.Json, Version=5.2.6.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
**ALSO** in the other scenarios like remove or updating nuget packages, the nuget should change the AssemblyBindings. Most of the project has a lot of packages so the programmers can't spend our time to update AssemblyBindings in config files.

**Comment by jainaashish** [comment]
@SoheilAlizade can you provide specific repro steps or repro solutions of your issue? There are already some existing issues with `BindingRedirects` like #6220 or #6187, etc.. if your issue is related to any of those, then please comment/ upvote there itself instead of creating a new.

**Comment by xsoheilalizadeh** [comment]
Hey @jainaashish, Sorry about this I think they are a common issue and please close this issue. 
Good luck;
