### ISSUE TITLE
Warn when installed version of a package is above version specified in project.json

### ISSUE THREAD

**Issue by anurse** [NuGet/Home#716]
Unless the user specifies a float `1.0.0-*` or `1.0.*`, etc.

If the package is a direct dependency of a project, it should mask all other versions in the graph, so if that version cannot be found, an error should be raised, rather than trying to install a later version.

**Comment by davidfowl** [comment]
Yes but no. This should be implemented with care. Don't treat top level nodes specially.

**Comment by anurse** [comment]
For now we'll do this the hacky way (compare project.json with actual resolved dependencies). File #837 to improve this.
