### ISSUE TITLE
NuGet.exe update -self doesn't update from 4.6.2 to newer version

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [NuGet/Home#7166]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.6.2.5055

OS version: Microsoft Windows NT 6.3.9600.0

Worked before? If so, with which NuGet version: Updated successfully from 4.5.1 to 4.6.2

## Detailed repro steps so we can see the same problem

1. Download [nuget.exe 4.6.2](https://dist.nuget.org/win-x86-commandline/v4.6.2/nuget.exe)

2. Run from command prompt: `nuget.exe update -Self`

I was expecting it to update itself to [version 4.7.0](https://dist.nuget.org/win-x86-commandline/v4.7.0/nuget.exe) (Latest stable at the moment), but instead I got this:

```
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.6.2.
NuGet.exe is up to date.
```

**Comment by jainaashish** [comment]
Related workitem - https://github.com/NuGet/Home/issues/7116
