### ISSUE TITLE
Docs on creating a Native TFM package

### ISSUE THREAD

**Issue by shamelo** [NuGet/Home#7168]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
nuget.exe NuGet Version: 4.7.0.5148
Visual Studio 2017 Enterprise
Windows 10 Pro

Worked before? If so, with which NuGet version: No, total nuget packagingnoob

## Detailed repro steps so we can see the same problem

After a ton of internet searching, I still have not found straight forward steps (for someone with absolute beginner experience with using nuget and packaging dlls, and packaging files in general that are not managed code) on how to use nuget to create a package with (unmanaged code) exisiting dlls.

Please help.

**Comment by jainaashish** [comment]
There are bunch of different documents on NuGet.org about creating different kind of packages like:
https://docs.microsoft.com/en-us/nuget/create-packages/overview-and-workflow
https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-the-dotnet-cli
https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework
etc...

Does any of these help you with your issue? if not, then explain your scenario. On a hindsight, there are multiple ways to include existing dlls in your package like you can include them under /build folder and write your simple target to include them in the project.

**Comment by shamelo** [comment]
None of this documentation helps as I am specifically trying to package a dll (that is unmanaged code). When I follow the documentation, I get the following error:

Install-Package : Failed to add reference to 'AppDynamics.Profiler_x64'.
  Please make sure that the file is accessible, and that it is a valid assembly or COM component.

Here is my nuspec file:
`<?xml version="1.0"?>
<package >
  <metadata>
    <id>MyPackage</id>
    <version>1.0.0</version>
    <title>MyPackage</title>
    <authors>Sha Melo</authors>
    <owners>Sha Melo</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>MyPackageDemo</description>
    <releaseNotes>Summary of changes made in this release of the package.</releaseNotes>
    <copyright>Copyright 2018</copyright>
    <tags>Tag1 Tag2</tags>
  </metadata>
    <files>
	<file src="mydll.dll" target="lib\mydll.dll" />
	<file src="*mydll.Profiler_x64.dll" target="lib\mydll.Profiler_x64.dll" />
    <file src="build\MyPackage.targets" target="build" />
  </files>
</package>`

Here is my .targets file
`<?xml version="1.0" encoding="utf-8"?> 
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"> 
  <Target Name="CopyMyPackageFiles" AfterTargets="AfterBuild"> 
    <ItemGroup> 
      <MyPackageFiles Include="$(MSBuildThisFileDirectory)..\lib\*.*"/> 
    </ItemGroup> 
    <Copy SourceFiles="@(MyPackageFiles)" DestinationFolder="$(OutputPath)" > 
    </Copy> 
  </Target> 
</Project>`

I can package and self host my files. However, when I try to install my package into an existing solution, the install fails with the error:

Install-Package : Failed to add reference to 'mydll.Profiler_x64'.
  Please make sure that the file is accessible, and that it is a valid assembly or COM component.

**Comment by StingyJack** [comment]
If you extract the nupkg that you create, does it have all the files you expected to see?

**Comment by shamelo** [comment]
I do see the files that I expect to see. When I install it, that's when I
see the error:

Install-Package : Failed to add reference to 'mydll.Profiler_x64'.
Please make sure that the file is accessible, and that it is a valid assembly or COM component.

I am using Visual Studio 2017 (Enterprise). Also, I have used the previous links as a guide to building the package. Those don't seem to help.

Thanks.

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/docs.microsoft.com-nuget/issues/2070
