### ISSUE TITLE
Installing NuGet package that is marked as a development dependency doesn't add the PrivateAssets="All" attribute to the PackageReference element

### ISSUE THREAD

**Issue by ygoe** [NuGet/Home#7171]
Here's the details. Unfortunately you seem to have deleted the referenced issue. And Microsoft won't let me comment on their side.

https://developercommunity.visualstudio.com/content/problem/23158/installing-nuget-package-that-is-marked-as-a-devel.html

**Comment by mishra14** [comment]
@ygoe The referenced issue is still available [here](https://github.com/NuGet/Home/issues/4125).

Further, if you see [this](https://github.com/NuGet/NuGet.Client/pull/2182) PR, you will notice that this has been fixed in VS 15.8 release. Have you tried a 15.8 preview?

**Comment by ygoe** [comment]
No, I'll wait for the release. Do I have to mark the tool package in some way?

**Comment by mishra14** [comment]
You need to add the following to your nuspec file - 

`<developmentDependency>true</developmentDependency>`

You can read more about it [here](https://docs.microsoft.com/en-us/nuget/reference/nuspec#developmentdependency).

**Comment by nkolev92** [comment]
@ygoe 
Have your problem been resolved?

**Comment by ygoe** [comment]
Well, I have no nuspec file. Just a .csproj file. Can I just put everything in there?

**Comment by nkolev92** [comment]
@ygoe 
Yes you can set the metadata, 
`<DevelopmentDependency>true</DevelopmentDependency>`

**Comment by ygoe** [comment]
Yes, that helps. My NuGet package is now automatically installed as private and will not show up as a dependency in a third project. Thank you!

**Comment by nkolev92** [comment]
Sounds good. 

Thanks for following up. 

Closing this now.
