### ISSUE TITLE
Add option to override default of online revocation check

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#7173]
Currently, in the verification code for signed packages we check for revocation online always, if the machine is not online we still try to make the verification online and give a warning if it was not possible.

We should add a flag (probably to nuget.config and CLI commands) that lets the users specify the revocation verification mode, either online or offline.

cc. @dtivel

**Comment by pascalberger** [comment]
@PatoBeltran Thanks for fixing this! What's the expected version for this to ship?

**Comment by PatoBeltran** [comment]
@pascalberger we are planning to ship this in nuget.exe 4.8.1 which should be out by early next week. Just a heads up, the approach from the testing private bit I sent you changed, the final approach uses an environment variable instead of adding the setting to nuget.config. Once the documentation for this feature is live I can point you to it, also feel free to see the code in the PR linked here.

**Comment by PatoBeltran** [comment]
@pascalberger nuget.exe 4.8.1 has just shipped with this fix. You can download it at https://www.nuget.org/downloads

**Comment by pascalberger** [comment]
@PatoBeltran Thanks! Do you plan to also update [NuGet.CommandLine package](https://www.nuget.org/packages/NuGet.CommandLine/) to this version?

**Comment by pascalberger** [comment]
And are there any release notes available somehwere?
