### ISSUE TITLE
[Test Failure] PackageReference Migrator menu was enabled incorrectly to all projects include C++ and .NET Core

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7176]
## Details about Problem
NuGet version: NuGet Client Dev 5.0.0.5381
VS Version: D16.0stg 28002.3001
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps 
1. Create a C++ UWP template via VS.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Install a package (e.g. “SampleCPlusPlusDevicePackage”) with “Packages.config” format.
4. Right-click the “References” node or “packages.config” file.
## Expected
There should be no PackageReference Migrator menu since it not support for C++ project. 
## Actual
There is PackageReference Migrator menu showing and the “eligible for migration” warning dialog pop out after clicking the menu as below screenshot. 
![migratorenabledtoallprojects](https://user-images.githubusercontent.com/20632625/43763866-692a6eea-9a1b-11e8-9a22-2fb2cd9493e7.png)

## Note
1.It repro on .NET Core projects which are already PackageReference.
2.It repro on D16.0stg 28002.3000+NuGet Client Dev 5.0.0.5375.
3.It didn't repro on D15.8 28002.00+NuGet Client Release-4.8.0-RTM\4.8.0.5377.

**Comment by mishra14** [comment]
@v-luzh This is the new expected behavior. @jainaashish fixed this as part of https://github.com/NuGet/NuGet.Client/pull/2361. 

Please update the tests as the option will be available for all project types, but on clicking it a dialog will be generated for unsupported project types.
