### ISSUE TITLE
nuget.exe returns exit code zero for invalid arguments

### ISSUE THREAD

**Issue by mikeclayton** [NuGet/Home#7178]
NuGet product used: nuget.exe

NuGet version (x.x.x.xxx): 4.7.0.5148

OS version (i.e. win10 v1607 (14393.321)):

```
C:\>ver
Microsoft Windows [Version 10.0.16299.492]
```

## Detailed repro steps so we can see the same problem

Calling nuget.exe with invalid command line arguments shows the help text for the command, but terminates with a zero exit code which makes it difficult to catch errors when calling nuget.exe from a script.

For example, when using the "-version" parameter (but not supplying a value):

```
C:\>"C:\Program Files\nuget\nuget.4.7.0.5148.exe" install mypackage -version -outputdirectory "C:\temp\packages"
install: invalid arguments.
usage: NuGet install packageId|pathToPackagesConfig [options]
... etc ...

C:\> echo %errorlevel%
0
```
I think this is because this line just falls through to "return 0" at the bottom of MainCore():

https://github.com/NuGet/NuGet.Client/blob/8e9a585d86f583e0c1e07cd7f389ace865b9ac60/src/NuGet.Clients/NuGet.CommandLine/Program.cs#L132

My expectation would be that invalid command line arguments should return a non-zero exit code. 

Maybe add a "return 1" after the above call to ViewHelpForCommand? I can send a PR if that helps?

**Comment by MarkKharitonov** [comment]
Yes, please fix it.
