### ISSUE TITLE
Restore not working in Visual Studio

### ISSUE THREAD

**Issue by eschneider999** [NuGet/Home#7179]
## Details about Problem
Nuget package manager 4.6.0
Visual Studio 15.7.6

Restore says it completed
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.5365078
========== Finished ==========

Yet I still get a build error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\Symbiotic\packages\MSTest.TestAdapter.1.3.2\build\net45\MSTest.TestAdapter.props.	UniversalTestProject_VB	D:\Dev\FrozenElephant\Nuget_Packages\Rel2.1.2\ExampleProjects\UniversalTestProject_VB\UniversalTestProject_VB.vbproj	348	
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\Symbiotic\packages\System.Data.SQLite.Core.1.0.108.0\build\net46\System.Data.SQLite.Core.targets.	UniversalTestProject_CS	D:\Dev\FrozenElephant\Nuget_Packages\Rel2.1.2\ExampleProjects\UniversalTestProject_CS\UniversalTestProject_CS.csproj	471

**Comment by eschneider999** [comment]
I figured out what was wrong.

I made a copy of the project in a different folder. The visual studio project file had all the wrong paths even after restoring nuget packages.

So the packages were there but the project file was bad.

Should't nuget update the project file with the new path?

**Comment by StingyJack** [comment]
> Should't nuget update the project file with the new path?

It will only do that if you either remove then re-add the package, or use `Update-Package` with `-reinstall`. Nuget is actually not as tightly integrated with the project system as the impression it gives.

If you use a nuget.config in the same directory as the sln file, and it has relative pathing to the package folder, you can copy that solution to wherever.

**Comment by eschneider999** [comment]
is there any plans to fix these issues?

If I do a restore, why doesn't it just remove the existing paths, that doesn't make sense.

**Comment by StingyJack** [comment]
> is there any plans to fix these issues?

Since you have mentioned "paths wrong in the csproj", you probably have a package.config file and not package reference in the csproj. This means that the answer to your question is "No" if you intend to continue using packages.config, as there will be no more development on this style of nuget package management ([source](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference), last "benefit").

However this specific problem is the one solved by changing to package ref. The proj file will no longer have a HintPath, VS/MSB will get the package from a global package folder or d/l it and put it there without needing any absolute or relative path in the proj file. 

> If I do a restore, why doesn't it just remove the existing paths, that doesn't make sense.

Restore isnt going to alter the project file in any case. Nobody _really_ wants that kind of pending change churn. Restore only puts the packages where the nuget.config tells it to put them. So if you are using a nuget.config file (you should have one in the same folder as the solution), make sure its using a relative path for the packages folder.

**Comment by eschneider999** [comment]
What nuget config are you talking about? do you mean the packages.config? That only has lib names, version and framework. No paths.

I would use the package ref but I keep finding issues with it, and they don't seem to get addressed. Also some published packages are known to not work with that new process. When you have a large solution, that's a big if. Maybe you could have an indicator that the package was tested for the package ref process? At least then we would have some idea if moving to it is feasible.

Frankly, if I could find a better alternative to Nuget, I would use it.

**Comment by StingyJack** [comment]
Here is a screenshot of how I have one of our medium sized solutions setup with a nuget.config file. 
![image](https://user-images.githubusercontent.com/15381181/43874572-84a9a7e0-9b5a-11e8-8c03-fa26e7866566.png)


I dont think you need to make it part of the solution, it just has to be in the same directory with the solution. VS reads that config file and uses that `repositoryPath` to put the packages in. That's the relative path I was talking about where package restore extracts the packages to.  We also define our local package feed and disable source control integration.

I feel your pain with both package ref and the direction nuget is heading; its a going to be an immense effort to get out of the corner we are getting painted into. [Ive given them plenty](https://github.com/NuGet/Home/issues?utf8=%E2%9C%93&q=is%3Aissue+mentions%3AStingyJack+) of blunt but honest ["feedback"](https://github.com/NuGet/docs.microsoft.com-nuget/issues/407), yet [some of them are shamelessly blind to the effects of their choices](https://github.com/NuGet/Home/issues/3050#issuecomment-395545417), and sometimes they are just [bad parodies of "the computer guy"](https://github.com/NuGet/Home/issues/6534). 

> Frankly, if I could find a better alternative to Nuget, I would use it.

For .net projects, there isnt. Paket isnt enough yet, Bower is dead, NPM is OK but not made for .net projects. Eventually NuGet won't be any good either with the best parts being ripped out every year. MSFT seems to want to re-invent DLL hell every few years. Perhaps this is just the next cycle coming in.

**Comment by eschneider999** [comment]
Thanks for the feedback. Do you have any links handy for the nuget.config?
Also if I use this nuget.config does that dictate which way to use nuget packages? ref vs config?

**Comment by rrelyea** [comment]
thanks @StingyJack for the help.

@eschneider999  - our docs for nuget.config.
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file

nuget.config works regardless of whether you use v1 style (packages.config) or v4 style (packagereferences)
