### ISSUE TITLE
Possible license violation when downloading NuGet packages

### ISSUE THREAD

**Issue by apirila** [NuGet/Home#718]
If you download a nuget package, a valid license file may not be distributed with the software. E.g. if you include a package "Json.NET" the license file is not included in the distribution. The MIT license however states 

"... The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software. .."

So distributing MIT licensed software requires that the license file is included with the package. Now if I create an application that includes e.g. this "Json.NET", the DLL files is nicely included with my application. But NuGet should also include the license (e.g. Json.NET.license.txt) so that NuGet would ensure that I comply with the MIT license. Most of the OSS licenses have similar requirement.

**Comment by yishaigalatzer** [comment]
We don't plan to enforce this. You can file a request against json.NET or any other package that you feel is not complying with their license.

You can file an issue on our gallery (nugetgallery repo) where we might be able to suggest additional validation to packages.

**Comment by hickford** [comment]
Similarly https://www.nuget.org/packages/Unity/ is Apache 2.0 licensed yet the `.nupkg` file neglects to include a copy of the licence document:

> You must give any other recipients of the Work or Derivative Works a copy of this License

I suspect:
1. This is true of the majority of open-source licensed projects on Nuget.org
2. No-one cares

Most these licenses were drafted in the 1990s. Today when almost every computer is connected to the internet, a link seems to be a good as a copy:

```
 <licenseUrl>http://opensource.org/licenses/Apache-2.0</licenseUrl>
```
