### ISSUE TITLE
Update-Package -Id <package> -Reinstall also reinstalls other packages

### ISSUE THREAD

**Issue by philippdolder** [NuGet/Home#7182]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Package Manager Console
NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):
2017 (15.7.4)
OS version (i.e. win10 v1607 (14393.321)):
Win 10 
Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. execute Update-Package -Id Newtonsoft.Json -Reinstall

2. seems it reinstalls all the packages in all the projects of the current solution

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by mishra14** [comment]
This has been fixed as part of https://github.com/NuGet/NuGet.Client/pull/2294 

Can you please try with latest Visual Studio 15.8 preview?

**Comment by philippdolder** [comment]
Sorry for the duplicate report, I didn't find it using the search function 🤔 

Works as expected with the latest VS preview
