### ISSUE TITLE
Expose API for Visual Studio extensions to trigger package restore

### ISSUE THREAD

**Issue by JoshVarty** [NuGet/Home#719]
I'm working on an extension that must compile/emit C# projects. 

It would be nice if there was a way for us to trigger package restore without having to call `nuget.exe` directly.

**Comment by yishaigalatzer** [comment]
@JoshVarty I forgot to mention that starting with Visual Studio 2015, we auto restore on build (unless the user opted out, which at that point I don't think you want to restore).

**Comment by JoshVarty** [comment]
I'm actually using Roslyn to build their projects behind the scenes. So I'm not going through VS's traditional build system.

**Comment by yishaigalatzer** [comment]
Key issue when this is implemented - Verify UI interactivity when needing to get credentials for authenticated feeds

**Comment by rohit21agrawal** [comment]
closing for being too dated.
