### ISSUE TITLE
Exclude default assemblies from nuget package

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7191]
_From @matkoch on August 8, 2018 17:31_

Is it somehow possible to exclude the default assemblies, e.g. `<lib>/<framework>/SampleApp.dll`, from the final nuget package?

_Copied from original issue: dotnet/cli#9806_

**Comment by mishra14** [comment]
@matkoch you can use the `-Exclude` option in the pack command - `nuget pack -Exclude lib/**/SampleApp.dll`.

You can read more about the options [here](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack#options).

**Comment by matkoch** [comment]
I would prefer a way to do this in the csproj file.

**Comment by mishra14** [comment]
@matkoch - I See. Will setting `IncludeBuildOutput` to false resolve your issue? 

Reference - [IncludeBuildOutput](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#includebuildoutput)

**Comment by matkoch** [comment]
Disabling would work. However, there is also `BuildOutputTargetFolder`, but that will again have a `net461` sub-folder. Is there any way to disable this behavior as well? Otherwise, I would just set the other property to false, and add the packages via `Pack=true`.

**Comment by mishra14** [comment]
@rohit21agrawal Do you have an alternative for @matkoch ?

**Comment by rohit21agrawal** [comment]
@matkoch no. there is no way to disable creation of tfm folder if you want nuget to include output assemblies in the package by default. Can you give more details about what kind of package you are trying to build and for what scenario ?

**Comment by matkoch** [comment]
It's alright then, thank you. From my side, this can be closed.
