### ISSUE TITLE
Can't install packages in VS 2015 with nuget version 3.6.0

### ISSUE THREAD

**Issue by dallasclement** [NuGet/Home#7195]
## Details about Problem

I am unable to install the Microsoft.EntityFrameworkCore.Tools package in VS 2015.  The latest nuget version 3.6.0 for VS 2015 prevents this package from being installed due to a version mismatch.  

**The 'Microsoft.EntityFrameworkCore.Abstractions 2.1.1' package requires NuGet client version '3.6.0' or above, but the current NuGet version is '3.6.0-rtm-2511'**

See details below.

This is a critical blocking issue for me!  I have a hard deadline a week away that I cannot achieve until this is resolved.  I am stuck with VS 2015 for this project.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Package Manager Console 

NuGet version (x.x.x.xxx):  3.6.0

dotnet.exe --version (if appropriate):  1.1.0

VS version (if appropriate):  VS Community 2015 version 14.0.25431.01 Update 3

OS version (i.e. win10 v1607 (14393.321)):  Windows Server 2012 R2

Worked before? If so, with which NuGet version:  Not sure.

## Detailed repro steps so we can see the same problem

1.  Download and install latest v3.6.0 for VS2015 => https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

2.  Try to install entity framework tools from the package manager console.

PM> Install-Package Microsoft.EntityFrameworkCore.Tools

Attempting to gather dependency information for package 'Microsoft.EntityFrameworkCore.Tools.2.1.1' with respect to project 'LetterHarvester', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 3.1 sec
Attempting to resolve dependencies for package 'Microsoft.EntityFrameworkCore.Tools.2.1.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.EntityFrameworkCore.Tools.2.1.1'
Resolved actions to install package 'Microsoft.EntityFrameworkCore.Tools.2.1.1'
Retrieving package 'System.Collections.Immutable 1.5.0' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore.Abstractions 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore.Analyzers 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.DependencyInjection.Abstractions 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.DependencyInjection 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Logging.Abstractions 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Primitives 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Caching.Abstractions 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Configuration.Abstractions 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Configuration 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Configuration.Binder 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Options 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Caching.Memory 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.Extensions.Logging 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore.Relational 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore.Design 2.1.1' from 'nuget.org'.
Retrieving package 'Microsoft.EntityFrameworkCore.Tools 2.1.1' from 'nuget.org'.
Retrieving package 'Remotion.Linq 2.2.0' from 'nuget.org'.
Retrieving package 'System.Interactive.Async 3.1.1' from 'nuget.org'.
Retrieving package 'System.Buffers 4.4.0' from 'nuget.org'.
Retrieving package 'System.Numerics.Vectors 4.4.0' from 'nuget.org'.
Retrieving package 'Microsoft.CSharp 4.5.0' from 'nuget.org'.
Retrieving package 'System.ComponentModel.Annotations 4.5.0' from 'nuget.org'.
Retrieving package 'System.Diagnostics.DiagnosticSource 4.5.0' from 'nuget.org'.
Retrieving package 'System.Runtime.CompilerServices.Unsafe 4.5.1' from 'nuget.org'.
Retrieving package 'System.Memory 4.5.1' from 'nuget.org'.
Adding package 'Microsoft.CSharp.4.5.0' to folder 'C:\Users\v-dallas.clement\Source\Repos\DPS-OSS-SCM\packages'
Added package 'Microsoft.CSharp.4.5.0' to folder 'C:\Users\v-dallas.clement\Source\Repos\DPS-OSS-SCM\packages'
Added package 'Microsoft.CSharp.4.5.0' to 'packages.config'
Successfully installed 'Microsoft.CSharp 4.5.0' to LetterHarvester
Install failed. Rolling back...
Package 'Microsoft.EntityFrameworkCore.Abstractions.2.1.1' does not exist in project 'LetterHarvester'
Removed package 'Microsoft.CSharp.4.5.0' from 'packages.config'
Package 'Microsoft.EntityFrameworkCore.Abstractions.2.1.1' does not exist in folder 'C:\Users\v-dallas.clement\Source\Repos\DPS-OSS-SCM\packages'
Removing package 'Microsoft.CSharp.4.5.0' from folder 'C:\Users\v-dallas.clement\Source\Repos\DPS-OSS-SCM\packages'
Removed package 'Microsoft.CSharp.4.5.0' from folder 'C:\Users\v-dallas.clement\Source\Repos\DPS-OSS-SCM\packages'
Executing nuget actions took 1.16 sec
Install-Package : **The 'Microsoft.EntityFrameworkCore.Abstractions 2.1.1' package requires NuGet client version '3.6.0' or above, but the 
current NuGet version is '3.6.0-rtm-2511'**. To upgrade NuGet, please go to http://docs.nuget.org/consume/installing-nuget
At line:1 char:1
+ Install-Package Microsoft.EntityFrameworkCore.Tools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by zhili1208** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.
