### ISSUE TITLE
Release Notes for NuGet 4.7.1

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7196]
[NuGet.Commandline](https://www.nuget.org/packages/NuGet.CommandLine/) was released for version 4.7.1. But nuget.org still shows 4.7.0 as latest version and there are also no [release notes](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.7-rtm) available. What has changed in 4.7.1? Was the release only be done for #7116 or does it contain any actual fixes?

**Comment by rohit21agrawal** [comment]
it was only done for fixing #7116 . there are no other changes in it .
