### ISSUE TITLE
Add documentation around PCLs

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#720]
There have been requests for guidance on adding PCLs to nupkgs.

A few things that could be covered in the docs:
1. Finding the NuGet PCL string for a portable profile number.  Examples of this can be found on: http://blog.stephencleary.com/2012/05/framework-profiles-in-net.html  but nuget.org is currently lacking any details about this.
2. Optional profiles for the xamarin frameworks. These do not need to be included unless the profile does not match a known .NET profile.
3. Using short names vs long names in PCLs. Example: wpa instead of WindowsPhoneApp to reduce the path size.
4. Guidance for using the string matching the actual profile. In general users should stick to the actual .NET portable profile frameworks they compiled against. Appending arbitrary frameworks to increase compatibility can lead to problems when the API surface areas used do not match.
5. Portable v5 documentation for 'dotnet'

**Comment by csharpfritz** [comment]
Holding for support of .NET Platform Standard so this isn't written and rewritten very quickly
