### ISSUE TITLE
nuget sources add should not delete credentials from NuGet.config

### ISSUE THREAD

**Issue by ap0llo** [NuGet/Home#7200]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4.7.1.5393

### Background

We run an internal NuGet server that requires authentication. 
To configure the feed to use, we place a `nuget.config` file in the source code repository, but configure the credentials for the feed in the user's local `NuGet.Config`

### Repro steps

1. Place a `nuget.config` in a source code repository or empty folder. 
   
    Example:

   ```xml
   <?xml version="1.0" encoding="utf-8"?>
   <configuration>
     <packageSources>
       <clear />
       <add key="Feed1" value="http://example.com/feed1" />
     </packageSources>
   </configuration>
   ````

2. Add the credentials for "Feed1" to `%APPDATA%\NuGet\NuGet.config`. 

    Example (I used `ClearTextPassword` for the example but the behavior is the same when using an encrypted password):

   ```xml
   <?xml version="1.0" encoding="utf-8"?>
   <configuration>
     <packageSources>
       <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
     </packageSources>
     <packageSourceCredentials>
       <Feed1>
         <add key="Username" value="USERNAME" />
         <add key="ClearTextPassword" value="PASSWORD" />
       </Feed1>
     </packageSourceCredentials>
   </configuration>
   ```

3. Run `nuget restore` or `nuget install` in the repository. NuGet combines the feed url and credentials from the different config files and succeeds to download packages.
4. Run `nuget sources add -name Feed2 -source http://example.com/feed1` from a directory outside the repository so NuGet does not load the repository-config file.
5. Inspect `%APPDATA%\NuGet\NuGet.config`. As expected, the source "Feed2" was added.
    However, the credentials for Feed1 are no longer present in the config file:

Expected:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Feed2" value="http://example.com/feed2" />
  </packageSources>
  <packageSourceCredentials>
    <Feed1>
      <add key="Username" value="USERNAME" />
      <add key="ClearTextPassword" value="PASSWORD" />
    </Feed1>
  </packageSourceCredentials>
</configuration>
```

Actual:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Feed2" value="http://example.com/feed2" />
  </packageSources>
</configuration>
```

**Comment by zhili1208** [comment]
I can repro this, it's because we rewrite the whole nuget.config when we modify the file, in this scenario, nuget added feed2 to nuget.config, but can't find feed1, then the feed1 credential is removed. we should consider this scenario.

**Comment by PatoBeltran** [comment]
This has been solved as part of the latest rework on the nuget.configuration code paths.
