### ISSUE TITLE
Install-Package ExcelDataReader does not install excel.dll

### ISSUE THREAD

**Issue by Gardens18** [NuGet/Home#7203]
Install-Package ExcelDataReader does not install excel.dll

**Comment by zhili1208** [comment]
could you provide more information? VS version? NuGet Version? project type? thanks

**Comment by mishra14** [comment]
closing as dupe of https://github.com/ExcelDataReader/ExcelDataReader/issues/342

@Gardens18 This is an issue that you need to take up with the package owners.
