### ISSUE TITLE
TargetFramework with specified UAP version doesn't respect TPV/TPMV

### ISSUE THREAD

**Issue by samhouts** [NuGet/Home#7205]
## Details about Problem

NuGet product used (Package Manager Console):

I don't expect to be able to install version 6.0.1 or greater of `Microsoft.NETCore.UniversalWindowsPlatform` into a UWP project with TPV/TPMV 10.0.14393.0....

```    <TargetPlatformIdentifier>UAP</TargetPlatformIdentifier>
    <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.14393.0</TargetPlatformMinVersion>
```

… because it is set to a target of 15138 ...
![image](https://user-images.githubusercontent.com/7827070/44124414-01399f32-9fe2-11e8-86f7-6dcc721e5c51.png)

….but I can install it nonetheless. 

This is problematic because I am trying to limit another nuget package to FCU or above, but the nuget package installs happily anyway, despite actually failing to install the required NetStandard2.0 dependency, resulting in a failure to compile.

In my package, I have also explicitly named the folders with the minimum version, in case [this spec](https://github.com/NuGet/Home/wiki/Converting-Extension-SDKs-into-NuGet-Packages#supporting-platform-versions-in-uap-nuget-packages) was still accurate.

Am I just misunderstanding how this is supposed to work? How do I keep users from installing a package into a lower target?

NuGet version (x.x.x.xxx): 4.6.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.7.6

OS version (i.e. win10 v1607 (14393.321)): 17735

Worked before? If so, with which NuGet version: ?

## Detailed repro steps so we can see the same problem

1. Open sample project (this is file>new UWP, targeted at 14393).
2. Note that it actually already has `Microsoft.NETCore.UniversalWindowsPlatform` 6.1.7. It shouldn't, since that is targeting version 15138.
2. Try to update to latest `Microsoft.NETCore.UniversalWindowsPlatform`. It should fail and warn about incompatibility. It succeeds.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

[NugetTargetVersion.zip](https://github.com/NuGet/Home/files/2288811/NugetTargetVersion.zip)

**Comment by zhili1208** [comment]
@diverdan92 does this look like a bug?

**Comment by samhouts** [comment]
Also, aside from the `targetFramework` not working how I expect, shouldn't Xamarin.Forms 3.0+ fail to install in a UWP project < 16299 anyway, since it fails to install the NETStandard2.0 dependency?

**Comment by diverdan92** [comment]
@samhouts  - if you look at Microsoft.netcore.universalwindowsplatform.6.1.7, you'll see it leverages platform multi-targeting:
![image](https://user-images.githubusercontent.com/6608201/44179956-b7034a80-a0ae-11e8-8fa6-77237a47c97d.png)

There is both a netcore50 folder (an artifact of naming before the .NET Core naming was finalized), as well as a uap10.0.15138.0 folder. When your TPMinV < 10.0.15138.0, the netcore50 folder will be restored. 

Can you try your same repro steps with just your NuGet package that presumably only has a single 
framework supported (or attach your .nupkg)?

**Comment by samhouts** [comment]
Oh, we're definitely using multitargeting. So, I presume that my package is restoring from the `netstandard1.0` folder, then. That's aggravating. :/

![image](https://user-images.githubusercontent.com/7827070/44372773-628b1100-a49a-11e8-8d2e-d828cece0ec1.png)

**Comment by samhouts** [comment]
Yep, verified that it works when I removed the netstandard1.0 target. Not really what I want, but not a bug either. Thanks!

**Comment by diverdan92** [comment]
Do you have any suggestions for how this could be better for your use case?

**Comment by samhouts** [comment]
If I try to install this same package into a MonoAndroid80 project, it fails, even though that project supports netstandard. I expected the UAP10.0.16299.0 targetFramework to work the same way.

**Comment by diverdan92** [comment]
I see. So you're saying that if the library has any UAP TFM, it should always take precedent (and effectively ignore) differing TFMs (in this case, netstandard)?

**Comment by samhouts** [comment]
Yep! Most specific matching target wins.
