### ISSUE TITLE
Author package signing Certificate with DigiCert

### ISSUE THREAD

**Issue by bruno-garcia** [NuGet/Home#7211]
On the [Microsoft docs](https://docs.microsoft.com/en-us/nuget/reference/signed-packages-reference#get-a-code-signing-certificate) on how to get a code sign certificate, one of the suggested services is **DigiCert**.

When attempting to acquire the cert, while holding the [minimum requirements spec](https://github.com/NuGet/Home/wiki/Package-Signatures-Technical-Details#-certificate-minimum-requirements) I was prompted with these options:

<img width="749" alt="screenshot 2018-08-13 14 23 07" src="https://user-images.githubusercontent.com/1633368/44256682-2b9ecc00-a20a-11e8-893b-9737f4d6c964.png">

Could you please clarify which of these options would be the correct one?

**Comment by rohit21agrawal** [comment]
@PatoBeltran & @dtivel  can you help @bruno-garcia ?

**Comment by dtivel** [comment]
@bruno-garcia, I'd choose Other.

**Comment by bruno-garcia** [comment]
That's what I'd choose too.
Anyway, we'll give it a shot, thanks!
