### ISSUE TITLE
Enable generating exact versions in nuspec dependencies

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#7213]
**Scenario**

Packages generated for multiple projects that are tightly coupled due to usage of InternalsVisibleTo need to use exact versions (e.g. `[1.0.0]`) when they refer to each other in their NuSpec dependency specification rather than right-open version range (e.g. `[1.0.0)`). Currently packages generated via Pack task only allow the latter.

**Proposal**
1. Allow `ProjectVersion` metadata of `ProjectReferencesWithVersions` items consumed by the `PackTask` to be version ranges. `ProjectVersion` string [parsing](https://github.com/NuGet/NuGet.Client/blob/50af5271b98ac5cb2896a707569bc4cd1e87a017/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L693) can be trivially updated to support ranges.

2. Allow specifying `ExactVersion="true"` metadata on `ProjectReference`, include the flag in assets.json and use it when initializing `ProjectReferencesWithVersions.ProjectVersion` to create closed range version.

This proposal allows projects to opt-into exact versions with project references annotated manually or automatically based on presence of InternalsVisibleTo using custom targets.

**Comment by tmat** [comment]
@rohit21agrawal Does the proposed design seem reasonable? If so, I'd send a PR for at least the part [1]. This affects Roslyn build, so I'd like to get it done soon.

**Comment by rohit21agrawal** [comment]
this is also very closely related to : https://github.com/NuGet/Home/issues/5556 

@tmat  from your suggestion, i am not sure what it would look like from an end user point of view. Are you suggesting ,that we solve this by adding ExactVersion=true metadata on a projectReference?

**Comment by rohit21agrawal** [comment]
CC: @bording

**Comment by bording** [comment]
It would be great if this also solved #5556.

**Comment by tmat** [comment]
> ExactVersion=true metadata on a ProjectReference

Yes.

> It would be great if this also solved #5556.

#5556 is similar, but it would not quite address the above problem. We don't want to specify a version number, just the fact that the range should be closed. Ideally we would design metadata that allow us to address both features with minimal amount of clutter.

**Comment by tmat** [comment]
Taking it one step further - if the .NET SDK defined an item group that allows to declare InternalsVisibleTo (for example [like so](https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Microsoft.CodeAnalysis.csproj#L51)) I could imagine a target that sets teh `ExactVersion=true` based on presence of InternalsVisibleTo. We can experiment with that separately once we have the ExactVersion feature.

**Comment by tmat** [comment]
One idea how to implement both #5556 and this feature using one attribute:

```xml
<PackageReference VersionRange="[*]">    <!-- exact version -->
<PackageReference VersionRange="[*,*)">  <!-- this is the default -->
<PackageReference VersionRange="[*,2.0.0]">  <!-- upper limit -->
```

In this syntax, `*` represents the actual version of the referenced project.

**Comment by dsplaisted** [comment]
`*` already means something, so the syntax could be something like the following:

```
<ProjectReference Include="R.csproj" PackVersion="[_]"/>    <!-- exact version -->
<ProjectReference Include="R.csproj" PackVersion="_"/>  <!-- this is the default -->
<ProjectReference Include="R.csproj" PackVersion="[_,2.0.0]"/>  <!-- upper limit -->
```

In this case we would be using `_` as a placeholder for the actual version of the referenced project.

**Comment by madelson** [comment]
As a side note, we used to use an exact version reference (e. g. `[1.2.3]`) but we've shifted to using a slightly different form `[1.2.3, 1.2.4)` instead. For non-prerelease packages this is the same bound, but the benefit of this construct is that it makes it easy to work with prerelease packages since you are still compatible with `1.2.4-alphaXX`.

**Comment by jam40jeff** [comment]
Any movement on this? I have the same need (to use the `=` constraint on project reference dependencies rather than `>=`).

**Comment by bencyoung** [comment]
Is this possible to hack up as a custom task without re-writing all of the MsBuild NuSpec generating code? It makes it hard to do proper semantic versioning at the project level if you can't control the dependency ranges generated for ProjectReferences...

**Comment by jwosty** [comment]
I'm running into this problem and it is making things very tricky

**Comment by aortiz-msft** [comment]
Duplicate of https://github.com/NuGet/Home/issues/5525.
