### ISSUE TITLE
Can use/ship nuget.exe along with my custom setups(exe)

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7214]
Hi,

I have used the nuget.exe in my custom setup (like create the MVC samples along with my assemblies) for this I have used the nuget.exe to install the microsoft NuGet packages for the MVC sample while creating the application by my exe. For this I need to ship nuget.exe along with my project. 

Can i use this along with my exe?
Is this legal or not?
If not means, how can I use this along with my exe?

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Hi,

Could you please provide the solution regarding this?

Thanks,
Ganesan R.

**Comment by rohit21agrawal** [comment]
you can find the license for using nuget.exe here at : https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/LICENSE.txt
