### ISSUE TITLE
NuGet.ProjectModel 4.8.0 doesn't exist

### ISSUE THREAD

**Issue by lbargaoanu** [NuGet/Home#7215]
Trying to install NuGet.Commands 4.8.0.
Unable to resolve dependencies. 'NuGet.ProjectModel 4.8.0-preview4.5321' is not compatible with 'NuGet.Commands 4.8.0 constraint: NuGet.ProjectModel (>= 4.8.0)'.

**Comment by rohit21agrawal** [comment]
these packages have been pushed. sorry for the inconvenience.

**Comment by lbargaoanu** [comment]
Thanks.
