### ISSUE TITLE
Operated failed. No projects supported by NuGet in the solution throws for a upgraded NetCore project

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#7216]
From https://developercommunity.visualstudio.com/content/problem/139176/operated-failed-no-projects-supported-by-nuget-in.html?childToView=315343#comment-315343 

For a working example of this error, open Lynda.com, go to the Course named Learning Entity Framework Core. The instructor provides sample code written as a console app for .net core 1.0

On first opening the first solution, it asks if you wan to upgrade the solution with a 1 way upgrade. choose "Yes".
Once it has finished upgrading and has opened the solution, you will notice the Microsoft.NETCore.App(1.0.4) has warning symbols on it (under Solution 'DemoConsole' > src > DemoConsole > Dependencies > SDK)
Go to the tools menu, and choose Manage NuGet Packeges for Solution
You will see the error message "Operation Failed. No project supported by NuGet in the solution"

**Comment by thinkOfaNumber** [comment]
This error seems to go away after I close and reopen VS2017 before selecting "Manage NuGet Packeges for Solution" again.

**Comment by jainaashish** [comment]
@thinkOfaNumber did you have the same repro as mentioned above?

**Comment by thinkOfaNumber** [comment]
@jainaashish yes, although I didn't try with the OPs repository. From memory I think I used https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-aspnetcore

**Comment by kylef000** [comment]
Tangentially related to this issue, but I ran into a similar issue where I migrated a solution using a project.json and .xproj file to VS2017 and had the same error messages. @thinkOfaNumber's solution worked for me.

**Comment by lemarcelo** [comment]
I just close the Visual Studio and open again, and solved for me.

**Comment by yangs2016** [comment]
Same here - just closed VS and re-opened; worked for me now.

**Comment by HenrikRClausen** [comment]
Old thread, resurfaced problem: I am getting this with a fresh, skeleton project in VS2017. Just a few classes, nothing functional in that project yet. Any ideas?

**Comment by qxecutioner** [comment]
> This error seems to go away after I close and reopen VS2017 before selecting "Manage NuGet Packeges for Solution" again.

Same in VS2019

**Comment by RafaelSilva30** [comment]
> > This error seems to go away after I close and reopen VS2017 before selecting "Manage NuGet Packeges for Solution" again.
> 
> Same in VS2019

Can confirm

**Comment by johanskoldekrans** [comment]
Same problem with VS 2019 Preview (16.4.0 Preview 2.0). Works after restart.

**Comment by bryancass** [comment]
Same problem with VS 2019 v16.4.2.

**Comment by mia01** [comment]
Same thing with VS 2019 v 16.3.3

**Comment by rasavant-ms** [comment]
Same thing with VS Community 2019 v 16.5.0

**Comment by martinrrm** [comment]
Hi everyone, I have tried to repro this, and I was unsuccessful, please try again in the latest version of Visual Studio and if the problem continues, please open a new bug or comment in this one.

**Comment by lukedukeus** [comment]
I am having this in 17.3.0 and closing and reopening is not helping.

Edit: Reinstalled Visual Studio, it is working now.

**Comment by kevin-marshall** [comment]
I was experiencing this same problem, but I figured out that I only had the problem with a specific project. In my case we included the "Visual Studio Installer" plugin in the solution. When I removed the installer project and selected  'Manage NuGet Packages for Solution' the package manager popped up as expected.
