### ISSUE TITLE
-AllVersions does not return full list of available package versions from UNC Source

### ISSUE THREAD

**Issue by ddspectron** [NuGet/Home#7218]
## Details about Problem
NuGet.exe v4.7.0, v4.7.1 and v4.8.0  all exhibit this bug.

I have seen this on Window 7 Professional.

Worked before? If so, with which NuGet version:
NuGet v3.4.4 is okay, slower, but does return the full list of versions.

## Detailed repro steps so we can see the same problem
1.  Have a local folder of packages of the same name with different versions

2.  Run nuget.exe init -Source \\UNC\path

3. Run nuget.exe list -Source \\UNC\path -AllVersions
...

### Verbose Logs
This is the output using the working version: v3.4.4:
H:\>c:\Vendor\ExternTools\NuGet_3_4_4\nuget.exe list StructurePusher -verbosity detailed -Source <SOMETHING> -AllVersions
NuGet Version: 3.5.0.1996
StructurePusher.x64
 6.16.9999.3038
 NeonConnect Component

StructurePusher.x64
 6.16.9999.3033
 NeonConnect Component

StructurePusher.x64
 6.16.9999.3034
 NeonConnect Component

StructurePusher.x64
 6.16.9999.3035
 NeonConnect Component

StructurePusher.x64
 6.16.9999.3036
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3038
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3033
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3034
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3035
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3036
 NeonConnect Component

This is the output from v4.7.0:
H:\>c:\Vendor\ExternTools\NuGet_4_7_0\nuget.exe list StructurePusher -verbosity detailed -Source [SOMETHING] -AllVersions
NuGet Version: 4.7.0.5148
StructurePusher.x64
 6.16.9999.3038
 NeonConnect Component

StructurePusher.x86
 6.16.9999.3038
 NeonConnect Component

It only returns the latest version of the packages found.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/4537
