### ISSUE TITLE
[Area:NuGetizer] NuGetizer3000-VS2017.0.2.6.vsix Installation Failure

### ISSUE THREAD

**Issue by DiggaTheWolf** [NuGet/Home#7219]
I have Visual Studio 2017 Enterprise 15.8 installed on Windows 10 x64 and I cannot get the NuGetizer3000-VS2017.0.2.6.vsix to install successfully.

Please see the attached log file.

[VSIXInstaller_0d60e2aa-933e-424f-b455-d7bb70d22d77.log](https://github.com/NuGet/Home/files/2306248/VSIXInstaller_0d60e2aa-933e-424f-b455-d7bb70d22d77.log)

**Comment by rohit21agrawal** [comment]
CC: @kzu

**Comment by DiggaTheWolf** [comment]
Do you have any update when this will be worked on? I need to get this installed into VS 15.8.n

**Comment by DiggaTheWolf** [comment]
Please can you supply an installer for Visual Studio 2017 15.8._n_ IDE?

**Comment by DiggaTheWolf** [comment]
I've remedied this myself by running the vsixinstaller.exe manually using the following steps:

- Downloaded and saved the VSIX from [NuGetizer3000-VS2017](http://bit.ly/nugetizer-2017)
- Ran the following in the VS command prompt to remove any currently installed products and install the VSIX, replacing PathToVSIX with my path to VSIX:

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Windows\System32>vsixinstaller

C:\Windows\System32>vsixinstaller /q /a /u:"NuGet.Packaging"

C:\Windows\System32>vsixinstaller /a /q "C:\PathToVSIX\NuGetizer3000-VS2017.vsix"

C:\Windows\System32>

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

You can use a [packaging project](https://www.clarius.org/nugetizer/#packaging-projects) supported out of the box by Visual Studio and NuGetizer.
