### ISSUE TITLE
Hang when switching target frameworks

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#722]
Visual Studio becomes unresponsive when changing .NET Framework version when Entity Framework 6 is added to a solution.

Steps to reproduce:

1. Create a new empy solution
2. Add a class libary project (Lib).
3. Use NuGet to add EF6 to the project.
4. Add a console app project (Demo).
5. Set the .NET version to 4.6 for Lib.
-- Visual Studio hangs. When restarted setting has worked.
6. Repeat for Demo.
-- Visual Studio hangs again.

**Comment by yishaigalatzer** [comment]
@danliu please try to repro with the latest bits

**Comment by pranavkm** [comment]
Not seeing this issue with 3.0-rtm build 514
