### ISSUE TITLE
nuget is not packaging .pdf files and some others.

### ISSUE THREAD

**Issue by iannazzi** [NuGet/Home#7221]
Place a .pdf file in `content` folder or `contentFiles` folder, pack it up, consume it, and no .pdf file shows up. .zip files are also missing. In the .nuspec file I have specifically asked for the file. I have also not specifically asked for the files, does not seem to matter. I have also renamed the .pdf file, removed the3 extension, and it still will not pack.

```
<contentFiles>
     <files include="**" copyToOutput="true" />
</contentFiles>
```
Additionally I am expecting the files to magically show up in `\bin\debug` so I can reference the path on the consuming project, but no luck.

An alternate approach is to use <files> which copies files to the package directory, however I do not know the package name due to changing versions, so trying to get to the files is difficult

**Comment by rohit21agrawal** [comment]
contentFiles is just a pointer to file inside the package. To actually include the file, you also need to add:
```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <id>routedebugger</id>
        <version>1.0.0</version>
        <authors>Jay Hamlin</authors>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Route Debugger is a little utility I wrote...</description>
    </metadata>
    <files>
        <file src="bin\Debug\*.dll" target="lib" />
    </files>
</package>
```
Note the files element outside of metadata.

**Comment by iannazzi** [comment]
@rohit21agrawal  that is not what I am experiencing....

From my experience <files> will put the files within the package folder. I want the files to show up within the consumer directory. I am successfully using <files> + a hard coded path to the package to access static content, when the package version changes I need to update the path. No biggie. Placing files within content folder or contentFiles folder of the package brings over *some* files to the consumer directory. It would be nice if they all came over.

**Comment by rohit21agrawal** [comment]
can you share a repro project and attach it as a zip?
