### ISSUE TITLE
Nuget keep asking for proxy credentials when running install package command line

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7225]
@jhenyffer commented on [Thu Aug 16 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1018)

Hello, is there a way to run nuget.exe install command with the credentials setted in the command? 
What I need is to install the packages without having to provide the credentials manually.

I have already tryied to set the credentials in Nuget.config, it worksed for some time, but all of a sudden it stoped working.

The thing is that I am using proxy, I have done the proxy configuration on NuGet.config, but nuget keeps asking for the credentials.

Can you plese advise me? I have spent a lot of time on this already...

Thanks!

**Comment by rohit21agrawal** [comment]
@nkolev92 can you help @jhenyffer ?

**Comment by nkolev92** [comment]
We're already having a discussion in https://github.com/NuGet/docs.microsoft.com-nuget/issues/947#issuecomment-417798213.

**Comment by PatoBeltran** [comment]
Closing this issue as no more information was provided.
