### ISSUE TITLE
Clarify that props and targets assets will not be imported through transitive dependencies

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7226]
@geeeyetee commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997)

The phrase "_as can projects that consume AppLogger_" in the following sentence is incomplete and may mislead some developers.

> AppLogger can consume the targets and props from Contoso.Utility.UsefulStuff, as can projects that consume AppLogger.

The sentence is in the section "_Controlling dependency assets_" on the "_Package references (PackageReference) in project files_" page. The following references detail the fact that targets and props can be made to `Import` to projects that directly consume a package, but not to projects that indirectly (transitively) consume a package.

- https://github.com/NuGet/Home/issues/6934 "_Transitive PackageReference packages do not contribute build logic_"
- https://github.com/NuGet/Home/issues/6091 "_Change the default behavior of build dependency asset to transitive_"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff707668-94d6-25a5-9139-b18cc1b6b446
* Version Independent ID: 494847b9-4894-0beb-7ffa-39a2359999fa
* Content: [NuGet PackageReference format (package references in project files)](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets)
* Content Source: [docs/consume-packages/Package-References-in-Project-Files.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-References-in-Project-Files.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

---

@nkolev92 commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409311468)

This is only by default. 
Package authors can build packages correctly to make their packages bring in the transitive dependencies. 

---

@geeeyetee commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409339790)

@nkolev92 - How can a project **`Import`** a `.props` or `.targets` file that is contained in a transitively-referenced `PackageReference`?

EDIT
My understanding is that the "by default" aspect concerns inclusion of the `.props` and `.targets` in the `.nupkg`. The article does cover how to overcome that. However, a consuming project will will only reference those files in `Import` elements when the package is a directly-included `PackageReference`-- there is no way to make that happen when the package is indirectly/transitively included.

---

@nkolev92 commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409340942)

Say you have the following:

Project 1 -> Package A -> Package B, where Package B has targets. 

When building Package A, the author of Package A can choose to allow the Package targets to flow transitively. 

Package A could be built with Package B as a reference like this:
> <PackageReference Include="B" PrivateAssets="content;analyzers"/>

The default PrivateAssets value is `build;content;analyzers` per https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

That would preserve that information in the nuspec of Package A when packed. 

Then the consumer of Package A will be happy. 

Note that the options are more limited when it comes to the Package A consumer. 

---

@geeeyetee commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409343119)

@nkolev92 - Thanks for your reply-- it crossed path with my "EDIT" above. Please let me know if that clarification makes sense to you and let me know if it is correct. Based on my own experience/testing and research over the last couple of days, I believe it is.

---

@geeeyetee commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409343830)

So in your example, if `PrivateAssets` is set to `none` Project 1 will theoretically have access to the targets files, but it will not import them.

---

@geeeyetee commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409344123)

... whereas the project for  Package A will import the targets.

---

@nkolev92 commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409345158)

>  Project 1 will theoretically have access to the targets files, but it will not import them.
I wouldn't say it has access, but you are correct, it won't import them. 

---

@bording commented on [Tue Jul 31 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/997#issuecomment-409350983)

>I wouldn't say it has access, but you are correct, it won't import them.

@nkolev92 Are you sure about that? I've definitely authored a package that has package references with `PrivateAssets=none`, and when projects consume that package, they definitely get the props/targets of the transitively referenced packages in their nuget.g.props/nuget.g.targets files.

**Comment by rohit21agrawal** [comment]
@karann-msft what is the issue here? the customer hasn't replied to @nkolev92 reply. i am going to close this issue for now, you can reactivate it on the docs side.

**Comment by nkolev92** [comment]
This is a docs discussion **still** anyways. 
If anything there's docs improvement work that needs to be done. 
Shouldn't the issue stay there?

**Comment by karann-msft** [comment]
@nkolev92 I disagree. It is not a docs issues. The discussion went in the direction of getting a repro, etc. and docs repo is not the place for that. Once you determine what needs changing and what should be updated in the docs, feel free to open a PR on the docs repo.
