### ISSUE TITLE
Add pack extension point for including debug symbols

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#7234]
`TargetsForTfmSpecificBuildOutput` can't be used to add supplementary .pdb files to only the "symbols.nupkg" file.

Please add an extension point like `TargetsForTfmSpecificDebugSymbolsOutput`.

**Comment by rohit21agrawal** [comment]
the .pdb files are only added to the symbols.nupkg file. you can include pdb files using ``` TargetsForTfmSpecificBuildOutput ``` and they will only be included as part of symbols.nupkg.

If you are seeing some other behavior, please share a repro project.

**Comment by ghost** [comment]
`TargetsForTfmSpecificBuildOutput` populates into
```
BuildOutputInPackage="@(_BuildOutputInPackage)"
```

Unless I'm misunderstanding `PackTask`, pdb files must be populated into
```
TargetPathsToSymbols="@(_TargetPathsToSymbols)"
```

**Comment by rohit21agrawal** [comment]
symbols.nupkg have have both BuildOutputInPackage AND TargetPathsToSymbols added to it.

**Comment by ghost** [comment]
Yes, but `TargetsForTfmSpecificBuildOutput` does not populate `TargetPathsToSymbols`.

**Comment by rohit21agrawal** [comment]
have you tried this out with an example yet?

**Comment by ghost** [comment]
Yes, although I don't have the example anymore to share.  The .pdb files populated by `TargetsForTfmSpecificBuildOutput` were filtered out because `BuildOutputInPackage` is filtered according to `AllowedOutputExtensionsInPackageBuildOutputFolder`.

**Comment by rohit21agrawal** [comment]
AllowedOutputExtensionsInPackageBuildOutputFolder filters files for the main nupkg, not the symbols.nupkg. For symbols.nupkg, AllowedOutputExtensionsInSymbolsPackageBuildOutputFolder  is what filters files, and that includes .pdb extension

**Comment by ghost** [comment]
https://github.com/NuGet/NuGet.Client/blob/25225bb1b55bc17e52cb6fa02335d559c12ccd18/src/NuGet.Core/NuGet.Commands/MSBuildProjectFactory.cs#L122-L124

For the main .nupkg,  
`TargetPathsToAssemblies` is filtered by `AllowedOutputExtensionsInPackageBuildOutputFolder` and
`TargetPathsToSymbols` is filtered by `AllowedOutputExtensionsInPackageBuildOutputFolder`.

For symbols.nupkg,  
`TargetPathsToAssemblies` is filtered by `AllowedOutputExtensionsInPackageBuildOutputFolder` and  `TargetPathsToSymbols` is filtered by `AllowedOutputExtensionsInSymbolsPackageBuildOutputFolder`.

(`TargetPathsToAssemblies` is [populated from](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTaskLogic.cs#L77) `BuildOutputInPackage`)

Never is `TargetPathsToAssemblies` filtered by `AllowedOutputExtensionsInSymbolsPackageBuildOutputFolder`.
