### ISSUE TITLE
Package Manager UI lazy loading needs caching

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#724]
From Visual Studio feedback:

lazy loading is nice, but still gives more interruptions than it shuold be. Try cache list locally? After all it's usually appended, so worst case scenario i will see an update few seconds later, but i will see list right away. Also, I can see 5 packages on my screen, when i scroll down i can see loading bar that loads 5 more. Why not load 100 instead? I doubt that would cause performance issue at server side, but it would give me probably all packages i was trying to find.

**Comment by yishaigalatzer** [comment]
This was already fixed. and we are already tracking further performance improvements.
