### ISSUE TITLE
Cancelled task throws 

### ISSUE THREAD

**Issue by bruno-garcia** [NuGet/Home#7240]
I'm using the NuGet client v 5.1:

```xml
<PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
````
When gracefully stopping my service (which trigger the cancellation token) I encounter errors:

```
 NuGet.Protocol.Core.Types.FatalProtocolException: The source does not have a Search service!
```

The error is thrown from [here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Protocol/Resources/RawSearchResourceV3.cs#L113).

More specifically, because [here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Protocol/Resources/RawSearchResourceV3.cs#L92), it ignores **all** errors, including a `OperationCancelledException`. Just above it only invokes the request if the token is not cancelled.
So it will prepare argument as many times as there are `_searchEndpoints` but will simply skip over the calls and end up throwing the `FatalProtocolException`

Not only this error is misleading but it's a problem as it floods sentry.io (I have multiple calls in-flight at once).

I end up with lots of events, each with lots of exceptions with this stack trace:

![image](https://user-images.githubusercontent.com/1633368/44622170-bab77e00-a8b3-11e8-99f0-d988ba45ee09.png)

**Comment by nkolev92** [comment]
Just adding the relevant metadata to this issue @bruno-garcia. 

We really appreciate you following up with a PR.
