### ISSUE TITLE
Clearing global-packages cache causes restore to fail for missing packages with misleading errors

### ISSUE THREAD

**Issue by StephenCleary** [NuGet/Home#7242]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.7.1.5393

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): win10 current

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a unique package that isn't available in public feeds. Place this in a local repo (e.g., `C:\nuget`).

2. Create a project and install that package. I used a netstandard library project, but I believe any project type would repro.

3. Delete the project's `bin` and `obj` directories (and solution `packages` folder if necessary). Delete the unique package from your local repo (e.g., `C:\nuget`).

4. Clear your local `global-packages` cache, e.g., `nuget locals global-packages -Clear`.

5. Attempt to build or restore packages.

What you get is an error from NuGet restore:

```
The local source 'C:\Users\...\.nuget\packages\' doesn't exist.
```

(this is much less easy to find when building in Visual Studio)

If building, you get another error:

```
Assets file '...\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
```

which is certainly misleading, since it actually means "NuGet package restore failed."

**Comment by nkolev92** [comment]
Just to be sure I understand the issue, the misleading error you are referring to, is the one during the build?
@StephenCleary 


The problem with the error message being difficult to find in Visual Studio seems to be the same as the following one: 
https://github.com/NuGet/Home/issues/7245

**Comment by StephenCleary** [comment]
Yes, the misleading error is if you try to build. If you just try to restore, then you get the actionable error.

**Comment by nkolev92** [comment]
Unfortunately, I am not sure we can do much here without some more drastic changes.

Restore is the only thing that understands why it failed. Build can't know that information as they are separate actions. 

This is made better with the dotnet commands where restore is implicit.

**Comment by PatoBeltran** [comment]
Will close this issue as we don't seem to have more information, and as @nkolev92 mentioned, there is not a lot we can do without more drastic changes since we don't control the build.
