### ISSUE TITLE
[Test Failure] The ‘custom.lock.json’ file is empty after installing PR packages while ‘NuGetLockFilePath’ set to ‘custom.lock.json’ file path

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7243]
## Details about Problem
NuGet version: NuGet Client dev-asja-projectLockFile\5.0.0.289
VS Version: D15.8stg 28020.3001
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps
1. Create a C# Class Library (.NET Framework 4.6.1) via VS.
2. Create a blank ‘custom.lock.json’ file at project directory (alongside *.csproj file).
3. Set MSBuild property “NuGetLockFilePath” to relative path to the above ‘custom.lock.json’ file 
4. Install several packages with PackageReference format.
5. Check the ‘custom.lock.json’ file at project directory (alongside *.csproj file).
## Expected
There are the packages details show in ‘custom.lock.json’ file. 
## Actual
The ‘custom.lock.json’ file is empty as below screenshot.
![customlockjsonisempty](https://user-images.githubusercontent.com/20632625/44698523-c9e32b00-aa6f-11e8-9ef0-89f02092783f.png)

**Comment by nkolev92** [comment]
//cc @jainaashish

**Comment by jainaashish** [comment]
@v-luzh thanks for reporting this. This was reproducible with relative path which I'll fix with the original PR. But it was working fine with absolute path. So try again with absolution path, and remove double quotes while setting that path.

**Comment by v-luzh** [comment]
@jainaashish , Yes, you are right. The absolute path (without quotes) works. Updated the repro steps.

**Comment by jainaashish** [comment]
@v-luzh please dont use double quotes (") while setting this msbuild property and then it will work fine for you.

**Comment by v-luzh** [comment]
@jainaashish I can still repro this issue when setting 'NuGetLockFilePath' to the **relative** path (no quotes) of ‘custom.lock.json’ file on D15.8stg 28020.3001+NuGet Client dev-asja-projectLockFile\5.0.0.465. Not very sure if it is fixed on above NuGet Client build. Could you please help to confirm the fix build and the correct way to set the relative path? I will verify it ASAP.Thanks a lot!

**Comment by jainaashish** [comment]
@v-luzh relative path is always to the *.csproj file. If you have `project.csproj` and `custom.lock.json` in the same directory then set `<NuGetLockFilePath>custom.lock.json</NuGetLockFilePath>` and try to repro it.

And you can use the latest dev or release-4.9.0-preview3 build to verify this.
