### ISSUE TITLE
Errors due to missing/failing sources are inconsistently shown in solution explorer vs the error list 

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7245]
From email:

There is a more widespread issue here of NuGet warnings never showing up in the error list. We see this in every project we maintain.
•	Can't connect to NuGet feed? No error from that, but hundreds of errors from missing types
•	Can't find the right package version? No errors from the restore, just missing types or methods
It's extremely frustrating to kick off a build that needs a new version of a dependency and just see a wall of errors, more so when the error that matters "we couldn't even find your feed" isn't even in the list. I think that:
•	NuGet errors and warnings should always appear in the errors list.
•	We should never see a yellow warning symbol on the references tree unless it's also in the errors list.

------------
We have noticed (guess since introducing .net core 2.1) increasing number of warnings related to nuget in project dependency hive. 
![image](https://user-images.githubusercontent.com/14800916/44736473-2d874b80-aaa4-11e8-9665-f90deabcbe24.png)

In many cases we get a more detailed message about issue. But I see this warning very often without any message as shown in picture above.
Would it be possible to always provide error (warning), which caused this issue, assuming it is an issue?
Is there any other way to figure out the issue? Enabling build full trace?

**Comment by nkolev92** [comment]
This is reproable. 
Auto-restore does not seem to propagate this error. 

Rebuild sometimes succeeds as well despite not being able to access the source. 

If you do a 2nd restore though after the auto restore, the error does show up in the window. 

Still need to confirm if this is a regression.

**Comment by NickCraver** [comment]
For those trying to repro in other ways, here was my super quick demo showing most of the issues at once:

![nugeterrors](https://user-images.githubusercontent.com/454813/44805143-6d782c80-ab91-11e8-8410-810d35d15647.png)

**Comment by nkolev92** [comment]
I was able to repro this on the latest D15.7, so it doesn't look like a regression from that specific release.

**Comment by nkolev92** [comment]
I think @rrelyea's work in https://github.com/NuGet/NuGet.Client/pull/3520 will fix this, but he'll know better :)

**Comment by nkolev92** [comment]
Restore Triage: Bumping priority as a good `quality` task.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9688.

**Comment by nkolev92** [comment]
Related scenario is mentioned in https://github.com/NuGet/Home/issues/10424.
