### ISSUE TITLE
Packing from Visual Studio does not include files defined in <files>

### ISSUE THREAD

**Issue by gthvidsten** [NuGet/Home#7246]
I'm using the latest Visual Studio (15.8.1) and I'm looking into the "Pack" feature to automatically create NuGet packages.

I've created them manually earlier and I had a .nuspec file ready which includes some additional files in the `<files>` element. However, these files are not included in the package when I use the "Pack" feature.

I found #3678, which is a bit unclear, but I've interpreted that issue to conclude that the "Pack" feature does not use the .nuspec file.

If my interpretation is correct, how can I make the "Pack" feature include additional files?

**Comment by rohit21agrawal** [comment]
To pack additional files which are not framework specific, refer to : https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#including-content-in-a-package 

For framework specific files, refer to: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#advanced-extension-points-to-create-customized-package

**Comment by gthvidsten** [comment]
Do you know of any way to do this automatically or through the GUI, without having to edit the .csproj file?

**Comment by rohit21agrawal** [comment]
no. that's not possible as of now.

**Comment by PatoBeltran** [comment]
closing this as it seems like the question has been answered, please feel free to reopen if needed.

**Comment by gthvidsten** [comment]
Yes, this has been answered. Sorry for not providing any updates.
I added the following to my .csproj file:
```xml
<Target Name="BackendIncludes">
  <ItemGroup>
    <BuildOutputInPackage Include="..\Some\Other\Folder\$(OutputPath)MyFile.dll">
    </BuildOutputInPackage>
  </ItemGroup>
</Target>
```
And now MyFile.dll is also included in the NuGet package generated when I click "Pack" from the project context menu in Visual Studio.
