### ISSUE TITLE
Unable to resolve 'System.Net.Http (>= 4.3.1)' for '.NETFramework,Version=v4.6.1'

### ISSUE THREAD

**Issue by sathyab18** [NuGet/Home#7247]
I got this below error when i run applcation in vs2017

Error	NU1100	Unable to resolve 'System.Net.Http (>= 4.3.1)' for '.NETFramework,Version=v4.6.1'.	
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.PerfCounterCollector (>= 2.4.1)' for '.NETFramework,Version=v4.6.1'.	
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel (>= 2.4.0)' for '.NETFramework,Version=v4.6.1'.	
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.Agent.Intercept (>= 2.4.0)' for '.NETFramework,Version=v4.6.1'.
Error	NU1100	Unable to resolve 'System.Net.Http (>= 4.3.1)' for '.NETFramework,Version=v4.6.1/win7-x86'.	
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.PerfCounterCollector (>= 2.4.1)' for '.NETFramework,Version=v4.6.1/win7-x86'.
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel (>= 2.4.0)' for '.NETFramework,Version=v4.6.1/win7-x86'.	
Error	NU1100	Unable to resolve 'Microsoft.ApplicationInsights.Agent.Intercept (>= 2.4.0)' for '.NETFramework,Version=v4.6.1/win7-x86'.

**Comment by PatoBeltran** [comment]
Hey, @sathyab18 thanks for opening this issue. Can you give me a little more information on how you got this error? It would be ideal if you could provide me with a project that has this issue so I can reproduce it and investigate the cause. 

Thanks!

**Comment by sathyab18** [comment]
Hey,
Actually i tried to study about rent a cab app.
https://www.c-sharpcorner.com/article/angular-demo-application-with-asp-net-core-mvc-rent-a-car/

So i installed vs studio 2017 community version. and tried to open this solution and i got this error.
![screen](https://user-images.githubusercontent.com/7556078/44890795-a6cbac00-acf9-11e8-812a-f100fffdac0a.png)

Thanks!

**Comment by PatoBeltran** [comment]
I tried downloading that project and it was able to restore all those packages correctly. Are you sure you have the correct SDK version? you can download the latest full framework and netcore sdk [here](https://www.microsoft.com/net/download). If that doesn't make it work, try doing a VS repair, you can use the VS installer for that.

**Comment by sathyab18** [comment]
Hey,
I have updated the SDK . Issue fixed.
Thank you so much .
