### ISSUE TITLE
NuGet.Build.Tasks.Pack should be a development dependency

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#7249]
This package can be manually consumed by a legacy .csproj with package reference to enable `msbuild /t:pack`. This is a workaround for https://github.com/NuGet/Home/issues/5979.

We should set `<developmentDependency>true</developmentDependency>` on the output nupkg.

/cc @rohit21agrawal @chenriksson

**Comment by rohit21agrawal** [comment]
it would have been easier to send a PR than to file an issue :P
