### ISSUE TITLE
Nugetizer: PackageTypes metadata

### ISSUE THREAD

**Issue by iskiselev** [NuGet/Home#7250]
Nugetizer do not support PackageTypes metadata generation for nuspec files. It even defines appropriate metadata in NuGet.Build.Packaging.targets, but don't use it in CreatePackage task.

**Comment by PatoBeltran** [comment]
cc. @kzu

**Comment by kzu** [comment]
@iskiselev would you consider sending a PR to https://github.com/NuGet/NuGet.Build.Packaging/blob/dev/src/Build/NuGet.Build.Packaging.Tasks/CreatePackage.cs?

Thanks!

**Comment by iskiselev** [comment]
PR created: NuGet/NuGet.Build.Packaging#168

**Comment by kzu** [comment]
This has been contributed and merged a while ago. Plz feel free to close.
