### ISSUE TITLE
NU3008: The package integrity check failed when installing System.Management.Automation 6.0.4.

### ISSUE THREAD

**Issue by GKlush** [NuGet/Home#7251]
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe
NuGet version (x.x.x.xxx): 4.5.1.4879
dotnet.exe --version (if appropriate): 2.1.302
OS version (i.e. win10 v1607 (14393.321)): win 10 v1607 (14393.0)
Worked before? If so, with which NuGet version: 4.5.1.4879

## Detailed repro steps so we can see the same problem
1. Build project.
2. Installing System.Management.Automation 6.0.4.
3. NU3008: The package integrity check failed.

**Comment by PatoBeltran** [comment]
Hey @GKlush, thanks for opening this issue! This failure might actually be a good thing! 

Since 4.6.2 nuget does integrity and trust validation on signed packages. 

This error means that you downloaded a package, and while doing the validation before extracting, the contents of the package seemed different from the ones the signature announced. This could be because someone tampered with the package since it was signed! 

Where did you get the package from? is it possible to download the package manually and verify it using `nuget.exe verify -signatures <package_path>`? This will basically perform the same validation that install is doing. If this still fails for that same reason it means the package is bad because it has been tampered with and it is not safe to use.

I'm curious about how you got this error through `dotnet.exe` because we haven't added any support for signature validation on that client. Are you sure you are seeing this error when using `dotnet.exe`?

**Comment by GKlush** [comment]
Tank you. You are right. Excuse my please. The command "dotnet restore" works very well. I get error when i execute command "nuget restore" and then i get empty folder ".nuget\packages\system.management.automation".
Below there are logs of command: nuget.exe verify -signatures .nuget\packages\system.management.automation\6.0.4\system.management.automation.6.0.4.nupkg

Verifying System.Management.Automation.6.0.4
C:\Users\User\.nuget\packages\system.management.automation\6.0.4\system.management.automation.6.0.4.nupkg

Signature Hash Algorithm: SHA256
Signature type: Author
Verifying the author primary signature with certificate: 
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
  SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 26.02.2018 3:00:00 to 27.01.2021 15:00:00

Timestamp: 14.08.2018 7:18:51

Verifying author primary signature's timestamp with timestamping service certificate: 
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
  SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 02.01.2017 3:00:00 to 02.04.2028 2:59:59

Signature type: Repository
nuget-v3-service-index-url: https://api.nuget.org/v3/index.json
nuget-package-owners: microsoft, PowerShellTeam
Verifying the repository countersignature with certificate: 
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
  SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 10.04.2018 3:00:00 to 14.04.2021 15:00:00

Timestamp: 14.08.2018 17:59:20

Verifying repository countersignature's timestamp with timestamping service certificate: 
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 23.12.2017 3:00:00 to 23.03.2029 2:59:59

Finished with 1 errors and 0 warnings.

**Comment by PatoBeltran** [comment]
Hey @GKlush, it is weird that it says that there was 1 error but there are no errors in the logs. Are you sure this is the complete log? Can you provide me with the package or a repo project where you see this restore failure so I can investigate on what is happening?

**Comment by PatoBeltran** [comment]
Closing this as there is not enough information for us to investigate it further. Feel free to reopen if you are still experiencing the same issue.

**Comment by nimDevOps** [comment]
I've also faced NU3008 but with another package Grpc.Core.1.17.1.
How I troubleshooted this: first I added nuget.exe install -Verbosity detailed ... 
That gave me more output.

I tried to install this package from company NugetServer server which is **http** source, 
and 'nuget install' command failed for any nuget.exe starting from 4.6.2 and later (validation of signed packages). Then I changed the source to **https://api.nuget.org/v3/index.json**.

It failed first time and I noticed following message :
**Retrieving package 'Grpc.Core 1.17.1' from 'C:\Users\myUser\.nuget\packages\'.**

which is the indication that nuget cache was used.
After cleaning cache folder myUser\.nuget\packages installation of Grpc.Core has been finally successful.

So I guess the recipie for the sucsessful installation in my case : 
- no cache
- https source

**Comment by amoghadithya007** [comment]
I am facing the same error, after trying to install Selenium WebDriver 3.141.0 to Visual Studio 2017. 
I have tried clearing the Nuget Cache, verifying the https source, restoring the package, downloading the package manually and installing it with the package manager console. But none of those methods work.

I am able to install "Selenium.Chrome.WebDriver" from the same source. This seems to be an issue with the "Selenium.WebDriver" package.

Any help would be highly appreciated.

Thanks

**Comment by nimDevOps** [comment]
Just tried from git.bash terminal, not a problem for me: (NuGet Version: 4.9.2.5706)
$ nuget install Selenium.WebDriver -Version 3.141.0  -Source https://api.nuget.org/v3/index.json -OutputDirectory ./out
Feeds used:
  C:\Users\build\.nuget\packages\
  https://api.nuget.org/v3/index.json



Attempting to gather dependency information for package 'Selenium.WebDriver.3.141.0' with respect to project './out', targeting 'Any,Version=v0.0'
Gathering dependency information took 263.05 ms
Attempting to resolve dependencies for package 'Selenium.WebDriver.3.141.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Selenium.WebDriver.3.141.0'
Resolved actions to install package 'Selenium.WebDriver.3.141.0'
Retrieving package 'Selenium.WebDriver 3.141.0' from 'C:\Users\build\.nuget\packages\'.
Adding package 'Selenium.WebDriver.3.141.0' to folder 'C:\Users\build\AppData\Local\Temp\2\out'
Added package 'Selenium.WebDriver.3.141.0' to folder 'C:\Users\build\AppData\Local\Temp\2\out'
Successfully installed 'Selenium.WebDriver 3.141.0' to ./out
Executing nuget actions took 481.85 ms

**Comment by relair** [comment]
I had same issue with Selenium WebDriver 3.141.0 and oddly enough when getting it by itself via `nuget install Selenium.WebDriver -Version 3.141.0 -Source https://api.nuget.org/v3/index.json ` it works. Since it is then cached it sort of resolved the issue for now.
