### ISSUE TITLE
Manage nuget packages solution level : dark theme VS update packages causes strange UI colours

### ISSUE THREAD

**Issue by Styxxy** [NuGet/Home#7253]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **VS UI**
NuGet version (x.x.x.xxx): the one provided with VS
VS version (if appropriate): **15.7.5**
OS version (i.e. win10 v1607 (14393.321)): **Windows 7**

Worked before? If so, with which NuGet version: **no**

## Detailed repro steps so we can see the same problem

0. Having Visual Studio configured to use **Dark theme**.

1. Having a solution with two projects. Both are non-SDK style projects.

2. One project has a nuget package installed but not the latest version (example: Newtonsoft.Json v10.0.3). The other project doesn't have any nuget package installed.

3. Manage nuget packages for the solution.

4. Go to the **Updates** tab.

5. Select the package to update, and press the Update button.

-->

6. The background of the version list of projects changes to other background than the dark theme.

![nuget-update-darktheme-pre](https://user-images.githubusercontent.com/1635825/44849912-e80d7e80-ac5b-11e8-8c8a-fe99ccf22569.png)

![nuget-update-darktheme-post](https://user-images.githubusercontent.com/1635825/44849914-eb086f00-ac5b-11e8-8ac6-fe9a08e81a86.png)

### Sample Project

Sample repository: https://github.com/Styxxy/Issue-Nuget-DarkTheme

**Comment by PatoBeltran** [comment]
@Styxxy this was fixed in https://github.com/NuGet/NuGet.Client/pull/2267 and was shipped in 4.8.0!

**Comment by Styxxy** [comment]
@PatoBeltran So in which VS version is this shipped, 17.8?
