### ISSUE TITLE
Feature Request - Provide capability to generate dependency graph

### ISSUE THREAD

**Issue by tomkerkhove** [NuGet/Home#7254]
With the new `csproj` format it no longer lists dependencies for packages that are being referenced with `PackageReference`.

This is great for the developer but in certain scenarios you'd like to have a full dependency graph of your project(s) in order to automate processes such as security scanning.

Currently `obj/project.assets.json` does generate this but this requires you to do a full build which is not interesting.

# Proposal

```shell
nuget generate dependency-graph --file foo.csproj
```

## csproj sample
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Owin" Version="4.0.0" />
  </ItemGroup>

</Project>
```

## Potential Output Format
I don't have an opinion on what the output should look like but this is a possible format:
```json
{
	"dependency-graph": [{
		"name": "Microsoft.Owin",
		"version": "4.0.0",
		"dependencies": [{
			"name": "Owin",
			"version": "1.0.0"
		}]
	}]
}
```

**Comment by maartenba** [comment]
May want to check:
* https://www.jerriepelser.com/blog/analyze-dotnet-project-dependencies-part-1/
* Or more visual: https://github.com/mholo65/depends (example: https://twitter.com/mholo65/status/1014128499987288069)

**Comment by tomkerkhove** [comment]
So there is no way to achieve this without building?

**Comment by tomkerkhove** [comment]
Looks like it, so I'm closing this one then.

**Comment by rrelyea** [comment]
by the way...`dotnet list package` is a tool to list the top level package references, and can include transitive. Even that requires that you restore the project.
