### ISSUE TITLE
ContentFiles: Embedded resources are always flattened

### ISSUE THREAD

**Issue by drieseng** [NuGet/Home#7255]
When a NuGet package is created with content files in a nested directory structure, the (manifest) resource names of the embedded resources that are created for these files do not contain the relative directory path (with slashes converted to dots).

### Steps to reproduce:

1. Create a **NuGet** package with the following content:

```
contentFiles
                any
                        any
                                sub
                                       myResource.txt
```

2.  In the **.nuspec** for this package, add the following fragment to the metadata element:

```xml
   <contentFiles>
        <files include="**" buildAction="EmbeddedResource" />
    </contentFiles>
```

3. Pack & Publish the **NuGet** package.
4. Create (for example) a **C# Console App** project named **ConsoleApp1** (with default namespace **ConsoleApp1**¨)  in Visual Studio (15.8).
5. Ensure that the default package management format is **PackageReference** in the *NuGet Package Manager Settings**.
6. Add a reference to the **NuGet** package that we published in step **3**.
7. Build the project.

### Expected result:

The **myResource.txt** file is embedded in the **ConsoleApp1.exe** assembly with the name 'ConsoleApp1.sub.myResource.txt'.

### Actual result:

The **myResource.txt** file is embedded in the **ConsoleApp1.exe** assembly with the name 'ConsoleApp1.myResource.txt'.

NuGet product used: VS UI (15.8.1)
OS version: Windows 7 Build 7601

**Comment by drieseng** [comment]
Suppose we have version **1.1.0** of a **OurCompany.Resources** NuGet package that contains a "any\any\images\logo.png" content file.

We reference this NuGet package in a **ConsoleApp1** project which has **C:\Temp\ConsoleApp1** as project directry, and build this project.

## Current behavior

The **ResolveNuGetPackageAssets** task creates the following item for the **logo.png** content file:

```
_NuGetContentItems=
  %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
      NuGetItemType=EmbeddedResource
      NuGetPackageId=OurCompany.Resources
      NuGetPackageVersion=1.1.0
```

This item in the **_NuGetContentItems** item group is then projected into an item in the **EmbeddedResource** itemgroup.

Next, a target path is assigned to each item in the **EmbeddedResource** item group using the **AssignTargetPath** task in the **AssignTargetPaths** target (in **Microsoft.Common.CurrentVersion.targets**):

```
Task Parameter:
  Files=
    %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
      NuGetItemType=EmbeddedResource
      NuGetPackageId=OurCompany.Resources
      NuGetPackageVersion=1.1.0
  Task Parameter:RootFolder=C:\Temp\ConsoleApp1
  Output Item(s): 
    _Temporary=
      %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
        NuGetItemType=EmbeddedResource
        NuGetPackageId=OurCompany.Resources
        NuGetPackageVersion=1.1.0
        OriginalItemSpec=%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
        TargetPath=logo.png
```

This task uses the project directory (**$MSBuildProjectDirectory**) as root directory to determine the (relative) target path for each embedded resource.  In case of content files that come from a referenced NuGet package, the full path (in **ItemSpec**) of the embedded resource is never relative to that root directory, and as such the file name of the content file is used as **TargetPath**.

The value of the **TargetPath** metadata item is subsequently used to create the manifest resource name.

Since, in case of resources coming from referenced NuGet packages, this is always the file name of the content file, we end up with a "flattened" resource name.

For our example, this resource name is **logo.png**.

## Proposal

The **ResolveNuGetPackageAssets** task adds a **Link** metadata containing the path of the "root" content folder for a given content file. when the **buildAction** is **EmbeddedResource**.

The value of this **Link** metadata is the path of the content file up to the `/contentFiles/{codeLanguage}/{TxM}` part.

In our example, this value would be `%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any`:

```
_NuGetContentItems=
  %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
      Link=%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any
      NuGetItemType=EmbeddedResource
      NuGetPackageId=OurCompany.Resources
      NuGetPackageVersion=1.1.0
```

The **AssignTargetPath** task already uses the value of the **Link** metadata item as **TargetPath** if it's available. 

For our example, this result of the **AssignTargetPath** task would then be:

```
Task Parameter:
  Files=
    %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
      Link=%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any
      NuGetItemType=EmbeddedResource
      NuGetPackageId=OurCompany.Resources
      NuGetPackageVersion=1.1.0
  Task Parameter:RootFolder=C:\Temp\ConsoleApp1
  Output Item(s): 
    _Temporary=
      %USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
        Link=%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any
        NuGetItemType=EmbeddedResource
        NuGetPackageId=OurCompany.Resources
        NuGetPackageVersion=1.1.0
        OriginalItemSpec=%USER_PROFILE%\.nuget\packages\ourcompany.resources\1.1.0\contentFiles\any\any\images\logo.png
        TargetPath=images\logo.png
```

Finally, we end up with **images.logo.png** as resource name.

## Next steps
Does this proposal seem feasible?
Do you want me to prepare a PR for this?

**Comment by PatoBeltran** [comment]
@tmeschter can you take a look at this?

**Comment by tmeschter** [comment]
1. What's behavior for SDK-based projects? Those use a different set of tasks and targets to read the project.assets.json file and generate MSBuild items; if we make a change we will need to do it in two places at once. And if they _currently_ have different behavior then we'll definitely need to deal with that, anyway.
2. What's the behavior when using packages.config rather than `PackageReference`?
3. Note this would be a breaking change--upgrading to a newer version of VS/MSBuild/SDK would change the names of some resources.

**Comment by drieseng** [comment]
@tmeschter I agree this would be a breaking change. I'll look into your questions.

**Note:**
To avoid naming conflicts across packages (hereby overwriting files or manifest resources of another package), we should actually also use the package name as prefix. This for both the 'Content' and 'Embedded Resource' build actions.

**Comment by tmeschter** [comment]
@drieseng @PatoBeltran I should elaborate: given that this is a breaking change, almost the only way we would do this is if packages.config or `PackageReference` in SDK-based projects work differently and we need to bring them all in line. In that case I expect we would change the `PackageReference` behavior to match the existing packages.config behavior unless there is some really compelling reason to pursue a different design.

While I agree the proposed design is better that's not enough to outweigh the potential harm to everyone dependent on the current behavior.

**Comment by wbrianwhite** [comment]
> Expected result:
The myResource.txt file is embedded in the ConsoleApp1.exe assembly with the name 'ConsoleApp1.sub.myResource.txt'.

Can you do a build step where you just rename the files to {parentfolder}.{filename}.{ext}?  Lets you keep your files the way you want, and get the results you want.

**Comment by nkolev92** [comment]
Copied to https://github.com/dotnet/NuGet.BuildTasks/issues/78
