### ISSUE TITLE
Normalize RestoreResult properties

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#7258]
Currently there are multiple properties in [`RestoreResult`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RestoreResult.cs) to identify existing assets file vs new assets file along which are used to identify when we need to write the assets file on disk. This has often resulted into more trouble since assets file schema keeps growing and there're always some or the other left over issues with comparison across platforms. Also, there is already `Status` field in this class to indicate whether restore was successful or not which is not effectively defined and utilized to differentiate all the different restore results.

As part of `Packages lock file feature` we're adding another field `NewPackagesLockFile` but instead of adding multiple fields, we're only adding single field and the idea is `RestoreCommand` will only populate this field when it either generated or updated as part of current restore.

So this is the tracking issue to update existing properties of assets file and cache file consistent with new lock file in dev16 along with:

- Normalize all existing properties (assets file, cache file, etc...)
- Enhance `Status` field from `boolean` to a better `enum` to represent different states of restore result
- Dont need a separate result class (`NoOpRestoreResult`) for noop, consolidate these different classes into single `RestoreResult`

**Comment by nkolev92** [comment]
Unlikely to make these breaking changes at this point. 
Low return of investment.
