### ISSUE TITLE
Visual Studio feedback: Uninstall process failures

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#726]
From Visual Studio feedback:

Uninstalling packages with new UI is a nightmare. The only thing that is done well - this is not a modal UI. Usability is terrible.

* remove dependencies checkbox is off screen quite often (long list of projects, limited vertical space on Surface 2 Pro, font sizes... its off screen too often)

* remove dependencies actually fails to find proper order of removal, I've played with some packages related to EF7 and attempt to uninstall them turned to be the real pain.

* Actions in combobox that doesn't keep state. Combobox is not great for actions. If I'm updating/removing few packages - i need to change selection constantly.

**Comment by yishaigalatzer** [comment]
We fixed the bulk of these suggestions.

The remaining item here it to address remove dependency order. We haven't heard any other specific feedback on this, and it is quite hard to reproduce.

Lets try to install/uninstall EF7 in a net45 project to see if this reproduces

**Comment by zhili1208** [comment]
did install/uninstall EF7 in a net45 project against 3.3, it didn't repro
