### ISSUE TITLE
Nuget package summary not supported in VS UI

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7260]
The summary field defined in the nuspec specification here: https://docs.microsoft.com/en-us/nuget/reference/nuspec#general-form-and-schema is not available in the Visual Studio UI.

Continuation of https://developercommunity.visualstudio.com/content/problem/175015/nuget-package-summary-not-supported-in-vs-ui.html?childToView=320389#comment-320389 per request of MS Staff.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/322074/nuget-package-summary-not-supported-in-vs-ui-1.html
VSTS ticketId: 672239_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

**Comment by nkolev92** [comment]
@rohit21agrawal @rrelyea 
This is regarding display the summary metadata in VS. 

However in the pack targets, we don't support the summary metadata per https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target?

Are we deprecating this?

**Comment by rrelyea** [comment]
Yes, we have decided to deprecate summary.
We show description in UI.
@anangaur - correct?

**Comment by anangaur** [comment]
We show summary if present else we show first few lines of description.
