### ISSUE TITLE
Uploading symbols always fails

### ISSUE THREAD

**Issue by vmelamed** [NuGet/Home#7261]
## Details about Problem
The small script below always fails at the last command:

```
dotnet clean --configuration Debug
dotnet build --configuration Debug --version-suffix beta.20
dotnet pack --include-symbols --include-source --configuration Debug --version-suffix beta.20
dotnet nuget push bin\Debug\ --source https://www.nuget.org
```
nuget push is trying to push the symbols package to nuget.org instead of smbsrc.net:

> info : Pushing vm.Aspects.Security.Cryptography.Ciphers.2.1.2-beta.20.nupkg to 'https://www.nuget.org/'...
> info :   PUT https://www.nuget.org/api/v2/package/
> warn : This package will only be available to download with SemVer 2.0.0 compatible NuGet clients,such as Visual Studio 2017 (version 15.3) and above or NuGet client 4.3 and above. For more information,see https://go.microsoft.com/fwlink/?linkid=852248.
> info :   Created https://www.nuget.org/api/v2/package/ 1782ms
> info : Your package was pushed.
> info : Pushing vm.Aspects.Security.Cryptography.Ciphers.2.1.2-beta.20.symbols.nupkg to 'https://www.nuget.org/'...
> info :   PUT https://www.nuget.org/api/v2/package/
> info :   Conflict https://www.nuget.org/api/v2/package/ 231ms
> error: Response status code does not indicate success: 409 (A package with ID 'vm.Aspects.Security.Cryptography.Ciphers' and version '2.1.2-beta.20' already exists and cannot be modified.).

Tried with just nuget push and all sorts of options but to no avail. Either I do not understand something and am doing it wrong, or there must be something broken, or the documentation is not up to date.

### NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): 

NuGet and dotnet.exe

### NuGet version (x.x.x.xxx):

4.7.1.5393

### dotnet.exe --version (if appropriate):

2.1.401

### VS version (if appropriate):

n/a

### OS version (i.e. win10 v1607 (14393.321)):

Microsoft Windows [Version 10.0.17134.228]

### Worked before? If so, with which NuGet version:

I think it worked 3-4 months ago...

### Detailed repro steps so we can see the same problem

See the script above

### Other suggested things

n/a

## Verbose Logs
nuget push bin\Debug\ -Source https://www.nuget.org/  -SymbolSource https://nuget.smbsrc.net/ -verbosity detailed

NuGet Version: 4.7.1.5393
Pushing vm.Aspects.Security.Cryptography.Ciphers.2.1.2-beta.21.nupkg to 'https://www.nuget.org/'...
  PUT https://www.nuget.org/api/v2/package/
WARNING: This package will only be available to download with SemVer 2.0.0 compatible NuGet clients,such as Visual Studio 2017 (version 15.3) and above or NuGet client 4.3 and above. For more information,see https://go.microsoft.com/fwlink/?linkid=852248.
  Created https://www.nuget.org/api/v2/package/ 1802ms
Your package was pushed.
Pushing vm.Aspects.Security.Cryptography.Ciphers.2.1.2-beta.21.symbols.nupkg to 'https://www.nuget.org/'...
  PUT https://www.nuget.org/api/v2/package/
  Conflict https://www.nuget.org/api/v2/package/ 1212ms
Response status code does not indicate success: 409 (A package with ID 'vm.Aspects.Security.Cryptography.Ciphers' and version '2.1.2-beta.21' already exists and cannot be modified.).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 409 (A package with ID 'vm.Aspects.Security.Cryptography.Ciphers' and version '2.1.2-beta.21' already exists and cannot be modified.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__18_0(HttpResponseMessage response)
   at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__32.MoveNext()

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

## Sample Project

https://github.com/vmelamed/vm/tree/dev/Aspects/Security/Cryptography/Ciphers

The batch files are in https://github.com/vmelamed/vm/tree/dev/Aspects/Security/Cryptography/Ciphers/build

**Comment by PatoBeltran** [comment]
Hey @vmelamed, thanks for opening the issue... this seems to be a bug... I was trying to repro it with the project you provided but I was not able to build it correctly (the build cmd failed because it couldn't find `vm.Aspects.Diagnostics.ObjectTextDumper with version (>= 2.0.3)`), could you provide me with a set of instructions on how to build it to properly generate the nupkg and symbols.nupkg to test this out?

Also, we recently released nuget 4.8.1, can you test this scenario with that and see if it is still an issue? You can get a copy here: https://www.nuget.org/downloads

Thanks!

**Comment by vmelamed** [comment]
Hi Patricio,

Thank you for investigating this. There seem to be a number of bugs in NuGet.exe which is disappointing. I will certainly help you as much as possible with repro this and other problems I am facing (see my questions on stackoverflow re: NuGet too). See my comments below inline

Thanks.
Val

**Comment by vmelamed** [comment]
Patricio,

Tried 4.8.1 and it has the same problem.

Thanks.
Val

**Comment by PatoBeltran** [comment]
I was trying to repro this and looking at the code, it seems that we don't support passing a directory as a path in push. What is happening is that push command is trying to find all the packages in `bin\Debug\` and it takes the `.symbols.nupkg` as well and it tries to push them as if they were packages. I tried looking at the documentation (https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push) and it doesn't mention anywhere the use of directories like that.

Try specifying the path to the package like:
```
dotnet nuget push bin\Debug\vm.Aspects.Security.Cryptography.Ciphers.2.1.2-beta.21.nupkg --source https://www.nuget.org
```

This should work and properly push the package to one server and the symbols to another.

**Comment by vmelamed** [comment]
I see. The problem is that the name of the package cannot be available because a part of the package name is the version which in turn is encapsulated either in the .csproj or in the AssemblyInfo.cs files. This makes your suggestion not workable for automation.

I guess this makes it a candidate for feature proposal.

Thanks.
Val

**Comment by PatoBeltran** [comment]
We do support globbing patterns, so you could probably change a little bit your script to something like:

```
dotnet nuget push bin\Debug\*beta.20.nupkg --source https://www.nuget.org
```

just be careful that your globbing pattern is specific enough that it will not include the `.symbols.nupkg` because then you would be facing the same issue where it tries to push them as packages instead of symbols.

**Comment by rrelyea** [comment]
.symbols.nupkg is difficult to use globbing for.
That is why when we did some new symbol package work, we now use .snupkg

Regardless, closing.
