### ISSUE TITLE
Properly release 4.8.1

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7262]
You've recently release 4.8.1 which contains an important fix for running in offline environments. Unfortunately [NuGet.Commandline](https://www.nuget.org/packages/NuGet.CommandLine/) package is not updated and still at 4.7.1  (while [NuGet.CommandLine.XPlat](https://www.nuget.org/packages/NuGet.CommandLine.XPlat/) is at 4.8) and there are no release notes available [here](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.7-rtm). 

Can you please properly release 4.8.1 on all channels and with full release notes.

**Comment by anangaur** [comment]
Thanks for the issue @pascalberger. Definitely something we could have done better. I guess the hurry to unblock developers due to #7008 caused us to release 4.8.1 exe before we could prepare a synchronized release. I will look into this and get the other pieces together asap.

**Comment by pascalberger** [comment]
@anangaur Thanks for taking care of this.

As being the reported of #7008 I would have prefered if you would have taken your time and release it properly, in which case I might be able to use it by now, what is not possible currently due to the missing pieces. If you want to unblock people quickly why not release a pre-release version (For this case I already had a testversion)?

What's getting boring is that I reported similar stuff already for [4.3](https://github.com/NuGet/Home/issues/5784), [4.4.1](https://github.com/NuGet/Home/issues/6203), [4.7](https://github.com/NuGet/Home/issues/7114) where you forgot to update the `nuget.commandline` nuget package, and [4.7.1](https://github.com/NuGet/Home/issues/7196) were release notes were missing. So there seems to be some kind of pattern here. 

Also currently there's still a big mess with versioning, between what you make available on https://dist.nuget.org/index.html, the `nuget.commandline` and `nuget.commandline.xplat` package. Also your proces doesn't match with what you've written in #4851 how your process should look like.

For example `nuget.commandline` has version [4.7.1](https://www.nuget.org/packages/NuGet.CommandLine/4.7.1) has no release notes, `NuGet.CommandLine.XPlat` has a version [4.8.0](https://www.nuget.org/packages/NuGet.CommandLine.XPlat/4.8.0) which doesn't even exist elsewhere. There's more mismatch if you compare https://dist.nuget.org/tools.json and the two NuGet packages.

Also I don't see why you make a difference between `Released` and `ReleaseAndBlessed` versions if you still fail at stuff like failing self update, which happened with 4.7.0, and which is even explicitely mentioned in #4851 as a use case for the `NuGet.CommandLine` package. Why not just have a set of proper integration tests for stuff like this and a release pipeline which publishes all the artifacts. IMHO this would lead to much more stable release scenarios than what we have now.

**Comment by anangaur** [comment]
No. Publish it for 4.8.1

State that VS shipped with 4.8 but will soon have a servicing release. When the servicing release happens update the release notes accordingly

-AG.

________________________________

**Comment by pascalberger** [comment]
@anangaur Do you have any plans when the missing pieces will be released?

**Comment by pascalberger** [comment]
@anangaur How does it look regarding release notes and requirements for 4.8.1? I tried to update to be able to use signed packages, but I'm running into issues (https://github.com/NuGet/Home/issues/7292). Maybe this is a known restriction or requirement which I'm missing in 4.8.1, but without proper documentation I have no clue, and therefore I'm still unable to upgrade to any nuget packages which are released since you introduced repository signing, including all security updates.

**Comment by pascalberger** [comment]
As the changes from 4.8.1 are now also deployed with Visual Studio based on [this](https://github.com/NuGet/Home/issues/7008#issuecomment-420385280) comment, it now definitely should be the recommended version and deserves proper release notes

**Comment by karann-msft** [comment]
Release notes are here - https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.8-rtm

**Comment by pascalberger** [comment]
While now finally recommended, parts on nuget.org are still missing: #7504

**Comment by fenneh** [comment]
Still missing Nuget 4.8.1 Command Line package. It's also missing from the XPlat packages.

To give an example of a real world effect of this - Teamcity uses the Nuget Command Line nupkg for its own Nuget runners, if you're looking to do a nuget restore which requires that client then you'll need to create your own nupkg currently.

**Comment by devlead** [comment]
@fenneh 4.8.1 had release issues, 4.9.1 is expected to be released in the near future.

**Comment by quasarea** [comment]
any news about syncing those things? 
there is 4.9.2 already available and if this package does not keep up it should be obsoleted as now it is just misleading.

**Comment by pascalberger** [comment]
@quasarea 4.9.2 is not blessed/recommendet yet, I expect that they will update the nuget.commandline package once it is blessed. 4.8.1 is still the recommendet version, but due to release issues with this version, nuget.commandline is still on the previous recommendet version which is 4.7.1

**Comment by pascalberger** [comment]
Closing as 4.9.2 is now blessed
