### ISSUE TITLE
Some packages still landing in my User packages

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#7266]
I rerouted my user packages to another location in my computer. However, some are still landing there. I wonder if there is another ``NuGet.Config`` that is being used? Or otherwise ignored?

For instance,

```Xml
<config>
  <!--
    The location of the default global packages folder. The default is %userprofile%\.nuget\packages (Windows)
    or ~/.nuget/packages (Mac/Linux). A relative path can be used in project-specific nuget.config files. This
    setting is overridden by the NUGET_PACKAGES environment variable, which takes precedence.
  -->
  <add key="globalPackagesFolder" value="G:\Dev\NuGet\global\packages" />
</config>
```

Specifically, the packages still landing there are:

```
microsoft.build
microsoft.build.engine
microsoft.build.framework
microsoft.build.utilities.core
nuget.versioning
```

Any of the others, some 287 or so folders, including a ``.tools`` folder, I copied to the rerouted location.

**Comment by rrelyea** [comment]
yes, nuget.config is hierarchical. If other projects are being resolved without that setting being in scope, that would explain it.
If you can reproduce this on a fresh machine, with an isolated repro...we would love to know.
Otherwise, I'm going to close this as a question for now.
