### ISSUE TITLE
Search provides irrelevant results

### ISSUE THREAD

**Issue by branislavsimo** [NuGet/Home#7267]
Searching for a package in VS UI (15.8.2) provides irrelevant results.

# Example:
### Searched keywords
"microsoft logging console"

### Result
Package Microsoft.Extensions.Logging.Console is not even listed.
When "microsoft" is removed, it gets listed on 8th place. It seems trying to be more specific actually hurts the search.

### Screenshot
![image](https://user-images.githubusercontent.com/13053178/45017776-cd0a8800-b028-11e8-84c5-bf64591684d3.png)

**Comment by PatoBeltran** [comment]
Issue moved to [NuGet/NuGetGallery #6392](https://github.com/NuGet/NuGetGallery/issues/6392) via [**ZenHub**](https://www.zenhub.com/)

**Comment by PatoBeltran** [comment]
Moved to NuGetGallery since they have the logic for it... You can get this same results if you search on nuget.org
