### ISSUE TITLE
Restore a project with platform x64

### ISSUE THREAD

**Issue by ManniManfred** [NuGet/Home#7269]
NuGet Version: 4.8.1.5435
msbuild version '15.8.168.64424'

Hi,
when i restore the following project MyProject.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>
</Project>
```
with the command ``nuget restore MyProject.csproj`` it creates a ".NETFramework,Version=v4.6/win7-x86" target in the project.assets.json. I would expect an entry for ".NETFramework,Version=v4.6/win7-x64".

**Comment by nkolev92** [comment]
This is a design problem with .NET overall. 
Closing as dup of https://github.com/dotnet/sdk/issues/1553

NuGet reads the RuntimeIdentifier. 

https://github.com/NuGet/NuGet.Client/blob/6c90e08a0bcbc6fd3bd8f851c3333dfdce1233ef/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L650
