### ISSUE TITLE
NuGet Core GetPackages does not set IPackage.Listed correctly

### ISSUE THREAD

**Issue by AnEnglishmanInNorway** [NuGet/Home#727]
The following code
            foreach (var repoName in new [] { @"http://server/api/v2" })
            {
                var repo = new PackageRepositoryFactory().CreateRepository(repoName);
                var packages = repo.GetPackages();
                var plotPackages = packages.Where(package => package.Id.Contains("PlotControl"));
                foreach (IPackage p in plotPackages)
                {
                    Console.WriteLine(p + " Listed=" + p.Listed + ", IsListed()=" + p.IsListed());
                }
            }
produces lines looking like this:
  KM.KCSClient.PlotControl 0.1.0-beta159 Listed=False, IsListed()=True
  KM.KCSClient.PlotControl 0.1.0-beta160 Listed=False, IsListed()=True
  KM.KCSClient.PlotControl.Styles 0.0.1-alpha001 Listed=False, IsListed()=False
  KM.KCSClient.PlotControl.Styles 0.1.0-beta001 Listed=False, IsListed()=False
Observe that the top two lines show IsListed()=True, which is correct, and the bottom two show IsListed()=False, which is also correct. But all 4 lines claim Listed=False. That's fine from C#, now I know it, but I'm checking from F#, where the IsListed extension method is not available.

**Comment by yishaigalatzer** [comment]
You need to call IsListed directly by calling `PackageExtensions.IsList(package)`

This is the actual code - 

```C#
        public static bool IsListed(this IPackage package)
        {
            return package.Listed || package.Published > Constants.Unpublished;
        }
```

Given that longish term we want to get rid of `nuget.core` I'm not inclined to try and fix it as it might break other people depending on this behavior.

We should probably add a doc comment to `IsListed` though

**Comment by yishaigalatzer** [comment]
Here is soome more info:
- Talking to the F# folks, they think the extension method should be available can you please submit an issue in to https://github.com/Microsoft/visualfsharp
- The reason Listed is different, is that it is used as the DTO model and some servers don't reported Listed directly instead they report the Published date. This means we can hack the setter in the implementations to return a different result than the getter, but that's just bad form and will cause other bugs.

**Comment by AnEnglishmanInNorway** [comment]
Hi! Thx for the response.
Maybe I misunderstand, but aren't extension methods a C# thing? Am on my
phone right now but I think I mentioned that I am using F# - the sample
code in C# just showed the problem with a really trivial example.
Cheers, Pete
4. jun. 2015 18.35 skrev "Yishai Galatzer" <notifications@github.com>:

**Comment by AnEnglishmanInNorway** [comment]
Ok, just saw the xtra info. Will try when I get back to my PC. Thx again.
Pete
4. jun. 2015 20.57 skrev "Yishai Galatzer" <notifications@github.com>:

**Comment by yishaigalatzer** [comment]
Extension methods are also just plain static methods you can call directly from the static class they are declared on.

**Comment by yishaigalatzer** [comment]
We are planning to deprecate nuget.core, and there is a clear fix here. So we are calling it by design for now (one can argue this is a won't fix). 

It is a side effect of using oData directly, and we don't plan to support that going forward.
