### ISSUE TITLE
VS2015 NuGet Package Manager UX problema

### ISSUE THREAD

**Issue by attilah** [NuGet/Home#728]
I've started to use VS2015 and the new NuGet came with it.

Upon the first encounter what I saw is that I can't see what is where...

Then came a some bad UX experience:
- When I open the NuGet PM at solution level, show me the list with the installed filter by default. I think that 
- Don't check the include prerelease by default. I think that not that's what MOST users want. If someone unchecks it, remember that setting at solution level and have an option for that in the global settings dialog too.
- When I like to update some packages for the solution and filtering on "Upgrade available", make the Update as the default action on the right, since that is what makes sense.
- Support multi-selection for packages on the left, and make "Upgrade all" also available. In today's world when everyhing is a NuGet package, at solution level you can easily have 40 packages...and more.
- On the left I see packages in Upgrade available filtering mode, but on the right I've only Install and Uninstall action available, so...why is that in the list on the left? When I do this at project level, Upgrade action is available for the same package.
- The Preview popup dialog does not respect the color scheme of VS.

I hope this helps.

**Comment by yishaigalatzer** [comment]
@attilah this is good feedback, we are going to handle some of it for RTM, and some for Update I. It really helps when issues are opened individually, so we can track them and triage them one by one.

Note that we released an update nuget extension just yesterday (still not on the visual studio gallery) https://nuget.codeplex.com/releases/view/615507 it will come to the gallery in a few days. Give it a try, it resolves quite a few issues.

#### Specifically to your comments

> When I open the NuGet PM at solution level, show me the list with the installed filter by default.

By default it is still all, but we now remember the last choice you made in Visual Studio settings. I think that what is the mode in the manager is pretty much a personal choice. I open the dialog mostly to find and install new packages, someone else for looking what is installed and upgrade. So the best choice is to remember the users choice.

> I think that don't check the include prerelease by default. I think that not that's what MOST users want. If someone unchecks it, remember that setting at solution level and have an option for that in the global settings dialog too.

We current remember it at the solution level, we are considering saving a default value at the user level (based on what you changed last) that will only impact new projects. But we are not going to add another global setting UI for this. Tracked by #732

> When I like to update some packages for the solution and filtering on "Upgrade available", make the Update as the default action on the right, since that is what makes sense.

I believe we fixed that already.

> Support multi-selection for packages on the left, and make "Upgrade all" also available. In today's world when everything is a NuGet package, at solution level you can easily have 40 packages...and more.

We plan on fixing this in Update I, you can do upgrade all from the PowerShell command line.

> On the left I see packages in Upgrade available filtering mode, but on the right I've only Install and Uninstall action available, so...why is that in the list on the left? When I do this at project level, Upgrade action is available for the same package.

This was fixed as well.

> The Preview popup dialog does not respect the color scheme of VS.

Opened #730 to track.


Thanks again. Closing this as it is being tracked now by individual issues.
