### ISSUE TITLE
Referencing .NET Core library from .NET 4.7.1 app causes System.Runtime 4.0.20.0 not found exception

### ISSUE THREAD

**Issue by AqlaSolutions** [NuGet/Home#7287]
`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.' - file not found.`

## Repro Steps

1. Create new .NET 4.7.1 Console App project in VS.
2. Install Microsoft.CodeAnalysis.CSharp nuget package using VS package manager.
3. Add `Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText("");` to the Main().
4. Run

## Workaround

Remove System.Runtime from binding redirects in app.config. You'll get the same exception for other references, repeat until you can run it.

## Version

NuGet Package Manager 4.6.0 for Visual Studio 
VS version: 15.8.3
OS version: win10 v1709 16299.192

<a href="https://www.dropbox.com/s/p0ewdvh4ifjksyi/ConsoleApp1NugetBug.zip?dl=1">Sample Project</a>

**Comment by rrelyea** [comment]
@jainaashish Please port https://github.com/NuGet/NuGet.Client/pull/2416 to 4.9/VS15.9
(already fixed in 5.0/VS16.0)

**Comment by jainaashish** [comment]
Already done https://github.com/NuGet/NuGet.Client/commit/454c7af0e8ab30b472afd9543a8e624d242e4440
