### ISSUE TITLE
[DOCS] “Setting Up The NuGet Development Environment” still refers to codeplex

### ISSUE THREAD

**Issue by binki** [NuGet/Home#729]
In the “Developing NuGet on Linux” section, I find the following instruction:

    git clone https://git01.codeplex.com/nuget

This seems to contrast the note found at https://nuget.codeplex.com/discussions :

> We have moved to GitHub. We are no longer following issues here. The issues are here for historical reasons only, please don't expect feedback from the NuGet team here, or anywhere on this site when it comes to issues/discussion/feedback.

**Comment by yishaigalatzer** [comment]
This is still correct until we move nuget.core to github, this is in progress and should complete shortly. We will then update the docs as well.

Thanks for bringing it up to our attention.

**Comment by emgarten** [comment]
This should be handled as part of the move from codeplex.

**Comment by yishaigalatzer** [comment]
@pranavkm I moved it out of the milestone because it doesn't need the scrutiny of shiproom, but we should still do it as soon as we can

**Comment by yishaigalatzer** [comment]
see https://github.com/nuget/home, we currently don't support developing nuget on linux. We plan to make nuget compile and build for coreCLR (where it will work on linux), but until that happens there is no docs issue.

nuget.core has indeed moved to github (nuget2 repo), but we plan to completely deprecate it in 3.4
