### ISSUE TITLE
Error restoring packages for MsBuild project which imports target from NuGet package

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7292]
I've a Visual Studio Solution which contains an MsBuild project which imports a target file, which comes from a NuGet package. During build we restore first the NuGet packages (`nuget restore mysolution.sln`) and then build the MsBuild project. This worked fine until NuGet 4.7.1. Starting with 4.8.1 this results now in an error, as nuget.exe seems to inspect the MsBuild project while restoring packages, which obviously fails, as the target will only be restored by NuGet:

```
C:\MyProject.csproj(58,3): error MSB4019: The imported project "C:\MyTarget.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.8.1

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.7.0

OS version (i.e. win10 v1607 (14393.321)):  Windows 10.0.17134.228]

Worked before? If so, with which NuGet version: 4.7.1

## Detailed repro steps so we can see the same problem

1. Create a NuGet package containing a MsBuild target file
2. Reference the target file from an MsBuild project
3. Try to restore the NuGet package

**Comment by rrelyea** [comment]
@nkolev92 can you please take a look here?

**Comment by nkolev92** [comment]
@pascalberger 

What's your project style? 

In PackageReference the import of targets file should not be raising errors like this normally. 

If you have a malformed project, you might be hitting that issue because of a performance optimization we added in 15.5 of the NuGet.targets and ported to NuGet.exe in 4.8

https://github.com/NuGet/NuGet.Client/pull/2354

It'd be great if you can provide me with a repro. 

You can also try if setting an env var to RestoreUseSkipNonexistentTargets="false" fixes it.

**Comment by pascalberger** [comment]
@nkolev92 The project is with `packages.config`. Will try with the env var and see if I can create a repro.

**Comment by pascalberger** [comment]
@nkolev92 Setting the `RestoreUseSkipNonexistentTargets` environment variable seems to fix the issue for projects referencing targets from NuGet packages and also for SSDT solutions (where it would throw otherwise with `error MSB4067: The element <DeploymentModel> beneath element <Project> is unrecognized.`)

Do you still need a repro?

Is there also a `nuget.config` entry which can be set instead of the environment variable? If I got it right, these changes were made for performance reasons and setting the environment variable would disable the performance optimization for all repos on a machine, while with an entry in the `nuget.config` file I would be able to disable it only for the repositories where otherwise issues would occur.

**Comment by pascalberger** [comment]
Also this change should be mentioned as a potential breaking change as part of the release notes at https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.8-rtm

**Comment by pascalberger** [comment]
I've also created https://github.com/NuGet/docs.microsoft.com-nuget/pull/1102 for adding this to the environment variables documentation of nuget.exe CLI.

**Comment by nkolev92** [comment]
@pascalberger 

Can you please provide a repro?

I don't follow why the targets file would attempt to be imported from that location. 
I attempted a simple check with packages.config project and targets coming from a package and that worked fine.

**Comment by pascalberger** [comment]
@nkolev92 Sure I'll provide you a repro. I'm just a little a little bit swamped with work at the moment.

**Comment by PatoBeltran** [comment]
hey @pascalberger, any chance you've gotten the time to create a repo? If not, is this still an issue?

**Comment by rrelyea** [comment]
Closing. Without a repro, or repro steps, cannot investigate.
