### ISSUE TITLE
[Test Failure]NuGet Client dev-ragrawal-4.0rtm\4.0.1.5492 is failed to install into D15rtwsvc\26228.52

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7295]
## Details about Problem
NuGet version:dev-ragrawal-4.0rtm\4.0.1.5492
VS version:D15rtwsvc\26228.52
OS version:Build 17134.rs4_release.180410-1804 
## Detailed repro steps
1. Install VS path: \\cpvsbuild\drops\VS\d15rtwsvc\products\26228.52\bootstrappers\Enterprise\vs_enterprise.exe
2. Install NuGet Client path:  \\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\dev-ragrawal-4.0rtm\4.0.1.5492\artifacts\VS15\NuGet.Tools.vsix
## Excepted
NuGet Client dev-ragrawal-4.0rtm\4.0.1.5492 should be installed into D15rtwsvc\26228.52 successfully.
## Actual
NuGet Client dev-ragrawal-4.0rtm\4.0.1.5492 is failed to install into D15rtwsvc\26228.52 as below screenshot ( [Error log.txt](https://github.com/NuGet/Home/files/2374522/Error.log.txt)):
![installiation failed](https://user-images.githubusercontent.com/40230425/45416364-534d4c80-b66f-11e8-9850-e4896e487f0c.png)
## Note
1. NuGet Manager disappeared after installing NuGet Client dev-ragrawal-4.0rtm\4.0.1.5492.
![no nuget manager](https://user-images.githubusercontent.com/40230425/45416380-59432d80-b66f-11e8-9831-36374d1421e6.png)
2. The issue reproes on D15rtwsvc\26228.54 after installing the same NuGet Client.

**Comment by rohit21agrawal** [comment]
Fixed

**Comment by v-luzh** [comment]
This issue repro on D15.9 28114.00+NuGet Client Release-4.9.0-Preview3 4.9.0.5507.
