### ISSUE TITLE
Incorrect NuGet.config used during restore when running as LocalSystem

### ISSUE THREAD

**Issue by b6o** [NuGet/Home#7299]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.7.1.5393

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2012

## Detailed repro steps so we can see the same problem

When running nuget restore as the LocalSystem user, the incorrect config file is used. Nuget is adamant that it is using "C:\Windows\system32\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config", and this is what is displayed :

```
NuGet Config files used:
    C:\windows\system32\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config
```

But when adding sources to the config, they are not included in the restore.

It instead uses the config found at "C:\Windows\SysWOW64\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config"

Any sources added here are loaded, but nuget still says that it is using the other config.

**Comment by jainaashish** [comment]
is this the same experience between `nuget.exe` and `Visual Studio`? what happens when you try to restore from VS? and Which nuget.config file is being updated when you add a source within VS?

NuGet uses `Environment.SpecialFolder.ApplicationData` to get the appdata path to use default nuget.config file.

**Comment by b6o** [comment]
This is on a build server so Visual Studio is not installed. 

When adding a source it is added to "C:\windows\system32\config\systemprofile\AppData\Roaming\NuGet\NuGet.Config". The source is visible when listing sources, but then only sources in the SysWOW64 config are actually used.

**Comment by nkolev92** [comment]
@1patryk What do you mean when listing sources? 
See for info on how the configs are processed.
https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses

Also why do you think the config at SysWOW64 is used if NuGet never tells you explicitly?

**Comment by b6o** [comment]
@nkolev92 I mean running the sources list nuget command. This shows the newly added source, but the source itself is not picked up or used when running a restore command.

I understand how the configs are procsessed, which was why it was odd having to add the source to a config that is supposedly not being loaded.

When the source is only added to the config at SysWOW64, the source is used and restore runs correctly, even though NuGet says it is not using this config.

**Comment by nkolev92** [comment]
When you say restore runs correctly, do you clear the the global packages folder before running?

If all the packages are already in the packages folder or the global packages folder, it won't matter what sources it's running with, it will work.

**Comment by b6o** [comment]
Yep, the global packages folder was cleared inbetween

When running a restore without the source being added to the SysWOW64 config, the only source that would be checked for packages was nuget.org

**Comment by nkolev92** [comment]
@1patryk Are you still able to repro this issue?

NuGet.exe is a 32-bit application, it's a bit strange that it's trying to use a non-32-bit path.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by nickhoeferpickpro** [comment]
what if it is run from a service? (like from a jenkins agent as an example)
