### ISSUE TITLE
Counter intuitive behaviour when using dotnet restore with "--configfile" option

### ISSUE THREAD

**Issue by felixhayashi** [NuGet/Home#7300]
Hi,

just wanted to report a rather counter intuitive behavior, not sure if it is a bug.

In my project root I am using `dotnet restore --configfile NuGet.Config` to restore my packages. This fails saying that not all packages could be found. However, when executing `dotnet restore` in the same directory without the `--configfile`, the restore works, all packages are found plus my local project-specific `NuGet.Config` is properly interpreted!

**Without** the `--configfile` specified, nuget seems to read the `<packageSources>` from my `/home/xxx/nuget/NuGet/NuGet.Config` file (yes, I am running on linux) and **also** interprets the config specified in `NuGet.Config`. 

**With the** `--configfile` specified, nuget completely ignores `<packageSources>` from my `/home/xxx/nuget/NuGet/NuGet.Config` directory and **only** reads my local project-specific `NuGet.Config` which lacks a `<packageSources>` – hence the failed retrieval of packages. 

Best wishes
Felix

**Comment by jainaashish** [comment]
By default NuGet reads all the nuget.config file starting from current directory but when you specify `--configfile` you restrict it with that specific file. That's the whole point of this parameter. So if you want the default experience, then you dont need to specify `--configfile` parameter. I'll look into updating the doc to better explain it.

**Comment by felixhayashi** [comment]
thanks for this explanation @jainaashish. yes, updating the docs would be helpful.
