### ISSUE TITLE
unlist the out of date wiki

### ISSUE THREAD

**Issue by SimonCropp** [NuGet/Home#7305]
can u remove the nuget wiki so it doenst show up in search results https://github.com/NuGet/Home/wiki/Adding-nuget-pack-as-a-msbuild-target

**Comment by jainaashish** [comment]
This is complete spec for Pack support as a msbuild target. What you mean by out of date?

**Comment by SimonCropp** [comment]
shouldnt this be the definitive reference https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets  ?

**Comment by SimonCropp** [comment]
an example of the wiki showing up in a search result 

![image](https://user-images.githubusercontent.com/122666/63636021-f34b8c80-c6ac-11e9-933c-016c78326e65.png)
