### ISSUE TITLE
NuGetizer: IDE Integration VSIX NuGetizer 3000 for VS2017

### ISSUE THREAD

**Issue by SubyBrue** [NuGet/Home#7312]
Currently using VS2017 Build 15.8.4 and cannot create a NuGet package on a solution.

Other co-workers who are on Build 15.8.2 and 15.7.# have no issues.

When I select Create NuGet package - the system builds the solution but never kicks off the process to generate the NuGet package.

**Comment by jainaashish** [comment]
@kzu

**Comment by SubyBrue** [comment]
Tried de-installing and reinstalling however my work PC is now on VS 2017 v15.8.5 and Nugetizer VSIX will no longer install there...

On my home PC (running VS 2017 v15.8.4) it was able to create 1 NuGet package for one project and then subsequent projects have not been able to create the NuGet packages... They rebuild but don't create the NuPKG files....   The initial project I assembled worked but when I deleted the NuPkg file and attempted to recreate it it did not create the package again.

**Comment by SubyBrue** [comment]
Any updates on this @jainaashish  or @kzu?   I'd  be more than happy to provide whatever I can in terms of log files, etc....

**Comment by kzu** [comment]
We're currently addressing other high-priority issues. NuGetizer isn't very high on the list, so if you want to take a stab at building from source (see https://github.com/NuGet/NuGet.Build.Packaging/) and sending a PR, that would be greatly appreciated.

Thanks!

**Comment by derekwheeler-tylertech** [comment]
> Tried de-installing and reinstalling however my work PC is now on VS 2017 v15.8.5 and Nugetizer VSIX will no longer install there...
> 

@SubyBrue. My company went to VS 2017 15.8.5 last week. I was initially unable to open my project. I had to reinstall the latest VSIX but then was able to open my project and do builds again.

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

You can use a [packaging project](https://www.clarius.org/nugetizer/#packaging-projects) supported out of the box by Visual Studio and NuGetizer.
