### ISSUE TITLE
[Test Failure] Installing PackageReference based package made the ‘Default project’ empty

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7315]
## Details about Problem
NuGet Version: Dev-ragrawal-4.0rtmwithfix\4.0.1.5510
VS Version: d15rtwsvc\26228.55
OS Version: Build 17134.rs4_release.180410-1804 
## Detailed repro steps 
1. Launch VS, create a new WPF App (.Net Framework) project.
2. Open PMC through Tools -> NuGet Package Manager -> Package Manager Console.
3. Select PackageReference format as default package management format in Package Manager Settings dialog.
4. Type “Install-Package Newtonsoft.json –Version 10.0.1” in PMC and execute it.
5. Check the Default project.
## Excepted
The ‘Default project’ show the project name correctly.
## Actual
The ‘Default project’ is empty after executing step3 as below screenshot.
![default project](https://user-images.githubusercontent.com/40230425/45867440-00604d00-bd73-11e8-9533-ca6a7410577b.png)

**Comment by rohit21agrawal** [comment]
this issue was fixed in 4.1, so not applicable to this release of VS (related issue: https://github.com/NuGet/Home/issues/4315 ).

@v-longmin  Just to make sure, does this behavior repro in d15rtwsvc without the VSIX installed?

**Comment by v-longmin** [comment]
@rohit21agrawal Yes,it  also repro in d15rtwsvc 26228.55 without the VSIX installed.
