### ISSUE TITLE
Xamarin.Android.Support.Desing package integrity check fails

### ISSUE THREAD

**Issue by oscpen** [NuGet/Home#7322]
I am trying to update this package in my Xamarin project in Visual Studio using Nuget Package Manager or the Package Manager console, but I get the same integrity check error in both.

Microsoft Visual Studio Community 2017 Version 15.6.2
Microsoft .NET Framework Version 4.7.03056
NuGet Package Manager   4.6.0
Tried with VS UI | Package Manager Console

Install-Package Xamarin.Android.Support.Design -Version 27.0.2.1
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/xamarin.android.support.design/index.json
Restoring packages for C:\Solutions\IN.PUBLISHER\IN.PUBLISHER\IN.PUBLISHER.Android\IN.PUBLISHER.Android.csproj...
  GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/index.json
  OK https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/index.json 481ms
  GET https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/27.0.2.1/xamarin.android.support.transition.27.0.2.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/xamarin.android.support.transition/27.0.2.1/xamarin.android.support.transition.27.0.2.1.nupkg 272ms
Installing Xamarin.Android.Support.Transition 27.0.2.1.
Signature Hash Algorithm: SHA256
Install-Package : NU3008: The package integrity check failed.
At line:1 char:1
+ Install-Package Xamarin.Android.Support.Design -Version 27.0.2.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Signature type: Author
Timestamp: 6/11/2018 5:27:08 PM

Verifying timestamp with timestamping service certificate: 
Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
Valid from: 1/1/2017 4:00:00 PM to 4/1/2028 4:59:59 PM

Verifying signature with author certificate: 
Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Valid from: 2/25/2018 4:00:00 PM to 1/27/2021 4:00:00 AM

Install-Package : Package restore failed. Rolling back package changes for 'IN.PUBLISHER.Android'.
At line:1 char:1
+ Install-Package Xamarin.Android.Support.Design -Version 27.0.2.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:10.2002380

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment]
@oscpen , could you try [downloading nuget.exe](https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe) and then run `nuget verify -all %USERPROFILE%\.nuget\packages\xamarin.android.support.design\27.0.2.1\xamarin.android.support.design.27.0.2.1.nupkg` to see if you get the same issue?  It could be that your download is corrupted or has been tampered with.

If you'd like to try downloading again, delete the `%USERPROFILE%\.nuget\packages\xamarin.android.support.design\27.0.2.1\` folder and all files in it (or run `dotnet nuget locals all --clear` to delete all your local packages), and try restoring or installing the package again.

**Comment by PatoBeltran** [comment]
Closing as we do not have enough information to investigate further. Please feel free to reopen if you continue to see this behavior.
