### ISSUE TITLE
VS2017 Web project build fails with RestoreProjectStyle set to PackageReference

### ISSUE THREAD

**Issue by JJoe2** [NuGet/Home#7323]
Repro:
- VS2017 15.7.5 (and I'm pretty sure also on 15.8.5).
- Create a new ASP.NET Web Application (.NET Framework)
- Choose the "Empty" project template and leave all checkboxes unchecked
- Edit the csproj file and add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` to the first `<PropertyGroup>` section (*)
- Close Visual Studio
- Delete the packages folder (it contains Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.8 and Microsoft.Net.Compilers.2.6.1 that are referenced in the csproj file).  This is because I'm using package restore on the build server so won't be committing the packages folder.
- Restart Visual Studio and build
- Build fails with error: 

"This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Net.Compilers.2.6.1\build\Microsoft.Net.Compilers.props."

(*) I added the `RestoreProjectStyle` element because I am planning to use .NET Standard projects in the solution, which reference .NET Standard Nuget packages, and this is necessary as described here:

https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

DLL Hell is alive and kicking in 2018.

**Comment by zivkan** [comment]
Adding `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` to the csproj is an incomplete packages.config to PackageReference migration. Unfortunately the [migration tool](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) is not enabled for ASP.NET projects, so it needs to be done manually, but please be aware of the limitations and compatability issues listed in the documentation.

The easiest way is to migrate an ASP.NET project is:
1. Use the NuGet Package Manager to uninstall all NuGet packages currently in the project
2. Ensure that in Options->NuGet Package Manager that the default package management format is PackageReference or that "Allow formation selection on first package install" is checked.
3. Use the NuGet Package Manager to install the packages that were uninstalled in step 1.

It is possible to migrate to PackageReference by manually editing the csproj and deleting packages.config. However, there is more work needed than simply adding that project property. There several lines in the csproj that need to be deleted. The error message that you reported is listed at the end of the csproj, for example.
