### ISSUE TITLE
Package search terms not working on own hosted nuget server

### ISSUE THREAD

**Issue by TrestleMonkey** [NuGet/Home#733]
I'm hosting my own NuGet feed using NuGet.Server v2.8.60318.667 but I can't seem to get the package search terms to work, both using Nuget command line and within VS2013. Search terms work fine with the nuget.org repo. (Nuget command line version is  2.8.60318.667).

e.g. my repo contains a package with the ID of "CT.Common". It lists correctly and if I run

~~~
nuget list ct.common
~~~

I get it fine. But if I run

~~~
nuget list id:ct.common
nuget list packageid:ct.common
~~~

I get no results. Same if I enter these search terms in Visual Studio. The same format of search is fine on nuget.org.

**Comment by yishaigalatzer** [comment]
@xavierdecoster can you help with some pointers?

**Comment by yishaigalatzer** [comment]
@TrestleMonkey I don't think we have this support in the local client. We think it is a Lucene operator only available in nuget.org, not something we implemented in the local nuget server.
