### ISSUE TITLE
Upgrading EF Core 2.1.2.0 to 2.1.3.0 - Dependent Assemblies in app.config are not all automatically updated

### ISSUE THREAD

**Issue by ajcvickers** [NuGet/Home#7331]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/13373 filed by @JRBonnema

I noticed that after installing the latest 2.1.3.0 version of EFCore the three packages below are not automatically updated to the new version. I have to do it by hand. Note that other packages are automatically updated. I didn't notice these behaviour during earlier updates, so I assume that this a new  problem. 

```
 <dependentAssembly>
    <assemblyIdentity name="Microsoft.EntityFrameworkCore" publicKeyToken="adb9793829ddae60" culture="neutral" />
     <bindingRedirect oldVersion="0.0.0.0-2.1.2.0" newVersion="2.1.2.0" />
  </dependentAssembly>
  <dependentAssembly>
     <assemblyIdentity name="Microsoft.EntityFrameworkCore.SqlServer" publicKeyToken="adb9793829ddae60" culture="neutral" />
     <bindingRedirect oldVersion="0.0.0.0-2.1.2.0" newVersion="2.1.2.0" />
  </dependentAssembly>
  <dependentAssembly>
     <assemblyIdentity name="Microsoft.EntityFrameworkCore.Relational" publicKeyToken="adb9793829ddae60" culture="neutral" />
     <bindingRedirect oldVersion="0.0.0.0-2.1.2.0" newVersion="2.1.2.0" />
  </dependentAssembly>
```

**Comment by ajcvickers** [comment]
Existing comments:

@ajcvickers commented 7 days ago
@JRBonnema Can you be more specific about what you mean by "installing the latest 2.1.3 version?" Installing what specifically from where?

@JRBonnema commented 7 days ago
@acjvickers: I Installed the three mentioned packages EFCore packages (version 2.1.3.0) from NuGet using the menuoption Manage NuGet Packages for Solution inside Visual Studio - version 15.8.4

@JRBonnema commented 4 days ago
Update: I did the same upgrade on another few solutions after have installed Visual Studio - version 15.8.5. I noticed a difference between these two versions of Visual Studio, but it still not working like it was before.

Further these errors are occurring in rather complex solutions, each having A WCF project in .Net Framework 4.72 using EF Core, calling a class library containing the datamodel in .Net Core itself also using EF Core. Further a second project in the solution of a Windows service in .Net Framework 4.72 embedding these WCF projects.

@ajcvickers commented 2 hours ago
@JRBonnema I'm still not fully understanding what you did and what the issue is. Are you saying that you installed 2.1.3 versions into your project, but that this didn't work and the versions in your project are still 2.1.2?

@JRBonnema commented 13 minutes ago
@acjvickers The title says it all : Upgrading EF Core 2.1.2.0 to 2.1.3.0 - Dependent Assemblies in app.config are not all automatically updated. The upgrading itself is working fine. The Nuget packages are installed. The issue I have is that the dependent assemblies in VS 15.8.4 were in three cases not updated. In VS 15.8.5 there is improvement, but in the case of the complex solutions I describe above I must still do 1 manual adjustment in app.config (for "Microsoft.EntityFrameworkCore") after upgrading. Before for instance when I migrated to EF Core 2.1.1 or EF Core 2.1.2 there was no need for these manual adjustments after upgrading. The error seems dependent on the version of VS. I noticed the error first in 15.8.4 when upgrading to EF Core 2.1.3 but it might have been there in earlier versions.

@ajcvickers commented 41 seconds ago
@JRBonnema I see what you're saying. Then this looks like a NuGet issue--I'll move it there.

**Comment by nkolev92** [comment]
@JRBonnema 

What kind of a project do you have when trying to upgrade the package? 
You refer to 3 packages, are you trying to update all those 3 packages individually? 

Basically, anything you can provide to help us repro this.

**Comment by JRBonnema** [comment]
nkolev92 : in my case the problem was still there a few days ago, when I upgraded a few projects from EF Core 2.2 to 2.3. Some EF Core 2.2 references in app.config were left unchanged. I also remember seeing a project where app.config was referring to both the EF Core 2.2 and 2.3 version of the same package, confusing the compiler. The package I'm choosing in NuGet is Microsoft.EntityFrameworkCore.SqlServer. Issue only occurs in more complex solutions. I have a feeling problem arises in solutions where class libraries using Net Core and class libraries using Net Framework are both used. The projects are also not new, but were originally created two, three years ago using VS 2015 and upgraded since. I'am currently on the latest version of VS2017.

**Comment by nkolev92** [comment]
@JRBonnema 
I'm not sure how much I can help without a repro. 

Binding redirects have been common pain points so they were removed from NuGet in PackageReference world. 

Have you considered moving your .NET Framework project to PackageReference? 
https://blog.nuget.org/20180409/migrate-packages-config-to-package-reference.html

**Comment by JRBonnema** [comment]
I agree that you will probably not be able to solve this on your own. In theory problems like this can be solved, but only when there is optimal cooperation between two, three or more departments, which in practice is not possible. That said there seems to be a possibility for better cooperation between the Nuget and Entity Framework teams. I will give PackageReference a try in the near future, to see if this is preferable in my situation yes or no. Thanks anyway

**Comment by nkolev92** [comment]
@JRBonnema 

If you are seeing something going wrong with the binding redirects, it's very unlikely that EF & NuGet have anything to solve together. 

Based on your comment, I assume I can close this as No Repro? 

If you have any further information that can help us investigate we'd be happy to reopen this issue or just create a new one.
