### ISSUE TITLE
Add PackageType for runtime and targeting packs to exclude them from search results & restore graph.

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#7337]
For .NET Core 3.0, we plan to have various assets available as NuGet packages so that they can be easily acquired by the SDK on demand, but these packages shouldn't show up in normal package search results on NuGet.org, as they wouldn't be explicitly installed in projects.  A new PackageType could be used for these packages, and the NuGet search could be updated to exclude this PackageType by default.

Examples of packages we would use this for:

- [Targeting packs](https://github.com/dotnet/cli/issues/10006) (assets such as reference assemblies needed to build a project targeting a framework)
- [Runtime packs](https://github.com/dotnet/cli/issues/10007) (the runtime implementation of a framework which needs to be deployed with a self-contained app)
- "Empty" packages for Microsoft.NETCore.App, NETStandard.Library, and Microsoft.AspNetCore.App to prevent earlier versions of those packages from bringing in additional unneeded dependencies.

**Comment by nkolev92** [comment]
A couple of items that need clarified here.

- [ ] From the discussions we understand that these packages will not have any dependencies. 
Do we want a pack experience for them? Should pack validate that targeting/runtime packages do not have any dependencies.

- [ ] Should the package type be exclusive similar to how the DotnetTool and snupkg types.

- [ ] What are the implications of the new package types + snupkg and licenses. Ex. runtime packs can have a snupkg, targeting packs don’t make as much sense. Note that the snupkgs package type is exclusive. 

- [ ] Restore should safeguard against targeting/runtime packs in the regular project graph.
- [ ] The nuget.org symbol server will be affected by how the package type plays with symbols. 
- [x] Package applicability should account for the runtime and targeting packs. https://github.com/NuGet/Home/issues/5725
- [ ] The targeting packs should have a defined experience on the gallery similar to dotnet tool packages. (i.e. no action tab and ideally a reference to docs describing targeting/runtime packs.) https://github.com/NuGet/NuGetGallery/issues/6825

- [ ] Targeting/Runtime packs will have a certain folder structure. Ideally the strucutre of these folders is not similar to library packages to avoid potential hick-ups when people install the packages with clients that do not have the aforemention validation.  

We need to understand that to validate the experience in all of scenarios.

**Comment by nkolev92** [comment]
Update form the discussions:

The package type name is `DotnetPlatform` and the packages will follow conventions where an existing one exists. No conventions will be defined for types of assets that were never handled by NuGet.
