### ISSUE TITLE
Cache the default search results on the client

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#734]
When opening the dialog to query for packages, a default query is executed.
This is the most common query to hit the search service. Clients can cache these for some time.

> $filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm=''&targetFramework=''&includePrerelease=false

**Comment by yishaigalatzer** [comment]
This is to support cache headers for V2 clients.

**Comment by yishaigalatzer** [comment]
@feiling the intent here is to cache the default search result for ~40 minutes (to disk) so initial opening of the dialog is fast on every instance of visual studio

**Comment by rohit21agrawal** [comment]
will open another issue if we get more feedback on perf around this area.
