### ISSUE TITLE
[Test Failure] Error ‘Object reference not set to an instance of an object’ occurred in the Error List after installing a package into a .NET Framework project

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7346]
## Details about Problem
NuGet Version: NuGet Client Dev\5.0.0.5535
VS Version: D16.0stg\28128.3000
OS Version: Build 17134.rs4_release.180410-1804 
## Detailed repro steps 
1. Launch VS.
2. New a Visual C# -> Window Classic Desktop -> ClassLibrary (.NET Framework) project.
3. Right-click on the project and click ‘Manage NuGet Packages…’.
4. Select ‘Packages.config’ as package management format in Package Manager Settings window and click 'OK'.
5. Install a package (for example, Newtonsoft.json 11.0.2).
## Excepted
The package should be installed successfully.
## Actual
There is an error occur in the Error List as below screenshot
![installed error](https://user-images.githubusercontent.com/40230425/46243628-f28b7700-c3c5-11e8-8938-ec589417f6f2.png)
## Note
1. The issue also repro except the .NetCore template.
2. The issue doesn’t repro on selecting ‘PackageReference’ as package management format in Package Manager Settings.
3. The issue doesn’t repro on D15.9stg + NuGet Client Release-4.9.0-Preview4\4.9.0.5536.
4. The issue doesn't repro on D16.0stg with default NuGet Client Dev\5.0.0.5495.

**Comment by rrelyea** [comment]
@v-longmin  - can you please attach the call stack when the null ref first chance exception is fired?

**Comment by PatoBeltran** [comment]
This should have been fixed by https://github.com/NuGet/NuGet.Client/pull/2452, @v-longmin please confirm in the next validation

**Comment by v-longmin** [comment]
It has been fixed on D16.0stg + NuGet Client Dev 5.0.0.5549, thanks.
