### ISSUE TITLE
Enforce PackagePathResolver is an absolute path

### ISSUE THREAD

**Issue by bjorkstromm** [NuGet/Home#7349]
Either make sure `PackagePathResolver.Root` is absolute [here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Packaging/PackageExtraction/PackagePathHelper.cs#L123) or just make it absolute in the PackagePathResolver constructor.

**Comment by rrelyea** [comment]
At risk for 5.3...unless these tests can get fixed very soon. @mholo65 - are you able address soon? Would love to get in.

**Comment by bjorkstromm** [comment]
@rrelyea submitted a fix for tests now, let's see how it goes. Having problems running whole test suite locally.

**Comment by rrelyea** [comment]
Thanks @mholo65 for your contribution. This should get into NuGet 5.3 release!
