### ISSUE TITLE
Cache the default search results on the search service

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#735]
The search service can cache the results for the most common query:

> $filter=IsLatestVersion&$orderby=Id&$skip=0&$top=30&searchTerm=''&targetFramework=''&includePrerelease=false

**Comment by csharpfritz** [comment]
Yes.. I can't agree with this more.  There should be caching on this query
and on the details queries for the top 100 most popular package pages.

**Comment by yishaigalatzer** [comment]
We don't need to cache this as it is already cached in the gallery which is the only public API.

As for Jeff's comment we need to measure and see where is the load after the change above comes from and then carefully consider the next actions. 

First need to consider what else needs to move off the search service. Lots of the critical to uptime data comes from already available plain good old blobs that can also ser e as cache.
