### ISSUE TITLE
VS Package Manager does not request credentials if feed responds with HTTP 401

### ISSUE THREAD

**Issue by dtretyakov** [NuGet/Home#7354]
VS: 15.6.3
NuGet package manager: 4.6.0
OS version: win10 v1803

## Detailed repro steps so we can see the same problem

1. Add private nuget feed, fill in credentials and enable "Remember password" option
2. Change user password for stored credentials
3. Browse packages from private nuget feed

### Actual Result:
Package manager writes in the console:
```
Failed to retrieve metadata from source 'http://host/httpAuth/app/nuget/feed/_Root/default/v3/query?q=&skip=0&take=26&prerelease=false&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 ().
```

### Expected result

VS shows credentials prompt the same as in the step 1.

## Consequences

Since VS Package manager requests to feed very often it could cause lock out of user accounts.

**Comment by nkolev92** [comment]
NuGet auth is working through a plugin mechanism (via MEF in Visual Studio).

What's the private feed in question here? 
Is an Azure DevOps one? There were some related issues with caching the user information that they've fixed since 15.6 but I am not certain if it's the same. 

Are you still able to reproduce this in 15.9.x of VS?

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.

**Comment by asutoshbiswal1995** [comment]
@nkolev92  In my project when I go to Manage Nuget Package->Add Package Source and if at the source I am giving my github package link https://nuget.pkg.github.com/repoName/index.json and click on update and Ok then it is supposed to ask me for the credentials which it didn't ask rather it gave me this error:  _**[github] Failed to retrieve metadata from source 'https://nuget.pkg.github.com/repoName/query?q=Associa&skip=0&take=26&prerelease=false&semVerLevel=2.0.0'.
  Response status code does not indicate success: 401 (Unauthorized).**_

**Comment by aharwood2** [comment]
I had to go to the Windows Credential Manager and revoke all the Github related credentials to force it to re-prompt me.

**Comment by zrawatm** [comment]
> @nkolev92 In my project when I go to Manage Nuget Package->Add Package Source and if at the source I am giving my github package link https://nuget.pkg.github.com/repoName/index.json and click on update and Ok then it is supposed to ask me for the credentials which it didn't ask rather it gave me this error: _**[github] Failed to retrieve metadata from source 'https://nuget.pkg.github.com/repoName/query?q=Associa&skip=0&take=26&prerelease=false&semVerLevel=2.0.0'. Response status code does not indicate success: 401 (Unauthorized).**_

works for me also

**Comment by patrickxavierms** [comment]
Had the same problem. I ended up running on command prompt `dotnet nuget update source "NAME" --username USERNAME --password PASSWORD` and it fixed the problem.
