### ISSUE TITLE
NuGet Package Manager UI fails to update imports when ignore dependencies option is present

### ISSUE THREAD

**Issue by jmusek** [NuGet/Home#7356]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 4.8.1.5435

VS version (if appropriate): 15.8.4

OS version (i.e. win10 v1607 (14393.321)): win10

Worked before? If so, with which NuGet version: Not sure

## Detailed repro steps so we can see the same problem

1. Install a pre-release version of package (i.e. 1.0.0-alpha) which add custom build targets as another import to project file.

2. Use UI to update to version 1.0.0

## Problem
After update both imports are kept (for alpha paths and stable paths) which fails to build the project when packages are restored in clean repository.

## Expected
After update old paths are replaced with new ones.

## Other
This is not happening when update is called with dependencies options set to: Lowest or when executed from Package Manager Console (even with -ignoredependencies option it works properly) or command line.

**Comment by nkolev92** [comment]
@jmusek 

Was the project file modified manually by any case? 

Is this reproducible with new projects? 

Can you provide an example package for which you are seeing this behavior.

**Comment by nkolev92** [comment]
Closing this issue as no repro was provided. 

Please create a new issue for future problems.
