### ISSUE TITLE
nuget package versions do not change on changing project .Net version

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#7358]
## Details about Problem

NuGet product used - VS UI

NuGet version: 4.8.1.5435

VS version: 15.8.6

OS version: 17134.320

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a porject in one verison, eg:, in .Net Framework 4.6.2 and get all the nuget packages

2. The downloaded pacakges are of .NetFramework 4.6.2

3. Change the taget framwork version for the project to 4.7.2

4. The nuget package versions are not changed (check in packages.config)

**Comment by nkolev92** [comment]
If you are using packages.config the retargeting story is not pretty. 

You need to run `Update-Package -Reinstall` in PMC. 

Note that the versions will stay the same, but the assets selected for them might.

**Comment by nkolev92** [comment]
Closing as there's no response.

**Comment by ranjan-2209** [comment]
Sorry, I am late for response. Too much workload in office

`Update-Package -Reinstall` solved the problem.

I was thinking it would have been better if it was directly without opening PMC
