### ISSUE TITLE
dlls aren't referenced to the project if packages.config is edited manually

### ISSUE THREAD

**Issue by ranjan-2209** [NuGet/Home#7359]
## Details about Problem

NuGet product used - VS UI

NuGet version: 4.8.1.5435

VS version: 15.8.6

OS version: 17134.320

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. If the packages.config is added manually, then on checking the project's Nuget references, we can see them

2. But the dlls aren't referenced to the project

**Comment by StingyJack** [comment]
When you change the target project framework or bitness, or if you edit the packages.config manually, you should run `update-package -reinstall` with the appropriate options to have nuget fix the references.

Also, check to make sure the csproj isnt setup to use package reference already. VS will default new projects to one style of nuget or the other and it will ignore the other totally.

**Comment by ranjan-2209** [comment]
ya, this works
even if packages.config is open
i think this should be the by default instead of manually doing `update-package -reinstall`

**Comment by StingyJack** [comment]
That probably won't happen as the NuGet team is trying to deprecate package.config in favor of the less useful Package reference.
