### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by skironDotNet** [NuGet/Home#7360]
Apparently the flag from documentation -CertificateFilePath has been replaced with -CertificatePath

**Comment by nkolev92** [comment]
@skironDotNet Can you clarify which document you are referring to? 

It seems up to date here: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-sign#options.

**Comment by skironDotNet** [comment]
I don't remember but I think it used to be part of nuget.org documentation, but I just visited the site and I notice all replaced by docs.microsoft.com so I guess problem solved

**Comment by nkolev92** [comment]
Thanks @skironDotNet for following up. Apologies for our overdue reply.
