### ISSUE TITLE
NuGet package manager does not always update the UI when selecting a package

### ISSUE THREAD

**Issue by AndersBillLinden** [NuGet/Home#7363]
Nuget package manager does not always update its UI when selecting a package. Affected panels are projects which a package is installed in and the package description.

Using:
NuGet version 3.4.4.1321
Visual studio professional 2015 version 14.0.25431.01 Update 3
Windows10 Pro v1803 (17134.285)

Steps I have used:
1. Open nuget package manager
2. Click the "installed" tab, Newtonsoft.Json was selected /although it is not the topmost package), panels seems to be ok.
3. Selecting the topmost package EntityFramework, panels are updating.
4. Selecting Selenium.WebDriver.ChromeDriver

Symptoms:
Panels has not been updated. The caption (above the version checkboxes) has been changed to reflect the name of the selected package (Selenium.WebDriver.ChromeDriver), but the version information in the checkbox list still reflects version for EntityFramework. The description still describes EntityFramework.

**Comment by nkolev92** [comment]
Thanks for reporting the issue. At this point we do not plan on releasing an update for VS2015. Please try latest [VS2017](https://www.visualstudio.com/#) and let us know if you need more help from us.

**Comment by AndersBillLinden** [comment]
The impact of this bug seems to be really severe, or am I wrong? Will you just ignore it for vs2015?
