### ISSUE TITLE
Highlight interactive Credential Provider message

### ISSUE THREAD

**Issue by DerAlbertCom** [NuGet/Home#7364]
## Details about Problem

If I do a `dotnet restore --interactive` or something like that, then on an Azure DevOps NuGet Feed I get ask for authentication (i'm sure for other authenticated feeds also, and it works fine).
```
      [CredentialProvider]DeviceFlow: https://XYZ.pkgs.visualstudio.com/_packaging/main/nuget/v3/index.json
      [CredentialProvider]To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XYZYZYSF to authenticate.
```
But this is in the same color then the other just informational messages. I think it would be useful to highlight that message in another color, because it is a call to action.

## On Windows
> dotnet --version
2.1.402

## suggested behavior

Separate the interaction message with blank lines from the rest, print the messages in a nice green or orange color, so that it will be directly visible.

**Comment by nkolev92** [comment]
Thanks for filing this issue @DerAlbertCom. 

So that is something that we can definitely improve. 
As far as the client is concerned, currently that is a generic log message, so the easiest thing would be for the plugins to add some pretty print around it.

**Comment by nkolev92** [comment]
/cc @satbai 

Maybe the plugin itself could modify the message a bit to improve the visibility.

**Comment by nkolev92** [comment]
For the azure artifacts plugin, the relevant code is here. https://github.com/Microsoft/artifacts-credprovider/blob/c0ef82af5cfef87837ccd7afbbd59925beadc195/CredentialProvider.Microsoft/CredentialProviders/Vsts/BearerTokenProvider.cs#L97-L98

**Comment by satbai** [comment]
The latest version of the credential provider has some additional attention tracking print around the device flow prompt. https://github.com/Microsoft/artifacts-credprovider/releases

**Comment by nkolev92** [comment]
Thanks @satbai.
