### ISSUE TITLE
NuGet.Client: Unit tests related to downloading WindowsAzure.Storage v6.2.0 failing

### ISSUE THREAD

**Issue by Stevie-O** [NuGet/Home#7365]
A clean checkout of NuGet.Client

## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 4dbe61444253d84d37e3629c1c47b00e1495dd43

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Win10 v1703 (15063.1324)

Worked before? If so, with which NuGet version: (unknown)

## Detailed repro steps so we can see the same problem

1. git clone https://github.com/NuGet/NuGet.Client

2. ./build.ps1

## Other suggested things

There are several unit tests failing because they expect exactly 11 files in the downloaded folder (excluding the .nupkg itself), but the actual count is 12.

I tried going checking out the commit in which one of the offending tests was first added, but the code wouldn't build; without a known-good point, I can't bisect the problem.  I suspect, however, it might be the ".nukpg.sha512" file that's being used as a lockfile.

**Comment by nkolev92** [comment]
A bunch of these issues were caused by repo signing on nuget.org and have been addressed when seen over the last few months.
