### ISSUE TITLE
Requiring direct dependencies on projects to be referenced

### ISSUE THREAD

**Issue by JacobSnyder** [NuGet/Home#7369]
We recently migrated to the new csproj format, and really appreciate all the benefits of not having to specify all of the transitive dependencies any more. However, this has changed the previous behavior where direct dependencies (especially on another project) must be explicitly referenced or you get a compilation error. 

There are a few big advantages in ensuring that direct dependencies are explicit in the .csproj:

- No risk of another project changing their dependencies and breaking your project because you used to get them transitively.
- Makes it much easier to discover direct dependencies across a large code base (you just have to search the .csproj’s for the references).
- When trying to decouple dependencies, it’s much easier to find all the direct dependencies by just removing the reference and letting the compiler find usages. With all of the transitive dependencies being brought in as well, you can no longer rely on this working.
 
We're aware of the PrivateAssets feature documented [here](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets).  This seems to be the route towards restoring the desired behavior.  We've done some experiments and are pretty sure we can get the behavior we want by adding Compile to the current defaults (e.g. setting PrivateAssets to `ContentFiles;Analyzers;Build;Compile`).  This gets us back to how project references used to work and does exactly what we want.
 
This is the point where it starts to feel like we're doing something wrong, swimming upstream, or going against the flow.  Ideally, we'd be able to change the "default" PrivateAssets value somewhere in our shared props file or something, but we’ve not been able to figure out how to do this.  [This spec](https://github.com/NuGet/Home/wiki/Change-the-default-build-dependency-asset-behavior-to-transitive) leaves adjusting this default as an open issue, but is trying to modify the "default" PrivateAssets value just like we are.  I tried to modify the Package References and Project References in a pre-build target, but the changes don't seem to get picked up, still allowing transitive dependencies to flow across project reference.  This leaves us with annotating all of our references with `PrivateAssets="ContentFiles;Analyzers;Build;Compile"`.  This is a maintenance nightmare, requiring everyone to manually edit the csproj when adding project or package references. Is there any way we can change the defaults for Private Assets?

**Comment by rrelyea** [comment]
Sounds like you are not liking the fact that ProjectReferences in SDK projects are transitive by default.
(yes, nuget packagereferences also have that behavior...)

But it sounds like you said: "especially on another project"

See: https://stackoverflow.com/questions/42428571/transitive-references-in-net-core-1-1

Also: https://github.com/dotnet/sdk/issues/200
