### ISSUE TITLE
dotnet restore Ambiguous project name 'project'

### ISSUE THREAD

**Issue by green4don** [NuGet/Home#7372]
## Details about Problem

NuGet product used: Package Manager Console

NuGet version: 4.8.0.5385

dotnet.exe --version (if appropriate): 2.1.400

VS version: 15.8.1

OS version: win10 v1803 (17134.285)): 

Worked before? first time using

## Detailed repro steps so we can see the same problem

1. Open solution

2. run 'dotnet restore' in package manager console

3. shows error: 

C:\Program Files\dotnet\sdk\2.1.400\NuGet.targets(114,5): error : Ambiguous project name 'project'. [C:\Users\Don\Visual Studio 2017\Projects\WTF\WTF.sln]

## Other suggested things
I have a solution which is many years old and moved from VS to VS and now resides on VS2017. I have a need for multi target to both NET35 (which is my base supported version) and NET40 (to use Task and async/wait) and so need to add .NETStandard2.0 as well to use the TFM feature in VS. Of course, that means I now need to 'dotnet restore' and fuss with nuget when I want nothing to do with it. And somehow figure out how to suppress all the standard errors.

This project port so far consists of 3 library modules (T, A, B) and one windows form application G. 
I now add references between these and they show up in a new folder PROJECTS under the NETSTANDARD dependency. Slightly new behavior, but fine. It's a reference, to a project and its dll

A -> T
B -> T
G -> T,  A, B

This fails as shown in the examples here.

If I remove the dependencies, it restores fine.

I have dozens of projects left to port and all of them have dependencies, so I can work for now by using 'dotnet restore' and then adding the dependencies back, but this isn't a long term solution.

Either I'm not doing something right or don't understand (certainly possible, maybe even probable) or else something is amiss.

Thanks.

### Verbose Logs

[dotnet.log](https://github.com/NuGet/Home/files/2453552/dotnet.log)

### Sample Project

[WTF.zip](https://github.com/NuGet/Home/files/2453557/WTF.zip)

**Comment by green4don** [comment]
p.s. I've read all the relevant 'ambiguous project' issues and they all use extreme brevity and code words and all seem to be talking about pulling code out to build packages. Circular is the term used frequently which is why I pulled the dependencies out and tested. But still makes no sense or gives me any help.

**Comment by green4don** [comment]
And still am presented with the error message "Error occurred while restoring NuGet packages: Ambiguous project name 'project'." when compiling the project.

**Comment by green4don** [comment]
Where this cycle is defined is eluding me.
Now I can not compile application G because of errors in library B.

<pre>
Error occurred while restoring NuGet packages: Ambiguous project name 'B'.
1>------ Build started: Project: G, Configuration: Debug x86 ------
1>C:\Users\Don\Visual Studio 2017\Projects\TeamMulti\G\G.csproj : error NU1108: Cycle detected. 
1>C:\Users\Don\Visual Studio 2017\Projects\TeamMulti\G\G.csproj : error NU1108:   G -> B -> B.
1>Done building project "G.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
</pre>

B has no references to B that I can find, but everytime nuget touches this project nuget believes it does.

Attached are the B.csproj and project.assets.json files.

[B.zip](https://github.com/NuGet/Home/files/2454447/B.zip)

**Comment by jainaashish** [comment]
With your first repro `WTF.zip` issue is that your `TeamMate.csproj` define it's `PackageId` as `BridgeMate` which is why it throws `Ambiguous project name` so fix your TeamMate project and it will work fine.

There might be similar issue with your another project, so check all your projects.

**Comment by green4don** [comment]
Thank you very much.
These were ported projects; some have a project_id, others do not.
Gone everywhere for now as this seems a new thing that wasn't around before.
The project_guid is gone as well, and references are by name now instead of
this guid, probably better.

*Don Greenwood*

**Comment by green4don** [comment]
The problem (as pointed out by Ashish Jain, thank you) is the project_id field present in some of the csproj files. These need to be unique or blank.
