### ISSUE TITLE
A question about transitive project/package references

### ISSUE THREAD

**Issue by ilya-chumakov** [NuGet/Home#7373]
## Details about Problem

NuGet product used: VS UI | dotnet.exe

NuGet version: 4.7.0.5

dotnet.exe --version (if appropriate): 2.1.400

VS version (if appropriate): 15.8.4

OS version: win10 v1803 (17134.286)

Worked before: Nothing is broken, I guess.

## Detailed repro steps so we can see the same problem

We have a core nuget package C used by nuget package P. Then, the application A directly references C as a dotnetcore project (they both are in the same solution):

    P -> (nuget) C1
    A -> (nuget) P
    A -> (csproj) C2

C1, C2 are two different versions of C codebase. C2 has some of the code removed. However, P uses that code and this is why it still references C1 package.

However, if we run the app A and call P-related code, we get a runtime "MissingMethodException" because A directly references C2 with the code already removed.

I know this referencing scheme is weird. Is it possible to keep both `P->C1` and `A->C2` references?

**Comment by rrelyea** [comment]
Do C1 and C2 have the same assembly name?
What assembly versions do they have?

**Comment by ilya-chumakov** [comment]
@rrelyea, here is our csproj:

```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <VersionPrefix>2.1.0</VersionPrefix>
    <VersionSuffix>$(VersionSuffix)</VersionSuffix>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
```
  
So, the nuget package has the full package version "2.1.0-buildXXX". We do not explicitly set the assembly version, it is '2.1.0' in both assemblies, just as well as the assembly name is the same.

**Comment by nkolev92** [comment]
This is more of a runtime conflict resolution problem. 
You need the assembly names to be different for this to work.

**Comment by ilya-chumakov** [comment]
Sad to hear that. As a workaround, we publish the core nuget package and its dependent packages at once, to keep it in-sync with the latest directly referenced code. One day we'll make things right and remove the csproj reference.
