### ISSUE TITLE
Current approach to packaging x86 and x64 assemblies 

### ISSUE THREAD

**Issue by quasarea** [NuGet/Home#7374]
## Details about Problem

Cannot find any documentation on how to release x86 and x64 assemblies in a single package. I 

The [supporting-multiple-target-frameworks](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks):
> If you have architecture-specific assemblies, that is, separate assemblies that target ARM, x86, and x64, you must place them in a folder named **runtimes** (...)

The [nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec) reference does not even once mention **runtimes** location

From what I have seen after evaluation of few native packages those are stored under **build\native\$(architecture)** or **build\native\bin\$(architecture)** and consumption is supported by .targets

The [nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec) reference mentions **native** location next to **build** not inside it, but this is not supported by nuget package explorer 

My current gut feeling is that I should go with **build\native\x64** and **build\native\x86** but it would be great if I could support it with something more than the gut

Thanks
J

**Comment by nkolev92** [comment]
Try using runtimes/{rid}/native as the first link suggests. 
Unfortunately our documentation is not great when it comes to architecture specific/native packages creation.

**Comment by nkolev92** [comment]
CLosing this as it's a question and is at this point not actionable.
