### ISSUE TITLE
Block NuGet package

### ISSUE THREAD

**Issue by Sc0tTyXL** [NuGet/Home#7378]
After finally [recovering](https://github.com/dotnet/corefx/issues/17522) from the [System.Net.Http](https://github.com/dotnet/corefx/issues/23306) [package](https://github.com/dotnet/corefx/issues/25773) [hell](https://github.com/dotnet/corefx/issues/22781) we would like to block the package entirely. As it is still an issue on .NET Framework projects.

I'm looking for a way to block the package from ever installing, so not blocking or locking a version but the entire package (due to a dependency or developer error). The block should be in the solution folder of the application so that every developer will have the block once updating from SVN.

I've looked at the NuGet.config and .nuspec documentation but was unable to find such a feature. My Google-fu also didn't yield any results. 

It seems that such an option [is not available](https://stackoverflow.com/posts/52715945) could this feature be added?

**Comment by rrelyea** [comment]
Sorry, this is not a feature we have seen many requests for...
My guess is that doing this at the msbuild level would be a better place.
