### ISSUE TITLE
NuGet.Build.Tasks.Pack package does not have license information

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#7379]
Package https://www.nuget.org/packages/NuGet.Build.Tasks.Pack should include license information as other packages owned by the nuget account.

**Comment by rrelyea** [comment]
@PatoBeltran - did this get fixed with your metadata change in 4.9.1?  (/cc @nkolev92 )

**Comment by nkolev92** [comment]
Doesn't seem covered.

**Comment by nkolev92** [comment]
Visual inspecting it, the following look inconsistent. 
Request license acceptance is false, but should be true.
licenseUrl, projectUrl, icon Url are not set. 

The tags are not set. 
The copyright is wrong, say .NET Foundation, while it should be Microsoft.

**Comment by nkolev92** [comment]
This is the only package that failed that validations through int.

**Comment by nkolev92** [comment]
Dev is fixed. 
In 4.9.1 we were still using the nuspec to pack.
Pato is changing that.

**Comment by nkolev92** [comment]
This was fixed.
