### ISSUE TITLE
Targeting net461, nuget doesn't use netstandard2.0 version of package dependencies

### ISSUE THREAD

**Issue by cortex93** [NuGet/Home#7385]
dotnet.exe --version (if appropriate):
2.1.402
VS version (if appropriate):
15.8.6

When adding a package reference with dependencies on .netstandard2.0, .netstandard1.6 and net451, nuget doesn't use .netstandard2.0 constraints.

1. Create a net sdk project targeting net461
2. Add PackageReference Microsoft.Diagnostics.EventFlow.Core 1.5.1
3. Add PackageReference Microsoft.Extensions.Configuration.Abstractions 2.1.1
4. dotnet restore

warning NU1608: Detected package version outside of dependency constraint: Microsoft.Diagnostics.EventFlow.Core 1.5.1 requires Microsoft.Extensions.Configuration.Abstractions (>= 1.1.1 && < 2.0.0) but version Microsoft.Extensions.Configuration.Abstractions 2.1.1 was resolved.

Microsoft.Diagnostics.EventFlow.Core as following dependencies
.NETFramework, Version=v4.7.1
Microsoft.Extensions.Configuration.Abstractions (>= 2.0.1)
.NETFramework, Version=v4.5.1
Microsoft.Extensions.Configuration.Abstractions (>= 1.1.1 && < 2.0.0)
.NETFramework, Version=v1.6
Microsoft.Extensions.Configuration.Abstractions (>= 1.1.1 && < 2.0.0)
.NETFramework, Version=v2.0
Microsoft.Extensions.Configuration.Abstractions (>= 2.0.1)

As, net461 supports netstandard2.0, I expect it resolves with .NETFramework, Version=v2.0 constraints but it seems it use either net451 or netstandard1.6.

**Comment by nkolev92** [comment]
This is by design. 
Same framework identifier is considered closer than netstandard.

netXY will always be selected before NetstandardXY

See related issue https://github.com/NuGet/Home/issues/5370.
