### ISSUE TITLE
C++ restore target doesn't restore when executed from command line 

### ISSUE THREAD

**Issue by quasarea** [NuGet/Home#7386]
## Details about Problem
NuGet product used msbuild /t:restore
VS version: 15.8.169+g1ccb72aefa
OS version: win10 v1803 (17134.286)):

Worked before? no

## Detailed repro steps so we can see the same problem

1. Create new **Windows Console Application** for **C++**
2. Add nuget package reference, i.e. for jmessage-cpp
3. Wait, packages.config will be created
4. Switch to console, remove packages folder from project
5. msbuild /t:restore,build ConsoleApplication1\ConsoleApplication1.vcxproj

## Verbose Logs
    msbuild /t:restore,build ConsoleApplication1\ConsoleApplication1.vcxproj
    Enterprise
    Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.
    Build started 10/10/2018 13:08:20.
    Project "C:\Users\user\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj" on node 1 (restore;build target(s)).
    Restore:
    Nothing to do. None of the projects specified contain packages to restore.
    C:\Users\user\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj(177,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is . .\packages\cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn.2.9.1\build\native\cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn.targets.
    Done Building Project "C:\Users\user\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj" (restore;build target(s)) -- FAILED.

    Build FAILED.

    "C:\Users\user\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj" (restore;build target) (1) ->
    (EnsureNuGetPackageBuildImports target) ->
    C:\Users\user\Documents\Visual Studio 2017\Projects\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj(177,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is  ..\packages\cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn.2.9.1\build\native\cpprestsdk.v140.windesktop.msvcstl.dyn.rt-dyn.targets.

        0 Warning(s)
        1 Error(s)

[ConsoleApplication1.zip](https://github.com/NuGet/Home/files/2464639/ConsoleApplication1.zip)

**Comment by rrelyea** [comment]
msbuild /restore or msbuild /t:restore doesn't support Packages.Config.
From the command line, nuget.exe is your only choice.

**Comment by konard** [comment]
`nuget.exe` restores packages to `packages` folder near `.sln` file. How to configure msbuild to take packages from that folder?

Update.
Using `NuGet.config` near `.sln` file.

**Comment by molesmoke** [comment]
You can now use PackageReference elements in C++/CLI projects:
https://devblogs.microsoft.com/cppblog/announcing-nuget-packagereference-support-for-c-cli-msbuild-projects-targeting-net-core/
