### ISSUE TITLE
Can we define packageType = Template in a .csproj file?

### ISSUE THREAD

**Issue by PureKrome** [NuGet/Home#7389]
Hi 👋 

I'm trying to see if it's possible to package a nuget from a `.csproj` where the package type is a `Template`.

---

NuGet product used: `VS UI` | `dotnet.exe`
dotnet.exe --version: `2.1.403`
VS version: `15.8.7`
OS version (i.e. win10 v1803 (17134.345)):

So I'm trying to [create a new custom template using the `dotnet new` template](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template). Part of the steps include creating a `.nupkg`. [The example documentation](https://docs.microsoft.com/en-us/dotnet/core/tutorials/create-custom-template#pack-the-template-into-a-nuget-package) says to do this using `nuget pack <nuspec file>`.

I'm trying to do this with `dotnet pack` instead. `nuget.exe` isn't in my path (yes, I know I can download it, etc) so I'm trying to do with the existing tools possible / least amount of friction.

In the `.nuspec` file it says we need to define the nuget package to be a  `template` like:

```
<packageTypes>
  <packageType name="Template" />
</packageTypes>
```

Is there a way we can define this in a `.csproj` file, so then I might be able to use `dotnet pack` instead?

**Comment by rrelyea** [comment]
It looks like setting the csproj property "PackageType" will be persisted as a PackageType when dotnet pack is used. NuGet.Build.Tasks.Pack.Targets defines a Target named "GenerateNuspec" which will pass $(PackageType) into the PackTask.

If this works well, or even better, please consider doing a doc PR or a doc issue to "The example documentation" page you link to in your initial comment.

**Comment by loic-sharma** [comment]
Should we add it to this documentation? https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#istool

**Comment by nkolev92** [comment]
Closing in favor of https://github.com/dotnet/docs/issues/17967

**Comment by Thraka** [comment]
Just to close the loop, those tutorials were rewritten a long time ago and do not use `nuget.exe` at all anymore. Instead they use the `<PackageType>Template</>` syntax along with `dotnet pack`.
