### ISSUE TITLE
Install-Package specify target directory

### ISSUE THREAD

**Issue by NCC1701M** [NuGet/Home#739]
When I install a package like angular-winjs it's not installed in the scripts folder, it's installed on the top level of my solution. I can't tell Install-Package a path where the package should be installed. Please implement such an option.

**Comment by yishaigalatzer** [comment]
What project type is this for?

**Comment by NCC1701M** [comment]
Default ASP.NET Web Application

**Comment by yishaigalatzer** [comment]
You have to copy the files manually for this scenario. Script packages targeting ASP.net should put the content in the scripts folder.

We will discuss support for such a feature, I'm not convinced this is the right approach though. You are already a manual decision the gap to copying the files over is quite minor. I'd like to see a better solution.

You can also consider using bower instead.

**Comment by yishaigalatzer** [comment]
This is a known issue, and we don't plan to make any changes here. winjs have bower packages, and that would be your best way forward.

We added bower support to Visual Studio 2015. If you want more or are missing any issues the Visual Studio Web teams wants you to vote on aspnet.uservoice.com
