### ISSUE TITLE
Restricting restore to explicitly specified feeds

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#7392]
Is it possible to restrict nuget restore to feeds explicitly specified in `RestoreSources` and/or `NuGet.config` file in the repository directory, without loading NuGet.config files from anywhere else on the machine (like user roaming directory, user profile directory, nuget under program files, etc.)? 

This is needed to make builds deterministic across machines, that is the same restore behavior regardless of machine state.

**Comment by rrelyea** [comment]
I believe you'll only load settins from one config file if you do the following:
dotnet restore --configfile c:\foo\nuget.config 

msbuild properties can still pull in sources, that aren't controllable using command line switches. Just normal msbuild properties, etc...

**Comment by rrelyea** [comment]
At the solution level, or above (repo?), you can also have a nuget.config that clears sources, clears disabledsources, and then sets the appropriate sources.  This allows normal projects to just work, without needing a special command line switch to restore.

**Comment by tmat** [comment]
I was able to remove the extra (outside of repo) nuget.config files by specifying 

```
<RestoreConfigFile>$(RepoRoot)NuGet.config</RestoreConfigFile>
```

in the project. Without this property the consulted config files are:

![image](https://user-images.githubusercontent.com/41759/46882084-4fddea00-ce02-11e8-9e30-3a35f2154abf.png)

with this property set it's just that one config file:

![image](https://user-images.githubusercontent.com/41759/46882512-d2b37480-ce03-11e8-9942-ebcb0d29ea73.png)

Is this the right way to do this? Will the behavior be consistent between restoring from VS and from command line build?

**Comment by anangaur** [comment]
The label states `ClosedAs:Question` but the issue isn't closed. Should it be? @rrelyea @tmat ?
