### ISSUE TITLE
dotnet restore: package sources with TCP port specified try to download packages from URL without port

### ISSUE THREAD

**Issue by shadow-cs** [NuGet/Home#7397]
## Details about Problem

`dotnet restore` doesn't seem to support servers running on non-standard ports.

I'm using `dotnet.exe`: `2.1.403`

NuGet version: `4.8.1.0`

OS version: Windows 7 7601 SP1

### Steps

1. Create a NuGet server running on port other than `80` (probably HTTPS on non-`443` will fail as well)
2. Publish a Package to the server
3. Add the server to `NuGet.config`
4. Create a project with a dependency to Package
5. Run `dotnet restore`

### TL;DR

I tried to access private repository running on `http://192.168.x.x:8000/feed` that uses basic auth,
I successfully added the feed URL to `NuGet.Config` including credentials. 

Nuget is able to find the package, the server responds to `http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0` with `401` followed by another request with `Authorization` header correctly set and the server responds with `200`.

Then another request is made to `http://192.168.x.x/feed/package/PkgName/0.0.1`, the `8000` port is missing in this request which results in an error.

Nuget then retries to find the package which succeeds (with the same procedure as described above).

The operation fails with following error message:

```
C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error : The feed 'feed
[http://192.168.x.x:8000/feed/]' lists package 'PkgName.0.0.1' but multiple
attempts to download the nupkg have failed. The feed is either invalid or
required packages were removed while the current operation was in progress.
Verify the package exists on the feed and try again. [D:\...\Import.csproj]
C:\Program Files\dotnet\sdk\2.1.403\NuGet.targets(114,5): error :   Unable to
find package 'PkgName.0.0.1'.
```

## Other suggested things

I tried running `dotnet restore -s http://192.168.x.x:8000/feed/` but with no success.

### Verbose Logs

```
CACHE https://api.nuget.org/v3-flatcontainer/pkgname/index.json (TaskId:25)
GET http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 (TaskId:25)
OK http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 235ms (TaskId:25)
GET http://192.168.x.x/feed/package/PkgName/0.0.1 (TaskId:25)
NotFound http://192.168.x.x/feed/package/PkgName/0.0.1 38ms (TaskId:25)
GET https://api.nuget.org/v3-flatcontainer/pkgname/index.json (TaskId:25)
GET http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 (TaskId:25)
OK http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 112ms (TaskId:25)
OK https://api.nuget.org/v3-flatcontainer/pkgname/index.json 310ms (TaskId:25)
CACHE https://api.nuget.org/v3-flatcontainer/pkgname/index.json (TaskId:25)
CACHE http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 (TaskId:25)
CACHE http://192.168.x.x:8000/feed/FindPackagesById()?id='PkgName'&semVerLevel=2.0.0 (TaskId:25)
```

**Comment by shadow-cs** [comment]
`NuGet.exe` v4.1.0.2450 doesn't work as well for .NET Frameworks projects.

**Comment by rrelyea** [comment]
What type of server do you have running on that port?  (VSTS, myget, nuget server, etc...)
Do you have the same problem with dotnet SDK 2.0? (does it start with 2.1?)

**Comment by shadow-cs** [comment]
We're running ProGet server for evaluation purposes... We'll soon be migrating to HTTPS. I'll retry with 2.0 as soon as I get back to work on Monday. But I don't think this is a `dotnet` CLI regression as `NuGet.exe` exhibits the same issue

**Comment by shadow-cs** [comment]
> Do you have the same problem with dotnet SDK 2.0?

@rrelyea just tested with `2.0.3` with the same outcome.

**Comment by shadow-cs** [comment]
Looks like this is the issue of the server, `FindPackagesById()` returns the address (in the `content` element) without port.

**Comment by craigbrett17** [comment]
@shadow-cs: Did you figure out how to fix this on ProGet? I'm seeing the same issue

**Comment by darkvertex** [comment]
This is still an issue. 😢

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="internal" value="http://internalserver:2015/index.json" protocolVersion="3" allowInsecureConnections="true" />
  </packageSources>
</configuration>
```

Something like this will still access `internalserver` on port 80 (or 443 if https) regardless of the port number explicitly clarified.
