### ISSUE TITLE
NuGet.PackageManagement: packages.<projectName>.config scenario does not work when packages.config is edited after opening the solution

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#74]
NuGet.PackageManagement: packages.<projectName>.config scenario does not work when packages.config is edited after opening the solution

**Comment by deepakaravindr** [comment]
Following functional tests are failing...

run-test UpdatePackagePreservesProjectConfigFile 
run-test InstallPackageAddMoreEntriesToProjectConfigFile 
run-test InstallPackageToWebsitePreservesProjectConfigFile 
run-test InstallPackagePreservesProjectConfigFile

**Comment by danliu** [comment]
one more 
run-test UpdatePackagePreservesProjectConfigFile

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.PackageManagement/commit/ada97b47f73b1cf4da001ab0aaa567c6248d94ab and https://github.com/NuGet/NuGet.VisualStudioExtension/commit/248a7d8637a49afffce8fd4eff66396678549e06
