### ISSUE TITLE
LightSwitch Designer Hosting package did not load correctly

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#740]
repro steps:
1. create lightswitch application

expected results: create successfully
actual results: a warning dialog pop up, LightSwitch Designer Hosting package did not load correctly

repro env: VS2015 23005.1 D14Rel + NuGet 3.0-rtm 527

![lightswitcherror1](https://cloud.githubusercontent.com/assets/11768961/8032696/97c96a9e-0e0a-11e5-8b5e-0da1432456c2.PNG)
![lightswitcherror2](https://cloud.githubusercontent.com/assets/11768961/8032695/97c69ae4-0e0a-11e5-9f65-855b5342d6ec.PNG)

**Comment by danliu** [comment]
This issue is external to NuGet and have filed an external bug for it.

**Comment by gsumankumar** [comment]
is there any solution to issue? share the link how to resolve it ?
