### ISSUE TITLE
Package reference doesn't work with template wizard apis 

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7405]

**Comment by dotMorten** [comment]
I'm finding that this work fine with UWP, however I'm having problems with this on WPF. It works on a few PCs and not on most others. Same VS version and more or less the same extensions installed.

**Comment by nkolev92** [comment]
@karann-msft Is this different than https://github.com/NuGet/Home/issues/4693?
Should it be closed in favor of that one?

**Comment by karann-msft** [comment]
@nkolev92 I guess you are right. Closing as dupe of #4693
