### ISSUE TITLE
Provide a way to access the value and type of the license without attempting to parse license expression

### ISSUE THREAD

**Issue by agr** [NuGet/Home#7406]
Currently, it seems, the only way to get the data specified in the &lt;license> node of the nuspec file is to call the `NuspecReader.GetLicenseMetadata`. This performs full processing of the value including the license expression parsing. If someone wants to protect themselves from parsing multi-megabyte license expressions they might want to check the length of the expression before attempting to parse it. It would be nice to have a way to access the value of license expression without attempting to parse it.

Being able to check the license expression type in the same minimal processing mode would also be nice.

- improve the error conditions when the license metadata does not contain the type.

**Comment by nkolev92** [comment]
We discussed this offline. 

This doesn't seem something that would be a 4.9 blocker imo, as @agr already uses a custom parsing mechanism. 

Furthermore there are no "functional" issues with the current implementation, and there would not be a problem if the gallery depended on a 5.0 version of the client libraries. 

I am moving this to 5.0.

**Comment by nkolev92** [comment]
I believe there's no scenario for adding this right now. 
It's super easy for any custom parsers to just look at the XML.
