### ISSUE TITLE
System.Numerics: A possibly wrong implementation of a Matrix3x2 Multiply method in Matrix3x2 class

### ISSUE THREAD

**Issue by johnpiliounis** [NuGet/Home#7408]
Hello.
The problem seems to be a class/method implementation inside the System.Numerics namespace. There is a class under the name Matrix3x2 and a Multiply method inside it where there is 'defined' a Matrix3x2.Matrix3x2 matrices multiplication, which is completely erroneous. One can simply NOT multiply a 3x2 matrix by a 3x2 matrix. It's completely undefinable in Mathematics. Number of columns of the first matrix MUST be equal to the number of rows of the second matrix in any two matrices multiplication for it to be valid. You may check the implementation at: https://referencesource.microsoft.com/#System.Numerics/System/Numerics/Matrix3x2.cs,8b8d67bb6823c1b6 

/// <summary>
        /// Multiplies two matrices together and returns the resulting matrix.
        /// </summary>
        /// <param name="value1">The first source matrix.</param>
        /// <param name="value2">The second source matrix.</param>
        /// <returns>The product matrix.</returns>
        public static Matrix3x2 Multiply(Matrix3x2 value1, Matrix3x2 value2)
        {
            Matrix3x2 result;
 
            // First row
            result.M11 = value1.M11 * value2.M11 + value1.M12 * value2.M21;
            result.M12 = value1.M11 * value2.M12 + value1.M12 * value2.M22;
 
            // Second row
            result.M21 = value1.M21 * value2.M11 + value1.M22 * value2.M21;
            result.M22 = value1.M21 * value2.M12 + value1.M22 * value2.M22;
 
            // Third row
            result.M31 = value1.M31 * value2.M11 + value1.M32 * value2.M21 + value2.M31;
            result.M32 = value1.M31 * value2.M12 + value1.M32 * value2.M22 + value2.M32;
 
            return result;
        } 

Please explain this implementation.
Thank you very much,
John Piliounis (BSc/MSc-Physics, MSc-ECE)

**Comment by nkolev92** [comment]
This is not the right repository for this issue. 

This is the repository for the NuGet Client. 

Please try stackoverflow or https://developercommunity.visualstudio.com for such questions.

**Comment by johnpiliounis** [comment]
I had initially posted it to https://developercommunity.visualstudio.com  and they directed me to post it here. John

**Comment by nkolev92** [comment]
@johnpiliounis 
Unfortunately that was a bad advice. 

NuGet has nothing to do with that implementation. 

As far as I'm aware, there's not even a package for this, it's part of the framework. 
Even if there was a package, the NuGet team does not support individual packages and the owners should be contacted in that case. 

Can you provide the link to the developer community issue?

**Comment by johnpiliounis** [comment]
Hello again Nikolche.
I eventually located the page @ social.msdn.microsoft.com forums where I 
first interacted regarding the
issue. Please find attached the full chat's content at the page where 
they advice me to address the issue
first at githubm/nuget.
John
