### ISSUE TITLE
Work around for if updated package has an added assembly, a new reference gets added during update nuget CLI command 

### ISSUE THREAD

**Issue by yash9patel** [NuGet/Home#7410]
I would like to find out if there is a work around to add dependent assembly for package that is being updated using nuget.exe update command. Is there a way to detect if package has dependent assembly that needs to be added?

NuGet product used (NuGet.exe):

NuGet version (4.7.1.5393):

OS version (win10):

NuGet.exe update

**Comment by nkolev92** [comment]
Not with nuget.exe nuspec pack. 

You can consider using the targets pack (sometimes called dotnet.exe pack) for PackageReference projects 
https://www.nuget.org/packages/NuGet.Build.Tasks.Pack/. 

That will automatically include project references as package references. 

However there is no way to include dependent assemblies that are not packed. 
https://github.com/NuGet/Home/issues/3891

For those cases you still need a nuspec file.
