### ISSUE TITLE
Add documentation for RestoreUseSkipNonexistentTargets environment variable

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7415]
Documentation for the `RestoreUseSkipNonexistentTargets` environment variable, as required by https://github.com/NuGet/Home/issues/7292, is missing at https://docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables.

**Comment by nkolev92** [comment]
The root docs issue probably belongs in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets. 

I'm still curious to learn more about your scenario in the other issue as I am not yet sure how nuget.exe is failing.

**Comment by pascalberger** [comment]
@nkolev92 You mean documentation in https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets additional to the environment variables documentation or instead of?

**Comment by nkolev92** [comment]
At the bottom, this was a targets change. 

See [this](https://github.com/NuGet/NuGet.Client/blob/26089e454276fa91276282687b84169131124846/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L46)

It's just that MSBuild can treat env vars as properties so you can change the behavior that way. 

And maybe in addition to increase discoverability.

**Comment by pascalberger** [comment]
While the change was in the targets it also introduced a new environment variable which can be passed to nuget.exe. What's the purpose of the CLI environment documentation page if not documenting all possible environment variables which can be used for the CLI? Especially as this is a CLI specific environment variable, not something that is just passed through. Also it doesn't introduce a new target or change anything target related but just passed a property to the msbuild target, which I never would search for in the targets documentation if there's an environment variable documentation.

**Comment by nkolev92** [comment]
https://github.com/NuGet/docs.microsoft.com-nuget/pull/1395
