### ISSUE TITLE
icon image not showing in designtime

### ISSUE THREAD

**Issue by bochelie1000** [NuGet/Home#7419]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version: 7.0.0-alpha0456

dotnet.exe: 4.5.2

VS version: 2017

OS version :W7

Worked before? If so, with which NuGet version: 6.0

## Detailed repro steps so we can see the same problem

1. I use a UserControl which contains a Button with an Icon and LargeIcon. 

2. This UserControl is then used in my Fluent:MainWindow inside a Fluent:RibbonGroupBox. 

3. The icons in the UserControl Fluent:Button are not shown during designtime (error icon is shown). Icons in the Fluent:MainWindow are ok.

**Comment by nkolev92** [comment]
@bochelie1000 

I don't think you've filled this issue in the correct repo. 

This is the issue repository for the NuGet Client. 

Please consider filing a developer community bug at https://developercommunity.visualstudio.com/ or through the VS, Help => Report a problem workflow.
