### ISSUE TITLE
NuGet should set PreAuthenticate to true to reduce the number of web requests

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#742]
WebRequest.PreAuthenticate is not set to true by NuGet. This means that when connecting to an authenticated feed, or thru an authenticated proxy, NuGet only sends the credentials after a challenge is returned. Seems we should set PreAuthenticate to true. This will  cut down the number of web requests in half.

**Comment by patrickjamesbarry** [comment]
+1

**Comment by yishaigalatzer** [comment]
We reviewed this with the security team, and believe this should not be fixed
