### ISSUE TITLE
Nuget package contentFiles propagation

### ISSUE THREAD

**Issue by hzw53** [NuGet/Home#7420]
## Details about Problem

Consider the following project structure:

Classlib A is consumed by classlib B which is in turn consumed by console app C.
A includes some additional files that have to be shipped along with the assembly.

A.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>nugettest.A</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="texts\file1.txt">
      <PackagePath>contentFiles\any\any\texts</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>
</Project>
```

B.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageId>nugettest.B</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nugettest.A" Version="1.0.0"/>
  </ItemGroup>
</Project>
```

C.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nugettest.B" Version="1.0.1" />
  </ItemGroup>
</Project>
```

I expected file1.txt to be copied to the output folder of C in the subdirectory texts, but
it is not copied at all. It is however copied to the output of B, just as expected.

Inspecting the generated nupkg files I find file1.txt in nugettest.B.1.0.0.nupkg in the path contentFiles\any\netstandard2.0, which
seems suspicious at the least.

Trying various combinations of <IncludeAssets> and <PrivateAssets> did not help, too.

Any ideas how to achieve the CopyToOutput behavior for dependent packages?

NuGet product used: dotnet.exe
dotnet.exe --version: 2.1.402
OS version: Ubuntu 18.04
Worked before? No

**Comment by nkolev92** [comment]
@hzw53 

That has to do with the rules for transitive flow of certian asset groups. 

https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

From the docs. 

Tag | Description | Default Value
-- | -- | --
IncludeAssets | These assets will be consumed | all
ExcludeAssets | These assets will not be consumed | none
PrivateAssets | These assets will be consumed but won't flow to the parent project | contentfiles;analyzers;build

Related issues: 

https://github.com/NuGet/Home/issues/6720
https://github.com/NuGet/Home/issues/6091
