### ISSUE TITLE
Handling of badly signed packages in the .nupkg metadata generation workflow

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7424]
Say you somehow got a badly signed package in the global packages folder prior to 4.9.

You upgrade to 4.9, then you try to restore a project that makes use of the previously extracted badly signed package.

Then the tools try to generate a .nupkg metadata file, the code throws [here](https://github.com/NuGet/NuGet.Client/blob/release-4.9.0-preview5/src/NuGet.Core/NuGet.Protocol/PackagesFolder/NuGetv3LocalRepository.cs#L187)

This basically means that the user sees  a cryptic error and can't get out of that state unless they the global packages folder.
This however does not prevent them from ending up in this situation again as evidenced by #7423.

This needs addressed before 4,9 ships.

//cc @PatoBeltran @jainaashish @dtivel

**Comment by jainaashish** [comment]
PR merged to release-4.9.0-preview5 as well as dev
