### ISSUE TITLE
Update-Package -Id {PackageName} –reinstall - not working

### ISSUE THREAD

**Issue by vadivel1234** [NuGet/Home#7425]
Hi There,

We have unlisted the few packages which act as a dependency purpose alone from the last main release. Due to which, unlisted packages will not be shown in the VS or in nuget.org. But, we can install it by using the Package Manager console. 

**Update-Package -Id {PackageName} –reinstall** 

The above command is not worked for unlisted packages when need to retarget some projects to other framework version and there is no way how to run **Update-Package -Reinstall** because it doesn't work for unlisted packages. 

**Note:** Using reinstall with specified package Id works in a simple scenario. 

Regards,
Vadivel Natarajan

**Comment by nkolev92** [comment]
Thanks for filing this issue. 

This is a duplicate of https://github.com/NuGet/Home/issues/7268 and there's a WIP fix in https://github.com/NuGet/NuGet.Client/pull/2429

**Comment by vadivel1234** [comment]
Was this fix merged in latest NuGet release?
