### ISSUE TITLE
[Test Failure][Repeatable Restore] Warning: “found invalid data while decoding” occurs when restoring with custom lock file

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7428]
## Details about Problem
NuGet version: NuGet Client Release-4.9.0-preview5\4.9.0.5627
VS Version: D15.9\28219.56
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps 
1. Create a C# Class Library (.NET Framework) project in VS.
2. Install a few ‘PackageReference’ packages into the project.
3. Create a blank ‘custom.lock.json’ file at project directory (alongside *.csproj file).
4. Set MSBuild property “NuGetLockFilePath” to relative path to the above ‘custom.lock.json’ file.
5. Do a restore.
## Expected
No warning show.
## Actual
Warning: “found invalid data while decoding” occourrs as below screenshot. 
![bug7428](https://user-images.githubusercontent.com/20632625/48895063-2d1e0700-ee7f-11e8-9994-c9942341d303.png)

**Comment by jainaashish** [comment]
does this only repros when you opt-in to lock file feature? or does it also repros when you don't preform steps 3 and 4?

**Comment by v-luzh** [comment]
It only repro after doing step5, not repro when I opt-in to lock file feature. It doesn't repro when skipping step 3 and 4.

**Comment by v-nancyj** [comment]
The issue not repro if create ‘custom.lock.json’ file through right click project name->'Add'->'New Item'->'JAON File'->change file name as ‘custom.lock.json’ in step 3.

**Comment by jainaashish** [comment]
This message should be a info instead of warning, to let customer that the current lock file threw parsing exception and we should make sure that the same message doesn't appear again.
