### ISSUE TITLE
Errors from lock file enforcement should show up in Error List Window

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7429]
## Details about Problem
NuGet version: NuGet Client Release-4.9.0-preview5\4.9.0.5627
VS Version: D15.9\28219.56
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps 
1. Create a C# Console Application (.NET Core) project via VS.
2. Install a few ‘PackageReference’ packages into the project.
3. Set MSBuild property “RestorePackagesWithLockFile” to true in csproj file.
4. Do a restore.
5. Check it should have generated ‘packages.lock.json’ file alongside *.csproj file.
6. Set the msbuild property “RestoreLockedMode” to “true”.
7. Install another package.
8. It should still work fine and update ‘packages.lock.json’ file.
9. Manually add a new PackageReference item into csproj file.
10. Perform restore.
## Expected
Error NU1004: “The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Please disable RestoreLockedMode MSBuild property or pass explicit --reevaluate flag to run restore to update the lock file” should show in Error List window.
## Actual
Nothing shows in Error List window as below screenshot. 
![bug7429](https://user-images.githubusercontent.com/20632625/48895104-41fa9a80-ee7f-11e8-86af-6215683a738e.png)

## Note
It just repro on C# Console Application (.NET Core) when restoring through PM UI.

**Comment by jainaashish** [comment]
is the error there in `obj\project.assets.json` file?

**Comment by v-luzh** [comment]
This error is not in obj\project.assets.json file.

**Comment by v-luzh** [comment]
No error show when restoring through command "dotnet restore" on D16.0 28230.56 + NuGet Client Dev 5.0.0.5638.

**Comment by v-luzh** [comment]
This issue is fixed on D16.0 28327.66 + NuGet Client Dev\5.0.0.5703.
