### ISSUE TITLE
Get-Project –All | Add-BindingRedirect doesn't work when using PackageReference

### ISSUE THREAD

**Issue by joshmouch** [NuGet/Home#7432]
I'm trying to add the binding redirects into my app.config, so I'm running the following command:

`Get-Project –All | Add-BindingRedirect`
or
`Get-Project 'MyProjectName' | Add-BindingRedirect`
or
`Add-BindingRedirect 'MyProjectName'`

However, these do absolutely nothing.
I believe this is because I'm using PackageReference instead of Package.config.

**Comment by kirchner-trevor** [comment]
I am also running into this same issue.

**Comment by jeanluc33** [comment]
Likewise.  Add-BindingRedirect does nothing when you switch to PackageReference, but BindingRedirects are still needed it seems!

**Comment by joshmouch** [comment]
Seems like there's some interest around this.  Any comments from the devs?

**Comment by nkolev92** [comment]
Binding redirects is not a concept that's handled by NuGet in the transitive PackageReference world. 

What NuGet used to do itself in packages.config is now moved to https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection. 

Related issue to improve the discoverability of this information. 
https://github.com/NuGet/Home/issues/8356

**Comment by Montago** [comment]
> Binding redirects is not a concept that's handled by NuGet in the transitive PackageReference world.
> 
> What NuGet used to do itself in packages.config is now moved to https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.
> 
> Related issue to improve the discoverability of this information. #8356

This aint working for me. 

I get this error : **System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.** 

Even after enabling Automatic Binding Redirects. 

Microsoft.Bcl.AsyncInterfaces version 6.0.0 is already present.
