### ISSUE TITLE
VS instance directory is configurable; configure.ps1 does not support this

### ISSUE THREAD

**Issue by heaths** [NuGet/Home#7435]
I see in https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/configure.ps1#L95 that you hardcoded the default location for the VS package cache, but this location can be relocated by users (and many do): https://docs.microsoft.com/visualstudio/install/disable-or-move-the-package-cache.

But rather than handling the registry lookup yourself, we recommend you use the installed vswhere.exe tool that is always located in the same place: https://docs.microsoft.com/visualstudio/install/tools-for-managing-visual-studio-instances

**Comment by jainaashish** [comment]
Fixed with https://github.com/NuGet/NuGet.Client/pull/2546

**Comment by rrelyea** [comment]
@heaths - thanks for the contribution. Appreciate it!
