### ISSUE TITLE
NuGet.exe pack fails on wildcard with x64

### ISSUE THREAD

**Issue by spy008** [NuGet/Home#7436]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 4.6.0

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): Visual Studio Professional 2015

OS version (i.e. win10 v1607 (14393.321)): Windows Server 2012 R2

Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

1.  Compile my 64-bit application in Visual Studio with this configuration:
Configuration: Debug | Release
Platform: x64

2.  Verify build output at: C:\dev\MyProject\bin\x64\Release

3.  This is the content of my nuspec:
```
<?xml version="1.0"?>
<package >
  <metadata>
    <id>MyProject</id>
    <version>1.0.0</version>
  </metadata>
  <files>
    <file src="bin\*\*" exclude="**\*.pdb;**\*vshost*" target="Contents\bin" />
  </files>
</package>
```

4.  Run NuGet pack command. Get this error:

> Attempting to build package from 'MyProject.nuspec'.
> Cannot create a package that has no dependencies nor content.

## Other suggested things

The NuGet pack command runs without error with this configuration:
Configuration: Debug | Release
Platform: Any CPU

In the nuspec, I have tried changing to <file src="bin\\**", but it will copy the whole "x64\Release" folder structure to the target rather than just the output files.

### Verbose Logs

C:\NuGet\v4.6.0\nuget.exe pack "C:\dev\MyProject\MyProject.nuspec" -OutputDirectory "C:\dev\BuildArtifacts" -Properties Configuration=Release -version 1.0.0.0

**Comment by rrelyea** [comment]
in my test, that will work if you use:
`   <file src="bin\*\*\*" exclude="**\*.pdb;**\*vshost*" target="Contents\bin" />
`

**Comment by spy008** [comment]
@rrelyea Thanks! That worked for me.
