### ISSUE TITLE
Missing support for VS Modelling Projects

### ISSUE THREAD

**Issue by stunney** [NuGet/Home#744]
Please add .modelproj project type with guid="{f088123c-0e9e-452a-89e6-6ba2f21d5cac}" to the list of supported project types.  This was actually a pull request made a year ago on the codeplex site but it was never merged.

**Comment by stunney** [comment]
Original pull request: http://nuget.codeplex.com/SourceControl/network/forks/stunney/nugetmodelprojSupport/changeset/bc384cde01e0eae418b4ff32190040acdaf556c6

**Comment by yishaigalatzer** [comment]
We can do that for Update I, can you please submit the PR here?

**Comment by stunney** [comment]
I can work on the pull request over the next couple of days.  It looks like the code change is "slightly" different in github compared to the codeplex code base.


What is the deadline for pull requests for update 1?



Sent from Yahoo Mail on Android

**Comment by stunney** [comment]
Hey @yishaigalatzer I am blocked by https://github.com/NuGet/NuGetGallery/issues/2539

**Comment by stunney** [comment]
Hey @yishaigalatzer I am blocked by https://github.com/NuGet/Home/issues/787

**Comment by yishaigalatzer** [comment]
Added some suggestions, we should get this resolved in a couple of days. Right now all heads down on finishing the last few RTM bugs.

**Comment by yishaigalatzer** [comment]
Coming back around to this, #787 is now resolved.

**Comment by yishaigalatzer** [comment]
@stunney, I'm moving out, since this is now been stale for quite some time. We will pull it back when a PR is submitted
