### ISSUE TITLE
Add proper handling of UNLICENSED

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7447]
As part of https://github.com/NuGet/NuGet.Client/pull/2424, the license expression parsing was implemented. 

But the NuGet license expression grammar also calls for the implementation of UNLICENSED. 

```
license-id            = <short form license identifier from https://spdx.org/spdx-specification-21-web-version#h.luq9dgcle9mo>
 license-exception-id  = <short form license exception identifier from https://spdx.org/spdx-specification-21-web-version#h.ruv3yl8g6czd>
 simple-expression = license-id / license-id”+”
 compound-expression =  1*1(simple-expression /
                 simple-expression "WITH" license-exception-id /
                 compound-expression "AND" compound-expression /
                 compound-expression "OR" compound-expression ) /
                 "(" compound-expression ")" )
 license-expression =  1*1(simple-expression / compound-expression / UNLICENSED )
```

**Comment by pombredanne** [comment]
My 2 cents, but using "UNLICENSED"  is not a great choice of words. There is a license called the "Unlicense" ...

**Comment by nkolev92** [comment]
@pombredanne 
Yeah we get that, but it's consistent with NPM and other discussed options are not slam dunks. 

Furthermore as casing matters, the likelihood of someone typing in the wrong license is decreased. 
Furthermore, public feeds should never accept UNLICENSED.
The UI experience also emphasizes when UNLICENSED is used.

**Comment by pombredanne** [comment]
My 2 cents is that the fact that it's consistent with NPM which made a fairly bad choice is not a good argument: a mildly popular bad choice does not make it better. 
`unknown`, `not-specified`, `proprietary` ... or `no-assertion` ... any of these would be better than `UNLICENSED` IMHO.
