### ISSUE TITLE
Nuget Pack command failed.

### ISSUE THREAD

**Issue by yaparlahari** [NuGet/Home#7448]
Hi Team,

We are facing below issue while we are building .net application in Jenkins Job. 

[ERROR] Could not find a part of the path 'E:\jws\CMS\NLG_88\Setup\Release'.
[ERROR] Pack command failed.
[ERROR] Package deploy failed.

**Comment by nkolev92** [comment]
@yaparlahari 

Which version of nuget.exe are you using?
Repro project? 
Are you able to reproduce this locally?

**Comment by Nirmal4G** [comment]
Related issues: #4054 , #4491
