### ISSUE TITLE
nuget.exe pack ignores SDK project's properties

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#7453]
If I `nuget.exe pack .\symbols.csproj` the following csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
   
    <PackageId>Loshar.Symbols</PackageId>
    <PackageVersion>1.0.0</PackageVersion>
  </PropertyGroup>
</Project>
```

The generated package will have the id `symbols` even though the specified package id is `Loshar.Symbols`. Packing this using `dotnet pack` works as expected.

/cc @cristinamanum @shishirx34

**Comment by rohit21agrawal** [comment]
nuget.exe pack isn't supposed to work with sdk style projects.

**Comment by rrelyea** [comment]
Project metadata for Packing, is supported by dotnet pack...not the old nuget pack. (as Rohit says)
our goal is to remove any gaps by adding more features to dotnet pack, and then retire nuget.exe.

**Comment by cristinamanum** [comment]
The nuget.exe ignores the version passed in the Properties command line as well. I tried 4 versions of nuget.exe . All behave the same, they do not add the version. The version is always 1.0.0.

49\nuget.exe pack MyProject.csproj -Properties version="3.1.0"
481\nuget.exe pack MyProject.csproj -Properties version="3.1.0" 
470\nuget.exe pack MyProject.csproj -Properties version="3.1.0"
451\nuget.exe pack MyProject.csproj -Properties version="3.1.0"

**Comment by loic-sharma** [comment]
If that's the case, should we make the NuGet client show an error message if you try to pack an SDK project? The current experience seems like the pack operation half "worked".
