### ISSUE TITLE
Can't install packages in VS 2015 with nuget version 3.6.0-rtm-2511

### ISSUE THREAD

**Issue by avinashpatil3484** [NuGet/Home#7455]
For 'Entity Framework' I have updated my NuGet to latest version i.e. '3.6.0-rtm-2511'.
After successful installation I have restarted the Visual Studio and tried installing 'Microsoft.EntityFrameworkCore' package from NuGet Package Manager and got below error:

Error	:	The 'Microsoft.EntityFrameworkCore 2.1.4' package requires NuGet client version '3.6.0' or above, but the current NuGet version is '3.6.0-rtm-2511'. To upgrade NuGet, please go to http://docs.nuget.org/consume/installing-nuget

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Microsoft.EntityFrameworkCore 2.1.4

NuGet version (x.x.x.xxx): 3.6.0-rtm-2511

dotnet.exe --version (if appropriate): .NET Framework 4.6

VS version (if appropriate): Visual Studio 2015

OS version (i.e. win10 v1607 (14393.321)): Windows 10 Enterprise 

Worked before? If so, with which NuGet version: No.

I also tried uninstalling the 'NuGet' from 'Extension and Updates' and installing the correct version i.e. '3.6.0' but still its giving me same error.

Please tell me how I can degrade this NuGet version to '3.6.0'.

Thanks In Advance.

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
