### ISSUE TITLE
.props and .targets file imports not honored during initial restore? 

### ISSUE THREAD

**Issue by awbushnell** [NuGet/Home#7457]
## Details about Problem

NuGet version (x.x.x.xxx): Package Manager Console Host Version 4.8.1.5435

VS version (if appropriate): Visual Studio 2017  15.8.8

OS version (i.e. win10 v1607 (14393.321)): Microsoft Windows [Version 10.0.17134.254]

## Detailed repro steps so we can see the same problem

We are trying to consume a package via the PackageReference mechnism that as part of it the package contains some targets and props imports that are critical to the build process.  What is noticed is that if we open our solution on a machine that has not download the packages in question, the initial build fails due to the target/props file not being imported. Reloading the solution/project in question does import the props/target files in question. 

Upon some evaluation, it appears that the following lines in the "generated" props and targets files is causing the import to NOT be seen during restore: 

<ImportGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">

Any ideas on how to get around this? Is this a known issue/limitation?

**Comment by nkolev92** [comment]
@awbushnell Do you have a repro project for us?
Clear repro step (example, load sln in VS, run build/rebuild/restore, whatever).
There's a lot of moving parts in your scenario. 

Are you building in Visual Studio?

If you are using an old style csproj based project, then the project-system **never** reloads the props/targets in a session. That's a limitation of the project-system.

But this is all just a guess based on what I could understand from your initial statement.

**Comment by awbushnell** [comment]
@nkolev92 I will try to do a small test case outside of our much larger solution.. out of curiousity, when you say "old style" csproj based project, what do you mean? We certainly are using csproj for our build, is that what you mean a "csproj" in general or is there some versioning in the csproj that will fix this?  We do build from a sln that contains the csproj that has the PackageReference

**Comment by nkolev92** [comment]
Right now, there are 2 different types of projects. 
1. SDK based projects, something like the following: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Versioning/NuGet.Versioning.csproj
It has an SDK import at the top. The files in the project directory are globbed, you can multi target.

2. Old style csproj, is what everyone gets when they create a .NET Framework project right now. 
An example is the following: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/NuGet.PackageManagement.UI.csproj

**Comment by awbushnell** [comment]
@nkolev92 ah, we definitely use the old style and that seems to be the issue then. I will see how easy for this particular project to convert it... Thanks

**Comment by nkolev92** [comment]
Glad we got to the bottom of it. 

I will dup this out to https://github.com/NuGet/Home/issues/7080.
