### ISSUE TITLE
Unable to get updates to the lowest level package

### ISSUE THREAD

**Issue by Pilchie** [NuGet/Home#7460]
_From @Varorbc on October 30, 2018 2:55_

For example, when I have three packages, A depends on,B depends on C. When C updates, project refer to package A cannot get updates to package C

_Copied from original issue: dotnet/project-system#4193_

**Comment by Pilchie** [comment]
Can you describe what you mean in more detail?  How are you referring to packages, what did you try and what did you observe?

**Comment by Pilchie** [comment]
_From @Varorbc on October 31, 2018 0:12_

for example,i have a project refer to `Newtonsoft.Json` package, `Newtonsoft.Json` package depend on `System.ComponentModel.TypeConverter` package(.NETStandard 1.0), `System.ComponentModel.TypeConverter` package depend on `System.Collections` package(.NETStandard 1.0). when `System.Collections` package updates, I can't get an update prompt.I have to wait for them to update before I get the lowest update

**Comment by nkolev92** [comment]
I think https://github.com/NuGet/Home/issues/5887 and https://github.com/NuGet/Home/issues/5553 cover the ask here. 

@varorbc Do you want to see the transitive packages listed so you could make a decision on which exact version is installed or?

**Comment by Varorbc** [comment]
I don't want to see all the transitive packages. I just want to see the packages that are updated.

**Comment by nkolev92** [comment]
I'm not sure I follow. 
Can you please clarify what you mean by `see the packages that are updated` ? 
Updated where?

**Comment by Varorbc** [comment]
Sorry, my English is very poor, I mean, I just want to see the updated package.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
