### ISSUE TITLE
ISettings should not be loaded more than once in restore

### ISSUE THREAD

**Issue by PatoBeltran** [NuGet/Home#7465]
As part of restore, `ISettings` is being loaded once at the beginning, then the file paths to all configs are stored in the [`ProjectRestoreMetadata`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/ProjectRestoreMetadata.cs#L68).

This list is intended to be used to display the list of configs used in restore, but `DependencyGraphSpecRequestProvider.Create(…)` [uses](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/RequestFactory/DependencyGraphSpecRequestProvider.cs#L133) this list to load the `ISettings` object again and read more information from it.

There should be no need to load `ISettings` more than one time. The top-most layer that loads `ISettings` should be able to pass down any information needed to the restore code path. Also, the list of config file paths should not be used to reload `ISettings`.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/commit/a725678ad3cf86236f91c5806a00a0d94179b602
