### ISSUE TITLE
licenses UI experience

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7467]
- [x] seems like too much whitespace in the expression
![image](https://user-images.githubusercontent.com/16904420/47932278-75549580-de8e-11e8-8ebc-ca0261bd5588.png)

- [x] it is better for the license acceptance window. There seems to be one extra space between MIT and OR
![image](https://user-images.githubusercontent.com/16904420/47932372-b056c900-de8e-11e8-9dde-f55f66873a53.png)

- [x] make the weight of the package id on the right same as that of the text on the left to which it is alligned to

![image](https://user-images.githubusercontent.com/16904420/47933866-f6159080-de92-11e8-9378-2bc20100b649.png)

- [ ] need a close button at the bottom center when you view license from package details. 

![image](https://user-images.githubusercontent.com/16904420/47932823-f3656c00-de8f-11e8-8770-b93558dafcb4.png)

- [x] Also can we make the above window apprear in the center of the screen

- [x] show the URL on hover for "view license" and license expressions 

cc: @nkolev92

**Comment by nkolev92** [comment]
The extra space is more a function of WPF than an extra space. 

I will see what I can do about it.

**Comment by nkolev92** [comment]
The only thing not added for 15.9 is the close button in the View License window.

**Comment by nkolev92** [comment]
Marking it as 5.0 since there's 1 item that was not completed.

**Comment by nkolev92** [comment]
@karann-msft 
Do you still think we need a close button?

**Comment by nkolev92** [comment]
Closing this as stale. 
We've heard no feedback on this otherwise. 
There already exists a way to close this.
