### ISSUE TITLE
Manage Packages for Solution: add project NuGet page link to package details

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7470]
<p>The Manage Packages for Solution tool displays details for a given package in the bottom right of the window, which includes links to the license for a project as well as a link to report abuse (example attached).</p><p><p>It would be nice if the package details could also include a link to the package's main page on the NuGet site.</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/43865-oracle-manageddataaccess-package.png"> Image:43865-oracle-manageddataaccess-package.png</a></p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/355394/manage-packages-for-solution-add-project-nuget-pag.html
VSTS ticketId: 703643_
_These are the original issue comments:_

Fiona Niu[MSFT] on 10/12/2018, 01:46 AM (21 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about two weeks on our next steps. </p>

**Comment by joelverhagen** [comment]
This is a great idea, and has been requested before here: https://github.com/NuGet/Home/issues/5299.

Feel free to ":+1:" that issue so we know people are interested in it.
