### ISSUE TITLE
error to install package to projectK WebAPI project with just api.nuget.org enabled

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#748]
Note: if check on package source nuget.org on manager settings, cannot repro the issue

repro steps: 
1. create ProjectK WebAPI project
2. wait the package restore complete
3. install TestPackage.OnlyDNXCore and EntityFramework

Expected results: install correctly, 
      Reference from Solution Explorer include the packages, 
      the package folder exist under path C:\Users\fwtlaba\.dnx\packages\EntityFramework\7.0.0-beta4 
Actual results: error to install packages
      Reference from Solution Explorer don't include the packages,
      the package folder don't exist under path C:\Users\fwtlaba\.dnx\packages\EntityFramework\7.0.0-beta4 

![refer1](https://cloud.githubusercontent.com/assets/11768961/8053185/b91557ba-0ec0-11e5-885d-cb9420a7e42b.png)
![refer2](https://cloud.githubusercontent.com/assets/11768961/8053184/b911395a-0ec0-11e5-8471-be5f8146be26.png)

**Comment by anurse** [comment]
I'll do some initial investigation on this and see if this is a DNX issue or a NuGet issue

**Comment by ChengTian** [comment]
K project system (or more specifically, `dnu restore`) ignores v3 feeds. So if you only have v3 feeds in your NuGet config, it's like you have no feed.

**Comment by anurse** [comment]
Right! I should have remembered that. We are going to be supporting v3 feeds but do not support them currently.

**Comment by yishaigalatzer** [comment]
This was by design from DNU side. They are going to fix it, but there is no NuGet action on this
