### ISSUE TITLE
get dotnet cli version from build/config.props in bash scripts

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7485]
`build.sh` and `scripts/funcTests/runFuncTests.sh` have hardcoded branches when running dotnet-install.sh to install the dotnet cli. It shouldn't be too difficult to use grep and maybe sed to get the branch from `build/config.props`, so it's always in sync with the powershell scripts.

**Comment by PatoBeltran** [comment]
This was solved as part of https://github.com/NuGet/NuGet.Client/pull/2118
