### ISSUE TITLE
[Test Failure][Client Policies] Unexpected error show when installing with trusted signers and package that will produce any warning on accept mode

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7488]
## Details about Problem
NuGet version: NuGet Client Release-4.9.0-rtm\4.9.0.5661
VS Version: D15.9\28306.50
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps 
1. Create a new test certificate:  `.\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority (certificate fingerprint="AAAAA")`
2. Sign a package:  `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>`
3. Create a project, add required mode in nuget.config file with trusted signers list:
```
  <config>
     <add key="signatureValidationMode" value="require" />
  </config>
  <trustedSigners>
     <author name="JamieZhang">       
         <certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" />
     </author>
  </trustedSigners>
```
4. Reload the solution, update the package source to the above package path (step2), install the package into the project in PM UI and CLI (cd to the project path and "nuget install PackageName")

## Expected
There is an error NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired, and the package was not installed in the project..

## Actual
Unexpected error NU3034 show as below:
```
NU3034: Package 'JamiePackage006 1.0.0' from source 'C:\Users\v-luzh\source\repos\Package006\Package006': This package is signed but not by a trusted signer.
```
## Note
It can repro on both PM UI and CLI.

**Comment by v-luzh** [comment]
Update the info since there are typing issue in GitHub. (Omit the “<>”. Can't edit and attach anything too)
## Detailed repro steps
1. Create a new test certificate:  .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority (certificate fingerprint="AAAAA")
2. Sign a package:  NuGet.exe sign “PackageFilePath” -CertificatePath “PfxFilePath”
3. Create a project, add required mode in nuget.config file with trusted signers list:
  config
     add key="signatureValidationMode" value="require" /
  /config
  trustedSigners
     author name="JamieZhang"       
         certificate fingerprint="AAAAA" hashAlgorithm="SHA256" allowUntrustedRoot="false" /
     /author
  /trustedSigners
4. Reload the solution, update the package source to the above package path (step2), install the package into the project in PM UI and CLI (cd to the project path and "nuget install PackageName")

## Expected:
There is an error NU3027: The signature should be timestamped to enable long-term signature validity after the certificate has expired, and the package was not installed in the project..

## Actual:
Unexpected error NU3034 show as below:
NU3034: Package 'JamiePackage006 1.0.0' from source 'C:\Users\v-luzh\source\repos\Package006\Package006': This package is signed but not by a trusted signer.

**Comment by PatoBeltran** [comment]
Closing as the test has been fixed and this is not reproing.
