### ISSUE TITLE
Visual studio 2017 version 15.8.9 freeze on nuget installation

### ISSUE THREAD

**Issue by AlenToma** [NuGet/Home#7490]
Hi, i started working with xamarin.forms and created a .netstandard xamarin.forms project.
after the last update i cant install any nuget package to my android project, with command or the gui.

I read this problem exited in the old update but now i see this problem with the latest version of vs.

is there any solution i can try ?

With Regards 
Alen Toma

**Comment by nkolev92** [comment]
@AlenToma 

Do you have a repro solution/project for us?

Can you provide a heapdump for us? Please make sure you are using the 32-bit task manager when generating the dump. 

Thanks!

**Comment by AlenToma** [comment]
Ok here is a solution `https://mega.nz/#!QhpXESzZ!cb9fCA1wKY0CdLkw9_zQmk9jBg0QfsJyMia_FCEvEjc`
how can i provide heapdump?

**Comment by nkolev92** [comment]
If you are on a 64-bit machine, run the 32 bit task manager from c:\windows\syswow64, go to details, find devenv.exe, right click on it and click CreateDumpFile. 

It would speed up things if you can provide the CLR and SOS dlls from C:\windows\microsoft.net\Framework\v4.0.30319

//cc @jainaashish

**Comment by AlenToma** [comment]
and here is DumpFile 
https://mega.nz/#!V9ggBYoI!Cz1b2pbMFbkQiHZm2ATQSw0WayPiXQtZNRv9t8iE2Yw
and here is the clr and sos dll files
https://mega.nz/#!EgpAnKZQ!ipj1p4Dg2XXF4M_HIiohfj-4DlUbZqtPzImULgAWPQ0

**Comment by AlenToma** [comment]
try to install xamarin.Auth for example to the android project and the vs will freeze

**Comment by AlenToma** [comment]
why is it taking so long to get help ? this has not been assigned yett ?

**Comment by PatoBeltran** [comment]
Hey @AlenToma, thanks for providing this data... I was looking at this and it seems like Xamarin is blocking the UI thread while waiting for a background thread to finish. This causes a deadlock and is the reason why you see this hang:

```
WindowsBase.dll!System.Windows.Threading.DispatcherSynchronizationContext.Wait(System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout)         Unknown
mscorlib.dll!System.Threading.SynchronizationContext.InvokeWaitMethodHelper(System.Threading.SynchronizationContext syncContext, System.IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) Unknown
[Native to Managed Transition] 
[Managed to Native Transition]  
mscorlib.dll!System.Threading.WaitHandle.WaitAny(System.Threading.WaitHandle[] waitHandles, int millisecondsTimeout, bool exitContext) Unknown
mscorlib.dll!System.Threading.WaitHandle.WaitAny(System.Threading.WaitHandle[] waitHandles, System.TimeSpan timeout, bool exitContext)      Unknown
Xamarin.Android.Build.Tasks.dll!Xamarin.Android.Tasks.AsyncTask.WaitForCompletion() Unknown
Xamarin.Android.Build.Tasks.dll!Xamarin.Android.Tasks.AsyncTask.Execute()       Unknown
Xamarin.Android.Build.Tasks.dll!Xamarin.Android.Tasks.Aapt.Execute()  Unknown
Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()                Unknown
Microsoft.Build.dll!Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask)            Unknown
```

I'm following up with the Xamarin team so they can take a look at this issue and engage properly, I will keep you posted. Fell free to follow up with them in the mean time.

**Comment by AlenToma** [comment]
thx man i opend a thread in 
https://forums.xamarin.com/discussion/144225/visual-studio-2017-version-15-8-9-freeze-on-nuget-installation/p1?new=1

I dont know if its a right place to ask. 
anyway thx for the help

**Comment by PatoBeltran** [comment]
No problem! I will close this issue in favor of the one you created in the Xamarin forum. I will update this threat if I get any update from the Xamarin team.

**Comment by AlenToma** [comment]
dont like the fix but i fixed the problem by unstalling visual studio
