### ISSUE TITLE
Need to define TFM mappings for .NETCore3

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#7491]
.NETCore 3 can load .NETFX assemblies via .NET Compat Shims. 

We expect that users will find very helpful to add a p2p ref to .NET Framework projects, but there are some caveats here:
- If the project uses `Packages.config` the dependencies are not copied to the .NETCore project
- If the project uses `PackageRef` the build fails with 

```
Error	NU1201	Project ClassLibrary1 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0) / win-x64. Project ClassLibrary1 supports: net472 (.NETFramework,Version=v4.7.2)	ConsoleApp7	C:\Users\rmpablos\source\repos\CoreDeps\ConsoleApp7\ConsoleApp7.csproj	1	
```

The workaround is using 
```xml 
<AssetTargetFallback />
```

We need to define the .NET Core 3 mappings to improve the compatibility with NETFX projects.

/cc: @jainaashish  @nguerrera @ericstj

**Comment by jainaashish** [comment]
Thinking little more about this, ideally SDK projects needs to update their `AssetTargetFallback` from `net46` to more compatible netfx version for .netcore3. That should help resolve this.

@livarcocc

**Comment by livarcocc** [comment]
cc @terrajobst @dsplaisted

The change is minimal on our side, but I want to make sure it is right.

**Comment by dsplaisted** [comment]
Yes, I recall the plan being to update the AssetTargetFallback in the SDK to use a higher version of .NET Framework.

**Comment by nguerrera** [comment]
There's another issue tracking this. Will link when I get to the office. There's concern around picking different assets in existing, successfully building projects. And a proposal to address that, but we have to check perf or other consequences.

**Comment by nguerrera** [comment]
Found it: 
https://github.com/dotnet/sdk/issues/2425

**Comment by jainaashish** [comment]
thanks guys. This will get tracked as dotnet/sdk#2425
