### ISSUE TITLE
dotnet list package outdated should not list RIDs

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7497]
Using the current dotnet CLI 3.0 preview, `dotnet list package --outdated --include-transitive` lists each TFM twice, the second time with some extra transitive runtime packages. It should skip RIDs and only output each TFM once, as it does with the dotnet CLI 2.2.

**Comment by v-luzh** [comment]
The issue doesn't repro on Dotnet SDK: 3.0.100-preview-010137 & Dotnet SDK: 3.0.100-preview-010140.

**Comment by dominoFire** [comment]
Looks like a duplicated issue of #7607

**Comment by rrelyea** [comment]
@dominoFire  - yes, please use "closedas:*" labels when we close for a reason other than it was fixed. that way, release notes and people will know if we fixed it or not.
