### ISSUE TITLE
Unwanted files in a Nuget Package

### ISSUE THREAD

**Issue by ghigad** [NuGet/Home#750]
Hi,

I'm creating a library that will be distributed as a Nuget package.  My project is a C# Class Library.  The project contains C# code, JavaScript files and CSS files.  The package is created from my .csproj file.

Ultimately, I want the CSS files to be placed in the content/Content directory and the JavaScript files to be placed in the content/Scripts directory.  Also, since my package has a few dependencies on other packages (jquery, bootstrap, angularjs, etc.), I don't want to include the Content and the Scripts directories of my project since I don't want to deploy the files I don't own:  I want to use package dependencies for that.

I tried quite a few scenarios, but I always get unwanted files in my resulting .nupkg file.

In my project, I have a Nuget directory in which I place the files I want in my .nupkg file.  

Here is a sample of my nuspec file:

    <?xml version="1.0"?>
    <package >
        <metadata>
            <id>$id$</id>
            <version>$version$</version>
            <title>$title$</title>
            <authors>$author$</authors>
            <owners>$author$</owners>
            <description>$description$</description>
            <dependencies>
            </dependencies>
        </metadata>
        <files>
            <file src="Nuget\**\*.*" target=""/>
        </files>
    </package>

I build my package using this command:

    Nuget.exe pack TestLibrary.csproj -IncludeReferencedProjects -OutputDirectory <path>

If I add a .css or a .js file to the Nuget\content directory (for example JavaScript1.js), I get the following structure in my .nupkg file:

    content
        Nuget
            Content
                JavaScript1.js
        JavaScript1.js
    lib
        net451
            TestLibrary.dll

I get the same structure with a .css file.  The file is included twice, and the Content/Nuget directory is clearly not wanted.

Il tried moving the file to the root of my project and using the following .nuspec.

    <?xml version="1.0"?>
    <package >
        <metadata>
            <id>$id$</id>
            <version>$version$</version>
            <title>$title$</title>
            <authors>$author$</authors>
            <owners>$author$</owners>
            <description>$description$</description>
            <dependencies>
            </dependencies>
        </metadata>
        <files>
            <file src="Nuget\**\*.*" target=""/>
            <file src="**\*.js" target="content"/>
        </files>
    </package>

Here's the resulting directory structure:

    content
        JavaScript1.js
    lib
        net451
            TestLibrary.dll

This works, but I get warnings complaining that my files have not been added to the package since they were already added (sorry, I don't have the exact english message since my machine is setup in frech...).

Looks like an "undocumented" behavior of Nuget...  It adds some files from the source project to the target package file.  (It'd be nice if this was included in the docs, stating exactly what files are processed by Nuget that way...)

So, my files are at the right place in my package, so no problem here...

Now, to move everything in my Scripts directory, here's my nuspec.  I removed the <file src="Nuget\**\*.*"> element since it was no longer needed...

    <?xml version="1.0"?>
    <package >
        <metadata>
            <id>$id$</id>
            <version>$version$</version>
            <title>$title$</title>
            <authors>$author$</authors>
            <owners>$author$</owners>
            <description>$description$</description>
            <dependencies>
            </dependencies>
        </metadata>
        <files>
            <file src="**\*.js" target="content/Scripts"/>
        </files>
    </package>

Note:  I don't want to place my project's files in the Scripts directory in my project in order to avoid conflicts with third parties.  That's why I retargeted the files with a file element and the target attribute.  This will allow me to use the exclude attribute to remove my project's Script directory from the Nuget package, effectively remove the files I get from Third Parties.

Now here's the new package structure:

    content
        Scripts
            JavaScript1.js
        JavaScript1.js
    lib
        net451
            TestLibrary.dll

The file got included twice!

And, if I add the JQuery package to my project and the exclude attribute to my file, "sometimes" a few JavaScript files from the third party packages also get included.  For instance, jquery-2.1.4.intellisense.js is sometimes added to the package.  I could not reproduce the behavior in my test project, but I've seen this in one of my projects.

As a reference, here is the final nuspec for all the file types I want to provide in my project.

    <?xml version="1.0"?>
    <package >
        <metadata>
            <id>$id$</id>
            <version>$version$</version>
            <title>$title$</title>
            <authors>$author$</authors>
            <owners>$author$</owners>
            <description>$description$</description>
            <dependencies>
            </dependencies>
        </metadata>
        <files>
            <file src="**\*.js" target="content\Scripts" exclude="Scripts\**\*.js"/>
            <file src="**\*.js.map" target="content\Scripts" exclude="Scripts\**\*.js.map"/>
            <file src="**\*.d.ts" target="content\Scripts\typings" exclude="Scripts\**\*.d.ts"/>
            <file src="**\*.css" target="content\Content" exclude="Content\**\*.css"/>
        </files>
    </package>

So...  How can I create a Nuget package with the file structure I'm expecting?  Clearly I don't want my files included twice!

Am I doing anything wrong??

Thank you for your help!

**Comment by yishaigalatzer** [comment]
So two thoughts here

1. I would probably build two separate packages depending on one another. One just having the dll and one just having the content files built in a completely separate project.
2. Consider that we don't think content files in NuGet is the right way forward, starting from ASP.NET 5 content files are no longer supported in nuget packages, and the recommendation is to use bower instead.
