### ISSUE TITLE
Release version 4.8.1 of nuget packages

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7504]
Since 4.8.1 is now finally recommended, packages on nuget.org should be updated to 4.8.1:

- https://www.nuget.org/packages/NuGet.CommandLine/
- https://www.nuget.org/packages/NuGet.Frameworks/
- https://www.nuget.org/packages/NuGet.Common/
- etc

**Comment by dominoFire** [comment]
Thanks for pointing this out, @pascalberger . In order to keep the issues more manageable, I'll close this issue and track the conversation on the previous issue #7262
