### ISSUE TITLE
run nuget.exe without mono

### ISSUE THREAD

**Issue by ctaggart** [NuGet/Home#7507]
The documentation says that mono is required. 😢 
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference

Can you make it work without mono? It would be nice if this worked:
```
docker run --rm -it microsoft/dotnet:2.1-sdk
curl https://dist.nuget.org/win-x86-commandline/v4.8.1/nuget.exe -sSfO
dotnet nuget.exe
```

But it results in this error:
```
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/'.
Failed to run as a self-contained app. If this should be a framework-dependent app, add the /nuget.runtimeconfig.json file specifying the appropriate framework.
```

It would be even better if it was a dotnet tool:
```
docker run --rm -it microsoft/dotnet:2.1-sdk
dotnet tool install NuGet.CommandLine -g
nuget
```

There are several occasions where I want to use the nuget.exe client. The current need is that it appears to be a requirement for Black Duck scans.

**Comment by devlead** [comment]
@ctaggart agree 👍  a better .NET CLI NuGet story would be really useful.

With the .NET CLI built-in `dotnet nuget` command you get delete & push capabilities, if that could be extended with more commands
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore21

Personally done a few workarounds for installing packages in a pure .NET Core environment, but there's quite a few other scenarios nuget.exe supports.

**Comment by PatoBeltran** [comment]
Hey @ctaggart and @devlead, thanks for opening the issue. 

We are aware that nuget.exe has some features that dotnet cli doesn't, however we keep striving to have dotnet cli cover all of our xplat scenarios. 

We are continuously working in improving our xplat experience. If you have specific pain points or feature requests for our current xplat toolset I would appreciate if you comment and upvote existing issues or open new issues with those specific requests. This way we can prioritize the work needed to improve our xplat story.

**Comment by nkolev92** [comment]
Closing this per @PatoBeltran's reply. 

If there are any feature gaps in dotnet.exe's NuGet functionalities please file issues on that.
