### ISSUE TITLE
NuGet 5.0 assemblies to require .NET 4.7.2 (via TFM change)

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7510]
All of VS is moving to net472 for dev16. 
Our libraries should do the same. 

//cc @NuGet/nuget-client @rrelyea @jainaashish

**Comment by jainaashish** [comment]
Somebody has to pick it ASAP. this blocks launching experimental instance for dev branch. So we'd need to explicitly build with MSBuild 15.0 and install the private vsix to test any new code.

**Comment by nkolev92** [comment]
@jainaashish 
I'll jump on it today/tomorrow.
