### ISSUE TITLE
NuGet plugin credential providers - hide the process window

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#7511]
When using NuGet plugin credential providers, the plugin process is started and displayed ([here](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.Protocol/Plugins/PluginFactory.cs#L149)).

Is there a reason for displaying the process window? Could the SDK be updated to set `WindowStyle = ProcessWindowStyle.Hidden` when starting the process?

**Comment by nkolev92** [comment]
@dtivel Do you any have issue with the proposed change?

**Comment by dtivel** [comment]
No
