### ISSUE TITLE
VS/dotnet.exe/nuget.exe/msbuild.exe restore doesn't use credentials when source name contains a whitespace

### ISSUE THREAD

**Issue by DoCode** [NuGet/Home#7517]
## Details

NuGet version: 4.9.0.5672

OS version: win10 v1809

Worked before? If so, with which NuGet version: 4.8.1

## Detailed repro steps so we can see the same problem

1. `nuget.exe list xxx` prompt for credentials, but was configured in `nuget.config`

2. `nuget.exe sources` shows feed with a name that contains a whitespace

3. Update credentials with `nuget sources update -name 'sample feed ' -username xxx -password xxx` prompt  
`The ' ' character, hexadecimal value 0x20, cannot be included in a name.`

4. Use the same feed with no whitespace in name works like <4.9.0

**Comment by PatoBeltran** [comment]
Hey @DoCode, thanks for opening the issue... We did a bunch of work around nuget.config in 4.9, so this might be a think we missed. I will look into reproing it and looking for the reason for it. In the meantime a quick solution could be to avoid using spaces in your sources names, that should fix your issue.
