### ISSUE TITLE
--interactive support for dotnet nuget push

### ISSUE THREAD

**Issue by thenderson21** [NuGet/Home#7519]
When I try to push a Nuget to Azure Artifacts using `--interactive` parameter it gives the following error on the Latest Mac:

```
dotnet nuget push ../Nugets/Austco.0.1.0.1811141734-pre.nupkg -s https://pkgs.dev.azure.com/Austco/_packaging/Austco/nuget/v3/index.json --interactive
Specify --help for a list of available options and commands.
error: Missing value for option 'interactive'
```

but `--interactive` shows up as a valid parameter in the help.

```
dotnet nuget push --help

Usage: dotnet nuget push [arguments] [options]

Arguments:
  [root]  Specify the path to the package and your API key to push the package to the server.

Options:
  -h|--help                      Show help information
  --force-english-output         Forces the application to run using an invariant, English-based culture.
  -s|--source <source>           Specifies the server URL
  -ss|--symbol-source <source>   Specifies the symbol server URL. If not specified, nuget.smbsrc.net is used when pushing to nuget.org.
  -t|--timeout <timeout>         Specifies the timeout for pushing to a server in seconds. Defaults to 300 seconds (5 minutes).
  -k|--api-key <apiKey>          The API key for the server.
  -sk|--symbol-api-key <apiKey>  The API key for the symbol server.
  -d|--disable-buffering         Disable buffering when pushing to an HTTP(S) server to decrease memory usage.
  -n|--no-symbols                If a symbols package exists, it will not be pushed to a symbols server.
  --no-service-endpoint          --no-service-endpoint does not append "api/v2/packages" to the source URL.
  --interactive                  Allow the command to block and require manual action for operations like authentication.
```

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

dotnet nuget

NuGet version (x.x.x.xxx):

dotnet --version  2.1.500 and 2.2 preview

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

MacOS 10.14.1

Worked before? If so, with which NuGet version:
nope

## Detailed repro steps so we can see the same problem

1.  `dotnet nuget push .XXXX.nupkg -s https://pkgs.dev.azure.com/XXXX/_packaging/XXXX/nuget/v3/index.json --interactive`

### Verbose Logs

NA

### Sample Project

NA

**Comment by nkolev92** [comment]
Thanks for creating this. It is a bug.

The arguments are not being forwarded. 
https://github.com/dotnet/cli/blob/release/2.1.5xx/src/dotnet/commands/dotnet-nuget/NuGetCommandParser.cs

//cc @livarcocc @rrelyea 

We should discuss the timeline for this fix.

**Comment by rrelyea** [comment]
I'd love to see this make 2.1.50x -- if we fix ~next week, would that be 2.1.501 @@livarocc ?

**Comment by livarcocc** [comment]
Do you need a train made for this or are you ok jumping on whatever train we have next? 2.1.501 seems like it but we will likely only ship in January now.

cc @leecow

**Comment by rrelyea** [comment]
nuget bug - fixed.
cli-sdk insertion - not yet.
docs - not yet.

**Comment by nkolev92** [comment]
Merged to CLI https://github.com/dotnet/cli/pull/10380.

It will ship in 2.1.600 of the SDK
