### ISSUE TITLE
License element documentation

### ISSUE THREAD

**Issue by JamesNK** [NuGet/Home#7521]
> warning NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.

Where is the documentation for the license element? I couldn't find any on the [nuspec reference](https://docs.microsoft.com/en-us/nuget/reference/nuspec).

**Comment by karann-msft** [comment]
here you go - https://docs.microsoft.com/en-us/nuget/reference/nuspec#license

**Comment by JamesNK** [comment]
Thanks!

btw you should audit your examples for licenseUrl and replace them with the new element, e.g. https://docs.microsoft.com/en-us/nuget/reference/nuspec#example-nuspec-files

**Comment by karann-msft** [comment]
Thanks James. I have PRd the fix for that example too. Feel free to close the issue.

**Comment by andremarcondesteixeira** [comment]
where can I find the equivalent .csproj tags for this?
I hate the fact the tag names are not equal between those files

**Comment by karann-msft** [comment]
@andremarcondesteixeira https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file

**Comment by itaibh** [comment]
I don't see a way to add custom URL for license, it's deprecated. Why is that? What other options do I have to send the user to our custom license?

**Comment by itaibh** [comment]
@karann-msft ^^
