### ISSUE TITLE
[Doc] Project-level NuGet.Config setting method should not be available for “Configuring NuGet behavior”

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7522]
## Detailed repro steps 
1. Open the doc “[Configuring NuGet behavior](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#changing-config-settings)”.
2. Check the content of this page.
## Expected
Project-level NuGet.Config setting should not be available for “Configuring NuGet behavior” since VS doesn't support it.
## Actual
Project-level NuGet.Config setting method still show in this doc as below screenshot. 
![confignuget](https://user-images.githubusercontent.com/20632625/48684671-b61e0f80-ebed-11e8-843d-1ffeafaf9bbe.png)

**Comment by nkolev92** [comment]
Small correction: VS never supported project-level configs. 
I have edited the original issue.

Related: https://github.com/NuGet/Home/issues/6746
//cc @rrelyea

**Comment by v-luzh** [comment]
It is fixed on VS Main\35221.199 + NuGet Client Dev\6.12.0.81. I will close this bug soon.
