### ISSUE TITLE
Improve Edit and Continue feature for NuGet package debugging experience

### ISSUE THREAD

**Issue by softboy99** [NuGet/Home#7526]
Currently, we cannot do modify any code when debugging, the ide said the module not loaded, but it really loaded with debugging symbols in fact. So, we modify one line /several lines of code and then publish the package and rerunning and modify the code and publish again and again. The Edit and Continue feature  cannot be used.

**Comment by nkolev92** [comment]
I'm not sure I understand your concern. 
Edit and continue only works when you are in debug mode and when you own the source code directly.
Since you own the product, you can setup your experience as you please. 

Furthermore it's a good practice to only pack release assemblies.

**Comment by nkolev92** [comment]
Closing as stale. 

Please open a new issue as needed.
