### ISSUE TITLE
Can't install Selenium.WebDriver

### ISSUE THREAD

**Issue by tomaz77** [NuGet/Home#7528]
I am trying to install Selenium.Webdriver in Visual Studio Professional 2017. I am having .NET 4.0.

The installation always fails with same reason. I have cleared local cache, but no succes. Error stays the same.

Attempting to gather dependency information for package 'Selenium.WebDriver.3.13.0' with respect to project 'Selenium', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 614,62 ms
Attempting to resolve dependencies for package 'Selenium.WebDriver.3.13.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Selenium.WebDriver.3.13.0'
Resolved actions to install package 'Selenium.WebDriver.3.13.0'
Retrieving package 'Selenium.WebDriver 3.13.0' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/selenium.webdriver/3.13.0/selenium.webdriver.3.13.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/selenium.webdriver/3.13.0/selenium.webdriver.3.13.0.nupkg 143ms
Installing Selenium.WebDriver 3.13.0.
Install failed. Rolling back...
Package 'Selenium.WebDriver.3.13.0' does not exist in project 'Selenium'
Package 'Selenium.WebDriver.3.13.0' does not exist in folder 'D:\projekti\Razvoj\Selenium\packages'
Executing nuget actions took 1,03 min
NU3008: The package integrity check failed.
Time Elapsed: 00:01:02.3902429
========== Finished ==========

Thank you for the help.

**Comment by nkolev92** [comment]
@tomaz77 I was unable to repro the simple case (with nuget.org). 

Can you please try the following:

Create a project file from this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="3.13.0"/>
  </ItemGroup>

</Project>
```

Download https://dist.nuget.org/win-x86-commandline/v4.9.0-rc1/nuget.exe and run
nuget.exe restore -verbosity detailed, and upload the logs here.

**Comment by tomaz77** [comment]
Hi,

this is my new csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="3.13.0"/>
  </ItemGroup>
</Project>
```
And after running "nuget.exe restore -verbosity detailed" I get this:
NuGet Version: 4.8.1.5435
Restoring NuGet packages for solution D:\projekti\Razvoj\Selenium_Console\Selenium_Console.sln.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe "C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\c2ahuck4.tbv.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\bihb1xer.reb.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="D:\projekti\Razvoj\Selenium_Console\nuget.exe" /p:RestoreSolutionDirectory="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionDir="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionName="Selenium_Console" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"
D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj(7,52): error MSB4066: The attribute "Version" in element <PackageReference> is unrecognized.
D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj : warning NU1503: Skipping restore for project 'D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\c2ahuck4.tbv.nugetinputs.targets]
C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\bihb1xer.reb.nugetrestore.targets(144,5): warning : Unable to find a project to restore! [C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\c2ahuck4.tbv.nugetinputs.targets]

Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.

**Comment by nkolev92** [comment]
Why do you have 
```xml
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
``` 
? It's gonna get included through the SDK.

**Comment by tomaz77** [comment]
I have removed this line, but the error stays the same

NuGet Version: 4.8.1.5435
Restoring NuGet packages for solution D:\projekti\Razvoj\Selenium_Console\Selenium_Console.sln.
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin\amd64'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild.exe "C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\1nju1gd3.ibi.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\bp1rmit5.t30.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="D:\projekti\Razvoj\Selenium_Console\nuget.exe" /p:RestoreSolutionDirectory="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionDir="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionName="Selenium_Console" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"
D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj(6,52): error MSB4066: The attribute "Version" in element <PackageReference> is unrecognized.
D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj : warning NU1503: Skipping restore for project 'D:\projekti\Razvoj\Selenium_Console\Selenium_Console\Selenium_Console.csproj'. The project file may be invalid or missing targets required for restore. [C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\1nju1gd3.ibi.nugetinputs.targets]
C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\bp1rmit5.t30.nugetrestore.targets(144,5): warning : Unable to find a project to restore! [C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\1nju1gd3.ibi.nugetinputs.targets]

Nothing to do. None of the projects in this solution specify any packages for NuGet to restore.

**Comment by nkolev92** [comment]
It seems like NuGet.exe is discover MSBuild 14.0 which doesn't work with PackageReference. 

Can you try force the msbuild version to 15.x?

You can do that by passing `-MSBuildVersion 15.x` to restore where x, is the update of Visual Studio you have.

**Comment by tomaz77** [comment]
Doesn't work either, Nugget is not able find the proper MSBuild version. I'm using VS 2017, which has MSBuild in a different folder. I have tryed also with -MSBuildPath but nothing seems to happen. 

_D:\Selenium_Console>nuget restore selenium_console.sln -verbosity detailed -MSBuildPath C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin
restore: invalid arguments.
usage: NuGet restore [<solution> | <packages.config file> | <Microsoft Build project>] [options]

Restores NuGet packages.

     If a solution is specified, this command restores NuGet packages that are installed in the solution and in project
     s contained in the solution. Otherwise, the command restores packages listed in the specified packages.config file
     , Microsoft Build project, or project.json file.

options:

 -RequireConsent                                    Checks if package restore consent is granted before installing a pa
                                                    ckage.
 -Project2ProjectTimeOut                            Timeout in seconds for resolving project to project references.
 -PackagesDirectory              (OutputDirectory)  Specifies the packages folder.
 -SolutionDirectory                                 Specifies the solution directory. Not valid when restoring packages
                                                    for a solution.
 -MSBuildVersion                                    Specifies the version of MSBuild to be used with this command. Supp
                                                    orted values are 4, 12, 14. By default the MSBuild in your path is
                                                    picked, otherwise it defaults to the highest installed version of M
                                                    SBuild.
 -MSBuildPath                                       Specifies the path of MSBuild to be used with this command. This co
                                                    mmand will takes precedence over MSbuildVersion, nuget will always
                                                    pick MSbuild from this specified path.
 -Recursive                                         Restore all referenced projects for UWP and NETCore projects. This
                                                    does not include packages.config projects.
 -Force                                             Forces all dependencies to be resolved even if the last restore was
                                                    successful. This is equivalent to deleting project.assets.json. (Do
                                                    es not apply to packages.config)
 -Source +                                          A list of packages sources to use for this command.
 -FallbackSource +                                  A list of package sources to use as fallbacks for this command.
 -NoCache                                           Disable using the machine cache as the first package source.
 -DirectDownload                                    Download directly without populating any caches with metadata or bi
                                                    naries.
 -DisableParallelProcessing                         Disable parallel processing of packages for this command.
 -PackageSaveMode                                   Specifies types of files to save after package installation: nuspec
                                                    , nupkg, nuspec;nupkg.
 -Help                           (?)                help
 -Verbosity                                         Display this amount of details in the output: normal, quiet, detail
                                                    ed.
 -NonInteractive                                    Do not prompt for user input or confirmations.
 -ConfigFile                                        The NuGet configuration file. If not specified, file %AppData%\NuGe
                                                    t\NuGet.config is used as configuration file.
 -ForceEnglishOutput                                Forces the application to run using an invariant, English-based cul
                                                    ture.

examples:

nuget restore MySolution.sln

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference__

**Comment by nkolev92** [comment]
Can you try running it from a 2017 developer command prompt? 

What I am trying to do here is where the faulty package is coming from. 

In one of your restores you obviously have a package from a source that's invalid. 
If we can figure out the source we can continue with the investigation into how/why that package is tampered. 

If you are struggling with the SDK based project try installing into a .NET Framework with PackageReference as project management style.

**Comment by tomaz77** [comment]
Have done it and bellow is the result. This is done through Developer Command Prompt for VS 2017. My packages.config looks like:
`<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver" Version="3.13.0"/>
  </ItemGroup>
</Project>`

Result is:
D:\projekti\Razvoj\Selenium_Console>nuget restore -verbosity detailed -MSBuildPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64"
Using Msbuild from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64'.
NuGet Version: 4.8.1.5435
Restoring NuGet packages for solution D:\projekti\Razvoj\Selenium_Console\Selenium_Console.sln.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64\msbuild.exe "C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\krxntqyc.0ye.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\tomazb\AppData\Local\Temp\NuGetScratch\okw21s0b.f0t.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="D:\projekti\Razvoj\Selenium_Console\nuget.exe" /p:RestoreSolutionDirectory="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionDir="D:\projekti\Razvoj\Selenium_Console\\" /p:SolutionName="Selenium_Console" /p:RestoreBuildInParallel="False" /p:RestoreUseSkipNonexistentTargets="False"

All packages listed in packages.config are already installed.

**Comment by nkolev92** [comment]
> My packages.config looks like:

Did you mean your csproj? 

The sentence "All packages listed in packages.config are already installed." is weird. 
Is the project part of the solution? 
All projects should be restore individually.

**Comment by erickephart** [comment]
I am having a similar issue, also specifically with WebDriver.  I can install non-Selenium packages fine.  

It has to be something local, as everything works as expected from another laptop.  Any ideas?

Also ran this and still no luck:

PS > .\nuget locals all -clear
Clearing NuGet HTTP cache: C:\Users\Ekephart\AppData\Local\NuGet\v3-cache
Clearing NuGet global packages folder: C:\Users\Ekephart\.nuget\packages\
Clearing NuGet Temp cache: C:\Users\Ekephart\AppData\Local\Temp\NuGetScratch
Clearing NuGet plugins cache: C:\Users\Ekephart\AppData\Local\NuGet\plugins-cache
Local resources cleared.

Here is the output:

PM> Install-Package Selenium.WebDriver -Version 3.12.1 -verbose

Attempting to gather dependency information for package 'Selenium.WebDriver.3.12.1' with respect to project 'ConsoleApp3', targeting '.NETFramework,Version=v4.6.1'
Missing C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\selenium.webdriver\3.12.1\selenium.webdriver.3.12.1.nupkg
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/selenium.webdriver/index.json
  GET https://ambitenergy.pkgs.visualstudio.com/_packaging/ef0fa19b-b8d0-404d-8898-c0644b361f61/nuget/v3/registrations2-semver2/selenium.webdriver/index.json
  OK https://ambitenergy.pkgs.visualstudio.com/_packaging/ef0fa19b-b8d0-404d-8898-c0644b361f61/nuget/v3/registrations2-semver2/selenium.webdriver/index.json 1357ms
Total number of results gathered : 4
Gathering dependency information took 1.96 sec
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	339.72 ms
https://ambitenergy.pkgs.visualstudio.com/_packaging/default/nuget/v3/index.json	-	1.74 sec
C:\Users\Ekephart\Downloads	-	1.09 sec
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\	-	19.82 ms
Attempting to resolve dependencies for package 'Selenium.WebDriver.3.12.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Selenium.WebDriver.3.12.1'
Resolved actions to install package 'Selenium.WebDriver.3.12.1'
Retrieving package 'Selenium.WebDriver 3.12.1' from 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/selenium.webdriver/3.12.1/selenium.webdriver.3.12.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/selenium.webdriver/3.12.1/selenium.webdriver.3.12.1.nupkg 173ms
Acquiring lock for the installation of Selenium.WebDriver 3.12.1
Acquired lock for the installation of Selenium.WebDriver 3.12.1
Installing Selenium.WebDriver 3.12.1.
Install failed. Rolling back...
Package 'Selenium.WebDriver.3.12.1' does not exist in project 'ConsoleApp3'
Package 'Selenium.WebDriver.3.12.1' does not exist in folder 'C:\repos\SeleniumPackageTest\ConsoleApp3\packages'
Executing nuget actions took 3.21 min
Signature Hash Algorithm: SHA256
Install-Package : The package integrity check failed.
At line:1 char:1
+ Install-Package Selenium.WebDriver -Version 3.12.1 -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
NU3008: The package integrity check failed.
Signature type: Repository
Timestamp: 10/15/2018 3:21:59 AM

Verifying timestamp with timestamping service certificate: 
Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
Valid from: 1/1/2017 6:00:00 PM to 4/1/2028 6:59:59 PM

    Subject Name: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
    SHA1 hash: 6FC9EDB5E00AB64151C1CDFCAC74AD2C7B7E3BE4
    SHA256 hash: F3516DDCC8AFC808788BD8B0E840BDA2B5E23C6244252CA3000BB6C87170402A
    Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
    Valid from: 1/11/2016 6:00:00 PM to 1/11/2031 5:59:59 PM

        Subject Name: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
        SHA1 hash: 3679CA35668772304D30A5FB873B0FA77BB70D54
        SHA256 hash: 2399561127A57125DE8CEFEA610DDF2FA078B5C8067F4E828290BFB860E84B3C
        Issued by: CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
        Valid from: 4/1/2008 7:00:00 PM to 12/1/2037 5:59:59 PM


Verifying signature with author certificate: 
Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
Valid from: 4/9/2018 7:00:00 PM to 4/14/2021 7:00:00 AM

    Subject Name: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
    SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6
    SHA256 hash: 51044706BD237B91B89B781337E6D62656C69F0FCFFBE8E43741367948127862
    Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
    Valid from: 10/22/2013 7:00:00 AM to 10/22/2028 7:00:00 AM

        Subject Name: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
        SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43
        SHA256 hash: 3E9099B5015E8F486C00BCEA9D111EE721FABA355A89BCF1DF69561E3DC6325C
        Issued by: CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US
        Valid from: 11/9/2006 6:00:00 PM to 11/9/2031 6:00:00 PM


Time Elapsed: 00:03:15.0311989
PM>

**Comment by usbook** [comment]
@tomaz77 
i have the same matter,do you solved it?thanks

**Comment by nkolev92** [comment]
@tomaz77 Are you still having issues/ 

Can you answer my above question about the project being a part of a solution?

**Comment by tomaz77** [comment]
I decided not to use selenium this way. :(

Thank you for your help.
________________________________________

**Comment by nkolev92** [comment]
Thanks for following up @tomaz77 

Closing this.

**Comment by 2Young4Code** [comment]
Getting same error....

So there's no solution to run Selenium on VS2017?


Dev express team seems to have fixed it so there should be a way...

https://www.devexpress.com/Support/Center/Question/Details/T668052/nu3008-the-package-integrity-check-failed-error-is-thrown-when-installing-devexpress

If you need steps to reproduce, Install VS2017, -> make new ConsoleApplication -> the go to Nuget Packages, -> type selenium select Selenium.WebDriver you will get your error...
