### ISSUE TITLE
[NuGet v3] Manifest Compatibility Check issues in UI

### ISSUE THREAD

**Issue by anurse** [NuGet/Home#753]
The RestoreCommand now manifests Compatibility Check issues in a list as part of the `RestoreResult` object. The VS extension needs to manifest something when the restore fails in order to inform the user. It could be:

1. A single error "NuGet Package Restore failed, see the Output Window for more information"
2. An error for each `CompatibilityIssue` in the various `CompatibilityCheckResults`

/cc @yishaigalatzer @emgarten

**Comment by emgarten** [comment]
The current message displayed if RestoreResult.Sucess is false is: Package restore failed for 'project name'.

https://github.com/NuGet/NuGet.PackageManagement/blob/dev/src/PackageManagement/BuildIntegration/BuildIntegratedRestoreUtility.cs#L83

The build can still continue at this point, does it need to stop msbuild from running?

**Comment by anurse** [comment]
It probably should stop MSBuild if possible. It should at least ensure there is an error in the Error List (not just the Output Window)

**Comment by emgarten** [comment]
On installs from the console or UI an InvalidOperationException is thrown and will be put in the error list. This should cover most scenarios, but if the user has floating versions and the package changes it could be hit just on build.

**Comment by yishaigalatzer** [comment]
We cannot stop the build from restore failures, as far as we know. We have been pinging @AArnott on this, but don't think there is a solution here.

We can follow up again to get a definite answer.

**Comment by anurse** [comment]
As long as there is a descriptive error in the error list saying something like "Package Restore failed, see output window for details", I think we could live with not stopping the build. But if we don't put a clear message in, there will be a bunch of build errors about missing references and users will get confused.

**Comment by AArnott** [comment]
@yishaigalatzer  Returning a failing HRESULT from the solution build started event *might* stop it, I don't know. But I don't think you should. If I'm off the network, and can't restore a package for a particular project but want to build the rest of my projects in my solution anyway, I don't think I'd be happy if NuGet got in the way. But an error in the error list and/or output window would be fine.

Just be sure to clean up the error list entry when the problem is resolved. :)

**Comment by anurse** [comment]
Sounds good. Error in the list, but don't stop the build. In theory, Restore should only fail in situations where the project would not build (network connectivity shouldn't cause a failure unless network connectivity would be REQUIRED to get something the user doesn't have locally) but I'm not 100% confident we handle all those cases properly.

**Comment by deepakaravindr** [comment]
For the non-UAP scenarios, this is what we already do. Errors in the error list, and we don't stop the build, whether the restore failed or was canceled. We will do the same for UAP

**Comment by anurse** [comment]
:+1:

**Comment by yishaigalatzer** [comment]
@anurse can we make a fix where we don't even go the network if everything is available fowler have an idea

**Comment by emgarten** [comment]
NuGet/NuGet3@fa39984a733f3871eac1b9785636fa70debf6d69

All packages in the graph are now added to the global folder, including the rejected ones to avoid having to connect to a remote source to find them later. For non-floating scenarios no network calls will be made.
