### ISSUE TITLE
Infinite loop in ConcurrencyUtilities.ExecuteWithFileLockedAsync

### ISSUE THREAD

**Issue by lbargaoanu** [NuGet/Home#7530]
When restoring a project in a destination path longer than MAX_PATH, the lock utilities enter an infinite loop. We expect the restore to fail immediately with PathTooLongException.
NuGet.Commands 4.8.

**Comment by nkolev92** [comment]
NuGet (and all corresponding .NET build siblings) do not work too well with long paths. 
There is no special long path handling embedded in the client libraries. 
See related https://github.com/NuGet/Home/issues/3324. 

Currently we only utilize whatever the underlying FS allows us to do. 
If possible, can you please provide a small repro for us exactly showing your scenario?

Thanks.

**Comment by lbargaoanu** [comment]
I've attached a repro package. It fails for us with the API, but the same happens in VS. It's possible for that path to be that long by accident. It seems to me it should fail immediately, rather than enter an infinite loop.
[1LongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNam.1.0.6897.29548.nupkg.zip](https://github.com/NuGet/Home/files/2604129/1LongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNameProcessLongNam.1.0.6897.29548.nupkg.zip)
