### ISSUE TITLE
nuget spec should remove licenseUrl and favor the new license property instead

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7531]
We are [deprecating licenseUrl](https://github.com/NuGet/Home/issues/4628)  and several getting started docs like [Quickstart: Create and publish a package using Visual Studio (.NET Framework, Windows)](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework#generate-the-initial-manifest) still have a `nuget spec` step that will lead new users down the wong path.
nuget spec should be fixed to remove licenseUrl and add license.

**Comment by nkolev92** [comment]
//cc @rrelyea 
This is not a bad starter work item. 

This basically means removing some more of the nuget.core.v2 dependencies from our codebase.

**Comment by dotMorten** [comment]
I have some issues with the current approach. Try this:

1. Create a nuspec with a `<license type="file">` tag pointing to an embedded license file.
2. Pack the nuget
3. Note that a `<licenseUrl>` is generated in the nuspec file inside the nuget, that points to a non-existing page:
```xml
<licenseUrl>https://aka.ms/deprecateLicenseUrl</licenseUrl>
```
That page just takes you to some generic nuget doc landing page.

I assume it's done for some backwards compat reason, and to support older clients. To remedy the wrong URL, I wanted to add both license and `licenseUrl`, so any client that doesn't understand the license tag will still work with my `licenseUrl`. However providing both `license` and `licenseUrl` creates the following packaging error:

> The licenseUrl and license elements cannot be used together.
...

I think it would be better to tell me `licenseUrl` is deprecated if no `license` tag is used (as it is today), but remove the warning if both are provided, and not prevent me from specifying both (as it is today). Especially considering you're injecting a fake `licenseUrl` into the package anyway, this property obviously isn't going away - I just don't get to control what you're forcing it to be. 

TBH I'm very reluctant to move to the new license approach, if we can't control fallback to licenseUrl and provide a proper URL. It would be quite a while (years) before I'm certain all my customers are minimum on VS2017.9

**Comment by clairernovotny** [comment]
There are many issues, see this entire thread:

https://twitter.com/dotMorten/status/1068232919334801408

**Comment by clairernovotny** [comment]
For example, you cannot have the client generate licenses to nuget.org, since that would be an information disclosure for private packages. Not all packages go to nuget.org.

How would the client even know at pack time what the destination is?

**Comment by karann-msft** [comment]
We discussed this, below is summary of the workflow:
![image](https://user-images.githubusercontent.com/16904420/49674825-1acbcd80-fa28-11e8-896b-04f5b6cd6871.png)
![image](https://user-images.githubusercontent.com/16904420/49674846-261ef900-fa28-11e8-9d07-66f9f066cbc9.png)

**Comment by zkat** [comment]
Update on this, since I started looking into it: doing this change seems to require refactoring `nuget spec` away from CoreV2, which will probably be a bigger change than expected. I'm happy to do this refactor and update the docs, though (is someone else besides us responsible for docs site changes?)

**Comment by nkolev92** [comment]
@zkat https://github.com/NuGet/Home/issues/7531#issuecomment-440449048 :D 

As far as docs go, we usually doc our own features.  
We now have a dedicated content developer, so if needed, he can help with structure/etc.

**Comment by zkat** [comment]
@nkolev92 omg of course it was -right there-
