### ISSUE TITLE
Nuget should not require ALL package sources be available when installing a package.

### ISSUE THREAD

**Issue by ScottSEA** [NuGet/Home#7532]
## Details about Problem

Product | Version
-------- | ------
NuGet product used | VS UI  & Package Manager Console (PMC)
NuGet version | 4.6.0
dotnet.exe --version | 2.1.403
VS version (if appropriate) | 15.8.9
OS version | Win10 v1709, OS Build  16299.726
Worked before | unknown

## Detailed repro steps so we can see the same problem

At the moment of issue, the https://api.nuget.org/v3/index.json package source was not responding (for whatever reason). 

When installing a package - whether using the VS UI or  PMC when I select **my enterprise nuget package source as the ONLY package source**, then try to install a package (it doesn't matter which one) I get the following error:

> Attempting to gather dependency information for package 'Any.Package.Whatsoever' with respect to project 'MyProject', targeting '.NETFramework,Version=v4.7.2'
> install-package : Exception 'System.AggregateException' thrown when trying to add source 'https://api.nuget.org/v3/index.json'. Please verify all your online package sources are available.
>   One or more errors occurred.
>   Unable to load the service index for source https://api.nuget.org/v3/index.json.
>   An error occurred while sending the request.
>   The remote name could not be resolved: 'api.nuget.org'
> At line:1 char:1
> + install-package Steeltoe.Security.Authentication.CloudFoundryOwin -so ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CategoryInfo   : NotSpecified: (:) [Install-Package], Exception
> FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:02.2950456
> 

-------------

I have even explicitly stated which source to use:

    PM> install-package Steeltoe.Security.Authentication.CloudFoundryOwin 
            -source https://mycompany.com/getemhere/api/nuget/Nuget-Snapshot
 
... and I still get the error that the other source is unavailable.  

In the dropdown I have specified my enterprise package source as the sole source.  In the install-package **command** I also specified the enterprise package source.  The only way I can successfully install the package is to go into settings and DESELECT the offline nuget package source, so it's only using one.  

Seems to me that if I can find the package from *ANY* source I should be able to install it, whether *ALL* the package sources are online or not.

**Comment by nkolev92** [comment]
Thanks for filing this @ScottSEA 
This is by design and only in package reference as of now.
The PMC already displays a warning when the -source is used.

More details in the following open issue https://github.com/NuGet/Home/issues/6373.

**Comment by ScottSEA** [comment]
"*More details in the following open issue #7532*"... this *is* issue #7532

**Comment by nkolev92** [comment]
Sorry about that, bad copy paste. 

https://github.com/NuGet/Home/issues/6373
