### ISSUE TITLE
NuGet fails to install package due to wrong directory separator picked.

### ISSUE THREAD

**Issue by tinaschrepfer** [NuGet/Home#7538]
When attempting to install a package, I'm getting this error:

Install-Package Microsoft.VisualStudio.ImageCatalog -Version 16.0.28316-pre

Install failed. Rolling back...
Package 'Microsoft.VisualStudio.ImageCatalog.16.0.28316-pre' does not exist in project 'VSIXProject13'
Package 'Microsoft.VisualStudio.ImageCatalog.16.0.28316-pre' does not exist in folder 'C:\Users\tinali\source\repos\VSIXProject13\packages'
Executing nuget actions took 539.83 ms
Install-Package : Could not install package 'Microsoft.VisualStudio.ImageCatalog 16.0.28316-pre'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, 
contact the package author.
At line:1 char:1
+ Install-Package Microsoft.VisualStudio.ImageCatalog -Version 16.0.283 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Talking to @jainaashish, seems like the wrong directory separator is used and causing this failure.

**Comment by nkolev92** [comment]
@tinaschrepfer 

Can you please provide a feed that either contains the package or that package itself so we can repro it better? 

As I assume you don't want this publicly providing this on an internal share or sending it to nuget-client[at] should work.

**Comment by jainaashish** [comment]
A little more investigation into this, showed that this was related to manual modification of nupkg which resulted into invalid entries format in nupkg so when we read through ZipArchieve, it failed. So this isn't related to NuGet.

Bottom of the issue is CloudBuild is not able to sign the package which resulted into Xaml team to modify the nupkg after it was build. There is already a email thread, and will take it forward from there.
