### ISSUE TITLE
Fix FormatException in DateTime.Parse from DateTimeConverter

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7539]
From internal bug 671653.

We're seeing crashes coming from `DateTime.Parse` within `DateTimeConverter`. We know it's a `FormatException`, but don't have enough date to know exactly why it happens. Best guess is that the machine has a custom date format setting, so the `value.TroString()` is outputting a format that can't be parsed by `DateTime.Parse`.

**Comment by nkolev92** [comment]
I don't think this meets the 4.9.x bar. 
The QB suggests that in the issue.

**Comment by rrelyea** [comment]
Merged to 4.9.2 yesterday.
