### ISSUE TITLE
Dialog for UWP restore

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#754]
Building a UAP application freezes the UI and VS is totally unusable for over 20 secs

Repro steps

1. Create a NuGet UAP application. Or, open an existing one
2. Make sure that the global packages folder is deleted
3. Build the NuGet UAP application

Expected:
Packages are restored and the progress is continuously reported on the output window

Actual:
The UI is completely non-responsive for several seconds (around 20+ seconds) and there is no visual feedback of any kind as to why the UI is busy

**Comment by yishaigalatzer** [comment]
This is to add the restore dialog, and if it is reasonable add a cancel button.
