### ISSUE TITLE
There is no explanation of what PackageLicenseExpressionVersion means

### ISSUE THREAD

**Issue by adamralph** [NuGet/Home#7544]
## Details about Problem

The [documentation](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack) currently states:

> If you want to add a license expression with a version, we follow a similar approach as the PackageType. We strongly encourage that you don't define the license expression version.

But doesn't offer any explanation of what a license expression version _is_.

## Detailed repro steps so we can see the same problem

1. Read the [documentation](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack).

2. Observe that there is no explanation of what a license expression version is.

**Comment by nkolev92** [comment]
@adamralph 

Is the following sufficient?

https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#nuspec-schema-changes

From the spec:

> Furthermore we define an optional version field which define the license expression grammar version. This will only be relevant if in the future we have an update to the license expression grammar.

**Comment by adamralph** [comment]
@nkolev92 the relationship between that section and the .NET SDK properties is a little obfuscated (and that's why I missed it).

**Comment by nkolev92** [comment]
Thanks @adamralph 
I have updated the spec to explicitly call out the relationship and improved the readability of the nuspec schema changes section. 

I will close this issue now. 
Feel free to comment if you don't consider your concerns addressed.
