### ISSUE TITLE
License URL and license causes read error with Metadata

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#7547]
With the new license element, it exports both the license and licenseUrl properties (for backwards compat).

The problem is that the Manifest reader throws if both are present meaning it cannot read the metadata of those packages.

The manifest reader should not throw if both are present.

This line fails in this scenario. I should not need to munch the xml before reading it; the API should allow round-tripping.

`  var manifest = Manifest.ReadFrom(reader.GetNuspec(), false);`

**Comment by jevansaks** [comment]
This also blocks trying to re-pack an unpacked nuget package using "nuget pack". Nuget itself blows up when it sees both license and licenseUrl. I had to modify my script to manually strip out the dummy licenseUrl out to work around this.

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/2769. 
It was a bug in the validation logic.
