### ISSUE TITLE
what's the replacement  of ZipPackage in NuGet.Core(V2)  in NuGet.Client(V3/V4)?

### ISSUE THREAD

**Issue by fhchina** [NuGet/Home#7548]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by PatoBeltran** [comment]
Hey @fhchina, there's no direct replacement for that type in the new APIs, nevertheless much of the same concept is covered by `PackageReaderBase` children, the most common one would be `PackageArchiveReader`. Does this help?

**Comment by fhchina** [comment]
Yes! Thanks for your answer. I just have a try for PackageArchiveReader. And try to implement an Adapter on top of PackageArchiveReader, to fit the interface of old ZipPackage.  In this process I find the design of LocalPackage/ZipPackage is problematic, especially for the resource leaking problem. So throw away these old API is correct refactory decision, but lack of documentation and migration guide is a huge pain for programmers like us.

**Comment by fhchina** [comment]
PackageArchiveReader.GetFiles() will return all files in zip package, including usually hidden stuff. Which method will return the real "content" files in zip, i.e. compatible for the NuGet.Core V2 behavior?

**Comment by fhchina** [comment]
I didn't find any method just like GetContentFiles(), This is what I need. In fact, I use nupkg as a generel packaging mechanism, not for .NET development. So it's content can be any file, and not follow the .NET packaging layout.

**Comment by fhchina** [comment]
I have borrowed some code from V2 to implement ZipPackage.GetFiles(), mainly excluding opc stuff by name rule.
