### ISSUE TITLE
NuGet.VisualStudio hangs during RestorePackages

### ISSUE THREAD

**Issue by remmus** [NuGet/Home#7549]
## Details about Problem

Package version: NuGet.VisualStudio.4.8.0
VS version (if appropriate): VS 2017 Enterprise
OS version (i.e. win10 v1607 (14393.321)): Windows 10 17134.345

I have created a VSIX plugin to create a solution template. Part of this process is to restore the Nuget package to the project using the following code:

```cs
var restorer = ServiceLocator.GetInstance<IVsPackageRestorer>();

foreach (Project project in _dte.Solution.Projects)
{
    restorer.RestorePackages(project);
}
```

Occasionally this works, but most of the time it hangs during the first iteraction through the loop. No errors are thrown it just causes Visual Studio to become unresponse and you have to force quit. I have tried to debug it, but am unable to step into the code for this method as it again hangs when I try to do so.

I found the code here which tests the functionaility:

https://github.com/NuGet/NuGet.Client/blob/f7eca8be30a7b2adc54637013f7950056dd205c2/test/TestExtensions/API.Test/InternalAPITestHook.cs

So also tried

```cs
ThreadHelper.JoinableTaskFactory.Run(
	async () =>
	{
	    await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();

	    var restorer = ServiceLocator.GetInstance<IVsPackageRestorer>();

	    foreach (Project project in _dte.Solution.Projects)
	    {
	        restorer.RestorePackages(project);
	        return;
	    }
	});
```

but get the same results. Unfortunately I cannot share the project sample as it uses a private nuget feed and it also contains sensitive information.

If I don't call this method the plugin works every time. Then if I open it and let VS restore packages everything is OK, but doing it through this code does not work.

Any ideas on what could be causing this?

Thanks

**Comment by ezolotko** [comment]
I am having the same problem with my solution.

**Comment by zkat** [comment]
@v-luzh do you mind trying to repro this to see if it's still happening?

**Comment by v-luzh** [comment]
Hi @zkat,This issue doesn’t repro on VS Master\30020.139.

**Comment by zkat** [comment]
Closing because we don't have a reliable repro
