### ISSUE TITLE
Allow project/solution setting to preference Nuget framework versions

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7553]
<p>Nuget allows packaging of multiple frameworks in a single Nuget, which is great.  However, getting projects to start referencing something like Standard over Framework is a pain because the consuming Framework project will automatically pick up the Framework DLLs, even if you want it to start referencing the newer Standard DLLs.  It would be great if you could set at a project or solution or nuget level a preference for what framework to target, then have fallbacks.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/379356/allow-projectsolution-setting-to-preference-nuget.html
VSTS ticketId: 726922_
_These are the original issue comments:_

Fiona Niu[MSFT] on 11/12/2018, 01:47 AM (15 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps. </p>

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
