### ISSUE TITLE
[PerfWatson] UIDelay: nuget.packagemanagement.visualstudio.dll!NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices+<AddOrUpdatePackageReferenceAsync>d__.MoveNext

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#7557]
Tracking issue for Classic csproj - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633668

**Comment by nkolev92** [comment]
The project sysrtem bug has been fixed in 16.4 (our 5.4). 

Closing this as there is no NuGet work required.
