### ISSUE TITLE
Improve package search by sorting search results

### ISSUE THREAD

**Issue by tb-mtg** [NuGet/Home#7558]
After performing a search is it possible to sort packages by not just relevance, but by any of the details provided (date last updated, total downloads, developer, version, etc...)?

**Comment by karann-msft** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#remove-the-tool

**Comment by PatoBeltran** [comment]
Hey @tb-mtg thanks for opening this issue. WE currently don't have any way to filtering our search results. Nevertheless there is some work going on around improving the search experience, for example https://github.com/NuGet/Home/issues/5725, if this sounds like something that would solve your issues I encourage you to jump in that thread and upvote so we can understand how many customers are affected by this. Thanks!

**Comment by zivkan** [comment]
I think this is a duplicate of https://github.com/NuGet/Home/issues/2585. @nkolev92  agreed?

**Comment by nkolev92** [comment]
@zivkan yep, nice catch.

**Comment by tb-mtg** [comment]
Thanks @zivkan 
Sure is a duplicate of #2585, I'll close this one and subscribe to that one.
