### ISSUE TITLE
After using Update All, packages remain in the Updates list 

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#756]
This issue is moved from Codeplex and reproes with NuGet 2.8.6 on Dev12. The original bug is https://nuget.codeplex.com/workitem/3885. 

Repro steps:

After update all the nuget packages (by clicking UpdateAll button), still have one ore more packages shown on the update list. 

 1) Create an MVC4 WebApplication 
 2) Update All Packages 
 3) Antlr is still left on the list

**Comment by yishaigalatzer** [comment]
This looks like a won't fix, the issue with updating dependencies is going to be fixed with transitive dependencies and project.json.
