### ISSUE TITLE
Nuget.VisualStudio API clarity

### ISSUE THREAD

**Issue by tonyhallett** [NuGet/Home#7563]
Nuget.VisualStudio for nuget API in visual studio extension

Is it possible to determine, with the events of IVsPackageInstallerProjectEvents and IVsPackageInstallerEvents, when a package has been installed for a particular project ?

Is there a guarantee that there is only a single batch operation being processed at a time - there is a guarantee that BatchStart is always followed by BatchEnd before the next BatchStart ?

**Comment by dominoFire** [comment]
> Is it possible to determine, with the events of IVsPackageInstallerProjectEvents and IVsPackageInstallerEvents, when a package has been installed for a particular project ?

@tonyhallett Did you take a look at:
1.  [IVsPackageInstallerEvents#PackageInstalled](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerEvents.cs#L13) ?
2. [VsPackageInstallerEvents#NotifyInstalled](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerEvents.cs#L80) (by checking the install path) ?

> Is there a guarantee that there is only a single batch operation being processed at a time - there is a guarantee that BatchStart is always followed by BatchEnd before the next BatchStart ?

It seems so: This [test](https://github.com/NuGet/NuGet.Client/blob/dev/test/TestExtensions/API.Test/InternalAPITestHook.cs#L125) document that.

I'm fairly new in this part of the code. If you have more questions, please reply in this issue.
