### ISSUE TITLE
Nuget 4.6 can not find beta package

### ISSUE THREAD

**Issue by LightVolk** [NuGet/Home#7566]
Nuget 4.6 can not find beta package.

Version 4.6. Works on:

Task         : MSBuild
Description  : Build with MSBuild
Version      : 1.120.0

 NuGet Version: 4.6.2.5055

So, i add nuget package to feed, but build can not find it when nuget restore:

NU1101: Unable to find package StyleCop.Analyzers. No packages exist with this id in source(s): MySource

I add 1.1.1-beta.61 version of this package.

But, also some time ago i add system.reactive.4.0.0-preview00001.nupkg and my build works with it and it was fine.

Also, i can find this package (StyleCop.Analyzers) via NugetPackage Manager from my VisualStudio!
Feed is the same.

What it can be?

**Comment by LightVolk** [comment]
Error message:  ""c:\Build1\externals\nuget\nuget.exe" restore "c:\Build1\.......\Project.csproj" -recursive" exited with code 1.

**Comment by PatoBeltran** [comment]
Hey @LightVolk that seems weird, can you try with the latest nuget.exe v4.9.1? You can get it from https://www.nuget.org/downloads... Also, you mentioned it shows in the VS UI, have you tried installing it from there? If this works, do you see any difference in the package reference that was added from VS and the one you did manually?

**Comment by LightVolk** [comment]
@PatoBeltran , very strange.. I update nuget.exe to 4.9.1 and nuget fails because he cannot find microsoft.visualstudio.web.codegeneration.tools package.
So, i add it into repo (2.0.4) and he can not find it again!

Log:

NuGet Version: 4.9.1.5694

```
Committing restore...
2018-12-03T11:10:59.4412250Z   Assets file has not changed. Skipping assets file writing. Path: c:\Build1\_work\1\s\path_to_proj\project.assets.json
2018-12-03T11:10:59.4412250Z   Restore completed in 99,04 ms for c:\Build1\_work\1\s\path_to_proj\MyProj.csproj.
2018-12-03T11:10:59.5818631Z     GET http://tfs.company.local:18099/folder/nuget/FindPackagesById()?id='Microsoft.VisualStudio.Web.CodeGeneration.Tools'&semVerLevel=2.0.0
2018-12-03T11:10:59.6130986Z     OK http://tfs.company.local:18099/folder/nuget/FindPackagesById()?id='Microsoft.VisualStudio.Web.CodeGeneration.Tools'&semVerLevel=2.0.0 43ms
2018-12-03T11:10:59.8631019Z   NU1101: Unable to find package Microsoft.VisualStudio.Web.CodeGeneration.Tools. No packages exist with this id in source(s): MyFeedName
2018-12-03T11:10:59.9256161Z   Value cannot be null.
2018-12-03T11:10:59.9256161Z   Parameter name: path
2018-12-03T11:10:59.9884904Z ##[error]Support\AutoBuild\path\PublishWeb.xml(141,5): Error MSB3073: The command ""c:\Build1\externals\nuget\nuget.exe" restore "c:\Build1\_work\1\s\path_to_proj\MyProj.csproj" -recursive" exited with code 1.
2018-12-03T11:10:59.9884904Z c:\Build1\_work\1\s\Support\AutoBuild\BuildScript\PublishWeb.xml(141,5): error MSB3073: The command ""c:\Build1\externals\nuget\nuget.exe" restore "c:\Build1\_work\1\s\path_to_proj\MyProj.csproj" -recursive" exited with code 1.
2018-12-03T11:10:59.9884904Z Done Building Project "c:\Build1\_work\1\s\Support\AutoBuild\BuildScript\PublishWeb.xml" (default targets) -- FAILED.


```

Response from Nuget Server: FindPackagesById()?id=%27Microsoft.VisualStudio.Web.CodeGeneration.Tools%27&semVerLevel=2.0.0



```
 <?xml

 version="1.0" encoding="utf-8"?>
<feed xml:base="http://tfs.company.local:18099/integration/nuget" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
  <id>http://schemas.datacontract.org/2004/07/</id>
  <title />
  <updated>2018-12-03T11:23:05Z</updated>
  <link rel="self" href="http://tfs.company.local:18099/integration/nuget/Packages" />
  <author>
    <name />
  </author>
</feed>

```


I need to clarify the situation:
We have removed almost all the packages from the build of the machine, including packages from. Net Core FallbackFolder, because we want to have complete control over the process of resolving dependencies when building projects.
In the local repository are all the packages that are needed to build projects, and no packages from the "temporary" directory or the sdk directory are not involved.

Nuget Server works on IIS, and in Web.config looks on local repo. User 'Network Service' have all rights (exclude special).

**Comment by LightVolk** [comment]
Maybe the error is that I am not using the 3rd version channel?
1. How can I find out which version of the channel I use?
2. How to explicitly specify version 3 for the local repository?

NugetServer (on local repo):You are running NuGet.Server v3.1.2.0

Error: https://docs.microsoft.com/ru-ru/nuget/reference/errors-and-warnings/nu1101

**Comment by LightVolk** [comment]
@PatoBeltran about installing package:

>Successfully installed 'StyleCop.Analyzers 1.1.1-beta.61'

I cannot see any differnce.
P.S. for now, this package find well from MS Build(nuget) and VS UI.

But not microsoft.visualstudio.web.codegeneration.tools. Not on MS Build and from VS UI.

**Comment by PatoBeltran** [comment]
@LightVolk it is weird that it works on VS but it doesn't on nuget.exe, the code that is running both of those should be the same one.

From one of the logs you provided I see:

```
2018-12-03T11:10:59.9256161Z   Value cannot be null.
2018-12-03T11:10:59.9256161Z   Parameter name: path
```

which caught my eye... can you run restore with detailed verbosity to see if that gives us more info in what is going on?


Also, could it be possible that you provide me with a small repro project to see if I can get this same behavior? You can zip it up and put it here for me to download and look into. Thanks!

**Comment by nkolev92** [comment]
@LightVolk 

Any headway on the repro? 
Thanks.

**Comment by LightVolk** [comment]
@nkolev92 , it seems that Nuget Server (or Visual Studio) can not work with beta package without some parameters like "Prerelease" or so on.

**Comment by nkolev92** [comment]
Not sure what you mean. 

Are you saying that the client cannot see all prerelease versions or?

**Comment by LightVolk** [comment]
@nkolev92 , client can not find prerelease packages.

**Comment by nkolev92** [comment]
And you are saying it only happens with NuGet.Server? 

From the response you posted above it looks like  NuGet.Server  doesn't seem think the package existson the feed. 

Let us know if you are able to provide us a repro with a public feed such as NuGet org, or give us clear instructions of your setup.

**Comment by LightVolk** [comment]
@nkolev92 , if this issue come again, i reopen this issue.
