### ISSUE TITLE
NuGet missing on this computer

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7568]
@perryraskin commented on [Fri Nov 30 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1200)

I'm trying to import my .sln file from a Visual Studio project (from a Windows computer) into Rider on my Mac. I'm getting the following error.

```
[null] This project references NuGet package(s) that are missing on this computer. 
Enable NuGet Package Restore to download them.  For more information, see
http://go.microsoft.com/fwlink/?LinkID=322105. 
The missing file is .../.nuget/NuGet.targets.
```

I already copied the .nuget folder from the Windows computer (where the project is working properly). Anything I'm missing here? Usually doing this fixes the issue when I've moved to another Windows computer in the past.

**Comment by PatoBeltran** [comment]
Hey @perryraskin, thanks for opening the issue! This error message since to be a Rider message instead of a nuget one. As far as NuGet knows, the suggestion to run a restore to get the missing packages, have you tried using `dotnet` to restore your project?

**Comment by perryraskin** [comment]
I get errors when using `dotnet` commands. 

```
error MSB4019: The imported project
"/usr/local/share/dotnet/sdk/2.1.302/Microsoft/VisualStudio/v15.0/WebApplications/
Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import>
declaration is correct, and that the file exists on disk.
```

**Comment by perryraskin** [comment]
This was fixed by putting the .nuget folder from the Windows computer where the original project was, in the root directory of the project.
