### ISSUE TITLE
TrustedSigners owners are evaluated with CaseSensitive strings

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#7573]
NuGet.org has packages owned by Microsoft with different casing in the repository signature metadata. 

Customers who want to trust packages owned by Microsoft must add two entries in the config file.

```xml
<owners>Microsoft;microsoft,</owners>
```

Since NuGet.org does not accept owners with different casing, NuGet clients should evaluate trust as case insensitive

/cc @PatoBeltran  @dtivel

**Comment by PatoBeltran** [comment]
@loic-sharma can you update this issue with your progress once you get to work on this?

**Comment by loic-sharma** [comment]
@PatoBeltran All Microsoft owned packages on NuGet.org now have an uppercased "Microsoft" listed as an owner in the repository signature metadata.

**Comment by PatoBeltran** [comment]
Awesome! Will close this issue since it has been resolved.
