### ISSUE TITLE
NuGet.exe should pass IgnoreMissingImports to MSBuild

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#7576]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): `4.9.1.5694`

dotnet.exe --version (if appropriate): `2.2.0-preview1-007622`

VS version (if appropriate): 15.9.2

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version: not a regression

## Detailed repro steps so we can see the same problem

Currently if using `NuGet.exe restore My.sln` and one of the projects has an import that doesn't exist, such as:

```
<Project>
  <Import Project="non-existing.csproj" />
</Project>
```

Then NuGet fails to restore the project. 

I think there should be a way to ignore this error and proceed. I know the MSBuild API has the `IgnoreMissingImports` switch - perhaps it should be used. 

This is a bit of a chicken and egg problem because the imported project doesn't exist because it needs to be downloaded/restored by NuGet, and NuGet doesn't work because the project isn't there.

**Comment by nkolev92** [comment]
Is IgnoreMissingImports even settable as a property? 

@jeffkl 

```
msbuild /t:restore F:\VSExtensibility\src\product\vssdk\msbuild\Microsoft.VisualStudio.Sdk.BuildTasks.16.0\Microsoft.VisualStudio.Sdk.BuildTasks.16.0.csproj -IgnoreMissingImports   

Microsoft (R) Build Engine version 16.5.0-preview-19617-05+7bcb2f961 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1001: Unknown switch.
Switch: -IgnoreMissingImports

For switch syntax, type "MSBuild -help"
```

**Comment by KirillOsenkov** [comment]
See here for API usage:
https://source.dot.net/#Microsoft.Build/Definition/ProjectLoadSettings.cs,350c1887cee7e2df,references

**Comment by nkolev92** [comment]
NuGet.exe starts an msbuild process and calls a target. :(  
There's no compile time dependency to MSBuild.

**Comment by KirillOsenkov** [comment]
I see, MSBuild /r uses that flag in `ExecuteRestore`, but if you call the `Restore` target manually it's not set:
http://index/?query=ExecuteRestore&rightProject=Microsoft.Build&file=XMake.cs&line=1356

You are correct, there's currently no way to pass IgnoreMissingImports to MSBuild via command line if not using /r.

**Comment by nkolev92** [comment]
It works if you call the "restore" target directly. 

Thing is nuget.exe calls GenerateRestoreGraphFile, and restores on its own, cause it has the packages.config logic there. 

https://github.com/NuGet/Home/issues/9035 :)

**Comment by zkat** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/9035
