### ISSUE TITLE
Migration to PackageReference

### ISSUE THREAD

**Issue by rafsanulhasan** [NuGet/Home#7578]
## Details about Problem

I'm working on a Xamarin.Forms solution which includes a Xamarin MAC project. In all the projects, I used Xam.Plugins.Settings NuGet package By James from Microsoft. When I tried to convert the project from PC to PR, I found this warning message propping up into a browser: 
**"Xam.Plugins.Settings v3.1.1<br/>
'content' assets will not be available when the package is installed after the migration."**

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):VS UI

NuGet version (x.x.x.xxx): 

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a Xamarin.Forms project

2. Within that solution Add a Xamarin.MAC project.

3. Install Xam.Plugins.Settings NuGet package into MacOS project

4. change the project from PC to PR

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
That's a warning message is as expected. 

More info 
https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html
https://github.com/NuGet/Home/issues/6659
