### ISSUE TITLE
The Installed indicator (the checkmark) does not show up for installed packages if they are not restored

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#758]
Repro
- Create a new console application.
- Install JQuery.
- Close the solution. Delete the packages folder.
- Open the solution, then open the package manager.

Expected:
A check mark on JQuery to show that it is installed.

Actual:
No check mark.

**Comment by yishaigalatzer** [comment]
@feiling I think this is a duplicate bug, and we should fix it for RTM (I actually thought you did), please take a look
