### ISSUE TITLE
Support for transitive project and packagereferences in netfx and .net core 

### ISSUE THREAD

**Issue by voltcode** [NuGet/Home#7584]
Scenario:

Project A packagereferences nuget X
Project B projectreferences Project A

When building Project B, I wish that it's nugets are automatically resolved from Project A dependency (Project B has indirect dependency on nuget X).

Can this be supported with current nuget ? I tried it to no avail (Project B on ,NET FX, Project A on netstandard). dotnet restore didn't work - project.assets.json were not rebuilt.

**Comment by nkolev92** [comment]
Is B a PackageReference based project? 

If it's already a real project you have a few options: 

If PC -> [migrate](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference)
If not PC -> Add `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` in a property group.

**Comment by voltcode** [comment]
The last bit helped, thanks!
