### ISSUE TITLE
nuspec should support optional files/folders

### ISSUE THREAD

**Issue by rossng** [NuGet/Home#7585]
## Details about Problem

NuGet product used: NuGet.exe, VS UI

NuGet version: 4.6.2.5055

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): Professional 15.9.3

OS version: win10 v1809 (17763.134)

Worked before? If so, with which NuGet version: N/A

## Steps to reproduce

1. In a nuspec file, create a `<file>` reference to the contents of a folder which does not exist, e.g. `<file src="bin\somefolder\*.*" target="lib\content\"/>`

2. Try to `nuget pack` the project. You will receive the following error message:

`Could not find a part of the path '[removed]\bin\somefolder'.`

## Other suggested things

It would be nice if there were a way to mark some includes as optional. In this case, it is because some folders are only created when running in CI, but I still want to be able to create NuGet packages locally for testing.

(Someone else's) [StackOverflow post](https://stackoverflow.com/questions/24804112/optional-or-conditional-folders-in-nuget-files-tag)

**Comment by zivkan** [comment]
Sorry for the late reply. We're focusing on improving the pack experience with MSBuild projects (primarily .NET SDK projects, but also other projects that import NuGet.Build.Pack.targets), and need to update our docs accordingly. MSBuild already supports conditions, so can achieve what you're asking for.

We're unlikely to get to this any time soon, so I'm closing to avoid anyone waiting for this with `nuget.exe pack`.
