### ISSUE TITLE
[Test Failure] Error “Provide value on ‘System.Windows.Markup.StaticExtension’ threw an exception” occur when opening PM UI in Solution Explorer window 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7592]
## Details about Problem
VS Version: D16.0 28404.61
OS Version: 17763.RS5_Release.180914-1434.
NuGet Version: Dev\5.0.0.5710
## Detailed repro steps
1. Launch VS and create a new Console App (.Net Core) project.
2. Open the PM UI in Solution Explorer window.
## Expected
PM UI should be opened successfully.
## Actual
Error “Provide value on ‘System.Windows.Markup.StaticExtension’ threw an exception” occur when opening PM UI in Solution Explorer window as below attachment.
![1205](https://user-images.githubusercontent.com/40230425/49503485-82f8a300-f8b2-11e8-8f8d-aee2e2e859a8.PNG)
## Notes:
1. The issue also repro on Dev\5.0.0.5708 and Dev\5.0.0.5709.
2. The issue not repro on Dev\5.0.0.5707.

**Comment by jainaashish** [comment]
@nkolev92 it seems upgrading to net472 PR# https://github.com/NuGet/NuGet.Client/pull/2544 has broke this. Can you look at this on high priority?
