### ISSUE TITLE
Restore unnecessarily enumerates global package folder in attempt to determine type

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#7596]
## Details about Problem

Nuget version 4.9.0.6

## Detailed repro steps so we can see the same problem

1. Create a packages.config file like the following
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="protobuf-net" version="2.1.0" />
</packages>
```
2. Open procmon and filter to accesses by nuget.exe

3. 'nuget restore <path to packages.config>

4. Notice that procmon has recorded a directory enumeration in an unrelated subdirectory of the global packages cache

This is caused by the fact that Nuget internally 'forgets' the feed type for the packages cache and needs to look at the file system to determine if it's e.g. v2 or v3.

**Comment by bergbria** [comment]
PR [here](https://github.com/NuGet/NuGet.Client/pull/2553)

**Comment by rrelyea** [comment]
@dtivel  - u able to take a quick look at this PR, perf wise, compat wise?

**Comment by dtivel** [comment]
The change looks good to me.  I don't see a significant performance change.

Thanks for the contribution, @bergbria.
