### ISSUE TITLE
Nuget.exe client crashes when network share contains files with .Nupkg extension

### ISSUE THREAD

**Issue by mikeholcomb** [NuGet/Home#760]
Nuget.exe will crash when listing network share sources that have files with .Nupkg (case matters) here extension.  Changing the extension to .nupkg fixes the issue.

Repro: 
1) Put valid nupkg on share. Example: copy foo.nupkg to \\machine\share\packages
2) Rename file from .nupkg to .Nupkg
3) Run nuget.exe list -Source \\machine\share\packages

In my repro case I used Microsoft.AspNet.WebApi.Client.5.0.0.nupkg

Expected:
Packages listed

Actual:

WARNING: Object reference not set to an instance of an object.
No packages found.

**Comment by deepakaravindr** [comment]
Just verified that I could do the following
1) nuget list -Source < myLocalPackageSource > as stated in the bug
2) nuget install <packageWithNupkgAsExtension> -Source < myLocalPackageSource > 

It works fine
