### ISSUE TITLE
NuGet Package Manager version in VS > Help > About ... is out of date

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#7600]
VS Version: 15.9.4 Preview 1.0

The version says "4.6.0". But really it is 4.9.
![image](https://user-images.githubusercontent.com/94054/49619451-74bd8c00-f971-11e8-8c57-ecd1642df861.png)

From PMC:

![image](https://user-images.githubusercontent.com/94054/49619472-869f2f00-f971-11e8-83d4-2e2d4cdb83ea.png)

**Comment by nkolev92** [comment]
This could probably be made better somehow, so we don't need to rename a value in a cs file ideally. 
For reference here's where the code is. 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.Tools/NuGetPackage.cs#L71

**Comment by v-luzh** [comment]
Same with internal bug 651994. We will verify after you fix it with a better way somehow.
