### ISSUE TITLE
Install the.NetFramework packages in .NetCore projects

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7602]
Hi Everyone,

I have generated the custom NuGet package for our assemblies with some dependent NuGet packages. 

NuGet package lib folder structure:

![image](https://user-images.githubusercontent.com/16695209/49623870-6a44d600-f9f5-11e8-8f48-4a1795d26e25.png)

Dependent NuGet package lib folder structure:

![image](https://user-images.githubusercontent.com/16695209/49623997-d7f10200-f9f5-11e8-81d6-d8db647f5b4a.png)

Now I have tried to install my custom NuGet package in .NETCORE projects. Packages installed successfully. But assembly not referred like I expected.

.NetFramework assembly structure - 2.4{Frameworkversion}.0.2 (For Ex: 2.4450.0.2)
.NetCore assembly structure - 2.4.0.2

I expect the assemblies like .Netframework structure in core project. Parent package assemblies added as i expected but, dependent packages assemblies added like .netcore assembly structure. But I need to add the .netframework assemblies structure from the dependent NuGet packages.

Could you please suggest me to achieve this?

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Hi All,

Could you please suggest me to achieve this?

**Comment by GanesanRengasamy** [comment]
Hi All,

Could you please suggest me to achieve this?

**Comment by nkolev92** [comment]
@GanesanRengasamy 
I'm having trouble following the question here.

I'm not sure what you mean by "core assembly structure". 

Can you clearly describe what's happening? 
An example project (with packages) would be super helpful.

**Comment by GanesanRengasamy** [comment]
Hi @nkolev92,

My custom assembly version is different for NetFramework and NetStandard like below,

.NetFramework assembly structure - 2.4**{Frameworkversion}0**.0.2 (For Ex: 2.4450.0.2)
.NetCore assembly structure - 2.4.0.2

When I installed the package in ASP.NET Core Project (4.6 framework) which is mentioned in previous comment my parent NuGet package refer the assembly like (2.4460.0.2), but my dependent packages refer assembly like 2.4.0.2 since the dependent packages refer assembly from netstandard lib folder.

**Comment by nkolev92** [comment]
@GanesanRengasamy 
Unfortunately I'm still not able to follow. 

Can you please create a repro project for us? 
Thanks.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
