### ISSUE TITLE
README.txt opens repeatedly during multi-project package update

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#761]
I've noticed when Update-Package is executing and several projects in the solution are impacted, the README.txt file is opened up several times (e.g. try closing the document while the update is still in progress and it will be re-opened). I believe the NuGet docs state that the readme.txt will only open when a package is directly installed (not as a dependency) and perhaps not as an update either, not sure.

Anyway, it seems to me that NuGet should only open the readme file at most once per operation -- not repeatedly.

Rough repro steps (since I highly doubt it depends on which exact package it is):
1. Have a solution with several projects
2. Install an older version of a package with a readme.txt file into all of them.
3. Close any readme.txt that opens.
4. Update the package to the latest version.

Expected:
at most one readme.txt doc opened

Actual:
about one readme.txt per project that is updated. (try leaving the doc open as updating proceeds, and/or closing the documents as they open during the update).

Related to #607 

I'll go ahead and suggest this bug has relatively low priority.

**Comment by yishaigalatzer** [comment]
We also want to make readme.txt show up for `project.json` scenarios

**Comment by rohit21agrawal** [comment]
@AArnott don't see this happening with the VS Nuget Client. Can you share details of what version/client you are using to get the repro?

**Comment by AArnott** [comment]
Nope. I'm afraid given the age of the bug and the fact that I don't recall it ever reproing for me after filing it, there's probably no way I can dig that information up either. I'd offer to close, but perhaps @yishaigalatzer  has in mind to use this bug to track the feature he mentioned above:

> We also want to make readme.txt show up for  project.json  scenarios

**Comment by yishaigalatzer** [comment]
We should do both, so if you can't repro we just need to design the other scenario

**Comment by rohit21agrawal** [comment]
@yishaigalatzer @harikm86 @rrelyea 
project.json scenarios work for non Project K projects (UWP etc) .

What should we do about ProjectK projects?
