### ISSUE TITLE
Some servers of api.nuget.org are giving timeout

### ISSUE THREAD

**Issue by NicolasDorier** [NuGet/Home#7612]
I noticed that `api.nuget.org` was making timeout  on my CI server.

```bash
wget https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracesource/index.json
--2018-12-10 13:26:59--  https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracesource/index.json
Resolving api.nuget.org (api.nuget.org)... 152.199.4.33
Connecting to api.nuget.org (api.nuget.org)|152.199.4.33|:443... connected.
HTTP request sent, awaiting response... ^C
```

It was working on my machine which was resolving a different IP, so I tried to modify my `/etc/hosts` on the CI server.

```bash
echo "117.18.232.200 api.nuget.org" | sudo tee -a /etc/hosts
```

Then things start working again.

This problem started today.

**Comment by sherloqholmes** [comment]
I was seeing the same issue on our CI environment.
The problem seems to be resolved now.

**Comment by NicolasDorier** [comment]
Still had this problem 1H ago.

**Comment by skofman1** [comment]
Hi, We will need additional information in order to investigate. Please follow the instructions here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible to gather logs and send to support@nuget.org

**Comment by jugg1es** [comment]
You don't even need nuget to reproduce this.  Just try to do a GET on https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracesource/index.json 

It times out.

**Comment by PeteBoyRocket** [comment]
The above link @jugg1es posted now works for me in the UK, but we are still seeing this issue on our AWS CI agents hosted in a US region

**Comment by skofman1** [comment]
@jugg1es  , it's a CDN related issue, so it's not reproducible from any location (works from Redmond). To investigate we need logs from YOUR location.

**Comment by PeteBoyRocket** [comment]
ON it! Bear with me, takes a bit of faffing to get onto our CI nodes...

**Comment by jugg1es** [comment]
our build servers are linux, I can't run that tool.  But the error is coming from AWS us-east-1 and my office which is near DC.   Here is the nslookup from my office: 
 nslookup api.nuget.org
Server:  ai-vmdc2.intranet.local
Address:  10.41.117.30

Non-authoritative answer:
Name:    cs22.wpc.v0cdn.net
Address:  152.199.4.33
Aliases:  api.nuget.org
          nugetapiprod.trafficmanager.net
          az320820.vo.msecnd.net



Here is the nslookup from the build server: 



 nslookup api.nuget.org
Server:         172.31.0.2
Address:        172.31.0.2#53

Non-authoritative answer:
api.nuget.org   canonical name = nugetapiprod.trafficmanager.net.
nugetapiprod.trafficmanager.net canonical name = az320820.vo.msecnd.net.
az320820.vo.msecnd.net  canonical name = cs22.wpc.v0cdn.net.
Name:   cs22.wpc.v0cdn.net
Address: 152.199.4.33

**Comment by PeteBoyRocket** [comment]
Our CI agents that are failing are also in us-east-1 fyi

**Comment by skofman1** [comment]
Thanks for the info! I'm working with Verizon CDN on investigation.

**Comment by PeteBoyRocket** [comment]
Heres the WinMTR test results so far:
```
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                           100.65.12.209 -    0 |  284 |  284 |    0 |    1 |   19 |   15 |
|                             52.93.28.99 -    0 |  284 |  284 |    0 |    0 |   21 |    1 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   56 |    0 |    0 |    0 |    0 |    0 |
|                           52.93.114.122 -    0 |  284 |  284 |    0 |    4 |   30 |   11 |
|                          54.239.111.255 -    0 |  284 |  284 |    0 |    0 |   24 |    0 |
|               core1.dca.edgecastcdn.net -    1 |  276 |  274 |    1 |    2 |   26 |    1 |
|                          152.195.64.129 -    0 |  284 |  284 |    1 |    4 |   39 |    3 |
|                            152.199.4.33 -    0 |  284 |  284 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

I've also emailed it to support@nuget.org

**Comment by skofman1** [comment]
Is the issue still in progress? We need some additional details for investigation:
1. Source IP
2. HAR file (instructions [here](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting))

**Comment by jugg1es** [comment]
no it appears fixed.  thank you!

**Comment by skofman1** [comment]
Is this fixed for everyone else as well or only @jugg1es ?

**Comment by NicolasDorier** [comment]
@skofman1 the source IP is in my logs `152.199.4.33`, give it a try. With a request at `https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracesource/index.json`. You can simulate this by changing your hosts to have `api.nuget.org` point to `152.199.4.33` and trying to fetch with `wget`.

I will try again today on my CI.

**Comment by PeteBoyRocket** [comment]
@skofman1  Working for me too now! thanks! 
(Sorry for the late reply, I was asleep!)

**Comment by skofman1** [comment]
@NicolasDorier , are you still able to reproduce the issue?

**Comment by NicolasDorier** [comment]
I just removed the hack I added on my CI server to see if it restores.
Seems to work fine now thanks.

**Comment by eSPiYa** [comment]
Experiencing the same issue right now. Can't install any nuget package

<center><h2>WinMTR statistics</h2></center>
<p align="center"> <table border="1" align="center">
<tr><td>Host</td> <td>%</td> <td>Sent</td> <td>Recv</td> <td>Best</td> <td>Avrg</td> <td>Wrst</td> <td>Last</td></tr>
<tr><td>192.168.100.1</td> <td>   0</td> <td> 182</td> <td> 182</td> <td>   0</td> <td>   1</td> <td>  10</td> <td>   1</td></tr>
<tr><td>203.160.163.145</td> <td>   0</td> <td> 182</td> <td> 182</td> <td>   2</td> <td>   6</td> <td>  39</td> <td>   3</td></tr>
<tr><td>10.1.100.1</td> <td>   1</td> <td> 178</td> <td> 177</td> <td>   2</td> <td>  16</td> <td> 272</td> <td>   6</td></tr>
<tr><td>116.93.32.49</td> <td>   4</td> <td> 158</td> <td> 152</td> <td>   2</td> <td>  16</td> <td> 228</td> <td>   5</td></tr>
<tr><td>ip-converge.0.127.121.in-addr.arpa</td> <td>   2</td> <td> 174</td> <td> 172</td> <td>  21</td> <td>  34</td> <td> 310</td> <td>  25</td></tr>
<tr><td>62.216.147.157</td> <td>   2</td> <td> 174</td> <td> 172</td> <td>  40</td> <td>  53</td> <td> 276</td> <td>  43</td></tr>
<tr><td>xe-3-2-1.0.cji02.hkg003.flagtel.com</td> <td>   2</td> <td> 174</td> <td> 172</td> <td>  40</td> <td>  55</td> <td> 273</td> <td>  41</td></tr>
<tr><td>15133.hkg.equinix.com</td> <td>   2</td> <td> 170</td> <td> 167</td> <td>  26</td> <td>  41</td> <td> 263</td> <td>  30</td></tr>
<tr><td>152.195.186.129</td> <td>   2</td> <td> 174</td> <td> 172</td> <td>  27</td> <td>  41</td> <td> 273</td> <td>  28</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
<tr><td>No response from host</td> <td> 100</td> <td>  36</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td> <td>   0</td></tr>
</table>

**Comment by skofman1** [comment]
Hi @eSPiYa ! Please follow instructions here: https://docs.microsoft.com/en-us/nuget/policies/nuget-faq#nugetorg-not-accessible and send logs to support@nuget.org.
Please also specify the location of the machine (region) and if it's part of a cloud (like AWS). Usually it's a connectivity issue between you and our CDN and I recommend checking with your ISP as well as us.
