### ISSUE TITLE
Error on build due to missing NuGet packages: "..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets"

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#7618]
@wfuller commented on [Fri Dec 07 2018](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1215)

I am getting this error "Error on build due to missing NuGet packages: "..\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets" when I try and build this solution in VS 2013.

Despite the error, I can see the 3 BCL files in my packages.config file:
    <package id="Microsoft.Bcl" version="1.1.3" targetFramework="net45" />
    <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net45" />
    <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net45" />

My package manager settings are set to "Allow NuGet to download missing packages", and to "Automatically check for missing packages during build in Visual Studio".

All of the troubleshooting info I've found suggests this should be all I need. The BCL files are specified in the packages.config file, and so VS should get them from NuGet if they aren't already present. 

But it still isn't working.

I should mention that this is an old web app build on a different computer some time ago by someone else, which I now need to modify. There is an old build that worked and can still run. I just can't get it to build now, on my computer.

**Comment by jainaashish** [comment]
what happens when you do an explicit restore? does it get the missing files on disk?

**Comment by wfuller** [comment]
No it doesn't do anything; that was what was so weird. 
However, I have since resolved the problem another way - by removing from the project and then adding back the package that was depending on the BCL.

**Comment by jainaashish** [comment]
>  by removing from the project and then adding back the package that was depending on the BCL

Not sure what you mean by this? A sample repro solution explaining the issue or your current workaround will help better understand the issue.

**Comment by zivkan** [comment]
If the old project used to be under `Solution Folder\Project\Project.csproj`, then the path to the packages folder is `..\packages`. However, if it was moved to something like `Solution Folder\src\Project\Project.csproj`, then the reference of `..\packages`  is no longer correct. This can be fixed by reinstalling the packages in the project. This issue is also one of the reasons that it's recommended to migrate to PackageReference, but that's only possible in Visual Studio 2017.

Anyway, I'm closing this as it's over a month since the last customer comment. If this is still an issue, please provide more details, preferably a sample solution/project that has this issue.

**Comment by herbertmilhomme** [comment]
> If the old project used to be under `Solution Folder\Project\Project.csproj`, then the path to the packages folder is `..\packages`. However, if it was moved to something like `Solution Folder\src\Project\Project.csproj`, then the reference of `..\packages` is no longer correct. This can be fixed by reinstalling the packages in the project. This issue is also one of the reasons that it's recommended to migrate to PackageReference, but that's only possible in Visual Studio 2017.
> 
> Anyway, I'm closing this as it's over a month since the last customer comment. If this is still an issue, please provide more details, preferably a sample solution/project that has this issue.

if the folder is empty, because a git ignore or a zip download, the migration of `packages.config` or `packagereference` wont matter because the build isnt downloading items that are missing or not found. The entire issue stems from being unable to locate resources, but the resources aren't being polled from web and downloaded if the contents are not where they are supposed to be. I've gone as far as using nuget manager to download libraries by name, but nuget is giving errors on fetching and downloading into the project. what am i supposed to do to resolve these errors?
