### ISSUE TITLE
msbuild -t:pack command, the project references (non-nuget package references) in a .Net class library (csproj) are included in dependencies for the package. 

### ISSUE THREAD

**Issue by npickett** [NuGet/Home#7623]
## Details about Problem

When using msbuild -t:pack command, the project references (non-nuget package references) in a .Net class library (csproj) are included in dependencies for the package. 

VERSIONS
=======
MSBuild Version: 15.8.169+g1ccb72aefa
Powershell Version: 5.1.17134.407 
OS version: Windows 10 v1803 (OS  Build 17134.407)

## Detailed repro steps so we can see the same problem

1. Open Powershell window
2. Change directory in NugetPackLibrary
3. Run this command below:

$msbuildPath = "[PathOfYourMSBuildBinFolder]";
$name = "NugetPackLibrary.csproj";
$packageId = "NugetPackLibrary";
$authors = "Test";
$packageVersion = "1.0.0.1";

// Nuget Restore on the project
& $msbuildPath\msbuild.exe -t:restore $name;

// Create the nuget package
& $msbuildPath\msbuild.exe -t:Pack $name; -p:Configuration="Release" -p:IncludeSource=true -p:IncludeSymbols=true -p:PackageOutputPath="." -p:PackageId=$packageId -p:Authors=$authors -p:PackageVersion=$packageVersion 

4. Review NugetPackLibrary.nuspec within generated nuget package NugetPackLibrary.1.0.0.1.nupkg

### Verbose Logs
EXPECTED RESULTS
================

Expect that NugetPackDirectProjectRef project would NOT be a dependency, instead contained/compiled into NugetPackLibrary assembly. 

NUGET SPEC FILE
===============
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>NugetPackLibrary.Signed</id>
    <version>1.0.0.1</version>
    <authors>KGS Buildings</authors>
    <owners>KGS Buildings</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.5.2">
        <dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Data.DataSetExtensions" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Data" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Xml.Linq" targetFramework=".NETFramework4.5.2" />
    </frameworkAssemblies>
  </metadata>
</package>
```

ACTUAL RESULTS
==============

NugetPackDirectProjectRef project is included as a dependency, expected to be contained/compiled into NugetPackLibrary assembly and not to be a dependency. 

NUGET SPEC FILE
===============
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>NugetPackLibrary</id>
    <version>1.0.0.1</version>
    <authors>Test</authors>
    <owners>Test</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.5.2">
        <dependency id="NugetPackDirectProjectRef" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="12.0.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Data.DataSetExtensions" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Data" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.5.2" />
      <frameworkAssembly assemblyName="System.Xml.Linq" targetFramework=".NETFramework4.5.2" />
    </frameworkAssemblies>
  </metadata>
</package>
```

### Sample Project

[NugetPackLibrary.zip](https://github.com/NuGet/Home/files/2669153/NugetPackLibrary.zip)

**Comment by jainaashish** [comment]
Project to project references are considered by default as nuget package references, which is why these are included in generated nupkg file. But you can set `PrivateAssets=All` on this ProjectReference to exclude it from being added as nuget reference in resulted nupkg.

**Comment by npickett** [comment]
Perfect, thank you for the response.  Added `PrivateAssets=All` and the referenced project `NugetPackDirectProjectRef` is now removed from the  dependencies.
