### ISSUE TITLE
way to list packages from command line?

### ISSUE THREAD

**Issue by kfalkowski11** [NuGet/Home#7624]
Trying to automate getting a list of our package license information through a continuous integration tool (jenkins). We are using the Get-Package powershell command but we currently have to do this through the Visual Studio Package Manager Console. Was hoping for a way to execute this command outside of Visual Studio, either using visual studio command line or nuget.exe?

**Comment by jainaashish** [comment]
You can use `dotnet list package` command to get the similar experience. Design spec# https://github.com/NuGet/Home/wiki/dotnet-list-package 

Soon (in next couple of days), we're going to update [dotnet list docs](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-reference) to explain this new feature as well.
