### ISSUE TITLE
Release Notes for 4.9.2

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#7626]
I saw that NuGet 4.9.2 was released but couldn't find any release notes for it [here](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm).

**Comment by jainaashish** [comment]
@anangaur can you take care of this?

**Comment by eriawan** [comment]
@pascalberger 
 
Release notes for 4.9.2 is available now: https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm#summary-whats-new-in-492

Could you please close this issue?

cc @jainaashish
