### ISSUE TITLE
Creating ASP.NET Web Application (that uses the template wizard) does not work when the assembly is not signed

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7627]
## Details about Problem
VS Version: D16.0 28410.60
OS Version: 17763.RS5_Release.180914-1434.
NuGet Version: Dev-nkolev92-fixlnteropBuild\Local
## Detailed repro steps
1. Launch VS.
2. Create a new ASP.NET Web Application (.NET Framework) project.
## Expected 
The project should be created correctly.
## Actual
Nothing created as below screenshot.
![created failed](https://user-images.githubusercontent.com/40230425/49859024-797eb600-fe31-11e8-9418-f29a3f747190.PNG)
## Notes
1. The issue also repro on all Web Site templates.
2. The issue does not repro on ASP.NET Core Web Application.
3. The issue does not repro before installing NuGet Client Dev-nkolev92-fixlnteropBuild\Local

**Comment by nkolev92** [comment]
This is an issue because the VSIX is not signed. 
The template tries to load a signed version of the interop assembly which obviously does not exist in this case. 

Note that this is known, and if you try to do the same thing with a VSIX from 2 months, you'd see the same behavior. 

A signed VSIX sohuld fix it.

**Comment by nkolev92** [comment]
I want to leave this issue open for tracking, so we can check if this ever worked. I will fix the issue title. 

This effecrtively means that you can't create an ASP.NET Web App in .NET Framework within the experimental instance.

**Comment by v-longmin** [comment]
@nkolev92 The issue does not repro on D16.0 28414.68 + NuGet Client Dev\5.0.0.5728.

**Comment by nkolev92** [comment]
@v-longmin 
The issue is not a product bug, rather whether the VSIX was signed or not signed. 
It is only about improving the day-to-day workflows of the team.
