### ISSUE TITLE
Cannot publish symbol package for .NET Core Global Tool

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#7632]
This was a bug where the PackageTypes were not being cleared for the snupkgs.
The snupkgs can/should only contain 1 package type, which is not combinable with other package types (similar to DotnetTool).

Original Comment text:
This is a copy of issue: 
https://github.com/NuGet/NuGetGallery/issues/6743
As discussed the pack command for snupkg will ignore all the packageTypes but SymbolsPackage.

**Comment by nkolev92** [comment]
Reopening because it hasn't been merged to 4.9.3. 

@rrelyea Waiting for your call about that.

**Comment by nkolev92** [comment]
Fixed. 

https://github.com/NuGet/NuGet.Client/commit/add8b695e842e2b6f4b07f804d1f5e55406dd843
