### ISSUE TITLE
project.assets.json with invalid targets generated in case of different target platforms on different configurations

### ISSUE THREAD

**Issue by lorond** [NuGet/Home#7634]
## Description
When AnyCPU set on Debug configuration and x64 on Release configuration there is no way no generate `project.assets.json` with valid `targets` other then set x64 on Debug configuration too.

## Environment
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe
NuGet version (x.x.x.xxx): 4.7.1.5393
dotnet.exe --version (if appropriate): 2.1.502
VS version (if appropriate): 15.9.4
OS version (i.e. win10 v1607 (14393.321)): win10 v1703 (15063,1446)
MsBuild version: 15.9.21.664

## Detailed repro steps
1. Create new solution with console project like this:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <RootNamespace>Test</RootNamespace>
    <AssemblyName>Test</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="$(Platform) == 'x64'">
    <PlatformTarget>x64</PlatformTarget>
    <!--<RuntimeIdentifier>win7-x64</RuntimeIdentifier>--> <!-- does not help -->
  </PropertyGroup>

</Project>
```

2. Configure to build AnyCPU on Debug and x64 on Release configuration, sln something like this:
```
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{proj_guid}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{proj_guid}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{proj_guid}.Release|Any CPU.ActiveCfg = Release|x64
		{proj_guid}.Release|Any CPU.Build.0 = Release|x64
	EndGlobalSection
```

When you build solution form VS, valid `project.assets.json` generated during restore:
```
  "targets": {
    ".NETFramework,Version=v4.7.1": {},
    ".NETFramework,Version=v4.7.1/win7-x64": {}
  },
```

But when you restore with `dotnet restore test.sln`, invalid `project.assets.json` generated - x86 instead of x64:
```
  "targets": {
    ".NETFramework,Version=v4.7.1": {},
    ".NETFramework,Version=v4.7.1/win7-x86": {}
  },
```

So it makes impossible to build such project outside of VS:
`C:\Program Files\dotnet\sdk\2.1.502\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198, 5): error NETSDK1047: Assets file 'C:\TeamCity\buildAgent\work\1e1431a3f4256377\src\Service\obj\project.assets.json' doesn't have a target for '.NETFramework,Version=v4.7.1/win7-x64'. Ensure that restore has run and that you have included 'net471' in the TargetFrameworks for your project. You may also need to include 'win7-x64' in your project's RuntimeIdentifiers.`

With `-r win7-x64` flag x86 target still generated.
The only solution we found is to make x64 for Debug build configuration.
But either AnyCPU or x86 is required in Debug configuration because that project is used in T4, which is x86 tool.

test project: [test.zip](https://github.com/NuGet/Home/files/2675968/test.zip)

**Comment by lorond** [comment]
And when project is not selected to be built for Debug configuration but selected for other, file `project.assets.json` not generated at all.

**Comment by jainaashish** [comment]
In your current repro, If I build/restore with `Debug` configuration, then It has `win7-x86` target from either VS or dotnet commandline. And if build/restore with `Release` configuration then it has `win7-x64` target from both VS or dotnet commandline.

Now, if you want the `win7-x64` target for both `Debug` and `Release` configuration then set `<RuntimeIdentifier>win7-x64</RuntimeIdentifier>` in top `PropertyGroup` (without Platform condition).

Other than this, I'm not able to understand what you really want to do here. And what's the issue?

**Comment by lorond** [comment]
I fount no information about passing msbuild parameters to dotent cli neither in cli help nor in msdn. Didn't expect it possible.

It works fine with `/p:Configuration=Release`. However it worth to note somewhere about passing msbuild parameters and so on.

@jainaashish I guess issue could be closed.
