### ISSUE TITLE
Take 1CS assessment and complete tasks for Dev16

### ISSUE THREAD

**Issue by chenriksson** [NuGet/Home#7636]
Date | Action
-- | --
Dec 10 through Jan 22 | Take 1CS assessments   Review & complete the   generated tasks
Jan 22 | Tenet Checkpoint   All tenet work identified, costed, and scheduled to be   done by Dev16 GA.   All known exceptions   anticipated for GA are logged.
Feb 26 | Sign-off on tenets   All tenet work complete.   All exceptions signed off.

Next Steps 
1.	Review the requirements for Compliance Tenets on the DevDiv Tenet wiki (https://aka.ms/DevDivTenets). 
2.	Go to the [1CS Compliance Tool](https://aka.ms/devdivtenets/Dev16Compliance), and complete an assessment for your Dev16 product area.
3.	The Assessment will generate Tasks for your team to complete. Follow the instructions in the created Tasks to complete them.
4.	If you need an exception, follow the instructions on the “Exceptions for Tenets” page on the DevDiv Tenet wiki. (https://aka.ms/devdivtenets/exceptions) 
5.	Sign off by 
a.	Setting the Tasks to Completed
b.	Setting the User Stories for each policy to Completed.
c.	Setting the Assessment for your product area to Completed.

**Comment by rrelyea** [comment]
thx.
