### ISSUE TITLE
Package is stuck in validation for hours

### ISSUE THREAD

**Issue by XtroTheArctic** [NuGet/Home#7641]
Package is stuck in validation for hours :(

https://www.nuget.org/packages/Atesh.BindableProperties

**Comment by nkolev92** [comment]
This issue was moved to NuGet/NuGetGallery#6770

**Comment by loic-sharma** [comment]
Hello @XtroTheArctic, there was an issue with our package publishing pipeline that caused delays two days ago. This should be fixed now!
