### ISSUE TITLE
NuGet should not print project path during restore with minimal logging

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#7647]
So during global tools install when `--verbosity:minimal` the output does not contain temp project's path. nuget can identify temp project by using `RestoreProjectStyle` being `DotnetToolReference`

@rrelyea @nkolev92 action item from 12/17/2018 meeting

**Comment by nkolev92** [comment]
@wli3 
We can probably suppress the full message if we wanted to. 

We can discuss when we get to the implementation.

**Comment by wli3** [comment]
> We can probably suppress the full message if we wanted to.

That's also fine or even better. Maybe whatever is easier to implement

**Comment by nkolev92** [comment]
Note that this change is "related" to https://github.com/NuGet/Home/issues/4695. 

That other issue needs done as before this will be considered complete.

**Comment by wli3** [comment]
Any update on this issue?

**Comment by nkolev92** [comment]
@wli3 
I will try to address it for preview 3 (will probably pick it up next week).

**Comment by wli3** [comment]
Any update?

**Comment by nkolev92** [comment]
What's the matching CLI version for this @wli3?

**Comment by wli3** [comment]
3.0.1xx or master
