### ISSUE TITLE
Typo in logging

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#765]
Removed file 'AutoMapper.3.3.0.nupkg' to folder 'C:\Source\MyProject\src\..\lib\AutoMapper.3.3.0'.

Should be "from" instead of "to"

**Comment by yishaigalatzer** [comment]
Thanks!

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik I also noticed a `..` in the middle there, can you give us more details on your setup and commands, we might have a bug in combining the paths.

**Comment by GeertvanHorrik** [comment]
This might be related to just concatting strings in the paths instead of using Path.Combine. This is because we use a customized nuget.config:

```
<configuration>
  <config>
    <add key="repositoryPath" value="../lib" />
  </config>
</configuration>
```

**Comment by yishaigalatzer** [comment]
That's what I thought. 

Note that `Path.Combine` doesn't do that magic, you need to code this yourself or use `GetFullPath`

What is the exact operation you are doing in the UI?

**Comment by GeertvanHorrik** [comment]
I was uninstalling a package (I use an existing project, removed what I didn't need).

**Comment by yishaigalatzer** [comment]
We got a fix :) Thanks!
