### ISSUE TITLE
[Bug Bash][Test Failure]The web page of https://github.com/wwizz/CrossBase cannot be found when clicking the link of Project URL

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7650]
## Details about Problem
VS Version: D16.0stg 28417.07
OS Version: 17763.RS5_Release.180914-1434.
NuGet Version: Dev\5.0.0.5728
## Detailed repro steps 
1. Launch VS and create a new C# iPad Blank App project.
2. Build Solution and open PM UI in Explorer Solution window.
3. Search ‘CrossBase’ in the filter of Browse tab and click a searched package.
4. Click the link of Project URL: https://github.com/wwizz/CrossBase on the right panel.
## Excepted
The web page of https://github.com/wwizz/CrossBase should be opened successfully.
## Actual
The web page of https://github.com/wwizz/CrossBase cannot be found when clicking the link of Project URL as below screenshot.
![webpage](https://user-images.githubusercontent.com/40230425/50145756-3a4adc00-02ed-11e9-9912-7d4089484610.PNG)

**Comment by nkolev92** [comment]
I don't get why this is a bug. 

The github project either doesn't exist or was somehow made private.
Use a  different package to verify that the project url is clickable and leads to a real web page.
