### ISSUE TITLE
PackageReference output missing libs

### ISSUE THREAD

**Issue by aarongomez1** [NuGet/Home#7652]
I have a custom nuget package that contains multiple DLLs.   When this package is consumed, I only want one of the DLLs, MyA.dll, to be referenced by the project.  However when I build I need all of my DLLs in the package to go to the build output folder.

Assume I have DLLs named MyA, MyB, MyC, MyD, MyE, and MyF

My nuspec looks like:

`<?xml version="1.0"?>`
`<package >`
`  <metadata>`
`    <id>My.ThirdParty.Package</id>`
`    <version>1.2.3</version>`
`     ...`
`     <references>`
`         <group targetFramework="net40">`
`             <reference file="MyA.dll" />`
`          </group>`
`     </references>`
`   </metadata>`
`   <files>`
`     <file src="My*.dll" target="lib\net40" />`
`  </files>`
`</package>`

When I use this package from a project using the _packages.config_ style.  Everything works.  I see that it only added the single reference to MyA.dll in my list of references.  When I build all of the DLLs are in my output folder, MyA through MyF.

If I then clear my output folder, migrate it to a _PackageReference_ style, and do a build, only MyA.dll is copied to the output folder.   I need MyA through MyF to be copied in this case just like it worked the old way.

I'm running NuGet Version: 4.5.1.4879
Visual Studio Enterprise 2017 Version 15.9.4

**Comment by adamgauthier** [comment]
I believe this issue is a duplicate of https://github.com/NuGet/Home/issues/3830

**Comment by rrelyea** [comment]
Closing as dupe.
