### ISSUE TITLE
Incorrect version restored on MSBuild sdk.proj

### ISSUE THREAD

**Issue by jcagme** [NuGet/Home#7654]
**sdk.proj**
```
<Project Sdk="Microsoft.DotNet.Arcade.Sdk"/>
```
[NuGet.config](https://github.com/dotnet/arcade-validation/blob/master/NuGet.config)
[global.json](https://github.com/dotnet/arcade-validation/blob/master/global.json)

In *random* occasions when running `MSBuild sdk.proj` the incorrect version of `Microsoft.DotNet.Arcade.Sdk` is restored as it always restores `1.0.0-dev.18424.13` and not what is defined in `global.json`.

An example of this is: https://dnceng.visualstudio.com/internal/_build/results?buildId=61204. Windows_NT Debug leg did the correct thing and restored `1.0.0-beta.18619.3` while the Release leg restored `1.0.0-dev.18424.13` even though the setup code is the same. Same happened for Validate_sign Test leg vs Real.

https://github.com/dotnet/arcade-validation is based of https://github.com/dotnet/arcade and so far this issue have not presented in arcade so probably I'm missing some setting in arcade-validation.

**Comment by rainersigwald** [comment]
@jeffkl This looks an awful lot like the NuGet SDK resolver is pulling the wrong version, but I can't see any obvious reason why. Seen anything like that before?

**Comment by jeffkl** [comment]
I haven't seen this.  Everything looks correct but the resolver is pulling the wrong version

https://dnceng.visualstudio.com/_apis/resources/Containers/870779?itemPath=Windows_NT_Build_Release%2FToolsetRestore.binlog

![image](https://user-images.githubusercontent.com/17556515/50250214-0925e680-0395-11e9-98cc-2e25f355ced0.png)

I thought maybe something was cached but I don't see any previous references to the bad version `1.0.0-dev.18424.13`.  The first place to look would be the NuGet API so this issue is in the correct place.

**Comment by nkolev92** [comment]
I don't have access to the resource to look into this. 
But it does seem really odd. This has been a relatively stable part of the product with minimal changes in the 4.x release. Not sure what's going on here, so any extra information is appreciated.

**Comment by jcagme** [comment]
It is odd indeed. also, i don't know what other details to share than those above. Last thing we tried was to bump the dotnet version from 2.1.3 to 2.1.401 but I checked and I found one build where this repro'ed even with the new version.

**Comment by ghost** [comment]
Hi. This is still happening sporadically for us. What kind of extra details would you like us to provide?

There were some access issues to the previously provided build. Can you access this one: https://dnceng.visualstudio.com/public/_build/results?buildId=67983,  where the `Windows_NT Build_Debug` job failed?

We also use our own build machines, so if you'd like us to provide something from one of the machines where we are seeing this, we can also do that.

**Comment by nkolev92** [comment]
@riarenas 
Can you get us the bin log?

**Comment by ghost** [comment]
Sure! https://riarenashelixresults.blob.core.windows.net/test-storage/Windows_NT_Build_Debug.zip

**Comment by nkolev92** [comment]
@riarenas 
I don't see a restore bin log in the zip you added. 
The toolset restore named file is actually a different target. WriteToolsetLocation.

**Comment by nkolev92** [comment]
Did this happen ever again? 
Anyfurther info to help NuGet & MSBuild investigate?

**Comment by ghost** [comment]
This stopped happening. Feel free to close.
