### ISSUE TITLE
How to list the packages of unlisted packages in nuget.org using commands

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7655]
Hi Everyone, 

I have published my some of the packages in nuget.org and also Unlist that packages. i want to list these packages back to show the packages while searching the packages in nuget.org. Currently I have do this manually from nuget.org site. But I want to do through the commands to reduce the manual process. Because from my side I need to list lots packages from my side. So, if it's manual process means, it will take more time to me. 

Please suggest me regarding this, How can I list the packages in nuget.org using commands.

Thanks,
Ganesan R.

**Comment by GanesanRengasamy** [comment]
Hi, 

Any update on this?

**Comment by GanesanRengasamy** [comment]
Hi Everyone,

Could you please suggest the solution regarding this?

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
Try https://docs.microsoft.com/en-us/nuget/tools/cli-ref-list. 

Note that this command is using old server APIs that have shown to be inconsistent across servers.

**Comment by GanesanRengasamy** [comment]
Hi @nkolev92 ,

I want to relist the packages which are already unlisted in the nuget.org. I have posted the query regarding this. Could you please reopen the issue and provide the solution.

**Note:** I can't understand your procedure that how can close the issue without waiting for the customer reply like whether the reported issue resolved or not.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
That's not possible with the commandline tools.
You have to do it manually relist them on nuget.org.

**Comment by GanesanRengasamy** [comment]
Hi @nkolev92 ,

If we relist the 10 packages means manual process is possible. But if we need to relist the more than 500 packages means, the manual process is very critical.

https://docs.microsoft.com/en-us/nuget/api/package-publish-resource#relist-a-package

Also, I have found the command for relist the packages from above link. But this is not working. Is this POST command available in old version nuget.exe only and Is there any possible to provide the relist option in latest nuget.exe.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
@GanesanRengasamy 

As far as I am aware, that has never made it into the nuget.exe client. 
What you are looking at is the documentation of the protocol. 

Regarding why the post request is not unlisting it, I'm not able to help you with that. 
But if you file an issue at https://github.com/NuGet/NuGetGallery/issues, specifically asking for that, they might be able to help. 

Regarding the client request of a relist functionality, here's the tracking number https://github.com/NuGet/Home/issues/6329

**Comment by GanesanRengasamy** [comment]
Hi @nkolev92,

Is there any possible to add the relist option in nuget.org client.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
See the edit of my last comment. 

> Regarding the client request of a relist functionality, here's the tracking number #6329

We have a tracking issue, but it's not a high priority currently.
