### ISSUE TITLE
nuget pack on csproj files doesn't work in tfs

### ISSUE THREAD

**Issue by mikeholcomb** [NuGet/Home#766]
Porting issue 3645 from http://nuget.codeplex.com/workitem/3645
## 

I use the nuget pack command inside msbuild to create nuget packages during tfs build

``` xml
    <Target Name="AfterBuild">
      <Exec WorkingDirectory="$(OutputPath)" Command="$(NuGetCommand) pack "%(ProjectReference.FullPath)" -BasePath "$(OutputPath) " -Exclude **\*.xml -Verbosity detailed" />
    </Target>
```

This works great in visual studio, but in tfs the outputpath of the csproj changes so this error occurs:

```
NuGet.CommandLineException: Unable to find 'd:\Builds\18\232\src\Foo\Binaries\Debug\Foo.dll'. Make sure the project has been built.
            at NuGet.Commands.ProjectFactory.BuildProject()
            at NuGet.Commands.ProjectFactory.CreateBuilder(String basePath)
            at NuGet.Commands.PackCommand.BuildFromProjectFile(String path)
            at NuGet.Commands.PackCommand.BuildPackage(String path)
            at NuGet.Commands.PackCommand.ExecuteCommand()
            at NuGet.Commands.Command.Execute()
            at NuGet.Program.Main(String[] args)
```

The correct path would be d:\Builds\18\232\bin\Foo.dll which is defined by tfs in $OutDir 
So I tried to workaround by adding this to the csproj file:

``` xml
<PropertyGroup Condition="$(OutDir) != '' ">
    <OutputPath>$(OutDir)</OutputPath>
</PropertyGroup>
```
## 

This normally solves the problem but nuget pack still tries to find the files in binaries\debug so it seems it doesn't really use the msbuild outputpath variable.

**Comment by mikeho-msft** [comment]
I'm still seeing this issue in Nuget 2.8.3 & 2.8.5

**Comment by yishaigalatzer** [comment]
```xml
<BuildCommand>$(NuGetCommand) pack "$(ProjectPath)"  $(NonInteractiveSwitch) -OutputDirectory "$(OutDir) " -Symbols -Prop Configuration=$(Configuration);OutputPath="$(OutDir) " </BuildCommand>
```

You probably want to make changes to the target files yourself, we can take a look at fixing the nuget build package

**Comment by mikeho-msft** [comment]
I've tried setting OutputPath to $OutDir and that fails as well.  I don't have logs for that failure, but I'll try to build a repro.

**Comment by yishaigalatzer** [comment]
At the end of the day, this is nothing more than running an msbuild script around nuget.exe, you should be able to deal with it, it has very little to do with NuGet itself (other than the fact that our build package doesn't work well). You can simply call nuget.exe from a post build step yourself as well.

**Comment by yishaigalatzer** [comment]
From chatting with folks, this was supposed to be fixed with newer builds of team build.

**Comment by yishaigalatzer** [comment]
@mikeholcomb was this issue resolved for you?

**Comment by AngryMikey** [comment]
I no longer have a repro.  I went ahead and created a .nuspec file.

**Comment by kstrauss** [comment]
this still seems to be an issue.

However, I believe changing the default nuget.targets for the properties passed to the nuget pack command. Added the OutputPath property. So my specific fix for me was something like:

```
<!-- original command -->
<!--
<BuildCommand>$(NuGetCommand) pack "$(ProjectPath)" -Properties "Configuration=$(Configuration);Platform=$(Platform)" $(NonInteractiveSwitch) -OutputDirectory "$(PackageOutputDir)" -symbols</BuildCommand>
-->
<!-- Added so that the nuget pack command will use the output directory of where tfs will put things -->
<BuildCommand>$(NuGetCommand) pack "$(ProjectPath)" -Properties "Configuration=$(Configuration);Platform=$(Platform);OutputPath=$(PackageOutputDir)" $(NonInteractiveSwitch) -OutputDirectory "$(PackageOutputDir)" -symbols</BuildCommand>
```

Seems to fix the problem for me

Credit to: http://nuget.codeplex.com/workitem/3645

**Comment by contento** [comment]
I wonder if it is possible to up the priority of this bug. I have tried so many workarounds (@kstrauss) in TFS to no avail. I know that we are going to find ways "to deal with" but, IMHO, this is supposed to be a simple build task with no hacks or long Google/Stackoverflow searches. Not sure, if it's because not that many developers use TFS (?).

**Comment by am11** [comment]
I was just having a similar issue with [libsass-net](https://github.com/sass/libsass-net) and fixed it after getting ideas from this thread. Thanks everyone! :)

We have:

```xml
<OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>
```

in out csproj file. The fix was

```cmd
:: to change:
nuget pack "LibSass.NET\LibSass.NET.csproj" -Properties Configuration=Release

:: to
nuget pack "LibSass.NET\LibSass.NET.csproj" -Properties "Configuration=Release;SolutionDir=..\"
:: or elaborately:
:: SolutionDir=%cd%\
:: in cmd,
:: SolutionDir=$pwd\
:: in Unix Shell or PowerShell
```

basically specifying the `SolutionDir` and `Configuration`. More generally, we need to specify all MSBuild variables the `OutputPath` (in .NET projects, or `OutDir` in C++ projects) string is relying on.
