### ISSUE TITLE
silence nuget feeds used

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7662]
_From @apobekiaris on December 25, 2018 16:1_

### Steps to reproduce

Run on any project the next command

```
msbuild Xpand.Utils.csproj /v:m
```
### Expected  behavior
I would like to stop nuget polluting my logs with repeat information. Think a many projects solution you repeatably get the feeds used per project as I posted in the actual behaviour  

### Actual behavior
```
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

          1 file(s) moved.
  Feeds used:
    C:\Users\Tolis\.nuget\packages\
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    C:\Program Files (x86)\DevExpress 18.2\Components\System\Components\Packages
    C:\Program Files (x86)\DevExpress 18.2\\Components\System\Components\packages
    https://xpandnugetserver.azurewebsites.net/nuget

  All packages listed in C:\Work\eXpandFramework\expand\Xpand\Xpand.Utils\packages.config are already installed.
  Xpand.Utils -> C:\Work\eXpandFramework\expand\Xpand.DLL\Xpand.Utils.dll
```

### Environment data
15.9.20.62856

_Copied from original issue: Microsoft/msbuild#4030_

**Comment by nkolev92** [comment]
@apobekiaris 
That message is only logged on normal verbosity not minimal. 

Furthermore not sure where the "\packages.config are already installed." is coming from as msbuild restore does not handle packages.config.

How are you actually restoring?

**Comment by apobekiaris** [comment]
@nkolev92 thanks for the pointer, looks like there was an hidden explicit nuget call in on Import, probably from old ages. I remove it and now I am fine.

**Comment by nkolev92** [comment]
Thanks for following up. 

Closing thi as resolved.
