### ISSUE TITLE
 Unable to find version 2.0.20525 of package 'expression-interactivity': Failed to restore Missing Nuget Package

### ISSUE THREAD

**Issue by boudinekirrou** [NuGet/Home#7663]
Hi,
i have an issue to restore NuGet Package, when i click retore it give me the following error: AN ERROR occured while trying to restore packages: Unable to find version 2.0.20525 of package 'expression-interactivity'
see attached screen
i'm using the source: https://api.nuget.org/v3/index.json

thanks
![error nuget](https://user-images.githubusercontent.com/15870461/50449025-e8c1d300-0924-11e9-9c53-9065168dc382.PNG)

**Comment by nkolev92** [comment]
@boudinekirrou 

The package does not exist on nuget.org. 

See https://www.nuget.org/packages/expression-interactivity. 

I don't think there's an issue here. The package simply is not there.

**Comment by boudinekirrou** [comment]
Thanks a lot for your reply. i fixed the issue.
