### ISSUE TITLE
dotnet`s error with credentials for nuget feed

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7664]
_From @1scrooge on December 26, 2018 12:56_

After updated dotnet up to 2.1.502 and uper I have an error with credentials for nuget feed when I using apikey
```
/usr/share/dotnet/sdk/2.1.502/NuGet.targets(499,5): error : Unable to parse config file because: Credentials item must have username and password. Path: '/home/user/.nuget/NuGet/NuGet.Config'
```
my NuGet.Config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
   <packageSources>
        <add key="name_feed" value="http://url_feed/nuget" />
    </packageSources>
    <packageSourceCredentials>
        <name_feed>
           <apikeys>
             <add key="http://url_feed/nuget" value="qwd32dqwd231vdas13" />
           </apikeys>
        </name_feed>
    </packageSourceCredentials>
</configuration>
```
on 2.1.403 version works fine
Could you fix it?

_Copied from original issue: dotnet/sdk#2773_

**Comment by nkolev92** [comment]
@1scrooge How did you generate that config file? 

The config file doesn't look right and I don't think it'll be used by any NuGet version. 

It's possible that the parsing became more restrictive than before but that wouldn't necessarily make it correct. 

//cc @PatoBeltran

**Comment by 1scrooge** [comment]
@nkolev92 From there https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections

**Comment by nkolev92** [comment]
Did you create it manually? 
The apikeys section should not be in the packagesorucecredentials section. 

It should be something like the following: 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
   <packageSources>
        <add key="name_feed" value="http://url_feed/nuget" />
    </packageSources>
     <apikeys>
        <add key="http://url_feed/nuget" value="qwd32dqwd231vdas13" />
     </apikeys>
</configuration>
```

It's best if you add the API keys using the [setapikey](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-setapikey) nuget cli command.

**Comment by 1scrooge** [comment]
@nkolev92 thank you. it helped, but strange how it worked on version 2.1.403

**Comment by nkolev92** [comment]
I'm not confident it ever work, you might have just been getting lucky :)

I double checked 2.1.4xx(4.8 nuget) and 2.1.5xx(4.9 nuget) behave the same when you use the setapikey command.
