### ISSUE TITLE
Deprecation of 'any'

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#767]
Recent discussions indicate that the 'any' concept is being deprecated in nuget3.
* Lib\foo.dll convention -> already deprecated in nuget3
* Lib\any\foo.dll convention -> soon to be deprecated

The following seem like they also need to be deprecated for consistency.  Otherwise folks are bound to create packages that have inconsistent authoring.
* dependencies/dependency@id 
* dependencies/group (no targetFramework)
* references/reference
* references/group (no targetFramework)
* frameworkAssemblies/frameworkAssembly (no targetFramework)

**Comment by yishaigalatzer** [comment]
Duplicate of #496 + #749
