### ISSUE TITLE
Is there any way to install a NuGet package so its version is not added to the project file?

### ISSUE THREAD

**Issue by Prologh** [NuGet/Home#7670]
## Details about Problem

NuGet product used: Package Manager Console

NuGet version: NuGet Command Line 4.9.2.0

Visual Studio: Community 15.9.4

dotnet.exe --version: 2.2.101

OS version: Windows 10 Education N  1703 version

## Question

Is there any way to install a NuGet package so its version does not get saved in the project file? For example if I run `install-package Microsoft.AspNetCore.App` from Package Manager Console, a following line will be added to my project file:

```
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0" />
```

Instead, I would like only this to be added:

```
<PackageReference Include="Microsoft.AspNetCore.App" />
```

If I manually paste a package reference line without a version inside a project file and then restore the whole project, it works fine, so I think the same could be achieved via console. Sadly, I failed to find a relevant CLI setting on my own.

**Comment by PatoBeltran** [comment]
Hey @Prologh, our tools currently don't have a way to achieve this. As you said, the best way to do it would be to manually add the PackageReference to your project file and then restore the project.

**Comment by Prologh** [comment]
Hello @PatoBeltran. Thanks for the response. I now feel a little let down knowing that, but just a little. All I wanted to do is to perform the trick via console, without getting my hands dirty by manually tweaking over project files. Still, this is not a great tragedy after all. I don't have any more questions, so you are free to close this issue if you want to.
