### ISSUE TITLE
Error creating new multi-platform project

### ISSUE THREAD

**Issue by JMCasablanca** [NuGet/Home#7671]
I just installed the NuGetizer-3000 extension, version 0.2.13 on Visual Studio 2017 CE, version 15.9.4. I am getting these errors when attempting to create a new multi-platform project or solution. Screen prints and sample project are attached.

**First error screen:**

Package Installation Error
Could not add all required packages to the project. The following packages failed to install from 'C:\Users\Justo.Casablanca\AppData\Local\Microsoft\VisualStudio\15.0_f8b5faf1\Extensions\ra1d4gn3.dob\Packages':

NuGet.Build.Packaging.0.2.5-dev.8 : Package restore failed. Rolling back package changes for 'Library4.NuGet'.

**Second error screen:**

The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

[NuGetizer-3000 New Project Error Screen Prints.pdf](https://github.com/NuGet/Home/files/2725647/NuGetizer-3000.New.Project.Error.Screen.Prints.pdf)
[Library4.zip](https://github.com/NuGet/Home/files/2725648/Library4.zip)

**Comment by PatoBeltran** [comment]
@kzu

**Comment by alex-relov** [comment]
When creating a new project I get errors
![image](https://user-images.githubusercontent.com/26199529/53144583-a6341400-35be-11e9-9851-65a1648f01cf.png)
![image](https://user-images.githubusercontent.com/26199529/53144595-b3e99980-35be-11e9-817e-d4211c778a1b.png)
VS2017 15.9.5
NuGetizer3000-VS2017 0.2.13

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

You can use a [packaging project](https://www.clarius.org/nugetizer/#packaging-projects) supported out of the box by Visual Studio and NuGetizer.
