### ISSUE TITLE
Cleanup CS0618 - obsolete API warnings from InteractiveLoginProvider

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7676]
Class in question src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/InteractiveLoginProvider.cs

**Comment by kartheekp-ms** [comment]
Follow-up for https://github.com/NuGet/Home/issues/8577 issue.  We removed `VisualStudioAccountProvider` from the repo in https://github.com/NuGet/NuGet.Client/pull/4482 PR. However, I forgot to remove NuGet's implementation of `InteractiveLoginProvider` which is causing some RPS test failures for VS Team explorer team. `InteractiveLoginProvider` implementation in partner team's repo can be found in this [internal link](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VSTeamExplorer?path=/VSIntegration/Client/Nuget/CredentialProvider/InteractiveLoginProvider.cs). cc @crmann1 @clboles

https://github.com/NuGet/NuGet.Client/search?q=InteractiveLoginProvider
![image](https://user-images.githubusercontent.com/52756182/161804534-f5f89ad3-bda7-4864-8378-eec2baf60143.png)
