### ISSUE TITLE
'dotnet' is not applicable to correct set of targets

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#768]
Currently 'dotnet' is not treated as applicable to the correct set of targets.  We want this to be applicable to everything except the following:
[net, net45) (note: exclusive)
[sl, sl5]
[wp, wp8) (note: exclusive)
[xbox]
[netmf]
[cf]

**Comment by yishaigalatzer** [comment]
Need more discussion with @ericstj on what is actually required here.

**Comment by ericstj** [comment]
Right now we agree that all of the previous listed explicit TFMs should not be compatible with dotnet.  I think we can move forward with that part of the implementation.

There is some contention on the behavior of portable-a+b+c (the combined TFMs).  
1. One option is to not support these at all.  That would mean that folks need to rebuild their packages, even if the set of TFMs in their list are all compatible with dotnet.  
2. Another option would treat portable-a+b+c as considered compatible with dotnet so long as a, b, and c are all compatible with dotnet.  

Option 2 does mean that we'd install a package without its contract dependencies since these old packages wouldn't have been built against the System.Runtime, etc packages, but at least we wouldn't be getting in the way of something that ought to work.  It also provides a path forward for existing packages.

**Comment by anurse** [comment]
To be clear, we ALSO need to add a rule that says that any TFM **not** in the block-list **is** compatible with `dotnet`. For example, `frob5.8.1` is compatible with `dotnet` :).

Given that, we should add all the Xamarin/Mono frameworks to the block list **for now** until we know for sure they will be supported. Also, the `native` psuedo-tfm should be in the block list

**Comment by anurse** [comment]
Assigned to @emgarten after discussion with @yishaigalatzer . Feel free to follow up.

**Comment by emgarten** [comment]
A fix for this is available in: https://github.com/NuGet/NuGet3/pull/68

All known frameworks that aren't explicitly blocked will allow installs of packages containing dotnet libraries.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet3@c8eacbec5209f1e5299c47e46ed1f46abe46144b
