### ISSUE TITLE
[Test Failure][Client policy] No error occur when the trusted author name in ‘NuGet.config’ is different with the “Authors” in the package’s nuspec file 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7681]
## Details about Problem
VS Version: D16.0stg 28508.124
NuGet Version: Dev\5.0.0.5759
OS Version: 17763.RS5_Release.180914-1434.
## Detailed repro steps 
1. Launch Visual Studio 2019 d16.0stg.
2. Create a new Class Library (.Net Framework) project and build Solution.
3. Go to the path: C:\Users\v-minlon\source\repos\Package34\Package34, create the package’s nuspec file, edit “Authors” to “Aimee” in the nuspec file and sign this package.
4. Go to the path: C:\Users\v-minlon\AppData\Roaming\NuGet and edit “Author name” to “JamieZhang” in the NuGet.config file.
5. Reload the solution, update the package source to the above package path (step3), and install the package into the project in PM UI and CLI.
## Expected
Error NU3034 should be occurred and the package should not be installed successfully.
## Actual
No error occur and the package is installed successfully as below attachment.
![noerroroccur](https://user-images.githubusercontent.com/40230425/50894235-ad072d00-143d-11e9-9292-6b66406b46fb.png)

**Comment by rrelyea** [comment]
@rido-min - can you please help triage this, and clarify understanding as needed.
I believe that author name="jamiezhang" and authors in nuspec -- are two totally different concepts.
so i believe this is by design. Thoughts?

**Comment by rido-min** [comment]
This by design. Signing verification is based on owners defined by Nuget.org. Authors in the nuspec can be considered as free text, hence is not trustable.
