### ISSUE TITLE
Issues labeled:waiting for customer don't get updated 

### ISSUE THREAD

**Issue by TrabacchinLuigi** [NuGet/Home#7683]
Once a customer reply to an issue labeled waiting for customer the label stays there and the issue too...

**Comment by jainaashish** [comment]
Thanks for the issue, completely agree that once we have got the adequate details about an issue, then we must remove this label and add other appropriate ones. We'll try to be more diligent about this in future.

@NuGet/nuget-client something to take care off while tracking issues.
