### ISSUE TITLE
[Test Failure] Error “Value cannot be null.” occur when installing a new PR package into a solution with multiple projects

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7684]
## Details about Problem
VS Version: D16.0stg 28509.126
NuGet Version: Dev\5.01.5763
OS Version: 17763.RS5_Release.180914
## Detailed repro steps 
1. Launch Visual Studio 2019 d16.0stg.
2. Create a new Class Library (.Net Framework) project named Project1, adding a new Class Library (.Net Framework) project named project2 into the solution.
3. Open the PM UI of Project1 and install a package with PackageReference format.
4. Open the PM UI of Project2 and install a package with PackageReference format.
## Expected
The package should be installed successfully in step3 and step4.
## Actual
Error “Value cannot be null.” occur when installing a PR package in step3 and step4 in PM UI and the package is not installed successfully as below attachment.
![errormessage](https://user-images.githubusercontent.com/40230425/50959425-e69f6d00-14fd-11e9-9b21-6a2ae65e8b4e.png)
## Notes
1. Open the PM UI of Project1&Project2 at the same time, installing a package for the Project2 is successful.
2. Uninstall the package (installed in note1) and install a package for Project1 and Project2 respectively, and then these packages can be installed successfully. 
3. It does not repro on a solution with only one .Net Framework project.
4. It does not repro when installing a package with package.config format.

**Comment by jainaashish** [comment]
As I've mentioned multiple time in past, it's important to understand when was the last time it worked fine and with which build it started happening... Now based on above information, it's really hard for me to understand when this regression was actually caused?

So tell me with which last build it worked fine? and going forward, PLEASE keep in mind to add these details while logging the bug itself.

**Comment by v-longmin** [comment]
@jainaashish The last build it worked fine: Dev\5.0.0.5759. The build it stared happing: Dev\5.0.0.5760. Never repro after build: Dev\5.0.1.5769.

**Comment by jainaashish** [comment]
So I'm closing it as Not Repro on latest builds
