### ISSUE TITLE
Package with no applicable lib installs without error.

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#769]
{
  "dependencies": {
    "System.Console": "4.0.0-beta-23011",
    "System.IO.Pipes": "4.0.0-beta-23011"
  },
  "frameworks": {
    "netcore50": { }
  }
}

Should produce an error for both of these since there is no lib in scope, but does not.

**Comment by ericstj** [comment]
/cc @anurse 
I was using NuGet.CommandLine.Cmd\build\NuGet.CommandLine.cmd restore project.json with 3.1.0-beta-10197.

**Comment by anurse** [comment]
Looking at this now. We definitely intend for this to fail, it might just be a bug in our logic.

**Comment by anurse** [comment]
Actually, no this is expected. There is a `ref/dotnet` folder for both packages and the project you provided doesn't have any `supports` or `runtimes` defined.

**Comment by anurse** [comment]
As an example, the following project.json does fail as expected:

```json
{
    "dependencies": {
        "System.Console": "4.0.0-beta-23011",
        "System.IO.Pipes": "4.0.0-beta-23011",
        "Microsoft.NETCore.Targets": "1.0.0-beta-*"
    },
    "frameworks": {
        "netcore50": {}
    },
    "runtimes": {
        "win10-x86": {},
        "win10-x64": {},
        "win10-arm": {}
    }
}
```

**Comment by ericstj** [comment]
I see.  That makes sense, though it is a little non-intuitive.  Should we be warning folks if they are missing supports and runtimes sections?

**Comment by anurse** [comment]
Yeah, that does make sense. I'll convert this bug into that and fix that. It'll only be a warning, since we do want to allow people to build PCLs that don't use guardrails (as an advanced scenario).

**Comment by anurse** [comment]
Actually I'll just open a new one :)

**Comment by anurse** [comment]
@davidfowl is not super happy with this idea actually since DNX will likely never use either. I think we could ship RTM without this check, since the user has to intentionally remove things to get in this situation so my suggestion is to defer this for a bit and gather feedback.

Thoughts?

**Comment by ericstj** [comment]
I see, if there is a case where no runtime and no framework is valid, then we should be doing the compatibility probe right?  Or is it the case that DNX permits a project with no runtime or compatibility section then infers a runtime?
If its the latter, can we say that the inference is not in effect for nuget/msbuild and then do lib probe/error?

**Comment by anurse** [comment]
It is (or rather will be ;)) the latter. We will infer runtimes. I'll chat with David, he might be OK with that.

**Comment by anurse** [comment]
We're still really hesitant to put that strict requirement on. Also, I should point out that in the RTM timeline, none of this would really show up, even if we did display a warning since the output is only written to the Output Window (not to the Error List).
