### ISSUE TITLE
Add new-version-published notifications to nuget.org

### ISSUE THREAD

**Issue by dotMorten** [NuGet/Home#7700]
I'd love to be able to subscribe to various packages I use a lot and get notifications when new versions are being published+listed.
Please add such a feature to nuget.org so we can better keep track of latest packages we can use.

**Comment by karann-msft** [comment]
in what form would you like these notifications? email?

**Comment by dotMorten** [comment]
Yup

**Comment by jainaashish** [comment]
Issue moved to [NuGet/NuGetGallery #6823](https://github.com/NuGet/NuGetGallery/issues/6823) via [**ZenHub**](https://www.zenhub.com/)
