### ISSUE TITLE
System.Drawing.common lib get an error when drawing Cambria Math font on Ubuntu

### ISSUE THREAD

**Issue by roywangaspose** [NuGet/Home#7701]
Hello, I am using System.Drawing.common 4.5.1 in my .netcore project.
It works fine on windows system, but I get some problems on Ubuntu(16.04, 64bit).
Here is my simple test code, and I have signed the error information in comments.
I also put my simple test project in the attachment, it will get an error on Ubuntu.

using System;
using System.IO;
using System.Drawing;

            //you may put any test bmp file here
            System.Drawing.Image img1 = Image.FromFile(Constants.BasePath + "TestBitmap.bmp");
            Graphics g2 = Graphics.FromImage(img1);

            //Here we use "Cambria Math" font, it is a kind of font which used in Equation of Excel file
            System.Drawing.Font f = new System.Drawing.Font("Cambria Math", 11.0f);
            Brush brush = new SolidBrush(Color.Red);

            //unicode charaters from "\ud835\udc4e"(𝑎) to "\ud835\udc67"(𝑧) (may be more), will cause crash on ubuntu(16.04, 64bit)
            //see charater "𝑦", not "y" (it is a charater in Excel file, under "Cambria Math" font of Equation)
            string s1 = "𝑦";
            //first problem: the charater "𝑦" will not be drawn correctly on ubuntu linux
            g2.DrawString(s1, f, brush, new PointF(10, 10), StringFormat.GenericTypographic);

            //second problem: after drawing "𝑦" charater, if we do any other operation to Graphics g2, it will crash.
            System.Drawing.Drawing2D.Matrix gTransform2 = g2.Transform;
            gTransform2.Multiply(new System.Drawing.Drawing2D.Matrix());
            //for example, Multiply operation will be crashed here
            //The error info is "A generic error occurred in GDI+."
            g2.Transform = gTransform2;

            //And if we run it on windows, it can run to here without any problem.
            g2.DrawString("123A", f, brush, new PointF(10, 30), StringFormat.GenericTypographic);
            g2.Save();
            img1.Save(Constants.BasePath + "TestBitmap2.bmp");

[ConsoleApp3.zip](https://github.com/NuGet/Home/files/2767645/ConsoleApp3.zip)

**Comment by jainaashish** [comment]
Please contact Package Author(s) regarding specific package issue. And since this is part of Dotnet framework, you can either create a VS feedback ticket or ask this question on StackOverflow.
