### ISSUE TITLE
Rethink suggesting Bower as front-end package manager

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7702]
I think it's not a good idea to suggest Bower as front-end package manager from the NuGet dialog. I totally agree NuGet should not be used for front-end packages, but don' agree on Bower. Even the Bower project suggest people use npm as package repo, either via npm or yarn as a tool. It's not that Bower is dead, but it is in maintenance mode only. Do we want to lead people on a path that we know will be obsolete in the near future?

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/400136/rethink-suggesting-bower-as-front-end-package-mana.html
VSTS ticketId: 740485_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/6/2018, 06:13 PM (41 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  You will hear from us in about a week on our next steps.</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

**Comment by anangaur** [comment]
I remember this going on and off. I thought we stopped suggesting this but seems like this is not the case. Also not positive if this is something thats lighted up from NuGet client codebase but we should do the right suggestion here or get the text fixed.

**Comment by jainaashish** [comment]
AFAIK this message is from ASP.NET or NETCore teams which I believe can be moved to LibMan now.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6623
