### ISSUE TITLE
Keep focus on Output - Package Manager

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7703]
<p></p><p></p><p>When working with Nuget
management the [Output - Package Managers] window always get switched to the
[Error List] even if installation/update/uninstallation is unsuccessful. Please
make the failed operation more obvious to the developer cause it is too easy to
miss. </p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/406388/keep-focus-on-output-package-manager.html
VSTS ticketId: 749828_
_These are the original issue comments:_

Jane Wu [MSFT] on 12/13/2018, 05:47 PM (34 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by jainaashish** [comment]
I'm lil confused, isn't Error List more important then output window in case installation was unsuccessful?

**Comment by nkolev92** [comment]
I agree with the above. 
Closing per that comment.
