### ISSUE TITLE
5.0p3 shipped VS Build SKU with wrong Newtonsoft.Json depedency

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7706]
## Details about Problem
NuGet version: NuGet Client Dev\5.0.0.5783
Build Tools VS Version: D16.0stg\28517.137
OS Version: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1. Install **VS BuildTools** D16.0stg\28517.137 from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2339941&view=results
2. Get the **Build Tools vsix** from: \\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\dev\5.0.0.5783\artifacts\VS15\Microsoft.VisualStudio.NuGet.BuildTools.vsix
3. Extract the vsix locally.
4. Go to the extracted folder and copy the contents of the folder: Contents\Common7\IDE\CommonExtensions\Microsoft\NuGet\
5. Copy those files to C:\Program Files (x86)\ Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet
6. Check out a .NET Framework Class Library/ .NET Core Console App/.NET Standard Class Library project with a PackageReference (NUnit 3.11.0) installed.
7. Run command: **“msbuild /t:restore”** or **“msbuild /t:build /restore”**.
## Expected
Running of these commands should succeed without any warnings. 
## Actual
Restore failed with an error: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0’ (as below screenshot).
![restorefailed](https://user-images.githubusercontent.com/20632625/51384329-f995eb00-1b56-11e9-8128-e390ec94e256.png)

## Note
1.The last fine build: Dev\5.0.0.5755.
2.The first broken build Dev\5.0.0.5756.
3.Restore on VS D16.0stg 28517.137 + NuGet Client Dev\5.0.0.5783 is OK.

**Comment by jainaashish** [comment]
@nkolev92  can you please take a look at it? Vendor says it started happening after this PR# https://github.com/NuGet/NuGet.Client/pull/2670 merged.

**Comment by nkolev92** [comment]
@v-luzh 
Can you do a quick change in the test. 

From: 

> 4. Go to the extracted folder and copy the contents of the folder: Contents\Common7\IDE\CommonExtensions\Microsoft\NuGet\
> 5. Copy those files to C:\Program Files (x86)\ Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet

to:

> 4. Delete the content of C:\Program Files (x86)\ Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet
> 5. Go to the extracted folder and copy the contents of the folder: Contents\Common7\IDE\CommonExtensions\Microsoft\NuGet\
> 6. Copy those files to C:\Program Files (x86)\ Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet

**Comment by v-luzh** [comment]
@nkolev92 The same error occur after testing with above changed steps.

**Comment by v-luzh** [comment]
Sorry, clicked a wrong button. Reopen the bug.

**Comment by jainaashish** [comment]
@nkolev92 it's still reproing with your updated instructions, so can you look at it? We're running with the dev16 p3 insertion with these bits.

**Comment by nkolev92** [comment]
@v-luzh Since you successfully tested: 
`NuGet in the Builds Tools SKU test report on VS Build Tools D16.0stg 28524.203 + NuGet Build Tools Dev\5.0.0.5787` as per the test reports, does that mean you are not seeing this issue anymore?

**Comment by v-nancyj** [comment]
@nkolev92 The issue still repro on VS Build Tools D16.0 28526.10 + NuGet Build Tools Dev\5.0.0.5798 after my verification today, could you help to check it?

**Comment by nkolev92** [comment]
So a bit of confusion here. 

The build was not broken by the packaging core removal, rather by https://github.com/NuGet/NuGet.Client/pull/2580. 

The fact that the builds were out of order because of CI flakiness is the issue.

**Comment by nkolev92** [comment]
I'm testing a fix right now.

**Comment by nkolev92** [comment]
Should be fixed in tonight's build @v-nancyj @v-luzh
