### ISSUE TITLE
NuGet doesn't appear to work in VS 2017 Community Edition

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7710]
@tshinkle commented on [Tue Jan 15 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1267)

I'm trying to do the most basic tutorial in VS 2017 and all I get is the following:
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Here is the first error of 34:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	VotingWeb	C:\Users\tim\source\repos\Voting\VotingWeb\VotingWeb.cs	1	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 906d0438-0338-0167-3a38-d213ee187ddb
* Version Independent ID: b558fa0c-f549-1e6a-c2db-fd2e6a2351be
* Content: [Troubleshooting NuGet Package Restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting)
* Content Source: [docs/consume-packages/Package-restore-troubleshooting.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-restore-troubleshooting.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

---

@karann-msft commented on [Fri Jan 18 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1267#issuecomment-455695593)

@tshinkle I am moving this issue to the Home repo which the place for exactly this sort of issue.
Can you share the steps to repro the issue and point to the tutorial that you are trying to follow.
Thanks!

**Comment by dominoFire** [comment]
Hi @tshinkle, we need more details to address your issue. Can you provide use a sample of the proj file?

Are you trying to run this application? https://github.com/Azure-Samples/service-fabric-dotnet-quickstart

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
