### ISSUE TITLE
New Nuget.Build.Packaging release on nuget.org

### ISSUE THREAD

**Issue by azeno** [NuGet/Home#7712]
The current hosted version on nuget.org is a little out-dated (from December 2017) and in my case misses certain important bug fixes. For know I've used the appveyor feed but I worry a little that the latest built package from that feed will disappear rather soon due to appveyor's cleanup policy (6 months). So any chance the current prerelease package gets uploaded to nuget.org or even better create a stable release?

This issue should be tagged with Area:NuGetizer

**Comment by dominoFire** [comment]
@kzu

**Comment by kzu** [comment]
This project has been forked, superseeded and is actively maintained as the new [NuGetizer](https://www.nuget.org/packages/NuGetizer) which is actively maintained.

**Comment by ghost** [comment]
Issue is missing Type label, remember to add a [Type label](https://github.com/NuGet/Client.Engineering/blob/main/designs/nuget-issues-approach.md#issue-type)
