### ISSUE TITLE
Consider changing the names of the ToHighestMinor and ToHighestPatch switches on update

### ISSUE THREAD

**Issue by johnataylor** [NuGet/Home#772]
PowerShell users can be very particular about the grammar and naming of switches. Please review these name.

**Comment by yishaigalatzer** [comment]
Don't change the existing names that where already shipped in 2.8.X. These are additional names

**Comment by yishaigalatzer** [comment]
Reading through the spec, this suggestion is good.
https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SD03

**Comment by emgarten** [comment]
From @johnataylor: these are new flags, one is an alias for an existing switch.

@csharpfritz can you take a look at these parameters and let us know if they are needed, and if the names would be intuitive to the users.
