### ISSUE TITLE
Package Installation Error when create blank app from windows\Universal

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#773]
install NuGet 575 from dev branch

repro steps:
1. create blank app from C#->Windows->Universal

expected results: create successfully
actual results: create failed with below error
![l_8a18 tmp](https://cloud.githubusercontent.com/assets/11768961/8127692/6ff8feb6-112b-11e5-9369-0d3c96bbec8b.PNG)

**Comment by emgarten** [comment]
This no longer repros in the latest bits.

**Comment by danliu** [comment]
This has reproed again with NuGet 615 dev + latest VS.

**Comment by emgarten** [comment]
This is due to a template/package mismatch.
