### ISSUE TITLE
Nuget trasitive dependecy should contain flag for .netcore or system level packages

### ISSUE THREAD

**Issue by inabeel** [NuGet/Home#7734]
Utility development for .NET Core project transitive dependencies

I am accessing Nuget.Package model to access Target dependencies of the project, which is excellent. The good point is it contains "AutoReferenced" flag to indicate the dependency is auto referenced. But the problem comes when I go to sub dependencies of "LockFileTargetLibrary" object, it doesn't have any similar flag to identify framework/ System level or internal libraries.

**Comment by nkolev92** [comment]
@inabeel 
Use the PackageSpec model. 

https://github.com/NuGet/NuGet.Client/blob/ec48ee474965d3d5f41ed7e5b4199af79868351a/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFile.cs#L29

https://github.com/NuGet/NuGet.Client/blob/ec48ee474965d3d5f41ed7e5b4199af79868351a/src/NuGet.Core/NuGet.ProjectModel/PackageSpec.cs#L92

https://github.com/NuGet/NuGet.Client/blob/ec48ee474965d3d5f41ed7e5b4199af79868351a/src/NuGet.Core/NuGet.ProjectModel/TargetFrameworkInformation.cs#L18

https://github.com/NuGet/NuGet.Client/blob/ec48ee474965d3d5f41ed7e5b4199af79868351a/src/NuGet.Core/NuGet.LibraryModel/LibraryDependency.cs#L29

LockFileTargetLibrary is expressing what was selected. 
The origin of the package and that fact that it's autoreferenced at that point is irrelevant.
