### ISSUE TITLE
No items found on package list when select Online\nuget.org

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#774]
install NuGet 756 from \\wsr-tc\Drops\NuGet.Signed.AllLanguages\build-523\Signed\VSIX\12

repro steps:
1. create a project
2. open Manage NuGet Packages..

expected results: packges displayed when select online-> nuget.org
actual results: No items found under Online->nuget.org, see below screenshot

Note: if you search an exist package, like jQuery, works fine

![nugetorgisblank](https://cloud.githubusercontent.com/assets/11768961/8129440/bd3d8092-113b-11e5-8ca5-0aa20a478751.PNG)

**Comment by maartenba** [comment]
This was an intermittent issue related to caching. It has been solved, and we took steps to mitigate this type of error in the future. Thanks for letting us know!
