### ISSUE TITLE
"Package is not compatible with netcoreapp2.2", but same message says it is supported

### ISSUE THREAD

**Issue by msfcolombo** [NuGet/Home#7742]
## Details about Problem

NuGet product used: dotnet.exe

dotnet.exe --version: 2.2.103

OS version: Win10 1809 build 17763.253

Worked before? No.

## Detailed repro steps so we can see the same problem

Open admin command prompt and type:

    dotnet tool install -g atgit --version 0.8.7

You shall see this error:

    error NU1202: Package atgit 0.8.7 is not compatible with netcoreapp2.2 (.NETCoreApp,Version=v2.2) / any. Package atgit 0.8.7 supports:
    error NU1202:   - net452 (.NETFramework,Version=v4.5.2)
    error NU1202:   - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
    error NU1202:   - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
    error NU1202:   - netcoreapp2.2 (.NETCoreApp,Version=v2.2)
    The tool package could not be restored.

The line one says that the package is not compatible with `netcoreapp2.2 (.NETCoreApp,Version=v2.2)`, but line 5 says that it is supported.

The source code is under this tree: [https://github.com/fernacolo/atgit/tree/27da81e/src](https://github.com/fernacolo/atgit/tree/27da81e/src).

The `publish.cmd` file contains the build and publish commands.

**Comment by heng-liu** [comment]
It seems like this may be the same issue as https://github.com/dotnet/cli/issues/10468.
Thoughts? @wli3

**Comment by wli3** [comment]
@msfcolombo this package is [ill formatted](https://github.com/dotnet/cli/blob/master/Documentation/general/tool-nuget-package-format.md). The dlls are in lib folder instead of tools. You should use `<PackAsTool>true</PackAsTool>` and run pack instead of setting package type directly.

@heng-liu I think we could close it

**Comment by msfcolombo** [comment]
@wli3 Thanks. I think you are missing a validation step here. Otherwise the message would not be so confusing. Consider leaving this open for the fix.

**Comment by rrelyea** [comment]
@msfcolombo - there are a couple of things that need fixing:
1) .NET Core team should improve the error message that *dotnet install* raises when the nuget restore they kick off to help them do the install fails. That is tracked as https://github.com/dotnet/cli#10468 
2) the atgit tool should not try to be a tool by just setting packagetype...as it has a problem with where the DLLs are. @wli3 says they should be in tools\ not lib\.

We're closing this issue down, as there is no fix required in the nuget.client repo.

**Comment by msfcolombo** [comment]
@rrelyea, I think you meant https://github.com/dotnet/cli/issues/10468.

@wli3, the fix was far more easy than writing a `nuspec`. I just had to remove support for net452 and add `<PackAsTool>true</PackAsTool>` in the `csproj` file. Here's the commit: https://github.com/fernacolo/atgit/commit/7096b3eff4c1817749c40e2891f6a4687297c001

You can now install atgit with this simple command:

    dotnet tool install -g atgit

Works like a charm! Thanks for the support!
