### ISSUE TITLE
While installing nuget package, a different dependency is brought down than what is shown.

### ISSUE THREAD

**Issue by gdodd1977** [NuGet/Home#7744]
I have a nuget package in my project that keeps pulling down some random dll instead of the ones listed as the dependencies.

i.e. package is CompanyName.SomePackage and it has a dependency on AnotherPackage.Core. When looking in nuget explorer, it even shows the correct dependency name. But when I actually tell it to install, it grabs AnotherPackage.SomeOlderNonUsedVersion instead during the install. It is really strange.
As well, only happens on one of my computers. I don't have this issue on any other computer. And my coworkers don't either.

I've tried clearing the nuget cache several times. Clean and rebuild. Uninstalled VS 2017 and reinstalled. Nothing has worked.

**Comment by heng-liu** [comment]
I have a question about the details of your repro scenario.

Package: CompanyName.SomePackage depends on what version of AnotherPackage.Core? (according to the .nuspec in CompanyName.SomePackage)

What version of AnotherPackage.Core ends up getting installed?

What type of project are you using? Is it using Packages.Config or PackageReference?

After that:
Besides clearing your global package folder, and other local caches with "nuget.exe locals -clear all", another variable to consider is which package feeds you and your coworkers have configured. If they are not identical, that may be a reason why behavior is different.

**Comment by gdodd1977** [comment]
So it doesn't even install AnotherPackage.Core. It installs some other dependency package that isn't part of the dependencies. It's like it's some how holding on to a really old version of this that USED to point to AnotherPackage.SomeOlderNonUsedVersion, but it no longer does. 

It uses PackageReference.

We all use the same package feed.

**Comment by heng-liu** [comment]
Thanks for your reply!
Can you please provide more details of the two scenarios(on your computer and your coworkers computer) so that I could repro? 
In the meantime, can you please also provide the two project.assets files(when you finished installing the CompanyName.SomePackage, under obj folder)? They might be helpful, too. Thanks!

**Comment by nkolev92** [comment]
Closing this as at this point we do not have enough information to investigate this issue.
