### ISSUE TITLE
Analyze test failure DependencyGraphRestoreUtility_LegacyPackageRef_Restore_BuildTransitive

### ISSUE THREAD

**Issue by jainaashish** [NuGet/Home#7745]
Disabled one unit test `DependencyGraphRestoreUtility_LegacyPackageRef_Restore_BuildTransitive` which is consistenly failing in CI but passing locally.

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2365490&view=logs

**Comment by nkolev92** [comment]
NuGet.CommandLineTest.RestoreCommandTests.Restore_LegacyPackageReference_BuildTransitive is failing for the same reason. 

The error suggests that targets and props are being selected independently, as:
```
buildTransitive\package.targets
build\package.props
```

**Comment by nkolev92** [comment]
The above one is a test bug. 

`build;analyzer` instead of 
`build,analyzers`

**Comment by nkolev92** [comment]
Test bug as well, PR is out. https://github.com/NuGet/NuGet.Client/pull/2833

Moving to 5.2, as there's no need to merge in 5.1 because the test is already disabled there.
