### ISSUE TITLE
Download package very slow in china

### ISSUE THREAD

**Issue by yh371174229** [NuGet/Home#7747]
## Details about Problem
Do you pay attention to China's nuget experience? Is there a mirror server for China? I did not try to download this update for the day.
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):latest

dotnet.exe --version (if appropriate):.net framework 4.5.2

VS version (if appropriate):2013/2015/2017

OS version (i.e. win10 v1607 (14393.321)):win 10

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem
always failed，My God！
Like npm,we have taobao mirror,But NuGet wo have nothing,it's so slow slow and slow
Hope to improve the experience

**Comment by KexyBiscuit** [comment]
See https://blog.nuget.org/20170907/Changes-to-NuGet-dot-org-service-management-and-performance-improvements-in-China.html.
