### ISSUE TITLE
Warning when dotnet pack .Net Core 3.0 console app project

### ISSUE THREAD

**Issue by YunWeiaa** [NuGet/Home#7750]
## Detailed repro steps so we can see the same problem
1. Create a new .net core console app project via CLI
2. Dotnet restore and build
3. Dotnet pack

## Expected behavior
Restore/build/pack succeeded with no warnings and no errors.

## Actual behavior
Pack succeeded with the warning NU5104: `A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.NETCore.Platforms [3.0.0-preview.19073.11, )" or update the version field in the nuspec.`
![image](https://user-images.githubusercontent.com/33921754/52037544-538cac80-256a-11e9-885a-9aaa5b6a9a64.png)
Solution: Dotnet pack again, the warning can disappear.
![image](https://user-images.githubusercontent.com/33921754/52037666-9ea6bf80-256a-11e9-87d3-3a4251f95a2b.png)
## Environment data
D16.0/28530.118(16.0.0 preview 3.0) + CLI\SDK: [3.0.100-preview-010190](https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x86.exe)
Dotnet --info:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010190
 Commit:    bf929e4649

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.0.100-preview-010190\

Host (useful for support):
  Version: 3.0.0-preview-27329-4
  Commit:  988132f2a8

.NET Core SDKs installed:
  3.0.100-preview-010190 [C:\Program Files (x86)\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27329-4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27329-5 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download



```

**Comment by livarcocc** [comment]
This is expected. This warning will only go away once we have a stable version of Microsoft.NETCore.App.

**Comment by nkolev92** [comment]
As mentioned above, this is expected. 

The reason why you don't see the warning the second time is the target no-oping. 

You need to change *something* in your project/build for pack to rebuild the package.
