### ISSUE TITLE
Machine readable output for dotnet list package

### ISSUE THREAD

**Issue by adamdriscoll** [NuGet/Home#7752]
## Details about Problem

It is difficult to parse the output of `dotnet list package`. We have requirements in our organization to audit packages that we are using in our projects. Without having a good way to parse the output of this command, it makes it difficult to structure the list of packages in a way that can be fed into another auditing system. 

Running the following command produces the following output:

```
dotnet list package --include-transitive
```

```
Project 'UniversalDashboard' has the following package references
   [net472]:
   Top-level Package                                           Requested          Resolved
   > Microsoft.AspNetCore                                      2.1.3              2.1.3
   > Microsoft.AspNetCore.Authentication.Cookies               2.1.2              2.1.2
   > Microsoft.AspNetCore.Authentication.Facebook              2.1.2              2.1.2
   > Microsoft.AspNetCore.Authentication.Google                2.1.2              2.1.2
   > Microsoft.AspNetCore.Authentication.JwtBearer             2.1.2              2.1.2
   > Microsoft.AspNetCore.Authentication.MicrosoftAccount      2.1.2              2.1.2
   > Microsoft.AspNetCore.Authentication.Twitter               2.1.2              2.1.2
   > Microsoft.AspNetCore.Mvc                                  2.1.2              2.1.2
   > Microsoft.AspNetCore.ResponseCompression                  2.1.1              2.1.1
   > Microsoft.AspNetCore.Routing                              2.1.1              2.1.1
   > Microsoft.AspNetCore.Server.Kestrel.Https                 2.1.3              2.1.3
   > Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv       2.1.3              2.1.3
   > Microsoft.AspNetCore.Session                              2.1.1              2.1.1
   > Microsoft.AspNetCore.SignalR                              1.0.3              1.0.3
   > Microsoft.AspNetCore.StaticFiles                          2.1.1              2.1.1
   > Microsoft.AspNetCore.WebSockets                           2.1.1              2.1.1
   > Microsoft.DotNet.PlatformAbstractions                     2.1.0              2.1.0
   > Microsoft.Extensions.Caching.Memory                       2.1.2              2.1.2
   > Microsoft.Extensions.Logging.Debug                        2.1.1              2.1.1
   > Microsoft.Extensions.Logging.Filter                       1.1.2              1.1.2
   > Newtonsoft.Json                                           11.0.2             11.0.2
   > NLog                                                      4.5.8              4.5.8
   > NLog.Web.AspNetCore                                       4.6.0              4.6.0
   > PowerShellStandard.Library                                5.1.0-preview-06   5.1.0-preview-06
   > Quartz                                                    3.0.6              3.0.6
   > System.Net.NameResolution                                 4.3.0              4.3.0
   > System.Reflection.Emit                                    4.3.0              4.3.0
   > System.Runtime.Loader                                     4.3.0              4.3.0
   > System.Security.Principal                                 4.3.0              4.3.0

   Transitive Package                                                Resolved
   > Libuv                                                           1.10.0
   > Microsoft.AspNetCore.Antiforgery                                2.1.1
   > Microsoft.AspNetCore.Authentication                             2.1.2
   > Microsoft.AspNetCore.Authentication.Abstractions                2.1.1
   > Microsoft.AspNetCore.Authentication.Core                        2.1.1
   > Microsoft.AspNetCore.Authentication.OAuth                       2.1.2
   > Microsoft.AspNetCore.Authorization                              2.1.1
   > Microsoft.AspNetCore.Authorization.Policy                       2.1.1
   > Microsoft.AspNetCore.Connections.Abstractions                   2.1.3
   > Microsoft.AspNetCore.Cors                                       2.1.1
   > Microsoft.AspNetCore.Cryptography.Internal                      2.1.1
   > Microsoft.AspNetCore.DataProtection                             2.1.1
   > Microsoft.AspNetCore.DataProtection.Abstractions                2.1.1
   > Microsoft.AspNetCore.Diagnostics                                2.1.1
   > Microsoft.AspNetCore.Diagnostics.Abstractions                   2.1.1
   > Microsoft.AspNetCore.HostFiltering                              2.1.1
   > Microsoft.AspNetCore.Hosting                                    2.1.1
   > Microsoft.AspNetCore.Hosting.Abstractions                       2.1.1
   > Microsoft.AspNetCore.Hosting.Server.Abstractions                2.1.1
   > Microsoft.AspNetCore.Html.Abstractions                          2.1.1
   > Microsoft.AspNetCore.Http                                       2.1.1
   > Microsoft.AspNetCore.Http.Abstractions                          2.1.1
   > Microsoft.AspNetCore.Http.Connections                           1.0.3
   > Microsoft.AspNetCore.Http.Connections.Common                    1.0.3
   > Microsoft.AspNetCore.Http.Extensions                            2.1.1
   > Microsoft.AspNetCore.Http.Features                              2.1.1
   > Microsoft.AspNetCore.HttpOverrides                              2.1.1
   > Microsoft.AspNetCore.JsonPatch                                  2.1.1
   > Microsoft.AspNetCore.Localization                               2.1.1
   > Microsoft.AspNetCore.Mvc.Abstractions                           2.1.2
   > Microsoft.AspNetCore.Mvc.ApiExplorer                            2.1.2
   > Microsoft.AspNetCore.Mvc.Core                                   2.1.2
   > Microsoft.AspNetCore.Mvc.Cors                                   2.1.2
   > Microsoft.AspNetCore.Mvc.DataAnnotations                        2.1.2
   > Microsoft.AspNetCore.Mvc.Formatters.Json                        2.1.2
   > Microsoft.AspNetCore.Mvc.Localization                           2.1.2
   > Microsoft.AspNetCore.Mvc.Razor                                  2.1.2
   > Microsoft.AspNetCore.Mvc.Razor.Extensions                       2.1.1
   > Microsoft.AspNetCore.Mvc.RazorPages                             2.1.2
   > Microsoft.AspNetCore.Mvc.TagHelpers                             2.1.2
   > Microsoft.AspNetCore.Mvc.ViewFeatures                           2.1.2
   > Microsoft.AspNetCore.Razor                                      2.1.1
   > Microsoft.AspNetCore.Razor.Design                               2.1.1
   > Microsoft.AspNetCore.Razor.Language                             2.1.1
   > Microsoft.AspNetCore.Razor.Runtime                              2.1.1
   > Microsoft.AspNetCore.ResponseCaching.Abstractions               2.1.1
   > Microsoft.AspNetCore.Routing.Abstractions                       2.1.1
   > Microsoft.AspNetCore.Server.IISIntegration                      2.1.1
   > Microsoft.AspNetCore.Server.Kestrel                             2.1.3
   > Microsoft.AspNetCore.Server.Kestrel.Core                        2.1.3
   > Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions      2.1.3
   > Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets           2.1.3
   > Microsoft.AspNetCore.SignalR.Common                             1.0.3
   > Microsoft.AspNetCore.SignalR.Core                               1.0.3
   > Microsoft.AspNetCore.SignalR.Protocols.Json                     1.0.3
   > Microsoft.AspNetCore.WebUtilities                               2.1.1
   > Microsoft.CodeAnalysis.Analyzers                                1.1.0
   > Microsoft.CodeAnalysis.Common                                   2.8.0
   > Microsoft.CodeAnalysis.CSharp                                   2.8.0
   > Microsoft.CodeAnalysis.Razor                                    2.1.1
   > Microsoft.CSharp                                                4.5.0
   > Microsoft.DiaSymReader.Native                                   1.7.0
```

The problem with this type of output is that it is difficult to parse. npm provides two options that make this easier when listing packages. They include both a `-parsable` and a `-json` parameter. I think `dotnet list package` should provide something similar. 

I think that `dotnet list package` should do something similar. 

```
F:\universal-dashboard\src\UniversalDashboard>dotnet --version
2.2.102
```

I'm happy to work on a PR for this. I've found the responsible code and could implement a "parse-friendly" version but wanted feedback from the community\team before doing anything. 

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.CommandLine.XPlat/Utility/ProjectPackagesPrintUtility.cs

------------------------------
**Update 12/10/2021:**
After diving into this issue, it's quite large issue, it looks none of dotnet command implemented it, this is 1st time. Let's divide and conquer this issue, here're sub issues:
* Machine readable json output for dotnet list package: https://github.com/NuGet/Home/issues/11449
Spec proposal PR: https://github.com/NuGet/Home/pull/11446

**Comment by nkolev92** [comment]
Hey @adamdriscoll 
Thanks for opening this issue. 
It is something we considered initially, but wasn't added for V1. 

@rrelyea @anangaur to chip in on how they'd want this done. 

I personally prefer a json option.

**Comment by anangaur** [comment]
Json seems fine as most of NuGet generated artifacts are json too. 

@adamdriscoll , If you could start with a one pager that includes the proposal on output i.e. the structure of the data and how sample output would look like with different options, that can be a good start. We can review the proposal and then suggest/make changes as required. Since this is not on our priority list, it would be difficult for us to propose a full spec on this in near term.

**Comment by ignatandrei** [comment]
json will be good to have.

**Comment by xavierdecoster** [comment]
Having a `--json` option for `dotnet list package` would be very convenient indeed, especially when `--outdated` and `--deprecated` come into the picture. Making the output machine-readable unlocks additional tooling and automation scenarios.

Based on today's (and planned) console output, here's a suggestion. 
Would love feedback/input and make sure we understand what data and format would be desired for this JSON output.

#### outdated.json

Command: `dotnet list package --outdated --include-transitive --json`

```
{
  "outdated": [
    {
      "framework": "netcoreapp2.0",
      "topLevelPackages": [
        {
          "id": "NuGet.Common",
          "requestedVersion": "4.8.0-preview1.5146",
          "resolvedVersion": "4.8.0-preview1.5146",
          "latestVersion": "4.9.1-zlocal.52990"
        }
      ],
      "transitivePackages": [
        {
          "id": "NuGet.Frameworks",
          "requestedVersion": "4.8.0-preview3.5278",
          "latestVersion": "4.9.1-zlocal.52990"
        }
      ]
    }
  ]
}
```

#### deprecated.json

Command: `dotnet list package --deprecated --json`

```
{
  "deprecated": [
    {
      "framework": "netcoreapp2.0",
      "topLevelPackages": [
        {
          "id": "My.Legacy.Package",
          "resolvedVersion": "2.0.0",
          "reasons": ["Legacy"],
          "alternativePackage": {
            "id": "My.Awesome.Package",
            "versionRange": "[3.0.0,)"
          }
        },
        {
          "id": "My.Buggy.Package",
          "resolvedVersion": "1.1.0",
          "reasons": ["Critical Bugs"],
          "alternativePackage": {
            "id": "My.NotBuggy.Package",
            "versionRange": "*"
          }
        },
        {
          "id": "My.CompletelyBroken.Package",
          "resolvedVersion": "0.9.0",
          "reasons": ["Legacy", "Critical Bugs"],
          "alternativePackage": null
        }
      ],
      "transitivePackages": null
    }
  ]
}
```

#### installed-packages.json

Command: `dotnet list package --json`

This would be very similar to the `outdated.json` example above but simply listing all installed packages.

**Comment by anangaur** [comment]
Should it be `null` or empty object list for no transitivePackages?

For multi-targetting, there is a trade-off (size of the file) between listing the packages separately for each framework vs. having this info as an attribute for each package. I like the current approach better though.

**Comment by xavierdecoster** [comment]
> Should it be null or empty object list for no transitivePackages?

No strong opinion :)

> For multi-targetting, there is a trade-off (size of the file) between listing the packages separately for each framework vs. having this info as an attribute for each package. I like the current approach better though.

The current model happens to correspond with the in-memory model used for console printing, which is rather convenient.

**Comment by anangaur** [comment]
Announcement for the spec review: https://github.com/NuGet/Announcements/issues/35
Spec: [Machine readable output for dotnet list package](https://github.com/NuGet/Home/wiki/%5BSpec%5D-Machine-readable-output-for-dotnet-list-package)

**Comment by nkolev92** [comment]
@anangaur @xavierdecoster Can you please put the spec in a PR to the https://github.com/NuGet/Client.Engineering repo? 

It's very difficult to leave comments on a spec that's in the wiki.

**Comment by zivkan** [comment]
I agree with moving the spec to a PR so feedback can be provided more easily.

In addition, the json format needs to take into account that it's possible to run `dotnet list package` on a solution, in which case it needs to show each project separately. The proposed output only looks suitable for single projects.

**Comment by anangaur** [comment]
Agree with having the specs as files than wiki. I will try to find a place, for next specs. A common place than having client vs. server places.

**Comment by nkolev92** [comment]
A couple of comments from a first look (please PR it!). 

* TransitivePackage should not be null. Just do an empty array. 
* How about framework as the key rather than having a framework kvp? 
* How do we handle multiple projects?

**Comment by xavierdecoster** [comment]
> Agree with having the specs as files than wiki. I will try to find a place, for next specs. A common place than having client vs. server places.

> A couple of comments from a first look (please PR it!).

Thanks, will update. Where should the spec files go (and the PR)? :)

**Comment by nkolev92** [comment]
Start with https://github.com/NuGet/Client.Engineering, unless @anangaur is ready with a new repo? :)

**Comment by anangaur** [comment]
[Home/wiki](https://github.com/NuGet/Home/wiki), for now :)

**Comment by nkolev92** [comment]
Another dup in https://github.com/NuGet/Home/issues/9524

**Comment by renemadsen** [comment]
Any progress on this issue?
Really need this for handling a farm of projects.

**Comment by anangaur** [comment]
/cc: @JonDouglas 

We are evaluating this as part of our package vulnerability work. 

@renemadsen, it may help if you could elaborate on your scenario a bit.

**Comment by delepster** [comment]
Any progress on this?

**Comment by olivierhelin** [comment]
Hello, any updates?

**Comment by MPapst** [comment]
@anangaur: our use case is to have a documentation over a complete solution (IoT with backend) . We would like to have a distinct list of used libraries and version over the complete solution.
The JSON list could be filtered for duplicates during the build process (instead of dropping a text document to the artifacts) and projected into a new data structure to show library --> applications.

**Comment by JonDouglas** [comment]
There are two goals to improve output for dotnet CLI commands using NuGet.

1. Human-readable output is first and foremost. This should be covered with the current list package command, however we may have some improvements coming to the command to make this better to glance at.

2. Machine-readable output is second to make output easier to handle, especially complex lists this command can produce (especially with transitive dependencies included)

The original spec: https://github.com/NuGet/Home/wiki/%5BSpec%5D-Machine-readable-output-for-dotnet-list-package includes one aspect of machine-readable output by including `--json`. We also would like to provide a parseable output such as `---parseable` which will provide output in a plain text format separated by tab characters otherwise known as (grepable)

We are working towards our vulnerability work & should be able to consider adding output such as `--json` & `--parseable` relatively soon next year.

**Comment by edespong** [comment]
For use cases around machine-readable output for security and license checking, I really would like some kind of connection between the top-level packages and the transitive dependencies. Just having output that says that there is a transitive dependency without some kind of reference to which top-level package that caused it to be included could create a lot extra work.

I think the proposal would be better with either having a tree-based structure where each top-level dependency contains all its transitive dependencies _or_ if there was some sort of unique id for each dependency that could be referenced.

**Comment by drewgillies** [comment]
As part of this work, we would want to include the output of the `--vulnerable` report. Extending @xavierdecoster's proposed output for `--outdated` and `--deprecated`, `--vulnerable` could look something like this:

```
{
  "vulnerable": [
    {
      "framework": "netcoreapp2.0",
      "topLevelPackages": [
        {
          "id": "My.Vulnerable.Package",
          "resolvedVersion": "2.0.0",
          "severity": 2
          "advisoryUrl": https://github.com/advisories/1234-5678-90ab-cdef
        },
        {
          "id": "My.OtherVulnerable.Package",
          "resolvedVersion": "1.1.0",
          "severity": 3
          "advisoryUrl": https://github.com/advisories/ghij-1234-5678-90ab
        }
      ],
      "transitivePackages": null
    }
  ]
}
```

@anangaur @JonDouglas

**Comment by KalleOlaviNiemitalo** [comment]
A hacky workaround. First use `nuget restore -UseLockFile` to generate `packages.lock.json` files throughout the solution, and then parse them with PowerShell:

```PowerShell
Get-ChildItem -Filter:packages.lock.json -Recurse |
ForEach-Object { Get-Content -LiteralPath:$_ | ConvertFrom-Json } |
ForEach-Object { $_.dependencies.PSObject.Properties } |
ForEach-Object { $_.Value.PSObject.Properties } |
Where-Object { $_.Value.type -ne "Project" } |
ForEach-Object { $_.Name + "/" + $_.Value.resolved } |
Sort-Object -Unique
```

Alas, neither this nor `dotnet list package` lists NuGet packages that are referenced as [MSBuild project SDKs](<https://docs.microsoft.com/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017#how-project-sdks-are-resolved>). Filed <https://github.com/NuGet/Home/issues/10669>.

**Comment by JonDouglas** [comment]
I am working on machine readable output for another command which is related here. Although the proposal is not fully public & still in-progress, I took aspects of other ecosystem's auditing experiences into account which ended up being very close to what @drewgillies & the original spec included. You can view that here:

https://github.com/NuGet/Home/blob/dotnet-audit/proposed/2021/DotNetAudit.md#dotnet-audit---json

```
{
  "audit": {
    "vulnerabilities": {
      "low": "0",
      "moderate": "2",
      "high": "0",
      "critical": "0",
      "dependencies": [
        {
          "name": "UmbracoForms",
          "requestedVersion": "8.4.1",
          "resolvedVersion": "8.4.1",
          "vulnerabilitySeverity": "Moderate",
          "advisoryUrl": "https://github.com/advisories/GHSA-8m73-w2r2-6xxj",
          "transitiveDependencies": [
            {
              "name": "Microsoft.Data.OData",
              "resolvedVersion": "5.2.0",
              "severity": "Moderate",
              "advisoryUrl": "https://github.com/advisories/GHSA-mv2r-q4g5-j8q5"
            }
          ]
        }
      ]
    },
    "deprecations": {
      "legacy": "1",
      "criticalBugs": "0",
      "other": "0",
      "dependencies": [
        {
          "name": "anurse.testing.TestDeprecatedPackage",
          "requestedVersion": "1.0.0",
          "resolvedVersion": "1.0.0",
          "reason": "Legacy",
          "alternativeDependencies": [
            {
              "name": "Microsoft.AspNetCore.MVC",
              "version": "0.0.0"
            }
          ]
        }
      ]
    },
    "outdated": {
      "packages": "2",
      "dependencies": [
        {
          "name": "anurse.testing.TestDeprecatedPackage",
          "resolvedVersion": "1.0.0",
          "latestVersion": "2.0.0"
        },
        {
          "name": "UmbracoForms",
          "resolvedVersion": "8.4.1",
          "latestVersion": "8.7.1"
        }
      ]
    },
    "scannedDependencies": "36"
  }
}
```

To ensure scope is met here, we will only be taking what is outputted by the commands & parameters today & converting them to `json` output. Anything that the tool does not do today will be out of scope for this issue.

**Comment by syedadeel2** [comment]
I have written a quick PowerShell Script to export into CSV, until we get this feature in-built maybe that script will help someone

https://gist.github.com/syedadeel2/169b3d6c7c3a12c2054d8a465ce8c7b2

**Comment by erdembayar** [comment]
@JonDouglas 
Is this spec https://github.com/NuGet/Home/wiki/%5BSpec%5D-Machine-readable-output-for-dotnet-list-package already approved? If yes then I can work on this.

**Comment by JonDouglas** [comment]
@erdembayar That spec predates my time here. I wrote https://github.com/NuGet/Home/blob/dotnet-audit/proposed/2021/DotNetAudit.md#dotnet-audit---json instead which hasn't been reviewed yet.

**Comment by erdembayar** [comment]
@JonDouglas 
Only deciding on json format should be enough for this issue. How do we proceed? Create new spec md proposal based on https://github.com/NuGet/Home/wiki/%5BSpec%5D-Machine-readable-output-for-dotnet-list-package? One problem is December is not good timing for spec reviews, most people will be OOF.

**Comment by JonDouglas** [comment]
It is small enough and has two directions to make a small proposal. When would be ideal to work on it?

**Comment by erdembayar** [comment]
If @aortiz-msft is ok with this then I can start working next Monday.

**Comment by nkolev92** [comment]
One thing that we discussed as learnings when dealing with `dotnet list package` was that specs that have spent more than 3-6 months on the backburner need a refresher.

The idea behind that is that we're likely to have more relevant info now and we *might* have different policies by then. 

Remember to put specs in the Home repo as a PR!

**Comment by erdembayar** [comment]
Related issue https://github.com/dotnet/sdk/issues/22366

**Comment by erdembayar** [comment]
For my ref: https://blog.kellybrazil.com/2021/12/03/tips-on-adding-json-output-to-your-cli-app/

**Comment by marcselis** [comment]
Please consider this as high-prio.  The recent events with log4j make it very clear that an automatic scan in build pipelines is highly needed.  Having a machine-readable output is important to make builds fail whenever a vulnerable package is found.

**Comment by zivkan** [comment]
@marcselis do you have any suggestions about the json schema, feedback about whether it makes sense to you whether or not `--deprecated` and/or `--vulnerable` make sense in the same output, or require separate commands, anything else in the spec?

- https://github.com/NuGet/Home/pull/11446

**Comment by roryprimrose** [comment]
Hi @zivkan, thank you for working on this.

The primary use case here is automation processes that can interpret the results. It is therefore likely enough that these automation processes will be interested in more than one type of information. In our case, we are interested in all the possible package outcomes of outdated, depreciated and security vulnerabilities. Calculating and walking the package dependency tree (with transitive dependencies) can be really expensive so doing this three times for each type of outcome would be very inefficient.

I think it is important that the design here allows for developers to request one or more options for the type of information they are looking for. Where more than one option (of outdated, depreciated or vulnerability) is requested then allowing a single scan that includes all this information will be a lot faster overall.

**Comment by marcselis** [comment]
> @marcselis do you have any suggestions about the json schema, feedback about whether it makes sense to you whether or not `--deprecated` and/or `--vulnerable` make sense in the same output, or require separate commands, anything else in the spec?
> 
> * [Spec for machine readable json output for dotnet list package #11446](https://github.com/NuGet/Home/pull/11446)

No real suggestions for the json schema.  Having an output that is machine readable is the most important.  Giving the --deprecated and --vulnerable similar outputs is no problem, after all we usually know what arguments were passed executing the command.  But for --vulnerable having the CVE information is a MUST as we want to report on that.

Another suggestion I would like to make is to stop the program with a return code different than 0 when there are indeed --deprecated or --vulnerable packages detected.  That way we can detect that there is indeed a problem or not and skip the need to parse the output where there isn't.

**Comment by darakian** [comment]
Hey all 👋 

Stumbled on this thread by way of https://devblogs.microsoft.com/nuget/how-to-scan-nuget-packages-for-security-vulnerabilities/

I see you're using the github advisory database and I just want to point out that we have a graphql api available for direct consumption.
https://docs.github.com/en/graphql/reference/objects#securityadvisories

**Comment by JonDouglas** [comment]
@darakian Thank you kindly for the heads up. We will investigate further when we revisit this area shortly.

**Comment by erdembayar** [comment]
@JonDouglas 
Could we make this issue epic? I don't see option for it. I believe this issue is quite large, I created several related issues just for json output, so it need to be epic.

**Comment by nkolev92** [comment]
@erdembayar Can this track the main functionality? 

The follow up issues are independent and kind of add-ons right?

**Comment by erdembayar** [comment]
> @erdembayar Can this track the main functionality?
> 
> The follow up issues are independent and kind of add-ons right?

Currently `json` is 1st sub issue. Still this one need sub issues like `parseable`,`yml` output, making it epic helps with keep progress of what is going on.

**Comment by clairernovotny** [comment]
As was called out, license information is not in scope for this initially. I don't think we should have several different tools for listing package related information so it would make sense for license info to be included here sooner rather than later.

A few other thoughts:
- The ordering of the data should be deterministic. I.e., running it again should always return the same ordering. New packages should be inserted in the order. This will assist with diff's to see what changed between two versions of this file.
- License information maybe an SPDX, a URL, or embedded content.
  - For embedded content, we should record a hash of the file 
  - For URL's, can we proxy this server-side to get a hash? The concern is similar to icon images on third party servers.

**Comment by nkolev92** [comment]
> Currently json is 1st sub issue. Still this one need sub issues like parseable,yml output, making it epic helps with keep progress of what is going on.

I say create json and then let the community open issues for yml/parseable whatever. Those are add-ons. 
You don't have to implement all ideas.

**Comment by JonDouglas** [comment]
@erdembayar I do not believe we need an epic here. This issue is mostly resolved by https://github.com/NuGet/Home/wiki/%5BSpec%5D-Machine-readable-output-for-dotnet-list-package

Your proposal should be an updated version of this and scoped to providing machine-readable output for the human-readable output people see today.

Anything else at this point should be tracked in a separate issue and an epic can be made for the collection of improvements to the `dotnet list package` command.

**Comment by zivkan** [comment]
IMO we should either delete the spec in the wiki, or edit it to be nothing more than a link to the spec in the repo's main branch.

**Comment by erdembayar** [comment]
My ref: https://github.com/dotnet/diagnostics/blob/main/src/Tools/dotnet-counters/Exporters/ICounterRenderer.cs

**Comment by Balkoth** [comment]
Will there be a way to call into this from a c# application when you dont have the project checked out. I am specifically thinking about a git bare repositiory.

**Comment by KalleOlaviNiemitalo** [comment]
@Balkoth, because PackageReference items can be added by Directory.Build.props, I think supporting bare Git repositories would need a virtual file system for MSBuild. There is Microsoft.Build.FileSystem.MSBuildFileSystemBase but I don't know whether all I/O goes through that.

Added 2022-08-11: Not all I/O goes through MSBuildFileSystemBase; <https://github.com/dotnet/msbuild/issues/7876> would be a prerequisite.

**Comment by CoenraadS** [comment]
In the meantime, I made a powershell script to parse the output. Sharing incase it's useful for others:

<details>
<summary>Script</summary>

```
param (
    [Parameter(Mandatory)] 
    [string] $solutionPath)

[array] $rawOutput = dotnet list $solutionPath package --include-transitive

$projects = @{
}

$projectPackageList = New-Object System.Collections.ArrayList
$packageType = ""

ForEach ($line in $rawOutput)
{
    $line = $line.Trim()

    $projectTypeMatch = [regex]::Matches($line, "Project '(.*)' has the following package references")
    if ($projectTypeMatch.Count -ne 0)
    {
        $projectName = $projectTypeMatch.Groups[1].Value
        
        $projectPackageList = New-Object System.Collections.ArrayList

        $projects[$projectName] = $projectPackageList
    }
    else
    {
        if ($line.Length -eq 0)
        {
            continue
        }

        if ($line -Like "Top-level Package*")
        {
            $packageType= "Top"
        }
        elseif ($line -Like ("Transitive Package*"))
        {
            $packageType= "Transitive"
        }
        elseif ($packageType -eq "Transitive")
        {
            $packageTypeMatch = [regex]::Matches($line, "> ([^\s]+)\s+([^\s]+)")
            if ($packageTypeMatch.Count -ne 0)
            {
                $currentPackage = @{
                }

                $packageName = $packageTypeMatch.Groups[1].Value
                $resolvedVersion = $packageTypeMatch.Groups[2].Value
                $currentPackage["Name"] = $packageName;
                $currentPackage["ResolvedVersion"] = $resolvedVersion
                $currentPackage["Type"] = $packageType

                $projectPackageList.Add($currentPackage) | Out-Null 
            }
        }
        elseif ($packageType -eq "Top")
        {
            $packageTypeMatch = [regex]::Matches($line, "> ([^\s]+)\s+([^\s]+)\s+([^\s]+)")
            if ($packageTypeMatch.Count -ne 0)
            {
                $currentPackage = @{
                }

                $packageName = $packageTypeMatch.Groups[1].Value
                $requestedVersion = $packageTypeMatch.Groups[2].Value
                $resolvedVersion = $packageTypeMatch.Groups[3].Value
                $currentPackage["Name"] = $packageName;
                $currentPackage["RequestedVersion"] = $requestedVersion
                $currentPackage["ResolvedVersion"] = $resolvedVersion
                $currentPackage["Type"] = $packageType

                $projectPackageList.Add($currentPackage) | Out-Null 
            }
        }
    }
}

$projects | ConvertTo-Json > out.json
```
</details>

<details>
<summary>Example Output</summary>

```
{
    "Project1": [
        {
            "ResolvedVersion": "5.9.0.4768",
            "Name": "Dependancy1",
            "Type": "Top",
            "RequestedVersion": "[5.*,)"
        },
        {
            "ResolvedVersion": "2.10.0.2656",
            "Name": "Dependancy2",
            "Type": "Transitive"
        }
    ],
    "Project2": [
        {
            "ResolvedVersion": "5.9.0.4768",
            "Name": "Dependancy1",
            "Type": "Top",
            "RequestedVersion": "[5.*,)"
        },
        {
            "ResolvedVersion": "1.2.3.4
            "Name": "Dependancy3",
            "Type": "Transitive"
        }
    ]
}
```
</details>

**Comment by sensslen** [comment]
Thanks a lot for this script. However this script ins not culture neutral. Unfortunately I was unable to change the culture with which the dotnet command is run in powershell.

**Comment by Vandersteen** [comment]
Is there any progress on this issue ?

**Comment by erdembayar** [comment]
> Is there any progress on this issue ?

I'm working on implementation, since this's the 1st ever json output for .net cli tooling still discovering new thing. 
I need community input for below spec revision: https://github.com/NuGet/Home/pull/11983

**Comment by dburriss** [comment]
Awesome to see the progress on this @erdembayar !
Will this be assigned to a milestone at any point? I have a usecase and I was going to parse the text but if it is feasible to wait for this to ship I would prefer that.

**Comment by erdembayar** [comment]
> Awesome to see the progress on this @erdembayar Erick Yondon FTE ! Will this be assigned to a milestone at any point? I have a usecase and I was going to parse the text but if it is feasible to wait for this to ship I would prefer that.

Thank you for your interest, I just merged the [PR](https://github.com/NuGet/NuGet.Client/pull/4855) for json output, in that PR I refactored the coupled code to MVC style code so next time someone can add `yaml`,`xml` outputs with little effort. 
Most likely this would be in NuGet 6.5 (VS17.5), I still need to complete https://github.com/dotnet/sdk/pull/28564 by next week.

**Comment by kaylumah** [comment]
Very cool :) hoop to see this soon :)

**Comment by erdembayar** [comment]
If anyone want to test out, it's already in public nightly build: https://github.com/dotnet/installer#table
We'll update the doc soon: https://github.com/NuGet/docs.microsoft.com-nuget/issues/2922
In case of there is any issue with generating json output then it will return `1` instead of `0` if you're using it for CI pipeline automation, so you can check what is going on.


![image](https://user-images.githubusercontent.com/8766776/204866596-575d1636-cfbf-42dc-878d-90ff02bf46a2.png)

![image](https://user-images.githubusercontent.com/8766776/204866720-f3c4104f-c18b-4c7a-b728-a04472bb61fa.png)

![image](https://user-images.githubusercontent.com/8766776/204867552-e3ac97c7-181a-4232-9557-5e971b8414a3.png)

![image](https://user-images.githubusercontent.com/8766776/204867675-6a355232-0c6e-4636-a566-471cfc08ac21.png)

![image](https://user-images.githubusercontent.com/8766776/204868682-43d8aa1e-a896-413d-b686-64308163aff7.png)

**Comment by erdembayar** [comment]
Alternatively, you can install latest binary from here `.\dotnet-install.ps1 -Channel 7.0.2xx -Quality daily`

**Comment by Postlagerkarte** [comment]
@erdembayar Thanks for the great work! However, I am a bit confused. The documentation has been updated a few days ago (https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package) - so I was assuming that this feature is ready to use in production. Sadly the latest .NET 7.0.2 from January 10, 2023 contains .NET SDK 7.0.102 and is missing the feature. I know that I can manually install the latest build but I want to use it within an Azure Pipeline. Can you advise?

**Comment by erdembayar** [comment]
> @erdembayar Thanks for the great work! However, I am a bit confused. The documentation has been updated a few days ago (https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package) - so I was assuming that this feature is ready to use in production. Sadly the latest .NET 7.0.2 from January 10, 2023 contains .NET SDK 7.0.102 and is missing the feature. I know that I can manually install the latest build but I want to use it within an Azure Pipeline. Can you advise?

Here is the [PR#32855](https://github.com/dotnet/docs/pull/32855) for doc change. I explicitly asked not to merge until it's GA, but someone merged it, considering it was for `main` branch not our `live` branch of docs, I didn't ask to revert. 
But it looks like they [moved all changes](https://github.com/dotnet/docs/pull/33394) from `main` to `live` 2 days ago even though not all new features are GA yet. I'll ask why it happened, by the way this change is in NET SDK 7.0.2xxx, not in 7.0.102.
Sorry for the confusion, most likely we just revert the change until NET SDK 7.0.2xxx is GA.

**Comment by Postlagerkarte** [comment]
Thanks for clarifying! Any idea when NET SDK 7.0.2xxx will be GA?

**Comment by erdembayar** [comment]
> Thanks for clarifying! Any idea when NET SDK 7.0.2xxx will be GA?

Sorry, I couldn't tell exactly, but looking at https://dotnet.microsoft.com/en-us/download/dotnet/7.0 release dates, it usually happens every 1 month, so I estimate sometime in Feb,2023.

**Comment by kaylumah** [comment]
The sdk for `7.0.200` has been released but using `dotnet list package --format json` results in 

```
Unrecognized command or argument '--format'
```

**Comment by erdembayar** [comment]
> > Thanks for clarifying! Any idea when NET SDK 7.0.2xxx will be GA?
> 
> Sorry, I couldn't tell exactly, but looking at https://dotnet.microsoft.com/en-us/download/dotnet/7.0 release dates, it usually happens every 1 month, so I estimate sometime in Feb,2023.

This feature is GA now with .NET SDK 7.0.200 :partying_face:, please download from https://dotnet.microsoft.com/en-us/download/dotnet/7.0
