### ISSUE TITLE
Restore can't float to a pre-release package if non-prerelease is referenced

### ISSUE THREAD

**Issue by KirillOsenkov** [NuGet/Home#7754]
Nuget.exe 4.9.2.5706

Have a simple SDK-style project with this PackageReference:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Language.Intellisense" Version="16.0.379-g4a55b0e4f2" />
  </ItemGroup>
```

Use this NuGet.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<packageSources>
		<add key="Nuget Official" value="https://api.nuget.org/v3/index.json" />
		<add key="VS Editor" value="https://vside.myget.org/F/vssdk/api/v3/index.json" />
	</packageSources>
</configuration>
```

Run Nuget.exe restore on the .sln or .csproj.

**Expected:** should pick `https://www.nuget.org/packages/Microsoft.VisualStudio.ImageCatalog/16.0.28527-pre` and succeed

**Actual:**
```
 NU1103: Unable to find a stable package Microsoft.VisualStudio.ImageCatalog with version (>= 16.0.27828)
      - Found 28 version(s) in Nuget Official [ Nearest version: 16.0.28205-pre ]
      - Found 1 version(s) in VS Editor [ Nearest version: 15.6.27415 ]
      - Found 0 version(s) in Microsoft Visual Studio Offline Packages
      - Found 0 version(s) in CliFallbackFolder
```

This is the package that requires a non-prerelease MS.VS.ImageCatalog:
https://vside.myget.org/feed/vssdk/package/nuget/Microsoft.VisualStudio.Language.Intellisense/16.0.379-g4a55b0e4f2

**Comment by KirillOsenkov** [comment]
[NuGet7754.zip](https://github.com/NuGet/Home/files/2819506/NuGet7754.zip)

Repro solution ^^

**Comment by nkolev92** [comment]
It's been a long day :)

Restore historically has only allowed stable versions, if the dependency is declared as a stable version. 
So it's a limitation and by design. 

There are 2 options here:
* Get the package owners to publish the missing package.
* Reference 16.0.28205-pre manually from the csproj.
