### ISSUE TITLE
Signing: Enabled Repo to require client verification of every package as repo signed -- via RepositorySignatures/5.0.0 resource

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#7759]
Unfortunately, due to #7574, we cannot flip the switch on nuget.org to say that all packages are signed.
We plan to change the protocol from 4.9.0 to 5.0.0 and the server will ignore that 4.9.0 ever existed.

@dtivel @PatoBeltran @loic-sharma @rido-min

**Comment by loic-sharma** [comment]
The server issue is here: https://github.com/NuGet/NuGetGallery/issues/6841

**Comment by loic-sharma** [comment]
@rrelyea The `RepositorySignatures/5.0.0` resource is live on DEV: https://apidev.nugettest.org/v3-index/repository-signatures/5.0.0/index.json

**Comment by loic-sharma** [comment]
Repository signed package - [Newtonsoft.Json 10.0.2](https://dev.nugettest.org/packages/Newtonsoft.Json/10.0.2)
Repository + author signed package - [System.Rido 1.0.1](https://dev.nugettest.org/packages/System.Rido/1.0.1)
Author signed package - [E2E.SignedPackage 2019.1.28-v094929](https://dev.nugettest.org/packages/E2E.SignedPackage/2019.1.28-v094929)
Unsigned package - [NodaTime 1.0.0](https://dev.nugettest.org/packages/NodaTime/1.0.0)
Package that depends on all previous packages - [Loshar.Bad.Depends 1.0.0](https://dev.nugettest.org/packages/Loshar.Bad.Depends/1.0.0)

**Comment by rrelyea** [comment]
@loic-sharma  --Haven't had a chance to test until now. Is this a problem with dev?
Happy to dig in on my side if you think that it is still deployed and fully functional.
Update: actually, let me debug a bit...

> C:\repos\nuget.client\artifacts\repository50>type ..\nuget.config
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>  <packageSources>
>     <clear />
>     <add key="nugetDev" value="https://apidev.nugettest.org/v3-index/repository-signatures/5.0.0/index.json" />
>  </packageSources>
> </configuration>
> 
> C:\repos\nuget.client\artifacts\repository50>dotnet add package nodatime -v 1.0.0
>   Writing C:\Users\rrelyea\AppData\Local\Temp\tmpE910.tmp
> info : Adding PackageReference for package 'nodatime' into project 'C:\repos\nuget.client\artifacts\repository50\repository50.csproj'.
> log  : Restoring packages for C:\repos\nuget.client\artifacts\repository50\repository50.csproj...
> **error: Unable to load the service index for source https://apidev.nugettest.org/v3-index/repository-signatures/5.0.0/index.json.**
> error:   The source does not have the 'version' property.
> 
> C:\repos\nuget.client\artifacts\repository50>dotnet add package newtonsoft.json -v 10.0.2
>   Writing C:\Users\rrelyea\AppData\Local\Temp\tmp543E.tmp
> info : Adding PackageReference for package 'newtonsoft.json' into project 'C:\repos\nuget.client\artifacts\repository50\repository50.csproj'.
> log  : Restoring packages for C:\repos\nuget.client\artifacts\repository50\repository50.csproj...
> error: Unable to load the service index for source https://apidev.nugettest.org/v3-index/repository-signatures/5.0.0/index.json.
> error:   The source does not have the 'version' property.
>

**Comment by loic-sharma** [comment]
It looks like you're using the wrong service index URL. It should be `https://apidev.nugettest.org/v3-index.json`
