### ISSUE TITLE
MultipartWebRequest::CreateMultipartRequest should use "\r\n" explicitly and not Environment.NewLine

### ISSUE THREAD

**Issue by bradbeck** [NuGet/Home#776]
[`MultipartWebRequest::CreateMultipartRequest`](http://nuget.codeplex.com/SourceControl/latest#src/Core/Http/MultipartWebRequest.cs) line 63 should use "\r\n" explicitly and not `Environment.NewLine` in order adhere to the [multipart content-type spec](http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html). When running `nuget` on unix via `mono` this causes `nuget push ...` operations to fail because the resulting `PUT` requests are malformed.

Reference: http://stackoverflow.com/questions/30807139/mono-nuget-exe-push-produces-invalid-multipart-put-request

**Comment by feiling** [comment]
Code fix checked into NuGet.V2.

**Comment by feiling** [comment]
Dependency updated in nuget v3 so that nuget v3 command line is also fixed.

**Comment by Knele83** [comment]
lbipzelccvvypsgq
