### ISSUE TITLE
Sync-Package installs the package into all projects - does not consolidate

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#7761]
## Details about Problem

NuGet product used (Package Manager Console):

NuGet version (4.9.2):

dotnet.exe --version (if appropriate):

VS version (if appropriate): 15.9.4

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Two projects in solution. ClassLibrary1 and ClassLibrary2

2. Install Newtonsoft.Json into ClassLibrary1.

3. Open Package Mangager Console.

4. With ClassLibrary1 selected in the console use 'sync-package Newtonsoft.Json'.

Expected result:

Nothing happens. I was assuming this was the same as consolidate available in the UI which fixes the NuGet package version to be the same in all projects but only in those projects where the package is installed.

Actual result:

Newtonsoft.Json is installed into ClassLibrary2.

Looking at the [SyncPackageCommand](https://github.com/NuGet/NuGet.Client/blob/55c6c244323397605392511ecf34923ebef72241/src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Cmdlets/SyncPackageCommand.cs#L95-L97) it iterates over all projects, which are not the default project, and then installs this package into all projects.

If this is by design then this is can be closed, but I was expecting this to be the Package Manager Console equivalent of the consolidate command. The comment at the top of the class says: `This command consolidates the specified package into the specified project.` but that does not seem to be the case.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
@mrward 

I looked through the history and it seems like this is done on purpose. 
I don't have the exact context on the requirements when it was implemented, so that's the best I can provide.

I haven't any requests from customers to change it, so I'd be hesitant to change anything about this.

**Comment by mrward** [comment]
OK. It seems odd to me that the comment says consolidate but it does not consolidate. Just installs the same NuGet package into every project, even if the project did not have that NuGet package before. Seems like this would be a feature of the Install-Package command. Anyway I can see this is how this particular NuGet command has always worked so closing this.
