### ISSUE TITLE
How to add binding redirects in web config through NuGet packages installation

### ISSUE THREAD

**Issue by skofman1** [NuGet/Home#7763]
@GanesanRengasamy commented on [Sun Feb 03 2019](https://github.com/NuGet/NuGetGallery/issues/6873)

Hi Everyone, 

I have prepared the sample MVC4 NuGet package for my dll with the dependent of the following NuGet packages compression.base, officeChart.base. I have installed my custom MVC4 NuGet pacakge in ASP.NET MVC project with framework version 4.5.2. After installation completed all dependent assembly entries are placed under the binding redirect tag of the webconfig file. But, I didn't add this entry in my NuGet packages and I don't aware regarding how this entries are added after install my NuGet packages. 

`<dependentAssembly>
        <assemblyIdentity name="Compression.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4451.0.4" />
</dependentAssembly>
<dependentAssembly>
        <assemblyIdentity name="OfficeChart.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4451.0.4" />
 </dependentAssembly>`

Could you please update the details regarding how this entries are placed in the web config file while install the NuGet packages. 

Also, Could you please suggest me how can I overwrite this entries from my side through NuGet packages installation like below 

`<dependentAssembly>
        <assemblyIdentity name="Compression.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4400.0.4" />
</dependentAssembly>
<dependentAssembly>
        <assemblyIdentity name="OfficeChart.Base" publicKeyToken="3d67ed1f87d44c89" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.4451.0.4" newVersion="1.4400.0.4" />
 </dependentAssembly>`

Could you please suggest me regarding this?

Thanks,

Ganesan R.

**Comment by nkolev92** [comment]
@GanesanRengasamy 

When you use packages.config, NuGet automatically adds the binding redirects based on your dependencies. 

You cannot customize how NuGet adds binding redirects. You can make NuGet reevaluate them however. 

Relevant information: 
https://docs.microsoft.com/en-us/nuget/tools/ps-ref-add-bindingredirect
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

You can always disable assembly redirection by NuGet and manage them manually (note that this can be complex.)
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#bindingredirects-section
