### ISSUE TITLE
Nuget pack fails with multi-target csproj

### ISSUE THREAD

**Issue by JeremyCaney** [NuGet/Home#7765]
A year or so ago, @mm6502 opened [a bug report](https://github.com/NuGet/Home/issues/5832) detailing how `nuget pack` would look in the wrong location for the build files when packing a multi-targeted project, resulting in an error similar to:
> Error NU5012: Unable to find 'bin\release\\{Project}\bin\release\'. Make sure the project has been built.

If you are going through the **NuGet Pack** task on **Azure DevOps**, the error will be wrapped as follows ([related report](https://github.com/Microsoft/azure-pipelines-tasks/issues/5006)):
> ##[error]The nuget command failed with exit code(1) and error(Unable to find 'bin\release\\{Project}\bin\release\'. Make sure the project has been built.)

This [issue was closed](https://github.com/NuGet/Home/issues/5832#issuecomment-327302225) since a workaround was provided. The workaround, however, is insufficient for the reasons detailed below; this should instead be reopened and treated as a bug.

## Workaround
The workaround suggested was to use `msbuild /t:pack` instead. This is insufficient because:
- This is a **bug**; from the user perspective it is expected that `nuget` will work the same on multi-target projects as it does on single-target projects.
- Even if this is an expected limitation of the product, the error message is unintuitive, and especially since the source directory cannot be specified by the user.
- This is [impacting downstream products](https://github.com/Microsoft/azure-pipelines-tasks/issues/5006), such as **Azure DevOps** (formerly **Visual Studio Team Services**).
- `msbuild` is not a comparable substitute, as it doesn't permit e.g. disabling the build, or specifying a version number (without extra tooling). It's also not the recommended approach for **Azure DevOps**.

## Details about Problem
- NuGet product used: **NuGet.exe**
- NuGet version: **4.9.2**
- dotnet.exe --version: **2.2.103** (N/A)
- VS version: **15.9.5** (N/A)
- OS version: **win10 Pro v1809 (17763.253)** (N/A)
- Worked before? If so, with which NuGet version: **Unknown**

## Detailed repro steps so we can see the same problem
1. Create a new C# Class Library (.NET Standard) project targeting `netstandard2.0`.
2. Edit the `csproj` file to add target framework `net4`:
  `<TargetFrameworks>net4;netstandard2.0</TargetFrameworks>`
3. Build and pack with `msbuild` (to check the build passes and package is created):
  `nuget restore`
  `msbuild Test.csproj /t:Clean,Build,Pack /p:Configuration=Release`
4. Pack with `nuget`:
  `nuget pack Test.csproj -Build -p Configuration=Release`
> **Note:** The above are a condensed version of the steps originally reported by @mm6502.

### Verbose Logs
```
NuGet Version: 4.9.2.5706
Attempting to build package from 'Test.csproj'.
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Apps\Development\IDEs\Visual Studio 2017\MSBuild\15.0\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
Error NU5012: Unable to find 'bin\release\Test\bin\release\'. Make sure the project has been built.
NuGet.Packaging.Core.PackagingException: Unable to find 'bin\release\Test\bin\release\'. Make sure the project has been built.
   at NuGet.CommandLine.ProjectFactory.BuildProject()
   at NuGet.CommandLine.ProjectFactory.CreateBuilder(String basePath, NuGetVersion version, String suffix, Boolean buildIfNeeded, PackageBuilder builder)
   at NuGet.Commands.PackCommandRunner.BuildFromProjectFile(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

### Sample Project
See @mm6502's [original bug report](https://github.com/NuGet/Home/issues/5832) for a sample project.

**Comment by chris-strauss** [comment]
Thanks for opening this issue.  It's something that should be fixed.

**Comment by nkolev92** [comment]
@JeremyCaney 

I believe that you may be some confusion about the resolution of that issue. 

NuGet ships 2 implementations of pack. 
The nuget.exe one, the primitive nuspec based pack, and the https://www.nuget.org/packages/NuGet.Build.Tasks.Pack/ or what's basically shipped with dotnet.exe. 

The tooling for SDK based projects is dotnet.exe/targets pack. 

The gap in question is the following issue https://github.com/NuGet/Home/issues/4491. 

It's not about single vs multi tfm projects. 
It's about nuget.exe and SDK based projects **nuspec***less*.

Based on my above comments I'd like to dup this issue to https://github.com/NuGet/Home/issues/4491.

**Comment by nkolev92** [comment]
Closing per my above comment.

**Comment by cyberkito** [comment]
> 
> 
> @JeremyCaney
> 
> I believe that you may be some confusion about the resolution of that issue.
> 
> NuGet ships 2 implementations of pack.
> The nuget.exe one, the primitive nuspec based pack, and the https://www.nuget.org/packages/NuGet.Build.Tasks.Pack/ or what's basically shipped with dotnet.exe.
> 
> The tooling for SDK based projects is dotnet.exe/targets pack.
> 
> The gap in question is the following issue #4491.
> 
> It's not about single vs multi tfm projects.
> It's about nuget.exe and SDK based projects **nuspec**_less_.
> 
> Based on my above comments I'd like to dup this issue to #4491.

I used **dotnet pack** and got my project packed up with multiple platforms. Nuget pack did not work.

**Comment by Njoro007** [comment]
How does one then change the Package Versioning, since Nuget Pack is not an option for multi-Targeting?

**Comment by warpedgeoid** [comment]
As @Njoro007 said, this is an issue for packages with versions derived from pipeline variables in, e.g., Azure DevOps.

**Comment by scholtz** [comment]
i confirm that nuget pack does not work, and dotnet pack works with target frameowrks flag..

you should not close such bugs, but rather fix it.. it should not be that difficult

**Comment by tiomny** [comment]
@nkolev92 `dotnet pack` either `msbuild -t:pack` do not support option `-IncludeReferencedProjects`. This option is required sometimes.
Please reopen this ticket.
