### ISSUE TITLE
Make lock file behavior more flexible

### ISSUE THREAD

**Issue by ocean-orrick** [NuGet/Home#7769]
Hi, I would like to report a scenario that makes a case for the implementation of the proposed IgnoreLockFileForRestore property at a minimum, and more ideally leads to more flexible behavior of lock file based restore, especially in regards to the content-hash.

I make changes to LibA and build it locally, which outputs a prerelease versioned nuget package which I include in my local feed.
I test these changes in AppB, and a lock file is generated using the hash from my local feed.
I push LibA to our build server, which publishes the same prerelease version to our team feed but which ends up having a different contenthash.
I push AppB to our build server and the build fails as the hash for LibA in the lock file is different since the build server only has access to the team feed and not my local drive.

One option for us is to add a build step on the build server that deletes the lock file before running restore when on a feature branch, as we only care about the reproducible builds for tagged releases on master. However, this would be better implemented by specifying the IgnoreLockFileForRestore.

Better than that would to be the option to change the strictness of the comparison. For our use case, we would be content with a minimally strict locking mechanism that only compares package version (I believe this would be more equivalent to packages.config behavior anyhow). More ideally, if a hashing algorithm that cared about the metadata and files matching without regards to whatever factor causes a different hash when it is built on different machines, we would use that.

**Comment by anangaur** [comment]
If you enabled lock files - today, by default, the lock files are overwritten if package dependencies or the content hash change across `restore` operations. I guess this is what you want during development mode. This is essentially `IgnoreLockFileOnRestore` i.e. lock files are overwritten if required and does not fail your build.

To ensure build repeatability and fail if NuGet cannot ensure it, you would need to turn on the `RestoreLockedMode` to `true`. This can be put under condition like I illustrated on my [blog post](https://blog.nuget.org/20181217/Enable-repeatable-package-restores-using-a-lock-file.html#how-does-nuget-use-the-lock-file):
```
<PropertyGroup>
       <RestoreLockedMode Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</RestoreLockedMode>
</PropertyGroup> 
```
You can either set `ContinuousIntegrationBuild` property when you build on `master` or replace `ContinuousIntegrationBuild` with another property that makes more sense.

I would be interested to know if this does not work for you and why?

**Comment by ocean-orrick** [comment]
Once the lock file is present, even if I set RestoreLockedMode to false, it still fails the restore/build for SHA mismatch.

From these docs, I would expect as much: https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#out-of-sync

Building the same commit on build server which has access to a different content-hash package of the same version will not qualify for any of the out-of-sync conditions.

**Comment by anangaur** [comment]
> Once the lock file is present, even if I set RestoreLockedMode to false, it still fails the restore/build for SHA mismatch.

I just checked the behavior with .NET Core SDK 2.2.104 and restore doesn't fail if `RestoreLockedMode` is `false`

Can you provide a repro and let us know the version of NuGet or .NET Core SDK or VS that you are using?

**Comment by ocean-orrick** [comment]
The projects I am testing on are net40 projects. NuGet version 4.9.2.5706. VS2017 15.9.6

**Comment by ocean-orrick** [comment]
I can work on putting together a little example repo for repro if there's not anything that immediately jumps out about those versions. I imagine the .net 4.0 projects might be the issue though?

**Comment by anangaur** [comment]
If you are using PackageReference, the lock file feature should just work as expected. We would good with any sample repro as long as it is using PackageReference.

**Comment by nkolev92** [comment]
@sxmanton Any chance you can provide us a repro as @anangaur requested. 
Thanks

**Comment by ocean-orrick** [comment]
@nkolev92 Sorry, been pretty busy with other things but hopefully I can find some time to put together a repro in the next few days

**Comment by anangaur** [comment]
@sxmanton Were you able to work on the repro. If not, can we close this issue for now and you can create another issue when you encounter this again?

**Comment by ocean-orrick** [comment]
@anangaur I don't anticipate having time to work on the repro any time soon. Feel free to close for now if you wish

**Comment by anangaur** [comment]
Thanks @sxmanton
