### ISSUE TITLE
MSBuild Pack creates bad file structure for source code content files (*.pp)

### ISSUE THREAD

**Issue by NerdyDuck** [NuGet/Home#7774]
VS: 15.9.5
NuGet.Build.Tasks.Pack: 4.9.2, 4.9.3, 5.0.0

I'm working on a multi-framework library (net461;netstandard2.0) and create the NuGet package during build time with the MSBuild Pack target. Libraries and dependencies look fine, but I also have two source files (or more exactly source code transformation files) that need to be added to the target project with a build action of Compile:
- HResult.vb.pp should be added to VB.NET project, no matter which TxM
- HResult.cs.pp should be added to any C# project, also Txm agnostic.

My first attempt was this .csproj file snippet:

``` xml
<ItemGroup>
  <Content Include="HResult.cs.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
  </Content>
  <Content Include="HResult.vb.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
  </Content>
</ItemGroup>
```

Which resulted in this .nuspec file snippet, and a matching file structure in the package:

``` xml
<contentFiles>
  <files include="cs/net461/HResult.cs.pp" buildAction="Compile" />
  <files include="cs/netstandard2.0/HResult.cs.pp" buildAction="Compile" />
  <files include="cs/net461/HResult.vb.pp" buildAction="Compile" />
  <files include="cs/netstandard2.0/HResult.vb.pp" buildAction="Compile" />
</contentFiles>
```
Obviously, the pack command did not recognize the .vb.pp file to be VB, and put it into the cs folder, so that won't work. Also, I didn't like the duplication of files, when `any` instead of specifics TxMs would do, but I can see that this not a decision that the Pack command can make. So I tried to fiddle with the paths to get the contentFile structure that I know to work from previous packages: `/contentFiles/cs/any/HResult.cs.pp` and `/contentFiles/vb/any/HResult.vb.pp` .

``` xml
<ItemGroup>
  <Content Include="contentFiles\cs\any\HResult.cs.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
  </Content>
  <Content Include="contentFiles\vb\any\HResult.vb.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
  </Content>
</ItemGroup>
```

I had several attempts with varying folder structures, but the result was more or less the one below.

``` xml
<contentFiles>
  <files include="cs/net461/contentFiles/cs/any/HResult.cs.pp" buildAction="Compile" />
  <files include="cs/netstandard2.0/contentFiles/cs/any/HResult.cs.pp" buildAction="Compile" />
  <files include="cs/net461/contentFiles/vb/any/HResult.vb.pp" buildAction="Compile" />
  <files include="cs/netstandard2.0/contentFiles/vb/any/HResult.vb.pp" buildAction="Compile" />
</contentFiles>
```

So any structure I create manually is just appended to the language/TxM structure created automatically. That may work for many occasions - especially when the content is completely language and TxM agnostic - , but I does not work for me. So after digging into the code of the Pack .targets file, I came up with the PackagePath property to add to my content items:

``` xml
<ItemGroup>
  <Content Include="contentFiles\cs\any\HResult.cs.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
    <PackagePath>\contentFiles\cs\any\HResult.cs.pp</PackagePath>
  </Content>
  <Content Include="contentFiles\vb\any\HResult.vb.pp">
    <Pack>true</Pack>
    <BuildAction>Compile</BuildAction>
    <PackagePath>\contentFiles\vb\any\HResult.vb.pp</PackagePath>
  </Content>
</ItemGroup>
```

Now this created exactly the file structure in the NuGet package that I expected, but, alas, now the .nuspec file hasn't any &lt;contentFiles&gt; elements!

I dug around for a while to find out why adding the PackagePath property would stop creating contentFile elements, but couldn' find anything.

Any ideas what I could try to get the structure I want (besides authoring the .nuspec file myself, again)? Thanks for any input!

Aside from everything else, the Pack target clearly has problems with languages other than cs. I think I saw a TODO in the code to improve that.

**Comment by nkolev92** [comment]
Thanks for creating this issue. I have a couple of ideas on how you can address your scenario, but I'll try to address the rest of your questions/comments. 


> Obviously, the pack command did not recognize the .vb.pp file to be VB, and put it into the cs folder, so that won't work. Also, I didn't like the duplication of files, when `any` instead of specifics TxMs would do, but I can see that this not a decision that the Pack command can make

You are right about the tfm part. When the build action is compile, pack does not use any. The TODO you've seen is likely the task to get the language of the project. https://github.com/NuGet/Home/issues/4100

Files having a language denominator in the name is not the common scenario. So pack figuring out that .vb.pp and .cs.pp don't belong in the same folder would special casing one single scenario. 

> Now this created exactly the file structure in the NuGet package that I expected, but, alas, now the .nuspec file hasn't any <contentFiles> elements!

I did not find that to be the case. 

I tested on my end and: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="HResult.cs.pp" BuildAction="Compile"/>
    <Content Include="HResult.vb.pp" BuildAction="Compile"/>
  </ItemGroup>
</Project>
```

Ended up with the following nuspec:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>ClassLibrary4</id>
    <version>1.0.0</version>
    <authors>ClassLibrary4</authors>
    <owners>ClassLibrary4</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETFramework4.6.1" />
      <group targetFramework=".NETStandard2.0" />
    </dependencies>
    <contentFiles>
      <files include="cs/net461/HResult.cs.pp" buildAction="Compile" />
      <files include="cs/netstandard2.0/HResult.cs.pp" buildAction="Compile" />
      <files include="cs/net461/HResult.vb.pp" buildAction="Compile" />
      <files include="cs/netstandard2.0/HResult.vb.pp" buildAction="Compile" />
    </contentFiles>
  </metadata>
</package>
```

Note that Pack="true" is the default for content files, so it's redundant to have it set to true.

The following also worked on end: 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="HResult.cs.pp" BuildAction="Compile">
      <PackagePath>contentFiles\cs\any</PackagePath>
    </Content>
    <Content Include="HResult.vb.pp" BuildAction="Compile">
      <PackagePath>contentFiles\vb\any</PackagePath>
    </Content>
  </ItemGroup>
</Project>
```

**Comment by nkolev92** [comment]
You can also use the extension targets like in: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#targetsfortfmspecificcontentinpackage

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
  </PropertyGroup>
  
  <PropertyGroup>
  <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);CustomContentTarget</TargetsForTfmSpecificContentInPackage>
</PropertyGroup>

<Target Name="CustomContentTarget">
  <ItemGroup>
    <TfmSpecificPackageFile Include="HResult.cs.pp">
      <PackagePath>contentFiles/cs/$(TargetFramework)</PackagePath>
    </TfmSpecificPackageFile>

    <TfmSpecificPackageFile Include="HResult.vb.pp">
      <PackagePath>contentFiles/vb/$(TargetFramework)</PackagePath>
    </TfmSpecificPackageFile>

  </ItemGroup>
</Target>  

</Project>

```

**Comment by NerdyDuck** [comment]
Now that did the trick! I added a BuildAction property and used 'any' instead of $(TargetFramework) in the PackagePath to avoid duplicating the files (as they are fine for any Tfm), although that netted me two NU5118 warnings.

```xml
<Target Name="CustomContentTarget">
  <ItemGroup>
    <TfmSpecificPackageFile Include="contentFiles\cs\any\HResult.cs.pp">
      <PackagePath>contentFiles/cs/any</PackagePath>
      <BuildAction>Compile</BuildAction>
    </TfmSpecificPackageFile>
     <TfmSpecificPackageFile Include="contentFiles\vb\any\HResult.vb.pp">
      <PackagePath>contentFiles/vb/any</PackagePath>
      <BuildAction>Compile</BuildAction>
    </TfmSpecificPackageFile>
  </ItemGroup>
</Target>
```

The resulting .nuspec (and the .nupkg file layout) is exactly as I wanted it.

```xml
<contentFiles>
  <files include="cs/any/HResult.cs.pp" buildAction="Compile" />
  <files include="vb/any/HResult.vb.pp" buildAction="Compile" />
</contentFiles>
```
I've been tinkering with NuGet package creation for some time now, but I completely missed those extension point targets. Thanks for making me aware to them!

**Comment by nkolev92** [comment]
Closing this per the above comment.
