### ISSUE TITLE
Dependency issue: version 1.2.3 turns into 1.2.2.2

### ISSUE THREAD

**Issue by ipavlu** [NuGet/Home#7775]
The issues seem to happen to a .net core project and to .net 4.7.2 project. they are both targeting a nuget net standard package on nuget.org originally created by a project in the same solution, but there are no references on csproj from the two projects with dependency issues.

Everything says, that I am targetting GreenSuperGreen.Benchmarking.NetStandard.dll version 1.2.3 but looking on actually built binaries it always goes with version 1.2.2.2

It seems as if 1.2.3 is resolved as 1.2.3.0 and when not found on nuget.org then it is going for a closest lower version which is 1.2.2.2 even when 1.2.3 version exists.

I created the corresponding tag on the github:
https://github.com/ipavlu/GreenSuperGreen/releases/tag/dependencyissue

and zipped tag with sources can be found here:
https://github.com/ipavlu/GreenSuperGreen/archive/dependencyissue.zip

I tried to move to 4 numbered versions. That means GreenSuperGreen.Benchmarking.NetStandard.dll version 1.2.5.1,
but consuming project again makes decission to target 1.2.4.1:
      "GreenSuperGreen.Benchmarking.NetStandard/1.2.5.1": {
        "dependencies": {
          "Concurrent.FastReflection.NetStandard": "1.0.1",
          "GreenSuperGreen.NetStandard": "1.2.5.1",
          "System.Collections.Immutable": "1.5.0"
        },
        "runtime": {
          "lib/netstandard2.0/GreenSuperGreen.Benchmarking.NetStandard.dll": {
            "assemblyVersion": "1.2.4.1",
            "fileVersion": "1.2.4.1"
          }
        }
      },

Thanks for any help.

Nuget Package Manager 4.6.0
Package Manager Host  Version: 4.9.3.5777

Same on OS Win10 Home and Win10 Professional but data gathered on:
Microsoft Windows 10 Home, 10.0.17134 N/A Build 17134

Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.03056
C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
GitHub.VisualStudio   2.6.0.6193

**Comment by nkolev92** [comment]
Thanks for creating this issue @ipavlu 

Unfortunately I'm having a bit trouble following. 

NuGet will never resolve a version smaller than the defined one. 

I'm not sure how the assets file snippet given relates to 1.2.3 and 1.2.3.0 version. 

Can you point to a specific project and explain what's the given, what you expect and what's actually happening.

**Comment by ipavlu** [comment]
Hi @nkolev92,

it was simple scenario, DotNet or DotNetCore project depends on NetStandard package and for some reason for some versions it was correct for other no.

The solution seems to be for .Net472 and NetCore2.1 to set in csproj this:
`<PreserveCompilationContext>false</PreserveCompilationContext>`

When it is set to false it starts behaving as expected.
Otherwise sometimes the version is overridden to take some lower version instead.

I am not sure if that is desided outcome if the setting is missin, but it felt pretty random and I have not found any info about this elsehwere. The main issue is from where the overriding setting came?

Thanks.

ipavlu

**Comment by nkolev92** [comment]
@ipavlu 

What's the `issue` in the context of the repro you attached? 
Which project is having a problem, and what's that problem.

**Comment by nkolev92** [comment]
Thanks for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
