### ISSUE TITLE
Document/configure order of dependency lists in Project.assets.json file

### ISSUE THREAD

**Issue by aodl** [NuGet/Home#7776]
I've been trying to determine how the order of dependencies in the `projectFileDependencyGroups` section of the project.assets.json file is determined. If it were purely alphabetical I would expect 'defaultTenant' in the example below to be listed at the top.
```
...
  "projectFileDependencyGroups": {
    ".NETCoreApp,Version=v2.2": [
      "CoreTenancy.Abstractions >= 1.0.0",
      "M3vc.ModuleEnhancement >= 1.0.0",
      "Microsoft.AspNetCore.App >= 2.2.0",
      "Microsoft.AspNetCore.Razor.Design >= 2.2.0",
      "Microsoft.Extensions.FileProviders.Embedded >= 2.2.0",
      "Microsoft.NETCore.App >= 2.2.0",
      "defaultTenant >= 1.0.0",
      "tenant1 >= 4.0.2",
      "tenant2 >= 1.0.0",
      "zzlast >= 1.0.0"
    ]
  },
...
```
I've tried fiddling with dependencies to affect build order to see if this has an influence, but it appears not.

If the answer is that the order is both arbitrary and unspecified, is there a way that a developer could practically influence this ordering?

This question also refers to the lists of dependencies in the `targets` section...

```
...
  "targets": {
    ".NETCoreApp,Version=v2.2": {
      "Microsoft.AspNet.WebApi.Client/5.2.6": {
        "type": "package",
        "dependencies": {
          "Newtonsoft.Json": "10.0.1",
          "Newtonsoft.Json.Bson": "1.0.1"
        },
...
```

### Why it would be useful for this to be documented (or even configurable)
When it comes to developing plugin style assembly relationships, I have found it useful to be able to parse the `project.assets.json` file to determine the compile/design time dependency graph (given that some dependencies are not listed in an assembly manifests - if the assembly does not reference to any of the dependencies' types). Knowing the compile time dependency relationships and altering plugin behaviour based on that provides a mechanism of establishing plugin priority/override behaviour (based on the 'distance' of transitive dependencies from the entry assembly.

I would like to be able to disambiguate between the priority behaviour of assemblies that sit as the same transitive dependency distance from the entry assembly, and I'm looking for a reliable way to do that.

**Comment by Thapanawat003** [comment]
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1267510763525119",
    enable_page_level_ads: true
  });
</script>

**Comment by nkolev92** [comment]
@aodl

Everything in assets file is sorted by the string identifier of the object, so the casing matters. 
The ordering does not imply priority by any means. 

The assets file is not really an exhaustive list of all the assemblies during compilation. 
It's merely an asset harvested by the build tasks (in the SDK).

I'd suggest reach out to the SDK team at https://github.com/dotnet/sdk/issues/new.

**Comment by aodl** [comment]
That's interesting. Under what circumstances would a dependency of a project not be included in the project.assets.json file?

Thanks for the tip, I'll be sure to reach out to the SDK team

**Comment by nkolev92** [comment]
> Under what circumstances would a dependency of a project not be included in the project.assets.json file?

Didn't mean to imply that. 
All the dependencies specified in the targets section of the assets file will be part of the compilation, but sometimes there'll be conflicts (assemblies are referenced by the SDK and can be refd in lots of other manual ways), then it's on the build tasks and the compiler to make a decision about what's going to be used.
