### ISSUE TITLE
VS hangs when adding a nuget package

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#778]
Repro steps:

1.Create a new Class Library (Protable) project.

2.Add -> New Project->Andorid->Blank App(Android)/Class Library(Android) project to the same solution.

3.Open Manage NuGet Package for Solution UI, search MvvmCross nuget package in Online.

4.Click Install.

Call stack from activititylog.xml:

Object reference not set to an instance of an object. at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value) at NuGet.NetPortableProfileTable.CreateOptionalFrameworksDictionary() at NuGet.NetPortableProfileTable.set_Profiles(NetPortableProfileCollection value) at NuGet.NetPortableProfileTable.get_Profiles() at NuGet.NetPortableProfileTable.GetProfile(String profileName) at NuGet.NetPortableProfile.Parse(String profileValue, Boolean treatOptionalFrameworksAsSupportedFrameworks) at NuGet.VersionUtility.GetShortFrameworkName(FrameworkName frameworkName) at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x) at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at System.String.Join(String separator, IEnumerable`1 values) at NuGet.DataServicePackageRepository.Search(String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) at NuGet.Dialog.Providers.LazyRepository.Search(String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) at NuGet.PackageRepositoryExtensions.Search(IPackageRepository repository, String searchTerm, IEnumerable`1 targetFrameworks, Boolean allowPrereleaseVersions) at NuGet.Dialog.Providers.SimpleTreeNode.GetPackages(String searchTerm, Boolean allowPrereleaseVersions) at NuGet.Dialog.Providers.PackagesTreeNodeBase.ExecuteAsync(Int32 pageNumber, CancellationToken token) at NuGet.Dialog.Providers.PackagesTreeNodeBase.<>c__DisplayClass3.<LoadPage>b__2(Object state) at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute()

**Comment by joelverhagen** [comment]
I have a PR for this:
https://github.com/NuGet/NuGet2/pull/50

**Comment by joelverhagen** [comment]
Fixed with https://github.com/NuGet/NuGet2/pull/50.
