### ISSUE TITLE
Can't update to 4.9.3 with nuget update -self

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#7780]
From everything I can tell, nuget 4.9.3 is officially released. However, when I run `nuget update -self` to update my global nuget install it tells me that 4.9.2 is the latest version. Is this intentional? When will 4.9.3 be available for this type of update?

**Comment by rrelyea** [comment]
we will release it this week.  nuget update self relies on nuget.commandline.#.#.#.nupkg being published.
we generally let the version mature in the market for a week or two before we turn on auto update.

**Comment by rrelyea** [comment]
NuGet.CommandLine.4.9.3.nupkg is now published to nuget.org.
