### ISSUE TITLE
<LICENSE> metadata fields implicitly requires license filename to have an extension

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7783]
@WilliamXieMSFT commented on [Wed Jan 30 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1291)

Using dotnet\sdk\2.2.101-rtm-009628 NuGet pack targets, I am getting
`error NU5030 The license file 'LICENSE' does not exist in the package.`

.nuspec file:
```
<metadata>
  <license>LICENSE</license>
</metadata>
```

This error goes away if I add a '.txt' extension to the LICENSE file and update the field.
.nuspec file:
```
<metadata>
  <license>LICENSE.txt</license>
</metadata>
```

**Comment by karann-msft** [comment]
@williamxiemsft how are you calling pack? using the dotnet CLI or within Visual Studio?

**Comment by willxie-eng** [comment]
@karann-msft I build with a PowerShell script that invokes msbuild against the csproj file (a netstandard 2.0 project) which references a nuspec file.

**Comment by nkolev92** [comment]
@WilliamXieMSFT 

Please take a look at 
https://github.com/NuGet/Samples/blob/master/PackageLicenseFileExample/PackageLicenseFileExample.csproj or 
https://github.com/NuGet/Samples/blob/master/PackageLicenseFileNuspecExample/PackageLicenseFileNuspecExample.nuspec

Note that `<license>license.txt</license>` on its own is not correct. It's missing the type attribute.

**Comment by willxie-eng** [comment]
@nkolev92 Thanks for the examples, my csproj and nuspec project match https://github.com/NuGet/Samples/blob/master/PackageLicenseFileNuspecExample/PackageLicenseFileNuspecExample.nuspec

Using that example project, I was able to get the nuget package generated with the LICENSE file with:
* nuget restore *csproj && msbuild *csproj && nuget pack *.csproj

I can create the NuGet package with the following commands as well but they do not contain the LICENSE file:
* dotnet restore *csproj && msbuild /t:pack *csproj
* dotnet pack *csproj
* dotnet build *csproj /t:pack

**Comment by nkolev92** [comment]
nuget.exe pack should work with that. 

Make sure you have a version that's 4.9.2 or later.

**Comment by willxie-eng** [comment]
Is there a way to do this with the dotnet command or msbuild?

**Comment by nkolev92** [comment]
Yes, https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack?tabs=netcore2x. 

If you are using SDK based projects however, I would discourage against using a nuspec to pack. 
It's very error prone. 

Consider using the targets pack in that case, similar to my first example.

**Comment by willxie-eng** [comment]
@nkolev92 Great, thank you for your help! It turns out adding the asterisk for "LICENSE*" also fixed my build issue.

**Comment by nkolev92** [comment]
Happy to help. 

Do you consider this issue resolved?

**Comment by willxie-eng** [comment]
Yes, please go ahead and resolve the issue.
