### ISSUE TITLE
[Feature] Allow `dotnet add package` command to add a reference without setting the version 

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7785]
_From @alirezajm on February 12, 2019 22:12_

Allow adding package references via the cli without it setting the version in the project file.
This is useful when a **Directory.build.targets** file is present and it is used to manage package versions.

## Feature behavior
Considering there is a Directory.Build.targes file present, containing the following
`<PackageReference Update="Microsoft.Orleans.Core" Version="2.1.2" />` 
running
`dotnet add package Microsoft.Orleans.Core --use-targets-version`
will add
 `<PackageReference Include="Microsoft.Orleans.Core" />` in the .csproj file.
All compatibility checks are intact.

If no reference is present in the .targets file, it should result in an error. Or maybe add an `<PackageReference Include="...` item.

Additional feature:
Enable adding and removing packages to .targets file. This of course is a bit more complex as currently **dotnet add package** command adds/upgrades package references, which will not work quite well with .target files

_Copied from original issue: dotnet/cli#10757_

**Comment by rrelyea** [comment]
@alirezajm - thanks for the request.
we should consider this scenario with regard to our central version management planned feature.

@anangaur is driving the design thinking in that space.

**Comment by mnmr** [comment]
I'd just like to add to this issue that it would be nice if the use of Directory.Build.targets was picked up not just by the command line tools, but also by stuff like the NuGet package manager. Currently, it is way to easy to accidentally add or update a package "the wrong way", and it's cumbersome to first have to find the package in the UI and then have to go to the CLI to actually add it.

**Comment by Thraka** [comment]
I just wanted to rally support for this feature. The .NET Core 2.1 SDKs that have testing projects at times need to add reference to the ASP.NET APP package, but the package needs to be versionless so that the SDK picks up the correct references. This requires calling `dotnet package add` and then hand editing the project file to remove the version reference. I would like to be able to tell users a command that lets them add the reference without a version.

**Comment by zkat** [comment]
Closing in favor of Central Package Version Management (https://github.com/NuGet/Home/issues/6764)
