### ISSUE TITLE
PMC Confirmation prompt has problems with localized builds - likely 15.x and greater

### ISSUE THREAD

**Issue by kant2002** [NuGet/Home#7789]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Package Manager Console

NuGet version (x.x.x.xxx): 5.0.0.5782

dotnet.exe --version (if appropriate):

VS version (if appropriate): VS2019 Preview 2.2

OS version (i.e. win10 v1607 (14393.321)):

## Detailed repro steps so we can see the same problem

1. Run Update-Package -Reinstall on the existing project
2. Message appear that bootstrap file want override file
В проекте «Library.Web» уже существует файл «Scripts\bootstrap.js». Вы хотите перезаписать его?
[Д] Да  [В] Да для всех  [Н] Нет  [В] Нет для всех  [?] Справка (по умолчанию «Н»):

There now way to distinguish between Yest for All and No for All. Both displays В
...

**Comment by rrelyea** [comment]
@kant2002 - can you confirm that VS 2017 15.9 works correctly? (is this a regression in 16.0?)

**Comment by kant2002** [comment]
I could not confirm, since I have VS 15.9 in English, I miss language selection when install Preview (which take my default language of OS which is Russian). Is installing language pack for VS 15.9 would allow me to see Nuget in Russian inside VS?

**Comment by kant2002** [comment]
@rrelyea after installing Russian language pack to VS 15.9 I observe same behavior.

**Comment by zkat** [comment]
hey @dominoFire could you please follow up on this?

**Comment by dominoFire** [comment]
Fixed in NuGet/NuGet.Build.Localization#866

**Comment by dominoFire** [comment]
@kant2002 Thanks for your report. This should marked as fixed in the next major VS release. Thanks!
