### ISSUE TITLE
Hard to use forked copies - strong naming

### ISSUE THREAD

**Issue by clairernovotny** [NuGet/Home#7790]
The current build.ps1 and build scripts will generate files that do not generate binaries with strong names. This makes it harder to use in forks where the strong name is needed. 

The build infrastructure is also fairly complicated. 

It would be helpful if the build.ps1 script had a parameter to enable public signing for all files that would apply the correct snk using the PublicSign option.

**Comment by nkolev92** [comment]
Fixed https://github.com/NuGet/NuGet.Client/pull/2863. 

The snk was added for ngen purposes.
