### ISSUE TITLE
Type showed the project language instead of the project type when executing command “Get-Project” in PMC

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7797]
## Details about Problem
NuGet version: NuGet Client Dev\5.0.0.5831
Build Tools VS Version: D16.0\28613.55
OS: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps 
1. Create a project [e.g. ASP.NET Web Application (.NET Framework)/C++ UWP/Console App (.NET Framework)] in VS.
2. Open PMC and execute command “Get-Project” in PMC.
## Expected
The project type showed correctly as below screenshot (e.g. ASP.NET Empty Web Site).
![correcttype](https://user-images.githubusercontent.com/20632625/52775318-57e0bb80-307a-11e9-8e99-bcc8f8025a41.png)

## Actual
The project type showed “unknown” as below screenshot.
![wrongtype](https://user-images.githubusercontent.com/20632625/52775322-5ca56f80-307a-11e9-9203-36b6ea8279bf.png)

## Note
1. It doesn't repro for .NET Core projects/ASP.NET Web Site projects.
2. It repro on D16.0\28613.55 (default NuGet Client 5.0.0.5821).
3. It repro on D15.8\27924.00 (default NuGet Client 4.8.0.5348).

**Comment by rrelyea** [comment]
Related to #7798
May be by design?

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
This is working as designed, the project type when it's created determines what is displayed in the console. Web application is a different project type than Web site.
