### ISSUE TITLE
NU5104 not reported on package with PrivateAssets set

### ISSUE THREAD

**Issue by KexyBiscuit** [NuGet/Home#7803]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

VS version (if appropriate): 16.0.0 Preview 3.0

OS version (i.e. win10 v1607 (14393.321)): Windows Version 1903 (OS Build 18334.1)

## Detailed repro steps so we can see the same problem

```xml
<Version>0.1.0</Version>
```

```xml
<PackageReference Include="Microsoft.CSharp" Version="4.6.0-preview4.19114.7">
    <PrivateAssets>none</PrivateAssets>
</PackageReference>
```

**Comment by nkolev92** [comment]
You are building a prerelease package though, why should NU5104 be reported then? 

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104

NU5104 is about stable package releases being built with prerelease dependencies which is not the case for you.

**Comment by KexyBiscuit** [comment]
@nkolev92 Sorry, I pasted the wrong csproj. This issue remains when my Version is set to stable.

**Comment by nkolev92** [comment]
@KexyBiscuit 

I can't repro your issue. I see the warning being generated correctly on my end.
Make sure restore has run before packing. 

Also make sure that the package is not already on disk.
When pack no-op (basically nothing has change since last time you packed), no warning will be reported.

**Comment by KexyBiscuit** [comment]
You're correct. After several retries now I find the problem is on my side, thanks for answering this.
