### ISSUE TITLE
No events from IVsPackageInstallerEvents and IVsPackageInstallerProjectEvents for SDK projects

### ISSUE THREAD

**Issue by sergeyQx** [NuGet/Home#7804]
here's the Visual Studio extension that obtains the IVsPackageInstallerEvents and listens to it https://drive.google.com/open?id=1oKqUYEUg_gCcBhkbDcjVIp7gUU_2vspa
It receives events for old-fashioned projects but does not for SDK-based projects.

**Comment by debonte** [comment]
Dupe of issue #6872?

**Comment by nkolev92** [comment]
Yeah, duplicate of https://github.com/NuGet/Home/issues/6872. 

Thanks @debonte
