### ISSUE TITLE
packages  path is wrong?!

### ISSUE THREAD

**Issue by athinboy** [NuGet/Home#7809]
Why does  the path is :   C:\work\code\k3applet\K3Applet\ \packages ?

1>------ 已启动生成: 项目: Test, 配置: Debug Any CPU ------
1>  正在还原 NuGet 程序包...
1>  若要防止 NuGet 在生成期间下载程序包，请打开“Visual Studio 选项”对话框，单击“程序包管理器”节点并取消选中“Allow NuGet to download missing packages”。
1>  Feeds used:
1>    C:\Users\***\.nuget\packages\
1>    https://api.nuget.org/v3/index.json
1>    https://nuget.org/api/v2/
1>    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
1>  
1>  Restoring NuGet package Microsoft.Web.Xdt.2.1.1.
1>  Restoring NuGet package NuGet.Core.2.14.0.
1>  Adding package 'Microsoft.Web.Xdt.2.1.1' to folder 'C:\work\code\k3applet\K3Applet\ \packages'
1>  Adding package 'NuGet.Core.2.14.0' to folder 'C:\work\code\k3applet\K3Applet\ \packages'
1>  警告: 未能找到路径“C:\work\code\k3applet\K3Applet\ \packages\NuGet.Core.2.14.0”的一部分。
1>  警告: 未能找到路径“C:\work\code\k3applet\K3Applet\ \packages\Microsoft.Web.Xdt.2.1.1”的一部分。
1>C:\work\code\k3applet\K3Applet\.nuget\NuGet.targets(100,9): error : 未能找到路径“C:\work\code\k3applet\K3Applet\ \packages\NuGet.Core.2.14.0”的一部分。
1>C:\work\code\k3applet\K3Applet\.nuget\NuGet.targets(100,9): error : 未能找到路径“C:\work\code\k3applet\K3Applet\ \packages\Microsoft.Web.Xdt.2.1.1”的一部分。
1>C:\work\code\k3applet\K3Applet\.nuget\NuGet.targets(100,9): error MSB3073: 命令“"C:\work\code\k3applet\K3Applet\.nuget\NuGet.exe" install "C:\work\code\k3applet\K3Applet\Test\packages.config" -source ""  -NonInteractive -RequireConsent -solutionDir "C:\work\code\k3applet\K3Applet\ "”已退出，代码为 1。
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

 
## Details about Problem 
NuGet version:4.9.3.5777
dotnet.exe --version :3.0.100-preview-009750
VS version : VS2012 update5
OS version: win10 1809
  

[K3Applet2.zip](https://github.com/NuGet/Home/files/2872488/K3Applet2.zip)

**Comment by rrelyea** [comment]
@zivkan - this sounds like a dupe of the extra space issue. Can you please dupe, if so?

**Comment by zivkan** [comment]
Yes, this is a duplicate of #7657
