### ISSUE TITLE
Suppress "Assembly not inside 'lib' folder" warnings

### ISSUE THREAD

**Issue by Exocomp** [NuGet/Home#7813]
I have a case where I created a .NET wrapper around native dlls, I include the native dlls as part of contentFiles and get the warning:

`WARNING: NU5100: The assembly 'dll here' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.`

Everything else works as expected, how do I suppress this warning ?

NuGet Version: 4.9.3.5777

To reproduce just add any dll in the contentFiles section and issue the pack command.

Command to reproduce:  nuget pack Test.nuspec

**Comment by rrelyea** [comment]
We rely on normal error and warning functionality in msbuild.
Our doc page for warnings and errors lists a link to "How to compress Compiler warnings" in visual studio

Adding a property like this to your project file:
`<NoWarn>NU5100</NoWarn>`

is one way to do this.

Then, when you run dotnet pack the next time, it suppresses that warning.
