### ISSUE TITLE
configure.ps1 fails when running outside of Developer Command Prompt with dev16

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#7818]
Error text after running `git clean -xffd` then `.\configure.ps1` in a plain PowerShell window:

<pre>
[14:22:05 +0]   [BEGIN] Validating VS 15 toolset installation
WARNING: [14:22:05 +0] VSSDK is not found at default location 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v15.0'. Attempting to
override.
Join-Path : Cannot find path <b>'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v15.0'</b> because it does not exist.
At D:\src\git\github.com\NuGet\NuGet.Client\configure.ps1:143 char:28
+ ... ToolsPath = Join-Path $vstoolset.VisualStudioInstallDir "..\..\MSBuil ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...ualStudio\v15.0:String) [Join-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand

Error-Log : [14:22:05 +0]       [FAILED +00:00:00] Validating VS 15 toolset installation
At D:\src\git\github.com\NuGet\NuGet.Client\build\common.ps1:142 char:17
+ ...             Error-Log "[FAILED +$(Format-ElapsedTime $sw.Elapsed)] $B ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Error-Log

[14:22:05 +0]   Using MSBUILD version 16.0.440.35270 found at 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin\msbuild.exe'
[14:22:05 +0]   Configuration data has been written to 'D:\src\git\github.com\NuGet\NuGet.Client\artifacts\configure.json'
D:\src\git\github.com\NuGet\NuGet.Client\configure.ps1 : Build's completed with 2 error(s):
>>> Cannot find path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v15.0' because it does not exist.
>>> [14:22:05 +0]       [FAILED +00:00:00] Validating VS 15 toolset installation
At line:1 char:1
+ .\configure.ps1
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,configure.ps1
</pre>

Notice there is a "v15.0" path under "2019". This is inconsistent and likely the problem. On my machine a "v16.0" folder is present.

A workaround is running the command from a Dev16 Developer Command Prompt.

/cc @nkolev92 @zivkan

**Comment by nkolev92** [comment]
The root cause might be that we are using VSWhere to detect the latest VS version when not running in a developer command prompt. Then we later on we are not considering the detected VS version when detecting the SDKs.

**Comment by nkolev92** [comment]
I don't see this as super important anymore. We're moving away from any `VisualStudioVersion` imports, so hopefully this is fied
