### ISSUE TITLE
Raise a deprecation warning for Gen1 credential plugin

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7819]
We shipped Gen2 of Authentication Credential Provider: #6642 shipped in 4.8/2.1.400 SDK/15.8 of Msbuild.

We should deprecate the Gen1 plugin in 5.0 and completely remove it in a future release.
This task is to provide a warning message if you are using the Gen1 provider in 5.0.

Future task to remove Gen1 support is: https://github.com/NuGet/Home/issues/7586.

**Comment by nkolev92** [comment]
@anangaur @karann-msft 

I am linking to https://docs.microsoft.com/en-us/nuget/reference/extensibility/nuget-cross-platform-authentication-plugin in the warning message. 

Can I get a redirect link to account for the docs potentially changing.

**Comment by karann-msft** [comment]
https://aka.ms/nuget-cross-platform-authentication-plugin
