### ISSUE TITLE
NuGet org should have 'pinned' repos

### ISSUE THREAD

**Issue by Eilon** [NuGet/Home#7821]
Right now there are no pinned repos on https://github.com/NuGet so it looks like this:

> ![image](https://user-images.githubusercontent.com/202643/53204217-e952af00-35df-11e9-8289-a0d395f1ccc2.png)

Having pinned repos can make it easier for people to find the most relevant repos (e.g. Home, Gallery, etc.). Here's what the https://github.com/aspnet/ org has:

> ![image](https://user-images.githubusercontent.com/202643/53204168-ce803a80-35df-11e9-99ac-0dfef73aedd2.png)

**Comment by rrelyea** [comment]
Thx. Just set a few up.

**Comment by Eilon** [comment]
Thanks @rrelyea , this is much nicer! BTW you can sort/re-order the pinned repos if you want by drag/dropping them (e.g. if you want Home to be first).

![image](https://user-images.githubusercontent.com/202643/53295641-92520300-37b4-11e9-84f5-ffa88b6edfdd.png)

**Comment by rrelyea** [comment]
Just did some more polish, including reordering:
![image](https://user-images.githubusercontent.com/8865080/53453087-159f6e80-39d8-11e9-87cb-130e0af91dad.png)
