### ISSUE TITLE
NuGet.exe update command does not work for packages.config without a project file.

### ISSUE THREAD

**Issue by hubuk** [NuGet/Home#783]
nuget.exe 2.8.6 (2.8.60409.62)
Update command does not work for packages.config file which is contained in a directory where there is no supported project file. This is an usecase when user wants to update tools needed to build a project.

Simple directory structure can be used to reproduce the problem (packages.config may be empty):
```
<project>
 ├ packages
 |  | (...)
 | nuget.exe
 | packages.config
```
just run:
NuGet.exe update packages.config
Error reported:
Unable to locate project file for '\<project\>\packages.config'.

Similar problem has been reported in the following locations:
https://github.com/NuGet/NuGet.CommandLine/issues/5
https://nuget.codeplex.com/workitem/3118
https://nuget.codeplex.com/workitem/4476
https://nuget.codeplex.com/workitem/3848

For nuget3 update functionality in NuGet.CommandLine is not currently available. Are there plans to support update functionality in nuget3?

**Comment by yishaigalatzer** [comment]
There is no plan to support this feature in the coming release of NuGet (3.0). You can however make this work today with nuget restore (3.0) and project.json (or dnu)

**Comment by yishaigalatzer** [comment]
@sharwell @hubuk as update in nuget.exe is not something we are going to recommend long term as the way to go, and the given solution with `project.json` and `restore`, I would like to get your feedback on the perceived importance of a fix here?

As far as I am understanding things, this is not something that we would need to fix with any urgency if at all, at the same time I'm open to taking a pull request for this once we move the full nuget command line into github.

**Comment by hubuk** [comment]
The fix is not urgent I think. In a matter of fact the longer I think about it the less I like the idea of using nuget to get a latest version of a build process tool.

There are some drawback of such approach I can think of:
1. We are introducing a new variable into the build process. Any failure (at build time or at run time) might be caused by a new version of downloaded tool. We are losing control over when and what version will be used in a build.
2. There is no "download latest" kind of functionality for NuGet.exe. You can only download a specific version of a package and then update it along with references in packages.config to a latest one (as long as nuget version 2.X is considered). This complicates build and makes it take longer.
3. We need to parse a name of the directory to which the updated package has been downloaded (if any) or check a version attribute's value in a packages.config file to determine which location is holding a latest version of the tool to be used.

Did you ever see such usage of nuget? Is this an usacase for which nuget is suitable tool? I would appreciate your help.

**Comment by yishaigalatzer** [comment]
With nuget 3 you do not need to update packages.config. But the other issues still exist.

It's a choice you need to make, for nuget we chose to make it and that is how we are building NuGet itself. Like you are suggesting the build is indeed more fragile, but it also catches build tools issues earlier.

In other builds I worked with (mvc5/web api2) we downloaded nuget itself from an http endpoint, again it is more fragile but it catches more issues.

Another thing to consider is that if you store your source files in git, you do want binaries to not be checked in.

**Comment by sharwell** [comment]
I believe there was some confusion regarding the desired behavior. It is my understanding that the only command we need for **packages.config** in a directory without a project file is `nuget restore`, and I believe that command does work properly.

**Comment by hubuk** [comment]
Ok maybe I went a little off-topic.

The desired behavior is that:
```
nuget.exe update packages.config
```
should update packages specified in the config file.

As I understand there is no sense in fixing this in a version which will be replaced by nuget3 in a couple of months. Is that correct?

**Comment by sharwell** [comment]
@yishaigalatzer Keep in mind that while we are no longer waiting for a fix to this issue, the underlying request is still valid as originally stated. This means you should include the resolution (which appears to be one of the **ClosedAs:** labels) along with closing the issue.

**Comment by yishaigalatzer** [comment]
Thanks for the reminder, we can look at it again if there is strong demand. I'm also ok with a pull request, shouldn't be too hard.

**Comment by hubuk** [comment]
@yishaigalatzer Thank you for your help. I will take a look into this issue as soon as be able to build source code (#787).

**Comment by bladeoflight16** [comment]
This can be worked around by creating a dummy project (`.csproj`) file in the same directory as the `packages.config` file, at least in some cases. Mine looked like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
</Project>
```

Just an empty `Project` element. NuGet didn't even modify it after performing the update. (Unsurprising, since the packages in question are command line tools rather than libraries to depend on, meaning they would never modify the project file.)
