### ISSUE TITLE
The "GenerateLockedPackageReferencesFile" task was not given a value for the required parameter ProjectAssetsFile

### ISSUE THREAD

**Issue by lidong6** [NuGet/Home#7833]
I am following this page to have central Packages.props to control versions: https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-packages-and-versions

but got this error: 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "GenerateLockedPackageReferencesFile" task was not given a value for the required parameter "ProjectAssetsFile".	RndsInDataLakeCode	C:\Users\lidonz\.nuget\packages\nuget.deterministic\2.0.8\build\NuGet.Deterministic.targets	38	

Nuget version: 4.9.3
VS2017: 15.9.7

I assume the ProjectAssetsFile is something like "project.assets.json", I don't see this file in my solution.

please help, thanks.

**Comment by nkolev92** [comment]
@lidong6 

That was just an initial spec. It's not implemented. 

The issue to track it's implementation is https://github.com/NuGet/Home/issues/6764.
