### ISSUE TITLE
Looking for an alternative to supplying "plain text password data" in the commandline argument -Password for nuget.exe (SSO?)

### ISSUE THREAD

**Issue by blair-ensinger** [NuGet/Home#7838]
Our company Security Policy forbids use of clear text credentials in stored procedures/batch jobs/etc. and several of our developers use scheduled tasks to operate nuget.exe for the "source" command line directive. Is there anyway to authenticate to "artifactory" without supplying the clear text password? Thanks

**Comment by blair-ensinger** [comment]
Sorry for the goof up.  Company Security Policy forbids use of clear text credentials and several developers use scheduled tasks to operate nuget.exe for the "source" command line directive.  Is there anyway to authenticate to "artifactory" without supplying the clear text password?  Thanks

**Comment by rrelyea** [comment]
Can you ask artifactory?
There are options that NuGet provides (credential providers to work in conjunction with nuget.exe and the server auth) -- but I'm unsure what artifactory has taken advantage of.

**Comment by rrelyea** [comment]
@blair-ensinger  - please see my earlier response.

**Comment by blair-ensinger** [comment]
Rob ... thanks ...
I contacted Artifactory and I am pursuing an action plan based on their response.

Blair Ensinger
