### ISSUE TITLE
GeneratePathProperty=true fails to generate property on case mismatch

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#7843]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): 5.0.0.1

dotnet.exe --version (if appropriate): 3.0.100-preview-010142

VS version (if appropriate): n/a

OS version (i.e. win10 v1607 (14393.321)): win10 v1809 (17763.195)

Worked before? If so, with which NuGet version: no

## Detailed repro steps so we can see the same problem

1. Use attached project. 

2. dotnet build, observe `PkgSystemMemory = C:\Users\user\.nuget\packages\system.memory\4.5.2`

3. dotnet build /p:Repro=true, observe `PkgSystemMemory =`

I believe the bug is here: https://github.com/NuGet/NuGet.Client/pull/2271/files#r261694951

[nugetCase.zip](https://github.com/NuGet/Home/files/2920486/nugetCase.zip)

**Comment by rrelyea** [comment]
Happy to talk, if you think there are issues with this approach. Let's target 5.1, if your question was just about milestone.

**Comment by nkolev92** [comment]
@jeffkl Already has a PR out for this and it looks good. 
I'll merge once the tests pass.

**Comment by anangaur** [comment]
@nkolev92, Is this feature documented somewhere? I couldn't find an issue that summarizes what we did finally?

**Comment by nkolev92** [comment]
@anangaur It wasn't publicly advertised on purpose iirc. 

Basically `no`, there's no documentation, it's just the issue. It should probably have been summarized in a desgin doc at the least however.

**Comment by anangaur** [comment]
Can you just create an issue on docs repo? Seems like an interesting and useful property.

**Comment by nkolev92** [comment]
@anangaur 
https://github.com/NuGet/docs.microsoft.com-nuget/issues/1355
