### ISSUE TITLE
Specify NuGet version for GeneratePackageOnBuild

### ISSUE THREAD

**Issue by amybingzhao** [NuGet/Home#7844]
Enhancement request: For projects using the new csproj format w/ PackageReferences that have GeneratePackageOnBuild=true, add the ability to specify which version of the NuGet.exe should be used

**Comment by rrelyea** [comment]
This functionality relies on the msbuild targets/tasks for pack that ship with VS, and are versioned with the nuget components within VS.
nuget.exe doesn't ship with VS.
If you need to use old versions of nuget.exe, you should not use this feature.
