### ISSUE TITLE
Plugins cache not discoverable intermittently on linux platforms

### ISSUE THREAD

**Issue by shubham90** [NuGet/Home#7845]
Remove the content above here and fill out details below.

## Details about Problem
Dotnet restore is failing intermittently with the following error:

Error from cmd is: "/usr/share/dotnet/sdk/2.1.504/NuGet.targets(114,5): error : Could not find a part of the path '/root/.local/share/NuGet/plugins-cache/7a7ff1b21f69ab23c9f21123251bb7e17eb0433c$CredentialProvider.Microsoft.dll/https:_api.nuget.org_v3_index.json.dat-new'. [/app/app.csproj]"

The NUGET_PLUGIN_PATHS  is set to a custom location of the artifacts credential provider. Also, nuget.config only contains public nuget registry, so, there is no need to call the credential provider to handle auth.
In the repro, we are creating a docker image with dotnet 2.1.504 on stretch slim with artifacts cred provider installed. The container is then running dotnet restore with public repos only(nuget.org). This happens only in Linux platforms like bionic, stretch etc. Here is a link to a failing build with the error: **https://ci.dot.net/job/dotnet_dotnet-docker/job/nightly/job/Linux_2.1-2.2_prtest/269/console**

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet restore

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate): 2.1.504

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): stretch-slim amd64

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Create a docker image using this [dockerfile](https://github.com/dotnet/dotnet-docker/blob/7e1e29ba6b5cebdb9be2549798985efd4ba0fabe/2.1/sdk/stretch/amd64/Dockerfile)

2. Run it and try to create similar [test](https://github.com/dotnet/dotnet-docker/blob/master/tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux) with nuget.config file that has just nuget v3 public registry as source.

3. It fails intermittently with the error stated above.
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

logs attached here: https://ci.dot.net/job/dotnet_dotnet-docker/job/nightly/job/Linux_2.1-2.2_prtest/269/console
### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by shubham90** [comment]
@nkolev92 @alexmullans This is a blocking bug for cred provider to go in dotnet docker images. This issue is intermittent but it reduces the reliability of the docker images.

**Comment by infin8x** [comment]
@anangaur thoughts on this?

**Comment by rrelyea** [comment]
@nkolev92 - Not sure if this was already addressed by your long filepath fix for this?
Can you please investigate?

**Comment by nkolev92** [comment]
@shubham90 
On the repro that you have can you please provide the dg file for the project on which you are running restore. 

Do you can do by running 
`dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath="someConvenientPathForYou"`

Also it'd be helpful if you can run restore with high verbosity.

`dotnet restore /v:d`

**Comment by nkolev92** [comment]
Actually looking at it again, the plugins cache is created because nuget is probably asking the plugin if it can support Download.

**Comment by shubham90** [comment]
@nkolev92 The repro is a test running in dotnet-docker repo. It's a very basic test which creates a project using "dotnet new console --framework netcoreapp2.2" and adds a nuget.config file similar to this:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
It then adds a RuntimeFrameworkVersion to csproj file and sets it to 1.1.*

After that it runs "dotnet restore -r linux-x64" and fails. I could not get this repro on my box. I can try to add the verbosity to my PR and see if this fails again.

**Comment by nkolev92** [comment]
On NuGet side we appear to the doing the correct thing when creating a shared directory. 

This is where the file is being created https://github.com/NuGet/NuGet.Client/blob/b0df1ba400b116f711cd8588f9f0a163a81f33d7/src/NuGet.Core/NuGet.Common/ConcurrencyUtilities.cs#L222. 


@shubham90 
I would imagine there Dockerfile you linked already has an image that's created, so maybe there's an exact image that I can use instead of having to piece the pieces from https://github.com/dotnet/dotnet-docker/blob/master/tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux ? 

I'm creating an ubuntu1604 VM to try to repro the problem.

**Comment by nkolev92** [comment]
Worked with @shubham90 offline to try to recreate the issue environment. 

I am trying with ubuntu 16.04 & 18.04, no luck yet. 

I will look through the NuGet code again, but I'm not sure how much I'll be able to do without a more consistent repro.

**Comment by nkolev92** [comment]
The permissions there are `-rw-r--r-- ` and this is a local directory, so not really what could be going on here.

**Comment by nkolev92** [comment]
I have a PR out to improve the logging to help us with the investigation of future plugin startup issues. 

https://github.com/NuGet/NuGet.Client/pull/2751

**Comment by shubham90** [comment]
@nkolev92 I think this is a good change to capture the cause. Could you please add this to 4.9.* patch as well so that we can test it with next dotnet sdk release?

**Comment by nkolev92** [comment]
@shubham90 
Can you try increasing the verbosity of the command to `/v:d`. 

That will contain information about the stack trace.

**Comment by shubham90** [comment]
I have added this to the dotnet docker tests where we found the issue earlier. I will update if we hit this again with verbose logging

**Comment by shubham90** [comment]
@nkolev92 I have got the logs from the dotnet docker team where they saw the same failure again. Relevant part of the logs being at the end of the log file
[Standard_Console_Output (1).log](https://github.com/NuGet/Home/files/3011040/Standard_Console_Output.1.log)

**Comment by nkolev92** [comment]
The fix in https://github.com/NuGet/NuGet.Client/commit/ea1a5fb2afe5149389bea7befb7c8a076f457274 might address this issue. 

I'll update when it's made it in the CLI.

**Comment by nkolev92** [comment]
3.0.0 preview 4, 2.1.700 and 2.2.300 P2 should hopefully be better now.

**Comment by nkolev92** [comment]
Moving to 5.2, and leaving this issue open for tracking.

**Comment by shubham90** [comment]
Thanks for fixing this. I will wait for dotnet docker to update their version of dotnet to 2.1.700 to verify if this is fixed. I am still not able to repro this locally.

**Comment by nkolev92** [comment]
Hey, @shubham90 I'm closing this as fixed for now. 

Happy to reopen if you still see issues though.
