### ISSUE TITLE
Some unit tests are broken after NuGet.Client PR #2569

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#7846]
PR: https://github.com/NuGet/NuGet.Client/pull/2569/files

Failures:

  - [x] PackageMetadataResource_Basic
    ```
    System.InvalidCastException : Unable to cast object of type 'ClonedPackageSearchMetadata' to type 'NuGet.Protocol.PackageSearchMetadataV2Feed'.
    ```
  - [x] PackageMetadataResource_UsesReferenceCache
    ```
    System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.List`1[NuGet.Protocol.Core.Types.IPackageSearchMetadata]' to type 'System.Collections.Generic.IEnumerable`1[NuGet.Protocol.PackageSearchMetadataV2Feed]'.
    ```

This is affecting units tests on Linux, Mac, and Windows.

**Comment by nkolev92** [comment]
//cc @zivkan @heng-liu @dominoFire 
One of needs to investigate this to ensure that there are no product issues.

**Comment by nkolev92** [comment]
I have a PR out at https://github.com/NuGet/NuGet.Client/pull/2748
