### ISSUE TITLE
[Proposal] Side-by-side packages.config and Package Reference

### ISSUE THREAD

**Issue by rlreis90** [NuGet/Home#7852]
### Description
Since Package Reference still doesn’t support install/uninstall scripts, drop-in content or configuration (which packages.config does), I suggest the creation of a **Hybrid Mode** where **both** types of packages could be included.

### Proposal
Offer a hybrid mode allowing users to individually select for each NuGet package which package reference system to use. Additionally auto-detect when a project CAN be Package Referenced without conflicts and do so by default. This would allow "partial migration" from packages.config, retaining the original system as-is for NuGet packages incompatible with Package References.

### Motivation
The lack of features in Package References, the bread and butter of many NuGet packages which rely heavily on app.config or native assemblies, makes it not viable as a replacement at the moment. However, with this proposal we could mitigate the issue and pave the way for it's wider (incremental) adoption.

**Comment by htapal** [comment]
Any update on this proposal?

**Comment by zkat** [comment]
@anangaur @chgill-MSFT this needs an official product decision.

**Comment by nkolev92** [comment]
Team Triage: We don't believe the effort and the technical complexity of this feature is worth the benefit.
