### ISSUE TITLE
Download NuGet package for every build in Jenkins

### ISSUE THREAD

**Issue by aaronyeddula** [NuGet/Home#7858]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):4.3.2

dotnet.exe --version (if appropriate):

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)):win 10

Worked before? If so, with which NuGet version:

1. Trying to download fresh NuGet packages every time i build the job in the Jenkins I tried all the commands but i am not getting the output. Can you let me know if there is a command to download fresh packages via NuGet  

Commands Used
C :\Path to nuget.exe restore .sln : Only downloads new packages that are needed
https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference
Used all the commands from above link only restore command is working.

Note: Please respond to my email aaronyeddula@gmail.com as soon as possible because this is priority issue.

**Comment by zivkan** [comment]
If I understand correctly, you don't want your CI builds to use the global packages folder, so all packages are downloaded from your nuget feeds on every build. If this isn't correct, please clarify your question.

A quick way to do this is to run `dotnet nuget locals global-packages --clear` or `nuget.exe locals global-packages -clear`. However, if you're running on a shared build server, this will have a negative impact on other users using the same build agent, as their restores will take longer. A better way would be to have your CI script create a [nuget.config](https://docs.microsoft.com/en-au/nuget/reference/nuget-config-file) file that sets the global packages folder to a local that gets cleaned every build.

However, NuGet expects packages to be immutable, so normally there should not be a need to clear packages once downloaded. If you're testing packages that the build packs, it's recommended to use pre-release packages with an incrementing version number for each build (for example, you can see [our myget feed](https://dotnet.myget.org/feed/nuget-build/package/nuget/NuGet.Packaging)), and once the package is ready to be released, build the tested & verified code without the pre-release label.

**Comment by nkolev92** [comment]
Closing this as we do not have enough info to continue investigating.
