### ISSUE TITLE
Transiet package download timeouts when building dotnet/cli on macOS.

### ISSUE THREAD

**Issue by peterhuene** [NuGet/Home#7860]
## Details about Problem

When building the latest out of `dotnet/cli` @ master on macOS, I receive a huge number of package download timeouts.  This occurred after a recent stage0 update for our repo.

There's a lot of console spew of the form:

```
 The HTTP request to 'GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.netcore.jit/index.json' has timed out after 100000ms.
```

This slows down the build considerably.  If I repeatedly run `./build.sh`, it seems to eventually get past the issue as the packages get downloaded.

The `dotnet` version from our stage0:

```
$ ./dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010615
 Commit:    81fa2d2f6d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/peterhuene/src/cli/.dotnet/sdk/3.0.100-preview4-010615/

Host (useful for support):
  Version: 3.0.0-preview4-27505-3
  Commit:  772074134e

.NET Core SDKs installed:
  3.0.100-preview4-010615 [/Users/peterhuene/src/cli/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview4-19155-01 [/Users/peterhuene/src/cli/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.2 [/Users/peterhuene/src/cli/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/Users/peterhuene/src/cli/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/Users/peterhuene/src/cli/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27505-3 [/Users/peterhuene/src/cli/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

OS version:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.3
BuildVersion:	18D109
```

## Detailed repro steps so we can see the same problem

1. `git clone git@github.com:dotnet/cli.git`

2. `cd cli`

3. `git checkout 871579a37b68897896ab618c861621466c5ec0e4` # current HEAD as of this issue

4. `./build.sh`

**Comment by peterhuene** [comment]
Two other CLI team members are seeing the timeout messages on macOS as well from Microsoft's corporate network.

**Comment by peterhuene** [comment]
Myself and @livarcocc also saw an immediate failure from `RestoreTask` with `invalid argument`, which on subsequent build runs we didn't experience.  If I see it again I'll include that information here.

**Comment by peterhuene** [comment]
Note: we don't exhibit any of this behavior from the `release/3.0.1xx` branch, which is (currently) our preview 3 branch with a stage0 dotnet of `3.0.100-preview3-010272`.

**Comment by amosonn** [comment]
I get the same errors, using the `mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview5` docker container on ArchLinux.
Running `dotnet --info` inside the container gives:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by peterhuene** [comment]
Closing this as it's been a few years now and it's likely this is no longer relevant.
