### ISSUE TITLE
dotnet pack does not support RepositoryCommit

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#7866]
_From @JanEggers on March 11, 2019 16:0_

## Expected  behavior

dotnet pack --RepositoryCommit 123 

nuget seems to support it

https://github.com/NuGet/docs.microsoft.com-nuget/pull/708

_Copied from original issue: dotnet/cli#10965_

**Comment by nkolev92** [comment]
At this point, we haven't received enoguh information to add a special switch for RepositoryCommit. 

Not that `dotnet` commands support MSBuild properties, so specifying `dotnet pack -p:RepositoryCommit:value should work.
