### ISSUE TITLE
globalpackagesfolder in nuget.config is ignored in alpine linux

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#7870]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet

NuGet version (x.x.x.xxx):
NuGet Command Line
4.9.0.6

dotnet.exe --version (if appropriate):
 2.1.503

OS version (i.e. win10 v1607 (14393.321)):
 OS Name:     alpine
 OS Version:  3.7
 OS Platform: Linux
 RID:         alpine.3.7-x64

Worked before? no

1. create a Nuget.Config in a root directory with a relative globalpackagesfolder defined
2.1 run dotnet pack to trigger a build of a project or
2.2 run dotnet nuget locals all --list -> the default globalpackagesfolder is shown 
3. the specified globalpackagesfolder is not used
4. works under windows but not under alpine linux

**Comment by nkolev92** [comment]
@v-luzh Can you please try to test this and confirm if it's still reproable.

**Comment by v-luzh** [comment]
@nkolev92 It doesn’t repro on OS: Linux Ubuntu 18.04 with .Net Core 3.1. “globalPackagesFolder” works well for both command “dotnet pack” and “dotnet nuget locals all --list” during the verification.

**Comment by nkolev92** [comment]
Thanks @v-luzh 

@TFTomSun 
At this point it's a bit difficult to test alpine linux specifically.

Are you still able to repro this? Reproable on any other linux versions?

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
