### ISSUE TITLE
Investigate noise in Functional / Windows tests

### ISSUE THREAD

**Issue by DoRonMotter** [NuGet/Home#7873]
Currently there are tests which only pass occasionally, understand the set of flaky tests and address.

**Comment by dtivel** [comment]
https://github.com/NuGet/Home/issues/7877
https://github.com/NuGet/Home/issues/7879
https://github.com/NuGet/Home/issues/7885
https://github.com/NuGet/Home/issues/7886
https://github.com/NuGet/Home/issues/7925
