### ISSUE TITLE
NuGet LicenseURL to License transition

### ISSUE THREAD

**Issue by agshah** [NuGet/Home#7876]
Hi all,
I updated our nuspec file to use license.txt as below:

Basically I removed <licenseUrl> element
and added below one line instead:
    <license type="file">license.txt</license>

I used nuget.exe to pack our NuGet package.

When using VS2017 update 15.9.5, i can see the license.txt when installing the package.
But I have another VS2017 with update 15.7.6 and instead of license.txt I see url https://aka.ms/deprecateLicenseUrl .

Can someone advise what I may be doing wrong in the change I have made in nuspec file that may be causing license.txt to not show up and instead url being displayed?

**Comment by jaime-olivares** [comment]
Apparently your xml tags are not being shown in your question. Use tick fences, like:

    ````xml
    <xmltag>something</xmltag>
    ````

that will output:
````xml
<xmltag>something</xmltag>
````

**Comment by agshah** [comment]
thanks for the suggestion. Let me try what you say:

Basically I removed element:
````xml
<licenseUrl>
````

and added below line instead:
````xml
<license type="file">license.txt</license>
````

**Comment by dominoFire** [comment]
Hi @agshah , there's nothing wrong with the license file.

In the release of NuGet 4.9, we announced the support for [licenses in self-contained NuGet packages](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm). Previously released NuGet clients that don't support embedded licences will show instructions (i.e. the https://aka.ms/deprecateLicenseUrl URL) for reading the license in those clients, as stated in the [technical spec](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#nugetorg-license-hosting).
