### ISSUE TITLE
Pre-release floating version doesn't resolve to the latest package.

### ISSUE THREAD

**Issue by DevKumar4Git** [NuGet/Home#7880]
I have this in my proj file. 

```
<ItemGroup>
    <PackageReference Include="PackageName" Version="0.1-*"/>
</ItemGroup>
```

On my feed, these are the pre-release packages with versioning implemented as Major.Minor.Patch. Patch gets incremented on a daily build.
0.1.35-alpha-313f0dda
0.1.38-alpha-ae402cd9
0.1.41-alpha-630080c4
0.1.42-alpha-f5e4e8e7
0.1.43-alpha-1942086d

The floating version 0.1-* doesn’t pick up the latest package, rather it gets the lowest one (0.1.35-alpha*).

Is there a workaround to this?

**Comment by rrelyea** [comment]
We don't have support for "x.y.*-*" yet, but are planning on something like that in the future.
So, don't think you have the ability to float prerelease, given your versioning strategy.

If you could keep the third set of digits to be the same, then you could float the prerelease part of version:
"0.1.0-*"

**Comment by rrelyea** [comment]
Note...this request is covered in: https://github.com/NuGet/Home/issues/912
