### ISSUE TITLE
Only one package is highlighted when updating multiple packages at the same time in PM UI 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#7882]
## Details about Problem
NuGet version: NuGet Client Dev\5.1.0.5896
VS Version: D16.1stg\28714.42
OS: Windows 10 RS4_Release 17134.1.180410-1804

## Detailed repro steps 
1. Create a Console App (.NET Framework) in VS.
2. Open PM UI of this project and install multiple packages (not the latest version).
3. Click “Upadates” tab, check “Select all packages” and click “Update” button.
## Expected
All the packages available to update are highlighted.
## Actual
Only one package is highlighted as below screenshot.
![OnlyOneHighlighted](https://user-images.githubusercontent.com/20632625/54423750-6212da00-474c-11e9-924c-fc489e9465bd.png)

**Comment by rrelyea** [comment]
@v-luzh  — when did this last work? (Need details on regression status)
(Did it work in 15.9? Etc)
Did it work in 16.0?

Update- i fixed my typo

**Comment by v-luzh** [comment]
@rrelyea, It is not a regression issue. It also repro on D16.0 28625.133 (NuGet 5.0.0.5856) , D15.9 28307.158 (NuGet 4.9.3.5777) and D15.8 28010.2050 (NuGet 4.8.1.5435).

**Comment by donnie-msft** [comment]
This isn't really a highlight, but the Selected Package styling is showing while the Update is in progress.

**Comment by v-luzh** [comment]
It still reproes on VS Main\35221.199 + NuGet Client Dev\6.12.0.81.

**Comment by jgonz120** [comment]
This is indicating which one is selected for the details pane. The ones being updated is indicated by the checkboxes.
