### ISSUE TITLE
unable to build project using msbuild pack target with NuGet.Build.Tasks.Pack

### ISSUE THREAD

**Issue by aeos** [NuGet/Home#7893]
## Details about Problem

I am using a combination of: CakeBuild, MSBuild with NuGet.Build.Tasks.Pack
I am building a csproj file targeting .net framework 4.5.2. When I add the pack target to the msbuild command it fails to build complaining about the project.assets.json which is not present in the obj folder.

NuGet version (x.x.x.xxx): 4.9.3.5777
VS version (if appropriate): 15.9.9
OS version: windows 10
## Detailed repro steps so we can see the same problem

1. 
`Executing: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/amd64/MSBuild.exe" /v:minimal /p:Configuration="Debug" /p:FileVersion=0.2.0-testdebugging0001 /p:InformationalVersion=0.2.0-testdebugging0001 /p:PackageOutputPath=C:/ic/hub/build/artifacts/nuspec /target:restore;pack "C:/ic/hub/src/api/ic.hub.api.models/ic.hub.api.models.csproj"`

2. I receive the following error:
`C:\ic\hub\src\api\packages\NuGet.Build.Tasks.Pack.4.9.4\build\NuGet.Build.Tasks.Pack.targets(299,5): error MSB4018: System.InvalidOperationException: The assets file produced by restore does not exist. Try restoring the project again. The expected location of the assets file is C:\ic\hub\src\api\ic.hub.api.models\obj\project.assets.json. C:\ic\hub\src\api\ic.hub.api.models\ic.hub.api.models.csproj]`

**Comment by nkolev92** [comment]
The pack targets only work with PackageReference based projects that generate an assets file. 

Is your project PackageReference based?

**Comment by aeos** [comment]
It is not. Thanks for the hint!

**Comment by nkolev92** [comment]
let us know if you face any issues after moving the project to use a project reference.

**Comment by nkolev92** [comment]
@aeos 

Are you still having issues?

**Comment by aeos** [comment]
Hi

I changed direction so this is no longer an issue.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nkolev92** [comment]
Thanks for following up. 

I will close this issue.
