### ISSUE TITLE
Provide better support for "custom" target frameworks

### ISSUE THREAD

**Issue by madelson** [NuGet/Home#7900]
**Problem**

Creating a .NET assembly that can be used as "Safe" in SQL CLR has various limitations that aren't well captured by target frameworks today (and likely never will be), such as not allowing some usages of static variables (see https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/clr-integration-programming-model-restrictions?view=sql-server-2017 for more).

We publish a number of internal NuGet packages at my company and some teams would like to leverage them in a CLR context. Today, due to these restrictions they invariably must fork the code and make adjustments since few packages meet all the requirements out of the box.

I believe there are other situations which are similar (but which I am less familiar with), such as Blazor (where you might want to ditch a bunch of code that won't be used or won't work to avoid bloat) or .NET Native (similar story).

Another more distantly-related case is optimization; a package must trade off between consumer debugging and performance when deciding to ship an optimized or non-optimized build.

**Existing Workarounds**

Today the main workarounds I know of are:

(a) Split out the codebase into compatible and incompatible parts and ship as separate NuGet packages. For SQL CLR this is often not possible since one class may easily have both features which are useful in the SQL context and features which violate SQL's restrictions.

(b) Create a separate package "MyPackage.SqlClr" which builds the same code under different compilation conditions to get a compatible build. This is more compelling, but requires creating a bunch of new parallel packages and educating consumers about when to install each (and nothing will stop someone from installing both MyPackage and MyPackage.SqlClr).

**Proposed Solution**

One way to address this problem would be to allow for "custom" target frameworks. In this model, a package publisher would produce a separate build as with option (b) above, but could pack that build in with the main package associated with a custom framework alongside builds associated with conventional frameworks.

One way this could work would be using MSBuild properties. For example, I could pack a custom framework like `sqlclr2.0-net45`. When installing, NuGet would look at the target project for a property like `<SqlClr>#.#</SqlClr>`. If that existed, then we'd try to use a `sqlclr#.#` custom framework (the project target framework would then match against the second part of the custom framework as per usual).

**Comment by madelson** [comment]
Basically this is just a request to represent SQL CLR as a target framework

**Comment by nkolev92** [comment]
The challenge here is that NuGet on its own cannot make a package work within a project context. 

That would require build changes (SDK, MSBuild etc). 

As such, I would recommend you file an issue to https://github.com/dotnet/sdk.
If the issue gets enough attention there, we can consider supporting it NuGet side.
