### ISSUE TITLE
IconUrl defined as AssemlyMetadata isn't copied into generated nuspec file

### ISSUE THREAD

**Issue by igor84** [NuGet/Home#7904]
## Details about Problem
NuGet.exe version (4.9.4.5839)

At some point NuGet got the ability to read authors, owners and id from AssemblyMetadata attribute in AssemblyInfo.cs but other metadata like iconUrl are still not read from there. I guess something like this needs to be added to AssemblyMetadataExtractor.ExtractMetadata

`if (builder.Properties.ContainsKey("iconUrl")) builder.IconUrl = builder.Properties["iconUrl"];`

This also goes for metadata like projectUrl, licenceUrl, summary, tags...

**Comment by nkolev92** [comment]
I understand the motivation, but logically I'm not sure why the assembly metadata would contain information like iconurl? 
The owner\author & id feels right, the rest of it not so much. 

What is your project type?
I assume you are using packages.config based restore? 

Have you consider PackageReference + the pack targets? 


https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files

Thoughts @rrelyea @anangaur ?

**Comment by anangaur** [comment]
IconUrl is already deprecated. Not sure if someone would add the new icon property in assemblyinfo.cs

**Comment by igor84** [comment]
Thanks nkolev92. I didn't know about PackageReference and pack targets, those might come in handy. My issue was that when I give nuspec file to the pack command it would pack everything unless I specify <files> explicitly while if I give it csproj file it would pack just the built artifacts just as I needed but would then miss some metadata in the package's nuspec like iconUrl. Also because of our workflow we need major and minor version to match whenever we have a need to switch from using a prebuilt package to using the source project directly and if using nuspec file we then need to remember to update the version in two places: nuspec and AssemblyInfo.
I may be missing something since I just recently started using Nuget so I am still learning.

BTW. If iconUrl is being deprecated what is it replaced with? Packing the icon with the package?

**Comment by nkolev92** [comment]
It's not deprecated yet, but will be very soon. The replacement will be embedded icons. 
You can track the following issue for more information  - https://github.com/NuGet/Home/issues/352

Why do you need to update both the nuspec and the assemblyinfo.cs when revving a version?

**Comment by igor84** [comment]
I was thinking that it might be useful for us to have properties on the dll show the same version as the package but after we though it through we realized it is not actually important.

**Comment by nkolev92** [comment]
things like version and name are important I'd say, but not so sure about the licenseurl & related. 
That feels like a package defining information rather than assembly defining.

**Comment by igor84** [comment]
Yes, when I think about it you are right. Should I close the issue then?

**Comment by nkolev92** [comment]
Yep, if you feel that your concerns have been addressed. 

Thank you for being responsive, it makes our job easier :)
