### ISSUE TITLE
Consider P2P reference to mask nuget references by assembly name

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#791]
Imagine a project with the following structure

Aproject -(p2p) - Cproject
Aproject - (nuget) - Bpackage

Bpackage - ( nuget ) - C.Unofficial.package

Aproject produces a.dll
Bpackage include b.dll
Cprojet produces c.dll
**C.Unofficial**.packages produces **c.dll**

In this case we will get multiple assembly references of the same assemblies and error in design time build and build.

We could consider making the dll mask the package references.

This looks like a project system/Roslyn feature, but I'd like to get a discussion going on this first.

CC @davidfowl @anurse @jasonmalinowski @emgarten @Pilchie

**Comment by jasonmalinowski** [comment]
Scenario makes sense. I think the big question is how we define "same assembly". It seems some metadata should be stated by the user "somewhere" (I don't know where exactly) that says "hey, this project over here is essentially a replacement for for this NuGet package over there" would work quite nicely. No idea where that would go though.

**Comment by yishaigalatzer** [comment]
I believe we covered this by include/exclude feature.

@emgarten can you document this?

**Comment by emgarten** [comment]
Adding a reference in project.json to C.Unofficial.package with `exclude="all"` should fix this.

**Comment by yishaigalatzer** [comment]
That's a doc issue. Just add it to the documents and close this bug

**Comment by emgarten** [comment]
I believe this is already covered in the current docs. Assigning to @karann-msft for tracking

**Comment by kraigb** [comment]
There is a section "Excluding references" in https://docs.microsoft.com/en-us/nuget/consume-packages/dependency-resolution that should take care of this. @yishaigalatzer please verify and close the issue if it's satisfactory.
