### ISSUE TITLE
Deprecate NuGet.exe list in favor of NuGet.exe search

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#7912]
Following the deprecation effort in commands to avoid ambiguity, the `nuget.exe list` command will be renamed to `nuget.exe search`.

## Why we are renaming?
1. The `dotnet.exe list` command lists package or project references in projects or solutions, which is different from listing packages from a feed in the actual `nuget.exe list` behavior. To avoid confusion between those commands, we want to set a more adequate verb for describing the actual `nuget.exe list` behavior.
2. We want to implement new search filters.

## How this will be?
First we'll both commands available in nuget.exe; both of them will have the same functionality, except for `nuget.exe list`, that will display a deprecation warning message each time the command is invoked.

In the upcoming releases, we will remove the `nuget.exe list` command.

The issue tracking all the deprecated commands is : https://github.com/NuGet/Home/issues/7753

**Comment by JonDouglas** [comment]
I'm not a fan of deprecating a command purely because its name. This tool has used a specific command for many years before a new one is introduced.

Let us use simple aliases instead.

**Comment by Dave-Senn** [comment]
@dominoFire `nuget list` list all versions of a package, while `search` only returns the latest version. Will the functionality to list all versions be just lost, or will you add it to `search`.  We use `list` got all versions and do some further processing with the data.

**Comment by Nigusu-Allehu** [comment]
Have you looked into utilizing https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-package-search? Specifically, the `--exact-match` option. It should allow you to list all the versions of a package.

**Comment by Dave-Senn** [comment]
@Nigusu-Allehu Thanks, this is very helpful.
