### ISSUE TITLE
Add extensibility point in NuGet.targets to control if Restore should even run

### ISSUE THREAD

**Issue by zarenner** [NuGet/Home#7917]
No-op PackageReference-style restore performance is not great today for restores of hundred or thousands of projects, and as @nkolev92 has already investigated, there isn't any low hanging fruit to significantly improve it.

As such, repos with many projects may want additional control over if restore even executes, based on their individual setup. For example, consider a large repo that uses traversal projects (dirs.proj), CentralPackageVersions (Packages.props) and uses exact package versions. As long as a restore of the root dirs.proj project has already succeeded, and packages.props does not change, once the entire repo has been restored there is no need to even execute Restore on the projects on the next 'dotnet build'.

If NuGet.targets had an extensibility point to run the Restore task conditionally, it would be possible for a build environment to add custom targets to greatly speed up unnecessary restores. e.g. in the above case they could implement a target which used a '.nugetverify' file or similar to compare against packages.props.

Today, NuGet.targets has no such extensibility, which means that the only solution is to override and reimplement the Restore target entirely, copying the internals of NuGet.targets. This is obviously non-ideal.

**Comment by nkolev92** [comment]
//cc @rrelyea

**Comment by nkolev92** [comment]
`Restore` perf was improved by moving to a different MSBuild parsing mechanism.
Static graph was a feature specifically built for scenarios like NuGet restore. 

https://github.com/NuGet/Home/issues/8791

This has improved evaluation times for 2-3 mins down to 3-4s. 

As such I think this makes this bug redundant.
