### ISSUE TITLE
Remove the usage of Uri for disk path in PathUtility.cs

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#793]
public static string GetPackagePath(string path)
        {
            // Uri.EscapeDataString escapes slashes and white spaces.
            return Uri.EscapeDataString(path).Replace("%5C", "/").Replace("%20", " ");
        }

For example, above method is hacky and could be error prone. We should not be using Uris for disk file path.

**Comment by yishaigalatzer** [comment]
No EscadeDataString is used for figuring out package path
