### ISSUE TITLE
Please allow for prioritizing sources

### ISSUE THREAD

**Issue by AceHack** [NuGet/Home#7938]
If the same package exists in two different sources I would like the ability to prioritize one source over another.  These are various use cases where we already depend on this behavior and it appears to be working.

See https://github.com/NuGet/Home/issues/3676 for a related issue.

**Comment by rrelyea** [comment]
@AceHack - are you asking this because your two packages differ, but have the same identity (id/version)? please describe why it is important, etc...

/cc @anangaur

**Comment by AceHack** [comment]
@rrelyea Yes, we use VSTS i.e. Azure DevOps nuget repos and VSTS to store symbols.  So we have two feeds, 1st feed is optimized and built in release mode.  2nd feed is not optimized and built in debug mode.  This makes testing very easy since you can just point to the debug nuget feed.  Problem is not all the packages are on the debug nuget feed some are only on the release nuget feed, so it would be ideal to try the debug nuget feed first and then trying to release nuget feed.

**Comment by anangaur** [comment]
Doesn’t upstreaming feature in ADO artifacts help you? You could use the debug feed that upstreams to release feed. And just mention the debug feed as source during development.

**Comment by AceHack** [comment]
It does not help because there is no “during development”. We need to deploy to production, production services and at the same time we need to locally debug those same service which include many shared libraries.  We also don’t want to pull release packages in the debug feed.

**Comment by AceHack** [comment]
We also try to not depend on any specific VSTS features around nuget so we could switch providers if needed.

**Comment by princeo911** [comment]
I would also like this to be reenabled. I use BAGet as a local repository as well as a local folder, I would eventually use just BaGet but I will need some time to transition the rest of the team, allowing ordering allows me to prove BaGet works fine and we can get rid of the folders as I feel BaGet is a very good nuget server for us. I  know I can remove the main nuget feed from the list, but I I am not comfortable with this and my team will say no to this suggestion. So we really need to be able to set the ordering. I think on teamcity the ordering of the nuget sources works, when you pass a nuget,config file path to the nugetsources (I think) property but not for visual studio.

**Comment by snowfire20** [comment]
I would also like this feature please. 
just ran into an issue today where a new private nuget source was added, that caused unrelated packages (from a different source) to fail to load.
 the package uses a format that the new source doesn't recognize, which caused an error that stopped the build. If I could order the nuget sources - I would be able to ensure that that problematic source always gets called last. as it stands I will probably have to remove that source, and related package.

**Comment by rrelyea** [comment]
@AceHack - see my comments about different techniques that one can control order in my comment from today on #3676 

@snowfire20 - problematic sources don't sound like a strong reason to add ordering. Make your sources good.

@princeo911  - read your feedback. appreciate you stating your use case.

Closing this issue. please consolidate any votes for this in 3676.
