### ISSUE TITLE
Change all NuGet Docs URLs to use HTTPS

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#7950]
See tweet with picture here: https://twitter.com/onovotny/status/1113137876190019587

ideally...that url should be https://docs.nuget.org not http://docs.nuget.org

**Comment by donnie-msft** [comment]
@rrelyea @nkolev92 
Wanted to mention, I found more URLs in code that are http://.
There's about 50 places, some are comments, some are metadata that I don't know if users will ever see. At least some Strings.resx but many don't show me references. An example string:
`Package '{0}' uses features that are not supported by the current version of NuGet. To upgrade NuGet, see http://docs.nuget.org/consume/installing-nuget.`

This one is only used to output to the Console.
` internal static string NuGetDocsCommandLineReference = "http://docs.nuget.org/docs/reference/command-line-reference";`

**Comment by rrelyea** [comment]
It is reasonable to fix more of these. Why don't you fix all the ones that look very safe like this one. The ones that are questionable, make a list of those, and run by a few people on the team including @anangaur
