### ISSUE TITLE
Show missing metadata on VS PM - package details

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#7957]
The following metadata is shown on Gallery but missing on VS Client:
* Release Notes
* Owner Info: https://github.com/NuGet/Home/issues/442
* Source code repository Link
* Package Size (from https://github.com/NuGet/NuGetGallery/issues/2957)
* Title (https://github.com/NuGet/Home/issues/5772)

New metadata, not yet exposed even on Gallery
* Signing information
* ReadMe

**Comment by loic-sharma** [comment]
Also, I would add the package type (`DotnetTool`, `Dependency`, etc) to the registration API. This is useful if the client has a different UI based on the package's type. For example, the NuGet gallery has a different UI for installation instructions if the package is a [dependency](https://www.nuget.org/packages/NUnit/) or a [tool](https://www.nuget.org/packages/dotnet-format/). Like @anangaur mentions below, this shouldn't show up on the Package Manager UI.

Also, we should consider including the source code's repository type to decide which icon to display.

Edited to clarify :)

**Comment by anangaur** [comment]
We should revisit package type when we discuss Search by TFM experience. IMO different package types shouldn't even show up on PM UI.

**Comment by emulicus** [comment]
Any updates on this?

**Comment by JVimes** [comment]
Release Notes can be important at install/upgrade time.

**Comment by jerrylzy** [comment]
Don't quite understand why this is not getting implemented? I don't think it's a hard change. Fields like release notes are important to MSFT internal customers (devs) and even more so to external customers / users.

**Comment by donnie-msft** [comment]
@chgill-MSFT I made this an Epic since it's pretty broad. I know there's ongoing work to spec out Readme's. Can you please link those here (directly or to the Epic) so I can understand the full scope? Thank you!

**Comment by nkolev92** [comment]
Looks like the majority of the issues listed, with the exceptions of release notes are completed. 

Maybe this can be closed in favor of a dedicated release notes issue?

**Comment by nkolev92** [comment]
Team Triage: Closing this issue as nearly all individual tasks have been completed. 
For release notes, please follow: https://github.com/NuGet/Home/issues/1203.

**Comment by mwpowellhtx** [comment]
Is there a (successful) resolution to this as per the OP request? I'd like to relay `Owner` metadata as well. Thank you...

**Comment by nkolev92** [comment]
@mwpowellhtx That's actively being worked on: https://github.com/NuGet/Home/issues/12501.
