### ISSUE TITLE
insertion of 5.1 into 16.1 preview 2

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#7959]
@nkolev92 created insertion. I just reviewed the payload, and passed to @DoRonMotter for insertion approval.

**Comment by rrelyea** [comment]
VS Insertion done.

These are still outstanding...waiting for branches to exist, i believe.
CLI 
https://github.com/dotnet/cli/pull/11054
https://github.com/dotnet/cli/pull/11053

SDK
https://github.com/dotnet/sdk/pull/3071
https://github.com/dotnet/sdk/pull/3070

**Comment by zivkan** [comment]
New insertion started and the previous cli and sdk PRs have been closed. The new ones are:

CLI
dotnet/cli#11112
dotnet/cli#11113

SDK
dotnet/sdk#3105
dotnet/sdk#3106
