### ISSUE TITLE
During package extraction, unneeded files like <packagefilename>.nupkg.sha512 and [Content_Types].xml are created in the packages folder

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#796]
During package extraction, unneeded files like <packagefilename>.nupkg.sha512 and [Content_Types].xml are created in the packages folder

Repro steps

1. Create a Console Application
2. Install-Package jQuery.2.1.4 (Any package would work)
3. Inspect the packages folder for jQuery

Expected:
All files present are needed

Actual:
Unneeded files like <packagefilename>.nupkg.sha512 and [Content_Types].xml are created in the packages folder

**Comment by martinsuchan** [comment]
I can still reproduce this issue in NuGet v 3.2.60902.10488 in VS2015 when **restoring NuGet packages** - [Content_Types].xml files are added to packages/[package] folders.

**Repro steps**
Create a Console Application
Install Package jQuery
Install Package Microsoft.Net.Http
Inspect the packages folders - no [Content_Types].xml files
Save and close the solution
Remove all folders from the /packages folder
Open the Solution -> right click on solution -> Restore Nuget Packages

**Expected:**
All files present are needed

**Actual:**
Unneeded files [Content_Types].xml are created in some package folders

**Comment by zhili1208** [comment]
investigated it with latest build, can't repro this. we will release new version this week, this should be fixed in that one.

**Comment by martinsuchan** [comment]
It is definitely reproducible with [NuGet v3.2 RC](http://blog.nuget.org/20150902/nuget-3.2RC.html). I was able to reproduce it on another machine now.

**Comment by zhili1208** [comment]
@martinsuchan  I still didn't get an repro with rc version, you said "Unneeded files [Content_Types].xml are created in some package folders", which package folder? thanks

**Comment by zhili1208** [comment]
And the source is nuget.org, right?

**Comment by zhili1208** [comment]
I can repro now, it only repro when v2 is enabled, if there is only v3 enabled, it works well

**Comment by nietras** [comment]
This is definitely still a problem in NuGet 3.2.0 part VS2015 RTM. We get these files whenever we install or update packages.

**Comment by zhili1208** [comment]
@nietras Yes, 3.2 still has this issue, it's fixed in 3.3
