### ISSUE TITLE
Identify dependency nuget packages

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#7964]
<p>When I update NuGet packages I would to know if the package is a dependency (required) for another package.</p><p>In this case I can update only packages I have installed without breaking dependencies.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/437919/identify-dependency-nuget-packages.html
VSTS ticketId: 779424_
_These are the original issue comments:_

Jane Wu [MSFT] on 1/29/2019, 02:24 AM (65 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;You will hear from us in about a week on our next steps.</p>

**Comment by anangaur** [comment]
Seems to be related to `packages.config` based projects that list all the dependencies in a flat list without any indication on which packages were top-level vs those that got installed as dependencies.

**Comment by rrelyea** [comment]
Yes, the solution here is likely with PackageReference. You will only be proposed to update "top-level" or "direct" dependencies. This will prevent you from over-updating a dependencies beyond the desire of the component which uses it.
Can you migrate your solution to PackageReference from Packages.Config? 

See https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8756
