### ISSUE TITLE
How does one clear HttpHandlerResourceV3.CredentialService cache?

### ISSUE THREAD

**Issue by albahari** [NuGet/Home#7965]
So that I can handle authenticated feeds, I've implemented ICredentialProvider as follows:

```
class LINQPadCredentialProvider : ICredentialProvider
{
    public string Id => "LINQPad NuGet Credential Provider";

    public Task<CredentialResponse> GetAsync (Uri uri, IWebProxy proxy, CredentialRequestType type, string message, bool isRetry, bool nonInteractive, CancellationToken cancellationToken)
    {     
        if (type == CredentialRequestType.Proxy) return;
        if (uri == null) return null;
        
        return Task.FromResult (
           new CredentialResponse (new NetworkCredential ("(username)",  "(password)")));
    }
}
```

I then assign it to HttpHandlerResourceV3.CredentialService as follows:

```
var credProviders = new LINQPadCredentialProvider().ArrayOfOne().AsEnumerable<ICredentialProvider>();

var credentialService = new CredentialService (
    new AsyncLazy<IEnumerable<ICredentialProvider>> (() => Task.FromResult (credProviders)),
    false,
    false);

HttpHandlerResourceV3.CredentialService = new Lazy<ICredentialService> (() => credentialService);
```

This works correctly if the username and password is entered correctly the first time. However, if the user first enters the credentials incorrectly, then re-enters them correctly, it still fails. The problem is that the original credentials are cached, and the code above runs only once for a given source. How do I go about clearing the cache?

**Comment by albahari** [comment]
I believe this should be classed as either a bug or an important omission in the API - it appears to be *impossible* to clear the credential cache. This provides a substandard experience when working with authenticated feeds in LINQPad - every time the user makes an change to the credentials, they have to re-start LINQPad. I really want to make LINQPad work properly with authenticated feeds, but this is getting in the way.

**Comment by nkolev92** [comment]
Hey @albahari, 

Thank you for this feedback. We prioritize issues based on the impact & upvotes by the community. 
At this point we don't believe we will be able to get to this issue, but we'd be happy to accept a design and PR for this.

**Comment by albahari** [comment]
Can you at least give me a clue as to where I could look in the source code, so I can start on a design and PR?

**Comment by nkolev92** [comment]
I haven't looked at it in depth, but I imagine it has to be something on the following interface: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Configuration/Credential/ICredentialService.cs.

**Comment by albahari** [comment]
Yes, that's what I would imagine, too. After changing credentials, I create a new `ICredentialService` and re-assign it to `HttpHandlerResourceV3.CredentialService`. However, the service is not called again - the username/password is being cached somewhere else and the old credentials are re-used on subsequent calls. I've looked at the NuGet source code but it's not obvious where or how it's being cached.

**Comment by albahari** [comment]
Never mind - I've figured out what to do. You also need to re-create all the providers (`ProviderFactory.GetCoreV3()`).
