### ISSUE TITLE
NuGetizer - Support for Visual Studio 2019

### ISSUE THREAD

**Issue by daveylad** [NuGet/Home#7967]
Will this extension be updated to support VS2019 ?

Tried running the the installer and although VS2019 is displayed as an option it is greyed out an not selectable.  The message displayed next to the option is "**The extension cannot be installed into this product due to prerequisites that cannot be resolved**"

![image](https://user-images.githubusercontent.com/2338522/55637382-d1647280-57bc-11e9-86d3-a0ac1eea13d4.png)

**Comment by nkolev92** [comment]
//cc @kzu

**Comment by daveylad** [comment]
is anyone looking at this or is it dead in the water ? @nkolev92 @kzu

**Comment by nkolev92** [comment]
@kzu would have info on that. 

I'm on the NuGet.Client team, only the issues repo is shared.

**Comment by derekwheeler-tylertech** [comment]
Is this still in limbo? Microsoft has started to let support for VS 2017 fall behind. (Specifically it no longer supports doing remote xamarin builds to a Mac that runs XCode 11). So we're forced to use VS 2019. And now we can't produce our nugets so we're basically dead. So anyway this could be bumped up priority would be appreciated. Thanks!

**Comment by daveylad** [comment]
I'd say the lack of a single response on this thread from @kzu speaks volumes in itself.

**Comment by zspitz** [comment]
Considering that the SDK project format allows embedding NuGet package details inside the project file, are there still any use case for NuGetizer 3000?

**Comment by daveylad** [comment]
> Considering that the SDK project format allows embedding NuGet package details inside the project file, are there still any use case for NuGetizer 3000?

But if you're unfamiliar with the SDK project and completely familiar with NuGetizer 3000 then that's a use case right there.

**Comment by brandonchastain** [comment]
I was looking around and found [this documentation](https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets) on the MSBuild pack target. It looks like msbuild supports generating packages out of the box now?

**Comment by nkolev92** [comment]
@brandonchastain 

You are correct, that's been around since Visual Studio 2017. 
SDK based projects support it out of the box.
Old style csproj projects with PackageReference work by installing the Pack SDK. https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

**Comment by kzu** [comment]
And all of the packing that this extension used to do, is now supported OOB by the [NuGetizer](https://www.nuget.org/packages/NuGetizer) nuget package which is actively maintained.
