### ISSUE TITLE
Why the CLI after all these years?

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7975]
@Korporal commented on [Sat Apr 06 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1389)

It's incredible that Microsoft have still not added GUI publishing support for nuget packages into Visual Studio. I half expected to see something appear in Visual Studio 2019 but alas no. I can use the GUI to edit package details, I can use the GUI to run "pack" but then I must open a command window (which will no doubt require me to enter a bunch of CD commands to get to the right folder, then perhaps edit my "path" setting to ensure I can find nuget.exe) and enter some cryptic command and hope I don't mistype anything.

Why have Microsoft STILL no added this support?

**Comment by nkolev92** [comment]
Duplicate here: 
https://github.com/NuGet/Home/issues/4459

**Comment by The-Futurist** [comment]
> Duplicate here:
> #4459

@nkolev92 - It's no surprise that this issue is duplicated from time to time. The original issue was opened 2 years ago and nobody has done jack!
