### ISSUE TITLE
NuGet package install failed to add the ApplicationInsights.config file

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#798]
install NuGet 599 from dev branch

repro steps:
 1. create blank app from C#->Windows->Universal, check on AI

expected results: create successfully
actual results: create failed with below error
![aierror](https://cloud.githubusercontent.com/assets/11768961/8202289/2593036a-150b-11e5-8b4f-7b0528d43a87.PNG)

**Comment by danliu** [comment]
It also repros with build 607 with 23016.0 D14OOB.

**Comment by yishaigalatzer** [comment]
By design until appinsights fixes their package. Content is not supported
