### ISSUE TITLE
set website project PackageReference

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#7985]
@sunliusi commented on [Mon Apr 01 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1374)

we have a old website porject. The website project reference netstandard library, website project no "csproj" file. how to set The website project to PackageReference.

**Comment by zivkan** [comment]
@sunliusi PackageReference needs a project file, as that is where the references are stored. Therefore website projects that do not have a MSBuild file are incompatible with PackageReference.
