### ISSUE TITLE
FrameworkReference suppress dependency flow via FrameworkReference.PrivateAssets

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#7988]
Follow up to https://github.com/dotnet/sdk/pull/3102. 

Turns out that there is a netstandard FrameworkReference which needs to be suppressed from transitive flow. 

Need to rethink https://github.com/NuGet/Home/wiki/%5BSpec%5D-FrameworkReference-in-NuGet#what-happens-in-the-future-ifwhen-frameworkreference-are-added-to-other-frameworks. 

[Spec](https://github.com/NuGet/Client.Engineering/pull/95)

//cc @rrelyea @nguerrera @dsplaisted

**Comment by nguerrera** [comment]
I think if we exclude the base framework reference, transitivity is ok. If netstandard ever gets optional framework refs, the meaning would have to be that any tfm compatible with that tfm should have the same optional framework name. But this does make it very important that we do not burn in the framework ref to NETStandard.Library, which is a subset of Microsoft.NETCore.App.

**Comment by nkolev92** [comment]
I wrote up a short spec on this. 

https://github.com/NuGet/Client.Engineering/pull/95

I believe we should go with both: 
`PrivateAssets="all"` & new item for the base framework references to avoid worse problems in the future. 

Feedback both here/on the spec PR is welcome. 
We should briefly sync-up during the partners meeting.

**Comment by nkolev92** [comment]
Synced up with @dsplaisted & @rrelyea 
We're doing only the NuGet side change.  Will introduce a new PrivateAssets attribute instead of Pack. 
It will go in 5.2 & Preview 6.
