### ISSUE TITLE
Microsoft.VisualStudio.SDK is not installed in Visual Studio 2017

### ISSUE THREAD

**Issue by GanesanRengasamy** [NuGet/Home#7989]
Hi, 

I have used the lots of NuGet packages for Visual Studio extension project. Microsoft release the https://www.nuget.org/packages/Microsoft.VisualStudio.SDK/ NuGet pacakges with all the required NuGet packages for Visual Studio extension. So, I have uninstalled all the installed NuGet packages in my machine and tried to install this single package in my source. But I have faced the below issue.

![image](https://user-images.githubusercontent.com/16695209/55934944-f8ed8c00-5c4f-11e9-96af-5fa939f608f7.png)

Then I have migrate my project to 4.6 and I have faced the below issue. 

![image](https://user-images.githubusercontent.com/16695209/55935164-84ffb380-5c50-11e9-9336-8089c839de73.png)

Could you please suggest me what framework version put in my project to install this package?

Thanks,
Ganesan R.

**Comment by zivkan** [comment]
When on the package detail page on nuget.org, you can use the "Contact owners" link to contact the package owner. The nuget team doesn't support individual packages.

About checking package target framework monikers (TFMs), you can check the dependencies on nuget.org's package detail page. For example, expanding the dependencies section for [Microsoft.VisualStudio.CoreUtility version 16.0.467](https://www.nuget.org/packages/Microsoft.VisualStudio.CoreUtility/16.0.467) shows it targets .NET 4.7.2.  Unfortunately some packages that only target a single TFM don't specify which TFM that is in their nuspec file. In these cases, you can take the URL of the package details page: https://www.nuget.org/packages/Microsoft.VisualStudio.CoreUtility/16.0.467
and change the `n` in the hostname to `f` to get https://www.fuget.org/packages/Microsoft.VisualStudio.CoreUtility/16.0.467. There we can see it has libraries for framework net472. If you don't trust 3rd party websites, you can download the package from nuget.org with your browser (there's a download link on the right on the package details page) and then use NuGet Package Explorer, or any program that can open zip files, and check what subdirectories exist in the `lib/` directory.
