### ISSUE TITLE
VS crash when create TypeScript App

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#799]
install NuGet 599 dev, have verified 607 still have the issue
repro steps:
1. select template TypeScript->HTML Application with TypeScript, click OK to create the prpject

expected results: create successfully
actual results: VS crash

dump file and call stack please refer to \\vwdbuild01\temp\V-lawu\dumpfile\D14OOB23012.00Nuget599

**Comment by yishaigalatzer** [comment]
Call stack

 	ntdll.dll!77a47a2c()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	
 	KERNELBASE.dll!76d02320()	Unknown
 	[Managed to Native Transition]	
>	Microsoft.Build.dll!Microsoft.Build.Construction.ProjectElementContainer.Children.get() Line 72	C#
 	Microsoft.Build.dll!Microsoft.Build.Construction.ProjectPropertyGroupElement.Properties.get() Line 50	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluatePropertyGroupElement(Microsoft.Build.Construction.ProjectPropertyGroupElement propertyGroupElement) Line 1126	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) Line 944	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) Line 1824	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) Line 1026	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) Line 1824	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) Line 1026	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) Line 1824	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) Line 1026	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement) Line 1824	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport) Line 1026	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate() Line 774	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate(Microsoft.Build.Evaluation.IEvaluatorData<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition> data, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, int maxNodeCount, Microsoft.Build.Collections.PropertyDictionary<Microsoft.Build.Execution.ProjectPropertyInstance> environmentProperties, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.Execution.ProjectInstance projectInstanceIfAnyForDebuggerOnly) Line 387	C#
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation) Line 2083	C#
 	Microsoft.VisualStudio.CommonIDE.dll!Microsoft.VisualStudio.Build.ComInteropWrapper.ProjectShim.GetEvaluatedProperty(string propertyName) Line 615	C#
 	[Native to Managed Transition]	
 	csproj.dll!CXMakeHelper::GetEvaluatedProperty(MSBuildEngine::IProject * pXMakeProject, const wchar_t * wszPropertyName, ATL::CStringT<unsigned short,ATL::StrTraitATL<unsigned short,ATL::ChTraitsCRT<unsigned short> > > & strPropertyValue, int) Line 845	C++
 	csproj.dll!CLangBuildMgr::GetPropertyValue(const wchar_t * pszPropName, const wchar_t * pszConfigName, unsigned long storage, wchar_t * * pbstrPropValue) Line 1579	C++
 	csproj.dll!CLangHierarchy::GetPropertyValue(const wchar_t * pszPropName, const wchar_t * pszConfigName, unsigned long storage, wchar_t * * pbstrPropValue) Line 5083	C++
 	[Managed to Native Transition]	
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.VirtualProjects.UIHierarchyUtilities.GetTypeScriptBuildConfigurationFromProject(Microsoft.VisualStudio.Shell.Interop.IVsBuildPropertyStorage projectConfiguration, string activeBuildConfigurationName, string propertyName)	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProject.ReadCompilationSettingsFromProject(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy project, string activeBuildConfigurationName)	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProject.UpdateCompilationSettings()	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProject.TypeScriptProject(string projectFilePath, System.IServiceProvider serviceProvider, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy projectHierarchy, System.Action typeScriptProjectItemChangedHandler, System.Action<Microsoft.VisualStudio.Shell.Interop.IVsHierarchy> typeScriptProjectRenamedHandler, Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ScriptIdFactory scriptIdFactory, string toolsVersion)	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProjectProvider.CreateProjectMap()	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProjectProvider.GetProjectMap()	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.TypeScriptProjectProvider.GetProjectSnapshots()	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ScriptContextProvider.ComputeContextsAsync(bool force, System.Threading.CancellationToken cancellationToken)	Unknown
 	Microsoft.CodeAnalysis.TypeScript.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.TypeScript.ScriptContexts.ScriptContextProvider.ComputeContextsAfterDelay.AnonymousMethod__3(System.Threading.Tasks.Task _)	Unknown
 	mscorlib.dll!System.Threading.Tasks.ContinuationResultTaskFromTask<System.Threading.Tasks.Task>.InnerInvoke() Line 111	C#
 	mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
 	mscorlib.dll!System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(object obj) Line 694	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 111	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl() Line 583	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state) Line 528	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891	C#
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke() Line 441	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue() Line 2232	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 2485	C#
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 341	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o) Line 494	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 104	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 37	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs) Line 1445	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 392	C#
 	[Native to Managed Transition]	
 	user32.dll!74bc5013()	Unknown
 	user32.dll!74ba4b80()	Unknown
 	user32.dll!74ba4481()	Unknown
 	msenv.dll!SCMI::FPreTranslateMessage(tagMSG * pMsg) Line 226	C++
 	msenv.dll!SCM::FPushMessageLoop(SCMI * pscmi, unsigned long uReason, void * pvLoopData) Line 2260	C++
 	msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long dwComponentID, unsigned long uReason, void * pvLoopData) Line 2996	C++
 	msenv.dll!CMsoComponent::PushMsgLoop(unsigned long msgloop) Line 705	C++
 	msenv.dll!VStudioMainLogged() Line 1187	C++
 	msenv.dll!VStudioMain(MAINPARAM * pMainParam) Line 1268	C++
 	devenv.exe!util_CallVsMain(MAINPARAM * pMainParam, int * piRes) Line 1080	C++
 	devenv.exe!CDevEnvAppId::Run(wchar_t * wszCmdLine, int nCmdShow) Line 755	C++
 	devenv.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * lpCmdLine, int nCmdShow) Line 64	C++
 	devenv.exe!__scrt_common_main_seh() Line 264	C++
 	kernel32.dll!74db3754()	Unknown
 	ntdll.dll!77a3a821()	Unknown
 	ntdll.dll!77a3a7ec()	Unknown

**Comment by danliu** [comment]
Have filed external bug and close this one.
