### ISSUE TITLE
Support for `<PackageIcon/>` in .*proj files

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#7992]
`nuget.exe` and `dotnet.exe` should be able to recognize and process `<PackageIcon/>` property in new-style csproj projects.

The main issue is: https://github.com/NuGet/Home/issues/352

**Comment by gsscoder** [comment]
I can see problems also with `PackageLicenseExpression`, impossible to reference a file. But with **LICENSE CODE** works.
