### ISSUE TITLE
What's the Lifecycle Policy of NuGet Windows x86 Commandline?

### ISSUE THREAD

**Issue by KexyBiscuit** [NuGet/Home#7994]
[Search product lifecyle](https://support.microsoft.com/en-us/lifecycle/search?alpha=nuget) returns nothing about NuGet, nuget.org provides so many versions of CLI, and the recommended latest version is still v4.9.4 now, I'm wondering how are the versions supported? Is there any doc about this?

**Comment by zivkan** [comment]
@anangaur @karann-msft @rrelyea ?

**Comment by rrelyea** [comment]
Discussed an initial proposal with NuGet Leads on Friday.

**Comment by nkolev92** [comment]
fyi @aortiz-msft

**Comment by aortiz-msft** [comment]
@JonDouglas - Could you please help with this one?

**Comment by JonDouglas** [comment]
@KexyBiscuit You can find information about NuGet's servicing here:

https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing#components-not-covered-by-visual-studio-servicing

> For Microsoft components that are installed by Visual Studio and do not have an explicit lifecycle policy in the lifecycle database, the supported version is the latest version that is currently available for download.

In other words, the supported version is the latest version that is currently available [here.](https://www.nuget.org/downloads)

If you use NuGet through the .NET CLI, you would instead follow this support policy:

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

For more details on Microsoft Lifecycle Policy, see https://docs.microsoft.com/en-us/lifecycle/policies/modern
