### ISSUE TITLE
NU1004 does not have a docs page

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#7996]
## Details about Problem
NuGet Version: Dev\5.1.0.5954
VS Version: D16.1stg 28808.226
OS Version: 17763.RS5_Release.180914-1434.
## Detailed repro steps 
1. Launch VS 2019 and create a new Class Library (.Net Framework) project.
2. Install a few ‘PackageReference’ packages into the project.
3. Set MSBuild property “RestorePackagesWithLockFile” to true in csproj file.
4. Do a restore.
5. Check it should have generated ‘packages.lock.json’ file alongside *.csproj file.
6.  Set msbuild property “RestoreLockedMode” to “true”.
7. Install another package.   
8. It should still work fine and update ‘packages.lock.json’ file.
9. Manually add a new PackageReference item into csproj file.
10. Perform restore.
11. Restore should fail stating “restore is running in locked mode but it needs to update the lock file…”
## Expected
Clicking error link NU1004 in VS Error List window goes to the correct document of error NU1004.
## Actual
Clicking error link NU1004 in VS Error List window goes to the wrong page as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/56021760-d2594f00-5d3c-11e9-8000-01b6e9d5f3aa.png)

**Comment by nkolev92** [comment]
The NU1004 page does not exist. 
This is a docs problem.

**Comment by rrelyea** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1441](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1441) via [**ZenHub**](https://www.zenhub.com/)

**Comment by rrelyea** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1440](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1440) via [**ZenHub**](https://www.zenhub.com/)
