### ISSUE TITLE
Use URI Templates instead of RegistrationsBaseUrl

### ISSUE THREAD

**Issue by jeffhandley** [NuGet/Home#80]
Building on #79, we should use URI templates instead of using the RegistrationsBaseUrl.  We are currently constructing URLs on top of the RegistrationsBaseUrl and that is hard-coding server specifics into the client when the server should be able to dictate how the addresses are formed.

Additionally, we seem to have other issues with how we're using RegistrationsBaseUrl.  For example:

1. We are using the same resource type for both dependency resolution and display metadata -- this is a no-no. We should instead have 2 separate resource types, even if pointing to the same resource, with one for dependency resolution and the other for display metadata.
1. We are never actually consuming the version-specific blobs for a package; instead, we're always consuming the data from the registration's index.json.  We should be able to refactor these blobs to get the right data in the most efficient way.
1. We aren't handling that there could be multiple resources exposed for the resource type needed

**Comment by RanjiniM** [comment]
Assigning to John as he suggested not doing this. John can add his proposal.
