### ISSUE TITLE
[Test issue] package jQuery doesn't be installed when install package jQuery.Validation on BlankApp(Universal Windows)

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#800]
install NuGet 599 dev, have verified 607 still have the issue

repro steps:
1. create blank app thru click C#->Windows->Univerdal-> Blank App(Universal Windows)
2. install package jQuery.Validation
3. select Filter_Installed, search jQuery
4. install package elmah, libphonenumber-csharp, get error "Package restore failed"
5. install package TestPackage.MinClientVersion, 

expected results: 
on step3, package jQuery should be installed, 
on steps4, should no error
on step5, should get error "The 'TestPackage.MinClientVersion 1.0.0' package requires NuGet client version '9.9999.0' or above, but the current NuGet version is '3.1.0'. To upgrade NuGet, please go to http://docs.nuget.org/consume/installing-nuget"

actual results: 
on step3, package jQuery doesn't be installed, 
on step4,5, get error "Package restore failed,"

**Comment by yishaigalatzer** [comment]
We don't support content in this world with `project.json`, so this is expected. Please update the tests.

**Comment by danliu** [comment]
We have updated our test bed to exclude UWP for jQuery check.

For failures in step 4 and 5, it's bug https://github.com/NuGet/Home/issues/859.
