### ISSUE TITLE
NuGet automated suggestion of installing package based on "using" keyword in C#.

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8006]
VSF_TYPE_MARKDOWNFor example I have &quot;using Newtonsoft.Json&quot; in my C# file header. Clicking on this when package Newtonsoft.Json is not installed should suggest installing appropriate NuGet package.

It already works when I click on a class reference in code, however the rules for it working is undocumented. I don't know how to make classes from my own NuGet packages handled like this. It works for Newtonsoft, it doesn't work for many others.

It works for classes, but it would be easier if it worked for namespaces. Because the class name is derived from what the class do or model, the namespace - from it's author, brand or similar. So the namespace would be more unique than a class name, so it should give a better hint about which NuGet package to suggest.

My idea is to use namespace for a simple NuGet directory search. Most of the time the namespace and package name are the same, or at least have a significant common part.

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/524382/nuget-automated-suggestion-of-installing-package-b.html
VSTS ticketId: 843340_
_These are the original issue comments:_

Jane Wu [MSFT] on 4/10/2019, 00:54 AM (6 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by zkat** [comment]
We believe this is a Roslyn issue, so I've reopened the feedback ticket and sent it the right way.
