### ISSUE TITLE
If login is needed for nuget feed notify user of the url to access in the login prompt

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8008]
<p>When opening an existing project that needs access to controlled access nuget feeds the login dialog repeatedly appears with no information as to what needs logging into or why he login failed.</p><p>Please look at adding some way to notify the user of what nuget feed needs login credentials and/or if login credentials failed for a specific feed.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/495932/if-login-is-needed-for-nuget-feed-notify-user-of-t.html
VSTS ticketId: 822458_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/18/2019, 01:30 AM (29 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by nkolev92** [comment]
This is not really NuGet. 

We integrate with the VS identity, so it'd be on that product to provide a way to specify the url for which the authentication request is happening for. 

Keeping it open as I don't know if any action would be necessary from NuGet perspective.

**Comment by nkolev92** [comment]
Tracking as dup of https://github.com/NuGet/Home/issues/1500
