### ISSUE TITLE
Restore failed for WAP project after deleting the packages

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#801]
install NuGet 606 3.0-rtm

repro steps
1. create MVC5 Application or empty webApplication 
2. save the project and close VS, delete package folder
3. open the project create previously and build solution

expected results: build successfully
actual results: restore failed
![restoreerror](https://cloud.githubusercontent.com/assets/11768961/8206588/8d86acfc-152d-11e5-9250-da1e180373fc.PNG)

**Comment by danliu** [comment]
This is the by design. The packages are not available on nuget.org yet.
