### ISSUE TITLE
line continuation in package manager console

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8010]
<p>With Core, Scaffold-DbContext lines are long. Ability to split over more than one line would be useful.</p><p>This is already available in most shells (bash, powershell etc)</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/idea/480145/line-continuation-in-package-manager-console.html
VSTS ticketId: 812475_
_These are the original issue comments:_

Jane Wu [MSFT] on 3/7/2019, 00:19 AM (40 days ago): <p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>

**Comment by nkolev92** [comment]
Thank you very much for your feedback. We appreciate you letting us know about the problem you encountered. Based on community feedback, this is currently low priority for us.
