### ISSUE TITLE
Update docs on how to create a dotnet cli template package with dotnet pack

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8018]
The following docs page says this: https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file

> Currently, a custom template is packed on Windows with nuget.exe (not dotnet pack). For cross-platform packaging, consider using NuGetizer 3000.

We should update the docs to explain how to pack with `dotnet pack`.

**Comment by Thraka** [comment]
If someone can give me the steps, I can update the doc to describe it.

**Comment by zivkan** [comment]
@Thraka it involves some investigation. My guess is the only reason they say it's necessary to use `nuget.exe` is because they use the `<packageType>` element. The other fields they have in the table are definately possible to set in the csproj. So, we should check nuget pack targets to see whether or not it's possible to specify the package type in a csproj. If not, test if putting a nuspec in the csproj directory allows the package to be packed correctly with `dotnet pack`.

**Comment by Thraka** [comment]
I've figured it out after a ton of trial and error. I'm going to be removing various variables to determine the minimum needed to get this working.

**Comment by Thraka** [comment]
Is there a spec on template.json?

**Comment by Thraka** [comment]
I found the wiki at https://github.com/dotnet/templating/wiki which has a bunch of info

**Comment by jchannon** [comment]
I just got this working thanks to @sayedihashimi with the following command

`dotnet pack ./content/CarterTemplate.csproj -p:nuspecfile=/Users/jonathan/projects/carter/template/cartertemplate.nuspec`

You can try it out from this repo https://t.co/J7jcxS2Goo

Hopefully this info can help the docs

NOTE: the nuspecfile has to be a full path

**Comment by zivkan** [comment]
Double-checking [.NET Core's docs on packing templates](https://docs.microsoft.com/en-us/dotnet/core/tools/custom-templates#packing-a-template-into-a-nuget-package-nupkg-file), they've already updated it to show how to pack using nothing more than the dotnet cli and a csproj. No custom `nuspec`, no `nuget.exe`.

Closing this issue as it's complete.
