### ISSUE TITLE
Clearly defined review process

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8024]
Discussed during our retrospective. 
Clearer problem statements, internal/external review process.

//cc @NuGet/nuget-client @anangaur @rrelyea

**Comment by nkolev92** [comment]
fyi @anangaur 

Last time we discussed we decided to use Client.Engineering as an interim thing. 

We'd be happy use a designs repo if created.

**Comment by zivkan** [comment]
Or just puts the spec in a `specs` folder here in the Home repo?

**Comment by nkolev92** [comment]
Done with https://github.com/NuGet/NuGet.Client/blob/dev/docs/feature-guide.md
