### ISSUE TITLE
PackagePathResolver.GetInstalledPath(PackageIdentity) could be more efficient

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#803]
PackagePathResolver.GetInstalledPath(PackageIdentity) could be more efficient

Today, PackagePathResolver.GetInstalledPath(PackageIdentity) computes all the possibilities by trying different values for versions. And, then, checks if the nupkg file exists on each one of those possibilities. This code comes from NuGet.Core

Instead, PackagePathResolver.GetInstalledPath(PackageIdentity) should enumerate all the directories starting with <packageId> and compare the versions with the input after normalizing them

Suggested by @yishaigalatzer

**Comment by yishaigalatzer** [comment]
This needs to be measured, there is no guarantee that this will actually improve the scenario. However it is currently very slow.

**Comment by nkolev92** [comment]
Redundant now. 
This has changed.
