### ISSUE TITLE
Unable to find package error when calling Update-package to ASP.NET 5 project

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#804]
Repros with latest dev build.

1.File->New Project->Visual C#->Windows->Blank App(Windows Universal).
2.Check Application Insights checkbox.
3.After the project has been created, build.
4.Open Manage NuGet Packages… UI.
5.Open Package Manager Console , type Get-Package -updates, and select one , type update-package Microsoft.ApplicationInsights.

Expected: works fine

Actual:
Update-package: Unable to find package 'Microsoft.NETCore.UniversalWindowsPlatform'.Existing packages must be restored before performing an install or update.

Verified that install-package works fine.

**Comment by emgarten** [comment]
Fixed with NuGet/NuGet.PackageManagement@5c2aac5148274ad92e1e257effb9b50bed155b36

**Comment by danliu** [comment]
Looks like this still reproes with latest dev build.
