### ISSUE TITLE
Implement `nuget.exe search`

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8040]
nuget.exe search command:
- [x] Implement query search
- [x] Implement take flag
- [ ] Implement skip flag
- [x] Implement prerelease flag
- [ ] Implement semver flag
- [x] Modify tests to reflect new `nuget.exe search`

NuGet Search API: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource

**Comment by karann-msft** [comment]
related issues -  [exact match and version search for nuget.exe list command #5138](https://github.com/NuGet/Home/issues/5138)

**Comment by TiltonJH** [comment]
Please consider implementing a `IncludeDelisted` flag as well.

I do understand that `nuget.org` or other nuget servers might not want such an feature to exists. But what is the harm of having such an option to opt-in to?
I would like to use that flag with my own nuget server. So it would be nice if I could turn that option on on my own server and then be able to use the `IncludeDelisted` flag in a search.

**Comment by chrisraygill** [comment]
@zkat @dominoFire does this still have pending work?

**Comment by nkolev92** [comment]
Search isn't implemented in nuget.exe

**Comment by nkolev92** [comment]
I don't really know what I was looking up. NuGet.exe search is implemented using the search resource. 5.8 is the first version with this functionality.
