### ISSUE TITLE
Signing: Fix 22 test failures on Mac OS

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8047]
There are still 22 test failures on Mac OS. 
* [x] 4 of this fail because chain building for verification doesn’t call the OCSP server. It seems like OCSP is called once for signing the package, but then when trying to build the chain for the same package in verification, the OCSP server is not being hit.
 
* [x] This 4 tests seem to behave differently on Mojave vs Sierra. On Sierra chain building fails in signing, while in Mojave signing succeeds but then verification fails with the OCSP server issues. 
The chain building issues in Sierra seem similar to the issues in the 18 other tests that don't repro in Mojave, so they might be related.

* [x] Other 18 I have not been able to repro 

The machine I use is on MacOS Mojave (10.14.2) while the CI is on MacOS Sierra (10.12.6) so there might be fixes done by the underlaying OS. 
In MacOS Mojave the string "The trust policy was not trusted." changed to "The certificate was not trusted." for Untrusted Root. If CI is updated, this would need to be updated for 7 tests to pass.
Only 13.16% of MacOS users use Sierra, while 36.57% use Mojave (see http://gs.statcounter.com/macos-version-market-share/desktop/worldwide)

This is one of the breakdown tasks from NuGet/NuGet.Client#2706

**Comment by nkolev92** [comment]
The 4 tests that behave differently on mojave are: 

Verify_WhenChainBuildingFails_Throws
GetCertificateChain_WithUntrustedSelfIssuedCertificate_ReturnsChain
Verify_WithUntrustedSelfSignedCertificate_Succeeds
GetCertificateChain_WithUntrustedRoot_Throws

These will be disabled in https://github.com/NuGet/NuGet.Client/pull/3003 and need to be re-enabled later when fixing this particular issue. 

@heng-liu Let me know if you want a separate issue or this one is enough.

**Comment by heng-liu** [comment]
@nkolev92 this one is enough. Thanks!

**Comment by zkat** [comment]
Closing this. We'll create new issues as needed.
