### ISSUE TITLE
PackageReference range with exclusive lower bound does not work if the lower bound is present on one of the sources.

### ISSUE THREAD

**Issue by cilerler** [NuGet/Home#8054]
📌 **_Transferred from https://github.com/aspnet/AspNetCore/issues/9680_**

### Describe the bug
PackageReference exclusive definition does not work correctly.  

> **_According to [Microsoft Docs](https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards)_**
> _Notation `(1.0,2.0)` Applied Rule `1.0 < x < 2.0` Description `Exact range, exclusive`_

### To Reproduce

1. Confirm that you have **SDK 2.2.203** through `dotnet --info`
2. Create a new console project `dotnet new console`
3. Add a package with `dotnet add package Ruya.AppDomain`
4. Locate the error message `error: Unable to find package Ruya.Primitives with version (> 1.0.470)`
5. You may see the complete Ruya.AppDomain.csproj file [here](https://github.com/cilerler/ruya/blob/0676f0eb70c84fc2f169c458d2d440f828b3ed7d/src/Ruya.AppDomain/Ruya.AppDomain.csproj#L20)
6. Go to https://www.nuget.org/packages/Ruya.Primitives/
7. Locate that there is a version above 1.0.487 

![image](https://user-images.githubusercontent.com/385958/56580794-7777f100-65a1-11e9-9d60-1ff2132dea9f.png)

### Expected behavior
It should pick the correct version of the package _(Ruya.Primitives 1.0.487 in this case)_ correctly.

### Screenshots

![image](https://user-images.githubusercontent.com/385958/56582060-6381be80-65a4-11e9-8e85-ad9b434de189.png)

### Additional context

output of `dotnet --info`

![image](https://user-images.githubusercontent.com/385958/56582264-dbe87f80-65a4-11e9-84d3-236a2c5cfbc3.png)

**Comment by nkolev92** [comment]
Thanks for creating this @cilerler. 

Do you know if this is a new behavior? 

I'd imagine the problem is here, https://github.com/NuGet/NuGet.Client/blob/5b975f446808a318e0696c8c23cd2dd6b9aa817b/src/NuGet.Core/NuGet.Commands/RestoreCommand/SourceRepositoryDependencyProvider.cs#L211

Related https://github.com/NuGet/NuGet.Client/pull/2578. 

I would imagine 2.2.10x line does not have this bug.

**Comment by nkolev92** [comment]
@rrelyea This looks like a regression worth investigating.

**Comment by cilerler** [comment]
@nkolev92 as long as I know it was there forever. 
Moreover, you are probably right about the code location; and, I don't see any indication of filtering the unlisted ones.

**Comment by nkolev92** [comment]
Quick check suggests that 2.1.500 does not have this bug, so I think my "educated guess" above is correct. 
This is a regression.

**Comment by nkolev92** [comment]
Unlisted ones are handled in different ways depending on the scenario. Unlisted versions are allowed in certain cases.

**Comment by cilerler** [comment]
Great, so, should I expect a fix soon? 😄

**Comment by nkolev92** [comment]
@cilerler 

We will triage and come back to you when we know more.

**Comment by nkolev92** [comment]
As a workaround you can always specify 
`<PackageReference Include="Ruya.Primitives" Version="[1.0.471,)" />`

It will have the same meaning.

**Comment by nkolev92** [comment]
@cilerler 

This will be in:
5.1 of NuGet
16.1 of Visual Studio 
2.2.300/ 2.1.700/ 3.0.100-preview6 of the SDK.
