### ISSUE TITLE
[NuGet.VisualStudioExtension] If "Update Available" for a selected package the default action must be "Update"

### ISSUE THREAD

**Issue by xperiandri** [NuGet/Home#806]
When I select a package which has an "Update Available" its action must be set to "Update"!
And when selected package is already installed its action must be set to "Remove" (or be configurable between "Install" and "Remove" within extension settings)

It is very annoying accidentally installing package for all the projects in solution instead of updating it for a few projects where it has already been installed just by habit left from previous package manager.

http://stackoverflow.com/questions/29966905/visual-studio-2015-rc1-manage-nuget-packages-for-solution

**Comment by yishaigalatzer** [comment]
Thanks for reporting this again. This bug did come to our attention and was fixed. By the way did you already try RC-2? http://nuget.codeplex.com/releases/view/615507

Here is what it looks like now:
![image](https://cloud.githubusercontent.com/assets/1238711/8222219/e7415afa-151c-11e5-99c3-7f807470e3ef.png)
