### ISSUE TITLE
Public API to parse "VersionRanges"

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#807]
PLIB need to parse strings into `VersionRanges`. I'm not sure if we'll need to parse `NuGetVersions` at some point.

**Comment by rchande** [comment]
We'll also need to functionality of VersionRangeComparer.

**Comment by emgarten** [comment]
@rchande can you provide more details on your scenarios here? Which methods/properties on the current VersionRange class and NuGetVersion are you using?

**Comment by rchande** [comment]
We're trying to compute the "intersection" of metapackages, which involves grouping them by id, throwing away the packages that don't apply to all the targets, and then taking the package with the highest version. Since can packages be specified in project.json with VersionRanges, we're taking the specified VersionRange with the highest minimum version.

With that implementation, we need an API that goes from a string to a NuGetVersion (or some kind of comparable thing) where that NuGetVersion is either the minimum of the range, or a specific version if that's what was specified.

**Comment by yishaigalatzer** [comment]
I'm not sure why you are doing this for. Can you provide more details? I'm not sure why this kind of code is running outside of NuGet and what is it for exactly

**Comment by davidfowl** [comment]
I agree with Yishai, what exactly is this for?

**Comment by yishaigalatzer** [comment]
This is to cleanup the public API on nuget.versioning and declaring it a public API rather than the internal API it is today.

This means locking down our public API to be final and no breaking changes inside a semver version once it is out

**Comment by yishaigalatzer** [comment]
Closing this as for inside VS we are going to provide a public API through IVSxxx interfaces https://github.com/NuGet/Home/issues/826
