### ISSUE TITLE
Custom CPS projects require AssemblyReferences project capability in order to restore.

### ISSUE THREAD

**Issue by kfertitta** [NuGet/Home#8071]
Our custom project systems are built on CPS and use a project SDK to import our targets.  We also import the Microsoft common targets.  Ours are not .NET project types, but full-on custom projects which produce domain-specific (non-assembly) artifacts.  While we do require support for the `ProjectReferences` capability and need to see project references in the dependencies tree in Solution Explorer, we have no notion of assembly references.  However, without declaring the `AssemblyReferences` project capability, our project does not perform a NuGet restore automatically when we create the project with our template wizard nor does it restore an existing project when opened.  With the `AssemblyReferences
<img width="1535" alt="Untitled" src="https://user-images.githubusercontent.com/1080656/56930757-b40c8680-6a92-11e9-9f75-530eb41f86e1.png">
` project capability in place, along with imports for the corresponding XAML rules files, everything works fine.

This leads to confusion for our customers that see dependencies that don't apply.  Please see the attached screenshot.

**Comment by nkolev92** [comment]
Apologies for the delay. 

We need to work with @davkean & project-system to clarify the capabilities NuGet should require from the project-systems in order to support auto restore. 

//cc @rrelyea

**Comment by nkolev92** [comment]
Maybe fixed by https://github.com/NuGet/NuGet.Client/pull/3726 and https://github.com/NuGet/NuGet.Client/pull/3644.

**Comment by nkolev92** [comment]
Confirmed that this is fixed. 
In here, https://github.com/NuGet/NuGet.Client/blob/a4c9d63bf942f1df1ba9486a87bad2e4b6888488/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/Projects/CpsPackageReferenceProjectProvider.cs#L77-L78 the checks are `CPS` and `PackageReferences` support.

**Comment by nkolev92** [comment]
Please note that this was fixed in 5.9, so it will be in the next Visual Studio 16.9 preview.
