### ISSUE TITLE
Deprecation Mechanism for nuget.exe commands

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8072]
Some `nuget.exe` commands will be deprecated. We need something to mark as deprecated and show warning messages in proper places.

## Why not `Obsolete` c# attribute ?

- You cannot provide an alternative command with the message parameter. 
- The message is almost the same for deprecation commands
- You cannot inherit the `Obsolete` to make your custom deprecation attributes

## Scenarios

Suppose `command` is the command to deprecate. The following scenarios must show a warning message:

`nuget.exe command`

`nuget.exe command -h`

`nuget.exe help command`

`nuget.exe help -all`

`nuget.exe help -all -markdown`

**Comment by nkolev92** [comment]
This tracks means of getting to an outcome rather than outcome. 

Closing.
