### ISSUE TITLE
Lock file is not honored in "*" scenarios 

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#8073]
Sample repo: https://github.com/NuGetPlay/TestLockFile

## Steps:
1. New project with `RestorePackagesWithLockFile` set
2. Take a dependency on a package with ` * `
3. Restore project
   * The lock file will be generated with the highest version (say **1.0.0**) present on the package source(s).
4. Add a newer version of the package (say **1.1.0**) to the repository (preferably local to avoid caching issues).
5. Delete obj, bin folders. 
6. Restore again, OR
7. Restore with `--locked-mode`

## Expected
* For 6, The restore should complete without modifying the lock file. Version **1.0.0** should be restored.
* For 7, the same should happen as 6. Restore **should not** fail.

## Actual
* For 6,  restore overrites the lock file, bringing in the version **1.1.0**
* For 7, restore **fails**.

**Comment by nkolev92** [comment]
* 6 
Isn't this by design? By deleting the obj folder you are defeating the no-op cache and forcing a full restore. The full restore will look at the sources again and update the lock file to contain what was restored locally. 

* 7 
This needs investigated. 
I fixed a couple of things in 5.1, but looking at this, I don't think this scenario is affected by those bugs.

**Comment by anangaur** [comment]
6. is not by design. One of the problem statements was to be able to restore the same version with ` * ` again and again if the lock file has it and no input package references change.

**Comment by nkolev92** [comment]
5.1 P4 has a few more days of M2 so if you want it in 5.1, bug @rrelyea early. 
If not, it likely slips to 5.2

**Comment by nkolev92** [comment]
Actually, I know the issue with 6 lol. 

And probably that's what's causing 7 too. 
In our version range normalization, 

"" = "(, )" 
"*" = "(, )" 

Pretty sure it's the same root cause as https://github.com/NuGet/Home/issues/6697.

**Comment by anangaur** [comment]
Not sure. Do we even look at the lock file to do a restore when no obj folder exists? If not, that would be the main culprit.

**Comment by nkolev92** [comment]
We do. 

You were right about 6. I think it's going to restore the same version again and again (haven't tested, but I'd imagine something like "1.*" would work). 

A culprit is definitely the fact that `*` does not round trip.
