### ISSUE TITLE
Downloads count of IPackageSearchMetadata 

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/Home#8075]
Hi,

I using Nuget.Protocol.Core.v3.dll in a .NET Standard lib for my powershell cmdlets like.

```cs
 private IObservable<IPackageSearchMetadata> PackageSourceSearchMetadatas(string source,string name,
            List<Lazy<INuGetResourceProvider>> providers){
            var metadatas = new SourceRepository(new PackageSource(source), providers)
                .GetResourceAsync<PackageMetadataResource>().ToObservable()
                .SelectMany(resource => resource
                    .GetMetadataAsync(name, IncludePrerelease, IncludeUnlisted, NullLogger.Instance,CancellationToken.None).ToObservable()
                    .SelectMany(enumerable => enumerable.ToArray())
                );
            return metadatas;
        }
```

the method works fine and can list all metadat, however for Nuget.org the DownloadsCount is null and for my custom Nuget.Server is -1. Is there a way to make it work with Nuget.Protocol.Core.v3.dll?

**Comment by nkolev92** [comment]
Apologies for the late reply. 

The V3 feeds such as nuget.org have the concept of resources, each specialized for certain tasks. 

What you are hitting with the PackageMetadataResource resource is the following https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource. 
It simply doesn't contain download count. 

The IPackageSearchMetadata is shared and depending on what endpoint is hit, different values might be populated. 
Can you try the PackageSearchResource? That goes against https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource. 

For reference take a look at https://docs.microsoft.com/en-us/nuget/api/overview. 

Another suggestion, you can use the NuGet.Protocol package. It replaced the NuGet.Protocol.Core.v3/v2 packages.

**Comment by 0xced** [comment]
> It simply doesn't contain download count.

It's quite misleading since `IPackageSearchMetadata`, returned by the `PackageMetadataResource.GetMetadataAsync()`, has a `DownloadCount` property which is always `null`.

But here's how to get the total downloads for a given NuGet package using [NuGet.Protocol](https://www.nuget.org/packages/NuGet.Protocol) and `PackageSearchResource`.

```csharp
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using NuGet.Common;
using NuGet.Configuration;
using NuGet.Protocol;
using NuGet.Protocol.Core.Types;

const string packageId = "Newtonsoft.Json";

var downloadCount = await GetDownloadCountAsync(packageId);
Console.WriteLine($"{packageId} total downloads: {downloadCount:N0}");

static async Task<long?> GetDownloadCountAsync(string packageId)
{
    var repository = Repository.Factory.GetCoreV3(NuGetConstants.V3FeedUrl, FeedType.HttpV3);
    var search = await repository.GetResourceAsync<PackageSearchResource>();
    var result = await search.SearchAsync($"packageid:{packageId}", new SearchFilter(includePrerelease: false), skip: 0, take: 1, NullLogger.Instance, CancellationToken.None);
    return result.FirstOrDefault()?.DownloadCount;
}
```
