### ISSUE TITLE
Props and target files in build\native are not referenced in vcxproj

### ISSUE THREAD

**Issue by heaths** [NuGet/Home#8078]
## Details about Problem

NuGet product used: nuget.exe, "msbuild /restore" (16.x)

NuGet version: 4.9.3.5777

OS version: Win10 v1809

## Detailed repro steps so we can see the same problem

1. Add reference: `<PackageReference Include="rapidjson" Version="1.0.2" IncludeAssets="all" PrivateAssets="all" />`

2. Run: `nuget restore` on solution

The generated project.assets.json has solution-level package references from a Directory.Build.props higher up, but does not reference the `build\native\rapidjson.targets` as nuget.exe (same version) did with packages.config prior to migration.

Here's a snippet of project.assets.json:
```json
      "Nerdbank.GitVersioning/2.3.125": {
        "type": "package",
        "build": {
          "build/Nerdbank.GitVersioning.targets": {}
        },
        "buildMultiTargeting": {
          "buildCrossTargeting/Nerdbank.GitVersioning.targets": {}
        }
      },
      "rapidjson/1.0.2": {
        "type": "package"
      },
      "Roslyn.Diagnostics.Analyzers/2.6.3": {
        "type": "package",
        "build": {
          "build/Roslyn.Diagnostics.Analyzers.props": {}
        }
      },
```

The files are known, however:
```json
    "rapidjson/1.0.2": {
      "sha512": "uYKgq5H2pC6yOjjRQKjXsOFiOrO4bPWwQBiOS3fH/5+u/PuB9ZoA1/OZfmybGa68RURhZhmyvB3kcmyQnhIqmg==",
      "type": "package",
      "path": "rapidjson/1.0.2",
      "files": [
        ".nupkg.metadata",
        "build/configurations.autopkg",
        "build/native/default-propertiesui.xml",
        "build/native/include/rapidjson/allocators.h",
        "build/native/include/rapidjson/document.h",
        "build/native/include/rapidjson/encodedstream.h",
        "build/native/include/rapidjson/encodings.h",
        "build/native/include/rapidjson/error/en.h",
        "build/native/include/rapidjson/error/error.h",
        "build/native/include/rapidjson/filereadstream.h",
        "build/native/include/rapidjson/filewritestream.h",
        "build/native/include/rapidjson/internal/biginteger.h",
        "build/native/include/rapidjson/internal/diyfp.h",
        "build/native/include/rapidjson/internal/dtoa.h",
        "build/native/include/rapidjson/internal/ieee754.h",
        "build/native/include/rapidjson/internal/itoa.h",
        "build/native/include/rapidjson/internal/meta.h",
        "build/native/include/rapidjson/internal/pow10.h",
        "build/native/include/rapidjson/internal/stack.h",
        "build/native/include/rapidjson/internal/strfunc.h",
        "build/native/include/rapidjson/internal/strtod.h",
        "build/native/include/rapidjson/memorybuffer.h",
        "build/native/include/rapidjson/memorystream.h",
        "build/native/include/rapidjson/msinttypes/inttypes.h",
        "build/native/include/rapidjson/msinttypes/stdint.h",
        "build/native/include/rapidjson/prettywriter.h",
        "build/native/include/rapidjson/rapidjson.h",
        "build/native/include/rapidjson/reader.h",
        "build/native/include/rapidjson/stringbuffer.h",
        "build/native/include/rapidjson/writer.h",
        "build/native/rapidjson.targets",
        "build/publisher-info.txt",
        "rapidjson.1.0.2.nupkg.sha512",
        "rapidjson.nuspec"
      ]
    },
```

**Comment by rrelyea** [comment]
Vcxproj files don’t support packagereference.
It may work from command line, but it doesn’t work inside of VS.
Please ask the C++ to add such support, if you miss it.

As such, you likely need to remove them from directory.build.props, or change directory hierarchy so that it doesn’t impact the .vcxprojs

**Comment by rrelyea** [comment]
Pointers to some other customer requests for PackageReference in C++ projects:
(not sure of best one)

-	https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33909292-use-packagereference-in-vcxproj
-	https://developercommunity.visualstudio.com/content/idea/351636/use-packagereference-in-vcxproj.html
-	https://developercommunity.visualstudio.com/content/problem/50373/obtaining-nuget-packages-via-packagereference-does.html

**Comment by heaths** [comment]
I ended up conditioning my `ItemGroup` on a property I set in .vcxproj files that need the old _packages.config_ support. Most work fine with `<PackageReference>`, fully understanding it's not supported (but works well enough for those projects). I'll add my vote. Thanks!
