### ISSUE TITLE
Restore:  investigate no-op restore performance

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8092]

**Comment by zarenner** [comment]
@dtivel @nkolev92 @rrelyea just curious since it's been a while since I've checked in - has there been or is there any work planned for no-op restore perf improvements on large project graphs? Especially when using CentralPackageVersioning (e.g. solution lock file support)?

fyi @boxofyellow

**Comment by rrelyea** [comment]
We believe that some major noop perf improvements will land in 5.5. see https://github.com/nuget/home/issues/8791 

CentralVersionPackageManager is a different effort, also in flight: see https://github.com/nuget/home/issues/8256

**Comment by zarenner** [comment]
Awesome, that's very exciting. Thanks for the update.

**Comment by nkolev92** [comment]
This was a generic placeholder for our investigate. We've done multiple phases of improvements and we'll keep doing so. 

Commandline scenario improvements: https://github.com/NuGet/Home/issues/8791
VS improvements; https://github.com/NuGet/Home/issues/9513
https://github.com/NuGet/Home/issues/9189
