### ISSUE TITLE
Final 5.1.0 insertion and shipping

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8104]
5.1.0.6013 Build
ReleaseId via AzDO: [322942](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=322942)

- [x] Shepherd insertions into VS-16.1.0-preview4-- inserted via the setup/msbuild/nuget joint insertion

- [x] Shepherd insertions into SDK
https://github.com/dotnet/sdk/pull/3217  -- sdk release/2.2.3xx branch
https://github.com/dotnet/sdk/pull/3218  -- sdk release/2.1.7xx branch

- [x] Shepherd insertions into CLI
https://github.com/dotnet/cli/pull/11303   -- cli release/2.2.3xx branch
https://github.com/dotnet/cli/pull/11304   -- cli release/2.1.7xx branch

- [x] Review and polish release notes
- [x] Send PR with release notes to team - https://github.com/NuGet/docs.microsoft.com-nuget/pull/1442
- [x] publish release notes - @karann-msft 
- [x] draft team tweet, etc... - @karann-msft 

- [x] Ship packages- @rrelyea 
- [x] Ship nuget.exe - @loic-sharma & @rrelyea - NuGet.Services.Index/pull/143

Wait a few weeks 

- [x] Bless nuget.exe if feedback after a few weeks is good.

**Comment by nkolev92** [comment]
@heng-liu blessed nuget.exe when we shipped 5.2
