### ISSUE TITLE
Ensure all projects use the same version of Newtonsoft.Json

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8108]
Several `src\NuGet.Client` projects were getting `Newtonsoft.Json` version 10 from transitive NuGet dependencies, but the compiled assemblies are getting assembly references to it. Since we bundle `Newtonsoft.Json.dll` 9 in our VSIX, depending on what workloads and components are installed with Visual Studio, it's possible that no `Newtonsoft.Json` 10 is installed, causing assembly load failures. Visual Studio has binding redirects for versions 6-9, meaning 10 is not redirected.

We should make sure that all of our dlls (and dependencies that we ship) use a consistent version of Newtonsoft.Json and work in a minimal install of VS.

**Comment by nkolev92** [comment]
Once the bugs we fixed for lock files make in production, we can just add lock files for our projects. 

Another option is to add a post-build/post restore step that looks at all the assets file and errors the selected newtonsoft.json version is not 9.0.1.
