### ISSUE TITLE
Error to update jQuery on Package Manager Console with MVC5Application

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#811]
env: 23016.0 D14OOB + NuGet 615 dev

repro steps:
1. create MVC5Application
2. execute below command to uninstall jQuery
Uninstall-Package Microsoft.jQuery.Unobtrusive.Validation
Uninstall-Package jQuery.Validation
Uninstall-Package jQuery
3. install jQuery.Validation on package console "Install-Package jQuery.Validation -Version 1.8"
4. update jQuery on package console "Update-Package jQuery"

Expected results: should update jQuery to latest version
Actual results: get error: Unable to find package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform'. Existing packages must be restored before performing an install or update
![updatejqueryerror](https://cloud.githubusercontent.com/assets/11768961/8229807/cb731c7a-15ec-11e5-95e7-9fc15a25c2d8.PNG)

Note: try to update jQuery to latest on NuGet Package Manager window, works fine

**Comment by danliu** [comment]
This is a duplicate to https://github.com/NuGet/Home/issues/804.
