### ISSUE TITLE
NuGet assembly versions should be consistent

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8113]
After adjusting the Visual Studio installation path (on the first line below) as necessary, execute the following PowerShell script:
```PowerShell
$directory = [System.IO.DirectoryInfo]::new('C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet')

$files = $directory.GetFiles('NuGet.*.dll')

$assemblyVersionsMap = [System.Collections.Generic.SortedDictionary[string, [System.Collections.Hashtable]]]::new()

ForEach ($file In $files)
{
    $assembly = [System.Reflection.Assembly]::LoadFile($file.FullName)
    $assemblyName = [System.Reflection.AssemblyName]::new($assembly.FullName)
    $fileVersionInfo = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($file.FullName)
    $versions = @{
        AssemblyVersion = $assemblyName.Version
        FileVersion = $fileVersionInfo.FileVersion
        ProductVersion = $fileVersionInfo.ProductVersion
    }

    $assemblyVersionsMap.Add($assemblyName.Name, $versions)
}

$assemblyVersionsMap | Format-Table `
    @{ Label = 'Assembly';         Expression = 'Key' }, `
    @{ Label = 'Assembly Version'; Expression = { $_.Value.AssemblyVersion } }, `
    @{ Label = 'File Version';     Expression = { $_.Value.FileVersion } }, `
    @{ Label = 'Product Version';  Expression = { $_.Value.ProductVersion } }
```
Sample output:

Assembly | Assembly Version | File Version | Product Version
--- | --- | --- | ---
NuGet.Build.Tasks | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Commands | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Common | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Configuration | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Console | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Credentials | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.DependencyResolver.Core | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Frameworks | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Indexing | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.LibraryModel | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.PackageManagement | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.PackageManagement.PowerShellCmdlets | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.PackageManagement.UI | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.PackageManagement.VisualStudio | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Packaging | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.ProjectModel | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Protocol | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Resolver | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.SolutionRestoreManager | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Tools | **5.0.0.5917** | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.Versioning | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.VisualStudio | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.VisualStudio.Common | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.VisualStudio.Implementation | 5.0.0.6 | 5.0.0.5917 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68
NuGet.VisualStudio.Interop | 1.0.0.0 | 1.0.0.0 | 5.0.0-rtm.5917+f2696527402305a7d7e51ca2aab1dc1c704d7c68

NuGet.VisualStudio.Interop.dll's assembly version should always be 1.0.0.0; however, I'm not aware of any good reason why all other assemblies don't have the same assembly version of 5.0.0.6.

**Comment by StingyJack** [comment]
> I'm not aware of any good reason why all other assemblies don't have the same assembly version of 5.0.0.6.

Why wouldn't the assemblies have 5.0.0.5917 as the version? What's the difference in usage between them?
