### ISSUE TITLE
Don't lowercase projects with custom assembly names in packages lock file

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8114]
See the broken test. 
RestoreNetCore_PackagesLockFile_CustomAssemblyName_DoesNotBreakLockedMode

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2652493&view=ms.vss-test-web.test-result-details
Also see: 
RestoreNetCore_PackagesLockFile_LowercaseProjectNameSolutionRestore

//cc @zivkan @rrelyea

**Comment by rrelyea** [comment]
@zivkan - can you please improve the title - i think the work morphed and the title should be improved.
