### ISSUE TITLE
The ‘ProjectName’ column lost in PMC after resetting window layout

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8117]
[658342](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/658342)

Repro steps: 

1. Launch VS and create a C# Blank App (Universal Windows).

2. Open “Package Manager Console”.

3. Drag the PMC window splitter to right.

4. Type ‘Get-Package -Updates’ in PMC.

5. Click “window->Reset Window Layouts”.

6. Open “Package Manager Console” and type ‘Get-Package -Updates’ in PMC again.

7. Drag the PMC window splitter to right and observe the package information.

Expected:

The ‘ProjectName’ column should be displayed in step 7 such as step 4.

Actual:

The ‘ProjectName’ column lost in step 7 as attachment picture. 

Notes:

1. The issue repro on D16.0stg 28002.3000 (default NuGet Client Release-4.8.0-preview3/4.8.0.5278).

2. The issue repro on D15.8 28002.3000 + NuGet Client Release-4.8.0-RTM\4.8.0.5374.

**Comment by SueSu01** [comment]
Verified this issue on VS Main\34807.21 + NuGet Client Dev\6.11.0.9, it's fixed, so closed it, thanks!
