### ISSUE TITLE
Get-package -updates returns no versions and update-package fails with referencing a newer version error

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#812]
Repros with latest Dev 615.

Repro step:

1.File->New Project->Visual C#->Windows->Windows 8->Hub App(Windows 8.1 Universal).
2.Check Application Insights checkbox.
3.After the project has been created, build.
4.Open Manage NuGet Packages… UI.
5.Open Package Manager Console , type Get-Package -updates, and select one , type update-package Microsoft.ApplicationInsights package, meet the error.

![picture](https://cloud.githubusercontent.com/assets/1087852/8237286/0532f114-15a3-11e5-87ff-7aab69ccd188.png)

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/c4ccf58e465dbfeae272494c7f3444dd38ca46a7
