### ISSUE TITLE
When will nuget.com server support SemVer 2.0.0 ?

### ISSUE THREAD

**Issue by lovettchris** [NuGet/Home#8121]
I see the [nice long spec](https://github.com/NuGet/Home/wiki/SemVer2-support-for-nuget.org-%28server-side%29) but that was two years ago.  When is it going to happen?

**Comment by nkolev92** [comment]
nuget.org supports Semver2, see the tracking issue https://github.com/NuGet/Home/issues/1359. 

The feature has been live for about ~2 years now. 
Clients newer than 4.3 & VS 2017 update 3 also support it.

**Comment by lovettchris** [comment]
Huh, weird, I just tried to publish a package with the version "8.0.0-1" and the "nuget push" failed saying the version was invalid.

**Comment by nkolev92** [comment]
Unfortunately you are hitting https://github.com/NuGet/NuGetGallery/issues/6948. 

Feel free to comment on the issue there.

**Comment by lovettchris** [comment]
Yes, I see the comment " /// which do not support a `.` in release labels, or release labels starting with numeric characters. ".  I'll try "8.0.0-a1" instead.
