### ISSUE TITLE
How do I determine what frameworks a package supports?

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#8126]
I thought I'd try to build some index of what frameworks each package on nuget.org supports.

Intellectually, it seems obvious to me that the definition of "supports" is actually a very deep question. For example, this question could be expanded by specifying:

1. Are you targeting packages.config? Are you targeting `PackageReference`?
1. What assets are you interesting in? For example, maybe want compile-time and run-time .NET APIs available in `lib`. Or perhaps you only want MSBuild targets. _wait wut_
1. _**HARD MODE:**_ What if the top level package is support be a dependency is now? For example, you have a meta-package with dependencies not under a target framework. For example, [Microsoft.AspNet.WebApi 5.2.3](https://www.nuget.org/packages/Microsoft.AspNet.WebApi/5.2.3).

... but how do I even try?

I tried a couple of approaches to determine this.

### Easy 

For example, I tried using [`PackageReaderBase.GetSupportedFrameworks`](https://github.com/NuGet/NuGet.Client/blob/932accfb173379c0ad01e6f3d47130e64dc383fa/src/NuGet.Core/NuGet.Packaging/PackageReaderBase.cs#L364). However this doesn't seems to take `ref/*` into account which `PackageReference` restore flow does ([source](https://github.com/NuGet/NuGet.Client/blob/932accfb173379c0ad01e6f3d47130e64dc383fa/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L436)).

For example, Microsoft.CSharp 4.3.0 has `netstandard1.3` in `lib` but `netstandard1.0` in `ref` meaning if `ref` is considered then `netstandard1.0`, `netstandard1.1` and `netstandard1.2` are actually supported.

### Okay, okay

I also tried using the code in `CompatibilityChecker` which suggests the frameworks that a package supports ([source](https://github.com/NuGet/NuGet.Client/blob/1bb100cd4df524de75356ccfd146041eb95c2d59/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L252-L294)) to the user while erroring out, but this code seems very different than the compatibility checker itself ([source](https://github.com/NuGet/NuGet.Client/blob/1bb100cd4df524de75356ccfd146041eb95c2d59/src/NuGet.Core/NuGet.Commands/RestoreCommand/CompatibilityChecker.cs#L332-L340)).

### can haz results

I then tried enumerating all frameworks known to NuGet and tried simulating each as a package dependency of a fake project in a restore. This gave me a lot of different answers than the first two attempts.

Perhaps the notion of what frameworks a package supports is a fallacy entirely due to point 2 above. Suppose a package is used for MSBuild goo by one person but expected to have `lib/*` (.NET APIs to use) by another person.

### Conclusion

To avoid further descent into depression, let's try to summarize what I am asking concisely.

**Is there a simple way to determine what NuGet frameworks a package supports? Let's assume I:**

1. Only care about `PackageReference` (absolves point 1 above)
1. Just want the package to install and don't care about any particular asset (absolves point 2 above)
1. Ignore any compatibility issues of transitive dependencies (absolves point 3 above)

`GetSupportedFrameworks` seems to not cut it due to ignoring `ref` assets. Although arguably without considering transitive references `ref` (i.e. point 3) doesn't make much sense since you need a runtime assembly eventually... right?

If there is not a simple API, is there a document describing the rules so I can implement it myself without creating [some frankenstein](https://github.com/joelverhagen/NuGetCompat/blob/54d3d78b11fe4b5565c2d0bbf68eaa3d543dc9ec/NuGetCompat/SupportedFrameworksProvider.cs#L181) of hacked NuGet restore code of questionable correctness?

**Comment by rrelyea** [comment]
@nkolev92  - perhaps we schedule some time for this?
Minimally, we should chat through this.

**Comment by nkolev92** [comment]
Yeah we should schedule some time to understand both what we want to and what we can achieve.

**Comment by joelverhagen** [comment]
For NuGet.org, we've implemented this an [`AssetFrameworkHelper`](https://github.com/NuGet/NuGetGallery/blob/64e797cca8628ce62eca9f6972abeb4915d611e4/src/NuGetGallery.Core/Services/AssetFrameworkHelper.cs#L16) to find the frameworks explicitly supported by assets and [`PackageFrameworkCompatibilityFactory`](https://github.com/NuGet/NuGetGallery/blob/64e797cca8628ce62eca9f6972abeb4915d611e4/src/NuGetGallery.Core/Frameworks/PackageFrameworkCompatibilityFactory.cs) to expend out the full list of supported frameworks (based on framework support mappings).

This code is tuned for display and filtering purposes on NuGet.org and does not exactly match the full package compatibility notion that exists in NuGet restore. 

If anyone else is reading this, you can try out the NuGet/NuGetGallery code but note that it has some known shortcomings (e.g. https://github.com/NuGet/NuGetGallery/issues/9337) and it not wrapped up in a re-usable package. The code is really an implementation detail of NuGet.org today.

**Comment by nkolev92** [comment]
I think given the lack of upvotes and all the info provided here, I don't think we need spend more time here. 

Closing.
