### ISSUE TITLE
Nuget 5.0.2 fails to find msbuild assemblies in debian stretch

### ISSUE THREAD

**Issue by byfron** [NuGet/Home#8137]
Hi,

I'm trying to package a csharp project in Linux using nuget+mono. Specifically the OS is a debian stretch: Linux dc1e45079844 4.9.0-3-amd64 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

It's been working fine with NuGet 4.6.2, but since updating to 5.0.2 when running `nuget restore project.sln` I get the following error:

MSBuild auto-detection: using msbuild version '' from '/usr/bin'.
Error parsing solution file at /project_folder/project.sln: Could not load file or assembly '/usr/bin/Microsoft.Build.dll' or one of its dependencies
NuGet.CommandLine.CommandLineException: Error parsing solution file at /project_folder/project.sln: Could not load file or assembly '/usr/bin/Microsoft.Build.dll' or one of its dependencies

It seems that with the new version the Msbuild auto-detection is failing to find the correct paths, given that the Microsoft.Build.dll  is located in /usr/lib/mono/xbuild/14.0/bin/ but nuget seems to be looking for it in /usr/bin. 

Thanks

**Comment by zivkan** [comment]
@byfron Could you let us know more about your environment and what changed?

What version of mono are you using?
Did you upgrade mono at the same time as changing versions of nuget.exe?
are you using the nuget.exe bundled with mono, or did you download from nuget.org?
Do you have a `msbuild` on your path, and if so what's its path?
Can you please try nuget.exe 4.9.4 to see if it's a regression from the previous version, or if there was a change some time after 4.6?

As a workaround, you can try using the `-MSBuildPath` argument to get nuget.exe 5.0 to work, but we'd like to understand why the selection is failing.

**Comment by rrelyea** [comment]
@byfron  - can you please follow up on @zivkan's questions from May 16th?

**Comment by rrelyea** [comment]
@byfon - no response. closing. please let us know info we asked for, if still an issue.
