### ISSUE TITLE
Insertion of 5.2.0-preview2.6020

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8138]
VS:
 * [x] https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/181368

* .NET Core 2.1
* [x] https://github.com/dotnet/cli/pull/11365
* [x] https://github.com/dotnet/sdk/pull/3242

* .NET Core 2.2
* [x] https://github.com/dotnet/cli/pull/11364
* [x] https://github.com/dotnet/sdk/pull/3241

* .NET Core 3.0
* [x] https://github.com/dotnet/cli/pull/11366
* [x] https://github.com/dotnet/sdk/pull/3243
* [x] https://github.com/dotnet/toolset/pull/1009

**Comment by wli3** [comment]
All insertion is failed in SDK.

**Comment by rrelyea** [comment]
@dominoFire will take point helping to drive SDK insertions

**Comment by dominoFire** [comment]
In all sdk PRs, two tests are failing: https://github.com/dotnet/sdk/blob/e915ce180c39a79e2ff1597d1a3fb3c9565c4c27/src/Tests/Microsoft.NET.ToolPack.Tests/GivenThatWeWantToPackAToolProjectWithGeneratePackageOnBuild.cs#L50

Test 1: `It_builds_successfully()`

```
Microsoft (R) Build Engine version 16.2.0-preview.19264.2+c3389964c for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
  Library -> C:\repos\github\dotnet\sdk\artifacts\Debug\tmp\It_builds_suc---81F3C59C\Library\bin\Debug\netcoreapp2.0\Library.dll
  consoledemo -> C:\repos\github\dotnet\sdk\artifacts\Debug\tmp\It_builds_suc---81F3C59C\App\bin\Debug\netcoreapp2.1\consoledemo.dll
  consoledemo -> C:\repos\github\dotnet\sdk\artifacts\Debug\tmp\It_builds_suc---81F3C59C\App\bin\Debug\netcoreapp2.1\consoledemo.dll
C:\repos\github\dotnet\sdk\artifacts\Debug\bin\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(337,5): error MSB4006: There is a circular dependency in the target dependency graph involving target "_WalkEachTargetPerFramework". [C:\repos\github\dotnet\sdk\artifacts\Debug\tmp\It_builds_suc---81F3C59C\App\consoledemo.csproj]
```

Test 2: `It_builds_and_result_contains_dependencies_dll()`

```
The file is not a valid nupkg. File path: C:\repos\github\dotnet\sdk\artifacts\Debug\tmp\It_builds_and---5F6DD855\App\bin\Debug\consoledemo.1.0.0.nupkg
```

**Comment by rrelyea** [comment]
marking as engineering improvement - (will also hide from release notes)
