### ISSUE TITLE
Get NuGet-Client source build clean

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8139]
- [x] get prebuilt clean - https://github.com/dotnet/source-build/issues/890
(coordinate the changes for microsoft.build.sdk.resolver with Rainer and Nick from msbuild team - ask if they want you to fix and have them review, or would they prefer to own this change)

- [ ] get patch clean - https://github.com/dotnet/source-build/tree/release/3.0/patches/nuget-client

Moved "get patch clean" to #8321

**Comment by nkolev92** [comment]
@dominoFire 

I think this work is done, can you please close it if so?
