### ISSUE TITLE
Support NuGet Search Tab effort

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8140]
One of our peer teams in Visual Studio is enhancing the search experience (ctrl+q) for many things. They plan to build a NuGet tab. Please help as necessary.

Minimally, we'll likely need to review their approach and provide advice.
We may need to provide new functionality...or work with them to build it.

@karann-msft has a design doc

**Comment by nkolev92** [comment]
This is a rolling task. Any active tasks initiated by this effort will be linked here.

**Comment by nkolev92** [comment]
This has been completed. 

There might be additional tasks that go beyond this, by my part so far in it is done.
