### ISSUE TITLE
Implement Nuget Package which contains UI pages

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8145]
@PrabhujiMudragalla commented on [Fri May 03 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1430)

Hi Team, 

I am planning to create a UI Package which can be used across all my projects, it should support the following type of applications:
1. MVC Web Applications
2. MVC Web API 
3. Web Forms
4. WPF Applications 
5. .NET Core Web API 
6. .NET Core MVC 
Can you please suggest what type of application should I prefer to achieve the above frameworks?

**Comment by karann-msft** [comment]
I would recommend taking a look at [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard). A package targeting netstandard can be consumed across .NET implementations, using this same set of APIs.

**Comment by rrelyea** [comment]
Given that 5 of those frameworks are owned by the ASP.NET team, I would ask about 1, 2, 3, 5, and 6 to the ASP.NET team in one of their repos.
Once you have those answers, figuring out WPF fits in, will be easier.
