### ISSUE TITLE
Mono nuGet init hangs several minutes after having successfully installed packages

### ISSUE THREAD

**Issue by blackholegalaxy** [NuGet/Home#8150]
## Details about Problem

NuGet product used: **nuget.exe** with **mono**

NuGet version: **NuGet Version: 5.0.2.5988**

OS version (i.e. win10 v1607 (14393.321)): **alpine linux 3.9** (also tested on strech and ubuntu xenial)

Dockerfile in which command in ran:

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9

RUN apk add --no-cache mono --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing && \
    apk add --no-cache --virtual=.build-dependencies ca-certificates curl && \
    cert-sync /etc/ssl/certs/ca-certificates.crt && \
    curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe && \
    apk del .build-dependencies && \
    apk add --no-cache nodejs~=10.14.2 yarn~=1.12.3 git ca-certificates openssh-client

COPY aliases.sh /etc/profile.d/aliases.sh
CMD ["/bin/sh", "-l"]
```

Useful information: **It runs on a CI/CD pipeline under gitlab-ci with no possible user input**

## Detailed repro steps so we can see the same problem

1. Command used: `mono /usr/local/bin/nuget.exe init /srv/build/local_packages /srv/localnugetrepo/packages`

2. nuget installs in milliseconds the packages (log with detailed verbosity):
```
NuGet Version: 5.0.2.5988
Acquiring lock for the installation of sync-model 1.0.0-latest
Acquired lock for the installation of sync-model 1.0.0-latest
Installing sync-model 1.0.0-latest.
Completed installation of sync-model 1.0.0-latest
Successfully added package '/srv/build/local_packages/sync-model.1.0.0-latest.nupkg' to feed /srv/localnugetrepo/packages'.
Acquiring lock for the installation of batch-model 1.0.0-latest
Acquired lock for the installation of batch-model 1.0.0-latest
Installing batch-model 1.0.0-latest.
Completed installation of batch-model 1.0.0-latest
Successfully added package '/srv/build/local_packages/batch-model.1.0.0-latest.nupkg' to feed '/srv/localnugetrepo/packages'.
 --- HANG HERE DURING ABOUT 2-3 MIN ---
```

Then it hangs for several minutes, doing nothing. Then stopping without non-0 exit code. So everything works properly but it hangs with no reasons during several times. 

It slows down our pipeline a lot. Machine running the process is a 6 core 64gb ram with NVMe.

**Comment by rrelyea** [comment]
What changed in your environment?
Just nuget.exe version?
Or mono version?
or other?
Do you see the same problem with NuGet.exe 4.9.4?

**Comment by blackholegalaxy** [comment]
nothing changed it's a new setup

**Comment by zivkan** [comment]
this could be related to package signature cert revocation checking. see this comment: https://github.com/NuGet/Home/issues/8127#issuecomment-492567914

**Comment by blackholegalaxy** [comment]
I just tested, as stated in comment to set an environment variable `NUGET_CERT_REVOCATION_MODE ` to `offline`. It doesn't change anything in our case. Our CI has access to internet so it would have been surprising. I don't have any timeout message.

I just noticed the fact we init one or multiple packages doesn't change the hang time.

 Nuget is only used here to source `nupkg` files built locally to a virtual local nuget repository (meant to be restored with `dotnet restore` later, which works properly and blazing fast). Only the `nuget init` is taking way too long.

**Comment by blackholegalaxy** [comment]
@rrelyea on some jobs it took about 10 min after latest `Successfully added package` for our job to continue. Running again the same job sometimes stop hanging after 30 sec (no cache on our runners). 

The number of added packages with `nuget.exe init` doesn't seem to impact neither in a positive nor a negative way. Hang time is random, but we encountered no less than 30 sec.

Please note the nupkg we build are only models, and weight about 50-100ko each.

We don't have any information about what's been done during this wait time AFTER all packages successfully added. Our log verbosity is at its maximum.

we tested with 4.9.4 and it triggers the same problem

Mono version: **5.18.0.268-r0**

**Comment by nkolev92** [comment]
@blackholegalaxy 

Can you try 4.8 as well? 

There were some IO changes that we made in 4.9/5.0, I just want to confirm that those did not make the mono scenario worse. 

That same fix, drastically improved the IO times on .NET Framework and .NET Core.

**Comment by nkolev92** [comment]
Did you get a chance to try 4.8? Can you also try latest NuGet.exe? 

We'd need a some sort of a repro to continue our investigation here.
perfview logs would also be helpful. 

Download and extract PerfView.exe. https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md#shortcut-to-download-the-latest-perfviewexe

**Comment by nkolev92** [comment]
At this point we don't have enough information to continue investigating this issue. Closing as not repro.
