### ISSUE TITLE
Download a package with its dependencies into a folder

### ISSUE THREAD

**Issue by lostmsu** [NuGet/Home#8152]
## Details about Problem

Can't find a way to download a package with its dependencies into a specified folder for offline use.

NuGet product used: dotnet.exe

NuGet version: 5.1.0.0

dotnet.exe --version (if appropriate): 3.0.100-preview5-011568

Worked before? If so, with which NuGet version: 3.5.0.1996
`nuget.exe install <PACKAGENAME> -OutputDirectory <OUTPUTDIR>`

## Detailed repro steps so we can see the same problem
`dotnet add package <PACKAGE NAME> --package-directory .` does not have an option to download package and its dependencies without passing a project file.

### Verbose Logs

`dotnet add package Gradient --package-directory .`

> Could not find any project in `C:\Users\USERNAME\AppData\Local\Temp\NuInstall\`.

**Comment by nkolev92** [comment]
Thanks of creating this issue. 

This is a duplicate of https://github.com/NuGet/Home/issues/6750. 

The problem with downloading a package and it's "dependencies" is that it is effectively restore.
