### ISSUE TITLE
solution based cache for packagereference

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/Home#8153]
I have targets on my packages that modify my assemblies before build in relation to project references. This worked well with the packages.config as the the default cache  is project based. However with packagereferences my consumer may patch the same assemblies from difference solutions as the cache now is global. 

Is there a workaround to this problem?

**Comment by apobekiaris** [comment]
what it would be perfect may be an attribute that my consumer can set and use a local cache instead

**Comment by nkolev92** [comment]
What you call "cache' is really an installation directory for the packages. For the most part it's meant to be user-wide. 

However, you can redirect as it as you see fit https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders. 
You can add them to the ignore list of your scm and passing have the global packages folder be in the repo root. 
The way to ensure the correct config is used is to put it next to the solution file and make sure you have clear tags in the lists like [here](https://github.com/NuGet/NuGet.Client/blob/dev/NuGet.Config) to avoid impact from user specific configs. 

Now note that modifying packages after they have been downloaded is not a recommended practice. 
NuGet provides integrity and in cases with nuget.org authenticity guarantees but by modifying packages after that fact you are messing with those guarantees. 

Are these "modifications" always the same?
You can consider modifying the package once and putting it on a private feed (be it a local file share or a full fledged service like AzureDevOps.

**Comment by nkolev92** [comment]
Closing per the above comment.
