### ISSUE TITLE
NuGet restoration of MsBuild SDKs is extremely buggy

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [NuGet/Home#8157]
I'm creating a custom MsBuild SDK and when I use it in my project, Visual Studio (2017 & 2019) has the following issues happening intermittently until everything eventually works:
- VS hangs.
- The project using the custom SDK will be unloaded. Reloading it will cause a hang.
- A strange window also appears running `CredentialProvider.Microsoft.exe`:
![msbuild-sdk-vs-issue](https://user-images.githubusercontent.com/9839187/58295510-709cf380-7d84-11e9-8f93-794d63a8335d.PNG)

Eventually, after restarting VS a couple times, everything works.

Azure DevOps's dotnet restore doesn't work at all: https://developercommunity.visualstudio.com/content/problem/581357/dotnetcorecli.html

I'm getting issues with running dotnet locally as well but it partially (if not entirely) due to https://github.com/NuGet/Home/issues/6045

The same NuGet package can be restored without problem if I add it to my csproj as a `<PackageReference />`.

## Details about Problem

NuGet product used:
- dotnet.exe
- Azure DevOps's DotNetCoreCLI@2 restore with NuGet.config
- VS UI

NuGet version: Whatever dotnet 2.2.102 uses

dotnet.exe --version: 2.2.102

VS version: 2017 (15) & 2019 (16)

OS version: win10 1803 17134.407 & Azure DevOps

## Detailed repro steps so we can see the same problem

1. Create an MsBuild SDK project, generate a NuGet package, and push it to a stream.

2. Use the `<Project Sdk="...">` attribute to reference your MsBuild SDK and specify the version of the Sdk via `global.json`. Alternatively, add the MsBuild SDK in [any of the ways specified in the documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019).

3. Watch everything burn.

### Verbose Logs

None.

### Sample Project

TODO

**Comment by rrelyea** [comment]
Sorry for the problems.

https://github.com/microsoft/msbuild/issues/4025 covers these problems with the current design and implementation. Will close this issue in favor of that one.

Although this code is in the nuget repo, it belongs to the msbuild team. We included it as part of our build to make it always totally in sync with nuget when inserted into VS.
