### ISSUE TITLE
UI does not respect package restore enabled setting

### ISSUE THREAD

**Issue by zhili1208** [NuGet/Home#816]
Repro Steps:

1. disable package restore in Option setting
2. Open UI, install moq
3. delete packages folder
4. install jquery in UI

expect: Jquery is installed but moq is not restored.
actual: jquery is installed, moq is also restored.

root cause is in UIActionEngine, it does not check packageRestoreConsent before do restore.

**Comment by yishaigalatzer** [comment]
That setting is only for restoring on build. If you are on the UI I think this is the right behavior. We can debate further

**Comment by zhili1208** [comment]
@yishaigalatzer  For this case,  Powershell respect enabled setting during install, if this is right behavior, we might need to change powershell behavior to keep consistency. Also 2.8.6, the UI respect enabled setting during install.
