### ISSUE TITLE
'--locked-mode' restore flag not respected if lock file is empty or malformed

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8160]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

dotnet.exe --version (if appropriate): 2.2.105

## Automated repro
You can download [lockedModeNotRespectedRepro.zip](https://github.com/NuGet/Home/files/3218983/lockedModeNotRespectedRepro.zip) and run repro.bat for an automated repro.

## Detailed manual repro steps

1. Create an empty or invalid packages.lock.json file next to a .csproj

2. Run `dotnet restore --use-lock-file --locked-mode`

**Expected**
The process should fail with an error saying the lock file is incorrect. It should not update the lock file since --locked-mode was set.

**Actual**
The process updates the file. It also returns a 0 exit code

**Comment by nkolev92** [comment]
I can repro this. 
The fix should be rather basic. 

Attempted a quick fix, will finish it up if the tests pass. 
dev-nkolev92-fix8160

**Comment by nkolev92** [comment]
I have a fix in code review for this.
