### ISSUE TITLE
nuget does not support passing properties during restore

### ISSUE THREAD

**Issue by jmecosta** [NuGet/Home#8161]
Hi,

we need this in our projects
```
    <TargetFrameworks>net472</TargetFrameworks>
    <TargetFrameworks Condition="'$(EnableDotNetStandard2)' == 'true'">net472;netstandard2.0</TargetFrameworks>
```

the reason is that i want to start using .netstandard and cant ask everyone to install tooling in their machines. so for now im only doing this in build farm and have regression builds there only. Later once everything is sorted out net472 is removed and netstandard will be the only one used.

Problem is that during restore i cant pass msbuild properties to nuget . and nuget restores only for net472 and later the compilation fails. 

can you support this?  i know i can patch the file before hand, but then i need to remenber all files i need to patch and they can be hundreds of project files in need of patching

thanks

**Comment by rrelyea** [comment]
What technique are you using to run restore that you need to solve passing properties for? (Nuget cli, dotnet cli, msbuild.exe, etc)

**Comment by jmecosta** [comment]
I run Nuget.exe

**Comment by nkolev92** [comment]
That's already supported with an environment variable. 

https://docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables

> NUGET_RESTORE_MSBUILD_ARGS

Can you try that?

**Comment by jmecosta** [comment]
@rrelyea  thanks, missed that from doc. Works as expected.

**Comment by nkolev92** [comment]
Thanks for following up!
