### ISSUE TITLE
There is an error occurred on the second project’s PM UI when closing the first project’s csproj file after migrating the installed package into PR format

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8163]
## Details about Problem
NuGet version: NuGet Client Dev\5.2.0.6028
VS Version: D16.2stg\28925.13
OS: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1. Launch VS and create a solution with two C# Console App (.NET Framework) projects.
2. Open PM UI of each project and install a package with “packages.config” format into the first project.
3. Right-click the “References” node of the first project in Solution Explorer window and click “Migrate packages.config to PackageReference…”
4. Right-click the first project in Solution Explorer window and click “Unload Project” after the migrating.
5. Right-click the first project in Solution Explorer window and click “Edit xxxxx.csproj”.
6. Close the opened csproj file and click the “Browse” tab in the second project’s PM UI.
## Expected
There is no error occurred on the “Browse” tab in the second project’s PM UI.
## Actual
There is an error occurred on the “Browse” tab in the second project’s PM UI as below screenshot.
![Error occurred](https://user-images.githubusercontent.com/20632625/58414481-0fd82880-80ae-11e9-9313-3d2952661eb2.png)
## Note
It is not a regression issue since it did repro on D15.9 28307.158 (Nuget Client 4.9.3.5777).

**Comment by nkolev92** [comment]
Somehow the project context is lost in the PM UI. 
I can repro this.

**Comment by SueSu01** [comment]
Verified this issue on VS Main\34807.21 + NuGet Client Dev\6.11.0.9, it's fixed, so closed it, thanks!
