### ISSUE TITLE
Nuget安装：Microsoft.AspNetCore.Mvc

### ISSUE THREAD

**Issue by HuaPing2017** [NuGet/Home#8173]
错误	NU1107	Microsoft.AspNetCore.Antiforgery 中检测到版本冲突。直接安装/引用 Microsoft.AspNetCore.Antiforgery 2.2.0 到项目 WebNETApp 可解决此问题。 
 WebNETApp -> Microsoft.AspNetCore.Mvc 2.2.0 -> Microsoft.AspNetCore.Mvc.ViewFeatures 2.2.0 -> Microsoft.AspNetCore.Antiforgery (>= 2.2.0) 
 WebNETApp -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.AspNetCore.Antiforgery (>= 2.1.1 && < 2.2.0).	

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Thanks for filling this issue. 

From what I can tell there is no bug in the client here. 

Microsoft.AspNetCore.Mvc and Microsoft.AspNetCore.App should always match their versions. 

You should not be manually chnaging the versions of these packages but rather upgrade the SDK that brings them. 

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-2.2#update-aspnet-core
