### ISSUE TITLE
Automatic package restore with EF Core

### ISSUE THREAD

**Issue by jp2images** [NuGet/Home#8182]
[SamuraiApp.zip](https://github.com/NuGet/Home/files/3243776/SamuraiApp.zip)
Please read the following information before posting the issue.

## Details about Problem
Sample files don't build because the EF Core version is incompatible? (Tried the MS Docs suggestions)

**Error messages:**
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is s:\.nuget\packages\Microsoft.EntityFrameworkCore.Design.2.2.0\build\net461\Microsoft.EntityFrameworkCore.Design.props.	SamuraiApp.Data	D:\Downloads\entity-framework-core-2-getting-started\04\demos\M4 Demos\2.2\After\SamuraiApp\SamuraiApp.Data\SamuraiApp.Data.csproj	184	

**AND A WARNING MESSAGE:**
Warning		Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit https://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: System.Linq, System.Linq.Expressions, System.Reflection, System.Runtime, System.Runtime.Extensions	SamuraiApp.Data		0	

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Visual Studio UI

NuGet version (x.x.x.xxx):
NuGet Package Manager 5.1.0

dotnet.exe --version (if appropriate):
v4.7.03190
VS version (if appropriate):
VS2019 v16.1.1

OS version (i.e. win10 v1607 (14393.321)):
Win10 Pro v1809 (17763.503)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Build the solution and fails to auto-update many EF Core packages.

2.

...

### Verbose Logs

1>------ Rebuild All started: Project: SamuraiApp.Domain, Configuration: Debug Any CPU ------
1>  SamuraiApp.Domain -> D:\Downloads\entity-framework-core-2-getting-started\04\
1>  demos\M4 Demos\2.2\After\SamuraiApp\SamuraiApp.Domain\bin\Debug\SamuraiApp.Do
1>  main.dll
2>------ Rebuild All started: Project: Tests, Configuration: Debug Any CPU ------
2>D:\Downloads\entity-framework-core-2-getting-started\04\demos\M4 Demos\2.2\Afte
2>r\SamuraiApp\Tests\Tests.csproj(63,5): error : This project references NuGet pa
2>ckage(s) that are missing on this computer. Use NuGet Package Restore to downlo
2>ad them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=3221
2>05. The missing file is s:\.nuget\packages\MSTest.TestAdapter.1.4.0\build\net45
2>\MSTest.TestAdapter.props.
3>------ Rebuild All started: Project: SamuraiApp.Data, Configuration: Debug Any CPU ------
3>D:\Downloads\entity-framework-core-2-getting-started\04\demos\M4 Demos\2.2\Afte
3>r\SamuraiApp\SamuraiApp.Data\SamuraiApp.Data.csproj(184,5): error : This projec
3>t references NuGet package(s) that are missing on this computer. Use NuGet Pack
3>age Restore to download them.  For more information, see http://go.microsoft.co
3>m/fwlink/?LinkID=322105. The missing file is s:\.nuget\packages\Microsoft.Entit
3>yFrameworkCore.Design.2.2.0\build\net461\Microsoft.EntityFrameworkCore.Design.p
3>rops.
4>------ Rebuild All started: Project: SomeUI, Configuration: Debug Any CPU ------
4>D:\Downloads\entity-framework-core-2-getting-started\04\demos\M4 Demos\2.2\Afte
4>r\SamuraiApp\SomeUI\SomeUI.csproj(181,5): error : This project references NuGet
4> package(s) that are missing on this computer. Use NuGet Package Restore to dow
4>nload them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=3
4>22105. The missing file is s:\.nuget\packages\Microsoft.EntityFrameworkCore.Des
4>ign.2.2.0\build\net461\Microsoft.EntityFrameworkCore.Design.props.
========== Rebuild All: 1 succeeded, 3 failed, 0 skipped ==========

### Sample Project

Very helpful if you can zip a project and paste into this issue!
Included. I get a similar problem when using a Manning Publication sample projects for learning to use EF Core.

**Comment by nkolev92** [comment]
@jp2images 

Seems like you manually modified the hint path in the SamuraiApp.Data project, is that correct? 

When that happens, NuGet can no longer detect the changes that it made to the project file, so it can't reinstall correctly.

**Comment by jp2images** [comment]
Hmmm. I don't think I did anything except download the source for Julie Lerman on PluralSight. I see the exact same issue with the source from JohnPSmith and the book EFCore In Action. https://github.com/JonPSmith/EfCoreInAction. Is the hint path easily fixable?

**Comment by nkolev92** [comment]
They need to be manually amended to match what NuGet did in the first place. 
So it's doable with the right context. 

Consider changing `s:\.nuget\` to `..\packages' in SamuraiApp.Data.csproj

That's at least one obvious issue.

**Comment by jp2images** [comment]
So... Interesting event. I have an EFCore project that I created from scratch in VS2017 but have since upgraded to VS2019. A coworker pulled the code from the repo with VS2019 and experienced similar reference issues on his machine that I am complaining about with the Samurai sample app.
The project I created was new, getting the EFCore stuff from NuGet and I used the Package Manager for Solution to get the EFCore stuff.

Anyway, my coworker tried to remove the Microsoft.EntityFrameworkCore reference via NuGet and after several seconds we got an error that it couldn't be removed. (no surprise there) What was surprising was that he no longer got the reference errors. Everything was great. I tried to recreate this with samurai.

Maybe this is an EFCore bug?

**Comment by nkolev92** [comment]
I can't claim anything either way. 

Packages.config is fragile that way. 
Any manual modifications will confuse the tooling. 

That's why PackageReference does not hardcode references any more. 

Regardless, did your specific issue get resolved? Did fixing the hint paths help? 
I would like to close this as not as bug if so. 

Thanks.

**Comment by jp2images** [comment]
Sure thanks.
