### ISSUE TITLE
nuget 4.5.1.4879 - restore created new folder

### ISSUE THREAD

**Issue by yury-fedorov** [NuGet/Home#8194]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (4.5.1.4879):

OS version ( Windows 7 Professional v 6.1 (Build 7601: Service Pack 1)):

## Detailed repro steps so we can see the same problem

1. delete from "<user folder>\.nuget\packages\<package>\" a folder named "New folder" 
2. nuget restore from solution folder of the project
3. in output the warning:
WARNING: The folder 'C:\Users\<sensitive-info>\.nuget\packages\<sensitive-info>.protobuf\New folder' contains an invalid version.

### Verbose Logs

NuGet Version: 4.5.1.4879
Restoring NuGet packages for solution D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector.sln.
MSBuild auto-detection: using msbuild version '16.1.76.45076' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\bin\msbuild.exe "C:\Users\<sensitive-info>\AppData\Local\Temp\NuGetScratch\gc23iek4.5jd.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\<sensitive-info>\AppData\Local\Temp\NuGetScratch\uekzmwhr.3iy.nugetrestore.targets" /p:RestoreTaskAssemblyFile="D:\bin\chocolatey\lib\NuGet.CommandLine\tools\NuGet.exe" /p:RestoreSolutionDirectory="D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector" /p:SolutionDir="D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector"

Running restore with 8 concurrent jobs.
Reading project file D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\<sensitive-info>.<sensitive-info>ConnectorLib.csproj.
Reading project file D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\<sensitive-info>.<sensitive-info>ConnectorLib.csproj.
Reading project file D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorTest\<sensitive-info>.<sensitive-info>ConnectorTest.csproj.
Reading project file D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector.csproj.
The restore inputs for '<sensitive-info>.<sensitive-info>ConnectorTest' have not changed. No further actions are required to complete the restore.
The restore inputs for '<sensitive-info>.<sensitive-info>Connector' have not changed. No further actions are required to complete the restore.
The restore inputs for '<sensitive-info>.<sensitive-info>ConnectorLib' have not changed. No further actions are required to complete the restore.
The restore inputs for '<sensitive-info>.<sensitive-info>ConnectorLib' have not changed. No further actions are required to complete the restore.
Committing restore...
Committing restore...
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\obj\project.assets.json
Assets file has not changed. Skipping assets file writing. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorTest\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\obj\<sensitive-info>.<sensitive-info>ConnectorLib.csproj.nuget.cache
No-Op restore. The cache will not be updated. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorTest\obj\<sensitive-info>.<sensitive-info>ConnectorTest.csproj.nuget.cache
Assets file has not changed. Skipping assets file writing. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector\obj\<sensitive-info>.<sensitive-info>Connector.csproj.nuget.cache
Restore completed in 42.26 ms for D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\<sensitive-info>.<sensitive-info>ConnectorLib.csproj.
Restore completed in 41.94 ms for D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorTest\<sensitive-info>.<sensitive-info>ConnectorTest.csproj.
Restore completed in 42.23 ms for D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector.csproj.
WARNING: The folder 'C:\Users\<sensitive-info>\.nuget\packages\<sensitive-info>.protobuf\New folder' contains an invalid version.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\obj\project.assets.json
No-Op restore. The cache will not be updated. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\obj\<sensitive-info>.<sensitive-info>Lib.csproj.nuget.cache
Restore completed in 48.3 ms for D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\<sensitive-info>.<sensitive-info>ConnectorLib.csproj.

NuGet Config files used:
    D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\NuGet.Config
    C:\Users\<sensitive-info>\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    \\<sensitive-info>\<sensitive-info>\<sensitive-info>\<sensitive-info>\NugetFeed
    http://<sensitive-info>/artifactory/api/nuget/virtual-nuget/
    https://api.nuget.org/v3/index.json
    https://<sensitive-info>/artifactory/api/nuget/nuget-cache
    https://<sensitive-info>/artifactory/api/nuget/nuget-releases-local

**Comment by dominoFire** [comment]
Hi @yury-fedorov 

Hope all is well.

Do this occurs in the most recent version of `nuget.exe` 5.0.2 ?

Can you try the following in your current NuGet version and see if the warning message is still showing ?

1. Delete your local cache with `nuget.exe locals all -clear`
2. Run `nuget.exe restore Connector.sln -Verbosity detailed` in your solution folder

It looks like when you delete the folder from the `.nuget\packages<package>`, there's a cached version of the folder in the NuGet cache.

**Comment by yury-fedorov** [comment]
Hi @dominoFire 

Thank you for the immediate feedback and readiness to support. I was not so quick to reply, sorry for that.

I tried with 5.0.2 what you have suggested:

1. nuget locals all -clear
2. nuget restore <sensitive-info>Connector.sln  -Verbosity detailed

It worked:

```
All packages and projects are compatible with .NETStandard,Version=v2.0.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.Service\<sensitive-info>.Service\obj\project.assets.json
Writing cache file to disk. Path: D:\<sensitive-info>\Workspace\<sensitive-info>.Service\<sensitive-info>.Service\obj\<sensitive-info>.Service.csproj.nuget.cache
Restore completed in 11.48 sec for D:\<sensitive-info>\Workspace\<sensitive-info>.Service\<sensitive-info>.Service\<sensitive-info>.Service.csproj.

NuGet Config files used:
    D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\NuGet.Config
    C:\Users\<sensitive-info>\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    <sensitive-info>\NugetFeed
    http://<sensitive-info>/artifactory/api/nuget/virtual-nuget/
    https://api.nuget.org/v3/index.json
    https://<sensitive-info>/artifactory/api/nuget/nuget-cache
    https://<sensitive-info>/artifactory/api/nuget/nuget-releases-local

Installed:
    8 package(s) to D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorLib\<sensitive-info>.<sensitive-info>ConnectorLib.csproj
    13 package(s) to D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>ConnectorTest\<sensitive-info>.<sensitive-info>ConnectorTest.csproj
    11 package(s) to D:\<sensitive-info>\Workspace\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector\<sensitive-info>.<sensitive-info>Connector.csproj
    40 package(s) to D:\<sensitive-info>\Workspace\<sensitive-info>.Service\<sensitive-info>.Service\<sensitive-info>.Service.csproj
```

Thank you for the support! 

Best regards
