### ISSUE TITLE
Generate report on TFM compatibility for most popular nuget.org packages

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8199]
Analyse packages with low install/restore success rate with packages with high success rate, to come up with suggestions for pack validation rules to help package authors create packages with fewer issues.

**Comment by nkolev92** [comment]
@zivkan Is this still relevant?

Can you close if not?

**Comment by zivkan** [comment]
It was an idea for an intern project, so while still interesting, we have no plans to actually work on it.
