### ISSUE TITLE
Search occasionally falls back to api-v3search-1, which does not seem to work

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#820]
Repro steps:
1. start nuget package manager dialog

Occasionally hitting this error

![search](https://cloud.githubusercontent.com/assets/1087852/8243205/c304be5e-15c9-11e5-857e-02a9b212c88d.PNG)

**Comment by danliu** [comment]
Hitting retry worked. But that search query should work, as 

"resources": [
  {
   "@id": "https://api-v3search-0.nuget.org/query",
   "@type": "SearchQueryService"
  },
  {
   "@id": "https://api-v3search-1.nuget.org/query",
   "@type": "SearchQueryService"
  },

**Comment by yishaigalatzer** [comment]
@joyhui this looks like a server issue, can someone take a look?

**Comment by joyhui** [comment]
I did a quick stress test on current api-v3search-1, and didn't find problem. It may be the known application pool recycle issue, or VM restart issue. Communicated with Dan, she didn't find this issue again these days. Let's reopen this issue if it can be repro.
