### ISSUE TITLE
APIs to get TFMs supported by package

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8200]
Talk to stakeholders to find what information is most useful to them.

Implement required APIs

APIs to implement (update after talking to stakeholders)
- [ ] IEnumerable<NuGetFramework> GetPackageFrameworks(package)

**Comment by nkolev92** [comment]
Related: 
https://github.com/NuGet/Home/issues/8126

Note that the answer can be different for PackageReference and packages.config.
