### ISSUE TITLE
Pack context menu should be hidden if the project is not packable

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8202]
Copied from Internal Bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/857426

## Details about Problem

Visual Studio context menu option "Pack" does not disable when the feature is disabled.

NuGet version (x.x.x.xxx): All

## Detailed repro steps so we can see the same problem

1. Create 2.2\3.0 ASP.NET Core project

2. Right click the project 

Expected: 

It should not show "Pack" as an option when 'IsPackable' property is set to false. 

Actual:

Pack options is available for all core projects irrespective of whether the project is packable or not?

**Comment by rrelyea** [comment]
@donnie-msft  - can you link to the project system bug on this so people can check on current status (link to github issue or just number of ADO issue)

**Comment by donnie-msft** [comment]
Original bug is in the first line of this Issue's description.

Looked into IsPackable flag and one usage of that is with `ProjectCapability.Pack` in Project System's code:  [CSharpProjectDesignerPageProvider.cs](http://index/?query=CSharpProjectDesignerPageProvider.cs&rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=ProjectSystem%5CVS%5CProperties%5CCSharp%5CCSharpProjectDesignerPageProvider.cs&rightSymbol=ahstqnchs22u)

The Pack menu is added through a Project System VSCT file: [Menus.vsct](http://index/?query=Microsoft.VisualStudio.ProjectSystem.Managed.VS%20menus.vsct&rightProject=Microsoft.VisualStudio.ProjectSystem.Managed.VS&file=Menus.vsct&rightSymbol=ncjq0st60ioc)

Given these files are owned by the Project System team, we transferred this Issue to them.
