### ISSUE TITLE
[Test Failure] Suggest not to show the “License” line under “Description” section when the package’s license is empty

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8206]
## Details about Problem
NuGet version: NuGet Client Dev\5.2.0.6040
VS Version: D16.2stg\29005.118
OS: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1. Launch VS and create a C++ UWP.
2. Open PM UI of the project and search package “SampleCPlusPlusDevicePackage” in “Browse” tab.
3. Select the package on the left and click the “View License” link on the right.
## Expected
The opened link should not be empty. Suggest not to show the license line under “Description” section when the package’s license is not configured by user.
## Actual
The opened link is empty as below screenshot.
![EmptyLincense](https://user-images.githubusercontent.com/20632625/59022065-ac08e900-887f-11e9-8013-40a57a0a0da8.png)
## Note
1.Same suggestion for empty “Project URL”, avoid showing the link like: http://PROJECT_URL_HERE_OR_DELETE_THIS_LINE on PM UI.
2.It is not a regression issue since it did repro on D15.9 28307.158 (Nuget Client 4.9.3.5777).

**Comment by donnie-msft** [comment]
Deprecation may be relevant https://github.com/NuGet/Home/issues/7531

**Comment by donnie-msft** [comment]
Creating a package without changing the license already shows warnings to the user, and this behavior is by design.

**Comment by rrelyea** [comment]
@donnie-msft  - We should make sure that our tooling (nuget pack or dotnet pack...or nuget spec and then nuget pack doesn't create that fake URL. if it does, we should at least warn in pack.

**Comment by donnie-msft** [comment]
@rrelyea, I already discussed with @karann-msft  and our tooling does create the fake URL and we do already show warnings to the user.
