### ISSUE TITLE
Add "skip-if-exists" flag to the CLI

### ISSUE THREAD

**Issue by Pzixel** [NuGet/Home#8207]
I'm not sure if it's the right place to ask the question, sorry for inconvinience if any.

My question is about pushing a package that may already exist in the gallery. Currently I have a command:
```ps
dotnet nuget push myproject/*.nupkg -k $NUGETAPIKEY -s https://api.nuget.org/v3/index.json
```

which works fine except when I rerun the CI server and it tries to push the package once again. Then I get

> Response status code does not indicate success: 409 (A package with ID 'My.Project.Name' and version '0.1.20' already exists and cannot be modified.).

It would be nice if I could write something like:

```ps
dotnet nuget push myproject/*.nupkg -k $NUGETAPIKEY -s https://api.nuget.org/v3/index.json --skip-if-exists
```

To make sure it returns 200 if package already exists.

---

P.S. Is there any common workaround to perform that task?

**Comment by rrelyea** [comment]
@donnie-msft recently delivered this for nuget.exe 5.1 and is working to add it to dotnet.exe very soon.

**Comment by Pzixel** [comment]
Cool. Can you link a PR if you don't mind?

**Comment by donnie-msft** [comment]
nuget.exe is done: https://github.com/NuGet/NuGet.Client/pull/2802
dotnet.exe is in process: https://github.com/NuGet/Home/issues/8100
