### ISSUE TITLE
Wrong behavior related to Show preview window and Do not show this again checkboxes

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#821]
Repro steps:
1. Have "Show preview window" checked and Do not show this again unchecked
2. Select a package, click install. When preview window is up, uncheck the Do not show this again
3. Now the "Show preview window" will be unchecked.
4. Select a package, click Install

Expected: 
preview window is not popping up, since "Show preview window" on the main UI is unchecked

Actual:
preview window is still showing up, with "Do not show this again" checked automatically. Note in step 2, this checkbox was unchecked. We should not change the state of the checkbox ourselves.

**Comment by feiling** [comment]
We'll remove the "Do not show this again" checkbox. Instead, we'll make the "Show preview window" checkbox setting per user instead of per window.

**Comment by yishaigalatzer** [comment]
@feiling  was this done in 3.3?

**Comment by rrelyea** [comment]
Confirmed by code inspection that 3.4 codebase has both of those things done:
- remove the "Do not show this again" checkbox. 
- make the "Show preview window" checkbox setting per user instead of per window.

**Comment by rrelyea** [comment]
In validation, Zhi found that this issue still repros. Reactivating.
