### ISSUE TITLE
Question: Does the order of package entries inside packages.config matter?

### ISSUE THREAD

**Issue by The-Futurist** [NuGet/Home#8216]
If someone were to reorder the list of packages in the packages.config XML does this have any impact on how the project rebuilds or anything?

I want to order the packages alphabetically in two related but different applications so we can see the (few) differences more easily when we look at the files.

**Comment by donnie-msft** [comment]
There's no significant impact beyond the order in which the packages are restored. Either way, they should all get restored. By default, packages and dependencies are added alphabetically, so likely yours were manually modified, anyway.
