### ISSUE TITLE
Plugins cannot be located when assemblies are not located next to Visual Studio

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#8220]
## Details about Problem

NuGet product used nuget.exe

NuGet version (x.x.x.xxx): 5.2

## Detailed repro steps so we can see the same problem

1. Set the MSBuild property `RestoreTaskAssemblyFile` to the full path to a local copy of `nuget.exe`
```
<PropertyGroup>
  <RestoreTaskAssemblyFile>$(MSBuildThisFileDirectory)build\nuget.exe</RestoreTaskAssemblyFile>
</PropertyGroup>
```

2. Use a feed that requires authentication

3. Restore packages

Plug-ins like the credential provider cannot be found.  I'm assuming this is because its looking next to itself which is not next to Visual Studio.  I think it should look for environment variables like `VSINSTALLDIR` so that the credential providers that come with Visual Studio can be found.  This logic could be added to [PluginDiscoveryUtility](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs).

**Comment by nkolev92** [comment]
Can you explain in more detail what your scenario is?

Everytime a nuget.exe restore is run, it discovers MSBuild and builds a relative path for the VS installed plugins through: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/PluginDiscoveryUtility.cs#L13

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/Command.cs#L195
So it should already be covered.

**Comment by jeffkl** [comment]
I've created a repro: https://github.com/jeffkl/nuget-repro-8220

I know its a little wierd to use `nuget.exe` as the task assembly but it comes in handy when users are facing issues with NuGet that are fixed but not yet released.  They can check in the `nuget.exe` with the fix and use that version during restore for command-line or hosted build scenarios.

I haven't had a chance to debug it, my best guess was that the `PluginDiscoveryUtility` just doesn't take into account this scenario so its unable to find the plug-ins.

**Comment by nkolev92** [comment]
Oh I see. You are calling the tasks that NuGet.exe carries. 

Yeah this scenario was not considered at all. I'm not sure we'd want to support it either way.
VSINSTALLDIR is not always set, and you can always use the environment variable to specify the plugins. 
Also in some rare case VSINSTALLDIR could be different from the NuGet assemblies' VS installation. 

@rrelyea @dtivel thoughts?

**Comment by jeffkl** [comment]
I completely agree its a weird scenario but its something that we need to have working.  Any time there's a bug fix that hasn't been released, it'll allow us to put in place a temporary workaround until there's an official release.

**Comment by nkolev92** [comment]
NuGet inserts frequently into VS. Why not take a dependency on the internal VS release channel?

**Comment by jeffkl** [comment]
I need a way to make it work in hosted and local builds.  I cannot ask everyone who hits the issue to install a Preview version.  I need to make a targeted fix for a repository and have it work for everyone.

**Comment by nkolev92** [comment]
> I need to make a targeted fix for a repository and have it work for everyone.

How do you deal with bugs in other parts of the tooling then?

**Comment by dtivel** [comment]
How about updating the `NUGET_PLUGIN_PATHS` environment variable?  That seems like an easy, flexible solution, and it's already available.

**Comment by jeffkl** [comment]
> How do you deal with bugs in other parts of the tooling then?

It depends on the component.  In some cases there are bugs in features we're attempting to adopt so we delay adoption.  In other cases the build logic is delivered as a NuGet package so we'll use privately built, non-released packages.  This is the first time we've hit an issue with NuGet and needed to work around it in this way.

> How about updating the `NUGET_PLUGIN_PATHS` environment variable?

For local builds, we do not require any special environment.  Setting of an environment variable would require a checked in batch file rather than being able to simply clone and build.  We can set the environment variable in hosted builds since we own the process end-to-end.  

Is there a larger bug here that `nuget.exe` will not be able to locate the plug-ins installed with Visual Studio?  `nuget.exe` restores call `msbuild.exe` to build the dependency graph but the restore is not.  So wouldn't restores fail in that scenario?

There's also the fact that `nuget.exe` does what I'm doing:

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs#L257

```C#
// Set path to nuget.exe or the build task
AddProperty(args, "RestoreTaskAssemblyFile", nugetExePath);
```

I really think that the plug-in discovery mechanism should look for the plug-ins next to the discovered MSBuild instance so that there's maximum parity between `msbuild.exe /t:Restore` and `nuget.exe restore`.

**Comment by nkolev92** [comment]
It's the entry point that makes the decision about the discovery of the internal plugins. 

So the restore task has one logic, the nuget.exe restore command has other logic. 
The restore task assumes it's in the commonextensions directory NuGet installs into. NuGet.exe restore uses the VS instance of the msbuild version it discovers.  So the parity exists, and works exactly as designed. 

The idea here is you are trying to work around our servicing story and our servicing story is "update your VS".

**Comment by jeffkl** [comment]
> The idea here is you are trying to work around our servicing story

I disagree.  I'm using stock nuget in what I think is a stock way.  I'm setting a stock property to indicate that I want it to use my version of nuget.exe.  nuget.exe does not ship with Visual Studio and its the only way to restore `packages.config`.  And its an easy way to temporarily use unreleased bits or bits that haven't yet been posted.  

Are you saying that this won't get fixed?  I'll need to write up some documentation explaining to people why so many builds are failing and that there's nothing we can do until the next release of Visual Studio.    Telling them all to install preview versions won't scale and I don't know of any other workaround.  Given all of the options, it seems like making this work is the best one for the user.  Unless there are any other suggestions that I'm not aware of?

**Comment by nkolev92** [comment]
`NUGET_PLUGIN_PATHS` is the big hammer workaround for these tricky situations. 

I'm not claiming either way whether this would get changed or not, just trying to clearly understand the scenario. 

There are concerns with this workaround too. It doesn't fix any Visual Studio issues.

**Comment by jeffkl** [comment]
I don't think this is worth fixing
