### ISSUE TITLE
Package Manager Console:  becomes unusable if used in an empty solution

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8226]
Package Manger Console (PMC) becomes permanently disabled (for that Visual Studio instance) if it is used in an empty solution.  Visual Studio must be restarted for PMC to become usable again.

**Repro steps:**
1.  Launch Visual Studio.
2.  Open PMC.
3.  In Visual Studio open a file (e.g.:  a text file or a PowerShell script) but not a solution or project.
4.  In PMC execute:  `get-help NuGet`

**Results:**
1.  Visual Studio dialog displays an error dialog:
```
---------------------------
Microsoft Visual Studio
---------------------------
Solution is not opened or not saved. Please ensure you have an open and saved solution.
---------------------------
OK   
---------------------------
```
2.  PMC never stops exits "executing" mode of the last command.  Thus, PMC will not accept any new commands.

**Observations:**
1.  If PMC was open and a topmost tool window when Visual Studio was last closed, then Visual Studio will reopened and reactivate PMC automatically during step 1 above, and step 2 will be unnecessary.
2.  If steps 2 and 3 above are reversed, then PMC reports the error inside PMC (instead of a dialog), but PMC is still disabled for that Visual Studio instance.  Step 4 will be unnecessary (and blocked).

**Comment by zivkan** [comment]
no longer reproducible
