### ISSUE TITLE
Expected errors should not be logged to the activity log.

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#823]
ShowError in NuGetUI is logging InvalidOperationExceptions to the activity log. The majority of these exceptions will be expected and should not be written out as if they were a crash. Users will be confused by this and think that incorrectly authored packages are NuGet crashes.

Ex: when a package is not compatible with the target framework 
An InvalidOperationExceptions is thrown and will be put into the log.

**Comment by yishaigalatzer** [comment]
Will deal with this as a cleanup task

**Comment by emgarten** [comment]
There has been no feedback on this and in some scenarios non-error info is written to the activity log on purpose. Closing this.
