### ISSUE TITLE
Open VS without any project creation, there is no nuget.org feed.

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8231]
## Details about Problem
VSTS Bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917743
The latest daily build of VS doesn’t initialize a source pointing to nuget.org

Figure out all the paths when we add nuget.org to the config files and when this is broken.

## Detailed repro steps so we can see the same problem

INSTALL STEPS
(copied from linked VSTS  Bug)

1. Clean machine: Win 7 x64 ENU
2. Install Dev16.2 (pre-release-build) VSC(.NET Core + Desktop workload)
Install  Dev16.2 Preview3 (pre-release-build)(d16.2-29012.301)VSC:https://vsdrop.corp.microsoft.com/file/v1/Products/DevDiv/VS/512656d7244eb30e91babe6b04d6eb4978d77082/27d6e958-99c1-df12-6393-187eae69b5a8%3bchannels/internal/Preview/bootstrappers/fixed/Community/vs_Community.exe
Select . Net Core + Desktop  workload 
Check 1.x Development tools under IC
2.2 development tools checked

REPRO STEPS

1. Open VS 

2. Continue without code.
3. Then click Tools> Nuget Package Manager> Package Manager Setting. click Package Sources. There are no package sources there.

Note: After create a new project, the package source pops up.
ACTUAL
![image.png](https://images.zenhubusercontent.com/5cbdfd8a4b83d30843e9e841/417ef594-6d2a-4213-872e-1a43e713434a)
EXPECTED:
![image.png](https://images.zenhubusercontent.com/5cbdfd8a4b83d30843e9e841/21c784f8-5978-49a4-a095-4979a5d2947e)

**Comment by rrelyea** [comment]
@zivkan - u fixed last week, right? Please dupe, close, etc...

**Comment by nkolev92** [comment]
Fixed within 5.2 (the revert of both fixes, addressed the issue).
