### ISSUE TITLE
NuGet pack is including everything in my project directory

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#8237]
My environment is as follows:

NuGet version: 4.9.3.5777
Visual Studio 2017
Windows 7 Pro x64

I am running *NuGet* during my build process because I have to. This is in a project that has a dependency against ``xunit.core``, which does not want to be built via conventional nor contemporary build steps. So I am finding that I must furnish my own ``nuspec`` to workaround that issue.

Anyway, the assets I want to include are simply these:

```Xml
<files>
  <file src="my.assembly.*" target="lib\netstandard1.1" />
</files>
```

The assembly targets ``netstandard1.1``, and I want to include the *DLL*, *XML*, and possibly also the *PDB*.

I am literally running ``NuGet`` via a *Build Target*,

```Xml
<Exec Command="nuget pack &quot;$(MSBuildProjectName).nuspec&quot; -OutputDirectory &quot;bin\$(Configuration)&quot; -Properties Configuration=$(Configuration)"/>
```

That's it. Nothing fancy about that.

However, *NuGet* is trying to package ***ALL*** the files from my project. It is completely ignoring the ``nuspec`` file.

**Comment by mwpowellhtx** [comment]
I'm figuring it out, this seems to be better behaved. However, I'm not sure why the project is failing to package in the first place as a natural build output. The only thing I can fathom is that the ``xunit.core`` dependency prohibits that for whatever reason. However, I can promise you, I *want* it packaged; that is by design.

```Xml
<PropertyGroup>
  <!-- TODO: TBD: we might even want to preface this, or caller might want to specify the commands, etc, or we allow for some arguments, etc, to better customize. -->
  <!-- Build out the command here. -->
  <_CommandText>nuget pack</_CommandText>
  <_CommandText>$(_CommandText) &quot;$(MSBuildProjectName).csproj&quot;</_CommandText>
  <_CommandText>$(_CommandText) -OutputDirectory &quot;bin\$(Configuration)&quot;</_CommandText>
  <_CommandText>$(_CommandText) -Version $(PackageVersion)</_CommandText>
  <_CommandText>$(_CommandText) -Properties &quot;Configuration=$(Configuration);tags=$(_NuGetTags)&quot;</_CommandText>
</PropertyGroup>

<Exec Command="$(_CommandText)" />
```

**Comment by heng-liu** [comment]
Thanks for reporting this issue!
I tried to repro but failed (packed without xunit.core related dlls successfully)
Can you please provide the following info so that we can repro? Thanks!
1.Are you using PackageReference or packages.config format?
2.Detailed repro steps.

**Comment by mwpowellhtx** [comment]
I sorted it out, but to be honest I'm not sure what the `solution´ actually was. I think it had something to do with correct comprehension of my licensing file(s), but I cannot say exactly. Closing for now, but it might be something to keep an eye on, i.e. why would MSBuild and/or ``nuget pack`` want to include everything in a package?

**Comment by heng-liu** [comment]
If it's packages.config format, and you use .nuspec to pack, it should get the files you specified in `<files>`  only. You may refer to this document: https://docs.microsoft.com/en-us/nuget/reference/nuspec#including-assembly-files

Usually, the path after "src="  is relative to the .nuspec file. So I'm not sure if "my.assembly.*" is the correct path.
And if you want to exclude some files and include all the other files from the same path, you may try the following:
`<files>
<file src="bin\Release\*.*" exclude="xunit.*" />
</files>`


If it's PackageReference format, you can use a msbuild target named pack, https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target
In this case, using .nuspec to pack is not necessary. 

Pls tell us if you find anything afterwards. Thanks!

**Comment by mwpowellhtx** [comment]
@heng-liu Only partially correct. And, no, I do not use package.config any more, at all, unless I have to, like I am working on a legacy project. However, most projects I work on these days are targeting at least ``netstandard`` at some version, usually ``2.0``, but sometimes ``1.1``, ``1.3``, etc, or ``netcoreapp``. To work around the ``LICENSE`` file issue, for instance, one has to do some work to use ``.nuspec`` after all, especially in projects that depend on ``xunit.core``, for instance, which cannot be packaged on its own by MSBuild contemporary targets.
