### ISSUE TITLE
source-build: Remove Newtonsoft.Json prebuilt from Nuget.Client

### ISSUE THREAD

**Issue by adaggarwal** [NuGet/Home#8249]
CLI Prebuilts |   |  
-- | -- | --
Package | Version | Status
Newtonsoft.Json | 9.0.1 | Using non-source-built Version

**Comment by adaggarwal** [comment]
This tag needs to be changed to \<NewtonsoftJsonVersion\>
https://github.com/NuGet/NuGet.Client/blob/686dd6b060639a0fb401eceb4c3a4029c1482023/build/config.props#L39

Then update that tag instead of the hardcoded-versions/deprecated-tag for newtonsoft versions. Example:
https://github.com/NuGet/NuGet.Client/blob/686dd6b060639a0fb401eceb4c3a4029c1482023/build/sign.proj#L26

This is in reference to [890](https://github.com/dotnet/source-build/issues/890)

**Comment by rrelyea** [comment]
@dominoFire  - please coordinate with @zivkan on options in this space until we move away from newtonsoft.

**Comment by dominoFire** [comment]
@adaggarwal Hi. What can I do is to grab the value from $(NewtonsoftJsonVersion) and assign it to `<NewtonsoftJsonVersionCore/>` in case the $(NewtonsoftJsonVersion) property is defined. Does that work for source-build?

**Comment by adaggarwal** [comment]
Hi @dominoFire, I think that it should be good for source-build. Thank you!
