### ISSUE TITLE
NuGet on VS 2015 RC crashes on almost any package install

### ISSUE THREAD

**Issue by mrchief** [NuGet/Home#825]
Both GUI and PM seem to crash with almost any package now. The only workaround is to open VS 2013 and install packages, save the project and resume in VS 2015.

This time its AutoMapper v3.3.1. Before that it was SimpleInjector. 

Is there any update to this? This is really annoying.

![image](https://cloud.githubusercontent.com/assets/781818/8246384/de1d1334-160b-11e5-9f3b-749364bc4d41.png)

**Comment by emgarten** [comment]
@mrchief you can get the latest update here: http://nuget.codeplex.com/releases/view/615507

**Comment by mrchief** [comment]
Thanks! Will give this a try!

**Comment by yishaigalatzer** [comment]
@mrchief please re-open if you still see the issues after the update. We can verify with newer versions we have built after this.

Please include a full repro project repro steps and crash callstack or dump

**Comment by mrchief** [comment]
Will do, thanks!
