### ISSUE TITLE
Define and add link behavior for deprecation alternate package in PMUI

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#8252]
Need to define and add the behavior for clicking the hyperlink pointing to the alternate package in deprecation PMUI.

Consider emitting telemetry on "deprecated view" + "deprecation expand/collapse" and "alternative package click". Or some subset.

**Comment by dominoFire** [comment]
This was fixed in this issue: https://github.com/NuGet/Home/issues/10996

Telemetry part is tracked here: https://github.com/NuGet/NuGet.Client/pull/4246
