### ISSUE TITLE
Validate dependency groups in nuspec

### ISSUE THREAD

**Issue by JarahSi** [NuGet/Home#8254]
Validate the dependencies found in the `lib` or `ref` folder in the nuspec

[Spec](https://github.com/NuGet/Engineering/blob/josi-pkgValidation/Client.Specs/PackageValidation/DependenciesInNuspecMatchLibRefFolder.md)

[PR](https://github.com/NuGet/NuGet.Client/pull/2936)

**Comment by saucecontrol** [comment]
I'm getting this warning now for Tools-only packages.  I'd suggest not including this warning if `IsTool` is true.
