### ISSUE TITLE
[Centrally managing NuGet packages and versions] Prototype (Visual Studio Integration)

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#8257]
Create a prototype that will support design and features decisions.

| Index | Experience | Notes |
| --- | --- | --- |
| 1 | Integrate msbuild SDK solution to nuget | The integration worked with integration to nuget.targets. However this allows only managing centrally the package version without any VS or/and other tooling integration |
| 2 | Evaluate usage of a different item type(different than PackageReference) for marking the central package reference | Completed - The different item type will work with new interface for IVsTargetFrameworkInfo. However upon more discussions the best solution is still to use the current PackageReference. Prototype: https://github.com/NuGet/NuGet.Client/commit/c3e8ababa22d2001a2b0349dedca470e22dd2c7d |
| 3 | Evaluate individual projects version overwrite as Item attribute | Completed - This is similar with the MsBuild SDK  |
| 4 | Evaluate individual projects version overwrite as grouping (similar with Paket) | Completed - the grouping need to be activated as in the attached Grouping.zip  | 
[Grouping.zip](https://github.com/NuGet/Home/files/3586100/Grouping.zip)

**Comment by cristinamanum** [comment]
Visual Studio integration is still under discussions.

**Comment by cristinamanum** [comment]
Keep this open until new meeting with Project System

**Comment by japj** [comment]
hello, is there any insight in when this is expected to land in VisualStudio?

we are currently using the CentralPackageVersioning MSBuild Sdk and are very interested in being able to manage from the VS UI and having support for transitive dependencies

**Comment by cristinamanum** [comment]
> hello, is there any insight in when this is expected to land in VisualStudio?
> 
> we are currently using the CentralPackageVersioning MSBuild Sdk and are very interested in being able to manage from the VS UI and having support for transitive dependencies

The feature spec is [here](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions). It contains the Visual Studio proposed updates. The experience may be updated until ship.

**Comment by cristinamanum** [comment]
Learning about IVS interfaces completed. Dev Design doc in review.
