### ISSUE TITLE
Conditional package references and Locked Mode

### ISSUE THREAD

**Issue by jessehouwing** [NuGet/Home#8258]
Looking for guidance here…
Say you have a solution that contains .NET core projects and that reference NuGet packages using <packagereference> in the project files. Say that these <packagereferences> are made conditional using the existing MsBuild constructs such as `<choose><when>`, `<packagereference condition=””>` or optional includes of targets files that contain the package reference…

Say I have such a solution…
https://github.com/tfsaggregator/tfsaggregator

Now if I want to create a packages.lock.json, I could use `dotnet build --use-lock-file`, but that will create a single lock file, not conditional on the build platform+configuration. Now when I try to restore, it fails. Cause each configuration pulls in a different set of nuget packages. And of course only on set can match the lock file.

Is there a way to set the naming pattern of the lock file somehow? Say `packages.lock-configuration-platform.json`?! 

Is this included in the spec for nuget/dotnet? I can’t find this case in the docs so far.

Given that MsBuild supports conditional nuget references, I suppose that the package-lock feature should support it to in a fashion.

**Comment by rrelyea** [comment]
`NuGetLockFilePath` can be set to different values for different sets of restores.

See documentation for that property here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#lock-file-extensibility

**Comment by rrelyea** [comment]
@jessehouwing said the following in a side email: 
Thanks! Exactly what I was after. I’d been looking at the targets files for NuGet and could’t decipher the thing.

I’m going to try adding a macro expansion to the directory.build.targets to generate a project specific lock file that includes the tfs version in our case.

**Comment by jessehouwing** [comment]
@rrelyea is there a way to also rename the `project.assets.json` similarly? Right now it's not created in a Configuration folder.

![image](https://user-images.githubusercontent.com/4173387/73654066-01093300-468b-11ea-9a1f-7cad58551a6f.png)

**Update**: Found it: 

```
    <RestoreOutputPath>$(IntermediateOutputPath)</RestoreOutputPath>
    <ProjectAssetsFile>$(RestoreOutputPath)\project.assets.json</ProjectAssetsFile>
```
