### ISSUE TITLE
Investigate migration from Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8259]
Investigate current usage of Newtonsoft.Json to be able to better estimate effort of migrating to System.Text.Json

In particular, look for public APIs that accept or return Newtonsoft.Json types and therefore we can't remove without breaking APIs.

**Comment by zivkan** [comment]
There are only 8 projects in the repo, excluding tests, which have files that contain `using Newtonsoft`. 

Project|Files|Comments
--|--|-- 
NuGet.Tools|1|No public APIs. 
Microsoft.Build.NuGetSdkResolver|1|No public APIs. 
NuGet.Build.Tools|10|Only unnecessary usings, which Roslyn interestingly didn't recognise as unnecessary. 
NuGet.Credentials|1|No public APIs. 
NuGet.PackageManagement|2|Public APIs in a single class `JsonConfigUtility`, which is only used in the same assembly and therefore never needed to be made public. 
NuGet.Packaging|4|Public APIs in the classes `JsonObjectReader` and `JsonObjectWriter`, which are used by other assemblies. 
NuGet.ProjectModel|11|Public APIs in the classes `DependencyGraphSpec`, `FileFormatException`, `IncludeExcludeFiles`, `JsonPackageSpecReader`, `JTokenExtensions`. `DependencyGraphSpec`. At least one class throws `JsonReaderException`. 
NuGet.Protocol|77|More details below. 

`NuGet.Protocol` exposes `Newtonsoft.Json` types in public APIs in several ways. 
* There are 9 converters that are public, despite only being used within the same assembly. 
* 3 classes in the `models` directory use attributes for serialisation. 
* 35 files in the `plugins/messages` directory use attributes for serialisation, and 3 use JObject as public property types 
* 4 classes in the `resources` directory expose JObject in public APIs.

For most of the public exposures of Newtosoft.Json types, we can support both Newtosoft.Json and System.Text.Json at the same time to minimise breaking changes. In some cases it would mean a low-performance adapter, in other cases it would mean duplicated code that would not be used by NuGet itself. However, there are a small number of files that we can't change in a compatible way. This would prevent us from finishing the migration to System.Text.Json until the next major version of NuGet.

**Comment by zivkan** [comment]
There is a [Guide to Porting from Newtonsoft.Json to System.Text.Json](https://github.com/dotnet/corefx/blob/61024c30b966ee63c357a491370a2daf94c4c42f/src/System.Text.Json/porting_guide/README.md). I used the permalink in case it moves or disappears in the future, but check for an updated version if working on the migration in the future.

Below are some issues discovered during investigation. They are not about public APIs, but rather more generally how NuGet uses Newtonsoft.Json.

* Using JObjects for incremental building of objects for serialization

In at least one place, NuGet creates output by creating a `JObject`, adding some objects to it, then calling `ToString`. The objects added to this JObject are also JObjects and may be returned from methods in other assemblies. This entire approach needs to be reconsidered. The most direct approach would be to use JsonWriter instead, but that just exchanges one leaky abstraction with another. Creating a class and using `JsonSerializer.Write` may be a better option.

* JObject as extensibility

In NuGet.Protocol, some of the model classes have JObject properties that expose the JSON file, or part of it. I can only assume it's to allow NuGet sources to return custom data, not defined in the NuGet protocol, thereby extending the NuGet protocol and our model classes provides them a way to read that response. Note it only exists for a small number of model classes.

While JsonElement is the closest equivalent to JObject in System.Text.Json, there are some fundamental differences to how it works. I'm not sure it's appropriate to put a `JsonElement` as a public property for random access. I'm not sure it's valid for a `JsonElement` to exist without its `JsonDocument`, but `JsonDocument` is `IDisposable`, so it would change the semantics of our model classes if we started making some `IDisposable`. Plus it would still be a leaky abstraction which would be a problem for users of our packages that don't use System.Text.Json.

Although it would be low performance, perhaps just putting the contents of the json on the model as a string would be best.

* TextReader

I saw at least one class that reads a JSON file by accepting a TextReader as a parameter, so tests could simply use something similar to
```c#
var json = "{...}";
using (var reader = StringReader(json))
{
   target.Method(reader);
}
```

At the time of writing, System.Text.Json only has APIs to read/parse strings and streams (but only if the contents are UTF-8, I believe). An easy solution is to simply use `TextReader.ReadToEnd()` and then use the string with System.Text.Json. But in production (so, not a test using StringReader), if the string is large, this can have a performance impact, particularly if the string is large enough to go into the Large Object Heap.

While it would make tests a little more complex, we could change the APIs to use Stream instead of TextReader.

* Compatibility

System.Text.Json was designed to be high-performance UTF-8, and appears to only support UTF-8. Therefore there's a risk that if any NuGet feed is returning other encodings that are automatically detected by TextReader, these feeds would break if we switch.

Additionally, System.Text.Json strictly follows the ECMA standard (with the exception of allowing opt-in ignore of javascript comments). This means that object keys must be quoted and unquoted key names cause an exception. Therefore any misguided attempts of improving performance by removing key name quoting will cause failures if we switch. For example `{"a":"b"}` is valid JSON, whereas `{a:"b"}` is not.

**Comment by zivkan** [comment]
When using `System.Text.Json` on a `net472` project, the following assemblies are copied to the output folder:
```text
System.Buffers.dll
System.Memory.dll
System.Numerics.Vectors.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Text.Json.dll
System.Threading.Tasks.Extensions.dll
System.ValueTuple.dll
```

Since System.Text.Json (and possibly some of the other assemblies) are still in heavy development, there's a concern that there could be assembly load failures when different assemblies depend on different versions given that NuGet is inserted into MSBuild and the .NET SDK.

We've agreed not to proceed until after .NET Core 3.0 is GA.

**Comment by 304NotModified** [comment]
FYI, the current JObject approach seems to make things unnecessary slow (and complex), so it would be in terms of performance already nice to remove that. See https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/804

**Comment by 304NotModified** [comment]
> We've agreed not to proceed until after .NET Core 3.0 is GA.

I see .net core 3 is now go live. From 
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0-preview-8/

> NET Core 3.0 Preview 8 is supported by Microsoft and can be used in production

**Comment by loic-sharma** [comment]
When we do this work, we should consider this thread: https://github.com/NuGet/Home/issues/8478#issuecomment-524918747

**Comment by zivkan** [comment]
Closing this issue because:

* The task was to do an investigation, not an implementation, which was done
* Recent, and currently ongoing, perf work includes reducing NuGet's dependency on JSON LINQ (such as JObject). This work has the outcome of significantly improving performance of NuGet's JSON deserialization.
* Comparing the performance of well written Newtonsoft.Json code to well written System.Text.Json, from a client point of view, the perf gains are minimal.
* Profiling NuGet while it's doing a restore, time spent in Newtonsoft.Json was less than 1%. Any perf gains that System.Text.Json can provide will provide minimal improvement to restore times.
