### ISSUE TITLE
IVsXXX extensibility is needed for common scenarios like check for frameworks compatibility, semantic version, nupkg etc

### ISSUE THREAD

**Issue by abpiskunov** [NuGet/Home#826]
At this point PackageIndex and WebProject system both would need these API for several scenarios, where we need to see if package/project frameworks are compatible or comparing SemanticVersions etc. There may be other components in VS that would be interested, so it would be nice to have a single source for such common APIs

**Comment by emgarten** [comment]
@abpiskunov can you provide details on specific scenarios you have around checking compatibility?

**Comment by yishaigalatzer** [comment]
Why does the webproject system need that? I thought the plan going forward is to remove the WebProject system support for installing packages.

Can you be specific about what exact APIs are you looking for and what are the scenarios?

**Comment by abpiskunov** [comment]
Scenarios:
1. To know if TFM1 is compatible with TFM2 (we need that in several places, for example to know if package should be installed to the project or not; or to add project reference to existing project or block it)
2. Correct SemanticVersion comparison (now we have our custom comparison which is limited and might not be correct when nuget's logic changes)

**Comment by yishaigalatzer** [comment]
These are not scenarios, these are requirements.

See my comment above, if we are moving back the responsibility for installing packages into the nuget extension, then do you still need the APIs in item 1 or not?

Similar question for semantic version comparison

**Comment by abpiskunov** [comment]
For 1. I don't see it happening yet in U1, also if you read it carefully, there is a second scenario when we would need it. For 2 it is not related to packages at all, it is for any semantic version comparison. 
adding @BillHiebert and @barrytang

**Comment by abpiskunov** [comment]
adding @PradeepKadubandi also

**Comment by yishaigalatzer** [comment]
Also consider this ask (seems duplicate) https://github.com/NuGet/Home/issues/807

**Comment by joelverhagen** [comment]
Per a meeting offline with @abpiskunov, we have narrowed the requirements for his scenario to the following required APIs. The shape might change a bit, but this is the general idea:

``` csharp
    /// <summary>
    /// Provides API for comparing and parsing frameworks 
    /// </summary>
    public interface IVsFrameworkProvider
    {
        /// <summary>
        /// returns correct short name for a FrameworkName (used in project.json  file as target framework name)
        /// </summary>
        string GetShortFrameworkName(FrameworkName fxName);

        /// <summary>
        /// could be a short name like dotnet5.1 or full framework name like .Net Framework XXXX 
        /// </summary>
        FrameworkName ParseFrameworkName(string shortOrFullFxName);

        /// <summary>
        /// note that compatibility could be one sided for example net451 is compatible with net452, but not other way around
        /// </summary>
        bool AreCompatible(FrameworkName source, FrameworkName target);

        /// <summary>
        /// returns framework form the list that matches given framework best: 
        ///     net45, dnx451 are both compatible for dnx452, but dnx451 is closer etc
        /// </summary>
        FrameworkName GetClosestFramework(FrameworkName targetFramework, IEnumerable<FrameworkName> frameworks);
    }

    /// <summary>
    /// Provides API for parsing semantic versions.
    /// </summary>
    public interface IVsSemanticVersionComparer
    {
        // standard 0, 1, -1 result for comparison
        int Compare(string versionString1, string versionString2);
    }
```

**Comment by yishaigalatzer** [comment]
@joelverhagen please spell out what API is required for what scenario right in the issue above.

**Comment by abpiskunov** [comment]
/// <summary>
/// Provides API for comparing and parsing frameworks 
/// </summary>
public interface IVsFrameworkProvider
{
    /// <summary>
    /// Returns correct short name for a FrameworkName (used in project.json  file as target framework name).
    /// In project.json targets are specified with short names most of the time and it would be helpful to have,
    /// a reliable way to get short names for frameworks when we manipulate dependencies in json file. 
    /// </summary>
    string GetShortFrameworkName(FrameworkName fxName);

    /// <summary>
    /// Could be a short name like dotnet5.1 or full framework name like .Net Framework XXXX 
    /// Opposite to above, which can provide generic FrameworkName out of given short or full 
    /// framework name also should be used when manipulating dependencies in project.json and need to 
    /// reliably compare framework names.
    /// </summary>
    FrameworkName ParseFrameworkName(string shortOrFullFxName);

    /// <summary>
    /// Useful for scenarios when we need to compare dependencies, for example when adding project refereces we need to 
    /// see if dependency project's targets are compatible with given project targets and we need to add dependency only to 
    /// compatible targets in project.json (or show message that there no compatible frameworks)
    /// Note: that compatibility could be one sided for example net451 is compatible with net452, but not other way around
    /// </summary>
    bool AreCompatible(FrameworkName source, FrameworkName target);

    /// <summary>
    /// Used in scenarios when some dotnet project property needs to contain a TFM part, for example output path.
    /// In order to get a TFM we need to select best compatible framework out of list of project's targets.
    /// 
    /// returns framework form the list that matches given framework best: 
    ///     net45, dnx451 are both compatible for dnx452, but dnx451 is closer etc
    /// </summary>
    FrameworkName GetClosestFramework(FrameworkName targetFramework, IEnumerable<FrameworkName> frameworks);
}

/// <summary>
/// Provides API for parsing semantic versions.
/// </summary>
public interface IVsSemanticVersionComparer
{
    /// <summary>
    /// Can be used in any places where we need to compare semantic package versions. For example, now it would be
    /// used in our runtime related logic when we are determining correct package versions to use for build, restore etc.
    /// returns: standard 0, 1, -1 result for comparison
    /// </summary>
    int Compare(string versionString1, string versionString2);
}

**Comment by abpiskunov** [comment]
``` cs
/// <summary>
/// Provides API for comparing and parsing frameworks 
/// </summary>
public interface IVsFrameworkProvider
{
    /// <summary>
    /// Returns correct short name for a FrameworkName (used in project.json  file as target framework name).
    /// In project.json targets are specified with short names most of the time and it would be helpful to have,
    /// a reliable way to get short names for frameworks when we manipulate dependencies in json file. 
    /// </summary>
    string GetShortFrameworkName(FrameworkName fxName);

    /// <summary>
    /// Could be a short name like dotnet5.1 or full framework name like .Net Framework XXXX 
    /// Opposite to above, which can provide generic FrameworkName out of given short or full 
    /// framework name also should be used when manipulating dependencies in project.json and need to 
    /// reliably compare framework names.
    /// </summary>
    FrameworkName ParseFrameworkName(string shortOrFullFxName);

    /// <summary>
    /// Useful for scenarios when we need to compare dependencies, for example when adding project refereces we need to 
    /// see if dependency project's targets are compatible with given project targets and we need to add dependency only to 
    /// compatible targets in project.json (or show message that there no compatible frameworks)
    /// Note: that compatibility could be one sided for example net451 is compatible with net452, but not other way around
    /// </summary>
    bool AreCompatible(FrameworkName source, FrameworkName target);

    /// <summary>
    /// Used in scenarios when some dotnet project property needs to contain a TFM part, for example output path.
    /// In order to get a TFM we need to select best compatible framework out of list of project's targets.
    /// 
    /// returns framework form the list that matches given framework best: 
    ///     net45, dnx451 are both compatible for dnx452, but dnx451 is closer etc
    /// </summary>
    FrameworkName GetClosestFramework(FrameworkName targetFramework, IEnumerable<FrameworkName> frameworks);
}

/// <summary>
/// Provides API for parsing semantic versions.
/// </summary>
public interface IVsSemanticVersionComparer
{
    /// <summary>
    /// Can be used in any places where we need to compare semantic package versions. For example, now it would be
    /// used in our runtime related logic when we are determining correct package versions to use for build, restore etc.
    /// returns: standard 0, 1, -1 result for comparison
    /// </summary>
    int Compare(string versionString1, string versionString2);
}
```

**Comment by yishaigalatzer** [comment]
@joelverhagen another one I believe is done, please resolve appropriately

**Comment by joelverhagen** [comment]
I have worked with @abpiskunov on these asks and all of the APIs are available, save `AreCompatible`, which Anton has another approach for (`GetClosestFramework` returns `null` if the provided framework are incompatible). Closing.
