### ISSUE TITLE
Locked-mode restore fails when a project's RuntimeIdentifier is changed

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8260]
## Details about Problem

dotnet.exe --version: Both 3.0.100-preview5-011568 and 2.2.204

### Automated repro
I've created a self-contained automated repro. You can run it by downloading 
[repro_runtimeIdLockFile.zip](https://github.com/NuGet/Home/files/3322730/repro_runtimeIdLockFile.zip) and running repro.bat

### General behavior:
1. Create a csproj targeting runtime identifier A
2. `dotnet restore --use-locked-file`
3. Change the runtime identifier to B
4. `dotnet restore --locked-mode`

### Expected behavior
1. The second restore should fail with ` error NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Please disable RestoreLockedMode MSBuild property or pass explicit --force-evaluate flag to run restore to update the lock file.`
2. The second restore should **not** install any packages (it's in locked mode)

### Actual behavior
1. The second restore fails with `error NU1403: The package runtime.osx-x64.Microsoft.NETCore.App.2.1.10 sha512 validation failed. The package is different than the last restore.`
2. The second restore installs OSX runtime packages

**Comment by nkolev92** [comment]
@cristinamanum 

Once you already have everything set-up, relevant code here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/ProjectLockFile/PackagesLockFileUtilities.cs#L49

The RIDS are not accounted for in that code path.
