### ISSUE TITLE
"dotnet restore" fails if "nuget" folder doesn't exist

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#8264]
_From @gthvidsten on Wednesday, June 26, 2019 11:58:14 AM_

## Steps to reproduce

I cloned a repo, but restore of NuGet packages (`dotnet restore`) failed with the following message:

> C:\Program Files\dotnet\sdk\2.2.101\NuGet.targets(114,5): error : The local source 'C:\ClonedRepo\nuget' doesn't exist. [C:\ClonedRepo\src\SomeProject\src\SomeProject.csproj]

I manually created `C:\ClonedRepo\nuget` and ran `dotnet restore` again, and now it worked just fine.

## Expected  behavior

`dotnet restore` should create the `nuget` folder if it doesn't exist.

## Actual behavior

`dotnet restore` fails because it can't find non-existing folder

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

_Copied from original issue: dotnet/cli#11634_

**Comment by livarcocc** [comment]
_From @gthvidsten on Wednesday, June 26, 2019 11:58:43 AM_

@blackdwarf

**Comment by rrelyea** [comment]
This is by design behavior. We fail restore if any of your sources are not reachable.
We don't want to create a folder for you, in case it was a typo.

A nuget.config should not configure sources that don't exist.
If there is machine config necessary that restore or build relies on, this should be communicated via readme.md or a msbuild based message?

This would work for command line restores: (wouldn't work inside of VS today)
```
  <Target Name="ensureSources" BeforeTargets="Restore">
    <Error Text="Run configure.ps1 to set up prereqs - missing local NuGetSource" Condition="!Exists('.\packages')" />
  </Target>

```

**Comment by bchewy** [comment]
> This is by design behavior. We fail restore if any of your sources are not reachable.
> We don't want to create a folder for you, in case it was a typo.
> 
> A nuget.config should not configure sources that don't exist.
> If there is machine config necessary that restore or build relies on, this should be communicated via readme.md or a msbuild based message?
> 
> This would work for command line restores: (wouldn't work inside of VS today)
> 
> ```
>   <Target Name="ensureSources" BeforeTargets="Restore">
>     <Error Text="Run configure.ps1 to set up prereqs - missing local NuGetSource" Condition="!Exists('.\packages')" />
>   </Target>
> ```

Hi, I'm very confused after looking at this, what exactly do i do with these few lines of code?

**Comment by levicki** [comment]
@rrelyea Sorry to necro this issue, but...

> This is by design behavior. We fail restore if any of your sources are not reachable. We don't want to create a folder for you, in case it was a typo.

What if the folder is a network share and is currently unreachable (and absolutely not needed for the packages in the current solution)?

Are we expected to connect to VPN to be able to access a network share with local feed even if the current solution we are working on only needs packages from say NuGet.org?

I understand failing to restore packages if you need the unreachable source to restore a specific package, but if you don't then why fail?

As it is, this behavior not only blocks restoring but also installing any other package from any other source if one of them is unreachable.

Please advise.
