### ISSUE TITLE
Investigate signature trust and validity functional tests

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8265]
## Details about Problem

NuGet product used: NuGet API

NuGet version: dev branch

OS version (i.e. win10 v1607 (14393.321)): NuGet CI Pipeline

Worked before? If so, with which NuGet version: These are tests that fails intermitently. 

## Detailed repro steps so we can see the same problem

1. Run a CI Build

The tests that are failing are:

- `VerifySignaturesAsync_WithExpiredPrimarySignature_ValidCountersignature_AndPrimarySignatureValidAtCountersignTime_SucceedsAsync` [permalink](https://github.com/NuGet/NuGet.Client/blob/b039c16d01170759f12fb5da4a78aba36a425779/test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/SignatureTrustAndValidityVerificationProviderTests.cs#L474) Failing at line 512 (approximately)
- `VerifySignaturesAsync_WithExpiredAndUntrustedPrimarySignature_ValidCountersignature_AndPrimarySignatureValidAtCountersignTime_SucceedsAsync` [permalink](https://github.com/NuGet/NuGet.Client/blob/b039c16d01170759f12fb5da4a78aba36a425779/test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/SignatureTrustAndValidityVerificationProviderTests.cs#L522) Failing at line 562 (apporximately)

## Other suggested things

Both tests fails at verifying a results list that should be empty, according to the tests.

```c#
  var resultsWithErrors = result.Results.Where(r => r.GetErrorIssues().Any());
```

Other failing builds:

- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2798844&view=logs
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2772497&view=logs&runId=6816226&resultId=100819
- https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2792043&view=logs&runId=6965562&resultId=100192

**Comment by heng-liu** [comment]
Bot work test: add a comment to test if `Triage:NeedsTriageDiscussion` is added correctly.
