### ISSUE TITLE
NU1603 is incorrectly raised with inconsistent versioning style

### ISSUE THREAD

**Issue by MisinformedDNA** [NuGet/Home#8267]
## Details about Problem

NuGet product used: VS UI
 
NuGet version (x.x.x.xxx): 5.1.0

VS version (if appropriate): VS 2019 v16.1

OS version (i.e. win10 v1607 (14393.321)): Win 1803 (17134.829)

Worked before? No?

## Detailed repro steps so we can see the same problem

1. Create a .NET Standard library

2. Add a NuGet reference to `FluentNHibernate`

EXPECTED: No warnings

ACTUAL: Two NU1603 warnings

> Warning	NU1603	NHibernate 4.0.0.4000 depends on Iesi.Collections (>= 4.0.0 && < 5.0.0) but Iesi.Collections 4.0.0 was not found. An approximate best match of Iesi.Collections 4.0.0.4000 was resolved.	NU1603	C:\Users\XXXX\Source\Repos\ClassLibrary1\NU1603\NU1603.csproj	1	
> Warning	NU1603	FluentNHibernate 2.0.1 depends on NHibernate (>= 4.0.0) but NHibernate 4.0.0 was not found. An approximate best match of NHibernate 4.0.0.4000 was resolved.	NU1603	C:\Users\XXXX\Source\Repos\ClassLibrary1\NU1603\NU1603.csproj	1	

In both cases, it complains that version `4.0.0` was not found and resorted to `4.0.0.4000`. But the requirement is `>= 4.0.0` and `4.0.0.4000` sure seems to match that requirement.

### Sample Project

[NU1603issue.zip](https://github.com/NuGet/Home/files/3335287/NU1603issue.zip)

**Comment by MisinformedDNA** [comment]
Sorry, I was confusing two different rules. I think this rule is executing as expected.

**Comment by rrelyea** [comment]
Yes, see more info here: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1603

The package is causing a perf problem. It depends on a package that has not been published to one of your sources. Package Author problem. Please contact author.
