### ISSUE TITLE
Insert NuGet 5.2.0.6067 into VS 16.2

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8268]
## Insert build 5.2.0.6067 for insertion into VS 16.2
- [x] Validate tests
- [x] Validate perf - https://devdiv.visualstudio.com/DevDiv/_build/results?releaseId=0&environmentId=1739355&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab&_a=release-environment-extension
- [x] Vendor validation - validated on top of d16.2stg 29027.113
- [x] verify "VsTargetBranch" in buildinfo.json on ddfiles for that  build -- yes it is:  "lab/d16.2stg",
- [x] verify cli/sdk branches to insert into:
- "CliTargetBranches":  "release/2.2.4xx;release/2.1.8xx;release/3.0.1xx",
- "SdkTargetBranches":  "release/2.2.4xx;release/2.1.8xx;release/3.0.1xx",
- [x] confirm new build has a different assembly version (run ildasm on nuget.frameworks.dll) -- current VS 16.2stg build is 5.2.0.2. 5.2.0.6067 has 5.2.0.3.
- [x] Submit insertion bug [939737](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/939737) for approval
- [x] merge VS Insertion PR [189144](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/189144?_a=overview)

## Post VS insertion insertions
- [x] SDK - https://github.com/dotnet/sdk/pull/3370 https://github.com/dotnet/sdk/pull/3371 https://github.com/dotnet/sdk/pull/3372
- [x] CLI - https://github.com/dotnet/cli/pull/11658 https://github.com/dotnet/cli/pull/11659 https://github.com/dotnet/cli/pull/11660
- [x] Toolset - https://github.com/dotnet/toolset/pull/1323
- [ ] Mono
- [ ] VS4Mac
- [x] increment assembly version in case we need to insert again.

**Comment by nkolev92** [comment]
We should probably branch at this point. 

There is no more M2 code flow for 5.2
