### ISSUE TITLE
Package Manager experiences for VS Codespaces

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8270]
Per this blog post from May 2019, https://aka.ms/vsfutures --> https://devblogs.microsoft.com/visualstudio/intelligent-productivity-and-collaboration-from-anywhere/

[ADO Query](https://devdiv.visualstudio.com/DevDiv/_queries/query-edit/5d5d5ecc-9e55-4053-9cdb-245a082dd02f/)

**Comment by nkolev92** [comment]
fyi @karann-msft, @aortiz-msft Epic tracking VSO.
