### ISSUE TITLE
"%23" is transformed into "#" for physical path, nuget or msbuild?

### ISSUE THREAD

**Issue by cbries** [NuGet/Home#8273]
In case I got a VisualStudio-solution with several projects (by email or from somewhere else) and within the solution one or more projects are in physical directories which include "%23" in there path, e.g. 
> C:\users\someuser\source\repos\_1.12\%231986\A-Serie-XYZ

During Solution-load the following error raise up in VisualStudio's error pane:

![image](https://user-images.githubusercontent.com/5418062/60316448-c871e000-996a-11e9-8070-5346a0a94354.png)

Because "%23" is transformed to "#" which is physically not available.

Host: VisualStudio 2019 Preview, 16.2.0 Preview 3.0

**Comment by zivkan** [comment]
I created a test project and found that the dotnet cli's msbuild works, while VS's msbuild has the error. I feel like it's probably an msbuild issue, but I want to have a better repro to share before passing it over.

**Comment by zkat** [comment]
moved to https://github.com/microsoft/msbuild/issues/5310
