### ISSUE TITLE
Unneeded assemblies in VSIX

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#828]
The 3.0-RTM VSIX contains additional dlls which may which not be needed.

* Microsoft.VisualStudio.ProjectSystem.V14Only.dll  - This is the CTP6 version, it should come from VS not from the VSIX 
* WindowsBase.dll - is this needed?
* System.ComponentModel.DataAnnotations.dll
* System.Net.Http.Extensions.dll
* System.Net.Http.Primitives.dll

**Comment by yishaigalatzer** [comment]
We need to remove the unnecessary packages, and we need a test to verify that nothing extra gets accidentally introduced. That test needs to run after we create the MSI
