### ISSUE TITLE
Add support for deprecation info to dotnet list package --outdated

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#8280]
See [spec](https://github.com/NuGet/Home/wiki/Deprecate-packages#cli).

```
> dotnet list package --outdated

3 packages need your attention - 2 outdated, 1 deprecated.

Package                Current     Wanted      Latest   
EntityFramework        6.1.2       6.1.2       6.2.0   
NUnit                  2.4.0       2.6.4       3.8.1  
My.Sample.Pkg          2.1.3 (D)   4.1.0       4.1.0

(D): Deprecated package(s). Use '--show-deprecated' option for more info.
```

**Comment by xavierdecoster** [comment]
@anangaur in the sample from the spec, the legend refers to a `--show-deprecated` option. Did you mean `--deprecated` instead?

```
(D): Deprecated package(s). Use '--show-deprecated' option for more info.
```

**Comment by xavierdecoster** [comment]
Additional question: if the `--outdated` option is to show deprecated labels, then what's the behavior of using both `--outdated --deprecated` options for `dotnet list package`?

**Comment by anangaur** [comment]
Remnant of older spec 😄.  —deprecated is good enough.

If both options are used, may be we should first state the outdated output followed by deprecated? And the info message goes away. This should be done per project output. However, if you got another proposal, let’s discuss that as well.

**Comment by nkolev92** [comment]
Can you please consolidate the spec/describe the expectations in each of the weird scenarios? :)
I guess this refers to both of you. 

It'll be easier to review the implementation if we're confident about what the expectations should be.
