### ISSUE TITLE
Update CLI docs to include package deprecation and vulnerability support

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#8281]
Update docs to include information about the following CLI updates:

`dotnet package list --outdated`
`dotnet package list --deprecated` 
`dotnet package list --vulnerable` 

For details, see the issues linked to [this spec](https://github.com/NuGet/Home/issues/8278).

**Comment by nkolev92** [comment]
Done: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-list-package
