### ISSUE TITLE
Old bond incompatibility issue. While building bond rpc I am getting error.

### ISSUE THREAD

**Issue by ashigput** [NuGet/Home#8285]
healthtypeforstoragemypersonal_types.h(24): fatal
       error C1189: #error:  This file was generated by an older Bond compiler which is incompatible with current Bond library. Please regenerate with the latest Bond compiler.

**Comment by zivkan** [comment]
@ashigput Perhaps you would like to try https://github.com/Microsoft/bond/issues, as I don't see how this is related to NuGet. If you get this error after using a NuGet package that has Bond files, you can use the "Contact owners" link on nuget.org when viewing the package to contact the owners and ask them to update to a newer version of Bond. The NuGet team does not support individual packages.
