### ISSUE TITLE
PM UI changes - unify Update/Installed tab

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8290]
Currently the update/installed tabs differ in 3 ways. 

1. On the installed tab, all top level dependency are displayed.  On the updates tab, only the ones that have newer versions on the selected source(s) are displayed. 
1. The updates tabs has checkboxes that are used to allow a multi package update. 
1. The updates label has a number that says how many packages have updates. 

My proposal is to merge these 2 tabs into since so much of the information is redundant. 

1. Add a new checkbox to filter packages with updates only. 
1. Keep the checkboxes on by default (or enable it when the updates only filter is checked). 
1. Keep the label on the newly consolidated tab. 

//cc @karann-msft @anangaur Thoughts?

**Comment by anangaur** [comment]
Would need UX study and some validation as part of customer studies. We should explore this though.

**Comment by donnie-msft** [comment]
@nkolev92  I am logically already doing this by moving toward a single ItemsControl, with the Updates tab simply filtering down certain items. Does this encapsulate your concern? https://github.com/NuGet/Home/issues/10082

**Comment by nkolev92** [comment]
Yes, I think so. 

Feel free to close it if it makes your tracking easier!
