### ISSUE TITLE
Raise NU5037 error with good doc page that explains customer fixes (The package is missing the required nuspec file)

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8291]
## Details about Problem

dotnet.exe --version: 3.0.100-preview5-011568

## Detailed repro steps so we can see the same problem

1. Create a .csproj

2. Add a PackageReference to something not bundled with the .net sdk (e.g. ````<PackageReference Include="NUnit" Version="3.12.0" />````)

3. `dotnet restore`

4. Delete the .nuspec file for the package from the packages cache (e.g. %userprofile%\.nuget\packages\nunit\3.12.0\nunit.3.12.0.nuspec

5. Delete the obj\ directory next to the .csproj

6. `dotnet restore`

This will produce the following error: `error NU5000: Nuspec file does not exist in package`

## Desired behavior
One of the following should happen:
1. The error should identify which package id/version/install dir is broken.
    a. Otherwise the error is nearly inactionable without clearing the entire packages cache
2. Silently reinstall the package like would occur if the entire install dir was deleted

## Comments
* This reflects cache corruption; it is not a mainline scenario
* This is a real scenario that one of our devs encountered (though we don't know exactly how the bad state happened)

**Comment by nkolev92** [comment]
I would say the message needs to be improved. 

It's not really a cache, there's no TTL/expiration policy. 
It's an install directory, so if something gets corrupted, cleaning it out is the recommended approach. 

I think the message should suggest potential corruption and suggest to the user that they should delete the install folder. 

I guess this is yet another potential thumbs for something like `locals clear packageid`.

**Comment by rrelyea** [comment]
Let's make a new error code for this situation. (don't use NU5000...)

Then let's error with:
The global package folder copy of package 'Foo.Bar' is missing one or more files: '<fullpathtofile>'.
