### ISSUE TITLE
How to deprecate the nuget package in nuget.org

### ISSUE THREAD

**Issue by kmuthukumar23** [NuGet/Home#8301]
I want to deprecate the nuget packages and add the tag as deprecated and provide the alternative package link on that deprecated package in nuget.org.

Can any one help me on this?

I have tried this [feed ](https://github.com/NuGet/Home/wiki/Deprecate-packages) but in my nuget.org profile does not have 'Deprecate package(s)' section.

What can i do now for deprecate the package?

**Comment by anangaur** [comment]
The feature is not yet live. But the good news is it will be, soon. We will announce the availability when this happens.
