### ISSUE TITLE
PackageReference from a Build Package

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#8307]
Hello,
i know that package references inside build packages are explicitly disabled, to avoid endless restores. I read, that it might be possible to get package references inside build packages working by restoring a second time. Can somebody explain, whats the best way to do that? My scenario is simple: I have a build package and based on some conditions i want that a second package is referenced automatically. So making the second package as a dependency of the build package won't work, because of the conditional thing.

Many thanks in advance.

**Comment by nkolev92** [comment]
> . I read, that it might be possible to get package references inside build packages working by restoring a second time.

I can't think of a way this can be achieved. 
Where did was that mentioned?

**Comment by TFTomSun** [comment]
I'll search for it later. I also recognized that visual studio restores such package references inside build packages correctly. Why is there a difference between visual studio and dotnet build/msbuild?

**Comment by TFTomSun** [comment]
@nkolev92  I narrowed down the difference between Visual Studio and dotnet build. Here are my 2 build packages. The test package references the nunit dependencies as well as provides them as a reference via the CrossCutting.Test.props file
[CrossCutting.zip](https://github.com/NuGet/Home/files/3377260/CrossCutting.zip)

When I reference the package in a test project, visual studio produces the following output:
![image](https://user-images.githubusercontent.com/5387192/60966748-3a5a0a00-a319-11e9-9bb0-8e7cf14177da.png)

dotnet build produces:
![image](https://user-images.githubusercontent.com/5387192/60966774-4cd44380-a319-11e9-9acf-c5230d0cc093.png)

As you can see some of the files are missing.

If i start a test run inside visual studio the test runs fine. When I start it from the console with dotnet test (after dotnet build) it can't discover any tests.

Edit: dotnet msbuild produces the same output like dotnet build

**Comment by nkolev92** [comment]
That is a VS bug, specifically project-system. 

Tracking issues: 
https://github.com/dotnet/project-system/issues/3734
https://github.com/dotnet/project-system/issues/653

The commandline experience is the correct one, so I'd recommend not relying on that.

**Comment by TFTomSun** [comment]
For all who come across this thread. I found a solution. I use a custom SDK instead of a build package. Inside the custom SDK i can add package references and they are handled correctly by the cli and Visual Studio.
The only disadvantage that SDK packages have right now, is that you can't point to the latest available version, which means no wildcard support in versioning.

**Comment by nkolev92** [comment]
Yeah, that's the way to satisfy the scenario. 

Note that there's perf concerns with that scenario.
https://github.com/microsoft/msbuild/issues/4025

Feel free to close if the concerns have been addressed.
