### ISSUE TITLE
GeneratePathProperty metadata on package reference does not generate the property

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#8311]
The feature GeneratePathProperty introduced with Visual Studio 15.9. seems not to work for me.

I'm using Visual Studio 15.9.11

My code
```xml

<ItemGroup>
    <PackageReference Include="CrossCutting.Build" Version="[*,9999.0]" GeneratePathProperty="true">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="Mylog" AfterTargets="CoreCompile">
    <Message Importance="high" Text="PkgCrossCutting_Build: $(PkgCrossCutting_Build)"></Message>
  </Target>



```
Expected output:
PkgCrossCutting_Build: [path to the resolved package]

Actual output
PkgCrossCutting_Build:

The property seems not to be generated at all.

**Comment by nkolev92** [comment]
@TFTomSun 
Are you able to repro this with other package ids (this one is not public, so I couldn't try, but I tried with other IDs and I couldn't repro it). 
Any public packages? 

It's possible that you are hitting: https://github.com/NuGet/Home/issues/7843

Is CrossCutting.Build the exact casing of the package in the nuspec. 

Can you upload the nuget.g.props & project.assets.json file if possible?

Note that they'll both contain local machine paths, sources and other project information that you might want obfuscated

**Comment by TFTomSun** [comment]
@nkolev92 i got it working, somehow. But honestly, i don't know what changed the behavior. Therefore I can't reproduce the issue anymore. And I achieved the goal, for what I wanted to use that feature with a custom SDK.
