### ISSUE TITLE
New helper function - get the top level packages given a package graph.

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8316]
We have partner teams who want to be able to analyze a set of packages listed in a packages.config file, and understand which are top-level.
We have code like this in PC to PR migrator...likely just needs to be refactored a bit.

**Comment by nkolev92** [comment]
First attempt at https://github.com/NuGet/NuGet.Client/tree/dev-nkolev92-topLevelPackageUtility.

**Comment by Smartisa** [comment]
> First attempt at https://github.com/NuGet/NuGet.Client/tree/dev-nkolev92-topLevelPackageUtility.

The link is not available now. Can you share it again?
Thanks!
