### ISSUE TITLE
Content files in Nuget package do not wind up in bin folder and get treated as C# files

### ISSUE THREAD

**Issue by mperdeck** [NuGet/Home#8319]
I need to distribute 2 .dll files along with 2 .xml files to various .Net Core projects targeting net47. Both the .dll and .xml files have to wind up in the bin folder of the projects.

I created the .nuspec file below. I'm copying all files to lib\net47. I'm also copying the .xml files to contentFiles\any\any.

I'm using a PackageReference to include this Nuget package into my projects:
`<PackageReference Include="Decideware.Spire.Xls" Version="*" />`

Problem is that when I build the project, the .xml files wind up amongst my source files. Also the build action has been changed from "None" in my .nuspec to "C# Compiler" and copyToOutput has been changed from "true" to "Do Not Copy". Visual Studio then tries to build the .xml files as if they were C# files, leading to lots of error messages.

How do I structure my .nuspec so the .xml files are copied to my bin directory?

```
<?xml version="1.0" encoding="utf-8"?>
<package>
    <metadata>
        <id>Decideware.Spire.Xls</id>
        <version>7.12.3</version>
		<!-- required for .Net Core style PackageReferences -->
		<contentFiles>
			<files include="Spire.XLS.xml" buildAction="None" copyToOutput="true" />
			<files include="license.elic.xml" buildAction="None" copyToOutput="true" />
		</contentFiles>
    </metadata>
	<files>
		<file src="Spire.License.dll" target="lib\net47\Spire.License.dll" />
		<file src="Spire.XLS.dll" target="lib\net47\Spire.XLS.dll" />
		
		<file src="Spire.XLS.xml" target="lib\net47\Spire.XLS.xml" />
		<file src="license.elic.xml" target="lib\net47\license.elic.xml" />
		
		<file src="Spire.XLS.xml" target="contentFiles\any\any\Spire.XLS.xml" />
		<file src="license.elic.xml" target="contentFiles\any\any\license.elic.xml" />
	</files>
</package>

```

**Comment by nkolev92** [comment]
```
	<contentFiles>
			<files include="Spire.XLS.xml" buildAction="None" copyToOutput="true" />
			<files include="license.elic.xml" buildAction="None" copyToOutput="true" />
		</contentFiles>
```

I think  you need to refer to the files in there with a contentFiles relative path. 
Or you might be able to glob them with something like `**/*.xml`.

**Comment by dotMorten** [comment]
I recently logged an issue about this elsewhere, and was told this was by-design, and you need to specify the build action in the nuspec. I do find it weird that the default action isn't 'content' considering it's in the `contentFiles` folder, but 🤷‍♂

**Comment by nkolev92** [comment]
Closing as this seems to be a set-up problem.
