### ISSUE TITLE
Update-Package will give error if the package installed has a higher version than the latest version uploaded to nuget.org

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#832]
Repro steps:
1. create a new Razor 3 web site
2. start PMC, type update-package

Expected: no package updates available

Actual:
PM> update-package 
Attempting to gather dependencies information for multiple packages with respect to project 'WebSite1(1)', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages
update-package : Unable to find package 'Microsoft.CodeDom.Providers.DotNetCompilerPlatform'. Existing packages must be restored before performing an install or 
update.
At line:1 char:1
+ update-package
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

**Comment by abatishchev** [comment]
Very annoying error, making many people stopping from adoption of VS2015 and going back to VS2013.
I would urge to release a hotfix, please. Can you share the schedule for 3.2?

**Comment by zidad** [comment]
Same problem here... I have to switch to VS2013 just to update nuget packages

**Comment by scottt732** [comment]
+1

**Comment by johnataylor** [comment]
I just created a project and added a local package with a version number higher than what I'd previously uploaded to nuget.org.

Now running Update-Package says there are no updates available from nuget.org which is the correct response. So I'm closing this issue.
