### ISSUE TITLE
[Test Failure] “Unable to parse config file” will prompt twice

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8320]
## Details about Problem
NuGet version: NuGet Client Release-5.2.x\5.2.0.6090
VS Version: D16.2\29110.123
OS: Windows 10 RS4_Release 17134.1.180410-1804
## Detailed repro steps so we can see the same problem
1. Create a solution with at least 1 project (e.g. 3 WPF projects) and close the solution.
2. And create a NuGet.Config file having some parsing errors next to the sln file.
3. Reload the solution.
## Expected
The error dialog “Unable to parse config file” will prompt only once.
## Actual
Same error dialog “Unable to parse config file” will prompt twice.
![ErrorDialogPromptTwice](https://user-images.githubusercontent.com/20632625/61047802-dddb1580-a412-11e9-86f0-070fd553d8c9.png)

**Comment by nkolev92** [comment]
I verified with 16.1, it is not a regression. 

Thinking about it I think my deadlock fix actually will address this. 
Will double check.

**Comment by nkolev92** [comment]
Will be fixed by https://github.com/NuGet/NuGet.Client/pull/2919.
