### ISSUE TITLE
get nuget-client source-build clean (patches)

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8321]
get patch clean - https://github.com/dotnet/source-build/tree/release/3.0/patches/nuget-client

**Comment by dominoFire** [comment]
Related PR: https://github.com/dotnet/source-build/pull/1189

Both seeing the error with NuGet.ProjectModel in a core-setup custom MSBuild task.

**Comment by nkolev92** [comment]
Long irrelevant :)
Closing.
