### ISSUE TITLE
Nugetizer3000 includes reference-only content in package

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#8322]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet + NuGet.Build.Packaging

NuGet.Build.Packaging - 0.2.3

dotnet.exe --version (if appropriate):
2.2.107

## Detailed repro steps so we can see the same problem

1. Create a netstandard2.0 class library, use following project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>n3000</PackageId>
    <Description>n3000 test nuget package</Description>
    <RestoreSources>$(RestoreSources);https://ci.appveyor.com/nuget/nugetizer3000</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Build.Packaging" Version="0.2.3" />
  </ItemGroup>
</Project>
```

2.  dotnet build

Expect: package with only lib
Actual: package contains all netstandard reference only libraries.

Bug is here: https://github.com/NuGet/NuGet.Build.Packaging/blob/abbff50b9b64d708945a726405e70351035cadb5/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.Inference.targets#L186-L190

This shouldn't be packing referencepath, but instead something like ReferenceCopyLocalPaths.

**Comment by ericstj** [comment]
Looks like the workaorund here is to set
```xml
  <IncludeFrameworkReferencesInPackage>false</IncludeFrameworkReferencesInPackage>
```

**Comment by ericstj** [comment]
Correction, this is actually https://github.com/NuGet/Home/issues/5800 and is fixed in a later release.

**Comment by ericstj** [comment]
So this worked for me after updating to 0.2.5-dev.9, at least for NETStandard.Library.  I'm reactivating this because I believe this is still wrong in general, the fix for NETStandard.Library just hardcoded that package ID 😢.  

These assets added by NETStandard.Library are *references* and will never be copied to the output of a project, I believe that's controlled by the `CopyLocal` metadata on the item placed there by ResolveAssemblyReferences (which is related to the value of `Private` metadata on the original reference).  There are other packages which can behave the same way should not be included in the nupkg.

**Comment by ericstj** [comment]
Here's a hack that I used to fix this problem more generically:
```xml
  <Target Name="RemoveNoCopyReferences" BeforeTargets="InferPrimaryOutputDependencies">
    <ItemGroup>
      <_PrimaryOutputRelatedFile Remove="@(_PrimaryOutputRelatedFile)" Condition="'%(_PrimaryOutputRelatedFile.CopyLocal)' == 'false'" />
    </ItemGroup>
  </Target>
```

It'd be better if instead the condition was updated here to consider CopyLocal instead of hardcoding NETStandard.Library:
https://github.com/NuGet/NuGet.Build.Packaging/blob/abbff50b9b64d708945a726405e70351035cadb5/src/Build/NuGet.Build.Packaging.Tasks/NuGet.Build.Packaging.Inference.targets#L186-L190

**Comment by kzu** [comment]
Agreed the fix could use that instead. @ericstj could you send a PR with a test plz?

**Comment by ericstj** [comment]
I don't need this fixed myself, and I'm not interested in contributing to yet another method for producing NuGet packages.   I'd really prefer we make the built-in Pack task better.

**Comment by kzu** [comment]
Makes sense!
