### ISSUE TITLE
Used -DependencyVersion Highest but non-latest version installed

### ISSUE THREAD

**Issue by TysonMN** [NuGet/Home#8327]
I am confused about the behavior of `Install-Package` when executed from Visual Studio's Package Manager Console.  I am using `-DependencyVersion Highest` but a less-than-highest version is being installed, and I don't understand why.

## Details about Problem

NuGet product used: Package Manager Console Host Version 5.1.0.6013
NuGet version: 3.5.0.1938
VS version: Visual Studio Enterprise 2019 version 16.1.5
OS version: Windows 10 v1803 (17134.885)

## Detailed repro steps so we can see the same problem

1. Observe that the [NuGet package of `Serilog.AspNetCore`](https://www.nuget.org/packages/Serilog.AspNetCore/2.1.1) depends on `Microsoft.Extensions.Logging (>= 2.0.0)`.

2. Observe that the latest release (i.e., non-preview) version of [`Microsoft.Extensions.Logging`](https://www.nuget.org/packages/Microsoft.Extensions.Logging/) (as of this writing) is 2.2.0.

3. In the Package Manager Console of Visual Studio, run `Install-Package Serilog.AspNetCore -DependencyVersion Highest`.

4.  Observe that version 2.0.0 of `Microsoft.Extensions.Logging` was installed (also see logs below).

## Expected behavior

I expected version 2.2.0 of `Microsoft.Extensions.Logging` to be installed since I used `-DependencyVersion Highest`.

Something I wonder is if there are additional implicit constraints that caused 2.0.0 to be installed instead of 2.2.0.  That would explain this behavior, but then I want to know how to make those implicit constraints explicit.

### (Non-Verbose) Logs
```
PM> Install-Package Serilog.AspNetCore -DependencyVersion Highest
Restoring packages for C:\Users\twilliams\Documents\Visual Studio 2017\Projects\Temp\Temp\Temp.csproj...
Installing NuGet package Serilog.AspNetCore 2.1.1.
Committing restore...
Writing assets file to disk. Path: C:\Users\twilliams\Documents\Visual Studio 2017\Projects\Temp\Temp\obj\project.assets.json
Restore completed in 212.54 ms for C:\Users\twilliams\Documents\Visual Studio 2017\Projects\Temp\Temp\Temp.csproj.
Successfully installed 'Microsoft.AspNetCore.Hosting.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.AspNetCore.Hosting.Server.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.AspNetCore.Http.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.AspNetCore.Http.Features 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Configuration.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.DependencyInjection 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.FileProviders.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Hosting.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Logging 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Logging.Abstractions 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Options 2.0.0' to Temp
Successfully installed 'Microsoft.Extensions.Primitives 2.0.0' to Temp
Successfully installed 'Serilog 2.5.0' to Temp
Successfully installed 'Serilog.AspNetCore 2.1.1' to Temp
Successfully installed 'Serilog.Extensions.Logging 2.0.0' to Temp
Successfully installed 'System.Runtime.CompilerServices.Unsafe 4.4.0' to Temp
Successfully installed 'System.Text.Encodings.Web 4.4.0' to Temp
Executing nuget actions took 622.13 ms
Time Elapsed: 00:00:01.3739645
```

### Sample Project

Here is a zip of the solution I used to create the above logs.

[Temp.zip](https://github.com/NuGet/Home/files/3387928/Temp.zip)

**Comment by nkolev92** [comment]
DependencyVersion is not a thing in PackageReference world, and from what I can see from your repro project you are using PackageReference. 

There's an ask about adding it to PackageReference, but it wouldn't be an install only decision, but a restore decision. 

https://github.com/NuGet/Home/issues/5553

**Comment by nkolev92** [comment]
On a side note I think it's worth having a warning message when someone uses this option in PR. 
It's already disable in the PM UI.
