### ISSUE TITLE
PSSearchResource is not honoring includePrerelease flag

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#833]
Even though the search filter sets includePrerelease to false, PSSearchResource is still returning prerelease versions for packages.

Repro steps:
1. Have nuget.org as the package source
2. Start PMC, type get-package -Listavailable

Expected: only stable versions are returned

Actual: prerelease versions are returned as well.

Tried with other package sources, this issue does not repro.

**Comment by danliu** [comment]
Here is the query to the search service (as seen in Fiddler)

https://api-v3search-0.nuget.org/query?q=&skip=0&take=50&prerelease=false

In the .json results, the Versions property contains all stable and prerelease versions, which should not be the case.

So this may be a search service issue.

**Comment by yishaigalatzer** [comment]
@johnataylor verified today that this is fixed in the next version of the search service. @joelverhagen is going to build a functional test to verify it.

**Comment by joelverhagen** [comment]
Added a functional test to the V2/V3 combined search service to verify that the `prerelease` flag is observed (tests a query with the flag as `true` and as `false` against an index with both prerelease and non-prerelease packages).
