### ISSUE TITLE
Restoring PackageReferences bypasses Xamarin.Mac networking stack

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#8330]
## Details about Problem

NuGet product used: VS Mac

NuGet version: 5.2

VS version:

OS version: macOS 10.13

Worked before? No

## Detailed repro steps so we can see the same problem

1. Run a restore on a project that uses PackageReferences, or install/update a NuGet package that uses PackageReferences.
2. NuGet bypasses the native Xamarin.Mac networking stack when it goes online.

VS Mac has a custom HttpHandlerResourceProvider which ensures the Xamarin.Mac's NSUrlSessionHandler (HttpMessageHandler) is used when HttpClient requests are made using the SourceRepository.

Certain operations that involve PackageReferences do not use the provided SourceRepository instance. This then causes NuGet to use Mono's networking stack to make HttpClient requests.

The problem seems to be that the CachingSourceProvider creates its own set of INuGetResourceProvider's

    _resourceProviders.AddRange(Repository.Provider.GetCoreV3());

https://github.com/NuGet/NuGet.Client/blob/423aec56fa69a5633c1a33a143a8a0a75cd2b5cd/src/NuGet.Core/NuGet.Protocol/CachingSourceProvider.cs#L31-L36

Which bypasses the custom HttpHandlerResourceProvider that VS Mac uses.

NuGet needs a way to allow for the CachingSourceProvider to use VS Mac's custom HttpHandlerResourceProvider. 
...

**Comment by mrward** [comment]
Another approach may be to change NuGet to allow injection of a custom HttpMessageHandler - VS Mac currently duplicates some code from NuGet in order to support a custom HttpHandlerResourceProvider. That might be more work than just providing a way for the custom resource providers to be used everywhere.

**Comment by zivkan** [comment]
Reading the issue more carefully, it sounds like VS for Mac creates a `SourceRepository` with its own networking stack, and there are some NuGet SDK APIs that use it, but others do not?

Do you have an example of some NuGet SDK APIs that VS for Mac calls which does and does not use your `SourceRepository` instance?

It may be better to pass though the source repository, or something similar, rather than messing with a static factory.

**Comment by mrward** [comment]
My initial investigation indicated that any call to DependencyGraphRestoreUtility may result in the native HttpHandler being bypassed since the source repositories seem to be recreated at some point in the callstack.

https://gist.github.com/mrward/cb2cf92def183905250f707ea3e7077e

**Comment by mrward** [comment]
This is now resolved.
