### ISSUE TITLE
Nuget.exe restore foo.sln fails if %platform% contains spaces

### ISSUE THREAD

**Issue by jdege** [NuGet/Home#8335]
I'm not seeing any reference here to nuget.exe relying upon the %platform% enviornment variable: [https://docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-environment-variables)

But when I run "nuget.exe restore mysln.sln", and I have %platform" = "Any CPU" (for reasons that have nothing to do with nuget restore), I see "Any CPU" in the error message.

`...\VisualStudio\v16.0\Fakes\Microsoft.QualityTools.Testing.Fakes.targets(13,5): error MSB4184: The expression "System.IO.Path]::Combine(...\, obj\"Any CPU"\Debug\Fakes)" cannot be evaluated. Illegal characters in path.`

**Comment by donnie-msft** [comment]
The problem is not related to NuGet, but is part of the build process which doesn't expect quotes. 

Tested it myself and removing the quotes from the Environment Variable avoids this error.
