### ISSUE TITLE
Add automation for inserting into Core-SDK

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8342]
## Details about Problem

Our Release Pipeline should have a new step to insert into the new [.NET Core-SDK Repo](https://github.com/dotnet/core-sdk)

**Comment by nkolev92** [comment]
I guess this migh tnot be needed after all.

**Comment by donnie-msft** [comment]
Yep, Livar didn't want me to insert to that repo when I asked, yesterday. Closing for now.
