### ISSUE TITLE
NuGet.VisualStudio has dependencies on unofficial Microsoft packages

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#8343]
This package: https://www.nuget.org/packages/NuGet.VisualStudio/5.1.0 has a dependency on this package https://www.nuget.org/packages/VSSDK.TemplateWizardInterface/ and a bunch of other non-Microsoft provided packages.

This indirectly causes http://github.com/dotnet/project-system to have a dependency on these packages. Please remove this dependency, it is causing us to have duplicate references/double-writes to the following assemblies:

![image](https://user-images.githubusercontent.com/1103906/61429998-c6001600-a96b-11e9-87db-6dc69345f280.png)

The assemblies with the vssdk prefix are not Microsoft-provided packages.

**Comment by nkolev92** [comment]
This would break our template wizard implementation. @sharwell is there an MS version of the package in question?

**Comment by sharwell** [comment]
@nkolev92 There is no alternative package available (at least none known to me). DoubleWrites are not a problem by default for projects. Downstream consumers of this package who implement customized tooling to validate not having DoubleWrites will need to incorporate custom logic to address these assemblies.

**Comment by nkolev92** [comment]
@davkean's link contains a Microsoft.VisualStudio.TemplateWizardInterface.dll coming from a package with the same name.

Investigating it's on the https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json feed, 
https://dotnet.myget.org/F/roslyn-tools/api/v3/registration1/microsoft.visualstudio.templatewizardinterface/8.0.0-alpha.json

Adding this to quality week @aortiz-msft

**Comment by davkean** [comment]
@nkolev92 There is a public feed containing that dll here: https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vs-impl&package=Microsoft.VisualStudio.TemplateWizardInterface&protocolType=NuGet&version=16.8.30403.137-pre.

**Comment by swesonga** [comment]
@nkolev92 is this still an issue now that myget was deprecated?

**Comment by nkolev92** [comment]
@swesonga 

We haven't changed the dependency, so the same behavior still persists.

**Comment by LittleLittleCloud** [comment]
(Pin)
Hit the same issue here

**Comment by nkolev92** [comment]
This was fixed in 6.0/17.0. https://www.nuget.org/packages/NuGet.VisualStudio/6.0.0#dependencies-body-tab
