### ISSUE TITLE
Suggestion: Add "tag" attribute to nuspec repository element

### ISSUE THREAD

**Issue by devlead** [NuGet/Home#8346]
Currently you can reference git respository specific branch and / or commit, for example:
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd">
    <metadata>
        ...
        <repository type="git" url="https://github.com/NuGet/NuGet.Client.git" branch="dev" commit="e1c65e4524cd70ee6e22abe33e6cb6ec73938cb3" />
        ...
    </metadata>
</package>
```

As a commit can be referenced from  multiple tags, to be able to connect a package commit to a specific release it would be really use full to also have a `tag` attribute, for example:
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd">
    <metadata>
        ...
        <repository type="git" url="https://github.com/NuGet/NuGet.Client.git" branch="dev" commit="a84f3d21844519ed64b9b5bf74d3782ad89551b9" tag="5.3.0.6103" />
        ...
    </metadata>
</package>
```

**Comment by pascalberger** [comment]
Not sure it works that easy. If you expect `tag` and `commit` attribute and both are passed this is redundant information in the best case (if tag points to the specified commit) and conflicting information in the worst case (if tag points to a different commit). If you can either pass `commit` or `tag`, `tag` is not necessarily a clear reference to a specific version of the code as it can change later.

**Comment by devlead** [comment]
@pascalberger I don't agree that it's redundant,  i.e. if your package version and tag doesn't match it's really hard to know which release a package version was part of. SHA-1 commit is immutable so that won't change and the signing nuspec makes package immutable. Also multiple tags can point to came commit id, specifying tag in nuspec makes it clear which tag used for package release at time it was packages and signed.

I.e. package
https://www.nuget.org/packages/Cake.Core/0.34.1
was created by release 
https://github.com/cake-build/cake/releases/tag/v0.34.1
and commit 
https://github.com/cake-build/cake/commit/24fa8d94989b12f7ad8d2bf354c6ddadc629bf43
in branch 
https://github.com/cake-build/cake/tree/main

In that case nuspec repository element would look  like this
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd">
    <metadata>
        ...
        <repository type="git" url="https://github.com/cake-build/cake.git" branch="main" commit="24fa8d94989b12f7ad8d2bf354c6ddadc629bf43" tag="v0.34.1" />
        ...
    </metadata>
</package>
```

making package origins really clear, despite tag and NuGet version not matching.

**Comment by pascalberger** [comment]
@devlead I see the point of additional information a tag provides. My issue was the case where the tag points to a different commit than the provided commit at package creation or tags change and point to a different commit after package was created. But of course first case would be just wrong information passed to one one of the attributes and the second one is at least questionable practices.

**Comment by nkolev92** [comment]
At this point I don't see us doing this. 
We believe that the existence of commits and branches covers this scenario. 

Additionally this would require an adoption on the consumer side of this element so the effects would likely take some time to propagate, if ever.
