### ISSUE TITLE
vs nuget settings  binding Redirects and Project binding Redirects What is the relationship?

### ISSUE THREAD

**Issue by Jun-GY** [NuGet/Home#8353]
vs nuget settings  binding Redirects and Project binding Redirects What is the relationship?

**Comment by donnie-msft** [comment]
Relevant information:
https://docs.microsoft.com/en-us/nuget/tools/ps-ref-add-bindingredirect
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

**Comment by Jun-GY** [comment]
@donnie-msft，vs options->Nuget Package Manager->Binding Redirects(Skip applying binding redirects) Do not know！
