### ISSUE TITLE
5.2 Release - publish packages and nuget.exe

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8357]
- [ ] publish all packages to nuget.org
- [ ] publish nuget.exe to the downloads page

cc: @nkolev92 @rrelyea

**Comment by heng-liu** [comment]
Done with publishing all 5.2.0 packages. https://devdiv.visualstudio.com/DevDiv/_releaseProgress?releaseId=383159&_a=release-pipeline-progress
Done with publishing nuget.exe 5.2.0 to the downloads page. https://www.nuget.org/downloads
