### ISSUE TITLE
Restore errors should be formatted to show up in error list

### ISSUE THREAD

**Issue by Pilchie** [NuGet/Home#836]
When restore fails, the error messages are currently buried in a bunch of output in the VS Output Window.  They should be formatted so that the VS output window regex that promotes output window lines into error list entries picks them up.

**Comment by yishaigalatzer** [comment]
See https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivslaunchpad.parseoutputstringfortaskitem.aspx

**Comment by anurse** [comment]
This should go in the Visual Studio code that implements ILogger.

**Comment by emgarten** [comment]
This doesn't appear to work, even when writing the example string to the output window.

We already write to the error log directly for restore problems, we can do the same for errors and warnings coming from the build integrated restore.

**Comment by emgarten** [comment]
This will be fixed by: https://github.com/NuGet/NuGet.VisualStudioExtension/pull/35

**Comment by yishaigalatzer** [comment]
Fixed by the fix to 810
