### ISSUE TITLE
Remove temporary WorkaroundNetStandard target from common.targets

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8364]
Related issue: https://github.com/dotnet/cli/issues/11378
The above issue is already fixed in VS 2019 16.2 preview2. 
But we don't have the latest version of VS on VSEng-MicroBuildVS2019 agent pool (the current version is 16.1.6). So we have to add a temporary WorkaroundNetStandard target to common.targets to make the build pass.

We need to remove this WorkaroundNetStandard target from common.targets when the VS on agent pool VSEng-MicroBuildVS2019 has that fix.

**Comment by heng-liu** [comment]
For now, VS on agent VSEng-MicroBuildVS2019 is upgraded to 16.3. But VS on 
VSEng-MicroBuildSxS is not yet upgraded. Shall we upgrade the version of VS2019 on VSEng-MicroBuildSxS? @nkolev92

**Comment by nkolev92** [comment]
I think it's a good idea to ask for them to do that. 
I don't see any problems with that.

**Comment by heng-liu** [comment]
Closed as fixed.
