### ISSUE TITLE
More detailed errors/warnings in project.json restore

### ISSUE THREAD

**Issue by anurse** [NuGet/Home#837]
- [ ] Capture line information when parsing project.json
- [ ] Expose line information for dependency on unresolved dependency errors, incompatible package errors, etc.
- [ ] Track all cases where a project.json dependency is changed by a package pulling in a newer version and report them as warnings (expansion of #716)
- [ ] Specifically warn for when a project.json asked for version X, but version X does not exist anywhere and only version Y exist on the feeds. This should be configurable to be an error (and perhaps an auto-fix to bump the version in the project.json)
- [ ] Track cases where a project.json dependency pulls down a package dependency as report as warning

(this is all for post-3.1)

**Comment by yishaigalatzer** [comment]
@joelverhagen can you please go through this issue and clean it up with what was already done/what is else is needed

**Comment by rohit21agrawal** [comment]
i think we have done a good  enough job with errors and warnings now  to close this
