### ISSUE TITLE
Documentation:  NuGet API documentation does not describe possible exceptions

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8380]
See https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio.

XML doc comments for each interface member should describe which exceptions may be thrown and why via the [`<exception />`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/exception) tag.

**Comment by nkolev92** [comment]
All the APIs are up to date after the recent pushes. 

All of the public documentation matches the documentation in the code itself. 

https://github.com/NuGet/docs.microsoft.com-nuget/commit/6a6ab72760641425b34526730ea7f45262ccc45a and others did the work.
