### ISSUE TITLE
Undo temporary workaround for MSBuild bug causing Linux to timeout

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8382]
## Details about Problem
In [this issue](https://github.com/NuGet/Home/issues/8381), we set an Environment Variable to avoid a timeout caused by MSBuild: `MSBUILDDISABLENODEREUSE=1`.

Once MSBuild resolves [this issue](https://github.com/dotnet/cli/issues/11560), we should stop using this Environment Variable.

**Comment by jeffkl** [comment]
For hosted builds and to maximize isolation, I would recommend not using node reuse.  The feature was designed to decrease start up times for local builds.  However, MSBuild is NGen'd as part of Visual Studio installs and is very fast to start.  Node re-use can cause multiple invocations to share state and reliability is preferred over start up time in a hosted build.

Adding `-NodeReuse:false` to your command-line or setting the env var is the best option in my opinion.

**Comment by donnie-msft** [comment]
Thanks, @jeffkl  -- closing this since it sounds like it's safe to leave the EnvVar set in our builds. No need to revert.
