### ISSUE TITLE
Test:  InstallAndUpdatePackageWithSourceParameterWarnsAsync is flaky

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8386]
An APEX test is failing in multiple builds

https://devdiv.visualstudio.com/DevDiv/NuGet/_TestManagement/Runs?runId=7599252&_a=runCharts

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2886571

The 'Source' parameter is not respected for the transitive package management based project(s) TestProject. The enabled sources in your NuGet configuration will be used
Expected: True
Actual: False

**Comment by dtivel** [comment]
I investigated this a little.  It appears that the root cause may be the same as https://github.com/NuGet/Home/issues/7891.

![image](https://user-images.githubusercontent.com/12734758/62009651-8f1dc300-b116-11e9-973e-b90aab52cc1e.png)

**Comment by nkolev92** [comment]
I'm perplexed. 
This issue is so weird. I did notice a pattern, any time it failed, it was the net core test case that fail, so if we want, I can try to disable that test case, as the others cover the scenario, but not sure if that's hiding some potential issues in the infrastructure.
