### ISSUE TITLE
NuGet client in Dev14Rel updates per project nuget.config unnecessarily

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#841]
From @aarnot
![aabug](https://cloud.githubusercontent.com/assets/1238711/8320236/0b6b64ca-19cd-11e5-9980-530213097c6c.png)

**Comment by AArnott** [comment]
This repros on Dev14 RTM. Is that expected? When is the fix for this supposed to be observed?

**Comment by zhili1208** [comment]
@AArnott Yes, this is expected in RTM and the fix is in UWP version, we will release UWP version this week.
