### ISSUE TITLE
PackageReference wild card resolves to non-existent version

### ISSUE THREAD

**Issue by realrubberduckdev** [NuGet/Home#8411]
## Details about Problem

`Wild card package reference version resolves to the 'Version' value passed into msbuild instead of the value in NuGet Feed. I am not sure if this is expected behaviour, can someone please direct me towards documentation if this is expected.
`
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

```
NuGet.exe
MSBuild.exe
```

NuGet version (x.x.x.xxx): `5.0.2.5988`
MSBuild version: `Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework`

dotnet.exe --version (if appropriate): NA

VS version (if appropriate): `VS Professional 2019 v16.1.5`

OS version (i.e. win10 v1607 (14393.321)): `Win 10 Pro 1803`

Worked before? If so, with which NuGet version: `Don't know.`

## Detailed repro steps so we can see the same problem

1. Unzip TestProj.zip to get TestProj.csproj

2. Nuget Restore
`nuget restore .\TestProj.csproj`

3. MSBuild the proj
`msbuild .\TestProj.csproj /P:Version=99.99.99`

4. Check dependency version on Nuget Package Explorer
See that the dependency NUnit version is set to the value we were setting for our nupkg instead of resolving to the one in the nuget feed.

![image](https://user-images.githubusercontent.com/22910832/62284647-ea6bf000-b44b-11e9-9f23-ebdac607e3d1.png)

### Sample Project
[TestProj.zip](https://github.com/NuGet/Home/files/3456105/TestProj.zip)

**Comment by dominoFire** [comment]
Reproduced in VS 16.2.0

It seems like a bug in NuGet MSBuild tasks.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8333, fixed in 5.5.
