### ISSUE TITLE
Nuget MSBuild auto-detection picks up msbuild.exe 14 on a machine that has VS 2017 installed

### ISSUE THREAD

**Issue by menaheme** [NuGet/Home#8412]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used: NuGet.exe

NuGet version (4.9.3.5777):

VS version (if appropriate): 2017 , 15.9 (other versions of VS also installed. 2015)

OS version (i.e. win10 v1607 (14393.321)): Win 7 v 6.1.7601

## Detailed repro steps:

1. run Nuget Restore <path to sln>  -NoCache -NonInteractive

### Actual result:

MSBuild auto-detection finds MSbuild ver 14, that is indeed installed on the machine. but visual studio 2017 came with MSBuild version 15.

### Expected result:
MSBuild auto-detection to find MSBuild version 15

### note:
this does not happen on all dev stations, and build agents. temporary fix - we use the specify msbuild version argument.

**Comment by dominoFire** [comment]
Hi @menaheme ,

Hope all is well.

Can you try using the most recent version of nuget.exe (5.1.0) ? 
Can you try an updated nuget.exe version that is closest to you current version (4.9.4) ?

**Comment by menaheme** [comment]
Will try an report back, probably in the next few days

**Comment by menaheme** [comment]
Tried both 4.9.4 and 5.1 , same results as 4.9.3 - picking up MSBuild 14

**Comment by menaheme** [comment]
Anyone there?

**Comment by menaheme** [comment]
why is this still labeled "waiting for customer" ? i posted back 3 weeks ago

**Comment by nkolev92** [comment]
Hey @menaheme, apologies for the delay. 

Is msbuild on your path? 

NuGet will prefer msbuild on the path if available.

**Comment by menaheme** [comment]
MSBuild 14.0 is in the path. MSbuild 15.0 is not

**Comment by nkolev92** [comment]
NuGet will prefer msbuild from the path. 

See https://github.com/NuGet/Home/issues/7621. I don't think there's a bug here.

**Comment by menaheme** [comment]
I agree, the issue should be closed
