### ISSUE TITLE
Minimal VS install has broken NuGet UI

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8414]
Withthe VS 16.3 preview, if you install just the shell, no workloads selected, then run VS, the Package Manager Console can be opened, but the host never finishes initializing. Also, if you go to tools->Options, if you select either of the NuGet pages you get an error.

**Comment by donnie-msft** [comment]
From Jitin John on [DevCom](https://developercommunity.visualstudio.com/content/problem/716176/nuget-package-settings-is-giving-error-without-any.html?childToView=719098#comment-719098):

> What steps will reproduce the problem?
> Open VS 2019 without any solution
> Go to Nuget Package Manager Settings
> What is the expected output? What do you see instead?
> Expected: Settings of nuget sources
> **Actual: An error occurred loading this property page**
> 
> Please provide any additional information below.
> This problem started soon after using VS2019

These are the products installled with VS

> Microsoft Visual Studio Enterprise 2019 Preview Version 16.3.0 Preview 2.0 VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152 Microsoft .NET Framework Version 4.8.03752 Installed Version: Enterprise Application Insights Tools for Visual Studio Package 9.1.00611.1 Application Insights Tools for Visual Studio ASP.NET and Web Tools 2019 16.3.205.56800 ASP.NET and Web Tools 2019 ASP.NET Web Frameworks and Tools 2019 16.3.205.56800 For additional information, visit https://www.asp.net/ Azure App Service Tools v3.0.0 16.3.205.56800 Azure App Service Tools v3.0.0 Azure Functions and Web Jobs Tools 16.3.205.56800 Azure Functions and Web Jobs Tools C# Tools 3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037 C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. Common Azure Tools 1.10 Provides common services for use by Azure Mobile Services and Microsoft Azure Tools. Fabric.DiagnosticEvents 1.0 Fabric Diagnostic Events IntelliCode Extension 1.0 IntelliCode Visual Studio Extension Detailed Info Microsoft Azure Service Fabric Tools for Visual Studio 2.5 Microsoft Azure Service Fabric Tools for Visual Studio Microsoft Azure Tools 2.9 Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20726.1 Microsoft Continuous Delivery Tools for Visual Studio 0.4 Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE. Microsoft JVM Debugger 1.0 Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines Microsoft Library Manager 1.0 Install client-side libraries easily to any web project Microsoft MI-Based Debugger 1.0 Provides support for connecting Visual Studio to MI compatible debuggers Microsoft Visual Studio Tools for Containers 1.1 Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container. NuGet Package Manager 5.3.0 NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/ ProjectServicesPackage Extension 1.0 ProjectServicesPackage Visual Studio Extension Detailed Info Snapshot Debugging Extension 1.0 Snapshot Debugging Visual Studio Extension Detailed Info SQL Server Data Tools 16.0.61907.31040 Microsoft SQL Server Data Tools TypeScript Tools 16.0.10802.2001 TypeScript Tools for Microsoft Visual Studio Visual Basic Tools 3.3.0-beta3-19407-03+d961190a1b4b2a81ac178b567840dfeff048b037 Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. Visual F# Tools 10.4 for F# 4.6 16.3.0-beta.19381.3+8e8a754ab056dc16f6dda49110fe8729d1bbabc9 Microsoft Visual F# Tools 10.4 for F# 4.6 Visual Studio Code Debug Adapter Host Package 1.0 Interop layer for hosting Visual Studio Code debug adapters in Visual Studio Visual Studio Tools for Containers 1.0 Visual Studio Tools for Containers

**Comment by donnie-msft** [comment]
Hit this today (closed as dupe) https://github.com/NuGet/Home/issues/9683

**Comment by dominoFire** [comment]
Workaround: Install one Workload that depends on NuGet component, named `Microsoft.VisualStudio.Component.NuGet`, documented [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2019)

**Comment by zivkan** [comment]
Another instance: https://developercommunity.visualstudio.com/t/error-setting-up-nuget-package-manager/1457437?from=email&viewtype=all#T-ND1459974

From the ComponentModel cache error file:

```text
NuGet.PackageManagement.VisualStudio.NuGetProjectFactory.ProjectServiceAccessor: expected exactly 1 export matching constraints:
    Contract name: Microsoft.VisualStudio.ProjectSystem.IProjectServiceAccessor
but found 0.
   part definition NuGet.PackageManagement.VisualStudio.NuGetProjectFactory
```

We need to ensure that the settings page doesn't need to use the project system APIs, since the .NET project system might not be installed.

**Comment by aortiz-msft** [comment]
@zivkan - Would you please take a look?

**Comment by dominoFire** [comment]
Dupe: https://developercommunity.visualstudio.com/t/Visual-Studio-2019-Community-2019---Nuge/1510763

**Comment by dominoFire** [comment]
Dupe: https://developercommunity.visualstudio.com/t/NuGet-Package-Manger-Setttings-not-avail/1526179

**Comment by dominoFire** [comment]
Reopening since this ticket has the same issue in 17.3

https://developercommunity.visualstudio.com/t/NuGet%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%83%9E%E3%83%8D%E3%83%BC%E3%82%B8%E3%83%A3%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%82%92%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93%E3%81%A7%E3%81%97%E3%81%9F/10164982

**Comment by nkolev92** [comment]
Closing this issue. We'll track the Dev Com one and watch for upvotes there.
