### ISSUE TITLE
Remove net40 support from NuGet.Framework

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8416]
NuGet/NuGet.Client#587 added `net40` as a TFM to `NuGet.Framework`

> This is to support using NuGet 3.x inside of NuGet 2.x (NuGet.Core.dll), which targets net40-client

We no longer support NuGet 2.x, so this can be removed.

to decide: remove in 5.x, or wait for 6.0

**Comment by nkolev92** [comment]
This tends to hit people developing for NuGet. 
We have a net40 and a net45 dependency and both of those can be difficult to download targeting packs for.

In fact that VS installer doesn't provide the option for these 2.

**Comment by nkolev92** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers even calls out that VS 2022 should not be used for development of net45 and net40, it's unsupported. 

cc @drewgillies 

Obv to address the above you'd need to remove NuGet.Packaging.Extraction which is a different discussion.

**Comment by zivkan** [comment]
Closing as a duplicate/subset of https://github.com/NuGet/Home/issues/11830
