### ISSUE TITLE
Suggestion:  NuGet config -list command to list configuration file locations

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8420]
Similar to how [`locals -list` command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-locals#options) lists local paths, it would be handy if a `config -list` command listed [NuGet configuration file locations](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses).

**Comment by nkolev92** [comment]
Adding dotnet.exe label as well. 
IMO, it's ok if we do this in dotnet.exe only.

**Comment by erdembayar** [comment]
> Adding dotnet.exe label as well. IMO, it's ok if we do this in dotnet.exe only.

Related issue `dotnet nuget config` https://github.com/NuGet/Home/issues/10294

**Comment by nkolev92** [comment]
https://github.com/NuGet/Home/issues/4855 has details about that too.

I might close https://github.com/NuGet/Home/issues/4855 in favor of that, as that has higher customer visibility and is really one of very few things left. 
I might also make 4855 an epic :D

**Comment by dainizzz** [comment]
This feature was implemented in https://github.com/NuGet/NuGet.Client/pull/5088, which has been merged.

**Comment by amis92** [comment]
It's not merged to dev, it's not released, and it's hard to know what is the actual status, even though it seems to be assigned to 6.8, I can't run this command on 6.8 (SDK v8 rc1). So what's the status?

**Comment by nkolev92** [comment]
The feature branch is not merged yet, https://github.com/NuGet/NuGet.Client/pull/5158. 
It seems like https://github.com/NuGet/Home/issues/12469 became the tracking issue, as this became part of a larger command. 

cc @martinrrm
