### ISSUE TITLE
[Test Failure][Localization] Deprecated package description strings and the tooltip are not localized

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8421]
## Details about Problem
Implicit NuGet version: NuGet Client Dev\5.3.0.6103
VS Version: D16.3\29201.74
OS: Windows-10-Enterprise-RS5-RU-RU-03-27-2019
## Detailed repro steps
1. Create a C# Console Application (.NET Framework).
2. Open PM UI of this project and click “Settings” button.
3. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json
4. Select the above deprecated package source and search below packages in Browse tab of PM UI.
    afine
    test10k
    ComplexLicense
ComplexLicenseExpressionWithException
5. Click the package in the left panel and check the deprecated package description in the right panel.
6. Hover on the warning icon and check the tooltip.
## Expected
Deprecated package description strings and the tooltip should be localized correctly.
## Actual
Deprecated package description strings (as below) and the tooltip are not localized as below screenshot.

**Deprecated**
This package has been deprecated as it has critical bugs and is no longer maintained.
**Alternate package**
ABC version 4.0.0
![NotLocalized](https://user-images.githubusercontent.com/20632625/62360111-be836400-b54a-11e9-8278-50fae2492b71.png)

## Note
It repro on all non-ENU languages.

**Comment by v-longmin** [comment]
Verify the issue on D16.3\29222.88, only repro on DEU and JAP languages.

**Comment by heng-liu** [comment]
Rob says that you're already working on this.

**Comment by dominoFire** [comment]
Verified on D16.3\29230.54

| StringID |  `dev` branch | `release-5.3.x` branch | Notes |
|----------|-------------|------------|------|
|Label_Installed_DeprecatedWarning | Needs loc. | Needs loc. | The label in the 'Installed' Tab |
|Label_Deprecated | OK | OK | The label on the right panel that says 'Deprecated' |

**Comment by dominoFire** [comment]
I can confirm that both strings are localized. We should await a new build to confirm.

Label_Installed_DeprecatedWarning: 
https://github.com/NuGet/NuGet.Build.Localization/blob/825309c176b04ae124aaf661760ff2c10dd95ef0/localize/ESN/15/NuGet.PackageManagement.UI.dll.lcl#L1399

Label_Deprecated: 
https://github.com/NuGet/NuGet.Build.Localization/blob/825309c176b04ae124aaf661760ff2c10dd95ef0/localize/ESN/15/NuGet.PackageManagement.UI.dll.lcl#L1270

**Comment by v-longmin** [comment]
Verify the issue on D16.3 29305.141, it has been fixed, closed it, thanks!
