### ISSUE TITLE
Perf:  reduce memory allocations in NuGet.ContentModel.Infrastructure

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#8428]
Internal bug [958532](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958532).

**Comment by aortiz-msft** [comment]
@nkolev92 - Do we know how many allocations can be attributed to this issue for our test solutions?

**Comment by nkolev92** [comment]
The original run in https://github.com/NuGet/Home/issues/10843 had this account for 16% of the total allocations. 
We know that it's been improved

We need to get updated #s to see if there's anything else worth tracking.

**Comment by nkolev92** [comment]
This is now being track in more specific scenarios. 
The allocations here have been more than halved since the issue was originally filled.
