### ISSUE TITLE
Fix new SDK 3.0 and MacOS10.14 related issues

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8429]
We locked SDK version 3.0 preview 7 for testing now. If we're going to ship with SDK 3.0 preview 9, we need to : 
1.We have some broken tests to fix when we need to test with SDK 3.0 preview 9.
2.MacOS on agent machine needs to upgrade.

**Comment by nkolev92** [comment]
@heng-liu I think this one is completed, correct?

**Comment by nkolev92** [comment]
I think this has been fixed.

**Comment by heng-liu** [comment]
Sorry, I didn't see it earlier.
Yes. The MacOS 10.14 issues are fixed. The SDK 3.0 has changed to 5.0, and the new issue is https://github.com/NuGet/Home/issues/9029.
