### ISSUE TITLE
dotnet nuget push source does not recognize PSDrive.

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#8431]
_From @VictorioBerra on Tuesday, August 6, 2019 2:57:03 PM_

## Steps to reproduce
- Mount a PSDrive without using `-Persist`
- Try and push a nuget package to it.

## Expected  behavior
It should see it as a file source and just work (tm)

## Actual behavior
I get an error about not providing an API Key as if it were a MyGet server or something.

If I use `-Persist`, the code works just fine.

```powershell
$null = new-psdrive Name "X" -PSProvider FileSystem -root $DeploymentTarget -Credential $cred -ErrorAction Stop;
dotnet nuget push something.nupkg -s "X:\"; # ERROR!!! MISSING API KEY
```

Simply adding `-Persist` will map the share top a drive letter and things work again.

Is there some way around this? I do not want to use `-Persist` on my build server.

_Copied from original issue: dotnet/cli#12155_

**Comment by livarcocc** [comment]
_From @livarcocc on Tuesday, August 6, 2019 5:34:38 PM_

@nkolev92 this seems like a NuGet issue. Should I go ahead and move this to nuget/home?

**Comment by livarcocc** [comment]
_From @nkolev92 on Tuesday, August 6, 2019 5:37:29 PM_

Yeah, feel free to move it. 

NuGet seems to detecting the source type wrong.

**Comment by VictorioBerra** [comment]
Thanks for moving this.

**Comment by zivkan** [comment]
The [docs for `New-PSDrive`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-6) says:

> However, because temporary drives are known only to PowerShell, you cannot access them by using File Explorer, Windows Management Instrumentation (WMI), Component Object Model (COM), or the Microsoft .NET Framework, or by using tools such as Net Use.

Doing a quick test, I can confirm that .NET code, such as nuget.exe, cannot see this drive. Therefore I don't see any way for this to work.

**Comment by VictorioBerra** [comment]
Do you think it's okay practice to persist a mapped network drive just for the ps session on a build server? Im only allowed to pick a single letter right?

**Comment by zivkan** [comment]
That depends very much on your company and team procedures, risk tolerances and so on, so I don't feel comfortable weighing in.

For what it's worth, if you have many packages in the feed, Package Manager UI will have better performance with a NuGet server, rather than a file source. There are several NuGet servers [listed on this docs page](https://docs.microsoft.com/en-gb/nuget/hosting-packages/overview). If you have the opportunity to use a private http feed, then this drive mapping issue goes away.

**Comment by VictorioBerra** [comment]
Thanks! I will discuss with my org. We chose file server over simplicity but its clear it does not scale when you introduce complexity like CI/CD.

**Comment by nkolev92** [comment]
Closing as I believe the question has been answered. 

Thank you for your feedback.
