### ISSUE TITLE
Create docs for new pack validation codes

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8439]
Create docs pages for the pack validations that @JarahSi created.

- [ ] NU5127: Add rule for build in package
  * Spec: none
  * Feature issue: https://github.com/NuGet/Home/issues/8244
  * Feature PR: https://github.com/NuGet/NuGet.Client/pull/2897
  * Docs PR: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1692

- [ ] NU5129: build.props do not match convention warning
  * Spec: https://github.com/NuGet/Client.Engineering/blob/master/Specs/PackageValidation/BuildPropsConventionIsUpheld.md
  * Feature issue: https://github.com/NuGet/Home/issues/8295
  * Feature PR: https://github.com/NuGet/NuGet.Client/pull/2982
  * Docs PR: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1689

- [ ] NU5128, NU5130: Validate dependency groups in nuspec
  * Spec: https://github.com/NuGet/Client.Engineering/blob/master/Specs/PackageValidation/DependenciesInNuspecMatchLibRefFolder.md
  * Feature issue: https://github.com/NuGet/Home/issues/8254
  * Feature PR: https://github.com/NuGet/NuGet.Client/pull/2936
  * Docs PR: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1677, https://github.com/NuGet/docs.microsoft.com-nuget/pull/1686

- [ ] NU5131: Rule: Package uses ref assemblies but no assemblies in ref folder
  * Spec: https://github.com/NuGet/Client.Engineering/blob/master/Specs/PackageValidation/RefAssembliesInNuspecMatchRefFolder.md
  * Feature issue: https://github.com/NuGet/Home/issues/8296
  * Feature PR: https://github.com/NuGet/NuGet.Client/pull/2987 https://github.com/NuGet/NuGet.Client/pull/2995
  * Docs PR: https://github.com/NuGet/docs.microsoft.com-nuget/pull/1693

**Comment by dasMulli** [comment]
Could you move the specs to the wiki so they are publicly accessible?

**Comment by zivkan** [comment]
@dasMulli I've updated the links. Thanks for the reminder. They were supposed to be created in a public place originally.

**Comment by dasMulli** [comment]
I don't mind things being initially worked on privately, I understand that a lot of specs require some critical thinking and iterations before being released as a draft / "RFC". But now when trying to figure out why a pack generates a warning is a bit hard once the implementation shipped 😅 .
