### ISSUE TITLE
Investigate perf of project.json based no-op restore

### ISSUE THREAD

**Issue by Pilchie** [NuGet/Home#844]
Creating a simple solution with a couple of projects (one using `runtimes` and one using `supports`) causes the before build restore to lock up VS for 5-10 seconds on every build (even when all packages are already present and nothing changes).

We should try to optimize this code path, or else move from restore on build to restore whenever a project.json file changes.

@lodejard had some ideas about still restoring on build, but having a "project.json version" global that gets changed when any project.json changes, and only restoring if we are out of date.

Additionally, it would be good if we can avoid writing a new `project.lock.json` file if nothing has changed (hard to detect, I know), because the project system has a watch on `project.lock.json` and kicks off a blocking "IntelliSense build" to update IntelliSense's command line options, and we do *that* on every build too.  CC @jasonmalinowski about this issue.

Also CC @pharring as an FYI about this issue.

**Comment by yishaigalatzer** [comment]
Assigning to @ChengTian to take a first look.

Something else we can do it compare an existing lock file with the project.json and if it matches/and no floating versions found we just need to download missing packages.

**Comment by davidfowl** [comment]
We haven't done any of the optimizations to nuget restore. If nothing changed I'd expect the restore to be sub second per project. We can also avoid writing the file if that saves intellisense from doing a crazy amount of work but I'd expect that to be somewhat incremental.

**Comment by jasonmalinowski** [comment]
Even simple tricks to avoid rewriting the lockfile would be helpful. For example, if right before you write the file out you just see if the file contents are going to be identical, and skip the write, that'd ultimately be a win.

**Comment by pharring** [comment]
Some additional data here: We have a performance test for a Blank UWP application which shows 4.85 seconds of elapsed time (all CPU time), blocking the UI thread on every build. So, it's not necessarily about the file I/O, there's also CPU usage.
e.g.
1,995 ms walking dependencies ```NuGet.DependencyResolver.RemoveDependencyWalker+<FindLibraryEntry>```
1,178 ms computing SHA512 hash called from ```NuGet.Commands.RestoreCommand.CreateLockFileLibrary```

**Comment by davidfowl** [comment]
@emgarten already fixed the SHA512 calls. The 2 seconds spent FindLibraryEntry we can look at.

**Comment by emgarten** [comment]
I've added caching for graph nodes during the walk cut number of calls to FindLibraryEntry.

**Comment by emgarten** [comment]
NuGet will now validate lock files before running an actual restore and displaying the wait dialog. For cases where there are no floating versions and the project.json file hasn't changed this will make the restore a noop for NuGet.

NuGet/NuGet.PackageManagement@7e9030ed2cf89225321aeba1111ec8319bb8926a
NuGet/NuGet.VisualstudioExtension@6b0340016cb518347c5aae7fb072ad99a156f752

**Comment by emgarten** [comment]
The current fixes avoid calling restore for most scenarios, but for scenarios where we do restore and the lock file is identical we can still avoid writing the lock file out in some scenarios if it is the same as @jasonmalinowski suggested. 

I'll add a change for this which should help the rebuild and first build scenarios. For the first build we have to restore since there isn't a way to know from the lock file what project to project closure the lock file was built against until we have stored it in memory.

**Comment by emgarten** [comment]
NuGet/NuGet3@faa5ce81965f37cfc5456792bc165a0c16e54cfb
