### ISSUE TITLE
Lock file missing entries when RuntimeIdentifier is specified for netcoreapp 3.0 projects

### ISSUE THREAD

**Issue by bergbria** [NuGet/Home#8442]
## Details about Problem

NuGet product used: dotnet.exe

dotnet.exe --version: 3.0.100-preview7-012821

Worked before? If so, with which NuGet version: yes. Seems to work even with current sdk if targeting netcoreapp2.0

### Automated repro
Download [repro_missingRuntimePackage.zip](https://github.com/NuGet/Home/files/3488060/repro_missingRuntimePackage.zip) and run repro.bat for an automated repro.

### Manual steps

1. Create a basic .csproj targeting netcoreapp3.0

2. Add `<RuntimeIdentifier>win-x64</RuntimeIdentifier>`

3. `dotnet restore --use-lock-file`

4. Notice that the generated lock file has no packages in it even though the build actually uses several (e.g. microsoft.netcore.app.runtime.win-x64)

This is a regression from netcoreapp2.0, which listed all packages as expected.

Tagging @rrelyea and @nkolev92 as FYI.

**Comment by nkolev92** [comment]
This is a consequence of the whole PackageDownload implementation, https://github.com/NuGet/Home/wiki/%5BSpec%5D-PackageDownload-support. 

Tracking issue: https://github.com/NuGet/Home/issues/7724. 

Platform artifacts are not always declared in project files anymore and they do not get downloaded through PackageReference, but rather PackageDownload. 

There's no locking mechanism in place for that right now. 

//cc @anangaur

**Comment by nkolev92** [comment]
Closing this per the above comment.

**Comment by bergbria** [comment]
@nkolev92 / @anangaur - is the lack of locking mechanism considered a bug that will be fixed before netcore3.0 is officially released or is it a 'meh, maybe sometime' issue?

**Comment by nkolev92** [comment]
@bergbria 
We consider this an important scenario and we'd like to fix, but 3.0 is almost fully on lockdown, so we cannot commit to fix it before that happens.
