### ISSUE TITLE
Make NuGet.CommandLine.XPlat debuggable

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8448]
Historically it has been very difficult to debug NuGet.CommandLine.XPlat (the entry point to several `dotnet` cli commands), involving copying compiled binaries into a dotnet sdk folder, setting an environment variable to cause NuGet to pause until a debugger is attached, and then attaching Visual Studio as a debugger to the correct PID.

It should be as easy to debug as debugging any other command line program.

**Comment by zkat** [comment]
This would be AMAZING
