### ISSUE TITLE
During restore for build integrated projects, we show the dialog even if there are no packages to restore

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#845]
For UAP projects, package restore operation should support user cancellation by honoring the CancellationToken

Repro steps

1. Create a UAP project
2. Clean and build the project created in Step-1
3. Make sure that all the packages are already restored

Expected:
No dialog is shown and package restore opt out message is not shown

Actual:
A dialog shows up and package restore opt out message is always shown

**Comment by emgarten** [comment]
NuGet will now validate lock files before running an actual restore and displaying the wait dialog. For cases where there are no floating versions and the project.json file hasn't changed this will make the restore a noop for NuGet.

NuGet/NuGet.PackageManagement@7e9030e
NuGet/NuGet.VisualStudioExtension@6b03400
