### ISSUE TITLE
Remove .NET Framework TFM from NuGet.CommandLine.XPlat

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8452]
NuGet.CommandLine.XPlat is intended to be used only by the dotnet cli, although searching github we can find multiple customers who use it and call our `Program.Main()` in their code. I can't verify that all existing usage is used by netcoreapp projects, so we'll wait until the next major release before removing the .NET Framework TFM.

**Comment by nkolev92** [comment]
Honestly, I'd be comfortable removing this sooner rather than later. 
It'd save us some build/signing time, and the download counts are so low that it suggests not a lot of people use it.

**Comment by zivkan** [comment]
I now think the .NET SDK in VS uses the net472 binaries. I don't think we can remote the TFM from the project.

**Comment by nkolev92** [comment]
In which scenarios?


That's only used for `dotnet nuget` commands, and those can't be run through VS.

**Comment by zivkan** [comment]
You're right. the VS scenarios are probably only build and pack, both of which are msbuild and don't use NuGet.CommandLine.XPlat.  Still, we should check that the SDK's build scripts don't break if our package doesn't contain net472 assets.

**Comment by nkolev92** [comment]
This was done by @jeffkl in https://github.com/NuGet/NuGet.Client/commit/1501b1a46dc2528912b8a8280a2b2696d7f29fe9.
