### ISSUE TITLE
No dependencies in Nuget.Protocol API for PackageSearchResource

### ISSUE THREAD

**Issue by CodeIsLie** [NuGet/Home#8462]
I use Nuget.Protocol 5.2.0 to investigate some features of Nuget dependency graph and i write next code:
```C#

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using NuGet.Common;
using NuGet.Configuration;
using NuGet.Protocol.Core.Types;
using NuGet.Protocol.VisualStudio;

namespace NuGetApiInvestigation
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var visStudio = Repository.Provider.GetVisualStudio();
            var packageSource = new PackageSource("https://api.nuget.org/v3/index.json");
            var sourceRepository = Repository.CreateSource(visStudio, packageSource);
            var packageSearchResource = await sourceRepository.GetResourceAsync<PackageSearchResource>();
            
            var searchAsync = await packageSearchResource.SearchAsync("", new SearchFilter(false), 0, 500,
                NullLogger.Instance, CancellationToken.None);
            foreach (var metadata in searchAsync)
            {
                Dictionary<string, int> usages = new Dictionary<string, int>();

                foreach (var dependencySet in metadata.DependencySets)
                foreach (var dependency in dependencySet.Packages)
                {
                    usages[dependency.Id] += 1;
                }
            }
        }
    }
}
```

And I realize that i don't get any dependencySet that way. Of course, i can use PackageMetadataResource to get dependencies for each package, but it took too many time for 500+ packages. Is it possible to get dependencies in package metadata by using PackageSearchResource? I mean, maybe there is exist some flag or PackageSource for this purpose?

**Comment by nkolev92** [comment]
The PackageSearchResource hits https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource which doesn't contain dependency information. 

The metadata resource hits https://docs.microsoft.com/en-us/nuget/api/registration-base-url-resource which contains all that information. 

The IPackageSearchMetadata API is returned by all "query" resources. 

Basically you have to use PackageMetadataResource if you want the dependency information.
