### ISSUE TITLE
Azure DevOps Nuget login fail on Mac

### ISSUE THREAD

**Issue by skir** [NuGet/Home#8468]
## Details about Problem

NuGet version: 5.1.0.6013
VS: Visual Studio Community 2019 for Mac Version 8.2.3 (build 16)
OS version: Mac OS 10.13.6

## Detailed repro steps

In our company we use local Azure DevOps (TFS) with set up for automatic builds and publishing NuGet packages to our private repository. 
To login we usually use TFS credentials, but this works only on WIndows machines.
I use Mac and I could not login using my TFS credentials. I tried this [tutorial](https://docs.microsoft.com/en-us/azure/devops/artifacts/get-started-nuget?view=azure-devops) for generating and using personal access token. And this actually worked for a short period of time. 
There were several updates installed for Visual Studio. But I don't know which one caused the problem, as I was temporarily using my Windows machine for another project.
I tried to downgrade nuget.exe with no success.

**Comment by rrelyea** [comment]
As of [NuGet 4.9](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-4.9-rtm), we've enabled xplat credential providers. 
The Azure Dev Ops team provides an installable artifacts-credential provider: https://github.com/Microsoft/artifacts-credprovider

Would using that solve your problem?

**Comment by skir** [comment]
Yes, I tried to use that artifacts-credential provider, but with no success.

Actually, today I came in to the office and this problem is gone. It is definitely the same setup on my Mac, and on our TFS server, as it was yesterday, when the issue was present. It's strange.

**Comment by rrelyea** [comment]
Glad things appear to work well. If you find things that are indicative of a NuGet bug, please re-raise the issue.
