### ISSUE TITLE
Change logging methods of ILogger and INuGetProjectContext to be async. Needed by the VS client

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#847]
Change logging methods of ILogger and INuGetProjectContext to be async. Needed by the VS client

Currently, the logging methods are sync methods. For the VS client, which might be updating a progress dialog or writing to output window, the logging methods would block the calling thread and switch to the UI thread to log messages. This is far from ideal. If the methods are async, we could switch to UI thread asynchronously

**Comment by yishaigalatzer** [comment]
We probably want to change how logging works all up, so the work to log can never be expensive. Not sure async is the right way to go.
