### ISSUE TITLE
 [Test Failure] The ‘Update’ button is disabled in ‘Installed’ tab on PM UI

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#8483]
## Details about Problem

NuGet Version: Dev\5.3.0.6182
VS Version: VS Master\29221.49
OS Version: Windows-10-Enterprise-19H1-04-01-2019

## Installation steps: 
1. Install VS from: [https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2963681&view=results](url)
2. Install NuGet Client: [\\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\Dev\5.3.0.6182\artifacts\VS15\NuGet.Tools.vsix](url)

## Repro steps: 

1. Create a C# Console App (.NET Framework) Project.
2. Open PM UI and install ‘NUnit’ with an older version.
3. Navigate to ‘Installed’ tab and observe the package ‘Nunit’.

## Expected:
The ‘Update’ button is available and the ‘available update’ tag is shown under package icon as below. 
![expected](https://user-images.githubusercontent.com/20632775/63503916-028ed680-c503-11e9-8f7b-fd8dda476468.png)

## Actual:
The ‘Update’ button is disabled and the ‘available update’ tag was missed as below.
![actual](https://user-images.githubusercontent.com/20632775/63504212-a082a100-c503-11e9-85b0-c6736d098eab.png)

## Notes: 
1. The issue **not** repro on VS Master\29221.49 with implicit NuGet Client Dev\5.3.0.6167.
2. The issue repro on solution PM UI.
3. The issue repro on other projects.

**Comment by nkolev92** [comment]
Hey @v-nancyj 

I was not able to repro this with latest VS and the 5.3.0.6182. 

Can you try retesting to see if it was some ambient state, like nuget.org being unreachable etc. 

Another question about the repro, when you say install packages, do you select a packages.config or PackageReference project?
Both have significant differences, so it'll be helpful to get such information in the repros.

**Comment by v-nancyj** [comment]
Hi, @nkolev92 We can still repro this on VS Master\29222.30 + NuGet Client Dev\5.3.0.6189 and D16.3\29222.88 + NuGet Client Dev\5.3.0.6189.
1. The issue repro when installing a package on both Packages.config and PackageReference format.
2. The issue repro on other projects, such as .NET Core, .NET Standard or UWP Project.
3. The issue **not** repro in 'Browse' or 'Updates' tab.
4. The issue **not** repro after uninstalling the latest NuGet version(Dev\5.3.0.6189).
I record a video for the steps on the repro machine, you could see the detail as below.

![video](https://user-images.githubusercontent.com/20632775/63581287-4b10c780-c5c9-11e9-9f3b-62f87b780f3f.gif)

**Comment by nkolev92** [comment]
Thanks @v-nancyj 
I can repro this now.
