### ISSUE TITLE
Compat check / Runtime.json does not consider version

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#849]
Let’s suppose that a particular vendor wants to implement a version of contract package A version 3.7 and associate that via runtime.json. They implemented the behavior as of 3.7, but may not work with future versions of A (3.7.1, 3.8, 4.5, etc).

Currently we’ll permit their old version to satisfy the compatibility check and there is no way for them to restrict the association via runtime.json to a specific package version.

I’m thinking that we might want to allow a versioned association in runtime.json and have that treated as a ceiling for the association. 

An alternative to this would be to check the assembly versions.  The binder will permit higher impl versions to load but not lower versions.
/cc @anurse @davidfowl

**Comment by yishaigalatzer** [comment]
Sounds pretty awful, limiting versions upfront sounds pretty bad. And in the case a vendor worries about this scenario, why wouldn't he put the runtime.json in A or re-ship A.

I fail to see how this is critical for RTM

**Comment by ericstj** [comment]
Sometimes folks won't be able to reship due to platform limitations or schedule/cost/etc. The way nuget3 works today, restore will permit mismatched compile/runtime assemblies and developer won't know until he runs on that platform and sees the loader error for ref/def mismatch.  We may not need this for dev14 RTM, but we will need it as we start to bring up cross-plat and third parties start trying to extend packages.

**Comment by davidfowl** [comment]
Sure we're not going to do this for rtm. We'll revisit later.

**Comment by yishaigalatzer** [comment]
@ericstj how critical do you think this thing is? I can see that a vendor shipping a newer version of a package being able to update the runtime dependency to empty or not shipping a new version.

Wondering if we should abandon this until we hit a real user scenario?

**Comment by ericstj** [comment]
It's actually essential for the generations plan to work.  We're going to have cases were Desktop needs to claim a new generation in order to expose the latest STDLIB API, but this may require dropping support for some non-STDLIB package (eg: System.XML).  See https://gist.github.com/ericstj/e250c76b23622f486f1e.

**Comment by nkolev92** [comment]
This is not a public feature anyore, right?
Closing now.
