### ISSUE TITLE
Inconsistent authoring model for inside package vs runtime.json

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#850]
Rutime.json does not support the ability to constrain a package:package association by target moniker but convention based layout within a single package does.

In other words, I can express a file as 
runtimes\myRuntime\lib\dnxcore50\mylib.dll

But I cannot do the same thing if I want to ship mylib.dll in another package.  Combine this with the fact that you can't have multiple runtime.jsons define a match for package X on runtime RID and you prevent folks from creating runtime associations for two different target monikers on the same RID.
/cc @anurse @loudej

**Comment by yishaigalatzer** [comment]
runtime.json is no longer a feature for the public

**Comment by nkolev92** [comment]
Closing as redundant.
