### ISSUE TITLE
Automaticaly load pdb from NuGet global packages folder

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8503]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/702430/automaticaly-load-pdb-from-nuget-cache.html)._

---
<p>Hi, it looks Visual Studio does not support loading pdb from NuGet Cache.</p><p>Is it possible to improve VS this way.</p><p>In detail: Let's e.g. assume having NuGet Package unpacked in the NuGet cache and the dll and pdb resides in the packagename\packageverlib\netstandard2.0 sub-folder. Visual Studio then supports probing the path to this sub-folder for loading the package source symbols. </p><p>This will help debugging experience source code with own only local stored NuGet packages.</p>

---
#### Jane Wu [MSFT] on 8/21/2019, 04:11 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by rychlym** [comment]
Hello,
I have tried to prepare the source code example(s) with small NuGet packages supposed to be stored in an offline NuGet repository. 
Please follow the steps from the ReadMe.txt file inside of the attached package file.  Finally (the step 4 in the ReadMe.txt) you end up with not loaded pdb for the library.

![image](https://user-images.githubusercontent.com/11144487/64010791-c2d77880-cb1a-11e9-9dab-4f077d104199.png)
[OfflineNugetPackageExample.zip](https://github.com/NuGet/Home/files/3559332/OfflineNugetPackageExample.zip)

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/5926.
