### ISSUE TITLE
PM UI - the details tab does not get loaded when on the browse tab

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8504]
1.Get the latest preview bits of Visual Studio. 
1. Open a project
1. open the pm ui. 
1. go to the browse tab
1. click on any selection
1. notice that the details metadata does not get loaded. 

The same doesn't happen on 16.2 latest, so it's a regression within this release. 

//cc @rrelyea

**Comment by donnie-msft** [comment]
Duplicate issue here, but may have useful repro details/screenshot: https://github.com/NuGet/Home/issues/8523

**Comment by scottbommarito** [comment]
I have not been able to reproduce this on my machine unfortunately. It always loads correctly. It might be related to some system configuration?
