### ISSUE TITLE
UI delay when loading icon URLs in PM UI

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#8505]
When loading icons, there's a lookup operation that causes an UI delay in the main thread.

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/487404/

Tasks:

- Find out if `BitmapImage`/`BitmapSource` has thread affinity to WPF UI threads

Possible solutions:

- Backgorund, non-UI thread on the converter for loading the image
- Convert IconUrl to an async, non-UI threaded property

**Comment by rrelyea** [comment]
fixed in 16.9
