### ISSUE TITLE
msbuild /restore works with Packages.Config

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#8506]
Spec: [Backporting PC to msbuild /restore](https://github.com/NuGet/Home/wiki/Backporting-PC-to-msbuild--restore)

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): msbuild

NuGet version (x.x.x.xxx): current

## Tracking issues

* [x] Get the code working in usual scenarios #8676
* [x] Write E2E tests: #8677
* [x] Refactor into shared code #8678

## Detailed repro steps so we can see the same problem

1. Create a P.C project

2. Try to restore using `msbuild /restore`

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6410 maybe. 

I think that's the original ask and we should probably dup this one out for that one, or least make sure they're both closed when this is fixed.

**Comment by anangaur** [comment]
@jeffkl Where is this documented?

**Comment by jeffkl** [comment]
I’m not sure, did you document this @zkat?

**Comment by rrelyea** [comment]
tracked as a doc issue linked on the bottom of this page: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets?source=docs#feedback

**Comment by anangaur** [comment]
Whats the option though?

**Comment by rrelyea** [comment]
it is in the title of the issue:

![image](https://user-images.githubusercontent.com/8865080/79491894-fbf22980-7fd3-11ea-930c-6b7d23d97aeb.png)

**Comment by anangaur** [comment]
👍 I should have clicked on the link! 😅

**Comment by asklar** [comment]
@zkat @rrelyea is there a way to specify the file if I want it to be different than packages.config? In my case I have to support a project in two different "modes"/"configurations" that rely on separate nuget packages.

**Comment by nkolev92** [comment]
@asklar 
Not really. 
packages.config discovery only works by convention, so either `packages.config` next to the project file or `packages.$(MSBuildProjectName).config` next to the project.

**Comment by anangaur** [comment]
I always forget `packages.$(MSBuildProjectName).config`. Is this documented somewhere?

**Comment by rrelyea** [comment]
i searched our docs a bit...but didn't find it. you would think it could be listed here: https://docs.microsoft.com/en-us/nuget/reference/packages-config

**Comment by asklar** [comment]
@nkolev92 @rrelyea I was trying to stick myself in the middle to redirect to a different file and I can see the value of the itemgroups are getting updated successfully but the Restore task seems to ignore it, any idea how I may be able to work around it?
```xml
  <Target Name="FixUpPackagesConfigPath" DependsOnTargets="_GenerateRestoreProjectSpec" BeforeTargets="Restore" Returns="@(_RestoreGraphEntry)" >
    <ItemGroup>
      <_RestoreGraphEntry 
        Condition="'%(_RestoreGraphEntry.PackagesConfigPath)' != ''">
        <PackagesConfigPath>$([System.String]::Copy('%(_RestoreGraphEntry.PackagesConfigPath)').Replace('packages.config','packages.WinUI3.config'))</PackagesConfigPath>
      </_RestoreGraphEntry>
    </ItemGroup>
  </Target>
```

**Comment by asklar** [comment]
@nkolev92 @rrelyea hmm is [this code](https://github.com/NuGet/NuGet.Client/blob/3803820961f4d61c06d07b179dab1d0439ec0d91/src/NuGet.Core/NuGet.PackageManagement/Projects/PackagesConfigNuGetProject.cs#L74) it?
Why is the nuget task not respecting whatever it gets from msbuild? it'd be great if this could be fixed :)

**Comment by rrelyea** [comment]
Gen 1 of nuget uses Packages.Config.
It likely didn't use msbuild to find the config file...so the options are limited.
Can you solve in a more mainline way? (something that works with this code from 2015 and before?)
