### ISSUE TITLE
Nuget ignores dependency constraints

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#851]
If a package specifies an upper bound for a dependency nuget is ignoring that.  We had previously agreed that this needs to be an error (potentially suppressible).  The same seems to be true if nearest wins algo chooses a lower verson than that requested by a package.

These types of errors will result in runtime failures (MissingMethodException, TypeNotFound, etc).  I understand you are trying to empower and unblock the app developer to do what they want, but we can't make it so easy to shoot yourself in the foot.

We must have a mode where nuget errors in these circumstances.
/cc @anurse @davidfowl

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/NuGet/NuGet3/issues/72
