### ISSUE TITLE
 [Test Failure] VS hung when reoloding solution after adding a NuGet.Config file with parsing errors 

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#8510]
## Details about Problem
NuGet Version: Release-5.3.x\5.3.0.6197
VS Version: VS D16.3\29227.100
OS Version: Windows-10-Enterprise-19H1-04-01-2019

## Installation steps: 
1. Install VS from: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2982864&view=results
2. Install NuGet Client: [\\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\release-5.3.x\5.3.0.6197\artifacts\VS15\NuGet.Tools.vsix](url)

## Repro steps: 

1. Create a solution with at least 1 project (something like WPF).
2. Create a NuGet.Config file having below parsing errors next to the sln file.
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="NuGet.org" value="https://api.nuget.org/v3/index.json" />
    <add key="NuGetVolatile" value="https://dotnet.myget.org/F/nuget-volatile/api/v3/index.json" />
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="dotnet-buildtools" value="https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json" />
    <add key="dotnet-roslyn" value="https://dotnet.myget.org/F/roslyn/api/v3/index.json" />
    <add key="cps" value="https://vside.myget.org/F/devcore/api/v3/index.json" />
    <add key="dotnet-msbuild" blalblasda="https://dotnet.myget.org/F/msbuild/api/v3/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
</configuration>
```
3. Reload the solution.
4. Click ‘OK’ button after the below error dialog pops up.
![Untitled picture](https://user-images.githubusercontent.com/20632775/63846368-3c0d8900-c9be-11e9-9869-0a989570a217.png)

(I record a video for the repro steps as below)
![vshang](https://user-images.githubusercontent.com/20632775/63846356-33b54e00-c9be-11e9-8307-9fac30636acb.gif)

## Expected:
VS will not hang after clicking the ‘OK’ button on error dialog.

## Actual:
VS hung after clicking the ‘OK’ button on error dialog.

## Notes: 
1. The issue repro on VS Master branch.
2. The issue is not stable, the repro rate is almost 80%.

**Comment by heng-liu** [comment]
Assigning to 5.3 milestone for consideration.

**Comment by v-nancyj** [comment]
Verified this issue on VS D16.5\29814.53 with implicit NuGet Client Dev\5.5.0.6422, it has been fixed, close it.
