### ISSUE TITLE
Running msbuild t:restore,build in one step does not add dlls in output

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8511]
@scorpionlion commented on [Mon Aug 19 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1642)

I was expecting same behaviour as would be for dotnet build , where it calls dotnet restore by default and copies all required package dlls in output. But when calling these two targets in one step, the build step does not find the project.asset.json file and does not copy some of the files due to the target CopyOutofDateSourceItemsToOutputDirectory does not get called (as I understood). It took me a while to figure out why some dlls were not getting copied to the output and at deploy time execution was failing.
As a workaround  calling msbuild t:restore and msbuild t:build in two steps works.

**Comment by nkolev92** [comment]
Maybe this? 

https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-and-building-with-one-msbuild-command

**Comment by nkolev92** [comment]
Closing as question. This thing is documented right now.
