### ISSUE TITLE
Bug 959482: [PerfWatson] UIDelay

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#8514]
microsoft.visualstudio.languageservices.dll!Microsoft.VisualStudio.LanguageServices.Packaging.PackageInstallerService+<>c__DisplayClass_0+<<OnWorkspaceChanged>b__>d.MoveNext|nuget.packagemanagement.visualstudio.dll!NuGet.PackageManagement.VisualStudio.VsProjectAdapter.GetTargetFrameworkStringAsync

Linked to ADO bugs 959482,961012

**Comment by nkolev92** [comment]
You don't really need to duplicate these issues. Having them in ADO is probably fine.
