### ISSUE TITLE
Solution PM UI - Deprecation warning icon has issues

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8516]
![image](https://user-images.githubusercontent.com/2878341/63895701-bc26f500-c9a4-11e9-91c3-08f27f91c915.png)

1. Create a solution with 1 project.
1. Install a deprecated package.
1. Open the solution level PM UI
1. Go to the installed tab.

You will see that the installed label has a warning icon, but in the packages list you cannot distinguish visually which package is deprecated. This is an issue. 

Note that this is not an issue on the project level PM UI. 

![image](https://user-images.githubusercontent.com/2878341/63895798-0c9e5280-c9a5-11e9-9eef-2024bebb9fe5.png)

This leads to an underwhelming experience, that I believe we should fix before shipping. 

//cc @rrelyea @anangaur @xavierdecoster @scottbommarito @NuGet/nuget-client

**Comment by scottbommarito** [comment]
How to disambiguate this view is a question for @anangaur.

As an easy option, we could consider removing the warning icon for the solution. Alternatively, we could show the warning icon in the list of versions on the right.

**Comment by anangaur** [comment]
In this case the warning icon could be aligned to the package name with tooltip stating: “The package version(s) were deprecated. Refer to the project list to know where the deprecated versions are being referenced”.

In addition, the warning icons should be shown alongside the versions installed per project on the right hand side.

**Comment by scottbommarito** [comment]
@anangaur - could you quickly mock-up a screenshot with the icons in the right place? It's not entirely clear to me where you'd like to put the icons from your description.

**Comment by scottbommarito** [comment]
Discussed offline with @anangaur and @rrelyea. We would like to do the following changes in 5.3 to improve the situation, but some additional improvements in 5.4 are likely.

For now, we'd like to:
- Add the warning icon in the list on the left-side pane and hide the latest version icon if the package is both deprecated and installed
- To the dropdown list of versions on the right-side pane, add a warning icon or "(deprecated)" text to indicate which versions are deprecated.
