### ISSUE TITLE
[Accessibility] Tab navigation skips certain PackageDetails metadata causing it to be missed by narrator

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8517]
Found while testing the new deprecated metadata. 

Note that  the description metadata gets skipped as well. It only goes to the information that's hyperlinked.

This is not a regression but just discovered due to it.

**Comment by rrelyea** [comment]
I did fix a bunch about the deprecation accessibility. (5.5) it did have problems. 

However, this issue itself is ok.
it is ok for non-controls to not be tab focusable. Reading mode in narrator (and other tools) drills into the content and reads more stuff.
