### ISSUE TITLE
TelemetryUtility.CreateFileAndForget name should indicate that it is in fact a file and forget name

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8519]
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Common/Telemetry/TelemetryUtility.cs#L10

Right now we end up with even names such as: 

`vs/nuget/pvspackagerestoremanager/onnugetprojectadded`. 

This would make it difficult to just categorize all of our file and forget failures. 

I think that it might be useful for all these events to get prefixed somehow, so that we can isolate them from our regular events. 

Thoughts @dtivel?

If we think that's the case, we should do it soon, if not close it :)

**Comment by dtivel** [comment]
Was that backslash in your example intentional?  I expect only forward slashes.

Sure, how about:  `vs/nuget/fileandforget/...' or something like that where 'vs/nuget/' is still the prefix.

**Comment by nkolev92** [comment]
It was a typing error :) 

That's what I had in mind as well. 

I'll talk to @rrelyea about which release we want this in.
