### ISSUE TITLE
PCL guardrails does not seem to be honoring runtime.jsons

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#852]
When guardrails evaluates compatibility for a specific TxM:RID pair it does not seem to be checking for runtime.json files that may be included by the TxM specific package graph.

Use the feed: https://www.myget.org/F/dotnet-core/

To repro use the following project:
```
{
  "supports": {
    "net46.app": { },
    "uwp.10.0.app": { }
  },
  "dependencies": {
    "Microsoft.NETCore" :  "5.0.0-beta-23024"
  },
  "frameworks": {
    "dotnet": {}
  }
}
```
This will fail the compatibility check for System.Runtime.Serialization.Primitives 4.0.0.  The reason this is failing is because the guardrails resolution is not pulling in the UWP lineup runtime.json from Microsoft.NETCore.Targets.UniversalWindowsPlatform

Now compare this to explicitly resolving the same set of dependencies against the TFM:RID pairs that were failing.
```
{
  "dependencies": {
    "Microsoft.NETCore" :  "5.0.0-beta-23024"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {},
    "win10-arm": {},
    "win10-arm-aot": {}
  }
}
```
This succeeds and brings in the runtime.json for Microsoft.NETCore.Targets.UniversalWindowsPlatform.

**Comment by ericstj** [comment]
PCL is hitting this when targeting DNXCore50 as well and that is not so easy to workaround.  It can be done manually but involves hand editing project.json and setting up a feed to point to the installed pacakges.  Not something we can ask partners to do.

**Comment by emgarten** [comment]
https://github.com/NuGet/NuGet3/commit/08e323da237238bcb980ec1acd7f6d05a8d2199c
