### ISSUE TITLE
The cursor in PMC is hard to spot in the light & blue themes

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8521]
The PMC cursor is hard to spot in the light and blue themes.

Not a regression. 

![image](https://user-images.githubusercontent.com/2878341/63903302-d7ecc400-c9c1-11e9-9377-5e4a7a295a76.png)

**Comment by v-luzh** [comment]
@nkolev92, is that same with the bug #8119? We can only repro this issue when changing the color theme after building solution.

**Comment by nkolev92** [comment]
@v-luzh Yeah it's a dup. Nice catch!

Pretty much consistently repros as long as VS is not restarted.

Closing as duplicate of https://github.com/NuGet/Home/issues/8119
