### ISSUE TITLE
The source at nuget.org is unreachable.

### ISSUE THREAD

**Issue by markwingfield-micro-p** [NuGet/Home#853]
Trying to install a package & getting "The source at nuget.org [https://www.nuget.org/api/v2/] is unreachable. Falling back to NuGet Local Cache at ..."

Package Manager Console Host Version 2.8.60318.667
Using VS 2012 (v 11.0.61030.00 update 4)

**Comment by maartenba** [comment]
Still seeing this issue?

**Comment by markwingfield-micro-p** [comment]
Hi Maarten .. yes

Not had a problem until recently

Thanks

 



 

 

 

-

 

Mark Wingfield

Web Developer

 

T              +44 (0) 1256 707070

DD          +44 (0) 1256 774113

E              mark.wingfield@exertis.co.uk

W            www.exertis.co.uk

**Comment by maartenba** [comment]
Can you browse to the URL in your browser?

**Comment by markwingfield-micro-p** [comment]
hi ... yes - i get

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://www.nuget.org/api/v2/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
</workspace>
</service>

**Comment by maartenba** [comment]
Is there a proxy involved? Or Fiddler started when Visual Studio was started?

**Comment by markwingfield-micro-p** [comment]
no, i'm on the business network .. firewall etc etc ... but not had a problem before.   No one else has reported any issues then?

**Comment by maartenba** [comment]
No not have had other reports. Could you try from another machine?

**Comment by markwingfield-micro-p** [comment]
I'm the only .Net developer in the building ... surrounded by PHP devs!! no VS installed anywhere else.
I'm getting in touch with .net devs in a different office ....

What would you expect to see if you hit the URL in a browser, same XML as above?

**Comment by maartenba** [comment]
Yeah the XML is what you're expected to see. If you append /Packages to the URL, a page of packages should show.

**Comment by markwingfield-micro-p** [comment]
Thanks for your help ... not resolved yet - but it does look like it's an internal issue.
Have a good weekend

**Comment by maartenba** [comment]
Likewise!
