### ISSUE TITLE
Automapper 8.1.1 returns nu3008 error

### ISSUE THREAD

**Issue by wmhhayes** [NuGet/Home#8530]
We are seeing a nu3008 error for Automapper 8.1.1 in our local nuget repository. 
![automapper error nu3008](https://user-images.githubusercontent.com/45670667/64037628-aee04680-cb1b-11e9-8d6c-07b270e09fe3.png)

 I have deleted the local copy and downloaded again from https://www.nuget.org/packages/AutoMapper/8.1.1 with no change.

We are seeing that the last modification date  for the package file was 2019-06-03 18:33:32 GMT. Earliest modification date for the package archive was 2019-06-03 11:35:14 GMT. Our local copies state that it was digitally signed 6/3/2019 1:35:14 PM.  

[AutoMapper.8.1.1.zip](https://github.com/NuGet/Home/files/3560780/AutoMapper.8.1.1.zip)

Does a correctly signed copy of 8.1.1 exist in the nuget repository?

**Comment by rrelyea** [comment]
You've seen the docs on NU3008?
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3008

**Comment by rrelyea** [comment]
I've just verified that a .net framework console project can install that package from nuget.org on VS 16.3 preview 3 internal bits w/ no verification problem.
I've also run "nuget.exe verify -signatures <filename>" on the .nupkg after it was downloaded -- and that suceeded.

**Comment by nkolev92** [comment]
Closing as I believe this issue has been addressed. 

Thank you for your feedback.

**Comment by wmhhayes** [comment]
Yes,  Thanks!  Thought I had closed it myself some time ago.

Best wishes,

William Hayes
Information Systems Security Analyst | Security
William.Hayes@saionline.com<mailto:William.Hayes@saionline.com>

Securities America
12325 Port Grace Blvd. • La Vista, NE 68128
LinkedIn<https://www.linkedin.com/company/securities-america-inc/> | Facebook<https://www.facebook.com/SecuritiesAmericaInc/> | Twitter<https://twitter.com/SecuritiesAm?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor> | YouTube<https://www.youtube.com/channel/UCVTQzmhfsipUqUjWAXnvKZQ> | Instagram<https://www.instagram.com/securitiesamerica/> | Website<https://www.securitiesamerica.com/>
