### ISSUE TITLE
I can't comment or edit my existing comment on #7309

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#8539]
I'm trying to add a comment of 
>Instead of the Browse tab it would be great if it defaulted to a Recent tab that showed the 50 most recent packages installed, or a Most Used with the 50 packages I install the most.

But it's giving me
![Screenshot_20190831-075133](https://user-images.githubusercontent.com/15381181/64063738-5ade6c00-cbc6-11e9-8ff0-958958303228.png)

If someone could incorporate that feedback into #7309 it would be appreciated.

**Comment by heng-liu** [comment]
Append the comment into #7309. Closed as duplicate.
