### ISSUE TITLE
Using NuGet with Static Linux Binaries

### ISSUE THREAD

**Issue by AlphaCluster** [NuGet/Home#854]
So we are using NuGet currently as a way to manage our static windows Visual C++ libraries but we want to also build up the same libraries in such a way that they can be consumed via NuGet on Linux. I have been having some issues with this and basically it has lead to some workarounds that I feel are less then ideal.

The main thing is I would like to treat a Linux static library the same way I am treating a Windows static library and leverage the build folder. Is there a way to do this? I have tried using content but that ends up adding the NuGet contents to the solution which we really don't want. When I used the build folder it packages fine build when I grab the package I get an error saying it cant fine a native library. 
> You are trying to install this package into a project that targets 'native, Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by davidfowl** [comment]
Can you add some more context here? What do you mean on linux? What client are you using?

**Comment by AlphaCluster** [comment]
I am using the VS Client to test the install cause we are writing the code in Visual Studio. Also planning to leverage the mono provided client but i haven't even got to that point yet.

As for linux i am talking about packing up linux archives so .a static libraries. I already have some binaries and the include files VS just rejects the package outright. Mostly I would like for them to live in something like build\rhel\lib or build\rhel\include.

**Comment by davidfowl** [comment]
> Also planning to leverage the mono provided client but i haven't even got to that point yet.

What client? Are you talking about xamarin studio?

> As for linux i am talking about packing up linux archives so .a static libraries. I already have some binaries and the include files VS just rejects the package outright. Mostly I would like for them to live in something like build\rhel\lib and build\rhel\include.

Is the package linux specific or does it support multiple platforms? The moniker for native projects in visual studio is "native" so you can't just make up random sub folders and expect VS to be happy. 

What do you do today for the windows packages?

**Comment by AlphaCluster** [comment]
For Linux I have been using the xamarin provided one via the mono docker image. (This works fine as crazy as that sounds)

It would be a linux specific but the NuGet package is being added to a NMake project. For windows code i am just packing it into build\native as is normal and using a target to manage build dependencies.

**Comment by AlphaCluster** [comment]
I thought I had tried using the native folder before and had issues but it does look like it works if you do build\native\* so thanks for the help.
