### ISSUE TITLE
NuGet in Intranet not useable (without Internet connection)

### ISSUE THREAD

**Issue by beachwalker** [NuGet/Home#8542]
## Details about Problem

NuGet.exe

NuGet version: 5.1.0.6013

OS version: win10, 10.0.15063

Did not work befor afaik.

## Detailed repro steps so we can see the same problem

1. Use config that uses local folder as source for nuget files

2. Disable external sources (nuget.org, http outside of intranet)

3. Ethernet adapter is configured with standard gateway, but proxy with auth is required (but not configured) to get out

4. NuGet tries to  reach outside repositories (runs into timeout) -> results in 30+min builds that should take only 1-2min

## Other suggested things
Have switch that denies connecting to other sources than configured in nuget.config(s)

### Verbose Logs

Verbosity flags does not help. We tried sysinternals procmon and saw process tried to access outside ip

### Sample Project

Sorry, not possible.

**Comment by beachwalker** [comment]
When removing the standard-gateway of the ethernet adapter, then nuget restore command works fast again. However this is not very nice, because then you have to edit host files etc. to access internal servers (e.g. for connection between gitlab<->gitlab-runner).

**Comment by heng-liu** [comment]
Are you using netcore SDK 3.0 preview version?
Could you look into obj\project.assets.json to see the complete list of sources used in the restore?

**Comment by beachwalker** [comment]
I use netcore2.2.

**Comment by rrelyea** [comment]
For one of the long running restores, please look at the obj\project.assets.json and examine the list of the sources used. Is that the list you expected? 

By on second thought...this may well be revocation checking.
See previous issue here: https://github.com/NuGet/Home/issues/7008
See docs on how to turn off here: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
