### ISSUE TITLE
Solution "Installed"-Tab shows unexpected the latest version not the installed version

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8545]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/712579/nuget-solution-installed-tab-shows-unexpected-the.html)._

---
Dear VS-Team,

I had to throw some work for cleaning up packages folder away, due the behaivior of the &quot;Installed&quot; Tab in NuGet Solution Browser. I think we can agree that the &quot;Installed&quot; Tab shows the installed packages. Unexpectedly the showed version is NOT the installed version, but the latest one. This makes no sense for this tab, because it is agains the given context.

Of course it is possible that multiple versions are installed, but in that case a easy &quot;multiple versions&quot; text would be appropriate.
It would of course also possible to addionaly show the latest version of the package also.

The content of the same installed tab for a specific project looks different and also shows the installed version.

I would also recommend, also for the other tabs, to show some prefix like &quot;newest:&quot; &quot;installed:&quot; before the version or some more intuitive than &quot;green arrow&quot; icon for the installed version. Currently its not intuitive as it should for such a simple dialog. I also discussed that with some collegues and they agree my conclusions.

Best regards
Marco Borm

---
#### Visual Studio Feedback System on 8/27/2019, 01:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Donnie Goodson [MSFT] on 8/30/2019, 04:58 PM: 

<p>Thanks for reporting the issue. If your selected package source doesn’t have the version that’s installed, it will only show the “latest” version it can find. What sources (feeds) do you have selected here? If you are only pointing to a local source, then does that source have the package you’re trying to install?</p>
<p>Thanks for the UI suggestion. I’ve created an issue on GitHub where it can be discussed with the team and community: <a target='_blank' href="https://github.com/NuGet/Home/issues/8538">https://github.com/NuGet/Home/issues/8538</a></p>

#### Marco Borm on 9/2/2019, 01:47 AM: 

<p>Dear Donnie, no, that's not correct. We only use packages from nuget.org. The installed tab for *the whole solution* *never* shows the installed version. It always shows the latest version.</p>

#### Donnie Goodson [MSFT] on 9/3/2019, 02:04 PM: 

<p>I see the issue now. The Solution PM UI tab should behave the same as the Project PM UI. Moving to GitHub.</p>

---
### Original Solutions
(no solutions)

**Comment by bormm** [comment]
Thank you for opening an official issue for my report.
