### ISSUE TITLE
Provide constructive CLI message when Dotnet pack is missing MSBuild Target

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8546]
## Details about Problem
With a .NET Framework project, the dotnet CLI does not have necessary Targets (eg, NuGet.Build.Tasks.Pack) for performing `dotnet pack`. The user gets an error about a missing "pack" target. It would be more useful to provide a a constructive message, possibly pointing to the documentation on how to obtain the required Targets. I ran into this during another repro, and found it a bit jarring. Dotnet CLI works for things like Restore, so users may expect Pack to work as well. 

Found an open Docs issue where someone asked for documentation for finding these targets: https://github.com/NuGet/docs.microsoft.com-nuget/issues/986

@karann-msft noted that the relevant docs are [here](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#add-the-nugetbuildtaskspack-package), and agreed that the CLI could be more informative.

NuGet product used: dotnet.exe
dotnet.exe --version (if appropriate): 3.0.100-preview9-014004

## Detailed repro steps so we can see the same problem

1. Create a .NET Framework project (ie, Class Library)
2. Run `dotnet pack` in the project directory
3. Output is:

> Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Nothing to do. None of the projects specified contain packages to restore.
> **C:\<Path>\myProj.csproj : error MSB4057: The target "pack" does not exist in the project.**

**Comment by nkolev92** [comment]
> The user gets an error about a missing "pack" target. It would be more useful to provide a a constructive message, possibly pointing to the documentation on how to obtain the required Targets

NuGet can't do that. 
The pack missing target error is an msbuild thing. 
And we can't add an error message in a scenario where our code doesn't run.

It'd have to be msbuild/dotnet.exe to special case this scenario. 

Even in that case there are caveats to consider: 
- The pack target only really makes sense with PackageReference. 
- The SDK brings in the pack SDK, so an SDK based project with a pack target missing has some custom modifications.

**Comment by donnie-msft** [comment]
> Even in that case there are caveats to consider:
> 
> * The pack target only really makes sense with PackageReference.
> * The SDK brings in the pack SDK, so an SDK based project with a pack target missing has some custom modifications.

This is a Framework project, not SDK, using packages.config.

**Comment by nkolev92** [comment]
In that case, packages.config projects won't work with the pack target anyways :) 
Which is the first caveat I listed.

**Comment by nkolev92** [comment]
Triage: 
Closing this as this is not actionable from NuGet perspective.

**Comment by cravecode** [comment]
I know this is closed, but Google will lead others here with similar issues.

Azure DevOps' dotnet pack step wraps the command in a MSBuild process. This will result in the error documented in this ticket (`The target "pack" does not exist in the project.`)

In my case, I was building a Nuget package that targets multi frameworks

The solution is the step documented specifically under: [Add the NuGet.Build.Tasks.Pack package](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#add-the-nugetbuildtaskspack-package)
```
<ItemGroup>
  <!-- ... -->
        <PackageReference Include="NuGet.Build.Tasks.Pack" Version="5.9.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
  <!-- ... -->
</ItemGroup>
```

**Updated:**
To include @zivkan's suggestion.

**Comment by zivkan** [comment]
@cravecode please use

```xml
<ItemGroup>
  <!-- ... -->
  <PackageReference Include="NuGet.Build.Tasks.Pack" Version="5.2.0" PrivateAssets="all" />
  <!-- ... -->
</ItemGroup>
```

People using your package should not get NuGet.Build.Tasks.Pack as a dependency, especially if they're using SDK style projects where the version of the pack tasks you're using are older than what ships in the .NET SDK itself.

**Comment by cravecode** [comment]
~~@zivkan, thanks for the response.~~
~~I'm confused about your suggestion. What makes your suggestion different from mine? Is it the use of `PrivateAssets`?~~
Oh! now I see what `PrivateAssets` does. (Ref: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)
Excellent point. Thank you!!

**Comment by zivkan** [comment]
FWIW, the `IncludeAssets` in your updated sample is not necessary. All private assets are included in the current project, it just doesn't flow transitively (become a package dependency).

**Comment by mloskot** [comment]
By the way, related to https://github.com/NuGet/Home/issues/8546#issuecomment-839805301, it may be worth to point at https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference#create-a-package-after-migration which says:

> add a reference to the nuget.build.tasks.pack nuget package, and then **use msbuild -t:pack** to create the package.

then it recommends to **not to use** `dotnet pack`:

> Although in some scenarios you could use dotnet.exe pack instead of msbuild -t:pack, it is not recommended.
