### ISSUE TITLE
package.config and nuget.config level mismatch

### ISSUE THREAD

**Issue by frialex** [NuGet/Home#855]
Hello,

I'm reading up on [Chaining Multiple Configuration Files](https://docs.nuget.org/consume/nuget-config-file#user-content-chaining-multiple-configuration-files) and I am confused as to why nuget.config is put at the solution level, but the package.config is at the project level. Since there doesn't seem to be a way to specify a feed source in packages.config this implies that  every project in the solution will point to the same feed.

This seems counter intuitive to me. Why not allow each project to control their feed source? I can just as easily use the `Install-Package awesomePackage -Source url` and select different feed on project basis. 

The problem that I'm experiencing is using Sidewaffle to create a web application template. This template takes in dependency from an internal NuGet feed.  Since Visual Studio Templates are copied on a project basis, NuGet restore fails right after an instance of the template is created. Though I can hack around and get the nuget.config moved over to solution root, it just doesn't seem right.

You almost had an awesome hierarchy but stopped one directory short and failed to provide an easy override... I'm just wondering why?

**Comment by yishaigalatzer** [comment]
That's a good question. But since the packages folder is setup per solution, mixing feeds per project can cause real damage.

We are also optimizing package restore across the whole solution which again making common feeds across the solution a very good assumption.

So moving the nuget.config will be at the solution level is not a hack its the right thing to do.

I'm closing this issue, but feel free to continue the discussion on this thread.

**Comment by frialex** [comment]
I see your point about a common package folder at the solution level. 

I hope you share my concern that in the future more than one package management solutions will be needed for a project. NPM/Bower does it on a project basis and NuGet does it on a solution basis.

The current problem presented by this difference is that NPM allows for a self-contained folder for a project while NuGet forces a Solution/Project hierarchy.

I guess only time will tell what the proper approach is.
