### ISSUE TITLE
Pack fails during AssemblyMetadataExtractor call when NuGet.exe filename is renamed

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8550]
## Details about Problem

Using a nuget.exe that is renamed to anything else (eg, nuget5.4.0.exe) causes the `Pack` command to silently fail, and incorrectly create package version 1.0.0.0.

Turns out that [AssemblyMetadataExtractor](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L776) which calls 

[`return (T)domain.CreateInstanceAndUnwrap(typeof(T).Assembly.FullName, typeof(T).FullName);`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/Pack/AssemblyMetadataExtractor.cs#L18)

which uses reflection on the NuGet.CommandLine assembly name.
This is "NuGet", and so if a user changes their NuGet.exe filename, it will throw an exception here, and break the Pack. 

Consider this overload (notice **From**) `domain.CreateInstanceFromAndUnwrap(string assemblyFile, string typeName)`

Oddly, Pack looks like it completes fine. Rather than showing an error, it says that it packed version 1.0.0.0. If you run `-verbosity detailed`, you'll see an inconspicuous error:` Could not load file or assembly 'NuGet, Version=5.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

Discovered this while trying to repro https://github.com/NuGet/Home/issues/8497

NuGet product used: NuGet.exe
NuGet Version: 5.1.0.6013

VS version (if appropriate): 16.3.0-pre.3.0+29229.4.d16.3 and 15.9.15+28307.812.
Worked before?: No

## Detailed repro steps so we can see the same problem

1. Create new C# class library, .NET framework 4.6.2

2. Build the library and pack it.

3. Upgrade the library to a newer version, e.g. 1.0.1

4. Build the library.

5. Rename NuGet.exe to a different name (eg, nuget4.exe).

6. Pack the library

## Expected result
You should now have a package with the new assembly version (eg, 1.0.1).

## Actual result
The output indicates success, even though it did not create the new version of the package. The version is incorrectly 1.0.0.0:
`Id: Repro8497
Version: 1.0.0.0
Authors: <username>
Description: Description
Dependencies:`
...
`Successfully created package 'NuGet.Client\artifacts\NuGet.CommandLine\16.0\bin\Debug\net472\Repro8497.1.0.0.nupkg'.`

## Sample project
[Repro8497.zip](https://github.com/NuGet/Home/files/3575969/Repro8497.zip)

**Comment by nkolev92** [comment]
How are you generating the nuspec?

Look at AssemblyMetadataExtractor for debugging purposes. 

Also, if it does work with the latest nuget.exe, what is your proposal? 
Service down level?

**Comment by donnie-msft** [comment]
> How are you generating the nuspec?

I'm not generating one. eg, Repro8497.1.0.5.nupkg

> Also, if it does work with the latest nuget.exe, what is your proposal?

I've asked the team to try this repro. We can discuss once I'm sure this is a consistent repro.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/4234
