### ISSUE TITLE
NU5048 is a warning in the error range

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8554]
NU code from 5000-5099 are errors.
5100-5199 are warnings. 

The root cause that the warning in question was originally an error and was never fixed. 

We should discuss if/how we want to address this, given that this has shipped in previews already. 

//cc @dominoFire @rrelyea 

Note that the pack codes already have issues; https://github.com/NuGet/Home/issues/7381

**Comment by nkolev92** [comment]
Discussed with @rrelyea, due to the fact that it's so late in the 3.0 cycle (3.0 Preview 9), this will be something we just live with.

**Comment by Thieum** [comment]
@nkolev92 any plan on reverting this error to a warning in a future version? It's not a quick fix to provide an image instead of an url for an existing package.

**Comment by nkolev92** [comment]
@Thieum 

> @nkolev92 any plan on reverting this error to a warning in a future version? It's not a quick fix to provide an image instead of an url for an existing package.

It's not an error. 

It's still a warning just the number for the warning is not in the range warnings usually are. 

If it's an error in your case, you likely have TreatWarningsAsErrors set somewhere.

**Comment by Thieum** [comment]
@nkolev92 makes sense, thanks!
