### ISSUE TITLE
Nuget command line parameters are inconsistent

### ISSUE THREAD

**Issue by dotMorten** [NuGet/Home#8555]
## Details about Problem
When using nuget.exe I was looking for help. So I naturally tried the various common ways to get the help output:
```
nuget /?
nuget -?
nuget --?
nuget -help
nuget /help
nuget --help
```
All of them returned:
```
Unknown command: '/?'
NuGet.CommandLine.CommandLineException: Unknown command: '/?'
   at NuGet.CommandLine.CommandManager.GetCommand(String commandName)
   at NuGet.CommandLine.CommandLineParser.ParseCommandLine(IEnumerable`1 commandLineArgs)
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```
Instead it turns out the command is
`nuget help` or `nuget ?`
This is a bit against common convention.
However it gets weirder. I needed help for the `nuget config` command, so now having learned you add `help` without a dash, I entered this:
```
c:\>nuget config help
Key 'help' not found.
```

It turns out that in this specific case, you must use a dash in front of the command: `nuget config -help`

This is rather inconsistent. The quick fix would allow `nuget -help`  and `nuget -?` (or forward slash on Windows) to be the common documented approach, as it's in alignment with common conventions, and also aligns with other help commands in the nuget cli.

I later realized you can also do `nuget help config`, but again I've found it more common you ask for help after the command you want help with, and not the other way around.

NuGet product used: `NuGet.exe`

NuGet version (x.x.x.xxx):  `5.1.0.6013`

OS version (i.e. win10 v1607 (14393.321)): `Win10 v1809 17763.529`

**Comment by aortiz-msft** [comment]
Thank you for creating this issue. Our team prioritizes fixes based on impact and upvotes, and, based on this, we don't think we will be able to get to this issue. However, we would gladly accept a PR for this. Thanks again.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/1907
