### ISSUE TITLE
How to suppress error NU1202 'Package is not compatible with netcoreapp'

### ISSUE THREAD

**Issue by alexgav** [NuGet/Home#8560]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe 

NuGet version (x.x.x.xxx): 2.8.7.0 on Linux

dotnet.exe --version (if appropriate): 2.2.107

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Ubuntu 18.04.3 LTS

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a netcoreapp2.2 reference netframework472 package. If you have permissions, you can use my app 

2. Try to run dotnet restore on Linux 

Here's the thing. I'm getting *warning* NU1701 when restoring this on Windows, and I am able to easily suppress it. I'm getting *error* NU1202 for the same exact package reference when trying to restore that project on Linux, and I can't figure out a way to suppress that error.

I know the reference netframework472 code runs fine on netcore, including on Linux, as I tested it without using <PackageReference ...> first. So the issue here really is "how do I suppress that error?". Also, why am I getting a different error on linux than warning on Windows for the same exact package? 

Here's my sample package reference

`<PackageReference Include="Microsoft.VisualStudio.Language.StandardClassification" Version="$(CoreEditorAssemblyVersion)" NoWarn="NU1701" />`

BTW, I'm MSFT employee, alias alexgav, so feel free to ping me internally.

Thanks,
Alex

**Comment by rrelyea** [comment]
What version of dotnet sdk are you using on Windows? What version on Linux?
Are you doing the identical command on both OSes?
Also, what version of the package are you trying to use?

**Comment by rrelyea** [comment]
I see NU1202 on windows with NetCore SDK 2.2.401
With NetCore SDK 3.0.100-preview9, i don't see this.

**Comment by alexgav** [comment]
Hi Rob, yes, you are right, I had 2.2 on Linux and 3.0 on Windows. Installing 3.0 on Linux that error goes away. Now 3.0 on Linux is refusing to run my netcoreapp2.2 (says no compatible frameworks found), so I guess I'll need to have both of them side-by-side? In either case, I guess that's no longer a nuget issue so we can close this one. Thank you very much for your help!
