### ISSUE TITLE
VSLangProj/PackageReferences, Package Restore with .NET Core 3.0 and FrameworkReferences

### ISSUE THREAD

**Issue by sae42** [NuGet/Home#8563]
**Visual Studio project system and Framework References for NuGet client**

I've updated to using Visual Studio 2019 16.3 Preview 3 with .NET Core Preview 9. As a third-party language vendor I have an implementation of VSLangProj150/PackageReferences. It is unclear to me whether the implementation of get_InstalledPackages should include the new FrameworkReference element or not.

Before Preview 9 I could return the implicit Microsoft.NETCore.App package. However, after installing preview 9 I get an error when executing a NuGet restore (through the VS interface, not from MSBuild):

... (1,1-1) : error NU1102 : Unable to find package Microsoft.NETCore.App with version (>= 3.0.0-preview9-19423-09)
... (1,1-1) : error NU1102 : - Found 74 version(s) in nuget.org [ Nearest version: 3.0.0-preview8-28405-07 ]
... : error NU1102 : - Found 0 version(s) in Microsoft Visual Studio Offline Packages

Can someone give guidance or clarity about how a project system should return Framework References to NuGet client in this scenario?

[@rrelyea: edit/correction -- I think you mean to say "how and when should a project system include a FrameworkReference item in an msbuild project" There are a variety of consumers of FrameworkReferences.]

 I can just stop returning this and the problem goes away, but I assume at some point there will be third party Framework References that would need to be restored.

OS version:
Windows 10 1903

**Comment by rrelyea** [comment]
I believe that FrameworkReference is an SDK concept...that NuGet participates in.
@livarcocc - does it make sense for your team to document and help people transition aware from Microsoft.NETCore.App to FrameworkReference? If not your team, recommendation?

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
