### ISSUE TITLE
Warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated with 3.0.100-preview9-014004

### ISSUE THREAD

**Issue by livarcocc** [NuGet/Home#8569]
_From @kdcllc on Thursday, September 5, 2019 4:49:06 PM_

This warning is displayed with DotNetCore 3.0.100-preview9-014004 with the following tag:
 ```
<PackageIconUrl>https://github.com/kdcllc/Bet.AspNetCore/raw/master/img/logo64x64.png</PackageIconUrl>
```
When changed to `<PackageIcon>` the sdk msbuild action is not able to find the local file.

_Copied from original issue: dotnet/core-sdk#4588_

**Comment by dominoFire** [comment]
@kdcllc,
We are not able to repro this problem.
1. started with a project like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageIconUrl>http://microsoft.com/foo.jpg</PackageIconUrl>
  </PropertyGroup>
</Project>
```
2. ran dotnet.exe pack and got a warning:

> C:\Program Files\dotnet\sdk\3.0.100-preview9-014004\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): warning NU5048: The 'PackageIconUrl'/'iconUrl' element is deprecated. Consider using the 'PackageIcon'/'icon' element instead. Learn more at https://aka.ms/deprecateIconUrl [C:\temp\iconTest\iconTest.csproj]

3. navigating to https://aka.ms/deprecateIconUrl, i find the steps to change to PackageIcon.
4. after step 3, i have the following csproj:
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
        <None Include="images\icon.png" Pack="true" PackagePath="\"/>
  </ItemGroup>
</Project>
5. create an images folder and put an icon.png inside of it.
6. run dotnet pack and all works:

> C:\temp\iconTest>dotnet pack
> Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Restore completed in 18 ms for C:\temp\iconTest\iconTest.csproj.
>   You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
>   iconTest -> C:\temp\iconTest\bin\Debug\netstandard2.0\iconTest.dll
>   Successfully created package 'C:\temp\iconTest\bin\Debug\iconTest.1.0.0.nupkg'.

**Comment by DevEddy** [comment]
Any news on this? I also have this bug when just building the project.

`
/usr/local/share/dotnet/sdk/3.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(5,5): Error: The icon file 'http://microsoft.com/foo.jpg' does not exist in the package. (HomematicIp)`

Eddy

**Comment by nkolev92** [comment]
@DevEddy 

Refer to https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-an-icon-image-file  for packing an icon file. 

You need to download the icon itself to your local machine and then pack that.
Pack will not automatically go to a URL and download the icon.

**Comment by nkolev92** [comment]
Closing this as no repro for now.
