### ISSUE TITLE
Update Gallery as per nuget 3.0 pack changes

### ISSUE THREAD

**Issue by bhuvak** [NuGet/Home#857]
Just a tracking bug for 
https://github.com/NuGet/NuGetGallery/issues/2570 to make sure we fix it as part of 3.0 commandline milestone.

**Comment by yishaigalatzer** [comment]
@bhuvak please add more details here, not sure what this is all about?

**Comment by deepakaravindr** [comment]
@bhuvak, Can you please add more details?

**Comment by bhuvak** [comment]
There is no schema change introduced as part of 3.0 command line and we have verified that we are able to push packages created using 3.0 pack to Gallery. Hence closing the issue.

**Comment by RanjiniM** [comment]
This was a non-issue
