### ISSUE TITLE
Retarget task in dotnet/sdk to net5.0 when ready to insert nuget bits targeting net5.0

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8570]
[updated based on teams call with @heng-liu , @zkat , @nkolev92 , @zivkan , @rrelyea ]

When it's ready to insert nuget bits targeting net5.0, 
(nuget current - net472, netstandard2.0, netstandard2.1)
(nuget change to - net472, netstandard2.0, net5.0)

Remember to go to the dotnet/SDK repository , change sdk/src/Tasks/Microsoft.NET.Build.Tasks/Microsoft.NET.Build.Tasks.csproj to ensure that they are using net5.0 version of us.

So that SDK will use the NuGet.Packaging targeting net5.0.

also:
restore -> needs net5.0 (because it needs validation to work)
pack -> doesn't need to verify, therefore could live with just netstandard2.0
dotnet add package -> xplat.dll - needs 5.0, so it pulls in the right restore bits.

**Comment by heng-liu** [comment]
Created an issue under dotnet/sdk category https://github.com/dotnet/sdk/issues/3629
So that both of NuGet and SDK will be aware of it.

**Comment by heng-liu** [comment]
I'm thinking if we should do this after merging to dev, or raising PR to dotnet team, but ask dotnet team to wait until we are sure to insert into dotnet with xplat verfication code, then they merge.
If dotnet team make this change, but xplat verfication doesn't catch up with the insertion, will there be any issue?

**Comment by zivkan** [comment]
> If dotnet team make this change, but xplat verfication doesn't catch up with the insertion, will there be any issue?

No. NuGet will always select the most compatible TFM. If we insert first, their projects will not use the new assets because their project is not compatible with our new TFM. If they update first, they'll keep using the "best" TFM in our packages, and as soon as we insert a package with extra TFMs, NuGet will find the new TFM and select it as the nearest match.

**Comment by heng-liu** [comment]
https://github.com/dotnet/sdk/issues/3629 is closed as fixed. So close this one.
