### ISSUE TITLE
Show the new NuGet default icons everywhere

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#8572]
1. When the icon is not provided, old icon is shown on PM UI:
   ![image](https://user-images.githubusercontent.com/14800916/64720052-695a3c80-d47e-11e9-90d6-d559eeebfef9.png)

2. Show NuGet icon (mono color) for "Manage NuGet packages..." https://github.com/NuGet/Home/issues/2790 
![image](https://user-images.githubusercontent.com/14800916/64720094-7ecf6680-d47e-11e9-9529-2d0d314e3c9f.png)

**Comment by rrelyea** [comment]
@anangaur - Do we have an associated issue on the gallery as well? Do you want to coordinate releases?

**Comment by anangaur** [comment]
Gallery already shows the right fallback icon:
![5C8A747E-7C55-486F-88FE-56038F902197](https://user-images.githubusercontent.com/14800916/65003719-8cd21c80-d8ae-11e9-8965-9d8e2580d2e3.png)

**Comment by donnie-msft** [comment]
Will be resolved in this issue, which is more specifically targeted to replacing this icon: https://github.com/nuget/home/issues/5937
