### ISSUE TITLE
PackTask validation failures don't always fail the build

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#8576]
## Details about Problem

When encountering a validation failure the task will log errors but the build does not always halt.

See 
https://dev.azure.com/dnceng/internal/_build/results?buildId=350161&view=logs&jobId=7c8326b9-0a5f-532a-e6de-db8515c72d9a&taskId=12d084b4-51e7-52c1-3fda-e5b95df7115e&lineStart=54&lineEnd=55&colStart=1&colEnd=1
vs
https://dev.azure.com/dnceng/internal/_build/results?buildId=350161&view=logs&jobId=b36057ec-f3d9-56c1-75f0-6724e6013c1d&taskId=d12b9310-d09c-5940-f1ca-4fb81ee61cf5&lineStart=78&lineEnd=78&colStart=1&colEnd=23

And 
https://dev.azure.com/dnceng/public/_build/results?buildId=347858&view=logs&jobId=d6d0747d-862c-5953-c201-f4e1a93f2cef&taskId=3ccc3669-e0b9-50c6-efe1-cc0487c0e6c1&lineStart=179&lineEnd=181&colStart=1&colEnd=60
vs
https://dev.azure.com/dnceng/public/_build/results?buildId=347858&view=logs&jobId=fa59fe4e-195c-56fa-189b-58fd241f10dd&taskId=afa1ce5e-d2bc-56f3-ad78-7883f25a3e3a&lineStart=202&lineEnd=203&colStart=1&colEnd=23

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet.exe

NuGet version (x.x.x.xxx):
5.3.0.6192

dotnet.exe --version (if appropriate):
3.0.100-preview9-014004

VS version (if appropriate):
n/a

OS version (i.e. win10 v1607 (14393.321)):
n/a

Worked before? If so, with which NuGet version:
??? validation errors are new, but this behavior likely pre-existed

## Detailed repro steps so we can see the same problem

1. Run `dotnet pack` against the following project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IsPackable>true</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="4.6.0-rc2.19461.4" />
  </ItemGroup>

</Project>
```

Expect: build errors and returns non-zero
Actual: build errors but returns success, causing CI/build-pipeline to proceed and ignore error.

2. Type `dotnet pack` again after the build failed in this way.

Expect: Error again, same as before.
Actual: Succeeds without error 😕 

## Other suggested things
Bug appears to be here https://github.com/NuGet/NuGet.Client/blob/007e5c55cad83aa90733ede04eec68a8c29f9be8/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTask.cs#L140

Task should return false when it fails.  /cc @rainersigwald

### Verbose Logs

![image](https://user-images.githubusercontent.com/8918108/64731626-73883500-d496-11e9-9c62-93888ee38951.png)

Please include verbose logs  (binlog, zipped)
[msbuild.binlog.zip](https://github.com/NuGet/Home/files/3602557/msbuild.binlog.zip)

### Sample Project

See above.  /cc @nkolev92 @zsd4yr

**Comment by nkolev92** [comment]
Without digging too much into it, seems like a dupe of https://github.com/NuGet/Home/issues/7404. 

I'll try to look into it for 5.4

**Comment by ericstj** [comment]
There's more to it than #7404.  There's also an incremental build bug here as I reported above with 2.  I suspect you need to do more than my suggested fix to also fix the incremental build case.

**Comment by rrelyea** [comment]
To confirm...this bug (and its dupe) isn't a regression, correct?

**Comment by nkolev92** [comment]
A problem (as there might be others) in 7404 is that the nupkg file is created even when there are errors reported. 

So yeah, as you suggested it goes beyond the exit code. 

I'd imagine in your case, the next one succeeds because we try to do an up to date check and that one succeeds because the package already exists and none of the inputs have changed.

**Comment by ericstj** [comment]
I believe this is existing but its much more prevalent now that NuGet has added more validation.

**Comment by rrelyea** [comment]
Thanks. We will take care of 7404 -- and we have links to the extra info here.

**Comment by zsd4yr** [comment]
Thanks @rrelyea
