### ISSUE TITLE
Removing all packages from created as a test

### ISSUE THREAD

**Issue by EasyLOB** [NuGet/Home#8582]
Hi,
I will publish my first set of Packages to NuGet, but before doing so I created a small test library and published 3 packages versions with NuGet CLI.
Now I would like to exclude all ( they are just tests ! ) but the only option I find is "delete/unlist".
How could I get rid of them ?
Will NuGet keep this packages forever ?

https://www.nuget.org/packages/Mock

Thanks

**Comment by dominoFire** [comment]
HI @EasyLOB 

Hope all is well.

You can send a support request with your case at https://www.nuget.org/policies/Contact 

Since this is nuget.org issue, I will close the issue.
