### ISSUE TITLE
NU1101 in ASP.NET Core template projects with VS 2019 16.3 Preview 3

### ISSUE THREAD

**Issue by ghogen** [NuGet/Home#8586]
## Details about Problem
I just installed VS 2019 16.3 Preview 3 and created a Web Application project (tried .NET Core 2.1 and .NET Core 3.0) and noticed that my NuGet packages are not restoring properly, so that out-of-the-box templates didn’t build.  I was getting NU1101 – couldn’t locate the package in the source ‘Microsoft VisualStudio Offline Packages’.

I was able to get these to build by going into “NuGet Package Manager” and adding a new package source as follows:

https://api.nuget.org/v3/index.json

So it would seem that VS is not setting things up correctly with the right package sources, or something.

NuGet product used ( VS UI ):

NuGet version ():

VS version (if appropriate): 16.3 Preview 3

OS version (iwin10 v1903)

**Comment by karann-msft** [comment]
the `https://api.nuget.org/v3/index.json` package source wasn't already present? Can you share a screenshot of `Tools>Options>NuGet package manager>Package Sources`

**Comment by rrelyea** [comment]
@ghogen  - more details?
Was this a fresh machine?
What other versions of VS were installed before?
What config files may have been defining or disabling sources?

**Comment by ghogen** [comment]
It was not a fresh machine - it also had VS 2013 on it.  I don't know about any config files that might have changed - it was a fresh install of VS 2019 16.3 Preview 3. I will see if I can repro it again sometime in the next few days.

**Comment by ghogen** [comment]
I just retried this on another machine with a fresh install of the same preview build, but it did not reproduce.  Well, it did happen, but I'll see if I can narrow this done more.  If I can reproduce on a machine again, I can share that machine for investigation.

**Comment by rrelyea** [comment]
@ghogen  - if i recall there was an issue like this during vs2015 when upgrading to nuget 3.4.0 or 3.4.1.
we did work to address that...
it is possible that there is some upgrade matrix that would repro this. sorry if it hits you.
if it ends up being something that affects many customers, would be happy to investigate and consider fixes.

**Comment by nkolev92** [comment]
Thank you for reporting this issue. We have not been able to reproduce this issue. If you are still able to reproduce this with the latest NuGet version, please provide additional steps.
