### ISSUE TITLE
Text templating inside of a nuget.config file

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#8587]
Hello, more of a question than an issue. We have a case where we would like to define some custom `<config/>` bits for expansion during the `<packageSources/>`. Along these lines,

```Xml
<config>
  <add key="myKey" value="myValue" />
</config>
<packageSources>
  <add key="$myKey$ Released Packages" value="..." />
</packageSources>
```

**Comment by rrelyea** [comment]
That isn't something that we do in config files. We don't have a templating mechanism inside of config files...and this would likely causes headaches for us to provide loading and saving these settings files, so we aren't keen to add it.

**Comment by mwpowellhtx** [comment]
That's a shame, because I've got some applications for that which would lend themselves to that sort of solution.

**Comment by rrelyea** [comment]
Perhaps T4 Text Templates as a technique to generate your config files would be something to consider.

https://docs.mcrosoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019

**Comment by mwpowellhtx** [comment]
@rrelyea Would that work without needing to reload the solution?

**Comment by rrelyea** [comment]
Not today. But we need to solve that problem sometime.
