### ISSUE TITLE
package restore failed when install some packages to UWP project

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#859]
repro steps:
 1. create blank app thru click C#->Windows->Univerdal-> Blank App(Universal Windows)
 2. install package libphonenumber-csharp,  NuGet.Server and TestPackage.MinClientVersion

expected results: install successfully
actual results: get restore error
![restoreerror](https://cloud.githubusercontent.com/assets/11768961/8426028/b7654c52-1f3e-11e5-8feb-74804de3e0ee.PNG)

**Comment by emgarten** [comment]
This package is not expected to install currently as the expected result says. All V3 restores that fail will add this general message to the error list, the details on why it failed can be found in the package manager console.

This could be improved now that more details are available in the RestoreResult. The same errors in PMC could be displayed in the error list.

**Comment by yishaigalatzer** [comment]
@emgarten looks like you have two bugs that are already on you
1. To make some of them install
2. To move the errors from output to the error list.

Should we just close this as dup?

**Comment by emgarten** [comment]
1. Won't fix this scenario.  netcore50 should never install a net45 package like this one.
2. The output formatting hasn't worked, we need to manually catch these errors and write them to the error window. We are doing that for the onbuild event, but not for package installs.

**Comment by yishaigalatzer** [comment]
This is already tracked by other issues

**Comment by BlueRaja** [comment]
> This is already tracked by other issues

Such as...?
