### ISSUE TITLE
Possible to add NuGet.Config at the Project level

### ISSUE THREAD

**Issue by mwpowellhtx** [NuGet/Home#8598]
Hello,

Is it possible to add `NuGet.Config` at the *Project* level? Or at least isolate config to a solution in which there are sister solutions in the same work space.

I've got config at the solution level at the moment, but I've got at least one case where it would be helpful to isolate package sources to at least a solution, if not a *Project* in that solution, for instance.

That is,

```
[ SolutionA: [...], SolutionB: [...], SolutionC: [ProjectA] ]
```

Would be helpful in this case to isolate a `NuGet.Config` for `ProjectA`, as contrasted with `SolutionA`, `SolutionB`, and `SolutionC` all being able to see it.

Worst case, I suppose we could also isolate a `tests` folder sister to our `src` folder, but it is a long story how we got here, and we have made an effort to keep the solution work space thread together consistently.

Thanks!

**Comment by zkat** [comment]
You can create a `nuget.config` file at a solution level, as [described in our documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses). Unfortunately, you can't do this at a .*proj level.
