### ISSUE TITLE
Revert deterministic docs

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8608]

**Comment by nkolev92** [comment]
The feature was reverted: https://github.com/NuGet/Home/issues/8602, #8599

**Comment by mivra** [comment]
What I really don't understand is why couldn't it stay there when it was an optional feature :(

**Comment by zivkan** [comment]
@mivra  [the .NET SDK sets deterministic to true by default](https://github.com/dotnet/sdk/blob/0979dd3c53a8971a5434cf4bc68efd103fe5ea68/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L34), so the issues were breaking many projects that never explicitly opted in.
