### ISSUE TITLE
[Test Failure] Install a package with PMC makes .Net Core “Default Project” is empty after setting package format is “Package Reference”

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#8609]
## Details about Problem
VS Version: D16.4 29318.156
OS Version: Windows-10-Enterprise-19H1-04-05-2019.
## Detailed repro steps 
1. Create a Console App (.Net Project) and set package format is “Package Reference” in setting General.
2. File >New Project>ASP.NETCore WebApplication (.NetCore)>1.0/1.1/2.0 no authentication.
3. Wait for the project restore completely.
4. Tools - NuGet Package Manager - Package Manager Console.
5. Run this: Install-Package Microsoft.EntityFrameworkCore.Tools -version 2.2.0.
## Expected
“Default Project” should show the project name correctly.
## Actual
 “Default Project” is empty as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/65236023-48db5380-db0a-11e9-95cb-bc2af38c1c95.png)
## Note
The issue only repro on .Net Core projects.

**Comment by zkat** [comment]
Note: I can reproduce this is 16.3 but not in 16.2.5. Calling this a regression.

**Comment by medright** [comment]
this is failing for me with visual studio enterprise 2019 v16.4.0, please see attached screenshot
![Snag_1a469f](https://user-images.githubusercontent.com/4702913/72099546-d4ae0100-32ee-11ea-98a2-9c0655440525.png)

**Comment by v-longmin** [comment]
Verify the issue on Master\30114.135 + NuGet Client dev\5.7.0.6612, it has been fixed, closed it, thanks!
