### ISSUE TITLE
NuGet completely fails to load when a nuget.config file is readonly

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#861]
This is a primary TFS scenario where nuget.config is on the path.

**Repro steps**
Create a nuget.config is a sub folder, and a project inside the folder. 
making nuget.config readonly
Open the project in visual studio
Right click manage nuget packages.

Result -> NuGetPackage failed to load dialog.

**Why**
NuGet is trying to update the nuget.config file with new Api V3 entry, but fails catastrophyically because the file is readonly.

**Also**
While updating the file it changes the path to a full path
![image](https://cloud.githubusercontent.com/assets/1238711/8443177/472f7002-1f39-11e5-9f53-76887e7e81fb.png)

**Comment by deepakaravindr** [comment]
https://github.com/NuGet/NuGet.VisualStudioExtension/pull/39
