### ISSUE TITLE
PR triggering for external contributors not working. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8617]
See: https://github.com/NuGet/NuGet.Client/pull/3070
The labels are being set, yet https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8118 shows no builds are being triggered.

**Comment by nkolev92** [comment]
@donnie-msft 
As hot seat, can you please look into this?

**Comment by donnie-msft** [comment]
Updated expired credential.
Re-labelled the linked issue, and it properly triggered a CI Build.
