### ISSUE TITLE
Automatically reinstall packages during build in Visual Studio

### ISSUE THREAD

**Issue by tugrulelmas** [NuGet/Home#8624]
There is a huge monolithic application on which 400 developers actively work. It's an ASP.NET Web Application project and it has 35 modules and 1 `.sln` file. Each module has 5 class library projects and is located under its folder. Modules depend on each other via project references. I have to say that there is a dependency hell that makes development difficult.

Now, I'm replacing these project references with nuget references and am creating nuget package for every projects and `.sln` file for every module so that developers can focus on their modules and work on small projects instead of a huge monolithic. My aim is to increase dependency between modules with using messaging queue or streaming in the future. In that scenario I'll remove nuget references from projects but, I can't say when it'll be possible.

Anyway, I'm creating 5 nuget packages for one module and install these packages to ASP.NET Web Application project. After every commit, I create a new version of nuget packages with commit id like `1.0.0-beta.1871248`. It seems that I'll be in trouble with this versioning, because I want every module and web application project to work with latest versions of other modules. In order to do that, developers need to update nuget packages in Visual Studio Package Manager. And right there I have to say that there is a version hell :) To solve this problem, I've decided to create nuget packages with only one specific version like `1.0.0-beta` and [reinstall ](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages) every packages during build from Visual Studio but there is no easy way to achieve this.
 
It seems that [Package restore in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#enable-and-disable-package-restore-in-visual-studio) does not use MSBuild targets. It would be easier if there were some MSBuild targets for that purpose, I could override one of them and just delete packages folder before restoring. So, here is my workaround:

I've disabled automatically check for missing packages during build in Visual Studio with adding `automatic` key to `NuGet.Config` to avoid double installation.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget.org-proxy" value="http://internal-nexus/repository/nuget.org-proxy/" />
    <add key="nuget-hosted" value="http://internal-nexus/repository/nuget-hosted/" />
    <add key="automatic" value="False" />
  </packageSources>
  <disabledPackageSources>
    <add key="nuget.org" value="true" />
    <add key="Microsoft and .NET" value="true" />
  </disabledPackageSources>
</configuration>
```

I've added new target to `.csproj` file to delete packages folder and reinstall packages. I'm doing this for only debug mode because my CI/CD pipeline never gets packages folder from source control. 

```
<Target Name="DeletePackagesFolderTarget" BeforeTargets="Build" Condition="'$(Configuration)' == 'Debug'">
  <Exec Command="rd /s /q $(SolutionDir)\packages" />
  <Exec Command="$(SolutionDir)\nuget\nuget.exe restore $(SolutionPath)" />
</Target>
```

It would be great if I could make it happen by just adding a key to `NuGet.Config`. It would be perfect if I could set it for one package source.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console):

NuGet version (x.x.x.xxx): 4.9.2.5706

VS version (if appropriate): Enterprise 2017 Version 15.9.14

OS version (i.e. win10 v1607 (14393.321)): win10 v1703

Worked before? If so, with which NuGet version:

**Comment by rrelyea** [comment]
Creating a bunch of packages that have the same identity (id and version) but different content, is a troublesome practice.

We'd think that publishing these packages as different versions is the right thing to do.
The challenge is the updates. One idea is to automate a change to the packages.config files and csproj files and merge that change. Then your engineers would be able to work at any part of the change history in source control, and have packages that work for them.

Note...if ASP.NET supported PackageReference, then using versions with wildcards ("*") in them would also help this be more automatic. That is why in 2015, we started working towards PackageReference and less hard coding that Packages.Config does.

Moving from Packages.Config to PackageReference would enable you to use versions with wildcards in them...that would support this same scenario.

However, the ASP.NET has not done work to enable and support PackageReference. (see devcommunity item: https://developercommunity.visualstudio.com/content/problem/246759/migrate-packagesconfig-to-packagereference-not-ava.html) 
Of course, ASP.NET Core supports PackageReference. I realize that is not a simple move.

**Comment by tugrulelmas** [comment]
With the same identity version scenario, developers can't work with different versions of packages because there is only one package. I know that the same identity version scenario is not a versioning system. In my opinion, it looks like tagging a docker image with `latest` keyword. In order to developers can work different versions of the same package, I can publish packages as different versions and with the same identity at the same time, but I want developers to work with the latest version of packages. All packages interact with the database and there is no versioning system for database. So even if I make possible to work with different versions, developers may not have chance to work with these packages.

Automating updating packages has some questions to be answered like should I update packages after every commit or after specific period (5 min., 1 hour, at midnight etc.). I think, that's more suitable for CI/CD pipelines than local development environment. Developers should be aware of getting latest changes from source control to work with the latest packages. It's not a big deal but installing latest packages during build is more efficient. 

I was very excited when I saw [wildcard versions rule](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-wildcard-versions) but there is no support for ASP.NET. So, I keep my excitement for the future because we want to migrate our project to .net core from .net framework.

**Comment by tugrulelmas** [comment]
Hi @rrelyea, I want to try PackageReference with wildcard versions for at least class library projects. As far as I can see, wildcard rule installs latest nuget packages but it doesn't check during every build if there is a new version and I can not force Visual Studio to install the latest one. Visual Studio probably uses a cache to install packages and that's why installs the latest one after a certain time. How can I force Visual Studio to install latest packages and how long do I need to wait to do so without forcing?

Lastly, I can't see which version of package is installed either from solution explorer or from Package Manager. After a build is failed, I need to look at the `project.assets.json` file to understand what's going on.
![image](https://user-images.githubusercontent.com/3829187/66205684-ad73e200-e6b6-11e9-9601-191cf83e244d.png)

**Comment by rrelyea** [comment]
@tugrulelmas  - 
In order to ensure you are getting the latest package when you a floatversion (with "*" somewhere in version) -- you need to force the restore to run:
- dotnet.exe restore --force
- nuget.exe restore -force
- in VS - build/rebuild all (will do a force under the covers)
- delete assets file from obj\ directory....then restore
- etc...

Yes, we don't handle floating versions in VS ui well. (although i am surprised that the solution explorer doesn't show it correctly after a restore) See https://github.com/NuGet/Home/issues/7345 for a link to the spec that we have spent some time on.

**Comment by tugrulelmas** [comment]
Thanks for letting me know `force` switch. This feature is missing in documents. See https://github.com/NuGet/docs.microsoft.com-nuget/issues/1729#issue-504282171 for the detail. It would also perfect if I can make a feed non-cacheable from `NuGet.config`. I'll follow this suggestion from https://github.com/NuGet/Home/issues/7198#issue-350193041

**Comment by nkolev92** [comment]
Closing per the discussion.
