### ISSUE TITLE
"Log" plugin-request should never fault

### ISSUE THREAD

**Issue by jmyersmsft** [NuGet/Home#8625]
While helping a customer with another issue, I noticed that sometimes Log requests are returning a fault complaining about some MSBuild problem.

All I have from the NuGet side in the credential provider log is "MSB0001: Internal MSBuild Error: ContextID 5 should have been in the ID-to-project file mapping but wasn't!" (along with information that it was a fault response to a Log request)

I think log requests should swallow exceptions (perhaps logging them to NuGet's output). The failure is unlikely to be the plugin's fault, the plugin probably can't do anything about it (if it even actively observes the result of a log request -- our plugins just fire-and-forget), plugins can provide other mechanisms for reliable logging, and the fault message can cause things to start canceling.

**Comment by nkolev92** [comment]
While running a specific repros, I'm seeing signals that it might. 
Will add some diagnostic logging to see if that makes a difference.

**Comment by nkolev92** [comment]
The root cause is https://github.com/Microsoft/msbuild/issues/3362. 
Still investigating how much/if any of #8528 can be traced back to this.

**Comment by nkolev92** [comment]
The risk here is what if we miss the message with the magic code and the link to do device flow. 
We need to consider what missing this message means. 

>I think log requests should swallow exceptions (perhaps logging them to NuGet's output)

The problem in the specific scenario is that logging to NuGet's output failed, so swallowing this would mean it would never be surfaced to the user in any way. 

Ideally MSBuild's issue is fixed and we don't see this manifest ever again.

**Comment by rainersigwald** [comment]
I suspect the proximate cause of this was #8688. With that fixed, I'd lean toward leaving logging failures as failures.

**Comment by nkolev92** [comment]
I agree. 

We also have no way to communicate any logging failures to the user.
