### ISSUE TITLE
Possible bug in validation rule implementation of NU5129

### ISSUE THREAD

**Issue by StephenBonikowsky** [NuGet/Home#8627]
In WCF repo after [updating our dependency](https://github.com/dotnet/wcf/pull/3920) to Arcade one of our packages began producing this validation error...

`".dotnet\sdk\3.0.100-preview9-014004\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5129: - At least one .props file was found in 'build/', but 'build/dotnet-svcutil.xmlserializer.props/dotnet-svcutil.xmlserializer.props' was not. - At least one .targets file was found in 'build/', but 'build/dotnet-svcutil.xmlserializer.targets/dotnet-svcutil.xmlserializer.targets' was not. "`

It's evident from the logging that something strange is happening, as far as I can see we are following convention.
[dotnet-svcutil.xmlserializer.props](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/files/GenerateNupkgProps.targets#L9)
[dotnet-svcutil.xmlserializer.targets](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj#L87)

I am suppressing the warning for now...
dotnet/wcf#3928

To reproduce just checkout the master branch from the [dotnet/wcf repo](https://github.com/dotnet/wcf)
Remove the [No Warn](https://github.com/dotnet/wcf/blob/master/src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj#L9)
 Run the following command from the root...
`eng\common\cibuild.cmd -configuration Release -prepareMachine -- /p:Test=false /p:IntegrationTest=false /p:Pack=true`

It will build some other stuff as well but will reproduce the error for that specific project.

**Comment by rrelyea** [comment]
Thanks for filing the bug...
(would be great if the WCF repo didn't need to download its own 3.0.100 if I already have it...I'm at a coffee shop downloading via my cell connection.)

**Comment by rrelyea** [comment]
yes, was able to repro. unsure why our validation rule is looking for build/projectname.targets/projectname.targets -- clearly a problem.
Haven't seen that elsewhere, so it may be something we fix...or tell you how to stop doing weird things. ???

**Comment by StephenBonikowsky** [comment]
Yes, that project does some less than normal things which are necessary and not the easiest to explain.

However, as it relates to adding a props file and a targets file to the package, we are placing them in the correct location following the correct naming convention. We would prefer not to suppress NU5129.
