### ISSUE TITLE
$package.GetFiles with VS2015

### ISSUE THREAD

**Issue by pascalberger** [NuGet/Home#863]
I've some inhouse NuGet Packages which include PowerShell scripts which call $package.GetFiles(). In Visual Studio 2015 the following error is thrown on executing this PowerShell:

    Method invocation failed because [NuGet.PackageManagement.VisualStudio.ScriptPackage] does not contain a method named 'GetFiles'.

Is there a way to retrieve all files in a package from a init.ps PowerShell script with the v3 API?

**Comment by yishaigalatzer** [comment]
There is currently no way to do that, we can look at bringing it back in the next release.

**Comment by pascalberger** [comment]
@yishaigalatzer Is this included in the recently released 3.2 RC or has it been pushed to a future release?

**Comment by yishaigalatzer** [comment]
3.3, you can tell from the milestone on the right hand side.

**Comment by pascalberger** [comment]
Thanks. I was confused since in the history only the "added this to the 3.2.0-Beta milestone" entry is shown, without showing it to be updated since back in July.

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet.Client/commit/90167c9b9b4e8d7c442c7d67c19efa6a8e745745
