### ISSUE TITLE
.NET Core Global Tool support

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8631]
@kbilsted commented on [Fri Sep 20 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1690)

When targeting multiple frameworks, nuget no longer displays ` This package contains a .NET Core Global Tool you can call from the shell/command line.` and you cannot install your tool through the command line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d8ea9f-7126-5908-64c1-68cbd135bd91
* Version Independent ID: a6f41006-95fc-bd79-6885-812d01f7872d
* Content: [Multi-targeting for NuGet Packages in your project file](https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file#feedback)
* Content Source: [docs/create-packages/multiple-target-frameworks-project-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/create-packages/multiple-target-frameworks-project-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by kbilsted** [comment]
You can test the behaviour by adding net452 to the `TargetFrameworks` of https://github.com/kbilsted/WhitespaceWarrior/blob/master/WhiteSpaceWarrior/WhiteSpaceWarrior.csproj

**Comment by nkolev92** [comment]
@kbilsted 

Can you please clarify where you see that message? 

I'm not aware of the NuGet Client emitting any such message.

**Comment by kbilsted** [comment]
"This package contains a .NET Core Global Tool you can call from the shell/command line." is displayed here https://www.nuget.org/packages/WhiteSpaceWarrior/ 

But more importantly, the easy installation in the console (`dotnet tool install ...`) is not working when you multitarget.

**Comment by nkolev92** [comment]
Ah, your point was about nuget.org. I will move this issue there. 

> But more importantly, the easy installation in the console (dotnet tool install ...) is not working when you multitarget.

Can you clarify this? 
When you multi target the package? 

That's supported and at tool install time, the best matching assets are selected.

**Comment by kbilsted** [comment]
Not sure where it belongs. It also ruins the installer through the `dotnet`

**Comment by nkolev92** [comment]
@kbilsted 

> Not sure where it belongs. It also ruins the installer through the dotnet

Can you please clarify this? 
I'm not sure I follow. Do you see a failure? What kind of failure do you see? 
Thanks.

**Comment by kbilsted** [comment]
The v1.0.0 of the tool is build using multitarget both .net core and .net framework. when I install it now i get

	PS C:\> dotnet tool install  --version 1.0.0 --tool-path c:\temp  whitespacewarrior
	error NU1212: Invalid project-package combination for WhiteSpaceWarrior 1.0.0. DotnetToolReference project style can only contain references of the DotnetTool type
	The tool package could not be restored.
	Tool 'whitespacewarrior' failed to install. This failure may have been caused by:

	* You are attempting to install a preview release and did not use the --version option to specify the version.
	* A package by this name was found, but it was not a .NET Core tool.
	* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
	* You mistyped the name of the tool.

	For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by nkolev92** [comment]
@kbilsted 
1.0.0 seems to be built incorrectly. 
NuGet and dotnet rely on a package type to understand which packages are tools. 

If you look at the 1.0.1 nuspec it has:

```xml
    <packageTypes>
      <packageType name="DotnetTool" />
    </packageTypes>
``` 
and if you look at the nuget.org page it has the instruction to install via dotnet tool. 
https://www.nuget.org/packages/WhiteSpaceWarrior/1.0.1

On the other hand the 1.0.0 nuspec doesn't have the package type metadata, so it can't be used as a tool.
Similarly the nuget.org tool contains instructions. 
https://www.nuget.org/packages/WhiteSpaceWarrior/1.0.0

So based on what I see, the error is as expected and should not be related to the fact that the package contains more than 1 framework. 


Note that as far as I'm aware (since dotnet tool is not a feature we own), having a dotnet tool target .NET Framework is not useful, since it will be used. 

How was the 1.0.0 tool built? 
Custom nuspec? 
Maybe there's an issue with PackAsTool?

**Comment by kbilsted** [comment]
Yes my bad, if I change the csproj to 
`<targetframeworks>netcoreapp2.1;net452;net472</targetframeworks>` I get the error 

    Severity	Code	Description	Project	File	Line	Suppression State
    Error	NETSDK1054	only supports .NET Core.	WhiteSpaceWarrior	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.PackTool.targets	77

**Comment by nkolev92** [comment]
@kbilsted 

Are all your concerns addressed here? 

Feel free to close if so, happy to help more if needed.

**Comment by nkolev92** [comment]
Closing per the above comments.
