### ISSUE TITLE
Build error due to incompatible fx 

### ISSUE THREAD

**Issue by sebastianslutzky** [NuGet/Home#8632]
Hello,
I am getting the following compile error running . .\build.ps1 -skipunittest -f

E:\github\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\NuGet.PackageManagement.VisualStudio.csproj  : error NU1201: Project NuGet.Indexing is not compatible with net461 (.NETFramework,Version=v4.6.1). Project NuGet.Index ing supports: net472 (.NETFramework,Version=v4.7.2) [E:\github\NuGet.Client\build\restorehelper.targets]
E:\github\NuGet.Client\src\NuGet.Clients\NuGet.PackageManagement.VisualStudio\NuGet.PackageManagement.VisualStudio.csproj  : error NU1201: Project NuGet.VisualStudio.Common is not compatible with net461 (.NETFramework,Version=v4.6.1). Project
NuGet.VisualStudio.Common supports: net472 (.NETFramework,Version=v4.7.2) [E:\github\NuGet.Client\build\restorehelper.tar gets]

My environment Info:
.NET Core SDKs installed:
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.302-preview-010246 [E:\github\NuGet.Client\cli\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]

```
    Hive: HKEY_LOCAL_MACHINE\software\Microsoft\NET Framework Setup\NDP\v4


Name                           Property
----                           --------
Client                         Version       : 4.7.02558
                               TargetVersion : 4.0.0
                               Install       : 1
                               MSI           : 1
                               Servicing     : 0
                               Release       : 461310
                               InstallPath   : C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\
Full                           Version       : 4.7.02558
                               TargetVersion : 4.0.0
                               Install       : 1
                               MSI           : 1
                               Servicing     : 0
                               InstallPath   : C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\
                               Release       : 461310
```

**Comment by nkolev92** [comment]
@sebastianslutzky 

What's the commit sha of the repo? 
We made that change ~1 year ago.
And it was done in one commit, all projects were moved at the same time. 
https://github.com/NuGet/NuGet.Client/commit/48179681099a91a61ad398628756f23075e9b6b1

**Comment by nkolev92** [comment]
Closing this as stale. 

I hope you were able to resolve these issues :)
