### ISSUE TITLE
Reference latest version of a prelease tag or metadata pattern

### ISSUE THREAD

**Issue by TFTomSun** [NuGet/Home#8633]
Is there any possibility to reference the latest version with a specific prerelease or metadata tag?

I tried:

```xml 
<PackageReference Include="MyPackage" Version="*+myTag" /> -> invalid package version string
<PackageReference Include="MyPackage" Version="*-myPrerelaseTag" />  -> invalid package version string

<PackageReference Include="MyPackage" Version="[1.0.0+myTag, 9999.0.0+myTag]" /> -> does not resolve to the latest package with the given tag
 
<PackageReference Include="MyPackage" Version="[1.0.0-myPrerelaseTag, 9999.0.0-myPrerelaseTag]" /> -> does not resolve to the latest version with the given prerelease tag

```

Any other option? I need to categorize the packages based on branch names. I want to be able to get the latest version for one specific branch.

**Comment by rrelyea** [comment]
Likely this could be enabled when we support `"*-*"` (two wildcards). @nkolev92 - can you please confirm and dupe if true.

**Comment by nkolev92** [comment]
I think prerelease metadata should not be part of version matching by design, because it violates https://semver.org/#spec-item-11. 

As far prerelease tags #912 is an equivalent ask. 

Currently there are no options.
