### ISSUE TITLE
The NuGet package didn't resolve 

### ISSUE THREAD

**Issue by miaoyukai** [NuGet/Home#8635]
![image](https://user-images.githubusercontent.com/38027640/65755707-36829a80-e146-11e9-9b40-4c7a561c0a16.png)
I created a grpc project on vs that was not available.

**Comment by rrelyea** [comment]
I just created a new gRPC project with VS 16.3.x.
It brought in 2.23.1 by default...which took a while to download all the packages it brought it.
Then i upgraded to 2.23.2 via the Package Manager UI.
It also upgraded fine, and was able to remove the warning from the solution explorer and intellisense worked.

If this behavior continues, or many other people see it, please give more details about how you got there and what you saw.
