### ISSUE TITLE
[Bug Bash][Test Failure] The empty/malformed lock file should not be updated when running ‘dotnet restore --use-lock-file --locked-mode’

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8640]
## Details about Problem
NuGet version: NuGet Client Dev\5.4.0.6261
VS Version: Master\29327.122
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps
1.	Create a .NET Core Console App project.
2.	Create an empty or invalid packages.lock.json file next to the .csproj file.
3.	Run dotnet restore --use-lock-file --locked-mode.
## Expected
Verify the process should fail with an error saying the lock file is incorrect. It should not update the lock file since --locked-mode was set.
## Actual
The error message said the lock file is inconsistent with the project dependencies instead of incorrect, and the lock file is updated with a wrong version as below screenshot.
![WrongVersion](https://user-images.githubusercontent.com/20632625/65829984-d6266100-e2dd-11e9-8785-9d2c1a767e16.png)

## Note
1.It repro on 16.2 GA 29116.123 (implicit NuGet Client 5.2.0.6090).
2.Please refer to the bug #8160.

**Comment by donnie-msft** [comment]
I couldn't repro on:

- VS 16.4.0 Preview 2.0 [29403.147.master]
- dotnet 3.1.100-preview1-014394

//cc @nkolev92 anything jump out to you ?

**Comment by nkolev92** [comment]
I can repro this with a malformed lock file.

> Verify the process should fail with an error saying the lock file is incorrect. 

I don't think that was ever the requirement. I'm referring to the language of incorrect vs inconsistent. 
The requirement is for NuGet for the operation to fail and that does happen. 
The 1004 was what implemented as a response to #8160. 

I think there's a valid argument that the message could be better though.

> It should not update the lock file since --locked-mode was set.

This is a good point. 
In locked mode, we should never update the lock file, it's output only.

**Comment by erdembayar** [comment]
@nkolev92  @aortiz-msft 
Is it compatibility tenet issue?

**Comment by v-luzh** [comment]
This bug is fixed on Main\31101.164 + NuGet Client Dev\5.10.0.7152. Close it now, thanks.

**Comment by nkolev92** [comment]
This was fixed by @kartheekp-ms!
gj @kartheekp-ms
