### ISSUE TITLE
Xamarin projects in Visual Studio do not use .targets in NuGet package references

### ISSUE THREAD

**Issue by danielcrenna** [NuGet/Home#8642]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used: VS2019 UI

## Detailed repro steps so we can see the same problem

1. Create a new Xamarin.iOS or Xamarin.tvOS application from the template.

2. Reference a NuGet package that uses a custom .targets file located in `\build`

It appears Xamarin projects in Visual Studio ignore the `.targets` file that ships with a NuGet package reference. Furthermore it is not possible to use `GeneratePathProperty` on the `PackageReference` to workaround this by manually importing the .targets file, since the path is not generated:

```xml
 <ItemGroup>
    <!-- GeneratePathProperty is ignored -->
    <PackageReference Include="fnalibs" GeneratePathProperty="true">
      <Version>19.9.0-pre</Version>
    </PackageReference>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\TVOS\Xamarin.TVOS.CSharp.targets" />
  <!-- .targets file is not used by Xamarin projects in VS (and this workaround doesn't work) -->
  <Import Project="$(Pkgfnalibs)build\fnalibs.targets" />
```

**Comment by rrelyea** [comment]
I was able to get both working fine with VS 16.3.

Repro steps:
1) file new project > iOS App (Xamarin)
2) created an sdk style project to build a package to use:
    dotnet new classlib -o buildtargets
    add buildtargets.targets to root of project with the following content:
```
<Project>
    <Target Name="DoIt">
        <Message Text="Did it DoIt?" />
    </Target>
</Project>
```
    modify csproj to be:

```
    <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <None Include="buildtargets.targets" Pack="True" PackagePath="build\buildtargets.targets" />
  </ItemGroup>
</Project>
```

build the package via dotnet pack
add the package to the ios project (first create a local package source that has the buildtargets.*.nupkg in it.  
Hand edit that packagereference to include generatepathproperty:
```
    <PackageReference Include="buildtargets" GeneratePathProperty="true">
      <Version>1.0.0</Version>
    </PackageReference>
```

next) restore and build the ios app.
look at obj\*.g.targets to confirm that GeneratePropertyPath works.

run "msbuild /t:doit" from command line in the ios app directory.

For me, this all worked.

**Comment by rrelyea** [comment]
@danielcrenna  - please chime in if this is still a problem for you.

**Comment by danielcrenna** [comment]
@rrelyea Thanks, Rob. I'll try this tonight and will respond/re-open if I run into anything further. It looks like the same steps I applied during exploration.
