### ISSUE TITLE
Lock File not properly generated - framework ordering should not impact the restore with lockedmode

### ISSUE THREAD

**Issue by carpnick** [NuGet/Home#8645]
## Details about Problem

**NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):**
VS UI, MSBuild CLI, Nuget.exe

**NuGet version (x.x.x.xxx):**
- nuget version  5.3.0.6260
- MSBuild  version - 16.3.0+0f4c62fea for .NET Framework
   - Nuget CommonExtension installed version - Nuget.Commands.dll - 5.3.0.6251

**VS version (if appropriate):**
 [Information](https://gist.github.com/carpnick/a275bf0be54960cfa8892eeee9916e0c#file-vs-versioning) 

**OS version (i.e. win10 v1607 (14393.321)):**
10.0.17763 Build 17763 -  Windows Server 2019 Datacenter

**Worked before? If so, with which NuGet version:**
MSbuild based restore - 15.9.21+g9802d43bc3
  - Project dependend on - NuGet.Build.Tasks.Pack 4.9.2

## Detailed repro steps so we can see the same problem

Run all these steps from within Visual Studio 2019 (See version info)
1. Create a new .NET solution with a class library (full framework).
2. Add a nuget reference to Newtonsoft.json (any will do)
3. Edit csproj file and add `<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>`
4. Reload project.  Build.
5.  Validate the packages.lock.json is generated.  See [example](https://gist.github.com/carpnick/a275bf0be54960cfa8892eeee9916e0c#file-packages-lock-json).
6. Edit CSPROJ again, this time add the following line:
` <RestoreLockedMode>true</RestoreLockedMode>`
7. Reload the project, and attempt to rebuild, 2 times.

Error Received:
`Error	NU1004	The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.			1		
`

MSBuild CLI to reproduce: `& 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' /t:"clean;Restore" /p:Configuration="Release" /p:Platform="Any CPU" /p:RestoreLockedMode="true" /p:RestoreNoCache="true"`

NOTE: We did not stumble on this issue like this, we stumbled on this setting RestoreLockedMode in our CI process to true.  But the above steps produce a reliable easy way to reproduce.

## Other suggested things

Other notes:

- When you allow MSBuild or VS to ForceEvaluate - it keeps generating incorrect package lock files.
- nuget.exe works as expected  - CLI `C:\nuget.exe restore -lockedmode -NoCache`
- **What is broken** - Copied Nuget.Clients Source privately from this [tag](https://github.com/NuGet/NuGet.Client/tree/5.3.0.6251).
    - At [this location](https://github.com/NuGet/NuGet.Client/blob/5.3.0.6251/src/NuGet.Core/NuGet.ProjectModel/ProjectLockFile/PackagesLockFileUtilities.cs#L105-L108) I added [this code](https://gist.github.com/carpnick/a275bf0be54960cfa8892eeee9916e0c#file-privatepatch) to my private copy.  When I run with my private version with Visual Studio or MSBuild CLI, I get the [following](https://gist.github.com/carpnick/a275bf0be54960cfa8892eeee9916e0c#file-msbuild-custom-output).  Notice the order is different.  When I run with my private version of nuget.exe I get [this](https://gist.github.com/carpnick/a275bf0be54960cfa8892eeee9916e0c#file-custom-nuget-exe).

### Workaround available
 - Modify lock file after it is generated and modify the order of the .NETFrameworks. (This would be very painful from a developer point of view, but does offer a workaround).
 - Another option is to not use MSbuild /t:restore and instead use nuget.exe

### Sample Project

Very helpful if you can zip a project and paste into this issue!
[ExampleSolution.zip](https://github.com/NuGet/Home/files/3672626/ExampleSolution.zip)

PS:
This was very helpful in debugging down to where the issue was: https://github.com/NuGet/Home/issues/8493#issuecomment-526375416

Thanks @nkolev92

**Comment by carpnick** [comment]
This was very helpful in debugging down to where the issue was: https://github.com/NuGet/Home/issues/8493#issuecomment-526375416

Thanks @nkolev92

**Comment by carpnick** [comment]
Potential fix.  Replace [these 2 lines](https://github.com/NuGet/NuGet.Client/blob/5.3.0.6251/src/NuGet.Core/NuGet.ProjectModel/ProjectLockFile/PackagesLockFileUtilities.cs#L105-L106) with the following:

```
var projectRuntimesKeys = project.RuntimeGraph.Runtimes.Select(r => r.Key).Where(k => k != null).AsList();
var lockFileRuntimes = nuGetLockFile.Targets.Select(t => t.RuntimeIdentifier).Where(r => r != null).Distinct().AsList();
projectRuntimesKeys.Sort();
lockFileRuntimes.Sort();
```

**Comment by carpnick** [comment]
Looks like a sort is happening on the writer side - https://github.com/NuGet/NuGet.Client/blob/5.3.0.6251/src/NuGet.Core/NuGet.Packaging/RuntimeModel/JsonRuntimeFormat.cs#L77

**Comment by nkolev92** [comment]
I think the root cause is: 

https://github.com/NuGet/NuGet.Client/commit/ee368364795a580a09e3fc8542fff7930485e606

fyi @cristinamanum 

> @carpnick Potential fix. 

I think there's a compare utility that accounts for the order.
https://github.com/NuGet/NuGet.Client/blob/dev/build/Shared/EqualityUtility.cs#L23
I'd use that. 

@carpnick since you've already done all the work, do you want to open a PR for this? 

You can add a test similar to the ones in the above commit.

**Comment by nkolev92** [comment]
Addressing the other suggested things: 

> When you allow MSBuild or VS to ForceEvaluate - it keeps generating incorrect package lock files.

MSBuild has a property to force reevaluate. dotnet restore is just a wrapper for dotnet msbuild /t:restore
Unfortunately the docs are lacking 
https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#restore-command-line-options. 

Created a docs issue for that: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1717

> nuget.exe works as expected - CLI C:\nuget.exe restore -lockedmode -NoCache

Are you suggesting nuget.exe works but the msbuild doesn't? 
They have the exact same validation code as long as the VS and nuget.exe versions are analogous. 

Specifically 16.3 <=> 5.3 

I'd be surprised if that's case so it's worth an extra look.

**Comment by carpnick** [comment]
Yes @nkolev92  which is why I am so confused.  

I was testing with 16.3.0+0f4c62fea of MSBuild which has the DLL in the CommonExtensions folder with a version of 5.3.0.6251....

However, when I test the same exact solution with nuget.exe  which is version 5.3.0.6260, it is working...  I know not the exact same build but close.  These 2 commands were run back to back below.


Nuget.exe output:
```
C:\nuget.exe
NuGet Version: 5.3.0.6260
```
```
c:\temp\Eliza-Eliza.Sample.VS2017.MSI>C:\nuget.exe restore -lockedmode -NoCache
MSBuild auto-detection: using msbuild version '16.3.0.46305' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'.
Restoring packages for c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\Utilitylib.unittests.csproj...
Restoring packages for c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\Eliza.Sample.VS2017.MSI.Utilitylib.csproj...
Committing restore...
Committing restore...
Writing assets file to disk. Path: c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\obj\project.assets.json
Assets file has not changed. Skipping assets file writing. Path: c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\obj\project.assets.json
Restore completed in 726.6 ms for c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\Eliza.Sample.VS2017.MSI.Utilitylib.csproj.
Restore completed in 726.54 ms for c:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\Utilitylib.unittests.csproj.

NuGet Config files used:
    C:\Users\Administrator\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json
```


MSBUILD:
```
PS C:\temp\Eliza-Eliza.Sample.VS2017.MSI> & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' /t:"Restore" /p:Configuration="Release" /p:Platform="Any CPU" /p:RestoreLockedMode="true" /p:RestoreNoCache="true"
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 9/30/2019 9:18:45 PM.
Project "C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln" on node 1 (Restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
ValidateProjects:
  The project "test1" is not selected for building in solution configuration "Release|Any CPU".
C:\temp\Eliza-Eliza.Sample.VS2017.MSI\SetupProject1\SetupProject1.wixproj : warning NU1503: Skipping restore for project 'C:\temp\Eliza-Eliza.Sample.VS2017.MSI\SetupProject1\SetupProject1.wixproj'. The project file may be invalid or mis
sing targets required for restore. [C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln]
Restore:
  Restoring packages for C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\Utilitylib.unittests.csproj...
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(123,5): error NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run
 in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file. [C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln]
  Committing restore...
  Assets file has not changed. Skipping assets file writing. Path: C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\obj\project.assets.json
  Writing packages lock file at disk. Path: C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\packages.lock.json
  Restore failed in 90.33 ms for C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib\Eliza.Sample.VS2017.MSI.Utilitylib.csproj.
  Committing restore...
  Writing assets file to disk. Path: C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\obj\project.assets.json
  Restore completed in 476.04 ms for C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Utilitylib.unittests\Utilitylib.unittests.csproj.

  NuGet Config files used:
      C:\Users\Administrator\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
Done Building Project "C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln" (Restore target(s)) -- FAILED.


Build FAILED.

"C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln" (Restore target) (1) ->
(_FilterRestoreGraphProjectInputItems target) ->
  C:\temp\Eliza-Eliza.Sample.VS2017.MSI\SetupProject1\SetupProject1.wixproj : warning NU1503: Skipping restore for project 'C:\temp\Eliza-Eliza.Sample.VS2017.MSI\SetupProject1\SetupProject1.wixproj'. The project file may be invalid or m
issing targets required for restore. [C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln]


"C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln" (Restore target) (1) ->
(Restore target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(123,5): error NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be r
un in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file. [C:\temp\Eliza-Eliza.Sample.VS2017.MSI\Eliza.Sample.VS2017.MSI.solution.sln]

    1 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.28
```

**Comment by carpnick** [comment]
I will look at doing a PR to handle the use case, but I figured I would mention the ordering being different in MSBuild vs Nuget.exe in case there is some oddness on the DepGraph load side.

**Comment by nkolev92** [comment]
That's a good point. 
Task restore(msbuild, dotnet) generates the Dep graphs in memory and uses the same. NuGet.exe relies on the graph generated by the invocation of an msbuild task, and that'll have things sorted.
