### ISSUE TITLE
Certificate error on https://nuget.smbsrc.net

### ISSUE THREAD

**Issue by xuzhg** [NuGet/Home#8647]
It's failed to upload the symbols to the symbols sever, the error message:

![image](https://user-images.githubusercontent.com/9426627/65919348-e4818500-e390-11e9-87df-4ac052329dcc.png)

I tried the nuget.exe 5.2.0 version. It's same error message. 

How can we upload the symbols server again?

**Comment by donnie-msft** [comment]
@xuzhg thanks for letting us know, moving to NuGet Gallery

**Comment by donnie-msft** [comment]
Issue moved to [NuGet/NuGetGallery #7598](https://github.com/NuGet/NuGetGallery/issues/7598) via [**ZenHub**](https://www.zenhub.com/)
