### ISSUE TITLE
Imports Newtonsoft.Json in VS 2010

### ISSUE THREAD

**Issue by abhisheka1993** [NuGet/Home#8649]
I want to imports Newtonsoft.Json in vs 2010 for converting the xml string into json but I am not able to add it with version 2.12+
anyone knows how to fix this

**Comment by donnie-msft** [comment]
Which command are you executing and what error message are you seeing? Also, I'm not clear if you're using NuGet.exe or VS2010, as those are separate products.

**Comment by abhisheka1993** [comment]
I am using vs2010 in that I want to add the reference of Newtonsoft.json but it's unable to add

**Comment by donnie-msft** [comment]
Can you copy/paste the error message, or take a screenshot of the error? Are you using the Install tab in "Manage NuGet Packages" or Package Manager Console?
