### ISSUE TITLE
Allow SDK-style Package Installs

### ISSUE THREAD

**Issue by JaimeStill** [NuGet/Home#8654]
## Details about Problem

Most of the work I do with .Net Core is in an offline environment. Currently, if I want to update the global nuget cache on my offline environment, I have to update dependencies with the `dotnet` CLI as follows:

```
dotnet add package <package> --package-directory <path-to-directory>
```

This is because of:  

![image](https://user-images.githubusercontent.com/14102723/65997274-0f3e0d00-e467-11e9-9f01-e67543bfd106.png)  
> From [Installing NuGet client tools](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#cli-tools)

Where I work, I have access to the `nuget` CLI, but cannot install .NET Core SDK on my internet-connected machine. This means that all of my dependency updates have to be done at home.

Being able to specify the platforms the `nuget` CLI commands installs for would be extremely helpful. Perhaps something similar to:

```
nuget install <package> -Source <source> -OutputDirectory <path-to-output> 
-Framework netcoreapp3.0
```

**Comment by rrelyea** [comment]
We don't plan to move dotnet add package to nuget.exe.
Longer term, we'll likely finish moving all valuable commands from nuget.exe to dotnet.exe, and we'll retire nuget.exe. Sorry.

**Comment by JaimeStill** [comment]
The dotnet CLI team says this [is a NuGet issue](https://github.com/dotnet/cli/issues/12764#issuecomment-537685513):

> This is still an issue that needs to be looked at by NuGet. They own dotnet restore, even though it is surfaced through the CLI. They also own package restore and what you are asking is a variation of that.

**Comment by rrelyea** [comment]
This is not a normal request. Why cannot you have netcore sdk on your machine????

**Comment by JaimeStill** [comment]
I'm a government contractor who builds apps on a disconnected, classified network. I have administrative privileges to the classified network for the sake of conducting app development. However, the unclassified network is restrictively locked down, and getting resources installed that require administrative privileges is a bureaucratic effort to say the least. My best alternative, currently, is to drive 30 - 40 minutes home, obtain the packages, and bring them in on disk.

**Comment by rrelyea** [comment]
Perhaps something like this would work for you today:

Nuget.exe locals clear all
File new project.
Choose right TargetFramework in csproj.
Hand add 1 or more package referenceS to that csproj.
Run nuget.exe restore in csproj.
Voila - copy all the downloaded packages from global package folder.

If that works, would be easy to make a command line tool that did those steps for you.

Sound good?

**Comment by JaimeStill** [comment]
`nuget.exe` version: **5.3.0**  

Gave this a shot, and it doesn't work. Here are the details:

Created a project using `dotnet new classlib -f netcoreapp3.0`.

Here is the `.csproj`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
  </ItemGroup>
</Project>
```

And the attempt to restore via `nuget.exe` after wiping the local cache:  

![failed-restore](https://user-images.githubusercontent.com/14102723/66209099-ac29c180-e684-11e9-84e4-6495e04baa95.png)  

Looks like even though the project is a .NET Core project, it's trying to build with .NET Framework?
