### ISSUE TITLE
Question: What is a Nuget Integrated Project?

### ISSUE THREAD

**Issue by maxinfet** [NuGet/Home#8655]
I just have a question about what kind of project does INuGetIntegratedProject map to? Is this a project that uses package.config or is this a project that uses package references?

**Comment by donnie-msft** [comment]
INuGetIntegratedProject is the way NuGet represents a project in VS, for interacting with project systems. It does not represent package.config projects; only PackageReference or project.json projects.

Closing, but let us know if you have other questions!
