### ISSUE TITLE
Issue with replacing deprecated '<iconUrl>' with '<icon>'

### ISSUE THREAD

**Issue by MarioZ** [NuGet/Home#8660]
# Details about Problem

I'm trying to make the replacement that was suggested when I recently uploaded ".nupkg".  
I've added the new `icon` element to my ".nuspec" file, but when trying to PACK it using "nuget.exe - recommended latest v5.2.0" I get the following error:

>The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'icon' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'contentFiles, iconUrl, developmentDependency, copyright, releaseNotes, repository, references, language, summary, dependencies, description, serviceable, tags, frameworkReferences, packageTypes, licenseUrl, frameworkAssemblies' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. This validation error occurred in a 'icon' element.

# Detailed repro steps so we can see the same problem

1. Create "sample.nuspec" with 'icon' element:

```xml
<package>
  <metadata>
    ...
    <icon>images\icon.png</icon>
    ...
  </metadata>
  <files>
    ...
    <file src="..\icon.png" target="images\" />
    ...
  </files>
</package>
```
2. Download [nuget.exe - recommended latest v5.2.0](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe).

3. Run command:

```powershell
nuget.exe Pack sample.nuspec
```

**Comment by MarioZ** [comment]
Also a side question if I may ask, what will happen with an older package releases that had `iconUrl`, will they continue to use that URL?
Basically what I'm asking is, do we now need to maintain both URL and the content file?

I can understand that for `licenseUrl` that was unavoidable, but in this case I believe you could handle the fallback of missing `iconUrl`.
Would you be open to that, help us package developers with handling these changes that you're introducing?

**Comment by rrelyea** [comment]
You need NuGet 5.3 to support Package Icons. We typically wait to make sure nobody finds a critical problem in it before we bless it (which turns on a few autoupdate mechanisms)

Over time, we'll stop using the iconurl.
Nuget.org will copy most of those icons to its own storage, so that even new clients will work with old packages.

It is possible for you to include both for now...it will make the warning go away for now.
At some later date, it will likely come back if you still have the URL around.

**Comment by MarioZ** [comment]
I thought that might be the case, which is why I emphasized that I was using "recommended latest v5.2.0".
I think it's good that you removed the warning.
Also, I think that upload on "nuget.org" should really be in sync with the recommended "NuGet.exe".

Anyway, it's great that you're planning on storing locally the `iconurl` images sometime in the future.
Will we be notified when this happens or will there be some news / feed?

Also, you mentioned "most of those icons", can you tell me what is the criteria, which icons will be stored?
Will it depend on the package itself, like how popular it is or if it's still active (has some recent uploads) or something else?

**Comment by kartheekp-ms** [comment]
NuGet.exe 5.3.0 version is now promoted as recommended latest version and can be downloaded from [here](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe). Refer [release notes](https://docs.microsoft.com/en-us/nuget/release-notes/) to learn more about new features and bug fixes for every release.
