### ISSUE TITLE
support for envvars in NuGet.config - improve docs for xplat behavior

### ISSUE THREAD

**Issue by infin8x** [NuGet/Home#8662]
## Details about Problem

NuGet product used: dotnet on Mac

dotnet.exe --version (if appropriate): 2.2.104

OS version (i.e. win10 v1607 (14393.321)): macOS Mojave 10.14.6

Worked before? If so, with which NuGet version: [Was No, @rrelyea added comment with link to docs. Perhaps this is a dotnet.exe bug only?]

## Detailed repro steps so we can see the same problem

1. Set up NuGet.configs and add a valid token to your environment like so:
![image](https://user-images.githubusercontent.com/483400/66218569-4afeef80-e67e-11e9-926d-5a9ecd9275c9.png)

2. Attempt to run `dotnet restore`:
![image](https://user-images.githubusercontent.com/483400/66218642-71bd2600-e67e-11e9-9f48-2e37b07c815f.png)

3. Move token to file directly (to prove that it's a valid token and not a server-side issue):
![image](https://user-images.githubusercontent.com/483400/66218735-a204c480-e67e-11e9-9c8d-4e2565542dd1.png)

_Note: I know there is a token in these screenshots. I revoked it before publishing._

### Verbose Logs

[log.txt](https://github.com/NuGet/Home/files/3691141/log.txt)

### Sample Project

You can git clone https://github.com/infin8x/starter-packages and use the `nuget-bacon` package.

**Comment by infin8x** [comment]
@anangaur sorry for the long delay, but here's the issue I promised to file.

**Comment by rrelyea** [comment]
Looks like I evolved the title badly. We do support envvars in nuget.config, and it should work on mac/linux too.
https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables

**Comment by rrelyea** [comment]
This works fine with dotnet.exe 3.0 on windows:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget" value="%myfeed%" />
    <add key="local" value="%localfeed%" />
  </packageSources>
</configuration>
```

**Comment by rrelyea** [comment]
@infin8x - can you try %NUGET_AUTH_TOKEN% instead of $NUGET_AUTH_TOKEN.
I think we call [ExpandEnvironmentVariables](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables?view=netcore-3.0), which doesn't document different character behavior on different platforms. Also, trying netcore 3.0 might be best...so we can test our latest behavior.

**Comment by infin8x** [comment]
No dice, that also fails, even after I install netcore 3.0.

Simplest repro of this:
1. Clone the repo I referenced above, on a Mac.
2. Make `.nuget\nuget\nuget.config` like the example below.
3. Add your token as an envvar.
4. Run `dotnet restore`.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
<packageSourceCredentials>
    <GPR>
      <add key="username" value="infin8x" />
      <add key="cleartextpassword" value="%NUGET_AUTH_TOKEN%" />
    </GPR>
  </packageSourceCredentials>
</configuration>
```

**Comment by infin8x** [comment]
But, I agree that this works on Windows, I think this is a Mac(/Linux)-only issue.

**Comment by rrelyea** [comment]
Looks like %foo% works fine on dotnet.exe 3.0 on linux (ubuntu 18.4)
I tested, with success, against a private azure artifacts feed (devdiv/vs)
Then I tested against a GPR feed ... w/o success.

My guess is that this is GPR implementation related.
If you can help me get GPR access...i'll dig into this more next week.
However, i think you could try both scenarios i mention...and see the difference in GPR implemetantion of communication with nuget client.

**Comment by rrelyea** [comment]
@infin8x - see my last comment.

**Comment by rrelyea** [comment]
work remaining here is to make sure we improve our docs.

**Comment by infin8x** [comment]
Sorry for the delay here, I think someone from the GPR team is digging in more to what's going on here. But, glad to know the envvar works. Looking forward to the docs improvement.

**Comment by rrelyea** [comment]
there is a modified section about env vars in config files here: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#using-environment-variables
It properly covers x-plat env var techniques.

also https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#packagesourcecredentials has been updated with a sample.
