### ISSUE TITLE
VS2010 plugin doesn't remember passwords

### ISSUE THREAD

**Issue by andrewducker** [NuGet/Home#8666]
## Details about Problem
NuGet version (x.x.x.xxx): 4.3.0.4406

VS version (if appropriate): 2010

OS version (i.e. win10 v1607 (14393.321)): 7

## Detailed repro steps so we can see the same problem

1. Open a VS2010 solution with a bunch of dependencies coming from a local NuGet repository.  Open "Manage NuGet packages for Solution".

2. See the "Some NuGet packages are missing from this solution.  Click to Restore..." and click the Restore button.

3.  Get hit with the password prompt every time, despite having put the correct password in when setting up the NuGet sources.  If I hit "cancel" then it tells me there was a "(401) Unauthorized."

Things that I've tried:
Running "nuget restore" on the solution.  This works perfectly, and uses the password set in the nuget.config file.

Theories I have:
The VS2010 nuget plugin doesn't support using the saved password.
The format that NuGet 4 uses to store the password isn't supported by the VS2010 plugin.

Additional Info:
The package is hosted on a Nexus server.
But as it works with "nuget restore" I'm fairly sure that that's not the issue.

I know that we should be moving off of VS2010, but it would be good to know if this issue will go away when we do (and would help build the business case for doing so).

This is an issue in the project because there are over a hundred dependendies, and it's a massive pain having to enter your password that many times!

**Comment by rrelyea** [comment]
I would hope that this would have improved...but I'm unable to test. I think that it is more appropriate for you to ask this question of the Nexus community.

Perhaps: https://support.sonatype.com/hc/en-us/requests/new

**Comment by andrewducker** [comment]
I don't believe it's a Nexus issue - otherwise "nuget restore" wouldn't work.

I strongly suspect that it was fixed by this pull request:
https://github.com/NuGet/NuGet.Client/pull/1513

But that this wouldn't apply to a VS2010 plugin, as they weren't being produced by then.

Would anyone on the NuGet team be able to confirm this?

**Comment by rrelyea** [comment]
Sorry. We aren't able to verify. 
Even before that commit, we worked just fine for many cached credentials with many nuget servers in VIsual Studio.

It would be probably be best for you to try VS2017 or VS2019 in your environment, following any special instructions that your nuget server vendor provides.

**Comment by andrewducker** [comment]
I've downloaded VS2019, and it works fine in that.  I'll work on getting us upgraded.  Thanks!

**Comment by dtivel** [comment]
NuGet/NuGet.Client#1513 was one half of the fix.  The other half of the fix was in Visual Studio 2017 itself.  It makes sense that the problem is resolved by moving from VS 2010 to VS 2019.
