### ISSUE TITLE
Determine if nuget source name is case-sensitive and ensure disable and other uses works properly given that

### ISSUE THREAD

**Issue by asherber** [NuGet/Home#8668]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.2.0.6090

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):  win10 v1709 (16299.1268)

Worked before? If so, with which NuGet version: Don't know

## Detailed repro steps so we can see the same problem

1. `nuget sources add -name FOO -source https://example.com`
1. `nuget sources list` (confirm new source is there)
1. `nuget sources disable -name foo` (nuget reports `Package source with Name: foo disabled successfully.`)
1. `nuget sources list` (source is still enabled!)
1. `nuget sources disable -name FOO` (nuget reports `Package source with Name: foo disabled successfully.`)
1. `nuget sources list` (source is disabled)

Note that `nuget sources remove -name foo` works just fine to remove a source whose name is `FOO`.

**Comment by kartheekp-ms** [comment]
Noticed that this issue was fixed in nuget.exe 4.8.2 version and broken in later releases.

**Comment by rrelyea** [comment]
Looked into this a bit. Looks like `nuget sources disable -name foo` will persist a disabled package source. However, it looks like packageSource FOO and disabledPackageSource foo are not found to match...so our system treats FOO as enabled.

Haven't looked at pre-4.9 behavior. (@kartheekp-ms said that 4.8.2 worked), but 4.9 is where we did major config file (setting) system enhancements.
Doing work for `dotnet nuget disable source` now... won't address this as part of that work, but we should fix.
