### ISSUE TITLE
Cannot hit NuGet server behind Azure AD

### ISSUE THREAD

**Issue by Greenstone3672** [NuGet/Home#867]
I created a NuGet server and pushed it to an Azure website as described in the following article: http://www.codeproject.com/Articles/872230/Create-Your-Own-Private-NuGet-Server-in-Windows-Az

The server worked just fine, as I could hit it from the browser or pull packages in Visual Studio 2013 with no issues.  When I tried to add Azure AD to secure it, I could still hit it fine through the browser (after the login step), but trying to list the packages using the VS manage NuGet packages dialog, the VS package manager console, or NuGet.exe does not work (I get 401s).  The credentials I used were my Microsoft account name and password, which I had added to the Azure AD group.

I saw that someone had been working on an Azure AD feature already, but I wasn't sure if that meant my use case was currently unsupported or if it was something extra: https://github.com/NuGet/Home/issues/708

My server is using the NuGet.Server package version 2.7.0.

**Comment by yishaigalatzer** [comment]
As the bug states there is no support for Azure AD in Visual Studio. There is a plug in model, where folks have written a plugin, but it does not work in Visual Studio. Please keep following #708 for more updates.
