### ISSUE TITLE
Stop displaying version duplicates in allowed and blocked versions list in PMUI

### ISSUE THREAD

**Issue by KarthickR5** [NuGet/Home#8679]
In VS Manage Nuget Packages window, When choose nuget from browse and see the listed versions, the message showing like   **Blocked by package.config** after under this message all the version again listed. This is for all packages in nuget.org.

Can anyone tell me the reason why shown that message like that?
![image](https://user-images.githubusercontent.com/56252418/66559927-e8bd5780-eb73-11e9-8bd6-932dd3dc7ef9.png)

**Comment by kartheekp-ms** [comment]
The fix should be available in VS 16.4 Preview 3 on 11/6/2019

**Comment by mikehachen** [comment]
Is there a workaround for VS 2019 16.3.5?

**Comment by kartheekp-ms** [comment]
@mikehachen - Please select package versions displayed above "blocked by package.config" option. If there are any [constraints](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#constraining-upgrade-versions) defined in packages.config file then please choose the appropriate version. See [doc](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards) for more information about versioning in NuGet.

**Comment by nkolev92** [comment]
The fix only went into 5.4...fixing up the milestone.
