### ISSUE TITLE
No fallback to full framework TFM dll when other assets are in a package

### ISSUE THREAD

**Issue by lanfeust69** [NuGet/Home#8687]
NuGet.exe, version 5.2.0

## Detailed repro steps

1. Create a .Net Core 3 application

2. Add a PackageReference to a nuget package with content similar to
`build/MyPackage.targets`
`lib/net40/MyPackage.dll`

3. Execute `nuget restore`

We would expect a `NU1701` warning, and a `project.assets.json` containing
```json
      "MyPackage/1.2.3": {
        "type": "package",
        "compile": {
          "lib/net40/MyPackage.dll": {}
        },
        "runtime": {
          "lib/net40/MyPackage.dll": {}
        },
        "build": {
          "build/MyPackage.targets": {}
        }
      },
```
but instead, there is no warning, and the json is missing the `compile` and `runtime` entries.

Then of course, the dll isn't referenced in the compilation step, which fails if it is really needed.

## Root cause

The issue comes from [this code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/LockFileUtils.cs#L89,L98) : the `.targets` asset is compatible, so the less strict TFMs are not checked.

**Comment by zivkan** [comment]
If the targets file is moved to `build/net40/MyPackage.targets`, it will work as expected.

We have a different, but related pack warning, [NU5127](https://docs.microsoft.com/en-gb/nuget/reference/errors-and-warnings/nu5127), which is when a package contains a `build/<tfm>/<package_id>.[props.target]` file, but no `lib/` or `ref`/` folder, informing the package author that their package will be treated as being compatible with all TFMs, despire only having tfm specific build file(s). Perhaps we need another pack warning when there is only an all-tfm build file, but there are tfm specific assemblies.

I fear that changing Asset Target Fallback to ignore "all-tfm" assets from first round selection may cause problems as it would change the restore behaviour for many packages. On one hand, it's low effort for package authors to change their package to work better with existing nuget client behaviour. On the hand, developers moving to .NET Core 3.0 or higher, particularly for WinForms or WPF, may wish to use existing packages on nuget.org that may no longer be maintained, and therefore getting a new version of the package with the props/targets file might not be feasible.

**Comment by lanfeust69** [comment]
@zivkan : indeed, I came across this while exploring a migration to .Net Core 3, with legacy packages that hopefully would run as we want, but no obvious way to have an official new version of the package.

This is as you said a trade-off to be considered, I have no strong opinion on the subject : the only thing is that, in my opinion, current restore doesn't follow a path of "least surprising behavior", and I needed to spend a significant amount of time understanding why the assembly wasn't referenced (admittedly, the open-source nature of nuget helped a lot !).

We have been using nuget packages for a very long time, with needs to package thirdparty libraries that weren't available in nuget (at the time), or re-package (for strong naming for instance), so we're used to that, nothing blocking for us.

**Comment by nkolev92** [comment]
Thank you for creating this issue. 

AssetTargetFallback was an improvement over PackageTargetFallback which actually did the compatibility resolution of assets groups independently and would have returned what @lanfeust69 wanted it to return. 

However this proved problematic because it had many unintended consequences because the packages were not behaving as the author intended it. 

At this point it's too risky to consider doing a further change here.
