### ISSUE TITLE
ManagedCodeConventions is missing a definition for the 'resources' property

### ISSUE THREAD

**Issue by anurse** [NuGet/Home#869]
Try installing Microsoft.OData.Client in NuGet 3/project.json and you will get an exception thrown in the NuGet.ContentModel code. This is because the ContentModel attempts to match the satellite assembly and fails to find the resources property.

**Comment by yishaigalatzer** [comment]
This issue was found by the connected services teams testing their scenarios. Its a rather rare case of packages shipping localized resources inside the package rather than satellite packages, however a key package (OData client) is using this so it looks like a must fix.
