### ISSUE TITLE
Developer: Make it easier to work on integration tests within visual studio for Nuget.Client

### ISSUE THREAD

**Issue by carpnick** [NuGet/Home#8690]
Development Issue:
While working on https://github.com/NuGet/NuGet.Client/pull/3075, specifically adding a test to Dotnet.Integration.Test.DotnetRestoreTests, I was struggling to understand why debug builds were not working.  Currently the code depends on nuget packages (within artifacts/nupkgs) folder to be updated .  When you are trying to work on an integration test, VS doesnt by default run the pack target on the builds.

This lead to a couple hours wasted figuring out what the problem is for a new developer.  Suggest we update the copy to use the artifacts from the artifacts folders directly OR we make the default build targets also include the packaging of the packages.

**Comment by nkolev92** [comment]
Thank you filing this @carpnick 

I have fixed this in https://github.com/NuGet/NuGet.Client/commit/6da9b6f04cf0198d89ff90cba64ad6e5c8027dcd#diff-3a22160d75af0ed49d60562b6157b371

*edit* I had pasted the wrong link.
