### ISSUE TITLE
internal 3rd party nuget packages management using packagereferances?

### ISSUE THREAD

**Issue by RajuVCh** [NuGet/Home#8693]
Hi Team,

Kindly share any information on managing internal 3rdpary nuget packages. we are in the process migrating from packages.config. migration tools working for public nuget packages and for internal pacakges it nighter show log nor error. migrationbackup folder has packages.config file and .csproj file but not upgradelog.

VS Version 2017.

Thanks.

**Comment by zivkan** [comment]
Could you check [Visual Studio's activity log](https://docs.microsoft.com/en-us/visualstudio/ide/reference/log-devenv-exe?view=vs-2019), to see if any errors were reported there?

How is the private package source secured? Is it a Azure DevOps Artifacts feed? Is it another authenticated feed that needs a username and password in `nuget.config`? Is it an unauthenticated feed that is only available inside the corporate network?

Could you try copying the internal nupkgs to a folder on your computer, edit your `nuget.config` to add this folder as a package source, then try the migration again? This ensures the packages are available and on a feed that does not need authentication.

**Comment by RajuVCh** [comment]
Thanks for reply!

i don't see any related info in visual studio activity log. (i can share if needed)

We use Jfrog artifactory which needs authentication the details for authentication and packages source provided in nuget.config file in project.

i don't see upgrade log after migration when references section has internal dependency package dll's...and the same is available for public packages  which are available in artifactory along with internal package 

i tried to use a folder which has packages on my computer as package source in nuget.config but the same behaviour as above..

the scenario including public nuget packages and internal nuget packages works well with packages.config model

Kindly advise!
Thanks for your time.

**Comment by nkolev92** [comment]
Thank you for filing this issue.

@RajuVCh it's not clear to us what the exact issue you are facing here is. 
Can you please provide a detailed repro (or a video recording) of the problems you are hitting.

**Comment by kartheekp-ms** [comment]
@RajuVCh - Can you please provide feedback to above comments?
