### ISSUE TITLE
Adding a NuGet package to Visual Studio does not add .targets and .props files of package dependencies

### ISSUE THREAD

**Issue by SotoiGhost** [NuGet/Home#8694]
## Details about Problem

It seems that **.targets** and **.props** files of dependencies packages are not being added correctly to the **project.assets.json** file or to **Foo.csproj.nuget.g.props** and **Foo.csproj.nuget.g.targets** files. These files are added until you explicitly add the NuGet package to the project.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

This happens with Visual Studio 2019 16.3 on Windows, Visual Studio for Mac Version 8.3.3 (build 8), also with Mono's MSBuild when using /t:restore the nuget.g.props and nuget.g.targets files do not contain dependencies.

NuGet version: 5.3.0.6192

dotnet.exe --version (if appropriate): 3.0.100

VS version (if appropriate): Visual Studio 2019 16.3 on Windows, Visual Studio for Mac Version 8.3.3 (build 8)

OS version (i.e. win10 v1607 (14393.321)): macOS Mojave 10.14.6 (18G103)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

Test case: [AdMobTest.zip](https://github.com/NuGet/Home/files/3725941/AdMobTest.zip)

Steps to reproduce the error:

1. Open the test case.
2. Add the `Xamarin.Firebase.iOS.Analytics` package.
3. Build.

When it fails, open the **AdMobTest.csproj.nuget.g.targets** and it will be just 1 import when it should be 3 imports due to dependencies. 

### Verbose Logs

[log.txt](https://github.com/NuGet/Home/files/3726527/log.txt)

The workaround for this by now is to add NuGet dependencies explicitly to your project.

**Comment by SotoiGhost** [comment]
Any progress on this?

**Comment by Aleksey7151** [comment]
I'm facing with the same issue right now. Does anybody have any updates?

**Comment by SotoiGhost** [comment]
Any progress on this?

**Comment by SotoiGhost** [comment]
Adding `PrivateAssets="None"` to the `ProjectReference`/`PackageReference` fixes this. Also, adding the .props and .targets files to the [buildTransitive][1] folder helped.

[1]: https://github.com/NuGet/Home/wiki/Allow-package--authors-to-define-build-assets-transitive-behavior
