### ISSUE TITLE
nuget.exe spec Generates a copyright Tag with Hard-Coded Text of Copyright yyyy Instead of $copyright$

### ISSUE THREAD

**Issue by ChristopherTheunissen** [NuGet/Home#8696]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.3.0.6260

dotnet.exe --version (if appropriate):

VS version (if appropriate): 

OS version (i.e. win10 v1607 (14393.321)): Version	10.0.17134 Build 17134
Worked before? If so, with
 which NuGet version:

## Detailed repro steps so we can see the same problem
1. Create any C# project such as an MSTest project that uses .NET Framework 4.7.2
2. Open the folder in a command prompt.
3. Execute **nuget spec**
4. Notice the generated .nuspec (in attached ZIP and copied below) contains a hard-coded Copyright 2019 inside the copyright tag:
&lt;?xml&nbsp;version="1.0"?&gt;
&lt;package&nbsp;&gt;
&nbsp;&nbsp;&lt;metadata&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;id&gt;$id$&lt;/id&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;version&gt;$version$&lt;/version&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;title&gt;$title$&lt;/title&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;authors&gt;$author$&lt;/authors&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;owners&gt;$author$&lt;/owners&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;licenseUrl&gt;http://LICENSE_URL_HERE_OR_DELETE_THIS_LINE&lt;/licenseUrl&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;projectUrl&gt;http://PROJECT_URL_HERE_OR_DELETE_THIS_LINE&lt;/projectUrl&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;iconUrl&gt;http://ICON_URL_HERE_OR_DELETE_THIS_LINE&lt;/iconUrl&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;requireLicenseAcceptance&gt;false&lt;/requireLicenseAcceptance&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;description&gt;$description$&lt;/description&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;releaseNotes&gt;Summary&nbsp;of&nbsp;changes&nbsp;made&nbsp;in&nbsp;this&nbsp;release&nbsp;of&nbsp;the&nbsp;package.&lt;/releaseNotes&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;copyright&gt;**Copyright&nbsp;2019**&lt;/copyright&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;tags&gt;Tag1&nbsp;Tag2&lt;/tags&gt;
&nbsp;&nbsp;&lt;/metadata&gt;
&lt;/package&gt;

If Copyright 2019 is replaced with $copyright$, it correctly picks it up at pack time, so nuget.exe should generate this tag with the $copyright$ token.

[SomeProject.zip](https://github.com/NuGet/Home/files/3729529/SomeProject.zip)

**Comment by SuNNjek** [comment]
Hello, I would like to fix this issue if it is still up for grabs.
I'm assuming this applies to the Nuget.Client repo?
