### ISSUE TITLE
Equivalent of Nuget install -Prerelease

### ISSUE THREAD

**Issue by karann-msft** [NuGet/Home#8701]
@jawn commented on [Thu Oct 03 2019](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1721)

Is there a way to install the latest prerelease version of a package, without using the explicit version number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d00296b-ac62-3d6c-beea-b2042b63dc5b
* Version Independent ID: 587da972-dfde-88bc-9dc0-7c32dae3454b
* Content: [NuGet Command-Line Interface (CLI) Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-exe-cli-reference)
* Content Source: [docs/reference/nuget-exe-CLI-Reference.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-exe-CLI-Reference.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by nkolev92** [comment]
Hi @jawn. 

If you refer to the docs https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-install, there is a -PreRelease option you can pass to the install command.
