### ISSUE TITLE
Show version of nuget package ref in properties window

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8709]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/772962/show-version-of-nuget-package-ref-in-properties-wi.html)._

---
It would be handy to be able to see the version of Nuget package ref in the property window instead of having to pull up the manage nuget packages window

---
#### Visual Studio Feedback System on 10/11/2019, 00:43 AM: 

We have converted this feedback item from problem to idea. This change was done to better reflect the feedback's nature.
#### Jane Wu [MSFT] on 10/11/2019, 08:00 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by nkolev92** [comment]
cc @chgill-MSFT @anangaur

**Comment by chrisraygill** [comment]
Seems like this is an issue with older VS versions. Seems to work for .NET Core, Standard, and Framework on the latest VS.

![image](https://user-images.githubusercontent.com/15097183/81333633-bcaa7c00-9059-11ea-8a9b-3277f73f8331.png)

**Comment by chrisraygill** [comment]
Closing this issue because it's fixed in the latest version of VS.
