### ISSUE TITLE
Optimize compatibility checks during restore noop valiation

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#871]
The graphs needed for Supports are not stored in the lock file. Each time a build happens the lock file must be regenerated to perform the validation.

**Comment by yishaigalatzer** [comment]
Bringing this to review, I believe this can be moved out, as the improvement.

**Comment by emgarten** [comment]
NuGet/NuGet.Client@f48718971aec219393268901a4d863f9b855c757
