### ISSUE TITLE
NuGet package manager search box doesn't show previous items until something is typed in

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8710]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/748330/nuget-package-manager-search-box-doesnt-show-previ.html)._

---
NuGet package manager search box doesn't show previous items until something is typed in. For instance, if I previously searched for `EntityFramework`, then next time I want to add it, I press drop down button on combobox, but the list is empty. But if I type `E`, then `EntityFramework` *does* appear.

---
#### Visual Studio Feedback System on 9/26/2019, 02:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Hey @chgill-MSFT, @anangaur can you help us confirm what we want the behavior to be here. 

Thank you.

**Comment by chrisraygill** [comment]
@nkolev92 it sounds like the feedback is saying that they can't get this, right?:

![image](https://user-images.githubusercontent.com/15097183/81332939-a9e37780-9058-11ea-89cc-ce0bbb733c24.png)

Past search results without an initial query? Seems like it might be an issue with an old VS version.

**Comment by nkolev92** [comment]
Oh, that's fantastic if it works. 
We just wanted to be sure the dropdown is something worth pursuing.

Probably an issue with an old version.

Closing this issue.
