### ISSUE TITLE
Make nuget work if one of the sources is not accessable

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#8711]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/762595/make-nuget-work-if-one-of-the-sources-is-not-acces.html)._

---
We host our own private nuget services, that some devs use via a vpn.

Allot of the time they are not on the vpn. When they are not on the vpn it is not possible to intsall *any* nuget packages from *any* source. This seams really dumb. Its a PITA to have to constantly go into settings to keep enabling and re-enabling available package sources all the time.

We need nuget to just continue, and maybe just report a warning that a source is not available. But continue to use the sources that are available.

---
#### Jane Wu [MSFT] on 10/8/2019, 05:26 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/6373
