### ISSUE TITLE
When can we view the source code through F12 when editing, not just when debugging?

### ISSUE THREAD

**Issue by cjmld5** [NuGet/Home#8712]
When can we view the source code through F12 when editing, not just when debugging? Instead of viewing the method declaration or the source code only by downloading symbols when debugging.

Similar to itellij idea, you can download and view the source code automatically when editing

**Comment by nkolev92** [comment]
Hey @xyz0822 

We believe that issue is not specific to NuGet and is better suited for Visual Studio DeveloperCommunity. 

Can you please file the issue there?

Thank you.
