### ISSUE TITLE
NuGet Crashes when installing AutoMapper (VS 2015 RC)

### ISSUE THREAD

**Issue by scrapcode** [NuGet/Home#872]
When attempting to install AutoMapper through the interface in VS2015RC, it freezes then crashes VS2015RC without an error. This does not happen when using the v2 API.

There is a discussion of this here: https://groups.google.com/forum/#!topic/automapper-users/siEHOgWdsOw

**Comment by yishaigalatzer** [comment]
This was fixed for RTM. Thanks for bringing it up.
