### ISSUE TITLE
Cannot find version of nuget.exe pack that supports <icon>

### ISSUE THREAD

**Issue by zooba** [NuGet/Home#8724]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.3.0.6260

OS version (i.e. win10 v1607 (14393.321)): Win 10 19H1

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Follow the instructions on nuget.org to replace `iconUrl` element with `icon` element

2. `nuget.exe pack <my nuspec>`

3. Either of these outputs, depending on which schema is referenced in the nuspec:

With no schema specified: 

> The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'icon' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'copyright, owners, iconUrl, dependencies, summary, repository, serviceable, frameworkReferences, licenseUrl, language, tags, releaseNotes, packageTypes, references, requireLicenseAcceptance, frameworkAssemblies, developmentDependency, contentFiles' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. This validation error occurred in a 'icon' element.

Using `http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd`:

> The schema version of '<my file>' is incompatible with version 5.3.0.4 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.

(Needless to say, I _am_ running the latest version from that link.)

Any suggestions where I can find something that supports the recommended option?

**Comment by heng-liu** [comment]
Hi, can you try to use http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd instead? 
Pls let us know if you still encounter this issue. Thanks!

**Comment by HealthyJR** [comment]
Same problem here.
http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd
still raising the problem.

**Comment by heng-liu** [comment]
I can repro for `http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd`
But I packed succesfully for `http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd`
Can you pls provide detailed repro steps? Thanks.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
