### ISSUE TITLE
`nuget list` with package id returns every package

### ISSUE THREAD

**Issue by wangzq** [NuGet/Home#8725]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.2.0.6090

## Detailed repro steps so we can see the same problem

```
nuget list Microsoft.Build -source https://api.nuget.org/v3/index.json
```
This lists every package and takes quite a while to finish.

**Comment by heng-liu** [comment]
Hi, thanks for reporting this issue.
Can you try " nuget list packageid:Microsoft.Build -source https://api.nuget.org/v3/index.json" ?
You may refer to [this comment](https://github.com/NuGet/Home/issues/8622#issuecomment-537639085) for more details.

**Comment by heng-liu** [comment]
Closed as a duplicate of https://github.com/NuGet/Home/issues/8622
