### ISSUE TITLE
NuGet doesn't understand the log level in the restore task -- which in heavy auth scenarios leads to NuGet unnecessarily receiving log tasks from the plugin 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8727]
In 2 min restore this ends up ~575 out of 577 tasks on NuGet side.
This was for a restore with a normal verbosity.

@rainersigwald Is this even possible? 
I haven't found a way to get the current verbosity either through MSBuild evaluation or the TaskLoggingHelper API.

**Comment by rainersigwald** [comment]
The MSBuild logging model is "client code always logs; the logging infrastructure then discards or actually logs as appropriate", so the log level is intentionally hidden.

Internally we have a couple of "should we even generate these log messages?" environment variables but they're for specific messages and I wouldn't recommend using them.

**Comment by nkolev92** [comment]
:( 

I understand that, but it's unfortunate because creates unnecessary stress in the plugin/nuget communication. 
The client should be able to handle the load regardless though.
