### ISSUE TITLE
How to get the version list and latest version of NuGet package in VSCode

### ISSUE THREAD

**Issue by ganesanviji** [NuGet/Home#8731]
Hi

Currently I am working on the Visual Studio Code extension support. In my case I need to install my latest NuGet packages from online to the VSCode Blazor projects. Could you please suggest me how can I get the all published NuGet packages based on the NuGet name and latest NuGet version of the package using typescript since I need the logic for the Visual Studio Code. I can't use the C# Visual Studio logic in Visual Studio Code. 

Regards,
Ganesan R.

**Comment by heng-liu** [comment]
Hi, may I know if your need is to install lastest packages for your project? Do .NET CLI commands work for you?

**Comment by heng-liu** [comment]
Or, if you're looking for SearchQueryService from NuGet, you may have a look at this document: https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource

**Comment by ganesanviji** [comment]
Hi @heng-liu 

I am using the below C# code in my Visual Studio extension project to install the latest NuGet packages in my project at runtime. I have planned to provide the extension to create the project with our components in Visual Studio Code like Visual Studio. So, I have tried the below code in the Visual Studio code and I can't since I need the typescript code to achieve this. 

IPackageRepository repo = PackageRepositoryFactory.Default.CreateRepository("https://packages.nuget.org/api/v2");
var version =repo.FindPackagesById(packageID).Max(p=>p.Version);

Could you please suggest me how can I use the above code in my Visual Studio Code extension project.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
@ganesanviji 

There is no 1st party typescript equivalent for the C# libraries that are built in NuGet.Client. 

There might be some 3rd party alternatives, but personally I am not aware of them. 
You can consider implement your own alternatives if based on the resource linked by @heng-liu and the C# implementation in https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Protocol/Resources.

**Comment by ganesanviji** [comment]
Hi @nkolev92 

Could you please suggest me which is that the 3rd party alternatives and teh resource linked by @heng-liu  is using for get the version details for nuget.exe. But I don't need the nuget.exe version. I need the version list of my NuGet packages which is published in nuget.org server.

Thanks,
Ganesan R.

**Comment by nkolev92** [comment]
@ganesanviji 

I was referring to the following: https://github.com/NuGet/Home/issues/8731#issuecomment-545199643

> Could you please suggest me which is that the 3rd party alternatives

I'm not aware of any 3rd party alternatives.

**Comment by heng-liu** [comment]
Here're some 3rd party APIs you may have a look at. 
Do note that they are not official NuGet APIs. 
 https://github.com/loic-sharma/BaGet/blob/master/src/BaGet.UI/src/SearchResults.tsx#L29
 https://github.com/loic-sharma/BaGet/blob/master/src/BaGet.UI/src/SearchResults.tsx#L219

**Comment by heng-liu** [comment]
Closed as: Question
