### ISSUE TITLE
Use LazyIntializer API to initialize a target type in a multi threaded environment

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#8738]
## Details about Problem
In the current [implementation](https://github.com/NuGet/NuGet.Client/blob/c1f6915918b82c096bbd666bd9c18528f1f70630/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/IDE/ExtensibleSourceRepositoryProvider.cs#L54) object is always locked even-though target type is already initialized.  Learnt from this [doc](https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/threading/LazyInitializer.cs#L197) that there is a .NET framework implementation to accomplish the same logic. `This issue is created to track other lazy initializations which rely on a similar pattern`.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

**Comment by kartheekp-ms** [comment]
One instance of this issue is fixed in #8740 and PR /NuGet/NuGet.Client#3091

**Comment by nkolev92** [comment]
Unassigning myself. 

Given that this has the potential to cause deadlocks in certain cases, I don't think this is necessarily a slam dunk change in every situation.

**Comment by aortiz-msft** [comment]
@nkolev92  - What are the next steps for this one? Should we close?

**Comment by nkolev92** [comment]
I think we should close it. 
There were a few people involved in a discussion on the PR so I didn't want to unilaterally close it.

**Comment by kartheekp-ms** [comment]
I am okay to close this issue.
