### ISSUE TITLE
Make multiple versions of nuget.exe available for download

### ISSUE THREAD

**Issue by feiling** [NuGet/Home#874]
There is only one version of nuget.exe available for download at www.nuget.org/nuget.exe. We should make all versions of nuget.exe available. E.g. user can get nuget.exe 2.8.5 at www.nuget.org/nuget.exe/2.8.5

**Comment by emgarten** [comment]
Moving this to @deepakaravindr who is taking care of this.

**Comment by deepakaravindr** [comment]
The new model to download is http://dist.nuget.org/index.html. And, all exe versions greater than 2.8.6 are available for download
