### ISSUE TITLE
IncludeInPackage does not copy references from NuGet package depdendencies

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#8743]
Originally posted here: https://developercommunity.visualstudio.com/content/problem/785069/cannot-include-dependent-packages-when-building-a.html

## Details about Problem

>  I am using the excellent built-in tool for creating nuget packages.
>
>I would like to include a dependent package/assembly/dll to the final nuget package, and I expected to be able to do so by checking the 'Include in Package' under NuGet properties for a Reference to the dependent package.
>
>However, what I am seeing is that it doesn't appear to have any effect to check the 'Include in Package' checkbox for references to external packages.
>
>Is this an error, or am I perhaps doing it wrong?
>
>I made a temporary workaround by including the actual dll in the lib/net472/ folder by adding it to the project manually, but I would naturally avoid a hack like that. :-)

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
