### ISSUE TITLE
Update NuGet 3.1.0-beta assembly version numbers to 3.1.0 for release

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#875]
The NuGet assemblies in are currently labeled with 3.1.0-beta. In preparation for the UWP release they should be changed to 3.1.0.

**Comment by feiling** [comment]
Fixed. See change https://github.com/NuGet/NuGet3/commit/235063c7df4aa82b3ea2c75beec6e53a16e9efb4 and change https://github.com/NuGet/NuGet.VisualStudioExtension/commit/b829f196cbed5a4f1d29914e98fdd31b3ff1597b
