### ISSUE TITLE
nuget.exe password is shown in clear text when authenticating in terminal

### ISSUE THREAD

**Issue by B3RR10** [NuGet/Home#8750]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe
NuGet version (x.x.x.xxx): 5.3.0.6160

When pushing a package from the NuGet Gallery to the company's Artifactory NuGet repository through the terminal, I'm asked to authenticate.

The password field, which comes after entering the username, shows the password in clear text while I'm writing it. I believe that should not be the case and that the password text box should not show any written character, which is the normal behavior for CLI programs.

## Detailed repro steps so we can see the same problem

1. Download a NuGet package from the NuGet Gallery (nuget.org)
2. Use the nuget.exe to push the package to a different "NuGet Repo".\
    `nuget.exe push <FILE.NUPKG> -Source Artifactory-Nuget`
3. The remote server asks for authentication.

**Comment by dominoFire** [comment]
@B3RR10 Can you provide some details, i.e., the prompt messages from `nuget.exe` and from the server ?

**Comment by B3RR10** [comment]
Sure thing.

```
$ nuget push comon.logging.1.2.0.nupkg -Source Artifactory
MSBuild auto-detection: using msbuild version '16.3.2.50909' from 'C:\Program Files (x86)\...'.
Bitte stellen Sie Anmeldeinformationen zur Verfügung für: https://artifactory.companyname.de/artifactory/api/nuget/v3/nuget-repository
UserName: USERNAME
Kennwort: PASSWORD IN CLEAR TEXT
Pushing common.logging.12.0.nupkg to 'https://artifactory.companyname.de/artifactory/api/nuget/v3/nuget-repository'...
    PUT https://artifactory.companyname.de/artifactory/api/nuget/v3/nuget-repository/
    Created https://artifactory.companyname.de/artifactory/api/nuget/v3/nuget-repository/ 116ms
Your package was pushed.
```

**Comment by nkolev92** [comment]
I was unable to reproduce this on my local machine with a different server. 
```
C:\Users\Nikolche\Documents\Code\NuGet\NuGet.Client [dev ≡]> C:\Users\Nikolche\Downloads\nuget.exe push .\artifacts\nupkgs\NuGet.Build.Tasks.5.5.0-zlocal.63745.nupkg -source https://devdiv.pkgs.visualstudio.com/_packaging/VSExtensibility/nuget/v3/index.json
Please provide credentials for: https://devdiv.pkgs.visualstudio.com/_packaging/VSExtensibility/nuget/v3/index.json
UserName: fadsad
Password: *******
```

Is this something you can reproduce on every machine?

**Comment by B3RR10** [comment]
@nkolev92 Your absolutely right! This issue was fixed on a new version of Artifactory Server. I'll close this thread now. Thank you for your time!
