### ISSUE TITLE
Display vulnerability info for PackageReference type projects on Installed tab of PMUI

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/Home#8755]
Display vulnerability information in the package graph on `Installed tab of Package Manager Dialog (PMUI).

Spec: https://github.com/NuGet/Home/wiki/Flag-vulnerable-packages

**Comment by nkolev92** [comment]
This is now completed. 

![image](https://user-images.githubusercontent.com/2878341/206078093-6d7090e5-a79b-4a00-b0a0-295cb986ad46.png)
