### ISSUE TITLE
PackageReference bug with Deployment Projects (MSI packager)

### ISSUE THREAD

**Issue by StephaneGraziano** [NuGet/Home#8768]
0.Config :  VS 2017 V15.9.17 - MS Visual Studio Installer Projects 0.9.3

1. Be sure you use **ProjectReference** with Nuget instead of packages.json (Tools->Options)
2. Create a WPF project .net 4.6.1 and add **System.Runtime.CompilerServices.Unsafe** 4.6.0 via nuget
3. Create Setup project (Visual Studio Installer)
4. Add the WPF Output
5. Compile the setup project and install it
6. Open the System.Runtime.CompilerServices.Unsafe with ILSpy or Reflector
7. It's the **reference lib**, not the lib (and if you used it in the WPF project, it will throw a BadFormatException)

So it's a bug => Please update the installer

**Comment by rrelyea** [comment]
we don't have access to: System.Runtime.CompilerServices.Unsafe (it is not published on nuget.org)
Can you change the repro steps that work with a public package?

**Comment by rrelyea** [comment]
If this works in a netfx 4.7.2 project, then you are probably hitting: https://twitter.com/terrajobst/status/1031999730320986112

When you look at the bin directory after a 4.6.1 build and 4.7.2 -- the 4.6.1 has a mess of files to try to be netstandard2.0 compat. Clearly there are problems in that world. Sorry.

**Comment by StephaneGraziano** [comment]
Same bug with 4.7.2 or 4.7 this is again the reference file, not the real binary
![image](https://user-images.githubusercontent.com/48211010/68106806-11224280-fee3-11e9-99f9-3f68fd54d236.png)
