### ISSUE TITLE
Link from Nuget.Server on nuget.org to project is broken

### ISSUE THREAD

**Issue by kkm000** [NuGet/Home#877]
The Project Site link from <https://www.nuget.org/packages/NuGet.Server/> leads to <http://nuget.codeplex.com/>, which now has a message directing to this project, <https://github.com/nuget/home>. I think the link at nuget.org should be rather changed to go directly to a project which builds the NuGet.Server package. And for the life of me I cannot find NuGet.Server sources on github... 

Please untangle the links.

**Comment by yishaigalatzer** [comment]
Moved to the right repo
