### ISSUE TITLE
[Suggestion][Test Failure] Suggest making the deprecated icon beside the Installed tab able to be navigated by Tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8770]
## Details about Problem
NuGet version: NuGet Client Dev\5.5.0.6284
VS Version: Master\29429.48
OS: Windows-10-Enterprise-19H1-04-05-2019
## Detailed repro steps 
1. Create a C# Console App (.NET Core) via VS.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json in the Settings dialog.
4. Select the above deprecated package source in Browse tab and install deprecated packages.
5. Tab to Installed tab.
## Expected
Suggest making the deprecated icon beside the Installed tab able to be navigated by Tab, so the user could know how many deprecated packages installed totally through keyboard.
## Actual
The deprecated icon beside the Installed tab can’t be navigated by Tab as below screenshot.
![DeprecatedIconCannotBeTab](https://user-images.githubusercontent.com/20632625/67843531-1d02b300-fb37-11e9-96de-28a241347621.png)

**Comment by aortiz-msft** [comment]
The Accessibility team did not flag this as an accessibility problem.
