### ISSUE TITLE
Embedded Icon won't show in Visual Studio (16.3)

### ISSUE THREAD

**Issue by krafs** [NuGet/Home#8772]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.3.1.6268

VS version: 16.3.6

OS version: win10 v1903 (18362.449)

Worked before?: Don't know. First time making NuGet-package.

## Detailed repro steps so we can see the same problem

1. Run `nuget spec`

2. Add `<icon>icon.png</icon>` to the metadata tag in the nuspec.

3. Add icon.png to the working folder. (icon taken from [PackageIconNuspecExample](https://github.com/NuGet/Samples/tree/master/PackageIconNuspecExample))

4. Run `nuget pack`

5. Add generated package to local repository

6. Open **Visual Studio** => **NuGet Package Manager**

7. Change **Package Source** to local repository.

8. Package has the default, fallback icon - Not the packed icon.

### Sample Project
[SampleNuget.zip](https://github.com/NuGet/Home/files/3789085/SampleNuget.zip)

**Comment by rrelyea** [comment]
We are doing this work. Done now, but need some improvements. So likely shipping in VS 16.5. #8189 is tracking that work.

Until then, packages can choose to use the new technique, and leave the old url in the project and/or nuspec -- that will stop the warning, and still work in versions of VS that don't know how to show it yet.

/cc @dominoFire @agr @karann-msft
