### ISSUE TITLE
Support Nuget without .csproj or .sln (as a module managemenet)

### ISSUE THREAD

**Issue by jogibear9988** [NuGet/Home#8775]
I'd like to use nuget as a Manager for Extension DLL's for my C# Software.
(Like iobroker uses npm for it's modules)

But this is not possible at the moment, cause I can't use nuget only for downloading and installing to a local path

**Comment by zivkan** [comment]
I'm aware of 3 projects/products that use NuGet as their own module distribution system: powershell, chocolatey, xenko.

Can you explain what's not working for you?

**Comment by rrelyea** [comment]
`dotnet tools install` creates a temporary csproj with appropriate properties, and downloads a bunch of packages. @wli3 could point you to the source code which seems to be in transit somewhere now.

**Comment by wli3** [comment]
Here is the code of creating a temp project https://github.com/dotnet/toolset/blob/b3a65fd82a879beb7ff8565a781ad257337f1de1/src/dotnet/ToolPackage/ToolPackageInstaller.cs#L158

**Comment by jogibear9988** [comment]
that means I always need to create a temp project?

**Comment by nkolev92** [comment]
@jogibear9988 

Are you using our libraries or are you using the tooling itself?

**Comment by kartheekp-ms** [comment]
@jogibear9988 - Please address [above comment](https://github.com/NuGet/Home/issues/8775#issuecomment-626943346) and explain the scenarios that are not working for you.
