### ISSUE TITLE
Interop Assembly in NuGet for Standard and Framework with EmbedInteropTypes = false

### ISSUE THREAD

**Issue by Roemer** [NuGet/Home#8776]
Hi all

I am trying to create a NuGet package with just an interop assembly inside.
This package will be used in .NET Standard, Core and Framework projects.
The package should make sure that `EmbedInteropTypes` is in all cases set to `false`.
I'm having a hard time achieving this. I tried to do it like the sample `https://github.com/NuGet/Samples/tree/master/NuGet.Samples.Interop` and just adjusting the `true` to `false` but I do not see anything added regarding `EmbedInteropTypes` in the csproj file. Neither on .NET Core nor on .NET Framework.

I don't really understand when the target file is needed and when it will work. Will it also work for .NET Framework? Or do I need an `install.ps` there which disables the `EmbedInteropTypes` for those types of projects and the `.target` only for .NET Standard/Core?

The project where I am trying to achieve this is: https://github.com/Roemer/UIAutomation-Interop
Any help would be greatly appreciated.

Thanks
Roman

**Comment by rrelyea** [comment]
Packages.Config will automatically embed interop types.  This is handled at install time, and modifies the .csproj appropriate. 
To override this behavior, I'd imagine an install.ps1 file might be a way to override that default.

For PackageReference, we implemented some support in [NuGet 5.0](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.0-rtm) added Enable EmbedInteropTypes for PackageReference (matching Packages.Config capability) - [#2365](https://github.com/NuGet/Home/issues/2365)

Unfortunately, this isn't yet respected in PackageReference scenarios.
- https://github.com/dotnet/sdk/issues/2732 (for sdk style projects)
and
- https://github.com/NuGet/Home/issues/8062 (for normal csproj projects using PackageReference)

So you likely get the behavior you want in PackageReference scenarios for Lib dlls.

**Comment by nkolev92** [comment]
Thank you for creating this issue. 
Closing as we believe that we have answered this question. 
Feel free to open new issues for any additional feedback.
