### ISSUE TITLE
retryingFindpackagesbyIdAsynccore issue in visual studio 2019

### ISSUE THREAD

**Issue by wpanduka** [NuGet/Home#8781]
I am working fine with one windows 10 machinewith grial UI kit for xamarin by using visual studio 2019, but one windows 10 machine making poblems with the retryingFindpackagesbyIdAsynccore and trying to download nuget packages but it fails to restore packages, wich leads to so many build errors, it also says in the out put that issue with "Severity	Code	Description	Project	File	Line	Suppression State	Suppression State Error	NETSDK1004	C:\Program Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	"tried cleaning the solution and rebuilding the solution it keeps giving errors .
Thank you in-advance for your support

**Comment by rrelyea** [comment]
@wpanduka - Likely an msbuild issue?

dotnet build cannot support path with folder name has '%20' [#2178](https://github.com/microsoft/msbuild/issues/2178)

If that isn't it...please look at other mentions of NETSDK1004:
[Search for NETSDK1004](https://www.bing.com/search?q=NETSDK1004&PC=U531&cvid=41601e7aec5b422ea2bff891741acec0&FORM=ANNTA9)

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
