### ISSUE TITLE
NuGet.Configuration dependency (System.Security.Cryptography.ProtectedData) is not copied to output directory

### ISSUE THREAD

**Issue by hugener** [NuGet/Home#8789]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.Configuration

NuGet version (x.x.x.xxx): 5.3.1

dotnet.exe --version: 3.0.100

VS version: 16.3.1

OS version: Win 10 1903

Worked before? If so, with which NuGet version: Not that I know

## Detailed repro steps so we can see the same problem

1. Create a new .netstandard2.0 lib

2. Reference NuGet.Configuration

3. Add the following MsBuild properties to the csproj:
`<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`
`<IsTool>True</IsTool>`
`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`

System.Security.Cryptography.ProtectedData is not included in output directory, even if it is listed as a dependency. 
As a result I get a FileNotFoundException when trying to load ApiKeys from NuGet.config.

**Comment by nkolev92** [comment]
The System.Security.Cryptography.ProtectedData package brings in a reference assembly and a couple of runtime assemblies. 
The runtime assemblies are gonna be deployed if you have an app. 

For example if you retarget to netcoreapp you will see a runtimes folder in the bin output. 

Can you verify that?

**Comment by hugener** [comment]
Yes, if I create a netcoreapp3.0 and reference NuGet.Configuration, i get a runtimes folder in the output.
Since, I am making a .netstandard2.0 lib there will never be an "app", or better said, my lib gets loaded at runtime by the actual app (MSBuild).
I also tried adding the following:
```
    <PackageReference Include="NuGet.Configuration" Version="5.3.0">
      <IncludeAssets>runtime; compile</IncludeAssets>
    </PackageReference>
```
But that did not have any effect and according to [package-references-in-project-files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files), "all" is default anyways. Should there be a way to force runtimes to be included for libs?

As a workaround I added a netcoreapp3.0 to my solution, made it build before my lib and finally had the build copy over the runtimes folder. That solved the problem, but also required me to add some extra build scripts for copying and deleting the unwanted .exe file.

**Comment by nkolev92** [comment]
> Should there be a way to force runtimes to be included for libs? 

That's a question better answered at https://github.com/dotnet/sdk/issues/new. 
I have some context, but the folks there will have the right answer. 

@nguerrera @dsplaisted any thoughts on this?

**Comment by dsplaisted** [comment]
It sounds like you're trying to make a dotnet tool that targets .NET Standard.  That's not supported, you need to target .NET Core.

@wli3 Maybe we should generate an error here if we don't already.

**Comment by wli3** [comment]
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets#L77

yes. If you use `dotnet pack /p:packastool=true`

**Comment by hugener** [comment]
@dsplaisted why ist that not supported? I mean it works. I was hoping target netstandard would also allow it to work with "classic" msbuild, but
@wli3 with `<PaskAsTool>true</PackAsTool>` I get an error saying I need to target NetCore.

Yes I'm building a build/tools package (developmentDependency), so all dependencies go into the package and I'm providing my own NuSpec. To do that I use `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` and I wonder if specifying that, is what should trigger the runtimes to also be copied to the output (even for netstandard, etc).
I'll try to get my source code on GitHub later today.

**Comment by dsplaisted** [comment]
There isn't always an implementation of a library for .NET Standard.  A library might have reference assemblies for .NET Standard but separate implementations for .NET Core and .NET Framework.  So you can't use CopyLocalLockFileAssemblies to get a "runnable" tool targeting .NET Standard, because there are no runnable versions of some libraries for .NET Standard.

**Comment by nkolev92** [comment]
> I mean it works. I was hoping target netstandard would also allow it to work with "classic" msbuild. 

If this is a build dependency only (meaning you have targets), then you can multi target netcore/netfx and use MSBuildRuntimeType to switch the task file imported based on that. 

https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019

**Comment by hugener** [comment]
@dsplaisted That makes sense, but in case the package does provide .netstandard compatible runtimes, shouldn't they be outputted?
For example, NuGet.Configuration provides netstandard1.3 libs for System.Security.Cryptography.ProtectedData.
Wouldn't those be safe to include when the consuming project targets netstandard2.0?
Of course, if I invoke that functionality they might throw PlatformNotSupportedExceptions on unsupported platforms, but I think that's better than FileLoadExceptions, since supported platforms will work.

Here are some links for my package and source code: Sundew.Build.Publish
[NuGet package](https://www.nuget.org/packages/Sundew.Build.Publish/)
[GitHub repo](https://github.com/hugener/Sundew.Build.Publish)

**Comment by nkolev92** [comment]
@hugener 

From a NuGet perspective, unfortunately I don't think there's much we can do. 

If this is still a concern you are trying to address, I think you should consider opening an issue on the SDK repo. 

Closing this issue as not actionable from NuGet side.
