### ISSUE TITLE
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.)

### ISSUE THREAD

**Issue by lnicolae** [NuGet/Home#8790]
Nuget 5.3.1

## Details about Problem

NuGet product used (NuGet.exe from console)

NuGet version 5.3.1:

OS version (i.e. win10 v1607 (14393.321)):

Worked before? Don't know

## Detailed repro steps so we can see the same problem

1. From console with admin rights:

C:\Users\xxx\Source\Repos\ConsoleApp11\ConsoleApp2\bin\Release>"c:\users\xxx\appdata\local\microsoft\visualstudio\16.0_f557710cexp\extensions\xxx\vsixtesttehnolog\1.0\NuGet\nuget.exe" push "C:\Users\xxx\Source\Repos\ConsoleApp11\ConsoleApp2\bin\Release\ConsoleApp2.1.0.1.nupkg" -Source https://api.nuget.org/
Pushing ConsoleApp2.1.0.1.nupkg to 'https://www.nuget.org/api/v2/package'...
PUT https://www.nuget.org/api/v2/package/
Forbidden https://www.nuget.org/api/v2/package/ 980ms
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
Key is Valid was generate 2 minutes before the push command from console with admin right. Alto I set the key with nuget.exe setApiKey and the same error
..

### Verbose Logs

Pushing ConsoleApp2.1.0.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 980ms
Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

### Sample Project
In code:
Project that try to push the package is a  VSIX propect type that use a async function to push packages

----------------
            await Task.Run(() =>
            {
                Process cmd = new Process();
                cmd.StartInfo.FileName = commandToExecute;
                cmd.StartInfo.Arguments = arguments;
                cmd.StartInfo.Verb = verb;
                cmd.StartInfo.RedirectStandardInput = true;
                cmd.StartInfo.RedirectStandardOutput = true;
                cmd.StartInfo.CreateNoWindow = true;
                cmd.StartInfo.UseShellExecute = false;
                cmd.OutputDataReceived += Cmd_OutputDataReceived;
                cmd.Start();
                cmd.BeginOutputReadLine();
                cmd.StandardInput.Flush();
                cmd.StandardInput.Close();
                cmd.WaitForExit();
            }).ConfigureAwait(false);
-----------------

**Comment by zkat** [comment]
[ConsoleApp2 already exists](https://www.nuget.org/packages/ConsoleApp2/1.0.0-CI-20180702-154742), which is probably why you're getting a 403 for it.

**Comment by lnicolae** [comment]
No the package is a new packaage and don't exist on server on my account, (The package name must be uniq per server ?)

**Comment by zkat** [comment]
Yes, the package name must be unique.

**Comment by zkat** [comment]
Yes, packages have to be unique per server. What's the package name you're trying to publish?

**Comment by lnicolae** [comment]
Thanks, I read documentation for PUSH from MSDN, I create a tool for NuGet (VSIX for VS2019)

**Comment by zkat** [comment]
What's the package name you're trying to publish?

**Comment by lnicolae** [comment]
Not have a specific name. The packages will have developer project name (I think)
