### ISSUE TITLE
The Visual Studio NuGet packages (RestoreManagerPackage) needs to auto load on solution build events

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8796]
See https://dev.azure.com/devdiv/DevDiv/_workitems/edit/792876. 

From a thread: 

We had a discussion on this and decided the proper way to do this is to whitelist the SolutionBuilding UI context for sync autoload. 

After the UI context is whitelisted, nuget will have to add the following into the package definition:
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionBuilding_string)]

Note that there should be no PackageAutoLoadFlags.BackgroundLoad flag in this registration. Otherwise your package will be async autoloaded, causing the same issue. Note that you may also want to keep the existing autoload on solution exists, as that’s async autoload and helps the Build performance sometimes.

**Comment by nkolev92** [comment]
Duplicate issue in [VSTS](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792876)

**Comment by nkolev92** [comment]
Assigning to Rob as the internal issue is assigned to him.

**Comment by rrelyea** [comment]
First attempt at a fix doesn't seem to succeed. Working with VS Extensibility Team to see if we didn't make the change correctly...or if they need another fix.

**Comment by rrelyea** [comment]
Figured out problem was due to non-default config of my test machine. Once fixed, then my change addressed the problem. Rebasing to get a test fix and revalidating on CI...should be in soon.

**Comment by rrelyea** [comment]
Merged into NuGet.Client's dev branch. Will likely be inserted into VS Master branch in next week or two, making it in time for 16.5 p2.
