### ISSUE TITLE
Package restoration fails due to Windows path limits in v3-cache directory

### ISSUE THREAD

**Issue by MikeRosoft** [NuGet/Home#8799]
I have encountered an error during the restoration of a NuGet package with a moderately long name (78 characters). The package download from our corporate Nexus server fails with 'path not found' error. After investigation, I have discovered that NuGet is trying to access a file in the cache directory, whose total path length (directory+file) exceeds the Windows limit of 260 characters.

The following appears in the console output of nuget.exe during nuget restore:

> WARNING: Unable to find version '1.4.0' of package 'Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'.
>   C:\Users\jenkinsRunner\.nuget\packages\: Package 'Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings.1.4.0' is not found on source 'C:\Users\jenkinsRunner\.nuget\packages\'.
>   https://nexusl1-emea.gemalto.com/repository/ICS-NuGet-DC/: Failed to fetch results from V2 feed at 'https://nexusl1-emea.gemalto.com/repository/ICS-NuGet-DC/FindPackagesById()?id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0' with following message : Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\2d6042322504e8cb5efaae64087a12b2ab1e0fcf$lto.com_repository_ICS-NuGet-DC_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.
>   Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\2d6042322504e8cb5efaae64087a12b2ab1e0fcf$lto.com_repository_ICS-NuGet-DC_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.
>   https://nexusl1-emea.gemalto.com/repository/ICS-NuGet-RnD/: Failed to fetch results from V2 feed at 'https://nexusl1-emea.gemalto.com/repository/ICS-NuGet-RnD/FindPackagesById()?id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0' with following message : Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\5dcd21fd99a760f045b929f3ca9ba8bea0d834b5$to.com_repository_ICS-NuGet-RnD_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.
>   Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\5dcd21fd99a760f045b929f3ca9ba8bea0d834b5$to.com_repository_ICS-NuGet-RnD_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.
>   https://nexusl1-emea.gemalto.com/repository/ics_nuget_cogent/: Failed to fetch results from V2 feed at 'https://nexusl1-emea.gemalto.com/repository/ics_nuget_cogent/FindPackagesById()?id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0' with following message : Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\04fc2590fe6239eadf8a5b526e1b0c4cf452859e$com_repository_ics_nuget_cogent_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.
>   Could not find a part of the path 'C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\04fc2590fe6239eadf8a5b526e1b0c4cf452859e$com_repository_ics_nuget_cogent_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new'.

Observe that the length of path "C:\Users\jenkinsRunner\AppData\Local\NuGet\v3-cache\2d6042322504e8cb5efaae64087a12b2ab1e0fcf$lto.com_repository_ICS-NuGet-DC_\list_FindPackagesById()_id='Gemalto.ICS.RnD.ApplicationFramework.DataStructures.WebServiceEndpointSettings'&semVerLevel=2.0.0_page1.dat-new" is 261 characters.

Workaround: move the v3-cache directory to a different location using NUGET_HTTP_CACHE_PATH environment variable.

NuGet version: 5.3.1.6268
Operating system: Windows 7

Way to reproduce:
* Create a solution referencing a NuGet package with a long package name. (Note: the problem also depends on the length of the Windows user name, and probably also on the length of the NuGet repository URL.
* Call `nuget.exe restore` on the solution.

**Comment by nkolev92** [comment]
There is a duplicate issue of this problem. https://github.com/NuGet/Home/issues/3324

Read https://github.com/NuGet/Home/issues/3324#issuecomment-389329153 for a more detailed explanation. 

Unfortunately at this point Windows 10 is the only OS where long path support can enabled. 

We recommend you use the workaround described in this issue and follow #3324 for any further updates.
