### ISSUE TITLE
MS-NuGet flattens and ignores empty dependency groups

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#88]
This is a copy of an email from Eric Rozell:

When I publish a package to ms-nuget with the dependencies as below, and take a dependency on the package for target net45, I still get the dependencies for net40.

    <dependencies>
      <group targetFramework="net40">
        <dependency id="System.Compatibility" version="1.0-alpha3" />
      </group>
      <group targetFramework="net45">
      </group>
    </dependencies>

The weird part about this is it only seems to occur when I take the nuget dependency from the ms-nuget service.  If I populate my local package cache using the .nupkg files (the same ones that I submitted to ms-nuget), and then re-install the package in a project, I only get the net45 dependencies. 

Likewise, if I take the dependency using the Package Manager Console from a local folder containing the nupkg files (with a clean package cache), I also do not get the net40 dependencies.

Lastly, if I clear the local package cache, request the dependency from ms-nuget via the Pacakge Manager Console, the first time I will get the net40 dependencies.  The second time I request the package, I only get the net45 dependencies.  So this only seems to be an issue when resolve the package the first time on a machine.

-- snip from another email on this thread --

When I publish this same package to ms-nuget, and use NuGet.Core to pull a reference to the package, I see that the number of dependency groups is only one.  In other words, the dependency groups have been flattened somehow by the ms-nuget service.  

This is problematic, as, from my issue below, it can cause dependency conflicts.  I suspect that ms-nuget is built using an older version of NuGet.Core that does not properly support dependency groups.

**Comment by yishaigalatzer** [comment]
We are not supporting MsNuGet.
