### ISSUE TITLE
Circular dependency error on PCL projects

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#880]
Reported by @davkean

Steps
1.  File -> New -> Portable project 
2. Choose .NET Framework 4.6 and Windows 10
3. Click OK

Error:
---------------------------
Microsoft Visual Studio
---------------------------
Circular dependency references not supported. Package 'Microsoft.VisualBasic'.
---------------------------
OK   
---------------------------                   

Build 687 repros the issue
Reverting to build 686 fixes the issue

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/NuGet/NuGet3/commit/08e323da237238bcb980ec1acd7f6d05a8d2199c
