### ISSUE TITLE
Make it obvious when a warning is elevated to an error

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8803]
Customers frequently get confused why restore fails when the message reported doesn't sound like an error, for example NU1603.

I think we should have something in the message that makes it obvious that NuGet considers it a warning, but it was elevated to an error by request.

**Comment by lukos** [comment]
@zivkan Can you explain what this means. I think we are suffering from this on package restore and the error doesn't make sense because it is just a warning that version X was requested but only version X + 1 was found.

**Comment by zivkan** [comment]
Here's an example:  I create a new project, `dotnet new classlib`. I then added a PackageReference, but did not provide a version (`<PackageReference Include="NuGet.Protocol" />`). Restore gives me this warning:

> C:\src\test\warnAsErrorTest\warnAsErrorTest.csproj : warning NU1604: Project dependency NuGet.Protocol does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

I then edit my csproj to add the property `<WarningsAsErrors>$(WarningsAsErrors);NU1604</WarningsAsErrors>`. Now when I restore I get this message:

> C:\src\test\warnAsErrorTest\warnAsErrorTest.csproj : error NU1604: Project dependency NuGet.Protocol does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

My proposal is to change the message to something like this:

> C:\src\test\warnAsErrorTest\warnAsErrorTest.csproj : error NU1604: (WarningAsError) Project dependency NuGet.Protocol does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

@lukos If the message you see says "Warning NUxxxx", then NuGet is not causing the process to return an error code. If you see "Error NUxxxx", then your project is either explicitly setting that NU code to be elevated to an error, or your project has opt into "treat all warnings as errors".
