### ISSUE TITLE
Logic in _GetRestoreProjectStyle should be in a task

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#8804]
## Details about Problem

The `_GetRestoreProjectStyle` target in `NuGet.targets` has its logic declared as MSBuild XML rather than a task.  This makes it more difficult to unit test and reuse the logic.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Any

NuGet version (x.x.x.xxx): Any

dotnet.exe --version (if appropriate): Any

VS version (if appropriate): Any

OS version (i.e. win10 v1607 (14393.321)): Any

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment]
reopening as PR that closed this issue is being reverted.
