### ISSUE TITLE
error : Unable to load the service index for source https://api.nuget.org/v3/index.json.

### ISSUE THREAD

**Issue by scalablecory** [NuGet/Home#8805]
_From @Meai1 on Saturday, October 26, 2019 9:54:55 AM_

```
pc@debian:~/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder$ dotnet build ./FlightFinder.sln
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]
/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   The SSL connection could not be established, see inner exception. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]
/home/pc/workarea/software/dotnet/sdk/3.0.100/NuGet.targets(123,5): error :   The remote certificate is invalid according to the validation procedure. [/home/pc/test/blazor-samples/samples/aspnetcore/blazor/FlightFinder/FlightFinder.sln]

Build FAILED.

```

Btw this happens for every project, I just used the sample project for illustration. And for some reason it works if I do the build via Jetbrains Rider IDE.
Before you point me to links like this: https://stackoverflow.com/questions/41185443/nuget-connection-attempt-failed-unable-to-load-the-service-index-for-source ...
Please notice that I consider this a bug whether there is a manual workaround or not because I can access that given url in the browser perfectly fine. If it works from the browser, it has to work from inside dotnet executables too. This should not be up to me to solve.

_Copied from original issue: dotnet/core#3701_

**Comment by scalablecory** [comment]
_From @scalablecory on Monday, October 28, 2019 6:38:24 PM_

This should be filed on the [Nuget repo](https://github.com/NuGet/NuGet.Client)

It sounds like this is a feature request (automatic proxy discovery on Linux) rather than a bug, yes?

CC @rrelyea

**Comment by scalablecory** [comment]
_From @Meai1 on Monday, October 28, 2019 7:36:08 PM_

@scalablecory absolutely not, it's 100% a bug. I am connected to the internet just fine, there is no reason whatsoever that nuget should be incapable of downloading things.

**Comment by scalablecory** [comment]
_From @scalablecory on Thursday, November 7, 2019 1:46:41 AM_

Are you using a proxy as the StackOverflow question suggests, or is this something else?

**Comment by scalablecory** [comment]
_From @rrelyea on Thursday, November 7, 2019 6:05:15 PM_

https://docs.microsoft.com/en-us/nuget/nuget-org/nuget-org-faq#nugetorg-not-accessible

**Comment by nkolev92** [comment]
@Meai1 Are you using a proxy?

**Comment by nkolev92** [comment]
Closing this as no repro as there has been no response from the customer.

**Comment by jonathanmccormick** [comment]
I'm having the same issue with the dotnet core CLI on Mac. No proxy.

```
dotnet add package Microsoft.EntityFrameworkCore.InMemory
Microsoft (R) Build Engine version 15.1.548.43366
Copyright (C) Microsoft Corporation. All rights reserved.

  Writing /var/.../...O.tmp
info : Adding PackageReference for package 'Microsoft.EntityFrameworkCore.InMemory' into project '/Users/.../test/test.csproj'.
log  : Restoring packages for /Users/.../test/test.csproj...
error: Unable to load the service index for source https://api.nuget.org/v3/index.json.
error:   The type initializer for 'System.Net.Http.CurlHandler' threw an exception.
error:   The type initializer for 'Http' threw an exception.
error:   The type initializer for 'HttpInitializer' threw an exception.
error:   The type initializer for 'CryptoInitializer' threw an exception.
error:   Unable to load DLL 'System.Security.Cryptography.Native.OpenSsl': The specified module could not be found.
error:    (Exception from HRESULT: 0x8007007E)
```

**Comment by jonathanmccormick** [comment]
Scratch this, updating .NET Core fixed it. 🙃

**Comment by alastairs** [comment]
For completeness (and a reproduction scenario), I experienced this error while building an ASP.NET Core application using multi-stage builds, using Docker's Linux Containers on Windows (LCOW) feature. I guess there's some proxying going on with LinuxKit or Docker itself in this scenario, but I don't know for sure. This is my Dockerfile:

```DockerfileFROM mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /src
COPY ["src/MyApp/MyApp.csproj", "MyApp/"]
RUN dotnet restore "MyApp/MyApp.csproj"
COPY . .
WORKDIR "/src/MyApp"
RUN dotnet build "MyApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyApp.csproj" -c Release -o /app/publish -r linux-musl-x64 --self-contained true --no-restore


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT "./MyApp"
```

You can then run the following Docker command to invoke this file and reproduce the error:

```bash
$ docker build -f "C:\path\to\myapp\src\MyApp\Dockerfile" --force-rm -t myapp:production --target build "C:\path\to\myapp"
```

All of the defined targets (except `base`) exhibit this behaviour.
