### ISSUE TITLE
Add "latest" option for -MSBuildVersion 

### ISSUE THREAD

**Issue by goyzhang** [NuGet/Home#8808]
Currently we can only specify the version in order to use this argument like:
> nuget restore a.sln -MSBuildVersion 16.3

**Why?**
It should be the latest by default. However, in some cases the PATH value overwrites this behaviour. e.g. if we have MSbuild14 in the PATH. There is currently no way to specify using the latest version of MSBuild. Is it possible to add this feature to `-MSBuildVersion` ?

**Comment by nkolev92** [comment]
As you articulated, latest is search by default unless there's a path variable with MSBuild on it. 
MSBuild is installed SxS with VS 2017 and later, so msbuild.exe is not added to the path at install time.

I understand you request, but I'd venture a guess that it's not something commonly hit. 
Marking this as up for grabs.

**Comment by goyzhang** [comment]
OK, thanks. In my environment the admin adds vs2013 buildtools to the PATH. Normal user have no control of that thus nuget always pick up the old 12.0 buildtools.

**Comment by nkolev92** [comment]
If you're interested, we'd be happy to take a PR. 

RElevant code; https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/MsBuildUtility.cs
