### ISSUE TITLE
Circular dependency with shared C++ projects

### ISSUE THREAD

**Issue by damyanp** [NuGet/Home#881]
Repros in build 687.

1.	Create a C# UWP
2.	Create a C++ UWP runtime component
3.	Create a shared C++ project
4.	Make the UWP runtime component reference the shared C++ project

When building the package restore fails with:

    “Error occurred while restoring NuGet packages: Circular dependency references not supported. Package 'Project1'.”

**Comment by emgarten** [comment]
Looks like the same error as: https://github.com/NuGet/Home/issues/880

**Comment by damyanp** [comment]
#880 is reported fixed in build 687.  I still see this in 687.

**Comment by yishaigalatzer** [comment]
Can you verify this is resolved with the fixes @davidfowl is doing for his issues?

**Comment by pranavkm** [comment]
Fixed as part of https://github.com/NuGet/NuGet3/commit/08e323da237238bcb980ec1acd7f6d05a8d2199c
