### ISSUE TITLE
cannot access project.lock.json file after completong restoring when create K Project

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#882]
install Dev14 23023.00 + D14OOB SDK 23102.00 (after install, NuGet version is 696)

repro steps:
1. create K project
2. wait to restore complete

after restore complete, got one error as below:
![kprojecterror](https://cloud.githubusercontent.com/assets/11768961/8497829/f520e5a8-21b2-11e5-922b-27c88299081a.PNG)

**Comment by Eilon** [comment]
@davidfowl ?

**Comment by yishaigalatzer** [comment]
External - Mayuri is following up
