### ISSUE TITLE
Definition of package executable entrypoint

### ISSUE THREAD

**Issue by ibigbug** [NuGet/Home#8821]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet.exe

NuGet version (x.x.x.xxx): nuget.exe v5.3.1

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): 19023.1

Worked before? If so, with which NuGet version: Feature request

## Detailed repro steps so we can see the same problem

Add support for distributing a binary executable like other package managers: NPM/Pip or whatever

It's very handy to publish command line tools written in NodeJS or Python. For CSharp, I had to use Scoop which was well-known in the community but still somehow a "third party" paltform.

Would you consider adding an official support of adding a new metadata in package definition so that nuget publish/install can be used to distribute command line tools shipped within a nuget package?

**Comment by nkolev92** [comment]
For distributing .NET Core based tools, the answer is https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools. 

Are you specifically asking for .NET based executables or something more general?

**Comment by ibigbug** [comment]
thanks @nkolev92 for pointing out, this seems to be what i wanted, let me have a look.

**Comment by ibigbug** [comment]
Thanks @nkolev92 . I've successfully publish my tool https://www.nuget.org/packages/PowerSession/'

I'm good to close this now.

**Comment by nkolev92** [comment]
Glad .NET Core tools satisfy your scenario :)
