### ISSUE TITLE
Files in ref folder are copied to project output folder

### ISSUE THREAD

**Issue by krafs** [NuGet/Home#8822]
## Details about Problem
When I build a project that references a NuGet package, that I've made myself, containing only files in the `ref` folder, the files are nonetheless copied to the project `output` folder. This is a problem when I'm making a NuGet package with only reference assemblies, as I only want them at compile time. If I wanted the files in the `output` folder I would've added them to the `lib` folder instead.
I'm using PackageReferences.

NuGet product used:
NuGet.exe

NuGet version:
5.3.1.6268

dotnet.exe --version:
3.0.100

VS version:
16.3.8

OS version:
win10 v1903 (18362.476)

## Detailed repro steps:
1. Run `nuget spec`
2. Add folder `ref/net35` to root folder
3. Add any file (x) to `ref/net35`
4. Run `nuget pack`
5. Add package as `PackageReference` in new .net35 project
6. Build project
7. Observe file x in `output` folder

NB! Project does not have to be .NET35, but that's what I used when encountering this issue.

**Comment by nkolev92** [comment]
I attempted this repro with net472 projects with both SDK style and old style csproj PackageReferece and was not able to repro it. 
[8822.zip](https://github.com/NuGet/Home/files/3849249/8822.zip)
See attached. 
Package creates a package when you run dotnet pack. 
The running dotnet build and msbuild /restore /t:build respectively to Project and Project-NETFX, in both cases the Package.dll did not get copied. 

Can you upload the assets file of the project that ends up copying the assembly? 

Through the assets file, NuGet tells the SDK which assemblies to use for compile and which to use for runtime.

**Comment by krafs** [comment]
Turns out the asset files that were copied over came from a different package, with an identical structure and content, except the files were put in the lib folder. My mistake. Your packages do indeed pack and run as intended, as do mine now that I know my error. This can be closed. Thank you!

**Comment by nkolev92** [comment]
Glad you managed to resolve your issue :)
