### ISSUE TITLE
Nuget.exe returns false positive during nuget restore when a feed is inaccessible.

### ISSUE THREAD

**Issue by abhinavdevone** [NuGet/Home#8828]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx):3.6.0

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)): Win10, Server 2016.

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Include multiple feeds and packages in corext.config.
 
2. Edit host file to point ONE nuget feed to a dummy ip address.

3. kick off nuget restore.

Result -- 
Nuget.exe continues to "hang" for a long period for the corrupt feed and eventually moves to the next feed's restore WITHOUT throwing an error. This results in an overall false positive.
...

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)
Nuget.Exe Restore

I can provide logs later. I would like to check if this issue has been addressed already since I realize that we have a much older version of nuget.exe running.

**Comment by nkolev92** [comment]
@abhinavdevone 

Is the project that you are restoring packages.config based? 
Did NuGet not restore all the packages successfully or? 
Would be able to post the logs?

**Comment by nkolev92** [comment]
Closing this issue as we do not have enough information to continue investigating.
