### ISSUE TITLE
[NuGet.VisualStudioExtension] Windows Desktop Manager going crazy when searching for packages

### ISSUE THREAD

**Issue by GeertvanHorrik** [NuGet/Home#883]
Whenever NuGet is searching for packages (the infinite progress bar animations shows), my Desktop Window Manager goes crazy in Windows 10:

![image](https://cloud.githubusercontent.com/assets/1246444/8498016/70858680-2182-11e5-8861-b45dfef236b9.png)

**Comment by GeertvanHorrik** [comment]
I'd rather have no animation than a single instance taking so much CPU. When updating packages, I normally do 3-4 solutions at the same time (because it takes a loooooooooooong time to update). Then this CPU usage is excessive.

**Comment by yishaigalatzer** [comment]
We can take a look, though I doubt that the cost comes from the animation. We do try to parallelize the calls to nuget to make the UI show-up a lot faster.

Since we are pretty much locked for RTM, we can take a look for 3.2. I'd appreciate taking a look if this still shows up after RTM is released on the 20th.

**Comment by GeertvanHorrik** [comment]
Added reminder, will let you know.

**Comment by GeertvanHorrik** [comment]
Just tested this, a single instance of VS still takes up to 80 % of CPU when checking for NuGet updates (and it takes a long time). In this case I am checking MyGet in a solution of 26 projects (mostly shared to support NET40 / NET45), and it has quite some dependencies, but it's frustratingly slow.

If you need more info, let me know.

**Comment by yishaigalatzer** [comment]
@GeertvanHorrik we made a bunch of improvements in this area, but I don't want to close this issue without your feedback. Please grab Update I/Nuget 3.3 when it goes out and let us know if it improved enough to make you happy?

We plan to do more perf improvements in 3.4.

You do want to use V3 feeds from myget to get better performance

**Comment by GeertvanHorrik** [comment]
Already on v3 feed, but definitely looking forward to the performance improvements of nuget. Will try to get a beta somewhere.

**Comment by GeertvanHorrik** [comment]
Already works much better, thanks!
