### ISSUE TITLE
Third argument sent to install.ps1 is NuGet.PackageManagement.VisualStudio.ScriptPackage in 3.0.0

### ISSUE THREAD

**Issue by Tornfeldt** [NuGet/Home#884]
ScriptPackage contains very little information (Id and Version) whereas OptimizedZipPackage used in NuGet 2.8 contains information about the installed NuGet package.
Because of the change many install.ps1 scripts will break -- for example when setting installed references to CopyOnly by using AssemblyReferences from OptimizedZipPackage.

**Comment by yishaigalatzer** [comment]
That's a true statement. The 2.8 'IPackage' was super extensive and not supportable going forward.

If you have specific items you depend on today, please let us know and we will add them back in.

**Comment by yishaigalatzer** [comment]
Please evaluate install.ps1 scripts in live nuget to see what popular packages are using in their scripts. 

Come up with a table of missing features and review with the team.

Implemented missing features.

**Comment by Tornfeldt** [comment]
At my company we use the property `AssemblyReferences` for our private NuGet feed, so it would be nice if you can include this.

We do not use the method `GetFiles` but I certainly see the use case for that method if for example you want to manipulate the Visual Studio project file in some way with regards to the installed files from the NuGet package.

I have looked at the top-50 most downloaded NuGet packages and the only properties used from the `$package` argument in `install.ps1` is `Id` and `Version` which is already included in ScriptPackage.

**Comment by zhili1208** [comment]
fixed in https://github.com/NuGet/NuGet.Client/commit/90167c9b9b4e8d7c442c7d67c19efa6a8e745745
