### ISSUE TITLE
nuget pack process loses file attributes

### ISSUE THREAD

**Issue by yacoub-hossain-adsk** [NuGet/Home#8846]
## Details about Problem

NuGet.exe

NuGet version (3.4.4.1321):

OS version win10 v1607 (14393.321):

Worked before? Not sure maybe it was always like this:

## Detailed repro steps so we can see the same problem

1. Create a file with read-only attributes

2. Pack it into a nuget package using nuget pack (and a valid nuspec file)

3. Extract the file out of the nupkg 

4. Check the file attributes and see that the read-only attribute is gone

Why does the packing process lose the read-only file attribute?

**Comment by zivkan** [comment]
Could you please explain the scenario for why you want files with the read-only attribute? What's the end-to-end experience? I haven't tested, but even if the file was read-only in the packages directory, when MSBuild copies files to the project output or publish directories, does it maintain the read-only attribute? is that desirable?

Issues/risks that concern me initially is that read-only attributes are not cross platform, but .NET and NuGet are. I tested quickly a read-only file zipped on Windows and unzipped on Linux, but it did not maintain read-only permissions. Similarly zipping a read-only file on Linux and unzipping on Windows did not use the read-only attribute. Therefore, this feature request is asking for functionality that other zip applications do not do. Also, it makes deleting files from the packages directory more difficult. We'd need to test if `dotnet nuget locals global-packages --clear` handles read-only files (my bet is that it doesn't) and we'd have to consider that anyone who uses a custom script to delete files may also find their script broken if NuGet started creating read-only files.

The title of the issue only says "file attributes", so considering other attributes, not only the read-only attribute, it becomes even more operating system specific. Windows has a hidden attribute, but on POSIX machines it's done by convention. The complexity in making NuGet support hidden files/directories for both Windows and Linux without forcing all packages to use the POSIX "start with a dot" convention would be great. I'm not aware of any Linux equivalent of the Windows "ready to archive" attribute.

So, I don't support NuGet supporting all file attributes. Even for read-only, I'd like to know more about what advantages this feature would provide, to justify the technical complexity the NuGet team would have to take on to test and maintain this feature.

**Comment by nkolev92** [comment]
I'd like to close this issue per the above comment. 
Per @zivkan's elaborate comment and my own investigation, there's no unique cross platform way for NuGet to preserve these attributes.
