### ISSUE TITLE
"An item with the same key has already been added" when restoring in Visual Studio

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#8847]
Using latest internal preview, or built from latest dev branch only. Latest public preview not affected.

**Comment by nkolev92** [comment]
Can you fix the name? :D 

This one is way to similar to https://github.com/NuGet/Home/issues/6795

**Comment by jmroyb** [comment]
Still ocurring in VS2019 Version 16.5.4

Where can I watch which item is failing?

![image](https://user-images.githubusercontent.com/4932314/80816964-cb63df80-8bd0-11ea-922b-fb766d9d5169.png)
