### ISSUE TITLE
DownloadTimeoutStream should not block by calling .Result

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8853]
Discovered while working on https://github.com/NuGet/Home/issues/8528. 
```
Name
Event Microsoft-DotNETCore-SampleProfiler/Thread/Sample
+ Type: External
|+ System.Private.CoreLib!ManualResetEventSlim.Wait
||+ System.Private.CoreLib!Task.SpinThenBlockingWait
|| + System.Private.CoreLib!Task.InternalWaitCore
||  + System.Private.CoreLib!System.Threading.Tasks.Task`1[System.Int32].GetResultCore(bool)
||   + System.Private.CoreLib!System.Threading.Tasks.Task`1[System.Int32].get_Result()
||    + nuget.protocol!DownloadTimeoutStream.Read
||     + nuget.protocol!ProtocolDiagnosticsStream.Read
||      + System.Private.CoreLib!System.IO.Stream+<>c.<BeginReadInternal>b__43_0(class System.Object)
||       + System.Private.CoreLib!System.Threading.Tasks.Task`1[System.Int32].InnerInvoke()
||        + System.Private.CoreLib!System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(class System.Object)
||         + System.Private.CoreLib!ExecutionContext.RunFromThreadPoolDispatchLoop
||          + System.Private.CoreLib!Task.ExecuteWithThreadLocal
||           + System.Private.CoreLib!Task.ExecuteEntryUnsafe
||            + System.Private.CoreLib!Task.ExecuteFromThreadPool
||             + System.Private.CoreLib!ThreadPoolWorkQueue.Dispatch
||              + System.Private.CoreLib!_ThreadPoolWaitCallback.PerformWaitCallback
||               + Thread (592) (.NET ThreadPool)
```

```
Name
Event Microsoft-DotNETCore-SampleProfiler/Thread/Sample
+ Type: External
|+ ?!0x7f4fe536bbfa
||+ System.Private.CoreLib!FileStream.ReadNative
|| + System.Private.CoreLib!FileStream.ReadSpan
||  + System.Private.CoreLib!FileStream.Read
||   + System.Private.CoreLib!System.IO.Stream+<>c.<BeginReadInternal>b__43_0(class System.Object)
||    + System.Private.CoreLib!System.Threading.Tasks.Task`1[System.Int32].InnerInvoke()
||     + System.Private.CoreLib!System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(class System.Object)
||      + System.Private.CoreLib!ExecutionContext.RunFromThreadPoolDispatchLoop
||       + System.Private.CoreLib!Task.ExecuteWithThreadLocal
||        + System.Private.CoreLib!Task.ExecuteEntryUnsafe
||         + System.Private.CoreLib!Task.ExecuteFromThreadPool
||          + System.Private.CoreLib!ThreadPoolWorkQueue.Dispatch
||           + System.Private.CoreLib!_ThreadPoolWaitCallback.PerformWaitCallback
||            + Thread (603) (.NET IO ThreadPool Worker)
```

DownloadTimeoutStream is a custom implementation for a stream timeout. The reasoning behind that is that the timeout property is not observed for asynchronous operations. 

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.networkstream.readtimeout?view=netframework-4.8#remarks

This class is only used in one place in the HttpRetry handler. 
https://github.com/NuGet/NuGet.Client/blob/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpRetryHandler.cs#L141

We only really call the async APIs. 

The sync api is implemented by calling .Result on the async call. This blocks the current thread. 
https://github.com/NuGet/NuGet.Client/blob/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584/src/NuGet.Core/NuGet.Protocol/Utility/DownloadTimeoutStream.cs#L43
Originally the intention was that this would never be called.
And it's not, not explicitly in the NuGet code at least. 

It is however called indirectly by the framework implementation. 

.NET Core: 
Specifically: https://github.com/NuGet/NuGet.Client/blob/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584/src/NuGet.Core/NuGet.Protocol/HttpSource/HttpCacheUtility.cs#L78

CopyToAsync  [=>](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/Stream.cs#L112) CopyToAsyncInternal [=>](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/Stream.cs#L122)
ReadAsync [=>](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/Stream.cs#L356-L358)
BeginEndReadAsync [=>](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/Stream.cs#L390) 
Stream.BeginReadInternal [=>](https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/Stream.cs#L291) synchronous read https://github.com/NuGet/NuGet.Client/blob/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584/src/NuGet.Core/NuGet.Protocol/Utility/DownloadTimeoutStream.cs#L43

Note that this codepath is only taken because we do not override [BeginRead](https://github.com/NuGet/NuGet.Client/blob/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584/src/NuGet.Core/NuGet.Protocol/Utility/DownloadTimeoutStream.cs#L52) on .NET Core. 

In .NET Framework

CopyToAsync => CopyToAsyncInternal => ReadAsync => BeginEndReadAsync => BeginRead => BeginReadInternal => Stream.Read. 

fyi @joelverhagen Thanks for providing context on the original change :)

**Comment by joelverhagen** [comment]
Hoping you're clocking in for these weekend hours 😉. Nice find!
