### ISSUE TITLE
RestoreSettingsUtils needs overload to use new SettingsLoadingContext

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#8855]
## Details about Problem

The new `SettingsLoadingContext` needs to be added as an overload to `RestoreSettingsUtils` so that it can be used when reading the settings initially.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Just adding milestones and a bunch of labels :)
