### ISSUE TITLE
How do I install NuGet.Tools.vsix that I compiled?

### ISSUE THREAD

**Issue by mingkuang-Chuyu** [NuGet/Home#8857]
## Details about Problem

NuGet product used VS UI

NuGet version (5.5.0.54553)

VS version 16.3.10:

OS version  Win7 SP1 x64 :

## Detailed repro steps so we can see the same problem
Hello, due to the poor support for props in the official version, such as unable to import Shared ImportGroup or ExtensionSettings ImportGroup in C++ Project.

So I modified the source code and compiled it to get NuGet.Tools.vsix, but I couldn't install it. What should I do to install my NuGet.Tools.vsix? I'm eager to get help to make C++ better. 

Thank you

mingkuang

**Comment by mingkuang-Chuyu** [comment]
I have tried using Microsoft.Build.Construction API in install.ps1 and uninstall.ps1, but this has some cache refresh problem.

**Comment by kartheekp-ms** [comment]
Please send us the installation log when you try to install modified version of `NuGet.Tools.vsix`. we believe it could be because of signing.
Since you have already modified source code for better user experience, feel free to submit a PR with your changes so that we can review it and plan next steps.

**Comment by mingkuang-Chuyu** [comment]
[dd_VSIXInstaller_20191127102107_2020.log](https://github.com/NuGet/Home/files/3894827/dd_VSIXInstaller_20191127102107_2020.log)


```
2019/11/27 10:21:14 - 安装错误: System.InvalidOperationException: NuGet++ Package Manager for Visual Studio 2019 安装失败。要安装此扩展，请至少安装以下组件之一: NuGet 包管理器, Developer Analytics Tools, 托管桌面工作负载核心, ASP.NET 和 Web 开发工具先决条件, Azure 开发必备组件, 通用 Windows 平台工具, Visual Studio 扩展开发必备组件, Office/SharePoint 开发, Python Web 支持, Xamarin, Visual Studio 的 Office 开发人员工具, 用于 Xamarin 的通用 Windows 平台工具
   在 Microsoft.VisualStudio.ExtensionManager.PackageInstaller.LoadComponent(IDependencyGraph dGraph, Boolean& isProductComponent)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   在 Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

```

I did not install nuget in vsinstaller, but now it prompts me that the prerequisite is it.

I want to test it locally first, and then submit a PR.

: )

Thanks

**Comment by zivkan** [comment]
If you have the NuGet solution open in Visual Studio, set the startup project to NuGet.VisualStudio.Client, then the debugging settings will automatically change to the Visual Studio Experimental Instance. Then either "start with debugger" or "start without debugger" will automatically deploy to the VS experimental instance and run it.

**Comment by mingkuang-Chuyu** [comment]
> If you have the NuGet solution open in Visual Studio, set the startup project to NuGet.VisualStudio.Client, then the debugging settings will automatically change to the Visual Studio Experimental Instance. Then either "start with debugger" or "start without debugger" will automatically deploy to the VS experimental instance and run it.

Bug I need to install it on another computers.  ：(

**Comment by kartheekp-ms** [comment]
Please go ahead and test your changes as suggested in [above](https://github.com/NuGet/Home/issues/8857#issuecomment-559252813) comment to ensure plugin works as expected for your scenarios.

We will work internally to discuss possibilities of distributing plugin to other computers. If the options are limited we will let you know so that you can create a PR with your new changes.
FYI - we do a lot of end to end tests to ensure new code don’t break existing behavior.

**Comment by mingkuang-Chuyu** [comment]
> Please go ahead and test your changes as suggested in [above](https://github.com/NuGet/Home/issues/8857#issuecomment-559252813) comment to ensure plugin works as expected for your scenarios.
> 
> We will work internally to discuss possibilities of distributing plugin to other computers. If the options are limited we will let you know so that you can create a PR with your new changes.
> FYI - we do a lot of end to end tests to ensure new code don’t break existing behavior.


Thanks. it works now.

**Comment by kartheekp-ms** [comment]
Great. Thanks for the update.
