### ISSUE TITLE
Odd dependency installation behavior

### ISSUE THREAD

**Issue by czangarine** [NuGet/Home#8858]
## Details about Problem
NuGet product used: nuget binary (Mac), Rider 2019.2 IDE (Mac), VS 2019 IDE (Win)
NuGet version (x.x.x.xxx): 4.7.0.5148
dotnet.exe --version (if appropriate): 3.0.100
VS version (if appropriate): 2019
OS version (i.e. win10 v1607 (14393.321)): MacOS Mojave 10.14.6
Worked before? If so, with which NuGet version:  N/A

## Detailed repro steps so we can see the same problem
We create and host NuGet packages in-house, with deep dependency trees.  I'm hoping you've seen this problem before and can provide some guidance.  I don't expect it to be a VS/Rider/etc bug, so much as we're doing something slightly wrong.

**Scenario**:
- Create “Package A” using the PackageReference style compilation of “contentFiles/any/any”.
     - Create a sub-folder under “contentFiles/any/any” called “Source”.
     - Place source code files in the “Source” folder.
     - Have a dependency on “Package B”.
- Create “Package B”, again using the PackageReference style, with a “Source” subfolder.
     - Place source code files in its “Source” folder.
- Pack and publish both.

**Expectation**:
- Install “Package A” (using the built-in NuGet package manager UI).
     - Your project gains a “Source” folder.
          - A’s source files are referenced into the new “Source” folder and compile with the project.
     - “Package B” is also installed, since it’s a dependency.
          - B’s source files are also referenced into the “Source” folder and compile with the project.
- Package A is immediately consumable by the project because all of its code, and all of its dependency’s code, is present.

**Actual**:
- Install “Package A”.
     - Your project gains a “Source” folder.
          - A’s source files are referenced into the new “Source” folder and compile with the project.
     - “Package B” is also installed, since it’s a dependency.
          - B’s source files **are not referenced** into the “Source” folder.
     - **Package A code cannot be compiled because the source for B is not in the project**.
- Manually install “Package B”, same as you did for “A”.
     - B’s source files are referenced into the new “Source” folder in the project.
     - Now “Package A” can be compiled and consumed.

If sample nuspec files are needed, etc. please let me know.

Thanks

**Comment by donnie-msft** [comment]
I believe NuGet doesn't handle the copying of files directly, but MSBuild plays a role. @nkolev92  can you provide more info?

You may want to give the `flatten` property a try. From the [nuspec ContentFiles docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-contentfiles-element-for-content-files):

```
<files include="cs/uap/config/config.xml" 
  buildAction="None" copyToOutput="true" flatten="true" />
```

**Comment by czangarine** [comment]
@donnie-msft - Thank you for the reply.  I don't think we want `copyToOutput` on the source files, since they're compile-time resources, not runtime.

**Comment by nkolev92** [comment]
The content files are by default excluded from flowing to parent projects. 
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

Do you own packageA? 
If you do, then you can consider change the default includes so that contentfiles are included :)

Note if you have a project to project transitive reference you might be hitting: https://github.com/NuGet/Home/issues/6826

**Comment by czangarine** [comment]
@nkolev92 - Thank you for the reply.

Is there something I can put in packageB's nuspec to have it not flag contentFiles as private?  If so, that might solve the problem immediately.

I do own packageA.  Are you suggesting that packageA should declare contentFiles for all of its dependency tree (e.g. packageB)?  That unfortunately isn't something we can do given other use cases.

6826 does read like my situation (maybe), but I don't know how we'd have gone a year without this functioning ... which makes me think it's not the same 🤷‍♂

**Comment by nkolev92** [comment]
> Is there something I can put in packageB's nuspec to have it not flag contentFiles as private? If so, that might solve the problem immediately.


> I do own packageA. Are you suggesting that packageA should declare contentFiles for all of its dependency tree (e.g. packageB)? That unfortunately isn't something we can do given other use cases.

When PackageA declares a dependency to PackageB it declares which assets from B should flow to A's installing project. 

Specifically: 
```
        <dependency id="nuget.common" version="5.4.0" include="Runtime,Compile,Native,ContentFiles,BuildTransitive" />
```

would include everything but build/analyzers.

**Comment by czangarine** [comment]
Awesome.  Thanks @nkolev92.  No clue how I missed this.  Will give it a try and see.

**Comment by nkolev92** [comment]
Which docs were you using as a reference?
Maybe we can add the information there to make things easier. 

Would you please loop back once you have tried out the suggestion?

**Comment by czangarine** [comment]
Lots of googling, but primarily https://docs.microsoft.com/en-us/nuget/reference/nuspec#dependencies-element.  Under `include`, it says `The default value is all.`.

I see now under `exclude`, it says `But content/ ContentFiles are also implicitly excluded in the final package which can't be over-written.` which seems to contradict what you're saying.

I should have test results in a few minutes.

**Comment by nkolev92** [comment]
This was changed here: 

https://github.com/NuGet/docs.microsoft.com-nuget/pull/1029/files#diff-a0f52482bd5f78d428773d6bf021313f

I have opened an issue to revisit that: https://github.com/NuGet/docs.microsoft.com-nuget/issues/1806.

**Comment by czangarine** [comment]
Confirmed, setting include on the dependency in packageA does cause packageB to get embedded into the project.  Thanks @nkolev92 @donnie-msft !

**Comment by nkolev92** [comment]
Glad to see that :) 
We've keep https://github.com/NuGet/docs.microsoft.com-nuget/issues/1806 open for a follow up.
