### ISSUE TITLE
I Can't delete a new create package

### ISSUE THREAD

**Issue by LuGuangguang** [NuGet/Home#8859]
I learn to how to create a package.When I had public a package,I want to delete this. But I can't by the URL "https://docs.microsoft.com/zh-cn/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework".This is no the delete button.
 
this doc
![PHZE(IIAT (%RF51${(RNDR](https://user-images.githubusercontent.com/34500722/69702479-47da2a00-112a-11ea-916c-46b7e5464878.jpg)

this my project
![L9%FP{ AT56MX)A80PD@3EV](https://user-images.githubusercontent.com/34500722/69702619-98ea1e00-112a-11ea-910e-246141aae206.png)

Thank you!

**Comment by donnie-msft** [comment]
This is the wrong repo for requesting package deletion. I've moved your Issue to [NuGet/NuGetGallery #7748](https://github.com/NuGet/NuGetGallery/issues/7748)
