### ISSUE TITLE
Push fails when specifying a fully-qualified path to the nupkg on POSIX.

### ISSUE THREAD

**Issue by dmccaffery** [NuGet/Home#886]
When executing NuGet push command using a fully-qualified path to the nupkg on POSIX (such as Linux or Mac), NuGet is incorrectly assuming that the specified path is relative to the current directory.

For instance:

If pwd = /Volumes/Storage/Users/test/repos/nuget

````bash
dnx nuget.exe push "/Volumes/Storage/users/test/repos/nuget/packages/test.pkg" -Source "/Volumes/Storage/Users/test/.config/NuGet/packages"
````
fails with error message:

````bash
Directory '/Volumes/Storage/Users/test/repos/nuget/Volumes/Storage/Users/test/repos/nuget/packages' not found.
````

**Comment by eatdrinksleepcode** [comment]
Confirmed on OSX while testing [Bau.NuGet](https://github.com/bau-build/bau-nuget).

**Comment by spadapet** [comment]
Uses of Uri.TryCreate are throwing exceptions. Still need to track them down.

**Comment by spadapet** [comment]
We have many uses of the Uri class in the code. They throw with UNIX paths due to a bug in corefx: https://github.com/dotnet/corefx/issues/1745
Seems like the Uri class is unlikely to be fixed soon since that's an old bug and changing Uri could have compatibility issues.
