### ISSUE TITLE
nuget restore sln really slow

### ISSUE THREAD

**Issue by tdesaules** [NuGet/Home#8864]
Hi guys,

I have an issue with the nuget 5.x version.

When i make a nuget restore from a sln file (packages are downloaded the first time and the second time they are copy from the cache)

Thats strange but when the copy come from cache it is really slow. I have that on several server (Windows Server 2016). With my user account it look fine ~ 1mn to restore 70 package. It take ~10mpn with other account.

Any idea ?

**Comment by donnie-msft** [comment]
I'm not clear on your scenario, or which accounts you're talking about.

However, to speculate on possibilities: what are your enabled Package Sources at the two different times you're restoring? If there's a slower source (either HTTP or local file feed) then the Restore could take longer to find/download the same package(s).

Try `nuget sources list` on the CLI as a quick way to see your Package Sources and their status.

**Comment by tdesaules** [comment]
Well,

In fact the packages are already on the local cache on the server (the server is a jenkins slave).

They have been downloaded the first time I run the nuget restore. The latency come from the local copy ( from the cache to my folder configure in the project app ).

Some packages are quicly copy, other take several secondes for a total arround 9mn at the end.

The strange things is that I have this issue with all users (I try with the laocal system account, a local admin account and a user admin account from Active Directory) except my AD admin account, with it it take less than a minute.

I rollback to nuget 4.1.0 and the issue is not present, the perf are not so good that in 5.X but I get the same time with all users ~2mn

I also check my source list, I only get the default one : https://api.nuget.org/v3/index.json
Not sure there is a relation because I can download the package without issue the first time

thank you

**Comment by donnie-msft** [comment]
@nkolev92  any insight, here?

**Comment by nkolev92** [comment]
@tdesaules 

Are your projects packages.config based or PackageReference?

**Comment by tdesaules** [comment]
Hi,

I forget this case... my bad.

We are using packages.config based for our asp dotnet 4.X and packageReference for the dotnet core apps.

**Comment by nkolev92** [comment]
I see, so you have both flavors. 

Would you be able to provide us detailed logs from the "slow run" or a repro. 
Unfortunately I don't have any ideas how to explain the discrepancy between the different users. 

Another question, what does the "cache" you talk about refer to?
> Thats strange but when the copy come from cache it is really slow.

**Comment by tdesaules** [comment]
When I say cache I mean, the first time the nuget restore is done it will download the package from internet to my local jenkins slave then copy to my working directory (jenkins) this take time bug not so mutch regarding the download latencies. Then when I build my app the second time it will only copy the nuget package from my "local temp nuget folder" to my jenkins workspace. This take a lot of time just to copy few MB on the local machine.

I'm in training this week, I will do some more test with the last nuget version next week.
I'm not sure where to find and enable some debug log for the nuget app ?

**Comment by nkolev92** [comment]
> I'm not sure where to find and enable some debug log for the nuget app ?

nuget.exe <command> -verbosity Detailed should do it. 

> internet to my local jenkins slave then copy to my working directory (jenkins) this take time bug not so mutch regarding the download latencies. T

I'm just trying to the understand the action here. 
Are you referring to NuGet built in capabilities or something jenkins does? 

See https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process for how NuGet pacakage installation works. 

In PackageReference NuGet installs packages in the global packages folder which is where build will use them from. 
In packages.config, the global packages folder installation happens + a copy to a local packages folder.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.

**Comment by mvonck** [comment]
I have the same issue, nuget restore goes from 20 seconds to 10 minutes but i can't figure get verbose details. I have this with .NET Framework 4.6.1 projects when using a newer NuGet.Exe (5.7). For now my solution is to include an older NuGet.Exe(3.4.4) in the git repository and use this one for legacy projects
