### ISSUE TITLE
VisualStudio ToolBox is not populated from a NuGet package if a project is placed in a solution folder

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#8868]
## Details about Problem

**NuGet product used:** VS UI

**NuGet version:** 5.4.0.6292

**VS version:** 16.4

**OS version:** 10.0.18362.0

**Worked before?:** No

Visual Studio doesn’t add toolbox items from a NuGet package if a project is placed into a solution folder. A VS customer created a small sample (WPF, .NET Core3) to demonstrate the issue: https://github.com/pavelovcharov/netcore3_toolbox_solutionfolders.

This is a bug in VsPathContextProvider.CreateNuGetProjectAsync. DTE.Solution.Projects doesn't include projects within solution folders. See https://www.wwwlicious.com/envdte-getting-all-projects-html/ for an explanation.

## Repro steps

1. git clone git://github.com/pavelovcharov/netcore3_toolbox_solutionfolders.git
2. open and build TestControl.sln. The TestControl.1.0.0.nupkg package will be created
3. open and build TestApp.sln, then open MainWindow.xaml. The TestControl item will be added to VisualStudio Toolbox
4. open and build TestApp.With.Solution.Folders.sln. This solution contains the same project, but it is placed into a solution folder. Open MainWindow.xaml. The TestControl item is not shown in the Toolbox.

**Comment by debonte** [comment]
@pavelovcharov

**Comment by rrelyea** [comment]
@aortiz-msft - @debonte is on the XAML tools team, and this issue was originally filed as internal bug 1011441 as a P1 bug.

**Comment by donnie-msft** [comment]
Discussed PR offline with @debonte.
NuGet/Toolbox integration tests passed.
