### ISSUE TITLE
NuGet.Gallery repo is missing...

### ISSUE THREAD

**Issue by dmccaffery** [NuGet/Home#887]
The ReadMe @ NuGet/Home suggests that a "new NuGet Gallery" is in the works under NuGet/NuGet.Gallery, but the repo is missing. I assume that it hasn't been made public yet, so the ReadMe should remove the reference until such time as it is.

I'm looking forward to getting up to speed on the new gallery implementation as we use NuGet internally for enterprise-level packages, and having a gallery is great for discovery.

**Comment by yishaigalatzer** [comment]
Thanks, you are right.
