### ISSUE TITLE
How to show the Toolbox control after install the NuGet package in Xamarin platform

### ISSUE THREAD

**Issue by ganesanviji** [NuGet/Home#8870]
Hi 

I am trying to add the Toolbox controls along with default Microsoft Visual Studio toolbox window for Xamarin, after install the Custom NuGet packages instead of install the custom Tool Box Extension since the toolbox has been enable for the Xaml pages. 

I have tried add the tools folder with the VisualStudioToolSDKmanifest.xml file along with my sample NuGet package. But don't have luck. The controls are showing in the default Visual Studio Xamarin Toolbox. But I can't drag and Drop the control in the XAML file since the controls are disabled in the toolbox window.

The above method has been worked on the WPF and UWP Xaml pages. But not working in the Xamarin project xaml pages. 

Is there any problem in xamarin XAML file to show the toolbox control through the NuGet packages?
Could you please any one suggestion to achieve this?

Thanks,
Ganesan R.

**Comment by ganesanviji** [comment]
Could you please anyone suggest the solution on this?

**Comment by donnie-msft** [comment]
I'm not familiar with Xamarin Toolbox, and it may be more appropriate to open this issue on their repo. What do you mean by showing the control "through the NuGet package"? What file are you trying to import into this toolbar: a .nupkg or a .dll or a .xaml?

**Comment by donnie-msft** [comment]
A similar issue was recently reported. I'm not sure if it's related, but you may want to take a look:
[VisualStudio ToolBox is not populated from a NuGet package if a project is placed in a solution folder](https://github.com/NuGet/Home/issues/8868).

**Comment by donnie-msft** [comment]
@ganesanviji is this still a problem for you? Could you take a look at https://github.com/NuGet/Home/issues/8868 and see if it sounds like the same problem? I have a PR for that issue in-review.

**Comment by nkolev92** [comment]
Closing per @donnie-msft's comment.

Let us know if you are still having issues.

Thanks.
