### ISSUE TITLE
Missing replacement for allowedVersions attribute in PackageReference

### ISSUE THREAD

**Issue by sieukrem** [NuGet/Home#8876]
The referenced article describes the usage of _PackageReference_ in project file and _package_ in packages.config as if the first a replacement for the second is. 

Both of them provide the possibility to define a dependency for the restore operation at development time and also for the pack operation.

When I want to define a strickt version of a dependency to be used in the .nuspec of packed project I have to use e.g

`<PackageReference Include="ExamplePackage" Version="[1.1.2]" />
`
This works fine for the .nuspec case, but prevents the possibility to update the package to the newer one in Visual Studio's package manager UI.  One have to modify PackageReference in project file manually.

If I would use 
`<PackageReference Include="ExamplePackage" Version="[1.1.2, ]" />
`
then I would be able to update the package in VS, but 
* it has different meaning in .nuspec than _Version="[1.1.2]"_
* VS package manager UI will replace _Version="[1.1.2, ]"_ by _Version="x.y.z"_

1. I miss a note in the article, that _PackageReference_ does not allow to use _allowedVersion_
2. I would like a possibility to allow an update to a newer version or at least a hint in the VS package manager UI that a newer version is available
3. I would like if VS will update to the newer version by only adapting the boundary version and not by replacing the whole version value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c462602-7e8f-2634-4006-3fadaa68ef45
* Version Independent ID: 7a6ec89f-55c5-2d49-6677-fcc87b0e40ac
* Content: [NuGet Package Version Reference](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning)
* Content Source: [docs/concepts/Package-Versioning.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/concepts/Package-Versioning.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@sieukrem - I have moved this issue to the product repo since your feedback is primarily about the product.

**Comment by donnie-msft** [comment]
There is already a related issue discussing this. I converted that issue to an epic, and will let this Issue serve as the PM UI side of any work done on this.

**Comment by nkolev92** [comment]
We are consolidating issues, closing this as dup of https://github.com/nuget/home/issues/6566
