### ISSUE TITLE
creating nuget package fails with no information - "IsPackable:true" is missing and needed to pack 

### ISSUE THREAD

**Issue by JimiSweden** [NuGet/Home#8877]
If you don't get a nuget package, look if this "<IsPackable>true</IsPackable>" is missing in the csproj PropertyGroup.

**Steps:**
VS 2019 -v: 16.3.10 , dotnet sdk 3.0.100
project: .NET.sdk, TargetFramework : netstandard2.0

I read all the "latest" docs explaining how to pack. * 
**Tested the following** 
from VS : right click on project in VS and selecting "pack"
MsBuild -t:pack
dotnet pack

information from the builds/packs was like this:
```
1>------ Build started: Project: LeeWay.Ensure.ControllerAttributes, Configuration: Release Any CPU ------
1>LeeWay.Ensure.ControllerAttributes -> C:\Git\LeeWay\LeeWay.Ensure.ControllerAttributes\bin\Release\netstandard2.0\LeeWay.Ensure.ControllerAttributes.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
 -  No errors, no information about the package. -

**when installing VS 2019 preview 16.4.0**
dotnet 3.1.100-preview3-014645

dotnet pack actually shows that "<IsPackable>true</IsPackable>" i needed in the csproj PropertyGroup.

```
Microsoft (R) Build Engine version 16.4.0-preview-19529-02+0c507a29b for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 54,43 ms for C:\Git\LeeWay\LeeWay.Ensure.ControllerAttributes\LeeWay.Ensure.ControllerAttributes.csproj.
  Restore completed in 495,88 ms for C:\Git\LeeWay\WebApi\WebApi.csproj.
  Restore completed in 495,89 ms for C:\Git\LeeWay\LeeWay.Ensure.ControllerAttributes.Tests\LeeWay.Ensure.ControllerAttributes.Tests.csproj.
  Restore completed in 495,89 ms for C:\Git\LeeWay\WebApi.ConfigurationTests\WebApi.ConfigurationTests.csproj.

  C:\Program Files\dotnet\sdk\3.1.100-preview3-014645\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(187,6): warning : This project cannot be packaged because packaging has been disabled. Add **<IsPackable>true</IsPackable> to the project file to enable producing a package from this project.** [C:\Git\LeeWay\WebApi\WebApi.csproj]
```

*
https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild

**Comment by karann-msft** [comment]
@JimiSweden - I have moved this issue to the product repo since your feedback is primarily around the product.

**Comment by donnie-msft** [comment]
@karann-msft can you elaborate why you think this doesn't belong in the Docs repo? It seems the linked docs do not explain the importance of IsPackable. 

The [first web search result](https://github.com/xunit/xunit/issues/1520#issuecomment-349282740) I found lead me to this comment: 
> After reaching near insanity-level confusion over why one of our infrastructure packages suddenly stopped outputting any nupkg files, I finally found this issue and after adding <IsPackable>true</IsPackable> we are back on track.

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #2036](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2036) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #2037](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2037) via [**ZenHub**](https://www.zenhub.com/)
