### ISSUE TITLE
How to CONFIGURE the package manager/nuget??

### ISSUE THREAD

**Issue by grimreaper38uk** [NuGet/Home#8878]
There is NO information on how to fix bad restore paths, edit ANY configuration or fix any of the myriad of problems that just appeared on my installation when I started work this morning.
I've lost hours on this b u l l s h i t already, and I can't find ANYTHING that documents HOW TO USE NUGET OR THE 'PACKAGE MANAGER CONSOLE' in VS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2942156d-9578-6b8a-6149-84724c6b1b56
* Version Independent ID: bface2dd-2e2d-ce98-8bda-21525bb0bf79
* Content: [Install and manage NuGet packages using the console in Visual Studio](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-powershell)
* Content Source: [docs/consume-packages/install-use-packages-powershell.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/install-use-packages-powershell.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
Moving this issue to Home since the feedback is primarily around the product.

**Comment by nkolev92** [comment]
Hey @grimreaper38uk 
Thank you for your feedback. 

As it stands now, we are not sure how to continue investigating this issue. 
Would you please create new issues for each individual gap you are facing. 

Please follow the template for product issues: https://github.com/NuGet/Home/issues/new.

**Comment by grimreaper38uk** [comment]
The question was: how does one configure package paths.
The implied question was: where is the documentation?

The solution of:
    It's not a bug.  Closed.
is absolutely ridiculous.
Thanks for getting back to it after 5 months though.  What a joke.
