### ISSUE TITLE
Update-Package does not work with PackageRef projects.

### ISSUE THREAD

**Issue by kagemartin** [NuGet/Home#8879]
Update-Package does not work with PackageRef projectsl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e755306-fb38-33c5-6f0f-1947832c21f2
* Version Independent ID: 0335cc14-e041-ffb3-f3c4-26dd39d18ef2
* Content: [Reinstalling and Updating NuGet Packages](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages)
* Content Source: [docs/consume-packages/Reinstalling-and-Updating-Packages.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Reinstalling-and-Updating-Packages.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by zkat** [comment]
This is stale, and this scenario does work. Please file a new one with repro steps if you run into this issue again.
