### ISSUE TITLE
NullReferenceException blocks install package when an invalid package source is selected

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#888]
Configuration:
NuGet Package Manager for VS 3.0.60624.657
D14Rel 23102.00

Granted it turns out this was user error in that a package source was a file when it should have been a directory. Nevertheless a `NullReferenceException` IMO always signifies a bug, and a more useful error message from NuGet would have unblocked me sooner.

Repro steps:
1. Add a package source in VS that is to a *file* on your local hard disk instead of a directory and select that as the active source.
2. install-package System.Collections.Immutable -version 1.1.36

> PM> install-package System.Collections.Immutable -version 1.1.36
Attempting to gather dependencies information for package 'System.Collections.Immutable.1.1.36' with respect to project 'ConsoleApplication1', targeting '.NETFramework,Version=v4.5.2'
install-package : Object reference not set to an instance of an object.
At line:1 char:1
+ install-package System.Collections.Immutable -version 1.1.36
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

First chance exception in debugger:

+		$exception	{"Object reference not set to an instance of an object."}	System.NullReferenceException

> >	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.GatherPackageFromSourceAsync(string packageId, NuGet.Versioning.NuGetVersion version, NuGet.Protocol.Core.Types.DependencyInfoResource resource, NuGet.Frameworks.NuGetFramework targetFramework, bool ignoreExceptions, System.Threading.CancellationToken token)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.ResolverGather.<GatherPackageFromSourceAsync>d__27>(ref NuGet.PackageManagement.ResolverGather.<GatherPackageFromSourceAsync>d__27 stateMachine)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.GatherPackageFromSourceAsync(string packageId, NuGet.Versioning.NuGetVersion version, NuGet.Protocol.Core.Types.DependencyInfoResource resource, NuGet.Frameworks.NuGetFramework targetFramework, bool ignoreExceptions, System.Threading.CancellationToken token)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.GatherPackageAsync(NuGet.PackageManagement.ResolverGather.GatherRequest request, System.Threading.CancellationToken token)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.ResolverGather.<GatherPackageAsync>d__26>(ref NuGet.PackageManagement.ResolverGather.<GatherPackageAsync>d__26 stateMachine)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.GatherPackageAsync(NuGet.PackageManagement.ResolverGather.GatherRequest request, System.Threading.CancellationToken token)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.StartWorkerTasks.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.__Canon>.Start<NuGet.PackageManagement.ResolverGather.(ref NuGet.PackageManagement.ResolverGather.<>c__DisplayClass25_0.<<StartWorkerTasks>b__0>d stateMachine)	Unknown
 	NuGet.PackageManagement.dll!NuGet.PackageManagement.ResolverGather.StartWorkerTasks.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<NuGet.PackageManagement.ResolverGather.GatherResult>>.InnerInvoke()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Execute()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown

**Comment by yishaigalatzer** [comment]
Verified this still repros in 3.3

**Comment by yishaigalatzer** [comment]
![image](https://cloud.githubusercontent.com/assets/1238711/13720658/847cbd72-e7c3-11e5-805b-615fdd74b3fe.png)
