### ISSUE TITLE
"Package Restore" doesn't take effect in vs2017 NuGet Package Manager configuration

### ISSUE THREAD

**Issue by GingerMoon** [NuGet/Home#8880]
Reproduce steps:
According to https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore-troubleshooting
Select the Tools > NuGet Package Manager > Package Manager Settings menu command.
Set both options under Package Restore.
Select OK.
Close the VS2017 and open it again, the two options are still unset. 
However, the file NuGet.Config was changed to:
<?xml version="1.0" encoding="utf-8"?>
```
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

but still met the error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\..\..\.nuget\packages\boost.1.64.0.0\build\native\boost.targets.	libbitcoin	C:\cppWorkspace\libbitcoin\builds\msvc\vs2017\libbitcoin\libbitcoin.vcxproj	553

**Comment by donnie-msft** [comment]
@zivkan looks like you were mistagged in an earlier comment. Any context on this one?

**Comment by zivkan** [comment]
No, I don't have any other context. Mike was helping with our docs and I was the go-to engineer when he had questions, so I assume that's why I was tagged.

**Comment by nkolev92** [comment]
This is not a bug, this just how packages.config works. 

In packages.config the assembly refs are burned into the csproj alongside a check that runs before build to verify that package is on disk. 

The solution is described in https://github.com/nuget/home/issues/8880#issuecomment-436848171
