### ISSUE TITLE
missing references related to sqlite

### ISSUE THREAD

**Issue by jagruti-caterlyst** [NuGet/Home#8883]
Severity	Code	Description	Project	Path	File	Line	Source	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\System.Data.SQLite.Core.1.0.112.0\build\net46\System.Data.SQLite.Core.targets.	CDC_Saleslyst	C:\Users\JagrutiPadariya\Documents\GitHub\CDC\CDC_Saleslyst\CDC_Saleslyst	C:\Users\JagrutiPadariya\Documents\GitHub\CDC\CDC_Saleslyst\CDC_Saleslyst\CDC_Saleslyst.vbproj	160	Build

**Comment by donnie-msft** [comment]
Have you tried to run NuGet restore, and if so, what errors are you seeing from that? You can learn how to run restore here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-visual-studio

**Comment by nkolev92** [comment]
Closing this issue as stale.
