### ISSUE TITLE
Copying nuget packages from one feed to another

### ISSUE THREAD

**Issue by garylogin** [NuGet/Home#8886]
Problem:

We have several branches on the way to release our product....I mention 2 here:
Developers machines
Dev Branch
We have a single feed for all packages called "ourproduct"

The developers build, create and test packages on their local machines.

At present they can use labels like alpha beta etc....prerelease versions..and they released directly to "ourproduct" feed.

Our CI uses the "Dev branch" and the "ourproduct" feed

When developers are ready they then check in their code to the "Dev branch", at present this can still reference a prerelease version.
The CI runs various tests on this branch which has access to the "ourproduct" feed.

Everything works fine...but now we want to release to our clients, but our tested packages are marked as prerelease...they are immutable.

I don't want to recompile the packages as different compilers might cause issues.

Solution:

So what if I do not use prerelease package versions....and I have 2 feeds...1 called "developers" 1 called "ourproduct".
Developers only use the "developers" feed
CI uses Dev branch and "ourproduct" feed

The process could now be developers do work, when they are happy to check into "Dev branch" and **copy packages** to the "ourproduct" feed.

This way we only end up with releaseable packages in the "ourproduct" feed.

**Comment by donnie-msft** [comment]
Not sure what you're asking for in this case. Are you not able to copy the NuGet packages to your second feed? If I understand, what you're asking for is to push distinct assemblies to 2 different local feeds, which you could certainly do with the [push command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-push#options) by specifying the -Source option. You can setup the two feeds using the [sources command](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources).
eg, If you named one of them "developerFeed", you could use the command 
`nuget.exe push -source "developerFeed" mypackage.1.0.0.nupkg`

**Comment by garylogin** [comment]
Hi Donnie, I have a big red face now :-) i can't believe i missed that thanks for your help
