### ISSUE TITLE
Constant "loading.." on installed tab, and "searching <term>.." on updates tab

### ISSUE THREAD

**Issue by anangaur** [NuGet/Home#8890]
#### Repro steps:
1. Open NuGet PAckage Manager on VS and Install a package to a project
2. Go to Browse, Installed and Updates tabs one after another
3. Go to Browse tab, search for a partial package ID term
4. Repeat Step 2
5. Keep repeating step 2,3,4 with different search terms and blanks

#### Expected:
Immediate results or no results on each tab

#### Actual
On installed tab:
![installed-tab-loading](https://user-images.githubusercontent.com/14800916/70415823-6259b080-1a12-11ea-803f-c5acb66abc48.gif)

![installed-tab-loading](https://user-images.githubusercontent.com/14800916/70415834-6a195500-1a12-11ea-8462-79ae63ba5676.png)

On updates tab:
![updates-tab-searching](https://user-images.githubusercontent.com/14800916/70416007-df852580-1a12-11ea-8448-744600add3cc.gif)

![updates-tab-searching](https://user-images.githubusercontent.com/14800916/70416041-f0359b80-1a12-11ea-8af0-adece36b26e6.png)

Note: Only default sources were enabled:

![default-sources-enabled](https://user-images.githubusercontent.com/14800916/70415810-5b32a280-1a12-11ea-87d1-13c97dfc090a.png)

**Comment by anangaur** [comment]
@chgill-MSFT , do add more information that I may have missed.

**Comment by donnie-msft** [comment]
@anangaur You're saying that "loading..." never disappears? Or is this a complaint about slow search? Not clear what is meant by "Expected: immediate results".

Would be great if you could include the version of VS where you're seeing this problem.

**Comment by anangaur** [comment]
I don’t think this is a perf issue. Sometimes it loads quickly and sometimes it just keeps loading. I used 16.5 preview 1

**Comment by dominoFire** [comment]
Appears to be fixed in https://github.com/NuGet/NuGet.Client/pull/3254

**Comment by anangaur** [comment]
Lets close the issue when we have a VS version to play with :)

**Comment by silkfire** [comment]
@dominoFire Has this fix been released to Visual Studio?

**Comment by aortiz-msft** [comment]
@silkfire The fix is available in 16.5.
