### ISSUE TITLE
Get onboarded on xplat signing work and help as needed

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#8891]

**Comment by zkat** [comment]
cc @heng-liu

**Comment by heng-liu** [comment]
Hi @zkat , thanks for helping me on xplat signing work! 
I've sent you an email about some materials to start with.
Pls don't hesitate to ping me if anything else is needed.

**Comment by zkat** [comment]
Thanks a bunch, Heng! I'll start looking through it right away. 🎉
