### ISSUE TITLE
How to install dependencies of a referenced project?

### ISSUE THREAD

**Issue by buddhashrestha** [NuGet/Home#8895]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.3.1.6268

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): win10

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem
I have two projects (Project A and Project B) and both have NuGet.config inside the directory where the solution file exists. Project A is dependent on Project B and according to my requirement, I have to reference Project B in Project A under another folder(Components). So I create the following structure to setup Project A:

- **Solution ProjectB**
      - ProjectB
          - Program.cs
          - ProjectB.csproj
          - packages.config
      - NuGet.config

Standalone ProjectB builds and runs fine.

- **Solution ProjectA**
   - ProjectA
        - Program.cs
        - ProjectA.csproj
        - packages.config
   - NuGet.Config
   - ComponentsFolder
        - ProjectB
             - XYZ.cs
             - ProjectB.csproj
             - packages.config
             - NuGet.config 

Now, while trying to build ProjectA it fails because

 all the dependencies for ProjectA is installed, but the dependencies for Project B is not installed. I know this makes sense since the project is created for ProjectA and it will look it's packages.config. 

But, I would like to know if there is any way NuGet will help me install the dependencies for ProjectB from ProjectA, without having to open ProjectB? 

I have attached the zip files of both the projects. Would be awesome if I could get some suggestion.
[ProjectA.zip](https://github.com/NuGet/Home/files/3942503/ProjectA.zip)
[ProjectB.zip](https://github.com/NuGet/Home/files/3942504/ProjectB.zip)

**Comment by donnie-msft** [comment]
It looks like you've added a direct Reference to the Exe. In order for NuGet to manage your dependencies, you have to create a NuGet package of your project. Detailed instructions for how this works are here https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio-net-framework

If you run into an issue with this process, let us know.

**Comment by buddhashrestha** [comment]
hi @donnie-msft ! Thank you for the reply. Yes, according to our requirement, we need to refer ProjectB as an executable in ProjectA. This is because while debugging code in ProjectA, we may want to put break points into ProjectB files as well. BTW, both ProjectA and ProjectB are in artifactory and when opening ProjectA, we copy ProjectB into ProjectA's components folder. So, from the components folder, we build ProjectB and then use it's executable to build ProjectA. I hope it makes sense. The problem is, we can't build ProjectB in first place, since it's Newtonsoft dependency is not resolved.

Here's a summary of my issue. Please let me know if I can improve the structure, but my main goal is to be able to put debug pointers on the referenced packages. This is why I structured the packages in such way,
![image](https://user-images.githubusercontent.com/10449218/70856426-e0dea400-1e91-11ea-9acc-fd76da106543.png)
