### ISSUE TITLE
dotnet pack doesn't build with GeneratePackageOnBuild flag but creates package

### ISSUE THREAD

**Issue by Gabsch** [NuGet/Home#8900]
## Details about Problem

Dotnet pack normally builds the project but it doesn't if "GeneratePackageOnBuild" is set to true.
This wouldn't be so bad and seems unfortunately to be by design (#6118), but it should definitely not just use previous build outputs to create the new package (with the new package version). 
There should be at least some warning (or better it should fail).

NuGet product used (dotnet.exe):

dotnet.exe --version: 3.0.100

OS version (i.e. win10 v1903 (18362.356)):

## Detailed repro steps so we can see the same problem

1. Create a new .NET Core Lib
1. Set `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`
1. Build via dotnet build
1. Change version
1. run "dotnet pack" in project folder
``

**Comment by nkolev92** [comment]
Hey @Gabsch 

Thank you for filing this issue. 
As you articulated, this behavior is by design. 
The pack functionality(like build) is incremental and will only run and create new files if necessary.
