### ISSUE TITLE
RestoreCommand_PathTooLongException is disabled for netcore, we need to enable it

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8920]
RestoreCommand_PathTooLongException is disabled for netcore.
We need to enable the test.

There's an related issue: https://github.com/NuGet/Home/issues/7588

**Comment by rrelyea** [comment]
I thought that netcore supports long file names nicely. So it may have different behavior than netfx???

**Comment by zkat** [comment]
I'm with @rrelyea on this one. If this test actually fails on NetCore, that tells me that it -does- support long filenames well, and what we should do instead is have a coreclr-only test that check that we _don't_ get an exception for long filenames. What do you think, @heng-liu, @dtivel?

**Comment by heng-liu** [comment]
@zkat I agree. But just have concerns on https://github.com/NuGet/Home/issues/7588. Seems we need to fix it before enable restore on NetCore?

**Comment by zkat** [comment]
I feel like #7588 is outside the scope of the package signing work, and it's admitted to be a lower-priority thing. We should take care of it eventually, but I'm not sure it has anything to do with getting package signing working?

**Comment by heng-liu** [comment]
@zkat You're right. GetAndVerifyRootDirectory is a general utility method. 
I think we may enable RestoreCommand_PathTooLongException test first and fix the #7588 later

**Comment by zkat** [comment]
I don't think it makes sense to enable it, because if NetCore handles long paths _better_, then we should just let NetCore be better? The test fails in NetCore, right?

**Comment by heng-liu** [comment]
We haven't tried to enable it, so it doesn't have a chance to run on NetCore yet.
