### ISSUE TITLE
How to upgrade local repository from .net core 2.2 to .net core 3.*?

### ISSUE THREAD

**Issue by LightVolk** [NuGet/Home#8922]
I have local nuget repository wich contains over 800 packages. Version of .net core is 2.2.
I have script that can push existing packages into this repo. Packages must be at my local computer.

So, how can i download all .net core 3.* sdk packages to my computer? If so, i can easy push all of this packages into my local repository.

Thank you!

**Comment by donnie-msft** [comment]
You're looking for an API to query by Target Framework and download all the results?

//cc @joelverhagen does nuget.org support something similar?

**Comment by nkolev92** [comment]
There's no utility/APIs to search by target framework today.
The general package applicability issue is https://github.com/NuGet/Home/issues/5725. 

@LightVolk How did you figure out which 800 packages need to be in your local source?

**Comment by LightVolk** [comment]
@nkolev92, @donnie-msft
The problem, in fact, has already been resolved as part of a manual, semi-automatic update of the necessary packages (.netсore, microsoft.extensions. * and others).

We have a corporate repository in which we have to update packages somehow.
Single updates are made by downloading the package and adding it through the **nuget.exe add package.**

But when the major version comes out, you have to update about 100-150 packages. Manually this is a difficult task. 
So I'm looking for a way to semi-automatically upgrade to the major version.
So far, the problem has been solved by using a program that downloads packages and their dependencies (maximum version) in a local directory and adding them to the repository.

P.S. the program is [https://github.com/paraspatidar/NugetDownloader](url).
I modify it to search maximum version of dependencies, but it not works ideal.

I do not push my changes to repo yet.



The problem itself is that when downloading a package and then downloading package dependencies, it is necessary that the maximum possible versions of dependent packages are selected.
This is necessary so that the corporate repository contains the maximum possible versions of not only the target package, but also its dependencies.

So far, this problem has not been solved by me 100%. I am using the above utility.
But she can not always get the maximum version of dependent packages.
In my modification, for each dependent package, a search is made in the global repository and from there I try to get the maximum version of the package.

**Comment by nkolev92** [comment]
So the thing you are looking for, is it safe to say it's 
"Given a package id, get me the latest version compatible with netcoreapp3.0" or are you looking to provide only the direct package dependency? 

> I modify it to search maximum version of dependencies, but it not works ideal.

NuGet PackageReference always tries to resolve the lowest required version by the requested packages, because that's the scenario where things are the most likely to work at runtime. So if you always try to get only the latest dependency packages, NuGet will raise lots of warnings like https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1603.

**Comment by LightVolk** [comment]
@nkolev92 ,yes it is that i want to get: latest dependencies (max versions)

**Comment by nkolev92** [comment]
That's not possible in PackageReference right now, see https://github.com/NuGet/Home/issues/5553. 

Given all this, we have 2 issues that can help your scenario, but they are not implemented yet. 
Do you see any other ask here?

**Comment by LightVolk** [comment]
@nkolev92 , thank you for response! I will be wait! :)
