### ISSUE TITLE
Improve search with package recommendations

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#8924]
Deliver spec to explore business/technical options.
Client side and/or Server side?
etc...

**Comment by rrelyea** [comment]
PR for first draft of spec: https://github.com/NuGet/Home/pull/8961

**Comment by donnie-msft** [comment]
A Bug was reported against the a11y of Browse tab's available recommendations. As part of this work, we should find a way to make users aware how many recommendations are available. (Bug #1049190)

**Comment by nkolev92** [comment]
Just cleaning up. This is done.
