### ISSUE TITLE
Updating package ‘EntityFramework’ need to restart VS for 3 times

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8928]
##  Details about Problem
NuGet version: NuGet Client Dev\5.5.0.6346
VS Version: Master\29612.110
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Launch VS and click “Create a New Project” button.
2. Create an ASP.NET Web Application (.NET Framework) project (Single Page Application).
3. Open PM UI of this project and go to ‘Update’ tab.
4. Select all packages and click ‘Update’ button.
## Expected
Updating package ‘EntityFramework’ from version 6.2.0 to 6.4.0 need to restart VS for only 1 time.
## Actual
Updating package ‘EntityFramework’ from version 6.2.0 to 6.4.0 need to restart VS for 3 times as below screenshot. That’s boring to restart VS just for uninstalling the same package ‘EntityFramework.6.2.0’.
![ThreeTimeRestartRequest](https://user-images.githubusercontent.com/20632625/70799964-ff876100-1de5-11ea-8509-ad61df4236f1.png)
## Note
It didn’t repro on 16.5 Preview1: D16.5\29521.150 (with implicit NuGet Client 5.5.0.6293)

**Comment by v-luzh** [comment]
Only one-time restart request repro on Master\29619.96+NuGet Client Dev\5.5.0.6353. Got the log from handle.exe as below.
![image](https://user-images.githubusercontent.com/20632625/71236278-859d2d80-2339-11ea-89a7-b375f58b87fc.png)

PS C:\Users\v-luzh\Desktop\Handle> .\handle.exe -a "C:\Users\v-luzh\source\repos\WebSinglePage\packages\EntityFramework.6.2.0\tools\EntityFramework.PowerShell.Utility.dll"

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

devenv.exe         pid: 14520  type: File          2084: C:\Users\v-luzh\source\repos\WebSinglePage\packages\EntityFramework.6.2.0\tools\EntityFramework.PowerShell.Utility.dll

**Comment by heng-liu** [comment]
Hi @v-luzh, is this a regression?
I tried but could not repro on 16.5 Preview4 (restarted only 1 time). 
But I'm not sure if it's fixed on 16.5 Preview4. Could you help to repro on 16.5 Preview4, to see if it still exists? Thanks!

**Comment by heng-liu** [comment]
Hi @v-luzh, to be more accurate, can you help to repro on latest VS version in rel/d16.5? Thanks!

**Comment by heng-liu** [comment]
Close it as couldn't repro on 16.5 Preview4. 
Pls reopen it if you can still repro. Thanks!

**Comment by v-luzh** [comment]
Hi @heng-liu, sorry, just saw your message since I didn't get your update comments in my mail-reminder. I can repro this bug on D16.5 GA (D16.5\29905.175)--asked to restart twice. Please help to reactivate it, thanks.

**Comment by heng-liu** [comment]
Hi @v-luzh , I just tried twice the following steps, but could not repro. (only 1 restart is required)
May I know if I miss anything in the repro? Or can you pls provide the detailed repro steps? Thanks!
1. Launch VS16.5.0 Preview 6.0 [29905.175.d16.5]
 
![image](https://user-images.githubusercontent.com/45407901/76255540-93ad6c80-620b-11ea-9e56-8d1fa77a0ae4.png)
2. Create a new ASP.NET web application(.NET Framework) project
![image](https://user-images.githubusercontent.com/45407901/76255634-bd669380-620b-11ea-8529-c866154976cf.png)
3. Choose Single Page Application
![image](https://user-images.githubusercontent.com/45407901/76255847-1fbf9400-620c-11ea-9426-3bd7ffe47888.png)
4. Open PM UI of this project and go to ‘Update’ tab, select all packages and click ‘Update’ button.
![image](https://user-images.githubusercontent.com/45407901/76256034-7d53e080-620c-11ea-9609-2e6d7dbd2657.png)
5. Finish all the updates and click the restart
![image](https://user-images.githubusercontent.com/45407901/76256378-12ef7000-620d-11ea-94d7-8f8d1b5a69d9.png)
6. Open the PM UI, and no restart is required anymore
![image](https://user-images.githubusercontent.com/45407901/76256499-49c58600-620d-11ea-872d-a1fd7c221027.png)

**Comment by v-luzh** [comment]
Hi @heng-liu, you can see the second-time restart request (as below screenshot) in PM Console in your step6.
![image](https://user-images.githubusercontent.com/20632625/76279007-185dc080-62c8-11ea-88d0-7951583c91d0.png)

**Comment by heng-liu** [comment]
Hi @v-luzh thanks for your reply! I'm able to repro now :)
This is after updating all the packages, before the first restart
![image](https://user-images.githubusercontent.com/45407901/76354886-8312fa00-62d0-11ea-8fe3-35200ca1405c.png)
If I click the restart button on the top, after the first restart, I could not found any restart request in my repro..
![image](https://user-images.githubusercontent.com/45407901/76354969-a8076d00-62d0-11ea-8320-c8faec9e3b0e.png)
If I click the restart button on the bottom(in PMC), then after restart, there will be another restart request in PMC.
So in your repro, you click the restart in PMC, right? Thanks!

**Comment by v-luzh** [comment]
Hi @heng-liu, yes, that's how I repro this issue. Please have a look, thanks,

**Comment by heng-liu** [comment]
It doesn't repro on ASP.NET .netcore. Only repro for ASP.NET .netframework.
And after clicking restart in PMC for two times, it goes back to normal. So it doesn't affect any operation after it.

**Comment by v-luzh** [comment]
Closing this bug since it is fixed on VS Main\34807.21 + NuGet Client Dev\6.11.0.9.
