### ISSUE TITLE
Dependency resolution only within same repository

### ISSUE THREAD

**Issue by krafs** [NuGet/Home#8932]
## Details about Problem

NuGet product used:
NuGet.exe

NuGet version:
5.4.0.6315

OS version:
10.0.18363 Build 18363

## Detailed repro steps so we can see the same problem

1. Add new source (e.g. **simple-source**) to _nuget.config_

2. Add a new package (e.g. **startup**) to **simple-source**

3. Install the package: `nuget install startup -source simple-source`

NuGet successfully installs **startup**, but then attempts to resolve any dependencies it might have. It seems to do this by searching for the package in simple-source **and** nuget.org. The problem is this: If a different package, on nuget.org, also happens to be named **startup**, nuget.exe will resolve the dependency of that package instead of (in addition to?) mine.

Now, maybe there is a command to tell nuget.exe to only resolve dependencies in a specific repository? Because I like having several sources specified in my nuget.config, but I want to be able to choose between them - not only for the one package, but for all the dependent packages as well.

Even if I enforce unique package id on all packages, maybe some other developer uploads a package to nuget.org that is unique there, but that conflicts with a package on my private feed. So the next time I install that package from my own feed, it would suddenly also download any and all dependency of that new package over at nuget.org

Is this already a feature, that I've missed?

**Comment by donnie-msft** [comment]
Install is behaving as expected. All enabled sources are used for dependency resolution.

Names and versions of NuGet packages should be unique. See guidelines: 
https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#choose-a-unique-package-identifier-and-setting-the-version-number

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package
