### ISSUE TITLE
Broken test in SignatureTest

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8933]
In SignatureTest,  Verify_WithUntrustedSelfSignedCertificateAndNotAllowUntrusted_FailsAsync failed on Linux and Mac

**Comment by nkolev92** [comment]
You should be adding test/bug labels etc. 

See Client team Hot Seat rotation One note - 2.

**Comment by heng-liu** [comment]
Thanks for your suggestion :)

**Comment by zkat** [comment]
This is done. See https://github.com/NuGet/NuGet.Client/pull/3208
