### ISSUE TITLE
Broken test in TimestampTests

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8935]
In TimestampTests,
test Timestamp_Verify_WithOfflineRevocation_ReturnsCorrectFlagsAndLogsAsync  failed on Linux and Mac.

**Comment by zkat** [comment]
Note: This is hanging when calling `SignedArchiveTestUtility.CreateAuthorSignatureForPackageAsync`, so the failure might just be a bug in our test utility. Looking into it now.

**Comment by heng-liu** [comment]
Pls take [this](https://github.com/dotnet/runtime/blob/master/docs/design/features/cross-platform-cryptography.md#x509chain) into consideration for Mac.

**Comment by rrelyea** [comment]
is this ready for review? think that the current PR had failures still. i checked because it is in the "in review" column on the board.

**Comment by zkat** [comment]
Sorry, I should've moved it back to In Progress.
