### ISSUE TITLE
Linux machines failing CI builds due to dotnet-install connection problem

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#8936]
Linux Machines are failing to run Functional Tests when attempting to run dotnet-install.sh.
There appears to be some network configuration or connectivity problem.
`curl: (7) Failed to connect to dotnet.microsoft.com port 443: Connection timed out`

Example failing builds:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298450
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298446
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3298399

As a temporary workaround, I placed the resolved script directly into our build folder: https://github.com/NuGet/Home/issues/8931

[This build](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=3317306) calls  curl -o cli/dotnet-install.sh -L -v https://dot.net/v1/dotnet-install.sh.  curl follows a redirection to https://dotnet.microsoft.com/download/dotnet-core/scripts/v1/dotnet-install.sh but is then unable to reach that URL.

@dtivel  noticed that curl tries using the IPv6 address, so he forced IPv4 in [this build](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=3317526), but the overall failure is still the same.

**Comment by erdembayar** [comment]
@NuGet/nuget-client 
It looks we have workaround embedded `dotnet-install.sh` which is very outdated. See [comment](https://github.com/NuGet/NuGet.Client/pull/4289#pullrequestreview-767238072). I believe we need to bump up priority on this issue, at least [update content of embedded](https://github.com/NuGet/NuGet.Client/pull/4289#issuecomment-930617890) `dotnet-install.sh` and add ` -Quality Daily`  option into it.

**Comment by erdembayar** [comment]
I'm reassigning this to next hotseat @jebriede. Once incident is resolved we need to re-enable tests.

**Comment by erdembayar** [comment]
Sorry, actually this is my item. Reassigning to myself.

**Comment by erdembayar** [comment]
Increased estimate because I need to address [functional test scripts too](https://github.com/NuGet/NuGet.Client/pull/4289#pullrequestreview-767238072).
