### ISSUE TITLE
Issue loading Credential plugins using NuGet.Credentials

### ISSUE THREAD

**Issue by eByte23** [NuGet/Home#8942]
## Details about Problem

Trying add Azure credentials plugin support to NuKeeper. 
From what I can see the correct? way  is to use   `DefaultCredentialServiceUtility.SetupDefaultCredentialService`

How ever when I do this I get 
```
Problem starting the plugin 'C:\Users\%username%\.nuget\plugins\netcore\CredentialProvider.Microsoft\CredentialProvider.Microsoft.dll'. Cannot start process because a file name has not been provided.
```

And the azuredevops packagesource will continue to return a 401.
I'll include for details below.

NuGet product used:
```
<PackageReference Include="NuGet.Protocol" Version="5.3.0" />
<PackageReference Include="NuGet.Credentials" Version="5.3.0" />
```

OS version:
Win10 v1909 build. 18363.476

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem
1. Use a package source from AzureDevops or other that requires Credential Plugin Auth.

2. Run NuKeeper inspect <ProjectPath>

...

### Sample Project
WIP change to test it https://github.com/eByte23/NuKeeper/commit/0ca5663746a2520e6d41e13e5de06bea2ce8a787

Exact Line
https://github.com/eByte23/NuKeeper/commit/0ca5663746a2520e6d41e13e5de06bea2ce8a787#diff-ec12459316ee7139ad1ac4e840a8f00aR47

**Comment by eByte23** [comment]
Any advice here?

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/7438
