### ISSUE TITLE
Github as a PSRepository?

### ISSUE THREAD

**Issue by Liturgist** [NuGet/Home#8948]
We have a local Enterprise GitHub instance. We would like to make use of standard installation tools for both PowerShell and Python code. We want to install only what is needed and not replicate the entire project repository onto every machine that will run the code.

It appears that we could create a local Enterprise NuGet server. Is that needed?

Where can I find information on publishing a GitHub project to NuGet?

Can GitHub act as a PSRepository which would make PowerShellGet commands see it as a PSRepository?

We need to do the same thing for Python applications and modules? Can a NuGet server act as a repository for Python installations? Or, is there a way to publish a GitHub project to PyPI?

**Comment by dominoFire** [comment]
> It appears that we could create a local Enterprise NuGet server. Is that needed?

You may need to take a look at the official documentation for GitHub Package Registry (GPR). You can configure GPR as a NuGet server: https://help.github.com/en/github/managing-packages-with-github-packages/configuring-dotnet-cli-for-use-with-github-packages

> Where can I find information on publishing a GitHub project to NuGet?

See https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package

> Can GitHub act as a PSRepository which would make PowerShellGet commands see it as a PSRepository?

In theory, yes. See https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-local-psrepositories?view=powershell-6

> We need to do the same thing for Python applications and modules?

In the GPR documentation, there's no scenario described for Python packages. You may need to use another Python package repositories. 
 
> Can a NuGet server act as a repository for Python installations? 

Unfortunately, we don't support Python wheels or packages on nuget.org

> Or, is there a way to publish a GitHub project to PyPI?

In theory, yes. See https://packaging.python.org/tutorials/packaging-projects/

If you have more questions regarding nuget.exe, dotnet nuget, NuGet on Visual Studio or nuget.org, you create a new issue.
