### ISSUE TITLE
Allowed supressing a downgrade warning

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#895]
Edit: This was originally tracking supressing an error, downgrade is a warning and we want to be able to ignore it

In NuGet 3.0 when a downgrade error occurs (top level package downgrades an eclipsed version), there is no way to override it.

This is a regression from the packages.config scenario where you could do it.

**Comment by RanjiniM** [comment]
@davidfowl, can you please comment on what is expected/ desired behavior here?

**Comment by yishaigalatzer** [comment]
This is now a warning, so the ask is to be able to suprress it
