### ISSUE TITLE
CSProj doesn't find central version from Directory.Packages.props

### ISSUE THREAD

**Issue by kushaag** [NuGet/Home#8951]
I created Directory.Packages.props file at solution level, but project doesn't refer Directory.Packages.props for version. Followed steps from https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions. 

[central-level-pkg.zip](https://github.com/NuGet/Home/files/3971647/central-level-pkg.zip)
@lovakumar

Please suggest if I am missing something.

**Comment by Lovakumar** [comment]
Added @anangaur for quick resolution.

**Comment by anangaur** [comment]
+@cristinamanum 

 This feature is currently being implemented. The link mentioned above is to the spec that’s currently being reviewed.

This is the second time folks have reached me. Looks like we need to mention “Spec” and status more prominently. However, happy to see developers are actively looking for the feature.

**Comment by kushaag** [comment]
Thank you Anand! could you please let us know when the feature will be available ?

Thanks,

**Comment by dominoFire** [comment]
@kushaag Please, see this issue for news and release announcements for Central Package Version Management (CPVM) in NuGet: https://github.com/NuGet/Home/issues/8256

A possible workaround is to use https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions

I will close this issue in favor of the NuGet CPVM epic issue. If you have more questions, feel free to open this or another issue.
