### ISSUE TITLE
Remove Temp fix on patching

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#8952]
For xplat verification, we use a temporary workaround to make the patching SDK work. We should remove this Temporary fix on patching when https://github.com/NuGet/Home/issues/8570 or https://github.com/dotnet/sdk/issues/3629 is closed.

**Comment by heng-liu** [comment]
This should be done after our first insertion into SDK, and before the second insertion into SDK

**Comment by zivkan** [comment]
The `NuGet.Packaging.csproj` has [a comment saying to remove two package references to remove a temp fix, with a link to this issue](https://github.com/NuGet/NuGet.Client/blob/b7c15bd1681b768c894a612590edcdd77fdd2bcc/src/NuGet.Core/NuGet.Packaging/NuGet.Packaging.csproj#L52-L54).

While we can probably get rid of the `deps.json` patching code from `DotNet.Integration.Tests`, we'll still need these package references unless the two assemblies become part of the .NET 5 Base Class Libraries (BCL) that are references automatically when using the `net5.0` TFM (and therefore the runtime that all .net5.0 apps will have access to). Inserting NuGet into the SDK while we have the PackageReference will not do that.

Therefore, we can get rid of the comment in the csproj, right?  Or am I missing something?

**Comment by heng-liu** [comment]
Nice catch~ Yes, that's right. I'll remove the comment when fixing this issue. 
Thanks.

**Comment by heng-liu** [comment]
This is blocked(Same as https://github.com/NuGet/Client.Engineering/issues/367). 
As the SDK version for testing should be at least 5.0 preview7.

**Comment by tmds** [comment]
> As the SDK version for testing should be at least 5.0 preview7.

hi @heng-liu, I came across this issue when looking at making some patches for source-build. Is there some progress on updating the SDK to one that uses the `net5.0` tfm instead of `netcoreapp5.0`?

When the SDK gets updated, can the [`NETCoreTargetFramework`](https://github.com/NuGet/NuGet.Client/blob/c5f496dae608298cb9d57768444717613400d3dc/build/common.project.props#L16) also be changed to `net5.0`? Or what is the reason this remains at `netcoreapp2.1`?

**Comment by heng-liu** [comment]
Closed as fixed by https://github.com/NuGet/NuGet.Client/pull/3777

**Comment by nkolev92** [comment]
Issues such as this should be tagged with engineering to avoid getting picked up in the release notes.
