### ISSUE TITLE
 /p:BuildProjectReferences=false should imply RestoreRecursive="false"

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8962]
Say you have a project structure as such: 

A -> B -> C -> D 

where all projects are package reference based projects.

If you run restore it will automatically restore for all packages A through D by default: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L44

Build will also do the same thing. 

However, if you pass 
 /p:BuildProjectReferences=false to a command like: 

> msbuild /restore /t:build  /p:BuildProjectReferences=false

restore will run for alll projects, but build will only be run for the top project. 

The proposal is for restore to honor this property in addition to restore recursive.

**Comment by nkolev92** [comment]
@jeffkl @rainersigwald @nguerrera @dsplaisted
Thoughts?

**Comment by jeffkl** [comment]
`BuildProjectReferences=false` only tells MSBuild not to call the `Build` target, the build still consumes the outputs of the project references.  That said, if you don't build the project reference, I don't see how any package assets would be consumed either.  I also don't know of any user-facing cases where we specify `BuildProjectReferences=false`, most of the usages I can think of are advanced scenarios that we mostly own.  So I would assume its fine to do a non-recursive restore, although I am working on making no-op much faster so maybe its moot?

**Comment by nguerrera** [comment]
I don't know enough about what RestoreRecursive=false does to say if this is correct. Does it change the graph? Do you still get transitive refs from the last time you restored?

**Comment by nkolev92** [comment]
When you invoke restore on a project, NuGet will run the restore for the project and all of it's dependencies. 
Specifically, A -> B -> C, all 3 projects will get assets file. 
RestoreRecursive doesn't control the flow of dependencies, they still get transitively applied as usual. It merely controls whether your children projects themselves get restored.

So it's basically the equivalent of BuildProjectReferences just in the restore context.

**Comment by nkolev92** [comment]
Closing this as low pri.
