### ISSUE TITLE
Cannot do any mouse control when the check-box of package in ‘Updates’ Tab is checked by Tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8964]
## Details about Problem
NuGet version: NuGet Client Dev\5.5.0.6353
VS Version: Master\29619.96
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Launch VS and click “Create a New Project” button.
2. Create an ASP.NET Web Application (.NET Framework) project (Single Page Application).
3. Open PM UI of this project and go to ‘Updates’ tab.
4. Navigate by Tab to the package list.
5. There is a dash-line showing on the outer edge of the first package.
6. Hit Tab again, attempt to focus on the check-box of this package.
7. Hit Space on the keyboard to check the check-box.
8. Try to click another package by mouse.
## Expected
Mouse control should also be successful when the check-box of package in ‘Updates’ Tab is checked by Tab.
## Actual
Cannot do any mouse control when the check-box of package in ‘Updates’ Tab is checked by Tab.Please refer to below video.
![MouseControlLost](https://user-images.githubusercontent.com/20632625/71243567-98206280-234b-11ea-9c99-47a0c6b4e0c8.gif)

## Note
1.It repro on 16.2 GA (D16.2\29116.123) with implicit NuGet 5.2.0.6090.
2.It doesn't repro when the check-box is checked by mouse.

**Comment by dominoFire** [comment]
Confirmed in GA and in 29619.127 ; it seems to be a problem when triggering focus events

**Comment by v-luzh** [comment]
This bug is fixed on Dev\5.10.0.7143. Close it now, thanks.
