### ISSUE TITLE
[Test Failure]Confusing supported .NET Framework version v0.0 show in the error NU1202 message when installing a package into a project with incompatible framework

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#8965]
## Details about Problem
NuGet version: NuGet Client Dev\5.5.0.6353
VS Version: Master\29619.96
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. Create a C# Blank App (Universal Windows) template via VS.
2. Open PM UI of the project by right-clicking the project->Manage NuGet Packages… in Solution Explorer.
3. Search the package “Blend.Interactivity.Wpf” in Browse tab and install it.
4. Look at the error message in Error List window.
## Expected
Package supported .NET Framework version v0.0 will not show in the error NU1202 message.
## Actual
Confusing supported .NET Framework version v0.0 show in the error NU1202 message as below screenshot. NuGet should prevent user to input wrong .NET Framework version if that is coming from user.
![NU1202ErrorMessage](https://user-images.githubusercontent.com/20632625/71240297-b8e4ba00-2343-11ea-9a63-6d55dff07711.png)

**Comment by nkolev92** [comment]
The package in question contains a "lib/net" folder which basically suggests, these package assets are compatible with all .NET Frameworks, hence v0.0. 

The message is as expected.

The package itself is old and built in a way that's not recommended today, but what they did is still valid (even though it's unlikely that the assembly will work correctly in all .NET frameworks).
