### ISSUE TITLE
Investigate E2E machine failures

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#8969]
An example: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3342180

02 and 03 are failing. 

@donnie-msft has already disabled couple of other machines.

01,04,06 have been disabled throughout people on the team.

We should keep this task open until we diagnose the issues that are happening with our scripts.

**Comment by zivkan** [comment]
We haven't had E2E failures since https://github.com/NuGet/NuGet.Client/pull/3184 was merged.
