### ISSUE TITLE
Allowed overriding a downgrade error

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#897]
In NuGet 3.0 when a downgrade error occurs (top level package downgrades an eclipsed version), there is no way to override it.

This is a regression from the packages.config scenario where you could do it.

**Comment by yishaigalatzer** [comment]
NuGet allows for overriding a version constraint, but the check we added last week is too strict. We would like to change it from an error to a warning.

@ericstj @lodejard

**Comment by pranavkm** [comment]
We went with making downgrade errors, warnings instead.

**Comment by pranavkm** [comment]
Fixed in https://github.com/NuGet/NuGet3/commit/55b23faac8841f7b4da97b6eb577efccae9ecb1e
