### ISSUE TITLE
Insertion of 5.5.0-preview2.6355

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#8971]
VS
* [x] PR: [220494](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/220494?_a=overview)

.NET Core SDK 3.1.2xx
* [x] CLI ([PR](https://github.com/dotnet/cli/pull/13164))
* [x] SDK ([PR](https://github.com/dotnet/sdk/pull/4105))
* [x] Toolset ([PR](https://github.com/dotnet/toolset/pull/3926))

.NET Core 5 Dev
* [x] SDK (https://github.com/dotnet/sdk/pull/4075)  - old one was not completed, so bot just updated the old PR :) https://github.com/dotnet/sdk/pull/4075/commits/8b18beb735df7b3a607040e9a16c3bac758c6c39
* [x] Toolset ([PR](https://github.com/dotnet/toolset/pull/3927))

* [x] Follow up version increment [PR 3177](https://github.com/NuGet/NuGet.Client/pull/3177)

**Comment by nkolev92** [comment]
Found the SDK PR :)  
The old one was not completed, so bot just updated the old PR :) dotnet/sdk@8b18beb

**Comment by heng-liu** [comment]
Closed as completed.
