### ISSUE TITLE
GeneratePackageOnBuild is transitive through ProjectReference

### ISSUE THREAD

**Issue by daveaglick** [NuGet/Home#8983]
It appears that `GeneratePackageOnBuild` is transitive through a `ProjectReference`. For example,
- Given a project A with `GeneratePackageOnBuild`, `a.nupkg` will be generated in the output folder of A
- Given a project B with a `ProjectReference` to A, `a.nupkg` will _also_ be generated in the output folder of B

This seems like a bug (though maybe it's by design?). It's particularly problematic in CI scenarios where you want to build all projects and then crawl for packages to push. Because of this behavior, all your test project outputs will have the packages of the projects they're testing. Likewise, you'll end up with multiple copies of packages if any projects reference other projects.

In my opinion the behavior should be to generate and output a package only for the project that contains `GeneratePackageOnBuild`. Maybe I'm missing a way to disable that behavior?

**Comment by nkolev92** [comment]
Hey @daveaglick. Thanks for filing this. 

I was unable to repro the issue with the described steps. 
Here's what I did. 

I create a sln with 2 netstandard projects, A & B, where B -> A. I set GeneratePackageOnBuild in A and run build. 

See the attached zip with the project structure.
[8983.zip](https://github.com/NuGet/Home/files/4013357/8983.zip)

Here are the logs: 

```
C:\Users\Nikolche\Documents\Code\Test\8983 [master]> dotnet build .\8983.sln
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 160.22 ms for C:\Users\Nikolche\Documents\Code\Test\8983\A\A.csproj.
  Restore completed in 160.22 ms for C:\Users\Nikolche\Documents\Code\Test\8983\B\B.csproj.
  A -> C:\Users\Nikolche\Documents\Code\Test\8983\A\bin\Debug\netstandard2.0\A.dll
  Successfully created package 'C:\Users\Nikolche\Documents\Code\Test\8983\A\bin\Debug\A.1.0.0.nupkg'.
  B -> C:\Users\Nikolche\Documents\Code\Test\8983\B\bin\Debug\netstandard2.0\B.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.20
C:\Users\Nikolche\Documents\Code\Test\8983 [master]>

C:\Users\Nikolche\Documents\Code\Test\8983 [master]> ls C:\Users\Nikolche\Documents\Code\Test\8983\B\bin\Debug\                                                                                                                                    

    Directory: C:\Users\Nikolche\Documents\Code\Test\8983\B\bin\Debug


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        31-Dec-19  11:22 AM                netstandard2.0


C:\Users\Nikolche\Documents\Code\Test\8983 [master]> ls C:\Users\Nikolche\Documents\Code\Test\8983\A\bin\Debug\                                                                                                                                    

    Directory: C:\Users\Nikolche\Documents\Code\Test\8983\A\bin\Debug


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        31-Dec-19  11:22 AM                netstandard2.0
-a----        31-Dec-19  11:22 AM           3161 A.1.0.0.nupkg


C:\Users\Nikolche\Documents\Code\Test\8983 [master]>
```

Anything that you do differently? 
Attaching a binlog would be great (note that it will contain the env vars on your machine).

**Comment by nkolev92** [comment]
Closing per the above comment. 
Please provide us a repro project if you are still having issues.
