### ISSUE TITLE
NuGet restore exited with code 3

### ISSUE THREAD

**Issue by hossambarakat** [NuGet/Home#900]
I have a solution inside a folder with name including dash (–) i.e "Project – Name\mysolution.sln". 
When I try to run NuGet Package restore. I receive the message NuGet existed with code 3.

After I have remove the dash everything is working correctly.

The folder name is the TFS project name which is can't be changed.

Any solutions or workarounds??

**Comment by yishaigalatzer** [comment]
Workarond is to rename the project name in TFS (I understand this might be hard for you). We will take a look at fixing this

**Comment by hossambarakat** [comment]
Thanks @yishaigalatzer,
I can't rename the TFS project because the feature is not there yet :). Renaming TFS project is available on TFS 2015 and VSO and I am not using any of them.

**Comment by yishaigalatzer** [comment]
So I guess the solution is to recreate it, I'm hoping there is not too much history there. I also think there is a way to map the tfs project to a different folder locally, I don't recall how to do it or if its applicable for your project

**Comment by hossambarakat** [comment]
I have changed the mapping locally and restore worked correctly. The issue with build server which will require changes to the workspace mapping

**Comment by yishaigalatzer** [comment]
cool! Looks like you have a workaround. Happy I could help. We will get a look at fixing this as well.

**Comment by alexsandro-xpt** [comment]
Thanks!!

**Comment by yishaigalatzer** [comment]
Verified this is fixed in NuGet 3.2.1 (and perhaps in earlier versions) available on https://dist.nuget.org/index.html

There might be another issue going with your project that I couldn't repro with my simple steps, if so feel free to open another issue with accurate repro steps and a sample.

See below:
![image](https://cloud.githubusercontent.com/assets/1238711/10678542/fa52dbaa-78c7-11e5-8a3d-7e36b83da746.png)

**Comment by deepakaravindr** [comment]
I have verified that this scenario works as desired, by creating a net45 C# application named 'A - A', installing WindowsAzure.Storage.4.3.0 on the created project, deleting the packages folder and calling 'nuget.exe restore on the solution file' using nuget.exe version 3.3
