### ISSUE TITLE
DependencyGraphSpec should support adding projects concurrently

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#9002]
## Details about Problem

The [DependencyGraphSpec](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs) object uses a standard collection object as a backing collection.  This makes it impossible to use it in a parallel loop or multiple threads.  It should use a concurrent collection instead.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Any

NuGet version (x.x.x.xxx): Any

dotnet.exe --version (if appropriate): any

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.
2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
This one should be an easy win.

**Comment by nkolev92** [comment]
The fact that we are doing post processing for CPVM pruposes during `AddProject` means that simply using concurrent collection is likely enough, but we need extra considerations.

https://github.com/NuGet/NuGet.Client/blob/62e098bfb22998fa638ce1a6dff5f91276770500/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L241-L258

I'm curious about the effect this would have on Visual Studio if we were to add the parallelism there.

**Comment by erdembayar** [comment]
Connected to this code: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L241
