### ISSUE TITLE
add tests on cross verifying signed packages 

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9003]
Since we have some different code paths for different platforms for signing/verification, we should generate signed packages on all platforms(windows/Linux/Mac), and cross verify them.
The list of signed packages should be cross verified are:
1.Author signed.
2.Author signed & timestamped.
3.Repository signed.
4.Repository signed & timestamped.
5.Author signed , repository countersigned.
6.Author signed & timestamped, repository countersigned.
7.Author signed, repository countersigned & timestamped.
8.Author signed & timestamped, repository countersigned & timestamped.

**Comment by zkat** [comment]
TODO: Make sure to check error cases, too, also check that tampered packages are properly detected.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Client.Engineering/issues/591 which has since been implemented.
