### ISSUE TITLE
trim guardrails messages

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#901]
Guardrails messages show lots of checking messages that are mostly noise in the output window. The summary shows fails and the user has to crawl up a long list if errors.

1. Minimize the spew
2. Repeat the relevant errors on the bottom of the spew
3. See if the error I error list can be meaningful

@davidfowl

**Comment by yishaigalatzer** [comment]
Also verify that filtering by error level works

**Comment by deepakaravindr** [comment]
1. Filtering by error level works. By default, the verbosity level is minimal. If the msbuild verbosity level is set to diagnostic, we get the guardrails messages which are debug messages as well. Does the issue suggest that we don't show debug messages at all?
2. Errors, in addition, to being shown as they occur on the output window, are also shown on the error list window. Hence, one can look for error messages in the error list window. We did not have this until one of the recent check-ins
3. Errors in the error list window are as they appear from the logger abstraction. If certain error messgaes messages are not meaningful, we should fix them. Are there any specific ones?

**Comment by deepakaravindr** [comment]
Discussed offline with @yishaigalatzer . Since, the messages shown on the output window are filtered by msbuild verbosity level, this bug can be closed as 'Won't Fix'
