### ISSUE TITLE
Signing: Design dotnet package signing commands

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9010]
Write up an RFC describing the commands and options and get it reviewed before implementing the actual commands.

**Comment by aortiz-msft** [comment]
We will start with dotnet nuget verify, dotnet nuget trusted-signers, and dotnet nuget sign commands. @zkat will follow up with Kathleen and others to see if there are any concerns with this proposal

**Comment by rrelyea** [comment]
based on my previous discussions with livar/kathleen before i did the dotnet nuget add/remove/etc.. sources work:
dotnet nuget verify
dotnet nuget sign.
dotnet nuget add/remove trusted-signers   [verb goes before noun]
perhaps dotnet nuget list trusted-signers   (which would map to nuget trusted-signers)

**Comment by zkat** [comment]
@aortiz-msft why did this get reopened?
