### ISSUE TITLE
Re-enable OSX failing signing tests

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9013]
These 4 tests seem to behave differently on Mojave vs Sierra. On Sierra chain building fails in signing, while in Mojave signing succeeds but then verification fails with the OCSP server issues.
The chain building issues in Sierra seem similar to the issues in the 18 other tests that don't repro in Mojave, so they might be related.

The tests have been disabled on CI and need to be fixed and re-enabled.

**Comment by zkat** [comment]
This PR may have to do with this: https://github.com/NuGet/NuGet.Client/pull/3003

**Comment by heng-liu** [comment]
Get the list of the 4 disabled tests from a [commit](https://github.com/NuGet/NuGet.Client/commit/a4797e1dc198103e47b4c5172b150c589a633250) in PR:  [NuGet/NuGet.Client#3003](https://github.com/NuGet/NuGet.Client/pull/3003)
In test/NuGet.Core.Tests/NuGet.Packaging.Test/SigningTests/CertificateChainUtilityTests.cs,
  GetCertificateChain_WithUntrustedRoot_Throws
  GetCertificateChain_WithUntrustedSelfIssuedCertificate_ReturnsChain
In test/NuGet.Core.Tests/NuGet.Packaging.Test/SigningTests/SigningUtilityTests.cs
  Verify_WhenChainBuildingFails_Throws
  Verify_WithUntrustedSelfSignedCertificate_Succeeds

**Comment by heng-liu** [comment]
Need to enable the 4 tests on Mac.

**Comment by heng-liu** [comment]
Closed as fixed.
