### ISSUE TITLE
[Centrally managing NuGet packages and versions] Close on the Visual Studio UI CPVM user scenarios

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9017]
This work will consist from:
1. Work with PM and UX teams to agree on the final design for UI regarding CPVM.
2. Review the UI design doc with Partners (msbuild, dotnet teams)
3. Reiterate until everyone in sync.

**Comment by aortiz-msft** [comment]
Bulk-closing old issues for CPVM.
