### ISSUE TITLE
VS extension operates on project.json even when csproj is open

### ISSUE THREAD

**Issue by roji** [NuGet/Home#902]
Many projects have dual build system - the classical csproj-based one and the new DNX one. It seems like as soon as there's a project.json in a project's directory, the nuget VS extension automatically operates on the project.json, this makes it difficult to work with dual-build projects.

It seems like if Visual Studio is open on a csproj then the csproj "mode" should be used regardless of whether a project.json exists or not in the directory.

VS2015RC, nuget 3.0.60602.486

**Comment by davidfowl** [comment]
@roji Why do you have them in the same folder (curious)?

**Comment by roji** [comment]
I guess there are several reasons - DNX is a bit new and things are sometimes quirky, so it's good to be able to fall back to "rock-solid" csproj builds. Lots of third-party products don't support DNX yet (e.g. Resharper unit test runner), but on the other hand if I want to experiment with CoreCLR I need DNX (right?).

By the way, the idea came to me from the EntityFramework 7 team, which does exactly this - each project dir has a csproj, a project.json and an xproj. There's a EntityFramework.sln referencing the csproj files, and an EntityFramework-dnx.sln referencing the xproj files.

**Comment by yishaigalatzer** [comment]
This is by design, see issue #797. Once we release 3.1 (shortly after RTM) you will be able to work with CoreCLR with regular projects.
