### ISSUE TITLE
Remove workaround of installing SDK version for building and global.json

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9030]
We now have a workaround to install SDK 5.0 for each CI machine.
We need to remove this workaround and use the SDK installed on CI machine.

We should also remove the global.json file from our solution.

**Comment by kartheekp-ms** [comment]
Moving this issue to backlog as per https://github.com/NuGet/Home/issues/9029#issuecomment-616680544. This workaround can't be removed from the package signing branch until `net5` is released to GA so that it can be installed on the CI agents. //cc @zkat @heng-liu

**Comment by zkat** [comment]
Moving this out of this epic and into the toplevel epic instead.

**Comment by nkolev92** [comment]
Closing. This has long been fixed.
