### ISSUE TITLE
dotnet pack --ouput directory no longer relative to current directory

### ISSUE THREAD

**Issue by wli3** [NuGet/Home#9034]
_From @frankkilcommins on Tuesday, November 12, 2019 10:30:50 AM_

As of yesterday, I get issues with dotnet pack where the output directory was created at the root working directory rather than relative to the current directory. This caused subsequent pack command to fail as the expected pattern was no longer matching.

sdk version: 2.1.500

Output:
`[command]C:\hostedtoolcache\windows\dncs\2.1.500\x64\dotnet.exe pack d:\a\1\s\DUPSCore\DigitalUserProvisioningService.Data.Core\DigitalUserProvisioningService.Data.Core.csproj --configuration release --version-suffix 96713 --output nupkgs
Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.`

Package was created in the following directory:
`Successfully created package 'd:\a\1\s\nupkgs\DigitalUserProvisioningService.Data.Core.1.3.0-ci-96713.nupkg'.`

Expected directory:
`d:\a\1\s\DUPSCore\DigitalUserProvisioningService.Data.Core\nupkgs\DigitalUserProvisioningService.Data.Core.1.3.0-ci-96713.nupkg`

I've worked around the issue by prefixing the _current_ directory to the `output` command:
`--configuration $(BuildConfiguration) --version-suffix $(Build.BuildId) --output DUPSCore/DigitalUserProvisioningService.Data.Core/nupkgs`

Just wondering why/when this changed and can I expect my builds to break again if/when it's reverted or resolved.

_Copied from original issue: dotnet/sdk#3894_

**Comment by wli3** [comment]
_From @bruno-brant on Tuesday, December 3, 2019 2:12:02 AM_

I'm getting the same behavior. SDK version is `2.2.108`.

**Comment by frankkilcommins** [comment]
@wli3 Today related to other issues, I switched to use version 2 of task `Use .NET Core` to installing .net core sdk version and the dotnet pack tasks started outputting to the relative paths correctly. Not sure if related but seems to consistently impact if I switch to and from `Use .NET Core` v0.* and v2 task versions

**Comment by frankkilcommins** [comment]
This issue reoccurred yesterday for us using v2.* of the dotnet pack task, so again had to apply the workaround I described in the initial issue registration

**Comment by nkolev92** [comment]
@frankkilcommins 

From which directory are you running dotnet.exe? 
Do you expect the package to be generated relative to working directory?
