### ISSUE TITLE
Building solution with both Core and Standard

### ISSUE THREAD

**Issue by Ynot1234** [NuGet/Home#9038]
I have a solution on MS 2017 with a Core startup project and a 'Standard' class library.   I migrated the package.config references to package references format.  When I try to build it on TFS with .Net Core Build tasks,  the Standard project is not able to locate some of the Top Level NuGet libraries...

_error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?) 
error CS0246: The type or namespace name 'Dapper' could not be found (are you missing a using directive or an assembly reference?) 
error CS0234: The type or namespace name 'Extensions' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) 
error CS0246: The type or namespace name 'JObject' could not be found (are you missing a using directive or an assembly reference?) 
error CS0246: The type or namespace name 'JToken' could not be found (are you missing a using directive or an assembly reference?)_

The application works locally (using these libraries) so is it an issue with the Core Build Task on TFS?  Can they not process a .Net Standard project?  I should point out that the version of these packages matches in both projects.

**Comment by kartheekp-ms** [comment]
As per this [doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=tfs-2018), Build, test, and deploy .NET Core apps is available from TFS 2017. Please refer to [restore-dependencies](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=tfs-2018#restore-dependencies) and [troubleshooting](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=tfs-2018#troubleshooting) sections in the doc to learn more about restoring nuget packages specified in the .NET Core project .csproj files.

**Comment by nkolev92** [comment]
![image](https://user-images.githubusercontent.com/2878341/78308086-567f8600-74fc-11ea-9737-81e6bf37415c.png)
