### ISSUE TITLE
SkipDuplicate option is ignored in symbol packages

### ISSUE THREAD

**Issue by diogorolo** [NuGet/Home#9039]
# Details about Problem

NuGet product used: dotnet.exe

NuGet version: 4.7.0.5148

dotnet.exe --version (if appropriate): 3.1.100

OS version (i.e. win10 v1607 (14393.321)): win10 v1903 18362.535

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem
Example command: dotnet nuget push dummy.nupkg --skip-duplicate -k my_key -s https://mysource.c/api/v2/package -ss https://mysymbolsource.c/symbols/api/v2/package -sk my_symbol_key

1. Push a package with symbols to a server that does not allow package overwritting

2. Push again the same packages with symbols

## Other Info
https://github.com/NuGet/NuGet.Client/blob/1f7820743cc143b675e3f195e77357feea2e8910/src/NuGet.Core/NuGet.Protocol/Resources/PackageUpdateResource.cs#L184

Here we can see that the variable SkipDuplicate is being force set to false.

### Verbose Logs

C:\dir>dotnet nuget push dummy.nupkg --skip-duplicate -k my_key -s https://mysource.c/api/v2/package -ss https://mysymbolsource.c/symbols/api/v2/package -sk my_symbol_key
info : Pushing dummy.nupkg to 'https://mysource.c/api/v2/package'...
info :   PUT  https://mysource.c/api/v2/package 
info :   Created  https://mysource.c/api/v2/package  1084ms
info : Your package was pushed.
info : Pushing dummy.symbols.nupkg to 'https://mysymbolsource.c/symbols/api/v2/package'...
info :   PUT https://mysymbolsource.c/symbols/api/v2/package/
info :   Created https://mysymbolsource.c/symbols/api/v2/package/ 785ms
info : Your package was pushed.

C:\dir>dotnet nuget push dummy.nupkg --skip-duplicate -k my_key -s https://mysource.c/api/v2/package -ss https://mysymbolsource.c/symbols/api/v2/package -sk my_symbol_key
info : Pushing dummy.nupkg to 'https://mysource.c/api/v2/package'...
info :   PUT  https://mysource.c/api/v2/package 
info :   Conflict  https://mysource.c/api/v2/package  443ms
log  : Package 'dummy.nupkg' already exists at feed 'https://mysource.c/api/v2/package'.
info : Pushing dummy.symbols.nupkg to 'https://mysymbolsource.c/symbols/api/v2/package'...
info :   PUT https://mysymbolsource.c/symbols/api/v2/package/
info :   Conflict https://mysymbolsource.c/symbols/api/v2/package/ 97ms
info : To skip already published packages, use the option --skip-duplicate
error: Response status code does not indicate success: 409 (The package could not be uploaded. The package "dummy" already exists. Overwriting existing packages is forbidden according to the package retention settings for this feed.).

As you can see, it fails the second time, even with the  --skip-duplicate option. In the error it suggests using the same option that's already in use.

**Comment by nkolev92** [comment]
Hey @diogorolo, 

Thanks for creating this issue. 
Apologies for the overdue response, this slipped through the cracks. 

There's a newer issue detailing the problem you are hitting, please refer to https://github.com/NuGet/Home/issues/9647.
