### ISSUE TITLE
project.json and AnyCPU Classic Desktop projects

### ISSUE THREAD

**Issue by bricelam** [NuGet/Home#904]
I was playing around with the Microsoft.Data.Sqlite package after this pull request: aspnet/Microsoft.Data.Sqlite#100

The nupkg looks something like tihs:
* Microsoft.Data.Sqlite
  * lib
    * dotnet
      * Microsoft.Data.Sqlite.dll
  * runtimes
    * win
      * native
        * x86
          * sqlite3.dll
        * x64
          * sqlite3.dll
    * (other RIDs)

I was trying to consume the package in a Full .NET AnyCPU project. (e.g. a WPF, WinForms, or Console app)

In theory, both the `x86` and `x64` directories (i.e. everything under `runtimes/win/native`) should be copied to the bin folder. The managed library could then call `LoadLibrary(Path.Combine(bin, arch, "sqlite3.dll"));` to load the appropriate library. Unfortunately, **the directory structure isn't preserved**. Both dlls are copied directly into the `bin` folder--one over top of the other.

I created a new Console app, added a `project.json`, and tried to install the package, but it gave the following error. It looks like instead of just using `win` for AnyCPU projects, it's trying to use `win-anycpu`.

 > C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(76,5): error : Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.6/win-anycpu mentioned in your targets.

I was able to resolve this using the following `project.json` file.

```JSON
{
  "frameworks": {
    "net46": { }
  },
  "runtimes": {
    "win": { },
    "win-anycpu": {
      "#import": [ "win" ]
    }
  },
  "dependencies": {
    "Microsoft.Data.Sqlite": "1.0.0-*"
  }
}
```

/cc @rowanmiller @divega

**Comment by bricelam** [comment]
The error looks like it's on line 130 of `Microsoft.NuGet.targets`:
```XML
<_NuGetRuntimeIdentifierWithoutAot>$(BaseNuGetRuntimeIdentifier)-$(PlatformTarget.ToLower())</_NuGetRuntimeIdentifierWithoutAot>
```

It shouldn't append `-$(PlatformTarget)` if `PlatformTarget` equals `AnyCPU`.

**Comment by bricelam** [comment]
Never mind. I updated that code, but got the same error:
> Make sure you have .NETFramework,Version=v4.6/win mentioned in your targets.

**Comment by bricelam** [comment]
Looks like the issue is larger than just AnyCPU; I updated the target platform to x86, and still get the error.
> Make sure you have .NETFramework,Version=v4.6/win-x86 mentioned in your targets.

**Comment by bricelam** [comment]
Is `project.json` supposed to work on Full .NET yet, or just `packages.config`?

**Comment by bricelam** [comment]
Got further. Adding the following to my `project.json` enables the package to install, build, and copy native artifacts.
```JSON
{
  "runtimes": {
    "win": { },
    "win-anycpu": {
      "#import": [ "win" ]
    }
  }
}
```

Unfortunately, the directory structure under `runtimes/win/native` isn't preserved so one `sqlite3.dll` file is copied on top of the other one.

**Comment by jasonmalinowski** [comment]
I updated the targets a few weeks ago in internal builds to do as you're describing. @yishaigalatzer, should this bug be closed? @bricelam, the changes are in current Update 1 builds internally if you want to try it.

**Comment by bricelam** [comment]
@jasonmalinowski it looks like it's correctly using the `win`directory now, but the directory structure under `native` still isn't being preserved. But maybe that's not how this feature was designed to be used anyway...

**Comment by bricelam** [comment]
The biggest oversight in the design that I see is that AnyCPU applications (not libraries) like Full .NET Console, WinForms, and WPF apps don't know the architecture until runtime (not at build-time).

/cc @ericstj

**Comment by bricelam** [comment]
BTW, in aspnet/Microsoft.Data.Sqlite#170 we've moved to a primarily MSBuild-based package in order to workaround this and an inability to differentiate between Win32 and WinRT libraries in a way that's compatible with DNX.

**Comment by yishaigalatzer** [comment]
Some of these can be now directly solved by using the content model

Sent from my Windows Phone

**Comment by jasonmalinowski** [comment]
@bricelam I think non-preservation of the directory structure is by design. @yishaigalatzer can you confirm?

**Comment by yishaigalatzer** [comment]
There is support in content to preserve structure

**Comment by davidfowl** [comment]
Yea this is still a fail for any CPUs in general. We need a corefx API for loading from that structure

**Comment by yishaigalatzer** [comment]
@bricelam I think NuGet now provides full support for laying out whatever you'd like on disk, and there is no further NuGet work here.

If someone disagrees feel free to re-open

**Comment by dotMorten** [comment]
@yishaigalatzer When you say "NuGet now provides full support for laying out whatever you'd like on disk" are you referring to the 'contentFiles' feature? Because that currently flattens the folder structure.
