### ISSUE TITLE
[Localization][CHS][CHT] String “By” should be translated to “作者:”

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#9045]
## Details about Problem
VS Version: D16.5\29708.193
OS Version: windows-10-enterprise-rs4-zh-cn
## Installation
1. Install a clean machine with OS: windows-10-enterprise-rs4-zh-cn
2. Install VS D16.5\29708.193: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3369922&view=results CHS/CHT
## Detailed repro steps 
1. Open Visual Studio 2019 preview.
2. Create a new Console App (.Net Core) project.
3. Right-click the project and open PM UI in Solution Explorer window.
4. Observe the translation of the author of the package (e.g. Newtonsoft.Json).
## Expected
String “by” should be translated to “作者:”.
## Actual
String “by” was translated to “由”/”依”, making the sentence incomplete as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/72142175-11e9c000-33cf-11ea-9741-c79269bd62bf.png)
![image](https://user-images.githubusercontent.com/40230425/72317361-faaf1900-36d3-11ea-98d0-4e48b9401031.png)

**Comment by v-luzh** [comment]
Note: This issue is not a regression.

**Comment by zivkan** [comment]
@dominoFire how do we report this to the loc team?

**Comment by janbaltus** [comment]
@lukaschal please review with LM translation for 
by {0}
0; "Text_ByAuthor"

**Comment by lukaschal** [comment]
Translated as "作者 {0}" on CHT and CHS.

**Comment by janbaltus** [comment]
PR with fix
https://github.com/NuGet/NuGet.Build.Localization/pull/581/files
https://github.com/NuGet/NuGet.Build.Localization/pull/582/files

**Comment by v-longmin** [comment]
Verify the issue on D16.6\30023.158 with Implicit NuGet Client Dev\5.6.0.6558, it has been fixed, close it, thanks.
