### ISSUE TITLE
Issues posted here with over 100 positive reactions and supporting comments are being ignored

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#9047]
Community feedback regarding a problem or feature isnt going to get much louder than that.  Why is the Nuget team not listening?

**Comment by rrelyea** [comment]
@StingyJack  - thanks for the feedback. We are trying to get to the top voted issues. We hope to be able to analyze and do them or close them as soon as we can. We continue to try to become more efficient in our work, but it is a constant battle.

**Comment by rrelyea** [comment]
@aortiz-msft  @anangaur - fyi - in our prioritization
