### ISSUE TITLE
Visual Studio 2017 Package Restore Fails If Build Forced "Too Early" (Race Condition?)

### ISSUE THREAD

**Issue by aolszowka** [NuGet/Home#9049]
## Details about Problem

NuGet product used: VS UI

VS version: Visual Studio 2017 15.9.14

OS version: Windows Server 2012 R2

## Detailed repro steps so we can see the same problem

In some scenarios not quite understood yet it appears that NuGet will fail to load properly in Visual Studio. Our best guess is this happens when loading larger solutions (anything with more than 50 projects, with more projects being more likely to occur).

When this happens opening up Package Manager Console in this manner and then rebuilding allows NuGet to restore the packages.

![FixNuGetInitalizationError](https://user-images.githubusercontent.com/2592881/72189833-2459fe80-33bb-11ea-8b3f-a84fb9c2cf26.gif)

## Other suggested things
Searching the open and closed issues for anything about race conditions shows some promising items; the closest that seems related might be https://github.com/NuGet/Home/issues/8881 but it is unclear.

Is there any logs we can grab to help troubleshoot this when we do see it occur? For now we apply the work around and that always seems to work.

**Comment by rrelyea** [comment]
The fix of #8881 will be shipping in VS 2019 16.5 preview 3. Please let us know if that doesn't address your issue.
We continue to improve the product, but only plan to fix security issues in VS 2017 15.9.x.

**Comment by aolszowka** [comment]
Is Preview 3 Available yet? on a fresh VM all I appear to be able to get is Preview 2?

**Comment by rrelyea** [comment]
Updated my comment to say “will be shipping” instead of “is shipping”

Wouldn’t hurt to see if you see improved behavior with preview 2

**Comment by aolszowka** [comment]
In testing with Preview 2 I do not seem to experience the issue, but this maybe because the option to "build" is disabled until much later in the process. Regardless, this is closed as resolved.
