### ISSUE TITLE
Feature request: support content packages

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#905]
I'm writing this feature request so we can track it for future releases...

"Content packages" have been used successfully as a way for nuget authors to write packages that work on all platforms without them having to worry about multiple platform directories or dependencies or anything. The most prominent one is "sqlite-net". Another is "TinyIOC". I'll update this with other prominent examples as I encounter them. 

(If we came up with a solution which allowed content, but was different for NuGet2 vs NuGet3, then that'd more or less defeat the use-case by forcing package authors to update their packages anyway...)

**Comment by yishaigalatzer** [comment]
Duplicate

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/627
