### ISSUE TITLE
Feature request: better message if package ID already exists

### ISSUE THREAD

**Issue by gsscoder** [NuGet/Home#9053]
If *package ID* exists I get:
```
info : Push di Tagger.1.0.5.nupkg in 'https://www.nuget.org/api/v2/package'...
info :   PUT https://www.nuget.org/api/v2/package/
info :   Forbidden https://www.nuget.org/api/v2/package/ 1398 ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
```
I discovered it using the web gallery instead of command line.

A meaningful message after this kind of fail for `dotnet pack` will be very useful!

Thank you for **excellent job**.

**Comment by karann-msft** [comment]
dotnet pack cannot predict what source you plan to push a package to. Are you saying you don't get the same error on dotnet nuget push?

**Comment by gsscoder** [comment]
Yes, exactly. **NuGet** gallery spotted the problem. When pushing using the command line, `dotnet nuget push` complained about **API Key** (saying it's expired or incorrect).

**Comment by karann-msft** [comment]
"or does not have permission to access the specified package." which is kinda the case here.

**Comment by gsscoder** [comment]
Ok.
It was just to let you know if it's the case to change something, but after all I think it's not a real problem.
Thank you
