### ISSUE TITLE
Github doesn't parse SDK style projects for packages. Required nuspec

### ISSUE THREAD

**Issue by Petermarcu** [NuGet/Home#9057]
Haven't found a good way to report this to github yet but figured you might want to know and push on it. https://github.community/t5/How-to-use-Git-and-GitHub/Used-by-counter-not-showing-the-packages/m-p/39425#M9620

People using SDK Style projects aren't able to use some of githubs features for referencing packages because of this.

**Comment by rrelyea** [comment]
@anangaur - can you help start this conversation? (might have already started that recently, in fact)

**Comment by anangaur** [comment]
@Petermarcu which GitHub features? I do see my dependencies listed for the `Dependency graph`

![image](https://user-images.githubusercontent.com/14800916/73219328-b9295f80-4110-11ea-9f11-1ed560a3ccf9.png)

**Comment by Petermarcu** [comment]
@weshaggard was looking into this more. It was specifically about the "Used By" button at the top of a repo and how you can control which package it gives you. Wes has been digging more and trying to understand why our projects that use SDK style projects are not showing up in that list of possible packages so we can repoint people at one of the more popular ones.

This is the repo we are looking at https://github.com/Azure/azure-sdk-for-net

**Comment by anangaur** [comment]
This is the first time I noticed the `Used by` feature 😄. Do you know why it picked up `Microsoft.Azure.Batch`? What are other packages you would like to show here? 

![image](https://user-images.githubusercontent.com/14800916/73332654-3ee60180-421c-11ea-9673-70ecda5bc882.png)

**Comment by Petermarcu** [comment]
What we want to have there is Azure.Storage.Blobs because its the most popular service and the version of the library we want people to use. We're trying to figure out why that library doesn't show up in the list even though its delivered from our repo.

**Comment by anangaur** [comment]
@Petermarcu  Looks like you figured out how to show `Azure.Storage.Blobs`.  Can you let me know how was this done and if we still need this issue? 
![image](https://user-images.githubusercontent.com/14800916/74056196-61071e80-4996-11ea-84be-7e91224471be.png)

**Comment by weshaggard** [comment]
This was fixed by the github folks by re-associating the Azure.Storage.Blobs package with our repo. I forwarded you some context with our conversation with them.

**Comment by nkolev92** [comment]
@anangaur marking this as external so it doesn't show up in our triaging as there's no engineering actionables for this at this point.

**Comment by anangaur** [comment]
Seems like the GitHub team is internally tracking this issue.  Seems like related issue has been marked solved here: https://github.community/t5/How-to-use-Git-and-GitHub/Used-by-counter-not-showing-main-project/td-p/37688

I think we should be able to close this issue as its external.

**Comment by nkolev92** [comment]
Sounds good. 
Thanks @anangaur
