### ISSUE TITLE
Specify Icon file outside of project directory

### ISSUE THREAD

**Issue by josh-degraw** [NuGet/Home#9060]
I am in the process of updating the `<PackageIconUrl>` tags to use `<PackageIcon>` instead, and I ran into an issue that I assume others may have.

Basically, I have multiple `.csproj`s in my solution, and many get packaged into libraries to be consumed. So far, I have applied the package icons in such cases by putting the line in my `Directory.Build.props` file and having it cascade and apply to all packages in my solution.

What I want to be able to do is have just one icon file at the root or in an `Img` file or something, and be able to specify in my `Directory.Build.props` file something like the following:

```xml
<PropertyGroup>
  <PackageIcon>Properties\icon.png</PackageIcon>
</PropertyGroup>

<ItemGroup>
  <Content Include="$(SolutionDir)\icon.png" Link="Properties\icon.png">
    <Pack>True</Pack>
    <PackagePath></PackagePath>
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </Content>
</ItemGroup>
```

If there is a way to do this already, I would love to know how to get it to work.

**Comment by rrelyea** [comment]
@karann-msft @dominoFire  - good question. Perhaps we could give the solution, if possible, and consider updating the docs.

**Comment by dominoFire** [comment]
@josh-degraw  Suppose that we have the following folder structure with projects in SDK-style format:

```
C:\path\to\SolutionSample
|
│   Directory.Build.props
│   myIcon.png
│   SolutionSample.sln
│   
├───ClassLib1
│      Class1.cs
│      ClassLib1.csproj
│
├───ClassLib2
│       Class2.cs
│       ClassLib2.csproj
│
└───ClassLib3
        Class3.cs
        ClassLib3.csproj
```

Now, in your `Directory.Build.props` file, you have:

```xml
<Project>
  <PropertyGroup>
    <PackageIcon>myIcon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)\myIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
```

Then, create the packages in the terminal by using `dotnet`. For example:

```shell
> cd C:\path\to\SolutionSample
> dotnet pack
```

The command above will create the three packages (ClassLib 1, 2, 3)  and each package will have the same embedded icon specified in the `Directory.Build.props` file.

**Comment by josh-degraw** [comment]
@dominoFire Thanks for that, looks like that accomplished this. 

One further question though, since this method shows the icon file at the project root, if I wanted to show it in the Solution Explorer tree under the `Properties` folder, for example, would that be possible? Or would it it only work at the top level? 

I tried restructuring the example you gave here to do that but it didn't seem to work. It's not a critical issue, just nice IMO to avoid clutter at the top level of my projects.
