### ISSUE TITLE
The <AdditionalIncludeDirectories/> in xx.props is not effective when <AdditionalIncludeDirectories/> in project is empty.

### ISSUE THREAD

**Issue by EastGaint** [NuGet/Home#9064]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 4.9.2.5706

dotnet.exe --version (if appropriate): 2.1.509

VS version (if appropriate): 4.8.03752(VS2017)

OS version (i.e. win10 v1607 (14393.321)): win10 v1903 (18362.535)

## Detailed repro steps so we can see the same problem

1.

```I have packed a native NuGet package with a .props file like follows:
<ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <ClCompile>
            <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)..\..\lib\native\ImageProcessLibrary\include\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
        </ClCompile>
        <Link>
            <AdditionalLibraryDirectories>$(MSBuildThisFileDirectory)..\..\lib\native\ImageProcessLibrary\lib\x64\;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
            <AdditionalDependencies>ImageProcessLibrary.lib;%(AdditionalDependencies)</AdditionalDependencies>
        </Link>
    </ItemDefinitionGroup>
2. I have new a application and add empty Additional Include Directories statement like follows:
<AdditionalIncludeDirectories></AdditionalIncludeDirectories>
3. Then install this package.
4. The .props file is imported into .vcxproj, but I can't directly include the header file I putted in NuGet.
```

**Comment by EastGaint** [comment]
```code for 2 step "<AdditionalIncludeDirectories></AdditionalIncludeDirectories>"```

**Comment by EastGaint** [comment]
IE is terrible, I can't add code into. I think you can know what I say.

**Comment by rrelyea** [comment]
You need to escape any XML content in a markup based system like GitHub.  I use three ` before the xml content, and three after.

**Comment by nkolev92** [comment]
@EastGaint 

> 4. The .props file is imported into .vcxproj, but I can't directly include the header file I putted in NuGet.

Based on that sentence, NuGet is working as expected in this scenario.
Unfortunately we don't have the right expertise with vcxproj to understand why you can't use the header in your project. 

We'd like to recommend you file this issue at https://developercommunity.visualstudio.com/ to get in contact with the C++ team.
