### ISSUE TITLE
Missing Full path on linked content

### ISSUE THREAD

**Issue by LorenDorez** [NuGet/Home#9066]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS SDK package builder

NuGet version (x.x.x.xxx): 5.4

dotnet.exe --version (if appropriate): 3.1.101

VS version (if appropriate): 2019 16.4.3

OS version (i.e. win10 v1607 (14393.321)): windows 10

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create 2 projects

2. Add a linked file (Must be bested in folder) reference from A to B

3. Build B the generated nuget spec removed the folder path for the linked file and just uses the filename.

...

**Comment by rrelyea** [comment]
I'm unsure how to reproduce this problem.
How do I find the "VS SDK package builder"?
What types of projects should i create?
How do I create a linked file?

Need more details in order to understand the steps you are having a problem with.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
