### ISSUE TITLE
How to setup NuGet (feed source and credentials) in CI/CD pipeline?

### ISSUE THREAD

**Issue by buddhashrestha** [NuGet/Home#9068]
Remove the content above here and fill out details below.

## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 5.3.1.6268

VS version (if appropriate): 2017

OS version (i.e. win10 v1607 (14393.321)): win10

Worked before? If so, with which NuGet version: No

I setup NuGet (feed source and credentials) in my local via Visual Studio UI. I don't have a NuGet.config in my repo. Now, if I want to build the code in CI/CD, then how should I do it? Because I don't have the feed source and credentials information in my repo, the CI/CD server also doesn't have that information yet. 

Also, I want to set it up such that I could change the package source from my local which would be reflected in during the CI build.

Each of my team members has their own credentials and they can set up their own feed source and credentials in local from Visual Studio.

I just want to know the best practice to create a build pipeline such that the packagesource information is controlled by developers and package credentials is managed by the CI server, which uses some default credentials.

**Comment by rrelyea** [comment]
Best practice is to create feed configuration in a nuget.config in your repo.
credentials can then be added as per-user nuget.config files.

**Comment by buddhashrestha** [comment]
Thanks!
