### ISSUE TITLE
It's slow to list avaiable packages in Visual Studio with large shared folder

### ISSUE THREAD

**Issue by ydmztang** [NuGet/Home#907]
We have a shared folder which contains 30,000 files. And the manage packages dialog takes forever to list the packages (actually waited for 5 mins). It would be nice to dynamically load the packages page by page.

**Comment by yishaigalatzer** [comment]
This is a scenario that was never supported. We don't recommend going over a few 10s of packages to low 100s. If you are in this mode please set up a local nuget server.
