### ISSUE TITLE
Visual Studio 2017 Enterprise crashes at least twice per hour

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9070]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/437369/visual-studio-2017-enterprise-crashes-at-least-twi.html)._

---
I've had this problem on different computers and projects going back to my first use of Visual Studio in 2010.<br>This is not a computer or project specific issue, but is clearly specific to Visual Studio from the 2010 version to the latest I'm using which is 2017 Enterprise.<br>I have no extensions or addons installed.<br>The symptoms start with Visual Studio occasionally hanging or the intellisense ceasing to work for several seconds.<br>Also project references such as &quot;C++ 2015 runtime for UWP&quot; or the &quot;Microsoft Advertising SDK for XAML&quot; occasionally show yellow triangles against them as though they are no longer recognised.  I then have to right click on either item in references for Visual Studio to start recognising them again.<br>These symptoms preceed a general deterioration of Visual Studio performance which either results in it crashing completely and restarting automatically or hanging indefinately where I then have to use Task Manager to end the Visual Studio task.  Noticably recovery of files currently being editing rarely works to the point of previous editing.<br>This catastrophic failure of Visual Studio occurs at least twice per hour when I'm on a sprint, which usually means I lose 30 minutes or so work at most, however it is one of the reasons why I'm actively considering moving to another IDE such as Eclipse, Rider or MonoDevelop for my future development projects.

---
#### Alisa Ma [MSFT] on 1/29/2019, 00:56 AM: 

<p>Dear Customer,</p><p>Thanks for your feedback! In order to help us investigate this issue more accurately, could you please provide a repro projects,and a dump.</p><p>You are able to get the files with the following steps:</p><p>- Download ProcDump from <a target="_blank"> https://docs.microsoft.com/en-us/sysinternals/downloads/procdump  </a>and extract to a local folder.</p><p>- Open an Administrator Command Prompt and navigate to ProcDump folder.</p><p>- Run Procdump.exe -w devenv.exe -e 1 -n 1000 -f *ArgumentException* -ma &gt; out.txt</p><p>- Launch Visual Studio and reproduce the error.</p><p>- Close Visual Studio</p><p>- ProcDump should generate some DMP files in the local directory if the exception is thrown</p><p>- Please zip the DMP file, reply to this thread and attach them using the attach / insert button</p><p>We look forward to hearing from you!</p><p>Thanks.</p>

#### pythonesquespam on 2/18/2019, 05:12 PM: 

<p>Tried to upload last three dmp files but the upload window does nothing when I click the upload button.  The dump files are 1 Gig when zipped so perhaps such large files aren't allowed??  I uploaded a zipped out.txt file if that's any use to you.  <a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/59933-out.zip">out.zip</a></p>

#### Alisa Ma [MSFT] on 2/18/2019, 11:08 PM: 

<p>Dear Customer,</p><p>Thanks for your reply! We need to this dump file and compress it then attached to us. </p><p>And Dick add a solution for this issue as below, if your issue is the as him, maybe you can reference it.</p><p>Thanks.</p>

#### pythonesquespam on 2/23/2019, 07:50 AM: 

(private comment, text removed)
#### pythonesquespam on 2/23/2019, 08:49 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 7/9/2019, 11:58 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
#### Dick solved on 1/28/2019, 03:00 AM, 0 votes: 

<p>Hello Andrew,<br><br>This looks like the problem I had in July 2018 when I installed VS 2017 because VS 2015 did no longer support UWP apps in combination with my W10 version. It took me 1,5 day to get it working. If you read the comments to my original post on<br><br><a target='_blank' href="https://developercommunity.visualstudio.com/content/problem/288722/visual-studio-2017-does-not-install-due-to-access.html" target="_blank">https://developercommunity.visualstudio.com/content/problem/288722/visual-studio-2017-does-not-install-due-to-access.html</a> it may help you as well.<br><br>VS installers are an absolute disaster. I won't install VS 2019 except forced and I don't even install updates for VS 2017. For almost any other software on my Pc I regularly update and it hardly ever takes more than a few minutes.</p><p>Dick</p>

#### pythonesquespam solved on 3/4/2019, 05:55 PM, 0 votes: 

<p>I've been battling with Visual Studio since I first started using it at college in 2010.  This issue is just one of many aspects of Microsoft technologies that simply get in the way of development. I find that most of my development effort is about trying to get the technologies to even work, rather than producing the software and that's just not the best use of my time. XAML is full of inconsistencies especially with Binding and the Advert and Store SDK's don't work with anything but the simplest examples. Even testing the Store SDK is no longer possible with the latest version as it uses the live store as it's basis... ridiculous.  So I've decided my next project will use other technologies and I can get away from this awful mess that is Microsoft!</p>

**Comment by rrelyea** [comment]
Can you please determine if this is a crash we've seen in 15.x and 16.x? How prevalent? Did we fix?

**Comment by zivkan** [comment]
Set developer community feedback status to "need more info".

The feedback currently has two crash dumps attached. One was not taken during an exception. The UI thread was rendering, so despite being in `ntdll.dll`'s `WaitForMultipleObjects`, it's probably waiting for the video driver. I didn't see evidence of a UI hang. The other memory dump was taken during a first change exception that was in a try-catch block, so would not cause VS to crash.

I'm unable to determine any problems at this time, and provided a link on [how to record problems with the VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#record-a-repro) in the developer community feedback.
