### ISSUE TITLE
nuget restore succeed but project .net don't have content css and js

### ISSUE THREAD

**Issue by osmodies** [NuGet/Home#9071]
Hi,

From Azure Pipeline restore package succeed, but the content (css,js ,img) of package is not added in Web application .net
![image](https://user-images.githubusercontent.com/19317872/72630201-dc3d5d80-391f-11ea-8d29-f2744282a8b9.png)

But, Build application faild 
![image](https://user-images.githubusercontent.com/19317872/72630022-79e45d00-391f-11ea-8356-4f8a1be39db2.png)

In the case of Visual Studio i must install package again.

Thanks if your help.

**Comment by karann-msft** [comment]
@osmodies - note that the Docs repo is for reporting Docs related issues Going forward, use the Home repo for product-related issues.

Please use the following template to help us understand your issues better.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by rrelyea** [comment]
Very similar to #9073 - see comments there.

**Comment by osmodies** [comment]
Very similar to #9073
