### ISSUE TITLE
Icon missing after package install in VS PM UI

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#9072]
## Details about Problem

NuGet product used: VS UI

NuGet version: 39963d7775d6ba22e2e5c1373a7cb027ce9bdaa7

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

0. Specify a NuGet source with a local folder. The packages must have embedded icons. Add it to nuget.config ($APPDATA\NuGet\NuGet.Config)
1. Open VS, with any project and open NuGet (Manage NuGet packages...)
2. Install a package with an embedded Icon
3. Go to the Installed Tab

**Comment by rrelyea** [comment]
Very similar to #9073
