### ISSUE TITLE
Cleanup redundant code in the VS extensibility services

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9074]
As part of the new extensibility work, I've discovered some dead/redundant code. 

This issue is to track the cleanup.

**Comment by heng-liu** [comment]
Reopen it as there's a regression scenario to consider. Related issue: https://github.com/NuGet/Home/issues/9129

**Comment by heng-liu** [comment]
Reopen it as there's a regression scenario to consider. Related issue: https://github.com/NuGet/Home/issues/9129
