### ISSUE TITLE
Publish/Build/Debug resolves to an old DLL resulting in MissingMethodException

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9080]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/748792/publishbuilddebug-resolves-to-an-old-dll-resulting.html)._

---
[regression] [worked-in:16.2.5]
We have a web application running on .NET Framework 4.6.1 (let's call this project `A`) that has a dependent NuGet package (let's call this `B`). B targets multiple frameworks and includes `C` as a private dependency. `C.dll` is not versioned at the nuget nor assembly level.

Here is what `B.csproj` looks like:

```xml
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461;netcoreapp2.2</TargetFrameworks>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeP2PAssets</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>

<ProjectReference Include="..\C\C.csproj" PrivateAssets="All" />

<Target Name="IncludeP2PAssets">
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)C.dll" />
    </ItemGroup>
  </Target>
```

In the web application project (`A`) we installed `B` using the newer `PackageReference` format even though it's in an older csproj format:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <!-- other old csproj format stuff skipped -->
  <PropertyGroup>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <SkipValidatePackageReferences>true</SkipValidatePackageReferences>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="B" Version="1.0.0.0" />
   </ItemGroup>
</Project>
```
On Visual Studio 16.2.5, all references seem to be resolved correctly (proven by decompiler). The .NET Standard version of `C.dll` is published at runtime.

On Visual Studio 16.3.0, however, the .NET Framework 4.6.1 version of `C.dll` is published at runtime and it is of a very old version, leading to `MissingMethodException`. The strange thing is this doesn't have any compile-time errors, only runtime errors.

Can you please fix this behavior change from 16.2.5 to 16.3.0?

---
#### Visual Studio Feedback System on 9/26/2019, 00:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 9/26/2019, 10:49 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by zivkan** [comment]
More information was asked for on Developer Community. The feedback was closed there due to no response, so closing here as well.
