### ISSUE TITLE
NuGet.Protocol does not support getting a version's download count from search

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/Home#9086]
## Details about Problem

NuGet product used: NuGet.Protocol
NuGet version: 5.5.0-preview.1.6319

## Detailed repro steps so we can see the same problem

The NuGet Search API returns the download count for each individual version of a package through the `downloads` property in the `versions` array (see [this documentation](https://docs.microsoft.com/en-us/nuget/api/search-query-service-resource#search-result)). For example, see: https://azuresearch-usnc.nuget.org/query?q=packageid:newtonsoft.json&prerelease=true&semVerLevel=2.0.0

The NuGet.Protocol library has a [`PackageSearchMetadata.GetVersionsAsync()`](https://github.com/NuGet/NuGet.Client/blob/9173d9bc53b5123d5cadec6cae513149d40505b0/src/NuGet.Core/NuGet.Protocol/Model/PackageSearchMetadata.cs#L197) method that returns `VersionInfo`s, which have a [`DownloadCount`](https://github.com/NuGet/NuGet.Client/blob/9173d9bc53b5123d5cadec6cae513149d40505b0/src/NuGet.Core/NuGet.Protocol/Model/VersionInfo.cs#L34) property. Sadly, this `DownloadCount` property returns the total download count instead of the version's download count. We should expose the version specific download count as well.

### Sample Project

Here's an example project that reproduces this issue: https://gist.github.com/loic-sharma/107210ba996fba598b6fdb5143ed847b

**Comment by loic-sharma** [comment]
In case anyone needs it, I've added a sample project that demonstrates how to do this properly: https://github.com/NuGet/Samples/pull/37

**Comment by campersau** [comment]
I think this is because of this:
> // TODO: in v2, we only have download count for all versions, not per version.
> // To be consistent, in v3, we also use total download count for now.

https://github.com/NuGet/NuGet.Client/blob/e9c22b1c5783edefcd9c5175dc76f99206fa14c8/src/NuGet.Core/NuGet.Protocol/Resources/PackageSearchResourceV3.cs#L37-L53

As a workaround we are using the `RawSearchResourceV3` directly in https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/340
