### ISSUE TITLE
Initial Net5.0 TFM support

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#9089]
Properly support TFM for .NET 5.0.

Spec: https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md

**Comment by dsplaisted** [comment]
Designs PR with details: https://github.com/dotnet/designs/pull/92

**Comment by zkat** [comment]
Reopening this to use as an epic for net5 tfm work.

**Comment by zkat** [comment]
Reopening to use as an epic for net5 tfm-specific work

**Comment by zkat** [comment]
Closing for now for realsies. I moved all the epic issues to be under https://github.com/NuGet/Home/issues/9090 instead :)
