### ISSUE TITLE
null $installPath and VsPackageMetadata.InstallPath in NuGet 3

### ISSUE THREAD

**Issue by bricelam** [NuGet/Home#909]
Trying to get Entity Framework 7's NuGet commands to work in a NuGet 3 project...

We try and get a pacakge's install path using the following code.

```ps1
$componentModel = Get-VSComponentModel
$packageInstaller = $componentModel.GetService([NuGet.VisualStudio.IVsPackageInstallerServices])
$package = $packageInstaller.GetInstalledPackages() |
    where Id -eq EntityFramework.Commands |
    select -First 1
```

Unfortunately, `$package.InstallPath` is always `null`.

Alternatively, I tried getting the install path using `init.ps1` script's `$installPath` parameter, but that too was `null`.

/cc @rowanmiller @divega

**Comment by zhili1208** [comment]
@bricelam I checked this on my machine, InstallPath in those two cases are not null. Can you provide me more details about your case?
