### ISSUE TITLE
Content files not added to project (but copied to it) 

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#9094]
(Moved from: https://github.com/dotnet/project-system/issues/5316 and opened on behalf of @MaceWindu)

**Visual Studio Version**: 16.2.2

**Summary**:
Check 
[OrmTest.csrpoj](https://github.com/dotnet/project-system/files/3511749/OrmTest.txt)
project file from this [issue](https://github.com/linq2db/linq2db/issues/1865). Installing package with content files doesn't work with it properly - files are copied to project folder, but not included into project itself.

I've tried to edit project file by replacing almost everything except project guid with content of new Windows Forms project, but it didn't helped (I suspect it already broke something in solution files at this point).

**Steps to Reproduce**:

1. Open attached project

2. Reinstall linq2db.PostgreSQL nuget package

**Expected Behavior**:
Content files appeared in project under `LinqToDB.Templates` folder

**Actual Behavior**:
Content files appeared in project folder, but not in project

**User Impact**:
Confusion and anxiety

**Comment by nkolev92** [comment]
@MaceWindu 

Thanks for filing this issue.

Can you clarify you expectation, how do you expect them to be appear in your projects?
Screenshots would be very helpful!

Thanks.

**Comment by MaceWindu** [comment]
![image](https://user-images.githubusercontent.com/1099238/84566284-3c6de980-ad70-11ea-98af-7e72892ecf62.png)

- CoreSDK is .net core console project (SDK project)
- FwLEgacy is .net framework console project (legacy project format)
- OrmTest is project from issue

Installing linq2db.postgresql package adds templates (`LinqToDB.Templates`) to first two project properly (as reference or as copy), but doesn't add anything for OrmTest project

**Comment by nkolev92** [comment]
Hey @MaceWindu 

So I looked into the repro. 
The package in question mark all the packages as BuildAction="None" and CopyToOutput=False. 

If you inspect the solution explorer with the new projects, you can see that the content files are wired in. 
If you inspect the solution explorer with old PackageReference projects, they are not displayed. 

If you change the action to Compile, you will see that both projects fail (cause the files it's linking are not compilable). 

As such this is really the same problem as: 
https://github.com/dotnet/project-system/issues/3431, 
https://github.com/dotnet/project-system/issues/3804 (opened by you :) )
https://github.com/dotnet/project-system/issues/3042
