### ISSUE TITLE
Having a (transitive) PackageReference and a ProjectReference to the same assembly leads to an error

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#9095]
(Moved from https://github.com/dotnet/project-system/issues/4663 and opened on behalf of @felixhirt)

I have the following situation (everything with the new .csproj project system):
"Application" has 
   ProjectReference to "LibA"
   ProjectReference to "LibB"
and "LibA" has
   PackageReference to "LibB"

This causes a build error in VisualStudio (2019, RC4) because all the PackageReferences are not found. A manual "dotnet restore" shows that "An item with the same key has already been added. Key: (LibB, X.X.X)"

The error only happens if both versions are the same. If i increment the version of LibB e.g. in the ProjectReference, it works fine (and uses the newer version)

Searching did not yield much for me, i only found [4421](https://github.com/dotnet/project-system/issues/4421) which seems to be similar, but doesnt have much follow up (and no build error, thats why i opened a new issue)

If need be, i can try to create a simple reproduction solution

**Comment by felixhirt** [comment]
Thx for moving this were it belongs. TLDR:
- Preferred solution would be to just use the project reference instead of the package reference from the point it is included onward (transitive). Maybe show a warning to inform people that there might be runtime issues since some projects in the solution use an older version through the nuget
- Alternatively, a clear error message would be nice

**Comment by felixhirt** [comment]
i think my issue is a variation of dotnet/sdk#1151. I guess i could have resolved it by making the package reference explicit and exclude its assets (the lib does not have a strong name)

**Comment by nkolev92** [comment]
Thank you filing this issue. 

@felixhirt The symptoms of the issue you are hitting are tracked in this duplicate issue https://github.com/NuGet/Home/issues/6795

The general ask is capture in  dotnet/sdk#1151 as you have correctly identified.
