### ISSUE TITLE
Test: RestoreNetCore_MultipleProjects_SameToolDifferentVersions_NoOp_FailsAsync is flaky

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9100]
[This assertion](https://github.com/NuGet/NuGet.Client/blob/ac177820b30d328e3c6a4f4a6801b28cc7441a66/test/NuGet.Clients.Tests/NuGet.CommandLine.Test/RestoreNETCoreTest.cs#L1877) is sometimes failing with: 

> 8 needs to be 9 or 10

edit: as per @nkolev92's comment below, this test is redundant and flaky, so is being deleted.

**Comment by nkolev92** [comment]
I'd delete the test tbh. 

I don't see it as super relevant as the other tests kind of ensure this is happening.
