### ISSUE TITLE
Pack library with analyzer

### ISSUE THREAD

**Issue by JohanLarsson** [NuGet/Home#9106]
If we have:

```
Lib.csproj
Lib.Analyzers.csproj
```

And we want to pack so that `Lib.nupkg` has a package dependency on `Lib.Analyzers.nupkg`

An example of the desired result is: [Microsoft.CodeAnalysis.Common](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Common/) that has a dependency on [Microsoft.CodeAnalysis.Analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.Analyzers/)

For anyone familiar with paket it is done like this using paket:

```
dependencies
  Lib.Analyzers
```

In `paket.template`

Is there support for this scenario and if so where is it documented?

**Comment by JohanLarsson** [comment]
https://github.com/dotnet/sdk/issues/3848

**Comment by nkolev92** [comment]
@JohanLarsson 

Are you asking for special analyzers support? That's captured i the following ask: https://github.com/NuGet/Home/issues/6793.

However, if I am interpreting the issue correctly you are asking about dependencies in general, and that's already available through the pack targets.

Refer to docs here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target
