### ISSUE TITLE
Show existing Package Manager UI for VS.Oe

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9110]
Launch PackageManager UI from N.VS.OE.Client.dll codepath.

[1068098](https://devdiv.visualstudio.com/DevDiv/_queries/edit/1068098/?triage=true)

**Comment by rrelyea** [comment]
One challenge I'm hitting currently with this...is loading of the the NuGet.PackageManagement.UI.dll from the N.VS.OE.Client.dll codepath.

see some background: https://github.com/NuGet/NuGet.Client/pull/2863

**Comment by rrelyea** [comment]
PM UI showing works in feature branch. Many work items need to be done to enable the different tabs and operations work remotely.
