### ISSUE TITLE
Better tools / options to manage packages across multiple solutions

### ISSUE THREAD

**Issue by JohnLudlow** [NuGet/Home#9115]
This is basically feedback / feature request so I omitted some of the bug-report-style elements of the template.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe Version: 5.4.0.6315
Visual Studio UI 16.3.4

OS version:
Win10 1909 10.0.18363 (18363.592)

## Our situation

We build an application that includes some .NET components, some of which rely on some NuGet packages. We've also started to make some of our own NuGet packages to share amongst different codebases and partition our code.

This application's code is spread across many solutions, but when the app is built and run, a lot of it ends up in the same process - this has implications like everyone needs to use the same version of .NET assemblies / nuget packages.

When someone working on one part wants to update one of the nuget packages to a higher version, they currently face some problems. It's all too easy for someone to forget to update one thing, and updating everything is a chore. The Consolidate tab in the VS UI is very useful within a single solution, but we have many solutions.

## Proposal

We'd like a tool which could tell us when this situation has occurred (potentially failing the build) and help us apply consistent versions. 

The way I imagine this working is a command line tool which takes a collection of projects or package configs (or lock files, maybe) and emits an XML or JSON file with package names and versions. We can tweak an XML or JSON file and run the tool to apply a consistent version.

**Comment by nkolev92** [comment]
Thank you for filing this issue. 

Please refer to https://github.com/NuGet/Home/issues/6764 for an upcoming that will help address your scenario.

See wiki: https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-packages
