### ISSUE TITLE
NuGet unnecessarily selects prerelease dependences when installing a prerelease package

### ISSUE THREAD

**Issue by mark-raymond** [NuGet/Home#9116]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version (x.x.x.xxx): 5.4.0.6315

OS version (i.e. win10 v1607 (14393.321)): Windows 10 1909 (18363.592)

If I restore a prerelease package with dependency resolution highest, prerelease versions of transitive dependencies are installed even when there isn't an explicit reference to a prerelease version.

Obviously, prerelease packages should be *allowed* to reference other prerelease packages. But I don't think NuGet should select prerelease dependencies that aren't explicitly required unless I pass `-Prerelease` in.

## Detailed repro steps so we can see the same problem

1. Extract [repro.zip](https://github.com/NuGet/Home/files/4133895/repro.zip)

2. Run repro.ps1

Expected: Version 3.2.0 of package C to be installed
Actual: Version 3.3.0-beta of package C is installed

**Comment by nkolev92** [comment]
Thank you for filing this issue @mark-raymond. 

This behavior is by design in the current implementation. 
And unfortunately changing it would be too dangerous given the expectations our customers have.
