### ISSUE TITLE
nuget config <configkey> does not return default values

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/Home#9118]
## Details about Problem

NuGet product used (NuGet.exe):

NuGet version (5.1.0.6013):

OS version (Windows 10 Enterprise 1809 17763.914)

Repro steps

1. Verify that the computer level nuget.config file %AppData%/Roaming/Nuget does not contain **repositoryPath** configuration data.
2. If using a user level configuration file, verify that it does not contain **repositoryPath** configuration data.
3. Open command line at root of C:\ drive, (or any location that does not have a nuget.config file in any of the paths up to the root.)
4. Execute: nuget config repositoryPath
5. Notice that the command returns Key 'repositoryPath' not found.

The above can also be replicated with **globalPackagesFolder** or any other config section key that has a default value if undefined in a configuration file.

I would expect the command to return the default value (perhaps with some standard way of notating that it is the default value as opposed to derived from a configuration file.)

...

**Comment by zkat** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/9670
