### ISSUE TITLE
Contentfile in nuget gets compiled causing build errors

### ISSUE THREAD

**Issue by althurman** [NuGet/Home#9123]
I have a nuget that has a contentfile in it. ContentFile is a json file and denoted as such in the nuspec file when the nuget is packed.

When installing the nuget in a regular wpf app, I get a couple build errors. It appears that Visual Studio is trying to compile the .json file. Wondering if anyone knows what may cause this??? As you'll see in the nuspec snippet I have BuildAction=None in the nuspec

ContentFile.json(1,1,1,2): error CS1022: Type or namespace definition, or end-of-file expected
ContentFile.json(4,16,4,26): error CS1001: Identifier expected
ContentFile.json(4,37,4,45): error CS1001: Identifier expected

![image](https://user-images.githubusercontent.com/19433674/73555610-f1d07e00-441b-11ea-81be-05b14b2ab0f2.png)

Note: Visual Studio 19. The nuget was packed from command line using nuget.exe in a batch script. The batch script runs "nuget.exe update --self" before packing the nuget

**Comment by nkolev92** [comment]
Hey @althurman, 

Thank you for filing this issue. 
Can you please provide a repro package so we can try out your scenario?

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
