### ISSUE TITLE
Add a TypeConverter for the SemanticVersion class

### ISSUE THREAD

**Issue by thomaslevesque** [NuGet/Home#9125]
The `SemanticVersion` class lacks a `TypeConverter`. Although it's easy to manually use `Parse` and `ToString()`, it's not always convenient. If, for instance, I want to use `SemanticVersion` in my model, I need to create a converter myself to support JSON serialization. Same if I want to accept a `SemanticVersion` as an parameter to an API endpoint.

If `SemanticVersion` had a `TypeConverter`, it would be automatically picked up by JSON.NET and `SimpleTypeModelBinder`.

In the meantime, a workaround is to implement that converter manually and add it dynamically using `TypeDescriptor.AddAttributes`:

```csharp
    class SemanticVersionConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
        {
            return sourceType == typeof(string);
        }
    
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value is null)
                return null;
            if (value is string versionString)
                return SemanticVersion.Parse(versionString);

            throw new ArgumentException($"Cannot convert '{value.GetType()}' to '{typeof(SemanticVersion)}'");
        }

        public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
        {
            return destinationType == typeof(string);
        }

        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
        {
            if (value is null)
                return null;

            if (destinationType != typeof(string))
                throw new ArgumentException($"Cannot convert '{value.GetType()}' to '{typeof(string)}'");

            if (value is SemanticVersion version)
            {
                return version.ToString();
            }
            
            throw new ArgumentException($"Cannot convert '{value.GetType()}' to '{typeof(string)}'");
        }
    }

    ...

    TypeDescriptor.AddAttributes(
        typeof(SemanticVersion),
        new TypeConverterAttribute(typeof(SemanticVersionConverter)));

```

**Comment by nkolev92** [comment]
Thank you for filing this issue @thomaslevesque 

We do not think we will able to get to this issue in the foreseeable future, but we would gladly consider a PR. 

Please refer to our contributing guide: https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md

**Comment by thomaslevesque** [comment]
@nkolev92 done!
https://github.com/NuGet/NuGet.Client/pull/3442

**Comment by donnie-msft** [comment]
Thanks, @thomaslevesque! This will ship in NuGet version 5.8.

**Comment by thomaslevesque** [comment]
Thanks @donnie-msft!
