### ISSUE TITLE
RestoreNetCore_MultipleProjects_SameTool_DifferentVersionRanges_DoesNotNoOpAsync is flaky

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9128]
A few failures in the last week 
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3433306&view=ms.vss-test-web.test-result-details

//cc @zivkan

**Comment by rrelyea** [comment]
Link to PR? this is in the "in review" column.

**Comment by nkolev92** [comment]
It never got disabled, did you see it happen again or?

**Comment by nkolev92** [comment]
Issue moved to [NuGet/Client.Engineering #191](https://github.com/NuGet/Client.Engineering/issues/191) via [**ZenHub**](https://www.zenhub.com/)
