### ISSUE TITLE
Portable nuspec files

### ISSUE THREAD

**Issue by juergenhoetzel** [NuGet/Home#913]
Ist there any way to use nuspec files with a platform dependend file-section on Windows and Mono/Unix?

Consider this nuspec file (https://github.com/fslaborg/FSharp.Charting):

        <?xml version="1.0" encoding="utf-8"?>											
	<package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">		
	  <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">						
	    <id>@project@</id>													
	    <version>@build.number@</version>											
	    <authors>@authors@</authors>											
	    <owners>@authors@</owners>												
	    <licenseUrl>http://github.com/fslaborg/FSharp.Charting/blob/master/LICENSE.md</licenseUrl>				
	    <projectUrl>http://fslab.org/FSharp.Charting</projectUrl>								
	    <iconUrl>https://raw.github.com/fslaborg/FSharp.Charting/master/misc/logo.png</iconUrl>				
	    <requireLicenseAcceptance>false</requireLicenseAcceptance>								
	    <summary>@summary@</summary>											
	    <description>@description@</description>										
	    <releaseNotes>@releaseNotes@</releaseNotes>										
	    <copyright>Copyright 2013</copyright>										
	    <tags>@tags@</tags>													
	    <dependencies />													
	  </metadata>														
	  <files>														
	    <file src="..\bin\FSharp.Charting.Gtk.dll" target="lib/net40" />														
	    <file src="..\bin\FSharp.Charting.Gtk.xml" target="lib/net40" />							
	    <file src="..\bin\FSharp.Charting.Gtk.fsx" target="." />								
	    <file src="..\bin\OxyPlot.dll" target="lib/net40" />								
	    <file src="..\bin\OxyPlot.GtkSharp.dll" target="lib/net40" />							
	    <file src="..\bin\LICENSE.md" target="." />										
	  </files>														
	</package>														
	                                                                                                            
```NuGet.exe pack -Version 0.90.12 -OutputDirectory "/home/juergen/fsharp/FSharp.Charting/bin" FSharp.Charting.Gtk.0.90.12.nuspec```
Results in (even if you use ```MONO_IOMAP=all```):

      Attempting to build package from 'FSharp.Charting.Gtk.0.90.12.nuspec'.
      File not found: '..\bin\FSharp.Charting.Gtk.dll'.            

Replacing ```\``` with ```/```, still an error:

     Attempting to build package from 'FSharp.Charting.Gtk.0.90.12.nuspec'.
     Cannot create a package that has no dependencies nor content.

Adding ```-NoDefaultExcludes``` (why?) fixes this issue:

    NuGet.exe pack -NoDefaultExcludes  -Version 0.90.12 -OutputDirectory    "/home/juergen/fsharp/FSharp.Charting/bin" FSharp.Charting.Gtk.0.90.12.nuspec 
    Attempting to build package from 'FSharp.Charting.Gtk.0.90.12.nuspec'.
    Successfully created package    '/home/juergen/fsharp/FSharp.Charting/bin/FSharp.Charting.Gtk.0.90.12.nupkg'.

Any feedback is highly appreciated

**Comment by yishaigalatzer** [comment]
Not sure I follow the question, is this about building a nuget package on *nix machine?

**Comment by juergenhoetzel** [comment]
@yishaigalatzer Exactly: I use *mono 4.0.1.44* on *GNU/Linux*

**Comment by yishaigalatzer** [comment]
Fei - Can we look at this as part of the 3.0 command line updates?

**Comment by eatdrinksleepcode** [comment]
Is anyone actively working on this? Is it open for a community contribution?

**Comment by yishaigalatzer** [comment]
It is being worked on, generally it will be open for a community contribution, but we are at the moment moving all the code out of nuget.core.dll into nuget3 repository, so it will be quite a sticky thing to jump into. I expect this to work in a couple of weeks. If it doesn't and we finished the port, you will be more then welcome to help on this <3.

The goal of the port is to make pack work on linux/mac natively with .Net Core, so it is just a matter of how fast we can finish the work and how many scenarios can we test before we gotta ship it.
