### ISSUE TITLE
Better support for C++/CLI (CLR) projects

### ISSUE THREAD

**Issue by JohnLudlow** [NuGet/Home#9130]
## Details about Problem
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.exe Version: 5.4.0.6315
Visual Studio UI 16.3.4

OS version:
Win10 1909 10.0.18363 (18363.592)

## Detailed repro steps so we can see the same problem
1. Create a C++/CLI or CLR project in Visual Studio.
2. Attempt to install a .NET NuGet package into that project.

### Expected
Package is installed and referenced in a similar way to how C# projects would be handled

### Actual
```
Attempting to gather dependency information for package 'Newtonsoft.Json.12.0.3' with respect to project 'MyClrLib', targeting 'native,Version=v0.0'
Gathering dependency information took 153.71 ms
Attempting to resolve dependencies for package 'Newtonsoft.Json.12.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.12.0.3'
Resolved actions to install package 'Newtonsoft.Json.12.0.3'
  GET https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.3/newtonsoft.json.12.0.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/newtonsoft.json/12.0.3/newtonsoft.json.12.0.3.nupkg 5ms
Installing Newtonsoft.Json 12.0.3.
Install failed. Rolling back...
Package 'Newtonsoft.Json.12.0.3' does not exist in project 'MyClrLib'
Package 'Newtonsoft.Json.12.0.3' does not exist in folder 'd:\src\MyApplication\packages'
Executing nuget actions took 907.78 ms
Could not install package 'Newtonsoft.Json 12.0.3'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:01.1156922
========== Finished ==========
```

**Comment by rennerg** [comment]
Upvote! For CLR projects, we should not be forced to use native targets...that's the point of CLR

**Comment by dominoFire** [comment]
@rennerg @JohnLudlow This is a very broad topic, from migrating packages.config to PackageReference and how load the assembles from NuGet and so on.

In the meantime, you can upvote this [Developer Community issue](https://developercommunity.visualstudio.com/idea/351636/use-packagereference-in-vcxproj.html).
