### ISSUE TITLE
Use XNode.EqualityComparer to compare XDocument instead of string comparison

### ISSUE THREAD

**Issue by kartheekp-ms** [NuGet/Home#9131]
Details about Problem - Use XNode.EqualityComparer to compare XDocument instead of string comparison for better usage of .NET API [src](https://github.com/NuGet/NuGet.Client/blob/01b8ddaf018b17e493646583b432a867dd8065f0/src/NuGet.Core/NuGet.Commands/RestoreCommand/Utility/BuildAssetsUtils.cs#L339)

**Comment by zivkan** [comment]
You added the `Area:Restore` tag. I guess this means the code is used in a restore?  Is it used in a no-op restore, or only a full restore?  What customer scenarios will a fix impact?

**Comment by kartheekp-ms** [comment]
PR is now approved. We will wait for few hours before merging to `dev`.
