### ISSUE TITLE
[Test Failure] PMC and PM UI were disappeared after installing NuGet client dev-cmanu-cpvm01\5.5.0.10112 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#9138]
## Installiation
Install VS:  https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3443381&view=results 
NuGet Version：dev-cmanu-cpvm01\5.5.0.10112 
## Repro steps 
1. Install a clean machine with OS: Windows-10-Enterprise-RS5. 
2. Install Visual Studio 2019 Preview Master\29804.172 
3. Install NuGet Client dev-cmanu-cpvm01\5.5.0.10112. 
4. Launch Visual Studio 2019 Preview and try to open PMC & PM UI. 
## Expected
PMC and PM UI can be opened successfully. 
## Actual
PMC and PM UI were disappeared after installing NuGet client dev-cmanu-cpvm01\5.5.0.10112. 
## Notes
1.The implicit NuGet Client is 5.5.0.6412 instead of 5.5.0.10112 after installing “NuGet Build tools” through “Quick Query”. 
2.It didn’t repro before installing NuGet client dev-cmanu-cpvm01\5.5.0.10112.
3.Below error prompt when creating ASP.NET Web Application(.Net Framework) after step 4 as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/73830419-9f3dfa00-483f-11ea-90ec-c7281bbcf7db.png)

**Comment by cristinamanum** [comment]
Created a builds:
**dev-cmanu-cpvm01\5.5.0.6419**
dev-cmanu-cpvm01\5.5.0.6416 

and tested with three applications types.

Web App AspNetCore
Console NetCore 
Console NetFramework 

The VS installed is from 
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3443381&view=results
SKU : VSProfessional , "Branch Channel"

Both PMUI and PMC work for the three scenarios.

**Comment by v-longmin** [comment]
We verified the issue on NuGet Client\dev-cmanu-cpvm01\5.5.0.6419, it has been fixed, close it, thanks!

**Comment by donnie-msft** [comment]
Commit for future reference: https://github.com/NuGet/NuGet.Client/commit/dc77e072a3f7733a63a5a5645548fd057d500391
