### ISSUE TITLE
Cann't load DSM.

### ISSUE THREAD

**Issue by ghost** [NuGet/Home#9139]
Windows 10, VS2017, WinformsSample1

code fails at Form1.cs, line 46
 `this._twainx.OpenDSM();`

Cann't load DSM.  dialog appears.  Can't run progam.

(Also the English contraction "can not" is spelled "can't" - just 1 'n')

**Comment by heng-liu** [comment]
I could not repro or tell if it's related to Package Manager in VS.
Can you pls provide detailed repro steps? Thanks!

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
