### ISSUE TITLE
Package which provides asset for lib\win is not considered applicable on netcore50

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#914]
Use the following project.json:
```
{
  "dependencies": {
    "Win2D": "0.0.22"
  },
  "frameworks": {
    "netcore50": {}
  }
}
```
I'd expect this to install since Win2D has an asset for lib\win.  Win is win8 which is treated as netcore45 which should be compatible with netcore50.  Same result for uap10.0.  Also, diag log gives no indication why it is not compatible:
```
info : Restoring packages for .NETCore,Version=v5.0...
error: Win2D 0.0.22 is not compatible with .NETCore,Version=v5.0.
error: Some packages are not compatible with .NETCore,Version=v5.0.
```

**Comment by emgarten** [comment]
I am not able to repro this in the latest NuGet build. There are existing unit tests around netcore50 -> win compatibility. Adding the Win2D package to a new UWP app installs it without any errors both with and without the supports section in the project.json file.

@ericstj are you still hitting this issue?

**Comment by ericstj** [comment]
Nope it works for me on latest, lib\win is honored.  /cc @damyanp

**Comment by damyanp** [comment]
Yup I also see this was fixed recently.
