### ISSUE TITLE
Determine Entire Configuration for a Given Path

### ISSUE THREAD

**Issue by gravidThoughts** [NuGet/Home#9140]
I've read all of the configuration documents, and I am pretty sure the answer is no.

Is there a Nuget CLI config command that will display the **entire** resolved configuration for the directory that nuget is executing in? This includes the configuration elements that cannot be accessed with the **config** command like `packageSources`.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8420
