### ISSUE TITLE
$ENV_VARIABLE doesn't work in my mac

### ISSUE THREAD

**Issue by aperdomob** [NuGet/Home#9141]
this comment

&lt;!--
            Used to specify the default location to expand packages.
            See: nuget.exe help install
            See: nuget.exe help update

            In this example, %PACKAGEHOME% is an environment variable. On Mac/Linux,
            use $PACKAGE_HOME/External as the value.
        --&gt;

suggests that in mac I need to use `$` for environment variables but It doesn't work, it works with %ENV_VARIABLE%

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ea1390e-db36-6759-3095-ebab9d546fdb
* Version Independent ID: ca88d8c6-0515-a267-aac3-a508c54157ab
* Content: [nuget.config File Reference](https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file)
* Content Source: [docs/reference/nuget-config-file.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/nuget-config-file.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by karann-msft** [comment]
@aperdomob - going forward, please use the Home repo to file product bugs/issues. Also, for this specific issue, please update it using the following template

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Thank you for filing this issue. 

This issue seems identical to https://github.com/NuGet/Home/issues/8662. Please follow that issue for updates.
