### ISSUE TITLE
NuGetVersionRange allows logically incorrect ranges to be parsed

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9145]
See: https://nugettoolsdev.azurewebsites.net/5.5.0-preview.2.6382/parse-version-range?versionRange=%5B10.0.0%2C+9.0.0%29

> [10.0.0, 9.0.0)

This range is empty and there's no reasonable scenario where it's necessary. 

This has always been the case, all the way to 2.5 https://nugettoolsdev.azurewebsites.net/2.5.0/parse-version-range?versionRange=%5B10.0.0%2C+9.0.0%29.

**Comment by erdembayar** [comment]
@nkolev92 
I see only 2 ways to handle this.  Which one is more appropriate this case? 
1. Let exception through here.

https://github.com/NuGet/NuGet.Client/blob/35b6dcdb23642c502065458d91e644fb6fb17ecf/src/NuGet.Core/NuGet.Versioning/VersionRangeFactory.cs#L72-L74

2. Return `VersionRange.None`.

**Comment by nkolev92** [comment]
I would throw communicating that it's an invalid range.

**Comment by erdembayar** [comment]
@nkolev92 
How about `(9.0.0, 9.0.0)`?  It's technically it's illogical range but also used as empty range in unit tests.
What to do in this case?

**Comment by nkolev92** [comment]
I think it's fine to leave that as a valid range.
Let's not overdo it :) 

Obviously not too many people were affected by this problem.
