### ISSUE TITLE
non-SDK style project with PackageReference with no version has bad error in Visual Studio

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9156]
See this Developer Community issue: https://developercommunity.visualstudio.com/content/problem/905757/nuget-restore-fails-with-error-systemargumentexcep.html

Steps to reproduce:

1. Create .NET Framework project (console app or class lib, it doesn't matter. Just needs to be not SDK style project).
2. Add a package to the project, using `PackageReference`
3. Unload the project
4. Edit the `PackageReference` and set the version to an empty string
5. Reload the project
6. Restore

Expected: error message saying which project and which package has a bad version

Actual:
> Error occurred while restoring NuGet packages: '' is not a valid version string.

**Comment by nkolev92** [comment]
Closing as dup of https://github.com/NuGet/Home/issues/9289, because that's the one linked in multiple partner conversations.
