### ISSUE TITLE
"update-package" fails if a package dependency has a version filter

### ISSUE THREAD

**Issue by VosmoyBit** [NuGet/Home#916]
Visual Studio 2013 Professional, Version 12.0.31101.00 Update 4
NuGet Package Manager 2.8.60318.734

A project I'm working on requires a specific version of Common.Logging to work. It creates a NuGet package as the output. The package installs with no problems, but calling `update-package` from the PM console results in an error. NuGet tries to install a higher version of Common.Logging and fails. Shouldn't `update-package` take into account the `allowedVersions` of installed packages and their dependencies?

The .nuspec for "MyPackage" restricts Common.Logging to version 2.1.2:

```
<dependencies>
  <dependency id="Common.Logging" version="[2.1.2]" />
</dependencies>
```

Please see the .nuspec file, command output, and packages.config. Notice that the packages.config entry for Common.Logging has no `allowedVersions` attribute.

**MyPackage.nuspec**
```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/10/nuspec.xsd">
  <metadata>
    <id>MyPackage</id>
    <version>3.12.1</version>
    <title>My Package</title>
    <authors>VosmoyBit</authors>
    <owners>VosmoyBit</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Description</description>
    <copyright>Copyright 2015</copyright>
    <dependencies>
      <dependency id="Common.Logging" version="[2.1.2]" />
    </dependencies>
  </metadata>
</package>
```

**Command Log**
Installing MyPackage into a new project and immediately running update-package
```
PM> install-package MyPackage -projectName MyProject
Attempting to resolve dependency 'Common.Logging (= 2.1.2)'.
Installing 'Common.Logging 2.1.2'.
Successfully installed 'Common.Logging 2.1.2'.
Installing 'MyPackage 3.12.1'.
Successfully installed 'MyPackage 3.12.1'.
Adding 'Common.Logging 2.1.2' to MyProject.
Successfully added 'Common.Logging 2.1.2' to MyProject.
Adding 'MyPackage 3.12.1' to MyProject.
Successfully added 'MyPackage 3.12.1' to MyProject.

PM> update-package -whatIf
No updates available for 'MyPackage' in project 'MyProject'.
Updating 'Common.Logging' from version '2.1.2' to '3.2.0' in project 'MyProject'.
update-package : Updating 'Common.Logging 2.1.2' to 'Common.Logging 3.2.0' failed. Unable to find a version of 'MyPackage' that is compatible with 'Common.Logging 3.2.0'.
At line:1 char:1
+ update-package -whatIf
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.UpdatePackageCommand
```

**packages.config** after running the above
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="MyPackage" version="3.12.1" targetFramework="net45" />
  <package id="Common.Logging" version="2.1.2" targetFramework="net45" />
</packages>
```

**Comment by yishaigalatzer** [comment]
Thank you for this detailed bug, we are going to take a look as soon as we close out the 3.0/3.1 releases

**Comment by johnataylor** [comment]
This appears to be fixed in the latest release. Update-Package now just reports that the project is up to date rather than an error. This looks like correct behavior to me.
