### ISSUE TITLE
Problems with target Framework

### ISSUE THREAD

**Issue by code2expert** [NuGet/Home#9168]
I have developed a solution using .NET Core 2.2 and after a while, I it got corrupted and I had to do a repair.

The problem is that since the repair, I've been getting NU1701 error every time I update a library. I have checked the version I'm using on in the application properties and its still showing .NET Core 2.2. 

Kindly advise on what I may be missing. Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 377ae860-386f-149f-c5e0-410d3aa89dbc
* Version Independent ID: 2b145147-fd3f-d1aa-2694-071a31542d9a
* Content: [NuGet Errors and Warnings Reference](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1701?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(NU1701)%26rd%3Dtrue)
* Content Source: [docs/reference/errors-and-warnings/NU1701.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU1701.md)
* Product: **nuget**
* GitHub Login: @zhili1208
* Microsoft Alias: **lzhi**

**Comment by karann-msft** [comment]
@code2expert - for future reference, select the "This Product" button when providing product-related feedback.
![image](https://user-images.githubusercontent.com/16904420/74288118-73f45880-4ce0-11ea-9ef0-b87cd2c51fd7.png)

Use the template below to provide more information for the team to triage the issue.

Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by code2expert** [comment]
Thanks for your update

**Comment by nkolev92** [comment]
Hey @code2expert, 

The warning you are referring to just suggests that the package itself might not be fully compatible with .NET Core projects. 

Are you seeing *any* problems beyond that?

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
