### ISSUE TITLE
Add protocolVersion argument to nuget source add

### ISSUE THREAD

**Issue by bvamos** [NuGet/Home#9170]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): any

Worked before? If so, with which NuGet version: No

## Feature request

Ability to specify protocolVersion property when adding new package source with CLI

**Comment by rtaylor72** [comment]
Is there an ETA on this? Should be very easy to implement.

**Comment by GMZwinge** [comment]
Should also support `protocolVersion` when updating a source, as well as when doing those using dotnet, eg: `dotnet nuget add/update source ...`.

**Comment by DavidRadoorHummel** [comment]
This would be very cool to have. Especially in an automated environment where you want to add a source

**Comment by nkolev92** [comment]
We prioritize investigations based on community engagement such as comments and up-votes. 
We don't believe we'll get to this issue soon, but we'd be happy to consider a contribution https://github.com/nuget/home#contributing.

**Comment by TobiasBreuer** [comment]
Linked #11871 as this issue is really causing trouble in CI pipelines, where NuGet sources are dynamically added via `nuget source add`.  
The fact that we cannot specify the protocolVersion as part of this command - and hence the version is missing from the config, leads to incorrect behavior of the `nuget push` command later on, not pushing the symbols that exist next to the package...

**Comment by zivkan** [comment]
As a workaround, you can use a small powershell script in your CI:

```
$xmlDoc = [xml](Get-Content nuget.config)
$newSource = $xmlDoc.CreateElement("add");
$newSource.SetAttribute("key", "MySource");
$newSource.SetAttribute("value", "https://my.source.test/");
$newSource.SetAttribute("protocolVersion", "3");
$packageSources = Select-Xml -Xml $xmlDoc -XPath "/configuration/packageSources"
$packageSources.Node.AppendChild($newSource)
$xmlDoc.Save("nuget.config")
```

Although using powershell to only set the protocolVersion would be easier:

```
dotnet nuget add source https://my.source.test/ -n MySource
$xmlDoc = [xml](Get-Content nuget.config)
$MySource = Select-Xml -Xml $xmlDoc -XPath "/configuration/packageSources/add[@key=""MySource""]"
$MySource.Node.SetAttribute("protocolVersion", "3")
$xmlDoc.Save("nuget.config")
```

If PowerShell isn't already available on your CI, [PowerShell (Core) is available as a .NET Tool](https://learn.microsoft.com/en-us/powershell/scripting/install/install-other-linux?view=powershell-7.3#install-as-a-net-global-tool), so even on Linux and Mac, as long as you have the .NET SDK installed, it should be possible to use one of these. Unfortunately I couldn't find something similar to `jq`, but for XML.

**Comment by TobiasBreuer** [comment]
Thx @zivkan. We actually already patch the NuGet.config file along the way as part of our CI, however, I consider this  a **very hacky** workaround and it is definitely not my go-to solution - and it doesn't solve the request to add the argument to the client 😉 - The scenario I linked, is just one example where the argument might come in handy... (while I actually think that it is a bug, that the attribute is required to successfully resolve the symbol stuff)

As soon as I find the time, I plan to provide the required contribution to make this part of an upcoming release...

**Comment by zivkan** [comment]
Big thank you to @dotnokato for contributing a PR to implement this feature!

I expect it to ship in NuGet 6.8 and the .NET 8.0.100 SDK.

**Comment by adminy** [comment]
so how come on `6.13.0.113` its still not there.
