### ISSUE TITLE
[CPVM] Re-discuss the CPV merge location

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9175]
There were question for the location where the CPVM and package reference merge needs to be done. 
At the entry point by (msbuild, VS, static restore graph entry points) or before restore .
Currently the merge is before restore when the packagespec is added to the dgspec. 

This item is to track if we need to change to do it at entry points.

**Comment by nkolev92** [comment]
@cristinamanum Is this still relevant?

**Comment by cristinamanum** [comment]
Closed as not relevant.
