### ISSUE TITLE
Rename no-cache to no-http-cache

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9180]
Across all the tooling, dotnet.exe/nuget.exe/msbuild.exe, we have a --no-cache, -NoCache, RestoreNoCache switch to turn off our http cache caching, which includes a few things: 

- Caching the resources (thing caching repository signatures, servide index)
- Caching the versions list
- Caching the nupkgs 

This whole experience is rather confusing. A lot of .NET Customers think of the global packages folder as a cache and they expect RestoreNoCache to exclude the global packages folder. In reality this is a nuget http cache and should be clearly indicated as such. 

Related to https://github.com/NuGet/Home/issues/3116. 

cc @aortiz-msft @NuGet/nuget-client

**Comment by fowl2** [comment]
The `NuGet.exe` help text is:
>-NoCache                                           Disable using the machine cache as the first package source.

Which at least mentions "machine", which I guess is different from that `%USERPROFILE\.nuget` which would be the "user cache"?

Whereas `dotnet restore`'s says:
 > --no-cache                           Do not cache packages and http requests.

Which very very strongly suggests that it will download them all from the feed. Try`-DirectDownload` - still no direct downloads.

(there doesn't seem to be a PowerShell version of this argument?)

see also: #7611

One scenario where being able to force an actual download is very important is to populate an upstream package cache eg. when switching to an Azure Artifacts feed.

**Comment by Denis535** [comment]
I was wondering why it doesn't work for local packages source ((
There is no way to disable caching for packages from local source? It's necessary for fast testing the package.

**Comment by aortiz-msft** [comment]
@Denis535 Thanks for your feedback. Would you please open a new issue for your use case?

**Comment by nkolev92** [comment]
> I was wondering why it doesn't work for local packages source ((

There is no cache for local package sources. 

See: https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process

> There is no way to disable caching for packages from local source? It's necessary for fast testing the package.

The global packages folder is an installation directory. It doesn't have life time management, so not quite a cache. 

Your scenario is covered in https://github.com/NuGet/Home/issues/6579.

**Comment by nkolev92** [comment]
> @Denis535 Thanks for your feedback. Would you please open a new issue for your use case?

@aortiz-msft Timing :D 

I think  https://github.com/NuGet/Home/issues/6579 covers that ask.

**Comment by Denis535** [comment]
I got it. There are local and remote (http) sources.
Also there is `http-cache` for packages from remote sources.
And there is `global-packages`. Many people think this is a cache. But this is just folder with installed (unzipped) packages.
Anyway `global-packages` lead to desynchronization ((

**Comment by nkolev92** [comment]
@Nigusu-Allehu The cautious approach would to be add `no-http-cache` as a new option and maybe warn when people use `no-cache`. We can choose to to keep or delete the `no-cache` option eventually, but for  sure keep it for a few releases.
