### ISSUE TITLE
IVsPackageInstallerServices.IsPackageInstalled  returns false on 1st call

### ISSUE THREAD

**Issue by softlion** [NuGet/Home#9181]
## Details about Problem
In an AsyncPackage visual studio extension, this code detects if the Xamarin Forms nuget is installed when a xaml file is focused.
The code works fine except the 1st time it is called. It was tracked down to IsPackageInstalled which returns ... false.

I suppose there is some async work taking place in the nuget component, which needs to load the nugets installed in the current project, and on the 1st call of IsPackageInstalled this initialization step is not finished. This is 100% guess.

```csharp
var dte = await vsPackage.GetServiceAsync<DTE,DTE2>();
var nugetService = componentModelService.GetService<IVsPackageInstallerServices>();


void OnWindowActivated(Window focus)
{
  if(focus.Document?.Name.ToLowerInvariant().EndsWith(".xaml") == true)
  {
     var installed = nugetService.IsPackageInstalled(focus.Project, "Xamarin.Forms")
     //RESULT: FALSE on 1st call, even if the package is installed
   }
}

dte.Events.WindowEvents.WindowActivated += (focus, lostFocus) => OnWindowActivated(focus);

```

NuGet product used: NuGet.VisualStudio nuget package
NuGet versions: 5.4.0 and 5.5.0-preview.2.6382
VS version : Version 16.4.5
OS version: Windows  10.0.18363.657

## Other suggested things

I can zip a repro project to someone.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/8616
