### ISSUE TITLE
[CPVM] Increase test coverage

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9184]
- public static ProjectStyle? GetProjectRestoreStyleFromProjectProperty(string restoreProjectStyleProperty)
- CentralPackageVersion ctor (null arg checks)
- internal class MSBuildItemIdentityComparer : IEqualityComparer<IMSBuildItem>
- JsonPackageSpecReader.cs  ->  PopulateCentralDependencies
- Add/update tests in test\NuGet.Core.Tests\NuGet.ProjectModel.Test\ProjectRestoreMetadataTests.cs
- Add/update tests on LibraryDependencyTests.cs.
- MSBuildProjectItemInstance.Properties
- Update the test TargetFrameworkInformationCloneTest to verify the CentralPackageVersions property.

**Comment by aortiz-msft** [comment]
Bulk-closing old issues for CPVM.
