### ISSUE TITLE
CommandRunnerResult works differently with dotnet.exe vs nuget.exe?

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#9190]
In dotnetsourcestests.cs needed to use item2, where item3 worked in nuget.exe based tests

```
                // TODO: Item2 in dotnet, vs Item3 in nuget.exe -- switched
                result.Item2.Contains(expectedErrorMessage),
                "Expected error is " + expectedErrorMessage + ". Actual error is " + result.Item2);
```

Figure out difference that causes that...in order to simplify porting any tests from nuget.exe to dotnet.exe

**Comment by donnie-msft** [comment]
Have been wanting to rid our CommandRunnerResult from the `Item1`, `Item2`, `Item3` in favor of only `Success`, `Errors`, `AllOutput`. This may be a good opportunity to do that.

**Comment by nkolev92** [comment]
Parsing errors are not reported to std error. That's true for dotnet build as well, so this is probably more of a dotnet.exe issue.
