### ISSUE TITLE
[Test Failure] There is an error “The calling thread cannot access this object because a different thread owns it” after installing/updating/uninstalling package in the PM UI

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9192]
## Details about Problem
NuGet version: dev-donnie-msft-a11yPmuiTabs\5.6.0.10272
VS Version: Master\29818.127
OS: Windows-10-Enterprise-RS5
## Detailed repro steps so we can see the same problem
1. Launch VS and create a project [e.g. Console App (.NET Core)].
2. Open the PM UI of the project or the solution.
3. Install/Update/Uninstall a package in the PM UI.
4. Observe the Error List window.
## Expected
There is no error in the Error List window.
## Actual
There is an error “The calling thread cannot access this object because a different thread owns it” after installing/updating/uninstalling package in the PM UI as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/74833300-2ddc6c00-5354-11ea-8df1-04cc517b842f.png)

## Note
1.	The error will disappear after building the project/solution.
2.	The operation of installing/updating/uninstalling package is successful even the error appears.

**Comment by donnie-msft** [comment]
Not really part of any Release.
This was a bug reported on my branch, before merging to Dev. 
FYI, it was during 5.5 timeframe.
