### ISSUE TITLE
Clarification regarding Standard 2.0 vs 2.1 as NuGet

### ISSUE THREAD

**Issue by DrGriff** [NuGet/Home#9193]
We have multiple applications that are written in .NET 4.8 and a few that are written in .Net Core 3.1.

We currently have a private library of NuGet packages that we've written in .Net Standard 2.0 that are consumed by both the 4.8 and Core 3.1 applications.  However, we want to start to leverage .Net Standard 2.1 so that we can use nullables etc.

So if I were to set the TargetFrameworks to be "netstandard2.0;netstandard2.1" and package this up as a NuGet package, then what will happen the 4.8 and Core 3.1 apps try to consume it?  Will the 4.8 one use the Standard 2.0 flavour, and the Core 3.1 use the Standard 2.1 flavour, or both use the Standard 2.0?

Is the the best approach for creating a NuGet package available in 2.0 and 2.1?

**Comment by karann-msft** [comment]
@DrGriff - for future reference, docs issues are meant to track bugs with our documentation. For product-related questions - use the Home repo.

Use the template below to provide context for the team to triage this issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
> Will the 4.8 one use the Standard 2.0 flavour, and the Core 3.1 use the Standard 2.1 flavour, or both use the Standard 2.0?

When selecting the closest matching framework, it's always done independently. 

net4.8 will select netstandard2.0
netcoreapp3.1 will select netstandard2.1
