### ISSUE TITLE
Question: NetStandard Resolution when consuming multi-target package

### ISSUE THREAD

**Issue by whoiskevinrich** [NuGet/Home#9198]
Given a consuming application:
`<TargetFramework>netcoreapp2.1</TargetFramework>`

that has a reference to a NuGet Package that is targeting multiple netstandard frameworks:
`<TargetFrameworks>netstandard1.3;netstandard2.0</TargetFrameworks>`

would the consuming application resolve the netstandard1.3 implementation or the netstandard2.0?

**Comment by karann-msft** [comment]
@whoiskevinrich - for future reference, the docs repo is meant for bugs related to our documentation. For product-related issues, use the Home repo.

Use the template below to provide information for the team to triage this issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

## Other suggested things

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by whoiskevinrich** [comment]
Which team would handle a question about current functionality that is not in the documentation, as asked above?

**Comment by kartheekp-ms** [comment]
Refer to [NuGet doc](https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#matching-assembly-versions-and-the-target-framework-in-a-project) to learn more about how NuGet installs a package that has multiple assembly versions. As per [doc](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), .NET Core 2.0 implements .NET Standard 2.0. In the scenario mentioned above, the consuming application should resolve netstandard2.0 libraries.
