### ISSUE TITLE
Restore:  improve performance by parallelizing population of solution dependency graph spec

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9200]
Restore and no-op restore performance can be improved by parallelizing population of the solution dependency graph spec.

Currently, [projects are added sequentially to the solution dependency graph spec](https://github.com/NuGet/NuGet.Client/blob/f67a6083f8a49502f52f0c50492db03452785359/src/NuGet.Core/NuGet.PackageManagement/BuildIntegration/DependencyGraphRestoreUtility.cs#L220-L276).

https://github.com/NuGet/Home/issues/9002 is a prerequisite for this.

The [DependencyGraphSpec ](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.ProjectModel/DependencyGraphSpec.cs#L241) object uses a standard collection object as a backing collection. 
There are no native framework concurrent SortedSet nor concurrent SortedDictionary, I just decided use ConcurrentDictionary for both of them. Then we sort it before consume it.
Also using ConcurrentDictionary in place of SortedSet may be extra space overhead since we only care about dictionary key not values. Please note ConcurrentBag not suitable for this because it doesn't check for duplicate item and checking it costs O(n) time complexity.
Overall I don't believe replacing SortedSet by ConcurrentDictionary degrade performance, because it's pure C# code usually doesn't tax heavy for small/medium size sets, it would matter unless there are hundreds thousands of items.
Here insert time O(logN) for SortedSet but much cheaper O(1) for Dictionary which is advantage.
But when iterate through values then O(n) for SortedSet but expensive O(n* logN) for Dictionary before consumption can be slight disadvantage.

So far I don't see much improvement after this my improvement is just 0-10% and which can be overshadowed by other factors like network/CPU/RAM load at the time. 
Before my change: [Log1](https://gist.github.com/erdembayar/6af1ce9bd8a52d2c2210bacca3c68392) 34.47sec, [Log2](https://gist.github.com/erdembayar/23d1994a10c5f1ec4564bbc93db4cad6) 31.85sec.

After my change: [Log1](https://gist.github.com/erdembayar/28f111eac86455ee86f0772e993c9ba0) 30.84 sec.

**Comment by nkolev92** [comment]
We do have metrics around the performance of the dg spec population. 

We could dig into those numbers to get a feel of what type of improvements we should expect here.

**Comment by erdembayar** [comment]
@nkolev92  @aortiz-msft 
We're closing this issue. For netcore projects it was already just few milliseconds already and not much improvement room, actually adding locks for sake of concurrency safety was detrimental. But for `LegacyPackageReference` type projects effort resulted in not consistent improvement. See more details from [here](https://github.com/NuGet/NuGet.Client/pull/3605#discussion_r513840690). We have new [issue#10197](https://github.com/NuGet/Home/issues/10197) for fixing bottleneck for `legacy Package Reference` type projects.

Below is improvement results which is not consistent.
Here are measurements from **desktop**:

4 Legacy Package Reference | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 69.075 | 63.875 | 52.15
StDev | 59.6237724 | 59.68214418 | 56.63402529


21 Legacy Package Reference | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 476.2 | 307.0888889 | 423.8444444
StDev | 222.0878819 | 141.6774221 | 217.93295


43 Mixed(Legacy + package.config)  | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 542.2444444 | 539.8333333 | 553.8444444
StDev | 284.1445819 | 262.3063396 | 303.021073

Here are measurements from **slow laptop**:

4 Legacy | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 119.65 | 84.75 | 75.6
StDev | 122.208 | 84.99042 | 52.68231


21 Legacy Package Reference | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 337.68 | 541.62 | 470.6
StDev | 259.264379 | 269.2187 | 285.6216

43 Mixed(Legacy + package.config) | Sequential | Parallelization1 | Parallelization2
-- | -- | -- | --
Avg | 513.9 | 500.36 | 480.02
StDev | 299.7865 | 317.0763 | 286.5742
