### ISSUE TITLE
nuget push does not accept absolute path of a package

### ISSUE THREAD

**Issue by liesauer** [NuGet/Home#9209]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version: 2.8.7.0

## Detailed repro steps so we can see the same problem

1. upload a package with full path.

2. nuget can not find the package because it always combine with current directory no matter it is an absolute path or a relative path.

```
cd /home/AnotherWorkSpace
nuget push /path/to/project/package.1.0.0.nupkg -Source "NuGet"
```

and say
```
Directory '/home/AnotherWorkSpace/path/to/project/package.1.0.0.nupkg' not found.
```
combine with current directory when specifing a absolute path is not right!

**Comment by nkolev92** [comment]
@liesauer You are using a very old version of NuGet that's not actively maintained. 

Can you try using a newer version of NuGet such as 5.4.0? 
A quick test relative and absolute paths work just [fine](https://github.com/NuGet/NuGet.Client/commits/dev/src/NuGet.Core/NuGet.Protocol/Utility/LocalFolderUtility.cs).

**Comment by liesauer** [comment]
i am not quite sure, i will check it tonight.

**Comment by liesauer** [comment]
the nuget.exe in my windows maybe very old, but in ubuntu, it should be the latest version, i install it via `apt-get install nuget`, has this package be deprecated? because i have the same problem in ubuntu.

**Comment by liesauer** [comment]
sorry, i got mixed up. nuget in ubuntu is very old. how can i update to latest. this package seems have been outdated for a long time. i install it via `apt-get install nuget`.

**Comment by liesauer** [comment]
the latest version is still 2.x...
![image](https://user-images.githubusercontent.com/8676741/75338780-40adee00-58ca-11ea-94cc-57befffeff80.png)

**Comment by nkolev92** [comment]
@liesauer 
That package is not maintained by the NuGet team. 

Go to https://www.nuget.org/downloads to get the latest nuget.exe

**Comment by liesauer** [comment]
@nkolev92 but i need the linux version, as far as I know, `dotnet nuget` is not exactly the same with `nuget`, there are so many commands that `dotnet nuget` doesn't supported such as `nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/owner/index.json" -UserName owner -Password GH_TOKEN`, so `dotnet nuget` is out. so the only way to use the latest version is install mono and use nuget.exe in linux?
