### ISSUE TITLE
[Offline] Nuget can not resolve packages if dependency lives in different directory

### ISSUE THREAD

**Issue by dehghani-mehdi** [NuGet/Home#9212]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `NuGet.exe`

NuGet version (x.x.x.xxx): `5.4.0.6315`

OS version (i.e. win10 v1607 (14393.321)): Win10

Worked before? If so, with which NuGet version: No.

## Detailed repro steps so we can see the same problem _I try my best_

1. Put dependency package inside folder `A`
2. Create folder `B` inside folder `A`
3. Try to install depended package inside folder `B` using `nuget install DependedPackage -source path/to/DependedPackage.nupkg`

NuGet shows this error message:

> Unable to resolve dependency 'dependency package'. Source(s) used: 'A'

If I try to add `DependedPackage` inside folder `A` everything works as expected.

__Update__:

I also tried to install `DependedPackage` from `A` and add `-OutputDirectory B`, same error appears

__Update 2__:

Based on my tests, install only works when install path is the same path as dependency package path.

**Comment by nkolev92** [comment]
Think of folder A as a source. 

NuGet supports 2 types of file sources:

	- V2 vs V3 file feed
		○ V2 - Given the root of a package feed, the structure of the feed is as follows:
			§ Root
				□ packageA.1.0.0.nupkg
				□ packageB.2.1.0.nupkg
		○ V3 - Given the root of a package feed, the structure of the feed is as follows:
			§ Root
				□ packageA
					® 1.0.0
						◊ PackageA.1.0.0.nuspec
						◊ PackageA.1.0.0.nupkg
						◊ PackageA.1.0.0.sha512
					® 2.0.0
						◊ PackageA.2.0.0.nuspec
						◊ PackageA.2.0.0.nupkg
						◊ PackageA.2.0.0.sha512
				□ packageB
					® 2.1.0
						◊ PackageB.2.1.0.nuspec
						◊ PackageB.2.1.0.nupkg
						◊ PackageB.2.1.0.sha512

Your scenario does not conform to either. 

You need the source you provide to be a proper source like above. 

Let me know if this addresses your question.

**Comment by dehghani-mehdi** [comment]
@nkolev92 here is what I'm doing:

I have a folder (lets call it offline) and use it as my package source in Visual Studio. if I need a package which doesn't exists in _offline_ folder, first I install that package into it using following config file and this command: `nuget install -config nuget.config packageId -OutputDirectory offline`, and then use it inside VS.

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>    
    <add key="Online" value="https://api.nuget.org/v3/index.json" />    
  </packageSources>  
</configuration>
```

I also have some libraries, which I wrote them, and for using them, I publish them as nuget package (by adding `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>` to `csproj` file). I have separate folder for my packages (lets call it personal).

The folder structure is something like this:

```
nuget
|
-----offline
|
-----personal
```

Note: in my first post I refer to offline as `A` and refer to personal as `B`

As I mentioned, if I add my personal packages inside `offline` everything works. but if my package have dependency to one of offline packages, nuget says `Unable to resolve dependency 'dependency package'. Source(s) used: 'offline'`.

Now about your answer, when I add packages from nuget/online source to offline folder, it always saved with following pattern:

```
 packageA.1.0.0.nupkg
 packageA.1.1.0.nupkg
 packageA.2.0.0.nupkg
```

In order to test your _solution_, first I need to save packages inside offline folder with following pattern:

```
packageA
    1.0.0
        PackageA.1.0.0.nuspec
        PackageA.1.0.0.nupkg
        PackageA.1.0.0.sha512
    2.0.0
        PackageA.2.0.0.nuspec
        PackageA.2.0.0.nupkg
        PackageA.2.0.0.sha512
```

How can I do that?

**Comment by nkolev92** [comment]
You can generate a V3 package source by running `nuget.exe add`.

Back to your original problem, you are running nuget.exe install with a source. 
NuGet.exe install in this case, uses "only" that source, so it's not even looking at your personal source.

Can you try not specifying the source and either not specifying anything, allowing NuGet to use the defaults for that directory or maybe point to a config file?

**Comment by dehghani-mehdi** [comment]
> You can generate a V3 package source by running nuget.exe add.

Should I run this Inside offline directory?

> Can you try not specifying the source and either not specifying anything, allowing NuGet to use the defaults for that directory or maybe point to a config file?

Sure

> so it's not even looking at your personal source

It doesn't need to look at personal. it should look at offline. I want to install my personal packages into personal folder which has dependency and this dependency lives @ offline folder.

**Comment by nkolev92** [comment]
Hey @dehghani-mehdi 

Were you able to try out my suggestions?

**Comment by dehghani-mehdi** [comment]
@nkolev92 I tried all possible commands (based on your answers and the docs), same happened.

I could not try V3 tho, because you didn't answer my question about that.

**Comment by nkolev92** [comment]
> Should I run this Inside offline directory?

https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-add

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
