### ISSUE TITLE
Nuget says Could not find a part of the path when compiling VB.NET solution

### ISSUE THREAD

**Issue by rrodriguez1975** [NuGet/Home#9213]
I have the following problem explained [here](https://stackoverflow.com/questions/60335041/ncrontab-signed-3-3-2-nuget-says-could-not-find-a-part-of-the-path-when-compilin) in stackoverflow.

In short, I have Visual Studio 2013 and a project built with .NET Framework 4.5. I know the problem is the version of Nuget I have. My Nuget version is 2.12.0.817 (last version available for Visual Studio 2013) and I know this is causing the problem. This problem was resolved in Nuget version 2.12.1 but I am not able to install version 2.12.1 in Visual Studio 2013.... I install Nuget 2.12.1 from console and it says it has been installed correctly but Visual Studio continue saying I have version 2.12.0.817.....

Also I have tried the workaround explained in most sites, I mean, changing blank space in the following line by a backslash and it is not working:

`<PaddedSolutionDir Condition=" '$(OS)' == 'Windows_NT'">"$(SolutionDir) "</PaddedSolutionDir>`

by 

`<PaddedSolutionDir Condition=" '$(OS)' == 'Windows_NT'">"$(SolutionDir)\"</PaddedSolutionDir>`

Please, could you help me?

**Comment by nkolev92** [comment]
@rrodriguez1975 
Those 2 components work side by side. 

The NuGet extension version is 2.12.0.817.
The NuGet.Build package powering the experience is 2.12.1 - https://www.nuget.org/packages/NuGet.Build/2.12.1

Beyond that it's possible that you are having a different issue.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
