### ISSUE TITLE
GeneratePackagePath Property is not kept during package update

### ISSUE THREAD

**Issue by StarWars999123** [NuGet/Home#9214]
## Details about Problem

NuGet product used: VS UI

NuGet version (x.x.x.xxx): - 

VS version: 16.4.5

OS version: 1903 (Build 18362.628)

Worked before? If so, with which NuGet version: no

## Detailed repro steps so we can see the same problem

1. Install a nuget package to a new .net core format project.
2. Add the GeneratePathProperty for the package
3. Update the installed package
--> The GeneratePathProperty (#4837) gets removed. It should be kept during an update, as it can only be configured manually in the .csproj files. Its very timeconsuming, when the package gets updated regularly.

### Sample Project
Here an example of the used package format with .NET 4.7.2:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>BingoApp</RootNamespace>
    <AssemblyName>BingoApp</AssemblyName>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" GeneratePackagePath="True" />
  </ItemGroup>
</Project>
```

**Comment by nkolev92** [comment]
Hey @StarWars999123 

I am unable to repro this behavior with either VS 2017 or VS 2019. 

What I get is the following: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>BingoApp</RootNamespace>
    <AssemblyName>BingoApp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" GeneratePackagePath="True">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

Also note that you are an incorrect attribute name, it should be `GeneratePathProperty` instead of `GeneratePackagePath`

**Comment by StarWars999123** [comment]
Yes, It was a communication failure within our team. The issue occured only on uninstalls and reinstallation of another the package. So this isn't a bug.
