### ISSUE TITLE
Search operations in Local folders in PM UI don't report a LoadingStatus different than Loading.

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#9217]
## Details about Problem

NuGet product used: VS UI

NuGet version:

dotnet.exe --version (if appropriate):

VS version (if appropriate): 16.4

OS version: Microsoft Windows [Version 10.0.19564.1000]

Worked before?

## Detailed repro steps so we can see the same problem

Search operations in Local folders in PM UI don't report a LoadingStatus different than `Loading`.

**Comment by nkolev92** [comment]
@dominoFire 

What's the customer impact of this issue?

**Comment by nkolev92** [comment]
@dominoFire 
What's the customer impact of this issue?

**Comment by dominoFire** [comment]
No direct UI impact. Impact was on narrator when using PM UI with local sources. It only read 'Loading' when using a local NuGet source.

I tested with latest Dev17 and the issues no longer appears in Windows Narrator.

This should be fixed with this method.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.VisualStudio/PackageFeeds/LoadingStatusExtensionMethods.cs

Closing for now. Any thoughts, please let me know.
