### ISSUE TITLE
Failing feed stops search in PM UI

### ISSUE THREAD

**Issue by dominoFire** [NuGet/Home#9218]
## Details about Problem

NuGet product used: VS UI

NuGet version: 5.6.0

VS version: Version 16.6.0 Preview 1.0 [29823.26.master]

OS version: Microsoft Windows [Version 10.0.19564.1000]

Worked before?

## Detailed repro steps so we can see the same problem

1. Open VS
2. Navigate to Tools > Options > NuGet Package Manager > Package Sources
3. Add a non existent remote folder as a NuGet Source, i.e., `\\imaginary-server\imaginary-folder`
4. Create any project or open an existing one.
6. Right click on the project and go to "Manage NuGet Packages..."
7. Select "All" in the Package Source drop-down list
8. Scroll down on the package list in the "Search" Tab

### Expected

Scrolling should show more package from all but the failing feed.

### Actual

Search stops looking for more packages from other feeds.

**Comment by dominoFire** [comment]
Failure occurs at `LocalPackageSearchResource`

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/2496. 
I discovered that issue during a hot seat investigation.
