### ISSUE TITLE
PM UI: Consolidate or Update packages operations should not be blocked due to errors (Package Downgrade, etc.)

### ISSUE THREAD

**Issue by bondarenkod** [NuGet/Home#9224]
Please read the following information before posting the issue.
## Details about Problem
NuGet product used: VS UI 
NuGet package manager: 5.4.0
VS version: VS 16.4.5
OS version:  win10 (18363.657):
Worked before?: NO

## Detailed repro steps so we can see the same problem
1. Solution with multiple projects. Some of the projects included different versions of some packages. Some projects are referenced by others. For example PkgA(1.0, 1.1), PkgB(2.0, 2.1), PkgC(3.0, 3.1).
![image](https://bdfss.blob.core.windows.net/shots/2020-02-26_09-44-41-5954c3ec-060c-46f7-80ef-f5bee1d5ec2a-devenv.png)

2. I want to consolidate or update versions of these packages to the latest (or single) one. But while I'm trying to do any of these actions, the process usually stopped by the next two errors:
- Error NU1605 Detected package downgrade: PACKAGE_NAME from X.X.X.X to Y.Y.Y.Y. Reference the package directly from the project to select a different version. 
- Error NU1107 Version conflict detected for PACKAGE_NAME. (rarely)
But it's exactly I want to do - update all these packages! 
![image](https://bdfss.blob.core.windows.net/shots/2020-02-26_09-46-00-aa315409-1a24-4377-bd03-831b107f0527-devenv.png)

## Other suggested things
I think the update or consolidate process should be fixed, and all these errors should be ignored during these operations. It should do what I want and warn\show errors after all.

Also, I can probably suppress these errors by adding NU1107, NU1605 to NO_WARN section, but I don't want to leave these suppressions there forever.
### Verbose Logs
no logs
### Sample Project
I don't have the sample project now, I can't share the private project, I will try to create an example later.

#8982 

## Fix details: In PMUI downgrade or consolidate.
Currently Nu1605 single largest cause of nuget install to fail according to below graph, after this fix is pushed this will drop very significantly, I expect it'll go down on-par to NU1202, even less than NU1202.
![image](https://user-images.githubusercontent.com/8766776/89201202-f827ea00-d565-11ea-9ff2-1c51358cb075.png)

For example in you have large solution with package reference style projects which are referencing each other.

![image](https://user-images.githubusercontent.com/8766776/89138178-99278e00-d4ef-11ea-8c12-0a87ae3bef15.png)

ConsoleApp2(grandparent)=> ConsoleApp1(parent)=>MainApplication(child)

 Now if you downgrade children and parent same time to same version or consolidate many different versions into same not highest version then it throws Nu1605 error. But still downgrade one bottom child, but not others. To finish it you have to repeat this action one by one.

Downgrade error Nu1605 demo (gif animation):
![DowngradeNU1065error](https://user-images.githubusercontent.com/8766776/89138238-cb38f000-d4ef-11ea-9dd7-18c764263415.gif)

Consolidate error Nu1605 demo  (gif animation): 

![ConsolidateNU1065error](https://user-images.githubusercontent.com/8766776/89138259-dc81fc80-d4ef-11ea-92bd-c5331cc6a9b0.gif)

If you 30 projects and they have different versions of same package then you may need to try up to 30 times to downgrade or consolidate all of them. 
With my change only 1 time try it will succeed if input are good or fail depending if input are not good. 
Now we're doing smart restore let children restore first then cache needed restore result in memory, next we restore parent and parent's of parent in target group in correct order so it wouldn't fail.
Current change doesn't change this current behavior: If you only select child ( without selecting parent too) and update to higher version than parent then it'll succeed, but wouldn't build code later.
Also good thing is it doesn't update half of solution and create  any undesirable state. This change will help with my next fix [#6010](https://github.com/NuGet/Home/issues/6010) to make it more deterministic and instead of bubbling many times of repeated restore only 1 time pass will work.
Please review @nkolev92  @zivkan @rrelyea, I tried to make as minimal surgical change without affecting other logics, for that one I took time to understand how whole process works.  Here is my [PR#3553](https://github.com/NuGet/NuGet.Client/pull/3553). 

Downgrade works demo after change  (gif animation):
![DowngradeFixed](https://user-images.githubusercontent.com/8766776/89138482-97aa9580-d4f0-11ea-9cec-45a1e7be2b09.gif)

Consolidate works demo after change (gif animation):
![ConsolidateFixed](https://user-images.githubusercontent.com/8766776/89138420-6c27ab00-d4f0-11ea-958c-3ab16bdaa18c.gif)
:

**Comment by nkolev92** [comment]
Hey @bondarenkod 
Thanks for filing this issue

> I think the update or consolidate process should be fixed, and all these errors should be ignored during these operations. It should do what I want and warn\show errors after all.

Am I interpreting this correctly to mean `Do not validate whether an install/uninstall/update operation is successful, just write it in the project file`

**Comment by bondarenkod** [comment]
One more example. 
Here is the scheme and short overview why it happening to me:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-40-02-912655d6-a674-4736-a820-fedab7593bc5-POWERPNT.png)
When I'm working from the **Solution B** with core projects, I'm updating packages. 
When I'm switching to the **Solution A**, I have different versions of packages in the **Solution A**'s projects. 

Packages in the current example:
- Microsoft.AppCenter family, including the *.Crashes, *.Distribute and *.Analytics NuGet packages.
- PI.XamarinForms.Core - private package (without any dependencies to Microsoft.AppCenter.*)

The initial state of the Consolidate NuGet Packages window: 
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-44-37-5678a82d-fe08-4c36-8652-361ee5e25199-devenv.png)

Detailed view for the PI.XamarinForms.Core package:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-50-58-aa0875e6-5a2a-44ce-9c12-eeb8f13c5cc4-devenv.png)
But after pressing install a see the next errors in the errors list window:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-52-40-df099bb8-92a9-462d-9440-fa757146e2a5-devenv.png)
So, I’m not able to update this package. 

Let’s move to update window:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-54-19-83bd7813-f02c-460a-8b47-d3e7384a3a15-devenv.png)
After pressing install I see the same error.

I also tried to update Microsoft.AppCenter.* packages:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-56-23-fb2fab32-066b-4410-9e9c-12a7c09ee980-devenv.png)

The result the same, but now you can see more errors related to the PI.XamarinForms.Core package:
![image](https://bdfss.blob.core.windows.net/shots/2020-03-24_13-58-54-1b1eaad0-d200-4f32-a4f8-a5254672d6c3-devenv.png)

It looks like when the NuGet tries to update packages it sees other packages downgrade status and it's kind of blocker for the current update process - circular dependency. 

I have no auto workarounds for this except the only one - manually change the package version in the *.csproj file. 

@nkolev92 thank you for your response! Yep, something like that. I think the NuGet should just do update and ignore some types of errors - e.g. 'detected package downgrade'.

**Comment by nkolev92** [comment]
Hey @bondarenkod. 

So based on what you are describing, I think it's similar to https://github.com/NuGet/Home/issues/6010. 

Can you try to manually update all package versions on disk and run a restore?
Does it work then? 
If yes, then I believe #6010 will help fix your scenario.

**Comment by erdembayar** [comment]
Merged the fix this morning.
It was made as part of another performance improvement work: https://github.com/NuGet/NuGet.Client/pull/3559
