### ISSUE TITLE
[Test Failure] Embedded icon can’t be shown in PM UI with local package feed - depending on / vs \

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9225]
## Details about Problem
NuGet version: NuGet Client Dev\5.6.0.6472
VS Version: Master\29825.171
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1.	Create a Class Library (.NET Framework 4.8) in VS and build the solution.
2.	In the Developer Command Prompt for VS, create a nuspec file by executing command “nuget spec”
3.  Make an image file (size limited to 1 MB with JPEG/PNG format and 128x128 resolution) and locate in the package.
4.  Add following to nuspec file.
```
<package>
  <metadata>
    ...
    <icon>images\icon.png</icon>
    ...
  </metadata>
  <files>
    ...
    <file src="..\icon.png" target="images\" />
    ...
  </files>
</package>
```
5.  Pack the package to local path by executing command “nuget pack”.
6.  Create a C# Console App (.NET Framework 4.8) in VS and open the PM UI of the project.
7.  Add the package source as a local feed in Settings->NuGet Package Manager->Package Sources.
8.  Select the new added local feed in the Package source dropdown box in the PM UI and install the package.

## Expected
The embedded icon show correctly in all the tabs of PM UI.
## Actual
The embedded icon can’t be shown in all the tabs of PM UI. as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/75345053-e8c9b400-58d6-11ea-8a4b-0c9f2a076604.png)
## Note
1.	It doesn’t repro for the package creating by “dotnet pack” with local package feed.
2.	It doesn’t repro for the package “Text2Xml.Lib” (version 1.1.1 and 1.1.2) in remote feed.
3.	It also repro with icon.jpg.

**Comment by dominoFire** [comment]
If you use `/` instead of `\` in the `<icon/>` element, then, you can see the package icon in the PM UI.

```xml
<package>
  <metadata>
    ...
    <icon>images/icon.png</icon>
    ...
  </metadata>
...
```

**Comment by rrelyea** [comment]
Please add team members to this review if you are ready for review.

**Comment by rrelyea** [comment]
talked with @dominoFire and learned the following:
dotnet.exe will normalize / and \ inside of icon metadata
nuget.exe will not normalize / and \ inside of icon metadata
VS UI currently only supports "/" in icon metadata.
he tested nuget.org and thinks that / and \ are both supported.

@dominoFire's current strategy: 
leave nuget.exe to not normalize
fix VS UI to support "/" or "\"
effectively saying that it is ok for packages to use either way.
that also means that we need to ensure nuget.org and other server implementations do that...if we do that, how do "spec" that requirement?  (azure devops is about to do this work, for example)

@karann-msft, @agr, @dominoFire, @jmyersmsft - can you ensure that you are all happy with the direction and understand if this fix has everything we need...and ensure we solve the 3rd party server as well.
