### ISSUE TITLE
How use nuget pack push on Jenkins installed on Linux

### ISSUE THREAD

**Issue by NithishHemanth** [NuGet/Home#9227]
NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Nuget.exe 

NuGet version (x.x.x.xxx):
5.4.0 or previous versions till 3.3.0

OS version (i.e. win10 v1607 (14393.321)):
Linux 

Worked before? If so, with which NuGet version:
I tried to create nupkg packages and push to artifactory using nuget 3.3.0 and later in Jenkins 1.546 installed on LINUX OS.

Nuget commands are not working at both windows command build step as well shell command build step. Please suggest to get this working for Jenkins installed on Linux

Commands used to create nuget packages :
nuget pack xxx.nuspec

Commands used to push artifacts to artifactory:
nuget setApiKey xxxx:xxxx -Source xxxx
nuget push *.nupkg -Source xxxx

NOTE: i have tried the same at jenkins installed on Windows worked fine. No issues.

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
@NithishHemanth 
Thanks for creating this issue. 

Can you explain what's not working? 

NuGet.exe is written for .NET Framework, so it can only run on platforms supporting CLR. In order to use NuGet.exe on Linux, you need to use mono.

dotnet.exe however is fully cross platform.

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
