### ISSUE TITLE
project.assets.json content doesn't parse with JSON deserializers

### ISSUE THREAD

**Issue by markolbert** [NuGet/Home#9228]
Not sure if this is the right place to raise this kind of question but it's where a search on some similar questions pointed me to...

I'm writing a C# metadata extractor which requires that I parse `project.assets.json` in order to locate the assembly references I need to have Roslyn compile the project I'm analyzing. This is complicated by the structure of `project.assets.json` not being well-formed, in the sense that it can't be easily deserialized by a JSON deserializer.

Consider the following example:

```
{
  "version": 3,
  "targets": {
    ".NETStandard,Version=v2.1": {
      "Autofac/5.1.2": {
        "type": "package",
        "compile": {
          "lib/netstandard2.1/Autofac.dll": {}
        },
        "runtime": {
          "lib/netstandard2.1/Autofac.dll": {}
        }
      },
```
Both the first target (".NETStandard...") and the package identifier ("Autofac/5.1.2") are valid JSON identifiers but not valid C# property names. Which is what upsets the deserializers I've tried (JSON.Net and System.Text.Json).

I'm curious as to why a structure something like the following isn't used:

```
{
  "version" : 3,
  "targets" : [
    {
      "targetName" : "NetStandard",
      "targetVersion" : "2.1.0",
      "packages" : [
        {
          "name" : "Autofac",
          "version" : "5.1.2",
          "type" : "package",
          "dependencies" : [ ],
          "compile" : [
            "lib/netstandard2.1/Autofac.dll"
          ],
          "runtime" : [
            "lib/netstandard2.1/Autofac.dll"
          ]
        },
```

**Comment by nkolev92** [comment]
Hey @markolbert

Unfortunately I can give you a complete historical answer as to why that specific decision was made.
Much has to do with the structure of project.json itself, but beyond the NuGet client itself, this structure is largely irrelevant.
It's something that NuGet writes and provides

Everyone that consumes the file uses https://github.com/NuGet/NuGet.Client/blob/bf9523d7b66f749f8709c8f082944db6a60f9153/src/NuGet.Core/NuGet.ProjectModel/LockFile/LockFileFormat.cs to read, and I'd suggest you do the same. 

Does this answer you question?

**Comment by markolbert** [comment]
Yes, it does. I took a quick glance at the link, which I’ll keep, but it looks a lot more involved than something I had started writing. If I get mine to work I’ll post it. 

Is there documentation available for version 3 of project.assets.json? I’m working off a particular example but it may not be comprehensive. 

Thanx for getting back to me.

**Comment by nkolev92** [comment]
> Is there documentation available for version 3 of project.assets.json?

Not really. This is considered an internal NuGet/Build asset, so as such it won't be super well documented and we don't really recommend you taking dependencies on it as it's something that changes according to the product needs.

**Comment by markolbert** [comment]
@nkolev92, I put together a little C# library for parsing project.assets.json files. You can [find it here](https://github.com/markolbert/RoslynUtils). It handles all hundred some odd examples I have on my system (all of which are version 3 files). Probably of no interest to anyone but me but it might be an alternative to the approach in the link you gave me. Enjoy!
