### ISSUE TITLE
[Test Failure] Restore should be fail with an error after running “dotnet restore --use-lock-file --locked-mode” with an empty or malformed lock file

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9229]
## Details about Problem
NuGet version: NuGet Client Release-5.5.x\5.5.0.6473
VS Version: D16.5\29827.131
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a Console Application (.NET Core) template in VS and close the solution.
2.	Create an empty or malformed packages.lock.json file next to the .csproj file. 
3.	Run “dotnet restore --use-lock-file --locked-mode”.
## Expected
Verify the process should fail with an error saying the lock file is incorrect.
## Actual
The restore completed without any error as below.
![image](https://user-images.githubusercontent.com/20632625/75553891-3fb8c000-5a74-11ea-9140-2143e6231175.png)
## Note
1. It didn't repro on NuGet Client Release-5.5.x\5.5.0.6464, so it start from Release-5.5.x\5.5.0.6473.
2. It didn't repro on Master\29826.166+NuGet Client Dev\5.6.0.6478.
3. The bug [8640](https://github.com/NuGet/Home/issues/8640) is fixed on this build.

**Comment by zivkan** [comment]
@v-luzh Can you explain, or link to instructions, on how you patched dotnet.exe to use the NuGet 6473 binaries?

I'm trying to reproduce locally, but I correctly get the error saying that the lock file is inconsistent with the project.

**Comment by v-luzh** [comment]
Hi @zivkan , this issue is fixed on the newer build. Now we can see the inconsistence error on VS Master\29925.152 + NuGet Client Dev\5.6.0.6532. You can resolve it as fixed. Thanks.
