### ISSUE TITLE
New EnableCentralPackageVersions property breaks Microsoft.Build.CentralPackageVersions

### ISSUE THREAD

**Issue by dfederm** [NuGet/Home#9232]
This change: https://github.com/NuGet/NuGet.Client/commit/08ded6ff38ec67e25c094d28e77cb23c15ee674b#diff-3b0018f61173d0adf1ba163a23821381 is causing incompatibility with [Microsoft.Build.CentralPackageVersions](https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions). Both use the `$(EnableCentralPackageVersions)` property and so conflict.

Specifically, this line in NuGet.targets:
```xml
    <EnableCentralPackageVersions Condition="'$(EnableCentralPackageVersions)' == ''">false</EnableCentralPackageVersions>
```

This disables the feature in the `Microsoft.Build.CentralPackageVersions` SDK.

**Comment by dfederm** [comment]
FYI @cristinamanum @jeffkl @AndyGerlicher

**Comment by rrelyea** [comment]
fyi: @zivkan @aortiz-msft

**Comment by cristinamanum** [comment]
Duplicate of https://github.com/NuGet/Home/issues/9235
