### ISSUE TITLE
document valid-authentication-types better

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#9233]
from PR comment:
https://github.com/NuGet/NuGet.Client/pull/3253#discussion_r382891553

What are all the available authentication types? Should we give a quick synopsis on what basic and negotiate means? Are there additional docs on these types that we can link? I would recommend wrapping the example in a code block: basic,negotiate

**Comment by nkolev92** [comment]
Issue moved to [NuGet/docs.microsoft.com-nuget #1986](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1986) via [**ZenHub**](https://www.zenhub.com/)
