### ISSUE TITLE
[CPVM] EnableCentralPackageVersions  name conflict with CentralPackageManagement MsBuild SDK 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9235]
## Details about Problem

The new name EnableCentralPackageVersions introduced in  NuGet.targets conflicts with the Central Package Versions SDK https://github.com/microsoft/MSBuildSdks/blob/f4e31079565777df7656a358777f8db285c4c0bd/src/CentralPackageVersions/Sdk/Sdk.targets#L28-L29

This needs to be changed to avoid the conflict.

**Comment by zivkan** [comment]
PR was merged, but issue wasn't linked correctly.
