### ISSUE TITLE
Design the authentication experience for VS Online Environments

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9244]
Currently the authentication model is talk to a plugin/pop-up a dialog if needed. 
We need to ensure that the customers receives a dialog similarly to normal VS. 
[1073273](https://devdiv.visualstudio.com/DevDiv/_queries/edit/1073273/)

This should be converted to an epic if necessary.

**Comment by rrelyea** [comment]
Driving design here: https://github.com/NuGet/Home/pull/9638, in conjunction with Thursday meeting with VS Identity team, Azure Artifacts and NuGet.

**Workaround:**
Restore NuGet packages using browser auth
Run this script in a terminal on your Codespace
Run dotnet restore --interactive.
Do not use NuGet.exe with private feeds, NuGet.exe might show a dialog prompt on the server side and you will not see it.

Manage NuGet packages
Work around: use the dotnet cli to add or remove a nuget packages from the terminal. More Info 
dotnet add package <PACKAGE_NAME> [-v version] [-s source]

See dotnet Project package commands  for more detailed command syntax.

**Comment by rrelyea** [comment]
After first meeting, it appears that there is much to be improved in every component involved in VS auth on server. VS Identity team debugged last week...and has a bug fix on their side and recommendations for the VS AACP (mef based) and nuget. We need to walk through that proposal and determine the plan.

**Comment by rrelyea** [comment]
NuGet inserted v 5.7.0.6665 into the VS Master branch (for preview 4) Monday: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/256263
(last week it was inserted into Preview3 branch, but VS-AACP fix isn’t in P3)

So today's Int Preview build will include all 3 fixes in the same branch for the first time.

This will make VS-AACP scenarios where your account to log into codespaces is the same as the account that is authorized to access the azure artifacts feed work.

Please let @Rob Relyea and @Christopher Gill of any other questions in this area. 

Future planned improvements and investigations for VS-AACP scenarios:

### VS & Azure Artifacts
- If the dev uses the same account to auth to the codespace as they will use to get packages from azure artifacts, no additional auth is required.
- If the dev uses a 2nd account to get packages from azure artifacts, that account must be authenticated for that feed.
    - Part of that problem is we don't have an anchor for authenticated sources. Perhaps we improve the error experience, and provide an anchor in the UI, so they can figure out how to do this. Tracking issue: [nuget/home#7814](https://github.com/NuGet/Home/issues/7814)


Current status for CLI...all improvements tracked in those issues.

### dotnet.exe/nuget.exe/msbuild.exe running in VS Terminal
- msbuild.exe /restore /p:NuGetInteractive=true
  - works via codeflow today, if you ask for interactive
    - integrated windows auth doesn't work w/o interaction, unlike normal CLIs and AACP on a client. (see "could it remote..." below)
  - device flow prompts once per feed, where it should be able to use the same creds, in most cases, if same AAD Tenant. [artifacts-credprovider#195](https://github.com/microsoft/artifacts-credprovider/issues/195)
- nuget.exe
  - NuGet.exe should detect execution on codespace, and send canPrompt to plugin as false. [nuget/home#9687](https://github.com/NuGet/Home/issues/9687) 
- dotnet.exe
  - make install of AACP (dotnet core flavor) installable easily [client.engineering#360](https://github.com/NuGet/Client.Engineering/issues/360)
  - Longer term: should dotnet.exe be able to use full framework copy of AACP? Or should dotnet.exe copy of AACP be able to replace full framework copy.
- all
  - [nuget/home#9688](https://github.com/NuGet/Home/issues/9688) improve error experience with NUXXXX errors when auth fails, or auth fails and no cred provider is there, etc...
