### ISSUE TITLE
GeneratePackageOnBuild does not pack transitive crosstargeting projects from non solution builds

### ISSUE THREAD

**Issue by cdmihai** [NuGet/Home#9247]
If you have:
- three projects, A->B->C
- C is crosstargeting
- A and C have GeneratePackageOnBuild set to true
- Build A.csproj

Then A will pack and C won't. The expected behaviour is for C to pack as well.

A.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\B\B.csproj" />
  </ItemGroup>
</Project>
```

B.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\C\C.csproj" />
  </ItemGroup>
</Project>
```

C.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard1.6;</TargetFrameworks>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
</Project>
```

Build with `dotnet msbuild /restore A\A.csproj`

dotnet.exe --version (if appropriate): 3.1.200-preview-015002
OS version (i.e. win10 v1607 (14393.321)): win10

**Comment by nkolev92** [comment]
Why should packing be transitive?

If you want it to package all of them, specify the property globally. 

In fact very recently there was an issue complaining that what you are asking for is the default behavior :)
 https://github.com/NuGet/Home/issues/8983.

**Comment by cdmihai** [comment]
#8983 seems to complain about a potential bug with transitive selective packing of projects that define `GeneratePackageOnBuild `. It does not complain about the feature itself, but a bug with the feature. 

It is my understanding that if a project defines `GeneratePackageOnBuild=true`, then it gets packed, indifferent of its location in the p2p graph. This happens from visual studio, and from command line based builds of solutions. but does not happen if you don't use a solution (e.g. quickbuild style `dirs.proj` that only references the repo roots, and not the entire closure).

**Comment by nkolev92** [comment]
I am reading #8983 as saying it shouldn't be transitive. Which it isn't, but let's put that to that side :)

> It is my understanding that if a project defines GeneratePackageOnBuild=true, then it gets packed, indifferent of its location in the p2p graph

It was never implemented this way. Pack as a target only considers the current project. We've not done any work to make it apply transitively. 

> This happens from visual studio, 
NuGet does not implement the invocation there, but if this is happening, we should understand and fix it there. /cc @zivkan as hot seat.

> and from command line based builds of solutions
I'd imagine this happens only if you set the property globally. 

I understand where you are coming from because build gets run transitively, but I'd be hesitant to assume the same thing for the projects.

**Comment by cdmihai** [comment]
>It is my understanding that if a project defines GeneratePackageOnBuild=true, then it gets packed, indifferent of its location in the p2p graph
>It was never implemented this way. Pack as a target only considers the current project. We've not done any work to make it apply transitively.

What is the intended behaviour of `GeneratePackageOnBuild` in the following scenario, w.r.t. which projects get packed:
- A->B->C
- A and C have `GeneratePackageOnBuild=true` but B doesn't
- A.csproj is built with `msbuild /t:Build A.csproj`

What is the intended behaviour for the above scenario when there's also a solution present, and that one gets built with `/t:Build`

I'd expect both behaviors to be the same.

**Comment by nkolev92** [comment]
> A.csproj is built with msbuild /t:Build A.csproj

Pack forces a build, so A, B, C get build because of how build works, and because C has a GeneratePackageOnBuild it gets packed as well.
So:
* A.nupkg
* C.nupkg

> What is the intended behaviour for the above scenario when there's also a solution present, and that one gets built with /t:Build

Build gets run on all projects individually, A and C have a pack on build.
So:

A.nupkg
C.nupkg
[pack.zip](https://github.com/NuGet/Home/files/4289019/pack.zip)

I have verified this with a repro.

**Comment by cdmihai** [comment]
Ah, in my local repro C is crosstargeting, I forgot about that. In this case, would it be expected for C to produce a nuget package?
A.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\B\B.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```
B.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\C\C.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>

</Project>
```

C.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard1.6;</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
```

script to run
```ps1
Get-ChildItem -Recurse -Directory -Include bin | rm -force -recurse
dotnet msbuild /restore .\A\A.csproj
Get-ChildItem -Recurse -File -Include "*.nupkg" | ForEach-Object{ $_.FullName }
```

Output
```
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 264.62 ms for E:\delete\transitivePack\B\B.csproj.
  Restore completed in 264.61 ms for E:\delete\transitivePack\C\C.csproj.
  Restore completed in 264.62 ms for E:\delete\transitivePack\A\A.csproj.
  C -> E:\delete\transitivePack\C\bin\Debug\netstandard2.0\C.dll
  B -> E:\delete\transitivePack\B\bin\Debug\netstandard2.0\B.dll
  A -> E:\delete\transitivePack\A\bin\Debug\netstandard2.0\A.dll
  Successfully created package 'E:\delete\transitivePack\A\bin\Debug\A.1.0.0.nupkg'.
E:\delete\transitivePack\A\bin\Debug\A.1.0.0.nupkg
```

**Comment by nkolev92** [comment]
Great scenario :)
Yeah, that's where it'd differ. 
Only the inner build runs there, and pack is an outer build target, https://github.com/NuGet/NuGet.Client/blob/162e23520da60ead3868b48b097731b1e405a5e4/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L131.

**Comment by nkolev92** [comment]
While that is not super intuitive, I don't think we'd want to change the behavior.
We'd end up packing targetframework x n number of times in multi targetted projects.
It's a nature of the beast type of scenario.

**Comment by cdmihai** [comment]
One possible fix would be for the inner build to call the outerbuild with pack. The call would get cached between all the inner builds, so first one takes the hit and the other ones should be a quick no-op. But it makes the already complex build more complex

**Comment by nkolev92** [comment]
Maybe, but in general it feels too complex, and unless it's a blocking an important scenario, I'd say let's not mess with it :)

**Comment by nkolev92** [comment]
Feel free to close the issue if you agree.

**Comment by zivkan** [comment]
.NET team might not like the idea of an inner build causing an outer build, as it would slow down the development loop (change line of code, run debugger/test).

**Comment by cdmihai** [comment]
I agree, not a biggie, though it might surprise users switching between VS and non-solution command line, or users switching between quickbuild builds (with msbuild calling patterns similar to VS' solution build manager) and command line build. The quickbuild case is more severe because there's no solutions, just [msbuild native traversal files](https://github.com/microsoft/MSBuildSdks/tree/master/src/Traversal), so a commandline vanilla msbuild build will miss these packages.
