### ISSUE TITLE
net5: How will our insertions work?

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9253]
We need to make sure we understand any extra work that might be needed for our insertions into net5. I believe we are already doing these insertions, but in light of #9252, we might need to update documentation about expected test branches and such. This issue is mostly about making sure we understand everything and documenting anything we need to document.

**Comment by zivkan** [comment]
Is there a specific question?

Each of our official builds gets [published to the .NET Build Asset Registry (BAR)](https://github.com/NuGet/NuGet.Client/blob/69276891c4a2e391b3711c6b7d5276886a5d857b/build/vsts_build.yaml#L524-L533).

Insertion into the .NET SDK means that we [promote our build into a .NET channel](https://github.com/dotnet/arcade/blob/master/Documentation/BranchesChannelsAndSubscriptions.md). The orchestration system then creates, and where possible, automatically merges PRs in the appropriate repo (which for .NET 5, I believe is only dotnet/sdk).

**Comment by zkat** [comment]
So it sounds like this is basically taken care of? I mostly made this issue to do some due diligence to make sure everything was already taken care of, but it sounds like it is?

**Comment by zivkan** [comment]
yes, we've been inserting into both .net 5 and .net core 3.1 previous simultaneously.

**Comment by zkat** [comment]
Then we're all set here. Cheers :)
