### ISSUE TITLE
NuGetVersion.TryParseStrict() should return false if it fails to parse

### ISSUE THREAD

**Issue by VonOgre** [NuGet/Home#9255]
## Details about Problem
It seems that NuGetVersion.TryParseStrict() doesn't actually ever return false, which isn't ideal for a "Try" method. The implementation actually does check if it can parse to a SemanticVersion, but always returns true anyways...
https://github.com/NuGet/NuGet.Client/blob/bf9523d7b66f749f8709c8f082944db6a60f9153/src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs#L105-L115

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet.Versioning v5.4.0

## Detailed repro steps so we can see the same problem

var isValid1 = NuGetVersion.TryParseStrict("NotAVersion", out var parsed1);
// isValid1 == true, parsed == null

var isValid2 = NuGetVersion.TryParseStrict("", out var parsed2);
// isValid2 == true, parsed == null

var isValid3 = NuGetVersion.TryParseStrict("1.0.0", out var parsed3);
// isValid2 == true, parsed != null

**Comment by zivkan** [comment]
This looks like an easy issue for a community contribution. Tests should be added to `test/NuGet.Core.Tests/NuGet.Versioning.Test/NuGetVersionTest.cs`. At the moment there are only positive tests, so negative tests need to be added.

**Comment by VonOgre** [comment]
Indeed, I'd meant to do a fork and PR last night but got sidetracked, but I expect either tonight or tomorrow 👍
