### ISSUE TITLE
##[error]The nuget command failed with exit code(1) and  error(Response status code does not indicate success: 403 (Forbidden - User '241a50c0-fa7f-4dd6-a984-1d62b0d8951a' lacks permission to complete this action.  You need to have 'AddPackage'. (DevOps Activity ID: 0034C39F-1B85-459F-B6AD-8D472545C971)).) Finishing: NuGet Push   please let me know how to fix this issue 

### ISSUE THREAD

**Issue by anil88972** [NuGet/Home#9259]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment]
The error message says that you don't have permissions. Azure DevOps is a different product/service than NuGet, so I'm not at all an expert, but as it's another Microsoft product, I can help by pointing to documentation that might be helpful.

[This doc is about managing Azure Artifacts feed permissions](https://docs.microsoft.com/en-us/azure/devops/artifacts/feeds/feed-permissions?view=azure-devops#editing-permissions-for-a-feed). You'll need to check what user name user "241a50c0-fa7f-4dd6-a984-1d62b0d8951a" is. I don't know if it's the user that started the build, or if it's the account that the CI agent machine is running as, or if it's some other account. But that's the account that NuGet appears to have authenticated as to Azure DevOps.

If you configured NuGet to connect with a specific personal access token (PAT), make sure that that the PAT has the correct scopes. However, if you use the [Azure Pipeline NuGet task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/nuget?view=azure-devops), I think it sets up the PAT automatically, so you just need to make sure that feed permissions are correct.

**Comment by nkolev92** [comment]
Closing per the above comment.
