### ISSUE TITLE
No keyboard gestures to edit the sources in the NuGet Package Manager Options window. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9262]
Affected Branch: 
Affected Build: 
Affected Product Language: 

Steps to reproduce:

Go to the Available Package Sources view. 

Use the arrow keys to navigate through the list of sources. When getting to the bottom source, you can navigate to the edit source section. There is no gesture to allows you to change the first n-1 sources. 

This has always been a problem (since 14.x)

**Comment by donnie-msft** [comment]
@nkolev92 did you try the `Home` key? I'm not clear on the problem or suggestion.

**Comment by nkolev92** [comment]
Home key leads you to the top, not what you need.

I think this is fixed (or maybe never was a problem, not sure, this was from an old accessibility pass.). 

The gesture is the following: 

* You can use the arrows to navigate. 
* When on a specific source, use `Tab`, that should take you to the editable area.

**Comment by donnie-msft** [comment]
No repro Version 16.8.0 Preview 6.0
