### ISSUE TITLE
nuget.exe pack for SDK multi targeting projects fails.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9266]
## Details about Problem

NuGet product used: NuGet.exe 

NuGet version: 5.4.0

OS version: win10 

Worked before? No sure

## Detailed repro steps so we can see the same problem

1. Download and unzip the attached project

2. Run: nuget.exe restore TestConsoleApp2.csproj

3. Run: nuget.exe pack TestConsoleApp2.csproj -Build

Result: 
Could not find a part of the path '***\TestConsoleApp2\bin\Debug\TestConsoleApp2\bin\Debug'.

### Observation
1. If the project does not use the TargetFrameworks but TargetFramework everything works fine.
2. In case that TargetFrameworks is used the project created does not have a TargetPath (https://github.com/NuGet/NuGet.Client/blob/5433d816f748d4ad78b75fc320397d8117f57771/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L480)
 but an output path = bin\debug this leads to teh new target path mentioned in the output (https://github.com/NuGet/NuGet.Client/blob/5433d816f748d4ad78b75fc320397d8117f57771/src/NuGet.Clients/NuGet.CommandLine/Commands/ProjectFactory.cs#L487)

In case that the TargetFramework is use the project has a TargetPath

### Sample Project

[TestConsoleApp2.zip](https://github.com/NuGet/Home/files/4299591/TestConsoleApp2.zip)

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/4491. 
PackageReference project pack with NuGet.exe is not well supported.
