### ISSUE TITLE
"Upgade Nuget Version" on RMB menu breaks selected project!

### ISSUE THREAD

**Issue by Braineeee** [NuGet/Home#9274]
![UpgadeNuget](https://user-images.githubusercontent.com/15795591/75854401-f8e50600-5da4-11ea-9783-500a0331b990.PNG)

Steps to reproduce:

1. Select project in Solution Explorer withh LMB.
2. RMB click on it.
3. Scroll down the menu that appears to the option "Upgade Nuget Version" and take it.
5. Message box appears. Project broken.

This mesage box appears after RMB clicking on the project name and selecting the menu option "Upgade Nuget Version" (this is verbatim for the menu).

This forcibly breaks the project. I don't know what to do about this...

**Comment by donnie-msft** [comment]
Could you show a screenshot of the menu option you're referring to? Are you referring to the option to Migrate Project to Package Reference?  

Is your project Package Reference? Including a simple sample project will help us understand your scenario.

**Comment by Braineeee** [comment]
I am sorry I have quit using Xamarin due to a number of crappy issues. Your software cost me a full week of time trying to get a build up and going. I could have finished it in that amount of time, or spent more than 6 hours actually writing code instead of monkeying with stupid settings just to get a singular build.

I have no idea how to reproduce this. I had the NuGEt pkg manager installed and also Plugin.BLE installed when it occurred. I had right-clicked on the project and down near the bottom middle is the option mentioned which breaks the project....
