### ISSUE TITLE
Restore NuGet Packages option not always visible

### ISSUE THREAD

**Issue by ThomCBlackwellBSS** [NuGet/Home#9275]
After updating Visual Studio 2019, the Restore NuGet Packages menu in the Solution explorer can mysteriously go away. I remember reading something describing how to get that option back, but I don't remember where. That information should be added to this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b20c46-c5f1-3a2a-738d-8aa8e69cf10c
* Version Independent ID: 7055e752-859b-6106-6802-70010d0305d9
* Content: [NuGet Package Restore](https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore)
* Content Source: [docs/consume-packages/Package-Restore.md](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/consume-packages/Package-Restore.md)
* Product: **nuget**
* GitHub Login: @karann-msft
* Microsoft Alias: **karann**

**Comment by donnie-msft** [comment]
Check these instructions and let me know the state of your settings mentioned here:

https://docs.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-packages-manually-using-visual-studio

**Comment by donnie-msft** [comment]
Closing due to no response. Docs link above should answer the question.
