### ISSUE TITLE
NuGet official builds aren't publishing to a BAR channel anymore

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#9279]
The last successful build that updated the `.NET Core 5 Dev` channel was https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3506459. Since then nuget bits aren't flowing anymore to dotnet/sdk or any subscriber.

```
C:\git\runtime>darc get-build --id 45163
Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        d39e857e6b1265d1b4990cbe660e2a0ad259e0cf
Build Number:  5.6.0.6492
Date Produced: 3/7/2020 7:32 AM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3533068
BAR Build Id:  45163
Channels:

C:\git\runtime>darc get-build --id 44314
Repository:    https://github.com/NuGet/NuGet.Client
Branch:        dev
Commit:        64f2febf7d1de8b0228eca5afed97a96c5a30bba
Build Number:  5.6.0.6478
Date Produced: 2/27/2020 2:21 AM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=3506459
BAR Build Id:  44314
Channels:
- .NET Core 5 Dev
```

cc @mmitche @nkolev92 @JohnTortugo

**Comment by ViktorHofer** [comment]
I don't know how BAR determines which channel the build assets is for but I added a default channel for the dev branch meanwhile:

```
C:\git\runtime>darc add-default-channel --channel ".NET Core 5 Dev" --branch dev --repo https://github.com/NuGet/NuGet.Client

(1125) https://github.com/NuGet/NuGet.Client @ dev -> .NET Core 5 Dev
```

**Comment by ViktorHofer** [comment]
Submitted https://github.com/dotnet/sdk/pull/10804 to fix this in the meantime.

**Comment by ViktorHofer** [comment]
Keeping this open until I verified this indeed fixes the issue.

**Comment by zivkan** [comment]
Is the problem just that we're using an old version of the relevant packages?

Would this fix it?
https://github.com/NuGet/NuGet.Client/compare/dev-zivkan-update-dnc-bar-publishing

Since we don't use arcade, I really don't understand how the whole flow works, so I don't know what's going wrong from our end or what we can do to fix it.

**Comment by ViktorHofer** [comment]
> Is the problem just that we're using an old version of the relevant packages?

Updating to a newer infra is definitely advisable but the preferred solution is that NuGet uses the common Arcade publishing infra. Matt told me that John will work with you on that.

I believe by setting a default channel I already fixed the dependency flow issue. I can verify with the next official build.

**Comment by ViktorHofer** [comment]
OK sorry for the noise, we can close this issue. I didn't know that NuGet is promoting their builds and not publishing live: https://github.com/NuGet/NuGet.Client/pull/3285#issuecomment-596710142.

I'll remove the default-channel that I added for nuget.
