### ISSUE TITLE
Latest version is not present using the NuGet API

### ISSUE THREAD

**Issue by darmalovan** [NuGet/Home#9291]
## Details about Problem
 I'm seeing a discrepancy in getting the latest version of a package between the NuGet website and the NuGet API.

## Detailed repro steps so we can see the same problem

1. Going to the NuGet web site for the `EntityFrameworkCore.Relational` package https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Relational/
the latest version is `3.1.2`. 

2. Using the API https://api.nuget.org/v3/registration3/microsoft.entityframeworkcore.relational/index.json I am getting `3.1.1` as the latest version.

I tried also to use the api.nuget.org/v3/registration3-gz-semver2 endpoint without any luck.

The search web site says `3.1.2` is the latest version:
![image](https://user-images.githubusercontent.com/5316748/76555697-d50a7a00-64a0-11ea-8c79-01e7b5c367dc.png)

Would love for any advice here :)

**Comment by donnie-msft** [comment]
Hi! I'm sending this over to the Server team to take a look.

**Comment by donnie-msft** [comment]
Issue moved to [NuGet/NuGetGallery #7866](https://github.com/NuGet/NuGetGallery/issues/7866) via [**ZenHub**](https://www.zenhub.com/)
