### ISSUE TITLE
NuGet plug-in API fails when doing simultaneous restores

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#9292]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx): 5.5

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Execute parallel restores that require authentication or other plug-in
2. Restore some times fails with an error like:
```
Problem starting the plugin 'PATHTOPLUGIN'. The process cannot access the file '%LocalAppData%\NuGet\plugins-cache\2a163a4397322a32ccf62440e8b2c089004a49c0\9d08616bea28af0d943074cf5bb029f7a6ac7aaf.dat-new' because it is being used by another process.
```

I suspect that the plug-in caching mechanism does not currently support this kind of concurrency.

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol/Plugins/PluginCacheEntry.cs

This was reported by an internal team that is doing restores in a very custom way.  We will probably just not use an auth plug-in for now to work around the issue.

**Comment by nkolev92** [comment]
Do you have the full stack trace? 
We actually had a very coarse locking and it caused perf issues :)
Since then we've switched it to a more granular one: https://github.com/NuGet/NuGet.Client/blob/b6ba5908951c172ed7df75e3074a7af409f743d7/src/NuGet.Core/NuGet.Protocol/Plugins/PluginManager.cs#L208. 

So it might be possible to improve the cross process locking.

**Comment by jeffkl** [comment]
I don't have a stack, the exception is caught by PluginManager and only the message is logged.  We probably need coarse locking for this plug-in cache file, not the whole operation.

**Comment by nkolev92** [comment]
@jeffkl 

Is there a specific customer impacted by this behavior?

**Comment by jeffkl** [comment]
[BuildXL](https://github.com/microsoft/buildxl) is the team who reported it.  They are doing some fancy stuff around scheduling of processes which causes the issue to happen.

**Comment by jeffkl** [comment]
No upvotes or other reports of this happening, so closing this for now.
