### ISSUE TITLE
Static Graph restore won't warn for invalid projects

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9300]
Have a sln with 2 projects, one restoreable, the other without the NuGet.targets. 

Regular restore will warn https://github.com/NuGet/NuGet.Client/blob/b6ba5908951c172ed7df75e3074a7af409f743d7/src/NuGet.Core/NuGet.Build.Tasks/NuGet.targets#L282-L292, while static graph restore quietly skips the project. 

cc @jeffkl 

We need to understand what we want the experience to be.

**Comment by jeffkl** [comment]
This would be easy to add so yeah we just need to brainstorm on the experience
