### ISSUE TITLE
MSBuild Restore is flaky (with corext bridge)

### ISSUE THREAD

**Issue by zachhats** [NuGet/Home#9314]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): msbuild /restore

NuGet version (x.x.x.xxx): unknown (CloudBuild)

dotnet.exe --version (if appropriate): n/a

VS version (if appropriate): n/a

OS version (i.e. win10 v1607 (14393.321)): Unknown (CloudBuild)

Worked before? If so, with which NuGet version: no

## Detailed repro steps so we can see the same problem

[This](https://cloudbuild.microsoft.com/build/63e1c919-11df-45b2-ba72-7f082a0a0eae?bq=CDP_PowerQuery-Web) is an example of corext init timing out. From talking to a colleague it seems like msbuild is crashing/hanging when trying to build the list of projects to be restored. msbuild was ran with /bl so there are dump files of the processes here. This is the most common issue we are facing.

[This](https://cloudbuild.microsoft.com/build/b059eaf8-61f2-4c8f-a3f1-11703cd25210?bq=CDP_PowerQuery-Web) is an example where the restore fails. What's odd is there are no warnings or errors in the restore.log. This is less common.

### Verbose Logs

Included above

### Sample Project

https://msazure.visualstudio.com/One/_git/PowerQuery-Web/

**Comment by zachhats** [comment]
For context, [here](https://mw-s7.cloudbuild.microsoft.com/dir?path=%5C%5CMW1SCH101331922%5Cd$%5Cdbs%5Csh%5Cappq%5C0316_125328_log&stampId=MW_S7) is an example of a successful build.

More info from colleague:
----------------------------
I personally cannot understand why they behave differently.
This is what happens when the build succeeds:
![restore1](https://user-images.githubusercontent.com/4756977/76911033-ea025700-686c-11ea-9c73-b8952345392e.png)


While this is when it fails:
![restore2](https://user-images.githubusercontent.com/4756977/76911041-f1296500-686c-11ea-9b11-d1dcd55390e8.png)
 

As you can see, for some reason when it fails, it doesn't complete all the steps of _GenerateRestoreProjectPathWalk. I would expect it to set _GenerateRestoreProjectPathWalkOutputs as it does when the build succeeds.

**Comment by zachhats** [comment]
Talked offline with Nikolche, we are going to try out the static graph restore but we're currently blocked because corext is missing Nuget.Builds.Tasks.Console.dll.

**Comment by rrelyea** [comment]
Should this issue stay open? or close for now, and reopen if necessary?
/cc @nkolev92

**Comment by nkolev92** [comment]
I'll let @zachhats make the call there.
We *think* static graph makes this better, but we have not confirmed it yet. 

I also think it's ok to potentially close it for now and reopen if necessary if @zachhats agrees.

**Comment by zachhats** [comment]
@rrelyea @nkolev92 sure, closing and will reopen if static graph doesn't help
