### ISSUE TITLE
Who can help me solve this problem? I don't know how to do it.I can't understand nuget's documentation.

### ISSUE THREAD

**Issue by NMSAzulX** [NuGet/Home#9317]
https://github.com/dotnet/roslyn/issues/42439#event-3135330568

**Comment by kartheekp-ms** [comment]
Please refer to [NuGet doc](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#include-msbuild-props-and-targets-in-a-package) to learn more about how to include `msbuild props and targets file in a package`. If you need further assistance, then please reopen or create new issue and provide issue description as per [this](https://github.com/NuGet/Home/issues/new) template.
