### ISSUE TITLE
Custom Nuget Package Issue with TFS

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#932]
I have wrapped up my java script code in Nuget package for distribution.Other team members can use this code by installing the nuget package created by us. this package contains nested folder structure and bulk java script  files.

I have created this package by using Nuget Package Explorer. Hosted it locally and run the command from package console. "install-package <packagename>".

 It works very well but the issue comes on TFS. When someone install the package on TFS project, it throws weird error "Collection Was Modified; Enumeration Operation May Not Execute." Al tough the package in installed with this error.

This is embracing  because we did everything but in the end it fails if we can not distribute that. Alternatively i have used batch file for that.

I have already posted an issue on the following url:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/3c9e8980-8ddd-4479-9e81-6423c9556c40/install-nuget-package-error-collection-was-modified-enumeration-may-not-execute-in-tfs?forum=tfsworkitemtracking&prof=required

They suggesting me to contact with Nuget team.
Is this a good practice to wrap up thousands of java scripts files in a package?  
Please look into this, i hope will get some resolution here.......

(Copied from https://github.com/NuGet/NuGetGallery/issues/2581 - @RajivDadwal)

**Comment by yishaigalatzer** [comment]
Please let us know what version of visual studio you are using?

Aside: Long term we are recommending to move away from NuGet for "content" packages, particularly javascript and use bower instead. ASP.NET 5 removed support for content completely and that would be the way long term.

**Comment by RajivDadwal** [comment]
Thanks for the reply,
I am using visual studio 2013.

I explored a bit about bower. It seems to be dependent on github. can i host my package other than github, I want to host  my js, css or image files in internal network, so that others can download that content in their projects. Earlier i was using the Nuget Packages for that.

**Comment by csharpfritz** [comment]
You can configure an internal Bower registry and host your privte bower
package in a private git repository:
https://github.com/bower/registry




Jeff

**Comment by yishaigalatzer** [comment]
This bug doesn't have enough information for reproduction. And we don't plan to fix this kind of issues in 2013.

If you have a clear repro in visual studio 2015 + NuGet 3.2 (or newer), please re-open and post the failing package here.
