### ISSUE TITLE
[Test Failure] The installed version is inconsistent with the embedded icon in the solution level PM UI for one package id with multiple versions installed

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9321]
## Details about Problem
NuGet version: NuGet Client Dev\5.6.0.6525
VS Version: Master\29919.118
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create a solution with two C# Console App (.NET Framework 4.8) (called ConsoleFW1 and ConsoleFW2) in VS. 
2.	Open the solution level PM UI.
3.	Select the remote feed “nuget.org” in the “Package source” dropdown box in the PM UI and type “Text2Xml.Lib” in the search box of Browse tab. 
4.	Install “Text2Xml.Lib version **1.0.0**” into project **ConsoleFW1** and install “Text2Xml.Lib version **1.1.1**” into project **ConsoleFW2**.
5.	Go to the “Browse”/“Installed”/”Updates”/“Consolidate” tab.
## Expected
The installed version should be consistent with the embedded icon. Every tab should show the latest installed version instead of lowest.
## Actual
The installed version is inconsistent with the embedded icon as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/77164869-1c6db780-6aec-11ea-91b8-29612cf5ad40.png)
## Note
It is not a regression.

**Comment by dominoFire** [comment]
@v-luzh Followed the instructions to repro the issue. But, I don't understand the issue. Could you help me indicating what are the expected scenarios in each tab?

Version details:

- 1.0.0: It does not have an icon (none)
- 1.1.1: It has an embedded icon (brown)
- 1.1.4: Latest version available in nuget.org (green)

Tab scenarios:

Browse: It shows latest version available in feed: 1.1.4 (green)

![image](https://user-images.githubusercontent.com/1192347/80557871-30c78e80-898d-11ea-9c07-0aba28814244.png)

Installed: It shows latest version installed: 1.1.1 (brown)

![image](https://user-images.githubusercontent.com/1192347/80557887-38873300-898d-11ea-8472-c77205bb3bff.png)

Updates: It shows latest version available on the feed: 1.1.4 (green)

![image](https://user-images.githubusercontent.com/1192347/80557915-55236b00-898d-11ea-84e0-d83bab243c80.png)

Consolidate: It shows the latest installed version: 1.1.1 (brown)

![image](https://user-images.githubusercontent.com/1192347/80557973-856b0980-898d-11ea-85cd-c9342936081d.png)

**Comment by v-luzh** [comment]
@dominoFire You can find that the icon and the installed version number are inconsistent. The icon shows is version 1.1.1 but the installed version shows on the right is 1.0.0 as below. The issue doesn't repro in project-level PM UI, but repro in solution-level PM UI. 
![image](https://user-images.githubusercontent.com/20632625/80676188-d04d6400-8ae8-11ea-9575-a19678de4edd.png)

**Comment by dominoFire** [comment]
@v-luzh Thanks for the clarification! A PR is on the way for fixing this issue.

**Comment by v-luzh** [comment]
Fixed on VS Master\30209.143 + NuGet Client Dev\5.7.0.6643. Thanks.
