### ISSUE TITLE
MsBuild version picking works badly on some non-english cultures

### ISSUE THREAD

**Issue by ievgennaida** [NuGet/Home#9322]
I have the latest sources for the NuGet (20.03.2020)
and for me **TestMsBuildPathFromVsPath** is failing with an error:
```
    Expected: ···a264bf76\MSBuild\15.0\bin
    Actual:   ···a264bf76\MSBuild\15.1\Bin
```
""\15.0\" is selected instead of "15.1" while the number cannot be parsed as float."

Problem is that the wrong MSBuild path is selected for a culture where ',' is used as float separator.

How to reproduce:
1. Change current regional settings to be with a culture where ',' is used.
![image](https://user-images.githubusercontent.com/17121033/77196169-1a532b00-6ae3-11ea-85ed-45df3d75fa19.png)

2. Run the test:

The fix is easy InvariantCulture should be used. Ex: MsBuildToolset.cs
if (float.TryParse(dirName, NumberStyles.Float, **CultureInfo.InvariantCulture**, out dirValue))

**Comment by rrelyea** [comment]
Have fix running tests in dev-rrelyea-fixMsBuildToolsetWithInvariantCulture branch of nuget.client
Assuming all works well, will add tests for this problem, and complete.

**Comment by ievgennaida** [comment]
@rrelyea Thanks for the quick response. I am not sure that it was only one place that leads to an error. I would really suggest to change the culture globally and execute all the tests. Thanks in advance!
