### ISSUE TITLE
Doesnt work while trying to add theme dictionaries

### ISSUE THREAD

**Issue by touseefbsb** [NuGet/Home#9323]
I tried to add custom theme and some control styles through a dictionary Themes.xaml in my component project and it was working as expected when trying directly but when I upload it to nuget and consume from there, it cant find resources.
More details : https://stackoverflow.com/questions/60722735/uwp-styles-and-themes-in-a-nuget-cannot-find-resource-file/60722835?noredirect=1#comment107495661_60722835

[Create NuGet Packages for the Universal Windows Platform](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages-cs#feedback)

**Comment by rrelyea** [comment]
By looking at that stackoverflow - looks like you solved your problem.
If our documentation has any deficiencies...please navigate to that page in the documentation...scroll to the Feedback section...and report feedback about "this page".
