### ISSUE TITLE
[CPVM] Tools available to evaluate the Directory.Packages.props for possible downgrades.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9324]
If a downgrade happens because of a transitive dependency presented in Directory.Packages.props an error will be produced at the restore.

This issue is to open the discussion to make available tooling around the evaluation of the  Directory.Packages.props without the context of a specific project and present the errors before an eventual package restore.

**Comment by aortiz-msft** [comment]
Bulk-closing old issues for CPVM.
