### ISSUE TITLE
.net core lib

### ISSUE THREAD

**Issue by furesoft** [NuGet/Home#9327]
is there a .net library to interact with nuget to use nuget as update server?

**Comment by rrelyea** [comment]
Please describe your goals in more depth. 
What are you trying to update? 
Bringing binaries down to your client app?
Bringing binaries down to a server?
are you trying to update some files/binaries during runtime, instead of during the normal build time that nuget is usually used?

**Comment by furesoft** [comment]
i want to bring down my binaries to my client app and at runtime

**Comment by rrelyea** [comment]
That is documented here: 
https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk#download-a-package

**Comment by furesoft** [comment]
thanks alot
