### ISSUE TITLE
How to use the consolidate/centralize command?

### ISSUE THREAD

**Issue by apobekiaris** [NuGet/Home#9328]
How do I access the command at 

https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions#next-steps-post-mvp

i get `error: Unrecognized command or argument 'consolidate/centralize'`

**Comment by rrelyea** [comment]
Central Version Package Management is a feature still being developed. @cristinamanum would be able to point you to which issue to stay tuned to...so you know when it first becomes available in preview form.
