### ISSUE TITLE
Show recent packages on UI for Manage Packages

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#933]
(was: Recent Packages on Gallery UI to reduce server roundtrip and usability)

Hello guys, 

I was on your site/blog and saw a post about the issues with servers.
I'd like to suggest an feature that was on my mind for a long time, I didn't find anything about where should I sent feature request, so I'm sending it here.

On "Manage Nuget Gallery" UI, Would be nice an option "Recent packages", it's very common to reuse the same package among all projects on solution, instead of searching the package every time, we could reuse the same package downloaded before, will be faster an easier for us and will release a lot of resources from your Search Servers, CDN and API.

I know that I can manage the packages from solution, but would be easier if this option was on UI, because we apply direct on the project, through solution we have more steps to perform this task.

Thanks

(copied from https://github.com/NuGet/NuGetGallery/issues/2577 - @guibirow)

**Comment by guibirow** [comment]
Sorry to post on wrong place, Thanks a lot to fix.
Will increase our productivity, sometimes I need to do this at least 30 to 50 times a day on new projects.
