### ISSUE TITLE
Missing format default on `dotnet nuget list source`

### ISSUE THREAD

**Issue by jschwanz** [NuGet/Home#9337]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.5.0

OS version (i.e. win10 v1607 (14393.321)): win10 v1909, windows-2019 (on Azure Pipelines)

Worked before? If so, with which NuGet version: 5.4.0

## Detailed repro steps so we can see the same problem

1. Run "nuget sources list"

With 5.4.0 (and earlier) this produces the detailed output of the sources list. With 5.5.0 it now produces this error:

```
invalid value for --format: None. Allowed values: 'detailed' or 'short'
```

The default format of 'detailed' is missing, and this is affecting downstream projects like PowerShellGet's Register-PSRepository cmdlet.

**Comment by jschwanz** [comment]
Here is the line in Register-PSRepository that is now not working:

https://github.com/PowerShell/PowerShellGetv2/blob/development/src/PowerShellGet/public/psgetfunctions/Register-PSRepository.ps1#L244

**Comment by rrelyea** [comment]
Thanks for the catch. Fix in PR now. Likely, we ship a 5.5.1 version of nuget.exe - but need approval first.
