### ISSUE TITLE
VS2015 Nuget Powershell does not have a Aggregate Source (All)

### ISSUE THREAD

**Issue by maartenba** [NuGet/Home#934]
In VS2013 there was a "All" source option, this does not exist in VS2015. 
With an additional private feed now many commands fail (like reinstalling all packages, for example after changing from .NET 4.0 to 4.5)

(copied from https://github.com/NuGet/NuGetGallery/issues/2582 - @biohazard999)

**Comment by danliu** [comment]
verified that this does not repro with latest RTM build. Now the active package source is not being honored for update-package and update-package -reinstall scenarios. It's going through all of the package sources for resolution.

**Comment by danliu** [comment]
Close the bug as Fixed.
