### ISSUE TITLE
Error when a Project has CPVM enabled but there are not any PackageVersion items defined

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9341]
## Details about Problem
This is a new feature request.

A project can be opted-in but it may not have any PackageVersion elements loaded. Currently there will be a NU1604 warning. This issue is to track if there will be a different error/warning needed. 

Proposal:
When a project is optedin CPVM error on PackageReference included but no corresponding PackageVersion exists.

**Comment by anangaur** [comment]
I agree to the last part where PR should be accompanied by PV, else it’s an error. The converse may not be true (obvious I guess). 

If CPVM is opted in, there could be no PV or PR altogether which IMO is fine
