### ISSUE TITLE
ProjectReferences clashing with PackageReference in multi-targeting project restore

### ISSUE THREAD

**Issue by ViktorHofer** [NuGet/Home#9354]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): dotnet.exe

NuGet version (x.x.x.xxx): 5.6.0-preview.2.6508

dotnet.exe --version (if appropriate): `5.0.100-preview.3.20170.6`

OS version (i.e. win10 v1607 (14393.321)): ` 10.0.19587`

### Error

```
C:\git\runtime\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable>dotnet restore
  Determining projects to restore...
C:\git\runtime4\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable.csproj : error NU1201: Project System.Runtime is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Project System.Runtime supports: net5.0 (.NETCoreApp,Version=v5.0)
C:\git\runtime4\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable.csproj : error NU1201: Project System.Runtime.InteropServices is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Project System.Runtime.InteropServices supports: net5.0 (.NETCoreApp,Version=v5.0)
  Restored C:\git\runtime4\src\libraries\System.Collections\ref\System.Collections.csproj (in 360 ms).
  Restored C:\git\runtime4\src\libraries\System.Runtime\ref\System.Runtime.csproj (in 360 ms).
  Restored C:\git\runtime4\src\libraries\System.Runtime.InteropServices\ref\System.Runtime.InteropServices.csproj (in 360 ms).
  Failed to restore C:\git\runtime4\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable.csproj (in 362 ms).
```

### Sample Project

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netcoreapp5.0;netstandard1.3</TargetFrameworks>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="System.Collections.Immutable.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp5.0'">
    <ProjectReference Include="..\..\System.Collections\ref\System.Collections.csproj" />
    <ProjectReference Include="..\..\System.Runtime\ref\System.Runtime.csproj" />
    <ProjectReference Include="..\..\System.Runtime.InteropServices\ref\System.Runtime.InteropServices.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.3'">
    <PackageReference Include="System.Memory" Version="$(SystemMemoryVersion)" />
  </ItemGroup>
</Project>
```
from: https://github.com/dotnet/runtime/pull/33553

#### Steps:
```
git clone https://github.com/ViktorHofer/runtime
git checkout RestorePhase2-respin
cd runtime\src\libraries\System.Collections.Immutable\ref\System.Collections.Immutable\
..\..\..\..\dotnet restore
```

@nkolev92 @rrelyea @ericstj can someone please help me understand why the ProjectReferences are clashing with the PackageReference even though they are imported on different targets (netcoreapp5.0 vs netstandard1.3). Why is the closure here expanded to the full set?

The package reference has a transitive dependency on the same assemblies as the ProjectReferences (System.Runtime, etc.):

![image](https://user-images.githubusercontent.com/7412651/77822351-11b9b080-70f2-11ea-8289-4979b3d34218.png)

**Comment by ViktorHofer** [comment]
cc @jeffkl.

Probably connected to what @nkolev92 mentioned [here](https://github.com/NuGet/Home/issues/8213#issuecomment-502787749):

> Yes, NuGet always prefers ProjectReference over PackageReference.

**Comment by rrelyea** [comment]
@ViktorHofer  - steps aren't correct. line 2 fails without a cd into runtime dir. then 3rd line needs runtime removed, and the last directory doesn't exist on my machine.
so i'm not really confident with the last command.
can you clean that up, so we are chasing the right thing?

**Comment by nkolev92** [comment]
@ViktorHofer Can you update the instruction per @rrelyea's request?

**Comment by nkolev92** [comment]
Closing as we have not heard back from the customer. 
@ViktorHofer If you have repro steps, we'll be happy to reconsider.
