### ISSUE TITLE
NuGet.exe 5.x on machines that don't have .NET runtime version 4.7.2  installed

### ISSUE THREAD

**Issue by bo-tu** [NuGet/Home#9356]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):  5.5.0

dotnet.exe --version (if appropriate):

VS version (if appropriate):  MS BuildTools 2017

OS version (i.e. win10 v1607 (14393.321)):  windows server 2012

Worked before? If so, with which NuGet version:  yep,  it works for nuget cli v5.4.0

## Detailed repro steps so we can see the same problem

1.  In TeamCity,  I run "nuget restore" in a runner of "MSBuild",  then it will restore nuget pkgs according to MSBuild file.

2. Then get errors as below,
[Exec] MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin'.
[21:17:16][Exec] C:\buildAgent\temp\buildTmp\NuGetScratch\iheve45x.nxo.nugetrestore.targets(438, 5): error MSB4018: The "GetRestoreProjectStyleTask" task failed unexpectedly. 
[Exec] C:\buildAgent\temp\buildTmp\NuGetScratch\iheve45x.nxo.nugetrestore.targets(438, 5): error MSB4018: System.TypeLoadException: Could not load type 'System.ValueTuple`3' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
at NuGet.Build.Tasks.GetRestoreProjectStyleTask.Execute() 
at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by rrelyea** [comment]
@jeffkl - related to your change?
Does it not work well on older .NET Framework, where it worked fine with 5.4.0?

@bo-tu -can you tell us which version of .NET Framework you are running on that server?

**Comment by jeffkl** [comment]
I don’t think it has to do with my change. ValueTuple has been around a long time

https://apisof.net/catalog/System.ValueTuple%3CT1,T2,T3%3E

**Comment by rrelyea** [comment]
Jeff's pointer said ValueTuple is in .net framework 4.7 and later.

According to: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies
Server2012 has .NET Framework 4.5 by default... and later versions are installable.

If this is the problem (running nuget.exe on .net 4.5), should nuget.exe complain that it needs a newer framework version.

**Comment by bo-tu** [comment]
1. We have multiple  .NET Frameworks installed on the windows 2012 server,  please refer this attachment. 
<img width="1002" alt="Screen Shot 2020-03-31 at 8 49 29 AM" src="https://user-images.githubusercontent.com/29054217/77955472-bfb09f00-732c-11ea-849a-4cbd45fbdd02.png">

2.  Also,  I attached my build step in TeamCity.  Sorry that I'm not sure which .NET Framework is used by nuget.exe.  I just rollback nuget.exe from v5.5.0 to v5.4.0,  then fixed this issue.
<img width="706" alt="Screen Shot 2020-03-31 at 8 52 24 AM" src="https://user-images.githubusercontent.com/29054217/77955640-056d6780-732d-11ea-82e5-235b7e895465.png">

**Comment by rrelyea** [comment]
@bo-tu - .net framework targetting packs are used during compilation. I'm asking about the .net framework runtime version installed on your CI. See https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed for details on how to determine which version is installed on that machine.
can you please determine that?

**Comment by nkolev92** [comment]
@bo-tu Did you get a chance to look at @rrelyea's comment [here](https://github.com/NuGet/Home/issues/9356#issuecomment-606218641)

**Comment by papeh** [comment]
I'm getting the same problem.
NuGet product used: NuGet.exe
NuGet version (x.x.x.xxx): 5.5.1
dotnet.exe --version (if appropriate): 2.1.509
VS version (if appropriate): 2017 (msbuild v15.9.21.664)
OS version: Windows 7 Pro SP1 (6.1.7601)
.NET version from HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full: Version 4.6.01055 (Release 394271)

Edit: installing Windows Updates fixed this problem for me.

**Comment by nkolev92** [comment]
Just summarizing all the information here:

* NuGet 4.x/VS 2017 was built for .NET Framework 4.6.2, so it requires the 4.6.2 runtime or later
* As @rrelyea mentioned, NuGet.exe in 5.x needs the 4.7.2 runtime to work
* The value tuples are available starting with .NET Framework 4.7.0

So the solution here is:

* Install .NET 4.7.2 runtime. 

@papeh, @bo-tu can you please try that. 

Unclear why NuGet didn't display any early warnings.

**Comment by nkolev92** [comment]
Closing this as per the last comment. 
Please install the .NET Framework 4.7.2 runtime.
