### ISSUE TITLE
StockSharp 5.0.0 не доступен для скачивания через Nuget

### ISSUE THREAD

**Issue by mazlov1989** [NuGet/Home#9360]

**Comment by heng-liu** [comment]
Hi, thanks for reporting this issue.
Are you referring to [StockSharp package](https://www.nuget.org/packages/StockSharp/) from source NuGet.org? If so, I can only see the highest available version is 4.4.16

**Comment by mazlov1989** [comment]
Но в NuGet.org версия 4.4.16 указана как устаревшая. К тому же в релизе на GitHub последней версией числится 5.0.0

**Comment by heng-liu** [comment]
So are you using Github as the source? If so, could you follow the instructions as follows?
https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages#authenticating-to-github-packages

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages#installing-a-package

By the way, could you please use English? Thanks!

**Comment by heng-liu** [comment]
May I know if your problem is solved? Thanks!

**Comment by zivkan** [comment]
We don't support individual packages (unless it's one of our own). Please contact the package author/owner.
