### ISSUE TITLE
csproj: how to pack at build platform-specific native assemblies

### ISSUE THREAD

**Issue by JosepBalague** [NuGet/Home#9361]
Microsoft Windows [Version 10.0.18363.720]
VS 2019 16.5.1

Hi,

I created a netstandard 2.0 project with this structure:

![imatge](https://user-images.githubusercontent.com/4932314/77951807-eb02a200-72ca-11ea-88e6-c2cc44aafff9.png)

When I consume it in an Console Core 3.1 x86 project, output bin has this structure:

\bin\x86\Debug\netcoreapp3.1\runtimes\ plus all content of above solution blue square

The problem here is native x86 dlls are not found and an exception is raised in my code.

if I create an x86 folder (in \bin\x86\Debug\netcoreapp3.1\) and copy in this new x86 folder dlls contained in runtime/win-x86/native, code works fine.

How can I pack at build platform-specific native assemblies? or is the issue in the consumer?

Thanks

**Comment by JosepBalague** [comment]
Any update?

**Comment by JosepBalague** [comment]
Can anyone help?

**Comment by nkolev92** [comment]
Hey @jmroyb 
Would you be able to provide a sample project?
It'll help us repro the exact issue you are seeing and provide suggestions.
