### ISSUE TITLE
Nuget does not add files to SDK-style project

### ISSUE THREAD

**Issue by lanyizi** [NuGet/Home#9364]
## Details about Problem

NuGet product used: Visual Studio UI

NuGet version: 5.4.0

dotnet.exe --version: 3.1.101

VS version: VS Community 2019 - 16.4.6

OS version: Windows 10 1909 18363.720

## Detailed repro steps so we can see the same problem

1. This package: https://www.nuget.org/packages/WPFThemes.DarkBlend/1.0.8/
(https://github.com/DanPristupov/WpfExpressionBlendTheme) should be supposed to add some files to my project, but I'm using the new SDK-style project file, and looks like it failed to add files

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...):  [log.txt](https://github.com/NuGet/Home/files/4406561/log.txt)

**Comment by nkolev92** [comment]
Hey @BSG-75,

Content folders are mutable and as such they are not supported in PackageReference. The replacement are content files, https://devblogs.microsoft.com/nuget/nuget-contentfiles-demystified/. 

See related issue https://github.com/NuGet/Home/issues/6659. Unlikely at this point.
