### ISSUE TITLE
Allow for a "Debug" or "Developer" mode of package

### ISSUE THREAD

**Issue by stevenbrix** [NuGet/Home#9375]
Many times when dealing with local Nugets, it can be very easy to be in a state where someone tries to build your project, only to have different behavior, only to realize later that it's because the nuget was already restored and that's why behavior is different. It would be great if there was a concept of a "Debug" or "Developer" mode package that would always restore so that you know it's up to date. Having to update the version number is tedious/manual and can easily be forgotten.

**Comment by nkolev92** [comment]
Hey @stevenbrix, thanks for filing this issue.

We are tracking the overall story in #6579
