### ISSUE TITLE
Issue with load list of package versions (nuget list [search terms] [options])

### ISSUE THREAD

**Issue by syakimchik** [NuGet/Home#9378]
When I call:
`nuget list [search terms] [options]`
for example:
`nuget list Xamarin.Android.Arch.Core.Common`
I expect, as descripted in documentation, that this command will return a list of versions for current package. But instead of this, the command is loaded all packages with latest versions. It takes a lot of time.
As I remember, previous version was loaded only list of versions available for current package

NuGet Version: 5.5.0.6382
OS: MacOS

**Comment by nkolev92** [comment]
@syakimchik 

NuGet.exe list has an -AllVersions option, can you try using that? 

https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-list

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
