### ISSUE TITLE
[CPVM] Error on floating transitive dependencies defined in Directory.Packages.props

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9384]
## Details about Problem

Discuss the behavior for transitive dependencies when defined with floating versions.

- Allowed/Not allowed
- If they are not allowed what is the desired behavior

**Comment by cristinamanum** [comment]
One scenario to describe the concerns:
Central File : A 1.0.0
                          B *
Package Dependencies:
A 1.0.0 depends on B strict [1.0.0]
Feed has: A 1.0.0
                  B 1.0.0
                 B 2.0.0
Project P depends on A 1.0.0
Restore will result in NU1608 .

Not CPVM enabled projects direct dependencies will lead into the same behavior, however it is less likely that this scenario could happen. The reduced likelihood is because the fact that the direct dependency to the project B should not be needed and is probably a user mistake in the PackageRefrence projects. 

Central File : None (CPVM not enabled)
Package Dependencies:
A 1.0.0 depends on B strict [1.0.0]
Feed has: A 1.0.0
                  B 1.0.0
                 B 2.0.0
Project P depends on 
A 1.0.0 and 
B *
Restore will result in NU1608 .


Proposal:
Error on floating versions in the Directory.Packages.props

**Comment by anangaur** [comment]
I don’t think there should be an error for defining floating versions for packages in the central file - direct or transitive. Whether the package becomes direct or transitive depends on a lot of factors after defining the floating version in the central file. Not sure if I am missing anything but would love to understand more.

**Comment by kzu** [comment]
This is currently the behavior on .NET5 RC2 and it's quite puzzling. 

>  error NU1011: Centrally defined floating package versions are not allowed.

Why would this be an error? I'd love to learn more about the reasoning behind this design.

Thanks!

**Comment by cristinamanum** [comment]
Hello @kzu, there were two reasons for which we choose to implement this behavior:
1.	The version defined at the central versions will be used for direct resolution and transitive resolution. The floating version resolution is the highest on the server in the rest of the cases is the min version in the specified range. A floating version for direct package dependency in a project P1, may lead to warnings in restore of a different project that happen to pull the floating version as transitive. Through this decision we tried to minimize unexpected cases like these.
1.	The central package version file is the place to define specific intent of the package versions. As floating version definition depends on the availability on the feed of the package versions we thought that enforcing a more precise definition is more in-line with the mental model of the central package version file . 

We are open for feedback, please add :+1: or :thumbsdown: to this issue; it will help us to reconsider this decision.

**Comment by rconard** [comment]
@kzu & @batzen,

Just to make sure that we are using the same terminology -

## Floating Versions:
```xml
<PackageReference Include="ExamplePackage" Version="6.*" />
```

## [Version Ranges](https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges):
```xml
<PackageReference Include="ExamplePackage" Version="[6,7)" />
```

Are you referring to both "Floating Versions" and "Version Ranges" or just to "Floating Versions" with the `*` notation?

**Comment by batzen** [comment]
I was referring to floating versions and haven't tested version ranges as i rarely use them.
I get that it might cause issues as described above and it would totally fine if this was a warning. But making it an error totally prevents floating versions.
I, for example, use floating versions to get the highest minor, patch or pre-release version automatically and don't know of other ways to achieve that.
Especially local development of dependencies would get harder, and it's already harder than it should be (aside from CPVM).

**Comment by kzu** [comment]
I too use floating versions for local development so I can constantly dogfood locally the packages produced by my main branch, and in CI I switch to fixed versions.

There aren't any real workarounds for this, since even if I produce a fixed version (say MyPackage-main.tip), the nuget cache would assume it never changes and would never actually get a new version. 

Since most folks already use WarningsAsErrors for CI/Release builds, I think it's enough if this was a warning, since it would be visible enough and if it pointed to an explanation like the one you gave above, would make it actionable (add a direct reference) and clearly understood.

**Comment by batzen** [comment]
@rconard Any news on this?
I just had to discover that newer versions of Visual Studio fail silently when using floating versions with CPVM.
That's the worst that can happen to a dev.
VS just does not restore a single project with no hint on what's wrong.

Even worse, but that might be a purely VS related issue, VS ignores my global.json which says SDK = 3.1.300 (where CPVM worked with floating versions) and uses a totally different MSBuild/SDK version instead.

**Comment by cros79** [comment]
@cristinamanum This behavior is really troublesome for us. We are producing internal nuget packages where use of floating versions would be immensely helpful. I really think that the decision to use a floating version should be on the user of the nuget client, not the author. Floating versions are no more or less valid just because you declare them locally in a project file.

**Comment by jackbond** [comment]
> We are open for feedback, please add 👍 or 👎 to this issue; it will help us to reconsider this decision.

Just received "Centrally defined floating package versions are not allowed." and found this thread. Based on the voting, it doesn't look like your decision to prevent this is a popular one. Any updates on this?

**Comment by voroninp** [comment]
@cristinamanum, I understand that it is a defined semantics of `*` (get the latest version), but I guess, in most cases, what devs really need is just _get the highest possible version_. 
Similar to non-greedy regex mode we could have an option `Version="*?"`.

And yes, usually, it's about minor versions: `Version="x.*"`

**Comment by jeffkl** [comment]
Unfortunately, Cristina is no longer on the NuGet team but I'm going to re-open this issue to continue to collect upvotes to see if we should take a look at making a change.

**Comment by flobernd** [comment]
Just to clarify: both, floating versions and version ranges are not allowed at the moment. Both features would be very useful to have with CPVM.

**Comment by handerss-spotfire** [comment]
This feature would be great, it would allow us to switch from the [MSBuild version of central package versions](https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions) which does support this. Our use case is also automatically using the latest versions of internal dependencies.

**Comment by jakenuts** [comment]
Floating versions is such a great feature in Nuget and we use them extensively with internal packages and trusted 3rd party libraries. Not sure why CPM needs to have this limitation but it's the one thing keeping my company from using CPM.

**Comment by kzu** [comment]
Ok, I'm ditching CPVM for [the thing that actually works](https://github.com/microsoft/MSBuildSdks/blob/main/src/CentralPackageVersions/README.md). 

Trivial migration:

1. Rename `Directory.Packages.props` to `Packages.props`

2. In your `Directory.Build.targets` add the SDK:

```xml
<Project>
  <Sdk Name="Microsoft.Build.CentralPackageVersions" Version="2.1.3" />
</Project>
```

3. `Packages.props`: find all `PackageVersion Include` and replace all with `PackageReference Update`. 

Done. Back to sane developing (especially for dogfooding previews)

**Comment by jeffkl** [comment]
At this time we're closing this issue as completed.  Float versions will not be allowed in CPM since we consider it an enterprise feature which should support repeatable restores.  Using floating versions can introduce non-determinism in your restore and is not recommended.  Instead, we recommend a system like [Dependabot](https://docs.github.com/code-security/dependabot/working-with-dependabot) to keep your dependencies up-to-date.  This sort of system makes commits in your repository that you can easily revert in the case of something broken during deployment.  If you use floating versions for "always having the latest" and something is broken, you have to either make a new commit manually or fix the problem, push a new package, and then restore again.  

https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1011

Also, be aware that I shipped both Microsoft.Build.CentralPackageVersions and NuGet's Central Package Management.  I will eventually be deprecating Microsoft.Build.CentralPackageVersions in favor of CPM.

**Comment by jackbond** [comment]
This seems like a "we could easily do it, but **WE** think floating versions are a bad idea, DESPITE NOT KNOWING ONE IOTA about your environment. Does the determinism issue magically not exist when NOT using CPM? NuGet should have a meeting and either decide to either support floating versions or not, and put out a statement that those CUSTOMERS who have chosen to use it are not morons, which this thread certainly implies. And before anyone says, "where did I say you were a moron", spare us the indignation. "you have to either make a new commit manually or fix the problem." Gee, thanks professor, I'm glad you're here to tell us these things. CPM is not an enterprise feature, in hindsight, it should have been the implementation from the start, and if a CUSTOMER chooses to use a floating version, then the CUSTOMER has chosen what's right for their environment.

**Comment by naiksujit** [comment]
This should be a choice really. We have been using floating versions as feature. Now all of sudden its gone.

**Comment by zivkan** [comment]
Support for floating versions in CPM was merged in December:

* https://github.com/NuGet/NuGet.Client/pull/5528
* https://github.com/NuGet/Home/issues/10432

It'll be part of Visual Studio & MSbuild 17.9 Preview 3, and I think that corresponds to the .NET 8.0.200 SDK.

**Comment by kzu** [comment]
This is great news. I can go back to using this :).

Glad to see the team listening to feedback 🫶

**Comment by WeihanLi** [comment]
still get an error with .NET 9 preview 4 SDK

```
error NU1011: Centrally defined floating package versions are not allowed
```

`dotnet --info` output:

```
.NET SDK:
 Version:           9.0.100-preview.4.24267.66
 Commit:            26d3d259e4
 Workload version:  9.0.100-manifests.63869261
 MSBuild version:   17.11.0-preview-24225-01+bd0b1e466

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.4.24267.66\

.NET workloads installed:
 [aspire]
   Installation Source: SDK 9.0.100-preview.4, VS 17.11.34909.67
   Manifest Version:    9.0.0-preview.3.24210.17/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.3.24210.17\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      9.0.0-preview.4.24266.19
  Architecture: x64
  Commit:       d0d6fed6c0

.NET SDKs installed:
  6.0.423 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]
  8.0.301 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.4.24267.66 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.4.24267.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by WeihanLi** [comment]
Configure
`<CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>` to enable floating version support, thanks very much

**Comment by jackbond** [comment]
Seriously, you need to opt in??? This is just too comical, so someone decided that this was a good idea?

if(centralPackageFloatingVersionsEnabled)
{
     // everything just works like it should have from the beginning
}

else
{
     // raise an error that never made sense
}

Pretty much tells you everything you need to know about the experience level of whoever made this decision. "The best part is no part" You've made something more complex than it needs to be FOR ABSOLUTELY NO REASON WHATSOEVER.

**Comment by WeihanLi** [comment]
Also thinks this could be enabled by default, any risks for disabled by default?

**Comment by RussKie** [comment]
> Configure `<CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>` to enable floating version support, thanks very much

@WeihanLi thank you for this.

@jeffkl could you please update the https://learn.microsoft.com/nuget/reference/errors-and-warnings/nu1011 docs to reflect the change? Thank you.

**Comment by tarurar** [comment]
> Configure `<CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>` to enable floating version support, thanks very much

This doesn't work, unfortunately. I tried to set this up in .Build.props file. Using .NET 8.

**Comment by WeihanLi** [comment]
> This doesn't work, unfortunately. I tried to set this up in .Build.props file. Using .NET 8.

> It'll be part of Visual Studio & MSbuild 17.9 Preview 3, and I think that corresponds to the .NET 8.0.200 SDK.


may need to check the SDK version, `dotnet --info` would be helpful

**Comment by TheXenocide** [comment]
@tarurar Enabling CPM can't be done via custom project SDKs either, the property needs to be enabled via `Directory.Packages.props` for it to work in our environments. Maybe the same is true for `CentralPackageFloatingVersionsEnabled`?

**Comment by tarurar** [comment]
> @tarurar Enabling CPM can't be done via custom project SDKs either, the property needs to be enabled via `Directory.Packages.props` for it to work in our environments. Maybe the same is true for `CentralPackageFloatingVersionsEnabled`?

You are right. Indeed it works fine if configured in `.Packages.props` instead of `.Build.props` file.
