### ISSUE TITLE
 Request headers must contain only ASCII characters.

### ISSUE THREAD

**Issue by bayramucuncu** [NuGet/Home#9385]
## Details about Problem

NuGet product used (NuGet.exe | dotnet.exe):

NuGet version (5.4.0.2):

dotnet.exe --version (3.1.102):

OS version (Win10 v1903 (18362.720)):

`dotnet nuget delete MyPack 1.0.1 -s https://api.nuget.org/v3/index.json -k apikey`

So when I run dotnet nuget `delete `or `push `command with an **apiKey** that generated `nuget.org`, throws an exception:

> Request headers must contain only ASCII characters.

In this stuation, I am trying to recreate the key multiple times until that contains only ASCII charecters.

For example trying this key `"oy2n43fdıq7hx5m5fujqjete2yqazefuxa65bvm2j6ı5pu"` throws exception.

**Comment by nkolev92** [comment]
Hey gallery folks, 
@joelverhagen @cristinamanum @loic-sharma 

Does this look like a valid API key? Is this an expected behavior?

**Comment by joelverhagen** [comment]
/cc @ryuyu who investigated this issue. We had a Turkish "i" bug where `ToLower()` was used instead of `ToLowerInvariant()`. There is a Turkish "i" in that API key suggesting it is the same bug.

@bayramucuncu, please generate a new API key. Apologies for the inconvenience.

**Comment by nkolev92** [comment]
Thanks @joelverhagen 

@bayramucuncu gonna close this issue now, let us know if the suggestion did not work. 

Thanks.

**Comment by bayramucuncu** [comment]
Thank you for your interest.
