### ISSUE TITLE
Nuget acceptance command works wrong!

### ISSUE THREAD

**Issue by bayramucuncu** [NuGet/Home#9386]
NuGet product used (NuGet.exe | dotnet.exe):

NuGet version (5.4.0.2):

dotnet.exe --version (3.1.102):

OS version (Win10 v1903 (18362.720)):

When I run my dotnet nuget command in console like following:

`dotnet nuget delete B3.Extensions.Data 1.0.2 -s https://api.nuget.org/v3/index.json -k apikey`

it asks me if I want to continue.

![e](https://user-images.githubusercontent.com/2901269/78363733-f30d5b00-75c4-11ea-88e0-4fc86767512d.PNG)

If I type "y", it is cancelling. If I type "n", it is deleting.

My language is Turkish. So there is a translation bug or logical bug here.

**Comment by heng-liu** [comment]
Thanks for reporting this issue!
Tried to repro in English, it worked correctly. So it should be a localization issue.
```
C:\reproIssues\packages> dotnet nuget delete project1 1.0.0 -s local
project1 1.0.0 will be deleted from the 'C:\reproIssues\packages'. Would you like to continue? (y/N)
n
info : Delete canceled
C:\reproIssues\packages> dotnet nuget delete project1 1.0.0 -s local
project1 1.0.0 will be deleted from the 'C:\reproIssues\packages'. Would you like to continue? (y/N)
y
warn : Deleting project1 1.0.0 from the 'C:\reproIssues\packages'.
info : project1 1.0.0 was deleted successfully.
```
