### ISSUE TITLE
NU5129 doesn't consider upwards directories

### ISSUE THREAD

**Issue by matkoch** [NuGet/Home#9388]
My `/build` directory structure for my project `Nuke.Common` is as follows:

```
- netfx/Nuke.MSBuildTasks.targets
- netcore/Nuke.MSBuildTasks.targets
- Nuke.Common.props
- Nuke.Common.targets
```

Even though this doesn't cause any issues in practice, I'm getting the `NU5129` warning:

```
warning NU5129: - At least one .targets file was found in 'build/netcore/', but 'build/netcore/Nuke.Common.targets' was not. [/Users/runner/runners/2.165.2/work/1/s/source/Nuke.Common/Nuke.Common.csproj]
```

So in essence, validation doesn't match actual resolution.

**Comment by zivkan** [comment]
Closing as duplicate of https://github.com/NuGet/Home/issues/8627
