### ISSUE TITLE
'nuget restore' via CLI does not restore content files

### ISSUE THREAD

**Issue by alex-jitbit** [NuGet/Home#9392]
## nuget restore does not restore content files

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.4.0

OS version (i.e. win10 v1607 (14393.321)): Win Server 2019

**This bug ruins CI/CD** because my web project's `/Scripts` folder and similar JavaScript/CSS/images and other static stuff is not being copied during deploy!

**Comment by MikhailArkhipov** [comment]
Having same issue. I am deploying very small assembly which all is does is launching NATIVE process and then talks to it. Packaging does include native bits and dependencies, but restoring/building app that uses the package does not restore folder with native process bits.

IMO, there are many targets like `lib`, etc, but what about *plain copy*. I can't place anything in `lib`, native bits must be in a specific folder. BTW, this used to work couple of years ago.

**Comment by nkolev92** [comment]
Hey @alex-jitbit, @MikhailArkhipov 

Would either of you be able to provide a repro here? 

Other helpful information would be whether your projects are packages.config or PackageReference based. 
Pointing us to a package that you are having problems with might help too.

**Comment by alex-jitbit** [comment]
@nkolev92 in my case it's `packages.config` (.NET Framework ASP.NET MVC5 project - **not** Core)

The project, for example, references `Microsoft.AspNet.SignalR.JS` nuget package, that puts JavaScript files into the /Scripts folder.

In Visual Studio it works fine. Via CLI - JS files are not being created.

**Comment by nkolev92** [comment]
Hey @v-luzh, 


Can you please try to repro this issue. 

Summarizing the steps that @alex-jitbit provided. 

1.  Create a (.NET Framework ASP.NET MVC5) project (not Core).
1. Install the package Microsoft.AspNet.SignalR.JS.
1. Close VS, delete the packages folder and try restoring from:
* Visual Studio
* nuget.exe

And check if you observe any differences. 

Thanks.

**Comment by alex-jitbit** [comment]
Thanks. Not just `packages` folder though, delete the `project/Scripts` folder too. Sorry for not mentioning this clearly

**Comment by nkolev92** [comment]
@alex-jitbit, that's for that detail, that's very valuable. 

Unfortunately due to the packages.config design, I would not expect restore to copy those scripts inside the project folder. 

Things that end up in the project folder are meant to be committed to your source control. 

Unfortunately that's a design limitation of packages.config. In PackageReference we made `contentFiles` (note the folder name) immutable, and they are linked from the global packages folder rather than added to the project file explicitly.

**Comment by nkolev92** [comment]
Closing per the above.

**Comment by daryllabar** [comment]
@nkolev92 So does that mean when working with dotnetcore, you should never create a NuGet Package that references a NuGet package that contains content files (See here https://stackoverflow.com/questions/65051835/how-to-add-nuget-source-only-package-dependencies for my current issue that results in me asking this question)?  I've been doing this with the packages.config for years and have not had a problem, so although I understand, it is rather disappointing...
