### ISSUE TITLE
NuGet should support multiple config files in %APPDATA%\NuGet directory

### ISSUE THREAD

**Issue by debonte** [NuGet/Home#9394]
## Details about Problem
NuGet product used: VS UI
NuGet version: 5.6.0.6489
VS version: 16.7
Worked before?: No

## Detailed repro steps so we can see the same problem
1. Unzip [SomeOther.zip](https://github.com/NuGet/Home/files/4430294/SomeOther.zip)
2. Place SomeOther.config in %APPDATA%\NuGet. This config file declares a single package source named "IssueRepro"
3. Start VS and open/create some project
4. Open NuGet Package Manager
5. Expand "Package source" combo box

**Expected:** IssueRepro source is one of the options.

**Actual:** IssueRepro source is not shown as an option.

**Workarounds**:
1. Place the file in %ProgramFiles(x86)%\NuGet\Config instead. 
1. Merge the IssueRepro package source into %APPDATA%\NuGet\NuGet.Config's list of package sources.

Note that what I really care about is fallback folders, but I'm using package sources for ease of repro.

## Reasoning
The XAML and WinForms teams want to allow control library installers to add user-specific NuGet fallback folders by having their SDK installers drop config files in %APPDATA%\NuGet. On uninstall this file would be deleted.

We considered two alternatives which I mentioned as workarounds above:
1. Require SDK installers to drop config files in %ProgramFiles(x86)%\NuGet\Config instead. However, we've gotten feedback from control vendors that they would like the option of installing without elevation which prevents the installer from being able to write to this directory.
2. Require SDK installers to modify the one %APPDATA%\NuGet\NuGet.config file. However this seems error prone.

@rrelyea @zivkan @aortiz-msft @mgoertz-msft

**Comment by nkolev92** [comment]
PR out https://github.com/NuGet/NuGet.Client/pull/3421
