### ISSUE TITLE
Visual Studio Extension - Change 'Do not show this again' appearance

### ISSUE THREAD

**Issue by csharpfritz** [NuGet/Home#94]
The 'Do not show this again' checkbox behaves more like a button or a command link that when clicked disappears.

Please update this control to be presented as a hyperlink.  Also verify that it presents with the proper font color in the Visual Studio dark theme.

**Comment by yishaigalatzer** [comment]
@feiling lets get together and look at this tomorrow.

**Comment by yishaigalatzer** [comment]
This is not critical for RTM, moving out. We need to triage this again, I don't think the effort here is justified.

**Comment by yishaigalatzer** [comment]
Fixed to be a proper checkbox
