### ISSUE TITLE
NuGet Package Manager should filter out types that cannot be installed in project

### ISSUE THREAD

**Issue by timheuer** [NuGet/Home#9401]
When you search for NuGet packages in the NuGet Package Manager UI it will show packages that can't actually be installed in the VS contexts within Visual Studio/VSMac.  For example, "Templates" show up but are not able to be installed/used in VS.

We are not helping customers to success.

![image](https://user-images.githubusercontent.com/4821/78583666-fb93aa80-77eb-11ea-8c21-d5b70e1671b1.png)

**Comment by anangaur** [comment]
Related issue: https://github.com/NuGet/NuGetGallery/issues/3098

**Comment by dominoFire** [comment]
Might be related to - #7284

**Comment by nkolev92** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/5725.

**Comment by anangaur** [comment]
While all of these can be clubbed under “Package applicability”, I feel this one is a low hanging fruit. Can we make it a task under the package applicability?
