### ISSUE TITLE
Restore fails with -Source <Relative Path>

### ISSUE THREAD

**Issue by WonyoungChoi** [NuGet/Home#9406]
## Details about Problem

`nuget restore` fails when specifying a relative path with `-Source` option in 5.5.1 or later versions. Because it tries to resolve the relative path based on the project file location.

This problem also occurs in dotnet-sdk 3.1.201, but dotnet-sdk 3.0.103 is fine.

NuGet product used : NuGet.exe and dotnet.exe
NuGet version : 5.5.1
OS version (i.e. win10 v1607 (14393.321)): Tested on mono 6.8 and ubuntu 16.04
Worked before? If so, with which NuGet version: 5.4.0

## Detailed repro steps so we can see the same problem

1.  Make a project structure like below:
```
├── ConsoleApp1
│   ├── ConsoleApp1.csproj
│   └── Program.cs
├── NuGets
│   ├── microsoft.netcore.app.ref.3.0.0.nupkg
│   └── newtonsoft.json.12.0.3.nupkg
├── ConsoleApp1.sln
```
2. Clear all nuget caches
```
nuget.exe locals all -clear
```

3. Restore the project with a relative nuget source path 
```
nuget.exe restore ConsoleApp1.sln -Source ./NuGets
```

### Verbose Logs

```
+ echo '#### Restore with nuget 5.4.0 ###'
#### Restore with nuget 5.4.0 ###
+ mono tools/nuget_5.4.0.exe locals all -clear
Clearing NuGet HTTP cache: /home/user/.local/share/NuGet/v3-cache
Clearing NuGet global packages folder: /home/user/.nuget/packages/
Clearing NuGet Temp cache: /tmp/NuGetScratch
Clearing NuGet plugins cache: /home/user/.local/share/NuGet/plugins-cache
Local resources cleared.
+ mono tools/nuget_5.4.0.exe restore ConsoleApp1.sln -Source ./NuGets
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Restoring packages for /home/user/RestoreWithRelativePath/ConsoleApp1/ConsoleApp1.csproj...
Installing Microsoft.NETCore.App.Ref 3.0.0.
Installing Newtonsoft.Json 12.0.3.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: /home/user/RestoreWithRelativePath/ConsoleApp1/obj/project.assets.json
Restore completed in 404.66 ms for /home/user/RestoreWithRelativePath/ConsoleApp1/ConsoleApp1.csproj.

NuGet Config files used:
    /home/user/.config/NuGet/NuGet.Config

Feeds used:
    /home/user/RestoreWithRelativePath/NuGets

Installed:
    1 package(s) to /home/user/RestoreWithRelativePath/ConsoleApp1/ConsoleApp1.csproj

+ echo '#### Restore with nuget 5.5.1 ###'
#### Restore with nuget 5.5.1 ###
+ mono tools/nuget_5.5.1.exe locals all -clear
Clearing NuGet HTTP cache: /home/user/.local/share/NuGet/v3-cache
Clearing NuGet global packages folder: /home/user/.nuget/packages/
Clearing NuGet Temp cache: /tmp/NuGetScratch
Clearing NuGet plugins cache: /home/user/.local/share/NuGet/plugins-cache
Local resources cleared.
+ mono tools/nuget_5.5.1.exe restore ConsoleApp1.sln -Source ./NuGets
MSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
Restoring packages for /home/user/RestoreWithRelativePath/ConsoleApp1/ConsoleApp1.csproj...
The local source '/home/user/RestoreWithRelativePath/ConsoleApp1/NuGets' doesn't exist.
```

### Sample Project
https://github.com/WonyoungChoi/RestoreWithRelativePath

**Comment by dominoFire** [comment]
@WonyoungChoi does that work if you use a source folder created with `nuget add` commands? For example:

```
nuget add pkg1.nupkg -source .\myfolder
nuget add pkg2.nupkg -source .\myfolder
nuget restore ConsoleApp1.sln -source .\myfolder
```

**Comment by WonyoungChoi** [comment]
@dominoFire Same error in `NuGet 5.5.1` 😢
```
$ pwd
 /home/foo
$ nuget add NuGets/microsoft.netcore.app.ref.3.0.0.nupkg -source ./LocalSource/
$ nuget add NuGets/newtonsoft.json.12.0.3.nupkg -source ./LocalSource/
$ nuget locals all -clear
$ nuget restore ConsoleApp1.sln -Source ./LocalSource/
The local source '/home/foo/ConsoleApp1/LocalSource/' doesn't exist.
```
The absolute path of the specified relative path './LocalSource' is `/home/foo/LocalSource`, but `nuget restore` resolves the path to `/home/foo/ConsoleApp1/LocalSource`.

**Comment by nkolev92** [comment]
@v-luzh

Can you please try to repro this issue?

**Comment by v-luzh** [comment]
@nkolev92, it **repro** on Main\30522.201 + NuGet Client release-5.8.0-preview.3\5.8.0.6854 as below.

C:\Users\v-luzh\Downloads\RestoreWithRelativePath-master\RestoreWithRelativePath-master>nuget.exe locals all -clear
Clearing NuGet HTTP cache: C:\Users\v-luzh\AppData\Local\NuGet\v3-cache
Clearing NuGet global packages folder: C:\Users\v-luzh\.nuget\packages\
Clearing NuGet Temp cache: C:\Users\v-luzh\AppData\Local\Temp\NuGetScratch
Clearing NuGet plugins cache: C:\Users\v-luzh\AppData\Local\NuGet\plugins-cache
Local resources cleared.

C:\Users\v-luzh\Downloads\RestoreWithRelativePath-master\RestoreWithRelativePath-master>nuget.exe restore ConsoleApp1.sln -Source ./NuGets
MSBuild auto-detection: using msbuild version '16.8.0.46803' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin'.
Restoring packages for C:\Users\v-luzh\Downloads\RestoreWithRelativePath-master\RestoreWithRelativePath-master\ConsoleApp1\ConsoleApp1.csproj...
The local source 'C:\Users\v-luzh\Downloads\RestoreWithRelativePath-master\RestoreWithRelativePath-master\ConsoleApp1\NuGets' doesn't exist.
