### ISSUE TITLE
[CPVM] Suggestion - Add centralTransitive group for all the CPVM enabled projects

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9409]
## Details about Problem

To enable packing of the transitive dependencies a new centralTransitiveGroup is added to the project.assets.json. 
Currently if the collection of centralTransitive dependencies is empty the group will not be serialized to project.assets.json. 

The suggestion is to serialize an empty collection. 
The pros will be that will allow to differentiate between CPVM is ignoring things and CPVM did not find anything. 
Cons : empty data in assets file.

**Comment by aortiz-msft** [comment]
Bulk-closing old issues for CPVM.
