### ISSUE TITLE
NuGet should not fail a restore if a feed is inaccessible but no * versioning is required

### ISSUE THREAD

**Issue by mmitche** [NuGet/Home#9415]
## Details about Problem

- Any nuget configuration
- Nuget Version: 4.*? Really anything recent

## Detailed repro steps so we can see the same problem

1.  Create a new project (of any real kind that has a nuget package reference). A dotnet core console app works fine. The project should have not * versioning. For example, the following package ref works:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" />
  </ItemGroup>
```
2. Add a feed to the Nuget.config which can't be accessed.  A 404 or a 401 works fine here. For example, the following NuGet.config:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageSources>
    <clear />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="inaccessible" value="https://api.nuget.org/v10/index.json" />
  </packageSources>
  <disabledPackageSources>
    <clear />
  </disabledPackageSources>
</configuration>
```
3. Restore. The restore will fail because the inaccessible feed cannot be accessed

## Why this shouldn't fail

We do not need to fail. Because there is no * versioning in any part of the dependency graph, the restore will either find the required packages, or it will not and it and restore will fail. **Because there is no * versioning, an exhaustive search of all input feeds is not required.**

The reason why the dotnet team wants this behavior over the current behavior is that we are an open source project that primarily works in the open, but occasionally needs to do internal builds for security fixes. When doing these security fixes, internal feeds will appear in our On release day, we:
1. Publish our built packages to nuget.org
2. Push the internal commits used to build the release to the public repos and tag them. Customers use these commits to build their own versions of the repos.
3. These commits have internal feeds in their nuget.config files, but because external customers do not have access to these feeds, they cannot build the commit without altering the nuget.config file, even though all required dependencies are accessible.

We've worked around this in .NET Core by creating scripting which dynamically alters the nuget.config file prior to build, but this is clunky, only applies to automated builds, and non-obvious.

There are some other reasons not to fail:
- If we fail, it means altering or refactoring feed structures can mean that old commits become unbuildable. For instance, the .NET Core team will remove feeds containing isolated, stable packages that are created while doing final builds as those packages are moved to nuget.org. Those feeds still exist in nuget.config from old commits, but those commits will no longer build even though the packages that they need are fully accessible.

**Comment by dominoFire** [comment]
As a workaround to avoid modifying nuget.config, what about using `RestoreAdditionalProjectSources`? Pseudocode below:

```powershell
$feed = "https://unstable.feed.org/v3/index.json"
$result = curl $feed
$cfg = "path\to\nuget.config"

if ($result.failed) {
  dotnet.exe restore --configfile $cfg
}
else {
  dotnet.exe restore /p:RestoreAdditionalProjectSources=$feed --configfile $cfg
}
```

**Comment by nkolev92** [comment]
> We do not need to fail. Because there is no * versioning in any part of the dependency graph, the restore will either find the required packages, or it will not and it and restore will fail. Because there is no * versioning, an exhaustive search of all input feeds is not required.

That's not quite right. 
Often times a package will have versions on more than one of the configured feeds.
NuGet's resolution algorithm prefers the lowest matching package version when available, but if the lowest matching versions is not available because the feed is unreachable, you could get a different package version.

**Comment by mmitche** [comment]
> That's not quite right.
Often times a package will have versions on more than one of the configured feeds.
NuGet's resolution algorithm prefers the lowest matching package version when available, but if the lowest matching versions is not available because the feed is unreachable, you could get a different package version.

That still doesn't require that all feeds are accessible, right? That could simply mean that if you don't get the exact match, and then feeds are inaccessible, then you fail.

In all cases here, we're desiring an exact match. I'm referencing:
- Foo.Package @ 1.2.3 **or**
- Foo.Package @ 1.2.3-preview.1-1234.5

I think what I'm pointing out is that the failure to access a feed should be moved to a point when we know that the failure to access the feed will result in an incorrect restore. In fact, it appears that this is at least partially true today. The existence of packages in the local cache appears to avoid a restore failures when feeds are inaccessible.

**Comment by nkolev92** [comment]
Related issues: https://github.com/nuget/home/issues/6373

Yeah we have a priority order:
Covered here: https://docs.microsoft.com/en-us/nuget/concepts/package-installation-process

**Comment by nkolev92** [comment]
Triage with @aortiz-msft @zkat 

Closing this as dup of #6373.
