### ISSUE TITLE
Getting "Text file busy" error while update NuGet.exe

### ISSUE THREAD

**Issue by outcast** [NuGet/Home#9416]
## Details about Problem

NuGet product used: NuGet.exe

NuGet version (x.x.x.xxx): 4.1.0

dotnet.exe --version (if appropriate): No using mono 6.8.0.105

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Linux Ubuntu 18.04.4 kernel 4.15.0-96-generic

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Fresh install of Ubuntu 18.04.4
2. Installed the package mono-complete from the apt repo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main"
3. `$ sudo mono tools/nuget/nuget.exe update -self`

### Verbose Logs
```
XXXX@XXX:~/$ sudo mono tools/nuget/nuget.exe update -self
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 4.1.0.
Updating NuGet.exe to 5.4.0.
Text file busy
```

**Comment by dominoFire** [comment]
Can you run it again with the `NUGET_SHOW_STACK` environment variable set to `true` and the mono debug options enabled? For example:

```
NUGET_SHOW_STACK=true sudo mono --debug tools/nuget/nuget.exe update -self
```

**Comment by nkolev92** [comment]
Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
