### ISSUE TITLE
PackagesLockFile issues with projects with an assembly name different from the project file name

### ISSUE THREAD

**Issue by PaulVrugt** [NuGet/Home#9417]
#  Details about Problem

I have an issue in which the lock file generated by visual studio differs from the lock file generated by nuget.exe. This causes the error I get during a CI build:
NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. When I run a build in visual studio and having the lock file enabled, some project references have a different key. With visual studio, they are called "[productname].[component]", while doing the same using nuget.exe they are called "[companyname].[productname].[componentname]".

NuGet product used:
Nuget command line tool: 5.4.0.6315
VS version: 16.5.3
OS version: Windows 10

## Detailed repro steps so we can see the same problem
I was unable to reproduce it with a small repro solution. But in our case
1. build the solution via visual studio with lock file enabled
2. now run nuget.exe:
nuget.exe restore <solutionname>.sln -LockedMode
3. wait for the error to appear
### Verbose Logs
NuGet Version: 5.4.0.6315
MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '16.5.0.12403' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\<user>\AppData\Local\Temp\NuGetScratch\jpm2vzqy.nc5.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\<user>\AppData\Local\Temp\NuGetScratch\dcsqavr1.xl0.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="c:\nuget\nuget.exe" /p:RestoreConfigFile="Website\nuget.config" /p:RestoreLockedMode="True"

Running restore with 8 concurrent jobs.
Reading project file <project file>.vbproj.
Persisting no-op dg to <project file>.nuget.dgspec.json
NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.
Committing restore...
Writing cache file to disk. Path: <project file>.nuget.cache
Writing packages lock file at disk. Path: <project folder>\packages.lock.json
Restore failed in 78,05 ms for <project file>.

**Comment by dominoFire** [comment]
@PaulVrugt  Can you try restoring your project using the latest nuget.exe preview version available at nuget.org/downloads? Can you run with detailed logging and setting the NUGET_SHOW_STACK environment variable to `"true"`?

```powershell
$env:NUGET_SHOW_STACK="true"
nuget.exe restore solution.sln -LockedMode -verbosity detailed
```

**Comment by PaulVrugt** [comment]
@dominoFire Thank you for the quick reply! I've tested it with the latest nuget preview, but the result is the same:


```
PS C:\Users\[user]\source\repos\[product]> $env:NUGET_SHOW_STACK="true"
PS C:\Users\[user]\source\repos\[product]> c:\nuget\preview\nuget.exe restore testing\***.***.web.tests\***.***.Web.Tests.vbproj -LockedMode -ConfigFile Website\nuget.config -verbosity detailed
NuGet Version: 5.6.0.6489
MSBuild P2P timeout [ms]: 120000
MSBuild auto-detection: using msbuild version '16.5.0.12403' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\msbuild.exe "C:\Users\[user]\AppData\Local\Temp\NuGetScratch\bhwlobox.btc.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\[user]\AppData\Local\Temp\NuGetScratch\vtspnsit.e1o.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\nuget\preview\nuget.exe" /p:RestoreConfigFile="Website\nuget.config" /p:RestoreLockedMode="True"

Running restore with 8 concurrent jobs.
Reading project file C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\***.***.Web.Tests.vbproj.
The restore inputs for '***.***.Web.Tests' have changed. Continuing restore.
NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\obj\project.assets.json
Writing cache file to disk. Path: C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\obj\project.nuget.cache
Writing packages lock file at disk. Path: C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\packages.lock.json
Persisting dg to C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\obj\***.***.Web.Tests.vbproj.nuget.dgspec.json
Restore failed in 110,46 ms for C:\Users\[user]\source\repos\[product]\testing\***.***.web.tests\***.***.Web.Tests.vbproj.

NuGet Config files used:
    C:\Users\[user]\source\repos\[product]\Website\nuget.config

Feeds used:
    https://pkgs.dev.azure.com/***code/_packaging/Shared/nuget/v3/index.json
```

**Comment by nkolev92** [comment]
Hey @PaulVrugt 

Any chance you can give us a repro? 
This error can happen for so many different reasons, and unfortunately our error https://github.com/NuGet/Home/issues/7696 is not great at this point, so a repro is one of our only means for investigation.

**Comment by PaulVrugt** [comment]
@nkolev92 

Yep, I've been able to repro it.

steps:

- open the attached solution
- rebuild the solution
- open a command line
- run: nuget.exe restore -LockedMode c:\temp\repro\Testing\TestProject.vbproj (where you replace the path with the path to the extracted project file)

It seems that nuget create a lock file with the assemblyname of the referenced assembly in it, and visual studio creates a lock file with the name of the projectfile. This causes the restore issue. You can see this, if you add the -ForceEvaluate flag to the nuget command and check the generated lockfile

[repro.zip](https://github.com/NuGet/Home/files/4492162/repro.zip)

**Comment by nkolev92** [comment]
Thanks, 
I can repro and I've updated the title to reflect the exact issue.

**Comment by uladz-zubrycki** [comment]
Hi. I've also just encountered it. Are there any workarounds or estimations available?

**Comment by Bouke** [comment]
I'm running into the same problem. When interacting with nuget through Visual Studio (16.8.4) the `packages.lock.json` file is rewritten changing `CompanyName.Project.Name` into `project.name`, causing build/restore issues. The workaround I've been working with thus far is running `nuget restore -LockedMode -ForceEvaluate` in the solution folder.

Update: the `project.name` is the name in the Solution Explorer for this old-style csproj project.

**Comment by uladz-zubrycki** [comment]
Updated my projects to SDK-based format and now it works the way they it's supposed to: consistent output for `Visual Studio's package manager restore`, `nuget.exe restore` and `dotnet restore`.

**Comment by SymbioticKilla** [comment]
Is there any fix planned => visual studio restore should create same lock files as nuget restore?

**Comment by vascofernandes** [comment]
I'm having the same issue.
Using VS 2019 package manager to update some nuget packages causes the following error:

`NU1004	The project references netproxy whose dependencies has changed. The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.`

**Comment by nkolev92** [comment]
Fixed in https://github.com/NuGet/NuGet.Client/pull/4172. 

Try out Visual Studio 2022, dotnet SDK 6.0.100 and/or NuGet.exe 6.0 for the matching tooling. 

Please ensure all your tooling is updated (consider using msbuild and VS since they ship together for best results).
