### ISSUE TITLE
Package TestPackage.MinClientVersion shouldn't install correctly to UWP project

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#942]
NuGet 715

repro steps:
1.create blank app thru click C#->Windows->Univerdal-> Blank App(Universal Windows)
2.install package TestPackage.MinClientVersion1.2.0 from \indigofs\CommonShare\danliu\Packages 

expected results: error message below should list on errorlist 
![minclienterror](https://cloud.githubusercontent.com/assets/11768961/8665784/92bbe79e-2a1a-11e5-9df0-2579bd44b84e.PNG)
actual results: install successfully

**Comment by natemcmaster** [comment]
+1 can confirm that NuGet 3.4.4 in VS 2015 u3 is ignoring the 'minClientVersion' nuspec setting on UWP projects.
