### ISSUE TITLE
Visual Studio non-sdk style PR projects with PR items without version silently fail to add package References.

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9423]
## Details about Problem
In a non-sdk package reference project if a PR item does not have a version:
1. Reading the package references fails without any error in the build output and the build succeeds .
The error is displayed in the "Test" result window.
![image](https://user-images.githubusercontent.com/16580006/79025495-cdd79a00-7b3a-11ea-802c-cda0f897ea69.png)

2. The package is not added in the solution explorer -> project -> references tree.
3. The behavior is different than the SDK style projects where in such cases the min version is used. 

VS version (if appropriate):
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.6.0 Preview 3.0 [30006.203.master]

## Detailed repro steps so we can see the same problem

1. Download the attached zip folder.
1. Load the project in Visual Studio.
1. Build. 

### Sample Project

[Repo.zip](https://github.com/NuGet/Home/files/4463526/Repo.zip)

**Comment by nkolev92** [comment]
Yep this is become more and more frequent. 

https://github.com/NuGet/Home/issues/9289
