### ISSUE TITLE
No packages will install

### ISSUE THREAD

**Issue by Sampleeeee** [NuGet/Home#9432]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Jetbrains Rider UI

NuGet version: 5.5.0

dotnet.exe --version: 2.1.512

VS version: Community 2019

OS version: Version 1909 (OS Build 18363.720)

## Detailed repro steps so we can see the same problem

1. Right click on project

2. Manage NuGet Packages

3. Choose any package, so far I have tested Newtonsoft.Json, CitizenFX.Core.Client, and CitizenFX.Core.Server

4. Install the package

5. Get error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception 'System.AggregateException' thrown when trying to add source 'http://packagesource'. Please verify all your online package sources are available.
One or more errors occurred.
Unable to load the service index for source http://packagesource.
An error occurred while sending the request.
The remote name could not be resolved: 'packagesource'				
```

### Verbose Logs
Unsure of how to do this on Visual Studio 2019, if someone can tell me how, I'd happily do it.

### Sample Project
I'll just zip the project I'm currently using
[MarvosaCADServer.zip](https://github.com/NuGet/Home/files/4472463/MarvosaCADServer.zip)

**Comment by donnie-msft** [comment]
Please review the Package Source [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#package-sources). It looks like you have an improperly configured source pointing to `http://packagesource`.

**Comment by nkolev92** [comment]
Closing this per the above answer.

https://github.com/NuGet/Home/issues/8420 is tracking an improvement on config discovery and https://github.com/NuGet/Home/issues/7973 is tracking config management.
