### ISSUE TITLE
net5 tfm: Add xamarin compatibility support for net5 platforms

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9435]
According to [the spec](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md), the following compatibilities need to be defined:

| TFM             | Compatible With                                            | Comments                          |
|-----------------|------------------------------------------------------------|-----------------------------------|
| net5.0-android  | xamarin.android                                            |                                   |
|                 | (+everything else inherited from net5.0)                   |                                   |
| net5.0-ios      | xamarin.ios                                                |                                   |
|                 | (+everything else inherited from net5.0)                   |                                   |
| net5.0-macos    | xamarin.mac                                                |                                   |
|                 | (+everything else inherited from net5.0)                   |                                   |
| net5.0-tvos     | xamarin.tvos                                               |                                   |
|                 | (+everything else inherited from net5.0)                   |                                   |
| net5.0-watchos  | xamarin.watchos                                            |                                   |
|                 | (+everything else inherited from net5.0)                   |                                   |

NOTE: It's unclear what `xamarin.android` is supposed to be. We don't recognize that tfm according to our code. Perhaps it's supposed to be `mono.android`?

**Comment by nkolev92** [comment]
Is this needed in 5.x or only in 6.x?

**Comment by nkolev92** [comment]
Given that NuGet is not *interpreting* the profile, things are a bit tricky here, it'd require NuGet to hardcode the mapping, thus NuGet will start *interpreting* the platform name.

**Comment by JonDouglas** [comment]
Should this be tracked in https://github.com/NuGet/Home/issues/9783?

**Comment by zkat** [comment]
@JonDouglas it is. Do you mean that it shouldn't be?

**Comment by JonDouglas** [comment]
@zkat Was just adding a reference after going through all the various `dotnet` partner tags.

**Comment by zkat** [comment]
I don't think there's anything for us to do here, so I'm closing this out.

**Comment by nkolev92** [comment]
Wouldn't we have the same ask in net6.0?
