### ISSUE TITLE
.NET 5.0 TFM: Framework Precedence Rules

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9436]
net5 has [specific precedence rules](https://github.com/dotnet/designs/blob/master/accepted/2020/net5/net5.md#precedences) that need to be followed. We need to implement them.

**Comment by zkat** [comment]
Note: This might be working already? Need to test.

**Comment by nkolev92** [comment]
So almost perfect :D
A bunch of scenarios worked by accident. PR in https://github.com/NuGet/NuGet.Client/pull/3535.
