### ISSUE TITLE
net5 tfm: design manifest entries

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9438]
Design NuGet manifest entries for TargetPlatformVersion and TargetPlatformMinVersion (not sure what "design" is needed -- TPV should be treated as part of the tfm itself. TargetPlatformMinVersion is a separate, new attribute. This is a bit more involved than just passing it through.)

**Comment by nkolev92** [comment]
Yeah, I think this is likely a no-op and you just need to address: https://github.com/NuGet/Home/issues/9439

**Comment by zkat** [comment]
As Nikolche says, this is basically a noop. :)
