### ISSUE TITLE
net5 tfm: TargetPlatformMinVersion in packed nuspec

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9439]
Ensure Pack target passes TargetPlatformMinVersion to .nuspec generator.

```xml
        <!-- something like this: (not just a single property. might have multiple dgroups. One per group.) -->
        <xs:attribute name="targetPlatformMinVersion" type="xs:string" use="optional" />
```

**Comment by nkolev92** [comment]
Reading the target frameworks in the inner build is a prerequisite for this task.

**Comment by zkat** [comment]
As per email, this is going to be taken care of by assembly attributes and analyzers, instead. No need for action on the NuGet side.
