### ISSUE TITLE
PCL dependency resolves incorrectly due to addition of aspnetcore50

### ISSUE THREAD

**Issue by kylemc** [NuGet/Home#944]
I'm writing a PCL library with Profile151 (portable-net451+netcore451+wpa81). I'm am able to successfully reference Newtonsoft.Json.6.0.5 (portable-net45+wp80+win8+wpa81), but am not able to reference Newtonsoft.Json.6.0.8 (portable-net45+wp80+win8+wpa81+aspnetcore50). Instead, when I reference 6.0.8, it defaults to the portable-net40 profile (portable-net40+sl5+wp80+win8+wpa81) and fails to compile.

What's the expected behavior here? It seems like I should be able to take the portable-net45 dependency successfully.

Error:
> Warning as Error: Reference to type 'System.IConvertible' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.6\Profile\Profile151\mscorlib.dll', but it could not be found	c:\code\343\Services\Main\Nuget.Packages\Newtonsoft.Json.6.0.8\lib\portable-net40+sl5+wp80+win8+wpa81\Newtonsoft.Json.dll

Visual Studio Version: 12.0.31101.00 Update 4
.NET Version: 4.6.00057
NuGet Package Manager: 2.8.60318.734

**Comment by emgarten** [comment]
This has been fixed in NuGet 3.0.0. It now prefers the highest version of net45 when breaking PCL ties like this.

**Comment by yishaigalatzer** [comment]
@kylemc are you able to move to visual studio 2015?

**Comment by kylemc** [comment]
No. Not for this. I may have to stick to version Json.Net 6.0.5 until I can.

**Comment by yishaigalatzer** [comment]
You could ask James to make a change (remove dnxcore50 or aspnetcore50 and move it to a separate folder) or you could change the reference in the csproj by hand.

**Comment by kylemc** [comment]
I assumed that if I couldn't take the right reference in Visual Studio that I couldn't take a package dependency either. That's probably not true, is it? If I updated the reference in my csproj, it would fix the issue I'm seeing now. Is this a solution that will work if I'm trying to ship my library as a PCL nupkg?

**Comment by emgarten** [comment]
It should work. The nupkg you create will have a dependency on json.net. If the user consuming it has NuGet 2.8.6 they may encounter this issue, but since you are building this for UWP scenarios they would likely have NuGet 3.0.0 and it would select the correct json.net dll.

**Comment by kylemc** [comment]
I was able to verify the workaround solved my problem in VS 2013. Thanks.
