### ISSUE TITLE
net5 tfm: produce error when missing TPV

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9441]
Produce an error when a OS flavored .NET 5 TFM is consumed but the package has no TPV in either folder name of the manifest. Is this supposed to be during restore??

**Comment by nkolev92** [comment]
Reading the target frameworks in the inner build will make this possible.

**Comment by zkat** [comment]
This is pretty small assuming we have https://github.com/nuget/home/issues/9756 in place :)

**Comment by zkat** [comment]
current status: I haven't been able to actually get started with rewriting this because I'm still working on https://github.com/NuGet/Home/issues/9215
