### ISSUE TITLE
net5 tfm: msbuild props supersede NuGetFramework data

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9443]
When present, msbuild props like `TargetPlatformIdentifier` and `TargetPlatformVersion` should supersede the corresponding data in `NuGetFramework` objects.

**Comment by nkolev92** [comment]
I think it's covered under: https://github.com/NuGet/Home/issues/5154. 

So probably close this in favor of that?

**Comment by zkat** [comment]
closing in favor of #5154
