### ISSUE TITLE
NuGet restore with mixed packages.config/PackageReference and Directory.Build.targets

### ISSUE THREAD

**Issue by niblak** [NuGet/Home#9446]
In our .NET 4.7.2 solution, the majority of our projects use the new Common Project System/SDK-style projects, but a few of the projects that do not support this are still using the old project system and packages.config (such as ASP.NET ones).

Recently, we added a Directory.Build.targets file that included a global PackageReference behind a condition that applied only to the SDK-style projects using PackageReference:
```
  <ItemGroup Condition="'$(UsingMicrosoftNETSdk)' == 'true'">
    <PackageReference Include="..." Version="..." PrivateAssets="all" />
  </ItemGroup>
```

Even though this condition evaluated to false for packages.config projects, the mere presence of PackageReference seems to have caused NuGet to change the restore style and completely ignore packages.config. When building with VS 16.4.6, none of the packages.config packages were restored. 

Is this expected behavior? As an additional data point, our Azure DevOps pipeline continued to work as it manually runs `nuget.exe restore` as part of the pipeline (version 4.3.0), so it took us a few months to notice this -- this seems to force NuGet to read packages.config even in this mixed scenario, but the on-build restore in VS does not work.

**Comment by nkolev92** [comment]
Hey @niblak 

We apologize for the inconvenience. 

Unfortunately this is a known project system bug which is tracked here: https://developercommunity.visualstudio.com/content/problem/721485/visual-studio-manage-nuget-packages-ui-does-not-re.html

Please follow and upvote that issue.

**Comment by niblak** [comment]
Thanks Nikolche, will do.
