### ISSUE TITLE
Application Insights SDK fails to add config (Need help getting more logs out of NuGet client tools)

### ISSUE THREAD

**Issue by TimothyMothra** [NuGet/Home#9448]
Application Insights SDK publishes this package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/ .
During installation, this package should add an "applicationinsights.config" file to the customer's application.
This works for most of our users but a small subset of users do not get this file added.

When I run the command `Install-Package Microsoft.ApplicationInsights.Web -Verbose` I see the log:
> Added file 'ApplicationInsights.config' to project 'WebApplication28'.

Our customers have shared verbose logs showing no errors and no attempt to add this config file to their projects.
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1337

## Details about Problem

NuGet product used: Package Manager Console

NuGet version: 5.5.0

dotnet.exe --version (if appropriate): 3.1.201

VS version (if appropriate): 16.5.4

OS version (i.e. win10 v1607 (14393.321)): Windows 10 v1909 (Build 18363.778)

## Detailed repro steps so we can see the same problem

We don't currently have a repo. I'm looking for guidance to collect more logs and maybe hone in on a repro.

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Are any of the projects in question PackageReference?

Looking at the package it contains only the `content` folder which is not supported in PackageReference. 

https://devblogs.microsoft.com/nuget/nuget-contentFiles-demystified/

**Comment by TimothyMothra** [comment]
Thank you, yes we did confirm that the affected projects are using PackageReference.

Can you help me understand, would the contentFiles be able to differentiate between:
1. a NetCore web project targeting net framework
    - in this scenario, we do not want to inject files. These customers should use the NetCore api.
2. a net framework web project using PackageReference
    - in this scenario, we need to inject both the applicationinsights.config and modify the web.config

**Comment by nkolev92** [comment]
Hey @TimothyMothra 

The contentFiles conform to the same best available assets selection as the compile time dependencies in lib. 

So for PackageReference, say you have the following files:

```
lib\net472\myframework.dll
lib\netcoreapp3.0\mynetcore.dll
contentfiles\cs\net472\myframeworkextras
```

Then the content files will apply to .NET Framework projects but not to the .NET Core ones. 

Editing the webconfig would be trickier. note that ASP.NET Core projects changed their config approach to the [options](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options) pattern.

**Comment by TimothyMothra** [comment]
Hey, I think I didn't ask my question clearly. :)

1. Scenario 1
    - ASP.NET Core project
    - targeting net472
    - uses Startup.cs to configure dependencies.
2. Scenario 2
    - ASP.NET Web Project (full framework)
    - targeting net472
    - utilizing PackageReferences
    - uses Global.ascx and web.config to configure dependencies.

If I add this to my package: `contentfiles\cs\net472\myframeworkextras` 
**Q: Would my package be able to differentiate from Scenarios 1 and 2?**

**Comment by nkolev92** [comment]
Scenario 1 is not possible. 
ASP.NET Core projects by default cannot target net472. They are .NET Core based on.

**Comment by TimothyMothra** [comment]
I think you're missing my point.
If I change my example to net461, can a package install differentiate between Scenarios 1 & 2?

----

Visual Studio will create an ASP>NET Core web app targeting net461 by default:
![image](https://user-images.githubusercontent.com/28785781/79808571-0fc6c400-8323-11ea-914a-22ebac02261c.png)

**Comment by nkolev92** [comment]
I see.
It won't be able to do that. 
The selection pivot is the target framework.

**Comment by TimothyMothra** [comment]
thank you. that's what i needed to know.

**Comment by nkolev92** [comment]
At this point those are all the pivots we allow.

Closing the issue per the last comment.
