### ISSUE TITLE
 NuGet Package Manager doesn't indicate which package is deprecated

### ISSUE THREAD

**Issue by StingyJack** [NuGet/Home#9454]
The Nuget PM UI does show that a package is deprecated, but fails to tell us which package is the deprecated one.  Its kind of useless to give the warning but not the necessary detail. Please fix.

There is a screenshot of the problem attached to the [other report](https://developercommunity.visualstudio.com/content/problem/957820/nuget-package-manager-ui-reports-you-have-1-deprec.html)  thats been idle for a month now.

**Comment by StingyJack** [comment]
this is the same as [this](https://developercommunity.visualstudio.com/content/problem/957820/nuget-package-manager-ui-reports-you-have-1-deprec.html) ,  per @anangaur it will be fixed in upcoming version

**Comment by anangaur** [comment]
@StingyJack Its available with VS 16.6 previews.
