### ISSUE TITLE
nuget.exe 5.5 fails to restore with MSBuild 14 or below

### ISSUE THREAD

**Issue by jeffkl** [NuGet/Home#9458]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): 5.5.1

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: 5.4.X

## Detailed repro steps so we can see the same problem

1. `nuget.exe restore -MSBuildVersion 14.0`

Fails with the error:
```
C:\Users\jeffkl\AppData\Local\Temp\NuGetScratch\npvhljmi.kme.nugetrestore.targets(435,34):
error MSB4092: An unexpected token ")" was found at character position 28 in condition
"@(PackageReference->Count()) > 0". [D:\AspNetWithNet35\AspNetWithNet35\AspNetWithNet35.csproj]
```

This was introduced by my change: https://github.com/NuGet/NuGet.Client/commit/1ce56a3cd779ec4ebae39a1b0ce3f7ccc3310584#diff-3b0018f61173d0adf1ba163a23821381R434
https://github.com/NuGet/NuGet.Client/pull/3135

It turns out that the item function `Count()` was only added in MSBuild 14.0 Update 3.  So when using an older version of MSBuild, we can't use this logic.

**Comment by ghost** [comment]
I got this error with msbuild 12.0 on nuget.exe v5.5.1 which is recommended version on download page then I tried nuget.exe v5.6.0 and I see it fixed.

**Comment by rrelyea** [comment]
@aortiz-msft @nkolev92 - likely should consider blessing 5.6.0 this week or next?

**Comment by nkolev92** [comment]
Thanks @rrelyea I'll do that this week. https://github.com/NuGet/Client.Engineering/issues/364
