### ISSUE TITLE
NuGet Pack does not encode file names with non-ASCII characters

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#9459]
## Details about Problem

**NuGet product used:** nuget.exe
**NuGet version:** 4.6.0 - 5.5.1
**OS version:** Windows 10, version 1909, 18363.778
**Worked before?** yes, 4.5.3

## Summary

Starting in NuGet 4.6.0, the pack command does not encode file names containing some special characters (such as Chinese characters: `中文文件.txt`). This causes older clients and OPC readers to behave incorrectly.

## Impact

Older NuGet client versions, including any code using NuGet.Core such as NuGet.Server (https://github.com/NuGet/NuGetGallery/issues/7955), fail to open the package.

## Detailed repro steps so we can see the same problem

1. Pack a package with Chinese characters in the file name
1. Open the .nupkg in 7-Zip and look at the file name.
1. Attempt to open the package with `System.IO.Packaging`

### 4.5.3

[TestPack.4.5.3.zip](https://github.com/NuGet/Home/files/4511729/TestPack.4.5.3.zip)

![image](https://user-images.githubusercontent.com/94054/79897212-3980f900-83be-11ea-8c43-bbd894fa3442.png)

#### Test tool output

```
/contentFiles/any/any/modules/testpack/wwwroot/????.txt
/contentFiles/any/any/modules/testpack/wwwroot/????.txt
/package/services/metadata/core-properties/ea59128cca144a82b30ef0b3de6a08a5.psmdcp
/TestPack.nuspec
/_rels/.rels
```

### 4.6.0

[TestPack.4.6.0.zip](https://github.com/NuGet/Home/files/4511730/TestPack.4.6.0.zip)

![image](https://user-images.githubusercontent.com/94054/79897238-469de800-83be-11ea-9f39-6bf8e6438d73.png)

#### Test tool output - .NET Core

(the non-encoded files are ignored)

```
/package/services/metadata/core-properties/e22cd3c096914f2f8f346c156d8b5167.psmdcp
/TestPack.nuspec
/_rels/.rels
```

#### Test tool exception - .NET Framework

(the non-encoded files cause an exception)

```
Unhandled Exception: System.ArgumentException: Item has already been added. Key in dictionary: 'contentFiles/any/any/modules/testpack/wwwroot/????????????.txt'  Key being added: 'contentFiles/any/any/modules/testpack/wwwroot/????????????.txt'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at System.Collections.Specialized.OrderedDictionary.Add(Object key, Object value)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.ParseRecord(BinaryReader reader, Int64 centralDirectoryOffset, Int32 centralDirectoryCount, Int64 expectedCentralDirectorySize)
   at MS.Internal.IO.Zip.ZipIOCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
   at MS.Internal.IO.Zip.ZipIOBlockManager.get_CentralDirectoryBlock()
   at MS.Internal.IO.Zip.ZipArchive.GetFiles()
   at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream)
   at ConsoleApp1.Program.Main(String[] args) in D:\trash\2020-04-21\ConsoleApp1\ConsoleApp1\Program.cs:line 20
```

### Test tool to show problem

```csharp
using System;
using System.IO;
using System.IO.Packaging;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            // var path = @"C:\Users\jver\Downloads\TestPack.4.5.3.zip";
            var path = @"C:\Users\jver\Downloads\TestPack.4.6.0.zip";
            using (var stream = File.OpenRead(path))
            using (var package = Package.Open(stream))
            {
                foreach (var parts in package.GetParts())
                {
                    Console.WriteLine(parts.Uri);
                }
            }
        }
    }
}
```

**Comment by nkolev92** [comment]
Probably a consequence of https://github.com/NuGet/NuGet.Client/pull/1855 & https://github.com/NuGet/Home/issues/5956

**Comment by nkolev92** [comment]
Triage: We believe that the fix made in NuGet/NuGet.Client#1855 & #5956 fixed a scenario that's important enough and we would not want to regress said scenario. 

The guidance here is to upgrade to newer versions of the NuGet libraries to read the package. 

Closing this as won't fix.

**Comment by jbaehr** [comment]
@nkolev92 Is that really the last word? Now nupkg files, even though based on the Open Packaging Conventions, cannot be processed with .NET's OPC API (`System.IO.Packaing`) any more. For me this is a severe regression that broke our tooling.
