### ISSUE TITLE
Inconsistent analyzer references between legacy and SDK projects

### ISSUE THREAD

**Issue by tmat** [NuGet/Home#9460]
NuGet version (x.x.x.xxx):

```
>msbuild /version
Microsoft (R) Build Engine version 16.7.0-preview-20215-01+aa655667e for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.7.0.21501
```

## Detailed repro steps so we can see the same problem

Unzip [Repro.zip](https://github.com/NuGet/Home/files/4512818/Repro.zip) and build the solution.

Checking the binlog, the compiler receives different sets of analyzers, even though both projects have the same PackageReference:

![image](https://user-images.githubusercontent.com/41759/79918785-f6d11800-83e1-11ea-839b-53e1fb0a7ee6.png)

![image](https://user-images.githubusercontent.com/41759/79918793-f9337200-83e1-11ea-9ddd-2650badbe10a.png)

In legacy project the compiler receives satellite assemblies. This is unexpected.

**Comment by nkolev92** [comment]
NuGet in PackageReference doesn't do anything special about analyzers. 
There's an ask for that but it's not been prioritized: https://github.com/NuGet/Home/issues/6279. 

This issue probably belongs in the dotnet/sdk & dotnet/NuGet.BuildTasks repos as that's where the targets that interpret the assets file live.

**Comment by nkolev92** [comment]
Triage: 

Hey @tmat, 

As per the above comment, this is something not currently being done in the NuGet repo. For immediate feedback, I'd recommend you file issues in the dotnet repos mentioned above. 

#6279 will cover overall analyzers support through NuGet.
