### ISSUE TITLE
Running a script after package installation doesn't work on .NET Core 3.0

### ISSUE THREAD

**Issue by ghost1372** [NuGet/Home#9462]
Hi, I have a script that needs to be run after the package is installed. This works well in .NET Framework. But in .NET Core 3.0, the script does not run

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

dotnet.exe --version (if appropriate): 5.3.1.6268

VS version (if appropriate): 2019 16.6 pre 3

OS version (i.e. win10 v1607 (14393.321)): win 10 - 18363

**Comment by kartheekp-ms** [comment]
@ghost1372 - Please provide us repro steps and a sample project (if possible) so that we can understand the issue better and prioritize accordingly.

**Comment by ghost1372** [comment]
Hi @kartheekp-ms Sorry for the delay in reply

I attached an example project. Please create a nuget package with *.nuspec file.
After creating the package, please install it on a WPF (.Net Core) project
After installation, the script must be run and the site opened
But nothing happens
[Nuget.zip](https://github.com/NuGet/Home/files/6311503/Nuget.zip)

**Comment by nkolev92** [comment]
Hey @ghost1372 

Install scripts are not supported in PackageReference (the package management style under .NET Core). 

Refer to https://github.com/NuGet/Home/issues/5963.
