### ISSUE TITLE
[Feature]: Support overriding centrally managed version on a package reference

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9465]
## Details about Problem

Feature request

CPVM support version overrides.

Version overrides are supported as a product of MsBuild flexibility.

**_Option 1:_**  use the Import MsBuild element but there is not a build in experience for the version overrides. 

``` xml
<Project>
	  <ItemGroup>
	    <PackageVersion Include="Xunit.StaFact.Mac" Version="1.0.24-beta-g88c3555268"/>
	    <PackageVersion Include="xunit.stafact" Version="1.0.24-beta-g88c3555268"/>
	  </ItemGroup>
	
	  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory).., Directory.Packages.props))\Directory.Packages.props" Condition="'$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory).., Directory.Packages.props))' != ''" />
	</Project>

```

**_Option 2 :_**  use the MsBuild Update as :  
``` <PackageVersion Update="Foo" Version="1.2.3"/> ```

**_Option 3:_**  use the MsBuild Conditions as :  

Directory.Packages.Props 
``` xml
<Project>
  <ItemGroup Condition="'$(Group)'=='Test'">
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageVersion Include="EntityFramework" Version="6.2.0" />
    <PackageVersion Include="ParentLibTestCM1" Version="3.0.0" />
    <PackageVersion Include="LibTestCM1" Version="3.0.0" />
    <PackageVersion Include="NUnit" Version="3.12.0" />
    <PackageVersion Include="Microsoft.Azure.Storage.Common" Version="11.1.2" /> 
  </ItemGroup>
</Project>

```

Directory.Build.props (for the project that needs Newtonsoft 12.0.2)
``` xml
<Project>
  <PropertyGroup>
    <Group>Test</Group>
  </PropertyGroup>
</Project>

```

**Comment by cristinamanum** [comment]
Three options were discussed. Added them below.

1.	Reuse the Version attribute on the PackageReference item to override the version defined centrally
 
**Behavior changes**
In the current implementation having a project with a defined Version on a PackageReference  is an error case that leads to a failed restore.  
With the proposed solution the behavior will change and the Version value from the PackageReference will override the centrally defined version. 
                **_Pros:_**
                                Reduced cognitive overload. The users do not need to learn about a new concept and we(NuGet) do not need to create/maintain new documentation.
                                Reduced engineering cost. The data is already pipped from the clients (MsBuild, ProjectSystem) and integrated through the NuGet code paths. Also there will be no need to support a new error code. 
                                The onboarding is easier/friendlier. As the projects with defined PackageReference Versions will not fail restore, the users can opt-in at their own peace to CPVM. 
**_Cons:_**
                There could be cases when the users will forget to remove the Version attribute and override unintentionally. 
 
2.	Introduce a new metadata attribute “VersionOverride” 
 
**Behavior changes**
                None. The restore will continue to fail on the projects with PackageReference items that have Version defined. 
To override the centrally defined versions the PackageReference items will need to define VersionOverride =”1.2.3”
 **_Pros:_**
            Reduce the chance to override unintentionally. 
            Closer model with the current MsBuild SDK solution.  
**_Cons:_**
           Increased cognitive overload. The users will need to learn a new concept and we(NuGet) will need to create/maintain new documentation.
                                Increased engineering cost. 
•	NuGet will need to read and process new data. 
•	ProjectSystem will need to pass new information to NuGet.
                                Usability drawback. There will be two actions needed to have a Version overridden: 
•	Remove the Version attribute.
•	Add the VersionOverride attribute.  
 
2.	Use a **_Grouping_**  method but with friendlier interface.
Directory.Packages.props
``` xml

<Project>
  <ItemGroup name="Test">
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>
 
  <ItemGroup>
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageVersion Include="EntityFramework" Version="6.2.0" />
    <PackageVersion Include="ParentLibTestCM1" Version="3.0.0" />
    <PackageVersion Include="LibTestCM1" Version="3.0.0" />
    <PackageVersion Include="NUnit" Version="3.12.0" />
    <PackageVersion Include="Microsoft.Azure.Storage.Common" Version="11.1.2" /> 
  </ItemGroup>
</Project>

```

.csproj
``` xml
<Project>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Group=”Test” />
  </ItemGroup>
</Project>
```

**Comment by cristinamanum** [comment]
Cleaned the milestone as more customer insights are needed to decide the right workflow.

**Comment by kzu** [comment]
Hi there, 
I've been exploring this and I think there is a third option that is a mix of what's proposed above.

3. Reuse the Version attribute on the PackageReference item to override a `DefaultVersion` defined centrally

**Behavior changes**
In the current implementation having a project with a defined Version on a PackageReference is an error case that leads to a failed restore. With the proposed solution the behavior will change and the Version value from the PackageReference will override the centrally defined version but only if it's declared as DefaultVersion. If it's Version, behavior will not change.

**Pros:**
Same as for option 1 plus option 2!
Overridability is explicity by the choice of `DefaultVersion` instead of `Version` in the centrally defined `PackageVersion`.
If someone overrides by mistake, this causes a failure (since Version will continue to behave like it currently does).

**Cons:**
Increased cognitive overhead for the new feature (learn difference between Version and DefaultVersion)


Thanks

**Comment by cristinamanum** [comment]
Hello @kzu, thank you very much for the feedback! Would the proposed solution be similar with https://github.com/NuGet/Home/issues/9465#issuecomment-657694752 ? 
Also we are currently engaging with developers to collect feedback for this feature and CPVM overall. Please let us know if you would you like to help in this study? @rconard

**Comment by kzu** [comment]
Heya, yes, count me in if it's not too late.

It was confusing that the options were not all laid out it in the main description, and rather just a comment, but yes, the comment includes what I mentioned.

**Comment by jeffkl** [comment]
Closing in favor of https://github.com/NuGet/Home/issues/11516 which has final design
