### ISSUE TITLE
[CPVM-OnBoard] Support inheritance across Directory.packages.props

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9466]
## Details about Problem

> Can Directory.Packages.props be arranged in multiple levels of the tree, such that different subtrees can have different default versions of packages? Is the goal to eventually aggregate the multi-level files so that the closest one overrides the parent ones but inherits what it doesn't change? Alternatively I suppose we can simply define the overrides in the nearer one and then <Import> the original one, since given the behavior you said it has, the subsequent ones that conflict will be ignored.

**Comment by jeffkl** [comment]
This is already possible as long as each `Directory.Packages.props` imports a parent one.  You can import at the top or the bottom as well.
