### ISSUE TITLE
[Feature] Error on multiple entries for the same package ids in Directory.Packages.props

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9467]
## Details about Problem

Error on multiple entries for the same package ids in Directory.Packages.props.

In the current  design the first declared entry is honored and the others are ignored. 

Note: consider the support for version override. See [issue](https://github.com/NuGet/Home/issues/9465)

**Comment by cristinamanum** [comment]
This issue depends on the https://github.com/NuGet/Home/issues/9465. If an error will be raised when there are multiple entries few of the recommended ways to override will start failing. 
Re-evaluate this issue after the issue https://github.com/NuGet/Home/issues/9465 is fixed.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9864. 

I am fixing https://github.com/NuGet/Home/issues/9864, which might fix this issue as well.

**Comment by nkolev92** [comment]
In 6.3, [NU1506](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1506) is raised as a warning when a duplicate is detected. 

We can choose to error when we detect duplicates or we can call the warning good and move on to other issues :) 

@jeffkl @JonDouglas

**Comment by jeffkl** [comment]
Thanks @nkolev92, I've verified that your new warning covers this scenario so I'll close this as fixed!
