### ISSUE TITLE
[Test Failure] Embedded icon in “Consolidate” tab should be same with the latest installed package icon in “Installed” tab

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9468]
## Details about Problem
NuGet version: NuGet Client Release-5.6.x\5.6.0.6578
VS Version: D16.6\30021.205
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Create a solution with two C# Console App (.NET Framework 4.8) in VS and open the PM UI of the solution. 
2. Add the DevOps feed (https://pkgs.dev.azure.com/farhub/_packaging/farhub/nuget/v3/index.json) into the Settings->NuGet Package Manager->Package Sources. 
3. Select the new added DevOps feed in the Package source dropdown box in the PM UI and install the package “classlib.net48” with different version into two projects. 
4. Check the embedded icon in “Consolidate” tab. 
## Expected
Embedded icon in “Consolidate” tab should be same with the latest installed package icon in “Installed” tab.
## Actual
Embedded icon in “Consolidate” tab is not same with the latest installed package icon in “Installed” tab as below.
![image](https://user-images.githubusercontent.com/20632625/80105932-c89f3400-85ab-11ea-99e1-e76fb3d96a9e.png)
## Note
It seems not a regression bug since it repro on 16.5.4 (D16.5\30011.22).

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/9250
