### ISSUE TITLE
Update-package puts incorrect entries in project.json file for ASP.NET5 project

### ISSUE THREAD

**Issue by danliu** [NuGet/Home#947]
Repro steps:
1. Create a new ASP.NET 5 project
2. Start package manager UI, install EF 6.1.3
3. Check include prerelease, update EF to 7.0.0-beta4

Expected: EF 7.0.0-beta4 is referenced by the project

Actual: EF 6.1.3 is referenced, and in project.json file, there are two entries for EF:

![capture](https://cloud.githubusercontent.com/assets/1087852/8685698/590c2c5a-2a35-11e5-839d-4a334f1f79ce.PNG)

**Comment by yishaigalatzer** [comment]
This belongs in the tooling repo

**Comment by danliu** [comment]
Filed an external bug to track this issue.
