### ISSUE TITLE
Pack with IncludeBuildOutput set to false still adds netstandard as a dependency

### ISSUE THREAD

**Issue by rainersigwald** [NuGet/Home#9470]
_From @TFTomSun on Thursday, April 23, 2020 2:10:28 PM_

### Steps to reproduce

Create a project file like this:

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.1</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>
</Project>

```
Pack it with:

Command line
```
dotnet pack
```
### Expected behavior

The resulting package has no dependency to NetStandard, because I don't include the build output. I would expect a package that can be installed standalone... without any dependency.

### Actual behavior
The package has a dependency to NetStandard

_Copied from original issue: microsoft/msbuild#5309_

**Comment by nkolev92** [comment]
I think you are looking for https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#suppress-dependencies. 

Unfortunately we can't overload IncludeBuildOutput to have the same behavior because that ship has long sailed and it'll cause an arguably unnecessary breaking change.
