### ISSUE TITLE
Unable to install Azure Module through Powershell

### ISSUE THREAD

**Issue by Vishallogin2050** [NuGet/Home#9475]
When trying to Install Azure Module through Powershell , shows gives the below message :

Please ensure that '2.8.5.201' or newer version of NuGet provider is installed

However unable to install the mentioned.

Please help

**Comment by donnie-msft** [comment]
We'd need you to provide the details requested in the Issue template, such as NuGet version, which product you're using, and the exact repro steps.

**Comment by zivkan** [comment]
This is about PowerShell, not NuGet as a product.

@Vishallogin2050 you should look at PowerShell's [`Install-PackageProvider`](https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-packageprovider?view=powershell-7) command. If you have problem with that, I suggest you contact the PowerShell team, as we the NuGet team don't have expertise in PowerShell.

**Comment by Vishallogin2050** [comment]
When i  run the command Install-Module -Name AzureRM -AllowClobber to install the Azure module , I get the below error : 

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based repositories. The NuGet
 provider must be available in 'C:\Program Files\PackageManagement\ProviderAssemblies' or
'C:\Users\testadmin\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet provider by
running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want PowerShellGet to install
and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria for the provider
'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package
has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac
   kageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro
   vider

PackageManagement\Import-PackageProvider : No match was found for the specified search criteria and provider name
'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider exists on the system.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.ImportPackageProv
   ider

WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be imported yet. Try
'Get-PackageProvider -ListAvailable'.

**Comment by Vishallogin2050** [comment]
This is running on a Azure VM with default policies. Tried it on some other environments and the issue is the same

**Comment by Vishallogin2050** [comment]
Internet is accessible on the azure VM

**Comment by Vishallogin2050** [comment]
Error for install package :   
PS C:\Users\testadmin> Install-PackageProvider -Name "Nuget" -RequiredVersion "2.8.5.216" -Force
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
Install-PackageProvider : No match was found for the specified search criteria for the provider 'Nuget'. The package
provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.
At line:1 char:1
+ Install-PackageProvider -Name "Nuget" -RequiredVersion "2.8.5.216" -F ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac
   kageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro
   vider

**Comment by WillParry** [comment]
I was having the same problem, I think, a fresh Azure VM getting the error for installing the NuGet package provider. Read the link below and tried running this:

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

And then you should be able to install the package provider. I hope this works for you as well.

https://dirteam.com/sander/2020/04/09/knowledgebase-you-receive-error-unable-to-download-when-you-try-to-install-the-azuread-or-msonline-powershell-module/

**Comment by Vishallogin2050** [comment]
> I was having the same problem, I think, a fresh Azure VM getting the error for installing the NuGet package provider. Read the link below and tried running this:
> 
> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
> 
> And then you should be able to install the package provider. I hope this works for you as well.
> 
> https://dirteam.com/sander/2020/04/09/knowledgebase-you-receive-error-unable-to-download-when-you-try-to-install-the-azuread-or-msonline-powershell-module/

**Comment by Vishallogin2050** [comment]
Thanks Will , I was able to move ahead with the mentioned suggestion.
