### ISSUE TITLE
Test: UninstallFromPMCForPC_SucceedAsync is flaky

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9476]
The test `NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync(projectTemplate: ClassLibrary)` has timed out on at least two builds: [1](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3669401&view=logs&j=54d34e6c-10d1-5f6f-0d73-85c1fa19385b&t=2bc2bfed-4a11-5a5c-814b-223591eb3d53), [2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3672284&view=logs&j=54d34e6c-10d1-5f6f-0d73-85c1fa19385b&t=2bc2bfed-4a11-5a5c-814b-223591eb3d53)

Since it times out, the test results xml doesn't get generated, which means Azure DevOps test result analysis can't help us determine how often it's happening (the Apex tests job has timed out for multiple reasons in the past)

```
     NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync(projectTemplate: ClassLibrary) [STARTING]
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:05:04
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:10:04
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:15:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:20:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:25:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:30:05
     NuGet.Tests.Apex: [Long Running Test] 'NuGet.Tests.Apex.AuthorSignedPackageTestCase.UninstallFromPMCForPC_SucceedAsync', Elapsed: 00:35:05
Attempting to cancel the build...
##[error]The task has timed out.
```

**Comment by dominoFire** [comment]
Got hit by this test in a private run 

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=7000949&view=logs&j=35fd8e9c-c657-57a4-085d-6f9cd010d4b2&s=15b9481b-7425-558a-0ea3-f3c852e48746&t=fe374095-4dab-523b-315b-414b8de0f050&l=546
