### ISSUE TITLE
PackTask should report build error after logging errors

### ISSUE THREAD

**Issue by AArnott** [NuGet/Home#9477]
SDK version: 3.1.201
OS: Windows 10

The `dotnet pack` command incorrectly returns an exit code of 0 even after experiencing and printing errors (where `TreatWarningsAsErrors=true` has been set). This allows Azure Pipelines (for example) to proceed to build and report success and ship software even when errors occurred during the pack.

For example, this Azure Pipeline should have failed, but proceeded after an error during pack:
https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=2632&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f33089cd-d3fe-578c-2c5e-4ee560e10a0d

**Repro**

In any repo that uses .NET SDK 3.1.201, introduce a pack warning. For example, set the `<PackageLicenseExpression>MS-Pl</PackageLicenseExpression>` property (which has a non-canonical capitalization for the property value).

```cmd
SET TreatWarningsAsErrors=true
dotnet pack
echo %ERRORLEVEL%
```

**Expected**

A non-zero exit code

**Actual**

A zero exit code

**Comment by AArnott** [comment]
The bug appears to be that the `PackTask` [uses `return true;`](https://github.com/NuGet/NuGet.Client/blob/23f38852e43830453508a0a3cdcfab2a83382795/src/NuGet.Core/NuGet.Build.Tasks.Pack/PackTask.cs#L140) in non-exceptional cases.

But the MSBuild Task pattern is to instead `return !Log.HasLoggedErrors;`, as can be [clearly seen](https://github.com/microsoft/msbuild/search?q=hasloggederrors&unscoped_q=hasloggederrors).

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/7404.
