### ISSUE TITLE
NuGet command line times out on bad internet connection while other services operate correctly.

### ISSUE THREAD

**Issue by jaypeeZero** [NuGet/Home#9478]
## Details about Problem
I live out in the boonies and have an internet connection that has a very unique problem.  If my internet reaches peak bandwidth usage on upload connections it will effectively drop to basically no bandwidth available.  This is 100% reproducible by uploading a large file, *or using dotnet command line tools that interact with nuget*.  I will go from 12Mbps down, 3Mbps up, to less than 1Mbps down and up.  
Now that I am working from home, this has caused me a unique problem when running my team's Docker compose files, which builds 10+ services using `dotnet test` and `dotnet restore` on OSX.  
What runs in 30 seconds for my teammates, ran for over an hour on my machine without reaching the end.

It's very worth noting that this problem with my internet only occurs *when uploading a large file or using `dotnet restore`* and not at any other time.  It *does not occur from reaching my peak download speeds*.

## Example errors: 

> Failed to download package 'Microsoft.NetCore.Analyzers.2.9.8' from 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.analyzers/2.9.8/microsoft.netcore.analyzers.2.9.8.nupkg'.
>    Received an unexpected EOF or 0 bytes from the transport stream.
>   Failed to download package 'runtime.native.System.4.0.0' from 'https://api.nuget.org/v3-flatcontainer/runtime.native.system/4.0.0/runtime.native.system.4.0.0.nupkg'.
>   The download of 'https://api.nuget.org/v3-flatcontainer/runtime.native.system/4.0.0/runtime.native.system.4.0.0.nupkg' timed out because no data was received for 60000ms.
>     Exception of type 'System.TimeoutException' was thrown.
>   Failed to download package 'System.Xml.ReaderWriter.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.xml.readerwriter/4.3.0/system.xml.readerwriter.4.3.0.nupkg'.
>    Received an unexpected EOF or 0 bytes from the transport stream.
>   Failed to download package 'System.Runtime.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.runtime/4.3.0/system.runtime.4.3.0.nupkg'.
>   The download of 'https://api.nuget.org/v3-flatcontainer/system.runtime/4.3.0/system.runtime.4.3.0.nupkg' timed out because no data was received for 60000ms.
>     Exception of type 'System.TimeoutException' was thrown.
>   Failed to download package 'System.Reflection.Primitives.4.3.0' from 'https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.3.0/system.reflection.primitives.4.3.0.nupkg'.
>   The download of 'https://api.nuget.org/v3-flatcontainer/system.reflection.primitives/4.3.0/system.reflection.primitives.4.3.0.nupkg' timed out because no data was received for 60000ms.
>     Exception of type 'System.TimeoutException' was thrown.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet restore

NuGet version (x.x.x.xxx): 5.5.0.4

dotnet.exe --version (if appropriate): 3.1.201

OS version (i.e. win10 v1607 (14393.321)): macOS Mojave 10.14.6

## Detailed repro steps so we can see the same problem

1. Have my internet connection.

2. run `dotnet restore` on a project in an environment that does not have any nuget packages cached.

**Comment by rrelyea** [comment]
generally, our goal is to saturate the CPU and network as much as possible for as long as restore is running. (as opposed to taking 50% of the bandwidth and doubling restore time)

That said, perhaps in your network situation that doesn't work well? 
Perhaps `dotnet restore --disable-parallel` would use fewer threads, and therefore slow down how many network requests are happening in parallel?

**Comment by jaypeeZero** [comment]
@rrelyea I have tried adding `--disable-parallel` and it has no effect on the problem.  
Currently I'm testing throttling my own upload speed using Network Link Conditioner, which is an XCode tool.  This appears to save my internet connection (I don't drop below 1Mbps down when using `dotnet restore`), but does not seem to effect the speed of nuget package downloads.  

I'm actually confused about one aspect of this.  My network connection issue is reproducible *when using peak upload bandwidth*, so why does nuget have this problem *when downloading packages*?  No other application I use has *any* issues when reaching my peak download speeds.

**Comment by jaypeeZero** [comment]
Throttling my upload bandwidth to 400kbps appears to allow `dotnet restore` to work, albeit very, very slowly.  
My download bandwidth is currently unthrottled (and according to various speed test sites should be reaching my full 12Mbps/down speeds).  
So, **downloading** nuget packages seems very clearly linked to my internet's **upload** speed.

**Comment by zkat** [comment]
Unfortunately, this sort of thing is out of our control: We rely on underlying libraries for our networking, which in turn rely on your operating system for managing this stuff. I don't think there's anything actionable on our end here, as much as I wish there were something we could do to help. If your network connection is cutting off download streams, that's kinda beyond our reach.

It sounds like that's something to discuss with your ISP and how it reacts to saturated connections.
