### ISSUE TITLE
Print which feed a package was resolved from

### ISSUE THREAD

**Issue by tdykstra** [NuGet/Home#9479]
Transferred from https://github.com/dotnet/docs/issues/12713

The request is to show which feed a package was resolved from when .NET Core CLI command `dotnet restore` is run either explicitly or implicitly.

**Comment by nkolev92** [comment]
Dup of https://github.com/NuGet/Home/issues/7691

**Comment by KirillOsenkov** [comment]
I don't think it's a dupe of 7691. 7691 is about printing the local location of the package on disk and this one is which feed the package came from.

**Comment by zivkan** [comment]
This issue is a dupe of https://github.com/NuGet/Home/issues/3055

**Comment by KirillOsenkov** [comment]
@zivkan I don't think so. The fix in https://github.com/NuGet/NuGet.Client/pull/3700 prints only when the package is installed into the global package cache. But it doesn't print when the package is used during restore.
