### ISSUE TITLE
NuGet.Indexing 5.6.0 preview 3 and later use a different public key token

### ISSUE THREAD

**Issue by mrward** [NuGet/Home#9481]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):  5.6.0 preview 3

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:  5.6.0 preview 2

## Detailed repro steps so we can see the same problem

NuGet.Indexing 5.6.0 preview 3 and rtm published on https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json no longer have the NuGet public key token 31bf3856ad364e35 but have another Microsoft public key token b03f5f7f11d50a3a.

Bad:

https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/nuget.indexing/5.6.0-preview.3.6558/nuget.indexing.5.6.0-preview.3.6558.nupkg

https://dotnetmyget.blob.core.windows.net/artifacts/nuget-build/nuget/v3/flatcontainer/nuget.indexing/5.6.0-rtm.6565/nuget.indexing.5.6.0-rtm.6565.nupkg

OK: 

https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/nuget.indexing/5.6.0-preview.2.6532/nuget.indexing.5.6.0-preview.2.6532.nupkg

VS Mac builds are currently failing when verifying the binding redirect in place:

```
In VisualStudio.exe.config: publicKeyToken 31bf3856ad364e35 from bindingRedirect for NuGet.Indexing doesn't match actual assembly b03f5f7f11d50a3a
```

NuGet.Indexing 5.6.0 preview 2 on nuget.org and the dotnet-core NuGet package source have the expected NuGet public key token - 31bf3856ad364e35

NuGet.Indexing seems to be the only assembly affected.

Not sure if this is expected or not - seems unexpected since preview 2 and older versions used the NuGet public key token.

**Comment by nkolev92** [comment]
Probably a consequence of https://github.com/NuGet/NuGet.Client/pull/3309. 

It wasn't intentional. 

Given how late we are in the 5.6, don't think we'd consider another insertion, but maybe we can fix the packages. 

cc @aortiz-msft Thoughts? 

The mean time, I'd take the downgrade and use 5.5 of indexing. We haven't really changed any functionality there.

**Comment by nkolev92** [comment]
@mrward Do you use the previews or stable releases in VS4Mac?

**Comment by mrward** [comment]
@nkolev92 Usually we use stable releases but we needed to update to 5.6 preview to get .NET 5 support working.

It is not a problem for us - was just logging it since it seemed wrong that the token had changed and was something that might be affecting other things.

**Comment by nkolev92** [comment]
Ahh, ok. 
Thanks for the clarification.
This helps me prioritize it correctly.

I'll revert it back to the old key, but I'll only do that in 5.7 then.
