### ISSUE TITLE
Add `-binlog` switch to build.ps1

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9482]
Binlogs are useful to debug builds. It should be easier to get this with NuGet's build script.

**Comment by kartheekp-ms** [comment]
Thanks @zivkan for creating this issue. Couple of days we reported an to issue to .NET tools team about  `.NET Core SDK` resolved `16.4 version of MSBuild` even though `Microbuild` team confirmed that the machine has `16.5 version of msbuild.exe`. In response to our request, .NET team asked us provide `binlog of the restore operation to capture more information the next time this happens`. Can we this switch in our CI/CD pipeline?

**Comment by zivkan** [comment]
Our CI doesn't use `build.ps1`.

In order to get binlogs on CI, in the relevant places in our YAML that use the msbuild task, we need to use the `-bl` switch, and anywhere we call msbuild indirectly (like E2E test's `runFunctionalTests.ps1`), we need to modify the script to use `-bl`). Finally, we need to modify the yaml to publish the binlog files as a build artifact, so we can access it.  Let's do it as a separate issue/PR.
