### ISSUE TITLE
Force reinstall package TFS build server

### ISSUE THREAD

**Issue by nicoleta-scrimint** [NuGet/Home#949]
Hi,

I have the following situation:
-	I use a Nuget package to share common functionality between internal product components.
-	This package is located at the relative path “..\..\..\..\Packages\” computed from the subfolder “.nuget” under the solution folder. The solution is configured to restore on build the missing packages, by choosing the option from right click solution "Enable Nuget Package restore"
-	Firstly, I checked-in the product solution with using the package with version 1.0.0. The TFS build succeeded.
-	After a day, based on some new insights, I modified the package still I did not give it a new version and it remained the version 1.0.0, because the changes I made were actually making part of the version 1.0.0
-	Locally on my machine, I cleared the Nuget cache from Visual Studio, I reinstalled the package, I saw that the new changes from the version 1.0.0 are downloaded in the local Packages folder and the local build in Visual Studio worked fine
-	The issue is that the TFS build fails because it still looks at the package with the old changes. It seems that the TFS build agents always use the same location and the old package is still at this location, this is why the package is not reinstalled in the TFS build server.
Extract from the TFS build log file:
“Project "...\ProductSolution.sln" (1) is building 
...
RestorePackages:
  "...\.nuget\NuGet.exe" install "...\ProjectName1\packages.config" -source "https://www.nuget.org/api/v2/;otherSource"  -NonInteractive -RequireConsent -solutionDir "SolutionPath"
  Restoring NuGet packages...
  To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
  All packages listed in packages.config are already installed.”
Note: We do not have access to the TFS build server to delete manually the package folder.

I read on the article "https://docs.nuget.org/consume/reinstalling-packages" that I can force reinstall a package, still the command "Update-Package –reinstall <packageName>" can be executed from the Nuget Package Manager Console in Visual Studio and not from the nuget.targets, where I found that the command to restore a package is "nuget install", which is used to install a package from command line.

Could you please help me in forcing reinstall a package on the TFS build server, by changing the nuget.targets or by creating a PowerShell script which can be executed in the TFS build as a prebuild action?
I suppose that the PowerShell script to be used in the TFS build would use the Nuget command line reference.

I mention that we use TFS Foundation Server 2013, where we can use PowerShell scripts for prebuild and postbuild actions in the TFS build definition.

Thank you for your support.

**Comment by yishaigalatzer** [comment]
The suggestion is to use pre-release monikers until you actually are 100% ready to release a package. So call your package 1.0.0-beta-0001 for example and rev it until you are done.

On the TFS build, just clean out the old package cache if you are stuck in this mode. Assuming that the package authoring itself didn't change, you don't need to reinstall/update, just wipe out the cache on the build ci every time.

**Comment by nicoleta-scrimint** [comment]
I like your solution for using pre-release monikers. Thank you for this solution!

Regarding cleaning out the package cache in the TFS build server, do you know any approach of doing this regarding the fact I do not have access to the TFS build server machine? You think of an approach related to some nuget commands in the nuget.targets file?

Thank you!

**Comment by yishaigalatzer** [comment]
I thought your can run powershell scripts ahead of the build (or at least in early stages). Just wipe the packages folder clean, and restore should bring down the latest package.

Like I mentioned above, its pretty tricky to run with the same package id and version regardless of if you can find a forcing solution, because you end up with multiple packages looking the same with nothing but a fragile timestamp to tell you which is which.

BTW even for RTM builds you marked the pacakges with -rtm-buildnumber, and only switch over when you are done.

**Comment by nicoleta-scrimint** [comment]
I understand. Thank you very for your solution! You were very helpful!
