### ISSUE TITLE
Does NuGet work with .net core?

### ISSUE THREAD

**Issue by bsweb** [NuGet/Home#9494]
Hi,

I have created a few simple .net core apps recently. I have just started to use on a bigger project and NuGet just doesn't seem to work.
It *installs* the package but no files are downloaded. This has happened for Typescript and Knockoutjs to name 2.
Should we be abandoning NuGet for other package managers?

Thanks.

**Comment by rrelyea** [comment]
NuGet definitely works with asp.net core, but is more focused on dependencies, not client side libraries.

LibMan may be helpful: https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/?view=aspnetcore-3.1

You may want to check with some people in this repo: https://github.com/dotnet/aspnetcore/issues (and you could help update info here?)

**Comment by bsweb** [comment]
Thanks for the update.

Libman has only got half the solution as it appears to be missing all the Typescript DefinitelyTyped for example.

If knockoutjs doesn't work with via NuGet with aspnetcore, should it not be hidden from the install options? Or are you saying this is a aspnetcore issue or a visual studio (NuGet Package Manager) issue? Just trying to understand how this works.

Thanks.

**Comment by zkat** [comment]
You'll need to use two package managers: NuGet for csharp libraries, and NPM (or one of its alternatives) for any client-side JavaScript/TypeScript/etc libraries. NuGet won't handle both, by design, and this is a pretty standard expectation across ecosystems.
