### ISSUE TITLE
[CPVM backcompat] Patch older tools to warn, error when a project is opt in cpvm

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9497]
Once a project is opt in CPVM its Version attributes are removed. Old clients will emit an warning in such cases.

This issue is to track any work needed to patch old version of tools like nuget.exe, VS to error/warn when a file is opted in cpvm.

**Comment by zkat** [comment]
We probably will not be addressing this because we're unlikely to patch older clients for any reason other than very severe issues.
