### ISSUE TITLE
There should be a better way to handle ATF

### ISSUE THREAD

**Issue by sbanni** [NuGet/Home#9499]
Currently our project system wants to have all types of references and we have to continue adding values to AssetTargetFallback to support this.  It would be ideal if there was a supported way to just include ALL values with possibly an exclusion list instead of having to opt into each one.

**Comment by nkolev92** [comment]
@sbanni 

Just to make sure I understand this ask, you have a project type that's technically compatible with all target frameworks, because it really only works with the already built artifacts (wapproj being that project)

**Comment by sbanni** [comment]
@nkolev92 Yes your understanding is correct.

**Comment by nkolev92** [comment]
Duplicate of https://github.com/nuget/home/issues/5272.
