### ISSUE TITLE
Solutions with a mix of packages.config and project.json (eg C++/CX and C#) project do not work correctly

### ISSUE THREAD

**Issue by damyanp** [NuGet/Home#950]
Create a new solution with a C# UWP - this uses project.json and installs nuget packages to %USERPROFILE%.

Install a nuget package (eg Win2D) to this project.

Add a new C++/CX UWP project to this solution.  This uses packages.config.

Now install the same nuget package to the second project.  The packages.config project's project file is updated to import the props/targets from "..\packages" which is incorrect, since the packages are actually installed to %USERPROFILE%.

**Comment by yishaigalatzer** [comment]
@damyanp the packages are actually installed to both places. Can you please reply if you are seeing something different?

**Comment by damyanp** [comment]
I also see the correct behavior now.  But I definitely saw the incorrect behavior when I first added it to the CX project when there was already an existing reference in the CS project.  I’ve tried various combinations of doing these things in the wrong order and haven’t been able to repro.
