### ISSUE TITLE
`nuget list` should support filtering for specific package name

### ISSUE THREAD

**Issue by cdmihai** [NuGet/Home#9512]
Missing capability: use nuget to list all the package versions from a given feed, for a given package name.

Workarounds are all tedious:
- listing all package can be super slow, taking tens of minutes on huge feeds
- installing the package requires cleanup afterwards

Most of the other package managers have such a feature.

**Comment by nkolev92** [comment]
Dup of: https://github.com/NuGet/Home/issues/5138.
