### ISSUE TITLE
Bad server leads to nullrefs

### ISSUE THREAD

**Issue by yishaigalatzer** [NuGet/Home#952]
Include the follow source and do a project.json restore

http://api.nuget.org/v3/registration0/1.0.0/index.json - this is a json file that is not a service index, which leads to the client getting confused and nullref-ing. Discovered accidentally by pasting the wrong URL into the source list

results:
Null ref exceptions

**Comment by xavierdecoster** [comment]
Is this nuget.exe restore or VS right-click on References node > Restore Packages?
Are you using the bad URL in the sources list of the options dialog or in nuget.config?

**Comment by yishaigalatzer** [comment]
VS, I suspect it will show up in other places as well. need some trial and error here.

**Comment by xavierdecoster** [comment]
Haven't been able to repro this one yet. Using the above faulty index.json results in regular 404s, no nullrefs.

> Warning: FindPackagesById: Fake.Component
>   Response status code does not indicate success: 404 (Not Found).
>   GET http://api.nuget.org/v3/registration0/1.0.0/index.jsonFindPackagesById()?id='Fake.Component'
> Error: FindPackagesById: Fake.Component
>   Response status code does not indicate success: 404 (Not Found).
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).

**Comment by yishaigalatzer** [comment]
I would suspect it is already fixed somehow.
