### ISSUE TITLE
VSTemplateWizard to perform a design time build if the vs template has a 'forceDesignTimeBuild' attribute

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#953]
VSTemplateWizard to perform a design time build if the vs template has a 'forceDesignTimeBuild' attribute in the 'WizardData' element of the .vstemplate file. NuGet's VSTemplateWizard should perform the design time build after installing the packages as part of IWizard.ProjectFinishedGenerating

**Comment by yishaigalatzer** [comment]
@deepakaravindr please hold on to this PR, but lets not commit it (even to 3.2) without further discussion with managed languages team to decide if we are taking it or not

**Comment by deepakaravindr** [comment]
OK. Will hold off on this

Sent using OWA for iPhone
________________________________

**Comment by deepakaravindr** [comment]
Fixed with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/217352b3770a42ec932b7bc0c9e7a60a6bc2ae9b

**Comment by deepakaravindr** [comment]
Will close after updating docs.nuget.org

**Comment by deepakaravindr** [comment]
Created https://github.com/NuGet/NuGetDocs/pull/361 to update documentation
