### ISSUE TITLE
Test: SimpleBindingRedirectsNonWeb is flaky

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9531]
Test `SimpleBindingRedirectsNonWeb ` is flaky and it times out after 10 minutes on certain CI machines (w001 and w004) for many times.
If logging onto the CI machine during the E2E test, we can see the test hangs as following:
![image](https://user-images.githubusercontent.com/45407901/81082499-33077c80-8ea8-11ea-89fe-18af6592d626.png)

**Comment by zivkan** [comment]
This is a duplicate of https://github.com/NuGet/Home/issues/8402
