### ISSUE TITLE
Regression: RuntimeJsonFormat.WriteRuntimeGraph writes invalid JSON

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#9532]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
NuGet API

NuGet version (x.x.x.xxx):
5.6.0-preview.3.6558

Worked before? If so, with which NuGet version:
Yes, 5.5.1

## Detailed repro steps so we can see the same problem

1. Call `RuntimeJsonFormat.WriteRuntimeGraph(file, graph)` to write a RuntimeGraph to file.

2. Call `RuntimeJsonFormat.ReadRuntimeGraph(file)` to read the file from 1.

Expect:
**Success**

Actual:
```
Unhandled exception. System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(JToken json)
   at NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(TextReader textReader)
   at NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(Stream stream)
   at NuGet.RuntimeModel.JsonRuntimeFormat.ReadRuntimeGraph(String filePath)
```
If you examine the `file` you can see that `WriteRuntimeGraph` no longer includes the top-level object.  It writes `"runtimes": { ... }` instead of `{ "runtimes": { ... } }`

### Sample Project
[runtimeTest.zip](https://github.com/NuGet/Home/files/4581990/runtimeTest.zip)

The bug is here: https://github.com/NuGet/NuGet.Client/commit/657aa2d254f85b5636ac7ac03c476b2a5079649a#diff-a929422d44edcc504a3beaf00e6cbf14L42

The WriteObjectStart method used to create a new JObject, add a property to that object and start a new object for that property, but now it only writes a property and starts an object for that property.

The WriteRuntimeGraph method assumes that WriteObjectStart will create the root object.
https://github.com/NuGet/NuGet.Client/commit/657aa2d254f85b5636ac7ac03c476b2a5079649a#diff-360db93f4ab729027d7a199a4ab6c1c4R67-L103

/cc @dtivel @nkolev92 @zivkan 

This is blocking uptake of NuGet (needed for new `net5.0` TFM) into dotnet/runtime since it broke our runtime.json generation.  I may be able to workaround this but I wanted to raise this regression. /cc @viktorhofer

**Comment by nkolev92** [comment]
cc @aortiz-msft this is a regression from some perf work in 5.5. 

~With the low usage of project.json (somehow it's still used),~ I don't expect this to be a problem in the product but it is a library breaking change.

**Comment by ericstj** [comment]
This regression is for runtime.json, not project.json.  I agree this is a rare case: the only folks who *write* runtime.json is essentially us (dotnet/runtime) so I wouldn't expect this to impact many/any  customers.

**Comment by nkolev92** [comment]
I mentioned project.json cause technically it's the only production scenario in which NuGet tries to write a runtime graph itself. 

Although in the pj scenario we don't write it individually so there's no way it breaks.

**Comment by marcin-krystianc** [comment]
I think it can be now closed - fixed in https://github.com/NuGet/NuGet.Client/pull/3934/files#diff-bfa969da7a62c48ed11cdb86eb6cff4b3e61c77d6dbc80759ca510d6d1fa8775

**Comment by ericstj** [comment]
Indeed it looks like it.  TFTF!
