### ISSUE TITLE
Generate nuget.config file from NuGet CLI

### ISSUE THREAD

**Issue by doggy8088** [NuGet/Home#9539]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `NuGet.exe`

NuGet version (x.x.x.xxx): `5.5.1.6542`

dotnet.exe --version (if appropriate): `3.1.201`

VS version (if appropriate): `Visual Studio 2019`

OS version (i.e. win10 v1607 (14393.321)): `Microsoft Windows [Version 10.0.18363.778]`

Worked before? If so, with which NuGet version: `No.`

## Detailed repro steps so we can see the same problem

`N/A`

## Other suggested things

In `npm`, there is a `npm init -y` command that can generate a default `package.json` file.

In `tsc` (TypeScript), there is a `tsc --init` command that can generate a default `tsconfig.json` file.

I think `nuget` (NuGet CLI) should have something like that to generate a default `nuget.config` file.

I know .NET Core CLI have something like this: `dotnet new nugetconfig`. But there is no equivalent CLI argument to generate a default `nuget.config` file just like .NET Core did. e.g. `dotnet new nugetconfig`

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

`N/A`

### Sample Project

Very helpful if you can zip a project and paste into this issue!

`N/A`

**Comment by donnie-msft** [comment]
Created an epic to track overall design of the CLI experience around configs, which is currently lacking even on dotnet.exe. 

I pinged some folks offline and it sounds like we would focus primarily on dotnet.exe. Can you elaborate why you'd prefer nuget.exe have these capabilities in addition to dotnet.exe ?

**Comment by doggy8088** [comment]
@donnie-msft For someone who doesn't use .NET Core yet, and they are still using .NET Framework. How can they generate `nuget.config` easily?

**Comment by zivkan** [comment]
You don't need to use .NET Core to install or use the dotnet cli.

**Comment by zivkan** [comment]
Another easy way, using powershell, is:

```powershell
"<configuration></configuration" > nuget.config
```

then you can use nuget.exe to add sources, set config, etc.

**Comment by doggy8088** [comment]
@zivkan Thanks! I know that actually. I just feel `nuget init`, `nuget config init` or `nuget --init` is much more elegant.

**Comment by nkolev92** [comment]
@doggy8088 We'd be happy to accept a contribution. 

Please refer to our contributing guide at https://github.com/NuGet/NuGet.Client/blob/dev/CONTRIBUTING.md and specifically to our `New Feature Guide`.

**Comment by ruifrvaz** [comment]
@zivkan correct me if i'm wrong, but there are cases where having this option is still useful for .net core devs. I have a .net core project and am using azure devops to build a pipeline with a yml file. This process uses a package restore task that is limited to accepting 1 feed. Since my project uses multiple feeds, i have to use a nuget.config file to restore packages, which doesnt exist in a .net core solution. So it is still great to have an option to generate a nuget.config file from a .net core project.

**Comment by zivkan** [comment]
@DigIntSys the dotnet cli already has [`dotnet new nugetconfig`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new) (the docs say this was added in the 1.0 SDK, so ever since .NET Core existed), [`dotnet nuget add source`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source) (added in SDK version 3.1.200).

But I highly recommend commiting your nuget.config into your repo. I don't understand why you'd want to regenerate it every CI build.

**Comment by ruifrvaz** [comment]
thanks for the feedback @zivkan . it seems to be the default behavior for .net core projects not to have a nuget.config file and we never needed it until now. i suppose we are relying on the shared nuget.config for our local development and never thought about the implications. ill see what we can do.

**Comment by aidapsibr** [comment]
@zivkan a good reason for not committing that file is if you have proprietary sources or packages with secrets that could leak. It's more of an edge case, but technically an authenticated nuget source is a secret and shouldn't be checked into source control.

**Comment by nkolev92** [comment]
@aidapsibr 

Source uri declaration can be independent from authentication for said source. 

NuGet provides a lot of different extensibility to address that. From hierarchical configs, to plugins. https://docs.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds

**Comment by Alex2357** [comment]
> [`dotnet new nugetconfig`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new)

Thanks that's what I was looking, but this is very frustrating that the command is not under dotnet nuget as the very first thing I have checked `dotnet nuget --help` and nothing is in there. Any other approaches did not like as I wanted to do via `dotnet` cmd

**Comment by doggy8088** [comment]
The `"<configuration></configuration>" > nuget.config` is not working any more. Let's leave a note here:

```ps1
'<?xml version="1.0" encoding="utf-8"?><configuration><packageSources><clear /></packageSources></configuration>' | Out-File nuget.config -Encoding utf8BOM
```

**Comment by nkolev92** [comment]
Not sure what you mean by that @doggy8088. 

Re-opening this issue as it's not fixed.

**Comment by doggy8088** [comment]
@nkolev92 
I expected the following command should append new package source to local `.\NuGet.config` file, but it doesn't. It added to the Global NuGet.config file.

![image](https://user-images.githubusercontent.com/88981/153974628-87c363b6-19b6-4450-a976-da88616091ff.png)

The `nuget sources add -h` said: ` If not specified, the hierarchy of configuration files from the current directory will be used. `

```txt
-ConfigFile  The NuGet configuration file. If specified, only the settings from this file will be used. If not spe
             cified, the hierarchy of configuration files from the current directory will be used. To learn more a
             bout NuGet configuration go to https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nu
             get-behavior.
```

**Comment by nkolev92** [comment]
@doggy8088 Currently, that's expected behavior. 

If you do not pass a config file, NuGet will pick the least specific configuration, which because your in repo config doesn't have a `clear`, becomes the user specific one.

**Comment by doggy8088** [comment]
@nkolev92 I thought `the hierarchy of configuration files from the current directory` means `the nearest configuration files from the current directory`. Since I already have a `NuGet.config` in the current directory, why doesn't this file been applied as the default config file?

**Comment by nkolev92** [comment]
Because you don't have a `clear` element. All your sources are probably declared in your user wide configs, so that one is added there as well.

**Comment by doggy8088** [comment]
The NuGet configuration will be applied multiple files. If there is no `clear` been defined in the local NuGet.config file, the configuration will inherit from global NuGet.config file first, then append local NuGet.config. If I want to add a new nuget source for my project, I expected the new source should be added to local NuGet.config file, but the global one. I thought it's a common sense.  Tell me if I'm wrong.

**Comment by nkolev92** [comment]
Please refer to https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied.
When the files are used, they are starting with the closest first, until you find a clear for the section. If you don't find a clear, they are all considered.

When you are *adding* a source without specifying an exact file it adds it to the *least* specific configuration,
Given that there's no clear for the packageSources, it ends up all the way in the user wide configuration.

**Comment by doggy8088** [comment]
As the document said, `NuGet's behavior is driven by the accumulated settings in one or more NuGet.Config (XML) files that can exist at project-, user-, and computer-wide levels.`. Also this, `These settings collectively apply to any NuGet operation invoked from the command line or from Visual Studio, with settings that exist "closest" to a project or the current folder taking precedence.`.

The "closest" nuget.config should be the `Solution` scope NuGet.config. I'm just curious why setting the "closest" nuget.config have to append `-Config .\NuGet.config` to the command.

**Comment by nkolev92** [comment]
The settings closest do take precedence. But you're not applying settings. 

You're adding new ones. 

I don't have all the details that went into that decision making, as this has always been the behavior, https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources#options.

**Comment by nkolev92** [comment]
Team Triage: 

NuGet.exe does not ship within Visual Studio or MSBuild today. 
The .NET SDK, and thus dotnet.exe, ships within most workloads that you use to build projects with the latest versions of Visual Studio today. 
If possible, we recommend using dotnet.exe new nugetconfig to generate configs. 

We don't think this is something we want to invest into right now, but we'd happily consider a community contribution.
