### ISSUE TITLE
Hook up FeatureFlags for PMUI in CodeSpaces

### ISSUE THREAD

**Issue by mirkomuggli** [NuGet/Home#9545]
As part of enabling PMUI for Codespaces, we've now listed as a Feature in Tools->Options->Preview Features (the VS PR to enable this flag is here: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/247442)

In PMUI, we should check this feature flag before enabling the "Manage Nuget Packages" menu item when connected to Codespaces.

**Comment by rrelyea** [comment]
closing until we are sure we need this. ideally, we just make it work and it all just lights up.
