### ISSUE TITLE
[Bug Bash][Test Failure] The “Browse” tab is not aligned left with search box

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#9559]
## Details about Problem
VS Version: Master\30112.146
OS Version: Windows-10-Enterprise-RS5.
NuGet Version: Dev\5.7.0.6611
## Installiation
Install VS: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3723092&view=ms.vss-build-web.run-extensions-tab
## Repro steps
1.  Launch Visual Studio 2019 preview.
2. Click “Create a New Project” button and create a new Console App (.Net Core) project.
3. Observe the position of “Browse” tab. 
## Expected
The “Browse” tab should be aligned left with search box.
## Actual
The “Browse” tab is not be aligned left with search box.
![NotLeftAligned](https://user-images.githubusercontent.com/40230425/81796716-68633880-9540-11ea-99e5-a04c4b4a292d.png)

**Comment by donnie-msft** [comment]
This is due in part to the tab's inner width/padding. If we really want this alignment, we could remove the left padding/margin and set the horizontal alignment to the left.

15.x was left-aligned, but haven't checked how far back into 16.x this was aligned, if ever. Likely, my new [TabControl](https://github.com/NuGet/NuGet.Client/pull/3238) introduced this.

15.x:
![image](https://user-images.githubusercontent.com/49205731/81833877-405ae180-950e-11ea-84f5-d2cec2f60e05.png)

**Comment by v-luzh** [comment]
Fixed on NuGet Dev\5.7.0.6632. Thanks.
