### ISSUE TITLE
No way to use nuget v3 on a machine without Dev14

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#956]
Nuget.CommandLine.Cmd has static depenedencies on Microsoft.Build v14 and Microsoft.Build.Framework v14 and dnx will only search for those in the GAC (despite what it says about all the places it searched, procmon shows that it only hit the GAC).  This has prevented me from consuming nuget v3 from our build servers.  We should either fix the probing behavior or make this a lightup dependency.  Alternatively, use MSBuild assemblies at version 4.0.0.0 which are part of the inbox framework if you don't need any of the new surface area.

**Comment by davidfowl** [comment]
> Alternatively, use MSBuild assemblies at version 4.0.0.0 which are part of the inbox framework if you don't need any of the new surface area.

That's actually wrong. MSBuild 4.0.0.0 can't properly compile newer MSBuild >= 12 projects. For the specific details, see https://github.com/OmniSharp/omnisharp-roslyn/issues/202#issue-72319706. 

If they made a NuGet package for the OSS MSBuild, everyone would be better off.

**Comment by yishaigalatzer** [comment]
@ericstj I guess for now you will have to GAC msbuild14 on the build server. We will take a look at reducing the dependency

**Comment by pranavkm** [comment]
Discussed this with Jason @davidfowl offline - we're going with launching `msbuild.exe` with the option to specify the path to it. We'll default to MsBuild 14.0, but restore now accepts a parameter that lets you switch.
