### ISSUE TITLE
How did you get the PackageVersion?

### ISSUE THREAD

**Issue by chucklu** [NuGet/Home#9560]
## Details about Problem

https://github.com/kerryjiang/SuperSocket/runs/669537495?check_suite_focus=true
The version "2.0.0-preview3(a0348157292533798b77690ab683d2e06f7fa1b2)" you get is used as production version. How could it become a package version? I suppose you will get the file version as the package version which is "2.0.0-preview3".

The version was defined in https://github.com/kerryjiang/SuperSocket/blob/a0348157292533798b77690ab683d2e06f7fa1b2/Directory.Build.props.
I can modify the format of production version to "2.0.0-preview3-a0348157292533798b77690ab683d2e06f7fa1b2", then the pack procedure will complete successfully.
I would like to know if it is possible keep the previous production version, and **get package version from file version** instead of production version.

/usr/share/dotnet/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(77,5): error MSB4018: The "GetPackOutputItemsTask" task failed unexpectedly. [/home/runner/work/SuperSocket/SuperSocket/src/SuperSocket.WebSocket.Server/SuperSocket.WebSocket.Server.csproj]
/usr/share/dotnet/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(77,5): error MSB4018: System.ArgumentException: **PackageVersion string specified '2.0.0-preview3(a0348157292533798b77690ab683d2e06f7fa1b2)' is invalid**. [/home/runner/work/SuperSocket/SuperSocket/src/SuperSocket.WebSocket.Server/SuperSocket.WebSocket.Server.csproj]

### Sample Project

Very helpful if you can zip a project and paste into this issue!
https://github.com/kerryjiang/SuperSocket/commit/a0348157292533798b77690ab683d2e06f7fa1b2

**Comment by zivkan** [comment]
[SemVer2](https://semver.org/) is strict on what characters it allows in a version string, and neither `(` nor `)` are allowed. As per the SemVer2 website, build metadata, such as the commit hash, can be put in the metadata field, which is prefixed with the `+`. So the version string `2.0.0-preview.3+commithash` would be ok.

Also note that if you ever have more than 9 previews, then using `preview9` and `preview10` will not sort the versions correctly. As per the SemVer2 spec, there should be a period `preview.9`, `preview.10`.

**Comment by chucklu** [comment]
@zivkan I did not specify the Package Version, you get the `production version` as package version.
**My question is why you use `production version` for package version**, I have another version `file version`, and the file version is 2.0.0.
I expect nuget pack use the` file version` as the package version instead of package version.

**Comment by zivkan** [comment]
NuGet uses `Version`, if `PackageVersion` isn't already defined: 
https://github.com/NuGet/NuGet.Client/blob/788bc01a1b063a37841cdd6d035feb320e90e475/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L28

The .NET SDK uses `VersionPrefix` and `VersionSuffix` when `Version` is not defined:
https://github.com/dotnet/sdk/blob/2eb6c546931b5bcb92cd3128b93932a980553ea1/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.DefaultAssemblyInfo.targets#L14-L18

Cloning your repo, checking out the commit that fails, and doing a pack with the `-bl` argument to get a msbuild.binlog file that I can open with the [MSBuild log viewer](https://github.com/KirillOsenkov/MSBuildStructuredLog/releases), I can see that the package `unclassified.netrevisiontask` is setting the `PackageVersion` property to this value that is not SemVer2 compliant.

As that package is not an official NuGet or Microsoft product, I stopped my investigation here.

**Comment by chucklu** [comment]
@zivkan  Thanks for your investigation, I will figure out  the problem with netrevisiontask.

**Comment by chucklu** [comment]
NetRevisionTask define the package version as informational version, that's the problem. I will negotiate with the author.
https://github.com/ygoe/NetRevisionTask/blob/c619ac946ccca1feeafb917596703ee8f08d697e/NetRevisionTask/build/Unclassified.NetRevisionTask.targets#L47
```xml
<PropertyGroup>
      <FileVersion>$(Version)</FileVersion>
      <PackageVersion>$(InformationalVersion)</PackageVersion>
    </PropertyGroup>
```
