### ISSUE TITLE
Bring `config` CLI experience to dotnet.exe for managing `nuget.config` files

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9571]
Design of an improved CLI experience for manipulating nuget.configs.

Today, there's `dotnet new nugetconfig` which copies a template. The `<clear />` isn't removable.

**Comment by JonDouglas** [comment]
@donnie-msft Is this specifically needed for the .NET team or just a `dotnet CLI` parity / feature enhancement?

**Comment by JonDouglas** [comment]
In other words, we want to create https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-config but for `dotnet CLI`?

**Comment by donnie-msft** [comment]
I created this based on the linked issues (21 upvotes!)
/cc @dominoFire whose area is CLI and @heng-liu for cross-plat

**Comment by nkolev92** [comment]
Is this referring to `dotnet nuget config` or something different?

dotnet nuget config is now available, so I'm wondering if this is referring to something different? https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-config-get

**Comment by donnie-msft** [comment]
@nkolev92 this issue was created 4 years before `dotnet nuget config` existed. I guess it wasn't closed as part of that work.

**Comment by nkolev92** [comment]
That's what I expected. 
Thanks @donnie-msft 

Closing
