### ISSUE TITLE
[Test Failure] Closing invalid Nuget.config xml box hangs VS

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9574]
## Details about Problem
NuGet version: NuGet Client Dev\5.7.0.6612
VS Version: Master\30114.135
OS Version: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Go to %appdata%\nuget\Nuget.Config
2. Open Nuget.Config and edit the file so that it contains invalid xml. In this case, mine contains multiple root level elements.
3. Close Nuget.Config and open VS
4. Create a new ASP.NET (NET core) web app.
5. The window below appears. Close it
## Expected
The window closed successfully without VS hanging.
## Actual
VS hangs as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/82193957-b1dcca80-9928-11ea-9606-a2962cb41cf3.png)
## Dump:
\\\mlangfs1\public\v-masche\dumps\NugetConfig.dmp
## Note:
1.This bug can be repro on both 16.3 (D16.3\29303.96—repro rate: 100%) and 16.6 (VS Master\29905.127 + NuGet Client Dev\5.6.0.6489 – repro rate: 50%).
2.Move from internal bug 976738.

**Comment by erdembayar** [comment]
@nkolev92  @aortiz-msft 
Is it compatibility tenet issue?

**Comment by aortiz-msft** [comment]
@v-luzh - Does this repro still?

**Comment by v-luzh** [comment]
It is fixed on Main\31820.317 + NuGet Client Dev\6.1.0.30. No crash happened. Close this issue now, thanks.
