### ISSUE TITLE
Issue with custom target file when package is referenced in multilevel hierarchy

### ISSUE THREAD

**Issue by archanasoni** [NuGet/Home#9575]
Hi,

We have native dlls to get bundled with nuget package targeting .NET Core 3.1. 
We are able to successfully package native dlls with our nuget package.
Our requirement is when package gets installed these native dll should get copied into Application bin directory..
To achieve this we have custom target file something like:
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <NativeLibs Include="$(MSBuildThisFileDirectory)**\*.dll" />
    <None Include="@(NativeLibs)">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>

This works fine when Proj B installs our package, but now suppose Project B is library and another Project C installs it then it will be something like Project C=>Project B=> Project A
Here Project A contains custom target file along with native dlls . These native dll must get copied in bin directory of Project C..

How can we achieve it ?

Also is there a way through which via assembly name we can get the Nuget Package info and installed location ? Please note this assembly will reside in Application bin directory... 

Regards,
Archana

**Comment by archanasoni** [comment]
Hi,

This issue is bit urgent for us. Customer is waiting to get resolution..
Can someone suggest whats the problem here.. ?

**Comment by zivkan** [comment]
I don't remember why it works the way it does, but there are 3 folders in the `nupkg` that NuGet checks for props and targets files: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory

Unfortunately it doesn't appear to be documented, or at least it's not clear enough, but files under `build/` are only used by projects that reference the package directly. If the package comes through transitively (it doesn't matter if it's via a project or another package), PackageReference projects will not use those `build/` files. Instead, your package should have your props and targets files in `buildTransitive/`.

I'm guessing this is the issue, as you didn't say in which folder your targets file is in the package (also you didn't put your xml in a code block, so it's not being shown). If this comment doesn't help, please provide more information about the package, and whether projects are using PackageReference or packages.config.

**Comment by archanasoni** [comment]
Thanks @zivkan .. it helped..
One more question- Our dll sits in Application bin path, Is there a way to know the package installation path from dll or assembly ?

**Comment by rrelyea** [comment]
@archanasoni  - if using packagereference, during restore, nuget creates obj\project.assets.json which but just points to copies of dll and .props/.targets in the global package folder (under %userprofile%\.nuget\packages by default)

During build, reference dlls are passed to the compiler based on entries that are listed in the assets file.

DUring build, reference dlls get copied into the bin\$(configuration) directory.

i think you are asking...during runtime, can you figure out where the package is?
answer: no, you are not using the copy of the dll in the global package folder...instead you are using the copy in the bin\$(configuration) directory.

@zivkan  - please chime in if i am not understanding.

**Comment by zivkan** [comment]
I also don't understand the new questions. As Rob said, runtime it shouldn't matter. Files should be copied to the build output directory, and if it's an application that gets deployed to a server, or installed on a customer's machine, there isn't going to be a NuGet global packages folder to look for.

If this is about finding the package directory from the MSBuild file, you can use [reserved MSBuild properties](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019) like `MSBuildThisFileDirectory`.

I would need a better explanation of the scenario give a better answer.

**Comment by archanasoni** [comment]
Thanks @zivkan and @rrelyea for your quick response and support..
Here is problem back ground:
We have .Net Core Library say LibA (it's driver like sqllite), this LibA is dependent on some C library(this we can take as C Driver for some database).
Since it's C we have dependency on Platforms.
So far we were keeping c Libraries in build folder of Nuget Package.. But Problem with this we found is if Proj A=> Proj B=> LibA (which is our package) ,  In bin directory of ProjA our C libraries of LibA doesn't get copied..

Problem with this is these C library gets loaded by LibA. Since we are unable to get path for C loading of our library it self is failing..
Now with buildTransitive option C Libraries are getting placed with Proj A as well..
But suppose some case where C Libraries are not in app bin.. we have to load it from Global installation path.. Thats where I asked at runtime how can we get the path of nuget Global installation folder..

I could read if native dlls we keep in runtime\RID\native  host automatically loads it.. 
But I'm not sure which will be faster and safer I mean Library loaded by us will be faster Or by Host..
Another doubt which I've is if multiple Applications are running Will Library loaded by Host have some clash ?
Can we place native database driver at runtime\RIC\native.. ?
if we take RID as WIN-X64, will our customer app or library have some problem ? Is it supported by all project types etc..

We need to select one path, Please advise recommended way to go ahead..

**Comment by zivkan** [comment]
This question is now more about how the .NET SDK works, rather than NuGet, which is outside of my knowledge. From NuGet's point of view, we select assets and write them into the project.assets.json, g.props and g.targets files. The SDK chooses where and when to copy those assets, and generate the .deps.json file that the runtime uses to know what to load when your program is executing.

@dsplaisted can you or someone in your team help?

**Comment by dsplaisted** [comment]
> But suppose some case where C Libraries are not in app bin

It sounds like if you use the `buildTransitive` folder for your .targets then the C libraries will be included.  So it seems like you don't have to worry about them not being included.

> I could read if native dlls we keep in runtime\RID\native host automatically loads it..

If you are targeting .NET Core, then I would recommend putting the native assets in the `runtime\<RID>\native` folder of the NuGet package instead of using a custom .targets file that includes those assets.  Using a `.targets` file is really a workaround for the fact that the runtime on full .NET Framework doesn't handle loading native assets for different architectures.  If you're just targeting .NET Core then you shouldn't need the .targets workaround.

**Comment by archanasoni** [comment]
Thanks @dsplaisted  and @zivkan  for your support..
Our Library is targeted to NETStandard 2.1.
In that case would it be good to go for runtime ? We are aware that FW is not supported by .NET Standard 2.1 but not sure other than .NET Core what other Frameworks support runtime\<RID>\native...

**Comment by zivkan** [comment]
The dotnet team have [docs mapping .NET Standard versions to runtime versions](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support), so you can see there what implements .NET Standard 2.1.

**Comment by archanasoni** [comment]
Thanks @zivkan , we can close this issue..
