### ISSUE TITLE
Inconsistent Circular Reference

### ISSUE THREAD

**Issue by joelmartinez** [NuGet/Home#9579]
## Details about Problem

We're publishing .NET reference at [Microsoft docs](https://docs.microsoft.com/dotnet/api/), and a new package release (Microsoft.Bot.Builder.AI.Luis) is causing some issues with a circular dependency. The dependency graph doesn't seem to indicate that there's actually a circular dependency, at least with the individual project's package ... the dependency seems to occur with nuget's own packages: Nuget.Packaging/Nuget.Packaging.Core

More details below in the repro section.

**NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):**
nuget.exe 

**NuGet version (x.x.x.xxx):**
nuget v4.7.0.5148

**OS version (i.e. win10 v1607 (14393.321)):**
Win10 v2004 (19041.264) ... but this was also replicated on our CI agents, which would be running a different version of windows.

## Detailed repro steps so we can see the same problem

For some examples:

If we run:

    PS > & nuget.exe install Microsoft.Bot.Builder.AI.Luis -Version 4.9.1 -OutputDirectory "c:\temp\nuget" -Framework netstandard2.0

We get the following error

```
Attempting to gather dependency information for package 'Microsoft.Bot.Builder.AI.Luis.4.9.1' with respect to project 'c:\temp\nuget', targeting '.NETStandard,Version=v2.0'
Gathering dependency information took 2.82 sec
Attempting to resolve dependencies for package 'Microsoft.Bot.Builder.AI.Luis.4.9.1' with DependencyBehavior 'Lowest'
Circular dependency detected 'Microsoft.Bot.Builder.AI.Luis 4.9.1 => Microsoft.Bot.Builder.Dialogs.Declarative 4.9.1 => NuGet.Client 4.2.0 => NuGet.Packaging 4.7.0 => NuGet.Packaging.Core 5.0.0 => NuGet.Packaging 4.7.0'.
```

So it seems to indicate that there's an issue with Nuget.Packaging 4.7.0, however if I install that directly, it works just fine:

    PS > & nuget.exe install Nuget.Packaging -Version 4.7.0 -OutputDirectory "c:\temp\nuget" -Framework netstandard2.0

Same with Nuget.Client ... it installs with no issues:

    PS > & nuget.exe install Nuget.Client -Version 4.2.0 -OutputDirectory "c:\temp\nuget" -Framework netstandard2.0

Here's where it gets a bit stranger ... if I install NuGet.Packaging.Core 5.0.0, it has a reference to Nuget.Packaging, but v5.0.0 (as opposed to the v4.7.0 that it shows in the circular dependency error). And if we install Nuget.Packaging 4.7.0, it instead installs Nuget.Packaging.Core 4.7.0!

So at this point, we're not sure if there's an issue in the way the actual project we're trying to deploy reference for is configured (Microsoft.Bot.Builder.AI.Luis), or if there's some bug in either the nuget packages or nuget itself :| any help would be greatly appreciated

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

[log.txt](https://github.com/NuGet/Home/files/4650755/log.txt)

**Comment by nkolev92** [comment]
This is a consequence of the NuGet tooling consolidating the libraries.
The NuGet.Packaging.Core assembly relevant code got merged into NuGet.Packaging in 5.x, that's why the dependency was reversed in order to provide Type Forwarders. https://github.com/NuGet/NuGet.Client/pull/2712
 
The NuGet.Client dependency is also gone. 
See https://github.com/NuGet/NuGet.Client/pull/1277. 

NuGet has 2 version solvers, the packages.config one, used by packages.config obviously and the install command & the PackageReference one. 

They are quite different. 

Given that this package is a library, if I install this question in a real netstandard2.0 project, i don't get any errors. 

netstandard2.0 projects can only be PackageReference so this shouldn't be too big of a concern. 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bot.Builder.Ai.LUIS" Version="4.9.1" />
  </ItemGroup>

</Project>
```

**Comment by joelmartinez** [comment]
@nkolev92 interesting, thanks for the insight ... This error is coming up in our automated pipeline tooling, which is why we depend on the nuget executable to pull down the package ... we're not adding it to a project and restoring it as a package reference, so this workaround doesn't really support our use case.

Do you know if the "install command solver" is still supported and receiving updates/maintenance for issues such as this one?

**Comment by nkolev92** [comment]
We have not made too many changes on the packages.config resolution side. 
It's a sensitive area, so we'd need to better understand the number of customers affected before investigating.

**Comment by joelmartinez** [comment]
@nkolev92 sure ... to give a bit more context as to what's happening here. My team builds the tools that publishes .NET reference docs for Microsoft. A brief and oversimplified overview of our process (in the context of this error) is as follows:

1. An engineering team publishes their library via nuget
1. They onboard to publish their documentation through the docs site, which configures a series of CI build pipelines for their product.
1. When a new release occurs, our pipeline first uses [a tool called Nue](https://github.com/docascode/nue), which in turn uses Nuget.exe to fetch all published binary artifacts (and dependencies) (that happens [here](https://github.com/docascode/nue/blob/e030086e01614f3c5dec1c53312f5aabef41bf39/Nue/Nue.StandardResolver/Resolver.cs#L24))
1. Once we have all assemblies local (to the build agent), we then use [a tool called mdoc](https://github.com/mono/api-doc-tools) to do API discovery over the final/published assemblies.
1. that metadata is then turned into something that will eventually be rendered and published on the website at https://docs.microsoft.com/dotnet/api/

So the issue we're encountering is there on step 3 ... we're highly dependent on nuget in this case to bring together a project's dependency tree for different releases; as you mention, it's not a trivial pursuit, so `nuget install` is quite critical for our pipeline.

On the flip side, could you recommend any way that the bot builder engineering could change their package dependency tree to avoid triggering this issue in `nuget install`? 

Please feel free to reach out and ask any other clarifying questions ... thanks :)

**Comment by nkolev92** [comment]
> On the flip side, could you recommend any way that the bot builder engineering could change their package dependency tree to avoid triggering this issue in nuget install?

Try upgrading the NuGet dependency to NuGet.Packaging 5.+ instead (so remove NuGet.Client, and use NuGet.Packaging instead, that's where the types moved).

This would mean the resolver won't even have to think about NuGet.Packaging.Core.

**Comment by cleemullins** [comment]
@nkolev92 I don't quite understand your comment. 

The [.csproj file in question is here](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.LUIS/Microsoft.Bot.Builder.AI.Luis.csproj). Here are the package references that project pulls in:
The project is a netstandard2.0 defined project
```
<TargetFramework>netstandard2.0</TargetFramework>
```
and pulls in the following references:
```
 <ItemGroup>
    <PackageReference Include="AsyncUsageAnalyzers" Version="1.0.0-alpha003" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime" Version="2.1.0" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Declarative" [...] />
    <PackageReference Include="Microsoft.Bot.Configuration" [...] />
  </ItemGroup>
```
Given this list, what should we remove? Is this a transitive dependency, or is this somehow brought in through our build system?

**Comment by joelmartinez** [comment]
@cleemullins looks like it was in Microsoft.Bot.Builder.Dialogs.Declarative, and it also looks like perhaps this issue has already been fixed in this commit?
https://github.com/microsoft/botbuilder-dotnet/commit/30162d8af079e04cbb5506cd03c54f384c76b372

**Comment by cleemullins** [comment]
@joelmartinez  Thanks. We'll pull that change into our next patch release.

**Comment by rrelyea** [comment]
seems solved. thanks all. closing.
