### ISSUE TITLE
Populate Solution Explorer package/project transitive dependencies from assets file

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9580]
[Copied from https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1107557]
For .NET Project System projects (eg. SDK style projects) where the Dependencies node exists, transitive dependencies of package and project references will no longer be populated using data from design time builds. Instead, this data will be lazily acquired from the assets file directly.

This code was originally going to exist in the Project System repo, but it requires logic from NuGet which is not consumable within VS due to problems with binding redirects.

**Comment by drewnoakes** [comment]
@donnie-msft I don't know what a shepherd does exactly (at least when no sheep are involved), but thank you for doing it 😆
