### ISSUE TITLE
dotnet push and handling multiple files

### ISSUE THREAD

**Issue by derekgreer** [NuGet/Home#9585]
Okay, this may be a combination of issues, but here's the issue(s) I'm seeing.

I'm working with pushing nuget packages to Azure DevOps using dotnet version 3.1.201.  I have a package.json for building locally and use Cygwin's bash as my shell.  My project produces 3 nuget packages along with the 3 associated symbol packages.

Here is the command I'm running:

```
"publish": "cross-env-shell ${npm_package_dotnetPath} nuget push --source ${npm_package_defaultSource} --api-key az --skip-duplicate dist/**/*.nupkg",
```

Upon attempting to push for a brand new version, it works because I'm including the skip-duplicates, but it complains about the symbol packages already being present:

```
Pushing my-company.7.1.0-test-4.nupkg to 'https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/
  Accepted https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/ 2041ms
Your package was pushed.
Pushing  my-company.7.1.0-test-4.symbols.nupkg to 'https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/
  Conflict https://pkgs.dev.azure.com/ my-company/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/ 330ms
Package 'C:\projects\mycompany\dist\mycompany.7.1.0-test-4.symbols.nupkg' already exists at feed 'https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/'.
...
```

As you can see, pushing the symbols fails, reporting that it already exists.  It seems that the push tool is automatically looking for the presence of the symbols package matching the associate package.  That's fine I guess, but I'd like to not see these error messages.  To test, I've tried modifying my command to exclude symbol files:

```
"publish": "cross-env-shell ${npm_package_dotnetPath} nuget push --source ${npm_package_defaultSource} --api-key az --skip-duplicate dist/**/*[!.symbol].nupkg",
```

This craps out though.  It seems whatever globbing code is being used by dotnet doesn't understand [!.symbol].  This should work though, as the following alternate globbing library works fine:

```
 "list": "cross-env-shell globstar ls dist/**/*[!.symbol].nupkg",
```

globstar is an npm library which expands the glob of the command passed in.  If I try to use it with the donet command, however, it highlights that dotnet.exe doesn't allow you to pass in multiple packages directly.

```
$ dotnet nuget push --source https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/mycompany-testfeed/nuget/v3/index.json --api-key az --skip-duplicate dist/mycompany.7.1.0-test-4.nupkg dist/mycompany.Bus.7.1.0-test-4.nupkg
Pushing mycompany.7.1.0-test-4.nupkg to 'https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/
  Conflict https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/ 1392ms
Package 'C:\projects\mycompany\dist\mycompany.7.1.0-test-4.nupkg' already exists at feed 'https://pkgs.dev.azure.com/mycompany/64fb1658-cc53-4091-9c06-2cf9907eb5ed/_packaging/b017efa1-71d0-44cd-a2d7-b0d2ac6c0649/nuget/v2/'.
```

This fails because the first package already exists, but I would expect it to attempt the second package which it doesn't do.  It seems the only way to include multiple files is with a glob, but the glob doesn't seem to be a full implementation.

**Comment by rrelyea** [comment]
running `dotnet nuget push -h`:
`dotnet nuget push --no-symbols`   -- If a symbols package exists, it will not be pushed to a symbols server.

does that help you?

**Comment by derekgreer** [comment]
That doesn't help as my intent _is_ to push the symbols.  I just don't want to push the symbols and see error messages that the symbols package is already there.  

Starting from an empty state of an Azure DevOps Artifacts feed setup as a NuGet source (i.e. no previously published packages), pushing a MyLib.1.0.0.nupkg and a MyLib.1.0.0.symbols.nupkg using the following command will result in it pushing both packages, but displaying an error message that the MyLib.1.0.0.symbols.nupkg is already there.

```
dotnet nuget push --source https://pkgs.dev.azure.com/yada-yada/index.json --api-key az --skip-duplicate **/*.nupkg
```

**Comment by derekgreer** [comment]
It appears I had my glob pattern incorrect.  To ignore including the symbols files, I believe I should have been using 'dist/**/*!(.symbols).nupkg', but this is apparently extended behavior which may not be supported.  That was just something I was trying though.  What I should be able to do is to push all *.nupkg files to an Azure DevOps Artifacts feed (libs and symbols) and have all the files pushed without errors. 

It appears this is what is happening:

A glob evaluates to two files: A.1.0.0.nupkg and A.1.0.0.symbols.nupkg.
The dotnet tool starts processing the A.1.0.0.nupkg file, pushes it, and looks for a matching symbols file (looks for it independent of the fact that it was passed in as one of the files to push).  It finds it and pushes it.  
The next file it comes to in the list of files is the same symbols file and it tries to push it again.  It sees it is already there and produces an error.

**Comment by RehanSaeed** [comment]
@derekgreer I've been trying and failing to get `nuget push "dist/*!(preview)*.nupkg" ...` working. How did you manage it?

**Comment by derekgreer** [comment]
@RehanSaeed I wasn't saying that works, I was just saying that would have been the correct glob pattern if ```dotnet.exe``` fully handled extended glob behavior (which I don't think it does).

**Comment by donnie-msft** [comment]
@derekgreer Thanks for the details... and you're spot-on with these issues! Globbing and skip-duplicate both have other Issues with specific details for each problem, so I'm closing this one in favor of those. Please follow these and contribute any other details you may find:

Globbing on `push` is covered in https://github.com/NuGet/Home/issues/9390
`Skip-Duplicate` applying to the automatic snupkg push is covered in https://github.com/NuGet/Home/issues/9647
