### ISSUE TITLE
Package Restore Failed (UWP) on several packages that worked fine in Win8.1

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#959]
I just tried four packages that all give "Package Restore Failed" on UWP:
   nspec
   Excel-DNA
   Antrl34
   StoryQ

They are all able to install in Win8.1 apps on VS2015 however. I think they should therefore be able to restore on UWP as well.

I'd like to know the root cause of the UWP package restore failed, so I can detect whether other more common packages will also suffer from it.

Note: nspec installs fine on Win8.1 but carries a .cs content file, even if we fix up the root cause of the "package restore failed" then nspec still won't work in UWP. Moreover the .cs content file depends on types that aren't in Win8.1

Note: Excel-DNA reports "can't find XmlSerializationWriter" when built on Win81.

Note: StoryQ gives build warning "lacks NeutralResourcesLanguageAttribute" when built on Win81.

**Comment by yishaigalatzer** [comment]
Please don't open bugs for these. We communicated the issue with each package back
