### ISSUE TITLE
Leak: PartCreationPolicy(CreationPolicy.NonShared) NuGet.SolutionRestoreManager.RestoreOperationLogger

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9595]
I loaded/unloaded a solution 777 times and  see almost 777 instances of “NuGet.SolutionRestoreManager.RestoreOperationLogger”

See: 
[1008657](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008657)

**Comment by erdembayar** [comment]
Here is screenshot from diagnostic tool before fix after 5 times open/close same project: 
![image](https://user-images.githubusercontent.com/8766776/83045866-0ce28180-9ffb-11ea-942c-a6163c46dc5c.png)

After 1 more open/close it increased to 6:
![image](https://user-images.githubusercontent.com/8766776/83045902-1835ad00-9ffb-11ea-9542-b26e872554f3.png)

But after fix more many times open/close it remains as "1".
![image](https://user-images.githubusercontent.com/8766776/83045964-2b487d00-9ffb-11ea-904d-6542b44552ee.png)

**Comment by erdembayar** [comment]
Please review my change https://github.com/NuGet/NuGet.Client/pull/3418  
@srdjanjovcic  @zivkan @nkolev92
