### ISSUE TITLE
dotnet nuget add source doesnt' exist...

### ISSUE THREAD

**Issue by tdykstra** [NuGet/Home#9597]
From @Tyler-IN , issue moved from https://github.com/dotnet/docs/issues/18476

> `dotnet add nuget source "https://repo.url/here/index.json" --name wtf --username wtf --password wtf --store-password-in-clear-text --configfile nuget.config`

```
Required command was not provided.
Usage: dotnet add [options] <PROJECT> [command]

Arguments:
  <PROJECT>   The project file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help   Show command line help.

Commands:
  package <PACKAGE_NAME>     Add a NuGet package reference to the project.
  reference <PROJECT_PATH>   Add a project-to-project reference to the project.
```

Have .NET Core SDKs for 2.0 up to 3.1.2 installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a08a1fa5-6267-3122-a377-5ba5b8503a07
* Version Independent ID: 1d2f0343-bda9-7e7a-34a9-f097635ff155
* Content: [dotnet nuget add source command - .NET Core CLI](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source#feedback)
* Content Source: [docs/core/tools/dotnet-nuget-add-source.md](https://github.com/dotnet/docs/blob/master/docs/core/tools/dotnet-nuget-add-source.md)
* Product: **dotnet-core**
* Technology: **dotnet-cli**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by rrelyea** [comment]
Shipped in [nuget 5.5](https://docs.microsoft.com/nuget/release-notes/nuget-5.5) which corresponds to dotnet.exe 3.1.200

@tyler-IN Please run ‘dotnet --version’ in the same directory you were running this command.

Sometimes global.json file is used to lock back to an older dotnet sdk, which will impact which commands are available.

**Comment by heng-liu** [comment]
Hi @Tyler-IN, could you try the following steps?
1.check the version by running  ‘dotnet --version’, to see if it's 3.1.200 or later.
2. change the sequence, from "dotnet add nuget " to "dotnet **nuget add** ".
I tried the following and it was successfully added.
`dotnet nuget add source "https://repo.url/here/index.json" --name whatever --username whatever --password whatever --store-password-in-clear-text --configfile nuget.config`

**Comment by zkat** [comment]
Closing as resolved, per https://github.com/NuGet/Home/issues/9597#issuecomment-649088342
