### ISSUE TITLE
Question: Controlling how a package's assets get consumed 

### ISSUE THREAD

**Issue by hugener** [NuGet/Home#9599]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version: 5.5.1.6542

dotnet.exe --version: 3.1.202

VS version: 16.5.5

OS version: win10 v1909

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

I'm trying to author a package to contains somethin in both tools and libs. According to this: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
If I mark it as a developmentDependency, it prevents the package from being included as a dependency in other packages, which is what I want.
However, it also excludes compile-time assets from compilation, which I do not want.
Currently, when I consume the package I have to add compile; to the IncludeAssets of the PackageReference and then everything works, but this is cumbersome.
Is there a way to author the package so that I can control how the PackageReference gets created? E.g. so that it will add "compile" automatically.

To give a little more context, the tools are doing some code generation and for it to work the libs needs to be referenced. So I'm looking for something that's both a developmentDependency (Does not allow adding my package as a dependency), but still allows my package to have libs referenced.

**Comment by rrelyea** [comment]
So, during build, you need those DLLs sent as references to the compiler, but at runtime there will be no dll dependency?
Can you give us more details on this scenario?

**Comment by hugener** [comment]
This gave me something to think about and I might have been going about it wrong.

Currently, I have a package that has the following folders:
build => msbuild target tie into build process
tools => msbuild task that does some code generation
lib => dll that is required for the generated code to work

developmentDependency => true

I was thinking I didn't want packages to contain my package as a dependency hence the developmentDependency => true, but I guess it's contradicting, since my lib would need exactly that. My thinking was that only projects that explicitly reference the package gets the code generation.

So I wonder about the following alternatives:
1. instead of lib I include the sources and then would have to be compiled into the project consuming my package. Being marked developmentDependency can I add sources for compilation?
2. instead of lib directly in the package could I use a dependency to a lib package? what would happen if a tools package (developmentDependency => true) that has a dependency to a lib package when added to a project?
3. I also wonder about the opposite. A lib package that has a dependency to a tools package?
4. Will removing developmentDependency mean that projects referencing projects that reference the tools also will get the tools running for them?

**Comment by nkolev92** [comment]
Closing as this is a conflicting request. Dev dependency can't be part of compilation.
