### ISSUE TITLE
`dotnet list` command supports `--verbosity` option

### ISSUE THREAD

**Issue by joelverhagen** [NuGet/Home#9600]
## Details about Problem

NuGet product used: dotnet.exe
dotnet.exe --version: 3.1.202
OS version: Windows 10, version 1909
Worked before? no

## Detailed repro steps so we can see the same problem

1. Create a new project, e.g. `dotnet new console`
1. Add a package, e.g. `dotnet add package NuGet.Packaging`
1. List deprecated packages, e.g. `dotnet list package --deprecated`

No HTTP `GET` and `OK` log lines are visible, unlike `dotnet restore --verbosity normal`, `dotnet nuget push`, and `dotnet nuget delete`. Especially when listing many packages or using `--include-transitive` it can lead to the command hanging for a long time without any visible output.

It would be helpful to have a verbosity switch like `dotnet restore` such as `--verbosity normal` to show the HTTP spew. This would allow understanding why the operation is slow and if one particular source is behaving badly.

You can do this investigation with restore via `dotnet restore --verbosity normal`.

I think it's right that the log lines are not shown by default (there are a lot sometimes) but there should be a way to see them without launching Fiddler or some other MITM proxy.

I think it's hardcoded to not allow this here:
https://github.com/NuGet/NuGet.Client/blob/eb9ad919724e5ef435d6321b775868c9f2c0f9a2/src/NuGet.Core/NuGet.CommandLine.XPlat/Commands/PackageReferenceCommands/ListPackage/ListPackageCommandRunner.cs#L649

### Verbose Logs

> Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

Well, that's the problem... 😂

```
PS C:\Users\joelv\Desktop\testproj> dotnet list package --deprecated --verbosity diag
Unrecognized command or argument '--verbosity'
Unrecognized command or argument 'diag'
Usage: dotnet list <PROJECT | SOLUTION> package [options]

Arguments:
  <PROJECT | SOLUTION>   The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
  -h, --help                                Show command line help.
  --outdated                                Lists packages that have newer versions.
  --deprecated                              Lists packages that have been deprecated.
  --framework <FRAMEWORK | FRAMEWORK\RID>   Chooses a framework to show its packages. Use the option multiple times for multiple frameworks.
  --include-transitive                      Lists transitive and top-level packages.
  --include-prerelease                      Consider packages with prerelease versions when searching for newer packages. Requires the '--outdated' or '--deprecated' option.
  --highest-patch                           Consider only the packages with a matching major and minor version numbers when searching for newer packages. Requires the '--outdated' or '--deprecated' option.
  --highest-minor                           Consider only the packages with a matching major version number when searching for newer packages. Requires the '--outdated' or '--deprecated' option.
  --config <CONFIG_FILE>                    The path to the NuGet config file to use. Requires the '--outdated' or '--deprecated' option.
  --source <SOURCE>                         The NuGet sources to use when searching for newer packages. Requires the '--outdated' or '--deprecated' option.
  --interactive                             Allows the command to stop and wait for user input or action (for example to complete authentication).
```

### Sample Project

[testproj.zip](https://github.com/NuGet/Home/files/4672506/testproj.zip)

**Comment by nkolev92** [comment]
See: https://github.com/NuGet/NuGet.Client/pull/3411#issuecomment-634299777

Personally I think we should do a `--verbosity` switch, change the default to minimal to match the other dotnet commands.
