### ISSUE TITLE
How to check framework compatibility?

### ISSUE THREAD

**Issue by silkfire** [NuGet/Home#9604]
I'm using the `NuGet.Protocol` APIs to fetch metadata about packages. I wonder if there is a way to check whether a package, or more specifically, a framework is compatible with a specific target framework.

If my designated TFM is `netcoreapp3.1` and I compare it to `netstandard2.1`, I want this to return `true`.

I'm fiddling with the `NuGetFramework` type but it doesn't seem to have such a method.

```csharp
var isCompatible = NuGetFramework.Parse("netcoreapp3.1") == NuGetFramework.Parse("netstandard2.1");
```

**Comment by nkolev92** [comment]
Use the default compatibility provider for that: https://github.com/NuGet/NuGet.Client/blob/6fd451a5099c6f3d0b17035915d6171a744c4c6b/src/NuGet.Core/NuGet.Frameworks/DefaultCompatibilityProvider.cs

That has an IsCompatible method: https://github.com/NuGet/NuGet.Client/blob/6fd451a5099c6f3d0b17035915d6171a744c4c6b/src/NuGet.Core/NuGet.Frameworks/def/IFrameworkCompatibilityProvider.cs#L20

**Comment by silkfire** [comment]
Thank you so much, this was exactly what I was looking for.
