### ISSUE TITLE
macOS Nuget restore with space in folder name Invalid Path error

### ISSUE THREAD

**Issue by tpitman** [NuGet/Home#9606]
## Details about Problem
Nuget can't restore .NET core projects when a related project has a space in the name on macOS

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI, Package Manager Console

NuGet version (x.x.x.xxx):
5.6.0.6489

VS version (if appropriate):
2019 Mac 8.6 build 4520

OS version (i.e. win10 v1607 (14393.321)):
macOS Catalina 10.15.4

Worked before? If so, with which NuGet version:
Not sure

## Detailed repro steps so we can see the same problem

1. Have a solution with .net core and .net framework mixed projects where the .net projects have spaces somewhere in the folder name hierarchy

2. Open the solution

3. VS automatically tries to restore packages

4. Note the error that there is an invalid path in the project folder

Here is the error:
/Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/NuGet.targets(557,5): error : Invalid path [/Users/.../Software/Shared Libraries/Platform/NonWindowsCommon/NonWindowsCommon.csproj]

Note the space in "Shared Libraries". This has been a long standing folder structure for this solution / project and didn't have this problem until we introduced a .NET core project into the solution.
...

### Verbose Logs
none

### Sample Project
none

**Comment by heng-liu** [comment]
Hi @tpitman , thanks for reporting this issue!
Could you provide more details on how to repro it?
I tried to repro with a path including a space "try space", but the restore is successful:
```
Getting restore information for project /Users/heng/repos/Project/try space/testProject/testProject.csproj
Running non-parallel restore.
Reading project file /Users/heng/repos/Project/try space/testProject/testProject.csproj.
The restore inputs for 'testProject' have changed. Continuing restore.
Restoring packages for /Users/heng/repos/Project/try space/testProject/testProject.csproj...
Restoring packages for .NETCoreApp,Version=v5.0...
Resolving conflicts for .NETCoreApp,Version=v5.0...
Restoring packages for .NETFramework,Version=v4.7.2...
Resolving conflicts for .NETFramework,Version=v4.7.2...
Checking compatibility of packages on .NETCoreApp,Version=v5.0.
Checking compatibility for testProject 1.0.0 with .NETCoreApp,Version=v5.0.
All packages and projects are compatible with .NETCoreApp,Version=v5.0.
Checking compatibility of packages on .NETFramework,Version=v4.7.2.
Checking compatibility for testProject 1.0.0 with .NETFramework,Version=v4.7.2.
All packages and projects are compatible with .NETFramework,Version=v4.7.2.
Committing restore...
Writing assets file to disk. Path: /Users/heng/repos/Project/try space/testProject/obj/project.assets.json
Writing cache file to disk. Path: /Users/heng/repos/Project/try space/testProject/obj/project.nuget.cache
Persisting dg to /Users/heng/repos/Project/try space/testProject/obj/testProject.csproj.nuget.dgspec.json
Restored /Users/heng/repos/Project/try space/testProject/testProject.csproj (in 50 ms).

NuGet Config files used:
    /Users/heng/repos/Project/NuGet.Config
    /Users/heng/.config/NuGet/NuGet.Config

Feeds used:
    https://api.nuget.org/v3/index.json

Packages successfully restored.
```

**Comment by tpitman** [comment]
Maybe it isn't the space in the path then. All I know is that for my
project this is happening. It is a really really big project, so I can't
send you the whole thing. What kinds of stuff could I do to help diagnose?

For example, here is the error output:

/Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/NuGet.targets(557,5):
error : Invalid path [/Users/tpitman/Projects/Powerteq/SoftwareUA/Shared
Libraries/Platform/NonWindowsCommon/NonWindowsCommon.csproj]

/Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/NuGet.targets(557,5):
error : Invalid path [/Users/tpitman/Projects/Powerteq/SoftwareUA/Shared
Libraries/PowerteqDeviceUpdate/PowerteqDeviceUpdate.csproj]

/Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/NuGet.targets(557,5):
error : Invalid path [/Users/tpitman/Projects/Powerteq/SoftwareUA/Shared
Libraries/Common/Common.csproj]

MSBuild exited with code 1

Those paths ARE there. That is why I suspected it was the space in the name.

**Comment by heng-liu** [comment]
May I know if you could run [dotnet restore](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore) successfully on this project?

**Comment by tpitman** [comment]
dotnet restore [solutionfile] works fine.

**Comment by heng-liu** [comment]
dotnet also use NuGet to restore. I'm not sure why vs for mac doesn't work correctly.
Could you raise an issue on developercommunity/Visual Studio for Mac? They may have a better understanding.
https://developercommunity.visualstudio.com/spaces/41/index.html

**Comment by tpitman** [comment]
ok

**Comment by nkolev92** [comment]
Closing per @heng-liu's latest comment.
