### ISSUE TITLE
Fix typos dependecy => dependency

### ISSUE THREAD

**Issue by pirluq** [NuGet/Home#9607]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): NuGet.exe

NuGet version : 5.6.0

dotnet.exe --version (if appropriate): 3.1.300

VS version (if appropriate): 2019 (16.6.0)

OS version (i.e. win10 v1607 (14393.321)): win10 v1607 (14393.321)

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. reading the code ^^
...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zivkan** [comment]
@pirluq thanks for creating the PR, and apologies for taking so long to get it merged.
