### ISSUE TITLE
Design proper session Permanence/Idempotency

### ISSUE THREAD

**Issue by mirkomuggli** [NuGet/Home#9609]
## Overview
There's currently a lot of uncertainty around multiple clients attaching to the same session.
* Is it possible?
* If so, what if someone does a restore while someone else is adding/removing packages?
* What if multiple restores are started?

We need to investigate what's supported and how other teams have handled these issues - I'll work with Rob to flesh out this issue.

PMUI for Codespaces

**Comment by rrelyea** [comment]
we only have one client per codespace. if we added liveshare, we would have to consider. closing for now.
