### ISSUE TITLE
Empty changes dialog when package installation fails

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#961]
If I try to install rx.windowstoreapps to a PCL targeting dnxcore50 and uap, package installation fails (as expected). However, NuGet brings up a window listing the changes to apply, but there aren't any, so the window is empty. In this case, NuGet should probably not bring up the window.

**Comment by rchande** [comment]
Alternatively, if I try to install Microsoft.AspNet.Razor into a PCL targeting Win8.1 + .Net 4.5, the preview window contains text, but the installation fails and leaves the following in the error list.

Could not install package 'Microsoft.AspNet.Razor 2.0.20505'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by emgarten** [comment]
Microsoft.AspNet.Razor 2.0.20505 contains only lib\net40 so the install failure is expected, however the preview window should display this information.

The bug tracking the preview window issues for UWP is: https://github.com/NuGet/Home/issues/843
