### ISSUE TITLE
Show version range on package reference nodes in dependencies tree

### ISSUE THREAD

**Issue by drewnoakes** [NuGet/Home#9614]
From https://github.com/NuGet/NuGet.Client/pull/3392/files/a462d871eebed985c3a3fe7fd145d75f7d30267e#r431223599

It may be useful to show the requested version range on the caption of dependencies tree items that represent package references.

The NuGet side of this would apply only to transitive package references. The .NET Project System would control the equivalent information for top-level package references.

**Comment by nkolev92** [comment]
> It may be useful to show the requested version range on the caption of dependencies tree items that represent package references.

I don't think the assets file keeps track of that. I think it only keeps track of the resolved ones. 
Someone should investigate to confirm this though.

**Comment by drewnoakes** [comment]
The version ranges appear to only exist for top-level dependencies in the assets file:

```
  "projectFileDependencyGroups": {
    ".NETFramework,Version=v4.7.2": [
      "MetadataExtractor >= 2.3.1"              👈 
    ]
  },
  "project": {
    "frameworks": {
      "net472": {
        "dependencies": {
          "MetadataExtractor": {
            "target": "Package",
            "version": "[2.3.1, )"              👈 
          }
        }
      }
    }
  }
```

Given this repo doesn't populate those nodes, I think this issue can be closed.
