### ISSUE TITLE
Show more information for a dependency's browse object in the dependencies tree

### ISSUE THREAD

**Issue by drewnoakes** [NuGet/Home#9616]
From https://github.com/NuGet/NuGet.Client/pull/3392/files/a462d871eebed985c3a3fe7fd145d75f7d30267e#r430953620

We could show more information in the browse object of transitive dependencies. For example, Include/Exclude values.

Someone with a deeper understanding of the domain should review this and see what's missing.

The NuGet side of this would apply only to transitive references. The .NET Project System would control the equivalent information for top-level references.

**Comment by nkolev92** [comment]
Are we talking ExcludeAssets, IncludeAssets metadata?

**Comment by nkolev92** [comment]
🔔 @drewnoakes 

Transitive PackageReferences do not have any user controlled metadata. If this is about include/exclude assets then I think it's a no-op. -

**Comment by nkolev92** [comment]
Closing this per the above. 

We don't have any relevant metadata for transitive references today. 
If/when we add them, we can reconsider.
