### ISSUE TITLE
Replace BrowseObjectBase with LocalizableProperties once updated shell package available

### ISSUE THREAD

**Issue by drewnoakes** [NuGet/Home#9619]
From https://github.com/NuGet/NuGet.Client/pull/3392#discussion_r431179016

Once the new package is available, this class can be removed.

**Comment by drewnoakes** [comment]
This work should also be done on Roslyn and the .NET Project System.

**Comment by nkolev92** [comment]
@drewnoakes Has the project-system/roslyn side work been completed?

**Comment by dominoFire** [comment]
It seems this resource string is not displayed anywhere https://github.com/NuGet/NuGet.Client/blob/abaa72f3390fba4bb65fb3c700f22104682bfae9/src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Items/PackageAssemblyItem.cs#L57

If this can be replaced with `LocalizableProperties`, I think this is a good moment to replace this class.

This was discovered during work on https://github.com/NuGet/Client.Engineering/issues/451

**Comment by dominoFire** [comment]
GetComponentName() is now a virtual method in this package

https://www.nuget.org/packages/Microsoft.VisualStudio.Shell.15.0/17.3.32804.24

https://www.fuget.org/packages/Microsoft.VisualStudio.Shell.15.0/17.3.32804.24/lib/net6.0-windows10.0.18362/Microsoft.VisualStudio.Shell.15.0.dll/Microsoft.VisualStudio.Shell/LocalizableProperties#M%3AMicrosoft.VisualStudio.Shell.LocalizableProperties.GetComponentName

**Comment by dominoFire** [comment]
Update: The string resource PackageAssemblyBrowseObjectClassName is used and shown in UI:

![image](https://user-images.githubusercontent.com/1192347/190841725-cabdff89-6df2-46c7-bc87-151a1bd866bb.png)

**Comment by drewnoakes** [comment]
Thanks for the reminder. I fixed up the Project System side of this too in: https://github.com/dotnet/project-system/pull/8510
