### ISSUE TITLE
"Package restore failed. Rolling back package changes..." appears in the error list

### ISSUE THREAD

**Issue by rchande** [NuGet/Home#962]
This error appears in the error list and it's frustrating that I can't get rid of it until after I build again.

**Comment by rchande** [comment]
Could we use an infobar instead?

**Comment by emgarten** [comment]
We'll take a look at how this could be improved. As for the infobar, I'm not sure that would be noticeable enough, and the user does need to know when the install failed.

**Comment by yishaigalatzer** [comment]
@rchande I just closed the bugs that asks for removing the error. I think it should not be removed. We are tracking elsewhere improving the error messages.

@RanjiniM can you please verify we show a more useful message here?

**Comment by RanjiniM** [comment]
Clearing out the milestone. We can't remove the error messages from error list yet until we find another way to surface those. In error cases the messages are explanatory.

**Comment by msthrax** [comment]
i have this problem too.
idont know how to fix this :((

**Comment by damonpkuml** [comment]
When I install signalR nugget package  for a UWP app, I have this problem too.How Can I fix this?

**Comment by harikmenon** [comment]
We need more details. Can you paste the contents in your output window?

**Comment by damonpkuml** [comment]
I have fixed it, Thanks ,I just not select the SignalR.Client package.

**Comment by Loves2Code** [comment]
I'm having same problem with installation of Nuget Packages:
    Microsoft.EntityFrameworkCore.SqlServer
[EntityFrameworkCore SQL Server Install errors.txt](https://github.com/NuGet/Home/files/638236/EntityFrameworkCore.SQL.Server.Install.errors.txt)

Trying to install either from the console or from the user interface in VS 2015. Error output is attached since it is quite extensive.

**Comment by jcjwall** [comment]
I am having the same issue with Microsoft.EntityFrameworkCore.SqlServer, with the following error log:
Restoring packages for C:\Users\JoeJo\Documents\Visual Studio 2017\Projects\Projects\OrganizeUsDataAccess\project.json...
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed. Rolling back package changes for 'OrganizeUsDataAccess'.
========== Finished ==========
Time Elapsed: 00:00:01.7899703

**Comment by dbrezack** [comment]
Having this issue in VS 2017 for Microsoft.Owin.Host.SystemWeb

**Comment by sameerfairgoogl** [comment]
Having this issue for EntityFramework VS2017, just stumbled over this thread through Google. Is there a workaround for this?
![exception](https://cloud.githubusercontent.com/assets/5323565/24587936/96fcc370-17d8-11e7-9faf-fc642b70dfc7.png)

**Comment by sameerfairgoogl** [comment]
ok, tried with Package Manager Console, and got 

"install-package : One or more packages are incompatible with .NETCoreApp,Version=v1.1."

well, atleast I have a ballpark

**Comment by sameerfairgoogl** [comment]
ok folks, for future reference, got Microsoft.EntityFrameworkCore installed instead with no issues

**Comment by ddynamight** [comment]
Hello guys, I got the issue when I tried adding "Microsoft.AspNet.Identity.EntityFramework" to a .NET Standard Class Library Project. But when I added it to a .NET Framework Class Library Project it worked successfully without a problem.

**Comment by m-henderson** [comment]
@sameerfairgoogl how did you install it ?

**Comment by nhtbtmz** [comment]
Hello guys,
If you have problem with an entityframework package just try to install latest stable version from Nuget. Prerelease versions may cause trouble.

**Comment by sameerfairgoogl** [comment]
@m-henderson installed the nuget package for it, most likely this one if I remember correctly https://www.nuget.org/packages/Microsoft.EntityFrameworkCore

**Comment by weitzhandler** [comment]
If you're using .NET Standard, try installing the [`Microsoft.NETCore.Portable.Compatibility`](https://www.nuget.org/packages/Microsoft.NETCore.Portable.Compatibility) package, and/or adding the `PackageTargetFallback` element to your _csproj_ file, example:

    <PropertyGroup>
      <TargetFramework>netstandard1.4</TargetFramework>
      <PackageTargetFallback>$(PackageTargetFallback);portable-win+net45+wp8+win81+wpa8</PackageTargetFallback>
    </PropertyGroup>

**Comment by dongle-the-gadget** [comment]
I have a problem when install Microsoft.Azure.NotificationHubs. How can I fix it

**Comment by tabareh** [comment]
So the summary is that we get this message when installing previous .net packages on .net Core projects, and this is a matter of incompatibility.
If your package has a corresponding one in .net Core, then you're lucky. Go for it!

**Comment by sameerfairgoogl** [comment]
Yes

**Comment by DamienDoumer** [comment]
I had this issue, but When I cleared My Nuget Packages Cache, it resolved this issue. On Visualstudio, Go to Tools -> Options -> Nuget -> and clear your cache.

**Comment by jefhai** [comment]
I had this same issue. I was also prevented from clearing the cache so I deleted the .nuget folder.

**Comment by ZainulPaleri** [comment]
please choose suitable version for targeted frame work then it will work
