### ISSUE TITLE
Convert Microsoft.VisualStudio.ProjectSystem.Managed from PackageDownload to PackageReference

### ISSUE THREAD

**Issue by drewnoakes** [NuGet/Home#9620]
From https://github.com/NuGet/NuGet.Client/pull/3392/files#r428498657

`Microsoft.VisualStudio.ProjectSystem` uses `PackageDownload` to reference `Microsoft.VisualStudio.ProjectSystem.Interop` directly with `EmbedInteropTypes` set to `true`.

https://github.com/NuGet/NuGet.Client/blob/34ceb7d3d5a70ba4b1ecf196e5902dcc9ffed05d/test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/NuGet.PackageManagement.VisualStudio.Test.csproj#L62-L65

https://github.com/NuGet/NuGet.Client/pull/3392/ copied this pattern for the .NET Project System packages, however this isn't necessary for `Microsoft.VisualStudio.ProjectSystem.Managed` and `Microsoft.VisualStudio.ProjectSystem.Managed.VS`.

Converting these to `PackageReference` triggers a package downgrade error on `Microsoft.CodeAnalysis.FxCopAnalyzers`.

Upgrading `Microsoft.CodeAnalysis.FxCopAnalyzers` that to `3.0.0` triggers 90 new errors, many of which look like they're worth a proper review.

**Comment by nkolev92** [comment]
https://github.com/NuGet/NuGet.Client/commit/20be995d651808feb5cd48f30cb97197e497377c did it.
