### ISSUE TITLE
NU1004 when restoring a solution that has mixed Legacy and netstandard2 projects from cmd line with LockedMode

### ISSUE THREAD

**Issue by efunkenbusch** [NuGet/Home#9623]
## Details about Problem

NuGet product used: nuget.client

NuGet version Several, but exists in prod 5.4, 5.5, 5.5.1 and 5.6 as well as 5.7 preview 1

VS version: 2019 16.7 Preview 1

OS version: Windows 10 19635.1

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Create a new dotnet core library (default is fine)
2. Add anew .net 4.7.2 library (with packages.config but also fails with PackageReference)
3. Add some legacy framework librarys to th e.net 4.7.2 library (i chose Google.Apis)
4. Add a project reference from .net core library to legacy framework library (no actual code reference needed)
5. install nuget.exe (i used chocolatey, installed prod 5.6.0)
6. open a command prompt, navigate to your solution foldeer
7. type "nuget.exe restore <your project>.sln -UseLockFile" (succeeds)
8. type "nuget.exe restore <your project>.sln -LockedMode (fails, with NU1004) (also fails if both flags are combined)

NOTE: Some observations
- Project builds fine in VS without error. 
- multi-targeting netstandard2 and net472 produces the same failed results.
- the generated packages.lock.json file looks reasonably correct to me.

### Verbose Logs

```
C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1>nuget restore ClassLibrary1.sln -LockedMode -verbosity detailed
NuGet Version: 5.4.0.6315
MSBuild auto-detection: using msbuild version '16.7.0.22806' from 'C:\PROGRA~2\MICROS~1\2019\Preview\MSBuild\Current\Bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
C:\PROGRA~2\MICROS~1\2019\Preview\MSBuild\Current\Bin\msbuild.exe "C:\Users\ErikFunkenbusch\AppData\Local\Temp\NuGetScratch\aegggkrs.jgg.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q /p:NuGetRestoreTargets="C:\Users\ErikFunkenbusch\AppData\Local\Temp\NuGetScratch\pirmklvn.dnv.nugetrestore.targets" /p:RestoreUseCustomAfterTargets="True" /p:RestoreTaskAssemblyFile="C:\ProgramData\chocolatey\lib\NuGet.CommandLine\tools\nuget.exe" /p:RestoreSolutionDirectory="C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\\" /p:SolutionDir="C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\\" /p:SolutionName="ClassLibrary1" /p:RestoreLockedMode="True"

All packages listed in packages.config are already installed.
Running restore with 16 concurrent jobs.
Reading project file C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj.
The restore inputs for 'ClassLibrary1' have changed. Continuing restore.
Persisting no-op dg to C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.dgspec.json
NU1004: The packages lock file is inconsistent with the project dependencies so restore can't be run in locked mode. Disable the RestoreLockedMode MSBuild property or pass an explicit --force-evaluate option to run restore to update the lock file.
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\obj\project.assets.json
Writing cache file to disk. Path: C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\obj\ClassLibrary1.csproj.nuget.cache
Writing packages lock file at disk. Path: C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\packages.lock.json
Restore failed in 83.46 ms for C:\Users\ErikFunkenbusch\source\repos\ClassLibrary1\ClassLibrary1\ClassLibrary1.csproj.

NuGet Config files used:
    C:\Users\ErikFunkenbusch\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    C:\Program Files (x86)\NuGet\Config\Xamarin.Offline.config

Feeds used:
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
    https://api.nuget.org/v3/index.json

```

### Sample Project

[ClassLibrary1.zip](https://github.com/NuGet/Home/files/4699515/ClassLibrary1.zip)

**Comment by efunkenbusch** [comment]
Note, the output is from 5.4.0 but it's the same in 5.6.0 and 5.7.0 preview 1

**Comment by nkolev92** [comment]
The repro was really helpful. 

The problem is that there is a ProjectReference from PR -> PC, and the lock file is checking compat. 

Investigating options right now.

**Comment by nkolev92** [comment]
Fix in review https://github.com/NuGet/NuGet.Client/pull/3820.
