### ISSUE TITLE
Suggestion: Add nuget.commandline packages to Winget repo

### ISSUE THREAD

**Issue by efunkenbusch** [NuGet/Home#9624]
Since Winget is new and all that gooey goodness, you should add the Nuget.client packages so they can be easily installed.

**Comment by nkolev92** [comment]
Hey @efunkenbusch,

Are you referring to adding nuget.exe to winget as an installable tool? 

Thanks.

**Comment by donnie-msft** [comment]
⏰ @efunkenbusch, could you please clarify this request?

**Comment by PiterGoCompany** [comment]
Hi, 
@nkolev92 it would be great if nuget.exe  could be downloaded by WinGet as an installable tool.
