### ISSUE TITLE
Check code relies on HResult value

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9628]
We have the following code relies on HResult. 
https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/Signing/Authoring/X509SignatureProvider.cs#L141

As per https://github.com/dotnet/runtime/issues/36786#issuecomment-632193883,  the HResult values of most of dotnet/runtime exceptions is not guaranteed by them.

We need to check if it's guaranteed, or else we may have to change the code.

**Comment by nkolev92** [comment]
Triage: 
@heng-liu Please add details for specific error codes/scenarios that would be affected by this.

**Comment by heng-liu** [comment]
There're two classes relying on HResut:
[CertificateProvider](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/SignCommand/CertificateProvider.cs) and [X509SignatureProvider](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/Signing/Authoring/X509SignatureProvider.cs)
Both of them use HResult to throw a more specific exception. If HResult changes in future, the impact will be, some different exception(from dotnet runtime) will be thrown. 

We have tests for the three exceptions rely on HResults in CertificateProvider.cs, we may detect the HResult change if any of those tests failed.
But we don't have test for the exception relies on HResults in X509SignatureProvider.cs.
Closed as won't fix. Pls let me know if you would like to reopen.
