### ISSUE TITLE
Thousands of NuGet.Versioning.NuGetVersion items are created

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9633]
I noticed this item is multiplying by thousands during memory leak investigation for another [item](https://github.com/NuGet/Home/issues/9595).
Looks like it's under our Nuget.Client domain.
![image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/dbb96fdb-3673-4e14-b9ec-41c32db0e882)
I think we need to investigate it. For now assigned to myself, most likely I'll work during this or next sprint.

**Comment by nkolev92** [comment]
Yeah, that's a known issue and a part of the overall NuGet consumes a lot of memory. We'll consider it during planning. 

For reference, we do have some primitive deduplication https://github.com/NuGet/NuGet.Client/blob/fc9dd52fcdf3c9a299a96de39b641b7c91779b5e/src/NuGet.Core/NuGet.Protocol/Utility/MetadataReferenceCache.cs

**Comment by nkolev92** [comment]
I removed the leak from the title. 
I don't believe it's a leak, rather we just don't dedup enough, the NuGetVersion in memory are being used.

**Comment by nkolev92** [comment]
Actually, this is a dup of https://github.com/NuGet/Home/issues/8352 :)
