### ISSUE TITLE
restore hangs if you define a source to network folder that doesnt exist

### ISSUE THREAD

**Issue by jmecosta** [NuGet/Home#9635]
Steps to reproduce:

1. wipe your local cache
2. define a Nuget.Config in root of solution with a source to a network share \\machine\nonexistenfolder
3. run dotnet restore, nuget restore, visual studio

expected: nuget should warn that the feed is not avaible
current: visual studio hanges, nuget hangets, donet hangs

annoying :(

**Comment by nkolev92** [comment]
@v-luzh Can you please try to repro this issue? 

Does NuGet recover at any point or does it hang forever.

**Comment by v-luzh** [comment]
Hi @nkolev92, **no hang** with dotnet restore, nuget restore, visual studio restore on both VS Main\30522.201 + NuGet Client release-5.8.0-preview.3\5.8.0.6854 and VS Main\30515.165 with implicit NuGet Client Dev\5.8.0.6842. NuGet gave errors (that the feed is not available) when selecting the unavailable source in Package source drop-down box.

**Comment by nkolev92** [comment]
Thanks @v-luzh 

@jmecosta UNfortunately we have not been able to reproduce this issue, and at this point we can't investigate this any further. 

Are you still facing this problem? 
Closing this issue for now, but we'd be happy to reconsider.
