### ISSUE TITLE
Unable to find project 'C:\Users\XXX\Documents\Visual Studio 2017\Projects\HI7.FHIR\1.6.0 for R4 (released 20200304)\fhir-net-api-1.6.0-r4\common\src\Hl7.FhirPath\Hl7.FhirPath.csproj'

### ISSUE THREAD

**Issue by ricktiger** [NuGet/Home#9637]
I downloaded fhir-net-api-1.6.0-r4.zip from Git and tried to build the solution in VS 2019 and I get lots of the same error...
**Unable to find project 'C:\Users\XXX\Documents\Visual Studio 2017\Projects\HI7.FHIR\1.6.0 for R4 (released 20200304)\fhir-net-api-1.6.0-r4\common\src\Hl7.FhirPath\Hl7.FhirPath.csproj'**

Can someone please advise?  Thank you!

**Comment by dominoFire** [comment]
@ricktiger It seems you need to ask for help in the Firely team product first.

https://github.com/FirelyTeam/fhir-net-api

If you have NuGet issues with their related NuGet packages, let us know.
