### ISSUE TITLE
Replace our converters with Microsoft.VisualStudio.PlatformUI.BooleanToCustomVisibilityConverter 

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9639]
My recent PR introduced a way to make the BooleanToVisibility converter have a `Hidden` state when the visibility is false (the default behavior is `Collapsed`).

After a PR review, it was suggested my naming of this property `HiddenWhenFalse` was confusing when considering the `Inverted` property. The suggestion was to name it `NonVisualState` [code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/BooleanToVisibilityConverter.cs#L21).

I named the converter in a way that seems clear, but is not concise: `NonVisualStateHiddenBooleanToVisibilityConverter` [code](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageItemControl.xaml#L89).

Further feedback recommended this be renamed.
https://github.com/NuGet/NuGet.Client/pull/3410#discussion_r434266139 : 
`BooleanToHiddenConverter is what I'd call this. Or something a bit more concise.
BooleanToHiddenInvertedCoverter is what i'd call it if you also inverted it.`

What suggestions do we have for this naming?

**Comment by nkolev92** [comment]
Triage: This seems like a simple change and easy win to decrease our issue count :)

**Comment by donnie-msft** [comment]
Let's refactor all our converters to utilize the VS PlatformUI converter instead:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.platformui.booleantocustomvisibilityconverter?view=visualstudiosdk-2019
