### ISSUE TITLE
Nuget compares {RID}s with case sensitive comparison

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#964]
It looks like nuget is doing a case sensitive comparison when doing a RID probe in the package.  Given that these are representing folders on a case insensitive file system it needs to be doing a case insensitive compare.  This would also make rid comparison consistent with tfm comparisons.

/cc @damyanp @pranavkm @yishaigalatzer

**Comment by davidfowl** [comment]
Use the right case.

**Comment by ericstj** [comment]
If you promote the use of case sensitive strings in the package those will break when you lay them down on windows.  You need to implement the least common denominator.  You're already case insenstive for TFMs please be consistent.

This isn't a blocking issue since it has a workaround, but something that should be addressed for consistency.  One customer has hit it, more certainly will.  The behavior when they hit: nuget drops the asset or chooses the wrong asset.  They may not discover this till runtime (as was the case here with a native asset).  Please don't push this burden on the developer when its such a simple code fix to make in nuget.

**Comment by yishaigalatzer** [comment]
They file system is sensitive on Linux, aren't we going xplat? We might want to warn and make sure all rid's are lower case

**Comment by yishaigalatzer** [comment]
Conslusion: RIDs are case sensitive.

We recommend that from now on you make all of them lower case, and we can consider enforcing it on pack and server uploads.
