### ISSUE TITLE
 error CS0234: The type or namespace name 'Practices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) 

### ISSUE THREAD

**Issue by DhanvannthVP** [NuGet/Home#9642]
i am new to nuget. i am downloading the packages from packages.config. 

using IBM.Data.DB2; could see  in .csfile.

Mentioned in packages.config to pull it from artifactory
  <package id="IBM.Data.DB2" version="10.0.5.5" targetFramework="net451" />

 error CS0234: The type or namespace name 'Practices' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) 
It s downloading but am getting same error CS0234. please help me what is the error..

Even  IBM.Data.DB2.dll in artifactory. how to find the target framework and mention in packages.config

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by DhanvannthVP** [comment]
fixed

**Comment by abrainard123** [comment]
How did you fix it. What were the steps
