### ISSUE TITLE
ContentFiles from Link'ed Files not in correct folder

### ISSUE THREAD

**Issue by pfeigl** [NuGet/Home#9643]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
msbuild / VS

NuGet version (x.x.x.xxx): 5.6.0.5

dotnet.exe --version (if appropriate): 3.1.300

VS version (if appropriate): 16.6.1

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: no

## Detailed repro steps so we can see the same problem

When adding contentFiles into a nuget package via the `<Content>` node inside a CSPROJ file, the correct subfolder is not taken into consideration and the file is put into the `contentFiles\{lang}\{arch}\` root folder.
This only happens for elements with a `<Link>`'ed reference. Local files are put into the respective folders correctly.

This is how my csproj looks like
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="SubFolder\LocalFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\LinkedFile.txt" Link="SubFolder\LinkedFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SubFolder\LocalFile.txt" />
  </ItemGroup>

</Project>

```

This is how it looks in VisualStudio
![image](https://user-images.githubusercontent.com/237891/83642729-81935e00-a5af-11ea-87b3-a0177d7c35d9.png)

And this is how it looks like in the final nuget package
![image](https://user-images.githubusercontent.com/237891/83642795-940d9780-a5af-11ea-91bc-92709d647dfe.png)

My understanding is, that this is a bug and that the folder structure created via the csrpoj file should be the same within `contentFiles`, no matter whether it's a linked or local file.

...

### Sample Project
[ContentFilesFromLinksMissingFolder.zip](https://github.com/NuGet/Home/files/4723641/ContentFilesFromLinksMissingFolder.zip)

**Comment by nkolev92** [comment]
Hey @pfeigl, 

Link metadata only affects how things are displayed in the solution explorer. 
To control the directory structure of the content files, you can use PackagePath. 

Refer to https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#including-content-in-a-package
