### ISSUE TITLE
Package with runtime native dll in "win" folder not copied to output

### ISSUE THREAD

**Issue by Sumoren** [NuGet/Home#9648]
I have a package with the structure
```
lib
|- net45
|  |- some managed dlls
runtimes
|- win
   |- native
      |- some natives dlls
```
When I consume this nuget from a c# .NetFramework project that target `AnyCPU` it copy the natives dlls to the output as expected. But if the c# project target `x64` then they are not copied.

From my understanding of the documentation here: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#rid-graph
>When NuGet restores packages, it tries to find an exact match for the specified runtime. If an exact match is not found, NuGet walks back the graph until it finds the closest compatible system according to the RID graph.

So it should fallback to `win` RID since it doesn't find any `win-x64` folder.

Why are the natives not copied when the project target `x64`?
I understand that generic `win` native dll is weird concept since the dll must target `x86` or `x64` not both. Is it why RID fallback graph is not apply in that case?

**Comment by nkolev92** [comment]
@Sumoren 

Hey, is the project in question packages.config or PackageReference? 

The runtimes/win pattern is supported only for PackageReference.

**Comment by zivkan** [comment]
Also, assuming the project uses PackageReference, is it "SDK style" (does it have `SDK="..."`), or "non-SDK style" (`Import = ... Microsoft.Common.props`, `Import = ... Microsoft.CSharp.targets`)?

**Comment by donnie-msft** [comment]
⏰ @Sumoren could you please clarify by answering the above?
