### ISSUE TITLE
VS watches / writes packages.lock.json too aggressively

### ISSUE THREAD

**Issue by petsuter** [NuGet/Home#9655]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.5.0

dotnet.exe --version (if appropriate):

VS version (if appropriate): 16.5.4

OS version (i.e. win10 v1607 (14393.321)): win10 1909 18363.836

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1. Store `packages.lock.json` in version control as described on https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file#solution---summary
2. Open Visual Studio
3. Use source control tool (e.g. pull latest changes, rebase)
4. Observe that Visual Studio aggressively watches / writes / tries to undo `packages.lock.json` causes all sorts of troubles. (E.g. from harmless but very annoying: trigger reload of projects when source control temporarily changes `packages.lock.json`; to very problematic when it interferes with ongoing operations like rebase basically causing data corruption.)

Expected behavior: VS should not modify `packages.lock.json` unless asked to. VS should not watch `packages.lock.json`  when VS is not active.

**Comment by nkolev92** [comment]
Hey @petsuter, 

Can you provide us a repro project? 

By default, lock files are not in lockedmode, and projects restore at solution load time. 

It is possible that you are hitting a bug, but we'd need an exact repro to fix your scenario. 

Thanks.

**Comment by petsuter** [comment]
To get a repro case, please create new projects in VS, add `<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>`, install some Nuget packages, and store packages.lock.json in version control. Sorry I can not provide a real world repro project.

Triggering the reload of projects is not difficult as it happens every time. The data corruption is probably not highly reproducible due to time sensitivity of the race condition between file accesses.

**Comment by nkolev92** [comment]
Hey @petsuter,

Unfortunately we won't be able to investigate without better details. 

It's possible that the issues you are facing are already tracked somewhere in our repo, see https://github.com/NuGet/Home/issues?q=is%3Aopen+label%3AArea%3ARestoreRepeatableBuild+label%3AType%3ABug for example. 

If you see anything that rings a bell let us know. 

At this point, I don't think we'll have an actionable on this issue without a repro. 

Thank for you for taking the time to file this issue!
