### ISSUE TITLE
P2P reference with different package graphs drops runtime dependency

### ISSUE THREAD

**Issue by ericstj** [NuGet/Home#966]
The minimal repro is UWP app p2p reference to PCL.  It doesn’t need to reference any other packages, nor is it specific to the unit test template.   

I’ve tried to reproduce the problem in a single project by duplicating the PCL’s package dependencies into that project.  Instead of getting the dependencies {a} from UWP project and {b} from PCL project I put both {a,b} in the UWP project: no repro. I’ve tried ordering in a single project {b,a}: no repro.

It doesn’t need to be a PCL either, if I reference another project that is a UAP class library that only references Microsoft.NETCore I observe the same behavior.  I do not observe this if the class library reference the same package as the head project (Microsoft.NETCore.UniversalWindowsPlatform).

I was able to work around it.  If I directly reference the portable meta-package, Microsoft.NETCore, in the head project the issue goes away. 
```
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",    
    "Microsoft.NETCore": "5.0.0"
  },
```

Given this I think this must be an issue with the P2P feature in nuget.  Repro is here: https://onedrive.live.com/redir?resid=3C96898B9FE8CB59!43764&authkey=!ANxcd48BwL2y3k0&ithint=file%2czip

**Comment by emgarten** [comment]
This will be fixed on @ericstj's side for 3.1. The correct fix for this on the NuGet side will come later.

**Comment by emgarten** [comment]
I'm no longer able to repro this bug using the current dev branch build. The lock file generated for App7 is the same with and without a reference to `"Microsoft.NETCore": "5.0.0"`

**Comment by yishaigalatzer** [comment]
@ericstj ping, can we close this issue or can you still reproduce it?

**Comment by emgarten** [comment]
@ericstj please re-open this is if you can repro it on the latest bits.

**Comment by ericstj** [comment]
I can't repro
