### ISSUE TITLE
Unable to update with locked version on nuget 5.4/5.6 (works on 4.7.1)

### ISSUE THREAD

**Issue by johnruck** [NuGet/Home#9661]
NuGet Versions (5.4 and newer) (only tested on 4.71, 5.4, 5.6)

Discovered this after Sqlite made a breaking change requiring us to lock down to a specific version of the System.data.sqlite nuget packages.  

nuget restore works in finding the specific package version without issue

nuget update fails on 5.4 and 5.6 due to the old version no longer being internally listed

G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest>c:\programdata\chocolatey\bin\nuget update packages.config
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Feeds used:
  https://api.nuget.org/v3/index.json
  http://rivendell.silverblazegaming.com:9000
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Attempting to gather dependency information for multiple packages with respect to project 'G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest\NugetSpecificVersionTest.csproj', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 6.29 sec
Applying constraint '(= 1.0.112)' defined in 'packages.config'.
Unable to resolve 'System.Data.SQLite'. An additional constraint '(= 1.0.112)' defined in packages.config prevents this operation.

G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest>c:\users\john\tools\nuget update packages.config
MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Feeds used:
  https://api.nuget.org/v3/index.json
  http://rivendell.silverblazegaming.com:9000
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Attempting to gather dependency information for multiple packages with respect to project 'G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest\NugetSpecificVersionTest.csproj', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 4.21 sec
Applying constraint '(= 1.0.112)' defined in 'packages.config'.
Applying constraint '(= 1.0.112.1)' defined in 'packages.config'.
Applying constraint '(= 1.0.112.1)' defined in 'packages.config'.
Applying constraint '(= 1.0.112.1)' defined in 'packages.config'.
Attempting to resolve dependencies for multiple packages.
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Resolution was successful but resulted in no action
There are no new updates available.
No package updates are available from the current package source for project 'G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest\NugetSpecificVersionTest.csproj'.
Executing nuget actions took 3.89 ms

G:\git-base\OfficeTests\NugetSpecificVersionTest\NugetSpecificVersionTest>

for reference - the c:\users\john\tools\nuget is version 4.71, the other is version 5.6.

I am attaching a simple project that demonstrates the issue.

[NugetSpecificVersionTest.zip](https://github.com/NuGet/Home/files/4753197/NugetSpecificVersionTest.zip)

**Comment by ghost** [comment]
This issue will now be closed since it had been marked Icebox cleanup candidate, but received no further activity in the past 14 days.
