### ISSUE TITLE
OutputConsoleLogger should not access main thread in constructor.

### ISSUE THREAD

**Issue by srdjanjovcic** [NuGet/Home#9663]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): _VS UI/Package Manager Console_
NuGet version (x.x.x.xxx): _Latest_
dotnet.exe --version (if appropriate): 
VS version (if appropriate): _Latest_
OS version (i.e. win10 v1607 (14393.321)): _Any_
Worked before? If so, with which NuGet version: N/A

## Detailed repro steps so we can see the same problem

OutputConsoleLogger is accessing main thread during construction, which is not a good pattern. As it is MEF-composed object, we cannot convert to "private-ctor-public-async-factory" model, so we should lazily initialize OutputConsole outside the constructor.

**Comment by donnie-msft** [comment]
I think some behavior I reported today triggered this Issue:

I've hit this several times where my Experimental VS is locked up. When I pause, it's usually here:
Detaching the debugger, the EXP instance remains unusable (can't maximize the window). So this seems like 

- bad for debugging

- probably bad for perf if sometimes this logic can hang

![image](https://user-images.githubusercontent.com/49205731/84218813-2ffe3e00-aa9d-11ea-8997-3cdbc3ed3ea3.png)

**Comment by nkolev92** [comment]
Closing this as dup of https://github.com/NuGet/Home/issues/9591 since it's older.

**Comment by nkolev92** [comment]
This did cause a hang in [1145067](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1145067)
