### ISSUE TITLE
can't work in vs2019 it can't find namespace

### ISSUE THREAD

**Issue by cppchuff** [NuGet/Home#9664]
Please read the following information before posting the issue.

## Before posting the issue...

* If you're having trouble with the NuGet.org Website, please post in [NuGetGallery issues](http://github.com/nuget/nugetgallery/issues)
* If you're having trouble with the NuGet client tools (the Visual Studio extension, NuGet.exe command line tool, etc.), you are in the right place.

Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
Microsoft.Web.WebView2.Wpf
NuGet version (x.x.x.xxx):
0.9.538
dotnet.exe --version (if appropriate):
.Net Framework 4.6.2
VS version (if appropriate):
VS2019
OS version (i.e. win10 v1607 (14393.321)):
win10 v1903
Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.
install Microsoft.Web.WebView2.Wpf
2.
add 
xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
into Mainwindow.xaml
3.run report erro
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Microsoft”中不存在类型或命名空间名“Web”(是否缺少程序集引用?)	FairsenseUI	C:\Users\fly\source\repos\FairsenseUI\FairsenseUI\obj\Debug\MainWindow.g.cs	13	活动
and
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	XLS0418	未找到程序集“Microsoft.Web.WebView2.Wpf”。请确保不缺少程序集引用并且已生成你的项目和所有引用的程序集。	FairsenseUI	MainWindow.xaml	8	

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by nkolev92** [comment]
Hey @cppchuff, 

Unfortunately we don't have sufficient information to investigation right now. 

The package you list is unavailable on nuget.org. 
Can you provide us a repro project.

**Comment by mzmlld** [comment]
我也遇到了，在第三次使用的时候，在安装最新版本报错
错误 XLS0418 未找到程序集“Microsoft.Web.WebView2.Wpf”。
并且重装 和 版本倒退到之前用过的版本都不行，
目前只会删除packages文件夹 + 复制以前的packages文件夹，然后就正常了
