### ISSUE TITLE
Move PMC functionality to new VS terminal

### ISSUE THREAD

**Issue by chrisraygill** [NuGet/Home#9666]
In VS 16.6, we have the ability to spawn our own terminal instance in VS. Instead of having a PMC component separate from VS terminal instances, we can consolidate the experience by spawning a terminal instance instead and running PMC commands there.

**Comment by zivkan** [comment]
I'd love it if we can get rid of our own console/terminal implementation.  Note however it's more than just creating the other terminal window. PMC also adds NuGet's cmdlets to the powershell host, plug execute package `init.ps1` which might add additional cmdliets, so we'd need to be able to do that.

**Comment by nkolev92** [comment]
Triage: 
Currently, our console commands rely on being part of the Visual Studio process, in addition to having a powershell host. 

At this point it's technically not feasible to do this.
