### ISSUE TITLE
Enhancement: NuGet spec command should have parameter to override automatic import of project files

### ISSUE THREAD

**Issue by pcgeek86** [NuGet/Home#967]
The documentation for the `nuget spec` command indicates:

> Generates a nuspec for a new package. If this command is run in the same folder as a project file (.csproj, .vbproj, .fsproj), it will create a tokenized nuspec file.

It would be desirable to have a parameter to override this, and prevent the automatic import of a Visual Studio project file.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by emgarten** [comment]
Thanks for the suggestion, we will take a look at this as part of the nuget command line work.
