### ISSUE TITLE
configure.ps1 & build.ps1 error when using Powershell Core

### ISSUE THREAD

**Issue by thomaslevesque** [NuGet/Home#9673]
## Details about Problem

Using PowerShell Core, when I run configure.ps1 and build.ps1 in order to build NuGet.Client, an error occurs:

```
Exception calling "CompareTo" with "1" argument(s): "Cannot process argument because the value of argument "version" is not valid. Change the value of the "version" argument and run the operation again."
At D:\git\NuGet.Client\build\common.ps1:21 char:5
+ if ($PSVersionTable.PSVersion.CompareTo($Version) -lt 0) {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : PSArgumentException
```

The error doesn't prevent the rest of the script from executing.
When using Windows Powershell, it works without error

Powershell version: 6.2.3

NuGet product used: NuGet.Client build scripts

NuGet version: N/A (commit fc9dd52fcdf3c9a299a96de39b641b7c91779b5e)

dotnet.exe --version: 5.0.100-preview.4.20258.7

VS version: VS2019 (16.6.0)

OS version: Windows 10 1903 (Build 18362.900)

Worked before? No idea... probably not

## Detailed repro steps so we can see the same problem

1. Clone the Nuget.Client repo

2. Run configure.ps1. Note the error when the script starts

3. Same with build.ps1

### Verbose Logs

N/A

### Sample Project

N/A

**Comment by nkolev92** [comment]
@teo-tsirpanis hit the same issue.
