### ISSUE TITLE
GitHub Updater Plugin: "Update package not available"

### ISSUE THREAD

**Issue by mere131** [NuGet/Home#9677]
Hello,
I haven't been able to update the "GitHub updater" plugin for a while now. It always says "update package not available". I am using version 9.4.2.9. Any idea why? 
Thanks!

**Comment by jernejk** [comment]
Maybe unrelated but just today we had a problem where nuget restore stopped working and we had to update nuget.exe to latest stable 5.5.1. Maybe you need to update your nuget.exe as well?

**Comment by jernejk** [comment]
Also, they recently removed support for TLS 1.0 and 1.1.

![image](https://user-images.githubusercontent.com/5943653/84741656-b90ffa80-aff2-11ea-9445-9f9d16ae5a4b.png)

**Comment by mere131** [comment]
I reinstalled the plugin and that seemed to help. Thanks!
