### ISSUE TITLE
[Test Failure] PMC & PM UI were disappeared after installing NuGet Client dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466 

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#9679]
## Details about Problem
VS Version: Master\30214.25 
OS Version: Windows-10-Enterprise-RS5. 
## Installation
1. Install VS: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3810721&view=ms.vss-build-web.run-extensions-tab 
2. Install NuGet: \\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\ dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466\artifacts\VS15\NuGet.Tools.vsix 
## Detailed repro steps 
1. Install a clean machine with OS: Windows-10-Enterprise-RS5. 
2. Install Visual Studio 2019 Preview Master\30214.25. 
3. Install NuGet Client dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466. 
4. Launch Visual Studio 2019 Preview and try to open PMC & PM UI.
## Expected
PMC & PM UI can be opened successfully. 
## Actual
PMC & PM UI were disappeared after installing NuGet Client dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466. 
## Notes
1. The implicit NuGet Client is 5.7.0.6630 instead of 5.70.11466 after installing “NuGet Build tools” through “Quick Query”. 
2. It didn’t repro before installing NuGet Client dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466. 
3. Below error prompt when creating F# Console Application (.Net Framework) after step4 as below screenshot. 
![Createdfailed](https://user-images.githubusercontent.com/40230425/84633953-b7c3cc80-af23-11ea-9b62-b509b60e53e7.png)
4. Below error prompt when creating C# UWP in Blend for Visual Studio after step4 as below screenshot. 
![image](https://user-images.githubusercontent.com/40230425/84634144-fbb6d180-af23-11ea-8595-361cbcb4122f.png)

**Comment by nkolev92** [comment]
Definitely equivalent to https://github.com/NuGet/Home/issues/9138.

@v-longmin @v-luzh 

Maybe running the preinstall script can be a part of your set-up whenever you are asked to test branches that are not `dev` or `release-*`

**Comment by v-longmin** [comment]
We verify the issue on Master\30215.128, it has been fixed after creating a clean VM and run preinstall, close it, thanks.
