### ISSUE TITLE
NuGet.exe cred providers should run well when CannotShowDialog is true

### ISSUE THREAD

**Issue by rrelyea** [NuGet/Home#9687]
```
if ($env:NUGET_CANNOT_SHOW_DIALOG == "true" || $env:CODESPACES == "true")
   create PluginCredentialProvider with canShowDialog: false
```

Although our CLIs have interactive switches, sometimes we want an authprovider to be interactive, but not to show a dialog for collection of credentials.

**Comment by donnie-msft** [comment]
Closing CodeSpaces issues.
