### ISSUE TITLE
Package NHibernate.Envers returned version is NOT listed on NuGet Gallery

### ISSUE THREAD

**Issue by v-limi** [NuGet/Home#970]
repro steps:
1. create a project
2. open Manage NuGet Packages window, search package NHibernate.Envers, latest version is 2.0.1
3. check the version on NuGet Gallery, http://www.nuget.org/packages/NHibernate.Envers/, the latest version is 2.0.0

expected results: the package version in NuGet client and Gallery are same
actual results: the version is different

**Comment by emgarten** [comment]
@v-limi can you verify the server changes have fixed this issue?

**Comment by danliu** [comment]
Test automation passed, so it's safe to close it now. Also verified manually.
