### ISSUE TITLE
create tests for INuGetProjectServices.GetInstalledPackagesAsync

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9703]
Feature was manually tested and PR created to make feature available ASAP to unblock UI delays. Need tests to detect regressions and just general good engineering practises.

**Comment by zivkan** [comment]
Also address `var` feedback from NuGet/NuGet.Client#3469 PR.

**Comment by nkolev92** [comment]
Seems like there's a bunch of tests added: https://github.com/NuGet/NuGet.Client/blob/dev/test/NuGet.Clients.Tests/NuGet.VisualStudio.Implementation.Test/Extensibility/NuGetProjectServiceTests.cs

I'm gonna be aggressive and close this. 

Feel free to reopen if you'd like to, but pretty sure the ask has been addressed.
