### ISSUE TITLE
PackageDependencyGroupConverter taking about 8% of thread runtime

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9708]
See screenshot, it's using JObject. Changing this one may not improve memory consumption but reduce runtime on large solutions. Improvement might be not much but worth doing it.

[image.png](https://images.zenhubusercontent.com/5eb1d84a3cd56675c3efe510/94336614-fab5-4ea5-8c8a-41bb9514b2f5)

Related to [#8352](https://github.com/NuGet/Home/issues/8352).

**Comment by nkolev92** [comment]
I think this would help, but as you suggested, I'm not sure how much. Given that's it's a relatively small change, maybe we do it later.

**Comment by nkolev92** [comment]
@erdembayar If this takes under a day and we get measurable improvements I think we sohuld od it.

**Comment by erdembayar** [comment]
It's has been 2 years since I filed bug. Maybe it doesn't matter anymore, if necessary then we can file another bug.
