### ISSUE TITLE
Output of dotnet list package --outdated, when used with VstsCredentialProvider, is very noisy

### ISSUE THREAD

**Issue by laurawalker** [NuGet/Home#9709]
## Details about Problem
When:
- using the dotnet list package --outdated command
- with a private Azure DevOps nuget feed that requires authentication, 
- and with the VstsCredentialProvider (https://github.com/Microsoft/artifacts-credprovider/) installed (from the powershell installation script)

...The output of dotnet list package is interspersed with many instances of the same log messages: 

info :     [CredentialProvider]VstsCredentialProvider - Acquired bearer token using 'ADAL Windows Integrated Authentication'
info :     [CredentialProvider]VstsCredentialProvider - Attempting to exchange the bearer token for an Azure DevOps session token.

I can't find a way to turn these log messages off - dotnet list package doesn't appear to support any of the verbosity commands, and the configurable environment variables for the credential provider also don't appear to help.

------

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
dotnet list package --outdated

dotnet.exe --version (if appropriate):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

VstsCredentialProvider  Command-line v0.1.24+de2b62bcfccebababa9ea4099aba6c44d2f349a4:

### Verbose Logs
Can't include verbose logs as suggested, because the verbosity command doesn't appear to be supported. Screenshot of output is below: 
![image](https://user-images.githubusercontent.com/16760146/85431214-21be2080-b579-11ea-98b0-04d22be6e255.png)

The duplicated messages appear many times (and a varying number of times, possibly waiting for a response) and between each project in the solution.

**Comment by donnie-msft** [comment]
Closing as duplicate: https://github.com/NuGet/Home/issues/9600
Thanks, your details will be referenced there.
