### ISSUE TITLE
Can't access TC builds to get the mirror extension

### ISSUE THREAD

**Issue by simonsabin** [NuGet/Home#971]
I'm trying to access the mirror command as part of nugget.exe as described in here https://docs.nuget.org/consume/command-line-reference#mirror-command

It says go to https://nugetbuild.cloudapp.net/ and use guest login to get the extension from the build but when I access that no builds are displayed.

How can I get hold of a nuget.exe with the mirror command?

**Comment by maartenba** [comment]
This is currently disabled until we have the 3.0 release of NuGet.exe.
