### ISSUE TITLE
Remove using specific version when downloading dotnet for testing

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9712]
When running configure.ps1/runFuncTest.sh, the downloading of master branch failed as following:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20323.3/dotnet-sdk-5.0.100-preview.7.20323.3-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20323.3/dotnet-sdk-5.0.100-preview.7.20323.3-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20323.3/dotnet-dev-win-x64.5.0.100-preview.7.20323.3.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.7.20323.3/dotnet-dev-win-x64.5.0.100-preview.7.20323.3.zip
```
We need to figure out how often the failure is.
For now, we use specific version instead of latest version.
When it's confirmed that the latest version will be available in a stable status, we should remove the workaround.

**Comment by heng-liu** [comment]
https://github.com/dotnet/installer/issues/7893 is fixed. So we could use the latest version of dotnet sdk for testing.

**Comment by nkolev92** [comment]
Closing in favor of https://github.com/NuGet/Client.Engineering/issues/1271. 

cc @heng-liu Correct me if I'm wrong.
