### ISSUE TITLE
Document best practices for creating nupkgs as part of a build

### ISSUE THREAD

**Issue by emgarten** [NuGet/Home#972]
The nuget docs should contain a guide to best practices on how users can pack their project into a nupkg at build time. This should include, how to download nuget.exe and pack during an msbuild task.

A practical guide to providing the nuspec metadata and the current version number at pack time would be helpful also.

/cc @ljw1004

**Comment by ljw1004** [comment]
I wonder if this would be a good place to advise people on which "TFM" to use? A way to tell them: "if your class-library targets XYZ, then use this TFM; if your PCL targets ABC, then use this TFM".

**Comment by emgarten** [comment]
The TFM docs are already in the works, the plan is to have them available after 3.1 is released.  https://github.com/NuGet/Home/issues/720 https://github.com/NuGet/Home/issues/358

**Comment by csharpfritz** [comment]
Added section to v3.3 docs indicating how to compile a package as part of a build
