### ISSUE TITLE
Remove .NET Standard 1.x packages from NuGet SDK packages

### ISSUE THREAD

**Issue by teo-tsirpanis** [NuGet/Home#9723]
## Details about Problem

As also happened in microsoft/msbuild#5242, NuGet's NuGet .NET Standard 2.0 packages reference some libraries that were intended for .NET Standard 1.x and are no longer maintained. What is more, these libraries do not directly target .NET Standard 2.0, they greatly expand the package dependency tree. Because we no longer support .NET Standard 1.x the simplest solution is to just remove these package references.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): `NuGet.Client` packages

NuGet version (x.x.x.xxx): 5.7.0-preview.3

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): N/A

Worked before? If so, with which NuGet version: No

## Detailed repro steps so we can see the same problem

1. Using Paket (which shows dependencies), create a `paket.dependencies` file that contains a reference to a prerelease version of a package like `NuGet.Common`.

2. `paket install`

3. The resulting `paket.lock` file has more than 100 lines for a single dependency.

### Verbose Logs

_N/A_

### Sample Project

_N/A_

**Comment by zivkan** [comment]
@teo-tsirpanis thank you very much for your contribution!  This will ship with NuGet v5.8.0, preview 1.
