### ISSUE TITLE
Hard to see the dash-line box of package format when navigating by tab through the “Choose NuGet Package Manager Format” dialog in Dark theme

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9729]
## Details about Problem
NuGet version: NuGet Client Dev\5.7.0.6677
VS Version: Master\30226.129
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. Launch VS and make sure the theme is “Dark”.
2. Create a C# Console Application (.NET Framework) project via VS and select “All format selection on first package install” in the settings dialog.
3. Open PM UI, click a package in “Browse” tab and lick “Install” button and navigate by Tab key through the opened “Choose NuGet Package Manager Format” dialog.
4. Check if the dash-line box can be seen clearly when the focus are on package format radio boxes: “Packages.config” and “PackageReference in project file”.
## Expected
The dash-line box can be seen clearly when the focus are on package format radio boxes: “Packages.config” and “PackageReference in project file”.
## Actual
Hard to see the dash-line box when the focus are on package format radio boxes: “Packages.config” and “PackageReference in project file” as below screenshot.
![629](https://user-images.githubusercontent.com/20632625/86011606-79fc9300-ba4f-11ea-8b4e-b7e4126b84de.png)
## Note
It is not a regression bug since it repro on 16.5 GA (D16.5 29905.175 with implicit NuGet version 5.5.0.6473).

**Comment by aortiz-msft** [comment]
@v-luzh - Would you please help understand if this is a regression since the last RTM?

**Comment by v-luzh** [comment]
@aortiz-msft It also repro on 16.6 GA (D16.6 30107.121 with implicit NuGet 5.6.0.6591).
