### ISSUE TITLE
Port HttpSource caching bug to NuGet

### ISSUE THREAD

**Issue by pranavkm** [NuGet/Home#973]
Need to determine if this is relevant to NuGet: https://github.com/aspnet/dnx/commit/379eae4a0294712bb7bce0a1cccd9b593a59a8ae

**Comment by yishaigalatzer** [comment]
Verified we already do the right thing

https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Protocol.Core.v3/RemoteRepositories/HttpSource.cs#L216-L217

But this was good because the string for `nuget` was incorrectly capitalized
