### ISSUE TITLE
Revert "shared compilation of XmlUtility"

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9733]
> This change caused CLI failing all over the place https://github.com/dotnet/cli/pull/13406/checks?check_run_id=798366059

(Broken in https://github.com/NuGet/NuGet.Client/pull/3438)

**Comment by kartheekp-ms** [comment]
Thanks @zivkan for suggesting [two possible options](https://github.com/NuGet/NuGet.Client/pull/3438#issuecomment-649737830) for this issue,

> one possible solution is to wait until we stop inserting into .NET Core 3.1

I don't know when we stop inserting into .NET Core 3.1. As per [.NET Core release lifecycles doc](https://dotnet.microsoft.com/platform/support/policy/dotnet-core), 3.1 is `LTS` support level now which makes me think that we  keep inserting into this version of SDK in the foreseeable future.

I have a question before we consider second option. `NuGet` dependencies are configured in [CLI](https://github.com/dotnet/cli/blob/85f4cbb5859e6ba74c2f70ab93c66e27ff6ee613/eng/Versions.props#L60) repo. I would like to understand why `NuGet.Commands` package version is not specified even though `NuGet.Build.Tasks` has a direct dependency on this package but other assembly versions are configured. I see similar settings in [dotnet/sdk](https://github.com/dotnet/sdk/blob/master/eng/Versions.props#L49) repo where we insert NuGet code in .NET5. I assume the initial PR would have failed the .NET 5 insertion build also.

**Comment by nkolev92** [comment]
This is meant to staay closed @kartheekp-ms 
It's tracking the revert. The original issue should be re-opened.

3.1 is LTS, but it's not going to be under active development, rather maintenance. 
So 5.8 is when we can change it.

**Comment by kartheekp-ms** [comment]
Thanks @nkolev92 for closing this issue. TBH I realized my mistake last night and wanted to close this one and reopen original issue as first thing in the morning. I will reopen original issue and start discussion there.
