### ISSUE TITLE
Feature Suggestion: Provide a switch or config to ignore the package downloading from trustless sources

### ISSUE THREAD

**Issue by walterlv** [NuGet/Home#9734]
## Situation

I have two package sources:

1. [nuget.org](https://nuget.org): This is the only fully trusted source.
1. A private NuGet source: this is a mirror source of the former one, and it also provides some private packages.

What matters is that the second source lists a package not existed and download it from the first one. But the downloading operation fails at very high risk so that it provides an error to the NuGet client:

> C:\Program Files\dotnet\sdk\3.1.201\NuGet.targets(124,5): error : Source "second [http://**.**.**.**/nuget" lists the package "dotnetcampus.picktextvaluetask.1.1.322", but all downloads to this package fails.

## Suggestion

I have a suggestion to the NuGet client to ignore errors to the trustless source. Maybe one of these solutions works:

My first alternate suggestion: Add an attribute to the NuGet.config file as below:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="rubbish.xx" value="http://xx.xx.xx.xx/v3/index.json" treatAsTrustless="true" />
  </packageSources>
</configuration>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" isTrustSource="true" />
    <add key="rubbish.xx" value="http://xx.xx.xx.xx/v3/index.json" />
  </packageSources>
</configuration>
```

If I configure the NuGet like this and run `nuget restore`, the nuget client only fetch packages from those trustless sources if all the trust sources don't have.

My second alternate suggestion: Add a command-line option to fulfill the same effect as the first one.

**Comment by donnie-msft** [comment]
PowerShell offers a paradigm that may be relevant for NuGet to adopt, with the `-Trusted` parameter in the PowerShell tool, `Register-PackageSource`. https://docs.microsoft.com/en-us/powershell/module/packagemanagement/register-packagesource?view=powershell-7#examples

**Comment by donnie-msft** [comment]
Do you think this feature would help your scenario? https://github.com/NuGet/Home/issues/6867

**Comment by nkolev92** [comment]
Hey @walterlv, we have a feature design for #6867 in https://github.com/NuGet/Home/pull/10660. 

Does that fit your scenario?

**Comment by walterlv** [comment]
@nkolev92 Thanks for your reply.

I think #10660 (`package namespaces`) solves my issue. What our private source provides are packages with internal namespaces, which is the right scenario of the feature.

**Comment by nkolev92** [comment]
Happy to hear that. 

I will close this as dup of https://github.com/NuGet/Home/issues/6867, which is the tracking issue for the feature. 

Please let us know if you have any feedback on our design!
