### ISSUE TITLE
Unable to load the service index for source https://api.nuget.org/v3/index.json. (The remote server returned an error: (403) Forbidden.)

### ISSUE THREAD

**Issue by xtompe** [NuGet/Home#9735]
## Details about Problem
I am unable to install "Microsoft.Data.SqlClient" NuGet package.
I get following in the log window:

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The remote server returned an error: (403) Forbidden.

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):
VS UI

NuGet version (x.x.x.xxx):
Package Manager Console Host Version 5.5.0.6473

## Detailed repro steps so we can see the same problem

1. Open "NuGet Package Manager" in any VS Solution
2. Go to "Browse" tab
3. Write "Microsoft.Data.SqlClient" in the "search" field
4. Select "Microsoft.Data.SqlClient" package and click "Install"

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by donnie-msft** [comment]
Perhaps this was a transient network error, or a proxy configuration issue? Can you access the URL from your web browser?

**Comment by nkolev92** [comment]
Closing per @donnie-msft's comment. 

Thank you reporting this issue. At this point we do not have enough information to continue investigating the issue. 
Please feel free to comment or open a new issue if needed.
