### ISSUE TITLE
[Performance]: Find a solution with better performance to reject the central transitive dependencies that have rejected parents. 

### ISSUE THREAD

**Issue by cristinamanum** [NuGet/Home#9740]
## Details about Problem
Related with the issue [Rejected transitive central dependencies should be removed from the restore graph](https://github.com/NuGet/Home/issues/9483) 

The [current solution](https://github.com/NuGet/NuGet.Client/pull/3374) does multiple loops through the the list of the central dependencies and their parents to detect any rejected parents. 

Evaluate if a different solution with better performance exists.

**Comment by cristinamanum** [comment]
Pull this in 177 if time allows

**Comment by nkolev92** [comment]
With the resolver rewritten, this is no longer relevant.
