### ISSUE TITLE
Listing transitive packages does not work with Xamarin projects

### ISSUE THREAD

**Issue by Cheesebaron** [NuGet/Home#9747]
## Details about Problem

dotnet.exe --version: **3.1.301**

## Detailed repro steps so we can see the same problem
Run: `dotnet list package --include-transitive` on any Xamarin.Android or Xamarin.iOS project. You will get the error:

> error: The imported project "C:\Program Files\dotnet\sdk\3.1.301\Xamarin\Android\Xamarin.Android.CSharp.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.301\Xamarin\Android\Xamarin.Android.CSharp.targets" is correct, and that the file exists on disk.  C:\git\MvvmCross\Projects\Playground\Playground.Droid\Playground.Droid.csproj

Similarly, with Xamarin.iOS projects, where it is looking for Xamarin.Apple.CSharp.targets.

The targets for Xamarin.iOS and Xamarin.Android live in: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin` not in the dotnet sdk folder.

Also posted here: https://github.com/dotnet/core/issues/4218

**Comment by rrelyea** [comment]
Currently, dotnet.exe list package relies on the dotnet.exe copy of msbuild.exe -- and its associated targets and props files.
As such, projects that need VS and its targets/props, aren't supported by dotnet.exe list package.

Classifying this issue...as we may choose to investigate ways to address in future, given enough votes, etc...

**Comment by Cheesebaron** [comment]
It would be very useful to have support for this with Xamarin Apps. Especially for generating "About" pages in Apps to comply with accepted licenses from NuGet packages etc. Currently, it requires quite a lot of manual effort to get the complete list of packages used in your App.

**Comment by nkolev92** [comment]
Adding NeedsTriageDiscussion. 
dotnet.exe supporting non-SDK projects seems unlikely at this point, as such, I don't see a path forward for this issue right now.

**Comment by jebriede** [comment]
[Team triage]: @nkolev92 what do you think about opening a bug against the SDK and resolving this as external since NuGet doesn't control which project types are loadable by .NET Core msbuild.

**Comment by nkolev92** [comment]
Team Triage: dotnet is only meant to work with SDK based projects, and given that these projects are not SDK based, the dotnet based commands can't support them.
