### ISSUE TITLE
Installed/Updates UI Filtering can be more conservative with Reloading

### ISSUE THREAD

**Issue by donnie-msft** [NuGet/Home#9749]
In https://github.com/nuget/home/issues/8294, I've applied UI Filtering to the Installed/updates tab-switches only when those tabs are loaded once. This was a tiny-step forward, and this issue is to take another (final?) step in this filtering.

1. Updates doesn't need to load independently of Installed. 
2. Switching away from Installed/Updates doesn't need to trash the cache. Keep it around and use it when switching back.

Related Issue that gets tangentially affected with this work https://github.com/nuget/home/issues/4176

**Comment by nkolev92** [comment]
> Switching away from Installed/Updates doesn't need to trash the cache. Keep it around and use it when switching back.

2 looks like #4176 basically :) 

Should this be an epic?

**Comment by donnie-msft** [comment]
closing in favor of more fleshed-out Epic https://github.com/NuGet/Home/issues/10082
