### ISSUE TITLE
PackageManager UI no longer shows projects that already reference the package

### ISSUE THREAD

**Issue by JasonBSteele** [NuGet/Home#975]
In VS 2013 if you Managed Packages for the solution and filtered by Installed Packages then selected a package, the dialog would show ticked check boxes for those projects which are using the package. 

In VS 2015 I cannot find a way to show which projects are already using a package.

**Comment by csharpfritz** [comment]
Use the filter combobox to select either "Installed" or "Upgrade Available"
to see these filtered views of the package list



Jeff

**Comment by JasonBSteele** [comment]
That's only half the story. Selecting installed shows me which packages are installed, but it doesn't show me which projects are actually using them. The projects listed ALL have ticks next to them for the "Install" Action whereas in 2013 only the projects that were already referencing the package would be ticked. You could then untick or tick others and click the button to update.

I have found a workaround. If you select "Uninstall" as the action then the projects that reference the 
the package are listed.

This is far from ideal as to work out which projects will end up referencing the package you have to flick back and forth between the Install and Uninstall Actions (and take screen shots!).

A solution may be for the Install action to also list those projects that already have the package, but with a grayed out ticked check box indicating that the action cannot uninstall them.

**Comment by yishaigalatzer** [comment]
@JasonBSteele this is good feedback, I'm adding this to the UI update bug and closing this one.

**Comment by yishaigalatzer** [comment]
https://github.com/NuGet/Home/issues/885
