### ISSUE TITLE
Package Manager UI memory leak when package metadata is garbage collected due to a bad binding

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9757]
I decided to create separate ticket from [#9731.](https://github.com/nuget/home/issues/9731) 
This one is for UI mostly.
Reproduce: 
1. Open solution in "Experimental  Instance".
2. Open PM UI go to "Browse", "Updates", "Consolidate" tabs then close it. Next close whole project.
3.  As you can see 2 attached images there are 3228 pcs of `NuGetVersion` and 1748 pcs of `VersionRange` items are stayes even though PM UI is closed. 
![image](https://user-images.githubusercontent.com/8766776/86664932-06eda200-bfa4-11ea-82e5-7ffcc543f64c.png)

![image](https://user-images.githubusercontent.com/8766776/86665171-3f8d7b80-bfa4-11ea-9a05-538b4ef4e9be.png)

4.  Repeat from 1 to 2. As you can see below `NuGetVersion` number increased from 3228 to 4260 and `VersionRange` number increased from 1748 to 3491.

If you open and close PM UI more than 10 times then it could be reach few MBs easily.

![image](https://user-images.githubusercontent.com/8766776/86667205-41583e80-bfa6-11ea-969c-704452d438b7.png)
![image](https://user-images.githubusercontent.com/8766776/86667277-546b0e80-bfa6-11ea-8b53-de63f6e43b24.png)

Seems like this was likely a long standing problem with our spinner control in the middle of PackageManager UI.
This caused every entire PM UI control tree to stay alive, because the spinner control had databindings to normal CLR objects...which cause propertyDescriptor tables in CLR to hold on to the spinner. Which causes the entire tab to stick around.  I was chasing the Version objects...but they were being held onto by the PM UI control instance.
So, over time, this led to much memory growth if people opened and closed PM UI alot.  (by moving the data type to implement INotifyPropertyChanged interface, wpf databinding avoided propertyDescriptors..and thus avoiding creating the problem.)

Before entire PM UI tree was not released from memory together holding everything in it, now it's released and can be GCed, with this changes fixes more than originally chasing after which was only NugetVersion and VersionRange.

**Comment by nkolev92** [comment]
In the investigation of this PR, @erdembayar noticed something that looks like a potential memory leak in the PM UI. 

Certain data was not getting cleaned up after closing the PM UI.

**Comment by erdembayar** [comment]
Thanks to @rrelyea @donnie-msft @srdjanjovcic fix it ready. Please review.
