### ISSUE TITLE
skipDuplicate and symbol package

### ISSUE THREAD

**Issue by clement911** [NuGet/Home#9758]
We use the `skipDuplicate` option so that a Github action can push a new nuget version whenever the version is incremented, and skip the push if that version was already published.

This works but the `skipDuplicate` doesn't appear to skip the symbol package.

As a result, a new symbol package is pushed on a every build. Because the symbol package doesn't match the originally publish nuget package, we receive an error by email "Symbol package validation failed".

See following image:
[1] Main package is skipped
[2] Symbol package is pushed nonetheless

![image](https://user-images.githubusercontent.com/3426504/86759452-d578e300-c044-11ea-851f-71de76551ab6.png)

Is there a way to skip symbol publication if the main package is skipped?

**Comment by zivkan** [comment]
duplicate of https://github.com/NuGet/Home/issues/9647.
