### ISSUE TITLE
[Test Failure] None package is showed under ‘Reference’ node in ‘Solution Explorer’ after installing package with ‘PackageReference’ format 

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#9759]
## Details about Problem

**NuGet Version:** Dev\5.7.0.6689
**VS Version:** Master\30306.116
**OS Version:** Windows-10-Enterprise-RS5

## Installation steps: 
1. Install VS: [https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3869190&view=ms.vss-build-web.run-extensions-tab](url)
2. Install NuGet Client: [\\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\Dev\5.7.0.6689\artifacts\VS15\NuGet.Tools.vsix](url)

## Repro steps: 

1. Create a C# Console App (.Net Framework) project.
2. ‘Tools’->’NuGet Package Manager’->’ Package Manager Settings’->check in ‘Allow format section on first package install ’.
3. Open ‘Manager NuGet Packages…’.
4. Install package ‘Newtonsoft.json’ with **‘PackageReference**’ format.

## Expected:
The Package should be showed under ‘Reference’ node in ‘Solution Explorer’.

## Actual:
None package is showed under ‘Reference’ node in ‘Solution Explorer’ as below screenshot.
![bug0707](https://user-images.githubusercontent.com/20632775/86763199-bd6f8680-c079-11ea-99f6-7097b901a1ca.png)

## Notes: 
1. The issue repro on VS Master\30306.116 with implicit NuGet Client Dev\5.7.0.6677.
2. The issue didn’t repro on UWP project and .NET Core project.

**Comment by donnie-msft** [comment]
No repro on 16.6.3
Repro on 16.8.0 Preview 1.0 [30306.11.master]

Clicking "Refresh" in Solution Explorer will show the package.

**Comment by donnie-msft** [comment]
I believe this is a regression on the VS side in 16.8.

Did not repro with Version 16.7.0 Preview 3.1 (VisualStudio.16.Preview/16.7.0-pre.3.1+30223.230).
Did repro with 16.8.x. without installing the VSIX above.

**Comment by heng-liu** [comment]
I could repro on VS 16.7 preview4. 
So this is a regression since 16.7 preview4.
Hi @nkolev92, I heard from triage meeting that, this level of node belongs to project system. So I'm wondering if it's necessary to check if it's brought in by our code or not? As I'm checking the compatibility tenet. Do you have any suggestion on this issue? Thanks!

**Comment by nkolev92** [comment]
In csproj.dll (Legacy) PackageReference based projects the node there is *completely* owned by the project system. 
I'd recommend we move it to their repo. 

You can use the global tool from https://www.nuget.org/packages/GithubHelperTool/ to transfer issues. 
You'll need a GH PAT.

**Comment by heng-liu** [comment]
Thanks @nkolev92 :)

**Comment by heng-liu** [comment]
Couldn't repro with VS16.3 + VSIX from Dev\5.7.0.6689, so it's not a NuGet issue.
