### ISSUE TITLE
Add RPS tests over real-world solutions

### ISSUE THREAD

**Issue by srdjanjovcic** [NuGet/Home#9760]
Such as OrchardCore and Roslyn

**Comment by nkolev92** [comment]
To goal here is to add a test for a primarily PackageReference based large solution. 

We want to have a representative of each solution type that we care for an OrchardCore is a good representative of the large sln group. 

The scenarios we care for are similar to the ones we care for in our cmd perf scripts: https://github.com/NuGet/NuGet.Client/tree/dev/scripts/perftests#nuget-client-performance-test-suite

Here we are interested in: 

1. No global packages folder, no http caches, nothing on disk.
2. All packages are on disk, no obj folders in the solution.
3. No-op where all the assets files exist and all packages are on disk.

An aspiring goal would be additional scenarios where the packages are on disk, but the assets files are *not* up to date for one reason or another. 
Given that the scenario is more difficult to set-up, we can do it in the future.

**Comment by nkolev92** [comment]
Primarily the focus here is solution load, that's the scenario that we care about the most. 

We should still test a few warm restores in VS by running Build/Restore NuGet Packages command.

From an analysis perspective, I think we care about the scenarios 2 and 3 more, so if you get into analyzing the results, I think that's our focus.
