### ISSUE TITLE
RPS: Adjust NuGet-Restore scenario markers to avoid capturing events during solution load

### ISSUE THREAD

**Issue by srdjanjovcic** [NuGet/Home#9761]
We are currently using `Microsoft-VisualStudio-Common/vs_nuget_projectinformation` event for start of the scenario, but we should have dedicated nuget-restore/Start event or something like that to actually capture start of restore. For now, that may be `Microsoft-VisualStudio-Common/vs_nuget_restoreinformation_restoreoperationchecks/Start`

**Comment by nkolev92** [comment]
@srdjanjovcic link the PR.

**Comment by srdjanjovcic** [comment]
AzDO Pull Request [259695](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/259695): Inner loop perf tests: Adjust NuGet scenarios.
