### ISSUE TITLE
Test: VerifySignaturesAsync_ExpiredCertificateAndTimestampWithTooLargeRange_FailsAsync is flaky on mac and Linux

### ISSUE THREAD

**Issue by heng-liu** [NuGet/Home#9763]
The VerifySignaturesAsync_ExpiredCertificateAndTimestampWithTooLargeRange_FailsAsync test is flaky on Mac only:
Error message:
```
Assert.Equal() Failure
Expected: 0
Actual: 1
```
or

```
Assert.Equal() Failure
Expected: 0
Actual: 2
```
Stack trace:
```
 at NuGet.Packaging.FuncTest.SignatureTrustAndValidityVerificationProviderTests.VerifySignaturesAsync_ExpiredCertificateAndTimestampWithTooLargeRange_FailsAsync() in /Users/runner/work/1/s/test/NuGet.Core.FuncTests/NuGet.Packaging.FuncTest/SigningTests/SignatureTrustAndValidityVerificationProviderTests.cs:line 234
--- End of stack trace from previous location ---
```

**Comment by rrelyea** [comment]
another hit https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3879869&view=results

**Comment by heng-liu** [comment]
I could repro by running the same tests for 100 times.
After investigation, I found all the second chain build succeed, but first chain build failed at 5% of the time, even if wait for 10s before first chain build. And all the 100 times of the tests are building the same certificates chain. 
Raised an issue in https://github.com/dotnet/runtime/issues/43608
