### ISSUE TITLE
RestoreIgnoreFailedSources=true still gives warnings

### ISSUE THREAD

**Issue by shahabhijeet** [NuGet/Home#9765]
I am trying to suppress NU1801 warning (Unable to load the service index for source…) If one of the Nuget sources is not accessible.
I have tried the following:
1. Provided this as one of the property to Restore Target  
 a. RestoreIgnoreFailedSources=true
2. Also added `<NoWarn>NU1801</NoWarn>` 
3 .Also pass `/p:NoWarn=NU1801`

NugetVersion = latest from nuget.com
dotnet = 3.1.301
VS = 16.6.3
OS = Win10

**Comment by rrelyea** [comment]
Can you tell us more about your scenario?
We'd prefer you disable sources that you know will be offline or unavailable.
Is there a reason that doesn't work well for you?

**Comment by shahabhijeet** [comment]
We have a scenario where we need to have code base in two different devOps organization for the next 6 months (we accquired a company recently)
And during stabilization we had to move code base between two orgs (devOps orgs) and hence each org had separate nuget feed.
So that is when I thought of using the `RestoreIgnoreFailedSources` flag to our advantage but saw bunch of warnings.
alternative is
add some smarts so that we add condition somehow to selectively choose the right nuget.config or pipeline yml files.

**Comment by rrelyea** [comment]
Perhaps you could conditionally add sources for environment 1 and environment 2...
RestoreAdditionalProjectSources is an msbuild property -- (from docs here: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets)

And then you wouldn't need to play with 2 different nuget.configs for the two different environments.

That said, this bug is still true...and we should triage, etc...
But i get nervous with uses of RestoreIgnoreFailedSources!!

**Comment by rrelyea** [comment]
Repro steps:
```
rd home9765 /s/q
md home9765
cd home9765
md packages9765
dotnet new globaljson --sdk-version 3.1.301
dotnet new nugetconfig
dotnet nuget add source packages9765
dotnet new classlib
dotnet add package newtonsoft.json
dotnet nuget add source directoryThatDoesNotExist
dotnet nuget locals -c all
dotnet restore /p:RestoreIgnoreFailedSources=true /p:NoWarn=NU1801
```

**Comment by rrelyea** [comment]
Believe my fixes for https://github.com/NuGet/Home/issues/9688, plus a tiny bit more will fix this.
Update: while my understanding of the area is much deeper...my belief was that a quick fix would be to move from _logger to logger...however, that didn't work. so this will take more investigation sometime in the future.

**Comment by nkolev92** [comment]
My fix for https://github.com/NuGet/Home/issues/7245 will solve this one too
