### ISSUE TITLE
Introduce a warning for null/empty version range (new or reuse NU1604)

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9767]
NU1604 currently complains that a project has a dependency without an inclusive lower bound.

https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1604

Now, often times this is true, but most frequently, the problem is that someone was playing with MSBuild and the variable that contains the version is now empty.  

The message can reflect that. 

We could introduce a new warning, but maybe there's no need for that.

**Comment by ocallesp** [comment]
"... has no version, or does not include a lower bound"

**Comment by nkolev92** [comment]
The warning check happens after restore has been completed, and the assets file has been created. 

https://github.com/NuGet/NuGet.Client/blob/a4c9d63bf942f1df1ba9486a87bad2e4b6888488/src/NuGet.Core/NuGet.Commands/RestoreCommand/Diagnostics/UnexpectedDependencyMessages.cs#L175-L186

**Comment by erdembayar** [comment]
@nkolev92 
I propose to close this issue, because we already fixed this issue with [PR#3796](https://github.com/NuGet/NuGet.Client/pull/3796) while fixing issue https://github.com/NuGet/Home/issues/9289. Because repro I used for that [PR#3796](https://github.com/NuGet/NuGet.Client/pull/3796) was https://github.com/erdembayar/IssueRepro9289. That repro has exact problem "MSBuild and the variable that contains the version is now empty" which is described in this issue body. Here is `MicroBuildVersion` is MSBuild variable but value it not set.

    <PackageReference Include="Text2Xml.Lib" Version="$(MicroBuildVersion)" PrivateAssets="all" />

Here is current current VS error/warning outputs:
![image](https://user-images.githubusercontent.com/8766776/108786566-b625bc00-7528-11eb-9a71-1b1d29975523.png)
![image](https://user-images.githubusercontent.com/8766776/108786671-f422e000-7528-11eb-91ad-417744972087.png)

Here is dotnet output:
```
C:\NuGetProj\IssueRepro\9289\IssueRepro9289>dotnet restore
  Determining projects to restore...
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\C\C.csproj : warning NU1604: Project dependency Text2Xml.Lib does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\B\B.csproj : warning NU1604: Project dependency NuGet.Common does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\A\A.csproj : warning NU1604: Project dependency Text2Xml.Lib does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\B\B.csproj : warning NU1604: Project dependency Text2Xml.Lib does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\B\B.csproj : warning NU1701: Package 'NuGet.Common 3.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
C:\NuGetProj\IssueRepro\9289\IssueRepro9289\Top\Top.csproj : warning NU1604: Project dependency Text2Xml.Lib does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results. [C:\NuGetProj\IssueRepro\9289\IssueRepro9289\IssueRepro9289.sln]
  Restored C:\NuGetProj\IssueRepro\9289\IssueRepro9289\Top\Top.csproj (in 852 ms).
  3 of 4 projects are up-to-date for restore.
```

I believe current output gives user enough info to guide in correct direction to investigate. User will immediately start checking why `Text2Xml.Lib does not contain an inclusive lower bound.`.

**Comment by nkolev92** [comment]
@erdembayar 

The bug that was fixed in https://github.com/NuGet/NuGet.Client/pull/3796 was actually not the common scenario. 

A lot larger percentage of people use SDK based PackageReference projects and they can run into the same scenario, and in fact they already often do.

The body of this issue acknowledges that and says that the message *could* be better. 

Currently the text of NU1604 says that the lower bound is missing. In some cases, the version is missing altogether. That's something that we know at restore and we could write a better message, especially for direct dependencies. 

As such, I don't think we should close this, because the main problem is not addressed.

**Comment by nkolev92** [comment]
That doesn't mean you have to do it yourself though. 

If you prefer to solve other issues, feel free to unassign as this is not a very high priority issue at this point.

**Comment by erdembayar** [comment]
@nkolev92 
Ok. I unassigned myself to focus on other higher priority issues.

**Comment by nkolev92** [comment]
I vote for changing the message here instead of introducing a new warning.
