### ISSUE TITLE
Nuget Restore says all packages are already installed and there is nothing to restore but iam getting an error during build

### ISSUE THREAD

**Issue by santoshi12** [NuGet/Home#9768]
Getting the below error during build in vs 2019
This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Gsl.0.1.2.1\build\native\Microsoft.Gsl.targets.

The packages folder in the solution is getting updated with that particular package whenever I restore but facing the above issue during build

**Comment by rrelyea** [comment]
Looks like that package was last published  in 2016 and has been marked on nuget.org as deprecated.

**Comment by santoshi12** [comment]
closed
