### ISSUE TITLE
"TheDateTimeOffset specified cannot be converted into a Zip file timestamp" with Microsoft.Extensions.DependencyInjection v3.1.0

### ISSUE THREAD

**Issue by pavanupb** [NuGet/Home#9774]
I am getting "TheDateTimeOffset specified cannot be converted into a Zip file timestamp" error while trying to build the solution. I am building an analyzer using Roslyn and using Microsoft.Extensions.DependencyInjection V3.1.0. However when I try to build the solution I am getting a build error. The date modified field is null for Microsoft.Extensions.* dll's. 
I have installed .Net SDK v3.1.301.

![image](https://user-images.githubusercontent.com/38906373/87083835-8e9a1180-c22d-11ea-9fa1-1be58a0b7030.png)

**Comment by rrelyea** [comment]
This doesn't sound like a nuget problem? Can you give more details so we can route correctly?

**Comment by nkolev92** [comment]
Possible dup in https://github.com/NuGet/Home/issues/7001. 

Are you running pack on build @pavanupb

**Comment by pavanupb** [comment]
> Possible dup in #7001.
> 
> Are you running pack on build @pavanupb

Yes

**Comment by nkolev92** [comment]
Closing as dup in that case.
