### ISSUE TITLE
Can't consume "Portable-net45+netcore45+wpa81+wp8" from project.json with imports": "portable-net452+win81"

### ISSUE THREAD

**Issue by ljw1004** [NuGet/Home#978]
The effect of this issue is that I don't seem to have a straightforward way to write a nuget package that can be consumed everywhere >=net45.

REPRO:
1. Create a NuGet package with a Profile259 pcl (targets NET45+Win8+WP81+WPSilverlight8) inside the “lib\portable-net45+win8+wpa81+wp8” directory
2. File>New>VB>PCL with targets “NET46 + UWP + DNX”. It has a project.json with imports": "portable-net452+win81"
3. Try to install that NuGet reference

WHAT I GET:
NuGet install fails with the message “MyNupkg 1.0.0 is not compatible with DNXCore,Version=v5.0.”

**Comment by emgarten** [comment]
This guard rails error is expected here. DNX is only compatible with DNX and dotnet.

**Comment by emgarten** [comment]
Moving this to 3.2 since there are some open questions around dnx support for PCLs.

**Comment by yishaigalatzer** [comment]
Discussing with @davidfowl, we think the dotnetstandard will allow for building such packages. But DNX is not planning to allow for these platforms to match
