### ISSUE TITLE
NuGet restore in VS should report progress to allow the project-system to better control design time build scheduling. 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9782]
CPS side: [1146684](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1146684)

Right now the BulkFileOperation API does not allow overlapping intervals. 

Internal issue: [1418717](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1418717/)

Design: https://github.com/NuGet/Home/blob/dev/proposed/2021/ProjectUpdateEventsInVisualStudio.md

PR in progress: https://github.com/NuGet/NuGet.Client/compare/dev-nkolev92-restoreProgressEvents?expand=1

**Comment by nkolev92** [comment]
This was discussed in a recent sync-up with project-system. 
They are to set-up a sync with us to discuss.

**Comment by nkolev92** [comment]
We have some experimentation we need to do...assigning to this sprint with 10pts.

**Comment by nkolev92** [comment]
There's a bug in BFO that requires we switch to the UI thread to check for a BFO. Needless to say, that's inconvenient and costly :) 

[1270921](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1270921/)

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/10678

**Comment by nkolev92** [comment]
This is blocked on prioritization for now.

**Comment by nkolev92** [comment]
Per discussions with @lifengl and others, we'll likely want a new API here.

**Comment by nkolev92** [comment]
Updating the estimate to represent the leftover work.

**Comment by zkat** [comment]
Moved to next sprint because you were a bit over :)

**Comment by nkolev92** [comment]
Lack of learning day means I only have 3 points for this week. I should be able to at least start this issue.
