### ISSUE TITLE
 Could not copy Error in docker linux container

### ISSUE THREAD

**Issue by ZergRushJoe** [NuGet/Home#9787]
## Details about Problem
I keep getting this error from my 'docker build .'. I'm getting the error with this .net core microsoft.analysisservices.adomdclient.netcore.retail.amd64. The Error that comes from it:

/usr/share/dotnet/sdk/3.1.301/Microsoft.Common.CurrentVersion.targets(4360,5): error MSB3021: Unable to copy file "/root/.nuget/packages/microsoft.analysisservices.adomdclient.netcore.retail.amd64/19.4.0.2-preview/lib/netcoreapp3.0/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll" to "bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll". Could not find a part of the path '/app/Processor/bin/Debug/netcoreapp3.1/zh-HANS/Microsoft.AnalysisServices.AdomdClient.resources.dll'

Don't know why it can't find that package. it restores just fine. I know it builds on windows which more then likly means I can never get it to work. The project it is in is an F# project.

Docker File
From node:12 AS web-build

COPY ./Web.UI ./

RUN npm i
RUN npm run test
RUN npm run buildProd

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS backend-build

WORKDIR /app
COPY . ./
COPY --from=web-build /Processor/wwwroot ./Processor/wwwroot
RUN dotnet test
RUN dotnet publish -c Release -o publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=backend-build /app/publish .
EXPOSE 80

**Comment by aortiz-msft** [comment]
This issue was moved to dotnet/sdk#12611
