### ISSUE TITLE
The down icon icon when the latest package version is installed is not intuitive. The old green tick was perfect

### ISSUE THREAD

**Issue by andreinitescu** [NuGet/Home#9789]
The NuGet package manager in Visual Studio shows a green "arrow down" icon when the **latest version** of the package is **already installed**:

![image](https://user-images.githubusercontent.com/743918/87300628-d6af8180-c516-11ea-8b0c-c671499c08d1.png)

The current "arrow down" icon is more commonly associated with the "_A new version is available to download_" idea than with "_The version is up to date_".

It used to show a green tick, which was more intuitive:

![image](https://user-images.githubusercontent.com/743918/87300801-360d9180-c517-11ea-8c99-46afea507b3f.png)
(Image taken from https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio)

## Details about Problem

NuGet product used: VS UI
VS version (if appropriate): 2019

Worked before? If so, with which NuGet version: No idea of the version when it was changed

## Other suggested things (optional)

Since we're at it, I'd like to suggest using these icons:

**Latest version** installed: 
![image](https://user-images.githubusercontent.com/743918/87301155-baf8ab00-c517-11ea-898d-f51a8e7dda89.png)
Like I said above, it's basically the previous icon which was shown by VS 

**New version** available:
![image](https://user-images.githubusercontent.com/743918/87301387-2b9fc780-c518-11ea-9bb8-eb6992a1d4a7.png)
 (maybe with dark yellow instead of blue)

**Comment by nkolev92** [comment]
Triage: Assigning to @chgill-MSFT for evaluation.

**Comment by donnie-msft** [comment]
@chgill-MSFT has this been evaluated? I'm working on icons now, so ideal time to change it, if warranted

**Comment by nkolev92** [comment]
cc @JonDouglas for awareness :)

**Comment by JonDouglas** [comment]
@andreinitescu I think I agree with your assessment of using a checkmark instead of a green down arrow & other suggestions.

I believe the reason why it's a green down arrow is to complement the opposite which is a blue up arrow for "update available". However this is pretty confusing as a user. I've ran into this many times myself too where I mistakenly check for updates because I see the icon yet there's no updates!:

![image](https://user-images.githubusercontent.com/1288848/91781593-45789500-ebc0-11ea-861d-9edb1e8a2d71.png)

![image](https://user-images.githubusercontent.com/1288848/91781497-17935080-ebc0-11ea-835a-c67811c97962.png)

We'll try reverting to the old "Ok" icon which is the green checkmark & we'll see if we can change the "Update" icon to an updated universal "sync" such as what you suggested.

![image](https://user-images.githubusercontent.com/1288848/91782291-4ad6df00-ebc2-11ea-9923-a68e53d76d79.png)

![image](https://user-images.githubusercontent.com/1288848/91782312-562a0a80-ebc2-11ea-8923-b678cdfd17c0.png)

👍 if you're reading this & believe this is better than the current behavior above.

@donnie-msft Feel free to see how these look & post a screenshot.

**Comment by donnie-msft** [comment]
Here's the StatusOK checkmark in light/dark themes. Seems there's no white halo around it. Dark mode is currently inverting colors which is a difference from existing behavior, but designers prefer we leave that enabled going forward.
EDIT: I learned the design team will be adding icons with the halos/borders probably in October.

![image](https://user-images.githubusercontent.com/49205731/92146197-5bb46a00-ede7-11ea-9156-8e588b6dd204.png)
![image](https://user-images.githubusercontent.com/49205731/92146308-87375480-ede7-11ea-85aa-26e3e999c2e7.png)

**Comment by donnie-msft** [comment]
Design team will have these icons available no earlier than October 2020.
Tracking here: https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/12595

**Comment by donnie-msft** [comment]
Example:
`- Moniker="{x:Static nuget:PackageIconMonikers.UpdateAvailableIndicator}"/>`
to
`+ Moniker="{x:Static catalog:KnownMonikers.StatusOK}" />`
https://github.com/NuGet/NuGet.Client/blob/595d508c578370c1b6ef31dbd636f434ac5b26f7/src/NuGet.Clients/NuGet.PackageManagement.UI/Xamls/PackageItemControl.xaml#L129

**Comment by andreinitescu** [comment]
After more thinking, my conclusion is... There should not be any icons! 

Usually, status icons are very useful, but in this particular context of the NuGet explorer, which is already a complex screen, I find the status icons over the package icons very distracting and they unnecessarily increase the overall complexity of the screen. 

For seeing the updates, there's already the "Updates" tab with the nice blue pill-like badge. Unfortunately, when you open the NuGet explorer, it takes an extra click to see what the Updates are, because it's a separate screen and it's not the default one. But let's leave this aside for the moment.

To see what I mean, compare the following two screenshots of the "Installed" screen, the current look and my suggested new look:

### Screenshot of the current look

![image](https://user-images.githubusercontent.com/743918/92299189-d94bb780-ef58-11ea-83d8-449126ec07b1.png)

Beside the confusing status icons, the stacked versions on the right side of every package item in the list is another issue.

### My mock-up of the new look

![image](https://user-images.githubusercontent.com/743918/92299202-f08aa500-ef58-11ea-867d-46b578adc05c.png)

Having no complicated overlay status icons and only show the current version numbers makes the "Installed" screen look like exactly what I think it's supposed to be: a **simple and clear list of your installed packages**.

### Another option for the new look

Another option I see for a better "Installed" screen is to add an "Update" button on those package items with an update available:

![image](https://user-images.githubusercontent.com/743918/92300091-cb019980-ef60-11ea-8f0a-3792393e6e71.png)

If having the "Update" button both on the package item in the list and in the package details panel on the right, might feel conflicting/confusing, there could only be only one button visible at a time depending on the selection of the list item:
- If the package in the list is **not selected**, the list item shows the "Update" button (like in my mock-up above)
- If the package in the list is **selected**, the list item does not show the "Update" button, because the package details panel on the right has the "Update" button for the selected package.

All these makes the "Updates" tab unnecessary. The blue badge showing the numbers of available updates would be displayed on the "Installed" tab item.

Also, in a similar way to how the app updates look on Android and iOS, the list could show first the packages which have updates. 

Not shown in my mock-up is the "Update" button at the top in order to update all packages. It would only appear if there's at least two updates available. 

I kept the same stacking of the current and update version numbers on the right when there's an update, but I think there might be a better way to show it than stacking them. Maybe something like just show the version of the update, or show "v12.0.2 ➡ v12.0.3" below the "Update" button.

**Comment by donnie-msft** [comment]
@andreinitescu I'll close this issue with https://github.com/NuGet/NuGet.Client/pull/3690 as it resolves the "old green tick" that this issue focuses on.
Your other comments, I've moved to #10071 - so please add further discussion there for the Refresh icon and removing indicators from the packages list. Thanks!
