### ISSUE TITLE
NuGet Visual Studio package fails to load to VS 2015 if NuGet.config is R/O

### ISSUE THREAD

**Issue by konste** [NuGet/Home#979]
When solution folder has subfolder ".nuget" with NuGet.config in there, if NuGet config is checked in to TFS and the file is read only, then attempt to load "Manage NuGet packages for Solution" causes error message about NuGet VS Package failing to load and ActivityLog.xml specifically points to NuGet.config being read only as the cause of the problem.

Obviously NuGet in VS should work normally when NuGet config is read only.

Konstantin

**Comment by emgarten** [comment]
Thanks for reporting this. The issue is being tracked under https://github.com/NuGet/Home/issues/868
