### ISSUE TITLE
`build\packages.targets` does not appear to run for all projects

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9790]
https://github.com/NuGet/NuGet.Client/pull/3449  included `PackageReference` items with a version, but the target that is supposed to fail the restore when versions are used in csproj did not fail 

https://github.com/NuGet/NuGet.Client/pull/3449/files#diff-802a1f72ef3d1349b83e7c33d4c4a2c0R25-R28

We should investigate and fix.

**Comment by teo-tsirpanis** [comment]
Why fail the build? The `SystemPackagesVersion` property is equal to `4.3.0`. Is there even a way to detect whether a package version was hardcoded or used from an MSBuild property?

**Comment by nkolev92** [comment]
We have a custom task to ensure that no versions are specified in the project files themselves. 

All the versions are specified in the packages.targets file, imported here https://github.com/NuGet/NuGet.Client/blob/2235bf9869c8fa4c7d441cc623f24cfd39bab621/build/common.targets#L63-L65, and then we run a target with that file not imported, and I expect that none of the PackageReference will have a version, https://github.com/NuGet/NuGet.Client/blob/2235bf9869c8fa4c7d441cc623f24cfd39bab621/build/build.proj#L329-L335.

**Comment by zivkan** [comment]
> Why fail the build?

To elaborate on why we we do as @nkolev92 wrote, to make sure that all projects are using the same version of all packages.

It's easiest to make sure you don't specify a version in the csproj, then let `packages.targets` update everything to set the correct version. Allowing versions to be specified in the csproj and then checking that it matches the desired version set in another file is much more difficult, and therefore not worth the effort.
