### ISSUE TITLE
dotnet list package suggests packages that are not compatible with the target framework

### ISSUE THREAD

**Issue by ghelyar** [NuGet/Home#9795]
NuGet product used:
dotnet cli

dotnet.exe --version:
3.1.301

Worked before? If so, with which NuGet version:
no

## Detailed repro steps so we can see the same problem

This can be reproduced with the [System.Management.Automation](https://www.nuget.org/packages/System.Management.Automation) package, which has an [unlisted version](https://www.nuget.org/packages/System.Management.Automation/6.1.7601.17515) that works on the full .net framework, although any package that has dropped support for an older framework in newer versions would work. The 6.x.x versions of this package target netcoreapp2.1 while 7.0.x target netcoreapp3.1, for example.

1. `dotnet new console`
2. change the target framework to net48
3. `dotnet add package System.Management.Automation -v 6.1.7601.17515`
4. `dotnet list package --outdated`

## Actual output:
The tool suggests upgrading to [7.0.2](https://www.nuget.org/packages/System.Management.Automation/7.0.2), which targets netcoreapp3.1, and is therefore not compatible with this project.
```
Project `...` has the following updates to its packages
   [net48]:
   Top-level Package                   Requested        Resolved         Latest
   > System.Management.Automation      6.1.7601.17515   6.1.7601.17515   7.0.2
```

## Expected output
The tool should suggest package versions that are compatible with the target framework.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/5725. 

list package does not do compatibility checks currently.

**Comment by nkolev92** [comment]
Merging this into https://github.com/NuGet/Home/issues/5725.
