### ISSUE TITLE
[Test Failure][Signing] No warning is showed in Error List when installing a signed package with packages.config format in PM UI

### ISSUE THREAD

**Issue by v-nancyj** [NuGet/Home#9798]
## Details about Problem

**NuGet Version:** Dev\5.8.0.6721
**VS Version:** Master\30314.159
**OS Version:** Windows-10-Enterprise-RS5

## Installation steps: 
1.	Install VS: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3891706&view=ms.vss-build-web.run-extensions-tab
2.	Install NuGet Client: [\\\ddfiles\Drops\NuGet\Drops\CI\NuGet.Client\Dev\5.8.0.6721\artifacts\VS15\NuGet.Tools.vsix](url)

## Repro steps: 
1. Create a .NET Framework package for testing.
2. Create a new test certificate: ` .\CreateTestCertificate.ps1 -AddAsTrustedRootAuthority`.
3. Sign a package: `NuGet.exe sign <PackageFilePath> -CertificatePath <PfxFilePath>`.
4.  Open Package Manager UI, Install the package into a project with ‘Package config’ format.

## Expected:
Warning NU3027 should be showed in Error list as below screenshot.
![bug71202](https://user-images.githubusercontent.com/20632775/87523356-6ab94e80-c6b9-11ea-8bd4-38d6c0663870.png)

## Actual:
No warning showed in Error List as below screenshot.
![0715](https://user-images.githubusercontent.com/20632775/87522276-fe8a1b00-c6b7-11ea-8322-3443ce213cb7.png)

## Notes: 
1. The issue didn’t repro on Master\30314.159 without installing the VSIX above.
2. The issue didn’t repro when installing package using command `NuGet install [package name]` in developer command prompt.

**Comment by heng-liu** [comment]
I could repro on version 5.8.0.6721 and 5.8.0.6718
The Ouput window from Package Manager has the NU3027 warning, but the Error List window doesn't show this warning.
```
Attempting to gather dependency information for package 'package1.1.0.0' with respect to project 'ClassLibrary5', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 919 ms
Attempting to resolve dependencies for package 'package1.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'package1.1.0.0'
Resolved actions to install package 'package1.1.0.0'
Adding package 'package1.1.0.0' to folder 'C:\Users\henli\source\repos\ClassLibrary5\packages'
NU3027: Package 'package1 1.0.0' from source 'C:\Users\henli\Desktop\package': The signature should be timestamped to enable long-term signature validity after the certificate has expired.
Added package 'package1.1.0.0' to folder 'C:\Users\henli\source\repos\ClassLibrary5\packages'
Added package 'package1.1.0.0' to 'packages.config'
Successfully installed 'package1 1.0.0' to ClassLibrary5
Executing nuget actions took 1.24 sec
Time Elapsed: 00:00:02.5621982
```

**Comment by heng-liu** [comment]
The regression is brought in between build 6705, 6706 and 6707.
As 6704 couldn't repro.

**Comment by heng-liu** [comment]
Tried to rerun 6705 and 6706, so it's 6707 breaks it.

**Comment by heng-liu** [comment]
Hi @srdjanjovcic, it looks like the regression is brought in by https://github.com/NuGet/NuGet.Client/pull/3484.
Can you take a look? Thanks.

Here is how to get the script CreateTestCertificate.ps1 used in repro steps:
Git clone https://github.com/NuGet/Entropy.git and cd to <path_to_Entropy>\TestCertGenerator

**Comment by srdjanjovcic** [comment]
@heng-liu I cannot get this script to work:

```
Export-PfxCertificate : Encryption failed. (Exception from HRESULT: 0x80090034)
```

Can you drop package and certificate into `\\ddfiles\team\xaml\srdjanj` ? Might be easier...

**Comment by v-nancyj** [comment]
@heng-liu The issue has been fixed on D16.7\30317.65 + NuGet Client release-5.7.x\5.7.0.6726 during our verification.
