### ISSUE TITLE
NuGet in VS 2015 ignores disableSourceControlIntegration config setting.

### ISSUE THREAD

**Issue by konste** [NuGet/Home#980]
When solution folder has subfolder ".nuget" with NuGet.config in there and config file contains
 <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>

NuGet still adds the files in the "packages" folder to source control, i.e. does not respect this setting anymore. 

Any workaround?

Thank you!
Konstantin

**Comment by emgarten** [comment]
@konste can you provide the contents of your nuget.config?

Does placing the nuget.config file the parent directory of your solution pick up the setting?

**Comment by konste** [comment]
For the repro I can use NuGet.config as trivial as this:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
</configuration>

Placing it to solution folder does not help to make  NuGet respect disableSourceControlIntegration setting. It still tries to check in new and updated packages in the "packages" folder.

**Comment by emgarten** [comment]
@konste the config XML looks invalid.  There is an extra "<config"

**Comment by konste** [comment]
It was just a side effect of me trying to figure out how to paste XML to Github markdown edit control. Actual config does not have this line and now I removed it from my previous answer also.

**Comment by emgarten** [comment]
Thanks @konste, we'll investigate.

**Comment by rbmanian75** [comment]
We are also having the same issue with Visual Studio 2015.

**Comment by NotMyself** [comment]
Just ran into this one as well. Short term fix is to simply undo the add in pending changes.

**Comment by dmccaffery** [comment]
Diddo; it seems to pend the change irrespective of the .tfignore which I always have. ... we should just all switch to git, me thinks. :)

**Comment by deepakaravindr** [comment]
@konste, Just to clarify. After updating the nuget.config to include the 'solution' section, Did you re-open or restart your solution in VS 2015?

**Comment by konste** [comment]
Nuget.config has solution section for the last year and was not changed. VS 2013 Update 4 was upgraded to VS 2015 and after that solution was reloaded and VS restarted many times - nuget behavior is persistent in that regard.

**Comment by deepakaravindr** [comment]
We will work on a fix. For the time being, there are 2 possible workarounds

* First one is to move nuget.config from the solution folder .nuget to the solution level and directory
* Second one is to undo the changes to the packages folder

**Comment by konste** [comment]
As far as I can tell after a few experiments, moving NuGet.config from .nuget folder to solution level does not change this behavior, so it is not really a workaround.

**Comment by Dreamwalker666** [comment]
I also just hit on this issue.  

I have updated from 3.0 to 3.1 in the last few days a regression maybe?  As I am sure it didn't happen on first install of 2015.

**Comment by peschuster** [comment]
@deepakaravindr I think this has nothing to do with the location of configuration files. As far as I can tell NuGet v3 does not even know the `disableSourceControlIntegration` configuration option, but it is still in the official docs and I would appreciate support for this option in VS 2015, too.

Here is a search through all repositories owned by NuGet for this term: https://github.com/search?l=&q=disableSourceControlIntegration+user%3ANuGet&ref=advsearch&type=Code&utf8=%E2%9C%93

**Comment by deepakaravindr** [comment]
Thanks for all the input! I will look into this as soon as I can.

@konste , you are right. First of my proposed workarounds above does not seem to work. Will look into this

**Comment by NotMyself** [comment]
thanks @deepakaravindr nice work.

**Comment by ilya-git** [comment]
Will we still need a solution folder with Nuget.Config in the new 3.2 release as a fix for this issue? Or will it be possible to set on a generic config level like that (not in the solution NuGet.Config):

```
<configuration>
  <config>
    <add key="repositorypath" value="Packages" />
    <add key="disableSourceControlIntegration" value="true" />
  </config>
</configuration>
```

That would be quite a useful option not to do this in each solution seems probably most don't need it in source control anyway...

**Comment by tengl** [comment]
> possible to set on a generic config level

I would like that too.

**Comment by deepakaravindr** [comment]
@ilya-git and @tengl,

You can add the setting not just to the solution level nuget.config, but also to your nuget.config at %appdata%\nuget. That works too! Just that it will get applied to every solution that you open on that machine. Remember to add the following section as a child to < configuration > section. And, note that the setting should always be under the < solution > section for it to work

``` xml
<solution>
    <add key="disableSourceControlIntegration" value="true" />
</solution>
```

Please let me know if you have any questions

**Comment by ilya-git** [comment]
I will try that, thank you. Will that work only in nuget 3.2? (I assume it's broken in 3.1?)

**Comment by deepakaravindr** [comment]
Yes, only on 3.2 and not on 3.1. Note that the pattern was always true. Except that it stopped working in 3.1 and now it is back to working again in 3.2

**Comment by NaomiN** [comment]
What should I do to fix the issue? Thanks in advance.

**Comment by deepakaravindr** [comment]
Please try the 3.2-RC VSIX which has been released. Check http://blog.nuget.org/20150902/nuget-3.2RC.html for more information

**Comment by NaomiN** [comment]
I am also having another problem described here https://social.msdn.microsoft.com/Forums/vstudio/en-US/d34b2a50-8f2e-42e7-b4ee-135edf75f82a/visual-studio-2015-scaffolding-is-not-working?forum=visualstudiogeneral

**Comment by deepakaravindr** [comment]
@NaomiN, Could you please open a different issue for this?

Please provide the repro steps alongwith the full version of VS 2015 you are using and the version of NuGet Package Manager extension

**Comment by NaomiN** [comment]
I added the issue description on MS Connect https://connect.microsoft.com/VisualStudio/feedbackdetail/view/1798314/scaffolding-no-longer-working

I am using VS 2015 Enterprise and the latest NuGet package

**Comment by NaomiN** [comment]
Ok, it looks like I don't really have that problem and it was the separate bug that caused the controller's Init method to not fire. The bug is related with out current DateTime Picker directive that sets dirty state.

**Comment by NaomiN** [comment]
Oops, sorry, wrong issue.

**Comment by Liero** [comment]
I'm using VS2015+NuGet 30.2.60914, but when I restore packages, the the files appears Team Explorer\Pending Changes\Excluded Files\Detected as added files.

``` xml
<configuration>
    <solution>
        <add key="disableSourceControlIntegration" value="true" />
        <add key="repositorypath" value="../Packages" />
    </solution>
</configuration>
```

**Comment by TwelveBaud** [comment]
@Liero: That behavior is expected. NuGet isn't adding the files to TFS at all, which is why they're not showing up in Included Files or Excluded Files and won't be checked in. Instead. Visual Studio itself is letting you know "hey, there are files here..." Add a `.tfignore` or `.gitignore` file if you want them to disappear from Candidate Changes too; there are options on the right-click menu to do this.

**Comment by breyed** [comment]
Related issue on MS connect: [NuGet adds packages to TFS despite .tfignore (1640242)](https://connect.microsoft.com/VisualStudio/feedback/details/1640242)

**Comment by MedAnd** [comment]
:+1: 

Neither the NuGet.config or the .tfignore methods worked to exclude the nuget packages folder from being included in all Pending Changes... 

Microsoft Visual Studio Enterprise 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

**Comment by nathan-alden-sr** [comment]
Still broken as of April 26. The .nuget folder under the folder containing the .sln file seems to be completely ignored.

**Comment by harikmenon** [comment]
I just tried this on my end and I cant seem to repro it. This is on Visual Studio 2015 + Update 2 with 3.4.3v of NuGet Package Manager which is the latest RTM combination.
1. Created a WPF app and added it to TFS source control
2. Added a package to the WPF app
3. Looked at pending changes and I could see the packages folder in it
4. Add a NuGet.config to a .nuget folder with the disableSourceControlIntegration set to true
5. Restarted VS
6. Added a new package to the WPF app
7. Checked pending changes and I could see that the new package did not show up there (the first package is still visible)

If this still repro's in this combination for you @nathan-alden @MedAnd, can you send me a small repro solution or atleast the folder hierarchy where you have the packages folder and nuget.config and copies of the nuget.config in %AppData%/NuGet/nuget.config and the nuget.config in your solution - you can either respond here or mail me at harikm@microsoft.com.

Also, if you can repro this in the above combination or in NuGet 3.4.3, please open a new issue and link this issue as reference to it.

**Comment by RobBowman** [comment]
Thanks harikm, I found your detailed steps very helpful. One thing I would add, to create the ".nuget" folder in windows explorer, you have to type the name ".nuget."
