### ISSUE TITLE
Ordered solution load and impact on NuGet restore performance

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9801]
NuGet PackageReference is transitive and as such additional information in children projects will affect the restore of the project being restored. 

Say we have a large solution among which the projects are:  A => B => C. 

Say the nominations come in the following order: A, B, then C.

If Nuget decides to restore after A & B have been nominated, whenever C gets nominated again, we run a sln restore, we'll need to invalidate A & B's restores and performance a full restore again. 

If the nominations come in the correct order, C => B=> A, no restore will be wasted.

**Comment by erdembayar** [comment]
If we ever need to do this on our side instead of  expecting Project system to give nomination in correct order then I can take it. Of course it may not be perfect  but we can give try sometime in the future.

**Comment by nkolev92** [comment]
Not a consideration at this point. 
Closing this issue for now. 

The focus is on running as few restores as possible.
