### ISSUE TITLE
[Bug Bash][Test Failure] The packages in "Updates" tab showed incorrectly after switching tabs quickly

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9804]
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6721
VS Version: Master\30315.165
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Create an ASP.Net Web Application (.NET Framework)-MVC solution in VS.
2.	Open the PM UI of the project level (or solution level) and go to the “Updates” tab.
3.	Switch between all the tabs quickly and go back to the “Updates” tab.
## Expected
There are 5 packages available to update.
## Actual
There are only 3 packages available to update instead of 5 as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/87653046-90ad2480-c787-11ea-82a6-06fcfe508f2d.png)
## Note
1.	It doesn’t repro when switching tabs slowly.
2.	It is a regression bug, it started to repro from \\ddfiles\drops\NuGet\Drops\CI\NuGet.Client\dev-donnie-msft-pmuiTabSwitchUIFiltering\5.7.0.11466 base on our verification.

**Comment by donnie-msft** [comment]
I've identified this as a background loading problem. I'll need to find a way of having the tab wait until all Latest Versions are completed loading, or reload the tab if the previous load is interrupted.

**Comment by donnie-msft** [comment]
Another problem that's related:

After updating package "EntityFramework" to latest, then update other packages by selecting all packages, failed with error: "Object reference not set to an instance of object."
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1160376

**Comment by donnie-msft** [comment]
Developer community: https://developercommunity2.visualstudio.com/t/Nuget-does-not-show-all-the-updates/1256924

**Comment by v-luzh** [comment]
It is fixed, base on the verification on Main\31108.185 + NuGet Client Dev\5.10.0.7157. Close it now, thanks.
