### ISSUE TITLE
Running NuGet.Client's build script on PowerShell Core raises an error

### ISSUE THREAD

**Issue by teo-tsirpanis** [NuGet/Home#9805]
## Details about Problem

NuGet product used: https://github.com/NuGet/NuGet.Client

NuGet version: `dev` branch

dotnet.exe --version (if appropriate): N/A

VS version (if appropriate): N/A

OS version (i.e. win10 v1607 (14393.321)): Windows 10 2004

Worked before? No

## Detailed repro steps so we can see the same problem

1. Clone the `NuGet.Client` repository.

2. Launch a `pwsh` shell in the repository's directory.

3. `.\build.ps1`

4. An error is displayed but building continues normally.

### Verbose Logs

```
MethodInvocationException: C:\Users\teots\code\NuGet.Client\build\common.ps1:19
Line |
  19 |  if ($PSVersionTable.PSVersion.CompareTo($Version) -lt 0) {
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "CompareTo" with "1" argument(s): "Cannot process argument because the value of
     | argument "version" is not valid. Change the value of the "version" argument and run the operation
     | again."
```

**Comment by nkolev92** [comment]
Thanks for filing this @teo-tsirpanis 
Dup of https://github.com/NuGet/Home/issues/9673
