### ISSUE TITLE
Speed up nupkg extraction using mmap/CreateFileMapping

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9807]
I was playing around with tarball extraction in Rust, trying to speed it up, when someone suggested using [`mmap`](https://en.wikipedia.org/wiki/Mmap) for the destination files before writing to them (Windows version is [`CreateFileMapping`](https://docs.microsoft.com/en-us/windows/win32/memory/creating-a-file-mapping-object)). This resulted in a 4-5x speedup of a 7.5mb tarball containing 65k files -- going from 17-22s extraction times to a mere 3.5-4.5s.

I believe it's worth exploring doing this ourselves for .nupkg extraction during Restore -- it's unclear whether the extraction benefit is mainly for many small files, or whether fewer large files can still take advantage of this, but it's worth a shot anyway, for that kind of improvement!

**Comment by nkolev92** [comment]
Tip for the implementer, use https://github.com/NuGet/NuGet.Client/tree/dev/scripts/perftests to validate the impact in a real restore :)
