### ISSUE TITLE
Create VS API: GetSourcesAsync

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9811]
Request from https://github.com/dotnet/roslyn/pull/46022/files#r456003371

Currently Roslyn calls `IVsPackageSourceProvider.GetSources`, which gets the sources for the current solution. I don't believe it takes into account additional sources that can be set for PackageReference projects. Therefore, we should consider if the new API is in `INuGetProjectService` and start returning per-project sources, or create a new `INuGetSolutionService` for a more equivalent API.

**Comment by nkolev92** [comment]
Is this ask covered by https://github.com/NuGet/Home/issues/8902?
