### ISSUE TITLE
Proposal: VS API to be notified when a restore completes

### ISSUE THREAD

**Issue by zivkan** [NuGet/Home#9813]
Probably should only fire when the restore was not a noop.

Request from the live unit testing team in order to be able to reliable and efficiently locate test adapters.

A use-case for wanting this information is to know when packages may have changed. Therefore, if https://github.com/NuGet/Home/issues/6872 is not implemented, then this API needs to fire when a restore happens during package install and uninstall.

**Comment by nkolev92** [comment]
Related to https://github.com/NuGet/Home/issues/9782. 

The asks are very similar. The project system *wants* to know when assets file writes are happening.

**Comment by nkolev92** [comment]
This is done. https://github.com/NuGet/Home/issues/9782

https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivsnugetprojectupdateevents-interface
