### ISSUE TITLE
Port static graph restore to NuGet.exe

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9824]
Along that, consider where moving nuget.exe to servergc is a good idea. 
This *could* become separate tasks, but I'll leave that to implementer :)

**Comment by nkolev92** [comment]
@jeffkl Just looking at static graph epic, do we still want/need this? IMO, it might be ok to just close, given that we now have the `RestorePackagesConfig` property as well.

**Comment by nkolev92** [comment]
While doing the tech debt analysis, I think at this point we don't need to port static graph to NuGet.exe, instead move customers to msbuild.exe where appropriate. 

@jeffkl Feel free to reopen if you disagree.

**Comment by jeffkl** [comment]
@nkolev92 I agree, I was just discussing with @martinrrm recently about just closing this.  Thanks for taking care of it.
