### ISSUE TITLE
Allow to user to input custom (floating) versions through the PM UI

### ISSUE THREAD

**Issue by martinrrm** [NuGet/Home#9829]
Change version input to a Combo Box displaying available version depending on the user input. This will allow users to select a floating version to install.

**Comment by donnie-msft** [comment]
Draft PR needs to be shepherded: https://github.com/NuGet/NuGet.Client/pull/3595

**Comment by kartheekp-ms** [comment]
@martinrrm - I think we should reopen the issue because the commit was reverted. Hope you are okay with that. Please let me know if I am missing any context.

**Comment by martinrrm** [comment]
Reopening because the changes were reverted and will be merged later in 17.2

**Comment by zivkan** [comment]
Reopening since this was reverted.
