### ISSUE TITLE
Progress bar is beyond useless when updating or installing packages from the Package Manager

### ISSUE THREAD

**Issue by jimmyheaddon** [NuGet/Home#983]
The progress bar just pulsates left-to-right and is completely redundant beyond telling you that *something* is happening.  Surely we can infer the progress steps available given the number of target projects and the number of files/assemblies?

Having a reliable progress bar would be infinitely helpful when performing solution wide updates to multiple packages (e.g. clicking 'Update All'), and doesn't appear insurmountable?

Cheers!

**Comment by emgarten** [comment]
@jimmyheaddon would you provide a few more details on your environment?

* What version of Visual Studio are you using?
* What version of NuGet do you have installed?
* Repro steps

**Comment by jimmyheaddon** [comment]
Certainly, this is with this weeks version of NuGet installed (but has always happened) when using either Visual Studio 2010 Ultimate or Visual Studio 2013 Ultimate on Windows 7 Ultimate x64.

At any point if I attempt to update multiple packages at once (in a single project or across an entire solution, e.g. 100+ projects) then you get the updating dialog with the rolling log messages, but the progress bar just strobes side-to-side, it doesn't progress from 0 to 100 at any point.

I'm pretty sure the progress bar state is 'Indeterminate', see here - http://www.wpf-tutorial.com/chapters/misc-controls/images/progressbar_indeterminate.png


Cheers

**Comment by emgarten** [comment]
This has been improved in NuGet 3.0.0 for Visual Studio 2015.  In NuGet 2.8.6 packages are installed/updated as they are discovered, the full list of packages needed to find out how far along the operation has progressed is not known until everything is complete.
