### ISSUE TITLE
NuGet should not infer dots platform version when parsing TargetFramework

### ISSUE THREAD

**Issue by dsplaisted** [NuGet/Home#9842]
Use NuGet to parse the following `TargetFramework`: `net5.0-android21`

**Expected:** Parsed `TargetFrameworkVersion` is `21` (or `21.0`, etc)

**Actual:** Parsed `TargetFrameworkVersion` is `2.1`

NuGet is probably using the same version parsing logic for the platform version as it does for the target framework version.  However, the target framework version parsing automatically inserts version separators, so that, for example, net451 parses to .NET Framework 4.5.1.

We (probably) can't change how the parsing works for the target framework for compatibility reasons (though we probably want to disallow `net50` in favor of `net5.0`, and eventually should consider what to do with `net10`).  But we shouldn't bring this logic forward to the platform versions.

**Comment by nkolev92** [comment]
This should be pretty straightforward.
fyi @zkat
