### ISSUE TITLE
Cleaning up old binding redirects

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9857]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1092773/cleaning-up-old-binding-redirects.html)._

---
Over time the config files of my solution got a lot of obsolete binding redirects. To clean them up I had to manually remove the existing redirects and then run on the nuget powershell the command Add-BindingRedirect

wanting to automate the process for all my projects in the solution, I found the code here very helpful
https://martowen.com/2018/09/12/refreshing-net-assembly-binding-redirects-in-a-visual-studio-solution/

Please add to the nuget powershell a command like Remove-BindingRedirect in the URL above so this can be done within VS built-in commands and not rely on 3rd party code

Another option would be to enhance the Add-BindingRedirect command with a parameter that will instruct it to remove all existing redirects before executing

---
#### Feedback Bot on 6/27/2020, 11:52 PM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.

**Comment by anangaur** [comment]
Related: https://github.com/NuGet/Home/issues/9706

**Comment by nkolev92** [comment]
Thank you for filling this issue, coalescing into https://github.com/NuGet/Home/issues/6870. 
Expanding the scope into adding a Remove-BindingRedirect command similar to this ask.

**Comment by vbjay** [comment]
```powershell
function Remove-BindingRedirects {
  $redirects = Get-ChildItem . -Recurse -File -Filter web.config | Select-Xml -XPath '//configuration/runtime/x:assemblyBinding' -Namespace @{ x = "urn:schemas-microsoft-com:asm.v1" }
  $redirects | % {
    $doc = $_.Node.OwnerDocument
    $node = $_.Node
    $node.ParentNode.RemoveChild($node)
    $doc.Save($_.Path)
  }

}
```
Rough function that you can parameterize and do exactly what is needed to remove the redirects and then di the next step.  Adjust what config files are processed as needed.
