### ISSUE TITLE
Nuget pack issue

### ISSUE THREAD

**Issue by DhanvannthVP** [NuGet/Home#9859]
Remove the content above here and fill out details below.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Nuget.exe

NuGet version (x.x.x.xxx): 5.5

dotnet.exe --version (if appropriate):

VS version (if appropriate):

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

When i tried to use nuget pack -ConfigFile "Nuget.config" ABC.sln -Prop Configuration=Release -Symbols 
It s including src folder inside nupkg file. I dont need to exclude the src folder. Is there anything i need to do with Nuget.config file. Kindly advise

2.

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zkat** [comment]
Hi there! Is this what you're looking for? https://docs.microsoft.com/en-us/nuget/reference/nuspec#using-the-files-element-for-content-files

**Comment by donnie-msft** [comment]
⏰ @DhanvannthVP Could you let us know if the document above answered your question?

**Comment by DhanvannthVP** [comment]
symbols.nupkg has src folder. After making it as false, got only one nupkg without src folder
