### ISSUE TITLE
[Test Failure] VS gave a wrong constraint warning when there are no package constraint in the packages.config file after updating packages 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9860]
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6753
VS Version: Master\30328.112
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1.	Open VS, click “Create a new project” button and search template “ASP.NET Web Site (Razor v3)” in the filter.
2.	Create the project, open the PM UI of the project and go to the “Updates” tab.
3.	Check “select all packages” and click “Update” button.
4.	Build the project.
## Expected
There is no warning.
## Actual
There is a wrong constraint warning since there are no package constraint in the packages.config file as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/88785603-feb00d80-d1c3-11ea-8100-f983c7f91f5b.png)
## Note
1.	It didn’t repro on D16.7\30323.103 with Implicit NuGet Client Release-5.7.x\5.7.0.6726.
2.     It started to repro from NuGet Client build Dev\5.8.0.6741.

**Comment by aortiz-msft** [comment]
6741 has two new commits compared to 6739 where the bug does not repro. These commits are https://github.com/NuGet/NuGet.Client/commit/e09b536dbcddbb193fd1f81028b66330bc7f5513 and https://github.com/NuGet/NuGet.Client/commit/cce84224f4e0c0959781ff6f13d50ecf092375c1.

**Comment by srdjanjovcic** [comment]
@v-luzh, can you provide more about repro? Is this Razor v3 template part of Visual Studio, or is it installed separately? I cannot find it.

EDIT: Never mind. I found it, it is in optional component "Legacy ASP.NET templates"

**Comment by srdjanjovcic** [comment]
Warning message:

> One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'DotNetOpenAuth.Core 4.3.4.13329 constraint: Microsoft.Net.Http ', 'WebGrease 1.6.0 constraint: Antlr (>= 3.4.1.9004)', 'WebGrease 1.6.0 constraint: Newtonsoft.Json (>= 5.0.4)'

…exists in Package Manager Output window pane _both_ before and after my change. It seems that, at most, I fixed a bug where warning was not displayed properly.

**Comment by nkolev92** [comment]
Does the warning get cleared when you run restore?
If it does, then it might be good.

**Comment by srdjanjovcic** [comment]
This is by design. My change fixed logging of warnings/errors to error list. Many places in code didn't log them properly.
