### ISSUE TITLE
Dependency Resolution Inconsistency

### ISSUE THREAD

**Issue by tyb-dev** [NuGet/Home#9861]
Expected: NuGet uses a nearest-wins approach to resolve conflicting dependencies. NuGet does not try to find a dependency that meets all constraints in the graph. That means, the dependency that is closer to the application in the dependency graph wins.
Actual: In the case below, this rule is violated. 

## Details about Problem

VS version (if appropriate):
2019

OS version:
Windows 10, 2004

Worked before? If so, with which NuGet version:
No

dotnet version:
3.1

## Detailed repro steps so we can see the same problem

Let's assume we have 2 packages, C, and D. D comes in two versions and C takes a dependency on D. 
D 1.0.0
C 1.0.0 -> D 2.0.0

Let us construct an app that results in a classic package downgrade, by referencing both C an D:
- App
  - C 1.0.0
    - D 1.0.0
  - D 1.0.0

```
Detected package downgrade D from 2.0.0 to 1.0.0
  App -> C 1.0.0 -> D (>= 2.0.0)
  App -> D (>= 1.0.0)
```

Let us introduce two new dependencies, which we put in front of C and D:
A 1.0.0 -> C 1.0.0
B 1.0.0 -> D 1.0.0

We can now construct a new App that is identical to the first app, except the dependencies C and D are shifted down by one level. All we did is add a new first layer. The nearest wins rule should still hold, but we get the following instead:

- App
  - A 1.0.0
    - C 1.0.0
      - D 2.0.0 (! this version is farther away but wins)
  - B 1.0.0
    - D 2.0.0 (! package upgrade from 1.0.0 to 2.0.0, although it is closer to App)

There is no package downgrade error. Instead, D is promoted to 2.0.0. 

Screenshot:
![pic](https://user-images.githubusercontent.com/57002348/88896242-e1258700-d249-11ea-9cb9-c307eaf5b8d6.png)

Repro:
[repro.zip](https://github.com/NuGet/Home/files/4999978/repro.zip)

Documentation:
https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution

**Comment by tyb-dev** [comment]
Can anyone point me to the implementation of this logic? Is this actually implemented somewhere else in MSBuild Static Graph Restore?

**Comment by zivkan** [comment]
Our PackageReference dependency resolver is here: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.DependencyResolver.Core

Note however that the "nearest wins" name is misleading. I believe it's really "direct dependencies override", but if a package is only selected by transitive dependencies, then it will try to meet all version range requirements.

Even if you find how to change the dependency resolver to be truely nearest wins, this will be a breaking change and therefore I don't believe we would be able to accept it as it would change the resolved graph depending on which version of NuGet they're using.

Before spending time making changes and creating a pull request, please explain what it is you intend on changing and why. In this case, I think it is better to change our documentation, not the product.

**Comment by tyb-dev** [comment]
I agree if this changes, you'll have all sorts of trouble even for simple projects using just System packages. At this point, I'm just trying to understand how it works to resolve package downgrade warnings and I could not understand some cases. An accurate documentation would be phenomenal.

**Comment by tyb-dev** [comment]
Based on the implementation, a package becomes downgraded if and only if any of its ancestor has a direct child with a lower version of the same package. Here's a visualization of that: 

 - App
   - TEST (>= 1.0.0) -> ❗ **Downgrade Warning**
   - A_1
     - TEST (>= 1.0.0) -> ❗ **Downgrade Warning**
     - A_1_1
       - TEST (>= 1.0.0) -> ❗ **Downgrade Warning**
       - A_1_1_1
         - TEST (>= 2.0.0) -> ▶ Here's the package that can become downgraded
         - A_1_1_1_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_1_1_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_1_1_2
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_1_2_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_1_2_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
     - A_1_2
       - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_1_2_1
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_2_1_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_2_1_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_1_2_2
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_2_2_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_1_2_2_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
   - A_2
     - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
     - A_2_1
       - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_2_1_1
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_1_1_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_1_1_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_2_1_2
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_1_2_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_1_2_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
     - A_2_2
       - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_2_2_1
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_2_1_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_2_1_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
       - A_2_2_2
         - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_2_2_1
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning
         - A_2_2_2_2
           - TEST (>= 1.0.0) -> ✔️ No Downgrade Warning

**Comment by nkolev92** [comment]
Hey @tyb-dev, you can refer to this related thread, specifically this comment: https://github.com/NuGet/Home/issues/5400#issuecomment-353762585

Your graph along side the comment I linked are a great description of what happens. 

Personally I think of the downgrade scenarios as the following ones:

* To get a downgrade, actively downgrade a package by requesting lower version of any package in the graph as a direct dependency
* Any package that ignored the above will cause an NU1605. 

It's because of this that NU1605s are elevated to an error by default in SDK based projects. 
The current algorithm logic also makes the resolution predictable. 
When an assembly is built using a downgraded version of a package, it is built against older assemblies. It ignored the asks of it's dependencies. The current algorithm replicates the resolution behavior when that project becomes a package and is installed in a different project.

**Comment by nkolev92** [comment]
Thank you for doing this investigation and raising this topic. 

I'll mark this issue as a docs issue. I'll try to add some more examples that hopefully will provide more clarity.
