### ISSUE TITLE
Bad UX to get to NuGet from the "Manage NuGet Packages" screen

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9866]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1126396/bad-ux-to-get-to-nuget-from-the-manage-nuget-packa.html)._

---
Right-click a csproj project, select "Manage NuGet Packages...", the familiar screen appears for managing packages.

Let's say you want to visit a package's page on NuGet for some additional information so you start quickly visually scanning your screen for any nuget links. The one that you'll spot first is **the Report Abuse link**, that you can then use to further navigate back to the package's page. In my case the situation is extra bad because the ReportAbuse part is wrapped to the next line.

---
#### Feedback Bot on 7/27/2020, 07:20 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Leftyx on 7/28/2020, 01:13 AM: 

<p>eh eh. I always do that.</p><p>The "Report abuse" is the most clicked url on the web, especially cause most packages don't have the link to the nuget packages, just the report abuse page.</p>

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Possible with nuget.org source packages
