### ISSUE TITLE
Restore.csproj failed to build while running dotnet tool install dotnet-ef

### ISSUE THREAD

**Issue by eza-impactcommerce** [NuGet/Home#9876]
I had ef 3.0.0 and advised to update to 3.1.0. Direct update failed so I uninstalled ef from dotnet tool and tried to reinstall it again. I got error while building a restore project in path like this: [/var/folders/gt/9l4q1djd12d__wt0cxkqyrc80000gn/T/gkjf01jk.whw/restore.csproj]
I passed verbosity option for detailed (--v d) with install command and it seems there is exception at NuGet.Protocol.ServiceIndexResourceV3Provider.GetServiceIndexResourceV3(SourceRepository source, DateTime utcNow, ILogger log, CancellationToken token)
I am not sure this is an actual bug or this is a problem with my environment. I am running on macos 10.15.6 and dotnet 3.1.302. This is happened also if I downgrade to dotnet 3.1.100.
<img width="987" alt="89300923-df502f00-d660-11ea-9185-802f753ab76f" src="https://user-images.githubusercontent.com/20289652/89434174-24489400-d73b-11ea-9b8d-0c571d41cb99.png">
<img width="1421" alt="89300937-e414e300-d660-11ea-90c5-4d8471e0855d" src="https://user-images.githubusercontent.com/20289652/89434193-290d4800-d73b-11ea-92db-4ee819e55587.png">
<img width="1421" alt="Screen Shot 2020-08-05 at 13 46 52" src="https://user-images.githubusercontent.com/20289652/89434195-2a3e7500-d73b-11ea-9342-d699a5b25776.png">

**Comment by aortiz-msft** [comment]
@v-luzh - Would you please try to repro?

**Comment by eza-impactcommerce** [comment]
@aortiz-msft not sure what do you mean. but this is has nothing with specific project. It's CLI problem.

**Comment by eza-impactcommerce** [comment]
Well I uninstalled again all SDKs/Runtimes all over using uninstalling tool. Also, I chased every singled dotnet/nuget folder and files and removed them manually. Installed everything again and now it works.
