### ISSUE TITLE
Managed NuGet Package designer doesn't let you cut from the search field

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#9877]
# Version

: Version 16.8.0 Preview 2.0 [30404.163.master]

# Repro

1. Highlight the text and press CTRL+X in the search box for this designer:

![image](https://user-images.githubusercontent.com/1103906/89485368-fbc8a480-d7e3-11ea-83d3-4bc1a4f9991e.png)

Expected: For the text to be cut
Actual: Nothing

**Comment by aortiz-msft** [comment]
@davkean  - Cannot repro the issue. Any additional repro steps?

**Comment by davkean** [comment]
What build are you on? This is 100% repro for me. The following shows it:

![CtrlX](https://user-images.githubusercontent.com/1103906/89592542-312acc00-d890-11ea-8369-d9c773b4f216.gif)

**Comment by davkean** [comment]
Pressed CTRL+X about 5 times in a row.

**Comment by davkean** [comment]
I'm hitting this on every single machine I have @aortiz-msft can you please reopen?

**Comment by davkean** [comment]
@aortiz-msft Can you try this instead, Edit -> Cut? It looks like in some circumstances VS command routing is picking up the CTRL+X instead of WPF. I've not figured out the trigger.
