### ISSUE TITLE
NuGet.CommandLine - packing a project file uses first .nuspec file in the project directory when multiple nuspecs exist.

### ISSUE THREAD

**Issue by dmccaffery** [NuGet/Home#988]
Consider the following project structure:

./MyCompany.MyProject/
|__ MyCompany.MyProject.csproj
|__ MyCompany.MyProject.nuspec  (tokenized nuspec)
|__ A.nuspec (manually composed)

In previous versions of the CLI, executing the following command would use the expected tokenized nuspec:

nuget pack MyCompany.MyProject.csproj

In NuGet 2.8.6 (and maybe older builds), NuGet seems to locate the first nuspec it finds in alphabetical order, rather than relying on the specification being named the same as the project name.

This results in the A.nuspec (which doesn't even rely on the build output of the csproj) being used instead of the expected MyCompany.MyProject.nuspec that is tokenized.

I can see the reasoning for doing this, it makes it less likely for a pack to fail if a typo exists, or the project is renamed without renaming the nuspec.

I recommend requiring an exact match of the name of the nuspec whenever more than one nuspec exists in the project path. In this way, if only one nuspec exists, it can be called whatever you want and it will "just work"; otherwise, it is impossible to determine which one of the nuspec files is the right one to use.

**Comment by emgarten** [comment]
In which version(s) of nuget.exe have you seen this work?

**Comment by dmccaffery** [comment]
Upon further investigation, I know why I thought it used to work. The following code eludes to the reasoning:

````C#
 private IEnumerable<string> GetNuspecPaths()
        {
            // Check for a nuspec in the project file
            yield return GetContentOrNone(file => Path.GetExtension(file).Equals(Constants.ManifestExtension, StringComparison.OrdinalIgnoreCase));
            // Check for a nuspec named after the project
            yield return Path.Combine(_project.DirectoryPath, Path.GetFileNameWithoutExtension(_project.FullPath) + Constants.ManifestExtension);
        }
````
It scans the project file to look for <none> and <content> nodes and cherry-picks the first one that ends with the .nuspec extension. I always add the .nuspec files to the project because TVFC is a nightmare when it comes to tracking files that aren't in the projects (and I haven't convinced my employer to use git, just yet).

Apparently, I've been lucky thus far in that the nuspec I want to execute happened to be found first when walking the project nodes -- until now.

It's still an issue, I think, in that it shouldn't cherry pick the first one ... could be fixed temporarily by inversing the yields as the code that calls the GetNuSpecPaths() method simply returns FirstOrDefault(File.Exists). This means that any nuspec matching the project name would take first priority over those included in the project file.

IMHO, this should fail if there are more than one NuSpecs found and one of them doesn't match the project name, though, as its definitely hit or miss in cherry-picking the right one otherwise.

**Comment by emgarten** [comment]
Thanks for the investigation, we will take a look at how this can be improved in a later release without breaking back compat.

**Comment by dmccaffery** [comment]
No worries. It's an easy thing to work around; didn't realize in the past how this actually worked.

For what it's worth, I don't think backward compatibility is a concern with regard to throwing an error if multiple NuSpecs are found -- if it's working for folks right now, they are winning the lottery, so to speak -- it's probably better than finding out the hard way some day like I did. lol
