### ISSUE TITLE
Package Manager Console Depends on Solution Start-up Project

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9880]
@BrianBu01 commented on [Tue, 03 Mar 2020 18:27:14 GMT](https://github.com/dotnet/roslyn/issues/42137)
**Version Used**: 

VS Professional 2019 v 16.4.5

**Steps to Reproduce**:

1. Select a start up project
2. In Package Manager Console, select a default project different from startup
3. Run a command that depends on building of projects or even code with in such as Scaffold-DbContext.

**Expected Behavior**:

The command runs in context of the default project

**Actual Behavior**:

The command run on the default project but in the context of the start-up project
**Notes**

Not really sure that this is a bug, but it is a confusing coupling between two different concepts.

**Comment by nkolev92** [comment]
@jinujoseph commented on [Thu, 05 Mar 2020 00:21:09 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-594959545)
Triage reroute : @davkean is this project system or nuget packge team

**Comment by nkolev92** [comment]
@BrianBu01 commented on [Thu, 06 Aug 2020 19:31:35 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670150471)
@davkean Do you have a reference to the ticket in project system or nuget package team?

**Comment by nkolev92** [comment]
@davkean commented on [Fri, 07 Aug 2020 00:11:27 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670251610)
This is not project system, and I'm not aware of how this is supposed to work.

**Comment by nkolev92** [comment]
@BrianBu01 commented on [Fri, 07 Aug 2020 00:27:32 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670255749)
@jinujoseph maybe you have a suggestion.

I'd assume Package Manager commands should run in the context of the default project not the startup project would be a solution.

**Comment by nkolev92** [comment]
@davkean commented on [Fri, 07 Aug 2020 00:32:21 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670256981)
@BrianBu01 

http://github.com/nuget/home would be a better place for this issue, I'd move it but we cannot move across organizations.

**Comment by nkolev92** [comment]
@jinujoseph commented on [Fri, 07 Aug 2020 00:35:03 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670257681)
cc @nkolev92 from nuget team to take a look

**Comment by nkolev92** [comment]
@BrianBu01 commented on [Fri, 07 Aug 2020 00:36:38 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670258141)
@davkean I'm confused.  How does Nuget itself have anything to do with the Package Manager in Visual Studio and the context of the solution's startup project?

It's really an integration issue.

**Comment by nkolev92** [comment]
@davkean commented on [Fri, 07 Aug 2020 00:38:59 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670258731)
The Package Manager is owned and lives in https://github.com/NuGet/NuGet.Client and bugs are tracked at https://github.com/NuGet/home.

**Comment by nkolev92** [comment]
@nkolev92 commented on [Fri, 07 Aug 2020 00:43:06 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670259673)
I can move the issue, but I don't have permissions to close this one.

**Comment by nkolev92** [comment]
@jinujoseph commented on [Fri, 07 Aug 2020 00:44:09 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670259921)
I can close this once you have a tracking issue your end @nkolev92

**Comment by nkolev92** [comment]
@BrianBu01 commented on [Fri, 07 Aug 2020 00:53:17 GMT](https://github.com/dotnet/roslyn/issues/42137#issuecomment-670261846)
@nkolev92 can you please provide the new issue, so I can follow it?

**Comment by zkat** [comment]
@v-luzh Could you try and repro this?

**Comment by zivkan** [comment]
This is not a NuGet bug. Running our [`Get-Project`](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.PackageManagement.PowerShellCmdlets/Cmdlets/GetProjectCommand.cs) command without any arguments will get PMC's default project. However, EF6's PowerShell module is [implemented explicitly to get the solution's startup project](https://github.com/dotnet/ef6/blob/04a6ae5556f38fb3ba622dcb142a6c6b37101dd9/src/EntityFramework.NuGet/tools/EntityFramework6.psm1#L689) instead.

This feedback should be redirected to the EF6 team instead.

**Comment by aortiz-msft** [comment]
@zivkan - Should we move this issue to the dotnet project then?

**Comment by zivkan** [comment]
I created this issue on the EF6 repo: https://github.com/dotnet/ef6/issues/1750
