### ISSUE TITLE
NuGet Package Update Automation

### ISSUE THREAD

**Issue by zpep92** [NuGet/Home#9888]
I am facing an issue with automating NuGet package update operations.  These commands had leveraged the NuGet.Core library for automating the process of applying NuGet updates to project files, but that library looks to have long since been deprecated.  

There is an issue with upgrading netstandard2.0 packages within a project (TargetFrameworkVersion 4.7.2). The debug message flow from PackageManager is:

-----------------------------------------------
> Looking for updates for 'MYPACKAGE'...

> Updating 'MYPACKAGE' from version 'x.y.z' to 'a.b.c' in project 'MYPROJECT'.

> Removing 'MYPACKAGE x.y.z' from MYPROJECT.

> Added file 'packages.config'.
> Successfully removed 'MYPACKAGE x.y.z' from MYPROJECT.

> Adding 'MYPACKAGE a.b.c' to MYPROJECT.
-----------------------------------------------
At which point a "MYPROJECT does not reference 'MYPACKAGE'" error is thrown.

The project is still using packages.config file to manage its NuGet package references.  NuGet packages are used to split and package code from various modules which are consumed by an application project.  An automated process in Azure DevOps pipelines is used to update those packages and push out to a CI environment for testing.

I have looked at the following scenarios unsuccessfully on how to upgrade our process to support newer netstandard2.0 packages:

-----------------------------------------------
01: Update NuGet.Core version
-> Library is deprecated, no newer version to upgrade to

02: NuGet.exe version update (to version 5.6.0)
-> NuGet version update has no effect on underlying NuGet.Core code

03: Leverage built-in NuGet supported tasks within Azure DevOps
-> NuGet.exe CLI does not support our necessary functions
    -> .csproj file is not updated with assembly references
    -> Files contained within NuGet packages are not updated/extracted as anticipated

04: Leverage commands supported by Visual Studio NuGet Package Manager Console
-> Commands can only be run within Visual Studio (no support for automation from command line)

-----------------------------------------------

What options does NuGet currently support for updating/managing package installations in automated fashion (such as from a CLI)?
Is there an option that has feature parity with the Visual Studio Package Manager Console?

Are there any libraries that have superseded NuGet.Core for programmatically updating NuGet packages? 
Is there a recommended migration path (with accompanying documentation)?

**Comment by zkat** [comment]
We have a new set of NuGet libraries that should be aware of things like 'netstandard2.0'. Please see https://docs.microsoft.com/en-us/nuget/reference/nuget-client-sdk for details.
