### ISSUE TITLE
GeneratePathProperty should automatically populate package path variables for package dependencies transitively

### ISSUE THREAD

**Issue by miniv** [NuGet/Home#9889]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **msbuild16 using PackageReference in csproj**

NuGet version (x.x.x.xxx):

dotnet.exe --version (if appropriate): **msbuild16**

VS version (if appropriate): 

OS version (i.e. win10 v1607 (14393.321)):

Worked before? If so, with which NuGet version: **No, didn't work**

## Detailed repro steps so we can see the same problem

When GeneratePathProperty is specified in a PackageReference, please populate package path variables for that package's dependencies transitively. We have run into issues where props/targets files associated with the package in the PackageReference need path variables for package dependencies and they are not populated correctly.

Setup:
- Nuget Package A that depends on Nuget Package B
- A targets file in Package A needs package path variable for Package B
- Application XYZ has PackageReference (with GeneratePathProperty="true") to Package A and uses the above targets file from Package A to build
- Package path variable for Package B is not populated and build fails

@rainersigwald 

...

### Verbose Logs

Please include verbose logs (NuGet.exe <COMMAND> -verbosity detailed | dotnet.exe <COMMAND> --verbosity diag | etc...)

### Sample Project

Very helpful if you can zip a project and paste into this issue!

**Comment by zkat** [comment]
We already have an ask for these variables as part of https://github.com/NuGet/Home/issues/7851
