### ISSUE TITLE
Need to improve error reporting mechanism when packages cannot be installed

### ISSUE THREAD

**Issue by MattGal** [NuGet/Home#989]
I hit this issue fairly regularly when working with new Portable Class libraries.  Specifically, when I make a "new" style portable library and add a package that fails to provide implementation for one of the target platforms, the problem is confusing and difficult to discover.

Example:  
- Create new Portable Class Library, targeting .NET Framework 4.6, ASP.NET Core 5.0, and Windows Universal 10.0
- Add a reference to a package like System.Diagnostics.TraceSource or System.Console, which lacks implementation for Windows Universal, via the VS Nuget Package management UI.

Best possible outcome:
- Install button on the package is not present /  disabled / otherwise indicating sadness, since the package can't satisfy the current project.

Less good, but acceptable outcome:
- When the user clicks "Install" a reasonably-worded error message appears in their error list explaining that they cannot install this package for the current project, 

What's happening today:
Only UI surfacing of the error:
![rollingback](https://cloud.githubusercontent.com/assets/7862010/8837584/d1429c6c-307b-11e5-8fa0-7fa249e94938.png)

Package Manager log:

**System.Diagnostics.TraceSource 4.0.0-beta-23119 provides a compile-time reference assembly for System.Diagnostics.TraceSource on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.**

Some folks will think that this is a bug with the packages' construction themselves, due to the cryptic nature of the message.

**Comment by yishaigalatzer** [comment]
@MattGal we made huge strides in logging errors for this scenario. There is nothing specific in this bug to address, We intend to keep investing in logging, so please bring more specific concerns, and we will address them individually.

**Comment by yishaigalatzer** [comment]
I'm taking my statement back, this still produces a pretty bad error message. We should make it better.

**Comment by emgarten** [comment]
Error messages have been improved around TFM checks. The error here is from the RID check which is going away.
