### ISSUE TITLE
Solution Explorer is not showing all NuGet package dependencies

### ISSUE THREAD

**Issue by vsfeedback** [NuGet/Home#9898]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1136736/soulution-explorer-not-showing-all-nuget-package-d.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
In latest visual studio preview (16.7.0 preview 6.0) then not all nuget package dependencies are show in solution explorer. I have opened the same project in two different Visual Studio instances (other being 16.6.5) and the non preview shows 6 nuget package references but the preview version shows only 4.

In the screenshot the preview version is to the left, and non preview to the right.

---
#### Nicolas Fløysvik on 8/5/2020, 02:53 AM: 

<p>Just to make it a little clearer, then this is talking about when we navigate to a nuget package under project-&gt;dependencies-&gt;Packages in the solution explorer and expand a nuget package here to see which other nuget packages it depends on. Then not all nuget packages it depends on are shown.</p>

#### Feedback Bot on 8/5/2020, 11:34 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Arturo Ortiz [MSFT] on 8/6/2020, 04:08 PM: 

<p>Hi Nicolas,</p>
<p>Thank you for your feedback. We need more information about your solution/projects in order to investigate the issue. Also, if you could please follow these steps to <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#record-a-repro" target="_blank">record a repro</a>, that would help us investigate.</p>
<p>Thanks and looking forward to your reply.</p>

#### Nicolas Fløysvik on 8/7/2020, 00:41 AM: 

I am only able to reproduce it with a private nuget package, but basically I Just install the nuget package in version 16.7 or later and not all the nuget package dependencies are shown. This worked as expected in version 16.6.x of Visual Studio. As can be seen from the nuget package installer then both destructurama.attributed and mediatr are dependencies for this backage, but only IN.x and Serilog are shown here.
#### Nicolas Fløysvik on 8/7/2020, 01:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by nkolev92** [comment]
Bug probably here: https://github.com/NuGet/NuGet.Client/blob/91084d0734c25fe17c981efcb206ba76c0c75b04/src/NuGet.Clients/NuGet.VisualStudio.Implementation/SolutionExplorer/Models/AssetsFileDependenciesSnapshot.cs#L142
