### ISSUE TITLE
Downgrading a package does not result in a package restore

### ISSUE THREAD

**Issue by MattGal** [NuGet/Home#990]
Using the new Nuget Package manager, if I upgrade a package in an ASP.NET 5 (or install a new one) I immediate see a full package restore run for the affected project.  

When I do downgrade, even if the downgraded version has never been on the machine (and thus isn't even in the cache) I just see:

***Installing NuGet package System.Diagnostics.TraceSource.4.0.0-beta-22231.
Successfully installed 'System.Diagnostics.TraceSource.4.0.0-beta-22231' to WebApplication3
========== Finished ==========***

It's not a major issue, but it is a behavioral quirk.

**Comment by emgarten** [comment]
Does the downgrade put the correct version into the project.json file? 
Is the package added to the global packages folder?

**Comment by MattGal** [comment]
- Project.Json is updated correctly.
- Package is **not** fetched / added to global package cache.

**Comment by emgarten** [comment]
From your description it looks like NuGet is handling this downgrade correctly. The restore part is done by DNX. Please file this issue on: https://github.com/aspnet/Home/issues
