### ISSUE TITLE
nuspec schema is incompatible with all versions of nuspec.xsd

### ISSUE THREAD

**Issue by DrStrangepork** [NuGet/Home#9901]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): nuget.exe

NuGet version (x.x.x.xxx): NuGet Version: 5.6.0.6591

VS version (if appropriate): VSCode 1.47.3

OS version (i.e. win10 v1607 (14393.321)): Win10.0.17763

Worked before? If so, with which NuGet version: it has never worked

## Detailed repro steps so we can see the same problem

1. `.\nuget pack .\app.nuspec`
```
The schema version of 'app' is incompatible with version 5.6.0.5 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.
```

2. Current setting in my app.nuspec file is `xmlns="https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd"`. I have tried all of the following nuspec.xsd options, and all have failed with the same error:

- http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd
- http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd
- http://schemas.microsoft.com/packaging/2015/03/nuspec.xsd
- http://schemas.microsoft.com/packaging/2016/06/nuspec.xsd

### Verbose Logs

```
 .\nuget pack .\app.nuspec  -verbosity detailed
NuGet Version: 5.6.0.6591
Attempting to build package from 'app.nuspec'.
The schema version of 'app' is incompatible with version 5.6.0.5 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.
System.InvalidOperationException: The schema version of 'app' is incompatible with version 5.6.0.5 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.
   at NuGet.Packaging.Manifest.CheckSchemaVersion(XDocument document)
   at NuGet.Packaging.Manifest.ReadFrom(Stream stream, Func`2 propertyProvider, Boolean validateSchema)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
```

### Sample Project

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd">
<!-- <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd"> -->
  <metadata>
    <id>app</id>
    <version>20200812</version>
    <title>app</title>
    <description>app</description>
    <authors>app</authors>
    <owners>app</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <copyright>Copyright 2020</copyright>
    <language>en-US</language>
    <icon>app.png</icon>
    <license type="file">LICENSE.txt</license>
  </metadata>
  <files>
    <file src="LICENSE.txt" target="" />
    <file src="app.png" target="" />
    <file src="rpmbuild\licenses.json" target="C:\Build\app" />
    <file src="tools\**" target="tools" />
  </files>
</package>
```

**Comment by donnie-msft** [comment]
@zkat may be able to comment on our support of these Schemas.

**Comment by aortiz-msft** [comment]
@v-luzh - Would you please try to repro replacing
`<package xmlns="https://raw.githubusercontent.com/NuGet/NuGet.Client/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd">`
with each of the published xsd files?

**Comment by DrStrangepork** [comment]
I don't know what "replacing ... with each of the published xsd files" means

**Comment by donnie-msft** [comment]
@DrStrangepork apologies that this didn't get answered sooner.
You can't point the xmlns to github. It has to point to a specific URI (identifier - which are not published files).
Our code checks for one of 6 known schemas: (see code [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L50) and [here](https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/ManifestSchemaUtility.cs#L125))

I've written up a Documentation issue to clarify this page, which I feel could be more clear
https://github.com/NuGet/docs.microsoft.com-nuget/issues/2195
