### ISSUE TITLE
New error from dotnet pack regarding DotnetToolSettings.xml starting with .NET SDK 3.1.401

### ISSUE THREAD

**Issue by lovettchris** [NuGet/Home#9902]
Remove the content above here and fill out details below.

## Details about Problem

SDK version 3.1.301, our nuget pack command worked fine.  Upgraded to 3.1.401 and now we get an error saying:
```
/usr/share/dotnet/sdk/3.1.401/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(198,5): error NU5118: File '/mnt/d/Temp/Coyote/bin/netcoreapp3.1/publish/DotnetToolSettings.xml' is not added because the package already contains file 'tools/netcoreapp3.1/any/DotnetToolSettings.xml' [/mnt/d/Temp/Coyote/Tools/Coyote/Coyote.csproj]
```

dotnet pack version (3.1.401):

OS version (Ubuntu 18.04)):

Worked before? If so, with which NuGet version: 3.1.302

## Detailed repro steps so we can see the same problem

1. https://github.com/microsoft/coyote

2. powershell -f Scripts/Build.ps1

3. dotnet pack Tools/Coyote/Coyote.csproj

### Verbose Logs

log attached
[pack.zip](https://github.com/NuGet/Home/files/5066180/pack.zip)

### Sample Project

https://github.com/microsoft/coyote

**Comment by rrelyea** [comment]
Repro the bug...but was hoping to do a quick check with net 5.0 preview 7 to see if the problem still existed...and you have so much validation checking assuming the sdk version is not a preview.
can you tell us if this still happens with 5.0 preview 7?

**Comment by lovettchris** [comment]
Hey Rob :-)   So I tried .NET 5.0 preview and got the same error.  But I'm beginning to think we should not have tried to copy DotnetToolSettings.xml in our .csproj.  We only do that because our real nuget package is still built using nuget.exe and a .nuspec, but we can't do that on linux, where we use dotnet pack, this then colides on linux, so we are going to change our build process instead, so I think you can close this bug report as something like "not supported scenario"...  just odd that this popped up only now.  I saw a bunch of new "error reporting" code was added recently in the nuget pack build task, and so I suspect that code picked up an error that was probably silently ignored before.

**Comment by lovettchris** [comment]
By the way I notice the .net 5.0 preview install doesn't modify "c:\Program Files\dotnet\dotnet.exe" is there a way to install .NET 5.0 dotnet.exe so that I don't have to do this:
```
dotnet "c:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\dotnet.dll" pack Tools\Coyote\Coyote.csproj
```

**Comment by aortiz-msft** [comment]
"I suspect that code picked up an error that was probably silently ignored before." - Yes, that is accurate :)
