### ISSUE TITLE
Release Process: Consider include a *complete* list of issues/commits fixed in a release 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9908]
See discussion in https://github.com/NuGet/docs.microsoft.com-nuget/pull/2052. 

cc @zkat @aortiz-msft @JonDouglas 

cc @fowl2 Would soimething like what I suggested in the title be sufficient for you?

**Comment by fowl2** [comment]
sure. GitHub's "tag compare" thing is probably good enough - assuming they are accurately represent releases.

eg. https://github.com/NuGet/NuGet.Client/compare/5.8.0.6761...5.8.0.6776

**Comment by aortiz-msft** [comment]
We can add the "tag compare" link in release notes moving forward.

**Comment by aortiz-msft** [comment]
Added to our playbook for Release Notes creation.
