### ISSUE TITLE
[Bug Bash][Test Failure] Warning icons show on the installed packages in Console App (.NET Core 5.0) project

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9910]
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6776
VS Version: Master\30413.119
OS: Windows-10-Enterprise-RS5
## Detailed repro steps 
1. Create a C# Console App (.NET Core) project in VS.
2. Open the project PM UI and the Solution Explorer window.
3. Install several packages from PM UI into the project.
4. Check the “Dependencies->Packages” node in the Solution Explorer window.
## Expected
No warning icons show on the installed package.
## Actual
Warning icons show on the installed packages in Console App (.NET Core 5.0) project but there is no warning in Error List window as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/90264971-81072580-de84-11ea-9e37-d2a64a649a1b.png)
## Notes
1. It repro on ASP Web Application (.NET Core 5.0), but not repro on Class Library (.NET Standard 2.1) project.
2. It didn’t repro when creating the .NET Core 5.0 project (so it is not the bug 1165638), repro after installing packages.
3. It didn’t repro on VS Master\30411.167 + NuGet Client Dev\5.8.0.6776, but repro on Master\30413.119 with implicit NuGet Client Dev\5.8.0.6776.

**Comment by kartheekp-ms** [comment]
Should be fixed by https://github.com/dotnet/sdk/pull/13093
