### ISSUE TITLE
NuGet Target framework information breaking change coordination

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9911]
In 16.8 P2, NuGet made a breaking change where we started reading the TargetFramework* and TargetPlatform* properties from the inner build.
This means that the framework detection across NuGet & SDK needed to change. 

In additional .NET 5 SDK, P7 and earlier, misreported the TargetPlatformMoniker for net5.0 projects as `Windows,Version=7.0`. 

Other notable challenges are that in 16.8 P2, NuGet used TargetPlatformIdentifier and TargetPLatformVersion, but in 16.8 P3 NuGet will use TargetPlatformMoniker. https://github.com/NuGet/NuGet.Client/pull/3578. 

So this is meant to coordinate the insertions necessary to get 16.8 P2 and 16.8 P3 in a happy state. 

- [x] NuGet -> VS (16.8 P2) [PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/267136) (done)
- [x] NuGet -> SDK (.NET 5 P8 & .NET 5 RC1)
  - @sfoslund in charge https://github.com/NuGet/Client.Engineering/issues/462, https://github.com/dotnet/sdk/pull/12915 and https://github.com/dotnet/sdk/pull/12897 (the main tracking issue)
  - Approved by tactics!
  - Merged into preview.8 (not master, yet?)
- [x] NuGet -> project-system (16.8 P2) https://github.com/dotnet/project-system/pull/6495 - This allows NuGet in VS 16.8 P2 and 16.8 P3 to work continuously.
- [x] Further insertion blocked (Charles and Peter)
  - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/267767?_a=overview
  - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/268099?_a=files
- [x] Insertions pending SDK changes
  - https://github.com/dotnet/sdk/pull/12944
  - https://github.com/dotnet/sdk/pull/12943
  - Estimated to land the night of 2020/08/17 (Monday), possibly early Tuesday
  - Once these are merged, insertion can be attempted again (and those will take a while to do their runs)
  - Matt will make sure drop gets pulled
- [x] SDK -> VS (.NET 5 P8 with NuGet to VS 16.8 P2)
  - @wli3 will be taking point on this
  - He will target https://dev.azure.com/devdiv/DevDiv/_git/VS?version=GBdev%2Fvslsnap%2Finsertions%2Fmaster.20200814130317 instead of 16.8 or master (because project system changes need SDK changes to pass DDRITS and vice versa)
  - SDK has flowed into the installer branch: https://dnceng.visualstudio.com/internal/_build/results?buildId=772035&view=results
- [x] project-system -> VS (16.8 P2) (See email thread for status, JJ and microbuild are on this. Tracking issue for insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/268099 )
  - master got locked, so PR 267767 had to be redirected to main

cc @zkat

**Comment by nkolev92** [comment]
Assigning all of us for awareness/visibility.

**Comment by nkolev92** [comment]
Assigning only @zkat...is that right?

**Comment by zkat** [comment]
I mean I'm assigned because I'm the one tracking/updating this. Should we add others, too?

**Comment by nkolev92** [comment]
I changed it because I didn't necessarily need the 5hrs of work showing up on my sprint.
There were no actionables from me.

**Comment by zkat** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/268099 has been merged, so we're done here. Time to focus on RC1 :)
