### ISSUE TITLE
Projects targetting net5.0-windows, end up generating a condition with an incorrect TargetFramework string

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9914]
This is a consequence of https://github.com/nuget/home/issues/9756. 

Some initial work started in `dev-nkolev92-originalTargetFrameworkCondition`

I'd estimate a 5-10 point task for someone familiar with the problem space.

**Comment by zivkan** [comment]
Assuming this issue makes it into the release notes when NuGet 5.8 ships, the first comment should probably be edited to make sense to people without the context that we have, having worked on the net5.0 stuff every day for several weeks, and many meetings about all these issues. Neither the title, nor body, nor PR explain which file(s) are affected by this change.

**Comment by nkolev92** [comment]
Things tagged with `RegressionDuringThisVersion` should not appear in the release notes. 
At least that's been my understanding.

I think the issue title is pretty good...how would you change it/the PR?

**Comment by nkolev92** [comment]
So I double it won't appear in the release notes: https://github.com/NuGet/Entropy/blob/20b5d7b00be51a89d95712c3a67882b2354223b9/ChangelogGenerator/ChangelogGenerator/ChangelogGenerator.cs#L99-L103. 

I am still curious about how you'd change it though.

**Comment by zivkan** [comment]
I'd just say what file it's impacting. I'm guessing this is related to the `.g.nuget.props` and `.g.nuget.targets` files, and nothing else, but neither this issue nor the PR makes that clear. The issue or PR titles don't necessarily need to be changed, but neither the issue nor PR bodies gave context about what this change is about.

But since it won't be in the release notes, it's not a big deal.

**Comment by zivkan** [comment]
Also, on the topic of issue titles, at least for release note titles, the title should use language to say what is fixed, not what the error is. So, "Generate correct condition in .g.nuget.[props|targets] for net5.0-windows" sounds better than a title that sounds like we want to introduce bugs :)

**Comment by nkolev92** [comment]
The PR title is that tone, calling out the usage of the original strings.
I have added a clarification for `in nuget.g.*`. 

I think the issue should say what's wrong, which it does. 

I think we're misusing issue titles for bugs tbh :D For features, it makes sense...bugs not so much.
