### ISSUE TITLE
Exclude specific reference from transitive dependencies

### ISSUE THREAD

**Issue by zd-dalibor** [NuGet/Home#9916]
If we have package A with dependency on package B (A -> B).

And if we have something like this in `MyProject.csproj` file:

```xlm
<ItemGroup>
  <PackageReference Include="A" Version="1.0.0" />
</ItemGroup>
```

this will automatically reference package B and package B will be downloaded from nuget repository.

I wont to manually reference package `B.dll` from my "D:\lib\" folder.

if I do this in `MyProject.csproj`:

```xlm
<ItemGroup>
  <PackageReference Include="A" Version="1.0.0" />
</ItemGroup>
<ItemGroup>
  <Reference Include="B">
    <HintPath>D:\lib\B.dll</HintPath>
  </Reference>
</ItemGroup>
```

I still get "B.dll" from nuget repository instead from "D:\lib\" folder.

How to solve this? How to tell package A does not include package B as reference in the project. Is there something like this:

```xlm
<ItemGroup>
  <PackageReference Include="A" Version="1.0.0">
    <Exclude Path="**\B.dll" />
  </PackageReference>
</ItemGroup>
<ItemGroup>
  <Reference Include="B">
    <HintPath>D:\lib\B.dll</HintPath>
  </Reference>
</ItemGroup>
```

**Comment by zd-dalibor** [comment]
Similar feature exists in gradle for java dependencies:

```goovy
  compile('org.jruby:jruby-core:9.0.5.0') {
    exclude('com.martiansoftware:nailgun-server')
  }
```

Does something like this exist for nuget dependencies?

**Comment by donnie-msft** [comment]
If I understand, I believe `<PrivateAssets>all</PrivateAssets>` is what you're looking for. Let me know if it helps!

> These assets will be consumed but won't flow to the parent project

See: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

**Comment by zd-dalibor** [comment]
But what if package A in some nuget repository (let say public one https://www.nuget.org/) has many dependencies (let say 5: B, C, D, E, F). I add reference to package A in my project. Now I only want to exclude B reference and use my version for them. I do not wont B reference from "https://www.nuget.org/" but all other C, D, E, F wont.

In this example I think all references B, C, D, E, F will be excluded, but I wont only B to be excluded.

```xml
<ItemGroup>
  <PackageReference Include="A" Version="1.0.0">
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
</ItemGroup>
<ItemGroup>
  <Reference Include="B">
    <HintPath>D:\lib\B.dll</HintPath>
  </Reference>
</ItemGroup>
```

Does NuGet have this feature?

**Comment by aortiz-msft** [comment]
This is not currently supported.

**Comment by nkolev92** [comment]
There's a related issues that deals with affecting the transitive dependency metadata. 

Specifically see: https://github.com/NuGet/Home/issues/6720

That issues covers things like, for Package `B`, adding ExcludeAssets=`all`.

**Comment by nkolev92** [comment]
Actually https://github.com/NuGet/Home/issues/5986 seems like an even more approriate issue. 

@zd-dalibor Does https://github.com/NuGet/Home/issues/5986 seem like an equivalent ask to yours?

**Comment by zd-dalibor** [comment]
@nkolev92
In general #5986 is similar to this. He wants to copy some transitive dependencies (not all of them) of PorjectA to ProjectB building output folder (ProjectB has reference on ProjectA)

**Comment by nkolev92** [comment]
Thanks, closing as dup of #5986 then. 

Can you please up vote that issue?

**Comment by QROST** [comment]
> If I understand, I believe `<PrivateAssets>all</PrivateAssets>` is what you're looking for. Let me know if it helps!
> 
> > These assets will be consumed but won't flow to the parent project
> 
> See: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

`<PrivateAssets>all</PrivateAssets>` doesn't resolve this problem... Not even if I have only one single B dependency for the A package. 
```
<ItemGroup>
  <PackageReference Include="A" Version="1.0.0">
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
</ItemGroup>
```
The above doesn't work for me..
