### ISSUE TITLE
Automatic formatting with `dotnet format`

### ISSUE THREAD

**Issue by zkat** [NuGet/Home#9917]
We should start enforcing code style through `dotnet format`. This will help us spend less time asking folks for miscellaneous style changes during code review, and catch it when we happen to miss something. Once the PR lands, it means in the future we'll stop having random formatting changes along with code PRs, hopefully.

As part of this task, we should also automate style verification on CI

**Comment by aortiz-msft** [comment]
We could also look into Stylecop?

**Comment by Nirmal4G** [comment]
> we should also automate style verification on CI

It should run before Restore and Build and fail fast if the style verification encounters warnings and errors.  (Related: #9970)

**Comment by jmarolf** [comment]
> We could also look into Stylecop?

Its currently in beta but in version 5 of `dotnet-format` you will be able to automatically fixup [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) if you add them to your project.

**Comment by zkat** [comment]
This is done.
