### ISSUE TITLE
resolve internal contracts assembly loading (fix RPS or get exception)

### ISSUE THREAD

**Issue by dtivel** [NuGet/Home#9919]
See https://github.com/NuGet/NuGet.Client/pull/3485#discussion_r468528172

**Comment by rrelyea** [comment]
testing early last week didn't show this DLL loading. RPS will be needed to confirm eventually, so leaving open.

**Comment by rrelyea** [comment]
RPS regression related to this: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1220030

**Comment by dtivel** [comment]
I created a simple Visual Studio extension that loads the "main" NuGet package when a command is invoked and installed this extension to both 16.7.6 and 16.9 Preview 2.

In 16.7.6 the following assemblies were loaded on NuGet package load (in order):

- NuGet.Tools.dll
- NuGet.VisualStudio.Common.dll
- NuGet.PackageManagement.UI.dll
- NuGet.PackageManagement.dll
- NuGet.Configuration.dll
- NuGet.VisualStudio.Implementation.dll
- NuGet.VisualStudio.Contracts.dll

In 16.9 Preview 2 the same assemblies above were loaded and the following additional assemblies were also loaded (in order):

- NuGet.PackageManagement.VisualStudio.dll
- NuGet.VisualStudio.Internal.Contracts.dll
- NuGet.Packaging.dll
- NuGet.Protocol.dll
- NuGet.Versioning.dll
- NuGet.ProjectModel.dll
- NuGet.Frameworks.dll

**Comment by dtivel** [comment]
Need to consider NGen-ing NuGet.VisualStudio.Contracts.dll and NuGet.VisualStudio.Internal.Contracts.dll, since JIT-ted methods was also a regressed RPS scenario.

**Comment by zivkan** [comment]
@dtivel don't those assemblies get JITed automatically since the first time the assemblies were inserted into VS?  Our VS package loads them every time our package is loaded, hence the first OptProf training after insertion should provide ngen data, right?

**Comment by dtivel** [comment]
@zivkan,

Since those 2 new contracts assemblies have been added, they have always been JIT-ted on a machine, never NGen-ed.  OptProf will not provide training data for these assemblies because we have not configured OptProf to profile the assemblies.

During OptProf's profiling phase, tests are run and training data are collected for assemblies.  NuGet provides input (via [build/OptProfV2.props](https://github.com/NuGet/NuGet.Client/blob/fa9fbcb87b8ce717d7f78d494cd16cf174be48e9/build/OptProfV2.props)) to the profiling process which identifies the tests to run and the target assemblies for data collection.  It is worth noting that NuGet enables partial not full NGen, so only the code paths in the assemblies we specify for a test that are hit by that test will be NGen-ed.

It may seem reasonable to add all NuGet assemblies (even future assemblies) proactively to OptProfV2.props.  However, if a specified assembly isn't loaded during a test, that's considered an error.  Because this can change over time --- we make a change that loads a new assembly that isn't profiled/optimized ---, there's the possibility that the overall scenario for which we want to optimize performance can regress.  We currently rely on existing RPS tests to catch regressions (e.g.:  assembly count increased, JIT-ed method count increased, etc).

Even if the assemblies build/OptProfV2.props specifies are loaded, there's a judgment call to be made as to whether or not we _should_ optimize, because there is a trade off with partial NGen-ing:  speed vs. memory.  If we partially NGen an assembly we wind up with 2 assemblies in memory:  a native image with NGen-ed code paths and an MSIL assembly for JIT-able code paths.  That would cause an RPS failure because more assemblies are being loaded, more memory is consumed.  If the trade-off was worth it, we'd need a permanent RPS exception for that.

Because these 2 contracts assemblies are loaded whenever the NuGet.Tools package loads, I think we need an exception whether the assemblies are optimized or not.  The justifications would be different though.

**Comment by zivkan** [comment]
Thanks @dtivel, that was very interesting.

For what it's worth, Roslyn calls `NuGet.VisualStudio.Contracts`'s `INuGetProjectService.GetInstalledPackagesAsync` on every project load. Hence, I think that ngening that assembly has potential to improve solution load perf. Their first insertion after starting to use this API, they had to request an exception because it wasn't getting ngend and their RPS was failing. I incorrectly assumed that after they inserted, our next build would start ngening it. I didn't know that we have an allow-list of assemblies in optprofv2.props. Thanks for letting me know!

**Comment by dtivel** [comment]
I profiled Microsoft Visual Studio Enterprise 2019 Int Preview (Version 16.9.0 Preview 2.0 [30712.215.main]), which contains NuGet version 5.9.0-preview.1.6955+fa9fbcb87b8ce717d7f78d494cd16cf174be48e9.fa9fbcb87b8ce717d7f78d494cd16cf174be48e9.  This version contains NuGet/NuGet.Client#3751.  PerfView reported the following JIT statistics for NuGet assemblies after a package load (per earlier repro steps).

Name | JitTime (ms) | Num Compilations | IL Size | Native Size | Foreground (ms) | Multicore JIT Background (ms) | Tiered Compilation Background (ms)
-- | -- | -- | -- | -- | -- | -- | --
TOTAL | 144.7 | 113 | 9,989 | 26,851 | 144.7 | 0 | 0
NuGet.Tools.dll | 57.1 | 22 | 3,166 | 6,379 | 57.1 | 0 | 0
**NuGet.VisualStudio.Internal.Contracts.dll** | **0.8** | 2 | 163 | 596 | 0.8 | 0 | 0
NuGet.VisualStudio.Common.dll | 0.6 | 2 | 49 | 140 | 0.6 | 0 | 0
**NuGet.VisualStudio.Contracts.dll** | **0.2** | 1 | 33 | 131 | 0.2 | 0 | 0
NuGet.PackageManagement.UI.dll | 0.2 | 1 | 51 | 275 | 0.2 | 0 | 0

The combined JIT cost of NuGet.VisualStudio.Contracts.dll and NuGet.VisualStudio.Internal.Contracts.dll is insignificant:  1 ms.
