### ISSUE TITLE
Pack tells me it will exclude folder starting with dot, but does not

### ISSUE THREAD

**Issue by jazzdelightsme** [NuGet/Home#9921]
## Version info

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): **NuGet.exe**

NuGet version (x.x.x.xxx): **5.6.0.6591**

OS version (i.e. win10 v1607 (14393.321)): **Win10 Version 2004 (OS Build20195.1000)**

Worked before? If so, with which NuGet version: **don't know**

## Description

"Nuget pack" is including my ".git" directory, even though it says it will exclude files and folders that start with a dot ('.'). Additionally, I have not been able to craft an exclude directive that will successfully exclude my .git directory.

### details

I keep my project in source control using git, so I have a .git directory and .gitignore file in the root of my project.

My project is very simple... just a PowerShell script module. So my "content" starts at the root directory.

Sample file layout:

```
PS E:\temp\nugetProblem2> dir -Recurse

    Directory: E:\temp\nugetProblem2

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           8/17/2020  8:10 PM                .git
-a---           8/17/2020  8:13 PM              4 .gitignore
-a---           8/17/2020  8:18 PM            309 nugetProblem.nuspec
-a---           8/17/2020  8:09 PM             52 ReadMe.txt

    Directory: E:\temp\nugetProblem2\.git

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           8/17/2020  8:10 PM              4 shouldNotBePacked.txt

PS E:\temp\nugetProblem2>
```
When I run "nuget pack", it very clearly tells me:

```
WARNING: NU5119: File 'E:\temp\nugetProblem2\.gitignore' was not added to the package. Files and folders starting with '.' or ending with '.nupkg' are excluded by default.
```

And in fact it *does* exclude the ".gitignore" file. But it does **NOT** exclude the ".git" directory.

On top of that, I have not been able to come up with an "exclude" directive, either on the command line or in the .nuspec file, to exclude the ".git" directory.

### Repro steps, with sample project

Attached is a sample/dummy project that will reproduce the problem:
[nugetProblem.zip](https://github.com/NuGet/Home/files/5087988/nugetProblem.zip)

**Repro steps:**
1. Extract the sample project.
2. In the root of the sample project directory, run "nuget pack".
3. Observe the warning message about how "Files and folders starting with '.'" will not be packed.
4. Rename the resulting .nupkg to .zip and open it up.

**Expected result:**
The .git folder should not be in the package.

**Actual result:**
The .git folder is in the package.

**Comment by donnie-msft** [comment]
Haven't repro'd yet but it looks like a potential bug. Do you see the same behavior with `dotnet pack` ? That may help you work around the problem for now.

/cc: @zkat

**Comment by zkat** [comment]
Closing as a duplicate of https://github.com/NuGet/Home/issues/8798, which is fixed. Please try it with the latest NuGet client and open a new issue if you can still repro this.
