### ISSUE TITLE
[Test Failure] No-op restore doesn’t occur at the first time in MSBuild restore command for the non-.Net SDK-style projects

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9924]
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6779
VS Version: Master\30418.48
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Create a non-.Net SDK-style project [e.g. C# Console App (.NET Framework)] in VS.
2. Open the PM UI of the project and install several packages with “PackageReference” format.
3. Save the solution and close VS.
4. Go to the VS developer command prompt, cd to the path of the project and do “msbuild /t:restore /v:d”.
## Expected Result
No-op restore occur for the first time.
## Actual Result
No-op restore doesn’t occur at the first time. It start to occur from the second time as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/90614395-321f0e80-e23d-11ea-95be-bb4fc721f963.png)
## Notes
1. It doesn’t repro in VS build restore for the same project (as below screenshot).
![image](https://user-images.githubusercontent.com/20632625/90614442-3f3bfd80-e23d-11ea-9f51-6c792da9d94b.png)
2. It started to repro from Dev\5.8.0.6761 (didn’t repro on Dev\5.8.0.6760).

**Comment by aortiz-msft** [comment]
@nkolev92 - Would you please take a look?

**Comment by nkolev92** [comment]
Yep, I caught this today while doing some other changes. 

Good:
* I understand the bug + the fix. It shouldn't be too bad.

Bad:
* This regression has existed for a while.
* I have automation that were supposed to catch this, but apparently didn't :)

**Comment by nkolev92** [comment]
I even left a comment in my code yesterday :D https://github.com/NuGet/NuGet.Client/commit/73961568042b185fcf9b992100738880945c172f. 

I'll front load the fix here, but it *only* affects no-op, no functional break restore here.

**Comment by nkolev92** [comment]
This is easy to fix and will do it, but want to merge https://github.com/NuGet/NuGet.Client/pull/3590 and https://github.com/NuGet/NuGet.Client/pull/3603 first since all 3 are touching related/same codepaths.

**Comment by nkolev92** [comment]
PR out: https://github.com/NuGet/NuGet.Client/pull/3606

Answering my question from above, the tests *do exists*, but they were not assert that the *msbuild call* failed completely without running the command. Unsure when this broke, likely in 16.x, but I have fixed the tests now.

**Comment by v-luzh** [comment]
It is fixed on Dev\5.8.0.6797.
