### ISSUE TITLE
Owner Tag not shipped in nuspec file using dotnet pack

### ISSUE THREAD

**Issue by joeloff** [NuGet/Home#9925]
---
**Issue moved from dotnet/sdk#12538**
- Please respond to @kmuthukumar23.

---

_From @kmuthukumar23 on Friday, July 17, 2020 4:26:19 AM_

### Describe the bug

Run the '**dotnet pack pathTo csproj**' in CLI, the owner tag is missing in nuspec file with in the generated nuget. I have faced this issue recent days. Before 10days it was working fine. last three days i am facing this issue.

### To Reproduce

I am using this below tags in my project file.

<Project Sdk="Microsoft.NET.Sdk.Razor">

      <PropertyGroup>

      <Title>projectTitle</Title>

      <Company>MyName</Company>

     <Authors>MyName</Authors>

     </PropertyGroup>

     </Project>

Expected Nupec contents

<metadata>

    <title>projectTitle</title>

    <authors>MyName</authors>

     <owners>MyName</owners>

</metadata>

But it generated with out '<owners></owners>' tag

<metadata>

    <title>projectTitle</title>

    <authors>MyName</authors>

</metadata>

It occurs recent days only.

### Further technical details
- ASP.NET Core version - 3.1

- Include the output of `dotnet --info`

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS ) you're running on, and it's version

Version 16.6.2

**Comment by joeloff** [comment]
---
**Issue moved from dotnet/sdk#12538**
- Please respond to @joeloff.

---

_From @joeloff on Wednesday, August 19, 2020 5:19:24 PM_

I believe this comes from NuGet.Build.Tasks.Pack.targets (GenerateNuspec target). Moving this over to NuGet.

**Comment by donnie-msft** [comment]
I was able to repro using `dotnet new console`, adding metadata, running `dotnet pack`, then inspecting the nuspec.
Resulting nuspec:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>Repro9925</id>
    <version>1.0.0</version>
    <title>projectTitle</title>
    <authors>bbbb</authors>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework="net5.0" />
    </dependencies>
  </metadata>
</package>
```
@zkat, any insights here?

**Comment by zivkan** [comment]
It was removed as requested by a community member: https://github.com/NuGet/Home/issues/5134

@kmuthukumar23 How do you use the owners metadata? Why is it important to you at pack time?

The intention for the owners metadata is that it represents the accounts were able to upload the package to an HTTP feed. Therefore, it is either unknown, or unverified at pack time. The authors metadata represent who created the package.

**Comment by nkolev92** [comment]
This was a deliberate decision made as part of the bigger picture around package ownership. 
Adding @chgill-MSFT as the PM that was for this change.

**Comment by donnie-msft** [comment]
⏰ @kmuthukumar23 could you please help us by answering the questions above?
