### ISSUE TITLE
Need VS 2015 RTM, Windows 10 Tools for 'nuget.exe restore project.json' to work

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#993]
Need VS 2015 RTM, Windows 10 Tools for 'nuget.exe restore project.json' to work

Repro steps

1. Create a UWP application
2. Run 'nuget.exe restore project.json'
3. Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neut
ral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system can
not find the file specified.

**Comment by pranavkm** [comment]
Dup of https://github.com/NuGet/Home/issues/956
