### ISSUE TITLE
CI build throws error NU5104 and succeeds regardless

### ISSUE THREAD

**Issue by AmadeusW** [NuGet/Home#9930]
Please read the following information before posting the issue.

## Details about Problem

Our CI build produces multiple instances of warning NU5104 (treated as error)
However, the CI build succeeds.

This may lead engineer diagnosing a build failure on an incorrect path, wasting their time, because the error which caused the build failure is buried somewhere else in the log.

The expected behavior is either
1. Make these warnings and allow the build to succeed
2. Fail the build since it has errors

The incorrect behavior is to see this in the logs
`15 Error(s) \ Successfully built`

## Versions

I'm not sure which nuget version it's used. It's happening in CI within DevDiv
```
Agent name: 'vs2019mb-00000J'
Agent machine name: 'vs2019mb-00000J'
Current agent version: '2.171.1'
Agent running as: 'dlab14'
```

The error originates at `dotnet\sdk\3.0.101\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5)`

NuGet product used:
msbuild using .NET SDK 3.0.101 in AzureDevOps CI build

NuGet version:
NuGet 5.0.2 x64

dotnet.exe --version (if appropriate): n/a

VS version (if appropriate): n/a

OS version (i.e. win10 v1607 (14393.321)): n/a

Worked before? If so, with which NuGet version:

## Detailed repro steps so we can see the same problem

1.  Pick any passing build in this definition: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8282
For a recent example, take https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3999127&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=08e986c2-058e-5f01-51da-ae4278e2d74e

2. Go to the build log

3. Observe
```
C:\A\1\_tool\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.Internal.VisualStudio.Shell.Embeddable [16.6.29918.18-pre, )" or update the version field in the nuspec. [C:\A\1\13\s\src\Editor\VisualStudio\Impl\EditorImpl.csproj]
C:\A\1\_tool\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading [16.7.29-alpha, )" or update the version field in the nuspec. [C:\A\1\13\s\src\Editor\Text\Test\Util\TextUnitTestHelper\TextUnitTestHelper.csproj]
C:\A\1\_tool\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading [16.7.29-alpha, )" or update the version field in the nuspec. [C:\A\1\13\s\src\Editor\Text\Test\Util\EditorTestApp\EditorTestApp.csproj]
C:\A\1\_tool\dotnet\sdk\3.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Microsoft.VisualStudio.Threading [16.7.29-alpha, )" or update the version field in the nuspec. [C:\A\1\13\s\src\Editor\Text\Test\Util\TextViewUnitTestHelper\TextViewUnitTestHelper.csproj]
    1505 Warning(s)
    15 Error(s)

Time Elapsed 01:10:07.28
Successfully built
```
Specifically, the issue is seeing these two messages:
`15 Error(s) \ Successfully built`

Please let us know whether this is an AzureDevOps configuration issue
Thanks!

**Comment by donnie-msft** [comment]
I know there's some configuration in AzDO to allow builds to succeed despite certain errors....
@zivkan may have guidance here

**Comment by zivkan** [comment]
There's a bug in pack where warnings that are elevated to warnings do not cause pack to return a non-zero exit code, hence build scripts and CI systems don't know that an error occurred.

I thought we had a better, more clear issue explaining this, but this is the only duplicate I can find at the moment: https://github.com/NuGet/Home/issues/6992

**Comment by zivkan** [comment]
I forgot to mention, please upvote 👍 the other issue to increase the chance it gets prioritized. GitHub doesn't provide any way for us to transfer upvotes on duplicate issues to the tracking issue.

**Comment by nkolev92** [comment]
Hey @AmadeusW, 

We're aware of this issue, duplicate of https://github.com/NuGet/Home/issues/7404. 
It was fixed in 5.7/3.1.400!

**Comment by nkolev92** [comment]
@zivkan @donnie-msft @AmadeusW 

Given that this scenario is dotnet.exe, the problem in dotnet.exe is fixed in the latest release.

**Comment by zivkan** [comment]
No wonder I had so much trouble finding the good duplicate issue, I forgot to check closed issues! (I forgot that this was fixed)
