### ISSUE TITLE
Investigate if uninstall have more than 1 restore problem for reference type projects.

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9932]
## Details about Problem

It's follow up for `Nuget Solution Package manager UI is slow because restore is run for every project instead of after all projects are updated ` [#6010](https://github.com/NuGet/Home/issues/6010) task. I solved [install/upgrade/downgrade cases](https://github.com/NuGet/NuGet.Client/blob/0f86276892b00c8abc41e94b186b32e1fc1a6b18/src/NuGet.Clients/NuGet.PackageManagement.UI/Actions/UIActionEngine.cs#L842), but my changes doesn't cover uninstall case. For 2-3 sample solutions I tried doesn't have multi restore problem, but just in case need to check all code path to make sure.

**Comment by nkolev92** [comment]
I think a good test case for this is;

Project 1 -> Project 2 -> Project 3, where 2 & 3, have Package A. 
Uninstall Package A and see how many restores happen. 

Quick test on my end, uninstall *does* have a problem. 

```
Restoring packages for C:\Users\Roki2\Documents\Code\test\uninstall\P3\P3.csproj...
Restoring packages for C:\Users\Roki2\Documents\Code\test\uninstall\P2\P2.csproj...
Committing restore...
Writing assets file to disk. Path: C:\Users\Roki2\Documents\Code\test\uninstall\P3\obj\project.assets.json
Successfully uninstalled 'Newtonsoft.Json 12.0.3' from P3
Committing restore...
Assets file has not changed. Skipping assets file writing. Path: C:\Users\Roki2\Documents\Code\test\uninstall\P1\obj\project.assets.json
Restored C:\Users\Roki2\Documents\Code\test\uninstall\P1\P1.csproj (in 0.7 ms).

NuGet Config files used:
    C:\Users\Roki2\Documents\Code\NuGet.Config
    C:\Users\Roki2\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
Executing nuget actions took 143 ms
Restoring packages for C:\Users\Roki2\Documents\Code\test\uninstall\P2\P2.csproj...
Committing restore...
Writing assets file to disk. Path: C:\Users\Roki2\Documents\Code\test\uninstall\P2\obj\project.assets.json

NuGet Config files used:
    C:\Users\Roki2\Documents\Code\NuGet.Config
    C:\Users\Roki2\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
Restoring packages for C:\Users\Roki2\Documents\Code\test\uninstall\P1\P1.csproj...
Committing restore...
Writing assets file to disk. Path: C:\Users\Roki2\Documents\Code\test\uninstall\P1\obj\project.assets.json

NuGet Config files used:
    C:\Users\Roki2\Documents\Code\NuGet.Config
    C:\Users\Roki2\AppData\Roaming\NuGet\NuGet.Config
    C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

Feeds used:
    https://api.nuget.org/v3/index.json
Executing nuget actions took 187 ms
Time Elapsed: 00:00:00.3942751
```

See how P2 is restored twice!

**Comment by erdembayar** [comment]
It looks you got this log from public VS2019. I got similar duplicate restore on my [TestRepo](https://github.com/erdembayar/MainApplicationTestSolution):
https://gist.github.com/erdembayar/d96a2f5cb45b92bec8e598f45484194b 
ConsoleApp2.csproj was restored 2 times.

I didn't really target uninstall scenarios but it looks already solved.
Below is log from experimental instance with my changes:
https://gist.github.com/erdembayar/772db3f51d191b9068f691671abbe293
Both ConsoleApp1.csproj and ConsoleApp2.csproj was restored only once.

https://gist.github.com/erdembayar/1a97b3d2853c5af432e0117392a01303
All projects was restored only once.

**Comment by erdembayar** [comment]
It looks both install and uninstall actions share same code path NugetPackageManager#[Line2601](https://github.com/NuGet/NuGet.Client/blob/17c2ba939257bb5988bdbc5c8391dfeed2b7e3aa/src/NuGet.Core/NuGet.PackageManagement/NuGetPackageManager.cs#L2601) where code optimization change was made. So now uninstall scenario also benefit from my change too.

**Comment by nkolev92** [comment]
> t looks both install and uninstall actions share same code path NugetPackageManager

Can you please add tests for it then? 

A scenario like the one I called out in https://github.com/NuGet/Home/issues/9932#issuecomment-679439201, would be great!

Assigning to you given that your change is already addressing it.

**Comment by erdembayar** [comment]
I added 2 unit tests for this uninstall case: 
[NetCorePackageReferenceProjectTests#L2156](https://github.com/NuGet/NuGet.Client/blob/530be9263181018b79bddae991a9dda0dc2d0998/test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/NetCorePackageReferenceProjectTests.cs#L2156)
[NetCorePackageReferenceProjectTests#L2325](https://github.com/NuGet/NuGet.Client/blob/530be9263181018b79bddae991a9dda0dc2d0998/test/NuGet.Clients.Tests/NuGet.PackageManagement.VisualStudio.Test/NetCorePackageReferenceProjectTests.cs#L2325)

**Comment by nkolev92** [comment]
Closing per https://github.com/NuGet/NuGet.Client/commit/53a7cf2b5b600cf46bc49285e1ae6f4cf887346b
