### ISSUE TITLE
Clicking NU code in Visual Studio Error List window should go to https://docs.microsoft.com/nuget/reference/errors-and-warnings/

### ISSUE THREAD

**Issue by Youssef1313** [NuGet/Home#9934]
Currently, it's:

```csharp
internal const string HelpLink = "https://msdn.microsoft.com/query/dev15.query?appId=Dev15IDEF1&l={0}&k=k({1})&rd=true";
```

This needs to be updated to either dev16, which is a later version, to be more future proof in case the old url was deprecated. Or update to docs.microsoft directly. (The choice between the two is currently being discussed in my PR)

**Comment by zivkan** [comment]
@Youssef1313 thank you for contributing a PR!  I believe this should make it into VS 16.8 before it goes GA.
