### ISSUE TITLE
Importing MSBuild Targets from Referenced Package

### ISSUE THREAD

**Issue by nfplee** [NuGet/Home#9938]
I have a project "Foo.Theme" which has the following defined in the "Foo.Theme.csproj" file:

```
<ItemGroup>
  <ProjectReference Include="..\Foo.Module\Foo.Module.csproj" />
</ItemGroup>

<ItemGroup>
  <None Include="Foo.Theme.props" Pack="true">
    <PackagePath>build\$(TargetFramework)\Foo.Theme.props</PackagePath>
  </None>
</ItemGroup>
```

Where the "Foo.Module" project has the following defined in it's "Foo.Module.csproj" file:

```
<ItemGroup>
  <None Include="Foo.Module.props" Pack="true">
    <PackagePath>build\$(TargetFramework)\Foo.Module.props</PackagePath>
  </None>
</ItemGroup>
```

Now if I add a package reference to "Foo.Theme" it correctly imports the targets from the "Foo.Theme.props" file within the package. However it's not importing the "Foo.Module.props" targets.

I can add a package reference to "Foo.Module" aswell but I thought since "Foo.Theme" has a reference to "Foo.Module" it would work without having to reference both.

I'd appreciate it if somone could explain why this is the case and possibly supply a solution. Thanks

**Comment by zivkan** [comment]
Unfortunately it's not well documented, well, not explained well in the docs. But the nupkg's `build\` directory is only used for direct dependencies. Transitive dependencies use `buildTransitive\`, so if you copy `Foo.Module`'s props file there, it will be imported. Note however that only PackageReference projects use `buildTransitive`. If you want your package to support both packages.config and PackageReference, you need your props file in both locations in the nupkg.

**Comment by nfplee** [comment]
Thanks @zivkan that worked a treat. I don't need support for packages.config therefore I've simply changed `build` to `buildTransitive`.

**Comment by SimonCropp** [comment]
@zivkan 

> Note however that only PackageReference projects use buildTransitive

is this documented anywhere?

**Comment by zivkan** [comment]
I couldn't find that specifically documented in a quick search, but note that when installing packages into a packages.config project, all the packages in the graph are added directly to the packages.config fie, hence all the packages are "direct". packages.config doesn't have the concept of transitive.
