### ISSUE TITLE
NuGet pack should reject duplicated entries in the same directory

### ISSUE THREAD

**Issue by mmitche** [NuGet/Home#9939]
Please read the following information before posting the issue.

## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): Any nuget path that can pack.

NuGet version (x.x.x.xxx): Any recent nuget version.

## Detailed repro steps so we can see the same problem

It is possible to create a package that contains multiple files with the same name in the same directory. This cannot be unpacked on any operating system in a predictable manner, and a push to nuget.org fails.

**Comment by jaredpar** [comment]
@ericstj did the investigation and can comment on how the `pack` ended up with two different files with the same name.

**Comment by jaredpar** [comment]
Related change is here: https://github.com/dotnet/arcade/pull/5818

Essentially we found that we had created NuPkg files with duplicate files and had to work to undo this. Such packages are essentially broken and can't be reliably used. Tooling that operates at the ZIP level don't expect to see this and ended up failing in our build pipeline. This change is us undoing that mistake.

**Comment by mmitche** [comment]
This change regressed this in Arcade: https://github.com/dotnet/arcade/commit/50da2e606edc3ec69750480c356f433e710304ef#r40426132

And it was fixed in the Arcade currently in use in rc1 in windowsdesktop: https://github.com/dotnet/arcade/commit/b1754cc4a2d37d522946792f50887eb716220f6a

**Comment by mmitche** [comment]
I think this actually may be because windowsdesktop was creating its nuget packages using a non-standard process, but @zkat we should still ensure that you can't get into this situation using the standard usage paths. @jaredpar said he had seen similar issues with roslyn, which I believe does use the standard pack processes.

**Comment by nkolev92** [comment]
@zkat this is probably a duplicate of https://github.com/NuGet/Home/issues/6941.

**Comment by zkat** [comment]
Closing as dupe, and assigning that one to myself instead.
