### ISSUE TITLE
dotnet on Linux incorrectly detects revoked certificates on signed packages.

### ISSUE THREAD

**Issue by rido-min** [NuGet/Home#9941]
The package https://www.nuget.org/packages/Rido.CoreAppLauncher/0.0.1-Beta1 is signed with author and repo certificates.

NuGet.exe  5.4.0.6315 reports the package as valid
```
Successfully verified package 'Rido.CoreAppLauncher.0.0.1-Beta1'.
```
<details>
Verifying Rido.CoreAppLauncher.0.0.1-Beta1
C:\Users\rido\Downloads\rido.coreapplauncher.0.0.1-beta1.nupkg

Signature Hash Algorithm: SHA256
Timestamp: 11/7/2018 8:31:32 PM

Verifying author primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=DigiCert SHA2 Timestamp Responder, O=DigiCert, C=US
  SHA1 hash: 400191475C98891DEBA104AF47091B5EB6D4CBCB
  SHA256 hash: FC834D5BFFDE31DBA5B79BF95F573F7953BCBF9156E8525163E828EB92EA8A93
  Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 1/3/2017 4:00:00 PM to 1/17/2028 4:00:00 PM

Verifying the author primary signature with certificate:
  Subject Name: CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
  SHA1 hash: AF227A682A7A39B3E21740C6C42C27E56312D3D8
  SHA256 hash: 518F74AE79E44C7451FB5013E63D46BFF967A11AA13CD8F4586C57059AE900C9
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 7/11/2018 5:00:00 PM to 10/11/2019 5:00:00 AM

Timestamp: 11/7/2018 8:36:43 PM

Verifying repository countersignature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: 625AEC3AE4EDA1D169C4EE909E85B3BBC61076D3
  SHA256 hash: CF7AC17AD047ECD5FDC36822031B12D4EF078B6F2B4C5E6BA41F8FF2CF4BAD67
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 1/1/2017 4:00:00 PM to 4/1/2028 4:59:59 PM

Signature type: Repository
nuget-v3-service-index-url: https://api.nuget.org/v3/index.json
nuget-package-owners: ridomin
Verifying the repository countersignature with certificate:
  Subject Name: CN=NuGet.org Repository by Microsoft, O=NuGet.org Repository by Microsoft, L=Redmond, S=Washington, C=US
  SHA1 hash: 8FB6D7FCF7AD49EB774446EFE778B33365BB7BFB
  SHA256 hash: 0E5F38F57DC1BCC806D8494F4F90FBCEDD988B46760709CBEEC6F4219AA6157D
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 4/9/2018 5:00:00 PM to 4/14/2021 5:00:00 AM

Successfully verified package 'Rido.CoreAppLauncher.0.0.1-Beta1'.
</details>

When trying to install the same package in Ubuntu 20 (WSL2) with `dotnet 5.0.100-preview.8.20417.9` I got the following error

```
error: Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': The author primary signature found a chain building issue: Revoked: certificate revoked
```

<details>
```
dotnet add package rido.coreapplauncher -v 0.0.1-beta1

  Determining projects to restore...
  Writing /tmp/tmpn2UntS.tmp
info : Adding PackageReference for package 'rido.coreapplauncher' into project '/home/rido/code/testcons/testcons.csproj'.
info : Restoring packages for /home/rido/code/testcons/testcons.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/rido.coreapplauncher/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/rido.coreapplauncher/index.json 399ms
info :   GET https://api.nuget.org/v3-flatcontainer/rido.coreapplauncher/0.0.1-beta1/rido.coreapplauncher.0.0.1-beta1.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/rido.coreapplauncher/0.0.1-beta1/rido.coreapplauncher.0.0.1-beta1.nupkg 10ms
info : Installing Rido.CoreAppLauncher 0.0.1-Beta1.
info : Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': Signature Hash Algorithm: SHA256
info : Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': Timestamp: 11/07/2018 20:31:32
info : Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': Verifying author primary signature's timestamp with timestamping service certificate:
info :   Subject Name: CN=DigiCert SHA2 Timestamp Responder, O=DigiCert, C=US
info :   SHA1 hash: 400191475C98891DEBA104AF47091B5EB6D4CBCB
info :   SHA256 hash: FC834D5BFFDE31DBA5B79BF95F573F7953BCBF9156E8525163E828EB92EA8A93
info :   Issued by: CN=DigiCert SHA2 Assured ID Timestamping CA, OU=www.digicert.com, O=DigiCert Inc, C=US
info :   Valid from: 01/03/2017 16:00:00 to 01/17/2028 16:00:00
info : Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': Signature type: Author
info : Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': Verifying the author primary signature with certificate:
info :   Subject Name: CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
info :   SHA1 hash: AF227A682A7A39B3E21740C6C42C27E56312D3D8
info :   SHA256 hash: 518F74AE79E44C7451FB5013E63D46BFF967A11AA13CD8F4586C57059AE900C9
info :   Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
info :   Valid from: 07/11/2018 17:00:00 to 10/11/2019 05:00:00
error: Package 'Rido.CoreAppLauncher 0.0.1-Beta1' from source 'https://api.nuget.org/v3/index.json': The author primary signature found a chain building issue: Revoked: certificate revoked
info : Package 'rido.coreapplauncher' is compatible with all the specified frameworks in project '/home/rido/code/testcons/testcons.csproj'.
error: Value cannot be null. (Parameter 'path1')
```
</details>

**Comment by heng-liu** [comment]
Yes, the certificate on this author primary signature is revoked.
But we set the ChainPolicy.VerificationTime to timestamp.UpperLimit.LocalDateTime before chain building at https://github.com/NuGet/NuGet.Client/blob/784274cc9b2002ca73055e8134064261118d8a01/src/NuGet.Core/NuGet.Packaging/Signing/Utility/CertificateChainUtility.cs#L174-L177.
 
According to [X509ChainPolicy.VerificationTime Property](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509chainpolicy.verificationtime?view=net-5.0), if the certificate is not yet revoked at the specified time, the chain status should not contain `Revoked`.

I created a console app to run chain building with/without setting the ChainPolicy.VerificationTime for the author signature certificate. The results are as following:
On Windows:
```
pls enter the pacakge path...
C:\\Users\\henli\\Downloads\\rido.coreapplauncher.0.0.1-beta1.nupkg
Timestamp.UpperLimit.LocalDateTime on this signature is 11/7/2018 8:31:32 PM
==========  Without setting X509ChainPolicy.VerificationTime ==============
   chain building for CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
"CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US,
CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US,
CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US,"
 Status : "NotTimeValid,Revoked"

==========  Setting X509ChainPolicy.VerificationTime to 11/7/2018 8:31:32 PM ==============
   chain building for CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
"CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US,
CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US,
CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US,"
 Status : OK
```
 
On Linux
```
pls enter the pacakge path...
/home/henli/demo/packages/rido.coreapplauncher.0.0.1-beta1.nupkg
Timestamp.UpperLimit.LocalDateTime on this signature is 11/08/2018 04:31:32
==========  Without setting X509ChainPolicy.VerificationTime ==============
   chain building for CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
"CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US,
CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US,
CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US,"
 Status : "NotTimeValid,Revoked"

==========  Setting X509ChainPolicy.VerificationTime to 11/08/2018 04:31:32 ==============
   chain building for CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US
"CN=Ricardo Minguez, O=Ricardo Minguez, L=Redmond, S=Washington, C=US,
CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US,
CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US,"
 Status : "Revoked"
```
So it looks like on Linux, the X509ChainPolicy.VerificationTime is not respected in chain building.
I'll raise an issue in dotnet runtime.

**Comment by heng-liu** [comment]
The chain building results on Linux and MacOS will have Revoked status, even if we specify the X509ChainPolicy.VerificationTime.
Dotnet runtime won't make any change to make the results same for different platforms.

So the restore will fail on Linux and MacOS, but succeed on Windows, for those packages with revoked certificate, even if it's timestamped.
Do you have any concerns? @rido-min @anangaur @JonDouglas @dtivel

**Comment by heng-liu** [comment]
Closed as external.

**Comment by rido-min** [comment]
Hi @heng-liu sorry for the late reply. Can we keep this open while we hear back from @dtivel or @anangaur ? 

Is there any potential workaround? If not we should build a plan to communicate the issue to our customers.

**Comment by heng-liu** [comment]
My understanding is, there is no workaround. We can't ignore the `Revoked` status, as we don't know whether it's revoked before the timestamp or after the timestamp. 
And from the current [X509Certificate2 Class](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=net-5.0 ) , there seems no way for us to get any information about when is the certificate revoked.
Pls correct me if it's wrong, thanks! @dtivel

**Comment by rido-min** [comment]
I'd suggest to re-evaluate, and ask again to .NET folks. 

As per my understanding this implies that once a cert is revoked, all package restores will fail validation on Linux. 

Now imagine that we need to revoke NuGet.org repo cert, or the Microsoft author cert, or one of the intermediates: Which would be the implications for non Windows clients?

**Comment by anangaur** [comment]
I agree we need to discuss this as the current experience is inconsistent across OS. We should initiate conversation with the .NET team on this. /cc: @JonDouglas

**Comment by heng-liu** [comment]
Hi @bartonjs @vcsjones, is there any way to achieve cross-platform consistency on this matter? Thanks.
As @rido-min mentioned that, if NuGet.org repo cert, or the Microsoft author cert, or one of the intermediate certs got revoked, there will be lots of packages affected. 
Those packages will still be able to restore on Windows platform, but will not able to restore on non Windows platforms.

**Comment by bartonjs** [comment]
OpenSSL doesn't make any time comparison for revocation: https://github.com/openssl/openssl/blob/a268ed3acf16948c0e19ba67b2b3f89b3312a416/crypto/x509/x509_vfy.c#L1633-L1659

The OpenSSL project is of the opinion that a revoked certificate should not be trusted even prior to the point of revocation, because the time in the CRL is simply the time that the revocation was processed (in something like key compromise, the compromise obviously has already happened, which is why it was revoked.. but how long ago? how many things should you distrust? their answer is an easy "distrust everything").  This processing is in line with what I read in https://tools.ietf.org/html/rfc5280#section-6.3.3 (which doesn't make any mention of using the revocation time in the status calculation).

> is there any way to achieve cross-platform consistency on this matter?

I don't believe so, no.  I don't see a way to ask Windows to do the OpenSSL behavior, nor a way for OpenSSL to do the Windows behavior.

**Comment by heng-liu** [comment]
Thanks @bartonjs !
Could you explain why we could not ask Windows to do the OpenSSL behavior? Thanks.

**Comment by vcsjones** [comment]
> Could you explain why we could not ask Windows to do the OpenSSL behavior?

Revocation checking is part of chain building (this is true of any correctly implemented chain builder). Windows gives a single entrypoint in to building an X509 chain, `CertGetCertificateChain`. This API does not appear to have the flexibility to indicate that `VerificationTime` should be used for expiration and not revocation. It's either both or none.

**Comment by heng-liu** [comment]
I see. Thanks @vcsjones !
FYI @rido-min @JonDouglas @dtivel @anangaur @aortiz-msft

**Comment by heng-liu** [comment]
Close it as there seems no way to keep cross-platform consistent.
Pls let me know if there is anything we could do and reopen it. Thanks!
@rido-min @JonDouglas @dtivel @anangaur

**Comment by rido-min** [comment]
@anangaur @bartonjs @dtivel 

> The OpenSSL project is of the opinion that a revoked certificate should not be trusted even prior to the point of revocation,

If we agree with this behavior, the NuGet validation logic in Windows could refuse to install any package signed with a revoked certificate. It's not the best experience but at least is consistent across platforms.

In the case of an major issue, I'd prefer consistent behavior for the good and the bad.
