### ISSUE TITLE
SDK 3.1.401 can no longer suppress NU5104 with NoWarn 

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9948]
@iwillspeak commented on [Wed, 19 Aug 2020 12:36:47 GMT](https://github.com/dotnet/sdk/issues/12981)
We have a dependency on a package with no release build available. Building
release builds of our packages results in the NU5104 warning being issued.

Previously we were able to suppress this warning with `NoWarn="NU5104"` on
the `PackageReference`. With the `3.1.401` SDK this no longer works. The
exit status of `dotnet pack` is now 1, causing our build pipeline to fail.

A minimal reproduction is in this Gist:

https://gist.github.com/iwillspeak/2d503703a579f5623fd5e5fb410a29f1

This can be worked around by installing an older SDK (e.g. 3.1.301) in our CI
pipeline, or by removing the `<TreatWarningsAsErrors>` property.

I can't find any reference to this being a deliberate change. Is this a regression?
How can we ignore the warning / error in this case? Ideally we would still be
able to use `<TreatWarningsAsErrors>` for other warnings.

**Comment by nkolev92** [comment]
@joeloff commented on [Wed, 19 Aug 2020 22:19:46 GMT](https://github.com/dotnet/sdk/issues/12981#issuecomment-676762022)
I tried to repro this on machine with 3.1.401, but couldn't. I don't see anything obvious that would have regressed this. Have you looked at a binlog to see if the ```NoWarn``` property is perhaps getting cleared out by another target.

cc @nkolev92 in case he knows of any changes around NuGet.

Update: I can repro when I set this on the PackageReference, but if I set it only as a project property like below, it is suppressed

```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <!--<TreatWarningsAsErrors>true</TreatWarningsAsErrors>-->
    <NoWarn>$(NoWarn);NU5104</NoWarn>
    <Version>1.2.3</Version>
  </PropertyGroup>
```

**Comment by nkolev92** [comment]
@iwillspeak commented on [Thu, 20 Aug 2020 08:00:37 GMT](https://github.com/dotnet/sdk/issues/12981#issuecomment-677441587)
I've updated the Gist with a script that reproduces the change in exit code with docker containers.

On my machine running `$ ./test_script.sh ` produces output similar to:

```

with SDK 3.1.201
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 2.27 sec for /test/nu5104bug.csproj.
  nu5104bug -> /test/bin/Debug/netstandard2.0/nu5104bug.dll
  Successfully created package '/test/bin/Debug/nu5104bug.1.2.3.nupkg'.
/usr/share/dotnet/sdk/3.1.201/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Lucene.Net [4.8.0-beta00011, )" or update the version field in the nuspec. [/test/nu5104bug.csproj]
++ passed. Exit code: 0 ++

with SDK 3.1.301
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /test/nu5104bug.csproj (in 1.91 sec).
  nu5104bug -> /test/bin/Debug/netstandard2.0/nu5104bug.dll
  Successfully created package '/test/bin/Debug/nu5104bug.1.2.3.nupkg'.
/usr/share/dotnet/sdk/3.1.301/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Lucene.Net [4.8.0-beta00011, )" or update the version field in the nuspec. [/test/nu5104bug.csproj]
++ passed. Exit code: 0 ++

with SDK 3.1.302
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /test/nu5104bug.csproj (in 2.11 sec).
  nu5104bug -> /test/bin/Debug/netstandard2.0/nu5104bug.dll
  Successfully created package '/test/bin/Debug/nu5104bug.1.2.3.nupkg'.
/usr/share/dotnet/sdk/3.1.302/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Lucene.Net [4.8.0-beta00011, )" or update the version field in the nuspec. [/test/nu5104bug.csproj]
++ passed. Exit code: 0 ++

with SDK 3.1.401
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /test/nu5104bug.csproj (in 1.95 sec).
  nu5104bug -> /test/bin/Debug/netstandard2.0/nu5104bug.dll
/usr/share/dotnet/sdk/3.1.401/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(198,5): error NU5104: A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "Lucene.Net [4.8.0-beta00011, )" or update the version field in the nuspec. [/test/nu5104bug.csproj]
-- failed. Exit code: 1 --
```

**Comment by AndreyTretyak** [comment]
@nkolev92 why was this issue closed? I look like it's still a problem

**Comment by nkolev92** [comment]
@AndreyTretyak 

I accidently moved this issue twice, so I closed the one with less context. 

The issue (with a better name) is tracked in https://github.com/NuGet/Home/issues/9949
