### ISSUE TITLE
nuget install does not honor 'PackageRestoreConsent' switch

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#995]
nuget install does not honor 'PackageRestoreConsent' switch. 
Not a regression. If this switch is meaningless, should we deprecate it?

Repro steps
1. Open VS, and Tools->Options->NuGet Package Manager
2. Disable check box 'Allow NuGet to download missing packages'
3. Run 'nuget install EntityFramework -PackageRestoreConsent' from a folder

Expected:
1. Does not install the package, since, package restore consent is not available

Actual:
1. Installs the package even though package restore consent is available

**Comment by yishaigalatzer** [comment]
We should ignore the switch from VS all over, and also remove the unnecessary warning

**Comment by yishaigalatzer** [comment]
We should remove the switch for consent from nuget.exe, and ignore this setting completely

**Comment by rrelyea** [comment]
Looks fixed in 3.4.3...
"nuget.exe install -packagerestoreconsent"
returns "Unknown option: '-packagerestoreconsent"
