### ISSUE TITLE
PM UI not updating correctly after repeated upgrade and downgrade operation

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9952]
## Details about Problem
I noticed PM UI doesn't update correctly if I keep upgrading or downgrading projects. It doesn't happen all the time, but if you try long enough then you'll notice it. I included gif animation for one case. ![PMUI_DelayToUpdate2](https://user-images.githubusercontent.com/8766776/91482512-08786f80-e85b-11ea-9ab1-0888ac5e54a5.gif)
It looks it's regression for PM UI experience. All dependency files on `obj` folder was updated with updated version( and csproj too), but PMUI doesn't. But if I close and reopen PMUI then it shows correct updated version.

## Detailed repro steps so we can see the same problem

1. Please note it doesn't happen all the time you need to play sometime.

### Sample Project

I used my personal test project for this gif animation. 
https://github.com/erdembayar/MainApplicationTestSolution

**Comment by nkolev92** [comment]
Potential fix in the draft PR here: https://github.com/NuGet/NuGet.Client/pull/3595/files#diff-0ca001db736f7c81adbec4c4666b2032R47-R257

**Comment by zkat** [comment]
@JonDouglas ping so you can maybe add this to an epic for tracking similar inconsistencies/hiccups 🥇

**Comment by nkolev92** [comment]
PR out for this.

**Comment by JonDouglas** [comment]
Should we create a new project for this epic or another issue to track?

**Comment by nkolev92** [comment]
We haven't used projects much in our backlog tracking. 

Unfortunately I don't recall the context of inconsistencies. This is largely a one off right now. It was a regression due to a new feature that actually does make things more consistent :D

**Comment by nkolev92** [comment]
Low report count + inconsistent repro means this is likely not a big concern. 

Fix is in review, but will be merged in 16.9 only.
