### ISSUE TITLE
Performance: Reduce UIDelays in GetPackageSpecsAsync for Legacy projects and non PR projects

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9953]
There are plenty of UI delays causes in this codepaths that affect codepaths at initialization and more importantly restore.

There are many related issues here, so consider this an epic if necessary. 

The goal here is to reduce the impact of legacy project on all NuGet operations. 

Issues: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1168242

**Comment by nkolev92** [comment]
@srdjanjovcic not costing it right now, but given that you have VS specific knowledge I don't expect it to take too long (think less than a week for sure. It's really dependent on how many problems beyond what the UI delay data calls out you find.)

**Comment by nkolev92** [comment]
@srdjanjovcic 

Is this meant to be closed?

The PR says "partially".

**Comment by srdjanjovcic** [comment]
Nope. It was accidentally closed with PR.

**Comment by srdjanjovcic** [comment]
Thanks for noticing 🙂
