### ISSUE TITLE
Make creating NuGetProjectActions for uninstall  from PM UI a parallel operation

### ISSUE THREAD

**Issue by erdembayar** [NuGet/Home#9956]
## Details about Problem
With my PMUI performance improvement [PR#3559](https://github.com/NuGet/NuGet.Client/pull/3559) makes `Uninstall` operation 2 times faster for large solution like OrchardCore. 

Before https://gist.github.com/erdembayar/2ba554f169e4f078baa61976affa62d4  `2 min 1 seconds`.
After    https://gist.github.com/erdembayar/2f9aebfbdc78e31d229a03223c8b1888  `58 seconds`. 

But there is still room for improvement which Nikolche [pointed out](https://github.com/NuGet/NuGet.Client/pull/3559/files#r479569921).
Currently we parallelization and optimization(only 1 restore per project) both for `creating` resolved action and `executing` actions for `install` operation.
It looks I overlooked `creation` of resolved actions can be parallelized too.  Above 2 times faster speed gain mostly comes from  parallelization and optimization(only 1 restore per project)  for `executing` actions for `uninstall` operation. Missing part is parallelization  for `create action` part now.
Details: When we uninstall package from solution there 2 stages. First `create uninstallActions`, then `execute uninstallActions` . 
We already optimized `execute uninstallActions` part so it's at least 2 times faster for large solutions like `OrchardCore`, but I missed optimizing `create uninstallActions` part and I just implemented it.

### Result
With this optimization has clear benefit for .Netcore projects. OrchardCore solution get **additional** boost, now it's another **2 times faster**, almost **50% reduction in runtime**.  Just compare with all of current improvement efforts it was [2 min 1 sec](https://gist.github.com/erdembayar/2ba554f169e4f078baa61976affa62d4)  2 months ago, but now it's **30-35 second range consistently 😄** , **total 4 times faster now**.

---------------------------------------------------------------------------------
Below are **new** measurements after adding improvement for evaluate dependency graph only once. 
If you compare with previous improvement measurements I can see extra few seconds improvements now.
**OrchardCore (158 projects) 
Before optimization:**
[1 min 10 sec](https://gist.github.com/erdembayar/6d575837cc44d5eacc07387d823638fd)
[1 min 11 sec](https://gist.github.com/erdembayar/fe7489ab08f058d9bf8b43b54d9af015)
[1 min 14 sec](https://gist.github.com/erdembayar/3c756f0c6aac4e80e8c15eee26eeddc9)
**After optimization:**
[30 sec](https://gist.github.com/erdembayar/cdf0c94f863afcb25dc75f812753a746)
[35 sec](https://gist.github.com/erdembayar/83b99ffdf9746c2116896699c4bf36aa)
[34 sec](https://gist.github.com/erdembayar/55ee7d377bcf9431045174c4b0782703)

**SmallNetCoreProject(4 projects)
Before optimization:**
[1.32 sec ](https://gist.github.com/erdembayar/c29a0f543a4bdd8da0637b0f2c35b39e)
[1.01 sec](https://gist.github.com/erdembayar/e97f50de18733c23515a028bb226d874)
**After optimization:**
[0.35 sec](https://gist.github.com/erdembayar/57f6c50449de1b562f4cf909c5b65964)
[0.72 sec](https://gist.github.com/erdembayar/0be0a61a38fd72a64a8f8951f65151e4)

**Comment by erdembayar** [comment]
@nkolev92 
I already tried to do same thing for [Issue9955](https://github.com/NuGet/Home/issues/9955) then discovered always `projectContext` or `solutionContext` are blockers. Please check my efford [PR3646](https://github.com/NuGet/NuGet.Client/pull/3646) for details. Even we get negligible gain it adds more uncertainty due to those parameters are passed along many functions. Always impossible to track down all usage and prevent from `deadlocks` in the future due to parallelization. I prefer not to do it since we can't prevent from mutations happening those `contexts`.

Look here:
https://github.com/NuGet/NuGet.Client/blob/9f9870a6b47f7918524d68e52ce21c422ce1af12/src/NuGet.Clients/NuGet.PackageManagement.UI/Actions/UIActionEngine.cs#L860-L861

**Comment by nkolev92** [comment]
We discussed this during our 1 on 1. 

The parallelization here should focus on parallelizing the restore part of the whole operation, similar to what https://github.com/NuGet/NuGet.Client/pull/3559 did for install/update.

**Comment by erdembayar** [comment]
@nkolev92  @dtivel addressed all review comments.
