### ISSUE TITLE
[Test Failure]Error “Unable to load the service index for source https://apidev.nugettest.org/v3-index/index.json” occurs after switching package source

### ISSUE THREAD

**Issue by v-longmin** [NuGet/Home#9958]
## Details about Problem
VS Version: Main\30430.19
OS Version: Windows-10-Enterprise-RS5.
NuGet Version: Dev\5.8.0.6801

## Installations
1. Install VS: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4024945&view=ms.vss-build-web.run-extensions-tab
2. Install NuGet: \\ddfiles\drops\NuGet\Drops\CI\NuGet.Client\dev\5.8.0.6801\artifacts\VS15\NuGet.Tools.vsix

## Detailed repro steps 
1.  Launch Visual Studio 2019 preview.
2.  Create a new C# Class Library (.Net Framework) project.
3.  Add a deprecated package source: https://apidev.nugettest.org/v3-index/index.json.
4. Click “Browse” tab.

## Expected
All packages can be loaded successfully.

## Actual
Error “Unable to load the service index for source https://apidev.nugettest.org/v3-index/index.json” occurs after switching package source as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/91703960-8fa44b00-ebad-11ea-855d-9748976dd4cf.png)

## Error Message
Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error |   | [Package source]   Unable to load the service index for source   https://apidev.nugettest.org/v3-index/index.json.  An error occurred while sending the   request.  The underlying connection was   closed: Could not establish trust relationship for the SSL/TLS secure   channel.  The remote certificate is   invalid according to the validation procedure. |   |   |   |  

## Note
Suspect it is the NuGet Server issue since it repro before installing the NuGet with the impilicit NuGet Client build "Dev\6.8.0.6783", but didn't repro on VS Main\30423.24 + NuGet Client Dev\5.8.0.6783.

**Comment by zkat** [comment]
@rrelyea Could you take a look at what this might be pointing to? See discussion on Teams, because this might just be a server-side issue, potentially, but it also might be something wrong with our TLS.

See also: https://github.com/NuGet/NuGet.Client/pull/3618#issuecomment-683538702

**Comment by rrelyea** [comment]
apidev had a cert expired. NUget server team are working to fix now. per @agr

**Comment by zivkan** [comment]
@v-longmin The package NuGet.Core on nuget.org (production) is marked as deprecated, so you can probably update your test instructions to use that package, and avoid using dev/test server environments.

**Comment by v-longmin** [comment]
@zivkan Thanks for your reminder. We have updated our deprecated test case.
