### ISSUE TITLE
An error “cannot find an instance of the NuGet.VisualStudio.IVsProjectAdapter service” occurred when installing a PackageReference package into a renamed .NET Framework project 

### ISSUE THREAD

**Issue by v-luzh** [NuGet/Home#9959]
## Details about Problem
NuGet version: NuGet Client Dev\5.8.0.6801
VS Version: Main\30430.19
OS: Windows-10-Enterprise-RS5
## Detailed repro steps
1. Create a non-.Net SDK-style project [e.g. C# Class Library (.NET Framework)] in VS—named ClassLibrary.
2. Open the PM UI of the project and rename the project (renamed ClassLibraryFw) in Solution Explorer (you can see the PM UI window name had updated automatically to ClassLibraryFw).
3. Back to the PM UI and install a package with PackageReference format.
## Expected
No error occur.
## Actual
Error “cannot find an instance of the NuGet.VisualStudio.IVsProjectAdapter service” occurred as below.
![image](https://user-images.githubusercontent.com/20632625/91719491-ff273400-ebc7-11ea-8456-ce7e5a929b61.png)
## Error Info:
`Microsoft.Assumes+InternalErrorException: Cannot find an instance of the NuGet.VisualStudio.IVsProjectAdapter service.   at Microsoft.Assumes.Fail(String message)   at Microsoft.Assumes.Present[T](T component)   at NuGet.PackageManagement.VisualStudio.NuGetProjectFactory.<CreateNuGetProjectAsync>d__9`1.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at NuGet.PackageManagement.VisualStudio.VSSolutionManager.<UpgradeProjectToPackageReferenceAsync>d__113.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at NuGet.PackageManagement.UI.NuGetUI.<UpdateNuGetProjectToPackageRef>d__10.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at NuGet.PackageManagement.UI.UIActionEngine.<CheckPackageManagementFormat>d__14.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()`
## Notes:
1.	It does not repro when installing a packages.config package in step3.
2.	It seems a legacy issue, repro on D16.7\30330.147 with implicit NuGet Client Release-5.7.x\5.7.0.6726.

**Comment by heng-liu** [comment]
I couldn't repro with the following:
internal preview channel: VS 16.8.0 Preview 3.0 [30431.6.main](latest dogfooding) + NuGet Client Dev\5.8.0.6801
public preview channel : VS 16.8.0 preview 2.1 + NuGet Client Dev\5.8.0.6801

Hi, @v-luzh could you help check if it still repro on latest VS? Thanks!

**Comment by v-luzh** [comment]
Hi @heng-liu , I still can repro on main\30431.43 + NuGet Client Dev\5.8.0.6801 as below screenshot.
![image](https://user-images.githubusercontent.com/20632625/91798990-b8cde580-ec58-11ea-9729-4982f5585b34.png)

**Comment by heng-liu** [comment]
Thanks! I could repro now.
Previously, I didn't open PMUI before renaming the project, so I didn't repro.

**Comment by rrelyea** [comment]
@aortiz-msft  - test seems to say that this is not a regression in 16.8. Broken in 16.7 too.

**Comment by heng-liu** [comment]
Yes, this is a legacy issue. I could even repro on 16.6.0.

**Comment by v-luzh** [comment]
Yes, it repro on D16.5\29905.175 (16.5 GA).

**Comment by erdembayar** [comment]
@nkolev92  @aortiz-msft 
Is it compatibility tenet issue?

**Comment by v-luzh** [comment]
It is fixed om Main\33912.166 + NuGet Client Dev\6.8.0.22, so I will close it. Thanks.
