### ISSUE TITLE
nuget update does not delete old versions of packages from packages directory

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#996]
nuget update does not delete old versions of packages from packages directory
Maybe  a regression

Repro steps
1. Create a net45 console application A
2. Install WindowsAzure.Storage -version 4.0.0
3. Open and check that the packages folder has WindowsAzure.Storage.4.0.0 and its dependents
4. Run 'nuget.exe update A.sln'
5. After it is successful, check the packages folder again

Expected:
1. Older versions of packages, like WindowsAzure.Storage.4.0.0 are not found

Actual:
1. Older versions of packages, like WindowsAzure.Storage.4.0.0 are found

**Comment by nick-schultz** [comment]
Any update on this ticket?  I am experiencing the behavior as well, however I am using a packages.config.

**Comment by bjorn-ali-goransson** [comment]
Me too. Using packages.config. But only sometimes, or in some solutions it seems.

**Comment by Lechus** [comment]
nuget 3.4.4

**Comment by nkolev92** [comment]
I could not repro this. 
Lots of changes have happened since this issue was created.

If anyone has a reliable repro, please create a new issue, sharing that.

**Comment by rmed1na** [comment]
I'm still experiencing this same issue: NET Framework v4.8
