### ISSUE TITLE
Use 'https://' when adding new package source through Visual Studio options

### ISSUE THREAD

**Issue by ChrisMaddock** [NuGet/Home#9974]
## Details about Problem

NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe): VS UI

NuGet version (x.x.x.xxx): 5.4.0

VS version (if appropriate): 16.4.4

OS version (i.e. win10 v1607 (14393.321)): win10

Worked before? If so, with which NuGet version: n/a

## Detailed repro steps so we can see the same problem

When adding a new package source through the VS UI - placeholder text is provided. This text uses http however, whereas most prominent feeds now use https. Propose changing this to https, to minimise the overtyping required.

![image](https://user-images.githubusercontent.com/4837132/91876596-c5f8cd80-ec74-11ea-8d20-57f9ea4e2259.png)

**Comment by zivkan** [comment]
@ChrisMaddock thanks for the contribution!  This should make it into VS 16.8 before it reaches GA
