### ISSUE TITLE
NuGet.Client should replace using of ManagedImageMonikers with KnownMonikers

### ISSUE THREAD

**Issue by davkean** [NuGet/Home#9977]
NuGet.VisualStudio.Implementation uses 3 icons from ManagedImageMonikers. These should be replaced with KnownMonikers equivalents to make sure that they pick up the icon refresh.

ManagedImageMonikers.ReferencePrivate -> KnownMonikers.ReferencePrivate
ManagedImageMonikers.Application -> KnownMonikers.Application
[Blocked] ManagedImageMonikers.NuGetGrey -> KnownMonikers.PackageReferencePrivate

The first two icons can be found in Microsoft.VisualStudio.ImageCatalog, 16.8.30431.43-pre. The latter is being worked on and will be available soon.

These APIs will be deleted from the dll in a future update: https://github.com/dotnet/project-system/pull/6570.

**Comment by donnie-msft** [comment]
Will try to knock this out with my current icon refresh work https://github.com/NuGet/Home/issues/5937

**Comment by donnie-msft** [comment]
build/packages.targets may need the following update?
`<VSFrameworkVersion>16.8.30523.219</VSFrameworkVersion>`

similar recent changes:
https://github.com/NuGet/NuGet.Client/commit/156230a57ee2c7f425dec377689b8d16d31b480b
https://github.com/NuGet/NuGet.Client/commit/e3c62df98bec2b6232c0cec93cb60b5fa1d9aa95

**Comment by donnie-msft** [comment]
Blocked until 16.8 packages are released publicly

**Comment by davkean** [comment]
@donnie-msft You can consume VS packages from the public feeds without needing them to be published to NuGet: https://pkgs.dev.azure.com/azure-public/vside/_packaging/vssdk/nuget/v3/index.json and https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-impl/nuget/v3/index.json.

**Comment by donnie-msft** [comment]
@davkean yes, but our repo pins those versions with a variable, so then other dependencies aren't yet available. 
Example: `Unable to find package Microsoft.VisualStudio.Utilities with version (>= 16.8.30523.219)`
The latest version available is 16.8.30323.125, which doesn't meet the minimum you mentioned: 16.8.30431.43-pre.

**Comment by davkean** [comment]
@donnie-msft We plan on deleting this type in 16.9. All monikers are now in KnownMonikers. Please either replace all usage, or copy the type itself into the NuGet tree.
