### ISSUE TITLE
NuGet.exe config: Adding source to local config file does not work

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#998]
NuGet.exe config: Adding source to local config file does not work. Not a regression

**Comment by deepakaravindr** [comment]
I have verified that this bug has been fixed by using `nuget.exe sources add -Name blahSource -Source c:\packages -ConfigFile NuGet.config`

**Comment by maximvsidorenko** [comment]
The issue is still reproducible on nuget.exe downloaded from https://www.nuget.org/nuget.exe (version 2.8.6)

**Comment by zhili1208** [comment]
Can you try version 3.3? you can download the latest version from NuGet.org homepage. thanks

**Comment by maximvsidorenko** [comment]
Looks like it is ok to use 3.3. But I want to emphasis that version placed here  https://www.nuget.org/nuget.exe contains bug.

**Comment by csharpfritz** [comment]
The nuget.org/nuget.exe is a legacy version that is no longer updated.  We
have relocated command-line builds to http://dist.nuget.org/index/html
where all binary client versions are maintained going forward.  This new
structure also allows us to be able to keep other clients for other
operating systems when they are ready.

You can always grab the latest command-line for Windows at:
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

**Comment by maximvsidorenko** [comment]
Thanks, Jeffrey
