### ISSUE TITLE
Dependency question - lowest available version - do not downgrade

### ISSUE THREAD

**Issue by mcgurdan** [NuGet/Home#9983]
Hi all, 

I have a package with lots of different dependencies and I specify the version for each dependency. Is there a way to write the version in my metadata so that the dependency will pick the lowest available option or exact version without causing a downgrade?

Thanks!

**Comment by rrelyea** [comment]
If you are doing this via PackageReference, you are likely requesting a feature debated in issue: https://github.com/NuGet/Home/issues/5553
