### ISSUE TITLE
Restore operations that throw due to a project not being loaded are reported as `NoOp` in telemetry

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9985]
Found this while investigating solution load. 

Repro steps: 

* Open NuGet.sln with latest VS (not latest NuGet, cause some of the dragons are gone there). 

Observe: Error occurred while restoring NuGet packages: The operation failed as details for project Test.Utility could not be loaded.

In telemetry, this event is reported as no-op, which is sort of incorrect. 
It's more of a skipped/failed restore. 
We should think about how we want reason about these events. 

cc @dominoFire @aortiz-msft 

There are some queries we can do to understand the number of misrepresented events. It'll be nice to fix in 16.8

**Comment by nkolev92** [comment]
@dominoFire Please chat with me when you get to this. I did some initial investigation and I had some learning that I can share with you.

If I get some time before that I might just show you the data here.

**Comment by nkolev92** [comment]
@dominoFire [link](https://dataexplorer.azure.com/clusters/ddtelinsights/databases/DDTelInsights?query=H4sIAAAAAAAAA+2STW/bIBjHz/GnQDk1U8TA5gH7kFO6Vb60VZP1GiH8pGFyIDJYrap++NnO5HSSpfaw28YJ9H95EPy29n53bfWT8yFas7ttnzDuHjBE3+hovSvd3jfHYZu8kecDNkjKULqIjdM1Wa3IXtcBR2190M5hXVa9NH+0odX1JraV9ZRL+oA16oDz0T7MuzvhedjGt43BIVkeT7U1Nl6s317wEZvQ2UiIuonh2cYDmXetqjfhS0RXdYU3GO8bbzAErDZRxzaQ1XnO+dR5Q3s86sa+dvP93WllfOui3V9NZ7vL9K75gnzhjFFGvpIhcLVYkoS8W5vWGMQKq48LR+vHrd+1rT9TefZN9f1Rt9bOYP2pxtE6UZokicwpA16oPJcZqDxTs1TSAiAFkYKSABnwmaASeJpBwQUUKRQzRjPBIWOFFFxlMk+5SpLtvwGh3fevPYJ4QYvoPtTtusxPNDGs+1fudTZIP05bf60j/pYv6nL89+V7xBf/Gf8rjEtB00wogAJkoZiQU4jnVMhcQN6hnDIGDKYY/wWIZ5IpZwUAAA==
)

Before fix:
NoOp, Succeeded, Failed, Cancelled
68.05197886357837    26.955254257655351    4.65123591459259    0.34153096417368217

After fix:
NoOp, Succeeded, Failed, Cancelled
64.23475595697046    26.955254257655351    8.468458821200505    0.34153096417368217

**Comment by dominoFire** [comment]
I did a test solution with multiple projects; one of them with invalid PackageReference data. Then, I opened the solution in VS and it was reported as a No-Op.
