### ISSUE TITLE
NuGet PMC memory usage - invest whether tool window DontForceCreate is an option

### ISSUE THREAD

**Issue by nkolev92** [NuGet/Home#9987]
Child of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1167790. 

If the PMC is visible when VS shuts down, when VS starts, it's loaded even with no solution loaded. 
This 75 M memory penalty is incurred even if user never uses the PMC  in that session.
Please lazily initialize and DontForceCreate. This will reduce the penalty for many sessions with very little change.

PMC: When PMC is loaded because the last time VS closed, PMC was open: 
https://docs.microsoft.com/en-us/visualstudio/extensibility/registering-a-tool-window?view=vs-2019

old link: https://social.msdn.microsoft.com/Forums/en-US/c53609dc-9146-4d82-a6c1-281eb960d243/how-to-hide-a-toolwindow-next-time-vs-starts-up

**Comment by erdembayar** [comment]
@aortiz-msft  @nkolev92 
This change makes PMC doesn't open when you re-open solution next time.
So it's change of user experience. What do you think should be go ahead with this one or not?

**Comment by aortiz-msft** [comment]
Let's not change the user experience for now. Thanks for the investigation!

**Comment by erdembayar** [comment]
@nkolev92 @aortiz-msft 
Thank you for your input. I'll close this now since we don't want this change.
