### ISSUE TITLE
`RuntimeEnvironmentHelper.IsRunningOnVisualStudio` performance issue on Mono

### ISSUE THREAD

**Issue by Therzok** [NuGet/Home#9989]
## Details about Problem

NuGet product used - NuGet IDE support in VSMac

NuGet version (x.x.x.xxx): 5.8.0-preview.3.6783

OS version (i.e. win10 v1607 (14393.321)): mono, macOS 10.15

## Detailed repro steps so we can see the same problem

1. NuGet implicitly calls `IsRunningInVisualStudio` in the `IsMono` check [here](https://github.com/NuGet/NuGet.Client/blob/e97d556a83750bb4f8017e3640bc699d04832657/src/NuGet.Core/NuGet.Common/RuntimeEnvironmentHelper.cs#L62), which then queries the BCL for the current process.

2. On mono, the first time initialization of Process.MainModule takes a long time, and it adds a few seconds to loading a solution in VSMac.

See sample trace here: https://gist.github.com/Therzok/9b2e09655e75aa0c4eeec25cc8df2123

This could be work-around by only querying `IsRunningInVisualStudio` on `Windows`, as VSMac does not have any `DEVENV` or `BLEND` processes it uses.

**Comment by zivkan** [comment]
Thanks for the contribution @Therzok. We're very close to branching for 5.9, so I'm not entirely sure if this will make it in NuGet 5.8 or NuGet 5.9 at this time. It depends which commit the eventual release branch gets created from.
