### ISSUE TITLE
nuget verbosity option never shows detailed log

### ISSUE THREAD

**Issue by deepakaravindr** [NuGet/Home#999]
nuget verbosity option never shows detailed log

**Comment by zhili1208** [comment]
this is not regression, 2.8.X has same issue. For install and restore, log with verbosity is same as log without verbosity. some commands don't have much log.

**Comment by yishaigalatzer** [comment]
I believe this was fixed at least for the XPLAT, if it wasn't for command line please move to 3.5, otherwise close

**Comment by joelverhagen** [comment]
This is fixed for Xplat and Command Line. I verified by adding test verbose log statements to all commands (based on https://github.com/NuGet/NuGet.Client/commit/f489a21dbb40706c4b8ac436e5462828feb9d1d5).
